### ISSUE TITLE
CopySpec output entries deduplication doesn't work in all cases

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#10005]
`CopySpec` output entries deduplication doesn't work in all cases. It's not that apparent on `Copy` or `Sync` as it will simply overwrite files. But it is very apparent when creating archives such as ZIP files that ends up having duplicated entries.

### Expected Behavior

`CopySpec` to always deduplicate output entries

### Current Behavior

Let's say we have an `input` directory that contains a `some.txt` file.

And a `Zip` task declared as follows:

```kotlin
tasks.register<Zip>("someZip") {
    from("input")
    from("input")
    destinationDirectory.set(layout.buildDirectory)
    archiveBaseName.set("some-zip")
}
```

Then the archive content doesn't include duplicated entries:

```
Archive:  build/some-zip.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        4  07-18-2019 14:54   some.txt
---------                     -------
        4                     1 file
```

However, the following produces a zip with duplicated entries:

```kotlin
tasks.register<Zip>("someZip") {
    from("input")
    from("input") {
        exclude("none")
    }
    destinationDirectory.set(layout.buildDirectory)
    archiveBaseName.set("some-zip")
}
```

```
Archive:  build/some-zip.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        4  07-18-2019 14:54   some.txt
        4  07-18-2019 14:54   some.txt
---------                     -------
        8                     2 files
```

### Context

See #9990

### Steps to Reproduce 

See above

### Your Environment

Gradle 5.5.1

**Comment by paplorinc** [comment]
It seems to me [this is a feature](https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy#L709) with [a simple, but unintuitive fix](https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/bundling/ArchiveIntegrationTest.groovy#L723).
The same is true for zip files  - though we may want to invert the defaults.

**Comment by wolfs** [comment]
Let's not fix deduplication right now.
