### ISSUE TITLE
ImmutableList is not deserialized correctly using instant execution

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#10009]
When using instant execution, the following example will not be deserialized correctly:
```
data class TaskData(val data: ImmutableList<String>?)

abstract class MyTask : DefaultTask() {
  private val taskData = TaskData(ImmutableList.of("sample"))
}
```
Although instances of `TaskData` are serialized correctly, when deserializing, `TaskData.data` will be `null`. The reason is that the `listCodec` always creates instances of [`ArrayList`](https://github.com/gradle/gradle/blob/06f8c2e7b26f81a658cc74313fb5a0a1ee8b6ce6/subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/Combinators.kt#L199) which are not assignable to field with `ImmutableList` type.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/10069
