### ISSUE TITLE
Gradle 3.2.1 - Caused by: org.gradle.api.InvalidUserDataException: A dependency must not be empty

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#1000]
When upgrading from Gradle 3.1 to Gradle 3.2.1, `Caused by: org.gradle.api.InvalidUserDataException: A dependency must not be empty` was thrown.

Here is my build: https://github.com/jaredsburrows/cs-interview-questions.

I believe the issue is with `cunit-test-suite` or `google-test-test-suite` plugins.

### Expected Behavior
No exception, this was not happening in Gradle 3.1

### Current Behavior
Exception

### Context
Simply upgrading Gradle 3.1 to Gradle 3.2.1

### Steps to Reproduce (for bugs)
Upgrade Gradle 3.1 to Gradle 3.2.1

### Your Environment
 * Build scan URL: https://gradle.com/s/xb2zvlsiuwflc
 * Build failure: https://travis-ci.org/jaredsburrows/cs-interview-questions/jobs/183049338

**Comment by lacasseio** [comment]
Thanks @jaredsburrows, I will triage this as soon as possible.

**Comment by bmuschko** [comment]
Thanks for reporting. This will be fixed with 3.3-RC1.

Internal code review: https://code-review.gradle.org/cru/REVIEW-6408

**Comment by jaredsburrows** [comment]
@bmuschko Since you all moved issues to Github, can you all move code reviews to Github so users can view them?

**Comment by bmuschko** [comment]
@jaredsburrows We partially already did that. BTW: The "internal" are actually public.

**Comment by jaredsburrows** [comment]
@bmuschko I cannot login and I see no sign up.

**Comment by bmuschko** [comment]
@jaredsburrows Never mind then. I thought you could simply create an account and view it.

**Comment by eriwen** [comment]
@jaredsburrows We're working on migrating to GitHub reviews where we can. I agree that these should be more open.

**Comment by jaredsburrows** [comment]
@bmuschko @eriwen Thanks! This is good to hear!
