### ISSUE TITLE
Make project.exec available in task action with instant execution

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#10000]
In the Android Gradle plugin, we use `Project.exec` for tasks like AIDL processing, Renderscript processing, stripping debug symbols from native libs etc. With instant execution it is not possible to use this API any more.

**Comment by eskatos** [comment]
https://github.com/gradle/gradle/pull/10461 introduced a `ExecOperations` service for that purpose.
It'll ship with Gradle 6.0.
You can try it out starting with nightly 6.0-20190906220037+0000
