### ISSUE TITLE
Init scripts for buildSrc should have access to gradle.properties

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#1001]
Currently, when having an init script in the Gradle user home directory which uses system properties from a `gradle.properties` in the Gradle user home dir then these are not available when applying the init script to `buildSrc`. Note that these only happens when using the standalone `gradle` command, when using the wrapper then this works.

### Expected Behavior
`gradle.properties` in the Gradle user home are always available to init scripts.

### Current Behavior
When using the `gradle` executable then system properties defined in `gradle.properties` are not available to init scripts applied to `buildSrc`.

### Context
I ran into this issue when using [remoteHttpCacheInit.gradle](https://github.com/gradle/gradle/blob/5b2d6c617896bce058fd2f306eae7e3e23b1ab9a/gradle/remoteHttpCacheInit.gradle) from my Gradle user home. I built a new Gradle version and tried to use that distribution to build Gradle itself.

### Steps to Reproduce (for bugs)

See the failing integration test [here](https://github.com/gradle/gradle/blob/2a4b973481ed90db4ce13f88fad0b1eaf5bc0df1/subprojects/launcher/src/integTest/groovy/org/gradle/launcher/BuildEnvironmentIntegrationTest.groovy#L227-L246).

**Comment by wolfs** [comment]
This is related to the inconsistent behavior here: https://github.com/gradle/gradle/issues/1055.

**Comment by adammurdoch** [comment]
We should avoid any changes that make `buildSrc` more different to the child builds of a composite build, as we want to converge here not diverge. If we make this change, then we should consider whether it also makes sense for child builds (it might).

**Comment by wolfs** [comment]
`GradleWrapperMain` loads `gradle.properties` here: https://github.com/gradle/gradle/blob/3ccc368a2684a34cd01ed58e0b1798e4f50de5c6/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleWrapperMain.java#L56-L56.
After doing that it calls `GradleMain.main`. When running the standalone `gradle` executable, `GradleMain.main` is called directly. This is why the properties are present when using the wrapper and are not when using the standalone executable.

**Comment by wolfs** [comment]
When fixing this we should probably consider fixing #985.

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/16757
This will be in Gradle 7.1
