### ISSUE TITLE
Gradle not sync error on android studio

### ISSUE THREAD

**Issue by Revanth1032** [gradle/gradle#10028]
### Your Environment

Build scan URL:

**Comment by Revanth1032** [comment]
Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

**Comment by blindpirate** [comment]
We can't help you if you provide nothing other than a single line. You need to at least provide:

- The environment (JDK/OS)
- The gradle version
- The AS version
- Steps to reproduce

A reproducible sample project would be best.
