### ISSUE TITLE
Model reference $. syntax does not work in project scope

### ISSUE THREAD

**Issue by dmfalk** [gradle/gradle#1002]
$. syntax, used to reference the model, cannot be used with project scope.
Affects release versions of gradle.

### Expected Behavior
$. syntax should be scope agnostic.

### Current Behavior
Generates error:

> Invalid variable name. Must include a letter but only found: $. At ...

### Context

Reported on the forum: https://discuss.gradle.org/t/syntax-within-project-scope/19771
Original Bug: https://issues.gradle.org/browse/GRADLE-3570

Found whilst working on a multi-project build. Nominal work around is to "apply from" script the build logic ( non-project scoped ) into the project scope. Whilst this works to some extent, there are further issues when upgrading wrapper ( for example ).

### Steps to Reproduce (for bugs)

Readily and easily reproducible:
Take the simple example from the variant docs1 as a base:
```
model {
    tasks {
        buildAllExecutables(Task) {
            dependsOn $.binaries.findAll { it.buildable }
        }
    }
}
```
This works just fine. 
Now embed the same code within a multi-project, single build script situation i.e
```
project(':bob') { // <-- this bit's new
model {
    tasks {
        buildAllExecutables(Task) {
            dependsOn $.binaries.findAll { it.buildable }
        }
    }
}
} // <-- this bit's new
```
and you get the error:

> build file 'test.gradle': 12: Invalid variable name. Must include a letter but only found: $. At [12:23] @ line 12, column 23.
> dependsOn $.binaries.findAll { it.buildable }

**Comment by alexgeek** [comment]
Any updates on this in recent versions?

**Comment by dmfalk** [comment]
Remains an issue in 3.3 and 3.4-rc-2

**Comment by lacasseio** [comment]
This will likely stay an issue for the next couple release as it was never supported. To work around this issue, I suggest you have a look at [`RuleSource` plugins](https://docs.gradle.org/current/userguide/software_model.html#sec:rule_sources).

**Comment by prokod** [comment]
@lacasseio Could you please elaborate on the suggested work around using RuleSource?

**Comment by lacasseio** [comment]
The equivalent of `RuleSource` plugin of the code example of this issue is the following. It's a bit more verbose but it's also more stable.
```
class YourCustomRulePlugin extends RuleSource {
    @Mutate
    void createBuildAllExecutablesTask(ModelMap<Task> tasks, BinaryContainer binaries) {
        tasks.create('buildAllExecutables') {
            dependsOn binaries.findAll { it.buildable }
        }
    }
}

apply plugin: YourCustomRulePlugin
```
