### ISSUE TITLE
Applying the kotlin-dsl plugin without any repositories should provide a helpful error message

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#10020]
Currently if you apply the `kotlin-dsl` plugin, e.g. in a `buildSrc` project, and add a Kotlin class or pre-compiled script plugin, it fails with a cryptic error message.

### Expected Behavior

Ideally, from a user's perspective, putting the following into `buildSrc/build.gradle.kts` should simply work:

```kotlin
plugins {
    `kotlin-dsl`
}
```

### Current Behavior

While we tell users that they need to define a repo from which to get the Kotlin compiler in the [documentation](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin), the error message is rather cryptic:

```
Could not resolve all files for configuration ':kotlinCompilerPluginClasspath'.
> Could not find org.jetbrains.kotlin:kotlin-sam-with-receiver:1.3.31.
  Required by:
      project :
```

### Context

The error message was not immediately actionable for me and thus I think users might feel the same way. So one option would be to make that clearer, in particular if no repositories have been specified at all.

For a `buildSrc` build, we could reuse the repositories from the root build script unless it defines custom ones. 🤔 

### Steps to Reproduce 

Run `gradle build` in https://github.com/marcphilipp/gradle-sandbox/tree/master/kotlin-dsl-plugin

### Your Environment

Build scan URL: https://scans.gradle.com/s/4cdky2gt45dlm/

**Comment by eskatos** [comment]
This is the generic dependency resolution error message one gets when declaring dependencies without repositories, or with repositories where some dependency cannot be found.

I'm not sure we want to special case the `kotlin-dsl` plugin use case. Maybe this is more about turning that generic error message into an actionable help message.

**Comment by marcphilipp** [comment]
When I encountered the error, I was a bit confused at first because I normally don't expect a plugin to require certain repositories and, despite knowing `buildSrc` is a separate build, even less so in a `buildSrc` project where I already configured repos in the root build script.

If we end up improving the generic error message, I think that would be a good outcome. 🙂

**Comment by bamboo** [comment]
I vaguely recall a discussion we had about actionable error/help messages in a previous World Meeting. One of the ideas floating around was to allow plugins to elaborate on build failures and provide better messages to the user.

In this particular case, say the `kotlin-dsl` plugin was able to provide a `BuildFailureElaborator` service that would be given a chance to analyse the build failure `Could not resolve all files for configuration ':kotlinCompilerPluginClasspath'` and return an actionable message: 

> The `kotlin-dsl` plugin requires additional Kotlin compiler dependencies to be resolved but no repository was defined, please add a repository to the project.

**Comment by big-guy** [comment]
> This is the generic dependency resolution error message one gets when declaring dependencies without repositories, or with repositories where some dependency cannot be found.

At least for the "no repositories" case, you should get a "Cannot resolve external dependency _foo_ because no repositories are defined."  Are there some dependencies defined in this case?

**Comment by marcphilipp** [comment]
The buildscript contains only the plugins block, no dependencies defined:
https://github.com/marcphilipp/gradle-sandbox/tree/master/kotlin-dsl-plugin

However, it looks like the plugin defines an [Embedded Kotlin Repository](https://scans.gradle.com/s/4cdky2gt45dlm/dependencies/repositories?repoToggled=W1swXV0#focusedRepository=embedded-kotlin-repository) which is probably why the "no repos"  error message isn't showing.

**Comment by devmike01** [comment]
Unfortunately, this issue has not been fixed on gradle `5.6.4`. I got the same cryptic error message today while trying to use Kolin DSL, and I was so confused until I stumbled on this issue page through gradle Github repository. Though I have fixed the bug, I believe something should be done to give accurate information on what really went wrong.
```
Execution failed for task ':buildSrc:compileKotlin'.
> Could not resolve all files for configuration ':buildSrc:kotlinCompilerPluginClasspath'.
   > Could not find org.jetbrains.kotlin:kotlin-sam-with-receiver:1.3.41.
     Required by:
         project :buildSrc

```
For those having this same issue, just add `repository` to your `build.gradle.kts` file. Like this:
```
repositories{
    jcenter()
}
```

**Comment by eygraber** [comment]
My buildSrc's build.gradle.kts looks like this:

```
plugins {
  `kotlin-dsl`
}

repositories {
  jcenter()
}
```

And I'm still getting this error:

```
Could not determine the dependencies of task ':compileKotlin'.
> Could not resolve all files for configuration ':kotlinCompilerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.72 because no repositories are defined.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by devmike01** [comment]
Clean your project. Delete the `.gradle` and `build` folders and then rebuild your project. If that doesn't work, close your project and remove it from recent projects. Then open it back and let it build by itself.

**Comment by eygraber** [comment]
That worked

**Comment by tprochazka** [comment]
I have the same error

```
Could not determine the dependencies of task ':compileKotlinMetadata'.
> Could not resolve all files for configuration ':kotlinCompilerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.72 because no repositories are defined.
     Required by:
         project :
```

I don't have jcenter()  but I'm using maven central and it is also there
https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-compiler-embeddable
Weird that there is missing project name.

**Comment by lrpaquet-jive** [comment]
We're getting this issue here with Gradle 6.8.3

```
Could not resolve compiler classpath. Check if Kotlin Gradle plugin repository is configured in project ':buildSrc'.
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':buildSrc:compileKotlin'.
Could not resolve all files for configuration ':buildSrc:kotlinCompilerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.20 because no repositories are defined.
     Required by:
         project :buildSrc
```

**Comment by Yetland** [comment]
> We're getting this issue here with Gradle 6.8.3
> 
> ```
> Could not resolve compiler classpath. Check if Kotlin Gradle plugin repository is configured in project ':buildSrc'.
> FAILURE: Build failed with an exception.
> * What went wrong:
> Could not determine the dependencies of task ':buildSrc:compileKotlin'.
> Could not resolve all files for configuration ':buildSrc:kotlinCompilerClasspath'.
>    > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.20 because no repositories are defined.
>      Required by:
>          project :buildSrc
> ```
> 
> ```
> // buildSrc/build.gradle.kts
> plugins {
>   `kotlin-dsl`
> }
> ```
just see this doc. and you will fix it.
https://docs.gradle.org/6.7.1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

**Comment by hemantsb** [comment]
Got it working by replacing `Jcenter()` with `mavenCentral()`.
<img width="578" alt="Screenshot 2021-07-17 at 5 54 59 PM" src="https://user-images.githubusercontent.com/38025210/126036911-396f6d87-2424-4ac8-b4e5-3260d6bb62d3.png">

**Comment by donat** [comment]
I've tested the scenario and the 7.4 error message is actually actionable and gives a proper link to the documentation: 
```
Execution failed for task ':buildSrc:validatePlugins'.
> Could not resolve all files for configuration ':buildSrc:compileClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 because no repositories are defined.
     Required by:
         project :buildSrc
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-reflect:1.5.31 because no repositories are defined.
     Required by:
         project :buildSrc

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I think the issue can be closed now.

**Comment by MahmoudZaherDeveloper** [comment]
If the previous fixes don't work for you and you still have an issue, use the lines below.

plugins {
    `kotlin-dsl`
}
repositories{
    mavenCentral()
}
