### ISSUE TITLE
Deadlock scheduling finalizer task on failed build

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#10033]
Occurs in version range `5.5.1..5.7-20190721220031+0000`.

Repro projects:
- https://github.com/Triple-T/gradle-play-publisher/tree/96b63a8525b80ee4aa52a8072844e8783ad10be8
- https://github.com/SUPERCILEX/issue-mcve/tree/52ae3dd651c054495bcd2f5e0f74e5390ec0fb55

Repro steps:
1. In `gradle-play-publisher`: `./gradlew publishToMavenLocal`
1. In `issue-mcve`: `./gradlew pApk`

`publishReleaseApk` will fail (as expected), but the **build will now be frozen forever**. This is because there's a finalizer task. Somehow, Gradle is deadlocking when trying to schedule the finalizer task.

**Comment by SUPERCILEX** [comment]
@big-guy this is blocking the Gradle Play Publisher `v2.3.1` release, would appreciate getting it into Gradle 5.6.

**Comment by big-guy** [comment]
@lptr @wolfs could you look at this? I don't know of any specific finalizer changes?

@SUPERCILEX I haven't tried your repro yet.  Does this happen every time?  Could you provide a thread dump for the daemon when it's hung?  Thanks!

**Comment by SUPERCILEX** [comment]
@big-guy yup, happens 100% of the time for me. Here's a [thread dump](https://github.com/gradle/gradle/files/3415636/dumps.zip). I feel like the culprit might be `File lock request listener` in `dump.txt`, but that's just a wild guess. Maybe someone never relinquished the lock?

**Comment by SUPERCILEX** [comment]
Also, [here's](https://github.com/gradle/gradle/files/3415642/logs.txt) the full output of running `./gradlew pApk --debug`. I've done some digging, but I don't see anything wrong.

**Comment by SUPERCILEX** [comment]
@lptr @wolfs have you been able to repro?

**Comment by wolfs** [comment]
@SUPERCILEX I can reproduce the problem. It seems like `commitEditForComDotSupercilexDotTest` destroys the output of `:app:publishReleaseApk` and can therefore not be scheduled since some other task still depends on the task generating the destroyed file, I guess `generateEditForComDotSupercilexDotTest`.

Currently, Gradle assumes that all task that depend on a task producing a file also consume it. Since `:app:publishApk` -> `app:publishReleaseApk` -> `generateEditForComDotSupercilexDotTest`, `:app:publishApk` blocks `:commitEditForComDotSupercilexDotTest`, since a finalizer is not considered as a dependency which can consume (and so destroy) the output.

Is the dependency/finalizer/destroys chain what you expect to happen?

**Comment by SUPERCILEX** [comment]
Hmmmm, I don't get that last part: `publish blocks commit since a finalizer is not considered as a dependency which can consume (and so destroy) the output.` Why would `commitEdit...` be blocked by `publishApk`? And why `publishApk` be assumed to consume inputs if it has no task actions? (It can't do anything with those inputs anyway.) The other weird thing is that this scenario _does_ work when nothing crashes:
```
> Task :app:publishReleaseBundleWrapper
> Task :app:publishReleaseBundle
> Task :app:publishRelease
> Task :app:publish
> Task :commitEditForComDotSupercilexDotTest
```

See for yourself by removing this line: https://github.com/Triple-T/gradle-play-publisher/blob/96b63a8525b80ee4aa52a8072844e8783ad10be8/plugin/src/main/kotlin/com/github/triplet/gradle/play/tasks/PublishApk.kt#L57. That's what I don't understand, why does crashing change the behavior?

**Comment by SUPERCILEX** [comment]
Also, I should mention that what I'm actually trying to do here is just run a task after another. If there's a better way to do that than with `finalizedBy`, please let me know.

**Comment by wolfs** [comment]
@SUPERCILEX I fixed the issue via https://github.com/gradle/gradle/pull/10232. The fix will be in Gradle 6.0. I'll ping you when I have a nightly for you to try out.

**Comment by SUPERCILEX** [comment]
Thank you! 🙏 Is 6.0 coming after 5.6?

**Comment by wolfs** [comment]
Yes.

**Comment by wolfs** [comment]
@SUPERCILEX Can you try out `5.7-20190808220314+0000` and see if the problem is fixed for you?

**Comment by SUPERCILEX** [comment]
Yaaaassss, it worked! Thank you!
