### ISSUE TITLE
Fail on duplicates when creating archives by default

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#10039]
In order to avoid JARs and TARs being flagged as "grossly invalid archives" (#9990), the default duplicate strategy should be fail.

De-incubate API:

- [x] `DuplicatesStrategy.INHERIT`

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
We ended up deprecating duplicates in archives with the default duplicates strategy in 6.0. Let's change the default strategy to `FAIL` in 6.0. See https://github.com/gradle/gradle/pull/10865.

**Comment by wolfs** [comment]
Closed via #15759

**Comment by donat** [comment]
@wolfs I see the de-incubation of `DuplicatesStrategy.INHERIT` was marked as done but the `@Incubating` annotation is still present.

**Comment by donat** [comment]
Thanks, @melix. I've marked the item as done in the spreadsheet.
