### ISSUE TITLE
kotlin-dsl multi-project: Unresolved reference when referencing plugin in subprojects

### ISSUE THREAD

**Issue by alwyn** [gradle/gradle#10056]
I am using the jib plugin from google to build docker images in a multi-project configuration. 
Now I'm trying to consolidate this configuration into the root build.gradle.kts file.

The Gradle proposed way of doing this works when using a Groovy build file, but not when using kotlin-dsl.  I have logged an [issue on JIB team github](https://github.com/GoogleContainerTools/jib/issues/1841), but we think it might be a kotlin-dsl issue since the Groovy configuration works.  I have copied the samples from that link to this issue.

### Expected Behavior
Referencing a plugin in the subprojects block of a kotlin-dsl based build file should return a usable reference.

### Current Behavior
Referencing a plugin in the subprojects block of a kotlin-dsl based build file results in an unresolved reference.

### Context
I cannot consolidate common plugin configuration for a multi-project build when using kotlin-dsl.

### Steps to Reproduce 
Please see [issue on JIB team github](https://github.com/GoogleContainerTools/jib/issues/1841)

Specific relevant comments:
[My original sample source](https://github.com/GoogleContainerTools/jib/issues/1841#issue-467490964)

Please note that the repository doesn't included the build files used in the following comments:
[Working Groovy build using JIB multi-project example from their repo](https://github.com/GoogleContainerTools/jib/issues/1841#issuecomment-511542558)

[Equivalent Kotlin-DSL build that fails](https://github.com/GoogleContainerTools/jib/issues/1841#issuecomment-511825363)

### Your Environment
Build scan URL: https://scans.gradle.com/s/gtp2am6eqviim/

**Comment by vlsi** [comment]
@alwyn , please check the documentation: https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin_using_standard_api

type-safe accessors are not generated when you apply the plugin via `apply(plugin = "com.google.cloud.tools.jib")`

If you want to use `jib...`, then you need to apply the plugin via `plugins` block.

For instance: replace top-level `id("com.google.cloud.tools.jib") version "1.3.0" apply false`  with `d("com.google.cloud.tools.jib") version "1.3.0"`

**Comment by alwyn** [comment]
After some testing I discovered the following:

When using ```plugins``` block without ```apply false``` and no ```apply(plugin...``` then I get jib extension not found.

Adding the ```apply(plugin...``` that error goes away.

I can also build a docker images when targeting a specific sub-project on the command line.

Problem is when I don't specify a specific project my expectation is for it to build images for all the sub-projects, but this fails because it is trying to build one for the root project too.

Feels like it should be possible to specify ```apply false``` and still get the expected result without the plugin being applied to the root project when using ```apply(plugin..``` in subprojects block?

**Comment by vlsi** [comment]
@alwyn , please follow the documentation.
It does clarify what to do. I'm not kidding. Really. It does.

Just use `configure<JibExtension> { ... }` syntax instead of `jib { ... }`

Your case is a very well known Gradle Kotlin DSL limitation, and your case definitely does not qualify as a bug report. That kind of questions need to be asked on StackOverflow.

**Comment by alwyn** [comment]
Yes, except that ```configure<JibExtension>``` results in Unresolved reference: JibExtension.

Thanks for the help and patience, I'll head over to StackOverflow.

**Comment by vlsi** [comment]
Do you use IDE to write build script?

You need to add  `com.google.cloud.tools.jib.gradle.JibExtension` which my IntelliJ IDEA suggests to add automatically.

**Comment by alwyn** [comment]
Just realized that, works now thanks!

**Comment by vlsi** [comment]
@alwyn , I cannot close (I'm not on a Gradle team). Would you please close the issue?

I have my own issues (e.g. https://github.com/gradle/gradle/issues/created_by/vlsi ), and I just want to increase its visibility by "closing" other ones :)
