### ISSUE TITLE
Deprecate old artifact transform API

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#10061]
---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
IIRC, we wanted to emit a deprecation warning for anybody using the `ArtifactTransform` API and remove the type/methods in 7.0.

**Comment by lptr** [comment]
OK, I renamed the issue.

**Comment by wolfs** [comment]
We should only deprecate when AGP 3.6 is out, so there is a stable version which doesn't use the old artifact tranforms API.

**Comment by wolfs** [comment]
The Kotlin plugin uses `ArtifactTransform` as well. Let's find out when they can remove the usage.
