### ISSUE TITLE
Add option to increase the number of idle duplicated daemons

### ISSUE THREAD

**Issue by lukaville** [gradle/gradle#10075]
### Expected Behavior
Add an option to change the number of idle duplicated daemons. By default, it can be set as `1`.

### Current Behavior
Currently, this strategy leaves only one the most recently used daemon (see `MasterExpirationStrategy.java`).

### Context

Since now [it is recommended](https://docs.gradle.org/current/userguide/gradle_daemon.html) to use Gradle daemon on CI machines we can benefit from running N instances of idle daemons instead of only one because usually CI agents build many projects at the same time and we can save a lot of time that we spent on starting new daemons if we have a pool of the daemons. The current strategy is not efficient for the CI agents because it kills all duplicated idle daemons except one after about 10 seconds.

This also may be useful when using Gradle to build projects remotely on one powerful machine. In this case, we need to have some pool of Gradle daemons in order to not spin them up each time.

**Comment by donat** [comment]
Hi! This seems like a little bit of an overkill. Before we do any actions, we would like to understand the situation a bit better. Did you do any measurements on the impact? How often is this a problem?
