### ISSUE TITLE
Could not find method integrationTestCompile for arguments [junit:junit] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by kyxap** [gradle/gradle#10070]
### Expected Behavior
After creation of custom source set I can't find how to set dependencies for that source type.
Based on the gradle docs it should work but it doesn't work for me.
My expectation that `test` and `integrationTest` should have different dependencies 

### Current Behavior

As for now im getting error when I try to build the project:

```bash
line: 16
A problem occurred evaluating root project 'untitled'.
> Could not find method integrationTestCompile() for arguments [{group=junit, name=junit, version=4.12}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

### Context

Want to find best way how to store `unit` and `integration` tests in the same `/src/**` folder and divide dependencies bc now `testCompile` doesn't apply to the `integration-test` 
e.g.:

![image](https://user-images.githubusercontent.com/3080529/61743770-cc670700-ad4a-11e9-869f-06d34f5435b1.png)

### Steps to Reproduce 

1) Create new project with Intellij Idea
2) Use gradle build:

full `build.gradle`

```groovy
plugins {
    id 'java'
}

group 'lalalla-test'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    integrationTestCompile group: 'junit', name: 'junit', version: '4.12'
}

configurations {
    integrationTestCompile.extendsFrom testCompile
    integrationTestRuntime.extendsFrom testRuntime
}

sourceSets {
    integrationTest {
        java.srcDir file('src/integration-test/java')
        resources.srcDir file('src/integration-test/resources')
        compileClasspath += sourceSets.main.output + sourceSets.test.output + configurations.testRuntime
        runtimeClasspath += sourceSets.main.output + sourceSets.test.output + configurations.testRuntime
    }
}
```
3) `gradle build`

### Your Environment
MacOs 10.14.5 
Gradle 5.4.1

Build scan URL:
https://scans.gradle.com/s/uxc4mgtv5kxu2

**Comment by ljacomet** [comment]
This is a declaration ordering issue.

The source set and its associated configurations are only created inside the `sourceSets` block, which is evaluated after the `dependencies` block. As the `dependencies` block cannot create configurations, the ones referenced need to exist when it is evaluated.

If you move up in your build file the `sourceSets` block, everything works as expected.

Note: you should not use `*Compile` and `*Runtime` but instead leverage the non deprecated configurations. See [documentation](https://docs.gradle.org/current/userguide/java_plugin.html#java_source_set_configurations) for details.

**Comment by ljacomet** [comment]
Closing as answered
