### ISSUE TITLE
Output with long lines and multi-byte characters displayed incorrectly

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1008]
This is migrated from [GRADLE-3329](https://issues.gradle.org/browse/GRADLE-3329), which had an [attempted fix](https://github.com/gradle/gradle/commit/1746300a) in Gradle 3.2.1.

### Expected Behavior
Output should not be garbled by Gradle regardless of line length or character encoding.

### Current Behavior
[This build](https://travis-ci.org/sormuras/beethoven/builds/183432849) demonstrates unexpected `�` characters in the output where multi-byte characters are.

### Context
Those relying on multi-byte characters for output will be affected. I expect this affects international users more significantly. 

[Original forum post](https://discuss.gradle.org/t/javaexec-task-mangles-utf-8-output/10975)
[Another forum post](https://discuss.gradle.org/t/utf-8-output-regression-or-not-fixed-or-3rd-party-problem/20667)

### Steps to Reproduce (for bugs)
Define and run the following task on a dumb terminal:
```gradle
task demonstrateBug() {
  def text = " ▓ " + ("✔" * 10) + (" a b c d e f " * 2) + ("✔" * 10) + " ▒ "
  1000.times {println text + text}
}
```

### Your Environment
This might behave differently depending on the OS and console.

**Comment by sormuras** [comment]
@eriwen It seems to be a Travis console/logging only problem. When I moved the test task into a plain shell script, like:
```bash
```
it too showed a lot of � characters in the output: � characters in the output https://api.travis-ci.org/jobs/183558479/log.txt?deansi=true
Will file an issue against Travis.

**Comment by eriwen** [comment]
Nice @sormuras! That was step one on my list for triaging this, but you kindly did that for us. Thank you again. I'll close this issue.
