### ISSUE TITLE
Idea plugin: IntelliJ in module-per-sourceset mode ignores idea.module.excludeDirs

### ISSUE THREAD

**Issue by timothybasanov** [gradle/gradle#10099]
### Expected Behavior
I expect to see `.out/extracted-include-protos/main` folder excluded in IntelliJ when I use code like this:

```groovy
apply plugin: 'com.google.protobuf'
apply plugin: 'idea'
idea {
  module {
    excludeDirs += file("${project.buildDir}/extracted-include-protos/main")
  }
}
```

So I should see this in modules:
 * `myApplication`: 
    * Content root: `.`. Excluded directories:    `.gradle`, `.out`, `out`
 * `myApplication/main`: 
    * Content root: `.out/extracted-include-protos/main`. Excluded: `.`
    * Content root: `src/main`. Source directories `java`, `proto`. Resource directories: `resources`.
    * Other content roots and modules

### Current Behavior
IntelliJ creates these modules:
 * `myApplication`: 
    * Content root: `.`. Excluded directories:
    `.gradle`, `.out`, `out`, `.out/extracted-include-protos/main`
 * `myApplication/main`: 
    * Content root: `.out/extracted-include-protos/main`. Source directories: `.`
    * Content root: `src/main`. Source directories `java`, `proto`. Resource directories: `resources`.
    * Other content roots and modules

So while the exclusion folder is added to an IntelliJ module, it's not the right module it's added to. As a result IntelliJ ignores this declaration.

### Context
IntelliJ starting 2019.2 is enforcing "one module per source set" policy. It's still possible to have an exception, but it's much harder to do this than earlier.
There is no direct support for this in an idea plugin (https://github.com/gradle/gradle/issues/9681), so edge cases are expected.
In this particular case when using both a protobuf plugin and an idea plugin it's no longer possible to exclude some folders (required as a workaround for https://github.com/google/protobuf-gradle-plugin/issues/222). All the exclusions are created in the top-level module, so they are ignored by source-set-specific submodules.
While I encountered this issue with protobuf plugin, it's by no means limited to that plugin.

What's interesting is sometimes some of the rules are propagated from the top module to the children. Seemingly my particular problem happens as that particular directory is both added to a source set and to exclusion directories. Nevertheless, this is a regression/inconsistent behavior, as disabling "module per source set" mode in IntelliJ changes the behavior to the one I expect.

### Your Environment
```
Switches
Daemon 	On
Parallel 	On
Build Cache 	Off
Configure on demand 	Off
Continue on failure 	Off
Continuous 	Off
Dry run 	Off
Offline 	Off
Re-run tasks 	Off
Refresh dependencies 	Off

Infrastructure
Operating system	Mac OS X 10.14.6
CPU cores	12 cores
Max Gradle workers	12 workers
Java runtime	Oracle Java(TM) SE Runtime Environment 1.8.0_212-b31
Java VM	Oracle Java HotSpot(TM) 64-Bit Server VM 25.212-b31 (mixed mode)
Max JVM memory heap size	2004 MB
Locale	English (United States)
Default charset	UTF-8
```

**Comment by oehme** [comment]
The "module per sourceset" logic is maintained by the Jetbrains team. Please open a bug report on their issue tracker. /cc @nskvortsov
