### ISSUE TITLE
Deamon does not release file handle to annotation processor subproject jar after build

### ISSUE THREAD

**Issue by canayozel** [gradle/gradle#10090]
### Context
I have a project setup as follows

- parent
 -- sub1 (common/library module for the application's other modules)
 -- sub2 (business module)
 -- subx (project has more business modules)

sub1 project defines annotations for annotation processing to hide the third party dependency from other modules and enforce a single style for the whole application. 

Which means all subx modules has a dependency to common subproject as follows:

```
dependencies {
    implementation project (":sub1")
    annotationProcessor project (":sub1")
}
```
### Expected Behavior
Subsequent invocations to "gradlew clean build" should work. (all invocations are started after the previous one is finished)
So I can follow  the cycle below.
1 clean build 
2 write code
3 go to 1 

### Current Behavior
The first invocation to clean and build works correctly and the all other subsequent invocations fail. 

```
cd D:\development\environment\samples\gradle-example-annotation-processor-immutables; ./gradlew clean build
> Task :sub1:clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sub1:clean'.
> Unable to delete directory 'D:\development\environment\samples\gradle-example-annotation-processor-immutables\sub1\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - D:\development\environment\samples\gradle-example-annotation-processor-immutables\sub1\build\libs\sub1.jar
    - D:\development\environment\samples\gradle-example-annotation-processor-immutables\sub1\build\libs
```
The only way to be able to clean and build again is to manually stop gradle deamon process.

### Steps to Reproduce 
The sample project zip is attached.
[gradle-example-annotation-processor-immutables.zip](https://github.com/gradle/gradle/files/3433292/gradle-example-annotation-processor-immutables.zip)

Step 1: Run gradle clean build (parent) and wait for its completion.
Step 2: Run gradle clean build (parent) and it will fail.

### Your Environment
Gradle 5.5.1
Tested on Netbeans, Eclipse and on command line (windows 10), the behaviour is same in all.

**Comment by oehme** [comment]
Gradle doesn't keep annotation processor jars open, we have integration tests that ensure that. Your attached example is not writing an annotation processor, but writing an extension for immutables. So most likely there is a jar leak in immutables. Can you please open an issue on their issue tracker or provide an example without immutables in the middle?

**Comment by canayozel** [comment]
I have experienced this issue with other annotation processors too such as lombok too (if i don't remember wrongly), currently experimenting on similar libraries. 

I will shortly create a sample project without a third-party and share the results.

**Comment by canayozel** [comment]
@oehme  here is an example without the immutables is in the middle. 
[Uploading gradle-example-annotation-processor-custom.zip…]()

sub1 is an module added to sub2 as an annotation processor. The case is sub1 during the processing phase opens, reads and closes a resource file in sub1 in annotation processing phase. The problem above still occurs.

**Comment by canayozel** [comment]
Accidentally closed...

**Comment by oehme** [comment]
The link above doesn't point to a file.

**Comment by canayozel** [comment]
I updated the link it works now.

**Comment by oehme** [comment]
The leak is caused by the usage of JarURLConnection in your processor. This connection caches the jar file handle by default, even after it is closed. You need to call `urlConnection.setUseCaches(false);` to avoid this file leak.
