### ISSUE TITLE
Copy task deletes all files in destination dir  when all files are excluded

### ISSUE THREAD

**Issue by danreb25** [gradle/gradle#1012]
### Expected Behavior

When using the exclude method and actually all files from sourceDir are excluded, the destination dir should remain unchanged

### Current Behavior

When using the exclude method and actually all files from sourceDir are excluded, 
Then **ALL** the ecluded files that are already present in the **DestinationDir** are **DELETED**

### Steps to Reproduce (for bugs)

e.g. in my file system:
* sourceDir with several (and only! )  *.sql files
* destDir  with the same files copied from sourceDir

then executing the following task

```java
task testBBLCopy (type: Copy){

	from sourceDir

	//exclude { details -> true }
	exclude '**/*.sql'

	into destDir

	includeEmptyDirs = false

}
```
### Your Environment

 * Build scan URL: 
Mac OS X ElCapitan 10.11.6
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 3.2
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
JVM Arguments: None
Program Arguments: None
Gradle Tasks: testBBLCopy

**Comment by wolfs** [comment]
Looks like this is the same as #973, right?

**Comment by danreb25** [comment]
Probably,
... but why should a Tasks with input files marked 'skip when empty' delete the output?
Why should a copy task  have a delete action? The sync task does, but the copy task should'nt, isn'it?

**Comment by eriwen** [comment]
@danreb25 Thanks for the bug report and example. I've copied it over to #973 and will close this one because they are almost certainly duplicates. 

Please click "Subscribe" on that issue to follow along with our progress on it.
