### ISSUE TITLE
Hide `init` task from `./gradlew tasks` output when build file exists

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10134]
### Expected Behavior

`./gradlew tasks` should not display `init` task when build file already exists.
What is the use of running `./gradlew init` in a project that already has a build file?
That task should be hidden automatically.

### Current Behavior

`./gradlew tasks` always prints `init - Initializes a new Gradle build` even though the task would be skipped like

```
$ ./gradlew init

> Task :init SKIPPED
The build file 'build.gradle.kts' already exists. Skipping build initialization.
```

### Context

https://github.com/gradle/gradle/issues/10133

**Comment by ljacomet** [comment]
Hi @vlsi 

The recent activity is mostly us making sure that all issues closed by the stale bot are properly marked as "not planned" instead of looking like regular completed issues.

This is an area that the team cannot currently focus on. So its state reflects this now.
