### ISSUE TITLE
Discourage reaching into sibling projects

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1013]
There are some rules that builds need to follow to be able to safely use configure on demand.  Many builds probably don't realize they violate our assumptions.

Given this build:

./a/build.gradle
```
sourceSets.main.output.dir 'anotherDir'
```
./b/build.gradle
```
task broken {
   inputs.files project(":a").sourceSets.main.output
   doLast {
      assert inputs.files.files.find { it.absolutePath.contains("anotherDir") }
   }
}
```
./build.gradle
```
subprojects {
   apply plugin: 'java'
}
```
./settings.gradle
```
include 'a', 'b'
```
Running `gradle :b:broken -Dorg.gradle.configureondemand=true` fails the build when configure-on-demand is enabled.

`gradle :b:broken` works.

### Expected Behavior
Gradle should warn when a build author has done something that's likely broken/wrong with configure-on-demand enabled.

### Current Behavior
The Gradle build may or may not work depending on how the build is executed.

One big problem with this is the use of `allprojects{}` and `subprojects{}` mostly negates the benefits of using configure on demand since we need to partially configure all the subprojects.  But ignoring that, this build fails when `org.gradle.configureondemand=true` because there's a  dependency between `a` and `b` that requires `a` to be fully configured.  The `b` project "reaches into" project `a` and grabs the output directory for the main source set.  Without configure-on-demand, this works because the source set output is a "live" collection and `a` would be fully configured.

### Context
I just helped diagnose problems with a build that had several references similar to this and configure-on-demand enabled.  

The appropriate way to handle this is to use a project dependency between the two projects. That would allow Gradle to see the dependencies and fully configure project `a`.

To avoid surprises for other builds, I think if we separated the `ProjectFinder`-like parts of `DefaultProject` into a separate service that could be injected into the project, we could emit a warning whenever `Project.project(...)` is called with configure-on-demand enabled without affecting `DependencyHandler.project(...)` (which is OK to call).  There might be other things we could do to tell that "half-configured" projects were used and fail the build.

### Steps to Reproduce (for bugs)

See example above.

**Comment by oehme** [comment]
We need to discourage users from reaching into sibling projects in general. The above example is a special case that works without configure-on-demand, but most cases of reaching into sibling projects will break no matter if configure-on-demand is used or not.
