### ISSUE TITLE
gradle init creates erroneous wrapper configuration

### ISSUE THREAD

**Issue by pschyma** [gradle/gradle#10144]
Using `gradle init` (locally installed 5.5.1) creates an erroneous wrapper configuration.
### Expected Behavior

Any invocation of `gradlew` such as e.g. `gradlew build` should download gradle.
### Current Behavior

The download fails with:
```
➜ ./gradlew build
Downloading https://services.gradle.org/distributions-snapshots/gradle-5.5.1-20190724234647+0000-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-5.5.1-20190724234647+0000-bin.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
	at org.gradle.wrapper.Download.download(Download.java:52)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

```
### Steps to Reproduce 

1. Run `gradle init` and follow the dialogs. I used: library, kotlin implementation, kotlin dsl
2. Run `./gradlew build`

[1] contains the project as created in step 1.

After an explicit invocation of `gradle wrapper --gradle-version=5.5.1` everything works again as expected.

### Your Environment

* Gradle installed via pacman on Arch Linux.

[1] https://github.com/pschyma/gradle-init-example

**Comment by big-guy** [comment]
Is it possible that `gradle` is actually a nightly installation (5.5.1-20190724234647+0000) and not 5.5.1?  That's what it looks like to me.

Can you post the output of `gradle -v`?

**Comment by mzilinec** [comment]
Hello, I'm having the exact same issue, the output of `gradle -v` is:
```
------------------------------------------------------------
Gradle 5.5.1-20190724234647+0000
------------------------------------------------------------

Build time:   2019-07-24 23:46:47 UTC
Revision:     <unknown>

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_222 (Oracle Corporation 25.222-b05)
OS:           Linux 5.1.15-arch1-1-ARCH amd64
```

**Comment by pschyma** [comment]
Hi. 

Sorry for the late response. Yes, seems like you're right about the nightly version. There is already an issue ([1]) open for this in the Arch bugtracker.

For me this is then resolved. 

[1] https://bugs.archlinux.org/task/63222

**Comment by francis36012** [comment]
> Is it possible that `gradle` is actually a nightly installation (5.5.1-20190724234647+0000) and not 5.5.1? That's what it looks like to me.
> 
> Can you post the output of `gradle -v`?

The gradle executable is built from source using https://services.gradle.org/distributions/gradle-5.5.1-src.zip (as of 2019-08-17), that doesn't look like a nightly release to me. Note that the `gradle` executables are built using the `installAll` task, without the `finalRelease` property set.

Output of my local build without finalRelease, `dist/bin/gradle -v`:

```
------------------------------------------------------------
Gradle 5.5.1-20190818040217+0000
------------------------------------------------------------

Build time:   2019-08-18 04:02:17 UTC
Revision:     <unknown>

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (Oracle Corporation 11.0.4+11)
OS:           Linux 5.2.8-arch1-1-ARCH amd64
```

Output of my local build with finalRelease, `dist/bin/gradle -v`:

```
------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-08-18 04:31:49 UTC
Revision:     <unknown>

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (Oracle Corporation 11.0.4+11)
OS:           Linux 5.2.8-arch1-1-ARCH amd64
```
