### ISSUE TITLE
Spike faster native directory walking on Windows

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#10142]
See https://gradle.slack.com/archives/C10J6STFZ/p1564601625018300.

There are some PRs on native platform: https://github.com/adammurdoch/native-platform/pull/38 and https://github.com/adammurdoch/native-platform/pull/36

cc @gradle/build-cache

**Comment by wolfs** [comment]
So what we should do for the spike is
- using the APIs from native platform for file stating and directory walking in Gradle
- See if that improves performance on Windows when using a version of native platform which includes the above improvements.

**Comment by lptr** [comment]
This is probably a non-issue but we should also make sure that using the new API doesn't slow Linux/macOS down.
