### ISSUE TITLE
Prefer loopback bind address for daemon communications

### ISSUE THREAD

**Issue by esayapina** [gradle/gradle#10155]
Prefer loopback bind address for daemon communications.

There was a pull request #7838 which was later reverted because of some connectivity issue between IDEA and Gradle daemon. It would be great to rework and merge this one.

I've applied the #7838 to gradle master and see the communication issue between IDEA 2019 and Gradle daemon. But with the small change it starts working for me: 
```
subprojects/messaging/src/main/java/org/gradle/internal/remote/internal/inet/InetAddressFactory.java

...

// initial version
localBindingAddress = inetAddresses.getLoopback().get(0); 
->
// update version
localBindingAddress = InetAddress.getLoopbackAddress();
```

I'm not sure if this change is correct just thought that it may be useful. 
Please see the attached [gradle-pull-7838-idea-ok.patch.txt](https://github.com/gradle/gradle/files/3460324/gradle-pull-7838-idea-ok.patch.txt)

### Expected Behavior
Gradle daemon listens on localhost
```
$ <jdk>/Contents/Home/bin/jps -l
7474 org.gradle.launcher.daemon.bootstrap.GradleDaemon

$ lsof -i -R | grep LISTEN
java      7474 7455 <user>  218u  IPv6 0xecb361b9baa51a77      0t0  TCP localhost:58556 (LISTEN)
```
### Current Behavior
Currently Gradle daemon listens on wildcard interface
```
$ lsof -i -R | grep LISTEN
java      7380 7117 <user>  218u  IPv6 0xecb361b9d75ce5f7      0t0  TCP *:58373 (LISTEN)

$ <jdk>/Contents/Home/bin/jps -l
7380 org.gradle.launcher.daemon.bootstrap.GradleDaemon
```

### Context
Users of Intellij IDEA are disturbed when IDE opens ports on wildcard interface. Please see, for example, https://youtrack.jetbrains.com/issue/IDEA-175889. Gradle daemon used for Gradle projects building is one of the reason leading to this issue.

### Steps to Reproduce 
Open some Gradle project in IDEA IDE, start Gradle build or just run `gradle --daemon` from the command line. Then `lsof -i -R | grep <java_gradle_pid>`.

### Your Environment
IntelliJ IDEA 2019.3 Snapshot (Ultimate Edition)
Build #IU-193.1822, built on July 31, 2019
Runtime version: 11.0.3+12-b360.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

**Comment by esayapina** [comment]
@wolfs @eskatos Could you please take a look?

**Comment by eskatos** [comment]
yes, in 70c9c730b44422b5722e56b8d47ad90718365a9c and 7baafc32539e32e9333d50821197d91b4fd0b30b
thank you @esayapina!
closing

**Comment by paplorinc** [comment]
I wonder if this will reduce the performance benchmark's firewall activity.
cc: @blindpirate, @donat

**Comment by eskatos** [comment]
It could if the firewall do less work on loopback traffic.

**Comment by charlesritchea** [comment]
https://github.com/gradle/gradle/issues/12232 @esayapina @eskatos @wolfs Can someone take a look at my issue, this fix broke my EC2 Jenkins gradle. The way gradle daemon binds addresses now doesn't work on my instance and I'm trying to figure out what I need to do to fix that. I'm planning on just running in docker in the future, but I'd like to solve this puzzle
