### ISSUE TITLE
Unable to install Gradle and have it function

### ISSUE THREAD

**Issue by Sweddy** [gradle/gradle#10160]
### Expected Behavior
I am able to install gradle and have it function.

### Current Behavior
It does not function.

### Context
I downloaded the binary version of gradle 5.5.1 and exported it to a new file in **C:/** called Gradle, as I was told in the instructions, giving it the file path **C:\Gradle\gradle-5.5.1**.
I then went to Properties -> Advanced System Settings -> Environmental Variables, and edited Path under System Variables to include the correct file path **C:\Gradle\gradle-5.5.1\bin**, of course preceded by a semicolon.
However when I open the command prompt to confirm my installation using `gradle -v` it simply continues to say:

> 'gradle' is not recognized as an internal or external command, operable program or batch file.

I have attempted to delete the Gradle file and reinstall multiple times without success. I tried creating a new system variable called **GRADLE_HOME** with the file path **C:\Gradle\gradle-5.5.1** and then add first **GRADLE_HOME\bin** and then **%GRADLE_HOME%\bin** with no success.

If it matters in anyway I have the Java JDK 12.0.2 installed.

I don't know where else to submit this issue but here.

**Comment by ljacomet** [comment]
I would verify the following first:
* verify the content of the unzipped distribution
** In particular, that you have `<GRADLE_PATH>\bin\gradle.bat`
* Try invoking Gradle using the _full_ path: `<GRADLE_PATH>\bin\gradle.bat -v`

If the above works, your installation is most likely OK and you only have to figure out how to get it added to the PATH in Windows.

**Comment by Sweddy** [comment]
The Gradle version I installed did not have anything in the bin folder. What do I do

**Comment by ljacomet** [comment]
Closing since the original reporter never responded to the suggested steps.
