### ISSUE TITLE
Incremental Java compile fails when Gradle user home is different to that used when compilation was last performed

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#1016]
### Steps to Reproduce (for bugs)

1. `gradle init --type java-library`
2. `echo "compileJava.options.incremental = true" >> build.gradle`
3. `gradle assemble -g dir1`
4. change version of guava from 20 to 19 (need to change the compile classpath to trigger the problem)
5. `echo "// compile me" >> src/main/java/Library.java`
6. `gradle assemble -g dir2`

### Analysis

Incremental Java compilation stores state in 2 places: the build's `.gradle` directory and in the user `.gradle` directory. The state in the build's `.gradle` directory references the state in the user `.gradle` directory and incremental Java compilation expects this to be present. However, when a different user `.gradle` directory is used, the state is not present and the result is a NPE.

I would probably just move the state from user home `.gradle` to live in the build's `.gradle`.

**Comment by eriwen** [comment]
Have we addressed this while stabilizing incremental compilation?

**Comment by adammurdoch** [comment]
Yes, we will have. We should add some test coverage to prove this is the case.
