### ISSUE TITLE
Tooling API should allow IDE-specific metadata to be provided to IDE

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#10162]
A number of releases ago, Gradle massively enhanced the idea and eclipse plugins to allow fine-grain control over the generated IDE project files (i.e. the withXml and merge features). These features acknowledged that it is unrealistic for Gradle to model every aspect of the IDE's metadata. Rather than attempting to model all that, a nicely flexible mechanism was developed that allows developers to tweak the generated projects to meet their needs.

Unfortunately, the Tooling API was never given similar enhancements. Today, the Tooling API forces developers and IDE vendors to live within its modeling limitations. One major example of this limitation is that there is no way to communicate to the IntelliJ IDE that a given module (i.e. a Gradle subproject) is of a given type (e.g. Java, IntelliJ plugin, Web, etc). Instead, the IDE makes an assumption that all modules are Java. The ramifications of this are that IntelliJ no longer provides key features specific to the module type. For example, JetBrains' gradle-intellij-plugin cannot generate modules, which when loaded, are identified by the IDE as Plugin development modules. Instead, they are treated as plain Java modules. This requires developers who wish a richer development experience to manually reconfigure their projects, only to have that configuration overridden the next time they sync their projects. Obviously, this is a terrible developer experience. Another example is related to development of web framework projects such as Ember or Angular. Because the imported Gradle project is not marked as a Web module, it is not possible to configure IDE run configurations to execute Ember and Angular CLI commands (e.g. build, test). This means it is not possible to run tests and serve applications within the IDE.

I propose that a Gradle file be able to provide IDE-specific metadata to the IDE via the Tooling API. One way this could be accommodated is to simply allow the withXml block to be exposed via the Tooling API. Even though an XML file is not generated on the file system, the XML would be provided to the IDE for its consumption as it sees fit. In the above module type example, the IDE could look in the XML for the presence of the module type element and set the module type accordingly. Obviously, once Gradle provides this enhancement, the IDE vendors would have to make use of it, but one has to start somewhere. This enhancement would bring the Tooling API to the same level of developer control as the existing project file generation.

**Comment by eskatos** [comment]
https://github.com/JetBrains/gradle-idea-ext-plugin might solve some of those shortcomings

**Comment by baron1405** [comment]
Thanks @eskatos for the pointer! That plugin looks very interesting and I want to make sure I understand how it works. Basically, there is a DSL for use in the idea.* block of your build.gradle. When the build.gradle is loaded into IntelliJ using the Tooling API, IntelliJ is able to read that DSL and process the respective configuration items (e.g. adding copyrights, run configurations, etc). Is that a correct understanding? If so, I do not see a way to configure the Module Type. In other words, I want to be able to convey to IntelliJ that the module described by the build.gradle file is something other than a Java module (e.g. an intellij plugin module, a python module, etc). Assuming that capability is not yet present in the DSL, do you think that it is possible to add the specification of module type?

**Comment by DPUkyle** [comment]
Seems like a better question for @nskvortsov 👋 

It would be super cool to marry gradle-idea-ext-plugin with @zolotov's gradle-intellij-plugin, so that the plugin module _finally looks like a plugin_.

![image](https://user-images.githubusercontent.com/2841209/80037763-17b07080-84a9-11ea-94fc-d4e6487e95dd.png)

**Comment by zolotov** [comment]
@DPUkyle gradle-intellij-plugin was supposed to be untied from IDEA as much as possible, at the early stages I even tried to develop IntelliJ-plugins in Eclipse and NetBeans using it. Probably I misunderstanding something but it looks like gradle-idea-ext-plugin may tie it back to the IntelliJ.

**Comment by DPUkyle** [comment]
Hi @zolotov , long time since we talked. I hope you're doing well.

Now I understand the intention to keep gradle-intellij-plugin "IDE-agnostic", that's cool. We really value that plugin and don't worry we're not asking for any changes to it.

When using gradle-intellij-plugin while developing with IntelliJ, I always wondered why the plugin module never showed up as a proper plugin (the silly icon above); that's because the .idea metadata presents it as a Java module. Now I am thinking to locally combine the power of gradle-idea-ext-plugin to make this work, that's all.

**Comment by baron1405** [comment]
@zolotov @nskvortsov is it possible for the gradle-idea-ext-plugin to allow setting the module type? If it is not currently possible, is it something JetBrains would consider adding? That would allow Gradle build files to specify the module type when the tooling API is used (e.g. PLUGIN_MODULE, PYTHON_MODULE).

**Comment by nskvortsov** [comment]
Currently, `gradle-idea-ext-plugin` does not support module types. We could consider adding them, but it needs more investigation. Would you mind opening a ticket in IntelliJ IDEA"s tracker? just follow the link
https://youtrack.jetbrains.com/newIssue?project=IDEA&c=Subsystem%20Build.%20Gradle&c=Type%20Feature

**Comment by baron1405** [comment]
I have created https://youtrack.jetbrains.com/issue/IDEA-239748.

**Comment by nskvortsov** [comment]
thank you

**Comment by ljacomet** [comment]
Closing as the IntelliJ support has been added as part of [plugin `idea-ext`](https://plugins.gradle.org/plugin/org.jetbrains.gradle.plugin.idea-ext).
