### ISSUE TITLE
Configuration cache property serialization should consider custom writeObject/readObject methods

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#10172]
When using instant execution, property serialization should consider custom implementations of writeObject/readObject. If a class defines these methods, those should be used.

**Comment by bamboo** [comment]
Custom writeObject/readObject methods are now supported (with caveats).

**Comment by bamboo** [comment]
The remaining issues with Java Object Serialization have been captured in #13588. Let's continue the discussion there.
