### ISSUE TITLE
Circular dependency between tasks when subprojects have tasks with same name and TaskProvider is used

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10180]
### Expected Behavior

It should be fine to have tasks with the same name in different projects, and it should be possible to specify dependencies between those tasks.

### Current Behavior

It fails when `TaskProvider` are used.

Note: it is funny that a mere `taskProvider.get()` workarounds the issue.

### Context

I want to establish "linear execution order" for tasks that do not support concurrent execution (e.g. `publishPlugin` tasks that publishes plugin to Gradle Portal).
In other words, I'm trying to workaround https://github.com/gradle/gradle/issues/7047 (by adding dependencies between tasks)

### Steps to Reproduce 

`settings.gradle.kts`

```kotlin
for(i in 1..2) {
  include("p$i")
}

rootProject.name = "deps"
```

`build.gradle.kts`

```kotlin
subprojects {
  tasks.register("hi") {
    doLast {
      println("Hi from project $project, task $this")
    }
  }
}

// Make task execution sequential
afterEvaluate {
  var t: TaskProvider<Task>? = null

  subprojects {
    val nextTask = tasks.named("hi")
    if (t != null) {
      println("Adding dependency: $nextTask.dependsOn($t)")
      // nextTask.get() // <-- if you un-comment this line, then the scripts starts working
      nextTask { dependsOn(t) }
    }
    t = nextTask
  }
}
```

### Your Environment

The problem happens for both Gradle 5.5.1 and 5.6 rc-1

**Comment by lacasseio** [comment]
It maybe a Kotlin DSL issue. Could you try in Groovy DSL? I don't see why it wouldn't work without the TaskProvider#get.

**Comment by vlsi** [comment]
@lacasseio , here's a Groovy reproducer.

```gradle
subprojects {
  tasks.register("hi") {
    doLast {
      println("Hi from project $project, task $this")
    }
  }
}

// Make task execution sequential
afterEvaluate {
  def t = null

  subprojects {
    def nextTask = tasks.named("hi")
    if (t != null) {
      println("Adding dependency: ${nextTask}.dependsOn($t)")
//      nextTask.get()
      nextTask.configure { dependsOn(t) }
    }
    t = nextTask
  }
}
```

```
$ ./gradlew hi

> Configure project :
Adding dependency: provider(task hi, class org.gradle.api.DefaultTask).dependsOn(provider(task hi, class org.gradle.api.DefaultTask))

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:p2:hi
\--- :p2:hi (*)

(*) - details omitted (listed previously)
```

After I un-comment `.get()`, it works:

```
$ ./gradlew hi

> Configure project :
Adding dependency: provider(task hi, class org.gradle.api.DefaultTask).dependsOn(provider(task hi, class org.gradle.api.DefaultTask))

> Task :p1:hi
Hi from project project ':p1', task root project 'deps'

> Task :p2:hi
Hi from project project ':p2', task root project 'deps'
```

**Comment by vlsi** [comment]
Ah. It seems I am just bitten by "late binding of the field in closure".

In other words, `configure { dependsOn(t) }` is not bound to a specific `t` value, but it captures an object with `t field`.

`nextTask.get()`  "solves" the issue because it realizes the task, so the configuration action is applied immediately, and it uses the proper (current) value of `t` variable.

**Comment by vlsi** [comment]
Just in case, the workaround is to "save `t` field to a local variable":

For instance:

```kotlin
afterEvaluate {
  var t: TaskProvider<Task>? = null

  subprojects {
    val nextTask = tasks.named("hi")
    if (t != null) {
      val prevTask = t // <-- this is a workaround
      println("Adding dependency: $nextTask.dependsOn($t)")
//      nextTask.get()
      nextTask { dependsOn(prevTask) }
    }
    t = nextTask
  }
}
```
