### ISSUE TITLE
Can not run docker image with gradle

### ISSUE THREAD

**Issue by KaterynaGubar** [gradle/gradle#10188]
I want to run my test in docker container with system time "2019-07-31 00:00:00"
I've found an image that could help me and inherit my Dockerfile from that one.

Here's my Dockerfile:

```
FROM openjdk:8-jdk-alpine
ENV APP_HOME=/app/

COPY . $APP_HOME

WORKDIR $APP_HOME

COPY --from=trajano/alpine-libfaketime  /faketime.so /lib/faketime.so
ENV LD_PRELOAD=/lib/faketime.so \
    DONT_FAKE_MONOTONIC=1

ENTRYPOINT ["./gradlew", "-Denv=integration", "-Dtags=myTest", ":ui-e2e-tests:clean", ":ui-e2e-tests:test"]
```
 Every time I run my image 
```
sudo docker run --rm -e FAKETIME="2019-07-31 00:00:00" faketime:latest
```
But every time I get same error

### Expected Behavior
Image started successfully.

### Current Behavior
Build file '/app/build.gradle.kts' line: 13

* What went wrong:
Plugin [id: 'io.qameta.allure', version: '2.8.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.qameta.allure:io.qameta.allure.gradle.plugin:2.8.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

### Context
Sometimes I get 'Gradle daemon disappeared unexpectedly '

**Comment by ov7a** [comment]
Sorry for the late reply.

Most likely, this problem is caused by TLS issues (you can't reliably resolve deps from HTTPS with skewed time).
