### ISSUE TITLE
Gradle does not remove stale output files from Java compilation after a version change

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1018]
If source files have been removed/moved around since the last compilation and the Gradle version changes (or the `.gradle` directory is deleted), Gradle will leave behind the orphaned `.class` files.

This can show up as strange test failures because Gradle will try to execute removed test classes.

1. Create `Main.java` and `Redundant.java` with some trivial code in them
2. Compile them by running compileJava
3. Remove `$projectDir/.gradle` (simulating a version upgrade)
4. Remove `Redundant.java`
5. Compile again
6. `Redundant.class` is still in the build/classes directory, even though its source is gone.

Spec: https://github.com/gradle/gradle/pull/984

**Comment by big-guy** [comment]
This is mostly fixed in 3.4.  We're going to do more for #821
