### ISSUE TITLE
platform and enforcedPlatform not working on non-transitive configurations

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#10195]
Tried switching from dependency recommender plugin and the old bom ingestion in gradle4 to the new `platform` declaration in gradle5. It works fine on transitive configurations, but as soon as you try to resolve a non-transitive one, gradle (5.4.1 and 5.5.1 tested) resolves the bom and then fails to resolve any version of the configuration's dependencies from it.

### Expected Behavior
When I pass a bom using `platform` or `enforcedPlatform` to a non-transitive dependency, it should resolve/enforce its (unspecified) dependencies versions by looking at the supplied bom.

### Current Behavior
The resolver resolves the bom itself, but then fails to infer versions to the non-versioned dependencies and fails.

### Context
Trying to migrate off gradle 4's "improved bom support" and the nebula dependency recommender plugin. In a few cases we use non-transitive dependencies configurations to avoid manually listing many exclusions, or when we need to just import some resources from some particular packages.

### Steps to Reproduce 
bare `build.gradle`:
```
repositories {
  jcenter()
}
apply plugin: 'java'
configurations {
  mydep {
    transitive = false
  }
}
dependencies {
  mydep enforcedPlatform('org.springframework:spring-framework-bom:5.1.9.RELEASE')
  mydep 'org.springframework:spring-web'
}
```
Execute
`./gradlew dependencies --configuration mydep` and the dependency resolution fails (tried gradle 5.5.1 and 5.4.1). Completes with success if you switch the configuration to be transitive, but brings in all of the transitive dependencies as well.

### Your Environment
Tried gradle 5.5.1 and 5.4.1, both showed the same behaviour.

**Comment by ljacomet** [comment]
This is a known situation. A platform is also a dependency, which itself contains mostly constraints. When applied in a non-transitive configuration, this results in the constraints of the platform to be ignored, as are transitive dependencies of any other dependency added to that same configuration.

There is no short term plan to improve that situation. Any solution would require amending the semantics of `transitive = false` at the configuration level.

**Comment by sacchettom** [comment]
@ljacomet is there any possible workaround for this in gradle 5, other than manually excluding all the dependencies from the configuration? Or would it be possible to add wildcards/regular expressions support to the exclude rules? (Looking at the existing class, only matching group and artifact ids seem supported)

**Comment by ljacomet** [comment]
If you need the constraints of the platform, you cannot set the configuration `transitive = false`. So what you can do is set _all_ the dependencies _but the platform_ to be `transitive = false`.
That's the only solution available in Gradle 5.

**Comment by sacchettom** [comment]
thanks @ljacomet that worked fine!
