### ISSUE TITLE
Add `archiveDigest` as property to archive tasks like distTar / distZip

### ISSUE THREAD

**Issue by nhoughto** [gradle/gradle#10222]
### Expected Behavior
Add configuration properties to `AbstractArchiveTask` that will allow the task to be configured to hash / create a digest of the output it is created, likely via `DigestOutputStream`, and then expose the property value as `archiveDigest` or similar so it could be referenced like `archivePath` etc are at the moment.

Most of the effort in hashing a file on modern systems is the I/O, with a small overhead for the algorithm itself. There is currently no way to configure this behaviour and the user is forced to reprocess the entire output file to generate a hash, which can be expensive for large output files.

It would be even better if we didn't have to hash it at all and the internal gradle build cache value that must be being calculated is made available, but that seems unlikely. Previous issue: https://github.com/gradle/gradle/issues/1729

### Current Behavior
There is no digest available, or extension point to add it.

### Context
We are currently using a `doLast {}` hook to digest the file after creation, this means we double our I/O to write then re-read and digest all the files. Our gradle build emits many GiBs of tar files, so we are feeling the pain of unnecessary I/O.

Happy to PR if this is a direction you'd like to take

**Comment by alllex** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.
