### ISSUE TITLE
Please comply with ASM license when re-distributing ASM

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10235]
### Expected Behavior

Gradle should comply with ASM license terms if Gradle incorporates asm.jar into the release artifacts.

### Current Behavior

Gradle re-distributes ASM jars (e.g. asm-7.1.jar), however Gradle fails to comply with the license.

ASM license specifies that `Redistributions of source code must retain the ... copyright notice`

Would you please comply with ASM license? (see https://gitlab.ow2.org/asm/asm/blob/e246de13a995837bc88777aca47f141d9bcbfc01/LICENSE.txt )

Thanks.

See also:
https://github.com/raphw/byte-buddy/issues/709
https://github.com/jacoco/jacoco/issues/916
https://gitlab.ow2.org/asm/asm/issues/317880

**Comment by vlsi** [comment]
PS. You might want to use https://github.com/vlsi/vlsi-release-plugins#license-gather-plugin to collect licensing information for the published jars/distributions

Here's how the plugin helps to keep Apache JMeter LICENSE file up to date: https://github.com/apache/jmeter/blob/6b672624dcfef5ab15dc260327c806fb1ab7fb1d/src/licenses/build.gradle.kts#L90-L94

**Comment by big-guy** [comment]
In 5.6+, we added the ASM license (and any other 3rd party dependency we bundle).
