### ISSUE TITLE
Cannot iterating repositories

### ISSUE THREAD

**Issue by rantianhua** [gradle/gradle#10242]
### Expected Behavior

Should iterate all maven repositories url through gradle API.
### Current Behavior

Can just iterate maven central url, custom maven urls configured cannot be iterated.
### Context

Gradle plugin version: 3.2.1
Gradle version: 4.6
Android Studio Version: 3.4.2
I want to write a gradle plugin to iterate all repositories url configured in the project.
My build.gradle file:
```groovy
buildscript {

    ext.kotlin_version = '1.3.0'
    repositories {
        flatDir { dirs 'libs' }
        maven { url 'http://host/repository/public/' }
        maven { url "http://host/nexus/content/repositories/releases/" }
        maven { url "http://host/nexus/content/repositories/snapshots/" }
        mavenCentral()
    }
}
```
My plugin code:
```kotlin
    @TaskAction
    fun iterateRepositories() {
        with(project.repositories) {
            maven {
                it.artifactUrls.forEach { url ->
                    println("custom maven url: $url")
                }
            }
        }
    }
```
### Steps to Reproduce 

I add my plugin to my project and run it through gradle, but there is no any output. I suppose to 
print like this:
```
custom maven url: http://host/repository/public/
custom maven url: http://host/nexus/content/repositories/releases/
custom maven url: http://host/nexus/content/repositories/snapshots/
```
### Your Environment

Build scan URL:

**Comment by blindpirate** [comment]
Note that you're not iterating the repositories, you're configuring a repository. Also note 

```
buildscript {
   repositories{
  }
}
```

is different from 

```
repositories {
}
```

The following code works for me:

```
    repositories {
        flatDir { dirs 'libs' }
        maven { url 'http://host/repository/public/' }
        maven { url "http://host/nexus/content/repositories/releases/" }
        maven { url "http://host/nexus/content/repositories/snapshots/" }
        mavenCentral()
    }


class MyTask extends DefaultTask {
    @TaskAction
    void iterateRepositories() {
        project.repositories.each {
          if(it.hasProperty('url'))
                    println("custom maven url: ${it.url}")
        }
    }
}

task my(type: MyTask)
```

Please don't add `regression` label if it's not a regression.

**Comment by rantianhua** [comment]
Thanks so much!! And I want to know what label should I use in this kind of problem?

**Comment by ljacomet** [comment]
This is a usage question, not a problem in Gradle. So it is best to start by asking a question on https://discuss.gradle.org.

**Comment by rantianhua** [comment]
Ok, I get it.
