### ISSUE TITLE
--debug-jvm is ineffective while running a single test method

### ISSUE THREAD

**Issue by dxxvi** [gradle/gradle#10250]
Not sure if this is a bug or if I don't know how to use gradle.
```bash
gradle test --tests path.to.a.ClassTests --debug-jvm
```
works (I can see `Listening for transport dt_socket at address: 5005`) but
```bash
gradle test --tests path.to.a.ClassTests.testMethod --debug-jvm
```
doesn't work (there's no `Listening for transport dt_socket at address: 5005`).

**Comment by blindpirate** [comment]
I'm pretty sure it works (please provide a reproducible sample). The only reason I can think of is that your `gradle test --tests path.to.a.ClassTests.testMethod` doesn't match any test method in the class.

**Comment by dxxvi** [comment]
> doesn't match any test method in the  class

That's correct. Now I'm so ashamed.
