### ISSUE TITLE
Gradle didn't work well with testNG dependsOnMethods

### ISSUE THREAD

**Issue by aaronlijie** [gradle/gradle#10263]
### Context and how to reproduce
The following is what I found and How to reproduce it:
I am using testNG and adding the following demo test code:
```
package controllers;
import org.testng.Assert;
import org.testng.annotations.Test;

public class ApplicationTest {
  @Test
  void test1() {
    assert 1 == 1;
  }

  @Test(dependsOnMethods = "test1")
  void test2() {
    assert 2 == 2;
  }
}
```
Then I ran the following command:
1. gradle test --tests controllers.ApplicationTest --scan --rerun-tasks 
    [build scan](https://scans.gradle.com/s/37yl72qisucuy/tests) succeed
2. gradle test --tests controllers.ApplicationTest.test1 --scan --rerun-tasks 
   [build scan](https://scans.gradle.com/s/zk7kwluey5w2o/tests) succeed
3. gradle test --tests controllers.ApplicationTest.test2 --scan --rerun-tasks 
   [build scan](https://scans.gradle.com/s/a7mdyzp7c2532) failed.

### Expected Behavior

The third command should run successfully.

### Current Behavior

The command failed with following issue:
```
The :test task failed.View task in console log
No tests found for given includes: [controllers.ApplicationTest.test2](--tests filter)
```

### Context

It forced me to rerun the whole test class instead of the single one. For our big project, it would be very slow.

### Steps to Reproduce 

Please check the first section

### Your Environment
It is Mac OS X with Gradle 5.2.1

Build scan URL:
https://scans.gradle.com/s/37yl72qisucuy/tests
https://scans.gradle.com/s/zk7kwluey5w2o/tests
https://scans.gradle.com/s/a7mdyzp7c2532

**Comment by ov7a** [comment]
Sorry for the late reply.

Fixed by
* https://github.com/gradle/gradle/pull/13879
