### ISSUE TITLE
Groovy test runtime scope does not inherit main runtime scope causing NoClassDefFoundError  

### ISSUE THREAD

**Issue by pmendelski** [gradle/gradle#10265]
When groovy tests are compiled NoClassDefFoundError is thrown. Groovy compiler does not see transitive dependencies from main runtime scope. 

### Expected Behavior

Tests from the [sample-project](https://github.com/pmendelski/bug-sample-groovy-runtime-deps-inheritance) should compile. Groovy compiler should have access to main runtime dependencies.

### Current Behavior

`NoClassDefFoundError` is thrown for classes from main runtime scope.

### Context

I cannot run tests written in groovy. I can quickfix this issue by listing all the runtime dependencies manually in test scope.

### Steps to Reproduce 
Download: https://github.com/pmendelski/bug-sample-groovy-runtime-deps-inheritance
Run: ./gradlew compileTestGroovy

### Your Environment

Build scan URL: https://gradle.com/s/nyzcfimlzxpxe

**Comment by pmendelski** [comment]
Hi, thanks for your prompt reply and clarification.

Please correct me if I'm wrong:
If clients of my library use Spock for testing I cannot use [`implementation` scope dependencies](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies). Most often gradle implementation scope dependencies are translated to `runtime` by [maven-publish plugin](https://github.com/coditory/sherlock-distributed-lock/blob/9494694c61979accdf088d70ed7070bb6fbfb72f/gradle/publish-project.gradle#L77) (sample [pom](https://oss.sonatype.org/service/local/repositories/releases/content/com/coditory/sherlock/sherlock-inmem-reactive/0.3.0/sherlock-inmem-reactive-0.3.0.pom)).

Conclusion: Library developers should not use `implementation` scope because it breaks Spock tests.

**Comment by bjornvester** [comment]
I wasn't aware that the maven publish plugin did that, so yes that makes a lot of sense. But the best way to go about it then is to apply the `java-library` plugin and use the `api` configuration instead of `compile` or `implementation`. That will make it available for the compilation scope, even if resolved transitively.

**Comment by pmendelski** [comment]
Yes this is the recommended configuration from [maven-publish plugin documentation](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example). 

I believe it deserves a line or two in [the java-library documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies) as well ;)

Thanks, again.

**Comment by pmendelski** [comment]
Reopened to apply the documentation change.
