### ISSUE TITLE
build aab file with gradle 5.1.1 and install apk lack of so file

### ISSUE THREAD

**Issue by haianhsing** [gradle/gradle#10269]
### Expected Behavior

app run with no error.

### Current Behavior

run the app and find lack of so file.

### Steps to Reproduce 

1. build the aab file
2. upload to googleplay, download and install or use bundletool tool to install
3. run the app and find the error

### Your Environment

android studio 3.4.2 with gradle 5.1.1

More infomation refer to [bundletool issue](https://github.com/google/bundletool/issues/110)

I hope to solve this problem as soon as possible. Thanks.

**Comment by blindpirate** [comment]
Doesn't look like a Gradle issue. Why you're sure it's Gradle issue?

**Comment by haianhsing** [comment]
@blindpirate Because the difference of two aab file is only the difference between gradle versions. I guess it might be gradle's problem.
