### ISSUE TITLE
Configuration with name 'implementation' not found in  Android  app/build.gradle

### ISSUE THREAD

**Issue by wxy520ll** [gradle/gradle#10268]
App/ build.gradle

![Aaron Swartz](https://s2.ax1x.com/2019/08/13/mCheb9.png)

log:
Configuration with name 'implementation' not found.

please help me

**Comment by blindpirate** [comment]
For help/questions please visit https://discuss.gradle.org/

You need to clarify your intention before asking for help. The current behavior is totally expected.
