### ISSUE TITLE
Unable to build Java 12 using Gradle 5.5.1 and 4.10.3

### ISSUE THREAD

**Issue by OssNass** [gradle/gradle#10275]
I am trying to compile an application using java 12 and gradle 4.10.3 (the same problem happened when using 5.5.1), The build.gradle file content is:
```
plugins {
    id 'java'
    id 'application'
}

group 'zxc'
version '1.0-SNAPSHOT'

sourceCompatibility = 12

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {

    compile group: 'com.h2database', name: 'h2', version: '1.4.199'
    compile group: 'org.apache.cayenne', name: 'cayenne-server', version: '4.0.1'
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

ext {
    moduleName = ' com.zxc'
    moduleLaunchPoint = 'com.voroniy.app.Main'
}

mainClassName="${moduleName}/${moduleLaunchPoint}"
```

The module-info.java file:
```
module com.zxc {
    requires java.sql;
    requires com.h2database;
    requires cayenne.di;
    requires cayenne.server;
}
```

When I try to compile I get the following:
```

/home/ossama/IdeaProjects/zxc/src/main/java/module-info.java:3: error: module not found: com.h2database
    requires com.h2database;
                ^
/home/ossama/IdeaProjects/zxc/src/main/java/module-info.java:4: error: module not found: cayenne.di
    requires cayenne.di;
                    ^
/home/ossama/IdeaProjects/zxc/src/main/java/module-info.java:5: error: module not found: cayenne.server
    requires cayenne.server;

```

The problem is for some reason the `javac` is not accepting libraries from Gradle, however, I have an older project with similar gradle.build structure that uses java 12 and different set of libraries that is compiled and linked using jlink correctly in gradle.

**Comment by rgoldberg** [comment]
From what I know, Gradle doesn’t support JPMS modules. They wrote a very barebones plugin to provide simple initial support. I forked an improved version, and I’ll provably release a new version sometime next week. It’s currently available at:

https://plugins.gradle.org/plugin/rgoldberg.experimental-jigsaw
