### ISSUE TITLE
A Conf2ScopeMapping is not used when added after a call to MavenPom.whenConfigured 

### ISSUE THREAD

**Issue by 3ll3d00d** [gradle/gradle#1027]
### Expected Behavior
When using the maven plugin, it should be possible to add a `Conf2ScopeMapping` at any time before the pom is produced irrespective of whether `whenConfigured` actions have been registered or not.

### Current Behavior
If a Conf2ScopeMapping is added after the `whenConfigured` action then that mapping is not available to the `PomDependenciesConverter` when `DefaultMavenPom.getEffectivePom` is called.

As a result, the generated pom.xml may be missing some dependencies and is thus invalid.

This appears to occur because `org.gradle.api.publication.maven.internal.pom.DefaultMavenPomFactory.create()` is implemented as follows

    public MavenPom create() {
        return new DefaultMavenPom(configurationContainer,
                new DefaultConf2ScopeMappingContainer(conf2ScopeMappingContainer.getMappings()), pomDependenciesConverter, fileResolver);
    }

i.e. the mappings are copied from `Conf2ScopeMappingContainer` into a new `DefaultConf2ScopeMappingContainer` when the `MavenPom` is created 

secondly `org.gradle.api.publication.maven.internal.BasePomFilterContainer.pom(Closure)` is implemented as 

    public MavenPom pom(Closure configureClosure) {
        return ConfigureUtil.configure(configureClosure, getPom());
    }

i.e. this triggers the creation of the maven pom and hence the mappings are copied.

### Context
This situation has been noticed when 

* a project as multiple sourceSets with different compile configurations
* the sourcesets are combined into a single artifact published to a maven repository
* the build uses a variety of plugins that configure the underlying gradle project based on the contents of the build.gradle (and hence the plugin defers its configuration using `projectsEvaluated` and/or configuration tasks

### Steps to Reproduce (for bugs)
The following build.gradle can reproduce the issue

	apply plugin: 'java'
	apply plugin: 'maven'

	sourceSets {
		generated
	}

	configurations {
		generatedCompile
		compile {
			extendsFrom generatedCompile
		}
	}

	dependencies {
		compile sourceSets.generated.output
	}

	project.tasks.jar {
		from sourceSets.generated.output
	}

	dependencies {
		generatedCompile 'com.google.guava:guava:20.0'
		compile 'com.google.inject:guice:4.+'
		testCompile 'org.testng:testng:6.8+'
		testCompile 'org.hamcrest:hamcrest-all:1.3+'
	}

	repositories {
		mavenCentral()
	}

	if (project.hasProperty('triggerBug')) {
		gradle.projectsEvaluated {
			project.conf2ScopeMappings.addMapping(MavenPlugin.COMPILE_PRIORITY + 1, configurations.generatedCompile, Conf2ScopeMappingContainer.COMPILE)
		}
	} else {
		project.conf2ScopeMappings.addMapping(MavenPlugin.COMPILE_PRIORITY + 1, configurations.generatedCompile, Conf2ScopeMappingContainer.COMPILE)
	}

	tasks.install {
		group = 'Upload'
		repositories.mavenInstaller {
			pom.whenConfigured { generatedPom ->
				generatedPom.project {
					name = 'this is a test install'
					description = 'it really is a test install'
				}
			}
		}
	}

Execute as

    gradle clean install

the resulting pom.xml will contain

	<name>this is a test install</name>
	<description>it really is a test install</description>
	<dependencies>
	  <dependency>
		<groupId>com.google.inject</groupId>
		<artifactId>guice</artifactId>
		<version>4.+</version>
		<scope>compile</scope>
	  </dependency>
	  <dependency>
		<groupId>com.google.guava</groupId>
		<artifactId>guava</artifactId>
		<version>20.0</version>
		<scope>compile</scope>
	  </dependency>
	  <dependency>
		<groupId>org.testng</groupId>
		<artifactId>testng</artifactId>
		<version>6.8+</version>
		<scope>test</scope>
	  </dependency>
	  <dependency>
		<groupId>org.hamcrest</groupId>
		<artifactId>hamcrest-all</artifactId>
		<version>1.3+</version>
		<scope>test</scope>
	  </dependency>
	</dependencies>

Execute as

    gradle -PtriggerBug=true clean install

the resulting pom.xml will contain

	<name>this is a test install</name>
	<description>it really is a test install</description>
	<dependencies>
	  <dependency>
		<groupId>com.google.inject</groupId>
		<artifactId>guice</artifactId>
		<version>4.+</version>
		<scope>compile</scope>
	  </dependency>
	  <dependency>
		<groupId>org.testng</groupId>
		<artifactId>testng</artifactId>
		<version>6.8+</version>
		<scope>test</scope>
	  </dependency>
	  <dependency>
		<groupId>org.hamcrest</groupId>
		<artifactId>hamcrest-all</artifactId>
		<version>1.3+</version>
		<scope>test</scope>
	  </dependency>
	</dependencies>

This means

* when `Conf2ScopeMapping.addMapping` is called before `MavenPom.whenConfigured`, the mapping is accounted for during dependency conversion
* when `Conf2ScopeMapping.addMapping` is called after `MavenPom.whenConfigured`, the mapping is NOT accounted for during dependency conversion
* the action registered on the MavenPom is executed in either case

### Your Environment
I am unable to upload information to a cloud service. The build environment is a vanilla gradle 3.2.1 running a recent java8

	$ ./gradlew -version

	------------------------------------------------------------
	Gradle 3.2.1
	------------------------------------------------------------

	Build time:   2016-11-22 15:19:54 UTC
	Revision:     83b485b914fd4f335ad0e66af9d14aad458d2cc5

	Groovy:       2.4.7
	Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
	JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
	OS:           Windows 7 6.1 amd64

**Comment by ipavkovic** [comment]
http://gradle.1045684.n5.nabble.com/pom-generation-and-inherited-dependencies-td1436197.html

**Comment by bigdaz** [comment]
The `maven` plugin (together with the core `Upload` task) are being replaced by the `maven-publish` plugin. As such, we don't plan on making changes to improve the (now legacy) `Conf2ScopeMapping`. Expect to see this type deprecated in Gradle 6.0, for possible removal in Gradle 7.0.
