### ISSUE TITLE
Add dependency deprecation/migration in the Gradle metadata spec

### ISSUE THREAD

**Issue by LouisCAD** [gradle/gradle#10283]
Such a feature would allow gradle and IDEs to emit a warning or an error when the authors of a dependency version decide to deprecate it.

Currently, no such thing exists, and it's a pain to guide users of a library that you want to discontinue to a new one.
This would also help changing the maven coordinates of an artifact.

In Kotlin's `@Deprecated` fashion, it'd nice to allow library authors to have the ability to publish the following when they are deprecating a library:

- Deprecation level (weak warning or warning, I don't think error level would have benefits, quite the opposite)
- Limited Markdown message (support `code`,  **bold**, _italic_, [links](https://gradle.org) and bullet points?), with hard to reach character limit though (let's say 4K characters, including links and other markdown symbols)
- ReplaceWith (with new maven coordinates, optional)
- Link to webpage (for more information, an alternative to link in limited markdown message)

IMHO, this would help the library and apps ecosystem to remain up to date.

I'm happy to help with the design of this feature, including considering compatibility with current Gradle metadata version.

**Comment by ljacomet** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.

***

This would only apply to a newly released version, as repositories will not allow modifications of already released metadata.
