### ISSUE TITLE
Support for nested files in incremental tasks 

### ISSUE THREAD

**Issue by uklance** [gradle/gradle#10281]
### Expected Behavior
When using the incremental task API's, I'd like to know the (root relative) path of each file in the event handlers.

- IncrementalTaskInputs.outOfDate​(Action<? super InputFileDetails>)
- IncrementalTaskInputs.removed​(Action<? super InputFileDetails>)

I suggest adding `InputFileDetails.getPath()` which would be the value of `FileVisitDetails.getPath()` for each `File` originating from a `FileTree` task input. 

### Current Behavior
Currently we only have access to `InputFileDetails.getFile()` but we don't know the relative path. We can actually calculate the path for file adds and updates with a bit of work but it's impossible to calculate the path for nested files which have been removed 

### Context

Let's use the example from [the documentation](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.incremental.IncrementalTaskInputs.html) 

```groovy
class IncrementalReverseTask extends DefaultTask {
     @InputDirectory
     def File inputDir

     @OutputDirectory
     def File outputDir

     @TaskAction
     void execute(IncrementalTaskInputs inputs) {
         if (!inputs.incremental) {
             project.delete(outputDir.listFiles())
         }
         inputs.outOfDate { change ->
             def targetFile = project.file("$outputDir/${change.file.name}")
             targetFile.text = change.file.text.reverse()
         }

         inputs.removed { change ->
             def targetFile = project.file("$outputDir/${change.file.name}")
             if (targetFile.exists()) {
                 targetFile.delete()
             }
         }
     }
 }
``` 

Notice how if files were nested in `inputDir` they will be flattened in `outputDir` because of the following (repeated) line

```
def targetFile = project.file("$outputDir/${change.file.name}")
```

Ultimately I'd like to do the following instead 
```
def targetFile = project.file("$outputDir/${change.path}")
```

Please see [this forum post](https://discuss.gradle.org/t/extending-copy-task-to-support-parallel-execution/32753/10) for a real world use case wanting to implement an incremental copy task

**Comment by lptr** [comment]
You can access the normalized path of the change using the `InputChanges` API introduced in Gradle 5.4 via `FileChange.getNormalizedPath()`. See https://docs.gradle.org/current/userguide/custom_tasks.html#sec:implementing_an_incremental_task

**Comment by uklance** [comment]
Ah, thanks. It would be great if you could mention in the `IncrementalTaskInputs` documentation that it's being deprecated in favour of `InputChanges

**Comment by lptr** [comment]
We are going to deprecate it in Gradle 6.0 and going to mention the new API then.
