### ISSUE TITLE
Gradle Model to manipulate build files

### ISSUE THREAD

**Issue by Dufgui** [gradle/gradle#10280]
### Expected Behavior
Is there any way to read model from gradle as object. And better modify it and dump it ?
We try to answer this interface
https://github.com/quarkusio/quarkus/blob/master/devtools/common/src/main/java/io/quarkus/cli/commands/file/BuildFile.java

just like this
https://github.com/quarkusio/quarkus/blob/master/devtools/common/src/main/java/io/quarkus/cli/commands/file/GradleBuildFile.java

but without the string parsing. Is it possible to access to AST or something equivalent from the connector ?

### Current Behavior
NA

### Context
I am contribute on quarkus, and we try to manipulate the build files from gradle (settings, build and properties).

properties can be loaded as a model to manipulate them. pom.xml form maven can be loaded and manipulate before save it.

but gradle build file and settings are script (groovy or kotlin).
We manipulate them as text until now but it's fragile. 

https://github.com/quarkusio/quarkus/issues/3497

**Comment by big-guy** [comment]
It depends on what you're trying to do, but if you're trying to get data out of the Gradle build, the best way is to go through the Tooling API:
https://docs.gradle.org/current/userguide/embedding.html#sec:embedding_introduction

Nebula has the [lint plugin](https://github.com/nebula-plugins/gradle-lint-plugin) that tries to parse the Groovy DSL and rewrite things.  There was talk about doing this for Kotlin too, but I don't know if that has happened.

Parsing the build file will never give you accurate information for all builds.  There are several limitations with just parsing:
- Dependencies can be defined in files other than `build.gradle` or `build.gradle.kts`. 
- Dependencies can be added by plugins (written in Java, Groovy, Scala, Kotlin, etc)
- Dependencies can be added programmatically based on the _lack_ of dependencies in the build file
- The coordinates for dependencies can be influenced programmatically.  So the build file could have `com.google.collections:google-collections:1.0`, but Gradle replaces that with Guava instead.
- Coordinates/dependencies can be substituted for other Gradle builds

I'm not entirely sure how you intend to use `BuildFile` and `GradleBuildFile`, but I wouldn't try to programmatically rewrite people's build files.

**Comment by Dufgui** [comment]
Many thanks for your reply.
