### ISSUE TITLE
Unable to publish artifacts with custom classifier/extension from java project with Gradle 5.6

### ISSUE THREAD

**Issue by cmuchinsky** [gradle/gradle#10287]
Unable to publish artifacts with custom classifier/extension from java project

### Expected Behavior
Publishing of artifacts with custom classifier/extension should work as it did prior to Gradle `5.6`.

### Current Behavior
When attempting to run `publishToMavenLocal` I get back an error message like:
```
Cannot publish multiple publications with coordinates '... : ... : ...' to repository 'mavenLocal'
```

### Context
Works with `5.5.1`, stopped working with `5.6`.

### Steps to Reproduce 
```
apply plugin: 'java'
apply plugin: 'maven-publish'

task assembleSwagger() {
  def outputFile = file("$buildDir/swagger.yaml")
  outputs.file outputFile
  doLast {
    outputFile << "test"
  }
}
publishToMavenLocal.dependsOn assembleSwagger

publishing.publications {
  api(MavenPublication) {
    artifact(assembleSwagger.outputs.files.singleFile) {
      classifier 'swagger'
      extension 'yaml'
    }
  }
}
```

### Your Environment
Gradle `5.6`, Java `1.8`

**Comment by big-guy** [comment]
I can't reproduce this with your example.  Is it possible that you're adding the same publication twice?

**Comment by cmuchinsky** [comment]
Let me try to come up with a complete reproduction case, just need to sanitize it to remove all the company specific stuff.

**Comment by cmuchinsky** [comment]
@big-guy I have put an example up at https://github.com/cmuchinsky/publishbug, as it stands running `publishToMavenLocal` fails, however if you switch the wrapper to `5.5.1`, it works fine.

**Comment by jjohannes** [comment]
What you are experiencing is an intended change: #9466

Apologies for not mentioning this in the "potentially breaking changes" section of the release notes.

I am not sure what you are intending to do. In your example you declare the same publication twice, with the second overriding the first. Which is probably wrong somehow and that's why we introduced the error.

```
publishing.publications {
  java(MavenPublication) {
    from components.java
  }
  api(MavenPublication) {
    artifact(assembleSwagger.outputs.files.singleFile) {
      classifier 'swagger'
      extension 'yaml'
    }
  }
}
```
Can be replaced with
```
publishing.publications {
  api(MavenPublication) {
    artifact(assembleSwagger.outputs.files.singleFile) {
      classifier 'swagger'
      extension 'yaml'
    }
  }
}
```
Which gives you the same result.

Maybe, in your real build, an `artifactId` setting is missing for one of your publications?

**Comment by cmuchinsky** [comment]
The intention is to publish multiple artifacts from the same build, a jar and corresponding swagger yaml file. Both share the same group/artifactId, but are distinguished by classifier and extension. This is similar to publishing a javadoc/sources jar I would think, right (see the layout of jars under https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/)?

**Comment by jjohannes** [comment]
I think then something like this is what you want (declaring both in one publication):
```
publishing.publications {
  java(MavenPublication) {
    from components.java
    artifact(assembleSwagger.outputs.files.singleFile) {
      classifier 'swagger'
      extension 'yaml'
    }
  }
}
```

Otherwise the result may also be incomplete. E.g., in your original example, the `jar` file is missing in the repo if you run it with `5.5.1`.

**Comment by cmuchinsky** [comment]
Its worth noting that in my "real" build, the `java` vs `api` publications are added in different parts of the build logic, the `java` publication is done via some shared logic in the root project recursing all subprojects, and the `api` publication is explicitly added in the subproject build. Is there a way to get the handle to the other publication so I can add to it?

**Comment by jjohannes** [comment]
The name you give to your publication internally can be used to refer to it everywhere in the build. So in your example the internal names are different: `java` and `api`, but you can use the same name (e.g. `java`) and then it is the same publication:
```
publishing.publications {
  java(MavenPublication) {
    from components.java
  }
}
...
publishing.publications {
  java(MavenPublication) {
    artifact(assembleSwagger.outputs.files.singleFile) {
      classifier 'swagger'
      extension 'yaml'
    }
  }
}

```

**Comment by cmuchinsky** [comment]
Thx, will give that a try!

**Comment by cmuchinsky** [comment]
👍 suggested workaround (use same publishing name) solves the problem.

**Comment by jjohannes** [comment]
We decided to turn the error into a warning: #10352

**Comment by wsargent** [comment]
How would I publish an additional shadow artifact using this syntax?  Using the documented publishing format in https://imperceptiblethoughts.com/shadow/publishing/

```
publishing {
    publications {
        shadow(MavenPublication) { publication ->
            project.shadow.component(publication)
        }
    }
}
```

doesn't give the correct results with `./gradlew publishToMavenLocal` with Gradle 5.6 -- instead I get 'Cannot publish multiple publications with coordinates' as above.

**Comment by ljacomet** [comment]
@wsargent Can you try with Gradle 5.6.1?
This was flagged as a regression and should be fixed in the patch release.
