### ISSUE TITLE
Please make it easier to create custom `Publication`s by not casting to `PublicationInternal`.

### ISSUE THREAD

**Issue by kreiger** [gradle/gradle#10295]
I'm trying to implement an `NpmPublication` similar to `MavenPublication` and `IvyPublication`, that would allow me to deploy artifacts to an NPM repository.

Something like:

    publishing {
        publications {
            myPackage(NpmPublication) {
                ...
            }
        }
    }

### Expected Behavior
It should be possible to create a custom publication without implementing `PublicationInternal`

### Current Behavior
`PublishingPlugin` tries to cast my `NpmPublication` to `PublicationInternal` causing a `ClassCastException`.

**Comment by Phlegethon90** [comment]
This would be very handy. Not any plans in sight?
