### ISSUE TITLE
Groovy documentation inconsistencies (regarding parentheses)

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#10307]
Hi,

I understand that Kotlin seems to be in focus now, but Groovy is still a valid DSL, and I find it weird when sometimes parentheses are used for a method call in your documentations whereas sometimes they are not, the following is just one example out of many:

Quoting from https://docs.gradle.org/5.6/userguide/plugins.html#sec:plugin_version_management :

```
                useModule('org.gradle.sample:sample-plugins:1.0.0')
```

vs.

```
            url '../maven-repo'
```

I don't think this is a good way of documenting code. There are various sources on the Internet about the disadvantages of inconsistency, I recommend reading them, e.g. https://medium.com/@jgefroh/why-consistency-is-one-of-the-top-indicators-of-good-code-352ba5d62020 .

While the https://groovy-lang.org/style-guide.html#_omitting_parentheses is not explicitly advocating the removal of parentheses where possible, I think the generic idea behind optionality is to reduce verbosity but only where readability is not sacrificed, so it really depends on the circumstances, still, should be unnecessary to write parentheses most of the time. And IDEs like IntelliJ IDEA gets that IMO, because it can auto-suggest removing unnecessary parentheses too. Groovy is about concise syntax, and it should be kept that way. If you don't like that syntax, you can switch to Kotlin, but if you code in Groovy, you should do it right.

When I use Gradle in a team, for me this is a frequent source of frustration, because I would always suggest the team members to spare the parentheses for consistency (except for cases when they would help readability of course), while the official documentation is working against me (they would tell that the official docs use parentheses so why should they omit them).

Thanks in advance.

**Comment by rkrisztian** [comment]
Also opened https://issues.apache.org/jira/browse/GROOVY-9230, as the official style guide isn't the clearest either to begin with.

**Comment by lacasseio** [comment]
Thanks @rkrisztian for raising this concern. You are right there should be consistency. I think what you are proposing, reducing verbosity but only where readability is not sacrificed, is a great guideline. Would you have time to help improve this situation? The short term approach would be to double-check all our sample to ensure it's following this guideline. The longer-term approach would be to find a way to lint/reformat our code sample automatically.

**Comment by rkrisztian** [comment]
Hi, @lacasseio, although not within the next few weeks, within 1 or 2 months I guess I can help you with the short-term approach. The longer one might actually be covered by https://github.com/CodeNarc/CodeNarc/issues/433 . But before I do anything, I'd like to see where that issue goes (coding styles are never an easy question).

**Comment by lacasseio** [comment]
@big-guy Any opinion on this? I would lean toward an auto formatter like clang-format or similar.
