### ISSUE TITLE
get gradle statusSuffix info

### ISSUE THREAD

**Issue by FunkyYang** [gradle/gradle#10306]
I used gradle for build application.and I want to get gradle process status in that which is working.
but gradle --status is simple and crude for me,I see the code and I want to get that info.

```
  String statusPrefix = trimToConsole(consoleCols, 0, progressBarPrefix);
            String coloredProgress = trimToConsole(consoleCols, statusPrefix.length(), fill(fillerChar, completedWidth));
            String statusSuffix = trimToConsole(consoleCols, coloredProgress.length(), fill(incompleteChar, remainingWidth)
                + progressBarSuffix + " " + (int) (current * 100.0 / total) + '%' + ' ' + suffix
                + (timerEnabled ? " [" + elapsedTimeStr + "]" : ""));
```
I want to get ```statusSuffix``` is above

**Comment by big-guy** [comment]
Hi @FunkyYang - depending on what you want to do, the [tooling API](https://docs.gradle.org/current/userguide/embedding.html) might be a better fit.  It gives you programmatic access to the Gradle build and you can get progress information out that way.
