### ISSUE TITLE
Add support BOM files to new pluginManagement block

### ISSUE THREAD

**Issue by altro3** [gradle/gradle#10315]
Gradle 5.6 took the first step toward resolving plugin versioning issues. It is very cool! But, this does not solve the problem completely, because at the moment, for example, using Kotlin, you can specify the version of jar files in one BOM file and use it in all services, but you still have to register the plugin version in all services independently.

It would be cool if you could use the same BOM files to control the version of plugins. This would allow full control of the entire platform and minimize fragmentation in the microservice architecture.

**Comment by wind57** [comment]
[this](https://gist.github.com/wind57/003412be5ab10a3d34450d19a77a4f35) is a poor man's solution. This was enough for me to generate the proper things I needed...

**Comment by brighthr-stanton** [comment]
I would also like to see this if ppossible...
