### ISSUE TITLE
Generate @Deprecated annotations for configuration accessors in Kotlin DSL

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#10312]
Follow up to: #8585

**Comment by jjohannes** [comment]
Maybe we can also offer a [ReplaceWith](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-replace-with/index.html).

**Comment by ljacomet** [comment]
Work suspended as causing unexpected feedback in the IDE - see #10794
