### ISSUE TITLE
Add property for max daemons and queue up work if that limit is reached

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#10321]
Here's a scenario:

1. Android Studio is building. (daemon is now BUSY)
2. I run a gradle command from the command line. (original daemon is BUSY, so a new second daemon is created)

### Current behavior/solution
Now I have two gradle daemons running on my local dev machine. This adds a lot of CPU and memory pressure on my device. 

Because I don't want two daemons running for the same project, I kill both. Which means I need to fire up a new daemon all over again.

### Preferred potential solutions
1. the second build command fails fast because the daemon limit is exceeded (identical to https://github.com/gradle/gradle/issues/4051)
2. (better option) the second build command is queued up until the daemon is IDLE

**Comment by matejdro** [comment]
Can we un-stale this? It would be really nice to have.

In OP's case, if first daemon already takes up most of the system's RAM (due to the project's size), second daemon could freeze the system or trigger OOM killer.
