### ISSUE TITLE
@Optional not applied to getter in Kotlin

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#10324]
### Expected Behavior
validateTaskProperties task should flag use of `@Optional` and `@Internal` used together on the same parameter:
```kotlin
@Internal
@Optional
val debug: Property<Boolean> = project.objects.property(Boolean::class.javaObjectType)
```

### Current Behavior
It doesn't, unless `@Optional` is replaced with `@get:Optional`.

### Context
In Kotlin: 

> If you don't specify a use-site target, the target is chosen according to the `@Target` annotation of the annotation being used.

This is fine for all task property annotations except `@Optional` as its target is `{METHOD,FIELD,PARAMETER}` while all another task annotations are `{METHOD,FIELD}`. In Kotlin if the use-site is not specified with `@get:` then PARAMETER is selected before FIELD, so the annotation is not applied to the getter.

It looks like PARAMETER was added to the list to [fix GRADLE-2195](https://github.com/gradle/gradle/commit/08d7b0f6f9a64bbc619ad0c3fc3107e8dbd02114#diff-d5ee54adb81e28ae20cc3b753e0b3212) way back in 2012, and the `@Optional` annotation target was changed to allow internal use. Probably there was never a reason to change it.

### Steps to Reproduce 
Can do this if required but should be very easy to replicate by adding above sample code to a task then running `validateTaskProperties` task and observing no warning.

### Your Environment
N/A

**Comment by rgoldberg** [comment]
@3flex: If Kotlin applies `@Optional` to the parameter, is that the parameter of the setter? Or some other parameter?

That seems to indicate that specifying `@Optional` without any other annotations would also be a bug, right?

See the class javadoc in:

https://docs.gradle.org/current/javadoc/org/gradle/plugin/devel/tasks/ValidateTaskProperties.html

**Comment by 3flex** [comment]
I might not have been clear, the issue isn't with validateTaskProperties but with the `@TARGET` of the `@Optional` annotation and how that works in Kotlin.

If there's no reason for `PARAMETER` to be included as a target for `@Optional` then removing that will resolve this.

**Comment by big-guy** [comment]
@eskatos @bamboo This looks like an ugly footgun. I don't think we can remove the `PARAMETER` target for `@Optional`, but this looks like something we should document and/or recommend always using `@get:` in Kotlin.  thoughts?

**Comment by lptr** [comment]
Where do we use `@Optional` or parameters, though? If it's not useful, can we remove that in 6.0 perhaps?

**Comment by eskatos** [comment]
All usages of `@Optional` as a parameter annotation are on internal `*NotationConverter`s `parseMap()` function that the runtime look for reflectively. So I would say it's not publicly useful.

**Comment by lptr** [comment]
OK, so we could fix this by introducing something like `@OptionalInternal` or something for those purposes, right? And having done that we could remove `PARAMETER` from `@Optional`.
