### ISSUE TITLE
Make PathSensitivity.RELATIVE the default for custom task inputs

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#10346]
Make `PathSensitivity.RELATIVE` the default for custom task inputs in Gradle 6.0+

### Expected Behavior
`PathSensitivity.RELATIVE` should be assigned as the default when task inputs are declared

### Current Behavior
`PathSensitivity.ABSOLUTE` is assigned as the default when task inputs are declared

### Context
In trying to improve our Gradle Enterprise Remote Cache performance,  one particularly frequent and tedious obstacle has been the need to explicitly set the PathSensitivity to RELATIVE on our custom task's input declarations.

E.g:
```
    inputs.files(configurations.myTaskDependencies)
             .withPathSensitivity(PathSensitivity.RELATIVE)
```

The current default is `PathSensitivity.ABSOLUTE` which undermines the cacheability of our artifacts whenever our project builds are homed in different directories, even though this is a very common discrepancy between both our developer machines and our CI machines.

From my experiences it seems like `PathSensitivity.ABSOLUTE` is almost never the right setting, and that `PathSensitivity.RELATIVE` would be a significantly more useful default setting.

**Comment by PedroWitzel** [comment]
I'm looking into contributing to gradle, after using it for more than a couple of years.   
Could I take this?

It's something that I struggled with when implementing my tasks and I can imagine the repercussions it may create.

**Comment by lptr** [comment]
Hi @PedroWitzel, it's great that you are planning to contribute!

This issue might not be a good one to start with as it has some wide-reaching consequences. We have some other ideas on how to simplify the declaration of properties, but they are not part of our roadmap for the foreseeable future.

I'm leaving this issue open as it seems like a good place to collect opinions on the topic.

**Comment by lptr** [comment]
Is there any particular reason to reopen this now @ghale?

**Comment by ghale** [comment]
@steffenyount Can you describe here how this is continuing to affect you?  For instance, is it common in your organization to create new custom tasks (and the sensitivity is frequently omitted)?  Or was this just an issue when optimizing the build?  Or is this surfacing in some other way?  I can try to repeat what you've shared with me, but I think it would be better if you stated it in your own words on this issue.

**Comment by steffenyount** [comment]
@lptr 
Being that the move to Gradle 7+ is just around the corner, now seemed like an opportune time to consider changing some of Gradle's suboptimal out-of-the-box default values.

I understand that changing default behaviors can be controversial, so I'd like to say that I would also be happy to just see a new API allowing me to globally override the default PathSensitivity.ABSOLUTE value.

If the default behavior is changed, that new API would probably be useful to have anyway, since it would enable an upgrade path for teams who rely on the current default PathSensitivity.ABSOLUTE value.

As a wish-list feature in this area: it would be great to have a "smart" default (maybe PathSensitivity.AUTO_DETECT?), where any input paths located inside "well-known" directory roots (directories familiar to Gradle, i.e: "${rootDir}", "${USER_HOME}/.gradle/", "${GRADLE_HOME}/", [a user configurable list?], etc), would effectively be PathSensitivity.RELATIVE to their matching directory root, while input paths outside of those "well-known" directories would be handled with PathSensitivity.ABSOLUTE.

@ghale 
For our org and how this is affecting us:

Our legacy multi-project repo is currently comprised of 572 projects.

To make Gradle Enterprise remote caching work for us we've had to identify, tune, and specify the non-default (i.e: not PathSensitivity.ABSOLUTE) values as follows:
* `withPathSensitivity(PathSensitivity.RELATIVE)` 262 separate times
* `withNormalizer(CompileClasspathNormalizer)` 26 separate times

(I'm less concerned about the 26 `CompileClasspathNormalizer` items)

Each of these entries typically introduces 2 extra lines of otherwise unnecessary boilerplate code into our `build.gradle` files. One of these lines is there to add a human identifiable property name since the default names are often confusing, while the other is there to override the default pathSensitivity. Here are some samples extracted from our build files of what that can look like:

```
task copyXxxxServiceUpgradeArtifacts(type: Copy) {
    inputs.files(configurations.xxxxServiceUpgrade)
            .withPropertyName('configurations.xxxxServiceUpgrade')
            .withPathSensitivity(PathSensitivity.RELATIVE)

    from {
        configurations.xxxxServiceUpgrade.files.collect()
    }
    into xxxxServiceUpgradeDestinationDir
}
```

```
processIntegrationTestResources {
    inputs.files(configurations.corePersistenceEntitiesJar)
            .withPropertyName('configurations.corePersistenceEntitiesJar')
            .withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.files(configurations.xxxPersistenceEntitiesJar)
            .withPropertyName('configurations.xxxPersistenceEntitiesJar')
            .withPathSensitivity(PathSensitivity.RELATIVE)

    eachFile {
        if (it.sourcePath == 'META-INF/persistence.xml') {
            it.filter(ReplaceTokens, tokens: [
                    corePersistenceEntitiesJar: configurations.corePersistenceEntitiesJar.asPath,
                    xxxPersistenceEntitiesJar: configurations.xxxPersistenceEntitiesJar.asPath,
                    classesDir: sourceSets.main.java.outputDir.path
            ])
        }
    }
}
```

```
task generateTypeScript(type: JavaExec) {
    def sourceProtoFiles = [
        'src/main/proto/Config.proto',
        'src/main/proto/Common.proto',
        'src/main/proto/Model.proto'
    ]

    inputs.files(sourceProtoFiles)
            .withPropertyName('sourceProtoFiles')
            .withPathSensitivity(PathSensitivity.RELATIVE)

    outputs.dir new File("${buildDir}/generated-ts/");
    outputs.cacheIf { true }

    classpath configurations.protoTypeScript
    main 'com.xyz.ProtoToTypeScriptGenerator'
    args sourceProtoFiles
}
```

(Note: com.moowork.gradle.node.task.NodeTask extends org.gradle.api.DefaultTask)
```
task compileLintCustomRules(type: NodeTask, dependsOn: [yarnInstall]) {
    description = "Transpiles Typescript code to Javascript"

    def lintInputCustomRulesPath = "./lint/custom-rules"
    def lintOutputCustomRulesPath = "${buildDir}/lint-custom-rules"

    script = file("${node.nodeModulesDir}/node_modules/.bin/tsc")

    inputs.dir("${lintInputCustomRulesPath}")
            .withPropertyName('lint/custom-rules')
            .withPathSensitivity(PathSensitivity.RELATIVE)

    outputs.dir("${lintOutputCustomRulesPath}")
    outputs.cacheIf { true }

    args = [
        "--project", "${lintInputCustomRulesPath}/tsconfig.json",
        "--outDir", "${lintOutputCustomRulesPath}"
    ]
}

```


This somewhat "advanced" boilerplate code in our build scripts is a maintenance burden.

It presents a bit of a trap/obstacle for new developers unfamiliar with Gradle and its quirks, since it's not obvious to the uninitiated when/where these declarations will be necessary. And, also as a consequence it requires us to actively monitor our build performance to catch this source of remote cache performance regressions.

**Comment by lptr** [comment]
On the Gradle side we do realize that the situation right now is not ideal. Changing things for 7.0 is not an option anymore, though, as the release is about to happen real soon now. But focusing on `@PathSensitive` is perhaps not the right approach to start with.

There are at least three different dimensions we “normalize” along:

- path sensitivity
- file order
- file content

You could also argue that there is also file metadata as a normalization aspect when we ignore timestamps and whatnot while parsing JARs on a classpath.

Ideally, we'd have an API (both runtime and annotation) where the compiler can enforce that you consider all these aspects. Then we don’t need validation or defaults to think about. This is our long-term goal. I'm not sure exactly when we'll be able to get there, though. We will make sure to leave a long deprecation period for the existing APIs when it happens.

@steffenyount thanks for providing so much background to your use cases. Specifically for those I think there might be things to do today already.

It is not necessary to register inputs for `Copy` tasks like `copyXxxxServiceUpgradeArtifacts`: specifying the files to copy in the `from` clause already registers them so.

For replacing tokens in resources, I think we should have a better API. I added https://github.com/gradle/gradle/issues/16606 to track that separately.

I don't have a good solution for `generateTypeScript` and `compileLintCustomRules`, but I'm wondering why not create custom class types for these instead of the adhoc tasks? I think it would give you more clear code, and it would also give you clear error messages about any missing annotations.

**Comment by lptr** [comment]
Still want to do this.

**Comment by TWiStErRob** [comment]
Is this now superseded by requiring the annotation everywhere to force the decision?

**Comment by lptr** [comment]
You have to specify normalization for every input property to satisfy the strict plugin validation rules, yes. That said, in most cases that'll be `RELATIVE`, so it would still be meaningful to make this the default. However, I don't see a way to make that happen without making a major change to how annotations work today.

**Comment by TWiStErRob** [comment]
Ah, it's strict only... if this is done: https://github.com/gradle/gradle/issues/22600, then the default path sensitivity wouldn't matter any more? (Assuming `gradlew check`/publish validates)

**Comment by lptr** [comment]
Yes. However, if we could start again (hah!), we could make something like `RELATIVE` be the default, and then we could remove the validation.
