### ISSUE TITLE
Deadlock in artifact transform with dependencies when resolving in a model builder

### ISSUE THREAD

**Issue by cmwarrington** [gradle/gradle#10356]
### Expected Behavior
No deadlock
[artifact_transform_deadlock.txt](https://github.com/gradle/gradle/files/3534725/artifact_transform_deadlock.txt)

### Current Behavior
Able to trigger a deadlock when syncing with studio

### Context
Introduced a new artifact transform with dependencies (auto namespacing) that has artifacts that are resolved as part of the model builder.

### Steps to Reproduce 
Will share the change

### Your Environment
Android Gradle Plugin with experimental change (I can share that or try to make a smaller case)
Reproduced in gradle-5.5 and gradle-5.7-20190818220021+0000-all

**Comment by lptr** [comment]
@cmwarrington do you have a way to reproduce this?

**Comment by cmwarrington** [comment]
So this no longer reproduces for me running AS from head, so I assume it was something odd about the tooling model builders we inherit from IDEA. (AS 3.6 canary 9 is broken, AS 3.6 at head as of 2019-09-17 is OK)
I'm going to close this, as I think the issue was on the IDEA side.
