### ISSUE TITLE
Email asking for scan(m)

### ISSUE THREAD

**Issue by dimorinny** [gradle/gradle#10354]
Right now we have 2 levels of this issue:

Level 1:
**Expected behaviour:** You shouldn't ask email address for giving access to build scan.
**Current behaviour:** You are actually doing.

Level 2:
**Expected behaviour:** I should be able to receive email with link to access my scan.
**Current behaviour:** I don't have any messages (even in spam -- which is the right place for that kind of messages).

**Comment by big-guy** [comment]
Hi @dimorinny 

The build scan is a [public version](https://scans.gradle.com/) of a [paid product](https://gradle.com/enterprise/).  There are terms of service you can read if you're concerned about how your email address would be used.

If you're not seeing an activation email, please contact [help@gradle.com](mailto:help@gradle.com) with a link to the build scan and the email address you tried to use. They can check if there's a problem on the backend.
