### ISSUE TITLE
gradlew emits misleading error message trying to find java

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#10358]
```
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi
```

**Actual:**
The code above swallows the error from `which java`. In my case, `which` wasn't installed, `java` was, so the message was completely misleading.

**Expected:**
Either test for `which` separately, or append the error message from the command to the console output.

**Comment by lacasseio** [comment]
Thanks @asarkar for this issue. You are right the error message should be better. Would you have some spare cycle to look into a PR to improve the error message? Testing the absence of `which` could be tricky but we could run a wrapper test with an empty `PATH` to simulate. I suggest adding the tests in `WrapperIntegrationTest`.
