### ISSUE TITLE
inconsistency when referencing maven repo for dependencies vs for deployment

### ISSUE THREAD

**Issue by eepstein** [gradle/gradle#1036]
### Expected Behavior

Consistent usage and structure.  IF we have this for the repository definition:

    maven {
        url "${myMavenRepoReadUrl}"
        credentials {
            username "${myMavenRepoUser}"
            password "${myMavenRepoPassword}"
        }
    }

THEN we should have something *very* similar for deploying artifacts to a maven repo.  For example:

        mavenDeployer {
            url "${myMavenRepoWrtieUrl}"
            credentials {
                username "${myMavenRepoUser}"
                password "${myMavenRepoPassword}"
            }
        }

### Current Behavior

Instead, today, the deployment config diverges (seemingly arbitrarily) from the dependency repo definition.  Different nesting, the credentials are stored in an "authentication" structure rather than a "credentials" structure; the username now requires an uppercase 'N'.  The variation makes no sense to me, doesn't seem to serve a purpose, and makes configuration both more confusing (more opaque) and more tedious (can't just copy & paste the repository format).

Overall, today it looks like:

    repositories {
        mavenDeployer {
            repository(url: "${myMavenRepoWriteUrl}") {
                authentication(userName: "${myMavenRepoUser}", password: "${myMavenRepoPassword}")
            }
        }

### Context

any ol' build.gradle file with the 'maven' plugin applied.

### Steps to Reproduce (for bugs)

see above.

### Your Environment

Gradle 3.2.1

**Comment by bmuschko** [comment]
The [Maven Publishing plugin](https://docs.gradle.org/current/userguide/publishing_maven.html) is the new plugin for publishing artifacts to Maven repositories. In the long run it will replace the Maven plugin. Among other things it addresses the [alignment of the DSL](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories).

**Comment by oehme** [comment]
Closing as the old plugins won't change anymore and the new plugins are consistent.
