### ISSUE TITLE
Explain how to troubleshoot the repositories used during the resolution

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#10377]
### Expected Behavior

A user should be able to learn how to find out where repositories are added. Or why a repository is used during the resolution.

### Current Behavior

It is expected the user has the advance knowledge for writing debugging build logic to find out the answer to his troubleshooting. The documentation is lacking these troubleshooting steps.

### Context

See https://github.com/gradle/gradle/issues/10376

**Comment by ov7a** [comment]
Will be addressed via
* https://github.com/gradle/gradle/pull/38084
