### ISSUE TITLE
Fully disable jCenter repository

### ISSUE THREAD

**Issue by MGaetan89** [gradle/gradle#10376]
### Expected Behavior

Dependencies are downloaded only from the repositories defined in the `repositories` block (either in `buildscript` or `allprojects`).

### Current Behavior

Dependencies are downloaded from jCenter as well as other defined repositories.

### Context

In my Gradle project, I use a custom Maven repository to download the dependencies I need for my Android project:

```groovy
buildscript {
    repositories {
        maven {
            url 'https://maven.my-company.com/'
        }
    }
}

allprojects {
    repositories {
        maven {
            url 'https://maven.my-company.com/'
        }
    }
}
```

I noticed that on our Jenkins, each Gradle task takes a couple more minutes to complete than on my computer.
With the help of the debug flag (`./gradlew --debug --refresh-dependencies  clean :app:assembleDebug | grep jcenter`), I noticed that each dependency is looked for in jCenter, even though I removed it from the `repositories` blocks:

```
[DEBUG] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Constructing external resource: https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml
```

As our Jenkins has no access to external network, those requests timeout and increase the overall build time.
Is there something to do to completely disable jCenter (or any other not explicitly defined repositories) repository in Gradle?

### Your Environment

I noticed this issue on our Jenkins server, but I could reproduce it on my local computer:
- Ubuntu 18.04
- Java 1.8.0_131
- Gradle 5.6

**Comment by ljacomet** [comment]
Gradle only has one default repository: the Grade plugin portal which is used when there are 0 repositories defined for the `buildscript`.

Otherwise, there is no concept of default repository for build or project dependencies.

So if your build is resolving things from JCenter, it is most likely because a plugin adds it, which is not a recommended practice.

You could dump the list of repositories in a build task by doing something like:

```
task ('dumpRepos') {
    doLast {
        project.repositories.each {
            println it.name
        }
    }
}
```

**Comment by lacasseio** [comment]
To add to what Louis already commented. There shouldn't be any core Gradle plugin that adds repositories such as `jcenter`. The configuration is coming from somewhere in the applied plugins or builds scripts. There are two ways you could approach the problem: 1) finding the where `jcenter` repository is added or 2) disabling the `jcenter` repository by either overwriting the URL or using content matching.

To find where the `jcenter` repository is added, it's best to inject our debugging logic as early as possible. An init script (e.g. `init.gradle`) would be the best place to start:
```
allprojects {
    repositories.all {
        if (url.host == 'jcenter.bintray.com') {
            new Throwable('jcenter repository was just added').printStackTrace()
        }
    }
}
```

Then you execute your build using `./gradlew --init-script init.gradle help`. The call stack that will be printed will show where the repository was added. In my example, I could find the following line: `at build_1gg2cwhc10gojpyg8nekh1109$_run_closure1.doCall(/Users/daniel/gradle/tmp/troubleshooting/build.gradle:8)` which points directly to the build script. It may be inside a plugin.

Although it is not recommended given it will only hide the root issue, you can disable the `jcenter` repository. You can either rename the URL to `https://maven.my-company.com/` or you can filter out everything, see [content filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_a_repository_filter).

**Comment by lacasseio** [comment]
If you see the repository is being added by a core plugin, please reopen the issue.

**Comment by MGaetan89** [comment]
Thank you both for all those useful information.

@ljacomet while investigating this issue on my side, I found a similar piece of code, but I didn't know what to do with it to locate where jCenter was added.

@lacasseio using your debug code, I managed to find that the `jcenter` repository is added by the [Realm](https://github.com/realm/realm-java) Android library in [Realm.groovy#L75](https://github.com/realm/realm-java/blob/789740d8050ba020c8990fd7983fb709b748f7b3/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy#L75). I will open an issue on there project to see if they can remove this line, instead of enforcing the repository.
In the meantime I will disable the `jcenter` repository as you suggested.

**Comment by lacasseio** [comment]
Great! I'm happy you got down to the root of the issue. The Realm plugin is not completely wrong to add the repository but they could do it in a smarter way like adding the repository only if no other repository were defined and adding some way to print a better error message in the even the dependencies they are trying to resolve aren't resolving with repository other than `jcenter` so the user can correctly action on the resolution error. There are other ways to fix this.

**Comment by MGaetan89** [comment]
That sounds better indeed. I linked your comment to the issue I created to give them some context,
