### ISSUE TITLE
unable to load nested project dependencies from build.gradle in gradle 5.5.1

### ISSUE THREAD

**Issue by vsananthchandragiri** [gradle/gradle#10370]
### Expected Behavior
i have tried to call the nested project dependencies in my build.gradle with gradle 5.5.1 version using 
dependencies {
	        api project(':reds-persistence-common')
	}
usually it should include the dependency in the existing project but its not.

### Current Behavior
but when I mention 
dependencies {
	        compile project(':reds-persistence-common')
	}

the dependency project has been loaded and it was working fine.
### Context
I want to implement this with gradle 5.5.1 where with gradle future versions the compile in dependencies will be depricated. so I used api instead of compile but its not working

**Comment by ljacomet** [comment]
Can you please clarify your issue?
As it stands, I am note sure what you are expecting in the working case and what you get in the non working case.
A suggestion for improving your description would be to show the output of `./gradlew dependencies --configuration <problematicConfig>` where `<problematicConfig>` could be `compileClasspath` or `runtimeClasspath` or any other configuration that is resolved by your setup.

**Comment by ljacomet** [comment]
Still missing basic information for understanding the problem, including the Gradle version in use.
Have you tried the suggested `./gradlew dependencies`?
Without knowing which task(s) you are running, it is hard to find an explanation for the `compile` working but not `implementation` or `api`.
But clearly there have been no other reports of `java-library` no longer working with `api` or `implementation` and Gradle has sufficient test coverage that it would show before being released.

**Comment by ljacomet** [comment]
With the given information, my best guess is that the `runCodeGenerator` task uses the `compile` configuration directly.

I will not be able to provide more advice on this, it clearly does not look like an issue in core Gradle and you have not answered any of my specific questions.

**Comment by TeamChocolate** [comment]
@vsananthchandragiri did you ever figure out what the issue was here?
