### ISSUE TITLE
Multiple publications with coordinates warning when running publishToMavenLocal for a gradle plugin artifact

### ISSUE THREAD

**Issue by embee1981** [gradle/gradle#10384]
### Expected Behavior
No warning should be displayed when publishing a gradle plugin.

### Current Behavior
Using gradle 5.6.1 the following is output:

> Task :publishPluginMavenPublicationToMavenLocal
Multiple publications with coordinates 'blah:com.blah:1.0-SNAPSHOT' are published to repository 'mavenLocal'. The publications will overwrite each other!

### Context
In version 5.5.1, no warning was displayed. 

5.6. an error occurs

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishPluginMavenPublicationToMavenLocal'.
> Cannot publish multiple publications with coordinates 'blah:com.blah:1.0-SNAPSHOT' to repository 'mavenLocal'
```
 5.6.1 shows a warning now instead of an error which implies something "bad" will happen which doesn't seem to be the case.
```
> Task :publishPluginMavenPublicationToMavenLocal
Multiple publications with coordinates 'blah:com.blah:1.0-SNAPSHOT' are published to repository 'mavenLocal'. The publications will overwrite each other!
```

### Steps to Reproduce 
Use the following build.gradle file

```
plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
}

group 'blah'
version '1.0-SNAPSHOT'
sourceCompatibility = 1.8

task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier = 'sources'
}

gradlePlugin {
    plugins {
        blah {
            id = "com.blah"
            implementationClass = "com.blah.BlahPlugin"
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
        }
    }
}

wrapper {
    gradleVersion = '5.6.1'
    distributionType = Wrapper.DistributionType.ALL
}
```
Run ```gradle clean publishToMavenLocal```
### Your Environment
Gradle 5.6.1

**Comment by jjohannes** [comment]
@embee1981 thanks for bringing this up. What you are doing seems to work ok, but there is still the potential that it may cause issues if you do more modifications to the publication. That's why we introduced the warning.

However, the example shows that the warning should carry more context. In particular to help you to get rid of it. Because in this case one of the publications is contributed by the _java-gradle-plugin_, it is less obvious where the duplication is.

You can change the `publishing { }` block in your script as follows:

```
publishing {
    publications {
        pluginMaven(MavenPublication) {
            artifact sourcesJar
        }
    }
}
```

By referring `pluginMaven`, you extend the publication that has been contributed by the plugin instead of creating a second one. (If this publication name is not documented anywhere, that's another shortcoming we should address.)

Now, there is no need to redeclare `from components.java`, which was already done by the plugin.

**Comment by embee1981** [comment]
@jjohannes thanks for that, that tweak did the job, no more warning output :-)
This would be good to document somewhere as I'm pretty sure the code I pasted in was copied from the gradle plugin examples section on publishing your own plugin.

**Comment by jjohannes** [comment]
@embee1981 I couldn't find any wrong documentation specifically for plugin publishing. If you should know about anything, please let me know.

But I can see that the sources jar publishing is a common use case for adjusting the publication directly. And if you just copy and paste that from the current documentation about publishing Java, you can easily run into this.

Gradle 6 will support publishing of sources (and Javadoc) out-of-the-box. The sample code in the updated documentation can now be "copy-pasted" independent of the publication name: https://docs.gradle.org/release-nightly/userguide/building_java_projects.html#sec:java_packaging

**Comment by asarkar** [comment]
@jjohannes I'm using Kotlin DSL, and get the same warning. It's not clear to me how to extend the `pluginMaven` publication. The [complete example](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example) doesn't seem so complete after all. 

```
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            pom {
              // bunch of stuff
            }
        }
      }
    }
```

**Comment by jjohannes** [comment]
Hi @asarkar. You need to use the name publication name `pluginMaven` (because that is introduced by the java-gradle-plugin).

For Kotlin DSL it should be:

```
publishing {
    publications {
        create<MavenPublication>("pluginMaven") {
            pom {
              // bunch of stuff
            }
        }
    }
 }
```

**Comment by philbrown-mdt** [comment]
@jjohannes  the documentation for using `from components.java` is directly in the javadocs for *MavenPublication*.

**Comment by TWiStErRob** [comment]
The built-in `pluginMaven` publication can be disabled with:
 * From build.gradle:
    ```gradle
    gradlePlugin { automatedPublishing = false }
    ```
 * From buildSrc:
    ```kotlin
    project.plugins.withId("java-gradle-plugin") { // only do it if it's actually applied
    	project.configure<GradlePluginDevelopmentExtension> {
    		isAutomatedPublishing = false
    	}
    }
    ```

This disables adding the publication in `MavenPluginPublishPlugin`.

Tried and tested in Gradle 5.6.4

**Comment by asarkar** [comment]
Sorry to resurrect a closed thread, but in my case, I want to publish a regular artifact and a uber jar, and get the same warning. This situation is not documented in the Gradle public docs (not a multimodule project).

My questions:
1. What is the correct way to do this?
2. How can I attach sources and Javadoc (same ones) to both publications, a requirement for Maven central?
```
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${project.name}"
            from components.java

            pom {
                ...
            }
        }
        shadow(MavenPublication) { publication ->
            project.shadow.component(publication)

            pom {
                ...
            }
        }
    }
}
```

**Comment by TWiStErRob** [comment]
1. isn't the problem that both your publications have the same coordinates, you might want to change the `artifactId` for the shadow publication to be different (`artifactId = "${project.name}-fat"`). I haven't done this, but it feels like that would work.

2. It's described in the OP of this issue. If the automated publishing is off, then that shows the way and won't fail.

You can a full integrated example here:
https://github.com/TWiStErRob/net.twisterrob.gradle/blob/cc11555e3ac274c8359aa2085a25a12b6e624923/gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/PublishingPlugin.kt#L112-L113

**Comment by jjohannes** [comment]
If you don't want the shadow version to have different coordinates, the best solution is probably **not** to have a second publication, but add the shadow Jar as a addditional variant to the `components.java`. Something like:

```
def shadowElements = configurations.create('shadowElements') {
  canBeConsumed = true
  canBeResolvedFalse = false
  attributes {
      attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
      attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
      attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.SHADOWED))
  }
  outgoing.artifact(tasks.named('shadowJar'))
}

components.java.addVariantsFromConfiguration(shadowElements) {  }
```

The shadow Jar will then be available with a _classifier_ in the name and will be listed in the Gradle Metadata (`.module` file).

In you current setup the metadata is "broken", because it is generated two times and one overrides the other. That's why you get the warning.

See: 
- https://docs.gradle.org/current/userguide/publishing_customization.html#sec:adding-variants-to-existing-components
- https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:variant-aware-sharing

**Comment by asarkar** [comment]
Thank you for your responses. The library in question is currently only packaged as a shadow jar. My intent is to publish the “thin” jar to Maven Central as usual with source and Javadoc, but also make the shadow jar available for existing users. It sounds like adding a variant is the best way to approach that. I’ll try it out and report back.
