### ISSUE TITLE
Groovy 2.5 meta annotations are not respected during Gradle builds

### ISSUE THREAD

**Issue by kod4n** [gradle/gradle#10380]
### Expected Behavior
Usage of the `@Immutable` meta annotation should produce classes with new constructors and methods.

### Current Behavior
Project using groovy 2.5.+ encounter runtime errors when executing tests or generated jars because expected constructors and functions are not present on groovy classes using meta annotations

### Context
I am attempting to upgrade my groovy projects to newer gradle and groovy versions.  This issue is blocking my usage of groovy 2.5.+ as I make heavy use of the `@Immutable` and `@Canonical` meta annotations.

### Steps to Reproduce 
This issue can be reproduced in this github project: https://github.com/kod4n/groovy-gradle-issue.  To reproduce the issue you need to run `./gradlew clean test` and there will be a groovy runtime error on test execution.

### Your Environment
I experienced this issue in my local IDE (Intellij IDEA 2019.2.1).

**Comment by bjornvester** [comment]
I am pretty sure this is a Groovy issue and has nothing to do with Gradle.

You are combining annotations using AnnotationCollector, but a limitation of this is that you cannot combine annotations that are already combined, if that makes sense. Here is how the GroovyDoc explains it:

> NOTE: The aliasing does not support aliasing of aliased annotations

The Immutable annotation is just that - a meta-annotation (see the source code [here](https://github.com/apache/groovy/blob/GROOVY_2_5_X/src/main/groovy/groovy/transform/Immutable.groovy)), so I expect this is why the AST transformation doesn't pick it up in your example. Not that this is explained anywhere in the GroovyDoc :(

Maybe you can ask on the [Groovy users mailing list](https://lists.apache.org/list.html?users@groovy.apache.org) or create a [JIRA ticket](https://issues.apache.org/jira/browse/GROOVY) to discuss if this is something that can be fixed, or at least better explained (assuming this is actually the problem to begin with, of cause.)

You might be able to get around it by putting all the annotations found on Immutable (MapConstructor, ImmutableBase, etc.) directly onto your own annotation collection.

**Comment by kod4n** [comment]
It is interesting that combining previously combined annotations wouldn't work as they have an example in the AnnotationCollector groovydoc http://docs.groovy-lang.org/latest/html/api/groovy/transform/AnnotationCollector.html.  I tried testing out including the annotations inside the collector but that also is not generating the expected bytecode.

I will submit the question to the Groovy mailing list and see where that gets me, thanks for all assistance on this issue.

**Comment by big-guy** [comment]
Thanks for the explanation @bjornvester.

I'll close this issue unless something needs to change on Gradle's side.
