### ISSUE TITLE
Duplicate entry in generated .classpath file in Gradle >= 5.6

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#10393]
### Expected Behavior

Given a `consumer` project with the following dependencies, the `consumer/.classpath` file generated by calling `./gradlew eclipse` should only contain a single `<classpathentry kind="src" path="/producer"/>` entry.

```kotlin
dependencies {
    testImplementation(project(":producer"))
    testImplementation(project(":producer", configuration = "testArtifacts"))
}

```

### Current Behavior

With Gradle 5.6 it contains two such entries and causes Eclipse to show a "duplicate classpath entry" error.

```xml
	<classpathentry kind="src" path="/producer"/>
	<classpathentry kind="src" path="/producer"/>
```

In Gradle 5.5 and below only a single entry is generated.

### Context

The project is unusable in Eclipse until the duplicate entry is deleted manually.

### Steps to Reproduce

1. Clone https://github.com/marcphilipp/gradle-sandbox
1. In `eclipse-multiple-project-dependencies`, run `./gradlew eclipse`
1. Inspect the generated `consumer/.classpath` file or open the project in Eclipse

**Comment by sbrannen** [comment]
Thanks for investigating this!

I'm looking forward to the JUnit 5 projects working in Eclipse again (without having to manually delete those duplicate classpath entries). 😉

**Comment by marcphilipp** [comment]
Possibly related to https://github.com/gradle/gradle/pull/9405.

**Comment by marcphilipp** [comment]
Workaround:

```kotlin
eclipse.classpath.file {
    whenMerged(Action<Classpath> {
        entries = entries.distinctBy {
            if (it is org.gradle.plugins.ide.eclipse.model.ProjectDependency)
                it.path
            else
                it
        }
    })
}
```

**Comment by ryanmkurtz** [comment]
We are seeing duplicate project dependencies ending up in the generated .classpath files with 5.6 and 5.6.1 in [Ghidra ](https://github.com/NationalSecurityAgency/ghidra) as well.

**Comment by sbrannen** [comment]
FYI: to get the above Kotlin-based workaround to work, you'll need the following.

```kotlin
import org.gradle.plugins.ide.eclipse.model.Classpath
```

**Comment by sbrannen** [comment]
I can confirm that the provided workaround solves the issue for the time being. See https://github.com/junit-team/junit5/commit/3e9565a65cf52c58ac1ed3557d8b7769d57ddf29.

Thanks, @marcphilipp!

**Comment by ryanmkurtz** [comment]
Would you mind posting an equivalent groovy workaround?

**Comment by sbrannen** [comment]
> Would you mind posting an equivalent groovy workaround?

I don't have one handy, but the following documentation should be helpful.

https://docs.gradle.org/current/userguide/eclipse_plugin.html#sec:eclipse_modify_domain_objects

**Comment by sbrannen** [comment]
And the customization I wrote here might prove useful as well for the Groovy syntax: https://github.com/spring-projects/spring-framework/blob/8d86a861a1eff13dd1abe14829e4213200509300/gradle/ide.gradle#L50-L57

**Comment by marcphilipp** [comment]
@ryanmkurtz Here's a Groovy version:

```gradle
eclipse.classpath.file {
    whenMerged {
        entries.unique(true) {
            if (it instanceof org.gradle.plugins.ide.eclipse.model.ProjectDependency)
                it.path
            else
                it
        }
    }
}
```
