### ISSUE TITLE
Configuration should be cached

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#10395]
> Gradle runs the configuration phase every time you build.
> I could run `gradle assemble` and then run it again and again, and each time I will have to wait for Gradle to configure the project even though I haven't changed anything.

https://artemzin.com/blog/fundamental-design-issues-of-gradle-build-system/#designissueconfigurationisnotcached

Is the upcoming Instant Execution API designed to address this issue?

**Comment by big-guy** [comment]
Yes, that's one of the goals, but not necessarily to generically cache the configuration for all invocations.

**Comment by ZakTaccardi** [comment]
Experimental support for this has arrived via the new Gradle [Configuration Cache](https://docs.gradle.org/nightly/userguide/configuration_cache.html)!
