### ISSUE TITLE
Add APIs to get back and forth between task class names and decorated ones

### ISSUE THREAD

**Issue by AmrAfifiy** [gradle/gradle#10407]
In android gradle plugin we have some task listeners which need to get the original class name of a task, the way we currently do it is to remove "_Decorated" from the end of the class name if exists.
This is a request to add a public API that converts a decorated task class name to its original class name to avoid possible problems in the future when the way Gradle names decorated classes changes.

**Comment by big-guy** [comment]
@wolfs I think you had poked around with this recently?

**Comment by wolfs** [comment]
I think this is a duplicate of https://github.com/gradle/gradle/issues/8252.
