### ISSUE TITLE
Error message produced for the first build in every new Gradle build with buildSrc

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1040]
When you build a project that has `buildSrc` for the very first time, Gradle emits a warning like:

> Invalidating buildSrc state cache (/path/to/project/buildSrc/.gradle/noVersion/buildSrc) as it was not closed cleanly.

I would expect this to only be produced when we know the "buildSrc state cache" was not "closed cleanly" vs when it never existed.

**Comment by bmuschko** [comment]
I actually fixed that today in my branch. Not sure if it is the right fix but here you go: https://github.com/gradle/gradle/commit/1a7e11be3a3a9183dea71ee4a0ac38a20afb55e9. The reason the message is happening is that the underlying implementation uses `Version1LockStateSerializer.DirtyFlagLockState` which always return `false` for `isInInitialState()`.

**Comment by eriwen** [comment]
Can this be closed @big-guy @bmuschko?

**Comment by bmuschko** [comment]
@big-guy took over my branch back then. Not sure if he kept the change.

**Comment by wolfs** [comment]
The message should be gone. Closing.
