### ISSUE TITLE
`buildNeeded` throws circular dependency error with `java-test-fixtures` plug-in

### ISSUE THREAD

**Issue by jonathan-yan** [gradle/gradle#10410]
### Expected Behavior

The fact of using the `java-test-fixtures` plug-in on a project should not cause circular dependencies when running `buildNeeded`.

### Current Behavior

A circular dependency error is thrown.

### Context

I have a Gradle multi-project where each application has its own CI pipeline for independent deployments which runs `buildNeeded`.

### Steps to Reproduce 

* Example project: [java-test-fixtures-bug.zip](https://github.com/gradle/gradle/files/3560981/java-test-fixtures-bug.zip).
* Run `./gradlew buildNeeded`.

### Your Environment

Build scan URL: N/A

**Comment by vryzhuk** [comment]
Any thoughts on when it will be fixed? Any workaround or alternative could be suggested?
This plugin looks very good but reported issue blocks us to use it for big projects, which uses `buildNeeded` to speedup a build process.

Thanks

**Comment by jjohannes** [comment]
Thanks for reporting this @jonathan-yan and sorry for the delay. A fix is merged and will be in `6.1`. 

@jonathan-yan  and @vryzhuk: Feel free to try the next nightly to verify that it works for you.

**Comment by jonathan-yan** [comment]
Thanks @jjohannes! I can confirm that it works like a charm with Gradle nightly version `6.1-20191128231107+0000`.
