### ISSUE TITLE
Application plugin's :run task's main property is set intermittently null/intermittently non-null when wired through a custom plugin's extension

### ISSUE THREAD

**Issue by lingocoder** [gradle/gradle#10412]
### Context

A custom plugin uses Gradle's built-in *`:run`* task to provide a required capability to its users. What I'm trying to do is make it convenient for users to setup the input my plugin requires, in a centralized extension. My plugin exposes a custom extension that allows users to configure its *`main`* property. The intention is for my extension's *`main`* property to get propagated automatically to the *`main`* property of the Gradle core application plugin's *`:run`* task. My plugin attempts to wire the two up by connecting them using a *`Property<String>`*. 

### Problem

In a TestKit functional test that exercises the wiring up of the two *`main`* properties, executing the application plugin's *`:run`* task sometimes *`SUCCEEDs`* and sometimes *`FAILs`*. The *`:run`* task's *`main`* property is intermittently set to the user-supplied value and sometimes intermittently set to *`null`*. Gradle seems apparently unaware that a value has absolutely been provided. Confusingly, absolutely nothing changes between successful and failed runs in neither the actual code under test, nor the test itself. When the *`:run`* test *`FAILs`*, Gradle reports: *`> No main class specified`*; 

### Expected Behavior

``` 
      ...
      
      BUILD SUCCESSFUL...
      
      ...
      
```

### Actual Behavior

``` 
      ...
      
      > Task :run FAILED

      FAILURE: Build failed with an exception.

      * What went wrong:
      Execution failed for task ':run'.
      > No main class specified      
      
      ...
      
```

### Steps to Reproduce
<sup>[***download example project***](http://bit.ly/RunPropBug)</sup>
1. Code a custom task for your plugin that defines a *`main`* property as one of a number of *`@Input`* properties:

   ```
   @CacheableTask
   public class MyTask extends DefaultTask {
   
       ...
       
       private final Property< String > main;
       
       ...
       @Inject
       public MyTask( ObjectFactory objects ) {
           ...
           this.main = objects.property( String.class );
           ...
       }
       
        ...
   
       @Input
       @Optional
       public String getMain( ) {
           return this.main.getOrElse( "" );
       }
   
       /* No setter for main is implemented */    
       ...
   
       @TaskAction
       void doStuff( ) {
            /*...Do stufff */
       }
    }
   ```

2. Code a corresponding extension:

    ```
    public class MyExtension {

        ...    
        private final Property< String > main;
    
        ...
        @Inject
        public MyExtension( ObjectFactory objects ) {
            ...
            this.main = objects.property( String.class );
            ...
        }
    
        ...
    
        public String getMain( ) { return this.main.get( ); }

        /* No setter for main is implemented */    
        ...
    }
    ```

3. In your plugin, register your task and your extension like so:

    ```
        ...        
        TaskProvider< MyTask > myTask = project.getTasks( ).register( "doStuff", MyTask.class, project.getObjects( ) );
        ...        
        MyExtension myExtn = project.getExtensions( ).create( "setUpStuff", MyExtension.class, , project.getObjects( ) );            
        ...
    ```
    
4. Code the internal implementation of your plugin to connect Gradle's core *`application`* plugin's *`:run`* task *`main`* property to your extension's *`main`* property:

    ```
        ...
        project.afterEvaluate({
            it.tasks.named( "run", JavaExec ).configure({ run ->
                ...
                run.setMain( it.extensions.getByType( MyExtension ).main.get(  ) )
                run.doFirst {
                    println( "$name's main: '" + run.getMain( ) + "'" )
                    ...
                }                
                ...
            });
        });
        ...
    ```

5. Code a TestKit functional test that exercises and verifies the setting of the property

     • the *`com.acme.main.JavaMain`* class is successfully confirmed to exist:

    ```
            ...    
            buildFile << """
            plugins {
                id 'java'
                id 'com.lingocoder.myplugin'
                id 'application'
            }
    
            setUpStuff{
                ...
                main = 'com.acme.main.JavaMain'
                ...
            }
            ...
    
            """
    
            when:
            def result = runner( )
                    .withArguments( ':doStuff', ':run' )
                    .build( )
    
            then:
            ...
            result.task( ":doStuff" ).outcome == SUCCESS
            ...
            result.task( ":run" ).outcome == SUCCESS
    
    ```
6. Run *`./gradlew check`*

    • the functional test's build (*intermittently*) *`FAILs`* with Gradle reporting: „*`> No main class specified`*“

    • the debug message printed in the overridden *`:run`* task's *`doFirst`* closure, prints: „_run's main: 'null'_“ to the console

    • Because of the flakey nature of the bug, *`gradlew check`* sometimes results in a *`BUILD SUCCESSFUL`*. These are some other tasks that have also produced the bug:

        gradlew functionalTest
        gradlew functionalTest --tests ApplyApplicationPluginFunctionalTest
        gradlew --no-build-cache clean publish functionalTest

### Environment

    ------------------------------------------------------------
    Gradle 5.5.1
    ------------------------------------------------------------
    
    Build time:   2019-07-10 20:38:12 UTC
    Revision:     3245f748c7061472da4dc184991919810f7935a5
    
    Kotlin:       1.3.31
    Groovy:       2.5.4
    Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
    JVM:          12 (Oracle Corporation 12+33)
    OS:           Windows 7 6.1 amd64
    

### What have you tried?

I've stepped through the code with a debugger. I could see in the debugger that the property was definitely being set:
 
![lingocoder custom run intermittent existence bug 0 d](https://user-images.githubusercontent.com/49788472/64059383-0aa5e080-cbab-11e9-8e11-50cf16a7de8c.png)

Following, to the best of my understanding, the User Guide examples for [*this*](http://bit.ly/AltOftUsd), [*this*](http://bit.ly/ObjFact) and [*this*](http://bit.ly/PropProv) has not solved the problem for me yet. I have also reached out to [*Gradle's Community Slack*](http://bit.ly/MyObjFact). I haven't managed to find an obvious root cause yet. 

I've created [*a scaled-down model of my plugin project*](http://bit.ly/RunPropBug) that reproduces the issue. The problem is frustratingly flakey about when it decides to reveal itself. All I know is: *If I run the functional test several times, the bug will eventually happen*. I've bundled into the attached demo project, a copy of the test reports folder that captured the outcome of one failed run. TIA :)

**Comment by lingocoder** [comment]
Related to #11124 & #11125

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/11643
