### ISSUE TITLE
Better incremental compilation support

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#10420]
As discussed with @oehme , it would be neat to improve the current algorithm to detect classes to recompile.

For example, consider these classes:
```
class A {
  private B b
}
class B {
  private C c
}
class C {
}
```

The previous algorithm in `ClassSetAnalysis.getRelevantDependents` would recompile all classes, if `C` was changed, because it walks the whole dependency graph and does not consider the "accessibility" of a dependency.

I.e. changing the class `C` should only recompile `C`,because it has changed, and `B` as a user of `C` and not `A`, because it is not affected by the change in `C`.

The updated algorithm does exactly this by checking the "accessibility" (`private` or not). "Accessible" dependents are recursively evaluated as before, but "private" dependents are not.

**Comment by snazy** [comment]
As a follow-up, it could be possible to further enhance the algorithm to not just distinguish between `private` and non-`private`, but to also distinguish:
* "package private"
* `protected`

However, the current proposal in #10419 is probably a "good enough" improvement for now.

**Comment by oehme** [comment]
Done in #10419
