### ISSUE TITLE
Why isn't DefaultGradleRunner.withJvmArguments part of public API (GradleRunner)?

### ISSUE THREAD

**Issue by edeandrea** [gradle/gradle#1043]
When using Gradle's TestKit I'm wondering why [DefaultGradleRunner.withJvmArguments](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/DefaultGradleRunner.java) isn't included in [GradleRunner](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/GradleRunner.java)'s public API? This is something we use extensively in our integration/functional test suite - being able to pass -D parameters to the build under test in order to test functionality we provide in our plugins.

It would be nice if this was included in the public API - since our code analysis tools flag our code because we are using an "internal" API and not a public one.

### Expected Behavior
[GradleRunner](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/GradleRunner.java) should include the **withJvmArguments** methods that are present on [DefaultGradleRunner](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/DefaultGradleRunner.java).

### Current Behavior
The behavior wouldn't change - just that this functionality would be included on the public API rather than having to cast to an internal Gradle class.

### Context
Our enterprise plugins offer ways to "switch" behaviors by the presence of certain environment variables. Some of the things we do are:

 * Allow overriding of the base URL our enterprise Artifactory server
 * Within the base URL of our enterprise Artifactory server, allow overriding which repo to resolve artifacts from
 * When publishing artifacts to our enterprise Artifactory
    * Which repo to publish to
    * Credentials in order to perform publish
 * Skip running our custom "auto-update" feature for the build invocation

In order to test these features we require the ability to set JVM arguments when launching via the Gradle TestKit.

**Comment by oehme** [comment]
Unrelated to the question whether this method should be public: The use cases you mentioned should probably be modeled using project properties, so users can conveniently overwrite them both on the command line and in `gradle.properties` files. Project properties can already be passed with TestKit.

**Comment by edeandrea** [comment]
Thanks for the comment Stefan. Generally speaking some of these properties aren't known by the project itself and are instead injected by a CI environment - which could still be done as a project property.

The bigger issue is when using init scripts. We package a custom Gradle distro that has some init scripts "pre-packaged" inside. Those init scripts (inside the initscript block) need access to those values as well, which isn't possible via a project property.

**Comment by bmuschko** [comment]
The main reason for not exposing the method `withJvmArguments` as public method is that system properties are not propagated if you run `GradleRunner` in debug mode. TestKit does not fork a new daemon JVM that can use the system property. To avoid confusion among end users of TestKit we decided not to expose the option.

You can already provide system properties to a test via `gradle.properties` - of course that only works if you run `GradleRunner` in non-debug mode. I don't fully understand the use case you are describing in regards to init scripts. TestKit doesn't necessarily aim for testing init scripts. The testing happens rather on the level of a plugin or a build script. I'd try to move all logic you have in your init script right now into a plugin that actually uses it. That'll make the logic testable.

**Comment by edeandrea** [comment]
One thing our init script that is packaged in our distro does in the initscript {} block is to set up the repositories {} block to point to our enterprise Artifactory, for which the URL & repo to resolve from within Artifactory can be over-ridden by setting system/env properties. Once that is set, the dependencies {} block is added to the initscript {} block which gives the coordinates of a few dependencies to bring in. It also registers a `BuildListener` that does various things, including things which can, again, be over-ridden using system/env properties.

In addition - there is also a system property which cancels the wiring of some of the dependencies - one of which is the dependency containing the plugins - which is wired in with the TestKit's `withPluginClasspath()` and the overall use of the `java-gradle-plugin` in the main build.

**Comment by bmuschko** [comment]
From what I read in your last comment you want to test the logic of an init script in conjunction with the applied plugins in that script. I guess you could do that by setting up a `gradle.properties` and an init script as part of your test fixtures in your test. In the `gradle.properties` you can set relevant environment variables as need for the test case.

Example:

```
file('gradle.properties') << """
     systemProp.myProp=test # Setting a system property
     MY_ENV_VAR_prop=somevalue # Setting an environment variable
"""
```

The init script could be written in a similar fashion:

```
file('some/dir/init.gradle') << """
    initscript { ... }
"""
```

To be able to use the init script you'd have to provide the `some/dir` via `GradleRunner.withTestKitDir()` or provide it via the `-g` argument. I'd probably move the `BuildListener` into a plugin which can be tested in isolation.

Overall, I think you can support the use case without adding `DefaultGradleRunner.withJvmArguments()` to the public API _if_ you run the `GradleRunner` instance in non-debug mode. I'd like to stay away from opening up the method for the reason mentioned in my previous post. It will simply cause more confusion than it's worth.

**Comment by edeandrea** [comment]
Hi Ben - thanks for the input.

The init script we have is "rolled-up" into our custom distro. In the main build of our distro we do this:

```
def getGradleCoreDistroRoot = { System.env.GRADLE_CORE_DISTRO_ROOT ?: gradle.gradleHomeDir }

task createCustomGradleDist(type: Zip, dependsOn: 'assemble', description: 'Creates a custom Gradle distribution containing the custom plugins') {
	baseName = project.getProperty('artifactId')
	classifier = 'bin'
	
	outputs.upToDateWhen { false }

	into("my-gradle-bin") {
		into('init.d') {
			from("${sourceSets.main.output.resourcesDir}/initScripts") {
				filter(org.apache.tools.ant.filters.ReplaceTokens, tokens: [
					GROUP_ID: project.group,
					ARTIFACT_ID: project.getProperty('artifactId'),
					ERSION: project.version,
					ARTIFACTORY_BASE_URL: 'http://url.to.our.internal/artifactory,
					ARTIFACTORY_RESOLVE_REPO: 'java-libs-dev'
				])
			}
		}
		
		from captureBuildSystemVersion
		from(getGradleCoreDistroRoot()) {
			exclude 'init.d/**'
		}
	}
}

integTest {
	dependsOn 'createCustomGradleDist'
	
	afterEvaluate {
		systemProperty 'initScriptLocation', "$sourceSets.main.output.resourcesDir/initScripts/my-gradle.gradle"
		systemProperty 'gradle.user.home', "$buildDir/tmp/TestKit"
		systemProperty 'distLocation', createCustomGradleDist.archivePath.absolutePath
		systemProperty 'gradleVersion', gradle.gradleVersion
	}
}
```

Then for our integration tests (using Spock) we have a base class that does the following - it points to the gradle distribution which was created prior to the execution of the integTest tasks.

I thought about moving the build listener into a plugin - but the problem there is that we are hooking into the `projectsLoaded` event - which if applied as part of a plugin would be too late in the lifecycle in order to capture that event.

```
import spock.lang.Specification

import org.gradle.testkit.runner.BuildResult
import org.gradle.testkit.runner.GradleRunner

import org.junit.Rule
import org.junit.rules.TemporaryFolder

import org.apache.commons.io.FileUtils

abstract class AbstractIntegrationTester extends Specification {
	@Rule
	TemporaryFolder tempFolder

	protected File testDir

	def setup() {
		def resourceURL = getClass().getResource(getClass().simpleName)
		def sourceDir = new File(resourceURL.toURI())
		def integrationTestBaseDir = System.properties['INTEGRATION_TEST_BASE_DIR']
		this.testDir = this.tempFolder.folder

		if (integrationTestBaseDir != null) {
			testDir = new File(integrationTestBaseDir, getClass().simpleName)
		}

		println "Copying from $sourceDir to $testDir"
		FileUtils.copyDirectory(sourceDir, testDir)
	}

	protected BuildResult build(String... commands) {
		def buildResult = createAndConfigureGradleRunner(commands).build()
		println buildResult.output

		buildResult
	}

	protected BuildResult buildAndFail(String... commands) {
		def buildResult = createAndConfigureGradleRunner(commands).buildAndFail()
		println buildResult.output

		buildResult
	}

	protected GradleRunner createAndConfigureGradleRunner(String... commands) {
		def distLocation = new File(System.properties['distLocation'])

		def runner = GradleRunner.create()
			.withProjectDir(this.testDir)
			.withPluginClasspath()
			.withJvmArguments('-DdontResolvePluginsFromArtifactory=true', '-DskipUpdateCheck=true')

		distLocation.exists() ?
			runner
				.withGradleDistribution(distLocation.toURI())
				.withArguments(['-s'] + (commands as List)) :
			runner
				.withGradleVersion(System.properties['gradleVersion'])
				.withArguments((['-I', System.properties['initScriptLocation']] + (commands as List)) as String[])
	}
}
```

**Comment by bmuschko** [comment]
> I thought about moving the build listener into a plugin...

You can bundle pretty much any class into a JAR file and and add it to the build script's classpath via `buildscript` or to an init script's classpath via `initscript`. It doesn't _have_ to be applied through a plugin.

**Comment by edeandrea** [comment]
You are correct - which is exactly what I'm doing. Give me a few minutes to "sanitize" my init script & I will share that as well. Maybe that will help you get a better picture as to what I'm trying to do.

**Comment by edeandrea** [comment]
Here's our init script

```
rootProject {
	ext {
		// This tells that the build was executed from the full company Gradle distro rather than simply wiring in some plugins in an app's build file
		fullBuildSystemUsed = true
	}

	buildscript {
		def artifactoryBaseUrl = System.properties['company.gradle.artifactory.baseUrl'] ?: '@ARTIFACTORY_BASE_URL@'
		def artifactoryResolveRepo = System.properties['company.gradle.artifactory.resolveRepo'] ?: '@ARTIFACTORY_RESOLVE_REPO@'
		def artifactVersion = System.properties['company.gradle.version'] ?: '@VERSION@'

		repositories {
			maven {
				url "$artifactoryBaseUrl/$artifactoryResolveRepo"
			}
		}

		dependencies {
			if (!Boolean.getBoolean('company.gradle.artifactory.dontResolveAigPluginsFromArtifactory')) {
				classpath "@GROUP_ID@:@ARTIFACT_ID@:$artifactVersion"
			}
		}
	}
}

// Also make the plugins available to this init script
initscript {
	def artifactoryBaseUrl = System.properties['company.gradle.artifactory.baseUrl'] ?: '@ARTIFACTORY_BASE_URL@'
	def artifactoryResolveRepo = System.properties['company.gradle.artifactory.resolveRepo'] ?: '@ARTIFACTORY_RESOLVE_REPO@'
	def artifactVersion = System.properties['company.gradle.version'] ?: '@VERSION@'

	repositories {
		maven {
			url "$artifactoryBaseUrl/$artifactoryResolveRepo"
		}
	}

	dependencies {
		if (!Boolean.getBoolean('company.gradle.artifactory.dontResolveAigPluginsFromArtifactory')) {
			classpath "@GROUP_ID@:@ARTIFACT_ID@:$artifactVersion"
		}
	}
}

// Using reflection here because this init script itself has to compile, and if SystemBuildListener isn't on the class path
// (which should only happen during integration testing), then the script will fail to compile
// This way the scipt will compile but at runtime won't be activated
try {
	def systemBuildListenerClass = Class.forName 'my.company.gradle.build.SystemBuildListener'

	if (systemBuildListenerClass) {
		addBuildListener systemBuildListenerClass.newInstance()
	}
}
catch (ClassNotFoundException ex) {
	if (!Boolean.getBoolean('company.gradle.artifactory.dontResolveAigPluginsFromArtifactory')) {
		// re-throw it
		throw ex
	}

	// Otherwise eat it
}
```

**Comment by bmuschko** [comment]
OK, thanks. Getting back to your original question...given that you can provide system properties and environment variables via `gradle.properties` I think you can fulfill your use case without opening up `DefaultGradleRunner.withJvmArguments()` as public API. Am I missing something?

**Comment by edeandrea** [comment]
No it doesn't work for me. When I put

```
systemProp.company.gradle.artifactory.dontResolveAigPluginsFromArtifactory=true
systemProp.company.gradle.skipUpdateCheck=true
```

in the test project's `gradle.properties`, the `if (!Boolean.getBoolean('company.gradle.artifactory.dontResolvePluginsFromArtifactory'))` statement inside `initscript { dependencies {} }` does not resolve correctly because the system property `company.gradle.artifactory.dontResolvePluginsFromArtifactory` is not found.

**Comment by bmuschko** [comment]
Would you mind setting up a minimalistic, sample project that reproduces the issue and share it on GitHub?

**Comment by edeandrea** [comment]
Sure I can do that

**Comment by edeandrea** [comment]
Here's a sample project - https://github.com/edeandrea/gradle-testkit-jvm-arguments

**Comment by bmuschko** [comment]
Thanks for the example project. Would you mind stripping down the example to the bare minimum? I think there's a lot of code that's not really relevant to the problem.

**Comment by edeandrea** [comment]
Sorry for the delay in getting back to you as I was away on vacation. I've removed some things - I'm not sure how to make it any simpler...

**Comment by bmuschko** [comment]
We are not planning to expose this as public API as I am sure it will allow users to shoot themselves into their foot given the [arguments described in my comment](https://github.com/gradle/gradle/issues/1043#issuecomment-268396721).
