### ISSUE TITLE
A plugin version is mistakenly identified as already published

### ISSUE THREAD

**Issue by dmitrykuzmin** [gradle/gradle#10442]
When I try to publish our plugin `io.spine.tools.gradle.bootstrap` of version `1.0.3`, I get the following error:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':plugin:publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'io.spine.tools.gradle.bootstrap', version: '1.0.3' exists already. It was created: 2019-03-22 15:53:38.756
``` 

When I navigate to the plugin [page](https://plugins.gradle.org/plugin/io.spine.tools.gradle.bootstrap) though, there is no version `1.0.3` there, and the plugin version is also not available when used as a dependency in other projects.

This seems like broken plugin upload.

### Expected Behavior
The plugin version is either successfully published when I try to do that, or is available on Gradle Plugins portal.

### Current Behavior
The plugin version can neither be published nor is available anywhere.

### Context
Just bumpimg version to `1.0.4` or changing it to something different from `1.0.3` is not really viable solution for us, so it would be great if this issue could be resolved in some other way.

### Steps to Reproduce 
This just seems like a bug that happens randomly from time to time with plugin publishing. We had the previous plugin version bugged like this before, but then we could just increment the version as a workaround.

### Your Environment
Publishing happens on Travis CI, Ubuntu 16.04.6 LTS.
The latest version (`0.10.1`) of [`plugin-publish`](https://plugins.gradle.org/plugin/com.gradle.plugin-publish) plugin is used.

**Comment by big-guy** [comment]
Was a 1.0.3 version published and then deleted? I can manually remove any trace of 1.0.3, but it would be good to know how it might have gotten into this state.

**Comment by dmdashenkov** [comment]
There was an _attempt_ to publish the `1.0.3` version before. However, it failed. I cannot tell why exactly, cause, unfortunately, the CI log was lost when we restarted the build. After a restart, there was the error message about the duplicate version already.

Please feel free to investigate our [config](https://github.com/SpineEventEngine/bootstrap/blob/master/gradle/plugin.gradle) for publishing the plugin and the latest [build log](https://travis-ci.com/SpineEventEngine/bootstrap/builds/125469235).

**Comment by big-guy** [comment]
Hmm, all right.  Nothing pops up in the logs, I've manually cleared the version and you should be able to try again.

Let me know if it doesn't work again.

**Comment by dmdashenkov** [comment]
This helped and the version is published now. Thanks!

**Comment by dmdashenkov** [comment]
@big-guy, the issue repeated. When publishing another version of the plugin.
[Here](https://travis-ci.com/SpineEventEngine/bootstrap/builds/126235370) is the Travis build.

The Gradle plugin publishing plugin ran out of memory:
```
Publishing plugin io.spine.tools.gradle.bootstrap version 1.0.8-SNAPSHOT
Publishing artifact build/libs/plugin-1.0.8-SNAPSHOT-sources.jar
Publishing artifact build/libs/plugin-1.0.8-SNAPSHOT-javadoc.jar
Publishing artifact build/libs/plugin-1.0.8-SNAPSHOT.jar
> Task :plugin:publishPlugins FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':plugin:publishPlugins'.
> Java heap space
```
We will change the heap size for future builds.

Could you please take a look at the version `1.0.8-SNAPSHOT`? I suspect, it left some trails in the repository.

**Comment by dmdashenkov** [comment]
@big-guy, also, it seems that there's something wrong with the metadata itself.
```
Plugin: 'io.spine.tools.gradle.bootstrap', version: '1.0.8-SNAPSHOT' exists already. It was created: 2019-03-22 15:53:38.756
```
The date `2019-03-22` is clearly off. Instead, the build which tried to publish this version ran today.
