### ISSUE TITLE
Non-static things in buildSrc are unexpectedly cached

### ISSUE THREAD

**Issue by hannespernpeintner** [gradle/gradle#10446]
Hey guys, happy gradle user here, thanks for your work :) But of course I have a problem I'm not able to solve by myself.

### Expected Behavior
I would expect that non-constant buildSrc elements are evaluated on every gradle execution.

### Current Behavior
buildSrc classes seem to be cached between gradle executions with no configuration way to avoid that.

### Context
We have a lot of projects that use multi project layouts. Many of them include a requirement: We need to find a free random port for a heavyweight server, then we have to start a server shared by all subprojects for testing, execute all project's tests and afterwards stop the whole thing. The port has to be passed into all subproject's tests, so we use test task configuration here (system properties, works fine). Now the thing: The random port is global in the project and we would love to place it exactly where we have other global variables, like versions, string identifiers etc. We're using an object declaration in the buildSrc directory for that.
The code looks like
`object Ports { val serverPort = java.net.ServerSocket(0).use { it.localPort } }`

However, subsequent executions lead to the ever same port number.

Our workaround is now to use extra properties on the project instance, but it worsens the code structure and the type safety, so we would love to somehow have our need supported by the buildSrc structure.

Is there any misconception on our side regarding the expectations about the buildSrc (and static objects)? Is there any way we haven't seen to enforce recompilation/reloading/cache invalidation or whatever to enable our use case?

### Steps to Reproduce 
Maybe I can create an example project for you, as I can't share the real project, give me some feedback if needed, that would be effort for me :)

### Your Environment
gradle-5.6.1
we're using kts
if enything's unclear, let me know

Thank you,
Hannes

**Comment by eskatos** [comment]
Hi @hannespernpeintner,
Thank you for the report!

Your `Ports.serverPort` is effectively static. Gradle reuses classloaders in order to speed up the builds. So what you're experiencing is expected.

IIUC you want a server port to be allocated for each build invocation, shared by the whole build (ie. all subprojects).

An extra property on the root project is a good idea because they provide just that.
It could also be a full blown extension on the root project, see https://docs.gradle.org/current/userguide/custom_plugins.html#sec:getting_input_from_the_build, but I'll leave that to your exercise and demonstrate using an extra properties. The same concepts apply.

One way to do that with something in `buildSrc` that can easily be used from build scripts with IDE completion would be:

```kotlin
// buildSrc/src/main/kotlin/Ports.kt

val Project.serverPort: Int
    get() = rootProject.extra["serverPort"] as? Int
        ?: ServerSocket(0).use { it.localPort }.also {
            rootProject.extra["serverPort"] = it
        }
```

Then in your build script you can simply refer to it:

```kotlin
// build.gradle

tasks {
    withType<Test>().configureEach {
        // e.g. pass the server port to tests as a system property
        systemProperty("serverPort", project.serverPort)
    }
}
```

HTH

**Comment by hannespernpeintner** [comment]
Thank you very much for the super fast and very helpful answer, I already suspected that it's because of classloaders. I think your code doesn't work ootb because you can't use _extra_ on Project in the buildSrc and there is an exception when accessing an extra property that doesn't already exist. I'm going to use the following snippets in our projects, maybe it's helpful for someone else:

```
class RootProjectExtra<T>(val initializer: () -> T): ReadOnlyProperty<Project, T> {
    override operator fun getValue(thisRef: Project, property: KProperty<*>): T {
        return thisRef.getOrInit(property.name, initializer)
    }
}

@SuppressWarnings("unchecked")
private fun <T> Project.getOrInit(key: String, initializer: () -> T): T {
    val ext = rootProject.extensions.extraProperties

    return if(ext.has(key)) {
        ext[key] as T
    } else {
        initializer().also {
            ext[key] = it
        }
    }
}
```

and usage afterwards:

```
val Project.random by RootProjectExtra { Random.nextInt().toString() }
```
or
```
val Project.random: Int
    get() = getOrInit("serverPort") { ServerSocket(0).use { it.localPort } }
```

Any chance to get something like this implemented in gradle, so that I don't have to explain my colleagues what's going on here? O:-)

**Comment by eskatos** [comment]
Right, you need to apply the `kotlin-dsl` plugin in `buildSrc` and then import `org.gradle.kotlin.dsl.*` to use `project.extra`.

```kotlin
// buildSrc/build.gradle.kts
plugins {
    `kotlin-dsl`
}
```

And you're right, it throws `UnknownPropertyException`.

Here's a revised version that doesn't throw nor requires the `kotlin-dsl` plugin:
```kotlin
val Project.serverPort: Int
    get() =
        if (rootProject.ext.has("serverPort")) rootProject.ext["serverPort"] as Int
        else ServerSocket(0).use { it.localPort }.also {
            rootProject.ext["serverPort"] = it
        }
```

It's about the same as your approach, you generalized it. Glad you got it working.

This issue would be more suited for a forum discussion at https://discuss.gradle.org/. I'm going to close it.

About your last point, please open a new feature request if you feel strongly about it.
