### ISSUE TITLE
Support adding tools.jar to dependencies

### ISSUE THREAD

**Issue by opticyclic** [gradle/gradle#10451]
### Expected Behavior
Following on from https://issues.gradle.org/browse/GRADLE-1477:

Gradle should automatically add tools.jar to the JDK classpath.

### Current Behavior

To make my tests run I have to add a test dependency. 
Either

    testCompile files("${System.getProperty('java.home')}/../lib/tools.jar")

Or

    testCompile files(org.gradle.internal.jvm.Jvm.current().toolsJar)

### Context
When running Java tests with Mockito from gradle it fails with the following because tools.jar is not included in the JDK:

    Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
    java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
    ...
      at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@55f10552
      ... 70 more
    Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
    Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)
      ... 75 more
    Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@70dba7d
      ... 85 more
    Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed

### Your Environment

    /gradlew --version
    ------------------------------------------------------------
    Gradle 4.10.1
    ------------------------------------------------------------
    Build time:   2018-09-12 11:33:27 UTC
    Revision:     76c9179ea9bddc32810f9125ad97c3315c544919
    Kotlin DSL:   1.0-rc-6
    Kotlin:       1.2.61
    Groovy:       2.4.15
    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
    JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
    OS:           Linux 5.1.0-050100-generic amd64

**Comment by maityyy** [comment]
```java
// Java Attach API
implementation files('C:\\Program Files\\Java\\jdk1.8.0_261\\lib\\tools.jar')
```
Works fine for me.

**Comment by opticyclic** [comment]
That's great that it works for you 
It will fail as soon as you run it on a build server using a Linux agent.
Or on another developers PC with a different JDK.
Or someone using a Mac.
Or a 32 bit JDK.
Or a JDK installed in a different location.
Or any other combination that makes this proposed solution not portable.

**Comment by maityyy** [comment]
```
implementation files("${System.properties['java.home']}/../lib/tools.jar")
```
:wink:
