### ISSUE TITLE
`@ReplacedBy` should work like `@Internal`

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#10452]
Especially, there shouldn't be any further checks for compatible modifiers. `@ReplacedBy` means to ignore the property.

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
Looks like we have an integration test that explicitly says that inherited properties marked with `@ReplaceBy` should be kept intact:

https://github.com/gradle/gradle/blob/63ab3d823d01d0950a4000fd5895ab0554c04375/subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/ValidateTaskPropertiesIntegrationTest.groovy#L904-L938

We need to decide if we are okay with changing that. I think I would.

**Comment by wolfs** [comment]
I think on the same level there shouldn't be conflicting property types, so the test is still fine. Replacing `@ReplacedBy` with `@Internal` in the test should also make the test fail.

What I need for the current use-case is that supporting annotations from the superclass are not taken into account.

In general, we could filter out not-supported annotations from the superclass if the current class changes the type of the property. Since the only use-case for this is ignoring a property, I don't think it would help in other cases. At least I can't come up with another use case.
