### ISSUE TITLE
Document JVM ecosystem attributes, their values and the compat / disamb rules

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#10469]
To understand variant aware matching, one needs to understand the used attributes.

We need to document the attributes of the JVM ecosystem as this is one of their biggest usage so far.

**Comment by jjohannes** [comment]
There is already some documentation where this is used as an example in `variant_model.adoc#sec:variant-aware-matching`.
If we address this issue, maybe as part of the Java plugins documentation (?), some content from that section can be reused/transferred and that section can then link to the new section. Another option would be to keep it all in `variant_model.adoc`, but add a section explicitly about the JVM attributes. 
Another source from where we can take information is the latest metadata specification.

**Comment by jjohannes** [comment]
I think we can work this into the section which is currently called "Declaring Attributes" and which we moved up to live next to the "Understanding variant selection" section.
I think that section should be slightly renamed then and "declaring attributes" then becomes one part of it.
