### ISSUE TITLE
`gradle[w].bat`/start scripts leak the `CLASSPATH` environment variable into the Java process

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#10463]
=== Expected behaviour
Environment variables used inside the batch scripts should not leak into the calling process.

=== Current behaviour
Batch scripts leak into Java process. See https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt#L83

**Comment by big-guy** [comment]
This is used by all start scripts, not just gradlew

**Comment by sschuberth** [comment]
I guess the best way to address this is would be by not setting `CLASSPATH` at all and solving the [long classpath issue for start scripts](https://github.com/gradle/gradle/issues/1989#issuecomment-550192866) in the same run by [using a pathing JAR as already done for JavaExec tasks](https://github.com/gradle/gradle/issues/10114#issuecomment-530908458).

**Comment by ljacomet** [comment]
Could someone add _why_ this is a problem to the issue description? 
Or describe a use case that this behavior impacts.

**Comment by ljacomet** [comment]
Closing as there was not more information provided explaining why / when this is a problem.
