### ISSUE TITLE
Complete documentation on fine grained dependency managment APIs

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#10468]
In `fine_grained_dm_apis.adoc`:

* the sections `resolution-result-api` and `artifact-view-api` need to be filled in, removed or reworked.
* the sections about attributes most likely need to be removed as the content is in `variant_aware_plugins.adoc`.

**Comment by jjohannes** [comment]
Structuring/removing blanks are handled as part of #2726.

Follow ups for missing content: #10867, #10868
