### ISSUE TITLE
Support for += in List/SetProperty

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#10475]
### Expected Behavior
`+=` syntax is supporter for List/SetProperty in `build.gradle`

```
pitest {
    fileExtensionsToFilter += ['xml', 'orbit']
}
```
with:
```
final ListProperty<String> fileExtensionsToFilter
```
and some default fileter extentions set by the plugin - extendable in a user configuration.

### Current Behavior
> MissingMethodException: No signature of method: org.gradle.api.internal.provider.DefaultListProperty.plus() is applicable for argument types: (ArrayList) values: ...

### Context
On a migration from `List<String>` to `ListProperty<String>` people have to change their configuration. Adding the `plus()` method could help.

**Comment by lacasseio** [comment]
@adammurdoch I feel this should just be decorated on the `List/SetProperty` given it's specific to the Groovy DSL. At the same time, I feel like it's more magic then necessary. We could add the decoration but issue a deprecation warning so the migration is easier to tell users to use `addAll` or `map`. What do you think?

**Comment by eskatos** [comment]
Note that, if desirable, this could also be added to the Kotlin DSL by leveraging [operator overloading](https://kotlinlang.org/docs/reference/operator-overloading.html).

Here is an example with `ListProperty<T>` for `+=`:

```kotlin
operator fun <T> HasMultipleValues<T>.plusAssign(element: T) =
    add(element)

operator fun <T> HasMultipleValues<T>.plusAssign(provider: Provider<T>) =
    add(provider)

operator fun <T> HasMultipleValues<T>.plusAssign(elements: Iterable<T>) =
    addAll(elements)

operator fun <T : Any> HasMultipleValues<T>.plusAssign(providers: Provider<Iterable<T>>) =
    addAll(providers)

// ...

val list: ListProperty<String> = ....

list += "some"
list += listOf("some")
list += provider { "some" }
list += provider { listOf("some") }
```

**Comment by rkrisztian** [comment]
I as a Groovy fan totally miss this. As you can already set property values with `=`, I would also expect `+=` to work for list-like properties. Currently you can't do:

```
def listProperty = objects.listProperty RegularFile
listProperty += file 'some.file'
```

And having to call `add()` is not idiomatic Groovy for a list-like property.

Note: I would also define `minus()` for the `-=`.

**Comment by rkrisztian** [comment]
Also, I'm wondering what we can do about assigning a list, as we cannot do this either:

```
listProperty = layout.projectDirectory.with { [file('some.file'), file('some.file2')] }
```

```
> No signature of method: java.util.ArrayList.get() is applicable for argument types: () values: []
  Possible solutions: get(int), get(int), set(int, java.lang.Object), set(int, java.lang.Object), grep(), grep()
```

**Comment by lacasseio** [comment]
There is a balance to strike here between usability and expectation here. We understand that those convenience methods are great during migration to the Provider API but also need to be mindful that those magic decorator (such as setting a value to a Property using `=`) can be confusing to beginner users. It definitely have some value as a feature even if it's a stop-gap migration one.

**Comment by mlopatkin** [comment]
The work actually continues in #23637.
