### ISSUE TITLE
You need to have compileSdk set to at least 28 in your module build.gradle to migrate to AndroidX

### ISSUE THREAD

**Issue by sagarsolace** [gradle/gradle#10477]
---
cc: @gradle/build-cache

app/build.gradle  ////////////////

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutter_sworl"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

Gradle.properties //////////////

org.gradle.jvmargs=-Xmx1536M
android.enableJetifier=true
android.useAndroidX=true

i complete all that thing but "You need to have compileSdk set to at least 28 in your module build.gradle to migrate to AndroidX" this error happens

**Comment by blindpirate** [comment]
Doesn't look like a Gradle issue. Why do you think this is an Gradle issue and why do you think it's related to build cache?

Note that Android Gradle Plugin and Gradle are totally different things.

**Comment by ruwanmadushanka** [comment]
go to app>build.gradle file. then do these changes.
Update compileSdkVersion to 28
Update targetSdkVersion to 28

**Comment by trulyhuman** [comment]
> go to app>build.gradle file. then do these changes.
> Update compileSdkVersion to 28
> Update targetSdkVersion to 28

worked for me
