### ISSUE TITLE
Gradle docs sitemap.xml is busted

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#10474]
This is something Google looks for when indexing our docs for users, so it will reduce the likelihood that folks will find new docs content via web search.

### Expected Behavior
https://docs.gradle.org/current/sitemap.xml returns a real sitemap.

### Current Behavior
https://docs.gradle.org/current/sitemap.xml referenced from https://docs.gradle.org/robots.txt is no longer there.

### Context
Individual sitemaps for each release are there. i.e. https://docs.gradle.org/5.6/sitemap.xml

This is generated by https://github.com/gradle/dotcom-docs/blob/33327e922b4951dfca200f658f82a98c325f80c1/build.gradle#L365-L371

**Comment by alexleventer** [comment]
This is probably something we should try to fix in the next week to play it safe.

The sitemap was last read successfully on 8/27.

**Comment by alexleventer** [comment]
![image](https://user-images.githubusercontent.com/3254549/64443420-aee5c680-d086-11e9-885c-1c56f8b4357c.png)

**Comment by big-guy** [comment]
This is fixed

**Comment by alexleventer** [comment]
Thanks @big-guy 👍
