### ISSUE TITLE
Is there a better way to represent optional file properties?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#10498]
Currently, I'm stuck doing this:
```kt
private fun <T : FileSystemLocation> Provider<T>.optional() =
        flatMap { project.objects.fileProperty().apply { set(it.asFile.orNull()) } }
```

However, I lose the task dependency information with that.

> Note to self: this lets me get rid of `dependsOn(resourceDir)`

**Comment by big-guy** [comment]
I can't quite tell how you're intending to use this.  Can't you just put `@Optional` on a `RegularFileProperty` and not set it?  

Our community Slack or the forums might be a better place to ask this question.

**Comment by SUPERCILEX** [comment]
Sorry, yeah, my issue was super unclear. It's basically the same as #2016 but for Providers.

Say I need to configure something based on what's in a folder. If the folder isn't there, I don't do anything. But if it is, I need to do stuff. Since the folder doesn't change and isn't configurable by the user, I want the property to always be set. However, that doesn't work with Gradle's model since it'll freak out if the file isn't there.

So the question is: can you easily get the property and null it out based on some condition?
