### ISSUE TITLE
support preloading of dependencies

### ISSUE THREAD

**Issue by matthiasbalke** [gradle/gradle#1049]
### Expected Behavior

I would like to be able to execute a gradle task to preload all needed dependencies without executing any other task. 

### Current Behavior

no feature known to to that.

### Context

In some situations, like on the CI server I want to preload all dependencies, to cache them for later builds and speed up build time. I would like to be able to execute a gradle task to preload all needed dependencies without executing any other task. This way I can seperate the loading of dependencies from doing real stuff. This would also help to profile execution times, as sometimes the download of dependencies is just slow because of network issues.

**Comment by bmuschko** [comment]
You can easily support this use case by writing a task that iterates over all configurations and resolves their dependencies. Then on CI you can set up another job that runs the task before any other task is running. Another option could be to use Artifact Query API to create a offline repository populated with all the dependencies you need in your build.

> This would also help to profile execution times, as sometimes the download of dependencies is just slow because of network issues.

The Gradle profile report and Gradle Cloud Services already makes the clear distinction between the  time spent on resolving dependencies vs. executing tasks.

**Comment by matthiasbalke** [comment]
Thanks for your quick answer. I didn't know that it is possible, to do this. I'll try to write the task and come back to you in case of problems.

When I said profiling, I didn't ment the gradle profiling. My team is using the Jenkins Pipeline Plugin. For each step of our build we have a custom stage, so we can directly see with step took how much time. But the download of the artifacts is done in the same stage with the "real" task and the artifact server is slow sometimes. Beyond caching these artifacts this is the second reason why I want to seperate the download and execution of the tasks.

**Comment by matthiasbalke** [comment]
I found this solution https://gist.github.com/matthiasbalke/3c9ecccbea1d460ee4c3fbc5843ede4a which seems to work fine! Thanks for pointing me into the right direction!
