### ISSUE TITLE
@LocalState providers not linked across tasks?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#10497]
Is it normal that @LocalState properties don't carry task information with them?

> Note to self: this lets me get rid of `dependsOn(genEditTask)`

**Comment by lptr** [comment]
IIUC, you'd like to consume the `@LocalState` created by a task. What is your use case? Why not make that property an `@OutputFile` (since it _is_ an output of the task)?

**Comment by SUPERCILEX** [comment]
Because it's also the input file. What's the recommended way to represent that?

**Comment by lptr** [comment]
Gradle does not currently have incremental build or caching support for tasks that modify their inputs in place. You could add `upToDateWhen { false }` and not declare any inputs for the task. You can declare the outputs as outputs if you want.

We might later add support for tasks that do in-place modifications on their inputs (like code formatters do), but this is not yet planned.

In 6.0 we are planning to deprecate consuming the `@LocalState` properties in other tasks, see https://github.com/gradle/gradle/issues/10529.

**Comment by SUPERCILEX** [comment]
Thanks for the info! PS: any thoughts on https://github.com/gradle/gradle/issues/10498#issuecomment-529759867?
