### ISSUE TITLE
'setArchiveName' deprecated, but use 'getArchiveFileName()' instead???

### ISSUE THREAD

**Issue by ChaosJohn** [gradle/gradle#10506]
### Expected Behavior
There should to be an API `setArchiveFileName(String name)`. 

### Current Behavior
The doc recommends us to use `getArchiveFileName()` to replace `setArchiveName(String name)`. 
[Code Link](https://github.com/gradle/gradle/blob/4781d15dc88ccfb67d4e2251580cb7e29e776ec3/subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java#L119)

### Context

Gradle 5.6, gradle-kts

### Steps to Reproduce 

```
val bootJar: BootJar by tasks
bootJar.apply {
    archiveName = "${archiveBaseName.get()}-${archiveVersion.get()}.${archiveExtension.get()}"
}
```

### Your Environment
macOS 10.14.6

**Comment by ljacomet** [comment]
`getArchiveFileName()` returns a `Property<String>` which is a mutable object, on which you can invoke `Property.set(value)`
This is all part of the new APIs for lazy binding of values - see https://docs.gradle.org/5.6.1/userguide/lazy_configuration.html#sec:lazy_properties

Note that the Groovy DSL will let you say: `archiveFileName = "value"` but the Kotlin DSL requires `archiveFileName.set(value)` but both allow to skip the `get` part, which remains mandatory in Java.

**Comment by ChaosJohn** [comment]
@ljacomet It works. Thanks!
