### ISSUE TITLE
!question! How do i decompile a dll that was generated by gradle

### ISSUE THREAD

**Issue by Vortetty** [gradle/gradle#10500]
im trying to decompile the dll of a game created with gradle (the game is open source so it would not be illegal) to figure out the difference between 2 versions, how could i unpack it to the source, or is this not possible?

**Comment by big-guy** [comment]
This is a little out of scope for Gradle, please ask these sorts of questions on our forums or Stackoverflow.

It's probably easier to diff the source code at different commits than the binary files (or decompiled binary files) if the project is open source.
