### ISSUE TITLE
Kotlin DSL sourceSets.compileClasspath

### ISSUE THREAD

**Issue by LoganDark** [gradle/gradle#10502]
### Expected Behavior
I want to have a module in my project that has, at compile time, the project's runtime dependencies.

In an older project that uses `build.gradle` (sans kts), it was as simple as this:

```groovy
sourceSets {
    launch {
        compileClasspath += main.compileClasspath + main.runtimeClasspath + main.output
    }
}
```

However, in the Kotlin DSL, I can't figure out how to get this to work. I've tried this:

```kotlin
the<JavaPluginConvention>().sourceSets {
	val api = getByName("api")
	val main = getByName("main")

	"api" {}

	"main" {
		compileClasspath += api.compileClasspath + api.runtimeClasspath + api.output
	}

	"launch" {
		compileClasspath += main.compileClasspath + main.runtimeClasspath + main.output
	}
}
```

but it doesn't work right. `launch`, which used to have the required dependency at compile-time when I had the dependency just listed as `compile` in the dependency block, is now full of errors.

The required dependencies are specified as `runtime` in the `dependencies` block.

### Context
I'm making a Minecraft tweaker (like a mod, but it doesn't require Forge) and using Mixin as a dependency. In the project I'm basing my build setup off of, `launch` (which patches the Minecraft code) is the only module with access to Mixin, the ASM library that allows this to happen. The rest of the code has it as a runtime dependency, but `launch` has it as a compile dependency so that it can use the library. I've been trying to mimic this using the Kotlin DSL, but it's not working... Ever since I decided to use the Kotlin DSL for my project, I've been having so many issues trying to get things to work correctly. It's nice, kind of, but it's really confusing and I can't find any help online because nobody uses it!

In the IntelliJ module view thing, it does show that `api` has a dependency on `main` and `launch` has a dependency on both, but `launch` doesn't have the compile dependency on Mixin that I need.

### Steps to Reproduce 
1. Specify something as a `runtime` dependency in the dependencies block
2. Define a sourceSet and add `main`'s runtime classpath to its own compile classpath
3. Watch how nothing happens

### Your Environment
OS: macOS Mojave 10.14.5
IDE: IntelliJ IDEA Ultimate 2019.2

**Comment by Eng-Fouad** [comment]
Try `sourceSets.main.get().compileClasspath`.
