### ISSUE TITLE
Proxy inheritance error

### ISSUE THREAD

**Issue by iwangjie** [gradle/gradle#10508]
AndroidStudio set up socks5 proxy, the automatically generated gradle configuration file is wrong

### AndroidStudio set up socks5 proxy

Tell us what should happen：
file gradle.properties
![image](https://user-images.githubusercontent.com/23075587/64502353-4d2c9300-d2f8-11e9-8aca-19359cd4ebbf.png)

 Tell us what happens instead of the expected behavior：
file gradle.properties

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=1086
and
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=1086

Cause the agent to fail

I downloaded a new Android Studio and set up Socks5 agent to create a new Android project, but the build failed, no matter what I did, because of a configuration error in gradle.properties.

My complete operation flow
1. download andorid studio
2. Set up socks5 proxy
3. New Android Project
4.Gradle failed to build.

### Your Environment

Build scan URL:

**Comment by blindpirate** [comment]
Can you share the failure? Looking at your description, this doesn't look like a Gradle issue, but an Android Studio issue, right?

**Comment by iwangjie** [comment]
Thank you, I will contact Android Studio.
