### ISSUE TITLE
Unable to use "." (dot) in @Option name

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#10518]
### Expected Behavior
I would like to name `@Option` with `.` in its name, to emphasis its relation to the plugin, e.g. `pitest.timestampedReports`.

### Current Behavior
```
class PitestTask extends JavaExec {
    @Input
    @Optional
    @Option(option = "pitest.timestampedReports", description = "Configures usage of timestamped reports in PIT")
    final Property<Boolean> timestampedReports
```
works with `-q help --task pitest`, but fails in the actual task execution:
```
gw pitest --pitest.timestampedReports
```
returns:
```
Caused by: org.gradle.internal.exceptions.LocationAwareException: Cannot add option 'pitest.timestampedReports' as an option can only contain alphanumeric characters or '-' or '_'.
Caused by: java.lang.IllegalArgumentException: Cannot add option 'pitest.timestampedReports' as an option can only contain alphanumeric characters or '-' or '_'.
```

### Context
It's natural to use `.` there.

### Steps to Reproduce 
Try to execute task with `@Option` named with `.` inside.

### Your Environment
Gradle 5.6.1

**Comment by big-guy** [comment]
This is a bug in our validation.  We should fail consistently when you're using `.`.  I don't think we want to support dots in an option name because you already need to put the option immediately following the task name and we may want to use the dot-notation for other things (e.g., allowing the option to appear anywhere in the command-line list).

**Comment by szpak** [comment]
I missed that I need to put the switch right after the task name. `--pitest.features=...` implemented on the Gradle side to be put anywhere in the command line is even better for me. Reported #10553 for a reference.
