### ISSUE TITLE
CodeNarc task does not fail if there were compilation errors

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#10516]
As decribed at CodeNarc/CodeNarc#439, there are compilation errors during CodeNarc execution, but the task does not fail.
Actually in that case it is wrong that the compilation actually fails, but I think if there are compilation errors, it is wrong that the task actually finishes successful instead of failing.

**Comment by erdi** [comment]
I'd argue that this is not the right place to report it - in my opinion the failure should occur in CodeNarc's Ant task which is maintained by the CodeNarc project and which Gradle delegates to. As far as I can tell, CodeNarc only logs compilation errors and does not fail the analysis when they occur. If the Ant task fails in that case then the error should simply bubble up to Gradle and fail the task.

**Comment by Vampire** [comment]
I see, I'll report another error for CodeNarc then
