### ISSUE TITLE
CodeNarc should use the Groovy version that the code actually is using

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#10521]
I have a problem where I have Groovy code that compiles properly, as it uses Groovy 2.5.4 (repeatable annotations used which only work since 2.5).
Calling CodeNarc it uses the default Groovy version of CodeNarc which is 2.3.11 where the compilation fails.
The details can be seen at https://github.com/CodeNarc/CodeNarc/issues/439.

The CodeNarc plugin should probably configure CodeNarc properly so that the Groovy version that the code actually is compiled with is also used for CodeNarc.

**Comment by erdi** [comment]
As far as I'm aware there is no concept of the version of Groovy that the code is actually compiled with (Groovy is just a jar that you add as a dependency to one of the configurations that end up on the compilation classpath) hence there is no way for Gradle to configure that. This is what the `codenarc` configuration added by the plugin is for - if you would like CodeNarc to use a different Groovy version for compilation during analysis of your code than the one used for compiling CodeNarc itself you should just add it to that configuration. You can even add a concept of `groovy` configuration to your build and then use it for both `codenarc` and `implementation` configurations:
```
configurations {
    groovy

    codenarc.extendsFrom groovy
    implementation.extenfsFrom groovy
}

dependencies {
    groovy 'org.codehaus.groovy:groovy-all:2.5.4'
}
```
