### ISSUE TITLE
Gradle metadata cannot be turned off in a first-class way

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#10523]
Hey Gradle friends, I'm a bit worried that Gradle 6 is pushing Gradle Metadata as the default format without a first-class way to disable it.
The worry here is that once a repo starts publishing metadata, all recent (Gradle 5) consumers automatically pick it up, so AFAIK it's next to impossible to do a controlled rollout.

### Expected Behavior

I should be able to turn off publishing gradle metadata / keep publishing just POMs, in a way that is guaranteed to be stable as part of the API.

### Current Behavior

Recent gradle nightlies (as of Sep 3) automatically turn on publishing of gradle metadata, with seemingly no way to turn it off.

Luckily I found this comment which allows us to turn it back off https://github.com/gradle/gradle/blob/fe6a13809696f4da35dd03973a4534950ca3c334/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java#L594-L595 but it mentions being temporary and it's not discoverable.

### Context

As for a particular example of why this worries us, we've attempted to migrate some of our internal projects to preempt any issues, but found a problem where published excludes seem to not be respected (by a consumer on both 5.6.1 / nightly Gradle) whereas they were before when the publishing project was publishing just POMs.

We'd like to have time to address these issues, while also being able to stay up to date with the latest Gradle.
Right now, the worry is that we'll have to pin Gradle to a particular version, if at some point the ability to stop publishing Metadata is taken away.

cc @iamdanfox @ferozco

**Comment by ljacomet** [comment]
As can be seen in the [nightly documentation](https://docs.gradle.org/nightly/userguide/publishing.html#disabling-gmm-publication), the _official_ way to disable publication of Gradle Module Metadata is by disabling the task that produces it.

But more importantly, if you find issues with it, like that `exclude` problem, do not hesitate to file an issue!

**Comment by dansanduleac** [comment]
Fair point, didn't notice that!
I will definitely file an issue, but as always repro is a bit slow since it happened on an internal project..
