### ISSUE TITLE
getOrElseGet() with provider as parameter for Property/Provider

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#10520]
### Expected Behavior
There are cases where it is handy to return another provider if the current one is empty.

```
class PitestPluginExtension {
    final SetProperty<String> targetClasses
    final SetProperty<String> targetTests
```
```
//get targetClasses or if not use targetClasses 
= extension.targetTests.getOrElseGet(extension.targetClasses) //method name should be enhanced
```

### Current Behavior
Without that it is needed to use `ifPresent()`:
```
= project.providers.provider {
    if (extension.targetTests.isPresent()) {
        return extension.targetTests.get()
    } else {
        return task.targetClasses.getOrNull()
    }
```
Similar approach is used in `java.util.Optional`

**Comment by big-guy** [comment]
Do you have a little more detail on where/how `= extension.targetTests.getOrElseGet(extension.targetClasses)` is used?

**Comment by szpak** [comment]
Sure. I the `targetTests` parameter is not set by an user in the plugin configuration the value from `targetClasses` is taken - `targetClasses` is always set by the plugin logic and is a sensible default value. However, an uses might want to narrow the scope of PIT execution to subset of tests. [Sample usage](https://github.com/szpak/gradle-pitest-plugin/blob/32a8c68973702e1f16dec35ab634635735a374f0/src/main/groovy/info/solidsoft/gradle/pitest/PitestPlugin.groovy#L104-L121) in code and the original [issue](https://github.com/szpak/gradle-pitest-plugin/issues/143) which brought me here.

**Comment by big-guy** [comment]
OK, in that case, could you just do:

```
extension.targetTests.convention(extension.targetClasses)
```

If targetTests is set explicitly, then that value is used.
If targetTests is not set, by convention, you use targetClasses.

**Comment by adammurdoch** [comment]
Have you looked at `Provider.orElse(Provider)`, added in Gradle 5.6? It does what you're asking for in the description.

**Comment by szpak** [comment]
> OK, in that case, could you just do:
> 
> ```
> extension.targetTests.convention(extension.targetClasses)
> ```
@big-guy I tried it before and with:
```
task.targetTests.convention(extension.targetClasses)
task.targetTests.set(extension.targetTests)
```
The second line overrides a default value even if `extension.targetTests` is a non-set provider. It's `SetProperty<String>` to maybe a default empty collection causes that? Is it an intended behavior?

---

> Have you looked at `Provider.orElse(Provider)`, added in Gradle 5.6? It does what you're asking for in the description.

@adammurdoch Yes, that's exactly what I needed, thanks. I've been looking for that, but maybe my IDE has an earlier Gradle version set, so I missed it.

**Comment by szpak** [comment]
> Yes, that's exactly what I needed, thanks. I've been looking for that, but maybe my IDE has an earlier Gradle version set, so I missed it.

Ok, I missed it as it is named `orElse()` not `getOrElse()` (which has just plain argument accepted).
