### ISSUE TITLE
Fix resolved version publication for strictly

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#10533]
When publishing a resolved version, it always becomes a `require`.
However, when the original declaration uses `strictly`, it makes sense to preserve that level in the published version.

**Comment by jjohannes** [comment]
I think this is related so I drop it here. But we can open a separate issue if it is not addressed with the solution here.

```
dependencies {
    conf('org:foo:1.0')
    conf('org:foo') {
       version { strictly '1.0' }
    }
}
```

This first defines require and then strictly. This is somewhere reduced to only require. And thus the strictly is not in the graph anymore.

If we change the order, it works.

```
conf('org:foo') {
   version { strictly '1.0' }
}
conf('org:foo:1.0')
```

Complete (failing) test case:
```
given:
repository {
    'org:foo:1.0'()
}

buildFile << """
    dependencies {
        conf('org:foo:1.0')
        conf('org:foo') {
           version { strictly '1.0' }
        }
    }
"""

when:
repositoryInteractions {
    'org:foo:1.0' {
        expectGetMetadata()
        expectGetArtifact()
    }
}
run ':checkDeps'

then:
resolve.expectGraph {
    root(":", ":test:") {
        edge("org:foo:{strictly 1.0}", "org:foo:1.0")
    }
}
```

It's also interesting that in both cases this is reduce to one edge. While there should probably be two (?)
