### ISSUE TITLE
Rebuild the task if cache is not validate

### ISSUE THREAD

**Issue by IronLung7** [gradle/gradle#10538]
Gradle should rebuild the task if cache is not validate
---
Our gradle task output maybe validated. Becase we saved file link in the txt file as an output. But that link maybe removed occasionally. So if the build is from cache, we want to validate the cache, if output is invalid, we want gradle to rerun that task.
Is there any planning for such requirement? 
cc: @gradle/build-cache

**Comment by lptr** [comment]
Looks like the task in question should not be cached in the first place: if rerunning the task should produce a (semantically) different output, then the task is not sufficiently reproducible to be stored and shared using the cache.
