### ISSUE TITLE
Upgrade to latest Groovy version bundled with Gradle

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1054]
Update the Groovy version (as soon as it is released) with the next major version of Gradle to incorporate bug fixes.

Reasons:

- https://discuss.gradle.org/t/groovy-memory-leaks/20916

**Comment by moley** [comment]
Cool, thank you

**Comment by eriwen** [comment]
Gradle 3.5 includes Groovy 2.4.10. Going to close this as delivered for now.
