### ISSUE TITLE
Consider showing release checksums without downloading the files

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10551]
### Expected Behavior

Release download page should provide SHA checksums for both distributions.
That would simplify updating of `gradle/wrapper/gradle-wrapper.properties`

### Current Behavior

The update of Gradle version requires to download relevant sha256 file, open it and copy-paste the checksum.

### Context

I do not download Gradle distributions manually. I update versions in `gradle-wrapper.properties`.
However providing distributionSha256Sum is not trivial.

It would be nice if https://gradle.org/releases/ contained `gradle-wrapper.properties` copy-paste ready checksums.

**Comment by vlsi** [comment]
Oh, I believe that is still relevant.

**Comment by JLLeitschuh** [comment]
We have a version of this here. But linking to this would be useful.

https://gradle.org/release-checksums/#6.7.1

**Comment by donat** [comment]
We've added links to checksums on the releases page.
