### ISSUE TITLE
Stable source dependencies

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#10559]
This is an epic to collect all of the issues we think are required to consider source dependencies stable and finished enough to encourage people to use them in production.

**Comment by lacasseio** [comment]
See https://github.com/gradle/gradle-native-private/issues/83

**Comment by jjohannes** [comment]
There is no work planned on this right now.

**Comment by tasomaniac** [comment]
Would it make sense to deprecate it and remove with the next major version?

The whole feature is half-baked and is not really useful.

**Comment by edgarkhimich** [comment]
Is there any updates planning regarding to this feature ?

**Comment by jjohannes** [comment]
I would assume there are no plans currently. But using included builds (some docs here https://docs.gradle.org/current/userguide/structuring_software_products.html) in combination with this plugin (https://github.com/melix/includegit-gradle-plugin), which is under active development, could be a suitable alternative.
