### ISSUE TITLE
Design Public API for BuildOperations

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1057]
Expected Output: design doc

**Comment by adammurdoch** [comment]
This is covered by https://github.com/gradle/performance/issues/143

**Comment by eriwen** [comment]
@oehme is this still planned for 4.0?

**Comment by oehme** [comment]
The worker api is in 4.0 and allows you to provide a display name for the work you are doing. We don't plan any more sophisticated API for build operations at this point.

**Comment by eriwen** [comment]
Closing as superseded
