### ISSUE TITLE
Support declaring dependency constraint to specific commit id used in source dependencies

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#10586]
### Expected Behavior

The following should be allowed:
```
dependencies {
    implementation('org.gradle.cpp-samples:utilities') {
        version {
            commitId = 'sha-1-commit-id'
        }
    }
}
```
We could also use the version field and if we can't find the version in the list of tag, we try to find that specific string as a commit id, then fail.

### Current Behavior

Users can't add a source dependency to a specific commit id.

### Your Environment

 * Build scan URL:

**Comment by martinda** [comment]
How about using a ref, it would be more universal:

```
dependencies {
    implementation('org.gradle.cpp-samples:utilities') {
        version {
            ref = 'branch, tag, sha1'
        }
    }
}
```
Or support all three with different assignment (`branch='...'`, `tag='...'`, `sha1='...'`).
