### ISSUE TITLE
Source dependencies from local (file:...) git repo not allowed in --offline mode

### ISSUE THREAD

**Issue by tculp** [gradle/gradle#10588]
Git repositories can be defined as a url or a path.

As a URL:
```
sourceControl {
    gitRepository("https://github.com/${repoGroup}/${repoName}.git") {
        producesModule("${module}")
    }
}
```
As a path:
```
sourceControl {
    gitRepository("../${repoPath}") {
        producesModule("${module}")
    }
}
```
### Expected Behavior
When the --offline parameter is given, I expect URL-based repos to fail, but path-based repos to succeed, since they do not require online functionality.

### Current Behavior
When using a path-based repo, I still receive the following:

> Could not resolve all artifacts for configuration ':classpath'.
   > Cannot resolve ${module}:1.0 (branch: dev) from Git repository at file:/Users/${repoPath}/ in offline mode.

### Context
Some git repositories are not published online, but should still be usable as a source dependency. More commonly, a machine may not be connected to the internet, but may still have all of the required repositories cloned locally. This is my situation.

### Steps to Reproduce (for bugs)
Attempt to assemble a project with a local, path-based sourceDependency with the --offline flag

**Comment by TLATER** [comment]
See the linked issue. I'd very much like to be able to do gradle offline build for nix packaging purposes.

Any chance this could be reopened?
