### ISSUE TITLE
Gradle 3.x throws java.lang.ClassNotFoundException when trying to use plugins

### ISSUE THREAD

**Issue by cdancy** [gradle/gradle#1059]
Migrating to Gradle 3.x throws java.lang.ClassNotFoundException, seemingly at random, when trying to use applied plugins. 

### Expected Behavior
When upgrading gradle script from 2.14.1 to 3.x I expect all plugins to load and work as expected. I expect all classes that belong to those plugins to be loaded and available as well.

### Current Behavior
Gradle, again seemingly at random, fails to find classes that a given plugin loads.

### Context
Our build pipeline is failing randomly, at different points, with seemingly no consistency between pops. The below snippet fails (at random) though a host of other plugins fail for us as well. The one take away we've found at this point is that the plugins that are failing are loading their dependencies at runtime vs the standard _dependency definition_ in a pom file. But why it works sometimes and others it doesn't I've no idea.

### Steps to Reproduce (for bugs)
Run the below snippet, assuming you have docker (any version) installed locally, with gradle 3.x. Just remember we can't get this to pop consistently as the issue appears to be seemingly at random.

```
buildscript() {
    repositories {
        jcenter()
    }
    dependencies {
	classpath 'com.bmuschko:gradle-docker-plugin:3.0.4'
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'

docker {
    url = "unix:///var/run/docker.sock"
}

task dockerVersion(type: com.bmuschko.gradle.docker.tasks.DockerVersion) {}
```

Furthermore, when applying the `nebula.dependency-lock` plugin , we [get this exception](https://gist.github.com/cdancy/4cc91935f2aeab4a87b8d8863a32fd98).

### Your Environment
OS: coreos 899.15.0 
Build-node-container running on coreos: Ubuntu 16.04
JDK: oracle jdk7 latest
Gradle: 3.2.1

### Other Notes
[Benjamin Muschko](https://github.com/bmuschko) may have some insight here as he is a maintainer (and original creator) on the `gradle-docker-plugin` along with myself. Anyone have any thoughts one way or the other?

**Comment by huxi** [comment]
Can you try this with [Gradle 3.3-rc-1](https://gradle.org/release-candidate/)?

I had a very similar issue and it was fixed for me by the #933 fix.

**Comment by cdancy** [comment]
@huxi I saw that as well but we're not invoking the `GradleBuild` task anywhere in our pipeline. Are you thinking this might still be related maybe behind the scenes in some way?

**Comment by huxi** [comment]
Give it a shot. I didn't do anything with `GradleBuild`either but had similar `ClassNotFoundExceptions` that were entirely random. None of them since 3.3-rc-1 and we had quite a few builds on our CI server in the meantime.

**Comment by big-guy** [comment]
`GradleBuild` made it more obvious, but there was an underlying thread safety issue that affected other caches without having to use `GradleBuild`.

Do you see any messages like the following in your logs?

> cache <something>.bin (</path/to/something>.bin) is corrupt. Discarding.

**Comment by huxi** [comment]
@big-guy I was celebrating when I saw that you had a reproducible failure for this issue. This problem was haunting me way longer than just Gradle 3.2 and forced us to always do clean builds with wiped caches on our build server for over a year.
Can you imagine how great it feels to be back in "result in a few minutes" terrain? I was literally dancing.

**Comment by lacasseio** [comment]
@cdancy could you provide a stack trace? I suspect this failure is related to https://github.com/gradle/gradle/issues/784. This issue is been addressed more broadly with https://github.com/gradle/gradle/issues/919. We are working on a fix for the next version of Gradle (after 3.3).

**Comment by cdancy** [comment]
@lacasseio [stacktrace here](https://gist.github.com/cdancy/707936b4950a087b49de866bbe49d96a). Attempting to wire-up gradle 3.3-rc1 for testing to see if that solves problems.

**Comment by cdancy** [comment]
@lacasseio @big-guy @huxi tried with gradle-3.3-rc1 and the `nebula/plugin/scm/ScmPlugin` plugin is still popping. [Stack trace here](https://gist.github.com/cdancy/1ec80b4ce0fbfbcb8e51748489422c9d).

**Comment by TimvdLippe** [comment]
I am seeing similar issues with the Gradle 3 => 4 upgrade. For me the `scan` plugin was generating these errors. Even when manually downloading the new plugin from the website, this error was thrown.

**Comment by cdancy** [comment]
No longer seeing this issue. Closing for now.
