### ISSUE TITLE
Warn about unsafe access to the project state

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#10605]
Similar to what we have for unsafe dependency resolution.
So that we can (eventually) stop hard to troubleshoot errors to happen in the future.

One example thing that this would help prevent is `ConcurrentModificationException`s when running parallel builds, like in https://youtrack.jetbrains.com/issue/KT-32853

### Expected Behavior
Build users of build logic that access the project state in an unsafe manner should be warned.

### Current Behavior
Hard to troubleshoot errors happen.

### Context
https://youtrack.jetbrains.com/issue/KT-32853
https://gradle.slack.com/archives/C09LZKUCB/p1567686087017400

**Comment by adammurdoch** [comment]
The project state has a very large surface area. So, I would think about splitting this up into some smaller steps, as each warning adds value. For example:

- Warn about using a container from a thread that does not own the project lock. The container implementations are already instrumented with other checks.
- Warn about creating or using a configuration from a thread that does not own the project lock. Currently we warn about resolution, but not other queries or mutations.
- Warn about using a decorated object
- Warn about using the project object
- Etc.

Alternatively, we might instead rely on instant execution to prevent these things, as it already prevents most access to the project state. We would still need to prevent access to the project object at task execution time, plus a few other places where project state can leak, such as `Task.getTaskDependencies()`.
