### ISSUE TITLE
Warn when expanding zipTrees at configuration time

### ISSUE THREAD

**Issue by MarkRx** [gradle/gradle#1062]
I am hitting a strange bug with gradle 2.12. My task is being considered up to date when it has input files and I explicitly disabled the up-to-date checking. Given the setup below, running

> gradle doCopy

works as expected. Running

> gradle clean doCopy

does not and results in my task being skipped.

### Expected Behavior
My task runs

### Current Behavior
My task does not run. Gradle thinks it is up to date and skips it. It appears that https://github.com/gradle/gradle/blob/REL_2.12/subprojects/core/src/main/groovy/org/gradle/api/internal/tasks/execution/SkipEmptySourceFilesTaskExecuter.java thinks the source files are empty when they are not.

### Context
My task is not being run and is appearing in the console as being up-to-date.

### Steps to Reproduce (for bugs)
build.gradle:

```
apply plugin: 'java'

configurations {
	cfg
}

dependencies {
	cfg files("$projectDir/replaceme.zip")
}

task doCopy(type: Copy) {

	outputs.upToDateWhen { false }
	def templates = zipTree(configurations.cfg.singleFile).matching({ "folder/*" }).files;
	println "TEMPLATES: " + templates;
	
	from(templates) {
		include '**/replaceme.json'
		expand([bar: "BBB"])
			
	}
	
	into "$buildDir"
}
```
replaceme.zip/folder/replaceme.json:
```
{
	"foo": ${bar}
}
```

### Your Environment
Gradle 2.12 Windows 7 x64

### Output

> gradle doCopy --info
> Starting Build
> Settings evaluated using settings file 'C:\master\settings.gradle'.
> Projects loaded. Root project using build file 'C:\git\gradle\gradle_bug2\build.gradle'.
> Included projects: [root project 'gradle_bug2']
> Evaluating root project 'gradle_bug2' using build file 'C:\git\gradle\gradle_bug2\build.gradle'.
> TEMPLATES: [C:\git\gradle\gradle_bug2\build\tmp\expandedArchives\replaceme.zip_24fq9z7f0usxdwntyo7ey8sd7\folder\replaceme.json]
> All projects evaluated.
> Selected primary task 'doCopy' from project :
> Tasks to be executed: [task ':doCopy']
> :doCopy (Thread[main,5,main]) started.
> :doCopy
> Executing task ':doCopy' (up-to-date check took 0.032 secs) due to:
>   Task.upToDateWhen is false.
> :doCopy (Thread[main,5,main]) completed. Took 0.28 secs.

> gradle clean doCopy --info
> Starting Build
> Settings evaluated using settings file 'C:\master\settings.gradle'.
> Projects loaded. Root project using build file 'C:\git\gradle\gradle_bug2\build.gradle'.
> Included projects: [root project 'gradle_bug2']
> Evaluating root project 'gradle_bug2' using build file 'C:\git\gradle\gradle_bug2\build.gradle'.
> TEMPLATES: [C:\git\gradle\gradle_bug2\build\tmp\expandedArchives\replaceme.zip_24fq9z7f0usxdwntyo7ey8sd7\folder\replaceme.json]
> All projects evaluated.
> Selected primary task 'clean' from project :
> Selected primary task 'doCopy' from project :
> Tasks to be executed: [task ':clean', task ':doCopy']
> :clean (Thread[main,5,main]) started.
> :clean
> Executing task ':clean' (up-to-date check took 0.0 secs) due to:
>   Task has not declared any outputs.
> :clean (Thread[main,5,main]) completed. Took 0.019 secs.
> :doCopy (Thread[main,5,main]) started.
> :doCopy
> Skipping task ':doCopy' as it has no source files.
> :doCopy UP-TO-DATE
> :doCopy (Thread[main,5,main]) completed. Took 0.021 secs.

This could be related to https://discuss.gradle.org/t/zip-task-ignores-output-when-checking-if-up-to-date/12003 and GRADLE-2579

**Comment by MarkRx** [comment]
Note the problem persists with gradle 3.2.1

**Comment by MarkRx** [comment]
I think I understand what is going on. The zipTree method is running in the configuration phase and is placing the unzipped files into build/tmp. The java clean task run during execution proceeds to delete the build directory. When the doCopy task goes to run the files are no longer there.

What would be a good way to work around this?

**Comment by MarkRx** [comment]
As a workaround I can place the zipTree method in a closure. This causes it to delay being executed until the copy task runs. I think it would be worth investigating if this situation could be remedied in a more intuitive way. I feel that it could easily cause frustration for people that are newer to gradle.

```
task doCopy(type: Copy) {

	outputs.upToDateWhen { false }
	def templates = { zipTree(configurations.cfg.singleFile).matching({ "folder/*" }).files; }
	println "TEMPLATES: " + templates;
	
	from(templates) {
		include '**/replaceme.json'
		expand([bar: "BBB"])
			
	}
	
	into "$buildDir"
}
```

**Comment by oehme** [comment]
Calling getFiles unzips the tree, that is expected. getFiles forces any file collection to be realized. The correct way to handle this is to just not call getFiles and instead pass the zipTree itself around.

**Comment by MarkRx** [comment]
But I want to flatten the zipTree and from what I found the way to do that is to use getFiles()

**Comment by oehme** [comment]
In that case using a closure is the way to go. In your case even more so because otherwise you are resolving dependencies at configuration time.

**Comment by oehme** [comment]
Given how often this comes up I wonder what we can do here. Some ideas are:

- warn when expensive operations like unpacking and dependency resolution are done at configuration time
- offer new methods that allow you to do this lazily, e.g. ´archives.transform { zipTree(it) }`. But these might be just as hard to find as finding out you should use a closure. Also there are so many ways a user might want to transform a file collection, it's hard to make all of them lazy, intuitive and efficient.
- a topical guide on this kind of problem

Or any combination of the above. I'll leave this open as a reminder, @eriwen feel free to close or split this if it is not actionable enough.

**Comment by amake** [comment]
> warn when expensive operations like unpacking and dependency resolution are done at configuration time

I had a declaration-ordering problem that was caused by me accidentally forcing dependency resolution at config time. It took me quite a while to figure out why. I would definitely have appreciated some sort of warning.
