### ISSUE TITLE
Introduce `mapInPlace` for Property types

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#10620]
As raised in https://github.com/gradle/gradle-native/issues/884, we currently hide the translation of a native task's properties into the underlying tool chain's arguments.  

To move this translation out of the internals, the task/plugin would need to add a Provider to `compilerArgs` and the spec to compiler arguments transformer would be removed from the lower level infrastructure (NativeCompiler and down). Translation of link paths/include paths can be kept separate for now.  This would make the true compiler arguments an input to the compile task vs individual properties in the task.

Pseudo:
```
def compilerArgs = project.objects.listProperty(String).empty()

compilerArgs.addAll toolChain.map {
    // tool chain specific arguments
}
compilerArgs.addAll platform.map {
    // add specific platform arguments
}
compilerArgs.addAll provider {
    // other arguments that are always present
}
// etc
```

This works fine for replacing the low-level translation infrastructure, but it doesn't make it user defined. To allow a user to have control over the translation, we could introduce a new `mapInPlace` for `compilerArgs`, pseudo:
```
compilerArgs.mapInPlace { existing ->
    // modify existing however you want
    return newArgs
}
```

Proposed signature for `ListProperty`:
```
void mapInPlace(Transformer<List<T>, List<T>> transformer);
```

Each call to `mapInPlace` adds a transformer to be called in order after resolving the value of the provider but before returning from `get()`.  If `get()` is never called, the transformers are never called. If the value of the provider is finalized, we can also choose to never call the transformers again.

Exceptions from the transformer would propagate out. 

The transformer would not be called if the value is `null`. The transformer would not be allowed to return `null`.

Calling `set` would clear the list of "in-place" transformers.

Alternatively to using `Transformer`, we could also provide a mutable value to an `Action`. I think `Transformer` is a better fit for non-List values.

Alternative names:
`finalize` - this better reflects when this transform runs
`modify` - used in Haskell
`adapt` - we're adapting the value into something else before anyone sees it
`tweak` - we're tweaking the value as above.
`replace` - we're replacing the value with something else.

I think `mapInPlace` is a bit ugly looking but is easy to find along with `map` and `flatMap`. `mapInPlace` is used by Swift and some Scala libraries, so it's not an unusual name. I would stay with `mapInPlace`, but I like the feeling of `finalize`.

Since this probably makes more sense with Collection-like things, we could consider doing this only for `ListProperty` and `SetProperty` until we have a good use case for why this would be a generic feature of `Property`.

Examples:
```
ListProperty<Integer> args = project.objects.listProperty(Integer).empty()
args.addAll(1, 2, 3)
assert args.get() == [ 1, 2, 3 ]
args.mapInPlace { existing ->
    existing.collect { it*2 }
}
assert args.get() == [ 2, 4, 6 ]

// clears on set
args.set([1, 2, 3])
assert args.get() == [ 1, 2, 3 ]

// applied in order
args.mapInPlace { existing ->
    existing.collect { it*2 }
}
args.mapInPlace { existing ->
    existing.collect { it-1 }
}
assert args.get() == [ 1, 3, 5 ]

// propagates through map
def mapped = args.map { provided ->
    provided.collect { (it+1)/2 }
}
assert mapped.get() == [ 1, 2, 3 ]

args.set([1, 2, 3])
assert mapped.get() == [ 1, 1.5, 2 ]

args.mapInPlace { existing ->
    existing.collect { it*2 }
}
assert mapped.get() == [ 1.5, 2.5, 3.5 ]

// fails always
args.mapInPlace { existing ->
    null
}

args.finalizeValue()
assert args.get() == [ 2, 4, 6 ]

// fails after finalizeValue
args.mapInPlace { existing ->
    existing.collect { it*2 }
}
```

WDYT @adammurdoch ?

**Comment by mlopatkin** [comment]
Superseded by #27227
