### ISSUE TITLE
CollectionProperty validation hides the underlying property name for a task

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#10622]
https://github.com/gradle/gradle/blob/e998de55cd247c1dc3ce706ec7d7f551b7aad8ce/subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/AbstractNestedRuntimeBeanNode.java#L163

When we try to get the value from a `CollectionProperty`, we perform validation, but without any context (name of the property or task).  This makes configuration to fail with a cryptic failure when a list of Strings has an Integer in it (as an example):

> Caused by: java.lang.IllegalArgumentException: Cannot get the value of a property of type java.util.List with element type java.lang.String as the source value contains an element of type java.lang.Integer.

There's not an easy way to figure out which property has this problem. I think this could effect other nested properties that throw runtime exceptions when getting a property's value.  The context is available, so we should be able to add it.

**Comment by wolfs** [comment]
@big-guy is this still an issue?

**Comment by big-guy** [comment]
```
interface MyExt {
    @Input abstract ListProperty<String> getStrings()
}

abstract class MyTask extends DefaultTask {
    @Nested
    abstract MyExt getMyExt()

    @TaskAction
    void doIt() {
        System.out.println(myExt.strings)
    }
}

task myTask(type: MyTask) {
    myExt.strings.add("1")
    myExt.strings.add(1)
}
```

This produces a nice message now:
```
Execution failed for task ':myTask'.
> Failed to calculate the value of task ':myTask' property 'myExt.strings'.
   > Cannot get the value of a property of type java.util.List with element type java.lang.String as the source value contains an element of type java.lang.Integer.
```

**Comment by eskatos** [comment]
@big-guy this got closed as completed without milestone so the issue is going back to our triage queue. Could you take care of finding out when it was fixed and assign a milestone?

Also the `team-triage` label should be removed.
