### ISSUE TITLE
The bat script produced by the application plugin fails if you have too many dependencies

### ISSUE THREAD

**Issue by larsgrefer** [gradle/gradle#1064]
If you have many dependencies in a project, the `bat` script generated by the `application`plugin does not work.

### Expected Behavior
The `bat` script produced by the example project linked below should print "Hello World" to the console and exit after 10 seconds.

### Current Behavior
The `bat` script produced by the example project linked below exits immediately without starting the java application.

### Steps to Reproduce (for bugs)
Example project: https://github.com/larsgrefer/gradle-windows-bug-demo

1. invoke the `installDist` task
2. try to execute the `build\install\windows-bug-demo\bin\windows-bug-demo.bat` file (either in a Command Line Promt or with a double-click)

### Your Environment
Tested on Windows 10 x64 (Version 1607) with Gradle `3.1` and `3.2.1`

**Comment by bmuschko** [comment]
Could you please provide the stack trace you are seeing when running the task with `-s`?

**Comment by larsgrefer** [comment]
@bmuschko There is no stack trace.

This is the full console log of the example project:
```
D:\git\gradle-windows-bug-demo>gradlew.bat clean installDist
:clean UP-TO-DATE
:compileJava
warning: Supported source version 'RELEASE_6' from annotation processor 'org.glassfish.corba.annotation.processing.ExceptionWrapperProcessor' less than -source '1.8'
warning: Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.persistence.internal.jpa.modelgen.CanonicalModelProcessor' less than -source '1.8'
2 warnings
:processResources UP-TO-DATE
:classes
:jar
:startScripts
:installDist

BUILD SUCCESSFUL

Total time: 43.075 secs
D:\git\gradle-windows-bug-demo>cd build\install\windows-bug-demo\bin

D:\git\gradle-windows-bug-demo\build\install\windows-bug-demo\bin>windows-bug-demo.bat
Die eingegebene Zeile ist zu lang.
Syntaxfehler.
```

**Comment by bmuschko** [comment]
There was already a discussion about this topic [here](https://github.com/gradle/gradle/pull/286). Would you be interested in following up with the discussion as a pull request? There're some ideas in the post that would be useful to have e.g. de-duping of dependencies, failing the build if Windows line-length exceeds 7k. Can you think of any other optimizations that could be made to satisfy Windows limitations?

**Comment by larsgrefer** [comment]
My first idea was to set the classpath to `lib/*` instead of listing every single jar.

Since classpath ordering seems to be important for some users I'd propose this:

List the application-jar and all direct dependencies (`runtime.resolvedConfiguration.firstLevelModuleDependencies`) by name and add all the transitive dependencies via `lib/*`

**Comment by bmuschko** [comment]
I think this use case could be solved elegantly by providing your own start script template as described in the [Javadocs for CreateStartScripts](https://docs.gradle.org/current/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html]. Based on your use case you can refer to dependencies via `lib/*` or implement some special handling in your custom `ScriptGenerator`.

**Comment by softniels-luiz-alcides** [comment]
Hello @bmuschko! I'm curious to know about the solution you've encountered to this problem. As I'm manually editing the .bat file to test changes on our dev server.
