### ISSUE TITLE
Maven plugin authorize requests for metadata

### ISSUE THREAD

**Issue by jameskleeh** [gradle/gradle#10652]
I have a build that is publishing snapshots to OSS Sonatype. Unfortunately I often am encountering a `Received status code 429 from server: Too Many Requests` error from the server. Sonatype apparently has an increased limit for requests that are authorized. I would like the ability to supply an authorization header to the requests for `maven-metadata.xml`.

I'm not sure if this is a question or a feature request since I don't know if its possible to do this today. If so please point me to the documentation and we can close this.

Thanks!

Example build failure https://travis-ci.org/micronaut-projects/micronaut-core/builds/583715508#L2996

**Comment by melix** [comment]
Possibly related to https://blog.sonatype.com/search-guard-central-repository

**Comment by jameskleeh** [comment]
@melix I don't see how that is relevant. Can you describe why you think it might?

**Comment by melix** [comment]
I'm just restating what Brian Fox from Sonatype told me. I don't see the relationship either, but maybe they made changes to their infra specifically for this.

**Comment by brianf** [comment]
We return a different error code for the affected components, so I was guessing it could be related given proximal timing.

**Comment by brianf** [comment]
Too many requests is a different issue. Possibly just the travis systems are triggering abuse defenses.
