### ISSUE TITLE
Upgrade static code analysis tools to latest library version

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1067]
Static code analysis tools shipped with Gradle core should update their libraries to latest version to stay current.

- FindBugs
- Checkstyle
- PMD
- CodeNarc

Similar to upgrade we did with Gradle 3.0:

https://docs.gradle.org/3.0/release-notes#plugin-library-upgrades

**Comment by eriwen** [comment]
Checkstyle has been updated by @big-guy. There is a PR for PMD I think.

**Comment by bmuschko** [comment]
I think we'll simply do this on a "as needed" basis.
