### ISSUE TITLE
ScalaCompile task does not respect all JavaForkOptions configuration

### ISSUE THREAD

**Issue by mark-vieira** [gradle/gradle#10685]
### Current Behavior
Configuring fork options on `ScalaCompile` tasks such as `executable` should affect the subsequently launched Scala compile daemon. For example given a script with configuration like below:

```
compileScala.options.forkOptions.executable = 'path/to/some/jdk/bin/java'
```

We would expect Scala compile daemon to be forked using the configured Java executable but that is not the case, this configuration get dropped. When we merge Scala and Java fork options [here](https://github.com/gradle/gradle/blob/a97d31bafe72f212f7cc71d428d5a77ff473ad48/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java#L76) we lose a bunch of configuration on `JavaForkOptions`, such as `executable`, `boostrapclasspath` and others. This makes it currently impossible to cross-compile Scala code with a JDK other than the Gradle runtime JDK. This is problematic since Scala still recommends that the [compiler be run with Java 8](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#running-versus-compiling) despite running Gradle with more modern JDKs being increasingly common. This same issue seems to [exist for Groovy](https://github.com/gradle/gradle/blob/a97d31bafe72f212f7cc71d428d5a77ff473ad48/subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java#L88) as well.

**Comment by mark-vieira** [comment]
What would be the best CoA action here? A quick fix would just be to call `setExecutable()` on the newly created `JavaForkOptions` copying over the configured value, but as mentioned, there are other settings there.

The other option is to adapt `BaseForkOptionsConverter` such that it can take an existing `JavaForkOptions` instance to which it will merge in config instead of creating a new default instance.

**Comment by mark-vieira** [comment]
@ghale I know we had a long discussion about the mess that is all our "options" types. The real blocker here for us is the inability to fork Scala compilation with a different Java version than that of the daemon. This is a huge blocker for us right now as it's keeping one of our projects from moving on from Java 8 for the build runtime because the scala compiler encounters issues on newer Java versions.

Would adding an executable option to `ScalaCompileOptions` just exacerbate the current situation? I don't see a major aligning of all these compile option classes happening anytime soon, nor am I sure it's even practical or possible at this point.

**Comment by mark-vieira** [comment]
Or perhaps instead of `executable` a `javaHome` setting. In any case, we want to control the Java version used to run the scala compiler.

**Comment by ghale** [comment]
Yeah, it's not ideal - it might make more sense to key this off of `javaHome`.  Maybe that's slighlty less awkward.  Fundamentally, I think we want to separate the idea of what fork options the compiler daemon uses and what version of java we compile against.

@big-guy and I spoke about this a little yesterday and we're envisioning a migration path like:
1. Make the compiler daemon use the version of Java specified in the Java compile options for now.
1. Have the user declare which version they want to compile against and then we sanity check that against the version of Java the daemon is running with (potentially throwing an error if these don't match).
1. Have the user declare what version to compile against and separately declare what jvm version to run the compiler daemon with and we figure out how to make that all work.

The last item is a bit nebulous in terms of what flexibility we have, but the idea is to ultimately get to a point where we are better capturing the user's intentions.

**Comment by mark-vieira** [comment]
Just to clarify, for an initial pass and addressing this issue, we are only looking at implementing item (1) above, yes?

**Comment by ghale** [comment]
Yeah, steps 2 and 3 are the path to get from the awkward situation we have now to something more reasonable.

**Comment by mark-vieira** [comment]
Should this be added to the 6.4 rc1 milestone?

**Comment by ljacomet** [comment]
Thanks for spotting that and to Sterling for doing it already 👍
