### ISSUE TITLE
Project.fileTree and Delete task ignores files with trailing "~"

### ISSUE THREAD

**Issue by DALDEI** [gradle/gradle#1068]
I want to delete 'backup' files from common programs like vi as part of the 'clean' command.
To do this I created a simple Delete task like 

```
task cleanBackup(type: Delete) {
  delete  fileTree(projectDir) {
    include '**/*~'
  }
}
```

I tried many variations of this using project.files() project.fileTree() 

### Expected Behavior
I expected files named "somefile.java~" or "gradle.properties~" to be deleted.

### Current Behavior
The backup files were not deleted.
Further investigation shows that fileTree() itself is omitting the files.
Example:

```
   fileTree('.').each { 
     println it
  }

```
no files ending in "~" are ever listed.
No combination of 'include' 'matching' etc would ever find the backup files

I was able to come up with a method using recursive  File.listFiles(), 
It is very obtuse and took a long time to figure out.
I am guessing that "~" files are removed intentionally so they are not included in common
tasks and source sets etc.  But this makes a simple clean very difficult to create, 
and requires skills I suspect are beyond typical uses.
At minimum this (and if there are other exclusions) should be documented.
Ideally some method of explicitly including or matching *any* file should be be exposed in fileTree().

### Context
This caused issues with checking in by accident backup files, creating clean source 'tarballs' etc.
### Steps to Reproduce (for bugs)

touch foo~ src/foo~

build.gradle

```

task x {
  doLast { 
    fileTree('.').each { println it ; }
  }
}
```

gradle x

No files ending in "~"

This ended up working: 

```
def cleanFiles( String dir ) {
   file(dir).listFiles().each { 
      if( it.isDirectory() ) project.cleanFiles( it.path )
      if( it.name.endsWith("~" ) ) project.delete it
      }
  }
      

task cleanEclipse(type: Delete){
  outputs.upToDateWhen { false }
  delete 'bin'
  delete fileTree(projectDir) { 
    include "**/*.log" 
   }
   
   doLast {
     project.cleanFiles "."
   }
       
} 

tasks["clean"].dependsOn  cleanEclipse

```

### Your Environment
On request, this is repeatable on all systems I have tested.

**Comment by martinda** [comment]
Issue still exists with Gradle 6.5.
