### ISSUE TITLE
Provide a way to declare a set of file names or paths as a task input

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#10680]
The IDE and Swift PM plugins all have tasks that generate outputs that encode file paths, such as source and header files. Often these paths are relative to some base directory.

These tasks don't care about the _content_ of these files, but they do need to know their locations. These files need to be built, as they may be generated.

Currently, it is awkward and unreliable to express this kind of task input. It is not an uncommon kind of input (many kinds of export task or reporting tasks have this kind of input) and we should make it easier to express this, to make the native and Swift PM plugins more robust.

**Comment by lacasseio** [comment]
@wolfs What is the recommended way to express a file system path as input?

**Comment by lacasseio** [comment]
If there isn't a note in the documentation, it would be important to mention it.
