### ISSUE TITLE
Gradle task is skipped when added as a dependency

### ISSUE THREAD

**Issue by durgaswaroop** [gradle/gradle#1070]
I have these two gradle tasks in my `build.gradle` file  one to archive a folder and another to push it to a remote server. 

    task tarTask(type: Exec) {
        commandLine 'tar', '-czf', 'javadocs.tgz', 'javadocs/'
    }

If I execute tarTask alone with `gradle tarTask` and with the `publish` task commented out,  the build succeeds. 
I am using this task as a dependency in the publish task. 

    task publish(dependsOn: tarTask) {
        ssh.run {
            settings {
                knownHosts = allowAnyHosts
                fileTransfer = 'scp'
            }
    
            session(remotes.webServer) {
                from: 'javadocs.tgz', into: 'publishingHouse/'
            }
        }
    }

But when i execute `gradle publish` it fails saying that it is not able to find the tgz file which should have been created if the previous task is executed. 

> java.io.FileNotFoundException: javadocs.tgz

Being new to gradle i am not really sure what I am missing here. Any ideas on what I can do?
I am on a Windows environment  and I am running the commands on Babun (cygwin) Terminal.

**Comment by bmuschko** [comment]
Very likely your path is incorrect. You are just referring to the file name without a path. I'd recommend using `tarTask.archivePath` instead.

**Comment by durgaswaroop** [comment]
What path are you referring to? And where should add the `tarTask.archivePath`, In the task definition?

**Comment by bmuschko** [comment]
> What path are you referring to?

The path to `javadocs.tgz` in your `from` statement.

> And where should add the tarTask.archivePath, In the task definition?

Instead of the String `javadocs.tgz`.

**Comment by durgaswaroop** [comment]
I don't think path is the issue because if the tar file exists the build succeeds. But when the tar file doesn't exist, which should have been come from the `tarTask`, then the `publish` task fails.

**Comment by bmuschko** [comment]
Please provide a reproducible example project on GitHub so I can have a look.

**Comment by durgaswaroop** [comment]
I don't have anything else in my project or in my build.gradle file that can interfere with  these two tasks. So, as far as I can check it should be reproducible with this.

**Comment by bmuschko** [comment]
You will need to provide us with the full build script. Otherwise, I do not know what actually creates the directory `javadocs`. Also I am sure you are applying various plugins.

**Comment by durgaswaroop** [comment]
`javadocs` is  just a directory that is already present on the file system. But I'll try to create a sample project.

**Comment by durgaswaroop** [comment]
Okay, I found out the cause for the problem. As Stanislav has expalained [here](http://stackoverflow.com/questions/41332974/gradle-task-not-executed-if-added-as-a-dependency?noredirect=1#comment69875223_41332974), `publish` task was looking for the file at configuration phase while that file will not be available until the execution phase of the `tarTask`. 
So, If I add `doLast` like this, It works. 

```
task publish(dependsOn: tarTask) {
    doLast {
        ssh.run {
            settings {
                knownHosts = allowAnyHosts
                fileTransfer = 'scp'
            }
            String destinationDirectory = "publishingHouse/"

            session(remotes.webServer) {
                put from: 'javadocs.tgz', into: destinationDirectory
                put from: 'swagger.json', into: destinationDirectory
                put from: 'swagger-spec.html', into: destinationDirectory
            }
        }
    }
}
```

**Comment by lacasseio** [comment]
You are right @durgaswaroop. Without the `doLast` the code will be executed at configuration time. This means the `ssh.run` will be executed all the time even if the `publish` task isn't executed. The `doLast` add an action to execute only when the task will execute. I will close this issue as not actionable.
