### ISSUE TITLE
Demonstrate simple Web application

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#10714]
It was raised that a simple Web application is painful with Gradle. Let's build a sample for this use case and identify the pain.

Please comment on what Web framework you are using so we can focus the demonstration.

**Comment by big-guy** [comment]
We added a Spring boot sample: #11339

**Comment by lacasseio** [comment]
I think this request was coming more along the way of WAR and EAR type of web application. I created issue https://github.com/gradle/gradle/issues/11417 to track this.
