### ISSUE TITLE
Non-Kotlin extensions crash the build when using Kotlin DSL + Kotlin plugins

### ISSUE THREAD

**Issue by kenzierocks** [gradle/gradle#10729]
### Expected Behavior
I should be able to use extensions written in languages other than Kotlin.

### Current Behavior
The build crashes with this message:
```java
* What went wrong:
Unresolved class: class edu.wpi.first.gradlerio.frc.FRCPlugin$_apply_closure8
```

### Context
This stopped working in Gradle 5.6, due to [this](https://github.com/gradle/gradle/blob/d3fe455/subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/DefaultProjectSchemaProvider.kt#L129) being added. It assumes that `concreteClass` is a Kotlin type, and converts it to a `KClass`, but when the visibility is resolved, it obviously cannot find the Kotlin metadata and throws the above error. It should probably detect if it is indeed a Kotlin type, and otherwise detect via normal Java mechanisms.

Note: it's not quite as simple as simply adding a non-Kotlin plugin, and I'm not exactly sure why. It seems like the accessor class path isn't attempted for generation unless I apply it as a dependency of my Kotlin-DSL-based plugin. Regardless, the following project reliably reproduces the issue.

### Steps to Reproduce 
Run the build for this project:
https://github.com/kenzierocks/gradle-kdsl-gen-accessors-non-kotlin-types-issue

### Your Environment
Build scan URL: https://scans.gradle.com/s/5cm4zyadrsscs

**Comment by eskatos** [comment]
Thanks for the report @kenzierocks, I can confirm the regression. 

The `ProjectSchemaProvider ` chokes on Groovy closures added as extensions, like in:

https://github.com/wpilibsuite/GradleRIO/blob/304f416e374874fd73b994999aa9fab6cbf7e4a0/src/main/groovy/edu/wpi/first/gradlerio/frc/FRCPlugin.groovy#L76-L78

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/11014/commits/6516f3aa4f322fcfd2241ffd81643632bea8767a for Gradle 5.6.3 and in https://github.com/gradle/gradle/commit/aa0d471973449263c4219e10dffd4ca0b08a28fdfor Gradle 6.0

Thanks again for the report @kenzierocks
