### ISSUE TITLE
Maven Publish Plugin doesn't work with Kotlin Script

### ISSUE THREAD

**Issue by juergenzimmermann** [gradle/gradle#10723]
### Expected Behavior
No error

### Current Behavior
I try to use _Maven Publish Plugin_ in my `build.gradle.kts` (see below) as documented in https://docs.gradle.org/current/userguide/publishing_maven.html. However, I get an error because `from(...)` requires a `SoftwareComponent`, but ``TaskContainer.`components` `` returns `ComponentReport`.

```
val sourcesJar by registering(Jar::class) {
    from(sourceSets.main.get().allSource)
    archiveClassifier.set("sources")
}

publishing {
    repositories {
        maven { url = ... }
    }
    publications {
        create<MavenPublication>("...") {
            // from(...) requires SoftwareComponent, but components returns ComponentReport
            from(components["java"])
            artifact(sourcesJar.get())
            ...
```

### Context
I want to use the _Maven Publish Plugin_ to produce a `pom.xml` which is required when using _RedHat's OpenShift_.

### Steps to Reproduce 
See code fragment above.

### Your Environment
Gradle 5.6.2, OpenJDK 12.0.2, Windows 10 Enterprise

**Comment by juergenzimmermann** [comment]
Using `from (project.components.getAt("..."))` instead of  `from(components["..."])` solved the compilation problem.

**Comment by ljacomet** [comment]
This is strange, as shown [in this sample](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/userguide/publishing/javaLibrary/kotlin) the `project` prefix is not required.
Also by default `TaskContainer` does not have a `components`.

* Which plugins are you applying?
* Are you defining a `components` variable in your script?

**Comment by juergenzimmermann** [comment]
There is no `components`variable in my buildscript.

Here are my plugins:

```
plugins {
    idea
    jacoco
    `project-report`
    `maven-publish`

    kotlin("jvm") version "1.3.50"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.3.50"
    id("org.jetbrains.kotlin.plugin.noarg") version "1.3.50"
    id("com.adarshr.test-logger") version "1.7.0"
    id("io.gitlab.arturbosch.detekt") version "1.0.1"
    id("org.sonarqube") version "2.7.1"
    id("org.jetbrains.dokka") version "0.9.18"
    id("com.github.nwillc.vplugin") version "3.0.1"
    id("com.github.ben-manes.versions") version "0.25.0"
    id("com.google.cloud.tools.jib") version "1.6.0"
    id("com.fizzpod.sweeney") version "4.1.0"
    id("org.owasp.dependencycheck") version "5.2.1"
    id("org.asciidoctor.jvm.convert") version "3.0.0-alpha.3"
    id("org.asciidoctor.jvm.pdf") version "3.0.0-alpha.3"
    id("com.github.jk1.dependency-license-report") version "1.10"
}
apply(plugin = "org.springframework.boot") // version "2.2.0.M6"
```

**Comment by juergenzimmermann** [comment]
The problem is that I had the `publishing {...}` block inside a `tasks{...}` block. After moving the `publishing {...}` block as a top-level block the issue is gone.
I strongly recommend to document this.
