### ISSUE TITLE
Annotation processing does not included Filer-generated class files on compilation classpath in Java 8

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#10726]
### Expected Behavior
If an annotation processor generates `.class` files directly via `Filer#createClassFile`, it should be on the compilation classpath and be on the IDE indexing classpath. This way other code (generated or manual) can use the generated APIs. 

These should be considered part of the source sets as well (treated as classes without sources) and indexable by the IDE in the same way generated .java source files are. Yes they would be red before an initial build, but be present by the time annotation processing is done. Much in the same way as, say, how Dagger will generate a `Dagger__Component.java` that will be red until it's generated in the first build.

### Current Behavior
If an annotation processor generates `.class` files directly via `Filer#createClassFile`, the created class does not appear to be included on the compilation classpath. It _is_ included in the final jar though. This is a problem because it prevents sources (generated or manually written) from accessing any APIs in the generated class file. 

The class file APIs do not index in the IDE either. They partially index if `"$buildDir/classes/java/main/io/sweers/classgentesting/sample"` is added to dependencies via `files()`, but that does not fix the missing class file on compilation classpath and compilation will still fail. It also does not index in an importable way, oddly. It can only be fully qualified even if in the same package.

This also appears to not work even if a `.class` file is included manually in source sets (as in - not generated, just copied in). Not that that's a target use case, but probably a similar problem to how the Java compilation task views them.

### Context
The example is a small case, but this could be a general use improvement to any annotation processor by allowing them to generate bytecode directly when possible. This was an idea researched by the Dagger team at one point, and also a good solution for small-scope annotation processors that generate very simple code that could be done without adding to the compilation workload after processing is done ([dagger-reflect](https://github.com/JakeWharton/dagger-reflect/tree/master/codegen) is a good example of this).

### Steps to Reproduce 
Repro gradle project: https://github.com/ZacSweers/copydynamic/tree/z/dynamicInvocationTesting/classgentesting. Run `./gradlew :classgentesting:sample:build` Basically look at `SimpleClass.java` in the sample project [here](https://github.com/ZacSweers/copydynamic/blob/z%2FdynamicInvocationTesting/classgentesting/sample/src/main/java/io/sweers/classgentesting/sample/SimpleClass.java). 
After one attempted build (to generate the initial class file), it will link in the IDE but the build (and any subsequent) will not pass. Bytecode generation is in `ClassGenProcessor.java` using ASM.

The sample [build file](https://github.com/ZacSweers/copydynamic/blob/z%2FdynamicInvocationTesting/classgentesting/sample/build.gradle) also has the IDE indexing dependency trick.

### Your Environment
Build scan URL: https://scans.gradle.com/s/cjcyp3tny64q6s (but this gives me a message saying "This page does not exist. (or you do not have permission to view it)", so not sure what to do).

**Comment by big-guy** [comment]
Hi @ZacSweers,

If I'm following your example properly, this should fail?
1. Clone your repo and checkout z/dynamicInvocationTesting
2. Change classgentesting/sample/build.gradle to remove `files(["$buildDir/classes/java/main/io/sweers/classgentesting/sample"])` and `dependencies.compileClasspath(files(["$buildDir/classes/java/main/io/sweers/classgentesting/sample"]))`
3. Uncomment `SimpleClass instance = io.sweers.classgentesting.sample.SimpleClassFactory.create();` in `SimpleClass.java`
4. Run `./gradlew :classgentesting:sample:build`

This doesn't fail for me with 5.4.1 or 5.6.2.  Is there something else that's missing?

**Comment by ZacSweers** [comment]
When I do step 2, this is what I see in the IDE as a result

![image](https://user-images.githubusercontent.com/1361086/65543834-fde18780-dedf-11e9-9f7f-551328bb7974.png)

And when I do step 3 and 4, I get this:

```
z/dynamicInvocationTesting ✔  ./gradlew :classgentesting:sample:build

> Task :classgentesting:sample:compileJava FAILED
warning: No SupportedSourceVersion annotation found on io.sweers.classgentesting.processor.ClassGenProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '1.8'
/Users/pandanomic/dev/kotlin/personal/copydynamic/classgentesting/sample/src/main/java/io/sweers/classgentesting/sample/SimpleClass.java:29: error: cannot find symbol
    SimpleClass instance = io.sweers.classgentesting.sample.SimpleClassFactory.create();
                                                           ^
  symbol:   class SimpleClassFactory
  location: package io.sweers.classgentesting.sample
1 error
2 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':classgentesting:sample:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
6 actionable tasks: 5 executed, 1 up-to-date

```

Your build is successful and it links in the IDE?

**Comment by lwasyl** [comment]
Fwiw it fails for me too:
```diff
diff --git a/classgentesting/sample/build.gradle b/classgentesting/sample/build.gradle
index da462b0..426c6bc 100644
--- a/classgentesting/sample/build.gradle
+++ b/classgentesting/sample/build.gradle
@@ -24,4 +24,4 @@ dependencies {
 }
 
 // Trick to get generated classes to index in the IDE
-dependencies.compileClasspath(files(["$buildDir/classes/java/main/io/sweers/classgentesting/sample"]))
+// dependencies.compileClasspath(files(["$buildDir/classes/java/main/io/sweers/classgentesting/sample"]))
diff --git a/classgentesting/sample/src/main/java/io/sweers/classgentesting/sample/SimpleClass.java b/classgentesting/sample/src/main/java/io/sweers/classgentesting/sample/SimpleClass.java
index 16808ca..8ede84b 100644
--- a/classgentesting/sample/src/main/java/io/sweers/classgentesting/sample/SimpleClass.java
+++ b/classgentesting/sample/src/main/java/io/sweers/classgentesting/sample/SimpleClass.java
@@ -26,6 +26,6 @@ public final class SimpleClass {
 
   public static void main(String[] args) {
     // This will not compile if you uncomment it even though it links
-    //SimpleClass instance = io.sweers.classgentesting.sample.SimpleClassFactory.create();
+    SimpleClass instance = io.sweers.classgentesting.sample.SimpleClassFactory.create();
   }
 }
```

```
▶ ./gradlew :classgentesting:sample:build --rerun-tasks

> Task :classgentesting:sample:compileJava FAILED
warning: No SupportedSourceVersion annotation found on io.sweers.classgentesting.processor.ClassGenProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '1.8'
/Users/wasyl/projects/temp/copydynamic/classgentesting/sample/src/main/java/io/sweers/classgentesting/sample/SimpleClass.java:29: error: cannot find symbol
    SimpleClass instance = io.sweers.classgentesting.sample.SimpleClassFactory.create();
                                                           ^
  symbol:   class SimpleClassFactory
  location: package io.sweers.classgentesting.sample
1 error
2 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':classgentesting:sample:compileJava'.
> Compilation failed; see the compiler error output for details.
```

```
▶ java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

**Comment by big-guy** [comment]
Yep, it worked for me, but I saw you might be using Java 8 and tried again.  That fails for me in the same way now.  I had originally tried it with Java 11.

Java 9 and 11 both seem to work, so I wonder if the Java 8 compiler needs a workaround (or isn't expected to work).

**Comment by ZacSweers** [comment]
interesting! Let me see if I can confirm that locally

**Comment by ZacSweers** [comment]
Yep confirmed on my end as well. Java 9, 11, and 12 all work. IDE indexing still requires the build.gradle workaround, but the build itself passes.

**Comment by ZacSweers** [comment]
Still an issue

**Comment by ZacSweers** [comment]
Closing due to lack of feedback from Gradle
