### ISSUE TITLE
Gradle 5.6.2 does not support lombok @Slf4j ?

### ISSUE THREAD

**Issue by 120011676** [gradle/gradle#10727]
### Expected Behavior
gradle build, success

### Current Behavior
> Task :manager:compileTestJava FAILED
/private/tmp/industry-server/manager/src/test/java/com/changhong/industry/database/PasswordTest.java:3: error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/private/tmp/industry-server/manager/src/test/java/com/changhong/industry/database/PasswordTest.java:11: error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/private/tmp/industry-server/manager/src/test/java/com/changhong/industry/other/ArrayTest.java:3: error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
/private/tmp/industry-server/manager/src/test/java/com/changhong/industry/other/ArrayTest.java:10: error: cannot find symbol
@Slf4j
 ^
  symbol: class Slf4j
/private/tmp/industry-server/manager/src/test/java/com/changhong/industry/controller/commodity/CommodityTypeControllerTest.java:4: error: package lombok.extern.slf4j does not exist
import lombok.extern.slf4j.Slf4j;
                          ^
![image](https://user-images.githubusercontent.com/1992933/64932302-7dcc7980-d870-11e9-947e-0b68477ec4dc.png)

### Context
Using lombok @Slf4j

### Your Environment
gradle 5.6.2
java 12.0.2
lombok 1.18.8

Build scan URL:

**Comment by blindpirate** [comment]
Can you please share a minimal reproducible example?

**Comment by 120011676** [comment]
@blindpirate https://github.com/120011676/lombok-gradle-slf4j.git

**Comment by blindpirate** [comment]
Test annotation processing need 

```
	testAnnotationProcessor 'org.projectlombok:lombok'
	testCompileOnly 'org.projectlombok:lombok'
```

to function.

**Comment by 120011676** [comment]
#10556 It's also my functional requirement or defect.

**Comment by 120011676** [comment]
@blindpirate Thank you,good,Although there are repetitions
