### ISSUE TITLE
Prevent publication of module with same variant name or equivalent variants

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#10736]
When publishing Gradle metadata, making it illegal to produce the following would help build and plugin authors in getting it right:
* Prevent publication of two variants with the same name
* Prevent publication of two equivalent variants, that is with the same attributes and capabilities

While technically a breaking change, this sounds like earlier error detection during publication.

**Comment by jjohannes** [comment]
Should we also fail (or warn?) if there is no variant in the publication? 
- Can more likely happen with #10510 in place
- Related to #7888 (fail when resolving GMM module without variants)
