### ISSUE TITLE
Gradle removes other package-private classes after an incremental compilation following a non-functional change in another class

### ISSUE THREAD

**Issue by GreenRecycleBin** [gradle/gradle#10746]
### Expected Behavior
Gradle doesn't remove other package-private classes after an incremental compilation following a non-functional change in another class.

### Current Behavior
Gradle removes other package-private classes after an incremental compilation following a non-functional change in another class.

### Context
Gradle doesn't exhibit the current behavior described above when the classes, which otherwise would be affected if they were package private, are public. Developers shouldn't have to resort to changing classes' visibility to make their code work with Gradle's incremental compilation.

### Project to Reproduce
[astrology.zip](https://github.com/gradle/gradle/files/3619900/astrology.zip)

### Steps to Reproduce 
1. `$ cd /tmp && mkdir astrology && cd astrology`
2. `$ unzip <path to astrology.zip>`
3. `$ ./gradlew test` (This must pass)
4. `$ echo -e '\n// Comment' >> src/main/java/io/github/greenrecyclebin/astrology/ValidationError.java` (Add a non-function change, i.e. a comment, at the end of ValidationError.java)
5. `$ ./gradlew test` (This fail when it shouldn't because ControllerAdvice.class has been removed)
6. `$ ./gradlew clean test` (This must pass)
7. Remove the comment added in step 4 above
8. `$ ./gradlew test` (This fail when it shouldn't because ControllerAdvice.class has been removed)
9. `$ ./gradlew clean test` (This must pass)

### Your Environment
```
$ uname -a
Linux localhost.localdomain 5.2.14-200.fc30.x86_64 #1 SMP Tue Sep 10 12:17:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment 18.9 (build 11.0.4+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11, mixed mode, sharing)
$ ./gradlew --version

------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (Oracle Corporation 11.0.4+11)
OS:           Linux 5.2.14-200.fc30.x86_64 amd64
```

### Comment
I guess this has to do with how Gradle decides which source files need to be recompiled in an incremental compilation. This list is somehow different from the respective one in a non-incremental (i.e. full) compilation.

I'd appreciate pointers to learn more about this. Thank you for your time and effort in building Gradle.

**Comment by GreenRecycleBin** [comment]
By the way, this issue is reproducible on the current latest version, i.e. v5.6.2, too.

**Comment by GreenRecycleBin** [comment]
By the way, this issue is reproducible on the current latest version, i.e. v5.6.2, too.

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (Oracle Corporation 11.0.4+11)
OS:           Linux 5.2.14-200.fc30.x86_64 amd64
```

**Comment by GreenRecycleBin** [comment]
This issue is not reproducible on the current latest version, i.e. v6.7.1.

Note to self to investigate how this was fixed.

**Comment by GreenRecycleBin** [comment]
After bisecting, the first commit that fixes this was https://github.com/gradle/gradle/commit/4493ca6395875ee91ddc532d24b5d7113c925578, part of https://github.com/gradle/gradle/pull/12511.

This is the same issue as https://github.com/gradle/gradle/issues/7363. The test for this is at https://github.com/gradle/gradle/commit/4493ca6395875ee91ddc532d24b5d7113c925578#diff-e93b6b7c81b2741c7c85cbaf017e5a00a354381f7a0cbf07e6c60d50c6bcb550R264-R306. 

[bisect-log.txt](https://github.com/gradle/gradle/files/5741109/bisect-log.txt)

**Comment by lptr** [comment]
Thanks for digging this up @GreenRecycleBin. I've added the milestone.
