### ISSUE TITLE
javadoc not working if dependency is defined using `implementation` (instead of `compile`)

### ISSUE THREAD

**Issue by dgruntz** [gradle/gradle#10741]
I have changed my dependencies in my java project from "compile" to "implements". As a consequence javadoc can no longer be created. The build file looks as follows:

    plugins {
        id 'java'
    }
    
    repositories {
        jcenter()
    }
    
    dependencies {
        implementation 'log4j:log4j:1.2.17'
    	
        testImplementation 'junit:junit:4.12'
    }
    
    task docs(type: Javadoc) {
        classpath = configurations.runtime
        source = sourceSets.main.allJava
    }

and the project contains the following simple source:

    package javadoc;
    
    import org.apache.log4j.BasicConfigurator;
    
    public class App {
        /**
         * Main Entry
         * @param args runtime arguments
         */
        public static void main(String[] args) {
        	BasicConfigurator.configure();
            System.out.println(new App().getClass().getName());
        }
    }

### Current Behavior

`gradle build` works fine, but if I execute `gradle docs` I get the following error:

    % gradle docs
    
    > Task :docs FAILED
    C:\Temp\javadoc\src\main\java\javadoc\App.java:3: error: package org.apache.log4j does not exist
    import org.apache.log4j.BasicConfigurator;
                           ^
    1 error
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':docs'.
    > Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'C:\Temp\javadoc\build\tmp\docs\javadoc.options'
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 1s
    1 actionable task: 1 executed

### Expected Behavior

If I change the depencency to use `compile` instead of `implemenation` javadoc can be created without problems:

    % gradle docs
    
    BUILD SUCCESSFUL in 2s
    1 actionable task: 1 executed

### Your Environment

    % gradle -version
    
    ------------------------------------------------------------
    Gradle 5.6.2
    ------------------------------------------------------------
    
    Build time:   2019-09-05 16:13:54 UTC
    Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781
    
    Kotlin:       1.3.41
    Groovy:       2.5.4
    Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
    JVM:          11.0.2 (Oracle Corporation 11.0.2+9-LTS)
    OS:           Windows 7 6.1 amd64

Build scan URL: 
Failure: https://gradle.com/s/xgddeimgc7nqm
Successful: https://gradle.com/s/xgycg46zd3jom

**Comment by ljacomet** [comment]
The issue is the way you specified the `classpath` property of the `javadoc` task with:
`classpath = configurations.runtime`

As can be seen in the [documentation](https://docs.gradle.org/5.6.2/userguide/java_plugin.html#sec:java_plugin_and_dependency_management), `runtime` is deprecated, does not extend `implementation`, and thus will not have the declared dependencies available.
You should keep it at its [default value](https://docs.gradle.org/5.6.2/dsl/org.gradle.api.tasks.javadoc.Javadoc.html#org.gradle.api.tasks.javadoc.Javadoc:classpath) or maybe for some cases change it to:
`classpath = project.sourceSets.main.runtimeClasspath`

**Comment by dgruntz** [comment]
@ljacomet, thanks for your help, declaring the classpath as 
`classpath = project.sourceSets.main.runtimeClasspath` 
solved my problem, but without declaring any classpath I still get an error message.
