### ISSUE TITLE
Deprecate using Java lambda as task action

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#10751]
We already turn off caching for task actions that are specified as lambdas. We should consider deprecating support completely.

----
/cc @gradle/build-cache

**Comment by bamboo** [comment]
What if they were `Serializable` actions?

**Comment by lptr** [comment]
IIUC we'd need to make `Action` serializable for that. I'm not sure about the implications of the first, but I suspect it would break a few things down the road. Do you have a good assessment of what it would take to do it?

We could probably also introduce something like `SerializableAction`, but that already adds complexity, and we'd need to come up with a new method name, as overloading `doFirst/doLast()` would make lambdas ambiguous. Not a terribly attractive direction.

I'm hoping to deprecate `doFirst()` and `doLast()` entirely sometime in favor of typed actions that must declare their own inputs and outputs properly. If we get to do that in the foreseeable future, then adding more complexity to `doFirst/doLast()` would be even less useful.

**Comment by wolfs** [comment]
We still want to emit the deprecation warning to make users aware of the problem.
