### ISSUE TITLE
Make Gradle Java docs more concise and add missing examples

### ISSUE THREAD

**Issue by mleonhard** [gradle/gradle#10764]
Learning gradle is taking me a long time.  I have spent more than a day and my straightforward Java project still isn't compiling and running tests the way I need. I don't want to read 67 pages just to get this stuff working:
 - [Build Script Basics](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html) 18 pages
 - [Building Java & JVM projects](https://docs.gradle.org/current/userguide/building_java_projects.html) 24 pages
 - [Testing in Java & JVM projects](https://docs.gradle.org/current/userguide/java_testing.html) 25 pages

It would be good to spend some effort rewriting these docs.  Make them describe Gradle and what it does, with examples.  Delete the extra prose describing how to make decisions about how to use Gradle.

The doc [Building Java & JVM projects](https://docs.gradle.org/current/userguide/building_java_projects.html) could use some editing.  I believe it would be improved by removing unnecessary words and by including simple examples in each section.

For example, the `Running Tests` section doesn't even contain an example of running tests and seeing output.  Such an example would address the first problem any gradle-java user has: how to see which tests ran and their output.  Specifically, they need to add this into their build.gradle file:
```
test {
    testLogging {
        events "started", "passed", "skipped", "failed", "standardOut", "standardError"
    }
}
```
Better yet, make that the default behavior so Gradle always shows which tests ran and their output.  Then provide a simple example of how to silence that output.

There's a lot of magic in Gradle.  The java plugin adds a bunch of tasks.  Why not just show a `build.gradle` file with those tasks, so readers can just see it for themselves?  Then you can save them the time of having to read a prose description of the thing.

Also consider giving the srcDirs() and srcDir() methods clear names: setSrcDirs() and addSrcDir().  Why make users read paragraphs to learn what these methods are, when you could just name them clearly?

**Comment by mleonhard** [comment]
Make the [Packaging & Publishing](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_packaging) section explain:
- A JAR file is created by default
- The path where the file is created
- How the name of the file is chosen
- What goes in it by default, stating the precise source set names and file globs
- Explain what is an uber/fat JAR

This is what people need.  Instead we have:

> How you package and potentially publish your Java project depends on what type of project it is. Libraries, applications, web applications and enterprise applications all have differing requirements. In this section, we will focus on the bare bones provided by the Java Plugin.
> 
> The one and only packaging feature provided by the Java Plugin directly is a jar task that packages all the compiled production classes and resources into a single JAR. This JAR is then added as an artifact — as opposed to a dependency — in the archives configuration, hence why it is automatically built by the assemble task.
> 
> If you want any other JAR or alternative archive built, you either have to apply an appropriate plugin or create the task manually. For example, if you want a task that generates a 'sources' JAR, define your own Jar task like so: ...

Also, consider changing the `java` plugin to create fat JARs by default.  This is 2019, not 2004.  Disk space and bandwidth is cheap.  And Java still doesn't have a run-time dependency system, so everyone is building, testing, and then deploying fat JARs.

**Comment by big-guy** [comment]
Maybe the [Building Java Applications](https://guides.gradle.org/building-java-applications/) or [Building Java Libraries](https://guides.gradle.org/building-java-libraries/) are closer to what you're looking for?
