### ISSUE TITLE
Dependencies of feature variant are not added to the test classpath

### ISSUE THREAD

**Issue by aburmeis** [gradle/gradle#10778]
I am migrating a Maven library project to Gradle. The original project also has optional dependencies. I use the [java-library plugin][1] but moving the formerly optional dependencies to implementation results in runtime dependencies instead of compile. So I tried the gradle [feature variants][2] which results in the right dependencies in the `pom.xml`. But doing so results is failing test compile as the dependencies of the feature variant are missing on the test compile classpath!

Here is my current setup in `build.gradle`:

```
apply plugin: 'java'
apply plugin: 'java-library'
apply plugin: 'maven-publish'

sourceCompatibility = 1.8

java {
  registerFeature('oSupport') {
    usingSourceSet(sourceSets.main)
  }
}

dependencies {
  api 'my.compile:dep-a:1.0.0'
  implementation 'my.runtime:dep-i:1.0.0'
  oSupportApi 'my.optional:dep-o:1.0.0'
}
```

Let's assume there is a class `O` available from `my.optional:dep-o`. If I import `O` in any class in `src/main/java` it works perfectly. Also the dependencies are exported right to Maven (using `gradle generatePomFileForMavenJavaPublication`, see the dependencies from the generated `pom.xml` below). But any test in `src/test/java` using class `O` will not compile (`import my.optional.O;` creates  `error: package my.optional does not exist`)

``` xml
<dependencies>
    <dependency>
      <groupId>my.compile</groupId>
      <artifactId>dep-a</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>my.rintime</groupId>
      <artifactId>dep-r</artifactId>
      <version>1.0.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>my.optional</groupId>
      <artifactId>dep-0</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
</dependencies>
```

PS: I use Java 8 and Gradle 5.6.2

In [stackoverflow](https://stackoverflow.com/questions/57988257/how-to-use-gradle-feature-variant-dependecies-in-tests) there are two work arounds but I think this should work out of the box. The problem may relate to #6483 but I am not sure.

  [1]: https://docs.gradle.org/current/userguide/java_library_plugin.html
  [2]: https://docs.gradle.org/current/userguide/feature_variants.html

**Comment by melix** [comment]
Thanks for the report. BTW, you don't need both `java` and `java-library` plugins. `java-library` is enough.

**Comment by s4nk** [comment]
@melix which feature dependency will end up on test classpath when using mutually exclusive variants (see https://docs.gradle.org/current/userguide/feature_variants.html#sec::incompatible_variants)?
