### ISSUE TITLE
XmlValidation.isLegalCharacter contains "always true" char c<0x10000 branch

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10773]
https://github.com/gradle/gradle/blob/84f01f434da42e9a2394371379c2a0d0c60517c7/subprojects/core/src/main/java/org/gradle/internal/xml/XmlValidation.java#L128

### Expected Behavior

It is not clear what that method validates, however it should probably validate a codepoint (`int`) rather than `char` value.

### Current Behavior

The code contains `if (c < 0x10000) {` conditions which is always true.

### Context

See https://github.com/gradle/gradle/issues/10770

### Steps to Reproduce 

Open `org.gradle.internal.xml.XmlValidation#isLegalCharacter` in IDEA.
It displays warning that `if (c < 0x10000) {` is always true.

### Your Environment

Gradle master branch (~ 84f01f434da42e9a2394371379c2a0d0c60517c7 ).

**Comment by vlsi** [comment]
@wolfs , technically speaking, the issue has been fixed in https://github.com/gradle/gradle/pull/10803

**Comment by wolfs** [comment]
@vlsi Nice, thank you for the info! I set the milestone.
