### ISSUE TITLE
executing the uname command in shell script from a gradle file on git bash returns Linux

### ISSUE THREAD

**Issue by musaddiqrg** [gradle/gradle#10788]
### Expected Behavior
On git bash, if I execute a script with the `uname` command in it, prints out `MINGW64_NT-10.0`. If I execute this script from gradle, I expect the same behaviour.

### Current Behavior
Prints out `Linux` instead

### Context
I am trying to run some deployment scripts which ordinarily work in git bash.

### Steps to Reproduce 
My script  
`
#!/bin/bash
uname
`

My gradle file is 
`
task uname() {
    doLast {
        exec {
            commandLine "bash", "./uname_script.sh"
        }
    }
}
`

### Your Environment
Using Windows 10, git bash, gradle 5.6.2

**Comment by big-guy** [comment]
Is it possible you're executing this in the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

**Comment by musaddiqrg** [comment]
no definitely in git bash
