### ISSUE TITLE
Fully deprecate the Upload task and related concepts

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#10796]
While Gradle 6.0 deprecates the usage of the `maven` plugin and the usage of the default `Upload` tasks created in a project, there is no general deprecation of the usage of `Upload` tasks.

This should be done to completely retire the legacy publication system.

**Comment by jjohannes** [comment]
This method should be deprecated: [Configuration.getUploadTaskName()](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/Configuration.java#L274)
