### ISSUE TITLE
"all" classifier not included in pom file when deploying a library that depends on sibling project's shadow configuration in multi-project build

### ISSUE THREAD

**Issue by domesticsimian** [gradle/gradle#10793]
I have a multi-project build that makes use of the `com.github.johnrengelman.shadow` plugin to re-package and re-namespace a library. In this setup, one of the libraries in the project (SomeLib1) depends on the `shadow` configuration of another library (SomeLib2). I have a minimal reproduction of this setup in https://github.com/disturbedsaint/shadowpom. 

### Expected Behavior
When I publish SomeLib1 to maven, I expect its pom file to refer to the `all` classifier of SomeLib2.

### Current Behavior
SomeLib1's pom file does not include the `all` classifier. This causes projects that use SomeLib1 to fail at runtime.

### Context
As mentioned above, the purpose of this specific library is to re-namespace the classes of some external dependency. But generally speaking, building fat jars can be used to minimize the number of external dependencies a given jar file has.

### Steps to Reproduce 
See https://github.com/disturbedsaint/shadowpom for code plus repro instructions.

### Your Environment
I've reproduced on OSX and Linux. The versions of gradle / shadow are specified in https://github.com/disturbedsaint/shadowpom.

At this point, I have no idea if the problem is in gradle or the shadow plugin. I've already filed https://github.com/johnrengelman/shadow/issues/514, but so far no movement there.

**Comment by ljacomet** [comment]
This is unfortunately not a new issue, however it is something that might get fixed in the future.
The shadow plugin would need to leverage the variant aware dependency management features of Gradle so that you no longer express the dependency with a `classifier` but instead use attributes.

Before that happens, a workaround is to add the missing `classifier` to the generated POM file with `MavenPublication.pom.withXml`

**Comment by ljacomet** [comment]
Sorry for the late reply

The issue is in the backlog of the relevant team and is prioritized by them.
