### ISSUE TITLE
Gradle may miss changes to files that are made immediately after the previous build

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#1079]
Gradle uses file modification timestamps to decide whether to hash the content of a file to check for changes. Sometimes this strategy can miss changes, for example, when the following sequence happens: change file > run fast build > change file > run build. When the first build is very fast, the file may end up with the same modification time after both mutations, meaning the second build will consider the file unchanged.

This sequence often happens when running tests or benchmarks against Gradle or a plugin.

### Expected Behavior

Gradle should consider all changes to a file.

### Current Behavior

Gradle sometimes misses these changes.

**Comment by adammurdoch** [comment]
A fix has been pushed, let's see how it goes.

**Comment by eriwen** [comment]
@adammurdoch Is this still in progress, done, or deferred?

**Comment by adammurdoch** [comment]
Done.
