### ISSUE TITLE
Deprecation of artifacts block

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#10797]
The `archives` configuration and the `artifacts` block are linked to the legacy publication system.

They however also serve to trigger building of registered archive tasks through the lifecycle task `assemble`.

In order to deprecate them a proper alternative needs to be found, including asking users to declare `assemble.dependsOn(myArchiveTask)`.

**Comment by rkrisztian** [comment]
Deprecating the `archives` configuration looks fine to me, but **are you sure about deprecating the `artifacts` block**? Please tell, how are we supposed to define inter-project dependencies then?

On [Multi-Project Builds](https://docs.gradle.org/current/userguide/multi_project_builds.html), we see multiple examples:

*  `subprojects { from tasks.withType(War) }`: if I understand it right, _"Declaring a task dependency from one project to another is a poor way to model this kind of relationship and introduces unnecessary coupling."_ Does that apply to this example too?
    * I guess it surely does apply to `from ':some-other-project:some-task'`.
* One example used `sourceSets { main { output.dir(buildInfo.outputFile.parentFile, builtBy: buildInfo) } }`, which you can refer to as `dependencies { runtimeOnly project(':producer') }`, but how do you actually refer to the exact artifact produced by the task then, without duplicating the path? You might create a separate source set, but I don't need all the extra classpath configurations that come with it.
* But then all we have left is the project dependency you can do from `artifact { myConfig myTask }`, which the current guide still mentions as a valid, non-legacy way of sharing artifacts between projects.

**Comment by melix** [comment]
Why do you want to deprecate the `artifacts` block? It's still used even for the new publishing.

**Comment by ljacomet** [comment]
I am talking about the `artifacts` block as in [the first exemple here](https://docs.gradle.org/current/userguide/artifact_management.html#sec:file_artifacts), not the `artifact` method in a publication.

How do you see it used in the `*-publish` plugins?

**Comment by jjohannes** [comment]
With #12379, the _archives_ configuration has been deprecated for _resolving_ and _dependency declaration_. To deprecate it completely, this issue has to be fixed first in the WAR and EAR plugins: #1353

**Comment by autonomousapps** [comment]
Please see [this thread](https://gradle-community.slack.com/archives/CAH4ZP3GX/p1596579656269200) in the gradle community slack for more reasons for removing the archives configuration and changing the behavior of `assemble`.

**Comment by eskatos** [comment]
@autonomousapps, I just opened https://github.com/gradle/gradle/issues/14065 about the specific problem discussed on slack.

**Comment by jjohannes** [comment]
I think #15639 is what we should do for 7.1

I think we should not touch the `artefacts {}` block until we have a clear replacement identified as part of the "aggregation topic" we are going to work on (see https://github.com/gradle/gradle/issues/9834#issuecomment-702090336).

**Comment by melix** [comment]
I don't think we should deprecate the `artifacts { }` block either.

**Comment by ljacomet** [comment]
Closing as stale indeed, these topics will be addressed differently.
