### ISSUE TITLE
Lazy evaluation of parent/grand-parent pom's properties

### ISSUE THREAD

**Issue by yetanotherion** [gradle/gradle#1080]
The following (failing) unit test might explain the issue better than text:
https://github.com/yetanotherion/gradle/commit/425cf55bc31cd651f840f38a25ccbf1d9b261bab

### Expected Behavior
dep.requested == moduleId('group-one', 'artifacttwo', '3')
(maven seems to do so)

### Current Behavior
dep.requested == moduleId('group-one', 'artifacttwo', '2')

**Comment by bmuschko** [comment]
Did you experience the issue for a concrete dependency from a Maven Central or a different Maven repository? It would be helpful to better understand how you came across the issue. Does the Maven POM specification explain this detail?

**Comment by yetanotherion** [comment]
- Did you experience the issue for a concrete dependency from a Maven Central or a different Maven repository?
Different Maven repository (internal)
- Does the Maven POM specification explain this detail? 
To reformulate: "maven seems to do so", we're currently migrating a maven build system to gradle and faced this "unexpected" bug in gradle but not in maven. I did not find such specification for now, I'll keep looking and write the links I found in that issue.
- What version of Gradle are you using ?
  3.2.1 and the gradle built on https://github.com/gradle/gradle/commit/e081c642f3a8b6374d22f1b597faa3c7563dd333

**Comment by bmuschko** [comment]
Thanks for the information. Is there any chance this dependency exists in Maven Central as well so I can reproduce the issue?

**Comment by yetanotherion** [comment]
Unfortunately, this one is not published. If I find any available in Maven Central I'll post the link that issue.
I would have two other questions:
- Would you be willing to merge a PR that fixes the unit test (I did not finish it yet), or 
- You'll prefer to have a confirmation that it's not an internal issue only, from either the maven pom spec or a dependency in Maven Central ?

**Comment by bmuschko** [comment]
I'd prefer being able to reproduce the issue with a real dependency first.

**Comment by yetanotherion** [comment]
Ok, just to be sure: would you consider 
- dummy dependency/artifacts uploaded 
- _just_ to reproduce the issue 
- as a valid use case to confirm the bug ? `(if confirmed)`

**Comment by bmuschko** [comment]
I'd be OK with any publicly-available dependency (e.g. on Maven Central or other repository) that exposes the issue when resolved from Maven and Gradle. When resolved on Maven it works, when resolved from Gradle it fails.

**Comment by yetanotherion** [comment]
After checkout-ing
https://github.com/yetanotherion/gradle/commit/b20f48039a20884383f3916218d686ab4f6d38a2
`cd test`

maven test (succeeds in my workstation)
`bash test_maven.sh`
...
>Downloading: https://criteo.bintray.com/integration-tests/com/criteo/dummy/artifacttwo/2.0/artifacttwo-2.0.pom

gradle test (fails in my workstation)
`bash test_gradle.sh`
> Could not resolve all dependencies for configuration ':compile'.
   > Could not find com.criteo.dummy:artifacttwo:1.0.
     Searched in the following locations:
         https://criteo.bintray.com/integration-tests/com/criteo/dummy/artifacttwo/1.0/artifacttwo-1.0.pom
         https://criteo.bintray.com/integration-tests/com/criteo/dummy/artifacttwo/1.0/artifacttwo-1.0.jar
     Required by:
         project : > com.criteo.dummy:artifactone:1.0

**Comment by bigdaz** [comment]
The core issue is that Gradle resolves properties in a parent POM in the context of the properties defined for that parent POM. It appears that Maven resolves properties in a parent POM using the properties of the importing child POM.

This is a bit surprising to me, but I suppose the 'correct' behaviour of parent POM resolution is defined by what Maven does, since this behaviour is not well specced out, as far as I can tell.

**Comment by superbobry** [comment]
It is indeed surprising, but it actually makes sense, if you think about properties in the context of programming languages (even though Maven is not one of them). 

Too bad Maven doesn't state this explicitly. The only googlable mention of this behaviour I've managed to find is [this](http://ted-gao.blogspot.fr/2011/08/inheritance-and-overriding-in-maven.html) blogpost.

**Comment by yetanotherion** [comment]
Actually, I don't know whether this behaviour is wanted by maven neither (did not see this case in maven unit tests). I agree with @superbobry's analogy though and I'd personally prefer both maven and gradle to behave like that. If you're ok with it, I'll start working on a fix.

**Comment by yetanotherion** [comment]
A first version of the fix is available at:
https://github.com/yetanotherion/gradle/commit/35b7f7cfd7c72f75de138d6176826a535207d44b

I have some questions before submitting a PR.
- Do you consider this change as "a non-trivial change that modifies the behavior or public API" ?
- If so, I'm supposed to 
 
  - Start a discussion on the Gradle developer list. Is it still necessary, considering the discussion we had here ?
  - Write a design document. Is it necessary ? (I don't see much to say about the design/implementation)
  - Add a section on the user guide. I personally think that this one is necessary, even if the change is not considered as "a non-trival change that modifies the behavior or public API".

Waiting for your inputs before going further :)

**Comment by yetanotherion** [comment]
@bmuschko FYI 
- The Bintray trial used to create a "bug reproducing environment" (see comment posted 22 days ago), will be over in 7 days. Said otherwise, the instructions mentioned in the comment above, that seems to confirm the issue, won't work in 7 days.
- A fix is available at https://github.com/gradle/gradle/pull/1192. It's most probably too late to integrate it in the 3.4 release. Feel free to do whatever seems convenient to you with it. From our side, we'll use it in a forked version.

**Comment by superbobry** [comment]
Just to get the discussion going again, is there a chance to see this in one of the upcoming Gradle releases?
