### ISSUE TITLE
Remove property CompileOptions.useDepend and corresponding public methods

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1081]
Now we have real incremental Java compilation, remove the `CompileOptions.useDepend` property and related options.

**Comment by bmuschko** [comment]
Closed as superseded by https://github.com/gradle/gradle/issues/1722

**Comment by eriwen** [comment]
@adammurdoch I thought it best to remove `DependOptions` as I could not find any external OSS use on the through [GitHub's search](https://github.com/search?l=&q=dependOptions+language%3AGroovy+or+language%3AJava&ref=advsearch&type=Code&utf8=%E2%9C%93). 

or through BigQuery public GitHub data:
```
SELECT
  content,
  sample_repo_name,
  sample_path,
  id
FROM
  [bigquery-public-data:github_repos.sample_contents]
WHERE
  content CONTAINS 'ependOptions'
```

Same as the Ant-based classes like `AntDependsStaleClassCleaner`.
