### ISSUE TITLE
Gradle 6.0 incorrectly maps the name portion of a feature variant's G:A:V coordinates

### ISSUE THREAD

**Issue by lingocoder** [gradle/gradle#10821]
### Context
According to version *`6.0-20190919220024+0000 Nightly`*'s [*Modeling features and their dependencies*](https://docs.gradle.org/nightly/userguide/modeling_features.html?_ga=2.183551526.1481707721.1568671834-850243443.1555977515#sec::declare_feature_variants) documentation:

> „*By convention, Gradle maps the feature name to a capability whose group and version are the same as the group and version of the main component, respectively, but whose name is the main component name followed by a - followed by the kebab-cased feature name.*
>
> *For example, if the group is org.gradle.demo, the name of the component is provider, its version is 1.0 and the feature is named mongodbSupport, the feature variant will be org.gradle.demo:provider-mongodb-support:1.0.*“

### Problem

If I create a *`java-library`* project that uses *`registerFeature('mongodbSupport')`*, and if I set the *`version`* property in the project's *`build.gradle`* to *`0.0.0-jdk8`*, then Gradle *`6.0-20190919220024+0000`* does not produce a feature variant that has a *`G:A:V`* coordinate precisely of the form the currently-published documentation says should be expected.

### Expected Behavior

```
    > Task :outgoingVariants 
    --------------------------------------------------
    Variant mongodbSupportApiElements
    --------------------------------------------------
    ...
    Capabilities
    - mr.jar:provider-mongodb-support:0.0.0-jdk8 (default capability)
    ...
      
```

### Actual Behavior

```
    > Task :outgoingVariants
    --------------------------------------------------
    Variant apiElements
    --------------------------------------------------
    ...
    Capabilities
    - mr.jar:provider:0.0.0-jdk8 (default capability)
    ...
      
```

### Steps to Reproduce
<sup>[***download example project***](http://bit.ly/Issue10817)</sup>
1. Create a simple *`java-library`* project that uses the *`6.0-20190919220024+0000`* wrapper <br />
    • Use [*the online Gradle Initializer*](http://bit.ly/GradleInit) for convenience

2. Add the following to the *`build.gradle`*: <br />

    ```
    ...
    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    java {
        registerFeature('mongodbSupport') {
            usingSourceSet(sourceSets.main)
        }
    }

    version = '0.0.0-jdk8'
    group = 'mr.jar'
    ...

   ```    
    
3. In a terminal, do: *`./gradlew outgoingVariants --all`*

### Environment

    ------------------------------------------------------------
    Gradle 6.0-20190919220024+0000
    ------------------------------------------------------------
    
    Build time:   2019-09-19 22:00:24 UTC
    Revision:     f6c349254943c709e33dd409729174f5adf9f6ce
    
    Kotlin:       1.3.50
    Groovy:       2.5.8
    Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
    JVM:          13 (Oracle Corporation 13+33)
    OS:           Windows 7 6.1 amd64    

From what I observe of the actual feature variant *`G:A:V`* that get's produced, I assume that Gradle produces an unexpected feature variant name if it detects the *`version`* contains a hyphen (*`-`*). If that's the intended behavior, then should the documentation make that obvious?

**Comment by melix** [comment]
What you see is expected. The complete output has this:

```
--------------------------------------------------
Variant mongodbSupportApiElements
--------------------------------------------------
Capabilities
    - mr.jar:provider-mongodb-support:0.0.0-jdk8
```

So Gradle produces (at least) one variant with the default capability (GAV of the main component) **and** other variants (API, implementation) for the feature, with the expected capability name.

**Comment by lingocoder** [comment]
Apologies @melix,

You're absolutely right. I was being hasty again and didn't scroll down the terminal far enough. The expected feature *`G:A:V`* was actually there all along. Sorry.

Nice work on the Dependency Management Team's features and capabilities stuff for 6!  I'm looking forward to learning more :+1:

**Comment by lingocoder** [comment]
Sorry @melix,

I know you guys are busy getting the new release over the wall. But please can you help me figure out why my  *`mongodbSupportRuntimeElements`* variant...

```
--------------------------------------------------
Variant mongodbSupportRuntimeElements
--------------------------------------------------
Capabilities
    - mr.jar:provider-mongodb-support:0.0.0-jdk8

Attributes
    - org.gradle.category            = library
    - org.gradle.dependency.bundling = external
    - org.gradle.jvm.version         = 8
    - org.gradle.libraryelements     = jar
    - org.gradle.usage               = java-runtime

Artifacts
    - build\libs\provider-0.0.0-jdk8.jar (artifactType = jar)
```

...does not have the *`Secondary variants (*)`* like the default *`runtimeElements`* variant...

```
--------------------------------------------------
Variant runtimeElements
--------------------------------------------------
Description = Elements of runtime for main.

Capabilities
    - mr.jar:provider:0.0.0-jdk8 (default capability)
Attributes
    - org.gradle.category            = library
    - org.gradle.dependency.bundling = external
    - org.gradle.jvm.version         = 8
    - org.gradle.libraryelements     = jar
    - org.gradle.usage               = java-runtime

Artifacts
    - build\libs\provider-0.0.0-jdk8.jar (artifactType = jar)

Secondary variants (*)
    - Variant : classes
       - Attributes
          - org.gradle.category            = library
          - org.gradle.dependency.bundling = external
          - org.gradle.jvm.version         = 8
          - org.gradle.libraryelements     = classes
          - org.gradle.usage               = java-runtime
       - Artifacts
          - build\classes\java\main (artifactType = java-classes-directory)
    - Variant : resources
       - Attributes
          - org.gradle.category            = library
          - org.gradle.dependency.bundling = external
          - org.gradle.jvm.version         = 8
          - org.gradle.libraryelements     = resources
          - org.gradle.usage               = java-runtime
       - Artifacts
          - build\resources\main (artifactType = java-resources-directory)
```

...I searched but could not find any documentation that explains how to add secondary variants to an outgoing configuration. Does any such documentation exist? Both [*this*](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ConfigurationPublications.html#variants-org.gradle.api.Action-) and [*this*](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.Configuration.html) have me stumped. I was just on my way to search the Gradle code base for examples right before I saw your reply here.

I realize I'm probably incorrectly assuming that they should be identical. And that it would likely be a mistake to make them identical. But, I still would be interested in knowing how to add secondary variants. Just in case a real use case for it ever arises in a real project. TIA.

**Comment by lingocoder** [comment]
Eureka! [*This was very helpful*](https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/OutgoingVariantsMutationIntegrationTest.groovy#L41-L62)!


From that, I derived this...

```
...
configurations {
    mongodbSupportRuntimeElements {
        canBeConsumed = true
        canBeResolved = false
        attributes {
            attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
            attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
            attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.EXTERNAL))
            attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, Integer.parseInt( JavaVersion.VERSION_1_9.majorVersion))
        }
        outgoing {
            variants {
                classes {
                    attributes.attribute( LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.CLASSES))
                    artifact file('build/classes/java/java9')
                }
                resources {
                    attributes.attribute( LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.RESOURCES))
                    artifact file('build/resources')
                }
            }
        }
    }
}
```

...which got me pretty close to what I was after.

**Comment by ljacomet** [comment]
Interested in the use case you have that makes you need these specific variants. Could you explain it?

**Comment by lingocoder** [comment]
Hi @ljacomet . Yeah, I was just experimenting as I'm learning. 

I don't have any real world use case for those specific variants. As I was reading the docs, and studying my *`outgoingVariants`* report, I noticed that the *`runtimeElements`* had those *`Secondary Variants`* (*`classes`* and *`resources`*). Whereas my *`mongodbSupport`* one only had the one. 

So the thought just popped in my head, „*It would be a good learning exercise for me to figure out how to create secondary variants. I might need to know that one day*“. 

I find that the best way for me to learn new stuff is just by doing. So no reason for those specific variants other than that :)

By the way, why does *`runtimeElements`* have those *`Secondary Variants`*, and my custom ones don't? TIA

**Comment by ljacomet** [comment]
The secondary variants are there for specific use cases. For example on `apiElements` the `classes` one is what's used by the `java` plugin when compiling. It allows Gradle to skip JAR creation when declaring dependencies between projects.

I believe the ones on `runtimeElements` exist for symmetry. They are however available to consumers that may have specific requirements.

That's why I was interested to know if you had a specific use case making them available 😉
