### ISSUE TITLE
ResolutionStrategy#failOnVersionConflict should support dependency constraints

### ISSUE THREAD

**Issue by christopher-cudennec** [gradle/gradle#10826]
You can't use resolution strategy "failOnVersionConflict" when using dependency constraints because this feature is based on the dependency tree. Unfortunately dependency constraints are only applied after building the dependency tree.

### Expected Behavior
The build should fail if conflicting versions of dependencies are found. The build should not fail if a conflict is resolved by dependency constraints.

### Current Behavior
The build fails even if the conflict is resolved by dependency constraints.

### Context
I used the following task as a replacement:
```
/**
     * This task fails if we find an uncertain dependency that is not covered by constraints. I.e.
     * - take all constraints
     * - for each dependency
     *   - check if artifact is already covered by constraints
     *   - check if requested version of the artifact differs from the selected version
     *   -> fail
     */
    task failOnMissingConstraints {
        doLast {
            def compileConfig = project.configurations.compile
            def dependencies = compileConfig.incoming.resolutionResult.allDependencies
            def constraints = new HashMap<String, ? extends DependencyResult>()

            // println "req vs. sel"
            // dependencies.forEach { dep -> println "Req: ${dep.requested}, sel: ${dep.selected}" }
            // println ""

            dependencies.stream()
                .filter { dep -> dep.isConstraint() }
                .forEach { dep -> constraints.put("${dep.selected}", dep) }
            // println "Constraints:"
            // constraints.keySet().sort().each { println it }

            def notConvergentDeps = dependencies.stream()
                .filter { dep -> !dep.isConstraint() }
                .filter { dep -> !constraints.containsKey("${dep.selected}") }
                .filter { dep -> "${dep.requested}" != "${dep.selected}" }
                .map { dep -> "${dep.selected}" }
                .collect(Collectors.toSet())

            if (!notConvergentDeps.isEmpty()) {
                println "Dependencies that need a constraint:"
                notConvergentDeps.sort().each { println "- ${it}" }
                println "Check your dependency graph by the following tools"
                println "./gradlew :${project.name}:dependencies --configuration compile"
                notConvergentDeps.forEach {
                    println "./gradlew :${project.name}:dependencyInsight --configuration compile --dependency ${it}"
                }
                throw new GradleException("Found dependencies that is not covered by constraints: ${notConvergentDeps}")
            }
        }
    }

    compileJava.dependsOn failOnMissingConstraints
```

**Comment by ljacomet** [comment]
`failOnVersionConflict` really says to fail the build the moment more than one version is present in the graph for any dependency.

It does not care at all about the source of the version: direct dependency, transitive dependency, constraint, ...

This is why the only way to resolve a `failOnVersionConflict` issue is through substitutions of component metadata rules, that is impact the dependency _before_ it enters the graph.

If I read correctly your task, what you are looking for is all dependencies that are declared with a version X but resolve Y _without_ a constraint involved, including transitive ones.

I do not think this is a generic enough use case that it needs to become a Gradle feature.
What you are doing uses the right APIs, although it should look at `compileClasspath` instead of `compile`.

The team has been discussing providing linting for a while on dependencies. But for example, we would flag _direct_ dependencies that resolve to a version different than the declared one, not _transitive_ ones.

**Comment by christopher-cudennec** [comment]
Hi Louis,

thanks for your quick reply!

> If I read correctly your task, what you are looking for is all dependencies that are declared with a version X but resolve Y without a constraint involved, including transitive ones.

Yes, you're reading correctly. I can elaborate on the background of my feature request: We're developing a base library that is used by many services thus: The dependencies of our base library will be pulled in by many services. We want to be as sure as possible that we pass the right dependency versions and we want to be notified if we use conflicting versions especially when upgrading single dependencies.

> I do not think this is a generic enough use case that it needs to become a Gradle feature.

We moved to dependency constraints just recently to simplify dependency management loosing the `failOnVersionConflict` feature. We probably will create a Gradle plugin from the task snippet above to be able to re-use this feature. Maybe someone else is interested in it, too?

Cheers,

Christopher

**Comment by ljacomet** [comment]
Did you look into creating a `java-platform` and using that as the source of version, removing versions from build scripts?

**Comment by christopher-cudennec** [comment]
Yes, that's what we do :)

**Comment by ljacomet** [comment]
Ok 👍 
But then you should be able to keep using `failOnVersionConflict`, it should flag the same issues than before. That is conflicts in transitive dependencies.
Or am I missing something?

**Comment by christopher-cudennec** [comment]
Oh, could it be that simple? Seems you're right! Thanks! 👍 

I wonder why I was on the wrong track. Probably because I read about solving version conflicts via dependency resolution. That probably won't work because resolution is applied **after** building the dependency tree.
