### ISSUE TITLE
Isolate dependencies to Java 5 and Java 6

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1082]
Currently, many projects are limited to Java 5 and Java 6 because of the project structure. Only then entry points need to run on Java 5 to be able to give a meaningful error message. For Java 6 it is enough that we can run tests there. If we isolate the necessary classes to dedicated subprojects we can use Java 7 in more places in our code base. The same is true for the next Java version upgrade.

This also makes it possible to upgrade Guava from `guava-jdk5` to a current version.

### Expected Behavior

More Gradle subprojects can be built with Java 7.

### Current Behavior

Some Gradle subprojects have to be built with Java 5 or 6.

**Comment by wolfs** [comment]
Closed in favor of #5798.
