### ISSUE TITLE
IDE Error Message Conflicts With Gradle Command Dependency Refresh

### ISSUE THREAD

**Issue by arminnaderi** [gradle/gradle#1083]
When I click refresh Gradle project in IntelliJ IDEA it throws this error: `Error:Cause: org.gradle.internal.component.external.model.DefaultModuleComponentSelector`

I ran `./gradlew --refresh-dependencies` and it gave a 

> build successful

 message.

I have looked this issue up and the causes/solutions seem to be random.

Running Gradle wrapper version 2.13 on IntelliJ 2016.3.2

Please advise. Thanks for reading.

**Comment by bmuschko** [comment]
This sound like an issue in the IDE integration of IntelliJ to me. This [answer on Stackoverflow](http://stackoverflow.com/questions/39704047/intelij-errorcause-org-gradle-internal-component-external-model-defaultmodulec) mentions that this error might be rendered if one of your dependencies cannot be resolved. Would you mind running `./gradlew dependencies` on the command line and see if one of your dependencies is marked with `FAILED`?

**Comment by arminnaderi** [comment]
I have solved the issue by assigning every project to a Collection and then using the configure(projects) block like so:
<img width="965" alt="screen shot 2017-01-05 at 11 17 02 pm" src="https://cloud.githubusercontent.com/assets/16402451/21707433/1acc9f02-d39d-11e6-8384-e8c3ce172db1.png">

**Comment by arminnaderi** [comment]
In the past, I was using the subprojects {} block to configure all the projects. This should not have any effect in the usual case, however in this situation it did resolve the problem. I will still try to reproduce the bug and run `./gradlew dependencies.` Give me a moment.

**Comment by arminnaderi** [comment]
The error initially occurred when I added a new module to the root project with the `include` statement. Removing the module at that time resolved the problem. Since then, I have added another module on top of that. This means that I had 3 modules when the error occurred, however now I have 4 modules. Using the `subprojects {} ` block now does not reproduce the error.

Would you like me to checkout an older version of my project and try to reproduce the error?

Thanks for reading.

**Comment by bmuschko** [comment]
What does `./gradlew dependencies` say for the module that causes the issue?

**Comment by arminnaderi** [comment]
Note: At the time I added the module, it did not have any of its own dependencies, except for those inherited by the parent project.

Here you go (None are marked as FAILED within the current version of the project):

[dependencies.txt](https://github.com/gradle/gradle/files/690803/dependencies.txt)

In order to be more helpful, I will try to get the error message again and then run the command. Give me a moment.

**Comment by arminnaderi** [comment]
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':chronpwn-common:dependencies'.
> Could not resolve all dependencies for configuration 'detachedConfiguration5'.
   > Could not resolve org.springframework.boot:spring-boot-starter-thymeleaf:.
     Required by:
         com.chronpwn:chronpwn-common:2.0-SNAPSHOT
      > Failed to resolve imported Maven boms: Basedir /Users/arminnaderi/IdeaProjects/chronpwn-error-debug/chronpwn-common does not exist
   > Could not find org.springframework.boot:spring-boot-starter-test:.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-test//spring-boot-starter-test-.pom
         https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-test//spring-boot-starter-test-.jar
     Required by:
         com.chronpwn:chronpwn-common:2.0-SNAPSHOT
   > Could not find org.springframework.boot:spring-boot-starter-jdbc:.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-jdbc//spring-boot-starter-jdbc-.pom
         https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-jdbc//spring-boot-starter-jdbc-.jar
     Required by:
         com.chronpwn:chronpwn-common:2.0-SNAPSHOT
   > Could not find org.springframework.boot:spring-boot-starter-web:.
     Searched in the following locations:
         https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-web//spring-boot-starter-web-.pom
         https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-web//spring-boot-starter-web-.jar
     Required by:
         com.chronpwn:chronpwn-common:2.0-SNAPSHOT
   > Could not find com.h2database:h2:.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/h2database/h2//h2-.pom
         https://repo1.maven.org/maven2/com/h2database/h2//h2-.jar
     Required by:
         com.chronpwn:chronpwn-common:2.0-SNAPSHOT

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
`

**Comment by arminnaderi** [comment]
You are right, the dependencies for that module did fail. They seem to be unable to resolve version numbers, even though I applied the Spring-Boot plugin to all subprojects.

**Comment by arminnaderi** [comment]
```buildscript {
    ext {
        springBootVersion = '1.4.0.RELEASE'
        propDepsVersion = '0.0.7'
    }
    repositories {
        mavenCentral()
        maven { url 'http://repo.spring.io/plugins-release' }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("org.springframework.build.gradle:propdeps-plugin:${propDepsVersion}")
    }
}

allprojects {
    group 'com.chronpwn'
    version '2.0-SNAPSHOT'
}

subprojects {
    //Provides configuration options such as sourceCompatibility and targetCompatibility (Currently removed)
    apply plugin: 'java'
    //Allows for global versioning of spring boot dependencies with ${springBootVersion}
    apply plugin: 'spring-boot' }```

**Comment by bmuschko** [comment]
You'll need to figure out why the dependency doesn't resolve but that's likely your problem.

**Comment by arminnaderi** [comment]
I found the problem, but not a way to resolve it. Here is what I noticed to be of interest when running with `-i`:

```
Resolving global dependency management for project 'chronpwn-common'
Using version '3.0.0.RELEASE' for dependency 'org.thymeleaf.extras:thymeleaf-extras-springsecurity4:3.0.0.RELEASE'
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-test//spring-boot-starter-test-.pom]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-test//spring-boot-starter-test-.jar]
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-jdbc//spring-boot-starter-jdbc-.pom]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-jdbc//spring-boot-starter-jdbc-.jar]
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-web//spring-boot-starter-web-.pom]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-web//spring-boot-starter-web-.jar]
Using version '8.0.32' for dependency 'org.apache.tomcat:tomcat-dbcp:8.0.32'
Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/h2database/h2//h2-.pom]
Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/com/h2database/h2//h2-.jar]
:chronpwn-common:dependencies FAILED
:chronpwn-common:dependencies (Thread[main,5,main]) completed. Took 4.271 secs.

FAILURE: Build failed with an exception.
```

**Comment by oehme** [comment]
There is no difference between using `subprojects {}` or `configure(someListOfProjects)`. If you are still facing this issue, please attach a zipped up example project.
