### ISSUE TITLE
Maven POM resolution leads to StackOverflowError if parent GAVs reference resolved POM GAVs

### ISSUE THREAD

**Issue by parthbhagat** [gradle/gradle#1084]
Opening this issue with reference of JIRA issue: https://issues.gradle.org/browse/GRADLE-3485

I am currently facing same issue as mentioned in https://discuss.gradle.org/t/failure-to-resolve-dependency-but-artifact-exists/17977/5

I am trying to build grails 2.3.11 from git repository to my local machine with additional logging statements. But due to above error I am not able to build grails distribution files.

I guess this issue is been reproduce with all the cases with:

- Group: org.springframework.uaa
- Artefact: org.springframework.uaa.client
- Version: 1.0.1.RELEASE/1.0.2.RELEASE

I am not sure whether this issue is gradle issue or POM issue (I have recently migrated my project to Ant to Gradle, so having little knowledge of Gradle). By reading at gradle discussion forum (link mentioned above), I am posting issue here.

**Comment by bmuschko** [comment]
@parthbhagat Could you please add the description of the JIRA ticket here as well?

**Comment by parthbhagat** [comment]
From grails-bootstrap progject, gradle dependency for spring uaa client:
```
uaa("org.springframework.uaa:org.springframework.uaa.client:1.0.2.RELEASE") {
	["protobuf-java-lite", "json-simple", "bcpg-jdk15", "bcprov-jdk15"].each { dep ->
		exclude group: "org.springframework.roo.wrapping", module: "org.springframework.roo.wrapping." + dep
	}
}
```

This results in following dependency resolution error.

```
Could not resolve org.springframework.uaa:org.springframework.uaa.client:1.0.1.RELEASE.
     Required by:
         org.grails:grails-bootstrap:2.3.11
      > Could not parse POM http://repo.grails.org/grails/core/org/springframework/uaa/org.springframework.uaa.client/1.0.1.RELEASE/org.springframework.uaa.client-1.0.1.RELEASE.pom
```
	  
This error is been thrown recursively and eventually yield to _java.lang.StackOverflowError_.
