### ISSUE TITLE
project dependencies in a multi module project inherit default which relies on deprecated compile

### ISSUE THREAD

**Issue by aburmeis** [gradle/gradle#10842]
If I setup a multi module java project (let's say module A and B), I can make one module depend on another one using a build setup similar to:

Module **A**:
```
apply plugin: 'java'

dependencies {
  implementation 'test.com:my-dep:1.0'
}
```

Module **B**:
```
apply plugin: 'java'

dependencies {
  implementation project(':A')
}
```

This works file for dependencies I configured for _compile_ in module A but dependencies configured for _implementation_ are not exposed. This is according to the documentation, which tells me _default_ extends _runtime_ and _runtime_ extends _compile_.

But runtime and compile are deprecated and you should use _implementation_ or _runtimeOnly_ instead. But if you do so, the module you depend on seems to have to dependencies as only the _default_ is exposed which does not contain _implementation_ e.g.

The setup above should make module B depend on `'test.com:my-dep:1.0'` but currently (gradle 6.5.2) does not. It only works if I replace _implementation_ by _compile_ in module A.

**Comment by ljacomet** [comment]
Closing as no work needed here.

**Comment by aburmeis** [comment]
Ok, thanks for clarification. I like the more clear concept of java-library and for a new project that is pretty fine. Migrating a larger multi module project may become somehow hard as you have to either stick with the old compile deprecated compile dependencies (for how long?) or change most of your modules to java-library and adjust all their dependencies to the new api/implementation approach. But ok, I have to go that way anyway.

**Comment by chrisinmtown** [comment]
Would you all please consider adding the example build.gradle files for modules A and B, for poor newbs like me who land here via google?  Seems that gradle has changed all kinds of things, like deprecating "compile", and most of the blog and other posts out there still confidently demonstrate how to declare dependencies that way.  This discussion at least hints of the new way but an example would be worth 1K words.  Thanks in advance.
