### ISSUE TITLE
Investigate impact of failing on duplicates in JARs by default

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#10856]
The change in https://github.com/gradle/gradle/pull/10143 affects the shadow plugin and we had reports of other build failures without a deprecation warning in earlier releases.

See https://github.com/johnrengelman/shadow/pull/517 for the PR to "fix" the shadow plugin.

**Comment by wolfs** [comment]
So the shadow plugin handles the merging of duplicate resources in its copy action: https://github.com/johnrengelman/shadow/blob/master/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/ShadowCopyAction.groovy#L111-L113

The duplicates check built into Gradle happens before the files are passed to the copy/zip action: https://github.com/gradle/gradle/blob/4f852e77369a441b5af30ec321918c06fcb3f0fa/subprojects/core/src/main/java/org/gradle/api/internal/file/copy/CopyActionExecuter.java#L35-L40

That means that the deprecation warning is triggered even though the final JAR doesn't contain duplicates since they are merged.

**Comment by rpalcolea** [comment]
I wouldn't even call https://github.com/johnrengelman/shadow/pull/517 a fix :). For me was more to just force the old behavior back. 

I think it would be great if Gradle could act after `ShadowCopyAction` for example.

However, this appears to be the behavior, just got exposed by making `FAIL` as the default. Maybe some underlying change needs to happen in Gradle before introducing the `FAIL` as default? I guess a deprecation warning and then making it default in 7.0 should be sufficient from customer perspective?

**Comment by wolfs** [comment]
> However, this appears to be the behavior, just got exposed by making `FAIL` as the default. Maybe some underlying change needs to happen in Gradle before introducing the `FAIL` as default? I guess a deprecation warning and then making it default in 7.0 should be sufficient from customer perspective?

Yeah, that is what we are going to do: Emit a deprecation warning and change the default to `FAIL` in `7.0`: https://github.com/gradle/gradle/pull/10865

**Comment by lptr** [comment]
We'll also need to turn the checks around somehow, so the Shadow plugin can do its thing. Or add some public API to allow declaring file merges in some form explicitly.

**Comment by wolfs** [comment]
We don't need to turn the checks around, the `Shadow` plugin can do its own checks and set the duplicates strategy to `INCLUDE`. Given that the shadow plugin does all the archive writing itself, I don't see where the check should be placed.

**Comment by lptr** [comment]
I don't really like it. I mean, it works as a workaround, but it hijacks the duplicate strategy property. And the Shadow plugin heavily depends on internal APIs. This would be a good opportunity to fix that, too.

**Comment by wolfs** [comment]
We now only emit a deprecation warning for duplicates in 6.0: https://github.com/gradle/gradle/pull/10865

We emit the deprecation warnings for copy tasks as well, though.

The current plan is to fail on duplicates by default in Gradle 7.0: #10039.

It would be great if the shadow plugin could be implemented on top of Gradle's public API (https://github.com/gradle/gradle/issues/10891). There seems to be some work necessary on the Gradle side as well.

**Comment by rpalcolea** [comment]
Thanks folks!
