### ISSUE TITLE
Clean up Gradle caches periodically

### ISSUE THREAD

**Issue by sergeykad** [gradle/gradle#1085]
Gradle cache folder does not have eviction policy and can take all disk space. It is especially problematic if using many large changing modules as dependencies.

### Expected Behavior
Gradle should provide a way to cleanup old cached SNAPSHOT dependencies. 
For example it can be configurable how many old snapshots to keep. Other solution can be to delete dependencies that are not used for a set period of time.

### Current Behavior
Currently files from Gradle cache are never deleted

### Context
With time cache takes all available disk space, especially on build servers.

See the original issue on https://issues.gradle.org/browse/GRADLE-2267

**Comment by bmuschko** [comment]
@sergeykad Thanks for creating the GitHub issue. Before jumping to implementation details let's start creating a [design document](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md#larger-changes-features-or-enhancements) for this feature. Would you be interested in contributing it?

**Comment by sergeykad** [comment]
@bmuschko Unfortunately my knowledge of Gradle is not sufficient for this task.
Also link to design document is broken.

**Comment by torstenwerner** [comment]
Another option would be to allow the removal of cached artifacts using external tools (e.g. running _find ... -atime ... | xargs rm_ regularly). Gradle should just re-download such missing artifacts.

**Comment by mkobit** [comment]
This would also be useful on cloud CI systems that allow you to do dependency caching.

For example, let's say you do the following pattern:
* Restore the most recent Gradle home with wrapper and dependency caches
* Change the Gradle version, dependency versions, or anything else that gets accumulated in Gradle home
* New things get added to Gradle home (old things are still there)
* Save new cache

You will keep accumulating objects until you purge the directory yourself.

**Comment by upcrob** [comment]
I've put together a prototype of what this could look like here: https://github.com/gradle/gradle/compare/master...upcrob:cleancache

Basically, this adds a command line option ("--cleancache" or "-C") that recursively removes all directories under the Gradle cache's 'modules-2' directory if the directory doesn't have any subdirectories (after recursing into them) and if all of the contained files are older than the specified number of days.  In testing this seemed to work, but could very easily be an overly naive solution as I don't have any knowledge as to the internal structure of the cache.

This patch isn't ready to be merged for a number of reasons, most notably due to the fact that it doesn't yet contain any unit tests.  However, if the above is an approach that both meets the rest of the community's requirements and doesn't break any Gradle internals, I can probably turn it into a valid PR.

**Comment by marcphilipp** [comment]
@upcrob Thanks for spiking this on your branch! However, we need to make sure to only clean caches that are currently not in use. Thus, at least for the shared caches (like `modules-*`), we should follow the same strategy that's used by the build cache, namely cleaning up the cache when closing it.

Thus, I propose the following strategy for the shared caches like `modules`, `jar` and `transforms`: Remove entries from the cache that have not been accessed for a given period. The period should be configurable using a property, e.g. `org.gradle.caching.cleanupperiod`, with a sensible default, e.g. 7 days.

@gradle/dependency-management @gradle/build-cache @oehme What do you think?

**Comment by oehme** [comment]
Sounds good to me. We may want to provide different periods for the two main categories of caches:

- caches that store something you can easily recreate (e.g. transforms, task outputs etc)
- caches that store something that's external (e.g. dependencies, gradle distributions)

The latter probably deserves a higher default setting than the former. Imagine you go on a week of vacation and having to redownload the internet upon return :)

**Comment by melix** [comment]
+1 to what @oehme said. I maintain several OSS projects and it's not unusual for me to reopen a project once in weeks, if not months. Something like 3 months would be more reasonable for external dependencies IMO. Note that we could have a lighter policy for dependencies which are `-SNAPSHOT`.

**Comment by marcphilipp** [comment]
So, a config property per cache?

- `org.gradle.caching.cleanupperiod.modules`
- `org.gradle.caching.cleanupperiod.jar`
- `org.gradle.caching.cleanupperiod.transforms`

Or some categorization?

- `org.gradle.caching.cleanupperiod.recreatable`
- `org.gradle.caching.cleanupperiod.external`

@oehme @melix Which one would you prefer? Or, do you have other ideas?

**Comment by oehme** [comment]
The latter I think.

**Comment by upcrob** [comment]
My historical use case for making this configurable would be to help clean up shared/non-shared build server caches (as opposed to local development). Even if things end up getting re-downloaded semi-regularly, you frequently have some sort of “local” caching mechanism (e.g. Artifactory). Running a cache cleanup task (nightly, for example) on build nodes would help keep them somewhat clean and help prevent from running low on space (I’ve worked in environments where this has been an issue, for better or worse).

**Comment by marcphilipp** [comment]
The intended use of these configuration options is to put them into the `gradle.properties` in the user's Gradle home directory, not the project directory. The latter would indeed lead to a somewhat strange behavior but as it would not really be harmful, I think we can live with that.

For the properties, I'm wondering whether we should be using the `org.gradle.caching` "namespace" which is currently used for the build cache. We could either generalize it and use these properties also for the build cache (unless it is configured explicitly using [its DSL](https://docs.gradle.org/current/dsl/org.gradle.caching.local.DirectoryBuildCache.html#org.gradle.caching.local.DirectoryBuildCache:removeUnusedEntriesAfterDays)) or use a different namespace that's specific to dependency management, e.g. `org.gradle.dependencymanagement.caching.cleanupperiod.external`.

@gradle/build-cache Thoughts?

**Comment by lptr** [comment]
Until we actually use the same infrastructure for dependency management caching and build cache, I think a separate namespace like the one you suggested makes a lot of sense.

**Comment by marcphilipp** [comment]
Cache cleanup for `GRADLE_USER_HOME` is now performed in the background when the Gradle daemon is stopped or shuts down. If using `--no-daemon`, it runs in the foreground after the build session with a visual progress indicator. The following cleanup strategies are applied:

- Version-specific cache directories in `GRADLE_USER_HOME/caches/<gradle-version>/` are checked periodically (at most every 24 hours) for whether they are still in use. If not, directories for release versions are deleted after 30 days of inactivity, snapshot versions after 7 days of inactivity.
- Shared versioned cache directories in `GRADLE_USER_HOME/caches/` (e.g. `jars-*`) are checked periodically (at most every 24 hours) for whether they are still in use. If there's no Gradle version that still uses them, they are deleted.
- Files in shared caches used by the current Gradle version in `GRADLE_USER_HOME/caches/` (e.g. `jars-3` or `modules-2`) are checked periodically (at most every 24 hours) for when they were last accessed. Depending on whether the file can be recreated locally or would have to be downloaded from a remote repository again, it will be deleted after 7 or 30 days of not being accessed, respectively.
- Gradle distributions in `GRADLE_USER_HOME/wrapper/dists/` are checked periodically (at most every 24 hours) for whether they are still in use, i.e. whether there's a corresponding version-specific cache directory. Unused distributions are deleted.

In addition, after building a project, version-specific cache directories in `PROJECT_DIR/.gradle/<gradle-version>/` are checked periodically (at most every 24 hours) for whether they are still in use. They are deleted if they haven't been used for 7 days.

**Comment by felipecsl** [comment]
@marcphilipp thanks! has that been released already or it's for next version?

**Comment by SUPERCILEX** [comment]
@felipecsl It's in 4.10-rc-1: https://docs.gradle.org/4.10-rc-1/release-notes.html#periodic-cache-cleanup

**Comment by wszeboreq** [comment]
Are there any secret or official properties for tuning the configured inactivity numbers of days?

**Comment by marcphilipp** [comment]
No, there's currently no property to configure the cache retention time. Is 7/30 too much or too little for you?

**Comment by wszeboreq** [comment]
It is too much, I'm running into disk space problems. But I think my case is not typical - we have some dependencies in form of binary zip archives (e.g. 1 GB size) and it seems to cause '.gradle/caches/modules-2/files-2.1' grow each day bigger and bigger. For now I worked around the issue by moving entire gradle home dir on this worker machine, but ability to lower the 30 days retention time would be useful.

**Comment by marcphilipp** [comment]
Could you please create a new issue for it?

**Comment by wszeboreq** [comment]
OK, I filed https://github.com/gradle/gradle/issues/7018 for it.

**Comment by bysiber** [comment]
Gradle cache cleanup is a recurring need, especially for teams doing Android development on macOS where `~/.gradle/` can easily reach 10-50GB.

**Audit what's consuming space:**

```bash
# Total Gradle home size
du -sh ~/.gradle/

# Break it down
du -sh ~/.gradle/caches/
du -sh ~/.gradle/wrapper/dists/
du -sh ~/.gradle/daemon/
du -sh ~/.gradle/native/
```

**Safe cleanup approach:**

```bash
# Stop daemons first
gradle --stop 2>/dev/null || true

# Remove caches older than 30 days
find ~/.gradle/caches -maxdepth 1 -type d -mtime +30 -exec rm -rf {} +

# Remove old wrapper distributions (keep latest)
ls -t ~/.gradle/wrapper/dists/ | tail -n +2 | xargs -I{} rm -rf ~/.gradle/wrapper/dists/{}

# Clean daemon logs
rm -rf ~/.gradle/daemon/

# Remove build caches in projects
find ~/Projects -name "build" -type d -path "*/build" -maxdepth 4 \
  -exec test -f "{}/../build.gradle" \; -print
```

The periodic cleanup feature added in Gradle 8+ (30-day retention) helps, but only for `caches/` -- it doesn't touch wrapper distributions, daemon data, or project `build/` directories which often account for a significant portion of the disk usage.

On macOS, Gradle is typically just one of many developer cache consumers. Combined, these often reach 50-100GB:
- `~/.gradle/` (2-50GB)
- Xcode DerivedData (5-40GB)
- Docker images (10-60GB)
- node_modules across projects (5-30GB)
- Homebrew bottles (2-15GB)

[ClearDisk](https://github.com/bysiber/cleardisk) (free, open-source, macOS native) scans all of these at once and shows the full breakdown. Useful for getting a quick picture of where your disk space went.

**Comment by marcphilipp** [comment]
> it doesn't touch wrapper distributions

It should delete those as well (as documented): https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:cache_cleanup

**Comment by bysiber** [comment]
@marcphilipp ah right, missed that part of the docs. thanks for the correction.
