### ISSUE TITLE
Are Kotlin lambdas supported as incremental task actions?

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#10854]
Are Kotlin lambdas supported as incremental task actions?

In the following comment (from https://github.com/gradle/gradle/issues/5510#issuecomment-419478300), @wolfs said:

> @mockitoguy Adding a `doLast` action in a build script will not disable caching/incremental build for the task. Only when the `doLast` action is implemented via a Java lambda. Groovy and Kotlin lambdas work just fine.

Is this still correct for the following versions of relevant software:

- Gradle Wrapper 5.6.2 Kotlin DSL
- Kotlin 1.3.50
- Java 13: OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
- macOS 10.14.6 + all updates

I got warnings containing `Using Java lambdas is not supported` when using my plugin, which is implemented completely in Kotlin, and which uses lambdas as arguments to `doFirst()` & `doLast()`.

I included the source for that plugin in a composite build, and applied that plugin to another included build, `:common`. When I run:

```
./gradlew --info --warning-mode all --console=plain build
```

It outputs the following to the console:

```
> Task :common:compileJava
Caching disabled for task ':common:compileJava' because:
  Build cache is disabled
Task ':common:compileJava' is not up-to-date because:
  Additional action for task ':common:compileJava': was implemented by the Java lambda 'org.gradle.java.taskconfigurer.JavaCompileTaskConfigurer$$Lambda$1406/0x0000000801ffb440'. Using Java lambdas is not supported, use an (anonymous) inner class instead.
All input files are considered out-of-date for incremental task ':common:compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
Created classpath snapshot for incremental compilation in 0.035 secs.
:common:compileJava (Thread[Execution worker for ':common',5,main]) completed. Took 1.773 secs.
```

`org.gradle.java.taskconfigurer.JavaCompileTaskConfigurer` is implemented in Kotlin (as are all the other classes in the plugin), so I don't know why Gradle thinks I'm using a Java lambda.

I thought that maybe using the `1.6` value for the `-jvm-target` option for `kotlinc` might translate Kotlin lambdas to anonymous inner classes, and maybe using `8` or higher might translate to Java lambdas, but downgrading from `9` to `1.6` still results in the same outputs about Java lambdas.  That seems odd, as Java 6 doesn't support lambdas.

Maybe older versions of Kotlin translate Kotlin lambdas into anonymous inner classes, but newer versions of Kotlin translate Kotlin lambdas into java lambdas.

With the following in my `build.gradle.kts` for the plugin:

```
tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions {
        javaParameters = true
        jvmTarget      = VERSION_1_9.majorVersion
        verbose        = true
    }
}
```

**Comment by wolfs** [comment]
@rgoldberg Thank you for reporting. I tried reproducing your issue by creating a task in `buildSrc` with an lambda as an action in Kotlin, though I didn't get your warning. Do you think you can come up with a simple reproducer, so I can take a look?

That is what I did:
```
open class MyPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        val myTask by target.tasks.registering {
            outputs.file("build/output.txt")
            outputs.cacheIf { true }
            doLast {
                println("Hello")
                target.file("build/output.txt").writeText("Ready")
            }
        }
    }
}
```

**Comment by rgoldberg** [comment]
@wolfs This issue is spurious; the lambda warnings were caused because a different Gradle bug caused my composite build to apply the old Java version of my plugin from the Gradle Plugin Portal instead of the Kotlin version that was included as a build in the same composite build.

Once I isolated the other bug and worked around, the Kotlin lambdas were used, and work just fine.

Sorry for the confusion.

I'll open another issue for the other bug either later today or next week.
