### ISSUE TITLE
Wrong information on default value for destinationDir on https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:destinationDir

### ISSUE THREAD

**Issue by oveits** [gradle/gradle#1086]
The Jar documentation on https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:destinationDir has wrong information on the default value of destinationDir, pointing to 'build/distributions' instead of 'build/libs'.

### Expected Behavior

I think, https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:destinationDir should specify following default value for the File destinationDir:

> File destinationDir
> 
> The directory where the archive is generated into.
>
> Default with java plugin:
>
> project.libsDir

where default of libsDir is 'build/libs' as can be seen [here](https://docs.gradle.org/current/userguide/java_plugin.html#sec:jar).

### Current Behavior

In the moment, I think, https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:destinationDir is specifying following default value for the File destinationDir:

> File destinationDir
> 
> The directory where the archive is generated into.
>
> Default with java plugin:
>
> project.distsDir

where default of distsDir is 'build/distributions' as can be seen [here again](https://docs.gradle.org/current/userguide/java_plugin.html#sec:jar).

### Context

N/A

### Steps to Reproduce (for bugs)

N/A

### Your Environment

 * Build scan URL: 
N/A

**Comment by bmuschko** [comment]
You are correct. The docs use the wrong value here. Would you be interested in contributing the fix?

**Comment by oveits** [comment]
Yes, I am willing to contribute, but I do not know, where to find the location of the error. I have scanned the source code for the pattern, but I could not find it. This is, why I was forced to create an issue instead of a pull request. Can you give me a hint?

**Comment by wolfs** [comment]
@oveits The location of the documentation is here: https://github.com/gradle/gradle/blob/cc389874c09f9f300f6468d341801e38374433c2/subprojects/docs/src/docs/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.xml#L41-L41

**Comment by oveits** [comment]
Hi @wolfs: I can see the ```project.distsDir```, but I never could have found it, since there is no string like "File destinationDir" there. I will patch it online and send a pull request.
