### ISSUE TITLE
Document ArtifactView API

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#10867]
This could be included in `artifact_transforms.adoc`.

**Comment by ljacomet** [comment]
This also should cover how to get to the metadata files for custom processing.
It should replace of supplement https://docs.gradle.org/5.6.3/userguide/working_with_dependencies.html#accessing_a_modules_metadata_file in order to answer the use case of #11449

**Comment by lkasso** [comment]
Closing as duplicate of https://github.com/gradle/gradle/issues/26007
