### ISSUE TITLE
Publishing Maven BOM without scope information

### ISSUE THREAD

**Issue by bclozel** [gradle/gradle#10878]
When publishing a Maven POM using the Java Platform plugin, Maven dependencies declared in the dependencyManagement section all have a `<scope>` tag. In many cases, this can cause issues with Maven consumers and it would be helpful to know a way to disable this behavior.

### Expected Behavior
When publishing Maven POMs, depending on the use case, we might not want to publish scope information for the dependencies published in the dependencyManagement section.
I'm looking for a way to not publish the scope information for those.

### Current Behavior
When using a build like the following:
```groovy
dependencies {
	constraints {
		api project('spring-core')
		api project('spring-web')
		//...
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = 'spring-framework-bom'
			from components.javaPlatform
		}
	}
}
```

The published BOM will look like:

```xml
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-core</artifactId>
        <version>5.2.0.BUILD-SNAPSHOT</version>
        <scope>compile</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-web</artifactId>
        <version>5.2.0.BUILD-SNAPSHOT</version>
        <scope>compile</scope>
      </dependency>
```

### Context

The Maven documentation is not always clear about BOMs vs. parent POMs and how dependency management and scopes play a part, so I'll try and use a concrete example.

If the Spring Framework project publishes its BOM with the `<scope>` information (for the sake of the example, let's pretend everything is published as `compile`), then this is the scope that will be enforced if no other scope is provided by the consumer.

Then if a Spring Boot application adds a `spring-boot-starter-test` with a `test` scope, then all transitive dependencies ("spring-test", "spring-core"...) will be on the `compile` scope of the application.

So in the case of BOMs that are publicly available and that do not express an opinion about how to consume dependencies (such as the Spring Framework BOM), having the scope information is creating issues.

So far, I've worked around this issue with the following:

```groovy
publishing {
	publications {
		mavenJava(MavenPublication) {
			artifactId = 'spring-framework-bom'
			from components.javaPlatform
			// remove scope information from published BOM
			pom.withXml {
				asNode().dependencyManagement.first().dependencies.first().each {
					it.remove(it.scope.first())
				}
			}
		}
	}
}
```

Is there a better way to achieve this?
Looking at Gradle's source, it seems that adding dependencies to the dependency management section of a POM requires a specific scope.

**Comment by ljacomet** [comment]
Thanks for the report, I did reproduce the issue.

Weird that I never noticed that before, either as a Maven user in the past or when we did the prototype and tried that feature.

Looking into what can be done, most likely in the `java-platform` plugin for handling this properly.

**Comment by ljacomet** [comment]
After some further discussions and testing, Gradle just has no reason to attempt publishing a `scope` to anything it generates in `dependencyManagement`.

**Comment by ljacomet** [comment]
To be clearer, the difference between Maven and Gradle here is that:
* For Maven, the `scope` of a `dependencyManagement` entry _changes_ the scope of a transitive dependency, potentially promoting a `test` dependency to `compile` as reported
* For Gradle, the configuration to which a `constraint` is attached indicates in which _context_ the `constraint` will be applied to dependencies.

This fundamental difference means that Gradle should make no attempt to express the potential reduced scope of a constraint for the Maven world.

**Comment by snicoll** [comment]
@ljacomet seems fair to me, thank you very much for looking at this so quickly.

**Comment by ljacomet** [comment]
Note that the workaround needs to be amended to not strip a `<scope>import</scope>` if you import other BOMs as Gradle `platform` dependencies in the project that publishes the BOM, as this will break the Maven side.

Though that does not seem to be the case of the `spring-framework-bom` but is the case for `spring-boot-dependencies` with the `jackson` BOM for example.
