### ISSUE TITLE
gradle degrade the jar version

### ISSUE THREAD

**Issue by liaomengge** [gradle/gradle#10881]
i use dependency-management and define the lombok version 1.18.10, for below:
```
dependencyManagement {
    dependencies {
        dependency "org.projectlombok:lombok:1.18.10"
```
and the use 
```
compileOnly "org.projectlombok:lombok"
annotationProcessor "org.projectlombok:lombok"
```

but use ` gradle dependencyInsight --dependency lombok ` show below:
```
org.projectlombok:lombok:1.16.22 (selected by rule)
   variant "runtime" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]

org.projectlombok:lombok:1.18.10 -> 1.16.22
```
I'm bewildered, why the gradle choose degrade lombok 1.16.22, not the upgrade version 1.18.10.

**Comment by ljacomet** [comment]
The answer lies in the header of the output: `selected by rule`
This indicates that a substitution rule is in place which seems to force the version of `lombok` to `1.16.22`.
You need to figure out where in your build this rule is added, either a build script or an applied plugin.

**Comment by liaomengge** [comment]
> The answer lies in the header of the output: `selected by rule`
> This indicates that a substitution rule is in place which seems to force the version of `lombok` to `1.16.22`.
> You need to figure out where in your build this rule is added, either a build script or an applied plugin.

how can i found where the substitution rule. i print the dependencies compileClass or other handle, but i don't kone where is replace by 1.16.22. could't you give me small suggest.

**Comment by liaomengge** [comment]
> The answer lies in the header of the output: `selected by rule`
> This indicates that a substitution rule is in place which seems to force the version of `lombok` to `1.16.22`.
> You need to figure out where in your build this rule is added, either a build script or an applied plugin.

yeah, i found the buildscript for below:
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.springframework.boot:spring-boot-gradle-plugin:2.1.8.RELEASE"
  }
}
```
when i use the plugin `spring-boot-gradle-plugin`,then the dependencies will be import, but i don't need the jar.

**Comment by ljacomet** [comment]
So this means the forced version comes from the Spring dependency management plugin.
Have a look at [its documentation](https://docs.spring.io/dependency-management-plugin/docs/current-SNAPSHOT/reference/html/) as it explains how to override versions coming from the BOM.
