### ISSUE TITLE
build android library with two or more local aar libs failed at version 3.5.0

### ISSUE THREAD

**Issue by kawais** [gradle/gradle#10882]
### Expected Behavior

build android library with two or more local aar libs success in AS

### Current Behavior

build failed

### Context

I want build the library to aar for other project, but build failed.

### Steps to Reproduce 

when run command:  gradlew mylibrary:build

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mylibrary:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'classes.jar'

example project:  https://github.com/kawais/testapp

### Your Environment

android stuido 3.5  
windows 10

**Comment by samuelneff** [comment]
I ran into the same issue with an internal component and resolved by downgrading Gradle to 3.4.2. This issue still persists in Gradle 3.5.2.

**Comment by zabojad** [comment]
Hi there, any solution found for this problem?

**Comment by mzennis** [comment]
this problem still occurred in Gradle 3.5.3

**Comment by friederbluemle** [comment]
> this problem still occurred in Gradle 3.5.3

That's correct. If you want to "fix" it by downgrading, try using `3.4.3`.

**Comment by mzennis** [comment]
I couldn't downgrade the Gradle version, I fixed it by uploading the aar's to internal artifactory

**Comment by friederbluemle** [comment]
> I couldn't downgrade the Gradle version, I fixed it by uploading the aar's to internal artifactory

Interesting.. Can you share some details which files you uploaded?

**Comment by zabojad** [comment]
@mzennis could you please describe how you did this:

> I fixed it by uploading the aar's to internal artifactory

**Comment by zabojad** [comment]
OK, here is a little update from my side on this issue. I'm using React native and latest versions of RN 0.63 uses gradle plugin 3.5.3 by default.

I tried to update to gradle plugin 3.6.4 and it seems to work, solving by the way this issue with aar files.

Hope this will help someone.

**Comment by ColdLight230** [comment]
packagingOptions {
        merge "classes.jar"
}

**Comment by ColdLight230** [comment]
I fixed it by add this code in module bulid.gradle

**Comment by mzennis** [comment]
> > I couldn't downgrade the Gradle version, I fixed it by uploading the aar's to internal artifactory
> 
> Interesting.. Can you share some details which files you uploaded?

I uploaded the aar library file that was previously local to the internal repository.

before:
`implementation files('libs/mylibrary.aar')`

now:
`implementation 'com.xxx.xxx:mylibrary:1.0@aar'`

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
