### ISSUE TITLE
upgrading gradle from 2.14 to 5.6 made artifactory publish stop working

### ISSUE THREAD

**Issue by webshammo** [gradle/gradle#10888]
### Expected Behavior
jars and build info should be published to artifactory

### Current Behavior
only build info is published to artifactory.  jars somehow never make it to artifactoryDeploy

### Context
I upgraded gradle and jfrog plugin (from "org.jfrog.buildinfo',                 name: 'build-info-extractor-gradle', version: '3.1.2" to 'org.jfrog.buildinfo',   name: 'build-info-extractor-gradle', version: '4.9.10'")
There was suprisingly little else to edit, and builds worked.  I put them up into jenkins to release and the build succeeds, but only the build info publishes and the jars do not.

### Steps to Reproduce 
attached my build.gradle

### Your Environment
Attached output from build on jenkins.

[build.gradle.txt](https://github.com/gradle/gradle/files/3659772/build.gradle.txt)
[build.output.txt](https://github.com/gradle/gradle/files/3659800/build.output.txt)

**Comment by ljacomet** [comment]
2.14 to 5.6 is a serious update. I would recommend making sure you no longer have any deprecation warnings and looking at the [4.x to 5 migration notes](https://docs.gradle.org/5.6.2/userguide/upgrading_version_4.html) in detail

**Comment by webshammo** [comment]
I read all that, and no deprecation warnings.   Sample attached.  I cannot figure out where I have something wrong, if I do.
