### ISSUE TITLE
When 'clean' depends on another task, it can happen in the middle of a build, breaking it

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#10889]
### Expected Behavior

Build should not fail.

### Current Behavior

Build fails.

### Context

Because of this issue, I have to run `./gradlew clean && ./gradlew build assembleAndroidTest` instead of a single gradle invocation.

### Steps to Reproduce 

1. `git clone git@github.com:square/leakcanary.git`
2. `./gradlew clean build assembleAndroidTest`

It is possible to make this build succeed by either:
1. Removing `tasks.getByName('clean').dependsOn installGitHooks` from the root `build.gradle` or
2. Adding the following to the root `build.gradle`
```
    def deleteTasks = project.tasks.withType(Delete)
    project.tasks.configureEach { Task task ->
      if (!(task instanceof Delete)) {
        task.mustRunAfter(deleteTasks)
      }
    }
```

### Environment
Nothing special. This is not even my project and I was able to reproduce on my local machine with the repro steps provided above.

**Comment by Armaxis** [comment]
Link to [`build.gradle` file commit](https://github.com/square/leakcanary/commit/2af976fca0d939e46b00310555ad3fad39734fc7#diff-c197962302397baf3a4cc36463dce5ea) where dependency was added for the `clean` task. We will most likely remove that dependency.

**Comment by lacasseio** [comment]
This is still a problem and should not be closed.
