### ISSUE TITLE
how to manage external dependencies and their versions in a separate properties files?

### ISSUE THREAD

**Issue by venkataraghu** [gradle/gradle#1089]
I am currently using gradle 2.11 version and i was able to successfully manage my external dependencies and their version in a separate properties file like dependencies.properties file using a gradle plugin MyDepNamesPlugin from https://github.com/RobertFischer/gradle-plugins 

 Is there any way i can manage my external deps and their versions in a separate file outside my build.gradle file in current version of gradle 3.3?

**Comment by bmuschko** [comment]
Yes, you can store the version for dependencies or the list of dependency coordinates anywhere you want. There are no real limitations as you have a programming language at hand. However, it's up to your custom code in the build script. For example you could externalize the versions into a properties file and then read it from Gradle as you would in Java.

Here's an example:

```
// read dependency coordinates
ext.deps = readDependencies(file('deps.properties'))

Properties readDependencies(File dependencyDefinitions) {
    if (!dependencyDefinitions.exists()) {
        throw new GradleException("Required dependency file does not exist: $dependencyDefinitions.canonicalPath")
    }

    Properties depProps = new Properties()

    dependencyDefinitions.withInputStream { stream ->
        depProps.load(stream)
    }

    depProps
}

// use dependency coordinates
dependencies {
    // iterate over properties and declare dependencies
}
```

Gradle does not have a built-in mechanism for this handling. I am going to close the issue as there's no concrete answer I could point you to in the Gradle documentation. It's up to your own definition.

**Comment by venkataraghu** [comment]
Thank you very much. i am using  a similar solution.  This solved my issue.
