### ISSUE TITLE
For `spring-boot-gradle-plugin plugin`, the springboot dependencies will be import

### ISSUE THREAD

**Issue by liaomengge** [gradle/gradle#10894]
when i use `spring-boot-gradle-plugin`, then my project will import `org.springframework.boot:spring-boot-dependencies:1.5.x.RELEASE` dependencies, but i don't need the dependencies for me, because i have my own bom to manager my jar, so some jar will be conflict, and the gradle choose the rule of jar may be `spring-boot-gradle-plugin`'s dependencies.so this is not what I expected, but i need use bootRepackage/bootJar, how can i solve the problem?

**Comment by ljacomet** [comment]
This is a feature of the Spring Boot plugin: https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#managing-dependencies

I recommend looking at their documentation to see if you can opt-out.
But this is not something Gradle core can solve for you.
