### ISSUE TITLE
JavaDoc header and footer can’t handle single quote characters

### ISSUE THREAD

**Issue by lessthanoptimal** [gradle/gradle#1090]
This is an old and long since unresolved bug report.  Inside a Javadoc task the following option should be valid:

`bottom = "TESTBOTTOM 'inside'"`

This is perfectly legal for JavaDoc (please see previous issue linked below) but the bug has to deal with how Gradle handles text strings.  Gradle will generate invalid code and fail.  Similar bug reports were submitted in the past but only a partially fix was created. My current work around is still to use Ant to create javadoc.

Old partially resolved issue:
[GRADLE-3099](https://issues.gradle.org/browse/GRADLE-3099)

### Misc
I've also created a $75 bounty for getting this issue resolved.  See [BoofCV's Bounty](http://boofcv.org/index.php?title=Bounties)  page

### Test Environments
* Gradle 3.2, openjdk version "1.8.0_111"
* Gradle 2.9 , jdk1.8.0_65/ , Mint Linux 17.2

**Comment by lessthanoptimal** [comment]
Awesome!  I'm on vacation at the moment but I'll verify that everything is working in about a week if not sooner.

**Comment by lessthanoptimal** [comment]
Tested it on my project and everything looks good!  @eriwen what's the next step so that this can be added to the next gradle release and this ticket closed?

**Comment by lessthanoptimal** [comment]
Did this fix make it into 4.0.1? Just tried creating documentation with javascript (after adding a hack for 8u121) and it fails.  I'm getting a ton of error messages like:

> javadoc: error - Illegal package name: "(function(i,s,o,g,r,a,m){i[\"

**Comment by bmuschko** [comment]
@lessthanoptimal The fix already made it into 4.0-rc1. Please raise a different issue if you see a another problem.
