### ISSUE TITLE
com.fasterxml.jackson.core:jackson-databind Security Vulnerabilities in Gradle 5.x

### ISSUE THREAD

**Issue by MikeBerryFR** [gradle/gradle#10902]
### Expected Behavior
The latest gradle distribution should include jackson databind libraries version 2.9.10 instead of version 2.9.8.

### Current Behavior
Several Security Vulnerabilities have been identified related to FasterXML jackson-databind in version 2.9.8

https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html

This is similar to previous issues: #5505, #8449

### Context
No known immediate impact to gradle however there is a new version of jackson-databind (2.9.10) which should address the issues above.

### Steps to Reproduce 
Not applicable

### Your Environment
Not applicable

**Comment by lingocoder** [comment]
You spotted that too, huh @MikeBerryFR? [*That's not the only one*](http://bit.ly/Post3302163), surprisingly.

Could it be one of those so-called, „*false positives*“ I wonder?

**Comment by big-guy** [comment]
We use Jackson to communicate with GCS-backed repositories, so Gradle isn't vulnerable in the same way that a webservice accepting user input may be.

Regardless, we updated to 2.9.10 in 6.0.

**Comment by JLLeitschuh** [comment]
Hi all,

I just want to follow up on this quickly. The other thing about this Jackson vulnerability and any similar gadget chain vulnerabilities is that it requires that the user is using `ObjectMapper::enableDefaultTyping`.

When this default typing feature is enabled, Jackson embeds type information into the JSON it generates. For example:

```
{ "phone" : {
   "@class" : "package.InternationalNumber",
   "areaCode" : 555,
   ...
  }
}
```

This allows a malicious attacker to specify their own custom class that Jackson will use to deserialize the JSON object.

If you search across the Gradle codebases you will find 0 uses of the `enableDefaultTyping` method or any of its variants. As such, we determined that this was not a vulnerability impacting Gradle in such a way that we felt this needed to be acted upon as a security issue.

**Comment by lingocoder** [comment]
Hey thanks for that reassurance, @JLLeitschuh :+1:

There probably isn't any value in posting these kind of explanations in your [*Securities Advisories page*](http://bit.ly/GrdlSecAdv) to clarify the different CVEs that Gradle libs get flagged for. Or is there? I doubt many people even know that tab exists. I only stumbled upon it myself by accident.

**Comment by JLLeitschuh** [comment]
I don't think that the security advisories page is a good location to tell people when we believe that security vulnerabilities _don't_ impact our software.

That GitHub feature is relatively new, I think that more people will know to look at it as it's usage gains traction.

If people are concerned, we can simply point them back to the above explanation.
