### ISSUE TITLE
Let precompiled script plugins compiled with Gradle 6.x work with previous versions of Gradle

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#10927]
Starting with Gradle 6.0, Kotlin DSL precompiled script plugins are compiled against a new base class which is not available in previous Gradle versions and because of that, precompiled script plugins built with Gradle 6.0 won't be compatible with previous Gradle versions.

Gradle should provide a mechanism to allow plugins compiled against Gradle 6.x to be used with Gradle versions prior to 6.0.

**Comment by bamboo** [comment]
A follow-up of #10822.

**Comment by adammurdoch** [comment]
In general, we don't support taking any kind of plugin compiled against a given version Gradle and running it in an older version of Gradle. Whether we should support this or not is another question, but I wouldn't fix this in an ad hoc way just for this case.
