### ISSUE TITLE
Can't resolve dependencies in --offline mode when dependency constraints are used 

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#10934]
### Context
This bug was originally reported for the Android Gradle plugin (see https://issuetracker.google.com/141128471), but it looks like an issue in Gradle, so I'm re-filing it here.

### Steps to Reproduce
(Most of the text below is copied from the linked bug.)

1. Open attached project: [JetifierTest.zip](https://github.com/gradle/gradle/files/3685434/JetifierTest.zip)
2. Run `./gradlew assemble` and let it download all dependencies and cached
3. Run `./gradlew assemble --offline`. Gradle will start complaining about dependencies missing from cache even though they were just downloaded a second ago.

### Possible Explanation
The sample project has these dependencies:
   ```
 dependencies {
        api("com.google.cloud:google-cloud-dialogflow:0.102.0-alpha")
        implementation("io.grpc:grpc-okhttp:1.22.0")
    }
```
where `com.google.cloud:google-cloud-dialogflow:0.102.0-alpha` transitively depends on `io.grpc:grpc-core:1.21.0`, and `implementation("io.grpc:grpc-okhttp:1.22.0")` is used to update `io.grpc:*:1.21.0` to `io.grpc:*:1.22.0`.

In the normal mode (without `--offline`), Gradle can read the meta-data of both `1.21.0` and `1.22.0`, but only downloads the finalized `1.22.0` version to the local cache.

In the offline mode, running `./gradlew assembleDebug --offline` produces the following error:

```
Execution failed for task ':lib:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':lib:debugCompileClasspath'.
   > Could not resolve io.grpc:grpc-core:[1.21.0].
     Required by:
         project :lib > io.grpc:grpc-alts:1.21.0
         project :lib > io.grpc:grpc-grpclb:1.21.0
      > No cached version listing for io.grpc:grpc-core:[1.21.0] available for offline mode.
```

This is because Gradle wants to read the meta-data of 1.21.0, but it wasn't downloaded earlier in the Gradle cache.

### Workarounds
The above issue doesn't happen if I use the following workarounds:

1. [Not recommended] Temporarily disable AGP's dependency constraints (https://developer.android.com/studio/build/dependencies#classpath_conflicts). This should be done for `--offline` builds only, and should be re-enabled whenever possible:
`    -Pandroid.dependency.useConstraints=false`

2. [Preferred] Use Gradle's dependency resolution rules to change the dependencies' versions instead of adding a new dependency with the intended version as done in the sample project (https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html):
```
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'io.grpc') {
                details.useVersion '1.22.0'
                details.because 'Insert reason here'
            }
        }
    }
```

### Request
The existence of workaround 1 suggests that this is a limitation of Gradle when dependency constraints are used. If this was by design, it would be a great to get a suggestion on a fix in the Android Gradle plugin or in the user's build.gradle files.

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue is no longer reproducible in 6.0.1. Most likely, it related to this change
https://docs.gradle.org/current/userguide/upgrading_version_5.html#maven_or_ivy_repositories_are_no_longer_queried_for_artifacts_without_metadata_by_default
