### ISSUE TITLE
Sample Portal

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#10932]
This epic serves the purpose of tracking the tasks to be accomplished for implementing the sample portal on `gradle/gradle` with a stretch goal of unifying the samples under `gradle/native-samples`, `gradle/kotlin-dsl-samples` and individual Guides. The unification here cover only the infrastructure. Each project should be free to publish its samples how ever they want. Some opinionated and less opinionated piece of infrastructure will be provided to assemble samples, create ready to use Zip (for kotlin and groovy DSL), a way to document the sample, a sample index, basic testing (well behave, working, cross-version, against nightly Gradle release, no deprecation warning, etc.).

A bigger stretch goal is to allow plugins author to use the same documentation plugins for developing samples for their plugins.

**Comment by lacasseio** [comment]
Keeping track of all the work involved by this epic from other repositories:
- https://github.com/gradle-guides/gradle-guides-plugin/pull/54
- https://github.com/gradle-guides/gradle-guides-plugin/issues/55

**Comment by jjohannes** [comment]
All samples from the guides have been moved to https://docs.gradle.org/current/samples/index.html

There are no plans to do anything on `gradle/native-samples` and `gradle/kotlin-dsl-samples`. We will just keep them around as they are.
