### ISSUE TITLE
Running Gradle with Java8 and compile Java13 with fork

### ISSUE THREAD

**Issue by frankbenoit** [gradle/gradle#10959]
### Expected Behavior
I want to run Gradle with the default system JRE, in my case Java8.
And in the build I want to use a specific JDK 13 with the option.fork=true

I use this configuration:
````
compileJava {
    options.encoding = 'UTF-8'
    sourceCompatibility = 13
    targetCompatibility = 13
    options.compilerArgs << "-parameters"
    options.compilerArgs << "--release" << "13"
    options.compilerArgs << "--enable-preview"
    options.fork = true
    options.forkOptions.executable = "${projectDir}/tools/java/bin/javac.exe"
}
````
### Current Behavior
When I start gradle with the JRE 8, this fails with message:
````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 13' using tool chain: 'JDK 8 (1.8)'.
````
But when I set the JAVA_HOME to the JDK 13, then it runs successfully.

I have also posted this as a question on stackoverflow: https://stackoverflow.com/questions/58247800/running-gradle-with-java8-and-compile-java13-with-fork

### Context
I want to exchange the used JDK by some procedure in the build process. Using the JDK for gradle itself leads to problems, because the gradle daemon is logging the files.

### Steps to Reproduce 
Have a JRE Java8 and a JDK 13. Configure the JDK 13 is forked javac and use the JRE8 to start Gradle.

### Your Environment
https://scans.gradle.com/s/pv55zxjyftouw

**Comment by ljacomet** [comment]
As an FYI, this is now possible and much easier with [the toolchain feature](https://docs.gradle.org/current/userguide/toolchains.html) introduced in Gradle 6.7.
