### ISSUE TITLE
Add Generated annotation to kotlin-dsl generated files

### ISSUE THREAD

**Issue by CristianGM** [gradle/gradle#10956]
JaCoCo ignores classes and methods annotated with any annotation containing Generated in the name ( since 0.8.3, previously at 0.8.2 it was mandatory to be named exactly Generated ) with RetentionPolicy class or runtime.

The kotlin-dsl plugin generates `kotlin-dsl-accessors`, `kotlin-dsl-external-plugin-spec-builders`, and `kotlin-dsl-plugins` folders with lots of files that JaCoCo add to the reports.

### Expected Behavior

JaCoCo shouldn't report coverage for any of those generated files.

### Current Behavior

The coverage is times lower because there are a lot of generated code.

### Context

I'm developing a gradle plugin and the coverage it's really low while the real coverage would be hight.

**Comment by eskatos** [comment]
Thanks for the report Christian, that makes sense.

Here are some pointers about Jacoco and `@*Generated*`:
- https://www.jacoco.org/jacoco/trunk/doc/changes.html, search for "generated"
- https://github.com/jacoco/jacoco/commit/2458e8a4e467a5afc376b56a4e487ac54de0158e
- https://github.com/jacoco/jacoco/issues/831
- https://github.com/jacoco/jacoco/issues/685

It's a shame that [`@javax.annotation.Generated`](https://docs.oracle.com/javase/7/docs/api/javax/annotation/Generated.html) has source retention 🤷‍♂

**Comment by vlsi** [comment]
Just in case, I've raised an issue for IntelliJ IDEA: https://youtrack.jetbrains.com/issue/IDEA-224315
