### ISSUE TITLE
FileSystemLocationProperty issue with plugins built with Gradle 5.6

### ISSUE THREAD

**Issue by jlstrater** [gradle/gradle#10953]
When a plugin is built with Gradle 5.6, any end-user trying to run with < Gradle 5.6 receives an error message similar to 
```
 > Could not generate a decorated class for class com.bmuschko.gradle.docker.DockerExtension.
         > org/gradle/api/file/FileSystemLocationProperty
``` 

More details can be found in [this linked issue](https://github.com/bmuschko/gradle-docker-plugin/issues/866#issuecomment-538173505). 

### Expected Behavior

no error in earlier versions of Gradle

### Current Behavior

plugin only works with Gradle 5.6+

### Context

I have tested this issue against Gradle 5.1-5.5 but not anything earlier than that.

### Steps to Reproduce 

see [this issue on the Docker plugin](https://github.com/bmuschko/gradle-docker-plugin/issues/866#issuecomment-538173505)

@bmuschko was also able to reproduce this as stated in the linked issue.

### Your Environment

Build scan URL is included in the linked issue.

**Comment by adammurdoch** [comment]
In general, we only guarantee that a plugin build with a particular Gradle version works only with that version and later versions. As such, this isn't a regression and the plugin should be built with the oldest version it is intended to support.

Of course, this isn't the greatest guarantee in the world, but the question of what the guarantee _should_ is a different one and also something we can improve. However, we're unlikely to implement an improved guarantee by making the Gradle API forwards compatible (ie Gradle version x can host something build using the API of Gradle version > x), but there are other options we have to make the experience better (eg give you a way to declare the plugin's target version and Gradle presents the correct API at compile time, and runs the functional tests against the target version and most recent version, and this metadata travels with the plugin when it is published, and so on).

I think it would be better to replace this issue with one that describes the use case better (maybe by just renaming this issue), e.g. I want to be able to build and test a plugin that supports an older version of Gradle using a newer version of Gradle.
