### ISSUE TITLE
[Documentation] Broken link in create documentation

### ISSUE THREAD

**Issue by dcabasson** [gradle/gradle#10965]
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.TaskContainer.html#org.gradle.api.tasks.TaskContainer:create(java.lang.String)

The link to

> See **here** for more details.

is pointing to https://docs.gradle.org/current/Project.html#properties which doesn't exist.

**Comment by big-guy** [comment]
Thanks @dcabasson - I pushed a fix to release for this. It'll be fixed in 6.0
