### ISSUE TITLE
Virtual File System

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#10964]
Implement a virtual file system which allows touching disk fewer times and fine grained invalidation.

----
/cc @gradle/build-cache

**Comment by wolfs** [comment]
There is a paper on [Confluently Persistent Tries
for Efficient Version Control](https://erikdemaine.org/papers/ConfluentTries_Algorithmica/paper.pdf) which introduces a data structure which is more efficient for inserts/removes/moves than our current immutable trie. We may want to look into this at some point.

**Comment by lptr** [comment]
Nice find!
