### ISSUE TITLE
ExtensionAware delegate provider in Kotlin DSL is very counterintuitive when used for extension properties

### ISSUE THREAD

**Issue by netvl** [gradle/gradle#10979]
### Expected Behavior

```kotlin
// in settings.gradle.kts

rootProject.name = "root"

include("project-1", "project-2")

gradle.allprojects {
    var someProperty: String by extra
    someProperty = name
}
```

```kotlin
// in build.gradle.kts

var Project.someProperty: String by extra

allprojects {
    println(someProperty)
}
```

I expect this script to print

```
root
project-1
project-2
```

### Current Behavior

Instead, this script prints

```
root
root
root
```

### Context

In my case, I have two groups of projects in a build written in different JVM languages and for different purposes. Within each group these projects have some common configuration logic. In order to set up this common configuration logic, I mark these projects with a boolean flag inside `settings.gradle.kts`, and then use this flag in the root `build.gradle.kts` to perform common configuration, roughly like this:

```kotlin
val Project.isFoo: Boolean by extra
val Project.isBar: Boolean by extra

allprojects.filter { it.isFoo }.forEach {
    ...
}

allprojects.filter { it.isBar }.forEach {
    ...
}
```

The problem is, the `by extra` delegation here won't work, since `extra` means extra properties of the top-level `Project` (because that's where these extension properties are declared). Instead of `by extra`, I have to use something like

```kotlin
val Project.isFoo: Boolean
    get() = extra.get("isFoo") as Boolean

val Project.isBar: Boolean
    get() = extra.get("isBar") as Boolean
```

The reason why this happens is that `ExtensionAware` delegate provider, quite naturally, uses the respective `ExtensionAware` object to retrieve properties from, ignoring the receiver object completely.

Ideally `extra` or probably some other delegate provider should allow using the target extra properties map. At the very least, if used like above, it should throw an exception, because currently it is very confusing because it compiles but does not work correctly.

### Steps to Reproduce 

See examples above.

### Your Environment

Gradle 5.6.2

**Comment by netvl** [comment]
Side note: I'm not sure what kind of issue this is (a bug or a feature request), but since it is an example of very confusing behavior, I decided it is more like a bug than a potential feature.

**Comment by bamboo** [comment]
Thanks for the report, @netvl.

I'd argue this is a feature request. And if I understand it correctly I think the title would better reflect it rephrased into something like:

> `ExtensionAware.extra` property delegate should honor receiver when used to declare an extension property.

What do you think?

**Comment by netvl** [comment]
@bamboo fair point about it being a feature request (as I said, I was not sure myself), but I think it might actually be better to keep `extra` the way it is (because `extra`, when not used as a delegate, actually does return the extra properties map of whatever object it is called on, so it would probably be equally confusing if the delegate it provides used the target object's map). Introducing an alternative way to declare such a delegate would be a better approach IMO.

**Comment by netvl** [comment]
Maybe something along the lines of
```
val Project.someProperty by extra.ofReceiver
```
?

I wonder if this could be done generically, since `extra` seems like an instance of some generic pattern represented by `org.gradle.kotlin.dsl.PropertyDelegate`/`org.gradle.kotlin.dsl.MutablePropertyDelegate`.
