### ISSUE TITLE
Check if native libraries work with macOS Catalina

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#10988]
From https://developer.apple.com/news/?id=04102019a:

> We’re working with developers to create a safer Mac user experience through a process where all software, whether distributed on the App Store or outside of it, is signed or notarized by Apple. With the public release of macOS 10.14.5, we require that all developers creating a Developer ID certificate for the first time notarize their apps, and that all new and updated kernel extensions be notarized as well. This will help give users more confidence that the software they download and run, no matter where they get it from, is not malware by showing a more streamlined Gatekeeper interface

Let's see if our native libraries are affected. Thanks @paplorinc for reporting.

---
cc: @gradle/build-cache

**Comment by paplorinc** [comment]
See https://twitter.com/thomaswue/status/1181517559503507456 for context

**Comment by lptr** [comment]
They seem to work:

![image](https://user-images.githubusercontent.com/495366/66734980-667bae80-ee65-11e9-8f17-741a95840949.png)

**Comment by paplorinc** [comment]
Thanks for checking!
