### ISSUE TITLE
TestLogging should use display names

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#10983]
JUnit 5 introduced the notion of display names for test classes/methods (or more generally all elements in the tree of tests).

Gradle currently only includes the display names in the HTML reports but prints the technical names when `testLogging {}` is configured.

### Expected Behavior

When running `./gradlew test` for the [junit5-jupiter-starter-gradle](https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle) project, the output should look like this:

```
> Task :test

CalculatorTests > 1 + 1 = 2 PASSED

CalculatorTests > 0 + 1 = 1 PASSED

CalculatorTests > 1 + 2 = 3 PASSED

CalculatorTests > 49 + 51 = 100 PASSED

CalculatorTests > 1 + 100 = 101 PASSED
```

Moreover, the currently internal `getClassDisplayName()` and `getDisplayName()` methods should be moved to `TestDescriptor` and marked with `@Incubating` so they can be used in callbacks like `afterTest {}` and `TestListener` implementations.

### Current Behavior

Current output:

```
> Task :test

com.example.project.CalculatorTests > addsTwoNumbers() PASSED

com.example.project.CalculatorTests > add(int, int, int)[1] PASSED

com.example.project.CalculatorTests > add(int, int, int)[2] PASSED

com.example.project.CalculatorTests > add(int, int, int)[3] PASSED

com.example.project.CalculatorTests > add(int, int, int)[4] PASSED
```

### Context

Related issue: #5975

**Comment by bjliu** [comment]
I am interested in working on this issue but am new to open-source!

**Comment by marcphilipp** [comment]
@bjliu Sure thing! Be sure to read our [contributor guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) before you start and let me know if you have any questions.

**Comment by marcphilipp** [comment]
@bjliu FYI There's already a PR now.
