### ISSUE TITLE
Expose Repository MetadataSources

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#10982]
We encountered a use-case where we replace build repositories coming from customers to add some credentials but we do it so by removing the declared repo and add a new one with some internal opinions.

This has been working great until now that we need to carry over things like `metadataSources` config.

Providing a public API to get current `MetadataSources` for a repository enables:

* Capability of verifying that repositories configurations are ok based provided information
* Being able to use the current configuration to copy over to other repo

**Comment by bmuskalla** [comment]
Fixed with #10981
