### ISSUE TITLE
./gradlew $TASKNAME --help

### ISSUE THREAD

**Issue by jmfayard** [gradle/gradle#10989]
I find the syntax for getting help on the CLI not great from a UX point of view.

### Current Behavior

`./gradlew help --task dependencies`

The syntax makes sense from the point of view of Gradle, there is a task called "help" who has an option "--task"

### Expected Behavior

As a user, I would find this flow more natural: add `--help` at the end of the command-line I am currently struggling with

`./gradlew dependencies --help`

So I would like to have this an alias for the first version.

### Context

I asked the question on the Gradle Community slack channel and it seems that I'm not the only one struggling with this.  

> Have been using Gradle for the past 6 years and I still type the first syntax and have to always look up the second one. It’s definitely a UX issue for me. 

https://gradle-community.slack.com/archives/CA7UM03V3/p1570627201006800

**Comment by oesolutions** [comment]
Some extra requirements to consider; Should `./gradlew taskOne ... taskN --help`:
1. Show help for all tasks.
2. Ignore taskOne ... taskN-1 and show help for taskN.
3. Execute taskOne ... taskN-1 and show help for taskN.
4. Other?

**Comment by jmfayard** [comment]
Good question. I have no strong opinions except that 3) would be really bad. Don't execute anything if I'm asking for help.

**Comment by Alex-Vol-SV** [comment]
I agree 3) would be really bad.
I would vote for 1) actually.
