### ISSUE TITLE
Gradle 5.4 and above break incremental compilation in Micronaut applications (and probably others)

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#10985]
When running tests in IntelliJ (https://github.com/micronaut-projects/micronaut-core/issues/2173) or using `./gradlew run --continuous` (https://github.com/micronaut-projects/micronaut-core/issues/2207) with the Gradle daemon enabled, incremental compilation is broken since Gradle 5.4 with Micronaut applications with the following error:

```
Caused by: java.lang.IllegalArgumentException: Not a valid class name: myapp.
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:129)
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107)
	at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:64)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.createCompileTask(JdkJavaCompiler.java:69)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:100)
```

### Expected Behavior

Should compile

### Current Behavior

Doesn't compile

### Context

We have to downgrade Micronaut users to Gradle 5.3 which is the last known working version without this issue.

### Steps to Reproduce 

See issue and example at https://github.com/micronaut-projects/micronaut-core/issues/2173 with steps to reproduce

### Your Environment

Gradle 5.4 or above, and any JDK

**Comment by ivyazmitinov** [comment]
@graemerocher issue is caused by `org.gradle.api.internal.tasks.compile.incremental.recomp.RecompilationSpec.NormalizingClassNamesSet#add` method, which effectively strips out most of Micronaut's proxies with names statrting with `$`.
For example, `$QueryFilterMergerDefinitionClass$$AnnotationMetadata.class`

**Comment by graemerocher** [comment]
So a bug in Gradle then.. class names of that nature are completely legal

**Comment by esocode** [comment]
I had the same error message (_Not a valid class name_) today with every second invocation of `compileTestJava` failing in a new Micronaut-based project that used Gradle 5.6.4. After switching to Gradle 6.0.1 the problem no longer occurs.

**Comment by big-guy** [comment]
@graemerocher could you give the nightly build `6.1-20191212033525+0000` a try (`gradle wrapper --gradle-version=6.1-20191212033525+0000`)?  The project linked in https://github.com/micronaut-projects/micronaut-core/issues/2173 wasn't failing with 6.0, but there was definitely a problem that I tried patching.

**Comment by graemerocher** [comment]
@big-guy I have been using the snapshot for most of today and have not seen the error again, so looks like it is fixed for good. Thanks again.

**Comment by graemerocher** [comment]
Bad news. I have seen this again with 6.1 rc1 

```
* What went wrong:
Execution failed for task ':runtime:compileJava'.
> Not a valid class name: io.micronaut.runtime.context.scope.package-info
```

**Comment by melix** [comment]
@graemerocher would you mind trying with a 6.5 snapshot? We changed how we map from class files to source files and therefore the mapping method at fault in this bug has gone. Note that this is only true if you're not setting `javaHome` or `executable` on `JavaCompile` tasks.
