### ISSUE TITLE
JavaExec should support the ability to inherit standard streams

### ISSUE THREAD

**Issue by gnodet** [gradle/gradle#1099]
The original issue has been raised in the JLine project, see [here](https://github.com/jline/jline3/issues/77).
JLine has very tight terminal integration and in order to leverage the terminal, it has to be able to access the standard input/output streams.

Hence, I propose to enhance to `JavaExec` task to add a `inheritIO` field that would trigger the use of the [`inheritIO()`](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#inheritIO()) method on the `ProcessBuilder`.

**Comment by gnodet** [comment]
Anything I can do to help ?

**Comment by lacasseio** [comment]
As discussed on the PR (https://github.com/gradle/gradle/pull/1152), a public API should be introduced to allow user input from Gradle's runtime JVM.
