### ISSUE TITLE
Provide support for Generic Repositories

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#11006]
Hi folks,

One of the breaking changes between Gradle 5.x and 6.x is the removal of `artifact()` from the default `metadataSources` for Ivy and Maven repos. While this is great, there are plugins that depended on these APIs to resolve artifacts from other types of repos. For example: https://github.com/srs/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/task/SetupTask.groovy#L180

Wondering if it would make more sense to have a support for a `Generic` repository that isn't related to Ivy or Maven at all. It seems that also would be simpler? like no need to support gradle metadata or what would happen if someone adds `artifact()` and `gradleMetadata()` for example. 

It seems like Gradle itself does similar kind of thing for javascript repos by using Maven repo: https://github.com/gradle/gradle/blob/b189979845c591d8c4a0032527383df0f6d679b2/subprojects/javascript/src/main/java/org/gradle/plugins/javascript/base/JavaScriptRepositoriesExtension.java#L53

What are your thoughts on this?

**Comment by melix** [comment]
A "generic" repository probably doesn't make a lot of sense if the associated artifacts have metadata: Gradle needs to know about metadata. However, the ticket here is about "raw files", like "give me a way to download this file".

There are different considerations:

1. provide an API to fetch external resources and explain for how long they can be cached. Something like this already exists for the component metadata suppliers, and we could probably make it available in a wider scope. This is not really a "repository", but rather a convenience for fetching external resources, relative to a base URI.

2. a generic "repository" with metadata. In this case, most likely an Ivy repository with a custom pattern and artifact pattern is enough.

**Comment by rpalcolea** [comment]
Hi @melix 

This makes sense. We are doing ivy repos and that’s enough.

Maybe this should be closed now? Thoughts?
