### ISSUE TITLE
Task without inputs is treated UP-TO-DATE, however it contradicts the documentation

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#11000]
### Expected Behavior

The documentation should match the behavior.

I'm inclined that "no inputs" should be more like a special case for `outputs.upToDateWhen { false }`.
In other words, if the user declares no inputs, Gradle should consider the task always stale, and it should suggest the user declare an input or a dummy `upToDateWhen { true }`.

### Current Behavior

https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_outcomes

> UP-TO-DATE
> Task’s outputs did not change.
> Task **has** outputs **and inputs** and they have not changed. See Incremental Builds.

To me it means the task has should have both inputs and outputs.
However, in practice, if I create a task that has only outputs, then Gradle still thinks the task can be cacheable.

```gradle
task abc() {
  outputs.file('test.txt')
  doLast {
    file('test.txt') << System.currentTimeMillis()
  }
}
```

```
$ ./gradlew abc --info
> Task :abc
Caching disabled for task ':abc' because:
  Build cache is disabled
Task ':abc' is not up-to-date because:
  No history is available.
:abc (Thread[Execution worker for ':',5,main]) completed. Took 0.163 secs.
```

Second execution:

```
> Task :abc UP-TO-DATE
Caching disabled for task ':abc' because:
  Build cache is disabled
Skipping task ':abc' as it is up-to-date.
:abc (Thread[Execution worker for ':',5,main]) completed. Took 0.013 secs.
```

### Context

I'm creating a task that produces "the draft mail". The task generates a text with different URLs, checksums, and so on, so I can't easily mention all the inputs.
The task itself is fast, so there's no much harm in re-running it every time.

However, I want to declare the output file, so the output can be consumed by other tasks, printed, etc.
Then comes the issue: if the input is not declared, Gradle assumes the task is always up to date which might be misleading.

**Comment by lptr** [comment]
There's a lot to clarify in our documentation, and we hope to get to it in the coming months.

As far as I can tell, your build works correctly.

The misunderstanding probably stems from the fact that not all inputs are user-defined. The task's type FQCN along with its classpath are automatically handled as inputs. In effect, this means that changing the task's implementation will make it out-of-date.
