### ISSUE TITLE
compileJava task fail in the case of contains specific characters in package name 

### ISSUE THREAD

**Issue by sis-yoshiday** [gradle/gradle#11017]
When compile java class with package contains characters `cvs`, `compileJava` task fail.

### Expected Behavior
`compileJava` task should be successful

### Current Behavior
fail with message `error: package cvs does not exist`

### Context
I tried to investigate if `cvs` is reserved by java lang, but not.

Affected versions are below

| gradle version | affected |
| --- | --- |
| 4.4 | **not** affected |
| 4.4.1 | **not** affected |
| 4.5 | **affected** |
| 4.6 - 5.6.2 | **affected** |

### Steps to Reproduce 

minimum project pushed to below repository.

https://github.com/sis-yoshiday/gradle-11017

and execute `compileJava` task.

```
./gradlew compileJava
```

### Your Environment
```
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Corretto-11.0.3.7.1 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.3.7.1 (build 11.0.3+7-LTS, mixed mode)
```
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**Comment by lptr** [comment]
Is this related to default excludes maybe?

**Comment by sis-yoshiday** [comment]
maybe `DirectoryScanner#getDefaultExcludes()` in `org.apache.ant` ?

in `DirectoryScanner`, that excludes some files matching `CVS`

was seems to be introduced by
e06778ba50e1a0ec04aac9db36ffc6b554faa4c2

**Comment by lptr** [comment]
Hm, how did you find that commit? IIRC, that change was just a reorganization of default excludes that were already observed when crawling directories.

Also, the change was made in Gradle 5.0, so it won't account for 4.5 and 4.6 etc. being affected. It should be something introduced in 4.5 that caused this change.

**Comment by sis-yoshiday** [comment]
@lptr sorry, I'm not familiar with internal behavior.
found commit searching by  keyword `default excludes`
and read `DirectoryScanner#getDefaultExcludes()` implementation from `org.apache.ant`

Right, as you said, this commit was in 5.0 and seems to be unrelated.

**Comment by wolfs** [comment]
@sis-yoshiday Can you try calling 
```
org.apache.tools.ant.DirectoryScanner.removeDefaultExclude("**/CVS")
org.apache.tools.ant.DirectoryScanner.removeDefaultExclude("**/CVS/**")
```

in your `settings.gradle` and see if it helps? This at least would show that the default excludes are the problem.

Is your directory named `CVS` or `cvs` when you look at it from your OS? Are you using a case insensitive file system?

**Comment by sis-yoshiday** [comment]
@wolfs Thanks for your help.

I tried changing `settings.gradle`.
And `compileJava` task came to work correctly.

Directory is named as lower case `cvs`.
And OS is `MacOS 10.14.6`, file system is case-sensitive.

**Comment by wolfs** [comment]
So you reformatted you disk on macOS with a case-sensitive file system? Since the default is case-insensitive.

**Comment by wolfs** [comment]
@sis-yoshiday I found the bug causing this behaviour in our code and fixed it in this PR: https://github.com/gradle/gradle/pull/11169
The change has been there since 5.4, thank you for reporting the issue!

**Comment by sis-yoshiday** [comment]
@wolfs sorry, my MacOS was set up by default and case-insensitive.
Is this be affected to above fix ?

**Comment by wolfs** [comment]
@sis-yoshiday The fix is not affected by using a case-insensitive file system.

**Comment by wolfs** [comment]
@sis-yoshiday Can you try out the nightly `6.1-20191029232520+0000` which contains the fix?

I also created #11176 and follow up issues for better handling default excludes in general.

**Comment by wolfs** [comment]
@sis-yoshiday did try out the nightly and confirmed it fixes the problem: https://github.com/gradle/gradle/issues/11176#issuecomment-548277795
