### ISSUE TITLE
 Server returned HTTP response code: 403

### ISSUE THREAD

**Issue by thubin233** [gradle/gradle#11025]
androidStudio create new a project ,This situation always occurs.

 Server returned HTTP response code: 403 for URL: https://services.gradle.org/distributions/gradle-4.10.1-all.zip

**Comment by blindpirate** [comment]
This is public on Internet. We didn't receive any other report for this issue, so I strongly recommend you checking yourself's network, e.g. firewall, proxy, etc.

P.S. I can download this file without issues.

**Comment by thubin233** [comment]
I tested it, the browser can download it directly, but androidStudio downloads the prompt number 403, so I think it is impossible to be a firewall problem, so it is probably the problem of androidStudio itself, but I still reinstall androidStudio is still invalid, so this with you We have no direct relationship, right? If so, should I consult the official androidStudio?

**Comment by blindpirate** [comment]
You may need to check the proxy settings for AS itself.

**Comment by thubin233** [comment]
It has not been set up before, it can be used, but now suddenly prompted an error, can not be downloaded.
