### ISSUE TITLE
Enforce dependsOn order on task references

### ISSUE THREAD

**Issue by ghost** [gradle/gradle#11031]
When I run this code from my root project, which includes many builds, I want to enforce the depends order of tests. I don't want the tests to run in parallel so I wrote this code but the compiler complains. In my view this should be possible.

```
task test {
    dependsOn gradle.includedBuilds*.task(":test")
    for (int i = 0; i < gradle.includedBuilds.size() - 1; i++) {
        def nextTask = gradle.includedBuilds[i + 1].task(":test")
        def currentTask = gradle.includedBuilds[i].task(":test")
        nextTask.mustRunAfter currentTask
    }
}
```

### Expected Behavior
It should run each test sequentially and chain the task dependency as is TaskReference was a real "Task".

### Current Behavior
It doesn't compile because TaskReference cannot be used
Compiler prints:
`> No signature of method: org.gradle.composite.internal.IncludedBuildTaskReference.mustRunAfter() is applicable for argument types: ([Ljava.lang.Object;) values: [[IncludedBuildTaskReference1_groovyProxy@65037e06]]`

### Context
I want to run tests sequentially because each project spawns to port listeners which might be the same and if they run in parallel, they conflict with the ports.

**Comment by coder82** [comment]
Figured it out, but shouldn't it be  simpler?

```
task test {
    def tasks = gradle.includedBuilds.toArray().stream().map { build ->
        tasks.create(name: "${build.name}_test", type: GradleBuild) {
            buildFile = "${build.name}/build.gradle"
            tasks = ['test']
            startParameter.systemPropertiesArgs = [cmsAutoStart: ""]
        }
    }.toArray()

    for (int i = 0; i < tasks.length - 1; i++) {
        tasks.getAt(i + 1).mustRunAfter(tasks.getAt(i))
    }

    dependsOn tasks //sequential run
}
```

**Comment by robstoll** [comment]
@coder82 did the above actually work in the end? I have the feeling this is no longer a composite build but just builds the projects independently one after the other without substituting the dependencies. Or am I wrong?

**Comment by ljacomet** [comment]
A couple things have changes in recent Gradle versions:
* You can address tasks from included build by path: #15002
* Build services have been introduced and allow to declare that tasks consume resources that have [limited parallelism](https://docs.gradle.org/current/userguide/build_services.html#concurrent_access_to_the_service). However you cannot currently declare a cross build service like that. See related issue #20867

But we will close this specific feature request as there is no plan to support a `TaskReference` for `mustRunAfter`.

**Comment by chris-hatton** [comment]
> But we will close this specific feature request as there is no plan to support a TaskReference for mustRunAfter.

I cannot think why not - this is a critical gap in Gradle's functionality.  There appears to be no way to make a referenced Task run *after* a regular Task, besides `finalizedBy` - which proves it can be done, it just has different semantics.

**Comment by mach-wkl** [comment]
I second the motion to reconsider. I have a cleanupDeploymentsDirectory task that deletes everything from a directory, and tasks in includedBuilds that deploy stuff to that same directory. My cleanupAndDeploy task has a `dependsOn cleanupDeploymentsDirectory` and a `finalizedBy deployEverything`, which then `dependsOn includedBuild('subproject').task(':deployToDeploymentsDirectory')` - this task frequently is executed before `cleanupDeploymentsDirectory` though! Having either `TaskReference.mustRunAfter` or `finalizedBy TaskReference` not error with "Cannot use finalizedBy to reference tasks from another build" would resolve this.
