### ISSUE TITLE
transitive=false configurations do not resolve java-platform versions

### ISSUE THREAD

**Issue by dgeissl** [gradle/gradle#11030]
### Expected Behavior
Declaring a `platform` dependency on a non-transivite configuration should resolve the versions from the platform.

### Current Behavior
The version constraints are not applied, so no versions are present at all and the dependencies can not be resolved.

### Context
I've used a `java-platform` for versioning dependencies of a multiproject build that contains `java`, `war` and  `ear` subprojects. That worked very well all configurations with the exception of  the `deploy` configuration from the `ear`. As I need to reference EJB and WAR artifacts built by other projects the BOMs are not only required for `earlib` dependencies but also for deploy artifacts.

### Steps to Reproduce 
See the forum thread or the reproducer project:
https://discuss.gradle.org/t/boms-broken-java-platforms-for-non-transitive-e-g-ear-deploy-configurations/33475
https://github.com/dgeissl/gradle-showcase-ear-platform/tree/master

### Your Environment
Gradle 5.5.1
Java 1.8.0_202
Windows 10 1809

**Comment by ljacomet** [comment]
This is more a feature request and not really a bug.
There is however no plan to support this for the moment, so closing.

**Comment by breskeby** [comment]
IMO that is definitely a bug. what makes it a feature request in your opinion @ljacomet ? I understand that implementation wise it's tricky. But having a platform applied and not resolving the proper version definitely seems like a bug. Especially as there's no documentation clarifying why that would only work on transitive dependencies. Just from the docs I would definitely expect this to work

**Comment by dgeissl** [comment]
Haven't opened a feature issue myself, but #18129 addresses exactly this bug as a feature request.
