### ISSUE TITLE
Suggestion: have a convention for configuring plugins version

### ISSUE THREAD

**Issue by jmfayard** [gradle/gradle#11032]
As a user, I wish to have a simple convention in place to setup my plugins version, especially in a Gradle multi-project build. 

### Expected Behavior

A suggestion would be to have a simple convention like searching for a Gradle property called `plugin.com.example.plugin.id=$VERSION`

```properties
// versions.properties
plugin.com.github.ben-manes.versions=0.25.0
plugin.de.fayard.buildSrcVersions=0.6.4
plugin.org.jetbrains.kotlin.jvm=1.3.50
plugin.com.gradle.build-scan=2.4.2
```

### Current Behavior

It already works if you don't mind copy some boilerplate in `settings.gradle.kts`

<details open>
<summary>settings.gradle.kts (Kotlin)</summary>

```kotlin
pluginManagement {

    /**
     * This `resolutionStrategy` allows plugin versions to be configured from `gradle.properties
     * The convention is simply
     *     plugin.$PLUGINID=$PLUGIN_VERSION
     * To check what happen, you can set the property
     *     resolutionStrategyConfig=verbose
     **/
    val resolutionStrategyConfig: String? by extra
    resolutionStrategy.eachPlugin {
        val property = "plugin.${requested.id.id}"
        if (extra.has(property) && resolutionStrategyConfig != "false") {
            val version = extra.get(property) as String
            if (resolutionStrategyConfig == "verbose") println("ResolutionStrategy used version=$version from property=$property")
            useVersion(version)
        }
    }
}
```

</details>
<details>
<summary>settings.gradle (Groovy)</summary>

```groovy
pluginManagement {
    resolutionStrategy.eachPlugin {
        def property = "plugin.${requested.id.id}"
        if (settings.ext.has(property)) {
            def version = settings.ext.get(property)
            if (resolutionStrategyConfig == "verbose") print("ResolutionStrategy selected version=$version from property=$property")
            useVersion(version)
        }
    }
}
```

</details>

### Context

It used to be really cumbersome to configure the versions to be used in the `plugins { ... }` block, especially in a Gradle multi-project build.

Configuring the version of the Android Gradle Plugin was especially terrible. 

Gradle 5.6 provided a better feature: 

```kotlin
// settings.gradle[.kts]
pluginManagement { 
    resolutionStrategy { 
        ... 
    } 
}
```

But as a user, I may want to not have to learn about resolution strategies at all. 

What I feel is missing is a `Convention over configuration` as documented here
https://guides.gradle.org/designing-gradle-plugins/#convention_over_configuration

I invite the users of my plugin to update Gradle to 5.6 and copy/paste the exact boilerplate I have shown in this ticket. As far as I see it works well. 

In the long term, it would be even better if Gradle had a a proper format for declaring dependencies and plugin versions. But in the long term we will all be dead, and using Gradle properties for plugin versions is I think an improvment possible now.

**Comment by serebit** [comment]
Ideally, I'd like to be able to specify my plugin versions in buildSrc and be able to refer to them in the `plugins` block in my main modules, like I can with dependencies. I'm not sure how easy that is to implement though.

**Comment by jmfayard** [comment]
@serebit for your info, it's similar but less performant to set the version inside the `buildSrc`. See https://github.com/jmfayard/buildSrcVersions/issues/77

**Comment by jmfayard** [comment]
not relevant anymore
