### ISSUE TITLE
TestDescriptor should expose getDisplayName methods

### ISSUE THREAD

**Issue by britter** [gradle/gradle#11035]
### Expected Behavior

The `TestDescriptor` interface should expose the `getDisplayName()` method which is currently only available on `TestDescriptorInternal`. This way the display name can be used in `before` and `after` callbacks:

```
test {
    afterTest { desc, result
        println "$desc.displayName result is $result.resultType"
    }
}
```

### Current Behavior

`getDisplayName()` is not available on `TestDescriptor`

### Context

Part of: #10983
Follow up of: #11026

**Comment by melix** [comment]
Wouldn't `getClassDisplayName` be ecosystem-specific? Some ecosystems don't have the concept of class.

**Comment by britter** [comment]
I agree with you that exposing `getClassDisplayName` is problematic. Since `DefaultTestClassDescriptor` already returns the `classDisplayName` as `displayName` I'm not even sure we really need it exposed. The only use case would be if I have a descriptor that represents a method, I could ask for the display name of the containing class. But this could also be done by using `TestDescriptor.getParent()`.

**Comment by marcphilipp** [comment]
I tend to agree with Cédric. While the test class/method assumption is currently omnipresent in the codebase, not exposing `getClassDisplayName()` would make it easier to change that in the future.

**Comment by britter** [comment]
I changed the name of the issue to refelct this.
