### ISSUE TITLE
GRADLE_METADATA for testFixtures dependencies contains "version: null"

### ISSUE THREAD

**Issue by mkmaier** [gradle/gradle#11047]
### Expected Behavior
When publishing gradle metadata for test-fixture dependencies, the metadata should be valid.

### Current Behavior
Metadata containing dependencies on test-fixtures is invalid, containing null as a version.

### Steps to Reproduce 
Reproducer with output: https://github.com/mkmaier/gradle-metadata

The interesting part is https://github.com/mkmaier/gradle-metadata/blob/master/second-1.0.module#L111

### Context
Depending on test-fixtures that depend on test-fixtures may seem like a strange thing to do, but this bug actually blocks us from using test fixtures in those projects.

**Comment by ljacomet** [comment]
Sorry for the late reply!

This was actually fixed, probably around Gradle 6.7 as other similar issues were fixed then.
