### ISSUE TITLE
Relative paths specified for Gradle's --init-script option should be evaluated relative to the root project directory

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#11049]
Gradle currently evaluates relative paths specified for its `--init-script` option as relative to its current execution directory. This makes reusing relative paths for this parameter (in bash aliases, CI functions, etc) impractical since, the resolution of these relative paths depends on the current working directory as well as any `-p` project path option specified (which of course varies between our Gradle invocations), while at the same time the init scripts' file locations are typically invariant with respect to the root project directory.

### Expected Behavior
Relative paths specified for the `--init-script` option should be resolved relative to the root project directory. 

### Current Behavior
Relative paths specified for the `--init-script` option are resolved relative to the current execution directory (i.e: the current working directory plus any `-p` project path specified). 

### Context
Relative paths are basically unusable and we're effectively stuck using only absolute paths to specify our `--init-script` values.

**Comment by ljacomet** [comment]
Any chance you can provide reproducer steps for this so that when it gets prioritized there is a clear understanding of what is expected / not working?

**Comment by steffenyount** [comment]
@ljacomet - reproducer steps
[test-project.zip](https://github.com/gradle/gradle/files/8411762/test-project.zip)

```
$ ./gradlew --init-script init-scripts/test.init.gradle
...
BUILD SUCCESSFUL
```

```
$ ./gradlew -p sub-project --init-script init-scripts/test.init.gradle
...
FAILURE: Build failed with an exception.

* What went wrong:
The specified initialization script '/Users/steffenyount/dev/1/test-project/sub-project/init-scripts/test.init.gradle' does not exist.
```

**Comment by ljacomet** [comment]
Looking at the reproducer and the way this currently works, there are two things to consider:
* It would be a major change of behavior for existing setups.
* Because an _init script_ does not belong to a build, as you can have them in your Gradle home directory for example, tying them that way does not look like a good idea.

For these two reasons, this is not something we are considering doing.
