### ISSUE TITLE
Configure Closure delegate even when passed through function with action argument

### ISSUE THREAD

**Issue by jbytecoder** [gradle/gradle#11060]
I noticed that tasks.register overload that takes Action<Task> argument will not configure the delegate of closure when used.  This affected me because I need to have a wrapper function over it:
`def fun( String name, Action<Task> task ) {
  tasks.register(name,task)
}`

and now if I do
`fun 'exmaple', {
   doLast {
      println "Hello"
   }
}`

The doLast method is looked up on the containing closure and not on the task instance
prefixing it with `it.` solves the issue. This suggests that the delegate is not configured.
I discovered this on register function, but i've got a hunch it will be the same with any public gradle function that was overloaded for both Action and Closure

### Expected Behavior
I expect that functions in gradle that take Action as argument, redirect the invocation
to their Closure typed counterparts when argument is an Closure. In case presented above that would be:
TaskContainer.register( String name, Action<Task> action ) needs to redirect to
TaskContainer.register( String name, Closure action ) when action instanceof Closure

### Current Behavior
Currently if action is an closure it is treated as any other action it just receives the argument, and the "gradle sugar" of changed delegate is missing - which is confusing

### Context
I'm writing a plugin that aids in creation of tasks from templates,  In order to supply
the configured tasks with custom extensions I need to wrap the registration / creation task

The issue really is that i'm dead set on using Action type instead of Closure.

I want to use the action type to preserve type safety and when I sometimes use the 
closure argument then I want the IDE to be helpful - using action dose this, but currently when i forget to refer to closure argument it stops working with hard to debug exceptions
I'm aware that i can fix that my self  in my custom function, but it fells like this should go inside gradle 

I believe that if that issue got resolved the gradle methods using Closures could be removed completely   improving groovy dsl type safety for every one cheaply

**Comment by big-guy** [comment]
This works but not quite the way you're doing it.

Depending on how you're creating the object that has the `fun` method, Gradle will decorate it.

Here's an example that shows something that works and something that doesn't:
```
class MyExtension {
    final Project project
    MyExtension(Project project) {
        this.project = project
    }
    void fun(String name, Action<Task> action) {
        project.tasks.register(name, action)
    }
}

def myExt = extensions.create("myExt", MyExtension, project)

myExt.fun("hello") {
    doLast {
        println "Hello"
    }
}

void nofun(String name, Action<Task> action) {
    project.tasks.register(name, action)
}

nofun("goodbye") {
    doLast {
        println "Goodbye"
    }
}
```
Plop this in a `build.gradle` and try running `gradle hello` vs `gradle goodbye`. Gradle decorates `MyExtension` with a method `fun(String, Closure)` that delegates things properly.

**Comment by jbytecoder** [comment]
My problem was indeed that I placed my functions on object owned by extension - not being extension it self. Correcting that solved the issue. 

Thank you for your time :)
