### ISSUE TITLE
Fix android-relocation-test

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11068]
Currently `AndroidCachingSmokeTest.can cache Santa Tracker Android application` fails and is ignored. There are multiple reasons for this:

1) it seems that despite pinning the repo to a specific commit (https://github.com/gradle/android-relocation-test/commit/63c4e4c25db4a21e6694fe3e31f20f77da403b6a), we build its `master` somehow.

2) recent changes around the build scan plugin (now the "enterprise plugin") make it incompatible with the most recent Gradle versions, and our version of Santa Tracker applies the build scan plugin on its own. (See https://github.com/gradle/gradle-private/issues/2809)

This test is also pretty contrived, and should probably be ran as a separate nightly build.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
How about converting the separate repository into a regular smoke test? So we don't have to invoke testkit from testkit and check out two repositories?

See also https://github.com/gradle/gradle-private/issues/1418.

**Comment by lptr** [comment]
Lemme try that.
