### ISSUE TITLE
Too many meta files on the root?

### ISSUE THREAD

**Issue by gabrielhuff** [gradle/gradle#11067]
I've been using Gradle for a few years and I just love how extensible and modular it is.

That said, today I was randomly browsing one of my projects on Github and just stopped to take a look at the root directory:

```
<root>
|-- modules/
|-- gradle/               <- Gradle
|-- .gitignore
|-- README
|-- build.gradle          <- Gradle
|-- gradle.properties     <- Gradle
|-- gradlew               <- Gradle
|-- gradlew.bat           <- Gradle
`-- settings.gradle       <- Gradle
```
I'd say this is a typical Gradle project. Thing is: **6 out of the 9 files on the root (i.e. 67%) are Gradle related files**.

I know that in isolation the each file has a specific function (gradle wrapper, build logic, build constants, module definitions). However, looking at the big picture, it just feels unreasonable: If I didn't know how Gradle works I'd definitely be overwhelmed by all these files. I know it sounds silly to only realise this after years of usage, but sometimes it's hard to think as a new user.

I also know that on paper only `build.gradle` would be strictly required. The thing is: wouldn't it be possible to just have all this stuff on a `gradle` directory? Something like:

```
<root>
|-- modules/
|-- gradle/               <- Gradle
|-- .gitignore
`-- README
```
Of course, this wouldn't have to be the norm: the current project structure works great. But it could be an opt-in. I know it's convenient to have the wrapper on the root, but it'd be possible to have an activation script (something like Python's virtualenv). Anyway, just throwing ideas.

### Expected Behaviour
Users have the option to define **all** Gradle configuration (maybe even including subproject scripts) inside a directory on the root

### Current Behaviour
The Gradle configuration is distributed across different meta files, most of them need to be on the root.

### Context
See the example above. Basically, this could make project structures visually more appealing.

**Comment by big-guy** [comment]
This isn't likely to change as a default, but there are a few things you can do.  The only required file is really the `settings.gradle` (or `settings.gradle.kts`).  That defines the "root" of the Gradle build. Most everything else is flexible or optional, but changing where some files are may break assumptions baked into other tools (IDEs, CI, gdub, etc). You can't move the `gradle.properties` file either, but you might be able to get around that by avoiding it or combining it with the gradlew/gradlew.bat scripts.

Some ideas:
1. Don't use the wrapper and have people manage the Gradle install via tools like https://sdkman.io/.  That removes the gradlew, gradlew.bat and gradle directories. Obviously, you give up being able to know that all developers are using the correct version of Gradle at all times. 
2. Install the gradle wrapper into a non-root directory, but keep everything else the same.  To run builds, you'd have to know to run `non-root-directory/gradlew` instead.  Annoying, but it's possible. This probably breaks other tool's assumptions that try to run Gradle.
3. Move the `build.gradle` into `gradle/`, but keep the settings file where it is. You can configure the path to the build script for all projects.  This may break some assumptions other tools have that there's always a file called "build.gradle" in the root.

There are tradeoffs for all of these options.  A bulk of the files are mainly for enforcing the correct version of Gradle and making it convenient to use without having Gradle pre-installed. 

If this really bothers you, you could always add more files into the root (`LICENSE`, `NOTICE`, ...) to offset Gradle. :)
