### ISSUE TITLE
Should onlyIf and similar be declared final?

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#11079]
I'm not fully sure this is a bug or merely an understanding question.
Sorry if only the latter.
The question is, now are you supposed to correctly use `onlyIf` in a custom task class, or are you supposed to use it at all?

I'm currently writing a custom task class in a Kotlin file.
I now use it like
```koltin
open class MyTask() : DefaultTask() {
    init {
        onlyIf {
            // ...
        }
    }
}
```

But for this IntelliJ rightfully complains that I'm calling a non-final method from a constructor which is bad practice and can lead to problems if the method gets overwritten in a sub-class and there for example uses fields that are not yet initialized.

IJ suggests to make the class final, which of course does not work, because then Gradle complains that the task cannot be created as the task class is final.

What actually works is to override the `onlyIf` method, making it final like
```koltin
open class MyTask() : DefaultTask() {
    init {
        onlyIf {
            // ...
        }
    }

    final override fun onlyIf(spec: Spec<in Task>) {
        super.onlyIf(spec)
    }
}
```

So I wonder, am I using this the wrong way?
Should I do this somehow else?
Or should probably this method and similar ones be final in the Gradle code?

**Comment by big-guy** [comment]
Along with a lot of other `Task`-related methods, it could probably be made final in Gradle, but I would suggest moving the `onlyIf` into the plugin that creates the task.  The places I see in the gradle/gradle codebase that use `onlyIf` from a constructor would probably be rewritten that way today.

The main problem that I see from just adding final in the appropriate places today is that there aren't many good ways to deprecate and migrate people away from these methods if they are overriding them (for whatever reason).
