### ISSUE TITLE
[Regression 6.0-rc-1] Fail to configure maven publications to artifactory

### ISSUE THREAD

**Issue by eyalroth** [gradle/gradle#11086]
I'm trying to migrate my hybrid Scala-Java multi module project to Gradle 6.0 (using 6.0-rc-1), but my entire publishing script fails configuration for some reason:
```
eyal@eyal:/mnt/c/Users/eyal/repos/java-scala-gradle-project$ ./gradlew clean

== BUILD FAILED ==

FAILURE: Build failed with an exception.

* Where:
Script '/mnt/c/Users/eyal/repos/java-scala-gradle-project/gradle/publish.gradle' line: 99

* What went wrong:
A problem occurred evaluating script.
> org.gradle.api.publish.maven.internal.publication.MavenPublicationInternal.getPublishableFiles()Lorg/gradle/api/file/FileCollection;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
```

### Steps to Reproduce 
[This](https://github.com/eyalroth/java-scala-gradle-project/blob/master/gradle/publish.gradle) is the publishing script file in my `master` branch. I had to completely comment it out on my [`gradle-6.0` branch](https://github.com/eyalroth/java-scala-gradle-project/tree/gradle-6.0).

### Your Environment

I'm running on Windows 10's WSL.
```
eyal@eyal:/mnt/c/Users/eyal/repos/java-scala-gradle-project$ ./gradlew --version

------------------------------------------------------------
Gradle 6.0-rc-1
------------------------------------------------------------

Build time:   2019-10-18 19:24:16 UTC
Revision:     5ed5fea1446b3300afa321c661d6e865ab3157a1

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Linux 4.4.0-18362-Microsoft amd64
```
Build scan: https://scans.gradle.com/s/ypeddbtoccdy2

**Comment by ljacomet** [comment]
Can you try upgrading to the latest version of the artifactory plugin?
You are using 4.8.1 and 4.10 is available.

**Comment by ljacomet** [comment]
Some deprecated methods were removed in Gradle 6.0 and that impacts older versions of plugins.

**Comment by eyalroth** [comment]
> Can you try upgrading to the latest version of the artifactory plugin?
> You are using 4.8.1 and 4.10 is available.

That worked, thanks :)

**Comment by pjajara** [comment]
> Can you try upgrading to the latest version of the artifactory plugin?
> You are using 4.8.1 and 4.10 is available.

Was facing the same issue, upgrading to `id "com.jfrog.artifactory" version '4.10.0'` resolved my issue. Thanks @ljacomet

**Comment by vestigegroup** [comment]
Error

Unable to find method 'org.gradle.api.publish.maven.internal.publication.MavenPublicationInternal.getPublishableFiles()Lorg/gradle/api/file/FileCollection;'
org.gradle.api.publish.maven.internal.publication.MavenPublicationInternal.getPublishableFiles()Lorg/gradle/api/file/FileCollection;

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin that is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.


please, anyone, help to resolve the Gradle problem. I used  Gradle-wrapper. properties

#Sat May 01 09:14:14 IST 2021
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
