### ISSUE TITLE
NamedDomainObjectContainer - add() called before configuration closure is executed

### ISSUE THREAD

**Issue by uklance** [gradle/gradle#11080]
Listeners to a NamedDomainObjectContainer are fired before the configuration closure executes

### Expected Behavior
When you call `TaskContainer.create​(String name, Closure configureClosure)` it makes sense that the following should occur.

1. Task is instantiated
2. configurationClosure is executed to configure the task
3. Task is added to the NamedDomainObjectContainer
4. Any listeners to the "live" collection are notified of the configured task 

### Current Behavior
1. Task is instantiated
2. Task is added to the NamedDomainObjectContainer
3. Any listeners to the "live" collection are notified of the task but it's not yet configured 
4. configurationClosure is executed to configure the task

### Context
Currently, the "live" methods on NamedDomainObjectContainer get notified too early so it's not possible to get the configured task in the listener. Ultimately this forces us to use the hacky `Project.afterEvaluate{...}` event to perform such actions.

Forum post here:
https://discuss.gradle.org/t/domain-collection-rules-get-applied-before-initialization/33394/5

### Steps to Reproduce 
```
tasks.matching { it.name.startsWith('example') }.all {
	println "before: name = $it.name, group = $it.group"
}
tasks.create(name: 'example1', group: 'group1')
tasks.create('example2') {
	group = 'group2'
}
tasks.matching { it.name.startsWith('example') }.all {
	println "after: name = $it.name, group = $it.group"
}
```
Output
```
before: name = example1, group = group1
before: name = example2, group = null
after: name = example1, group = group1
after: name = example2, group = group2
```

Notice how group is null for example2 in the "before" println above

### Offending Code
Ultimately, the problem can be traced to [these lines of code](https://github.com/gradle/gradle/blob/a138710ab109e271b17ee48dc49b359284cd3f66/subprojects/core/src/main/java/org/gradle/api/internal/AbstractPolymorphicDomainObjectContainer.java#L67-L69)
```java
    public <U extends T> U create(String name, Class<U> type, Action<? super U> configuration) {
        assertMutable("create(String, Class, Action)");
        assertCanAdd(name);
        U object = doCreate(name, type);
        add(object);
        if (configuration != null) {
            configuration.execute(object);
        }
        return object;
    }
```
Notice how `add(object)` is called before `configuration.execute(object);`

### Your Environment
```
------------------------------------------------------------
Gradle 5.6
------------------------------------------------------------

Build time:   2019-08-14 21:05:25 UTC
Revision:     f0b9d60906c7b8c42cd6c61a39ae7b74767bb012

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Windows 7 6.1 amd64
```

**Comment by big-guy** [comment]
Thanks for taking the time to write this up.  This is all intentional.  I know it seems like the given configuration closure  _should_ be the first thing called, but it's not meant to be used that way. The configuration order is always the order the configuration is added. This is consistent with all other configuration blocks for things outside of containers too, AFAIK. 

All of the closure taking `create(...)` and `register(...)` methods are equivalent to something like `closure.call(create(...))`, which means the closure can run after other configuration has already happened against the object.

If we made the configuration closure the first thing to run, this would break builds that rely on the current ordering in very hard to find ways, and I don't think there's a workable way to deprecate and migrate to a different behavior without new APIs. 

If @ddimtirov has a more complete example, it might uncover something else that's missing/wrong instead.  I haven't seen a good example of where new APIs that change this behavior would help over some other technique, but I'm interested to find otherwise.

**Comment by uklance** [comment]
Can you show me an example of when this behavior is desirable? It seems like a counter intuitive thing to do. Why would listeners want the object before it's configured?

**Comment by big-guy** [comment]
This is something we've discussed internally several times, but I think it boils down to a couple of things:

- To make build scripts work in the order they're written:
```
tasks.withType(SomeType) {
    someProp = "foo"
}

tasks.create("myfoo", SomeType) {
    someProp = "bar"
}

assert tasks.myfoo.someProp == "bar"
```
Obviously, `tasks.create(...)` could have been written as something like `tasks.create(...).configure { }` if the "run first" behavior was the default.

- A lot of the time, someone wants to "run first" to get ahead of some other configuration.  So we're more interested in having some kind of lifecycle/better context of what the configuration is intended for (conventions, just configuration, verification, etc).

This is partially what the `Provider`/`Property` APIs are supposed to help with.  They separate the reading (this property's value comes from here) and writing (this property's value _is_ this) aspects.  You can also set a value vs set a convention for a property.

**Comment by ddimtirov** [comment]
@big-guy, in this case I am implementing a plugin - in other words, if you `JavaExec` one of the recognized main class, you get predefined set of environment variables and defaulted working directory. 

The build users know about the `JavaExec` task, and would rather not learn new tasks if it can be avoided. The whole thing works if I apply the rule in `afterEvaluated` block, but as Lance pointed out in the forum that leads to weird behavior when overused, and I should be able to set it directly on the collection.

I appreciate that config logic that reacts to what has already been configured may be a bit smelly, but it is so convenient... It can be solved with the properties and providers mechanism, except that 2 years after their announcement most of the core tasks are still using direct getters and setters.
