### ISSUE TITLE
https://gradle.org/release-checksums/ as JSON

### ISSUE THREAD

**Issue by eighthave** [gradle/gradle#11099]
https://gradle.org/release-checksums/ provides essential data for verifying gradle binaries, that page looks like it is already produced in an automated way.  Please add this data as JSON or something machine readable format.

### Expected Behavior

https://gradle.org/release-checksums/index.json should contain all the data that is listed on https://gradle.org/release-checksums/

### Current Behavior

https://gradle.org/release-checksums/ is only HTML, so it has to be scraped in order to be used in automation.

### Context

This would be useful in many contexts, like:
* possible fix to #9361
*  automatically generating _gradle-wrapper.properties_ files
* pre-caching and verifying the gradle binaries on a corporate caching proxy

**Comment by big-guy** [comment]
I don't think we'll expose that specifically as JSON, but we have something similar here: https://services.gradle.org/versions/

**Comment by eighthave** [comment]
ah, that looks perfect thanks!  Maybe then just a link to
https://services.gradle.org/versions/all on
https://gradle.org/release-checksums so you don't get this question again :)

**Comment by eighthave** [comment]
So those JSON feeds are missing the "Complete" `-all.zip` binaries, there are just the wrapper JAR and the `-bin.zip` binaries there.  The "Complete" binaries are listed on the webpage.
