### ISSUE TITLE
Kotlin test fixtures aren't hooked up to compile with the main source set

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#11094]
Gradle 5.6.x.

This means I can't access anything marked as internal in `main` from `testFixtures`.

**Comment by eskatos** [comment]
The `testFixtures` Kotlin compilation tasks should be configured to be "friends" of the `main` compilation tasks for this to work. This is only possible with a public API starting with Kotlin Gradle Plugin 1.3.60 which is currently in EAP. See https://youtrack.jetbrains.com/issue/KT-20760

**Comment by big-guy** [comment]
I'm going to close this since it's an issue in the Kotlin Gradle plugin.
