### ISSUE TITLE
Pmd Plugin: Ability to use Pmd Java 13 Preview Feature Support

### ISSUE THREAD

**Issue by Koizumi85** [gradle/gradle#11107]
### Expected Behavior
Pmd has Java 13 Support since Version 6.18.0. For it to work one has to supply `--enable-preview` in environment variable `PMD_JAVA_OPTS` and to supply version `-version 13-preview`.
[See here for details.](https://pmd.github.io/pmd-6.18.0/pmd_release_notes.html#java-13-support)

I think a flag "enableJavaPreviewFeatures" which automatically adds the environment variable and the possibility to specify the language version would be enough to make this work without breaking anything of the current behaviour.

### Current Behavior
As far as I found, it is not possible to use the Java 13 Preview Feature Support of Pmd using the Pmd Plugin

### Context
With Java 12 and 13 two very nice language features have come to the Java World: Switch Expressions and Textblocks. But if you want to check classes compile with --enable-preview check, you have to use the flags described above. As both of these language features were long awaited by the Java community, I suppose there are a lot of people looking forward to use them and would be very happy to get this feature very soon. 

If you have any questions, I would be glad to help.

**Comment by Koizumi85** [comment]
any thoughts on this? I assume it will not be better with the current Java 14 release

**Comment by dragonjuggler** [comment]
I'm running into this issue with Java 15.  I can't find any documentation for how to pass --enable-preview and -version 13-preview.  Is there a resolution to this problem?

**Comment by McPringle** [comment]
Same problem here: A huge report with thousands of messages like:

`Pattern Matching for instanceof is only supported with Java 14 Preview and Java 15 Preview`

or

`Records are only supported with Java 14 Preview and Java 15 Preview`

or others. Every message contains a complete stacktrace. This report has around 23 MB, so we deactivated PMD on all of our projects. This is a great pity and hopefully only temporary. However, this issue is already well over a year old. Is it being worked on?

**Comment by namero999** [comment]
Considering that the gradle task is already executed with a suitable java configuration, such as

```java
tasks.withType(JavaCompile) {
    options.fork = true
    options.encoding = 'UTF-8'
    options.compilerArgs << '--enable-preview'
    sourceCompatibility = JavaVersion.VERSION_14
    targetCompatibility = JavaVersion.VERSION_14
}
```

maybe the plugin could simply acknowledge this configuration if no overrides are being introduced.
