### ISSUE TITLE
Gradle 2.14 timeout connecting to daemon on IBM JDK 8

### ISSUE THREAD

**Issue by dal-ibm** [gradle/gradle#1110]
Hello! This is a repeat of [bug GRADLE-3500](https://issues.gradle.org/browse/GRADLE-3500), which was [originally discussed here](https://discuss.gradle.org/t/gradle-2-14-daemon-doesnt-work-with-ibm-java-8/18311).

The bug has been fixed in Gradle 3.0-rc1, but persists in 2.14. I'm hoping for the fix to be ported to 2.14.

### Expected Behavior

A build in IBM Java 8 with Gradle 2.14 succeeds, rather than failing at the start.

### Current Behavior

Exactly as described in the [discussion thread](https://discuss.gradle.org/t/gradle-2-14-daemon-doesnt-work-with-ibm-java-8/18311): in short, daemon builds fail.

@ghale found that: "This is due to an issue with how we obtain the os-specific memory information from the OperationSystemMbean. For some reason, this blows up on IBM JDK8. I've changed this so that we do an mbean attribute lookup instead, and this seems to workaround the issue."

Setting `org.gradle.daemon=false` in the project's `gradle.properties` and/or using `--no-daemon` don't seem to affect the outcome: output very similar to that in the original "discuss" post is produced regardless. 

### Context

We'd like to be able to build Android code (library & app) with Gradle 2.14+, using the daemon.

Versions of [the Android plugin](https://bintray.com/android/android-tools/com.android.tools.build.gradle) past 2.1.2 rely on 2.14+, so we're stuck using v2.1.2 of the plugin and Gradle 2.13. The plugin is core to Android development. It does not ~use~ auto-configure Gradle 3 and I don't know if/when that's planned to change.

My understanding is that this affects all Android developers wanting to use the Gradle daemon on IBM JDK 8.

### Steps to Reproduce (for bugs)

[As discussed in the original bug report](https://discuss.gradle.org/t/gradle-2-14-daemon-doesnt-work-with-ibm-java-8/18311).

### Your Environment

I'd rather not provide a build scan unless it's strictly necessary - the build environment is slightly sensitive :)

Please let me know if the original thread, and the bug diagnosis by Gary Hale, require more information.

**Comment by eriwen** [comment]
@dal-ibm Thanks for the well-written issue. I regret to inform you that we will not be able to resolve your need directly soon; it's very unlikely we'll backport the fix to 2.14.x unless there's no Android plugin that uses Gradle 3+ for quite some time. For both our sakes I hope that doesn't happen :)

I'm putting this in the Icebox for now, just in case.

**Comment by dal-ibm** [comment]
Thanks for looking at this. Over the weekend I decided to try the Android plugin with Gradle 3.3, and they seem to work together just fine!

I haven't been able to find any recent documentation on this from the Android build-tools team (everything is either very old or references 2.14), but this is a satisfactory solution which doesn't require a code change.

Not sure how you guys sort issues or what the Icebox is, but I'm happy for this issue to be closed in light of this development.

**Comment by lacasseio** [comment]
Thanks @dal-ibm for coming back to us. As you experienced, the fix is implemented in Gradle 3.x series. Given what @eriwen said and how you worked around your current issue, I will close this issue as won't fix.
