### ISSUE TITLE
Will WorkAction work without a WorkParameter?

### ISSUE THREAD

**Issue by forestbat** [gradle/gradle#11108]
If I write this:
`workExecutor.noIsolation().sumbit(MyWorkAction.class,parameters->{})`
will this "MyWorkAction" work?

**Comment by big-guy** [comment]
Yes.  If your work action has no parameters, you can use `WorkParameters.NONE`: https://github.com/gradle/gradle/blob/28f54bab7d11a7077d85168f53dabd2ee72d862a/subprojects/workers/src/main/java/org/gradle/workers/WorkParameters.java#L47
