### ISSUE TITLE
Publishing task fails on gradle 6.0-rc-1, working on 5.6.3 with Metadata publishing enabled

### ISSUE THREAD

**Issue by mvignale1987** [gradle/gradle#11116]
In a basic Android library, with Gradle Module Metadata enabled, when executing for instance `./gradlew publishToMavenLocal` it fails and it doesnt deploy any artifact and doesnt generate the `.module` file

This happens only on gradle 6.0-rc-1, on gradle 5.6.3 works fine and generates the `.module` file accordingly.

### Expected Behavior
Artifacts should be published and `.module` file should be created

### Current Behavior
task `generateMetadataFileForXXXPublication` fails with this error

Execution failed for task ':lib:generateMetadataFileForXXXPublication'.
> Invalid publication 'aar':
    - Variants 'releaseApiPublication' and 'releaseApiPublicationAar' have the same attributes and capabilities. Please make sure either attributes or capabilities are different.
    - Variants 'releaseRuntimePublication' and 'releaseRuntimePublicationAar' have the same attributes and capabilities. Please make sure either attributes or capabilities are different.

I searched around the issues and didnt find anything related, if there is any additional information I can add please tell me so, I am adding a build scan URL if it is useful.

Build scan URL:
https://gradle.com/s/t4mpicr7eempm

Thanks! Regards

Mauricio Vignale

**Comment by jjohannes** [comment]
Which AGP version are you using?

There is an issue at AGP about this already and it will be fixed on their side: https://issuetracker.google.com/issues/142543668

You can work around this for now like this:

```

aarComponent.withVariantsFromConfiguration(releaseApiPublicationAar) {
  if (it.configurationVariant.artifacts.isEmpty()) { it.skip() }
}
aarComponent.withVariantsFromConfiguration(releaseRuntimePublicationAar) {
  if (it.configurationVariant.artifacts.isEmpty()) { it.skip() }
}
```

**Comment by mvignale1987** [comment]
I tested this with AGP 3.6.0-beta01 and also with the new 4.0.0-alpha01 that was just released, both with the same output.
the workaround isn't working for me at the moment, but checking on the issue it totally seems like it is an issue from the AGP and not from gradle itself

I don't know if we should close this bug as it could be helpful to someone what do you think?

**Comment by jjohannes** [comment]
We can keep the issue open until it is fixed in AGP.
Sorry I wrote down the workaround without testing it. Some details were wrong. I updated it in my comment above. It should work like that.

**Comment by mvignale1987** [comment]
It happens that I had already tested exactly just that, but with one key omission, I was trying to remove the `releaseXXXPublicationAar` and not the other ones, removing the ones without Aar suffix worked like a charm :)

Just in case for any visitors here is the snippet for kotlin-dsl

`
val debugComponent = components["debug"] as AdhocComponentWithVariants
        debugComponent.withVariantsFromConfiguration(configurations["debugApiPublication"]) {
            if (configurationVariant.artifacts.isEmpty()) { skip() }
        }
        debugComponent.withVariantsFromConfiguration(configurations["debugRuntimePublication"]) {
            if (configurationVariant.artifacts.isEmpty()) { skip() }
        }
`

**Comment by carlonzo** [comment]
or with this you can apply the above workaround to all the components:

```
afterEvaluate {

    components
            .findAll { it instanceof AdhocComponentWithVariants }
            .forEach {
                it.withVariantsFromConfiguration(configurations.findByName("${it.name}ApiPublication")) {
                    if (configurationVariant.artifacts.isEmpty()) {
                        skip()
                    }
                }
                it.withVariantsFromConfiguration(configurations.findByName("${it.name}RuntimePublication")) {
                    if (configurationVariant.artifacts.isEmpty()) {
                        skip()
                    }
                }
            }
}
```

**Comment by efemoney** [comment]
AGP 3.6.0-beta05 has been released which claims to have fixed this. Worth checking it out so we can close this issue.

**Comment by jjohannes** [comment]
Thanks. Works as expected with `AGP 3.6.0-beta05`. Closing this.
