### ISSUE TITLE
Gradle Distribution cache includes URI user info

### ISSUE THREAD

**Issue by gatesn** [gradle/gradle#11120]
### Expected Behavior
Expect Gradle Wrapper to see a cache hit even if the username / password changes for a distribution URI. 

### Current Behavior
The distribution cache is keyed by the full URI: https://github.com/gradle/gradle/blob/5092c763e528cc46bbaccb259a9fb6f11894eca7/subprojects/wrapper/src/main/java/org/gradle/wrapper/PathAssembler.java#L49

### Context

We mirror Gradle distributions behind an authenticated server. The authentication is token-based, but jammed into the basic auth password field. These tokens expire every day.

We already have a mechanism for refreshing tokens on the user's machines, however every day they need to download a new Gradle distribution since the cache key changes.

**Comment by big-guy** [comment]
This is a good catch.  Would you be interested in contributing a fix?

We have a `Download.safeUri` that can be used to strip the user credentials.
