### ISSUE TITLE
Nondeterministic behavior of application plugin convention mapping

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#11125]
### Context

Today when I'm investigation an issue https://github.com/gradle/gradle/issues/11124 , it's surprising that a property returned by convention mapping is nondeterministic. See the following script:

```
            plugins {
                id 'application'
            }

            mainClassName = "my.module/io.greeting.HelloWorld"

            run {
                doFirst {
                    main = ''
                    assert main == "my.module/io.greeting.HelloWorld"
                    throw new StopExecutionException()
                }
            }
```

Run this several times you'll see the different output. On my computer, I get the flaky behavior:

```
$ gradleDev run
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

BUILD SUCCESSFUL in 3s
2 actionable tasks: 1 executed, 1 up-to-date
 
$ gradleDev run
Starting a Gradle Daemon, 2 incompatible and 7 stopped Daemons could not be reused, use --status for details
> Task :run FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/zhb/Projects/gradle/subprojects/core/build/tmp/test files/JvmOptionsIntegrationTest/build_a_legal_comma...ain_Class/vfoud/build.gradle' line: 11

* What went wrong:
Execution failed for task ':run'.
> assert main == "my.module/io.greeting.HelloWorld"
         |    |
         ''   false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
2 actionable tasks: 1 executed, 1 up-to-date
```

Maybe this is due to memory visibility in multithread environment?

IIUC, Gradle heavily uses convention mapping, so this might be a big issue.

**Comment by lacasseio** [comment]
We should really just change everything for the Provider API.

**Comment by adammurdoch** [comment]
The assertion failure is what we would expect to see, as the value of main will continue to be the empty string once the value has been set. You might double check that the `run` task is actually running and not being skipped (eg is up-to-date) when the build succeeds.

**Comment by blindpirate** [comment]
I think  `JavaExec` is never up-to-date, right? I tried with `--console=plain` and I'm pretty sure they're executed.

```
# zhb @ bs-MacBook-Pro in ~/Projects/tmp/issue-11125 [11:47:25] C:1
$ gradleDev run --console=plain
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :run FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/zhb/Projects/tmp/issue-11125/build.gradle' line: 10

* What went wrong:
Execution failed for task ':run'.
> assert main == "my.module/io.greeting.HelloWorld"
         |    |
         ''   false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 490ms
1 actionable task: 1 executed

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/issue-11125 [11:47:45] C:130
$ mkdir -p ../userhome

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/issue-11125 [11:47:57]
$ gradleDev run --console=plain --gradle-user-home=../userhome

Welcome to Gradle 6.1-20191024082226+0000!

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :run

BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/issue-11125 [11:48:09]
$ gradleDev run --console=plain --gradle-user-home=../userhome
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :run

BUILD SUCCESSFUL in 488ms
1 actionable task: 1 executed

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/issue-11125 [11:48:22]
$ gradleDev run --console=plain
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :run FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/zhb/Projects/tmp/issue-11125/build.gradle' line: 10

* What went wrong:
Execution failed for task ':run'.
> assert main == "my.module/io.greeting.HelloWorld"
         |    |
         ''   false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 486ms
1 actionable task: 1 executed
```

**Comment by adammurdoch** [comment]
Perhaps put some logging in the `doFirst { }` action to make sure that the assignment and assertion code is actually running each time.

**Comment by lingocoder** [comment]
> „*...Perhaps put some logging in the `doFirst { }` action to make sure that the assignment and assertion code is actually running each time....*“

I do precisely that @adammurdoch, in the ***Steps to Reproduce*** section of [*this very closely-related bug I reported a couple months ago*](https://github.com/gradle/gradle/issues/10412).

The details in #10412 might be helpful to you @blindpirate. The ***TL;DR*** of those details, is:  *I only ever encountered the *`:run main`* bug when I was running tests in TestKit*. And, like what you're seeing, it sometimes happened and sometimes didn't.

**Comment by lingocoder** [comment]
Another very peculiar thing I just remembered that's probably worth mentioning, @blindpirate, @lacasseio @adammurdoch: When I was troubleshooting #10402 back in August, stepping through the debugger I could see the property value for *`main`* set on the appropriate object(*s*) — *all the way from the build script, through the TestKit framework, through the plugin, object, the extension object, and right through the inner guts of Gradle. And back*. 

I show some of that route in the screenshots of #10402.

But the second TestKit went to check the result, *Poof!* The value had magically disappeared! Right before my eyes. Seeing a bug like that playing out in real time, I gotta tell ya, although frustrating as all hell, it is actually a pretty fascinating thing to witness.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/1164
