### ISSUE TITLE
Removing output does not trigger rerun in (at least) 5.6.2 / 5.6.3

### ISSUE THREAD

**Issue by shabunc** [gradle/gradle#11136]
### Expected Behavior

Whenever I remove output task should be triggered. 

### Current Behavior

In a task with output the task is not running when output has been removed. 

### Context

I have a task that generates specific artifact that I need further in tests. However when I've switched to gradle 5.6.3 my tests started to fail on my local machine even after `gradle clean` - because all inputs are actually belong to source repository and since they are not changed - the task is just not triggered.

### Steps to Reproduce 

1. git clone https://github.com/Kotlin/dukat.git
2. ./gradlew wrapper --gradle-version 5.6.3
3. ./gradlew generateBinary
4.  du ./compiler/build/declarations.dukat
5. rm ./compiler/build/declarations.dukat
6.  ./gradlew generateBinary
7.  du ./compiler/build/declarations.dukat

### Your Environment

MacOS. Sorry, I don't have a gradle scan.

**Comment by big-guy** [comment]
@wolfs anything new in 5.6.x that could cause this?

**Comment by lptr** [comment]
I'm not sure what I should be seeing here. This is what I get in when I run `du` the second time:

```console
$ du ./compiler/build/declarations.dukat
18352	./compiler/build/declarations.dukat
```

Looks like everything is rebuilt as expected. What am I missing?

**Comment by lptr** [comment]
Closing this as everything seems to be in order. Please reopen if necessary.
