### ISSUE TITLE
Add provider API support to AttributeContainer

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#11139]
This would be good to have:

`AttributeContainer.attribute(attribute(Attribute<T> key, Provider<T> value)`

With Gradle Module Metadata, library authors and plugin authors (sometimes also authors of consuming builds) will need to use the Attributes API more often. Sometimes, lazy evaluation would be advantageous.

**Comment by melix** [comment]
I tried to spike this in the past, in particular as a way to perform lazy computation of the target java platform attribute. It turned out to be quite hard, because of the performance aspect (attribute factory is memory optimized) and the conversion to immutable attributes.

**Comment by jjohannes** [comment]
Maybe we can treat the values that come in via providers separate until we make the container immutable. These are then only the user provided attributes and it should not have an impact on performance of other cases.

**Comment by melix** [comment]
This would totally defeat the attribute container factory, which is basically a tree. All providers would lead to a different entry.

**Comment by jjohannes** [comment]
We are plan to add higher level APIs (https://github.com/gradle/gradle/issues/9834 and related) which shall use providers/properties. It's maybe not needed anymore to make this "low level" API extension.
