### ISSUE TITLE
Gradle daemons caching certs is unclear to troubleshoot

### ISSUE THREAD

**Issue by A-Tran** [gradle/gradle#11143]
Running gradle prior to cert updates end up caching the old certs, and is difficult to troubleshoot if you don't know that it's happening.

**Comment by jrodbx** [comment]
FWIW, this happened again today during a new hire onboarding.

**Comment by jrodbx** [comment]
FWIW, this is still an issue.

**Comment by ljacomet** [comment]
While I can understand this is confusing, the Gradle daemon runs inside a JVM. If you update environmental settings that a running JVM does not detect as changed, it is unlikely we will add this monitoring to the daemon itself.
