### ISSUE TITLE
Support service injection for TransformActions

### ISSUE THREAD

**Issue by britter** [gradle/gradle#11147]
### Expected Behavior

The available services documented in the [user manual](https://docs.gradle.org/current/userguide/custom_gradle_types.html#services_for_injection) should be available in `TransformAction`s.

### Current Behavior

`TransformAction`s currently cannot receive services like `FileSystemOperations`.

### Context

I'm trying to use a `TransformAction` to extract the Jacoco Agent Jar out of the Jacoco library in the Jacoco plugin and `FileOperations` would come in very handy here. See https://github.com/gradle/gradle/pull/11148

**Comment by lptr** [comment]
Hi @britter. It's unlikely we are going to get to this anytime soon. Would you care to add a PR?

**Comment by wolfs** [comment]
Note two things:
- We don't really want to support injecting things in the constructor. We try to use getter injection everywhere.
- Even if we support the services currently injected for the Worker API, you won't be able to unzip an archive with them. Currently only `ObjectFactory`, `FileSystemOperations`, `ExecOperations`, `ProjectLayout` and `ProviderFactory` are supported (see the [user manual](https://docs.gradle.org/current/userguide/custom_gradle_types.html#service_injection)). So to make your use-case better, more methods would need to be added to `FileSystemOperations` as well.

**Comment by adammurdoch** [comment]
When we implement this, please do not make `ProjectLayout` available to transform actions (https://github.com/gradle/gradle/issues/11434) or to any isolated object.

**Comment by wolfs** [comment]
Hmmm... Why is `ProjectLayout` supported for worker actions? https://github.com/gradle/gradle/blob/77b95b655f184f089050e97bfab6e324fe5e51ab/subprojects/workers/src/main/java/org/gradle/workers/internal/WorkerPublicServicesBuilder.java#L48

**Comment by wolfs** [comment]
Ah, got it, that is what https://github.com/gradle/gradle/issues/11434 is about.

**Comment by adammurdoch** [comment]
The same set of services are now available for transform actions, worker API actions and build services: https://github.com/gradle/gradle/pull/11759
