### ISSUE TITLE
Error in version-range resolution

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#11145]
This happens with Gradle 5.6.3:

```
> Task :dependencies FAILED

------------------------------------------------------------
Root project
------------------------------------------------------------

libtest0
\--- org.eclipse.emf:ecore:2.3.0-v200706262000
     +--- org.eclipse.core:runtime:[3.3.0,4.0.0) -> 3.10.0-v20140318-2214
     |    +--- org.eclipse:osgi:[3.7.0,4.0.0) -> 3.10.0-v20140606-1445
     |    +--- org.eclipse.equinox:common:[3.6.100,4.0.0) -> 3.6.200-v20130402-1505
     |    +--- org.eclipse.core:jobs:[3.2.0,4.0.0) -> 3.6.0-v20140424-0053
     |    |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
     |    +--- org.eclipse.equinox:registry:[3.4.0,4.0.0) -> 3.5.400-v20140428-1507
     |    |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
     |    +--- org.eclipse.equinox:preferences:[3.4.0,4.0.0) -> 3.5.200-v20140224-1527
     |    |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
     |    +--- org.eclipse.core:contenttype:[3.3.0,4.0.0) -> 3.4.200-v20140207-1251
     |    |    +--- org.eclipse.equinox:preferences:[3.2.0,4.0.0) -> 3.5.200-v20140224-1527 (*)
     |    |    +--- org.eclipse.equinox:registry:[3.2.0,4.0.0) -> 3.5.400-v20140428-1507 (*)
     |    |    \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
     |    \--- org.eclipse.equinox:app:[1.0.0,) -> 1.3.200-v20130910-1609
     |         +--- org.eclipse.equinox:registry:[3.4.0,4.0.0) -> 3.5.400-v20140428-1507 (*)
     |         \--- org.eclipse.equinox:common:[3.2.0,4.0.0) -> 3.6.200-v20130402-1505
     \--- org.eclipse.emf:common:[2.3.0,3.0.0) FAILED

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencies'.
> Could not resolve all files for configuration ':libtest0'.
   > Could not find any version that matches org.eclipse.emf:common:[2.3.0,3.0.0).
     Versions that do not match:
       - 2.3.0-v200706262000
       - 2.1.0
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/emf/common/maven-metadata.xml
     Required by:
         project : > org.eclipse.emf:ecore:2.3.0-v200706262000

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
1 actionable task: 1 executed
```

While imho publishing with a version range is bad practice, I guess it should still work properly.
And as `[2.3.0,3.0.0)` means `>= 2.3.0 && < 3.0.0`, I wonder that `2.3.0-v200706262000` is not be considered eligible.

**Comment by ljacomet** [comment]
While it may be confusing, and we've had a number of reports / questions on this topic recently, this is expected and has been like that for a long time.

The problem, [as documented](https://docs.gradle.org/6.0-rc-1/userguide/single_versions.html#version_ordering), is that a version 1.1.0-a is always considered inferior to 1.1.0.
This causes two usability issues in ranges:
* 1.1.0-a is _excluded_ from a range that starts with `[1.1.0,...`
* 1.1.0-a is _included_ in a range that ends with `...,1.1.0)`

We had discussions to adapt this to make it behave more like expected but there is the complicating factor of the behavior change this would introduce.

A trick to work around the current scheme would be to transform the range bounds and suffix them with a `-a` that would then be lower than pretty much all variations of said root version.

**Comment by Vampire** [comment]
Oh, that's bad of course.
Atually something like `2.3.4-alpha1` or `2.3.4-rc1` is probably correct to be lower than `2.3.4`, while `2.3.4.sp1` should probably be greater.
Also if the defined range is `...,2.3.4)` to support anything before `2.3.4` it is probably unnice that you get `2.3.4-alpha1` as resolution result.

Actually imho this just underlines that you shouldn't publish metadata that defines a range.
And that you shouldn't publish pre-releases to something like maven central but into a separate pre-releases repository.

This can probably hardly be done "correctly".
But I guess most intuitive would be to assume most people follow the rule to not release pre-releases to a release repository, but yeah, it would change resolution results of course. :-/
