### ISSUE TITLE
Allow excluding files from published Java components

### ISSUE THREAD

**Issue by eyalroth** [gradle/gradle#11150]
When configuring a Java publication, one may wish to exclude certain files from the main published JAR, but _not_ from the build; i.e, an application (fat JAR) generated in the build would contain the file, but the published ("slim") JAR would not.

One particular use case for this is making use of sensitive resource files in local development, but referring from publishing them to a public repository.

### Expected Behavior
```groovy
publishing {
    publications {
        api(MavenPublication) {
            from components.java
            exclude 'secret.txt'
        }
    }
}
```

### Current Behavior
In order to exclude files one can create a custom JAR artifact, but the problem is that the generated POM will be lacking all of the dependencies. This is especially noticeable in multi-module projects.

There is a workaround for this, but it is quite messy. It involved declaring a second internal publication based on `from components.java`, which is used only to generate the POM and "copy" it to the publication with the custom JAR:

```groovy
task apiJar(type: Jar) {
    from sourceSets.main.output
    exclude 'secret.txt'
}

publishing {
    publications {
        def pomString = null

        internal(MavenPublication) {
            from components.java
            pom.withXml {
                pomString = asString().toString()
            }
        }

        api(MavenPublication) {
            artifact apiJar
            pom.withXml {
                def builder = asString()
                builder.delete(0, builder.length())
                builder.append(pomString)
            }
        }
    }
}

generatePomFileForApiPublication.dependsOn(generatePomFileForInternalPublication)
```

### Context

This has been brought up [on StackOverflow](https://stackoverflow.com/questions/37171372/) as well.

**Comment by eyalroth** [comment]
I like you too @stale bot.

**Comment by eyalroth** [comment]
Ahh stale bot my old frenemy.

**Comment by jvandort** [comment]
Excluding entries from a published archive _in this way_ will likely never be possible in Gradle. Conceptually, publishing is not aware of the contents of the artifacts it is publishing. If you wish to publish a modified artifact compared to the "normal" one, that modification should be done at the time of _building_ that artifact. In general, publishing should be transparent -- publishing exactly the component which is declared on `from`. If you wish to change what is published, the `components.java` should be updated to reflect that.
