### ISSUE TITLE
Break when the java or java-library is applied after java-platform is applied

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#11162]
The opposite already breaks since the introduction of `java-platform`. However doing it as in the title was only deprecated so far.

Plugin application result should not be order dependent, so this difference should be removed.

**Comment by melix** [comment]
While I reckon it's a good thing to have, it's something we shouldn't add in a 2d rc.

**Comment by ljacomet** [comment]
The current state is that it does not throw, but the end project is not really usable due to the way it is setup.
We were conservative when detecting the problem back in 5.3, and missed it during the 6.0 phase. I would rather not wait 7.0 to make this change though.

**Comment by melix** [comment]
I understand. However, the more we add to RCs, the longer the delay. We should absolutely think about what is strictly necessary to unblock the RC. Otherwise it's tempting to any team to add more things and never stabilize.

**Comment by ljacomet** [comment]
Ok, I see your point. I have removed the target milestone so that it does not hold RC2 back. BUt I suggest merging it, if it can get a positive review _before_ RC2.
Makes sense?

**Comment by jjohannes** [comment]
I think this should be 6.0, because it was planned and we just overlooked it. And it is technically a breaking change. So while I would have moved a similar change (not breaking) from lets say 6.1 to 6.2 in this phase, for a major release like this one I think this change should go in.
