### ISSUE TITLE
Inconsistent `sysProp.*` with `buildSrc` subproject

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#11173]
When attempting to access a system property defined in `gradle.properties` file from build script of `buildSrc` subproject, it may be available or not depending on how Gradle is started (command line, wrapper script, tooling API call).

### Expected Behavior
for a system property defined in `gradle.properties`, it should be visible or not regardless of how the Gradle was invoked.

### Current Behavior
in attached projects, for project `gradle-buildSrc-sysprop`
 * with a local gradle distribution
```
gradle projects -> 
   buildSrc akey = null
   rootProject akey = a_val
```
* with a tooling API client `gradle-buildSrc-sysprop-tapi`
```
./gradlew run ->
  buildSrc akey = null
  rootProject akey = a_val
```
* but with wrapper script
```
./gradlew projects ->
  buildSrc akey = a_val
  rootProject akey = a_val
```

### Context
a user attempted to extract common configuration to `gradle.properties`, this caused import failure for Android Studio https://issuetracker.google.com/issues/142669429

### Steps to Reproduce 
attaching the archive with demo project + demo TAPI client.

### Your Environment
OS Windows
Jdk: Amazon Coretto 1.8.0_222

Build scan URL:
* https://scans.gradle.com/s/rjsmv4hfe54m2 - running with local distribution: `gradle help`
* https://scans.gradle.com/s/vs76bdaq4mjnc - running with wrapper: `./gradlew help`

**Comment by nskvortsov** [comment]
sample project [buildSrc-sysprop.zip](https://github.com/gradle/gradle/files/3784956/buildSrc-sysprop.zip)

**Comment by donat** [comment]
@wolfs I've checked the provided sample and the issue you referenced covers this report. The Gradle wrapper loads the system properties from the `gradle.properties` file before launching Gradle, which does not happen when an installed distribution or the TAPI is used.

There's no inconsistency when project properties are declared in `gradle.properties`.

**Comment by eskatos** [comment]
@donat, note that with Gradle 6.0 the issue described here can't be reproduced when using an installed distro, but it can be using a TAPI client.

**Comment by donat** [comment]
@eskatos I've experimented further with the sample project from above and tested it against multiple Gradle versions. You are right, the behavior is changed in Gradle 6.0. Fortunately, the change made Gradle's behavior consistent:
```
[donat@Tiamat /Development/samples/gradle-11173]$ ./run-all.sh 
Gradle 6.0-rc-3 + local installation
  system_property_available in buildSrc:  true 
  project_property_available in buildSrc: false 
  system_property_available in root:      true 
  project_property_available in root:     true 
Gradle 6.0-rc-3 + TAPI
  system_property_available in buildSrc:  true 
  project_property_available in buildSrc: false 
  system_property_available in root:      true 
  project_property_available in root:     true 
Gradle 6.0-rc-3 + wrapper
  system_property_available in buildSrc:  true 
  project_property_available in buildSrc: false 
  system_property_available in root:      true 
  project_property_available in root:     true 
```

**Comment by wolfs** [comment]
@donat What about included builds? Do they expose the same behaviour as `buildSrc` now? That would meant that they wouldn't have access to project properties neither.

**Comment by donat** [comment]
With Gradle 6.0, included builds also behave consistently. The included build has access to the system properties from the root project's `gradle.properties` file but not to the project properties. The same is true for `buildSrc` inside the included build.

**Comment by donat** [comment]
We added an integration test to Gradle to avoid future regressions: https://github.com/gradle/gradle/pull/11357
