### ISSUE TITLE
[Jacoco plugin] Consider to fall back to defaults if user provided dependencies do not resolve to jacoco

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#11209]
When adding a platform as a dependency to a configuration, `defaultDependencies` does not run, even if it is the only dependency.

### Expected Behavior

Since a platform can only define constraints, not actual dependencies, it should not prevent `defaultDependencies` from running.

### Current Behavior

When the only dependency is a platform, `Configuration.defaultDependencies` is not run.

### Context

In a project using the `jacoco` plugin, a construct like this attempting to apply a platform to all configurations in a project

```kotlin
configurations.configureEach {
  dependencies.add(configuration.name, platform(project(":platform")))
}
```

The project fails to run tests with this error message

```
> Task :project:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project:test'.
> Expected configuration ':project:jacocoAgent' to contain exactly one file, however, it contains no files.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Perhaps applying a platform to all configurations like that is not a good pattern (open to suggestions). However, applying a platform to jacoco configurations to manage their versions along with all other versions in a platform, as opposed to having to set the version in the jacoco extension, seems like a valid use case.

Even if this is not considered a valid use case, the error message is too confusing to understand the relationship to the problem (adding platforms to the jacoco configuration isn't supported). In that case, I'd recommend updating the Jacoco plugin to understand this case and provide a better error message or behavior, possibly using `withDependencies`.

### Steps to Reproduce 

https://github.com/anuraaga/gradle-platform-default-dependencies

`./gradlew test jacocoTestReport`

### Your Environment

Gradle 6.0-rc-2, Windows, Java 13 (zulu)

**Comment by jjohannes** [comment]
I have to disagree with the initial reasoning. :)

In Gradle, a _platform dependency_ is a dependency as every other dependency. The _platform()_ only decides what to pick from the thing you depend on. With _variant-aware dependency management_ each component can have multiple variants. `platform()` only says that we want to pick **a** _platform variant_. In theory, the targeted component can have both _platform_ and _library_ variants. And a `java-platform` can also have dependencies with `allowDependencies()`.

For the concrete use case:
Adding the dependency to `jacocoorg.jacoco:org.jacoco.agent` (without version) should fix the problem - `jacocoAgent("jacocoorg.jacoco:org.jacoco.agent")`.

**Comment by anuraaga** [comment]
I understand those semantics for platform dependencies, which does make sense. But it makes me feel that in such a case, `defaultDependencies` loses a lot of it's purpose - what is a good pattern for it with the presence of platforms? As you say, "The platform() only decides what to pick from the thing you depend on" so it seems it should still run when there are only platforms, to give a chance to decide the things you depend on.

Also, I did use adding the dependencies like you mentioned as a workaround (before really understanding what was going on). At some point of version upgrades or something, I ended up with a jacoco error of "configuration resolved to two files" :( I'm still not sure why that happened but assumed my workaround was bad in the first place and finally looked at the jacoco code to see defaultDependencies and thought it is a bad interaction with it and platform.

Anyways, my 2c and additional observation of having a weird issue with that workaround. Either way I'd be happy enough if Jacoco plugin gave a less cryptic error :)

**Comment by jjohannes** [comment]
> "configuration resolved to two files"

Would be interesting to know what the other file was there. Maybe this is something that could be improved in how this is done in JaCoCo. There is a PR attempting to improve things here already (#11148) and maybe this can be taken into account if we better understand the problem. We can certainly think about improving the error message.

>  `defaultDependencies` loses a lot of its purpose - what is a good pattern for it with the presence of platforms?

In my mind the usage for `defaultDependencies` is limited to very specific use cases already. The moment a decision is made to use the _defaults_ is before Gradle knows what the declared dependencies will resolve to.

My recommendation would be to not rely on `defaultDependencies` at all. There are other options to add a "default" like the one you expected here.
I.e. the JaCoCo plugin could fall back to the default if an error occurs **after** resolution.
Or you can use `Configuration.withDependencies {}`, where you can also add "defaults" after inspecting what was declared. There is no "one-fit-all" solution here in my opinion.

**Comment by anuraaga** [comment]
I agree with the reasoning and that there seem to be very few use cases for `defaultDependencies`. So does it make sense to rename this issue to focus on jacoco - `Jacoco plugin should fall back to defaults if user provided dependencies don't resolve to jacoco`?

**Comment by jjohannes** [comment]
Yes. Please rename the issue @anuraaga.
