### ISSUE TITLE
Missing packaging causes gradle to skip checking other repositories

### ISSUE THREAD

**Issue by DDesideria** [gradle/gradle#1120]
Issue occurs when a dependency with same name is found in repository which but the required packaging is missing.

Example: 
1) Project requires dependency 'group:projectA:1.2' with packaging 'jar' and defines repositories 'repo1' and 'repo2' (in respective order) in build.gradle
2) Both repositories contain 'group:projectA:1.2', but only repo2 contains needed packaging ('jar') in this case

Please see integration test for reference (note: code might be inaccurate, but should give basic idea)

    package org.gradle.integtests.resolve.maven

    import org.gradle.integtests.fixtures.AbstractHttpDependencyResolutionTest

    class MavenBrokenRemoteResolveIntegrationTest extends          org.gradle.integtests.fixtures.AbstractHttpDependencyResolutionTest {
        // existing tests skipped
        public void "reports and recovers from missing artifact packaging"() {
            given:
            def repo1 = mavenHttpRepo("repo1")
            def repo2 = mavenHttpRepo("repo2")
            def module1 = repo1.module("group", "projectA", "1.2").publish()
            def module2 = repo2.module("group", "projectA", "1.2").publish()

           buildFile << """
              repositories {
                  maven { url "${repo1.uri}"}
                  maven { url "${repo2.uri}"}
              }
              configurations { present }
              dependencies {
                  present 'group:projectA:1.2'
              }
              task resolvedFiles { doLast { println configurations.present.files } }
          """

          when:
          module1.pom.expectDownload()
          module1.artifact.expectDownloadBroken()
          // same behavior if uncomment following:
          // module1.artifact.expectDownloadMissing()
          module2.pom.expectDownload()
          module2.artifact.expectDownload()
          then:
          succeeds("resolvedFiles")
      }
    }

### Expected Behavior
Dependency is resolved successfully by checking 'repo2'
### Current Behavior
Build fails and gradle doesn't try to check other repositories
### Context
Currently I've faced the issue 2 times:
1) Tampered private artifactory: pom.xml contains correct packaging, but jar is unavailabe (404 error)
2) Different packagings for same artifact 'com.viewpagerindicator:library:2.4.1@aar':
    jcenter() contains only apklib packaging, while on maven { url "http://dl.bintray.com/populov/maven" } required packaging is available

### Your Environment
Gradle 3.3

If the behavior is expected I would appreciate a workaround, since currently I am forced to shuffle repos order to get artifact cached locally.

**Comment by DDesideria** [comment]
Also seems to be related to https://issues.gradle.org/browse/GRADLE-1066

**Comment by DDesideria** [comment]
Ok, seems that I found a workaround:
    repositories {
                maven { 
                    url "${repo1.uri}" 
                    artifactUrls "${repo2.uri}" 
                }
                maven { url "${repo2.uri}"}
    }

This works if 'repo1' is missing artifact

**Comment by big-guy** [comment]
Why does repo1 have the metadata but not the artifact?

Since Gradle finds metadata in the first repo, it uses that repo for the artifact too.

**Comment by DDesideria** [comment]
I listed 2 issues. Let me clarify a bit:
1) Issues with proper sync of the artifactory. For performance reasons our company uses local artifactory which contains all the artifacts required by different teams. But sometimes the sync fails resulting in missing files. In this case the gradle works more predictably - the pom really does list correct metadata but not the jar.
2) Example with 'com.viewpagerindicator:library:2.4.1' is more interesting: the original library was deprecated, but the corresponding tooling (android plugin) has changed the format of the artifact 
(from apklib to aar). But the author of the library never repackaged it, so some other guy just published repackaged artifact with same id and version but with in different format. 
In this case even the metadata is different so I was expecting gradle to look for artifact in other repository. You can compare them: http://dl.bintray.com/populov/maven/com/viewpagerindicator/library/2.4.1/library-2.4.1.pom
https://jcenter.bintray.com/com/viewpagerindicator/library/2.4.1/library-2.4.1.pom

3) Third issue is imaginary, but I believe this scenario might theoretically occur:
     one might list several repositories just for the sake of reliability, with the hope that in case of connection error gradle will recover and use the second repository.

**Comment by oehme** [comment]
This is working as expected. If the metadata of a module is found in a repository, the artifact is expected to be in that repository as well. Otherwise a failed deployment in repo1 could lead Gradle to fall through to repo2, which might not have the same security level etc.

**Comment by ohuohuo** [comment]
it seems this issue is still there with even the newest version, 4.4

**Comment by cyberpwnn** [comment]
For me it only stupidly checks the first repository about 4 times, not finding metadata or anything, completely ignores the other repositories.

**Comment by mattiasflodin** [comment]
This also happens if the DNS name doesn't resolve. How do I set up repositories so that one is a fallback for the other?
