### ISSUE TITLE
Make maven-publish incremental

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#11203]
Please make the `maven-publish` plugin incremental.

I understand that when *publishing* to a maven repository, this part of the task faces difficulty with incremental work as it is a shared directory. But when generating the files **to be published** - they don't need to be generated again if they have already been generated (maybe they can be cached somewhere and skip the republishing of the same files).

Additionally, my use case is that I am not publishing to a shared maven repo - but to a local build directory.  As an Android developer, I publish to each module's local build directory - `build/maven-publish/<variant-name>`. I then utilize a couple of `Sync` tasks to merge each of the respective output directories into the final artifact we deploy.

Unfortunately, the lack of incrementality of the `build/maven-publish/<variant-name>` publishing, even though it's not a shared directory (only the publish task's output goes there) causes all the downstream `Sync` tasks to be considered out of date.

**Comment by ZakTaccardi** [comment]
Diving into this task a bit more, the issue is this:

```
17:52:49.122 [INFO] [org.gradle.internal.execution.steps.SkipUpToDateStep] Task ':favorite-color:deleteDebugLocalBuildDirRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.

```

```
18:17:56.985 [INFO] [org.gradle.internal.execution.steps.SkipUpToDateStep] Task ':favorite-color:assembleDebugArtifact' is not up-to-date because:
  Input property 'rootSpec$1' file /../git/gradle-maven-upload/favorite-color/build/maven-publish/debug/com/test/maven/upload/favorites/favorite-color-debug/maven-metadata.xml has changed.
  Input property 'rootSpec$1' file /../git/gradle-maven-upload/favorite-color/build/maven-publish/debug/com/test/maven/upload/favorites/favorite-color-debug/maven-metadata.xml.md5 has changed.
  Input property 'rootSpec$1' file /../git/gradle-maven-upload/favorite-color/build/maven-publish/debug/com/test/maven/upload/favorites/favorite-color-debug/maven-metadata.xml.sha1 has changed.
```

What changed in `maven-metadata.xml`?

```
<lastUpdated>20191106231756</lastUpdated>
```
became:
```
<lastUpdated>20191106232025</lastUpdated>
```

Ideally, the timestamp would be injectable, or better yet, reused between executions when the inputs have not changed.

Preparing the artifacts (what gets published) vs publishing them to an external repo are two separate steps. This would allow the artifacts to be re-used and cached between executions.

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
This is a valid issue. 

Short of skipping the publish task, It seems like we could not update maven-metadata.xml if nothing has changed for local repositories. 

As another alternative, `Sync` could be updated to be smarter and only copy what actually changed.
