### ISSUE TITLE
Platform dependency on published BOM does not apply transitive BOM dependencies

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#11208]
When creating a `java-platform` with `javaPlatform.allowDependencies()` and depending on a published BOM using `api(enforcedPlatform("group:module-bom:version")`, if that BOM itself imports BOMs (i.e., using `<dependency><type>pom</type><scope>import</scope>...</dependency>`, the transitive BOMs are not applied by the platform.

### Expected Behavior

A platform should apply the transitive dependencies of any dependency BOMs, similar to what Maven would do.

### Current Behavior

The platform does not apply transitive dependencies, and any dependencies defined in those will not resolve.

### Context

Trying to use `google-cloud-bom` - it has worked so far since all dependencies were defined in the BOM but the most recent version switched to importing BOMs transitively, which should be a no-op but is currently not handled correctly by a platform.

### Steps to Reproduce 

https://github.com/anuraaga/gradle-platform-transitive

This project does not build, but if you downgrade the version in `platform/build.gradle.kts` to `com.google.cloud:google-cloud-bom:0.116.0-alpha`, it does build (that version does not use transitive BOMs).

### Your Environment

Gradle 6.0-rc-2, Windows, Java 13 (zulu)

**Comment by jjohannes** [comment]
That's by design. There is no such thing as "transitive BOMs" if we follow the semantics implemented in Maven. In Maven you have the same problem with that BOM if you move from `0.116.0-alpha` to `0.117.0-alpha`.

I am not sure what the motivation behind https://github.com/googleapis/google-cloud-java/pull/6554 was, but if `google-cloud-bom` is meant to be imported as a "super BOM", the change is not going to work in Maven (or Gradle) like this.

I am not saying I like this behavior :), but we are trying to stay as close to the Maven semantics as we can here.

If you want true _transitive platform dependencies_ with Gradle, you can be published Gradle Module Metadata with _platform dependencies_.

**Comment by chingor13** [comment]
cc @elharo

**Comment by elharo** [comment]
@saturnism

**Comment by anuraaga** [comment]
Thanks for the explanation and sorry for the noise @jjohannes. Actually I don't use maven much so made a really wild assumption. I agree it's better to match Maven semantics so there's nothing wrong here then.

**Comment by elharo** [comment]
The comment https://github.com/gradle/gradle/issues/11208#issuecomment-549557803 is incorrect. There is such a thing as transitive BOMs and Maven does work with them. I just verified this with google-cloud-bom:0.117.0-alpha. 

I don't know anything about gradle java-platforms, but if it's supposed to mirror the Maven behavior , then this is indeed a bug in Gradle.

Here is one pom.xml that uses the transitive BOM to set the version of `com.google.api:gax`. If you can produce a Maven project, where the transitive BOM fails, I'd be curious to see that. Meanwhile I recommend reopening this bug. 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <packaging>war</packaging>
  <version>0.1.0-SNAPSHOT</version>
  <groupId>com.example</groupId>
  <artifactId>example</artifactId>
  <properties>  
    <appengine.maven.plugin.version>2.2.0</appengine.maven.plugin.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bom</artifactId>
        <version>0.117.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <!-- Compile/runtime dependencies -->
          <dependency>
        <groupId>com.google.api</groupId>
        <artifactId>gax</artifactId>
      </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <version>3.1.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet.jsp</groupId>
      <artifactId>javax.servlet.jsp-api</artifactId>
      <version>2.3.1</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jstl</groupId>
      <artifactId>jstl</artifactId>
      <version>1.2</version>
    </dependency>
    <dependency>
      <groupId>com.google.appengine</groupId>
      <artifactId>appengine-api-1.0-sdk</artifactId>
      <version>1.9.76</version>
    </dependency>
    <!-- Test Dependencies -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <!-- for hot reload of the web application-->
    <outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>${appengine.maven.plugin.version}</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>3.0.0-M2</version>
        <executions>
          <execution>
            <id>enforce-maven</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <!-- appengine-maven-plugin requires Maven 3.5.0 -->
                <requireMavenVersion>
                  <version>3.5.0</version>
                </requireMavenVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by jjohannes** [comment]
@elharo Thanks for clarifying and sorry for my wrong statement. It was late for me yesterday.

So you are right and this **is working** in Gradle, because we already "flatten" the BOM when reading it - i.e. we get the imported BOM and that makes up one "platform".

Your example `com.google.api:gax` is also working in Gradle:

```
dependencies {
    api(platform("com.google.cloud:google-cloud-bom:0.117.0-alpha"))
    implementation("com.google.api:gax")
}
```

@anuraaga I think your issue stems from the fact that `grpc-google-cloud-trace-v2` is not listed anymore in the BOM at all (not in the BOM itself and also not in the imported BOMs). So this is the failing Maven build I had which got me confused:

```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>org</groupId>
  <artifactId>test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>test</name>

  <dependencies>
    <dependency>
      <groupId>com.google.api.grpc</groupId>
      <artifactId>grpc-google-cloud-trace-v2</artifactId>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bom</artifactId>
        <version>0.116.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

Not sure if this is desired or an oversight that happened during the `google-cloud-bom` refactoring.

Sorry again for the confusion.

**Comment by anuraaga** [comment]
Thanks for putting time into this - indeed it looks like I landed on a very sharp corner case which I generalized before investigating enough.

**Comment by suztomo** [comment]
@anuraaga The missing "grpc-google-cloud-trace-v2" has been added back to google-cloud-bom in its master. https://github.com/googleapis/java-trace/pull/36 . Thank you for getting attention of us.

@jjohannes Thank you for the precise analysis!
