### ISSUE TITLE
`--scan` does not work when settings script is written in Kotlin

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#11202]
### Expected Behavior
Same behavior as with a Groovy DSL based settings script.  Build scan should be created.

### Current Behavior

Build scan is not created:
> Build scan cannot be created because the Gradle Enterprise plugin was not applied.
> For more information on how to apply the Gradle Enterprise plugin, please visit https://gradle.com/scans/help/gradle-cli.

### Context
This is new in 6.0

### Steps to Reproduce 

`gradle init`
Choose 'basic' and 'kotlin' DSL.
`gradle --scan help`

**Comment by ldaley** [comment]
Test is here: https://github.com/gradle/gradle/blob/412cfdace49a677346c0ee3e0cfd10d1d2f33374/subprojects/core/src/integTest/groovy/org/gradle/internal/scan/config/BuildScanAutoApplyKotlinIntegrationTest.groovy#L29

Currently trying to work out how the test is broken.

**Comment by ldaley** [comment]
@bamboo @eskatos can I get your help here please. Seems that Kotlin settings scripts don't respect auto applied plugins. We had a test for this, but it was bugged and gave a false positive.

I had a look, but I couldn't find where we forked the path for Project vs Settings. I fixed the test on https://github.com/gradle/gradle/tree/ldaley/kotlin-settings-auto-applied-plugins (https://github.com/gradle/gradle/blob/828cb8e494741cfb8d3821d0f715e013da25dc64/subprojects/core/src/integTest/groovy/org/gradle/internal/scan/config/BuildScanAutoApplyKotlinIntegrationTest.groovy#L33). 

Please point me in the direction of the change to make, or just push it directly to that branch. Thanks.

**Comment by bamboo** [comment]
@ldaley fix pushed to the branch.
