### ISSUE TITLE
Best practices for logging during plugin configuration?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#11213]
How should plugin developers log stuff so that Gradle shows which pugin it came from? When you do a println while in a task, it'll show the output under `> Task :myName`. Is there a way to do this for plugins so it would show `> Configure plugin My Plugin Name`? I thought the point of `Logging.getLogger(PluginClass::class.java)` was so that Gradle could do this kind of thing, but that does not appear to be the case.

**Comment by tasomaniac** [comment]
In couple of plugins, I added a constant prefix to all error messages (especially the ones that are during configuration time)

**Comment by SUPERCILEX** [comment]
@tasomaniac I think that's what I might have to do, but I'm really hoping there's a better solution.

**Comment by big-guy** [comment]
I think the "best practice" would be to not produce any logging by default and use your best judgment for messages that are emitted for info/debug level.

For _failures_, I think we can do better to connect failures to plugins/tasks/configuration, but that wouldn't necessarily happen at the logger level. 

Do you have some examples of what you were trying to do?

**Comment by SUPERCILEX** [comment]
@big-guy yes, I'm logging a warning about a deprecated feature, so this goes back to https://github.com/gradle/gradle/issues/9500. There's currently no good way to do this.

**Comment by tasomaniac** [comment]
With version 5, Gradle has this mechanism now to combine deprecations and display them at the end of the build. This is for Gradle APIs. I wonder if it would be possible to expose this to plugin developers.

**Comment by SUPERCILEX** [comment]
Good idea, I'll play with using [this](https://github.com/gradle/gradle/blob/d9f454a0b5810d217e3e14fd10caaccbc7d733b7/subprojects/logging/src/main/java/org/gradle/internal/featurelifecycle/LoggingDeprecatedFeatureHandler.java) plus including the plugin name in my log message.

**Comment by SUPERCILEX** [comment]
I ended up going with the `DeprecationLogger`: https://github.com/Triple-T/gradle-play-publisher/commit/13ba0d08146194890125b489676f46f4e993d3c5. Still would be nice to have some special logger for stuff that happens during plugin configuration.
