### ISSUE TITLE
java.nio.file.Path is not usable with Gradle

### ISSUE THREAD

**Issue by kenzierocks** [gradle/gradle#1122]
`Path` is not usable and can cause hard-to-debug problems when passed to Gradle.

### Expected Behavior
Passing `Path` to `project.file` or `project.files` should result in the same behavior as passing `path.toFile()`.

### Current Behavior
- `project.file`: Raises an exception
- `project.files`: Does nothing on initial call, hangs Gradle when `getFiles()` is called

### Context
I prefer to use `Path` to `File`, but I need to remember to double-check all the variables I pass to Gradle to ensure no `Path` instances are being used. Otherwise, Gradle will hang as noted in the second bullet point above.

### Steps to Reproduce (for bugs)
https://github.com/kenzierocks/gradle-path-infinity-resolve

This project contains a single file, `build.gradle` with a `singleFile` task and a `multiFile` task. The `singleFile` task passes `Paths.get('.')` to `project.file`. The `multiFile` task passes `Paths.get('.')` to `project.files`. If everything is working properly, both tasks should print a path equivalent to `.`.

### Your Environment
`gradle -Dscan`: https://scans.gradle.com/s/r4ylr7jlg6klq

**Comment by lacasseio** [comment]
Thanks @kenzierocks for the detailed issue. Could you provide us with a build scan for each behavior: `project.file` and `project.files`. That would help us. I see the `Path` object doesn't seem to be supported as a valid path and it make sense to support those.

**Comment by kenzierocks** [comment]
`project.file`: https://scans.gradle.com/s/osz7prvosbfyw
`project.files`: Impossible to do, as the build does not appear to stop. Manually killing it does not produce a scan.

**Comment by kenzierocks** [comment]
It looks like this might have been solved by #813. I'll test it soon.

**Comment by kenzierocks** [comment]
This has been fixed.
