### ISSUE TITLE
Check native performance after performance improvements to Virtual File System

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11227]
The performance improvements should address the regressions introduced by merging #11226. Those were:
- gradle/gradle-private#2822
- gradle/gradle-private#2823
- gradle/gradle-private#2824
- gradle/gradle-private#2825

Some ideas:
- Store information from a filtered read in the vfs and use it on the second read of the same location
- merge directory snapshots instead of replacing them. E.g. shallow + partial should keep known stuff from partial
- Replace two calls for `updateWithKnowSnapshot` (invalidate/store) by one call
- capture shallow snapshot of directory after a few missing files have been queried and use in in subsequent queries

**Comment by lptr** [comment]
Moved to 6.4 when we'll focus on snapshotting/VFS performance.

**Comment by wolfs** [comment]
We won't do anything about these regressions right now.
