### ISSUE TITLE
Add a conventional sample headers (download link, IDE info, etc)

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#11234]

**Comment by lacasseio** [comment]
<img width="957" alt="Screen_Shot_2019-11-06_at_8_44_04_AM" src="https://user-images.githubusercontent.com/22181740/68271531-e31f3880-0071-11ea-9a15-2a21a52aeceb.png">

**Comment by lacasseio** [comment]
- The buttons are styled in https://github.com/gradle/gradle/pull/11240
- The display name is used in https://github.com/gradle/gradle/pull/11242
- The IDE notes are added in https://github.com/gradle/gradle/pull/11237
- The caption bloc are for samples are fixed by https://github.com/gradle/gradle/pull/11238

@big-guy The only missing thing is the description as shown on the index page. Do you think it would be useful to add it?

**Comment by big-guy** [comment]
Let's see what this looks like for now.  I don't think the description has to be there

**Comment by lacasseio** [comment]
Alright, then let's close and open another issue if needed.
