### ISSUE TITLE
Jacoco-plugin seems to break Gretty-plugin

### ISSUE THREAD

**Issue by jnaalisv** [gradle/gradle#1125]
Jacoco-plugin seems to break Gretty-plugin in Gradle 3.3. This issue was not present in 3.2.1

### Expected Behavior
appRun should run with jacoco-plugin applied.

### Current Behavior
appRun throws a NPE if jacoco-plugin is applied

### Context
I've been using both Jacoco and Gretty in my projects and after updating to Gradle 3.3 Gretty-tasks started mysteriously failing.

### Steps to Reproduce (for bugs)
Example project: https://github.com/jnaalisv/gradle-gretty-jacoco-issue

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/j5tkhswublk4o

**Comment by wolfs** [comment]
Looks like for some reason I do not quite understand yet, the Gretty plugin applies the Jacoco plugin to a [DummyTask](https://github.com/akhikhl/gretty/blob/936fcb7b9d5ccfb78abf6a43e85cb684bc24f372/libs/gretty/src/main/groovy/org/akhikhl/gretty/DummyTask.groovy) which returns `null` for `getInputs()`. Starting from Gradle 3.3 the Jacoco plugins registers more inputs for the task for better up to date checking and uses `getInputs()` on the task for that (see [JacocoPluginExtension.applyTo](https://github.com/gradle/gradle/blob/c3edb5c41a3c9a5d6cab616023d0e2891869b511/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoPluginExtension.java#L104-L104)).
I don't think a task should be allowed to return `null` for `getInputs()`, so I suppose this is a problem with the Gretty plugin. Could you open an issue there?

**Comment by bmuschko** [comment]
Closing issue as it has to be resolved in the Gretty plugin.

**Comment by jnaalisv** [comment]
@wolfs, thanks for investigating this.
