### ISSUE TITLE
Investigate failure of `AssemblyLanguageIncrementalBuildIntegrationTest.does not re-execute build with no change`

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11263]
The test started failing after https://github.com/gradle/gradle/pull/10975 has been merged.

**Comment by wolfs** [comment]
The test seems to not find `C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\codeanalysis\sourceannotations.h` in the second invocation. For some reason there is a complete directory snapshot at `Microsoft Visual Studio 12.0/VC/include` which wasn't there on the first invocation:
```
Querying C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\codeanalysis\sourceannotations.h
C:
  Program Files (x86) | PartialDirectorySnapshot
    Microsoft Visual Studio 12.0/VC/include | Directory | CompleteDirectorySnapshot
    Windows Kits/10/Include/10.0.15063.0 | PartialDirectorySnapshot
      shared | CompleteDirectorySnapshot
      um | CompleteDirectorySnapshot
```

The question is now why this snapshot returns a missing snapshot for `codeanalysis/sourceannotations.h`.

**Comment by wolfs** [comment]
The directory snapshot seems to be empty :(
```
C:
  Program Files (x86) | PartialDirectorySnapshot
    Microsoft Visual Studio 11.0/VC/include | Directory | CompleteDirectorySnapshot
    Windows Kits/10/Include/10.0.15063.0 | PartialDirectorySnapshot`
```

How is that possible? Does Gradle not have the rights to read the directory contents?

**Comment by wolfs** [comment]
So I finally understand what is going on. I made a mistake when printing out the contents of the `CompleteDirectorySnapshot`. It isn't empty, it actually is this:
```
C:
  Program Files (x86) | PartialDirectorySnapshot
    Microsoft Visual Studio 11.0/VC/include | Directory | CompleteDirectorySnapshot
      CodeAnalysis | CompleteDirectorySnapshot
        Warnings.h | RegularFileSnapshot
        sourceannotations.h | RegularFileSnapshot
      ConcurrencySal.h | RegularFileSnapshot
```

So when querying
```
Querying C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\codeanalysis\sourceannotations.h
```

the file is not found in the `CompleteDirectorySnapshot`, since the case of the `CodeAnalysis` directory differs.

I think the include is coming from within Visual Studio (all supported versions), so the user can't do anything about it.

Note that the `CompleteDirectorySnapshot` is coming from the `Assemble` task, which uses the whole include path as input files instead of doing a header analysis.

With partial VFS invalidation, the task outcome would be consistent, since the complete directory snapshot would always exist. In the current state, when the `Assemble` task executes, the complete directory snapshot is removed and the follow-up compile task then directly queries the file.

What we could do is:
- search in a case insensitive way in `CompleteDirectorySnapshots` when on a case insensitive file system
- work on Visual Studio have the problem fixed upstream (I don't know if this is feasible)
- live with the problem that sometimes your compilation task may be out of date, depending on whether some other task left a complete directory snapshot around or not. This should be mitigated with partial VFS invalidation,

**Comment by wolfs** [comment]
@lacasseio Do you have any input on this?

**Comment by lptr** [comment]
> work on Visual Studio have the problem fixed upstream (I don't know if this is feasible)

What is the problem that VS would need to solve here?

Isn't this just a typical thing in Windows development to use arbitrary casing for file names (including include file names)?

> search in a case insensitive way in CompleteDirectorySnapshots when on a case insensitive file system

That would solve some other potential problems, too, at the cost of some performance. We could also do the case-insensitive compare only when looking for include files (and still treat `Input.TXT` replaced by `input.txt` as a removed-then-added input).

**Comment by wolfs** [comment]
> > work on Visual Studio have the problem fixed upstream (I don't know if this is feasible)
> 
> What is the problem that VS would need to solve here?

Visual Studio should use the right case in its internal header files when including other internal header files.

**Comment by lptr** [comment]
Ah, so the `#include` comes from a VS file, ok. I guess even if we fixed VS, user code would still not observe this rule on Windows, so I don't think this is an effective direction.

**Comment by lacasseio** [comment]
Wouldn't it be wiser to compare the paths with the file system sensitiveness? Windows is known to be case insensitive which causes a whole lot of strangeness if you mix case sensitive OS (through Git for example). It would make sense they should use the right case but it's also on us to be resilient on the case comparison.
