### ISSUE TITLE
Demonstrate additional test suite in the same project (e.g. integration tests)

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#11273]
This is an extremely common use case for which we don't have higher-level abstractions and there are various examples of how to do this floating around. It's currently included in one of the init templates.

**Comment by rkrisztian** [comment]
There are quite some users of the [gradle-testsets-plugin](https://github.com/unbroken-dome/gradle-testsets-plugin). I believe that the plugin helps us greatly reduce boilerplate, and it would be nice to have something like that provided as a core feature maybe. Just a suggestion.

**Comment by lacasseio** [comment]
Thanks @rkrisztian for mentioning the gradle-testsets-plugin. It does show a lack in Gradle for that specific use case. The samples are mostly meant about showing what can be done with Gradle. We are a bit shy to mention 3rd party plugin inside the documentation for the moment they fall behind. This is a lack in the whole community plugin which is how do you promote a plugin that solve a specific use case. The samples work hard on making those use cases explicit.
