### ISSUE TITLE
Edit this page does not link on new sample pages

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#11270]
Steps to reproduce:

- Open a new sample page e.g. https://docs.gradle.org/nightly/samples/groovyBasicApplication/
- Click "edit this page"
- The browser goes to https://github.com/gradle/gradle/tree/master/subprojects/docs/src/docs/userguide

**Comment by lacasseio** [comment]
Duplicate of https://github.com/gradle/gradle-private/issues/2828
