### ISSUE TITLE
[Scala] Depending on sub-project doesn't include Scala classes

### ISSUE THREAD

**Issue by aesteve** [gradle/gradle#11280]
### Expected Behavior
In a multi-project Scala build. A Scala sub-project depending on an other Scala sub-project should include its Scala classes.

Let's say we have the following project structure:

```
rootProject
  \___ project1 (Scala)
  \___ project2 (Scala)
```

And project2 depends on classes of project1.

### Current Behavior
With Gradle 5.6.2 with kotlin DSL declaring in project2 (`project2/build.gradle.kts`):
```
plugins {
  scala
}
dependencies {
  implementation(project(":project1"))
}
```
Does not include Scala classes from `project1`

### Context
I got it working with the following simple workaround.
In `buildSrc/src/main/kotlin/scala.kt` (so that I can benefit from it in different sub-projects) I defined an extension method as follows:

```
/**
 * This fixes a bug in the Scala plugin: adding: project(":some-project") as dependency, doesn't include Scala sources
 */
fun DependencyHandlerScope.scalaProject(path: String) {
    apply {
        project(path)
                .dependencyProject
                .extensions
                .getByName<SourceSetContainer>("sourceSets")
                .forEach {
                    if (it.name == "test") dependencies.apply { "testImplementation"(it.output) }
                    else dependencies.apply { "implementation"(it.output) }
                }
    }
}
```
Now in `project2` I can simply write:

```
dependencies {
    scalaProject(":project1")
}
```

### Steps to Reproduce 
Simply create a multi-project Scala build, with one sub-project depending on another one.
Then, using Kotlin DSL (not sure it's relevant to Kotlin DSL, I guess it's the same with Groovy?), declare a dependency from `project2` to `project1` as follows:

```
dependencies {
  implementation(project(":project1"))
}
``` 

### Your Environment
Gradle 5.6.2, official Scala plugin. Mac OS 10.14.6.
Not sure what other relevant information I can add, do not hesitate to ask.

Not a blocker, since I found a workaround. And not sure I really need the workaround (maybe I declared something wrong). Do not hesitate to close with a link to an example, or best practices I might have missed (really sorry for the noise if that's the case).

Thank you for your work with Gradle, congratulations for the release of Gradle 6.

**Comment by aesteve** [comment]
Gonna experiment with Gradle 6.0 to check if the bug exists.

**Comment by aesteve** [comment]
Actually, with Gradle 6.0, this:

```
dependencies {
    implementation(project(":project1"))
      testImplementation(project(path = ":project1", configuration = "test")) // if you've registered a configuration for tests (useful if you're also registering a test jar)
}
```
Also works.
Gonna close the issue, since looks fixed in 6.0, avoiding creating noise.
Hopefully this can help future readers, though.

**Comment by jjohannes** [comment]
@aesteve Gradle 5.x had some issues with using `implementation` in combination with the Scala plugin. It should all work with Gradle 6 (as you observed).

You can now, and should, combine `scala` and `java-library`

``` 
plugins {
  scala
  `java-library`
}
```

Then you can also declare `api` dependencies if desired. That all works with Gradle 6.

Regarding test code: The behavior you observe is the expected. It is the same for Java (or Groovy) test code. Test code is not expected to be shared. Instead, you should use [test fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) (the samples are for Java, but it should all work the same with Scala code if the `scala` plugin is applied).

If you really really (not recommended) want to share the test code, you can turn the `test` source set into a [feature variant](https://docs.gradle.org/current/userguide/feature_variants.html#sec::declare_feature_variants) and depend on it via a `requireCapability()`. That would be the preferred way now over selecting a configuration directly (configuration = "test").

**Comment by aesteve** [comment]
> Then you can also declare api dependencies if desired. That all works with Gradle 6.

Didn't check that! But thanks! That'll remove a lot of boilerplate stuff I wrote in the past.

Regarding the tests, I'm not completely sure I get the difference between a test artifact, a test fixtures, and the feature variant yet. But I'll try to understand, thanks for your pointers.

Sometimes, I need to share tests outside the project, for this I'm publishing a test jar.
Sometimes, I just need a sub-project to access classes (mostly: property-test generators) from another sub-project, only for the sake of DRY.

So far it works, and the workaround I wrote earlier is completely fine for me, still don't get why sharing test code is not recommended though. For instance: defining a Property-Test generator shouldn't be done in `main` but in `test` and then other projects could benefit from it, no?

**Comment by jjohannes** [comment]
> So far it works, and the workaround I wrote earlier is completely fine for me, still don't get why sharing test code is not recommended though. For instance: defining a Property-Test generator shouldn't be done in main but in test and then other projects could benefit from it, no?

The idea is to keep utility code for tests (which can be reused) separated from actual tests which are only of interest for the current project. Mixing the two can get messy if you have a lot of tests and utility (test fixture) code, as we for example have in our own Gradle build.

The property test generator is an example of something that should go into test fixtures then. With test fixtures you have this:

````
src/main/scala          <- here goes your production code
src/testFixtures/scala  <- here goes code to setup tests, test data, test infrastructure, etc. that can be used by other projects
src/test/scala          <- here go the tests for *this* project

**Comment by aesteve** [comment]
Ok! I get it, makes complete sense.

Thanks for your help.
