### ISSUE TITLE
Demonstrate 2 intermediate use cases around the dependency management

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#11287]
The core team may have time to take up the work or promoting 2 intermediate snippets from the dependency management user manual as samples.

**Comment by lacasseio** [comment]
@gradle/dependency-management Could you provide us with 2 user manual samples that you feel are important, focused, use cases for intermediate users? We should be able to provide assistance in migrating them over, removing the duplication that it will create (snippets vs samples) and provide links from the user manual to the samples.

**Comment by jjohannes** [comment]
Samples have been updated massively recently. We'll add more in the future and open individual issues for them.
