### ISSUE TITLE
property name incorrect in sample included in the documentation: astTranformationClasspath

### ISSUE THREAD

**Issue by jechlin** [gradle/gradle#11305]
`subprojects/docs/src/samples/groovy/compilationAvoidance/groovy/build.gradle` and `build.gradle.kts` have an incorrect property name `astTranformationClasspath` which should be `astTransformationClasspath` (the `s` is missing).

This is discussed in the documentation here: https://docs.gradle.org/current/userguide/groovy_plugin.html#sec:groovy_compilation_avoidance. The copy has the correct property name, the included samples do not.

As many people will copy from the sample, this leads to:

    > Could not get unknown property 'astTranformationClasspath' for task ':xyz:compileGroovy' of type org.gradle.api.tasks.compile.GroovyCompile.

**Comment by blindpirate** [comment]
Thanks for reporting @jechlin we'll fix it soon.

**Comment by blindpirate** [comment]
Closed by https://github.com/gradle/gradle/pull/11313
