### ISSUE TITLE
Properly handling multiple forms of command-line options

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#11302]
Multiple forms of command-line options should be recognized / handled as appropriate.

e.g., double-dash arguments for recent JDK tools support two forms, like:

1. `--option value`
2. `--option=value`

e.g., `JavaCompilerArgumentsBuilder` doesn't recognize the `--option=value` form for multiple options that it tries to detect.

Commit 2df1138d151afcc923e90a44ccb4df314a84da81 for PR #10862 fixes the above, but only using a utility method directly in `JavaCompilerArgumentsBuilder`, instead of providing a general purpose utility for use by all of the Gradle codebase / Gradle users to use.

I think that any utilities that you create to handle this should be available in the API, to allow plugin developers / build authors to easily properly handle multiple forms of arguments.

Other tools might provide different alternate forms for the same option (e.g., maybe using a colon instead of equals as the separator between option name & value), and should also be properly handled.

**Comment by rgoldberg** [comment]
This would still be useful. If I were to make a utility method to handle this, what class (either existing or new) should it be put into?

**Comment by ljacomet** [comment]
Sorry for the late reply

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

To clarify what the request is, it would be a general support for Gradle to handle both option notations when specifying arguments for launched tools that have richer APIs than simply passing in an argument list - like what `JavaCompilerArgumentsBuilder` does.

Currently Gradle only supports the space separator form, and will not be able to analyze an option passed using `=` as a separator.

**Comment by big-guy** [comment]
Do you have any more specific use cases of where this is causing problems or what you need? We're not likely to provide a general purpose way of parsing command lines.
