### ISSUE TITLE
Fail publishing if artifact already exists

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#11315]
so I just published a maven artifact over an existing released version, I'm sure allowing this is intentional, but I would like the option to reject a publish if the artifact already exists (I personally think that should be the default). using `maven-publish`

**Comment by big-guy** [comment]
This might be better done on the artifact repository side for a couple of reasons:

1. Some dependencies are expected to be overwritten (like a snapshot or changing dependency).  So publishing would need to know if the consumer expects overwrites or not. I believe most artifact repositories allow you to configure this on a per-repository level.
2. There's a race between checking if the artifact exists and publishing.  The artifact repository can prevent this by not allowing overwrites.

**Comment by xenoterracide** [comment]
we use an s3 repository, we could write lambda's I suppose to implement this, but this is much harder on the metadata.xml end. wheras gradle, which already has to parse it, could easily check to see if this version already exists.
