### ISSUE TITLE
Core locking ergonomics with write-locks and update-locks

### ISSUE THREAD

**Issue by OdysseusLives** [gradle/gradle#11319]
### Current Behavior
Given a project uses Gradle core locking
And locks are in use,
When a dependency resolves to a new version
And `--write-locks` and `--update-locks` with a group & artifact are both invoked,
Then the user should be informed that these should not be run at the same time

### Context
The lack of warning creates an unexpected ergonomics where a person's intention to selectively update dependency locks vs update all dependencies is unclear.

### Expected Behavior
Instead, the task should fail and warn the user to only use one of these flags.

### Steps to Reproduce 
Here is a sample project that walks through this scenario: https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/locking-ergonomics

In the end, the update-locks is used (which is better than unlocking & resolving all dependencies), but it would be better to warn the user.

Looks like these values are set here in the `DefaultDependencyLockingProvider`[1] and then get used in the `LockEntryFilterFactory.forParameter(...)` where if there are no dependencies to update, then a `FILTERS_NONE` is returned. But if there are selective dependencies to update, then only those are updated.

[1]https://github.com/gradle/gradle/blob/v6.0.0/subprojects/dependency-management/src/main/java/org/gradle/internal/locking/DefaultDependencyLockingProvider.java#L69-L75
[2]https://github.com/gradle/gradle/blob/v6.0.0/subprojects/dependency-management/src/main/java/org/gradle/internal/locking/LockEntryFilterFactory.java#L45-L67

### Your Environment
Using Gradle 6.0

**Comment by ljacomet** [comment]
Sorry the late reply

The issue is in the backlog of the relevant team and is prioritized by them.

***

Given this currently "works", it would need a deprecation / removal cycle.
