### ISSUE TITLE
Convention mapping intermittently does not detect explicitly configured value

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#11323]
### Expected Behavior

When a convention mapping is configured, the `Callable` should only be called when a value for the property has not been explicitly configured.

### Current Behavior

Intermittently, the convention mapping fails to detect the explicit configuration of the property and then calls the `Callable` unexpectedly.

### Context

It's hard to be certain with which version it stopped working as the problem is intermittent. I have managed ten consecutive successful builds with 5.1.1, but I always see a failure within ten builds with 5.2 and later.

I am trying to update Spring Boot's build to use Gradle 6 to build its Gradle plugin. It is currently using 4.10.3.

### Steps to Reproduce 

Running `./gradlew clean build` multiple times with
[this example project](https://github.com/gradle/gradle/files/3835549/convention-mapping-problem.zip) should see a mixture of failed and successful builds.

### Your Environment

https://gradle.com/s/ftnc2diia6iam - successful build
https://gradle.com/s/2qjv2raxloxyy - failed build

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/11643
