### ISSUE TITLE
macOS: set process names for better indentification

### ISSUE THREAD

**Issue by gabrielittner** [gradle/gradle#11326]
### Current Behavior

Currently all Grade daemon processes show up as `java`.
![Screenshot 2019-11-12 at 13 27 12](https://user-images.githubusercontent.com/1358105/68671676-28e76f80-0550-11ea-8883-04df90dd4d3e.png)

### Expected Behavior

Gradle daemon processes should be named something like `Gradle daemon 5.5.1`.

### Context

Currently it's hard to identify which processes are Gradle's and which java processes come from somewhere else (for example Kotlin's compiler daemon). This would make it a lot easier. The only way I currently know is to manually match process ids with the output of `gradle -status` (but that only gives you the daemons for the Gradle version you're running).

**Comment by big-guy** [comment]
You can use `jps -m` to list all Java processes.  Gradle passes its version number as an argument to the daemon:
```
2021 GradleDaemon 5.6.4
357 
1943 GradleDaemon 6.0
2283 Jps -m
```

**Comment by gabrielittner** [comment]
@big-guy I missed your reply. That is definitely helpful, but it still would be very useful to see the name directly in Activity Monitor.
