### ISSUE TITLE
Build android project error using gradle 

### ISSUE THREAD

**Issue by gongzelong0718** [gradle/gradle#11322]
### Expected Behavior

Build successfuly

### Current Behavior
```
Caused by: com.android.build.gradle.internal.crash.ExternalApiUsageException: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method deleteAllActions() for arguments [] on task ':category:extractDebugAnnotations' of type com.android.build.gradle.tasks.ExtractAnnotations.
    
https://docs.gradle.org/current/userguide/upgrading_version_4.html
The Task.deleteAllActions() method has been removed with no replacement.
```

### Your Environment
Android gradle plugin: 3.4.2
gradle wrapper version: 5.5.1
classpath 'com.android.tools.build:gradle:3.4.2'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.5.1-all.zip

Instead, if I use the following environment:
Android gradle plugin: 2.3.3
gradle wrapper version: 3.3
classpath 'com.android.tools.build:gradle:2.3.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

Android Studio version: 
Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 2, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1

I will encounter the following issue.

ERROR: The module 'controls' is an Android project without build variants, and cannot be built.
Please fix the module's configuration in the build.gradle file and sync the project again.

I do not know where I set the deleteAllActions and do not know how to avoid it.

Now, I stuck in the build procedure.

**Comment by flutterq** [comment]
[[Solved]  AbstractDynamicObject$CustomMessageMissingMethodException error in android](https://exerror.com/solved-abstractdynamicobjectcustommessagemissingmethodexception-error-in-android/)
