### ISSUE TITLE
Make it easier to combining Groovy and Kotlin in one project

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#11333]
Sometimes it is desired to have both Groovy and Kotlin code in one project. This can be difficult to set up, if classes implemented in different JVM languages depend on each other. It is hard to customize, because both the Groovy and Kotlin plugins add dependencies to the `compileJava` task(s).

As a consequence it is common practice to remove such dependencies, when combining Groovy and Kotlin. For example:

* Spring framework doing: `compileGroovy.dependsOn = deps - "compileJava"`
https://github.com/spring-projects/spring-framework/blob/master/spring-beans/spring-beans.gradle
* _android-junit5_ doing: `targetCompile.dependsOn.remove(javaCompileName)`
https://github.com/mannodermaus/android-junit5/blob/4a2b3f3a94743f020f6abfdc56d18f2fcd412beb/buildSrc/src/main/kotlin/Utilities.kt#L33

Removing task dependencies however, is no longer supported in Gradle 6.0.

The outcome of this issue can be to provide a good working best practice that works with Gradle `6.0` already (I think there is none) or add something to Gradle `6.1` that helps here (like making the groovCompile<->javaCompile dependency configurable in the groovy plugin extension)

**Comment by jjohannes** [comment]
Fixed through #11480

**Comment by mar3kk** [comment]
Is it still valid with latest kotlin gradle plugin? Apparently using class path is now an error. 
`Using 'classpath: FileCollection' is an error. Replaced with 'libraries' input`

**Comment by mkubiczek** [comment]
Is it still valid with latest kotlin gradle plugin? Apparently using classpath is now an error.
Using 'classpath: FileCollection' is an error. Replaced with 'libraries' input.

I tried doing
`
tasks.compileKotlin {
    libraries.plus(files(sourceSets.main.get().groovy.classesDirectory))
}
`

But during compilation the classes written in groove cannot be resolved by kotlin compiler.

**Comment by liplum** [comment]
For Kotlin 1.7.20 or higher, `classpath` is deprecated, and will be remove in the Kotlin 1.8.0 or higher.
You can opt-in it by replacing `classpath` with `libraries` inside `tasks.compileKotlin` closure.

```kotlin
tasks.compileGroovy {
    classpath = sourceSets.main.get().compileClasspath
}
tasks.compileKotlin {
    // replace `classpath` with `libraries`
    libraries.from(files(sourceSets.main.get().groovy.classesDirectory))
}
```
