### ISSUE TITLE
TestKit failure: cannot find extension of type AppExtension

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#11338]
I am developing a Gradle plugin that reacts to various Android plugins (`com.android.application` and `com.android.library`) in order to report unused dependencies. You can find it [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin). I have added a stub TestKit functional test. I have actually been able to "build" my stub Android project with TestKit, but the moment I apply my plugin-under-test to the `plugins {}` block in this stub project, there is a failure at TestKit-build time. More information in the "Context" section below.

### Expected Behavior

The functional test should pass.

### Current Behavior

The test fails because it cannot find AppExtension. I presume it is failing at [this line](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/master/src/main/kotlin/com/autonomousapps/DependencyAnalysisPlugin.kt#L42), but the failure stacktrace is too opaque to be certain.

### Context

The issue is affecting me because I cannot write functional tests to validate end-to-end behavior and defend against regressions.

The failure is:

> * What went wrong:
> A problem occurred configuring project ':app'.
> > Extension of type 'AppExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, DefaultArtifactPublicationSet, ReportingExtension, SourceSetContainer, JavaPluginExtension, NamedDomainObjectContainer<BaseVariantOutput>, BaseAppModuleExtension, KotlinAndroidProjectExtension, KotlinTestsRegistry]

This is nonsensical, since the `com.android.application` plugin _has_ been applied, and `AppExtension` _must_ exist at this point. Please note that manual tests of this plugin have succeeded, and the Android "app" defined in the TestKit context "builds" just fine. (You can remove the line `id('com.autonomousapps.dependency-analysis')` and re-run the test, and it will pass.)

This issue might be tangentially related to [this issue](https://github.com/gradle/gradle/issues/7974). But please note, I have encountered that particular issue before, and you can see the workaround [here](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/master/build.gradle.kts#L49-L51).

### Steps to Reproduce 

1. Clone [this repo](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin).
1. Ensure your build environment is set up to build Android apps (you will need the Android SDK and build-tools).
1. Run `./gradlew funcTest`
1. Observe the failure.

### Your Environment

Build scan URL: https://scans.gradle.com/s/zwg5yeodiqauss (but I cannot view it)

**Comment by autonomousapps** [comment]
I've attempted a couple of workaround based on a conversation in the [community slack](https://gradle-community.slack.com/archives/CA745PZHN/p1573581635185300).

This is the original code
```
the<AppExtension>().applicationVariants.all {
  val androidClassAnalyzer = AppClassAnalyzer(this@analyzeAndroidApplicationDependencies, name)
  analyzeAndroidDependencies(androidClassAnalyzer)
}
```
it uses the Kotlin DSL.

I tried replacing with 
```
(extensions.getByName("android") as AppExtension).applicationVariants.all {
  val androidClassAnalyzer = AppClassAnalyzer(this@analyzeAndroidApplicationDependencies, name)
  analyzeAndroidDependencies(androidClassAnalyzer)
}
```
and got the error:
> com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated cannot be cast to com.android.build.gradle.AppExtension

Which is ridiculous, as `BaseAppModuleExtension` _extends_ `AppExtension`.

I then tried replacing with 
```
(extensions.getByName("android") as BaseAppModuleExtension).applicationVariants.all {
  val androidClassAnalyzer = AppClassAnalyzer(this@analyzeAndroidApplicationDependencies, name)
  analyzeAndroidDependencies(androidClassAnalyzer)
}
```
and got the error
> com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated cannot be cast to com.android.build.gradle.internal.dsl.BaseAppModuleExtension

and now I don't even.

**Comment by autonomousapps** [comment]
Can I get some eyes on this? It's making it impossible to write any functional tests for a plugin designed to work on Android projects. I provided a build scan and a reproducer with clear steps. What else can I do?

**Comment by vlsi** [comment]
@autonomousapps , are you 100% sure the extension class is valid?

The exception message says "Extension of type 'AppExtension' does not exist", and it does say "KotlinAndroidProjectExtension" is present.

Are you sure the very same build succeeds and AppExtension indeed is present?

PS. You can "wait" for both plugins by using nested calls like

```
plugins.withId("...kotlin...") {
    plugins.withId("...android...") {
        /* this will be executed when both kotlin and android are activated*/
    }
}
```

**Comment by autonomousapps** [comment]
Yes, I'm certain. This same code works when I apply the plugin to a real
android project.

**Comment by autonomousapps** [comment]
I found a workaround, but it's highly unsatisfying. I still think there's a bug in TestKit somewhere. The workaround suggests that my plugin and AGP are loaded in different classloaders and can't see each other. If I add this to my functional test:

```
        val buildSrcDir = projectDir.resolve("buildSrc")
        buildSrcDir.mkdirs()
        buildSrcDir.resolve("settings.gradle").writeText("")
        buildSrcDir.resolve("build.gradle").writeText("""
            repositories {
                jcenter()
                google()
                gradlePluginPortal()
            }
            dependencies {
                implementation("com.android.tools.build:gradle:3.5.3")
                implementation("gradle.plugin.com.autonomousapps:dependency-analysis-gradle-plugin:0.10.0")
            }
        """.trimIndent())
```
then it works. In other words, I'm adding a buildSrc dir to my fake project-under-test in order to force AGP and my plugin to share a classloader.

And actually, I'm not sure what the implications are as I iterate on my plugin. Will it actually use my plugin-under-test, or will it use the binary version it is downloading from the gradle plugin portal?

**Comment by autonomousapps** [comment]
Unfortunately, it's really not a great workaround. It uses the version of the code hosted by the plugin portal, so I can't use it locally without publishing first. May as well just test locally.

**Comment by autonomousapps** [comment]
Finally able to really resolve this. I had
```
tasks.withType<PluginUnderTestMetadata>().configureEach {
    pluginClasspath.from(configurations.compileOnly)
}
```
_above_ my `dependencies {}` block. When I moved it to below, everything worked fine. So, that bit of code was eager and not lazy as I implicitly expected.

**Suggestion:** the `compileOnly` configuration should be automatically added to the test/TAPI classpath, so users aren't forced to auto-wire it in this undocumented way. We need to add things like AGP to the `compileOnly` configuration so we're not forcing our version choices on the users of our plugins.

**Comment by CristianGM** [comment]
@autonomousapps shouldn't you update the issue saying the workaround didn't work at all?

**Comment by autonomousapps** [comment]
That's what https://github.com/gradle/gradle/issues/11338#issuecomment-568226298 says.

**Comment by CristianGM** [comment]
But your last comment says opposite
https://github.com/gradle/gradle/issues/11338#issuecomment-568228102

**Comment by autonomousapps** [comment]
That one does in fact work. It was an ordering issue. I was trying to add the compileOnly dependencies to the test kit classpath, but it was empty, because I did it BEFORE my dependencies declarations.

**Comment by CristianGM** [comment]
Then we should CLOSE this issue.

I should open a new one with the real issue that is not being able to test a plugin against multiple versions of the Android Gradle Plugin, which was my issue and as it fails with the same error I thought we where talking about the same.
Maybe for the reproducer you could already show it because you have the same issue and you fixed it like me using project properties to test agains multiple versions.
