### ISSUE TITLE
Can't use source repositories with Gradle 6.0

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#11348]
I'm trying to use this with Gradle 6:
```
sourceControl {
    gitRepository(uri("https://github.com/MasonAmerica/mason-apps-build-system.git")) {
        producesModule("com.bymason.build:mason-apps")
        plugins { id("mason-apps") }
    }
}
```

It used to work, but now the `plugins { id("mason-apps") }` block keeps failing and says that it can't find the plugin. Nothing else has changed, so this seems like a bug in Gradle 6.

**Comment by big-guy** [comment]
Do you have a fuller example? That looks like `https://github.com/MasonAmerica/mason-apps-build-system.git` is producing the plugin `mason-apps` and you're applying it to itself?

**Comment by SUPERCILEX** [comment]
No, I'm trying to apply it in a private repo that I can't share. That repo works fine until I upgrade it to Gradle 6. After that, it says that it can't find the `mason-apps` plugin which is clearly there, especially given that I didn't change the target tag (consuming it with `com.bymason.build:mason-apps:1.0.1`).

**Comment by big-guy** [comment]
What isn't clear to me is that `https://github.com/MasonAmerica/mason-apps-build-system.git` appears to be the build that creates the plugin `mason-apps`.  This plugin can only be applied to a Project object.

And in your example above, you're applying the plugin `mason-apps` to the source dependency (mason-apps-build-system).  This can't work since `mason-apps` can't be applied to a Settings object.

**Comment by SUPERCILEX** [comment]
Your first statement is correct. `mason-apps-build-system` produces the plugin that should be consumed from the private project I tried upgrading to Gradle 6.0.

Your second statement is wrong. I'm wondering if the new plugins block in settings.gradle.kts is breaking things. The `plugins` block I'm using is [`VersionControlRepository#plugins`](https://docs.gradle.org/current/javadoc/org/gradle/vcs/VersionControlRepository.html#plugins-org.gradle.api.Action-). It's supposed to tell gradle that the source repo produces a plugin.

**Comment by big-guy** [comment]
> The plugins block I'm using is VersionControlRepository#plugins. It's supposed to tell gradle that the source repo produces a plugin.

Not quite.  This `plugins` is a list of plugins to inject into the source dependency. 

Could you share how you're applying the mason-apps plugin to the build itself?

**Comment by SUPERCILEX** [comment]
Lol, I'm stupid. No idea how that ever worked in the first place. Anyway, thanks for your help, removing that extra `plugins` block fixes everything.

**Comment by big-guy** [comment]
No worries.  I didn't know we had inadvertently fixed a bug :)
