### ISSUE TITLE
Demonstrate how to publish a custom component with Gradle Module Metadata

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#11351]
Publishing Gradle Module Metadata requires a `SoftwareComponent`. While Gradle language plugings will usually create and wire such a component, it might be interesting to have a full sample showing how to create such a component, through a `buildSrc` plugin and how to configure it for publication.

**Comment by melix** [comment]
What's the difference with https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components ?

**Comment by ljacomet** [comment]
Not much!
My view is as follows: what we have in the documentation lacks an easy access to a full blown sample with all the files and their content in the right place.
With the new samples section, we have the opportunity to put that forward: full blown samples.

So my vision is:

1. Do the full blown sample, with a link back to the doc.
2. Replace the doc snippets by ones pointing to the full blown sample.
3. At a later stage, when doc snippet reference a sample, we automate the insertion of a link to the sample

**Comment by melix** [comment]
I beg your pardon but I still don't understand what you mean. We have a full blown sample here -> https://github.com/gradle/gradle/tree/7e43726dae8a0ecc4d114e42f64dc3cfc9acc9ff/subprojects/docs/src/samples/userguide/dependencyManagement/modelingFeatures/crossProjectPublications/advanced-published

It's the one used for snippets in the docs.

**Comment by ljacomet** [comment]
oh right, and you and I (and others) know where to find it. But not the average user.
I never said doing the sample was hard, it can be just copying over the existing one. But then it is indexed and accessible to users navigating the docs. That would cover 1 and 2. Point 3 would still need to happen.
And I believe making point 3 happen with all the snippets we currently have would be counterproductive as too many of them are too arcane or used in too many contexts ... or plain too old.

**Comment by melix** [comment]
But that's IMO the problem. We have good samples, nobody can find them. Rewriting samples because we can't find them is a waste of time. Just analyze the pages, extract the samples in use and provide a way to "link to the full sample directory" from a documentation page. Then create an index of samples too. And last step, improve/replace the existing samples when they are not so good.

**Comment by lacasseio** [comment]
The sample work we are doing right now is much more than _just_ extracting the samples. We have a lot of edge cases and frankly, the current samples aren't well tested (for the majority that I looked at). We can _just_ analyze the pages and extract the samples but that requires a lot of upfront engineering time as we don't have anything that does that at the moment. There is also a non-negligible investment in adding a proper README for each sample which we can't really automate this.

We will get to those proper samples in due time and this is were we need issues like this one so the developer can fill missing samples as well as existing samples that could be exposed as they are. For the existing samples, we could batch them to release them faster.

An important point to note is the end-to-end lifecycle of the samples hasn't been properly established yet and we won't invest more engineering until it is established. For the time being, manual work is required and we will work hard on removing as much duplication as it makes sense. The current focus is releasing high-value samples that automation wouldn't be able to do.

**Comment by jjohannes** [comment]
This is explained (with snippets) here: https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components
