### ISSUE TITLE
afterEvaluate closure ignored when added to an evaluated project

### ISSUE THREAD

**Issue by uklance** [gradle/gradle#1135]
Forum post [here](https://discuss.gradle.org/t/weird-interaction-between-allprojects-and-evaluationdependson/21063)

### Expected Behavior
When calling `project.afterEvaluate(Closure)` on a project which has already been evaluated, either a WARN message should be logged or an exception thrown. These sorts of issues can be hard to track down if one plugin is calling `evaluationDependsOn(String)` and another calling `afterEvaluate(Closure)`

### Current Behavior
Gradle allows you to call `project.afterEvaluate(Closure)` on a project which is already evaluated. Meaning that the closure will never fire

### Context
One plugin is calling `evaluationDependsOn` and another is calling `afterEvaluate`. It took hours of debugging to figure out why the `afterEvaluate` was not firing

### Steps to Reproduce (for bugs)
build.gradle
```groovy
allprojects { p ->
	println "[1] Adding afterEvaluate for $p.name"
	p.afterEvaluate {
		println "[1] afterEvaluate $p.name"
	}
}

project(':a') {
	println "[2] Adding evaluationDependsOn"
	evaluationDependsOn(':b')
	evaluationDependsOn(':c')
}

allprojects { p ->
	println "[3] Adding afterEvaluate for $p.name"
	p.afterEvaluate {
		println "[3] afterEvaluate $p.name"
	}
}
```
output
```
[1] Adding afterEvaluate for root
[1] Adding afterEvaluate for a
[1] Adding afterEvaluate for b
[1] Adding afterEvaluate for c
[2] Adding evaluationDependsOn
[1] afterEvaluate b
[1] afterEvaluate c
[3] Adding afterEvaluate for root
[3] Adding afterEvaluate for a
[3] Adding afterEvaluate for b
[3] Adding afterEvaluate for c
[1] afterEvaluate root
[3] afterEvaluate root
[1] afterEvaluate a
[3] afterEvaluate a
```

Notice how `[3] afterEvaluate b` and `[3] afterEvaluate c` are never output

### Your Environment
```
------------------------------------------------------------
Gradle 3.0
------------------------------------------------------------

Build time:   2016-08-15 13:15:01 UTC
Revision:     ad76ba00f59ecb287bd3c037bd25fc3df13ca558

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_40 (Oracle Corporation 25.40-b25)
OS:           Windows 7 6.1 amd64
```

**Comment by oehme** [comment]
Another option that we discussed previously is to execute the action immediately if the project was already evaluated.

**Comment by uklance** [comment]
That would also work as technically any time after evaluation is `afterEvaluate`

**Comment by TWiStErRob** [comment]
Bump?

At minimum a warning should be output that `afterEvaluate` was called after evaluation was completed, and that the closure will be ignored.

**Comment by isker** [comment]
This issue flambéed me with regard to the task configuration avoidance APIs.  I was calling afterEvaluate in a Task constructor (likely wrong or evil, I know) in a task that is unconditionally created.  But due to the laziness of task creation with the new APIs, suddenly afterEvaluate could be called after the project was evaluated.  

This stumped me because many of the other "hook" closure APIs (e.g. PluginContainer.withType, etc etc) will immediately evaluate your closure if the condition for their execution is already satisfied.  This one silently dumping your closure on the floor is likely the worst possible outcome.  I'd be in favor of the immediate execution @oehme mentioned but if you think that loudly failing is preferable, so be it.

**Comment by lacasseio** [comment]
Executing `afterEvaluate` actions after projects have been evaluated would be breaking change as code that is silently ignored would suddenly start executing. Instead, we will issue a warning for this specific use case and will become an error by Gradle 7.0. The `afterEvalutate` API is a long time problem that we are trying to address using the Provider APIs. We wish to phase out the API at some point in the future. Making it more convenient would go against this goal. It would be preferable for the users to open issues on how they are using the API so we can provide better APIs (not relying on the execution order) instead.
