### ISSUE TITLE
De-duplicate resolution error messages

### ISSUE THREAD

**Issue by melix** [gradle/gradle#11368]
## Context

A memory snapshot taken from a customer "large Android build" showed that during IDE sync, 1300+ resolution errors are kept in memory. Those are variant selection errors, and the error message is identical between all builds. This message is long so it wastes a large amount of memory.

We should think about deduplicating the strings for exceptions, or deduplicate the exceptions themselves.

**Comment by vlsi** [comment]
Have you seen the following? (Apache 2.0 code ahead) https://github.com/JetBrains/intellij-community/blob/e12af508c9fd8971760eaee80f54a586b671fac7/platform/util/src/com/intellij/openapi/util/objectTree/ThrowableInterner.java#L78-L81

:)
