### ISSUE TITLE
Provide public API to locate JVM or JDK installations and query their metadata

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#11391]
Introduce a public service that build logic can use to query metadata about a JVM or JDK installation at a particular location and also the current JVM.

This would be a simple step that would help teams that want to run Gradle and compile and test JVM based projects using different Java versions, and a step towards some high level way for the build logic to declare expectations about the JVM or JDK versions or implementations that should be used for these things.

### Expected Behavior

A public service that provides information about a Java installation, given its install directory. For example:

- Is it a JVM or JDK (or both)?
- Which Java version does it implement?
- What is the implementation name and version?
- What is the classpath (possibly empty) to use to compile against the tools APIs?
- Where are executables such as `java`, `javac`, etc, if present?

Also allow these things to be queried for the JVM that the build logic is running in.

Gradle's internals already know all this stuff. A simple skin over this would be very useful.

Such a service could later grow to allow a JVM or JDK of a particular version or implementation to be discovered using some conventions, possibly including some operating system specific conventions and some standard system properties or environment variables. The JVM could even be provisioned in some way, for example by grabbing binaries from https://adoptopenjdk.net.

Such a service could also be used by the Java plugins and other JVM based plugins to allow build logic to declare the target Java version or implementation for the project, where the build would fail if an appropriate JVM or JDK could not be discovered or provisioned.

Some examples where this would be useful:

- #10451
- #9146
- #2200
- #1652

### Current Behavior

Build logic authors are on their own with this problem. It's certainly possible to implement this kind of thing, but it's complicated to get right.

**Comment by adammurdoch** [comment]
Added the service via https://github.com/gradle/gradle/pull/11631

Still needs some documentation and/or samples.

**Comment by rieske** [comment]
Closing against 6.3. Release note is in place and further documentation will be added separately.

**Comment by ljacomet** [comment]
Cleared the milestone. While there is ongoing work on this topic, nothing will be delivered in 6.5

**Comment by ljacomet** [comment]
This is a currently active development topic, which will also result in smaller tasks to move forward. So closing this one in favor of smaller items.

**Comment by gliptak** [comment]
Were some documentation updates describing this API?

I'm trying to make a build compatible with both Java `8` an `11`. Adding

```
    testCompile files(org.gradle.internal.jvm.Jvm.current().toolsJar)
```

makes it work under `8` and fails under `11`

PS I ended up conditionally adding the JAR only under `8`

**Comment by ljacomet** [comment]
@gliptak This ended up looking somewhat different. Have a look at [the toolchain support](https://docs.gradle.org/6.8.1/userguide/toolchains.html)

**Comment by gliptak** [comment]
@ljacomet thank you for the pointer. Providing `tools.jar` location might have lesser relevance as don't seem to be required for `Java 11+`
