### ISSUE TITLE
Generate a dependency verification metadata file

### ISSUE THREAD

**Issue by melix** [gradle/gradle#11398]
## Context

Add a new CLI flag, like `--write-verification-metadata`, to generate a dependency verification file.

This file will constitute the initial reference for "dependency verification metadata". Ideally the implementation shouldn't be bound to a particular source, but it's not a requirement at this stage.

The file will most likely be an XML file.

Some comments:

- we know that ideally, folks should _never_ rely on automatically generated verification files because we can't trust the sources of artifacts.
- however, because checking repositories for checksums, or even because checksums are sometimes not available, it's tedious to generate this by hand, so a _bootstrapping_ method has to be provided.

This story is _not_ about consuming the metadata to actually do the verification. It's about writing an initial implementation of verification metadata generation to support this. Only checksums at this stage, and only for artifacts (so no generation for POM/IVY/GMM files).

**Comment by vlsi** [comment]
[TOFU](https://en.wikipedia.org/wiki/Trust_on_first_use) is a valid case for relying on generated files.

**Comment by ljacomet** [comment]
Merged, so done
