### ISSUE TITLE
"Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."

### ISSUE THREAD

**Issue by itsandreramon** [gradle/gradle#11390]
### Expected Behavior

"...making it incompatible with Gradle **6.0.**"

### Current Behavior

"...making it incompatible with Gradle **7.0.**"

### Context
When compiling via the CLI, Gradle shows the following message:
<img src="https://i.imgur.com/A73NAMl.png"/>

**Comment by melix** [comment]
This isn't a bug. This says exactly what it means. You are using features which are deprecated and your build will not work with 7.0. We just give you a chance to fix that before 7.0 is out.

**Comment by itsandreramon** [comment]
I am using Gradle 6 default init command, why should I be using deprecated features with default config?

**Comment by melix** [comment]
Can you elaborate what init parameters you used? Do you have an init script in your `.gradle` which would add plugins?
