### ISSUE TITLE
getResourceAsSteam not work in build.gradle

### ISSUE THREAD

**Issue by Dreampie** [gradle/gradle#1140]
```groovy
//build.gradle custom task
InputStream is = Thread.currentThread().getContextClassLoader().getResourceAsStream("thrift/Enums.thrift")
// is always null
```
// thrift/Enums.thrift in other jar
![image](https://cloud.githubusercontent.com/assets/3667080/21810963/ca50c48c-d788-11e6-8d55-ec0b99415eb0.png)

**Comment by lacasseio** [comment]
The GitHub issues are reserved for feature request and bug. Please use the [user forum](https://discuss.gradle.org/) for any question related to Gradle usage. In the event your question does turn out to be a valid GitHub issue, please follow the [contribution guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
