### ISSUE TITLE
Illegal reflective access using Lookup on org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper

### ISSUE THREAD

**Issue by iesen** [gradle/gradle#11407]
Getting illegal reflective access warnings on JDK 13 and Gradle 6.0. I am developing a custom gradle plugin and warnings appear while running tests. Tests use gradle ProjectBuilder fixture helper to validate the plugin behaviour.

### Expected Behavior

No warnings
### Current Behavior
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper (file:/C:/Users/40696163948ana/.gradle/caches/6.0/generated-gradle-jars/gradle-api-6.0.jar) to class java.lang.ClassLoader
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Context

I am developing a custom gradle plugin. While running unit tests (:test task) of the project, warnings appear. If task output results are cached warnings do not appear as expected.
### Steps to Reproduce 

Clean build, clear cache and run test task.
### Your Environment

.\gradlew -version output:

------------------------------------------------------------
Gradle 6.0
------------------------------------------------------------

Build time:   2019-11-08 18:12:12 UTC
Revision:     0a5b531749138f2f983f7c888fa7790bfc52d88a

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.1 (AdoptOpenJDK 13.0.1+9)
OS:           Windows 10 10.0 amd64

Build scan URL: 
https://scans.gradle.com/s/cb46f2qfp5ha2

**Comment by yogurtearl** [comment]
I am getting this error on JDK 11 as well, when running `:buildSrc:test`

**Comment by tobias-** [comment]
Still there in:

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Ubuntu 11.0.7+10-post-Ubuntu-3ubuntu1)
OS:           Linux 5.4.0-37-generic amd64

**Comment by bmuskalla** [comment]
In preparation for JDK16 (which fails on these), these warnings have been fixed in the 7.x stream.

**Comment by liutikas** [comment]
What commit fixes this issue? We are seeing this with Gradle 7.5-rc-5 (after upgrading from 7.5-rc-2)

```
> Task :buildSrc-tests:test
  WARNING: Illegal reflective access using Lookup on org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper (file:$GRADLE_USER_HOME/caches/7.5-rc-5/generated-gradle-jars/gradle-api-7.5-rc-5.jar) to class java.lang.ClassLoader
  WARNING: Please consider reporting this to the maintainers of org.gradle.internal.classloader.ClassLoaderUtils$AbstractClassLoaderLookuper
```

**Comment by yogurtearl** [comment]
this ticket was closed 18 months ago, so what you are seeing is likely a reoccurrence of a similar but different issue. 

I suggest that you file a new ticket with detail on how to [reproduce with nightly builds](https://services.gradle.org/distributions-snapshots/).
