### ISSUE TITLE
Remove org.gradle.kotlin.dsl.caching.buildcache

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11418]
The system property `org.gradle.kotlin.dsl.caching.buildcache` can currently be used to disable using the build cache for Kotlin scrips: https://github.com/gradle/gradle/blob/c2c5fd6d6fe470da6817fd0e287b5362bd2b07cf/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/cache/BuildServices.kt#L49

The property can now be removed completely, since Kotlin script caching is stable and can be disabled by disabling the build cache.

**Comment by bamboo** [comment]
We still want to do it, don't we?

**Comment by wolfs** [comment]
I added the 7.0 RC1 milestone.

**Comment by eskatos** [comment]
Done in https://github.com/gradle/gradle/pull/16082
