### ISSUE TITLE
 :buildSrc:configurePrecompiledScriptDependenciesResolver not incremental

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#11427]
Gradle 5.6.2 

### Expected Behavior
`:buildSrc:configurePrecompiledScriptDependenciesResolver`  **should declare outputs** so it can be incremental

### Current Behavior

 `:buildSrc:configurePrecompiledScriptDependenciesResolver`  declares no outputs, so it can't be incremental...

**Comment by big-guy** [comment]
This is expected right now.  There's not a way to make it incremental (since it doesn't produce outputs).  There's nothing to be gained since the work it does is the same as what would need to be done if it was incremental.
