### ISSUE TITLE
Use gradle to build java project, in the project root directory produced a. Gradle directory

### ISSUE THREAD

**Issue by GuaiShu** [gradle/gradle#1142]
Use gradle to build java project, in the project root directory produced a. Gradle directory, I would like to ask what is the use of this directory.

**Comment by lacasseio** [comment]
Thanks @GuaiShu for your interest in Gradle. The GitHub issues are strictly reserved for bugs and feature request and need to follow the [contribution guideline](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md). Any questions or discussion should be directed to the [user forum](https://discuss.gradle.org/).

That been said, the `.gradle` folder is used for caching any information for your particular build. See [`--project-cache-dir`](https://docs.gradle.org/current/userguide/gradle_command_line.html) for a bit more information. For questions like this one, we highly encourage the user to first search for an answer on the [user forum](https://discuss.gradle.org/) or through your favorite search engine.
