### ISSUE TITLE
STRING_TOO_LARGE error doesn't fail the build

### ISSUE THREAD

**Issue by kubotron** [gradle/gradle#11420]
The 3.5.1 version of the Android Gradle Plugin is replacing large strings with "STRING_TOO_LARGE". It is logged as a build error in the console, as far as I understand it. It doesn't fail the build, however. Is this the intended behavior? 

This leads to situations where a critical string is replaced but it is not immediately noticed. It seems that the previous versions of the Android Gradle Plugin were handling large strings fine.

**Comment by big-guy** [comment]
We don't maintain the Android Gradle plugin.  I didn't see an issue for this on their issue tracker, so it would be [worth reporting your issue there](https://issuetracker.google.com/issues/new?component=192709&template=842921).

Thanks!
