### ISSUE TITLE
Worker API actions should not have access to mutable project state via `ProjectLayout`

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#11434]
`ProjectLayout` allows mutation of the project state, via `getBuildDirectory().set()` and friends, and indirectly via `getBuildDirectory().get()`. Generally, we don't allow access to the mutable project state from concurrent work, to avoid confusing and impossible to reproduce reliability issues.

### Expected Behavior

There are a few options:

1. Inject an instance of `ProjectLayout` whose values are isolated from the project and build directories, and whose mutation methods throw an exception.
2. Finalize the build directory prior to running any worker actions, so that the build directory can safely be queried from multiple threads.
3. Don't inject `ProjectLayout`, and the author can pass any locations required by the action as parameters.

I think item 3 (and separately, item 2 for other reasons) is the best option here. It doesn't really make sense for a worker _action_ to access the project layout as this almost certainly means the action is hard-coding or duplicating some convention that lives, or should live, higher up.

This is also important for caching in the future, as requiring the project layout essentially says "I may need something from the project or build directories, but I'm not going to tell you what", whereas passing the locations via the parameters makes it more likely that the inputs and outputs are already expressed and can be annotated easily.

Finally, this also removes the mutation methods, which would always fail, from the APIs that the worker action author sees in places such as content completion or documentation, making the process of writing an action simpler and less confusing.

### Current Behavior

Work actions can mutate the build directory and other project state, possibly unintentionally, potentially producing unexpected results when other work is happening concurrently.

### Your Environment

Build scan URL:

**Comment by ghale** [comment]
Thanks, @adammurdoch.  The thinking here was to make the injectable types consistent with what could be injected in other managed types.  It didn't occur to me that the getters in `ProjectLayout` effectively exposed mutable state.  We'll definitely need to fix this.

**Comment by adammurdoch** [comment]
@big-guy can we close this now?

**Comment by ghale** [comment]
This was fixed many moons ago.
