### ISSUE TITLE
Could not compile settings file 'android\settings.gradle'.

### ISSUE THREAD

**Issue by barmola** [gradle/gradle#11430]
I have set up fresh project and haven't installed any dependencies but while running the project i am getting this error.

I have gone through some similar issues which got resolved by replacing "\" with "/" in settings.gradle file but my settings.gradle already have "/",

I have also tried to run ./gradlew clean inside \android folder but nothing works out

```
* Where:
Settings file 'android\settings.gradle'

* What went wrong:
Could not compile settings file 'android\settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57
```

**Comment by big-guy** [comment]
It looks like you are using Java 13, but a version of Gradle that does not support Java 13 (only 6.0 and up).

**Comment by nageswararaorachapathi** [comment]
@big-guy, you are absolutely correct, the issue is with java 13. I have downgraded it to java8 and it is resolved now.
Thank you

**Comment by abuthahir-19** [comment]
how to do like that (i.e downgrading to java 8)

**Comment by musaatalay1** [comment]
> rootProject.name = 'timer' apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings) include ':app' hai this is my gradle setting file.
> 
> error: info Starting JS server... info Installing the app...
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Settings file 'D:\GitHub\timer\android\settings.gradle'
> * What went wrong:
>   Could not compile settings file 'D:\GitHub\timer\android\settings.gradle'.
> 
> > startup failed:
> > General error during semantic analysis: Unsupported class file major version 60
> 
> java.lang.IllegalArgumentException: Unsupported class file major version 60 at groovyjarjarasm.asm.ClassReader.(ClassReader.java:196) at groovyjarjarasm.asm.ClassReader.(ClassReader.java:177) at groovyjarjarasm.asm.ClassReader.(ClassReader.java:163) so on please help me ![26 10 2021_15 03 09_REC](https://user-images.githubusercontent.com/36436915/138851682-a5456fb7-aa56-4693-90cc-d5ae7c789ac9.png)

have you managed to solve issue an how?

**Comment by haduc25** [comment]
nah i have same error :<
