### ISSUE TITLE
Junit5 @DisplayName is ignored in junit.xml file

### ISSUE THREAD

**Issue by wr-pkazlenka** [gradle/gradle#11445]
junit.xml file generated by gradle for junit5 tests ignores '@DisplayName' annotation for tests and uses test method name instead
### Expected Behavior
I expect that @DisplayName value is used for '<testcase name=' attribute in generated xml file (when provided, of course)
### Current Behavior
Test method name is used for '<testcase name=' attribute in generated xml file even when @DisplayName exists
### Context
I am going to use CI (Jenkins) in a chain Junit tests -> junit.xml -> CI -> Jira test results. In order to achieve this, I need test case names in junit.xml to be exactly the same as they are stored in Jira (we use zephyr plugin to manage tests): e.g. 'Test Case 1', not 'testCase1()'.

### Steps to Reproduce 
Test class:
```java
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("Displayed Name for Class")
public class TestClass {
    @Test
    @DisplayName("Displayed Name For Test")
    void test1() {

    }
}
```
build.gradle
```groovy
plugins {
    id 'java'
}

group 'reports'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.1.0'
}
```
Run gradle test
In build/test-results/test/TEST-TestClass.xml: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestClass" tests="1" skipped="0" failures="0" errors="0" timestamp="2019-11-22T13:49:44" hostname="localhost" time="0.005">
  <properties/>
  <testcase name="test1()" classname="TestClass" time="0.005"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```
Expected to have:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Displayed Name for Class" tests="1" skipped="0" failures="0" errors="0" timestamp="2019-11-22T13:49:44" hostname="localhost" time="0.005">
  <properties/>
  <testcase name="Displayed Name For Test" classname="Displayed Name for Class" time="0.005"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```
### Your Environment
gradle 6.0.1
Java 13
Junit 5.3.1
Build scan URL:

**Comment by cynic783** [comment]
Yes, we are observing the same problem with @DisplayName not being honored.

Also, the `@ParameterizedTest` name attribute is not honored.  e.g.

`@ParameterizedTest(name = "{index} ==> {0}: {1}")`

Observed:
`com.acme.MyTest.testFoo(String, Boolean...)`
Expected:
`1==>Fred, Jones`
