### ISSUE TITLE
Streamline Plugin Development

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1144]
## Objective
Maximize the breadth and depth of the Gradle Build Tool plugin ecosystem by making it easier to design, write, document, test, and publish plugins.

## Motivation
Writing Gradle plugins can be difficult, even for Gradle engineers. We cannot maintain a healthy ecosystem or get into new technologies without our users.

## Implementation
- Create public APIs for common plugin functionality
- Write guide(s) for designing, writing, documenting, testing, and publishing plugins.
  - Make every single one of those steps as easy as possible
- Provide a few good concrete examples of well-written plugins. Publicize them as such.
- Provide guidance for high-impact plugins/authors

**Comment by bamboo** [comment]
It should also include advice on writing plugin models that work well with both Groovy and Kotlin DSLs.

**Comment by bmuschko** [comment]
@bamboo Is writing a plugin with Kotlin really very different from writing a plugin in any other JVM language? The API is the same.

**Comment by bamboo** [comment]
@bmuschko You're right, it's not very different but I didn't mean we should incoude advice on writing plugins in Kotlin. I meant we should include advice on writing plugins (in any JVM language) whose contributed extensions and tasks can be just as easily used / configured from Kotlin based _build scripts_ as they are from Groovy build scripts. That mostly means not creating models based on Groovy types or metaprogramming tricks such as `groovy.lang.Closure` and `methodMissing`. Instead, plugins should base their models on Gradle API types and patterns such as `Action<T>`, domain object containers, etc.

**Comment by adammurdoch** [comment]
We might also start inspecting for or even deprecate certain Groovy patterns for a plugin's model and task types. We already inspect certain aspects of a plugin's types at plugin build time, and there's a lot of stuff we might do at runtime as well.

**Comment by jjohannes** [comment]
This is no longer use to track work. Instead we use the [in:plugin-development](https://github.com/gradle/gradle/labels/in%3Aplugin-development) label.
