### ISSUE TITLE
Provide a way to access Gradle module metadata files from dependency resolution

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#11449]
There is currently a way, through `ArtifactResolutionQuery`, to get at the POM files for a dependency resolution result.
Gradle should offer a similar access to the Gradle Module Metadata file.

While it might make sense to offer access to metadata through the `ResolvableDependencies` in the future, this does not mean a more direct / custom access is not needed for specific use cases.

**Comment by jjohannes** [comment]
Closing this as the use case can be addressed with component metadata rules:
https://github.com/gradle/gradle/blob/fd9eb88be349f2fb35372c6f4bd2a0bd205be57e/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/rules/VariantFilesMetadataRulesIntegrationTest.groovy#L87-L114

(improved by #11565 in 6.1)
