### ISSUE TITLE
Allow @option to be used with configuration extensions

### ISSUE THREAD

**Issue by jeremylong** [gradle/gradle#11456]
As recommended in the gradle documentation - most plugins use extensions to add configuration options (doc ref: [Making the Plugin Configurable](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:getting_input_from_the_build)).

The `@Option` attribute is extremely useful as well.  However, the `@Option` attribute is only available on tasks - it would be very helpful if the @Option attribute could be used within an extension.

### Desired Behavior
It would be great if we could add `@Option` using the following:

```groovy
class GreetingPluginExtension {
    @Option("message", "The greeting message")
    String message = 'Hello from GreetingPlugin'
}

class GreetingPlugin implements Plugin<Project> {
    void apply(Project project) {
        // Add the 'greeting' extension object
        def extension = project.extensions.create('greeting', GreetingPluginExtension)
        // Add a task that uses configuration from the extension object
        project.task('hello') {
            doLast {
                println extension.message
            }
        }
    }
}

apply plugin: GreetingPlugin
```

__Output of `gradle -q hello --message "Wassup from greeting plugin"`__
```
> gradle -q hello --message "Wassup from greeting plugin"
Wassup from greeting plugin
```

**Comment by lacasseio** [comment]
It's an interesting concept. I'm not sure the `@Option` API where meant to be use with the model in any way. It is possible to workaround this by using System (`-D<prop>=<value>`) or Project (`-P<prop>=<value>`) properties. If I remember correctly, I think that using `-Pgreeting.message="Wassup from greeting plugin"` would actually work without any custom code given the extension name isn't colliding with any properties on `Project` object. However, there is no way to discover what is currently configurable. It would probably be a good idea to may these feature more discoverable if we go down that line. Maybe giving a description to the `Property` object so we can list them and the register extensions when requesting help on the project, kind of like the `model` task of the Software Model.

**Comment by jeremylong** [comment]
The `-P<prop>=value` does not appear to work with extensions - am I missing something?

__Output of gradle -q hello -Pgreeting.message="Wassup from greeting plugin"__
```
> gradle -q hello -Pgreeting.message="Wassup from greeting plugin"
Hello from GreetingPlugin
```

**Comment by lacasseio** [comment]
It looks like I miss read the code. It's mostly a feature that would be coming from `DynamicObject`. However, it's an internal API and doesn't seems to treat extensions as properties to be accessed by the project properties. You are left with wiring everything yourself.

```
greeting.message = hasProperty('message') ? getProperty('message') : 'Hello from GreetingPlugin'
```

The question we are wondering is why would you want to configure the extension via the command line? What kind of use case are you looking at solving?

**Comment by jeremylong** [comment]
This comes from a ticket posted to [dependency-check-gradle#161](https://github.com/jeremylong/dependency-check-gradle/issues/161). The plugin performs software composition analysis and can be configured to fail the build if a vulnerability is identified in one of the dependencies and has a CVSS score above a configured level.  Their use case would be being able to adjust the CVSS threshold (i.e. the build may be configured to have it fail on a CVSS of 7.0 - but a developer may want to locally complete a successful build without having to modify the build.gradle while they finish solving their current task without having to fix the vulnerable component immediately).

In other cases one may want to `skip` the analysis - but allowing the task developer to keep all the configuration in one place (the extension). If we could put an @Option (or similar) on a configuration task we could more easily allow disabling a task.
