### ISSUE TITLE
JavaScript Support

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1145]
## Objective
Empower users to build applications using JavaScript with Gradle

## Motivation
Adding just 1% of the web community would significantly grow Gradle user base

## Approach
* Educate users through guides and examples how and why to take advantage of Gradle’s unique features
  * Write a guide on best practices for calling Gulp, Webpack, etc. through Gradle
* Explore ways for users to call Gradle through JS tools of choice
   * Spike gulp-gradle-plugin
* Invest in [gradle-node-plugin](https://github.com/srs/gradle-node-plugin)
  * Provide guidance and technical improvements where necessary

**Comment by bmuschko** [comment]
@eriwen Should we close this for now?

**Comment by eriwen** [comment]
@bmuschko No, we're still discussing prioritizing some JS support in 2018. If we decide to omit it, I'm okay with closing this at that time.

**Comment by jjohannes** [comment]
There are no concrete plans for this in the foreseeable future.
