### ISSUE TITLE
Warn if maven- or ivy-publish is publishing an artifact under a different name and allow custom names

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#11473]
By default, naming conventions are used for naming artifacts to make them discoverable by Maven/Ivy. This can be confusing because if the name of a file is configured in the build, for example in an archive task, this name is never used. Often, this is just a mistake in the build. Instead of changing the name, build authors might want to set the `archiveClassifier` to get a customized name that also follows Maven/Ivy conventions.

The publishing plugin should warn about this potential missconfiugration by comparing the file name to the actual _published name_. For example [here](https://github.com/gradle/gradle/blob/f2436d7d6eb45e693adee43402000845e8abf7a4/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java#L703).

**Comment by ljacomet** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
