### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings warning with Custom Plugin not using Logging API

### ISSUE THREAD

**Issue by chhex** [gradle/gradle#11479]
### Expected Behavior

It seems be good practice to separate Gradle Plugin code into code and tests which do not depend on any Gradle API and Gradle Plugin specific code , see also https://github.com/gradle-guides/testing-gradle-plugins/tree/master/samples/code/url-verifier-plugin

Logging for the Gradle API dependent code is straight forward and well supported.

For the Gradle API independent code, i assumed that you can  pretty much use any logging framework. I used SLF4j, as that’s what Gradle’s API extends from. The only limitation being that you won’t have access to Gradle specific logging levels such as LIFECYCLE or QUIET.

I added a 
`    implementation("org.slf4j:slf4j-api:1.7.25")`
dependency 

For Integration Testing i added 
`  integrationTestRuntimeOnly("org.slf4j:slf4j-simple:1.7.29")`

with a 
```
val integrationTestRuntimeOnly: Configuration by configurations.getting {
    extendsFrom(configurations.testRuntimeOnly.get())
}
```

To my build

My expectation where  Logging according to Log Level in the Functional Gradle Dependent tests and in the Integration Tests, specifically of the application level code, see https://github.com/apgsga-it/apg-gradle-plugins/blob/che-IT-34786-2/dependency-manager/src/main/kotlin/com/apgsga/maven/LoggerDelegate.kt

### Current Behavior
Logging as expected , except for  slf4j warnings: 
`SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/Users/chhex/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.29/82ae07f95088577987a15d90171de12b00d81847/slf4j-simple-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/Users/chhex/.gradle/caches/5.0/generated-gradle-jars/gradle-api-5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
`

If i remove the 

`    implementation("org.slf4j:slf4j-api:1.7.25")`

dependency i don't get log output according to log level for the Integration Tests.  

Unexpected:  SLF4J: Found binding in [jar:file:/Users/chhex/.gradle/caches/5.0/generated-gradle-jars/gradle-api-5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]

I do not see, where this runtime dependency comes from and how to avoid it, specially since on application level i do not have any Gradle Dependencies. 

### Context

We often start with separating Gradle Dependent Code from API independent code and eventually may move the independent code to a seperate jar, so that it can be used in other context's then as Gradle Plugin.  
### Steps to Reproduce 

If necessary i should be easily  be able to reproduce the problem with for example the https://github.com/gradle-guides/testing-gradle-plugins/tree/master/samples/code/url-verifier-plugin

### Your Environment

Build scan URL:
https://gradle.com/s/kmg7r3jflrews

See https://scans.gradle.com/s/kmg7r3jflrews/dependencies?toggled=W1syXSxbMiwxNl1d#configurationId=16&projectId=2

**Comment by lptr** [comment]
This is still a problem.

**Comment by ljacomet** [comment]
Given the following:
* We are missing a full reproducer for this issue.
* Testing of generic `java-library` for sure does not have a problem with Gradle API shaded version of a slf4j logger.
So it might be that the issue comes from using a single Gradle project for both scopes.

There are multiple ways of creating "Gradle independent" elements for your plugin, and we can't know which one was used. So the issue will be closed. We will consider it if a full reproducer is shared.
