### ISSUE TITLE
EclipsePlugin sets incorrect javaRuntimeName for older target runtimes

### ISSUE THREAD

**Issue by donat** [gradle/gradle#1148]
### Expected Behavior

The convention mapping should set the following `javaRuntimeName` depending on the current `targetCompatibility`:

    JavaSE-1.8
    JavaSE-1.7
    JavaSE-1.6
    J2SE-1.5
    J2SE-1.4
    J2SE-1.3
    J2SE-1.2
    JRE-1.1

These values are declared as [defaults](https://github.com/eclipse/eclipse.jdt.debug/blob/master/org.eclipse.jdt.launching/plugin.xml#L241-L303) in the Eclipse platform.

### Current Behavior

The convention mapping sets `javaRuntimeName` to `JavaSE-1.x`. 

### Context

https://discuss.gradle.org/t/building-with-newer-jdks/21102/5

### Steps to Reproduce (for bugs)

Import a Java project into Buildship with `targetCompatibility=1.5` configuration.

**Comment by donat** [comment]
The release branching is coming very soon so I've assigned this story to the next release.

**Comment by jjohannes** [comment]
LGTM 👍

**Comment by donat** [comment]
Thanks for the review, @jjohannes!
