### ISSUE TITLE
Task input property is not really nullable

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#11483]
### Expected Behavior
I should be able to register a property not caring if it is null or not. The parameter is annotated as `@Nullable`, see [6.0.1 JavaDoc](https://docs.gradle.org/6.0.1/javadoc/org/gradle/api/tasks/TaskInputs.html#property-java.lang.String-java.lang.Object-).

### Current Behavior
Running the task fails with an exception:
```
A problem was found with the configuration of task ':test'.
> No value has been specified for property 'myProp'.
```

### Context
I wanted to set a task input property from a system environment variable

### Steps to Reproduce 
Create a project using 'gradle init' and append:
```
test {
    inputs.property 'myProp', System.getenv('NON_EXISTENT')
}
```
then run `./gradlew test`

### Your Environment
I get an exception for Gradle versions between 5.0 and 6.0.1.

Gradle 4.10.2 runs correctly (doing correct up-to-date checks based on env var value) without any problems.

**Comment by lptr** [comment]
We had a plan to support `@Nullable` as an alternative to `@Optional`. I guess we should do it.

**Comment by wolfs** [comment]
@pkubowicz The argument is `@Nullable`, though you need to also declare that you actually expect the parameter to take null values by using
```
inputs.property('myProp', System.getenv('NON_EXISTENT')).optional(true)
```

By default, Gradle assumes you are declaring a non-null (aka optional) property.

**Comment by pkubowicz** [comment]
I understand your explanation _why_ Gradle currently behaves as it does, but I still believe it needs to be fixed. What you showed in the snippet is lots of writing just to make a system property a task input property, which is probably the most often use case for task input property. 

Also please note that this is a change of behaviour from Gradle 4.10.2.

**Comment by wolfs** [comment]
> I understand your explanation why Gradle currently behaves as it does, but I still believe it needs to be fixed. What you showed in the snippet is lots of writing just to make a system property a task input property, which is probably the most often use case for task input property.

What would you suggest as fix? You want to easily be able to register an optional system property as input for the `Test` task? Or an environment variable?

For the system property, there already is a way: use `Test.systemProperty`. Since system properties are opt-in for the `Test` task, this is even required for passing a system property.

All environment variables are currently passed to the `Test` task without tracking any of them. I suppose it depends on the `Test` task whether a given environment variable it needs to be tracked and whether it needs to be set or not.

Gradle should probably provide a shortcut to declare those environment variables, though I am not convinced that the default should allow environment variables to be unset.

> Also please note that this is a change of behaviour from Gradle 4.10.2.

Gradle should emit a deprecation warning in 4.10 and fail with Gradle 5.0. Can you confirm this?

**Comment by pkubowicz** [comment]
Yes, I get a message with Gradle 4.10.2:
```
Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated. This is scheduled to be removed in Gradle 5.0. A problem was found with the configuration of task ':test'.
 - No value has been specified for property 'myProp'.
```
I don't think it's a problem specific to Test task. There are many cases where the result of a task depends on the state of a particular env var: it can be running NodeJS or any other executable that reads environment variables inside. In my case some of Java tests are skipped depending on an env var, so I want to track this env var.

Environment variable not being set is a perfectly normal situation and I don't understand why it should be treated specially.

From build script author perspective: having a nullable public method parameter that causes the method call to fail when null is passed is very puzzling. You can remove `@Nullable` annotation and force users to write `System.getenv('MY_VAR') ?: ''` - with Elvis operator this is not that much writing, and definitely less than appending `.optional(true)`.

**Comment by wolfs** [comment]
I opened https://github.com/gradle/gradle/issues/11534 to track the feature request (easier way to track environment variables). Please comment on it if you think I forgot something form the discussion above. I'll close this issue now as superseded by https://github.com/gradle/gradle/issues/11534.
