### ISSUE TITLE
Warn when changing copy specs during copy task is executing

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#1149]
Users sometimes change the copy specs of a copy or archive task (e.g. `Jar`) in a `doFirst()` call. These changes are ignored by up-to-date checks and task output caching, but we don't show any warning about them.

We should forbid this behavior in the long run completely. As a first step we should show a warning about the problem and mention that we're going to be more strict in the next major release.

### Steps to Reproduce (for bugs)

This also doesn't just affect users, as we had this problem in the Gradle build itself (see https://github.com/gradle/gradle/pull/791).

**Comment by eriwen** [comment]
Seems related to #1131
