### ISSUE TITLE
Groovy plugin improperly sets target bytecode version

### ISSUE THREAD

**Issue by dovchinnikov** [gradle/gradle#11497]
```groovy
apply plugin: 'java'
apply plugin: 'groovy'
sourceCompatibility = 10
targetCompatibility = 10
println "Java: $compileJava.targetCompatibility"
println "Groovy: $compileGroovy.targetCompatibility"
```
When run prints:
```
Java: 1.10
Groovy: 1.10
```

The same string (`'1.10'`) in `org.gradle.api.internal.tasks.compile.ApiGroovyCompiler#execute` is passed to `org.codehaus.groovy.control.CompilerConfiguration#setTargetBytecode` where it gets ignored, since Groovy knows about `'10'` only.

### Expected Behavior
Generated classes have 10 version.

### Current Behavior
Generated classes have 7 version.

### Context
Spock should fail, but it works since generated classes are of 7 version.
https://github.com/spockframework/spock/issues/1011

### Steps to Reproduce
```
$ git clone git@github.com:dovchinnikov/gradle-groovy-target-bytecode-bug.git && cd gradle-groovy-target-bytecode-bug
$ ./gradlew classes --no-daemon
$ javap -v build/classes/groovy/main/com/Foo.class
...
public class com.Foo implements groovy.lang.GroovyObject
  minor version: 0
  major version: 51
...
```

### Your Environment
```
$ ./gradlew -version

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.6 x86_64
```

### Workaround
Set the target bytecode version directly to the task:
```
tasks.withType(GroovyCompile) {
  targetCompatibility = 10
}
```

**Comment by ov7a** [comment]
[Fixed in 8.0](https://docs.gradle.org/current/userguide/upgrading_version_7.html#format_of_javaversion_has_changed_for_java_9_and_java_10):

> The string format of the JavaVersion has changed to match the official Java versioning. Starting from Java 9, the language version must not contain the 1. prefix.
