### ISSUE TITLE
Misleading Error "Could not create SecurityManager" caused by empty entry in forkOptions.jvmArgs

### ISSUE THREAD

**Issue by decoded4620** [gradle/gradle#11490]
Currently in JVM Based gradle Projects (e.g. Java Application, Play, Scala), if you have invalid `forkOptions.jvmArgs` entry (such as an empty string) within a `tasks.withType` closure in a build script  (`build.gradle`) 
e.g.
```groovy
tasks.withType(PlayRun) {
        forkOptions.jvmArgs = ["-DXms4g", "", "-DXmx8g"]
}
```

or

```groovy
tasks.withType(PlayRun) {
        forkOptions.jvmArgs = ["", "-DXmx8g"]
}
```

This can feasibly happen with `ScalaForkOptions`, `PlayForkOptions`, `JavaForkOptions`, etc. 

Current Behavior: you will receive this error:

```bash
Successfully started process 'Gradle Play Worker 5'
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager: worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager
        at sun.misc.Launcher.<init>(Launcher.java:106)
        at sun.misc.Launcher.<clinit>(Launcher.java:54)
        at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1444)
        at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1429)
```

This naturally led me to https://github.com/gradle/gradle/issues/4689 (which is a closed issue).
You'll see in that issue that  @dlehammer (https://github.com/dlehammer) mentions "leading space" as a possible cause which is, as this bug will describes, only partially true.

I do not think this should be considered closed. I looked through the code but was unable to see where the core logic that builds the eventual command to run the JVM. But this code should instead do one the following:

1. Filter out any "empty string" entries and silently "fix" the users mistake
2. Cry out in pain and fail if there is an empty entry, e.g. Fail the build, don't wait until runtime gets ahold of it and prints obscure errors with little or no easy reasoning behind them.

### Context
Our app uses dynamic values to build the jvm string. Having an error mentioning that one of our values was empty would have reduced a significant amount time to understand it was a user-error and not a system error.

### Steps to Reproduce 
I'll use "Play" as an example here, although this is *not a Play Bug*, it is a bug in how the JVM command is constructed using `ForkOptions`

1. Create a Vanilla Play application project
2. Create an "invalid" `tasks.withType(PlayRun)` closure in the root of the build script using one of the examples above.
3. Try `gradle runPlayBinary --info`
4. Observe the obscure error

### Your Environment
OSX Catalina
Gradle 5.6.2 or Gradle 5.6.3
Play 2.6.22
Java 1.8.232-zulu

**Comment by DPUkyle** [comment]
Hey Bow; maybe improve the setter to add some preprocessing like trim and remove empty strings?

https://github.com/gradle/gradle/blob/master/subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java#L89

(And while you're at it, remove that stupid Guava initializer :trollface: )

**Comment by DPUkyle** [comment]
Maybe something like this (based on v5.6.4, but should work):

```
Index: subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java	(date 1572422661000)
+++ subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/BaseForkOptions.java	(date 1575307768871)
@@ -15,13 +15,14 @@
  */
 package org.gradle.api.tasks.compile;
 
-import com.google.common.collect.Lists;
 import org.gradle.api.tasks.Input;
 import org.gradle.api.tasks.Internal;
 import org.gradle.api.tasks.Optional;
 
 import javax.annotation.Nullable;
+import java.util.ArrayList;
 import java.util.List;
+import java.util.stream.Collectors;
 
 /**
  * Fork options for compilation. Only take effect if {@code fork}
@@ -34,7 +35,7 @@
 
     private String memoryMaximumSize;
 
-    private List<String> jvmArgs = Lists.newArrayList();
+    private List<String> jvmArgs = new ArrayList<>();
 
     /**
      * Returns the initial heap size for the compiler process.
@@ -86,7 +87,7 @@
      * Defaults to the empty list.
      */
     public void setJvmArgs(@Nullable List<String> jvmArgs) {
-        this.jvmArgs = jvmArgs;
+        this.jvmArgs = jvmArgs == null ? null : jvmArgs.stream().map(String::trim).filter(s -> !s.isEmpty()).collect(Collectors.toList());
     }
 
     @Override
```

**Comment by decoded4620** [comment]
I'm on it! I'll provide a test as well to ensure it works as expected! Thanks @DPUkyle
