### ISSUE TITLE
The value returned by JavaExec.execResult should be treated as an output of the task

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#11492]
It should be possible to connect the `Provider` returned by `JavaExec.getExecResult()` into an `@Input` property of another task, and have Gradle infer the task dependency.

### Expected Behavior

A task can consume the `ExecResult` of a `JavaExec` task.

Ideally, if inputs and outputs of the exec task are declared, then the result would be persisted and continue to be available if the task is later up-to-date.

Also, both the `Exec` and `JavaExec` tasks should have the same APIs for doing this.

### Current Behavior

The task dependency information is not carried by the provider, the result is also lost between invocations, and the APIs for `Exec` and `JavaExec` are different.

**Comment by ldaley** [comment]
Can you give an example of a useful use of this?

**Comment by adammurdoch** [comment]
It would be useful whenever the command is expected to fail and you want to do something in response to this. For example, the command may be a tool that performs some validation and I want to generate a report from this and include information about whether the validation succeeded or not, or whether the whole thing just blew up. Or the command may be a tool that probes the state of something and communicates this through the return code. For example, I might check the dirty state of the git repo and then do something based on this.

Another option, instead of modelling the result, would be to insist that people always use `exec { }` and a custom task type to do this kind of thing, and remove `execResult` from these tasks types. Right now we have this half implemented output/result value, and we should either finish implementing it or remove it.

**Comment by ldaley** [comment]
I see.

Seems like it would be better to offer something along the lines of your second paragraph. But, there might be a more convenient middle ground in reducing the boiler plate and ceremony needed to do this, which from my experience is a reason that people use the raw Exec tasks and the like.

In particular, we should be encouraging people to have such tasks fail better than “Process exited with non zero error code”, and that's rather cumbersome to do currently.

**Comment by ov7a** [comment]
Currently, the following code:
```
            apply plugin: "java"

            def run = tasks.register("run", Exec) {
                dependsOn(compileJava)
                executable = org.gradle.internal.jvm.Jvm.current().javaExecutable
                args '-cp', project.layout.files(compileJava).asPath, 'driver.Driver', "1"
            }
        
            abstract class VerifyTask extends DefaultTask {
                @Input
                @Optional
                abstract Property<Integer> getExitValue()

                @TaskAction
                void verify() {
                    println("Exit value: " + exitValue.getOrNull())
                }
            }

            tasks.register("verify", VerifyTask) {
                dependsOn(run)
                exitValue.set(run.flatMap { task -> task.executionResult.map { it.exitValue } })
            }
```
Leads to 
```
Exit value: null
```

with configuration cache enabled. Works fine with Vintage
