### ISSUE TITLE
Gradle 5.6.x-6.7 erratic behaviour with platforms and rich version with version ranges

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#11503]
### Expected Behavior
An enforced platform and a platform are applied to a configuration.
The enforced platform specifies a range i.e. [7,8) for a transitive dependency that is brought in by multiple direct dependencies.
The highest revision of that dependency which satisfies the applied constraint should be selected.

### Current Behavior
Fails in all gradle 5.6.x and the lowest revision is selected instead.

### Context
Works correctly in gradle 5.5.1. Both in 5.5.1 and 5.6.x the dependencyInsight gives as selection reasons "By constraint" and "Forced", but 5.5.1 selects the highest revision as per documentation while 5.6.x gets the lowest.

**Comment by jjohannes** [comment]
Hi @sacchettom. Thanks for reporting. The expected behavior sounds correct, but we are not aware that it changed (in general) in 5.6.x. There can be a lot of possible reasons why you observe this behavior or why a possible regression is caused. Many features interact in dependency resolution.

Please provide a reproducible example.

**Comment by sacchettom** [comment]
@jjohannes sorry for the delay, it took a lot of time to reproduce but I finally found the issue. 
[Archive.zip](https://github.com/gradle/gradle/files/3905517/Archive.zip)

Between gradle 5.5.1 and 5.6 something seems to have broken the resolution strategy when facing dependency ranges in the bom/platform. If you look at the example, it will resolve (as expected) `org.apache.commons:commons-lang3` version `3.9` with gradle 5.5.1, but version `3.4` with gradle 5.6.x (I've tried the original 5.6 and the last 2 minors and they were all affected). In the example switching line 9 of the local platform project from `api 'org.apache.commons:commons-lang3:[3,5)'` to `api 'org.apache.commons:commons-lang3:3+'` fixes the issue.

**Comment by ljacomet** [comment]
I believe I understand what happened:
* You are using `enforcedPlatform` which relies on a `force` under the hood.
* But the version to be enforced is a range
* In Gradle 5.6 we did changes around version selection to improve performance in some cases. This improvement changed the way we order selectors.
* It looks like an undetected side effect of that change is that when forcing a range, we end up forcing the _first_ version which is not a range that enters resolution.

Two workarounds for now:
* Use `platform` instead of `enforcedPlatform`
* Use a fixed version in the platform instead of a range

**Comment by sacchettom** [comment]
The workarounds unluckily are not fit for our use case. Using `platform` unluckily brings in a number of higher revision transitives that we don't want, and since we apply the platform to a large number of projects, manually adding exclusions to each one of them isn't something I'm really willing to do.
The fixed version at the same time is something we don't want as some modules get updated very often, so we rather want to depend on dependency locks.
I guess that for now my fix is to revert back to 5.5.1. Any possibilities a patch will be made for this issue on gradle 5.6?

**Comment by jjohannes** [comment]
@sacchettom if you are able to move to Gradle 6, we have the new concept of strict versions that you can define in the platform itself:
https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version

It is the preferred method from 6 onwards, because "force", the way it works, will always be order dependent and can cause issues like the one you encounter. We might be able to move `enforcedPlatform` away from using `force` under the hood, but there are no concrete plans yet.

Currently we recommend: _platform_ + _strict versions_. (That's why _platform_ is stable in 6, but _enforcedPlatform_ stays incubating.)

**Comment by sacchettom** [comment]
Not planning to do upgrades to Gradle6 until next year, as we need to evaluate the compatibility of some internal plugins. I have read about the strict versions now but unluckily they show to me the same issue of adding exclusions - that must be done project by project, where with an enforced platform we can just publish the changes we want into a new bom and then get that applied to a wide number of projects without having to edit the gradle code at all. I'm thinking that probably the best way to go would be to use a normal platform for version suggestions, and then use the nebula dependency rules plugin whenever we need to enforce anything.

**Comment by sacchettom** [comment]
Is there any plan to fix this issue? I see weird implications of how dependency resolution works affecting the whole platform thing as far as gradle 6.7, it's not documented and to be honest it makes the whole platform (not just the enforced platform, I'm seeing issues with the normal one as well) unreliable.
What I'm seeing today for example is the following, with a normal platform applied to a configuration:
```
api "dependency:6.+"  ->  makes the configuration get the latest 6.+ version from the repository
api "dependency:[6,7]"  ->  makes the configuration get the last 6.+ in the dependency tree
api "dependency", { version { require '6.+' } } -> makes the configuration get the latest 6.+ version
api "dependency", { version { require '[6,7]' } } -> gets the last 6.+ already in the dependency tree
api "dependency", { version { strictly '[6,7]' } } -> gets the latest 6.+ version from the repository
```

**Comment by sacchettom** [comment]
It doesn't even apply just to configurations, normal dependency resolution and rich versioning is affected:
```groovy
apply plugin: 'base'
apply plugin: 'java'

repositories {
  jcenter()
}

version='1.0.0'

buildscript {
  repositories { jcenter() }
}

group = 'com.test'

dependencies {
  implementation group: 'org.apache.commons', name: 'commons-text', version: '1.7'
  implementation group: 'com.nimbusds', name: 'oauth2-oidc-sdk', version: '5.22.1'
  //implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.+'
  //implementation group: 'org.apache.commons', name: 'commons-lang3', version: '[3,4]'
  //implementation group: 'org.apache.commons', name: 'commons-lang3', { version { require '3.+' } }
  //implementation group: 'org.apache.commons', name: 'commons-lang3', { version { require '[3,4]' } }
  //implementation group: 'org.apache.commons', name: 'commons-lang3', { version { strictly '[3,4]' } }
}
```
Just uncomment one of those lines to see how the commons lang dependency is resolved in different versions. Including the `require` that doesn't just always require it seems but actively pushes a new version, same for the `strictly`. This is on gradle 6.7

**Comment by jjohannes** [comment]
@sacchettom Are you sure you are seeing this:

> api "dependency", { version { strictly '[6,7]' } } -> gets the latest 6.+ version from the repository

I can not reproduce this. If I do for example:

```
dependencies {
    api("org.apache.commons:commons-lang3:3.2")
    api("org.apache.commons:commons-lang3") { version { strictly("[3,4]") } }
}
```

It will resolve to

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- org.apache.commons:commons-lang3:3.2
\--- org.apache.commons:commons-lang3:{strictly [3,4]} -> 3.2
```

The difference between `+` and range is working as expected.
- `+` means always select the lastest from the repository
- Range means select one in the range, if no version is required/preferred take the latest within the range. Higher required versions are allowed.
- A _strict_ range, is the same, just that it does not allow higher versions outside the range.

**Comment by sacchettom** [comment]
@jjohannes you're right, with that example of yours I don't see the issue. I see it with mine, where `commons-lang3` is a transitive:
```
dependencies {
  implementation group: 'org.apache.commons', name: 'commons-text', version: '1.7'
  implementation group: 'com.nimbusds', name: 'oauth2-oidc-sdk', version: '5.22.1'
  implementation group: 'org.apache.commons', name: 'commons-lang3', { version { strictly '[3,4]' } }
}
```
Which resolves the latest from the repositories rather than validating the transitive one:
```
> Task :dependencyInsight
org.apache.commons:commons-lang3:3.11 (by ancestor)
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]

org.apache.commons:commons-lang3:3.4 -> 3.11
\--- com.nimbusds:oauth2-oidc-sdk:5.22.1
     \--- runtimeClasspath

org.apache.commons:commons-lang3:3.9 -> 3.11
\--- org.apache.commons:commons-text:1.7
     \--- runtimeClasspath

org.apache.commons:commons-lang3:{strictly [3,4]} -> 3.11
\--- runtimeClasspath
```
Interestingly instead replacing `strictly` with `require` works following the rules you just gave above (I think you should probably add the `x.+` cases to the rich versions documentation page).
Note that I can replicate the above even if I transform the last dependency in a constraint, i.e. :
```
dependencies {
  implementation group: 'org.apache.commons', name: 'commons-text', version: '1.7'
  implementation group: 'com.nimbusds', name: 'oauth2-oidc-sdk', version: '5.22.1'
  constraints {
    implementation group: 'org.apache.commons', name: 'commons-lang3', { version { strictly '[3,4]' } }
  }
}
```
The selection reason contains the constraint but the result is the same, and again it behaves as with a `require '3.+'`:
```
org.apache.commons:commons-lang3:3.11
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]
   Selection reasons:
      - By ancestor
      - By constraint

org.apache.commons:commons-lang3:3.4 -> 3.11
\--- com.nimbusds:oauth2-oidc-sdk:5.22.1
     \--- runtimeClasspath

org.apache.commons:commons-lang3:3.9 -> 3.11
\--- org.apache.commons:commons-text:1.7
     \--- runtimeClasspath

org.apache.commons:commons-lang3:{strictly [3,4]} -> 3.11
\--- runtimeClasspath
```

**Comment by ljacomet** [comment]
This is working as expected _in the current implementation_.

A `strictly` means that the version information from deeper in the graph is ignored and only the `strictly` declaration matters. If your `strictly` is a range without a `prefer` it will then resolve to the highest version matching the range.

The example from Jendrik was putting a different version at the same level as the strictly, meaning it was accounted for.

One thing we have discussed doing was to improve range resolution for `strictly` by considering the overridden versions as `prefer` only. We never got to implement that feature though and we would need to assess the impact on existing projects that may rely on the current `strictly` behavior.

**Comment by sacchettom** [comment]
Thanks for the answer @ljacomet , this makes things clearer (but I strongly suggest you to add all of this information to the documentation, as well as extra examples, as currently it doesn't seem clear to me).
`prefer` doesn't accept ranges. My use case is for using the latest version of a dependency already in the dependency tree, but without allowing to update to a newer version.
At this point it seems clear enough for me that what I want is:
```
implementation group: 'org.apache.commons', name: 'commons-lang3', {
    version {
      require '[3,4]'
      reject '[4,'
    }
  }
```
