### ISSUE TITLE
DefaultFileHierarchySet can't handle Windows root directory correctly

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#11508]
### Context

The following test can't pass on windows:

```
    @Requires(TestPrecondition.WINDOWS)
    def "can handle windows system root"() {
        expect:
        def set = DefaultFileHierarchySet.of(Arrays.asList(new File("C:\\"), new File("D:\\")))
        set.contains(tmpDir.file("any"))
    } 
```

The special case (windows root directory `X:\`) is not properly handled [here](https://github.com/gradle/gradle/blob/92a3b8235d3ab604215324a5180f5ac6d1ae8a20/subprojects/base-services/src/main/java/org/gradle/internal/file/DefaultFileHierarchySet.java#L110).

**Comment by wolfs** [comment]
@blindpirate Yeah, I saw this when I created a similar thing for the virtual file system. This is how I solved it there: https://github.com/gradle/gradle/blob/7267c5f4a4a39bc2b1f4fd9a79c35d297d895683/subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/VfsRelativePath.java#L59-L66

**Comment by wolfs** [comment]
There also needs to be some fixing for determining the offset when the common prefix of the two things is empty:
https://github.com/gradle/gradle/blob/fd5a1df827c84ec8f0394aafe0eaa591a8c19d59/subprojects/base-services/src/main/java/org/gradle/internal/file/DefaultFileHierarchySet.java#L169-L172

I.e. the index for the next path is then not `1` but `0`.

**Comment by blindpirate** [comment]
> the index for the next path is then not 1 but 0.

Oh yeah, that's why I still got failures after my attempt to fix this morning...
