### ISSUE TITLE
Give user information about increasing inotify watch count when needed

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11504]
When watching for changes on Linux, the default limit of inotify handles is 8192. This runs out pretty quickly for medium sized projects. For example, running `:snapshots:integTest` on `gradle/gradle` wants to register 10K+ watches.

It is typically okay to increase this number substantially, though it requires superuser privileges. IntelliJ for example recommends 512K watchers. Some more info on memory consumption etc: https://unix.stackexchange.com/a/13757

If we hit the limit, and thus can't watch the file system, we should warn the user at the end of the build, pointing them to some resource describing how they could bump the watch count.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
The error number returned from `inotify_add_watch` is ENOSPC (28) when the user runs out of inotify watches:
```
       ENOSPC The user limit on the total number of inotify watches was
              reached or the kernel failed to allocate a needed resource.
```

**Comment by wolfs** [comment]
These are the messages IDEA uses: https://github.com/JetBrains/intellij-community/blob/0e4772fc8c2e70019209d9bfb41fac6de131cf14/native/fsNotifier/linux/main.c

Note that there is the [inotify instance limit](https://confluence.jetbrains.com/display/IDEADEV/Inotify+Instances+Limit) and the [inotify watches limit](https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit) which may need to be increased.

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/13573
