### ISSUE TITLE
Support OSX KeyChain as Truststore

### ISSUE THREAD

**Issue by noetro** [gradle/gradle#11516]
As per the contributing guide I am opening an issue for discussion before starting any work.

Oracle ships with a provider for a _java.security.Keystore_ that uses the macOS KeyChain.

https://docs.oracle.com/en/java/javase/13/security/oracle-providers.html#GUID-3185649A-C316-45F2-A70E-2B3FF6BDC34F

Gradle does not currently support this, even if you initialise the JVM with:

-Djavax.net.ssl.trustStoreType=KeychainStore

Ideally we would like this support as we have certificates provisioned onto developer machines and our Nexus artifact server is configured with the same certificate.  Without this support Gradle will not pull dependencies from our artifact server.

The problematic code appears to be here; it seems like the code is missing a case for this trust store type.

https://github.com/gradle/gradle/blob/master/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/DefaultSslContextFactory.java

I'm happy to contribute the fix if this is the right place.

### Expected Behavior

We can configure -Djavax.net.ssl.trustStoreType=KeychainStore in our gradle.properties and gradle will correctly initialise with the macOS KeyChain as the trust store.

### Current Behavior

It appears that Gradle expects any trustStoreType other than "none" to be file based and tries to initialise with files.  Even when passing the trust store type correctly the certificates are not loaded from the macOS KeyChain and downloading dependencies fails with a SSL trust exception.

### Context

We are trying to get gradle to pull dependencies with trusted certificates that are in the macOS KeyChain.

Our workarounds are to also provision file based trust stores onto developer machines.  Which, is feasible but this seems like a small fix that we could contribute back the project.

The following is a simple scratch main method that demonstrates how the a trust store should be initialised with this provider - note the two null arguments to the load method.

```
public static void main(String[] args) {
    try {
      KeyStore ks = KeyStore.getInstance("KeychainStore");
      ks.load(null, null);

      Enumeration<String> en = ks.aliases();
      while (en.hasMoreElements()) {
        String aliasKey = en.nextElement();
        X509Certificate c = (X509Certificate) ks.getCertificate(aliasKey);
        System.out.println("alias: " + aliasKey);
        System.out.println("cert:" + c.getSubjectX500Principal().toString());
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }
  }
```

This seems to be a very similar type of issue to this:

https://github.com/gradle/gradle/issues/6584

**Comment by knolleCC** [comment]
FYI: as posted in #6584 you can work around this by using a dummy file (must exist) as "trustStore" e.g.:

    systemProp.javax.net.ssl.trustStore=C:/some/existing/file.txt
    systemProp.javax.net.ssl.trustStoreType=YOUR-TYPE-HERE

**Comment by MatthiasRobbers** [comment]
The workaround is still needed... I recommend using `/dev/null` as some existing file as it is present on any Mac:

```
systemProp.javax.net.ssl.trustStore=/dev/null
systemProp.javax.net.ssl.trustStoreType=KeychainStore
```

**Comment by EarthCitizen** [comment]
This is a MAJOR, MAJOR problem for anyone working behind a corporate proxy that modifies the certs.

**Comment by marazmarci** [comment]
> The workaround is still needed... I recommend using `/dev/null` as some existing file as it is present on any Mac:
> 
> ```
> systemProp.javax.net.ssl.trustStore=/dev/null
> systemProp.javax.net.ssl.trustStoreType=KeychainStore
> ```

This workaround is not working for me. I tried with Gradle `7.2` and `7.5.1`

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue was fixed in 
* #25106

Note that due to [this bug in JDK](https://bugs.openjdk.org/browse/JDK-8303465) fixed in JDK 21 you may experience issues with Apple <-> Java integration because only the user domain is considered. But Gradle behavior should not differ from the code snippet provided in the Context section.
