### ISSUE TITLE
Misleading deprecation warning for compileOnly configuration

### ISSUE THREAD

**Issue by stovocor** [gradle/gradle#11512]
After upgrading to Gradle 6.0.1, we receive this deprecation warning:

```
The compileOnly configuration has been deprecated for resolution.
This will fail with an error in Gradle 7.0. Please resolve the
compileClasspath configuration instead.
```

The message could be interpreted that `compileClasspath` is a drop-in replacement for `compileOnly`, but the resolved artifacts for both configurations differ.

### Expected Behavior
In the warning message a replacement should be mentioned that can be actually used instead of `compileOnly`.

### Current Behavior
The warning message mentions a replacement that can not be used in some cases.

### Context
We are trying to collect all dependencies required at runtime like this:
```
def libs = configurations.runtimeClasspath.resolvedConfiguration.resolvedArtifacts
        .findAll { !configurations.providedRuntime.resolvedConfiguration.resolvedArtifacts.contains(it) }
        .findAll { !configurations.compileOnly.resolvedConfiguration.resolvedArtifacts.contains(it) }
        .collect { artifact -> artifact.moduleVersion.id }
```

### Steps to Reproduce 
Try to access `configurations.compileOnly` in the `build.gradle`.

### Your Environment
Gradle 6.0.1

**Comment by melix** [comment]
The message says exactly what it should say: you shouldn't try to resolve `compileOnly` because it's a bucket of dependencies. `compileClasspath` is what should be resolved. If you try to resolve `compileOnly`, like in your code sample, you get wrong results.

**Comment by ljacomet** [comment]
Have a look at the way configurations are wired together in the java plugins: https://docs.gradle.org/6.0.1/userguide/java_library_plugin.html#sec:java_library_configurations_graph

`compileOnly` should not be resolved indeed. In the variant aware dependency management world, it does not carry attributes, and so its resolution detail might be off compared to the resolution of `compileClasspath` which includes the `compileOnly` dependency.

Your logic for determining the runtime dependencies seems flawed in substracting what is in `compileOnly`. While unlikely, there could be a valid reason for a dependency to appear in your transitive runtime graph, while your project believes it needs it only for compilation.

**Comment by stovocor** [comment]
> The message says exactly what it should say: you shouldn't try to resolve compileOnly because it's a bucket of dependencies.

Well, the message may be interpreted as: "You are using the old way, please use this instead from now on." In my opinion, this may be misleading, because the results differ.

**Comment by ljacomet** [comment]
Thanks for your feedback.
How would you improve the message to make it clear that declaring dependencies in `compileOnly` is ok and remains supported but it is accessing resolution results (thus triggering resolution) that is deprecated and to be removed?

**Comment by stovocor** [comment]
> Your logic for determining the runtime dependencies seems flawed in substracting what is in compileOnly. While unlikely, there could be a valid reason for a dependency to appear in your transitive runtime graph, while your project believes it needs it only for compilation.

Thanks for the hint. What I am trying to accomplish is to filter out `servlet-api` which is part of the `runtime` configuration. But using `compileOnly` may be not the right way because I do not need it at compile time at all.

**Comment by stovocor** [comment]
> How would you improve the message to make it clear that declaring dependencies in compileOnly is ok and remains supported but it is accessing resolution results (thus triggering resolution) that is deprecated and to be removed?

Hm, just remove the "Please resolve the compileClasspath configuration instead." part?

**Comment by melix** [comment]
I don't think it would be a good idea. In fact, if we just said "don't try to resolve `compileOnly`" you would probably have complained that there's no alternative.

Here, we're saying what is the _right_ alternative: `compileClasspath` contains the resolved dependencies. It's a bit harsh to say "you were doing it wrong", though :)

**Comment by stovocor** [comment]
> I don't think it would be a good idea. In fact, if we just said "don't try to resolve `compileOnly`" you would probably have complained that there's no alternative.

It is scary that you know me that well after only a couple of hours. :)

Okay, perhaps the warning is okay as it is and we made the situation better by explaining it here as a kind of external documentation.

**Comment by ljacomet** [comment]
Maybe that's the trick: add a reference to the documentation inside that error message and make sure there is a detailed explanation in the documentation.
