### ISSUE TITLE
Different classpath order through Gradle TAPI and Scripting API

### ISSUE THREAD

**Issue by NataliaUkhorskaya** [gradle/gradle#11529]
Classpath for build.gradle.kts is requested through `KotlinBuildScriptModelBuilder.kotlinBuildScriptModelFor` (when Kotlin Plugin requests dependencies for one script in Intellij) and  through `KotlinDslScriptsModelBuilder.buildFor` (when the hole project is imported in Intellij).

In the second method there is an optimization in `dehydrateScriptModels` that may not save the original order.

### Expected Behavior
The classpath order should be the same for both cases

### Current Behavior
The classpath order may be changed, especially with multi-modules projects

related issue in Kotlin Project https://youtrack.jetbrains.com/issue/KT-34626

**Comment by eskatos** [comment]
Right, the dehydratation should only consider common prefixes, not all common elements. I'll work on a fix.

**Comment by eskatos** [comment]
Fixed in #11543, will ship with Gradle 6.1, closing
