### ISSUE TITLE
Adoption of Gradle Module Metadata in open source libraries

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#11528]
With [Gradle 6.0 and the automatic publishing of Gradle Module Metadata](https://blog.gradle.org/avoiding-dependency-hell-gradle-6), a number of open source libraries could benefit from the features supported by that metadata format.

Help library authors and the community in general by suggesting libraries that could benefit from features like [alignment](https://blog.gradle.org/alignment-with-gradle-module-metadata), capabilities and more.

Please add comments indicating which library either offers Gradle Module Metadata or could benefit from it, with a link to an issue requesting the support.

This issue description will also be edited to list frameworks and libraries publishing Gradle Module Metadata.

**Comment by vlsi** [comment]
It would be nice to hear the way to control and **test** metadata.

I've a case when Gradle tries to use the metadata for the module that is not published to Nexus.

"library": https://github.com/apache/jmeter

The build is using [java-platform](https://github.com/apache/jmeter/blob/d3d7fdd91679406dfbadceaf0afaa8e95106e7cc/src/bom/build.gradle.kts) to consolidate "dependency constraints" in a single place, then individual projects use the [platform dependency](https://github.com/apache/jmeter/blob/d3d7fdd91679406dfbadceaf0afaa8e95106e7cc/src/jorphan/build.gradle.kts#L20).

So far so good (it allows to declare versions in a single place, the versions can be adjusted via the command line, and it does not suffer from `buildSrc`-change-recompile-all-modules issue).

The generated poms use `resolved` versions, so they do not really refer to `bom` (and it is even an [unsupported case](https://github.com/gradle/gradle/issues/9866) ).
That is why `bom` is not yet published to Nexus.

However, if I publish metadata for other modules (e.g. for `:src:jorphan` which uses `platform(project(":bom"))`), then the published metadata for `:src:jorphan` would include `:src:bom` reference. Apparently that metadata reference is invalid (as `:bom` is never published), so any attempt to use the published `jorphan` project with Gradle would fail as Gradle.

That is basically the case I disable metadata publication for now :-/

Is it something you want to hear here?

**Comment by jjohannes** [comment]
Hi @vlsi. Thanks for the feedback. We would love to see **jmeter** publish Gradle Module Metadata soon. If I understand your comment and the discussion on #9866 correctly, you are publishing resolved versions to properly support Maven consumers, which can not "automatically" import the BOM. Which is a common use case.
There is #10861 for adding a feature that removes the platform dependencies from publication (which we plan to address soon). However, I was wondering if you would consider publishing the BOM/platform, even if it is a "duplication" of versions. If you publish the dependency to the platform it can be advantageous (for Gradle 6 users) because you always will have all constraints in the graph, also for the dependencies one of your modules does not have. This can help to _better_ align versions in case of conflicts if your library is combined with others. See also our recent blog post about the topic: https://blog.gradle.org/alignment-with-gradle-module-metadata

**Comment by vlsi** [comment]
@jjohannes , BOM generation for JMeter is blocked by https://github.com/gradle/gradle/issues/11299 which has PR https://github.com/gradle/gradle/pull/11317 which has zero comments from Gradle team :'(

**Comment by jjohannes** [comment]
Sorry @vlsi. I didn't catch that this is blocking your directly. The issue is on our list of upcoming work (a lot of things are going on right now). Thank you very much for the PR. We forgot to comment but it is on our radar. I'll see that we address it very soon.

**Comment by jjohannes** [comment]
### Junit 5

JUnit 5 is publish GMM starting with `5.6.0-M1`  🎉 
 https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.6.0-M1/

**Comment by jjohannes** [comment]
### Guava

There is a PR at Guava for publishing GMM: https://github.com/google/guava/pull/3683

This is an interesting case as it covers multiple use cases (see https://github.com/google/guava/pull/3683 for details):

- Multiple variants for different JDK versions
- Compile-only API dependencies to avoid annotation processor libraries on runtime classpath
- Use capabilities to detect conflicting implementations (e.g. `com.google.guava:guava`  vs. `com.google.guava:listenablefuture`)
- Publish _Gradle Module Metadata_ with Maven

**Comment by jjohannes** [comment]
### Android & AndroidX Libraries

[AndroidX](https://developer.android.com/jetpack/androidx) will publish GMM soon.

Publishing with Gradle 6+ and AGP (Android Gradle Plugin) 3.6.0 / 4.0.0 (beta/alpha available now) supports publishing of GMM by default. That allows for advanced use cases when publishing Android libraries. For Android libraries, you now have now a _component_ available for each buildType/flavor combination (e.g. `debug` and `release` by default). But there is also a `all` component you can use to publish everything and then let Gradle select which variant to use at consumption times (as if the library where a local project).

```
afterEvaluate {
    publishing {
        publications {
            aar(MavenPublication) {
                from components.all
            }
        }
    }
}
```

**Comment by jjohannes** [comment]
### Other widely used Libraries

For inspiration, here are some more sample of how GMM could look for some well-known libraries (Guice, FLF4J, Hibernate, ...)
https://github.com/jjohannes/what-if-gradle-metadata/tree/master/usecases

**Comment by jjohannes** [comment]
### Log4J

There is a discussion on the mailing list about adopting GMM: http://mail-archives.apache.org/mod_mbox/logging-log4j-user/202001.mbox/%3C9290FD78-1641-417B-A4F1-4EB952242F9D%40dslextreme.com%3E

**Comment by jjohannes** [comment]
### SLF4J

Discussion about the [dev.jacomet.logging-capabilities](https://plugins.gradle.org/plugin/dev.jacomet.logging-capabilities) plugin and GMM on the SLF4J user mailing list: http://mailman.qos.ch/pipermail/slf4j-user/2020-January/001736.html

**Comment by jjohannes** [comment]
### Jackson

Related blog post: https://blog.gradle.org/alignment-with-gradle-module-metadata

Discussion on the Jackson user mailing list: https://groups.google.com/forum/#!topic/jackson-user/OTwpIl6chUY

**Comment by jjohannes** [comment]
### Okio

JVM, Android and Kotlin multiplatform I/O library 

https://square.github.io/okio
https://github.com/square/okio

**Comment by jjohannes** [comment]
=== OkHttp

HTTP client for Java and Kotlin

https://square.github.io/okhttp/
https://github.com/square/okhttp
https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/4.4.0/

**Comment by britter** [comment]
### Bean Validators

Additional validator implementations for javax.validation

[britter.github.io/bean-validators](https://britter.github.io/bean-validators)
[britter/bean-validators](https://github.com/britter/bean-validators)
[repo1.maven.org/maven2/com/github/britter/bean-validators/0.7.0](https://repo1.maven.org/maven2/com/github/britter/bean-validators/0.7.0/)

**Comment by jjohannes** [comment]
We will close this as an issue as there are no more planned actions on this right now.

Thanks everyone who reported on the adoption of GMM here.
