### ISSUE TITLE
Feature request: move to Graal Native for Gradle execution as replacement for Gradle Deamon

### ISSUE THREAD

**Issue by remmeier** [gradle/gradle#11525]
# Expected Behavior

Fast and reliable startup and execution are essential for every developer-related tooling. The JVM historically performs rather poorly in that regard. Gradle works around this issue by having the Gradle deamon to keep the JVM warmed-up. Still this open up other issues like dangling states, memory leaks and heavy resource usage while not being used.

There has been a lot of progress on AoT in recent times. Most notable, Graal Native sees increased adoption. Thereby frameworks see performance improvements of a factor 10x in startup time (e.g. https://technology.amis.nl/2019/09/03/microservice-framework-startup-time-on-different-jvms-aot-and-jit/). Gradle puts more focus on Kotlin tehse days, gaining type-safety at sompile time. This in turn could make Graal Native or related tooling a next step to improve performance while eliminating the footprint of the gradle deamon.

### Current Behavior

Gradle deamon as resource intensive and slightly error-prone workaround.

**Comment by mkotsbak** [comment]
Still reproducable. Probably duplicate of #7690.
