### ISSUE TITLE
Java/JUnit: includeCategories does not include Parameterized Tests

### ISSUE THREAD

**Issue by fibsifan** [gradle/gradle#1153]
EDIT: Fill out Issue Template.

When running Tests from a certain Category by using includeCategories in build.gradle, parameterized tests (see [JUnit Wiki](https://github.com/junit-team/junit4/wiki/Parameterized-tests)) are not run without any error message. I'd expect the tests to run, just like any other test or tests, that are run when using excludeCategories instead. Include would definitely preferred, because otherwise every test, where someone forgot to put a category would be run in the testsuite.

In [this post](https://discuss.gradle.org/t/junit-categories-includecategories-filter-not-working-for-parameterized-tests/20902), Marcus Bento has kindly provided a not working example.

### Expected Behavior
All Tests annotated with the given @Category (ies) run.

### Current Behavior
Only non-parameterized Tests with the given @Categories (y) run.

### Context
Our tests are categorized by various criteria (tests for not yet implemented features, tests for administrator functionality, tests for end user functionality). Tests which are itself in development are not Categorized.
When adding new tests it is important, that they don't pollute Categorized test suites. When adding new Categories, it would be nice if the deveolper/tester just had to write his own gradle task and not going through all other test tasks and exclude his new category.

### Steps to Reproduce (for bugs)
See [this forum post](https://discuss.gradle.org/t/junit-categories-includecategories-filter-not-working-for-parameterized-tests/20902).

### Your Environment
See [same post](https://discuss.gradle.org/t/junit-categories-includecategories-filter-not-working-for-parameterized-tests/20902).

**Comment by fibsifan** [comment]
I just realized that JUnit is unable to run parameterized tests which are categorized *per method*. However gradle still does not find parameterized tests that are categorized *per class*. However, when using `excludeCategories`, gradle is able to run categoriezed *methods* that are in parameterized classes.

**Comment by oehme** [comment]
@marcphilipp Do you know when JUnit 4.13 with the [fix](https://github.com/junit-team/junit4/issues/751) for this will come out?

**Comment by marcphilipp** [comment]
@oehme Soon™ – I hope within the next few weeks. There are only two issues left to be sorted out. Feel free to track https://github.com/junit-team/junit4/issues/1496 for details.

**Comment by oehme** [comment]
Thanks! I think we can close this issue then and ask users to upgrade to 4.13 as soon as possible.
