### ISSUE TITLE
Does gradle's internal maven repo support mirror?

### ISSUE THREAD

**Issue by pan3793** [gradle/gradle#11535]
You know, we can config `~/.m2/settings.xml` to set a global mirror of all repo which id is `central` in maven.
```
<settings>
  <mirrors>
    <mirror>
      <id>aliyun-maven-central</id>
      <mirrorOf>central</mirrorOf>
      <name>aliyun-maven-central</name>
      <url>https://maven.aliyun.com/repository/central/</url>
    </mirror>
  </mirrors>
</settings>
```
Does gradle has this feature? I mean just set a value in `ENV` or `gradle.properties` to overwrite url of `mavenCentral()`, `jcenter()`, etc.

**Comment by pan3793** [comment]
@blindpirate Would you please have a look on this issue?

**Comment by blindpirate** [comment]
You can configure it by global init script, i.e. `~/.gradle/init.gradle`:

https://stackoverflow.com/questions/25997745/what-is-the-gradle-equivalent-of-maven-repository-mirrors/45409118

**Comment by pan3793** [comment]
> You can configure it by global init script, i.e. `~/.gradle/init.gradle`:
> 
> https://stackoverflow.com/questions/25997745/what-is-the-gradle-equivalent-of-maven-repository-mirrors/45409118

Thanks for your quickly reply, already found this solution, but it looks not elegant as `gradle` style. 
Any possible to config it in `Environment Variable` or `gradle.properties` ? 
If not, can you take this issue as a feature request?

**Comment by blindpirate** [comment]
```
repositories {
    maven {
      url(project.findProperty("mavenCentralUrl") ?: 'https://maven.aliyun.com/repository/public/')
    }
}
```

Then put `mavenCentralUrl` property to either project-level or global `gradle.properties`.

**Comment by pan3793** [comment]
This should works for my own project, what about other ones own? If they config it in `build.gradle`, how can I overwrite it via properties? I think a native support like maven mirror would be a more generic solution.
```
repositories {
  mavenCentral()
}
```
