### ISSUE TITLE
Copy the jacoco exec file from external directory to $buildDir/jacoco before jacoco report produced

### ISSUE THREAD

**Issue by Asisranjan** [gradle/gradle#11545]
As part of gradle integrationTest task i am launching application in docker container and running junit test cases. While launching container i am also attached jacoco agent. the report (exec file) is saved to /tmp directory in host machine.

I am trying to copy exec file from /tmp to $buildDir/jacoco. this is my build.gradle  file

task integrationTest(type: Test) {
    useJUnit {
        includeCategories 'com.myorg.itest.core.category.Integration'
        excludeCategories 'com.myorg.itest.core.category.Functional'
    }
}

task copyExtJacocoExec {
    copy {
        from "/tmp"
        into "$buildDir/jacoco"
        include "*.exec"
    }
}

copyExtJacocoExec.dependsOn integrationTest
integrationTest.finalizedBy copyExtJacocoExec

### Expected Behavior

I am expecting the exec file to be copied to $buildDir/jacoco

### Current Behavior

It is not copying.

### Context

If i am able to copy exec file, it will be easy for me to merge all the report generated during unit test case in the subprojects and publish one report after merging.

I am doing above by having another two task such as jacocoMerge which merge all jacoco report from subprojects and codeCoverageReport which produces html report.

### Your Environment

Build scan URL:

**Comment by bmuskalla** [comment]
@Asisranjan can you ensure that the `.exec` file are actually generated in `/tmp`? How is your merge/report task setup? It could be that you need to ensure they're run *after* the copy task. A small reproducible example would really help to track this down.
