### ISSUE TITLE
Global pluginManagement for repositories with auth doesn't work for Gradle 5.6.2+

### ISSUE THREAD

**Issue by foghcz** [gradle/gradle#11578]
After the new security fixes provided in Gradle 5.6.2 we're not able to use the global pluginManagement configuration (init.gradle script) described in:
https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management
Gradle doesn't provide the credentials defined in allprojects -> repositories section of the init.gradle file. The block beginning "settingsEvaluated { settings -> settings.pluginManagement.repositories" doesn't know the global properties set in gradle.properties. To make this work, we had to hardcode the credentials inside of the init.gradle script, having them on two places.
If there's another way to avoid having credentials inside of init.gradle script, I'd appreciate if the documentation was updated:
https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management
Thank you.

### Expected Behavior
Expected is either:
1) a way to provide variable set in gradle.properties
settingsEvaluated { settings ->
    settings.pluginManagement.repositories {
		maven {
			url "https://repo.url"
			credentials {
				username nexusUsername //properties from gradle.properties
				password nexusPassword
			}
		}
2) Gradle would reuse the credentials already set in allprojects/repositories section. However sometimes the plugin repositories may be different.

### Current Behavior
Build fails, due to unauthorized HTTP code:
Could not HEAD 'https://nexus-repo/...'. Received status code 401 from server: Unauthorized

### Context
Due to having multiple projects, we try to avoid having nexus configuration spread accross all the build files for each project. We'd like to have it centralized the same maven has it. The nexus URL has already changed in the past.
The Jenkins build machines don't have any internet access due to security reasons, they have to get all the libraries/plugins from the corporate Nexus server.

### Steps to Reproduce 
Gradle configuration:
[gradle-bug-report.zip](https://github.com/gradle/gradle/files/3922951/gradle-bug-report.zip)
1) Have a machine without internet connection
2) Run a build requiring some non-standard plugin, e.g. 
plugins {
    id "org.jetbrains.kotlin.jvm" version 1.3.50
}

### Your Environment
N/A

**Comment by p3k** [comment]
I think I have the same issue:

**gradle.properties**

```properties
foo = foo
bar = bar
```

**settings.gradle**

```groovy
pluginManagement {
	repositories {
		maven {
			url 'http://localhost:2015/'

			credentials {
 				username properties.foo
 				password properties.bar
			}
		}
	}
}

// Correctly prints "foo" and "bar"
println properties.foo
println properties.bar
```

**HTTP test server output**
```plain
# Browser request using foo/bar as credentials
::1 -  [10/Aug/2020:13:37:22 +0200] "GET / HTTP/1.1" 401 17
::1 - foo [10/Aug/2020:13:37:25 +0200] "GET / HTTP/1.1" 404 14 # File not found is OK (test server)

# Running Gradle task using config above
127.0.0.1 -  [10/Aug/2020:13:37:33 +0200] "GET /com/github/node-gradle/node/com.github.node-gradle.node.gradle.plugin/2.2.4/com.github.node-gradle.node.gradle.plugin-2.2.4.pom HTTP/1.1" 401 17
127.0.0.1 - null [10/Aug/2020:13:37:33 +0200] "GET /com/github/node-gradle/node/com.github.node-gradle.node.gradle.plugin/2.2.4/com.github.node-gradle.node.gradle.plugin-2.2.4.pom HTTP/1.1" 401 17 # Still 401 means authentication failed (see null at 3rd position of log line)
```

**Comment by mlopatkin** [comment]
One workaround for this issue is to supply [credentials without explicit configuration](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials) in the `gradle.properties` file. It requires at least gradle 6.6 though.

**Comment by ljacomet** [comment]
This issue will be closed
* See [documentation](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) which has `Example 5` showing the proper way to access Gradle properties in init scripts
* Recent Gradle versions have additional repository authentication support that support this scenario as commented above.

**Comment by p3k** [comment]
In case someone is still looking for a solution – especially, because the last comment refers to a non-existing `Example 5` – here is what works for me:

> [!note]
> I am using Gradle version 7.6.4 in the meantime.

## 1. `getProperty()` method

```properties
# gradle.properties
my.credentials.username = foo
my.credentials.password = bar
```

```groovy
// settings.gradle
pluginManagement {
  repositories {
    maven {
      url 'http://localhost:2015/'
      credentials {
        username getProperty('my.credentials.username')
        password getProperty('my.credentials.password')
      }
    }
  }
}
```

## 2. `settings.ext.get()` method

```properties
# gradle.properties
my.credentials.username = foo
my.credentials.password = bar
```

```groovy
// settings.gradle
pluginManagement {
  repositories {
    maven {
      url 'http://localhost:2015/'
      credentials {
        username settings.ext.get('my.credentials.username')
        password settings.ext.get('my.credentials.password')
      }
    }
  }
}
```

## 3. Convention as described in the [official documentation](https://docs.gradle.org/8.5/userguide/declaring_repositories.html#sec:handling_credentials)

> [!note]
> This is [not documented in version 9.5.0](https://docs.gradle.org/9.5.0/userguide/declaring_repositories.html#sec:handling_credentials), anymore – maybe the content was moved or the feature removed. 

```properties
# gradle.properties
myCredentialsUsername = foo
myCredentialsPassword = bar
```

```groovy
// settings.gradle
pluginManagement {
  repositories {
    maven {
      // Using dots is not supported here!
      // (Identity may contain only letters and digits)
      name 'myCredentials'
      url 'http://localhost:2015/'
      credentials(PasswordCredentials)
    }
  }
}
```
