### ISSUE TITLE
Streamline Maven Migration

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1158]
Users planning to migrate from Maven to Gradle need to be equipped with capable tools that provide a smooth transition. Well known concepts in the Maven world need to translate to Gradle to ensure compatibility with existing Maven infrastructure. Appropriate user guides and samples need to be established to educate users about migration strategies.

### Expected Behavior

Maven projects can be easily translated to Gradle projects without a lot of manual intervention. Users are guided through the transition by appropriate documentation. Existing shortcomings of Gradle's interoperability with Maven infrastructure is minimized.

### Current Behavior

The Gradle `init` task can help to get started with Maven migration but lacks in features. Manual intervention is necessary. There's little information about how Maven concepts translate to Gradle. Migration of large Maven projects to Gradle is not trivial and requires intricate knowledge about both ecosystems. Specific Maven features are simply not supported by Gradle.

### Context

Over time Maven users will have a look at the Gradle ecosystem to see if there are better solutions to the problems they are facing. The easier the tooling and documentation for a migration, the more likely it is for users to start a prototype.

[Possibly interesting words from Eric](https://docs.google.com/document/d/1Jw18NzT2rOlH7CxWfD_qQv_TXH0TEaEqb3ScQhaCwyU)

**Comment by bmuschko** [comment]
I see some quick wins here:

- Improving the `init` task to make it even easier for people to migrate without manual intervention.
- Heavily promote the Maven migration guide to the community and harvesting feedback. I can't even find the guide when googling for it.

Personally, I'd like to see the BOM support in Gradle though that's a personal opinion and requires some deep thinking.

**Comment by jjohannes** [comment]
Some things mentioned here have been done (BOM/platform support, improvements to gradle init, updates to the migration guide). Since this issue is no longer tracking any current or planned work, I am closing it.
