### ISSUE TITLE
Update code quality plugin versions

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#11581]
We supply a default version for PMD, CodeNarc, and Checkstyle.  We should keep this close to the latest release unless we're limited by our minimum version guarantees. e.g., if the latest version of PMD required Java 13+, we cannot upgrade the default version used until Gradle requires Java 13+ (Gradle needs to work with Java 8+ out of the box).

To update these versions, we need to do a few things:
- In each of the plugin classes (PmdPlugin, CodeNarcPlugin, CheckstylePlugin), update the default version to the latest appropriate version.
- Check the documentation for the plugin (the user manual .adoc file for the plugin, the extension class and the task) for any links that are broken or version specific.  If there's a reliable version agnostic link we can use, we can switch to that.  
- Update Gradle's 6.x upgrade guide (`upgrading_version_6.adoc`) to mention the default version change.  The upgrade notes just need to include the version we upgraded from and to with a link to any release notes, if they're available.  [Here's an example](https://docs.gradle.org/5.6/userguide/upgrading_version_5.html#default_pmd_version_upgraded_to_6_15_0)
- Check the code coverage is adequate for the plugin (see CheckstyleCoverage, CodeNarcCoverage and AbstractPmdPluginVersionIntegrationTest). We always test the default version, so it's a judgment call if another version needs to be added to list. e.g., if we're testing 1.1 and 1.2 and the upgrade is 1.3 to 1.3.1, we don't need to test 1.3 and 1.3.1.  But if we're testing 1.0 and 1.5 and the upgrade is 1.9 to 2.0, we should add 1.9 to the list. 

If none of the plugins have any upgrades available, we can close this issue.

**Comment by rieske** [comment]
CodeNarc latest is 1.4 and we are on 1.4.

**Comment by big-guy** [comment]
I merged the other two PRs, thanks!
