### ISSUE TITLE
Ignore space behind a version if defined in gradle.properties

### ISSUE THREAD

**Issue by ehmkah** [gradle/gradle#11603]
### Expected Behavior

Gradle should remove spaces in versions for dependencies if they are the last character. E.g.
givenVersion  | expectedVersion
"1.2.0"           | "1.2.0"
"1.2.0 "          | "1.2.0"
"1.2.0<TAB>" | "1.2.0"

I have no opinion how to handle other whitespace characters 

### Current Behavior
If I  configure the version of our dependencies in gradle.properties. For example:

"batikVersion                      = 1.8"

and use this defined version in build.gradle the following way: 

"compile group: "org.apache.xmlgraphics", name: "batik-transcoder", version: "${batikVersion}""

Everything works fine until the moment I insert a space as the last character for batikVersion. So it becomes: 

"batikVersion = 1.8 "

Now gradle says it can't find the dependency because there ist no "1.8 ". 

### Context
- Sometimes I add a space accidentaly and it becomes difficult to spot the additional space because its difficult to see that dependency has a space in it. 

- alternatives:
-- remove space manually in build.gradle (should work always)
-- validate gradle.properties 
-- make it more obvoius that the last caharcter is a Space

**Comment by ljacomet** [comment]
I am not sure about doing the trimming in Gradle itself. This feels like hiding errors in a way.
However, the point about making it more obvious in the error message is a good one.

Could you share the exact error message you are getting?

**Comment by ehmkah** [comment]
Thank you for your fast answer. Error message looks like:
```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.apache.commons:commons-lang3:3.4 .
```
So it might help to write something like `its not  allowed to have a space as last character"
