### ISSUE TITLE
`--info` should display why a lifecycle task is not `UP-TO-DATE`

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#11601]
Lifecycle tasks (created with just `tasks.register("name")`) have no action, and yet they can be `UP-TO-DATE` or not, depending on the `UP-TO-DATE` state of their direct task dependencies.

Gradle's output with `--info` shows why regular tasks are up to date or not (e.g. showing which input changed), but for lifecycle tasks there's no info why a task would not be `UP-TO-DATE`. This makes it harder to debug tests that validates task states for a given scenario.

Therefore, It would be useful to display which direct dependency task triggered the not up-to-date state.

**Comment by wolfs** [comment]
Let's do this as part of introducing a specific lifecycle task.

cc @gradle/build-cache

**Comment by lptr** [comment]
See #11839 for first-class support for lifecycle tasks.
