### ISSUE TITLE
Module metadata parser fails for capability requests without version

### ISSUE THREAD

**Issue by bdeneuter** [gradle/gradle#11616]
We publish libraries in a company wide BOM file that is being used by our applications. With Gradle 6 we moved to Gradle variants for publishing testBuilders for our libraries. Some of our applications publish also an SDK and we found out that when using capabilities from the BOM, the version is NULL in the metadata that is being published to the Maven repository. So it seems that for a requireCapability the version is not correctly resolved. As it is a feature from a library published in a BOM file, we don't know the exact version number. When using the SDK we receive an error as the published metadata module is not correct. 

### Expected Behavior

When publishing a metadata module to Maven central, a valid module is being published whit the correct version resolved

### Current Behavior

The version is NULL and when trying to use the library, Gradle throws an exception

The version is not resolved correctly in the metadata file:
`        {
          "group": "com.test",
          "module": "my-library",
          "requestedCapabilities": [
            {
              "group": "com.test",
              "name": "my-library-my-feature",
              "version": null
            }
          ]
        }`

### Context

We are trying to publish common code in reusable libraries and the versions managed in a BOM file

### Steps to Reproduce 

I have created a sample with 2 projects. Project 0_project will create a BOM and a library. This can be published to Maven local. The second project uses the BOM and add a dependency on the feature. 

[gradle-bug.zip](https://github.com/gradle/gradle/files/3936216/gradle-bug.zip)

Steps:

- cd 0_project
- ./gradlew publishToMavenLocal
- cd ../1_project
- ./gradlew generateMetadataFileForMavenJavaPublication

`{
  "formatVersion": "1.1",
  "component": {
    "group": "com.test2",
    "module": "1_project",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "x5dauafhrvayxbxkprk4p56yie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.test",
          "module": "my-bom",
          "version": {
            "requires": "1.1.1"
          },
          "attributes": {
            "org.gradle.category": "enforced-platform"
          }
        },
        {
          "group": "com.test",
          "module": "my-library",
          "requestedCapabilities": [
            {
              "group": "com.test",
              "name": "my-library-my-feature",
              "version": null
            }
          ]
        }
      ],
      "files": [
        {
          "name": "1_project-1.1.1.jar",
          "url": "1_project-1.1.1.jar",
          "size": 861,
          "sha512": "7bbbd57be798cc045ae8389b820e1d1d8fc1948b8fbdaf0fa760a465ebf54812ff319a59c4e4fa24bb401ce073e0e16701f2b412ca6b4ce8f7b6675d01949d4f",
          "sha256": "8a75c1d84fb3492591034334e6730deaf95cbca8dbcb781d8212ddd54044bab1",
          "sha1": "39f46a2865bbf2bc20bb579a037b365954ac0bba",
          "md5": "f1aacaff02ad6f0b13875b46198348cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.test",
          "module": "my-bom",
          "version": {
            "requires": "1.1.1"
          },
          "attributes": {
            "org.gradle.category": "enforced-platform"
          }
        },
        {
          "group": "com.test",
          "module": "my-library",
          "requestedCapabilities": [
            {
              "group": "com.test",
              "name": "my-library-my-feature",
              "version": null
            }
          ]
        }
      ],
      "files": [
        {
          "name": "1_project-1.1.1.jar",
          "url": "1_project-1.1.1.jar",
          "size": 861,
          "sha512": "7bbbd57be798cc045ae8389b820e1d1d8fc1948b8fbdaf0fa760a465ebf54812ff319a59c4e4fa24bb401ce073e0e16701f2b412ca6b4ce8f7b6675d01949d4f",
          "sha256": "8a75c1d84fb3492591034334e6730deaf95cbca8dbcb781d8212ddd54044bab1",
          "sha1": "39f46a2865bbf2bc20bb579a037b365954ac0bba",
          "md5": "f1aacaff02ad6f0b13875b46198348cc"
        }
      ]
    }
  ]
}
` 

### Your Environment

Build scan URL:

**Comment by jjohannes** [comment]
Thanks for the report @bdeneuter. The problem is not that the platform constraints are ignored, but that we expect a version during parsing although it is totally fine that there is no version in a capability request.
This was an oversight from our side. Instead of publishing null, it should publish nothing and  when consuming the publication it should not fail. Working on a fix for 6.1.

**Comment by jjohannes** [comment]
@bdeneuter the fix is in the latest 6.1 night - `6.1-20191217025822+0000`. Can you confirm that it fixes the issue for you?

**Comment by bdeneuter** [comment]
@jjohannes thanks, I tested it and with the gradle version you specified it works.
