### ISSUE TITLE
Disable default "pluginMaven" publication for maven-publish plugin

### ISSUE THREAD

**Issue by dnut** [gradle/gradle#11611]
For the maven-publish plugin, there is no way to disable the default publication called pluginMaven. So it clutters my tasks and it forces me to publish pluginMaven if I ever run `maven publish`. Then my publication gets overwritten in maven and I can never make use of it:

> Multiple publications with coordinates ... are published to repository ... The publications will overwrite each other!

The recommendation in #10384 is to merge my publication with pluginMaven. Well I don't want to include a pointless jar and module in my publication. Also, it would be nice to give it a descriptive name. It's frustrating that there is no way to disable the default publication.

I can't just set `enabled = false` for the generated tasks because different task names are automatically generated depending on the available maven repositories. These tasks run on many systems with several repositories available. I need to be able to delete the entire publication, not just play whack-a-mole with the tasks.

**Comment by ljacomet** [comment]
The `maven-publish` plugin does not add any default publication.

What other plugins are you applying?

The issue you reference is about publishing a Gradle plugin, which indeed adds a publication.
But your comment about not needing a "pointless jar and module" makes me wonder if you are not using plugins you do not need.

**Comment by dnut** [comment]
You're right. It was the kotlin-dsl plugin. I misunderstood the purpose of that plugin. Thanks.

**Comment by TWiStErRob** [comment]
The built-in `pluginMaven` publication can be disabled with:
 * From build.gradle:
    ```gradle
    gradlePlugin { automatedPublishing = false }
    ```
 * From buildSrc:
    ```kotlin
    project.plugins.withId("java-gradle-plugin") { // only do it if it's actually applied
    	project.configure<GradlePluginDevelopmentExtension> {
    		isAutomatedPublishing = false
    	}
    }
    ```

This disables adding the publication in `MavenPluginPublishPlugin`.

Tried and tested in Gradle 5.6.4
