### ISSUE TITLE
Consumption of dependencies from existing Maven repositories

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1161]
Gradle is compatible with consuming dependencies from Maven repositories to a large extent. Users reported various dependencies and conditions under which Gradle does not behave like Maven or fails to resolve a dependency.

### Expected Behavior

Gradle can resolve dependencies via the defined metadata POM similar to Maven. Any known POM parsing issues are fixed. 

https://issues.gradle.org/browse/GRADLE-2159?jql=status%20%3D%20Open%20AND%20text%20~%20%22pom%20parsing%22

This story does not address the support for Maven BOMs.

### Current Behavior

Known issues reported by users about POM parsing issues or unresolvable dependencies.

### Context

Ensure that existing Maven repositories and their published dependency can be reused. This is especially important for users migration from Maven to Gradle.

**Comment by wilkinsona** [comment]
Will this cover exclusions declared in a pom behaving as they would in Maven? That's something that has caused us some trouble in the past and I'd love to see Gradle's behaviour align with Maven's here.

**Comment by bmuschko** [comment]
@wilkinsona Correct. I turned this issue into an Epic and will assign relevant issues moving forward. Can you point me to the issue that describes the problems with exclusions or create a new one?

**Comment by wilkinsona** [comment]
I couldn't find an existing issue so I have opened https://github.com/gradle/gradle/issues/1473

**Comment by scr** [comment]
FYI https://issues.gradle.org/browse/GRADLE-3115 is also related to this

**Comment by jjohannes** [comment]
Closing this Epic. Further work will be tracked through `in:dependency-...` labels.
