### ISSUE TITLE
Improve handling of notifyDaemonsAboutChangedPaths TAPI call

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11627]
The 6.1 implementation of `notifyDaemonsAboutChangedPaths` can be improved. There are currently some limitations:

1. There is a race condition between checking whether the Daemon is idle and actually sending the command to the daemon.
2. Even busy daemons should be notified about file changes to source files, while they are not interested in changes they are doing themselves. We should do something similar we will do for the file watchers for this API on the daemon side. As a first step, we could queue up notifications from the IDE and invalidate the FS state at the end of the build.
3. ~~The tooling API client should iterate over all of the versions of the tooling API providers it has loaded up and notify each one of each change, rather than notifying whichever version currently happens to be used (eg I'm switching between branches where different Gradle versions are being used).~~ -> https://github.com/gradle/gradle/issues/15218

See for example [this comment](https://github.com/gradle/gradle/pull/11604#discussion_r355223746).

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
Another thing we could do:
> I haven't thought it completely through, but another way of doing this could be to have a "invalidation broadcaster" service that the VirtualFileSystem can listen on. Then instead of reaching into the service registry to get the VirualFileSystem, you could just broadcast the invalidation list.
That might make testing a little easier since you could assert that the listener was called vs looking at the log.

See https://github.com/gradle/gradle/pull/11604#discussion_r354971866.

**Comment by wolfs** [comment]
1) and 2) will be fixed by https://github.com/gradle/gradle/issues/15199

**Comment by wolfs** [comment]
I created https://github.com/gradle/gradle/issues/15218 for 3). This is now done.

**Comment by lptr** [comment]
Shall we close this?
