### ISSUE TITLE
Unexpected dependency substitution where implicit module replaced by project

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle#11625]
When upgrading [caffeine](https://github.com/ben-manes/caffeine) to use ErrorProne v2.3.4, its transitive dependency on Caffeine is replaced by a project dependency. Since ErrorProne is compiling Caffeine, this results in a `NoClassDefFoundError`. See https://github.com/google/error-prone/issues/1445.

### Expected Behavior
The module dependency is used and does not conflict with building the project.

### Current Behavior
The module dependency is rewritten to be on the project. There are no dependency substitutions and the conflict resolution remains on `latest` (as not using `preferProjectModules`).

```
./gradlew :caffeine:dependencyInsight \
  --configuration errorprone \
  --dependency com.github.ben-manes.caffeine:caffeine
```
```
> Task :caffeine:dependencyInsight
project :caffeine
   variant "errorprone"
   variant "runtimeElements" [
      org.gradle.usage               = java-runtime (not requested)
      org.gradle.libraryelements     = jar (not requested)
      org.gradle.dependency.bundling = external (not requested)
      org.gradle.category            = library (not requested)
      org.gradle.jvm.version         = 8 (not requested)
   ]

com.github.ben-manes.caffeine:caffeine:2.7.0 -> project :caffeine
\--- com.google.errorprone:error_prone_check_api:2.3.4
     \--- com.google.errorprone:error_prone_core:2.3.4
          \--- project :caffeine (*)

(*) - dependencies omitted (listed previously)
```

### Context
There are no customizations to the resolution strategies for the build. A reflective toString of the configurations, etc doesn't show anything amiss.

```groovy
import org.apache.commons.lang3.builder.*

configurations.all.each {
  print ToStringBuilder.reflectionToString(
    it.resolutionStrategy, ToStringStyle.MULTI_LINE_STYLE)
}
```

### Steps to Reproduce 
1. Clone [caffeine](https://github.com/ben-manes/caffeine)
2. Update `gradle/dependencies.gradle` to use the version `errorprone: '2.3.4'`.
3. Run any of the commands,
    - `./gradlew clean build -x test` to fail,
    - `./gradlew :caffeine:dependencies --configuration=errorprone`
    - `./gradlew :caffeine:dependencyInsight --configuration errorprone --dependency com.github.ben-manes.caffeine:caffeine`

### Your Environment
Note that Java 8 is still the default JDK for this project.

**Comment by ben-manes** [comment]
After a lot of various attempts, the only way I could get around this was to use a local jar dependency. This way Gradle does not rewrite based on the `maven-metadata.xml`, e.g. if using jitpack. I wasn't able to configure the build in a way to disable this replacement, which is implicitly done for transitive dependencies to the executing project. A sibling project in a multi-project build refers to the external jar.

https://github.com/ben-manes/caffeine/commit/aa0cdfad2e94e4a39432f7d27f43ff0a3e25755a

**Comment by ljacomet** [comment]
Sorry for the late reply

The issue is in the backlog of the relevant team and is prioritized by them.
