### ISSUE TITLE
How to call gradlew for each included build in a composite build?

### ISSUE THREAD

**Issue by coder82** [gradle/gradle#11636]
Hi all,

I am running a complex composite build where the root project is trying to launch the tests of all included projects. Is there a way to call gradlew rather than gradle, I have several projects which are required to use their own gradle version. I cannot figure out how to do it.

```
task test {
    dependsOn gradle.includedBuilds*.task(":test")
}
```

I don't want to refer to it by name, the * helps me with that.

**Comment by lacasseio** [comment]
Only a single Gradle version is used across all included build for composite build.

Please use the [user forum for asking questions](https://discuss.gradle.org/). The GitHub repository is strictly for [reporting bugs](https://github.com/gradle/gradle/blob/master/.github/ISSUE_TEMPLATE/contributor_bug_report.md) and [requesting features](https://github.com/gradle/gradle/blob/master/.github/ISSUE_TEMPLATE/contributor_feature_request.md) following the respective template.

**Comment by coder82** [comment]
But that's why I thought u should add it as a feature, is this completely out of the current architecture?
