### ISSUE TITLE
Ability to generate web page deriving essential information about project

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1163]
For Maven users, the [Maven Site plugin](https://maven.apache.org/plugins/maven-site-plugin/) is important. I can't count the number of times I have been asked about an equivalent in the Gradle world. Establish a Gradle plugin that can render important information about project in the form of HTML pages.

### Expected Behavior

Gradle provides a plugin similar to the Maven Site plugin that allows for generating project information. The plugin would derive data from the build configuration to generate relevant information in HTML pages e.g. plugins applied, dependencies/repositories declared etc.

### Current Behavior

Project information can only be rendered as a web page via Gradle Cloud Services or the Enterprise version of Cloud Services.

### Context

Maven users will feel right at home. Project information could be easily hosted as part of a CI build or something similar.

**Comment by adammurdoch** [comment]
Sounds like a build scan to me.

**Comment by bmuschko** [comment]
@adammurdoch Generally speaking, I'd agree. Here's my only concern: some users might not want to use a cloud service (because of security/confidentiality issues) or want to provision/install/pay for commercial software _just_ to get some basic information about the project. The build scan is also heavily based on the execution of a specific task and the provided build parameters. I guess we'll see if the community has a strong reaction to this feature, especially users migrating from Maven. We can probably close it if nobody likes or votes it up.

**Comment by pioterj** [comment]
I think this type of page / report is typically meant to be shared. It could be another Cloud Services feature. Maybe not a build scan that is focused on execution of individual tasks but a "project scan" or something like that. 

@bmuschko I'd update the title and description to remove implementation details like that it would be a plugin and how it would work. Focus on the use case and the capability instead. As @adammurdoch pointed out we should have a discussion on how to provide such feature at some point.

**Comment by bmuschko** [comment]
I used the idea of a site plugin for a Gradle guide example project: https://github.com/gradle-guides/gradle-site-plugin. Maybe the community wants to take it from there.

**Comment by eriwen** [comment]
@bmuschko seems like we can close this and suggest people use build scans/gradle-site-plugin depending on their needs. Agreed?

**Comment by bmuschko** [comment]
@eriwen Yeah, you can close it.
