### ISSUE TITLE
Pin snapshot not working

### ISSUE THREAD

**Issue by pedrolamarao** [gradle/gradle#11639]
Using Gradle 6.0.1, pinning a dependency SNAPSHOT version is not working for us:

> Could not find crypto-pfx-1.0.0-20191122.161310-5.jar (prodist-jvm:crypto-pfx:1.0.0-SNAPSHOT:20191122.161310-5).
  Searched in the following locations:
      http://nexus.prodist.com.br:8081/repository/maven-beta/prodist-jvm/crypto-pfx/1.0.0-20191122.161310-5/crypto-pfx-1.0.0-20191122.161310-5.jar

This seems to be a regression to GRADLE-2784.

### Expected Behavior
Coordinates (prodist-jvm:crypto-pfx:1.0.0-SNAPSHOT:20191122.161310-5) map to location http://nexus.prodist.com.br:8081/repository/maven-beta/prodist-jvm/crypto-pfx/1.0.0-SNAPSHOT/crypto-pfx-1.0.0-20191122.161310-5.jar

### Current Behavior
http://nexus.prodist.com.br:8081/repository/maven-beta/prodist-jvm/crypto-pfx/1.0.0-20191122.161310-5/crypto-pfx-1.0.0-20191122.161310-5.jar

### Context
Dependency published with Gradle 6.0.1.

### Steps to Reproduce 
Publish SNAPSHOT version of component to Maven repository with Gradle 6.0.1.
Define a project with a pinned dependency on this specific SNAPSHOT.
Build project.

### Your Environment
Build scan URL: https://scans.gradle.com/s/ujgfj6keayjpq

**Comment by ljacomet** [comment]
Thanks for the report, I have been able to reproduce.
Looks like while doing fixes for #9462, some corner cases were still missed.

**Comment by pedrolamarao** [comment]
We did a quick check today:

- 5.6.4 [succeds]
- 6.0.1 [fails]
- 6.1 20191218000035+0000 [succeeds]

**Comment by ljacomet** [comment]
Thanks for taking time to confirm the fix is working.
