### ISSUE TITLE
Building Gradle plugins with Maven

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1164]
An organization mainly uses Maven to build their projects. As a library or tooling provider you already have a multi-module build in place built with Maven. Gradle has become an important ecosystem and you want to provide a Gradle plugin to support the use case but don't want to break out the plugin logic into a new repository. In those cases you'd like to build and publish the Gradle plugin with Maven. In practice that means that you need to be able to reference the Gradle API from a repository.

### Expected Behavior

Organizations can easily build Gradle plugins with Maven. Gradle API JARs need for compilation can be resolved from a publicly available repository.

### Current Behavior

Gradle only publishes some core libraries. Gradle does not publish the shaded JARs.

### Context

Organizations which mainly build projects with Maven still want to provide a solution for Gradle but not build it with Gradle.

**Comment by big-guy** [comment]
I think publishing the jars is only one solution that has a lot of downsides. It's hard(er) to run TestKit tests, you don't get any of the plugin validations that we've added/are adding and we may want to have more than one kind of gradleApi publication (e.g., public only and legacy public/internal).

As another idea, we could also build a Maven MOJO that can build Gradle plugins.

**Comment by ajoberstar** [comment]
This seems related to my issue #1835.
