### ISSUE TITLE
Enhance Maven migration documentation and samples

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1166]
Maven users new to Gradle need guidance. We already established a migration guide but it wasn't promoted heavily. We should enhance it by any outstanding topics, promote it heavily and ask the community for feedback. In addition to the guide, provide example projects.

### Expected Behavior

Maven users can map existing concept from Maven to Gradle land. Any missing topic is going to be added over time based on feedback. Maven users will know how to effectively approach a migration.

### Current Behavior

Little information on the web about how to work around challenges a Maven user faces when migrating to Gradle.

### Context

Enable and educate Maven users on how to migrate their project to Gradle.

**Comment by eriwen** [comment]
This is an epic that's not really actionable, I'm afraid. Documentation should be a part of other tasks we do, so I think we should close this for now in favor of either specific actions or docs produced by other maven migration stories.

**Comment by oehme** [comment]
I agree with Eric on this one. Let's make docs part of upcoming Maven interop stories.
