### ISSUE TITLE
Allow fine-grained control for incremental task execution

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#11679]
### Expected Behavior

It would be great if something like the following was available:

a) `inputChanges.ack(property, file)` to mark the file as processed, so the next execution of the task would not process the file again even in case the task fails. This would be useful when task processes files individually, so it can process some of the files (e.g. verify them), and at the end the task might fail with ta set of violations. However, it would be great to skip re-processing if the task is re-executed with the same parameters.
b) `inputChanges.reject(property, file)` to mark the file as rejected, so the file should be passed again on the next task execution even if the task succeeds.
c) `inputs.canUseIncremental { ... }` callback so task-specific logic could verify if new inputs allow for incremental execution (or if full execution is needed). For instance, if user updates configuration of the task like "forbid unused imports", then the task could check previous execution results and find out that "unused imports" were never detected previously, so there's no need to re-execute the task even though its "input" has changed.

a&b would be great as well for the tasks that modify their inputs (e.g. fix newlines in the source files).

### Current Behavior

Under the current execution model, Gradle performs non-incremental execution in case any input changes. It is like "all or nothing". If the task fails, Gradle thinks that "all inputs need to be re-processed" the next time the task executes.

That makes it complicated to implement incremental tasks that process individual files.

### Context

I'm implementing a task/plugin that verifies "code style". The files can be processed independently, so I would like Gradle to provide API like "treat this file as processed", or "treat this file as unprocessed".

The set of input files might be huge, so it is important to process the files incrementally. However, Gradle tasks are not suitable for file-by-file incremental processing.

**Comment by lptr** [comment]
There's a similar (though somewhat more limited/focused) idea floating around, where the task defines the mapping between input and output files. This would allow Gradle to parallelize more, and to make sure changes like a source file disappearing are properly handled. This could cover some of the use cases you mention here.

**Comment by lptr** [comment]
We also have the `@Incremental` annotation to be used with the new `InputChanges` API to mark properties that can participate in incremental execution. If a property _not_ marked as `@Incremental` changes then incremental execution is disabled. This covers some of c).

**Comment by vlsi** [comment]
I've seen https://github.com/gradle/gradle/issues/11440, but does not seem to be completely related.

The case for "code tool" / "verification" tasks is they do not really produce much output.
In other words, they do not compile tasks and so on.

**Comment by vlsi** [comment]
> We also have the @Incremental annotation to be used with the new

AFAIK `@Incremental` + `@Input` does not really work:

```
Could not determine the dependencies of task ':autostyleApply'.
> Could not create task ':autostyleMiscApply'.
   > A problem was found with the configuration of task ':autostyleMiscApply'.
      > has @Incremental annotation used on an @Input property
```

**Comment by lptr** [comment]
Yes, at present incrementality is only available for file inputs.

**Comment by altsvetkov** [comment]
> We also have the @Incremental annotation to be used with the new InputChanges API to mark properties that can participate in incremental execution

@lptr is there an issue for that?
