### ISSUE TITLE
Check if daemon is reused in VFS retention integration tests

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11682]
I've seen this happen a few times that when running `VirtualFileSystemRetentionIntegrationTest` as a forking integration test sometimes daemons were not reused when they should have been. The reason I saw for the daemon not reused for `source file changes are recognized` was that the previous daemon was incompatible.

This shouldn't happen. If it does, then we just throw away the VFS contents together with the daemon. and thus we are not testing what we should. Therefore we need a mechanism to declare that a subsequent build must happen using the same daemon as the previous one in the same test. Or we might just check this for every test in forking mode unless the test opts out explicitly.

---
cc: @gradle/build-cache

**Comment by big-guy** [comment]
I think the way we do this in other tests is to opt into isolated daemons (`requireIsolatedDaemons` on the executer). Could you be seeing not incompatible daemons but expired daemons interfering with the tests?

e.g.,
- VirtualFileSystemRetentionIntegrationTest test starts running a Gradle build. Daemon starts.
- Other suite test starts a different (incompatible) Gradle build. Another daemon starts.
- VirtualFileSystemRetentionIntegrationTest build finishes. Daemon expiration kicks in and the first daemon expires.
- Other suite test finishes.
- VirtualFileSystemRetentionIntegrationTest test starts second build step.  The previous daemon is gone and the only running one is incompatible.  New daemon starts.

It might require extra pressure for the expiration to kick in so quickly.

You probably want isolated daemons anyways so another compatible daemon doesn't slip in between steps.

**Comment by lptr** [comment]
I was only running this one test suite, and there wasn't much pressure either. Good point about the isolated daemons, thanks!

**Comment by wolfs** [comment]
I started using isolated daemons for the VFS retention tests. See https://github.com/gradle/gradle/pull/11719 for a PR.

I got now basically all the tests working - now I get problems since there are some leftover files: https://builds.gradle.org/viewLog.html?buildId=29760624&problemId=52892

```
/home/tcagent1/agent/work/a16b87e0a70f8c6e/subprojects/version-control/build/tmp/test files/unknown-test-class/v3pys/daemon/6.2-20191218181405+0000/registry.bin.lock
[19:35:16]/home/tcagent1/agent/work/a16b87e0a70f8c6e/subprojects/version-control/build/tmp/test files/unknown-test-class/ryumm/daemon/6.2-20191218181405+0000/registry.bin
```

I suppose that means that the isolated daemon exits after the test cleanup finished and therefore recreates the registry? Or is something else going on?

**Comment by wolfs** [comment]
Looks like I have been doing it wrong. Now it works.

**Comment by lptr** [comment]
What fixed the problem?

**Comment by wolfs** [comment]
The problem was that the way I called `requiredIsolatedDaemons` caused the daemons not to be cleaned up since there daemon registries were not registered. Mostly a problem how I extended our test infrastructure.

**Comment by wolfs** [comment]
This works now, since we require isolated daemons.
