### ISSUE TITLE
Gradle Wrapper Jar checksum mismatch on Debian-based distributions

### ISSUE THREAD

**Issue by tegoo** [gradle/gradle#11699]
### Expected Behavior
Checksum matches officially published checksum. It might differ due to changes introduced by Debian packagers. If so, it should be mentioned in Gradle Wrapper documentation (under Checksum verification section).

### Current Behavior
Checksum does not match. It might differ due to changes introduced by Debian packagers. There is no way for users of Debian-based distributions to verify checksum.

### Context
- Generating Gradle wrapper, want to verify checksum of jar.

### Steps to Reproduce 
- In Debian-based distribution run `gradle wrapper`
- Check sha256sum of generated jar.

### Your Environment
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"

$ gradle --version
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.6 compiled on July 11 2019
JVM:          11.0.5-ea (Ubuntu 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OS:           Linux 5.3.0-24-generic amd64

$ gradle wrapper
BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
$ sha256sum gradle/wrapper/gradle-wrapper.jar 
803c75f3307787290478a5ccfa9054c5c0c7b4250c1b96ceb77ad41fbe919e4e  gradle/wrapper/
```

**Comment by big-guy** [comment]
Sorry, we don't support the Debian Gradle package. 

Please [install](https://gradle.org/install/) Gradle with one of the ways that install distributions we build.
