### ISSUE TITLE
Make up-to-date checks for :kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable faster

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11693]
Currently, even when running with VFS retention enabled, snapshotting the inputs for `:kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable` takes more than 300ms.

It seems like this is due to the `zipTree` input, and the sources of the `Sync` task being marked with `SkipWhenEmpty`: When determining whether the sources are empty, the whole zip file is unzipped.

This is the flame graph from Async-profiler running a fully up-to-date build:
![image](https://user-images.githubusercontent.com/423186/70914982-4f01a300-2019-11ea-9ad6-61ad983f530e.png)

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
Moved this to 6.4 when we will focus on VFS/snapshotting performance.

**Comment by wolfs** [comment]
Looking closer into the flame graph, it seems Gradle does not unzip the zip but reads the whole zip header. That seems to take around 900ms.

When I replace the task by a task with a custom `Unzip` task with a single input file then up-to-date checking is much faster.

I am also not sure why we need `unpackPatchedKotlinCompilerEmbeddable` at all. I think it is only in place so that IDEA doesn't show error in the `kotlin-dsl` subproject, e.g. in [`Lexer.kt`](https://github.com/gradle/gradle/blob/691cc03e066763aae6fc6ea13c47ca0de224d3c5/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Lexer.kt#L19-L26).

The IDEA support seems broken for me right now even with the task: 
![image](https://user-images.githubusercontent.com/423186/84001843-be70a380-a967-11ea-8c85-3946c7e63c7a.png)

**Comment by wolfs** [comment]
The IDEA support may have worked at some point by unpacking the patched Kotlin compiler, though it stop working. Since unpacking the compiler is pretty expensive, we should avoid doing so. See https://github.com/gradle/gradle/issues/11693 and for more context.

**Comment by wolfs** [comment]
I removed the task in https://github.com/gradle/gradle/issues/13359, so this is not something we need to do to make the Gradle build faster.
