### ISSUE TITLE
Build script class names depend on the absolute path

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11703]
It seems like we use the absolute path for the class names of build scripts, see https://github.com/gradle/gradle/blob/a138710ab109e271b17ee48dc49b359284cd3f66/subprojects/core/src/main/java/org/gradle/groovy/scripts/TextResourceScriptSource.java#L76-L79.

As a consequence, `Closure`s defined in build scripts (`build.gradle`) also will have a reference to the absolute path of the build script. The class name looks something like this: `build_cy3ca74runcdcinr48br22m24$_run_closure2$_closure4`.

This means that nested beans, like `CommandLineArgumentProvider`s, defined by `Closure`s in build scripts will cause the task to become non-relocatable.

For example, this is what happened in the spring boot build: https://ge.spring.io/c/4odyr2tkwjse6/aha5vme4vawuo/task-inputs

This is the corresponding code: https://github.com/wilkinsona/spring-boot/blob/7e400d1e73b0d008b6e4f4c200fe1bec9cb7a10c/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-data-cassandra/build.gradle#L23-L32

As a workaround, an actual class can be defined in the build script, which causes the class name to not contain a reference to the build script.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
We should probably use the same logic as we use for determining the class name of task actions: https://github.com/gradle/gradle/blob/bf64fff701e3d2033d41b891079969f1156d0cc4/subprojects/core/src/main/java/org/gradle/api/internal/AbstractTask.java#L773-L780

In other words, we should use `ScriptOrigin` when available.

**Comment by lptr** [comment]
How did we not find this problem before? Ah, because we don't have a way to check if script sources load from the cache. Using the execution pipeline for this would have fixed/highlighted the problem.

**Comment by wolfs** [comment]
> How did we not find this problem before? Ah, because we don't have a way to check if script sources load from the cache. Using the execution pipeline for this would have fixed/highlighted the problem.

This has nothing to do with loading the script sources from the cache. The problem here is that a nested bean is defined by an anonymous inner class a build script. The reason we missed this seems that we simply didn't have a test for it.

**Comment by wolfs** [comment]
We should probably check if this is a problem for Kotlin as well.

**Comment by wolfs** [comment]
Looks like this is only a problem for Groovy: #11962.

**Comment by lptr** [comment]
I guess this would be easy to fix when we make Groovy DSL compilation via the execution engine, right?

**Comment by wolfs** [comment]
> I guess this would be easy to fix when we make Groovy DSL compilation via the execution engine, right?

I don't see how using the execution engine and fixing the absolute path names in script classes is related.

**Comment by lptr** [comment]
Let's put it this way: the conversion will present an opportunity to fix both.

**Comment by wolfs** [comment]
Still an issue.
