### ISSUE TITLE
Build scan does not prompt license agreement via ssh

### ISSUE THREAD

**Issue by neworld** [gradle/gradle#11711]
Execute gradle task with `--scan` ivia ssh like:
```
ssh mainframer "cd mainframer/android && ./gradlew tasks --scan"
```

### Expected Behavior
Get a prompt for agree or disagree of terms

### Current Behavior
The message at the end of the build output:
```
The build scan was not published due to a configuration problem.

The Gradle Terms of Service have not been agreed to.

For more information, please see https://gradle.com/scans/help/plugin-terms-of-service.

Alternatively, if you are using Gradle Enterprise, specify the server location.
For more information, please see https://gradle.com/scans/help/plugin-enterprise-config.
```

### Context
Most of the time I am building on the remote machine. On older gradle versions I was able to agree for terms only on my machine using `init.gradle` configuration:
```
allprojects {
  plugins.withId('com.gradle.build-scan') {
    buildScan { termsOfServiceUrl = "https://gradle.com/terms-of-service"; termsOfServiceAgree = "yes" }
  }
}
```

However, since 6.x it does not work anymore. Also, put the agreement on the repository is not a good idea either. 

### Steps to Reproduce 

1. You need set up a remote server with any project `gradle init for example` and ssh access
2. ssh <server_connect> "cd <dir> && ./gradlew tasks --scan"

### Known workaround

Temporally put and do not forget to remove before pushing code to the repo. It is annoying but it is working:
```
buildScan {
    termsOfServiceUrl = "https://gradle.com/terms-of-service"
    termsOfServiceAgree = "yes"
}
```

**Comment by big-guy** [comment]
The build scan plugin changed in 6.0: https://docs.gradle.com/enterprise/gradle-plugin/#upgrading_to_gradle_6

A different plugin is applied, so your callback no longer fires. I think you want something like this now:
```
gradle.settingsEvaluated { settings ->
    settings.plugins.withId("com.gradle.enterprise") {
        settings.gradleEnterprise.buildScan { 
            termsOfServiceUrl = "https://gradle.com/terms-of-service"; termsOfServiceAgree = "yes" 
        }
    }
}
```
