### ISSUE TITLE
Unclear report on task state serialization failure in instant execution

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#11723]
This was initially reported in the Kotlin issue tracker: [(link)](https://youtrack.jetbrains.com/issue/KT-35181#focus=streamItem-27-3873778.0-0)

In a certain case of instant execution task state serialization failure, the console output and the failure report don't give enough information to diagnose the issue.

This happened in a sample project during testing of instant execution support for Kotlin Kapt tasks with Android Gradle plugin. One of the tasks created by the Android Gradle plugin failed to serialize, but the report and the console output didn't give a clear hint as to which task it was.

### Expected Behavior

Clear diagnostics including the name of the task that failed to serialize.

### Current Behavior

Task name missing in both the console output and the instant execution failure report.

The stacktrace will be:
```stacktrace
AllErrorsWarnings
1 instant execution problems were found
Learn more about Gradle Instant Execution.
Problems grouped by message
▼ ❌ Don't know how to serialize an object of type org.gradle.execution.plan.ActionNode.
▼ Gradle runtime
▼ exception stack trace 📋
java.lang.IllegalArgumentException: Don't know how to serialize an object of type org.gradle.execution.plan.ActionNode.
	at org.gradle.instantexecution.serialization.codecs.BindingsBackedCodec.computeEncoding(BindingsBackedCodec.kt:75)
	at org.gradle.instantexecution.serialization.codecs.BindingsBackedCodec.access$computeEncoding(BindingsBackedCodec.kt:33)
        ...
```

The instant execution failure report can be found in [this comment](https://youtrack.jetbrains.com/issue/KT-35181#focus=streamItem-27-3874815.0-0).

This culprit task name only appeared in the `--debug` logs:
```
2019-12-18T07:42:14.244-0800 [INFO] [org.gradle.instantexecution.DefaultInstantExecution] instant-execution > serialized field `actions` of task `:modules:module-app:mergeDebugJavaResource` of type `com.android.build.gradle.internal.tasks.MergeJavaResourceTask` with value [org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction@1edcd555]
2019-12-18T07:42:14.244-0800 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 15: released lock on :modules:module-app
2019-12-18T07:42:14.245-0800 [WARN] [org.gradle.instantexecution.DefaultInstantExecution] 1 instant execution problems found:
  - unknown property: Don't know how to serialize an object of type org.gradle.execution.plan.ActionNode.
```

### Steps to Reproduce 
Run a build using Android Gradle plugin 4.0.0-alpha04 with `-Dorg.gradle.unsafe.instant-execution=true` – under certain conditions (I have no exact steps) it will fail to serilalize a task.

**Comment by eskatos** [comment]
Thanks for the report @h0tk3y 
It seems the report doesn't attribute serialization problems in task actions to tasks.

**Comment by eskatos** [comment]
Here's the instant execution problem reports for the issue [es6rhda5rbize84j7c75rhkui.zip](https://github.com/gradle/gradle/files/3982956/es6rhda5rbize84j7c75rhkui.zip)

**Comment by stephanenicolas** [comment]
In https://issuetracker.google.com/issues/146458537 we have the hypothesis that it might be a doFirst / doLast property of a task that is not being reported in the IE report...

**Comment by adammurdoch** [comment]
@eskatos It doesn't make any sense to attribute `ActionNode` serialization problems to a task, as these are nodes in the work graph. They're siblings of task and artefact transforms. Issues related to them should be attributed to something like "Gradle internals" or "Gradle dependency management".

**Comment by adammurdoch** [comment]
@stephanenicolas This failure is due to some of the Gradle internals not yet being fully supported with instant execution. You shouldn't have to change your build to fix this particular problem. Instead, we will fix the problem soon and you can try again.

**Comment by stephanenicolas** [comment]
@adammurdoch thx for the follow up. Let us know when we can try a build. I didn't know that Gradle had ActionNodes outside of tasks. But anyway, yes, I would be happy to try again instant execution on our build when this bug is fixed and we can report issues more accurately. Thx for working on this.

**Comment by stephanenicolas** [comment]
Just as a side note. Someone from google suggested that it might a `doFirst`/`doLast` related issue in https://issuetracker.google.com/issues/146458537. Will the fix report these accurately as well ?
(Or are ActionNode the representation of `doFirst`/`doLast` for instance?)

I am waiting for a better reporting tool before changing our codebase.

**Comment by adammurdoch** [comment]
@stephanenicolas this should be fixed now. You can try this out using a recent Gradle nightly build

**Comment by stephanenicolas** [comment]
Thx Adam, I am off until next Monday. I will give it a try early next week.

Le jeu. 2 janv. 2020 05 h 42, Adam Murdoch <notifications@github.com> a
écrit :

**Comment by bamboo** [comment]
Closing this one for 6.2 as the original `ActionNode` related issue was fixed.

Feel free to open new issues to help us improve the reporting of problems.
