### ISSUE TITLE
I can't close the Gradle process

### ISSUE THREAD

**Issue by QQ794763733** [gradle/gradle#11729]
Hi,I have a probleam,I fell very strange,
I don't sure it's a bug or some configuration error of mine.
![idea](https://user-images.githubusercontent.com/30444727/71169796-c2fbaf80-2294-11ea-9db7-054cb26b4e0c.png)
Have another Gradle instance.I try to close it.but i can't.
There is a Gradle process in my system.
Its pid is change every second,It's active when i reboot my computer,I can't close it.
![terminal](https://user-images.githubusercontent.com/30444727/71169888-f9d1c580-2294-11ea-93f4-1a470b9cfe90.png)
So,Delete lock file of caches directory do not help.

Build any project that's i create or already exists is failure in idea.
Maybe is setting error of idea of mine,I set gradle and java environment,And setting gradle home directory for build tools of idea.

Thanks look this issue.

**Comment by big-guy** [comment]
You're not seeing a Gradle process.  That's just grep. The command has `gradle` in its command-line.

You'd see the same thing if you ran `ps -a | grep foobar` (there's no foobar process).
