### ISSUE TITLE
Gradle 6.x - Unable to pull down zipped maven dependency

### ISSUE THREAD

**Issue by ravikancherla** [gradle/gradle#11725]
### Expected Behavior
Like any other dependency, zip file in the artifactory was working in gradle 5.x versions. Expected to work the same in gradle 6.x as well

### Current Behavior
Unable to pull zipped dependency

### Context
We have custom checkstyle configuration zipped into maven artifactory and use regex to get latest version so every developer is consistent with coding styles.

### Steps to Reproduce 
```
plugins {
  id 'checkstyle'
}

repositories {
  mavenLocal()
  maven {
    url 'https://xyz-maven-repo.com/artifactory/xyz-repo'
  }
}

configurations { 
  checkstyleConfig
}

dependencies {
  checkstyleConfig "com.xyz:checkstyle:+@zip"
}

// Checkstyle
tasks.withType(Checkstyle) {
  group = 'checkstyle'
  reports {
    xml.enabled false
    html.enabled true
  }
}

checkstyle {
  config = resources.text.fromArchiveEntry(
      configurations.checkstyleConfig, "checkstyle/checkstyle.xml")
}
```

### Output
```
Execution failed for task ':checkstyleMain'.
> Could not resolve all files for configuration ':checkstyleConfig'.
   > Could not find any matches for com.xyz:checkstyle:+ as no versions of com.xyz:checkstyle are available.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Please note that same configurations work in gradle 5.x versions. We are noticing this only after gradle 6.x upgrade. I have tried with just version instead of using regex and that doesn't seem to work as well

**Comment by ljacomet** [comment]
You are most likely facing [this breaking change](https://docs.gradle.org/current/userguide/upgrading_version_5.html#maven_or_ivy_repositories_are_no_longer_queried_for_artifacts_without_metadata_by_default).

Can you try adding an `artifact()` metadata source to your repository declaration?
If that fixes the problem, I would recommend combining repository content filtering to make sure you have a dedicated repository for this dependency where you would only search for the artifact and no metadata at all.

**Comment by ravikancherla** [comment]
```metadataSources {
      mavenPom()
      artifact()
    }
```

Adding both `mavenPom` and `artifact` worked. Thanks for the solution

**Comment by caiqichang** [comment]
> ```
> metadataSources {
>       mavenPom()
>       artifact()
>     }
> ```
> 
> Adding both `mavenPom` and `artifact` worked. Thanks for the solution

i meet this problem too, and also fail after add these.
