### ISSUE TITLE
Print diagnostics in KotlinDslScriptsModelBuilder with info level logging only

### ISSUE THREAD

**Issue by NataliaUkhorskaya** [gradle/gradle#11730]
Now in https://github.com/gradle/gradle/blob/0c2a6de9b9303c2659834fd30ce27dcb90787268/subprojects/kotlin-dsl-tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinDslScriptsModelBuilder.kt#L120 there are a `println` call that pass diagnostic information to default output

### Expected Behavior
Pass those diagnostics only with info level logging

### Context
They appear in IDE console log that is quite annoying for users
see https://youtrack.jetbrains.com/issue/KT-35552

**Comment by eskatos** [comment]
Fixed in #11733, will ship in Gradle 6.2
