### ISSUE TITLE
InstantExec - resolving configuration w/o building the artifact to be transformed

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#11754]
Gradle version: `6.2-20191221230424+0000`
Run: `./gradlew :app:javaPreCompileDebug`

Serializing this task fails because configuration is resolved before `:lib` is built. Field that fails to be stored is: https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/JavaPreCompileTask.java#53

[AnnotationProcessorPreCompile.zip](https://github.com/gradle/gradle/files/3995202/AnnotationProcessorPreCompile.zip)

**Comment by adammurdoch** [comment]
This should be fixed now via https://github.com/gradle/gradle/pull/11776

**Comment by eskatos** [comment]
https://github.com/gradle/gradle/pull/11781 un-fixed this, reopening

**Comment by eskatos** [comment]
Running:
```
git clone https://github.com/gradle/perf-android-large.git
cd perf-android-large
git checkout android-36
```
and updating Gradle to nightly 6.2 and AGP to 4.0.0-alpha08,
```
gw :phthalic:assDeb -Dorg.gradle.unsafe.instant-execution=true
gw clean -Dorg.gradle.unsafe.instant-execution=true
gw :phthalic:assDeb -Dorg.gradle.unsafe.instant-execution=true
```
fails with
```
Execution failed for IdentityTransform: /Users/gavra/AndroidStudioProjects/perf-android-large/outissue/caricetum/handbolt/build/libs/handbolt.jar.
   > Expecting a file or a directory: /Users/gavra/AndroidStudioProjects/perf-android-large/outissue/caricetum/handbolt/build/libs/handbolt.jar
```
which indicates that the subproject is not built before AT runs

see https://gradle.slack.com/archives/C10J6STFZ/p1578588082001100?thread_ts=1578587922.000600&cid=C10J6STFZ

**Comment by adammurdoch** [comment]
@eskatos The revert did not break the fix, it just removes some refactoring that ended up not being worth the effort at the moment. Instead, what you're seeing is a different issue with the same symptoms. Specifically, you're seeing the case where the `java-library` plugin does not create a JAR file if the classes directory does not exist when the instant execution cache is written, which we've seen before.

I think we should close this issue again, as the problem reported here is still fixed (task dependencies are not honoured when artefact transforms are applied to task outputs) and track the other problem (`java-library` does not produce a jar file) separately.

**Comment by adammurdoch** [comment]
The issue with Jar generation should be fixed now: https://github.com/gradle/gradle/pull/11953
