### ISSUE TITLE
InstantExec - Transforms with dependencies requiring other transforms fail

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#11753]
Running `./gradlew assembleDebug` (version `6.2-20191221230424+0000`) for the attached project fails with
```
1 instant execution problem was found, 1 of which seems unique:
  - Gradle runtime: objects of type 'org.gradle.execution.plan.ActionNode' are not yet supported with instant execution.
```

The issue seems to occur when running dexing artifact transform with dependencies that need to be additionally transformed. AT with dependencies are caused by `source/targetCompatibility` set to 1.8 in `app/build.gradle`. Dependencies need to be transformed because of `useAndroidX/enableJetifier=true` in `gradle.properties`. 

Commenting out `compileOptions` block in `app/build.gradle` fixes the issue. Also, commenting out `useAndroidX` and `enableJetifier` in `gradle.properties` fixes the issue.

[ArtifactTransformsWithDeps.zip](https://github.com/gradle/gradle/files/3994745/ArtifactTransformsWithDeps.zip)

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/11768

**Comment by adammurdoch** [comment]
@gavra0 thanks for the example build. This was very useful
