### ISSUE TITLE
Adding Groovy source directories to testSourceDirs for idea does not work

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#11758]
With Kotlin DSL in Gradle 5.6.2 this works perfectly fine to have the sources marked as test sources in IJ:
```kotlin
sourceSets {
    create("pitest") {
        idea {
            module {
                testSourceDirs = testSourceDirs + allJava.sourceDirectories.files
            }
        }
    }
}
```

But neither of these two seem to have any effect at all:
```kotlin
sourceSets {
    create("integTestCommon") {
        idea {
            module {
                this@create.withConvention(GroovySourceSet::class) {
                    testSourceDirs = testSourceDirs + allGroovy.sourceDirectories.files
                }
            }
        }
    }
}
```
```kotlin
sourceSets {
    create("integTestCommon") {
        withConvention(GroovySourceSet::class) {
            idea {
                module {
                    testSourceDirs = testSourceDirs + allGroovy.sourceDirectories.files
                }
            }
        }
    }
}
```

As Groovy supports joint compilation of Java files that are present in the Groovy source directories, in this case the workaround of course is easily to use `allJava` instead of `allGroovy`, but that is not the point, it should work properly imho.

**Comment by Vampire** [comment]
Still the same with Gradle 6.8 and IntelliJ 2020.3.1

**Comment by ljacomet** [comment]
Because both Gradle and JetBrains are moving away from the `idea` plugin, it is quite unlikely this will get attention in the short or medium term.
And to my knowledge the JetBrains Gradle plugin `idea-ext` does not support that kind of information for now.

**Comment by Vampire** [comment]
If they move away from `idea`, what are they moving to?
`idea-ext` is actually an extension on top of `idea` to configure additional things that are not configurable in `idea`, isn't it?

**Comment by reinsch82** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

---

Please provide a scenario that works and one that doesn't work for you.
As a hint you might want to consider using different APIs, since `testSourceDirs` and `withConvention` is deprecated.

**Comment by Vampire** [comment]
Ok, I updated the reproducer to current 7.6 API.
Just use `init` to create a `basic` build, create the directory `src/foo/groovy`, and put this in the build script:
```
plugins {
    idea
    groovy
}

sourceSets {
    create("foo") {
        idea {
            module {
                testSources.from(groovy.sourceDirectories)
            }
        }
    }
}
```
When you sync now, the the directory is marked as sources root, not test sources root.

**Comment by reinsch82** [comment]
Thx for the reproducer.
I checked what Gradle is providing to IntelliJ and it seems IntelliJ only shows the groovy code as test code when it also gets the java sources directories. That looks to me like an IntelliJ issue as the only difference here is that we add one more item to the list of test sources in the scenario where it works.

**Comment by Vampire** [comment]
Thanks for the investigation.
Follow-up issue: https://youtrack.jetbrains.com/issue/IDEA-313611
