### ISSUE TITLE
New sample Index missing Native examples and Java + Native (JNI)

### ISSUE THREAD

**Issue by swpalmer** [gradle/gradle#11765]
Release notes for 6.1.-rc-1 indicate I should file an issue about samples that are missing.  There is no sample project for C/C++ native code.

### Related Samples
In addition to a stand-alone native code sample, there should be an example that creates a JNI library and uses it in a Java project.

### Context
Java + JNI is not uncommon.   The JDK itself should really be using Gradle instead of the mess they have now (requiring Cygwin and other out-of-place tools on Windows).   OpenJFX uses Gradle, though not as effusively as they could, as the Gradle native support was not mature and they hacked in a similar awkward mess as the JDK.  A "pure Gradle" solution for these sorts of projects would be far simpler and elegant.

**Comment by lacasseio** [comment]
Thanks for the great request. We have a JNI sample in progress but is prioritized at the same level as native work. All native sample are unfortunately held within the https://github.com/gradle/native-samples. The goal is to make those samples discoverable via the same index as well as adding Kotlin DSL example and all the nice addition the new sample infrastructure gives us.
