### ISSUE TITLE
Snapshot versions are incorrectly ordered before non snapshot versions

### ISSUE THREAD

**Issue by svermeulen** [gradle/gradle#11760]
See the following test script:

```groovy
import org.gradle.api.internal.artifacts.ivyservice.ivyresolve.*
import org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.*

def left = "4.1.0-SNAPSHOT"
def right = "4.1.0-ALPHA.7"

tasks.register("run") {
  doLast {
    def versionComparator = new DefaultVersionComparator()
    def versionParser = new VersionParser()
    def result = versionComparator.compare(new VersionInfo(versionParser.transform(left)), new VersionInfo(versionParser.transform(right)));

    if (result == 0) {
      println "'${left}' == '${right}'"
    } else if (result < 0) {
      println "'${left}' < '${right}'"
    } else if (result > 0) {
      println "'${right}' < '${left}'"
    }
  }
}
```

This prints out `'4.1.0-ALPHA.7' < '4.1.0-SNAPSHOT'`.  However, when using these versions in a real project, this order is not respected.

I have created a minimal sample project that shows the issue and uploaded it here:  https://drive.google.com/open?id=1ble_VVLMbbO47bgerijYzxNwQfB6nUlX

This project contains 3 sub projects:  lib2, lib1, and app.  If you run the `run_test.sh` at the root the issue should be reproduced.  It should print:

```
------------------------------------------------------------
Project :app
------------------------------------------------------------

foolib
+--- com.svkj.bug_example:lib2:4.1.0-SNAPSHOT -> 4.1.0-ALPHA.7
\--- com.svkj.bug_example:lib1:1.0.0
     \--- com.svkj.bug_example:lib2:4.1.0-ALPHA.7

(*) - dependencies omitted (listed previously)
```

Which shows that gradle has chosen the `4.1.0-ALPHA.7` over the `4.1.0-SNAPSHOT` version.  I noticed also that if I use anything other than `-SNAPSHOT` (eg. `-SNAPXHOT`) then the `-SNAPXHOT` version does take precedence.  So it seems like gradle is doing special handling for `-SNAPSHOT` versions?  If so, this is different from the [official documentation for version ordering](https://docs.gradle.org/current/userguide/single_versions.html#version_ordering) which states that "The string SNAPSHOT has no special meaning".

### Expected Behavior

Gradle should behave as described in the documentation.  Snapshot versions should be treated similar to non snapshot versions.  In the example above, the snapshot version should be considered 'after' the ALPHA version.

### Current Behavior

The alpha version is considered more recent.

### Steps to Reproduce 

See above

### Your Environment

Mac OSX.  I tried both gradle 5.x and gradle 6.x with the same issue

**Comment by svermeulen** [comment]
This makes certain desirable workflows impossible.  For example, let's say you have a library A which depends on library B which depends on library C.  Let's then say that you publish a snapshot version of C and would like to test it in project A.  So you set up the following dependencies:

A -> C (version `1.0.0-SNAPSHOT`)
A -> B (version `1.0.0-ALPHA.5`)
B -> C (version `1.0.0-ALPHA.17`)

In this case, by default it will use C version `1.0.0-ALPHA.17` because it thinks `1.0.0-ALPHA.17` is larger/newer than `1.0.0-SNAPSHOT`.  It seems it is impossible to use the SNAPSHOT version of C without either re-publishing B to also use the C snapshot version, or to do this:

```
configurations.all { 
  it.resolutionStrategy {
    force 'C:1.0.0-SNAPSHOT'
  }
}

```

Both of which are not good options.

Publishing snapshots for testing like this is a common workflow, so I'm wondering whether there is a workaround?

**Comment by vlsi** [comment]
Just in case, here's a relevant article that describes Maven's behavior: https://octopus.com/blog/maven-versioning-explained#a-sorted-list-of-versions ( + the spec: https://maven.apache.org/pom.html#Version_Order_Specification )

**Comment by svermeulen** [comment]
From my reading of those links, it sounds like maven orders `-SNAPSHOT` versions immediately before the version without a qualifier (eg. `1.0.0`), and after alpha and beta versions.
