### ISSUE TITLE
Kotlin DSL DependencyConstraintHandler lacking overloads and maybe @DslMarker

### ISSUE THREAD

**Issue by jeremy-im** [gradle/gradle#11773]
This snippet tries to create dependencies when it should create constraints:
```kotlin
dependencies {
    constraints {
        api(group = "somegroup", name = "artifact", version = "version")
    }
}
```

### Expected Behavior

Maybe `@DslMarker` should be attached to the `constraints` so the outer scope `dependencies` DSL functions are not available from within the nested scope?

An overload `DependencyConstraintHandler.$kotlinIdentifier(group:String,...)` should be generated from `AcessorFragments` that builds a `mapOf("group" to group, ...)` to pass as the dependency notation.

### Current Behavior

The calls to `api(...)` or `runtime(...)` match the signature of the external functions on `DependencyHandler` generated at https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/AccessorFragments.kt#L167

The calls will fail at runtime with "Adding dependencies to platforms is not allowed by default"... Unless `javaPlatform.allowDependencies()` has been specified, then they will succeed but do something the user clearly did not intend.

### Context

Was trying to create a platform and was surprised when the constraints I wrote weren't constraints.

### Steps to Reproduce 

Very minimal project attached - run the `dependencies` task to see the surprising behavior:
[ConstraintsBug.zip](https://github.com/gradle/gradle/files/4010167/ConstraintsBug.zip)

### Your Environment

Build scan URL: https://gradle.com/s/gyf53nu6ybu4w

**Comment by melix** [comment]
See also #9249

**Comment by jeremy-im** [comment]
I did search, but somehow did not find that issue. My particular problem seems to match the one mentioned by https://github.com/NielsDoucet as a comment over there. Some of my bug description might help whoever gets to work on this bug - should we leave this issue as a separate thing? or maybe copy my text from above into a comment there?
