### ISSUE TITLE
Could not resolve spring-boot-devtools error

### ISSUE THREAD

**Issue by brucebrit** [gradle/gradle#11793]
gradle version - v6.1 RC 1
IDE: Spring Tool Suite 4.4.2

I am currently developing on a gradle-based multi-project. The root gradle.build is as shown below.
Upon triggering "synchronize with gradle project" in Spring Tool Suite IDE, i keep getting 
"Could not resolve: org.springframework.boot:spring-boot-devtools:2.2.2.RELEASE." error
Not sure if anyone had encountered this when using v6.1 RC 1 gradle?

```
plugins {
	id 'org.springframework.boot' version '2.2.2.RELEASE'
	id 'io.spring.dependency-management' version '1.0.8.RELEASE'
	id 'java'
}


allprojects {
  repositories {
	mavenCentral()
  }
  
}
subprojects{
	
	group = 'com.example'
	version = '0.0.1-SNAPSHOT'
	sourceCompatibility = '1.8'
	apply plugin: "java"
	apply plugin: "org.springframework.boot"
	apply plugin: "io.spring.dependency-management"
	configurations {
	  developmentOnly
		  runtimeClasspath {
		    extendsFrom developmentOnly
		  }
	}

	dependencies {
  		developmentOnly 'org.springframework.boot:spring-boot-devtools'
		implementation 'org.springframework.boot:spring-boot-starter-security'
		implementation 'org.springframework.boot:spring-boot-starter-web'
		
		testImplementation('org.springframework.boot:spring-boot-starter-test') {
			exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
		}
		testImplementation 'org.springframework.security:spring-security-test'
		
	}
	test {
		useJUnitPlatform()
	}
	
}

bootJar { enabled = false }
```

**Comment by jjohannes** [comment]
@brucebrit thanks for reporting. Does this work for you with Gradle 6.0.1?

I tried your sample build and was not able to reproduce the error.

**Comment by brucebrit** [comment]
> @brucebrit thanks for reporting. Does this work for you with Gradle 6.0.1?
> 
> I tried your sample build and was not able to reproduce the error.
Hi, thanks. I have not tried using Gradle 6.0.1. The reason why i using Gradle 6.1 RC 1 is because this version of gradle allows relocating .gradle folder from one machine to another machine without issue.  I will try it with Gradle 6.0.1 and update the result here.

Btw, I assume u are also using Gradle 6.1 RC 1 and not able to reproduce the error.

**Comment by brucebrit** [comment]
Hi,
I notice that the issue could lie with the Spring Tool Suite IDE, not the gradle itself. After I close and re-open the project in the IDE, this issue goes away. So conclusion, there is nothing wrong with Gradle 6.1 RC 1.
Sorry for the false alarm
