### ISSUE TITLE
Provide InputArtifactDependencies changes for incremental transforms

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#11794]
### Context
If there is a change in `InputArtifactDependencies` of a transform, currently Gradle runs the transform non-incrementally. This limits the number of scenarios where a transform can run incrementally (especially for the dexing transform in the Android Gradle plugin where the `InputArtifactDependencies` include library subprojects which can change frequently).

### Request
It would be great if Gradle could provide the changes in `InputArtifactDependencies` and run the transform incrementally when such changes occur.

**Comment by lptr** [comment]
cc @gradle/build-cache
