### ISSUE TITLE
Add API to Customize Version Sort Order

### ISSUE THREAD

**Issue by rwinch** [gradle/gradle#11809]
### Expected Behavior

I'd like a way to customize the order in which versions are sorted.

### Current Behavior

There is no way to customize the order in which versions are sorted.

### Context

There are times when projects have semantics that do not work with Gradle's definition of [version ordering](https://docs.gradle.org/current/userguide/single_versions.html#version_ordering).

For example, Spring and Project Reactor currently use bom version conventions that do not align with Gradle's versioning ordering. The ordering is such that releases ending with `-RELEASE` (i.e. `Dysprosium-RELEASE`) are considered before releases with `-SR<number>` (i.e. `Dysprosium-SR2`). This means that using Gradle's [version ranges](https://docs.gradle.org/current/userguide/single_versions.html) do not work.

For example, at the time of writing [reactor-bom](https://repo.maven.apache.org/maven2/io/projectreactor/reactor-bom/) has the following versions:

```
...
Dysprosium-RELEASE
Dysprosium-SR1
Dysprosium-SR2
```

If I have a build that looks like:

```groovy
plugins {
	id 'java-library'
}
repositories {
	mavenCentral()
}
dependencies {
	implementation platform("io.projectreactor:reactor-bom:latest.release")
	implementation "io.projectreactor:reactor-core"
}

```

Gradle considers `Dysprosium-RELEASE` to be more recent than `Dysprosium-SR2`.

```bash
gradle dependencies --configuration runtimeClasspath
...
runtimeClasspath - Runtime classpath of source set 'main'.
+--- io.projectreactor:reactor-bom:latest.release -> Dysprosium-RELEASE
|    +--- io.projectreactor:reactor-core:3.3.0.RELEASE (c)
|    \--- org.reactivestreams:reactive-streams:1.0.3 (c)
\--- io.projectreactor:reactor-core -> 3.3.0.RELEASE
     \--- org.reactivestreams:reactive-streams:1.0.3

(c) - dependency constraint
A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 485ms
1 actionable task: 1 executed
```

I'd like a way to change Gradle so that the `Dysprosium-SR2` version is resolved instead.

### Related Issues

It seems that there are [other users](https://github.com/gradle/gradle/issues/1872) that have been surprised by version ranges, so this feature could perhaps benefit them as well.

**Comment by rwinch** [comment]
This issue is still relevant. Please keep it open

**Comment by ljacomet** [comment]
This is very unlikely to be done any time soon.
Some changes were done in the 6.x cycle and became the default with Gradle 7 - see #13050

Given this, closing for now, acknowledging the use case described here is not supported.
