### ISSUE TITLE
missing org.jetbrains.kotlin.core...jar\bin'

### ISSUE THREAD

**Issue by ConradKrinock** [gradle/gradle#11808]
### Background/Intro:

We've run successfully:
    git clone https://github.com/gradle/gradle.git
    ./gradlew installAll -Pgradle_installPath=/usr/local/gradle-source-build 
Which has created all our jar files beautifully.

### Steps to Reproduce 
However this fails:
    gradle run

### Expected Behavior
- successful launch of gradle

### Current Behavior
Error message:
Project 'build.gradle.kts' is missing required library: 
'C:\Users\conra.p2\pool\plugins\org.jetbrains.kotlin.core_0.8.19.v20191112-1134.jar\bin'

### Current Behavior - continued
additional error messages in this attachment:
[ConradRunErrors.txt](https://github.com/gradle/gradle/files/4026982/ConradRunErrors.txt)

### Context
We're having challenges with some of our gradle builds and need to step thru them with a debugger and need HELP !!!!

### Related Issues
https://github.com/Kotlin/kotlin-frontend-plugin/issues/25
https://github.com/Kotlin/kotlin-frontend-plugin/issues/143

Thanks/RSVP,

Conrad J Krinock -- 775-450-1202
Cyber Security Architect

**Comment by big-guy** [comment]
It looks like after building Gradle you're trying to run the build with a different, older version of Gradle.   ValidatePlugins was added in Gradle 6.0, so you would need at least that version to run the Gradle build.

Without building Gradle itself, you should be able to attach a debugger to the running gradle process for your build by passing `-Dorg.gradle.debug=true` on the command-line.  That tells Gradle to open port 5005 for a Java debugger to attach.  You should be able to attach to the Gradle daemon and set break points in your plugin code.

**Comment by ConradKrinock** [comment]
RESOLVED -- Thanks Sterling !!! -- although now we're getting a different error -- we'll submit another Issue.
