### ISSUE TITLE
Build actions can't handle spaces in the classpath

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1180]
Our classpath serialization code seems unable to handle spaces in classpath urls. This breaks TAPI build actions if their classpath is located in such a folder. An example is Eclipse Buildship installations on Windows.

See https://discuss.gradle.org/t/buildship-2-0-doesnt-allow-to-import-projects/21118

**Comment by oehme** [comment]
This is breaking many Buildship 2.0 installations on Windows, scheduling for 3.4.

**Comment by donat** [comment]
I was able to reproduce the problem and provided an initial fix for the problem on a branch: https://github.com/gradle/gradle/tree/dc-faulty-classloader
@oehme Please have a look.

**Comment by adammurdoch** [comment]
We should understand why our existing coverage did not catch this, as there's intentionally whitespace in the test directories for exactly this kind of problem.

**Comment by oehme** [comment]
@adammurdoch The spaces are only in the directory of the project under test. The tapi jars are in the gradle build folder which does not have spaces.

**Comment by donat** [comment]
I've created a pull request for the `release` branch with the fix.

**Comment by adammurdoch** [comment]
I don't think we should close this without some integration test coverage.

**Comment by donat** [comment]
I've added an [integration test](https://github.com/gradle/gradle/commit/3074ad67f43f12c4e727a459e00718edbf8f53d2). @oehme would you mind having a look?

**Comment by oehme** [comment]
Lgtm
