### ISSUE TITLE
Use a task to create the Jar manifest

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11818]
We currently use a `GeneratedSingletonFileTree` which creates the manifest file on demand for the `Jar` task. Same for the `Ear` task and the deployment descriptor. See [this code](https://github.com/gradle/gradle/blob/f933c22721a3e65ca8fc172874b84b0f4e7d2752/subprojects/platform-jvm/src/main/java/org/gradle/jvm/tasks/Jar.java#L59-L79) in the `Jar` task.

It would be much simpler if the would be a `Manifest` task which can be configured, declares some inputs and then produces the manifest file as an output. This would remove quite some complexity from the code base and make it easier to support use-cases such as OSGi or complex manifest entries which need to do some actual work.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
Using `GeneratedSingletonFileTree` also seems to cause a problem with instant execution: changes to the manifest are not picked up, since the constructor of the `Jar` task not called when run with instant execution. So the `metaInf` `CopySpec` is serizalized into the instant execution cache. On serialization, the `CopySpec` is resolved, which causes writing the manifest file with whatever entry it had on the first run. On subsequent run, only the location of the manifest is loaded from the instant execution cache when deserializing the `Jar` task, so the (re-)creation of the manifest isn’t triggered anymore, since there isn’t a `GeneratedSingletonFileTree` which would take care of it.

**Comment by lptr** [comment]
The instant execution team wants to approach the underlying problem differently.
