### ISSUE TITLE
Gradle doesn't want to pull a specific dependency from a repo it already pulls other dependencies

### ISSUE THREAD

**Issue by MrIvanPlays** [gradle/gradle#11814]
### Expected Behavior
Gradle pull the dependency properly

### Current Behavior
Gradle doesn't pull the dependency from the maven repository; instead, pulling the dependency from a local cache which is outdated.

### Context
Discord bot. The specific dependency it doesn't want to pull is a command manager for a discord bot. 

### Steps to Reproduce 
Try pulling dependency `com.mrivanplays:JDCF:1.0.4-SNAPSHOT` from maven repository https://repo.mrivanplays.com/repository/ivan/

See it doesn't work. 

### Your Environment
IntelliJ IDEA 2019.3 Ultimate. 

[This is](https://bin.mrivanplays.com/Qfj3S8vm1QM) the build.gradle I use to deploy the dependency I talk about if it has something to do with the issue.

**Comment by ljacomet** [comment]
The most likely explanation is that another repository, declared first, provides that version as well with an outdated version.

Can you please add information on which repositories are declared in the build that pulls the dependency? If it contains `mavenLocal()`, please have a look at [this mention](https://docs.gradle.org/6.0.1/userguide/declaring_repositories.html#sec:case-for-maven-local) in the documentation.

Are you also aware of the caching done by Gradle and the default 24 hours cache time for SNAPSHOT? See [the documentation](https://docs.gradle.org/6.0.1/userguide/dynamic_versions.html#sec:controlling_dependency_caching_programmatically) on how to tweak that behavior.

**Comment by MrIvanPlays** [comment]
> The most likely explanation is that another repository, declared first, provides that version as well with an outdated version.
> 
> Can you please add information on which repositories are declared in the build that pulls the dependency? If it contains `mavenLocal()`, please have a look at [this mention](https://docs.gradle.org/6.0.1/userguide/declaring_repositories.html#sec:case-for-maven-local) in the documentation.
> 
> Are you also aware of the caching done by Gradle and the default 24 hours cache time for SNAPSHOT? See [the documentation](https://docs.gradle.org/6.0.1/userguide/dynamic_versions.html#sec:controlling_dependency_caching_programmatically) on how to tweak that behavior.

No I'm not aware of the caching, I'm new to gradle and I'm curious for every setting I do. I recently switched from maven. 

I've removed the `mavenLocal()` repository but it still doesn't pull it. The repository from where it should pull this dependency is [this](https://repo.mrivanplays.com/repository/ivan/) as mentioned in my initial post on this issue. I'll try applying that setting you told me about the caching. Ill update as soon as I receive any news

**Comment by MrIvanPlays** [comment]
The settings suggested fixed everything! Thanks
