### ISSUE TITLE
Explore using kevents for file system watching in macOS

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11812]
We have some issues with the current way file system changes are tracked on macOS, one being that when the entire watched folder is removed we get no notification. Supposedly using `kevents` offers a better way.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
Here is some comment on the drawback of `FSEvents`: https://github.com/notify-rs/notify/pull/144#issuecomment-427560683

**Comment by lptr** [comment]
Reading material: https://developer.apple.com/library/archive/documentation/Darwin/Conceptual/FSEvents_ProgGuide/KernelQueues/KernelQueues.html

**Comment by lptr** [comment]
This is interesting:

> ### Choosing an Event Mechanism
> 
> File system events are intended to provide notification of changes with directory-level granularity. For most purposes, this is sufficient. In some cases, however, you may need to receive notifications with finer granularity. For example, you might need to monitor only changes made to a single file. For that purpose, the kernel queue (kqueue) notification system is more appropriate.
> 
> **If you are monitoring a large hierarchy of content, you should use file system events instead, however, because kernel queues are somewhat more complex than kernel events, and _can be more resource intensive because of the additional user-kernel communication involved._**

**Comment by lptr** [comment]
Looks like we'll be able to solve our issues with `FSEvents`, so let's not use `kevents`.
