### ISSUE TITLE
All deprecation messages should include a link to relevant documentation 

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#11828]
When Gradle emits a deprecation message, it should contain a link to the user manual that provides more context around the deprecation. 

In some cases, this can be somewhat generic (one method replaced by another one).  This documentation will most likely live in the upgrade guide, but that's not a strict rule.  e.g., if one behavior is being replaced by another similar behavior, it might make sense to link to the new behavior's documentation.

### Expected Behavior
All deprecation warnings have relevant documentation links.

### Current Behavior
It's up to the writer of the deprecation to add this link. 

I think we should also consider including this link as a separate thing that can be captured by build scans.

**Comment by rieske** [comment]
We have two cases remaining without documentation links:
- [Build invocation deprecations](https://github.com/gradle/gradle/blob/d4052eb02ada08cad9de84d936b60234692b9241/subprojects/core-api/src/main/java/org/gradle/internal/deprecation/LoggingDeprecatable.java#L39) - currently there are no deprecations using this path.
- [Extending JavaCompile task](https://github.com/gradle/gradle/blob/d4052eb02ada08cad9de84d936b60234692b9241/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L137-L150)

**Comment by big-guy** [comment]
This is good enough for 6.2
