### ISSUE TITLE
kotlin-dsl.gradle.kts error: Unresolved reference: systemProperty

### ISSUE THREAD

**Issue by ConradKrinock** [gradle/gradle#11826]
### Background/Intro:
We've run successfully:
git clone https://github.com/gradle/gradle.git
./gradlew installAll -Pgradle_installPath=/usr/local/gradle-source-build
Which has created all our jar files beautifully.

### Steps to Reproduce
However this fails:
gradle run

### Expected Behavior
- successful launch of gradle

### Current Behavior
- error: Unresolved reference: systemProperty
error file:
[ConradRunErrors.txt](https://github.com/gradle/gradle/files/4032728/ConradRunErrors.txt)

### Context
We're having challenges with some of our gradle builds and need to step thru them with a debugger (using -Dorg.gradle.debug=true) and need HELP !!!!

Thanks/RSVP,

Conrad J Krinock -- 775-450-1202
Cyber Security Architect

**Comment by big-guy** [comment]
Hi @ConradKrinock,

This looks like the same kind of problem I described in https://github.com/gradle/gradle/issues/11808#issuecomment-571448529

The gradle/gradle build sometimes uses features that are only available in nightly releases of the next version of Gradle. These are methods that were introduced in 6.1 (which hasn't seen a final release). You're going to keep running into these problems by trying to use a different version of Gradle to build Gradle than what's expected.

It seems like you might be building Gradle and then trying to run that just built version of Gradle to execute `gradle run` in the gradle/gradle project. This isn't going to do anything useful (the Gradle build doesn't have a "run" task).

If you just want to attach a debugger to your project's build, you _do not_ need to build Gradle from source.  Please see https://docs.gradle.org/current/userguide/troubleshooting.html#attaching_a_debugger_to_your_build

HTH.
