### ISSUE TITLE
Improving Gradle error messages

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#11827]
When encountering an error (or warning), Gradle should produce a _help_ message, not an _error_ message.

This is inspired by some of the recent examples of improving messages emitted by tools by [other ecosystems](https://elm-lang.org/news/compiler-errors-for-humans).

**Comment by vlsi** [comment]
Do you think https://github.com/gradle/gradle/issues/11224 is relevant?

I often find that `TaskExecutionException: Execution failed for task ':testingBase:integTest'.` is not very helpful.
It is often printed side by side with the name of the failing task, so it looks like `Execution failed for task` adds nothing for humans.

**Comment by jjohannes** [comment]
This is not used to track work anymore. For improving a certain message, please open an individual issue.
