### ISSUE TITLE
Use same infrastructure for VFS retention and continuous build

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11834]
We are now detecting changes on the file system in two different ways. Consolidate this.

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
Are we going to stop supporting continuous mode for platforms unsupported by our own native file watching, or are we going to add some proxy for the JDK's polling perhaps?

**Comment by wolfs** [comment]
We could keep the JDK watcher backend around. I am also fine with dropping support for continuous build on platforms not supported by our native file watching.

**Comment by lptr** [comment]
See thread about problematic timeouts wrt continuous mode (especially macOS): https://gradle.slack.com/archives/C0WTFHWT1/p1583943879064600

We need to update these. Searching for `\b2000\b` in the codebase turns them up usually.

**Comment by wolfs** [comment]
Currently, most of the continuous build integration tests don't work on Java > 8 on macOS, since we don't set `HIGH_FREQUENCY` on the JDK watchers. See ☝️ .

**Comment by wolfs** [comment]
`ChangesDuringBuildContinuousIntegrationTest` should be changed so it actually checks if the detected changes are picked up by the tasks which are executed.

**Comment by wolfs** [comment]
Using the native infrastructure for continuous build will also fix https://github.com/gradle/gradle/issues/3427.

**Comment by graemerocher** [comment]
Could this be prioritized for 6.6? continuous build is a great feature but can be slow on Mac

**Comment by graemerocher** [comment]
Any news?

**Comment by lptr** [comment]
We are also frustrated with this issue, and will address it in the foreseeable future. It's non-trivial, though. Give us a bit more time.

**Comment by avanwieringen-sensus** [comment]
Any progress on this issue? I know it is a difficult one, but  just wondering :-)

**Comment by lptr** [comment]
Not for 7.0, but keep watching this space! :)
