### ISSUE TITLE
Gather statistics for VFS performance

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11838]
We don't currently have a good understanding of how much the VFS can help avoid touching the file system, or how much overhead maintaining adds to the build time. We need to capture this information via build operations.

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
Here's my plan:

Put usage-specific types close to the actual implementation (like `CachedFileHasherStatisticsCollector` next to `CachedFileHasher`, and `FileSystemStatisticsCollector` next to `FileSystem`).

And then from `FileSystemWatchingBuildActionRunner` triggers each of these collectors on build finish to print their reports and reset themselves for the next build.

The individual collectors are dumb and each can only produce a number of string messages that we put on the `warn` log if `org.gradle.vfs.verbose` is enabled.

I’d like to merge the existing watching VFS logging (`"Virtual file system retained information about {} files, {} directories and {} missing files since last build"` etc.) into this system.

**Comment by wolfs** [comment]
I think the plan is sound. If you trigger the logging in `FileSystemWatchingBuildActionRunner`, then the log will be captured in the build logs.
I think we should create a build operation containing the statistics, so we can capture it and add some custom values to our build scans without the need to parse some log.
I am currently mostly interested in the `FileSystemAccess` statistics, so maybe we should start with that one.
