### ISSUE TITLE
Transforms can't use task outputs as an input

### ISSUE THREAD

**Issue by nallar** [gradle/gradle#11847]
### Expected Behavior
Using a subproject task's output as the input to an artifact transform should not crash. It should also add a dependency so the transform runs after the task.

### Current Behavior
```
* What went wrong:
Execution failed for task ':compileTestJava'.
> Cannot isolate parameters org.minimallycorrect.mixinplugin.transform.MixinTransform$Parameters_Decorated@ab11013 of artifact transform MixinTransform
   > Could not isolate value: [org.minimallycorrect.mixinplugin.transform.MixinTransform$Parameters_Decorated@ab11013] of type: [class org.minimallycorrect.mixinplugin.transform.MixinTransform$Parameters_Decorated]
      > Could not serialize value of type 'org.minimallycorrect.mixinplugin.ApplyMixins'
```
Crashes.
Using a task's `getOutputs()` as part of the inputs to a transform isn't possible as it can't be serialized.

### Context
A transform depends on the output of a subproject's build to run. This transform's inputs are set using that task's outputs.  
This transform is applying patches to a dependency from mixins in the subproject.

Further discussion on context here: https://github.com/MinimallyCorrect/Mixin/issues/6

### Steps to Reproduce 
This commit has an example of the problem. `gradlew check` demonstrates the issue.
https://github.com/MinimallyCorrect/Mixin/tree/8daf68287cfcd86f954d0de04ad4f5ff37234aab/

It currently has a workaround using `static`! state, so doesn't fail. Remove that by unmarking this field https://github.com/MinimallyCorrect/Mixin/blob/8daf68287cfcd86f954d0de04ad4f5ff37234aab/gradle-plugin/src/main/java/org/minimallycorrect/mixinplugin/ApplyMixins.java#L55 as transient and it will crash. 

### Your Environment

Environment: A gradle plugin test, on JDK 13 or 8. Gradle 6.0.1
Build scan URL: https://scans.gradle.com/s/fm4lz3ji7x4ks

**Comment by wolfs** [comment]
Thank you for reporting.

The short answer to your question: transforms can already use task outputs as inputs as shown by this test: https://github.com/gradle/gradle/blob/cc392c15aad43287b8a9572c2172c30d8c014fca/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformWithFileInputsIntegrationTest.groovy#L175-L204

For your use-case:

You need to use `@Nested` on inputs which are also annotated with input annotations. So this should work:
```
public interface Parameters extends TransformParameters { 
 	@Nested 
 	Map<String, ApplyMixins> getPerDependencyApplyMixins();
}
```

I would suggest using a `MapProperty` instead of a mutable `Map` property.

As a note for `ApplyMixins`: You shouldn't store the configuration in the object. Use a property or `FileCollection` which does the mapping instead. A file collection is also lazy, so it won't be resolved when registering the transform.

Regarding using the outputs of the `Jar` task: better use `Jar.archiveFile`. This is a `RegularFileProperty`, only one file, and will also add the task dependency.

In general, there shouldn't be any transient fields on your parameter object. Use lazy types like `Property`, `RegularFileProperty` and `FileCollection` instead.

**Comment by nallar** [comment]
Thanks for the help @wolfs!

> You need to use `@Nested`

Unfortunately this doesn't make any difference, it still crashes with the same NotSerializableException.

```
Caused by: org.gradle.internal.operations.BuildOperationQueueFailure: There was a failure while populating the build operation queue: Cannot isolate parameters org.minimallycorrect.mixinplugin.transform.MixinTransform$Parameters_Decorated@72d866a0 of artifact transform MixinTransform
...
Caused by: java.io.NotSerializableException: org.gradle.api.internal.tasks.DefaultTaskOutputs$TaskOutputUnionFileCollection
	at org.gradle.internal.snapshot.impl.DefaultValueSnapshotter.serialize(DefaultValueSnapshotter.java:171)
```

> In general, there shouldn't be any transient fields on your parameter object. Use lazy types like Property, RegularFileProperty and FileCollection instead.

Are transient `@Internal` caches created from values of other fields still okay?

> Regarding using the outputs of the Jar task: better use Jar.archiveFile. This is a RegularFileProperty, only one file, and will also add the task dependency.

It also gets used with `sourceSet.getAllJava().getSourceDirectories()` in another place, so hope that makes sense to keep using the `FileCollection`?

> You shouldn't store the configuration in the object. Use a property or FileCollection which does the mapping instead

Is there an example of doing this? We care about the dependency's ID's. It could just be a list of dependencies, but there's no way to make a detached configuration at this point to do the resolution so it seemed the only way to get it to work was to pass the configuration through.

**Comment by nallar** [comment]
@wolfs 

Making a single `FileCollection` with `@Classpath` works. A `@Nested` with something containing a `FileCollection` with `@Classpath` causes the `java.io.NotSerializableException`.

**Comment by wolfs** [comment]
How do you create `ApplyMixins`? You need to create it using `ObjectFactory` and the same rules as for the parameters apply. So you probably should declare an abstract getter for the `FileCollection` and then use `fileCollection.from(...)` to set it to an actual value.

**Comment by nallar** [comment]
@wolfs 

🎉 

Finally kinda working:

![image](https://user-images.githubusercontent.com/782440/72104507-7b13f980-3323-11ea-9d9b-da7900e4b797.png)

Older gradle versions' `ObjectFactory` can't create the abstract get methods, but if you use your own fields you still get the serialize exception. For backwards compatibility this means shipping an extra class which has the properties, and deciding which one to use based on gradle version.

Compatibility back to 4.2 is right out as you can't use properties.

The errors gradle produces here are extremely unclear, without your messages it would have been very difficult to get this working.  
Still don't really understand why it works now. What's the difference between gradle making getters for the properties and properties made with `ObjectFactory.property`? Why don't the latter work?!

**Comment by wolfs** [comment]
The difference is that, when Gradle generates the fields, it knows how to create copies of the parameters object to isolate it when running the transforms in parallel. When you create the getter, Gradle currently doesn't know how to create copies of your parameters object and then fails.
