### ISSUE TITLE
Enabling java-test-fixture plugin breaks eclipse junit runner

### ISSUE THREAD

**Issue by tomqwpl** [gradle/gradle#11845]
### Expected Behavior
I should be able to run junit tests using the "run as junit" test runner (not "run as gradle unit test") from within eclipse, despite having enabled the "java-test-fixture" gradle plugin

### Current Behavior
I can't.
The wrong classpath is generated when running the junit test.
If I use the "show command line" option on the run configuration in eclipse, and then look at the classpath file, I see entries like:

    <project>/bin/test
    <project>/bin/default

When things work (when there's no java-test-fixture plugin enabled) I get classpath entries like:

    <project>/bin/test
    <project>/bin/main

In the .classpath file, I get the following when it doesn't work:#

	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main"/>
		</attributes>
	</classpathentry>

vs

	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>

(compare values of "gradle_used_by_scope")

### Context
Run junit tests in eclipse.

### Steps to Reproduce 
Simply add
 apply plugin: 'java-test-fixtures'
to a working gradle project. Refresh eclipse, do "Refresh Gradle Project". Try and run a junit test.

### Your Environment
Windows eclipse 2019-06

**Comment by tomqwpl** [comment]
I can apparently work round this bug by adding the following to my build.gradle:

    subprojects {
        apply plugin: 'eclipse'
	eclipse.classpath.file.whenMerged {
		def main = entries.find { it.path == 'src/main/java' }
		if (main) {
			main.entryAttributes['gradle_used_by_scope'] = 'main,test'
 	    }
	}	
    }

**Comment by ljacomet** [comment]
@donat Coud you have a look? Any chance we can do something in buildship for that?

**Comment by donat** [comment]
@tomqwpl What Gradle and Buildship version do you use? This problem might be already fixed in a more recent version.

**Comment by tomqwpl** [comment]
So I tried various versions and got different results with different ones.
eclipse 2019-12 is fundamentally broken for me (https://bugs.eclipse.org/bugs/show_bug.cgi?id=558495) the latest I can use is 2019-9. 
I *think* that with that this version is resolved, but I get another, possibly related, issue: https://github.com/eclipse/buildship/issues/966
With 2019-9 I seem to be using test fixtures OK
