### ISSUE TITLE
Support symlinks with VFS retention

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11851]
---
cc: @gradle/build-cache

**Comment by lptr** [comment]
This would mainly mean that we'd need to canonicalize paths all the time, something we stopped doing as a performance improvement a while back.

**Comment by wolfs** [comment]
I think it is a little bit more complicated than that. When a directory contains a symlink, then it isn't enough to watch the directory for changes but we also need to watch the parent directory of the target of the symlink.

Currently, we also only normalize the roots of whatever we are snapshotting, so canonicalizing those also wouldn't be enough. I think as a start it would be better to detect the symlinks and drop the VFS entries for the symlinks at the end of the build.

**Comment by wolfs** [comment]
As a first step, we could detect when we try to watch directories which have a different canonical path than the requested path and then disable VFS retention.

For a hierarchical watcher, we need to check that all the subdirectories we care about (aka which we want to watch), do not contain symlinks. For a non-hierarchical watcher we need to make sure that all the directories we pass to the watcher are not symlinks. We probably also need to check that no files in the watched directories are symlinks.

The detection can happen while we snapshot a directory or a file, since there we already know if a directory/file is a symlink.

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/13031.
