### ISSUE TITLE
Gradle doesn't report abbreviated task name as ambiguous when task name has numbers

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1185]
Given this build file:
```
task unique1()
task uniqueA()
```

Running with this command-line should produce an ambiguous task selection error between unique1 and uniqueA.
```
gradle unique
```

Instead, we select unique1.   Tested with 1.0, 2.0, 2.2.1 and master (2.4 nightly). 

Migrated from: https://issues.gradle.org/browse/GRADLE-3258

**Comment by martinda** [comment]
Hello stale bot :-) The problem still exists with Gradle 6.5.

**Comment by ov7a** [comment]
This is still an issue in gradle 8.10
