### ISSUE TITLE
Let Kotlin script compilation use execution engine

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11855]
The Kotlin script compilation caching currently uses its own infrastructure for storing stuff in the build cache. On one hand this leads to redundant code that we need to maintain. On the other it means we are missing on existing and future features of the execution engine (like capturing build operations for snapshotting, using the VFS to avoid touching the file system when possible etc.).

We should fix this by migrating Kotlin script compilation to the execution engine.

Doing this will also make it easier to use the execution engine for Groovy script compilation in the future. Doing so in turn would allow using the remote cache (among other things).

---
cc: @gradle/build-cache, @eskatos

**Comment by lptr** [comment]
After discussing with @eskatos today it seems that doing this will be more-or-less straightforward. The process of Kotlin compilation actually consists of the following steps:

1. use the `kotlinc` lexer to split up the script into classpath-altering blocks (`plugins {}`, `pluginManagement {}` and `buildscript {}`) and its body,
2. generate accessors (source code + byte code) for all the classpath-altering blocks, if any,
3. compile the classpath-altering blocks, if any,
4. generate accessors for the script body,
5. compile the script body.

Step 1 is not cached, while steps 2-5 are all stored in the local and remote cache. There are no non-relocatable outputs in any of the steps.

The reason for the many steps is the Kotlin compiler is slow, and thus reusing compiled accessors is a priority. Maybe this will not be the case after Kotlin 1.4.1 delivers some major performance improvements around the compiler. One of the advantages of moving to the execution engine is that we'll be able to use standard tools (e.g. the Gradle Profiler) to confirm if this is indeed the case.

**Comment by lptr** [comment]
We will probably need two new `UnitOfWork` types, one for the accessor generation, and one for the compilation, and will need to create zero, one or two instances of each, depending on the result of the lexing.

**Comment by bamboo** [comment]
Step 1 is cached in the emitted `Program` class structure. We only ever lex the script again when the file changes.

**Comment by lptr** [comment]
Once https://github.com/gradle/gradle/pull/12072 is merged we can move on to executing the actual compilation on the execution engine.

**Comment by lptr** [comment]
We need to add a test for the Kotlin DSL workspace provider cleanup.

**Comment by lptr** [comment]
Let's take care of the cache cleanup in https://github.com/gradle/gradle/issues/13999.
