### ISSUE TITLE
Timeout waiting to lock * in Gradle 5.6.3

### ISSUE THREAD

**Issue by Jocce-Nilsson** [gradle/gradle#11861]
We have seen problems in our CI environment recently where Gradle processes stop due to "Timeout waiting to lock *". It happens a few times a week, enough to be a disturbance.

/local/.gradle/daemon/5.6.3/daemon-4219.out.log:      Timeout waiting to lock Java compile cache (/local/.gradle/caches/5.6.3/javaCompile). It is currently in use by another Gradle instance.
/local/.gradle/daemon/5.6.3/daemon-4219.out.log-  Owner PID: unknown
/local/.gradle/daemon/5.6.3/daemon-4219.out.log-  Our PID: 4219
/local/.gradle/daemon/5.6.3/daemon-4219.out.log-  Owner Operation: unknown

/local/.gradle/daemon/5.6.3/daemon-8299.out.log:> Timeout waiting to lock file hash cache (/local/.gradle/caches/5.6.3/fileHashes). It is currently in use by another Gradle instance.
/local/.gradle/daemon/5.6.3/daemon-8299.out.log-  Owner PID: 8867
/local/.gradle/daemon/5.6.3/daemon-8299.out.log-  Our PID: 8299
/local/.gradle/daemon/5.6.3/daemon-8299.out.log-  Owner Operation: 

/local/.gradle/daemon/5.6.3/daemon-8466.out.log:      Timeout waiting to lock Java compile cache (/local/.gradle/caches/5.6.3/javaCompile). It is currently in use by another Gradle instance.
/local/.gradle/daemon/5.6.3/daemon-8466.out.log-  Owner PID: 10270
/local/.gradle/daemon/5.6.3/daemon-8466.out.log-  Our PID: 8466
/local/.gradle/daemon/5.6.3/daemon-8466.out.log-  Owner Operation: 

/local/.gradle/daemon/5.6.3/daemon-8491.out.log:> Timeout waiting to lock file hash cache (/local/.gradle/caches/5.6.3/fileHashes). It is currently in use by another Gradle instance.
/local/.gradle/daemon/5.6.3/daemon-8491.out.log-  Owner PID: 8867
/local/.gradle/daemon/5.6.3/daemon-8491.out.log-  Our PID: 8491
/local/.gradle/daemon/5.6.3/daemon-8491.out.log-  Owner Operation: 

Is there a workaround or a fix for this? As I understand Gradle internals, there should be an inter-process communication between instances of Gradle daemons to avoid this situation. But I cannot see any warnings or logs regarding failing communication, which would be an obvious reason. 
I have checked iptables and there are no rules preventing the communication as far as I can see. 

[daemon-8867.out-cleaned.log](https://github.com/gradle/gradle/files/4044388/daemon-8867.out-cleaned.log)
[daemon-8299.out-cleaned.log](https://github.com/gradle/gradle/files/4044389/daemon-8299.out-cleaned.log)

**Comment by big-guy** [comment]
Hey @Jocce-Nilsson 

Were these builds running at the same time as others for the same project? It looks like 8299 and 8867 were running at the same time, but I can't tell if they were building the same project.

You're right that there's an inter-process communication channel for these locks.  There are a couple of common problems:
- Sharing a network mounted filesystem for Gradle User Home across multiple machines (the processes can't see each other).  I don't think that's what you're doing.
- Sharing a Gradle user home directory across Docker containers.  This is basically the same as the network file system because the daemons running in separate containers can't see each other.

I don't think there's anything special we log up until the timeout.

**Comment by Jocce-Nilsson** [comment]
Yes, there were around 7-8 parallel builds at the time, all building the same project but in different workspaces. All builds were on the same server, and no containers were involved.

**Comment by big-guy** [comment]
Thanks @Jocce-Nilsson 

If I understand you correctly, you have a project `foo` and you have separate copies of it in different directories?  And then you're running different tasks in each of those directories where you sometimes see timeouts?

Or do you have a single copy of project `foo` in a directory and you're running different tasks on that one copy at the same time?  Do those tasks overlap in any way?  e.g., if you have tasks A, B and C and A&B depend on C, if you try running A and B in separate Gradle invocations, C would be an "overlap".

**Comment by Jocce-Nilsson** [comment]
@big-guy 
Separate copies, in different directories. In order to run all 150+ integration test suites in parallel for that repository, since each of the suites takes up to 30 minutes to complete.

**Comment by Jocce-Nilsson** [comment]
@big-guy 
We have seen this error a few more times now. Once or twice a week it happens. But actually only on 5.6.3. 

Versions we use: 
4.10.2
4.10.3
4.2.1
5.6.2
5.6.3
6.0
6.1.1

**Comment by aolenev** [comment]
Confirm. I have the same issue even without parallel builds. It looks like previous build doesn't release lock

**Comment by Jocce-Nilsson** [comment]
@big-guy 
The problem still remains. Any ideas or progress in solving it?
I have some additional info that may be useful for reproducing. 
We are using the no-daemon option, which spawns one background process. And from what I see, one of the compilation tasks of that background job is really big. In total, the compile job can take up to 10 minutes if the server is under load.

**Comment by prashantkalkar** [comment]
We are also facing the same issue. In my case, gradle is running inside a container. I think this issue should be reopened.
