### ISSUE TITLE
Gradle Wrapper ignores ~/.gradle/gradle.properties proxy settings 

### ISSUE THREAD

**Issue by ajkettun** [gradle/gradle#11864]
Gradle Wrapper ignores ~/.gradle/gradle.properties proxy settings (for downloading Gradle distribution).

GradleWrapperMain line 69:

`
private static void addSystemProperties(File gradleHome, File rootDir) {
        System.getProperties().putAll(SystemPropertiesHandler.getSystemProperties(new File(gradleHome, "gradle.properties")));
        System.getProperties().putAll(SystemPropertiesHandler.getSystemProperties(new File(rootDir, "gradle.properties")));
    }
`

Project settings override anything else (including command line arguments). We would like to keep our personal proxy-settings in  ~/.gradle/gradle.properties and configure proxy-settings required in CI environment in the project gradle.properties.

Problem can be easily circumvented by taking proxy settings away from project gradle.properties and setting them in CI scripts but wrapper behavior still seems inconsistent with rest of the Gradle.

**Comment by sschuberth** [comment]
Sounds like a duplicate of https://github.com/gradle/gradle/issues/985.
