### ISSUE TITLE
Task declaring mustRunAfter is not taken under consideration with finalizer definition

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1186]
This issue was originally report via [GRADLE-3389](https://issues.gradle.org/browse/GRADLE-3389). Given the following build script:

```
task A

task B {
    mustRunAfter "A"
    finalizedBy "C"
}

task C {
    dependsOn "A"
}
```

### Expected Behavior

The task `B` should be run after `A. The expected output is the following:

```
:A UP-TO-DATE
:B UP-TO-DATE
:C UP-TO-DATE
```

### Current Behavior

The actual output is the following:

```
:B UP-TO-DATE
:A UP-TO-DATE
:C UP-TO-DATE
```

### Steps to Reproduce (for bugs)

See code example above.

**Comment by MrCeeJ** [comment]
Any update on this? It looks similar to a bug I am seeing..

**Comment by netvl** [comment]
This is very much still an issue. Oh well, useful stale bot again...
