### ISSUE TITLE
settingsEvaluated block in init.gradle.kts doesn't work as documented

### ISSUE THREAD

**Issue by karlsabo** [gradle/gradle#11885]
### Expected Behavior

Per the [documentation](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management) the following code in an init.gradle.kts file should work:
```kotlin
settingsEvaluated { settings ->
    settings.pluginManagement {
        plugins {
        }
        resolutionStrategy {
        }
        repositories {
        }
    }
}
```

### Current Behavior

A compile error occurs:
```
* What went wrong:
Script compilation errors:

  Line 17: settingsEvaluated { settings ->
                             ^ Type mismatch: inferred type is (Nothing) -> Unit but Closure<(raw) Any!>! was expected
```

### Context

Trying to use Kotlin in a home directory init script.

### Steps to Reproduce 

Create an [init.gradle.kts script](https://docs.gradle.org/current/userguide/init_scripts.html) and use the [documented settingsEvaluated block](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management). When you try to run a Gradle command you will get an error.

### Workaround
```kotlin
settingsEvaluated(Action<Settings> {
    fun apply(settings: Settings) {
        settings.pluginManagement {
            plugins {
            }
            resolutionStrategy {
            }
            repositories {
            }
        }
    }
})
```

### Potential fix
Either update the documentation [src/snippets/plugins/pluginManagement/kotlin/init.gradle.kts](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/snippets/plugins/pluginManagement/kotlin/init.gradle.kts) or add Kotlin DSL functions.

I think the following would work:
[kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt](https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt)
```kotlin
abstract class KotlinInitScript(
    private val host: KotlinScriptHost<Gradle>
) : InitScriptApi(host.target) /* TODO:kotlin-dsl configure implicit receiver */ {

...
    open fun settingsEvaulated(action: Action<in Settings>) =
        host.target.settingsEvaluated(action)

    open fun settingsEvaulated(closure: Closure<Any>) =
        host.target.settingsEvaluated(closure)
}
```

But I haven't tested that. Contributor guide said to make an issue first to start the discussion.

### Your Environment

Build scan URL: N/A (not available because of script compile error)
```
C:\Users\ksabo\git\gradle>.\gradlew --version

------------------------------------------------------------
Gradle 6.2-20200107194018+0000
------------------------------------------------------------

Build time:   2020-01-07 19:40:18 UTC
Revision:     755719c1f8f3c54d2d4b4d15b835860f86c5f148

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.5 (AdoptOpenJDK 11.0.5+10)
OS:           Windows 10 10.0 amd64

C:\Users\ksabo\git\gradle>
```

**Comment by bamboo** [comment]
HI @karlsabo, the documentation is indeed wrong. In Gradle Kotlin DSL scripts, the Gradle type `Action<T>` is equivalent to the Kotlin function type `T.() -> Unit`, that is, a  [function type with a receiver](https://kotlinlang.org/docs/reference/lambdas.html#function-literals-with-receiver). 

Remove the `settings ->` parameter declaration and it should work:
```kotlin
settingsEvaluated {
    // `this` is `Settings` within this lambda
    pluginManagement {
        plugins {
        }
        resolutionStrategy {
        }
        repositories {
        }
    }
}
```
I hope that helps.

I'll take care of fixing the documentation and closing this issue when it is.
Thanks for the report!
