### ISSUE TITLE
Callback listeners that cause events to occur cause deadlocks with parallel execution

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1188]
We have a `TaskExecutionListener` that recalculates the hashes for inputs for a task: https://github.com/gradle/gradle/blob/master/gradle/taskCacheBuildScanUserData.gradle

This sometimes causes deadlocks between a `TaskExecutionListener` and `DependencyResolutionListener` when running with `--parallel`.  For now, we've disabled our listener when parallel execution is enabled.  In the long term, we're going to replace this listener with built-in functionality.

I haven't been able to reduce it down to a reproducible test.  The problem seems to be deep down in our listener manager infrastructure and we deadlock trying to handle listener callbacks.

**Comment by rkrisztian** [comment]
#2406 could be a similar bug.

**Comment by oehme** [comment]
@rkrisztian no, this is unrelated.
