### ISSUE TITLE
Keep watchers alive during build

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11901]
Keeping watchers alive during build is a requirement for some future features, like validating if tasks change their inputs during execution.

Doing this is also beneficial for build time in the "inner loop" use case, because we don't need to register / unregister watchers for every build.

We can implement this first by ignoring events during build and updating watchers at the end of the build.

Doing this requires a fully event-driven interface for all supported watchers (see #11813 for the Linux implementation).

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
I wrote down possible steps for implementing this: https://docs.google.com/document/d/15sJC1vDwTwOy5W4-jliNbWENkbvrT54mQJV13qLulWg/edit#heading=h.34w1wa8wko9o

**Comment by wolfs** [comment]
Closing in favor of https://github.com/gradle/gradle/issues/12437.
