### ISSUE TITLE
How to allow insecure protocol for variable in gradle.properties

### ISSUE THREAD

**Issue by lukavucko** [gradle/gradle#11905]
Hi,
how I can allow insecure protocol for variable in gradle.properties?
I have for example in gradle.properties:
mavenResolverUrl=http://www.example.com/
After executed build I see in deprecations on build scan this message:
Using insecure protocols with repositories has been deprecated.
I fixed for examples like it's written in documentation:
repositories {
    maven {
        url = "http://my-company.example"
        allowInsecureProtocol = true
    }
But I don't know how to do that on variable in gradle.properties or somewhere else in the code. For example in java class when I also have a variable which is value is some http link.

Thank you in advance
Luka

**Comment by big-guy** [comment]
If you're using the value from `gradle.properties` as your repository URL, setting `allowInsecureProtocol` for that repository is the right way to go.

> But I don't know how to do that on variable in gradle.properties or somewhere else in the code. For example in java class when I also have a variable which is value is some http link.

I'm not 100% sure what you mean here, but this deprecation only applies to Gradle and URLs that it uses.  If your application is using HTTP URLs, that won't trigger the deprecation warning.  There isn't a way to mark a property from `gradle.properties` as being a "safe" URL.  These are just key/value strings.

**Comment by lukavucko** [comment]
Yes, you are right, I did that and now it's working.

**Comment by AmrAbuelhamd** [comment]
now it's called allowInsecureProtocol
so your maven would be like this:
      maven {
            url "http://**************"
            allowInsecureProtocol = true
        }

**Comment by execptionerror** [comment]
[[Already Solved] Allow insecure protocols android Gradle](https://exerror.com/allow-insecure-protocols-android-gradle/)

**Comment by l3ender** [comment]
Sorry for the silly question, but how can the configuration be written on one line?

When I try this:
```
maven { url "http://myorg.example/repo"; allowInsecureProtocol = true }
```

I get the following error:
> Could not set unknown property 'allowInsecureProtocol' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

**Comment by ashank96** [comment]
> Sorry for the silly question, but how can the configuration be written on one line?
> 
> When I try this:
> 
> ```
> maven { url "http://myorg.example/repo"; allowInsecureProtocol = true }
> ```
> 
> I get the following error:
> 
> > Could not set unknown property 'allowInsecureProtocol' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

See if you have upgraded your gradlew version to 7.2

**Comment by chhavish** [comment]
I tried bot the ways and still cannot get gradle to build-
maven { url "http:/XXXXXXX/maven" setAllowInsecureProtocol(true) } and maven { url "http://XXXXX/maven" allowInsecureProtocol true }
error message-
Could not resolve all dependencies for configuration ':classpath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported.

**Comment by jokermonn** [comment]
but when `apply from: 'xxx.gradle'`, and there is a http maven in `xxx.gradle`, how to resolve it?

**Comment by Priyanka-src** [comment]
For me passing allowInsecureProtocol = true  is not working, 
Gradle version-7.3.2

**Comment by jjmgreen** [comment]
Gradle version 7.5, and it doesn't work for me.  Neither allowInsecureProtocol = true nor allowInsecureProtocol(true) work

**Comment by peterkelley519** [comment]
I switched it to use the following and it works ok in 7.x (where I had the assignment statement before)
`setAllowInsecureProtocol(true)`
>> some had posted this code, but left out _set..._

**Comment by Riane14** [comment]
Hey, i'm using gradle 7.5.1 and having this problem, i tried every thing setAllowInsecureProtocol(true) , allowInsecureProtocol = true and <application    allowInsecureProtocol ="true"> in  AndroidManifest.xml 
But still not working !! any idea ?

**Comment by sanjay-dreamcast** [comment]
maven {
            url "http://raw.github.com/saki4510t/libcommon/master/repository/"
            setAllowInsecureProtocol(true) 
        }


> Could not resolve all dependencies for configuration ':classpath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven3(http://raw.github.com/saki4510t/libcommon/master/repository/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.5/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 

Any solution??

**Comment by boxsnake** [comment]
For Java conventions, boolean property is mapped to `isXXX`, so you should use like:
```
maven {
   isAllowInsecureProtocol = true
}
```
for `*.gradle.kts` files.
