### ISSUE TITLE
Support polymorphism and collections with @Nested annotation

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#1190]
There are two often repeated issues with how `@Nested` works currently:

- it doesn't support collections – IIRC, we revert back automatically to using the serialized version of anything that is not understood by `@Nested`
- it doesn't support polymorphism – when you declare a field to be of type `MinimalJavadocOptions`, only the annotations on that type are processed by `@Nested`, ignoring anything declared in the actual runtime type of the value. Again, there's no warning to the user, and this leads to unexpected results.

We could rework this, and use the runtime type of the values instead of the declared type to walk the data. There are a few things to pay attention to:

- when validating the task type as part of the build (see `ValidateTaskProperties` task), we can only use the declared type information, so it won't be the same as the runtime validation
- we need to handle cyclic references
- processing annotated inputs needs to be moved from the `AnnotationProcessingTaskFactory` to `ValidatingTaskExecuter` (or a new executer before that).
- calling `getProperties()` before task execution won't return the values for annotated properties

**Comment by big-guy** [comment]
We may want to split the "handle collections" from the "handle runtime types/polymorphism" parts.  

Other things to keep in mind...
1) What's the names of properties that are in a collection? or is the property's value the collection?
   - If the property's value is a collection, then what kind of error do you get when the 3rd element in a list has a null value for a non-`@Optional` property?
2) Should we allow a `Map` property?

**Comment by lptr** [comment]
I think we currently consider the value of the property to be the (serialized form of the) collection, and we simply report that the value has changed (need to check the details, but I think this is what happens with `@Input` at least). To me the only logical way to improve the situation is to map collection indexes to sub-properties, like `elements.3.name` etc. Mapping `Map`s to sub-properties by key is also easy as long as the keys are Strings containing valid Java identifiers.

**Comment by adammurdoch** [comment]
I'd make the types we use to represent snapshots richer and polymorphic so they can deal with these use cases naturally, rather than trying to coerce every path through the graph into a string. Though we certainly could start with the use cases where we can do the coercion though.

**Comment by mark-vieira** [comment]
@lptr Hasn't this issue been effectively resolved? What's remaining to be done here?

**Comment by wolfs** [comment]
@mark-vieira You are right, we already support `Iterable`s and `Map` as well as polymorphism. Validation could still need some improvement, but that should be tracked separately.

Let's close this.
