### ISSUE TITLE
Copy tasks do not consider filter/eachFile/expansion properties in up-to-date checks

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#1191]
@lptr commented on [Tue Jul 12 2016](https://github.com/gradle/task-output-cache/issues/21)

Code review: [REVIEW-6089](https://code-review.gradle.org/cru/REVIEW-6089)

See JIRA issues:
- [GRADLE-1646](https://issues.gradle.org/browse/GRADLE-1646)
- [GRADLE-1276](https://issues.gradle.org/browse/GRADLE-1276)
- [GRADLE-1298](https://issues.gradle.org/browse/GRADLE-1298)

GitHub issues:

- https://github.com/gradle/gradle/issues/861
- https://github.com/gradle/gradle/issues/1015
- #4729

---

@lptr commented on [Tue Jul 12 2016](https://github.com/gradle/task-output-cache/issues/21#issuecomment-232010880)

Added tests in gradle/gradle@e42e1038fb759155c9f1eca0c1c7d168ce339a0a

---

@lptr commented on [Tue Jul 12 2016](https://github.com/gradle/task-output-cache/issues/21#issuecomment-232050113)

Discussion on Slack with @melix about deprecating the imperative methods on `CopySpec` like `filter(Closure)`: https://gradle.slack.com/archives/build-tool/p1468322257003567

---

@lptr commented on [Thu Jan 12 2017](https://github.com/gradle/task-output-cache/issues/21#issuecomment-272126602)

Since we don't want to cache archive or copy tasks, we are moving issues related to them to the main Gradle board. This issue is already reported on the main board (see description for links).

**Comment by huxi** [comment]
@lptr Consider adding my test in #861 regarding nested (for lack of a better word) expands, i.e. the `filesMatching '**/*.properties', { expand expandMap }` part.

**Comment by lptr** [comment]
@huxi do you think we should have them besides these? https://github.com/gradle/gradle/commit/e42e1038fb759155c9f1eca0c1c7d168ce339a0a

**Comment by huxi** [comment]
@lptr Yes.
I was able to fix the first of the two tests in #861 but that change wouldn't have affected the second test scenario where the `expand` was a parameter to `filesMatching`.

> The straight-forward idea of adding the line `getInputs().properties(properties);` to `AbstractCopyTask.expand(Map<String, ?> properties)` fixes the first but not the second test.

**Comment by rikoe** [comment]
Are there any plans to fix this issue, or a workaround I can use in the interim? How can I get my build to update the application.properties file if one of the input variables have changes?

**Comment by lptr** [comment]
As a workaround you can register the input variables via `task.inputs.property()`.

**Comment by rikoe** [comment]
Thank you @lptr.

So I have:
```
processResources {
	filesMatching('application.properties') {
		expand(project.properties)
	}
}
```

If I change it to 
```
processResources {
	inputs.properties(project.properties)
	filesMatching('application.properties') {
		expand(project.properties)
	}
}
```
I get this error:
```* What went wrong:
Could not add entry ':processResources' to cache taskHistory.bin (C:\Development\...\.gradle\3.4\taskHistory\taskHistory.bin).
> Unable to store task input properties. Property 'classLoaderScope' with value 'org.gradle.api.internal.initialization.DefaultClassLoaderScope@2b00d37' cannot be serialized.
```

Any idea what is wrong? I get the same error if I use `inputs.property` with only the single property I want to add to the inputs (which is just a string).

I am using Gradle 3.4

**Comment by lptr** [comment]
`project.properties` contains a lot of things, some of which is not serializable, and thus we can't track changes to them. You could take the properties that you know will be used during expansion (say, `propA` and `prop2`), and add them specifically:

```groovy
processResources {
	def expandProps = ["propA": propA, "prop2": prop2]
	inputs.properties(expandProps)
	filesMatching('application.properties') {
		expand(expandProps)
	}
}
```

**Comment by cabeaulac** [comment]
Using `inputs.properties(props)` to copy when filters change saved me! This took awhile to find. Thank you!

**Comment by big-guy** [comment]
@wolfs Now that we have polymorphic inputs, can this be tackled more easily?

**Comment by lptr** [comment]
I think we could handle the `CopySpec` methods that don't take a `Closure`/`Action` (like `eachFile {}` does) now, yes. We could also handle the ones _with_ the actions, but they would produce a lot of false cache misses in the typical case when the action is declared in the build script. Still, for a lot of use cases we could be doing things better.

**Comment by ZakTaccardi** [comment]
> we don't want to cache archive or copy tasks

Why not? My `Sync` tasks are generally just merging output from one or more tasks into a new folder

**Comment by vlsi** [comment]
I guess the idea is that "build cache" would require Gradle to download the entry from build cache and unpack it.
It would take the same or even extra time as just performing copy/archive actions locally.

**Comment by SgtSilvio** [comment]
While implementing a custom task type with similar inputs than a copy/archive task, I wanted to get inspired by the implementation of the Gradle types and it was unexpected that renaming is not properly implemented for up-to-date checks.
I think that at least a warning is missing in the documentation, with a not that the users currently needs to workaround by declaring inputs themselves (for example on the [working with files page](https://docs.gradle.org/current/userguide/working_with_files.html))
Correct me if I was just too blind to find a note about this topic in the documentation.

**Comment by ajrouvoet** [comment]
This is actually an annoying issue to work around. Typically if something is not marked as an input one can just add it to the inputs of a task explicitly, but because CopySpec is also used outside of concrete tasks (for example, the distribution extension has a copyspec), this is not possible here.

**Comment by jjohannes** [comment]
Why does this not have more upvotes? 😅 
Many users probably don't realize that they have this issue...
