### ISSUE TITLE
Cannot run single test with gradle test --tests command

### ISSUE THREAD

**Issue by octavchiriac** [gradle/gradle#11918]
### Expected Behavior
Running a command like "gradle test --tests TestName" should run only the TestName test

### Current Behavior
After running that command, all the tests in the project run

### Your Environment
I am using gradle 4.10, Junit 5 and java 8

This is my build.gradle file. 
Thanks!

`buildscript {
    repositories {
        maven {
            url "https://mycompanyurl/mvn-public"
        }
        mavenCentral()
    }
    dependencies {
        classpath 'org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.6'
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.2'
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.junit.platform.gradle.plugin'
apply plugin: 'org.sonarqube'
apply plugin: 'jacoco'

ext.junit4Version        = '4.12'
ext.junit5VintageVersion  = '5.5.2'
ext.junitPlatformVersion = '1.5.2'
ext.junit5JupiterVersion  = '5.5.2'
ext.junit5JupiterEngine = '5.5.2'
ext.junitBomVersion = '5.5.2'

compileTestJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}

repositories {
    maven {
        url "https://mycompanyurl/mvn-public"
    }
    mavenCentral()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    compile group: 'com.google.apis', name: 'google-api-services-gmail', version: 'v1-rev98-1.25.0'
    compile group: 'com.sun.mail', name: 'javax.mail', version: '1.6.2'
    compile group: 'com.google.oauth-client', name: 'google-oauth-client-jetty', version: '1.22.0'
    compile group: 'com.relevantcodes', name: 'extentreports', version: '2.41.2'
    compile group: 'org.freemarker', name: 'freemarker', version: '2.3.29'
    compile group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '3.7.1'
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.10'
    compile group: 'org.apache.httpcomponents', name: 'httpcore', version: '4.4.12'

    testCompileOnly("junit:junit:4.12")
    testImplementation("org.junit:junit-bom:${junitBomVersion}")

    // JUnit Jupiter API and TestEngine implementation
    testImplementation("org.junit.jupiter:junit-jupiter:${junit5JupiterVersion}")

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.5.2")

    testImplementation("junit:junit:${junit4Version}")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine:${junit5VintageVersion}") {
        //because 'allows JUnit 3 and JUnit 4 tests to run'
    }

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junit5JupiterEngine}") {
        //because 'allows JUnit 3 and JUnit 4 tests to run'
    }

    testRuntimeOnly("org.junit.platform:junit-platform-launcher:${junitPlatformVersion}") {
        //because 'allows tests to run from IDEs that bundle older version of launcher'
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}`

**Comment by bmuskalla** [comment]
@octavchiriac Have you tried to use a more recent version of Gradle? JUnit Platform/Jupiter is supported [out of the box](https://docs.gradle.org/4.6/release-notes.html#junit-5-support) without the junit plugin

**Comment by bmuskalla** [comment]
Closing this for now. Please feel free to reopen if you can reproduce this.
