### ISSUE TITLE
Plugins block doesn't work on .settings.gradle.kts

### ISSUE THREAD

**Issue by CristianGM** [gradle/gradle#11911]
### Expected Behavior

a gradle plugin like, "custom-plugin.settings.gradle.kts", with:
```
plugins {
  id("com.gradle.enterprise")
}
```

should compile ( and apply the plugin )

### Current Behavior

> Task :compileKotlin FAILED
e: /Users/cristiangarcia/IdeaProjects/jvm-plugin2/src/main/kotlin/com/adevinta/commonplatform/scans.settings.gradle.kts: (6, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
@Deprecated @Incubating public fun Project.plugins(block: PluginDependenciesSpec.() -> Unit): Nothing defined in org.gradle.kotlin.dsl

### Context

As gradle enterprise needs to be configured on settings.gradle.kts now i'm trying to create an internal plugin to configure all the tags, links and values.
As I really love the precompiled scripts I'm trying to create the plugin using them.

### Steps to Reproduce 

https://github.com/CristianGM/plugin-settings-issue-reproducer

### Your Environment

Build scan URL: https://gradle.com/s/hj2r3ppt2ujta

**Comment by itsandreramon** [comment]
Any updates on this? I am facing the same issue.

**Comment by CristianGM** [comment]
I did just workaround that doing: `plugins.apply(GradleEnterprisePlugin::class.java)`

I haven't checked again if it's been fixed in newer Gradle releases

**Comment by jjohannes** [comment]
This is supposed to work. See the Gralde build itself for example: https://github.com/gradle/gradle/blob/master/settings.gradle.kts#L26-L29

A potential issue with the linked example is that the `plugins {}` block needs to go first. In the sample there is another line in front of it (`rootProject.name = "plugin-settings-issue-reproducer"`).

**Comment by yogurtearl** [comment]
seems to be fixed in 7.1, but was broken in 7.0...
