### ISSUE TITLE
User manual documentation for precompiled script plugins, lacking information on applying 3rd-party plugins

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#11912]
### Expected Behavior

In the section on [precompiled script plugins](https://docs.gradle.org/5.3.1/userguide/kotlin_dsl.html#kotdsl:precompiled_plugins), the documentation **should not be** silent on how to apply 3rd-party plugins.

### Current Behavior

In the section on [precompiled script plugins](https://docs.gradle.org/5.3.1/userguide/kotlin_dsl.html#kotdsl:precompiled_plugins), the documentation **is** silent on how to apply 3rd-party plugins.

### Context

I was encouraged to file this issue by @eskatos and @pioterj on the [gradle community slack](https://gradle-community.slack.com/archives/CA745PZHN/p1579078003059700?thread_ts=1578374905.017500&cid=CA745PZHN).

### Your Environment

Build scan URL:

**Comment by eskatos** [comment]
This is now true for both Kotlin and Groovy precompiled script plugins
https://docs.gradle.org/nightly/userguide/custom_plugins.html#sec:precompiled_plugins

cc @rieske

**Comment by pioterj** [comment]
It's a big gap in the docs. Thanks for raising this, @autonomousapps.

**Comment by rieske** [comment]
This is now fixed: https://docs.gradle.org/current/userguide/custom_plugins.html#applying_external_plugins_in_precompiled_script_plugins
