### ISSUE TITLE
Gradle Docs page fails to load on Firefox

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#11928]
When I open any page from https://docs.gradle.org/ in Firefox the page starts eating 100% of one of my CPU cores (see the screenshot).
![gradle-docs](https://user-images.githubusercontent.com/13313417/72594917-eef86800-3908-11ea-97b2-35fa490b40a5.png)

This happened also in November, where removing all cookies and local storage from Gradle domain helped, but now the issue appeared again on the same browser and cleaning does not help. Running Firefox in privacy mode does not help as well. No problems in Chrome.

My environment:
Firefox 72.0.1+build1-0ubuntu0.19.10.1 with 'Enhanced Tracking Protection' set to 'Standard'
Kubuntu 19.10

**Comment by big-guy** [comment]
Does this happen with any other version pages? e.g.

https://docs.gradle.org/nightly/release-notes.html
https://docs.gradle.org/5.0/release-notes.html
https://docs.gradle.org/6.0/release-notes.html

**Comment by big-guy** [comment]
Do you have any extensions installed? I don't see this locally and have had a few others try too.

**Comment by pkubowicz** [comment]
I just reproduced the issue on another machine with identical Firefox version (but I think the version is not so critical since the issue existed already in November). I don't remember ever having problems with Gradle docs website on this machine.

I ctrl-clicked those links in the order you provided and nightly opened without a problem, but remaining two started lagging and finally displayed the warning 'web page slowing down'. Afterwards opening nightly docs stopped working as well.

Initially I had [AdBlock](https://addons.mozilla.org/en-US/firefox/addon/adblock-for-firefox/) and Plasma Integration extensions enabled, but disabling them and restarting the browser does not help. Opening pages in privacy mode does not help as well.

**Comment by pkubowicz** [comment]
Have you changed anything? Some time at the end of the previous week the problem disappeared on both of my computers with Firefox that were previously experiencing it.

**Comment by big-guy** [comment]
No, nothing's changed on our side AFAIK.  Please let us know if this reappears.
