### ISSUE TITLE
Switch to Guava's Java 8 compatible variant

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11920]
We should probably give another go to switching to the Java 8-compatible variant, as there were changes around `ImmutableSet.Builder`:

* 28.1 – `collect`: Fixed a bug in `ImmutableSet.Builder` that could lead to infinite loops when building multiple sets from the same builder. (https://github.com/google/guava/commit/0007cb257b593400097f37cf5fa9c8d5fb598c62)

---
cc: @gradle/build-cache

**Comment by baron1405** [comment]
Better yet, remove Guava from the codebase. Guava leads to nothing but incompatibility issues for the core code and plugins. Most of what is typically used from Guava is now either in Java or was a nice-to-have usage.

**Comment by lptr** [comment]
@baron1405 do you have some specific problems caused by our use of Guava? It should not be visible via the Gradle API.

We use some of the things in there that are not in the JDK, like `ImmutableCollection`s, `TypeToken`s etc.

**Comment by baron1405** [comment]
Writing IntelliJ plugins I have been bitten by the platform version of Guava differing in an incompatible way from the version used by one of my transitive dependencies (an all too easy situation to get into and all too hard to get out of). Looking back in the Gradle closed issues there are a number that talk about Guava version incompatibility impacting debugging and other issues. Bottom line is that something like ImmutableCollection is all to easy to substitute with Collections.Immutable\* to achieve a similar outcome without bringing in the headaches. Thanks for letting me vent :-)

**Comment by lptr** [comment]
Gradle shades its own usage of Guava under `org.gradle.internal.impldep.com.google.common` (among other third-party implementation dependencies), so plugins are free to use their own versions if they want to.

**Comment by baron1405** [comment]
Thanks for the info. Regardless, it would be a very good thing to excise Guava from the code base.

**Comment by lptr** [comment]
If not for collisions with third-party code, why do you think Guava is a bad thing to have as a dependency in Gradle?

**Comment by big-guy** [comment]
dupe #15744

**Comment by lptr** [comment]
This is not so much about upgrading to Guava 30, but about switching from `-android` (aka Java 7 variant) to `-jre` (aka Java 8 variant).

**Comment by lptr** [comment]
There is a performance regression that is introduced by the switch (at least when we last tried it around `27.1-jre`). It might be gone, or we might accept the regression.

**Comment by bmuskalla** [comment]
Some work has been done on [this branch](https://github.com/gradle/gradle/tree/bmuskalla/guava30) exposing some performance problems

**Comment by big-guy** [comment]
@gradle/execution do we need to do this for 7.0? would this be a breaking change?

**Comment by lptr** [comment]
The change is not supposed to be breaking at all. The only reason we never did this since forever is because there is a small performance regression introduced by the switch that we couldn't get rid of. IIRC, it's present in Guava 30 as well.

I strongly believe that accepting the regression would be worth it in the long run, as the Java 8 variant of Guava would allow us to take better use of the Java 8 APIs and write better (and faster) code where we are currently forced to fall back to alternatives.

**Comment by big-guy** [comment]
OK, I'm going to bump this to 7.1 since we can do this later.

**Comment by lptr** [comment]
Note that we should still upgrade to Guava 30 in 7.0.

**Comment by ov7a** [comment]
This issue is no longer relevant. 

Fixed in
* https://github.com/gradle/gradle/pull/17480
