### ISSUE TITLE
Investigate why VFS retention and IE performance tests are slower than direct Gradle profiler runs

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11929]
When running VFS retention performance test as part of our performance test suite, the times are about 200ms slower than running the same tests via `gradle-profiler` directly.

That is very strange, since the performance test suite also uses `gradle-profiler` under the hood.

We should find out what is causing this.

[Performance test infrastructure](https://builds.gradle.org/repository/download/Gradle_Check_IndividualPerformanceScenarioWorkersLinux/30370748:id/results/performance/build/test-results-fullPerformanceTest.zip!/benchmark.html): 
![image](https://user-images.githubusercontent.com/423186/72595782-e56fff80-390a-11ea-88ed-8da4507c0d33.png)

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
I tried combinations of memory settings, though they don't seem to have the desired effect. I am passing now the same Gradle opts/command line opts we do for the standalone tests.

I also tried using exactly the same revision as we did for the standalone tests - no effect.

I saw that Gradle profiler depends on `tooling-api:5.2.1`, I suppose the `toolingApi` project takes precedence over that at test runtime. That means we are using a different TAPI version in Gradle's performance tests. Maybe that is the reason?

**Comment by lptr** [comment]
FTR, today we also mentioned path length as a potential differentiator.

**Comment by lptr** [comment]
Adding @eskatos as this affects IE performance tests as well.

**Comment by lptr** [comment]
Here are our current measurements with direct `gradle-profiler` invocation:

![chart (20)](https://user-images.githubusercontent.com/495366/72726769-823fd080-3b89-11ea-8c5c-536f8a24ca7a.png)

When both IE and VFS optimizations are enabled we are down to `474 ms` after 10 iterations, and reach around `350-400 ms` by the time of the 50th build.

**Comment by wolfs** [comment]
One thing I can think of is that, when running the performance test via Gradle, then Gradle and the test JVM occupy quite some memory, so there is less memory available for OS file system caches. This also would explain why I see a bigger improvement when using VFS retention than in @lptr's measurements.

FTR, this is what I have currently [on CI for non-abi change](https://builds.gradle.org/repository/download/Gradle_Check_IndividualPerformanceScenarioWorkersLinux/30434901:id/results/performance/build/test-results-fullPerformanceTest.zip!/benchmark.html):
![image](https://user-images.githubusercontent.com/423186/72731049-211cfa80-3b93-11ea-9182-dd2a9772cb02.png)

Median after 10 warmups:

scenario | median
--- | ---
no optimizations | 982ms
VFS retention | 811ms
instant execution | 815ms
instant + VFS | 650ms

**Comment by wolfs** [comment]
It seems there is quite some memory available when running perf tests:

![image](https://user-images.githubusercontent.com/423186/72733570-62fc6f80-3b98-11ea-857d-924c4eb644d9.png)
![image](https://user-images.githubusercontent.com/423186/72733670-9a6b1c00-3b98-11ea-9081-2c1b367c076e.png)

So it doesn't seem that memory pressure would affect the timings.

**Comment by lptr** [comment]
In any case we could set the memory limit explicitly. Or do we do that already?

**Comment by lptr** [comment]
Oh, and FTR, I'm wondering why IE only is so unstable on the `gradle/gradle` executions, whereas it is fairly stable when executed via `gradle-profiler` directly.

**Comment by wolfs** [comment]
Here are 100 runs with our test infrastructure:
![image](https://user-images.githubusercontent.com/423186/72787927-2466c380-3c31-11ea-84fd-38e731b28e92.png)

After like 50 iterations the time stabilizes, as it does with the Gradle profiler runs.

**Comment by wolfs** [comment]
Long paths don't seem to be the issue. I tried running the Gradle profiler tests in a path of the same length, and the no optimizations build still goes down to around 700ms after 100 runs.

I also tried changing the JVM arguments, that didn't change anything.

**Comment by lptr** [comment]
I used Oracle Java 8 in my experiments. Are you running on the same?

**Comment by lptr** [comment]
Can you reproduce the faster results with direct `gradle-profiler` invocation?

**Comment by wolfs** [comment]
Both use Java 8. I reproduced the faster results on the same TC agent. I am going to investigate if Teamcity does influence the performance result, given that they add a test listener.

**Comment by wolfs** [comment]
Running Gradle as shell command doesn't change the picture: https://builds.gradle.org/buildConfiguration/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/30473086?buildTab=overview

So it is not the Teamcity init script.

**Comment by wolfs** [comment]
I ran the performance test via the command line and got a result similar to Gradle profiler:
![image](https://user-images.githubusercontent.com/423186/72808393-bedafd00-3c59-11ea-9bff-99ea0ba91698.png)

I used this command line:
```
./gradlew clean santaTrackerAndroidJavaBuild performance:performanceAdHocTest --baselines defaults --scenarios "faster non-abi change on santaTrackerAndroidJavaBuild (build comparison)" --warmups 1 --runs 100 --checks all --channel adhoc -x prepareSamples -Porg.gradle.performance.branchName=wolfs/vfs/perf-test -PtestJavaHome=/opt/jdk/oracle-jdk-8 -Dorg.gradle.workers.max=4 -PmaxParallelForks=4 -s --daemon -Dorg.gradle.internal.plugins.portal.url.override=https://dev12.gradle.org/artifactory/gradle-plugins/ -x :performance:performanceAdhocTestBuildCommitDistribution
```

So what is missing is the application of the build scan plugin and configuring the performance test database.

**Comment by wolfs** [comment]
@blindpirate Do you have any idea what is going on there?

**Comment by wolfs** [comment]
I tried adding more and more flags to the command line. I ended up with:
```
./gradlew clean santaTrackerAndroidJavaBuild performance:performanceAdHocTest --baselines 6.2-20200120230549+0000 --scenarios "faster non-abi change on santaTrackerAndroidJavaBuild (build comparison)" --warmups 1 --runs 100 --checks all --channel adhoc -x prepareSamples -Porg.gradle.performance.branchName=wolfs/vfs/perf-test -PtestJavaHome=/opt/jdk/oracle-jdk-8 -Dorg.gradle.workers.max=4 -PmaxParallelForks=4 -s --daemon -Dorg.gradle.internal.plugins.portal.url.override=https://dev12.gradle.org/artifactory/gradle-plugins/ -I /home/wolf/gradle/gradle/init-scripts/build-scan.init.gradle.kts --build-cache -Dgradle.cache.remote.url=https://cache-node-frankfurt.grdev.net/cache/ -Dgradle.cache.remote.username=gradle1 -Dorg.gradle.internal.tasks.createops
```

Which is exactly the same which is added on CI. No slowdown so far.

**Comment by wolfs** [comment]
I also did set `TMP`, `TEMP` and `TMPDIR` within my home, so the `tmpfs` mounted temp isn't used as it happens on Teamcity as well. No effect.

**Comment by lptr** [comment]
If this goes on long enough @wolf will have the whole of TeamCity implemented. If it _still_ doesn't reproduce the problem, I propose we switch to Stefan's TeamCity implementation.

**Comment by wolfs** [comment]
Even when setting all environment variables from TC, the build running from the command line is still fast...

**Comment by wolfs** [comment]
I can finally reproduce the difference. It seems to be some environment variable. Let's try to find out which one...

**Comment by wolfs** [comment]
It seems like the build is slower, when `CI=1`. Does the Android plugin maybe react to that environment variable?

**Comment by wolfs** [comment]
I can even reproduce the result by running Gradle profiler alone and setting the environment variable.

**Comment by wolfs** [comment]
For some reason, when the `CI` environment variable is set, Gradle spends more time in snapshotting the outputs (`80ms` vs `240ms`). I wonder why that is...

**Comment by wolfs** [comment]
Without the CI flag, even when running on CI, the [performance result is better](https://builds.gradle.org/repository/download/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/30517221:id/results/performance/build/test-results-performanceAdhocTest.zip!/benchmark.html):

![image](https://user-images.githubusercontent.com/423186/72913023-d343f600-3d3c-11ea-8156-f4fc59fcc0b0.png)

**Comment by wolfs** [comment]
Looks like all of the extra time is spent on snapshotting the outputs of 
`packageApplication`: https://scans.gradle.com/s/qq6wl3s5i4zxe/timeline?details=dyhhf7s7la5am&expanded=WzRd&sort=longest

**Comment by wolfs** [comment]
When `CI` is set, the build produces three APKs instead of one, each having 28M. That explains why output snapshotting takes so much longer. The culprit is in the [Java variant of `santa-tracker`](https://github.com/gradle/santa-tracker-android/blob/609eb93f19c8fc8c9d8a0cb130d620e31d47b9bc/santa-tracker/build.gradle#L59-L60):
```groovy
    boolean ciBuild = System.getenv("CI")
    splitEnabled = ciBuild                   // Tip 3
```

The Kotlin variant of santa tracker doesn't seem to have the problem.

**Comment by lptr** [comment]
🎉 Nice detective work @wolfs.

**Comment by wolfs** [comment]
This PR removes the code dependent on "CI" from santa-tracker Java: https://github.com/gradle/santa-tracker-android/pull/10

**Comment by wolfs** [comment]
This is fixed on `master` now.
