### ISSUE TITLE
`-x` is not honored by the configuration cache

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/gradle#11926]
While testing gradle instant execution, I had an issue with a task, and tried to skip it using `-x`. But the task was still being executed. (gradle 6.1-RC2).

**Comment by eskatos** [comment]
Thanks for the report @stephanenicolas 
It is correct that adding `-x` doesn't invalidate the instant execution cache, yet.
If you need to use `-x` Today you need to [invalidate the cache](https://gradle.github.io/instant-execution/#invalidate_cached_state) yourself.

**Comment by eskatos** [comment]
Fixed in 6.5, closing
