### ISSUE TITLE
Brew upgrade is not working with 6.1

### ISSUE THREAD

**Issue by Jonatha1983** [gradle/gradle#11932]
Hi 

I see that yesterday a new release was upload but when running brew upgrade gradle it is still fetchin 6.0.1.

Maybe it is on brew side but can be that the new version was not upload properly ?

**Comment by rpalcolea** [comment]
Homebrew is aware of 6.1 -> https://formulae.brew.sh/formula/gradle

```
❯ brew info gradle
gradle: stable 6.1
Open-source build automation tool based on the Groovy and Kotlin DSL
https://www.gradle.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gradle.rb
==> Requirements
Required: java >= 1.8 ✔
==> Analytics
install: 29,106 (30 days), 144,607 (90 days), 611,211 (365 days)
install-on-request: 28,237 (30 days), 137,584 (90 days), 577,691 (365 days)
build-error: 0 (30 days)
``` 

Maybe needs an update from your side?

**Comment by Jonatha1983** [comment]
Now it is working. Till few hours ago it did not. 
I ran brew upgrade gradle and it kept 6.0.1.
Thanks.
