### ISSUE TITLE
Determine whether anything needs to be built without actually building

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#11942]
### Expected Behavior

There should be a way to ask Gradle if something needs to be built without actually building anything.

### Current Behavior

There is no such command in Gradle currently.

### Context

See [this discussion](https://discuss.gradle.org/t/determine-if-a-task-is-up-to-date-from-cache-without-actually-executing-it/34504) in the forum: E.g. to determine if / which prerequisites need to be installed for CI builds, it would be good to know if Gradle needs to build anything at all, or if e.g. only `*.md` files that do not affect the build were modified.

One possible way to implement this probably would be by extending the existing `--dry-run` command line option to print something like `SKIPPED (would be: UP-TO-DATE)` to denote what the task status would be without `--dry-run`, and / or changing the exit code accordingly.

**Comment by lptr** [comment]
How would you handle cascading changes, i.e. when a task is not up-to-date and its output is used downstream?

**Comment by sschuberth** [comment]
If a task in the task graph is not up-to-date, then it needs to be built, and the logic could just stop there without looking at anything downstream as the question basically just is *if* anything needs to be built (for a given "leaf" task), not necessarily *what*.

**Comment by lptr** [comment]
How do you imagine this interaction to work out, for example when invoked from the console? What would the command-line look like, and what would be reported back to the user?

**Comment by sschuberth** [comment]
> What would the command-line look like, and what would be reported back to the user?

Please see my "One possible way to implement this" paragraph from above, and feel to ask further concrete questions if anything is unclear in there.

**Comment by lptr** [comment]
Say, I have a Java multi-project, what's the command-line I invoke for testing is everything down to `assemble` is up-to-date? The `--dry-run` switch is for something else, so we'd need some other way of specifying this.

And say that `:lib:compileJava` is not up-to-date, which has a bunch of downstream dependencies. How would this work? Would the build fail? (We currently only return a non-zero exit code when it does.) Would this be a different status than `FAILED` vs `SUCCESS`? What would the user see on the console?

What I can imagine that we could easily add is something like `--fail-if-not-fully-up-to-date` or something, but its value as a feature seems dubious to me. Introducing a new build outcome besides `FAILED` and `SUCCESS` seems like an integration nightmare (e.g. CI tools and build scans would need to handle the outcome somehow). Printing something on the console and looking for that at the calling side seems brittle.

**Comment by lptr** [comment]
Closing as no further input is received.

**Comment by sschuberth** [comment]
@lptr, please don't prematurely close unresolved issues just because there has been no feedback for a few weeks. People might have different real-life priorities (like business trips, vacation, sick leave etc.), so four weeks can easily pass.

I'm still not convinced that the console output of `--dry-run` could not be extended to display the information that I look for. But if you'd prefer a new command line option, I'd probably call it something like `--check-up-to-date`. That name makes it pretty much clear that a non-zero exit code is returned if the check failed, i.e. not all tasks are up-to-date.

**Comment by lptr** [comment]
We will close feature requests and bug reports after longer periods of inactivity. That said, please feel free to reopen them whenever you have more to add.

I wonder how having something like `--check-up-to-date` returning a non-zero error code would help you in case only `*.md` files were modified.

**Comment by sschuberth** [comment]
> We will close feature requests and bug reports after longer periods of inactivity.

I basically agree with that approach, but obviously our definitions of "longer" differ :wink: 

> That said, please feel free to reopen them whenever you have more to add.

I might have overlooked it, but I'm pretty sure the button to reopen the issue was missing although I'm the original reporter.

> I wonder how having something like `--check-up-to-date` returning a non-zero error code would help you in case only `*.md` files were modified.

Well, I imagine it to work like this:
- We have no tasks that use `*.md` files as input.
- PR builds get triggered if the repo contents changed.
- So within a PR, if `--check-up-to-date` returns zero, we know that only code that is irrelevant to the build has changed, e.g. only `*.md` files.
- If only code irrelevant to the build has changed, we can avoid installing a ton of prerequisites in CI which are required only for building.

**Comment by lptr** [comment]
Looks like we could handle your use case via this feature idea: https://github.com/gradle/gradle/issues/11945

**Comment by sschuberth** [comment]
Well, somewhat. @vlsi was also involved in the [original discussion](https://discuss.gradle.org/t/determine-if-a-task-is-up-to-date-from-cache-without-actually-executing-it/34504) that I linked in my first post, and that's also where he suggested that idea in the first place.

What I don't like about his idea is that you *have* to implement the logic to install Python (in his example) in Gradle. I'd like to be free to implement that logic differently, outside of Gradle, and only query Gradle about whether a build is needed or not.

**Comment by vlsi** [comment]
@sschuberth , the thing is the current model Gradle uses does not allow to predict if the task will be up-to-date or not.
That is determined at the time of task execution.

Frankly speaking, I dot not like the idea of adding extra modes to `--dry-run` because, well, it takes time to implement, test, and support, however, the gains are extremely limited.

I do like how Gradle enables having modular builds. That is, in M build system you can't really build all the jars without publishing them to local repository and running all the tests.
In Gradle, you can do just the relevant compilations and jars.

In the same way, I see you have pain with installing toolchains, however, I believe, that should be made in a fine-granular way.

In other words, the solution should support more than a single toolchain, and it should not really fail in cracks in case it sees "I am not sure if the task is up to date" case.

---

Note: there's a connected case with C++ and JavaScript development.
It would be great if Gradle could download and install the relevant toolchains if they are missing at the developer machine.

Implementing a feature like "ok, your build is not completely up to date" is of very limited help there :-/

---

It looks like `build services` is a very relevant feature here. AFAIK you can model `python` installation as a `build service`, and it would enable you to install the toolchain only in case a relevant task is actually executed.

Of course, #11945 might be relevant as well, however, it is not yet in core.

**Comment by sschuberth** [comment]
Also with *Build Services* I would have to implement the logic to install prerequisites in Gradle. If I had to do that anyway, I'd prefer to do so via your simpler `initializedBy` proposal. I also acknowledge it's more generic if you stick to the "Gradle universe", so I'll close my feature request and support yours instead.

**Comment by vlsi** [comment]
> install prerequisites in Gradle

Well, you could still call a shell script from Gradle.

> `initializedBy` proposal

Well, now we need to trick someone into implementing it :)
