### ISSUE TITLE
Compiled plugins with kotlin-dsl repository{} in buildscript block are broken since 6.1

### ISSUE THREAD

**Issue by JasonMing** [gradle/gradle#11947]
### Expected Behavior

Build still works

### Current Behavior

Build failed

### Context

The compiled plugin with kotlin-dsl  `repository { ... }` in `buildscript{ ... }` block use gradle 6.0.1 are broken in gradle 6.1. 

### Steps to Reproduce 

1. Compile plugin use gradle **6.0.1**

   ```kotlin
   class FooGradlePlugin : Plugin<Gradle> {
       override fun apply(target: Gradle) {
           target.beforeProject {
               buildscript {
                   repositories { // <<= This block is actually call `org.gradle.kotlin.dsl.ProjectExtensions.repositories(...)`
                       // configure repository here
                   }
               }
           }
       }
   }
   ```

2. Apply the plugin in gradle **6.1**

3. Report error

   ```
   Caused by: java.lang.NoSuchMethodError: org.gradle.kotlin.dsl.ProjectExtensionsKt.repositories(Lorg/gradle/api/initialization/dsl/ScriptHandler;Lkotlin/jvm/functions/Function1;)V
   ```

### Cause

In gradle 6.1 the extension method `ScriptHandler.repositories(configuration: RepositoryHandler.() -> Unit)` moved  from file *org/gradle/kotlin/dsl/__ProjectExtensions.kt__* to *org/gradle/kotlin/dsl/__ScriptHandlerExtensions.kt__*.

This causes the generated class name is changed.

**Comment by ljacomet** [comment]
Thanks for the report, that is a mistake made in a change for Gradle 6.1 in #11425 

Looking at options for taking care of this.
