### ISSUE TITLE
Inconsistent Kotlin DSL for dependencies

### ISSUE THREAD

**Issue by AHeise** [gradle/gradle#11956]
Most Kotlin DSL methods that help to define dependencies in certain configuration take `dependencyNotation: Any` to also support maps and arrays. However, there are some non-obvious exceptions.

### Expected Behavior

I'd expect all dependency related method to take `dependencyNotation: Any`.

### Current Behavior

The method
```
fun DependencyHandler.`implementation`(
    dependencyNotation: String,
    dependencyConfiguration: Action<ExternalModuleDependency>
)
```
is not allowing `Any`. The underlying method takes `Any` though. Same is true for testImplementation and probably other configurations.

### Context

This is currently not compiling
```
plugins {
    `java-library`
}

object Libs {
    val hadoop_common = mapOf("group" to "org.apache.hadoop", "name" to "hadoop-common")
}

infix fun Map<String, String>.classifier(classifier: String): Map<String, String> = this + mapOf("classifier" to classifier)

dependencies {
    testImplementation(Libs.hadoop_common classifier "tests") {
        exclude("jdk.tools", "jdk.tools")
    }
}
```

If I remove the configuration with the exclusion, then all is good.

### Steps to Reproduce 

See above example.

### Your Environment

Gradle 6.1

I can provide more information but I hope it's already enough.

**Comment by AHeise** [comment]
Btw I could provide a PR to fix it if it's indeed just an oversight and not a deliberate design decision.

**Comment by AHeise** [comment]
Okay just noticed that
```
    api(project("...")) {
        exclude(group = "org.apache.kafka", module = "kafka-clients")
    }
```
Would not work anymore. Seems like a limitaton of Kotlin that it doesn't pick the more specific extension method.

**Comment by bamboo** [comment]
> Okay just noticed that
> 
> ```
>     api(project("...")) {
>         exclude(group = "org.apache.kafka", module = "kafka-clients")
>     }
> ```
> 
> Would not work anymore. Seems like a limitaton of Kotlin that it doesn't pick the more specific extension method.

Right and that's basically why we chose the current design which uses the static type of the dependency notation to drive the type of dependency is made available to the configuration lambda.

**Comment by AHeise** [comment]
Okay thank you for the response, closing
