### ISSUE TITLE
[com.gradle.plugin-publish] Custom plugin with classifier dependency

### ISSUE THREAD

**Issue by Ealrann** [gradle/gradle#11958]
### Context

In a custom plugin, the pom.xml generated by the ‘com.gradle.plugin-publish’ doesn't contains the dependencies related to a classifier (here, 'native-linux'). 

### Steps to Reproduce 
A use case project [is available here](https://github.com/Isotropy-Studio/gradle-shaderc/tree/16a4222ad8c163d775761443a88cea889e904ba0) (the gradle plugin is inside _buildSrc/_). It works when used in buildSrc, but not when published due to the following problem.

Here the dependencies in the custom gradle plugin (build.gradle):
```
dependencies {
	implementation "org.lwjgl:lwjgl:3.2.3"
	implementation "org.lwjgl:lwjgl-shaderc:3.2.3"
	runtimeOnly "org.lwjgl:lwjgl:3.2.3:natives-linux"
	runtimeOnly "org.lwjgl:lwjgl-shaderc:3.2.3:natives-linux"
}
```

### Current Behavior
The generated pom.xml (build/publish-generated-resources/pom.xml):
```xml
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0">
      <modelVersion>4.0.0</modelVersion>
      <groupId>gradle.plugin.org.isotropy.gradleshaderc</groupId>
      <artifactId>buildSrc</artifactId>
      <version>0.0.3</version>
      <dependencies>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl</artifactId>
          <version>3.2.3</version>
          <scope>runtime</scope>
          <type>jar</type>
          <optional>false</optional>
        </dependency>
        <dependency>
          <groupId>org.lwjgl</groupId>
          <artifactId>lwjgl-shaderc</artifactId>
          <version>3.2.3</version>
          <scope>runtime</scope>
          <type>jar</type>
          <optional>false</optional>
        </dependency>
      </dependencies>
    </project>
```

### Expected Behavior
I expected two more dependencies in the pom.xml, something like:
```xml
<dependency>
	<groupId>org.lwjgl</groupId>
	<artifactId>lwjgl</artifactId>
	<classifier>natives-linux</classifier>
</dependency>
<dependency>
	<groupId>org.lwjgl</groupId>
	<artifactId>lwjgl-shaderc</artifactId>
	<classifier>natives-linux</classifier>
</dependency>
```

### Your Environment
Gradle 6.1 (with wrapper)
```
plugins {
	id 'java-gradle-plugin'
	id 'com.gradle.plugin-publish' version '0.10.1'
}
```

**Comment by jjohannes** [comment]
@Ealrann Thanks for reporting. I have to apologize: many details of the portal publishing plugin are badly documented at the moment.

The plugin has it's own pom generation mechanism which lacks some features (that's what you are encountering). But you can also make it use Gradle's core publishing mechanism for the pom generation which is now very advanced. (This should really be the default behavior, I hope we get to fixing this soon.)

For now, for the mechanism to take effect, you need to apply the `maven-publish` plugin in addition. 

```
plugins {
   id 'maven-publish'
   ...
}
```
Then this should work.

**Comment by Ealrann** [comment]
Thank you very much, it works !
