### ISSUE TITLE
Gradle 6.1 release notes page not complete?

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#11954]
I noticed that the 6.1 release notes have no fixed issues listed

https://docs.gradle.org/6.1/release-notes.html#fixed-issues

These seems quite unusual to me as most releases fix issues :) Known issues also isn't populated which is more plausible but I think somewhat unlikely.

Is the page information complete?

For example, I found by trial/error that 6.1 stopped allowing injection of `ProjectLayout` into workers as per #11434. But I can't find any mention of this breaking change in the release notes so was surprised to run into it. To clarify, I don't mind a breaking change to an incubating API itself, but was hoping they're mentioned in release notes, at least as part of the list of fixed issues.

**Comment by big-guy** [comment]
This was a bug in our documentation generation in 6.1.  You can see the fixed list here: https://services.gradle.org/fixed-issues/6.1

There's an upgrade guide that contains more information about breaking/potentially breaking changes:
https://docs.gradle.org/6.1/userguide/upgrading_version_6.html#projectlayout_is_no_longer_available_to_worker_actions_as_a_service

This is linked from the "Upgrade Instructions" section.

**Comment by mikejhill** [comment]
Just wondering, is it possible to retroactively add these to the 6.1 release notes page? I keep having to navigate back to this issue and then to the link in @big-guy's comment to see if something I'm running into is known/fixed. It also kind of makes it look like 6.1 didn't fix anything for anybody looking through release notes and considering upgrading.
