### ISSUE TITLE
Gradle Test Kit: Support for setting test directory programmatically

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#11965]
Currently, in order to configure the Gradle Test kit so that you can set the temporary directory that it uses as the Gradle Home directory, you have to set, and then unset the system property `org.gradle.testkit.dir`.

https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/DefaultGradleRunner.java#L48

### Expected Behavior

The Gradle Test Kit API should provide a programmatic API way to configure the directory for the Gradle Home directory.

### Context

Without this, writing a plugin that writes to the `gradle.properties` file and then tests that the files contents are sane isn't really possible.

Use case: `plugin-publish-plugin`

**Comment by big-guy** [comment]
We talked about the `gradle.properties` use case separately, but I think what you're asking for is `GradleRunner.withTestKitDir()`.
