### ISSUE TITLE
Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry

### ISSUE THREAD

**Issue by ConradKrinock** [gradle/gradle#11961]
### Background/Intro:
We have successfully:
•	downloaded the gradle source code from https://github.com/gradle/gradle.git
•	run a full build
Objective:  We need to step through the gradle source code to closely inspect our development builds.  

### Primary Error Message:   
Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry

### Possible related issue:
https://github.com/gradle/gradle/issues/9598

### Point of failure: 
org.gradle.launcher.bootstrap.EntryPoint.createCompleter()
(see attachment for additional details)

### Possible Solution 1 – folder permissions:
(see attachment for additional details)

### Possible Solution 2 – increase JVM memory:
(see attachment for additional details)

### Full Error Log
(see attachment)

### Attachment
[ERROR-GlobalScopeServices.createClassLoaderRegistry.docx](https://github.com/gradle/gradle/files/4092119/ERROR-GlobalScopeServices.createClassLoaderRegistry.docx)

**Comment by ConradKrinock** [comment]
### Update
Found the following annotations in org.gradle.launcher.bootstrap.EntryPoint.java.  The two items I denoted in bold/italic print appear to be in conflict:

- An entry point is the point at which execution will never return from.
  Its purpose is to consistently apply our completion logic of forcing the JVM
  to exit at a certain point instead of waiting for all threads to die, and to provide
  some consistent unhandled exception catching. 
- Entry points may be nested, as is the case when a foreground daemon is started. 
- The **_createCompleter() and createErrorHandler() are not really intended to be overridden_**
  by subclasses as they define our entry point behaviour, but they are protected to enable
  testing as it's difficult to test something that will call System.exit().

- **_Unless the createCompleter() method is overridden, the JVM will exit before returning_** from this method.
  
I'm going to do an Internet  search on something  like "gradle override EntryPoint.createCompleter"

**Comment by ConradKrinock** [comment]
### On-Hold
I've nearly got this solved.  Hope to publish the resolution tomorrow.

**Comment by thecodesmith** [comment]
@ConradKrinock were you able to solve this one? Running into the same issue.

**Comment by ConradKrinock** [comment]
Hi Brian -- OMG I got diverted to other duties and can't remember if I solved this partially or totally.   I'll take a look at my finding Friday morning 14-Feb and add another comment.  (Been up since 430am and it's now 630pm)

**Comment by blindpirate** [comment]
Please attach at least stacktrace (you can get that via `--stacktrace`), otherwise we can't provide any help.
