### ISSUE TITLE
Provider.map and flatMap should be able to return null

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#11979]
The Android Gradle Plugin is starting to use `Property` objects with non file types (eg `Property<String>`).

We expose them via our Variant API as inputs to our tasks because we don't want people to reach our task instances as the task types are not stable (nor do we want them to become stable). So this abstraction is important to set any type of values on tasks.

Some of these properties are initialized with `Provider.map {...}`. Sometimes these providers are actually consumed artifact. For instance:

```
val artifact: FileCollection = config.incoming.artifactView(...).artifacts.artifactFiles
val dataProvider: Provider<Data> = artifact.elements.map { Data.load(it.single.asFile) }
myXProp.set(dataProvider.map { data.getX() }
myYProp.set(dataProvider.map { data.getY() }
```

In these cases it's important to be able to handle optional data and have `map` return a null value.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/12025
