### ISSUE TITLE
Allow more fine-grained configuration of checksums in maven-publish

### ISSUE THREAD

**Issue by marco-schmidt** [gradle/gradle#11984]
### Expected Behavior
I would like to create checksum files for algorithms SHA-1, MD-5 and SHA-256 only.

### Current Behavior
Since gradle version 6.0, checksum files SHA-256 and SHA-512 are uploaded when publishing with the maven-publish plugin: https://docs.gradle.org/6.0/release-notes.html#publication-of-sha256-and-sha512-checksums

Since gradle 6.0.1 there is a property to suppress the two new checksum types when publishing: https://docs.gradle.org/6.0.1/release-notes.html#publication-of-sha256-and-sha512-checksums

However, there is no way to just get SHA-256 but not SHA-512 files, either both or none of them:
https://github.com/gradle/gradle/blob/eb55a885af363f8a2981034d5cdd4a0eeb300b47/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java#L261

### Context
Our artifact server only supports SHA-256, SHA-1 and MD-5, but not SHA-512. We do want the SHA-256 files, but all SHA-512 files are considered as artifacts, doubling the number of entries in all views and in the database. We would like to avoid the clutter while getting the benefit of the more secure SHA-256 checksum.

It would be nice to have a configurable option for the types of checksum files that are uploaded with maven-publish. There will always be various artifact servers that support different types of checksums at any given time.

Ideas:
- There could be a comma-separated list of checksum types like this: systemProp.org.gradle.internal.publish.checksums.types=sha1,md5,sha256
- There could be a way to enable or disable SHA-256 and SHA-512 separately with two system properties, one for each type (relatively easy to implement in the context of the code segment that I quoted above), e.g. like this:
systemProp.org.gradle.internal.publish.checksums.sha256=true
systemProp.org.gradle.internal.publish.checksums.sha512=false

**Comment by melix** [comment]
I don't think we should do this. Basically, supported checksums should ideally be inferred from the repository. Just like signatures, checksums are "side effects" of the publication and shouldn't be configurable really. I understand the pain in the transition, but adding a flag has a cost that we cannot really afford.

**Comment by marco-schmidt** [comment]
I don't have a good overview of the market share of various repository server software packages. But Artifactory is an important one. I also don't know why gradle developers picked both SHA256 and SHA512 (why wasn't one enough).

But deciding that every repo software better accept both these types plus the old ones with gradle 6.0 seems strange to me when there are negative side-effects (sha files being considered artifacts themselves if unknown, cluttering repositories or causing warnings or errors). There's a good reason that 6.0.1 added the ability to turn off the new hash types again. Going a step further and giving developers control is the obvious solution to me.

This is also true for the other direction, no longer using weak hash types, wanting to stop using SHA1 and MD5, which I think is also not possible right now. This would be mostly relevant for closed systems.

I doubt that gradle has the clout to force repo vendors everywhere to quickly change their ways. A request to support SHA512 with npm in Artifactory has been open for half a year: https://www.jfrog.com/jira/browse/RTFACT-20084

**Comment by ljacomet** [comment]
While we can understand your point, adding any kind of configuration is much more work than we are ready to commit to for now. Especially because of the way the publishing plugins work, with different repositories, etc ...

Gradle will reach out once again to the main repository providers and see if this can be resolved on their side. This would be the best outcome for security.

**Comment by ljacomet** [comment]
Closing as there is no plan for more fine grained checksum configuration for publication in Gradle.

**Comment by eric-creekside** [comment]
Can you at least point to where in the Gradle code the checksum file generation happens? Some of us might want to write our own derivative maven publish plugin that does something slightly different than the standard `maven-publish` one.

**Comment by mach-wkl** [comment]
@eric-creekside The generation and upload of checksums is called in https://github.com/gradle/gradle/blob/master/platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java#L287 and happens a few lines later.

I've been running into the same issue - we want to stop uploading checksums other than sha256 to minimize requests to our maven repo server.
