### ISSUE TITLE
`CalculatedTaskInputFileCollection` should propagate dependencies

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#11998]
Currently, [`CalculatedTaskInputFileCollection`](https://github.com/gradle/gradle/blob/ade03bae73c41d670524d726af52d15aebf8b693/subprojects/core/src/main/java/org/gradle/api/internal/file/CalculatedTaskInputFileCollection.java) doesn't depend on any of the dependencies of the file collection it depends on.

It should override `visitDependencies` and add the `inputs` and `calculatedFiles` as dependencies to resolve.

This would help for the native compile tasks when adding an include directory which is generated by a task, since the include directories are ignored, only the detected header dependencies are inputs.

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
We should probably add a `ForwardingFileCollection` base class for these purposes.

**Comment by wolfs** [comment]
This is not necessary, since the native task which uses `CalculatedTaskInputFileCollection` already propagates the dependencies:https://github.com/gradle/gradle/blob/946abeb1108edd69576be49f544d19b40b144dcf/subprojects/language-native/src/main/java/org/gradle/language/nativeplatform/tasks/AbstractNativeCompileTask.java#L80-L81
