### ISSUE TITLE
Compile and runtime classpath should request attribute category=library

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#11995]
Otherwise, Gradle would look for other variants if the _library_ variants are discarded (e.g. because of a wrong Java version).

As for example reported here: https://twitter.com/marcknaup/status/1220638897316581376

**Comment by fluidsonic** [comment]
Thanks for creating the issue!

Simple example `build.gradle.kts`:
```kotlin
plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
}

configure<JavaPluginConvention> {
    targetCompatibility = JavaVersion.VERSION_1_7
}
```

`org.junit.jupiter:junit-jupiter-api:5.6.0` requires Java 8.

### Error
```
Execution failed for task ':compileTestJava'.
> Could not resolve all files for configuration ':testCompileClasspath'.
   > Could not resolve org.junit.jupiter:junit-jupiter-api:5.6.0.
     Required by:
         project :
      > Cannot choose between the following variants of org.junit.jupiter:junit-jupiter-api:5.6.0:
          - javadocElements
          - sourcesElements
        All of them match the consumer attributes:
          - Variant 'javadocElements' capability org.junit.jupiter:junit-jupiter-api:5.6.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'javadoc' but wasn't required.
                  - Required org.gradle.jvm.version '7' but no value provided.
                  - Required org.gradle.libraryelements 'classes' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
          - Variant 'sourcesElements' capability org.junit.jupiter:junit-jupiter-api:5.6.0:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'sources' but wasn't required.
                  - Required org.gradle.jvm.version '7' but no value provided.
                  - Required org.gradle.libraryelements 'classes' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
```

**Comment by melix** [comment]
The missing attribute can be added this way:

```
configurations.all {
   if (name.endsWith("Classpath") && isCanBeResolved) {
       attributes {
           attribute(Category.CATEGORY_ATTRIBUTE, project.objects.named(Category.LIBRARY))
       }
   } 
}
```

Then the build would fail with a more appropriate error message:

```
         - Variant 'apiElements' capability org.junit.jupiter:junit-jupiter-api:5.6.0:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '7' and found incompatible value '8'.
              - Other attributes:
                  - Required org.gradle.category 'library' and found compatible value 'library'.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'classes' and found compatible value 'jar'.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
                  - Found org.jetbrains.kotlin.localToProject 'public' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.

```

Which then tells that `7` is incompatible with `8`. It would still need refinements to be more understandable but that's beyond the scope atm.

**Comment by jjohannes** [comment]
Will be fixed in Gradle 6.2 (#11997). Thanks again for bringing this to our attention @fluidsonic!

**Comment by melix** [comment]
This is how such an error would look like with the improved error messages of #12647 

![Selection_442](https://user-images.githubusercontent.com/316357/78127854-2c06cd80-7415-11ea-8553-41c418e4bae8.png)

**Comment by alehhramovichvipps** [comment]
Hi, folks! Having the same issue:
`[STDERR]                   - Found org.gradle.category 'documentation' but wasn't required.,
[STDERR]                   - Found org.gradle.docstype 'sources' but wasn't required.,
[STDERR]                   - Required org.gradle.jvm.version '8' but no value provided.,
[STDERR]                   - Required org.gradle.libraryelements 'jar' but no value provided.,
[STDERR]                   - Found org.gradle.status 'release' but wasn't required.,
[STDERR]               - Compatible attributes:,
[STDERR]                   - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.,
[STDERR]                   - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.,
[STDERR] ,
[STDERR] * Try:,
[STDERR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.,
[STDERR] ,
[STDERR] * Get more help at https://help.gradle.org,
[STDERR] ,
[STDERR] BUILD FAILED in 14s. Check https://github.com/appium/appium-espresso-driver#troubleshooting regarding advanced session startup troubleshooting. (SessionNotCreated)`

Any suggestions on how to fix it?
