### ISSUE TITLE
Add testRuntimeOnly to Managing Dependencies of JVM Projects

### ISSUE THREAD

**Issue by spottedmahn** [gradle/gradle#11996]
On https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html#sec:configurations_java_tutorial shouldn't `testRuntimeOnly` also be listed?

Under this section:

![image](https://user-images.githubusercontent.com/14079228/72831876-b7aff100-3c51-11ea-8434-3108672cbc10.png)

**Comment by lacasseio** [comment]
This issue is related to the `gradle/gradle` user manual, I moved it to the right repository.

**Comment by ljacomet** [comment]
That specific section mentions the most used configuration, and the sentence that introduces it explicitly says "let's look at a few of the standard configurations".

So I think it is fair to leave out `testRuntimeOnly` at this point. Being exhaustive would double the entries otherwise.

**Comment by spottedmahn** [comment]
>Being exhaustive would double the entries otherwise.

Fair enough.  What about a link to the exhaustive list? 🤔

**Comment by ljacomet** [comment]
Unless I am missing something, this is exactly what the link in the sentence before the `implementation` entry gives you.
It leads to [this section](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph) which lists `compileOnly`, `runtimeOnly` and more

**Comment by spottedmahn** [comment]
>Unless I am missing something, this is exactly what the link in the sentence before the implementation entry gives you.

🤦‍♂️, it does, my bad!  thanks!
