### ISSUE TITLE
Gradle have to have improve creation of caches [version 5.6.4]

### ISSUE THREAD

**Issue by netbeansuser2019** [gradle/gradle#12017]
There is issue with gradle and I guess that it is due to fact that gradle creates so long names e.g.:
…_run_closure12_closure13$_closure14$_closure15…class
I can see issue with bootRun task that application was not possible to start
after I have changed a gradle user home dir from implicit to explicit (shortest possible path)
it seems there is no issue at least for now with such files. 

Now I can see that there is only workaround by changing gradle user home folder, but 
this is not real solution as if there is no protection that respect used filesystem 
limits so my suggestion is that it should be used shorter file names 
at least (e.g. instead of using word "_closure" it could be used e.g. just "c").

### Expected Behavior
Do not create such a long paths in under Gradle User Home.

### Current Behavior
Creating such long path under Gradle User Home affect a possibility to run task from gradle build.
See: https://discuss.gradle.org/t/gradle-have-to-have-improve-creation-of-caches-version-5-6-4/34219

### Context
Gradle: 5.6.4 for wrapped 6.0.1
JVM: 11.0.2 (Oracle Corporation 11.0.2+9)

### Steps to Reproduce 
There is no exact steps, but it really happends all the time that it is created long paths
under Gradle User Home.

As example: 
GRADLE_HOME\caches\6.0.1\scripts-remapped\build_2xyj9vk6ngi4xwuivtvjbcf9t\da1sm9frj07j6zzcy3daf5nlj\cp_proj27b7120d8bed45e60dd0b95b8e5ecea0\classes\…_run_closure12_closure13$_closure14$_closure15…class
or 
GRADLE_HOME\caches\6.0.1\scripts\1ev8hkffve8pufuf7mpnouzvd\cp_proj\cp_proj27b7120d8bed45e60dd0b95b8e5ecea0\classes\…_run_closure12_closure13$_closure14$_closure15…class

### Your Environment
Gradle: 5.6.4 for wrapped 6.0.1
JVM: 11.0.2 (Oracle Corporation 11.0.2+9)

**Comment by netbeansuser2019** [comment]
I think that it is still relevant it should not be create such long filenames.

**Comment by octylFractal** [comment]
We do not control the length of filenames, that is controlled by the compiler (Kotlin or Groovy). The only applicable fix is storing the arguments to certain commands in files and using special syntax to execute them, which is covered by #1989.
