### ISSUE TITLE
No way to use the same locked dependencies among all sub-projects

### ISSUE THREAD

**Issue by aaronabf** [gradle/gradle#12023]
### Background

We have a multi-project build running the latest version of Gradle, v6.1. Each sub-project declares its own dependencies along with any restrictions necessary for the project to run properly. We wish for all of our code to compile and run with the same dependencies in both testing and production

### Issue

As part of our build pipeline we ensure dependency resolution can succeed with proper conflict resolution and then lock all dependencies. However, we recently realized that sub-projects were not compiling with the locked dependencies. This is because each sub-project looks for dependency locks in its own `gradle/dependency-locks` directory and we are only generating these file in our root project.

For instance we notice discrepancies such as
```
$ ./gradlew :dependencies | grep this-is:a-dependency | sort -u | head -n1
+--- this-is:a-dependency:2.0

$ ./gradlew :some-subproject:dependencies | grep this-is | sort -u | head -n1
|   \--- this-is:a-dependency:1.0
```

### Feature

This seems like fairly common use-case of a multi-project build. There should be a way to have a specific set of locked dependencies be used across all sub-projects.

**Comment by ljacomet** [comment]
What you are looking for is captured in #7395

**Comment by dsilvasc** [comment]
> What you are looking for is captured in #7395.
> 
> Once such a feature is available, you will be able to lock only the base configuration used to determine versions.

Would that be one base configuration per subproject, or one for the entire multi-project build?
