### ISSUE TITLE
Spotbugs Plugin Throwing Exception

### ISSUE THREAD

**Issue by mistermage** [gradle/gradle#12022]
When applying the 'Spotbugs' plugin we shouldn't be throwing an exception when no classes are provided.

### Expected Behavior
When performing a 'spotbugsSource' task when the source set has no source the spotbugs task ought to be skipped with 'NO-SOURCE' result.

### Current Behavior
The spotbugs plugin blows up due to the implementation of the 'SpotBugsSpecBuilder' class (line 48). 

### Context
I am configuring a suite of plugins for internal use at my company and I was strategically applying the spotbugs plugin to a project who happened to have no source in a particular source set.

### Steps to Reproduce 
1. Configure a gradle project
2. Apply the 'java' and 'spotbugs' plugin to it
3. Ensure there is no source in a source set
4. Run the 'spotbugsSource' task for said source set

### Your Environment
Gradle Version: 6.0.1

### Extra info:
Spotbugs has a cli flag 'noClassOk' as found here:
https://spotbugs.readthedocs.io/en/stable/running.html#project-configuration-options

I would assume that you could remove the exception being thrown and employ their cli flag when it comes time to execute the spotbugs task.

**Comment by rpalcolea** [comment]
This seems more suitable for https://github.com/spotbugs/spotbugs-gradle-plugin since spotbugs is not part of Gradle core

**Comment by mistermage** [comment]
> This seems more suitable for https://github.com/spotbugs/spotbugs-gradle-plugin since spotbugs is not part of Gradle core

This is very true. I was thinking about other prepackaged plugins like Checkstyle while I wrote this. I'll take it to their repo, thank you!
