### ISSUE TITLE
The GroovyDoc task should support the 'nomainforscripts' option

### ISSUE THREAD

**Issue by Cliabhach** [gradle/gradle#12049]
### Expected Behavior
The GroovyDoc task should allow configuration that disables the generation of docs for the `main` method. With that option, the documentation output for many Gradle scripts would look a little clearer.

### Current Behavior
The GroovyDoc task delegates to an internal class called [AntGroovydoc](https://github.com/gradle/gradle/blob/15bbe86d054fb/subprojects/language-groovy/src/main/java/org/gradle/api/internal/tasks/AntGroovydoc.java). Currently, there is no way to add custom properties to the Map defined on line 77 of that file, which means that a user's gradle script has no way of passing parameters like `nomainforscripts` to the GroovyDoc tool.

### Context
This all relates to the [`GroovyDoc` task](https://github.com/gradle/gradle/blob/15bbe86d054fb/subprojects/language-groovy/src/main/java/org/gradle/api/tasks/javadoc/Groovydoc.java) added by the 'groovy' plugin. There is a feature in the base GroovyDoc tool (as described in the [official docs](https://github.com/apache/groovy/blob/GROOVY_2_5_7/subprojects/groovy-groovydoc/src/spec/doc/groovydoc.adoc)) which makes the documentation generation skip over the `public static void main` method that all script files offer by default.

When I generate the documentation for my Groovy-related projects, I aim to exclude methods (like `main`) that distract from the purpose of said projects. Propagating this flag would let me switch from using a command-line invocation of `groovydoc` to using the very nice DSL offered by Gradle's plugin.

**Comment by Cliabhach** [comment]
Shoot, let me fix that

**Comment by chess-levin** [comment]
I also want use that feature from the plugin dsl.

**Comment by solvingj** [comment]
+1 i need this
