### ISSUE TITLE
JPMS problem with gradle-api-6.1.1.jar

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#12047]
There is a JPMS problem with gradle-api-6.1.1.jar:

The following `jdeps` command line (using OpenJDK 13.0.1):

```bash
jdeps -v --module-path ~/.gradle/caches/6.1.1/generated-gradle-jars/gradle-api-6.1.1.jar some.jar
```

Outputs the following error:

```
Error: Module gradle.api contains package org.w3c.dom.stylesheets, module jdk.xml.dom exports package org.w3c.dom.stylesheets to gradle.api
```

`org.w3c.dom.stylesheets` has been included in the JDK since Java 1.4.

Is is possible to remove it from gradle-api-*.jar?

If not, is there any way around this JPMS issue?

**Comment by ljacomet** [comment]
Thanks for the report.

While I agree this needs to be fixed, the priority is hard to assess.
Could you share how and why you need `gradle-api-*.jar` to be a valid on the module path?

**Comment by rgoldberg** [comment]
I opened #10408 a while ago.

I noticed from some other issue that the cause of #10408 seem to be fixed, so I tried the `jdeps` command line to verify that.

I no longer got the error from #10408, but I got this new error, so I figured I'd report it.

Currently, I can't remember exactly why I needed `gradle-api-*.jar` to be modular.

Do you expect large problems from removing the package (& possibly others) from the jar?  Would those classes even get used, or would the JDK versions supersede them?  If the former, are they included to ensure that the same version of those classes are used by Gradle regardless of the JDK used with Gradle?

**Comment by cristatus** [comment]
I am facing a similar issue with a custom java gradle plugin project that uses `org.w3c.dom.Document` and other related classes.

**Comment by cristatus** [comment]
We have a custom gradle plugin as part of a multi-module project. Some how eclipse (latest with buildship) adds "gradle-api-*.jar" to the classpath of all other projects. Also, the plugin itself is using xml api so even moving the plugin as an independent project also doesn't work.

**Comment by cristatus** [comment]
IMO, all the non-gradle dependencies should be shaded when generating `gradle-api-*.jar`.

**Comment by ljacomet** [comment]
@donat Any chance we can help the buildship situation there?

As for the rest, there is no current plan on making Gradle jars valid JPMS modules.

**Comment by jjohannes** [comment]
Maybe you could use the compile classpath instead of the runtime classpath in Eclipse. Then the Gradle API should not leak everywhere. See: https://github.com/eclipse/buildship/issues/815#issuecomment-565408634

**Comment by ljacomet** [comment]
Closing as there are no changes planned on the Gradle side.

**Comment by rgoldberg** [comment]
@ljacomet

If you need to override the version supplied by the JDK, aren’t override mechanisms available?

If you need to supply the package to JREs, and if JREs don’t already include the package, is there any way of detecting that the package is missing, and only including it when it is missing?

If the above are possible, wouldn’t the package need to be in its own jar?

Is removing the package impossible, not worth the effort, prone to causing problems elsewhere, something else?
