### ISSUE TITLE
Support NIO Path as an alternative to IO File

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#1205]
### Expected Behavior
We should consider further usage for `Path`, such as a method to resolve to a `Path` instead of a `File` on `Project` and support in `FileCollection` and friends.

### Current Behavior
Thanks to @kelemen and his PR https://github.com/gradle/gradle/pull/813 we now support NIO Path inside `Project#file(...)`.

### Context
Some build master prefer using `Path` object and Gradle should handle them by avoiding unnecessary conversion.

**Comment by kelemen** [comment]
I would love to see a better `Path` support in Gradle (and help creating one). Though, I'm very unsure about what the best course of action would be to preserve backward compatibility.

Currently, the following things come to mind:

- Create another interface like `FileCollection` but for `Path` objects and start providing support for it everywhere (along with conversion methods). This seems to be extremely tedious and will even be a lot of extra burden forever.
- Wherever an instance of `FileCollection` is created (even if it is a wrapper), let the implementation also implement another interface which provides a `Path` view of the collection and tell its client if it is the preferred view.

Do you have any specific plan in mind? Also, as much as I have seen, Gradle does not seem to care about true backward compatibility in the sense that it often adds methods to some interfaces. So, can we add methods to `FileCollection` as well? If yes, then my 2nd proposal could be simplified.

**Comment by lacasseio** [comment]
From my understanding on the direction for this feature, it would be preferable to add the feature to existing interface. We can break this issue in smaller one to create distinct PR and avoid any stalled work.

Maybe @adammurdoch can comment on the various step this feature can take since the original proposition came from him.

**Comment by adammurdoch** [comment]
There are a bunch of options. I'd probably just add a method to `FileCollection` to allow you to view its contents as a collection of `Path` instances.

**Comment by kelemen** [comment]
Should there also be some way for a client of `FileCollection` to determine the "preferred" view? So, that it could choose the most efficient view (though I have a hard to time to believe that this would be any kind of performance bottle neck)

**Comment by adammurdoch** [comment]
I probably wouldn't bother until we have a real use case for it.

**Comment by kelemen** [comment]
Ok, I won't be around for a week from tomorrow. So, I will only be able to work on this issue after that, if that is good for you.

**Comment by kelemen** [comment]
I have pushed 27b90756da82c5348e15061f3d542fb7812c2f58 to my issue_1205 branch. Does this seem ok?

**Comment by kelemen** [comment]
There are a few inconveniences however

- *core* is set to source level = 1.6, and Idea complains about the usage of `Path`
- `org.gradle.util.Path` conflicts with nio `java.nio.file.Path`. This could be inconvenient in Gradle scripts because the former is automatically imported.

**Comment by adammurdoch** [comment]
> org.gradle.util.Path conflicts with nio java.nio.file.Path. This could be inconvenient in Gradle scripts because the former is automatically imported.

This we could potentially fix in 4.0. The classes in `org.gradle.util` aren't actually part of the public API but somehow ended up being automatically imported. So we could change this in 4.0. It's a breaking change but I don't think `org.gradle.util.Path` is very widely used in build scripts.

**Comment by kelemen** [comment]
I have opened PR #1279. which contains the changes (I have squashed the commits). Please, review it and tell me what is missing.
