### ISSUE TITLE
have 'Gradle Worker Daemon 1' forked processes respect GRADLE_OPTS or similar environment variable

### ISSUE THREAD

**Issue by pjfanning** [gradle/gradle#1206]
### Expected Behavior
I would like to be able to apply Xmx settings to Gradle forked processes.
I understand that using GRADLE_OPTS could affect users who rely on the existing behavior. Would it be possible to support an environment variable called GRADLE_FORKED_PROCESS_OPTS?
As described below, I did find a solution but it would be nice to have an env variable that could be used to cap JVM Xmx in forked processes. In practice, there can be many different gradle builds and concurrent builds running on a build server and it is difficult to ensure that all the gradle scripts have explicit Xmx settings for forked processes.

### Current Behavior
Currently, these forked processes are running with no Xmx setting and this means that processes that are running a lot of tests can use a lot of heap.
What I am seeing is similar to:
http://stackoverflow.com/questions/21906736/how-do-i-set-jvm-options-for-gradleworkermain

The affected JVM looks like:
62259867 46556 46552   0 10:29am ??         0:02.39 /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/pj.fanning/.gradle/caches/3.3/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Worker Daemon 1'

On further investigation, the issue appeared to come from the ScalaCompiler task.
This fixes the issue:
```
tasks.withType(ScalaCompile) {
    configure(scalaCompileOptions.forkOptions) {
        memoryMaximumSize = '1g'
    }
}
```

### Context
We have a jenkins server that runs many parallel builds and there can be multiple GradleWorkerMain JVMs that are using 8Gb of resident memory.
We are using Gradle 3.3 in most builds but some use Gradle 2.14.1 or older 2.x versions.

**Comment by oehme** [comment]
These settings can be applied through the build script and are best kept there, as each build will know best what settings are required for it. If all your projects are roughly the same size, you could write a little plugin that every project applies. You could also write an init script that is used on CI and ensures certain limits.

As you can see, there are many ways to solve this already, so we won't add another one.
