### ISSUE TITLE
The  codes run fine in eclipse but not in online compiler

### ISSUE THREAD

**Issue by nikilsss** [gradle/gradle#12077]
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Scanner;

public class Test{

	public static  void main(String[] args){
		Scanner in= new Scanner(System.in);
		int a= in.nextInt();
		Test t= new Test();
		ArrayList<LineSegment> lsa= new ArrayList<LineSegment>();
		ArrayList<LineSegment> currents= new ArrayList<LineSegment>();
		ArrayList<Points> psa= new ArrayList<Points>();
		for(int i=0;i<a;i++){
			String s= in.next();
			double x1=in.nextDouble();
			double y1=in.nextDouble();
			double x2=in.nextDouble();
			double y2=in.nextDouble();
			Points p= t.new Points(x1,y1);
			Points p2= t.new Points(x2,y2);
			LineSegment ls = t.new LineSegment(p ,p2,s);
			lsa.add(ls);
			psa.add(p);
			psa.add(p2);
		}
		//in.close();
		Collections.sort(psa,t.new PointCompare());

		for(int j=0;j<psa.size();j++){
			Event e = t.new Event(); 
			if (psa.get(j).segmentGetter(psa.get(j), lsa) != null) {
				if(psa.get(j).segmentGetter(psa.get(j), lsa).xpoint==psa.get(j) ){
					Collections.sort(psa,t.new PointCompare());
					LineSegment activated= psa.get(j).segmentGetter(psa.get(j), lsa);
					e.first(lsa,activated,psa,psa.get(j),currents);
				} else if(psa.get(j).segmentGetter(psa.get(j), lsa).ypoint==psa.get(j)){
					if (psa.get(j).segmentGetter(psa.get(j), lsa) != null) {
						LineSegment activated=  psa.get(j).segmentGetter(psa.get(j), lsa);
						e.second(lsa,activated,psa,psa.get(j),currents);
					}
				}else {
					if (psa.get(j).segmentGetter(psa.get(j), lsa) == null) {
						LineSegment activated=  psa.get(j).segmentGetter(psa.get(j), lsa);
						e.intersection(lsa,activated,psa,psa.get(j),currents);
					}
				}
				j--;
			}
		}

	}
	public class Points {
		double x,y;

		public Points(double x, double y) {
			super();
			this.x = x;
			this.y = y;
		}

		public LineSegment segmentGetter(Points s,ArrayList<LineSegment> lsaa){
			for(int i=0;i<lsaa.size();i++){
				if((lsaa.get(i).xpoint.x==s.x && lsaa.get(i).xpoint.y==s.y)||
						(lsaa.get(i).ypoint.x==s.x && lsaa.get(i).ypoint.y==s.y)){
					return lsaa.get(i);
				}
			}
			return null;

		}
	}
	public class PointCompare implements Comparator<Points> {

		public int compare(Points a, Points b) {
			if (a.y > b.y) {
				return -1;
			} else if (a.y < b.y) {
				return 1;
			} else {
				return 0;
			}
		}
	}
	public class Event{

		public void first(ArrayList<LineSegment> T,LineSegment current,ArrayList<Points> Q,
				Points pointsAdd,ArrayList<LineSegment> currents){
			Q.remove(pointsAdd);
			currents.add(current);
			for(int i=0;i<currents.size();i++){
				System.out.print(currents.get(i).alpha +" ");
			}
			System.out.println();
			for (int i=0;i<Q.size();i++){
				System.out.print(Q.get(i).x+" "+Q.get(i).y+" ");
			}
			System.out.println();
			for(int i=0;i<currents.size()-1;i++){
				Points currentPoint =current.Intersection(currents.get(i), currents.get(i+1));
				if (currentPoint != null) {
					Q.add(currentPoint);
				}
			}
			Collections.sort(Q,new PointCompare());

		}

		public void second(ArrayList<LineSegment> T,LineSegment current,ArrayList<Points> Q,
				Points pointsAdd,ArrayList<LineSegment> currents){
			Q.remove(pointsAdd);
			currents.add(current);
			for(int i=0;i<currents.size();i++){
				System.out.print(currents.get(i).alpha +" ");
			}
			System.out.println();
			for (int i=0;i<Q.size();i++){
				System.out.print(Q.get(i).x+" "+Q.get(i).y+" ");
			}
			System.out.println();
			Collections.sort(Q,new PointCompare());
		}

		public void intersection(ArrayList<LineSegment> T,LineSegment current,ArrayList<Points> Q,
				Points pointsAdd,ArrayList<LineSegment> currents){
			Q.remove(pointsAdd);
			for(int i=0;i<currents.size()-1;i++){
				Points currentPoint =current.Intersection(currents.get(i), currents.get(i+1));
				if (currentPoint != null) {
					Q.add(currentPoint);
				}
			}
			Collections.sort(Q,new PointCompare());
		}
	}

	public class LineSegment {

		Points xpoint,ypoint;
		String alpha;
		public LineSegment(Points xpoint, Points ypoint, String alpha) {
			this.xpoint = xpoint;
			this.ypoint = ypoint;
			this.alpha = alpha;
		}

		public Points Intersection(LineSegment x1 ,LineSegment y1){
			double  storeValue=(y1.ypoint.y-y1.xpoint.y)*(x1.ypoint.x-x1.xpoint.x)-(y1.ypoint.x-y1.xpoint.x)*(x1.ypoint.y-x1.xpoint.y);
			if(storeValue!=0.0){
				double s=((y1.ypoint.x-y1.xpoint.x)*(x1.xpoint.y-y1.xpoint.y)-(y1.ypoint.y-y1.xpoint.y)*(x1.xpoint.x-y1.xpoint.x))/storeValue;
				double s2=(x1.xpoint.x+s*(x1.ypoint.x-x1.xpoint.x));
				double s3=(x1.xpoint.y+s*(x1.ypoint.y-x1.xpoint.y));
				return new Points(s2,s3);
			}
			else
			{

				return null;
			}
		}
	}
}

what I get in online compiler  is 
$javac Test.java
$java -Xmx128M -Xms16M Test
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextInt(Scanner.java:2117)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at Test.main(Test.java:12)

**Comment by big-guy** [comment]
Hi @nikilsss 

This doesn't appear to be related to Gradle.  [Stackoverflow](https://stackoverflow.com/) might be a better place to ask your question.
