### ISSUE TITLE
Enable VFS retention for local builds only

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12087]
We should probably retire `org.gradle.unsafe.vfs.retention` system property and introduce `org.gradle.unsafe.file.watching`. (We could later promote this to `org.gradle.file.watching`, too.)

It could have three options:

- `disabled`: disabled
- `enabled`: enabled
- `local-only` enabled only if `CI` environment variable is not present

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
For dogfooding, we end up dropping the VFS on CI and enabling VFS retention via `gradle.properties`: https://github.com/gradle/gradle/pull/12170

**Comment by lptr** [comment]
We'll instead make first CI builds explicitly drop their VFS state and let VFS retention be enabled on CI as well. Subsequent CI builds on the same agent for the same commit will be able to reuse VFS state. The hope is that registering watchers and handling the events will be low enough in load that we can just leave it on.
