### ISSUE TITLE
Provide access to ExecOperations in a Settings plugin

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#12080]
### Expected Behavior

`ExecOperations` is available to a Settings plugin.

### Current Behavior

There's no equivalent of `Project.exec(Action)` on `Settings`. We can inject `ProcessOperations` but that's internal API.

### Context

 My goal is to use `exec(Action<? super ExecSpec>)` to invoke `git` to collect information that will be included in tags and custom values on a build scan. Doing this in a plugin will allow us to share common configuration across multiple projects built with Gradle.

**Comment by adammurdoch** [comment]
This will be available in Gradle 6.2.

**Comment by wilkinsona** [comment]
That was quick. Thanks very much!
