### ISSUE TITLE
Dark mode for HTML test report with @media (prefers-color-scheme: dark)

### ISSUE THREAD

**Issue by philippefichet** [gradle/gradle#12103]
W3C working on media queries level 5 (draft) which add @media/prefers-color-scheme.
Some browser already support @media/prefers-color-scheme (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#Browser_compatibility).
Can you upgrade css to support dark mode on HTML test report ?

### Expected Behavior
When dark mode is enabled, then the HTML test report must be in dark mode.

### Current Behavior
When dark mode is enabled, then the HTML test report is in light mode

### Context
The activation of the dark mode depends on the browser.
On Opera 66, in Settings, enable dark mode.
On Windows 10 and Firefox 72, put windows 10 in dark mode and restart Firefox
It's possible test HTML test report in dark mode with browser extension (like Stylus) on browser (tested on Firefox 72 and Opera 66).

Here is an example of a dark mode:
```
/* base-style.css */
@media (prefers-color-scheme: dark) {
    html {
      background: black;
    }
    body, a, a:visited {
        color: #a3a3a3;
    }
    #footer, #footer a {
        color: #cacaca;
    }
    ul.tabLinks li {
        border: solid 1px #cacaca;
        background-color: #151515;
    }
    ul.tabLinks li:hover {
        background-color: #383838;
    }
    ul.tabLinks li.selected {
        background-color: #002d32;
        border-color: #007987;
    }
    div.tab th, div.tab table {
        border-bottom: solid #d0d0d0 1px;
    }
    span.code pre {
        background-color: #0a0a0a;
        border: solid 1px #5f5f5f;
    }
}
/* style.css */
@media (prefers-color-scheme: dark) {
    .breadcrumbs, .breadcrumbs a {
        color: #9b9b9b;
    }
    #successRate, .summaryGroup {
        border: solid 2px #d0d0d0;
    }
    
    .success, .success a {
        color: #007900;
    }
    div.success, #successRate.success {
        background-color: #001c00;
        border-color: #007900;
    }
    .failures, .failures a {
        color: #a30000;
    }
    .skipped, .skipped a {
        color: #a26d13;
    }
    div.failures, #successRate.failures {
        background-color: #170000;
        border-color: #a30000;
    }
}
```

**Comment by big-guy** [comment]
@philippefichet would you be willing to submit a PR with those suggestions?

**Comment by philippefichet** [comment]
Unfortunately, when I try to build from the v6.1.1 tag with `gradlew.bat build`, I get the following error "Gradle build daemon has been stopped: JVM garbage collector thrashing and after running out of JVM memory".
I tried increasing the heap to 8192MB (`org.gradle.jvmargs=-Xmx8192m ...`) and disabling parallelization (`org.gradle.parallel=false`) in gradle.properties and buildSrc\gradle.properties , but I get the same error message.
I wouldn't be able to check my changes.
OS: Windows 10 Pro, CPU: AMD Ryzen 7 1700X 3.4 Ghz, Memory: 16 GB, JVM: AdoptOpenJDK\jdk-11.0.2+9

**Comment by big-guy** [comment]
Thanks @philippefichet - running `gradle build` is probably too much (we have tens of thousands of tests).

Could you try building a local installation and manually checking your changes with an example build? https://github.com/gradle/gradle#installing-from-source

**Comment by philippefichet** [comment]
Thanks :), I was wrongly thinking that `gradle build` was a prerequisite for `gradlew install`.
I created a pull request: https://github.com/gradle/gradle/pull/12177.
Thanks again :)

**Comment by bmuskalla** [comment]
@blindpirate Can this be closed?

**Comment by blindpirate** [comment]
Yes, sure. Thanks @bmuschko

**Comment by big-guy** [comment]
I think you mean @bmuskalla :)

**Comment by Zalewa** [comment]
Can this be reopened since the accepted PR was reverted here by @big-guy  https://github.com/gradle/gradle/commit/1f559e43e060e338773a14ec1d3ecd699a4f4cfb

I can't find explanation for this revert.

The entirety of my system is dark, but the test report is blasting my 👀 with bright white. I'd like to request the dark theme be brought back.

**Comment by jeremy-nocek-rp** [comment]
> Can this be reopened since the accepted PR was reverted here by [@big-guy](https://github.com/big-guy) [1f559e4](https://github.com/gradle/gradle/commit/1f559e43e060e338773a14ec1d3ecd699a4f4cfb)
> 
> I can't find explanation for this revert.
> 
> The entirety of my system is dark, but the test report is blasting my 👀 with bright white. I'd like to request the dark theme be brought back.

I second this. My eyes are suffering after opening a test report in a dark room, and I'm not sure I'll ever recover.

**Comment by carlspring** [comment]
Hi,
Any updates on this?
