### ISSUE TITLE
Jar manifest can't include archiveVersion from gradle.properties file

### ISSUE THREAD

**Issue by jentfoo** [gradle/gradle#12112]
I am currently trying to upgrade to gradle 6.1.1 for my project.  I have run into what appears to be a defect when updating from `version` to `archiveVersion`.  If `archiveVersion` is spefied using the `gradle.properties`, it can not be used in the jar manifest.

### Expected Behavior
I should be able to change from `version` to `archiveVersion`.

### Current Behavior & Steps to reproduce
This can be seen in the following branch doing `./gradlew jar`:
https://github.com/jentfoo/threadly/tree/gradle-6.1.1

Resulting output:
```
* What went wrong:
Execution failed for task ':jar'.
> Could not copy MANIFEST.MF to '/home/jent/code/workspace/threadly/build/tmp/jar/MANIFEST.MF'.
   > No value has been specified for this provider.

```

Manifest update: https://github.com/jentfoo/threadly/commit/4a3e494f74f740501adb350d49c33b07d9c05ad6#diff-89bac694ded5e34fb7dbe8a8cee2b372R33
gradle.properties update: https://github.com/jentfoo/threadly/commit/4a3e494f74f740501adb350d49c33b07d9c05ad6#diff-503f218d646c10f484fdc9d6315bf2e3L2

If you instead undo those two changes and use the deprecated `version`, the jar builds without error (only the expected deprecation warning).

Let me know what additional information I can provide to help.  Thank you!

**Comment by big-guy** [comment]
The deprecation was for the Jar task's version property and not the Project's version property.  By default, the Project's version property is used as the value for the Jar's version (and archiveVersion)'s value.  

So you shouldn't need to change `gradle.properties` to use archiveVersion since that's setting the Project's version property.

**Comment by jentfoo** [comment]
Thank you for the help, this is the direction I needed
