### ISSUE TITLE
Environment: Windows, Eclipse, Local Terminal - Console output is not readable 

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1212]
Original issue in Jira: https://issues.gradle.org/browse/GRADLE-3562

This was caused by a change in Jansi. It is unclear if it should be fixed on the Jansi or Eclipse Terminal side (or somewhere else). See discussion here:

- https://github.com/fusesource/jansi/issues/64
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=502134

**Comment by oehme** [comment]
Closing as it is not even clear whether this is an Eclipse, Jansi or Gradle issue. If it turns out to be a problem in Gradle, please reopen with more details.
