### ISSUE TITLE
Parsing gradle properties file with invalid syntax fails with unhelpful error message

### ISSUE THREAD

**Issue by zach-klippenstein** [gradle/gradle#12122]
### Expected Behavior
When parsing a `gradle.properties` file fails (e.g. due to bad characters as the result of an unresolved merge, `<<<<<<` etc), the gradle command should print the name of the file, and, ideally, the location in the file where the parsing failed.

### Current Behavior
The gradle command prints out this error message: `String index out of range: 0`

### Context
I ran into this issue here: https://github.com/square/workflow/issues/937
A hotfix branch was merged to master, causing a merge conflict in the root `gradle.properties` file where our version number is specified. Builds started failing with this mysterious error. Running with the `--debug` and `--stacktrace` flags only helped by indicating that the error was happening somewhere in the property processing.

**Comment by big-guy** [comment]
Thanks @zach-klippenstein - this'll be fixed in 6.3.

It was the `======` dividers that caused the failures.  This gets turned into a property with name "" (empty string) and value "=====".
