### ISSUE TITLE
Generated decorator for Task type that extends abstract Task type is incorrect

### ISSUE THREAD

**Issue by vierbergenlars** [gradle/gradle#12133]
It looks like that in certain constellations of Task classes, the decorator that is automatically generated is behaving incorrectly since Gradle 6.1.

### Expected Behavior

When creating a custom Task class, the behavior of getters with an implementation is not modified. The getter returns the value of the property.

### Current Behavior

Calling the getter on some custom Task classes returns a different instance than the property has. These instances are not linked to each other.
Making a modification through the instance returned by the getter does not affect the instance stored in the property, and results in an incorrect value being read in the task action.

### Context

I tested with multiple Gradle versions, including pre-releases. It was working as expected until Gradle 6.1-milestone-3 and broke in Gradle 6.1-RC-1.
With the reduced testcase listed below, I bisected the error down to 8d6f4b40f76a103466404984a36aae7240533836, which does seem to change some logic in the ClassGenerator.

<details>
<summary>git bisect log</summary>

```
git bisect start
# good: [b360d725d00cc62bad1e1f95f66077b18b5cf9a0] Rebaseline cold daemon on largeJavaMultiProject
git bisect good b360d725d00cc62bad1e1f95f66077b18b5cf9a0
# bad: [091da954cc24262bb056965f70f172e1e587e9ca] Re-add RegularFileSnapshot.getMetadata() (#11739)
git bisect bad 091da954cc24262bb056965f70f172e1e587e9ca
# good: [41b93f4417f54cd8853f9994d55b1b7818c94b65] Merge pull request #11586 from gradle/wolfs/architecture/more-memory
git bisect good 41b93f4417f54cd8853f9994d55b1b7818c94b65
# bad: [acdd99aeebcdd66ef10ddf112db1212e6a9543a0] Fix too many buckets issue
git bisect bad acdd99aeebcdd66ef10ddf112db1212e6a9543a0
# bad: [f3e87c7ac51853ed73600595e0c95ef84af2aa29] Merge pull request #11604 from gradle/wolfs/vfs/tooling-api-invalidation
git bisect bad f3e87c7ac51853ed73600595e0c95ef84af2aa29
# good: [0f0341236e25fe01a403b3994390616e311d6d78] Merge pull request #11543 from gradle/eskatos/kotlin-dsl/tapi-model-preserve-order
git bisect good 0f0341236e25fe01a403b3994390616e311d6d78
# bad: [3c20db9aa32375f74bdcd39212f14d428d112f90] Correctly filter buckets (#11645)
git bisect bad 3c20db9aa32375f74bdcd39212f14d428d112f90
# good: [67196a47a0c140a857feeaed19a51be0e7ea5c9c] Fix duplicate UUIDs in TC DSL (#11641)
git bisect good 67196a47a0c140a857feeaed19a51be0e7ea5c9c
# bad: [24d920fd87c224e2d4e5dd88a81a1041a75657d9] Fix Groovy AST test cases for ancient versions of Groovy
git bisect bad 24d920fd87c224e2d4e5dd88a81a1041a75657d9
# bad: [5977d816ad4cbf8b0b66b75b6449c73b9712d29e] Fix typo
git bisect bad 5977d816ad4cbf8b0b66b75b6449c73b9712d29e
# bad: [8d6f4b40f76a103466404984a36aae7240533836] Fix convention mapping applied to a property with a setter with a covariant return type.
git bisect bad 8d6f4b40f76a103466404984a36aae7240533836
# first bad commit: [8d6f4b40f76a103466404984a36aae7240533836] Fix convention mapping applied to a property with a setter with a covariant return type.
```
</details>

### Steps to Reproduce 

https://github.com/vierbergenlars/gradle-reproducer-12133

Run `./gradlew applyAlfrescoAmp` to reproduce the issue (the task throws an exception when its input is unexpectedly empty).
Downgrade Gradle to 6.0.1, and the issue is not present.

### Your Environment

https://scans.gradle.com/s/z47e5wymzdnb2

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/12158
