### ISSUE TITLE
The `clean` task does not report changes to VFS

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12134]
The `CachedPathSensitivityIntegrationTest` tests fail on Windows (and the failure is masked by a VFS drop (see https://github.com/gradle/gradle/issues/11836#issuecomment-582619833) on macOS) because the `clean` builds in the middle of the tests do not properly report changes to the VFS.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
Note that it is not "the" `clean` task, but the way the ad-hoc clean task is added in `CachedPathSensitivityIntegrationTest`: https://github.com/gradle/gradle/blob/55f05f7d28b0c3cf66603895fce8ef768bee7222/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedPathSensitivityIntegrationTest.groovy#L34-L38

Replacing this task by applying the `base` plugin should fix the test.

**Comment by lptr** [comment]
> Note that it is not "the" `clean` task, but the way the ad-hoc clean task is added in `CachedPathSensitivityIntegrationTest`:

OK. I added https://github.com/gradle/gradle/issues/12140 to handle this case better.
