### ISSUE TITLE
Fix `PlayContinuousBuildReloadWaitingIntegrationTest` with VFS retention

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12136]
`wait for changes to be built when a request comes in during initial app startup and there are pending changes` currently fails on Windows (and probably would fail on macOS if it weren't for #11836). Fix this.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
See https://github.com/gradle/gradle/issues/11849

**Comment by wolfs** [comment]
The underlying issue here is https://github.com/gradle/gradle/issues/12163.
