### ISSUE TITLE
Support `SUBST` or disable its use with file watching

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12135]
`SUBST` is not currently supported and we fail the `SubstIntegrationTest` on Windows.

We should either add support for it or fail/degrade in a meaningful way.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
Seems like we fail on subst drives, since we try to watch the parent of the drive - which is `null`.

**Comment by wolfs** [comment]
Subst drives work if you run the build from the subst drive.
