### ISSUE TITLE
Allow model query to be done in parallel

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#12156]
Right now IDEs have to query models for each gradle projects in sequential order.

Allowing to query all projects in parallel would speed up Gradle import in IDEs (including android Studio).
Because dependency resolution would happen in parallel, this would also enable parallel download which would boost performance even more for initial import on a new machine.

**Comment by alllex** [comment]
Sorry for the late reply. This was delivered in Gradle 6.8 with the `BuildController.run(..)` method.

See the relevant docs here:
- https://docs.gradle.org/current/javadoc/org/gradle/tooling/BuildController.html#run(java.util.Collection)
