### ISSUE TITLE
Gradle project selection

### ISSUE THREAD

**Issue by aeiplatform** [gradle/gradle#12153]
Why is project generating?

- > Applying dependency management to configuration 'TASK' in project 'ALL INCLUDED'

- >\> Configure project :N
  > Evaluating project ':ANY' using build file...

For: `./gradlew :ANY` if they are not relevant in the statement

**:** should indicate module selection
**ANY** would select task for execution

**Comment by big-guy** [comment]
I'm not 100% sure what you're asking/saying, but Gradle evaluates all projects, even if there are no tasks to execute for the project.

**Comment by aeiplatform** [comment]
That just doesn't seem right to load configuration and evaluation for semantic graph of modules which won't be even used.
I'm just saying it would definitely save memory, cache hits and build time for huge multi-modular projects.
