### ISSUE TITLE
Use of annotation processors forces unnecessary recompile

### ISSUE THREAD

**Issue by justin-michel-boeing** [gradle/gradle#12150]
We're using [Micronaut ](https://micronaut.io/documentation.html)in our project, and noticed that any change to a file in a project results in recompilation of 41 classes. 

Here is the relevant part of `gradle --info build`

```
> Task :framework:compileJava
Compiling with JDK Java compiler API.
Incremental compilation of 41 classes completed in 18.497 secs.
```

In this case, we made a trivial change to the private implementation details of a single class, but it triggered some kind of work for a 40 unrelated classes that had Micronaut annotations.

I'm not sure if this is a bug with Micronaut, Gradle, or just expected behavior, but it would be really nice to avoid 18 seconds compilation when changing an unrelated file. To be clear the Micronaut annotations are used in other java files that happen to be in the same project, not on the file that was changed. 

Btw, we're also affected by the following issue due to the 21,000 constants in our project.
[Make incremental compile faster on constant changes #6482](https://github.com/gradle/gradle/issues/6482)

Micronaut: 1.3.0 
Gradle: 6.1.1

**Comment by rpalcolea** [comment]
maybe a leftover from https://github.com/micronaut-projects/micronaut-core/issues/2718 ?

**Comment by melix** [comment]
@rpalcolea yes, that's what I had in mind too

**Comment by ljacomet** [comment]
It is a Micronaut issue which needs to be fixed there.
If you can show this has to be fixed in Gradle, please re-open.

**Comment by graemerocher** [comment]
So can you guys please explain why this is a Micronaut issue? The fix for https://github.com/micronaut-projects/micronaut-core/issues/2718 has already been applied following @oehme's advice. What is it that the Micronaut processor is doing wrong now to upset Gradle?
