### ISSUE TITLE
gradle-tooling-api JAR with valid OSGi MANIFEST

### ISSUE THREAD

**Issue by vorburger** [gradle/gradle#1216]
### Expected Behavior
In an ideal world, the gradle-tooling-api JAR should have a MANIFEST.MF making it a valid OSGi bundle itself.

### Current Behavior
gradle-tooling-api JAR's MANIFEST.MF is not a 3-line non-OSGi compliant quasi empty one.

### Context
I've embedded Gradle using the Tooling API into an OSGi bundle; in https://github.com/vorburger/ch.vorburger.osgi.gradle, for https://github.com/vorburger/ch.vorburger.minecraft.osgi.

Because gradle-tooling-api JAR does not currently have a valid OSGi MANIFEST, I've re-packaged it myself so that it has one, see https://github.com/vorburger/ch.vorburger.osgi.gradle/tree/master/org.gradle.tooling.osgi for how-to (needs https://github.com/vorburger/ch.vorburger.osgi.gradle/blob/master/build.gradle parent, of course).

[EmbeddedGradleToolingAPITest](https://github.com/vorburger/ch.vorburger.osgi.gradle/blob/master/org.gradle.tooling.osgi.test/src/test/java/org/gradle/tooling/osgi/test/EmbeddedGradleToolingAPITest.java) is the test for it (using Pax Exam for OSGi integration testing).

Please note that this re-packaging part in itself is technically unrelated to the extended functionality of the coe in [ch.vorburger.osgi.gradle](https://github.com/vorburger/ch.vorburger.osgi.gradle/tree/master/ch.vorburger.osgi.gradle/src/main/java/ch/vorburger/osgi/gradle), notably the [SourceInstallService](https://github.com/vorburger/ch.vorburger.osgi.gradle/blob/master/ch.vorburger.osgi.gradle/src/main/java/ch/vorburger/osgi/gradle/SourceInstallService.java); this issue is merely only that it would be "handy" if future versions of the gradle-tooling-api JAR were published by you upstream at source with a valid OSGi MANIFEST (i.e. ignore the rest of my project).

Please let me know if a Pull Request for this would be potentially of interest.

Feel free to close if N/A - no offense taken.

**Comment by vorburger** [comment]
Hi @oehme & @etiennestuder - FYI this issue, in case of interest to you.

**Comment by oehme** [comment]
Hey Michael,

you can get the osgi version of the TAPI jar from the Buildship update sites.

That being said, we do plan to add a proper manifest to the one published to our Maven repositories too. So if you'd like to give that a shot, it would be a welcome contribution.

**Comment by vorburger** [comment]
@oehme would a contribution basically just porting my approach as-is be OK? Perhaps you could have a quick peek at it confirm. So it's based on a bnd.bnd and using the BND plugin biz.aQute.bnd.builder... I'm asking ahead just to make sure that I don't put in this work to then hear afterwards something like e.g. "but we don't want to have to run 3rd-party Gradle plugins such as BND as part of our core build", kind of thing - so worth to clarify here before actual PR.

**Comment by oehme** [comment]
I'm not sure what bnd does for us here. Afaik you basically specified the whole manifest content by hand in the bnd file. Seems like we could just write the manifest directly.

**Comment by vorburger** [comment]
@oehme I would argue that https://github.com/vorburger/ch.vorburger.osgi.gradle/blob/master/org.gradle.tooling.osgi/bnd.bnd is more readable and maintainable than https://gist.github.com/vorburger/0cf2fd2d74ad9997ce2c0e7e4f7d5797 ? ;-) 

Also running BND to gen. the MANIFEST would let it perform validation and sanity checking of the Manifest instructions and resulting bundle, whereas keeping a verbatim literal full one in SCM and copying it into the JAR would be much more error prone. 

It's also real easy to run it... just in case you've ever looked at e.g. that [OSGi enRoute](http://enroute.osgi.org) stuff, and may be thinking of and concerned about how they have those funky "workspaces" defined there to build anything, rest assured that's not required here; this really is just about an `apply plugin: 'biz.aQute.bnd.builder'`.

**Comment by oehme** [comment]
Fair enough, as long as the bnd plugin doesn't use Gradle internals it should be fine (we build Gradle with the latest snapshot of Gradle).

There should be no apache commons imports btw, the only dependency is slf4j-api. Also, I don't understand what the "private package" directive is for. We don't have it in our current manifest so we probably don't need that.

Please use our existing [manifest](http://download.eclipse.org/buildship/updates/e46/releases/2.x/2.0.0.v20170111-1029/plugins/org.gradle.toolingapi_3.3.0.v20170103170240.jar) for reference.

**Comment by oehme** [comment]
Closing as there was no further activity.
