### ISSUE TITLE
Signing via GnupgSignatory is broken for multi-module builds

### ISSUE THREAD

**Issue by MariusVolkhart** [gradle/gradle#12167]
Using the `Signing` plugin [configured to use the gpg-agent](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:using_gpg_agent), when performing signing of a multi-module project **in parallel**, some `signXYZ` tasks fail with the error message `gpg: signing failed: Cannot allocate memory`.

### Expected Behavior
I expect that running `./gradlew --parallel signXYZ` will sign all of the projects. I expect that running `./gradlew subprojectA:signXYZ` will sign just `subprojectA`.

### Current Behavior
When running `./gradlew --parallel signXYZ`, the error message `gpg: signing failed: Cannot allocate memory` is printed twice to `system::error`, and some `signXYZ` task reports a failure with the message `Process 'command 'gpg2'' finished with non-zero exit value 2`.

When running `./gradlew subprojectA:signXYZ`, signing completes without incident.

### Context
This issue affects me because I am using the `signing` plugin in conjunction with the `maven-publish` to publish a multi-module project to Maven Central, and artifacts submitted to Central must be signed. The project is configured to use parallel builds by default.

I am using the `gpg-agent` because leaving the password for the signing key sitting in a properties file on my hard disk is a security concern.

### Steps to Reproduce 
A reproducible project is available at https://github.com/pkware/truth-android/tree/mv/gpg

Be sure to use the `mv/gpg` branch.

from the command line, run `./gradlew signMavenAndroidPublication`. You'll probably need to change the line `signing.gnupg.keyName=4DE4D53B` in the root `gradle.properties` to use a PGP key of your own.

### Your Environment
GPG Tools: 1.5.1

Build scan URL: https://scans.gradle.com/s/p2uttrxf44op6

**Comment by MariusVolkhart** [comment]
# Workaround
The workaround, in case other run into this, is to not run the build in parallel. `--no-parallel` on the command line during signing/publish tasks seems to do the trick.

**Comment by JavierSegoviaCordoba** [comment]
The workaround is working but, after caching, publishing would take around 5 seconds and now takes almost 1 minute.

I am using `useGpgCmd()`, `useInMemoryPgpKeys(...)` has this problem too?

**Comment by marcphilipp** [comment]
I also just ran into this. Hacky workaround:

```kotlin
val gpgAgentLock: ReentrantLock by rootProject.extra { ReentrantLock() }

tasks.withType<Sign>().configureEach {
	doFirst {
		require(gpgAgentLock.tryLock(15, SECONDS)) {
			"Did not manage to acquire GPG lock within timeout"
		}
	}
	doLast {
		gpgAgentLock.unlock()
	}
}
```

**Comment by marcphilipp** [comment]
I did a bit of research and came across this issue: https://dev.gnupg.org/T4255

It states the mitigation is to add `auto-expand-secmem` to `~/.gnupg/gpg-agent.conf`. After doing so and stopping all running `gpg-agent` processes, it worked for me. Therefore, I'm closing this issue since it's a GnuPG issue.
