### ISSUE TITLE
"Upgrade with the Gradle Wrapper" doesn't work if older daemon version already running (Windows)

### ISSUE THREAD

**Issue by IanKemp** [gradle/gradle#12160]
### Expected Behavior
Attempting to upgrade Gradle by following the instructions at [Installation > Upgrade with the Gradle Wrapper](https://gradle.org/install/#with-the-gradle-wrapper) succeeds.

### Current Behavior
Attempting to upgrade Gradle by following the aforementioned instructions fails if an older version of the daemon is running, and that version does not support the currently installed JDK version.

### Context
I'm upgrading an application to JDK 13, and to do so need to upgrade the Gradle version.

### Steps to Reproduce 
The project currently supports JDK 12, so it references Gradle 5.6.3, and when I run the build the first time it fails because I have JDK 13 installed, which Gradle 5.6.3 doesn't know about:

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.
e > Compiling sep
* What went wrong:
Could not open settings remapped class cache for 2h1x2113elpoltn2uv9vmb4ok (C:\Users\IanKemp\.gradle\caches\5.6.3\scripts-remapped\settings_58j5re9wij63rbk1h7itmn3de\2h1x2113elpoltn2uv9vmb4ok\settings72bd3ee34b98ea3cc794dbe5b6aad667).
> Could not open settings generic class cache for settings file 'C:\Work\foo\bar\android\settings.gradle' (C:\Users\IanKemp\.gradle\caches\5.6.3\scripts\2h1x2113elpoltn2uv9vmb4ok\settings\settings72bd3ee34b98ea3cc794dbe5b6aad667).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57
```

Hence I follow the aforementioned installation instructions and run:

```
> .\android\gradlew wrapper --gradle-version=6.1.1 --distribution-type=all
```

to upgrade to a Gradle version that is JDK 13-aware, but this fails with the exact same error because the old 5.6.3 daemon is currently running:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings remapped class cache for 2h1x2113elpoltn2uv9vmb4ok (C:\Users\IanKemp\.gradle\caches\5.6.3\scripts-remapped\settings_58j5re9wij63rbk1h7itmn3de\2h1x2113elpoltn2uv9vmb4ok\settings72bd3ee34b98ea3cc794dbe5b6aad667).
> Could not open settings generic class cache for settings file 'C:\Work\foo\bar\android\settings.gradle' (C:\Users\IanKemp\.gradle\caches\5.6.3\scripts\2h1x2113elpoltn2uv9vmb4ok\settings\settings72bd3ee34b98ea3cc794dbe5b6aad667).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57
```

However, after I manually edit `android/gradle/wrapper/gradle-wrapper.properties` and set the `distributionUrl` to `https\://services.gradle.org/distributions/gradle-6.1.1-all.zip`, the next build downloads the updated wrapper and uses it, thus succeeding.

### Your Environment
Windows 10 version 1909 (Build 18363.592)

java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

**Comment by big-guy** [comment]
This might be expected.  Did you update to JDK13 first, try to run `gradle wrapper ...` and then downgrade to JDK12 where you see the same failure?

`./gradlew wrapper ...` runs the "old" version of Gradle (not the version you're trying to upgrade to), so if the old version of Gradle doesn't support the version of JDK you're trying to use, it'll fail.

**Comment by IanKemp** [comment]
> This might be expected. Did you update to JDK13 first, try to run gradle wrapper ... and then downgrade to JDK12 where you see the same failure?

JDK12 has never been installed on this machine.

> `./gradlew wrapper ...` runs the "old" version of Gradle (not the version you're trying to upgrade to), so if the old version of Gradle doesn't support the version of JDK you're trying to use, it'll fail.

The issue is this:

```
FAILURE: Build failed with an exception.
```

when I run `gradlew wrapper --gradle-version=6.1.1`. That tells me that Gradle is trying to run the build, which is explicitly **not what** I told it to do - I told it to update itself, and nothing more.

In other words, it's either ignoring the `--gradle-version` argument, or it's trying to do other things first, and falling over - either of which would be incorrect.

**Comment by big-guy** [comment]
> That tells me that Gradle is trying to run the build, which is explicitly not what I told it to do - I told it to update itself, and nothing more.

`gradlew wrapper` still requires the build to be configured because additional configuration for the wrapper can be in the build itself.  Even if that wasn't the case, you're still running Gradle 5.6.3 to do the update, which may not support JDK13.  The `gradle-wrapper.jar` can only read the properties file, not update it.

This is the way things are intended to work, but I understand it can be annoying.  The alternatives are to either 1) run with JDK12 so 5.6.3 can do the update to 6.1.1 or 2) manually update to 6.1.1 and run `gradlew wrapper` afterwards.
