### ISSUE TITLE
`GradleBuildTaskIntegrationTest.can run multiple GradleBuild tasks concurrently` fails with VFS retention

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#12169]
The test uses a build with `GradleBuild` to invoke the same build twice. I am not sure why this fails, maybe because we use the isolated daemons.

This may be related to #11837.

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
@wolfs What platform does this fail on? Do we have build scans or TeamCity logs maybe?

**Comment by wolfs** [comment]
Here is a build scan: https://e.grdev.net/s/3kvitigj6gio6/tests/jwlujjaynfeci-4iu77xbq336sk

Looks like the test only failed on `windows41` twice, once [for VFS retention](https://e.grdev.net/s/3kvitigj6gio6/tests/jwlujjaynfeci-4iu77xbq336sk) and once [without](https://e.grdev.net/s/pgtgsapjkdwyy/tests/by-project?search=can+run+multiple+GradleBuild+tasks+concurrently).

Let's close this, it looks more like an environment issue.
