### ISSUE TITLE
Throw an exception when building a Java Platform if dependency constraints are not resolvable

### ISSUE THREAD

**Issue by Thunderforge** [gradle/gradle#12175]
Say that I have a [Java Platform](https://docs.gradle.org/current/userguide/java_platform_plugin.html#java_platform_plugin) where I define api constraints like so:

```
dependencies {
    constraints {
        api 'commons-httpclient:commons-httpclient3.1'
        runtime 'org.postgresql:postgresql:422.5'
    }
}
```

I run `gradlew build publish`.

### Expected Behavior

The command should fail because the two dependencies are not resolvable. 

In this particular case, I should be informed that `commons-httpclient3.1` is not a valid module name (there is a missing colon between name and version) and `postgresql` does not have a version `422.5`.

### Current Behavior
The command succeeds, and consumers of my Java Platform are required to debug that the constraints are not valid because they cannot be resolved.

In the case of a missing colon like with `commons-httpclient3.1`, consumers receive a `NullPointerException` when trying to build. The error below appears when `myApp` is a consumer of `my-platform`.

```
> Task :myApp:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myApp:compileJava'.
> Could not resolve all files for configuration ':myApp:compileClasspath'.
   > Could not resolve com.example:my-platform:1.0-SNAPSHOT.
     Required by:
         project :myApp
      > java.lang.NullPointerException (no error message)
   > Could not find org.postgresql:postgresql:.
     Required by:
         project :myApp
```

### Context
Our organization has adopted a Java platform to manage shared dependencies between projects. This has been helpful, but we've had developers who have incorrectly added a non-existent version of a dependency (after being sure that it would work due to `gradlew build` completing successfully) and then had several downstream projects fail, affecting other developers.

We also ran into the second situation of a missing colon and were baffled that downstream projects were getting `NullPointerException`s. We initially thought that there was some sort of bizarre caching situation going on and purged cache before someone suggested looking at this platform. At first, we thought everything was okay, until finally one eagle-eyed developer spotted the missing colon. The `NullPointerException` gave no hints that the platform was what was the issue.

In both cases, throwing an exception when running `gradlew build` on the Java platform would have prevented bad code from being committed and affecting projects that consume the platform.

**Comment by ljacomet** [comment]
While I understand what you are asking, this is not something that should be done by default. There are valid use cases where the published platform may reference things to be published later.

Instead you could have a task dedicated to testing your platform. You would look at all constraints declared in `runtimeElements` with something like `configurations.runtimeElements.allConstraints` and add those as dependencies on a custom configuration. That custom configuration would be created to have the same attributes as the `runtimeClasspath` form the `java-library` plugin.
And you would then attempt to resolve it. Any failure in resolution would indicate an issue with the platform constraints.

**Comment by Thunderforge** [comment]
@ljacomet You make a good point that it may be the use case that a platform might want to reference unpublished dependencies. Although I wonder why you would be publishing such a platform if it’s not ready to be consumed.

That said, I do think that real-world projects (where the platform is published as opposed to being a sub project) have a need to validate that the current platform dependencies are valid, lest they run into issues like I described. You suggested a workaround with a custom task, but surely others have this problem and would benefit from a standardized solution.

If failing the build is not desirable, perhaps we could at least have a warning?

**Comment by ljacomet** [comment]
No work is planned on this. The flexibility of constraints make it hard to validate in general.
