### ISSUE TITLE
Check why Windows VFS tests cannot start watching certain directories

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12179]
This came out of `InstantExecutionIntegrationTest`, but it's likely that it happens with other tests silently, too, as `InstantExecutionIntegrationTest` is one of the very few that exhaustively check their outputs.

We could add a check to `VfsRetentionGradleExecuter` to scrape the output for error reports like this (like we do with deprecation warnings).

https://e.grdev.net/s/ivk3bivhnsrka/tests/2mly5dzorsp52-s4thxow2vp3yy

```text
Couldn't start watching 0000000000000A1C for 'C:\tcagent1\work\a16b87e0a70f8c6e\subprojects\instant-execution\build\tmp\test files\InstantExecutionIntegrationTest\instant_execution_f...y_project\22rf1', error = 6
```

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
I think these are now solved.

**Comment by wolfs** [comment]
What was the reason why the directories couldn't be watched?

**Comment by lptr** [comment]
I don't remember, but have refactored the Windows code heavily since, and haven't seen these errors for a long time now.
