### ISSUE TITLE
DependencyHandler.kotlin returns Any instead of String and doesn't work with implementation taking dependencyConfiguration

### ISSUE THREAD

**Issue by darioseidl** [gradle/gradle#12172]
This is a very small issue, similar to https://github.com/gradle/gradle/issues/11956.

The `DependencyHandler.kotlin` helper returns `Any`, which works usually, because, for example, `DependencyHandler.implementation` also accepts `Any`. However, I just noticed, when you add `dependencyConfiguration` to the `dependency`, it won't work anymore, because the latter only accepts a `String`. It seems to me that `DependencyHandler.kotlin` could simply return a `String` instead of `Any` to make this work.

### Expected Behavior

The following should work:
```
    implementation(kotlin("reflect")) {
        because("reason")
    }
If `kotlin` would return a `String` it would work.
```

### Current Behavior
A type cast is needed:
```
    implementation(kotlin("reflect") as String) {
        because("reason")
    }
```

### Your Environment

Gradle 6.1.

**Comment by ljacomet** [comment]
@melix Another issue that relates to what you looked at recently

**Comment by ov7a** [comment]
Sorry for the late reply

This is still a valid issue:
* https://github.com/gradle/gradle/blob/f475d38add16bda7b0c2b986dd5e20bc5bf5f648/build-logic/kotlin-dsl/src/main/kotlin/gradlebuild/kotlindsl/generator/tasks/GenerateKotlinDependencyExtensions.kt#L93

**Comment by donat** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
***

Alternatives for fixing this issue:
- Return a String instead of Any from the generated method
```
fun DependencyHandler.kotlin(module: String, version: String? = null): String =
    "org.jetbrains.kotlin:kotlin-$module${version?.let { ":$version" } ?: ""}"
```
- Return a `Dependency` :
```
fun DependencyHandler.kotlin(module: String, version: String? = null): Dependency =
    create("org.jetbrains.kotlin:kotlin-$module${version?.let { ":$version" } ?: ""}")
```

We favour the second option.

**Comment by donat** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by sarosh-engineer** [comment]
Hi @donat , I'm planning to work on this.
Thanks!

**Comment by tomatotomata** [comment]
I was looking at #12172 and the `Dependency` return type suggestion looks like the better fit for Gradle's dependency-configuration overloads. I’m going to trace the generated Kotlin extension and its existing integration coverage, then make the smallest generator change so `kotlin(...)` and `embeddedKotlin(...)` return `Dependency` consistently, with a regression showing `implementation(kotlin("reflect")) { because("...") }` works without a cast. I’ll keep the public behavior and version formatting unchanged, and I’ll include the required AI-use disclosure in the PR if I open one.
