### ISSUE TITLE
Gradle compares versions differently to Maven

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#1218]
See https://discuss.gradle.org/t/cannot-resolve-dependencies-that-are-resolved-by-maven/18894
Given version range for dependencies Maven sometimes finds a matching dependency, whereas Gradle doesn't. This is due to how Gradle compares dependencies.

Given the following build script:
```groovy
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'org.eclipse.scout.sdk.deps', name: 'org.eclipse.jface', version: '3.12.0.v20160518-1929'
}
```
Note that the pom of `org.eclipse.jface:3.12.0.v20160518-1929` has a dependency on `org.eclipse.scout.sdk.deps:org.eclipse.swt.win32.win32.x86:[3.105.0,3.105.1)` and the following version for `org.eclipse.swt.wind32.win32.x86` exists: `3.105.0.v20160603-0902`

### Expected Behavior
Dependency resolution succeeds and `org.eclipse.scout.sdk.deps:org.eclipse.swt.win32.win32.x86:3.105.0.v20160603-0902` is included as a transitive dependency.

### Current Behavior
Dependency resolution fails with
```
Could not find any version that matches org.eclipse.scout.sdk.deps:org.eclipse.swt.win32.win32.x86:[3.105.0,3.105.1).
  Versions that do not match:
      3.105.0.v20160603-0902
      3.104.0.v20150528-0211
```

### Context
Gradle should resolve dependency ranges the same way Maven does.

### Steps to Reproduce (for bugs)
For the steps to reproduce, see above. Here is a reprository exposing the bug: https://github.com/msridhar/gradleDependencyBug

### Your Environment
Gradle Version: 2.14.1
Operating System: Mac OS X 10.11.6 x86_64

**Comment by wolfs** [comment]
@msridhar I migrated this bug from [Jira](https://issues.gradle.org/browse/GRADLE-3529) to Github issues. Do you want to add something?

**Comment by msridhar** [comment]
No, this looks great!  Thanks for doing the migration!

**Comment by jjohannes** [comment]
Another incarnation of this issue: #1218

**Comment by ov7a** [comment]
This is still reproducible with Gradle 9.5.1

```
* What went wrong:
Execution failed for task ':resolve' (registered in build file 'build.gradle').
> Could not resolve all artifacts for configuration ':reproCfg'.
   > Could not find any version that matches org.eclipse.scout.sdk.deps:org.eclipse.swt.win32.win32.x86:[3.105.0,3.105.1).
     Versions that do not match:
       - 3.105.0.v20160603-0902
       - 3.104.0.v20150528-0211
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/scout/sdk/deps/org.eclipse.swt.win32.win32.x86/maven-metadata.xml
     Required by:
         root project 'repro' > org.eclipse.scout.sdk.deps:org.eclipse.jface:3.12.0.v20160518-1929
   > Could not find any version that matches org.eclipse.scout.sdk.deps:org.eclipse.core.commands:[3.8.0,3.8.1).
     Versions that do not match:
       - 3.8.0.v20160316-1921
       - 3.7.0.v20150422-0725
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/scout/sdk/deps/org.eclipse.core.commands/maven-metadata.xml
     Required by:
         root project 'repro' > org.eclipse.scout.sdk.deps:org.eclipse.jface:3.12.0.v20160518-1929
   > Could not find any version that matches org.eclipse.scout.sdk.deps:org.eclipse.equinox.common:[3.8.0,3.8.1).
     Versions that do not match:
       - 3.8.0.v20160509-1230
       - 3.7.0.v20150402-1709
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/scout/sdk/deps/org.eclipse.equinox.common/maven-metadata.xml
     Required by:
         root project 'repro' > org.eclipse.scout.sdk.deps:org.eclipse.jface:3.12.0.v20160518-1929
```
