### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by JIN-096** [gradle/gradle#12199]
### Expected Behavior

I follow your manual for update gradle version 6.1 to 6.1.1
But not upgrade version. just stay in 6.1
so using this string "wrapper --gradle-version 6.1.1", finally 
It will be upgrade.
### Current Behavior

But, The result is that,

> Task :printGlobalBuildInfo UP-TO-DATE
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.1.1
  OS Info               : Linux 4.15.0-76-generic (amd64)
  JDK Version           : 13 (Oracle Corporation 13.0.2 [Java HotSpot(TM) 64-Bit Server VM 13.0.2+8])
  JAVA_HOME             : /usr/lib/jvm/java-13-oracle
  Random Testing Seed   : 4F8E1F0E59E9932D
  In FIPS 140 mode      : false
=======================================

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
  

Also. i can see
./gradlew wrapper --gradle-version 6.1.1
Downloading https://services.gradle.org/distributions/gradle-6.1.1-all.zip
.............10%.............20%.............30%.............40%..............50%.............60%.............70%.............80%.............90%..............100%

Welcome to Gradle 6.1.1!

Here are the highlights of this release:
 - Reusable dependency cache
 - Configurable compilation order between Groovy/Kotlin/Java/Scala
 - New sample projects in Gradle's documentation

For more details see https://docs.gradle.org/6.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type ChecksumService using BuildSessionScopeServices.createChecksumService().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

### Your Environment

------------------------------------------------------------
Gradle 6.1
------------------------------------------------------------

Build time:   2020-01-15 23:56:46 UTC
Revision:     539d277fdba571ebcc9617a34329c83d7d2b259e

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Linux 4.15.0-76-generic amd64

**Comment by big-guy** [comment]
Could you try running with `--stacktrace`?  Usually problems that look like "Could not create service of type" are related to problems with creating files or permissions.
