### ISSUE TITLE
gradleApi() IDE indexing is broken with Gradle 6.2-rc-2

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#12198]
### Expected Behavior
I would expect Gradle APIs to continue showing up in the IDE

### Current Behavior
They no longer index when updating to Gradle 6.2-rc-2

### Context
It's an android gradle plugin, written in kotlin and using gradle kotlin dsl. It works fine from command line, but IDE is broken. If I switch branches back to gradle 6.1.1, it works fine again.

![image](https://user-images.githubusercontent.com/1361086/74304058-e0e01080-4d29-11ea-95e5-8c182e50e3a3.png)

### Steps to Reproduce 
Can repro on this branch with Android Studio 3.5.3: https://github.com/slackhq/keeper/tree/z/gradle62rc2

Open `InferAndroidTestKeepRules.kt` and observe that gradle APIs are all red in the IDE.

### Your Environment
Build scan URL: https://scans.gradle.com/s/mn2uemfpyv5yu

**Comment by big-guy** [comment]
Thanks @ZacSweers - We've backed these changes out for 6.2.  Could you give RC3 a try?

**Comment by ZacSweers** [comment]
Yep RC3 is working for me again, just updated the linked PR
