### ISSUE TITLE
Dependency refreshing takes a long time with GCS Maven Repository

### ISSUE THREAD

**Issue by Ranzdo** [gradle/gradle#12221]
When dependencies are refreshing with a GCS (Google Cloud Storage) Maven Repository, the process takes a long time since it tries to find all dependencies separately in GCS.

By "dependency refreshing", I don't mean a full refresh with "--refresh-dependencies", only the one that runs before every task (I think, I am not 100% how the gradle decides to check dependencies, could be our `resolutionStrategy.cacheChangingModulesFor 0, 'seconds'` for SNAPSHOT dependencies that makes it happen before every task).

I have identified that a solution is to fix a bug where a value in https://github.com/gradle/gradle/blob/master/subprojects/resources-gcs/src/main/java/org/gradle/internal/resource/transport/gcp/gcs/GcsClient.java#L143 is not null checked (Google APIs returns null instead of empty lists). When fixing this in a separate fork, the dependencies refreshes a lot faster and fixes this issue. I think the list call gets a null pointer exception and then the transport layer fallbacks to getting each dependency individually, which takes more time. I am not sure why it is requesting something that does not exist however, since we have a lot of files in the bucket & path we use.

### Expected Behavior
Running a task with a GCS Maven Repository does not have a 30 sec overhead of checking dependencies.

### Current Behavior
Running a task with a GCS Maven Repository have a 30 sec overhead of checking dependencies.

### Steps to Reproduce
1. Add a GCS Maven Repository like this gcs://<bucket_name>/<sub_folder>/ .
2. Run any task.
3. If it is not slow, add `
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
` and put some dependencies on `changing: true`

**Comment by ljacomet** [comment]
Would you consider providing a PR for that simple change?

**Comment by ljacomet** [comment]
PR has been merged, thank for the report and fix
