### ISSUE TITLE
Run soak tests with VFS retention enabled

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12227]
To shake out some of those pesky crashes.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
What we want to do is create a soak tests, where we run
- many builds with file changes in between the builds with VFS retention enabled
- have one daemon watching a project directory, and then have another daemon (maybe another version) run many builds on that project, so the first daemon needs to pick up many changes while idle.

**Comment by lptr** [comment]
Just a thought: for the second case we don’t need the changes to be effected by a Gradle daemon; we can simply modify a lot of files in the idle daemon’s project directory.
