### ISSUE TITLE
grpc dependency version constraint is not immutable for same version

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#12229]
[io.grpc:grpc-core:1.23.0](https://search.maven.org/artifact/io.grpc/grpc-core/1.23.0/jar) has a weird dependency on `grpc-api`, which uses square brackets but a single version nonetheless:

```xml
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-api</artifactId>
      <version>[1.23.0]</version>
      <scope>compile</scope>
    </dependency>
```

It seems this is the case for previous versions too.

In gradle however, we've noticed that this dependency sometimes gets interpreted as just `1.23.0`, causing the dependents of grpc-api to change, which in turn causes inconsistent lock files when using [gradle-consistent-versions](https://github.com/palantir/gradle-consistent-versions).

### Expected Behavior

Dependencies for a specific version of `io.grpc:grpc-core` should be stable and not change across different machines. I don't have an opinion on which constraint should be the "correct" one, as long as all invocations of gradle are consistent.

### Current Behavior

Different machines, especially those with non-fresh caches, resolve the dependency mentioned above as `[1.23.0]`, but with a fresh empty cache on CI for example, this dependency is always resolved as `1.23.0`.

I think this has only recently started happening, with 6.1.1 or possibly earlier as well. Can confirm this is still happening with 6.2-rc-1 as well.

### Context

This is causing people to be unable to satisfy gradle-consistent-versions's check on CI that the `versions.lock` file is up to date, even after running `--write-locks` locally.

The only solution so far is to wipe out grpc from the gradle caches:

```
find ~/.gradle/caches/ -path '*grpc*' -delete
```

### Steps to Reproduce 

Conflicting tars of `metadata-95` for grpc-core:

- [grpc-core-constraint-without-brackets.tar.gz](https://github.com/gradle/gradle/files/4214019/grpc-core-constraint-without-brackets.tar.gz)
- [grpc-core-constraint-with-brackets.tar.gz](https://github.com/gradle/gradle/files/4214020/grpc-core-constraint-with-brackets.tar.gz)

Both extracted after running with gradle 6.1.1.

### Your Environment

Build scan URL:

**Comment by dansanduleac** [comment]
Uploaded the conflicting metadata files.

**Comment by pnepywoda** [comment]
gradle-6.1.1 worked fine for me but broke in gradle-6.2
