### ISSUE TITLE
Gradle dependency not working

### ISSUE THREAD

**Issue by justin-michel-boeing** [gradle/gradle#12230]
I have java projects with a code generation tasks and their dependencies don't seem to be working properly. 

I have two subprojects that have code generation tasks defined within the subproject itself. 

proj1 has 
compileJava.dependsOn codeGen1

proj2 has
compileJava.dependsOn codeGen2

If I run `gradlew :proj1:test --dry-run`
then I get:
```
:proj1:codeGen1 SKIPPED
:proj1:compileJava SKIPPED
...
:proj2:compileJava SKIPPED
```
The opposite happens if I `gradlew :proj2:test`
```
:proj1:compileJava SKIPPED
...
:proj2:codeGen1 SKIPPED
:proj2:compileJava SKIPPED
```

So, even though both proj1 and proj2 have `compileJava dependsOn codeGen*`,  and compileJava is definitely a task that will run for both when testing either, gradle doesn't seem to calculate the correct dependencies. 

### Expected Behavior
compileJava.dependsOn codeGen should ensure that codeGen is run before compileJava whenever gradle determines that compileJava should be run.

### Current Behavior
The codeGen task for proj1 isn't even checked when running the tests for proj2. It's not being identified as a dependent task in the initialization phase. 

### Your Environment
Gradle 6.1.1
Java OpenJDK 8.0.232

**Comment by ljacomet** [comment]
Could you please provide a reproducer for this? or share more than snippets of your build script?

It feels like a basic feature would need to be broken for this to be possible, so this is much more likely to be something wrong in your build setup.

**Comment by justin-michel-boeing** [comment]
I will try to reproduce with a simpler example, but our build is "complicated". If it helps, I first ran into the problem where the Antlr plugin was failing when doing incremental compiles. It would build, then you'd make a minor change in an unrelated java file, and gradle would do an incremental compile but suddenly couldn't find the output from the antlr plugin. I think there is a separate issue reported from 2016 on this, but I can't seem to find it now. 
Anyway, I replaced the antlr plugin in the relevant sub-project build.gradle files with:
```
import java.nio.file.Paths

configurations {
    genDecoderTypes
}

dependencies {
    genDecoderTypes group: 'antlr', name: 'antlr', version: antlr2Version
}

// Use JavaExec instead of antrl plugin, because the latter prevents incremental compilation
task runAntlr(type:JavaExec) {
    inputs.dir "src/main/antlr/"
    def outDir = "$projectDir/build/generated/antlr/main/com/foo/bar/proj1/decoder/antlr/type/"
    outputs.dir outDir

    classpath = configurations.genDecoderTypes

    main = "antlr.Tool"

    args = [ "-o",  outDir, "src/main/antlr/com/foo/bar/proj1/decoder/antlr/type/type.g",
    ]

    outputs.upToDateWhen { Paths.get(outDir).toFile().exists()}
}

compileJava.dependsOn runAntlr

project.sourceSets.main.java.srcDirs(runAntlr.outputs)

```
