### ISSUE TITLE
Older version can not override version of dependency in BOM.

### ISSUE THREAD

**Issue by wreulicke** [gradle/gradle#12233]
We cannot use older version than version in BOM

example:
https://github.com/wreulicke/gradle-12233-reproduce

### Expected Behavior

We can override older version of dependency properly when we use dependency constraint by `platform("bom")`.

Older version of dependency can override version of dependencies in BOM.

```
dependencies {
  implementation platform('com.fasterxml.jackson:jackson-bom:2.9.7')
  // i expect we can downgrade version than bom
  implementation 'com.fasterxml.jackson.core:jackson-annotations:2.9.6' 
}
```

### Current Behavior

Older version of dependency **can not** override version of dependencies in BOM.

### Context
We try to migrate to gradle native bom from spring's dependency management plugin.
But, we cannot migrate without workaround.

* reproduce repository
https://github.com/wreulicke/gradle-12233-reproduce

## Workaround

Use `force`

```
  implementation 'org.elasticsearch.client:elasticsearch-rest-high-level-client:6.3.2', { force = true }
```

### Steps to Reproduce 

* clone repository
* cd jackson-bom && ./gradlew dependencies
* check that we can override version of jackson-annotation
* cd spring-boot-bom && ./gradlew dependencies
* check that we **can not** override version of jackson-annotation

### Your Environment

* jackson-bom
https://scans.gradle.com/s/2x77m23zo5e7a

* spring-boot
https://scans.gradle.com/s/c2fsgvanbwuhu

I tested with gradle 5.0, 5.1, 5.2, 6.0.1, 6.1.1.

**Comment by wreulicke** [comment]
I added more tests.
We can not upgrade elasticsearch dependencies...

```
  implementation platform("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE")
  // We cannot override dependencies!! Why !?!?!?!
  // I am not sure, but I seem that we can not override version of dependency for elasticsearch...
  implementation 'org.elasticsearch.client:elasticsearch-rest-high-level-client:6.3.2' 

  // We can override dependencies
  implementation 'com.fasterxml.jackson.core:jackson-core:2.10.2'
  // We can override dependencies
  implementation 'io.reactivex.rxjava2:rxjava:2.2.17'
  // We can override dependencies
  implementation 'org.hibernate:hibernate-core:5.4.11.Final'
```

**Comment by wreulicke** [comment]
I added more tests

```groovy
dependencies {
  implementation platform("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE")
  // older version can not override dependency
  implementation 'com.fasterxml.jackson.core:jackson-core:2.7.9'
}
```

**Comment by jjohannes** [comment]
@wreulicke if you want to _downgrade_ a version, you need to use _strict versions_.

In your example you can do:

```
dependencies {
  ...
  implementation 'com.fasterxml.jackson.core:jackson-core:2.7.9!!'
}
```

https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html

(Note: this works with Gradle 6+)

**Comment by wreulicke** [comment]
Thanks!!
I will try it!

**Comment by ljacomet** [comment]
Closing as a solution has been provided.
