### ISSUE TITLE
Field annotated with @Nested annotation incorrectly gets Property  is not annotated with an input or output annotation.

### ISSUE THREAD

**Issue by paulnuk** [gradle/gradle#12243]
See https://github.com/bmuschko/gradle-docker-plugin/issues/919 for the main issue and replication steps

According to the author:

"My guess is that Gradle doesn't discover this input/output annotations correctly. The field instruction is annotated with @Nested, however, it's not a class, it's an interface. FileInstruction is an implementation of that interface. I think that trips up Gradle's checks."

### Expected Behavior

Fields annotated with @Nested should not generate the warning
### Current Behavior

Running the task returns:

Property 'instructions.$3.file' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

**Comment by lptr** [comment]
I've answered on the linked issue.
