### ISSUE TITLE
unable to resolve class org.apache.ivy.core.settings.IvySettings

### ISSUE THREAD

**Issue by StevenMcWilliams** [gradle/gradle#12246]
When I add the line "import org.apache.ivy.core.settings.IvySettings" to my build.gradle file, then run any gradle task, it reports the following error against that new line: "unable to resolve class org.apache.ivy.core.settings.IvySettings".

### Expected Behavior

I expected gradle to find the IvySettings class in its classpath and not throw an error.

### Current Behavior

Currently it does not find the IvySettings class and reports the erorr: "unable to resolve class org.apache.ivy.core.settings.IvySettings"

### Context

I was interested in instantiating an IvySettings instance and using it to load my ~/.ivy2/ivysettings.xml file, then use the resulting IvySettings instance to populate the repositories used by my gradle scrip (as described in the post from Mar 25 2009 here: http://gradle.1045684.n5.nabble.com/configuring-gradle-from-ivysettings-xml-td1433719.html).

### Steps to Reproduce 

See attached build.gradle file (zipped):
[build.gradle.zip](https://github.com/gradle/gradle/files/4209573/build.gradle.zip)

### Your Environment

Build scan URL:
https://gradle.com/s/go64svb7bpyli

**Comment by big-guy** [comment]
At the very beginning, Gradle used Ivy for dependency resolution, but this hasn't been the case for a very long time and so Ivy isn't a part of Gradle's API anymore.  I don't think we're going to make changes to expose Ivy again.

I think you have a couple of options:
1. Write a plugin that uses a [Groovy XML slurper](https://groovy-lang.org/processing-xml.html#_xmlparser_and_xmlslurper) to read the ivy settings file directly and translate that into Gradle repositories. 
2. Write a plugin that uses Ivy and can rely on `IvySettings` in the plugin to translate repositories into Gradle's API.

Depending on how complicated the ivy settings are, you might not be able to make a 1:1 translation from an Ivy resolver to a Gradle repository or you may want to use Gradle features that won't be in the Ivy settings file, so you may be better off maintaining two sets of definitions.
