### ISSUE TITLE
DefaultResolvedArtifact produces different dependencies every time it's visited

### ISSUE THREAD

**Issue by westinrm** [gradle/gradle#12245]
### Expected Behavior
DefaultResolvedArtifact#visitDependencies should always add equal dependencies to the resolve context so that the CachingDirectedGraphWalker can properly cache them and so LocalTaskNode#postAction can properly de-duplicate them

### Current Behavior
https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultResolvedArtifact.java#L56-L74 provides a new instance of FinalizeAction every time it's called, causing any cached results stored in the directed graph walker to be useless on future calls, and always adding a new post action to the task node, even if one from the same resolved artifact always exists.

### Context
After upgrading to Gradle 6.1.1 I've noticed poor performance during configuration -- the build scan reports task graph calculation as taking upwards of 5 minutes.  Some profiling shows the majority of time is spent along the following back trace:
```
ImmutableSet.construct
...
ImmutableActionSet$SetWithManyActions.addOne
ImmutableActionSet.add
LocalTaskNode.appendPostAction
TaskNodeDependencyResolver.attachActionTo
CachingTaskDependencyResolveContext.attachFinalizerTo
CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues
```
I briefly experimented with pulling the anonymous class construction out of DefaultResolvedArtifact#visitDependencies and into a final field on DefaultResolvedArtifact, and saw my 5 minute configuration time reduce to 30 seconds.

### Steps to Reproduce 
I have not managed to reproduce this on any project I can share.  I was able to confirm that `LocalTaskNode#postAction` contained repeated instances of the anonymous class in DefaultResolvedArtifact, each anonymous class instance capturing the same resolved artifact instance.

### Your Environment
This was running Gradle v6.1.1 with Java 1.8.0_221

**Comment by big-guy** [comment]
Hey @westinrm 

Could you try running your build with the `gradle-profiler` + async profiler? https://github.com/gradle/gradle-profiler#async-profiler

And then share the flamegraph with us?  You can email it to performance@gradle.com

**Comment by westinrm** [comment]
I've sent the flame and icicle graphs to performance@gradle.com

**Comment by big-guy** [comment]
Thanks, I saw the flamegraph and I agree that ImmutableActionSet seems like a big chunk of it.

Is this the kind of change you experimented with? https://github.com/gradle/gradle/blob/8d14abaae7a0f00bba57dc803229c3c731cb523f/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultResolvedArtifact.java#L53

Our perf tests don't show much of a difference with this change, but maybe you could try this nightly and see if you see any gains: `./gradlew wrapper --gradle-version=6.3-branch-sg_63_hacks_artifact_dep-20200216022116+0000`

**Comment by westinrm** [comment]
Yep that matches the change I experimented with.  Using the mentioned version:

My original project configuration time of 5 minutes dropped to 45 seconds, and I no longer see ImmutableActionSet construction/addition in the flames.  I also am no longer touching the ImmutableActionSet$SetWithManyActions code

The perf tests may not see a difference since we do have quite a few plugins in this project -- one of them may be doing something that brings out this performance issue, though I haven't found anything yet.

**Comment by big-guy** [comment]
@gradle/jvm ☝️ I went ahead and merged the refactor since the effect seems to be large.  Do you have any idea what kind of test would expose this improvement?

@westinrm you should see this in 6.3

**Comment by westinrm** [comment]
We're running the nightlies now and haven't seen this issue show up again, so I'm going to close the issue.  There's still a question of what different thing we're doing in our gradle project that causes this bug to be hit, but that may remain unsolved.
