### ISSUE TITLE
Publish a multi-module project on maven publish plugin

### ISSUE THREAD

**Issue by jzdayz** [gradle/gradle#12256]
### Expected Behavior

publish one Repositories

### Current Behavior

![image](https://user-images.githubusercontent.com/35563513/74647850-6abf2c00-51b7-11ea-90d3-da8dfd3b702e.png)
there is four.And they are all incomplete

### Context

project address -> https://github.com/jzdayz/gradle-t

### Steps to Reproduce 

1. Create a muti-module project
2. update build.gradle use maven-publish and singing plugins
3. publish project to maven central

### Your Environment

Build scan URL:
In the root directory of the project:
./gradlew --no-daemon --no-parallel publish

**Comment by jzdayz** [comment]
If it is a non-multi-module project, the release will succeed

**Comment by ljacomet** [comment]
So I was going to say that this issue should only happen with `--parallel`.

Have a look at [this plugin](https://github.com/marcphilipp/nexus-publish-plugin) which can help when you want to do things in parallel anyway.
