### ISSUE TITLE
Publishing Gradle plugin marker: can't set pom name and description

### ISSUE THREAD

**Issue by gabrielittner** [gradle/gradle#12259]
I want to set the pom name and description like this to satisfy the maven central requirements:

```groovy
publishing {
    publications.all {
        pom {
            name = 'My Library'
            description = 'A concise description of my library'
            url = 'http://www.example.com/library'
        }
    }
}
```

### Expected Behavior

Generated poms should contain:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project ...>
  ...
  <name>My Library</name>
  <description>A concise description of my library</description>
  <url>http://www.example.com/library</url>
</project>
```

### Current Behavior

The 3 lines exist in the actual artifact's pom. However the pom for the plugin marker does not contain the name and description.

### Context

This worked in Gradle 4.10.3. On newer versions it is broken. Tested it with 5.0, 5.6.4, 6.0 and 6.2.

Because of this issue it's not possible to publish plugin markers to maven central.

### Steps to Reproduce 

This is a sample project with publishing set up. If you run `publish` it will write to `build/repo`:
[publish-sample.zip](https://github.com/gradle/gradle/files/4215992/publish-sample.zip)

**Comment by gabrielittner** [comment]
This seems to be a working workaround:
```kotlin
myPublication.pom.withXml { pom ->
    pom.asNode().appendNode("name", "the name")
    pom.asNode().appendNode("description", "the description")
}
```

**Comment by gabrielittner** [comment]
This is still happening in Gradle 6.8.2

**Comment by gabrielittner** [comment]
This is still happening in Gradle 7.2. Would you accept a fix that only executes these lines when `declaration.getDisplayName()` and `declaration.getDescription()` are respecitively not null?

**Comment by DavidGregory084** [comment]
I have found another workaround for this:

https://github.com/opencastsoftware/gradle-build-info/blob/main/build.gradle.kts#L96=

You have to do something similar to get signing of the plugin marker to work too:
https://github.com/opencastsoftware/gradle-build-info/blob/main/build.gradle.kts#L132=

I have no idea how anyone is supposed to figure this out but I found some good info in these threads:
https://discuss.gradle.org/t/adding-custom-artifacts-to-an-existing-publication/18067
https://discuss.gradle.org/t/how-can-i-customize-the-pom-of-the-plugin-marker-artifacts/33053/4

**Comment by StefMa** [comment]
Happen still with 8.5.
I fixed it by adding `displayName` and `description` to the `publings.register` from the `java-gradle-plugin` plugin block:
```kotlin
gradlePlugin {
    plugins.register("com.ioki.sentry.proguard") {
        id = "plugin.id"
        implementationClass = "impl.Class"
        displayName = "SameAsInPom"
        description = "Some Description"
    }
}
```

I guess the plugin should instead of relaying on this properties, fallback to the `publishing.publications.pom` declaration of the `maven-publish` plugin in case it is available...
