### ISSUE TITLE
Task up to date because Build cache is disabled

### ISSUE THREAD

**Issue by kec2** [gradle/gradle#12263]
I have a multi project build.
Executing gradlew :build results in compile and test to be up to date.
The timestamp of the source/test files has changed between builds but not the content.
This is done on Jenkins.

Gradle 6.1.1, Windows 10, Java 1.0.8_232

### Expected Behavior

compile and test should not to be up to date and should be run.

### Current Behavior

compile and test are up to date and does not run.

### Context

Because test does not run I don't get new test reports.
After test Jenkins publishes the test reports but because they are now a few days old the build fails.

### Your Environment

Build scan URL:

**Comment by lptr** [comment]
> The timestamp of the source/test files has changed between builds but not the content.

In this case the task should be up-to-date. Gradle cares about content, not timestamps.
