### ISSUE TITLE
Kotlin DSL + TestKit - Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by pun-ky** [gradle/gradle#12262]
### Expected Behavior

There should not occur script compilation error when using Gradle TestKit running build using Kotlin DSL when trying to configure a task which type is extending some another type extracted to separate JAR.

### Current Behavior

Right now the same test is working when running via CLI instead of running via TestKit.
Also thanks to @big-guy suggestion got on Slack community channel, confirmed that when rewriting build script file being tested from Kotlin DSL to Groovy DSL, there is no such problem with `Supertypes of the following classes cannot be resolved` which confirmed that the bug is connected with TestKit and Kotlin DSL integration.

https://github.com/Cognifide/gradle-aem-plugin/blob/kotlin-dsl-bug/src/functionalTest/kotlin/com/cognifide/gradle/aem/pkg/PackagePluginTest.kt#L100 - this line wasn't working before when using Kotlin DSL, rewritten to Groovy DSL and it started working

https://github.com/Cognifide/gradle-aem-plugin/blob/kotlin-dsl-bug/src/functionalTest/kotlin/com/cognifide/gradle/aem/bundle/BundlePluginTest.kt#L112 - similar case, intentionally kept not rewritten to Groovy DSL to let you see the error.

### Context

The plugin that I am developing is written in Kotlin and is officially supporting only build scripts using Kotlin DSL. So that I am a little bit concerned because after major refactoring performed (splitting my plugin to set of separate plugins) I need to use Groovy DSL in some tests using TestKit instead of Kotlin DSL which does not make sense in my case.

### Steps to Reproduce 

For reproduction, I created for you a separate branch in my GitHub project which I will remain untouched, to let you build it and see the error by yourself.

https://github.com/Cognifide/gradle-aem-plugin/pull/610 (PR / branch / source code)
https://github.com/Cognifide/gradle-aem-plugin/pull/610/checks?check_run_id=452170428 (PR build with error visible in output)

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vsts/work/1/s/build/functionalTest/bundle-extended/build.gradle.kts'

* What went wrong:
Script compilation error:

  Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
      class com.cognifide.gradle.aem.bundle.tasks.BundleCompose, unresolved supertypes: com.cognifide.gradle.common.tasks.JarTask
  

1 error
```

### Your Environment

Build scan URL:

https://scans.gradle.com/s/koutfge7p3gu4

**Comment by pun-ky** [comment]
Right now, I haven't found any other workaround except rewriting the test build script files from Kotlin DSL to Groovy DSL. Any ideas appreciated.

**Comment by bamboo** [comment]
@pun-ky Could you try the Kotlin version without the [`withDebug(true)` setting](https://github.com/Cognifide/gradle-aem-plugin/blob/aad08c4fcaa36e7e9f5d78be81c02c6d6b145ba8/src/functionalTest/kotlin/com/cognifide/gradle/aem/test/AemBuildTest.kt#L39) and report back?

**Comment by pun-ky** [comment]
sure, tomorrow :)

**Comment by pun-ky** [comment]
@bamboo magic!!! commenting out `withDebug` helped ;) is this a bug or not? why is it helping?

**Comment by pun-ky** [comment]
btw if you are the same Rodrigo available on Gradle stand at KotlinConf at Kopenhagen, it was nice to meet you ;)

**Comment by bamboo** [comment]
Hey @pun-ky, yes, that was me, just recognised you from the picture as well, nice meeting you :)

The Kotlin DSL incompatibility with `withDebug(true)` is indeed a known bug: https://github.com/gradle/gradle/issues/6862

**Comment by pun-ky** [comment]
heh, nice :) 

the error message looks a little bit different however as I understand it, the root cause is the same.
hmm it is known since 2018... so no bigger chances for fix in future? if it is a duplicate you could close this one.

thx for support
