### ISSUE TITLE
how to remove a local  jar form a library 

### ISSUE THREAD

**Issue by vipheyue** [gradle/gradle#1227]
### Expecte Behavior
remove a jar form a library 
------------------------------------------------------------------
myProject
	compile cn.bmob.android:bmob-sdk:3.5.3 library(.aar I can't modify The source code)
							----libs
							---------okhttp-3.3.0.jar(it's a jar)

i watch the projtct depdences by gradle command 
```
gradle dependencies
```

![9daca4bf-3a30-4d1a-a94c-2c4550ca6d3e](https://cloud.githubusercontent.com/assets/11717882/22175425/7a36df4a-e02f-11e6-80cc-2204f3155aa6.png)

i use this code but  invalid, okhttp.jar still in bmob Library
```
compile ('cn.bmob.android:bmob-sdk:3.5.3',{
        exclude module: 'okhttp'
    })
```
![892ad131-285f-49bb-bf66-cd4405ab2984](https://cloud.githubusercontent.com/assets/11717882/22175428/81119918-e02f-11e6-9fab-8350c786e989.png)

   please tell me how to exclude this local jar,thank you very much

**Comment by vipheyue** [comment]
Is there a method for inspecting/excluding modules from .jar dependencies not available on Maven? gradle dependencies seems to not report dependencies added with compile files('libs/example.jar')

**Comment by lacasseio** [comment]
The GitHub issues are reserved for feature request and bug. Please use the [user forum](https://discuss.gradle.org/) for any question related to Gradle usage. In the event your question does turn out to be a valid GitHub issue, please follow the [contribution guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).
