### ISSUE TITLE
IdeaModelBuilder does not provide groovy-all as compile dep for buildSrc

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#12274]
In `6.2` creating a buildSrc project in an Android build results in groovy-all missing from its compile classpath. This means that references to e.g. GString are not resolved in the IDE.

The root cause seems to be that the `IdeaModelBudiler.buildDependencies` does not handle `ModuleLibrary` which is the type used to wrap groovy-all after this change https://github.com/gradle/gradle/commit/0b56b6121f262b78d8002b84408b0d70c0487905.

**Comment by big-guy** [comment]
This'll be fixed in 6.2.1
