### ISSUE TITLE
Documentation to upgrade wrapper is misleading

### ISSUE THREAD

**Issue by dreis2211** [gradle/gradle#12273]
Hi,

today I upgraded the Gradle wrapper on Spring-Boot to 6.2 (see https://github.com/spring-projects/spring-boot/pull/20213 ).

To my surprise running `./gradlew wrapper --gradle-version 6.2` as stated in the [official docs](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper) isn't the complete solution. Running another `./gradlew wrapper` was necessary to actually update the `gradlew.bat`.

I have found #884 that talks about the root cause of this, but in the meantime the documentation should be updated to reflect this surprising behaviour.

Cheers,
Christoph

**Comment by dreis2211** [comment]
Still valid

**Comment by dreis2211** [comment]
Still valid

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
