### ISSUE TITLE
Allow unknown options in `BuildLauncher`

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#1228]
### Expected Behavior

Turn on `org.gradle.cli.CommandLineParser.allowUnknownOptions` in build started by `BuildLauncher`

### Current Behavior

When I started a build with `BuildLauncher` and some command line arguments such as `--tests xxx`, I got the following error:

```
Unknown command-line option '--tests'.
Either it is not a valid build option or it is not supported in the target Gradle version.
Not all of the Gradle command line options are supported build arguments.
Examples of supported build arguments: '--info', '-u', '-p'.
Examples of unsupported build options: '--daemon', '-?', '-v'.
Please find more information in the javadoc for the BuildLauncher class.
```

I have read the source code and found the option `allowUnknownOptions` was turned on in `GradleWrapperMain` by default, but not in `org.gradle.cli.AbstractCommandLineConverter`. I want to know if it can be set as default value so that I can use some customized arguments in `BuildLauncher`. That would help me a lot. 

If it is reasonable, I will create a PR to do this.

Thanks.

**Comment by big-guy** [comment]
If you're trying to use `--tests`, you should really be using `TestLauncher` instead. 

https://github.com/gradle/gradle/blob/master/subprojects/tooling-api/src/main/java/org/gradle/tooling/ProjectConnection.java#L106-L106

Is there some other command-line argument you're trying to use?

**Comment by blindpirate** [comment]
@big-guy Thanks for your reply.

Actually, I want to use `--tests` only, but what I'm writing is a plugin for go programming language, so methods of `TestLauncher` cannot be applied in this case. When I tried with `TestLauncher.run()`, the error occurred:

```
org.gradle.tooling.TestExecutionException: No test declared for execution.
```

Is there any way to  achieve my goals? Thank you very much.

**Comment by eriwen** [comment]
Aside @blindpirate: Kudos for tackling Go support for Gradle — that's awesome!

**Comment by blindpirate** [comment]
@eriwen Thanks.

I want to replace the default `RepositoryHandler` to my own implementation, but it seems that this can only be done with reflection. Could you please tell me how to replace the default `RepositoryHandler` service in `DefaultProject`'s `serviceRegistry` gracefully?

**Comment by blindpirate** [comment]
@eriwen 
My current solution is 

```
        DefaultProject defaultProject = (DefaultProject) project;
        DefaultServiceRegistry serviceRegistry = (DefaultServiceRegistry) defaultProject.getServices();
        Class serviceProviderClass = Class.forName("org.gradle.internal.service.DefaultServiceRegistry$ServiceProvider");

        Object proxy = Proxy.newProxyInstance(getClass().getClassLoader(), new Class[]{serviceProviderClass}, new InvocationHandler() {
            @Override
            public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
                if ("get".equals(method.getName())) {
                    return injector.getInstance(GolangRepositoryHandler.class);
                } else {
                    return null;
                }
            }
        });
        Map providerCache = (Map) ReflectionUtils.getValueIncludingSuperclasses("providerCache",
                serviceRegistry);
        synchronized (serviceRegistry) {
            providerCache.put(RepositoryHandler.class, proxy);
        }
```

It works but I don't like it.

**Comment by blindpirate** [comment]
@big-guy @eriwen I'm still waiting for your reply...

**Comment by big-guy** [comment]
hey @blindpirate, 

What are you trying to do with your own `RepositoryHandler` implementation?  You can't replace the `repositories {}` that comes with Gradle, but you can extend it by using extra properties: https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:extra_properties

So you can do something like:

```
repositories.ext.myExtraProperty = { println it }

repositories {
   myExtraProperty("hello world")
}
```
That would print "hello world".

I think if you're trying to use `RepositoryHandler` to add your own type of `ArtifactRepository`, that's not going to work due to how tangled the artifact repository implementations are to internal APIs.  Are you going to try to use configurations and regular Maven-like repositories for Go dependencies?

**Comment by blindpirate** [comment]
Yes, and I have finished all of them with some hacking. I will try your advice, thanks a lot.
