### ISSUE TITLE
Gradle transitive dependencies doesn't respect version (follows highest version wins rule when relevant deps are declared in same gradle file and priority based resolution otherwise)

### ISSUE THREAD

**Issue by ramanpreetSinghKhinda** [gradle/gradle#12286]
### Brief summary
Gradle at runtime resolves the transitive dependencies incorrectly where it gives preference to the version that is being resolved first (`buildSrc gradle` -- followed by --> `root  project gradle` --- followed by --> `module gradle`) rather than the one which has the higher version. Consider below example:

#### Setup 1

**Project build.gradle**

```
buildscript {
    repositories { . . . }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.firebase:perf-plugin:1.3.1'
    }
}
.  .  .
```
#### Setup 2

**Project build.gradle**

```
buildscript {
    repositories { . . . }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
    }
}
.  .  .
```

**Module build.gradle**

```
buildscript {
    .  .  .
    dependencies {
        classpath 'com.google.firebase:perf-plugin:1.3.1'
    }
}
 . . .
```

[com.android.tools.build:gradle:3.4.2](https://mvnrepository.com/artifact/com.android.tools.build/gradle/3.4.2) (the Android Gradle Plugin or AGP) has a dependency on `org.ow2.asm` with **version 6.0**.

[com.google.firebase:perf-plugin:1.3.1](https://mvnrepository.com/artifact/com.google.firebase/perf-plugin/1.3.1) (the Firebase Performance Plugin) also has a dependency on `org.ow2.asm` but with **version 7.0**.

In the **Setup 1**  case, gradle resolves the `org.ow2.asm` dependency to **version 7.0** (the one declared by the `perf-plugin` as it's higher in version) and both the `AGP` and `perf-plugin` at runtime gets the `org.ow2.asm` with **version 7.0**.  However, in **Setup 2** case, gradle resolves the  `org.ow2.asm` dependency to **version 6.0** (the one declared by the `AGP`).

The reason for this inconsistency (which I have figured out so far) is, gradle doesn't respect the highest version wins rule when dependencies are declared in different gradle files, rather, it applies priority based rule which gives highest priority to the gradle which is being resolved first, followed by the next and so on. So the chain looks like this:

`buildSrc gradle` -- followed by --> `root  project gradle` --- followed by --> `module gradle`

### Expected Behavior
Gradle should resolve to the highest version of dependency, no matter if the conflicting deps are declared in different gradle files.

### Current Behavior
Gradle follows highest version wins rule when dependencies are declared in the same gradle file and follows priority based rule when deps are declared in different gradle files.

### Context
Since (with **Setup 2**) at runtime `perf-plugin` get's the `org.ow2.asm` with **version 6.0**, it throws `IllegalArgumentException` at  [this](https://gitlab.ow2.org/asm/asm/blob/ASM_6_0/src/org/objectweb/asm/ClassVisitor.java#L79) line, for each class the `perf-plugin` tries to instrument and thus the devs are unable to use the `perf-plugin` until they realize that they need to put the `perf-plugin` dependency along with the `AGP` as both have conflicts on `ASM` dependency version.

### Steps to Reproduce 
See below for one of the issues reported by the dev and how to reproduce that:
https://github.com/wokkaflokka/firebase-perf-plugin-bug-report

------

**NOTE:** I have explained the scenario with `AGP` and `perf-plugin` however, this is a general problem and can happen with any 2 (or more) dependencies which conflicting versions of transitive dependencies.

**Comment by ljacomet** [comment]
Thanks for the report.

This looks like another occurrence of #9650 with a deeper analysis. Hopefully that will help provide an answer / fix for this situation.
