### ISSUE TITLE
Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

### ISSUE THREAD

**Issue by girishgadad** [gradle/gradle#12291]
Environment:
OS-Wondows 10
Processor i7-7700 CPU @3.60GHz 3.60GHz
RAM- 16GB

**Comment by girishgadad** [comment]
I am stucked with this issue and not able to proceed for further development.

**Comment by ljacomet** [comment]
Unless you provide more information, there is no chance we can help you. Ideally provide a reproducer project. At least explain what you are trying to do and provide the stacktrace of the error.

**Comment by girishgadad** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'OneApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.4.2.     
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.4.2.  
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.
               > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run 
CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'OneApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.4.2.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.4.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.
               > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at runOnAllDevices (C:\Girish\OneApp\OneApp\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (C:\Girish\OneApp\OneApp\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:179:41)
    at C:\Girish\OneApp\OneApp\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (C:\Girish\OneApp\OneApp\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:182:9)

**Comment by girishgadad** [comment]
Please help me ..i am struggling since yesterday.

**Comment by girishgadad** [comment]
Here is **Package.json:**

{
  "name": "OneApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/cli-platform-android": "^2.9.0",
    "react": "16.9.0",
    "react-native": "0.61.5"
  },
  "devDependencies": {
    "@babel/core": "7.8.4",
    "@babel/runtime": "7.8.4",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

============================================
**Build.gradle**:

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

=======================================
**gradle-wrapper.properties:**
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

**Comment by girishgadad** [comment]
> 
> 
> Unless you provide more information, there is no chance we can help you. Ideally provide a reproducer project. At least explain what you are trying to do and provide the stacktrace of the error.

Hi, I'hv done a setup on new machine with given configuration and trying to run a sample project but facing this issue.

**Comment by big-guy** [comment]
Hi @girishgadad,

> Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.

This points to some kind of environment/network problem.  Either that is being blocked or the Java install you're using is unable to authenticate that server.   If you can download that URL from a browser, I would try installing a newer version of Java if you can.

**Comment by girishgadad** [comment]
Hi @big-guy ,
I am still facing the same issue after installing new version of java 

> 
> 
> Hi @girishgadad,
> 
> > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.2/gradle-3.4.2.pom'.
> 
> This points to some kind of environment/network problem. Either that is being blocked or the Java install you're using is unable to authenticate that server. If you can download that URL from a browser, I would try installing a newer version of Java if you can.

Hi @big-guy ,
I am still facing the same issue even after installing the latest version of java.

**Comment by girishgadad** [comment]
someone please help me...I am facing this issue since a week.

**Comment by markosrx** [comment]
Is there any solution since then?
