### ISSUE TITLE
Wrong test status in IntelliJ because of replaced exceptions

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#12302]
If I run Spock tests with IntelliJ with delegating to Gradle enabled, for most failures the icon is wrong.
Instead of the yellow failure icon the red error icon is shown which does signify something that is not an `AssertionError` was thrown.
The cause for this is, that Spock uses subclasses of `AssertionError` in most cases and you somehow somewhere replace the actual error with a `PlaceholderException`.
If IJ then tests the type, the check fails and the node is marked as errorerd instead of failed.
Only if `AssertionError` itself is used, the test is properly shown as failed.

I didn't dig deep enough to have more insight on how to properly solve it, but maybe you should have an additional `PlaceholderAssertionError` and also transport whether the exception was an instanceof `AssertionError`, so that the later instanceof check succeeds even if the exception got replaced.

As I'm not sure on which side this is best to fix, I actually created an IJ and a Gradle issue, the corresponding one is at https://youtrack.jetbrains.com/issue/IDEA-233546

**Comment by melix** [comment]
It's probably a mix of the two. IDEA shouldn't rely on the exception types but get the status of a test via the Tooling API test descriptor. At the same time, it would be nice if Gradle had a specific subtype of assertion error for placeholder exceptions of that kind.

However, I'm not seeing this behavior with IDEA 2020.1, would you mind checking that you still have the problem?

**Comment by Vampire** [comment]
Sorry for the late reply.
Yes, it still happens with 2020.1, but as you now hopefully fixed it, I guess you found this too. :-)
