### ISSUE TITLE
De-serialization of task graph incorrect for anonymous subtypes of enum.

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#12301]
Say you have a Task with a enum input 

```
class MyTask: DefaulTask() { 

   @get:Input
   val myEnumValue: Property<SomeEnumType>
}
```
now let's define the enum with some added methods : 
```
enum SomeEnumType { 
   ValueOne: { 
      fun doSomething() {...}
   }
   ValueTwo: { 
      fun doSomething() {...}
   }
   abstract fun doSomething()
}
```
when MyTask executes, the type of the myEnumValue (say ValueOne) is not SomeEnumType but SomeEnumType$1 

When deserializing the code at : 
https://github.com/gradle/gradle/blob/master/subprojects/instant-execution/src/main/kotlin/org/gradle/instantexecution/serialization/codecs/EnumCodec.kt

will deserialize the class name as SomeEnumType$1 for which encodingForType() will return false and it will deserialize the object as a dangling instance instead of "reusing" the enum object. 

I suspect that serialization should really serialize the class name as SomeEnumType rather than SomeEnumType$1 but I can see how deserialization could be made smarter too.

**Comment by bamboo** [comment]
Thanks for the report, @jdochez. 

> I suspect that serialization should really serialize the class name as SomeEnumType

I think so too.
