### ISSUE TITLE
Completely locked out of gradle

### ISSUE THREAD

**Issue by aadharna** [gradle/gradle#12300]
I just made a [PR](https://github.com/aadharna/UntouchableThunder/commit/71dcc5aca23628c90e4b704a2713ccf6e69b99b4) (in my own code) to fix the issue the issue I opened up last week, #12231 using the second solution of running ./gradlew install and then having my code call the created .jar file. However, I seem to have corrupted some necessary file. because I cannot run **ANY** `./gradlew` command. Solutions found online to java I/O errors over lock files -- see the below stack-trace error -- suggest deleting the .gradle folder and then rebuilding, but that option is not open to me. 

I have tried `rm -rf`-ing pretty much everything not 100% necessary in my HPC-useraccount, including a complete delete and reinstall of my conda environment and the .gradle folder, but the issue persists. 

I am using gradle 5.1.1 and I have found the issue to exist whether or not i have java 11.0.1 or java 11.0.4 as my path'd java. 

### Expected Behavior

I should be able to run any sort of basic ./gradlew command such as ./gradlew clean. And when I run the commands on my personal computer, they work as expected.  
![image](https://user-images.githubusercontent.com/16660757/74986727-a6503500-5407-11ea-96b0-a21e392e7afa.png)

But I get the following error when run on the HPC:

### Current Behavior

![image](https://user-images.githubusercontent.com/16660757/74985728-1067da80-5406-11ea-92de-947ae66449c3.png)

This same error will show up. Here's the text of the error: 
```
Exception in thread "main" java.io.IOException: Input/output error
        at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:96)
        at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1167)
        at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:55)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)
```

There are no running gradles: 
```
(thesis) [ad5238@log-0 GVGAI_GYM]$ ps aux | grep gradle
ad5238    55329  0.0  0.0 112656   972 pts/66   S+   13:12   0:00 grep --color=auto gradle
```

This issue happened to me once before in the last week, but when I wiped clean my user-account on the hpc, things were resolved (I deleted the `.gradle` folder as well as my `.conda` folder. This time around that has not lifted the problem. 

### Context

I cannot test the solution that was recommended to me in #12231 therefore i cannot perform the the experiments I need to finish my thesis. 

### Steps to Reproduce 

Again unfortunately this is on an HPC computer so I don't see how it could be made reproducible. 

### Your Environment

Build scan URL: Unfortunately I cannot provide that this time around because as mentioned, I cannot run any command using gradle.

**Comment by big-guy** [comment]
It looks like the filesystem that Gradle's trying to lock the file on doesn't support file locking. The error is terrible, but it's failing to lock a file under the Gradle user home.

Do you happen to have the environment variable GRADLE_USER_HOME set to anything or are you passing `-g`?

**Comment by aadharna** [comment]
I implemented the `-g` GRADLE_USER_HOME method you mentioned earlier this week. However, it wasn't working perfectly. Therefore myself and the main-dev on GVGAI_GYM decided to do the `./gradlew install` method. 

When I queried  `echo $GRADLE_USER_HOME` it came up blank. I removed the code which was passing in the `-g` flag with the PR linked above.

**Comment by aadharna** [comment]
So, this has been resolved on the HPC end by factory-resetting my account. However, presumably something happened on the gradle-side that you might still want to look into. On the other hand this scenario is so niche that it might just warrant writing it off. 

@big-guy thank you for your help and thoughts on my issues over the past week.
