### ISSUE TITLE
Unable to resolve dependency artifact

### ISSUE THREAD

**Issue by embee1981** [gradle/gradle#12313]
On upgrading from Gradle 5.5.1 to 6.2, the following dependency is no longer being resolved:

```javascript
 compile ("com.blah.core:My_JavaBeans:1.0.0") {
        artifact {
            name = "HelloWorld"
            type = "jar"
        }
    }
```

Execution failed for task ':my-service:compileJava'.
> Could not resolve all files for configuration ':my-service:compileClasspath'.
   > Could not find com.blah.core.My_JavaBeans:1.0.0:.
     Required by:
         project :my-service

The nexus repository has no artifact "My_JavaBeans" this is a simple top level folder that contains lots of jar files plus an ivy file:

```javascript
<ivy-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0" xsi:noNamespaceSchemaLocation="http://ant.apache.org/ivy/schemas/ivy.xsd">
<info organisation="com.blah.core" module="My_JavaBeans" revision="1.0.0" status="integration" publication="20170810115952"/>
<configurations>
   <conf name="master"/>
   <conf name="compile"/>
   <conf name="provided" description="Container provided dependencies"/>
   <conf name="runtime" extends="compile"/>
   <conf name="test" extends="runtime" visibility="private"/>
   <conf name="default" extends="master,runtime"/>
   <conf name="sources"/>
   <conf name="javadoc"/>
</configurations>
<publications>
    <artifact name="Blah"/>
    <artifact name="TestBean"/>
    <artifact name="HelloWorld"/>
</publications>
</ivy-module>
```
How do you now resolve such an artifact, assuming this is a change in behaviour and not a bug?

**Comment by jjohannes** [comment]
Hi @embee1981. How does the corresponding repository definition look like?

You might need to add `metadataSources { artifact() }`

https://docs.gradle.org/current/userguide/upgrading_version_5.html#maven_or_ivy_repositories_are_no_longer_queried_for_artifacts_without_metadata_by_default

https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources


If that solves the issue, there might be something else wrong in the repository structure. Because this would indicate that the `ivy.xml` file is not found/used.

**Comment by embee1981** [comment]
Thanks @jjohannes, we'd missed that section in the upgrade docs. That gets us passed that issue. Something else that's popped up is we have

``` groovy
 repositories {
        maven { url ourNexusUrl
            metadataSources { mavenPom();  artifact() }
        }
        mavenCentral {
            metadataSources {  mavenPom(); artifact() }
        }
        ...
}
```
and previously we had a dependency on jacoco via
```groovy
compile "org.jacoco:org.jacoco.agent:0.8.4:runtime"
```
On our nexus repo, it has a org.jacoco.agent-0.8.4-runtime.jar and a org.jacoco.agent-0.8.4.pom along with sha1 files (exact copies of maven central ).

We get

> Could not resolve all files for configuration ':my-service:jacocoAgent'.
   > Could not find org.jacoco.agent-0.8.4.jar (org.jacoco:org.jacoco.agent:0.8.4).
     Searched in the following locations:
         http://ourNexusUrl/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4.jar

Should it not search mavenCentral if it can't find it in ourNexusUrl repo (as for some reason we don't have org.jacoco.agent-0.8.4.jar in our nexus repo)?

**Comment by ljacomet** [comment]
No it will not. Once Gradle identifies a repository for serving a version of a dependency, all artifacts must come from that repository.

Your nexus situation effectively means you have a partial mirror. This is not supported by Gradle.

**Comment by embee1981** [comment]
Ahh ok. Thanks for your help @jjohannes and @ljacomet
