### ISSUE TITLE
InputChanges.getFileChanges() doesn't accept ConfigurableFileCollection type

### ISSUE THREAD

**Issue by yevhenii8** [gradle/gradle#12318]
### Expected Behavior
`InputChanges.getFileChanges()` should accept param that is marked with `@Incremental` and has `ConfigurableFileCollection` type. And it does, but it doesn't work at runtime.

### Current Behavior
When a task execution comes to getFileChanges() it throws this exception:
`Cannot query incremental changes: No property found for value file collection.`

### Context
I'm writing a custom gradle plugin. At some point I want some task to have an input property that represents a `FileCollection` of runtime dependencies. And process them incrementally.

```
    val dependencies: ConfigurableFileCollection
        @Incremental
        @InputFiles
        get() = project.files(project.configurations.getByName("runtimeClasspath").resolvedConfiguration.files)
```
```
inputChanges.getFileChanges(dependencies).forEach { change ->
            println("   $change")
            // and so on...
        }

```
### Steps to Reproduce 
1. Unpack archive [fxdistributor.zip](https://github.com/gradle/gradle/files/4237852/fxdistributor.zip)
2. Go to fxdistributor/fxdistributor-demo-app
3. Run `./gradlew publishToLocal --rerun-tasks`
4. Get this
```
* What went wrong:
Execution failed for task ':fxdistributor-demo-app:publishToLocal'.
> Cannot query incremental changes: No property found for value file collection. Incremental properties: dependencies.
```

fxdistributor-gradle-plugin/src/main/kotlin/.../PublishToLocalTask.kt - contains call of getFileChanges() at line 59.
fxdistributor-demo-app - just uses that plugin from the local repository.

### Your Environment

Build scan URL: https://gradle.com/s/egy7phztlaauc

**Comment by wolfs** [comment]
As stated in the [user manual](https://docs.gradle.org/current/userguide/custom_tasks.html#sec:implementing_an_incremental_task), an incremental task property always need to return the same instance:
> To query incremental changes for an input file property, that property always needs to return the same instance.

Your `val` doesn't. This can be easily fixed by doing a variation of:
```
val dependencies: ConfigurableFileCollection = project.files().from(Callable {
  
  project.configurations.getByName("runtimeClasspath").resolvedConfiguration.files 
})
```
