### ISSUE TITLE
Intelligently choose when to download remote build cache results 

### ISSUE THREAD

**Issue by cckroets** [gradle/gradle#12319]
The remote build cache server should intelligently choose when to serve build cache artifacts, and when to withhold them based on the size of the artifacts, the estimated download speed, and estimated unpacking speed.

As the build is downloading more and more artifacts, the client should be maintain an approximate download speed that can be sent with each remote build cache request. Since the build cache server knows how long it took to produce the artifact in the cache, it can perform a cost-benefit analysis to determine if serving the artifact will actually be faster than withholding it and letting the client re-computing it. The difficult part with this approach is this assumes the requesting machine is similar in performance to the machine that produced the original artifact. Each machine would need to produce some heuristic to properly compare them.

### Expected Behavior

When requesting an artifact from the remote build cache, we should not download the actual build artifacts if the estimated time to download and unpack the artifact is higher than the estimated execution time. 

### Current Behavior
Whenever the inputs match, the artifacts are always downloaded from the remote cache independent of download speed or artifact size.  

### Context

For a heavily modularized Android build, our build scans occasionally show a negative "Avoidance Savings" due to the remote build cache. Looking through individual tasks, there is a combination of positive and negative savings.

#### Alternatives considered:
Disabling caching for certain types of tasks
- This approach doesn't work well because some instances of the task types have net positive avoidance savings and some instances do not, depending on the size of the output and current network speed.
- Also the `doNotCacheIf` method doesn't allow us to specify between local and remote caching.

Disable remote cache when network is slow
- A naive solution would be to entirely disable the remote build cache when we detect that the download speed is slow. However some tasks may still benefit from the remote cache even when the network is deemed "slow". This also doesn't take into account the estimated unpack speed which should be considered when returning artifacts.

**Comment by ldaley** [comment]
Hi @cckroets.

This general problem is something that we have been circling for some time now. Thanks for the input.

Can you share some example artifact sizes and network details? To what extent is this dynamic for different developers with different connections?

**Comment by cckroets** [comment]
Sure Luke,

I don't see anywhere that build scans aggregates this data (another feature request perhaps!). So here is data from three random users's local build scans Remote cache hit:


| Artifacts 	| Remote hit time spent  	| Download Size 	| Speed    	|
|----------	|-------------	|---------------	|----------	|
| 872      	| 3m 52s      	| 757 MB        	| 3.2 MB/s 	|
| 1518     	| 10m 15s     	| 830 MB        	| 1.4 MB/s 	|
| 1061     	| 27m 15.802s 	| 766 MB        	| 468 kB/s 	|

Total execution speed was around 7m 30s for all of these builds. For download speed, this seems most variable when using WiFi vs direct ethernet connection (this is just anecdotal though)
