### ISSUE TITLE
Replace project depend with aar runtime

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#12328]
### Expected Behavior

Sometimes local project depend is prefect, however sometimes aar depend is faster. So in my very large project, I want to switch between project depend and aar depend.

I develop a plugin. And then I listen project afterEvaluate event. Here is my code:

```java
@Override
public void apply(Project target) {
    target.afterEvaluate(project -> {
        ConfigurationContainer configurationContainer = project.getConfigurations();
        Configuration configuration = configurationContainer.getByName("debugRuntimeClasspath");
        DependencySet dependencySet = configuration.getAllDependencies();
        List<Dependency> deleteSet = new ArrayList<>();
        for (Dependency dependency : dependencySet) {
            if (dependency instanceof DefaultProjectDependency) {
                deleteSet.add(dependency);
            }
        }
        configuration.getAllDependencies().removeAll(deleteSet);
    });
}
```
As you see, I want to delete all DefaultProjectDependencies. However I cannot do that because gradle throws exception.

I do not know if I can delete all DefaultProjectDependencies runtime but in fact I really want this feature.

### Current Behavior

```java
> java.lang.UnsupportedOperationException
```
### Your Environment

Build scan URL:

**Comment by jjohannes** [comment]
@CoXier you should be able to do what you describe with dependency substitution rules:
https://docs.gradle.org/current/userguide/resolution_rules.html#sub:module_to_project_substitution

**Comment by CoXier** [comment]
@jjohannes Very thanks for your reply. I want to know is there any way to do that in custom plugin.

Such code in build.gradle:

```java
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute project(":api") because "we use a stable version of org.utils:api" with module("org.utils:api:1.3")
    }
}
```

**Comment by ljacomet** [comment]
Depending on the language you use for developing your plugin, the syntax may differ a bit, but otherwise, yes you can do that.

For example in java 8+:

```
public void apply(ProjectInternal project) {
    project.getConfigurations().all(conf -> {
        conf.getResolutionStrategy().dependencySubstitution(substitutions -> {
           substitutions.substitute(substitutions.project(":api")).because("we use a stable version of org.utils:api").with(substitutions.module("org.utils:api:1.3"));
        });
    });
}
```

**Comment by CoXier** [comment]
Thanks @ljacomet . I will try myself.

**Comment by CoXier** [comment]
@ljacomet Hi， I have tried， however it does not work.

```java
    @Override
    public void apply(Project target) {
        target.afterEvaluate(project -> {
            target.getConfigurations().all(configuration -> {
                configuration.getResolutionStrategy().getDependencySubstitution().all(dependency -> {
                    if (dependency.getRequested() instanceof ProjectComponentSelector) {
                        System.out.println("HHHHHHH:" + dependency);
                    }
                });
            });
        });

    }
```

**Comment by CoXier** [comment]
In addition, I use below code in my app project and it does not work for me.

```java
configurations.all {
    resolutionStrategy.dependencySubstitution.all { DependencySubstitution dependency ->
        println(dependency.requested.toString() + "hhhhhh")
        if (dependency.requested instanceof ProjectComponentSelector) {
            println(dependency.requested.toString() + "hhhhhh")
        }
    }
}
```

**Comment by jjohannes** [comment]
Pay attention to the example here: https://github.com/gradle/gradle/issues/12328#issuecomment-590398304

What you **have** is code to access all substitutions (but you don't have any)
`getResolutionStrategy().getDependencySubstitution().all( ... )`

What you **want** is code adding a new substitution
`getResolutionStrategy().dependencySubstitution(...)`

**Comment by CoXier** [comment]
@jjohannes  Now I have a question. If I does not have any substitution, how can I change all project to module depend? Actually I want to do that in a loop, because every substitution is similar.

**Comment by CoXier** [comment]
**Another question:**

Can I invoke `getResolutionStrategy().dependencySubstitution(...)`  after project evaluating ?

**Comment by jjohannes** [comment]
You can iterate `rootProject.getSubprojects()` and then add a rule for each subproject. A rule will only have an effect if there actually is a dependency on the corresponding subproject.

There is no need to add the rules in `afterEvaluate {}`, although it should not be a problem. You can register them at any time before the dependencies are resolved.

**Comment by CoXier** [comment]
@jjohannes Sorry I have not explained my question clearly yet.

For example, there is 30 modules A, B and C and so on. In build.gradle of A module:

```java
// A build.gradle
implementation project(":B")
implementation project(":C")
implementation project(":D")
implementation project(":E")
...
```
Now how can I add substitutions for B，C, D, and E ...

**Comment by CoXier** [comment]
Finally, I know how to do what I want. Thanks a lot, all guys @jjohannes @ljacomet . Have a nice day.
