### ISSUE TITLE
Improve mapping of dynamic version selectors to Maven POM

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1232]
Original issue: https://issues.gradle.org/browse/GRADLE-3224

### Expected Behavior

The generated `pom.xml` uses the resolved version for a dependency when declared with a dynamic version e.g. `+` or `latest.release` in the build script e.g.

```
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>1.5</version>
    <scope>runtime</scope>
</dependency>
```

### Current Behavior

Both plugins use the dynamic version in the generated `pom.xml` file e.g.

```
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>+</version>
    <scope>runtime</scope>
</dependency>
```

**Comment by t4gedieb** [comment]
1+

**Comment by thomas-klambauer** [comment]
Hi all! Are there any plans / schedule to address this? Best regards, Thomas

**Comment by bmuschko** [comment]
At the moment a fix is not scheduled. We are happy to accept community contributions though if you feel like you want to have this sooner.

**Comment by mnlipp** [comment]
The workaround suggested [here](https://stackoverflow.com/questions/20959558/in-gradle-how-can-i-generate-a-pom-file-with-dynamic-dependencies-resolved-to-t/32353697#32353697) works quite well for me (with minor adaptions) using gradle 4.1. It shouldn't be that hard to merge it in the code for someone who knows the environment.

```
pom.withXml {
	// Generate map of resolved versions
	Map resolvedVersionMap = [:]
	Set<ResolvedArtifact> resolvedArtifacts = configurations.compile.getResolvedConfiguration().getResolvedArtifacts()
	resolvedArtifacts.each {
		ModuleVersionIdentifier mvi = it.getModuleVersion().getId();
		resolvedVersionMap.put("${mvi.getGroup()}:${mvi.getName()}", mvi.getVersion())
	}
	Set<ResolvedArtifact> testResolved = configurations.testCompile.getResolvedConfiguration().getResolvedArtifacts()
	testResolved.each {
		ModuleVersionIdentifier mvi = it.getModuleVersion().getId();
		resolvedVersionMap.put("${mvi.getGroup()}:${mvi.getName()}", mvi.getVersion())
	}

	// Update dependencies with resolved versions
	if (asNode().dependencies) {
		asNode().dependencies.first().each {
			def groupId = it.get("groupId").first().value().first()
			def artifactId = it.get("artifactId").first().value().first()
			it.get("version").first().value = resolvedVersionMap.get("${groupId}:${artifactId}")
		}
	}
}
```

**Comment by adammurdoch** [comment]
It would be better if the title of this issue reflected some use case(s) to be solved, rather than describing an implementation. Sometimes you want the versions used to build and test the thing being published, to let consumers know a combination of versions that is known to work, sometimes you want to use the original constraints, to let the consumer know which versions it can select from. Often you want _both_.

We certainly don't want to change the behaviour of the publishing plugins so that the _only_ option is that the published metadata includes the versions used to build the thing.

**Comment by mnlipp** [comment]
> We certainly don't want to change the behaviour of the publishing plugins so that the only option is that the published metadata includes the versions used to build the thing.

But you are aware of the fact that a pom with a + in the version is invalid? That's what I currently get if a dependency has a + in its version part and what makes consumers of the pom fail. This is not about a special use case, this is about a bug: MavenPublishing (new) generates invalid pom if + is used in (gradle) dependencies' versions.

**Comment by oehme** [comment]
This could be solved by translating `+` to a Maven-compatible version range that roughly means the same thing. I agree with Adam that we shouldn't just change it to the other extreme.

**Comment by mnlipp** [comment]
More or less by accident, I just discovered a work-around. It isn't mentioned in the gradle documentation (at least I couldn't find it where it should be: https://docs.gradle.org/current/userguide/dependency_management.html) but obviously gradle supports the version range notation from maven! I changed my uses of '+' to the maven notation and voilà, dependencies are resolved during build as expected and end up in the pom.xml as specified. The support for maven version ranges should *definitely* be documented! Would have saved me a lot of time.

**Comment by oehme** [comment]
Simply don't use that syntax, but use Maven version range syntax for your dependencies instead.

**Comment by fcurts** [comment]
How does this help? I don't want version ranges in the POM.

**Comment by oehme** [comment]
If that's your preference then you can use the nebula.resolved-pom plugin.

**Comment by grv87** [comment]
For fixing `1.+` in POMs see #3466

**Comment by bigdaz** [comment]
It is now possible to publish the _resolved versions_ via `maven-publish`, rather than the _declared versions_: https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies.

**Comment by quaff** [comment]
```groovy
dependencies {
	api "org.testcontainers:testcontainers:latest.release"
}
publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			versionMapping {
				usage("java-api") {
					fromResolutionOf("runtimeClasspath")
				}
				usage("java-runtime") {
					fromResolutionResult()
				}
			}
			suppressAllPomMetadataWarnings()
		}
	}
}
```
result in `RELEASE` version instead of resolved version
```xml
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
      <version>RELEASE</version>
      <scope>compile</scope>
    </dependency>
```
Is it a bug? @bigdaz
