### ISSUE TITLE
Feature request: add EnumProperty to improve Kotlin DSL

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#12321]
### Expected Behavior

Sample interface:

```java
public interface EnumProperty<T extends Enum<T>> extends Property<T> {
    void set(@Nullable String name);
}
```

Potential implementation:

```java
@Override
public void set(@Nullable String name) {
    if (getType() == null || !Enum.class.isAssignableFrom(getType())) {
        return;
    }
    if (name == null) {
        set((T) null);
        return;
    }

    String enumName = name.toUpperCase()
            .replace('-', '_')
            .replace(' ', '_');
    T value = Enum.valueOf(getType().asSubclass(Enum.class), enumName);
    set(value);
}
```

### Current Behavior

Currently, the Kotlin DSL has to use fully qualified and imported types to set `Property<Enum>` whereas the Groovy DSL can simply use string names. It would be nice if the Kotlin DSL could do the same.

**Comment by ephemient** [comment]
An extension function in the DSL could also do the trick.

```kotlin
inline fun <reified T : Enum<T>> Property<T>.set(name: String?) = set(
    name
        ?.splitToSequence('-', ' ')
        ?.joinToString('_')
        ?.let { java.lang.Enum.valueOf(T::class.java, it) }
)
```

**Comment by aSemy** [comment]
Thanks to the new assignment overloading in Gradle 8.2 ([announced as experimental in v8.1.1](https://docs.gradle.org/8.1.1/release-notes.html#experimental-simple-property-assignment-in-kotlin-dsl-scripts)), this is now possible on an enum-by-enum basis by defining an extension function:

```kotlin
fun Property<Values>.assign(value: String) {
  set(Values.valueOf(value))
}
```

### Example usage

```kotlin
enum class Values {
  FOO,
  BAR,
  BAZ
}

abstract class MyTask : DefaultTask() {
  @get:Input
  abstract val prop: Property<Values>
}

fun Property<Values>.assign(value: String) {
  set(Values.valueOf(value))
}

tasks.register<MyTask>("myTask") {
  prop = Values.FOO // assignment overload provided by Gradle
  prop = "FOO"      // uses custom assignment overload, defined above
}
```


### All enums

This extension function should enable assignment overloading for _all_ `Property<Enum<*>>` properties, but I suspect this is risky because it's not possible to opt-out of the assignment overloading, and it would affect _all_ Gradle Kotlin DSL files.

```kotlin
inline fun <reified T: Enum<T>>Property<T>.assign(value: String) {
  val enumValue = enumValueOf<T>(value)
  set(enumValue)
}
```

Perhaps enums could opt-in to string-assignment overload using an interface that the Enum could implement as a marker?


```kotlin
interface EnumStringAssignmentOverload

enum class AssignmentOverloadedValue : EnumStringAssignmentOverload {
  FOO,
  BAR,
  BAZ
}
```

#### Example usage
 

```kotlin 
abstract class MyTask : DefaultTask() {
  // string-assignment will be available for this property
  @get:Input
  abstract val prop1: Property<AssignmentOverloadedValue>
  // string-assignment NOT available for this property
  @get:Input
  abstract val prop2: Property<RegularValue>
}

// only enable string-assignment for enums that implement the marker-interface
inline fun <reified T>
    Property<T>.assign(value: String)
    where T : Enum<T>, T : EnumStringAssignmentOverload {
  val enumValue = enumValueOf<T>(value)
  set(enumValue)
}

tasks.register<MyTask>("myTask") {
  prop1 = AssignmentOverloadedValue.FOO // assignment overload provided by Gradle
  prop1 = "FOO"                         // uses custom assignment overload, defined above
  
  prop2 = RegularValue.FOO // assignment overload provided by Gradle
  prop2 = "FOO" // ERROR Type mismatch
}
```

**Comment by lptr** [comment]
What the user wants to say is "`prop1` should be set to the `FOO` value". I agree that having to say `prop1 = Values.FOO` is more verbose than `prop1 = "FOO"`. However, by allowing string assignment we lose compiler support, which is a biggie.

Ideally, I think we should have `prop1 = FOO` and have `FOO`. Can we somehow hint IntelliJ to always do static imports for enum values in the context of Kotlin DSL?

**Comment by ephemient** [comment]
> Ideally, I think we should have `prop1 = FOO` and have `Values.FOO` be statically imported.

Instead, the language is moving towards allowing unqualified names when in specific contexts: https://youtrack.jetbrains.com/issue/KT-16768

I don't know if that will work with the assignment plugin or if additional effort is required.

**Comment by lptr** [comment]
That sounds exactly like the right solution to this problem. Let's close this then.

**Comment by eskatos** [comment]
This is an issue with the Kotlin IDE support, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please upvote or/and add your use case to https://youtrack.jetbrains.com/issue/KT-16768
