### ISSUE TITLE
GenerateModuleMetadata writes wrong file names in case of customized artifact publications.

### ISSUE THREAD

**Issue by ams-tschoening** [gradle/gradle#12339]
### Expected Behavior

The file names available in `*.module` should match the file names created by an actual publication, even if that and the repo-layout have been (slightly) customized.

### Current Behavior

The file names available in `*.module` seem to always use the name of the artifact in combination with its revision, even if the publication removed the latter by purpose. The publication creates a file named `some_lib.jar`, while `*.module` references the same files as `some_lib-0.1.0.jar`. That latter file doesn't exist in the repo and because Gradle's metadata is preferred by default, builds fail.

### Context

I'm using a slightly customized Ivy-publication with a slightly customized repo-layout NOT combining artifact and revision name into one file name. The layout is the following:

    [organization]/[module]/[revision]/[artifact](-[classifier]).[ext]

That worked pretty well for Gradle 5.6, files have been created as expected. While those files are still being created exactly the same way as before, with `GenerateModuleMetadata` the content of `*.module` is preferred over the available `ivy.xml` and builds fail, because the former file references not existing file names.

I additionally didn't find any way to influence how `GenerateModuleMetadata` generates file names. Looking at the source, it seems publications itself render file names, but that leads to different results for some reason in my case.

    private void writeArtifact(PublicationInternal publication, PublishArtifact artifact, JsonWriter jsonWriter) throws IOException {
        if (artifact instanceof PublishArtifactInternal) {
            if (!((PublishArtifactInternal) artifact).shouldBePublished()) {
                return;
            }
        }
        PublicationInternal.PublishedFile publishedFile = publication.getPublishedFile(artifact);

        jsonWriter.beginObject();
        jsonWriter.name("name");
        jsonWriter.value(publishedFile.getName());
        jsonWriter.name("url");
        jsonWriter.value(publishedFile.getUri());

        jsonWriter.name("size");
        jsonWriter.value(artifact.getFile().length());
        writeChecksums(artifact, jsonWriter);

        jsonWriter.endObject();
    }

### Steps to Reproduce 

The attached archive contains an example publishing things into `${HOME}/Downloads/ghi` using `gradlew publish` , which can be changed in `buildSrc\src\main\gradle\publish\ams_ivy\CurrUser.gradle`. That creates an IVY-repo containing a `gradle.module` containing the unexpected file names.

[de.am_soft.build.gradle.zip](https://github.com/gradle/gradle/files/4249742/de.am_soft.build.gradle.zip)
![Clipboard03](https://user-images.githubusercontent.com/6223655/75244308-dca50000-57cb-11ea-8614-da6e9af60a3b.png)

### Your Environment

gradlew 6.2.1

**Comment by ljacomet** [comment]
Initial investigation indicates that fixing will be quite involved. So instead the current plan will be to disable Gradle module metadata generation when an Ivy repository contains a custom repository layout.
