### ISSUE TITLE
Transitive dependencies are not found when using composite builds with custom publish metadata

### ISSUE THREAD

**Issue by svermeulen** [gradle/gradle#12331]
Given the following three projects (foo, bar, and app), where app depends on bar depends on foo, I'd like to be able to simply install bar in project app and have library foo automatically installed as well.  This does work correctly with the following scripts:

# Project 'foo' build.gradle

```
plugins {
  id "maven-publish"
}

repositories {
  mavenLocal()
}

group = "com.test2.foo"
version = "0.0.1"

def distZip = file("${buildDir}/dist.zip")
def distFile = file("${buildDir}/Foo.txt")

tasks.register("createDistFile") {
  outputs.file(distFile)
  doLast {
    distFile.delete()
    distFile.parentFile.mkdirs()
    distFile.text = "foo output 1"
  }
}

tasks.register("assembleZip", Zip) {
  dependsOn "createDistFile"
  from distFile
  archiveName = distZip.name
  destinationDir distZip.parentFile
}

publishing {
  publications {
    main(MavenPublication) {
      artifact(distZip) {
        builtBy tasks.named("assembleZip")
      }
    }
  }

  repositories {
    mavenLocal()
  }
}
```

# Project 'bar' build.gradle

```
plugins {
  id "maven-publish"
  id "base"
}

repositories {
  mavenLocal()
}

group = "com.test2.bar"
version = "0.0.1"

def distZip = file("${buildDir}/dist.zip")
def distFile = file("${buildDir}/Bar.txt")

tasks.register("createDistFile") {
  outputs.file(distFile)
  doLast {
    distFile.delete()
    distFile.parentFile.mkdirs()
    distFile.text = "bar output 2"
  }
}

tasks.register("assembleZip", Zip) {
  dependsOn "createDistFile"
  from distFile
  archiveName = distZip.name
  destinationDir distZip.parentFile
}

artifacts {
  "default" distZip, {
    builtBy tasks.named("assembleZip")
  }
}

publishing {
  publications {
    main(MavenPublication) {
      artifact(distZip) {
        builtBy tasks.named("assembleZip")
        pom.withXml {
          def dependenciesNode = asNode().appendNode('dependencies')

          def dependencyNode = dependenciesNode.appendNode('dependency')
          dependencyNode.appendNode('groupId', "com.test2.foo")
          dependencyNode.appendNode('artifactId', "foo")
          dependencyNode.appendNode('version', "0.0.1")
        }
      }
    }
  }

  repositories {
    mavenLocal()
  }
}
```

# Project 'app' build.gradle

```
repositories {
  mavenLocal()
}

configurations {
  api
}

dependencies {
  api "com.test2.bar:bar:0.0.1"
  // This should be automatically installed when bar is installed
  // api "com.test2.foo:foo:0.0.1"
}

tasks.register("installLibs", Copy) {
  dependsOn configurations.api
  destinationDir = file("${buildDir}/libs")
  configurations.api.each { config ->
    from zipTree(config)
  }
  doFirst {
    destinationDir.deleteDir()
  }
}
```

# The Problem

When using the above scripts, this can be verified by running `installLibs` in project app and verifying that both `Bar.txt` and `Foo.txt` are installed into the `build/libs` directory.

However, if I change the `settings.gradle` file in project 'app' to be this:

```
rootProject.name = 'app'

includeBuild '[PATH TO BAR PROJECT]'
```

Then if I run `./gradle installLibs` again for the app project, I find that `Foo.txt` is no longer installed.  Is there a way to manually specify this build metadata for project bar, so then when it is used with includeBuild that its transtive dependencies get included?

I noticed that transitive dependencies + composite builds works fine with java projects, so this must be possible somehow already, but I see no way to do this

**Comment by jjohannes** [comment]
@svermeulen this does not work using `pom.withXml`. The information you add there is only for tweaking the POM file. Gradle does not add it to its model of the project.

Instead you should use Gradle's dependency management. Since you are not using the "java-library" plugin, you need to define your own _Configuration_. If you also want to publish you need to define your own _Component_ for publishing. There you define how the dependencies are mapped to the POM.

```
configurations {
  myConfiguration
}
dependencies {
   myConfiguration("com.test2.foo:foo:0.0.1")
}
...
```

You can read up more about the topics here:
- https://docs.gradle.org/current/userguide/cross_project_publications.html
- https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components

**Comment by ljacomet** [comment]
Closing as an answer has been provided and there is nothing to do on the Gradle side.
