### ISSUE TITLE
"Package name 'abc' does not corresponed to the file path 'xyz'" errors are ignored when using subprojects

### ISSUE THREAD

**Issue by immortaleeb** [gradle/gradle#12341]
### Expected Behavior
Gradle should detect mismatches between package names and directory paths and should not ignore errors like:

```
Package name 'com.example.hello' does not correspond to the file path 'foobar'
```

### Current Behavior
Gradle seems to ignore errors like

```
Package name 'com.example.hello' does not correspond to the file path 'foobar'
```

when a class in an incorrect package directory structure is present in a subproject.

### Context
I discovered this issue when renaming packages in my IDE. Something went wrong during one of the renames which renamed a package folder to a folder with the name `com.example.foo.bar`.
I missed this during my code changes and committed and deployed this to production.
Our CI pipeline did not complain (since we're using gradle) and the application is running fine in production, but when working on the code in an IDE it (correctly) complains about classes not being in the right folders.

### Steps to Reproduce 
The minimal requirement to reproduce is that I have a class in a subproject whose directory path does not match with the package path in its import statement.

You can find minimal example at https://github.com/immortaleeb/gradle-package-bug.

In this example the class `Hello` should be in the package `com.example.hello` but its physical location is in the root folder `foobar` (see `src/main/java/foobar`).
The JVM correctly recognizes this as an error when you try to build the class via the command line:

```
Package name 'com.example.hello' does not correspond to the file path 'foobar'
```

But gradle happily builds this project into a jar and runs the main class:

```
$ ./gradlew run
16:28:29: Executing task 'run'...

> Task :hello:compileJava UP-TO-DATE
> Task :hello:processResources NO-SOURCE
> Task :hello:classes UP-TO-DATE

> Task :hello:run
Hello there!

BUILD SUCCESSFUL in 164ms
2 actionable tasks: 1 executed, 1 up-to-date
16:28:29: Task execution finished 'run'.
```

### Your Environment
I tested this with the following combinations:
* OpenJDK 8 with a gradle wrapper on version 5.6.2
* OpenJDK 8 with a gradle wrapper on version 6.2.1
* OpenJDK 11 with a gradle wrapper on version 6.2.1

**Comment by ljacomet** [comment]
I understand the usability issue, but I do not think that `javac` errors out on that by default. Can you share which command line invocation you used to make it fail?

On the contrary, for `javac` the location of the _source_ file does not matter. It however matters for the _compiled_ class file, as otherwise the JVM will fail to locate the file.

As for having a solution in Gradle, did you try configuring compilation with `-Werror` which would cause all warnings to be treated as errors?

**Comment by immortaleeb** [comment]
>  I do not think that `javac` errors out on that by default. Can you share which command line invocation you used to make it fail?

You're right, this does not seem to be an error that `javac` does by default. I'm using IntelliJ which was reporting this as an error and I assumed it got this from running `javac`. Turns out it's actually a feature built into the IDE.

Since javac does not do this kind of checking, I can not expect gradle to do this either.
I'll consider the issue closed.
