### ISSUE TITLE
Gradle doesn't forward command line options like "--settings-file" for included builds.

### ISSUE THREAD

**Issue by ams-tschoening** [gradle/gradle#12356]
### Expected Behavior

If additional program arguments for executing Gradle have been provided, those should be used for included builds as well.

![Clipboard01](https://user-images.githubusercontent.com/6223655/75374843-46f19980-58cd-11ea-8b4a-74e23340425e.png)

### Current Behavior

The first executed build uses additional program arguments like expected, but at some point it gets lost for included builds.

### Context

I was trying to [work around some limitations](https://discuss.gradle.org/t/how-to-make-buildship-use-a-specific-settings-gradle-instead-of-the-default-one/35061) of Buildship using two different settings files, `settings.gradle` and `settings_buildship.gradle`. The latter got configured in Eclipse only and contains additional statements needed to make Buildship better support composite builds. Those shouldn't be necessary in general and aren't outside of Buildship, therefore I wanted to manage those in two different files to make both files easier to maintain.

When executing Gradle on the shell to test things, the first `settings_buildship.gradle` for the concrete project I execute tasks for is used. But [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) shows that for all included builds `settings.gradle` is used instead.

    19:42:59,9047672	java.exe	10052	ReadFile	C:\Users\tschoening\Downloads\ghi\de.am_soft.sm_mtg.api\settings_buildship.gradle	SUCCESS	Offset: 0, Length: 247, Priority: Normal
    19:42:59,9218030	java.exe	10052	ReadFile	C:\Users\tschoening\Downloads\ghi\de.am_soft.sm_mtg.parser.ks\settings.gradle	SUCCESS	Offset: 0, Length: 49, Priority: Normal

The command line used to actually read the files looks the same in both cases:

    "C:\Program Files\Java\jdk-8\bin\java.exe" -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=windows-1252 -Duser.country=DE -Duser.language=de -Duser.variant -cp C:\Users\tschoening\.gradle\wrapper\dists\gradle-6.2.1-all\4vp27twfwktff74t6xt7byg0o\gradle-6.2.1\lib\gradle-launcher-6.2.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.2.1

### Steps to Reproduce 

    gradlew build --settings-file=settings_buildship.gradle

[ghi.zip](https://github.com/eclipse/buildship/files/4257587/ghi.zip)

### Your Environment

Gradle 6.2.1

Because I first recognized this with [Buildship itself ](https://github.com/eclipse/buildship/issues/973) on the shell as well, I created a bug for that, too.

**Comment by ams-tschoening** [comment]
Explicitly not using already available daemons doesn't change a thing as well. The following still leads to `settings.gradle` being read for included builds.

    gradlew clean --settings-file=settings_buildship.gradle --no-daemon

The [docs](https://docs.gradle.org/current/userguide/composite_builds.html#composite_build_intro) contain the following statement:

> [...]Included builds do not share any configuration with the composite build, or the other included builds. Each included build is configured and executed in isolation.

If that's the reason for not honoring command line flags in the composite by included builds, that should be reconsidered. Using different versions of the Gradle wrapper itself by included builds [doesn't work as well](https://discuss.gradle.org/t/how-to-properly-upgrade-gradle-in-composite-builds/30015), so that statement is already not strictly true. The current behaviour seems pretty inconsistent: `--settings-file` is not honored by included builds, `--no-daemon` in theory is because the included builds are processed by the daemon of the composite itself only, different versions of Gradle wrapper for included builds and the composite don't work again etc.

Things like `--settings-file` changing a build fundamentally should be somehow forwarded to included builds. The only workaround I found so far is providing some flag, checking for that in `settings.gradle` and apply a different file instead. The good thing is that this seems to work with and without using the daemon and that the Gradle-dialog of Eclipse provides a way to forward JVM-properties.

    gradlew clean -DuseBuildshipWorkaround=true

At the top of `settings.gradle`:

	if (System.getProperty('useBuildshipWorkaround'))
	{
		apply from: 'settings_buildship.gradle'
		return
	}

**Comment by jjohannes** [comment]
The `--settings-file` and `--build-file` options are now deprecated. In general, configuration required to run a build should be encoded in the build itself. You should not have two different settings file. If you need a workaround, you should be able to encode it inside your single `settings` file (e.g. using `if` check).

Command line options like `--no-daemon` usually influence the whole build run and not details of a single build. 

With respect to composite builds, it is expected that included builds can work on their own (e.g. a workaround should be encoded in the settings file of the included build). There are no plans to changes this.

**Comment by ams-tschoening** [comment]
> [...]In general, configuration required to run a build should be encoded in the build itself. You should not have two different settings file.

Of course it makes sense to use individual setting files for some environments in which builds need to be processed pretty specifically to e.g. [work around some limitation](https://discuss.gradle.org/t/how-to-make-buildship-use-a-specific-settings-gradle-instead-of-the-default-one/35061). This is not different to any other approach to make a build modular.

> If you need a workaround, you should be able to encode it inside your single settings file (e.g. using if check).

Which is NOT easier than simply using configs provided by Eclipse already to tell Gradle for Eclipse to use some special workaround for Eclipse ONLY without any complicated runtime checks, bloating an otherwise Eclipse-agnosting settings file etc.

```
apply from: 'buildSrc/src/main/gradle_6.2/settings/CustomFileLoader.gradle'
if (System.getProperty('loadedSettingsCustomFile')) { return }
```

Having those lines in the settings file is NOT a feature making the build easier to maintain.

> Command line options like --no-daemon usually influence the whole build run and not details of a single build.

As said already, than fix your documentation about independence of included builds, which is simply wrong regarding versions of Gradle wrappers, the above flag etc.

> With respect to composite builds, it is expected that included builds can work on their own (e.g. a workaround should be encoded in the settings file of the included build).

It doesn't make any sense to force me to implement the above workaround into ALL individual included builds, while ONE single Eclipse config would have been enough otherwise.

> There are no plans to changes this.

Wrong decision.
