### ISSUE TITLE
Disable maven-metadata.xml SHA256 and SHA512 upload warnings to Nexus

### ISSUE THREAD

**Issue by flemingadam** [gradle/gradle#12355]
### Expected Behavior
The flag `systemProp.org.gradle.internal.publish.checksums.insecure=true` should disable publishing of sha-256 and sha-512 checksums for maven-metadata.xml files.  See #11308.  I do not expect warnings when the disable flag is explicitly set.

### Current Behavior
Publishing appears to be successful, but console is polluted with set of warnings like the following for each artifact that is published:
```
Cannot upload checksum for snapshot-maven-metadata.xml. Remote repository doesn't support sha-256. Error: Could not PUT 'http://.../x.y.z-SNAPSHOT/maven-metadata.xml.sha256'. Received status code 400 from server: Invalid path for a Maven 2 repository
Cannot upload checksum for snapshot-maven-metadata.xml. Remote repository doesn't support sha-512. Error: Could not PUT 'http://.../x.y.z-SNAPSHOT/maven-metadata.xml.sha512'. Received status code 400 from server: Invalid path for a Maven 2 repository
Cannot upload checksum for module-maven-metadata.xml. Remote repository doesn't support sha-256. Error: Could not PUT 'http://.../x.y.z-SNAPSHOT/maven-metadata.xml.sha256'. Received status code 400 from server: Invalid path for a Maven 2 repository
Cannot upload checksum for module-maven-metadata.xml. Remote repository doesn't support sha-512. Error: Could not PUT 'http://.../x.y.z-SNAPSHOT/maven-metadata.xml.sha512'. Received status code 400 from server: Invalid path for a Maven 2 repository
```

### Context
I'm publishing a library with multiple custom Gradle plug-ins to Nexus OSS Repository 3.  Nexus does not support sha-256 and sha-512 (see https://issues.sonatype.org/browse/NEXUS-21802 for feature request).  A feature flag has been implemented but did not appear to alter anything when applied via `gradle.properties` or CLI argument (see #11308).

This does not appear to prevent anything, but it prints out hundreds of unnecessary warning lines in my build, making it difficult to find meaningful warnings.

### Steps to Reproduce 
Publish custom Gradle plug-ins to a repository to Nexus OSS 3.

Optionally:
* add `systemProp.org.gradle.internal.publish.checksums.insecure=true` to `gradle.properties`
* add `-Dorg.gradle.internal.publish.checksums.insecure=true`

### Your Environment
Gradle 6.2.1 (latest release as of bug report)
Nexus OSS Repository 3.21.1-01 (latest release as of bug report)
Windows 10

**Comment by ljacomet** [comment]
From your report, the flag is not properly configured as setting it should completely bypass the publication of SHA256 and SHA512 checksum files.

Could you try printing that system property from a publication block in your build and see if it is set properly?

**Comment by flemingadam** [comment]
I ran the exact same code today and the error warnings no longer print out.  I can't think of any changes on my end that would have affected this, but I will assume I made an error of some sort.  I apologize for taking up your time and appreciate the help.
