### ISSUE TITLE
Investigate why Kotlin projects don't show an improvement with VFS retention

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#12350]
We don't see any improvements from enabling VFS retention with santa tracker Kotlin. We need to understand why.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
For a fully up-to-date build, the execution time seems to go down quite a bit:
0.8s -> 0.35s.
See https://scans.gradle.com/s/wd4r6dupjhske/performance/execution vs https://scans.gradle.com/s/sc6iqhm5wygok/performance/execution

For the non-abi change, snapshotting time also goes down:
0.48s -> 0.27s (https://scans.gradle.com/s/egodifshldnau/performance/execution vs. https://scans.gradle.com/s/i62ruf3iauia4/performance/execution) - though it isn't noticed since it mostly happens outside of the critical path:

No optimizations:
![image](https://user-images.githubusercontent.com/423186/75781729-075bff00-5d5e-11ea-807d-29d076d117a7.png)

With VFS retention:
![image](https://user-images.githubusercontent.com/423186/75781923-5efa6a80-5d5e-11ea-989e-303167348a73.png)


[vfs-retention-chrome-traces.zip](https://github.com/gradle/gradle/files/4281598/vfs-retention-chrome-traces.zip)

**Comment by lptr** [comment]
Conclusion: we do see improvements on the scale we expect them, but they are shadowed by the long time it takes to actually run the Kotlin tasks. All is well on the VFS retention side.
