### ISSUE TITLE
Better error messaging when resolution fails

### ISSUE THREAD

**Issue by chali** [gradle/gradle#12358]
### Expected Behavior
I would like to see simplified error messages with original causes even without using `--info` to increase the logging level.

### Current Behavior
During the resolution process we got errors like this:

```
* What went wrong:
Execution failed for task ':lego-server:generateLock'.
> Could not resolve all dependencies for configuration ':lego-server:compile'.
   > Could not resolve netflix:nfi18n-core:2.161.
     Required by:
         project :lego-server
      > Skipped due to earlier error
   > Could not resolve netflix:reloaded-zen:1.0.
     Required by:
         project :lego-server
      > Skipped due to earlier error
   > Could not resolve netflix:mutation-stream-client:latest.release.
     Required by:
         project :lego-server
      > Skipped due to earlier error
```

There was about 1000 lines of such output. Without `--info` you couldn't even see what is the "earlier error"

### Context
We use ranges to specify the dependencies version. We use ivy metadata. When gradle tries to determine what is the latest version from the range it sequentially queries from the most recent version until it finds a matching version. Our range is `latest.release` before a latest release is found each newer snapshot metadata is queried. One of those snapshots returned 500 when GET for metadata was issued.

**Comment by ljacomet** [comment]
This can still happen and Gradle should not swallow / hide the earlier error.

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by big-guy** [comment]
@tresat Timebox if we can make this any better
