### ISSUE TITLE
Attribute "without_test_code" is missing in .classpath file for project references

### ISSUE THREAD

**Issue by NHendricks** [gradle/gradle#12354]
Assume you have 2 gradle projects (project a and projectb) in a multi project setup where projectb is referencing project a. 
Apply the java and the eclipse plugin on both projects (projecta and projectb) and define a project dependency to projecta.
The .classpath file for project b contains the line <classpathentry kind="src" path="/projecta" />. Here an attribute <attribute name="without_test_code" value="true"/> is missing. Therefore it is possible to access test classes of project a in tests of project b. This compiles in Eclipse but it fails in the Gradle build.

### Expected Behavior
The attribute <attribute name="without_test_code" value="true"/> (available since Eclipse 4.8) should be generated for project references.

### Current Behavior
The attribute is missing.

### Context
When writing tests in Eclipse we would like to prevent the possibility to access foreign unit test classes.

### Your Environment
We tested this with Gradle 6.2.1 and Eclipse 4.14.

**Comment by donat** [comment]
To work around the problem, you can add the following snippet to your build scripts:
```
plugins {
  id 'eclipse'
}

eclipse.classpath.file.whenMerged {
  entries.findAll { it instanceof org.gradle.plugins.ide.eclipse.model.ProjectDependency }
         .each { it.entryAttributes['without_test_code'] = 'true' }
}
```

**Comment by mduft** [comment]
This destroyed our eclipse projects after a gradle update, as we're sharing some test code between projects. Now we have to do the exact opposite to your workaround, and set `without_test_code` to `false`

**Comment by jetztgradnet** [comment]
Same here, with Gradle 6.7 and Eclipse 2020-09 this does not work when test code in project B depends on test code from project A. Regular Gradle build works (as dependencies are declared correctly), but BuildShip somehow doesn't see this dependency. 
The workaround described by @mduft worked for us as well.

**Comment by foto-andreas** [comment]
Hi,

I think that this was not the correct solution. Same problems here - the test dependencies are now broken.

Andreas

**Comment by thefang12** [comment]
same issue as well the plugin should figure out whether to set it to false or true based on gradle configurations

**Comment by donat** [comment]
> Same here, with Gradle 6.7 and Eclipse 2020-09 this does not work when test code in project B depends on test code from project A. Regular Gradle build works (as dependencies are declared correctly), but BuildShip somehow doesn't see this dependency.

@jetztgradnet Can you please send me a minimal project exhibiting the problem?

**Comment by jetztgradnet** [comment]
Unfortunately not, as this is now working again for me and we have meanwhile upgraded to Gradle 6.8. IIRC there was also some mention about Gradle test dependencies in the release notes in 6.7.1 or so.
