### ISSUE TITLE
Could not target platform: 'Java SE 13' using tool chain: 'JDK 11 (11)'.

### ISSUE THREAD

**Issue by YiHan-HuaHua** [gradle/gradle#12368]
Gradle 6.2.1 
Execution failed for task ':compileJava'.
> Could not target platform: 'Java SE 13' using tool chain: 'JDK 11 (11)'.

![Uploading image.png…]()

**Comment by blindpirate** [comment]
Your image is broken.

**Comment by YiHan-HuaHua** [comment]
![21582806066_ pic](https://user-images.githubusercontent.com/27755602/75444844-2abe2d00-599f-11ea-94cc-dc3d6bd6d893.jpg)

![31582806078_ pic_hd](https://user-images.githubusercontent.com/27755602/75444849-33166800-599f-11ea-8f4b-282b6573365c.jpg)

![41582806119_ pic](https://user-images.githubusercontent.com/27755602/75444865-3c073980-599f-11ea-9328-356e110e7538.jpg)

**Comment by YiHan-HuaHua** [comment]
I don't know why the image is corrupted, I can't access it after uploading

**Comment by YiHan-HuaHua** [comment]
I don't know why the image is corrupted, I can't access it after uploading

**Comment by blindpirate** [comment]
It seems like your IDEA configuration is wrong. Note that Project SDK != the Java SDK you're using to import Gradle project. You'd better check the Gradle settings in IDEA.

**Comment by YiHan-HuaHua** [comment]
我本地的 Java 环境是 13.0.2  ,  idea 项目的 SDK 也是配置的 13.0.2 , Gradle 的 Java 插件
sourceCompatibility 和 targetCompatibility 配置的都是 JavaVersion.VERSION_13

**Comment by blindpirate** [comment]
Please do not use Chinese.

**Comment by YiHan-HuaHua** [comment]
Ok, thank you very much. My problem has been solved.

**Comment by YiHan-HuaHua** [comment]
My problem has been solved
