### ISSUE TITLE
Deprecate 'default' and 'archives' configurations for resolving and declaring dependencies

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#12379]
The 'default' and 'archives' configurations are added to each project that applies the 'base' plugin (which is almost every project). They are currently still required for backward compatibility. But using them is generally discouraged.

They definitely should not be used for resolving. Thus we should deprecate that. 

It will also have the positive effect that the `dependencies` task won't list and resolve them anymore.

And then `gradle dependencies --write-locks` also won't write (unnecessary) lock files for them.

**Comment by ljacomet** [comment]
Fixed through #12460
