### ISSUE TITLE
Bug: uploadArchives task is not parallel safe

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1237]
When running an older version of `MavenMultiProjectPublishIntegrationTest` we were testing one invocation of Gradle's `uploadArchive` task with two subprojects that both tried to upload artifacts to a local maven repo.

### Context
[This gist](https://gist.github.com/eljobe/b7fea64faeca62c9cf27) shows the stack trace.

Please note, this bug is not easily reproducible. I've run a shell loop 1000 times and not been able to reproduce the problem. 

### Steps to Reproduce (for bugs)
I set up [this sample project](https://github.com/eljobe/experiments/tree/master/deps) to reproduce the issue. And I actually did get it to fail one time where I forgot the stacktrace flag. But, in a loop of 1000 invocations of `rm -rf maven-repo; gradle uploadArchives -s` I have not been able to make it happen again. My `gradle.properties` file looks like this:
```
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=6
```

### Your Environment
This was tested on Gradle 3.1 on macOS. Likely affects all platforms.

**Comment by bigdaz** [comment]
The `maven` plugin (together with the core `Upload` task) are being replaced by the `maven-publish` plugin. As such, we don't plan on making changes to improve the (now legacy) `uploadArchives` behaviour. 
Expect to see the `maven` plugin deprecated in Gradle 6.x, for possible removal in Gradle 7.0.
