### ISSUE TITLE
How to skip project even though project included

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#12370]
### Related Samples

My root project contains 30+ subprojects. In order to speed up build, I use `Substitution` to replace some projects with modules. For example:

```
// build.gradle of project A
implementation project("B")
implementation project("C")
```

As you see, B and C now is useless however there are configuring every build life cycle. It seems to be useless. So how can I skip these two projects although they are included. 

You may ask me: why don't you not include these two projects? Yes I must, because there are required by project A. If I don't include them,  `gradle`  will report error: B and C project not found.

**Comment by big-guy** [comment]
What do you mean by "substitution"?

**Comment by CoXier** [comment]
> What do you mean by "substitution"?

Such as:

```java
substitutions.substitute(":B").with("com.example:B:1.0.0")
```
