### ISSUE TITLE
how publishToMavenLocal task do only a flavor publication

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#12389]
### Expected Behavior

`publishToMavenLocal` can do only a flavor publication.

### Current Behavior

`publishToMavenLocal` does all flavors publication.

### Context

There are three flavor name: A、B、C in my project. I can upload only A flavor like this:

```java
// only upload A of account module
./gradlew :account:publishAPublicationToMavenLocal
// only upload A of profile module
./gradlew :profile:publishAPublicationToMavenLocal
// only upload A of feed module
./gradlew :feed:publishAPublicationToMavenLocal
// only upload A of news module
./gradlew :news:publishAPublicationToMavenLocal
....
// there are another 30+ modules
```
Above task works well, however now I want to add a new task and the new task depends above all tasks. I do like this:

```java
target.rootProject.subprojects.forEach {project->
    val publishTask = project.tasks.getByName("publishToMavenLocal")
    newTask.dependsOn(publishTask)
}
```
From https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:install
> The task name follows the pattern of publishPubNamePublicationToMavenLocal. Each of these tasks is wired into the publishToMavenLocal aggregate task

As you see, I can not get `profile:publishAPublicationToMavenLocal` directly because I can not find it. However if I use `project.tasks.getByName("publishToMavenLocal")`, it will upload all flavors: A,B and C.

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
If I understand correctly, you should be able to simply do: `./gradlew publishAPublicationToMavenLocal` which will invoke that task on _all_ projects that declare it.
