### ISSUE TITLE
build too slow on proxy network even add offline option

### ISSUE THREAD

**Issue by shift-morikawa** [gradle/gradle#12403]
Hello , please help us.

We use gradlew for Selenium Project on proxy network.
command like below

```cmd
gradlew clean test --tests MyTest
```

It takes 5-7 minute to build.
And so many debug log such like `Emitting XX memory status event` was loggerd on gradle log.
We tried to add `--offline` option, but it comes same.
When we tried on no-proxy network , the problem was gone.

Does anybody know why it is so slow?

### Context

I use gradle for GUI automation test by using selenium , selenide , appium.
Please see library dependencies below.

### Your Environment

- OS:Windows10
- Java:AdoptOpenJDK 8.0.222
- Selenium:3.141.59
- Gradle: 4.10.3
- Selenide:5.6.1
- Appium Version:1.15.1

### gradle log (partical)

```log
12:06:03.384 [DEBUG] [TestEventLogger]     12:06:03.380 [Test worker] DEBUG com.codeborne.selenide.webdriver.WebDriverFactory - browser=jp.shiftinc.automation.driver.AppiumDriverProvider
12:06:03.385 [DEBUG] [TestEventLogger]     12:06:03.385 [Test worker] DEBUG com.codeborne.selenide.webdriver.WebDriverFactory - browser.version=null
12:06:03.387 [DEBUG] [TestEventLogger]     12:06:03.386 [Test worker] DEBUG com.codeborne.selenide.webdriver.WebDriverFactory - remote=null
12:06:03.388 [DEBUG] [TestEventLogger]     12:06:03.387 [Test worker] DEBUG com.codeborne.selenide.webdriver.WebDriverFactory - browserSize=null
12:06:03.389 [DEBUG] [TestEventLogger]     12:06:03.388 [Test worker] DEBUG com.codeborne.selenide.webdriver.WebDriverFactory - startMaximized=false
12:06:05.480 [LIFECYCLE] [org.gradle.process.internal.health.memory.MemoryManager]
12:06:05.480 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 8463499264, Free: 1839992832}
12:06:05.480 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 4705484800, Committed: 1873281024}
12:08:10.489 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 4705484800, Committed: 1873281024}

... omitting

12:09:15.735 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 4705484800, Committed: 1873281024}
12:09:20.480 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 8463499264, Free: 1659760640}
12:09:20.480 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 4705484800, Committed: 1873281024}
12:06:03.315 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
12:06:03.315 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :mobilenative:test
```

### library Dependencies

org.springframework:spring-aspects:5.2.1.RELEASE: aspects
org.junit.jupiter:junit-jupiter-api:5.6.0-M1
com.codeborne:selenide:5.5.1
io.github.bonigarcia:webdrivermanager:3.7.1
io.appium:java-client:7.2.0
io.qameta.allure:allure-gradle:2.8.1
io.qameta.allure:allure-selenide:2.13.1
org.yaml:snakeyaml:1.25
org.apache.pdfbox:pdfbox:2.0.17
com.googlecode.java-diff-utils:diffutils:1.3.0
ch.qos.logback:logback-classic:1.2.3
com.sun.mail:javax.mail:1.6.2
javax.xml.bind:jaxb-api:2.3.1
org.apache.ant:ant:1.10.7
ru.yandex.qatools.ashot:ashot:1.5.4
org.glassfish.jersey.core:jersey-client:2.29.1
org.glassfish.jersey.inject:jersey-hk2:2.29.1
org.glassfish.jersey.connectors:jersey-apache-connector:2.29.1
com.google.code.gson:gson:2.8.6
org.aspectj:aspectjrt:1.9.5
org.aspectj:aspectjweaver:1.9.5
org.springframework:spring-tx:5.2.1.RELEASE
com.univocity:univocity-parsers:2.8.4
org.projectlombok:lombok:1.18.10: compileOnly
org.projectlombok:lombok:1.18.10: annotationProcessor
org.springframework:spring-aspects:5.2.1.RELEASE: aspects
org.junit.jupiter:junit-jupiter-api:5.6.0-M1
com.codeborne:selenide:5.5.1
io.github.bonigarcia:webdrivermanager:3.7.1
io.appium:java-client:7.2.0
io.qameta.allure:allure-gradle:2.8.1
io.qameta.allure:allure-selenide:2.13.1
org.yaml:snakeyaml:1.25
org.apache.pdfbox:pdfbox:2.0.17
com.googlecode.java-diff-utils:diffutils:1.3.0
ch.qos.logback:logback-classic:1.2.3
com.sun.mail:javax.mail:1.6.2
javax.xml.bind:jaxb-api:2.3.1
org.apache.ant:ant:1.10.7
ru.yandex.qatools.ashot:ashot:1.5.4
org.glassfish.jersey.core:jersey-client:2.29.1
org.glassfish.jersey.inject:jersey-hk2:2.29.1
org.glassfish.jersey.connectors:jersey-apache-connector:2.29.1
com.google.code.gson:gson:2.8.6
org.aspectj:aspectjrt:1.9.5
org.aspectj:aspectjweaver:1.9.5
org.springframework:spring-tx:5.2.1.RELEASE
org.projectlombok:lombok:1.18.10: compileOnly
org.projectlombok:lombok:1.18.10: annotationProcessor
org.springframework:spring-aspects:5.2.1.RELEASE: aspects
org.junit.jupiter:junit-jupiter-api:5.6.0-M1
com.codeborne:selenide:5.5.1
io.github.bonigarcia:webdrivermanager:3.7.1
io.appium:java-client:7.2.0
io.qameta.allure:allure-gradle:2.8.1
io.qameta.allure:allure-selenide:2.13.1
org.yaml:snakeyaml:1.25
org.apache.pdfbox:pdfbox:2.0.17
com.googlecode.java-diff-utils:diffutils:1.3.0
ch.qos.logback:logback-classic:1.2.3
com.sun.mail:javax.mail:1.6.2
javax.xml.bind:jaxb-api:2.3.1
org.apache.ant:ant:1.10.7
ru.yandex.qatools.ashot:ashot:1.5.4
org.glassfish.jersey.core:jersey-client:2.29.1
org.glassfish.jersey.inject:jersey-hk2:2.29.1
org.glassfish.jersey.connectors:jersey-apache-connector:2.29.1
com.google.code.gson:gson:2.8.6
org.aspectj:aspectjrt:1.9.5
org.aspectj:aspectjweaver:1.9.5
org.springframework:spring-tx:5.2.1.RELEASE
org.junit.jupiter:junit-jupiter-params:5.6.0-M1
org.junit.vintage:junit-vintage-engine:5.6.0-M1
org.seleniumhq.selenium:selenium-java:3.141.59
io.qameta.allure:allure-gradle:2.8.1
org.slf4j:slf4j-log4j12:1.7.28
br.com.six2six:fixture-factory:3.1.0
io.qameta.allure:allure-junit5:2.13.1
org.projectlombok:lombok:1.18.10
org.springframework:spring-aspects:5.2.1.RELEASE: aspects
org.junit.jupiter:junit-jupiter-api:5.6.0-M1
com.codeborne:selenide:5.5.1
io.github.bonigarcia:webdrivermanager:3.7.1
io.appium:java-client:7.2.0
io.qameta.allure:allure-gradle:2.8.1
io.qameta.allure:allure-selenide:2.13.1
org.yaml:snakeyaml:1.25
org.apache.pdfbox:pdfbox:2.0.17
com.googlecode.java-diff-utils:diffutils:1.3.0
ch.qos.logback:logback-classic:1.2.3
com.sun.mail:javax.mail:1.6.2
javax.xml.bind:jaxb-api:2.3.1
org.apache.ant:ant:1.10.7
ru.yandex.qatools.ashot:ashot:1.5.4
org.glassfish.jersey.core:jersey-client:2.29.1
org.glassfish.jersey.inject:jersey-hk2:2.29.1
org.glassfish.jersey.connectors:jersey-apache-connector:2.29.1
com.google.code.gson:gson:2.8.6
org.aspectj:aspectjrt:1.9.5
org.aspectj:aspectjweaver:1.9.5
org.springframework:spring-tx:5.2.1.RELEASE
com.univocity:univocity-parsers:2.8.4

**Comment by ljacomet** [comment]
You state yourself that the issue disappears when using a non proxied network. This means that the issue is unlikely to be in Gradle. It could be that your Selenium tests take a much longer time to establish connections, etc ...

Unless you can pinpoint the issue to a Gradle component, there is nothing that can or should be done by the Gradle team at this stage.
