### ISSUE TITLE
tests fail when root project (/directory) name contains "-"-character

### ISSUE THREAD

**Issue by Barblebee** [gradle/gradle#12400]
When I followed the "Building Java Libraries" guide I used a different directory name ("java-library" instead of "demo"). When I executed the build the test failed. I recreated the project with different testing frameworks (all 4) while using the same directory name. The tests always failed. I found out that It worked when I created the directory with a "_"-character instead of "-". It seems as if the "-" was substituted by "." as I got the following error:

java.lang.SecurityException: Prohibited package name: java.library

Build-Scan: https://gradle.com/s/tn5qudznruw7o

    Am I not allowed to use "-"-characters?
    Is it a bug of gradle, java or something else? What is the reason for that?

I just saw that there is an open issue under (gradle/guides) from lacasseio (Example build fails #264 ). Could be that he has the same problem. Sorry, when I did something wrong with my posts. This is my 3rd post ever. 

Thanks in advance!
Kai

**Comment by big-guy** [comment]
Hi @Barblebee 

This is a restriction from the JVM itself.  User code packages aren't allowed to begin with the package `java`. 

The reason you see a difference between `-` and `_` has to do with how we convert a project name into a package name when generating a project. We take the project name `java-library` and turn that into the package name `java.library` and we take the project name `java_library` and turn that into the package name `java_library`. `java_library` is legal and `java.library` is not.

We _could_ special case this and choose a different name for you, but most projects will already be using a different package name anyways--usually, a [reversed domain name](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).  Just avoid using `java` as the name for your package.

**Comment by Barblebee** [comment]
Hi big-guy!
Thank you very much for your fast response and your good explanation. I was nearly sure that the problem had to do merely with the "-"-char.
Have a good day :-)
