### ISSUE TITLE
Gradle not capturing all application test output

### ISSUE THREAD

**Issue by asaikali** [gradle/gradle#12423]
Project to reproduce issue is at https://github.com/asaikali/stray-output as you can see 
for a plain boot application generated from start.spring.io output is not fully captured.

```
 |master S:1 U:5 ✗| → ./gradlew build 
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :test
2020-03-04 10:03:39.248  INFO 41278 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-03-04 10:03:39.249  INFO 41278 --- [extShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-03-04 10:03:39.249  INFO 41278 --- [extShutdownHook] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
2020-03-04 10:03:39.251  INFO 41278 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-03-04 10:03:39.255  INFO 41278 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

BUILD SUCCESSFUL in 29s
5 actionable tasks: 5 executed
```

Java version 11 being used.

```
 |master S:1 U:5 ✗| → java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

**Comment by vlsi** [comment]
@asaikali , can you please clarify why you believe there's a defect in Gradle?

**Comment by asaikali** [comment]
If you look at the test report console output under `build/reports/tests/test` as shown in the screen shout below it is missing the shutdown hook output that is printed to the gradle console. It seems that there is a race condition of some kind since some output is escaping. 

<img width="1894" alt="Screen Shot 2020-03-05 at 8 29 11 AM" src="https://user-images.githubusercontent.com/945207/75986203-a2b6b680-5ebb-11ea-97b8-ab99820bfab6.png">

The default gradle console output does not produce a long list of output that scrolls up the screen, it just prints out on a single line what tasks are executing and the final summary, for how many tasks were executed, up to date ... etc.

```
./gradlew build

BUILD SUCCESSFUL in 779ms
5 actionable tasks: 5 up-to-date
```

I very much like the distraction free output. I am expecting gradle to either print out everything from the execution of a spring boot program or nothing.

**Comment by sbrannen** [comment]
I haven't checked out the implementations for the last three things logged, but the first two (`org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor` and `org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean`) both implement `org.springframework.beans.factory.DisposableBean` which causes their `destroy()` methods to be invoked by a JVM shutdown hook (see `org.springframework.context.support.AbstractApplicationContext.registerShutdownHook()`).

Thus, I assume that has something to do with the behavior you're experiencing.

**Comment by saagar2000** [comment]
Just would like to set up scenario for further discussion - You may already be aware that gradle test worker processes capture the test logs and redirect to gradle file location.  In case of shutdown hook, logs are generated asynchronously and after the test case execution by which time the worker processes has already teared down the redirection and the shutdown hook logs ends up appearing on the console. More details here https://stackoverflow.com/questions/60018839/how-to-turn-off-output-from-shutdown-hooks-in-gradle-boot-tests.

**Comment by asaikali** [comment]
this might be related to https://discuss.gradle.org/t/capturing-test-output-from-multiple-threads/13464/4
