### ISSUE TITLE
Cannot find direct download link for Gradle on https://gradle.org/

### ISSUE THREAD

**Issue by veita** [gradle/gradle#12422]
On https://gradle.org/ there are seemingly no direct download links for the binary Gradle distribution available.

Copying link locations gives something like
 https://gradle.org/next-steps/?version=6.2.1&format=bin

However such links do not necessarily work on with tools other than browsers (e.g. wget).

**Comment by big-guy** [comment]
There's a direct link available on the page you linked (https://gradle.org/next-steps/?version=6.2.1&format=bin).

**Comment by veita** [comment]
OK, sorry, I've only looked on the pages where the the download links are provided, but not on the page that ist displayed after the download started.
