### ISSUE TITLE
Task created by rules cannot be configured by legacy code then mutated by further rules

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1242]
Because of a limitation of the rules/legacy bridging, we have introduced a configuration ordering issue between model and legacy lands. Essentially, a task created by rules cannot be configured by non-rules code (legacy plugin, build script, etc) and then later mutated by further rules. 

### Context
This issue was originally reported by this forum post: https://discuss.gradle.org/t/illegalstateexception-cannot-add-mutate-rule/10541

### Steps to Reproduce (for bugs)
Consider the following build script:

```
apply plugin: 'base'
task foo
assemble.dependsOn foo
apply plugin: 'java'
```

<details><summary>The result is the following error:</summary>
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mark/Desktop/gradle/build.gradle' line: 4

* What went wrong:
A problem occurred evaluating root project 'gradle'.
> Failed to apply plugin [class 'org.gradle.language.base.plugins.LanguageBasePlugin']
   > Cannot add rule org.gradle.language.base.plugins.LanguageBasePlugin$Rules#attachBinariesToAssembleLifecycle(org.gradle.api.Task, org.gradle.platform.base.BinaryContainer) for model element 'tasks.assemble' at state Initialized as this element is already at state GraphClosed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
</details>

**Comment by lacasseio** [comment]
No additional work will be done on the software model plugins unless it's a blocker for current users. This is not a blocker so I'm closing this issue. Reopen on [gradle/gradle-native](https://github.com/gradle/gradle-native).
