### ISSUE TITLE
ThirdPartyGradleModuleMetadataSmokeTest resources use a hardcoded version of Kotlin but should use AbstractSmokeTest.TestedVersions.kotlin instead

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#12425]
This is a test maintenance issue.

# Current behavior

Upgrading the embedded Kotlin to 1.3.70 there were 26 test resource files that required updates. Half of the diff is from updating the resources for the GMM smoke test, starting at https://github.com/gradle/gradle/pull/12424/files#diff-680780de644898975da0785571e8e871

# Expected behavior

Updating `AbstractSmokeTest.TestedVersions.kotlin` should be enough.

Fixing this might be a good oportunity to `@Unroll` the test on the supported kotlin versions.

**Comment by jjohannes** [comment]
Thanks. I missed that when creating the tests. Thanks for updating this time.

I don't think an _unroll_ is necessary here as changes in Gradle are unlikely to change anything with older Kotlin versions only.

This test is here to observe/track/react to changes done on the Kotlin side.

**Comment by eskatos** [comment]
That test is still on Kotlin 1.4. This issue is still relevant

**Comment by ov7a** [comment]
This issue is no longer relevant. 
See:
* https://github.com/gradle/gradle/pull/26800
