### ISSUE TITLE
Register watchers for newly added file locations during the build

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#12437]
Whenever we snapshot a new location, we start watching the new location, if we haven’t been watching it already.

We still ignore changes coming in to outputs during the build, as in https://github.com/gradle/gradle/issues/12438.

### Implementation notes

Now we need to have some state about what we are currently watching. The implementation of what we are currently watching is different between Windows/macOS (hierarchical watches) and Linux (non-hierarchical watches). For OSes supporting hierarchical watches, we will probably never need to update watches, while for Linux we will be updating the watches continuously.

At the end of the build we won’t need to register/deregister any watches.

#### Os specific notes:

- *Windows/macOS*: We won’t do many updates since we watch the project directory. Tracking watched directories is cheap, since we don’t watch many. We will probably never unwatch a watched directory.
- *Linux*: We track each directory in the VFS. When a directory is removed from the VFS we need to cancel the watch since it will possibly be removed from the disk which causes the OS to cancel the watch. When we add a directory to the VFS, we need to start watching it. So the invariant we could try to keep is to have a watch for all elements of the VFS and update both things simultaneously.

See https://docs.google.com/document/d/15sJC1vDwTwOy5W4-jliNbWENkbvrT54mQJV13qLulWg/edit#heading=h.diwjwyqecf66

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
How does this relate to https://github.com/gradle/gradle/issues/11902?

**Comment by wolfs** [comment]
It is the same. I didn't find #11902 when I opened this one.

**Comment by wolfs** [comment]
Fixed by #12628.
