### ISSUE TITLE
reproducible native builds

### ISSUE THREAD

**Issue by marcpawl** [gradle/gradle#1243]
Native builds should have options to be byte-for-byte reproducible.
In order to do this for gcc:
build-id needs be able to be specified.
-I include paths should be relative, otherwise the directory that you compile in changes the output.
-L library paths should be relative, otherwise the directory that you compile in changes the output.

### Expected Behavior
Relative paths are used as displayed in options.txt

### Current Behavior
options.txt displays absolute paths

-I
/home/xx/yy/zz/libs/bb/include

### Context
Try to move from Makefiles to gradle, but one of our requirements is that any developer should be able to check out the code base, build, and have identical MD5 checksums of the executables.

### Steps to Reproduce (for bugs)
Native project with 

```groovy
   c {
        source {
            srcDir "."
            include "*.c"
        }
        exportedHeaders {
            srcDir "../include"
        }
    }
```

### Your Environment
Gradle 3.3 on Fedora 25

**Comment by lacasseio** [comment]
No additional work will be done on the software model plugins unless it's a blocker for current users. Please try the new native plugin to see if the issue is still valid and reopen on [gradle/gradle-native](https://github.com/gradle/gradle-native).
