### ISSUE TITLE
Cannot create service of type TaskExecuter using ProjectExecutionServices.createTaskExecuter() 

### ISSUE THREAD

**Issue by harshshingala** [gradle/gradle#12436]
Gradle Build error in android studio 3.6.1 Gradle Version 5.6.4

Cannot create service of type TaskExecuter using ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #22 of type ReservedFileSystemLocationRegistry.
> Cannot create service of type ReservedFileSystemLocationRegistry using ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.

**Comment by davidoort** [comment]
I have the same

**Comment by theejkb** [comment]
Same here, need help please :/

**Comment by alexiordan** [comment]
I ran into the same issue when trying to deploy another project on the same virtual device. 
For me it was solved by selecting "Wipe Data" for that Virtual Device in Android Virtual Device Manager.

**Comment by ndangnguyen** [comment]
I'm facing this issue too, any answer?

**Comment by Will-1-Am** [comment]
Same issue here launching brand new Flutter project.  Flutter launches fine on iOS Simulator interestingly enough.

**Comment by beauzo** [comment]
I ran into this issue on my mac with a Flutter project when gradle cache consumed disk space to exhaustion. From that point on, and despite clearing cache to recover disk space, every gradle-based Flutter command would result in the above error. Restarting the machine worked for me.

**Comment by peetonn** [comment]
Encountered this exact error with Unreal Engine project for Android stored on external drive. Android Studio fails to build the gradle project. When project is copied over to the local hard drive, no issues building it.

**Comment by gyakhoe** [comment]
Yeah, same issue here. I face the same issue from the flutter project that I stored in external drive and used VS code. I made android project from android studio and faced the same issue. I have updated the android studio to 3.6.3.

**Comment by Weightang** [comment]
I have the same,I use an external hard drive

**Comment by Weightang** [comment]
It turned out that there was a problem with my gradle environment variable setting, I fixed it

**Comment by peetonn** [comment]
@Weightang what was wrong with the environment/what did you check? maybe i have similar issue

**Comment by Weightang** [comment]
@peetonn gradle environment,  GRADLE_HOME  Configuration.

**Comment by n27jain** [comment]
What did you change

**Comment by t-animal** [comment]
I had this error in a flutter project and mysteriously there was a (zombie?) gradle process lingering around (possibly holding file locks). After killing it, flutter built again.

**Comment by YousefAlsayad** [comment]
I have the same issue

**Comment by mohit-kaushik** [comment]
I am working on React Native, I had this issue while building the project with gradle for the first time using "react-native run-android", I resolved this by changing the project directory permission.
sudo chown -R <Your Username>  <Path of prjoject folder or . for current directory>

**Comment by sayanmondal31** [comment]
I faced the same problem when running application then I open a terminal in vscode  and write `flutter clean` command and then run my code and it works.

**Comment by aloev** [comment]
> @peetonn gradle environment, GRADLE_HOME Configuration.

Could you elaborate more on that answer please ?

**Comment by anteeek** [comment]
Running `chown <your-username>:<your-username> <project-root-dir>` and then `chmod 777 -R <project-root-dir>` fixed it for me. You might want to make your keystores more restrticted after that

**Comment by rajesh-shanthi** [comment]
Remove the caches directory under c:\Users\<Your user name directory>\.gradle directory worked for me.

**Comment by siaron** [comment]
same issue

**Comment by ademcayir** [comment]
I just try to create "empty activity" application with latest and greatest version of Android Studio, and I get this error out of no reason. What a shame that you can not even a create a hello world application with Android Studio without a great effort.

Same here

**Comment by SodaisNasir** [comment]
I encountered the same issue in react native I resolved it by stopping Gradle and then executing the step again 

gradle --stop

**Comment by Weightang** [comment]
Sorry to open this issue again. If you put the project on an external hard drive, you need to give Android Studio full access to the disk on the Mac. Hope to solve your problem

**Comment by Fatima-Karaki** [comment]
I am facing the same issue in android studio please help!!! I am panicking |_|
help me or my team will kick me out

**Comment by coling-git** [comment]
Same issue while building a react-native project with gradle for the first time using "react-native run-android"

**Comment by hayelom123** [comment]
the same here

**Comment by hegyibalint** [comment]
> @tresat try this: https://github.com/tassilo-posegga/Firefly Basically I created a new empty multiplatform project and upgraded all dependencies.

Can anybody in this thread check the reproducer?
On my side, it built fine multiple times fine - but I would like to see this fail.

Some questions also you could help us out:
- Is the issue intermittent, or it's constantly breaking?
- After fixing the issues by various means, is it coming back immediately, comes back later, or disappears forever?


Environment info:
```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.15 (Oracle Corporation 11.0.15+3)
OS:           Linux 5.16.11-zen1-1-zen amd64
```

**Comment by ljacomet** [comment]
Closing given the reproducer seems to work fine
