### ISSUE TITLE
internal_error when attempting to upload to repository behind cloudflare

### ISSUE THREAD

**Issue by sanjay900** [gradle/gradle#1244]
### Expected Behavior
I would expect uploadArchives to succeed

### Current Behavior
uploadArchives fails with Failed to deploy artifacts: Could not transfer artifact org.sosy-lab:java-smt:jar:1.0.2 from/to remote (https://maven.tangentmc.net/repository/victoria): Received fatal alert: internal_error

### Context
This issue affects me as i am unable to push code to my nexus instance, and i would like to depend upon this project from somewhere else.

### Steps to Reproduce (for bugs)
https://github.com/sanjay900/java-smt-maven
I am attempting to deploy this plugin to a nexus repository proxied behind cloudflare.

### Your Environment
 * Build scan URL: 
https://scans.gradle.com/s/nbcf5ejp47ahs#infrastructure

**Comment by eriwen** [comment]
@sanjay900 The problem seems to be caused by an SSL error. Can you explain why you would believe this to be a Gradle issue?

**Comment by sanjay900** [comment]
Ive seen some other projects that had similar issues and they were fixed by the developers.

**Comment by oehme** [comment]
This is unlikely to be a problem in Gradle itself, since the error is coming from the SSL layer. If there is evidence that this is actually a Gradle problem, please don't hesitate to follow up with more details here.
