### ISSUE TITLE
Configuring the Jar task's manifest gives an Incubating warning

### ISSUE THREAD

**Issue by Mahoney** [gradle/gradle#12447]
When configuring the `org.gradle.api.tasks.bundling.Jar` task via Kotlin, IntelliJ highlights a call to `manifest` as a call to an `Incubating` feature:
```kotlin
val jar by tasks.getting(Jar::class) {
  manifest {} // manifest is highlighted as Incubating
}
```

It’s because it's a method on the supertype (`org.gradle.jvm.tasks.Jar.manifest(Action<? super Manifest> configureAction)`) which is not overridden on `org.gradle.api.tasks.bundling.Jar`, and the entire `org.gradle.jvm.tasks` package is `Incubating`.

The `org.gradle.jvm.tasks` package seems to have been incubating ever since it was extracted from `org.gradle.api.tasks.bundling` in 2014: https://github.com/gradle/gradle/commit/2ab01d0c99106a0f1bc2304c787f37ae2ce40ef6#diff-b72732e284c9c175dea297a8fedff67d

`Incubating` should either be removed from `org.gradle.jvm.tasks` or else the following should be added to `org.gradle.api.tasks.bundling.Jar` to export the overloaded `manifest` method:
```java
    @Override
    public Jar manifest(Action<? super Manifest> configureAction) {
        super.manifest(configureAction);
        return this;
    }
```

**Comment by jjohannes** [comment]
Thanks @Mahoney for reporting this. We simply missed this one. Fixed in `6.4`.
