### ISSUE TITLE
Determine workspace location in execution engine

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12449]
For incremental units of work such as tasks and project-bound artifact transforms we have an `identity` (basically the location of the workspace for the work) and a `cache key` (that is a unique identifier for the outputs). For this reason we have `UnitOfWork.getIdentity()`. This works well for tasks, because `getIdentity()` is trivial to calculate early in the execution, while calculating the cache key requires input snapshots, so it happens later, when such snapshots are available (and only if needed). For project-bound transforms the situation is fairly similar, though the calculation of the identity is a bit more complicated.

This doesn't work so well for non-incremental (=immutable) work, though. Such work include global artifact transforms and the different parts of Kotlin script compilation. For these work items identity _is_ the cache key.

This means that for now we need to pre-calculate the identity/cache key _before_ invoking the execution engine (and then just expose the cache key as a single input to the execution engine). This means that we miss out on the features provided by the execution engine to snapshot inputs and calculate the cache key (i.e. we need to duplicate the code), and the work we do outside the execution engine will not be captured in build operations.

We can improve this by introducing the concept of the workspace to the execution engine. A good representation of what we need to do is to show how the pipeline would need to change:

```diff
 return new DefaultWorkExecutor<>(
       new LoadExecutionStateStep<>(
       new MarkSnapshottingInputsStartedStep<>(
       new SkipEmptyWorkStep<>(
       new ValidateStep<>(validationWarningReporter,
+      CaptureInputsBeforeExecutionStep(/* ... */,
-      new CaptureStateBeforeExecutionStep(buildOperationExecutor, classLoaderHierarchyHasher, valueSnapshotter, overlappingOutputDetector,
       new ResolveCachingStateStep(buildCacheController, buildScanPlugin.isBuildScanPluginApplied(),
+      DetermineWorkspaceLocationStep(/* ... */,
+      CaptureOutputsBeforeExecutionStep(/* ... */,
       new MarkSnapshottingInputsFinishedStep<>(
       // ...
```

Meaning that we'd need to break up `CaptureStateBeforeExecutionStep` into two separate steps: one capturing inputs, the other the outputs. This works because we have the following dependencies:

```text
  input snapshots      (provided by CaptureInputsBeforeExecutionStep)
    ^
    |
  cache key            (provided by ResolveCachingStateStep)
    ^
    |
  workspace location   (provided by DetermineWorkspaceLocationStep)
    ^
    |
  output snapshots     (provided by CaptureOutputsBeforeExecutionStep)  
```

Note that for tasks we don't currently need to determine a workspace location. However, we have a plan for Gradle to auto-configure task output locations, in which case a workspace provider for tasks would make sense.

Moreover, having a `Workspace` abstraction could work to collect all output properties of any unit of work, including tasks.

---
cc: @gradle/build-cache, @eskatos

**Comment by wolfs** [comment]
The problem here is that the first step - `LoadExecutionStateStep` - also depends on the identity of the work.

**Comment by lptr** [comment]
Good point.

It seems that we need to differentiate between _incremental_ work (that requires an execution history, and an identity different from the cache key), and _non-incremental/immutable_ work (that doesn't require an execution history, or an identity separate from the cache key). Both of these types of work could make use of a workspace determined as described above.

We can have two different pipelines for this, the immutable one having none of the stale file cleanup etc. steps required for the incremental one. We could get away without snapshotting the outputs for immutable work at all.

**Comment by wolfs** [comment]
If the immutable work is not up-to-date, we need to clean up the workspace. For determining whether it is up-to-date, we need the input snapshots and can use those to determine the workspace/identity. And then we would load the execution history so we can check if the last execution succeeded and nobody messed with the outputs.

**Comment by lptr** [comment]
Right. What I'm suggesting is we can also drop the up-to-date check on the immutable workspace, and replace it with existence check. This could work well if we made these cache directories atomic by moving the results into the directory.

We don't check the integrity of our other caches AFAIK. We could make the integrity check a switch to enable if the user wants more strictness in their workflow. Either way we could have a mode where immutable work output is never snapshotted.

Not sure how useful this is, as most immutable work _is_ used in the same build in some downstream work unit, so... And we are planning to include output hashes in the cached artifact, which means we'd need to snapshot the outputs that we want to store anyway, so...

Okay, probably not worth trying to optimize this out.

**Comment by lptr** [comment]
FTR, I just talked with @britter and Maven caching snapshots their outputs because of the cache store use case.

**Comment by lptr** [comment]
> For determining whether it is up-to-date, we need the input snapshots and can use those to determine the workspace/identity. And then we would load the execution history so we can check if the last execution succeeded and nobody messed with the outputs.

I'm not sure what you are suggesting here, but if you are proposing to move the loading of the current state to later in the pipeline, then that's not trivial. We'd either need to break up `SkipEmptyWorkStep` to determine early if we can skip things, and then clean things up once the previous outputs are loaded. Or we need to move it to later in the pipeline.

The latter will make projects that apply language plugins they don't use (such as the build-tool itself) somewhat slower to execute. Maybe we can re-evaluate the regression when we had the discussion about the role of fully up-to-date performance tests.

In any case, `SkipEmptyWorkStep` should come later in the pipeline, at least after `ValidateStep`, so we learn about problems with the configuration of empty tasks, too. Doing this will probably break some builds, so we need to be careful.

At best we could move `SkipEmptyWorkStep` after `CaptureInputsBeforeExecutionStep`, and use the input snapshots to determine emptiness. This would slow things down even more, but again, maybe that's an acceptable regression.
