### ISSUE TITLE
Using withSourcesJar() produces deprecation warnings

### ISSUE THREAD

**Issue by dawi** [gradle/gradle#12451]
I am using Gradle 6.2.2.

I have seen that it is now possible to simplify the creation of a sources jar.

So instead of

```
val sourcesJar by tasks.registering(Jar::class) {
    group = LifecycleBasePlugin.BUILD_GROUP
    archiveClassifier.set("sources")
    from(sourceSets.main.get().allSource)
    dependsOn(tasks.classes)
}
```

I can simply tell gradle to do this via:

```
java {
    withSourcesJar()
}
```

This seems to work well, but it introduced the warning that "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.":

```
Copying or archiving duplicate paths with the default duplicates strategy has been deprecated. This is scheduled to be removed in Gradle 7.0. Duplicate path: "de/xxx/Xxx.java". Explicitly set the duplicates strategy to 'DuplicatesStrategy.INCLUDE' if you want to allow duplicate paths. Consult the upgrading guide for further information: https://docs.gradle.org/6.2.2/userguide/upgrading_version_5.html#implicit_duplicate_strategy_for_copy_or_archive_tasks_has_been_deprecated
```

I figured out that this warning is caused by having the following configuration in our build:

```
sourceSets {
    main {
        resources.srcDir("src/main/java")
    }
}
```

Is this a bug or expected behavior?

Regards, Daniel

**Comment by ljacomet** [comment]
Indeed the fact that you configure resources to include sources is what's causing the deprecation warning.
Why do you need to add the sources as resources in your project?
Unless you have a particular use case, this should not be needed at all.

**Comment by dawi** [comment]
Yes, I know, and I don't like the fact that we have to do this either.

The reason is that it is an apache wicket project, where it is a standard practice to have all files of a component in one place. Example: 
https://github.com/apache/wicket/tree/master/wicket-examples/src/main/java/org/apache/wicket/examples/datetime

Now if we don't add `src/main/java` to the `resources`, the resources will not land in `build/resources` and `build/libs/<component>.jar`.

**Comment by ljacomet** [comment]
Closing as there is no plan on changing the behavior in Gradle.

**Comment by dawi** [comment]
A simple solution is to configure the `sourcesJar` task like this:

```kts
tasks.named<Jar>("sourcesJar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
```
