### ISSUE TITLE
"error=7, Argument list too long" still an issue on nix

### ISSUE THREAD

**Issue by sonicsnes** [gradle/gradle#12453]
The pathing jar improvements in #11620 have solved 'argument list too long', but the length requirements aren't strict enough.

### Expected Behavior

JavaExec with a ridiculous number of classpath dependencies should not fail.

### Current Behavior

If string length of the classpath is above 131072 (the single arg strlen limit on linux), but the total command length is lower than 2097152, then gradle doesn't attempt to use a pathing jar, and the command fails with "error=7, Argument list too long".

### Steps to Reproduce 

`gradle run` with a project containing a classpath slightly over 132k characters.

### Your Environment

Gradle 6.2

**Comment by quad** [comment]
Workaround:

`org.gradle.internal.cmdline.max.length=131072`

**Comment by hborders** [comment]
I'm also seeing this on `macOS` `10.13.6` running Gradle `6.1.1` and Oracle JDK `1.8.0_181`

**Comment by hborders** [comment]
This seems like this same issue as https://github.com/gradle/gradle/issues/5754

**Comment by hborders** [comment]
https://github.com/gradle/gradle/issues/11907 indicates it was supposed to be fixed on `macOS` in Gradle 6.2, but the original reporter is using Gradle 6.2.

**Comment by hborders** [comment]
> Workaround:
> 
> `org.gradle.internal.cmdline.max.length=131072`

I had to add the following to my `gradle.properties`:

```
systemProp.org.gradle.internal.cmdline.max.length=131072
```

**Comment by fawaad** [comment]
I was running into a similar error when our CI was running our `detekt` gradle task. I tried all of the steps above but the fix ended up being an upgrade of our detekt plugin to `1.8.0`. 

For any folks running into this in the future, you may want to try upgrading the underlying dependencies, just in case.

**Comment by maxirosson** [comment]
I am seeing this issue on Gradle 6.5

**Comment by hborders** [comment]
I just got this again with a `kapt` task. I only get this intermittently, but when it happens, it's always on a `kapt` task. Knowledgeable People™️ told me to add this to my `gradle.properties` file:
```
kapt.use.worker.api=true
kapt.workers.isolation=none
```

**Comment by c4milo** [comment]
I'm using 6.6.1 and running into this as well.

**Comment by josemlechon** [comment]
Happening too in 6.7.1 . Is there a reliable solution?
