### ISSUE TITLE
mavenLocal is different from local repo?

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#12468]
---
cc: @gradle/build-cache

Hi all，

from gradle doc： https://docs.gradle.org/current/userguide/dependency_management.html?_ga=2.153774842.318125195.1583497031-966615681.1582185653#sec:case-for-maven-local

I know mavenLocal is not trusted by gradle cache because its content can be changed anytime. So I want to know where gradle can cache my local repo, such as ~/Desktop/repo location.

And is mavenLocal different from local repo?

**Comment by ljacomet** [comment]
Please use [the user forums](https://discuss.gradle.org/) or [Stackoverflow](https://stackoverflow.com/search?q=gradle&mixed=1) for this kind of question instead of opening issues.
