### ISSUE TITLE
plugin-publish-plugin: Allow user to specify publish API key and secret via plugin bundle DSL

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1246]
Should be possible to set publishing api key / secret via the plugin bundle DSL. This allows using environmental variables or other sources for these values, when setting via `gradle.properties` or system properties is not preferred.

The way the plugin consumes the api key and secret makes it difficult to use on build machine line TravisCI. One use-case for this is public CI systems that don't mask secure vars when echoing out the command line.

### Context
Original report: http://discuss.gradle.org/t/add-apikey-and-apisecret-to-pluginbundle-extension-for-plugin-publish-plugin/8636

### Workaround
```groovy
task setupPluginUpload << {
    def key=System.env.gradlePublishKey
    def secret = System.env.gradlePublishSecret

    if( !key || !secret)
    {
        throw new RuntimeException("gradlePublishKey and/or gradlePublishSecret are not defined environment variables")
    }

    System.properties.setProperty("gradle.publish.key", key)
    System.properties.setProperty("gradle.publish.secret", secret)
}

tasks.publishPlugins.dependsOn tasks.setupPluginUpload
```

**Comment by cortinico** [comment]
Bump since this issue is a bit stale. I also needed this kind of feature and I ended up applying the same fix. https://github.com/cortinico/kotlin-gradle-plugin-template/blob/1194fbbb2bc61857a76da5b5b2df919a558653de/plugin-build/plugin/build.gradle.kts#L43-L55

Is it possible to contribute somehow?

**Comment by cortinico** [comment]
Commenting as this is still a thing

**Comment by cortinico** [comment]
Commenting as this is still a thing :)

**Comment by cortinico** [comment]
Yup I've been moving to those env variables since a while
