### ISSUE TITLE
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory(). 

### ISSUE THREAD

**Issue by ct17b7** [gradle/gradle#12465]
* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type ChecksumService using BuildSessionScopeServices.createChecksumService().

**Comment by blindpirate** [comment]
We can't help you if you don't provide enough information. A reproducible sample would be great, but the following information is minimal required:

- JVM/OS/Gradle version
- Stacktrace (you can get it by adding `--stacktrace` argument)

Closing, please feel free to reopen.
