### ISSUE TITLE
maxParallelForks is feasible in mobile application 

### ISSUE THREAD

**Issue by JeffGaly** [gradle/gradle#12471]
Im trying to do a parallel execution using maxParallelForks .It works in desktop browser execution by executing 2 browser at a time .
I wish to execute 2 mobile applications at a time in android or ios devices.
Any suggestion would be grateful .

**Comment by big-guy** [comment]
Hey @JeffGaly 

This looks like a question and not a bug/feature report. You might have better luck getting it answered on our forums: https://discuss.gradle.org/

I'm not an Android developer, but this looks promising for what you want: https://firebase.google.com/docs/test-lab/
