### ISSUE TITLE
Dependency ordering issue when upgrading to Guava 28.2-jre

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12475]
When I upgraded to Guava `28.2-jre` (from `27.1-android`) the following tests started to fail:

Test | failures
-- | --
ResolutionResultApiIntegrationTest.each dependency is associated to its resolved variant [with fluid dependencies] | 3 failures in 2 configurations
ResolutionResultApiIntegrationTest.each dependency is associated to its resolved variant [without fluid dependencies] | 4 failures in 2 configurations
ResolutionResultApiIntegrationTest.reports duplicated dependencies in all variants [with fluid dependencies] | 4 failures in 2 configurations
ResolutionResultApiIntegrationTest.reports duplicated dependencies in all variants [without fluid dependencies] | 4 failures in 2 configurations

https://builds.gradle.org/viewLog.html?buildId=32330657

This seems to point to some unordered `Set` somewhere.

---
cc: @gradle/build-cache

**Comment by melix** [comment]
Could it be that Guava changed semantics of `ImmutableSet.of` and friends and are not order-preserving now?

**Comment by lptr** [comment]
I don't think `ImmutableSet` has changed order preservation. What I've seen is that `ListMultimap.values().stream()` now handles entries in a different order (see https://github.com/gradle/gradle/pull/12472/commits/7c10b74f1b09a5dca481cff2bb5ff52d8d6459b1).

**Comment by lptr** [comment]
The fact that `reports duplicated dependencies in all variants` is one of the problematic tests makes me think that the change is about handling the order of duplicate entries in one of the collections.

**Comment by ljacomet** [comment]
The change in behavior comes from the Guava `Platform.newHashSetWithExpectedSize` method, which has different implementations for the Android vs. JRE versions.
However the usage of a `HashMultimap` in `DefaultResolvedComponentResult` seems fishy, as it can affect consistent ordering of the result of `DefaultResolvedComponentResult.getDependenciesForVariant`
