### ISSUE TITLE
Build service installed via init script closes prematurely when `:buildSrc` sub-build is finished

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12488]
This has been observed with Gradle Profiler 0.9.2+ (after https://github.com/gradle/gradle-profiler/commit/53202a9a9497d4aba243bdcaf39930cc1c9c7f1c has been added). The profiler registers a build service to capture build operations here:

https://github.com/gradle/gradle-profiler/blob/71f7760e72d88b25108e6291b6f35f47ba3db935/src/main/java/org/gradle/profiler/buildops/BuildOperationInstrumentation.java#L46-L55

This works well for builds without a `:buildSrc` sub-build, but ones with it only gather statistics from the `:buildSrc` sub-build, but not from the actual root build itself.

Looking at this with @eskatos we have a strong suspicion that the problem is caused by the build service being closed after the `:buildSrc` build is finished here:

https://github.com/gradle/gradle/blob/d02b9d84c08dba64775fb9581e3280f88d319a21/subprojects/core/src/main/java/org/gradle/api/services/internal/DefaultBuildServicesRegistry.java#L224-L227

Whether the cause is the presence of a `:buildSrc` sub-build, or having the build service installed from an init script is also required is unclear at this point.

Once this issue is fixed it would be good to add tests for both `:buildSrc` and included builds.

---
cc: @gradle/build-cache

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/12602.

The profiler also needs to be changed so that it registers the listeners only for the root build:
- https://github.com/gradle/gradle-profiler/blob/master/subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java#L35
- https://github.com/gradle/gradle-profiler/blob/master/subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java#L44

**Comment by lptr** [comment]
It looks like the fix in https://github.com/gradle/gradle/issues/12488 has solved the issues in Gradle Profiler. At least the operation times reported by the profiler look realistic now. Why would we need to make changes in the profiler? If we did what you suggest, @adammurdoch, would that mean we'd not measure build operations in `:buildSrc`?

**Comment by lptr** [comment]
I've added a printout here:

https://github.com/gradle/gradle-profiler/blob/53202a9a9497d4aba243bdcaf39930cc1c9c7f1c/subprojects/build-operations/src/main/java/org/gradle/trace/buildops/BuildOperationTrace.java#L39-L46

And it seems we only register every build operation once even if there is no change in Gradle Profiler:

```text
* Running warm-up build #1
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler12285528953335052741build-ops-org.gradle.api.internal.tasks.execution.ExecuteTaskBuildOperationType
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler16391286394416597569build-ops-org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep$Operation
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler11645089503939708877build-ops-org.gradle.api.internal.artifacts.configurations.ResolveConfigurationDependenciesBuildOperationType
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler9194196319186792609build-ops-org.gradle.internal.execution.steps.SnapshotOutputsStep$Operation
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler8135548537467492609build-ops-org.gradle.api.internal.artifacts.transform.DefaultTransformer$FingerprintTransformInputsOperation
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler5040373793234611421build-ops-org.gradle.caching.internal.operations.BuildCacheArchiveUnpackBuildOperationType
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler1829079217629175008build-ops-org.gradle.api.internal.tasks.execution.ExecuteTaskActionBuildOperationType
>>>> Adding build-op listener: /var/folders/mz/pzpp4shn29d9hj35tccsbd240000gn/T/gradle-profiler486670611019128572build-ops-org.gradle.caching.internal.operations.BuildCacheArchivePackBuildOperationType
> Task :buildSrc:compileJava
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors
> Task :buildSrc:processResources
> Task :buildSrc:classes
> Task :buildSrc:jar
> Task :buildSrc:assemble
> Task :buildSrc:pluginUnderTestMetadata
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins
> Task :buildSrc:check
> Task :buildSrc:build
> Task :compileKotlin NO-SOURCE
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :spring-security-crypto:compileJava
```

**Comment by adammurdoch** [comment]
The change to gradle-profiler would mean that it's not registering multiple listeners all writing to the same location, one per child build. If it looks like it's not doing that then perhaps we don't need to make the change, but it does seem a little coincidental without the explicit check and so potentially fragile.
