### ISSUE TITLE
File path separator for Cygwin is wrong

### ISSUE THREAD

**Issue by WizardOfOz** [gradle/gradle#12497]
File.separator should return '/' (forward slash) in Cygwin on Windows, not '\\' (backslash).

The operating system is correctly detected as Windows, but since Cygwin is a Linux-like environment, the path separators should be forward slashes.

Otherwise you get errors like this:

> The system cannot find the path specified.
> "/cygdrive/c/Users/some_user_account/jdk-11.0.2\bin\java"

(Notice the two last separators being backslashes.)

I noticed this while using [Open Liberty](https://openliberty.io/) framework, trying to run "gradle libertyRun" command, but assumed that the problem would be in Gradle, since:

`println(File.separator)`

.. returns '\\'.

### My Environment

Gradle version: 6.2.2
Cygwin version: 3.0.7(0.338/5/3)
Operating system: Windows 10 Enterprise (10.0.17763 Build 17763)

$ java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by big-guy** [comment]
Cygwin is Linux-like, but the file separator is still `\` on Windows.  Cygwin is doing a translation between the two.  The file separator is something the JVM determines, not Gradle.

It looks like you might be trying to use a Cygwin-only path.  You need to use the Windows path (even under Cygwin).
