### ISSUE TITLE
Print native-platform version with `--version`

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12499]
When running `gradle --version` we should print the version of `native-platform` used. Something like:

```text
$ ./gradlew --version

------------------------------------------------------------
Gradle 6.3-20200304230105+0000
------------------------------------------------------------

Build time:   2020-03-04 23:01:05 UTC
Revision:     87540e2f3a81b4182b959596f8600e81e440e134

Kotlin:       1.3.61
Groovy:       2.5.8
Native:       0.22-milestone-1
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.4 (AdoptOpenJDK 11.0.4+11)
OS:           Linux 4.15.0-88-generic amd64
```
---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
I wonder how the version of native platform is different from the version of, say Guava. IOW, why should be print the version of native platform and not the version of the other (internal) third party dependencies.

**Comment by lptr** [comment]
Maybe just for the time being, to help diagnose VFS problems. It is always possible to track back to the `native-platform` version from the Gradle version, but... yeah, maybe it's overdoing it. We could print it in the incubating message maybe.
