### ISSUE TITLE
Use the Java API compiler when possible

### ISSUE THREAD

**Issue by melix** [gradle/gradle#12513]
## Context

Gradle will use our `JdkApiCompiler`, which uses the compiler API from the JDK, by default. However, as soon as one sets `javaHome` or `executable` in the fork options, we fallback to the CLI compiler, even if the target compiler _does_ support the compiler API.

This is currently a problem when trying to improve the incremental compiler. We should restrict the CLI compiler to "fallback" mode for things we don't support directly (for example, very old compilers).

This should be considered as part of the "better toolchain support" work.

**Comment by wolfs** [comment]
I think it would be OK to not support incremental compilation for CLI compilers.

**Comment by bmuskalla** [comment]
@ljacomet I pushed the most recent incarnation of this to [this branch](https://github.com/gradle/gradle/tree/bmuskalla/toolchainsUseCompileDaemon) before heading out. I'm still not sure if this isn't too risky for 6.7 given I keep seeing random places using `Jvm.current`. Maybe you can have another look at it until I'm back and see if we can reduce the risk.

Also added another test for cross-compiling with Java 1.7 that doesn't work yet so this is a scenario that we may want to fix as well.

**Comment by ljacomet** [comment]
This has been done for the new toolchain support.
Attempting something similar for the other use cases is risky given the number of possible corner cases.
It is not planned to improve the situation when a user manually configures a Java home or an executable.
Toolchain support should be preferred in that case.
