### ISSUE TITLE
Nullpointer exception on compile with proguard with gradle 3.6.1

### ISSUE THREAD

**Issue by kujaomega** [gradle/gradle#12516]
I'm writing this issue here because I was not allowed to write an issue on "https://source.android.com/source/report-bugs" with the gradle category.

Using the following library versions:
com.android.tools.build:gradle:3.6.1
kotlin: 1.3.70
org.robolectric:robolectric:4.3.1

I migrated gradle from 3.5.3 to 3.6.1 and started getting nullpointer exceptions when I was getting an object with a SerializedName annotation.

**Comment by bmuskalla** [comment]
@kujaomega Would you be able to share a project to reproduce this issue and please post the stacktrace you're seeing.

**Comment by bmuskalla** [comment]
Without more information, there is not much we can do. Closing for now. Please feel free to reopen if you can provide more information.
