### ISSUE TITLE
Can't upgrade to Gradle 6.3-rc-1 from 6.1 (new project)

### ISSUE THREAD

**Issue by redlet** [gradle/gradle#12525]
### Expected Behavior

`./gradlew wrapper --gradle-version=6.3-rc-1`
A fresh Gradle project should be able to upgrade from 6.1 to 6.3-rc-1 on JDK 14.

### Current Behavior

`Could not initialize class org.codehaus.groovy.runtime.InvokerHelper`

### Context

I was able to upgrade a single project from a version of 6.3 that did not support JDK 14 to one that does... for some reason, all other projects cannot be upgraded (even brand spanking new ones).

### Steps to Reproduce 

Just create a new Gradle project in IntelliJ IDEA EAP (March 12 update).

```
------------------------------------------------------------
Gradle 6.1
------------------------------------------------------------

Build time:   2020-01-15 23:56:46 UTC
Revision:     539d277fdba571ebcc9617a34329c83d7d2b259e

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14 (Oracle Corporation 14+36-1461)
OS:           Linux 5.5.9-arch1-2 amd64
```

**Comment by bmuskalla** [comment]
@redlet Can you please share the whole stacktrace? 
Also, when you upgrade using `./gradlew wrapper --gradle-version=6.3-rc-1` you're still running an older Gradle version that is not compatible with Java 14 but as it looks using a Java 14 JVM. I think you need to use a supported version to do the upgrade. Or provide some more steps to reproduce this issue.

**Comment by redlet** [comment]
@bmuskalla You were right; my IDE was using JDK 14. I thought IntelliJ IDEA was packaged with its own JDK. `sudo archlinux-java set java-13-openjdk` then relaunching IDEA fixed the issue. (Prior to this, I actually copy/pasted the gradle wrapper from another project lol.)
