### ISSUE TITLE
Public API to post test events from custom tasks

### ISSUE THREAD

**Issue by Romanow88** [gradle/gradle#12523]
### Expected Behavior
With Gradle 6.1+ a new test API was added so that IDEs and CIs are notified when gradle a test event happens. If tooling switches to these, we as developers would need a way to produce these test events for custom written tasks.

### Current Behavior
Only core gradle tasks produce test events.

### Context
Currently, we use TeamCity and Gradle. We also trigger non-java tests, notably karma for web tests in a custom Node task. To make this work with TeamCity we use the a specific log pattern to notify TC about test lifecycle.

Also, running karma test task in IDEA does not produce test events. This is not a gradle problem, per say, but if https://youtrack.jetbrains.com/issue/IDEA-232317 would get implemented, that would mean that suddenly we would have the ability to notify gradle about tests correctly, which in turn would propagate to other tooling.

**Comment by aSemy** [comment]
Hi, does [BuildEventsListenerRegistry](https://docs.gradle.org/current/javadoc/org/gradle/build/event/BuildEventsListenerRegistry.html) sound like what you want?

Example here: https://github.com/gradle/gradle/issues/20151#issuecomment-1208299165

https://docs.gradle.org/current/userguide/build_services.html#operation_listener

**Comment by Romanow88** [comment]
Hi, no, this does not really what is needed. Here is a scenario:

I execute a gradle test task in IDEA and see the executed tests in the IDEA UI as a tree (in addition to seeing the task execute in the console). This works because the Java test task has access to some APIs to which it can post test events, and these events then are picked up by IDEA.

I would like to have access to such an API so that I could, for example, achieve the same IDEA UI for a custom gradle task that is running tests via Jest. The idea is that I can, with a special Jest plugin, produce some output that would be parsed by my Gradle task and translated to the Gradle API that would then pass that over the the IDE.

**Comment by aSemy** [comment]
What data do you want to send from the Gradle task to the IDE? I've not used it, but the BuildEventsListenerRegistry can at least send whether a test passed/failed/skipped.

The current way that IntelliJ listens to Java task events and sends XML updates to the IDE requires breaking Gradle's [incremental build](https://docs.gradle.org/7.5.1/userguide/more_about_tasks.html#sec:up_to_date_checks), which is really painful (https://youtrack.jetbrains.com/issue/IDEA-240111).

**Comment by Romanow88** [comment]
BuildEventsListenerRegistry needs to get the information about what tests were executed from somewhere. There is currently, as far a I know, no way for a custom task (e.g. a custom task that executes something like `yarn run jest`) to provide the data about tests that were executed to the underlying Gradle infra, so the BuildEventsListenerRegistry will not get these events, which is the problem.

**Comment by aSemy** [comment]
Okay, clear! Thanks for explaining. So to summarise: there's [TestListener](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestListener.html) (though it's [slated for removal in 8.0](https://docs.gradle.org/current/userguide/upgrading_version_7.html#task_execution_events)) for listening to test results, but you need to publish events, and there's no docs or public API for that.

Have you tried using the internal Gradle API to create a publisher? I've not tried, but it seems that's how test events are published in AbstractTestTask.

https://github.com/gradle/gradle/blob/2b14de7de061f508d3db11a223400f5b7b2c4cc0/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java#L115-L119

A more hacky workaround is to manually create the IntelliJ 'test report' XML, the format is in [IJTestLogger.groovy](https://github.com/JetBrains/intellij-community/blob/bad1488cd1307fce451529ed33ffb3c278a9f71a/plugins/gradle/resources/org/jetbrains/plugins/gradle/IJTestLogger.groovy), and log each message to stdout.

**Comment by Romanow88** [comment]
I fiddled around with trying to extend the AbstractTestTask, but did not get it working, as it's a tightly coupled to the JVM impl. 

Let me spend some time trying to wire something up with the `ListenerManager`
