### ISSUE TITLE
Constraints can sometimes impact excludes

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#12536]
When sourcing constraints from a published platform, with Gradle Module Metadata, there is a bug that causes them to be considered as a real path to the dependency for the exclude computation.

This has two effects:
* Since constraints cannot have declared excludes, all dependencies of the target module will be in the graph.
* The only way to exclude dependencies of a module that has a constraint coming from a published platform is to use configuration level exclude.

Note that platform projects and Maven BOM are not impacted.

**Comment by jjohannes** [comment]
Fixed by #12537
