### ISSUE TITLE
Gradle build goes into endless loop ~50% of the time: Waiting to acquire shared lock on daemon addresses registry.

### ISSUE THREAD

**Issue by szubersk** [gradle/gradle#12539]
I use gradle to invoke GNU make underneath (as convenience wrapper). One of the 200+ CI jobs fails somehow consistently, while others are completely unaffected by this problem, not even once (Gradle 6.1.1, openjdk-1.8.0.242). Today I rerun the job ~40 times, ~20 time it was failing.

Could you please point out to possible root causes? Feels like 

Unsuccessful run:
> 2020-03-16T20:44:54.615+0000 [QUIET] [system.out] make: Leaving directory `/home/jenkins/workspace/CE/OPENMGW/components/develop/SS_MGWTDMPhlMgr/ci_build_ut/SS_MGWTDMPhlMgr/build' // this is where GNU make ends its job
**> 2020-03-16T20:44:58.457+0000 [LIFECYCLE] [org.gradle.cache.internal.DefaultFileLockManager]** 
> 2020-03-16T20:44:58.457+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 2020-03-16T20:44:58.457+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
> 2020-03-16T20:44:58.457+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> 2020-03-16T20:44:58.457+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 2020-03-16T20:44:58.457+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
> 2020-03-16T20:44:58.457+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> ... and so on...

For comparison, successful run:

> 2020-03-16T20:43:00.117+0000 [QUIET] [system.out] make: Leaving directory `/home/jenkins/workspace/CE/OPENMGW/components/develop/SS_MGWTDMPhlMgr/ci_build_ut/SS_MGWTDMPhlMgr/build' // this is where GNU make ends its job
> 2020-03-16T20:43:00.120+0000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
> 2020-03-16T20:43:00.120+0000 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'bash'' finished with exit value 0 (state: SUCCEEDED)
> 2020-03-16T20:43:00.120+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute exec for :ut'
> 2020-03-16T20:43:00.120+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute exec for :ut' completed
> 2020-03-16T20:43:00.121+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot outputs after executing task ':ut'' started
> 2020-03-16T20:43:00.121+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Snapshot outputs after executing task ':ut''
> 2020-03-16T20:43:00.121+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Snapshot outputs after executing task ':ut'' completed
> 2020-03-16T20:43:00.121+0000 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for task ':ut' from context.
> 2020-03-16T20:43:00.121+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :ut'
> 2020-03-16T20:43:00.121+0000 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :ut' completed
> ...

**Comment by big-guy** [comment]
Messages like these:

> Waiting to acquire shared lock on daemon addresses registry.

are 100% normal and what you'd see with a Gradle daemon running. 

This looks a bit like the underlying command didn't complete and that's why there isn't any logging from `org.gradle.process.internal.DefaultExecHandle`.  When a build is hung, could you check if any child processes are running?

**Comment by szubersk** [comment]
@big-guy Thanks for replying to this issue. Indeed there is a hung process that becomes a process group leader but belongs to Gradle daemon session.

PID  PPID  PGID   SID COMMAND
**14164**     1 14164 14164 /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/bin/java -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=US-ASCII -Duser.country=US -Duser.language=en -Duser.variant -cp /opt/gradle-6.3/lib/gradle-launcher-6.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.3
22577 14130 14130   213 /usr/lib/jvm/jre-1.8.0-openjdk/bin/java -Xmx64m -Xms64m -Dorg.gradle.appname=gradle -classpath /opt/gradle-6.3/lib/gradle-launcher-6.3.jar org.gradle.launcher.GradleMain -Parch=x86_64_acpi5 ut
24158     1 24158 **14164** HUNG_PROCESS

In the light of the above I will close this issue and again, big thanks for helping!
