### ISSUE TITLE
https://services.gradle.org/fixed-issues/3.0 does not list all issues

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1255]
### Expected Behavior
https://services.gradle.org/fixed-issues/3.0 and thus the release notes should include the issues fixed in all RC and M releases.

### Current Behavior
It only includes the RC issues, but not the M issues.

### Expected List of Issues
https://issues.gradle.org/browse/GRADLE-1910?jql=fixVersion%20in%20(3.0%2C%203.0-rc-1%2C%203.0-rc-2%2C%203.0-milestone-1%2C%203.0-milestone-2)%20ORDER%20BY%20id

**Comment by eriwen** [comment]
@Vampire I've updated the JIRA fix versions so that https://services.gradle.org/fixed-issues/3.0 now should show the full list. Closing as complete.

**Comment by Vampire** [comment]
Actually `3.0` is still missing, which makes the list one less, than the search link I provided. Actually I have seen small discrepancies in former release notes already too, but didn't think about it too much. Here it was a huge difference, so I investigated. Here what else I observed since 2.0 release notes:

- `2.1` missing for `2.1` and hence 1 issue
- `2.4` missing from `2.4` and hence 2 issues
- `2.5` missing from `2.5` and hence 1 issue
- `2.6` missing from `2.6` and hence 1 issue
- `2.10` missing from `2.10` and hence 1 issue
- `2.12` missing from `2.12` and hence 2 issues
- `2.14` missing from `2.14` and hence 2 issues
- `2.14.1` missing from `2.14.1` and hence 1 issues
- `3.0` missing from `3.0` and hence 1 issues
- the 2 JIRA issues are missing from `3.3`, but I guess this is a transition issue

**Comment by eriwen** [comment]
Thanks for the thorough notes. I've gone ahead and corrected the missing issues before v3.3.

**Comment by Vampire** [comment]
@eriwen one more question. Is affects-version:3.3 really the right tag for identifying known issues?

**Comment by eriwen** [comment]
@Vampire That's the intent, why do you ask?

**Comment by Vampire** [comment]
@eriwen well, if that's the intent, it is ok, I just wanted to make sure. In JIRA "affects version" and "known bug of" were separate. Everything you find in 3.3 is reported with affects version 3.3, but only things that were introduced by the changes in 3.3 (regressions) were marked as known bug of 3.3. Before you had a list of 0-5 known bugs for a release, now you have 30 known bugs for 3.3. I just wondered whether this was intended or by accident.

Does that also mean, that if you release 3.4, you will mark all issues that are marked with affects-verion:3.3 and that are not fixed in 3.3 with affects-version:3.4, so that they appear as kown bugs in 3.4 release notes also?

**Comment by Vampire** [comment]
#1245 for example would be a known bug fo 2.14 and 3.3, but not for 2.14.1, 3.0, 3.1, 3.2 or 3.2.1. Was it fixed in 2.14.1 and reintroduced in 3.3? With the old semantics it just means someone has seen this error in 3.3 and someone had seen it in 2.14, on all other version it is just not known for sure.

**Comment by Vampire** [comment]
And what about for example #929? It was shown as known bug in the release notes, but it is not shown anymore now. And if I search for `affects-version:3.3` bugs, there are 34 while the release notes only show 30 known bugs.

**Comment by Vampire** [comment]
Btw. even if the definition of a known issues has changed, then at least the release notes have to be updated, as they still say `Known issues are problems that were discovered post release that are `**`directly related to changes made in this release.`**

**Comment by lacasseio** [comment]
Thanks @Vampire for finding this issue. It's actually related to the maximum item per page in GitHub API. A fix is on its way and you should see the right amount of known issues.

You are right that our `affects-version` is lacking a bit in consistency. It is safe to assume that any version from the lowest `affects-version` label to the milestone it was closed are affected by the issue. The `affects-version` are usually added when we have hard fact the version is affected by the issue. In the perfect world, we would be testing all release and add the appropriate labels.

**Comment by Vampire** [comment]
@lacasseio So, will the list be updated to show the issues even if they don't have the appropriate `affects-version` set but should be affected, or will only the ones that are actually labeled be shown still? Just for my understanding.

**Comment by lacasseio** [comment]
Good point @Vampire, the list only shows what was tagged in GitHub with label `affects-version`.

**Comment by Vampire** [comment]
@lacasseio I know that it is like that currently. The question was, whether you plan to change this or not. :-)

**Comment by lacasseio** [comment]
My bad. At the moment, this isn't on our list of things to improve. It will stay like this for a little while.
