### ISSUE TITLE
Improve error reporting when serializing @Input

### ISSUE THREAD

**Issue by britter** [gradle/gradle#12552]
### Expected Behavior

If Gradle fails to serialize a field marked with `@Input` it should suggest to annotate the field with `@Nested`.

### Current Behavior

A failure indicating the field should be made `Serializable`

**Comment by lptr** [comment]
@britter can you please provide a reproducer, and the error message? If so, please reopen this issue.

**Comment by britter** [comment]
@lptr please see https://gradle.slack.com/archives/C03A0MT6S/p1584449681191800
