### ISSUE TITLE
Overload resolution ambiguity when applying an extension configuration from buildsrc

### ISSUE THREAD

**Issue by jdiazcano** [gradle/gradle#12564]
### Expected Behavior
I should be able to configure extensions from outside the base `build.gradle.kts` file and apply from the file.

### Current Behavior
I'm getting an exception `Overload resolution ambiguity ` when trying to apply from a file.

```
e: buildSrc\gradle\experimental.gradle.kts:1:12: Overload resolution ambiguity: 
public abstract fun <T : Any!> configure(p0: Class<TypeVariable(T)!>!, p1: Action<in TypeVariable(T)!>!): Unit defined in org.gradle.api.plugins.ExtensionContainer
@Incubating public abstract fun <T : Any!> configure(p0: String!, p1: Action<in TypeVariable(T)!>!): Unit defined in org.gradle.api.plugins.ExtensionContainer
public abstract fun <T : Any!> configure(p0: TypeOf<TypeVariable(T)!>!, p1: Action<in TypeVariable(T)!>!): Unit defined in org.gradle.api.plugins.ExtensionContainer
```

### Context
I have defined a buildSrc project that is a git submodule for every project that I create. This is useful to not repeat code everytime. It can be seen [here](https://github.com/jdiazcano/buildSrc/blob/master/gradle/experimental.gradle.kts)

### Steps to Reproduce 
Apply the file [experimental.gradle.kts](https://github.com/jdiazcano/buildSrc/blob/master/gradle/experimental.gradle.kts) to any gradle project.

### Your Environment
Build scan URL: https://scans.gradle.com/s/hdakx6utxsaem

**Comment by jdiazcano** [comment]
As workaround, if I copy the exact code from the file and put it directly to the `build.gradle.kts`, it compiles just fine.

**Comment by eskatos** [comment]
Thanks for the report @jdiazcano 

The root problem is:
```
Line 1: extensions.configure(org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension::class.java) {
                                 ^ Unresolved reference: jetbrains
```
https://scans.gradle.com/s/hdakx6utxsaem/console-log#L44-L45

The script you apply doesn't have the Kotlin Gradle Plugin in its classpath. That's not a bug but a known limitation.

If you want to keep using an applied script plugin you need to add the Kotlin Gradle Plugin to its classpath using the `buildscript {}` block.

Moreover the `sourceSets` accessor isn't available, see https://scans.gradle.com/s/hdakx6utxsaem/console-log#L47-L48
You would need to use `configure<SourceSetContainer> {}` instead. See https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin_using_standard_api

Given you use `buildSrc` to share build logic you can also consider using a _precompiled script plugin_ instead (a `.gradle.kts` script in your `buildSrc` kotlin source set). Those scripts get the shared `buildSrc` classpath plus type safe accessors. See https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:precompiled_plugins

HTH
