### ISSUE TITLE
Retrying for too long while sending build scan

### ISSUE THREAD

**Issue by mwos-sl** [gradle/gradle#12563]
We have some developers for which sending build scan is hanging for too long.
In our case, sending build scan should have very short timeout (~20 sec) and no retries. After that, sending build scan should be just skipped.

### Expected Behavior
Do not retry sending build scan, and shorter timeouts. Ideally - allow to configure both (number of retries and timeout in second).

### Current Behavior
3 retries and very long timeout.

### Context
Because of that gradle command hands for too long.

```
Publishing build scan...
Publishing build scan failed due to network error 'java.io.IOException: Error writing request body to server' (2 retries remaining)...
```

```
Publishing build scan failed due to network error 'java.io.IOException: Error writing request body to server' (1 retry remaining)...
A network error occurred.
The hostname '________________________' could not be resolved.
Please check that you have specified the correct server address.
You may also receive this error if you are offline from the network.
If you require assistance with this problem, please report it to your Gradle Enterprise administrator and include the following information via copy/paste.
----------
Gradle version: 5.6.4
Plugin version: 3.1
Request URL: _____________________________________
Request ID: _________________________________
Exception: java.net.UnknownHostException: ___________________________
----------
```

### Steps to Reproduce 
Introduce domain resolving problem.

**Comment by mwos-sl** [comment]
One more example:
```
BUILD SUCCESSFUL in 26s
329 actionable tasks: 329 up-to-date
Publishing build scan...
<=============> 100% EXECUTING [1m 48s]
> IDLE
> IDLE
> IDLE
> IDLE
```

So sending took here >1 min and still hanging. I saw cases 5min+.

**Comment by ldaley** [comment]
Hi @mwos-sl 

This one got lost in the stream when it came in. Since version 3.3 (May 2020), the upload now happens in the background and the initial request has a short timeout of 3s-connect/5s-read.
