### ISSUE TITLE
Idle daemon timeout strategy prints debug message even when not expiring

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#1257]
`DaemonIdleTimeoutStrategy` prints a debug message every time it triggers saying that the daemon is expiring.  However it is used not only by itself for "normal" daemon idle expiration but also in composite expiration conditions like the duplicate idle daemon strategy and the low OS memory strategy.  So we are seeing this message in daemon logs even when the daemon is not actually expiring (i.e. even when these composite conditions do not trigger). 

We should just remove this message altogether since we get a logging message with this information when an actual expiration is triggered.

**Comment by ghale** [comment]
@eriwen I went ahead and pushed this with https://github.com/gradle/gradle/commit/73bfb651d8844650a7101f755244614f1fba12d1.  I hadn't refreshed the page so I didn't see that you had picked this up already.

**Comment by eriwen** [comment]
No problem, just glad it's done :) I'll close this as complete.
