### ISSUE TITLE
about  idea generate gradle.xml

### ISSUE THREAD

**Issue by 929404097** [gradle/gradle#12587]
I created the springboot project of gradle through idea2019, and idea will generate gradle.xml file for me under idea directory. Since the value of externalProjectPath parameter configuration is the absolute path of the project, gradle cannot be used later, so I need to change this absolute path to $PROJECT_DIR$, so gradle can be used. Is this the problem of gradle? Or is idea incompatible?

**Comment by big-guy** [comment]
I'm not 100% sure what you're referring to, but we don't generate a `gradle.xml` file, so I think this is something with IntelliJ IDEA.  HTH
