### ISSUE TITLE
PMD Plugin should allow to specify source file encoding

### ISSUE THREAD

**Issue by matthiaskraaz** [gradle/gradle#12590]
### Expected Behavior

The PMD Plugin should allow to set the encoding like this:

```
pmd {
  encoding = 'UTF-8'
}
```

Maybe you could even use compileJava.options.encoding as a default.

The setting should be passed to the PMD ant task:

```
ant {
  taskdef(name: 'pmd', ...
  pmd(encoding: ...
}
```

### Current Behavior

Encoding cannot be specified. At least on my system, the default does not match my source file encoding. I can't figure out what the default is. My source files are encoded in UTF-8.

### Context

Some of my source files have Unicode characters like the euro symbol within string literals.
They cause: 

`net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file C:\osis_src.trunk\jsource\src\jls\odv\ViewpanelController.java at line 439, column 16.  Encountered: "\u201a" (8218), after : "\'\u00e2"
`

If I invoke PMD directly and specify the encoding, the error dissappears.

**Comment by big-guy** [comment]
PMD runs in the Gradle process, so it needs to share the same file encoding as the Gradle daemon. The easiest way to fix this would be to set the encoding for the Gradle process, we do this in our gradle.properties (see `-Dfile.encoding=UTF-8`):

https://github.com/gradle/gradle/blob/master/gradle.properties#L1

By default on Windows, the file encoding is Windows-1252 for the JVM.

**Comment by adammurdoch** [comment]
I'm not sure we should close this, or at least we should raise a related issue instead. You _should_ be able to specify the encoding that your source files use, ideally at the source set level, and have integrations honour this. For example, the the right encoding option should be passed to the Java compiler, and the PMD plugin/task can do things like run the analysis in another JVM when daemon encoding != source file encoding, or pass the right option to PMD, or at least fail with a nice error message when it cannot honour the source file encoding.

**Comment by matthiaskraaz** [comment]
I tried  `org.gradle.jvmargs=-Dfile.encoding=UTF-8 ` as in your `gradle.properties` without effect.

What DID work however was any of:

- environment variable `GRADLE_OPTS=-Dfile.encoding=UTF-8`
- environment variable `JAVA_OPTS=-Dfile.encoding=UTF-8`
- in gradle.properties: `systemProp.file.encoding=UTF-8`

For me, it is solved. 

However, this does not feel right:

- for Java compilation, you have the source file encoding on a task level
- for PMD, you have the source file encoding on a global level
