### ISSUE TITLE
Slow Scala compilation times in 6.2.2 compared to 5.6.2

### ISSUE THREAD

**Issue by SheliakLyr** [gradle/gradle#12591]
### Expected Behavior
I expected build times to stay the same or drop after upgrade to the newer version of Gradle. Small performance drop is also acceptable.

### Current Behavior
For multimodule builds with Scala code build times increased dramatically (2 times the usual time). I've traced the problem to the tasks that compile Scala. I think this might be related to the Zinc upgrade.

### Context
Fast compilation: Gradle 5.6.2
Slow compilation: Gradle 6.2.2, 6.3-rc4

I have two projects build with gradle (small one ~ 10 modules, large one ~ 100 modules). The problem occurs for both of them.

For small project:
```
Gradle 5.6.2:

gw clean compileScala --no-build-cache --profile

Two instances of GradleWorkerMain:
 - Non heap memory at the end: 180MB, 202MB
 - Loaded classes: 11274, 11047

Total time:
BUILD SUCCESSFUL in 2m 28s
61 actionable tasks: 60 executed, 1 up-to-date

Gradle 6.2.2:

gw clean compileScala --no-build-cache --profile

Two instances of GradleWorkerMain:
 - Non heap memory at the end: 714MB, 716MB
 - Loaded classes: 44244, 43294

Total time:
BUILD SUCCESSFUL in 4m 29s
61 actionable tasks: 60 executed, 1 up-to-date
```

I've profiled Gradle workers and have noticed a large increase in loaded classes and non-heap space usage. In 6.2.2 a lot of classes are loaded multiple times, for example:
 - scala.tools.nsc.Global (5 instances in different classloaders)

I've tried to build a single module and the times are the same in 5.6.2 and 6.2.2. Only multimodule builds are noticable slower.

Note: I'm not using the incremental Scala compilation:
```
        scalaCompileOptions.with {
            force = true
        }
```

### Steps to Reproduce 
I think this can be reproduced by any multimodule build with scala code. 
Here is an example:
https://github.com/SheliakLyr/gradle-scala-slow-compilation-example

I tried to build it with 5.6.2 and 6.2.2: `./gradlew clean build --scan`.
The build scan for 5.6.2: https://scans.gradle.com/s/dy5hsgpq3dotw
The build scan for 6.2.2: https://scans.gradle.com/s/ujdltbw6csltc

Task execution time for 5.6.2: 28s
Task execution time for 6.2.2: 6m+

### Your Environment
https://scans.gradle.com/s/ujdltbw6csltc
I will be happy to answer any questions that might help you solve this issue.

**Comment by big-guy** [comment]
Is this consistent for every build or is it just the first build with the newer version of Gradle?

**Comment by SheliakLyr** [comment]
Consistent. I've just added an example project and build scans for 5.6.4 and 6.2.2.

**Comment by SheliakLyr** [comment]
Just a guess: can this be caused by the removed compiler caches in ZincScalaCompilerFactory? I am almost sure that the problem is caused by the recreation of the compiler for each compiler task, and it seems that those caches were supposed to avoid the cost of that operation. Compare getScalaInstance methods for example.

**Comment by SheliakLyr** [comment]
@big-guy I have some additional info.

First of all, the problem happens also for version 6.0.

Secondly, I performed the following experiment:

1. I took the current master and tested it. Compilation is slow, 6m 18s: https://gradle.com/s/ba3pge2sdxl2u
2. I reverted a part of your commit 55cc6461feed063b4ebdb8a709e87bfca1c794e3. Compilation is fast!! again 26s: https://gradle.com/s/5yxhz5i7ndjzq.

The changes tested by me can be seen here: https://github.com/SheliakLyr/gradle/commit/0a7baeb57794a79864daf2d59298bfdfc9afbad8

I think this confirms that this is a cause. I can open a pull request, but I wonder: were those caches causing any issues and were removed because of that?

**Comment by lure** [comment]
Hi everyone. 
Just wanted to ask if aforementioned pull requests are going to be merged? 
Thank you. 
P.S.: our `./gradlew test` time jumps about 35% simply by replacing 5.6.2 with any of 6 :)

**Comment by mdbergmann** [comment]
We see a massive increase of both compile time (25 minutes (Gradle 6.4) instead of 5 minutes (Gradle 4.10).
Also a massive increase of memory consumption. Often it bails out with out-of-mermory with 1Gig setting.

**Comment by mdbergmann** [comment]
We had to increase Gradle heap to 2gig and the Scala compiler to 4gig !!!.
```
    tasks.withType(ScalaCompile) {
        scalaCompileOptions.forkOptions.with {
            memoryMaximumSize = '4g'
        }
    }
```
Otherwise it would bail out with error 137, out-of-memory.

**Comment by SheliakLyr** [comment]
@mdbergmann I had the same problem, apart from the slow compilation times. That's what led me to analyzing the heap usage, and in turn, classloader cache.

**Comment by mdbergmann** [comment]
> @mdbergmann I had the same problem, apart from the slow compilation times. That's what led me to analyzing the heap usage, and in turn, classloader cache.

Thanks for doing that.

**Comment by ljacomet** [comment]
Just to confirm that the Gradle team is aware of the issue and thanks to @SheliakLyr who worked on a PR, we are aiming to have the fix in Gradle as soon as possible.

**Comment by ljacomet** [comment]
The PR has been merged and will be part of Gradle 6.5.

If you are a Gradle Scala user, please make sure to take 6.5 RC1 for a spin. To be released early next week!

**Comment by dsilvasc** [comment]
Should this issue be listed in https://docs.gradle.org/6.5-rc-1/release-notes.html ?

**Comment by ljacomet** [comment]
My mistake, I forgot to update the milestone when merging to 6.5 release branch.
I have updated it now, it will definitely show up in the 6.5 release notes.

@dsilvasc Thanks for the reminder.
