### ISSUE TITLE
"Could not initialize class org.codehaus.groovy.runtime.InvokerHelper" on JDK 14

### ISSUE THREAD

**Issue by christianhujer** [gradle/gradle#12599]
### Expected Behavior
Gradle works on JDK 14

### Current Behavior
Gradle does not work on JDK 14

### Context
I tried to upgrade a Gradle project to JDK 14.

### Steps to Reproduce
Create a simple Gradle project by creating the following `build.gradle` file:
```
plugins {
    id 'java'
}

group 'some.group'
version '0.0.1-SNAPSHOT'

sourceCompatibility = 14

repositories {
    mavenCentral()
}
```

Run it using `gradle --scan` or something like that.

### Your Environment

Build scan URL: not available, as `gradle --scan` fails.
The following file `stderr.txt` was produced by, using the following `build.gradle.txt` as `build.gradle`:
```
./gradlew --stacktrace --info --debug >stderr.txt 2>&1
```
[build.gradle.txt](https://github.com/gradle/gradle/files/4365008/build.gradle.txt)
[stderr.txt](https://github.com/gradle/gradle/files/4365007/stderr.txt)

**Comment by christianhujer** [comment]
Closing this issue. I've just tried Gradle 6.3-rc-4 and it works just fine with JDK 14.

**Comment by alexmccabe** [comment]
Downgrading to JDK11 also resolves the issue

**Comment by arecastudio** [comment]
Thank you, downgrade to version 11 really solve my problem

**Comment by Qasim-Yousaf** [comment]
> Closing this issue. I've just tried Gradle 6.3-rc-4 and it works just fine with JDK 14.

Thanks it work

**Comment by QuditWolf** [comment]
Same issue with gradle 7.0 , on jdk 15.0.2...
 ./gradlew build --debug gives 
[debug.txt](https://github.com/gradle/gradle/files/6414986/debug.txt)

**Comment by markw101** [comment]
I took advice of christianhujer and downloaded gradle 6.3 and java jdk 14. Downloaded them from here: https://jdk.java.net/archive/ and https://gradle.org/releases/ I was then able to run gradle wrapper with no issues. Thanks for your assistance christianhujer. Cheers!

**Comment by nebadi420** [comment]
> Downgrading to JDK11 also resolves the issue

Thank you soooo much!
