### ISSUE TITLE
Getting error message when trying to setup Gradle with a project

### ISSUE THREAD

**Issue by vicmanea** [gradle/gradle#12609]
![77315580-29ea9380-6cde-11ea-9cc2-20c1fcd0aac4](https://user-images.githubusercontent.com/36647329/77342046-fde30880-6d05-11ea-82cf-17134d0c1e19.png)

### Expected Behavior
We expect it to launch, however it throws this error.

### Current Behavior
Presently there is this error shown.

### Context

This issue is preventing the application from running as expected, with the intended features.

### Your Environment

Build scan URL:

**Comment by big-guy** [comment]
This looks like a change made in the Android plugin in AGP 3.5.  Here's a similar report: https://github.com/mannodermaus/android-junit5/issues/167

Running with `--stacktrace` might reveal more information about where that error is coming from, but it's likely that you'll need to downgrade AGP or upgrade some other plugin to that's compatible with AGP 3.5+
