### ISSUE TITLE
ResolvedDependencyResult.getResolvedVariant() can return a null value

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#12643]
While this should not be the case, it seems to happen in specific situations, like a capabilities conflict resolution.

![debugger image](https://user-images.githubusercontent.com/1219911/77584695-8f5ba180-6ee3-11ea-9bff-52e84b899c2d.png)

The result construction should be amended so that this case is no longer possible.

Additional situations to check:
* Replacement rules
* Substitution rules

**Comment by melix** [comment]
@ljacomet did you have a reproducer for this?

**Comment by jjohannes** [comment]
Reproducer:

```

apply plugin: 'java-library'
repositories {
    jcenter()
}
configurations.all {
    resolutionStrategy.capabilitiesResolution.withCapability('com.google.collections:google-collections') {
        selectHighestVersion()
    }
}
dependencies {
    implementation 'com.google.guava:guava:28.1-jre'
    implementation 'com.google.collections:google-collections:1.0'
    components {
        withModule('com.google.guava:guava') {
            allVariants {
                withCapabilities {
                   addCapability('com.google.collections', 'google-collections', id.version)
                }
            }
        }
    }
}
```

The result for the `com.google.collections:google-collections:1.0` node (that is upgraded to `guava:28.1-jre`) won't have a selected variant.
