### ISSUE TITLE
Typo in Windows start script template

### ISSUE THREAD

**Issue by sf17k** [gradle/gradle#1264]
### Expected Behavior

These lines in the [windowsStartScript.txt template](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt) used by the Application plugin should seemingly produce identical lines in the resulting bat file created by `startScripts` task:
```
if "%DIRNAME%" == "" set DIRNAME=.\

set APP_BASE_NAME=%~n0
```

### Current Behavior

Instead, the slash seems to be interpreted as a continuation line, producing this (note missing slash and newline):
```
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
```
The next line in the template is:
```
set APP_HOME=%DIRNAME%${appHomeRelativePath}
```
Which is compiled into this line that now looks like it's missing a slash (strangely, it works anyway):
```
set APP_HOME=%DIRNAME%..
```

### Context

Doesn't seem to change behavior, just looks wrong. Noticed it while looking for a way to set appHomeRelativePath to move the start scripts out of bin/. (Couldn't find one and ended up customizing the templates instead).

**Comment by eriwen** [comment]
@sf17k Thanks for the note. Given that it works, I don't see any reason to address this. That said, you're welcome to provide a PR if you feel strongly about it.

**Comment by tomwhoiscontrary** [comment]
The reason this works is that

```
```
