### ISSUE TITLE
Provide a path forward to remove deprecation warnings for IDE support

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#12656]
Currently Gradle's support for annotation processors does not extend to IDEs like Eclipse and Visual Studio Code. For these to be properly supported we must currently add the following plugin:

```
id "net.ltgt.apt-eclipse" version "0.21"
```

Unfortunately adding this plugin results in deprecation warnings. So we are in a situation where we either live with deprecation warnings or get IDE support. In an ideal world we wouldn't have to make this choice.

### Expected Behavior

Gradle support should be usable in IDEs without deprecation warnings and without needing a third party plugin

### Current Behavior

IDE support requires a third party plugin which introduces deprecation warnings.

### Steps to Reproduce 

Add the following plugin to any gradle build

```groovy
plugins {
    id "net.ltgt.apt-eclipse" version "0.21"
}
```

### Your Environment

Any version of Gradle 6.x

**Comment by big-guy** [comment]
@donat ☝️ do you know what we're missing here for Eclipse?

**Comment by donat** [comment]
Adding annontation processor support is the highest voted Buildship issue: https://github.com/eclipse/buildship/issues/329. We haven't done it simply due to the lack of time. I haven't dug deep into this yet, but it seems that the implementation would be to read the `annotationProcessor` dependencies from Gradle and assign it to the Eclipse project's annotation processor factory path.

**Comment by graemerocher** [comment]
To my understanding `net.ltgt.apt-eclipse` takes the `annotationProcessor` path and generates a `.factorypath` file such as:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<factorypath>
	<factorypathentry kind="EXTJAR" id="..../.gradle/caches/modules-2/files-2.1/io.micronaut/micronaut-inject-java/1.2.7/96e40a2c0412152f1341c82e17c47c4cb5d09968/micronaut-inject-java-1.2.7.jar" enabled="true" runInBatchMode="false"/>
	 .... 
</factorypath>
``` 

It shouldn't be terribly complex to implement

**Comment by graemerocher** [comment]
Any update on this? We are still unable to remove deprecation warnings for end users projects generated by https://micronaut.io/launch/ for Gradle because without `apt-eclipse` IDE support for Eclipse and VSCode is broken

**Comment by graemerocher** [comment]
Closing as we switched to another plugin
