### ISSUE TITLE
Build fails but terminates with exit code 0

### ISSUE THREAD

**Issue by leeyimin** [gradle/gradle#1265]
`gradlew` unexpectedly terminates with exit code 0 instead of 1, when build fails, causing Travis to identify build as passing rather than failing.

### Expected Behavior
`gradlew` is expected to terminate with exit code 1 in event of build failure.

### Current Behavior
In this particular case `gradlew` terminated with exit code 0, when build failed.

### Context
Travis identifies failing build as passing build, due to incorrect exit code from `gradlew`.

### Steps to Reproduce (for bugs)
https://travis-ci.org/TEAMMATES/teammates/builds/194891714
Unable to reproduce again.

### Your Environment
Details can be found in job log: https://travis-ci.org/TEAMMATES/teammates/builds/194891714

**Comment by eriwen** [comment]
This looks like a duplicate of a bug we fixed, but I can't be sure unless I have details about the Gradle version and the build scripts that produced the problem. It's also very difficult without a reproducible example.

@leeyimin Could you please provide these things so we can take a closer look?

**Comment by leeyimin** [comment]
@eriwen The Gradle version is 2.13 and the build script is here at https://github.com/TEAMMATES/teammates/blob/master/build.gradle .

**Comment by bmuschko** [comment]
@leeyimin Could you please try this with latest version of Gradle? Thanks!

**Comment by bmuschko** [comment]
We haven't heard back in the meantime. I am going to close this issue for now. Please let us know if you need further assistance.
