### ISSUE TITLE
In version constraints, the order of `prefer X` vs `strict Y` matters

### ISSUE THREAD

**Issue by svermeulen** [gradle/gradle#12661]
The [documentation](https://docs.gradle.org/current/userguide/rich_versions.html) suggests that using strict versions should be compatible with using preferred versions, but in practice there are issues when used together.  In particular, the order matters.

### Expected Behavior
The order of `prefer` vs `strictly` should not matter when specifying version constraints

### Current Behavior
Currently, `prefer` has to be placed after `strictly`

### Steps to Reproduce 
I created an example project here:
https://github.com/svermeulen/GradleBugExample-StrictVersionOrdering

Then:
* `cd foo`
* `./gradlew dependencies | grep bar`
* Observe that bar version `1.2.0` is chosen
* Move the `prefer` line to be after the `strictly` line in `foo/build.gradle`
* Execute `./gradlew dependencies | grep bar` again
* Observe the bar version is now chosen as `1.0.0`

### Your Environment
macOS

**Comment by ljacomet** [comment]
Had a look at your PR and a chat inside the team. Given the current meaning of `strictly` and `prefer`, there is indeed no reason for clearing the `preferred` version when setting a `strictly`.
