### ISSUE TITLE
Extend tooling models with Integer typed Java version accessors

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#12672]
Some tooling model getters are typed with the `JavaVersion` enum. The enum however, is limited to Java versions Gradle currently support for **running Gradle**. Compiling with a newer version of Java, by setting `forkOptions.javaHome` or `forkOptions.executable` most likely works anyhow and is now better supported in Gradle itself by setting the `release` property (#12648). If the `release` property is set to a version that is not yet supported by the enum, IDEs should still be able to get that version.

Getters that use the enum as return type:

- `IdeaJavaLanguageSettings.getSourceLanguageLevel()`
- `IdeaJavaLanguageSettings.getTargetBytecodeVersion()`
- `EclipseJavaSourceSettings.getSourceLanguageLevel()`
- `EclipseJavaSourceSettings.getTargetBytecodeVersion()`
- `InstalledJdk.getJavaVersion()`
- `JavaRuntime.getJavaVersion()`

**Comment by bmuskalla** [comment]
`JavaVersion` supports enums for future version of Java. Given this, in combination with the fact that we still need to somehow support the JDK we target (e.g. command line flags, detecting its version for toolchains), I doubt an integer is a good representation for the java version. WDYT?
