### ISSUE TITLE
Gradle Logger#trace blackholes logs

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#12678]
### Expected Behavior

Gradle should log `trace` logs at some level or allow them to be enabled somehow.
Alternatively, we should document that `debug` will black hole logs sent to `trace`.

### Current Behavior

Gradle blackholes all SLF4J `trace` level logging.

https://github.com/gradle/gradle/blob/a501ac4f046e9c2b50119fa2f80bfded83b48026/subprojects/logging/src/main/java/org/gradle/internal/logging/slf4j/OutputEventListenerBackedLogger.java#L111-L149

**Comment by bmuskalla** [comment]
Closing stale issue.

**Comment by mlopatkin** [comment]
Closing stale issue (now really closing).
