### ISSUE TITLE
ResolvableDependencies.beforeResolve​ action is not triggered for sub-projects

### ISSUE THREAD

**Issue by assimd** [gradle/gradle#12673]
[ResolvableDependencies.beforeResolve​](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolvableDependencies.html#beforeResolve-org.gradle.api.Action-) does not get triggered for sub-projects when parent project's dependencies are resolved and it has a dependency on child project.

### Expected Behavior
Given a multi-project setup, `beforeResolve` should get executed for each project whenever its dependencies are resolved.

### Current Behavior
Given a multi-project setup, `beforeResolve` _does not_ get executed for child projects when its dependencies are resolved.

### Context
To enable Gradle in our internal build ecosystem, we use these configurations hooks (`beforeResolve`) to download the dependencies from a custom repo into a local maven repo. In case of multi-project setup, say Project `P` depends on Project `C` and Project `C` declares dependencies on module FooBar (`'org.foo:bar:1.0`),  Project `P` should be able to use FooBar as it is a transitive dependency. But since `beforeResolve` hooks in for Project `C` are not being executed, this setup fails.

Same behavior observed when  `DependencyResolutionListener` is used or when `evaluationDependsOnChildren` is set. 

The behavior is same across at least 3 major versions of Gradle (`4.10.3`, `5.6.4` & `6.3`) so this is probably not a bug but something we are doing incorrectly. If that's the case, can you please advice on how we can resolve this on our end.

### Steps to Reproduce 
See the attached project. Execute the command `./gradlew dependencies`, Only the `beforeResolve` from parent project is executed (see the println statements), even though dependency report includes the dependencies from child project. That means dependencies for child project is resolved but its `beforeResolve` is not executed.

### Your Environment
Build scan URL: https://scans.gradle.com/s/zhhc2bwg2yyli
[MultiProjectHooks.tar.gz](https://github.com/gradle/gradle/files/4402226/MultiProjectHooks.tar.gz)

**Comment by ljacomet** [comment]
This is indeed a misunderstanding of the `beforeResolve` feature.
Have a look at the documentation on the [different types of configurations](https://docs.gradle.org/6.3/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs) and the [structure of the configurations](https://docs.gradle.org/6.3/userguide/java_library_plugin.html#sec:java_library_configurations_graph) in a java library.

In a classical setup, you resolve a _resolvable_  configuration. When it references a project, this goes through a _consumable_ configuration of said project.
So there is no resolved configuration in that dependent project and thus no `beforeResolve` invoked.

Given your particular setup, you probably need to make sure all dependencies are pulled first in a local maven repo.
Another option could be to have a fake remote repository that translates the Maven queries into queries for your own setup.

**Comment by assimd** [comment]
Ok, just to be clear that I understand this correctly, if I have a consumable configuration extendsFrom a resolvable configuration (Is it a bad idea?) in a child project, and when parent project is resolved, `beforeResolve` at least on resolvable configuration of child project should get executed? But it does not. So when does `beforeResolve` is executed for dependencies declared in child project?

And since the configuration is not resolved as part of child project, Gradle looks for the dependency in a repository defined in parent project, right?

**Comment by assimd** [comment]
It seems like some dependencies may get resolved without invoking `beforeResolve` for any configuration or for [DependencyResolutionListener](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/DependencyResolutionListener.html). If this is correct, which it seems so, then either it is a bug or documentation needs to be updated to set the correct expectation.

**Comment by ljacomet** [comment]
Ideally a consumable configuration should not extend a resolvable one. It is better to have them both extend a combination of dependency buckets instead. See the [java library plugin documentation](https://docs.gradle.org/6.3/userguide/java_library_plugin.html#sec:java_library_configurations_graph) for an example.

Your understanding of configurations and how they work is also incorrect.

* If a consumable configuration extends a resolvable one, the resolvable one _will not be resolved_ when a resolvable configuration, in a different project, consumes the consumable one.
* A consumable configuration appears in the engine the same way that published metadata does: it is a container of first level dependencies. These dependencies are flattening of all dependencies declared in the configuration hierarchy.
* So in your question: `beforeResolve` is _never_ executed for dependencies in the child project.

If the above does not explain your last comment, please rephrase it as I do not understand what you are stating / asking.

**Comment by assimd** [comment]
> A consumable configuration appears in the engine the same way that published metadata does: it is a container of first level dependencies. These dependencies are flattening of all dependencies declared in the configuration hierarchy.

So from the perspective of parent project, dependencies of child project is viewed as published metadata, this part make sense.

> If a consumable configuration extends a resolvable one, the resolvable one will not be resolved when a resolvable configuration, in a different project, consumes the consumable one.

As per the doc of [Configuration.withDependencies](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Configuration.html#withDependencies-org.gradle.api.Action-), *A Configuration will participate in dependency resolution when: Another Configuration that references this one as a project dependency is resolved*

You are saying it *will not be resolved* but doc say it *will participate in dependency resolution*, how can a configuration participate in dependency resolution but not get resolved? If a consumable configuration is treated as published metadata, then `withDependencies` should not be called either.

**Comment by assimd** [comment]
@ljacomet 

Thank you for the explanation, this clears most doubts we had related to configurations from project dependencies.

If my understanding is correct, configurations from project dependency will not be resolved just because there is a dependency between configurations, but it will be resolved if there is a task dependency between the 2 projects that task triggers the resolution. e.g. In case of Java projects, `java` plugin automatically setup tasks dependency like `:parentProject:compileJava -> :childProject:jar -> :childProject:classes -> :childProject:compileJava`, and `:childProject:compileJava` resolves the resolvable configurations from `childProject`, so configurations from child project does get resolved when there is a project dependency and task has work to do.

However, unlike `java` plugin, Android Gradle Plugin behaves differently, i.e. it tries to fetch dependencies, without resolving the configurations, while it is generating task graph. I am not sure if this is a bug or just the way Android plugin works.

**Comment by ljacomet** [comment]
Closing as the main question has been clarified.
