### ISSUE TITLE
Incremental copying of read only files fails

### ISSUE THREAD

**Issue by staffanf** [gradle/gradle#1267]
If a Copy task contains readonly files to be copied, Gradle does not do incremental builds very well.
If the copy spec is changed without affecting the readonly file, Gradle will still try to copy the file even though the file is up-to-date.

### Expected Behavior
The readonly file should be detected as up-to-date since it has not changed and the build should succeed.
If the readonly file had changed, the gradle should give me some way of handling this except for adding `doFirst { delete readonly-file }`

### Current Behavior
```
:copyReadonlyFile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':copyReadonlyFile'.
> Could not copy file '/tmp/readonly-file-test/readonly-file' to '/tmp/readonly-file-test/build/readonly-file'.
```
### Context
Our releaseFiles which assembles the files for our release zip fails because someone added or modified an unrelated file and tried an incremental build. It fails because a dependency jar is included as readonly. The error message is not that useful for the developer that just modified some java file and wanted to see that the release is still working. 

### Steps to Reproduce (for bugs)
Run the following in a empty dir on a linux machine:
```
#!/bin/bash
gradle wrapper
cat > build.gradle <<- EOM
task copyReadonlyFile (type:Copy) {
  from "readonly-file"
  // from "rw-file"  
  into buildDir
}
EOM
touch readonly-file
touch rw-file
chmod -w readonly-file
./gradlew copyReadonlyFile
# Test changing copy spec to add another file
sed -i 's#//##' build.gradle
./gradlew copyReadonlyFile
# Test external change to readonly file
chmod +w readonly-file
echo "change" > readonly-file
chmod -w readonly-file
./gradlew copyReadonlyFile
```

### Your Environment
Linux

**Comment by staffanf** [comment]
Any comment on this? This is something that's been bothering me ever since we started using Gradle. There are some old Jira issues that solved the problem by working around it  https://issues.gradle.org/browse/GRADLE-3348 .
The other open issue was closed ( https://issues.gradle.org/browse/GRADLE-3269 )
It feel that this is issue is short and concise enough that it should not be to hard to fix if you know where to look.
Also keeping unintuitive behavior for Sync and Copy tasks will probably result in more issues filed in the future with similar issues.

**Comment by eriwen** [comment]
@staffanf I expect that we will batch a bunch of these Copy task issues together and do them all at once sometime. However, right now we're trying to keep focus on things that affect _everybody_: performance, console/logging, software model, etc.

You suggest that it "should not be hard to fix if you know where to look". That indicates that this issue may be better suited to getting community help. Is this something you'd be willing to contribute a fix for?

**Comment by staffanf** [comment]
@eriwen Fair enough, it's just that as an user it's frustrating finding issues that were reported years ago with no fix. 
I would be willing to take a look at it to see if it's a reasonable to fix without massive knowledge about gradle inner workings. I've been searching a bit here on github, but finding the right place to look in gradle is a bit harder than many other open source projects.
Any thought on where to start? After looking around for a while in IntelliJ, org.gradle.api.tasks.CopyPermissionsIntegrationTest or something similar might be place to start to convert the above bash code to tests.
I can't promise any progress but I can take a look at least.

**Comment by eriwen** [comment]
@staffanf I completely sympathize with your frustration as a long-time Gradle user. I would like to see us get better at enabling the community to help us with these issues, because there's no way we can both get through the backlog of issues and provide awesome features that competing build tools are providing. 

I agree that the barrier to entry is high, and that is a problem that is going to take a very long to fix in a fundamental way. I welcome ideas to lower this barrier for you, especially those that scale to many contributors.

You're on the right track to start with a failing test, and `CopyPermissionsIntegrationTest` seems like a good place to start from. In truth, you are starting from the same place as I am on this issue, as that is an area of the code base I'm not familiar with.

**Comment by ljacomet** [comment]
Sorry for the late reply

We have more recent issues around this topic, so keeping this one closed as a duplicate.
