### ISSUE TITLE
debug cacerts usage

### ISSUE THREAD

**Issue by smarek** [gradle/gradle#12682]
This ticket is related to #12518 #9614 #3416

Gradle fails to correctly handle and report issues related to obtaining system configured trusted CA roots, and subsequently fails to validate PKIX path

### Expected Behavior
When gradle fails to securely fetch resources, because of issues with trust path, the report should detail on the environment information, specifically used `cacerts` keystore and number of contained/trusted CA roots

### Current Behavior
```
> gradle check

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'PhoneFoneFun'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.3.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.1.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom'.
            > Could not HEAD 'https://repo.jfrog.org/artifactory/libs-release-bintray/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom?referrer'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.1.3.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

Report just states, there was problem when building PKIX path (and even the message is confusing, was the path not built, or was one of the contained or all of the contained certificates found untrusted/invalid?), no context information

### Context
- I'm using Debian 10 (x64), with stock JRE (openjdk-11-jdk:amd64 and openjdk-11-jre:amd64 version 11.0.6+10-1~deb10u1 from debian repositories)
- I also have JDK/JRE 9.0.4 from SDKMan installed locally in user profile
- System cacerts store is in **/etc/ssl/certs/java/cacerts** and relevant JRE files are symlinks to the system keystore
  - /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts and ~/.sdkman/candidates/java/9.0.4-open/lib/security/cacerts are both symlinks to mentioned system keystore
- keystore password is default in my case
- system java keystore is updated via hook `/etc/ca-certificates/update.d/jks-keystore` after re-configuring system `ca-certificates` to remove/add some of the offered CAs, however this should  

```
> gradle -version

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
OS:           Linux 5.4.0-0.bpo.4-amd64 amd64
```

### Steps to Reproduce 
I'm not sure how to reproduce, because the debugging info / reports, do not contain relevant information, i'm not sure which cacerts keystore was used when error occurs, or which CA roots were trusted/compared to trust-chain provided by HTTPS repositories.
Setting `JAVA_HOME=/usr/lib/jvm/default-java/` did not help, so this issue is probably not caused by searching from JAVA_HOME (I do not have JAVA_HOME env set usually)

### Workaround
I've temporarily solved the issue by configuring gradle to use specific trustStore in ~/.gradle/gradle.properties by adding these two lines
```
systemProp.javax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts
systemProp.javax.net.ssl.trustStorePassword=changeit
```

**Comment by guai** [comment]
I think this error happen when the deamon wasn't start against the same java installation

**Comment by nabond251** [comment]
Saved my bacon. Thanks so much.
