### ISSUE TITLE
OpenJDK 13 caused Error running forked groovyc

### ISSUE THREAD

**Issue by mictadlo** [gradle/gradle#12700]
Hi,
I installed Netbeans 11.3 and OpenJDK-13 under Ubuntu 18.04 and created in the following a new Groovy project.

 1. Choose File > New Project (Ctrl-Shift-N;\u2318-Shift-N on Mac) from the main menu to open the New Project wizard.
 2. Select Java Application in the Java category. Click Next.
 3. Type GroovyJavaDemo as the Project Name and specify the folder where you want to create the application in the Project Location field.
 4. Deselect the Create Main Class checkbox. Click Finish.
 5. Next, I created a Groovy Script file with only this content println "Hello" and it caused the following problems:

```
    ant -f /home/ubuntu/NetBeansProjects/GroovyJavaDemo -Djavac.includes=Hello.groovy -Drun.class=Hello run-single
    init:
    deps-jar:
    Created dir: /home/ubuntu/NetBeansProjects/GroovyJavaDemo/build
    Updating property file: /home/ubuntu/NetBeansProjects/GroovyJavaDemo/build/built-jar.properties
    Created dir: /home/ubuntu/NetBeansProjects/GroovyJavaDemo/build/classes
    Created dir: /home/ubuntu/NetBeansProjects/GroovyJavaDemo/build/empty
    Compiling 1 source file to /home/ubuntu/NetBeansProjects/GroovyJavaDemo/build/classes
    /home/ubuntu/NetBeansProjects/GroovyJavaDemo/nbproject/build-impl.xml:1120: The following error occurred while executing this line:
    /home/ubuntu/NetBeansProjects/GroovyJavaDemo/nbproject/groovy-build.xml:26: Error running forked groovyc.
    BUILD FAILED (total time: 1 second)
```

It turns out it works fine with OpenJDK-8 ( https://stackoverflow.com/questions/60984238/error-running-forked-groovyc-caused-in-netbeans#60984238 ).

Thank you in advance,

Michal

**Comment by big-guy** [comment]
It looks like you're running Ant, not Gradle.  Nothing jumps out at me with what's wrong, but if things work with an older version of the JDK and not a newer one, that might mean the version of Groovy you're trying to use doesn't support the newer version.

**Comment by mictadlo** [comment]
Yes, you right! [Here](https://issues.apache.org/jira/browse/NETBEANS-4124) is the solution.
