### ISSUE TITLE
-Dtest.single doesn't work with buildSrc

### ISSUE THREAD

**Issue by astellingwerf** [gradle/gradle#1271]
When a project has a ```:buildSrc```, ```-Dtest.single``` will typically not work.

### Expected Behavior
I'd like to be able to both put custom build logic in ```buildSrc```, AND run a single test of one of the projects.

### Current Behavior
During the execution of ```:buildSrc:test```, Gradle searches for the test provided in ```-Dtest.single```, and fails when it can't be found.

### Steps to Reproduce (for bugs)
1. ```git clone https://github.com/astellingwerf/test-single-gradle-issue.git```
2. ```cd test-single-gradle-issue```
3. ```./gradlew test -Dtest.single=Test```

### Your Environment
```$ ./gradlew test -Dtest.single=Test
buildSrc has no tests.
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:test'.
> Could not find matching test for pattern: Test

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.775 secs
```

**Comment by Jamlee** [comment]
spring-framework have this bug too.

**Comment by cer** [comment]
I had to add `test.enabled=false` to `buildSrc/build.groovy`

**Comment by melix** [comment]
For the record, neither `-Dtest.single`, `--test` or `-x test` work for `buildSrc`.

**Comment by astellingwerf** [comment]
@melix my problem is not that I can't use those for `buildSrc`. My problem is: When I have `buildSrc`, I can't use `-Dtest.single` for the other projects.

**Comment by caseyduquettesc** [comment]
Using gradle 4.8.1, I have found a few workarounds.

If your original command is this,
```
./gradlew :subproject:test -Dtest.single=ClassNameTest
```

#### Instead of using `-Dtest.single`, you can use the full task name
```
./gradlew :subproject:test -D:subproject:test.single=ClassNameTest
```

#### Instead of using `-Dtest.single`, you can use the `--tests` option
```
./gradlew :subproject:test --tests ClassNameTest
```

#### Use @cer 's suggestion and add `test.enabled=false` to `buildSrc/build.gradle`
```groovy
test.enabled=false
```
#### Or `buildSrc/build.gradle.kts`
```kotlin
tasks {
    "test" {
        enabled = false
    }
}
```
