### ISSUE TITLE
processResources (copy) task cannot change destinationDir

### ISSUE THREAD

**Issue by sniffertine** [gradle/gradle#12716]
### Expected Behavior

Update of destinationDir property during configuration phase should be respected
```
processResources {
    println getDestinationDir()
    setDestinationDir(new File(getDestinationDir(), 'foo'))
    println getDestinationDir()
}
```
The second print should contain `"foo"`

### Current Behavior

The new configuration dir `"foo"` is not used.

I debugged into the build script and saw, that in `DestinationRootCopySpec` the `destinationDir` property is set correctly, but `fileResolver.resolve(destinationDir)` still returns the old value. 
Either this is a problem with lazy evaluation/ wrapper / caching, or the setDestinationDir should not be used. If the latter applies, how should I know this?

### Context

I want my resources to go into a subfolder in the build directory
`src/main/resources/bar.txt` --> `build/resources/main/foo/bar.txt`

### Steps to Reproduce 

Use the configuration above and run `gradle build`

### Your Environment

Build scan URL: https://gradle.com/s/5y5xwjqio7dkg

**Comment by jbartok** [comment]
Sorry for the late reply.
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by ov7a** [comment]
Actually, it's a duplicate of
* https://github.com/gradle/gradle/issues/25824
