### ISSUE TITLE
Add .idea/icon.png (and .idea/icon_dark.png) for icon in IDEA and JetBrains Toolbox

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#12722]
Sample: https://github.com/apache/jmeter/pull/579 , https://github.com/junit-team/junit5/pull/2240

Frankly speaking, I'm not sure where to get Gradle icon that works in light and dark modes.

Output:

Toolbox:
<img width="432" alt="Toolbox" src="https://user-images.githubusercontent.com/213894/78499940-63021980-775c-11ea-9dfb-322267ef01b7.png">

IDEA:

<img width="665" alt="IDEA" src="https://user-images.githubusercontent.com/213894/78499961-7ad99d80-775c-11ea-836e-ef101af78d13.png">

**Comment by big-guy** [comment]
We have icons available on https://gradle.com/brand/

Do you know what the requirements are for this logo (dimensions/size)?

**Comment by vlsi** [comment]
128x128

>

**Comment by vlsi** [comment]
Just in case, there can be two icons: `.idea/icon.png` and `.idea/icon_dark.png`.

https://github.com/JetBrains/intellij-community/blob/b2295bc87c633200ff49ed0f87eeeb16cf469ad0/platform/platform-impl/src/com/intellij/openapi/wm/impl/welcomeScreen/ChangeProjectIconForm.java#L68-L69

**Comment by vlsi** [comment]
The icons have already been merged, so closing the issue.
