### ISSUE TITLE
 Continuous Build doesn't work within a Docker Container

### ISSUE THREAD

**Issue by zavalit** [gradle/gradle#1272]
Hi, I try to delegate the project build into a container.

### Expected Behavior

file changing within src/main/java/project folder have to trigger rebuild, if container is currently executing ```gradle build -t``` within a project root folder.

### Current Behavior

changes on a file, that have to be mounted into a docker container, doesn't trigger a rebuild

### Steps to Reproduce (for bugs)

1 .  ``` docker run --rm -it -v $PWD:/app  java8 gradle build -t ```
2. changing a file(that mounted within an /app folder)
3. nothing happens

### Your Environment

 * Build scan URL: https://gradle.com/s/ylauxy4xfusmc
Docker Image: Alpine 3.4
Gradle version 3.3. 
Java 8
Host System: Mac OSX.

**Comment by bmuschko** [comment]
Can you describe what you mean by "3. nothing happens"? Are you saying that the task is up-to-date? What kind of project are you building?

**Comment by oehme** [comment]
Closing as there was not enough information to reproduce. Please feel free to reopen with a reproducible example project - in this case ideally as a docker image.

**Comment by bvkatwijk** [comment]
I ran into this issue using Gradle 5.2.1 with Docker on Windows 10. I've created a [sample repository](https://github.com/bvkatwijk/gradle-issue-1272) showcasing the behaviour.

Interestingly the setup works for me using Mac OS Mojave.

**Comment by big-guy** [comment]
Thanks @bvkatwijk - I don't know for sure, but I suspect this is a limitation with the way the filesystem is shared with the container on Windows (maybe https://github.com/docker/for-win/issues/56)?

We're relying on the JDK's file watching APIs, which use FS events (or polling on macOS) to drive continuous build.

**Comment by Heasummn** [comment]
I am still seeing this behavior in Gradle 5.4, continuous builds are not happening inside of a docker container hosted on a Windows machine.

**Comment by warrenc5** [comment]
I have written java Watcher code and see that inotify events are not triggered inside the container (on mounted volumes or in the image itself) - this is a docker issue not a gradle issue. This is a well known issue ( "docker file system + inotify" in your favourite SE)
Some workarounds for MAC worth mentioning - 
https://stackoverflow.com/questions/70117645/inotify-on-docker-mounted-volumes-mac-linux
