### ISSUE TITLE
Resolving a dependency prevents its further use as a BOM

### ISSUE THREAD

**Issue by frost13it** [gradle/gradle#12728]
### Expected Behavior
Resolving a configuration with some dependency does not affect other usages of the dependency, including platform consumption.

### Current Behavior
Gradle does not use constraints from a transitive platform after it is resolved as part of some configuration.

### Context
Structure of the project:
```
: (root)
   :submodule 
```

The root project is a Java platform that depends on `com.fasterxml.jackson:jackson-bom`.
The `submodule` project is a Java library that consumes root project as a platform and depends on `com.fasterxml.jackson.core:jackson-databind` (without version specified).
Also there is `resolve` task in the root project, which creates a detached configuration with `com.fasterxml.jackson:jackson-bom` and resolves it.
Complete code is here: [test-project.zip](https://github.com/gradle/gradle/files/4437295/test-project.zip).

### Steps to Reproduce
`gradle clean build` runs successfully.
`gradle clean resolve build` fails with the following message:
```
Execution failed for task ':submodule:compileJava'.
> Could not resolve all files for configuration ':submodule:compileClasspath'.
   > Could not find com.fasterxml.jackson.core:jackson-databind:.
     Required by:
         project :submodule
```
The same behavior can be achieved via the `dependencies` task (`gradle clean :dependencies build`).

### Your Environment
Gradle 6.3
Build scan for successful build: https://scans.gradle.com/s/mhuw54fvzpm6k
Build scan for failed build: https://scans.gradle.com/s/4asqjudx5ohdq

**Comment by melix** [comment]
Thanks for the reproducer. The bug is in the `java-platform` plugin. Not going into the details, a workaround is to apply the `java-base` plugin to in addition to the `java-platform` plugin.
