### ISSUE TITLE
gradlew issue

### ISSUE THREAD

**Issue by ret394** [gradle/gradle#12730]
### Expected Behavior

don't know. maybe the help should be shown? if its the correct, else show the correct way instead.
### Current Behavior

https://gist.github.com/ret394/4ce1f1562c503f4bdc109c3ea67bf40a

### Context

to use gradle for 1 single project without major pains.

### Steps to Reproduce 

1. `git clone https://github.com/Arcnor/pixel-dungeon-gdx --depth=1`
2. `git branch newbranch`
3. switch to it and try .\gradlew.bat -h

### Your Environment

Build scan URL:
none.

**Comment by big-guy** [comment]
I think it could be one of two things:
- You need to switch to HTTPS in https://github.com/Arcnor/pixel-dungeon-gdx/blob/master/gradle/wrapper/gradle-wrapper.properties#L6. We disabled access over HTTP earlier this year:  https://blog.gradle.org/decommissioning-http
- services.gradle.org was temporarily unavailable at the time you tried to download that file. It's working now.

**Comment by ret394** [comment]
changing line to `distributionUrl=https\://services.gradle.org/distributions/gradle-1.11-all.zip` worked. 

thanks. have a nice day. keep up the good work.

[ret394](https://github.com/ret394)
