### ISSUE TITLE
/tmp cluttered up with gradle-worker-classpath* files

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#12745]
### Expected Behavior
Even after of 10 hours of running Gradle builds I would like to be able to easily find an arbitrary disposable file saved from Firefox (or any other application) in `/tmp`.

### Current Behavior
Every Gradle build generates the `gradle-worker-classpath*` file in the root of the system temporary directory (`/tmp` on Linux) which makes it harder to find anything else there.

### Context
After a day of running Gradle builds it might be problematic to find an arbitrary disposable file saved there to be used (and to be forgotten after a system restart).
The files seem to be never cleaned up. They seem to be not reusable across builds (every build using a daemon creates the new one). Maybe they could be cleaned up on successful execution?
In a case they are used for build cache or anything else maybe or it's not feasible to automatically remove them, they could be created in a subdirectory in `/tmp`, not in its root.

The problem occurs with Gradle 5.x, tested also with the latest 6.3.

**Comment by centic9** [comment]
This is pretty much the same as issue #12020, maybe this one can be closed duplicate to avoid double discussions.

**Comment by szpak** [comment]
You are right, @centic9. Closing in favor of #12020.

**Comment by BonusLord** [comment]
+1, our automated testing nodes are suffering from this tmp file accumulation
