### ISSUE TITLE
Java compile warnings appear on same line as task name in console

### ISSUE THREAD

**Issue by hWorblehat** [gradle/gradle#1275]
This issue is a migration of [GRADLE-1230](https://issues.gradle.org/browse/GRADLE-1230) from jira. When the java or groovy compiler outputs a warning, it appears on the same line as the compilation task name in the console. As well as being unsightly, this affects output parsers that are looking for either warnings or task names.

### Expected Behavior
Using [this](https://gist.github.com/hWorblehat/d1705dd70e7cc4f007b7d4b20aa84234) gist as a single-folder gradle project, the warning about unchecked or unsafe operations should appear below the `:compileJava` line in the console.

### Current Behavior
Instead, it appears on the same line.

### Steps to Reproduce (for bugs)
Download the gist linked above and run `gradle classes`.

### Your Environment
This bug is reproducible in multiple versions of gradle, from as early as version 0.9 right up to the current version (3.4-rc-1). I have seen it with all JDKs I've tried (Oracle 1.6, 1.7, 1.8). Only tested on Windows.

**Comment by eriwen** [comment]
The logging improvements we're making right now may resolve this because we're more strongly separating logging task names and their logs. Marking this for 4.0.

**Comment by eriwen** [comment]
This is solved by the log buffering/grouping we're doing in 4.0. Please give gradle.org/nightly a try for yourself to verify.

**Comment by adammurdoch** [comment]
Is there test coverage for this?

**Comment by eriwen** [comment]
@adammurdoch Not for this specific issue. I'm not sure if it's worth developing an maintaining a functional test for this. I think investing in more general logging tests is worthwhile, though. Agreed?

**Comment by adammurdoch** [comment]
Yes, general is better. I don't think we'd want to go more general than a task using the compiler infrastructure, or perhaps some test coverage for a task using the worker API.
