### ISSUE TITLE
Gradle dependency locking > inconsistent dependencies resolution with/without --write-locks option

### ISSUE THREAD

**Issue by ghilainm** [gradle/gradle#12751]
I am using Gradle 6.2 (tried with 6.3 as well).

I have an issue with a transitive dependency (org.aspectj:aspectjrt:1.9.5) not being included in the locked dependencies.

I have activated dependency locking like this:
```
dependencyLocking {
    lockAllConfigurations()
}
```

I have run the following command lines:
 `gradle dependency insight --dependency aspectjrt --configuration runtimeClasspath --scan`
and 
`gradle dependencyInsigh --dependency aspectjrt --configuration runtimeClasspath --write-locks --scan`

When I use the '--write-locks' parameter the aspectjrt is not resolved.
When I don't use it is resolved and fails because it is not part of the lock.

It is not the first time I observe this kind of issue I had the same with JUnit platform at one point (solved it by upgrading JUnit).

I can't provide you access to source code but I can provide you with more information by email if you wish (build scans).

**Comment by ljacomet** [comment]
I've reached out on the Gradle community slack to get a build scan.

If possible, could you share here the report output of the `dependencyInsight` task?

**Comment by ljacomet** [comment]
So the underlying issue is linked to excludes and in particular having different excludes on edges that request the same version of a dependency.

More investigation is required to assess how this could be fixed and at which cost, mostly performance wise.
