### ISSUE TITLE
Deprecate `JacocoMerge` task

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#12767]
The `JacocoMerge` task was used to provide single exec files from multiple `test` tasks (or other Jacoco-enhanced tasks). Nowadays, consumers of those exec files either do not exist anymore (most of them switched over to `.xml` and can be consumed via `JacocoReport`) or they accept a list of inputs (e.g. Sonarqube Gradle Plugin).

**Comment by bmuskalla** [comment]
[Sonar Java Analyzer 6.0](https://community.sonarsource.com/t/java-analyzer-v6-0-more-accurate-analysis-with-fewer-false-positives/18547) removes support for `.exec` files.

**Comment by marekjagielski** [comment]
Would it be still possible to generate one html report form multi-module project? Let's say I have few integration test types that each executes on whole multi-module project. I would like to show the joint coverage for example to identify which part of project is being used and which is probably a dead code.

**Comment by bmuskalla** [comment]
@marekjagielski Yes. The `JacocoReport` task accepts a list of `.exec` files as input, there is no need to merge them beforehand, see also [this sample](https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage.html).
