### ISSUE TITLE
gradle-6.3-all.zip Does not contain sources

### ISSUE THREAD

**Issue by gabrielshanahan** [gradle/gradle#12771]
Hello everyone,

when I download https://services.gradle.org/distributions/gradle-6.3-all.zip, the sources are not available, even though they are available when downloading https://services.gradle.org/distributions/gradle-6.2.2-all.zip

jar tf gradle-6.3/lib/gradle-kotlin-dsl-6.3.jar | grep kt -> Returns empty result
jar tf gradle-6.2.2/lib/gradle-kotlin-dsl-6.2.2.jar | grep kt -> Returns many failes ending with .kt 

As a consequence, IDEA only resolves definitions to decompiled .class files

Kind regards,

Gabriel

**Comment by big-guy** [comment]
@eskatos @bamboo was this an intentional change you remember?

**Comment by CristianGM** [comment]
OTOH It would be great if intelliJ was able to download the sources directly instead of forcing the project to use all distribution (even imat CI where you don't care about sources and samples)

**Comment by jjohannes** [comment]
In the original report it looks like the sources were *inside* the kotlin-dsl Jar. Which should not be the case.  So it might have been wrong before. The "sources" belong inside the "src" folder directly insider the "-all" zip. Which is the case for the latest nightly (*.kt files are also there).

I can navigate to the sources in IDEA.
