### ISSUE TITLE
Add support for Clojure and ClojureScript...

### ISSUE THREAD

**Issue by jszakmeister** [gradle/gradle#1277]
Several plugins out there ([gradle-clojure](https://github.com/cursive-ide/gradle-clojure), [graclj](https://github.com/graclj/graclj), and [clojuresque](https://bitbucket.org/clojuresque/clojuresque)) have attempted to provide this support, but all of them are hitting walls.  This is partly due to how fast Gradle is changing, and partly due to not knowing the right way to get things done.  I've been digging around to try and understand exactly what needs to be built in order to support a new JVM-based language, and have come up dry.  Any decent reference to Gradle plugin development is out-of-date (e.g., [Idiomatic Gradle](https://leanpub.com/idiomaticgradle)), so it's hard on this end to know whether I'm heading down the wrong road.  Additionally, it doesn't cover any new features that Gradle 3 and above have to offer, which I'd love to see supported.

It would be very helpful to have a detailed example showing what needs to be done for a new language (both JVM-based and non-JVM based).  But right now, I think the complexity is so high and things are moving so fast that the only reasonable thing to do is to ask the core team to implement support for Clojure and ClojureScript. :-(  So here is my humble request to do so.

**Comment by eriwen** [comment]
Hi @jszakmeister Thanks for your request. One of our major goals for this year is to Streamline plugin development (#1144) which is basically giving the community a bunch of guides, examples, and public APIs. 

I think you'll generally see a shift from us from providing technology-specific plugins and toward enabling users more and more; after all, we cannot do this alone. We'll enable users through individual guidance, if necessary, rather than technical implementation. 

That said, I am happy for us to help connect and promote contributors who are willing to collaborate toward a good plugin. Please speak up on this issue.

**Comment by jszakmeister** [comment]
> I think you'll generally see a shift from us from providing technology-specific plugins and toward enabling users more and more; after all, we cannot do this alone. We'll enable users through individual guidance, if necessary, rather than technical implementation.

I'm probably just being dumb, but I'm not quite sure how to interpret this.  What I hear is that you want to empower users to do develop these kinds of plugins.  I've got that (and agree!).  What I don't understand is what "individual guidance" means.  Do you mean we should ask questions somewhere and get answers?  I've tried interacting with others on the forums, and basically got several people responding showing similar frustrations.  One came back and said the new JVM language support was getting too complicated and the team is evaluating their options now (https://discuss.gradle.org/t/new-jvm-language-plugins/21088/5), and pointed to a couple of resources that may be useful.  But honestly, it really doesn't help me with modern Gradle, and it doesn't really get to the problem: how to go about actually doing the work.

> That said, I am happy for us to help connect and promote contributors who are willing to collaborate toward a good plugin. Please speak up on this issue.

I'm not sure how to read this either.  I think I'm speaking up right now. :-)  Is there something more I should do?  What are your hopes?  I'm happy if any of the 3 Clojure plugins could be made to work well with Gradle.  The author of graclj responded to my thread in the forums with the same frustrations.  I can certainly reach out to him, but we're both in the same boat: how do we go about finishing this support.  I guess my point is that it doesn't help to have more contributors if no one knows how to move forward or how to hook correctly into Gradle.  It's a knowledge problem. :-(

Perhaps connecting us with a developer who might be willing to answer specific questions and point us in the right direction?  I can't speak for the graclj author, but I'm certainly willing to put some time behind it--I don't need a free handout, despite my suggesting it (honestly, it's quite hard digging through the architecture to figure what exactly needs to be done and what a correct Gradle plugin looks like from a language perspective... And I'm not a newbie at this kind of thing!).  But I don't want to chase my tail either. :-)

**Comment by eriwen** [comment]
@jszakmeister 

I'm sorry for being vague, let me be concrete since you shared an interest in this: If you're serious about building a Clojure plugin, I would like to schedule a 1-hour Google Hangout with you (and a collaborator if you like) and @bmuschko (author of Gradle In Action) to discuss what you want to accomplish with your plugin and advise you on how you might go about those things. 

> Perhaps connecting us with a developer who might be willing to answer specific questions and point us in the right direction?

I think this is exactly what you're asking for. The goal would be to take your ideas and design thoughts and give you enough information to go build the plugin having full confidence you're doing it in a future-proof, well-modeled way. Now I recognize in this case we might not be working from scratch (if you've already written a plugin, say), and if that's the case it'd be ideal to know in advance.

After that, we could schedule a follow up implementation review where we check out the plugin source and provide guidance for polishing it (this can be done async or via Hangout). 

If all of that goes well, I expect that we'd want to promote your plugin as a well built Gradle plugin and thank you for your contributions.

What do you think?

**Comment by jszakmeister** [comment]
@eriwen 

> I'm sorry for being vague, let me be concrete since you shared an interest in this: If you're serious about building a Clojure plugin, I would like to schedule a 1-hour Google Hangout with you (and a collaborator if you like) and @bmuschko (author of Gradle In Action) to discuss what you want to accomplish with your plugin and advise you on how you might go about those things.

No worries and thank you for making it more concrete.  Your proposal sounds good to me, but let me reach out to a few people.

> I think this is exactly what you're asking for. The goal would be to take your ideas and design thoughts and give you enough information to go build the plugin having full confidence you're doing it in a future-proof, well-modeled way. Now I recognize in this case we might not be working from scratch (if you've already written a plugin, say), and if that's the case it'd be ideal to know in advance.

Yes, exactly!  I haven't written a Clojure plugin myself yet, but I've been in touch with several who have tried.  I'd like to bring them into the mix because it's ultimately one of their plugins that I'd like to start from and use, if it makes sense.

Give me a little bit of time to reach out to them and see if I can bring the other Clojure plugin authors into the fold (especially since they face similar issues).  And thank you so much for the offer.  I'd definitely like to take you up on it, even if they don't.

**Comment by eriwen** [comment]
I'll await your reply then :)

**Comment by jszakmeister** [comment]
@eriwen I reached out to two plugin  authors (@cursive-ide and @ajoberstar) that I wanted to see be a part of the conversation, and they're interested as well.  So I think we're on.  The one thing I want to do before we schedule something is get you links to the code bases, and put together some information on what we're looking to accomplish and, hopefully, you guys can steer us in the right direction.  Give me a few days to get our thoughts together, and we'll look to schedule something.  Does that sound fair?

**Comment by eriwen** [comment]
That sounds awesome!

**Comment by eriwen** [comment]
@jszakmeister Please mention @bmuschko when you're ready to progress on this. Looking forward to chatting.

**Comment by jszakmeister** [comment]
Will do.  FYI: I'm trying to get some data and some questions together so that we have something to help guide the meeting.  Hopefully, we'll have that done in the next week, and we can look to schedule something.  Sorry it's taking so long... day jobs and all that. :-)

**Comment by jszakmeister** [comment]
@eriwen Sorry it's been so long.  I've gotten some feedback on my document.  I need to make some changes and then I'll give that to you guys to give a bit of background, and then we can schedule some time for a chat.  Again, sorry it's taking so long.

**Comment by eriwen** [comment]
@jszakmeister No apologies necessary, sir! We've been extremely busy ourselves. 

Please let me know when you're ready anytime. 

Aside, I think it'd be great to have a talk on working with Gradle and Clojure at the Gradle Summit. Perhaps you'd be interested? https://summit.gradle.com/speak

**Comment by bmuschko** [comment]
@jszakmeister Cool, ping me after organizing your thoughts and we can have a chat!

**Comment by neuromantik33** [comment]
+1

@jszakmeister if you need some help, I'm able and willing... I'm learning clojure atm and Leiningen is just too slow (no daemon) compared to gradle. Right now my support is calling my own LeinTask which is simply not cutting it ;)

**Comment by jszakmeister** [comment]
@bmuschko and @eriwen Sorry it's been so long.  Work has been extremely busy as well as baseball season with my kids.

Attached is some information about current plugins, Clojure and ClojureScript, and some desired goals.  We could probably have some of that conversation on here, if folks are busy.  I know my schedule is a bit in chaos right now, and may get worse for the next 30 days or so.

> Aside, I think it'd be great to have a talk on working with Gradle and Clojure at the Gradle Summit. Perhaps you'd be interested? https://summit.gradle.com/speak

Perhaps next year when we've done something more.  Right now, things are in a pretty rocky spot.  It'd be nice to have a better story before engaging the wider community. :-)

---

Here's our document:

* There are several attempts at Clojure plugins:

  - clojuresque - Hasn't been touched since late October 2015
    (https://bitbucket.org/clojuresque/clojuresque).  This project stalled due
    to the inability to keep up with Gradle API changes has been a real burden.

  - gradle-clojure - Colin Fleming's plugin that really got started as a way to
    build Cursive.  It's definitely a good start, but there's more to be done to
    support a polyglot environment, different source sets, etc.

  - graclj - Andrew Oberstar's plugin that attempts to use the new Software
    Model to provide Clojure support.  Unfortunately, Gradle seems to have
    stalled development on the software model approach, so it's unclear what
    direction to go in.

* Goals

  - To have solid Clojure and ClojureScript support in Gradle.

  - To "future-proof" the plugin as much as possible to avoid the same fate as
    Clojuresque where changing APIs is becoming too hard to support while
    maintaining compatibility for users.  This is highly important to us.

  - To take advantage of new features that Gradle is offering, especially on the
    JVM language, where it makes sense.

* We'd like to make either [gradle-clojure](https://github.com/cursive-ide/gradle-clojure)
  or [graclj](https://github.com/graclj/graclj) the plugin to build your
  Clojure and ClojureScript code (we'd use whatever one is closer to the what we
  need).

* Some Clojure specifics:

  - The Clojure compiler only builds Clojure (`*.clj`) files.  It doesn't not
    support joint Java and Clojure compilation like Scala.

    * Clojure integrates well with Java, but the Java classes need to be present
      to build.

  - `*.cljc` can be compiled under both Clojure and ClojureScript and is
    supported by Clojure 1.7 and greater using reader conditionals.  We want to
    support this.

  - Packaging is done one of three ways: the source files only, ahead-of-time
    compiled (AOT) only, and both in a single jar.  There are some headaches
    here:

    * The timestamps of the files need to be preserved to avoid Clojure
      recompiling the source files.  The Shadow plugin was fixed to support
      this: https://github.com/johnrengelman/shadow/pull/260

    * There's been discussion around the fact that we might need to make AOT
      compilation "infectious" (i.e., we need to AOT compile all libraries
      whether they were supplied that way or not).  See this comment:
      http://dev.clojure.org/jira/browse/CLJ-1544?focusedCommentId=43558&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-43558

    * Many projects don't compile... they just ship source.

  - Clojure can produce many classes from a single file.  If there's only one
    namespace per file (and the convention is to name the file and the namespace
    the same), and the namespace is a.b.c, then the file will be named `c.class`
    and may have additional class files of the form `c$*.class`.  It is,
    however, acceptable to have more than one namespace in a file.  The above is
    only convention.  Records and protocols can introduce classes that don't
    follow the above naming convention, so it's hard to identify which class
    files go with which Clojure files.  Is there a strategy we could employ that
    would help us make the correct association and maintain that between runs of
    Gradle?

    * We'd be okay saying "we don't support more than one namespace in the
      file" (we only support the convention rather than the full capability),
      but we'd be interested in supporting the full capability would be hard in
      Gradle.

    * It's also hard to identify the dependent Java classes.  Using AOT, we
      might be able to inspect the resultant byte code (if Gradle has support
      for such things) to help identify dependencies.  However, from a source
      build perspective, that may not be possible--or at least, it's not
      directly accessible.

* ClojureScript specifics:

  - The compiler builds `*.cljs` files, and is shaped much the same way as
    Clojure.   It too supports the `.cljc` extension.

  - The ClojureScript compiler uses Clojure and Google Closure, and has several
    different output formats (single file, multiple files, source maps, etc.).

  - There are a fair number of compiler options that we'd need to support:
    https://github.com/clojure/clojurescript/wiki/Compiler-Options

  - Optimized builds can take a long time.

  - It'd be nice to be smart here.  I don't think we can avoid compiling
    everything if there's a single output file and a source file changes.  In a
    development build, that might be a different story.

* It'd be nice to provide some helpful tooling to support getting a REPL in for
  both environments, or to at least provide some footing for that kind of
  tooling to be built.  Something like Fighweel
  (https://github.com/bhauman/lein-figwheel) would be really nice to support in
  ClojureScript.

* Things we'd like to get out of the discussion:

  - What is happening on the Software Model front?  Is it alive and well?  Is it
    still the future direction?

  - How about on the JVM language front?

  - What approach should we be taking?  How do we future-proof the plugin as
    much as possible?  How do we leverage what has been done?  Any guidance that
    can be offered here?  Example code, a basic plugin implementing compilation
    for a new JVM language, etc.?

    * Can this be done in a way that will support Gradle 2.x and leverage
      benefits and features from Gradle 3.x?  At what cost?  Are they two
      different approaches?  Or is there some common ground?

  - For all the documentation that's out there, there really isn't much on the
    language support front.  The best resource we've seen is Idiomatic Gradle,
    but it's written for the 2.x line, and it's not clear we should be following
    its stragies for the 3.x line and beyond.

  - Any suggestions on handling the fact that one Clojure file produces multiple
    class files?  We'd really like to avoid folks having to do a clean and
    rebuild everything again.  It just makes for a slow development cycle.

  - WRT API compatibility, even in the short time I’ve been working on the
    plugin, I’ve had to do things like
    https://github.com/cursive-ide/gradle-clojure/blob/master/src/main/groovy/cursive/ApiFacade.groovy#L34-L40.
    There must be a better solution for this.

  - Anything you feel we should know and haven't explicitly mentioned.  Part of
    the issue right now is that we don't know what we don't know. :-)

**Comment by eriwen** [comment]
@jszakmeister Thank you very much for your reply and for your patience as we recover from the Gradle 4.0/Gradle Summit rush.

I propose that @bmuschko and I meet with you for a 1-hour Google hangout to discuss what you've asked and respond to your design concerns. Are there any good times for you this month? Both Ben and I are in the US, FYI for scheduling. Are there others you'd like to invite? Please let us know and I'll get it scheduled ASAP.

**Comment by jszakmeister** [comment]
@eriwen No problem!  I'm sure you guys are busy--you all have been cranking out release after release lately. :-)

I'm in the US as well.  I would like to include @cursive-ide and @ajoberstar if possible.  I believe Andrew is in the US as well, but Colin is in New Zealand.

For me, Thursdays work best or afternoon to evening on Tuesdays.  On the whole, I'm fairly flexible with my only really bad times being Tuesday mornings and all day on Wednesdays.

@cursive-ide @ajoberstar care to jump in with times that work for you guys?

**Comment by cursive-ide** [comment]
Sure, as a starter for 10 Thursday afternoon/evening US time would work well for me. I'm pretty far from EST right now ([meeting planner](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20170725&p1=2096&p2=137&p3=179)) but I could do from 7:30am my time (3:30pm EST, 12:30pm EDT).

Mostly I'm pretty flexible, and can do from that time any day with a bit of notice.

**Comment by ajoberstar** [comment]
I can join in too (I'm in CDT). Evenings work best for me, so more in the 6:30 EDT or later would be preferred.

**Comment by eriwen** [comment]
@jszakmeister @cursive-ide @ajoberstar @bmuschko Would this Thursday at 4pm PDT/6pm CDT/7pm EDT/11am NZ time work for everyone? If so, could you please send me your email addresses to eric@gradle.com and I'll send out an invite. If not, please let me know if next week at that time would work.

**Comment by ajoberstar** [comment]
That time works for me.

**Comment by cursive-ide** [comment]
That works for me.

**Comment by cursive-ide** [comment]
BTW there's more discussion highlighting the sorts of issues we're having in cursive-ide/gradle-clojure#12.

**Comment by jszakmeister** [comment]
Works for me too.

**Comment by oehme** [comment]
Since we won't add Clojure support to Gradle itself I'm going to close this issue. However, please open specific issues if an API (or lack thereof) is stopping you from developing a great Clojure plugin.
