### ISSUE TITLE
Provide a means to include generated POM into produced JAR files

### ISSUE THREAD

**Issue by alexei-osipov** [gradle/gradle#1278]
Original issue: https://issues.gradle.org/browse/GRADLE-2916

I want to include generated pom.xml (produced by "generatePomFileForMavenJavaPublication" task) into resulting JAR file. Just as Maven does that.

The problem is that task "generatePomFileForMavenJavaPublication" not available during project configuration phase. So I can't do something like that:
```
jar {
        into("META-INF/maven/$project.group/$project.name") {
            from generatePomFileForMavenJavaPublication
            rename ".*", "pom.xml"
        }
    }
```
Is there any way to do that?

**Comment by bmuschko** [comment]
The task `generatePomFileForMavenJavaPublication ` is created late during the configuration phase. You will have to defer the creation of the reference to the task by assigning the task as `Closure` return type in the `from` statement.

```
jar {
    into("META-INF/maven/$project.group/$project.name") {
        from { generatePomFileForMavenJavaPublication }
        rename ".*", "pom.xml"
    }
}
```

There are certainly other ways around it but I think this is the most elegant.

**Comment by goldyliang** [comment]
For me, I am using  maven-publish, and the solution above does not work. Eventually, I got it work with below:

apply plugin: 'maven-publish'

publishing {
	publications {
			pluginDist(MavenPublication) {
					from components.java
			}
	}
}

jar {
	doFirst {
		tasks['generatePomFileForPluginDistPublication'].execute()
	}

	into("META-INF/maven/$project.group/$project.name") {
		from "$projectDir/build/publications/pluginDist"
		rename ".*", "pom.xml"
	}
}

**Comment by AlexByte** [comment]
@goldyliang task `generatePomFileForMavenJavaPublication` must be used.

**Comment by AlexByte** [comment]
Why somebody might need to include generated POM into produced JAR files?

**Comment by panchenko** [comment]
@AlexByte There is an answer on [SO](https://stackoverflow.com/questions/1677994/what-is-the-significance-of-the-pom-file-that-maven-places-in-a-jar-file-is-it).

**Comment by goldyliang** [comment]
To be more complete an answer, following snippet can be added if want to include the pom in the zip file, which is deployed as Maven:

```
distZip {
    into("META-INF/maven/$project.group/$project.name") {
        from { generatePomFileForMavenJavaPublication }
        rename ".*", "pom.xml"
    }
}
```

**Comment by trejkaz** [comment]
What about the pom.properties file? Why can't it just do all this by default? :(
