### ISSUE TITLE
Disable SSL check

### ISSUE THREAD

**Issue by Vant1032** [gradle/gradle#12793]
### Expected Behavior

Can you add an option so we can disable SSL check?

Some thing like java -Dssl.check.disable=true
### Current Behavior

There is no way to disable ssl check.

### Context

I encounter exception like PKIX path fail blah blah.Maybe you will say I can use keytool to import certificate.But I tried, and failed. I don't know why.Maybe my network or something else is abnormal.So I debug gradle and find it is use Apache HttpClient to establish ssl connection.
I want to change the behavior of ssl check, but I find nothing to disable ssl check.Can you add a feature to disable ssl check, please, please please!

**Comment by big-guy** [comment]
Sorry, but this isn't something we'll be adding.

If you can't use HTTPS when downloading dependencies (you really should), you can use HTTP instead, which won't use SSL.
