### ISSUE TITLE
Creating repositories in subprojects taking longer than reusing root project repositories

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#12801]
The AndroidX team is observing that reusing repository objects across individual build.gradle files saves an average of about 0.16 seconds over recreating them in each project ( https://android-review.googlesource.com/c/platform/frameworks/support/+/1284100 )

In particular, it seems that this code:

  allprojects {
    repositories {
      google()
      mavenLocal()
      jcenter()
    }
  }

executes about 0.08s more slowly, on average, than this code:

  repositories {
    google()
    mavenLocal()
    jcenter()
  }
  subprojects { subproject ->
    subproject.repositories.addAll(subproject.rootProject.repositories)
  }

when settings.gradle declares ~400 projects.

To reproduce, see https://github.com/mathjeff/gradle-samples/tree/master/sharing-repository-configuration-durations

Maybe Gradle could make the former run as fast as the latter, since the former is probably what developers more commonly write?

Thanks

**Comment by big-guy** [comment]
We're trying to discourage the use of allprojects/cross-project configuration.

For repositories specifically, we have a centralized repository definitions: https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration
