### ISSUE TITLE
Can't apply a plugin from buildSrc in my settings.gradle.kts

### ISSUE THREAD

**Issue by hichem-fazai** [gradle/gradle#12804]
My plugin in buildSrc :
````kotlin
class GreetingPlugin : Plugin<Settings> {
  override fun apply(target: Settings) {
    println("hello")
  }
}
````
in settings.gradle.kts :
````kotlin
apply<GreetingPlugin>()
````
I'm getting the error :
`Unresolved reference: GreetingPlugin`

**But if I put GreetingPlugin in settings.gradle.kts, it works fine. It looks like settings.gradle.kts cant access buildSrc.

I'm using :
Gradle:     6.1.1
Kotlin:       1.3.61

**Comment by ljacomet** [comment]
This is expected and documented as a breaking change in Gradle 6.0.

See the [migration guide](https://docs.gradle.org/6.0/userguide/upgrading_version_5.html#classes_from_buildsrc_are_no_longer_visible_to_settings_scripts) for details.
