### ISSUE TITLE
Dependency order not honored by tooling API

### ISSUE THREAD

**Issue by charlesritchea** [gradle/gradle#1280]
I think I'm having a problem with this issue <https://issues.gradle.org/browse/GRADLE-2294> which I did not find on github.

My problem is that I have JUnit 4 tests that use JMockit. Everything works fine when run from gradle, but if I try to run in Intellij all of the Mocked objects are null implying that JMockit was not initialized which implies that JUnit is getting loaded before JMockit despite the correct order being present in the testCompile dependencies. I can work around it by using RunWith(JMockit.class) but this prevents me from combining JMockit with JUnitParams or any other JUnit runner.

As you can see from here <https://youtrack.jetbrains.com/issue/IDEA-119709> JetBrains claims this is the responsibility of the tooling API

**Comment by novaterata** [comment]
I'm using gradle 3.2.1
Here are my test deps:
```
    testCompile 'commons-io:commons-io:2.5'
    testCompile 'pl.pragmatists:JUnitParams:1.0.5'
    testCompile 'org.hamcrest:hamcrest-all:1.3'
    testCompile 'org.jmockit:jmockit:1.30'
    testCompile 'org.assertj:assertj-core:3.5.2'
    testCompile 'org.yaml:snakeyaml:1.17'
    testCompile 'com.fasterxml.jackson.core:jackson-core:2.8.3'
    testCompile 'com.fasterxml.jackson.core:jackson-databind:2.8.3'
    testCompile 'com.fasterxml.jackson.core:jackson-annotations:2.8.3'
    testCompile 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.8.3'
    testCompile 'org.slf4j:slf4j-api:1.7.21'
    testCompile 'uk.org.lidalia:slf4j-test:1.1.0'
    testCompile 'com.jcabi:jcabi-log:0.17.2'
    testCompile 'junit:junit:4.12'
    testCompile 'org.jooq:jool:0.9.12'
    testCompile 'org.languagetool:language-all:3.4'
    testCompile 'com.optimaize.languagedetector:language-detector:0.5'
    testCompile 'org.antlr:ST4:4.0.8'
```
