### ISSUE TITLE
Exceptions thrown in TestEngine.discover() are swallowed by test tasks

### ISSUE THREAD

**Issue by fcurts** [gradle/gradle#12813]
### Expected Behavior

When an implementation of `org.junit.platform.engine.TestEngine.discover()` throws an exception, the test task and build should fail.

### Current Behavior

The test task and build succeed even though no tests were executed.

### Context
CI builds have been green for weeks even though they weren't actually executing any tests. We only discovered this when we noticed a stack trace in the CI build logs:

```
Gradle Test Executor 12 STANDARD_ERROR
    Apr 13, 2020 6:05:10 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
    WARNING: TestEngine with ID 'xxx' failed to discover tests
    java.lang.NoSuchMethodError: [...]
```

### Steps to Reproduce 
Write an `org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine` that throws (say) `AssertionError` in `TestEngine.discover()`. Write an empty test class annotated with `@org.junit.platform.commons.annotation.Testable`. Execute the test task.

### Your Environment

Gradle 6.2.2, JDK 8 or 11, macOS 10.15.3 or Docker with Oracle Linux 8

**Comment by bmuskalla** [comment]
Thanks for raising this. This has been fixed by upgrading the junit platform launcher in 6.4. See #12489 for details
