### ISSUE TITLE
Application Plugin Generated Scripts Print Inaccurate Error and Needlessly Have Env. Dependency

### ISSUE THREAD

**Issue by dlandis** [gradle/gradle#1281]
The Unix scripts generated by the application plugin depend on the OS having the `which` utility installed. That program is not commonly included nowadays in many standard Docker images such as `centos:latest` (not to mention more minimal images such as Alpine). 

If you don't have it installed and you don't have JAVA_HOME set, then the generated script erroneously prints:
```shell
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
```

It would be better to use a builtin utility such as `hash` to achieve the same thing. You could change the generated line to:

```shell
    hash java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
```

Reproduced in Gradle 3.3

**Comment by bmuschko** [comment]
@dlandis Thanks for your assessment. Would you be interested in providing a pull request to fix the issue?

**Comment by dlandis** [comment]
@bmuschko Yeah sure

**Comment by bmuschko** [comment]
@dlandis Thanks! The PR should also come up with some sort of way to test the proposed change.
