### ISSUE TITLE
How to get the Third party dependencies of newest version in gradle

### ISSUE THREAD

**Issue by ljzyljc** [gradle/gradle#12819]
Now my project apply the third dependency implementation "org.greenrobot:eventbus:3.1.1"，and my project hava a lot of third party dependenies like eventbus(the newest vesion is 3.2.0)，I know the IDE(Android Studio) can prompt us have the newest version，but it's just a prompt，so I can't get the real newest version(I want to print it)。and I can't do like this implementation "org.greenrobot:eventbus:3.+"，because there may be some bug in third dependenies if we always denpend on the newest。I just want to print the newest version,  how should I do that I can get the newest version of third party denpendcies through gradle or gradle plugin and print it (need print the version)?@blindpirate

**Comment by ljacomet** [comment]
There is currently no core support for this in core Gradle.

There are however community plugins that provide a similar functionality. Have a look at the [versions plugin](https://plugins.gradle.org/plugin/com.github.ben-manes.versions) for example.

**Comment by ljacomet** [comment]
Note that you could also leverage dynamic versions (`3.+`) and [dependency locking](https://docs.gradle.org/6.3/userguide/dependency_locking.html) where the update locks feature can be used to attempt version upgrades.

**Comment by ljzyljc** [comment]
@ljacomet，thank you very much! great!

**Comment by ljacomet** [comment]
Closing as there are no plans to offer this in Gradle core for now.
