### ISSUE TITLE
gradle init gives an error: Return code is: 501 , ReasonPhrase:HTTPS Required

### ISSUE THREAD

**Issue by iamranga** [gradle/gradle#12825]
I have a maven project with below specific entries - 

1. Under `<dependencyManagement>` tag
`            <dependency>`
       `        <groupId>org.arquillian</groupId>`
       `        <artifactId>arquillian-universe</artifactId>`
`        <version>1.1.15.2</version>`
`        <type>pom</type>`
`        <scope>import</scope>`
`</dependency>`

2. Below mentioned in `<repositories>` tag section
`<repository>`
`	      <id>MavenCentral</id>`
`	      <url>http://repo.maven.apache.org/maven2</url>`
`	    </repository>`

### Expected Behavior
When i issue a gradle init command for the above mentioned project, i expect build.gralde to be created by resolving the imported pom from MavenCentral using **https://**, even though transport protocol scheme mentioned in the repository tag of pom.xml is **http://**

### Current Behavior
When i issue gradle init command to aforementioned project, the command errors out with below error - 
`> Task :init`
`Maven to Gradle conversion is an incubating feature.`

`> Task :init FAILED`

`FAILURE: Build failed with an exception.`

`* What went wrong:`
`Execution failed for task ':init'.`
`> Could not convert Maven POM /Users/user/Desktop/SampleMavenApp/pom.xml to a Gradle build.`
   `> Unable to create Maven project model using POM` `/Users/use/Desktop/SampleMavenApp/pom.xml.`
 `     > Some problems were encountered while processing the POMs:`
  `     [ERROR] Non-resolvable import POM: Could not transfer artifact org.arquillian:arquillian`
`universe:pom:1.1.15.2 from/to MavenCentral (http://repo.maven.apache.org/maven2): Failed to`
`transfer file: http://repo.maven.apache.org/maven2/org/arquillian/arquillian`
`universe/1.1.15.2/arquillian-universe-1.1.15.2.pom. Return code is: 501 , ReasonPhrase:HTTPS` `Required. @ line 13, column 16`

### Steps to Reproduce 
1. Create a maven project with pom.xml having dependency management tag and repository with no mention of maven central repository.
2. Issue gradle init command.

### Your Environment
I used Gradle 5.5 version for executing gradle init task, on Mac OS.

Please let me know if am missing anything

**Comment by ljacomet** [comment]
`http` is no longer supported for [Maven Central interactions](https://blog.sonatype.com/central-repository-moving-to-https), for security reasons. The existence of that `repositories` tag with an `http` reference makes your Maven project invalid.
There should be no expectation that Gradle `init` can work off an invalid Maven project.

Remove the `repositories` tag and try again.

**Comment by iamranga** [comment]
@ljacomet ,
Thanks for your response. I have removed the `repositories` tag and tried `gradle init`. I am  still getting the same error as mentioned in my original post.
