### ISSUE TITLE
Android uses gradle: 3.6.2 so path after packaging

### ISSUE THREAD

**Issue by milanxiaotiejiang** [gradle/gradle#12824]
This is my demo link https://github.com/milanxiaotiexiang/myapplication

The code in mainactivity of my program homepage is as follows
```
        String path = getApplicationInfo().nativeLibraryDir;
        Log.e(TAG, path);
        File[] files = new File(path).listFiles();
        Log.e(TAG, "" + files.length);
       //...
```
Under the two versions of gradle plugin 3.5.2 and 3.6.2, the values in getapplicationinfo#native librarydir are from 5 to 0 (because there are five so files in total)
Check the APK file after packing. The so does exist
Please ask me how to solve this problem and how to configure it in gradle. I've tried a lot and don't want to go back to the gradle version.

Tried
```
    sourceSets {
        main.jni.srcDirs = []
        main.jniLibs.srcDirs = ['libs']
    }
```

```
        ndk {
            abiFilters "armeabi-v7a"
        }
```

Android Studio : 3.6.2
Android Gradle Plugin Version : 3.6.2 / 3.5.2
Gradle Version : 5.6.4

And after packing, the Lib directory is 1.5MB larger. What's the matter?

English is not very good, please forgive me.

**Comment by HraD** [comment]
Has the same issue with latest Studio and Gradle.
Sample new project from Android Studio (simple empty activity), .so files are in src\main\jniLibs. I can see libs in compiled apk, but they are not installed into getApplicationInfo().nativeLibraryDir...


distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
classpath "com.android.tools.build:gradle:4.1.1"

Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: ModuleLibraries, myBitbucket, Lombook Plugin, com.apkfuns.androidsourceviewer, com.dengzii.plugin.adb, com.thoughtworks.gauge, org.intellij.plugins.markdown, com.intellij.marketplace, org.jetbrains.kotlin, Failed Line Inspection for Kotlin, cn.bestwu.gdph, org.jvmlet.intellij.reveal-dependency-plugin, com.wuyr.google_library_query, me.scana.okgradle, com.layernet.plugin.adbwifi, com.atlassian.bitbucket.references

**Comment by blindpirate** [comment]
This doesn't look like a Gradle issue, why do you think it's a Gradle issue?
