### ISSUE TITLE
Gradle Image using docker 

### ISSUE THREAD

**Issue by 2020testuser** [gradle/gradle#12829]
I'm using Gradle image (from docker repo.) to build my SpringBoot application and getting the below error.
Caused by:java.io.IOException:Cannot run program 'docker' (in directory "/workspace/source"} : error=13, Permission denied.
I've the docker in docker setup . In my Dockerfile, I I have /var/run/docker.sock mount to the host system's /var/run/docker.sock.

### Expected Behavior

The image must build the application without any docker errors.

### Context
I'm trying to build the application using Gradle image inside a container without any errors.

### Steps to Reproduce 
1. Use the gradle image from the docker repo.
2. Use the gradle command within the Docker file to build the application.

### Your Environment
Running the image from MAC OS. The source code is available locally.

**Comment by bmuskalla** [comment]
The docker image is not maintained by the Gradle team. Please raise this issue with the maintainers of the Docker image: https://hub.docker.com/_/gradle
