### ISSUE TITLE
Let the user override the main distribution contents configured by the ApplicationPlugin

### ISSUE THREAD

**Issue by tnielens** [gradle/gradle#12823]
Currently, gradle application plugin creates a main distribution, puts all runtime dependencies and main jar in the `lib` folder and startscripts in the `bin` one. I didn't manage to override this behavior. 
`Distribution.contents` is read only and `CopySpec` seems to be append only.

I tried to remove the main distribution and recreate it, but that threw a task recreation error.
```gradle
distributions.removeElement(distributions.main)
distributions {
    main {
        contents {
          // ...
        }
    }
}
``` 
The error: 
```
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'distZip' as a task with that name already exists.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.failOnDuplicateTask(DefaultTaskContainer.java:269)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.registerTask(DefaultTaskContainer.java:410)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.register(DefaultTaskContainer.java:387)
        at org.gradle.api.distribution.plugins.DistributionPlugin.configureArchiveTask(DistributionPlugin.java:104)
```

Is there a straighforward way to do this?

For more details see this stackoverflow issue. https://stackoverflow.com/questions/43734274/gradle-change-main-distribution-get-rid-of-bin-and-lib-folders

**Comment by montrivo** [comment]
Could a core contributor review this request? I'd be happy to implement it.

I see a couple of ways of implementing this: 
- adding a config option on the plugin extension that would undo/not do the distri configuration
- letting the DistributionContainer remove a distribution (and its associated tasks)
- adding a `clear` method on the CopySpec

**Comment by anderso** [comment]
I also stumbled upon this issue, found no obvious solution and created a separate distribution instead trying to change the existing one. But it would be much nicer to be able to disable it or reconfigure it, instead of having two distributions, only one of which is actually used.

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

The application plugin provides an opinionated distribution. You can use a less opinionated `distribution` [plugin](https://docs.gradle.org/current/userguide/distribution_plugin.html), which is a skeleton for building your own distributions.
