### ISSUE TITLE
Testing custom plugin using build.gradle.kts result in an Unresolved reference

### ISSUE THREAD

**Issue by NitroG42** [gradle/gradle#12838]
Following the [documentation](https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-classpath-injection)
I made the following project that should reproduce the issue: https://github.com/NitroG42/GradleIssues/tree/kotlindsl (**be sure to checkout the kotlindsl branch**)
Just run the only test ("testLongRun").

The following code in a build.gradle.kts:
```
        buildFile.writeText(
            """
        plugins {
            `com.nitro.issue`
        }              
            """.trimIndent()
        )
        val result = GradleRunner.create()
            .withProjectDir(testProjectDir.root)
            .withArguments("build", "--info")
            .withPluginClasspath()
            .build()
```
result in 
```
  Line 3:     `com.nitro.issue`
              ^ Unresolved reference: `com.nitro.issue`
```

While in a build.gradle:
```
        buildFile.writeText(
            """
        plugins {
            id "com.nitro.issue"
        }
""".trimIndent()
)
```
Works

### Expected Behavior
The code should work or the documentation should say it isn't compatible with Kotlin DSL

### Current Behavior
It throw an error not recognizing my plugin.

### Steps to Reproduce 
https://github.com/NitroG42/GradleIssues/tree/kotlindsl (**be sure to checkout the kotlindsl branch**)

### Your Environment
Gradle 6.3

**Comment by bmuskalla** [comment]
I think you're missing to add the plugin to the classpath of your tests. Please have a closer look at https://guides.gradle.org/testing-gradle-plugins/#functional-tests and how the sample [sets up functional tests](https://github.com/gradle/guides/blob/master/subprojects/testing-gradle-plugins/samples/code/url-verifier-plugin/gradle/functional-test.gradle)

**Comment by NitroG42** [comment]
On your link i see the following line :

> Every Gradle plugin project should apply the plugin development plugin to reduce boilerplate code. By applying the plugin development plugin, the test source set is preconfigured for the use with TestKit.

Which I did https://github.com/NitroG42/GradleIssues/blob/b91758a31b19d649b00d5d1de8c5e134091438fe/build.gradle.kts#L3 , and I don't have a custom sourceset

**Comment by NitroG42** [comment]
As answered by tbroyer:

> You need to use id("com.nitro.issue").
> 
> Technically com.nitro.issue is a property access / method call but there's no such property/method as this is how you'll load external plugins!
