### ISSUE TITLE
JavaExec.main not settable in doFirst

### ISSUE THREAD

**Issue by wolfseifert** [gradle/gradle#12841]
I have my own "run" task (allprojects):

task("run", JavaExec::class) {
  doFirst {
    main = "defaultClassName"
  }
}

I set "main" in "doFirst" because I want to "override" it using "doLast" in some subprojects.
Using gradle-6.4-rc1 (and also gradle-6.4-20200418230023+0000) I get:

"The value for task 'run' property 'mainClass' is final and cannot be changed any further."

This worked fine with gradle 6.3 and earlier.

**Comment by jjohannes** [comment]
@wolfseifert what you describe is expected as the `main` field is now backend by a [property for lazy configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html).

You should treat the error as a problem with your build script that Gradle now detects.

`main` should not be set in a `doFirst` or `doLast` **task action**. It is meant to be set during task configuration. (Setting in `doLast` also has no effect normally, as the actual running already executed before that.)

Sou you should set it like this:

```
tasks.create<JavaExec>("run") {
   main = "defaultClassName"
}
```

For the "overriding" you can now use the new property `mainClass` (instead of main) and set a convention.

```
// In your task creation code
tasks.create<JavaExec>("run") {
   mainClass.convention("defaultClassName") // convention will be used if the property is not set
}

//...

// In your more specific code where you want to 'override' the convention
tasks.named<JavaExec>("run") {
   mainClass.set("myConcreteClassName")
}
```

**Comment by wolfseifert** [comment]
Ok, `main` should be set during configuration.
But should I use

```
tasks.create<JavaExec>("run") {
   mainClass.convention("defaultClassName")
}
tasks.named<JavaExec>("run") {
   mainClass.set("myConcreteClassName")
}
```
or the more concise

```
tasks.create<JavaExec>("run") {
   main = "defaultClassName"
}
tasks.named<JavaExec>("run") {
   main = "myConcreteClassName"
}
```
Both seem to work. The second one looks more appealing.

**Comment by jjohannes** [comment]
You should use the firs `mainClass.set(...)` as the other will be deprecated soon.

I know that the syntax switch from `=` to `set` can feel "not so nice". But in the future you'll be able to do all configuration using the `set(...)` API and have much less issues with configuration timing (see:  [documentation on lazy configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html)).

**Comment by rkrisztian** [comment]
@jjohannes, why is the assignment operator way (`mainClass = ...`) going to get deprecated? Where is it documented? `mainClass.set(...)` feels fine for Kotlin, but Groovy is more about conciseness, the assignment operator fits the language well there, as we don't call getters or setters in the conventional way in that language. The property API seems to break that design intent of the language. Plus, Gradle was all about look DLS-like in the build scripts. Now we're losing that aspect too. E.g. we don't even remove the optional parentheses from the `set` calls. Same for `ListPoperty`, where assignment never worked at all.

**Comment by rkrisztian** [comment]
Sorry, deleted my comment, the original ticket was about Kotlin.
