### ISSUE TITLE
Ability to use ConfigurableFileCollection with custom Provider

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#12845]
### Expected Behavior
Plugin developers should be able to feed `ConfigurableFileCollection` with values (e.g. a source set) provided by users in the plugin configuration.

### Current Behavior
Existing `ConfigurableFileCollection.setFrom()` can be used to assign a life collection, but the instance has to exist at that time. It doesn't work  with the values provided by users in the plugin configuration.

### Context
Migrating [my plugin](https://github.com/szpak/gradle-pitest-plugin) from Convention Mapping to Lazy Configuration I need to replace:
```
task.conventionMapping.with {
    sourceDirs = {
        extension.mainSourceSets.get()*.allSource.srcDirs.flatten() as Set
    }
}
//Extension: final SetProperty<SourceSet> mainSourceSets
//Task: @InputFiles Set<File> sourceDirs
```

with something like:
```
task.sourceDirs.setFrom(extension.mainSourceSets.get()*.allSource)
//Task: @InputFiles final ConfigurableFileCollection sourceDirs 
```

Unfortunately, it doesn’t work as `extension.mainSourceSets` is `null` when assignment is executed. I would like to have something similar to:

```
task.sourceDirs.setFrom(project.providers.provider() {
    extension.mainSourceSets.get()*.allSource
})
```

but `ConfigurableFileCollection.setFrom()` doesn’t seem to work with that argument (tested with 5.4 and 6.3).

Unless I missed something, without that implemented the `@InputFiles Set<File> sourceDirs` construction should not be marked as deprecated.

My original question at the [forum](https://discuss.gradle.org/t/how-to-configurablefilecollection-setfrom-with-provider/35713).

**Comment by szpak** [comment]
I missed the fact in `Project#files` documentation that I can use `Callable` (or `Clousre`) to achieve the desired behavior.

Just for reference, in my case it was:

```
task.sourceDirs.setFrom({ 
    extension.mainSourceSets.get()*.allSource*.srcDirs
} as Callable<Set<SourceDirectorySet>>)
```

Btw, I had to use coercion to help determine what is returned to prevent:
> java.lang.ClassCastException: class ArrayList1_groovyProxy cannot be cast to class java.util.Iterator (ArrayList1_groovyProxy is in unnamed module of loader org.codehaus.groovy.runtime.ProxyGeneratorAdapter$InnerLoader @38f617f4; java.util.Iterator is in module java.base of loader 'bootstrap')

**Comment by big-guy** [comment]
I think something like... `task.sourceDirs.from(extension.mainSourceSets.flatMap { it.allSource })`  may be close to what you want too.

The closure/callable will erase all dependency information.

**Comment by szpak** [comment]
Yes, with a suggestion @wolfs I ended up with:
```
task.sourceDirs.setFrom(extension.mainSourceSets.map { it*.allSource*.srcDirs })
```
