### ISSUE TITLE
[scala] When the user specifies a non-default version of Zinc, compiler-bridge.jar from DEFAULT_ZINC_VERSION is still used

### ISSUE THREAD

**Issue by retronym** [gradle/gradle#12869]
### Expected Behavior

The compiler-interface.jar should be the same version as the rest of  Zinc,

### Current Behavior

The user is allowed to choose a different Zinc version but this is ignored when downloading the compiler interface.

### Context

While helping a Gradle/Zinc user in https://github.com/sbt/zinc/pull/701, we noticed that the bug fix in Zinc 1.3.5 (which happened to be in the shipped i compiler-interface.jar) was not working.

After some investigation, I realised that an older version of compiler-bridge.jar was still being used.

### Steps to Reproduce 

```
$ git clone -b topic/gradle-zinc-version --single-branch  https://github.com:retronym/kafka.git && cd kafka
$ git show --oneline
```
```diff
136ede16a (HEAD -> topic/gradle-zinc-version, retronym/topic/gradle-zinc-version) Reproducer for Gradle Bug
diff --git a/build.gradle b/build.gradle
index 7675b8175..ac9fa3b9c 100644
--- a/build.gradle
+++ b/build.gradle
@@ -425,7 +425,7 @@ subprojects {
   plugins.withType(ScalaPlugin) {

     scala {
-      zincVersion = versions.zinc
+      zincVersion = versions.zinc // due to a Gradle bug, this version is ignored when resolving compiler-interface.jar
     }

     task scaladocJar(type:Jar) {
@@ -465,7 +465,9 @@ subprojects {
       "-Xlint:private-shadow",
       "-Xlint:stars-align",
       "-Xlint:type-parameter-shadow",
-      "-Xlint:unused"
+      "-Xlint:unused",
+      "-release", "9",
+      "-Ydebug"
     ]

     // Inline more aggressively when compiling the `core` jar since it's not meant to be used as a library.
@@ -495,7 +497,7 @@ subprojects {

     configure(scalaCompileOptions.forkOptions) {
       memoryMaximumSize = '1g'
-      jvmArgs = ['-Xss4m']
+      jvmArgs = ['-Xss4m', '-Xlog:class*=debug:file=/tmp/class.txt']
     }
   }

diff --git a/gradle/dependencies.gradle b/gradle/dependencies.gradle
index 67d85d626..7b2e2e34e 100644
--- a/gradle/dependencies.gradle
+++ b/gradle/dependencies.gradle
@@ -115,7 +115,7 @@ versions += [
   spotbugsPlugin: "4.0.5",
   spotlessPlugin: "3.28.1",
   testRetryPlugin: "1.1.5",
-  zinc: "1.3.5",
+  zinc: "1.3.5", // Due to a Gradle bug, Gradle ignores the value when resolving compiler-interface.jar.
:
```

```
$ ./gradlew --no-daemon --stacktrace :core:compileScala
$ grep ExtractAPI /tmp/class.txt  | grep class,load | head -n1
[21.853s][info ][class,load              ] xsbt.ExtractAPI source: file:/Users/jz/.gradle/caches/6.3/zinc-1.3.5_2.12.11_11/compiler-bridge.jar

$ jar xf /Users/jz/.gradle/caches/6.3/zinc-1.3.5_2.12.11_11/compiler-bridge.jar META-INF/MANIFEST.MF

$ cat META-INF/MANIFEST.MF
Manifest-Version: 1.0
Specification-Vendor: org.scala-sbt
Specification-Title: Compiler Bridge
Specification-Version: 1.3.0
```

### Your Environment
JDK 11, MacOS

### Notes

 - [DownloadingScalaToolChain](https://github.com/gradle/gradle/blob/55cc6461feed063b4ebdb8a709e87bfca1c794e3/subprojects/language-scala/src/main/java/org/gradle/language/scala/internal/toolchain/DownloadingScalaToolChain.java#L74-L78) in Gradle code hard codes references to `DEFAULT_ZINC_VERSION`. It isn't obvious to me if the architecture of Gradle will make it difficult to use the configured version.
 - The user submitted a [PR to Gradle](https://github.com/gradle/gradle/commit/3dfd2b12f0d7ea1c060f135c8abbdd84ca1e5cc4) to upgrade the default Zinc version. Using 6.4-RC1 solves his issue, although the potential for mismatches is still there.
  - We (Lightbend Scala Team) could submit a PR to Gradle to suggest the upgrade on each release to stop the default version from drifting behind. /cc @dnw
  - We are also starting work on the 1.4.x series of Zinc. Some internals have changed but its likely that your integration will not need to change much.

**Comment by ljacomet** [comment]
Thanks for the report.

* `DownloadingScalaToolChain` is part of the Gradle Software Model which is deprecated and planned for removal in the next major.
However the same issue exists in `ScalaRuntime`, which depends on the hard coded default zinc version instead of using the one from the extension, which the user can then modify.
The good news is that wiring both is pretty trivial and so will be fixed in Gradle 6.5.
* Having the Lightbend Scala Team submit a PR to upgrade Zinc on each release of it would be very welcome.
* For the 1.4.x version, hopefully as of Gradle 6.5, it will be easy to see whether or not it requires internal modifications. The earlier it can be tested, the better of course.

**Comment by ijuma** [comment]
> * We (Lightbend Scala Team) could submit a PR to Gradle to suggest the upgrade on each release to stop the default version from drifting behind. /cc @dnw
> * We are also starting work on the 1.4.x series of Zinc. Some internals have changed but its likely that your integration will not need to change much.

@retronym Looks like zinc 1.4.3 has been released. Is Lightbend planning to submit a PR to update the version used in Gradle?

**Comment by marc-szalkiewicz-dd** [comment]
@ijuma I took a quick peek at this, and hopefully the incompatibility is minor: https://github.com/gradle/gradle/issues/15491.
