### ISSUE TITLE
Documentation incorrectly states that --configuration parameter to dependencyInsight is optional

### ISSUE THREAD

**Issue by fransflippo** [gradle/gradle#12861]
https://docs.gradle.org/5.6.4/userguide/inspecting_dependencies.html states:
>Every Gradle project provides the task `dependencyInsight` to render the so-called dependency insight report from the command line. Given a dependency in the dependency graph you can identify the selection reason and track down the origin of the dependency selection. You can think of the dependency insight report as the inverse representation of the dependency report for a given dependency. When executing the task you have to provide the mandatory parameter `--dependency` to specify the coordinates of the dependency under inspection. *The parameters `--configuration` and `--singlepath` are optional but help with filtering the output.*

(Emphasis mine)

However, if I run `./gradlew dependencyInsight --dependency jackson-databind` against my project, I get an error stating:
```
> Dependency insight report cannot be generated because the input configuration was not specified.
  It can be specified from the command line, e.g: ':dependencyInsight --configuration someConf --dependency someDep'".
```

This contradicts the documentation.

### Expected Behavior
When I run `./gradlew -q dependencyInsight --dependency jackson-databind`, insight is shown into how this dependency was included in my project (either in all scopes or in the `compile` scope by default).

### Current Behavior
When I run `./gradlew -q dependencyInsight --dependency jackson-databind`, I get an error stating:
```
> Dependency insight report cannot be generated because the input configuration was not specified.
  It can be specified from the command line, e.g: ':dependencyInsight --configuration someConf --dependency someDep'".
```

### Context
Trying to upgrade libraries in my project that have known vulnerabilities per the NIST NVD. Knowing which dependencies caused a particular JAR to be pulled into my project transitively is essential to be able to make sure the final version of the library that ends up in my project does not have known vulnerabilities.

### Steps to Reproduce 
1. Create a new gradle project: `gradle init` (basic / Groovy / any project name)
2. Run `./gradlew dependencyInsight --dependency jackson-databind`

### Your Environment
* OSX
* Gradle 5.6.4

Either the documentation needs to be fixed explaining that:
1. `--configuration` is *not* optional
2. how to use the `--configuration` parameter

or the `dependencyInsight` task needs to actually work without specifying `--configuration`.

**UPDATE**

OK, so my project is a multi-project and the top-level has no dependencies of its own. That seems to be the problem. If I run the task against a submodule (`./gradlew submodule:dependencyInsight --dependency jackson-databind`), it does work. (Credits to https://stackoverflow.com/questions/24026378/unable-to-see-dependency-tree-with-gradlew-or-gradle for pointing me in the right direction.)

I think that would be useful to add to https://docs.gradle.org/5.6.4/userguide/inspecting_dependencies.html .

**Comment by melix** [comment]
You are correct, `--configuration` is mandatory for `dependencyInsight` (it's only optional for `dependencies`). If you want to see the runtime classpath dependencies, use `--configuration runtimeClasspath` (**not** `runtime`)

**Comment by ljacomet** [comment]
@fransflippo Would you be interested in contributing a fix to the documentation for this?
The source is [here](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/viewing_debugging_dependencies.adoc).

**Comment by fransflippo** [comment]
Guess I can't complain without contributing :-) 

I'll have a stab at it! The usual fork - commit - pull request jive?

**Comment by ljacomet** [comment]
That would be great 😉 
Details are in the [contribution guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md). the main point for a documentation only change is around the commit sign off.

**Comment by ljacomet** [comment]
Note that in this case, you could imply use the edit button on the source I linked
