### ISSUE TITLE
Monobuild request: Import bottom up so I can refactor across multiple projects (composite build)

### ISSUE THREAD

**Issue by deanorderly** [gradle/gradle#12889]
I am setting up a monorepo outside twitter and there are many features that twitter's build system had(pants) that I would LOVE to see in gradle.

This relates to the previous request I opened as well.  In Intellij(and eclipse), I can open a project and all the projects it depends on BUT I want to do the reverse.  I want to open a library and the THREE things that depend on that library so that I can refactor library and Intellij will change all 4 projects.  Currently refactoring is a bit of a pain unlike at twitter's monorepo where I can bring in all 4 projects into intellij just with the click of a button.

**Comment by ljacomet** [comment]
The feature request as it is will not be done in Gradle. However Gradle is working on different things that might end up helping because they would allow either to not pay configuration time at each invocation and/or to select which projects to import in an IDE as opposed to all of them.
