### ISSUE TITLE
Set default DuplicateStrategy for WarTask to `duplicatesStrategy(DuplicatesStrategy.FAIL)`

### ISSUE THREAD

**Issue by DanielWeigl** [gradle/gradle#12883]
Accordingly to https://github.com/gradle/gradle/issues/10856 Gradle now should emit a warning and later on with 7.0 fail on including colliding file names in a ShadowJar.

Would it also make sense to default to `duplicatesStrategy(DuplicatesStrategy.FAIL)` for the `WarTask`? 

We encountered a very strange bug in our project that uses SpringBoot's `BootJar`, which should behave similar to the War-Task, where we included two different, unrelated dependencies which include different modules with the same file name and exact same version string. Which resulted in colliding filenames in the .jar file.

See a more detailed description here: https://github.com/spring-projects/spring-boot/issues/20999

I now tried to run the build with `./gradlew --warning-mode all` (gradle 6.3) but it still does not show any warnings regarding the colliding filenames, but produces a invalid BootJar or BootWar file.

I guess https://github.com/gradle/gradle/issues/10856 is only related to ShadowJar and does not affect BootWar/BootJar Tasks - would it also make sense to include the same behavior there?

```
 ./gradlew bootWar --warning-mode all

unzip -l ./build/libs/myapp-0.1.0.war | grep core-3.4.0 
   244695  2019-12-10 08:48   WEB-INF/lib/core-3.4.0.jar
   539901  2020-03-31 13:10   WEB-INF/lib/core-3.4.0.jar
```

**Comment by DanielWeigl** [comment]
Also see this demo project, which explains it more in detail: https://gitlab.com/DanielWeigl/duplicatestrategyfailingdemo

**Comment by ljacomet** [comment]
@wolfs Can I get your opinion on this as you were the one implementing the changes around `DuplicateStrategy`?

**Comment by DanielWeigl** [comment]
Okay, maybe it is already fixed and it was a mistake on my side. First I built the JAR without `--warning-mode` and then never `clean`ed - thats the reason I never saw the warning in my test project.

See https://github.com/spring-projects/spring-boot/issues/20999#issuecomment-618351392

**Comment by wolfs** [comment]
@DanielWeigl The duplicates strategy should emit the warning for all copy spec which don't explicitly set a duplicates strategy. The `War` task doesn't set one, so it should detect the duplicates as well. And it seems like you were able to reproduce that it shows the warning.

I am closing this issue now, please re-open if there is anything else to do.
