### ISSUE TITLE
ZipCopyAction.CONSTANT_TIME_FOR_ZIP_ENTRIES is timezone specific

### ISSUE THREAD

**Issue by philwebb** [gradle/gradle#12895]
### Expected Behavior
When using a zip/war/jar action that has `preserveFileTimestamps=true` the entry time should be constant no matter what machine runs the build. 

### Current Behavior
The timestamp of the zip entries will be set to February 1st 1980 in the timezone of the machine that runs the build.

### Context
This issue was discovered whilst looking at a similar problem in Spring Boot.
https://github.com/spring-projects/spring-boot/issues/21005

The constant is defined in [ZipCopyAction](https://github.com/gradle/gradle/blob/26fdf17556532de2c59165a32d06951d24c08d6b/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipCopyAction.java#L57) and the comment states that "The date is 1980 February 1st CET", however, this is only the case for machines with a CET timezone.

I believe that using `OffsetDateTime.of(1980, 2, 1, 0, 0, 0, 0, ZoneOffset.UTC)` will fix the issue.

### Steps to Reproduce 
Build a zip or jar with `preserveFileTimestamps=true`. Change the machines timezone. Build the zip again and compare with `unzip -l`.

### Your Environment
MacOS and Java 8.

**Comment by big-guy** [comment]
@wolfs This sounds super familiar.  What's the value we expect here?

**Comment by wolfs** [comment]
See [this comment](https://github.com/spring-projects/spring-boot/issues/21005#issuecomment-615506181) from the issue you linked:

> When using GregorianCalendar the timestamps are consistent, but I can't yet explain the difference.

We also have tests which assert a fixed JAR file hash, and the test works on different operating systems and timezones. So I think the code works as expected now.

Am I missing something?

**Comment by vlsi** [comment]
The results of `new GregorianCalendar(1980, Calendar.FEBRUARY, 1, 0, 0, 0).getTimeInMillis()` is impacted by the default time zone, however, it is done so to compensate ``new Date(millis)` in {@link java.util.zip.ZipUtils}#javaToDosTime()`.

See: https://github.com/gradle/gradle/blob/26fdf17556532de2c59165a32d06951d24c08d6b/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipCopyAction.java#L52-L53

---

Just in case, the following prints

```
318211200000
318229200000
318207600000
```

in https://onecompiler.com/java/3vqywups4

```java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println(epoch());
        TimeZone.setDefault(TimeZone.getTimeZone("America/New_York"));
        System.out.println(epoch());
        TimeZone.setDefault(TimeZone.getTimeZone("Europe/Paris"));
        System.out.println(epoch());
    }
    
    private static long epoch() {
      return new GregorianCalendar(1980, Calendar.FEBRUARY, 1, 0, 0, 0).getTimeInMillis();
    }
}
```

**Comment by wolfs** [comment]
@vlsi Thank you, I should have read my own comment 🤦 

So if `preserveFileTimestamps=false`, then the zip produced is independent of the timezone as expected.

**Comment by philwebb** [comment]
Ahh thank you. I should have checked things more carefully. Sorry for the noise!
