### ISSUE TITLE
running a specific testcase in gradle 6.3 running all test cases in the project

### ISSUE THREAD

**Issue by Sandeepkaushik34** [gradle/gradle#12906]
Hi,

When our project was running in gradle 4.10,we wre running the specific test cases using below command that was working perfectly fine 
./gradlew  -Dtest.single=AdditionalVisaTests :test

Now we have moved to gradle version 6.3 and the command runs all the test cases and not the AdditionalVisaTests only.

I tried running other flavours below but no success:
```
./gradlew test --tests *AdditionalVisaTests
./gradlew test --tests="*AdditionalVisaTests*"
./gradlew test --tests=AdditionalVisaTests
./gradlew test --tests AdditionalVisaTests
```

Any help would be highly appreciated

**Comment by big-guy** [comment]
How are the test implemented in your project?  Are they JUnit, Spock, some other testing framework?

Do you have any custom runners?

**Comment by Sandeepkaushik34** [comment]
Junits

**Comment by Sandeepkaushik34** [comment]
> How are the test implemented in your project? Are they JUnit, Spock, some other testing framework?
> 
> Do you have any custom runners?

We have Junits,the problem is with running the Single Test class.
We have test suite as well  for which we have created a task in build.gradle so those work fine.

**Comment by big-guy** [comment]
Could you see if `--tests` shows the same behavior with 4.10?  

There's a slight difference in the way the two ways of selecting a test worked (`-Dtest.single` and `--tests`).   `-Dtest.single` matches on the _file name_ of the test class, while `--tests` matches at the class level through JUnit. 

Do you have a reproducible project that you could share?
