### ISSUE TITLE
Gradle 6.2: Implicit task dependencies not working

### ISSUE THREAD

**Issue by cckroets** [gradle/gradle#12907]
I have the following sample plugin that declares a producer task and a consumer task. Running the :produce task fails in 6.2 but succeeds in 6.1
```kotlin
abstract class SamplePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val producerTask = project.tasks.register("produce", ProducerTask::class.java) { task ->
            task.outputFile.set(project.buildDir.resolve("produced.txt"))
        }

        // Expect that when consume is executed, produce will also be executed
        // Works as expected in 6.1, breaks in 6.2.
        project.tasks.register("consume", ConsumerTask::class.java) { task ->
            task.inputFile.set(producerTask.flatMap { it.outputFile })
        }
    }
}

abstract class ProducerTask: DefaultTask() {

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun produce(): Unit = outputFile.get().asFile.writeText("src/main/resources/sample1.txt")
}

abstract class ConsumerTask: DefaultTask() {

    @get:InputFile
    abstract val inputFile: RegularFileProperty

    /**
     * Exception thrown here. Exploded is attempted to be read by gradle to figure out the task dependencies
     * before `inputFiles` is populated by :produce. So we get FileNotFoundException. This doesn't happen in 6.1
     */
    @get:InputFiles
    @get:SkipWhenEmpty
    val exploded: Provider<FileCollection> by lazy {
        inputFile.map { file ->
            project.layout.files(file.asFile.readLines().map { File(it) })
        }
    }

    @TaskAction
    fun consume(): Unit = project.logger.warn("Files: ${exploded.get().files}")
}
```

### Expected Behavior
For the task to succeed like it does in Gradle 6.1

### Current Behavior
Build fails due to:
```
Could not determine the dependencies of task ':consume'.
> java.io.FileNotFoundException: /.../GradlePropertyDemo/build/produced.txt (No such file or directory)
```

### Context
My plugin tries to run static analysis on a partial set of the project. The producer task will output a file that contains references to a bunch of files in the project. These are what need to be analyzed. 

So in the consumer task that performs the static analysis, there are two inputs. 
1. The aggregate file containing all references to all source files
2. The FileCollection of source files themselves.

Is there a better way to declare these inputs, than what I am doing? 

### Steps to Reproduce 
Demo project: https://github.com/cckroets/GradlePropertyDemo

### Your Environment
Build scan URL: https://scans.gradle.com/s/zpznwmopbxmhc

**Comment by big-guy** [comment]
I think the problem comes from the use of a `Provider<FileCollection>` -- this was never intended to work, so when it did, it was by accident.  A `FileCollection` is an older type (it predates `Provider`), but it's "Provider-like", so this looks like `Provider<Provider<...>>`, which doesn't make much sense.

I would do what you're doing slightly differently (modified from your reproducer):
```
import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.*
import java.io.File

abstract class SamplePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val producerTask = project.tasks.register("produce", ProducerTask::class.java) { task ->
            task.outputFile.set(project.layout.buildDirectory.file("produced.txt"))
        }

        project.tasks.register("consume", ConsumerTask::class.java) { task ->
            task.inputFiles.from(producerTask.map { 
                it.outputFile.get().asFile.readLines()
            })
        }
    }
}

abstract class ProducerTask: DefaultTask() {

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun produce(): Unit = outputFile.get().asFile.writeText("src/main/resources/sample1.txt")
}

abstract class ConsumerTask: DefaultTask() {

    @get:InputFiles
    @get:SkipWhenEmpty
    abstract val inputFiles: ConfigurableFileCollection

    @TaskAction
    fun consume(): Unit = project.logger.warn("Files: ${inputFiles.files}")
}
```

This removes the need for a `Provider<FileCollection>` by using `ConfigurableFileCollection`.  I also noticed that you were explicitly converting lines from the `produced.txt` file into `File` objects. This is a common gotcha that only really works when the paths are absolute paths. Creating a `File` with a relative path implicitly relies on the current working directory of the process and this isn't guaranteed to be the project directory.  With my changes, this instead relies on Gradle to convert from the relative path in a project directory relative way.

HTH

**Comment by cckroets** [comment]
Thanks for the help and detailed explanation, that works!
