### ISSUE TITLE
It is not possible to prevent the -h option to be passed to the Java compiler

### ISSUE THREAD

**Issue by clo-vis** [gradle/gradle#12904]
### Expected Behavior
The possibility to prevent the -h option to be passed to the Java compiler.

According to the documentation of the compile option _headerOutputDirectory_:

> If this option is set to a non-null directory, it will be passed to the Java compiler's `-h` option, prompting it to generate native headers to that directory.
Default with java plugin:
${project.buildDir}/generated/sources/headers/${sourceDirectorySet.name}/${sourceSet.name}

I think it's natural to expect that, if the option is set to null, then `-h` is **not** passed to the Java compiler, though strictly speaking I couldn't expect anything, as the documentation doesn't say what happens in this case. It is also not immediately clear that, even if you set the option explicitly to null, the default value will be used anyway.

### Current Behavior
`-h` is always passed to the java compiler even if headerOutputDirectory is set to null.

### Context
I use the Eclipse compiler, which doesn't support the `-h` option.

### Steps to Reproduce 
```
tasks.withType(JavaCompile) {
    options.headerOutputDirectory = null
}
```
Then check _build\tmp\compileJava\java-compiler-args.txt_. The `-h` option is still there.

**Comment by ljacomet** [comment]
It is possible to prevent it from being passed, but the method is not obvious.

The value has a `convention` tied to it, which needs to be cleared.

So you need to do 
```
tasks.withType(JavaCompile) {
    options.headerOutputDirectory.convention(null)
}
```

The team is fully aware that this is not ideal and we are looking into making this kind of situation much more obvious to deal with.

**Comment by bmuskalla** [comment]
@ljacomet I think this should be closed (it is possible) but instead have a proper issue tracking the general problem of discoverability of doing these things with the property API. WDYT?

**Comment by bmuskalla** [comment]
Closing this as dup of #14768

**Comment by ljacomet** [comment]
Effectively closing as duplicate
