### ISSUE TITLE
kotlin doesn't discover task in subproject, but groovy does

### ISSUE THREAD

**Issue by chb0github** [gradle/gradle#12937]
Given a sample of the groovy code below, it's Kotlin equivalent won't run due to compile error. 

### Expected Behavior
I simply expect that, when types as accounted for, a similar script should run. The net is filed with easy before-and-after examples. 

### Current Behavior
in `settings.gradle.kts`

```kotlin
    rootProject.name = File(".").canonicalFile.name
    File(".").let{
        start -> start.walkTopDown().filter { it.extension == "sln" }.map { it.path.split("/")[1] } }.forEach { include(it) 
    }
```

in `build.gradle.kts`

```kotlin
    subprojects {
        apply(plugin = "com.ullink.msbuild")
        apply(plugin = "com.ullink.nuget")
    
        tasks.register("hello") {
            doLast {
                println("I'm ${this.project.name}")
            }
        }
        msbuild {
            solutionFile = this.buildDir.walkTopDown().find { it.extension == "sln" }
            projectName = project.name
            verbosity = "normal"
            targets = listOf("Clean", "Rebuild")
            configuration = "Release"
        }
        tasks.findByName("msbuild")?.let{
            // this outputs
            it.javaClass.declaredMethods.map{ it.name }.forEach { println(it) }
        }
    }

```
```
Line 15:     msbuild {
               ^ Unresolved reference: msbuild

  Line 16:         solutionFile = this.buildDir.walkTopDown().find { it.extension == "sln" }
                   ^ Unresolved reference: solutionFile

  Line 17:         projectName = project.name
                   ^ Unresolved reference: projectName

  Line 18:         verbosity = "normal"
                   ^ Unresolved reference: verbosity

  Line 19:         targets = listOf("Clean", "Rebuild")
                   ^ Unresolved reference: targets

  Line 20:         configuration = "Release"
                   ^ Unresolved reference: configuration
```
In `build.gradle` groovy script:

```groovy
plugins {
  id "com.ullink.msbuild" version "3.8" apply(false)
  id "com.ullink.nuget" version "2.20" apply(false)
}

subprojects{
  apply plugin: 'com.ullink.msbuild'
  apply plugin: 'com.ullink.nuget'

  msbuild{
    solutionFile = {
      def result
      this.project.projectDir.traverse(type: groovy.io.FileType.FILES, nameFilter: ~/.*\.sln/) {result = it}
      result
    }()
    projectName = project.name
    verbosity = "normal"
    targets = ["Clean", "Rebuild"]
    configuration = "Release"
  }
}
```
with groovy `build.gradle`:
```
   $ gradle msbuild
    
    > Task :workflowadaptor-cwi_fl_lake_ui:msbuild
    Build started 4/27/2020 1:36:27 PM.
```

### Context
I am trying to autodiscover, configure, and build hundreds of msbuild projects

### Your Environment
$ gradle -version

------------------------------------------------------------
Gradle 6.1.1
------------------------------------------------------------

Build time:   2020-01-24 22:30:24 UTC
Revision:     a8c3750babb99d1894378073499d6716a1a1fa5d

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Mac OS X 10.13.6 x86_64

**Comment by ljacomet** [comment]
Hello,

Your expectations are not correct for the Kotlin DSL. Have a look at the [documentation on type safe accessors](https://docs.gradle.org/6.3/userguide/kotlin_dsl.html#type-safe-accessors) to understand better what is possible and how to handle other cases.

**Comment by chb0github** [comment]
I will try to digest it and see if I can figure out the right syntax for this. Thanks

**Comment by ljacomet** [comment]
Closing as this is not something to be fixed in Gradle.

Feel free to ask if you can't get to some of these accessors with the help of the documentation though.
