### ISSUE TITLE
Construct AbstractTask with a list of Action to execute

### ISSUE THREAD

**Issue by RoRoche** [gradle/gradle#12945]
I want to declare the `List<Action>` that my custom task has to execute.

### Context

I can't do this using the `@TaskAction`.

Doing so, `Action` can be reused and unit tested properly.

I would appreciate a sample code to do this.

Thanks.
Regards.

**Comment by big-guy** [comment]
Most tasks should only have one action.  If you wanted to have several separate actions that a task does, you could have a single method that calls each of the other actions.  Those actions could be separate Action classes or methods or however you saw fit to divide them.

You can also add multiple actions with `doFirst` and `doLast`, but this is usually only done to existing task types that you can't modify.
