### ISSUE TITLE
Injecting project properties with dots via environment variables

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1295]
Environment variables are often not settable if they contain dots.
In Bash e. g. you cannot do

    ORG_GRADLE_PROJECT_gradle.publish.key=bar sh -c 'env | grep key'

or

    export ORG_GRADLE_PROJECT_gradle.publish.key=bar && sh -c 'env | grep key'

Instead you have to do

    env 'ORG_GRADLE_PROJECT_gradle.publish.key=bar' sh -c 'env | grep key'

But if you e. g. use CircleCI, you cannot setup any system property with dots, the UI does not even allow it and if you try it via circle.yml, it displays as if it worked, but it did not work.

It would be nice if there will be some way to overcome this that is provided by Gradle.
e. g. `ORG_GRADLE_PROJECT_PROPERTIES='gradle.publish.key="bar" gradle.publish.secret="foo"'` or maybe `ORG_GRADLE_DOT_I_PROJECT_gradleIpublishIkey=bar` where you can define a replacement for the dot in the name of the env variable.

*Workaround:* Set some valid env variable and then set the correct project property from the env variable in your build script.

**Comment by bmuschko** [comment]
Would you mind raising an issue with CircleCI? The issue seems to be rather a limitation on their end.

**Comment by Vampire** [comment]
I of course also raised an issue with them, but CircleCI was just an example.
You also cannot set any environment variable with dots in your `.bashrc` file or on the commandline using `export` as described above.
It would be really nice if Gradle would provide some magic for this.

**Comment by oehme** [comment]
Instead of using project properties with dots, I'd recommend using camel case, which looks much more idiomatic in a Groovy/Kotlin environment. With that approach, no additional magic is required.

**Comment by Vampire** [comment]
@oehme the problem is, that you don't always have it under your control. And if you look again at my example, it is even your own code (Gradle Inc.'s) that requires an environment variable with dots. Actually for Java properties files it is quite common to have dots in the keys and rather alien to have camel-case.

**Comment by oehme** [comment]
Thanks for following up. I think a good approach would be to handle this as part of #2885. The proposal there is to model such options more strongly and this could include explicitly specifying the name of the environment variable. Then it could be different from the system property, e.g. using underscores instead of dots.

**Comment by Vampire** [comment]
Well, this is surely a good idea. But it only works for stuff that uses this facility. There could be other pieces of code that require dotted env variables and refuse to change. ;-)

**Comment by oehme** [comment]
Sure, but for those you already correctly identified the workaround. The whole environment variable mapping is just a convenience and I don't think it is worth the effort to make it more elaborate.

**Comment by Vampire** [comment]
Ok, that is a statement I can live with. :smiley:

**Comment by oehme** [comment]
Cool :) Just one more idea: You could encapsulate one of your proposed mapping schemes in a plugin that your projects can use. You'd apply that plugin as the first one in your project and it should work just like the built-in mapping.

**Comment by Vampire** [comment]
Yeah, that's the alternative for not copy & pasting the translator-code of course. Maybe I make a released plugin out of it then. :-) @oehme I think the problem with dots could / should be added to Gradle docs. Do you think at such a paragraph such a 3rd party plugin could berecommended as workaround, or is that a no-go in the Gradle docs?

**Comment by oehme** [comment]
I'm not sure what our approach is there, @eriwen probably has an opinion on this.

**Comment by eriwen** [comment]
I'm happy for the docs to link to external plugins. It is best to put suggestions like this in goal-oriented docs, for example, tutorials for setting up cloud CI. Such a thing doesn't exist in the official docs that I know of, but they _really_ should; the docs need some more love.
