### ISSUE TITLE
maven local repository

### ISSUE THREAD

**Issue by chenyu9390** [gradle/gradle#12959]
How to publish gradle project to maven local repository

**Comment by Vampire** [comment]
By applying and configuring the `maven-publish` plugin https://docs.gradle.org/current/userguide/publishing_maven.html
Then you can use `publishToMavenLocal` task.

**Comment by chenyu9390** [comment]
but error
Execution failed for task ':publishMavenJavaPublicationToMavenLocal'.
> Failed to publish publication 'mavenJava' to repository 'mavenLocal'
   > Artifact gradleTest-1.0-SNAPSHOT.jar wasn't produced by this build.

**Comment by melix** [comment]
This error message happens if you're trying to publish a stale jar file. It's likely you have configured your build in such a way that the jar file being published is not the standard Gradle jar file. A reproducer would help diagnosing more precisely.
