### ISSUE TITLE
Gradle image needs user root in pod

### ISSUE THREAD

**Issue by 2020testuser** [gradle/gradle#12953]
Hi,
Could you please let me know whether Gradle 4.6 image (from docker hub) need user -root to run  in Kubernetes pod? Below is the yaml file content sample.
`- name: app-build
      image: <my docker repo>/gradle:4.6
      imagePullPolicy: Always
      #securityContext:
       # runAsUser: 1000
        #runAsGroup: 1000 
      workingDir: /workspace/app
      script: |
          #!/bin/sh
           gradle wrapper -u '1000' --info --scan --gradle-version=4.6
           gradle wrapper -u '1000' --gradle-version=4.6 --distribution-type=bin
           gradle  build service:jib -u '1000' --no-build-cache --recompile-scripts -S -i --debug --scan  -x test \
           -Djib.to.auth.username='xxxx' \
           -Djib.to.auth.password=''xxxx' \
           -Djib.container.user='1000:1000' \
           -Djib.container.user='gradle:gradle' \
           -Djib.extraDirectories.paths = ['/workspace/app', '/workspace/app/service'] \
           -Djib.extraDirectories.permissions = ['/workspace/app': '775', '/workspace/app/service': '775'] \
           -Djib.to.image='<my docker repo/new image name>:latest'
      volumeMounts:
      - name: workspace
        mountPath: /workspace`

Gradle 4.6 image in Docker Hub need to run as user -root and fails for all other users when run in Kubernetes Pod.

### Expected Behavior
 Gradle 4.6 image must be able to run as user - gradle or user - 1000 when initiated in Kubernetes pod whose securitycontext is set to user - root and group as root.  

### Current Behavior
Gradle 4.6 image works only for user root in Kubernetes pod and fails for user 1000 and user - gradle in Kubernetes pod. 

### Context
 How has this issue affected you? What are you trying to accomplish? I'm trying to run gradle image from within Kubernetes Pod as non-root user.

### Steps to Reproduce 
sample code above

### Your Environment
Gradle 4.6 image pulled from Docker hub and pushed to company's Docker registry.
 The Gradle 4.6 image when run in Kubernetes Pod as user -root , the application build is successful. The Gradle 4.6 image when run in Kubernetes Pod asnon-root user , the application build fails.  
Exception Message is below.
`[service-build-step] 07:43:25.705 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().
[service-build-step] 07:43:25.705 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:857)
[service-build-step] 07:43:25.705 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:808)`

I tried passing -u - root, -u - gradle , changing the permission of the project directory and no luck.
Any info. to fix this issue would be greatly helpful.

Thanks in advance!

**Comment by melix** [comment]
The docker image is not maintained by Gradle, nor is it endorsed by Gradle. It only has the name "official" because that's how Docker calls such things. We recommend using the Gradle wrapper instead.

**Comment by 2020testuser** [comment]
Thanks!
Used gradle wrapper build command and got the same exception. Looks like this is a permission issue when gradle and Gradle are used inside the Kubernetes Pod. Please let me know if anyone got the image working in Kubernetes Pod. Thanks!

**Comment by bmuskalla** [comment]
As said above, the docker image is not maintained by us. If you can provide steps to reproduce, please let me know and we can reopen the issue.
