### ISSUE TITLE
JacocoMerge task as executionData for JacocoReport task

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#12962]
If you have a `task jacocoMerge(type: JacocoMerge)` task and then use
`executionData(jacocoMerge)` on a `JacocoReport` task, you get a `NullPointerException`:
```java
Caused by: java.lang.NullPointerException
        at com.google.common.collect.Iterables.any(Iterables.java:623)
        at org.gradle.testing.jacoco.tasks.JacocoReportBase$1.isSatisfiedBy(JacocoReportBase.java:62)
        at org.gradle.testing.jacoco.tasks.JacocoReportBase$1.isSatisfiedBy(JacocoReportBase.java:59)
        at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:47)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:42)
        ... 20 more
```

This is because only tasks with the `JacocoTaskExtension` are supported as `executionData`.
If only ineligible tasks are supplied, there should be meaningful error message during execution instead of a NullPointerException and a `JacocoMerge` task should probably also be supported as input.

**Comment by bmuskalla** [comment]
I very much agree that this behavior is confusing and should be fixed. Taking this further needs some consideration. Personally, I don't like that we just skip over non-compatible tasks right now but so far, that has been the contract. Failing if no tasks match while passing if at least one task matches might actually be even more confusing (depending on what you expect).

I think one way we should consider is breaking the contract and only accepting compatible tests. I fail to see a good reason to accept non-compatible tasks.

**Comment by Vampire** [comment]
What also be fine for me personally.
Besides that you said `tests` where I hope you meant `tasks` and `JacocoMerge` tasks will then also be supported. :-)

**Comment by bmuskalla** [comment]
@Vampire After checking back with the team, we might not be able to break the contract here without further ripple effects that we cannot do in a minor release. Nonetheless, I'm not having luck yet reproducing the NPE you describe. One thing is whether we accept `JacocoMerge` as input (new feature), the other is whether it fails with an NPE (bug). Would you be willing to share a small reproducer? 

This seems to work fine for me (skipping the report as it has no inputs). But the NPE indicates some other problem in your scenario.
```
plugins {
    id 'java'
    id 'jacoco'
}

task jacocoMerge(type: JacocoMerge)

task jacocoReport(type: JacocoReport) {
    executionData(tasks.jacocoMerge)
}
```

**Comment by Vampire** [comment]
Ah, iirc you must first empty the executionData or not apply the `java` plugin.
With the `java` plugin applied there is already an execution data file registered, so the NPE will not happen.

**Comment by Vampire** [comment]
If you still cannot reproduce, I'll knit a reproducer

**Comment by bmuskalla** [comment]
@Vampire Sorry, I didn't get around to look into this any further. Would you be able to share a reproducer?

**Comment by Vampire** [comment]
Ah, forget the NPE. I should probably have mentioned that this was on version 4.10.3. Getting the NPE requires that you either set `executionData = null` and this is deprecated in 5 and removed in 6 or do not apply the `java` plugin which caused the same problem as `null` was the default value.

With Gradle 5 the task changed to lazy configuration and so the default case vanished and with Gradle 6 the setter was removed, so the explicit caes vanished.

What is left is just supporting `JacocoMerge` tasks as `executionData`.
And actually supporting `TaskProvider` of supported tasks as `executionData`, but I'll report that as a separate issue.

**Comment by bmuskalla** [comment]
Taking a step back on this, what was the initial motivation to use the `JacocoMerge` task instead of passing the jacoco exececutionData directly to the `JacocoReport` task? Trying to gauge whether I missed a usecase before doing #12767

**Comment by Vampire** [comment]
I'm not sure anymore, I've rewritten the according code multiple times in the meantime and right now do not use `JacocoMerge` where I did.
I used it before giving it to TeamCity as there were some problems or quirks.
Maybe I then thought I also simply use the result for the report or something like that.

**Comment by bmuskalla** [comment]
With #12767 in flight, let's close this in favor of other approaches to combine the coverage data.

**Comment by Vampire** [comment]
What would be the other approaches? Except of making all consumers accept xml reports or multiple exec files?

**Comment by bmuskalla** [comment]
Do you have examples of consumers that can't handle this right now? Last time I tasked on the community slack, we concluded that there are no more users for that

**Comment by Vampire** [comment]
I don't know any personally, but that doesn't mean there are none.
I was just interested in what other approaches you see, your comment suggested there are others. :-)
