### ISSUE TITLE
Failing example in documentation about aggregating unit test reports

### ISSUE THREAD

**Issue by mattes3** [gradle/gradle#12961]
I have a project with subprojects and I want to generate an aggregated test report about the tests in all subprojects, both the succeeding and the failing tests. Using the instructions in the docs, the test report is not generated. Using the instructions from the Gradle forum in 2014, the test report *is* generated very well!

So, please update the docs.

### Expected Behavior

Test reports from subprojects should be incorporated in the main test report.

### Current Behavior

When I use these instructions here (from the official Gradle docs), the build **fails before the report is generated** because the TestReport task `dependsOn` Test:

#### Failing example
```groovy
subprojects {
    apply plugin: 'java'

    // Disable the test report for the individual test task
    test {
        reports.html.enabled = false
    }
}

task testReport(type: TestReport) {
    destinationDir = file("$buildDir/reports/allTests")
    // Include the results from the `test` task in all subprojects
    reportOn subprojects*.test
}
```

I found this at https://docs.gradle.org/current/userguide/java_testing.html#test_reporting

However, when I use code and explanation from an old entry in the Gradle forum from 2014, the report is generated very well:

#### Working example, instead:

```groovy
subprojects {
    apply plugin: 'java'

    // Disable the test report for the individual test task
    test {
        reports.html.enabled = false
    }
}

task testReport(type: TestReport) {
    destinationDir = file("$buildDir/reports/allTests")
    reportOn subprojects*.test.binResultsDir
}
subprojects {
    test.finalizedBy(testReport)
}
```

This works because it is not a `dependsOn` but a `finalizedBy` relationship.

I found this code (including a good explanation) at https://discuss.gradle.org/t/testreport-not-generated-if-one-of-executed-tests-fails/1770

### Steps to Reproduce 

1. Try `gradle testReport` in the first example and watch what happens when a test in a subproject fails (i.e. the directory `$buildDir/reports/allTests` is not created at all!)
1. Try `gradle test` in the second example and see that the directory is created and filled with a nice test report!

### Your Environment

Gradle 6.3
openjdk 14
Mac OS X 10.15.4

**Comment by arielcarrera** [comment]
I've a similar gradle build file configuration with something like your workaround:
`test.finalizedBy(testReport)`
but it doesn't work well for me, when you try to filter tests or run single tests from IntelliJ Idea, you ends up running the whole test suite.

**Comment by ajordanow** [comment]
The documentation has been updated, and TestReport samples are working now.
