### ISSUE TITLE
Resolve transitively applied plugins from an included build

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#12976]
Given a project structure:
```
├── build.gradle
├── settings.gradle
├── included-build
│   ├── build.gradle
│   ├── settings.gradle
│   └── src
│       └── main
│           └── groovy
│               └── included-build-plugin.gradle
└── shared-plugin
    ├── build.gradle
    ├── settings.gradle
    └── src
        └── main
            └── groovy
                └── shared-plugin.gradle
```
Where 
`settings.gradle`:
```
rootProject.name="root"
includeBuild("shared-plugin")
includeBuild("included-build")
```
`build.gradle`:
```
plugins {
    id "included-build-plugin"
}
```
`included-build/build.gradle`:
```
plugins {
    id "groovy-gradle-plugin"
    id "shared-plugin"
}
```
`included-build/src/main/groovy/included-build-plugin.gradle`:
```
plugins {
    id "shared-plugin"
}
```

### Expected Behavior
The transitively applied `shared-plugin` (via `included-build-plugin`) should be resolved and the build should succeed.

### Current Behavior
Build fails:
```
* What went wrong:
An exception occurred applying plugin request [id: 'included-build-plugin']
> Failed to apply plugin [id 'included-build-plugin']
   > Plugin with id 'shared-plugin' not found.
```

### Context
Currently the transitive plugin `shared-plugin` is not resolved when applied in the main project via `included-build-plugin`.
At the same time, it is resolved while building the `included-build` project itself as it is applied in that project's `build.gradle`.

A workaround is to add `id "shared-plugin" apply false` to the plugins block of the root `build.gradle`.

This issue demonstrates non-trivial behavior from `gradle/gradle` build if we were to compile the currently `shared-with-buildSrc` script plugins in their own project and have them applied in both to the build-logic (via an included build instead of buildSrc) and the main project.

**Comment by jjohannes** [comment]
@rieske Maybe I misunderstand the issue, but it seems to work here in this example: https://github.com/jjohannes/idiomatic-gradle/commit/ce88c7d15b7309584ba84097a691928671b3dcbb

Could you explain what is not working or provide a small reproducer for the problem?

**Comment by rieske** [comment]
Here's what I had in mind: https://github.com/rieske/test-shared-with-included-build
Perhaps I'm missing something, trying to get my head back around this now.

**Comment by jjohannes** [comment]
@rieske I think that is expected. and the sample misses a dependency.

Since `included-build` uses `shared-plugin` in the plugin it defines (`src/main/groovy/included-build-plugin.gradle`) it needs to declare a dependency to the project that contains that plugin. 

So you need to add this to `included-build/build.gradle`:
```
dependencies {
    implementation(":shared-plugin")
}
```

Then it works.

**Comment by rieske** [comment]
Makes sense now, thanks.
