### ISSUE TITLE
Cannot use nested "TaskCollection.configureEach {}" calls

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#12980]
Currently I cannot do this:

```groovy
tasks.matching { it.name == 'myTask1' }.configureEach { task1 ->
	tasks.matching { it.name == 'myTask2' }.configureEach { task2 ->
		task1.mustRunAfter task2
	}
}

task myTask1 {}
task myTask2 {}
```

Because I get the following error:

```none
> Could not create task ':myTask1'.
   > DefaultTaskCollection#configureEach(Action) on task set cannot be executed in the current context.
```

The following works, although the use of `afterEvaluate` is arguable, because usually it is viewed as a bad practice in a plugin code:

```groovy
project.with {
	afterEvaluate {
		tasks.named('myTask1').configure {
			mustRunAfter tasks.named('myTask2')
		}
	}
}
```

### Context

I need to write a plugin that adds extra behavior to existing tasks, mostly in the form of extra task dependencies added to them. However this logic only works correctly if I can define execution ordering between the already existing tasks.

Can you please provide an API that lets me do this? Or if there is already a solution that I have not stumbled upon, please let me know.

**Comment by big-guy** [comment]
This is intentional.  If you could nest these calls, then you could easily configure things in a way that would break when certain tasks aren't realized.

Take this example:
```
tasks.named("myTask1").configureEach { task1 ->
    tasks.with("myTask2").configureEach { task2 ->
        task2.someProp = "foobar"
        task1.dependsOn task2
    }
}
```
If we allowed nested configuration like this, then when I run `gradle myTask1`, `myTask2` won't run at all. If I run `gradle myTask1 myTask2`, then `myTask2` _will_ run in the correct order. Even worse, if I run `gradle myTask2`, `myTask2` won't be configured properly (someProp won't be "foobar").  This is because the configuration of these two tasks only happen properly when both of them are created.

Using `matching` like you are will defeat the purpose of using `configureEach` because all tasks need to be created in order to match against them, so if you can, stick to using `tasks.configureEach`, `tasks.named` and `tasks.withType().configureEach`.

I think what you'd like to do is just this:
```
tasks.named('myTask1').configure {
    mustRunAfter 'myTask2'
}
```

**Comment by rkrisztian** [comment]
Hi, @big-guy ,

Thank you for your answer. First I wanna say that my original example wanted to follow the configuration avoidance API completely, but I forgot to use `tasks.register`:

```
tasks.register('myTask1') {}
tasks.register('myTask2') {}
```

The problem with `tasks.named` is that it cannot wait until the task has actually been created. I mean I can do the following but it's quite verbose:

```groovy
tasks.withType(DefaultTask).configureEach { task1 ->
	if (task1.name == 'myTask1') {
		task1.mustRunAfter 'task2'
	}
}
```

(I don't know the task type in advance just its name.)

And if I look at [the documentation](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html), `matching` does not eagerly create tasks:

> Instead of: TaskCollection.matching(groovy.lang.Closure) | This is OK to use because it does not require tasks to be created immediately.
> -- | --
> Use: OK
 
Indeed if I run a build scan, it shows that only `:help` is realized. So something is really wrong here.

Also, neither that page, nor the API docs are really clear about passing string literals to `Task.dependsOn` is OK because it behaves lazily. I always thought I needed to pass `tasks.named(...)` to `dependsOn` as the only correct way.

So can we at least update the documentations then, please?

**Comment by big-guy** [comment]
> And if I look at the documentation, matching does not eagerly create tasks:

You're right here.  I had in my mind when I wrote that that this was trying to do something like `otherTask.dependsOn tasks.matching { ... }`.  Just configuring tasks with `matching` is OK. 

> Also, neither that page, nor the API docs are really clear about passing string literals to Task.dependsOn is OK because it behaves lazily. I always thought I needed to pass tasks.named(...) to dependsOn as the only correct way.

This is linked from the DSL reference and Javadoc for dependsOn, mustRunAfter and shouldRunAfter: 
https://docs.gradle.org/current/dsl/org.gradle.api.Task.html#N18C85
> You can use objects of any of the following types to specify dependencies and ordering:
> A String, CharSequence or groovy.lang.GString task path or name. A relative path is interpreted relative to the task's Project. This allows you to refer to tasks in other projects.

**Comment by rkrisztian** [comment]
Sorry, what I mean is, how does the quoted description above indicate that Strings passed to `dependsOn` are configuration avoidance compatible?

**Comment by rkrisztian** [comment]
Opened #13060 because I feel ignored. :(
