### ISSUE TITLE
Could not determine java version from '14'.

### ISSUE THREAD

**Issue by davvit** [gradle/gradle#12999]
### Expected Behavior

Should complete build
### Current Behavior

```
`Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:

Could not determine java version from '14'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

```

### Context

I am trying to build react native application

### Steps to Reproduce 

npx react-native run-android

### Your Environment

```
java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)

Gradle 6.3
```

**Comment by big-guy** [comment]
Could you try running `gradlew.bat -v` with a different JDK? I suspect you're not actually using Gradle 6.3

**Comment by davvit** [comment]
I found that there is wrapper in project level build.gradle thats looking at version 5.1.
Could this be the issue. I test with 6.3 and report.

task wrapper(type: Wrapper) {
    gradleVersion = '5.1'
    distributionUrl = distributionUrl.replace("bin", "all")
}

**Comment by big-guy** [comment]
Only Gradle 6.3+ supports Java 14, everything earlier would fail in the way you're seeing. 

I also think Gradle 5.0 made it an error to create a task named `wrapper` like you're showing, so you're likely using Gradle 4.x still.

**Comment by govinda-raj** [comment]
I added Java 14 in my classpath but removed it also because of some reason, I use Gradle 4.4. It throws the same error that @davvit has mentioned above. How could I resolve the issue?

**Comment by mothukuriv** [comment]
@govinda-raj 
Were you able to resolve this error ? I m facing similar issue.

**Comment by amin3141** [comment]
Also facing a similar issue here.

**Comment by behnambm** [comment]
I had the same issue.
I'm not java developer, I just needed to build a java app using `gradlew` 

I switched to `jdk8` and it worked.

First install the `jdk8` 
```
$ sudo apt install openjdk-8-jdk
```
Now see what versions of jdk you have installed using the following command
```
$ update-alternatives --config java
```

This will result in the following output(an interactive shell press ctrl+c) 
```
  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

```

Copy the path to `java-8` and set as `JAVA_HOME`

```
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64
```

Now run the command you want (for example `gradlew build`)
