### ISSUE TITLE
Incorrect maven-metadata.xml for SNAPSHOT versions

### ISSUE THREAD

**Issue by sbabych** [gradle/gradle#12993]
When I publish new SNAPSHOT version of my library, incorrect maven-metadata.xml file
is generated and uploaded to repository. I am using maven-publish plugin and upload my library to the GitHub Packages repository.

The problem is next:  
snapshot information in maven-metadata.xml file is not updated and always points to first snapshot, but new snapshotVersion is added to the list.
[maven-metadata.txt](https://github.com/gradle/gradle/files/4563607/maven-metadata.txt)
 
```xml
<snapshot>
    <timestamp>20200430.154204</timestamp>
    <buildNumber>1</buildNumber>
</snapshot>
```
As a result when I try to use this library as a dependency only first snapshot is always downloaded.

I did try with Gradle versions 6.3 and 6.2.2
Thank you.

**Comment by ljacomet** [comment]
This works everywhere else.

Could you provide a reproducer that shows what's uploaded is wrong?

**Comment by sbabych** [comment]
@ljacomet sure, 
[build.gradle.txt](https://github.com/gradle/gradle/files/4573916/build.gradle.txt)
[publish.debug.log](https://github.com/gradle/gradle/files/4573925/publish.debug.log)
generated [maven-metadata.xml.txt](https://github.com/gradle/gradle/files/4573928/maven-metadata.xml.txt)

**Comment by ljacomet** [comment]
Hey @sbabych ,

Thanks for the quick follow up and sorry for the terse message previously.

The `maven-medata.xml` you shared, is it the one coming from the server? Or the one coming from the build?
If the former, could you share the file `build/tmp/publishGprPublicationToGitHubPackagesRepository/snapshot-maven-metadata.xml`?
If I misidentified the task name, have a look for `build/tmp/**/snapshot-maven-metadata.xml`.

Also could you add a local publication repository to your project, to check if that is an artifact of your project or an interaction with the Github package registry.

By adding something like:
```
publishing {
    ...
    repositories {
       ...
       maven {
           name = "myRepo"
           url = uri("${buildDir}/repo")
        }
    }
}
```
and then running `./gradlew publishAllPublicationsToMyRepoRepository` a couple times, I am interested in the `maven-metadata.xml` from both `build/tmp/publishGprPublicationToMyRepoRepository` and `repo/<group>/<artifact>/<version>/maven-metadata.xml`

**Comment by sbabych** [comment]
Hi @ljacomet thank you for a quick reply.
The `maven-medata.xml` I had attached is from server (GitHub Packages).

from build/tmp/publishGprPublicationToGitHubPackagesRepository [snapshot-maven-metadata.xml.txt](https://github.com/gradle/gradle/files/4575089/snapshot-maven-metadata.xml.txt)

---
I did try to publish to local repo and this file looks different. So now `snapshot.timestamp` and `snapshot.buildnumber` looks good and points to latest snapshot build. but snapshotVersions contains only information about latest build (I guess this is ok) 

local repo [maven-metadata .xml.txt](https://github.com/gradle/gradle/files/4575070/maven-metadata.xml.txt)

from build/tmp/publishGprPublicationToMyRepoRepository  [snapshot-maven-metadata.xml.txt](https://github.com/gradle/gradle/files/4575078/snapshot-maven-metadata.xml.txt)

Thank you very much for your help. Do you think it's a problem on GitHub Packages side and they merge `maven-metadata.xml` incorrectly ?

**Comment by ljacomet** [comment]
Given the feedback, I would indeed think that the Github package registry is attempting to do something that does not work with this `maven-metadata.xml` file.

**Comment by sbabych** [comment]
@ljacomet  thank you very much for your help and time

**Comment by ljacomet** [comment]
Just got feedback from GitHub that this should be fixed on their side now.

@sbabych Any chance you can confirm this?

**Comment by jcansdale** [comment]
The strange thing is that Maven doesn't appear to be impacted by this, only Gradle seems to care. I wonder how Maven decides on its default SNAPSHOT version? 🤔

**Comment by sbabych** [comment]
Thank you very much, 

Absolutely yes, will check it today and write you back asap.

**Comment by sbabych** [comment]
I have verified and it works !!! 

Thank you very very much
