### ISSUE TITLE
Dependent classes not recompiled when Android resource is added on Gradle 6.3

### ISSUE THREAD

**Issue by Sipkab** [gradle/gradle#12995]
When a new Android resource is added, some Java classes may miss incremental recompilation.

If an Android resource ID is assigned to a constant field, and that field is referenced by other classes, then the dependent classes are not recompiled:

`MainActivity.java`

```java
public static final int MY_CONST = R.string.string_1;
```

`Dependent.java`
```java
    public static int get(){
        return MainActivity.MY_CONST;
    }
```

After adding a resources with the name `string_0`, the value of `string_1` is updated. However, the `get()` method above still returns the old value of `string_1`.

```xml
<string name="string_0">string 0</string>
```
### Expected Behavior
The `Dependent.java` should be recompiled.

### Current Behavior
It is not recompiled.

### Context

It results in incorrect incremental builds.

This was working in previous versions of gradle. I failed to reproduce on 5.4.1.

### Steps to Reproduce 
[GradleConstantBugExample.zip](https://github.com/gradle/gradle/files/4564222/GradleConstantBugExample.zip)

1. Download example project.
2. Run `gradle installDebug`
3. Check that the numbers on the screen are the same.
4. Uncomment `<!-- <string name="string_0">string 0</string> -->` from `strings.xml`
5. Run `gradle installDebug`
6. Check that the numbers on the screen are different. **They should be the same.**

You can also use `javap` or other mechanisms to verify that the compiled bytecode is correct, no need to actually run the app. See `MainActivity.java` on how the text is displayed.

### Your Environment

```
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_221 (Oracle Corporation 25.221-b11)
OS:           Windows 10 10.0 amd64
```

**Comment by oehme** [comment]
Can reproduce with 6.3, but not 6.8.3. This is already fixed.
