### ISSUE TITLE
[IDEA plugin] Allow configuration of issue navigation link

### ISSUE THREAD

**Issue by nicolaiparlog** [gradle/gradle#13004]
IntellIj allows the configuration of an issue navigation link, which enables it to link commit message texts like `#229` to, e.g., `https://github.com/junit-pioneer/junit-pioneer/issues/229`. It would be great if [Gradle's IDEA plugin](https://docs.gradle.org/current/userguide/idea_plugin.html) had a configuration option for that, so it can be configured in one place for everybody checking out that project.

### Expected Behavior

A [configuration option on `IdeaProject`](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaProject.html) called `issueNavigation` of a new type `IssueNavigation` that takes two strings `issueRegexp` and `linkRegexp`. They can be mapped 1:1 to the corresponding entries in `.idea/vcs.xml` (see below).

### Current Behavior

No such option exist.

### Context

Open source projects can make life of contributors easier by configuring this for the projects. At the moment, they can do that with a file `.idea/vcs.xml` with that configuration to their repo, e.g.:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="IssueNavigationConfiguration">
    <option name="links">
      <list>
        <IssueNavigationLink>
          <option name="issueRegexp" value="#(\d+)" />
          <option name="linkRegexp" value="https://github.com/junit-team/junit5/issues/$1" />
        </IssueNavigationLink>
      </list>
    </option>
  </component>
  <component name="VcsDirectoryMappings">
    <mapping directory="" vcs="Git" />
  </component>
</project>
```

(This example comes from junit-team/junit5#2241)

Adding IDE-specific configuration files to a project is fragile, though, and it appears that IDE-specific build tool plugins may be the better option.

(Btw, the same applies to the icon displayed in the toolbox (e.g. junit-team/junit5#2240). If it is decided that Gradle wants to tackle the navigation link, I will open another issue for the icon.)

**Comment by vlsi** [comment]
@nicolaiparlog , IDEA issue link has been discussed in https://github.com/gradle/gradle/pull/12755#issuecomment-619977099

The icon is already there: https://github.com/gradle/gradle/pull/12733

So I guess there's nothing to do here :)

**Comment by nicolaiparlog** [comment]
Hi @vlsi, I think you misunderstood the request. This is not about Gradle's issue navigation link and Gradle's icon. This is about every project out there that uses Gradle and wants to configure these things with the Gradle IDEA plugin.

Re #12755, this is exactly what we want to avoid as well - having to check in `.idea/vcs.xml` is fragile. Instead we hope that Gradle's IDEA plugin can write that file for us.

**Comment by vlsi** [comment]
@nicolaiparlog, the configuration you mention is neither Gradle specific, nor IDEA specific.
That is why there's no point in placing the configuration into gradle-idea plugin.

The configuration for "icon" and "issue URL" should be via editor config (editorconfig/editorconfig#425 editorconfig/editorconfig#426) or something like that. Then the configuration would work for multiple IDEs.

**Comment by nicolaiparlog** [comment]
I only really use IntelliJ for coding (and VS Code for private projects), so I don't know how prevalent the issue navigation link feature is and how uniformly it can be configured (is it always regex?). Same for the project icon - do other IDEs offer such a feature? That makes it tough for me to decide how much sense a global approach with editorconfig makes and I will trust your judgement on that.
