### ISSUE TITLE
validatePlugin gives in appropriate warnings

### ISSUE THREAD

**Issue by andifreed** [gradle/gradle#13019]
Given a task like:
```
public class TestTask  extends DefaultTask {
  @Optional @InputFile File configFile;
  @InputFile String source;  
  @OutputFile File target;
  @Override public String getDescription() { return "Task description"; }
  @Override public String getGroup() { return "Group X"; }
  @TaskAction void doit() { }
```

### Expected Behavior

I expected no warnings

### Current Behavior

```
Execution failed for task ':validatePlugins'.
> Plugin validation failed. See https://docs.gradle.org/6.3/userguide/more_about_tasks.html#sec:task_input_output_annotations for more information on how to annotate task properties.
   > Warning: Type 'TestTask': field 'configFile' without corresponding getter has been annotated with @Optional, @InputFile.
   > Warning: Type 'TestTask': field 'source' without corresponding getter has been annotated with @InputFile.
   > Warning: Type 'TestTask': field 'target' without corresponding getter has been annotated with @OutputFile.
   > Warning: Type 'TestTask': property 'description' is not annotated with an input or output annotation.
   > Warning: Type 'TestTask': property 'group' is not annotated with an input or output annotation.
```

### Context

it does recognize when a method is overriding a metadata property versus a consumer property.
It doesn't recognize when the property is accessible directly without a getter.

Finally it is objecting to the value is not a getter, when infact you should be objected that it's not on a setter.

### Steps to Reproduce 

create a build.gradle importing 'java-gradle-plugin'
add the task above

### Your Environment

any 6.x version of gradle

**Comment by big-guy** [comment]
These are all valid warnings. 

>  @Optional @InputFile File configFile;
>  @InputFile String source;  
>  @OutputFile File target;

These annotations are ignored in Java classes.  That's why it's complaining that there isn't a getter. The documentation linked to at the top of the error has more details about this.  If this was Groovy, this would be putting the annotations on the getter due to the way this is compiled by the Groovy compiler.

I wouldn't and you don't need to override `getGroup` or `getDescription`.  Just call `setGroup` and `setDescription`.

**Comment by andifreed** [comment]
Thanks.  My actual description logic used a different description for root project vs subproject, I was surprised that getProject actually returns a result in the constructor so I will move it to the constructor.  But  I can actually see wanting to use properties of the task, and that information isn't available in the constructor.

**Comment by big-guy** [comment]
If you can, move the configuration of tasks into the plugin vs doing it in the constructor. This makes the tasks more "dumb" and the plugin is the source of all configuration.
