### ISSUE TITLE
AntlrTask doesn't respect non-default source-directories

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#13016]
Using a custom source-directory for antlr grammar files doesn't work.

For example (Kotlin):
```
sourceSets {
    main {
        withConvention(AntlrSourceVirtualDirectory::class) {
            this.antlr.srcDir("src/antlr")
        }
    }
}
```

The above changes the `srcDir`, but the [`inputDirectories` evaluated in `AntlrExecuter`](https://github.com/gradle/gradle/blob/80d6c54e04db7cd486439ec1078e143dbdf3cb40/subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/internal/AntlrExecuter.java#L136) still evaluates the default `src/main/antlr`, which leads to wrong relative directories and in turn a failed build. I.e. `spec.getGrammarFiles()` uses the correct set of files (in `src/antlr`), but `spect.getInputDirectories()` always uses `src/main/antlr`.

TBH, the nested for-each-loops over the input-directories AND the _relative_ source-grammar files  is quite confusing.

**Comment by snazy** [comment]
Ouch - my fault.
`SourceDirectorySet.srcDir` *adds* a directory.

**Comment by snazy** [comment]
Well, sorry (not enough coffee yet). It is an issue - the initial comment's still valid.

**Comment by abextm** [comment]
This is still broken in 8.1
