### ISSUE TITLE
Provide an idiomatic manner by which to obtain NamedDomainObjectProviders for existing Objects from NamedDomainObjectContainers in the Kotlin DSL

### ISSUE THREAD

**Issue by RomanHargrave** [gradle/gradle#13021]
Presently, there exists no *idiomatic* way (that I have found) to obtain a `NamedDomainObjectProvider` for an extant object (i.e. task, sourceSet, etc...) using the delegates provided by the DSL. This requires the writing of explicit code to retrieve the the provider from the project.

### Example

Take for example the delegate `C.registering` (defined in [`NamedDomainObjectContainerExtensions.kt`](https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt#L53))

```kotlin
val myTask = tasks.registering(MyTaskType::class)

myTask.configure {
    foo("bar")
}
```
In the above sample, `myTask` is actually a `TaskProvider<MyTaskType!>` (which is a subclass of `NamedDomainObjectProvider`).
Because this is a `NamedDomainObjectProvider`, the `configure` function is available as a convenient means of interacting with the object within a dedicated scope.

If, however, the task `myTask` already exists, one might access the instance in the following fashion 

```kotlin
val myTask: MyTaskType by tasks
```

`myTask` will be an instance of `MyTaskType`, rather than an implementation `NamedDomainObjectProvider` (as is clearly indicated by the property type). 
As such, the following will fail to compile

```kotlin
myTask.configure {
   foo("baz")
}
```

Currently, the two "solutions" to this (not very critical) issue are to either obtain a `NamedDomainObjectProvider` by calling `named()` on the desired container (and casting the result to the applicable type, if need be) or by getting an unwrapped instance of the object and interacting with it sans-`configure`.

It would be nice to introduce an additional delegate, solely for the purpose of writing clean-er scripts.

### Context

I have an extremely complicated buildscript that depends on third party plugins. Some of these plugins define tasks that do some very undesirable and poorly thought out things by default - as such, I would like to adjust their settings to make the tasks more useful. ***This issue is not preventing me from doing this***; however, it would certainly be a pleasant improvement to have some sort of `withName` (or otherwise named) counterpart to `registering`.

**Comment by vlsi** [comment]
@RomanHargrave , have you tried `tasks.existing`?
See https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:configuring_tasks , example 10:

```kotlin
// Configure task using Kotlin delegated properties and a lambda
val myCopy by tasks.existing(Copy::class) {
    from("resources")
    into("target")
}
myCopy { include("**/*.txt", "**/*.xml", "**/*.properties") }
```

**Comment by RomanHargrave** [comment]
Odd - I'm not sure how I didn't run across that in the source code. I typically do not reference the gradle docs (as odd as that may sound) because they tend to cover only basic features.
