### ISSUE TITLE
Groovy Compile / Scala Compile - Order of error output can be wrong

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1303]
In very rare cases (under which conditions is not clear at the moment):

If groovy compilation is failing, the compiler error output is written to the error ouput stream *after* the build  fail exception (`CompilationFailedException: Compilation failed; see the compiler error output for details.`).

### Expected Behavior

Expected error output order:
1. Compile error. E.g. `unable to resolve class...`
2. `CompilationFailedException: Compilation failed; see the compiler error output for details.`

### Current Behavior
Most of the time the order is correct.
Seems to only happen under special conditions with `groovyOptions.fork = true` 
The complete message is still printed (only the order is wrong)

The situation was most likely improved already by this change: https://github.com/gradle/gradle/commit/ac2b1170119c0259f8e98c51ebc473b243176b51

**Comment by jjohannes** [comment]
Same issue can be observed with the ZincScalaCompiler.

Examples of the issue on CI:
- Groovy: https://builds.gradle.org/viewLog.html?buildId=2161892
- Scala: https://builds.gradle.org/viewLog.html?buildId=2542107

**Comment by eriwen** [comment]
Is this still an issue @jjohannes? I expect this is more related to `logging` than those specific plugins.

**Comment by jjohannes** [comment]
I think this is/can be both related to logging in general but also how the specific plugin print log messages.

However, this is only about the order of messages. It's debatable if this is a real issue in practice.

I don't think it's reasonable to invest more time into this at the moment. I am closing this issue. It can be re-opened if we encounter this as a real problem in practice.
