### ISSUE TITLE
Compiler arguments for modularity.inferModulePath = true are not enough for the Eclipse Java Compiler

### ISSUE THREAD

**Issue by clo-vis** [gradle/gradle#13041]
The compiler arguments generated when `modularity.inferModulePath = true` are ok for javac, but ecj (the Eclipse Java Compiler) still cannot compile the project.

### Expected Behavior
The compiler arguments should work with both javac and ejc.

### Current Behavior
foo/build.gradle:
```
plugins { id 'java-library' }
repositories { jcenter() }
plugins.withType(JavaPlugin).configureEach {
    java { modularity.inferModulePath = true }
}
tasks.withType(JavaCompile) {
    options.headerOutputDirectory.convention(null)
    options.generatedSourceOutputDirectory.convention(null)
}
```
foo/src/main/java/module-info.java:
```
module foo {  
    exports foo; 
}
```

foo/src/main/java/foo/Library.java:
```
package foo;
public class Library { }
```

The compiler arguments generated (which I see with `gradlew --debug`) are:
`-source 12 -target 12 -d A:\Workspace\foo\build\classes\java\main -g -sourcepath A:\Workspace\foo\src\main\java -proc:none -XDuseUnsharedTable=true A:\Workspace\foo\src\main\java\foo\Library.java A:\Workspace\foo\src\main\java\module-info.java`

`javac <compiler arguments>` works perfectly. But if you use these arguments with ejc:
`java -jar ecj-3.21.0.jar <compiler arguments>`
you will get:
```
1. ERROR in A:\Workspaces\java\foo\src\main\java\module-info.java (at line 2)
        exports foo;
                ^^^
The package foo does not exist or is empty
```

### Context
I need to use use the Eclipse Java Compiler `¯\_(ツ)_/¯` (among other reasons because javac aborts with an assertion error when compiling my project).

ecj can be downloaded from [https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.core/]()

**Comment by ljacomet** [comment]
Thanks for the report.

Any chance you know what's the command line that works for `ecj` in this case?

Could you also share how you get `ecj` wired in `JavaCompile`, or better a full reproducer.

**Comment by clo-vis** [comment]
That's the full build.gradle. 
```
plugins { id 'java-library' }
repositories { jcenter() }
configurations { ecj }
dependencies { ecj 'org.eclipse.jdt:ecj:3.21.0' }

plugins.withType(JavaPlugin).configureEach {
    java { modularity.inferModulePath = true }
}

tasks.withType(JavaCompile) {
    options.headerOutputDirectory.convention(null)
    options.fork(executable: 'java', jvmArgs: [ "-jar", configurations.ecj.files[0].toString() ])
}
```

**Comment by bmuskalla** [comment]
Here are the [supported arguments](https://help.eclipse.org/2020-03/topic/org.eclipse.jdt.doc.user/tasks/task-using_batch_compiler.htm?cp=1_3_8_0) for ECJ

**Comment by ljacomet** [comment]
@clo-vis Sorry to insist, but that would help this issue move forward:

> Any chance you know what's the command line that works for ecj in this case?

**Comment by clo-vis** [comment]
> Any chance you know what's the command line that works for ecj in this case?`
I have no idea.
