### ISSUE TITLE
unable to make up-to-date checks in my tasks

### ISSUE THREAD

**Issue by hichem-fazai** [gradle/gradle#13051]
### Context
I have two incremental tasks that wrtite to the same file. The first task depends on the second one. When I run gradle, the tasks are never up-to-date because the output file has changed.

### Current Behavior
Gradle rerun the task when output file has been modified or deleted.

### Expected Behavior
Is there any way to achieve up-to-date check in my case ? or maybe a way to configure my tasks to rerun only when output files are deleted (not modified)

**Comment by ljacomet** [comment]
Two tasks cannot have overlapping outputs, this breaks indeed up-to-date checks.

Your second task should move the file to a different location and then change it.

**Comment by hichem-fazai** [comment]
Thank you for your answer :) here the behaviour of gradle is perfectly correct. But I think that in some cases where tasks are collaborating on the same resources can't avoid having overlapping outputs.
