### ISSUE TITLE
Amend version sorting to resolve differences on well known qualifiers

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#13050]
From analysing differences between Gradle and Maven around sorting some popular version qualifiers, like `-SNAPSHOT`, `-GA` and `-SP`, the following changes would help users having to support both Gradle and Maven consumers of their libraries:
1. Make sure we resolve `SNAPSHOT` between `RC` and `RELEASE`, instead of before `RC` currently
2. Adding `GA` next right before `RELEASE`, instead of not special casing it now
3. Adding `SP` after `FINAL`, instead of not special casing it now

In terms of implementation, the changes would be first behind a feature flag, as Gradle should not change something like this in a minor, and possibly made the default with the next major version, based on user feedback.

Another set of changes would be around handling version ranges, so that issues like #1872 and #11145 can be mitigated.
The change to resolve that would be:

4. An excluded upper bound in a range, like `…, 2.0)`, would be interpreted as a smart prefix. It will reject any version starting with `2.0`.

**Comment by vlsi** [comment]
Just in case, here's a nice reference: https://octopus.com/blog/maven-versioning-explained#qualifiers-and-aliases

> Maven recognises a number of special qualifiers, shown here in order of precedence:
> * alpha or a
> * beta or b
> * milestone or m
> * rc or cr
> * snapshot
> * (the empty string) or ga or final
> * sp
>
> We saw in the list of sorted versions that these qualifiers do indeed result in Maven versions being sorted into the same order as the bullet point list.
>
> Versions with unrecognised qualifiers are treated as later releases than an unqualified version, and unrecognised qualifiers are compared as case insensitive strings.

**Comment by ljacomet** [comment]
Thanks, I was aware of this.

Due to the way Gradle sorts versions with qualifiers, `a`, `alpha`, `beta`, `b`, `milestone` or `m` do not need special treatment and will be sorted the same way in Maven and Gradle, _between each other_.

The main issue is when qualifiers unknown to Maven enter the picture: they get sorted _after_ the version without qualifier, while they get sorted _before_ in Gradle.

So Maven has:
`2.0-a1 < 2.0-beta < 2.0 == 2.0-final < 2.0-sp < 2.0-a < 2.0-dev` since `a` alone is not the same as `a1`, and `dev` is not special. As you can see, Maven puts non special qualifiers to be bigger than the unqualified version.

While Gradle has:
`2.0-dev < 2.0-a < 2.0-a1 < 2.0-beta < 2.0-sp < 2.0-final < 2.0` since only `dev` and `final` are special currently. As you can see Gradle puts non special qualifiers _and special ones_ to be smaller than the unqualified version.

With the suggested change, the list above would only move to become:
`2.0-dev < 2.0-a < 2.0-a1 < 2.0-beta < 2.0-final < 2.0-sp < 2.0`

This means of course that in order to be useful a qualifier like `sp` cannot be mixed with unqualified version. It has to be used when the release version was `ga`, `final` or `release`

**Comment by demonti** [comment]
Regarding the issue #13123 which you closed, correctly classifying and sorting alone may be a step towards it, but it does not solve my problem. I would like to define a range, say [1.2,2), and would like to exclude all non-production grade versions. For example, if a version 1.6 exists and the developers release a 1.6.1-beta, I do not want this version to be used, although it matches the range. If later the developers. When at a later point in time the finished version 1.6.1 (without any suffix or with a -final suffix) is released, the version should be found.

**Comment by ljacomet** [comment]
Right, I focused only on the range aspect, not the status. Let's continue the conversation over there.
