### ISSUE TITLE
Log how much of the VFS we need to drop due to symlinks

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#13052]
Once https://github.com/gradle/gradle/pull/13031 is merged we'll be dropping anything accessed via symlinks from the VFS at the end of the build. It would be good to understand the impact of this. Doing so would allow to better judge if this policy is enough to cover the important use cases or not.

It would be particularly interesting to learn how tools that rely heavily on symlinks like NPM and native compilers influence the VFS retention feature.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
We're not going to do this.
