### ISSUE TITLE
Test fixtures fails dependency resolution when constraint on api is applied

### ISSUE THREAD

**Issue by adrianskrobaczrevolut** [gradle/gradle#13067]
Given a very simple setup with constraint on the `api` configuration and dependency on `testFixturesImplementation` that transitively pulls the constrained dependency the build fails with `Could not resolve xxxx`.

### Expected Behavior

Build if successful

### Current Behavior

Following error is yield:
```
Execution failed for task ':compileTestFixturesJava'.
> Could not resolve all files for configuration ':testFixturesCompileClasspath'.
   > Could not resolve com.sun.mail:javax.mail:{strictly 1.5.2}.
     Required by:
         project :
      > Cannot find a version of 'com.sun.mail:javax.mail' that satisfies the version constraints:
           Dependency path ':test-sttrictly:unspecified' --> 'com.icegreen:greenmail:1.5.5' --> 'com.sun.mail:javax.mail:1.5.6'
           Constraint path ':test-sttrictly:unspecified' --> ':test-sttrictly:unspecified' --> 'com.sun.mail:javax.mail:{strictly 1.5.2}'
```

### Context

I'm trying to set up dependency constraint block in my root project, so the dependency versions are shared between `subprojects`.

### Steps to Reproduce 

Following simple `build.gradle.kts` file reproduces the error:
```
plugins {
    `java-library`
    `java-test-fixtures`
}

repositories {
    jcenter()
}

dependencies {
    constraints {
        api("com.sun.mail:javax.mail") {
            version {
                strictly("1.5.2")
            }
        }
    }
    implementation("com.sun.mail:javax.mail")

    testFixturesImplementation("com.icegreen:greenmail:1.5.5")
}
```
As a workaround I found out that adding the exact same constraint on the `testFixturesImplementation` as well makes the build succeed.

### Your Environment

Build scan URL: https://scans.gradle.com/s/xukcaobfhjw5m

**Comment by ljacomet** [comment]
There is no Gradle issue there. This is behaving as expected.

On one side you have a constraint stating that `com.sun.mail:javax.mail` is to be `1.5.2` _strictly_.
And then another transitive dependency says it needs `1.5.5`, which is incompatible.

So first of all, I would check whether that strictly is really needed. And if it is, it means you have to make a decision about the transitive version that attempts an upgrade.

Have a look at [the documentation](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html) for more information on this topic.

**Comment by adrianskrobaczrevolut** [comment]
Hey @ljacomet 
Thanks for the response 🙂I actually read this doc as well while struggling with this, but maybe I don't understand it well then 🤔What confuses me is that when we change the `testFixturesImplementation("com.icegreen:greenmail:1.5.5")` to `implementation("com.icegreen:greenmail:1.5.5")` it will resolve just fine(adding constraint on `javax.mail` to the `testFixturesImplementation` works as well as I mentioned in the original message). That would kind of make sense as per:
> For example, imagine that your project B strictly depends on C:1.0. Now, a consumer, A, depends on both B and C:1.1.
> 
> Then this would trigger a resolution error because A says it needs C:1.1 but B, within its subgraph, strictly needs 1.0. This means that if you choose a single version in a strict constraint, then the version can no longer be upgraded, unless the consumer also sets a strict version constraint on the same module.

but we already satisfy this part "unless the consumer also sets a strict version constraint on the same module." by adding the constraint on the `api` configuration. `testFixturesImplementation` clearly sees the constraint as well since the error message prints it out. What am I missing here 😕  ?

**Comment by ljacomet** [comment]
Ok, I think I understand where the confusion can be coming from.

When you set the constraint on `api` it appears at the root of the graph for `compileClasspath` and `runtimeClasspath`. Which is why when adding the dependency in `implementation` it works, the `strictly` overrides the transitive version.

However for `testFixturesCompileClasspath` the constraint appears because there is a dependency on the `apiElements` of the same project. The test fixture variant depends on the main variant.
Test fixtures do not use configuration inheritance, they use regular dependency and so the constraint is not at the root of the graph.
This is what the following expresses:
```
Constraint path ':test-sttrictly:unspecified' --> ':test-sttrictly:unspecified' --> 'com.sun.mail:javax.mail:{strictly 1.5.2}'
                 is testFixturesCompileClasspath   is apiElements
```
And because of that, the `strictly` does not override the other version, it conflicts with it as they are both down the graph.

So you need to either _repeat_ the constraint. One way to achieve it is to introduce a configuration that is then inherited by both `api` and `testFixturesApi`.
Or you can move the constraint to `testFixturesApi` instead if it is only applicable to test fixtures dependencies.

**Comment by adrianskrobaczrevolut** [comment]
Thank you! Great explanation that resolves all my doubts 🙂
Just one idea for improvement: would be great if Gradle could print in error message the configurations and potential resolution like:
```
Execution failed for task ':compileTestFixturesJava'.
> Could not resolve all files for configuration ':testFixturesCompileClasspath'.
   > Could not resolve com.sun.mail:javax.mail:{strictly 1.5.2}.
     Required by:
         project :
      > Cannot find a version of 'com.sun.mail:javax.mail' that satisfies the version constraints:
           Dependency path ':test-sttrictly:testFixturesCompileClasspath' --> 'com.icegreen:greenmail:1.5.5' --> 'com.sun.mail:javax.mail:1.5.6'
           Constraint path ':test-sttrictly:testFixturesCompileClasspath' --> ':test-sttrictly:apiElements' --> 'com.sun.mail:javax.mail:{strictly 1.5.2}'
        Potential resolutions:
           Specify the constraint on testFixturesImplementation configuration
```
> One way to achieve it is to introduce a configuration that is then inherited by both api and testFixturesApi

by the way that's actually exactly what I did 😉
