### ISSUE TITLE
Gradle should warn against using COD in combination with Kotlin DSL

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#13061]
### Current Behavior
#4823 describes the pitfalls of using COD with Kotlin DSL. The order of evaluation of projects in a multiproject build can get Gradle to a state where all builds fail with no clear reason. I'm not certain about the conditions that trigger this state or how to resolve it, but a combination of clearing caches or running clean builds doesn't cut it. The experience can be extremely frustrating for a user, since the error message doesn't provide any indication that COD is involved, or how to address.

### Expected Behavior
Ideally, COD should be fixed as described in the issue, since large builds see significant speedups in configuration time. Until then, Gradle should detect the combination of COD and Kotlin DSL and present a warning or just disable it proactively.

### Context
Last observed in v6.3.

https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:limitations

**Comment by quibi-jlk** [comment]
Big +1 to this. Figuring out that I needed to disable COD for our build was a big time sink for me and I believe it's affected our configuration speeds (which are quite bad with Kotlin DSL).

**Comment by Syex** [comment]
Still seeing it with Gradle 7 and have to agree, I wasted some time finding this mentioned issue.

**Comment by eskatos** [comment]
Implementation wise, adding behavior deprecation logging in `KotlinScriptPluginFactory` should be enough. We should make it an error in the next major after implementation.

**Comment by eskatos** [comment]
* https://github.com/gradle/gradle/issues/4823 is now closed

Dropping this
