### ISSUE TITLE
Regression in Gradle 6.4: New system property spurs a new daemon.

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/gradle#13069]
Using Gradle 6.3, we can launch gradle using
  1. first `./gradlew :help`
  2. second `./gradlew -Djava.net.preferIPv4Stack=true :help`

And the 2 invocations of gradle will reuse the same instance of Gradle daemon.

But in 6.4, the same operations spurs the creation of 2 different instances of daemons.

This has a direct impact on Android Studio that uses this flag. It means we cannot reuse the same instance of the daemon from CLI Gradle invocations and Android Studio syncs & builds.

**Comment by stephanenicolas** [comment]
This is linked to https://github.com/gradle/gradle/pull/12582

**Comment by big-guy** [comment]
@stephanenicolas could you give this nightly a try?  `./gradlew wrapper --gradle-version=6.4.1-20200514173331+0000`

**Comment by mlopatkin** [comment]
FWIW, Studio no longer does that according to https://issuetracker.google.com/issues/157254660
