### ISSUE TITLE
Java platform plugin constraints Leak

### ISSUE THREAD

**Issue by udayshnk** [gradle/gradle#13078]
Scenario:
Github Link for the project: [https://github.com/udayshnk/gradle-constraints-leak](https://github.com/udayshnk/gradle-constraints-leak)
Created a multi module gradle project with projects **projectA**, **projectB**, **projectX** and **projectY**.

**A** has a 'java-platform' plugin defining dependeny constraints as below
`javaPlatform {
    allowDependencies()
}
dependencies {
    api(platform("com.fasterxml.jackson:jackson-bom:2.9.8"))
    constraints {
        api("com.google.guava:guava:29.0-jre")
    }
}`

**X** is a 'java-library' project using the jackson databind constraint from A to resolve dependency version
`dependencies {
    implementation(platform(project(":projectA")))
    implementation("com.fasterxml.jackson.core:jackson-databind")
}`

**Y** is a 'war' project using the constraints from **A** to resolve dependencies as shown below
`dependencies {
    implementation(platform(project(":projectA")))
    implementation(project(":projectX"))
    implementation("com.google.guava:guava")
}`

**B** is another 'war' project just depending on **X** and also has a dependency on guava library as shown below
`dependencies {
    implementation(project(":projectX"))
    implementation("com.google.guava:guava:19.0")
}`

Below is the runtimeclasspath for **B**.

+--- project :projectX
|    +--- project :projectA
|    |    +--- com.fasterxml.jackson:jackson-bom:2.9.8
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.8 (c)
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0 (c)
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.8 (c)
|    |    \--- com.google.guava:guava:29.0-jre (c)
|    \--- com.fasterxml.jackson.core:jackson-databind -> 2.9.8
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
|         \--- com.fasterxml.jackson.core:jackson-core:2.9.8
\--- com.google.guava:guava:19.0 -> 29.0-jre
     +--- com.google.guava:failureaccess:1.0.1
     +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
     +--- com.google.code.findbugs:jsr305:3.0.2
     +--- org.checkerframework:checker-qual:2.11.1
     +--- com.google.errorprone:error_prone_annotations:2.3.4
     \--- com.google.j2objc:j2objc-annotations:1.3

As can be seen from the dependency graph there was a version conflict for guava dependency between 29.0-jre and 19.0 version declared in projects **A** and **B** respectively and gradle resolved to use 29.0-jre. 

**B** just depends on **X** which actually doesn't depend on guava jar at all, still the version of guava jar is overriden by depending on **X**.
We are using **A** as a parent project for **X** and **Y** which just defines constraints on common dependencies.
In large project even more constraints can be added into a project like **A** and there may be even more sub projects using its constraints and can potentially leak more constraints.
In maven dependencyManagement for a similar setup, dependencies versions are not leaked. 
I am not sure if its a bug in gradle or that's implemented in such a way intentionally.
If it's not a bug, can you please suggest any other approach to avoid leaking of constraints.

**Comment by ljacomet** [comment]
This is totally expected and is the way Gradle dependency management works. You can find more details [in the documentation](https://docs.gradle.org/6.3/userguide/dependency_resolution.html).

In short, Gradle will always account for all versions it sees in the graph. And anything that is declared in `implementation` is visible on the `runtimeClasspath` of consumers.
So your constraint for Guava `29.0-jre` is effectively transitive.

Have a look at [your options](https://docs.gradle.org/6.3/userguide/dependency_downgrade_and_exclude.html) for changing the Guava version in B.

**Comment by udayshnk** [comment]
Thanks for the **strict** version suggestion @ljacomet its working 

I have found another scenario where constraints leak is causing issue.
In the scenario explained in the main post, i have removed guava dependency from **B** and added a dependency on project **Z** which is depending on guava library as shown below

`
dependencies {
    implementation("com.google.guava:guava:19.0") {
        version {
            strictly("19.0")
        }
    }
}
`

Here is the updated **B** build script
`
dependencies {
    implementation(project(":projectX"))
    implementation(project(":projectZ"))
}
`
After these changes, build is failing with below reason
Execution failed for task ':projectB:war'.
> Could not resolve all files for configuration ':projectB:runtimeClasspath'.
   > Could not resolve com.google.guava:guava:{strictly 19.0}.
     Required by:
         project :projectB > project :projectZ
      > Cannot find a version of 'com.google.guava:guava' that satisfies the version constraints:
           Dependency path 'gradle-constraints-leak:projectB:unspecified' --> 'gradle-constraints-leak:projectZ:unspecified' --> 'com.google.guava:guava:{strictly 19.0}'
           Constraint path 'gradle-constraints-leak:projectB:unspecified' --> 'gradle-constraints-leak:projectX:unspecified' --> 'gradle-constraints-leak:projectA:unspecified' --> 'com.google.guava:guava:29.0-jre'

   > Could not resolve com.google.guava:guava:29.0-jre.
     Required by:
         project :projectB > project :projectX > project :projectA
      > Cannot find a version of 'com.google.guava:guava' that satisfies the version constraints:
           Dependency path 'gradle-constraints-leak:projectB:unspecified' --> 'gradle-constraints-leak:projectZ:unspecified' --> 'com.google.guava:guava:{strictly 19.0}'
           Constraint path 'gradle-constraints-leak:projectB:unspecified' --> 'gradle-constraints-leak:projectX:unspecified' --> 'gradle-constraints-leak:projectA:unspecified' --> 'com.google.guava:guava:29.0-jre'

If only the constraints of **A** which are applicable for **X** are applied when resolving **B** project, then conflict would have been avoided.

We have a project with 130 modules which is right now using maven, we are trying to move to gradle. It has multiple modules for each micro service and each of them has sub modules. So i am testing all scenarios to avoid dependency hell.

I feel the above use case is a common one in a multi project gradle build where multiple modules are present and each module have sub modules and there can be intra/inter module dependencies.

**Comment by ljacomet** [comment]
What you are hitting is a fundamental difference between Maven and Gradle.

And the "leak" you mention is actually a feature.

Someone designed project Z and decided, through testing for example, that it only works with Guava 19.

Then someone else uses project Z and project B in parallel. Gradle then tells you _at build time_ that there is a conflict between the Guava versions used by project Z and B.
Then as a developer, you are made aware of this, can investigate and decide which version _your project_ should use and express that choice.

Also, thanks to the "leak", the choice you made to fix using Z and B together will be known to _your users_.

**Comment by udayshnk** [comment]
I agree there should a version conflict if some other dependency/transitive dependency in B is using guava 29.0-jre.

Here B doesn't have any dependency on guava directly or indirectly other than from Z. Isn't it possible to give the preference to the version which Z needs.

I am not able to get rid of this build error whatever options i have tried on B

**Comment by ljacomet** [comment]
You can add a `strictly` constraint in B about `guava`. See https://docs.gradle.org/6.3/userguide/dependency_downgrade_and_exclude.html

Closing as there is nothing to change on the Gradle side.

**Comment by udayshnk** [comment]
Strictly constraint in B is working @ljacomet. Thanks for that.

In my honest opinion I think it would have been better if the dependency constraints were only applied on the direct project dependencies on which the constraints were added. Any other project which needs the same constraints will need to add it too. 

I am not sure in which scenario does the transitive propagation of constraints help, you guys might know it better as you know various use cases.

Sorry for troubling you since last week. I am really in awe with your product, I love the simplicity and overall performance it brings and it gives us a different perspective for building our build system.
