### ISSUE TITLE
Windows C++ projects that include system headers located in "winrt/" fail to compile.

### ISSUE THREAD

**Issue by alastairpatrick** [gradle/gradle#13074]
### Expected Behavior
"winrt/" directory should be added to include search path in the same way as other Windows SDK include paths.

### Current Behavior
Here is the layout of the include directories in the Windows 10 SDK:

```
C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/
  cppwinrt/
  shared/
  ucrt/
  um/       # Gradle already includes um/ in include search path
  winrt/    # but not winrt/
```

Gradle already automatically adds "um/" include directory to include search path but not "winrt/". See source of Gradle's WindowsKitWindowsSdkLocator.java.

A workaround is to add the absolute path "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt" to publicHeaders in build.gradle but this is brittle.

### Context
I'm trying to convert https://github.com/google/angle to use Gradle as its build system. That project includes the system header <wrl.h> which is in the "winrt/" include directory so compilation fails without the workaround mentioned above.

I'm evaluating build systems for a project that will utilize C, C++ and Java. As part of that, I also adapted the angle project linked above to use the MSBuild and CMake build systems and both automatically put the "winrt/" include directory in the search path and compiled without issue.

### Steps to Reproduce 

// src/main/foo.cpp
#include <windows.h>  // Succeeds because this part of Windows SDK is in search path
#include <wrl.h>           // Fails because winrt/ include directory is not in search path
<snip>

// build.gradle
plugins {
    id 'cpp-application'
}
<snip>

### Your Environment

Gradle Version: 6.0
Windows 10 64-bit
Windows 10 SDK versions 10.0.17763.0 and 10.0.18362.0 installed
Microsoft Visual Studio Community 2019 Version 16.5.4 installed
Eclipse IDE version: 2020-03 (4.15.0) installed
Running gradle via Eclipse integration

I have been using Gradle for 6 hours. Apologies if I have neglected useful information.

**Comment by lacasseio** [comment]
Thanks for trying out Gradle for building native. You are right there are some improvements that can be done around Windows development. To avoid back and forward on the issue, it would be great if you could join the [community Slack](https://gradl.es/slack-invite-2019) where we can chat more about what you are doing and see how I can help you move forward with your evaluation. There is a `#native` channel that we can use.

With regards to your specific issue, there are better solutions than adding an absolute path to the `winrt` directory. It's also worth discussing your specific use case and expectation as some project targets the Windows Runtime while others don't so there is a balance to strike for the default behaviour.

Finally, the issues for the core Gradle native support is mostly handled by [`gradle/gradle-native`](https://github.com/gradle/gradle-native). Looking forward to talking with you on the Slack channel.

**Comment by alastairpatrick** [comment]
Among the things we discussed on Slack was the default include search path used by Visual Studio for C++ projects. The screen shot shows those for a console application newly created using VS's new project wizard.

![image](https://user-images.githubusercontent.com/6560438/81587123-6f851d80-936b-11ea-9501-a15016280926.png)

Gradle already puts "um/" in the include search path but not "winrt/" and some of the other directories.

**Comment by swpalmer** [comment]
I am hitting this issue as well. For me the missing atlmfc/include folder is causing problems.  It is mentioned above that there are better solutions than adding the absolute path.  What are they?
