### ISSUE TITLE
Extract Ansi/console layer and release it as a reusable artifact

### ISSUE THREAD

**Issue by rmannibucau** [gradle/gradle#13082]
Hi everyone,

The layer built on top of Ansi class to provide a curses like feature is great and I think it can benefit the java community as a whole so it would be awesome if it can be extracted in a more granular artifact (almost no dependency except jansi) and released on one of the main maven repo.

Romain

**Comment by big-guy** [comment]
Thanks for the suggestion @rmannibucau - I don't think we're interested in doing this right now. Our console is pretty deeply tied to Gradle.
