### ISSUE TITLE
Calling hasTask from a BuildResult gives confusing behavior

### ISSUE THREAD

**Issue by DSteve595** [gradle/gradle#13093]
Gradle 6.4.

In `BuildListener::buildFinished`, calling `buildResult.gradle.taskGraph.hasTask(':mytask')` returns `false`, even when `:mytask` is run.

Calling `gradle.taskGraph.whenReady { it.hasTask(':mytask') }` returns `true`, which is what I expect.

Interestingly, in both of those `TaskExecutionGraph` instances, `allTask` does contain `:mytask`.

### Expected Behavior
I expect `hasTask` to return `true` for tasks that were executed in the build, regardless of how I retrieve the task graph.

### Current Behavior
`hasTask` returns `false` when called on the task graph returned by `buildResult.gradle.taskGraph`.

### Steps to Reproduce 
[Sample project](https://github.com/gradle/gradle/files/4612775/BuildListenerGraphBug.zip)

### Your Environment
Build scan URL: https://scans.gradle.com/s/uq37eswchggum

**Comment by big-guy** [comment]
I think this has been this way for a long time.  I think the task graph is intended to be used just before it's executed or while it's being executed.  The task graph gets cleared by the time buildFinished is called.

What would you like to do with this check? There might be another way to accomplish the same thing.

**Comment by DSteve595** [comment]
> What would you like to do with this check? There might be another way to accomplish the same thing.

I'm checking to see what tasks were executed in a build. There is indeed another way to accomplish that: the `whenReady` approach. That's why I called it "confusing behavior" and not necessarily a bug.

With `buildResult.gradle.taskGraph`, you have this situation:
- `allTasks` - Docs say "Returns the tasks which are included in the execution plan."
`allTasks` does contain `:mytask`.
- `hasTask` - Docs say "Determines whether the given task is included in the execution plan.".
But, `hasTask(':mytask')` returns false.

**Comment by big-guy** [comment]
We're not likely to do anything about this as we're trying to minimize the use of buildFinished for configuration caching.
