### ISSUE TITLE
java14 helpful NPEs not working in test

### ISSUE THREAD

**Issue by apflieger** [gradle/gradle#13096]
### Expected Behavior
I configure the test task to add the new jvm flag (java14) that enables helpful NPE messages 

*build.gradle.kts*
```kotlin
tasks.withType<Test> {
    jvmArgs("-XX:+ShowCodeDetailsInExceptionMessages") // Helpful NPEs not working :(
    testLogging {
        setExceptionFormat("full") // Prints exception messages
    }
}
```

With a test like that

```java
    @Test
    public void true_npe() {
        Object o = null;
        o.toString();
    }
```

I expect NPEs to have messages with details, something like this

```
TestNPE > true_npe FAILED
    java.lang.NullPointerException: Cannot invoke "Object.toString()" because "o" is null
        at TestNPE.true_npe(TestNPE.java:8)
```

### Current Behavior
It prints no message

```
TestNPE > true_npe FAILED
    java.lang.NullPointerException
        at TestNPE.true_npe(TestNPE.java:8)
```

### Context
For now, I guess only a few people uses this flag but as mentioned in the JEP https://openjdk.java.net/jeps/358, it will become the default behavior in a future version.
I posted it on stackoverflow https://stackoverflow.com/questions/61664979/how-to-enable-helpful-nullpointerexceptions-in-gradle-test/61737264#61737264 but I'm putting the same infos here

### Steps to Reproduce 
I created a simple project to reproduce it. https://github.com/apflieger/gradle-helpful-npe
Just `./gradlew test`
Make sure to have java14.

### Environment

```
java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

I retrieved the classpath gradle uses by running test with debug logs. With that, I could run JUnit directly. With `-XX:+ShowCodeDetailsInExceptionMessages` and the helpful NPE message shows up:

```
java -cp '/Users/apflieger/src/gradle-helpfull-npe/build/classes/java/test:/Users/apflieger/.gradle/caches/modules-2/files-2.1/junit/junit/4.13/e49ccba652b735c93bd6e6f59760d8254cf597dd/junit-4.13.jar:/Users/apflieger/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar' -XX:+ShowCodeDetailsInExceptionMessages org.junit.runner.JUnitCore TestNPE
JUnit version 4.13
.E.E
Time: 0.006
There were 2 failures:
1) throw_npe(TestNPE)
java.lang.NullPointerException: My own message
    at TestNPE.throw_npe(TestNPE.java:13)
2) true_npe(TestNPE)
java.lang.NullPointerException: Cannot invoke "Object.toString()" because "o" is null
    at TestNPE.true_npe(TestNPE.java:8)

FAILURES!!!
Tests run: 2,  Failures: 2
```

So it doesn't come from JUnit

**Comment by ljacomet** [comment]
I believe this is linked to the exception serialization between the Gradle worker and the daemon.
So it relates to #12302, #12764, #9487 and the internal `ExceptionPlaceholder` type.

**Comment by melix** [comment]
I just tested your reproducer with Gradle 6.4 and it worked: https://scans.gradle.com/s/fa5chfjb2dvhs/console-log?anchor=33

**Comment by apflieger** [comment]
Nah, it didn't. That's a `System.out.println` that appears in the log, not the exception message

**Comment by melix** [comment]
Oh right my bad I misread the results.

**Comment by melix** [comment]
@ljacomet it's not a `PlaceholderException` problem: what we see is a `NullPointerException`, and what we deserialize is a `NullPointerException`. Somehow it looks like the additional information that the NPE carries is lost during (de)serialization. At this stage I wonder if it's a bug in the JVM itself, or if there's something we need to implement to make this happen.

**Comment by cocorossello** [comment]
The additional information is not serialized, if you look at the sources:

`    public String getMessage() {
        String message = super.getMessage();
        if (message == null) {
            return getExtendedNPEMessage();
        }
        return message;
    }

    /**
     * Get an extended exception message. This returns a string describing
     * the location and cause of the exception. It returns null for
     * exceptions where this is not applicable.
     */
    private native String getExtendedNPEMessage();`

**Comment by melix** [comment]
Thanks I didn't have the sources under my eyes but debugging led me to the same conclusion: it seems the information used to get this information is in the backtrace which is transient. I guess we'll have to do something special for NPEs to support this use case.

**Comment by cocorossello** [comment]
This is my workaround if it can help (is a junit 5 extension, but something similar can work out in gradle)

```
public class HelpfulNullPointerExceptionExtension implements TestExecutionExceptionHandler {
    @Override
    public void handleTestExecutionException(ExtensionContext context, Throwable throwable) throws Throwable {
        Throwable actual = throwable;
        do {
            if (actual instanceof NullPointerException) {
                var field = Throwable.class.getDeclaredField("detailMessage");
                field.setAccessible(true);
                field.set(actual, actual.getMessage());
            }
            if (actual == actual.getCause()) {
                break;
            }
            actual = actual.getCause();
        } while (actual != null);
        throw throwable;
    }
}
```

**Comment by melix** [comment]
I took a similar approach in a PR, but as I expected, it's issuing warnings because of illegal reflection access on JDK classes...

**Comment by cocorossello** [comment]
I see, since you are using an ExceptionPlaceholder for each cause then just replacing the NPE with another one with the message should be enough, shouldn't it?

        if(isJava14() && throwable instanceof NullPointerException) {
            NullPointerException extendedMessage = new NullPointerException(throwable.getMessage());
            extendedMessage.setStackTrace(throwable.getStackTrace());
            throwable = extendedMessage;
        }

(I don't know how to test it in gradle, sorry)

**Comment by melix** [comment]
I actually didn't think about that simple solution, much easier than the one I'm trying, playing around with the serializer :D
