### ISSUE TITLE
Fail task of type Test immediately upon encountering first failure

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1310]
Original issue: https://issues.gradle.org/browse/GRADLE-1518

**Highly voted issue: 43!**

### Expected Behavior

Immediate feedback for long-running test suites. Expose a configuration option for the `Test` task type for failing upon encountering first failure. The test report indicates the failed test. Tests that have not been run are indicated explicitly.

### Current Behavior

Task does not fail immediately after a failure is detected. A user has to wait until whole test suite is exercised before task fails and report is generated.

### Context

We use the `Test` task for longer running integration and acceptance testing. In these cases I would like to fail the build fast (right after the first test failure is detected).

**Comment by bmuschko** [comment]
Potential approach from @adammurdoch to tackle the problem:

> regarding stopping tests on the first failure, instead of adding a special flag, I’d think about using the `—continue` flag
> i.e if you are not using `—continue`, we always stop on first failure, and if you are using it, we keep going

**Comment by eriwen** [comment]
Assigning to myself to discuss with Adam.

**Comment by emersonf** [comment]
Has this been deprioritized?

**Comment by eriwen** [comment]
@emersonf This is currently unscheduled until we can finish up the big things we're working on. Java 9 support (runtime and jigsaw), Kotlin build scripts, Composite builds, and then probably JUnit 5 support before this. 

Very happy for a community member to pick this up in the meantime.
