### ISSUE TITLE
gradle run -Dlogback.configurationFile=foo.xml --args='foo/bar'

### ISSUE THREAD

**Issue by adligo** [gradle/gradle#13103]
Java command line arguments should be passable to the java script that runs a java application somehow.

### Expected Behavior
I would be able to pass arguments to the execution of java that gradle creates with;
gradle run

### Current Behavior
If it's possible I couldn't figure it out

### Context
Well for log back I could stick it in the jar that I was creating, however for java memory options etc I don't see a way to do it.

**Comment by big-guy** [comment]
If this is something that always needs to be passed to the application, you can configure the run task:

```
run {
   systemProperty("logback.configurationFile", "foo.xml")
}
```

Otherwise, it's only possible to pass arguments to the application (with `--args`), not the JVM itself.
