### ISSUE TITLE
Dynamic dependencies: prevent use of pre-release versions

### ISSUE THREAD

**Issue by demonti** [gradle/gradle#13123]
Hi,
I am rather new to Gradle and to the Maven repositories (user Ant and local libraries before), so please be indulgent if I write nonsense or if there is already a solution for it.
I have the following problem: I would like to use the dynamic dependencies, e.g. ranges like [1.2,2), but this may cause that versions are picked up that are named as alpha, beta or a milestone release. It seems to me that I cannot prevent this. According to the documentation, these non-numeric labels are included into the version match and are then treated as subordinated versions of their prefix. One publisher even used the specific label ".Final" for their production-grade versions, but I did not manage to provide a suitable pattern (I tried something like "library:[1.2,2).Final", but it didn't work).
I found some tricks in the web which add some special code to filter the libraries, but this is quite library-specific and cumbersome. As the Maven repository turns out to be far more chaotic than I expected, I guess that there is no suitable meta information for the packages which reveal their development status, so the version string is the only means to take into account. I wonder whether Gradle could be extended to better deal with the situation. I am to unexperienced that I can formulate a concrete proposal, but I imagine an extended pattern for the version string and/or a global ignore pattern, e.g. that I can specify that all versions are ignored that end with .Alpha, .Beta or whatever.

**Comment by ljacomet** [comment]
The good news is that we aiming to fix this in an upcoming Gradle version by having the excluded upper bound of a range behave like a prefix exclusion. So doing something like `...,2)` will exclude all versions starting with `2` and larger than `2`.

Follow the evolution through #13050.

And closing this as duplicate for now.

**Comment by ljacomet** [comment]
Looks like I missed addressing the `status` part in your question. Have a look at #6023 which shows how you can combine a dynamic version with a status limitation.
That issue also indicates the support is not yet 100% complete, but can be working for the `release` use case.

However, by default Gradle interprets Maven dependencies as `release` unless they are a `-SNAPSHOT`, which are then `integration`.

So you would have to combine this with a component metadata rule to change the status of versions for specific patterns like `beta`, `rc`, etc ...

Have a look at [the following documentation](https://docs.gradle.org/6.4/userguide/component_metadata_rules.html#sec:custom_status_scheme) for details

**Comment by demonti** [comment]
This is what I called cumbersome ;-) But as said, I have no idea how to represent this nicely and briefly. So I accept that you close the issue, and if you or someone else would be somehow a little bit inspired by my statements, this would be sufficient for me.
