### ISSUE TITLE
JVM crash with file-system watching enabled on Windows

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13135]
`ArtifactTransformCachingIntegrationTest.cache cleanup does not delete entries that are currently being created` seems to crash in `file-events.dll`.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff90d7b3b69, pid=10600, tid=8716
#
# JRE version: OpenJDK Runtime Environment (14.0+36) (build 14+36-1461)
# Java VM: OpenJDK 64-Bit Server VM (14+36-1461, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [native-platform-file-events.dll+0x23b69]
```

See https://builds.gradle.org/viewLog.html?buildId=34884728&buildTypeId=Gradle_Check_VfsRetention_30_bucket6&fromExperimentalUI=true

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
[Crash log](https://github.com/gradle/gradle/files/4632969/hs_err_pid10600.log)

There doesn't seem to be a daemon log, maybe because the build was started with `--no-daemon`.

The re-run worked: https://e.grdev.net/s/fixi5bxoa5a3i/tests/:dependencyManagement:vfsRetentionIntegTest/org.gradle.integtests.resolve.transform.ArtifactTransformCachingIntegrationTest/cache%20cleanup%20does%20not%20delete%20entries%20that%20are%20currently%20being%20created#1

Since it was a no-daemon build and judging from the build log, the crash seems to happen in `startWatching`.

**Comment by wolfs** [comment]
Same [here](https://builds.gradle.org/buildConfiguration/Gradle_Check_VfsRetention_30_bucket5/34979894?buildTab=overview) and [here](https://builds.gradle.org/viewLog.html?buildId=34979897&buildTypeId=Gradle_Check_VfsRetention_30_bucket8&tab=buildResultsDiv&branch_Gradle_Check_VfsRetention_30=master).

**Comment by lptr** [comment]
Commit where things started to fail: 09185e8fc34ff9ff3b6792dacd60963fd9c78c64

**Comment by wolfs** [comment]
Some resources how to find out where the crash on Windows happens:
- [Crash course on JVM crash analysis Blog](https://community.oracle.com/blogs/kohsuke/2009/02/19/crash-course-jvm-crash-analysis)
- [llvm-pdbutil](https://llvm.org/docs/CommandGuide/llvm-pdbutil.html), you can download a binary from [here](https://github.com/shaharv/llvm-pdbutil-builds). This is for extracting information from `pdb` files.
- [dumpbin](https://docs.microsoft.com/de-de/cpp/build/reference/dumpbin-reference?view=vs-2019) Allows disassembling `dll` files and show their headers. Installed already on our CI machines as part of Visual Studio.

**Comment by lptr** [comment]
FTR, the PDB generated by @wolfs points to line 128 as the crash location, which probably means the line below:

https://github.com/gradle/native-platform/blob/16b2181e9fdf949385b3aa05ec983e4c263864d2/src/file-events/cpp/win_fsnotifier.cpp#L128-L132

**Comment by wolfs** [comment]
I managed to reproduce the crash on `master` (d91f4d034f911a4a6ad362b7c38aeb3b26f814c6) as well.

Let's see if I can reduce the number of tests we need to run.

**Comment by wolfs** [comment]
Usage of the tools above:
To show the headers with `dumpbin`, you can use
```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /headers ..\gradle\intTestHomeDir\worker-1\native\5fef6b658a83c5bcc1b3
72000e2bec0065fa8a789a588892999cc2c26706b2e4\windows-amd64\native-platform-file-events.dll
...
OPTIONAL HEADER VALUES
             20B magic # (PE32+)
           14.25 linker version
           13600 size of code
            F400 size of initialized data
               0 size of uninitialized data
            4D94 entry point (0000000180004D94)
            1000 base of code
       180000000 image base (0000000180000000 to 0000000180026FFF)
...
```

Then you can disassemble the `dll` by this:
```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /exports /disasm ..\gradle\intTestHomeDir\worker-1\native\5fef6b658a83c
5bcc1b372000e2bec0065fa8a789a588892999cc2c26706b2e4\windows-amd64\native-platform-file-events.dll > native-platform-file-events.asm
```

In that file, you can look up the address from the `hs_err` file:
```
0000000180023B57: E8 3F EE FD FF     call        000000018000299B
  0000000180023B5C: E9 36 01 00 00     jmp         0000000180023C97
  0000000180023B61: 48 8B 84 24 E0 00  mov         rax,qword ptr [rsp+00000000000000E0h]
                    00 00
  0000000180023B69: 83 78 68 01        cmp         dword ptr [rax+68h],1
  0000000180023B6D: 0F 84 CB 00 00 00  je          0000000180023C3E
  0000000180023B73: BA 02 00 00 00     mov         edx,2
  0000000180023B78: 48 8B 0D 29 64 15  mov         rcx,qword ptr [0000000180179FA8h]
```

Though that probably won't help you much to pin down the line in the code.

So, if you have the `pdb` file for the `dll`, you can use `llvm-pdbutil` to show the mapping from address to line:
```
llvm-pdbutil.exe pretty --lines build/libs/nativePlatformFileEvents/shared/windows_amd64/native-platform-file-events.pdb > native-platform-f
ile-events.lines
```

In the resulting file you can search for (part of) the address of the crash to find out the source code lines:
```
    <project-dir>\src\file-events\cpp\win_fsnotifier.cpp (MD5: 995F304E9F7C13F091B902D16166C592)
...
      Line 124, Address: [0x00023b4f - 0x00023b5b] (13 bytes)
      Line 125, Address: [0x00023b5c - 0x00023b60] (5 bytes)
      Line 128, Address: [0x00023b61 - 0x00023b72] (18 bytes)
      Line 129, Address: [0x00023b73 - 0x00023c3b] (201 bytes)
      Line 131, Address: [0x00023c3c - 0x00023c3d] (2 bytes)
      Line 133, Address: [0x00023c3e - 0x00023c4c] (15 bytes)
...
```

There you go: it is line 128.

**Comment by wolfs** [comment]
Looking at the [flaky tests for the last 24hs on `master`](https://e.grdev.net/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.names=coverageOs&search.relativeStartTime=P1D&search.tags=master&search.tasks=vfsRetentionTest&search.timeZoneId=Europe/Berlin&search.values=windows&tests.sortField=FAILED&tests.unstableOnly=true), I found more occurences of the JVM crash:
- https://e.grdev.net/s/c4hnyrfkd7ung
- https://e.grdev.net/s/7rv6o5dt4blf4
- https://e.grdev.net/s/i2b5ab2c7o7co
- https://e.grdev.net/s/npktpqbb6qy7e
- https://e.grdev.net/s/gtp3piq6l2lnq

The other flaky tests are also caused by JVM crashes in `native-platform-file-events.dll`, this time at `0x2143a`.

**Comment by lptr** [comment]
So `0x2143a` seems to map to here:

```text
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xlocale (MD5: 48B1BDF6F3916796193CD4CB8DDA87E7)
      Line 1084, Address: [0x0002140c - 0x00021431] (38 bytes)
      Line 1086, Address: [0x00021432 - 0x00021441] (16 bytes)
      Line 1087, Address: [0x00021442 - 0x00021446] (5 bytes)
```

```cpp
        while (_Mid1 != _Last1 && _Mid2 != _Last2) { // convert and put a wide char
            unsigned long _Ch;
/* --> */   const unsigned short _Ch1 = static_cast<unsigned short>(*_Mid1);
            bool _Save                = false;
```

I guess it's the de-referencing of `_Mid1`, i.e. we are trying to convert a wide string from an invalid memory location. That makes sense, and points to an invalid `path` being converted again.

**Comment by wolfs** [comment]
Sometimes it seems that cancelling a watch point fails with `device or resource busy` (see for example [here](https://e.grdev.net/s/vxjc7k2vat7t6/tests/:compositeBuilds:vfsRetentionIntegTest/org.gradle.integtests.composite.SamplesCompositeBuildIntegrationTest/can%20run%20app%20when%20modified%20to%20be%20a%20composite%20with%20kotlin%20dsl#1)). I only recall seeing this problem when not using isolated daemons, see #12604.

**Comment by wolfs** [comment]
Looks like `DependencyVerificationIntegrityCheckIntegTest` is now so flaky that the build fails consistently on `master`: https://e.grdev.net/s/buk5vdoiy3xqs/tests/flaky

**Comment by wolfs** [comment]
I ignored the test on `master` for now: https://github.com/gradle/gradle/commit/6995019fe261034f50cb0518f6dd9f2676c7245b
