### ISSUE TITLE
Investigate why fileHashes.lock sometimes stays locked on Windows

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1313]
`fileHashes.lock` is sometimes still locked after a build finished.
Occurrence on CI:
- https://builds.gradle.org/viewLog.html?buildId=2165815
- https://builds.gradle.org/viewLog.html?buildId=2210377

Possible related commit: 
https://github.com/gradle/gradle/commit/b0c142972089b382b22f99ef452c742d35df5603

### Expected Behavior
- It should always be possible to delete/modify `fileHashes.lock` after a build finished

### Current Behavior
- `fileHashes.lock` sometimes stays locked on Windows

Once this is fixed, remove `@LeaksFileHandle` / `@Ignore` from 

- [x] `checkDefaultGradleUserHome`- https://github.com/gradle/gradle/blob/e80e77278a02a9b8d38d3bdfe8e9026461f09a82/subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CommandLineIntegrationTest.groovy#L132-L132 (fixed by https://github.com/gradle/gradle/pull/1326)
- [x] `systemPropGradleUserHomeHasPrecedenceOverEnvVariable` - https://github.com/gradle/gradle/blob/e80e77278a02a9b8d38d3bdfe8e9026461f09a82/subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/CommandLineIntegrationTest.groovy#L195-L195 (fixed by https://github.com/gradle/gradle/pull/1326)
- [ ] `generates events for downloading artifacts` - https://github.com/gradle/gradle/blob/5116753a4279a5b76a17ea8e4681838ac63ef9b4/subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/r35/BuildProgressCrossVersionSpec.groovy#L95-L95

**Comment by adammurdoch** [comment]
This is intended behaviour. A process will keep this cache open until some other process requires the lock.

If these tests are failing because they happen to be using a test specific Gradle user home that they later delete, they should inform the test fixtures about this, which can in turn tell `DefaultGradleUserHomeScopeServiceRegistry` to eagerly close the cache.

**Comment by adammurdoch** [comment]
I should clarify: "intended behaviour" doesn't necessarily mean "good behaviour". We might rethink how this works, or not.

**Comment by breskeby** [comment]
I've tried to get rid of the @LeakFileHandle annotation here for another tapi test but without anyluck. I've tried manually passing the system property `org.gradle.internal.reuse.user.home.services` to the build manually but that didn't solve the problem. My latest try is here reusing `requireIsolatedToolingApi`: https://builds.gradle.org/viewLog.html?buildId=2328588&tab=buildResultsDiv&buildTypeId=Gradle_Branches_CommitPhase_WindowsCommit_WindowsCommitJava17_2WindowsCommitJava

**Comment by bmuschko** [comment]
@jjohannes Can you help out @breskeby so we can get this issue into the done state?

**Comment by jjohannes** [comment]
What @adammurdoch described earlier goes into the right direction I think. This is an issue with the tooling API test fixtures when running isolated daemons. In that case, we force kill the daemon at the end of the test (or do not stop it at all). Still we attempt to delete the daemon base dir, as it is inside the test folder. This leads to situations where the daemon might still hold file handles (or the handles did not get released yet because of the force kill).
I think the solution here, and probably to other file handle leaking tooling API tests, is to improve the test fixtures `ToolingApi` and `ToolingApiSpecification` in a way that they properly stop the isolated daemon and wait for it to be stopped during cleanup. **Before** the test directory is cleaned.
_Note that there are several flags and fields in `ToolingApi` which influence whether a separte daemon base dir is used or not. This could use some simplification as well._

I am opening a separate issue for this on our CI health board and closing this one. I am also removing the `bug` tag, as this was only about test fixture issue.

**Comment by eric-isakson** [comment]
Ran into this one...is there a link you can provide to the bug you mentioned opening on the CI health board. Any workaround or resolution other than reboot my machine so I can release this lock?

**Comment by big-guy** [comment]
This is referring to Gradle's test infrastructure, not Gradle in general.

If you're running into this, you can try stopping daemons (`gradle --stop`).

**Comment by eric-isakson** [comment]
Yes, I'm aware. I'm doing plugin developement testing for plugins used at my company. I execute tests using the Gradle Runner on Gradle versions from 2.6 - 3.5. I'm invoking the Gradle Runner with arguments that isolate the test into a temporary directory under my buildDir, something like build/acceptance-tests/...

Everything is fine when the tests are passing, but I just started adding 3.5 testing and have some test failures. Now, the fileHashes.lock is locked by the System process and then I start getting failures when I run the 'clean' task because it cannot delete the temporary directories used by my tests under the buildDir.

It sounds like this problem but perhaps I'm seeing a different similar bug?

**Comment by jjohannes** [comment]
@eric-isakson This sounds like a similar, but different issue to me. Maybe the GradleRunner is starting a daemon process and does not shut it down in case of failure in your case.
If this is still an issue for you, could you create a separate bug issue with an example that allows us to reproduce the problem? Thanks!

**Comment by diegoflores** [comment]
According to Microsoft documentation you should the gradle daemon
`
   # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
    ./gradlew --stop  
`
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
