### ISSUE TITLE
API to delete a build scan

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#13133]
We'd like to use build scans more in our CI flows, but are concerned about them being publicly available if links are discovered. It would be ideal if we could save the created scans and then delete them on some scheduled cadence. Could Gradle add an API for this?

**Comment by rhart** [comment]
Hi @ZacSweers,

It is already possible to delete build scans on scans.gradle.com via the UI, I'm afraid we don't have any current plans to make an API for this.  Perhaps not ideal, but it would be possible to create some automation around this using Selenium or similar.

Alternatively, [Gradle Enterprise](https://gradle.com/) addresses these kind of data privacy concerns by being installed on-premises.  There are also other features you don't get with scans.gradle.com such as aggregate views, build scan comparisons, flaky test insights, and distributed testing to name just a few.  I only mention in case you were not aware of this, you can request a free trial here if it's of interest https://gradle.com/enterprise/trial/

**Comment by ZacSweers** [comment]
We would be happy to go to Gradle Enterprise, but it still does not support the type of authentication we need to use on premise. CC @Rooz-sf
