### ISSUE TITLE
version range difference between 1.1+ and 1.1.1+

### ISSUE THREAD

**Issue by gspeiliu** [gradle/gradle#13149]
Hi, 
I am confusing about the definition of the prefix version range.
The doc site: https://docs.gradle.org/current/userguide/single_versions.html wrote:
A prefix version range: e.g. 1.+, 1.3.+
             Only versions exactly matching the portion before the + are included.
             The range + on it’s own will include any version.
However, the android site: https://developer.android.com/studio/releases/gradle-plugin wrote the range in the format 1.1+.

Could you please shed some light on me the difference between the definition format 1.1+, 1.+ and 1.1.1+? Thanks.
1.1+ get the latest version lower than 1.2 or 2.0? 
1.+ get the latest version lower than 2.0?
1.1.1+ get the latest version lower than 1.1.2?

**Comment by ljacomet** [comment]
It simply means that what's on the left of the `+` must match in the target version.
So in short, for a version to be considered, if you have `<prefix>+`, then the target version <version> should return true for `<version>.startsWith(<prefix>)` and after that, version sorting will determine the highest matching.

**Comment by jjohannes** [comment]
Closing as there is no action. See explanation above.
