### ISSUE TITLE
IDEA-Plugin: adding exclude using regex

### ISSUE THREAD

**Issue by igreenfield** [gradle/gradle#13169]
In module configuration there is:
![image](https://user-images.githubusercontent.com/5586356/82318514-aba62700-99d8-11ea-9ff1-78fc6e3fc860.png)

it will be great if it can be configured from the plugin.

**Comment by bmuskalla** [comment]
Thanks for reporting. The Intellij integration is built by jetbrains: https://youtrack.jetbrains.com/
