### ISSUE TITLE
jacocoTestReport task is stuck on connectedDebugAndroidTest

### ISSUE THREAD

**Issue by bushmen** [gradle/gradle#13168]
In our project recently we have bumped gradle 3.4.0 to 3.6.2 and we have noticed issues with jacocoTestReport task to hang on many occasions when trying to perform connectedDebugAndroidTest. We run the task by invoking: 
`./gradlew --parallel clean jacocoTestReport`

Here is our buildscan: https://scans.gradle.com/s/ezmeqnapdsmow

Do you know what can be the reason or how to get more information other than just gradle being stuck indefinitely?

**Comment by ljacomet** [comment]
Without a reproducer, it is hard to say if this is an issue in the Android plugin or in Gradle itself.

Please provide one otherwise this issue will not be looked at.
