### ISSUE TITLE
File-based task inputs and outputs should behave like annotation counterparts

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1316]
Original issue: https://issues.gradle.org/browse/GRADLE-2638

### Expected Behavior

Task inputs and outputs declared through the API should validate the assigned values and create necessary, non-existent directories. Properly document the behavior in the user guide and Javadocs.

### Current Behavior

Task inputs and outputs declared through the API do not validate the assigned values, nor and create necessary, non-existent directories.

### Context

The runtime behavior for task inputs/outputs should be consistent across the ways they can be declared. There's absolutely no compelling reason for not doing so and leads to confusion for end users.

### Steps to Reproduce (for bugs)

**Usage of annotations:**

```
// Fails the build by saying that input file does not exist
task validatesInput(type: MyTask) {
    inputFile = file('does-not-exist.txt')
}

// Automatically creates directory "some/dir"
task createsOutputDir(type: MyTask) {
    inputFile = file('does-exist.txt')
    outputFile = file('some/dir/output.txt')
}

class MyTask extends DefaultTask {
    @InputFile
    File inputFile

    @OutputFile
    File outputFile

    @TaskAction
    void doSomething { ... }
}
```

**Usage of API:**

```
// No validation
task noValidationInput {
    inputs.file('inputFile',  file('does-not-exist.txt'))
}

// No automatic creation of output directory "some/dir"
task noCreationOutputDir {
    inputs.file('inputFile',  file('does-exist.txt'))
    outputs.file('outputFile', file('some/dir/output.txt'))
}
```

**Comment by eriwen** [comment]
We highly encourage development of [custom tasks](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks) for performance and safety. 

 It doesn't seem like we have a great need for this right now, so I'm putting this in the Icebox until we have some.
