### ISSUE TITLE
Could not find method compile() / Could not find method implementation() ...

### ISSUE THREAD

**Issue by martijintro** [gradle/gradle#13173]
### Expected Behavior
No error message like that, should end successfully after clicking "Sync Now"-Button in Android Studio 

### Current Behavior
Get the messages written in the issue's title...

### Context
1. File `PROJECT_FOLDER\app\build.gradle` is configured as follows:
`
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        implementation fileTree(dir: 'libs', include: ['AndroidCompatibleHTTPClient.jar'])
        // compile fileTree(dir: 'libs', include: ['*.jar'])
    }
}
`

2. A file called `AndroidCompatibleHTTPClient.jar` exists in `PROJECT_FOLDER\app\libs` !!

3. Same problem with `compile ... ` (deprecated) and `implementation ... `

4. Some problem with `(dir: 'libs', include: ['AndroidCompatibleHTTPClient.jar'])` and `(dir: 'libs', include: ['*.jar'])`

### Steps to Reproduce 
I can send you the project as a zipped archive. (Because it's not for public) Don't hesitate to ask me. Then you can give me your mail address and i will send it to you!

### Your Environment
Android Studio with all most current components, updated today.
Build scan URL:

What is the `Build scan URL` ??

Thank you very much! :-)

With best regards,
Jan

**Comment by jjohannes** [comment]
As it says in the comment `// NOTE: Do not place your application dependencies here`.

You should do that in the `app/build.gradle` script where the plugin is applied.

There should be something like this in that script:
```
plugins {
    id('com.android.application')
}
```

Without the plugin, `implementation` and `compile` is not available and that's why you get the error.

**Comment by jmar83** [comment]
yes not it works

**Comment by jmar83** [comment]
"not" -> "now" ;-)

**Comment by martijintro** [comment]
...so you can close my issue now. Thanks.

Best regards, Jan
