### ISSUE TITLE
Wrong order in Single-Page HTML User Guide

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1317]
Since Gradle 2.0, in the Single-Page HTML User Guide, the whole `Part I` is rendered in the end, right before the Appendix starts and not even this, within `Part I` first `Chapter 2` is present and only thereafter `Chapter 1`.

**Comment by Vampire** [comment]
Hm, but only in the online versions at https://docs.gradle.org/3.4-rc-1/userguide/userguide_single.html and so on. If I generate the Userguide from source, it looks correct.

**Comment by bmuschko** [comment]
Would you be interested in fixing the issue?

**Comment by Vampire** [comment]
How should I? As noted, this is only happening in the online version, not in locally generated one. So it probably happens somewhere in your deployment process or something like that.I guess I'd need access to your servers to investigate this and I doubt you will provide this unless I'm hired by Gradle Inc. :-D

**Comment by bmuschko** [comment]
Fair enough. I guess we'll have to have a look ourselves. Thanks for reporting back.

**Comment by Vampire** [comment]
This indeed is fixed since 3.5.1
