### ISSUE TITLE
GraalVM Native Image support

### ISSUE THREAD

**Issue by wlsc** [gradle/gradle#13181]
Provide a **GraalVM Native Image** support feature that creates native executable. 
More information here https://www.graalvm.org/docs/reference-manual/native-image/

### Expected Behavior
User should be able to select if he wants to produce a jar or a native image of GraalVM.

### Current Behavior
No such feature.

### Context
It might be useful to have it either integrated into Gradle or have an official plug-in that can compile your application into GraalVM native image.

**Comment by ljacomet** [comment]
There is at least one plugin for this: https://github.com/palantir/gradle-graal and [might be others](https://plugins.gradle.org/search?term=graal).

There is currently no plans to have this made a core Gradle plugin.

**Comment by wlsc** [comment]
ok, but I hope somewhere in future along with jar and war you will integrate one more application packaging type -- native image.

**Comment by ljacomet** [comment]
I am closing this as this is something that is already provided by plugins non core to Gradle. And there is no plans to offer this from a core Gradle plugin.
