### ISSUE TITLE
Dependency Substitution not working on platform project dependencies.

### ISSUE THREAD

**Issue by udayshnk** [gradle/gradle#13204]
Created a sample proejct for the issue at [https://github.com/udayshnk/gradle-platform-dependency-substitution](https://github.com/udayshnk/gradle-platform-dependency-substitution).

Its a multi module project with subprojects named **foo-v1**, **foo-v2**, **baz-v1**, **baz-v2** and **bar**.
**bar** is depending on **foo-v1** using platform project dependency and also depending on **baz-v1** as a regular project dependency.

    dependencies {
        implementation(platform(project(":foo-v1")))
        implementation(project(":baz-v1"))
        implementation("com.google.guava:guava")
        implementation("com.fasterxml.jackson.core:jackson-databind")
    }

Dependency substitution is declared in parent build.gradle.kts to substiture **foo-v1**,**baz-v1** with **foo-v2**,**baz-v2** respectively as below

    subprojects {
       configurations {
           all {
               resolutionStrategy {
                   dependencySubstitution {
                       substitute(project(":foo-v1")).apply {
                           with(project(":foo-v2"))
                       }
                       substitute(project(":baz-v1")).apply {
                           with(project(":baz-v2"))
                       }
                   }
               }
           }
       }
    }

Below is the dependency graph for runtime configuration of project **bar**

    +--- project :foo-v1
    |    +--- com.fasterxml.jackson:jackson-bom:2.9.7
    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.7 (c)
    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0 (c)
    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.7 (c)
    |    \--- com.google.guava:guava:28.0-jre
    |         +--- com.google.guava:failureaccess:1.0.1
    |         +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
    |         +--- com.google.code.findbugs:jsr305:3.0.2
    |         +--- org.checkerframework:checker-qual:2.8.1
    |         +--- com.google.errorprone:error_prone_annotations:2.3.2
    |         +--- com.google.j2objc:j2objc-annotations:1.3
    |         \--- org.codehaus.mojo:animal-sniffer-annotations:1.17
    +--- project :baz-v1 -> project :baz-v2
    |    \--- commons-io:commons-io:2.6
    +--- com.google.guava:guava -> 28.0-jre (*)
    \--- com.fasterxml.jackson.core:jackson-databind -> 2.9.7
         +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
         \--- com.fasterxml.jackson.core:jackson-core:2.9.7

From the dependenecy graph it can be seen that dependency substitution is working fine for regular dependency like **baz**, whereas for platform dependency like **foo** substitution is not working.

Note: I have tried to debug the gradle code to figure out the issue. I have observed that DefaultProjectComponentSelector object which is constructed by parsing build script from dependencySubstituion has missing attribute **org.gradle.category=platform** for platform project dependencies.

**Comment by melix** [comment]
Thanks for this bug report. It's actually not a bug, but a missing feature. Let me explain: it's normal that the project component selector you see doesn't have the attribute, because dependency substitutions works on dependency specifications. That is to say, the `substitute(project(...))` call means "substitute dependencies which match this project dependency specification".

And because there are different kinds of dependencies (project dependencies _or_ dependencies on the platform declared by a project), the two are actually distinct.

Ideally, we should have a way to tell what _dependency attributes_ we need on the "source" of a substitution. This would let you tell "I'm actually trying to substitute project platform dependencies". Unfortunately that's a use case we totally forgot, and that we absolutely need to fix.

**Comment by udayshnk** [comment]
Thanks for analyzing the problem @melix, sorry i am unable to edit the label from bug to feature.
Passing dependency attributes for dependency substitution should be fine.
I think it would be better if that option works for both source and target types of a dependencny substituion.

**Comment by udayshnk** [comment]
Thanks a lot @melix
