### ISSUE TITLE
GE plugin init configuration is made compatible with --scan flag

### ISSUE THREAD

**Issue by felipefzdz** [gradle/gradle#13208]
### Expected Behavior

GE [docs](https://docs.gradle.com/enterprise/gradle-plugin/#gradle_enterprise) shows mechanism to configure the plugin at init script level. So, if the scripts sets 3.2.1 version of the plugin, that will be used. That should happen when using `publishAlways()` or when using `--scan` flag.

### Current Behavior

When using `--scan` flag the auto-applied GE plugin bundled with Gradle takes precedence over what it's configured at the init script, e.g. when using Gradle 6.4 the plugin version will be 3.3, even if the script configured 3.2.1.

### Context

The workaround is using `publishAlways()`, but of course, that might betoo eager for some users.

**Comment by ldaley** [comment]
This is going to be difficult to fix in Gradle.

@felipefzdz please try the example, but replace `settingsEvaluated` with `beforeSettings`. That should get the init script plugin applied first, then it will win.

**Comment by felipefzdz** [comment]
`beforeSettings` works as expected, thanks.

Should we close this? And probably related, should we update the GE docs replacing `settingsEvaluated` with `beforeSettings`.

**Comment by ldaley** [comment]
@felipefzdz let's update the docs, then close this with that as the solution.

**Comment by felipefzdz** [comment]
@ldaley https://docs.grdev.net/enterprise/gradle-plugin/#gradle_enterprise. It will be deployed to prod in our next docs release.
