### ISSUE TITLE
An exception occurred applying plugin request

### ISSUE THREAD

**Issue by sboishtyan** [gradle/gradle#13210]
I add a new module to the project. PR with changes https://github.com/avito-tech/avito-android/pull/412
And on configuration phase I get and error: 
```
* What went wrong:
An exception occurred applying plugin request [id: 'com.avito.android.instrumentation-tests', artifact: 'com.avito.android:instrumentation-tests:2020.5.4']
> Failed to apply plugin [id 'com.avito.android.instrumentation-tests']
   > com.avito.utils.gradle.EnvArgs$Impl cannot be cast to com.avito.utils.gradle.EnvArgs
```

### Expected Behavior

The configuration phase must end successfully. Because I already have modules with applied `com.avito.android.instrumentation-tests` plugin e.g.
[line with plugin applied in the same project](https://github.com/avito-tech/avito-android/blob/0d4e61b623cf094aa4bcee6fa28a28c52f61b721/subprojects/android-test/test-app/build.gradle.kts#L16)

### Current Behavior

I got the exception on the configuration phase while applying the plugin

### Context

I have no idea why it happened because I have the plugin already applied.
I changed `build.gradle.kts` to `build.gradle` but it didn't help

### Steps to Reproduce 

0. fetch [project](https://github.com/avito-tech/avito-android/tree/mbs-8472)
0. run `./gradlew help`

### Your Environment

Build scan URL: https://scans.gradle.com/s/ubcqodbdyeni2

**Comment by ljacomet** [comment]
The exception mentions a non Gradle type - `com.avito.utils.gradle.EnvArgs` - so I would look first into that plugin implementation.

Unless you can provide a small reproducer pointing at a Gradle issue, this type of report will not get much attention given the current priorities of the team.

**Comment by sboishtyan** [comment]
> The exception mentions a non Gradle type - com.avito.utils.gradle.EnvArgs - so I would look first into that plugin implementation.
That plugin is in our project. We have full control to fix it but I have no idea how
> Unless you can provide a small reproducer pointing at a Gradle issue, this type of report will not get much attention given the current priorities of the team
In my opinion, it is a Gradle issue because I have a module in my project with applied `com.avito.android.instrumentation-tests` and there are no exceptions and plugin works.
I ask for help I'm free to dig by myself, but I need a direction

**Comment by runningcode** [comment]
Can you double check that it isn't related to this change: https://github.com/avito-tech/avito-android/commit/467f43fd1a6904e95e71478e44959c73f5b14b86#diff-3460908a873409dfe94a2b460b4e954dR17

That change has changed the method's return type.

**Comment by sboishtyan** [comment]
> Can you double check that it isn't related to this change: [avito-tech/avito-android@467f43f#diff-3460908a873409dfe94a2b460b4e954dR17](https://github.com/avito-tech/avito-android/commit/467f43fd1a6904e95e71478e44959c73f5b14b86#diff-3460908a873409dfe94a2b460b4e954dR17)
> 
> That change has changed the method's return type.

Thank you for digging so deep. I will check this. But what is your hypothesis? As I see we hide concrete return type by interface and anything didn't change for consumers

**Comment by sboishtyan** [comment]
So I've reverted version to 2020.4.6 and got:

* What went wrong:
An exception occurred applying plugin request [id: 'com.avito.android.instrumentation-tests', artifact: 'com.avito.android:instrumentation-tests:2020.4.6']
> Failed to apply plugin [id 'com.avito.android.instrumentation-tests']
   > com.avito.utils.gradle.EnvArgs$Stub cannot be cast to com.avito.utils.gradle.EnvArgs

As I said previous the most strange thing that we already have modules with the applied plugin and they work correct

**Comment by sboishtyan** [comment]
Does anyone have any ideas?
One more thing I have no problems with my plugin outside of my repository. So the problem occurs only when I use the plugin in the repo where the plugin source code locates

**Comment by sboishtyan** [comment]
I found a root cause. Today I will write more information. It would be a pleasure for me if you give me an explanation: why it is happening

**Comment by sboishtyan** [comment]
We had the error at the line with [EnvArgs.kt property](https://github.com/avito-tech/avito-android/blob/develop/subprojects/gradle/build-environment/src/main/kotlin/com/avito/utils/gradle/EnvArgs.kt#L16)

The problem is that we have [LazyPropertyInProjectExtras](https://github.com/avito-tech/avito-android/blob/develop/subprojects/gradle/kotlin-dsl-support/src/main/kotlin/com/avito/kotlin/dsl/ProjectExtensions.kt#L130).
It helps us to compute something once and put it to the `rootProject.extras` and then we simply get an instance from `rootProject.extras`.

So, we created an instance with some `ClassLoader` and put it in `rootProject.extras`.
Then while applying plugin in another module we got the instance from `rootProject.extras` and tried to cast it but got ClassCastException because we have another instance of `ClassLoader`.

It wasn't obvious that I couldn't share instances via `rootProject.extras`

Is It expected behavior that we load classes with different ClassLoaders in the configuration phase?
What is the right way to share instances between plugins in the configuration phase?

@ljacomet @runningcode I will be glad If you find time to read this and ask my question. Thank you.

**Comment by sboishtyan** [comment]
I dig deeper.
At [my branch](https://github.com/avito-tech/avito-android/tree/mbs-8472) I have three modules with applied `com.avito.android.instrumentation-tests plugin`:
- [test-app](https://github.com/avito-tech/avito-android/blob/mbs-8472/subprojects/android-test/test-app/build.gradle.kts#L16)
- [test-app-kaspresso](https://github.com/avito-tech/avito-android/blob/mbs-8472/subprojects/android-test/test-app-kaspresso/build.gradle.kts#L15)
- [test-app-1](https://github.com/avito-tech/avito-android/blob/mbs-8472/subprojects/android-test/test-app-1/build.gradle.kts#L4)

They were looking up the `plugin Class` in `org.gradle.api.internal.plugins.DefaultPluginRegistry#lookup(org.gradle.plugin.use.PluginId)`

`test-app` was first who looked for the `plugin Class`. Couldn't find it in the cache and loaded the `plugin Class` by his ClassLoader
Then `test-app-1` looked for the `plugin Class`. And it couldn't find `plugin Class` too, so it loaded a `plugin Class` by own ClassLoader
The last one was `test-app-kaspresso`. It found the `plugin Class` loaded by `test-app` in the cache `org.gradle.api.internal.plugins.DefaultPluginRegistry#idMappings`

So, I have three modules and twice loaded `plugin Class`. Is It an expected behavior?

**Comment by sboishtyan** [comment]
I think I met a rare case. So closing issue shall be a better option for both sides
