### ISSUE TITLE
Jacoco Xml report for each Subproject level Gradle

### ISSUE THREAD

**Issue by cdpatelgit** [gradle/gradle#13214]
**My Project configuration** : Gradle 2.8 ,SonarQube 7.9
**Problem Statement** : Do we have any way to generate jacoco xml report for each subproject?
					As my root project has so many subproject and we dont want to analyze all projects.
					so in sonar-project.properties we have subproject level properties defined.
					Can anyone please suggest how we can generate jacoco xml report for each subproject level?

**Comment by cdpatelgit** [comment]
1. I have project structure like below so much nested project structure:
  Root project
       projectA
       projectB
            project B1
            project B2
            project B3
      project C

2. We are using powerMock for Junit 
3. I have tried below for jacoco xml report generate for each subproject
   **My root project build.gradle**:


```
subprojects{ subproject->

   buildscript {
      repositories {
         flatDir ( name:'gradle_plugin', dirs: "${rootDir}/lib/gradle_plugin" )
      }

      dependencies { classpath 'com.att.osd.gradle:gradle_plugin:1.0' }
   }
	
   apply plugin: 'java'
   apply plugin: 'eclipse'
   apply plugin: 'jacoco'

   jacoco { 
		toolVersion = "0.8.2" 
		//reportsDir = file("$buildDir/customJacocoReportDir")
   }

test {
		finalizedBy jacocoTestReport // report is always generated after tests run
	}
   jacocoTestReport {
		dependsOn test // tests are required to run before generating the report
	}
	
	jacocoTestReport {
		group = "Reporting"
		description = "Generate Jacoco coverage reports after running tests."
		reports {
			xml.enabled true
			//xml.destination file("${buildDir}/reports/jacocoXml")
			csv.enabled false
			html.enabled true
			}
	}
}

```
4. i am executing gradle jacocoTestReport  then xml and html reports are getting generated but few classes not showing coverage in it. while i am trying same class from eclipse its showing coverage.

Can someone please guide what is wrong here?

**Comment by ljacomet** [comment]
This type of question is better asked on Stackoverflow or the [Gradle discourse](https://discuss.gradle.org).

Given that you are using Gradle 2.8, I would strongly recommend attempting to update. While you might be facing a bug in Gradle, there will be not fix for an old version.
