### ISSUE TITLE
Tar and Untar tasks lose symbolic links

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1321]
Current and expected behavior can be derived from the issue title.

### Context
Migrated from [GRADLE-3002](https://issues.gradle.org/browse/GRADLE-3002) with 8 votes

### Steps to Reproduce (for bugs)
_Reproducible example needed_

### Your Environment
This is not working in Gradle 1.7, Gradle 2.3, and likely recent releases.

**Comment by ddresser** [comment]
I can confirm that this is still an issue in Gradle 3.4.1.

**Comment by abedwardsw** [comment]
still occurs on Gradle 4.0

**Comment by myskov** [comment]
#3982 describes the issue wider, has linked PR and discussions with gradle engineers. Worth closing this issue as a duplicate.
