### ISSUE TITLE
Verify correct usage of FileTimeStampInspector when file-system watching is enabled

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13234]
When file-system watching is enabled, we use the global scope `FileTimeStampInspector` to determine whether Gradle can use the hash of a file from the file hashes cache if the timestamp and size of the file are the same.

The `BuildScopeFileTimeStampInspector` does something slightly different and the caching hasher uses this one when file watching is disabled.

We should check whether the above can cause any problems, like missing some file content changes, or not.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
I checked out `FileTimeStampInspector` and its sub-classes and added some clarifying comments about their usage: https://github.com/gradle/gradle/pull/13579

This are the differences I found:

* The Gradle user home last build timestamp is updated every time there is a build with a daemon running in the same Gradle user home.
* The build session scoped last build timestamp is only updated per build on the same project.
* The Gradle user home timestamp inspector discards some hashes from `fileHashes` at the end of the build.

I don’t understand why the global timestamp inspector removes some files from the global file hasher, and the build session scoped timestamp inspector doesn’t.

Since the watching virtual file system uses the `fileHashes` cache located in the Gradle user home, it is correct that it also uses the Gradle user home scoped file timestamp inspector. Both timestamp inspectors have the same strictness guarantees.

**Comment by wolfs** [comment]
The `FileTimeStampInspector` use `File.lastModified()` to obtain the last modified of the marker file. I wonder if we should use the `FileSystem` service instead, so we use a consistent way to determine the timestamp of a file.

**Comment by wolfs** [comment]
I ended up using `Stat` in #13579.

**Comment by lptr** [comment]
I like the changes in #13579.

> I don’t understand why the global timestamp inspector removes some files from the global file hasher, and the build session scoped timestamp inspector doesn’t.

This is the only thing that worries me. If it makes sense to evict these things for the global inspector, why not for the project-level one? It would be good to ask @adammurdoch about the reasons, I couldn't figure out the reasons from the comment on the commit that introduced the eviction.
