### ISSUE TITLE
Allow specifying global buildscript classpath repo from init script for script plugins

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1323]
Migrated from [GRADLE-2801](https://issues.gradle.org/browse/GRADLE-2801) with 51 votes.

### Expected Behavior
As background, here is an example of what users are trying to achieve:
1. Have a single place where all repositories are defined, and which point to our nexus - it should be global, not per build
2. Have a parent boilerplate build file that applies some plugins, in this case, the gradle-tomcat-plugin
3. Have all webapps apply the parent build and be able to use its configuration, classpath and so on and only refine the configuration as the webapps need it

### Current Behavior
The above is not possible.

### Context
This may be related to #952 and #883. This is one of the most highly sought features from JIRA.

**Comment by bmuschko** [comment]
Definitely related to https://github.com/gradle/gradle/issues/1322.

**Comment by adammurdoch** [comment]
This is quite doable now:

1. Create a script plugin that contains the repository definitions.
2. Use this in each script plugin:

```
buildscript {
    apply from: 'repos.gradle', to: buildscript
    dependencies {
        ...
    }
}
```

**Comment by fbaro** [comment]
To expand on your answer, are you suggesting something along the following lines?
* Create a `repos.gradle` in a common directory, e.g. the user `.gradle` directory:
```
repositories {
  maven {
    url '...'
  }
}
```
* Add the following to each `gradle.build`
```
buildscript {
  apply from: "${System.properties['user.home']}/.gradle/repos.gradle", to: buildscript
}
```

**Comment by eriwen** [comment]
Given @adammurdoch's note, closing as delivered.

**Comment by bendavidpaz** [comment]
Is the thread closed to a follow up question? How can repos.gradle utilize properties like those found in gradle.properties.

I have used @adammurdoch 's suggestion and discovered that properties from gradle.properties are not ingested by repos.gradle script. My script is not located in .gradle folder.  The properties are important as those credentials should not be into repos.gradle script

Example repos.gradle script with literals provided but repoURL property provided in gradle.properties file :

```
apply plugin: "groovy"
apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'maven-publish'
apply plugin: "com.jfrog.artifactory"

buildscript {
	repositories {
		maven { credentials { username "admin"; password "admin"}  
			url repoURL + "MavenRepo/"}
		}
}

```
The error from attempting to compile is:   Could not get unknown property 'repoURL for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

**Comment by bendavidpaz** [comment]
I figured a workaround which isn't that pretty. Using groovy, I read in the properties file in whatever scope I need. In my case I defined the properties in the buildscript closure and then iterated over each property from the properties file. Walla, the properties were available in the buildscript also.

**Comment by bimargulies** [comment]
Having to edit each buildscript does not resolve the issue here. The need is to download an arbitrary complex build from github and run it using a repository manager as the repository without having to patch each and every .gradle file.

**Comment by kennknowles** [comment]
Agree with @bimargulies. I feel like I must be missing something. My use case: build an existing project offline using a customized maven repository mirror. Invasively changing the `*.gradle` files is not an option.

**Comment by nlwillia** [comment]
I found it difficult to externalize and share the repositories block in all the places where I needed it, but injecting config properties works well enough.  I did a study in how to apply some of these techniques [here](https://github.com/nlwillia/kotlintest).  It's invasive, but if you're trying to centralize key properties and cut down on boilerplate, that's a compromise that may be worth making.
