### ISSUE TITLE
Repositories don't follow redirects

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#13259]
### Expected Behavior

Repositories should follow redirects

### Current Behavior

They do not

### Context

The androidx project has a repository for snapshots, where they upload builds to regularly. This repo url is intended to follow a redirect: https://androidx.dev/snapshots/latest/artifacts/repository

### Steps to Reproduce 

```kotlin
repositories {
  maven("https://androidx.dev/snapshots/latest/artifacts/repository")
}
```

Then attempt to use a snapshot dependency from there, such as `androidx.activity:activity-ktx:1.2.0-SNAPSHOT`

**Comment by ZacSweers** [comment]
CC @tikurahul, who maintains that site on the Google side

**Comment by tikurahul** [comment]
I think the URL should have been  `https://androidx.dev/snapshots/latest/artifacts/repository`.

**Comment by ZacSweers** [comment]
Just to clarify - it doesn't follow the redirect with the fixed URL either

**Comment by melix** [comment]
I just tried a sample build file:

```
plugins {
    id 'java-library'
}

repositories {
  maven { url = "https://androidx.dev/snapshots/latest/artifacts/repository" }
}

dependencies {
    implementation 'androidx.activity:activity-ktx:1.2.0-SNAPSHOT'
}
```

and metadata is downloaded properly. Is this still an issue for you?
```

**Comment by tikurahul** [comment]
Which version of Gradle are you using ?

**Comment by melix** [comment]
Gradle 6.6. But there hasn't been any change in this area for months so I suspect it's the same for older versions.

**Comment by ZacSweers** [comment]
Confirmed this is working for us now too. I'm not sure what changed where as both Rahul and I were able to reproduce it, buuuuuut I'm not complaining!
