### ISSUE TITLE
Applying plugins to root project from another plugins can be not idempotent

### ISSUE THREAD

**Issue by ilgonmic** [gradle/gradle#13252]
In Kotlin project, there is plugins, which can applying another plugins on root project but nor project, on which was applied initial plugin.

**Case:**
There are 2 plugins `org.jetbrains.kotlin.multiplatform` and `org.jetbrains.kotlin.js` in which, another plugin `NodeJsRootPlugin` is applied to root project.
There is project with 2 subprojects, in one `org.jetbrains.kotlin.multiplatform` applied, in another - `org.jetbrains.kotlin.js`.
Both will apply `NodeJsRootPlugin` onto root project, which leads to problems, for example with duplicated task registration.
*Note:* there is WA, plugins `org.jetbrains.korlin.multiplatform` and `org.jetbrains.kotlin.js` can be declared on root project with `apply false` and it solves particular problem.

### Expected Behavior
Applying plugins is idempotent. And the second applying doing nothing.

### Current Behavior
The second applying doing `apply` method. And it breaks build with duplicated task registration.

### Context
Some issues:
https://youtrack.jetbrains.com/issue/KT-31669
https://youtrack.jetbrains.com/issue/KT-39210

### Steps to Reproduce 
In https://youtrack.jetbrains.com/issue/KT-39210 there is project.
It is reproducer, which now is failed, because `NodeJsRootPlugin` applied on root project twice.
Sorry for this non minimized reproducer, I tried to minimize it with sample plugins, but failed with it :(
[temp-13-js-lib.zip](https://github.com/gradle/gradle/files/4689076/temp-13-js-lib.zip)

### Your Environment
Build scan URL: https://scans.gradle.com/s/rvr5dio3h7kpg

**Comment by ov7a** [comment]
Sorry for the late reply.

Given that the YT issues are closed and the collaboration between Gradle and JetBrains, this is most likely obsolete. 

Unless there is a disagreement, this issue will be closed in 7 days.

**Comment by ilgonmic** [comment]
Feel free to close it, no problem
