### ISSUE TITLE
Unable to create instances with ClassGenerator after upgrading to 5.6.3

### ISSUE THREAD

**Issue by darshanmehta10** [gradle/gradle#13257]
We have got a bunch of custom plugins in our project and we use `ClassGenerator` interface to instantiate model classes in the plugin definitions.

Current Gradle version : 4.10.3
Version to be upgraded to : 5.6.3

### Expected Behavior
* When we instantiate classes with `classGenerator.newInstance(<class>,  <args>)`, it should return a new instance

### Current Behavior
* When we execute  `classGenerator.newInstance(<class>,  <args>)`, it throws an Exception saying `unable to resolve class org.gradle.api.internal.ClassGenerator`
* This is still expected as `ClassGenerator` has moved to [model-core](https://github.com/gradle/gradle/tree/v5.6.3/subprojects/model-core/src/main/java/org/gradle/internal/instantiation) package. However, after updating the `import` path, we still get the same error as the `interface` is no longer public.

### Context
* The changes are present in [this](https://github.com/gradle/gradle/commit/481d3468977e643f704151e9cc3c3c47d99074d4) and [this](https://github.com/gradle/gradle/commit/80d1acd581a32fd45173329c9d50497a6633e6c1) commits. Although there might be reasons behind these changes, we are not sure how we can instantiate the classes.
* Another option for us would be to use `ObjectFactory`. However, that requires constructors to be annotated with `@Inject`. We do not have control over the classes we are trying to instantiate so can't change those.

### Steps to Reproduce 
```
ClassGenerator classGenerator = rootProject.services.get(ClassGenerator)
MyClass instance = classGenerator.newInstance(MyClass, args)
```

**Comment by melix** [comment]
This isn't a bug. `ClassGenerator` is an internal Gradle class (as its package name implies). You shouldn't really have used it in the first place. Also the software model is deprecated and will be removed. Would you mind sharing more context for what you are doing and why you need this internal utility?

**Comment by darshanmehta10** [comment]
@melix thanks for the reply. Sure, let me add some context. We are using `ClassGenerator` to instantiate the classes, below is the example code:

```
MyClass instance = classGenerator.newInstance(MyClass, args).with {
   a = some_value
   b = some_value
}


instance.conventionMapping.with {
   c = some_value
   d = some_value
}
```

Now, this class has constructor that accepts `args`, so we can replace the above instantiation code with the following:

```
MyClass instance = new MyClass(args).with {
   a = some_value
   b = some_value
}


instance.conventionMapping.with {
   c = some_value
   d = some_value
}
```

That way, we would move away from `ClassGenerator` and would still have the `instance`. However, this fails on subsequent line with the error saying ` No such property: conventionMapping for class MyClass`. Now, `MyClass` doesn't have a property named `conventionMapping` so I believe it gets dynamically injected while the class is instantiated with `ClassGenerator` and is not present while calling the constructor explicitly.

I don't know much about how `ClassGeneator` instantiates the classes but I need to replicate the same behavior without using `Classgenerator`.

**Comment by melix** [comment]
You should then use the `ObjectFactory`:

```
class MyClass {
   int a
   int b
   int c
   @javax.inject.Inject
   MyClass(int c) { this.c = c }
}

def obj = objects.newInstance(MyClass, 3)

obj.conventionMapping.with {
   map('a') { 1 }
   map('b') { 2 }
}

println obj.a
println obj.b
println obj.c
```

Note that using convention mapping is not recommended anymore. We recommend that you model using the [lazy configuration API](https://docs.gradle.org/current/userguide/lazy_configuration.html) instead.

**Comment by darshanmehta10** [comment]
@melix thanks again for the prompt response. I have already tried using `ObjectFactory` (I have mentioned that in the description too). However, it complains about Model classes not having constructors annotated with `@Inject`. As I do not have control over Model classes, I can't use `ObjectFactory`. Is there any other workaround?

**Comment by melix** [comment]
Not that I'm aware of...

**Comment by bmuskalla** [comment]
Given this is about contracts of internal classes, there is no regression we plan to address at this point.
