### ISSUE TITLE
Artifact transforms for binary dependencies are executed too late (only when task actions request artifacts)

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#13267]
### Problem
When a task depends on artifact types that require transforms, Gradle does not run the transforms eagerly but waits until the task's action requests them, which significantly slows down build speed. (This issue holds for external module dependencies, not project dependencies.)

### Version
Gradle 6.5-milestone-1
Android Gradle plugin (AGP) 4.1.0-alpha10

### Steps to Reproduce 
1. Open [MyApplication.zip](https://github.com/gradle/gradle/files/4695740/MyApplication.zip). It is an empty Android project with the following script in the `app/build.gradle` file.
```
if (project.getProperties().get("withDepSub") == "true") {
    configurations.all {
        resolutionStrategy.dependencySubstitution.all { DependencySubstitution dependency ->
            if (dependency.requested instanceof ModuleComponentSelector
                    && dependency.requested.group == "com.google.code.findbugs") {
                dependency.useTarget "com.google.errorprone:error_prone_annotations:2.3.4"
            }
        }
    }
}

configurations {
    myDependencies {
        attributes.attribute(Attribute.of('artifactType', String), "processed-jar")
    }
}
dependencies {
    myDependencies "com.google.code.findbugs:jsr305:3.0.2"
}
task printMyDependencies {
    inputs.files(configurations.myDependencies)
    doLast {
        println "I'm in the task action of " + name
        println "Resolved files: " + configurations.myDependencies.files
    }
}
```
In the `gradle.properties` file, the Jetifier feature needs to be disabled to reveal this bug (explained below):
```
android.enableJetifier=false
```

2. Run `./gradlew :app:printMyDependencies -PwithDepSub=false -i`. Observe that the IdentityTransform from `jar` to `processed-jar` (added by the AGP) is executed only when the task's action requests it.
```
All projects evaluated.	
...
:app:printMyDependencies (Thread[Execution worker for ':',5,main]) started.	
> Task :app:printMyDependencies	
Task :app:printMyDependencies in app Starting	
...
I'm in the task action of printMyDependencies
Transforming artifact jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2) with IdentityTransform	
...
Resolved files: .../jsr305-3.0.2.jar
Task :app:printMyDependencies in app Finished
```

3. Run `./gradlew :app:printMyDependencies -PwithDepSub=true -i`. Observe that the transform is executed early before the task starts.
```
All projects evaluated.
...
IdentityTransform (Thread[Execution worker for ':',5,main]) started.
> Transform artifact error_prone_annotations-2.3.4.jar (com.google.errorprone:error_prone_annotations:2.3.4) with IdentityTransform
Transforming artifact error_prone_annotations-2.3.4.jar (com.google.errorprone:error_prone_annotations:2.3.4) with IdentityTransform
...
IdentityTransform (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
:app:printMyDependencies (Thread[Execution worker for ':',5,main]) started.
> Task :app:printMyDependencies
Task :app:printMyDependencies in app Starting
...
I'm in the task action of printMyDependencies
Resolved files: .../error_prone_annotations-2.3.4.jar
Task :app:printMyDependencies in app Finished
```

### Observations
1. Adding dependency substitution rules seems to force Gradle to resolve configurations and run transforms early ([relevant code](https://github.com/gradle/gradle/blame/8600b25fe82115c703a2af46e1b88d09a5bd3903/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultResolutionStrategy.java#L226)). While resolving configurations early during task graph creation decreases build speed, running transforms early is beneficial, and the latter seems to outweigh the former.

Since the Jetifer feature in the AGP has dependency substitution rules, we have noticed that the build is faster with Jetifier enabled (since transforms are executed early) than with Jetifier disabled.

2. However, if the substitution rule is written in this [simpler form](https://docs.gradle.org/current/userguide/resolution_rules.html#sub:module_to_project_substitution) to indicate that only module dependencies are replaced by module dependencies:
```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute module("...") with module("...")
    }
}
```
then the transforms are executed late again (possibly because Gradle thinks it is safe to do so, whereas if the rules are written in the other form shown in the example script, Gradle has to resolve configurations early in case module dependencies are replaced by project dependencies).

That's why our attempt to rewrite the rule for Jetifier in the simpler form actually resulted in a performance regression: https://issuetracker.google.com/156449751#comment9

3. If we remove `configurations.myDependencies.files` from the task action in the example above, then the transform is not executed when `-PwithDepSub=false`, which is optimal as they won't be needed (but it is still executed when `-PwithDepSub=true`). I'm guessing that could be a motivation for running the transforms when the task action actually needs them, but that case doesn't seem to be common enough to justify that strategy.

### Expected Behavior
Artifact transforms should be executed early to improve build speed.

**Comment by hungvietnguyen** [comment]
Adding more context: Looks like this boils down to ways dependency resolution takes place, and both have their pros and cons:

1. Early dependency resolution during task graph creation phase: 
- Pros: Required transforms are executed early, which improves build speed.
- Cons: Dependency resolution will be single-threaded, which decreases build speed (as filed at this bug http://issuetracker.google.com/156449751#comment1).

2. Lazy dependency resolution (only when the relevant tasks run): 
- Pros: Dependency resolution happens in parallel.
- Cons: Required transforms are executed too late, which can become bottlenecks (as reported at this comment http://issuetracker.google.com/156449751#comment9).

Which strategy is better probably depends on the build scenario (e.g., whether the transform cache is populated and most transforms are up-to-date, in which case when the transforms are executed probably doesn't matter).

=============

Currently, Gradle seems to use strategy 1 for project dependencies and strategy 2 for external module dependencies. (From https://docs.gradle.org/current/userguide/artifact_transforms.html#artifact_transform_selection_and_execution: _"You can now see what happens when we run the resolveRuntimeClasspath task which resolves the runtimeClasspath configuration. Observe that Gradle transforms the project dependency before the resolveRuntimeClasspath task starts. Gradle transforms the binary dependencies when it executes the resolveRuntimeClasspath task."_)

I guess this ticket can be closed as working as intended, but I'm leaving it open to see if you want revisit the strategies or introduce a new transform scheduling mechanism to address the cons in strategy 2.

**Comment by hungvietnguyen** [comment]
FYI: In AGP, we are not really blocked by this issue right now, so it's up to Gradle to see if there are any optimizations that can be done in this area.

**Comment by hungvietnguyen** [comment]
To be more specific, from https://docs.gradle.org/current/userguide/artifact_transforms.html#artifact_transform_selection_and_execution:

> Observe that Gradle transforms the project dependency before the `resolveRuntimeClasspath` task starts. Gradle transforms the binary dependencies when it executes the `resolveRuntimeClasspath` task.

Is there a reason binary dependencies are treated differently than project dependencies? It seems to me that it will improve build performance significantly if all project and binary dependencies are transformed *as early as possible* in the task execution phase **after** task graph creation (transforming them during task graph creation will actually slow down the build as they can't be parallelized). // cc @wolfs as I think he has experience in this area.

**Comment by wolfs** [comment]
The problem here is the following: Gradle does not resolve the full dependency graph (note that this does not mean to resolve aka download the dependencies) when trying to find out task dependencies for performance reasons, mostly because task dependency calculation is serial. This is why Gradle does not detect some external dependencies at task graph building time which need to be transformed, and therefore can not schedule the necessary transforms. When you use dependency substitution, this forces Gradle to resolve the full dependency graph at task graph building time - and that is why it is able to detect the transform which needs to run and schedule it.

So the right solution here is to always resolve the full dependency graph on task graph building time and make this faster. Note that when you use configuration caching, this will happen and therefore the transforms should be scheduled accordingly.

**Comment by hungvietnguyen** [comment]
Thank you for the nice explanation! It's a lot clearer now. :)
