### ISSUE TITLE
Allow SourceSet descriptions analogously to Project and Task descriptions

### ISSUE THREAD

**Issue by stellingsimon** [gradle/gradle#13265]
Thank you for building the awesome product that Gradle is. I hope to make a small contribution with this feature request:

### Expected Behavior

Given this Gradle Kotlin DSL code in a `build.gradle.kts` (which compiles just fine)...
```
val dbUnitTestSourceSet = sourceSets.create("dbUnitTest") {
    description = "contains unit tests which require a running DB"
    ...
}
```

...I expect to set the description of the newly created SourceSet `dbUnitTest`.

### Current Behavior

Instead, with the above snippet, I am accidentally overwriting the project's description.
Note how this happens only with `SourceSet`, but not `Configuration` or `Task` objects.

The following already do what I expect them to:

```
val dbUnitTestTask = task<Test>("dbUnitTest") {
    description = "Runs db unit tests"
    ...
}
```

```
val commonImplementation by configurations.creating {
    description = "base configuration extended by every other 'implementation' configuration"
}
```

### Context

Our project makes extensive use of SourceSets to structure our code base, usually ~5-8 source sets per Gradle project. These source sets are created in various files, so documenting them in the Gradle model (and not just the source code) seems worthwhile. 

The fact that `SourceSet`'s don't have a description is a serious element of surprise when using Gradle's API, because `Project`, `Configuration` and `Task` objects all have a description property. Further, the fact that this code compiles just fine because of the implicitly available `project.description` makes the issue worse.

```
val dbUnitTestSourceSet = sourceSets.create("dbUnitTest") {
    description = "contains unit tests which require a running DB"
    ...
}
```

**Comment by ljacomet** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.
