### ISSUE TITLE
Make checking the integrity of the gradle wrapper files convenient

### ISSUE THREAD

**Issue by LouisCAD** [gradle/gradle#13291]
Currently, there's a way to [check the integrity of the jar file for the gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification).
Its usefulness is very limited though, because it's not the entry point of Gradle.
The entry point is a **shell or batch file**, which **can do as much damage as a malicious jar file**.

After [a discussion on the Gradle Community Slack](https://gradle-community.slack.com/archives/CA7UM03V3/p1584883460197900), I learned that these files might be rightfully modified to tweak the launch arguments, so here's my proposal:

# Proposal

Provide a reliable tool that checks the integrity of the `gradlew` and `gradlew.bat` files (independently of the OS it's been run on) against an online database secured by Gradle, and, in case of a difference, shows the diff so the user can check it, and judge whether the modifications are safe or not.

Such a tool should not rely on the version of the gradle wrapper, to allow it to work on old projects that one might want to checkout for any reason.

This could be integrated into the [gradle wrapper validation GitHub Action](https://github.com/marketplace/actions/gradle-wrapper-validation).

Finally, this could be integrated into IDEs such as IntelliJ, Android Studio, CLion, Eclipse, and in a middleware for the gradle wrapper (for runs from command line), to make trying out projects, issue reproducers and all safer for everyone by default, reducing the likelihood of developers having their machines compromised with all the scary implications that it can bring.

**Comment by big-guy** [comment]
I think that this isn't likely something we'll do.

The importance of providing a checksum for the Gradle wrapper jar is that it's very hard to review. Shell scripts are reviewable and I think should be treated like any other piece of code that you're considering to run.

Verifying that the shell script matches something that Gradle has generated doesn't tell you that...

1. The build.gradle, settings.gradle, etc scripts are safe to execute
2. The plugin dependencies that the build downloads are safe to execute
3. The project's dependencies are safe to execute
4. The code that's compiled is safe to execute

The wrapper scripts aren't used when interacting with Gradle via TAPI, so this largely wouldn't improve that situation.

**Comment by LouisCAD** [comment]
What is TAPI? Searching for the acronym on Google didn't help.

**Comment by LouisCAD** [comment]
> Shell scripts are reviewable

Differences, yes, but shell is less readable than gradle scripts. About the dependencies, I can analyze where they come from, and even before that, analyze the repositories that are defined, since some of them (e.g. mavenCentral, google…) bring a security responsibility.

**Comment by LouisCAD** [comment]
My concern was about projects one would clone, not projects one would maintain and review PRs, although, there, automatic checking would also help.

**Comment by vlsi** [comment]
I wonder if it makes sense to verify artifacts and dependencies against user-local database.

Gradle 6.2 has [dependency verification](https://docs.gradle.org/current/userguide/dependency_verification.html). However, what it does it verifies the dependencies against in-repository checksums and signing keys.

What if there was a way to have a machine-local trust database that would be used to verify dependencies?

----

Dependency verification alone does provide safety within a single project, however, if I download an unknown project, then it is not that easy for me to verify the provenance :-/
On the other hand, if I configure my Gradle that SHA512 `7EBA7097...ACC4` is ok for `org.ow2.asm:asm:7.1`, then the use of third-party repositories would be safer.

----

The same goes for `gradle-wrapper.jar` and `gradlew`. There might be user-local database for the set of "approved" scripts, so user might be warned when the script is odd.
Of course, users should not launch `gradlew` directly in that case, and they should launch Gradle with a machine-local script (e.g. https://github.com/kordamp/gm, http://www.gdub.rocks/ or something like that)

WDYT?

**Comment by big-guy** [comment]
Sorry for missing all of these replies.

TAPI is the Tooling API which IDEs and other tooling uses to communicate with Gradle. 

@vlsi that's an interesting idea. It sounds similar to what malware scanners do to look for known bad files, but for the opposite purpose.

Another problem with trying to verify `gradlew` scripts is that they can and are modified by users for legitimate purposes. 

I'm going to close this because we don't have plans to provide checksums for other generated files (`gradlew` and `gradlew.bat`) at this time.
