### ISSUE TITLE
ProviderFactory#gradleProperty does not work for project-local properties

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#13302]
### Expected Behavior

It should work

### Current Behavior

It does not. Property is always considered "not present"

### Context

I am trying to use the new `ProviderFactory#gradleProperty()` APIs to better prepare for configuration caching.

### Steps to Reproduce 

Repro case:

This project + branch: https://github.com/ZacSweers/CatchUp/compare/z/gradlePropertyIssueDemo?expand=1

In `app/build.gradle.kts` there are two properties used, one local to `app` and the other local to the whole project.

```kotlin
val localProperty = providers.gradleProperty("localProperty").orElse("not found")
val rootProperty = providers.gradleProperty("rootProperty").orElse("not found")

println("Local property is ${localProperty.get()}")
println("Root property is ${rootProperty.get()}")
```

Run `./gradlew help`

Observe that the local property is not found and only the root project is

```
> Configure project :app
Local property is not found
Root property is rootPropertyValue
```

I would expect that the `localProperty` would be found. If I manually do it like so

```kotlin
val localProperty = providers.provider { property("localProperty")?.toString() }.orElse("not found")
```

it works

```
> Configure project :app
Local property is localPropertyValue
Root property is rootPropertyValue
```

This is with Gradle 6.4.1. I gave it a try on 6.5-rc-1, but to no avail. A slight change is that 6.5 doesn't allow resolving those at configuration time, but with a simple dummy task:

```kotlin
val localProperty = providers.gradleProperty("localProperty").orElse("not found")
val rootProperty = providers.gradleProperty("rootProperty").orElse("not found")

abstract class DummyTask : DefaultTask() {

  @get:Input abstract val localPropertyProp: Property<String>
  @get:Input abstract val rootPropertyProp: Property<String>

  @TaskAction
  fun act() {
    println("Local property is ${localPropertyProp.get()}")
    println("Root property is ${rootPropertyProp.get()}")
  }
}

tasks.register<DummyTask>("testingThingsOut") {
  localPropertyProp.set(localProperty)
  rootPropertyProp.set(rootProperty)
}
```

And then running `./gradlew testingThingsOut`

```
> Task :app:testingThingsOut
Local property is not found
Root property is rootPropertyValue
```

Still no dice :/ 

### Your Environment

Build scan URL:

**Comment by ZacSweers** [comment]
For now I've added this in our plugin as a workaround

```kotlin
// TODO remove this once https://github.com/gradle/gradle/issues/13302 is fixed
internal fun Project.localGradleProperty(name: String): Provider<String> {
  return provider {
    if (hasProperty(name)) {
      property(name)?.toString()
    } else {
      null
    }
  }
**}**
```

**Comment by framon** [comment]
Should it resolve properties defined inside `ext` of `build.gradle` too? It haven't too.

**Comment by bamboo** [comment]
> Will it resolve properties defined inside ext of build.gradle too?

No.

**Comment by ZacSweers** [comment]
@bamboo I heard through the grapevine that apparently project-local properties aren't officially supported and won't be supported in configuration caching, but I can't find any docs or info about this. Is that going to be the case (i.e. is this bug obsolete)?

**Comment by ZakTaccardi** [comment]
I _almost_ found a workaround to fully support this with the configuration cache - but was unable to identify what gradle properties were passed on the command line as a `StartParameter` in a way that supported config caching
  * https://github.com/gradle/gradle/issues/19474

**Comment by ZacSweers** [comment]
Closing due to lack of feedback from Gradle

**Comment by ZakTaccardi** [comment]
@ZacSweers why is it beneficial to close this? Lack of complete `Property<String>` support for _all_ gradle properties has been the most difficult part of migrating to the configuration cache for us personally.

Would love some feedback from Gradle here, too

**Comment by ZacSweers** [comment]
Feel free to open a new one if you want to pursue it, I'm not obligated keep these issues in my inbox when their lack of acknowledgement just becomes a point of annoyance.
