### ISSUE TITLE
Dynamic task not processing command line method

### ISSUE THREAD

**Issue by skyviper** [gradle/gradle#13310]
If I write a task and it uses a dynamic task to run a command line it doesn't attempted to run the command line. There isn't any output the to the Gradle console. Also why isn't commandLine 'cmd', args treated the same as commandLine 'cmd', "opt1", "opt2"?

### Expected Behavior
The commandLine should run (or fail due to shell syntax issues). Also, using the args collection should act the same as adding each element to the method.

### Current Behavior

The commandLine doesn't run and no output to the console window is shown.
Using the args collection causes the options to be incorrectly handled.

### Context

Causes a lot of time to find work-arounds

See code example below

### Steps to Reproduce 

```
task ex1{
	ext.xArrayList = new ArrayList<>() //Gradle and Groovy syntax
	def xArray1 =[param1:'listA', param2:'dir', param3:'/A']
	def xArray2 =[param1:'listB', param2:'dir', param3:'/B']
	def xArray3 =[param1:'listW', param2:'dir', param3:'/W']
			
	xArrayList.add(xArray1)
	xArrayList.add(xArray2)
	xArrayList.add(xArray3)
}

task ('varyTask')
{	
	dependsOn 'ex1'

	doLast
	{
		ex1.xArrayList.forEach	//Groovy syntax
		{
			println"Running list ${(it.get("param1")).toUpperCase()}."	
			
			def cmd = it.get("param2")
			def copt = it.get("param3")
			
			task "cmd${it.get("param1")}"(type:Exec){$it->
				workingDir '../'
				args "${cmd}"
				args "${copt}"
					
				commandLine 'cmd', args
				
				//commandLine 'cmd', "${cmd}", "${copt}"
				
				print commandLine
				
			}

			println" "
		}
		
	}
}
```
### Your Environment

Windows 7/10

Build scan URL:

**Comment by big-guy** [comment]
This won't work as you're trying to do it.  You're creating tasks during the execution phase, so those tasks will never be executed.

I think you may want to use `project.exec {}` to execute things instead of defining a task for each, but it's a little hard to tell.  There are lots of helpful people on our forums and Slack that could answer your question.

**Comment by skyviper** [comment]
Hi,
Why does half of the task work and the other half doesn’t? This seems inconsistent with your explaination.

Regards

**Comment by skyviper** [comment]
Can you reopen until completely answered?
