### ISSUE TITLE
Make sure SamplesToolingApiIntegrationTest shuts down isolated daemons before deleting daemon log

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1332]
### Expected Behavior
During the tests' cleanup phase, all files must be accessible for removing

### Current Behavior
Tests may fail on Windows with
`java.io.IOException: Unable to delete file: subprojects\tooling-api\build\tmp\test distros\can_use_tooling_API...run_tasks\sc605\toolingApi\runBuild\daemon\3.5-snapshot-1\daemon-3972.out.log`

https://builds.gradle.org/viewLog.html?buildId=2242395

**Remove `@LeaksFileHandles` annotation from test class once this is fixed.** - https://github.com/gradle/gradle/commit/b9c5bb24e5fd67675f0d1747b523e90638d93530

**Comment by eriwen** [comment]
@jjohannes is this still an issue?

**Comment by jjohannes** [comment]
This is covered in https://github.com/gradle/ci-health/issues/91
