### ISSUE TITLE
Extended test results for Tooling API events

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#13323]
Tooling API uses `FailureResult` with `Failure` instances for failed tests ([javadoc](https://docs.gradle.org/current/javadoc/org/gradle/tooling/Failure.html)). This limits possiblities of introspection and error handling. See [IJTestEventLogger.groovy](https://github.com/JetBrains/intellij-community/blob/553c8de0cf1ae90adbde0258c2496e899d1ab11c/plugins/gradle/resources/org/jetbrains/plugins/gradle/IJTestLogger.groovy#L58) for sample of such handling.

### Expected Behavior
TAPI client have an opportunity to post-process the actual errors and receive result of this post processing

### Current Behavior
Client can only get a list of `Failure`

### Context
IntelliJ IDEA extracts additional information:
 * to distinguish between assertion error and test code failure
 * to display diff views between actual and expected information

**Comment by donat** [comment]
Fixed in https://github.com/gradle/gradle/pull/19911
