### ISSUE TITLE
CL code snippets are broken in Gradle docs

### ISSUE THREAD

**Issue by rohjar** [gradle/gradle#13320]
### Expected Behavior

Code snippets are properly displayed
### Current Behavior

> gradle -q hello
include::{snippetsPath}/tasks/accessUsingPath/tests/accessUsingPath.out
### Context

online documentation
### Steps to Reproduce 

open for example: https://docs.gradle.org/current/userguide/more_about_tasks.html
and go to any 'Output of gradle ...' snippet

**Comment by suztomo** [comment]
I also observe this problem.

https://docs.gradle.org/current/userguide/build_lifecycle.html

<img width="1257" alt="Screen Shot 2020-06-03 at 11 22 55" src="https://user-images.githubusercontent.com/28604/83655886-e4bfc900-a58c-11ea-9330-fdf716b049bb.png">
