### ISSUE TITLE
Env/Gradle property providers do not handle absence alone

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#13334]
### Expected Behavior

I would expect a non-existent env or gradle property to result in an absent provider/property

### Current Behavior

It will throw.

### Context

In some cases, certain envs or properties may only exist in certain environments (such as CI). When trying to create a property around these, a task that accepts them with no wrapping will fail rather than allow the task to rely on semantics like `orElse` or `orNull`.

### Steps to Reproduce 

Simple setup in a `build.gradle.kts` file

```kotlin
val userProvider = project.providers.environmentVariable("NOT_A_REAL_ENV")

abstract class TestTask : DefaultTask() {
  @get:Input
  abstract val userProp: Property<String>

  @TaskAction
  fun printUser() {
    println(userProp.orNull ?: "Absent")
  }
}

project.tasks.register<TestTask>("testTask") {
  userProp.set(userProvider)
}
```

Then run `./gradlew testTask` and you will see this exception during configuration

```
A problem was found with the configuration of task ':testTask' (type 'Build_gradle.TestTask').
> No value has been specified for property 'userProp'.
```

Interestingly, it does handle absence on the property itself. For example, this change will make the task/configuration pass.

```kotlin
val userProvider = project.providers.environmentVariable("NOT_A_REAL_ENV")
    .orElse("Absent")
```

The same results happen if you use `gradleProperty` instead of `environmentVariable`. Same workaround makes it pass too

```
A problem was found with the configuration of task ':testTask' (type 'Build_gradle.TestTask').
> No value has been specified for property 'userProp'.
```

### Your Environment

Build scan URL:

**Comment by bamboo** [comment]
Hi @ZacSweers 👋 

`userProp` is missing a `@get:Optional` annotation.

**Comment by ZacSweers** [comment]
D'oh! 🤦‍♂️

Would it be of interest to make this issue a FR for that to be a suggestion in the error message? Something like "did you mean to make this property optional?" maybe?

**Comment by autonomousapps** [comment]
This has bitten me before, so enhancing the error message with "maybe use `@Optional`?" seems potentially useful.

**Comment by ZacSweers** [comment]
FYI @runningcode - using `convention` on the property itself doesn't actually seem to escape this, which seems odd 🤔 

```
val userProvider = project.providers.environmentVariable("NOT_A_REAL_ENV")

abstract class TestTask @Inject constructor(objects: ObjectFactory) : DefaultTask() {
  @get:Input
  val userProp: Property<String> = objects.property<String>().convention("default")

  @TaskAction
  fun printUser() {
    println(userProp.orNull ?: "Absent")
  }
}

project.tasks.register<TestTask>("testTask") {
  userProp.set(userProvider)
}
```

Will result in 

```
A problem was found with the configuration of task ':testTask' (type 'TestTask').
> No value has been specified for property 'userProp'.
```

**Comment by bamboo** [comment]
@ZacSweers, failing with `No value has been specified for property...` is the expected behaviour in that case. 

The reason for that is that a given `convention` value is only used when no value (or provider) has been set for the property. It is not the same as providing a default value.

If you believe this behaviour is not ideal, please open a separate feature request.
