### ISSUE TITLE
Provider.orElse(<provider>) tests presence eagerly

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#13333]
### Expected Behavior

If I have a provider used in a task, it should not test presence during configuration

### Current Behavior

It does, and results in an exception

```
Caused by: java.lang.IllegalStateException: Cannot obtain value from provider of environment variable 'USER' at configuration time.
Use a provider returned by 'forUseAtConfigurationTime()' instead.
```

### Context

I want to use an environmentVariable provider and want to default it if absent.

### Steps to Reproduce 

Drop this into a build.gradle.kts file

```kotlin
val userProvider = project.providers.environmentVariable("USER")
    .orElse(project.provider { "absent" })

abstract class TestTask : DefaultTask() {
  @get:Input
  abstract val userProp: Property<String>

  @TaskAction
  fun printUser() {
    println(userProp.get())
  }
}

project.tasks.register<TestTask>("testTask") {
  userProp.set(userProvider)
}
```

Then run `./gradlew testTask`

You'll see this failure

```
Could not determine the dependencies of task ':testTask'.
> Cannot obtain value from provider of environment variable 'USER' at configuration time.
  Use a provider returned by 'forUseAtConfigurationTime()' instead.

```

### Your Environment

Build scan URL:

**Comment by runningcode** [comment]
I believe the best way of setting a default value for this use case would be using convention:
```
val userProvider = project.providers.environmentVariable("USER")
    .convention(project.provider { "absent" })
```

**Comment by ZacSweers** [comment]
convention is a `Property` API, not a `Provider` API :/

**Comment by bamboo** [comment]
Thanks for the report, @ZacSweers.

There is indeed a problem with `orElse(Provider<T>)`, in the meantime, if you want to use a constant as a default `orElse(T)` should work as expected.

**Comment by lwasyl** [comment]
@bamboo Doesn't seem to work for `orElse(T)` either, though. This code:
```kotlin
val someProp = providerFactory.gradleProperty("someProp")
    .forUseAtConfigurationTime()
    .orElse("fallback")
```
works when calling `someProp.get()` in configuration phase, but 

```kotlin
val someProp = providerFactory.gradleProperty("someProp")
    .orElse("fallback")
    .forUseAtConfigurationTime()
```
does not and fails with
```
A problem occurred evaluating project ':app'.
> Cannot obtain value from provider of Gradle property 'someProp' at configuration time.
  Use a provider returned by 'forUseAtConfigurationTime()' instead.
```

**Comment by bamboo** [comment]
@lwasyl, that's by design, `forUseAtConfigurationTime()` only effects the immediate provider it's called on.

**Comment by lwasyl** [comment]
Ah, I misunderstood the original issue then. Thanks for clarifying :)

**Comment by technoir42** [comment]
@bamboo I see that you made a draft PR. Is anything blocking it?
FWIW my use case is a fallback from an environment variable to Gradle property.

**Comment by bamboo** [comment]
@technoir42 that PR requires more work, in its current state it causes some regressions.

We plan to get back to that soon.
