### ISSUE TITLE
Multiple Daemon spawning

### ISSUE THREAD

**Issue by Gh05ts** [gradle/gradle#13354]
I have Java JDK 13 installed on my machine, as android studio and gradle currently don't support it, I have to change the jdk location for the project to the version that android installs in the path './android/android studio/jre'. But it is giving a warning of multiple daemon spawning on doing so, the project builds, but I'm not sure if this is intended behavior and whether it can cause trouble while building projects.

### Expected Behavior

After changing the jdk location gradle should only be using the specified version for jdk not the JAVA_HOME of the my environment as well as the jdk location inside project structure, leading to multiple daemon spawns.

### Current Behavior

Multiple daemon spawns while building projects.

### Context

As Jdk 13 is currently not supported I have to change and use the jdk inside android studio to build projects, but it is causing multiple daemon spawning, although the project is build successfully regardless of the warning.

### Steps to Reproduce 

In a computer with java version 13 installed, try using android studio with JAVA_HOME set to JDK 13, the subproject properties are able to compile the program after changing jdk location to jre inside the android studio, but it is spawning multiple daemon on doing so.

### Your Environment

Build scan URL:
Using windows 10, android studio 3.6.1, gradle 5.6.4, JAVA_HOME points to jdk 13, but inside project  structure jdk location is set to '.../android/android studio/jre' to use older version of java which android studio and gradle can build.

**Comment by rpalcolea** [comment]
You appear to be in a old gradle version (5.6.4), have you tried upgrading?

Gradle introduced JDK 13 support back in Gradle 6.0 -> https://docs.gradle.org/6.0/release-notes.html#support-for-java-13

**Comment by Gh05ts** [comment]
While you are correct that might stop the multiple spawning issue, but shouldn't the gradle system be not spawning two daemons when I have set the jdk location to android path instead of my home java path?

**Comment by big-guy** [comment]
Let us know if you're still running into problems with a newer version of Gradle and Java 13
