### ISSUE TITLE
Transformation fails in project that depends on itself

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#13353]
I have a project that contains an implementation dependency to itself through a binary dependency. The `preferProjectModules` resolution strategy is then used to replace the dependency with a project dependency to look like this:

![image](https://user-images.githubusercontent.com/2517200/83932314-8e9e8180-a756-11ea-9997-278a8f8763f2.png)

Applying a transformation in this configuration _in a clean build_ crashes, since the transformation is applied to the output artifact of the project itself which, of course, doesn't exist:

```
* What went wrong:
Execution failed for task ':scythe:runtime:kaptKotlin'.
> Could not resolve all files for configuration ':scythe:runtime:_classStructurekaptKotlin'.
   > Failed to transform runtime.jar to match attributes {artifactType=class-structure, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for StructureArtifactTransform: /Users/cpuerta/temp/oss/scythe/runtime/build/libs/runtime.jar.
         > /Users/cpuerta/temp/oss/scythe/runtime/build/libs/runtime.jar (No such file or directory)
```

In order to repro, use the repo from #13329 (shared with @ljacomet, @melix and @jjohannes), pull to the latest master, and run:

```
rm -rf scythe/runtime/build
./gradlew :scythe:runtime:compileKotlin -Pscythe.apply
```

Environment: Gradle 6.5
Build scan: https://scans.gradle.com/s/rogy6bluv22gg

**Comment by jjohannes** [comment]
This is kind of related  #10484.

Although this issue here should be solved in a way that we do not get and error (while #10484 might be solved by giving the right error)

**Comment by cesar1000** [comment]
Yeah, I would expend the self-dependency to either be dropped automatically or cause an error.
