### ISSUE TITLE
finalizer tasks are not up to date when finalized tasks are up to date

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#13357]
https://discuss.gradle.org/t/finalizedby-tasks-runs-even-though-the-original-task-is-up-to-date/29150

From the documentation:

> On the other hand, finalizer tasks are not executed if the finalized task didn’t do any work, for example if it is considered up to date or if a dependent task fails.

This test fails…

```
    @Unroll
    void 'finalizer tasks are up to date if all finalized tasks are up to date'() {
        when:
        buildFile << """
            class NotParallel extends DefaultTask {}
            task a {
                finalizedBy 'f'
                inputs.file("in")
                outputs.file("out")
                doLast {
                    file("out").text = file("in").text
                }
            }
            task f {
                doLast {}
            }
        """
        file("in") << "foo"

        then:
        succeeds("a")
        executedAndNotSkipped(":a", ":f")

        and:
        succeeds("a")
        skipped(":a", ":f")
    }
```

For the second invocation, `:f` is not up to date.

### Expected Behavior

As stated by the documentation. A finalizer should be up to date if all tasks being finalized were up to date.

### Current Behavior

Finalizers are always executed.

**Comment by etiennestuder** [comment]
If we do not intend to fix the current behavior, we should at least update the [documentation](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:finalizer_tasks):

```
On the other hand, finalizer tasks are not executed if the finalized task didn’t do any work, for example if it is considered up to date or if a dependent task fails.
```

**Comment by pedrox-hs** [comment]
Hi, any update about this behavior?

**Comment by asodja** [comment]
This is more of a documentation issue. It makes sense to not run the finalizer task if finalized task is up-to-date in some cases, but not in all cases. 

So if you want the finalizer task to be up-to-date, then you should achieve that but correctly set inputs/outputs.
