### ISSUE TITLE
Project properties not accessible from settingsEvaluated

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [gradle/gradle#13362]
I have an init.d file with logic similar to this:

````
settingsEvaluated { settings ->
  settings.pluginManagement {
    resolutionStrategy {
      eachPlugin {
        if (requested.id.id.startsWith("jb_")) {
          useModule("dk.jyskebank.tooling.buildscripts:buildscripts:${buildScriptsVersion}")
        }
      }
    }
  }
}
````
I would like the project to provide `buildScriptsVersion` in its gradle.properties file.

Reading the documentation https://docs.gradle.org/current/dsl/org.gradle.api.initialization.Settings.html, I would expect properties to be available.

### Expected Behavior

The property `buildScriptsVersion` should be picked up from gradle.properties.

### Current Behavior

The builds fail with:
````
Could not get unknown property 'buildScriptsVersion' for object of type org.gradle.plugin.management.internal.DefaultPluginResolveDetails.
````

### Context

I am trying to make use of the new `id {}` syntax for applying plugins, while providing the resolution strategy from a global init file.

I would like to avoid replicating the resolution strategy into all our projects, as it will probably change over time.

### Steps to Reproduce 

The attached project archive demonstrates the problem.

Run with:
    ./gradlew --init-script initd.gradle clean

It should moan about missing a dependency, but instead fails due to the missing property.

### Your Environment

Build scan URL: https://scans.gradle.com/s/ebguqklj66rrg

**Comment by jskovjyskebankdk** [comment]
[gradle-settings-bug.zip](https://github.com/gradle/gradle/files/4745335/gradle-settings-bug.zip)

**Comment by jskov-jyskebank-dk** [comment]
Adding rootProject does fix the problem. This was not clear to me from reading the docs.

**Comment by ljacomet** [comment]
Actually, adding `rootProject` is a bit strange. Instead you should be using `settings`, which, as documented in the link from the description, has access to the different properties.

What happens is that without a prefix, `buildScriptsVersion` is resolved against the `Gradle` object, as [documented](https://docs.gradle.org/7.4.1/userguide/init_scripts.html#sec:writing_an_init_script).

That last section could have a note clearly stating that you need to pay attention to the scope of what you are attempting to reach when writing init scripts logic.
