### ISSUE TITLE
Introduce RegularFileProperty to represent output of WriteProperties task

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#13363]
This task should get a `RegularFileProperty ` called `destinationFile` to replace the simple `getOutputFile() : File` property.

**Comment by wolfs** [comment]
I don't understand why it should get a `DirectoryProperty`. I would assume it should get a `RegularFileProperty` `destinationFile`. The name could also be `propertyFile`, though `destination` and `destinationFile` is good as well.

**Comment by jjohannes** [comment]
Sorry. Copy&paste mistake. Change to `RegularFileProperty`.
