### ISSUE TITLE
(2.14.1) First Result from the Daemon Was Empty

### ISSUE THREAD

**Issue by StaticCloud** [gradle/gradle#1336]
### Expected Behavior

Hello. 

For almost two weeks now, I dealt with an issue regarding gradle; every time my application _tries_ to refresh gradle (I'm using Android Studio), it gives me an error:

Error: The first result from the daemon was empty. Most likely the process died immediately after connection.

I'm currently using Gradle 2.14.1 (Android plugin version 2.1.3).

Here is my build.gradle:

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

gradle.wrapper:
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip`

Why this is happening? I'm not sure, it started happening when I disabled version control and unsynced GitHub from Android Studio. This isn't just limited to this one project however, it started happening for every other project and every other project I created.

### Your Environment

 * Build scan URL:

**Comment by jorgeduardo27** [comment]
Have you found a solution for this problem? I've tried a lot of things but any of them seem to work.
