### ISSUE TITLE
./gradlew -version  Received fatal alert: protocol_version

### ISSUE THREAD

**Issue by zhangyang520** [gradle/gradle#13373]
Downloading https://services.gradle.org/distributions/gradle-6.0.1-all.zip

Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version

**Comment by blindpirate** [comment]
See: https://stackoverflow.com/questions/16541627/javax-net-ssl-sslexception-received-fatal-alert-protocol-version
