### ISSUE TITLE
(2.14.1) First Result from the Daemon Was Empty

### ISSUE THREAD

**Issue by StaticCloud** [gradle/gradle#1337]
### Expected Behavior

I want gradle to build successfully, with this issue however, it can't.

### Current Behavior

Error: The first result from the daemon was empty. Most likely the process died immediately after connection.

### Context

I can't run my application or edit it either.

### Steps to Reproduce (for bugs)

I'm not sure, it started happening when I disabled version control and unsynced GitHub from Android Studio. This isn't just limited to this one project however, it started happening for every other project and every other project I created.

**EDIT:** When I turned off version control (File > Settings > Version Control > Pressed "-"), I noticed that gradle was taking longer than usual to build, so I shut down Android Studio. It was when I reopened it when I got the error.

### Your Environment

I'm currently using Gradle 2.14.1 (Android plugin version 2.1.3).

Here is my build.gradle:

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

gradle.wrapper:
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip`

**Comment by eriwen** [comment]
@StaticCloud I'm sorry to say that there is not enough information for us to act here. How did you go about disabling version control? Is it possible that there is a file permissions issue (for example, if the Gradle home directory can no longer be written to)?

**Comment by StaticCloud** [comment]
@eriwen I updated my post with how I disabled version control including when the error started happening. Also, I'm not sure what you mean by the Gradle home directory (still relatively new to Android programming), is it something I access through command line?

**Comment by oehme** [comment]
I'm afraid that there is not enough information to say what was the issue here. Please feel free to reopen if this is still happening to you.

**Comment by jorgeduardo27** [comment]
I Just installed android studio on my laptop and I got the same error at the moment I created my first Application and I haven't found any solutions yet.
