### ISSUE TITLE
Allow lazy mapping of file collections while preserving input dependencies

### ISSUE THREAD

**Issue by Myaamori** [gradle/gradle#13386]
### Expected Behavior
`FileCollection` should provide e.g. a `map` or `mapLazy` function that takes a closure `(File) -> T` and returns a `Provider<List<T>>`. If the `FileCollection` contains tasks (e.g. you ran `ConfigurableFileCollection.from` with a `TaskProvider` as input), and the output provider of the map is assigned to a property or added to a `ListProperty` annotated with `@Nested` or `@Input`, the input tasks should be automatically added as dependencies of the current task.

Additionally, Gradle should track the files added to the collection and ensure that the up-to-date check fails if any of the input files have changed.

### Current Behavior
`FileCollection.map` (from `Iterable.map`) evaluates the file collection immediately and prevents lazy configuration, and does not preserve dependencies.

`project.provider { fileCollection.map { ... } }` enables lazy configuration, but does not preserve dependencies.

### Context

I have a task where, during the configuration phase, the user can add a set of "items" from files. These files can possibly be generated from other tasks, those tasks may generate multiple files, and each file may contain multiple "items". The task reads these items and merges them into one single file.

However, during configuration I want it to be possible for the user to configure the items before they're merged. Thus, the function for adding items additionally takes a closure which is executed for each read item.

My problem is that there's no obvious way of making sure that input dependencies are automatically detected if tasks were specified as inputs. Ideally I would like to do something like the following:

```kt
/* task */
class Item(@get:Internal inputFile: File) {
    @get:Internal
    val metadata = readMetadata(inputFile)

    @get:Input
    val name = project.objects.property<String>()
}

@get:Nested
val items = project.objects.listProperty<Item>()

fun addItems(files: Any, action: Item.() -> Unit) {
    // example use of non-existent mapLazy function
    val addedItems = project.files(files).mapLazy { file ->
        Item(file).apply(action)
    }
    items.addAll(addedItems)
}


/* build.gradle.kts */
val myTask by tasks.registering(MyTask::class) {
    addItems(otherTask) {
        if (metadata.type == "video") {
            name.set("My Video")
        } else {
            name.set("My Picture")
        }
    }
}
```

Instead what I have to do for Gradle to automatically notice the dependencies (and for the up-to-date check to work properly) is to add the input files to an auxiliary file collection that I never use elsewhere:

```kt
@get:Nested
val items = project.objects.listProperty<Item>()

@get:InputFiles
val auxiliaryFiles = project.objects.fileCollection()

fun addItems(files: Any, action: Item.() -> Unit) {
    auxiliaryFiles.from(files) // never used outside of this function

    // use provider to ensure lazy configuration
    val addedItems = project.provider {
        project.files(files).map { file ->
            Item(file).apply(action)
        }
    }
    items.addAll(addedItems)
}
```

**Comment by Myaamori** [comment]
Hmm that doesn't quite seem to work as I hoped. If I use `FileCollections.elements.map` and add that to a `ListProperty` marked with `@Nested` I get a warning that says `Querying the mapped value of provider(interface java.util.Set) before task ':otherTask' has completed has been deprecated.`, and the other task is not run.

I wrote a small example demonstrating the issue, tested with Gradle 6.5. The magic happens in `Merge.from`.

```kt
open class Generate : DefaultTask() {
    @get:Input
    val inputText = project.objects.property<String>()

    @get:OutputFile
    val output = project.objects.fileProperty()

    @TaskAction
    fun run() {
        output.get().asFile.writeText(inputText.get())
    }
}

/* Simple task to concatenate text files, each with its own header. */
open class Merge : DefaultTask() {
    inner class Item(@get:Internal val file: File) {
        @get:Internal
        val size = file.length()

        @get:Input
        val name = project.objects.property<String>()
    }

    @get:Nested
    val items = project.objects.listProperty<Item>()

    @get:OutputFile
    val output = project.objects.fileProperty()

    fun from(vararg files: Any, action: Item.() -> Unit) {
        val itemsLazy = project.files(files).elements.map { set ->
            set.map { file -> Item(file.asFile).apply(action) }
        }
        items.addAll(itemsLazy)
    }

    @TaskAction
    fun run() {
        val outputText = items.get().joinToString("\n\n") {
            "# ${it.name.get()}\n${it.file.readText()}"
        }

        output.get().asFile.writeText(outputText)
    }
}

val generate1 by tasks.registering(Generate::class) {
    inputText.set("hi")
    output.set(project.file("file1.txt"))
}

val generate2 by tasks.registering(Generate::class) {
    inputText.set("this is a larger file")
    output.set(project.file("file2.txt"))
}

val merge by tasks.registering(Merge::class) {
    from(generate1, generate2) {
        if (size > 10) {
            name.set("Large file")
        } else {
            name.set("Small file")
        }
    }
    output.set(project.file("merged.txt"))
}
```

Running this I get:

```
$ ./gradlew merge --warning-mode all
Querying the mapped value of provider(interface java.util.Set) before task ':generate1' has completed has been deprecated. This will fail with an error in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.5/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed
Querying the mapped value of provider(interface java.util.Set) before task ':generate2' has completed has been deprecated. This will fail with an error in Gradle 7.0. Consult the upgrading guide for further information: https://docs.gradle.org/6.5/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed
> Task :merge FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':merge'.
> java.io.FileNotFoundException: file1.txt (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 367ms
1 actionable task: 1 executed
```

Am I not using it correctly?

**Comment by adammurdoch** [comment]
Thanks for the example. It turns out using `@Nested` on a provider/property type is broken when the provider carries task dependencies. The task dependencies are being ignored and so the `merge` task is run before the generate tasks.

There are some interesting questions to answer in order to fix this. We can't query the value of the `@Nested` provider when calculating the task graph because the tasks that produce its values have not been run yet, so we would have to use only the task dependencies carried by the provider. However, if it later turns out that one of the `@Input` or `@InputFiles` (etc) properties on the nested value also carry additional task dependencies, then we have a problem because those tasks will have not been added as dependencies of the consuming task and the values will not be ready. We could just fail in this case.

**Comment by Myaamori** [comment]
I suppose that means that something like the following would not work:

```kt
val merge by tasks.registering(Merge::class) {
    from(generate) {
        name.set(someOtherTask.map { it.someValue })
    }
}
```

While I don't have any immediate need for this, it would be an unfortunate limitation of the task... Would it be at all possible to detect the dependencies in waves, so that the first time around the dependency on `generate` dependency is detected, and then after `generate` has been executed, Gradle is able to evaluate the `ListProperty`, construct the `Item` instances, detect the dependency on `someOtherTask`, which it adds to the task graph before actually running `merge`?

Or if that is not architecturally feasible (do all the dependencies have to be resolved during configuration?), maybe it could be allowed if the dependency is declared up-front using an explicit `dependsOn(someOtherTask)`?

**Comment by mlopatkin** [comment]
It looks like we already have the lazy API requested in a form of `files.elements.map { ... }`, and the `@Nested` dependency discovery is tracked in #13590. What else needs to be done here?

**Comment by mlopatkin** [comment]
So `FileCollection.getElements` is the solution to the original problem. The `@Nested` issue is tracked separately.
