### ISSUE TITLE
Unable to build Java app with gradle 5.1

### ISSUE THREAD

**Issue by darshanmehta10** [gradle/gradle#13394]
### Expected Behavior
Gradle's `compileJava` task should generate class files 

### Current Behavior
`compieJava` task fails while trying to recreate `Q` classes (i.e. `QueryDSL` classes).

### Context
I am trying to upgrade the gradle version from 4.10 to 5.1. I have a Java app and as a part of gradle build, I am generating `Q` classes (i.e. QueryDSL). Below was my configuration for Gradle 4.10:
```
task generateQueryDSL (type: JavaCompile) {
    source = sourceSets.main.java.srcDirs
    classpath = sourceSets.main.compileClasspath
    destinationDir = file('src/main/java')
    options.compilerArgs = ['-proc:only', '-processor', 'com.querydsl.apt.jpa.JPAAnnotationProcessor', '-Aquerydsl.packageSuffix=.querydsl']
}
compileJava.dependsOn generateQueryDSL
```
Now, as `com.querydsl.apt.jpa.JPAAnnotationProcessor` is no longer present in the compile classpath from Gradle 5, the above task started failing with `Annotation processor not found` message (which was expected).

I then removed `compilerArgs` and added the following in the `dependencies`:
```
annotationProcessor (
	"com.querydsl:querydsl-apt:4.2.1:jpa",
	"org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final",
	"javax.annotation:javax.annotation-api:1.3.2"
)
```
After this change, it went further but then started failing with the below logs:
```
Attempt to recreate a file for type mypackage.QMyResource
error: Attempt to recreate a file for type mypackage.QMyResource
<more such lines>
35 errors
```

This was followed by the stacktrace:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':my-app:compileJava'.
...
...
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
```

After investigating a bit more, I found [this SO answer](https://stackoverflow.com/questions/57391939/gradle-5-querydsl-generating-duplicate-classes) which explained why `annotationProcessor` was generating duplicate classes. To fix it, I got rid of `generateQueryDSL` task altogether. Now, my config looks like this:

```
compileJava {
	options.annotationProcessorGeneratedSourcesDirectory = file('src/main/java')
	options.debug = true
}
```

However, I am **still** getting the same error: `error: Attempt to recreate a file for type mypackage.QMyResource`. 

Is there anything else that I need to change?

### Steps to Reproduce 
* Execute `gradlew compileJava`

### Your Environment
Gradle Version: 5.1
Java Home: C:\jdk-11.0.5-win-x64

**Comment by pupostd** [comment]
Hi @darshanmehta10, I was getting the same issue and as a workaround I excluded the generated files from `compileJava`
```
compileJava {
  options.fork = false
  options.incremental = true
  options.encoding = 'UTF-8'
  options.deprecation = true
  options.compilerArgs += ['-Werror']

  exclude(['path/to/my/model/Q*'])
  
  dependsOn generateQueryDSL
  dependsOn processResources
  source generateQueryDSL.destinationDir
}
```

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

Have a look at the [upgrade guide for Gradle 5](https://docs.gradle.org/current/userguide/upgrading_version_4.html)
