### ISSUE TITLE
Resolving unsafe configuration resolution errors - deprecated warning - will be removed in gradle 7.0

### ISSUE THREAD

**Issue by zvrablik** [gradle/gradle#13403]
I was checking gradle 7.0 deprecated apis and found there link to https://docs.gradle.org/6.5/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors

There was request to fill new ticket in case I have usecase which require access of projects configuration metadata from other project.

I have application written for Tomcat Servlet container. There are multiple classloaders. One which is shared among all web applications and then one classloader per application. 

3rd party dependencies must be in the shared classloader (in the tomcat/lib directory) if used in both lib projects and war projects. 3rd party dependencies which are used only in war projects are packaged in the war file.

### What I use now (gradle 5 and 6.5)
To build web application dependencies I use setWarDependencies gradle task

```
def getLibProjects(){
    def subprojects = project.getParent().getSubprojects()
    def allDependencies = subprojects.minus(project)
            .findAll{p ->
        def prjType = project.esMappingProjects["${p.name}"].iSmartProjectType
        prjType == esMapping.lib
    }

    return allDependencies
}

//remove from war dependencies all dependencies already added to tomcat lib directory
task setWarDependencies {
    doFirst {

        def warProjectDeps = project.sourceSets.main.runtimeClasspath

        getLibProjects().each { prj ->
                warProjectDeps = warProjectDeps.minus(prj.sourceSets.main.runtimeClasspath)
                        .minus(prj.jar.archivePath)
        }

        war.classpath = warProjectDeps
    }
}

war.dependsOn(project.tasks.setWarDependencies)
```

### Other use case - building installer project. 

I don't use gradle to run installation, only to create izpack installer and I need to organize jar/war files to izpack packs.

To build installer I need set of jar files/war files ... to copy to directories.
I have to create the list of jar files which should be copied to tomcat/lib directory
I use this code which again access project metadata from another project

```
def jarFiles = getDependencyProjects().findAll{ prj ->
            project.esMappingProjects["${prj.name}"].iSmartProjectType == esMapping.lib
        }.collect{ prj ->
            prj.jar.archivePath
        }
```
or

```
 def webProjectJarFilesToExclude = getAllProjects().findAll{ prj ->
            def projectType = project.esMappingProjects["${prj.name}"].iSmartProjectType

            (projectType == esMapping.webapp || projectType == esMapping.webappLib)
        }.collect{ prj ->
            prj.jar.archivePath
        }
```

Is it possible to keep this usecase in gradle 7?
I don't need change the other project dependencies, I need only to know the selected projects 3rd party dependencies  to remove these from web application 3rd party dependencies to avoid having classes in both application classloader and in the shared classloader.

**Comment by melix** [comment]
This issue tracker shouldn't be used for questions. Please ask in the  [forums](https://discuss.gradle.org/) instead. In the meantime, please take a look at [safe cross-project publication docs](https://docs.gradle.org/current/userguide/cross_project_publications.html).

**Comment by zvrablik** [comment]
@Cédric Champeau
This is not question. All works fine in gradle 6.
During build I got message that I am using API which will be removed in gradle 7 and there was message to post my use case to this forum to avoid removing the API from gradle 7.
