### ISSUE TITLE
Import of Ant build script does not respect antcall definitions

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1341]
Original issue: https://issues.gradle.org/browse/GRADLE-1571

### Expected Behavior

The declaration of `antcall` is translated into a task dependency. 

### Current Behavior

The declaration of `antcall` is ignored. No task dependency is established. 

**build.gradle:**

```
ant.importBuild 'build.xml'

task intro {
    dependsOn hello

    doLast {
        println 'Hello, from Gradle'
    }
}
```

**build.xml:**

```
<project>
    <target name="indirect"/>

    <target name="hello">
        <echo>Hello, from Ant</echo>
        <antcall target="indirect" />
    </target>
</project>
```

### Context

The bug still presents a big hole in Gradle's Ant compatibility layer.

**Comment by deaddowney** [comment]
The example here doesn't reproduce the problem. 

This is the **build.gradle:**
`ant.importBuild 'build.xml'

task intro {
    doLast {
        println 'Hello, from Gradle'
    }
}
`
build.xml
`<project>

    
    <target name="indirect">
    </target>

    <target name="hello"  depends="intro">
        <echo>Hello, from Ant</echo>
        <antcall target="indirect" />
    </target>
</project>
`

**Comment by Kassmadin** [comment]
Hello there, i ran into a similar problem while using
```
ant.importBuild('build.xml') { antTargetName ->
    'a-' + antTargetName
}
```
just that the message was stating
BUILD FAILED in 0s
Imported Ant target 'a-fest' depends on target or task 'a-printEnvironmentInfo' which does not exist
15:33:15: Task execution finished 'a-fest'.

**build.gradle**
```
task printEnvironmentInfo {
    doLast {
        println 'Hello, from Gradle'
    }
}
```

**build.xml**
```
<project>
    <target name="fest"  depends="printEnvironmentInfo">
        <echo>Hello, from Ant</echo>
    </target>
</project>
```
Might the cause of this be the same as above or should i start writing a new issue?

Greetings,
Robert

PS: I might try solving this issue as it would help our transition to gradle enormously
