### ISSUE TITLE
scala cross compilation in scala plugin

### ISSUE THREAD

**Issue by borissmidt** [gradle/gradle#13418]
Hey, 
Scala has a problem with binary compatibility between minor version releases and currently we have to use plugins to cross compile scala libraries between multiple versions. 

So i wanted to ask if it would be possible to build it directly into the scala plugin of gradle. 
Then we can easily support multiple sourcesets per scala version. A bit like sbt currently does. Are you instresed into helping me implement this? 

currently i have to resort to this plugin to do it, but it woul be better that it is just build into the default plugin.
https://github.com/prokod/gradle-crossbuild-scala

**Comment by SimY4** [comment]
The way I did it in my gradle config is I created a separate build.gradle file per scala compiler version and included them as separate gradle modules sharing the same source directories:

settings.gradle
```
include 'proj_2.11'
project(':proj_2.11').with {
    projectDir = file('proj')
    buildFileName = 'build-2.11.gradle'
}
include 'proj_2.12'
project(':proj_2.12').with {
    projectDir = file('proj')
    buildFileName = 'build-2.12.gradle'
}
include 'proj_2.13'
project(':proj_2.13').with {
    projectDir = file('proj')
    buildFileName = 'build-2.13.gradle'
}
```

then in each individual file I can do:

build-2.13.gradle
```
buildDir = 'build-2.13'

clean {
    delete 'build-2.13'
}

sourceSets {
    main.scala.srcDirs += [file('src/main/scala-2-'), file('src/main/scala-2.13+')]
}
```

It's not ideal but it works alright. No additional plugins needed.
