### ISSUE TITLE
Question: What are the  possibilities and cause gradle wont downlaod a jar

### ISSUE THREAD

**Issue by blackmo18** [gradle/gradle#13420]
This question may or may not related to Gradle Itself.

As the title above, What are the possibilities and cause Gradle won't download a jar file.

This the version of Gradle I am using

------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Linux 5.3.0-59-generic amd64

------------------------------------------------------------
I uploaded my project library to bintray successfully via bintray gradle plugin, and able to see the jar files uploaded.

but when I test to use it on as dependencies I don't get any jars, and no Error at all at `gradle build`.

here I posted my [issue](https://stackoverflow.com/questions/62366952/kotlin-multiplatform-no-jar-files-downloaded-on-gradle-depedencies-after-uploa) on StackOverflow.

**Comment by ljacomet** [comment]
Replied on Stackoverflow - please do not create issues in such situations
