### ISSUE TITLE
NamedDomainObjectContainer extensions cannot be serialized (and thus passed to workers)

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#13422]
I'm trying to pass an extension created by `project.container()`, but I'm getting serialization errors because of the name constructor. Here's a simple repro:

```kotlin
abstract class Extension(
        @get:Internal val name: String
) {
    @get:Input
    abstract val thing: Property<String>
}

abstract class MyTask @Inject constructor(@Nested private val extension: Extension) : DefaultTask() {
    @TaskAction
    fun doStuff() {
        project.serviceOf<WorkerExecutor>().noIsolation().submit(Doer::class) {
            config.set(extension)
        }
    }

    abstract class Doer : WorkAction<Doer.Params> {
        override fun execute() = Unit // Do stuff

        interface Params : WorkParameters {
            val config: Property<Extension>
        }
    }
}

val myExtensions = container<Extension>()
myExtensions.register("one") {
    thing.set("Foobar")
}

tasks.register<MyTask>("myTask", myExtensions.getByName("one"))
```

And here's a build scan: https://scans.gradle.com/s/bbyvgab6p6d4i/failure

**Comment by SUPERCILEX** [comment]
Actually, it doesn't seem to have anything to do with the constructor. It's just that `container` isn't decorating the class properly or doing whatever magic is need to make the properties serializeable.

**Comment by SUPERCILEX** [comment]
BTW, I should mention that this is on Gradle 6.5 and that I thought it would work since the code above works fine if you use the `extensions` container instead of the named domain objects:

```kotlin
abstract class Extension { // Remove constructor
    @get:Input
    abstract val thing: Property<String>
}

// Use extensions container
val myExtension = extensions.create<Extension>("myExtension")
myExtension.thing.set("Foobar")

tasks.register<MyTask>("myTask", myExtension)
```

**Comment by PerryAJ** [comment]
This remains an issue on gradle 6.7, ended up moving away from `NamedDomainObjectContainer` as a result.  Would have liked to support the DSL it provides, but not usable right now for kotlin based plugins in my experience.

**Comment by SUPERCILEX** [comment]
Closing old issues.

**Comment by vlsi** [comment]
I believe the issue is still relevant.
@bmuskalla , would you consider reopening it?

I just bumped into the issue when tried passing `val signatures: NamedDomainObjectContainer<SigstoreSignature>` to `WorkParameters`
