### ISSUE TITLE
the class is not up-to-date after gradle build on 6.4.1

### ISSUE THREAD

**Issue by yulele166** [gradle/gradle#13426]
### Expected Behavior

The java class should be up-to-date after gradle build
### Current Behavior

The java class is not up-to-date after gradle build on 6.4.1

### Your Environment

Build scan URL:

$ gradle -v

------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Windows 10 10.0 amd64

**Comment by bmuskalla** [comment]
@yulele166 The description of the issue you're facing is very general. Could be please elaborate more and attach a project/snippet to reproduce this issue?
