### ISSUE TITLE
Disable file system watching when there is a change to Ant default excludes

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13427]
We want to do the following:
- Support modification of default excludes in `settings.gradle`, both with and without file system watching enabled
- Deprecate modification of default excludes after settings have been evaluated.
- If default excludes are modified during the build, we want to drop the virtual file system.

See #11176.

---
cc: @gradle/execution

**Comment by vlsi** [comment]
In Apache JMeter we un-exclude `.gitattributes` and `.gitignore` files as we need to be able to add those files to the source release artifacts: https://github.com/apache/jmeter/blob/913735db54bf5a2e0a1461aee0e110df19512424/settings.gradle.kts#L70-L74

Does that mean `DirectoryScanner.removeDefaultExclude` would disable file watching?

**Comment by wolfs** [comment]
I updated the description to reflect our current plan.
