### ISSUE TITLE
Transitive deps of substituted libraries are inherited by their replacement

### ISSUE THREAD

**Issue by nsoft** [gradle/gradle#1342]
Given:
H depends on C version 1.2 published under group name X
A depends on B version 1.0 which depends on C version 1.0 published under group name Y
B version 1.1 which depends on C version 1.0 published under group name Y

In this situation one needs to exclude the earlier version manually because the change in group name across versions prevents gradle from recognizing the newer version as a valid alternative. Thus per the docs:

```
compile("H")
compile("A") 
compile("B:1.1") {
  exclude group:"Y"
}

```

### Expected Behavior
C version 1.0 should not appear in `gradle dependencies`

A should have B:1.1 substituted for B:1.0 per normal, which should obliterate B:1.0's reference to C:1.0

The resolution of B:1.1 should manually exclude anything from group Y also obliterating that reference to C:1.0, which should leave no references to C:1.0 in the project (thus resolving the conflict created by the group change between versions)

### Current Behavior
C version 1.0 appears as a dependency in `gradle depenencies` and is packed into the ensuing war file along side C version 1.2 (required by H)

```
+ B:1.1
| + Y:C:1.0
```

This can then interfere with H if it loads classes from C:1.0

### Context
Please see http://stackoverflow.com/a/42079525/1172174

### Steps to Reproduce (for bugs)
Please see http://stackoverflow.com/a/42079525/1172174

### Your Environment
http://stackoverflow.com/a/42079525/1172174

**Comment by oehme** [comment]
I'm not sure we could make that expected behavior happen, as conflict resolution happens after the dependencies are already added to the graph. @bigdaz can probably tell you for sure.

In general, don't use excludes on individual dependencies, but on configurations instead. That way the unwanted dependency is sure to be excluded, no matter where it comes from.

```
configurations.all {
  exclude group: 'Y'
}
```
