### ISSUE TITLE
Scaladoc not working in multi-module project.

### ISSUE THREAD

**Issue by Iltotore** [gradle/gradle#13431]
I'm trying to generate the scaladoc of a subproject.

### Expected Behavior
The scaladocs should be generated

### Current Behavior
I get a MalformedURLException without further informations.

### Context
There is no more significative elements. All my subprojects have the scala plugin and I'm using Gradlew 6.5.

### Steps to Reproduce 
Create a composite project, add the scala plugin, try to generate scaladocs.

### Your Environment
Wrapper version: 6.5
OS: Windows
Used JVM: 1.8 & 11
Build scan URL: https://gradle.com/s/uilnwpdvjjyj6

**Comment by big-guy** [comment]
The build scan says you're using Gradle 6.1, could you double check that?

Scaladoc was broken in 6.0 and 6.1 with Scala 2.13 and only fixed in Gradle 6.2: https://github.com/gradle/gradle/issues/9855

**Comment by Iltotore** [comment]
I will double check that tomorrow. Maybe it's just a careless mistake.
