### ISSUE TITLE
Gradle --continous --watch-fs is slow on mac compared to linux 

### ISSUE THREAD

**Issue by erichelgeson** [gradle/gradle#13446]
I am using Java 14, Gradle 6.5, Micronaut 2.0RC1, and osx native file watcher in mn. File changes are picked up immediately but the build/start process takes over 10 seconds on macosx. The same app on Linux takes approximately 4 seconds. 

Mac is 10.15.5 Mac Book Pro i9, 64gb RAM.
PC is Ubuntu 20.20, Ryzen 3900x, 32gb RAM.

### Expected Behavior

I expect the rebuild & reload of both machines to be about the same.

### Current Behavior

The MacOS reload is 6 seconds slower.

### Context

Quickly reloading an app helps development and testing cycles.
Initial exchange testing - https://twitter.com/graemerocher/status/1272901760248623106
Video of the slowness - https://drive.google.com/file/d/1R9NayK-DFA0AseGpvp2GI_mGVv-6HJc5/view

### Steps to Reproduce 

```
$ curl https://launch.micronaut.io/demo.zip -o demo.zip
$ unzip demo.zip -d demo && cd demo
## add io.micronaut:micronaut-runtime-osx to build.gradle on osx
$ ./gradlew run --continuous --watch-fs
```
Make change, count seconds between change seen and micronaut back up listening.

### Your Environment

Build scan URL: https://gradle.com/s/5ualcsi3e4y7o

---
I am happy to grab other details may be important to help debug this with some guidance.

**Comment by lptr** [comment]
This is one of the things we are planning to implement as part of making the feature production ready. We are not yet using the native watchers for continuous mode. See https://github.com/gradle/gradle/issues/11834

**Comment by melix** [comment]
@lptr What can explain that it's fast on Graeme's machine, then? 

https://t.co/B8Ybrf9G0p?amp=1

Pretty much same hardware, same OS...

**Comment by lptr** [comment]
Continuous mode uses the JDK's built-in watcher. Maybe there was an update in some JDK version that made it more responsive. Or they just hit the end of the 6-second update window.

**Comment by erichelgeson** [comment]
Turns out it was the specific implementation of java 14- `14.0.1-open` 4 seconds (sometimes longer if I hit the "wait" max) - `14.0.1.hs-adpt` - 10.5seconds each time no matter what. Seems not all JDK's are the same. (identifiers are from `sdkman`)
