### ISSUE TITLE
Gradle 6.4.1 on Java 14 fails with "Unresolved reference: id" in plugins DSL

### ISSUE THREAD

**Issue by TimvdLippe** [gradle/gradle#13444]
### Expected Behavior
Gradle on Java 14 compiles and runs

### Current Behavior
Gradle on Java 14 fails with the following error (https://travis-ci.org/github/mockito/mockito/jobs/698916788):
```
e: /home/travis/build/mockito/mockito/settings.gradle.kts:38:3: Unresolved reference: id
FAILURE: Build failed with an exception.
* Where:
Settings file '/home/travis/build/mockito/mockito/settings.gradle.kts' line: 38
* What went wrong:
Script compilation error:
  Line 38:   id("com.gradle.enterprise").version("3.3.4")
             ^ Unresolved reference: id
1 error
```

### Context
I am trying to enable the Java 14 build on Mockito: https://github.com/mockito/mockito/pull/1945 Gradle 6.4.0 was reported to support Java 14, but I can't seem to figure out how to make that work. I haven't made any configuration changes, although I did start debugging by moving random things around (see the commits in the PR)

### Steps to Reproduce 
I honestly don't really know where to start, other than to clone Mockito and run the Gradle build on a Java 14 runtime. Sadly I lack the knowledge of Gradle and Kotlin to determine what the possible reproduction steps could be, as I am at a complete loss as to why this unresolved variable could pop up, but not in previous Java versions.

### Your Environment
I can't run the build scan, as my Gradle fails compilation before we get to that step.

**Comment by TimvdLippe** [comment]
Interestingly enough, @epeee just pointed out that the other Java 14 job we have *did* get past Gradle: https://travis-ci.org/github/mockito/mockito/jobs/698954197

**Comment by big-guy** [comment]
Hmm, this looks very strange.

The build that fails is using a different cache key: https://travis-ci.org/github/mockito/mockito/jobs/698954215#L460

so I think it's possible this is somehow some bad state carried over from another build.  Is it possible to disable to the caching to see if the problem goes away?

**Comment by TimvdLippe** [comment]
I deleted the cache on https://travis-ci.org/github/mockito/mockito/caches for PR 1945. The build did not use a build cache: https://travis-ci.org/github/mockito/mockito/jobs/699476509 and I can confirm it resolved the issue.

For the poor soul who might later find this issue: have you tried turning it off and on again? 😢
