### ISSUE TITLE
Project isn't evaluated when it's the target of a substitution and that configure on demand is used

### ISSUE THREAD

**Issue by vRallev** [gradle/gradle#13448]
In a small open source project I'm replacing some external dependencies by internal modules. This results in an obscure error that shouldn't happen according to the Gradle documentation:

https://github.com/vRallev/hephaestus/commit/805e8b34cafbc7c53c85d6c53ad2dafedfe57e49

Note that the commit reverts a workaround to make it work.

### Expected Behavior
Dependency substitution works as documented. 

### Current Behavior
The build fails:
```
Could not determine the dependencies of task ':sample:app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':sample:app:debugCompileClasspath'.
   > Could not resolve com.squareup.hephaestus:annotations:1.0.1-SNAPSHOT.
     Required by:
         project :sample:app
         project :sample:app > project :sample:library
      > No matching configuration of project :annotations was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Configuration 'ktlintRuleset':
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about its usage (required an API)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
```

### Steps to Reproduce 
1. Checkout https://github.com/vRallev/hephaestus/commit/805e8b34cafbc7c53c85d6c53ad2dafedfe57e49
2. Run `./gradlew :sample:app:assembleDebug`.

### Your Environment
Build scan URL: https://scans.gradle.com/s/q3knhbirmsule

**Comment by Jim-Bar** [comment]
Same problem here.

**Comment by melix** [comment]
This seems to be a bug with the Kotlin plugin. For some reason the variants are not visible yet when the substitution happens. A workaround is to do this in your root project:

```
evaluationDependsOn(":annotations")
evaluationDependsOn(":compiler")
```

**Comment by melix** [comment]
Correction: the issue is not related to the Kotlin plugin, but to the use of configuration on demand. Turning it off in the `gradle.properties` file _also_ fixes the problem.

**Comment by melix** [comment]
Should be reopened

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to efficiently track down and fix your problem. Our available resources are severely limited and we must be sure we are looking at the exact problem you are facing.  

If we have a reproducer we may be able to also suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you provide more information.

----

Unfortunately the link to the reproducer has expired.
