### ISSUE TITLE
Amazon Fire App / Android Studio 4

### ISSUE THREAD

**Issue by buddhatunes** [gradle/gradle#13451]
Hi, trying to build Amazon Fire App on Android Studio 4 and Windows 10, receiving error below:

"Cannot set the value of read-only property ‘outputFile’ for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=, versionCode=10, versionName=1.0.7}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl."

### Your Environment

Build scan URL:

**Comment by bmuskalla** [comment]
This sounds like an AGP/usage issue. Please try if some of the suggestions on [StackOverflow](https://stackoverflow.com/questions/46949311/cannot-set-the-value-of-read-only-property-outputfile-for-apkvariantoutputimpl/47523816) work for you. If not, please refer to the Android Issue Tracker.
