### ISSUE TITLE
Make `init` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13456]
This issue is about making the `init` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `init` plugin are compatible with the configuration cache.

Note that this issue isn't about making all builds generated by the `init` plugin to support the configuration cache. See issues for plugins used in the generated builds in https://github.com/gradle/gradle/issues/13454

**Comment by mlopatkin** [comment]
This was fixed as part of the #20156. While the `init` task is marked as `notCompatibleWithConfigurationCache`, it works without failures with the configuration cache enabled.
