### ISSUE TITLE
Gradle exits on build failure without showing an error

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#13452]
I ran into an issue where a failed build stops the execution halfway through the configuration phase without showing an error:

![image](https://user-images.githubusercontent.com/2517200/84871627-a23ec780-b035-11ea-9b0a-b958a94d8e6b.png)

I put up a private reproducer in https://github.com/cesar1000/gradle-premature-exit (since it uses an internal project). Happy to enable contributors as needed.

Gradle version: 6.5

**Comment by big-guy** [comment]
@cesar1000 could you add me to the repo?  Could you share a log with `--debug`?

Do you know what kind of failure it is? e.g., a RuntimeException, Error, something else?

**Comment by cesar1000** [comment]
There's no exception at all, in the debug output or in the daemon logs... Here's the full debug log:

[debug-log.txt](https://github.com/gradle/gradle/files/4796806/debug-log.txt)

**Comment by big-guy** [comment]
Could you invite @ljacomet to that repo too?

**Comment by cesar1000** [comment]
Yeah, done!

**Comment by big-guy** [comment]
@cesar1000 Sorry, we're trying to get our backlog of issues in order. Is this something we helped you with on Slack already? Is this still happening?

**Comment by cesar1000** [comment]
This wasn't fixed, but I used some workaround and haven't ran into it again. I put up a repro since I found it so add that it would crash without any errors. I tried to upgrade the repro to 7.2, but I'd have to upgrade the binary dependencies as well, which is too much of a hassle, I think. It's likely an edge case anyway, so feel free to close!

**Comment by big-guy** [comment]
Thanks @cesar1000
