### ISSUE TITLE
Make `maven-publish` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13468]
This issue is about making the `maven-publish` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `maven-publish` plugin are compatible with the configuration cache.

**Comment by bamboo** [comment]
Initial work done in #13391 and #13397.

**Comment by ALikhachev** [comment]
Is there any plans to make `PublishToMavenLocal` task compatible with configuration cache too? May be I can help?

**Comment by eskatos** [comment]
Thank you @ALikhachev for making `PublishToMavenLocal` task compatible with configuration caching in https://github.com/gradle/gradle/pull/16945!

**Comment by eskatos** [comment]
The 3 PRs linked in the comments above made `maven-publish` work with the configuration cache with local `file://` based repositories only. Publishing to remote repositories remains to be made compatible with the configuration cache.

**Comment by eskatos** [comment]
Related https://github.com/gradle/gradle/issues/18369

**Comment by yogurtearl** [comment]
related: https://github.com/gradle/gradle/issues/19842

**Comment by 3flex** [comment]
Fixed by #21282? If not, what's still missing?

**Comment by abstratt** [comment]
@3flex Conditional publishing for one

**Comment by abstratt** [comment]
This went into 7.6. Please open a more specific issue if you find any problems.

**Comment by abstratt** [comment]
Re: conditional publishing, see: https://github.com/gradle/gradle/issues/22641
