### ISSUE TITLE
Make `signing` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13470]
This issue is about making the `signing` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `signing` plugin are compatible with the configuration cache.

**Comment by eskatos** [comment]
None that I know of. But doing it might lead to some discoveries.

**Comment by bamboo** [comment]
Fixed via #23262 and #23280.

**Comment by gabrielittner** [comment]
Will an in memory gpg private key be stored in the cache? Asking because they are passed to the extension as string

**Comment by hfhbd** [comment]
I hope the `useInMemoryPgpKeys` won't be stored in the cache...
I also like the feature of https://github.com/gradle/gradle/issues/16056 to use a `Credential` class as configuration instead.

**Comment by martinbonnin** [comment]
> I also like the feature of https://github.com/gradle/gradle/issues/16056 to use a Credential class as configuration instead.

What does using a `Credential`class brings compared to `useInMemoryPgpKeys`? In both cases, Gradle would need some logic to not persist the keys and since most CI use environment variables, I kind of like the simplicity of `useInMemoryPgpKeys(System.getenv("KEY"), System.getenv("PASSWORD"))`

**Comment by hfhbd** [comment]
Mostly a common expected variable name aligned with RepositoryCredentials and Sonatype Publishing Credentials:
```
ORG_GRADLE_PROJECT_myMavenRepoUsername
ORG_GRADLE_PROJECT_sonatypeUsername

ORG_GRADLE_PROJECT_signingUsername // for example
```
etc.
And the option to implement your own credential class 🤷🏻‍♂️

But more important is open question of the cache..

**Comment by martinbonnin** [comment]
Gotcha.

> But more important is open question of the cache..

Agreed 👍

**Comment by gabrielittner** [comment]
@martinbonnin this sounded to me like when something is obtained through the credential API it wouldn't be persisted in the cache https://docs.gradle.org/7.6/userguide/configuration_cache.html#config_cache:requirements:safe_credentials
