### ISSUE TITLE
Compile classpath snapshotting and annotation processor detection should handle irrelevant files

### ISSUE THREAD

**Issue by melix** [gradle/gradle#1347]
The new compile classpath snapshotting and the annotation processor detection mechanisms that were introduced in Gradle 3.4-rc-1 cannot handle elements on classpath which are irrelevant to compilation. For example, the presence of a `pom.xml` file on classpath (which can happen because of transitive dependency resolution) is enough to prevent Gradle from building a Java project: https://discuss.gradle.org/t/could-not-calculate-the-signature-for-jar-file-icu4j/21452/5

Both the snapshotter and the annotation processor detector should gracefully handle irrelevant files, and just ignore them.

**Comment by oehme** [comment]
This is fixed on the release branch.
