### ISSUE TITLE
Make `project-report` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13473]
This issue is about making the `project-report` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `project-report` plugin are compatible with the configuration cache.

**Comment by abstratt** [comment]
See https://github.com/gradle/gradle/issues/22781 for a fix for HtmlDependencyReportTask.

**Comment by abstratt** [comment]
See https://github.com/gradle/gradle/issues/23728 for DependentComponentsReport (`:dependentComponents`)

**Comment by abstratt** [comment]
See https://github.com/gradle/gradle/issues/23732 for DependencyInsightReportTask (`:dependencyInsight`)

**Comment by abstratt** [comment]
See https://github.com/gradle/gradle/issues/23733 for Help Tasks plugin issues with CC/load-after-store.

**Comment by abstratt** [comment]
This is now completed, since the last remaining task #22781 has been fixed for CC.

**Comment by mlopatkin** [comment]
`dependencyInsight` task is not technically part of the `project-report` plugin, and tasks of this plugin are now fixed.
