### ISSUE TITLE
Make `kotlin-dsl` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13472]
This issue is about making the `kotlin-dsl` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `kotlin-dsl` plugin are compatible with the configuration cache.

**Comment by eskatos** [comment]
Some changes in https://github.com/gradle/gradle/pull/17449

**Comment by hythloda** [comment]
[Is this resolved in Gradle 7.5? ](https://docs.gradle.org/7.5.1/release-notes.html#:~:text=plugin%20is%20now%20compatible)

**Comment by bamboo** [comment]
Yes, it is! Thanks, @hythloda.
