### ISSUE TITLE
Make `cpp-library` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13485]
This issue is about making the `cpp-library` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `cpp-library` plugin are compatible with the configuration cache.

**Comment by mlopatkin** [comment]
Fixed in #30161.

**Comment by mlopatkin** [comment]
> This issue was closed as completed and looks release-note worthy, but no PR with release-notes update has been found. Please, do one of the following:
> 
> 1. Attach a PR with the release notes update to this issue.
> 2. Add the `has:release-notes-decision` label to the issue if it's not release-note-worthy or it was fixed in an old release and close the issue.
> 3. Close issue as "not planned".

GitHub cannot attach the PR.
