### ISSUE TITLE
Document default exclusion pattern for ConfigurableFileTree

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1348]
Original issue: https://issues.gradle.org/browse/GRADLE-1883

### Expected Behavior

Gradle applies default exclude patterns for a `ConfigurableFileTree`. Those need to be properly documented to prevent surprises. Expose a way to configure the default exclude patterns.

### Current Behavior

It's confusing to users if specific file patterns are excluded they would have expected to be included. Currently, default exclude patterns are not documented.

**Comment by foragerr** [comment]
Default exclude patterns inherited from ant:

	**/%*%             
	**/.git/**         
	**/SCCS            
	**/.bzr            
	**/.hg/**          
	**/.bzrignore      
	**/.git            
	**/SCCS/**         
	**/.hg             
	**/.#*             
	**/vssver.scc      
	**/.bzr/**         
	**/._*             
	**/#*#             
	**/*~              
	**/CVS             
	**/.hgtags         
	**/.svn/**         
	**/.hgignore       
	**/.svn            
	**/.gitignore      
	**/.gitmodules     
	**/.hgsubstate     
	**/.gitattributes  
	**/CVS/**          
	**/.hgsub          
	**/.DS_Store       
	**/.cvsignore

**Comment by lacasseio** [comment]
Thanks @foragerr for documenting those. Would you be willing to open a PR with the required change to the documentation?

**Comment by mkobit** [comment]
On a similar note, how do you remove the default exclusions in tasks like `Tar`?

**Comment by Vampire** [comment]
@mkobit look at the linked original JIRA issue, there I provide a work-around. I don't know whether it works in recent Gradle versions and there are certainly improvements that could be done like issuing the reset in a finalized task that didn't exist when I made the workaround.

**Comment by mkobit** [comment]
Thanks @Vampire , don't know how I didnt see that.

It looks like that is still a useful workaround and worked for me on both `4.0.2` and `4.1-rc-2`

**Comment by Vampire** [comment]
@bmuschko, @eriwen and @blondierte, documentation is just half of the necessary changes. The original JIRA issue actually was about the missing way to disable the excludes for a task and merely mentioned that documentation is also missing. There is still no way to disable them for one task, is there? And if, it is not mentioned in the newly added documentation.

**Comment by blindpirate** [comment]
@Vampire Thanks for pointing out, I don't want to put a workaround in the documentation, and we haven't made any decision about how to disable it. I've created #2986 to propose and track the following update.

And I would appreciate hearing your opinion in @2986 .
