### ISSUE TITLE
Make `visual-studio` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13482]
This issue is about making the `visual-studio` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `visual-studio` plugin are compatible with the configuration cache.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/30423

**Comment by adammurdoch** [comment]
Release notes are in referenced PR.
