### ISSUE TITLE
Make `xctest` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13488]
This issue is about making the `xctest` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `xctest` plugin are compatible with the configuration cache.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/30423

**Comment by adammurdoch** [comment]
Release note updates are in the referenced PR.
