### ISSUE TITLE
Java incremental compilation api/impl usages separation does not work between modules

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [gradle/gradle#13499]
As I understand, https://github.com/gradle/gradle/pull/10419 was intended to break chains of incremental compilation early by stopping at "private" usages of affected types.

E.g. If `B` privately uses `A` and `C` uses `B`, then a change in `A` should not cause a recompilation of `C`.
```
public class A {
      // uncomment incremental change below
      // public int bar() { return 0; }
}

public class B {
     private A a = null; 
}

public class C {
    B getB() {
           return new B();
     }
}
```
In the example the separation works as intended only when `A`, `B` and `C` are in the same source set. If `C` is in a different subproject, then `C` is recompiled on an ABI change of `A`, which is suboptimal.
In case of the Kotlin project (https://github.com/JetBrains/kotlin) that often results in an effectively non-incremental (i.e. incremental compilation, which recompiles almost everything) recompilation of Java. It might be even slower, than the clean compilation, because of the dependency analysis.

I suspect, that the difference between inter- and intra-source-set IC is a bug.
Also it seems to me, that the problem comes from two places.
First is `ClasspathChangeDependentsFinder.collectDependentsFromClasspath` https://github.com/gradle/gradle/blob/bea6b1cbb4d2507ca3885f825d363ecc55a54124/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/ClasspathChangeDependentsFinder.java#L98
```
    private DependentsSet collectDependentsFromClasspath(Set<String> modified) {
        final Set<String> privateDependentClasses = Sets.newHashSet(modified);
        final Set<String> accessibleDependentClasses = Sets.newHashSet(modified);
        final Deque<String> queue = Lists.newLinkedList(modified);
        while (!queue.isEmpty()) {
            final String dependentClass = queue.poll();
            for (File entry : classpathSnapshot.getEntries()) {
                DependentsSet dependents = collectDependentsFromClasspathEntry(dependentClass, entry);
                if (dependents.isDependencyToAll()) {
                    return dependents;
                } else {
                    for (String intermediate : dependents.getPrivateDependentClasses()) {
                        if (privateDependentClasses.add(intermediate) && !accessibleDependentClasses.contains(intermediate)) {
                            queue.add(intermediate);
                        }
                    }
                    for (String intermediate : dependents.getAccessibleDependentClasses()) {
                        if (accessibleDependentClasses.add(intermediate) && !privateDependentClasses.contains(intermediate)) {
                            queue.add(intermediate);
                        }
                    }
                }
            }
        }
        return DependentsSet.dependentClasses(privateDependentClasses, accessibleDependentClasses);
    }
```
Here private usages are added to the `queue`, so they will be processed just like `modified` entries. Which means that the analisys does not stop at private usages within a classpath.
E.g. for 
```
public class A {
      // public int bar() { return 0; }
}

public class B {
     private A a = null; 
}

public class C {
    private B b = null;
}

public class D {
    public B b = null;
}
```
`B` is added to `privateDependentClasses`, then `C` is also added to `privateDependentClasses` and `D` is added to `accessibleDependentClasses`. However, only `B` should be added to 
`privateDependentClasses`, because `C` & `D` cannot be affected by a change in `A`.

So all transitive usages of a modified class (within a classpath) are considered affected (affected class set is not optimal).
Then `handleModified` finds all dependends of the affected class set.
```
    private DependentsSet handleModified(File classpathEntry, final ClasspathEntrySnapshot previous) {
        final ClasspathEntrySnapshot currentSnapshot = classpathSnapshot.getSnapshot(classpathEntry);
        ClassChanges classChanges = currentSnapshot.getChangedClassesSince(previous);

        if (classpathSnapshot.isAnyClassDuplicated(classChanges.getAdded())) {
            return DependentsSet.dependencyToAll("at least one of the classes of modified classpath entry '" + classpathEntry + "' is already present in the classpath");
        }

        DependentsSet affectedOnClasspath = collectDependentsFromClasspath(Sets.union(classChanges.getModified(), classChanges.getAdded()));
        if (affectedOnClasspath.isDependencyToAll()) {
            return affectedOnClasspath;
        } else {
            Set<String> joined = affectedOnClasspath.getAllDependentClasses(); // <- here joined also contains private usages
            return previousCompilation.getDependents(joined, currentSnapshot.getRelevantConstants(previous, joined));
        }
    }
```
This means, that even if `B` privately uses `A` within a classpath, usages of `B` within a sourceset are still considered affected by an ABI change of `A`. It does not seem right, only usages of `A` should be considered affected.

The described behaviour can be easily reproduced with examples above and Gradle 6.0.1 (I think the bug is reproducible with any 6.+ version, but I tested only with 6.0.1).

**Comment by pillisan42** [comment]
I think we have the same problem described by @altsvetkov on a big multimodule project

And it provoke or build to go from 10 seconds to 3 min recompilation depending on which class we have modified.

I'm investigating why my build is slow event with incremental recompilation since 3 month. 

Note: We did not had this problem on 5.x version
