### ISSUE TITLE
Component metadata rules with injected services leak project references

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#13497]
We inject an `ObjectFactory` in a `ComponentMetadataRule`:

```
    static class IvyVariantDerivationRule implements ComponentMetadataRule {

        @Inject
        ObjectFactory getObjects() { }
```

That results in an `__objects__` field on the generated `$Inject` class causing project reference leaks in the daemon:

<img width="1451" alt="Screen Shot 2020-06-17 at 2 29 00 PM" src="https://user-images.githubusercontent.com/1479220/84953334-2d58a580-b0a8-11ea-980b-de7f31471459.png">

We're configuring this by class, as it's intended to be a cachable rule (which I guess would also leak this reference if it weren't on this path):

```
project.dependencies.components.all(IvyVariantDerivationRule)
```

### Expected Behavior
Class-based component metadata rules provide a safe way of using project-scoped services without leaking references to them.

### Current Behavior
Project references are retained causing memory leaks.

### Steps to Reproduce 
- Configure a class based rule, injecting a project scoped service that holds a reference to the project, such as `ObjectFactory`
- Run a build
- Take a heap dump and notice that there are live references to `DefaultProject_Decorated` instances 

### Your Environment
Gradle 6.5

**Comment by rpalcolea** [comment]
Just in case, our rule deviates a little bit from https://docs.gradle.org/current/userguide/variant_model.html#sub:ivy-mapping-to-variants but same implementation when using `ObjectFactory`

**Comment by melix** [comment]
Can you clarify what memory leak you see? The in-memory module metadata cache is _per build_. It means that at the end of a build, it's discarded. While I agree that it doesn't really make sense that the in-memory cache keeps a reference to the rules (I was actually working on a fix before I remembered this cache is _per build_), which themselves leak the project, but Gradle would never, in any case, release the `Project` instances before the end of a build.

This means that in practice even if we have a path to the project in this cache, it shouldn't be a problem (the GC will release the cache on memory pressure).

Does it make sense?

**Comment by DanielThomas** [comment]
Oh, maybe I misread the path. I gather `valuesForPreviousSession` is discarded on a the new run? `DefaultCrossBuildInMemoryCache` threw me.

**Comment by melix** [comment]
Oh wait, yours is a `@CacheableRule`, right? If this is the case, then it's cross build...

**Comment by DanielThomas** [comment]
Yes it is. We turned off caching again because of the exclude issues we saw, but it's intended to be cacheable.
