### ISSUE TITLE
Gradle 6.5 allocated large numbers of 'jar transforms' threads

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#13492]
Looks like these eventually get freed but wanted to check in that such large numbers of allocated threads weren't a surprise:

{noformat}
jstack 32507 | grep 'jar transforms' | wc -l
     223
{noformat}

### Expected Behavior
Not sure. That's why I'm asking.

### Current Behavior
Large number of transform threads are allocated.

### Context
N/A

### Steps to Reproduce 
Ran a build for the first time on Gradle 6.5.

### Your Environment
Gradle 6.5

**Comment by big-guy** [comment]
Since 2a1e74166bc82607e15de78002ef56582b34af0d, we've limited the number of threads that can be created to ~availableProcessors

This should probably be rolled into other worker limits, but I think this is very early in the process.
