### ISSUE TITLE
Configuration cache should support file-system based repositories

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13509]
The configuration cache doesn't support file-system based repositories yet. This issue is about adding that support.

### Expected Behavior

The configuration cache supports file-system based repositories.

### Current Behavior

Changes to the filesystem in the repositories aren't detected.
As a workaround you can use `--refresh-dependencies`.

See https://docs.gradle.org/nightly/userguide/configuration_cache.html#not_yet_implemented

**Comment by melix** [comment]
You mean "Configuration cache _should support_ file-system based repositories"?

**Comment by eskatos** [comment]
Right, thanks @melix. Fixed this issue's title and did the same with the other ones I just opened in batch.

**Comment by adammurdoch** [comment]
Fixes in https://github.com/gradle/gradle/pull/23284
