### ISSUE TITLE
Configuration cache should support composite builds

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13503]
The configuration cache doesn't support composite builds yet. This issue is about adding that support.

### Expected Behavior

The configuration cache supports composite builds.

### Current Behavior

See https://docs.gradle.org/nightly/userguide/configuration_cache.html#not_yet_implemented

**Comment by simtel12** [comment]
I don't suppose there is any target milestone for this yet?  Is there anything we of the community can do to help?  :)  Do you know generally how this should be implemented?

**Comment by eskatos** [comment]
This will ship in 6.8
