### ISSUE TITLE
Configuration cache should support dynamic and changing dependencies

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13508]
The configuration cache doesn't support dynamic versions nor changing modules yet. This issue is about adding that support.

### Expected Behavior

The configuration cache supports dynamic versions and changing modules.

### Current Behavior

See https://docs.gradle.org/nightly/userguide/configuration_cache.html#not_yet_implemented

**Comment by adammurdoch** [comment]
Support for dynamic versions added via https://github.com/gradle/gradle/pull/13584

**Comment by adammurdoch** [comment]
Support for changing modules added via https://github.com/gradle/gradle/pull/13616
