### ISSUE TITLE
Make `cpp-unit-test` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13514]
This issue is about making the `cpp-unit-test` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `cpp-unit-test` plugin are compatible with the configuration cache.

**Comment by mlopatkin** [comment]
Fixed in #30250. Need to update the compatibility table.

**Comment by mlopatkin** [comment]
Has release notes in #30250
