### ISSUE TITLE
Review how TestKit directories are watched

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#13513]
File-system watching will be enabled by default soon, and this includes TestKit tests. When the same daemon is reused to run many such tests, it could end up watching a lot of separate hierarchies, which are suspected to cause issues at least on macOS.

There are a few things we can investigate:

- don't enable file-system watching for TestKit tests (probably not a good idea)
- force using a fresh daemon per test (likely overkill)
- drop VFS and stop watching after TestKit test method finished (hard to detect, but maybe we can wire something into the test directory provider?)
- ensure that test directory is cleaned up after successful test (how can we enforce this? what happens if there are many failed tests that we want to preserve the output of?)

---
cc: @gradle/execution

**Comment by wolfs** [comment]
We could remove things from the VFS which haven't been read for a longer time when we need to watch many directories for hierarchical watchers.
