### ISSUE TITLE
flatDir repositories not inherited by upstream projects

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1352]
Example project reproducing this issue: https://github.com/eriwen/gradle-repro-1352

### Expected Behavior
Given a subproject with a `flatDir` repository, it should be inherited and used from parent projects.

### Current Behavior
It seems as though `flatDir` repositories are not inherited by parent projects (or some underlying problem). 

### Workaround
Declare same `repositories {}` in parent project.

### Context
Migrated from [GRADLE-1940](https://issues.gradle.org/browse/GRADLE-1940) with 3 votes

### Steps to Reproduce (for bugs)
Run `gradle build` in [example project](https://github.com/eriwen/gradle-repro-1352)

### Your Environment
This issue affects 1.0 through 3.4

**Comment by oehme** [comment]
This works as designed, repositories are project scoped. This also doesn't just apply to flat dir repositories, but to any repositories.

**Comment by mauromol** [comment]
This does not justify the current behaviour, I think, at least not completely. If you look at the example project, it's project B that depends on a JAR in its own flatDir repository. Project A does not have any direct dependency on that JAR, it just inherits it from B. So, project A by itself does not need any JAR from that flatDir, however it still does not build unless you add an (apparently useless) flatDir declaration on A too.

**Comment by oehme** [comment]
It does need that repository, to fetch the transitive dependency. The simplest workaround is defining the same repositories for all projects once, in an allprojects block.
