### ISSUE TITLE
Update integration tests using Jetty to run on JDK15

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#13530]
For reference, builds with test failures:
Quick Linux: https://builds.gradle.org/viewQueued.html?itemId=36077906
Quick Windows: https://builds.gradle.org/viewLog.html?buildId=36078330

Jetty used in integration tests uses a deprecated Java method that's being removed: https://builds.gradle.org/viewLog.html?buildId=36077888&tab=buildResultsDiv&buildTypeId=Gradle_Check_Quick_16_bucket33 We use an old version of Jetty in the tests infrastructure. We should either upgrade or rewrite the failing parts to not use Jetty.

**Comment by ljacomet** [comment]
@rieske Do you have any ETA expectations for this to be done?

**Comment by rieske** [comment]
We would like Gradle to support JDK15 once it is released in September.
This only affects the testing infrastructure on our side and not the build tool itself, but it would be great to have the pipeline green and without skipped tests by then.

**Comment by melix** [comment]
See https://github.com/gradle/gradle/pull/14378
