### ISSUE TITLE
JDK 15 support in Gradle

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#13532]
We have experimental pipeline set up that tests Gradle against an early access release of JDK15.

For reference, builds with test failures:
Quick Linux: https://builds.gradle.org/viewQueued.html?itemId=36077906
Quick Windows: https://builds.gradle.org/viewLog.html?buildId=36078330
Platform Linux: https://builds.gradle.org/viewQueued.html?itemId=36083404
Platform Windows: https://builds.gradle.org/viewQueued.html?itemId=36082316

Those are the issues that need to be resolved before Gradle can be used on top of JDK15:
- Java version parsing for early access versions in the `files` module: https://github.com/gradle/gradle/pull/13409
-  Jacoco plugin. https://github.com/gradle/gradle/issues/13529
- Jetty used in integration tests https://github.com/gradle/gradle/issues/13530
- Some Kotlin snippets tests are failing: https://github.com/gradle/gradle/issues/13531

Ready for release experimental pipeline on JDK15 should also be added to possibly uncover more issues.

**Comment by big-guy** [comment]
Docs have been updated (except release notes) and CI Pipeline has been updated to use JDK15.

JaCoCo still doesn't have a release that supports JDK15

**Comment by lalithsuresh** [comment]
https://github.com/jacoco/jacoco 0.8.6 just got released earlier today.

**Comment by redslapss** [comment]
guys i need help on gradle for jdk15, not found on android studio
