### ISSUE TITLE
When --profile is used, the build output show show a link to the profile at the end.

### ISSUE THREAD

**Issue by jmslau** [gradle/gradle#1354]
When using --profile with Gradle, there is no link directly to the report. It's hard for users who are not familiar with Gradle to find the reports.

### Expected Behavior
The build output show show a link to where the profile report is so it's easy for the user to open it.

### Current Behavior
No link shown in build output.

### Context
While debugging build issues with customers, they couldn't even find the build report. While debugging over chat, it's easy to miscommunicate. Even after I told them the path to the report, they still wasn't able to find it. Eventually they found it, but this type of issue seems easily avoidable. Also, we want to bring more awareness to developers about potential build issues, and this is a step toward the right direction.

### Steps to Reproduce (for bugs)
Invoke gradle with --profile.

### Your Environment
Any

**Comment by eriwen** [comment]
@jmslau Thanks for the issue. I've put this in our backlog to be tackled in one of the next couple sprints.

**Comment by bmuschko** [comment]
PR: https://github.com/gradle/gradle/pull/1424

**Comment by eriwen** [comment]
Closing as complete. This will be in Gradle 3.5. — nice work Ben.

**Comment by jmslau** [comment]
Thanks for doing this guys! This is going to help a ton :)
