### ISSUE TITLE
How can I use Tooling API to get dependency information from one gradle and use them to set up another project.

### ISSUE THREAD

**Issue by QZzcoder** [gradle/gradle#13543]
### Expected Behavior

I have known that I can use module.getDependencies() to parse Gradle and get information about the dependency of my project. But I'd like to set the dependency of a project. There can be  a script which can change the content of build.gradle so that I can build it with updated dependency which has been set in my new build.gradle .

**Comment by ljacomet** [comment]
The tooling API is not designed to have features for modifying Gradle build files.
You can achieve what you want by querying the build dependencies with the tooling API but the modifications will have to be done by your code.
