### ISSUE TITLE
Pre-existing empty output directory may cause incorrect up-to-date checks

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#13554]
### Version
Gradle 6.5

### Step to Reproduce
This issue is hard to reproduce. When it happens, it's something like this:

1. In the first build, task A generates an empty directory. Task B uses the empty directory as one of its input files.
2. Perform some other builds. (This part is why it's hard to reproduce.)
3. Then delete the empty directory (e.g., manually or by running `clean` to delete the entire `build` directory).
4. In the next build, task A is (incorrectly) UP-TO-DATE, and therefore doesn't recreate the empty directory. Task B then fails because its input directory does not exist.

### Workaround
Delete `<project>/.gradle/<gradle-version>/executionHistory/` (or `<project>/.gradle`). Note that `clean` build doesn't help, and the users are stuck with the build error until they delete that Gradle directory.

### Context
This issue was originally reported on AGP issue tracker (without knowing the root cause): http://issuetracker.google.com/142788472. I then came across this bug myself and found that it's probably an issue in Gradle.

### Debugging Process
I've managed to localize the issue to the way Gradle fingerprints empty directories.

In a **correct** build (where in step 4 task A is out-of-date), the fingerprint of the empty directory is:
   - (**c1**) a `SerializableFileCollectionFingerprint` with 1 fingerprint and 1 rootHash after the last execution (when the directory was not deleted yet)
   - (**c2**) an `EmptyCurrentFileCollectionFingerprint` with 0 fingerprints and 0 rootHashes for the current execution (when the directory has been deleted)
   - when comparing these two states, Gradle is able to detect a change (which is correct).

In an **incorrect** build (where in step 4 task A is UP-TO-DATE), the fingerprint of the empty directory is:
  - (**i1**) `FileCollectionFingerprint#EMPTY` with 0 fingerprints and 0 rootHashes for the last execution (when the directory was not deleted yet)
   - (**i2**) is the same as (**c2**)
   - when comparing these two states, Gradle does not detect a change (which is incorrect).

Note that (**c1**) and (**i1**) are read from the data in `<project>.gradle/6.5/executionHistory/` (the relevant code is `FileCollectionFingerprintSerializer#read`), so it seems that this data is somehow corrupted for (**i1**). 

(I see `BTreePersistentIndexedCache` has lots of TODOs, with mentions of "thread safety" and "file corrupt", not sure if it's related.)

**Comment by wolfs** [comment]
@hungvietnguyen It seems like the behavior you describe would happen if the output directory already exists before you first run task A. Then the output directory is not counted as an output produced by task A and task A does not have any outputs.

Deleting the empty directory then doesn't have any effect on the outputs of task A - since Gradle thinks there aren't any.

Can you confirm that this is the reason for the behaviour you are seeing?

**Comment by hungvietnguyen** [comment]
Ah yes, I've just confirmed that is the correct explanation. (Not sure why it was a bit hard to reproduce before.)

I wonder if there is anything Gradle can do to avoid this issue, as I can imagine users deleting `<project>/.gradle` without cleaning their build directory first won't be too uncommon. (I've seen 3 bug reports on this: https://issuetracker.google.com/142788472, https://issuetracker.google.com/158674351, and 1 internal bug.)

**Comment by wolfs** [comment]
Gradle could consider the root directory as always belonging to the task's output. That would mean that the root directory would belong to multiple tasks. That seems to not cause any test failures on our side, and makes sense since the task would create the root directory if it would run.

> as I can imagine users deleting <project>/.gradle without cleaning their build directory first won't be too uncommon.

Do you know why folks are deleting the `.gradle` directory? And when they do so, they need to run a `clean` afterwards.

It shouldn't be necessary to delete the `.gradle` directory. If it is necessary, then it is a bug in Gradle which needs to be fixed.

**Comment by hungvietnguyen** [comment]
Actually, now I've found that this issue doesn't happen when I delete `<project>/.gradle`, it happens only when I delete `<project>/.gradle/<gradle-version>`.

When I delete `<project>/.gradle` (or upgrading the Gradle version), I see that Gradle deletes the existing output directory first before snapshotting (probably by `CleanupStaleOutputsExecuter`, and using `<project>/.gradle/buildOutputCleanup`), and therefore the snapshot is correct.

So everything is still as expected: Deleting `<project>/.gradle` does not cause issues, whereas deleting anything inside `<project>/.gradle` may (understandably) cause issues.

> Do you know why folks are deleting the .gradle directory? And when they do so, they need to run a clean afterwards.

When running into build failures, people try all sorts of things to reset to a clean state. But fortunately, as mentioned above, deleting `.gradle` without running `clean` still works.

> It shouldn't be necessary to delete the .gradle directory. If it is necessary, then it is a bug in Gradle which needs to be fixed.

Yes, I agree. And it turns out that there is no bug.

But note that I didn't mess with `<project>/.gradle` right in the beginning. I ran into this issue first, then I found deleting `<project>/.gradle` fixed the issue, and then I played around with `<project>/.gradle/<gradle-version>/executionHistory` to try to reproduce the issue. It's impossible to find the original cause now---I'll ping this bug if it comes up again.

I think this can be closed, thank you for looking into this!
