### ISSUE TITLE
Class cast exception when GStrings are used with System.getProperty

### ISSUE THREAD

**Issue by sadheeshv** [gradle/gradle#13569]
Summary: 
GString substitution is now working. It works fine with Gradle 6.4.1 and earlier. But it break on Gradle 6.5

Steps to Reproduce
task bugFoo{
    doLast {
        String appCode = "XX"
        println (":app-${appCode}:${System.getProperty('os.name', "${appCode}-gunit")}")
    }
}

 Expected Behavior
Should print ":app-XX:Mac OS X" without any exception

 Current Behavior
It throws following error
"""* Where:
Build file '/Users/svenkatachalam/gw/lab/gosu-java-single-proj/build.gradle' line: 118

* What went wrong:
Execution failed for task ':bugFoo'.
> org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
"""

**Comment by big-guy** [comment]
Thanks @sadheeshv - this looks real.

As a workaround, I think you can remove the extra layer of interpolation:
> println (":app-${appCode}:${System.getProperty('os.name', "${appCode}-gunit")}")

becomes

> println (":app-${appCode}:${System.getProperty('os.name', appCode+"-gunit")}")

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/13585.
