### ISSUE TITLE
Unexpected “Duplicate path” warning in :processFuncTestResources task

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#13578]
### Expected Behavior
I don't see the “Duplicate path” warnings when paths are not in fact duplicated.

### Current Behavior
```
> Task :processFuncTestResources
Copying or archiving duplicate paths with the default duplicates strategy has been deprecated. This is scheduled to be removed in Gradle 7.0. Duplicate path: "testProjects/junit5simple/src/test/java/pitest/test/LibraryJUnit5Test.java". Explicitly set the duplicates strategy to 'DuplicatesStrategy.INCLUDE' if you want to allow duplicate paths. Consult the upgrading guide for further information: https://docs.gradle.org/6.5/userguide/upgrading_version_5.html#implicit_duplicate_strategy_for_copy_or_archive_tasks_has_been_deprecated
Copying or archiving duplicate paths with the default duplicates strategy has been deprecated. This is scheduled to be removed in Gradle 7.0. Duplicate path: "testProjects/junit5simple/build.gradle". Explicitly set the duplicates strategy to 'DuplicatesStrategy.INCLUDE' if you want to allow duplicate paths. Consult the upgrading guide for further information: https://docs.gradle.org/6.5/userguide/upgrading_version_5.html#implicit_duplicate_strategy_for_copy_or_archive_tasks_has_been_deprecated
...
```
Those files are not duplicated. Something causes those files to be detected wrongly.

### Context
I reported it while ago on the [forum](https://discuss.gradle.org/t/unexpected-duplicate-path-warning-in-processfunctestresources-task/35420), but it hasn't got an attention. I wouldn't like to hit it removed in Gradle 7.

After upgrade to Gradle 6.x (tested with 6.3 and 6.5) I see a number of the “Duplicate path” warnings. Those files are not duplicated.

The configuration for the [`funcTest` sourceset](https://github.com/szpak/gradle-pitest-plugin/blob/01c6c5221869d7a75e7e8ef2811132cd17c1b53e/build.gradle#L32-L36):
```
sourceSets {
    funcTest {
        java.srcDir file('src/funcTest/java')
        groovy.srcDir file('src/funcTest/groovy')
        resources.srcDir file('src/funcTest/resources')
    }
}
```
In the `src/funTest/resources` there is a group of test projects:
![image](https://user-images.githubusercontent.com/148013/85587701-4e8a3a80-b642-11ea-9ff0-bbce46f1d0bb.png)

### Steps to Reproduce 
1. Clone https://github.com/szpak/gradle-pitest-plugin/
2. Call `gw :processFuncTestResources  --warning-mode all`

### Your Environment
Gradle 6.3 and 6.5. OpenJDK 14.0.1 by RedHat, Fedora 31.

**Comment by big-guy** [comment]
It's a clumsy error message, but what's happening is you're adding the same paths as the convention:
```
sourceSets {
    funcTest {
        java.srcDir file('src/funcTest/java')
        groovy.srcDir file('src/funcTest/groovy')
        resources.srcDir file('src/funcTest/resources')
    }
}
```

This registers `src/funcTest/resources` as a path twice and that gets used to configure the Copy task.

Try:
```
sourceSets {
    funcTest
}
```

**Comment by lackovic** [comment]
I had the same issue with my `sourceSets`: 

```
$ ./gradlew build :processE2eTestResources
> Configure project :
Linux
> Task :processE2eTestResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processE2eTestResources'.
> Entry application.properties is a duplicate but no duplicate handling strategy has been set. 
Please refer to https://docs.gradle.org/7.0.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

To fix it I deleted from `sourceSets` only the `resources.srcDir` line and the build completed successfully, strangely even after I put the line back! Using Gradle 7.0.2.
