### ISSUE TITLE
platforms not matching external dependencies and artifacts generated by the project

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#13574]
We currently generate a bom file (using the platform plugin) that contains a number of dependencies versions we share with multiple projects. It does contain some dependencies with dynamic versions, i.e. 5.+.
We publish the platform as a bom and then apply it to the `implementation` configuration.
One of our projects using that bom is a multi-module project. One of its subprojects artifacts is contained into the bom. Other subprojects have dependencies on that artifact too, declared into the implementation dependencies with the notation `project('<subproject-path>').
So the situation is like this:
```
externally saved bom in repository -> sets <artifact1:5+> in the dependency management section

<main_project>
|
\-- <subproject1>
|           \- produces <artifact1:5.+>
|
\-- <subproject2>
            \- applies the platform from the bom to the implementation configuration
            \- has a dependency in the form of implementation project(':main_project:subproject1')
```
It all works fine in the project while making new releases, subproject2 keeps taking the latest version of artifact1 which is produced by the build itself.
But we ended up having now to patch a previously released artifact.

### Expected Behavior
We had a later version available in the ivy repository (i.e. `5.100.0`) but were patching an earlier version (i.e. generating `5.80.1`). We expected the project to see that it was building `artifact1 5.80.1` inside `subproject1`. Since the new `artifact1 5.80.1` satisfies the constraint from the bom, and there are no other dependencies that call for that artifact, we'd have expected the build to use `artifact1 5.80.1`.

### Current Behavior
The platform (both enforce and not enforced) seems to always bring in the latest version from the repository and have its version compete with the locally built version.
```
> Task :subproject1:dependencyInsight
com.mycompany:artifact1:5.100.0
   variant "default" [
      org.gradle.status              = integration (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage               = java-api
         org.gradle.category            = library
         org.gradle.dependency.bundling = external
         org.gradle.libraryelements     = classes
         org.gradle.jvm.version         = 8
   ]
   Selection reasons:
      - By constraint
      - By conflict resolution : between versions 5.81.1-dev.0.uncommitted+6c5d973 and 5.100.0
...
com.mycompany:artifact1:5.+ -> 5.100.0
\--- com.mycompany:mybom:1.26.0
     \--- compileClasspath (requested com.mycompany:artifact1:5.+)
```

### Context
We're trying to get the artifact patched, bringing in newer dependencies from the same repository isn't safe.
The problem is quickly fixed by excluding the dependency from the platform.

### Steps to Reproduce 
It's a bit complicated, you need a repository and you need a published artifact.

### Your Environment
Gradle 6.5.
We are using enforced platforms on the project but reproduced the issue even with normal platforms.
All projects are java/scala projects.

**Comment by ljacomet** [comment]
This is actually a feature of Gradle although I understand it does not match what you are trying to achieve.

What you want in this context is `resolutionStrategy.preferProjectModules()`. See [the documentation](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:preferProjectModules()) for details.
