### ISSUE TITLE
:docs:samplesMultiPage and other tasks report "Copying or archiving duplicate paths with the default duplicates strategy has been deprecated."

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13575]
When running `gradle stageDocs` in the Gradle build, I get a lot of `Copying or archiving duplicate paths with the default duplicates strategy has been deprecated.` messages.

This is one of the duplicate paths: `zips/sample_android_application-groovy-dsl.zip`

If I search for the zip, these are the location I find in `subprojects/docs`:
```
build/working/samples/render-samples/zips/sample_android_application-groovy-dsl.zip
build/working/samples/docs/zips/sample_android_application-groovy-dsl.zip
build/docs/samples/zips/sample_android_application-groovy-dsl.zip
build/sample-zips/sample_android_application-groovy-dsl.zip
```

See https://e.grdev.net/s/cdocxixl7gyye/deprecations?details=29&expanded=WyIyOCJd

**Comment by jjohannes** [comment]
This issue has been fixed by now.
