### ISSUE TITLE
Invalid patcher dependency

### ISSUE THREAD

**Issue by lijinhong11** [gradle/gradle#13576]
Executing Gradle task: eclipse
Build info: MCreator 2020.2.14217, 1.14.4, 64-bit, 8083 MB, Windows 10, JVM 1.8.0_232, JAVA_HOME: D:/MCreator/jdk/jre
> Configure project :
New Dep: net.minecraftforge:forge:1.14.4-28.2.3_mapped_snapshot_20190719-1.14.3
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'MCC'.
> Invalid patcher dependency: de.oceanlabs.mcp:mcp_config:1.14.4-20190829.143755@zip
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 12s
BUILD FAILED
Task completed in 12908 milliseconds

**Comment by JLLeitschuh** [comment]
@lijinhong11 Can you provide more context and potentially a build scan for this issue?

**Comment by lijinhong11** [comment]
I didn't see it in the folder of the gradle dependency library 1.14.4-20190829.143755@zip

**Comment by lijinhong11** [comment]
I didn't see the file

**Comment by lijinhong11** [comment]
When I replaced gradle 6.6 Version, his log was like this:
Executing Gradle task: build 
Build info: MCreator 2020.2.14217, 1.12.2, 64-bit, 8083 MB, Windows 10, JVM 1.8.0_232, JAVA_HOME: D:/MCreator/jdk/jre 
Watching the file system is an incubating feature. 
Received 174 file system events since last build 
Virtual file system retained information about 4965 files, 396 directories and 32 missing files since last build 
Dependency verification is an incubating feature. 
> Task :buildSrc:compileJava NO-SOURCE 
> Task :buildSrc:compileGroovy NO-SOURCE 
> Task :buildSrc:processResources NO-SOURCE 
> Task :buildSrc:classes UP-TO-DATE 
> Task :buildSrc:build:compileJava NO-SOURCE 
> Task :buildSrc:binaryCompatibility:extractPluginRequests UP-TO-DATE 
> Task :buildSrc:jar UP-TO-DATE 
> Task :buildSrc:assemble UP-TO-DATE 
> Task :buildSrc:check UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:generatePluginAdapters UP-TO-DATE 
> Task :buildSrc:checkSameDaemonArgs 
> Task :buildSrc:build 
> Task :buildSrc:kotlinDsl:extractPrecompiledScriptPluginPlugins UP-TO-DATE 
> Task :buildSrc:kotlinDsl:generateScriptPluginAdapters UP-TO-DATE 
> Task :buildSrc:versioning:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:kotlinDsl:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:versioning:processResources UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:kotlinDsl:processResources UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:processResources UP-TO-DATE 
> Task :buildSrc:buildPlatform:assemble UP-TO-DATE 
> Task :buildSrc:buildPlatform:check UP-TO-DATE 
> Task :buildSrc:buildPlatform:build UP-TO-DATE 
> Task :buildSrc:cleanup:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:configuration:compileKotlin UP-TO-DATE 
> Task :buildSrc:configuration:compileJava NO-SOURCE 
> Task :buildSrc:configuration:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:configuration:processResources UP-TO-DATE 
> Task :buildSrc:configuration:classes UP-TO-DATE 
> Task :buildSrc:configuration:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:configuration:jar UP-TO-DATE 
> Task :buildSrc:cleanup:processResources UP-TO-DATE 
> Task :buildSrc:integrationTesting:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:integrationTesting:processResources UP-TO-DATE 
> Task :buildSrc:performance:extractPluginRequests UP-TO-DATE 
> Task :buildSrc:performance:generatePluginAdapters UP-TO-DATE 
> Task :buildSrc:packaging:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:packaging:processResources UP-TO-DATE 
> Task :buildSrc:performance:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:performance:processResources UP-TO-DATE 
> Task :buildSrc:docs:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:docs:processResources UP-TO-DATE 
> Task :buildSrc:plugins:extractPrecompiledScriptPluginPlugins UP-TO-DATE 
> Task :buildSrc:plugins:generateScriptPluginAdapters UP-TO-DATE 
> Task :buildSrc:plugins:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:plugins:processResources UP-TO-DATE 
> Task :buildSrc:profiling:extractPrecompiledScriptPluginPlugins UP-TO-DATE 
> Task :buildSrc:profiling:generateScriptPluginAdapters UP-TO-DATE 
> Task :buildSrc:buildquality:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:buildquality:processResources UP-TO-DATE 
> Task :buildSrc:configuration:assemble UP-TO-DATE 
> Task :buildSrc:configuration:check UP-TO-DATE 
> Task :buildSrc:configuration:build UP-TO-DATE 
> Task :buildSrc:ide:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:profiling:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:ide:processResources UP-TO-DATE 
> Task :buildSrc:profiling:processResources UP-TO-DATE 
> Task :buildSrc:uberPlugins:extractPrecompiledScriptPluginPlugins UP-TO-DATE 
> Task :buildSrc:uberPlugins:generateScriptPluginAdapters UP-TO-DATE 
> Task :buildSrc:uberPlugins:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:uberPlugins:processResources UP-TO-DATE 
> Task :buildSrc:build:compileGroovy UP-TO-DATE 
> Task :buildSrc:build:pluginDescriptors UP-TO-DATE 
> Task :buildSrc:build:processResources NO-SOURCE 
> Task :buildSrc:build:classes UP-TO-DATE 
> Task :buildSrc:build:jar UP-TO-DATE 
> Task :buildSrc:build:assemble UP-TO-DATE 
> Task :buildSrc:build:check UP-TO-DATE 
> Task :buildSrc:build:build UP-TO-DATE 
> Task :buildSrc:kotlinDsl:generateExternalPluginSpecBuilders UP-TO-DATE 
> Task :buildSrc:kotlinDsl:compilePluginsBlocks UP-TO-DATE 
> Task :buildSrc:kotlinDsl:generatePrecompiledScriptPluginAccessors UP-TO-DATE 
> Task :buildSrc:kotlinDsl:configurePrecompiledScriptDependenciesResolver 
> Task :buildSrc:kotlinDsl:compileKotlin UP-TO-DATE 
> Task :buildSrc:kotlinDsl:compileJava NO-SOURCE 
> Task :buildSrc:kotlinDsl:classes UP-TO-DATE 
> Task :buildSrc:kotlinDsl:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:kotlinDsl:jar UP-TO-DATE 
> Task :buildSrc:kotlinDsl:assemble UP-TO-DATE 
> Task :buildSrc:kotlinDsl:check UP-TO-DATE 
> Task :buildSrc:kotlinDsl:build UP-TO-DATE 
> Task :buildSrc:ide:compileKotlin UP-TO-DATE 
> Task :buildSrc:ide:compileJava NO-SOURCE 
> Task :buildSrc:cleanup:compileKotlin UP-TO-DATE 
> Task :buildSrc:cleanup:compileJava NO-SOURCE 
> Task :buildSrc:cleanup:compileGroovy NO-SOURCE 
> Task :buildSrc:cleanup:classes UP-TO-DATE 
> Task :buildSrc:cleanup:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:cleanup:jar UP-TO-DATE 
> Task :buildSrc:cleanup:assemble UP-TO-DATE 
> Task :buildSrc:cleanup:check UP-TO-DATE 
> Task :buildSrc:cleanup:build UP-TO-DATE 
> Task :buildSrc:ide:classes UP-TO-DATE 
> Task :buildSrc:ide:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:ide:jar UP-TO-DATE 
> Task :buildSrc:ide:assemble UP-TO-DATE 
> Task :buildSrc:ide:check UP-TO-DATE 
> Task :buildSrc:ide:build UP-TO-DATE 
> Task :buildSrc:versioning:compileKotlin UP-TO-DATE 
> Task :buildSrc:versioning:compileJava NO-SOURCE 
> Task :buildSrc:versioning:classes UP-TO-DATE 
> Task :buildSrc:versioning:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:versioning:jar UP-TO-DATE 
> Task :buildSrc:docs:compileJava NO-SOURCE 
> Task :buildSrc:versioning:assemble UP-TO-DATE 
> Task :buildSrc:versioning:check UP-TO-DATE 
> Task :buildSrc:versioning:build UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:compileKotlin UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:compileJava UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:compileGroovy UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:compileGroovyPlugins UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:classes UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:jar UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:assemble UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:check UP-TO-DATE 
> Task :buildSrc:binaryCompatibility:build UP-TO-DATE 
> Task :buildSrc:docs:compileGroovy UP-TO-DATE 
> Task :buildSrc:docs:classes UP-TO-DATE 
> Task :buildSrc:docs:jar UP-TO-DATE 
> Task :buildSrc:docs:assemble UP-TO-DATE 
> Task :buildSrc:docs:check UP-TO-DATE 
> Task :buildSrc:docs:build UP-TO-DATE 
> Task :buildSrc:packaging:compileKotlin UP-TO-DATE 
> Task :buildSrc:packaging:compileJava NO-SOURCE 
> Task :buildSrc:packaging:classes UP-TO-DATE 
> Task :buildSrc:packaging:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:packaging:jar UP-TO-DATE 
> Task :buildSrc:packaging:assemble UP-TO-DATE 
> Task :buildSrc:packaging:check UP-TO-DATE 
> Task :buildSrc:packaging:build UP-TO-DATE 
> Task :buildSrc:integrationTesting:compileKotlin UP-TO-DATE 
> Task :buildSrc:integrationTesting:compileJava NO-SOURCE 
> Task :buildSrc:integrationTesting:classes UP-TO-DATE 
> Task :buildSrc:integrationTesting:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:integrationTesting:jar UP-TO-DATE 
> Task :buildSrc:integrationTesting:assemble UP-TO-DATE 
> Task :buildSrc:integrationTesting:check UP-TO-DATE 
> Task :buildSrc:integrationTesting:build UP-TO-DATE 
> Task :buildSrc:performance:compileJava UP-TO-DATE 
> Task :buildSrc:performance:compileGroovy UP-TO-DATE 
> Task :buildSrc:performance:compileGroovyPlugins UP-TO-DATE 
> Task :buildSrc:performance:classes UP-TO-DATE 
> Task :buildSrc:performance:jar UP-TO-DATE 
> Task :buildSrc:performance:assemble UP-TO-DATE 
> Task :buildSrc:performance:check UP-TO-DATE 
> Task :buildSrc:performance:build UP-TO-DATE 
> Task :buildSrc:plugins:generateExternalPluginSpecBuilders UP-TO-DATE 
> Task :buildSrc:plugins:compilePluginsBlocks UP-TO-DATE 
> Task :buildSrc:plugins:generatePrecompiledScriptPluginAccessors UP-TO-DATE 
> Task :buildSrc:plugins:configurePrecompiledScriptDependenciesResolver 
> Task :buildSrc:plugins:compileKotlin UP-TO-DATE 
> Task :buildSrc:plugins:compileJava NO-SOURCE 
> Task :buildSrc:plugins:compileGroovy NO-SOURCE 
> Task :buildSrc:plugins:classes UP-TO-DATE 
> Task :buildSrc:plugins:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:plugins:jar UP-TO-DATE 
> Task :buildSrc:plugins:assemble UP-TO-DATE 
> Task :buildSrc:plugins:check UP-TO-DATE 
> Task :buildSrc:plugins:build UP-TO-DATE 
> Task :buildSrc:profiling:generateExternalPluginSpecBuilders UP-TO-DATE 
> Task :buildSrc:profiling:compilePluginsBlocks UP-TO-DATE 
> Task :buildSrc:profiling:generatePrecompiledScriptPluginAccessors UP-TO-DATE 
> Task :buildSrc:profiling:configurePrecompiledScriptDependenciesResolver 
> Task :buildSrc:profiling:compileKotlin UP-TO-DATE 
> Task :buildSrc:profiling:compileJava NO-SOURCE 
> Task :buildSrc:profiling:classes UP-TO-DATE 
> Task :buildSrc:profiling:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:profiling:jar UP-TO-DATE 
> Task :buildSrc:profiling:assemble UP-TO-DATE 
> Task :buildSrc:profiling:check UP-TO-DATE 
> Task :buildSrc:profiling:build UP-TO-DATE 
> Task :buildSrc:buildquality:compileKotlin UP-TO-DATE 
> Task :buildSrc:buildquality:compileJava NO-SOURCE 
> Task :buildSrc:buildquality:classes UP-TO-DATE 
> Task :buildSrc:buildquality:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:buildquality:jar UP-TO-DATE 
> Task :buildSrc:buildquality:assemble UP-TO-DATE 
> Task :buildSrc:buildquality:check UP-TO-DATE 
> Task :buildSrc:buildquality:build UP-TO-DATE 
> Task :buildSrc:uberPlugins:generateExternalPluginSpecBuilders UP-TO-DATE 
> Task :buildSrc:uberPlugins:compilePluginsBlocks UP-TO-DATE 
> Task :buildSrc:uberPlugins:generatePrecompiledScriptPluginAccessors UP-TO-DATE 
> Task :buildSrc:uberPlugins:configurePrecompiledScriptDependenciesResolver 
> Task :buildSrc:uberPlugins:compileKotlin UP-TO-DATE 
> Task :buildSrc:uberPlugins:compileJava NO-SOURCE 
> Task :buildSrc:uberPlugins:classes UP-TO-DATE 
> Task :buildSrc:uberPlugins:inspectClassesForKotlinIC UP-TO-DATE 
> Task :buildSrc:uberPlugins:jar UP-TO-DATE 
> Task :buildSrc:uberPlugins:assemble UP-TO-DATE 
> Task :buildSrc:uberPlugins:check UP-TO-DATE 
> Task :buildSrc:uberPlugins:build UP-TO-DATE 
FAILURE: Build failed with an exception. 
* What went wrong: 
A problem occurred configuring root project 'gradle'. 
> Dependency verification failed for configuration ':classpath' 
  13 artifacts failed verification: 
    - commons-lang3-3.8.1.jar (org.apache.commons:commons-lang3:3.8.1) from repository BintrayJCenter 
    - commons-logging-1.1.3.jar (commons-logging:commons-logging:1.1.3) from repository BintrayJCenter 
    - diff4j-1.2.jar (com.cloudbees:diff4j:1.2) from repository BintrayJCenter 
    - fastcsv-1.0.2.jar (de.siegmar:fastcsv:1.0.2) from repository BintrayJCenter 
    - httpclient-4.3.3.jar (org.apache.httpcomponents:httpclient:4.3.3) from repository BintrayJCenter 
    - javaxdelta-2.0.1.jar (com.nothome:javaxdelta:2.0.1) from repository BintrayJCenter 
    - localizer-1.12.jar (org.jvnet.localizer:localizer:1.12) from repository BintrayJCenter 
    - lzma-java-1.3.jar (com.github.jponge:lzma-java:1.3) from repository BintrayJCenter 
    - maven-artifact-3.6.0.jar (org.apache.maven:maven-artifact:3.6.0) from repository BintrayJCenter 
    - ForgeGradle-3.0.179.jar (net.minecraftforge.gradle:ForgeGradle:3.0.179) from repository maven 
    - artifactural-1.0.12.jar (net.minecraftforge:artifactural:1.0.12) from repository maven 
    - srgutils-0.2.12.jar (net.minecraftforge:srgutils:0.2.12) from repository maven 
    - trove-1.0.2.jar (trove:trove:1.0.2) from repository BintrayJCenter 
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/6.6-20200621220020+0000/userguide/dependency_verification.html#sec:troubleshooting-verification 
   
  Open this report for more details: file:///E:/MCC/build/reports/dependency-verification/at-1593350699279/dependency-verification-report.html 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
BUILD FAILED in 1m 37s 
Received 425 file system events for current build 
Virtual file system retains information about 6476 files, 583 directories and 33 missing files till next build 
BUILD FAILED 
Task completed in 98074 milliseconds

**Comment by lijinhong11** [comment]
E:/MCC/build/reports/dependency-verification/at-1593350699279/dependency-verification-report.html's pictrue

![Dependency verification report - Opera 2020_06_28 下午 09_37_03](https://user-images.githubusercontent.com/62691956/85949143-96cd9380-b987-11ea-8086-74e0f4a1251b.png)
