### ISSUE TITLE
Compile classpath snapshotting should be lenient with broken jars/class files

### ISSUE THREAD

**Issue by melix** [gradle/gradle#1358]
The newly introduced compile classpath snapshotting, which is the root of the performance improvements known as compile avoidance, is not tolerant to broken jars or class files. In practice, it means that if a jar is malformed, or a class file is malformed, then it prevents Gradle from building a project.

### Expected Behavior

Instead of failing, we should log a warning saying that we recognize the error, ignore it, but that it will no longer be supported in Gradle 5.0: we will encourage users to fix broken jars or classes.

### Current Behavior

Upgrading from Gradle 3.3 to 3.4 prevents a project from building if a jar on Java compile classpath is broken (wrong entry, malformed jar file), or a class contained either in a jar file or in a class directory on Java compile classpath is broken. It also means that if the user had _effectively_ used the broken class in the project, the build would fail in any case.

### Context

Several users reported issues with broken jars on classpath since rc1:

- [icu4j contains a broken class file](https://discuss.gradle.org/t/could-not-calculate-the-signature-for-jar-file-icu4j/21452)
- [malformed class file in a jar](https://discuss.gradle.org/t/gradle-3-4-rc-2-is-now-available-for-testing/21483/4?u=bmuschko)

**Comment by oehme** [comment]
This is fixed on the release branch.

**Comment by oehme** [comment]
See #1359
