### ISSUE TITLE
War property problem

### ISSUE THREAD

**Issue by SteveHigham** [gradle/gradle#13581]
I'm executing this code from the build.gradle file to show this poroblem

war {
    doLast {
        war.properties.sort { it.key }.each { println "Prop: $it.key , Value: $it.value" }
    }
}

### Expected Behavior
I should get a sensible list of properties in key value pairs.

### Current Behavior
Some properties are fine (e.g. archiveName) but some are strange (e.g. archiveFileName)
Prop: archiveFileName , Value: task ':MyProject:war' property 'archiveFileName'

### Context
I'm trying to capture the war file name so I can use its value in a generated config file.

### Steps to Reproduce 
See git@github.com:SteveHigham/gradle-defect-example.git

### Your Environment

Build scan URL: https://gradle.com/s/gj5ccywyckaz6

**Comment by jnizet** [comment]
`archiveName` is a `String`. See https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.War.html#org.gradle.api.tasks.bundling.War:archiveName.

`archiveFileName` is a `Property<String>`. See https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.War.html#org.gradle.api.tasks.bundling.War:archiveFileName and https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html.

If you want to acces the actual value of the archive file name, you thus need (for example) `war.archiveFileName.get()`

**Comment by SteveHigham** [comment]
Hi jnizet,

Please don't take this personally but I find this deeply disappointing. I've used Groovy and Gradle for a few years on and off. It is clear that huge effort has gone into making the language and tools intuitive so you don't have to look everything up. You do what seems natural and most of the time it works.

Properties are a great example of this. Java beans shows you how to create getXxx () and setXxx () methods. Groovy simplifies this and allows access via an object.xxx property syntax. However if you override the setters and / or getters they are called so you have no loss of flexibility.

For some time we have had project properties which are natural and easy to use. For example buildDir provides a File reference to the build directory but it can also be used in string interpolation like "$buildDir/subdir/myfile.txt". Now we are introducing properties that can only be referenced by a propertyName.get () syntax. Furthermore when interpreted as a property (e.g. "$archiveFileName") you get what is clearly a debug string. You need to check the documentation and use "${archiveFileName.get()}" instead.

I agree that this is documented, the shame is that you have to go to the documentation as the implementation is inconsistent and unfriendly from a users / developers perspective. Just consider the code to loop through all properties and display their values. You need to check the type of each property and call the appropriate method rather than just relying on a sensible toString () implementation.

Are we moving towards a print("Hello World".get()+"\n"); style syntax? It doesn't feel very groovy!

Kind Regards,

Steve
