### ISSUE TITLE
Gradle Plugin cannot use log4j:log4j:1.2.17 as a dependency

### ISSUE THREAD

**Issue by collenda-bwa** [gradle/gradle#13593]
The generated gradle-api.jar contains log4j 1.x classes which prevents using that library as a dependency in your plugin or any of its dependencies.

### Expected Behavior
Plugin should build and use the correct class.

### Current Behavior
Build fails because the method is unknown:

```
$ gradle build

> Task :compileJava FAILED
C:\Workspaces\BrokenGradle\src\main\java\BrokenGradle\BrokenGradlePlugin.java:19: error: cannot find symbol
                LogManager.exists("");
                          ^
  symbol:   method exists(String)
  location: class LogManager
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

### Context

I'm trying to execute a custom plugin that uses a class from a dependency that includes log4j@v1.2.17 and calls that library's LogManager#exists() method.
Since the generated gradle-api-6.5.jar contains its own LogManager class in org/apache/log4j/LogManager that does not contain that method, a NoSuchMethodError is thrown.
I have not found a way to circumvent this by reordering the classpath or using the Worker API.

### Steps to Reproduce 

see https://github.com/collenda-bwa/gradle-plugin-error

1. Use Gradle 6.5 to init a new plugin project with Java language and Groovy buildscript DSL
2. Add log4j to the implementation configuration
3. use LogManager.exists() in the plugins code
4. Code won't compile

**Comment by ljacomet** [comment]
A plugin running in Gradle is inside the Gradle runtime itself.
While Gradle can clearly improve the situation around logging and logging from plugins in particular, it is unlikely that we will lift this specific limitation soon.
