### ISSUE TITLE
Memory inefficiency in ConsumerVariantMatchResult for very large project.

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#13596]
This was found in the hprof dump filed here: https://issuetracker.google.com/158846149

2,500 module project. Gradle 6.5.

`ConsumerVariantMatchResult` is responsible for wasting ~1.8GB of memory due to ~180K empty list objects (list is empty but the initial size is not zero and it adds up).

The code is initialized with some estimated size, and only used in `ConsumerProvidedVariantFinder.findProducersFor` which uses the square of `variantTransforms.getTransforms().size()`. Looks like this is aggressively allocating too much?

See screenshot:
<img width="1050" alt="Screen Shot 2020-06-25 at 11 32 33 AM" src="https://user-images.githubusercontent.com/3945493/85779067-133a4b00-b6d8-11ea-82b9-701d54785ef0.png">

**Comment by ghale** [comment]
This is related to #13402 which describes a similar (but slightly different) issue with `ConsumerProvidedVariantFinder` in larger AGP builds.

**Comment by ducrohet** [comment]
thanks for that link.
Actually I just realized that the path shows that it's an unmodifiableList so the culprit is the copy constructor that does `this.matches = Collections.unmodifiableList(other.matches);`

This could maybe be easily fixed by checking whether `other.matches` is empty? (unless you do care about it being a read-only wrapper on a list that can change.)
