### ISSUE TITLE
 org.gradle.configureondemand causes build failure in multi module project

### ISSUE THREAD

**Issue by nuhkoca** [gradle/gradle#13602]
### Expected Behavior
When executing `:app:dependencies` in a multi-module project, it should work properly.

### Current Behavior
When executing `:app:dependencies` in a multi-module project, it fails and gives the error below:

```
* What went wrong:
Execution failed for task ':app:dependencies'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > A problem occurred configuring project ':network'.
      > Cannot change dependencies of dependency configuration ':network:classpath' after it has been resolved.
```

### Context
Another department is supposed to release our project and they execute a script to read dependencies. This script calls `app:dependencies` but it causes a failure. It is originating from  `org.gradle.configureondemand=true` in `gradle.properties`. If set it to `false` it works.

### Steps to Reproduce 
1. Create a multi-module project
2. Add other modules into `app`
3. Add  `org.gradle.configureondemand=true` in `gradle.properties`
4. Execute `./gradlew :app:dependencies`

### Your Environment
Build scan URL: https://gradle.com/s/7essvnkj7yfm4

**Comment by gavra0** [comment]
This looks like https://issuetracker.google.com/165821826, which is fixed in AGP 4.1.0-rc01.

**Comment by nuhkoca** [comment]
@gavra0 thanks, great!

**Comment by bmuskalla** [comment]
AGP 4.1.0 has been released and I assume this has been fixed. @nuhkoca please report back if you're still seeing any issues and whether we need to reopen this.

**Comment by nuhkoca** [comment]
@bmuskalla sorry for too late reply, but I can confirm that I am not getting an issue anymore. Thanks for taking care and time on this!
