### ISSUE TITLE
Feature to delete / remove specific dependency

### ISSUE THREAD

**Issue by hanct** [gradle/gradle#13613]
npm (node package manager) has the commnad "npm uninstall <package name>" to remove specific dependency. Does gradle also has one? If not, i would like to suggest having this specific feature in gradle, as I believe it should be a very welcome feature. Other solution I know of is the use of --refresh-dependencies. But i would more of hoping to have a gradle built-in task that intuitively and easily allow us to remove a specific dependency, similar to "npm uninstall"

**Comment by melix** [comment]
May I ask what you want to achieve, what is your use case? Gradle works very differently from NPM. It doesn't "install" dependencies, so it doesn't need to "uninstall" them. It has a cache of dependencies, repository-aware. This cache is cleaned up automatically from time to time from unused dependencies, typically.

**Comment by hanct** [comment]
The use case is that sometimes the libraries downloaded to my development machine could be a lot, so to "reclaim back the disk space", it would be good if we developer can delete those unused libraries.
Also gradle did not "install" dependencies, but still it downloaded them from the web to the harddisk. Hence a good feature would be for gradle to provide a feature to delete/remove the selected dependencies.

**Comment by melix** [comment]
Gradle will automatically prune unused dependencies from its cache: https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_cleanup

**Comment by hanct** [comment]
> Gradle will automatically prune unused dependencies from its cache: https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_cleanup

I read this article. It mentions "Cache Cleanup
Gradle keeps track of which artifacts in the dependency cache are accessed. Using this information, the cache is periodically (at most every 24 hours) scanned for artifacts that have not been used for more than 30 days. Obsolete artifacts are then deleted to ensure the cache does not grow indefinitely."

That mean we need to wait for artifacts to be unused for more than 30days, then it will auto delete it.  So if I need to clear the harddisk for more space, I still have to wait for unused artifacts to stay for more than 30 days.  The thing is why can't Gradle just simply provide us the ability to immediately delete the artifact

**Comment by ljacomet** [comment]
There is no plan to implement a feature like this in Gradle.

The [documentation on sharing the dependency cache](https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_copy) gives indications on the cache structure. You could use that to achieve what you want.
