### ISSUE TITLE
Creating a snap package

### ISSUE THREAD

**Issue by tunix** [gradle/gradle#13615]
### Context

Snap is universal package format that allows users to install gradle through a store or by issuing a simple command. It allows users to switch between different versions of the app as well as alpha/beta packages. Snaps can be used on different Linux distributions.

Currently the official package in Ubuntu archives is old (4.4.1) and users will have to either install it via SDKMAN or download the binary distribution manually. Providing a snap would be beneficial to many users.

All it takes to build a snap package is to create a `snapcraft.yaml` file and use the `snapcraft` tool to build the package. I've already created the file [here](https://github.com/tunix/gradle-snap) and am ready to create a PR.

For information about snapcraft please check [here](https://snapcraft.io/). There is also an active forum [here](https://forum.snapcraft.io/).

**Comment by lacasseio** [comment]
This was requested a while back. Although it's a good idea, it's hard for the team to maintain in practice. My proposal at the time and still is would be a community effort to publish all those different redistribution that focus on common infrastructure and transparency. This way the Gradle team can be involved is required and community member can provide additional integration. Users can also see how each package is built to ensure no malicious intent took place.

The reason why the Ubuntu Gradle version is so old can be attributed to the package process they decided on (building from source). Despite being a great idea, it's hard to build Gradle completely from source (dependency included). It would be best is Ubuntu would simply take the distribution built by Gradle. Some requirements may prevent this approach but the solution should be about finding a compromise that can reuse the effort already accomplished by the Gradle team to release a high-quality distribution.

For Gradle to support this, it's a lot more involved than simply creating a yaml file. It's mostly a question of backend support that needs to be maintained. It would be important to include the data regarding impacted users. "many users" is not actionable. 35M users is actionable. The data would allow for the final say if it's worth the investment.

**Comment by tunix** [comment]
Hi @lacasseio ,

I think snapping gradle's official binary distribution aligns with your perspective (and also Ubuntu's). I think all distributions will eventually move onto a packaging alike.

I understand that it would be hard for gradle team to handle packaging for different systems. I'd like to offer my help if that's possible. I think it'd be great to have a common infrastructure and transparency for not just the snap but for other packaging systems as well. But I'm not sure how I can achieve this. Should I create a topic on the forum to see if there's interest?

Unfortunetely I'm not in the position to mention any numbers as I don't have them. :) I'm just an Ubuntu user and a Java developer who wants easier access to the tools.

**Comment by lacasseio** [comment]
You are right, I feel the right step forward is to create an org, something like gradle-packages, and write some automation code that would query the service.gradle.org for the latest version and execute a package release. I'm sure you can use GitHub action for a free automation. Everything can be release under an open source license and talk about it to get other on board.

**Comment by lacasseio** [comment]
I created this (https://github.com/lacasseio/gradle-packaging) a while back buy didn't get enough traction internal to justify investing time into it. Feel free to use it as a basis for the effort. I'm sure you could get Gradle to mention the effort in the documentation once you at least have the snap package release and hopefully automated.

**Comment by tunix** [comment]
I'll check it and will let you know. Thanks for pointing me to the right direction!

**Comment by tunix** [comment]
Hi @lacasseio ,

gradle snap is successfully published into Snap Store and is now maintained by [snapcrafters github repository](https://github.com/snapcrafters/gradle). I'll be sending PR's for new releases to trigger automated builds (on snapcraft.io) that builds gradle for all supported CPU architectures.

There was a discussion [here](https://forum.snapcraft.io/t/request-for-classic-confinement-for-gradle/18860/) about whether gradle developers would be interested to adopt it but there seems to be no interest at the moment. So they moved the package onto snapcrafters' github account which is kind of safer.

service.gradle.org seems to be inactive? I was trying to figure out whether it's possible to setup some GitHub actions based on it so that I could at least create new issues for new releases or maybe fully automate sending PR's etc. I'm not sure, though, whether it's OK for gradle community to build packages on snapcraft.io's servers.

Just wanted to give an update on this matter. Cheers!

**Comment by elect86** [comment]
Something is wrong.

I explicitly unistalled Gradle and re-installed it again, still the same problem:

> elect@5800x:~$ gradle 
> ERROR: JAVA_HOME is set to an invalid directory: /snap/gradle/120/usr/lib/jvm/default-java
> Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

`JAVA_HOME` seems to be wrongly set from `/snap/gradle/120/meta/snap.yaml`, which contains the following

`      JAVA_HOME: $SNAP/usr/lib/jvm/default-java`

**Comment by tunix** [comment]
Please see this issue at snapcrafters/gradle: https://github.com/snapcrafters/gradle/issues/17

**Comment by donat** [comment]
The https://github.com/snapcrafters organization is maintaining the [Gradle Snap package](https://snapcraft.io/gradle). I think we can close this story as implemented.
