### ISSUE TITLE
Invalid stream header: 1668D9AA

### ISSUE THREAD

**Issue by snattri** [gradle/gradle#13640]
### Expected Behavior
After latest security update of windows, my machine get restarted. I reopened my android project which started showing this error on gradle build start. Same error happening while I am trying to clean & rebuild my project in android studio (version 4.0).

### Current Behavior
I am constantly getting error - ```Cause: invalid stream header: 1668D9AA``` in all of my android projects on gradle build.

### Context
All of my android projects stopped working on my machine.

### Steps to Reproduce 
I am not sure how to reproduce but this is happening in all of my existing projects. I am using windows 10 home edition, Android studio version 4.0 & gradle version 6.1.1.

### Your Environment
Android studio version 4.0 & gradle version 6.1.1.

Here is the detailed log of android studio -
[idea.log](https://github.com/gradle/gradle/files/4853924/idea.log)

**Comment by snattri** [comment]
This error is gone after downgrading gradle version to 5.6.4.

**Comment by bmuskalla** [comment]
@snattri Can you reproduce this with a more recent version (e.g. `6.5`)?

**Comment by ljacomet** [comment]
Closing for lack of answer from original reporter.
