### ISSUE TITLE
"error=7, Argument list too long" still an issue on osx / gradle 6.5

### ISSUE THREAD

**Issue by eboudrant** [gradle/gradle#13642]
Issue #12453 was closed but looks like Gradle 6.5 re-introduced the but. We have several build failed with `Argument list too long` : 

```
* What went wrong:
Execution failed for task ':ui_module:compileDebugKotlin'.
> java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java": error=7, Argument list too long
...
Caused by: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java": error=7, Argument list too long
at org.jetbrains.kotlin.daemon.client.NativePlatformUtilKt.launchProcessWithFallback(NativePlatformUtil.kt:58) |  
  |   | at org.jetbrains.kotlin.daemon.client.NativePlatformUtilKt.launchProcessWithFallback$default(NativePlatformUtil.kt:37) |  
  |   | at org.jetbrains.kotlin.compilerRunner.ReportUtilsKt.runToolInSeparateProcess(reportUtils.kt:81) |  
  |   | at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileOutOfProcess(GradleKotlinCompilerWork.kt:300) |  
  |   | at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemonOrFallbackImpl(GradleKotlinCompilerWork.kt:147) |  
  |   | at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:117) |  
  |   | at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:146) |  
  |   | at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runCompilerAsync(GradleKotlinCompilerRunner.kt:141) |  
  |   | at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunner.runJvmCompilerAsync(GradleKotlinCompilerRunner.kt:81) |  
  |   | at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:449) |  
  |   | at org.jetbrains.kotlin.gradle.tasks.KotlinCompile.callCompilerAsync$kotlin_gradle_plugin(Tasks.kt:359) |  
  |   | at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.executeImpl(Tasks.kt:316) |  
  |   | at org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile.execute(Tasks.kt:288)


```

### Expected Behavior
Build passes

### Current Behavior
Build fails with `org.gradle.api.UncheckedIOException: java.io.IOException: Cannot run program "/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/bin/java": error=7, Argument list too long`

### Context
It is an Android project built from Android Studio.

### Steps to Reproduce 
`./gradlew assembleDebug` in our app.

### Your Environment

Gradle 6.5,Gradle Enterprise plugin 3.3.3,Android Gradle plugin 3.6.3

Build Cache | On |  
-- | -- | --
Configure on demand | On |  
Daemon | On |  
Parallel | On |  
Continue on failure | Off |  
Continuous | Off |  
Dry run | Off |  
Offline | Off |  
Re-run tasks | Off |  
Refresh dependencies | Off |  
Task inputs file capturing | Off |  

Operating system | Mac OS X 10.15.5 |  
-- | -- | --
CPU cores | 16 cores |  
Max Gradle workers | 16 workers |  
Java runtime | Azul OpenJDK Runtime Environment 1.8.0_242-b20 |  
Java VM | Azul OpenJDK 64-Bit Server VM 25.242-b20 (mixed mode) |  
Max JVM memory heap size | 11453 MB |  
Locale | English (United States) |  
Default charset | UTF-8 | 

Total build time	9m 43.761s	 	 
Initialization & configuration	41.944s	 	 
Startup	0.507s	 	 
Settings	1.294s	 	 
Build :buildSrc	16.939s	 	 
Loading projects	0.026s	 	 
Configuration	23.178s	 	 
Execution	9m 1.817s	 	 
Task execution	9m 1.689s	 	 
End of build	0.128s	 	 
Total garbage collection time	20.104s	 	 
Peak heap memory usage		 	 
PS Eden Space	3.55/3.68 GB (96.4%)	 	 
PS Survivor Space	1.16/1.43 GB (81.2%)	 	 
PS Old Gen	5.75/8.59 GB (66.9%)

**Comment by rpalcolea** [comment]
This appears to be a Kotlin issue and not a Gradle one. 

You can follow the issue in https://youtrack.jetbrains.com/issue/KT-34487 

It appears to be fixed in 1.4.M3

**Comment by c4milo** [comment]
is there any known workaround?

**Comment by rpalcolea** [comment]
@c4milo , upgrading to Kotlin 1.4 should fix this

**Comment by jjohannes** [comment]
Closing, as this was a Kotlin issue that is now fixed.
