### ISSUE TITLE
compileOnly doesn't work in ant.taskdef same as in 3.3

### ISSUE THREAD

**Issue by xxBedy** [gradle/gradle#1364]
See attached example to reproduce issue.
We have large project with one module that has sources for custom ant tasks.
Then we use these tasks during build process itself.
These ant task project is defined in compileOnly scope because we don't want package these dependency in distribution jar.
In gradle 3.3 works correctly.
### Expected Behavior

Work same as in 3.3
### Current Behavior

Failed with:
Execution failed for task ':module-app:sayHelloFailed'.
> taskdef class foo.HelloAnt cannot be found
   using the classloader AntClassLoader[]
### Context

Gradle 3.4-rc-2
Build time:   2017-02-06 21:17:28 UTC
Revision:     4a4d6ae7c800239c63561020194df4d7a5e82cd7

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_112 (Oracle Corporation 25.112-b16)
OS:           Mac OS X 10.12.3 x86_64
### Steps to Reproduce (for bugs)

unzip attached file and run: gradle build
[GradleIssue.zip](https://github.com/gradle/gradle/files/760726/GradleIssue.zip)

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
`compileOnly` no longer extends `compile` (that extends relationship was a bug). Please use `compileClasspath` to get "everything needed for compilation" (this includes compile and compileOnly).
