### ISSUE TITLE
Add 'rootProjectDirectory' to 'project.layout' (ProjectLayout)

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#13654]
Currently, you have to do `rootProject.layout.projectDirectory`. Which means you have to access the `rootProject` object first, which we want to discourage on the long run - do not access the state of another project directly.

However, there are use cases where all subprojects need to access a common resource in the file system. For example a `version.txt` in the root folder.

There are other cases in the build logic of the `gradle/gradle` build (search for in `rootProject.layout.projectDirectory` buildSrc).

**Comment by melix** [comment]
Agreed. A typical use case is to have a common "test publish repository" at the root of the build. I don't think this needs to be solved with this issue, but sometimes I think something like "give me the path to the root of the whole invocation", for included builds, would also help. Otherwise you're limited to the scope of the current build.

**Comment by melix** [comment]
Still relevant

**Comment by jjohannes** [comment]
Right now, because this does not exist, I am using this notation:

```
version = providers.fileContents(rootProject.layout.projectDirectory.file("gradle/version.txt")).asText.getOrElse("")
```

Now I am looking at project isolation and then that is no longer allowed. I can do the following instead, but that's quite ugly as the types of `rootDir` and `fileContents` (or similar methods) do not match:

```
version = providers.fileContents(layout.file(provider { File(rootDir,"gradle/version.txt") })).asText.getOrElse("")
```

Any plans to implement this feature or something similar in the context of the project isolation work?

**Comment by alllex** [comment]
In the context of Isolated Projects we are planning to introduce a better API to access the root directory. Having a direct `rootProjectDir` on a `ProjectLayout` is one of the top candidates.

In the meantime, you can already use the new `IsolatedProject` [view API](https://docs.gradle.org/8.8/release-notes.html#:~:text=Isolated%20project%20views) to reach the root directory without breaking the isolation:
```
project.isolated.rootProject.projectDirectory
```

**Comment by alllex** [comment]
After considering the alternatives we settled on exposing `settingsDirectory` on `ProjectLayout`.
-  https://github.com/gradle/gradle/pull/31550

---

It addressed one of the most common use cases: resolving files that should be shared across all projects of a single build, such as linting configs or `version.txt`-style files.

It explicitly does not address other use cases, such as sharing files between a sub-tree of projects or sharing files across multiple builds in a composite build. Those use cases are different and so might be their solutions.
