### ISSUE TITLE
Gradle fails to report plugin with incompatible JDK version

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#13659]
I accidentally built my plugin to target JDK 11. As expected, the build failed when attempting to load it under JDK 8. However, the error states that the plugin could not be found, instead of describing the version mismatch:

![image](https://user-images.githubusercontent.com/2517200/86307432-a0473d80-bbcb-11ea-96ff-fd90137c43fd.png)

The [build scan](https://scans.gradle.com/s/swiawsn26ow3y/build-dependencies?toggled=W1swXSxbMCwwXSxbMCwwLFsxXV0sWzAsMCxbM11dXQ) shows that the plugin was found, but its dependencies were somehow not added to the classpath:

![image](https://user-images.githubusercontent.com/2517200/86307504-c5d44700-bbcb-11ea-9b22-ea6ba67bbc27.png)

Running Gradle under JDK 11 loads the classpath successfully ([build scan](https://scans.gradle.com/s/mrv4h76guir2u/build-dependencies?toggled=W1swXSxbMCwwXSxbMCwwLFsxMThdXSxbMCwwLFsxM11dLFswLDAsWzExOCwxMTldXSxbMCwwLFsxMywxNF1dXQ)):

![image](https://user-images.githubusercontent.com/2517200/86307555-e56b6f80-bbcb-11ea-98b8-2a1d136514db.png)

I could not quite figure out the exact conditions for repro, so I put up the project and a precompiled plugin in a private repo: https://github.com/cesar1000/jdk-11-plugin-dependency.

I repro'ed in the latest nightly, 6.6-20200701220021+0000.

**Comment by melix** [comment]
@cesar1000 the invite for the repro has expired. I tried to reproduce locally in tests but I can't : the error I get always indicates a variant selection problem. Would you mind reissuing an invite?

**Comment by cesar1000** [comment]
Yeah, done! I updated it to the latest nightly, 6.6-20200811230046+0000 (shouldn't that be 6.7?), and it continues to repro.

**Comment by melix** [comment]
Lastest nighty is actually 6.7: https://services.gradle.org/distributions-snapshots/

**Comment by cesar1000** [comment]
Ah I'm dumb and I looked for it in the wrong place :). Let me update.

**Comment by cesar1000** [comment]
Updated! It also repros in the latest nightly.
