### ISSUE TITLE
Gradle 6.5 pulls in optional dependency

### ISSUE THREAD

**Issue by fransflippo** [gradle/gradle#13656]
### Expected Behavior

When adding a dependency on a library, e.g. `org.dom4j:dom4j:2.1.3` that declares an **optional** dependency, that dependency should not become part of any classpath.

### Current Behavior

Adding a dependency on a library, appears to be causing its direct optional dependencies to be included, for example declaring a dependency on `org.dom4j.dom4j:2.1.3` causes its optional dependency `pull-parser:pull-parser:2` to also be added to the classpath. Transitive optional dependencies do not seem to suffer from this problem, for example adding a dependency on `org.hibernate:hibernate-core:5.4.18.Final` which has a dependency on `org.dom4j.dom4j:2.1.3` does **not** cause dom4j's optional dependency `pull-parser:pull-parser:2` to be included.

### Context

I have a unit test that uses Apache POI. My project was explicitly depending on dom4j 2.1.3 because of a CVE in the default version of dom4j (2.1.1) pulled in by the hibernate version I was using (5.4.12.Final) which my project also depends on. 
POI uses Apache XMLBeans which at some point calls `org.xml.sax.XMLReader.setProperty("http://xml.org/sax/properties/lexical-handler", this)`. 

- When pull-parser is the selected SAX implementation, this results in an error as pull-parser does not support this property.
- Without pull-parser on the classpath, the default Xerces parser is used which does not have a problem.

This project built fine on Gradle 5.4 and this unit test ran with no problem. However on Gradle 6.5 because of this issue, the test fails with the pull-parser error regarding the `.../lexical-handler` property described above. It seems the behaviour with respect to optional dependencies changed in Gradle 6 or 6.5. 

I want to use Gradle 6.5 because older versions do work on JDK 14.

### Steps to Reproduce 

Create a project with the following build file:

```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.hibernate:hibernate-core:5.4.18.Final'
}
```

Running `./gradlew dependencyInsight --dependency pull-parser --configuration runtimeClasspath` shows:

```
No dependencies matching given input were found in configuration ':runtimeClasspath'
```

which is expected.

Now add `implementation 'org.dom4j:dom4j:2.1.3'` to the `dependencies` section and run `./gradlew dependencyInsight --dependency pull-parser --configuration runtimeClasspath` again. Now the output is:

```
pull-parser:pull-parser:2
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 14
   ]

pull-parser:pull-parser:2
\--- org.dom4j:dom4j:2.1.3
     +--- runtimeClasspath
     \--- org.hibernate:hibernate-core:5.4.18.Final
          \--- runtimeClasspath

(*) - dependencies omitted (listed previously)
```

`pull-parser` is on the classpath, even though the [dom4j 2.1.3 POM](https://repo1.maven.org/maven2/org/dom4j/dom4j/2.1.3/dom4j-2.1.3.pom) declares it as `optional`.

### Your Environment
Build scan URL **with dom4j dependency in `build.gradle`**: https://gradle.com/s/3fzeseouehmk4
Build scan URL **without dom4j dependency in `build.gradle`**: https://gradle.com/s/jmbkfm27tulu2
(Oddly enough, neither mention pull-parser).

**Comment by fransflippo** [comment]
I've created a quick project that shows the actual pull-parser error when using POI.
[gradle-13656.zip](https://github.com/gradle/gradle/files/4860244/gradle-13656.zip)

Just unzip and run

```
./gradlew build
java -jar build/libs/gradle-optional-dependencies-1.0-SNAPSHOT.jar
```

Remove the dom4j dependency from the `build.gradle` and recompile and you won't get the error.

**Comment by melix** [comment]
The bug is actually in dom4j: they published invalid [Gradle Module Metadata](https://repo1.maven.org/maven2/org/dom4j/dom4j/2.1.3/dom4j-2.1.3.module). Gradle prefers Gradle Module Metadata over POM.

The reason for this bug is probably because they are manually tweaking the POM file to make dependencies optional, instead of relying on the [built-in feature](https://docs.gradle.org/current/userguide/feature_variants.html) of Gradle.

I would suggest you open a bug report to them so that they can fix their module metadata.

Because all their dependencies are optional, you can actually fix this by applying a rule:

```groovy
dependencies {
   components {
       withModule('org.dom4j:dom4j', ClearDependencies)
   }
}

class ClearDependencies implements ComponentMetadataRule {
   void execute(ComponentMetadataContext context) {
       context.details.allVariants { withDependencies { clear() } }
   }
}
```
```

**Comment by fransflippo** [comment]
https://github.com/dom4j/dom4j/issues/99 raised with dom4j.
