### ISSUE TITLE
Add a (working) "edit on GitHub page" link on all documentation pages

### ISSUE THREAD

**Issue by LouisCAD** [gradle/gradle#13660]
### Context

If found a little room for improvement while browsing the documentation ([this page](https://docs.gradle.org/current/userguide/custom_tasks.html), for instance), and I wanted to suggest a modification as a PR.

Not having to search the repo each time I want to submit improvement suggestions would make me contribute more.

_Additional note: I could find it thanks to GitHub code search: [here is the PR](https://github.com/gradle/gradle/pull/13661)._

**Comment by LouisCAD** [comment]
😔

**Comment by lkasso** [comment]
We don't plan to make additional changes for this issue and it will be closed.

We now have the Gradle documentation located in the "platforms" section of our repo.

Additionally, we have new contributor guidelines and a proper doc README to address how to make changes.

Users are expected to be able to confidently find the page they want to make changes to using their IDE search, command line search, or Github search.
