### ISSUE TITLE
Restore default excludes from the configuration cache

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13665]
Ant's default excludes affect Gradle's up-to-date checking and file walking behaviour. They are currently used from `org.apache.tools.ant.DirectoryScanner.getDefaultExcludes`.

Our current suggestion is to change the default excludes very early in the build, so best in `settings.gradle`, if you want to have your build using them. Even that does not necessarily work well right now, see https://github.com/gradle/gradle/issues/2986.

### Expected Behavior
When default excludes have been changed in `settings.gradle`, a new daemon which has a configuration cache hit should use the same default excludes.

### Current Behavior
Configuration caching does not take default excludes into account.

**Comment by bamboo** [comment]
This is still relevant.

**Comment by erichaagdev** [comment]
Is there a known/recommended workaround for this? I've been working in the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) project that has many `.gitignore` files in their test resources directory. Following [the current recommendation](https://docs.gradle.org/current/userguide/working_with_files.html#sec:file_trees) of adding `DirectoryScanner.removeDefaultExclude("**/.gitignore")` to `settings.gradle.kts` breaks the configuration cache on subsequent runs.
