### ISSUE TITLE
RuntimeException: "Could not create parent directory for lock file" when running with `systemd-run`

### ISSUE THREAD

**Issue by piegamesde** [gradle/gradle#13663]
### Expected Behavior

It builds just fine, without errors, just like outside of the sandbox.

### Current Behavior

```
Exception in thread "main" java.lang.RuntimeException: Could not create parent directory for lock file /.gradle/wrapper/dists/gradle-6.3-bin/8tpu6egwsccjzp10c1jckl0rx/gradle-6.3-bin.zip.lck
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Finished with result: exit-code
```

### Context

I packaged my application built with Gradle for Arch Linux. However building it fails when some sandboxing options are enabled (running the build with DynamicUsers using `systemd-run`).

### Steps to Reproduce 

**Method A**

1. `git clone https://github.com/Minecraft-Technik-Wiki/BlockMap`
2. `cd BlockMap`
3. `sudo systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -E HOME=/tmp -p WorkingDirectory=$PWD bash -c "GRADLE_USER_HOME=$PWD/gradle;$PWD/gradlew --no-daemon"`

This may be reproducible with other Gradle repositories, but I know that the application "JabRef" (which is packaged in a similar way) does not have this issue, so there's no guarantee.

**Method B**

See https://github.com/actionless/pikaur/issues/498

### Your Environment

```
------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14.0.1-internal (Oracle Corporation 14.0.1-internal+0-adhoc..jdk14u-jdk-14.0.1-ga)
OS:           Linux 5.7.4-arch1-1 amd64
```

**Comment by LockedThread** [comment]
Still occurring on gradle 7.0.2

**Comment by ljacomet** [comment]
Can you try passing `-g $PWD/gradle` instead of the inline env var? Which I believe is ignored because of the `;` between it and the invocation of Gradle.
