### ISSUE TITLE
Jacoco plugin need a way to pass a source encoding

### ISSUE THREAD

**Issue by hidekatsu-izuno** [gradle/gradle#13666]
### Expected Behavior
JacocoTestReport task use java source code as the input. I need to specify a encoding of their source code.

For instance:
```
jacocoTestReport {
    sourceEncoding = 'UTF-8'
}
```

[Jacoco Ant Task](https://www.eclemma.org/jacoco/trunk/doc/ant.html#report) already has this feature that is a encoding attribute of sourcefiles element.

### Current Behavior
JacocoTestReport always assumes that the encoding of their source code is system property "file.encoding".

### Context
I use gradle on Windows 10 in Japan. Normally, the default "file.encoding" is Windows-31J (MS932).
But most user use UTF-8 as source code encoding. So we need this feature.

**Comment by bmuskalla** [comment]
This sounds reasonable. If anyone is interested in contributing this, it will likely need to pass the source encoding to the [respective `sourcefiles` object](https://github.com/gradle/gradle/blob/master/subprojects/jacoco/src/main/java/org/gradle/internal/jacoco/AbstractAntJacocoReport.java#L74).
