### ISSUE TITLE
Configuration cache should allow undeclared access to all default system properties provided by the current JVM

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13676]
Currently the configuration cache allows undeclared access to a hardcoded list of system properties.
This issue is about allowing undeclared access to all default system properties provided by the current JVM instead.

This would include JVM specific default system properties such as the ones that allow to detect the JVM bitness for example (`sun.arch.data.model` or `com.ibm.vm.bitmode`).

### Expected Behavior
Undeclared access to default system properties provided by the current JVM are allowed.

### Current Behavior
Accessing default system properties provided by the current JVM are reported as a problem if they are not in the hardcoded list of allowed properties.

### Context
Several builds and Gradle plugins read such properties, either directly or via some libraries.

**Comment by eskatos** [comment]
We could use the JVM probe infrastructure for this. I guess we can then collect the default system properties but we will need a set of filtered out system properties, e.g. `java.io.tmpdir`.

**Comment by bamboo** [comment]
Closing as fixed since Gradle no longer reports problems for system properties read at configuration time.
