### ISSUE TITLE
Allow to override default expiry age for cached artefacts

### ISSUE THREAD

**Issue by vkolomeyko** [gradle/gradle#13684]
At times it is necessary to override default cache expiry timeout to make use of previously downloaded artefacts.

### Expected Behavior
To have a `-D` property to be able to override default expiry timeout.

### Current Behavior
Impossible to override current hardcoded interval set to 1 day in: `org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultCachePolicy`

### Context
Second day in a row we are facing stability issues with repository: https://repo.gradle.org
Anytime Gradle build performed it is failing with:
```
 > Failed to list versions for net.minidev:json-smart.
    > Unable to load Maven meta-data from https://repo.gradle.org/gradle/libs-releases/net/minidev/json-smart/maven-metadata.xml.
       > Could not HEAD 'https://repo.gradle.org/gradle/libs-releases/net/minidev/json-smart/maven-metadata.xml'.
          > Read timed out
```
The thing is that library in question is available in the local cache, however it is marked as expired by Gradle:
```
15:04:15.196 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'net.minidev:json-smart:2.3' in 'MavenRepo'
15:04:15.196 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'net.minidev:json-smart:2.3' in 'BintrayJCenter'
15:04:15.196 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Version listing in dynamic revision cache is expired: will perform fresh resolve of 'net.minidev:json-smart:[1.3.1,2.3]' in 'maven4'
```
Library-wise nothing has changed in the project for the last day and whilst remote resource is not available, it would be good to have a workaround and be able to specify custom timeout such that local cache artefacts will still be used.

**Comment by melix** [comment]
You can use `resolutionStrategy.cacheDynamicVersionsFor` or [dependency locking](https://docs.gradle.org/current/userguide/dependency_locking.html) for this purpose.

**Comment by vkolomeyko** [comment]
Thanks @melix for your prompt reply!
Indeed `resolutionStrategy.cacheDynamicVersionsFor` works quite nicely.
