### ISSUE TITLE
A copy of a configuration fails to resolve a dependency on its containing project

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#13680]
### Expected Behavior

When a configuration is created with a call to `copyRecursive()` from another configuration, it should produce the same resolution results as the original configuration, unless changes are made to it that prevent it from doing so.

### Current Behavior

A configuration created with `copyRecursive()` fails to resolve a direct or transitive dependency on its containing project, reporting the following (here, `lib` is the containing project, and `libtests` is a project that brings a transitive dependency on `lib`):

```
> Could not resolve all task dependencies for configuration ':lib:testCompileClasspathCopy'.
   > Could not resolve project :lib.
     Required by:
         project :lib > project :libtests
      > No matching configuration of project :lib was found. The consumer was configured to find an API of a library, and its dependencies declared externally but:
          - None of the consumable configurations have attributes.
```

### Context
This issue arises in the Kotlin Multiplatform plugin that, when resolving dependencies, creates a copy of a configuration to resolve it with additional dependencies (thus making sure that the versions are consistent and the original configuration is unmodified). In the Kotlin issue tracker, see: [KT-39037](https://youtrack.jetbrains.com/issue/KT-39037)

### Steps to Reproduce 
Checkout the project [`h0tk3y/gradle-self-dependency-issue-repro`](https://github.com/h0tk3y/gradle-self-dependency-issue-repro) and build it. It will fail.

Or, in a clean project `foo`, setup dependencies in a way that a project depends on itself. One simple and realistic way to do this is to have a `testImplementation` dependency on another project `bar` which in turn has an `api` dependency on `foo`.

Then copy the configuration that contains such a dependency with `copyRecursive()` and try to resolve it or ensure that it is resolved during a build:

```
val testCompileClasspath by configurations
val copy = testCompileClasspath.copyRecursive()
sourceSets["test"].compileClasspath = copy
```

**Comment by melix** [comment]
This isn't a bug but the expected behavior, as stated in the javadocs. In general we would advice against using `copyRecursive`, as it wouldn't do in general what you'd expect.

A workaround is to do this:

```kotlin
val testCompileClasspath by configurations
val copy = configurations.testCompileClasspath.copy()
testCompileClasspath.extendsFrom.forEach(copy::extendsFrom)
```
