### ISSUE TITLE
"chosen compiler did not support incremental annotation processing" when called from TestKit

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle#13681]
### Expected Behavior
Incremental annotation processing works in TestKit the same as in a regular build.

### Current Behavior
When run through TestKit, build reports:
```
Full recompilation is required because the chosen compiler did not support incremental annotation processing.
```
when a class has changed.

Also, but this is a minor change, when a source file is added, it says
```
Incremental compilation of 0 classes completed in 0.062 secs.
```
when it previously said (Gradle in 6.4.1)
```
Incremental compilation of 1 classes completed in 0.062 secs.
```

### Context

I was updating https://github.com/tbroyer/gradle-incap-helper to Gradle 6.5.1, and `DynamicIncrementalProcessorIntegrationTest` started failing. It runs 3 builds of the same project successively through TestKit (without specifying a Gradle version, so using the current one) after making small changes to the project source code, and checks for specific logs in the output.

I tried with `withGradleVersion("6.4.1")` and the test passed. I then reverted to Gradle 6.4.1 and tried with `withGradleVersion("6.5")` (could have tried with 6.5.1 too) and the test failed again.

So:
| Gradle Version | `withGradleVersion` | Result |
| ------------------- | -------------------------- | :---------: |
| 6.5.1                | *(none)*                    | FAIL   |
| 6.5.1                | 6.4.1                        | PASS |
| 6.4.1                | *(none)*                   | PASS |
| 6.4.1                | 6.5                           | FAIL   |

### Steps to Reproduce 

Clone https://github.com/tbroyer/gradle-incap-helper and checkout tag `v0.3`, then edit `integTest/src/test/kotlin/net/ltgt/gradle/incap/integTest/DynamicIncrementalProcessorIntegrationTest.kt`, and run the build with
```
./gradlew :integTest:test --tests DynamicIncrementalProcessorIntegrationTest
```

I couldn't reproduce with https://github.com/gwtproject/gwt-places, at tag `v1.0.0-RC1`, modifying `processor/src/funcTest/java/org/gwtproject/place/impl/PlaceHistoryMapperGeneratorTest.java`, or adding a source file, and running `./gradlew :processor:compileFuncTestJava`.

### Your Environment

Build scan URL: https://scans.gradle.com/s/5o26e3x3dfkwi

This build scan corresponds to https://github.com/tbroyer/gradle-incap-helper at tag `v0.3` with the following diff applied. That diff also enables build scans for the successive TestKit-driven builds:
1. https://scans.gradle.com/s/z7v3f75hsalm6 (works as expected, clean build)
2. https://scans.gradle.com/s/tutzcmv3eus66 (added source file, shows `Incremental compilation of 0 classes` rather than `Incremental compilation of 1 classes`)
3. https://scans.gradle.com/s/tkisyruuyms64 (modified source file, shows `Full recompilation is required because the chosen compiler did not support incremental annotation processing.`)

Well, actually, the `--info` output is not present in those build scans, strangely, but is there in the *parent* build scan, where I used `testLogging.showStandardStreams = true` to redirect them to standard output.

<details>
<summary>Diff for build scan</summary>

```diff
diff --git a/integTest/build.gradle.kts b/integTest/build.gradle.kts
index 6aaf06b..d12ccd7 100644
--- a/integTest/build.gradle.kts
+++ b/integTest/build.gradle.kts
@@ -45,5 +45,7 @@ tasks {
         systemProperty("version", rootProject.version.toString())
 
         dependsOn("publishLibPublicationToTestRepository", "publishProcessorPublicationToTestRepository")
+
+        testLogging.showStandardStreams = true
     }
 }
diff --git a/integTest/src/test/kotlin/net/ltgt/gradle/incap/integTest/DynamicIncrementalProcessorIntegrationTest.kt b/integTest/src/test/kotlin/net/ltgt/gradle/incap/integTest/DynamicIncrementalProcessorIntegrationTest.kt
index 78cfda6..bdad681 100644
--- a/integTest/src/test/kotlin/net/ltgt/gradle/incap/integTest/DynamicIncrementalProcessorIntegrationTest.kt
+++ b/integTest/src/test/kotlin/net/ltgt/gradle/incap/integTest/DynamicIncrementalProcessorIntegrationTest.kt
@@ -53,7 +53,7 @@ class DynamicIncrementalProcessorIntegrationTest {
         with(compileJava()) {
             // then
             assertThat(output).doesNotContainMatch("Full recompilation is required ")
-            assertThat(output).contains("Incremental compilation of 1 classes completed")
+            //assertThat(output).contains("Incremental compilation of 1 classes completed")
         }
 
         // when
@@ -72,7 +72,7 @@ class DynamicIncrementalProcessorIntegrationTest {
             assertThat(output).doesNotContainMatch("Full recompilation is required because .* is not incremental")
 
             // For some reason, second compilation counts 2 classes rather than 1,
-            assertThat(output).contains("Incremental compilation of 2 classes completed")
+            //assertThat(output).contains("Incremental compilation of 2 classes completed")
             // …but this is not the other source file (probably the generated class?)
             assertThat(output).doesNotContain("src/main/java/test/AnnotatedClass.java")
         }
@@ -81,6 +81,16 @@ class DynamicIncrementalProcessorIntegrationTest {
     private fun setupProject() {
         testProjectDir.newFile("settings.gradle.kts").writeText(
             """
+            plugins {
+                id("com.gradle.enterprise").version("3.3.4")
+            }
+            gradleEnterprise {
+                buildScan {
+                    termsOfServiceUrl = "https://gradle.com/terms-of-service"
+                    termsOfServiceAgree = "yes"
+                }
+            }
+
             include(":processor")
             """.trimIndent()
         )
@@ -188,7 +198,9 @@ class DynamicIncrementalProcessorIntegrationTest {
     }
 
     private fun compileJava() = GradleRunner.create()
+        .withGradleVersion("6.5")
         .withProjectDir(testProjectDir.root)
-        .withArguments("--info", "compileJava")
+        .withArguments("--info", "compileJava", "--scan")
+        .forwardOutput()
         .build()
 }
```

</details>

**Comment by big-guy** [comment]
@ljacomet @melix I think this might be related to the source -> class name mapping changes in 6.5.

**Comment by jjustinic** [comment]
I don't believe this behavior is limited to TestKit, but the exact changes to reproduce seem to vary between users. Another report here: https://discuss.gradle.org/t/full-compiletestjava-run-when-only-one-test-class-changed/36741

**Comment by asodja** [comment]
+1 on this one. We have one big legacy module with 1500+ Java classes and full-recompilation is needed every second run. So +20s every second run if you modify it. We had to switch back to Gradle 6.4.1 from Gradle 6.6. We are using lombok.

I guess we learned a lessons: don't have big modules :).

Does this: https://github.com/gradle/gradle/pull/14109 fix it?

**Comment by mschaaf** [comment]
> I don't believe this behavior is limited to executing through TestKit, but the exact changes to reproduce seem to vary between users/environments. Another seemingly related report here: https://discuss.gradle.org/t/full-compiletestjava-run-when-only-one-test-class-changed/36741

Gradle version 6.6.1 fixed the issue for us.

**Comment by tbroyer** [comment]
I confirm that it fixes my use-case as well, so it probably was related to https://github.com/gradle/gradle/issues/14280

**Comment by tbroyer** [comment]
https://travis-ci.com/github/tbroyer/gradle-incap-helper/builds/181641160
