### ISSUE TITLE
Calling `configuration.dependencies.addAllLater(project.provider { ... })` results in a ClassCastException

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#13700]
### Expected Behavior

A call to `addAllLater(project.provider { listOf(...) })` adds the items lazily evaluated by the provider to the collection. 

### Current Behavior

A `ClassCastException` is thrown:

```
Cause 5: java.lang.ClassCastException: org.gradle.api.internal.provider.DefaultProvider cannot be cast to org.gradle.api.internal.provider.CollectionProviderInternal
        at org.gradle.api.internal.DefaultDomainObjectCollection.addAllLater(DefaultDomainObjectCollection.java:296)
        at org.gradle.api.internal.DelegatingDomainObjectSet.addAllLater(DelegatingDomainObjectSet.java:105)
        ...
```

### Steps to Reproduce 

For example, call `addLater` with a `Provider` constructed as `project.provider { ... }` on a  `Configuration`'s `dependencies`. 

### Your Environment

Gradle 6.5

**Comment by melix** [comment]
I agree it would be nice to support a list of things. We're kind of blocked by type safety constraints here, because generic type support in providers would then prevent us from telling what kind of provider is expected...

**Comment by lacasseio** [comment]
@h0tk3y You should be able to work around this issue by bouncing through `objects.listProperty(<type>).value(listOf or providers {})`.

@melix The workaround would gives a list with the correct type.

**Comment by h0tk3y** [comment]
Thanks, the workaround works for me.
