### ISSUE TITLE
gradle-module-metadata spec 1.0 and 1.1 have identical examples

### ISSUE THREAD

**Issue by cgruber** [gradle/gradle#13717]
The module specifications have two versions 1.0 and 1.1 (also listed as "latest"). 

The [example file of 1.1](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-1.0-specification.md) is identical to the [example in 1.0](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-1.0-specification.md), offering no difference highlighting the changes between the specification versions. 

### Context
I am implementing an improvement to [maven-archeologist](http://github.com/square/maven-archeologist) to support fetching and parsing gradle module metadata, so repository resolving/fetching client code can make use of the metadata (e.g. [bazel maven repository](http://github.com/square/bazel_maven_repository) ). As such, I'm relying on these specification documents to ensure I obtain the correct format and semantic interpretation.  Seeing examples that highlight the difference can illustrate, and fully flesh out the parsing.

**Comment by bmuskalla** [comment]
@ljacomet I think we should also highlight changes to the GMM spec in the release/upgrade notes
