### ISSUE TITLE
Task is mistakenly up-to-date with configuration cache

### ISSUE THREAD

**Issue by melix** [gradle/gradle#13718]
With the following script:

```groovy
interface Injected {
    @javax.inject.Inject FileSystemOperations getFs() 
}

def layout = project.layout

tasks.register('someTask') {
    def destination = project.providers.systemProperty('someDestination')
    def injected = project.objects.newInstance(Injected)
    inputs.dir('source')
    outputs.dir(destination)
    doLast {
        injected.fs.copy { 
            from 'source'
            into destination
        }
    }
}
```

and an _empty_ `source` directory, the behavior with and without the configuration cache is different:

_Without_ the configuration cache, running:

`gw someTask -DsomeDestination=build/bar`

creates `build/bar` then running:

`gw someTask -DsomeDestination=build/baz`

creates `build/baz`.

However _with_ the configuration cache, the second build will be up-to-date and will _not_ create the `baz` directory.

Adding a file in `sources` fixes the problem.

### Expected Behavior

Behavior should be consistent between configuration cache and no configuration cache.

**Comment by eskatos** [comment]
This is fixed in Gradle 7.4 since the system property change is now properly detected, closing
