### ISSUE TITLE
Play plugin uses deprecated APIs

### ISSUE THREAD

**Issue by iNikem** [gradle/gradle#13722]
I use `id "org.gradle.playframework" version "0.9"` with Gradle 6.5

### Expected Behavior
As seen from https://scans.gradle.com/s/rlut2gh3j56ci/deprecations?expanded=WyI0NCIsIjMiXQ#3 it uses deprecated APIs which results in Gradle warnings during the build.

### Current Behavior
No warnings :)

**Comment by bjornvester** [comment]
I believe this has already been reported here: https://github.com/gradle/playframework/issues/114.

**Comment by iNikem** [comment]
With PRs open for 7 months :(
