### ISSUE TITLE
Configuration to scope mappings are lost when accessing a MavenResolver's pom at the "wrong" time

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#1373]
### Expected Behavior

A `MavenResolver`'s pom should use all of the mappings configured on the project's `Conf2ScopeMappings`, irrespective of when it's first accessed.

### Current Behavior

The first time a `MavenResolver`'s pom is accessed it's configured with new `Conf2ScopeMappings` that are a snapshot of the project's `Conf2ScopeMappings`. Subsequent changes to the project's `Conf2ScopeMappings` are then not available during pom generation.

### Context

@rwinch and I are trying to figure out how to get our [propdeps](https://github.com/spring-gradle-plugins/propdeps-plugin) and [dependency management](https://github.com/spring-gradle-plugins/dependency-management-plugin) plugins to work reliably with each other and any other plugins that customise the configuration to scope mappings.

The Maven portion of the propdeps plugins configures custom mappings and customises the pom. The dependency management plugin just customises the pom. As things stand, if the dependency management plugin goes first, the propdeps plugin's custom mappings are lost and, as a result, dependencies are missing from the generated pom. A more detailed description of this behaviour is available [here](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/149).

It appears that I can work around the problem by wrapping the logic that configures the `Upload` task in an `afterEvaluate` block. To be sure of reliably working together, it looks like all plugins that access a `MavenResolver`'s pom would have to do the same. Ideally, this wouldn't be necessary. If it is necessary, then it would be welcome if the javadoc of `MavenResolver.getPom()` contained a warning about the side-effects of accessing the pom.

### Steps to Reproduce (for bugs)

The following `build.gradle` script:

```groovy
apply plugin: 'java'
apply plugin: 'maven'

configurations {
	another
}

tasks.withType(Upload) { upload ->
	upload.repositories.withType(MavenResolver) { mavenResolver ->
		mavenResolver.pom
	}
}

conf2ScopeMappings.addMapping(1000, project.configurations.another, "compile")

dependencies {
	another "commons-logging:commons-logging:1.2"
}
```

Reproduces the problem:

```groovy
$ gradle clean install -q
$ cat build/poms/pom-default.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId></groupId>
  <artifactId>brittle-conf-mapping</artifactId>
  <version>unspecified</version>
</project>
```

Note that the `commons-logging:commons-logging` dependency is missing from the pom.

If the configuration of the `Upload` task and the `conf2ScopeMappings` are swapped around:

```
apply plugin: 'java'
apply plugin: 'maven'

configurations {
	another
}

conf2ScopeMappings.addMapping(1000, project.configurations.another, "compile")

tasks.withType(Upload) { upload ->
	upload.repositories.withType(MavenResolver) { mavenResolver ->
		mavenResolver.pom
	}
}

dependencies {
	another "commons-logging:commons-logging:1.2"
}
```

Then the problem does not occur:

```
$ gradle clean install -q
$ cat build/poms/pom-default.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId></groupId>
  <artifactId>brittle-conf-mapping</artifactId>
  <version>unspecified</version>
  <dependencies>
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.2</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

Note that the `commons-logging:commons-logging` dependency is now present in the pom.

### Your Environment

I don't believe this problem is environment-specific. I am running on macOS with Java 8 and Gradle 3.3. The problem also occurs with Gradle 2.14.1. I haven't tested other versions.

**Comment by bigdaz** [comment]
The `maven` plugin (together with the core `Upload` task) are being replaced by the `maven-publish` plugin. As such, we don't plan on making changes to improve the (now legacy) `Conf2ScopeMapping`. 
Expect to see this type deprecated in Gradle 6.x, for possible removal in Gradle 7.0.
