### ISSUE TITLE
Rename `Provider.getOrElse(T)` to `orElse(T)`

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#13733]
`Provider` has some strong similarities with `java.util.Optional`, and that similarity is helpful for users discovering `Provider`. There is an unnecessary dissimilarity between the two types:

* `Optional` has `orElse(T)` to return the given value as fallback,
* `Provider` has `getOrElse(T)` instead.

Another reason to do this is that `Optional` has another useful method that we could have on `Provider`: `orElseGet(Supplier<T>)`. If we did that, though (which I think we absolutely should), we would end up with both `Provider.getOrElse()` and `Provider.orElseGet()`, another unnecessarily confusing situation.

So let's rename `Provider.getOrElse()` to `orElse()`, and add `orElseGet()` while we are at it! We can keep `getOrElse()` as a deprecated method for a long time to avoid breaking existing code.

**Comment by lptr** [comment]
I guess it would be a worthwhile exercise to check the Java functional types and see if there's more useful methods we could replicate in our `Provider` infrastructure.

**Comment by melix** [comment]
Although I agree with the reasons why you'd like to change, this is going to p* off our early adopters. I think we should commit on stability of APIs, even if they are incubating.

**Comment by lptr** [comment]
I see we already have `Provider.orElse()` returning another `Provider` (which is similar to `Optional.or()`)...

**Comment by lptr** [comment]
Maybe it's not too late. I mean, we are going to carry these APIs with us for a long time. It would make a lot of sense to also upgrade methods taking a `Transformer` to use a `java.util.Function` instead, too. I wouldn't mind a custom type so much, but `Transformer` has its generic parameters backwards, which confuses me every single time.

**Comment by melix** [comment]
I totally agree with that (`Function` vs `Transformer`). However I've been myself in the situation where incubating APIs break, which forces your users to upgrade to latest Gradle to get your plugin working, which then isn't compatible with another plugin using the same incubating APIs in a lower version... This is extremely painful.

**Comment by lptr** [comment]
That is definitely how things work today, and simply flipping `Provider.orElse(T)` to return `T` instead of `Provider<T>` would break a lot of people's plugins, and builds, and in general would put people in a very inconvenient position, again. And I fully agree that we shouldn't do that.

But breaking builds and not changing anything are hardly the only two options we have. We have so many other ways to address a change like this! We can alter classes while loading them, we can provide proxy classes to provide backwards compatibility, we can load different variants of a plugin for different Gradle versions etc.

We could also think about how to better ensure that people rely on incubating APIs more reliably(?). We could for example require that plugins opt-in to using `@Incubating` stuff (same with internal APIs), and then they the opted-in plugins would be highlighted as unstable themselves in build scans, wouldn't work in strict mode etc.

I'm sure we can improve the process to allow for some improvement, some flexibility, if we put our minds to it.

**Comment by lptr** [comment]
For example, if we knew which Gradle version a plugin was compiled against, we could find any that was built against, say, Gradle 6.6 or earlier, and replace all calls in the bytecode to `Provider.orElse(x)` with `Provider.map((_) -> x)` or something like that. Yeah, if you mixed code compiled against different versions of Gradle, it wouldn't work, and there would be some other issues I'm sure. But it would work for _most_ people, which is a lot better than what we have today. And we would have a way to improve our APIs as long as we could add these shims.

**Comment by CristianGM** [comment]
Can't you simply leave the old method hidden with a Deprecated annotation and the replaceWith?
(I'm thinking on Kotlin https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-deprecated/ )

It would fail from the IDE if you try to use it, work for compiled code and provide an auto fix.

**Comment by CristianGM** [comment]
Ouch https://github.com/gradle/gradle/issues/13733#issuecomment-656036099
Having already orElse (at least this one is from 5.6 ) makes it a bigger issue that I don't know how to fix without annoying everyone.

**Comment by lacasseio** [comment]
I agree with @lptr. The issue is at runtime and plugins targeting multiple version. I would hope the Gradle team consider what is the simplest for the plugin authors vs the simplest for the build tool. Even if we mention some API are incubating, plugin authors always, I mean *always* have to rely. Take for example native. All of it was incubating for ever yet everyone building native had to rely on them. At every release, when it was under heavy development, something broke. Not pleasant and especially impossible to write plugins for that kind of behavior. The community is important for Gradle and a flexible Gradle is important for the future.

I like the idea for Gradle to shim older APIs. If you have a good idea, we can work with the [Gradle Plugin Toolbox](https://github.com/gradle-plugins/toolbox) to add the information in a consumables way for Gradle inside the metadata. Then you can work out the Gradle decoration with this data.

**Comment by lptr** [comment]
We might be able to address this in the foreseeable future.

**Comment by jbartok** [comment]
Won't happen.
