### ISSUE TITLE
ProviderFactory should support reading all `systemProperties` 

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#13730]
While looking into [Configuration Cache - Undeclared reading of system properties](https://docs.gradle.org/6.5.1/userguide/configuration_cache.html#undeclared_sys_prop_read) I found that there is no way to read al properties in a safe manner.

It is recommended to use 

```
def enabled = providers.systemProperty("SOME_Property_VAR").forUseAtConfigurationTime().present
```

However, we have cases where we read all system  for reporting in Gradle plugins. Example build file:

```
apply plugin: MyPlugin

class MyPlugin implements Plugin<Project> {
    static final String OVERRIDE_PROPERTY_PREFIX = 'override.'

    @Override
    void apply(Project project) {
        def overrideProperties = System.properties.findAll { it.key.startsWith(OVERRIDE_PROPERTY_PREFIX) }
        overrideProperties.collectEntries { key, value -> [key - OVERRIDE_PROPERTY_PREFIX, value] }
    }
}
```

When `System.properties` is invoked, it produces several configuration cache warnings and fails the build:

```
44 configuration cache problems were found.
- unknown location: read system property 'java.runtime.name' from class 'MyPlugin'
  See https://docs.gradle.org/6.5.1/userguide/configuration_cache.html#undeclared_sys_prop_read
  See https://docs.gradle.org/6.5.1/userguide/configuration_cache.html#undeclared_sys_prop_read
- unknown location: read system property 'java.vm.vendor' from class 'MyPlugin'
``` 

Another use case: https://github.com/nebula-plugins/gradle-metrics-plugin/blob/28b59df6d4ffc5538ce7e62ebd9087b0f909b65f/src/main/java/nebula/plugin/metrics/model/Info.java#L51

I couldn't find anything related to read all system properties in nightly docs also: https://docs.gradle.org/nightly/userguide/configuration_cache.html

Since there are cases where reporting multiple properties by prefix or just not knowing all potential properties is quite common, are there plans to add something to `ProviderFactory` to enable this?

**Comment by adammurdoch** [comment]
We're quite reluctant to add a way to access all of the system properties, as this will make all of the system properties inputs to the configuration cache entry and so limit reuse of the cache entry. This will be an easy way for plugin authors to accidentally kill the effectiveness of the configuration cache.

Instead, it would be better to add something like a method to access all system properties whose name starts with a given (non-empty) prefix.

**Comment by eskatos** [comment]
Closing as won't fix.

See https://github.com/gradle/gradle/issues/13819 about reading a controlled subset of system properties.
