### ISSUE TITLE
Add a Provider to check is file exist during configuration

### ISSUE THREAD

**Issue by CristianGM** [gradle/gradle#13738]
### Expected Behavior
I need to check if a directory exists to enable a feature from my plugin, but if I do that configuration cache won't know if it changes.
I expect something similar to Provider.fileContents 

### Current Behavior
It doesn't exist so I'm doing:
```
    project.plugins.withType<LibraryPlugin> {
        val extension = project.extensions.getByName("android") as LibraryExtension
        extension.onVariants {
            androidTest {
                enabled = file("$projectDir/src/androidTest").exists()
                    || buildType?.let { file("$projectDir/src/androidTest${it.capitalize()}").exists() } ?: false
                    || file("$projectDir/src/androidTest${flavorName.capitalize()}").exists()
                    || buildType?.let { file("$projectDir/src/androidTest${flavorName.capitalize()}${it.capitalize()}").exists() } ?: false
            }
        }
    }
```
it works, but once cached changes won't be noticed by gradle

### Context
AGP adds tasks for androidTests even if there is no test code at all. I tried disabling the tasks but as you know it doesn't remove all the tasks they depend on.

When we run: `./gradlew assembleDebugAndroidTest` it runs on all the android modules of the app, and even if most tasks are cached, just downloading and unpaking all the files is a big overhead.

**Comment by ljacomet** [comment]
With the evolution of configuration caching, it should track file existence checks at configuration time and then consider those files' presence as an input
Closing this as fixed, anchoring in Gradle 8.1 which made CC stable.
