### ISSUE TITLE
Stackoverflow visiting file collections referencing themselves

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13745]
### Expected Behavior

No stackoverflow

### Current Behavior

Visiting file collections referencing themselves can cause stackoverflows

### Context

Trying to update the wrapper on `release` produces such stackoverflow.
* https://builds.gradle.org/buildConfiguration/Gradle_Check_Quick_1_bucket45/36478702?buildTab=overview
* https://ge.gradle.org/s/7grbrnmrjrayq/failure?expanded-stacktrace=0&focused-stack-frame=0-0

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/13757
