### ISSUE TITLE
Unexpected character added when reading property from gradle.properties

### ISSUE THREAD

**Issue by tvolkov** [gradle/gradle#13741]
I have a couple of properties stored in my GRADLE_USER_HOME/gradle.properties I have a simple task which reads and prints them. One of the properties contains the '£' character. When I run the task I see that gradle adds the 'Â' character right before the '£'. I have no idea why is it happening and how to fix it. I tried setting encoding to utf8 using different options but none of them work.

The code of the task is as simple as
```
task printProps {
    doLast {
        println nexusPassword
    }
}
```

and I run it by `./gradlew printProps`.

Hope somebody helps to shed some light on that. Thanks.

### Expected Behavior
in gradle.properties:
nexusPassword=$£
should print to console
$£

### Current Behavior
in gradle.properties:
nexusPassword=$£
actually prints this:
$Â£

### Context

I'm trying to read username and password from gradle.properties to use them to authorise with nexus
But in case of my password which contains '£' character gradle fails to read it correctly.
### Steps to Reproduce 

1. clone the repo https://github.com/tvolkov/gradle-properties
2. add this property to  your GRADLE_USER_HOME/gradle.properties `nexusPassword=$£`
3. run `./gradlew printProps` and see what it prints
### Your Environment

Build scan URL: https://gradle.com/s/ljtyakx2n76mu

**Comment by jnizet** [comment]
Standard .properties files are supposed to be encoded in ISO-8859-1, not in UTF-8. Make sure to configure your editor to use the ISO-8859-1 (A.K.A. latin1) encoding, and then re-type those properties. £ is a valid latin1 character, but for some more exotic characters that are not supported by ISO-8859-1, you'll need to use escape sequences such as \u03a9.

**Comment by bmuskalla** [comment]
See the answer above. If you still believe this is an issue, it would be great to see a reproducer. Let me know if you can still reproduce this or create a new issue.

**Comment by bmuskalla** [comment]
And thanks @jnizet for answering :)
