### ISSUE TITLE
to many open files on project with a lot of files

### ISSUE THREAD

**Issue by TomDePauw** [gradle/gradle#1374]
I am using osx, our project has a lot of non java files, and i can run gradle lint fine a couple of times.
But when running nebula-plugins/gradle-lint-plugin a couple of times more i get :

> Execution failed for task ':lintGradle'.
> > java.nio.file.FileSystemException: /Volumes/work/code/git-java/core/build/classes/main/com/.../PositionGroupDTO.class: Too many open files

if i keep running ./gradlew deploy
the error occurs before gradlelint is run, thats why i think its gradle issue and not gradle lint.

> A problem occurred evaluating root project 'projectname'.
> > /Volumes/work/code/git-java/integration/sql/clear_junit.sql (Too many open files)

**Comment by bmuschko** [comment]
You might want to open an issue with the Gradle Lint plugin directly. It sounds to me as if the logic that reads the files doesn't close a resource properly.

**Comment by bmuschko** [comment]
@TomDePauw Did you have a chance to check in with the author of the Lint plugin?

**Comment by TomDePauw** [comment]
Thanks for reminding, i opened an issue.

**Comment by bmuschko** [comment]
Thanks for creating the [issue](https://github.com/nebula-plugins/gradle-lint-plugin/issues/91). I am going to close this issue for now. We can reopen the issue if you determine that the issue lies in Gradle core.
