### ISSUE TITLE
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0

### ISSUE THREAD

**Issue by oschanger** [gradle/gradle#13763]
I meet same problem https://github.com/gradle/gradle/issues/10032 , but this issue closed without fix.
In our project, we can't change jdk version to jdk10+.
I think we can add default compile time in gradle generated jar to fix this problem, 
in this way we are able to not depend on jdk version.
There is a 'bazel' fix way:
https://github.com/protocolbuffers/protobuf/blob/4426cb573356c5ff710bff8ac8a1170baac7dcf0/src/google/protobuf/compiler/zip_writer.cc#L75
https://github.com/bazelbuild/bazel/issues/6173

**Comment by oschanger** [comment]
May be call ZipEntry.setTime() or ZipEntry.getLastModifiedTime() in ZipPacker.java can fix this problem.
After fix, the class time should not look like this:
_jar tvf class.jar_ 
  1372 **Thu Jan 01 08:00:00 CST 1970** xxxxxxxxx$1.class
   .....

**Comment by bmuskalla** [comment]
We don't plan to fix this at this point. It only affects JDK 9 (not 8 or 10+).
