### ISSUE TITLE
Default to compileClasspath configuration in DependencyInsightReportTask

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#1376]
### Expected Behavior
'dependencyInsight' task should provide a working default when user does not provide `--configuration` option

### Current Behavior
The task prints

    No dependencies matching given input were found in configuration ':compile'

### Steps to Reproduce (for bugs)
- Write a project using `java-library` plugin
- Declare `implementation 'org.slf4j:slf4j-api:1.7.0'`
- Run `gradle dependencyInsight --dependency slf4j-api`

### Context
`DependencyInsightReportTask.configuration` defaults to `compile`. However, `compile` configuration should be empty for properly written projects using `java-library`. 

### Your Environment
Gradle 3.4-rc-2

I think the default should be changed to `compileClasspath`. This works fine with both `java` and `java-library` and is the closest equivalent of the old `compile` configuration.

**Comment by eriwen** [comment]
Thanks for the well written issue @pkubowicz! Would you consider submitting a PR for this?

**Comment by bmuschko** [comment]
@melix Does the proposal sound reasonable to you?

**Comment by oehme** [comment]
Thanks for fixing this @pkubowicz !
