### ISSUE TITLE
Check what gets watched from the Maven local repository

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#13768]
We seem to have some unexpected behavior around artifacts found in Maven's local cache. We should check what happens wrt file system watching when:

1) `mavenLocal()` is not configured as a repository, but our magical lookup finds an artifact there
2) `mavenLocal()` is configured as a repository

---
cc: @gradle/execution

**Comment by wolfs** [comment]
I asked the dependency management team what happens with the artifacts in case 1) and 2):
1. The artifacts are copied into Gradle's dependency cache.
2. The artifacts aren't copied into Gradle's dependency cache. The same is true for any other local Maven, Ivy or file repository. Moreover, the dependency management engine doesn't cache the metadata for local Maven and Ivy repositories. We should probably handle local Maven, Ivy and file repositories the same as a declared `mavenLocal()` repository.

**Comment by lptr** [comment]
In which case do artifacts get copied, when `mavenLocal()` is declared or not?

**Comment by wolfs** [comment]
The 1) and 2) are for your cases 1) and 2) from the issue description: The artifact is only copied to the artifact cache, when `mavenLocal()` is not declared.

**Comment by lptr** [comment]
1. When we copy artifacts to our own dependency cache (with potentially changed contents), do we invalidate the corresponding parts of the VFS?

2. Should we automatically watch the root of any declared Maven, Ivy and file repository?

**Comment by wolfs** [comment]
The location of artifacts in our own dependency cache is always dependent on the contents. So we never change existing files in the dependency cache, we only add new files. That means there is nothing to invalidate in the VFS.

It sounds like a good idea to watch the roots of local Maven, Ivy and file repositories, if there are any. We should handle them probably in a similar way to project root directories.
