### ISSUE TITLE
Cannot infer types of arguments of closures like those for `tasks.withType` in Groovy

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#13779]
There is a type inference problem with several of Gradle's closure callbacks used in `build.gradle` files, because many closures are defined without the `ClosureParams` or `DelegatesTo` annotation in interfaces, for example this one:

https://github.com/gradle/gradle/blob/71f41e1ea985dc8b696cd4a0486ff6d2054bb97e/subprojects/core-api/src/main/java/org/gradle/api/DomainObjectCollection.java#L84

Because of it, you cannot type:

```groovy
tasks.withType(JacocoReport) { reports.xml.enabled true }
```

Well you can, and it would work, but because IntellIJ IDEA does not know what `reports` is, you don't have IntelliSense (code completion, proper syntax highlighting). So you have to change it to the awkward:

```groovy
tasks.withType(JacocoReport) { JacocoReport task -> task.reports.xml.enabled true }
```

Of course I could have mentioned the Task Configuration Avoidance API way, still the same problem arises:

```groovy
tasks.withType(JacocoReport).configureEach { reports.xml.enabled true }
```

Where again you would have to explicitly type the closure argument:

```groovy
tasks.withType(JacocoReport).configureEach { JacocoReport task -> task.reports.xml.enabled true }
```

And *it can get worse* if you need to perform function calls like:

```groovy
tasks.withType(JacocoReport).configureEach { callMyMethodOn it }
```

Because then IDEA may complain that `it` needs a cast to `JacocoReport`...

Why I'm asking for this? Because Groovy can be such a great language, if used correctly, sadly it's quite misunderstood. It could do so much with inferred types, its conciseness is excellent, but only if we implement our interfaces well enough. We lose a lot of Groovy's advantages by mistakes like this. And then no wonder why people want to move to the Kotlin DSL instead...

BTW, I've seen issue #2309, that may be something to keep in mind when finding a fix for this problem.

**Comment by ov7a** [comment]
Sorry for the late reply.

This should be partially fixed by:
* https://github.com/gradle/gradle/pull/20614

The remaining parts are in
* https://github.com/gradle/gradle/issues/28104

Please add a comment to #28104 if there are new cases of that issue.
