### ISSUE TITLE
VersionComparator doesn't understand versions like '1.0.0.RELEASE'

### ISSUE THREAD

**Issue by Petikoch** [gradle/gradle#1378]
There are some projects like the `io.spring.dependency-management` plugin with their own version scheme and versions like `1.0.0.RELEASE` or `1.0.0.RC2`, see https://plugins.gradle.org/plugin/io.spring.dependency-management for examples.

As discussed in https://discuss.gradle.org/t/wrong-version-comparison-for-maven-affecting-spring/11066 by @bigdaz `RELEASE` wasn't and isn't supported by Gradle. Despite the fact that "latest version resolvement" doesn't work properly in such cases, this leads to issues like https://github.com/ben-manes/gradle-versions-plugin/issues/140 in @ben-manes `gradle-versions-plugin`.

See the last two lines in the following test:

`DefaultVersionComparatorTest` 

    def "gives some special treatment to 'dev', 'rc', and 'final' qualifiers"() {
        expect:
        compare(smaller, larger) < 0
        compare(larger, smaller) > 0
        compare(smaller, smaller) == 0
        compare(larger, larger) == 0

        where:
        smaller     | larger
        "1.0-dev-1" | "1.0"
        "1.0-dev-1" | "1.0-dev-2"
        "1.0-rc-1"  | "1.0"
        "1.0-rc-1"  | "1.0-rc-2"
        "1.0-dev-1" | "1.0-xx-1"
        "1.0-xx-1"  | "1.0-rc-1"
        "1.0-final" | "1.0"
        "1.0-dev-1" | "1.0-rc-1"
        "1.0-rc-1"  | "1.0-final"
        "1.0-dev-1" | "1.0-final"
        '1.0.0.RC1'  |'1.0.0.RC2'      // supported 
        '1.0.0.RC2'  |'1.0.0.RELEASE'  // not supported (yet)
    }

**Comment by eriwen** [comment]
@Petikoch Thanks for the great background. This seemed like a quick fix so I just went ahead and tried it: https://github.com/gradle/gradle/pull/1384 

Please let me know if you think that won't work for some reason.

**Comment by Petikoch** [comment]
Thanks @eriwen, looks great, IMHO.
