### ISSUE TITLE
Prompt user for credentials when credentials aren't provided via environment

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#13780]
As a continuation of the credentials story...

### Expected Behavior
When using a Credentials provider and credentials aren't found in the environment, Gradle should prompt the user.

### Current Behavior
When using a Credentials provider and credentials aren't found in the environment, Gradle fails and says it cannot find the credentials.

**Comment by lacasseio** [comment]
I'm sure it's implied but it should fail on CI or basically anytime no terminal is attached.

**Comment by jbartok** [comment]
Not in scope atm.
