### ISSUE TITLE
Error when applying 'idea' plugin to projects with duplicate names

### ISSUE THREAD

**Issue by mark-vieira** [gradle/gradle#1379]
### Expected Behavior
When apply the 'idea' plugin to projects with duplicate names, the plugin should consider the project parent for name deduplication regardless of whether the parent project has the 'idea' plugin applied or not.

### Current Behavior
Currently, when projects with duplicate names have the 'idea' plugin applied, but their parent projects do not, they are both considered "root" projects and therefore Gradle throws an error attempting to make project names unique.

### Context
This issue was reported on the forums: https://discuss.gradle.org/t/idea-plugin-bug/21525

### Steps to Reproduce (for bugs)
You can easily reproduce via the following settings.gradle file.

https://gist.github.com/mark-vieira/6e41d02788c6a76baef28d5dc72a6157

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/l52amnj6rrwyu?_ga=1.110771845.1873743488.1426104094#failure

**Comment by little-fish** [comment]
It's still happening in Gradle 7.2. Can it be reopened?
