### ISSUE TITLE
Eclipse plugin does not use the sourceSets with fewest excludes

### ISSUE THREAD

**Issue by donat** [gradle/gradle#1381]
Volker Belkin's report from Bugzilla ([source](https://bugs.eclipse.org/bugs/show_bug.cgi?id=512021))

Our sourceSets look like (simplified):

    sourceSets {
        main {
            java {
                srcDir 'src'
            }
        }
        javascriptCompress {
           resources {
               srcDir 'src'
               include '**/viewer/**/*.js'
               include '**/viewer/*.js'
          }
        }
    }

This results in a .classpath:

    <?xml version="1.0" encoding="UTF-8"?>
    <classpath>
        <classpathentry including="**/viewer/**/*.js|**/viewer/*.js" kind="src" path="src"/>

We have try to as first and as last sourceSets follow
 
    eclipseClasspath {
        java {
            srcDir 'src'
        }
    }

But it does not change any. This means the order of declaration is not important.

A workaround is:

    eclipse.classpath.file.whenMerged { classpath ->
                classpath.entries { entry ->
                    if ( entry.kind == 'src' ) {
                        entry.includes = []
                        entry.excludes = []
                    }
                }
    }

See also at: https://discuss.gradle.org/t/buildship-does-not-use-the-sourcesets-with-fewest-excludes/21535

**Comment by bmuschko** [comment]
@donat Is this issue solely related to Buildship? Should this issue rather be on https://github.com/gradle/buildship/issues?

**Comment by donat** [comment]
No, it's a problem in Gradle core, only the title is misleading. Let me adjust it.
