### ISSUE TITLE
Buildscript dependencies have bad handling of pom files

### ISSUE THREAD

**Issue by jskovjyskebankdk** [gradle/gradle#13816]
### Expected Behavior

I have a custom gradle plugin that includes org.cyclonedx:cyclonedx-gradle-plugin as a dependency.
And tailors some of its plugins from java code in my plugin.

My plugin applies the cyclonedx plugin.

### Current Behavior

When my plugin is activated, it causes 6.6RC1 to explode: [gradle-6.6RC1-bug.txt](https://github.com/gradle/gradle/files/4930912/gradle-6.6RC1-bug.txt)

### Context

Using 6.6RC1 fails. It works with 6.5.1

The problem appears to be just including the cyclonedx dependency in the buildscript classpath.
I do not know what they look like - it may actually be some bad POM. But "it used to work"(tm)

### Steps to Reproduce 

A simple build file containing just this causes the problem:

````
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
 	  classpath "org.cyclonedx:cyclonedx-gradle-plugin:1.1.3"
    }
}
````

Just starting the gradle wrapper causes the failure.

### Your Environment
Build scan URL: https://scans.gradle.com/s/ds5dlykbnupua

**Comment by eskatos** [comment]
Thanks for the report @jskovjyskebankdk

Some instrumentation of the build logic classpath fails on a broken jar
https://scans.gradle.com/s/ds5dlykbnupua/failure?expanded-stacktrace=0-1&focused-stack-frame=0-1-1

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/13841
