### ISSUE TITLE
Provide a configuration cache friendly way of looking up a subset of system properties and environment variables

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#13819]
Gradle build configuration cache does not allow a generic way of looking up a set of System properties as build configuration in put. At the elasticsearch build, we currently pass all system properties starting with `tests.` to the test task system properties in a generic way. 
 

### Expected Behavior
Provide a way to use all, or better just a subset of system properties as build configuration input. 

E.g `providers.systemProperties.filter(name -> name.startsWith("test."))`

### Current Behavior

The user can only lookup system properties explicitly one by one by their names. by using `getProviders().systemProperty('name')`. This is not useable in a scenario where I want to use a generic subset of system properties as in put for my build (e.g. everything prefixed with `test.` to pass down to my test tasks. 

### Context

When testing 6.6-rc-1 configuration cache with the elasticsearch master https://github.com/elastic/elasticsearch I stepped into the problem described above when running `./gradlew clean precommit --configuration-cache`

**Comment by rpalcolea** [comment]
related to https://github.com/gradle/gradle/issues/13730 :) 

Looking forward to see this introduced 👍

**Comment by bmuskalla** [comment]
The flyway plugin does something similar as it [tries to pass all](https://github.com/flyway/flyway/blob/master/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L886) `flyway.` properties along.

**Comment by eskatos** [comment]
The `gradle/gradle` build itself does something similar with environment variables at
https://github.com/gradle/gradle/blob/d0929974b3c47843e58ab21bebf78ef335f55049/build-logic/jvm/src/main/kotlin/gradlebuild/propagated-env-variables.kt#L81

It could be reworked to query a subset of environment variables if that feature was implemented.

**Comment by eskatos** [comment]
FWIW, the `gradle/gradle` build now uses an explicit list of environment variables instead of querying all of them. When possible this should be the preferred approach.

There are use cases described above for which it is not possible though and make this issue a valid request.
