### ISSUE TITLE
Ability to reuse services when using configuration cache

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#13815]
In order to reuse existing services in `gradle` or `project` scope in combination with the configuration cache, one has to either move the services to the build tree scope or add them to the `codecs.kt`. This [introduces a dependency](https://github.com/gradle/gradle/commit/9c126d77ccbb499249c7a8351228b5b794473cfd) from the configuration cache to all other modules which should be avoided.

**Comment by adammurdoch** [comment]
Do you have an example? It's not clear what you mean by "reuse existing services".

**Comment by bmuskalla** [comment]
Sorry if this wasn't clear what I meant. I tried to use an existing service (`JavaCompilerFactory`) in another service (with project scope) but can't as it tries to serialize the service. It would be great if I could use the `JavaCompilerFactory` without further ceremony.

**Comment by adammurdoch** [comment]
You can just attach `@ServiceScope` to the service and the configuration cache serialisation will recognise it as a service and serialize it correctly.

**Comment by adammurdoch** [comment]
I think we can close this.
