### ISSUE TITLE
Junit 5 tag not working with Gradle 6.5.1

### ISSUE THREAD

**Issue by shrikant606** [gradle/gradle#13810]
Hi All, 
I am trying to learn JUnit 5, my Gradle version is Gradle 6.5.1
java version is openjdk version "11.0.7" 2020-04-14
OS ubuntu 18.04.4.

```
public class FruitCalculator {
    public int addFruit(int fruit1, int fruit2) {
        return fruit1 + fruit2;
    }
    public int subFruit(int fruit1, int fruit2) {
        return fruit1 - fruit2;
    }
}

```
```
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
public class FruitCalculatorTest {
    @Test
    @Tag("add")
    void addFruitTestTag1() {
        System.out.println("FruitCalculatorTest.addFruitTestTag1");
        FruitCalculator fruitCalculator = new FruitCalculator();
        assertEquals(2, fruitCalculator.addFruit(1, 1), "1 fruit + 1 fruit is 2 fruit");
    }
    @Test
    @Tag("sub")
    void subFruitTestTag1() {
        System.out.println("FruitCalculatorTest.subFruitTestTag1");
        FruitCalculator fruitCalculator = new FruitCalculator();
        assertEquals(1, fruitCalculator.subFruit(2, 1), "2 fruit - 1 fruit is 1 fruit");
    }
}

```

```
plugins {
    id 'java'
}
group 'org.example'
version '1.0-SNAPSHOT'
repositories {
    mavenCentral()
}
dependencies {
    testImplementation('org.junit.jupiter:junit-jupiter:5.6.2')
    testRuntimeOnly('org.junit.jupiter:junit-jupiter-engine:5.6.2')
}
test {
    useJUnitPlatform {
        includeTags 'add'
        excludeTags 'sub'
    }
}

```
1-> @ tag is not working. if I run using cmd or IntelliJ, it's running all 4 test cases.

2 -> in cmd -> gradle clean build test printing no output whether the test is passed or failed.

```
~junit5$ gradle clean build test
BUILD SUCCESSFUL in 1s
5 actionable tasks: 5 executed
```
even the System.out is also not printing.

**Comment by jnizet** [comment]
1. If you run the tests using IntelliJ, the gradle test task configuration is irrelevant. You need to run the tests using gradle for the gradle test task configuration to be taken into account. You can use gradle from IntelliJ by selecting the test task in the gradle tools window and executing it, or by configuring IntelliJ to run the tests using Gradle instead of its own test runner (by opening "Preferences", then searching for "gradle", and then select "Gradle" in the select box "Run tests using:".

2. That's expected. The test task generates an HTML report (under build/reports/tests/test), which lists all the tests and their output. The gradle output says "BUILD SUCCESSFUL", so the tests passed. If a test had failed, then the build would have failed and you would have an error in the console signalling it, such as:

```
> Task :test FAILED

FruitCalculatorTest > addFruitTestTag1() FAILED
    org.opentest4j.AssertionFailedError at FruitCalculatorTest.java:13

1 test completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/jb/tmp/fruit/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by soloturn** [comment]
in maven it is easy to exclude tests which have the tag "slow" on the command line with:
```
mvn clean install '-Dgroups=!slow'
```
what is the equivalent on gradle? currently i put it into the build.gradle.kts file which is not so flexible (kotlin, not groovy):

```
tasks.test {
  useJUnitPlatform {
    // gradle-5.6.1 not yet allows passing this as parameter, so exclude it
    excludeTags("slow")
    includeEngines("junit-jupiter")
    includeEngines("junit-vintage")
  }
}

tasks.register<Test>("slowTests") {
  useJUnitPlatform {
    includeTags("slow")
  }
}
}
```

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on discuss.gradle.org or stackoverflow.com where to get answers by the community of Gradle users.

You can pass any property you want [from the CLI to your build scripts](https://docs.gradle.org/current/userguide/build_environment.html) as well as [excluding specific tasks from running](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:excluding_tasks_from_the_command_line) with the -x flag `./gradlew check -x slowTests` (
