### ISSUE TITLE
Discard messages from standard out/error source if they become a bottleneck 

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1382]
A frequent source for OutOfMemoryExceptions and hanging workers (see #1377) seems to be an overload of messages printed to the standard streams through extensive logging. This may often be caused by badly/ill configured loggers.

### Expected Behavior
Gradle should do something the user can live or work with. E.g.: issue an error saying something like: _Too much messages originating from X, discarding further messages until X terminated. Consider A, B, or C to avoid this situation._

### Current Behavior
- Daemon hangs with OOME, workers hang because of unresponsive daemon
- Addressing #1377 could slightly improve this situation by clearly terminating everything instead of letting it hang.

### Context
This is a situation we have run in several times. Analysing and getting to the bottom of such problems is often painful. Although it does not sound like a perfect solution to just discard messages, it might well be a good enough default behavior. For example, if 3rd party libraries are responsible for producing extensive log output.

### Steps to Reproduce
See example project attached to #1377.

### Thoughts on Implementation
Messages could be discarded on worker/client (producer) or daemon (consumer) side. Usually it is the daemon who runs into trouble receiving too much messages from several workers in parallel. So the decision for discarding messages should probably be made on daemon side. Discarding the messages could still be done on worker side, if the worker gets informed by the daemon that it would not accept a certain type of message anymore.

**Comment by adammurdoch** [comment]
I think it would be better to block the producer or spool the messages to disk instead of discarding.

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

Spooling messages to disk would be a solution to this problem indeed.

Related:
* #28501
