### ISSUE TITLE
Identify APIs and features to be unincubated

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1383]
### Expected Behavior

Identify APIs and features that have been used in production for years with the goal to remove the `@Incubating` annotation and promote them in the release notes.

### Current Behavior

`@Incubating` APIs and feature have not been cleaned up or made a production-ready feature.

### Context

Users get confused about the status of incubating features. Typical questions are being asked like:

1. Is this feature usable?
2. Is the feature going to be removed?
3. When is it production-ready?

**Comment by eriwen** [comment]
This seems like an Epic. Is the goal of this issue to identify features to promote?

**Comment by bmuschko** [comment]
It's about identifying and promoting features. Why do you think this should be an Epic? Did you say that because you think it's a lot of work or because you'd like to break out an issue API/feature to be unincubated?

**Comment by eriwen** [comment]
If it's just about identifying features, I don't think this is an epic as that is an independent task. Actually doing the promotions should be scheduled one-by-one by feature so we can deliver incrementally (the latter of your 2 options).

**Comment by bmuschko** [comment]
OK, I changed the title and text to indicate that this story is just about _identifying_ APIs and features to be unincubated.

**Comment by big-guy** [comment]
What about something like the `wrapper` or `init` tasks? Does that fall under this bucket?

I think the wrapper can be de-incubated: https://github.com/gradle/gradle/blob/9386657d496ddb47d2a272d22616d1b00503e3c7/subprojects/build-init/src/main/groovy/org/gradle/buildinit/tasks/internal/TaskConfiguration.java#L90-L90

**Comment by jjohannes** [comment]
We should de-incubate both `wrapper` and `init`, because they are very visible to users and something we won't take away.
See discussion: https://gradle.slack.com/archives/engineering/p1487833450000639

**Comment by adammurdoch** [comment]
Perhaps add a separate issue for `wrapper` and `init` so we can fix them and close the issue without waiting for every candidate to be identified and a decision made.

**Comment by pioterj** [comment]
I agree with @adammurdoch. See https://github.com/gradle/gradle/issues/1531.

**Comment by jjohannes** [comment]
In Gradle 7.0, everything that was around since more than a few minor versions has been promoted unless:
- It is still under active development and likely to change
- Is unmaintained already again (candidate for deprecation)
