### ISSUE TITLE
Process isolated workers always use system default encoding for file names

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#13843]
When we spawn worker processes when using process isolation with the worker API, the environment of the spawned process is scrubbed.  We do set the `file.encoding` system property by default, but this only affects the _contents_ of files.  File _names_, on the other hand, are interpreted by the underlying native library of the JVM which relies on the locale (e.g. "LANG" environment variable) to define the effective charset.  In the absence of any environment variables, it will use whatever the default is for the operating system and file system.

When passing a file property as a parameter and the file name contains UTF-8 characters, if locale environment variables are set for the build process, this can lead to a mismatch between the encoding used when interpreting the filename between the build process and the worker process leading to a `FileNotFoundException` when the worker process tries to access the file.

Explicitly setting the `LANG` environment variable in the worker process configuration resolves the issue.  So, one solution would be to set the `LANG` environment variable in worker processes to whatever has been set in the build process.

### Expected Behavior
Worker processes should use the same encoding for file names as the build process unless explicitly changed by the user.

### Current Behavior
Worker processes may or may not use the same encoding for file names as the build process.

### Context
This came up in the context of the Android team configuring their Jacoco task to use the worker api.  They are passing the name of the file to instrument as a worker api file property parameter.  They have a test that uses non-ASCII characters in the filename.  On Linux, the build process has UTF-8 encoding, the worker process gets spawned with a null value for the LANG environment variable, and so the filename gets interpreted with the default encoding, which is something else (might be ASCII, might be ISO-8859, not sure) leading to a `FileNotFoundException`.  

### Steps to Reproduce 
See https://github.com/gradle/gradle/commit/2ce3189e53be449e03cf0072b2171e13826bd729

**Comment by lptr** [comment]
Fixed by https://github.com/gradle/gradle/pull/25319
