### ISSUE TITLE
Gradle application plugin using Kotlin is not compiling Java files

### ISSUE THREAD

**Issue by PraveenTalari** [gradle/gradle#13848]
Gradle application plugin using Kotlin is not compiling Java files

### Expected Behavior
Should be able to run.

### Current Behavior
Class files are not generated to added java class and crash with NoClassDefFoundError

### Context
command line gradle kotlin application with Java file added.

### Steps to Reproduce 
1. Create gradle application

gradle init
Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 2

Select implementation language:
  1: C++
  2: Groovy
  3: Java
  4: Kotlin
  5: Swift
Enter selection (default: Java) [1..5] 4

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Kotlin) [1..2] 2

2. Add SomeJavaClass.java file beside App.kt file
class SomeJavaClass{
    public void m(){
        System.out.println("x");
    }
}

3. Try to access SomeJavaClass in App.kt main method
    SomeJavaClass().m()

### Your Environment
6.5.1 gradle
Build scan URL:
https://gradle.com/s/eesl5kad3rcyg

**Comment by jnizet** [comment]
You're supposed to put the Java source files into the `src/main/java` folder, not into the `src/main/kotlin` folder.

**Comment by PraveenTalari** [comment]
Oh yes. But that should show compile time error, isn't it ?

I have added java folder inside main and moved the Java file inside it. I have added the following to build.gradle so that java sourceSets are available.

sourceSets {
    main.kotlin.srcDirs = ['src/main/java', 'src/main/kotlin']
}

**Comment by PraveenTalari** [comment]
instead of all this, just renaming "kotlin" folder present inside src to "java" is the simplest solution.

**Comment by jjohannes** [comment]
Closing as this was an issue with the build setup (see comment above).
