### ISSUE TITLE
sourceSets.test.output returns wrong values for the first subproject

### ISSUE THREAD

**Issue by jokram** [gradle/gradle#1385]
### Expected Behavior

For the first subproject in a multi-project `project(':zlibprj').sourceSets.test.output` should return
- `<project root>\zlibprj\build\classes\test`
- `<project root>\zlibprj\build\resources\test`

### Current Behavior

For the first subproject in a multi-project `project(':zlibprj').sourceSets.test.output` returns
- `<project root>\build\classes\test`
- `<project root>\build\resources\test`

and by this cannot resolve references.

Note: For the second subproject this problem does not appear, only the alphabetically first subproject having the dependency is affected.

### Context

- I have a library `LibraryZ` which also offers some test utilities provided in it's `src/test/java/LibraryZTest.java`
- This library is in a subproject called `zlibprj`
- Now I have two other subprojects `subprj1` and `subprj2` which want to use for their testing that `LibraryZTest` class
- To achieve this in the `subprj*/build.gradle` I've added in the dependencies `testCompile project(':zlibprj').sourceSets.test.output`
- But when I build with gradle I'll get errors that the symbols of `LibraryZTest` class cannot be resolved:
https://github.com/jokram/gradle_sourceset_problem/blob/sourceset-problem/gradle.log

### Steps to Reproduce (for bugs)
- Clone https://github.com/jokram/gradle_sourceset_problem/tree/sourceset-problem
- Run `gradle build`
- The following errors are returned: https://github.com/jokram/gradle_sourceset_problem/blob/sourceset-problem/gradle.log

Workaround:
- Edit the `settings.gradle` and remove the comment of the first line
- This will enable also the `dummyprj`
- The `dummyprj` only contains a `build.gradle` file: https://github.com/jokram/gradle_sourceset_problem/blob/sourceset-problem/dummyprj/build.gradle
- Since the problem only occurs for the first subproject and `dummyprj` the other subprojects work properly (`dummyprj` comes alphabetically before `subprj1`, `subprj2` and `zlibprj`)
- So see the workaround in action you can clone https://github.com/jokram/gradle_sourceset_problem where the workaround is already applied, see https://github.com/jokram/gradle_sourceset_problem/blob/master/gradle.log

### Your Environment
```
------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------
Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b
Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Windows 7 6.1 amd64
```
All commands run from DOS prompt

**Comment by eriwen** [comment]
@jokram your thorough submission of this issue is greatly appreciated. We'll look into this.

**Comment by oehme** [comment]
The simple answer is: Don't reach into other project's configuration. Using `someProject.sourceSets.test.output` is not the right model of what you want to do (it breaks IDE integration and misses transitive dependencies). It also breaks encapsulation between projects, making you dependent on configuration order, which can lead to all kinds of funny behavior. In this specific case the project you are trying to reach into has not yet been configured, but the parent project happens to have a property called "sourceSets", so you get those instead.

You can model this as a proper project dependencies, as shown in this [forum post](https://discuss.gradle.org/t/how-do-i-declare-a-dependency-on-a-modules-test-code/7172).

Also, I'd recommend splitting tests and test fixtures. I'm pretty sure you don't want your downstream project's tests to rerun every time you make a change to any test in the upstream project. What you probably want is to just share a few common test fixtures instead and only rerun if those have changed.

Something like this should help, of course extracted into a common script plugin that all projects reuse:

```
sourceSets {
  testFixtures {
    java.srcDir 'src/testFixtures/java'
  }
  test {
    compileClasspath += testFixtures.output
    runtimeClasspath += testFixtures.output
  }
}
configurations {
    testCompile.extendsFrom(testFixturesCompile)
    testRuntime.extendsFrom(testFixturesRuntime)
    testFixtures.extendsFrom(testFixturesRuntime)
}
task testFixturesJar (type: Jar) {
    baseName = "${project.name}-testfixtures"
    from sourceSets.testFixtures.output
}
artifacts {
    testFixtures testFixturesJar
}
```

In a downstream project you can then do:

```
dependencies {
  testCompile project(path: ':foo', configuration: 'testFixtures')
}
```
