### ISSUE TITLE
Build in master causes 4 class files to be created in a git indexed directory

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#13853]
If a build is ran from master, 4 class files get created in git indexed directories. This is not good, and running a build should not result in any new files.

```
subprojects\build-init\src\integTest\resource\org\gradle\buildinit\plugins\MavenConversionIntegrationTest\enforceplugin\target\classes\Foo.class

subprojects\build-init\src\integTest\resource\org\gradle\buildinit\plugins\MavenConversionIntegrationTest\flatmultimodule\webinar-api\target\classes\webinar\Demoable.class

subprojects\build-subprojects\build-init\src\integTest\resource\org\gradle\buildinit\plugins\MavenConversionIntegrationTest\flatmultimodule\webinar-impl\target\classes\webinar\Webinar.class

subprojects\build-subprojects\build-init\src\integTest\resource\org\gradle\buildinit\plugins\MavenConversionIntegrationTest\flatmultimodule\webinar-impl\target\test-classes\webinar\WebinarTest.class

```

### Expected Behavior
No extra indexed files should be created during a build.

### Current Behavior
Indexed files are created during a build.

### Context
Slows down commits, as I can't just run `git add .`

### Steps to Reproduce 
1. Clone https://github.com/gradle/gradle
2. Build (I was using `./gradlew :platformBase:build` but I'm sure others would do it)
3. Run `git status` and see extra files.

**Comment by bmuskalla** [comment]
This doesn't happen on `master` anymore. Thanks for reporting
