### ISSUE TITLE
Deprecate `JavaApplication#setMainClassName` in favour of property

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#13855]
`JavaApplication` currently has `setMainClassName` and `getMainClassName`. In 6.4, we also introduced `Property<String> getMainClass()` with a `@ReplacedBy`. I think we should `@Deprecate` the previous ones in favor of the property API. 

@jjohannes Was this intentionally not done yet to not force people to use an `@Incubating` API?

**Comment by blindpirate** [comment]
@bmuskalla I think we force people to add `@Incubating` to new APIs, what do you mean "not done yet"?

**Comment by bmuskalla** [comment]
We didn't deprecate the set/get that we're replacing with the property API.

**Comment by ljacomet** [comment]
That was on purpose. The API option should not be between `@Incubating` and `@Deprecated`.

Now, nothing forces us to keep the new API incubating for long.

**Comment by jjohannes** [comment]
I think we can go ahead now and now for 6.7: remove the incubation on the new APIs here and deprecate the old ones.

**Comment by digitalheir** [comment]
I don't understand what happened here: `setMainClassName` was deprecated with the message: "Set via getMainClass() instead." 

Do we need to subclass JavaApplication??? What the hell. I would expect a setter method `setMainClass`.

**Comment by melix** [comment]
`mainClass` is a `Property<String>`. So in the Groovy DSL you just need to write:

```
mainClass = 'my.Main`
```
or in the Kotlin DSL:
```
mainClass.set("my.Main")
```
