### ISSUE TITLE
 Unable to find module with Gradle path ':moduleName'

### ISSUE THREAD

**Issue by QumberAbbas** [gradle/gradle#13864]
I am facing this issue, unable to sync the project successfully. I do have the module in my application. But still, this giving me the error which leads to sync failure.
Android Studio Version: 4.0.1
Gradle: 5.6.4

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

This might be an issue with AGP, please [refer to sources](https://stackoverflow.com/questions/29566006/unable-to-find-module-with-gradle-path-linking-to-library-unspecified-instead) to track this down.
