### ISSUE TITLE
Dependency resolution of Ivy artifacts does not support [type] token

### ISSUE THREAD

**Issue by frisby** [gradle/gradle#1386]
### Summary

There should be a way to customize every element of an Ivy artifact pattern. It appears that there is no way to specify a `[type]` that does not match `[ext]`.

### Context

Sample Ivy layout pattern, taken from the [Gradle 3.3 User Guide](https://docs.gradle.org/3.3/userguide/dependency_management.html#sec:defining_custom_pattern_layout_for_an_ivy_repository):

```
repositories {
    ivy {
        url "http://repo.mycompany.com/repo"
        layout "pattern", {
            artifact "[module]/[revision]/[type]/[artifact].[ext]"
        }
    }
}
```

Fairly typical external dependency, also from the [Gradle 3.3 User Guide](https://docs.gradle.org/3.3/userguide/artifact_dependencies_tutorial.html#sec:external_dependencies_tutorial):

```
dependencies {
    compile group: 'org.hibernate', name: 'hibernate-core', version: '3.6.7.Final'
}
```

(`apply plugin: 'java'` was specified in a previous Example, and presumed to remain in effect.)

In the above example, `compile`'s `group:` parameter maps to `[module]`, `name:` to `[artifact]`, and `version:` to `[revision]`. Although I can find no documentation for it, the `compile` command appears to support `ext:`, which maps to Ivy's `[ext]` token.

### Current Behavior

As near as I can tell, Gradle forces `[type]` to match `[ext]`. While very common, this is not guaranteed, which is why they are separate tokens to begin with.

### Expected Behavior

There should be a way, either inline or via closure, to let `[type]` and `[ext]` operate independently of one another. Because they usually match, a default in which they are equal is fine.

In researching this, I've seen a few people draw comparisons to Maven's `classifier`. In these online discussions, Gradle developers have resisted this comparison, for reasons I presume are valid (this is not my area of expertise). Nevertheless, the `[type]` token should have _some_ mechanism of support.

### Steps to Reproduce (for bugs)

Using the examples above, an Ivy repository with the following directory layout should be sufficient to reproduce:

```
org.hibernate/
  |
  +--3.6.7.Final/
      |
      +--bin/
      |    |
      |    +--hibernate-core.jar
      |
      +--src/
           |
           +--hibernate-core.jar
```

The expectation would be that Hibernate's binary file would have a `[type]` of `'bin'`, while the source code would have a `[type]` of `'src'`. The goal is to specify an external dependency that lets one download either `.jar` using the Ivy pattern in Gradle's User Guide.

(The only workaround I can see right now is to create separate patterns with each value for `[type]` hard-coded into it. This not only misses the point of having a token, it forces a download of _every_ `.jar`, instead of "just sources" or "just binaries".)

I saw that the incubating [`IvyArtifact`](https://docs.gradle.org/3.3/dsl/org.gradle.api.publish.ivy.IvyArtifact.html) class has a `type` property, but it appears to be publish-only. I cannot find an equivalent concept for dependencies.

### Your Environment

I am currently a developer working at a large enterprise with a strong division of roles between developers and operations. My access to the Ivy repository is restricted to an "end-user" role, so altering its configuration is not an option.

**Comment by eriwen** [comment]
Thank you very much for a thorough feature request @frisby. It sounds like you dug into the code here, would you be willing and able to submit a PR to address this? I believe it will ship to users like yourself faster.

**Comment by eriwen** [comment]
Note that this seems closely related to #1357. A contributor could make a very big impact by addressing both changes.
