### ISSUE TITLE
ComponentMetadataRule for Ivy dependencies always adds all variants

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#13869]
Gradle: `6.5
Android Gradle plugin: `4.1+`
Original issue: https://issuetracker.google.com/161405989

Using [lint-checks.zip](https://github.com/gradle/gradle/files/4952682/lint-checks.zip) project and running `./gradlew :app:assembleDebug`, the build fails with:
```
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find checks-1.0-SNAPSHOT-samplessources.jar (org.gradle.sample:checks:1.0-SNAPSHOT).
     Searched in the following locations:
         file:/home/gavra/AndroidStudioProjects/LintChecks/ivyRepo/org.gradle.sample/checks/1.0-SNAPSHOT/checks-1.0-SNAPSHOT-samplessources.jar
```

Although this sample is synthetic for the ease of reproduction, we are using similar `ComponentMetadataRule` code in the IDE to fetch additional components of dependencies. However, it seems that this rule also impacts configurations which do not specify the docstype attribute when querying the configuration. E.g I've added `implementation "org.gradle.sample:checks:1.0-SNAPSHOT"` to `app/build.gradle` and that dependency is in the Ivy repo under `$rootDir/ivyRepo`. Is this by design? Adding
```
if (ctx.getDescriptor(IvyModuleDescriptor) != null) {
    return
}
```
to the rule solves the issue.

**Comment by ljacomet** [comment]
By default, an Ivy dependency has no variants. There is no way to derive variants from Ivy configurations as there are simply too many possibilities. See #10299 for a longer discussion on this.

So what happens with your generic metadata rule is that you end up adding a single variant to _all_ Ivy dependencies, without converting any of the Ivy configurations into variants themselves.
This result in Gradle taking the preferred path of variant resolution for the Ivy dependencies, but only the `samplessources` variant is available and causing selection issues.

Ignoring Ivy dependencies is the right call in your setup I believe.

There is nothing Gradle can improve on this topic in a generic fashion.

**Comment by ljacomet** [comment]
Closing as there are no changes to be done on the Gradle side for this.
