### ISSUE TITLE
Configuration Cache report not using custom `buildDir`

### ISSUE THREAD

**Issue by LarsKaulen** [gradle/gradle#13866]
When using the configuration cache (with `--configuration-cache` on the command line) on a build that contains errors, a report is generated. The location of this report is always under the `build` directory, even when `buildDir` was configured to be something else.

### Expected Behavior

The report should be generated in `<<buildDir>>/reports/configuration-cache/` where `<<buildDir>>` corresponds to the specified `buildDir`.

### Current Behavior

The report is generated in `build/reports/configuration-cache/` even though the `buildDir` is configured to e.g. `target`.

### Context

Testing the new configuration-cache and its problem/error report.

### Steps to Reproduce 

Configure the `buildDir` e.g. like
```
allprojects {
    buildDir = 'target'
}
```
Run `./gradlew help --configuration-cache` on a project with configuration-cache-errors.

**Comment by LarsKaulen** [comment]
Tested with `6.6-rc-2`.

**Comment by eskatos** [comment]
Fixed in #13900, will be in Gradle 6.6
