### ISSUE TITLE
Deprecate including sub-projects from outside the root project directory

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#13891]
In many places we already assume that the root directory includes all the source code for the project. And it's a good assumption, allowing us to do optimizations like watching only the project root for changes (see #13887).

However, it's actually possible to include subprojects from directories outside the root dir:

```groovy
include("side-project")
project(":side-project").projectDir = file("../side-dir")
```

We should deprecate this as bad practice and remove it soon.

---
cc: @gradle/execution

**Comment by oehme** [comment]
That's essentially `includeFlat`, which is popular with Eclipse users, because Eclipse still sucks at nested project layouts (it reports resources multiple times in the "open resource" dialog, once for each nesting level).

**Comment by lptr** [comment]
Hm... I guess one way to solve this is to watch the parent of the root project dir if `inlcudeFlat()` is used. That way we could support this use case and still deprecate including arbitrary stuff in the project.

**Comment by oehme** [comment]
That sounds reasonable.

**Comment by lptr** [comment]
I did a bit of research around `includeFlat()`. It seems that people typically have some kind of "master" directory where the `settings.gradle` lives, and the other project directories are its siblings, like so:

```text
.
├── common-algorithm
├── common-api
├── common-bean-javassist
├── common-compress
├── common-core
├── common-db
├── common-gentool
├── common-mail
├── common-model-api
├── common-model-repository
├── common-spring
└── commons-build-config  <--- holds the settings.gradle file
```

I tried to build https://github.com/featherfly/commons/tree/2ab63a180104c21c94fc7d6b438113dfabdfa01b to see what the `rootDir` points to in such a case.

I had to delete this line, but otherwise running `gradle assemble` worked fine with Gradle 6.5.1:

https://github.com/featherfly/commons/blob/2ab63a180104c21c94fc7d6b438113dfabdfa01b/commons-build-config/settings.gradle#L15

Printing the root directory shows that it actually points to the `commons-build-config` directory instead of the actual root dir of the whole project. :/

**Comment by lptr** [comment]
Reassigned to idiomatic Gradle effort /cc @jjohannes.

**Comment by big-guy** [comment]
@lptr how does this interact with included builds that will typically be outside of the root?

e.g., if I have:

```
root-build/
   settings.gradle
   sub1/
      src/main/java/...
included-build/
   src/main/java/...
```

When I'm in `root-build` and run `gradlew --include-build ../included-build someTask`, is that OK because we would optimize for two different roots (root-build and included-build) or does it suffer from the same problem as subprojects included outside of the root?

**Comment by lptr** [comment]
@big-guy if you are asking about file system watching, then included builds work fine: we always watch the root of the build. Does that answer your question?

**Comment by donat** [comment]
It would also make sense to deprecate the `includeFlat` method as it also encourages using a flat project structure.

**Comment by sdroselius** [comment]
> We should deprecate this as bad practice and remove it soon.

Why do you consider this a "bad" practice, if I may honestly ask?

**Comment by sdroselius** [comment]
> That's essentially `includeFlat`, which is popular with Eclipse users, because Eclipse still sucks at nested project layouts (it reports resources multiple times in the "open resource" dialog, once for each nesting level).

Not just Eclipse.

Can you please clarify your objection to a project upon which other non-owning projects might depend?

**Comment by sdroselius** [comment]
_In many places we already assume that the root directory includes all the source code for the project. And it's a good assumption,_

No, that's an awful, ridiculous, harmful assumption.

Who's in charge of Gradle these days?  

Because I'm a compass-point from telling my students it's a failed hot mess.

**Comment by sdroselius** [comment]
> We should deprecate this as bad practice

When you say "should", you make it a moral issue.

WTF is your actual problem, good respected sir?

**Comment by pioterj** [comment]
@sdroselius Please follow our code of conduct at https://gradle.org/conduct/ if you want to participate in discussions in this issue tracker.

**Comment by sdroselius** [comment]
My apologies, comments deleted.

**Comment by lptr** [comment]
We'd like to push towards a model where the file system area underneath the project root directory is treated specially: during a build this area should be mutated exclusively by Gradle and the tools that are invoked as part of the build. Enforcing this separation of scope between Gradle-owned vs everything else allows us to safely optimize execution.

We also offer the option to split your build into several a composite of builds if you want to have a higher level structure.

We are not aware of a use case where these would be too inflexible requirements, but it seems you have some. Could you tell me how your builds are structured, and why ensuring that everything that belongs to the build lives under the project root is a problem for you? Thanks!

**Comment by UmaMtwo** [comment]
Hi @lptr,

let's assume I have two projects which share a common lib and the projects and lib are in separate repositories. How would you set up the project structure?

**Comment by chriscottingham** [comment]
I would like to second @UmaMtwo.

As stated earlier, Eclipse does not support a strict hierarchy well.  Are you going to simply exclude Eclipse users from using future generations of gradle?

In eclipse, if I want my project to rely on something I check out from github, I will check out that project as another project in the workspace, which makes it a sibling of the project which will rely on it.  

In the hierarchical project structure which you are proposing to force on users, I will have to put my settings and build gradle files in the workspace directory, where eclipse cannot find them.  This will break eclipse support for building my projects.  I will (afaik) not be able to use future generations of gradle with eclipse.

**Comment by mickyp** [comment]
I have a similar situation regarding @UmaMtwo  and @chriscottingham. I need the project structure to make sure they are workable in Eclipse.

**Comment by mauromol** [comment]
I just discovered that Gradle 7.1 has deprecated the flat project layout. I really don't understand what is wrong with it, even if we talk about file system watching. In flat layout I have:

- master
- subproject1
- subproject2
- etc.

Isn't it enough to watch on those three directories? Or on the common parent of all of them? Why this layout should be "bad practice"??

As other have already highlighted, working with the nested project structure is still a pain in Eclipse in 2021. And I also think that having a root project named "master" gives the opportunity to put in there some multiproject data (like documentation, database upgrade scripts, anything else) which is relevant across subprojects to the whole multiproject, without mixing folders with data with folders with subproject (as you have to do when using the hierarchical project structure).

In the Gradle 7.1 you say that "there are several disadvantages of using a flat project structure": what are these disadvantages? You just mention filesystem watching, which still doesn't convince me, honestly.

We have been living with the flat project layout really happy for years and we never found any drawback caused by this choice...

**Comment by mauromol** [comment]
> We'd like to push towards a model where the file system area underneath the project root directory is treated specially: during a build this area should be mutated exclusively by Gradle and the tools that are invoked as part of the build. Enforcing this separation of scope between Gradle-owned vs everything else allows us to safely optimize execution.

The parent folder of the master project in a flat layout would have these characteristics, unless one puts something else there, along with the master project and all the other subprojects. Perhaps Gradle may just emit a warning if this is the case...

> We are not aware of a use case where these would be too inflexible requirements, but it seems you have some. Could you tell me how your builds are structured, and why ensuring that everything that belongs to the build lives under the project root is a problem for you? Thanks!

One use case, as other have said, is using Gradle with Eclipse: using the hierarchical project structure is possible, but it's quite uncomfortable. Some Eclipse plugins, in particular SCM ones, are still being cheated by the fact that a project actually resides within another project (the root project, for instance) and may exhibit annoying behaviours, like showing the same modified file twice in the SCM case.
Eclipse aside, I still think that a flat structure with projects coming from different source code repositories (as @UmaMtwo described) is another use case for which the hierarchical layout isn't suited, without adding the complexity to set up a composite build.

**Comment by ingokegel** [comment]
I would like to ask you to weigh the benefit of easier file system watching against the pain that this forced migration to composite builds will bring for your existing users. I estimate that this change will cost me 5 to 10 days of work for my projects.

**Comment by lptr** [comment]
Our goal with this step, as with several others, is to enable Gradle to "own" the build directory's contents. This enables us to do a number of optimizations safely. File system watching is just one piece of that puzzle.

> Eclipse aside, I still think that a flat structure with projects coming from different source code repositories (as @UmaMtwo described) is another use case for which the hierarchical layout isn't suited, without adding the complexity to set up a composite build.

How are composite builds adding complexity here? Gradle's way of handling this use case is via composite builds. If there's unnecessary complexity around that, we might be able to reduce it.

**Comment by mauromol** [comment]
@lptr: probably @ingokegel can better answer regarding composite builds.

What I can say is that you asked for use cases, multiple people are highlighting the problems with Eclipse (including @oehme, who is a Buildship committer, if I remember well) and you're still ignoring them.

And again, you don't say why the master project parent folder is not a good candidate for the Gradle "owning" of the whole build contents.

**Comment by donat** [comment]
> How could you close this topic ... You will just ignore the problem that is coming with this!!!

I've opened a new issue: https://github.com/gradle/gradle/issues/18644

**Comment by donat** [comment]
FYI we'll revert the deprecation warning in Gradle 7.4: https://github.com/gradle/gradle/pull/19135

**Comment by borisblizzard** [comment]
> @lptr Unfortunately, a composite build is not a good replacement for sub-projects outside the root directory. For example, I cannot refer to `Project` instances of projects in the included build. This alone makes a big difference in how I can structure my build logic.
> 
> Let me reiterate the general use case for this feature independently of eclipse:
> 
> I have projects A and B and a common project C. All of these projects live side by side in the same VCS repository. A and B include C in their settings files. In this way, C becomes a fully integrated part of both A and B.
> 
> You cannot do that in the same way with composite builds. I have now tried to change my projects to composite builds but I stopped because I could not make it work without major changes in the build architecture.
> 
> Please reconsider this change, it is extremely painful to people who depend on this feature.

I also have a project setups. On top of that my projects use C++ code which also needs to be easily accessed by other IDEs. Having all Android Studio related files (including gradle project definitions) in a special folder (just like XCode and Visual Studio) is crucial to maintaining orderly source code. With this requirement I am forced to restructure everything because Gradle won't play nice anymore.

**Comment by borisblizzard** [comment]
> Thanks @borisblizzard. In case you haven't seen the comments from @donat above, we've released the reversal of this deprecation already in Gradle 7.4, so you should be all good.

I must've missed it somehow. Thank you!
