### ISSUE TITLE
(2.10) 'An established connection was aborted by the software in your host machine.'

### ISSUE THREAD

**Issue by StaticCloud** [gradle/gradle#1390]
### Current Behavior

When I sync Gradle, I keep getting an error saying: **Error: An established connection was aborted by the software in your host machine**

### Steps to Reproduce (for bugs)

What I did was I downgraded my Android Studio Gradle version to 2.10 from 2.14.1 (having issues with 2.14.1). This included removing the 2.14.1 files from the .gradle folder in the user directory and all 2.14.1 folders in the Android Studio directory.

**Comment by eriwen** [comment]
I'm afraid we don't have enough information to know whether this is a bug in Gradle or in Android tooling. 

Were you able to solve this issue? How? Do you have a stack trace from Android Studio? What version of Android Studio?

**Comment by StaticCloud** [comment]
@eriwen 
I opened the project on another computer and it worked fine, so I concluded that its an issue with the current computer I have.

**Comment by eriwen** [comment]
Ok closing this then, thanks.

**Comment by jbaris** [comment]
If you are on Windows, just try to restart your computer :)
