### ISSUE TITLE
How to determine the deployment url and artifact values in init.gradle, uploadArchive task will pick while executing

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [gradle/gradle#13905]
In the Build.gradle, I have defined uploadArchive task and jar in the project.
```
jar {
	baseName = 'GradleVersionParam'
}

uploadArchive {
    repositories {
       mavenDeployer {
            repository(url: ReleaseURL) {
                authentication(userName: Username, password: Password)
            }
            snapshotRepository(url: SnapshotURL ) {
                authentication(userName: Username, password: Password)
            }
        }
    }
}
```

Approach is to do validation pre and post upload, when I am executing uploadArchives, rootname for the project is 'JAVADEMO' and baseName is 'GradleVersionParam', both are different, so the artifact gets created with baseName. I am not able to be fetch baseName of the artifact in init.gradle at the global level. We have applications running on v4.1 to v6.5 of Gradle. So expectation is run init.gradle for all Gradle verions 

```
projectsEvaluated {

    rootProject.allprojects {
    
   Upload uploadTask = (Upload) project.tasks.uploadArchives;

    gradle.addListener(new TaskExecutionListener() {

    void beforeExecute(Task task) {
if (task.name.matches("publish.*PublicationTo.*Repository") ) {
                        def publication = task.publicationInternal
                        println("Remote => $publication.artifactId $publication.groupId $publication.version  $task.repository.url")
                        groupId = "$publication.groupId"
                        artifactId = "$publication.artifactId"
                        version = "$publication.version"
                        repoURL = "$task.repository.url"
                    }

                    if (task.name.matches("uploadArchives")) {
                        uploadTask.repositories.mavenDeployer {
                            if ( pom.getGroupId() != 'unknown' ){
                                groupId = pom.getGroupId()
                            }
                            println("pom.getArtifactId()--->"+pom.getArtifactId())
                            if ( pom.getArtifactId() != 'empty-project' ) {
                                artifactId = pom.getArtifactId()
                            }
                            println("pom.getVersion--->"+pom.getVersion())
                            if ( pom.getVersion() != '0') {
                                version = pom.getVersion()
                            }

                            if ( version.contains('SNAPSHOT') ) {
                                repoURL = snapshotRepository.url
                            } else {
                                repoURL = repository.url
                            }
                        }
                    }
             }
                void afterExecute(Task task, TaskState state) {
              }
      }
}
```

I am not able fetch the configuration details of the uploadArchives task just before the execution time like Artifactname, version, groupId and the url where it is getting uploaded.

Expected values to fetch before the uploadArchives task execution :

ArtifactID
GroupID
version
Url

**I have put this query on  various public forums even on [Gradle discussion forum](https://discuss.gradle.org/t/how-to-determine-the-deployment-url-uploadarchive-task-will-pick-at-runtime/36990), but could not get any response. Can you please assist.**

**Comment by big-guy** [comment]
Sorry that we've taken so long to get back to you on this.

`UploadArchive` has been deprecated and partially removed in Gradle 7.  `maven-publish` is the replacement mechanism and it does not currently expose the final URL either, but you should be able to look at the publication associated with the `PublishToMavenRepository` task and verify that the group/version/artifactId are what you would expect.  You might also be able to confirm that the right repository is being used or disable any `PublishToMavenRepository` tasks that should not be used.

I'm going to close this issue since we do not intend to provide an API specifically for this use case at this time.

Thanks!
