### ISSUE TITLE
Print positive/negative time savings when build cache is used

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#13908]
### Expected Behavior

Gradle could estimate the amount of time build-cache shaved from the build:

```
BUILD SUCCESSFUL in 275ms
1 actionable task: 1 from cache (saved ~42s)
```

I see that cache item metadata does include the time it took to build the task, so Gradle could take that and subtract from the actual task duration.

### Current Behavior

```
BUILD SUCCESSFUL in 275ms
1 actionable task: 1 from cache
```

### Context

I'm adding build-cache configuration to my Gradle build, and I want to know if the cache introduces a positive or negative impact.

**Comment by vlsi** [comment]
Of course, there's a question on the verbosity of the output, however, let me show "the most verbose", then we can figure out if the output needs to be configurable and/or which fields should be printed.

Note: I'm not sure if "local cache" statistics should be included as well (it should probably be included if it exceeds 1-2 seconds).

```
BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed
Remote cache saved: 0ms, wasted: 233ms, reads: 1, hits: 0, elapsed: 233ms, processed: 0 B
Remote cache writes: 1, elapsed: 121ms, sent to cache: 472 B
```

Remote cache reads:
* `saved: 0ms` – the estimated time saved by the remote build cache (`original_task_elapsed_time - from_cache_task_elapsed_time`).
Note: this estimation does not account for parallel task execution. Negative estimation means it is
probably faster to build task from scratch rather than download the cached results.
* `wasted: 233ms` – the amount of time spent for `cache misses` (==load request sent, but no entry found in the cache)
* `reads: 1` – number load requests to the remote cache
* `hits: 0` – number items loaded from the remote cache
* `elapsed: 233ms` – total time spent on loading items from the remote cache
* `processed: 0 B` – number of bytes loaded from the remote cache

Remote cache writes:
* `cache writes: 1` – number of store requests to the remote cache
* `elapsed: 115ms` – time spent uploading items to the remote cache
* `sent to cache: 472 B` – number of bytes sent to the remote cache

**Comment by vlsi** [comment]
One more idea: at the end of the build, Gradle knows all the timings, and it knows build parallelism, and task dependencies. Then it can simulate "task graph execution" with both "cache enabled" and "cache disabled" timings.

This would provide a more accurate estimation of the impact of the caching on the build performance.

Of course, that estimation won't be right for worker-based tasks, however, it might be interesting to have something like "if you increase parallelism from 4 to 8, the expected build duration would reduce from 6min to 5min".

WDYT?

**Comment by wolfs** [comment]
Thank you for the suggestion. Since this feature involves multiple builds on different machines and is more about tracking performance across builds this is more an enterprise feature. It adds more noise to the individual builds if you see those printouts on every build.

When trying out the build cache, you can use the free scans.gradle.com service for looking up the execution times. Or if you have a Gradle Enterprise installation, you can get this information and more.
