### ISSUE TITLE
Can't update gradle without it ruining your project

### ISSUE THREAD

**Issue by jimgwhit** [gradle/gradle#13915]
Please help, is there a way to update gradle without a project being ruined, and having to redo the whole app from scratch.

I can go from netbeans 8 to 12, do a clean and build on native build (native is ant I believe), and the app / project works perfect.

What is the deal with gradle. I went from netbeans 11 to 12, updated gradle in a gradle project in netbeans, my project / app was runied. Help please. How to update gradle without a rig ma rah. I want to develop java, not spend hours updating what should be a simple build tool.

An update should auto apply to a project.

If a solution doesn’t exist for netbeans, I am willing to use eclipse. What do I do?

Been using netbeans for years, never seen such a thing as having to actually recode a whole project because an update runied it.

HELP.

Make gradle be easy like ant.

**Comment by big-guy** [comment]
I'm sorry you've had trouble with Gradle.

Without more specific information about what kind of problems you've had, it's hard to make suggestions.

You may be able to get [more help](https://gradle.org/help/#gsc.tab=0) from our community forums or StackOverflow. 

In general, you're not forced to upgrade Gradle when changing the version of the IDE. We try hard to maintain backwards compatibility with old plugins and old IDEs.  We also try to emit deprecation warnings on older versions of Gradle when a feature or API will be removed and then only remove it at major version bump.
