### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR.

### ISSUE THREAD

**Issue by eliusmamun** [gradle/gradle#13914]
I updated the following-
 Gradle version from 5.4.1 to 6.5.1
 Plugin version from 3.5.3 to 4.0.0
 Kotlin version from 1.3.61 to 1.3.72
My Android Studio version is 4.0. After gradle sync the build failed with the below error.
Direct local .aar file dependencies are not supported when building an AAR

### Expected Behavior

The build should not fail
### Current Behavior

The build fails with the below error .
Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). 

### Your Environment
Android Studio 4.0

Build scan URL:

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
