### ISSUE TITLE
Memory and performance improvements related to external dependencies

### ISSUE THREAD

**Issue by huxi** [gradle/gradle#1392]
Introduce something like this:

```java
public interface ExternalDependencyDefinition {
	String getGroup();
	String getName();
	String getVersion();
	String getClassifier();
	String getExtension();
}

/* Immutable */
public class DefaultExternalDependencyDefinition {
	private final ModuleIdentifier moduleIdentifier;
	private final String version;
	// [..]
}
```

Implement a build scope `DependencyDefinitions` service (i.e. something like `ModuleExclusions` over in #1298) that handles the parsing, lookup and caching of parsed instances.

Use `ExternalDependencyDefinition` instead of individual fields in your internal classes related to external dependencies. This detaches the dependency definition from target configuration and artifacts.

This alone would save you at least 4*"size of a pointer" bytes of memory per external dependency used in any configuration as well as ("total number of external dependencies"-"number of unique external dependencies")*"cost of parsing either string or map into external dependency" of configuration time.

It should be considered to also add `excludes` and `transitive` to those definitions, or rather some kind of definition extending from it. That would introduce additional complexity, though, because the `String`/`Map` used to create an external dependency wouldn't have a 1:1 relationship to the definition instance anymore.

Having "something like that" would be nice to have anyway because it could be used to finally implement functionality similar to `<dependencyManagement>` of Maven. The registry could provide lookup methods that would work with just `"group:name"` and would return the matching definition including the full information.

Yes, I'm aware of [io.spring.dependency-management](https://plugins.gradle.org/plugin/io.spring.dependency-management) but I really think this should by gradle-core functionality, especially since it could be a side-effect of this enhancement.

**Comment by oehme** [comment]
> The registry could provide lookup methods that would work with just "group:name" and would return the matching definition including the full information.

It already is a core functionality, see `Configuration.resolutionStrategy.eachDependency()`. The Spring dependency managament plugin simply builds on top of those.

Regarding the main proposal: Configuration time and memory consumption improvements are definitely topics that we will prioritize soon, there were just some bigger items to take care of first (see the 3.4 release). 

Which internal classes are you referring to that could save memory? We only use the `String`/`Map` syntax at the user level. It is converted into a strongly typed [dependency object](https://github.com/gradle/gradle/blob/c8143c9bcf412a2d19053b8c926c7787c1dc8087/subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractExternalModuleDependency.java#L23-L23) right away, which is then passed around during dependency resolution.

**Comment by huxi** [comment]
The idea was that an intermediate immutable `DependencyDefinitions` is created which is holding all information that can be parsed from either `String` or `Map` representation of an external dependency. That `DependencyDefinitions` could then be resolved from a cache if it was already previously generated, saving the costs of parsing it over and over again.

If an instance of that `DependencyDefinitions` was used in e.g. `AbstractExternalModuleDependency` instead of the several separate fields then this would save `("number of removed fields"-1)*sizeof(reference)` of memory (minus 1 because there would still be that single reference to the `DependencyDefinitions` that is replacing the multiple references).

We are currently implementing something like Maven `<dependencyManagement>` by using two methods, `void registerVersion(String groupWithName, String version)` and `String managedDependency(String groupWithName)` backed by a `Map<String, String>`. Those methods also perform a few sanity checks like checking that versions are only registered once.

So this code:
```groovy
registerDependency('foo:bar', '1.0.0')
dependencies {
    compile managedDependency('foo:bar')
}
```

would be equivalent to this code:
```groovy
dependencies {
    compile 'foo:bar:1.0.0'
}
```

This works and does what it should (keeping all versions the same across all modules) but also means that the actual dependencies are currently always recreated from the returned `String` on the fly.

It would be ideal if the above could be changed to something like `Dependency managedDependency(String groupWithName)` or `DependencyDefinitions managedDependency(String groupWithName)` to circumvent this but I'm not aware of any (public) API to simply generate a `Dependency` from a given `String` or `Map` representation for the purpose of caching and reuse.

`Configuration.resolutionStrategy.eachDependency()` can provide that "same version" functionality but is doing so with higher complexity (O(1) vs. O(n)).

**Comment by oehme** [comment]
> Configuration.resolutionStrategy.eachDependency() can provide that "same version" functionality but is doing so with higher complexity (O(1) vs. O(n)).

I'm afraid I don't understand the difference in complexity, can you please elaborate? Why would it be O(n)? 

The approach you showed above only manages the declared dependencies, but would not help you with transitive dependencies. That's why you should use the `ResolutionStrategy` to ensure the expected dependency is always selected, no matter if it was a top level one or brought in transitively.

**Comment by huxi** [comment]
> I'm afraid I don't understand the difference in complexity, can you please elaborate? Why would it be O(n)?

A hashtable lookup `O(1)` vs. iterating over every declared dependency `O(n)`. It's actually even `O(n*m)` where `m` is the number of `eachDependency` calls/rules and `n` is the number of declared dependencies.
Transitive dependencies are generally more fragile than explicit ones. If those cause a problem then one could still fix that issue by declaring them explicitly instead.

**Comment by oehme** [comment]
Sorry I don't follow. It doesn't make a difference whether you do this:

```
dependencies {
  compile someConstantTimeLooup("group:name") //same for each dependency
  ... 
}
```
or this

```
configurations.foo.resolutionStrategy.eachDependency { dependency ->
  someConstantTimeLookup(dependency)
}
```

Both do one constant time lookup for each dependency. The second is just more accurate because it also catches transitive dependencies, which the first one misses.

**Comment by huxi** [comment]
Well, the second one would be executed in addition to something like the first one because the dependencies would still need to be declared anyway.

But you are right that, for the scenario were only the version differs, the lookup of the correct version can be constant. `ModuleVersionSelector` includes the version (and arbitrary other data depending on the exact type), though, so this won't just be a straight-forward lookup into a `Map<ModuleVersionSelector, String>` where the `String` value of the `Map` would be the correct version.

I kind of disagree about the "more accurate" part because I've had my fair share of problems caused by inadvertently upgraded transitive dependencies, too. That's not a simple true/false thing.

**Comment by oehme** [comment]
> Well, the second one would be executed in addition to something like the first one because the dependencies would still need to be declared anyway.

I'm not sure what you mean. With the resolution rule solution you just declare your dependencies without version, so there is no need for any additional work.

```
dependencies {
  compile 'foo:bar' //version added by rule later
}
```

> ModuleVersionSelector includes the version (and arbitrary other data depending on the exact type), though, so this won't just be a straight-forward lookup into a Map<ModuleVersionSelector, String> where the String value of the Map would be the correct version.

Looking up by "group:name" is just one use case of many and pretty simple to do by concatenating them to form the cache key. There are many other kinds of rules though where I might for instance want to use the same version of all dependencies under a certain group. Resolution rules provide a framework to make any kind of such rule possible, including the one you were looking for.

Now to get back to the original title of the post: We are definitely going to look at the efficiency of dependency notation parsing so that reusing parsed `Dependency` objects will become a non-issue. Your build would have to be pretty deeply optimized in order for this to be the bottleneck right now though.

**Comment by huxi** [comment]
I'm down to 2.5-3s configuration time for that 500+ module project (aside from https://github.com/spring-projects/spring-boot/issues/8167 because of which I can currently decide whether I want fast configuration time or faster overall build time, but not both) so, yeah, I'm just searching for places to save a few more ms to make continuous build more viable.
The situation isn't bad and the build is already fast. But faster is always better and reusing parsed `Dependency` objects seems to be the most obvious thing. I don't expect too much speedup but wouldn't be surprised by 100-200ms, either.
I kind of assumed that you are already looking into this but wanted to say something anyway because it has been like this for years. Just in case.

**Comment by oehme** [comment]
Until this is optimized on our side you could use `DependencyHandler.create()` to create and reuse dependency objects.

**Comment by oehme** [comment]
Closing this as even on large builds I do not see dependency notation parsing as an overhead anymore. If you still see this, please use the [Gradle profiler](https://github.com/gradle/gradle-profiler) to create a JFR recording and send it to us.
