### ISSUE TITLE
StackOverflowError on Gradle compileGroovy

### ISSUE THREAD

**Issue by katoquro** [gradle/gradle#13938]
### Expected Behavior
Code is compiled with `@CompileStatic` annotation without errors

### Current Behavior
Error from https://issues.apache.org/jira/browse/GROOVY-9090

### Context

First I thought that is mostly groovy issues but after I've found out a workaround (place all source files is one module and they are compiled as expected) I decided that is gradle related too.
I've built minimal version to reproduce the bug and attached to the groovy issue (and copy here)
https://issues.apache.org/jira/secure/attachment/13008170/13008170_GROOVY-9090.zip
You can se my [comment in groovy jira](https://issues.apache.org/jira/browse/GROOVY-9090?focusedCommentId=17162808&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17162808) for details

### Steps to Reproduce 
[GROOVY-9090.zip](https://github.com/gradle/gradle/files/4982834/GROOVY-9090.zip)

### Your Environment
Groovy 3.0.4 
```
------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------
Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a
Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.3 (Amazon.com Inc. 11.0.3+7-LTS)
OS:           Mac OS X 10.14.6 x86_64
```

**Comment by melix** [comment]
This doesn't seem to be related to Gradle: it's the compile groovy task which is failing.

**Comment by katoquro** [comment]
My first thought was the same but why it works if classes to compile are in the same module?

**Comment by melix** [comment]
IMO, It should be reproducible with plain Groovy `groovyc` on CLI. When you have separate modules, Groovy will resolve the class from bytecode and build a model from it which is different than if it has the class in the same module when the model (AST) is built from source.

**Comment by ljacomet** [comment]
Closing as a Groovy issue. Please update if you can share a reproducer showing that what works in Groovy fails in Gradle.
