### ISSUE TITLE
Invalid Jar Index Exception Thrown by TestKit 

### ISSUE THREAD

**Issue by rnc** [gradle/gradle#13939]
Running our functional tests work fine on Gradle 5.x and 6.3, 6.4 but not on 6.5. We get a strange exception from within a Gradle classloader.

### Expected Behavior

Tests pass.

### Current Behavior

The tests now throw https://gist.github.com/rnc/5d62bb5565f4db8636501977dbcc0724

### Context

We hit it during our work to upgrade to Gradle 6 ( https://github.com/project-ncl/gradle-manipulator/pull/218 ) I have tried under a Travis run with 6.4.1 (which works) but not with 6.5.1.

### Steps to Reproduce 

Please see above PR which contains the code to build/test project under Gradle 6. 

I realise you are extremely busy with such a lot of issues and would be happy to provide any logs and would appreciate any pointers on what to try :-) 

### Your Environment

Build scan URL:

**Comment by big-guy** [comment]
Would it be possible for you to run the build with `--scan` and provide a link here? That'll give us some more clues as to the dependencies going into the TestKit test classpath.

**Comment by rnc** [comment]
@big-guy Scan is https://scans.gradle.com/s/mp6wuymyuko5u

**Comment by rnc** [comment]
@big-guy Is there anything I can provide to help debug this please?

**Comment by rnc** [comment]
I'm marking this as a duplicate of #15269 as I provided a test case a better information on the latter.
