### ISSUE TITLE
6.6.0-rc-3 can no longer be built from source tars

### ISSUE THREAD

**Issue by serebit** [gradle/gradle#13930]
### Expected Behavior
When building from a .tar.gz source tar from a Gradle source tag, the build should (and used to, with 6.5.1) succeed.

### Current Behavior
In Gradle 6.6.0-rc-3, the build no longer succeeds. Instead, the following stack trace is given:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/serebit/Code/Solus/gradle-6.6.0-RC3/subprojects/build-scan-performance/build-scan-performance.gradle.kts' line: 19

* What went wrong:
An exception occurred applying plugin request [id: 'gradlebuild.internal.java']
> Failed to apply plugin [id 'gradlebuild.performance-test']
   > Could not create task ':buildScanPerformance:performanceTest'.
      > repository.branch must not be null
```

### Context
It would appear that Gradle is attempting to fetch Git repository information, and instead of handling an edge case where there is no Git information, the build instead fails instantly. If the build is instead performed from a clone of Gradle, the build succeeds.

### Steps to Reproduce 
```bash
wget https://github.com/gradle/gradle/archive/v6.6.0-RC3.tar.gz
tar -xf v6.6.0-RC3.tar.gz
cd gradle-6.6.0-RC3
./gradlew
```

### Your Environment
I'm on Solus 4.1 (Linux distribution), using OpenJDK 11.

**Comment by blindpirate** [comment]
Fixed in https://github.com/gradle/gradle/pull/13942
