### ISSUE TITLE
Artifact transform parameters isolation fails when using a groovy defined class

### ISSUE THREAD

**Issue by AmrAfifiy** [gradle/gradle#13946]
When registering an artifact transform with one of the parameters being an abstract class that is defined in a groovy script, Gradle fails to isolate the transform parameters because the class is not serializable. The problem doesn't occur when using an interface, or when using kotlin script.

Here is a build script that reproduces the issue

```
abstract class DataClass implements Serializable {
    @Input
    abstract Property<Integer> getIntValue()
}

abstract class Transform implements TransformAction<Parameters> {
    interface Parameters extends TransformParameters {
        @Nested
        DataClass getData()
    }

    @PathSensitive(PathSensitivity.NAME_ONLY)
    @InputArtifact
    abstract Provider<FileSystemLocation> getInputArtifact()

    @Override
    void transform(TransformOutputs outputs) {

    }
}

def artifactType = Attribute.of('artifactType', String)
def transformed = Attribute.of('transformed', Boolean)

dependencies {
    attributesSchema {
        attribute(transformed)
    }
    artifactTypes.getByName("jar") {
        attributes.attribute(transformed, false)
    }
    registerTransform(Transform) {
        from.attribute(transformed, false).attribute(artifactType, "jar")
        to.attribute(transformed, true).attribute(artifactType, "jar")

        parameters {
            getData().intValue.set(1)
        }
    }
}

configurations.all {
    afterEvaluate {
        if (canBeResolved) {
            attributes.attribute(transformed, true)
        }
    }
}
```

**Comment by lptr** [comment]
I tried the build script with Gradle 6.5.1, but not sure how to reproduce the issue you're seeing. I had to add `apply plugin: "java-base"` for the script to compile, but then I could run `./gradlew assemble` without a problem.

Can you maybe include a build scan of what you are seeing?

**Comment by AmrAfifiy** [comment]
It might be missing dependencies to transform, If you add a buildSrc with the script then it should fail. [Here](https://scans.gradle.com/s/lr5dw6ttfnjfc) is a build scan of the problem.
