### ISSUE TITLE
Nested finalizers should honor task order across projects

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#13941]
When there are multiple nested finalizers for a task and one of the finalizers is in a different project (and parallel is enabled) the finalizer task in the other project can execute even though one of the tasks it finalizes has not executed yet.

### Expected Behavior
All task relationships are honored and the finalizer in the other project does not execute until all tasks it finalizes have executed.

### Current Behavior
The finalizer in the other project sees the state of one of the tasks it finalizes as "MUST_NOT_RUN" because the post-execution step to force it to "MUST_RUN" has not been called yet.  So the finalizer in the other project thinks all of its dependencies are satisfied and since it is in a different project, it can start executing. 

### Context
This only happens when there are multiple nested finalizers (i.e. first finalizedBy second finalizedBy third) and the other finalizer is in a different project.

### Steps to Reproduce 
The following script reproduces the issue:
```
def fooTask = tasks.create("foo") {
    doLast {
        println "foo"
    }
}

project(':child') {
    ['first', 'second', 'third'].each { taskName ->
        task "${taskName}" { 
            doLast {
                sleep 1000
                println name
            }
        }
    }

    first.doLast { throw new RuntimeException('BOOM!') }

    first.finalizedBy second, fooTask
    second.finalizedBy third
    third.finalizedBy fooTask
}
```

Run `gradle first` to see the issue.  The `foo` task should not execute until after `third` executes, but because after `first` executes, `third` is still in the "MUST_NOT_RUN" state, so it shows up as being complete, allowing `foo` to start executing.

**Comment by jk12559** [comment]
I spent more time than I'd care to admit today debugging a very similar problem where mustRunAfter relationships were not honored between tasks that were dependencies of different finalizer tasks.  Here is a sample project that is a simplified version of what I was trying to work through today. 

```
project(':childA') {
    def finalizeTaskDependency = tasks.register('finalizeTaskDependency') {
        doLast {
            println name
        }
    }

    def finalizeTask = tasks.register('finalizeTask') {
        doLast {
            println name
        }
        dependsOn finalizeTaskDependency
    }

    tasks.register('fooTask') {
        doLast {
            println name
        }
        finalizedBy finalizeTask
    }
}

project(':childB') {
    def finalizeTaskDependency = tasks.register('finalizeTaskDependency') {
        doLast {
            println name
        }
    }

    def finalizeTask = tasks.register('finalizeTask') {
        doLast {
            println name
        }
        dependsOn finalizeTaskDependency
    }

    tasks.register('fooTask') {
        doLast {
            println name
        }
        finalizedBy finalizeTask
    }
}

project(':childA').tasks.named('finalizeTaskDependency') {
    mustRunAfter project(':childB').tasks.named('finalizeTaskDependency')
}
```

If I run `fooTask` in both child projects, the task execution queue shows the correct ordering, but on execution childA's finalizeTaskDependency task will incorrectly run before that of childB.

I also tracked this down to issues with the execution state being set to MUST_NOT_RUN.

**Comment by wolfs** [comment]
I tried this out with Gradle 8.0 RC1 and this seems to be fixed now: https://ge.gradle.org/s/7rhky7b5gfesi/timeline


![Image](https://user-images.githubusercontent.com/423186/212036207-1914b043-c236-41aa-a5c7-0533c8da0910.png)
