### ISSUE TITLE
dependencies not compiling

### ISSUE THREAD

**Issue by Laggg** [gradle/gradle#1394]
It's my first time working with dependencies and although when I build this (a minecraft mod) the build is successful, it then gives me a bunch of errors when I take it into my game that the class I used in one of my dependencies doesn't exist.

The two dependencies are 
`dependencies {
    compile 'joda-time:joda-time:2.8.1'
    compile 'net.hypixel:Java:1.0-SNAPSHOT'
}`

and they're at C:\Users\ddude\.m2\repository\joda-time\joda-time\2.8.1\joda-time-2.8.1.jar
and C:\Users\ddude\.m2\repository\net\hypixel\Java\1.0-SNAPSHOT\Java-1.0-SNAPSHOT.jar
So I think by adding mavenLocal() to my repositories, that should be the right place?

But it still returns errors when I run it... (not when building though)
If anybody can offer any advice with this, I'd appreciate it, I'm new to gradle ._.

Here's what I have right now:
`buildscript {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            name = "forge"
            url = "http://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.0-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'java'

version = "1.0"
group= "com.yourname.modid"
archivesBaseName = "modid"
sourceCompatibility = 1.8
targetCompatibility = 1.8

minecraft {
    version = "1.8-11.14.4.1577"
    runDir = "run"
}

repositories {
        mavenLocal()
}

dependencies {
    compile 'joda-time:joda-time:2.8.1'
    compile 'net.hypixel:Java:1.0-SNAPSHOT'
}

processResources
{
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}`

**Comment by eriwen** [comment]
@Laggg Could you please provide the errors you're getting? Aside, you're much more likely to get a helpful answer [on the forums](https://discuss.gradle.org/c/help-discuss) where more community members are able to answer questions like this.

**Comment by Laggg** [comment]
i fixed it by adding     from configurations.compile.collect { zipTree it }
in the processresources block :)
thanks anyways

**Comment by eriwen** [comment]
@Laggg Cool, glad you got it working :)
