### ISSUE TITLE
junit-platform test framework should contribute the `junit-platform-launcher` to the test runtime classpath

### ISSUE THREAD

**Issue by donat** [gradle/gradle#13955]
### Expected Behavior

The `org.junit.platform:junit-platform-launcher` should be part of the test runtime classpath with the same version as defined in the build.

### Current Behavior

If the launcher dependency is not explicitly defined in the build script then the junit-platform tooling might be unusable. 

### Context

https://github.com/eclipse/buildship/issues/980#issuecomment-665124002

**Comment by wilkinsona** [comment]
Still relevant, AFAIK.

**Comment by jvandort** [comment]
We fixed half of this with https://github.com/gradle/gradle/pull/21919
Now, any test tasks created with test suites have `junit-platform-launcher` on the runtime classpath. Though, the default test suite and any tests created manually will still load the launcher from the distribution. 

We need to do some re-work to how to manage these dependencies for non-suite tests.

**Comment by jvandort** [comment]
#24189 deprecates the behavior which loads potentially incompatible versions of junit-platform-launcher. Users will now need to provide the dependency themselves, unless they are using test suites. https://github.com/gradle/gradle/issues/24678 will finish up the deprecation process by adding proper warning messages when the user does not provide the dependencies themselves.
