### ISSUE TITLE
Cleaning the cache could be done in the background 

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/gradle#13951]
On Gradle < 6.5, it can take several minutes for gradle to clean the cache. Could this done in the background ?
![image](https://user-images.githubusercontent.com/1832925/88727886-5fb4e400-d0e5-11ea-9eca-842c4314d811.png)

**Comment by wolfs** [comment]
@stephanenicolas Are you using `--no-daemon`? That would cause the cleanup to happen in the foreground.

**Comment by wolfs** [comment]
Do you see this cleanup on your machine? I wonder why your build cache got so big so it takes so long to clean it up. One option to reduce the cleanup time would be to reduce the time entries are kept in the local cache: [DirectoryBuildCache.DirectoryBuildCache:removeUnusedEntriesAfterDays](https://docs.gradle.org/current/dsl/org.gradle.caching.local.DirectoryBuildCache.html#org.gradle.caching.local.DirectoryBuildCache:removeUnusedEntriesAfterDays)

Moving the cleanup in the background would mean that the daemon is not useable until the cleanup is finished. So starting a new build would cause starting a new daemon. You can start a new build on the project from a new terminal window, though I suppose that is not very convenient.
