### ISSUE TITLE
gradle download error width ssl

### ISSUE THREAD

**Issue by gaodda** [gradle/gradle#13961]
![image](https://user-images.githubusercontent.com/30640664/88871776-4af26080-d24b-11ea-95b9-eefd9e5b0041.png)

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. We'll close this issue for now. If you have more information, please feel free to create a new issue.

***

[optional additional text]
