### ISSUE TITLE
SNAPSHOT version are not searched across repositories

### ISSUE THREAD

**Issue by mflis** [gradle/gradle#1397]
Issue was already discussed on  [forum](https://discuss.gradle.org/t/gradle-does-not-check-snapshot-timestamps-across-repos/13674) and  in the [old issue system](https://issues.gradle.org/browse/GRADLE-2257). I'm bringing it here, because nobody else did, and it's still pain in the back in our company, as we make heavy use of snapshot versions.

### Expected Behavior

We have "-SNAPSHOT" version of artifact both in `mavenLocal() ` and in remote repository. I expect gradle to check both repositories looking for newest version of artifact. 

```
repositories{
		 mavenLocal() 
		maven {url "private company repo"}
	}
```

### Current Behavior

Gradle stops searching for newer "-SNAPSHOT" version after finding it in one repository. In example above, if `mavenLocal()` contains this artifact, remote repository won't be checked for newer version. `--refresh-dependencies` is not helping here

### Context

Our projects consist of many separate project, that are linked together. As all components are developed concurrently, developer needs to get newest version of components others develop on daily basis, so dynamic versions are necessity.  Components are either downloaded from company repo or form `mavenLocal()` (to test your component before sharing it with others)
Because gradle is not checking all repositories for newest versions, we often wondered why the newest version of component wasn't used  and that forced us to  build everything locally or purge local repository. 

### Steps to Reproduce (for bugs)

1. prepare following setup

```
repositories{
		 mavenLocal() 
		maven {url "private company repo"}
	}

dependencies {
  compile  group: 'test', name: 'dependency', version:"1.0-SNAPSHOT"
 }
```
2.  publish `test:dependency:1.0-SNAPSHOT` both to `mavenLocal()` and remote repository.
3.  publish newer version of`test:dependency:1.0-SNAPSHOT` only to  remote repository.
4.  use `--refresh-dependency` on project prepared earlier. Version from `mavenLocal()` will be used instead of  version from remote repository.
 

### Your Environment

- **Version :** Observed in all version of Gradle since 2.1. This [issue](https://issues.gradle.org/browse/GRADLE-2257) suggest problem is present since beginning of Gradle
- **Operating system** Observed on both Linux and Windows

**Comment by mhuebner** [comment]
We are also having trouble with this behaviour. Currently the only way to handle this (kind of a workaround) is to NOT publish into your loal repo and set 

```
    configurations.all {
        resolutionStrategy.cacheDynamicVersionsFor 0, 'minutes'
    }
```

So no changing versions will be cached and downloaded from remote (private company repo) on each build.

This is no long term solution but might help in your case.

**Comment by pzieminski** [comment]
Thank you for logging this bug. We're struggling with this issue also. We don't have the option to NOT publish to the local repo. We cannot publish shared libraries which have not been tested.

One way around it is two version the snapshot versions locally, install it to mavenLocal with a new version and update the version references in the gradle project to pick up the changes.

It's hacky, time consuming and error prone. We're continually having to change the pom files of the dependency we're testing and there are many in a multi module maven project.

**Comment by lacasseio** [comment]
Consider [this discussion](https://groups.google.com/d/topic/gradle-dev/7HSrC5XC_VU/discussion) as the direction we would prefer to take on this issue.

**Comment by vehovsky** [comment]
Hi, would anyone be willing to look at my pull request? @lacasseio 
Thank you

**Comment by hacki11** [comment]
any update?
the maven SNAPSHOT concept is broken within gradle

**Comment by natronite** [comment]
We are struggling with this as well. It always pulls the remote SNAPSHOT even though I published a newer one locally. Tried it with gradle 4.9 and 4.10. Same result.

**Comment by big-guy** [comment]
@natronite are the other builds that produce SNAPSHOTs also built with Gradle?  If so, the better answer here is to use [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html).  They don't require you to use snapshots to integrate things through mavenLocal.

**Comment by natronite** [comment]
@big-guy we have complex use cases. Sometimes we do indeed have something like composite builds but some of the things we do require us to use SNAPSHOTs. The same things works flawlessly with an older project using gradle 3.5.

**Comment by hacki11** [comment]
no idea why they won‘t add this. This is a mechanism i never thought of it would be missing intentionally.
