### ISSUE TITLE
Configuration avoidance in mixed language projects

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#13976]
When applying a Groovy plugin solely for use in testing, the `jar` task is never up to date.

The context is:

### Expected Behavior
If I haven't changed any files, nothing should be executed.

### Current Behavior
`jar` and all its dependents gets executed even if I run Gradle multiple times in a row.

### Context
Build is slower than it needs to be

### Steps to Reproduce 
Using wrapper for Gradle 6.4.1, create a project as follows:
* source roots `/src/main/java` and `/src/test/groovy/`. Put in some files.
* apply the `groovy` to be able to compile the tests. `java` gets transitively applied
* run `gradlew build -i` twice

The second run should be fully up to date. Instead you will see:

```
> Task :jar
[...]
Task ':jar' is not up-to-date because:
  Output property 'archiveFile' file .../build/libs/....jar has changed.
file or directory '.../build/classes/groovy/main', not found
:jar (Thread[Daemon worker,5,main]) completed. Took 0.073 secs.
```

**Comment by jbartok** [comment]
Might be related to https://github.com/gradle/gradle/issues/18228

**Comment by ljacomet** [comment]
Could not reproduce with the instructions provided.
If this is still an issue for you, please open a new issue with a full reproducer.
