### ISSUE TITLE
JPMS and Kotlin

### ISSUE THREAD

**Issue by Agcom** [gradle/gradle#13978]
### Expected Behavior

`compileJava` task should finish successfully. Thus, application plugin `run` and Intellij run icon (they depend on `compileJava`).

### Current Behavior

`compileJava` throws the following error,

```
error: module not found: kotlin.stdlib
    requires kotlin.stdlib;
```

So, I'm unable to run any code.

### Context

I'm trying to make a Kotlin JVM library. Using modular Java, cause it's the standard on Java 9 and higher.

### Steps to Reproduce 

**Step 1**: Create a simple Gradle project.

> `gradle init`

**Step 2**: Add Kotlin and Java plugins, enable modularity. Add Kotlin standard library dependency.

`build.gradle`:

```groovy
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.72'
}

repositories { mavenCentral() }


plugins.withType(JavaPlugin).configureEach {
    java {
        modularity.inferModulePath = true
    }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
}
```

**Step 3**: Add `module-info.java` to the main src. Add Kotlin stdlib module requirement.

`src/main/java/module-info.java`:

```java
module hello {
    requires kotlin.stdlib;
}
```

**Step 4**: Run the `compileJava` gradle task.

*No need to add any src code.

### Your Environment

[Build scan URL](https://gradle.com/s/vcoq3x7higfom)

**Comment by ljacomet** [comment]
Can you confirm that the Kotlin stdlib is a Java module? That is it has either a module-info or a Manifest entry.

**Comment by jjohannes** [comment]
The 1.3.x stdlib Jar does not contain a module descriptor. You need a specific std-lib Jar with the `modular` classifier`. classifier. It should change with Kotlin 1.4:

See also: 
- https://github.com/jjohannes/gradle-jpms-experiments/issues/1#issuecomment-617919533
- https://youtrack.jetbrains.com/issue/KT-21266
