### ISSUE TITLE
Toolchain is taken into account for up-to-date checks

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#13970]
Currently, toolchains should be resolved based on other inputs to a task (e.g. language level, source compatibility). We need to consider whether the toolchain itself (or properties thereof) should be considered as task inputs as well. For example: is it enough to have the java version as @Input and ignore the toolchain (even though different users may resolve to a different vendor). 
Currently, task output caching is disabled altogether if you use things like `compileTask.options.forkOptions.executable`

**Comment by wolfs** [comment]
Related: https://github.com/gradle/gradle/issues/9102

That means that the toolchain request should instruct Gradle which parts of the Java version used (vendor, major/minor version) should be taken into account.

**Comment by ljacomet** [comment]
Moving out of 6.7 as we do not plan any more changes for this in the first toolchain release.
