### ISSUE TITLE
Configurations containing a provided configuration are not resolved correctly

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#13977]
Adding a configuration to a configuration through a provider doesn't seem to behave correctly. I used the following script to reproduce:

```
val myConfiguration by configurations.creating

dependencies {
    implementation(kotlin("stdlib"))
    myConfiguration("javax.inject:javax.inject:1")
    if (isLazy) {
        implementation(provider { myConfiguration })
    } else {
        implementation(myConfiguration)
    }
}
```

Adding the configuration directly, the [build scan](https://scans.gradle.com/s/bmh7tqku6qrxq/dependencies?toggled=W1swXSxbMCwzXSxbMCwwXV0) shows that both dependencies are added to the compilation and runtime classpaths, as expected:

![image](https://user-images.githubusercontent.com/2517200/89094517-8b4ffc80-d379-11ea-8af3-e0f08ee07280.png)

However, adding the configuration through a `provider` causes `myConfiguration` to be resolved (which is a somewhat unexpected behavioral change), but the [build scan](https://scans.gradle.com/s/2cpbyg7on7vgs/dependencies?toggled=W1swXSxbMCwwXSxbMCw0XSxbMCwzXV0) does not list the resolved dependencies in the compilation or runtime classpaths:

![image](https://user-images.githubusercontent.com/2517200/89094546-d36f1f00-d379-11ea-9cb2-2ce04b6075fc.png)

This is obviously inaccurate, since the compilation would've failed if the dependency was truly missing. What's worst, the dependency is also missing in the published runtime classpath:

```
diff  ~/.m2/repository/com/twitter/test/incomplete-configuration/0.1.0-direct/incomplete-configuration-0.1.0-direct.module ~/.m2/repository/com/twitter/test/incomplete-configuration/0.1.0-lazy/incomplete-configuration-0.1.0-lazy.module
```

![image](https://user-images.githubusercontent.com/2517200/89094579-44163b80-d37a-11ea-9cc1-1f40e931d01c.png)

I put up a [reproducer](https://github.com/cesar1000/incomplete-configuration) using the latest nightly (6.7-20200731220031).

**Comment by melix** [comment]
Thanks for the bug report. It make me discover a "feature" of Gradle, that you could add a `Configuration` _as a_ dependency :) I had no idea what it would do. Looking at the code, it seems like there's an easy workaround: instead of adding a dependency on the configuration, just _extend from_ the configuration. Configurations are not lazy in any case, so it should have no impact.

**Comment by cesar1000** [comment]
Oh I've been using it extensively as a means to declare a hierarchy of configurations that I build during configuration time. Long story short, this is used in a Gradle plugin that provide a bunch of utilities to configure annotation processors. The processor and runtime dependencies of each processor are added to the right configurations conditionally based on the source sets where they have been enabled. I'm using `provider { configuration }` in order to delay the check for whether a configuration needs to be added to another configuration or not.

There's another reason why I'm using this model: provided configurations are resolved, which means that adding `provider { configuration }` is not equivalent to adding `configuration`. I'm not sure that this is intended, since the behavior is inconsistent for no obvious reason. However, it gives me the ability to resolve configurations using their own attributes before the resolved files get added to the containing configuration, which is a nice feature in itself.

One last thing I found: since `provider { configuration }` resolves the inner configuration, Gradle fails to find cycles among the configurations involved in the resolution, and may hang in an infinite loop. Fun times :)

**Comment by melix** [comment]
> Oh I've been using it extensively as a means to declare a hierarchy of configurations that I build during configuration time

But you could do `myConf.extendsFrom(other)` and it has the exact same semantics. That's what I discovered investigating this bug report.

> I'm using provider { configuration } in order to delay the check for whether a configuration needs to be added to another configuration or not.

I understand this is the intent, but that's not what it's going to do. The semantics are different as you have discovered. When you do:

```
implementation(someConf)
```

the (synchronous) code is strictly equivalent to `implementation.extendsFrom(someConf)`. In practice, this DSL code is replaced with something like `configuration.getByName("implementation").extendsFrom(someConf)`. Note that it doesn't call _add_ to the dependencies.

If you do: `implementation(provider { someConf })` then we don't know in advance what the provider will supply. It is assumed to be something that _can be converted to a `Dependency`_. For example, you can provide a `String` notation, which will be converted to a `Dependency` by Gradle. The thing you provide here is a `Configuration`, which, accidentally, _can_ be converted to a `Dependency`. Note that we're not talking about _hierarchy_ anymore, we're talking about a `Dependency`. This dependency, in case of conversion from a `Configuration`, is to resolve the configuration and put the list of resolved artifacts as "dependencies". This behavior is clearly not intended.

What I plan to do for this report is instead to capture the fact that what the provider supplies is a `Configuration` and _fail_. We are talking about another way to add a provider for a file collection and another for a _dependency list_ which would help here, but it wouldn't solve your problem.

In any case, if you're talking about hierarchies, I'd recommend using `extendsFrom` in any case. The fact that you want to do it _later_ (maybe it's going to extend, maybe not) should be handled by the lifecycle of your plugin instead (not saying that's easy).

In retrospect I think it was a mistake to deal with `Configuration` as `extendsFrom` in the beginning with this DSL, but I don't have the background to explain why it was done, maybe there was a good reason....

**Comment by cesar1000** [comment]
I suspect that adding the configuration to the hierarchy when declared as a dependency was well defined back when Gradle didn't support variant aware dependencies. Nowadays, the configuration hierarchy frequently behaves in unintuitive ways: resolvable configurations behave as dependency buckets if added to the hierarchy, `allDependencies.all { ... }` doesn't really work, or `provider { configuration }` treats the configuration as a regular file collection, instead deferring the addition of the configuration to the hierarchy (which I think is sound conceptually, and would be the behavior I'd expect, intuitively).

I understand that the behavior of `provider { configuration }` is logically inconsistent and, as such, undesired. However, a `Configuration` is a `FileCollection` so, technically, it can be converted to a dependency. As far as I know, any other file collection would be fair game with `provider` so, why make it fail if it happens to be a configuration?

In any case, it's worth considering that `extendsFrom(configuration)` and `provider { configuration }` are not equivalent, since the latter resolves `configuration` using its own attributes and resolution strategy, instead of just contributing its dependencies to the root configuration. In that regard, the error message in #14143 is not entirely accurate, and may cause confusion.

Also, to clarify, the core bug described in this issue repros with any file collection – not necessarily a configuration. My understanding is that providing a file collection should be well defined, since it can be converted into a dependency. Is that a supported use case?

**Comment by melix** [comment]
> I suspect that adding the configuration to the hierarchy when declared as a dependency was well defined back when Gradle didn't support variant aware dependencies. 

It's actually totally orthogonal to variant aware resolution. My feeling is that someone thought it would be a nice shortcut.

> Nowadays, the configuration hierarchy frequently behaves in unintuitive ways

Nothing has changed in this regards: configurations always behave like that independently of the Gradle version. We want to get rid of this concept of `Configuration` in the future, to remove all those confusing bits, but it's a long way to go.

> As far as I know, any other file collection would be fair game with provider so, why make it fail if it happens to be a configuration?

Because the `Configuration` case is the only one which behaves inconsistently. If you add a file collection as dependencies directly or using a `Provider`, they behave consistently. Note that I'm not saying the current behavior of `provider { configuration }` doesn't make sense: it's just confusing to have 2 different behaviors depending on what notation you use.

> In that regard, the error message in #14143 is not entirely accurate, and may cause confusion.

Do you have a suggestion in mind?

> Also, to clarify, the core bug described in this issue repros with any file collection – not necessarily a configuration. My understanding is that providing a file collection should be well defined, since it can be converted into a dependency. Is that a supported use case?

As of now it is :) But as stated in the PR, we'd like to provide more explicit APIs in the future.

**Comment by cesar1000** [comment]
Yeah, it makes sense about special-casing `provider { configuration }`. Also, I realize that adding a file collection (or a resolved configuration) to a configuration doesn't play well with publication (which is the crux of this issue report) since, from the point of view of Gradle, they are just plain local files. It seems to me that the core issue is that the publication is allowed to proceed at all, even if some of its dependencies can't be referenced in the metadata. Would Gradle be able to detect an attempt to publish and incomplete set of dependencies and fail fast?

The other issue is that the Dependencies tab in a build scan doesn't list file collection dependencies, which results in a partial view of a configuration. Is there a particular reason for that?

As for the error message, maybe you can just drop the recommendation to use `extendsFrom`, since it's not truly equivalent, and Gradle doesn't really offer an alternative.

Also, happy to hear that you're planning to replace `Configuration` in the future :)

**Comment by melix** [comment]
> Would Gradle be able to detect an attempt to publish and incomplete set of dependencies and fail fast?

It goes in the same direction as publishing resolved versions. Currently the implementation is quite simple, but there are different strategies we can apply, and even if we don't end up publishing resolved versions, we can certainly add some "linting" to detect problematic things. We already warn you, for example, if you publish things which have different semantics under Gradle and Maven.

> As for the error message, maybe you can just drop the recommendation to use extendsFrom, since it's not truly equivalent, and Gradle doesn't really offer an alternative.

Ended up clarifying that it should be used if your intent was to _inherit_ from the same set of dependencies as the other configuration.

**Comment by cesar1000** [comment]
> we can certainly add some "linting" to detect problematic things

This sounds like a great idea. This is much worse of a problem, in my view, than the Gradle/Maven case, since a configuration that contains raw files cannot be consumed in full through a publication – both in Gradle and Maven. As a result, the project and the binary dependencies have different semantics, which strikes me as a bug in every case.

To be clear, I understand now that this is intended behavior. Still, I'd really appreciate if Gradle would detect it and fail proactively, since it's entirely not obvious!
