### ISSUE TITLE
Allow build scripts to be named after the project name

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14001]
Given you have a project with subprojects:

```
├── my-first-library
│   ├── build.gradle.kts
│   └── ...
├── my-second-library
│   ├── build.gradle.kts
│   └── ...
└── settings.gradle.kts
```

It is hard to find back build scripts because they are all called `build.gradle.kts`. In the `gradle/gradle` build, we use the names of the projects instead for the script names like this:

```
├── my-second-library
│   ├── my-second-library.gradle.kts
│   └── ...
├── my-second-library
│   ├── my-second-library.gradle.kts
│   └── ...
└── settings.gradle.kts
```

You can currently only do this by adding some [extra configuration code to settings.gradle.kts](https://github.com/gradle/gradle/blob/1c8914266db5ad2be6db510cdcd0e2e956c28427/settings.gradle.kts#L183).

This should be a built-in feature of Gradle: If there is no `build.gradle(.kts)` script, we should automatically looks for a `<project-name>.gradle(.kts)` script.

**Comment by bamboo** [comment]
Maybe this capability should be provided by a settings plugin?

**Comment by jjohannes** [comment]
Test if there are issues with this in Android Studio. See: https://issuetracker.google.com/issues/162090314

**Comment by crgarridos** [comment]
I think this should be an explicit option (property?). making `mymodule.gradle` being a fallback of the absent of `build.gradle` could end being a mix of both and a potential mess 🙈

**Comment by bamboo** [comment]
I agree with @crgarridos. And it might have startup performance implications as well. I think something like a conventional `Settings` plugin that must be explicitly applied would be a better solution.

**Comment by LouisCAD** [comment]
What about multi-module projects that are more than 2 level deep? How would you name the gradle build files?

**Comment by michaelzangl** [comment]
I don't see any advantage in this. It makes renaming projects even more difficult. It makes finding the build file more difficult. And a modern IDE displays the project name in the editor tab any way as soon as you open more than one build.gradle file.

**Comment by jjohannes** [comment]
@michaelklishin thanks for the feedback. Good point about:

> It makes renaming projects even more difficult

This is something we have to keep in mind if we should move forward with something here.

> It makes finding the build file more difficult.

Could you elaborate on this a bit more? Why do you say "even more difficult"? 
It sounds like it is difficult today for other reasons, which are those?
 
Why do you think this setup would make it more difficult to find a build file?

**Comment by michaelzangl** [comment]
@jjohannes 
> Could you elaborate on this a bit more? Why do you say "even more difficult"?
> It sounds like it is difficult today for other reasons, which are those?
> 
> Why do you think this setup would make it more difficult to find a build file?

In a more complex gradle project, you have multiple build files. Most of the time I find them by searching for a file called <subproject path>/build.gradle. This is very convenient when searching using tools like IntelliJ or the github file tools. When renaming the build.gradle files to something else, this would not work.

When working with a new project, I do a quick `find | grep build.gradle` to get all build files and a quick overview of the subprojects => would not work either.

When working in the file explorer, I have project directories with 72 files/directories in a project dir (current project). Even simple subprojects often have 10+ files in the project dir, like checkstyle configs, IDE files, gitignores, webpack/npm files, additional gradle files. When searching for the build.gradle in such a directory, I always have to look at 'b'. Especially when having a file tree, this is currently my best way of spotting those files. It is not that easy, because they are mixed with many other files, but it is much easier than if every one of them had a different name.

**Comment by JLLeitschuh** [comment]
## Better Build File Names

I wrote this plugin last year to work as a simple fix for this problem in my projects so I didn't need to keep the same copy & pasted logic in every `settings.gradle.kts` project I maintain.

https://github.com/gradleweaver/better-build-file-names

**Comment by jjohannes** [comment]
After looking into this further we decided to not add anything specific to Gradle. Keeping your build scripts named `build.gradle(.kts)` stays the recommendation and works out of the box. We also use that in the build of Gradle itself now.

There are pros and cons for both approaches as discussed in the comments on this issues. The `build.gradle(.kts)` has the advantage that "main" build scripts are clearly recognisable and distinguishable from other scripts such as pre-compiled script plugins in buildSrc. The main drawback that was discussed here is discoverability. This is mitigated by modern IDEs such as IDEA, as you can also find the scripts by searching for the folder that contain the scripts.

That being said, it's also a matter of taste, size of project, and which tools you use what works best for you. If you prefer the "script-by-project-name" naming please continue to use it. You can use the `better-build-file-names` plugin by @JLLeitschuh  or add your own custom script code in settings. The main reason why we did not introduce an option in Gradle so that you can "just opt into it" without addition plugin, is that the default behaviour of this is not as obvious as it seems (what if there is not script? Should Gradle fail? What if there still is a `build.gradle`? etc.).

The confusing section about this topic mentioned in #13158 has been removed from the user manual in 6.7.
