### ISSUE TITLE
Upgrading a dependency's version via a rule breaks 'available-at' in its variant-aware resolution 

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#14017]
If a transitive dependency's version is upgraded via some rule in a resolution strategy and the new version uses `available-at` in its module metadata, then the resolution results won't include the module referenced in `available-at`.

### Sample project

Checkout [`h0tk3y/gradle-variant-aware-resolution-version-upgrade-bug`](https://github.com/h0tk3y/gradle-variant-aware-resolution-version-upgrade-bug).
Run `./gradlew checkClasspath`

### Steps to reproduce

Create a plain Java or Kotlin project.

Add a dependency on a **published** (*) module such as [`org.jetbrains.common:kotlin-scripting-common:1.4.0-rc`](https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-scripting-common/1.4.0-rc/) that depends on [`kotlinx-coroutines-core` version `1.3.7`](https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.3.7/) – this is a plain JVM-only module that doesn't have any Gradle module metadata.

```
dependencies {
    // transitively depends on kotlinx-coroutines-core version 1.3.7, which is a JVM-only module
    implementation(kotlin("scripting-common", "1.4.0-rc")) 
```

Add a resolution strategy rule that upgrades the version of [`kotlinx-coroutines-core` to `1.3.8-1.4.0-rc`](https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.3.8-1.4.0-rc/) – now this is a 'root' module of a multiplatform library whose `*.module` metadata points to a JVM variant in [`kotlinx-coroutines-core-jvm`](https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.3.8-1.4.0-rc/) referenced with `available-at` (don't be confused by the JAR in the `kotlinx-coroutines-core` module, it's there for compatibility reasons and is not used in variant-aware resolution):
```
configurations.all { 
    resolutionStrategy {
        eachDependency {
            if (requested.group == "org.jetbrains.kotlinx" && 
                requested.name == "kotlinx-coroutines-core"
            ) {
                // Upgrade the dependency to the version where it contains Gradle module metadata which
                // points to the JVM module using 'available-at'
                useVersion("1.3.8-1.4.0-rc") // Commenting this returns the 1.3.7 version JAR to the classpath
            }
        }
    }
}
```

Resolve the dependency in any configuration that gets it, like `compileClasspath`.

### Expected behavior

The `kotlinx-coroutines-core` version `1.3.8-1.4.0-rc` module metadata is read, the JVM variant is chosen and resolved from the `kotlinx-coroutines-core-jvm` module.

### Actual behavior

The resolution results will contain the module `kotlinx-coroutines-core` with the chosen JVM variant (as reported by `dependencyInsight`), but Gradle won't fetch the module `kotlinx-coroutines-core-jvm` that actually contains the JVM variant, and so the classpath won't contain the `kotlinx-coroutines-core` JVM artifact (or any other of its artifacts).

### Context

This issue affects migration of the kotlinx libraries from JVM-only to multiplatform, as the old naming scheme implied that the modules named like `kotlinx-coroutines-core` are the JVM modules, and now they should be the multiplatform 'root modules' that only contain Gradle module metadata and point to the other modules like `kotlinx-coroutines-core-jvm` as its variants. 

Upgrading the version of `kotlinx-coroutines-core` should not break dependency resolution, the consumer should still get the JVM artifacts in the resolution result. 

The Spring Framework project is already affected by this issue, [their workaround](https://github.com/sdeleuze/spring-framework/blob/master/spring-webmvc/spring-webmvc.gradle#L64) is to duplicate the dependency on `kotlinx-coroutines-core` in the project (as it won't be a transitive dependency anymore, it won't be affected).

–

(*) Bringing `kotlinx-coroutines-core` version `1.3.7` as a transitive dependency by adding a `project("...")` dependency is not affected

**Comment by ljacomet** [comment]
This is a side effect of #8315.

Because `org.jetbrains.common:kotlin-scripting-common:1.4.0-rc` depends on `kotlinx-coroutines-core:1.3.7` with an _exclude all_ transitives, the way `available-at` currently works is broken by that exclusion if there are no other edges to that dependency.

**Comment by sdeleuze** [comment]
Hi, is there any plan to fix this short-term since it will impact all users of Kotlin scripting when 1.4 will be released (should happen before the end of the month I think)?

**Comment by erokhins** [comment]
Also @h0tk3y @ligee if there any possible workarounds on kotlin side?

**Comment by ligee** [comment]
The `kotlin-scripting-common` dependency on the `kotlinx-coroutines-core` is transitive now, the fix is already in the 1.4.0 release, so I guess this issue could be closed.

**Comment by h0tk3y** [comment]
Well, the behaviour on the Gradle side in general is still there, so maybe the issue should stay. But dependencies on the Kotlin modules should be OK now.

**Comment by ligee** [comment]
The second check revealed that the fix was insufficient at least for the Spring case. So, the new one is on the way for Kotlin 1.4.10 release. cc: @sdeleuze

**Comment by ljacomet** [comment]
Fix has been merged.
