### ISSUE TITLE
Parent first configuration evaluation ordering is not working correctly with `evaluationDependsOn`

### ISSUE THREAD

**Issue by vryzhuk** [gradle/gradle#14013]
Parent configuration should be evaluated before it's children even if some other module is using `evaluationDependsOn` to the child module. Such issue makes it impossible to use parent modules as a module with common configurations for it's children. As a workaround, all such configurations should be put under root build script

```
parent/
  - build.gradle -> subprojects {group='com.project.sub'}
  - child1/                               <-- should be evaluated after parent
    - build.gradle
main/
  - build.gradle -> evaluationDependsOn(':parent:child1')
build.gradle -> subprojects {group='com.project'}
settings.gradle -> include 'main', 'parent', 'parent:child1'
```

# Expected Behavior
parent configuration is evaluated before it's children especially if order allows to do this (parent module do not depends on a child via `evaluationDependsOn` or via `evaluationDependsOnChildren`)

### Current Behavior
Child module configuration is evaluated before it's parent

### Context
We have 150+ multi-module gradle project and we want to use parent folders as an aggregate with common configurations for all children to logically split our build scripts. Alternative approach is to apply such common scripts in each children or have `evaluationDependsOn` from all children to parent

### Steps to Reproduce 
Steps to reproduce: run or check Actions build step https://github.com/vryzhuk/gradle-parent-ordering-issue

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue is not reproducible in Gradle 7.4 and later versions.
