### ISSUE TITLE
TestNG annotated Test method with attribute enabled=false are not reported as skipped

### ISSUE THREAD

**Issue by cedrik23** [gradle/gradle#1403]
This is a continuation of the bug reported and closed here: https://issues.gradle.org/browse/GRADLE-2643

See also: http://forums.gradle.org/gradle/topics/testng-disabled-tests-are-not-properly-reported-as-skipped

A TestNG testmethod like:

`import org.testng.annotations.Test;
public class MixedMethodsTest {
   @Test(enabled = false) 
   public void skipped() {
   }
}'

should be reported as skipped in xml results and default html reports. Yet it does not report these in the Gradle test report.

### Expected Behavior
To see the tested marked enabled=false as skipped tests on the Gradle test report

### Current Behavior
Disabled TestNG tests are not appearing as skipped in Gradle report

### Context
Our company is using TestNG with Gradle across most of our testing suites. We require the ability to see which tests are ignored for maintenance and auditing. Not fixing this will require us to move a large chunk of our testing to a different testing framework which is a huge refactor.

### Steps to Reproduce (for bugs)
1. Download example of allure reporting using Gradle and TestNG here:
https://github.com/allure-examples/allure-gradle-testng-example
2. Update one of the tests as "@Test(enabled=false)" and run "gradle clean build".
3. Open Gradle test report found at ..\allure-gradle-testng-example-master\build\reports\tests\test

You can clearly view that the test marked with "enabled=false" does not appear in the report as "Skipped"

**Comment by simple-elf** [comment]
See https://github.com/allure-framework/allure-java/issues/209

**Comment by radarsh** [comment]
Gentle nudge. Why is this still bug open? Are there any technical challenges in implementing this?
