### ISSUE TITLE
Jacoco HTML report displays wrong "created with" version

### ISSUE THREAD

**Issue by philbrown-mdt** [gradle/gradle#14033]
**To summarize the issue,** the _toolVersion_ setting is not respected, such that the generated report shows that it was created by a different version of JaCoCo. I also posted this on the [JaCoCo project](https://github.com/jacoco/jacoco/issues/1077). It it not clear if this is a JaCoCo defect or a Gradle Plugin defect.

### Expected Behavior
Generated report should show "Created with JaCoCo <version specified as toolVersion>" (in this case 0.7.6.201602180812)

### Current Behavior
Generated report shows this Created with... text but it is for a newer version than specified in the plugin. (in this case 0.8.4.201905082037)

### Context
We validate all the software we use in our projects, and although we configured our project with the validated version, the output causes confusion - is the expected version used? These are questions we need solid answers or fixes for.

### Steps to reproduce

  1. Configure Gradle such that jacoco plugin toolVersion is set to 0.7.6.201602180812 and the JaCoCo classpath is set to the same. This will look something like:
        ````groovy
        buildscript {
            repositories {
            maven {
                url = 'https://maven.google.com/'
            }
            jcenter()
            google()
            }
            dependencies {
                classpath 'org.jacoco:org.jacoco.core:0.7.6.201602180812'
            }
        }
        apply plugin: 'jacoco'
        jacoco {
            toolVersion = '0.7.6.201602180812'
        }
        ````
  2. Create a task of type JacocoReport to configure the inputs:
        ````groovy
        afterEvaluate {
            project.task([type: JacocoReport], 'jacocoTestReport') {
                group 'verification'
                dependsOn ['test']
                reports {
                    xml.enabled = true
                    html.enabled = true
                    csv.enabled = true
                }

                sourceDirectories = project.files(project.java.sourceSets.main.java.srcDirs)
                classDirectories = project.files(project.fileTree(dir: project.javaCompile.destinationDir, excludes: jacocoFileFilter))
                executionData = project.files(project.fileTree(dir: project.buildDir, includes: ['jacoco/*.exec''])
            }
        }
        ````
  2. Run the jacocoTestReport task created above

### Your Environment
* Windows 10
* Gradle 5.6.2

**Comment by LethalMaus** [comment]
Hi I'm running into a similar problem like this and in my case it seems like Jacoco settings within gradle are being ignored. I have way of reproducing it, it is simple enough. You will need the following setup (may be reproducible with some variance):

- Windows 10 10.0 amd64
- Android Studio 4.1.1
- Gradle 6.7
- Kotlin 1.3.72
- Groovy 2.5.12
- Ant Apache Ant(TM) version 1.10.8 compiled on May 10 2020
- JVM 15.0.1 (Oracle Corporation 15.0.1+9-18)

1. Create a new project in Android Studio and select Kotlin as a language. 
2. Setup Jacoco following the [gradle guide](https://docs.gradle.org/current/userguide/jacoco_plugin.html)
3. Have either a phone connected / emulator running, ready to be used for instrumented tests.
4. In the the terminal run:
`gradlew createDebugCoverageReport`
5. Wait until the report gets generated (running with no tests)
6. Check if the 'Created with JaCoCo' on the bottom right of the report matches what is defined within build.gradle
