### ISSUE TITLE
RepositoryContentDescriptor should support include/exclude version ranges

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#14041]
Hi folks,

I was looking into the docs for [RepositoryContentDescriptor excludeVersion](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/RepositoryContentDescriptor.html#excludeVersion-java.lang.String-java.lang.String-java.lang.String-)  and I couldn't find anything related to version ranges. 

For example:

```
repositories {
    maven {
        url = 'http://some-url'
        content {
             excludeVersion('com.google.guava', 'guava', '[19.0,)')
       }
    }
}

```

What I try to accomplish is to exclude  where the version is >= 19.0 on this case by using [Maven Version Ranges](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402)

Also, I couldn't find tests related to this use case: https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/RepositoryContentFilteringIntegrationTest.groovy

## Use case

Given the following repos

```
ivyRepo
|-- mygroup
|    |-- my-library 
|    |    |-- 1.0
|    |    |    +-- my-library-1.0.xml
|    |    |    +-- my-library-1.0.jar
|
```

```
mavenRepo
|-- mygroup
|    |-- my-library 
|    |    |-- 2.0.0
|    |    |    +-- my-library-2.0.0.pom
|    |    |    +-- my-library-2.0.0.jar
|    |    +-- maven-metadata.xml
|
```

If I have the following declared repositories:

```
repositories {
     maven {
        url = 'mavenRepoUrl'
    }
    ivy {
        url = 'ivyRepoUrl'
        layout 'pattern' , {
            artifact '[module]/[revision]/[artifact](.[ext])'
            ivy '[module]/[revision]/ivy.xml'
        }
    }
}
```

I should be able to add `excludeVersionRange` (that's the API I think it should be created to avoid a breaking change to current `excludeVersion` behavior

so it would look like this:

```
     maven {
        url = 'mavenRepoUrl'
    }
    ivy {
        url = 'ivyRepoUrl'
        layout 'pattern' , {
            artifact '[module]/[revision]/[artifact](.[ext])'
            ivy '[module]/[revision]/ivy.xml'
        }
        content {
             excludeVersionRange('mygroup', 'my-library', '[2.0.0,)')
        }
    }
}

```

## More context

I'm trying to apply these rules to thousands of groups and/or modules.

 One option was to use `excludeVersionByRegex` and use something like `^([0-9]|[1-9][0-9]*)\\.([0-9]|[1-9][0-9]*)\\.([0-9]|[1-9][0-9]*)(?:-([0-9A-Za-z-]+(?:\\.[0-9A-Za-z-]+)*))?(?:\\+[0-9A-Za-z-]+)?\$` to make sire we exclude versions that don't have 3 digits. However, looking at the implementation, using `ByRegex` suggest that also the group and module name will be regex and the `PatternSpecMatcher` [creates a `Pattern` for each part](https://github.com/gradle/gradle/blob/088067a35fc9d3855d8e041d2e365b35cb85ad51/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java#L298-L321). 

This could definitely work for us but a little hesitant to do it as we have a good amount of modules and this could be a performance impact, that's why having version range support seems like a better approach for this and also a nice addition to the current offering

**Comment by ljacomet** [comment]
Just clarify one thing around repository resolution. The content filtering in the example is useless because Gradle respects the order of repositories. And so any version `2.+` will be found in the first repo and thus the next repo will never be searched anyway.

I understand this was a sample for the issue and in reality, it might be beneficial to leverage content filtering. But I also wanted to make it clear that ordering can play a role in there for some use cases.

Example where it matters:

```
maven {
    url = 'mavenRepoUrl'
    content {
        excludeVersionRange('mygroup', 'my-library', '[,2.0.0)')
    }
}
ivy {
    url = 'ivyRepoUrl'
    layout 'pattern' , {
        artifact '[module]/[revision]/[artifact](.[ext])'
        ivy '[module]/[revision]/ivy.xml'
    }
}
```
