### ISSUE TITLE
Where do I put build logic?

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#14048]

**Comment by dsilvasc** [comment]
related: https://github.com/jjohannes/idiomatic-gradle/issues/11

**Comment by dsilvasc** [comment]
The gradle 8 release notes seem to suggest buildSrc: https://docs.gradle.org/8.0/release-notes.html#improvements-for-buildsrc-builds

**Comment by dsilvasc** [comment]
related: https://github.com/gradle/gradle/pull/23457

**Comment by gildor** [comment]
Currently, gradle init uses build-logic for this, but I think the proposal from https://github.com/jjohannes/idiomatic-gradle is better, it uses `gradle/plugins`, it also makes it more consistent with the default location of `libs.versions.toml`
I think it's really makes it harder to find

**Comment by jbartok** [comment]
We believe this issue is no longer relevant. Please file a new issue if necessary.

**Comment by dsilvasc** [comment]
Does not relevant mean the docs and "gradle init" are now in sync and not ambiguous anymore about whether to use buildSrc versus a "build-logic" explicitly included in settings.gradle?
