### ISSUE TITLE
Improve project naming conventions

### ISSUE THREAD

**Issue by donat** [gradle/gradle#14054]
This epic lists the necessary steps required before we can recommend the following naming conventions:
 - The project names correspond to the folder names (which is the default in Gradle)
 - All projects and subproject names should consistently use kebab case formatting: all letters lowercase, words separated with a dash (‘-’) character (e.g. kebab-case-formatting)
 - The root project name should be fixed in the settings file

**Comment by lacasseio** [comment]
@donat could you expand on what this issue means?

**Comment by donat** [comment]
@lacasseio I've added a brief description [above](https://github.com/gradle/gradle/issues/14054#issue-674900105).

**Comment by lacasseio** [comment]
Thanks for updating the issue. I'm a bit confused, is the issue for the Gradle build or as a recommendation to the community?

**Comment by donat** [comment]
It's going to be a general recommendation for all Gradle projects.
