### ISSUE TITLE
Eliminate the use of subprojects from gradle/gradle build

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#14069]
https://github.com/gradle/gradle/blob/dab6eafc521d5c91f786b1fba03454cfe756076d/buildSrc/build.gradle.kts#L26

**Comment by rieske** [comment]
https://github.com/gradle/gradle/blob/728d386966d9769c8b3211eb0eb188d5bbb6a2a3/buildSrc/subprojects/buildquality/src/main/kotlin/gradlebuild/ci-reporting.gradle.kts#L51

**Comment by rieske** [comment]
https://github.com/gradle/gradle/blob/ed08eb5704e8e496c3604389fd887805524f0b27/buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild/lifecycle.gradle.kts#L64

**Comment by rieske** [comment]
https://github.com/gradle/gradle/blob/master/subprojects/internal-build-reports/internal-build-reports.gradle.kts#L37

**Comment by jjohannes** [comment]
Reporting plugin: https://github.com/gradle/gradle/issues/15421

Remaining place is in root build script of buildSrc, which will be solved through #15438.
