### ISSUE TITLE
Bad stale issue instructions about re-opening issues

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#14067]
In your stale bot message you refer to the blog post https://blog.gradle.org/stale-issue-backlog
In that blog post you write:
> If an issue you care about is marked as stale or closed but it is still a concern for you: Please re-open and update the issue.

Unfortunatley you do the same mistake there that many maintainers do.
We cannot re-open issues that we did not close.
If I close an issue I opened, I can also re-open it.
But if someone else like you or the stale bot closed an issue, then I have not enough power to re-open the issue.
We have to get one of you to reopen it, or the stale bot would need to re-open an issue on comment if he closed it previously or something like that.

**Comment by bmuskalla** [comment]
Thanks for the feedback @Vampire. We were aware of that limitation but thought it wouldn't be too bad given we have a grace period of 3 weeks before the stale bot actually closes issues. Unfortunately, the bot we're using does [not support reopening things](https://github.com/probot/stale/issues/282). If you comment within the grace period, the stale bot will actually remove the `stale` label again automatically.
If you missed the grace period on an issue, please feel free to ping one of us to reopen it or create a new issue. Any existing issues I should take a look at?

**Comment by Vampire** [comment]
Nope, all well, I unstaled what is still relevant in 6.5.1 and closed what was fixed in the meantime.
It's just a common phrase of maintainers to say "I'm closing this, re-open it if you need more help", totally being unaware that the user is unable to re-open.

Don't get me wrong, I'm not complaining about your course to clean up the issue queue.
I just question the concrete sentence "if the bot closed the issue, reopen it" as this is technically impossible and a user might search until christmas 2030 for the button to reopen. ;-)

**Comment by Vampire** [comment]
:-(

**Comment by bmuskalla** [comment]
It's been fixed!! Deployment just needed a few minutes
