### ISSUE TITLE
Introduce a consistent set of convention plugins for developing build logic in Java, Groovy and Kotlin

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#14072]

**Comment by big-guy** [comment]
`java-gradle-plugin`
`groovy-gradle-plugin`
`kotlin-dsl` -> `kotlin-gradle-plugin`?

Should be able to apply the Kotlin plugin in Groovy scripts too.

**Comment by bamboo** [comment]
_Kotlin Gradle plugin_ is how the Kotlin team [refers to their Kotlin Gradle plugin](https://kotlinlang.org/docs/reference/using-gradle.html). Using the same term here would be confusing.

**Comment by jjohannes** [comment]
Duplicate of #15219
