### ISSUE TITLE
gradlew task on project starts chain-loading java processes

### ISSUE THREAD

**Issue by ROMVoid95** [gradle/gradle#14079]
By either initiating a new Gradle project or updating an existing project's gradle wrapper to any 6.5+ version, executing any gradlew task on project starts chain-loading java processes, with the task populating the terminal with `Starting a Gradle Daemon, (n) busy Daemons could not be reused, use --status for details`

Real example of output

    C:\path\to\project\dir> ./gradlew <any task>
    Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip
    .................................................................................................
    
    Welcome to Gradle 6.5!
    
    Here are the highlights of this release:
     - Experimental file-system watching
     - Improved version ordering
     - New samples
    
    For more details see https://docs.gradle.org/6.5/release-notes.html
    
    Starting a Gradle Daemon (subsequent builds will be faster)
    Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
	~ -------- ~
	Starting a Gradle Daemon, 35 busy Daemons could not be reused, use --status for details
	Starting a Gradle Daemon, 36 busy Daemons could not be reused, use --status for details

### Your Environment
Unable to produce a build-scan since the task will not complete or run correctly. Hopefully this is more than what might be needed
[System Information Output](https://haste.romvoid.dev/unuforuyab.yml)

**Comment by bmuskalla** [comment]
Thanks for the report. But there is not much we can do without further steps to reproduce. Did you try again using a newer version of Gradle (e.g. 7.x ?). Please let us know if the problem persists for you.
