### ISSUE TITLE
Change 'gradle init' to generate multi-projects

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14084]
- If the same project is a single project now, change it to have a (empty) root with a single subproject
- Also fix not-recommended details in templates if discovered (such as use of lazy task APIs or cross-project configuration)

**Comment by adammurdoch** [comment]
I would not make this an option, as every option adds complexity. I think the init templates should stick to the recommendation of never using the root project to produce software and just always generate the useful stuff into a subproject.

**Comment by vlsi** [comment]
I wonder if something like Gradle Zen could exist (see https://www.aether.ru/files/zencoding.pdf )

For instance:
`gradle init java#backend(spring,weblfux),kotlin-mpp#clients(coroutines,serialization),groovy#tests(spock)` which means `<template_name>#<project_name>(<dependencies>)`

I guess it would work amazingly well for the demos 😄

**Comment by jjohannes** [comment]
After more discussions, we decided to got with this suggestion: https://github.com/gradle/gradle/issues/14084#issuecomment-671613853

I changed the title and description.
