### ISSUE TITLE
Typo Configuration Cache in docs

### ISSUE THREAD

**Issue by JavierMeep** [gradle/gradle#14091]
Configuration cache docs said we should use `true` instead of `of`, `on` or `warn`.

https://docs.gradle.org/6.6/userguide/configuration_cache.html

```
Option configuration-cache doesn't accept value 'true'. Possible values are [OFF, ON, WARN]
```

**Comment by eskatos** [comment]
Thanks for the report @JavierMeep.

Starting with Gradle 6.6, `--configuration-cache` is a boolean flag with its `--no-configuration-cache` counterpart. You can use `--configuration-cache-problems` with a `fail` or `warn` value.

This was different in 6.5. From the snippet you posted above I guess you tried using the configuration cache with 6.5. Please use 6.6 instead.

**Comment by JavierMeep** [comment]
I am using `Gradle 6.6-bin` and I am writing it directly in gradle properties, it works with `on` but fails with `true`. Android Studio 4.0.1.
