### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by jrcacd** [gradle/gradle#14106]
From gradle 6.5 or higher on android studio 4.0, 4.1, 4.2
Gradle 6.4 works well.

* What went wrong:
Execution failed for task ':project1:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: Y:\prog\Projetos\project1\build\intermediates\navigation_json\debug\navigation.json

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
