### ISSUE TITLE
Add the support to run a task of included build via TAPI

### ISSUE THREAD

**Issue by vladsoroka** [gradle/gradle#14117]
There is no reliable way to run a task from the included build of a Gradle composite project.

### Expected Behavior
It should be possible to run a task from included build using Gradle Tooling API.
This invocation should honor composite configuration and rules defined for the whole composite.

### Current Behavior
There is no way to use a task from the included build when the root build directory used for the task running.
Composite configuration/rules are not used when the included build directory used for the task running.
A flat list of separate `--include-build` arguments (per included builds participants) can not be used when there is a transitive composite builds. Since it leads to "included build has the same root project name as the main build" error, see https://youtrack.jetbrains.com/issue/IDEA-207003 for details.

**Comment by nskvortsov** [comment]
this also affect compilation from IDEA, as compile tasks can not be properly launched 
details: https://youtrack.jetbrains.com/issue/IDEA-248124

**Comment by big-guy** [comment]
@rieske We should have TAPI tests similar to what we have in CompositeBuildTaskExecutionIntegrationTest
