### ISSUE TITLE
gradlew error in building corda

### ISSUE THREAD

**Issue by sanojuvce** [gradle/gradle#1412]
Hi, I am trying to build the corda code and it seems to be failing without giving much reason. Below is the debug trace, I am pretty much sure its related to proxy of my corporate network as it works just fine in my personal laptop. Even setting proxy information it doesn't seem to work.
Looking forward to your direction. Thanks.

### Your Environment

 * Build scan URL: 
My proxy settings:
systemProp.http.proxyHost=myhost
systemProp.http.proxyPort=myport
systemProp.http.proxyUser=myname
systemProp.http.proxyPasswor=mypass
systemProp.https.proxyHost=myhost
systemProp.https.proxyPort=myport
systemProp.https.proxyUser=myname
systemProp.https.proxyPassword=mypass

19:31:31.253 [DEBUG] [org.apache.http.impl.conn.PoolingClientConnectionManager]
                                                                               C
onnection request: [route: {tls}->http://myproxyadd:myport->https://plugins.gra
dle.org][total kept alive: 0; route allocated: 0 of 5; total allocated: 0 of 10]

19:31:31.279 [DEBUG] [org.apache.http.impl.conn.PoolingClientConnectionManager]
                                                                               C
onnection leased: [id: 0][route: {tls}->http://myproxyadd:myport->https://plugi
ns.gradle.org][total kept alive: 0; route allocated: 1 of 5; total allocated: 1
of 10]
19:31:31.298 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator]
                                                                               C
onnecting to myproxyadd:myport
19:31:31.330 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cac
he not set in the context
19:31:31.338 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthentication
                                                                               ]
                                                                               P
roxy auth state: UNCHALLENGED
19:31:31.350 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending
 request: CONNECT plugins.gradle.org:443 HTTP/1.1
19:31:31.407 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receivi
ng response: HTTP/1.1 200 Connection established
19:31:31.417 [DEBUG] [org.apache.http.client.protocol.ResponseProcessCookies] Co
okie spec not specified in HTTP context
19:31:31.426 [DEBUG] [org.apache.http.impl.client.SystemDefaultHttpClient] Tunne
l to target created.
19:31:31.673 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connect
ion 0.0.0.0:49342<->myproxyadd:myport closed
19:31:31.684 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connect
ion 0.0.0.0:49342<->myproxyadd:myport shut down
19:31:31.693 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connect
ion 0.0.0.0:49342<->myproxyadd:myport closed
19:31:31.703 [DEBUG] [org.apache.http.impl.conn.PoolingClientConnectionManager]
                                                                               C
onnection released: [id: 0][route: {tls}->http://myproxyadd:myport->https://plu
gins.gradle.org][total kept alive: 0; route allocated: 0 of 5; total allocated:
0 of 10]
19:31:31.716 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Tim
ing: Running the build script took 0.869 secs
19:31:31.731 [ERROR] [org.gradle.BuildExceptionReporter]
19:31:31.740 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed w
ith an exception.
19:31:31.752 [ERROR] [org.gradle.BuildExceptionReporter]
19:31:31.760 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
19:31:31.767 [ERROR] [org.gradle.BuildExceptionReporter] Build file 'D:\temp\cor
\corda\build.gradle' line: 53
19:31:31.776 [ERROR] [org.gradle.BuildExceptionReporter]
19:31:31.783 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
19:31:31.790 [ERROR] [org.gradle.BuildExceptionReporter] Error resolving plugin
[id: 'us.kirchmeier.capsule', version: '1.0.2']
19:31:31.799 [ERROR] [org.gradle.BuildExceptionReporter] > Could not GET 'https:
//plugins.gradle.org/api/gradle/2.10/plugin/use/us.kirchmeier.capsule/1.0.2'.
19:31:31.810 [ERROR] [org.gradle.BuildExceptionReporter]    > peer not authentic
ated
19:31:31.820 [ERROR] [org.gradle.BuildExceptionReporter]
19:31:31.827 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
19:31:31.833 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace o
ption to get the stack trace.
19:31:31.843 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:31:31.849 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
19:31:31.856 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:31:31.863 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 19.414 secs
19:31:31.872 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasin
g lock on cp_settings class cache for settings file 'D:\temp\cor\corda\settings.
gradle' (C:\Users\username-xxx\.gradle\caches\2.10\scripts\settings_7ncy3p
jenyey7v67o4aav7x4d\cp_settings).
19:31:31.881 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasin
g lock on settings class cache for settings file 'D:\temp\cor\corda\settings.gra
dle' (C:\Users\username-xxx1\.gradle\caches\2.10\scripts\settings_7ncy3pjen
yey7v67o4aav7x4d\settings).
19:31:31.888 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasin
g lock on cp_proj class cache for build file 'D:\temp\cor\corda\build.gradle' (C
:\Users\username-xxx1\.gradle\caches\2.10\scripts\build_8gga39fwli7hcvvpo7l
v59ev4\cp_proj).
19:31:31.897 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache artifa
ct cache (C:\Users\username-xxx1\.gradle\caches\modules-2) was closed 0 tim
es.
19:31:31.904 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine
.store.ResolutionResultsStoreFactory                                           ]
                                                                               D
eleted 0 resolution results binary files in 0.0 secs
19:31:31.912 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.me
mcache.InMemoryCachedRepositoryFactory                                         ]
                                                                               I
n-memory dependency metadata cache closed. Repos cached: 0, cache instances: 0,
modules served from cache: 0, artifacts: 0
19:31:31.922 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCach
e                                                                              ]
                                                                               C
losing cache plugin-use-metadata.bin (C:\Users\username-xxx1\.gradle\caches
\2.10\plugin-resolution\plugin-use-metadata.bin)
19:31:31.932 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasin
g lock on Plugin Resolution Cache (C:\Users\username-xxx1\.gradle\caches\2.
10\plugin-resolution).

**Comment by eriwen** [comment]
@sanojuvce I'm afraid there isn't enough information here to assess whether this is a bug in Gradle. You are more likely to get an answer from the community on the [help/discuss forums](https://discuss.gradle.org/c/help-discuss). 

Minimally, we would need example code that reproduces the problem in order to move forward.

**Comment by sanojuvce** [comment]
Hi eriwen, Sorry had put in those in a haste. I will post these in help. I believe we can mark this as not a bug. Thanks for your direction.
Regards,
Sanoj
