### ISSUE TITLE
Copy/Tar task filtering corrupts symbols in UTF-8 file

### ISSUE THREAD

**Issue by walkerburgin** [gradle/gradle#14134]
### Expected Behavior
I'd expect that string manipulation in a copy filter doesn't result in corrupted (`??`) characters in the destination file. 

### Current Behavior
I've observed that copy/tar task filtering occasionally corrupts symbols in a UTF-8 file and replaces them with `??`.

### Context
We're using Gradle to orchestrate our frontend build. One of the last steps in the build is to collect several webpack bundles into a TGZ. When we do that we replace several placeholder strings with the final asset's group/name/version. We hit bug this week where a JavaScript dependency that's dynamically creating a regular expression at runtime started failing in the browser with a "nothing to repeat" error, essentially because `/??/` is an invalid regular expression. We tracked this down in the build to the Gradle Tar task that replaces the placeholders inadvertently corrupting a `𝔜` character to `??`. Interestingly, the value of the strings we're replacing seems to matter -- injecting a version of `4.4.11` triggered the issue but `4.4.10-1-g9d13472cb4a` did not (which incidentally means we only hit the issue on full releases and not snapshots 🤦 ) . 

Potentially related: 
+ [Ant replace task corrupts symbols in UTF-8 file](https://stackoverflow.com/questions/8118494/ant-replace-task-corrupts-symbols-in-utf-8-file)
+ https://github.com/gradle/gradle/issues/4010
+ https://github.com/gradle/gradle/issues/11257
+ https://github.com/gradle/gradle/issues/1938

In the short term, I think we can hack around this by setting the `filteringCharset` to `ISO_8859_1` (inspired by [this](https://github.com/gradle/gradle/issues/4010#issuecomment-508985532) comment), but that seems a little unintuitive / potentially error prone. We've also considered just rolling a fully custom task to build the asset TGZ, but that would be a bummer. 

### Steps to Reproduce 
+ Unpack [repro.zip](https://github.com/gradle/gradle/files/5070030/repro.zip)
+ Run `./gradlew copy`
+ Open `build/simple.js` and you should see `??` in the middle of a sequence of `𝔜` characters. 

Sorry, I know this is a little bit of a contrived repro but I can't share the original JavaScript file where we caught this. 

### Your Environment

Build scan URL: https://scans.gradle.com/s/5k7ghenbekwsa

**Comment by vlsi** [comment]
An observation: `??` does appear in the output even if trivial `filter { line -> line }` is used

**Comment by vlsi** [comment]
I believe the bug is caused by [Ant's ReaderInputStream](Gradle uses it in https://github.com/gradle/gradle/blob/ee8e275fc45c7bc64128418f4ae217ed251abefd/subprojects/core/src/main/java/org/gradle/api/internal/file/copy/FilterChain.java#L66)

In other words, Ant's implementation
1) Reads characters from Reader
2) If it reads too much it returns just the desired number of `bytes` read, and it tries to convert "extra" characters to bytes to "read them later": https://github.com/apache/ant/blob/aab46b586e3d29100f072a352467e44b6715dc33/src/main/org/apache/tools/ant/util/ReaderInputStream.java#L140

Apparently, one must not try to split surrogate pairs, so Ant's implementation does have at least one bug.

**Comment by vlsi** [comment]
Here's the Ant bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=40455 (created 2006-09-10 11:51:50 UTC )

**Comment by vlsi** [comment]
As far as I see, Gradle does have `commons-io` in the dependencies, so Gradle fix could be trivial: use `ReaderInputStream` from `commons-io`.

**Comment by walkerburgin** [comment]
Amazing, thank you!
