### ISSUE TITLE
Release build freeze after update  gradel(com.android.tools.build:gradle) to (4.0.1)

### ISSUE THREAD

**Issue by nishantBabaria** [gradle/gradle#14156]
release build freeze after update gradle plugn from 3.6.3  to 4.0.0+
I tried every 4.0.0+ version but no luck

**toolsGradle** : com.android.tools.build:gradle:4.0.1
**distributionUrl ** = https\://services.gradle.org/distributions/gradle-6.4-all.zip

please help me

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by jbartok** [comment]
Closed due to lack of feedback.
