### ISSUE TITLE
Let user configure JavaCompile with source/target/release independant of a toolchain

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#14160]
Right now, the toolchain dictates the source/target level. This should be configurable yet defaulted by the toolchain.

**Comment by ljacomet** [comment]
After discussion, at the project level, using a toolchain will result in ignoring the `java.*Compatibility` values.
At the task level however, both `*Compatibility` and `release` can be used in combination with a toolchain compiler.
