### ISSUE TITLE
Error while trying to upgrade from gradle 5.2 to 6.0

### ISSUE THREAD

**Issue by darshanmehta10** [gradle/gradle#14163]
### Expected Behavior
`call()` method for `org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar` should return a directory

### Current Behavior
Groovy returns an error saying `groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar.call()`

### Context
I am trying to upgrade gradle version of a custom build plugin from 5.2 to 6.0. It has gor a following test code to check `clean` task:
```
def "test 'clean' task"() {
	def task = project.tasks.findByName('clean')

	expect:
	task instanceof Delete
	task.delete.iterator().next().call() == project.buildDir
}
```

When I try to build the project with `gradle2 build`, the above fails with the below error:

```
Condition failed with Exception: task.delete.iterator().next().call() == project.buildDir | | | | | | | | | 
groovy.lang.MissingMethodException: No signature of method: 
org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar.call() is applicable for argument types: () values: [] | | | | 
Possible solutions: wait(), any(), wait(long), map(org.gradle.api.Transformer), value(java.lang.Object), 
value(org.gradle.api.provider.Provider) | | | property(interface org.gradle.api.file.Directory, fixed(class 
org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory
```

I have tried comparing content of class `DefaultFilePropertyFactory` in both [gradle 5.2](https://github.com/gradle/gradle/blob/v5.2.0/subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java) and [gradle 6](https://github.com/gradle/gradle/blob/v6.0.0/subprojects/file-collections/src/main/java/org/gradle/api/internal/file/DefaultFilePropertyFactory.java) but can't see many structural changes (nothing related to `call()` anyway).

### Steps to Reproduce 
* Execute `gradlew build`

### Your Environment
Gradle Version: 6.0
Java Home: C:\jdk-11.0.5-win-x64

**Comment by big-guy** [comment]
`org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar` is an internal API and the implementation of it shouldn't matter in your tests. 

I think you can achieve something similar with (I didn't try this, but it should get you started):
```
	task.delete.targetFiles.files == [project.buildDir]
```

targetFiles is a file collection of all of the paths that will be deleted.
