### ISSUE TITLE
Scala compilation of protobuf generated code is broken because zinc leaks protobuf-java to compile classpath

### ISSUE THREAD

**Issue by gfjalar** [gradle/gradle#14168]
### Expected Behavior

I expect generated protobuf code to compile when the version used for generation and the version specified for compilation match.

### Current Behavior

It seems `protobuf-java` version used during compilation is the one that `zinc` configuration depends on, instead of the one that was specified through `dependencies`. See: https://scans.gradle.com/s/f7nralo66empe/dependencies?dependencies=protobuf-java&expandAll

### Context

I have confirmed that the setup used to work in Gradle 5.6.4. 

### Steps to Reproduce 

Here is a repository that contains a minimal example in which this issue is visible https://github.com/gfjalar/gradle-6.6-protobuf

To trigger the issue, run `./gradlew compileScala`.

### Your Environment

- Gradle 6.6: https://scans.gradle.com/s/f7nralo66empe
- Gradle 5.6.4: https://scans.gradle.com/s/jxuyvhipfxxck

### Other reports

- https://stackoverflow.com/questions/63010652/gradle-scala-plugin-zinc-1-3-5-leaks-protobuf-3-7-to-the-compiler-classpath

**Comment by SheliakLyr** [comment]
I think this might be fixed by #13992

**Comment by gfjalar** [comment]
@SheliakLyr It does! Thank you :) I've added a test case that verifies that zinc deps are not leaked anymore here: https://github.com/SheliakLyr/gradle/pull/1 (and also checked that the exact same setup fails when compiling with Gradle 6.6).

**Comment by SheliakLyr** [comment]
Great. Unfortunately I did not read your message before my PR got merged into gradle/master. Could you create a new PR that targets gradle/master instead of my fork?

**Comment by gfjalar** [comment]
Sure thing. No problem.
