### ISSUE TITLE
File system watching should support a build directory outside the build root

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/gradle#14174]
We want to be able to move our `buildDir`  in Gradle outside of the source tree. Our idea is that mounting the source tree in RAM would speed up the IDE. However, having the `build/` directory in the source tree makes the source tree too big.

However, this is currently not supported by file system watching, and the benefits of the VFS don't apply to such a build directory. It would be nice if VFS would support this use case, for us this is a mid-term goal.

**Comment by lptr** [comment]
FTR, there is a downside of keeping sources in-memory, i.e. if the machine crashes you lose all non-pushed work.

Having the `build/` directory mounted to a ramdisk is also an option. Doing so you could get better _build_ performance, while your work would be safe on disk. That use case is already supported (more or less; it might be a bit complicated to mount a `build/` directory under the project root).

**Comment by lptr** [comment]
There is a feature that would allow you to register the external build directory as watchable: https://github.com/gradle/gradle/issues/13598.

**Comment by wolfs** [comment]
Closing in favor of https://github.com/gradle/gradle/issues/13598.
