### ISSUE TITLE
Windows 10 Permissions Deleted on build directory Safe Mode required to delete

### ISSUE THREAD

**Issue by HarbingerNight** [gradle/gradle#14184]
### Expected Behavior
- gradle being able to delete files and directories under build
- owner of the project directory being able to delete directory
- administrators being able to delete directory beyond that

### Current Behavior
when a gradle build script fails on multiple occasions it changes the ownership and permissions of files and directories in build
directory. gradle then fails on the next build attempt complaining that its unable to delete a file or directory in build. The build directory is only deletable by restarting Windows in Safe Mode, none of the usual administrator overrides from File Explorer or Power Shell in Administrator mode work.

### Context
Continually have to go into Safe Mode to delete build directory

### Steps to Reproduce 
happens on multiple projects
under Windows 10 run gradle build and have it fail for any reason

gradle init settings:
both application and library
Kotlin Language
Kotlin DSL

### Your Environment
Windows 10
gradle 6.6
Powershell 7.0.3

occurs running gradle through all of the following:
PowerShell direct
VS Code
Idea Community Edition

**Comment by jbartok** [comment]
Could you pls. give us some concrete examples of folders you can't delete?

**Comment by jbartok** [comment]
Might be related to https://github.com/gradle/gradle/issues/14200.

**Comment by jbartok** [comment]
Closed due to lack of feedback.
