### ISSUE TITLE
EclipseModelBuilder incorrectly serialises access rules

### ISSUE THREAD

**Issue by donat** [gradle/gradle#1418]
Original bug report: https://github.com/eclipse/buildship/issues/338

Currently, the way how to specify access rules for Eclipse classpath entries is mutually exclusive in the TAPI and in the Eclipse plugin.

### Expected Behavior

Consider the following build script
```
apply plugin: 'java'
apply plugin: 'eclipse'
eclipse.classpath.file.whenMerged {
    def jre = entries.find { it.path.contains 'org.eclipse.jdt.launching.JRE_CONTAINER' }
    jre.accessRules.add(new AccessRule('accessible', 'sun/misc/**'))
}
```
The result classspath entry should look like this when the `eclipse` task is invoked and when the classpath is populated from `ElipseProject` model (by Buildship).
```
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/">
    <accessrules>
        <accessrule kind="accessible" pattern="sun/misc/**"/>
        </accessrules>
    </accessrules>
</classpathentry>
```
### Current Behavior

The build script above only works with the `eclipse` plugin and fails when the `EclipseProject` model is requested via the TAPI. 

If the access rule is created with `new AccessRule('0', 'sun/misc/**')` then the TAPI model works, but the `eclipse` task creates the following access rule which has no effect.

    <accessrule kind="0" pattern="sun/misc/**"/> 

### Proposed fix

`EclipseModelBulder` should parse the possible values access rule values (`accessible`, `nonaccessible`, and `discouraged`) and return the integer codes defined in the IAccessRule Eclipse interface. For backward compatibility (with existing Buildship configs) the `Integer.parseInt()` solution should be kept around.

**Comment by donat** [comment]
Code review: https://code-review.gradle.org/cru/REVIEW-6460

**Comment by big-guy** [comment]
LGTM, assuming it fixes the Buildship issue.
