### ISSUE TITLE
"java-test-fixtures" plugin causes compile errors if used with BOM dependencies

### ISSUE THREAD

**Issue by voytovichs** [gradle/gradle#14205]
I've noticed a compile error in a Gradle multi-module project that seems to be caused by simultaneously using two Gradle features: `java-test-fixtures` plugin and BOM dependencies.

To give a better context, I've prepared a project with no code in it to reproduce an error in isolation:
https://github.com/voytovichs/gradle-test-fixtures
- The project consists of two submodules `module-a` and `module-b`.
- Submodule `module-a` provides `module-a/src/testFixtures`, and `module-b/src/test` has a dependency on it.
- The root `build.gradle` declares a `implementation platform("io.servicetalk:servicetalk-bom:0.29.0")` BOM dependency for `allprojects`
- `module-a/build.gradle` declares a dependency `api "io.servicetalk:servicetalk-http-api"` (without specifying a version, relying on BOM)

### Expected Behavior
`./gradlew build` is expected to compile the project successfully

### Current Behavior
```
$ ./gradlew build
> Task :module-a:compileTestFixturesJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':module-a:compileTestFixturesJava'.
> Could not resolve all files for configuration ':module-a:testFixturesCompileClasspath'.
   > Could not find io.servicetalk:servicetalk-http-api:.
     Required by:
         project :module-a

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 549ms
3 actionable tasks: 3 executed
```

### Context
- Without `java-test-fixtures` plugin and without cross-module test dependencies the project compiles doesn't fail to compile
- I've noticed that the `module-a` dependency on service is `implementation` instead of `api`, it compiles successfully
- I've also noticed that adding explicit versions to the `module-a` dependency (i.e. `api "io.servicetalk:servicetalk-http-api:0.29.0` makes the project compile without the error

### Steps to Reproduce 
1. Check out https://github.com/voytovichs/gradle-test-fixtures
2. Run `./gradlew build`

### Your Environment
I'm running it on macOS Catalina 10.15.6 with Gradle 6.4.1

**Comment by ljacomet** [comment]
This is the normal behavior, though I can understand it can be surprising.

The test fixtures depends on the main source and dependencies, respecting the [API/Implementation separation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation). Your platform used in `implementation` is thus not visible for `testFixturesCompileClasspath`.
You need to either move the platform to `api` or add it as well to `testFixturesImplementation`.

If you run `./gradlew :module-a:dI --configuration testFixturesCompileClasspath --dependency module-a` in your reproducer, you get the following output:
```
> Task :module-a:dependencyInsight
project :module-a
   variant "testFixturesCompileClasspath" [
      org.gradle.usage               = java-api
      org.gradle.category            = library
      org.gradle.dependency.bundling = external
      org.gradle.libraryelements     = classes
      org.gradle.jvm.version         = 11
   ]
   variant "apiElements" [
      org.gradle.usage               = java-api
      org.gradle.libraryelements     = jar (compatible with: classes)
      org.gradle.dependency.bundling = external
      org.gradle.category            = library
      org.gradle.jvm.version         = 11
   ]

project :module-a
\--- project :module-a (*)

(*) - dependencies omitted (listed previously)
```

This report shows that the dependency graph of `:module-a:testFixturesCompileClasspath` contains two variants of `module-a`:
* The `testFixturesCompileClasspath` which is the root of the dependency graph and what we are trying to resolve.
* The `apiElements` which is the exposed variant of the main part of the project (the production code)

That later variant will _hide_ the _implementation_ dependencies, as designed.

**Comment by ov7a** [comment]
Closing this as it's not actionable
