### ISSUE TITLE
Race condition on access to the internals of Closure

### ISSUE THREAD

**Issue by john-auden** [gradle/gradle#1420]
Weird build exception `initialize must be called for meta class of class`
### Expected Behavior
Task succeeds

### Current Behavior
I am experiencing weird build error time to time (~1-2% of builds are failed):
```
18:52:50 Execution failed for task ':module1:unpackTars'.
18:52:50 > initialize must be called for meta class of class build_4eob1vc78iegmx7jkwtg7hvqr$_run_closure14$_closure50$_closure82$_closure83(class org.codehaus.groovy.runtime.metaclass.ClosureMetaClass) to complete initialisation process before any invocation or field/property access can be done
```
task implementation is pretty simple:
```
    task unpackTars {
        doLast {
            configurations.tars.files.each {
                tarFile ->
                    copy {
                        from(tarTree(tarFile)) {
                            dirMode 0755
                        }
                        into stageFolder
                    }
            }
        }
    }
```
Gradle 3.2.1
OS: Debian 6.0
JVM: Oracle SDK 1.8
Gradle build has around 50 modules and runs with `--parallel`
Jenkins server has 32 CPU cores and 128GB RAM, parallel build usually starts 32 threads
It seems like execution phase starts before configuration has been finished

### Steps to Reproduce (for bugs)
There are no steps to reproduce it, issue is intermittent

### Your Environment

 * Build scan URL:

**Comment by eriwen** [comment]
@john-auden Are you using `--configure-on-demand` or any other flags?

**Comment by john-auden** [comment]
Good morning,
We have few environments building different branches of the same application, some of them use `--parallel --configure-on-demand`, though I can't tell you if it correlates. I will try to disable everything, but `--parallel` to recheck. I am sorry there is no easy way to reproduce, so I'll have to just wait.

**Comment by eriwen** [comment]
@john-auden It's possible for execution to begin before configuration completes when using `--configure-on-demand`. Note that both of these flags are `@Incubating`, though we are working hard to get them perfectly stable.

**Comment by john-auden** [comment]
I have just got a build failure with the same error, verified start options. Only `--parallel` is enabled, configuration on demand is off.

**Comment by bmuschko** [comment]
Thanks for checking. Do you think you might be able to put together a (somewhat) reproducible example project?

**Comment by john-auden** [comment]
Hardly. We have a 6GB codebase with 50+ modules, so don't have any ideas how to replicate it in test project. BTW, thanks, with parallel build and fast host it takes ~4mins to build 4GB of artifacts

**Comment by big-guy** [comment]
I would try tweaking your extract task a bit:
```
task unpackTars(type: Sync) {
    dependsOn configurations.tars

    from {
        configurations.tars.files.collect {
            tarTree(it)
        }
    }
    into stageFolder
    dirMode 0755
}
```

Otherwise, you're creating lots and lots of anonymous classes to handle extracting each tar when there are lots of tars in `configurations.tars`.

**Comment by john-auden** [comment]
Thanks, I will definitely check it, though there are 1-2 tars in this configuration.

**Comment by astraia** [comment]
I am affected by the same problem, gradle 3.5 with parallel build turned on and daemon turned off.

I have the theory, it happens since I changed something in Jenkins, where now I start building two subprojects from the same root project concurrently (at the same time). Before, everything from the Jenkins POV was serialized (still parallel =true in gradle) I never saw this problem.

Sadly it is also hard for me to extract a reproducible example. Big and complex buildSrc and many projects.

I ll run the build with --stacktrace, and let you know next time it happens.

**Comment by lqbweb** [comment]
I am affected by the same problem, gradle 3.5 with parallel build turned on and daemon turned off.

I have the theory, it happens since I changed something in Jenkins, where now I start building two subprojects from the same root project concurrently (at the same time). Before, everything from the Jenkins POV was serialized (still parallel =true in gradle) I never saw this problem.

Sadly it is also hard for me to extract a reproducible example. Big and complex buildSrc and many projects.

I do have the full stacktrace:

> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mycompany_module_extras:generic:user_management:JAASUserAuthentication:jar'.
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
> 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
> 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
> 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
> 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
> 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
> 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
> 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
> 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
> 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
> 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
> 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
> 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
> 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
> 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
> 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
> 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
> Caused by: java.lang.IllegalStateException: initialize must be called for meta class of class com.mycompany.build.mycompanyPluginConvention$_configureBuild_closure4$_closure27(class org.codehaus.groovy.runtime.metaclass.ClosureMetaClass) to complete initialisation process before any invocation or field/property access can be done
> 	at com.mycompany.build.mycompanyPluginConvention$_configureBuild_closure4$_closure27.doCall(mycompanyPluginConvention.groovy:218)
> 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
> 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:637)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
> 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
> 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
> 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
> 	... 20 more
>

**Comment by grolfcry** [comment]
I have same issue on copy operation in multi module project with parallel execution (about 30%-40% of builds)

**Comment by john-auden** [comment]
@grolfcry Please use code snippet proposed by @big-guy. It worked for me.

**Comment by adrian-baker** [comment]
I hit this with a fairly simple copy-type task, using configureondemand + parallel.

```
task buildFeature {
    dependsOn configurations.feature
    inputs.file("${project.projectDir}/src/main/feature/feature.xml")
    outputs.file("${project.buildDir}/feature.xml")
    doLast {
        // The resolved version of the sdk dependencies is dynamic, so create a nested map of 
        // resolved {group} -> {artifact-name} -> {version} data for reference in the feature.xml. 
        def versions = configurations.feature.resolvedConfiguration.getFirstLevelModuleDependencies()
                .stream().collect(
                    Collectors.groupingBy({it.moduleGroup},
                            Collectors.toMap({it.moduleName}, {it.moduleVersion})));
        copy {
            from file("${project.projectDir}/src/main/feature/feature.xml")
            into "${project.buildDir}"
            expand(project.properties + [ "versions" : versions ])
        }
    }
}
```

I couldn't use the copy task, because I wanted to pass the versions of resolved configurations in expand.

Gradle 4.3.1,

**Comment by sagneta** [comment]
I hit the same problem with parallel + configureondemand. We had to turn it off. The odd thing is it would only occur on our TeamCity (a build system) on a VM. Never locally. No reliable way to recreate. This is obviously a race condition. 

Stuff happens. gradle is great. I'm not complaining but warning others.

Regards,
Steve

**Comment by eriwen** [comment]
Folks should usually avoid using configure-on-demand, in general, because it rarely provides performance benefits. We'll be working on other ways to improve configuration time.

**Comment by sagneta** [comment]
I see. Thanks for the response. I/We appreciate it.

**Comment by Ardesco** [comment]
We have turned off configureondemand, but we are still occasionally seeing this error.

our gradle.properties looks like this:

```
org.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.daemon=true
```

**Comment by axmetishe** [comment]
Looks like I've ran into the same problem:

```gradle
// dependencies.gradle
String max2017SdkPath = "${project.ext.sdkDirectory}/maxsdk2017"
HashMap max2017Libraries = [
  bmm             : 'bmm.lib',
  core            : 'core.lib',
  geom            : 'geom.lib',
  gfx             : 'gfx.lib',
  mesh            : 'mesh.lib',
  maxutil         : 'maxutil.lib',
  maxscrpt        : 'maxscrpt.lib',
  morpher         : 'Morpher.lib',
  poly            : 'Poly.lib',
  paramblk        : 'Paramblk2.lib',
  assetmanagement : 'assetmanagement.lib',
]

model {
  repositories { // this is a 128 line in the origin file
    libs(PrebuiltLibraries) {
      max2017Libraries.each { name, path ->  // this is a 400 line in the origin file
        libs.create(name) {
          String max2017HeadersPath = "${max2017SdkPath}/include"
          headers.srcDirs max2017HeadersPath,
            "${max2017HeadersPath}/xref",
            "${max2017HeadersPath}/maxscript",
            "${max2017HeadersPath}/maxscript/macros",
            "${max2017HeadersPath}/maxscript/foundation",
            "${max2017HeadersPath}/maxscript/maxwrapper",
            "${max2017HeadersPath}/maxscript/mxsplugin"
          String max2017LibPath = name == 'morpher' ? "${max2017SdkPath}/samples/modifiers/morpher/Lib/x64/Release"
            : "${max2017SdkPath}/lib/x64/Release"
          binaries.withType(StaticLibraryBinary) {
            staticLibraryFile = file("${max2017LibPath}/${path}")
          }
        }
      }
    }
  }
}
```

```batch
D:\path\to\project> gradlew mainVisualStudio -PpureGradle
Starting a Gradle Daemon (subsequent builds will be faster)
Parallel execution is an incubating feature.
> Task :foliage_exporter:foliage_exporter_mainDllVisualStudioProject FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'D:\path\to\project\gradle\dependencies.gradle' line: 400

* What went wrong:
Execution failed for task ':foliage_exporter:foliage_exporter_mainDllVisualStudioProject'.
> Exception thrown while executing model rule: repositories { ... } @ gradle\dependencies.gradle line 128, column 3
   > initialize must be called for meta class of class dependencies_5cwmil6twuutfnbbzojw986yk$_run_closure1$_closure2$_closure3$_closure25$_closure65(class org.codehaus.groovy.runtime.metaclass.ClosureMetaClass) to complete initialisation process before any invocation or field/property access can be done
```

I've tried to reproduce it with `--stacktrace` switch but no luck - any further builds were successful
```batch
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
OS:           Windows 10 10.0 amd64
```

**Comment by shevek** [comment]
Also affects gradle 5.6 with --parallel

**Comment by nhoughto** [comment]
Just got this with Gradle 6.2 with --parallel as well.

**Comment by shevek** [comment]
Confirmed by rewriting build logic: This _is_ a race condition on access to the internals of Closure. We are no longer affected by this bug, but it is valid.

I think the race may be related to accessing the internals of a lexically-outer closure when the lexically inner closure is called asynchronously to the outer closure, e.g. an afterConfigure callback, etc.

**Comment by nhoughto** [comment]
Bad bot, this should stay open and be fixed

**Comment by jjohannes** [comment]
Unfortunately, from all the comments it is unclear what the issue to fix is here.

Some of the shared samples have incorrect build logic (e.g. all configurations that are resolved should be declared as input).

If [this](https://github.com/gradle/gradle/issues/1420#issuecomment-601839193) is a general underlying problem, can someone please share a reproducer for that.

For now I assume that what this about. I adjusted the title and categorised this as a "groovy-dsl" bug. But we need clearer information to act on it.

**Comment by nhoughto** [comment]
maybe it just requires a better explanation of the problem / cause? i've had and worked around the issue, but never thought of either the racey or workaround groovy logic as 'incorrect'. Maybe its not clear to people when they are doing something incorrectly?

is this incorrect?
```
task buildFeature {
...
    doLast {
...
        copy {
            from file("${project.projectDir}/src/main/feature/feature.xml")
            into "${project.buildDir}"
        }
    }
}
```

if its `the internals of a lexically-outer closure when the lexically inner closure is called asynchronously to the outer closure` im not _quite_ sure what that means =)

**Comment by jjohannes** [comment]
That looks like correct build logic. If that is enough to reproduce the issue - thanks for sharing @nhoughto
