### ISSUE TITLE
Conflict between kotlin-dsl and plugin.serialization

### ISSUE THREAD

**Issue by radzio** [gradle/gradle#14211]
After updating kotlin to 1.4.0 I have big problems to make it work with kotlin-dsl because of older embedded kotlin version inside gradle. 

`buildSrc\build.gradle.kts`
```

buildscript {

    repositories {
        jcenter()
    }

    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-serialization:1.4.0")
    }
}

repositories {
    google()
    mavenCentral()
    jcenter()
}

plugins {
    `kotlin-dsl`
    kotlin("plugin.serialization") version "1.4.0"
}

kotlinDslPluginOptions {
    experimentalWarning.set(false)
}

gradlePlugin {
    plugins {
        register("MyPlugin") {
            id = "MyPlugin"
            implementationClass = "com.example.MyPlugin"
        }
    }
}



dependencies {
    implementation(gradleApi())

    implementation("com.android.tools.build:gradle:4.0.0")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0")
    implementation("io.ktor:ktor-client-core:1.3.1")
    implementation("io.ktor:ktor-client-okhttp:1.3.1")
    implementation("io.ktor:ktor-client-json:1.3.1")
    implementation("io.ktor:ktor-client-auth-jvm:1.3.1")
    implementation("io.ktor:ktor-client-serialization-jvm:1.3.1")
}
```

### Expected Behavior

Project sync without any problems. 

### Current Behavior
When syncing:

```
A problem occurred configuring project ':buildSrc'.
> Failed to notify project evaluation listener.
   > This version of the kotlin-serialization Gradle plugin is built for a newer Kotlin version. Please use an older version of kotlin-serialization or upgrade the Kotlin Gradle plugin version to make them match.
   > This version of the kotlin-serialization Gradle plugin is built for a newer Kotlin version. Please use an older version of kotlin-serialization or upgrade the Kotlin Gradle plugin version to make them match.
```

### Your Environment
Gradle 6.6
AGP 4.0.0
Kotlin 1.4.0

**Comment by icorbrey** [comment]
Just ran into this issue on Android Studio with Kotlin 1.4.0

**Comment by RomeuG** [comment]
Any news on this? I am facing the same problem.

**Comment by MrXlebNick** [comment]
Also interested in a solution for this!

**Comment by eskatos** [comment]
Gradle 6.8 comes with embedded Kotlin 1.4.20.
Note that the `kotlin-dsl` plugin and `.gradle.kts` scripts still compiles against Kotlin 1.3 language/stdlib.
In Gradle 7.0 this will be changed to compile against Kotlin 1.4 language/stdlib.

**Comment by speekha** [comment]
@eskatos I'm using Gradle 6.8.1 and still get that message.
Kotlin version is 1.4.30 and Kotlinx serialization is 1.0.1.
Is there anything special to do to solve this?

**Comment by eskatos** [comment]
@speekha nothing you can do really, except do what the warning says. This is a limitation in the backwards compatibility of kotlinx-serialization also due to the fact that Gradle embeds the Kotlin compiler. Gradle 7.0, unreleased at this time, will embed Kotlin 1.4.30. You can give `7.0-milestone-1` a try.

**Comment by skymansandy** [comment]
@eskatos Also facing the same issue.
Gradle 7.1.1
Kotlin: 1.4.31
AGP: 4.2.0

Any solution? Thanks!

**Comment by ljacomet** [comment]
This is unlikely to get resolved at this point in Gradle. The Kotlin version that Gradle uses for Kotlin build script supports is a constraint on Gradle plugins leveraging Kotlin themselves.

While there may be technical ways to lift these limitations in the future, the current team capacity does not allow for it.
