### ISSUE TITLE
Absent replacement setters in AbstractArchiveTask

### ISSUE THREAD

**Issue by hiljusti** [gradle/gradle#14218]
### Expected Behavior

Setters to replace the deprecating `setArchiveName()` and `setDestinationDir()`

### Current Behavior

`setArchiveName()` and `setDestinationDir()` are marked `@Deprecated` but both point to get methods with no replacement set methods.

### Context

I'm working on 6.5.1, and using `--warning-mode all` to check

I'm doing this to prepare for 7.0 compatibility. In our use case, we make use of `Zip` (which extends `AbstractArchiveTask`) inside our own custom tasks, and have some simple code that uses the inherited setters.

### Steps to Reproduce 

Perhaps easiest way to see it is in the generated javadocs or the source code?

- https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#setArchiveName-java.lang.String-
- https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#setDestinationDir-java.io.File-

Note both point to "get" methods, and a similarly named "set" method doesn't exist.

### Your Environment

N/A

**Comment by big-guy** [comment]
There aren't supposed to be setters.  The getter returns a Property, which has a separate methods for configuring the value to [allow plugins to lazily wire things together](https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties).

So this:
`archiveTask.setDestinationDir(someFile)`

becomes:
`archiveTask.getDestinationDirectory().fileValue(someFile)`

There are other setter methods (convention, set, etc), which one you need depends on what you're doing: https://docs.gradle.org/current/javadoc/org/gradle/api/file/DirectoryProperty.html

**Comment by hiljusti** [comment]
Thanks, I see!

It's a feature I wasn't familiar with.
