### ISSUE TITLE
PluginRepositoriesSpec does not have the helper methods RepositoryHandler has

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1422]
If I want to define `mavenLocal()`, or `mavenCentral()` or `jcenter()` and so on as plugin repository, there are no helper methods to do so. When deploying to one of those, you can also deploy the plugin marker artifacts, especially if you want to use a local build of a Gradle plugin.

It would be nice if the `PluginRepositoriesSpec` interface has the same helper methods that are also provided by the `RepositoryHandler` interface.

**Comment by bmuschko** [comment]
I am still not fully understanding the use case. Can you please give me concrete code example where you'd want this to work?

**Comment by Vampire** [comment]
Assume I develop a build that uses a Grade plugin. Now I need to modify the plugin to extend it. I want to test it in my consuming build. So I deploy the plugin to maven local. In the consuming building it would now be nice to be able to use mavenLocal(). The same for the others. If someone decides to deploy his plugin to maven central or jcenter but not to plugin central, they would be easily usable. I was not aware plugin central mirrors those. If this persists, maybe only mavenLocal makes sense.

**Comment by bmuschko** [comment]
I'd use TestKit to test your plugin under development in different consuming scenarios. That's basically the use case you are trying to fulfill except that you do it manually. Have you considered using TestKit?

**Comment by Vampire** [comment]
Sure, TestKit is great to formulate automated integration tests. And the plugin in question also uses it. But that's not the point. I wanted (a) test it in my reals use-case and (b) use it already with a local build until the maintainer accepted and released my PR.

**Comment by mkobit** [comment]
I think that the original request of this is resolved in [4.4](https://docs.gradle.org/4.4/release-notes.html), and possibly the overall request is more resolved by [#2528 - _Support composite builds for `plugins` block_](https://github.com/gradle/gradle/issues/2528)?

**Comment by Vampire** [comment]
Indeed 4.4 solves it, as `PluginRepositoriesSpec` does not exist anymore and was replaced by `RepositoryHandler` according to release notes.
