### ISSUE TITLE
Dominator view for dependency size in dependencies task and build scan

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#14222]
### Expected Behavior

What if there was a [dominator tree](https://www.ibm.com/support/knowledgecenter/en/SS3KLZ/com.ibm.java.diagnostics.memory.analyzer.doc/dominatortree.html) view for dependencies?
The dominator tree tells us which dependencies would be eliminated if a given dependency is removed.

For instance, here are the file sizes:

```
 34K org.jacoco.ant-0.8.5.jar
125K org.jacoco.report-0.8.5.jar
190K org.jacoco.core-0.8.5.jar
251K org.jacoco.agent-0.8.5.jar
 68K asm-commons-7.2.jar
 32K asm-analysis-7.2.jar
 49K asm-tree-7.2.jar
112K asm-7.2.jar
```

Here are the immediate dominators.
For example, `asm-commons -> org.jacoco.core` means `asm-commons` would disappear from the dependency tree if `org.jacoco.core` is removed (and `org.jacoco.core` is the minimal dependency that needs to be eliminated to remove `asm-commons`)

```
org.jacoco.ant -> ROOT
org.jacoco.core -> org.jacoco.ant
org.jacoco.report -> org.jacoco.ant
org.jacoco.agent -> org.jacoco.ant
asm -> org.jacoco.core
asm-commons -> org.jacoco.core
asm-tree -> org.jacoco.core
asm-analysis -> asm-commons
```

Then the immediate dominators would be as follows:

```
jacocoAnt - The Jacoco ant tasks to use to get execute Gradle tasks.
\--- 861K (34K self) org.jacoco:org.jacoco.ant:0.8.5
     +--- 451K (190K self) org.jacoco:org.jacoco.core:0.8.5
     |    +--- 112K org.ow2.asm:asm:7.2
     |    +--- 100K (68K self) org.ow2.asm:asm-commons:7.2
     |    |    \--- 32K org.ow2.asm:asm-analysis:7.2
     |    \--- 49K org.ow2.asm:asm-tree:7.2
     +--- 251K org.jacoco:org.jacoco.agent:0.8.5
     \--- 125K org.jacoco:org.jacoco.report:0.8.5
```

### Current Behavior

```
jacocoAnt - The Jacoco ant tasks to use to get execute Gradle tasks.
\--- org.jacoco:org.jacoco.ant:0.8.5
     +--- org.jacoco:org.jacoco.core:0.8.5
     |    +--- org.ow2.asm:asm:7.2
     |    +--- org.ow2.asm:asm-commons:7.2
     |    |    +--- org.ow2.asm:asm:7.2
     |    |    +--- org.ow2.asm:asm-tree:7.2
     |    |    |    \--- org.ow2.asm:asm:7.2
     |    |    \--- org.ow2.asm:asm-analysis:7.2
     |    |         \--- org.ow2.asm:asm-tree:7.2 (*)
     |    \--- org.ow2.asm:asm-tree:7.2 (*)
     +--- org.jacoco:org.jacoco.report:0.8.5
     |    \--- org.jacoco:org.jacoco.core:0.8.5 (*)
     \--- org.jacoco:org.jacoco.agent:0.8.5
```

### Context

I'm trying to optimize the project dependencies, and it might be the case that rarely used dependencies consume lots of bandwidth.

**Comment by ljacomet** [comment]
Aside from the size aspect, `dependencyInsight` provides information that can show the different paths bringing in a dependency.

There is no plan to do the size based part at all given the current team capacity.
