### ISSUE TITLE
More workers spawned than max-workers

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#14224]
### Expected Behavior

When executing a parallel build, there should be no more workers than the value of `max-workers`

### Current Behavior

Our build always ends up spawning 4 extra workers

### Context

We have a large build that tests a monolithic Java agent. A default `./gradlew build` will almost always bring a machine to its knees because max-workers defaults to the number of CPUs, but we end up 4 extra workers. This makes the experience for those new to our project painful (my laptop has 8 CPUs so I always have to run builds with --max-workers=4). This is the only repository I've seen the behavior with.

I've tried digging through build scans and info logs but couldn't see any reason for extra workers to appear. The workers are only test tasks, not compilation or other tasks.

Related issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/740

### Steps to Reproduce 

```
git clone https://github.com/open-telemetry/opentelemetry-java-instrumentation
cd opentelemetry-java-instrumentation
./gradlew :instrumentation:check --max-workers=4
```

Wait, as tests run more workers will eventually spawn past the limit of 4. Apologies for the build being very large / slow, if I knew how to make it smaller I would probably know how to fix the actual bug :)

### Your Environment

Mac OS X Java 11 Gradle 6.6

Build scan URL: https://gradle.com/s/odtmfjc3mc7ka
(Build failure is unrelated to scan the build faster, but it already had 8 workers at failtime)

**Comment by anuraaga** [comment]
I found that even in a much simpler repository, we still see this behavior - https://github.com/open-telemetry/opentelemetry-java/pull/1936 Any help would be great

**Comment by eskatos** [comment]
`--max-workers` limit the number of workers concurrently _in use_, doing actual work, but it doesn't limit the numbers of spawned workers.

Gradle will spawn test workers according to your build setup. I see you have `test` and `integrationTest` tasks in this multi project build. There are several properties of the `Test` task type that can influence this: maxParallelForks, forkEvery etc...

Note that Gradle may also fork processes for compilation tasks, aka. compilation workers. Those are kept alive during the build as they can be reused by subsequent compilation tasks.

The above can explain that you see more processes forked than max workers. But only `--max-workers` will be doing actual work at the same time.

Does the console show more than `--max-workers` doing work concurrently? What does the output of `jps -l | grep Gradle` show in the middle of the build?

**Comment by anuraaga** [comment]
@eskatos Thanks for the tip. I've tried running the jps command command and see 8 `GradleWorkerMain` even with `--max-workers=4`. I'm not sure how to differentiate between active and just spawned workers, are these all active?

e.g.,
```
91105 worker.org.gradle.process.internal.worker.GradleWorkerMain
88139 worker.org.gradle.process.internal.worker.GradleWorkerMain
87626 org.gradle.launcher.daemon.bootstrap.GradleDaemon
87786 worker.org.gradle.process.internal.worker.GradleWorkerMain
87789 worker.org.gradle.process.internal.worker.GradleWorkerMain
91085 worker.org.gradle.process.internal.worker.GradleWorkerMain
87788 worker.org.gradle.process.internal.worker.GradleWorkerMain
78412 org.gradle.launcher.daemon.bootstrap.GradleDaemon
27214 org.gradle.launcher.daemon.bootstrap.GradleDaemon
90991 worker.org.gradle.process.internal.worker.GradleWorkerMain
87790 worker.org.gradle.process.internal.worker.GradleWorkerMain
91028 worker.org.gradle.process.internal.worker.GradleWorkerMain
87610 org.gradle.wrapper.GradleWrapperMain
```

By the way, the reason I thought there were too many workers is the number of log lines for worker output also expands to the +4 mark, which isn't what I would expect - they do appear to be outputing logs concurrently. Sorry for leaving that out of my report :)

And anecdotally speaking, while I would expect the maximum workers computed by Gradle without any `--max-workers` flag to be a reasonable one for my machine, for this build without a cap on max-workers, there end up being 12 log lines (didn't try with jpl but quite certain it's 12 spawned workers) and the build essentially freezes as that is way more than capacity. Builds with --max-workers=4 never cause frozen computer, though other tasks stop working well - a sign of ~100% capacity rather than the ~150% capacity from the default settings.

**Comment by eskatos** [comment]
You can't distinguish active/idle processes. You'd have to look at debug logging and see how work is scheduled.

The console can display more lines than active workers with for example test tasks. One line is occupied by the test task plus one for each test workers. But the test task itself isn't doing actual work, just waiting for its workers. I agree this can be confusing.

As for builds slowing down your machine too much you could give `org.gradle.priority=low` a try, see https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

**Comment by anuraaga** [comment]
@eskatos Thanks for the information, yeah the log lines were tricky but in that case it sounds like this issue isn't a problem. We've been trying with priority=low to good effect :) Thanks for the pointer.
