### ISSUE TITLE
gradlePluginPortal() for RepositoryHandler

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1423]
Please also provide the `gradlePluginPortal()` helper method for the `RepositoryHandler`, not only for `PluginRepositoriesSpec`, so that you can easily use the Gradle plugin portal for settings plugins and also can compile agains plugins in the plugin portal.

**Comment by bmuschko** [comment]
This has been requested and rejected before. Please find our [reasoning in the PR](https://github.com/gradle/gradle/pull/613).

**Comment by Vampire** [comment]
As far as I read in that PR, there is no reasoning. There is though in the Devlist thread. But as far as I read there, you just miss proper usecases and if new ones come up, the discussion can continue. I provide two new ones here. I was not even aware plugin central is mirroring jcenter and maven central.
