### ISSUE TITLE
Dependency substitution failure with @jar qualifier

### ISSUE THREAD

**Issue by MrBean355** [gradle/gradle#14254]
### Expected Behavior
We should (I think?) be able to substitute dependencies that use a qualifier (e.g. `@jar` or `@aar`).

### Current Behavior
The build fails when adding a qualifier to an external module dependency that is being substituted with a local `project()` dependency.

When substituting dependencies like this:
```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute module('com.example:lib') with project(':my-own-module')
    }
}
```

✅ This works as expected:
```
implementation "com.example:lib:1.2.3"
```

❌ This does not work:
```
implementation "com.example:lib:1.2.3@jar"
```

The error:
```
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find lib.jar (project :my-own-module).
```

### Context
I'm trying to implement dependency substitution in our large Android project.
I want to be able to substitute some external module dependencies for some local `project()` ones.
Some of our dependencies need to use the `@aar` qualifier which seems to break the dependency substitution system.

### Steps to Reproduce 
[Sample project on GitHub](https://github.com/MrBean355/gradle-dependency-substitution)
_Note that I'm just using Retrofit as an example. The problem also happens to our internal dependencies when using the `@aar` qualifier._

### Your Environment
Build scan URL: https://scans.gradle.com/s/bbhng4jrq5lyi
Using Gradle wrapper 6.6 on a Macbook.
Building a minimalistic Java/Kotlin project.

🤖 Thanks for an awesome project!

**Comment by ljacomet** [comment]
Gradle 6.6 has introduced support for substitution rules that target classifiers or artifacts. See https://docs.gradle.org/current/userguide/resolution_rules.html#sec:substitution_with_classifier
You will need to be explicit about the artifact in that substitution.

**Comment by MrBean355** [comment]
Thank you, I guess I should RTFM more closely!
Appreciate the fast reply.
