### ISSUE TITLE
Deprecate `--recompile-scripts` flag 

### ISSUE THREAD

**Issue by melix** [gradle/gradle#1425]
The `--recompile-scripts` flag is ignored when the daemon is used: scripts won't get recompiled.

### Expected Behavior

Build scripts should be recompiled if the user requested it through command line, independently of the use of the daemon.

### Current Behavior

The `--recompile-scripts` flag only works when the daemon is off, or that a new daemon is spawned. The reason is the presence of the [CrossBuildInMemoryCachingScriptClassCache])https://github.com/gradle/gradle/blob/659eda9e9c4651d0374b25e0d9407723275d3a5b/subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/CrossBuildInMemoryCachingScriptClassCache.java#L29-L29). If it contains scripts (that is to say, it's not empty), which always happens after the first build, then the flag is ignored.

### Steps to Reproduce (for bugs)

Run a build:

`gradle tasks`

then run:

`gradle -i tasks`

Output should contain something like:

> Compiling build file '/tmp/groovylibrary/build.gradle' using SubsetScriptTransformer.
> Compiling build file '/tmp/groovylibrary/build.gradle' using BuildScriptTransformer.

But it doesn't. Add the following to the build script:

```
gradle.buildFinished {
 gradle.services.get(org.gradle.groovy.scripts.internal.CrossBuildInMemoryCachingScriptClassCache).cachedCompiledScripts.clear()
}
```

and to the same: now that we clear the cache at the end of the build, the script is recompiled, which indicates the cross-build cache gets into the way (because it finds a script with the same name, hash and timestamps, it doesn't bother recompiling).

### Your Environment

This is a low-impact bug.

**Comment by eriwen** [comment]
@melix Is this a recent regression?

**Comment by melix** [comment]
I don't think so. It has probably been introduced when cross-build script caching was added, which was, if I recall properly, around 2.4.

**Comment by oehme** [comment]
Since nobody has complained about that in such a long time, this makes me doubt the value of this switch.

**Comment by adammurdoch** [comment]
We should remove it and just fix whatever caching issues still affect script compilation (if any). There would always be `rm -rf` as a workaround for these situations.

**Comment by melix** [comment]
+1 to what @oehme and @adammurdoch said

**Comment by chris-doclily** [comment]
If this is a low-impact bug, what's the workaround for when I've edited a script but its changes aren't reflected in the build? adammurdoch mentioned "rm-rf", but what directory are we supposed to use that on?

**Comment by big-guy** [comment]
Do you have a reproducible example of when changes aren't reflected in the build?  

I think we don't have any known problems with caching of script compilation, so we would be interested in fixing that.

The workaround is to stop the daemon and re-run the build or edit the build script again.

**Comment by chris-doclily** [comment]
I don't have anything easily reproducible outside of my development environment. TBH, the problem is probably the way my script is structured. I'm new to Gradle and have been having a lot of trouble understanding the right way to do things. Things such as the way that code inside tasks runs before the task actually runs have been tripping me up. Thanks though.

**Comment by oehme** [comment]
>  I've edited a script but its changes aren't reflected in the build

That should never happen, as any change to the script will trigger a recompile. You are probably running into a different problem that just looks like the change didn't take effect. We'll need more details to get to the bottom of that though.

**Comment by eskatos** [comment]
The `--recompile-scripts` flag does work correctly for the Kotlin DSL when using the daemon, see [kotlin-dsl/../ScriptCache.kt](https://github.com/gradle/kotlin-dsl/blob/develop/provider/src/main/kotlin/org/gradle/kotlin/dsl/cache/ScriptCache.kt#L49). So I guess this bug only affects the Groovy DSL.

We've been using this flag during development of the Kotlin DSL. Doing `rm -rf` on the whole script cache is not strictly equivalent, `--recompile-scripts` triggers recompiling scripts for the current build only. I suppose we could live without this flag but it felt pretty convenient at times.

/cc @bamboo

**Comment by oehme** [comment]
> We've been using this flag during development of the Kotlin DSL. 

For what use case?

**Comment by eskatos** [comment]
@oehme debugging the Kotlin DSL implementation, when working on script compilation, so not really a "valid use case". We can definitely live without it.

**Comment by Ethan1983** [comment]
--configure-on-demand worked for me with newer versions of gradle.

**Comment by martin-braun** [comment]
@Ethan1983 It returns `Configuration on demand is an incubating feature.` for me, what does this mean?

Please bring `--recompile-scripts` back, I need to sync (but not build) using the terminal.
