### ISSUE TITLE
Gradle 6.6 hangs when executing `test` task

### ISSUE THREAD

**Issue by mattmook** [gradle/gradle#14252]
### Expected Behaviour
Unit tests should execute as expected.

### Current Behaviour
Under Gradle 6.6 the build hangs indefinitely (I have left computer running for over 6 hours) when running `test` task. No tests start to execute.

### Context
Upgrading project from Gradle 6.5.1 to Gradle 6.6 with no other changes.

### Steps to Reproduce 

Check out and build this commit with `./gradlew certificatetransparency:test` which uses Gradle 6.6:
https://github.com/babylonhealth/certificate-transparency-android/tree/197bc16a2a7700ee9cceb24fa01caf7800ec72c9

Observe that execution hangs when it reaches the `test` task. I have attached thread dumps of the running Java processes for Gradle:
[dump1.txt](https://github.com/gradle/gradle/files/5112047/dump1.txt)
[dump2.txt](https://github.com/gradle/gradle/files/5112048/dump2.txt)

Contrast this to running the same task with Gradle 6.5.1:
https://github.com/babylonhealth/certificate-transparency-android/tree/ef1d81df1ddf79b8a101861468ab147de2facb80

### Your Environment
Running on macOS Catalina 10.15.6, Java 11.0.1+13-LTS

Unable to generate a build scan as the build under Gradle 6.6 never completes.

**Comment by ghale** [comment]
@mattmook Is this something intermittent or is happening all the time for you?  I checked out the commit listed above and gave it a try and the build completed just fine for me.  Looking at the stacktrace, it's not in a part of the build where I would expect a deadlock or anything, so it makes me wonder if this is reproducible or not.  

One thing that may or may not be relevant is that you mention above that you are running with JDK11, but when I tried to use 11, the `kotlinCompile` task failed because of a removed feature.  The task ran fine with JDK8, though.  Are you actually using JDK11 or was that a mistake?

**Comment by mattmook** [comment]
Seems to be happening all the time... interestingly the JDK11 I was pointing to wasn't complaining about the deprecation, having reverted to the system JDK I see the compile time issue and have fixed that in the branch https://github.com/babylonhealth/certificate-transparency-android/tree/deps which uses Gradle 6.6.1 but still getting the hanging.

```
B-1565:certificate-transparency-android matt.dolan$ ./gradlew --version

------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
OS:           Mac OS X 10.15.6 x86_64
```

I've also tried switching to JDK 8 but it's still hanging for me ¯\_(ツ)_/¯

```
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_261 (Oracle Corporation 25.261-b12)
OS:           Mac OS X 10.15.6 x86_64
```

Is this a Mac specific problem? The same build worked fine on CI https://github.com/babylonhealth/certificate-transparency-android/runs/1075066669?check_suite_focus=true
