### ISSUE TITLE
Smoke test Gradle Module Metadata with Kotlin Gradle Plugin 1.4

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#14255]
https://github.com/gradle/gradle/pull/14147 adds the Kotlin Gradle Plugin in smoke tests but skips it in `ThirdPartyGradleModuleMetadataSmokeTest` as the metadata changed, the test data needs to be updated.

Kotlin Native 1.4 adds `artifactType=org.jetbrains.kotlin.klib` attribute.

This issue is about updating `ThirdPartyGradleModuleMetadataSmokeTest` and its test data to cover both KGP 1.3 and 1.4.

**Comment by ljacomet** [comment]
@eskatos Are you planning on fixing this yourself?

**Comment by eskatos** [comment]
@ljacomet not now, still 🌴. I'm also not sure about how to approach this, duplicate all the test data? template it?

**Comment by jjohannes** [comment]
I think we already discussed improvements: https://github.com/gradle/gradle/issues/12425
