### ISSUE TITLE
Gradle Module Metadata vs. Non-standard Ivy Pattern Layout

### ISSUE THREAD

**Issue by smichovan** [gradle/gradle#14267]
Gradle Module Metadata is not published in case that custom patternLayout is defined for Ivy repository.

### Expected Behavior
We wanted to upgrade to new version of Gradle (from 5.6.2 to 6.6) in order to use Fearture Variants of components, but we use our own pattern layout.

### Current Behavior
When pattern layout is defined like this:
```gradle
repositories{
        ivy {
            setUrl("...")
            patternLayout {
                artifact("[organization]/[revision]/[module]/[artifact]-[revision](-[classifier]).[ext]")
                ivy("[organization]/[revision]/[module]/ivy-[revision].xml")
            }
        }
}
```

then a message appears in log when publishing: 
"Publication of Gradle Module Metadata is disabled because you have configured an Ivy repository with a non-standard layout"

So I can understand it is sort of intended behaviour. Also I found this comment here https://docs.gradle.org/current/userguide/upgrading_version_6.html:

"Gradle versions from 6.0 to 6.3.x included could generate bad Gradle Module Metadata when publishing on an Ivy repository which had a custom repository layout. Starting from 6.4, Gradle will no longer publish Gradle Module Metadata if it detects that you are using a custom repository layout."

### Context
I can see it that we have to make a choice. Either switch to standard ivy repository layout which is quite a big change for us. Or resign on using new gradle features base on Gradle Module Metadata - which is really a pitty. 

Is there a plan to support publishing Gradle Metada even with custom repository layout?

**Comment by ljacomet** [comment]
There is no intention to add support for custom Ivy layouts to Gradle Module Metadata publishing.
While some layouts might be made to work, we would not be able to support all of them.
