### ISSUE TITLE
ERROR: Process command "C:\Program Files\Java\jdk-14.0.1\bin\java.exe" finished with non-zero exit value 1 Running Ofbiz error . 

### ISSUE THREAD

**Issue by LavanyaRose497** [gradle/gradle#14288]
DESCRIPTION: This error occurred while starting the ofbiz. 'gradle cleanAll loadAll' command gave BUILD SUCCESSFUL. while starting ofbiz using the command 'gradle ofbiz'. Kindly help me to fix this issue

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Please provide more steps how to reproduce this and we can reopen the issue.
