### ISSUE TITLE
Add 'compileOnlyApi' configuration to java-library projects 

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14299]
The `java-library` plugin should add a configuration called `compileOnlyApi`. (Which we already use here #14240.)

The meaning is "This is on the API but only at compile time, and NEVER on the runtime classpath".

A typical use cases is an annotation library, where the annotation need to be accessible transitively by an annotation processor but where the annotations are not available/used at runtime.

The definition is:
```
Configuration compileOnlyApi = configurations.maybeCreate("compileOnlyApi");
configurations.getByName(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME).extendsFrom(compileOnlyApi);
configurations.getByName(JavaPlugin.API_ELEMENTS_CONFIGURATION_NAME).extendsFrom(compileOnlyApi);
```

**Comment by dsvensson** [comment]
@jjohannes Why is this not more generally available? Shouldn't I be able to have a Kotlin project with compileOnlyApi without including java-library?

**Comment by jjohannes** [comment]
@dsvensson it's the same as with `api`. It is expected to combine a JVM language plugin (Groovy, Kotlin, Scala) with the `java-library` plugin if you built a library in the corresponding language.

See: https://docs.gradle.org/current/samples/sample_building_kotlin_libraries.html#review_the_project_files

**Comment by jjohannes** [comment]
Apart from that, this is a convenience feature. It uses only public APIs. You can setup a `compileOnlyApi` configuration yourself if you desire. (e.g. for older Gradle versions)

https://github.com/jjohannes/what-if-gradle-metadata/blob/master/libraries/guava/build.gradle.kts#L20-L25

**Comment by dsvensson** [comment]
Thanks for the clarification.

**Comment by tbroyer** [comment]
Just now looking in more details at that new configuration (which was a really great news for me!), as I'm preparing a presentation about Gradle at my company, and it looks to me like `testCompileClasspath` should extend `compileOnlyApi`, which doesn't seem to be the case currently.

Should I open a new issue?

**Comment by jjohannes** [comment]
@tbroyer currently `testCompileClasspath` does on extend `compileOnlyApi` similar to how it does not extend `compileOnly` . Both could be debated, but I would keep it like it is.

You _could_ say because it is is "api" it should always be on the classpath. But with that argument `implementation` should not be on the test compile classpath by default (which it currently is).

I would either put everything on the "test" compile classpath (including `compileOnly`) or keep it as it is to not make things more complex.

Test classpath setup is very individual depending on which types tests you write. I think there is not the one right answer.

A problem with Gradle's current model for this is that it is easier to add an `extendsFrom` than removing one.
So if you want it in your tests, you can add the one line of config code to extend-from `compileOnly` which includes `compileOnlyApi` (or only extend `compileOnlyApi`).

**Comment by tbroyer** [comment]
IMO `testCompileClasspath` should **not** include `compileOnly`, it's ok as it is today; but it **should** include `compileOnlyApi`, just like anything depending on the project would have it in it's compile classpath.
In other words, `testCompileClasspath` should be `apiElements`+`implementation`.

**Comment by jjohannes** [comment]
@tbroyer you have a point there. Can you open a separate issue so that it is easier for us to discuss the topic?

**Comment by tbroyer** [comment]
Done #15017
