### ISSUE TITLE
Bump Groovy dependency to 2.4.9

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#1431]
While [investigating some Java 9 issues](https://discuss.gradle.org/t/current-java-9-status-and-roadmap/21459) I found that Groovy has problems dispatching some calls. 

As a quick test, open a the Groovy shell and run this:

> Collections.newSetFromMap([:])

It passes under Java 8 with any version of Groovy, succeeds in 2.4.8 + Java9, but fails in Groovy 2.4.7 + Java9 with:

> No signature of method: static java.util.Collections.newSetFromMap() is applicable for argument types: (java.util.concurrent.ConcurrentHashMap) values: [[:]]

Any chance we can get a Gradle Groovy version upgrade for the next versions?

### Expected Behavior
The artifactory plugin should be applied without errors for all supported versions of Java and also Java9ea. The first error I see can be resolved as described above. If there are further errors, they can be addressed as separate issues.

### Current Behavior
The artifactory plugin works with Java 8, but does not work with Java 9.

### Context
I can not use the artifactory plugin with Gradle 9. There are likely other plugins that would fail for the same reason, but I haven't gotten to them.

### Steps to Reproduce (for bugs)
1. Install Java9-ea+154
2. Install Gradle 3.3
3. Create a simple build.gradle with the following content:
```
plugins {
    id 'com.gradle.build-scan' version '1.0'
    id "com.jfrog.artifactory" version "4.4.8" // update periodically
}
```
4. Run `gradle tasks` (do not use Gradle Wrapper - that is a separate problem)

### Your Environment
* Windows 10 x64
* Gradle 3.3
* Java HotSpot(TM) 64-Bit Server VM (build 9-ea+154, mixed mode)
* `-Dscan` doesn't work as the scan license is not accepted (the license block is evaluated after the plugin section that throws the exception)

**Comment by bmuschko** [comment]
@ddimtirov Would you be interested in sending us a pull request? We'll likely hold off on merging the PR as it is a potentially breaking change. Upgrading Groovy can have a lot of other unexpected side effects especially for plugins that have been written in Groovy.

**Comment by lptr** [comment]
This would help us get rid of https://issues.apache.org/jira/browse/GROOVY-7966 that is causing some problems with task output caching.

**Comment by lptr** [comment]
This one should fail once the upgrade happened: https://github.com/gradle/gradle/blob/5d961deafd7d980ccc31a6fc8e56da69f8126af6/subprojects/plugins/src/integTest/groovy/org/gradle/groovy/compile/GroovyJavaJointCompileSourceOrderIntegrationTest.groovy#L25-L25

**Comment by melix** [comment]
Groovy 2.4.9 was [released today](http://www.groovy-lang.org/changelogs/changelog-2.4.9.html).

**Comment by lptr** [comment]
I've upgraded `master` to 2.4.9 on a branch, and it's looking good so far, stage 3 done:

https://builds.gradle.org/viewQueued.html?itemId=2454072&buildTypeId=Gradle_Branches_Checkpoints_Stage4FullCoverage&tab=dependencies

PR: https://github.com/gradle/gradle/pull/1508

**Comment by lptr** [comment]
The PR looks pretty good, I think it's ready for merging.

**Comment by lptr** [comment]
@big-guy merged the PR to `release`.

**Comment by big-guy** [comment]
This will be delivered in 3.5
