### ISSUE TITLE
Gradle crashes my computer routinely

### ISSUE THREAD

**Issue by digitalheir** [gradle/gradle#14324]
### Expected Behavior
Gradle does not crash my computer

### Current Behavior
Gradle crashes often

### Context
I have a number of issues on the Android Studio issue tracker 

https://issuetracker.google.com/issues/162684733
https://issuetracker.google.com/issues/164130207
https://issuetracker.google.com/issues/164631890

I think the issue is with Gradle. 

Caches and logs are corrupted:
```
cache resourceHashesCache.bin (/home/maarten/.gradle/caches/6.6.1/fileHashes/resourceHashesCache.bin) is corrupt. Discarding.
```

Oddly, Gradle is also usually unable to connect to the Kotlin daemon:

```
Could not perform incremental compilation: Could not connect to Kotlin compile daemon
Could not connect to kotlin daemon. Using fallback strategy.
```

### Steps to Reproduce 
It seems to be some deadlock issue when multiple things go on at once (happens more often when I have multiple projects open at the same time), but I can't find a good way to reproduce it. I also can't really make a thread dump because the entire UI freezes progressively in a weird way: at first everything seems responsive, then websites stop loading in Firefox and I can't open new programs (although dialog boxes still open and for instance YouTube keeps playing), and after a while everything just freezes.

### Your Environment 
Build scan URL: 

I sadly can't make a build scan of a freezing build, because it is becomes completely unresponsive. These builds fail because because a type inference errors or whatever, but shows corrupted files in Console log. 

https://scans.gradle.com/s/xogn4vd4hw5aw 
https://scans.gradle.com/s/hqldz53hbje5q

**Comment by lptr** [comment]
Thanks for reporting @digitalheir. This is probably unrelated, seeing that you are on Linux, but a couple questions:

* Did you have the experimental file system watching enabled? (`--watch-fs` or `org.gradle.unsafe.watch-fs` property)
* Can you reproduce this with Gradle 6.6? Can you reproduce with a recent nightly?

The Kotlin compiler disappearing was a problem with Gradle 6.5 (and to a lesser extent with 6.6 as well) when file system watching was enabled on macOS, though we never observed similar problems on Linux (nor Windows).

**Comment by digitalheir** [comment]
Thanks for the quick reply. Some more details:

It happens with all 6.x Gradle versions I've tried, including 6.6. I then tried downgrading and now actually the last freeze happened when I tried upgrading with `./gradlew wrapper --gradle-version=6.6.1`.

I get the feeling there is some toxic interplay with Kotlin, because the issue also occurs when I perform some action in the IDE like opening a new project.

> Did you have the experimental file system watching enabled? (--watch-fs or org.gradle.unsafe.watch-fs property)
I don't think so

> Can you reproduce this with Gradle 6.6? Can you reproduce with a recent nightly?
Will try now with 6.6.1.

**Comment by digitalheir** [comment]
Maybe it is a good idea anyway to auto-clear corrupted caches, because I get these errors all the time until I manually delete the folder. See attached log.
[corrupt-cache.log](https://github.com/gradle/gradle/files/5141874/corrupt-cache.log)

**Comment by lptr** [comment]
I'd encourage you to file an issue with JetBrains about the Kotlin compiler disappearing. If you could create a small reproducer project, I'd be happy to take a look, too.

Another thing to investigate is if you can reproduce the same problem with different Kotlin plugin versions.

**Comment by digitalheir** [comment]
Started an issue in Kotlin issue tracker as well:

https://youtrack.jetbrains.com/issue/KT-41473

The frustrating thing is: I can't really reproduce it confidently. It happens from time to time, seemingly at random. But it happens on all projects, even sample projects from Google / JetBrains that I usually upgrade Gradle versions of. I'll share one such project which does not contain sensitive code once it happens again.

**Comment by jbartok** [comment]
Since one of the linked issues concluded with a hard-drive problem, it's probably safe to say that this is no longer an issue to look into. Pls. reopen if you disagree.
