### ISSUE TITLE
Verbose/Confusing console output when using incremental compile

### ISSUE THREAD

**Issue by hansd** [gradle/gradle#1432]
The compileJava task occurs two times in the log. See screenshot:

<img width="1002" alt="1__hans_hans-mbp16____github_performance-comparisons_single-large-project__zsh__and_new_issue_ _gradle_gradle" src="https://cloud.githubusercontent.com/assets/37539/23090955/465aefb4-f55f-11e6-9e51-2e0bd8bcd852.png">

This is with latest from master branch: commit 3abfc0227fb366559c99bdbb8a333ef3c6b3ae7e

**Comment by oehme** [comment]
The task does not occur twice, the second line is just a log message which happens to start with the task path.

**Comment by hansd** [comment]
It looks a bit weird and confusing to me. But if this is by design I don't feel that strong about. Close as you wish.

**Comment by oehme** [comment]
@melix Should this be an `--info` level message instead? I feel it is rather verbose on lifecycle level - and confusing as Hans noted.

**Comment by hansd** [comment]
This is also something we want to capture in a build scan.

**Comment by oehme** [comment]
Yep, along with the exact reason (currently it just says "any of these reasons"). But that's another story :)

**Comment by eriwen** [comment]
This should be improved as we improve logging output, so marking with 4.0 milestone.

**Comment by eriwen** [comment]
@hansd As a lifecycle message, this message will no longer be output by default, except possibly in CI environments. It will also be grouped correctly. 

I would like to suggest that we verify this in 4.0 RC1 and take no further action on this.

**Comment by hansd** [comment]
@eriwen Fine for me

**Comment by eriwen** [comment]
These log messages in question have been moved to INFO: https://github.com/gradle/gradle/commit/d13310882ea1015cf96b274cbcba137b9d327aee
