### ISSUE TITLE
Kotlin 1.4 build classpath binary incompatibility

### ISSUE THREAD

**Issue by Dkhusainov** [gradle/gradle#14331]
# Your Environment
Gradle wrapper 6.6
Kotlin 1.4

### Context
Latest Gradle is incompatible with build logic(plugins, etc.) written in Kotlin 1.4
Upgraded to Kotlin 1.4 and started getting runtime errors

### Steps to Reproduce 
1. Create a project with Gradle 6.6 this `build.gradle`
```
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.0"
  }

  def name = Class.forName("kotlin.jvm.internal.FunctionReferenceImpl")
  println(name.classLoader.properties.toString())
  println()
  name.constructors.each {println(it)}
}
```
2. Run `gradlew `

### Expected Behavior
* classLoader loaded kotlin-stdlib 1.4
* class FunctionReferenceImpl has more than one constructor

### Current Behavior
* classLoader loaded kotlin-stdlib 1.3.72
* class FunctionReferenceImpl has one constructor
* Getting `kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V` in my external(to the project) gradle plugin compiled with Kotlin 1.4

**Comment by big-guy** [comment]
Gradle requires you to use the embedded version of Kotlin (1.3.72) for build scripts. We'll be upgrading to 1.4 eventually. #12660
