### ISSUE TITLE
Allow repository definition by configuration

### ISSUE THREAD

**Issue by DanySK** [gradle/gradle#14336]
Currently defined repositories affect every configuration.
However, in many projects i needed to depend for my `runtimeClasspath` only on artifacts hosted on a certain repository (e.g. Maven Central), while it was ok to fetch something from elsewhere (say, jcenter) for other configurations (e.g. for generating documentation, or running linters).

I currently restrict repository content by filtering groups, e.g.:
```kotlin
repositories {
    mavenCentral()
    jcenter {
        content {
            includeGroup("com.soywiz.korlibs.korte")
            includeGroupByRegex("""org\.jetbrains\.(dokka|kotlinx)""")
        }
    }
}
```
Is required for me to run Dokka 1.4.0-rc on Kotlin projects.
The problem is that this configuration requires developers to keep in mind not to depend on artifact in the whitelisted group, or do so only for versions that are hosted on the main repository as well.
It is not maintainable in the general case, and unwanted dependencies might percolate to implementation/runtime configurations.

### Expected Behavior

There should be a way to filter repository use per-configuration.
It could work as filter or as additional source for artifact in the configuration spec, the latter likely better.
Something along the line of:

```kotlin
repositories {
    mavenCentral()
}
configurations {
    "dokkaRuntime" {
        additionalRepositories {
            jcenter()
        }
    } 
}
```

### Current Behavior

Currently, declared repositories are valid for all configurations, and can't be extended or filtered on a configuration basis.
With this change, a set of repositories valid for all configurations can be extended (or possibly reduced) on specific configurations.

### Context

See the introduction for a contextualized example.

**Comment by ljacomet** [comment]
Have a look at the [full API](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/RepositoryContentDescriptor.html) of `RepositoryContentDescriptor`, there is already an option to filter per configuration. Note that the names need to be the names of the _resolvable_ configurations like `compileClasspath` or `runtimeClasspath`.

**Comment by DanySK** [comment]
Thank you, I did not find it mentioned in the docs so I supposed there was not a method already. Maybe we can extend them with a pointer to the full API and a few examples?
If you believe the documentation suffices already, you can close this feature proposal.

**Comment by ljacomet** [comment]
The end of the [first section](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering) has a link but without adding info that there are other filtering methods.
That probably deserves an improvement indeed.
