### ISSUE TITLE
Wrong user.dir if run application from symlink

### ISSUE THREAD

**Issue by SButterfly** [gradle/gradle#1433]
If you will place symlink to you application run script to your $PATH and execute symlink from $HOME, than `user.dir` will be symlink directory. NOT your $HOME.
If you run from any other directory, everything is ok.

### Expected Behavior
Executing application work correctly no matter how it launched.

### Current Behavior
Wrong `user.dir`, if you run app from symlink from $HOME on MacOS.

### Context
I want to create install application script, which will compile and install application to user system automatically. Application is a simple console app, which deals with files. So I want to run it such way:
` /User/sergey $ my-app my-file.txt`.
But when I run, it says that relative file (`my-file.txt`) doesn't exist. 
I found out it happens, because application scripts in gradle are wrong. They changed run directory to other.

### Steps to Reproduce (for bugs)
1. Create simple application app, which takes path to file as first param.
2. Run `gradle insallDist`
3. Create symlink in `/usr/local/bin` to your start script
4. Run app from your $HOME.

I've created simple repo: https://github.com/SButterfly/GradleApllicationBug
Run `install_to_path.sh`, which do above steps.
Than run `$ gradle-application-bug .bash_history`

App will say, that file doesn't exist.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/2bj3pqa2dqixq

**Comment by eriwen** [comment]
@SButterfly Thank you for the thorough issue description. That will help us prioritize this better.
