### ISSUE TITLE
GradleWrapperMain may get stuck if process is launched from another JVM

### ISSUE THREAD

**Issue by DanySK** [gradle/gradle#14347]
This is a very puzzling issue to me.
I'm using Gradle 6.6.1, and I noticed that under some circumstances launching a Gradle process from another Java process and waiting for termination results in an infinite wait. Terminating the Gradle wrapper process and analyzing its output, the build actually completed successfully, it's just the process that does not terminate.

I inspected what happens with a profiler. Here is the thread dump for `main`:

> "main" #1 prio=5 os_prio=0 cpu=559,06ms elapsed=73,93s tid=0x00007f1b34016000 nid=0x1b37f7 waiting for monitor entry  [0x00007f1b3bb3f000]    java.lang.Thread.State: BLOCKED (on object monitor)         at org.gradle.internal.logging.console.ThrottlingOutputEventListener.onOutput(ThrottlingOutputEventListener.java:68)         - waiting to lock <0x00000000fe68adf0> (a java.lang.Object)         at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.8/DelegatingMethodAccessorImpl.java:43)         at java.lang.reflect.Method.invoke(java.base@11.0.8/Method.java:566)         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)         at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)         at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:245)         at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:157)         at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)         at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)         at com.sun.proxy.$Proxy0.onOutput(Unknown Source)         at org.gradle.internal.logging.sink.OutputEventTransformer.onOutput(OutputEventTransformer.java:104)         at org.gradle.internal.logging.sink.OutputEventRenderer.onOutput(OutputEventRenderer.java:431)         - locked <0x00000000fe674e78> (a java.lang.Object)         at org.gradle.internal.logging.sink.OutputEventListenerManager$1.onOutput(OutputEventListenerManager.java:36)         at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:225)         at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:185)         at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:148)         at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)         at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:56)         at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:212)         at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:275)         at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:247)         at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)         at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)         at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:92)         at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:38)         at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)         at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)         at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)         at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)         at org.gradle.launcher.Main.doAction(Main.java:35)         at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.8/Native Method)         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.8/NativeMethodAccessorImpl.java:62)         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.8/DelegatingMethodAccessorImpl.java:43)         at java.lang.reflect.Method.invoke(java.base@11.0.8/Method.java:566)         at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)         at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)         at org.gradle.launcher.GradleMain.main(GradleMain.java:31)         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.8/Native Method)         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.8/NativeMethodAccessorImpl.java:62)         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.8/DelegatingMethodAccessorImpl.java:43)         at java.lang.reflect.Method.invoke(java.base@11.0.8/Method.java:566)         at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)         at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)     Locked ownable synchronizers:         - None

It looks like it is waiting for output.

The bug is hard to reproduce:
1. it only seems to happen on big and complex projects;
2. it seems reproducible only if the process is launched from another JVM instance

The behaviour seems to be unrelated to the deamon, or, at least, I reproduced the bug with `--no-daemon`.

### Expected Behavior
The process terminates once the build is finished.

### Current Behavior
Under special circumstances, the process does not stop.

### Context
I wrote [a bot doing something similar to Dependabot](https://github.com/DanySK/upgradle), but working with Gradle kts scripts and supporting [refreshVersions](https://github.com/jmfayard/refreshVersions).
I need to launch the command `./gradlew refreshVersions` on multiple repositories, and I do so by:

```kotlin
    private fun runRefresh(projectRoot: File): ProcessOutcome {
        val process = ProcessBuilder(listOf(gradleCommand, "--console=plain", taskName))
            .directory(projectRoot)
            .start()
        return try  {
            when (process.onExit().get(timeoutInMinutes, TimeUnit.MINUTES).exitValue()) {
                0 -> ProcessOutcome.Ok
                else -> ProcessOutcome.Error(process)
            }
        } catch (timeOut: TimeoutException) {
            logger.error("One process has timed out", timeOut)
            process.destroy()
            try {
                process.onExit().get(1L, TimeUnit.SECONDS)
            } catch (unkillableTimeOut: TimeoutException) {
                logger.error("One process refused to terminate after timeout, destroying forcibly", unkillableTimeOut)
                process.destroyForcibly()
            }
            ProcessOutcome.TimeOut(process)
        }
    }
```

### Steps to Reproduce 
1. fork [this repository](https://github.com/AlchemistSimulator/Alchemist/) (you will need write access)
2. [download upgradle](https://github.com/DanySK/upgradle/releases/download/0.2.2-dev1e+814f0d3/upgradle-0.2.2-dev1e+814f0d3-all.jar)
3. Create an `upgradle.yml` in the same folder of `upgradle-0.2.2-dev1e+814f0d3-all.jar` file with the following content:
```yaml
includes:
  - owners: .*
    repos:
      - Alchemist
    branches:
      - develop
modules:
  - name: GradleWrapper
    options:
      strategy: next
      versionRegex: \d+(\.\d+)*
  - name: RefreshVersions
    options:
      strategy: next, latest
      versionRegex: \d+(\.\d+)*
labels:
  name: version-upgrade
  color: deffaa
author:
  email: danilo.pianini@gmail.com
```
4. run `java -jar 'upgradle-0.2.2-dev1e+814f0d3-all.jar' upgradle.yml` from the folder where you downloaded the jar

### Your Environment
The bug can be [reproduced in CI](https://travis-ci.com/github/DanySK/upgradle-bot/builds/182074076)

**Comment by DanySK** [comment]
Full thread dump
[thread-dump.log](https://github.com/gradle/gradle/files/5150962/thread-dump.log)

Full heap dump
[heapdump-1598883726410.hprof.tar.gz](https://github.com/gradle/gradle/files/5150980/heapdump-1598883726410.hprof.tar.gz)

**Comment by big-guy** [comment]
I suspect that this is happening because you're starting Gradle, but not reading stdout/stderr while the build is running. stdout/stderr need to be flushed to prevent the child process from hanging/waiting.

Have you considered using the Tooling API? https://docs.gradle.org/current/userguide/third_party_integration.html#embedding

This gives you programmatic access to the Gradle build you're running.

**Comment by DanySK** [comment]
This can very likely be the reason, indeed. I'll try out the tooling API

**Comment by DanySK** [comment]
It is working correctly with the Tooling API. @big-guy, you framed the issue correctly.
