### ISSUE TITLE
Deadlock in gradle daemon when using Junit 5 parallel execution

### ISSUE THREAD

**Issue by ChrisTrenkamp** [gradle/gradle#14350]
I'm not sure if this is an issue with gradle or Junit.  

When enabling Junit 5's parallel execution features, the gradle daemon sometimes reaches a deadlock.

### Expected Behavior

The gradle daemon executes multiple tasks for parallel testing.

### Current Behavior

The gradle daemon executes multiple tasks for parallel testing, but the daemon sometimes encounters a deadlock and the tests hang and never complete.

### Context

I'm trying to enable parallel testing to speed up our CI/CD pipeline and improve the developer experience.  

### Steps to Reproduce 

In a project using Junit 5, create a file under `src/test/resources/junit-platform.properties` with the content:

```
junit.jupiter.execution.parallel.enabled = true
junit.jupiter.execution.parallel.mode.default = concurrent
junit.jupiter.execution.parallel.mode.classes.default = concurrent
```

... and in the `build.gradle` file, set:

```
test {
	useJUnitPlatform()
}
```

Sometime the deamon encounters a deadlock, sometimes it doesn't.

### Your Environment

I can't provide a scan, but I was able to profile the daemon, and the problem seems to be in these three different methods/threads:

![gradle-deadlock](https://user-images.githubusercontent.com/3903329/91738022-e560ff00-eb7d-11ea-942c-ccd1c73cdc2c.png)

**Comment by big-guy** [comment]
Gradle is already running tests in parallel with multiple forked workers, so I'm not sure you'll see much of an improvement and could potentially run into other headaches right-sizing the number of tests you want to run in parallel.

Could you get thread dumps from the test worker processes? The test workers will be called something like `GradleWorkerMain 'Gradle Test Executor 2'`

This output you have here looks like "normal" behavior from the daemon waiting for the test workers to complete, so if something is wrong, it'll be in the test workers.

**Comment by ChrisTrenkamp** [comment]
Disregard this issue.  PEBKAC.
