### ISSUE TITLE
Public API for deciding whether config caching is enabled

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#14375]
### Expected Behavior

It would be great if a plugin(like android-gradle-plugin, kotlin-gradle-plugin) can tell whether config caching is enabled from gradle public api.

### Current Behavior

Currently, android-gradle-plugin uses the internal api StartParameterInternal.isConfigurationCache which is not very robust. The same goes for kotlin-gradle-plugin.

### Context

From agp side, currently we use this information for analytics purpose.

**Comment by ysb33r** [comment]
This will be really useful from a plugin PoV (and from Grolifant) if `StartParamter.isConfigurationCache()` is an API method.

**Comment by dsvoronin** [comment]
my scenario using Gradle enterprise is to:
- filter all local builds without CC enabled
- check the adoption
- push the adoption by messaging devs :slightly_smiling_face: 
- ask if there is a problem with enabling it which is not already reported

i know that there is a flag in build scan, but i can't filter by
I'm sending a custom build scan tag, using `StartParameterInternal` way now

**Comment by bingranl** [comment]
Recently Gradle has refactored the internal API which affects some users. Is there any plan of adding an public API?

**Comment by adammurdoch** [comment]
Added in https://github.com/gradle/gradle/pull/22460

**Comment by bingranl** [comment]
@adammurdoch Does it make sense to have an public API for whether project isolation is enabled as well?
