### ISSUE TITLE
Check user manual on build script naming recommendation

### ISSUE THREAD

**Issue by donat** [gradle/gradle#14384]

**Comment by big-guy** [comment]
We should not recommend that people change the name of the build script file.

see #13158

**Comment by donat** [comment]
I’ve checked the user manual and I haven’t found any mentions on how to name build scripts. The only mention in #13158 was deleted in https://github.com/gradle/gradle/commit/3e0293820cd1866ec373756eef9c12e136b27961#diff-7771f539d485064cec758b4da165c48aL54.
