### ISSUE TITLE
Document usage of `usesService` when working with build services

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle#14380]
### Related Samples
None.

### Context
A user was reporting that `spec.getMaxParallelUsages().set(1)` did not take effect (build service still called by more than one task at a time) until he added `useseService` to the affected tasks:

```
task abc1(type: SpecialTask) {
    ...
    usesService serviceProvider
    ...
}
abc1.getServer().set(serviceProvider)
```

Can you please add some documentation on when/how to make use of `usesService` whichis currently not documented on docs.gradle.org (except the Javadoc).

**Comment by crkurz** [comment]
Example 3 on [Shared Build Services](https://docs.gradle.org/current/userguide/build_services.html#registering_a_build_service) contains two code issues:

```
        ...
        Provider<WebServer> serviceProvider = project.getGradle().getSharedServices().registerIfAbsent("web", WebServer.class, spec -> {
        ...
        project.getTasks().register("download", Download.class, task -> {
```
should read
```
        ...
        Provider<WebServer> serviceProvider = project.getGradle().getSharedServices().registerIfAbsent("web", WebServer.class, {spec -> ...
        ...
        project.getTasks().register("download", Download.class, { task -> ...
```
("spec" and "task" were moved into the closure)

**Comment by bamboo** [comment]
@crkurz thanks for the heads-up but that sample code is correctly written in Java, maybe you assumed it was Groovy?

**Comment by crkurz** [comment]
Hi @bamboo , thank you, very true! I am using the code in my (Groovy!) Gradle scripts. I am sorry, please ignore.

Would the „usesService“ issue in @etiennestuder ´s post needs doc changes?
