### ISSUE TITLE
Align usage of `groovy-all` dependency across multiple example in user guide

### ISSUE THREAD

**Issue by jjstreet** [gradle/gradle#1441]
Example 56.3 describes how to add groovy as a dependency for compilation should you use groovy in production code:

```
repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.7'
}
```

Example 56.4 describes how to add groovy as a dependency for writing test code:
```
dependencies {
    testCompile "org.codehaus.groovy:groovy:2.4.7"
}
```

The dependency listed in 56.4 does resolve to an actual package, however this is not the package other libraries such as Spock use. Spock has a dependency to `groovy-all` and thus, example 56.4 should be:
```
repositories {
    mavenCentral()
}

dependencies {
    testCompile 'org.codehaus.groovy:groovy-all:2.4.7'
}
```

**Comment by bmuschko** [comment]
I agree that all three sample code snippets should use the same Groovy library for consistency. Would you be interested in providing a pull request for this?

**Comment by jjstreet** [comment]
Sure, sounds good to me.
