### ISSUE TITLE
HTTP Build Cache should follow redirects

### ISSUE THREAD

**Issue by fkorotkov** [gradle/gradle#14433]
I suggest to allow redirect. I posted my concerns and use case in #13759 

> I'm trying to implement a GitHub Action which will act as a proxy for GitHub's Caching API and be compatible with Gradle's Build Cache protocol. This proxy will redirect to Azure's shared access signature URL on a cache download request. I've also seen other HTTP caches that uses a similar technique of redirecting to a "pre-authorized" S3/GCP/other storage URL in order to optimize the I/O and make CI builds load directly from storage rather then going though a proxy.

### Expected Behavior

Build cache should respect redirects

### Current Behavior

Throws an exception

**Comment by fkorotkov** [comment]
For context https://github.com/bazelbuild/bazel/issues/5131#issuecomment-386060676

**Comment by mkousteris** [comment]
We are using Jfrog artifactory as a remote cache and facing errors due to redirects.
Right now it seems that the latest Gradle version supported is v4.10.3
https://jfrog.com/knowledge-base/verified-client-versions-for-the-jfrog-platform-release/

**Comment by johngun3** [comment]
I want to second @mkousteris concern. I also am running into this problem when attempting to use JFrog Artifactory as a remote cache. It seems like it would be a good idea to allow users to opt into enabling redirects and have the default setting the way it is now.
