### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by umairaziz112221** [gradle/gradle#14432]
![Screenshot_2020-09-01-20-24-01](https://user-images.githubusercontent.com/63067048/92259503-b1286e00-eef0-11ea-8220-7b0f2d84c4d5.png)

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

Where is the link from?
