### ISSUE TITLE
Local state conflict when changing Kotlin precompiled script plugin id from package+filename to filename convention

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#14446]
When removing package declarations and renaming Kotlin precompiled script plugins to have their plugin id in the filename, the builds started failing due to state stored in either `~/.gradle/caches/<gradle-nightly-version>` or `buildSrc/.gradle/caches/<gradle-nightly-version>` (https://github.com/gradle/gradle/pull/14445).

```
[Step 1/3] Execution failed for task ':buildSrc:cleanup:compilePluginsBlocks'. org.gradle.kotlin.dsl.support.ScriptCompilationException: Script compilation errors:

  Line 35: import Gradlebuild_availableJavaInstallationsPlugin
                  ^ Unresolved reference: Gradlebuild_availableJavaInstallationsPlugin

  Line 36: import Gradlebuild_minifyPlugin
                  ^ Unresolved reference: Gradlebuild_minifyPlugin

  Line 37: import Gradlebuild_moduleIdentityPlugin
                  ^ Unresolved reference: Gradlebuild_moduleIdentityPlugin

  Line 38: import Gradlebuild_repositoriesPlugin
                  ^ Unresolved reference: Gradlebuild_repositoriesPlugin

  Line 39: import Gradlebuild_reproducibleArchivesPlugin
                  ^ Unresolved reference: Gradlebuild_reproducibleArchivesPlugin
```

### Expected Behavior
Moving from `plugin-id-in-package` to `plugin-id-in-filename` convention in Kotlin precompiled script plugins should compile.

### Current Behavior
Changing Kotlin precompiled script plugins from `plugin-id-in-package` to `plugin-id-in-filename` convention resulted in compilation failures due to state stored in local caches.

Build scan URL: https://ge.gradle.org/s/xtdhxycdoujee

**Comment by ov7a** [comment]
We haven't seen this for some time, and it's probably obsolete. If someone stumbles into this, please open a new issue with a reproducer.

Related:
* https://github.com/gradle/gradle/issues/15214
