### ISSUE TITLE
Where to define dependency versions

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14471]
Also: How to share same between the _main build_ and _buildSrc_.

**Comment by edrd-f** [comment]
Not sure it's related, but I have an issue with that in one of my projects. I created some extensions for the Kotlin Multiplatform Gradle DSL inside my `buildSrc` module, and to be able to access such Kotlin Multiplatform symbols I need to declare a dependency to the Kotlin Gradle plugin in my [`buildSrc/build.gradle.kts`](https://github.com/edrd-f/xmg/blob/de2637b908d8fda603cf7a32ac2b853365325eaa/buildSrc/build.gradle.kts#L11). This prevents me from defining it elsewhere, as Gradle complains a plugin version is already specified in the classpath, and so my plugin version is constrained to the `buildSrc` module. I tried extracting it to `gradle.properties` but couldn't access it using the standard `val propertyName: String by project`.
