### ISSUE TITLE
gradle dist still broken for play 2.5.x

### ISSUE THREAD

**Issue by YehudaCohen** [gradle/gradle#1448]
When I call gradle dist, the generated bin/playBinary starts the deprecated NettyServer and the binary will fail at context build. This seems to be due to the following code.
https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayDistributionPlugin.java#L140

### Expected Behavior

Instead, for this version of play, play.core.server.ProdServerStart should be used.

### Current Behavior

The binary fails to start up.
### Context

I am trying to use gradle to build my play applications rather than use sbt.

### Steps to Reproduce (for bugs)
Simply run gradle dist on a play 2.5.x project. Go into the build/distributions/playBinary.zip and unzip this.

execute ./bin/playBinary

### Your Environment

gradle build docker container and macbook

**Comment by YehudaCohen** [comment]
I can submit a pull request for PlayDistributionPlugin.java, but I don't know if there are any other touch-points affected here.

**Comment by bmuschko** [comment]
@ghale @big-guy @bigdaz As you have been working on the Play integration could you have a look at the issue? Could this be solved by looking at the version of the Play dependency and then dynamically using a different main class name at runtime?

**Comment by ghale** [comment]
I think so.  We already adapt for play version in a number of other places and do slightly different things for different versions.  I'd think we'd just use the same pattern here and create a script with a different main class for versions >= 2.5.X.  What's not clear to me (and I haven't looked into this at all) is why this isn't failing when we do multi-version testing with 2.5.  Seems like either the server would not start up or at least it would fail when we try to access some of the content.  We should look into this and make sure the tests are working as expected.

**Comment by bmuschko** [comment]
@YehudaCohen We'd be happy to accept a pull request for this. Please see @ghale's suggestion for guidance.

**Comment by marcospereira** [comment]
This was also fixed in #3314.

**Comment by bigdaz** [comment]
@marcospereira Thanks for the report. Marking a fixed.
