### ISSUE TITLE
Proposal to mitigate flaky tasks: Implement retry mechanism on task DSL

### ISSUE THREAD

**Issue by sambsnyd** [gradle/gradle#1449]
This is a feature request.

### Expected Behavior
An example of what such a mechanism might look like in a gradle file:
```gradle
task example {
  retry {
    times 2
    onlyIf { ex ->
      ex.message == 'foo'
    }
  }
  doLast {
    throw new GradleException('foo')
  }
}
```

If this proposed `retry` extension were omitted tasks would maintain their current behavior in the face of failure (i.e.: `retry.times` defaults to `0`)
`retry.onlyIf` accepts a closure which takes one `java.lang.Exception` parameter and returns a `boolean`.

If the task passes the `retry.onlyIf` closure is not evaluated and normal execution continues.
If the task fails and has not already retried `retry.times` and the `retry.onlyIf` closure evaluates to `true` then the task is rerun. Whatever the result of rerunning the task, it replaces the original task result.

If on a retry the task fails and `retry.onlyIf` evaluates to `false` then the task is not retried regardless of `retry.times` and the last result stands as the canonical result for the task.

If `retry.onlyIf` is set and `retry.times` is not explicitly set, `retry.times` is implicitly set to `1`
If `retry.times` is set to a negative integer that's a configuration time error
If `retry.times` is set to a positive integer and no closure has been explicitly supplied to `retry.onlyIf` then `retry.onlyIf` defaults to `{ ex -> true}`

The command console/logs should reflect how many times the task was retried and what the result was. For the `example` task above that might look like this:
```
D:\project> gradlew example
:project:foo FAILED, RETRYING 2 TIMES
:project:foo FAILED, RETRYING 1 TIMES
:project:foo FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\project\build.gradle' line: 9

* What went wrong:
Execution failed for task ':project:example'.
> foo

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.216 secs
```

Other considerations:
Should `retry.onlyIf` have similar semantics to `task.onlyIf` and add the supplied closure to a list of closures which are `&&` together?
If the task fails for *different* reasons when retried how should that be recorded and reported?
Should `task.onlyIf` be reevaluated with each retry of the task?

### Current Behavior
No generic, task-level mechanism currently exists.
Classes implementing the task interface or extending from DefaultTask may implement this type of logic on an ad-hoc basis.

### Context
Sometimes a task or task type that isn't perfectly reliable must, for technical or organizational reasons, be part of the build.  In a large build with many plugins and many users, a task which crashes even 1% of the time can become very aggravating.

When the underlying issue cannot easily be addressed, such as there being an intermittent bug in a closed-source subprocess, a mechanism to retry a failing task could be helpful.

In our specific case the poorly-behaved process is Checkstyle 6.5 which occasionally crashes as it churns through around 250 java projects. Upgrading Checkstyle to a newer version, while desirable, would be a ton of work as newer versions expose several thousand violations which must be hand-corrected.

### Steps to Reproduce (for bugs)
N/A

### Your Environment
~250 java projects, ~15 non-java projects

**Comment by ov7a** [comment]
Sorry for the late reply.

We have concerns about how this feature may be abused in order to hide underlying stability problems. 

We would need additional scenarios to justify this change. Until this happens, we won't implement this feature.
