### ISSUE TITLE
userguide and release notes headings rendered behind header when using adblocker

### ISSUE THREAD

**Issue by staffanf** [gradle/gradle#1450]
If I go to https://docs.gradle.org/current/release-notes.html using the uBlock Origin plugin in Chrome, then the main heading is rendered behind the header.

### Expected Behavior
The page to look good, even for people using adblockers.

### Current Behavior
The page heading is hidden from view.

![image](https://cloud.githubusercontent.com/assets/8639600/23258798/1af8068a-f9ca-11e6-89c1-41f17f85dd73.png)

### Context
It really a cosmetic thing in the user guide, but a lot of users will be using ad blockers and the first view of the guide will be missing the header

### Steps to Reproduce (for bugs)
Add uBlock Origin to Chrome. Goto https://docs.gradle.org/current/release-notes.html

**Comment by lacasseio** [comment]
Nice catch @staffanf. Now I know why it worked in incognito mode.

**Comment by eriwen** [comment]
Will allow you to prioritize this whenever you want if you don't mind @facewindu

**Comment by facewindu** [comment]
@eriwen Will fix tomorrow

**Comment by facewindu** [comment]
Fixed and pushed live.

Thanks @staffanf for raisin this.

**Comment by staffanf** [comment]
lgtm
