### ISSUE TITLE
6.7-rc-1 Toolchain Feature Could not target platform Java SE 15

### ISSUE THREAD

**Issue by jamespedwards42** [gradle/gradle#14500]
I am testing out the new Toolchain feature that was just released in 6.7-rc-1 with the hope I can replace the current way of doing things: https://docs.gradle.org/6.6.1/userguide/building_java_projects.html#example_configure_java_7_build.

Is this feature intended to work with early access versions of Java?

### Expected Behavior

When I add the following configuration to my build it should find or download JDK 15 to compile, test and build my project.

```groovy
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(15)
  }
}
```

### Current Behavior

```sh
./gradlew check

> Configure project :json-iterator
Project :json-iterator => 'systems.comodal.json_iterator' Java module

> Task :json-iterator:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':json-iterator:compileJava'.
> Could not target platform: 'Java SE 15' using tool chain: 'JDK 14 (14)'.
```

### Your Environment

```
> java --version
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

> ./gradlew --version

------------------------------------------------------------
Gradle 6.7-rc-1
------------------------------------------------------------

Build time:   2020-09-11 16:17:05 UTC
Revision:     fe783600075485236c778e073cad5640729cf8f5

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          14.0.2 (Oracle Corporation 14.0.2+12-46)
OS:           Mac OS X 10.15.6 x86_64
```

I have my JDK's installed under `/Library/Java/JavaVirtualMachines` including OpenJDK 15+36-1562.

Here is a successful build scan if I use JDK 15 in my local shell: https://scans.gradle.com/s/seoqmzla2mbfa
and here is a failed build scan with it failing against JDK 14 in my local shell: https://scans.gradle.com/s/khqla7ffs7d5w

**Comment by ljacomet** [comment]
The download support in toolchains is indeed limited to GA versions, so this is not technically a bug. If you feel that's a too strong limitation, please file a feature request.

I will amend the documentation so that this is made clear.

**Comment by melix** [comment]
> > Could not target platform: 'Java SE 15' using tool chain: 'JDK 14 (14)'.

The error message is not super clear, though. Shouldn't it say it wasn't able to find a matching JDK?

**Comment by ljacomet** [comment]
Looking more at the reported error, there is something fishy indeed.
@jamespedwards42 Could you share more of you setup?
In which project / build file is the toolchain block declared?
What are the configurations around java compile for `json-iterator`?

In short you are getting an error message coming from the legacy way Gradle attempted to figure out a toolchain based on the version running it and the requested source / target compatibility. You are not getting the error message from the new toolchain support.

**Comment by jamespedwards42** [comment]
@ljacomet I pushed a branch with what I was doing to test things out, here is the relevant build file: https://github.com/comodal/json-iterator/blob/gradle-toolchain/systems.comodal.json_iterator/build.gradle

Note that it is a subproject to an empty parent build file: https://github.com/comodal/json-iterator/blob/gradle-toolchain/build.gradle

I created a PR to show the diff of what I added to test things out and which also comments out the current solution I use to do this: https://github.com/comodal/json-iterator/pull/1/files

**Comment by ljacomet** [comment]
So your setup should fail for another problem: when using toolchains, you can no longer use `sourceCompatibility` at the project level.
However you seem to be getting another exception because a plugin does change the compile task setup. I think it might be the Java modularity related plugin.
You may want to let them know that they have a compatibility issue with the toolchain support appearing in Gradle 6.7.

Thanks for raising the issue and bringing plugin support to our attention. This issue will be closed once the documentation clearly states that only GA Java releases will be downloaded.

**Comment by jamespedwards42** [comment]
I was able to remove my dependency on the [moduleplugin](https://github.com/java9-modularity/gradle-modules-plugin), in favor of the newer native [module configuration](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular).  After that everything just worked!  Thank you for your guidance.
