### ISSUE TITLE
Property auto-detect used at configuration time when using toolchain with auto-download=false

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle#14504]
### Expected Behavior
Build fails because it cannot find a suitable toolchain.

### Current Behavior
Build fails with:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Cannot obtain value from provider of Gradle property 'org.gradle.java.installations.auto-detect' at configuration time.
        Use a provider returned by 'forUseAtConfigurationTime()' instead.
```

### Context

Gradle 6.7-rc-1
Using
```kotlin
java { toolchain { languageVersion.set(JavaLanguageVersion.of(15)) } }
```
with `org.gradle.java.installations.auto-download=false`

### Steps to Reproduce 
Should be reproducible with any Java (or Kotlin/Groovy/Scala) project.
1. Configure a toolchain you do **not** have installed.
2. Execute any `JavaCompile` task (even one that would be skipped because it has no source) with `org.gradle.java.installations.auto-download=false`

### Your Environment
Build scan URL: https://scans.gradle.com/s/hi4zunolp7x6i

This scan is from gradle-errorprone-plugin, with some local modifications (bumping to Gradle 6.7-rc-1 to begin with). I originally noticed the issue within a TestKit test while adding toolchains support to the plugin.

**Comment by ljacomet** [comment]
Thanks for the report. I had fixed a bunch of these before the RC1. Looks like I missed one!

**Comment by ljacomet** [comment]
Indeed, I enhanced an error message to show the state of these properties ... and forgot to mark them for use at configuration time 🤦
