### ISSUE TITLE
Add Early Access JDK Support to Toolchain Feature

### ISSUE THREAD

**Issue by jamespedwards42** [gradle/gradle#14515]
Expand the functionality of the new [Toolchains feature](https://docs.gradle.org/6.7-rc-1/userguide/toolchains.html) to support early access and release candidate versions of OpenJDK.

### Expected Behavior
Similar to the current functionality it should be able to find the latest version/build given a major version number.

### Current Behavior
Only GA versions are currently supported.

### Context

The current solution for using a new JDK that Gradle does not yet support is boilerplate heavy and not very intuitive: https://docs.gradle.org/6.6.1/userguide/building_java_projects.html#example_configure_java_7_build

My naive assumption in requesting this feature is that expanding the local search functionality to support EA or RC JDK version strings would be relatively simple. 

For downloads however, I believe adoptopenjdk only publishes GA builds.  Another provider such as [Zulu](http://static.azul.com/zulu/bin/) could be used which provides predictable naming.  Even if this is a no go, supporting local look ups would be very nice to have.

**Comment by ljacomet** [comment]
To be clear: what is currently not supported is the auto download feature.
If it is detected locally, by installing it with one of the [supported tools in auto detect](https://docs.gradle.org/6.7-rc-1/userguide/toolchains.html#sec:auto_detection), or explicitly configured, the toolchains feature introduced in 6.7 works just fine with Java 15 already.

As for the reason we did not include automatic download of early access release, it was mostly a concern of stability and being explicit. Through discussions in the team, we believe that supporting early access is better done when it is explicit rather than implicit.

**Comment by jamespedwards42** [comment]
Ah okay, I misunderstood.  After fixing my issues with plugins which do not yet work with toolchains (https://github.com/gradle/gradle/issues/14500#issuecomment-693138564), the local look up worked as advertised.  Closing this as downloading and wiring the path to a JDK is simple enough in today's CI's, for example with [Github Actions](https://github.com/comodal/json-iterator/blob/master/.github/workflows/gradle-nightly.yml#L31).

**Comment by yschimke** [comment]
I'd love to open this up again, it seems like it might be mostly allowing "ga" to be settable to "ea".  But likewise it would be great if you could also choose different distributions, outside openjdk.  While that appears baked in at the moment.

The value here would be in easy testing across local command line builds, local IDE builds and CI.  Without tying into CI infrastructure.  More than that all of these can eventually benefit from things like centralised download caching.

Definitely not essential for EA testing.  But hopefully something in Gradle 7.0 that would be nice to make more flexible inside the build system.  My build currently compiles with JDK11, runs with Android or JDK8-15, and has one module that compiles with 14.

**Comment by bmuskalla** [comment]
@yschimke With 6.8, we'll introduce support for choosing by vendor (oracle, amazon, adoptopenjdk, ...) as well as by implementation (hotspot, j9, ..).
For EA versions, we still plan on supporting EA versions for provisioning toolchains, we just didn't get to it yet (see #14814)

**Comment by uschindler** [comment]
What's the status on this. Technically Adoptium now also has preview releases, but the download URL is hardcoded to have "ga" here:

https://github.com/gradle/gradle/blob/7af2e5edf3d99eb9bda3b611cf22af70b1a0dde5/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkRemoteBinary.java#L159-L161

We really need this in Apache Lucene for compiling multi-release JARs with preview releases of the new panama-foreign APIs. We don't want to have people install those versions, what's the problem in downloading them like any other relase. I would have expected that you can configure it in the spec.

**Comment by uschindler** [comment]
Is there any way to "emulate" the provisioning by hacking the url in the build script? We need a quick solution without rewriting whole toolchain support in our build scripts...
