### ISSUE TITLE
Run with vmoptions: '-ea', error: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by yihchu** [gradle/gradle#14520]
I need 'assert' in my code, so i set '-ea' to vmoptions, but it can not run, and give me the error: `Run with vmoptions: '-ea', error: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1`

I tried java project and maven project, both of them works well, so i guess i must be something wrong with gradle.
I have tried gradle-4.10,gradle-6.5 and gradle-6.6.1, all of them went wrong.

### Expected Behavior
no error

### Current Behavior

error: `Run with vmoptions: '-ea', error: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1`

### Context

Just new a gradle project in idea, and add a Class and a main function, just like
```java
public class Test {

    public static void main(String[] args) {
        assert 2 > 1;
        System.out.println("2 > 1");
        assert 1 > 2;
        System.out.println("1 > 2");
    }

}
```
and add '-ea' to vm options, and the error will go out
### Steps to Reproduce 

```java
public class Test {

    public static void main(String[] args) {
        assert 2 > 1;
        System.out.println("2 > 1");
        assert 1 > 2;
        System.out.println("1 > 2");
    }

}
```

### Your Environment

very simple: jdk 8 or 11, gradle 4.10 - 6.6.1, nothing else

**Comment by blindpirate** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/12689835/93283807-d9bf3a80-f803-11ea-91e7-2d3efe096836.png)

![image](https://user-images.githubusercontent.com/12689835/93283822-e0e64880-f803-11ea-83e9-92d51e25ff1d.png)

![image](https://user-images.githubusercontent.com/12689835/93283868-f52a4580-f803-11ea-8978-e50c862eec1f.png)

**Comment by yihchu** [comment]
please not use openjdk

> Can't reproduce.
> 
> ![image](https://user-images.githubusercontent.com/12689835/93283807-d9bf3a80-f803-11ea-91e7-2d3efe096836.png)
> 
> ![image](https://user-images.githubusercontent.com/12689835/93283822-e0e64880-f803-11ea-83e9-92d51e25ff1d.png)
> 
> ![image](https://user-images.githubusercontent.com/12689835/93283868-f52a4580-f803-11ea-8978-e50c862eec1f.png)

Please not use openjdk

**Comment by blindpirate** [comment]
Same with Oracle JDK: 

![image](https://user-images.githubusercontent.com/12689835/93293700-29f5c700-f81b-11ea-9d14-66c2f3ea5b6a.png)

**Comment by yihchu** [comment]
> Same with Oracle JDK:
> 
> ![image](https://user-images.githubusercontent.com/12689835/93293700-29f5c700-f81b-11ea-9d14-66c2f3ea5b6a.png)

😔
Thanks.............................
