### ISSUE TITLE
Incorrect directory in documentation / IDE

### ISSUE THREAD

**Issue by malachid** [gradle/gradle#14526]
Android Studio relies on documented directories; but they are incorrect.

### Expected Behavior
The directory listed on [this page](https://docs.gradle.org/current/userguide/kotlin_dsl.html#troubleshooting) should exist.

### Current Behavior
For Ubuntu 20.04 specifically, it states that the logs are located in `$HOME/.gradle-kotlin-dsl/logs`
They are actually located in `$HOME/.gradle-kotlin-dsl/log` (without the `s`).

### Context
Android Studio detected a failure and attempted to open the documented directory; but it does not exist. 
I considered opening an issue in the Android Issue Tracker - but the issue is that the gradle-kotlin-dsl log directory is incorrect.

### Steps to Reproduce 
Try setting an invalid plugin like `kotlin("kapt") version "1.3.72"` then click "Show Kotlin Gradle DSL Logs in Files" from Android Studio. 

### Your Environment
Build scan URL: https://gradle.com/s/lkapgbczyjtyk

(you can ignore the build failures, that's irrelevant to the documentation bug)

**Comment by eskatos** [comment]
Thanks for the report @malachid 
See #14592
