### ISSUE TITLE
Artifact transforms with dependencies fail when project substitutes external one

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#14529]
Using [MyApplication.zip](https://github.com/gradle/gradle/files/5237119/MyApplication.zip) project and running ` ./gradlew clean :app:mergeExtDexDebug` fails with Gradle 6.6.1 and 6.7-rc-1. Changing version back to Gradle 6.5.1 fixes the issue.

In this project, subproject `:core-common` replaces external dependency `androidx.arch.core:core-common`. While desugaring e.g `androidx.savedstate:savedstate:1.0.0` we need the transformed artifacts of `:core-common` but those transforms will fail as project artifacts are not produced yet.

Stacktrace is:
```
 Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
         > Failed to transform core-common.jar (project :core-common) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
            > Execution failed for JetifyTransform: /Users/gavra/AndroidStudioProjects/MyApplication/core-common/build/libs/core-common-100.jar.
               > Transform's input file does not exist: /Users/gavra/AndroidStudioProjects/MyApplication/core-common/build/libs/core-common-100.jar. (See https://issuetracker.google.com/issues/158753935)
```

**Comment by adammurdoch** [comment]
Potential fix via https://github.com/gradle/gradle/pull/14586, which should be in 6.7 RC2

**Comment by eskatos** [comment]
@gavra0 could you please confirm `6.7-20200923130742+0000` fixes it?
