### ISSUE TITLE
HotSwap: Failed to clean up output files for task compileJava

### ISSUE THREAD

**Issue by cdalexndr** [gradle/gradle#14538]
### Expected Behavior
No error.

### Current Behavior
Error: Couldn't delete file.class:

```
> Task :backend:server:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend:server:compileJava'.
> Failed to clean up output files for task ':backend:server:compileJava'
```
Trying to manually delete the file shows `File In Use` dialog because file is open in OpenJDK Platform binary (my runing app).

### Context
I'm using [DCEVM hotswap for java 11](https://github.com/TravaOpenJDK/trava-jdk-11-dcevm).
This error shows up regularly when the hotswap mechanism tries to build changes (every 30sec).

### Steps to Reproduce 

1. Start app
2. Do some changes that fails build
3. Wait for hotswap automatic rebuild -> expected error
4. Revert changes
5. Stuck with error `Couldn't delete`, but build should succeed

Stopping running app resolves the issue, but the whole point of hotswap is to work while app is running.

### Your Environment
Win 10
Gradle 6.5.1

**Comment by big-guy** [comment]
I think this might be a Hotswap problem, unfortunately: https://github.com/HotswapProjects/HotswapAgent/issues/359

I'm not sure how this would be expected to work on Windows if the JVM is holding open the class files.

I think you'd see the same thing if you just ran `gradle clean compileJava`.

**Comment by bmuskalla** [comment]
Sounds like this should be fixed on the HotSwapAgent site. If you believe there is a way for Gradle to resolve this, let us know and we can reopen this issue.
