### ISSUE TITLE
lock bug at DefaultConditionalExecutionQueue

### ISSUE THREAD

**Issue by vaneyli** [gradle/gradle#14533]
- Gradle 6.5.1

- The daemon work thread add an item to the queue with the lock : [queue.add(execution)](https://github.com/gradle/gradle/blob/0f831ea756e574b3c2f54f6ea89330397fc06885/subprojects/base-services/src/main/java/org/gradle/internal/work/DefaultConditionalExecutionQueue.java#L77)

- The work queue thread runs "queue.isEmpty()" without the lock : [queue.isEmpty()](https://github.com/gradle/gradle/blob/0f831ea756e574b3c2f54f6ea89330397fc06885/subprojects/base-services/src/main/java/org/gradle/internal/work/DefaultConditionalExecutionQueue.java#L199)

**Comment by bmuskalla** [comment]
@ghale This sounds reasonable. I know it's a long shot but do you think this could be a problem? (it was part of d2a501efe083e45b9ef825d0072324178991ddbd )

**Comment by ghale** [comment]
Looks legit, but @big-guy already fixed it: https://github.com/gradle/gradle/commit/3b824d71c6124cf9ef309b006dc18a4ececd29a6.  I think this can be closed.

**Comment by bmuskalla** [comment]
Dang, sorry for the noise. I was under the assumption that I'm looking at `master`. Thanks @ghale
