### ISSUE TITLE
Manifest timestamp attribute not ignored

### ISSUE THREAD

**Issue by sehenst** [gradle/gradle#14530]
### Expected Behavior

Task `:jar` should be `UP-TO-DATE` even though `Build-Timestamp` attribute has changed.

### Current Behavior

Task `:jar` is run even though timestamp attribute should be ignored.

### Context

I would like to be able to add a timestamp attribute to the .jar manifest file without having to rebuild the .jar file when the timestamp changes.

### Steps to Reproduce 

1. clone https://github.com/sehenst/IgnoreManifestAttribute
2. run `gradlew build` two times

This is the output from the second build:
```
...
> Task :jar
Caching disabled for task ':jar' because:
  Build cache is disabled
Task ':jar' is not up-to-date because:
  Input property 'rootSpec$2$1' file C:\Users\sehenst\IdeaProjects\IgnoreManifestAttribute\build\tmp\jar\MANIFEST.MF has changed.
file or directory 'C:\Users\sehenst\IdeaProjects\IgnoreManifestAttribute\build\resources\main', not found
:jar (Thread[Execution worker for ':',5,main]) completed. Took 0.016 secs.
:assemble (Thread[Execution worker for ':',5,main]) started.
...
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/sbouuhcc5hzlc

**Comment by big-guy** [comment]
runtimeClasspath normalization only applies to tasks that are consuming the jar, not the jar task itself. 

IMHO, you really shouldn't add timestamps like this into the manifest to start with. I don't believe they're ever useful.
