### ISSUE TITLE
Applying Build Scan Plugin (--scan) cause the following error 'Cannot mutate content repository descriptor 'Gradle Central Plugin Repository' after repository has been used'

### ISSUE THREAD

**Issue by ghilainm** [gradle/gradle#14536]
### Expected Behavior
No error and build scan plugin applied.

### Current Behavior
Gradle build fails with the following exception:

```
java.lang.IllegalStateException: Cannot mutate content repository descriptor 'Gradle Central Plugin Repository' after repository has been used
        at org.gradle.api.internal.artifacts.repositories.DefaultRepositoryContentDescriptor.assertMutable(DefaultRepositoryContentDescriptor.java:56)
        at org.gradle.api.internal.artifacts.repositories.DefaultRepositoryContentDescriptor.addExclude(DefaultRepositoryContentDescriptor.java:191)
        at org.gradle.api.internal.artifacts.repositories.DefaultRepositoryContentDescriptor.excludeGroupByRegex(DefaultRepositoryContentDescriptor.java:157)
        at org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler$1.includeGroupByRegex(DefaultRepositoryHandler.java:182)
        at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
```

### Context
I executing `gradle build` on a multi project build.

I have custom enterprise repositories defined in my init.d/init-script.gradle.

```
settingsEvaluated { settings ->
    settings.pluginManagement {

        repositories {
             exclusiveContent {
                forRepository {
                    maven {
                        name = "gitlab"
                        url "https://our-gitlab.io/api/v4/groups/110/-/packages/maven"
                        credentials(HttpHeaderCredentials) {
                            name = "Private-Token"
                            value = GITLAB_PRIVATE_TOKEN
                        }
                        authentication {
                            header(HttpHeaderAuthentication)
                        }
                    }
                }
                filter {
                    includeGroupByRegex("(xxx-.*)|(a.b.xxx.*)")
                }
            }
            gradlePluginPortal()
         }
    }
}
```

### Steps to Reproduce 
I can't provide an easy way to reproduce, can't either provide access to the project. However, I am available for a debug session or can provide any information you want.

### Your Environment
------------------------------------------------------------
Gradle 6.6
------------------------------------------------------------
Build time:   2020-08-10 22:06:19 UTC
Revision:     d119144684a0c301aea027b79857815659e431b9

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.6 (Eclipse OpenJ9 openj9-0.18.0)
OS:           Linux 5.4.0-47-generic amd64

**Comment by bmuskalla** [comment]
@ghilainm We've done several changes to how we merge repository descriptors in the recent releases. Would you be willing to try this with the 7.x stream again? 
I'm going to close this for now but please, report back if you still see any issue with this and I'll reopen.

**Comment by dsvoronin** [comment]
Hello, please take a look at sample-reproducer for this issue: https://github.com/dsvoronin/GRADLE-14536

**Comment by mformetal** [comment]
Getting this error after upgrading to Gradle 7.4: https://gradle.com/s/wrdqjnhrf4o7c

I unfortunately cannot share the source code, but it happens when I use an `exclusiveContent {...` block

**Comment by inktomi** [comment]
I'm also seeing this with Gradle 7.4 and `id("com.gradle.enterprise") version "3.8.1"`. 

I also have `exclusiveContent` set up for repositories in a `buildSrc` plugin that I use to manage all my repositories.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/20065
