### ISSUE TITLE
Unify storage measurement unit multipliers

### ISSUE THREAD

**Issue by paplorinc** [gradle/gradle#14540]
When raw byte counts are converted to human-readable format, there are usually two ways to do it: divide by `10^3` or `2^10`.
To avoid confusion - and to stay compatible with the [rest of the scientific community](https://en.wikipedia.org/wiki/International_System_of_Units) -, the binary multiplier often uses a different notation, i.e. instead of **kilobyte** (_kB_), **megabyte** (_MB_) it uses **[kibibyte](https://en.wikipedia.org/wiki/Kibibyte)** (_KiB_), **[mebibyte](https://en.wikipedia.org/wiki/Mebibyte)** (_MiB_).

In the Gradle codebase sometimes we're using the [binary base](https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/dependency-management/src/main/java/org/gradle/internal/resource/transfer/ResourceOperation.java#L46-L57), in other cases the [decimal one](https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/base-services/src/main/java/org/gradle/internal/util/NumberUtil.java#L47-L58) - same notation different meaning.
Actually the casing of first exponent's notation *is* different (`kB`/`KB`), but none are `KiB`.

In the test distribution project we would like to be consistent with the build tool, which one should we use as a basis?
Are there plans of unifying these notations throughout the codebase?

**Comment by big-guy** [comment]
I think it doesn't matter too much which format we use as long as we're consistent.

There aren't any active plans to unify this, would you be willing to identify the places that need to be brought in sync and change them?  I'm happy to review.

It looks like we probably use 1024 to mean kilo in most places, so the KiB/MiB notation is probably closer to what we mean. It's also less likely to cause confusion.

**Comment by paplorinc** [comment]
Provided a PR, let me know if there's anything you would like me to change.

**Comment by ldaley** [comment]
@big-guy 

> I think it doesn't matter too much which format we use as long as we're consistent.

I don't think that's right. `MiB` and friends are foreign to most and not widely used. Are we sure we want to put this in front of users?

**Comment by big-guy** [comment]
@ldaley sorry, just noticed this.

> I don't think that's right. `MiB` and friends are foreign to most and not widely used. Are we sure we want to put this in front of users?

I think the "mebibyte" name of `MiB` is unknown, but the symbol is understood to be "something like MB". Even if you don't know exactly if it's 1000 or 1024-based, you can at least figure out what we intended it to be because it's unambiguous. kB vs KB is well known, but MB is ambiguous (but probably 1000). 

I also think it's OK to put this in front of users because this is the format that git uses. 

> Receiving objects: 100% (382/382), 56.15 KiB | 11.23 MiB/s, done.
> Resolving deltas: 100% (170/170), completed with 91 local objects.

We might be ahead of the curve, but no one will question if we really meant kB or KB or what MB actually means.

**Comment by paplorinc** [comment]
Thanks @big-guy, we'll continue on the GE side accordingly: https://github.com/gradle/dotcom/pull/7581#issuecomment-741622545

**Comment by bmuskalla** [comment]
@paplorinc Can this be considered done?

**Comment by paplorinc** [comment]
Yes, thanks, even on GE side.
