### ISSUE TITLE
Wrong Classpath in scripts/xyz and scripts/xyz.bat created by gradle 6.6.1 (and other?)

### ISSUE THREAD

**Issue by kreincke** [gradle/gradle#14555]
### Expected Behavior
The scripts in build/scripts/ should start the application

### Current Behavior
They don't start the scripts. Instead of this, they throw the error  java.lang.ClassNotFoundException (mainClass)

### Context

This is evoked by a simple typo

  * ``gradle build`` stores the respective scripts under ``build/libs/``.
  * The CLASSPATHs for the local libs in both scripts is CLASSPATH=$APP_HOME/lib/yxz.jar
You 've forgotten to add an ``s`` behind ``lib``.
OR: If you want to follow the logic of gradle itself ( "/opt/gradle/latest/lib/..." ), you've added an s to much.

If I had known which repo I had had to checkout, I would have created a pull request. Tell me and I will fix it. It's a simple typo. 

Interims solution:
``find . build/scripts/ -type f | while read f; do mv $f sav; cat sav | sed "s/\/lib\//\/libs\//g" > $f; rm sav; done``
 

### Your Environment
Linux Ubuntu 20.04 with openjdk-11 and gradle-6.6.1

Build scan URL:

**Comment by big-guy** [comment]
This is the way it's supposed to work (the similar lib/libs are a coincidence). You can't run the application from build/scripts, but if you run `gradle installDist`, there will be a separate `build/install` directory with everything you need to run the application.
