### ISSUE TITLE
Use gradle.buildFinished listener to fail a build (throw an exception)

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#14553]
I have a [plugin](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin) whose primary intended use-case is that users run the task `buildHealth` and this does a holistic analysis of the project's dependencies and applied plugins. There is an "advice task" registered for each subproject, and an "adviceReport" on the root project, that aggregates all the subproject advices (using configurations, not direct task dependencies). Users are able to configure the plugin to fail when it detects an issue. Current behavior is that it only does so on the `buildHealth` task, but this can confuse users who expect sub-tasks to also fail. I would like to be able to use a build service to collect "failures" for each sub-task and then, in `buildFinished`, check the list of failures and then throw a custom exception if it finds any issues. In this way I can maintain the behavior that the build should fail once, only at the very end, regardless of whether a user ran `buildHealth` or a sub-task.

I am unclear on whether this is a supported use of `buildFinished`. I note that I need to use a latch to only throw once; without such a latch, the build throws multiple failures (indicating it may not be designed to throw from within the listener).

If this is not a desirable use-case, then it should be documented as such, and enforced programmatically if possible.

### Expected Behavior
I want to be able to optionally throw an exception like:
```groovy
gradle.buildFinished { result ->
  if (somePredicate) throw GradleException("hello")
}
```

### Current Behavior
I am unclear on whether this is considered permissible or idiomatic. Furthermore, I note that if I do this:
```groovy
gradle.buildFinished { result ->
  throw GradleException("hello")
}
```
that is, unconditionally throw, then I see multiple build failures. It looks like the listener may retry a few times before giving up?

### Context
My summary is probably too verbose and indicates most of the context. For additional context, see [this conversation](https://gradle-community.slack.com/archives/CA745PZHN/p1600386761000400) in the gradle community slack.

**Comment by vlsi** [comment]
I guess it would help if you add the sample exceptions (e.g. a sample failure), otherwise, it is hard to tell/evaluate if the case needs merging exceptions.

Do exceptions from different projects cancel each other?
Is "combined exception" any better than the set of individual exceptions?

**Comment by autonomousapps** [comment]
Well, I don't know how to throw more than one exception :D, so my thought was to combine potentially many into a single, say, `CompositeAdviceException` which had a useful -- and perhaps very verbose -- error message.

**Comment by vlsi** [comment]
> Well, I don't know how to throw more than one exception :D, 

:)

What I mean is the issue description provides no exception at all. I doubt `throw GradleException("hello")` is your desired production code.

It would definitely help if you provide the sample exception which are relevant for *your* use-case.
For instance, there's https://github.com/gradle/gradle/issues/8543, and there's a sample for "failing integration tests".

>say, `CompositeAdviceException` which had a useful

The type of exception is not very important here, and it is important to see which information do you show finally.

**Comment by autonomousapps** [comment]
Something like this:
```kotlin
gradle.buildFinished {
  val errors: List<Throwable> = service.getErrors()
  if (errors.isNotEmpty()) throw CompositeAdviceException.from(errors)
}
```

**Comment by vlsi** [comment]
I mean error message is more important than actual implementation (as there are plenty of ways to implement `List -> String` conversion :) )

**Comment by autonomousapps** [comment]
I will let you imagine it for now ;-) I personally don't think the precise message is critical to understand the issue I've raised. I don't want to spend time crafting the perfect implementation only to discover Gradle thinks this is a Bad Idea and doesn't want to support it.
GitHub <notifications@github.com> wrote:
“I mean error message is more important than actual implementation (as there are plenty of ways to implement List -> String conversion :) )”

**Comment by melix** [comment]
It feels like what you're trying to do doesn't really fit well with the way Gradle "works" in general: as you explained, the idea is that individual tasks fail. This analysis you're doing shouldn't really be different: a task is going to analyze dependencies, and possibly fail the build. This isn't different from a "checkstyle" or "spotbugs" task failing. Each of those tasks can generate reports, and in general if you want aggregation, it means another task which would depend on the outputs of all those individual reports to generate its own report.

Currently we don't have a convenient way to build such an "aggregating" task so you have to build it yourself. I also understand that what you're trying to do is to generate a "summary" at the end of the build, which is not _exactly_ the goal of an aggregating task, so maybe we should have an API to register "things to summarize" at the end of the build. In any case I'm not convinced that using a build service and making the build fail at the end is the way to go.

**Comment by autonomousapps** [comment]
Thanks for the reply, Cédric, much appreciated. Before I forget, I believe that @lacasseio also had a use-case for throwing inside `buildFinished`.

I can accept the conclusion that I shouldn't throw in `buildFinished`, but I'd like to clarify a couple things first. My plugin has _two_ levels of aggregation. The first is at the `Project` (module) level, and is basically due to Android. Because Android is variant-first, I register "advice" tasks for each variant (so adviceDebug, adviceRelease, etc); this is also necessary because each variant can be arbitrarily different in every respect from another variant (dependencies, source, resources...). So I register all of those tasks and then register an `aggregateAdvice` tasks that combines all the variant-specific advice. This is the first level. (nb: I do the same thing for JVM projects but there's only one "variant" there) I consider this level of aggregation essential for correctness.

The next level is at the "whole-project" level, represented by the `buildHealth` task registered on the root project. It aggregates all the `aggregateAdvice` tasks from each subproject. I consider this to be the primary task for users of the plugin, and document it as such. It's this task I configure to fail or not, based on user configuration in my custom extension. I also make the output available via a hook that lets users register their own post-analysis task.

Because `buildHealth` is so expensive (in memory and CPU terms), I understand why a user might prefer to run a smaller task such as `proj:aggregateAdvice`, and wanted to support this use-case by configuring this task to fail (or not) in a similar way to `buildHealth`. However, if someone actually does run `buildHealth`, I do _not_ want a subtask to fail the build early, and I also don't want to require users to use `--continue`. I want a _single_ failure, at the _end_ of the build, regardless of whether the user invoked `proj:aggregateAdvice` or `:buildHealth`.

If I can't (or shouldn't) use `buildFinished`, I can take a look at other options to achieve this, but that seemed like an elegant solution to me.

**Comment by eskatos** [comment]
Hi Tony,

What you could do is keep your project aggregating tasks but not consume their outputs from the whole build aggregating task. In other words, let `:buildHealth` not consume outputs of `:proj*:aggregateAdvice`. And instead have `buildHealth` consume the outputs of individual inspection tasks (per variant iiuc). Then you can let `:proj*:aggregateAdvice` and `:buildHealth` fail normally. The effect would be that running `buildHealth` would lead to a single task failure while keeping the possibility to check targeted projects where each project aggregating task would fail independently.

One drawback of this would be that the `buildHealth` task would have to do the aggregation work from all variants, which couldn't be reused by project aggregating tasks. That'd be easily fixed by splitting the project aggregation and check/fail work into two tasks, say `:proj*:aggregateAdvice` and `:proj*:projectHealth` where the latter can fail.

About showing a summary at the end of the build, exception messages for task failures are displayed by Gradle. If you let the exceptions thrown by `:buildHealth` and `:proj*:aggregateAdvice` have the summary as messages it should do.

**Comment by autonomousapps** [comment]
Thanks for the response, Paul; that's an interesting idea that sounds like it could work.

I'd be inclined to close this issue at this point, but as I said, @lacasseio said in slack he also had a use-case, so I want to give him a chance to chime in.

**Comment by autonomousapps** [comment]
I'm going to close this, as I found a better solution a long time ago. Thanks for the discussion!

**Comment by markjeffreymiller** [comment]
@autonomousapps don't leave us hanging!  What was the solution?
