### ISSUE TITLE
Gradle 3.3 -> 3.4 broke writing custom JavadocOptionFileOption

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#1456]
Gradle 3.3 -> 3.4 broke writing custom JavadocOptionFileOption

### Expected Behavior
Developer should be able to write a custom JavadocOptionFileOption by implementing org.gradle.external.javadoc.JavadocOptionFileOption. Then use that custom object to call org.gradle.external.javadoc.CoreJavadocOptions.addOption used by org.gradle.api.tasks.javadoc.JavaDoc.

This behavior used to work fine.

### Current Behavior
We get a class cast exception because gradle now implicitly casts JavadocOptionFileOption to JavadocOptionFileOptionInternal

e.g.
Caused by: java.lang.ClassCastException: android.support.doclava.DoclavaMultilineJavadocOptionFileOption cannot be cast to org.gradle.external.javadoc.internal.JavadocOptionFileOptionInternal
        at org.gradle.external.javadoc.CoreJavadocOptions.addOption(CoreJavadocOptions.java:585)

### Context
This behavior changed in https://github.com/gradle/gradle/commit/746ff55719a992819517d4e4a400a7342aa7014c and that CL should be reverted as there is nothing public we could extend (there is AbstractJavadocOptionFileOption, but that is in internal package.

### Steps to Reproduce (for bugs)
Write your own 
public class FooBarJavadocOptionFileOption implements JavadocOptionFileOption<List<List<String>>>;

Pass that to Javadock task addOption.

### Your Environment
This started with the switch to from Gradle 3.3. to Gradle 3.4.

**Comment by bmuschko** [comment]
The [release notes](https://docs.gradle.org/3.4/release-notes.html#javadoc-options-should-not-be-overwritten) state the following:

> `Javadoc.setOptions(MinimalJavadocOptions)` is now deprecated. Use `Javadoc.options()` to configure JavaDoc options.

Can't you just use `Javadoc.options()` instead?

**Comment by aviverette** [comment]
1) We are using options().
2) How is that related?

**Comment by bmuschko** [comment]
@aviverette Would you mind providing me with the code you are using in your build script?

**Comment by aviverette** [comment]
The custom option class is defined [here](https://github.com/android/platform_frameworks_support/blob/master/buildSrc/src/main/groovy/android/support/doclava/DoclavaMultilineJavadocOptionFileOption.java) and the option is added to the javadoc task [here](https://github.com/android/platform_frameworks_support/blob/master/build.gradle#L236).

We've since rewritten the option class to extend AbstractJavadocOptionFileOption, which is not ideal as this is an internal class.

**Comment by bmuschko** [comment]
@lptr Can you please comment on the intent of the change?

To get around the issue can you do the following? I didn't try but I think it could work if I am not missing something.

```
def hdfOptions = ['android.whichdoc': 'online', 'android.hasSamples': 'true']

task generateDocs(type: DoclavaTask, dependsOn: configurations.doclava) {
    options {
        hdfOptions.each { key, value ->
            addStringOption key, value
        }
    }
}
```

Also the class [DoclavaMultilineJavadocOptionFileOption.java](https://github.com/android/platform_frameworks_support/blob/master/buildSrc/src/main/groovy/android/support/doclava/DoclavaMultilineJavadocOptionFileOption.java#L20) uses a Gradle internal class which should be avoided if possible.

**Comment by aviverette** [comment]
The issue is that the hdf parameter take two values, which doesn't seem to
be supported, and it needs to be applied multiple times, which also doesn't
seem to be supported.

So on the command line, you would see:
  -hdf android.whichdoc online \
  -hdf android.hasSamples true

**Comment by big-guy** [comment]
@aviverette could you give this 3.5-nightly a try? It should restore compatibility.

Update with:
`./gradlew --no-daemon wrapper --gradle-version=3.5-20170301172655+0000`

Or pointing your wrapper to:
http://services.gradle.org/distributions-snapshots/gradle-3.5-20170301172655+0000-bin.zip

I raised https://github.com/gradle/gradle/issues/1484.  I think we should support what you're trying to do out of the box.

**Comment by big-guy** [comment]
@aviverette I went ahead and incorporated what you were doing with a custom javadoc option:

https://docs.gradle.org/nightly/release-notes.html#support-for-multi-value-javadoc-options

Could you try the latest 3.5 nightly and see if this removes your need for a custom javadoc option?

**Comment by aviverette** [comment]
I have tested with the new javadoc option in 3.5-20170306000041+0000 and it works fine for our use cases.

I also tried reverting our custom options to the implementations linked earlier, and they compile fine using the nightly. The custom options still have to import an internal class, internal.JavadocOptionFileWriterContext, to override the write() method, which would be nice to migrate away from in the future. Would it be helpful to file a FR for that?

**Comment by bmuschko** [comment]
@big-guy Ready to be closed?

**Comment by big-guy** [comment]
@aviverette Thanks!  This will be delivered in 3.5.

If you can use 3.5+, you should be able to get rid of your custom javadoc option entirely and use the new built-in:

```
javadoc {
   options {
      def hdf = addMultilineMultiValueOption("hdf")
      hdf.setValue([
            ['android.whichdoc', 'online'],
            ['android.hasSamples', 'true']
      ])
   }
}
```

Please feel free to open an issue WRT the internal `JavadocOptionFileWriterContext`, I noticed that too.  All of the Javadoc option handling looks like it needs some TLC.
