### ISSUE TITLE
Allow subprojects in current project to be addressed by GA coordinates

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14564]
If I have a project like
```
├── part-a
├── part-b
└ settings.gradle.kts
```
Where `part-b` depends on `part-a` and both set their `group` to `org.myorg`, this should be possible:

```
dependencies {
  implementation("org.myorg:part-a"))
}
```

instead of 
```
dependencies {
  implementation(project(":part-a"))
}
```

Why do we want this?
- This feature is needed in composite builds to enable included builds to depend on something from the including build. This can happen because there are situations where such "build cycles" are desired (see #6229 which has to be fixed as well).
- To have unified way to refer to "components" independent of whether they are published, defined by another build of a composite, or in a separate subproject of the current build.
- Makes it easier to refactor a build (e.g. split up a large build into multiple)
- Allows us to discourage the use of the `project("...")` API completely, as we already discourage it now for cross-project configuration or for accessing the internal state of another project.

This should probably be implemented the same way it is done for the other builds of a composite right now: register a global dependency substitution rule for each subproject. This needs to be done after the project has been configured so that the `group` of each project is known, but (obviously) before dependencies are resolved.

**Comment by jjohannes** [comment]
Fixed for the case where the build is a composite (#4638)

**Comment by jjohannes** [comment]
Spike to continue this work:  #14633

**Comment by big-guy** [comment]
Maybe project accessors make this better?
