### ISSUE TITLE
Add performance tests for build script compilation

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#14565]
Cross-Gradle versions:
- Kotlin DSL multiproject (small/medium/large) build without plugins blocks
- Groovy DSL multiproject (small/medium/large) build without plugins blocks
- Kotlin DSL multiproject (small/medium/large) build with plugins blocks
- Groovy DSL multiproject  (small/medium/large) build with plugins blocks

Cross-Build:
- Kotlin DSL vs Groovy DSL multiproject (small/medium/large) build without plugins blocks
- Kotlin DSL vs Groovy DSL multiproject (small/medium/large) build with plugins blocks

**Comment by rieske** [comment]
We already have cross-Gradle version tests for build script compilation for large (500 subproject) projects:
- [Groovy DSL](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceSlowCoordinator/38225328:id/report-performance-performance-tests.zip%21/report/tests/buildSrc-api-change-in-largeJavaMultiProject-comparing-gradle.html?redirectSupported=false)
- [Kotlin DSL](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceSlowCoordinator/38225328:id/report-performance-performance-tests.zip%21/report/tests/buildSrc-api-change-in-largeJavaMultiProjectKotlinDsl-comparing-gradle.html?redirectSupported=false)

**Comment by wolfs** [comment]
I think we shouldn't add any cross build tests anymore. We should strive to make Kotlin/Groovy DSL projects faster. If you really want to compare both projects you can easily get both numbers from the corresponding cross version (aka regression) tests.
