### ISSUE TITLE
Settings plugins should be visible to other included builds

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14562]
If an included build defines a _settings plugin_, that plugin should be visible to builds included afterwards.

**Comment by jjohannes** [comment]
I rebased this to include to include the latest fixes of 910c710dcf1. The solution in this PR breaks `CompositeBuildIsolationIntegrationTest` again.

**Comment by jjohannes** [comment]
Done for 7.0. See description of #15317 for details.

**Comment by JavierSegoviaCordoba** [comment]
@jjohannes is it compatible with `buildSrc` or it has to be a different included build?

**Comment by jjohannes** [comment]
For buildSrc, it should already work in 6.7.

But `buildSrc` only provide build logic for its main build and cannot be shared with other builds. So there is only one settings file in which you can apply the plugin.

**Comment by jjohannes** [comment]
Sorry I was mistaken. It actually does not work with buildSrc. And I think it probably never will. (see e.g. #11090 for context)

You can either use an additional included build (which you can then also use in buildSrc). Or switch from buildSrc to included builds in general.
