### ISSUE TITLE
Incremental compile fails when trying to hash dependency jar that doesn't exist

### ISSUE THREAD

**Issue by ajmurphy520** [gradle/gradle#1457]
Our multi project build is failing with 3.4 when incremental compile is enabled. The failure happens when one subproject defines a jar task and adds the output of that task to the compile configuration artifacts for dependent projects. However if this task generates no output (in our case it was set to skip using onlyIf) then the compile of dependent projects will fail when they try to hash the output jar file that doesn't exist. Disabling incremental compiling resolves the issue.

### Expected Behavior

Incremental compiling should not try to create snapshots of files that don't exist.

### Current Behavior

The build fails with an IOException when CachingFileHasher attempts to hash a file that doesn't exist

### Context

We defined tasks in a common build script for creating additional jar files. These tasks get added to all subprojects and some of the created jars are needed to compile dependent projects. We configured the artifacts of all the subprojects to include these additional jar tasks in the compile configuration. However not every subproject creates every jar and rather than create a jar with just a manifest file we set the task to skip using onlyIf. This is mostly an issue because we are transitioning from an ant build and still have significant inconsistencies with the jar packaging rules between the different subprojects.

### Steps to Reproduce (for bugs)

A multi project build of these two projects will fail to build
Root project build.gradle
```
apply plugin: 'java'

dependencies {
    compile project(':A')
}

compileJava {
    options.incremental = true
}
```

Subproject A build.gradle
```
apply plugin: 'java'

jar {
    onlyIf {
        false
    }
}
```

The root project must have at least one java source file to compile to reproduce

**Comment by bmuschko** [comment]
Would you mind providing a stack trace (run the build with `-s`)? Thanks!

**Comment by oehme** [comment]
@melix can you fix this for 3.5 (branching next week)?

**Comment by melix** [comment]
Yes, I can fix it.

**Comment by melix** [comment]
This is ready for review.
