### ISSUE TITLE
Add support for standardized initialization script location within the project structure

### ISSUE THREAD

**Issue by mcumings** [gradle/gradle#14578]
There is currently no way for a project to contribute an initialization script through the use of a conventional name or location.  Please add a project-level location (e.g., "${rootProject.projectDir}/init.d/") so that projects can leverage this capability without having to integrate with system-level or user-level locations.

### Expected Behavior

Initialization scripts are currently searched for in the following, ordered locations:
1. The command line `--init-script` argument(s)
1. `USER_HOME/.gradle/*.init.gradle(.kts)`
1. `USER_HOME/.gradle/init.d/*.gradle(.kts)`
1. `GRADLE_HOME/init.d/*.gradle(.kts)`

This feature request is that a project-specific location is inserted between the command line and first USER_HOME location.

For example, if there was a file named `project.init.gradle.kts` as a sibling next to the `settings.gradle` file, this could be detected and automatically included as an initialization script when running Gradle against that particular project.

### Current Behavior

Currently, there is no way for a project to specify initialization behavior outside of  the use of the command line.

### Context

Some build configuration and/or tuning options are only available for dynamic modification through the use of the command line or initialization scripts.  One example of this is the maximum Gradle worker count, which can me modified by calling:

```
     gradle.startParameter.maxWorkerCount = tunedWorkerCount
```

In our scenario, there is a wide variance in the capabilities of various machines performing the build.  Using a static configuration results in some nodes being overwhelmed while others are under-leveraged.  We have developed an algorithm to dynamically tune aspects of the build  that we can control and are limited as to where in the build process we can effect these changes.   The only option we have here is the use of the command line option, but getting users and environments to all specify the correct values is lossy (i.e., some users  and/or calls will forget to add the option) and brittle (changes to the call over time need to be manually propagated).

One aspect of the above is the split between command line invocation of Gradle and that done through the IDE.  In our scenario, AndroidStudio (based upon IntelliJ) allows for configuration of additional Gradle command line arguments but places the configuration in the user-specific `workspace.xml`, meaning that changes to the file must be made by the user, and are therefore brittle as their environment changes, etc..  If the proposed initialization script approach was leveraged, the project configuration  could be dynamically set and apply to both CLI and IDE invocations automatically.

**Comment by mcumings** [comment]
We did come up with a workaround to the above but it is a bit of a Rube Goldberg machine:
1. Create a plugin in buildSrc which deploys a bootstrap init script into `${gradle.gradleUserHomeDir}/init.d/repo_init_bootstrap.gradle.kts`.
1. When Gradle is invoked, the bootstrap script looks for the presence of a `project.init.gradle.kts` script in the project  being built.  If it exists, it does: `apply { from(repoInitFile) }}`
1. The `project.init.gradle.kts` script then does project-specific  logic.

The above:
- Works for all but the first invocation of Gradle in a particular environment.  This is the primary weakness.
- Works for CLI and IDE calls
- Allows for the logic to NOT be leveraged for repos that don't "support" the idea (since they wouldn't likely have an init 
 script in the location being applied)
- Tries to keep the bootstrap as logic-free as possible, immediately redirecting back into the repo for the actual  project-specific logics so that it is under version control / is associated with a particular branch, etc.

**Comment by quentinflahaut** [comment]
It could be great to be able to use this path also:  <project>/gradle/wrapper/init.gradle
It is very painful to publish our custom gradle wrapper only for packaging a /init.d/init.gradle

**Comment by mlopatkin** [comment]
This approach looks more like a workaround. Init scripts aren't really intended for the project-specific configurations. We'd rather try to expose necessary configuration APIs to the settings script. Please feel free to file issues to request more APIs there.
