### ISSUE TITLE
Consolidate snapshotting missing elements in different file collections

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#14587]
When snapshotting a `FileTree` we skip the snapshot as if there was nothing to snapshot, while if we encounter a missing element in a `FileCollection`, we return a missing snapshot for it. This is inconsistent without a clear reason why.

https://github.com/gradle/gradle/blob/8a2c3ae2e2b647615c62cc8b47171e3f53d76a0e/subprojects/core/src/main/java/org/gradle/internal/fingerprint/impl/DefaultFileCollectionSnapshotter.java#L76-L78

---
cc: @gradle/execution

**Comment by wolfs** [comment]
I vaguely remember that for a file tree we want to treat missing roots and empty file trees the same. We do something similar here I think: https://github.com/gradle/gradle/blob/bb0f079250d4fe4e51df26880457e3ef14a3a14e/subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/FileSystemSnapshotFilter.java#L35-L43

For example if you have multiple source directories declared, it doesn't really matter whether a source directory does not exist or it is empty.

**Comment by lptr** [comment]
Could we consolidate this in 7.0, given that we both have empty directory handling now, and the ability to break behavior if needed?

**Comment by wolfs** [comment]
Is a missing directory and an empty directory considered the same by empty directory handling? Since this is what we are asking for here, right?

**Comment by wolfs** [comment]
Part of the consolidation happens here: https://github.com/gradle/gradle/pull/19987

**Comment by wolfs** [comment]
Spec: https://docs.google.com/document/d/1qd_LahHJD91vjPIhvcyp-bFQWXCLq4ayyYHR-Wq3cxw/edit
