### ISSUE TITLE
Gradle 6.7-rc1 -- Error: "An internal error occurred that prevented a build scan from being created."

### ISSUE THREAD

**Issue by JvmName** [gradle/gradle#14582]
Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.7 (AdoptOpenJDK 11.0.7+10)
OS:           Mac OS X 10.15.6 x86_64

Also:
- Gradle `6.7-rc1` (happened on 6.6.x as well)
- AGP `4.2-alpha11` (happened on 10 and 9 as well)
- my actual app uses Kotlin `1.4.10`

running `./gradlew --scan properties` (or anything else, the actual command is unimportant) causes the following error: 

```
2020-09-21T19:10:12.645-0400 [WARN] [org.gradle.internal.enterprise.core.GradleEnterprisePluginManager] An internal error occurred that prevented a build scan from being created.
```

### Context
Here's two points of evidence that there's a config issue:
1.  I'm on a backend project as well (no Android obv, Gradle `6.6.1`), and running the same command creates a build scan! 
1. this happens on Github Actions CI runs as well. 

So clearly my laptop isn't borked, and there's a very specific issue that's happening on my Android repo.

 
### Steps to Reproduce 
I'm not really sure how to repro; `--info`, `--stacktrace`, and `--debug` provide zero interesting information. 
Assuming that this is a config issue, I've `cat`'d my properties into a file and uploaded it here. 
[propertiesOutput.txt](https://github.com/gradle/gradle/files/5258579/propertiesOutput.txt)

### Your Environment

Build scan URL: lol I wish I could 😂

**Comment by JvmName** [comment]
I'm happy to share any debugging info necessary to help sort this problem out! The repo is private, but @runningcode knows how to get a hold of me if you need a specific non-publishable piece of information 😄

**Comment by runningcode** [comment]
Can you try to reproduce using the catchup project?
https://scans.gradle.com/s/hq5q7gsha43qm
I was able to produce a scan using Gradle 6.6.1, AGP 4.2.0-alpha10 and Gradle Enterprise 3.4.1.

Does it work if you apply the gradle enterprise plugin?

**Comment by JvmName** [comment]
> Does it work if you apply the gradle enterprise plugin?

Okay, that led me on the right path! Turns out, I was attempting to apply it, but incorrectly: 
```kotlin
id("com.gradle.enterprise") version "3.4.1" apply (System.getProperty("CI")?.toBoolean() == true)
```

Really, it should have been `getenv`!

**Feature Request:** Shouldn't Gradle say _"hey, the plugin isn't really applied"_ versus the truly un-helpful _"An internal error occurred"_

**Comment by runningcode** [comment]
If a plugin isn't applied it's likely that is being done on purpose.
`--scan` will work whether or not you have the plugin applied.
Feel free to ask questions about this in the Gradle Community slack.
https://gradl.es/slack-invite-2020

I will close this issue for now as it seems resolved.
