### ISSUE TITLE
Try dependency sharing recommendation with Android projects

### ISSUE THREAD

**Issue by donat** [gradle/gradle#14608]
The Android documentation recommends a version declaration scheme that we discourage. We should collaborate with their team to adjust the recommendation.

**Comment by ColtonIdle** [comment]
@donat are you referring to this page? https://developer.android.com/studio/build/gradle-tips.html#configure-project-wide-properties

**Comment by donat** [comment]
Exactly. We are in the process of establishing a recommendation for declaring dependency versions. This is a marker ticket for me to coordinate with the Android team on this.
