### ISSUE TITLE
Build failure ActionFacade invalid offset on jpg's

### ISSUE THREAD

**Issue by Xendrez** [gradle/gradle#14618]
I have a large (many resource files) Android project and the build keeps on failing.
The build fails with the following error:
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
    > Entry :res/drawable-xxhdpi-v4/hawk_bat_2.jpg invalid offset (-2146837233)

### Expected Behavior
Build should pass or at least fail in different places if memory settings are tweaked.

### Current Behavior
Build keeps on failing even when problematic jpg's are removed

### Context
I'm trying to build an Android project with two dynamic modules that deliver photo's to the app. I've split it because of the amount and size of the photo's. The app needs offline capability and that's why the photo's need to download with install.

### Steps to Reproduce 
I can invite you as a collaborator on my project for you to reproduce the build error.

### Your Environment

Build scan URL: https://scans.gradle.com/s/nn6eo527qvge6
And another one after increasing Max JVM memory heap size:https://scans.gradle.com/s/wpmirojqvk3ro

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
