### ISSUE TITLE
Investigate why IDEA does not navigate to extensions sources defined by precompiled script plugin

### ISSUE THREAD

**Issue by donat** [gradle/gradle#14613]
When a precompiled script plugin defines an extension, then "Go to declaration" opens an editor with a decompiled class file.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/419883/94010982-f7ae1180-fda6-11ea-9ee0-46f7ceeba4a8.png">

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/419883/94011127-33e17200-fda7-11ea-8a9e-39809d2cb6d9.png">

In my case, the script plugin is defined in an included build.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/419883/94011322-77d47700-fda7-11ea-98c3-1acaf8a9eaa9.png">

**Comment by jjohannes** [comment]
This is working now (tested with IDEA 2021.1).
