### ISSUE TITLE
Incompatible because this component declares an API of a platform

### ISSUE THREAD

**Issue by sendev1** [gradle/gradle#14620]
### Expected Behavior
When Java platform api dependency is used it should be resolved.

### Current Behavior
Receiving this error ` Incompatible because this component declares an API of a platform and the consumer needed a runtime of a library`

### Context
I have a project which uses java-platform. I am trying to add the java-platform dependency into my spring boot app. This is happening in gradle 6.4.1 but tried all the previous versions and latest version but did not able to make it work. For my project minimum gradle requirement is 6.4.1

### Steps to Reproduce 
I created reproducer and add it into github
java-platform dependency -> https://github.com/sendev1/gradle-depedency.git
Using the java-platform dependency in spring boot app -> https://github.com/sendev1/using-gradle-java-platform-depedency.git

error

```> Task :bootJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootJar'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve com.example:Dependencies:1.0-SNAPSHOT.
     Required by:
         project :
      > No matching variant of com.example:Dependencies:1.0-SNAPSHOT was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its de
pendencies declared externally but:
          - Variant 'apiElements' capability com.example:Dependencies:1.0-SNAPSHOT:
              - Incompatible because this component declares an API of a platform and the consumer needed a runtime of a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
          - Variant 'enforcedApiElements' capability com.example:Dependencies-derived-enforced-platform:1.0-SNAPSHOT:
              - Incompatible because this component declares an API of an enforced platform and the consumer needed a runtime of a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
          - Variant 'enforcedRuntimeElements' capability com.example:Dependencies-derived-enforced-platform:1.0-SNAPSHOT declares a runtime of a component:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
          - Variant 'runtimeElements' capability com.example:Dependencies:1.0-SNAPSHOT declares a runtime of a component:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
```
### Your Environment
gradle 6.4.1 spring boot 2.3.1 windows 10 java 8
Build scan URL:

**Comment by ljacomet** [comment]
When your dependency is a platform, you need to tell Gradle about it.
This is done by wrapping the dependency coordinates in a `platform` like: `implementation(platform("com.example:Dependencies:1.0-SNAPSHOT"))`

Have a look at [the documentation](https://docs.gradle.org/current/userguide/java_platform_plugin.html#sec:java_platform_consumption) for details.

**Comment by johan-roets** [comment]
I'm getting exactly the same error, and I am specifying as a platform

`
Could not determine the dependencies of task ':account:compileJava'.
> Could not resolve all task dependencies for configuration ':account:compileClasspath'.
   > Could not resolve com.csa:platform:GRADLE_7_GRADLE_PLATFORM_2-1003.
     Required by:
         project :account > com.csa:base:GRADLE_7_GRADLE_PLATFORM_2-1003
      > No matching variant of com.csa:platform:GRADLE_7_GRADLE_PLATFORM_2-1003 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability com.csa:platform:GRADLE_7_GRADLE_PLATFORM_2-1003 declares an API of a component:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
`

This is especially weird since the other project (csa) compiles fine. But when I pull in a dependency of csa:base into another project, I get this issue.

In csa base gradle I have: 

`
dependencies {
    testFixtures(platform(project(':platform')))
    testFixturesAnnotationProcessor(platform(project(':platform')))
    api(platform(project(":platform")))
    annotationProcessor(platform(project(":platform")))
    testAnnotationProcessor(platform(project(":platform")))

`
In the other project: 
`
api "com.csa:base:GRADLE_7_GRADLE_PLATFORM_2-1003"
`
