### ISSUE TITLE
Let the configuration cache execute tasks in parallel when storing the cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#14624]
### Expected Behavior

Tasks are run in parallel by default when the configuration cache is enabled even when there's a cache miss.

This would also make all problems, the ones occurring when storing and the ones occurring when loading, surface on the first build. This would make things less confusing and limit the possibility to create problematic configuration cache entries.

### Current Behavior

Only builds with configuration cache hits run tasks in parallel.
Builds storing the configuration cache runs as regular builds, not isolating tasks and not running them all in parallel.

**Comment by eskatos** [comment]
One option to implement this would be to start over once CC is stored on first build, with the potential side effect of releasing the memory used by heavyweight configuration objects such as `Configuration` instances.

**Comment by SgtSilvio** [comment]
@eskatos Why is running independent tasks of the same project in parallel only considered to be implemented with the configuration cache?
When being very strict and declaring all inputs/outputs/dependencies, then running tasks in parallel should be possible with or without using the configuration cache.

**Comment by blundell** [comment]
We did some benchmarking in this area, that might be helpful 

With configuration caching & build cache on, we see a 90% speed gain in initialisation & configuration, a 84% gain in execution and 92% less time spent in garbage collection (vs cc off & bc off).

<img width="955" alt="Screenshot 2021-11-30 at 9 00 23 am" src="https://user-images.githubusercontent.com/655860/144016699-25d3bcac-be11-4571-9c7b-634654698962.png">

CC = configuration cache
BC = build cache
GC = garbage collection
control = the run used to create the % comparison

**Comment by eskatos** [comment]
@SgtSilvio, the configuration cache isolates tasks thus guarantees that tasks can be safely run in parallel, without this strictness it would be very easy to shoot yourself in the foot and face hard to troubleshoot problems.

**Comment by autonomousapps** [comment]
> with the potential side effect of releasing the memory used by heavyweight configuration objects such as `Configuration` instances.

yes please!!

**Comment by abstratt** [comment]
This will be addressed when the work in https://github.com/gradle/gradle/issues/21985 is merged.
