### ISSUE TITLE
about FatFrameworkTask Issue

### ISSUE THREAD

**Issue by VincentChen1212** [gradle/gradle#14623]
Hi
Because I want to manager and separate my customer task
so I create ios.gradle.kts file

my project
```
project
|
----build.gradle.kts
|
----platformConfig
           |
            ----ios.gradle.kts
```

In my build.gradle.kts
```
apply(from = "${rootProject.rootDir}/platformConfig/ios.gradle.kts")
```

In my ios.gradle.kts
```
import org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask 
......


tasks.create(".....", FatFrameworkTask::class){
........
}
```

It looks ok
Then after build I got error **Unresolved reference: jetbrains**

But if only one build.gradle.kts
It is ok.

Thanks

**Comment by jjohannes** [comment]
Including script like that won't work very well in Kotlin DSL. The whole concept of including scripts like this will be deprecated at some point.

Please have a look at precompiled script plugins and use them instead:
- https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins
- https://docs.gradle.org/current/samples/sample_convention_plugins.html
