### ISSUE TITLE
Upgrade to zinc 0.3.13

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1463]
Currently we're on an older version of zinc. The new version [seems to have some performance improvements](https://github.com/typesafehub/zinc/issues/105#issuecomment-280553264), so we should consider upgrading.

**Comment by eriwen** [comment]
This should be an easy one for someone to contribute, otherwise we'll get to this after 3.5.

**Comment by pioterj** [comment]
Perhaps it would help with [reported Scala compilation performance regression](https://github.com/gradle/gradle/issues/1475) after we switched from ant-based compilation to zinc.

**Comment by eriwen** [comment]
Closing as complete
