### ISSUE TITLE
Could not find method archiveFileName() on task 'zipArchive'

### ISSUE THREAD

**Issue by tobymurray** [gradle/gradle#14635]
Running with `--warning-mode all` yields:
```
The AbstractArchiveTask.archiveName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveFileName property instead. See https://docs.gradle.org/6.6.1/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:archiveName for more details.
        at build_e2l1frirg87dxpqvnrh3sl52b$_run_closure4.doCall(/<snip>/build.gradle:18)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

Using `archiveFileName` instead of `archiveName` yields:
```
Could not find method archiveFileName() for arguments [<snip>] on task ':zipArchive' of type org.gradle.api.tasks.bundling.Zip.
```

The [docs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip:archiveFileName) show the property is there, so not really sure what's going on.

### Expected Behavior
I will not get build failures if I follow the instructions correctly

### Current Behavior

I get a failure when trying to use the `archiveFileName`, I think I am using it correctly (in exactly the same fashion as I used `archiveName`).

### Context

I am trying to produce a zip archive of files from my project

### Steps to Reproduce 
Define a custom task, e.g.:

```
task zipArchive(type: Zip) {
	archiveName 'artifact-name.zip'
	destinationDirectory file("$buildDir/libs/")
	from "$buildDir/some-files"
}
```
execute the task (hopefully successfully, or at least see that its valid). Make the suggested update to replace the deprecated `archiveName` with `archiveFileName`
```
task zipArchive(type: Zip) {
	archiveFileName 'artifact-name.zip'
	destinationDirectory file("$buildDir/libs/")
	from "$buildDir/some-files"
}
```
execute the task again, see that it fails.

Executable example forthcoming

### Your Environment

```
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Linux 4.15.0-117-generic amd64
```

**Comment by ljacomet** [comment]
The new property uses a richer type, a `Property<String>`, to enable [lazy evaluation and other goodness](https://docs.gradle.org/6.6.1/userguide/lazy_configuration.html#lazy_properties).
This has however one consequence in terms of DSL:
* In Groovy DSL, you have to use an `=` for the assignment, so `archiveFileName = 'artifact-name.zip'`
* In the Kotlin DSL, you have to do `archiveFileName.set("artifact-name.zip")` (which is available in Groovy as well)

**Comment by tobymurray** [comment]
As a naive user, I find this is a very confusing change (in a usability sense). Is this a Groovy thing (so the solution is to "learn Groovy so I can intuit this")? E.g. what should I search to discover when an equals sign can be omitted? As it stands, the distinction between assigning directly and using `=` is subtle and opaque, it's difficult to search, the error message doesn't indicate why it has failed, and there's nothing on the linked supporting documentation that leads me to know to use `=` unless I recognize the implications of the changed return type. Maybe "users should know the difference in syntax available between assigning values to a string and to other types" is a bar I'm not clearing, but I would be very surprised if I'm the only person to have tripped on this.

Does using `=` always work for properties in the Groovy DSL? If so, maybe it's worth pushing towards using `=` all the time in examples so there's less friction with features like this? Are things more consistent across changes like this with the Kotlin DSL (e.g. should I be opting for Kotlin instead of Groovy)?
