### ISSUE TITLE
Amazon S3 custom endpoint results in invalid region, causing publishing to fail

### ISSUE THREAD

**Issue by Theleruby** [gradle/gradle#1464]
### Expected Behavior
When using the system property "org.gradle.s3.endpoint" to specify a custom endpoint for S3 publishing or retrieval (e.g. `-Dorg.gradle.s3.endpoint=https://s3.example.com/`) the default AWS region of US East 1 should be used, and/or it should be possible to specify the region of the custom endpoint.

### Current Behavior
A made-up invalid region is used based on the provided hostname of the custom endpoint, e.g. for endpoint s3.example.com, the region sent to the server when publishing is "example"

### Context
The above bug renders it impossible to publish an artifact to a custom endpoint if the server rejects signatures with an invalid region. For example, if trying to publish to a minio server, the following error occurs:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Region does not match. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRegion; Request ID: 3L137), S3 Extended Request ID: 3L137
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3787)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1137)
        at org.gradle.internal.resource.transport.aws.s3.S3Client.doGetS3Object(S3Client.java:194)
```

### Workarounds
1 - I changed the configuration of the minio server to set the configured region to the invalid one that Gradle chose to use (e.g. 'example'). This allowed Gradle to connect and the publish worked. Unfortunately, this broke other software that expected the region to be valid (e.g. Cyberduck is unable to create new buckets or upload files to minio in this configuration, because it expects the region to be set to the default region of US East 1 on custom endpoints)

2 - I created a new custom endpoint with a URL that had the format "s3-us-east-1.example.com" and pointed Gradle there instead. This caused Gradle to determine the region name "us-east-1" from the hostname, so publishing succeeded.

### Steps to Reproduce
Specify a custom endpoint using the system property and attempt to publish. e.g.:
`gradlew publish --stacktrace -Dorg.gradle.s3.endpoint=https://s3.example.com/`

### Your Environment
Gradle 3.4

**Comment by Tinytimrob** [comment]
Want to add to this, although it's not a bug:  Having to pass the custom endpoint as a system property on the command line was not intuitive. I was expecting to be able to specify the property in gradle.properties, but that doesn't work.

**Comment by giovanichaves** [comment]
Having the same issue, any chance to have `region` optional?

**Comment by n0mer** [comment]
cross-reference: https://www.digitalocean.com/community/questions/maven-repository-on-digitalocean-spaces-any-luck - custom s3 endpoint for DigitalOcean spaces

**Comment by mbuccini** [comment]
I think this is a great undocumented feature that could be made a bit better just by having the possibility to set the property in gradle.properties, as you mentioned (not a big deal without, though).

**Comment by wyattjsmith1** [comment]
I agree that there should be some way to set the custom endpoint outside of system properties.

@Tinytimrob, I just found out that you can prepend the property with `systemProp.` in `gradle.properties`, and it will work:
```
systemProp.org.gradle.s3.endpoint=https://my.s3.endpoint
```

**Comment by ov7a** [comment]
Sorry for the late reply. 

This is still a valid issue and reproducible in 9.5.1

Looks like Gradle does not set the region properly in some cases. Note: migration to SDKv2 would not solve this.
