### ISSUE TITLE
Execution failed for task ... > kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by tglaeser** [gradle/gradle#14660]
### Expected Behavior
Using `org.gradle.testkit.runner.GradleRunner` to test a Gradle plugin written in Kotlin depending on Kotlin version `1.4`.

### Current Behavior
Instead getting the error above which seem to indicate a missing method exception. This happens since the underlying modules used by the Gradle plugin build upgraded their dependencies from Kotlin `1.3` to `1.4`.

### Context
Compile tasks are successful however warnings
```
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /local/gradle-6.6.1/lib/kotlin-stdlib-1.3.72.jar (version 1.3)
    /local/gradle-6.6.1/lib/kotlin-stdlib-common-1.3.72.jar (version 1.3)
    /local/gradle-6.6.1/lib/kotlin-stdlib-jdk7-1.3.72.jar (version 1.3)
    /local/gradle-6.6.1/lib/kotlin-stdlib-jdk8-1.3.72.jar (version 1.3)
    /local/gradle-6.6.1/lib/kotlin-reflect-1.3.72.jar (version 1.3)
    .gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.10/998caa30623f73223194a8b657abd2baec4880ea/kotlin-stdlib-jdk8-1.4.10.jar (version 1.4)
    .gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.10/e2b3c6695eee6085e606d96d685396dce23a3a06/kotlin-reflect-1.4.10.jar (version 1.4)
    .gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.10/30e46450b0bb3dbf43898d2f461be4a942784780/kotlin-stdlib-jdk7-1.4.10.jar (version 1.4)
    .gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.10/ea29e063d2bbe695be13e9d044dcfb0c7add398e/kotlin-stdlib-1.4.10.jar (version 1.4)
    .gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.10/6229be3465805c99db1142ad75e6c6ddeac0b04c/kotlin-stdlib-common-1.4.10.jar (version 1.4)
w: Consider providing an explicit dependency on kotlin-reflect 1.4 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
```
are logged.

Running the tests then results in failures with stack trace
```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit3033764610543800357 with arguments [foo, --warning-mode, all]

Output:

> Task :foo FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foo'.
> kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 185ms
1 actionable task: 1 executed

	at org.gradle.testkit.runner.internal.DefaultGradleRunner$2.execute(DefaultGradleRunner.java:255)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner$2.execute(DefaultGradleRunner.java:251)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:324)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:251)
        ...
```

### Steps to Reproduce 
n/a; obviously a compatibility issue. What are the plans to fully support Kotlin `1.4`?

### Your Environment
The environment is Kotlin `1.4`, but Gradle seems to **pin** the Kotlin version from its installation `lib` directory to the classpath resulting in the version conflict that leads then to  expected _strange errors_; any workaround for this? Is there a way to tell Gradle to respect the users dependency declarations?

**Comment by Lafreakshow** [comment]
While building an IntelliJ plugin I get the same error. I tried running with Gradle 6.6.1, 6.5 and 6.1; all behaved the same. Tests would fail with the above error, compilation and running in the development instance via `runIde` task work fine. IntelliJ and the Kotlin plugin, which my code depends on, ship with Kotlin library jars (version 1.3.72 in my case) and from my probing it looks like these end up earlier on the classpath than my explicitly declared 1.4 dependencies, but only while running tests curiously. I wrote a hacky function to pull all kotlin 1.4 jars to the front of the classpath before tests run and that fixed my issue. Simply removing the incompatible jars did also work.

I gotta admit my knowledge of Gradle is limited so I don't know exactly how it is supposed to behave in this case, whether it does anything to sort the classpath in a specific way or something like that and I also don't know how stable this solution is or whether it may lead to different issues down the line but it seems a valid workaround right now.

Here is the function I use (you may want/need to adjust it, it is horrifically inefficient and contains some hardcoded paths and unnecessary debugging output but it should provide a good reference):
```kotlin
fun FileCollection.pullUpLibs(
    // Names of libraries to pull forward. Must match the filename exactly
    libsToPull: List<String>,
    // Patters of libraries to highlight and strip. Function tests if fine name contains any of these.
    libPatternsToTarget: List<String>,
    // When false, output entire classpath. When true output only remaining items of libPatterns
    shortenOutput: Boolean = true,
    // Remove all matched targets from classpath, keep only libsToPull
    stripTargets: Boolean = false,
    // Pull libsToPull to the beginning of classpath
    pullLibs: Boolean = true
): FileCollection {
    // Used to print each path on one line, with a tab in front so make it easier to read.
    // Also highlights that matched any item in libPatternsToTarget and libsToPull with an additional indent and marker.
    val transform: (File) -> CharSequence =
        {
            val libsCombined = (libsToPull + libPatternsToTarget).distinct()
            val shortPath = it.path.replace(Regex("^.*(.jdks|files-2.1|test-valet)\\\\"), "\\\\...\\\\")
            if (libsCombined.any { lib -> it.name.contains(lib) }) {
                "\t !!! $shortPath"
            } else shortPath
        }

    // Find the actual file instances that correspond to the list of names to pull up
    // Note that this matches the name exactly, including file extension but no parent directories
    val actualPullUps = this.filter { it.name in libsToPull }

    val result = when {
        stripTargets && pullLibs ->
            files(
                actualPullUps,
                this.filter {
                    libPatternsToTarget.none { pattern -> it.name.contains(pattern) } && it !in actualPullUps
                }
            )

        stripTargets && !pullLibs ->
            files(
                this.filter {
                    libPatternsToTarget.none { pattern -> it.name.contains(pattern) } && it in actualPullUps
                }
            )
        !stripTargets && pullLibs -> files(actualPullUps, this.filter { it !in actualPullUps })
        else -> this
    }

    println("Version: ${gradle.gradleVersion}")
    println(
        "Classpath: \n\t" + result
            .filter { !shortenOutput || libPatternsToTarget.any { pattern -> it.name.contains(pattern) } }
            .joinToString("\n\t", transform = transform) + "\n"
    )

    return result
}
```

Use it like this: 
```kotlin
tasks.test {
    doFirst {
        classpath = classpath.pullUpLibs(
            listOf("kotlin-reflect-1.4.10.jar", "kotlin-stdlib-1.4.10.jar"),
            listOf("reflect", "stdlib")
        )
    }
}
```

This is using kotlin dsl build scripts. Note that I had to pull forward the stdlib jar as well. If anyone ends up straight up copying this, keep in mind that passing "stdlib" while using the stripTargets option will also remove stdlib-common, stdlib-jdk7 and stdlib-jdk8 from the class path. I would really recommend writing a better function instead of copying my attempt.

Naturally, this workaround doesn't change the fact that Gradle ships with Kotlin 1.3 but it should allow you to at least successfully run tests.

**Comment by tglaeser** [comment]
Thanks for the pointer, I tried that but still getting the same error, seems like the configuration is not honored, the `org.gradle.testkit.runner.internal.DefaultGradleRunner` seems to have the Kotlin version from its installation lib **pinned** to its classpath, no clue what this means and how it can be unpinned.

Would be nice to  hear a word from the Gradle folks, curious what their plan with respect to Kotlin version 1.4 is anyway...

**Comment by Lafreakshow** [comment]
Looks like in the end our issues are probably unrelated to each other and just happen to produce the same error. I have been working on a Gradle plugin a few weeks back and had similar issues there too. I had hoped that when I go back to it I could just adapt this solution but this sounds to be a lot more complicated to work around unfortunately.

**Comment by tglaeser** [comment]
Anyone from the Gradle folks; what's your timeline with respect to upgrading the Gradle dependency on Kotlin from `1.3` to `1.4`?

**Comment by eskatos** [comment]
Gradle 6.8 comes with embedded Kotlin 1.4.20. Could you confirm it fixes this issue?

**Comment by tglaeser** [comment]
In the meantime, to avoid the issue, we reverted our Kotlin sources to be version 1.3 compatible.

I upgraded our Gradle and Kotlin dependencies to 6.8 resp. 1.4.20 and all tests passes.

I consider the issue being resolved, closing the ticket.
