### ISSUE TITLE
Type-checked POM configurer misses "roles" in developer

### ISSUE THREAD

**Issue by melix** [gradle/gradle#14681]
### Context

A `developer` in a POM file can be assigned roles. The current POM configuration DSL doesn't support this:

```
developer {
                        id = 'uid'
                        name = 'Julius Caesar'
                        roles {
                            role = 'Developer'
                        }
                    }
```

**Comment by ljacomet** [comment]
This is actually supported. `roles` is modeled as a `SetProperty<String>` and thus supports additive operations or full assignment.

```
developer {
    id = 'uid'
    name = 'Julius Caesar'
    roles.add('Developer')
}
```

**Comment by melix** [comment]
oh indeed, thank you! :facepalm:
