### ISSUE TITLE
Enable selection of JVM implementation for java toolchain

### ISSUE THREAD

**Issue by breucode** [gradle/gradle#14692]
The current java toolchain implementation has hotspot hardcoded as the jvm impl. Since AdoptOpenJDK provides the option to select openj9 instead of hotspot for the JVM Implementation it would be great to configure that in the toolchain.

### Expected Behavior
A configuration option to select the jvm_impl for downloading AdoptOpenJDK.

### Current Behavior
hotspot is hardcoded in the URL for downloading from AdoptOpenJDK.

### Context
I think it should be made clear, that this option only affects downloading the JDK from AdoptOpenJDK and not for selecting locally installed JDKs.

Our plan is to build our application on our CI server with OpenJ9, where gradle downloads the JDK. This way we can use a more general image for our CI build step.

**Comment by bmuskalla** [comment]
This is actually not only relevant for downloading but also for selecting a toolchain in case you got both installed locally but your build requires a specific one (e.g. j9)

**Comment by bmuskalla** [comment]
Thanks, @breucode for the request. This is indeed something we plan on doing. I'm closing this one in favor of a more general issue to track this feature: #14802
