### ISSUE TITLE
Gradle 3.3 -> 3.4 Annotation Processor not called in JavaCompile Task 

### ISSUE THREAD

**Issue by ralfeis** [gradle/gradle#1471]
If I use the JavaCompile Task with compilerArgs Options, then the Annotation Processor "SQLProcessor" is not called anymore. With gradle 3.0,3.1,3.2, 3.3 it is working. With gradle 3.4 it seems to be broken.

The Java source files and the annotation processor are in the same project. 

### Expected Behavior
Same result as with gradle 3.3. 

### Current Behavior
Annotation Processor is not called anymore.

### Steps to Reproduce (for bugs)

This task does not call the Annotation Processor anymore. 

```
task generateSQLConst (type: JavaCompile) {
   description = "Creates SQL Constants"
   destinationDir = file("$buildDir/classes/sql")
   source = file("$projectDir/src/de/")
   includes = ['**/*.java']
   classpath = sourceSets.main.output + configurations.compile + configurations.provided
   options.compilerArgs = ['-processor', 'de.util.annotation.SQLProcessor']
}
```

### Your Environment
Java 7, Gradle 3.4

**Comment by oehme** [comment]
Could you please push a reproducible example to GitHub? That would make it easier for us to fix the problem.

**Comment by oehme** [comment]
I think I know what the issues is though: Your annotation processor is missing the processor configuration file (`META-INF/services/javax.annotation.processing.Processor`, see [javac documentation](http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javac.html#processing)). Gradle 3.4 scans for these configuration files and passes the `proc:none` flag if it doesn't find any.

Apparently javac allows you to use a processor with the explicit `-processor` flag even if it does not have a valid processor configuration file. So I guess Gradle should be lenient in this case as well.

As a workaround, add a processor configuration file for your processor. That way you don't have to pass `-processor` anymore, making your task setup simpler.

**Comment by oehme** [comment]
@melix This should be a simple fix we can do between branching and 3.5-RC-1. We need to check for an explicit `-processor` flag [here](https://github.com/gradle/gradle/blob/e93700c9a83e2aabe6ee028386029aaa976c4930/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/AnnotationProcessorDetector.java#L85-L85).

**Comment by ralfeis** [comment]
Thanks for  your fast reply. 

Your solution proposal worked for us. We added META-INF/services/javax.annotation.processing.Processor and removed the "-processor" flag.

**Comment by melix** [comment]
@oehme can you take a quick look at the fix above and close this issue if you are happy with it?

**Comment by oehme** [comment]
LGTM
