### ISSUE TITLE
Gradle 6.6.1

### ISSUE THREAD

**Issue by MrR1pp3r** [gradle/gradle#14742]
I'm using Flutter and for this Gradle is in use..

Please see the image for java and gradle details:
![20201003_192547.jpg](https://user-images.githubusercontent.com/48425460/94993679-63b32580-05b0-11eb-838c-7bdc7026fecf.jpg)

I get an error : < **org.codehaus.groovy.runtime.InvokerHelper** >

when i build apk using cmd: **flutter run**
![20201003_192606.jpg](https://user-images.githubusercontent.com/48425460/94993765-e1773100-05b0-11eb-9da2-a8e56811dc63.jpg)

Please Help!!

**Comment by big-guy** [comment]
Gradle 6.7 is the first version of Gradle to support Java 15.  You can either downgrade to Java 14 or wait until 6.7 is out.
