### ISSUE TITLE
Zinc compilation is slow when used with --parallel

### ISSUE THREAD

**Issue by jacobilsoe** [gradle/gradle#1475]
After upgrading from Gradle 2.11 to 2.12 (and later) we have seen a significant performance decrease in scala compilation.

### Expected Behavior
Scala compilation performance should be comparable to that of Gradle 2.11.

### Current Behavior
I have created a sample ([SlowScala.zip](https://github.com/gradle/gradle/files/806628/SlowScala.zip)) with 50 subprojects each one having a single scala source file. I have done some measurements comparing Gradle 2.11 to Gradle 3.0. Here are my results:

gradlew.bat --daemon --parallel clean build

2.11: 12s

3.0: 26s

gradlew.bat --daemon clean build

2.11: 16s

3.0: 18s

gradlew.bat --daemon --parallel --max-workers=4 clean build

3.0: 18s

gradlew.bat --daemon --parallel --max-workers=6 clean build

3.0: 22s

As you can see, --parallel really hurts performance. Removing the --parallel options helps but I cannot get 2.11 performance and I really do not like to sacrifice --parallel.

Is this a known performance issue with Gradle 2.12+?

**Note:** this is still a problem in Gradle 3.4.

### Your Environment
OS is Windows 8.1 and Java is 1.8.0_60.

**Comment by otrosien** [comment]
Gradle 2.12 release notes mention that they moved the default from ant-based cmpilation to zinc. (https://docs.gradle.org/2.12/release-notes.html) This is most likely the issue, and from my understanding you can switch back to the ant-based compilation. Nevertheless it would be nice if we got zinc to outperform ant, right.. ;-)

**Comment by jacobilsoe** [comment]
Yes, but that option is no longer available in Gradle 3.4 as far as I can see. It was deprecated in an earlier version.

**Comment by jacobilsoe** [comment]
I just tried upgrading to zinc 0.3.13. No change unfortunately.

**Comment by oehme** [comment]
@jacobilsoe I can reproduce the issue. We do not have capacity to analyse it at this point though. If you could profile it and provide some more insight where the issue might be, that would help a lot.

**Comment by jacobilsoe** [comment]
I profiled the Gradle daemon for versions 2.11 and 3.4. I did this for the attached sample project and also for a similar project just with Java files.
A big noticeable difference is the thread usage which naturally increases during compilation and then decreases back to the original count. Here are some numbers for thread usage:

Scala:
2.11: 5 -> 16 -> 5
3.4: 9 -> 94 -> 9

Java:
2.11: 5 -> 15 -> 5
3.4: 9 -> 15 -> 9

For Java the usage is the same in versions 2.11 and 3.4 whereas for Scala there is a huge increase in thread usage in Gradle 3.4.

**Comment by eriwen** [comment]
@jacobilsoe Thanks for the analysis. Could you please confirm that you're using zinc (not ant-based compiler) when compiling Scala using Gradle v2.11?

**Comment by jacobilsoe** [comment]
@eriwen I am not using zinc when compiling in Gradle 2.11. I just use the default behaviour of the Scala plugin. I have tried this in Gradle 2.11:
```
tasks.withType(ScalaCompile) {
  scalaCompileOptions.useAnt = false
}
```
And now I get performance similar to that of Gradle 3.4. Thread usage is 5 -> 80 -> 5.

**Comment by oehme** [comment]
Thank you @jacobilsoe. This means that the Zinc based compiler always had this problem, so at least we know this is not a newly introduced regression.

**Comment by jacobilsoe** [comment]
Maybe a temporary solution could be to reintroduce ant-based compiler support?

**Comment by dforsl** [comment]
I'd also very much like that, the current state is pretty bad for large projects. 

We have a multiproject of ~100 projects, and the previous performance of Scala compilation using the ant-based compiler at has gone out the window with how Zinc is currently used, from ~4 to 9-10 minutes in total build time when upgrading from 2.10 to 3.5. We haven't done any other changes apart from mandatory switching to zinc, and we can see the daemons constantly working on Scala compilation.

I hope this can be fixed not too far from now - either temporary by bringing the ant-based compiler back, or fixing the current state.

**Comment by ijuma** [comment]
Might be interesting to test the new zinc implementation https://github.com/gradle/gradle/issues/2158
