### ISSUE TITLE
Explicit definition of settings file does not work with non build.gradle file

### ISSUE THREAD

**Issue by aalmiray** [gradle/gradle#14756]
Given a project like

    .
    ├── build-other.gradle
    ├── gradle
    │   └── wrapper
    │       ├── gradle-wrapper.jar
    │       └── gradle-wrapper.properties
    ├── gradlew
    ├── gradlew.bat
    └── settings.gradle

### Expected Behavior
Invoking `./gradlew -b build-other.gradle -c settings.gradle clean` should result in a successful build.

### Current Behavior
The build does not work at all

    $ ./gradlew -b build-other.gradle -c settings.gradle clean
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Build file '/private/tmp/test/build-other.gradle' is not part of the build defined by settings file '/private/tmp/test/settings.gradle'. If this is an unrelated build, it must have its own settings file.
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 423ms

### Context
It appears that Gradle expects `build.gradle[.kts]` but can't handle a custom build file name. 

### Steps to Reproduce 
Create a build structure as shown above.

### Your Environment

    ------------------------------------------------------------
    Gradle 6.6.1
    ------------------------------------------------------------
    
    Build time:   2020-08-25 16:29:12 UTC
    Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3
    
    Kotlin:       1.3.72
    Groovy:       2.5.12
    Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
    JVM:          1.8.0_265 (Amazon.com Inc. 25.265-b01)
    OS:           Mac OS X 10.15.6 x86_64

Problem is reproducible with 6.7-rc3

**Comment by rieske** [comment]
`-b` and `-c` command-line options for custom build layouts will be deprecated with 7.1. Closing as wontfix.
https://github.com/gradle/gradle/issues/16402

**Comment by aalmiray** [comment]
Does this mean that the top most build file must always be named `build.gradle[.kts]`? Because that's what this ticket is about, not the fact that `-b` was used.

**Comment by rieske** [comment]
You can specify a custom build file name for the root project using `rootProject.buildFileName = "build-other.gradle"` in the settings file.

**Comment by aalmiray** [comment]
Yeah, no, that's not what I'm after. What you are proposing is that for a codebase where I'd like to test out different build configurations I'll have to modify build files instead of passing different settings on the command line.
However being that this deprecation is pretty much a done deal there's no more point in continuing this thread.

**Comment by rieske** [comment]
You can also configure the build differently based on a project property that you pass to a build.
For example, you can do:
```
if (hasProperty("foo")) {
    rootProject.buildFileName = "foo.gradle"
} else {
    rootProject.buildFileName = "bar.gradle"
}
```
And use `foo.gradle` using `./gradlew -Pfoo`.

Similarly to this use case: https://github.com/gradle/gradle/issues/16402#issuecomment-816902060

**Comment by aalmiray** [comment]
I'm fully aware of that, which is not the point.
