### ISSUE TITLE
`Problems reading data from Binary store` with intra-project dependency and capability resolution strategy

### ISSUE THREAD

**Issue by jdai8** [gradle/gradle#14770]
Building a `shadowJar` fails with: 
```
Could not determine the dependencies of task ':p1:shadowJar'.
> Could not resolve all dependencies for configuration ':p1:runtimeClasspath'.
   > Problems reading data from Binary store in /private/var/folders/wc/1z_z159n7nxf31gbbnmldcmc0000gn/T/gradle871452152608880068.bin offset 203 exists? true
```

This seems to be an edge case that involves:
- the order of an intra-project dependency
- custom resolution strategy

More details in the repro project below.

### Expected Behavior
Dependencies should resolve consistently

### Current Behavior
See error above.

### Context
I am trying to model some projects in our dependency graph that have multiple incompatible variants of generated code. I'd like to use a capability resolution strategy to resolve conflicts when they occur.

### Steps to Reproduce 
https://github.com/jdai8/gradle-bug-repro

### Your Environment
Gradle nightly `6.8-20201005220043+0000`, also tested with `6.6.1`
Shadow plugin `6.0.0`

Build scan URL:
https://scans.gradle.com/s/m4l36qd4jgzpk

**Comment by melix** [comment]
Thank you so much for the reproducer, definitely helped!
