### ISSUE TITLE
Create a badge for plugin portal version

### ISSUE THREAD

**Issue by uklance** [gradle/gradle#1477]
I'd like a to add a badge to my `README.md` files in github which show the latest version of my plugin on the gradle plugin portal. The badge will also be a link to the page on the plugin portal.

Eg: ![plugin portal](https://img.shields.io/badge/plugin%20portal-v1.2-blue.svg)

Note: The webservice can simply redirect to `https://img.shields.io/badge/<SUBJECT>-<STATUS>-<COLOR>.svg` once the latest version is determined.

See [shields.io](http://shields.io/) for more sample badges and [github.com/badges/shields](https://github.com/badges/shields) for the badge design specification. Please note that I'd like to see the version number included in the badge similar to npm and bintray etc.

**Comment by eriwen** [comment]
@uklance If I understand correctly, we just need an API to get the latest version of a plugin given a plugin ID. That seems like a thing that exists already, will look it up.

**Comment by uklance** [comment]
It would be great if you could provide a webservice

eg: `https://plugins.gradle.org/plugins/badge?pluginId=com.lazan.gradlemavenshare`

The webservice
1. Takes the pluginId
2. Finds the latest version
3. Redirects to `https://img.shields.io/badge/<SUBJECT>-<STATUS>-<COLOR>.svg `
(eg `https://img.shields.io/badge/plugin%20portal-v1.2-blue.svg`)

**Comment by eriwen** [comment]
Ok, we'll consider it.

**Comment by uklance** [comment]
Thanks, please note that many other service providers provide a similar service

eg 
coveralls `https://coveralls.io/repos/github/uklance/gradle-maven-share/badge.svg?branch=master` [![Coverage Status](https://coveralls.io/repos/github/uklance/gradle-maven-share/badge.svg?branch=master)](https://coveralls.io/github/uklance/gradle-maven-share?branch=master) 
bintray `https://api.bintray.com/packages/uklance/maven/gradle-maven-share/images/download.svg` [![Download](https://api.bintray.com/packages/uklance/maven/gradle-maven-share/images/download.svg)](https://bintray.com/uklance/maven/gradle-maven-share/_latestVersion)

**Comment by uklance** [comment]
I've copy / pasted the svg xml for `https://img.shields.io/badge/plugin%20portal-v1.2-blue.svg`. Perhaps it's simple enough that the webservice could create it's own response rather than redirecting to  `https://img.shields.io`

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
	width="114" height="20">
	<linearGradient id="b" x2="0" y2="100%">
		<stop offset="0" stop-color="#bbb" stop-opacity=".1" />
		<stop offset="1" stop-opacity=".1" />
	</linearGradient>
	<clipPath id="a">
		<rect width="114" height="20" rx="3" fill="#fff" />
	</clipPath>
	<g clip-path="url(#a)">
		<path fill="#555" d="M0 0h79v20H0z" />
		<path fill="#007ec6" d="M79 0h35v20H79z" />
		<path fill="url(#b)" d="M0 0h114v20H0z" />
	</g>
	<g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif"
		font-size="11">
		<text x="39.5" y="15" fill="#010101" fill-opacity=".3">plugin portal</text>
		<text x="39.5" y="14">plugin portal</text>
		<text x="95.5" y="15" fill="#010101" fill-opacity=".3">v1.2</text>
		<text x="95.5" y="14">v1.2</text>
	</g>
</svg>
```

**Comment by yuchi** [comment]
Don't forget that working with variable text length can be tricky, so you better either pass responsibility to shields.io or actually use their implementation (it's OSS), in my humble opinion

**Comment by StefMa** [comment]
I just found that and just wanted to reference https://github.com/badges/shields/issues/1125 this ticket 🙃 

I'm also very interested to have a badge for the gradle plugin portal.
Would be great if you can provide a API somehow 😄

**Comment by radarsh** [comment]
In the meantime, can't we just parse the output of `https://plugins.gradle.org/plugin/<plugin-id>` and extract the output? This would be abstracted by the shields.io API so when Gradle does expose a public API for getting just the version, we could always update the shields.io implementation.

**Comment by paulmelnikow** [comment]
Just wanted to ping from Shields.

Is the code that runs the plugin registry in this codebase?

If a contributor were interested, is this public endpoint something they could implement?

**Comment by eriwen** [comment]
Hi @paulmelnikow, thanks for the ping.

The code for plugins.gradle.org is unfortunately not open source right now. We have others asking to implement other features, and we're considering our options — stay tuned.

**Comment by robstoll** [comment]
Any progress on this one?

**Comment by eriwen** [comment]
I'm afraid not, Rob. Unfortunately, this is going to take a lot more time than we'd like due to how the plugin portal is setup right now. Doing what the Jib project did (see link above in the issue) would be best for now, but I will update you once this changes.

**Comment by loosebazooka** [comment]
This can be solved using maven metadata.
See: 
https://github.com/badges/shields/issues/1839
https://github.com/GoogleContainerTools/jib/pull/787
