### ISSUE TITLE
Gradle web services are down

### ISSUE THREAD

**Issue by plever** [gradle/gradle#1478]
### Expected Behavior
Able to login to gradle forums and view gradle plugins.

### Current Behavior
Not sure this is the right place to post this issue but, I can't download any gradle plugins or login to the forums there's an application error for both.  I'd post this on the forums but, I can't.

### Context
Can't build on a system that does not have a local cache of gradle plugins.

**Comment by agabara** [comment]
Same here. Amazon has some issues with its S3 service, maybe related.

**Comment by plever** [comment]
I'm assuming this was due to the S3 outage yesterday since it's working today.  

Closing
