### ISSUE TITLE
Improve performance of probing toolchains

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#14799]
Probing all java installations may take some significant time as it needs to start multiple JVMs. We should look into ways to make this faster as the cost is paid on each daemon right now.

Considerations:
* probe toolchains in parallel
* lightweight probing if we only need the version
* Cache probes on disk for reuse

**Comment by bmuskalla** [comment]
After talking to @lptr, this might actually be a good reason to move the existing detection and probing into a `UnitOfWork` and leverage the `WorkExecutor` (see `GeneratePluginAccessors` as an example). We should spike this when we take this one (build operations would be for free as well)

**Comment by bmuskalla** [comment]
As part of some other work (9bf5b6f5ebfa30fdc14348524364e193daef17f6), we know check the suppliers in parallel which already shaves off ~20% from collecting the suppliers (macOs still taking the longest due to `java_home`). Need to decide if we want to have a performance this for this as this involves triggering multiple external processes.

**Comment by ljacomet** [comment]
A number of changes have been made around probing for 6.8, including parallel probing. Let's wait and see how that impacts real world performance before doing more work on that topic.

**Comment by lptr** [comment]
Can this be closed now?

**Comment by ljacomet** [comment]
Indeed, the planned work on this topic has been done and were delivered with 6.8
