### ISSUE TITLE
Enable Groovy plugin to leverage toolchains

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#14801]
The groovy compile tasks should be able to consume a toolchain instead of an exectuable/java_home. This includes making the Groovy compile daemon compatible as well.

**Comment by bmuskalla** [comment]
And remove [docs stating otherwise ](https://github.com/gradle/gradle/pull/14826/files)

**Comment by ljacomet** [comment]
Groovydoc support will be added through #15283
