### ISSUE TITLE
Allow user to show all available toolchains

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#14804]
For debugging purposes, it would be good for users to see all available (or rather detected) toolchains including their metadata. 

Considerations:
* a default task like `model` or `dependencyInsight`
* show detected toolchains when resolving the first toolchain via --info level (and with metadata on --debug)

**Comment by bmuskalla** [comment]
@ljacomet Started to play around with this a bit. Would love to get your input before we go too far on this: https://scans.gradle.com/s/rmhkltj3dhxky/console-log?anchor=91

**Comment by bmuskalla** [comment]
And with colors

<img width="741" alt="Screenshot 2020-10-15 at 21 27 21" src="https://user-images.githubusercontent.com/316929/96176875-41fd5b00-0f2d-11eb-8a61-6f04e3bfaf77.png">

**Comment by ljacomet** [comment]
Two comments:
* We could consider grouping by vendor
* Language Version should only print the major and not the full tool version. If we believe the tool version matters (and I think it does), it should be shown in a different field.

Otherwise I like the format: simple and informative

**Comment by bmuskalla** [comment]
> We could consider grouping by vendor
We should certainly play around with that. We can't do it yet as the probes do not expose the vendor separately as this point (but we'll have that soon). It's sorted by their implementation name now (which has the vendor) so its sort of grouped.

> Language Version should only print the major
Fully agree.

**Comment by ljacomet** [comment]
This is now done
