### ISSUE TITLE
Incremental compilation wipes out aggregating processor file in Gradle 6.7

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#14808]
When you alter a java class that does not participate in the creation of file generated by an aggregating annotation processor the generated file is deleted. This behaviour did not occur in 6.6

See https://github.com/micronaut-projects/micronaut-core/issues/4277 for steps to reproduce.

### Expected Behavior

The file should not be deleted.

### Current Behavior

The file is deleted.

### Context

This has broken incremental compilation support in Micronaut and is a critical issue for us. See https://github.com/micronaut-projects/micronaut-core/issues/4277

### Steps to Reproduce 

See https://github.com/micronaut-projects/micronaut-core/issues/4277

### Your Environment

    Operating System: macOs
    Micronaut Version: 2.1.0
    Gradle: 6.7 rc4
    JDK Version: openjdk version "11.0.2" 2019-01-15

**Comment by jjohannes** [comment]
Fixed in #14813
