### ISSUE TITLE
Ensure compiler daemons are reused with toolchains involved

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#14800]
@melix indicates that we may not reuse the compiler daemons between runs for incremental compilation when toolchains are in the mix. Ensure this is the case

**Comment by bmuskalla** [comment]
In order to test-drive this change, we'll wait until the whole BT build is using toolchains so we can dog-food this. /cc @ljacomet

**Comment by ljacomet** [comment]
Closing as obsolete
