### ISSUE TITLE
CodeNarc Plugin does not print errors on console when using 'console' reportFormat

### ISSUE THREAD

**Issue by mohlendo** [gradle/gradle#1481]
When using the report format `console` like:

    codenarc {
      toolVersion = '0.26.0'
      reportFormat = 'console'
    }

I see no output in the console when CodeNarc finds rule violations.

**Comment by eriwen** [comment]
@mohlendo Would you please put together a simple example for our testing? Could you tell us about your environment (Gradle version, OS, etc) as well (build scan preferred)?

**Comment by mohlendo** [comment]
I have created a small project for reproducing this bug:  https://github.com/mohlendo/codenarc-console
Running `./gradlew clean build` prints no CodeNarc errors on the console.
I think this is because there is also a test failure, but the console logs:

```
:sub-module:codenarcTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sub-module:codenarcTest'.
> CodeNarc rule violations were found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.606 secs
```

**Comment by mohlendo** [comment]
And here is the buildscan: https://scans.gradle.com/s/vnmkzxtrmg2im

When you have a look at the console output you will see, that the codenarc reporting is missing

**Comment by mohlendo** [comment]
Is anything missing to make it actionable?

**Comment by eriwen** [comment]
@mohlendo Thank you for the extra info. This issue is actionable now.

**Comment by grv87** [comment]
`CodeNarcReports` interface still doesn't have `console` property. Could you add it so this report could be configured (enabled/disabled)?

**Comment by bmuschko** [comment]
@grv87 Did you try that with Gradle 4.1? That's the version that includes the feature. Please see https://github.com/gradle/gradle/pull/2170 for some usage patterns. Please provide a reproducible code example if that doesn't work for you.

**Comment by grv87** [comment]
@bmuschko, I'm with 4.2 now.

Code:
```groovy
task('codenarc', type: CodeNarc) {
  group 'Test'
  source 'Jenkinsfile'
  source 'build.gradle'
  for (f in new FileNameFinder().getFileNames(projectDir.path, '**/*.groovy')) {
    source f
  }
  configFile = file('config/codenarc/codenarc.groovy')
  reports {
    xml {
      enabled = true
      destination = codenarcXMLOutput
    }
    console { enabled = true } // I've added it here but nothing has changed
    html {
      enabled = true
      destination = codenarcHTMLOutput
    }
  }
}
```

**Comment by blindpirate** [comment]
@grv87 There's something wrong with current implementation. I've confirmed this issue. The message is mistakenly outputted with `info` level, so if you run with `--info` you should see the message.

We'll investigate this.

**Comment by bmuschko** [comment]
@blindpirate Can you create an issue for it?

**Comment by blindpirate** [comment]
@bmuschko Sure. It's in #3021 now.
