### ISSUE TITLE
Using auto-downloaded Java 8 toolchain on Windows fails intermittently

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#14823]
### Expected Behavior

Auto-downloaded toolchains should be usable.

### Current Behavior

```
Downloading api.adoptopenjdk.net/v3/binary/latest/8/ga/windows/x64/jdk/hotspot/normal/adoptopenjdk to C:\Users\runneradmin\.gradle\jdks\adoptopenjdk-8-x64-windows.zip
Installed adoptopenjdk-8-x64-windows.zip into C:\Users\runneradmin\.gradle\jdks\jdk8u265-b01
Starting process 'command 'C:\Users\runneradmin\.gradle\jdks\jdk8u265-b01\bin\java.exe''. Working directory: C:\Users\RUNNER~1\AppData\Local\Temp\1602322016793-0 Command: C:\Users\runneradmin\.gradle\jdks\jdk8u265-b01\bin\java.exe -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\RUNNER~1\AppData\Local\Temp\1602322016793-0 JavaProbe
Successfully started process 'command 'C:\Users\runneradmin\.gradle\jdks\jdk8u265-b01\bin\java.exe''

> Task :platform-tooling-support-tests:test FAILED
:platform-tooling-support-tests:test (Thread[Daemon worker,5,main]) completed. Took 6.203 secs.

Closing Git publish repo: D:\a\junit5\junit5\documentation\build\gitPublish
341 actionable tasks: 226 executed, 100 from cache, 15 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':platform-tooling-support-tests:test'.
> Illegal char <
> at index 50: C:\Users\runneradmin\.gradle\jdks\jdk8u265-b01\jre

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at help.gradle.org

BUILD FAILED in 6m 58s

Publishing build scan...
https://ge.junit.org/s/iqglklqwr7kqq
```

Source: https://github.com/junit-team/junit5/runs/1235021599

### Context

So far we've only seen this issue on Windows with GitHub Actions.

### Steps to Reproduce 

Unfortunately, the issue is intermittent and thus cannot be reproduced reliably.

### Your Environment

Build scan URL: https://ge.junit.org/s/iqglklqwr7kqq

**Comment by bmuskalla** [comment]
So I've tried to reproduce this with a small repository and GitHub actions on Windows. Also inspected the probe code to determine how we could reach that state. The only thing that may cause this (even though completely unlikely) is the fact that the probe returns a each key/value pair separated by the "jdk under probe" newline character while we use the Gradle JVMs newline char to parse it. But given they're running on the same machine, we should be able to assume those are the same. Experiments breaking the environment (e.g. setting up java with a JAVA_HOME that contains a newline character) have no effect on the correctness. Given this only happens rarely, I'd stop the investigation at this point, assume it's a Github infra issue and just `trim()` the returned probe values remove any whitespace/newlines.

@ljacomet Any more ideas?

**Comment by breskeby** [comment]
In the elasticsearch build we use the javaInstallationRegistry (see https://github.com/elastic/elasticsearch/blob/93e2064496a984a3e9e982ade22c7e9901656961/buildSrc/src/main/java/org/elasticsearch/gradle/info/GlobalBuildInfoPlugin.java#L222-L231) and seen this issue since updating to 6.7. Is there a chance of back porting this fix as a patch (e.g. 6.7.1) ?
