### ISSUE TITLE
Application execution output is lost sometimes

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#1482]
Running an application via `./gradlew run -q` will sometimes fail to show the application output.

This is the output from running a [trivial java application](https://gist.github.com/bamboo/9b285b85e4959db700b20028076b20cf) against a build from master as of 3d19493427c5dd2eeb2a3445b7fe4099cc90921b using the new default console, notice the output of the 7th execution is lost:

```
➜  hello-world git:(master) ✗ for i in {1..10}; do echo $i && g run -q; done
1
Hello, world!
2
Hello, world!
3
Hello, world!
4
Hello, world!
5
Hello, world!
6
Hello, world!
7
8
Hello, world!
9
Hello, world!
10
Hello, world!
➜  hello-world git:(master) ✗
```

### Expected Behavior
Application output should be shown every time.

### Current Behavior
Application output is lost sometimes.

### Your Environment
Local build from master as of 3d19493427c5dd2eeb2a3445b7fe4099cc90921b.

Build scan from one of the (successful) runs: https://e.grdev.net/s/3tr3baph6dyuk

**Comment by bamboo** [comment]
Upon further inspection it seems the first line of application output is actually overwritten.

**Comment by lacasseio** [comment]
Thanks @bamboo for reporting this, I will look into it.
