### ISSUE TITLE
Circular task dependency caused by property dependency inference

### ISSUE THREAD

**Issue by jbytecoder** [gradle/gradle#14824]
In gradle-6.6  a circular dependency is created on a task with property marked as both `@InputFile` and `@OutputFile` due
to dependency inference based on property connection

### Steps to Reproduce 
Consider following build:
```
import javax.inject.Inject

ext.controlFile = project.objects.fileProperty().fileValue(file("build/root.ctl"))

abstract class Producer extends DefaultTask {

  @InputFile
  @OutputFile
  abstract RegularFileProperty getControlFile();

  @Inject
  Producer(ObjectFactory factory) {
    getControlFile().convention(project.controlFile)
  }
}

tasks.register("producer",Producer) {
  doLast {
    println "producer did work"
  }
}
```
Let's assume that the file "build/root.ctl" exists so that task configuration is valid

### Expected Behavior
In presented build the task producer should have no task dependencies.

### Current Behavior
In gradle-6.2.2 this build works as expected, however in gradle-6.6  this build fails with circular dependency - the ":producer"
is made to depend on it self. I managed to discover why that is:  The combination of annotations on the property causes this. If I remove either  `@InputFile` or `@OutputFIle` the code works as expected. 

### Context
I have a plugin that aids me with version management.  I have a code that tracks number of builds per git branch and uses it to devise the total build count upon release. I think that both annotations in this case are valid. The task in question first reads from the configured file if it exists ( So this is a  sort of input file, conditional input file )and then at the end the file is written to ( So it also happens to be an output file ). This seemed valid in previous versions.  I used latest gradle just to keep up with gradle development.    

Perhaps if my usage of this annotations is deemed as invalid ( I/O property ). This case could be detected and reported. 
In any case i think that the code responsible for task dependency auto configuration should detect that it attempts to create
a circular dependency  

I'm also a little bit puzzled,  why task dependency auto configuration started here in the first place. I merely connected task owned property to owner-less property ( that is how I view properties created by project.objects ) and as i understand dependency auto configuration should only start when both properties are owned by task

**Comment by wolfs** [comment]
@jbytecoder You cannot mark the same property as input and output file. This code will fail with Gradle 7.0. Gradle currently doesn't have a good story for tasks which modify their own inputs. Check out https://github.com/gradle/gradle/issues/15616 for more information on this. If your use-case doesn't fit #15616 or is a new use-case, please comment on the other issue.
