### ISSUE TITLE
Investigate up-to-date checks when buildscript classpath changes

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#14830]
<placeholder>

Figure out how up-to-date checking works for tasks of external plugins when buildscript classpath changes.
With buildscript compilation avoidance, we might be in a situation where the buildscripts are not recompiled (non-ABI change in buildscript classpath) but the tasks of external plugins would fail the up-to-date checks and need to be rerun.

**Comment by jjohannes** [comment]
There is no concrete action in this issue and since nothing was done for almost half a year, I _assume_ there is no problem right now. If there is, it should be reported as a separate bug with reproducer.
