### ISSUE TITLE
Allow to configure maven repository url via property just as credentials

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#14844]
Hi would like to configure a repository via properties, and only refers to the repo via its name

### Expected Behavior

Having the following properties

```
github-mycompanyUrl=...
github-mycompanyUsername=...
github-mycompanyPassword=...
```

I would like to configure a repo this way

```
repositories {
    maven {
        name "github-mycompany"
        credentials(PasswordCredentials)
    }
}
```

Or even it'll be nice to refer to the name only

```
repositories {
    maven(name: "github-mycompany")
}
```

Maybe there's other consideration as the repositories can be configured with various settings.

### Current Behavior

Currently the url and eventually other setting have to be repeated in various places, and in particular when multiple projects targets the same repository.

```
repositories {
    maven {
        name "github-mycompany"
        url "https://maven.pkg.github.com/mycompany/private-repo"
        credentials(PasswordCredentials)
    }
}
```

Properties

```
github-mycompanyUsername=...
github-mycompanyPassword=...
```

### Context

Multi gradle project using a single internal repository. Migrating the URL repository would be transparent if we didn't have to open a PR to change the URL for every single project.

**Comment by mlopatkin** [comment]
This case is probably better solved with a [precompiled script plugin](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins). You can define common repositories there and include the plugin in the projects that need it. Then you'll have only a single place to change the repository's URL.

**Comment by bric3** [comment]
@mlopatkin Pre-compiled scripts don't solve anything because such script would likely be stored on the private repository which you'll have to configure to fetch these pre-compiled scripts. This makes the whole thing quite inelegant.

**Comment by mlopatkin** [comment]
How do you plan to pass the properties with this scheme? Via command line/environment variables?

**Comment by bric3** [comment]
I was thinking about Gradle properties.

Eg

```
repoName.username
repoName.token
...
```
