### ISSUE TITLE
Performance Test Failures when VCS Branch Name is too long 

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#14856]
When the VCS branch name is too long, the performance tests fail because they can't put the information into the database.

https://ge.gradle.org/s/hwpbj4l6znanm/tests/:performance:bigCppAppPerformanceTest/org.gradle.performance.regression.nativeplatform.NativeBuildPerformanceTest/assemble%20with%20header%20file%20change?anchor=e30&focused-exception-line=0-1-0#1

This happened because dependabot generates some insanely long branch names.

**Comment by wolfs** [comment]
@JLLeitschuh I don't think we should fix this on our side. Why are we running performance tests on those PRs? I think those individual PRs should not be merged but we should create one PR which replaces all usages of the old JUnit version by a newer one if it makes sense. And if you really want to build this PR, then build the `pull/<PR number>/head` branch on TC.

**Comment by JLLeitschuh** [comment]
@big-guy and I just ignored the performance failures and merged anyway. Since there are usually only 1-2 PRs ever generated at a time, most of the time merging them together doesn't make sense.
