### ISSUE TITLE
gradle fails when using a project directory as a source root

### ISSUE THREAD

**Issue by Jonatino** [gradle/gradle#14857]
### Expected Behavior
Gradle should build.

### Current Behavior
Gradle fails to build because it can not use a project dir as a sources root.

### Context
I want to have the following gradle directory structure.
```
core
----> src
---------> main
---------------> kotlin
-----------------------> *source files*

defs
---> *source files*

scripts
---> *source files*
```

The files inside of defs/scripts are Kotlin script files. These are scripts that can still be compiled for error checking, but are ran at runtime dynamically.

### Steps to Reproduce 
See video: https://dl.dropboxusercontent.com/s/sq5pqa1ohcycthy/SzsZ4rybef.mp4
Sample project: https://dl.dropboxusercontent.com/s/dcndh26tp4qrovm/GradleSubProjects.zip

### Your Environment
Windows 10
Build scan URL: https://gradle.com/s/7jy6jqsobl27k

**Comment by tfedyanin** [comment]
Hi @Jonatino, I try you project and found multiple shortcomings:

1. There is no files or directory `defs` in attachment.
2. You use `application` project as dependency, as I know for pure java projects it's not applicable and produce many strage things.
3. You ran script from intellij idea which produce warning for duplicate content root and do not apply sources location to module structure. You need to rewrite launcher to pure gradle executor to verify error.

**Comment by mlopatkin** [comment]
I was able to successfully build the project after adding necessary dependencies to the `:scripts` project:
```gradle
project(":scripts") {
    dependencies {
        compile project(":core")
        implementation "org.jetbrains.kotlin:kotlin-stdlib"
        implementation "org.jetbrains.kotlin:kotlin-reflect"
        implementation "org.jetbrains.kotlin:kotlin-script-runtime"
        implementation "org.jetbrains.kotlin:kotlin-script-util"
        implementation "org.jetbrains.kotlin:kotlin-compiler-embeddable"
        implementation "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable"
        implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core"
        implementation "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.3.7"
    }
```

As tfedyanin noted, import into IDEA produces a warning. Adding a `scripts/foo` dir helps though. This seems to be a limitation of IDEA, not Gradle.
