### ISSUE TITLE
Provide API to convert a `FileSystemLocation` into a `RegularFile` or `Directory` instance

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#14872]
Given a `FileSystemLocation`, I want to be able to convert it to a `RegularFile` or `Directory` instance.

Desired use case:

The output of a `Zip` task will always be a file and not a directory. So, I want to provide the following extension function:

```kotlin
internal fun Provider<Zip>.asFileProvider(): Provider<RegularFile>
```

Where the `RegularFile` is the `.zip` file itself.

Then, I could connect it as input to a custom task:

```kotlin
val input: RegularFileProperty = objects.fileProperty() 
```

Problem:

```kotlin
// can't be done
fun Provider<Zip>.asFileProvider(): Provider<RegularFile>

// can be
fun Provider<Zip>.asFileProvider(): Provider<FileSystemLocation>
```

This means that my downstream task's input has to be defined as:

```kotlin
val input: Property<FileSystemLocation> = objects.property(FileSystemLocation::class.java)
```

Which unfortunately is less specific. I've had to design all my inputs as `FileSystemLocation` when I wanted to be more specific with `RegularFile` or `Directory`.

Why? We cannot cast `DefaultFileSystemLocation` to a `RegularFile`, even though it is a file and not a directory

```kotlin
internal fun Provider<Zip>.asFileProvider(): Provider<RegularFile> = flatMap { zipTask ->
    zipTask.outputs
        .files
        .elements
        .map { fileSystemLocationSet: Set<FileSystemLocation> ->
            check(fileSystemLocationSet.size == 1) {
                "Zip task should have had only one element as output"
            }
            fileSystemLocationSet.first()  // the directory
        }
        .map { fileSystemLocation: FileSystemLocation ->
            // cannot cast DefaultFileSystemLocation to a RegularFile, even though it is a file and not a directory
            fileSystemLocation as RegularFile 
        }
}
```

If Gradle can provide an API to convert a `FileSystemLocation` into a `RegularFile` or `Directory` instance, then my problem would be solved

**Comment by big-guy** [comment]
Can't you do `zip.flatMap { it.archiveFile }`?

e.g.:
```
val zip: TaskProvider<Zip> = tasks.register<Zip>("zip")

val someFileProperty = objects.fileProperty()
someFileProperty.set(zip.flatMap { it.archiveFile })
```

**Comment by mlopatkin** [comment]
It seems that https://github.com/gradle/gradle/issues/14872#issuecomment-708864110 has an answer.
