### ISSUE TITLE
Kotlin scripts should be compiled with `-Xjvm-default=enable`

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#14875]
So as to allow classes defined within scripts to implement Kotlin interfaces containing `@JvmDefault` methods.

**Comment by bamboo** [comment]
Since we are on Kotlin 1.4 now we should probably use `-Xjvm-default=all`.

https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/

**Comment by eskatos** [comment]
Done in https://github.com/gradle/gradle/pull/16040
