### ISSUE TITLE
Let .gradle.kts scripts use Kotlin language and api 1.4

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#14888]
Gradle 6.8 upgrade the embedded Kotlin to 1.4 but keep the `.gradle.kts` scripts language and api to 1.3 for backwards compatibility. This issue is about changing that to 1.4.

This will allow build authors to use Kotlin language and api 1.4 in build scripts and precompiled scripts.

**Comment by eskatos** [comment]
This is a potential breaking change and must be done on a major version. Added to milestone 7.0

**Comment by eskatos** [comment]
Experiment in branch https://github.com/gradle/gradle/compare/eskatos/kotlin-dsl/lang-1.4

**Comment by ChristianBecker** [comment]
Hey @eskatos, is this branch available as a `SNAPSHOT` version?

**Comment by eskatos** [comment]
@ChristianBecker not yet, the experiment is not complete. This issue will be updated when there will be a snapshot to try out.

**Comment by eskatos** [comment]
Done in https://github.com/gradle/gradle/pull/15485

This can be tried using `7.0-20210112085059+0000`

**Comment by LouisCAD** [comment]
If I understand correctly, Gradle 6.8+ plugins can use Kotlin 1.4 in their code, but build scripts can only use Kotlin starting from Gradle 7.0?

**Comment by bamboo** [comment]
@LouisCAD Correct. In Gradle 6.8 build scripts are compiled against Kotlin 1.4 but the language version is still set to 1.3. Gradle 7.0 bumps the language version.

**Comment by LouisCAD** [comment]
Language version is set to 1.4 for Gradle plugins own code, or is the language version also set to 1.3 there?

**Comment by bamboo** [comment]
The Gradle `kotlin-dsl` plugin sets the language version to 1.3 in Gradle < 7.0 and to 1.4 in Gradle >= 7.0.
