### ISSUE TITLE
Cannot use apply plugin syntax together with the java-gradle-plugin

### ISSUE THREAD

**Issue by jacobilsoe** [gradle/gradle#1488]
I am writing some tests for a plugin and would like to apply that plugin in the test build.gradle file. I cannot use the plugins syntax since I need to "apply from" some file before applying the plugin. Trying to use the apply plugin does not work - the plugin was not found.

### Steps to Reproduce (for bugs)
Update this file in the official samples: samples\testKit\gradleRunner\automaticClasspathInjectionQuickstart\src\test\groovy\org\gradle\sample\BuildLogicFunctionalTest.groovy, changing:
```groovy
plugins {
  id 'org.gradle.sample.helloworld'
}
```
to
```groovy
apply plugin: 'org.gradle.sample.helloworld'
```
The test fails with:
```
Plugin with id 'org.gradle.sample.helloworld' not found.
```

**Comment by bmuschko** [comment]
Applying a plugin with the plugins DSL has to be declared as the first statement in a Gradle build script. This behavior is mandatory without and with the use of TestKit. For example the following would not work:

```
apply from: 'test.gradle'

plugins {
    id "com.bmuschko.tomcat" version "2.2.5"
}
```

The failure you'd see would be the following:

```
build file '/Users/bmuschko/dev/projects/gradle-playground/plugins/build.gradle': 3: only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed
```

Needing to apply a script plugin before another binary plugin almost certainly is a smell for bad practice. It sounds like you need to apply specific logic that your binary plugin reacts to. In your binary plugin implementation you should have logical that does exactly that: "if this logic is applied, then configure a task or plugin or something else a certain kind of way". How do you do that? Mostly likely with something like `project.tasks.withType(...) { // configure }` or `project.plugins.withType(...) { // configure }.

Can you elaborate on your use case?

**Comment by jacobilsoe** [comment]
I know about the plugins limitation. That was what I would like to work around by using the apply plugin syntax instead.
My specific use case is that I have a number of plugins defined in buildSrc. Some of the plugins need third party dependencies. I have defined the dependencies in a file called libraries.gradle. In the build.gradle file in buildSrc I have this:
```
apply from: "libraries.gradle"
```
so that the plugins can use these. I now want write a test for a plugin using the approach from automaticClasspathInjectionQuickstart.
But now that I think of it, I am not sure how best I can ensure that the plugin has access to the definitions in libraries.gradle. I might need to rethink how to test this.
But nevertheless I suppose apply plugin should work anyway?

**Comment by bmuschko** [comment]
> I have defined the dependencies in a file called libraries.gradle.

Why would your plugin need a list of dependencies? Dependencies are resolved during execution time and _only if_ a dependency is required by a specific task e.g. defined by your plugin. Does you plugin declare a custom task? I am also confused about why you declare dependencies in `buildSrc`. What you'll likely want is that the plugin already declares default dependencies out-of-the-box. Are you aware of [Specifying default dependencies for a configuration](https://docs.gradle.org/current/userguide/dependency_management.html#sec:configuration_defaults)?

> But nevertheless I suppose apply plugin should work anyway?

I don't quite understand what you mean by this statement. Please elaborate.

**Comment by jacobilsoe** [comment]
> Are you aware of Specifying default dependencies for a configuration?

No, I will look into this. Thanks for pointing me in that direction.

> I don't quite understand what you mean by this statement. Please elaborate.

I just mean that the example in the top of this thread should work, shouldn't it? The change from plugins syntax to apply plugin should work, or?

**Comment by bmuschko** [comment]
> I just mean that the example in the top of this thread should work, shouldn't it? The change from plugins syntax to apply plugin should work, or?

No, that won't work. Using the plugins DSL is mandatory. I think we should state this more clearly in the user guide. In fact I already have an [open issue on my plate](https://github.com/gradle/gradle/issues/1231) to straighten this out soon.

I am going to close this issue for now. Please add another comment if you want to further discuss.

**Comment by jacobilsoe** [comment]
What I really want to achieve is having a single place where all dependencies are defined. The same way as Gradle has it in gradle/dependencies.gradle. But looking through the Gradle source code I see that the classycle plugin has a dependency on 'classycle:classycle:1.4@jar'. This is similar to my plugin. However, to avoid duplication, I would like to "read" those dependencies from gradle/dependencies.gradle instead of hardcoding it in the plugin. Is that possible?

**Comment by edudar** [comment]
I posted on the [forum](https://discuss.gradle.org/t/testkit-and-plugin-dependencies/26267) first but then found this issue and seems like it's somewhat similar. I use [applying plugins to subprojects](https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl) technique in a test and it doesn't work as I expected. I see in the output that plugin is resolved and all dependencies are downloaded but when I apply it, it fails to find a class.
