### ISSUE TITLE
Leave comments and ordering untouched in the verification-metadata.xml file

### ISSUE THREAD

**Issue by scottdweber** [gradle/gradle#14885]
We have added XML comments to our `verification-metadata.xml` file to provide additional context around specific content, as well as re-ordering some of the content to bring related information closer to each other. However, if we update this file with `./gradlew --write-verification-metadata sha256 help`, all comments and custom ordering are lost, which makes it difficult to update this file. It would be really nice if the file writer would leave comments and custom ordering of content in place when making updates to the file.

Ordering, in particular, might be tricky, since it's nice to have all the versions of a library next to each other, but maybe there's a way around this?

### Expected Behavior
Comments should be left alone in the `verification-metadata.xml` file when re-writing the file. And, ideally, content that has been moved around in the file should be left where it was located.

### Current Behavior
All comments are stripped out of the file, and all content is re-ordered to strictly follow the alphabetic ordering default.

### Context
We have had to make some manual alterations to our `verification-metadata.xml` file for several reasons, mostly related to dependencies that are pulled during CI, but not on local developer machines. We were hoping to use the `--write-verification-metadata` flag to easily cleanup the XML file as we update and remove dependencies from our project. This also means that we need to make sure that all of those dependencies that are not used on developer machines get stripped out of the file. In order to make it easier to maintain, we've moved all of these dependencies to the top of the file and added several comments that explain exactly why they're there. However, with the `--write-verification-metadata` flag clobbering these comments and re-ordering, it doesn't fully solve our concern.

**Comment by melix** [comment]
We're aware of this issue. However:

- we recommend `--write-verification-metadata` only for bootstrapping: added/updated dependencies _should_ be done manually
- if you still want to do this, what we recommend is to look at the diff, analyze the added/removed dependencies, and selectively pick the changes to the file
- alternatively you can run with `--dry-run` and compare the generated dry-run.xml file with the original one

Keeping comments and ordering is indeed too complex ATM.

**Comment by big-guy** [comment]
@ljacomet do you think this is better now?

**Comment by REPLicated** [comment]
We would also love to be able to add comments to the file (especially in the `configuration` block) without Gradle removing them again.

The less friction, the more people use this valuable Gradle feature.

**Comment by ljacomet** [comment]
As of upcoming Gradle 7.4, comments in the file header - that is comments between `<?xml` and the first tag `<verification-metadata` will be preserved.

There is no plan to add support for comments elsewhere in the file at this stage. If you believe it makes sense, I would prefer discussing the introduction of a dedicated attribute / node for this.

Note that we also went further with regards to ordering: all content is sorted to make sure that regenerating the file after an update creates the smallest change possible.

We did that to allow using generation as an update strategy.

**Comment by yeikel** [comment]
> As of upcoming Gradle 7.4, comments in the file header - that is comments between `<?xml` and the first tag `<verification-metadata` will be preserved.
> 
> There is no plan to add support for comments elsewhere in the file at this stage. If you believe it makes sense, I would prefer discussing the introduction of a dedicated attribute / node for this.
> 
> Note that we also went further with regards to ordering: all content is sorted to make sure that regenerating the file after an update creates the smallest change possible.
> 
> We did that to allow using generation as an update strategy.

We are experiencing this problem with what seems to be this same problem


Example : 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<verification-metadata xmlns="https://schema.gradle.org/dependency-verification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://schema.gradle.org/dependency-verification https://schema.gradle.org/dependency-verification/dependency-verification-1.1.xsd">
   <configuration>
      <!--
         Verify the integrity of artifacts using checksums.
         https://docs.gradle.org/current/userguide/dependency_verification.html#sub:enabling-verification
      -->
      <verify-metadata>true</verify-metadata>
```
