### ISSUE TITLE
kotlin language version not updated to 1.4 with gradle 6.8-M1

### ISSUE THREAD

**Issue by wolfseifert** [gradle/gradle#14887]
Gradle 6.8-M1 uses kotlin 1.4.10, but does not allow to use new kotlin 1.4 features (like trailing commas). This is probably due to src/kotlin-dsl/org/gradle/kotlin/dsl/KotlinSettingsScript.kt defining "-language-version", "1.3", "-api-version", "1.3". Please update to "1.4".

**Comment by eskatos** [comment]
This was done on purpose because it is a breaking change for existing builds.

Scripts will move to language and api 1.4 on the next major version, 7.0.
See https://github.com/gradle/gradle/issues/14888

Also see the discussion in #12660 for some more context
