### ISSUE TITLE
Gradle should remove transforms-2/files-2.1/.../unzipped-distribution

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#14898]
### Expected Behavior

It looks like Gradle does not really use `.gradle/caches/transforms-2/files-2.1/.../unzipped-distribution/...`, so it should remove the files earlier.

### Current Behavior

`.gradle/caches/transforms-2/files-2.1` contains several unzipped distributions (e.g. 6.6, 6.7-rc-5).
* Extra files in `.gradle/caches` results in extra space usage at CI servers
* IntelliJ IDEA indexes `unzipped-distribution/...` files for some reason

### Context

I'm analyzing `.gradle` contents, and extra files make the comparison harder.

**Comment by wolfs** [comment]
Gradle creates that directory for IDE support. It contains the sources of the distribution: https://github.com/gradle/gradle/blob/e0dd1c8d5f7e686b303ffbfbf0700b7e80dfc88a/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/resolver/SourceDistributionProvider.kt#L38-L53

I think this transform should not run on CI, and IDEA would cause the transform to run. Did you find the directory on CI as well?

**Comment by vlsi** [comment]
Thanks for the clarification. I think I see the directory on my local machine only.
