### ISSUE TITLE
Task 'PublishToMavenRepository': Property 'credentials' cannot be serialized

### ISSUE THREAD

**Issue by lschwahn** [gradle/gradle#14902]
Since Gradle 6.6 in a java-project the task "PublishTomavenRepository" fails with java.io.NotSerializableException, when the following Code is applied: 

```
tasks.withType(PublishToMavenRepository).configureEach {
    outputs.upToDateWhen { true }
}
```

We are applying this code to make sure the publish-task is not executed when the jar-Task was UP-TO-DATE (this is our fix for #11203). In Gradle 6.5.1 this workaround was still working.

### Expected Behavior
When this code is applied, the task "publish" is UP-TO-DATE, when the task "jar" was UP-TO-DATE.

### Current Behavior
When this code is applied, the Task "publish" fails with "NotSerializableException".

### Context
We are trying not to publish artifacts, which aren't changed since the last build.

### Steps to Reproduce 
Unzip the attached zip-File:
[publish_notserializable_exception.zip](https://github.com/gradle/gradle/files/5400565/publish_notserializable_exception.zip)
```
cd experimente
./gradlew publish
```

### Your Environment
Build scan URL: https://scans.gradle.com/s/4mtfrptxthqmi

**Comment by bmuskalla** [comment]
This has been fixed by #15217 for 6.8
