### ISSUE TITLE
Gradle version 6.5 --scan throws could not resolve plugin artifact com.gradle:gradle-enterprise-gradle-plugin:3.3.3

### ISSUE THREAD

**Issue by saradach** [gradle/gradle#14900]
Hi All,

I am using Java 8 and Gradle version 6.5. 

I am getting error the below error

```
* Where:
Auto-applied by using --scan

* What went wrong:
Plugin [id: 'com.gradle.enterprise', version: '3.3.3', artifact: 'com.gradle:gradle-enterprise-gradle-plugin:3.3.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle:gradle-enterprise-gradle-plugin:3.3.3')
  Searched in the following repositories:
    maven(https://artifactory.int.corp.sun/artifactory/public/)
```

so I tried to add the plugin in settings.gradle

```
pluginManagement {
    repositories {
        maven { url "https://artifactory.xxx/artifactory/public/" }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.gradle.enterprise") {
                useModule("com.gradle:gradle-enterprise-gradle-plugin:3.3.3")
            }
        }
    }
}

plugins {
    id "com.gradle.enterprise" version "3.3.3"
}

rootProject.name = 'entitlements-customer-api'

```
The pulgin is availiable in com.gradle but trying to fecth from org.gradle

Any help would be appreciated.

**Comment by saradach** [comment]
I am using --stracktrace or --debug as alternative
 but still not sure why --scan throws the below error

could not resolve plugin artifact com.gradle:gradle-enterprise-gradle-plugin:3.3.3

**Comment by mlopatkin** [comment]
The Gradle Enterprise plugin (which powers build scans) lives at Gradle's plugin portal repository. It isn't a built-in plugin. You should either mirror the plugin and its dependencies to your private repository or add `gradlePluginPortal()` as a repository under `pluginManagement` block.
