### ISSUE TITLE
Failed to load native library error when using Gradle 3.4

### ISSUE THREAD

**Issue by fritaly** [gradle/gradle#1493]
### Expected Behavior

Upgrading from Gradle 3.3 to 3.4 should work.

### Current Behavior

On certain build machines, upgrading from Gradle 3.3 to 3.4 throws this error.

```
23-Feb-2017 03:18:56	FAILURE: Build failed with an exception.
23-Feb-2017 03:18:56	
23-Feb-2017 03:18:56	* What went wrong:
23-Feb-2017 03:18:56	Failed to load native library 'libnative-platform.so' for Linux amd64.
23-Feb-2017 03:18:56	
23-Feb-2017 03:18:56	* Try:
23-Feb-2017 03:18:56	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

This issue relates to this Gradle forum [post](https://discuss.gradle.org/t/failed-to-load-native-library-error-when-using-gradle-3-4/21723).

### Context

This issue only happens when building on a CI build machine (hosting CentOS 5.8) (not locally on my Mac).
 

### Steps to Reproduce (for bugs)

Even a simple Gradle project with an empty build script can reproduce the issue as it happens prior invoking Gradle.

### Your Environment

 * Build scan URL:

**Comment by eskatos** [comment]
@fritaly, could you please run again with `--stacktrace` and provide the output, or share a [build scan](https://gradle.com/scans/get-started)?

**Comment by jim-gish-at-oracle-com** [comment]
Even a simple gradle -version fails.  No stack trace or build scan possible -- it doesn't get that far.  In our case we're seeing this on Oracle Enterprise Linux (el5uek) (pretty much the same as RHEL).
Version: Linux 2.6.39-400.210.2.el5uek amd64

**Comment by adammurdoch** [comment]
Could you try running the native-platform test application on these machines and sending us the stack trace?  The test app is at https://repo.gradle.org/gradle/webapp/#/artifacts/browse/tree/General/libs-releases-local/net/rubygrapefruit/native-platform-test.

If possible, please run version 0.13 (used by Gradle 3.4) and 0.12 (used by Gradle 3.3) so we can see whether the failure is something new, or something old that was hidden in older Gradle versions.

**Comment by fritaly** [comment]
Here you are:

Version 0.12 yields the following output.

```
* Stdout: terminal
* Stderr: terminal
* Terminal implementation: Curses terminal on stdout
* Terminal size: 204 cols x 44 rows
* Text attributes: yes
* Color: yes
* Cursor motion: yes

TEXT ATTRIBUTES
[normal] [bold] [normal]

COLORS
[black] [black]
[red] [red]
[green] [green]
[yellow] [yellow]
[blue] [blue]
[magenta] [magenta]
[cyan] [cyan]
[white] [white]

CURSOR MOVEMENT
[1]       [2]
[3]       [4]
done!
```

Version 0.13 fails with this error:

```
Exception in thread "main" net.rubygrapefruit.platform.NativeException: Failed to load native library 'libnative-platform.so' for Linux amd64.
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:66)
	at net.rubygrapefruit.platform.Native.init(Native.java:55)
	at net.rubygrapefruit.platform.Native.get(Native.java:80)
	at net.rubygrapefruit.platform.test.Main.terminal(Main.java:80)
	at net.rubygrapefruit.platform.test.Main.main(Main.java:75)
Caused by: java.lang.UnsatisfiedLinkError: /dev/shm/native-platform2247054862715772268dir/libnative-platform.so: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by /dev/shm/native-platform2247054862715772268dir/libnative-platform.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at net.rubygrapefruit.platform.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:50)
	... 4 more
```

I had noticed that the failure occurred on a machine running CentOS 5.8 but not on CentOS 6.5. Does it mean this failure will occur on any machine running an old glibc version ?

In my case, I have:

```
$ ldd --version
ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by rhaendel** [comment]
I'm currently having the same issue on two machines running Debian GNU/Linux 5.0, ldd (GNU libc) 2.7.

**Comment by adammurdoch** [comment]
@fritaly thanks for running those tests.

And yes, the failure will happen on machines with an older glibc. We'll get a fix into Gradle 3.5.

**Comment by eriwen** [comment]
@adammurdoch Is this still in progress and intended to go into 3.5?

**Comment by eskatos** [comment]
@eric, this should be fixed in `master` since https://github.com/gradle/gradle/commit/4c78b4c85db2f02a98e5fb022d68c33a7cb06f2f

@fritaly, @rhaendel, @jim-gish-at-oracle-com, could you confirm it works for you using a nightly?
This one should do: https://services.gradle.org/distributions-snapshots/gradle-3.5-20170314221603+0000-bin.zip

**Comment by fritaly** [comment]
@eskatos yes it works with the nightly build.

**Comment by tompluess** [comment]
just ran into this issue, since we had the same failure, when running on Gitlab CI:
```
Failed to load native library 'libnative-platform.so' for Linux amd64.
```
Using the nigthly build mentioned by @eskatos in the `gradle-wrapper.properties` worked for me. Thanks!

**Comment by eskatos** [comment]
Thanks for the feedback @fritaly & @tompluess 
3.5 is coming soon
I'll go ahead and close this issue

**Comment by c3ph3us** [comment]
@eskatos this issue will be present also when  env var GRADLE_USER_HOME is inaccessible (this could be due to user has no rights or file is not present) so please add some **checkups on gradle run if access to env var file is not restricted and its present** 

simple to test 

`$ chmod  000 $GRADLE_USER_HOME`
`$ gradle --version`


```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.so' for Linux amd64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

**Comment by Shai1436** [comment]
I have used Homebrew to install gradle. It finished without errors. But it says 

> Failed to load native library 'libnative-platform.dylib' for Mac OS X x86_64

, while running 'gradle' command in the console.
I have also tried downloading the zipped files and extracted it in /opt/gradle/. I changed the folder permission to 777, but the issue persists.

**Comment by afadili** [comment]
Please Can someone show me how to do the nightly build to fix this problem ?

**Comment by marcphilipp** [comment]
@afadili Please refer to https://gradle.org/nightly/.

**Comment by afadili** [comment]
I can't have the lastest version of gradle, even if i follow these steps I still have the version 3.4.1

**Comment by marcphilipp** [comment]
Could you please show me the commands you ran and their output?

**Comment by marcphilipp** [comment]
@afadili I just realized there's no need to use a nightly build because Gradle 3.5 has been released a long time ago. In order to reduce the number of people that get notified of comments, please open a new issue for the wrapper-related problem you're having.

**Comment by shabeepk** [comment]
We'e seeing this issue on Gradle 4.8.1

```
------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.14.62-65.117.amzn1.x86_64 amd64
```

JDK version
`1.8.0_181`

glibc version 

```
Name        : glibc
Arch        : x86_64
Version     : 2.17
Release     : 222.173.amzn1
Size        : 14 M
Repo        : installed
From repo   : amzn-updates
Summary     : The GNU libc libraries
URL         : http://www.gnu.org/software/glibc/
License     : LGPLv2+ and LGPLv2+ with exceptions and GPLv2+
Description : The glibc package contains standard libraries which are used by
            : multiple programs on the system. In order to save disk space and
            : memory, as well as to make upgrading easier, common system code is
            : kept in one place and shared between programs. This particular package
            : contains the most important sets of shared libraries: the standard C
            : library and the standard math library. Without these two libraries, a
            : Linux system will not function.
```

Any ideas why ?
