### ISSUE TITLE
ConfigurationVariantDetails mapToMavenScope test scope support

### ISSUE THREAD

**Issue by fedorl** [gradle/gradle#14934]
ConfigurationVariantDetails.mapToMavenScope should support all maven allowed scopes

Currently (Gradle 6.6.1):
```
components.java.withVariantsFromConfiguration(configurations.testFixturesApiElements) {
    mapToMavenScope('test')
}
```
_> Invalid Maven scope 'test'. You must choose between 'compile' and 'runtime'_

Maven defines 5 valid dependency scopes and it is up to the build author to decide which scope is published to the generated pom. Customizing resulting scope after generation e.g. with pom.withXml is hacky and it is not trivial to match configuration for the generated dependency.

**Comment by ljacomet** [comment]
Published Maven metadata will not make use of the `test` scope. When you consume a library, that information is not used. So there is no plan on the Gradle side to enhance that support.

**Comment by ljacomet** [comment]
Closing as "will not fix"

**Comment by fedorl** [comment]
> Published Maven metadata will not make use of the test scope. When you consume a library, that information is not used.

When you consume from Gradle with gradle metadata it may be not (as the generated pom in general), but when you consume the published pom from maven, obviously it is used. Please look at https://github.com/gradle/gradle/issues/14936. Obviously many maven projects use test scope in the published pom and test scope IS the correct way to publish test fixtures or other test dependencies for standard maven pom, not the wrong compile scope Gradle publishes in the pom. 

Publishing test dependencies with compile scope for standard maven pom seems plainly wrong, IMHO there is no any justification having junit or fixtures with compile scope in the published pom as it will incorrectly bring transitive test dependency to maven projects on compile scope. 

I'm not sure why it requires some special "support". It should be the decision of the build author and Gradle should just verify it is one of maven scopes. Filtering out a scope for which Gradle authors have an idea that it is "not used" scope and calling adding a standard maven scope to allowed list an "enhancement" is a bit against the documentation claim that Gradle publishes maven compatible pom to the repository.

**Comment by ljacomet** [comment]
The fact that many Maven projects publish their `test` dependencies is because the POM file is both a sharing format and a build format. And the later leaks information in the former.

When you declare a `test` dependency in Maven, its _transitive `compile` scope dependencies_ will be added to the test compile classpath, while _its transitive `runtime` scope dependencies_ will be added to the test runtime classpath.

The "transitive" `test` dependencies will be completely ignored as [it is not a transitive scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope)

So Gradle is fully compatible with what matters for _published_ POMs.

**Comment by fedorl** [comment]
I have a feeling you misunderstand/misinterpret the problem. 

Let me illustrate with https://github.com/gradle/gradle/issues/14936: 

When one publishes a regular jar with junit test classpath dependency, junit dependency **is** added by Gradle to the resulting pom, with the **test** scope. This IS the current behavior, it is correct and expected, conforming to the behavior you describe above (and it is in fact it implies there is an internal mapping to the maven test scope). So I'm not sure why you provide the description above enumerating the known facts, there is no problem and this is exactly the behavior one expects.

The problem arises when the Gradle publishes a test fixture (a feature which does not directly exist in maven and by large should map to a test classifier jar in maven pom, consumed by maven with the test scope, while Gradle consumers should use the new Gradle metadata instead). 

When fixture is published, junit and other fixture dependencies are suddenly published as a dependency with **compile** scope, not a test scope! This is not expected and this seems obviously incorrect behavior, leaking test fixture dependencies into compile class path (and not the test compile class path as expected). One obviously would expect test fixture compile dependencies to appear in the classic published pom under the test scope (and consumed in the test compile classpath as you describe), and not map to the compile scope and leak into the consumer compile classpath.

Was it possible to mapToMavenScope('test'), the problem (IMHO a fixture publishing bug) was easily and generically solved.  Now it requires manipulating the resulting pom xml to determine fixture dependencies which should not be at compile scope of a consumer and changing their scope to test, which is a quirk and is fragile. 

The above is a specific problem/bug, but naturally it leads to the discussion why withVariantsFromConfiguration .. mapToMavenScope(xx) should be restricted by Gradle to some arbitrary scope subset at all. It is an advanced API for build authors and hence why not let the build author to decide which scope to map in the resulting pom. Were the Gradle developers ideas and default mapping sufficient in all imaginable cases, there was no need to expose this mapToMavenScope API to build authors in the first place.
