### ISSUE TITLE
'java-gradle-plugin' should use the 'java-library' over the 'java' plugin

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#1494]
3.4 "deprecates" some of the configurations used in the `'java'` plugin.
The `'java-gradle-plugin'` should use the `'java-library'` plugin instead of it.

### Expected Behavior

Dependency scopes on published plugins have correct scopes.

### Current Behavior

Plugin `pom` scopes published are affected by [#1118: Published POMs using the `maven-publish` plugin have "runtime" for all dependency scopes](https://github.com/gradle/gradle/issues/1118)

### Your Environment

* Gradle 3.4
* `'java-gradle-plugin'`

**Comment by oehme** [comment]
You can just apply `java-library` on top of it for now. Also, we corrected the publishing for the `java` plugin as well and the published `pom` matches the behavior inside a multi-project build (i.e. both the old `compile` and `runtime` configurations are leaked into downstream projects and are thus assigned to Maven's `compile` scope). 

So the "current behavior" described above is not what should happen (unless there is a bug).

**Comment by mkobit** [comment]
Thanks @oehme for the quick response, I'll double check in the next couple days if the current behavior is actually what happens or not and follow up on this issue. 

I wanted to file this as a sort of tracking issue before I forget about it, because this seems like a good place to be able to make a contribution.

**Comment by eriwen** [comment]
@mkobit Indeed. It sounds like you're interested in contributing here. Looking forward to seeing what you do.

**Comment by jjohannes** [comment]
Part of: #9353
