### ISSUE TITLE
Could not add entry ':app:bundleReleaseJsAndAssets' to cache executionHistory.bin > java.lang.IllegalArgumentException: Block payload exceeds maximum size

### ISSUE THREAD

**Issue by salvoravida** [gradle/gradle#14952]
Could not add entry ':app:bundleReleaseJsAndAssets' to cache executionHistory.bin (/Users/runner/work/1/s/apps/RNmobile/android/.gradle/5.5/executionHistory/executionHistory.bin).
> java.lang.IllegalArgumentException: Block payload exceeds maximum size

Basically you are using int instead of long on block payload for caching, so if the task genrate a over 2gb cache payload,
the task will crash

https://github.com/gradle/gradle/blob/master/subprojects/persistent-cache/src/main/java/org/gradle/cache/internal/btree/FileBackedBlockStore.java#L219

**Comment by salvoravida** [comment]
is there a way to ignore executionhistory.bin? basically the idea is: we do not need executionhistory.bin on CI

**Comment by salvoravida** [comment]
my temp workround:

 public void put(K key, V value) {
    // do nothing.
   }


is there a command-line option for disable store cache?

**Comment by john-spare** [comment]
Currently on gradle 5.6.4, are there any available command-line options available to turn off store cache? Or was this resolved in a later version of gradle?
