### ISSUE TITLE
Inconsistent and wrong examples or description in toolchain documentation

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#14955]
https://docs.gradle.org/current/userguide/toolchains.html#specify_custom_toolchains_for_individual_tasks says,
> In the example below, we configure the default toolchain to use JDK8 for compiling and testing. Additionally, we introduce a new Test task that is going to run our unit tests but using a JDK 14.

But the examples (Groovy and Kotlin) do not match that description and also do not match each other.
The Groovy example configures all `JavaCompile` tasks and the existing `test` task,
the Kotlin example configures all `JavaCompile` and all `Test` tasks.

**Comment by bmuskalla** [comment]
Thanks for reporting @Vampire - I'll fix this
