### ISSUE TITLE
Kotlin DSL hides configuration errors in IDEA

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#14957]
When there is an error in a Kotlin build script and I hit "Refresh Gradle projects" in IDEA, the build simply continues on errors. It only issues a couple of warnings saying "This script caused build configuration to fail", but these get burried in the log. This means that the user is confronted with hundreds or thousands of follow-up errors in the `Build` view instead of getting a clear stacktrace to the first error that made the build fail. Even more confusing, the final message says `BUILD SUCCESSFUL`. This is also a performance issue, because all these follow-up errors take a while to aggregate.

### Expected Behavior
When there is an error in a build script, refreshing the projects should fail immediately and show the trace to the error, just like calling `gradle help` would.

### Current Behavior
Gradle just keeps going, running into countless follow-up errors that flood the log.

### Context
I was editing build scripts and made some mistake, syncing didn't tell me what's wrong but instead gave me thousands of `CacheOpenException`s that made me think something was wrong with Gradle. I had to drop to the command line and run `gradle help` to see the true problem.

### Steps to Reproduce 
Check out `gradle/gradle` and add `throw RuntimeException` to the `plugins {}` block in `subprojects/files/build.gradle.kts`. Import into IDEA and see 600+ errors saying that `project files can't be resolved`.

**Comment by eskatos** [comment]
Thanks for the report @oehme 
Could you please share the IntelliJ version and Kotlin IntelliJ plugin version you were using?

@NataliaUkhorskaya, @snrostov, @vladimirdolzhenko,
It seems the lenient mode meant for grabbing kotlin script models in the presence of errors is abused and used for the whole IntelliJ import process.

**Comment by oehme** [comment]
I'm using 2020.2.3, with Kotlin 1.4.10

**Comment by snrostov** [comment]
@eskatos Thanks!

@vladimirdolzhenko It seems it is caused by your change https://github.com/JetBrains/kotlin/commit/23d33f51a2513219fc28e753fabee346912661b5#diff-f11c3a5fedecb68616ad4f0c07336315e169256e779f4403cacf8a6e2526f1bcR75. If I'm not missed something you are removed `throw IllegalStateException(...` for the latest IntelliJ version in case of errors.

It should not be removed. This exception is used to terminate import to avoid importing broken models in case of errors in `*.gradle.kts` scripts.

**Comment by vladimirdolzhenko** [comment]
@snrostov I don't think so as this change is only in current master (unreleased 1.4.30) and would not make any effect for 1.4.10

**Comment by snrostov** [comment]
@oehme Could you please share the Gradle version you were using?

**Comment by snrostov** [comment]
Ooops, @vladimirdolzhenko you are right sorry. we definitely need to fix it for 1.4.30, but that seems another problem, will create an issue in youtrack.

JFR for this issue: seems we have another problem for Gradle older than 6.1: we are checking `kotlinDslScriptsModelImportSupported` before stepping in this code. so, if one has an old Gradle, the import is not canceled too. We will discuss it internally and fix, will create an issue in youtrack too (will post here)

**Comment by oehme** [comment]
I was building `gradle/gradle`, which uses Gradle 6.8 nightlies. So no old version.

**Comment by eskatos** [comment]
This has been changed in IntelliJ since then. The IDE import/sync will now fail fast on the first error.
