### ISSUE TITLE
gradlew bundleRelease fails without args but succeeds with --scan

### ISSUE THREAD

**Issue by gabriel-tentaculo** [gradle/gradle#14967]
If I run my react-native (v 0.60.5) project with the command below it fails every single time
"bundle-android": "cd android && export ANDROID_X=1 && ./gradlew clean && ./gradlew bundleRelease",
But if I add -- scan like so below, it successfully bundles every single time
"bundle-android": "cd android && export ANDROID_X=1 && ./gradlew clean && ./gradlew bundleRelease --scan",

### Expected Behavior
Either fail both times with or without scan or bundle successfully for both cases

### Current Behavior
with --scan the bundleRelease is successfull, without it it fails

### Context
I use this command to generate a new release version of my app to send to google play

### Steps to Reproduce 
Just run both commands and it will be clear what happens

### Your Environment

Here is the link to my react-native package.json file and the android folder from that project, if that helps.
If more files and info is needed let me know so I can provide.
https://drive.google.com/drive/folders/1IR_yy9mXTA-YRTa2DYwXt8SKLE1Phl4U?usp=sharing
sdkmanager --list output is included in the link above

```
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

This is one of the scans that worked out just fine, now I use the --scan param just to be able to bundle my app but do not upload the scan data anymore, which is a nice workaround for me
Build scan URL: https://scans.gradle.com/s/5gsb4k33z7xna

So, in order for me to understand better what is happening, could someone tell me what is it that changes when the --scan param is added that it makes the bundle process to succeed?
Colleagues from work tell me this could be related to my java environment setup, but how could that be so if the scan makes it work?
**What I'm looking for here is more information so I can better narrow down whats wrong with my setup that it does not bundle as expected when removing the --scan argument.**

Thank you

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. Could you please show the error message that you're getting? We're sorry that it took is that much time to get to this issue.

This issue will be closed after 7 days unless you can provide more information.

**Comment by mlopatkin** [comment]
Closed as a non-actionable without additional information.
