### ISSUE TITLE
Please include LICENSE in gradle-wrapper.jar

### ISSUE THREAD

**Issue by hyandell** [gradle/gradle#14968]
Could you include the LICENSE file in the gradle-wrapper.jar, please?

That way your jar would be self-attributing and your users would not have to consider whether they need to add a separate LICENSE file whenever they place that jar file in their codebases.

### Expected Behavior
The license applying to the contents of gradle-wrapper.jar, and any accompanying files such as a NOTICE, would appear in META-INF/ within said jar.

### Current Behavior
There is no licensing within the jar.

### Context
It causes doubt for users on whether you expect a separate license file to be placed with the jar file.

**Comment by swltr** [comment]
I agree that having license information for the wrapper JAR would be very helpful for all projects trying to be compliant. Automatically adding a `gradle/wrapper/LICENSE` file could be an alternative. That would document the license more visibly.

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.
