### ISSUE TITLE
java-library init template should use java-library plugin

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1497]
### Expected Behavior
As a user, I want Gradle to encourage best practices by leveraging the hot new java-library plugin in project bootstrap templates

### Current Behavior
`gradle init --type java-library` still generates a project that uses the `java` plugin.

### Context
It is unclear how many users this will help, but presumably thousands will try this out.

### Your Environment
N/A

**Comment by eriwen** [comment]
Here's another one for ya if you want @mkobit ;)

**Comment by pioterj** [comment]
@eriwen From what I can see this is already done in 3.4.

**Comment by glefloch** [comment]
Yes I just tried it, the generated `build.gradle` uses `java-library` plugin.

**Comment by eriwen** [comment]
My mistake. I tried this init template in one of my projects, but perhaps I wasn't on Gradle 3.4. Closing as invalid.
