### ISSUE TITLE
archiveVersion does not work in manifest file creation

### ISSUE THREAD

**Issue by alexanderveit** [gradle/gradle#14972]
Gradle 6.7 build complains about
```
The AbstractArchiveTask.version property has been deprecated.
This is scheduled to be removed in Gradle 7.0. Please use the
archiveVersion property instead. See https://docs.gradle.org/6.7/dsl
/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#
org.gradle.api.tasks.bundling.AbstractArchiveTask:version for more details.
```
When changing `build.gradle` according to https://docs.gradle.org/current/userguide/building_java_projects.html#sec:jar_manifest to
```gradle
jar {   
        manifest {
                from("src/main/resources/META-INF/MANIFEST.MF")
                attributes(
                        "Implementation-Title": project.name,
                        "Implementation-Version": archiveVersion)
        }
}
```
the entry in the `MANIFEST.MF` created is
```
Implementation-Version: task ':jar' property 'archiveVersion'
```
With `version` it works as expected.

### Expected Behavior
The entry in the `MANIFEST.MF` should be
```
Implementation-Version: 1.0.0-SNAPSHOT
```

### Current Behavior
The entry in the `MANIFEST.MF`  is
```
Implementation-Version: task ':jar' property 'archiveVersion'
```

**Comment by bmuskalla** [comment]
`archiveVersion` is a lazy property. What you see is the toString of the property itself, not its value. You can use `Property#get()` to resolve the real value. Please see this part of the documentation: https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties

**Comment by alexanderveit** [comment]
Thanks for the explanation. `"Implementation-Version": archiveVersion.get()` works.

But now I'm even more unsure if this is a bug in the documentation or a bug in the implementation. I would suggest the second because to me it seems quite useless to have output like `task ':jar' property 'archiveVersion'` in the generated manifest attributes.

**Comment by ljacomet** [comment]
There is something fishy with your setup. When passing a `Provider`, which a `Property` is, into the `manifest` configuration, you should get a result equivalent to calling `get()` on the property.
I reproduced that in a simple example and this is even [documented](https://docs.gradle.org/6.7/userguide/building_java_projects.html#sec:jar_manifest) exactly like this.

Are you not accidentally forcing a `toString` somewhere in your code between the `attributes` configuration and the task execution?

**Comment by ljacomet** [comment]
Unless you can provide a reproducer, this issue will be close as non reproducible.

**Comment by alexanderveit** [comment]
Here a repository to reproduce the bug (with Gradle 6.7) https://github.com/alexanderveit/gradle-14972

```bash
gradle :clean :build --warning-mode all ; cat ./build/tmp/jar/MANIFEST.MF
```
shows the manifest with `Implementation-Version: task ':jar' property 'archiveVersion'`. Branches `with-get` and `with-version` contain the variants with `archiveVersion.get()` and `version` respectively.

**Comment by ljacomet** [comment]
Thanks a lot for the reproducer, it helped me figure out why I could not reproduce.

The issue is indeed present when you have a `from` in your manifest construction. In that case, the code path is different and we do not properly handle that kind of values.

**Comment by zerovian** [comment]
This seems to be an incomplete fix.  I have a build.gradle file kinda like below.  

But there are 2 weirdness.  1. the "implementation-version" property doesn't show up in the manifest.  It appears to be skipped entirely.

And second, 'archiveVersion' is still expanded improperly when used inside a groovy string.


gradle.properties 
-------------
archiveVersion = 12.6.0

build.gradle
--------


jar {
    manifest {
        attributes( 
            'Implementation-Version': archiveVersion,
            'Class-Path'            : "foo-${archiveVersion}.jar",
            )
            
    }
}

**Comment by ljacomet** [comment]
That's a different problem. There is a `Jar.archiveVersion` property, which is what gets referenced from your `manifest` block. Since it is not set, it skips the first assignment. And probably produces some `toString` in the second case.

If you want to wire your `archiveVersion` from Gradle properties, you have to access it properly. A `project.` prefix should do the trick.
