### ISSUE TITLE
Use up-to-date checks for creating the JAR manifest

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#14989]
For generating the manifest for the JAR task Gradle currently uses a `GeneratedSingletonFileTree`. This file tree generates the file for every build, and then Gradle needs to snapshot the file since it is an input to the JAR task.

We should not generate the manifest if it already exists and the configuration didn't change. So we want to use up-to-date checks for generating the manifest to improve performance for incremental builds.

---
cc: @gradle/execution

**Comment by wolfs** [comment]
Related to #11818.

**Comment by wolfs** [comment]
Adding a new task to create the manifest would add up-to-date checks, but also is hard with respect to backwards compatibility. We can easily add a manifest task for the JAR task added by Gradle plugins, but we can't add the task easily for arbitrary JAR tasks.

Another option would be to use the execution engine in `GeneratedSingletonFileTree` to create the manifest. For that to work, we would need to declare the inputs to the manifest work unit from the JAR task. We could also schedule the generation of the manifest as a separate node in the execution graph.

**Comment by lptr** [comment]
If we want to change how manifests are added, we might need to do it in 7.0.
