### ISSUE TITLE
The configuration order gradlew read is different from gradle

### ISSUE THREAD

**Issue by liaoya** [gradle/gradle#1499]
In https://docs.gradle.org/3.4/userguide/build_environment.html. The configuration is applied in following order (if an option is configured in multiple locations the last one wins):
- from gradle.properties in project build dir.
- from gradle.properties in gradle user home.
- from system properties, e.g. when -Dsome.property is set on the command line.

We're a team located different location and each location has its own proxy server. We put in systemProp.http.proxyHost and the corresponding setting in gradle.properties under the same folder as gradlew. Since gradle.properties will be put under source control system, it only contain the correct value for our master build system. 

The guys in other office have to modify proxy configuration gradle.properties in project build dir when we use new gradle version (gradlew need download the correct version). And we have set the correct proxy in gradle.properties in gradle user home (set gradle user home with -g option). Why these configuration does not work. 

I check the source code find root cause in org/gradle/wrapper/GradleWrapperMain.java.

        Properties systemProperties = System.getProperties();
        systemProperties.putAll(converter.convert(options, new HashMap<String, String>()));
        File gradleUserHome = gradleUserHome(options);
        addSystemProperties(gradleUserHome, rootDir);
        ....
    private static void addSystemProperties(File gradleHome, File rootDir) {
        System.getProperties().putAll(SystemPropertiesHandler.getSystemProperties(new File(gradleHome, "gradle.properties")));
        System.getProperties().putAll(SystemPropertiesHandler.getSystemProperties(new File(rootDir, "gradle.properties")));
    }

From the code, the order is:
- from system properties, e.g. when -Dsome.property is set on the command line.
- from gradle.properties in gradle user home.
- from gradle.properties in project build dir.

So that our http proxy configuration in project build dir always win, even I set gradle user home with -g option

The right code must be 

        File gradleUserHome = gradleUserHome(options);
        Properties properties = new Properties();
        addSystemProperties(properties, gradleUserHome, rootDir);
        properties.putAll(System.getProperties());
        properties.putAll(converter.convert(options, new HashMap<String, String>()));
        System.getProperties().putAll(properties);  // Copy all the configuration back to SystemProperties
        ....
    private static void addSystemProperties(Properties properties, File gradleHome, File rootDir) {
        properties.putAll(SystemPropertiesHandler.getSystemProperties(new File(rootDir, "gradle.properties")));
        properties.putAll(SystemPropertiesHandler.getSystemProperties(new File(gradleHome, "gradle.properties")));
    }

### Expected Behavior
The gradlew follow configuration in the the same order as gradle

### Current Behavior
The configuration in gradle.properties file of project always win

### Context
Gradlew read the configuration in different order compare to gradle make download impossible for somebody if the gradle.properties in project build dir has not been changed.

### Your Environment
N/A

**Comment by lacasseio** [comment]
Thanks for reporting this @liaoya. Is this 1) a regression from Gradle 3.3 or 2) you started using the wrapper in your company and found out about this difference in behavior?

**Comment by liaoya** [comment]
I have check the history of org/gradle/wrapper/GradleWrapperMain.java. I check the oldest version and it use the similar order. I think the oldest version must has such issue.

        private static void addSystemProperties(String[] args) {
            System.getProperties().putAll(SystemPropertiesHandler.getSystemProperties(args));
            System.getProperties().putAll(SystemPropertiesHandler.getSystemProperties(new File(gradleUserHome(), "gradle.properties")));
            System.getProperties().putAll(SystemPropertiesHandler.getSystemProperties(new File("gradle.properties")));
    }

I need some time to give a produce steps without code change, the key point is writing or using existing proxy (which must be used as second proxy for me).
