### ISSUE TITLE
Do not canonicalize paths for mutation info

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#15008]
Canonicalization of output paths did show up as a hotspot in profiles for incremental changes on large builds.

We should handle canonicalization consistently between the VFS and the rest of the code. Currently, we don't do canonicalization, so let's do the same for mutation info.

This should improve performance when there are many tasks/outputs to canonicalize.

---
cc: @gradle/execution

**Comment by wolfs** [comment]
The improvements in #14988 don't seem to make a difference for santa tracker, but they make a difference for the projects with many subprojects:

* `run assembleDebug | largeAndroidBuild | RealLifeAndroidBuildPerformanceTest` is 3-7% faster
* `assemble for non-abi change | largeJavaMultiProject | JavaNonABIChangePerformanceTest` is 2% faster
See https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestTestLinux_Trigger/39095393:id/performance-test-results.zip!/report/index.html

![image](https://user-images.githubusercontent.com/423186/97424435-02f9dd00-1911-11eb-9988-5f104779b6a2.png)

**Comment by wolfs** [comment]
Fixed via #14988.

**Comment by wolfs** [comment]
Looks like on Windows, we get even better improvements:
![image](https://user-images.githubusercontent.com/423186/97473586-74568180-194b-11eb-8e14-4f7672b4e699.png)

On macOS, we are similar to the Linux results: 
![image](https://user-images.githubusercontent.com/423186/97473709-95b76d80-194b-11eb-8053-d326803d4dac.png)

**Comment by lptr** [comment]
So cool!
