### ISSUE TITLE
Can't execute tests when using strictly to override version inherited from platform BOM

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#15009]
When inheriting versions from a BOM and then using `strictly` to specify a version to override from the BOM the application can compile (using `gradle testClasses` works) but when running tests it fails with:

```
> Could not resolve all files for configuration ':azure-function-app:testRuntimeClasspath'.
   > Could not resolve io.micronaut.azure:micronaut-azure-function:{strictly 2.0.3}.
     Required by:
         project :azure-function-app
      > Cannot find a version of 'io.micronaut.azure:micronaut-azure-function' that satisfies the version constraints:
           Dependency path 'co.nisto.refdata:azure-function-app:0.1' --> 'io.micronaut.azure:micronaut-azure-function:{strictly 2.0.3}'
           Constraint path 'co.nisto.refdata:azure-function-app:0.1' --> 'io.micronaut:micronaut-bom:2.1.2' --> 'io.micronaut.azure:micronaut-azure-function:2.0.2'
           Constraint path 'co.nisto.refdata:azure-function-app:0.1' --> 'io.micronaut.security:micronaut-security:2.1.1' --> 'io.micronaut:micronaut-bom:2.1.2' --> 'io.micronaut.azure:micronaut-azure-function:2.0.2'
           Constraint path 'co.nisto.refdata:azure-function-app:0.1' --> 'io.micronaut.azure:micronaut-azure-function-http:2.0.2' --> 'io.micronaut.azure:micronaut-azure-function:2.0.2'
```

If the build is changed to use `force = true` it works but this is deprecated.

### Expected Behavior

Using:

```
version {
    strictly("2.0.3")
}
```

And using a `platform` BOM (not `enforcedPlatform`) should override the dependency version in use as is the case with `force`

### Current Behavior

Build cannot execute with an exception

### Steps to Reproduce 

Unzip [bugtest.zip](https://github.com/gradle/gradle/files/5451195/bugtest.zip)

and run:

```
gradle azure-function-app:test
```

### Your Environment

```
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_262 (GraalVM Community 25.262-b10-jvmci-20.2-b03)
OS:           Mac OS X 10.15.7 x86_64
```

**Comment by melix** [comment]
I think I found the problem. There's a dependency from `io.micronaut.security:micronaut-security:2.1.1(runtimeElements)` to ` io.micronaut:micronaut-bom:2.0.1`. But this dependency is published as `enforcedPlatform`. Using `enforcedPlatform` for libraries is strongly discouraged as it leaks to consumers.

What happens now is that you have two platforms disagreeing and both saying that a dependency should be forced. I also think that this isn't the only module having this problem.

I could verify my theory by adding this rule:

```
   components.all {
        	allVariants {
        		withDependencies {
        		    it.each { dep ->
		    			if (dep.group == 'io.micronaut' && dep.name=='micronaut-bom') {
		    				dep.attributes {
		    					String cat = getAttribute(keySet().find { it.name == "org.gradle.category" })
		    					println cat
		    					if (cat == Category.ENFORCED_PLATFORM) {
		    						attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.REGULAR_PLATFORM))
		    					}
		    				}
		    			}
        			}
        		}
        	}
        }
    ```

Then your build passes.

**Comment by graemerocher** [comment]
I see, we will review our builds and make sure enforced platform is not used. Thanks.

**Comment by graemerocher** [comment]
@melix should the `java-library` plugin forbid the use of this? It seems like it will be really easy to publish bad metadata without some enforcement

**Comment by melix** [comment]
Absolutely, minimally there should be a warning.

**Comment by melix** [comment]
Closed by improving error messages and adding validation during publication in https://github.com/gradle/gradle/pull/15285
