### ISSUE TITLE
testCompileClasspath should include compileOnlyApi

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle#15017]
### Expected Behavior

`testCompileClasspath` should include the same dependencies as `apiElements`, plus `implementation` (as tests are likely to exercise internal components), and of course `testImplementation` and `testCompileOnly`.

### Current Behavior
`compileOnlyApi`, added in 6.7, is in `apiElements` but not in `testCompileClasspath`.

### Context
See discussion at https://github.com/gradle/gradle/issues/14299#issuecomment-712702820

**Comment by tbroyer** [comment]
Interestingly, add the `java-test-fixtures` plugin will *fix* this by/when reconfiguring the test classpaths.

Using this build script:
```kotlin
plugins {
  `java`
  // `java-test-fixtures`
}
dependencies {
  compileOnlyApi("com.google.errorprone:error_prone_annotations:2.4.0")
}
```

1. run `gradle dependencies --configuration testCompileClasspath`, it won't show the Error Prone annotations dependency
2. uncomment the `java-test-fixtures` line to apply the plugin
3. re-run the command from step 1, see how it know includes the Error Prone annotations

Should this be requalified as a bug then?

**Comment by jjohannes** [comment]
@tbroyer thanks again for reporting this. The situation with the `java-test-fixtures` is another good argument for doing this. The change will be in 6.8. Feel free to give it a try when rc-1 is out or with the next 6.8 nightly.
