### ISSUE TITLE
JavaDocs JFlag no longer seems to get set with Gradle 3.4

### ISSUE THREAD

**Issue by andykane** [gradle/gradle#1502]
We use the JavaDoc task to build our JavaDocs and we use our own doclets package to filter out what doesn't need to be added to the JavaDoc documentation.  From the JavaDoc task options closurer, we set the JFlag parameter to a system property which is then picked up within our doclets package.

After switching to Gradle 3.4, setting the system property with the JFlag parameter doesn't seem to get set as when I viewed the system property from within the doclets package, the system property was set to null.

We use the following JavaDoc task:

task apiDocs(type: Javadoc, dependsOn: configurations.midoclet) {
		destinationDir = new File(apiDocsDir, "build")
		failOnError = true
		options.showFromPublic()
		options.use()
		options.doclet = "com.sample.tools.doclets.standard.Doclet"
		options.docTitle = "${product_name} ${version} API"
		**options.JFlags = ["-Dpublic.api=com.sample.tools.VisibilityPublic"]**
		options.footer = "${product_name} ${version}"
		options.header = "${product_name} ${version}"
		options.windowTitle = "${product_name} ${version} API"
		
One of the doclets classes fetches the system parameter:

**String property = System.getProperty("public.api")**

In previous versions of Gradle it would have returned '**com.sample.tools.VisibilityPublic**', but after switching to Gradle 3.4 it returns **null**.

We use the JavaDoc task to build our JavaDocs and we use our own doclets package to filter out what doesn't need to be added to the JavaDoc documentation.  From the JavaDoc task options type, we set the JFlag parameter to a system property which is then picked up within our doclets package.

After switching to Gradle 3.4, setting the system property with the JFlag parameter doesn't seem to get set as when I viewed the system property from within the doclets package, the system property was set to null.

We use the following JavaDoc task:

task apiDocs(type: Javadoc) {
		destinationDir = new File(apiDocsDir, "build")
		failOnError = true
		options.showFromPublic()
		options.use()
		options.doclet = "com.sample.tools.doclets.standard.Doclet"	
		**options.JFlags = ["-Dpublic.api=com.sample.tools.VisibilityPublic"]**		
		
One of the doclets classes fetches the system parameter:

**String property = System.getProperty("public.api")**

In previous versions of Gradle it would have returned '**com.sample.tools.VisibilityPublic**', but after switching to Gradle 3.4 it returns **null**.

**Comment by big-guy** [comment]
Thanks @andykane 

I've confirmed that this is a problem. I don't see a workaround for now, but we'll get this fixed.

**Comment by bmuschko** [comment]
@big-guy Can you please add a milestone for the issue?

**Comment by blindpirate** [comment]
I believe this has been fixed and it should be closed in order to avoid misleading people.

**Comment by wolfs** [comment]
This has been fixed in Gradle 3.5.
