### ISSUE TITLE
Java 15 Support in Gradle 6.6.1 & 6.7

### ISSUE THREAD

**Issue by gagarwa** [gradle/gradle#15031]
I attempted to run gradle 6.7 & 6.6.1 (from direct download) in Windows 10 with Java 15.  Using gradle 6.7, it was not returning any output for any commands (event`gradle --version`).  Using gradle 6.6.1, it is working to show the version, but it is showing the following error when running `gradle init`:

**DaemonConnectionException: Could not dispatch a message to the daemon.**

### Expected Behavior
The latest version of gradle should support Java 15.

### Current Behavior
The latest version of gradle does not support Java 15 in Windows (as far as I can determine).  Both gradle 6.6.1 and 6.7 work however using Java 14.

### Steps to Reproduce 
1. Download Gradle 6.7
2. Download OpenJDK 15 OpenJ version
3. run `gradle --version` (Note no output)
4. Download Gradle 6.6.1
5. run `gradle --version` (this works)
6. run `gradle init` (this fails with exception)

### Your Environment
Windows 10 AMD64
OpenJDK 15 OpenJ
Gradle 6.6.1/6.7

_Apologies if this issue has already been reported._

**Comment by bjornvester** [comment]
I can confirm the problem. Just to give a few more details as the title might be slightly misleading:

Gradle 6.6.1 only [supports Java versions 8 to 14](https://docs.gradle.org/6.6.1/userguide/compatibility.html), so there is no unexpected issue here.

Gradle 6.7 [supports Java 15](https://docs.gradle.org/6.7/userguide/compatibility.html). It works with AdoptOpenJDK HotSpot 15 (`15.0.1_9` at this time), but there is an issue with the latest OpenJ9 variant (at least on Windows 10).

It works with the previous version `15_36_openj9-0.22.0`:
```
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          15 (Eclipse OpenJ9 openj9-0.22.0)
OS:           Windows 10 10.0 amd64
```

But not with version `15.0.1_9_openj9-0.23.0`. Both the "normal" and "large heap" variants are affected.

For whatever reason, the affected version actually appears to work in Gradle 6.6.1 even though Java 15 isn't supported here:
```
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          15.0.1 (Eclipse OpenJ9 openj9-0.23.0)
OS:           Windows 10 10.0 amd64
```

**Comment by damingerdai** [comment]
i meet a issue:
```
Could not target platform: 'Java SE 15' using tool chain: 'JDK 14 (14)'.
```
i use gradle version:
```
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          14.0.1 (Oracle Corporation 14.0.1+7)
OS:           Windows 10 10.0 amd64
```

**Comment by bmuskalla** [comment]
@bjornvester We currently don't plan to backport any support but generally expect Gradle to work on common JDK implementations. If we encounter such issues with J9 and newer Gradle versions, please feel free to create a new issue with steps to reproduce.

@damingerdai You were running Gradle with Java 14 but your build script tried to use a Java 15 compiler (e.g. using `sourceCompatibility`). Please have a look at the [toolchains support](https://docs.gradle.org/current/userguide/toolchains.html) how to ease such setups
