### ISSUE TITLE
Detached configuration with a dependency of same module root id is being resolved with the current version of the project.

### ISSUE THREAD

**Issue by torrescd** [gradle/gradle#15032]
We have a use case where we are referencing as a dependency an older version of the own project for a certain process of delta generation.

Detached configuration with a dependency of same module root id is being resolved with the current version of the project.

Some related changes were introduced with this [commit]  (https://github.com/gradle/gradle/commit/3191481144f11dff68e143448dd2337d0de054be) @bigdaz 

### Expected Behavior
Detached configuration should't be resolving with the root module as is detached.

### Current Behavior
Detached configuration sresolve with the root module.

### Context
We have a use case where we are referencing as a dependency an older version of the own project for a certain process of delta generation.

### Extra
Versions above the current one resolve well.

**Comment by ov7a** [comment]
Sorry for the late reply.

Given the changes in
* https://github.com/gradle/gradle/pull/29468
is it still relevant?
