### ISSUE TITLE
Multi JDK build fails for specific target JDK8 + alpn bootclasspath

### ISSUE THREAD

**Issue by yschimke** [gradle/gradle#15051]
### Expected Behavior

All variants of the build show pass. https://github.com/square/okhttp

Build uses JDK11 compiler (uses new JDK features), targets JDK8, runs tests with variable JDK and optional bootclasspath (alpn-boot)

### Current Behavior

JDK8 + alpn-boot in bootclasspath causes failures since adopting the Java Toolchain.

### Context

Nightly errors in CI.

### Steps to Reproduce 

Hard to reproduce out of context, so happy to just discuss ways to investigate or what the meaning of the error is.

### Your Environment

https://app.circleci.com/pipelines/github/square/okhttp/4059/workflows/4a0bcdf6-c50d-4074-b304-d6cafdd36492

**Comment by yschimke** [comment]
![image](https://user-images.githubusercontent.com/231923/97781472-8de20e00-1b83-11eb-9a89-d7de4589d907.png)

**Comment by yschimke** [comment]
```
* Where:
Build file '/home/circleci/project/build.gradle' line: 236

* What went wrong:
A problem occurred evaluating root project 'okhttp-parent'.
> Could not resolve all dependencies for configuration ':mockwebserver:testCompile'.
   > The new Java toolchain feature cannot be used at the project level in combination with source and/or target compatibility
```

**Comment by yschimke** [comment]
```
  if (platform == "jdk8alpn") {
    // Add alpn-boot on Java 8 so we can use HTTP/2 without a stable API.
    def alpnBootVersion = alpnBootVersion()
    if (alpnBootVersion != null) {
      dependencies {
        testCompile "org.mortbay.jetty.alpn:alpn-boot:$alpnBootVersion"
      }
      def alpnBootJar = configurations.testCompile.find { it.name.startsWith("alpn-boot-") } <-- fails here
      test {
        jvmArgs += "-Xbootclasspath/p:${alpnBootJar}"
      }
    }
  }
```

**Comment by yschimke** [comment]
Since we only add the dependency to trigger it to be downloaded, is there an alternate API to get the location of a JAR on demand to set the bootclasspath?

**Comment by jutoft** [comment]
I would personally create another configuration just for that artifact. Something like this:

    def jarPath = configurations.detachedConfiguration(dependencies.create(org.mortbay.jetty.alpn:alpn-boot:$alpnBootVersion)).singleFile

That will trigger the resolution of the jar at configuration time and give you a path to the file.

**Comment by yschimke** [comment]
@jutoft perfect, thanks!
