### ISSUE TITLE
Wrong maven dependency being used with artifact org.wildfly:wildfly-ejb-client-bom:10.1.0.Final

### ISSUE THREAD

**Issue by avelella** [gradle/gradle#1505]
### Expected Behavior
I expect the compile dependencies to be as shown on https://mvnrepository.com/artifact/org.wildfly/wildfly-ejb-client-bom/10.1.0.Final

For example: org.jboss.xnio:xnio-nio:3.4.0.Final instead of org.jboss.xnio:xnio-nio:3.3.1.Final

### Current Behavior
The dependencies should be, instead of:

org.jboss.xnio:xnio-api:3.4.0.Final instead of org.jboss.xnio:xnio-api:3.3.1.Final
org.jboss.xnio:xnio-nio:3.4.0.Final instead of org.jboss.xnio:xnio-nio:3.3.1.Final
org.jboss.remoting:jboss-remoting:4.0.21.Final instead of org.jboss.remoting:jboss-remoting:4.0.9.Final
org.jboss.marshalling:jboss-marshalling:1.4.11.Final org.jboss.marshalling:jboss-marshalling:14.10.Final
org.jboss.marshalling:jboss-marshalling-river:1.4.11.Final org.jboss.marshalling:jboss-marshalling-river:1.4.10.Final
org.jboss.logging:jboss-logging:3.3.0.Final.jar instead of org.jboss.logging:jboss-logging:3.2.1.Final.jar

### Steps to Reproduce (for bugs)
apply plugin: 'java'

repositories {
    maven {
		url "https://repository.jboss.org/nexus/content/repositories/releases/"
    }
}

dependencies {
    compile "org.wildfly:wildfly-ejb-client-bom:10.1.0.Final"
}

### Your Environment
Using Gradle 3.4
 * Build scan URL:

**Comment by oehme** [comment]
What you linked to is a BOM, which is not supposed to be used as a dependency, but in Maven's `<dependencyManagement>` block. There is a [Plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin#importing-a-maven-bom) that adds this functionality to Gradle.
