### ISSUE TITLE
Fix `toLowerCase` sensitivity regarding `Locale`

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#1506]
### Expected Behavior

Using a different `Locale` than English shouldn't cause unexpected behavior in Gradle.

### Current Behavior

Using Turkish locale can cause unexpected behavior in presence of dotless i character (upper->lower). [Various place](https://github.com/gradle/gradle/blob/38e5dc0f772daecca1d2681885d3d85414eb6826/subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java#L62) in the code base is vulnerable to this `Locale` sensitivity. Some places are fixed by [rolling out a contextual fix](https://github.com/gradle/gradle/blob/4ab85f7e62af6e41ff993849aa7ac361c4f2f9d2/subprojects/language-java/src/main/java/org/gradle/external/javadoc/internal/EnumJavadocOptionFileOption.java#L50-L50).

### Context

This started with PR https://github.com/gradle/gradle/pull/1408. @wolfs suggest we use Findbugs or Pmd to check for this kind of bug. @sterling suggest using a utility method to address this problem:

> I figured the utility method would be something like `GUtil.toLowerCase(String)` that would just call `toLowerCase(Locale.ENGLISH)` and `GUtil.toLowerCaseLocaleSensitive(String)` that would call `toLowerCase()`. The first case is what we would always try to use and the other would only be used in cases where we should be producing a locale dependent message/file/whatever (it doesn't have to be in `GUtil`)

A quick search in the codebase reveal lots of potential areas that could be affected.

**Comment by Siedlerchr** [comment]
It is advisable to use Locale.ROOT for case sensitive work:
https://garygregory.wordpress.com/2015/11/03/java-lowercase-conversion-turkey/

**Comment by big-guy** [comment]
This is still an issue.

`git grep toLowerCase\(\) | grep main | wc -l` shows over 100 instances where this could be a problem.

**Comment by Vampire** [comment]
Most prominent place:
![grafik](https://user-images.githubusercontent.com/325196/111011717-90a70800-839a-11eb-834e-370197a3b112.png)
:-D

**Comment by LouisCAD** [comment]
There's also toUpperCase to check 😄

**Comment by mlopatkin** [comment]
Another instances of this problem: #17361, #17383

**Comment by wolfs** [comment]
I suppose writing an architecture test with archunit should also be pretty straightforward. Spotbugs also finds these problems.

**Comment by Marcono1234** [comment]
Might also be worth to consider integrating https://github.com/policeman-tools/forbidden-apis in this context? It can detect these methods and also other methods which implicitly depend on the OS settings.

**Comment by ov7a** [comment]
Related:
* https://github.com/gradle/gradle/issues/17926
