### ISSUE TITLE
Build fails to acquire state lock with configuration on demand and included build

### ISSUE THREAD

**Issue by jdai8** [gradle/gradle#15068]
This error is similar to https://github.com/gradle/gradle/issues/14516, but is a different issue since it's not fixed in 6.7 or nightly versions.

### Expected Behavior
The build succeeds.

### Current Behavior

```
$ ./gradlew --configure-on-demand :main-project:compileJava
Configuration on demand is an incubating feature.
> Task :included:plugin:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':included:plugin:compileJava'.
> Could not resolve all files for configuration ':included:plugin:compileClasspath'.
   > Cannot acquire state lock for project ':included' as another thread (Thread[Daemon worker Thread 11,5,main]) currently holds the state lock for all projects.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 477ms
```

### Context
The build succeeds on 6.6, but fails on 6.7 and 6.8 nightly.

This is blocking me from upgrading from 6.2 to 6.7 and using the file system watching feature.

### Steps to Reproduce 
https://github.com/jdai8/gradle-included-plugin-repro

### Your Environment
macOS, java 8, Gradle 6.7

Build scan URL:
https://scans.gradle.com/s/jhbucwbtmm7pa

**Comment by jdai8** [comment]
Possible workarounds would be useful too. For example, the issue seems to be some kind of deadlock, which we might be able to avoid by removing/refactoring some dependencies.

**Comment by bigdaz** [comment]
@jdai8 To workaround this issue in your sample project, try adding this to the root `build.gradle` file:
```
plugins {
    id 'com.foo.bar' apply false
}
```
This won’t change the behaviour of the root build or the `main-project`, but will ensure that the plugin is loaded into the root classloader, which for some reason avoids the `Cannot acquire state lock` error.

**Comment by bigdaz** [comment]
Git bisect reveals that this commit introduced the breakage: https://github.com/gradle/gradle/commit/49299d15e53060d53ce0a847b2343ae62c1e791c

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/15244
