### ISSUE TITLE
Backport toolchain bug fixes

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#15060]
Candidates:
- https://github.com/gradle/gradle/issues/15042
- https://github.com/gradle/gradle/issues/14798
- https://github.com/gradle/gradle/issues/14761
- https://github.com/gradle/gradle/issues/14955
- https://github.com/gradle/gradle/issues/14825
- https://github.com/gradle/gradle/issues/15049

**Comment by bmuskalla** [comment]
@ljacomet WDYT?

**Comment by bmuskalla** [comment]
Backporting
* https://github.com/gradle/gradle/commit/305191e4ee31b75efe04f0610e4d2d22b0f082c7
* https://github.com/gradle/gradle/pull/14764
* https://github.com/gradle/gradle/commit/1419f90f048c93fc1dc275f860189f6b5b02436c

**Comment by ljacomet** [comment]
Merged to `release`
