### ISSUE TITLE
Do not produce stack trace about file system watching in INFO log with unsupported OS

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#15086]
We should only print the stacktrace at debug level, like we do with the other native loading error message.

---
cc: @gradle/execution

**Comment by wolfs** [comment]
> do not initialize file system watching on the client. We currently load it on the CLI as well.

I looked a little bit closer and it is currently hard to decide whether we need to initialize file system watching on the client: We initialize the native services before we decide to run the build in-process or out of process. So maybe we also need to split the initialization of the file watching from loading the native services. Or leave it as is and always load the file-system watching services.

**Comment by wolfs** [comment]
I created https://github.com/gradle/gradle/issues/15158 to not initialize file system watching on the client.

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/15157.
