### ISSUE TITLE
javadoc, options

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#15093]
javadoc and making it quiet is not really documented, would be great to add some information. e.g as it us used here:
https://github.com/EvidentSolutions/dalesbred/blob/master/build.gradle.kts

```
configure<JavaPluginExtension> {
  withJavadocJar()
  withSourcesJar()
}
```
```
tasks.withType<Javadoc> {
  val opts = options as StandardJavadocDocletOptions
  opts.addBooleanOption("Xdoclint:none", true)
}
```

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

Please indicate what part of the documentation you would see improved?
