### ISSUE TITLE
v6.8 (20201106230041) Can't use kotlin 1.4.20-RC

### ISSUE THREAD

**Issue by ylemoigne** [gradle/gradle#15090]
### Expected Behavior
By defining 
```
plugins {
    kotlin("jvm") version "XXX"
```

I can use the kotlin version of my choice (for the application).

### Current Behavior
I can't :
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.4.10}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path ':gmp-system-manager:unspecified' --> 'org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.4.20-RC' --> 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20-RC' --> 'org.jetbrains.kotlin:kotlin-stdlib:1.4.20-RC'
           Constraint path ':gmp-system-manager:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.4.10}' because of the following reason: Pinned to the embedded Kotlin
```

I don't see any note or warning in documentation saying that using gradle-dsl will lock application kotlin version to gradle embedded kotlin version.

### Context
Some of the project and internal dependency of the project has been migrated migrated to use kotlin-dsl ; thinking going forward "the gradle way" as the documentation say it provide better perf and typesafe editing.

This broke many app. In fact, every project which has migrated to kotlin 1.4.X has been broken.
The answer was to use the gradle nightly as kotlin 1.4 release is only 2 month old, gradle still not support it in a release.

Now, I wanted to do some testing with 1.4.20-RC, but the issue is back.

I think gradle teams is well placed to know how it's hard to get people to test RC and catch issue before release.
I think gradle should not force us to wait for release + gradle update including up-to-date embedded compiler to test our app with new release.
I think the kotlin version used to build/run and app should not be tied with the emmbeded kotlin version of gradle.

### Steps to Reproduce 
I'm unsure if it's because the project has a build-src with kotlin-dsl, or use a plugin with a such declaration.

### Your Environment
Used `distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-6.8-20201106230041+0000-bin.zip`

### Workaround
Revert all work that has been done on migrating gradle build to kotlin ? Is there another ?

**Comment by eskatos** [comment]
Hi @ylemoigne,

This strict constraint is only applied if you also apply the `kotlin-dsl` plugin which is meant to write Gradle plugins and is unnecessary if you are writing a regular kotlin application.

That being said, if you are writing a Gradle plugin, note that the embedded Kotlin has been upgraded to 1.4.20 in Gradle 6.8 after the nightly you are using. See #15238. RC1 should be out shortly.

**Comment by ylemoigne** [comment]
Hi @eskatos 

Thanks for your answer.

The application project contains a buildSrc which use `kotlin-dsl`.
Great to have a build where the version is updated. But I fear that the issue get back with another update.

So if I get it right :
If I use a gradle plugin written with kotlin, it does not lock the kotlin version for an app-project
If I use a `gradle-dsl` anywhere in an app-project (including buildSrc), the it lock the version for the app.

Then if it happen again, the workaround would be to extract buildSrc logic in a separate plugin ?

Am I correct ?

**Comment by eskatos** [comment]
The constraint should only apply on the project where the `kotlin-dsl` plugin is applied. In other words if you apply the `kotlin-dsl` plugin in your `buildSrc/build.gradle.kts` the constraint will only be present in that project and not in the other projects in your build.

**Comment by ylemoigne** [comment]
Ok thanks. So our build or one of our plugin must mess-up with classpaths as it is not the behavior I observe.

I close this issue as the main point was `kotlin version used to build/run and app should not be tied with the emmbeded kotlin version of gradle.` and by your explanation, I understand this is not tied "by default" ou "by gradle technical constraint" but by something on our side.

I neeed more testing to extract exactly what happen and frame correctly the issue.

**Comment by timorantalaiho** [comment]
@ylemoigne , did you happen to be able to resolve your issue?

I have a similar problem, and this thread is one of the few hits I have found about it :)

**Comment by ylemoigne** [comment]
@timorantalaiho Yes. One of our gradle plugin had a dependency to another project which was a kotlin project. After breaking the dependency, things got ok but maybe it was not the only step. In the mean time, we removed all kotlin code from `buildSrc` (returning to basic java ; the `buildSrc` seems to cause more issue on the intellij side than gradle, but I'm not sure).

**Comment by timorantalaiho** [comment]
Oh... thankyou! This might be a bit tricky to fix then, but let's try :sweat_smile:

**Comment by timorantalaiho** [comment]
Turns out we only have this problem when using `buildscript`; removing that solves the issue for us.
