### ISSUE TITLE
Deleting bean class doesn't trigger aggregating incremental processor reexecution

### ISSUE THREAD

**Issue by max-kammerer** [gradle/gradle#15097]
Deleting bean class doesn't trigger aggregating incremental processor reexecution

### Expected Behavior
Aggregating processor should be reexecuted during annotated class removal

### Current Behavior
All `compile` tasks are up-to-date, nothing is changed including result of aggregating processors

### Context
Used to work in Gradle 6.6, doesn't work since 6.7

### Steps to Reproduce 
1. Build attached project: `./gradlew --no-daemon clean  build --info`
2. Check content of  generated resource: ` cat build/classes/java/main/META-INF/services/io.micronaut.inject.BeanDefinitionReference`
3. Delete `AutoStartingBean2.java` file
4. build: `./gradlew --no-daemon  build --info`
5. Check content of  generated resource again: `cat build/classes/java/main/META-INF/services/io.micronaut.inject.BeanDefinitionReference` . It's same

### Your Environment
Gradle 6.7, Ubuntu 20.04
[micronaut-playground.tar.gz](https://github.com/gradle/gradle/files/5509018/micronaut-playground.tar.gz)

**Comment by max-kammerer** [comment]
Same with Micronaut 2.1.3

**Comment by melix** [comment]
Just a heads-up: I'm still trying to understand what's going on. On simpler test cases this just works fine so there must be something special happening with the chain of APs from Micronaut.

**Comment by melix** [comment]
@graemerocher may I request your assistance on this? It seems to be related to the chain of APs in Micronaut. I can see the following when compiling:
- io.micronaut.annotation.processing.TypeElementVisitorProcessor
- io.micronaut.annotation.processing.AggregatingTypeElementVisitorProcessor
- io.micronaut.annotation.processing.PackageConfigurationInjectProcessor
- io.micronaut.annotation.processing.BeanDefinitionInjectProcessor
- io.micronaut.annotation.processing.ServiceDescriptionProcessor

I need to understand what kind (isolating, aggregating) each of them is, and what they produce. If I just keep the last two in the pipeline, then Gradle behaves correctly. I also have written tests showing that if I have a class annotated by `@Foo` processed by an isolating processor (1 by 1 mapping) which generates a class annotated with `@Bar`, processed by an aggregating processor (n to 1) which generates a resource, then deleting also works fine.

**Comment by melix** [comment]
Thanks for the input @graemerocher. I've managed to create a reproducer and it's indeed because the isolating processor creates a `.class` file, _not_ a source file. This interferes with the fix for #13767 which actually made sure we only reprocess things... which have a real source :/

**Comment by graemerocher** [comment]
Well if it is a choice between the two it is better this issue than the other one 😄
