### ISSUE TITLE
NPE with Cucumber and JUnit Categories

### ISSUE THREAD

**Issue by andyrbell** [gradle/gradle#1510]
NullPointerException being thrown if [JUnit Category](https://github.com/junit-team/junit4/wiki/Categories) restrictions are used in a project containing Cucumber tests

### Expected Behavior
Test completes without error

### Current Behavior
The build fails with an InitializationError and the following stacktrace is printed to the test report standard out:

```
java.lang.NullPointerException
	at org.junit.runner.Description.createSuiteDescription(Description.java:124)
	at org.gradle.api.internal.tasks.testing.junit.CategoryFilter.shouldRun(CategoryFilter.java:47)
	at org.junit.runners.ParentRunner.shouldRun(ParentRunner.java:434)
	...
```

### Context
Need to exclude certain integration tests from the main build since they call external systems which may be unavailable at the time of the build, resulting in failure. Those tests are essentially just checking whether the external system's API has any breaking changes. They still need to run periodically, just not on commit. JUnit Categories seem ideal for this purpose.

### Steps to Reproduce (for bugs)
[Failing test case](https://github.com/andyrbell/junitCategoriesCucumberBug)

### Your Environment
Gradle 3.4.1

**Comment by bmuschko** [comment]
Thanks for reporting. Can you elaborate why this issue is specific to the use of Cucumber? Is there a way to reproduce the issue without Cucumber?

**Comment by andyrbell** [comment]
For the following Cucumber feature
```
Feature: Foobar
  Scenario: Foo and Bar
    Given foo
    When bar
    Then foobar
```

- Cucumber will generate 3 JUnit Tests (one for each step definition). 
- When dynamically generating those tests, the Cucumber JUnit Runner (`FeatureRunner`) does not set the Test Class on the test `Description` as there isn't one.
- The Gradle `CategoryFilter` has deviated from the vanilla JUnit implementation and doesn't handle this null case
- Running JUnit directly, without Gradle, works as expected.

**Comment by bmuschko** [comment]
Thanks. I guess what I am asking is the following: Can the issue be reproduced with plain JUnit without the use of Cucumber?

**Comment by bmuschko** [comment]
The example you give here is likely a Cucumber-specific runner: `@RunWith(Cucumber.class)`. I was wondering if you can reproduce the issue without any Cucumber dependencies. That would make the testing setup for a fix much easier and we don't have to depend on an external dependency.

**Comment by andyrbell** [comment]
There is already an existing dependency on Cucumber in the Gradle integration tests, if that's the problem..?

I added an integration test to [my fix](https://github.com/gradle/gradle/pull/1511) and was careful to use the same [version of Cucumber](https://github.com/gradle/gradle/pull/1511/files#diff-5f0d43be86cb54e0341985c9d42adc6aR23) used in [existing integration tests](https://github.com/gradle/gradle/blob/master/subprojects/testing-jvm/src/integTest/resources/org/gradle/testing/cucumberjvm/CucumberJVMReportIntegrationTest/testReportingSupportsCucumberStepsWithSlashes/build.gradle#L25).

**Comment by bmuschko** [comment]
> There is already an existing dependency on Cucumber in the Gradle integration tests, if that's the problem..?

Yes, that's what I am mostly concerned about. Even if there's an existing dependency Cucumber we probably should have tried earlier to avoid the dependency.

> I added an integration test to my fix and was careful to use the same version of Cucumber used in existing integration tests.

Do you think we could emulate the issue without Cucumber in the fix?

**Comment by andyrbell** [comment]
Good point. I've managed to replicate the issue without Cucumber and have updated the PR.

**Comment by ovstetun** [comment]
Just as I was ready to start implementing this change (I work on a project with Kristian Rosenvold who posted in the original forum post), I found this in-work issue.
We will be glad to help if you need anything, and will gladly test on our project!

**Comment by andyrbell** [comment]
Hi @bmuschko, have you had chance to look at the updated PR? Is there anything else you need me to do to get this over the line?

**Comment by bmuschko** [comment]
@andyrbell Sorry for the delay. I'll have a look sometime this week.

**Comment by bmuschko** [comment]
@andyrbell I added a couple of comment to the review. Can you please touch up the PR so we can merge?

**Comment by andyrbell** [comment]
@bmuschko thanks for the feedback. I've addressed the comments and updated the PR.

**Comment by andyrbell** [comment]
@bmuschko anything else you want me to do on this..?

**Comment by bmuschko** [comment]
@andyrbell Sorry again for the delay. We'll certainly pull in this change for 4.0. I am going to merge soon.

**Comment by andyrbell** [comment]
@bmuschko awesome, thanks! Bit of a shame I missed 3.5 as I was hoping to start using Categories fairly soon in my project, which is already using Cucumber. I guess it won't be long before 4.0 comes along though and, in the meantime, I can just run a patched version. Thanks again!
