### ISSUE TITLE
Gradle very slow while executing compileTestJava

### ISSUE THREAD

**Issue by oneiros-de** [gradle/gradle#15112]
Gradle build, which was started this way:

`./gradlew --no-daemon --exclude-task=check --exclude-task=compileJava --debug --console=plain :compileTestJava`

takes 33:32 minutes for compileTestJava task. This is probably quite similar to #14531

### Expected Behavior

Gradle finishes the build.

### Current Behavior

Gradle seemlingly hangs; compilation takes 33:32 minutes on a 4 ore Leonovo T550.

### Context

See attachments for build output and thread dumps of Gradle processes. I could not tell which GradleDeamon started the hanging build, so I attached thread dumps of both.
[build.txt](https://github.com/gradle/gradle/files/5518435/build.txt)
[stacktrace.GradleWrapperMain.txt](https://github.com/gradle/gradle/files/5518446/stacktrace.GradleWrapperMain.txt)
[stacktrace.GradleDaemon.8793.txt](https://github.com/gradle/gradle/files/5518448/stacktrace.GradleDaemon.8793.txt)
[stacktrace.GradleDaemon.5877.txt](https://github.com/gradle/gradle/files/5518451/stacktrace.GradleDaemon.5877.txt)

### Steps to Reproduce 

This happens every time. 

### Your Environment

A build scan of a `compileJava`run is at https://scans.gradle.com/s/osy2bv62vp4jo

System is Ubuntu 20.4 with 
```
> java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode)
```

**Comment by hamidahmetovic94** [comment]
same for me
im using Gradle 7.0

compileJava is really fast (10sec) while compileTestJava takes 8min+ 
im using Mac BigSur

**Comment by heitorpaceli** [comment]
This issue is reproducible for me. I have only one class and it is stuck in compileJava task. It haven't finished yet, so I'm not sure if it is doing something.

**Comment by oneiros-de** [comment]
Still present with 7.2:

```
> ./gradlew --version

------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OS:           Linux 5.4.0-84-generic amd64

```

**Comment by big-guy** [comment]
It's possible this is due to heap exhaustion in the compiler daemon.  Without more information or a reproducer, this will be hard to check.
