### ISSUE TITLE
Automatically group worker javaexec output in the terminal

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#15117]
When using `WorkerExecutor` with `ExecOperations.javaexec` ([example](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:buildSrc/src/main/kotlin/androidx/build/metalava/MetalavaRunner.kt;l=60)) that calls some CLI tool can result in intermingled stdout and stderr output, which is a different behavior from concurrent tasks.

This FR is to automatically group worker javaexec output in the terminal.

### Expected Behavior
Gradle should buffer for stdout and stderr and then print it out once javaexec is complete, to make sure that output is not mixed with other concurrently running workers.

### Current Behavior
Depending on timing, the outputs get mixed making it hard for developers to read the output.

### Context
We have considered setting a custom `OutputStream`s on the `ExecSpec` and then passing it to `Logger`, however there is no clean way to do streaming to logger.

**Comment by mathjeff** [comment]
Some more context: having this spliced output also makes it more difficult for automated systems to parse the output, determine what's unexpected and worth showing to the user (in the case of a build failure) or flagging as unrecognized (in the case of a build success), https://github.com/gradle/gradle/issues/13090

**Comment by donat** [comment]
Implementing some tricky buffering would be useful for this use case but it would be confusing for others. Most users actually expect the output to appear instantly on the console.

Also, there's an easy workaround for the problem. You need to configure the `JavaExec` tasks to redirect the output to a file, then print them at the end of execution.

```groovy
def printJavaExecOutput = tasks.register('printJavaExecOutput') {
    doLast {
        for (def output : project.layout.buildDir.dir('out').get().asFile.listFiles()) {
            println output.name
            println output.text
            println '--'
        }
    }
}

tasks.withType(JavaExec).configureEach {
    def outDir = project.layout.buildDir.dir('out').get().asFile
    if (!outDir.exists()) {
        outDir.mkdir()
    }
    def outFile = new File(outDir, "${it.name}.out")
    outFile.text = ""
    standardOutput = new FileOutputStream(outFile)

   finalizedBy printJavaExecOutput
}
```
