### ISSUE TITLE
Hyperlink issue on most sample links in docs

### ISSUE THREAD

**Issue by tasomaniac** [gradle/gradle#15127]
I noticed a common behavior with multiple **sample links** in this document: https://docs.gradle.org/current/userguide/kotlin_dsl.html

`groovy-interop` sample and `maven-plugin` samples have the issue as an example. A `/` is missing as a separator and Github gives 404.

### Expected Behavior

Link should go to 
https://github.com/gradle/kotlin-dsl-samples/tree/master/samples/groovy-interop

### Current Behavior

Link goes to
https://github.com/gradle/kotlin-dsl-samples/tree/master/samplesgroovy-interop

**Comment by bmuskalla** [comment]
These links do not exist anymore in the document.
