### ISSUE TITLE
6.7: ConcurrentModificationException while resolving configurations across projects

### ISSUE THREAD

**Issue by davidburstromspotify** [gradle/gradle#15120]
I've set up a configuration in the root project which gets modified with a `withDependencies` closure. This configuration is resolved from tasks that are registered on all projects. When parallel execution is turned on, this sometimes lead to a ConcurrentModificationException (or an NPE) in the `withDependencies` closure, as multiple worker threads are modifying the configuration.

The key to the problem is that a resolving task is defined on the root project. If the tasks are only registered on the subprojects, everything works as expected.

### Expected Behavior

Resolving the configuration in parallel should be safe even when the root project is involved.

### Context

I came across this as I want to specify a version of a dependency only once (in the root project) and let all projects use that configuration to execute a specific set of tasks with identical classpaths.

### Steps to Reproduce 

A self-contained example project is attached. See its README.md how to provoke the issue.
[gradle-issue-configuration-cme.zip](https://github.com/gradle/gradle/files/5522586/gradle-issue-configuration-cme.zip)

### Your Environment
Gradle 6.7
macOS 10.15.7

**Comment by davidburstromspotify** [comment]
A sensible workaround, suggested by @melix, is to add an AtomicBoolean in the `withDependencies` callback to ensure only one of the threads gets to execute the modification.

**Comment by melix** [comment]
I think the problem shows up because you're not declaring the configuration as an input. If I change the code to:

```
    tasks.register('provoke') {
        inputs.files(configurations.consumer)
        doLast {
            configurations.consumer.resolve()
        }
    }
```

Then the error goes away. We're going to look into protecting undeclared access too but you should declare your inputs.

**Comment by davidburstromspotify** [comment]
> I think the problem shows up because you're not declaring the configuration as an input.

You're absolutely right, in the production code there was a missing input declaration. That was subtle. Good to see that there are two solutions to the same problem.

**Comment by davidburstromspotify** [comment]
As for the AtomicBoolean workaround, it also requires a CountDownLatch so that any other thread that doesn't do the initialization still waits for the end result of the modification. Otherwise the configurations will miss dependencies depending on race conditions.

**Comment by melix** [comment]
You actually need the `lock` I initially added otherwise something can think that the initialization was done but it's still in progress.

**Comment by davidburstromspotify** [comment]
Agreed, either the lock or latch, or both if you want to play on difficulty=hard.
