### ISSUE TITLE
Dependency graph cannot be loaded from disk

### ISSUE THREAD

**Issue by anoopgarlapati** [gradle/gradle#15122]
We receive dependency resolution failures when building our project in Jenkins CI in which two of our tasks implement JacocoCoverageVerification and JacocoReport. The following is the stack trace from one such instance:
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':codeCoverageVerification'.
> Could not resolve all dependencies for configuration ':detachedConfiguration235'.
   > Problems reading data from Binary store in /tmp/gradle862192282417286221.bin offset 254688 exists? false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':codeCoverageReport'.
> Could not resolve all dependencies for configuration ':detachedConfiguration236'.
   > Problems reading data from Binary store in /tmp/gradle862192282417286221.bin offset 256164 exists? false

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

### Expected Behavior

Build should succeed with Jacoco report successfully published.
### Current Behavior

Build fails with dependency resolution error.
### Context

We build our project on Jenkins CI and we notice this intermittent failure from time to time. The project contains 4 test tasks from which we aggregate the results to generate Jacoco report and code coverage verification. This is impacting our team's developer productivity as our integration test suite takes ~90 mins and at the end of 90 mins the build fails due to this error in code coverage verification. This causes us to re-run the CI job.
### Steps to Reproduce 

No reproducer available yet.
### Your Environment

Gradle version: 6.7
Environment: Jenkins CI running with no-daemon flag

**Comment by melix** [comment]
A couple questions:
- would it be possible that the disk is full when this error happens?
- if not, because the build looks very slow, could there be any automated cleanup task on CI which deletes files from `/tmp`?

I am asking because of the `exists? false` which seems to indicate that the file that Gradle generates to offload to disk dependency resolution graphs is missing.

**Comment by anoopgarlapati** [comment]
@melix Thanks for the pointers! 
I checked with our CI team and they do run a cron job to removes files which are not accessed in the last 1 hour in `/tmp` directory. 
We will work on optimizing our tests and entire build to run within an hour. 
Closing the ticket as it is an issue in our CI workflow.
