### ISSUE TITLE
Git repository at https://gitee.com/xing16/module_test.git did not contain a project publishing the specified dependency.

### ISSUE THREAD

**Issue by xing16** [gradle/gradle#15129]
setting.gradle:
`

include ':app'
rootProject.name = "ApplicationModule"
sourceControl {
    gitRepository("https://gitee.com/xing16/module_test.git") {
        producesModule("com.fc.moduletest:home")
        rootDir = "home"
    }
}

`

build.gradle
`
 api 'com.fc.moduletest:home:v2.2'
`

build result: 
`
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Git repository at https://gitee.com/xing16/module_test.git did not contain a project publishing the specified dependency.
     Required by:
         project :app

`

**Comment by jjohannes** [comment]
@xing16 Sorry for the late reply, but can you please provide a full reproducer of the problem and open a new issue with that if it persists?

The error message indicates that the _source dependency_ does not contain the module you are looking for - `com.fc.moduletest:home:v2.2`. I.e. Gradle does not know how to build that module from that Git repository. You should check the Gradle build in the Git repo for what it produces. That is, the name of the project should be `home`, and the group should be `com.fc.moduletest`.
