### ISSUE TITLE
DirectoryProperty.files() resolves incorrectly

### ISSUE THREAD

**Issue by chao2zhang** [gradle/gradle#15128]
### Expected Behavior
```
layout.buildDirectory.files('a.txt', 'b.txt').each { println it.absolutePath }
// /Users/cazhang/GradleBuildDirectoryResolution/build/a.txt
// /Users/cazhang/GradleBuildDirectoryResolution/build/b.txt
println layout.buildDirectory.file('a.txt').get().asFile
// /Users/cazhang/GradleBuildDirectoryResolution/build/a.txt
println layout.buildDirectory.file('b.txt').get().asFile
// /Users/cazhang/GradleBuildDirectoryResolution/build/b.txt
```

### Current Behavior
```
layout.buildDirectory.files('a.txt', 'b.txt').each { println it.absolutePath }
// /Users/cazhang/GradleBuildDirectoryResolution/a.txt
// /Users/cazhang/GradleBuildDirectoryResolution/b.txt
println layout.buildDirectory.file('a.txt').get().asFile
// /Users/cazhang/GradleBuildDirectoryResolution/build/a.txt
println layout.buildDirectory.file('b.txt').get().asFile
// /Users/cazhang/GradleBuildDirectoryResolution/build/b.txt
```

### Context
`DirectoryProperty.file()` resolved to the correct file path. However, `DirectoryProperty.files()` does not resolve the array of files into the correct file path (See how /build is truncated).

### Steps to Reproduce 
This is very straightforward in a vanilla gradle project. I have attached the sample repo as below:
https://github.com/chao2zhang/GradleBuildDirectoryResolution/blob/main/build.gradle

### Your Environment
Build scan URL: https://scans.gradle.com/s/udwi3hajxj3zm/

**Comment by wolfs** [comment]
This has been fixed and will be in Gradle 7.5.
