### ISSUE TITLE
When app is built using gradle plugin >= v3.6.0 and gradle version >= v5.6.4, apk file does not package META_INF folder which contains MANIFEST.MF file

### ISSUE THREAD

**Issue by hyperion-mk2** [gradle/gradle#15133]
https://issuetracker.google.com/issues/168013083

when run from Android Studio (green arrow) or run with command ./gradlew -Pandroid.injected.build.api=28 assembleDebug

Gradle version: >= v5.6.4

Android Plugin Version: gradle plugin >= v3.6.0

Module Compile Sdk Version: 29

Module Build Tools Version: 29

Android SDK Tools version: 30

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This seems to be an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Unless you identify something specific to core Gradle, this will not be followed upon.
