### ISSUE TITLE
Android - package info versionName is null after update to gradle 4.1.0

### ISSUE THREAD

**Issue by salim-lachdhaf** [gradle/gradle#15140]
I have a multi modular app and for some reason and after updating to gradle 4.1.0 this function not working any more :
```
public static String getApplicationVersionName(Context pContext) {

        String version = "0";

        try {
            PackageInfo pInfo = pContext.getPackageManager().getPackageInfo(pContext.getPackageName(), PackageManager.GET_META_DATA);
            version = pInfo.versionName;
        } catch (NameNotFoundException e) {
            printStackTrace(e);
        }
        return version;
    }
```

i tried this solution [here ](https://stackoverflow.com/questions/64333763/buildconfig-version-code-is-missing-after-update-to-com-android-tools-buildgra)but it works only BuildConfig generated class

```
buildConfigField 'int', 'VERSION_CODE', "${rootProject.appVersionCode}"
buildConfigField 'String', 'VERSION_NAME', "\"${rootProject.appVersionName}\""
```

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Feel free to create a new defect with more information that is actionable.
