### ISSUE TITLE
annotationProcessor dependency can't have an aar as a transitive dep

### ISSUE THREAD

**Issue by ronshapiro** [gradle/gradle#1515]
`com.google.dagger:dagger-android-processor:2.10-rc2` is a `jar` that has a dependency on `com.google.dagger:dagger-android-support:2.10-rc2`, an `aar`. When gradle attempts to resolve the deps for the processor, it sees `<type>aar</type>` and silently ignores it. Is that expected behavior? It seems that it should at least warn, if not error, or just support it out of the box. The processor only needs the `classes.jar` of the `aar` and nothing else.

Please let me know if this is better suited as a bug on the Android plugin and I'll file there instead.

This is in reference to a bug initially filed at https://github.com/google/dagger/issues/608

/cc @JakeWharton

**Comment by oehme** [comment]
This is indeed better suited for the Android bug tracker :)

**Comment by ronshapiro** [comment]
Sounds good, moved there: https://code.google.com/p/android/issues/detail?id=237622&thanks=237622&ts=1488815420
