### ISSUE TITLE
Provide 'test executor number' in env var or system property for parallel testing

### ISSUE THREAD

**Issue by flozano** [gradle/gradle#15164]
It would be very useful for logging and issue identifying purposes to have this info available in an env var or system property. 

I have a parallel build in which a few tests are wrongly interacting with each other and having this info would be super handy - for example, to be able to log different 'test executors' to different files.

### Expected Behavior
For a given executor (`'Gradle Test Executor 11'`), the 'test executor number' would be available in an env var (`GRADLE_TEST_EXECUTOR_NUMBER=11`) or in a system property of the forked JVM (`-Dgradle.test.executor.number=11`

### Current Behavior
This info is not easily accessible right now.

### Context
Tests should be independent and forking should not affect them, but sometimes that's not the case - and in order to identify those interactions and fix them, it'd be very helpful to have this info.

**Comment by bmuskalla** [comment]
@flozano When running tests with multiple workers, you should have access to the `org.gradle.test.worker` system property.

```
Your tests can distinguish between parallel test processes by using the value of the org.gradle.test.worker property, which is unique for each process. You can use this for anything you want, but it’s particularly useful for filenames and other resource identifiers to prevent the kind of conflict we just mentioned
```
See https://docs.gradle.org/current/userguide/java_testing.html#sec:test_execution for more details. Would that cover your usecase?

**Comment by flozano** [comment]
Yes, this works well for my use-case. I see it's a long value, that fully works and covers my case. I don't know how I didn't see it 🤦

**Comment by bmuskalla** [comment]
Don't worry, I didn't know about its existence before today either ;) (and shoutout to @marcphilipp for the hint)
