### ISSUE TITLE
Eclipse Project Launcher use Gradle dependency from first library project

### ISSUE THREAD

**Issue by Horcrux7** [gradle/gradle#1516]
BuildShip 2.0.1 and Gradle 3.4

If we add a library project for debugging to an eclipse project then the launcher resolve the project and external dependencies form the library project and not from the main project. The result are ClassNotFoundExceptions from libraries which are only in the main project.

This is also good visible in the classpath order of the launcher. The project and external dependencies follow the first library project.

Our library project look like:

    <?xml version="1.0" encoding="UTF-8"?>
    <classpath>
    	<classpathentry kind="src" path="src"/>
    	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
    	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
    	<classpathentry kind="output" path="bin"/>
    </classpath>

Our main project look like:
	
    <?xml version="1.0" encoding="UTF-8"?>
    <classpath>
    	<classpathentry combineaccessrules="false" kind="src" path="/LibraryToDebug"/>
    	<classpathentry kind="src" path="src"/>
    	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
    	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
    	<classpathentry kind="output" path="bin"/>
    </classpath>
	
The library classpathentry must before the gradleclasspathcontainer else the library classes come from gradle and not from eclipse project and we can't debug it.

The expected behavior is that the project launcher use ever the dependencies from the current (main) project and not from the first project with Gradle dependencies. The Ivy plugin has solved this with adding then dependencies from all projects in the classpath. But I think this is not needed.

**Comment by oehme** [comment]
Can you please provide a reproducible example project?

Also you might want to use a [composite build](https://docs.gradle.org/current/userguide/composite_builds.html) instead of manually adjusting Eclipse .classpath files.

**Comment by Horcrux7** [comment]
The composite build based on settings in the gradle.settings will also have an effect to the build system.

Settings in the .project file and the *.lauch files are development only. A team can share this setting without any effect to the build system.

It is very important to have in the repository settings for 
* the build system
* shared for build and dev systems
* dev systems only.

I will create a eclipse workspace to demonstrate it and upload it.

**Comment by oehme** [comment]
> The composite build based on settings in the gradle.settings will also have an effect to the build system.

That's the point, it properly tells Gradle to substitute dependencies, so you don't have to do classpath ordering stunts in Eclipse :)

You can do composite builds with an if-statement, so they don't affect your CI environment. We also plan to add some UI in Buildship in the future so you can do ad-hoc composites without changing a settings.gradle file.

**Comment by Horcrux7** [comment]
> You can do composite builds with an if-statement, so they don't affect your CI environment.
How can I do this if condition?

I have attached a sample workspace. Its contains:
* a library project "JLessC" with extra debug output
* its contain 2 main projects. The only difference is the order of classpathentry in the file .classpath and the main class was renamed to differentiate. Both haven a jcenter reference to 2 libraries.

The one main project does not show the extra debug output from the library (expected). The other show the ClassNotFoundException (the bug). The compiler can resolve the class. The launcher does not.

[EclipseLauncherSample.zip](https://github.com/gradle/gradle/files/823694/EclipseLauncherSample.zip)

PS: Sounds also like a posible hack to differ between compile dependencies and runtime dependencies.

**Comment by oehme** [comment]
Thank you for the example. Turns out that JDT de-duplicates classpath containers when you don't explicitly tell it not to. I've created a [PR for buildship](https://github.com/eclipse/buildship/pull/424/files) to fix that.

**Comment by donat** [comment]
FYI the [Buildship PR](https://github.com/eclipse/buildship/pull/424) has been merged.
