### ISSUE TITLE
vfs.watch doesn't update with classes

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15173]
maybe it doesn't update period, I'm not certain

```properties
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.vfs.verbose=true
```

```
Watched directory hierarchies: [/Users/calebcushing/IdeaProjects/ppm/api]
Received 7 file system events during the current build while watching 1 hierarchies
```

https://www.jetbrains.com/help/idea/gradle-settings.html

when I update the source code in idea it doesn't update the class files on disk, I can see it in the timestamps, if it did spring boot devtools would reload the context.

```
> yarn gradle --version                                                                                                                                                           # ppm -> 1-setup |• — +

------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.8 (AdoptOpenJDK 11.0.8+10)
OS:           Mac OS X 10.16 x86_64
```

**Comment by lptr** [comment]
IIUC, you expected Gradle to pick up your changes and rebuild them. That is what continuous mode (`--continuous` or `-t`) does. See https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continuous_build.

File system watching is a different feature that aims to speed things up by using file system events. See https://blog.gradle.org/introducing-file-system-watching
