### ISSUE TITLE
Document lack of signing capability in maven-publish plugin

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#1517]
`maven-publish` plugin isn't suitable for publishing to Maven Central due to the lack of signing capabilities. We should add this capability but in the meantime let's at least document this limitation in the user manual.

**Comment by ilya-g** [comment]
Out of curiosity, is adding a sentence to the documentation page requires waiting for the next major release?

**Comment by pioterj** [comment]
This is a very low risk change. @bmuschko Can we push it to the release branch so it's included in 3.5 RC2?

**Comment by bmuschko** [comment]
@ilya-g As you can see in the PR the change includes more changes than just adding a single sentence. We are auto-testing code snippets included in the documentation. The same is true for Javadocs. For that reason it has to run through portions of the CI pipeline first. Either way once merge you are able to see the change to documentation in the nightly. Usually, we do not try to introduce additional changes (except for bug fixes) so late in the release process as it might have other side effects.

@pioterj It's relatively low risk. I am still waiting for a review. I guess we could merge into release.
