### ISSUE TITLE
Regression with JUnit Platform it is not possible to select inherited tests via command line

### ISSUE THREAD

**Issue by leonard84** [gradle/gradle#15185]
This issue is came up in https://github.com/spockframework/spock/issues/1235, according to @marcphilipp in https://github.com/junit-team/junit5/issues/2476 the issue is in gradle itself.

---

### Expected Behavior
With the old JUnit, i.e. non `useJUnitPlatform()`, it is possible to run:

`./gradlew test --tests *ChildSpec.parent -Pspock1`

to execute an inherited test.

(See  https://github.com/spockframework/spock/issues/1235 for a demo project)

### Current Behavior

With the JUnitPlatform and Spock 2 the same command does not execute a test.

`./gradlew test --tests *ChildSpec.parent`

### Context

My guess is that it is probably that line here
`return matcher.matchesTest(methodSource.getClassName(), methodSource.getMethodName());`

https://github.com/gradle/gradle/blob/46d60a4c6d72ce8880882e76a73d8db25d8aed9a/subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java#L179

Comment by @marcphilipp 
> The `MethodSource` is supposed to contain the declaring class, hence "source", and was introduced to allow IDE navigation. The filtering code could check for the parent descriptor's `ClassSource` in this case instead of using the `MethodSource`'s class name.

>The filtering code that probably needs to be changed is in Gradle, not JUnit Platform. Would you mind opening a Gradle issue instead?

### Steps to Reproduce 
See  https://github.com/spockframework/spock/issues/1235 for a demo project

**Comment by marcphilipp** [comment]
Please bear in mind that my analysis (if you can even call it that) above is preliminary. Should be easy to reproduce in a functional test, though.
