### ISSUE TITLE
java platform with artifact() metadata source basing itself only on jar artifacts to find versions

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#15188]
Not sure this is intended or not. I'm trying to define all dependencies in a platform, but I have an issue with a flat files remote repository. I have defined it as an ivy repository, with a pattern of `[module].[revision].[ext]`. There are no descriptor files on the repository, so the `artifact()` metadata descriptor has been enabled. This files repository contains zip and rpm files, and in my case I would like to pick up the latest version of a rpm file to include into the build.
I have defined a platform module with constraints and rich version definitions for all dependencies. I'm trying to add this dependency there as well, asking for the latest version by setting the version to `+`.

### Expected Behavior
By setting the extension in the dependency (but tried setting it in the platform constraint, and in both places at the same time as well), gradle should pick up the last version of my rpm.

### Current Behavior
It's not possible to set the version through the platform. While the constraint is applied, the artifact extension defined either in the platform, or in the dependency, or in both, gets ignored and, looking at the debug logs, gradle keeps attempting to resolve the latest version by forcefully looking for `jar` extension artifacts in the repostory. The only way to fix this is to add `version: '+'` straight to the dependency. At that point gradle is able to resolve the dependency correctly. What's more confusing is this: if you then remove the version definition from the dependency and leave it only in the constraint coming from the platform, gradle keeps resolving the version until the dependencies cache is unvalidated with `--refresh-dependencies`.

### Context
It's not particularly terrible considering that the platform plugin exists for the java world, and this is probably a niche case with a non-java dependency. Still the fact that the constraint works with the cached dependency resolution, even after modifying the dependency definition, is a bit hard to understand. For the time being I've removed the specific dependency from the platform.

### Your Environment
Gradle 6.7, OSX

**Comment by ljacomet** [comment]
This is clearly a use case beyond the initial support and coupled with the complexity of Ivy support, this is unlikely to get looked at.
