### ISSUE TITLE
Build failed with gradle 6.5, project on encrypted exFAT file system disk

### ISSUE THREAD

**Issue by Gizmo-73** [gradle/gradle#15193]
Project was located on encrypted with “VeraCrypt” exFAT file system disk. Build failed with an exception:
e: A:\test\build.gradle.kts: 9:1: Unresolved reference: loadLocalProjectProperties.
About system:
Encryption program: “VeraCrypt”
File system: exFAT
Java: Liberica Standard JDK 11.0.8.1 x86 64 bit for Windows
OS: Windows 10 Pro: 19042.572

Problem was resolved by relocate project on encrypted with “VeraCrypt” NTFS file system disk.
About system:
Encryption program: “VeraCrypt”
File system: NTFS
Java: Liberica Standard JDK 11.0.8.1 x86 64 bit for Windows
OS: Windows 10 Pro: 19042.572
[broken_project.zip](https://github.com/gradle/gradle/files/5551884/broken_project.zip)

**Comment by bmuskalla** [comment]
Supporting exFAT is tracked on #4329. Thanks for the report
