### ISSUE TITLE
Windows Gradle flags a `**\*.ext` pathname as a Bad pathname while on macOS, it does not

### ISSUE THREAD

**Issue by doctorpangloss** [gradle/gradle#15201]
Using the ant recursive path asterisks seems to break on Windows. Simplified from my project:

```
task myTask() {
  outputs.files("$project.projectDir/src/main/java/com/myproject/**.*.java")
  doLast {}
}
```
throws an exception in `org.gradle.execution.plan.LocalTaskNode.canonicalizePath` with `java.io.IOException: Bad pathname`.

Using `outputs.dir("$project.projectDir/src/main/java/com/myproject")` works fine.

### Expected Behavior
The same ant-style recursive paths that work in macOS should work in Windows.

### Current Behavior
`java.io.IOException: Bad pathname` is thrown on the ant-style recursive path on Windows.

### Context
My objective is to use the JOOQ code generator with caching, so I always specify the paths of outputs it creates in my custom task. You can see more in the Gradle file [here](https://github.com/hiddenswitch/Spellsource/blob/5e3021d8002f1004082a3924caf9b27f48ff9e85/framework/build.gradle#L247).

### Steps to Reproduce 
It should be sufficient to put this into a test file on Windows:
```
task myTask() {
  outputs.files("$project.projectDir/src/main/java/com/myproject/**.*.java")
  doLast {}
}
```
and the script will throw not during configuration but during runtime.

### Your Environment
Java 11, Windows 10, Gradle 6.7 from distribution, bash from https://git-scm.com/downloads, IntelliJ 2020.

Task that throws this error `TERM=mintty gradle framework:migrationsOrSqlChanged --scan --stacktrace` build scan URL: https://gradle.com/s/v2epccsl7hd2y

Note, to have a hope and a prayer of executing this on Windows, follow the [Windows getting started section](https://github.com/hiddenswitch/Spellsource#getting-started-with-development-on-windows).

**Comment by mlopatkin** [comment]
The `files(...)` method doesn't support wild cards, it interprets the `*` symbol verbatim. This is a valid filename symbol on Mac but not on Windows, hence the failure on the latter. If the exact names of the output files aren't known beforehand (at the task's configuration time) then I suggest setting a separate directory for the task outputs and using `dir(...)`.
