### ISSUE TITLE
help for a given task

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15207]
I have to be honest, after finding out about `dependencyInsight` it was kind a pain to understand, but even worse, I don't actually remember how to use it without googling it.

suggested fix, make `help` work like `git help`

```
gradle help dependencyInsight
```
would print the help for that task, presumably it would find the task via the tasks api, thus you could also run

```
gradle help :foo:mytask
```

of course in order for this to work at all you need to add an API for documenting task usage, ~~maybe some kind of cli task ... I'm thinking of an API like~~ ok, during the course of writing this I found [picocli...](https://picocli.info/) I've never tried it though and now I'm thinking gradle should just switch to using this O.o so should spring boot. so something like this and it would just generate help

```kotlin
tasks.register("myTask") {
    @Option(names = "-c", description = "create a new archive")
    val foo: boolean;
}
```

**Comment by melix** [comment]
You're looking for:

```
./gradlew help --task dependencyInsight
```

see https://docs.gradle.org/current/userguide/command_line_interface.html#sec:show_task_details

**Comment by ljacomet** [comment]
I would recommend using `-q` as well in that context so the output focuses on the task help.
