### ISSUE TITLE
continues for background with gradle daemon

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15208]
re: #15173 add the following properties configuration

```
org.gradle.continuous=true
```

this would run continuous in the background on the daemon.

oh, and change `--watch-fs` to something more intelligible heck, make that a alias for `--continuous` and make the option something like `--watch-vfs-for-file-metadata` because as is, imho these options are kind of completely unintelligible.

**Comment by mlopatkin** [comment]
It is a bit difficult to understand what is proposed there. I assume that the proposed property enables continuous build for each build invocation. What are the use cases for this property that aren't covered by the existing command-line switch? Enabling continuous build for every build may be problematic for CI environments.

**Comment by xenoterracide** [comment]
In my opinion, the problem with the current it's hard to find what options you're looking for, and what they actually do compared to other products.

Reading this again I don't even remember what `--watch-fs` does, but IIRC it does not actually watch the normal file system in the way you would think reading the option. I would think an option  called `--watch-fs` in a build tool would watch the code in my project directory and rebuild on change, or rerun some defined code on change. That's not what it does, though, IIRC.

**Comment by xenoterracide** [comment]
>  I assume that the proposed property enables continuous build for each build invocation

Oh, and it would enable cases where the tool isn't run by your standard command line, like some IDEs which themselves are deciding the command to invoke.

> Enabling continuous build for every build may be problematic for CI environments.

I can see that, kinda reminds me of spring boot configuration, I always have a separate developer profile that isn't tracked by git. Sounds like you want to do that too ;).

**Comment by donat** [comment]
Having a `org.gradle.continuous=true` configuration option for Gradle has no value. As @mlopatkin said, it would render a Gradle build useless when an interactive shell is not available. You'd also need a `--no-continuous` flag, to counter the configuration option.

Regarding `--watch-fs`: naming is hard :). At the same time, if you run `gradle --help 
 grep watch-fs`, the one-line description gives an arguably good summary on the feature:

```
--watch-fs Enables watching the file system for changes, allowing data about the file system to be re-used for the next build.
```

If that's not clear enough, a quick google search can take you to the Gradle docs, or to a blog post with detailed description: https://blog.gradle.org/introducing-file-system-watching

**Comment by xenoterracide** [comment]
Yeah except it's not about the file system, It's about the virtual file system which is not the same thing. At least not in most people's heads.
