### ISSUE TITLE
Allow specifiying additional class files to be processed by any annotation processors

### ISSUE THREAD

**Issue by kitlith** [gradle/gradle#15205]
Sometimes, it would be nice to have the ability to run annotation processors against class files that have already been compiled. Gradle already does this for incremental compilation w/ Aggregating Processors (at the very least), but this is limited to files present in a previous compilation.

### Expected Behavior

(Note: I'm speculating on a possible API, I'm open to whatever api may be decided on)

A configuration `{sourceSet}AnnotationProcess` is provided, which causes a dependency to be included in annotation processing and/or a method `processClasses` is added to JavaCompile (and other relevant tasks?) that acts akin to `source`, except for compiled class files.
### Current Behavior

No such api exists.
### Context
So, I have two specific scenarios where I've wanted to reach for something like this:

#### Aggregating Annotation Processor Across Multiple (Sub)Projects
In a certain project I'm helping with, we're implementing the api of a monolithic class, but all of the static methods are split between various subprojects, and we ended up needing to touch our implementation of that monolithic class so often that it was causing a bunch of merge conflicts. One of the solutions that we're looking into is performing some annotation-based code-generation.

Unfortunately, given that our project is split up into many subprojects, and we'd want to generate a single class in yet another subproject, our current options are either to:
 - Process each subproject individually, spit out metadata, then do some codegen in the relevant subproject based on the metadata from all the other subprojects. (This is what I've currently implemented)
 - essentially roll our own annotation processor by using asm to find all the annotations, and then perform codegen. (This is a bit more attractive as we wouldn't need intermediate metadata files, we'd just be translating from asm to <source generation library of choice>.)
 - ???

These options that I've found aren't all that great, but they are what work currently. (If there's a possibility I've missed, I'd be glad to hear it.) Being able to specify additional classes for annotation processing would allow me to use an annotation processor to generate the monolithic classes directly, without any intermediate steps, and without rolling my own annotation processing framework.

#### Running Annotation Processors on Generated Class Files
(i.e. via the ASM library)

There's a library we use that uses annotations both at runtime and at compile-time -- the compile time annotation processor generates metadata files having to deal with obfuscation mappings, for use at runtime along with the annotations proper.

The idea came up recently to use ASM to generate class files for use with this library. However, if we do that, we don't have a way to run the annotation processor on it to generate the metadata files, etc. Being able to specify additional classes for annotation processing would allow us to generate the metadata files through the usual annotation processor.

**Comment by kitlith** [comment]
Excuse me, there *is* still a way to accomplish this without adding additional features to gradle, but I wouldn't call it a great way to do it.

If you get gradle to use CommandLineJavaCompiler, then you can add class names to compilerArgs because the final arguments are now lumped onto the commandline. i.e.
```gradle
compileJava.options.fork(executable: "/usr/bin/javac")
compileJava.options.compilerArgs.add("com.example.TestFile")
```

means that the TestFile class (which can be from a dependency) will now get processed for annotations.

I think I'd still prefer there be an actual feature in gradle for this, but it's something.

**Comment by kitlith** [comment]
Full implementation of the hack mentioned above, but using JAVA_HOME instead of executable since that's just a single internal API away (and there's possibly a non-internal api way to get it that I missed so far): https://github.com/kitlith/patchwork-api/blob/b91a4ebe7a2099fdbde457d953643d428249269e/patchwork-god-classes/build.gradle#L37-L68

**Comment by ljacomet** [comment]
Annotation processing is not a current focus of the team, aside from bug fixing.
Do not expect clear feedback on the interest to have such support in Gradle in the short or medium term.
