### ISSUE TITLE
Accessors generation task for Kotlin precompiled script plugins can produce and store problematic outputs

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#15214]
In order to generate type-safe accessors for Kotlin precompiled script plugins the plugins block is applied to a synthetic project, allowing to gather the "project schema".

If that fail for some reason then the accessors aren't generated and the `generatePrecompiledScriptPluginAccessors` task succeeds and its outputs are stored in the build cache.

If the failure is environmental then the produced outputs can be considered wrong. This makes it hard to troubleshoot.

Recovering from this requires running a clean build with the build cache disabled, or somehow invalidating the cache. If the problem happens in `buildSrc` this requires more gymnastic. This makes it hard to workaround.

### Expected Behavior
Errors during "project schema" gathering for Kotlin precompiled script plugins type-safe accessors generation disable reusing the outputs, either incrementally or from the build cache.

### Current Behavior
Such wrong state is hard to troubleshoot and workaround.

### Context
This happened on our CI. See the following:
- https://gradle.slack.com/archives/C09LZKUCB/p1605680008327000
- The first failing build https://ge.gradle.org/s/5yfrszqcvaygg/console-log?task=:buildSrc:integration-testing:generatePrecompiledScriptPluginAccessors
- It stored wrong outputs in the cache https://ge.gradle.org/s/5yfrszqcvaygg/timeline?details=c3cy4oa6gjehi&expanded=WyIxNCJd&taskFilter=:buildSrc:integration-testing:generatePrecompiledScriptPluginAccessors

**Comment by big-guy** [comment]
@eskatos @bamboo do you think this has been fixed with all the changes in 7.0?

**Comment by bamboo** [comment]
Yes, I think so. The task will no longer store to the build cache by default:

https://github.com/gradle/gradle/blob/0f34f39da91f21275c879c69805df4d43d4dd0d2/subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/tasks/GeneratePrecompiledScriptPluginAccessors.kt#L124-L128

It can be told to use the build cache via the `org.gradle.kotlin.dsl.precompiled.accessors.strict` system property, in which case the task fails whenever plugin application fails.

https://github.com/gradle/gradle/blob/96096bfea2ca691f1ba1392318a1d132b9ae0bae/subprojects/kotlin-dsl-provider-plugins/src/main/kotlin/org/gradle/kotlin/dsl/provider/plugins/precompiled/DefaultPrecompiledScriptPluginsSupport.kt#L229-L235

**Comment by eugene-krivobokov** [comment]
Hi! Is it possible to backport this fix to 6.9?
In Android projects updating to 7.0 turned out not so trivial due to compatibility issues in AGP and Kotlin plugins.

**Comment by iNikem** [comment]
Is `org.gradle.kotlin.dsl.precompiled.accessors.strict` property documented somewhere?
