### ISSUE TITLE
Toolchains for jvm projects autoprovision configuration extension

### ISSUE THREAD

**Issue by netbeansuser2019** [gradle/gradle#15211]
See: https://discuss.gradle.org/t/toolchains-for-jvm-projects-autoprovision-direct-download/38086

### Expected Behavior
You can directly in gradle build script:
- set url from where it should be downloaded JDK
- set in-project-path/url where to take specific JSON file from where it could be selected correct path so no need implement
  any thirdtyparty API (webserver and so on)

So both cases can be useful in closed environments or even restricted about direct access to internet.

### Current Behavior
Turn off autoprovision or demand implementation of thirdtyparty API for any other JDK provider.

### Context
No dependency on thirdtyparty API for autoprovision of JDK and provide support even for closed environments.

**Comment by ljacomet** [comment]
We might consider adding such support in the future but there is no short term plan.

The team will open an issue once this gets added to planning.
