### ISSUE TITLE
Interrupted JDK download blocks re-attempting download

### ISSUE THREAD

**Issue by pun-ky** [gradle/gradle#15215]
```
> Unable to download toolchain matching these requirements: {languageVersion=11}
   > Unable to expand TAR '/Users/krystian.panek/.gradle/jdks/adoptopenjdk-11-x64-mac.tar.gz'
       The tar might be corrupted or it is compressed in an unexpected way.
       By default the tar tree tries to guess the compression based on the file extension.
       If you need to specify the compression explicitly please refer to the DSL reference.
```

### Expected Behavior
When incidentally or not JDK download is being interrupted, the second attempt should delete uncompleted download, and download process should be repeated without error.

### Current Behavior

Re-attempting interrupted download of JDK fails.

### Context

Trying to use auto-provisioning of JDK in the custom plugin: https://github.com/Cognifide/gradle-aem-plugin/pull/797

### Steps to Reproduce 

Interrupt download by CTRL+C and try to rerun the task initiating the download.

https://files.slack.com/files-pri/T9HD2BQF9-F01F08ALA1Y/image.png

### Your Environment

```
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          14 (Oracle Corporation 14+36-1461)
OS:           Mac OS X 10.15.7 x86_64

```

**Comment by ljacomet** [comment]
Thanks for the report, this was believed fixed in 6.7.1, will take another look.

**Comment by pun-ky** [comment]
yep, my bad ;) you are too quick. thx for this nice feature!

**Comment by ljacomet** [comment]
I am confused now 😄 
Your report says you tried with 6.7.1 and saw the issue still. Is that right?

**Comment by pun-ky** [comment]
that's my bad ;) I did migration in the time of testing toolchains. And 2 separate windows/project opened in the same time ;) sorry

**Comment by ljacomet** [comment]
Ah ok, great. Thanks for confirming!

**Comment by ljacomet** [comment]
Duplicate of #14761
