### ISSUE TITLE
Gradle 6.5 cause infinte gradle daemon start

### ISSUE THREAD

**Issue by fransiscushermanto** [gradle/gradle#15224]
This bug happen when try to build app at Android Studio. It will call hundreds of gradle daemon till your memory leak and all your programs started to crash. Did anyone find out the solution?

**Comment by robbiecic** [comment]
Have also noticed this problem with 6.7

**Comment by Monta111** [comment]
Happen when turn on wifi hotspot in windows 10

**Comment by fransiscushermanto** [comment]
Really? Yeah i'm using it with my hotspot turn on hmm maybe that is the
problem

**Comment by mlopatkin** [comment]
We track the endless creation of daemons in unusual network configurations in #12232. Please add your votes/reproducers there.
