### ISSUE TITLE
settings.gradle.kts not using the buildSrc logic

### ISSUE THREAD

**Issue by kubapet** [gradle/gradle#15242]
I basically want to re-escalate the issue [11090](https://github.com/gradle/gradle/issues/11090)
Read through it again please and look how many people are disappointed with the new behaviour.
The buildSrc should be logic for building of the project. It doesn't make sense if it is evaluated only somewhere in the middle of the process.
Fix it please or provide both options as 2 stages of the build logic compilation buildSrc and projectSetupSrc.. I don't mind how you call it.
Also, you shouldn't do such a breaking changes in the API, we never had this issue with mvn and I have to face tensions for migration back to maven because of things like this.

**Comment by jjohannes** [comment]
In Gradle 7, you can include a build in `pluginManagemnt {}` this would be similar to the old "early" buildSrc avaluation behavior mechanism (there are no plans to change that back): https://docs.gradle.org/7.0-rc-1/release-notes.html#plugin-development-improvements
