### ISSUE TITLE
Notify user about overflow in watched dir on macOS

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#15249]
We saw in gradle/gradle-private#3235, that we don't report `INVALIDATE` events with a path as overflow on macOS. The handling of the VFS (invalidate anything which is at the path) is good, though we might inform the user at the end that this overflow happens to understand why fewer files are retained in the VFS.

---
cc: @gradle/execution

**Comment by lptr** [comment]
We are now handling overflows consistently by invalidating overflown watched hierarchies, see: https://github.com/gradle/gradle/issues/15911.
