### ISSUE TITLE
Follow up on not fingerprinting outputs

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#15250]
There are a few leftovers from #15113:

- Add more tests for `OutputChanges`, since it is not tested any more as part of `FingerprintCompareStrategyTest`
- Remove the absolute path creation from `PathTracker`
- Update the Javadoc on `OutputUtil`.

We may also want to remove filtering out missing files in `OutputChanges` and use a similar descriptive change as in `FileChange` when a file goes from `MISSING` to something else.

---
cc: @gradle/execution

**Comment by lptr** [comment]
PR #15282 has been reverted.
