### ISSUE TITLE
JDK 9 with `--release 7` gives `JavaFileManager is not a StandardJavaFileManager.`

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#15267]
In theory, this should use adoptjdk 9 and compile for a target of JDK 7. 

```kotlin
tasks.compileJava {
   options.release.set(7)
}

java {
   toolchain {
      languageVersion.set(JavaLanguageVersion.of(9))
   }
}
```

### Expected Behavior

This just works? provide a `StandardJavaFileManager`. :) 

### Current Behavior

Gives this error: 

```
* What went wrong:
Execution failed for task ':compileJava'.
> --release option specified, but the provided JavaFileManager is not a StandardJavaFileManager.
```

### Context

This would be useful for trying to compile some old code in a way to that works on Android. 

### Your Environment
Gradle 6.7.1

**Comment by ljacomet** [comment]
This was a bug in Java that has been fixed for 10+, see [the JDK bug system](https://bugs.openjdk.java.net/browse/JDK-8139607).

This means that we should document that the release flag cannot be used with a Java 9 compiler unfortunately.

**Comment by bmuskalla** [comment]
@ljacomet We should even consider catching the above exception and decorate it with this link and your workaround.

**Comment by ljacomet** [comment]
As a workaround, you can instead rely on `targetCompatibility` to get Java 7 bytecode.
The one downside is that it will not prevent you from using API introduced in 8 or 9.

**Comment by ljacomet** [comment]
Documentation has been updated. Closing as support for Java 9 will not be fixed.
