### ISSUE TITLE
Enable the "Gradle User Manual" page show the vertical menu located in the left for a mobile device

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#15263]
### Expected Behavior

For the [Gradle User Manual](https://docs.gradle.org/current/userguide/userguide.html) page, it should have the same navigation support for a mobile device such as PC Desktop and Laptop have available.
### Current Behavior

For a tablet based on Android and working with Google Chrome (updated in the tablet), the latter only shows the first page and is not possible get the vertical menu shown in the left. It happens even activating the `desktop mode`.  I can't neither navigate nor read the complete documentation.

### Context

I am able to only see the page 01 and is not possible to navigate to other sections how I am able to do in a Web Browser in a PC Desktop and Laptop. I can't read more sections.

**Comment by tom-bowles** [comment]
This makes it impossible to read the user guide on mobile.

**Comment by anderso** [comment]
I believe this media query completely hides the navigation for views under 1024 px, and there is no other way of reaching it that I can see. 

```
/* Top navigation mobile styles */
@media (max-width: 1023px) {
```
So the documentation is pretty much useless and confusing on mobile devices and small screens as it is now. It can be easily reproduced on any PC by resizing the window until the navigation disappears.

**Comment by yihtserns** [comment]
I was wondering why this was closed even though there's no visible change in the doc when browsed using a phone browser.

Turns out the fix was to show the navigation area at the bottom of the pages. 🤦‍♂️
