### ISSUE TITLE
GUI to report at real time all the daemons running/stopped/delayed by all Gradles instances

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#15261]
### Expected Behavior

Through a tool based on GUI show at real time all the daemons running (and stopped/delayed) by all the Gradle versions working. And showing what app is involved behind the scenes.

For example the tool would show: 

* daemon X being running by Gradle 6.6 by terminal/console
* daemon Y being running by Gradle 6.7 by terminal/console
* daemon Z being running by IntelliJ Idea
* daemon W being running by STS (Spring Tool Suite)

And give the option to stop it.

### Current Behavior

Run each time the `gradle --status` for each Gradle release to see the current status.

### Context

Detect quickly where and who is causing a lock about daemons.

**Comment by mlopatkin** [comment]
Thank you for the suggestion! 

We are thinking about potential improvements in this area but having a GUI for daemon statuses is unlikely.
