### ISSUE TITLE
Source dependencies do not support dependencySubstitution

### ISSUE THREAD

**Issue by tasomaniac** [gradle/gradle#15268]
Gradle Composite Builds and Source Dependencies automatically resolve the component from the included build. In some conditions, the dependency may not declare those as part of Gradle project property. Some of the libraries just declare them as part of maven publication only. 

When that's the case, we get the following error:

>  Git repository at ssh://git@github.com/company/foo.git did not contain a project publishing the specified dependency.

Composite Builds have `dependencySubstitution` feature where it allows you to substitute a module with a project within the included build. In the example below, the dependent project is a simple library and the folder they have is just `library`

```
includeBuild('../') {
    dependencySubstitution {
        substitute module('com.company:foo') with project(':library')
    }
}
```

### Expected Behavior

Just like composite builds, source dependencies should also support `dependencySubstitution`

### Current Behavior

Source dependencies does not support `dependencySubstitution`

Related to #10559

**Comment by ljacomet** [comment]
Source dependencies are a feature that needs some attention before it integrates properly with the rest.

There is unfortunately no plan for doing that in the short or medium term.
