### ISSUE TITLE
gradle init should not create buildSrc but use included build logic builds

### ISSUE THREAD

**Issue by cvmocanu** [gradle/gradle#15326]
From what I understand, ``buildSrc`` is discouraged for new projects, since it has a number of disadvantages, maybe the biggest being that any change in it will force a full rebuild.

Because of this, the ``init`` task should be re-written to:
* no longer create ``buildSrc``
* create build plugins instead (maybe put each build plugin inside a ``build-plugins`` directory)
* reference the build plugins from the settings file using ``includeBuild``

Doing this is particularly important since builds created by ``gradle init`` are probably considered "best-practice" by people unfamiliar with Gradle.

**Comment by jjohannes** [comment]
Thanks for opening this issue @cvmocanu. We are already working towards this and will track progress here.

Other things to consider (taken from #14044):

- Update all documentation to refer to buildSrc as an included build
- Remove "bad practices" from documentation such as referring to classes from buildSrc without applying a plugin
- Document discouraged practices or behavior we will want to deprecate
- Add/update documentation around using included builds for shared build logic
    - Need to have at least one sample where build logic is shared between buildSrc and root build

**Comment by jjohannes** [comment]
I would like to see this change _soonish_. In particular to guide new users into the best direction.

I am happy to provide a PR if this change is desired.

**Comment by eskatos** [comment]
@jjohannes that would be great! Note that the `init` plugin now has a flag/question about using _incubating_ features. As a first step this change should be behind this flag with the intention to make it the default eventually.

**Comment by jjohannes** [comment]
@eskatos thanks for the feedback. Here is a PR #21192.

**Comment by bamboo** [comment]
One setup that I really like is to have an included build for build logic under `$PROJECT_ROOT/gradle/plugins`, that has two main benefits:
* less Gradle related stuff at the root
* clarity with regards to the role of the included build

**Comment by eskatos** [comment]
Thank you @jjohannes for your contribution in https://github.com/gradle/gradle/pull/21192!
It'll ship with Gradle 7.6

**Comment by chkpnt** [comment]
I've just read about this in the [release notes](https://docs.gradle.org/7.6/release-notes.html#relocated-convention-plugins-in-projects-generated-with-init), but I'm wondering that the documentation still [states](https://docs.gradle.org/7.6/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins):

> We recommend putting source code and tests for the convention plugins in the special buildSrc directory in the root directory of the project. For more information about buildSrc, consult [Using buildSrc to organize build logic](https://docs.gradle.org/7.6/userguide/organizing_gradle_projects.html#sec:build_sources).

Since this issue was opened already in 2020 and @cvmocanu wrote "buildSrc is discouraged for new projects", am I missing something?

**Comment by mrclrchtr** [comment]
I stumbled across the same question because I was wondering why init does not create a buildSrc. Is buildSrc recommended or not?
