### ISSUE TITLE
Dont  recognize version from Bom

### ISSUE THREAD

**Issue by Monax111** [gradle/gradle#15330]
### Expected Behavior
add implementation(platform("ru.tim:bom:0.0.1")), remove version for dependency "io.github.microutils:kotlin-logging", 
Gradle take version from Bom(ru.tim:bom:0.0.1)

### Current Behavior
Could not find io.github.microutils:kotlin-logging:.

### Context
I have a lot of standard projects and I don't want to specify versions

### Steps to Reproduce 
clone [exemple project](https://github.com/Monax111/bomExample)
execute in module bom task publishToMavenLocal
remove version [kotlin-logging](https://github.com/Monax111/bomExample/blob/main/application/build.gradle.kts#L18)
try build module application

### Your Environment
https://scans.gradle.com/s/lnkxjthugapn6

**Comment by ljacomet** [comment]
The issue comes from declaring the constraints as `runtime`. This means that they are only applicable when resolving a runtime classpath, not a compile one. See [the documentation](https://docs.gradle.org/6.7.1/userguide/java_platform_plugin.html#sec:java_platform_separation) for details.
