### ISSUE TITLE
Build init plugin (type pom) should support compileOnly scope

### ISSUE THREAD

**Issue by otrosien** [gradle/gradle#1533]
At the moment, when initializing a gradle project from maven which has dependencies in provided scope, gradle generates a warning message, that this type of dependencies is not supported yet:

```
/* This dependency was originally in the Maven provided scope, but the project was not of type war.
                       This behavior is not yet supported by Gradle, so this dependency has been converted to a compile dependency.
                       Please review and delete this closure when resolved. */
```

See https://github.com/gradle/gradle/blob/master/subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy#L314

### Expected Behavior

This can be revised as provided can be mapped to compileOnly scope.

### Current Behavior

The current warning is obsolete and results in having a dependency in the wrong scope.

### Context

I noticed this when I was converting a multi-module maven build to gradle.

### Steps to Reproduce (for bugs)

- create a pom.xml with a dependency using `<scope>provided</scope>`
- run `gradle init --type pom` to produce the gradle build artifacts.

**Comment by bmuschko** [comment]
Right, we should have fixed that right away when introducing `compileOnly`. Are you interested in providing a pull request for this?

**Comment by glefloch** [comment]
Hi, I'm looking into contributing to the project. Can I look at this issue?

**Comment by bmuschko** [comment]
@glefloch Thanks for offering your help. Feel free to do so. You might want to coordinate with @otrosien.

**Comment by otrosien** [comment]
@bmuschko I just reviewed @glefloch implementation. Looks good.

**Comment by glefloch** [comment]
The pull as been merged, I think this issue can be close

**Comment by bmuschko** [comment]
@glefloch We are still going to peer review internally before closing.
