### ISSUE TITLE
Consider using zstd instead of zip

### ISSUE THREAD

**Issue by LifeIsStrange** [gradle/gradle#15334]
https://facebook.github.io/zstd/
Some gradle workloads make use of zip e.g through ziptree.
Zip performance might sometimes be non negligible e.g here https://github.com/gradle/gradle/issues/11693 (I believe)
Zstd is a state of the art and mature compression algorithm which allows better compression ratios at much better performance.

**Comment by ljacomet** [comment]
From my quick reading, this is a different algorithm altogether, not a faster implementation of zip.
So this would not help `ziptree` which reads _zip_ files ...

Given that, I do not see Gradle "replacing" ziptree with this library.

**Comment by LifeIsStrange** [comment]
@ljacomet Right, however there is a faster zip implementation:
https://github.com/ebiggers/libdeflate
cf: https://lemire.me/blog/2021/06/30/compressing-json-gzip-vs-zstd/
