### ISSUE TITLE
Expose access to gradle properties in dependencyResolutionManagement DSL

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#15337]
### Context
Gradle properties are a core part of statically configuring a build, but are currently not accessible in the new `dependencyResolutionManagement` DSL in Gradle 6.8. This prevents us from properly using it as we gate access to certain repositories on the presence of gradle properties. Is there any reason this is not possible since we are able to access properties elsewhere in settings files?

**Comment by ZacSweers** [comment]
Scratch this, looks like it still (coincidentally) works as long as access is done on a `withGroovyBuilder` on the `settings` object within the block

```kotlin
settings.withGroovyBuilder {
  // do the dark magic here
}
```

**Comment by AAverin** [comment]
Would love this to be reopened.
It's completely unclear from documentation how can values from `gradle.properties` be used in `settings.gradle` when defining dependencyResoltuionManagement

**Comment by stefan-g** [comment]
it's not clear to me either. why is properties.wyz working in pluginManagement and not in dependencyResolutionManagement?
