### ISSUE TITLE
https://www.google.com/finance#feat?firebase


### ISSUE THREAD

**Issue by Enterprises-Gracida-Veracruz** [gradle/gradle#15357]
https://www.google.com/finance#php=build?/github.com/firebase

**Comment by Enterprises-Gracida-Veracruz** [comment]
> https://www.google.com/finance#php=build?/github.com/firebase
> 

https://github.com/gradle/gradle/issues/15357

**Comment by Enterprises-Gracida-Veracruz** [comment]
https://www.google.com/finance#php=build?/github.com/firebase

**Comment by ljacomet** [comment]
Closing as spam
