### ISSUE TITLE
official project homepage

### ISSUE THREAD

**Issue by Enterprises-Gracida-Veracruz** [gradle/gradle#15366]
---
cc: @gradle/execution

**Comment by Enterprises-Gracida-Veracruz** [comment]
> Ayuda de la app para Android
> 
> ---m.me/enterprises-gracida-veracruz
> cc: @gradle/execution
> https://developers.facebook.com/docs/commerce-platform/platforms/distribution/MPApprovalAPI/@enterprises-gracida-veracruz

https://www.google.com/settings/chrome/sync/5RRQ+V4 Veracruz, Ver., México, https://plus.codes/76F55RRQ+V4

**Comment by wolfs** [comment]
Closed as Spam.
