### ISSUE TITLE
Cannot resolve symbol 'File' in settings.gradle

### ISSUE THREAD

**Issue by kafan1986** [gradle/gradle#15363]
I have an android project and now after updating to gradle 6.5.1 I see this error message on android studio. Although the project still builds OK.

Earlier with gradle 6.1.1 I never encountered this problem.

![Screen Shot 2020-11-29 at 4 07 47 AM](https://user-images.githubusercontent.com/7953422/100527474-c4e62680-31f8-11eb-9e28-b053de038297.png)

**Comment by kafan1986** [comment]
Error message is not shown anymore on Android studio 4.1.2. So closing the issue.

**Comment by brianreinhold** [comment]
I have the bug in just installed Android 4.2

**Comment by esiek** [comment]
I have the same bug in Android 4.2. For URL same - Cannot resolve symbol.
![Przechwytywanie](https://user-images.githubusercontent.com/14806683/118248647-d9676400-b4a4-11eb-936e-4a8f340148dc.PNG)

**Comment by brianreinhold** [comment]
Grzegorz,

I tried everything to resolve it ... the final thing that worked- uninstall 4.2.0 or 4.2.1 and re-install 4.1.3. All those issues went away.

Used gradle 4.1.3 and gradle wrapper 6.5 in the working 4.1.3 solution.

Brian

________________________________

**Comment by esiek** [comment]
@brianreinhold unfortunately this is the only solution at the moment :( 

The second problem is red lines that display in the IDE for all generated Navigation Component (directions, args etc.) classes from the JetPack. Problem is only inside java classes. Everything is displayed correctly in Kotlin classes. Adds attachments with screenshots.
![screen2](https://user-images.githubusercontent.com/14806683/118472374-0caa2d00-b709-11eb-91c7-9bc9988ab080.PNG)
![screen1](https://user-images.githubusercontent.com/14806683/118472375-0d42c380-b709-11eb-8915-06a1e863387c.PNG)

**Comment by jvankooo** [comment]
Tried everything mentioned above. Uninstalled, deleted all associated files and folders, reinstalled different versions of Android Studio and gradle. Still, no luck.

Finally fixed by changing JDK version to corretto-1.8.0_292.

**Comment by dhjaber** [comment]
i think you are using IDEA that is not support Enterprise IDE features....

**Comment by ChenJunXu** [comment]
@brianreinhold @esiek 

I found a solution. File -> project structure，switch annother jdk location，click "apply"，and then resume origin jdk location, and click "apply".

It work for me and  mine friends.

**Comment by brianreinhold** [comment]
@ChenJunXu Need to try that should it happen again. I just switched to OpenJDK and that solved it. Perhaps that is a manifestation of your solution!

**Comment by bolds07** [comment]
Is this a bug on gradle or on android studio?

**Comment by drewjosh** [comment]
I'm running Android Studio 2020.3.1 and I'm also having this error. Although I can build without problems, it is just annoying to see the errors in the editor.

**Comment by sinan546** [comment]
Don't worry about this problem
![image](https://user-images.githubusercontent.com/66713485/150950785-f6399b8e-eba0-469b-817c-fc63b2c1b0ba.png)
Just run your app as it is.

**Comment by Oneotrix** [comment]
big thank you for answering on my questions)
