### ISSUE TITLE
com.firebase.google.project.facebook

### ISSUE THREAD

**Issue by Enterprises-Gracida-Veracruz** [gradle/gradle#15362]
com.firebase.google.project.facebook

_Publicado originalmente por @Enterprises-Gracida-Veracruz en https://github.com/Enterprises-Gracida-Veracruz/app-manifest-AndroidManifest.xml/issues/1#issuecomment-735286305_

**Comment by Enterprises-Gracida-Veracruz** [comment]
> com.firebase.google.project.facebook
> 
> _Publicado originalmente por @Enterprises-Gracida-Veracruz en https://github.com/Enterprises-Gracida-Veracruz/app-manifest-AndroidManifest.xml/issues/1#issuecomment-735286305_

@Enterprises-Gracida-Veracruz

**Comment by ljacomet** [comment]
Closing as spam
