### ISSUE TITLE
plugins {} block could be able to use dynamic versions

### ISSUE THREAD

**Issue by torrescd** [gradle/gradle#15389]
Currntly is not supported due this PR https://github.com/gradle/gradle/pull/6774, but seems that not being able to use dynamic versions on plugins is a colateral effect.

### Expected Behavior
Be able to use ranges on plugin versions 
https://docs.gradle.org/current/userguide/single_versions.html

### Context
With this approach, the next block could work.

```
plugins {
    id 'best-plugin' version '1.0.+'
}
```

**Comment by torrescd** [comment]
related/duplicated of https://github.com/gradle/gradle/issues/14704

**Comment by bmuskalla** [comment]
This has been added for Gradle 7.0. See [release notes](https://docs.gradle.org/current/release-notes.html)

```
Using dynamic versions in the plugins block
Until now, the plugins { } block only supported fixed versions for community plugins. All version string notations Gradle supports are now accepted, including + or latest.release.

We recommend using the plugins {} block for applying plugins using Gradle 7. The old apply plugin: mechanism will be deprecated in the future.
```
