### ISSUE TITLE
Give access to catalogs from binary plugins

### ISSUE THREAD

**Issue by melix** [gradle/gradle#15382]
### Context

A binary plugin may need to access version catalogs (declared in settings). Because the catalogs consist of generated classes, we cannot expose those classes directly to binary plugins. Instead, there should be a container of catalogs available, which gives access to "raw data".

Unlike the generated accessors, this API cannot be type safe.

e.g:

```
@Inject
abstract VersionCatalogContainer getVersionCatalogs()

...

versionCatalogs.getByName("libs").getDependency("some-alias")
```

**Comment by gildor** [comment]
What about precompiled script plugins? you cannot use @Inject there (if I'm not mistake), and having generated accessors there would be very useful, especially for Kotlin DSL (same as for tasks/extensions)
