### ISSUE TITLE
Existing Sample in documentation for Plugin Marker is broken

### ISSUE THREAD

**Issue by madorb** [gradle/gradle#15395]
As of this commit https://github.com/gradle/gradle/commit/9e9ec88a267e22520afe3f22aa524cb229dc65f8 the text was changed to use different group names (`com.example` from `org.gradle.sample`) but the corresponding image was not updated. 
https://github.com/gradle/gradle/commits/master/subprojects/docs/src/docs/userguide/img/pluginMarkers.png

https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers

I found this to be rather confusing as it's unclear why the names changed if that was some sort of side-effect of the marker generation etc.

**Comment by jjohannes** [comment]
Thanks @madorb. Good catch!

I updated the image and cleaned it up a bit so that it, hopefully, also looks less complex: https://github.com/gradle/gradle/commit/61f8ac16f943f75a4cd972b0d9c668e385436598
