### ISSUE TITLE
Incorrect behavior when publishing artifacts to (slow) Maven Central

### ISSUE THREAD

**Issue by nehaev** [gradle/gradle#15398]
Maven Central is quite often overloaded and responds slowly. Gradle can not handle this correctly even when publishing relatively small artifacts (700KB).

### Current Behavior

Gradle console:

```
> Task :publishMavenJava8PublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenJava8PublicationToMavenRepository'.
> Failed to publish publication 'mavenJava8' to repository 'maven'
   > Could not write to resource 'https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/loki4j/loki-logback-appender-jdk8/0.4.0/loki-logback-appender-jdk8-0.4.0.jar'.
      > Read timed out
```

On staging repositories page (https://oss.sonatype.org/#stagingRepositories) I see 2-3 new repos that contain only the artifact that Gradle failed to load, in my case: `loki-logback-appender-jdk8-0.4.0.jar`

### Expected Behavior

1. I should be able to set the timeout from my build configuration
2. Retry behavior should be configurable from the build configuration and probably by default Gradle shouldn't retry publishing, as I don't expect to see multiple staging repos if I ran `publish` only once.

### Your Environment

```
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.9.1 (Ubuntu 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OS:           Linux 5.4.0-54-generic amd64
```

**Comment by ljacomet** [comment]
Retries during publishing is problematic at different levels.
Here you are also using a staging repositories which can take some time to create on the repository side.
But you should be able to retry then.

This is an area that Gradle wants to improve but this not going to happen in the medium term. I will close this for now and it will be considered when working in this area.

**Comment by nehaev** [comment]
> I will close this for now and it will be considered when working in this area.

Is there any workaround I can use until then?

**Comment by ljacomet** [comment]
There are [plugins](https://plugins.gradle.org/search?term=nexus) that allow to control the creation, closing and promotion of staging repositories. Using one of those helped me in the past to get the staging repo properly configured before attempting any upload.
