### ISSUE TITLE
Java executable requires file extension 

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#15392]
Using a `Test` task + custom executable changed behavior. I used to work with just an executable name (e.g. `java`) but on Windows, it now requires `java.exe`. We should look into whether `DefaultJvmVersionDetector` should just the canonical path to check if it exists.

**Comment by bmuskalla** [comment]
@breskeby this has been fixed for RC2. Maybe you can give that a spin. A Nightly is building soon (should be from December 4th or later).

**Comment by breskeby** [comment]
@breskeby tested on our windows machines and all seems fine again including what was blocking us from upgrading from 6.6.1 to 6.7 :) 👍 🤠  👍

**Comment by bmuskalla** [comment]
Thanks, @breskeby for verifying 🙇
