### ISSUE TITLE
resolutionStrategy.eachDependency should be able to blacklist project dependencies and fail the build

### ISSUE THREAD

**Issue by KidDaedalus** [gradle/gradle#1540]
### Expected Behavior
Naively, `resolutionStrategy.eachDependency` looks like it could be used to enforce a "Project A may not depend on Project B" condition.

```gradle
configurations.compile {
    resolutionStrategy{   
        eachDependency { DependencyResolveDetails details ->
            // This exception is swallowed. The user never sees it and the build succeeds.
            throw new GradleException('Not allowed to use that dependency!')
        }
    }
}
```

### Current Behavior
To achieve "Project A may not depend on Project B" enforcement we ended up using this code snippet:
```gradle
project.afterEvaluate {
    def projectDependencies = configurations.compile.allDependencies.findAll { it instanceof org.gradle.api.artifacts.ProjectDependency }
    projectDependencies.each {
        Project dependentProject = it.getDependencyProject()
        if(dependentProject.path.startsWith(':disallowed:path')) {
            throw new GradleException("$project.path not allowed to depend on $dependentProject.path")
        }
    }
}
```
This achieves our desired result but it seems strange that dependency resolution rules, which at first look tailor made for this, only really work with non-project dependencies. 

### Context
In a multi-project build it is sometimes desirable to enforce rules about which projects can depend on which other projects. For example you might have "services" which cannot directly depend on each other but which are allowed to depend on "interfaces". 

It wastes developer time to get all the way to code review (or later) before finding out "Oh no you can't depend on the implementation, you have to use the interface or you'll bloat the installer/cause spring context errors/make the classpath non-deterministic"

### Your Environment
Gradle 3.4,
275ish projects where there are "applications" which can depend on "interfaces" but not on the "services" that implement those interfaces. Everything is allowed to depend on "libraries" but those libraries may not depend on anything but other libraries.

**Comment by bmuschko** [comment]
If you look at `DependencyResolveDetails` you will notice that you cannot resolve Project dependencies. It's only about external modules that can be forced to use a different version or target.

There are other ways to achieve what you want and you are using one of those. I don't think we'll work in Project dependencies `eachDependency` anytime soon. I'd encourage you to write up a spec if you are interested in such a proposal. In the meantime I am going to close the issue.
