### ISSUE TITLE
GradleConnector#disconnect can trigger undesirable download of a distribution

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#15405]
### Expected Behavior

When a TAPI client is shutting down, TAPI should not need to download a Gradle distribution to try to stop daemons.

### Current Behavior

When a TAPI client is shutting down, TAPI downloads the full Gradle distribution. 

### Steps to Reproduce 

Reported to JetBrains: https://youtrack.jetbrains.com/issue/IDEA-256542

**Comment by nskvortsov** [comment]
Lets make sure same applies to ProjectConnection.notifyDaemonsAboutChangedPaths()

**Comment by donat** [comment]
> Lets make sure same applies to ProjectConnection.notifyDaemonsAboutChangedPaths()

@nskvortsov Can you please elaborate what's the expected and actual behavior?

**Comment by nskvortsov** [comment]
> 
> @nskvortsov Can you please elaborate what's the expected and actual behavior?

IIRC, expected behavior is "Calling ProjectConnection.notifyDaemonsAboutChangedPaths() does not start Gradle distribution download". Not sure about actual behavior.
