### ISSUE TITLE
Difference between runtime and runtimeClasspath configurations 

### ISSUE THREAD

**Issue by xeruf** [gradle/gradle#15400]
I asked on the gradle forum, but I think I need a dev to understand this:
https://discuss.gradle.org/t/difference-between-runtime-and-runtimeclasspath-configurations/38376

### Expected Behavior
When creating a new sourceset and creating a consumable configuration that extends from `<name>RuntimeClasspath`, and depending on it from another project, the compilation outputs become part of the classpath.

### Current Behavior
When I depend on the `runtimeClasspath` configuration, the compilation outputs of main are part of the classpath, but when I depend on the `<name>RuntimeClasspath` configuration of a custom sourceset `<name>`, the compilation outputs of that sourceset aren't available to the dependent.

Upon inspection, I found that even in that case the outputs of the main configuration become part of the classpath, which bewildered me even more.

### Context
I wanted to split up a module into multiple sourcesets so I can internally only depend on the ones I need.

### Steps to Reproduce 
Since this may be intended behavior in some way that I don't yet understand, I won't go through the effort to create a multi-module project just for this issue. If it is deemed necessary, I will of course supplement that.

**Comment by ljacomet** [comment]
There is a different between `configurations.runtimeClasspath` and `sourceSet.main.runtimeClasspath`.
The former only handles _dependencies_ while the later adds to that the output of the source set.

Note that `runtime` has been deprecated for a while and is no longer available in Gradle 7.

**Comment by ljacomet** [comment]
Closing as there is nothing to do in Gradle
