### ISSUE TITLE
Add way to opt in to performance mode for buildSrc compile avoidance

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#15412]
Looking at: https://docs.gradle.org/6.8-rc-1/release-notes.html#kotlin-dsl-script-compilation-improvements

We can leverage compilation avoidance for `*.gradle.kts` files. However, introducing an inline function would break this new feature. Can we get a flag to opt in a "performance" mode that would fail the build if an inline function is introduced?

Something like:

```kotlin
org.gradle.buildSrc.allowKotlinInline=false
```

And this would fail the build if a developer accidentally introduces an inline function. My concern is that it might be easy to accidentally break this performance enhancement without realizing it.

**Comment by ljacomet** [comment]
This is not something we would want to provide. Instead we would aim for support inline functions - either by doing it in Gradle or by having the Kotlin compiler do it right.
