### ISSUE TITLE
Make sure 'plugins {}' and 'pluginManagement {}' blocks are supported in pre-compiled settings script plugins - Kotlin DSL and Groovy DSL

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#15416]
This is only about ***.settings.gradle(.kts)** plugins.

At the moment we seem to have this (weird) situation:

Kotlin DSL:
- `plugins` - does **not work** :x:
- `pluginManagement` - does **work** :white_check_mark: 

Groovy DSL:
- `plugins` - does **work** :white_check_mark:
- `pluginManagement` - does **not work**  :x:

**Comment by rieske** [comment]
The only remaining inconsistency to fix for this issue is to make precompiled Kotlin settings plugins support the plugins {} block.
This is a test that needs to pass: https://github.com/gradle/gradle/pull/17235

**Comment by jjohannes** [comment]
Done through #16625 and #17240.

**Comment by rieske** [comment]
This is the follow-up for fixing the version handling with graceful and informative failures: https://github.com/gradle/gradle/issues/17246
