### ISSUE TITLE
ProviderFactory is not accessible in included build's settings script

### ISSUE THREAD

**Issue by AlessandroOddone** [gradle/gradle#15425]
This issue is analogous to https://github.com/gradle/gradle/issues/14465, but in the context of an included build's settings script.

### Expected Behavior
`getProviders` can be called from the settings script of an included build to obtain `ProviderFactory`.

### Current Behavior
Attempting to call `getProviders` from the settings script of an included build produces the following error:
```
A problem occurred evaluating settings 'includedBuild'.
> Could not get unknown property 'providers' for settings 'includedBuild' of type org.gradle.initialization.DefaultSettings.
```

### Context
I found this issue during an attempt to update, in a large project that is set up as a composite build, a number of settings scripts to be configuration caching-ready. These settings scripts are currently reading environment variables and external files.
 
### Steps to Reproduce 
Self-contained reproducer: https://github.com/AlessandroOddone/providers-issue-reproducer

`settings.gradle` in the `includedBuild` module from the sample repo above reproduces the issue.

I was able to reproduce the issue on the following Gradle versions:
- 6.8-rc-1
- 6.8-20201203115311+0000
- 6.9 20201202230031+0000

**Comment by grossws** [comment]
Still relevant afaict

**Comment by mlopatkin** [comment]
This issue can no longer be reproduced with the provided reproducer, even with Gradle 6.8-rc-1. Please comment here or file a new issue if the problem persists with the newer versions of Gradle.
