### ISSUE TITLE
Incomplete support for junit5 reporting of cucumber

### ISSUE THREAD

**Issue by Darkvater** [gradle/gradle#15435]
See https://github.com/cucumber/cucumber-jvm/issues/2176

As commented on by Cucumber Dev:
> Depending on the location of the feature file Cucumber provides the JUnit 5 with either a ClasspathResourceSource, FileSource, or UriSource. Currently Gradle does not support tests that do not have a ClassSource and we can not provide JUnit 5 with a ClassSource for obvious reasons.
>
> I would suggest that you file an issue with Gradle. It may be worth pointing out that the reports generated by maven appear to behave correctly.

**Describe the bug**
The juniper junit platform runner / test reporter is not passing the class names to the output, marking all as "`UnknownClass`". This is troublesome as feature files with the same scenario name, or any scenario outline is incorrectly reported. They are all run but in the test-reports file that is being used by IntelliJ for example the test counts are incorrect as well as difficult for a user to find which test was broken. Many just say "`UnknownClass.Example #1`"

**To Reproduce**
1. Clone repository https://github.com/bonigarcia/mastering-junit5/tree/master/junit5-cucumber
2. update the cucumber version to 6.9.0 (although 6.6.1 in the example repo behaves the same)
3. run the tests using gradle `./gradlew clean test` output:
```
org.junit.platform.launcher.core.LauncherConfigurationParameters fromClasspathResource
INFO: Loading JUnit Platform configuration parameters from classpath resource [file:/.../resources/test/junit-platform.properties]
UnknownClass.Addition STANDARD_OUT

     Scenario: Addition                         # iogithub/bonigarcia/calculator.feature:6
      Given a calculator I just turned on       # io.github.bonigarcia.CalculatorSteps.setup()
      When I add 4 and 5                        # io.github.bonigarcia.CalculatorSteps.add(int,int)
 ...
 UnknownClass.Addition PASSED
 ...
    Scenario Outline: Several additions         # iogithub/bonigarcia/calculator.feature:20
      Given a calculator I just turned on       # io.github.bonigarcia.CalculatorSteps.setup()
      When I add 1 and 2                        # io.github.bonigarcia.CalculatorSteps.add(int,int)
 ...
 UnknownClass.Example #1 PASSED
     Scenario Outline: Several additions        # iogithub/bonigarcia/calculator.feature:21
      Given a calculator I just turned on       # io.github.bonigarcia.CalculatorSteps.setup()
      When I add 3 and 7                        # io.github.bonigarcia.CalculatorSteps.add(int,int)

 UnknownClass.Example #2 PASSED
```

**Expected behaviour**
Expecting to be able to see all class names as normal. For example running the same tests using JUnit4 results in (how to setup is detailed in #2175:
```
io.github.bonigarcia.CucumberTest > Basic Arithmetic.Addition STANDARD_OUT

   Scenario: Addition                          # iogithub/bonigarcia/calculator.feature:6
     Given a calculator I just turned on       # io.github.bonigarcia.CalculatorSteps.setup()
     When I add 4 and 5                        # io.github.bonigarcia.CalculatorSteps.add(int,int)
...
io.github.bonigarcia.CucumberTest > Basic Arithmetic.Addition PASSED
```

**Context & Motivation**
Upgrading to JUnit5 using ```cucumber-junit-platform-engine``` is not usable for test reporting and we will have downgrade cucumber to JUnit4. 
* Our teamcity tests results now report 509 tests instead of 550 as it counts duplicate entries in `build/test-results/test/TEST-...xml` as one. All entries with names `<testcase name="Example #1" classname="UnknownClass" time=".."/>` are collapsed into one.
* Failed tests simply say "`UnknownClass.Example #1`" which makes it impossible to find out which test has failed
* Failed tests where the same scenario template iteration has failed "override" each other, hiding other failing tests.

**Your Environment**
 - Versions used: Cucumber 6.9.0
 - Operating System and version: N/A
 - Build tool: Gradle 6.6.1, but same on Gradle 5.6.1

**Comment by ljacomet** [comment]
Might be resolved in the future by the work done on #5975 
@melix Could you check?
