### ISSUE TITLE
BuildListener added by a plugin is never called

### ISSUE THREAD

**Issue by v1nc3n4** [gradle/gradle#15434]
Hi,

It seems build listeners registered by a plugin are never called.

### Expected Behavior

In the main class of a plugin, I added the following code expecting it would trigger the corresponding listener in case of events:
```java
public void apply(final Project project) {
    // Either the first method call or the second one is applied of course.
    // But I want to highlight that none of the 2 methods allows to trigger the listener at the end of the build.
    project.getGradle().addBuildListener(new CustomBuildAdapter());
    project.getGradle().addListener(new CustomBuildAdapter());
    // ...
}

public CustomBuildAdapter extends BuildAdapter {
    @Override
    public void buildFinished(final BuildResult result) {
        // Do something when the build is finished.
    }
}
```

### Current Behavior
Unfortunately, it does not work, the listener is never called. I tried to debug with a breakpoint at the beginning of the `buildFinished` method, and it was never hit.

### Context
I need to do some cleanup in a plugin at the end of builds. So I tried to register a build listener (listening for the `buildFinished` event, but it is never called by Gradle at the end of the build.

### Your Environment
Gradle: 6.7.1
O/S: Windows 10 Pro 64 bits
JDK: OpenJDK 11

What am I doing wrong or misunderstanding?
Thanks in advance for your help!
Regards

**Comment by donat** [comment]
Hi! I've tried to reproduce your problem in a sample plugin but the listeners work as expected. Can you please provide a minimal sample project and the steps to reproduce the issue?

**Comment by donat** [comment]
Closing as inactive.
