### ISSUE TITLE
com.gradle.plugin-publish has no documentation on how to setup signing

### ISSUE THREAD

**Issue by sdavids** [gradle/gradle#15441]
There is no documentation on how to setup/configure signing.

### Expected Behavior

https://plugins.gradle.org/docs/publish-plugin

has been updated with a new "signing example" or the "full example" includes the signing config as well.

### Current Behavior

https://plugins.gradle.org/docs/publish-plugin

Does not mention how to configure signing.

### Context

https://plugins.gradle.org/plugin/com.gradle.plugin-publish

> Version 0.12.0 (latest)
> Created 26 May 2020.
>
> - Add support for publishing signatures and checksums for plugins

**Comment by bigdaz** [comment]
Pending a documentation update, this plugin provides a working example of signing together with `plugin-publish`:
https://github.com/gradle/gradle-enterprise-build-config-samples/blob/master/common-custom-user-data-gradle-plugin/build.gradle#L45
