### ISSUE TITLE
Deadlock situation with Android lint task and Gradle 6.8-RC1

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#15449]
Happens during parallel task execution.

### Expected Behavior

No deadlock.

### Current Behavior

With several lint tasks executing concurrently:
```
:apps:a:features:b:c:lintDebug
:apps:a:features:b:c:lintRelease
:apps:a:features:b:d:lintDebug
```

With AGP 4.1.1 and Gradle 6.8-RC1 the Gradle daemon hangs.
See thread dump at https://gist.github.com/eskatos/729c23b99e1febcb0b3703de547afa4c

### Context

https://gradle.slack.com/archives/C7R6T1XGS/p1607000837140600

**Comment by adammurdoch** [comment]
Potential fix via https://github.com/gradle/gradle/pull/15457
