### ISSUE TITLE
Project is not using NDK, but not-correctly configuring  ANDROID_NDK_HOME, NPE raised by Gradle

### ISSUE THREAD

**Issue by dreaminplus** [gradle/gradle#1545]
### Expected Behavior
BUILD SUCCESSFULE

### Current Behavior
NPE raised

### Context
If ANDROID_NDK_HOME configured or ndk.dir configured, Gradle will use ndk to strip the debug symbols from native libraries...
Here I think, as a tooler, you should not do this by default.
(com.android.build.gradle.internal.ndk.DefaultNdkInfo.java)
 `            for(File platform : platformSubDirs) {` this line raises NPE. because of platformSubDirs is null)

### Steps to Reproduce (for bugs)
ANDROID_NDK_HOME 's directory is wrong... but my project is not using NDK.
So I think this should not interrupt the compiling procedure..

### Your Environment
Win7
Gradle 2.14.1

**Comment by bmuschko** [comment]
This issue is better suited to be raised on the forum for the Android plugin which is developed by Google. Could you please open an issue there? I am sure they are happy to help and have a much deeper insight into the behavior of their plugin.
