### ISSUE TITLE
Allow 3P plugin authors to contribute information to build scan

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#15456]
I still think #9500 and #9499 would be very helpful.

**Comment by ldaley** [comment]
@SUPERCILEX deprecations in particular are something we are working towards and we have general plans on allowing more interesting diagnostic information to be expressed, by Gradle itself and plugins. These are too rudimentary at this stage to share more details, but keep an eye out.

**Comment by SUPERCILEX** [comment]
That sounds awesome!

**Comment by SUPERCILEX** [comment]
Closing old issues.
