### ISSUE TITLE
compileJava fingerprint should take full version into account

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#15464]
### Expected Behavior

`compileJava` should be re-executed even if the only change is javac 1.8.0u152 vs 1.8.0u222.

Different javac versions might have different **bugs**, so caching the results is not really valid.
1.8.0u152 is known to have multiple bugs in the area of annotations, and the bugs look like "javac produces invalid bytecode and completes successfully"

### Current Behavior

Gradle reuses the build cache when JAVA_HOME alternates between `jdk1.8.0_152.jdk` and `adoptopenjdk-8-222.jdk`

### Context

It breaks Apache Calcite builds in an unexpected way.
The build fails for the developers even after they upgrade Java since Gradle reuses class files produced by the old (and buggy) `javac`.

### Steps to Reproduce 

`javac` bugs are not trivial to reproduce, however, the following command reproduces the issue `./gradlew :plus:compileJava :plus:forbiddenApisMain` in https://github.com/apache/calcite/commit/404f968f6079360621896e6ee20ec12488a40bc2

### Your Environment
Build scan URL: https://scans.gradle.com/s/s4g2xytyreqbu

The build scan is for 1.8.0u222 which should work without the build cache, yet it fails.

Here's a build scan with `--rerun-tasks` which succeeds: https://gradle.com/s/hkt5seq72zsai

**Comment by vlsi** [comment]
The following might be relevant: https://github.com/gradle/gradle/issues/9301

Just in case you wonder, here are the values from AdoptopenJDK 222:

```
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.8.0_222-b10
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = AdoptOpenJDK
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_222
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = AdoptOpenJDK
    java.vm.version = 25.222-b10
```

Oracle 1.8u152

```
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 1.8.0_152-b16
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_152
    java.vm.info = mixed mode
    java.vm.name = Java HotSpot(TM) 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.152-b16
```

Liberica 15

```
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 15.0.1+9
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 15
    java.vendor = BellSoft
    java.vendor.url = https://bell-sw.com/
    java.vendor.url.bug = https://bell-sw.com/support
    java.version = 15.0.1
    java.version.date = 2020-10-20
    java.vm.compressedOopsMode = Zero based
    java.vm.info = mixed mode, sharing
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 15
    java.vm.vendor = BellSoft
    java.vm.version = 15.0.1+9
```

**Comment by vlsi** [comment]
Sample known issues with old Java 1.8: https://github.com/policeman-tools/forbidden-apis/issues/173#issuecomment-685512769

**Comment by ljacomet** [comment]
Hey @vlsi,

Thanks for the report. This has been the topic of many discussions internally when developing caching, toolchains and anything that touches the Java used for compilation and friends.

The team believes that only tracking the major version is the right balance for most users.
As [documented](https://docs.gradle.org/6.8-rc-1/userguide/common_caching_problems.html#java_version_tracking), build authors can easily track the full version if they need to.

There is no plan to revisit this decision at this time.
