### ISSUE TITLE
Document example of a composite build interacting with a multi module build

### ISSUE THREAD

**Issue by asaikali** [gradle/gradle#15493]
The documentation at https://docs.gradle.org/release-nightly/userguide/composite_builds.html#composite_build_executing_tasks does not explain how to interact with an included build that is a mulit module build. Consider something along the lines.

```
.
├── build.gradle.kts
├── components
│   ├── blob
│   ├── build.gradle.kts
│   ├── database
│   ├── email
│   ├── security
│   ├── settings.gradle.kts
│   ├── template
│   └── util
├── docker-compose.yml
├── gradle
│   └── wrapper
├── gradle.properties
├── gradlew
├── gradlew.bat
├── platforms
│   ├── boot-platform
│   ├── settings.gradle.kts
│   └── test-platform
├── plugins
│   ├── conventions
│   └── settings.gradle.kts
├── settings.gradle.kts
└── fooapp
    ├── Dockerfile
    ├── api
    ├── build
    ├── build.gradle.kts
    ├── settings.gradle.kts
    └── ui
```

*components* is a multi module build, and *fooapp* is a multi module build. if you try something like `./gradlew :components:database:build` it builds the database project but if you try `./gradlew :components:build` wanting to build all the modules in the component project it runs the `buildEnviroment` task if you try `./gradlew :components:assemble` it errors out saying assemble is not defined on the project if you try ` ./gradlew -p components  build` it works. This is very confusing behavior it would be nice to document it in the docs, and explain why it happens.

**Comment by jjohannes** [comment]
Starting with Gradle 6.8, it is now possible to address tasks in included builds. See: 
https://docs.gradle.org/current/userguide/composite_builds.html#composite_build_executing_tasks

More documentation and sample for structuring large builds are also available:
- https://docs.gradle.org/current/userguide/structuring_software_products.html
- https://docs.gradle.org/current/samples/sample_structuring_software_projects.html
