### ISSUE TITLE
Remove `IncrementalTaskInputs`

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#15496]
### Summary
Follow up after https://github.com/gradle/gradle/issues/9048

### Checklist
- [x] Validate whether we should remove the API in the 8.0 release
- [x] Update the upgrade guide (https://github.com/gradle/gradle/pull/21472)
- [x] Check User Manual for dangling references and outdated documentation (https://github.com/gradle/gradle/pull/21472)
- [x] Remove IncrementalTaskInputs from the code (https://github.com/gradle/gradle/pull/21481)

-----
/cc @gradle/execution

**Comment by asodja** [comment]
Removed for Gradle 8.
