### ISSUE TITLE
Trigger installation of gradle-completion

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1550]
Goal is to streamline integration of gradle-completion

### Expected Behavior
Prompt user to install [gradle-completion](https://github.com/gradle/gradle-completion) upon some action that indicates they would be interested in it. For example, have the Gradle wrapper ask user to install completion when the wrapper task is invoked on bash or zsh in an interactive terminal. 

### Current Behavior
There is no integration with gradle-completion currently

### Context
[gradle-completion](https://github.com/gradle/gradle-completion) is now an official project. We should consider indirect integration for now.

**Comment by vpavic** [comment]
Could this be reconsidered, especially now that gradle-completion project is apparently [active again](https://github.com/gradle/gradle-completion/releases/tag/v1.5.0)?

I'm not sure how many users are aware of gradle-completion at all, but it's a very helpful utility and its integration into the build tool would certainly help with discoverability and make a lot installation easier.
