### ISSUE TITLE
Remove deprecated methods from IdeaContentRoot

### ISSUE THREAD

**Issue by donat** [gradle/gradle#15512]
### Summary
Methods to remove:
org.gradle.tooling.model.idea.IdeaContentRoot.getGeneratedSourceDirectories()
org.gradle.tooling.model.idea.IdeaContentRoot.getGeneratedTestDirectories()

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [x] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

**Comment by jjohannes** [comment]
Fixed #15513
