### ISSUE TITLE
Multiple transformed artifacts selected

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#15536]
Using [duplicates.zip](https://github.com/gradle/gradle/files/5685454/duplicates.zip) project and running `./gradlew :app:mergeExtDexDebugAndroidTest :app:mergeExtDexDebug` (it is important to run tasks in the same Gradle invocation) fails with Gradle 6.7+ because `debug` runtime classpath contains unexpected artifacts. This succeeds with Gradle 6.6.1.

When building `debugAndroidTest` variant, we do the following:
- resolve `debugAndroidTest` runtime classpath with `artifactType=android-dex`, this is `A`
- resolve `debug` runtime classpath with `artifactType=android-dex`, this is `B`
- final result is all files in `A` that are not found in `B` (this is needed in order to avoid duplicate classes in test and main APK)

Because desugaring is enabled, some artifacts e.g `lifecycle-livedata-core-2.2.0` will be dexed twice. Two output artifacts will be produced, as dependency graphs for `debug` and `debugAndroidTest` differ. However, this should only result in having `lifecycle-livedata-core-2.2.0` DEX in both APKs, and it should not result in having these two versions in the `debug` runtime classpath.

Workarounds include:
- running tasks in separate Gradle invocations
- disabling dex desugaring by increasing `minSdkVersion` in `app/build.gradle` to 24+

**Comment by adammurdoch** [comment]
Should be fixed now via https://github.com/gradle/gradle/pull/15637

**Comment by manask88** [comment]
@adammurdoch , thanks for fixing this bug. I'm wondering if it would be possible to cherry pick this into 6.8 . In case it cannot be cherry picked, wondering when will the next RC be cut. Thanks!

**Comment by benjaminRomano** [comment]
+1 to cherrypicking into 6.8. For us, upgrading to 7.0 is going to take a while as we need to audit and update all our gradle plugins to remove usages of deprecated features.

**Comment by Onlinedispatcher** [comment]
Same here, please backport

**Comment by davidburstromspotify** [comment]
We also ran into this issue just now. We'd also appreciate a backport, if possible.

**Comment by alaershov** [comment]
Also seeing this in production, please backport this to 6.8.
7.0 is pretty far, and all plugins supporting it is even further. We have some workarounds:

1. don't build two APKs in the same Gradle command
2. ```tasks.named('mergeExtDexDebugAndroidTest').configure {
        mustRunAfter tasks.named('mergeExtDexDebug')
    }```

**Comment by opatry** [comment]
I can reproduce with 6.8.3 (seems ok on 7.0 RC2 + AGP `7.0.0-alpha09`) (my repro project if it can help https://github.com/opatry/desugaring-issue)

Do you confirm it's not part of 6.8?

Can't make @alaershov's 2nd suggestion work though :(

**Comment by archfz** [comment]
I have wasted simply too much time on this. If anyone else searching for this and wondering where @alaershov's 2nd suggestion should be placed, see here https://github.com/alaershov/android-merge-ext-dex-bug-sample/blob/master/app/build.gradle#L75

Or more specifically add at the end in `app/build.gradle` the following:

```gradle
// @TODO: See https://github.com/gradle/gradle/issues/15536
gradle.projectsEvaluated {
    tasks.named('mergeExtDexDebug').configure {
        mustRunAfter tasks.named('mergeExtDexDebugAndroidTest')
    }
}
```

**Comment by archfz** [comment]
Actually the fix is not working consistently for me, we do have both build debug and release for android test, on pipeline it's stiff failing and I am having a very difficult time understanding the issue. That is why I opted to cherry pick the fix from 7.x, lets hope gradle team releases it soon into 6.x
