### ISSUE TITLE
Add GraalVM as a JvmVendor

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#15535]
### Expected Behavior

Developers that use the new [JVM toolchain selection](https://docs.gradle.org/6.8/userguide/toolchains.html) feature might want to explicitly choose GraalVM for it's [polyglot features](https://www.graalvm.org/reference-manual/embed-languages/), and thus should be able to specify it to be the chosen JVM. While `ORACLE` will be supported as a [JvmVendorSpec](https://docs.gradle.org/6.8-rc-1/javadoc/org/gradle/jvm/toolchain/JvmVendorSpec.html) in Gradle 6.8, there is no `GRAAL_VM` value in [JvmImplementation](https://docs.gradle.org/6.8-rc-1/javadoc/org/gradle/jvm/toolchain/JvmImplementation.html), which would be the expectation.

### Current Behavior

There is no way to explicitly choose GraalVM as the JVM toolchain.

### Context

I'm trying to ensure in a Gradle build that GraalVM is used so its [polyglot features](https://www.graalvm.org/reference-manual/embed-languages/) can be used.

**Comment by fizzkwik** [comment]
FYI, as a work-around; the vendor for my GraalVM JDK is `GraalVM Community`, not Oracle, so you can use `JvmVendorSpec.matches("GraalVM Community")`.

**Comment by sschuberth** [comment]
It occurred to me that modifications to `JvmImplementation` should not be needed, as the "GraalVM Community" vendor only offers a single JVM Implementation, so there is no need to distinguish further here. I've implemented the trivial `JvmVendor` additions in PR #16595.
