### ISSUE TITLE
Configuration.copy improvement proposal

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#1555]
Our resolution rules plugin uses `copyRecursive` in an `incoming.beforeResolve` block for each configuration when processing [alignment rules](https://github.com/nebula-plugins/gradle-resolution-rules-plugin/wiki/Dependency-Rule-Types#align).

We've run into a some correctness and ergonomic issues with `copy` that have lead us to use reflection and other hackiness to workaround. We've run into API changes in the latest nightlies with those hacks (`CollectionEventRegister` is now an interface, so older builds of the plugin fail with an `IncompatibleClassChangeError`):

https://github.com/nebula-plugins/gradle-resolution-rules-plugin/blob/master/src/main/kotlin/nebula/plugin/resolutionrules/configurations.kt

To avoid us maintaining this code moving forward, I wanted to run some improvements by you, that we can then send you a pull request for.

## When configuration to be copied is on the configuration container, process add handlers

Resolution strategies are often applied through `configurations.all`, and we want the copied configuration to resolve identically to the source configuration.

It's not possible to add the configuration ourselves to the configuration container, because dependency resolution may be happening on code that iterates the container, and results in a `ConcurrentModificationException` leading us to resort to reflection.

`copy` should include add handlers, if the source configuration is on the configuration container.

## Allow the configuration name to be specified

Alignment is a multi-step process, so we want to provide context by naming the configuration descriptively. 

`copy` should allow the destination configuration name to be specified.

**Comment by DanielThomas** [comment]
@bmuschko note there's also a bug documented here, let me know if we should split that out.

**Comment by bmuschko** [comment]
@DanielThomas Yeah, if you have a separate bug then please file a new issue for it. The smaller the chunks, the better. Thanks!

**Comment by DanielThomas** [comment]
@bmuschko @oehme we're run into a problem with this again with the `DisplayName` optimization on Gradle 4.0. Any opinions about this before I get you a PR? 

Incidentally, the issue I broke out https://github.com/gradle/gradle/issues/1638 is tagged as a question, pretty sure that's a bug. Have a reduced, reproducible use case there.

**Comment by oehme** [comment]
@DanielThomas I'm wondering if we should take this into a completely different direction. Copying configurations is a very costly workaround for the fact that you are missing a hook in our dependency resolution engine. It seems you (and other plugins) need something to control version selection and conflict resolution, with possible respins managed by Gradle.

That being said, we could of course fix some of the issues around copying in the short term (and your proposals sound reasonable to me) and deprecate the whole concept later.

**Comment by bigdaz** [comment]
We're making progress on new features that should reduce/eliminate the need to copy and resolve configurations. But as Stefan mentioned:
> That being said, we could of course fix some of the issues around copying in the short term (and your proposals sound reasonable to me) and deprecate the whole concept later.

@DanielThomas Do you still want to provide a PR for this improvement? If so please comment here and I'll reopen the issue.

**Comment by DanielThomas** [comment]
@bigdaz improvements here still wouldn't help with the other hoops we have to jump through to implement version alignment in a resolution strategy. We'll stick with pursuing core features to replace our plugins.

**Comment by bigdaz** [comment]
@DanielThomas roger that
