### ISSUE TITLE
Remove deprecated work validation failures

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#15552]
### Summary

In Gradle 7.0 we will start failing the build for a number of validation failures that were previously reported as deprecations.

List of validations to be converted TBD.

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [ ] Update the upgrade guide
- [ ] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

**Comment by wolfs** [comment]
Fixed via #16401.
