### ISSUE TITLE
Unable to have "tar" in Project Name.

### ISSUE THREAD

**Issue by butItsMyFirstday** [gradle/gradle#1556]
Unable to have tar in Project name.
Project name is "StartIt"
gradle created tar file is StartIt.tar
untar I get "It.tar" 

### Expected Behavior

Expected to get project name when project is untar. 

### Current Behavior

When gradle tars a project it strips the first "tar"  it sees instead of stripping ".tar" at the end.
Produced tar file looks fine but folder inside has the first tar stripped out.
As long as you don't have "tar" in the name it works great.

### Context

I upgraded from 1.12 to 3.4.1.

### Steps to Reproduce (for bugs)

Create a project with the word tar in it.  "StartIt"
Build it with gradle and look inside created tar file.  

 

### Your Environment

 * Build scan URL: 
java

**Comment by bmuschko** [comment]
Please provide a sample project on GitHub that reproduces the issue.

**Comment by big-guy** [comment]
The way we stripped the extension from the archive path wasn't converted from Groovy correctly:
https://github.com/gradle/gradle/blob/ae786d81ea7bb58420f2fb31df6500a24e9e84b0/subprojects/plugins/src/main/java/org/gradle/api/distribution/plugins/DistributionPlugin.java#L116-L118

I added a test to reproduce it and just fixed it in https://github.com/gradle/gradle/commit/62814d9b5d4829a2026a10fa5b37565dc0f5899f
