### ISSUE TITLE
Make FailureResolutionAware usable for users & plugin developers

### ISSUE THREAD

**Issue by andreas-schilling** [gradle/gradle#1558]
The interface `FailureResolutionAware` allows Exceptions implementing it to supply further information to the `BuildExceptionReporter` such that the `Try:` part of the failure output contains detailed guidance for the user on how to solve the problem. This interface is currently only available for internal usage by core Gradle plugins.

### Expected Behavior
Make the interface consumable for any (plugin) developer such that it could also be promoted as a best practice to supply problem solutions to the user if they are derivable from the error that occurred.

The new output could look like this:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'path/to/my/project/build.gradle' line: 123

* What went wrong:
Execution failed for task ':theAwesomePreprocessor'.
> Input file is malformed

* Try:
The AWESOMEPREPROCESSOR expects each input file to contain definitions of A and B, you only supplied A. Add B as well (Line 1024).
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

### Current Behavior
Currently error details and user guidance can only be supplied through the error message which then will be displayed in the `What went wrong` section. While this is no problem as such, being able to provide additional details to the `Try:` part has several advantages:
- Most users probably read a failure in their output window bottom up from the `BUILD FAILED` message. First thing that appears is the `Try:` section that contains per default information on how to print a stacktrace or enable a more verbose build. If more detail would be provided here, the user is less likely to possibly miss that detail when it is shown in the `What went wrong:` section
- Strictly speaking putting a possible solution into the `What went wrong` section is not correct. May be nitpicking, but consistency is always great.
- Through `FailureResolutionAware` it is possible to supply further formatting to the output which can also enhance the user experience further.
- It might motivate (plugin) developers even more to supply detailed failure information when it is easy to do so

### Context
I often have additional support tasks inside builds that allow developers to automate tasks that are not strictly part of the build (e.g. preprocessing files, performing scaffolding runs, validating something, etc.) As in these cases there's always more user input than for "regular" build steps there are also more ways in which the task can fail. Being able to supply further guidance would be great here.

Even more so the feature would be of use for plugin developers, allowing community plugins to provide guidance in error cases in the same way as some internal plugins already do.

There are two main ways in which I personally would like to use that feature:
- Either have some new exception type implementing `FailureResolutionAware` that provides a default implementation and takes a simple (optional) `String solution` message which then will be shown in the `Try:` section. Possibly also the `GradleException` can directly implement the interfance and then take the optional parameter. This would be useful for cases where the solution help is short and does not need elaborate formatting.
- For all other cases I just would like to be able to have my own exception type implement the interface and fully implement `appendResolution` to supply as much detail as necessary in any formatting I like. Then the `BuildExceptionReporter` will just detect the interface and pick it up accordingly.

### Your Environment
Any.

**Comment by bmuschko** [comment]
Thanks for creating the issue. Are you interested in contributing a pull request for this?

**Comment by andreas-schilling** [comment]
In general absolutely, however I have to see how much time I can actually find to get into this. No that easy right now for several private and work-related reasons.
But I'll definitely try to work on this soonish! As it's "just" some enhancement I believe we're not on a schedule here ;-)
