### ISSUE TITLE
Artifact tranformation API: Support Kotlin "Commonizer" use case

### ISSUE THREAD

**Issue by sellmair** [gradle/gradle#15587]
The Commonizer is a transformation of `n -> m` artifacts. It takes serval platform "cinterop" libraries and pulls common declarations from those into a new artifact. 

Currently there are several issues preventing us from implementing this as `TransformAction`: 

_____

**API only supports `1 -> n` transformations** 
- Can be mitigated by creating/bundling all n-inputs into a new artifact (but might not the ideal solution) ☑️

_____

**API does not allow to transform from _missing attribute_ to _{some attribute value}**
- Can be mitigated by creating synthetic "none" attribute values ☑️
_____

**Commonizer classpath needs to be resolved when necessary**

- Cannot be done while registering the transformation, because the configuration of this transformation is not lazy. Users that do not rely on any commonization would still have to resolve the classpath.

- Cannot be done during transformation, because we do not see any way of getting a `Project` reference during transformation
_____

Why not passing a project reference into the `TransformAction`?:
_Will definitely break caching a transformation on a given artifact across project boundaries_

Why not configuring transform actions lazily?
1. Could pave the way for fishy code where heavy lifting could be done during configuration and only references to the results are passed as parameters. 
2. Gradle still needs the `from` and `to` parts of configuration to investigate which transform chain would have to run! Just making the configuration of the action lazy will not really help.

Idea: One make the configuration of parameters lazy. Commonizer could resolve the classpath there and only there if it is really necessary.

**Comment by sellmair** [comment]
Regarding laziness of configuration:
- Configuring the TransformSpec would ideally be lazy until Gradle tries to really resolve dependencies
- Configuring parameters would ideally be lazy until the transformation has to run

**Comment by jjohannes** [comment]
I am not sure what you mead by TransformSpec being not lazy. 

You can define your own parameter interface and the properties on it can be (and should be) lazy. Like here for example:

https://github.com/gradle/gradle/blob/master/build-logic/packaging/src/main/kotlin/gradlebuild/shade/transforms/ShadeClasses.kt#L55-L64

**Comment by sellmair** [comment]
I mean 
```
dependencies { 
    registerTransform(...) {
        // not lazy
        // should maybe be lazy until dependencies are really resolved
        parameters {
            // not lazy
            // should maybe be lazy until transformation is really necessary 
        }
    }
}
```

**Comment by jjohannes** [comment]
Can you explain, why you cannot pass the "Commonizer classpath", and the information if it is need or not, into lazy properties of the parameters? Such things should be done be done like this:

```
   parameters {
      myClasspath.from(...) // This is of type ConfigurableFileCollection
      needsToDoWork.set(...) // This is of type Property<Boolean>
   }
```

This is effectively *Configuring parameters are lazy until the transformation runs*

See the sample I already linked above. Here the parameters are lazily evaluated only when they are needed:
https://github.com/gradle/gradle/blob/master/build-logic/packaging/src/main/kotlin/gradlebuild/shade/transforms/ShadeClasses.kt#L77

**Comment by sellmair** [comment]
I tried this with `FileCollection` and `Provider`s. However both of them cannot be isolated.
```
Could not determine the dependencies of task ':p2:compileNativeMainKotlinMetadata'.
> Could not resolve all artifacts for configuration ':p2:allSourceSetsCompileDependenciesMetadata'.
   > Failed to transform libcurl-7.64.1-kib0.kib (io.sellmair:libcurl:7.64.1-kib0) to match attributes {artifactType=org.jetbrains.kotlin.klib, commonizer-target=[linux_x64, macos_x64], org.gradle.status=release, org.gradle.usage=kotlin-api}.
      > Could not isolate parameters org.jetbrains.kotlin.gradle.ib.InteropBundleCommonizerTransformation$Parameters_Decorated@4d0eae4b of artifact transform InteropBundleCommonizerTransformation
         > Could not isolate value org.jetbrains.kotlin.gradle.ib.InteropBundleCommonizerTransformation$Parameters_Decorated@4d0eae4b of type InteropBundleCommonizerTransformation.Parameters
            > Could not serialize value of type InteropBundleCommonizerTransformation.Parameters

```

**Comment by jjohannes** [comment]
Can you share what is different to the sample above - https://github.com/gradle/gradle/blob/master/build-logic/packaging/src/main/kotlin/gradlebuild/shade/transforms/ShadeClasses.kt#L55-L64

Ideally a full reproduced.

**Comment by sellmair** [comment]
Thanks for the help. 
This issue is no longer necessary!
