### ISSUE TITLE
Remove deprecated org.gradle.logging.LoggingManagerInternal

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#15599]
### Summary

- org.gradle.internal.logging.LoggingManagerInternal

See how it goes and consider getting rid of the types and patch the bytecode or generate placeholder types to let plugins compiled against past API work.

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [x] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

**Comment by jjohannes** [comment]
Done: #15767
