### ISSUE TITLE
Multi-project build: Import child projects recursively

### ISSUE THREAD

**Issue by itssven** [gradle/gradle#1559]
### Expected Behavior

If a new sub-project is generated, there is no need for a change in setting.gradle in root project, gradle scans the root project-folder for further sub-projects

### Current Behavior

Currently you need to add the sub-project and all further sub-sub-projects to the root settings.gradle this is inconvenient, and hard to maintain and error prone in large projects with many sub- and sub-sub*-projects.

### Context

root-project
- settings.gradle
- sub-project
-- sub-project
--- sub-project 
- sub-project
- sub-project
-- sub-project
-- sub-project
-- sub-project
--- sub-project 
--- sub-project

**Comment by bmuschko** [comment]
This looks like a question rather than an issue. Can you please open a post on the Gradle forum?

**Comment by schulz-m** [comment]
This seems to me like a feature request - is there any movement on this where one can vote for or contribute?
