### ISSUE TITLE
Wrong file passed as input to artifact transform in 6.8

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#15604]
In Gradle `6.8-rc-1`, using [local_aar.zip](https://github.com/gradle/gradle/files/5703318/local_aar.zip) project and running:

```
cd copy_LocalAarProject && GRADLE_USER_HOME=../tmp ./gradlew assembleDeb
cd .. && rm -rf copy_LocalAarProject
cd LocalAarProject && GRADLE_USER_HOME=../tmp ./gradlew assembleDeb
```

fails with
```
Execution failed for ExtractAarTransform: /home/gavra/AndroidStudioProjects/local_aar/copy_LocalAarProject/app/libs/lib1-1.0.aar.
         > /home/gavra/AndroidStudioProjects/local_aar/copy_LocalAarProject/app/libs/lib1-1.0.aar (No such file or directory)
```

If the second run is w/o a daemon, everything works i.e `cd LocalAarProject && GRADLE_USER_HOME=../tmp ./gradlew --no-daemon assembleDeb` succeeds.

This is most likely related changes in 6.8 which cause daemon to maintain more in-memory state about transformed artifacts.

**Comment by wolfs** [comment]
Fixed via #15610.
