### ISSUE TITLE
Must do before 7.0 release

### ISSUE THREAD

**Issue by melix** [gradle/gradle#15606]
## Context

This issue summarizes miscellaneous things that we **must** fix before releasing 7.0. In particular, some removals, some behavioral changes may imply temporarily disabling tests, things to document, commits to revert, etc... If you have such things, either create an issue for them and assign them to the 7.0-rc-1 milestone, or list them here with a checkbox:

## Must-dos

- ~Make sure a compatible version of the [Spring Boot plugin is released](https://github.com/spring-projects/spring-boot/issues/24526)~
  - This is not necessary before 7.0 anymore because we decided to keep the (empty) MavenPlugin class for now  
- ~Make sure a compatible version of the [Shadow plugin is released](https://github.com/johnrengelman/shadow/pull/624)~
  - This is not necessary before 7.0 anymore because we decided to keep the (empty) MavenPlugin class for now  
- ❓  Publish the binary compatibility report
- ❓ Make it easier to publish a distribution (see org/gradle/api/plugins/DistributionPluginIntegrationTest.groovy)
- [x] Provide a version of the Gradle Plugin Publish Plugin which works without the MavenPlugin
- [x] Double check that we have no unused dependencies in the distribution. Because of some larger removals, some may not be necessary anymore.
  - Would be great to also check the code base for unused classes and methods
  - Can we use some tool for this?
- [x] Double check incubation report
- [x] Remove `DeprecationLogger.willBeRemovedInGradle7` and `DeprecationLogger.willBecomeAnErrorInGradle7` make sure all usages are gone.
   - We may add corresponding methods for Gradle 9 right away
- ~Double check remaining `@Deprecated` annotations in production code~

**Comment by ljacomet** [comment]
Are the issues with Spring Boot and Shadow lifted by keeping a class for the removed `maven` plugin?

**Comment by jjohannes** [comment]
I updated the description.

**Comment by big-guy** [comment]
@jjohannes split this up or close this issue

**Comment by jjohannes** [comment]
Superseded by:
- https://github.com/gradle/gradle/pull/16202
- https://github.com/gradle/gradle/issues/16203
- https://github.com/gradle/gradle/issues/16204
