### ISSUE TITLE
Fixed issues service endpoint includes open issues

### ISSUE THREAD

**Issue by dreis2211** [gradle/gradle#15618]
Hi,

I couldn't find where https://services.gradle.org/fixed-issues/6.8 is generated, so forgive me if this is not the correct project. I noticed that the endpoint exposes open issues as well and thus is a bit misleading and leads to wrong release notes, for example.
### **Service response**
![image](https://user-images.githubusercontent.com/6304496/102517773-bde06480-4090-11eb-8864-7bf1e8164d31.png)
### **Release notes**
![image](https://user-images.githubusercontent.com/6304496/102517890-e36d6e00-4090-11eb-8539-6acec5e5dd42.png)
### **Actual issue**
![image](https://user-images.githubusercontent.com/6304496/102517955-f54f1100-4090-11eb-8037-41265aa087e1.png)

### Workaround
I've tested a workaround by filtering open issues in https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/release/content/script.js that I could provide via a PR, but obviously it would be better if the fixed issues response doesn't contain unresolved issues in the first place.

Let me know what you think.
Cheers,
Christoph

**Comment by big-guy** [comment]
Thanks.

Part of our process is to make sure no open issues are assigned to milestones when we close them, so we would have caught this then. That issue shouldn't have been assigned to 6.8.
