### ISSUE TITLE
notify when new version of gradle is available

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15611]
I'd like gradle to print out a notification when I a new version is available

### Expected Behavior

```sh
./gradlew something
```
```
Gradle <version> is available. you can upgrade using
./gradlew wrapper --gradle-version <version>
See Release Notes https://docs.gradle.org/<version>/release-notes.html
```

gradle should only check periodically, I'd suggest once a week by default, or if gradle's release schedule is more predictable. I think this should be on by default, but there should be a flag to disable it. Maybe this output should happen at the end, so you're more likely to notice it. I'd also suggest a switch to turn it off `--disable-automatic-new-version-check`, and maybe also a parsable task `gradle checkVersion` which could output the results as json or something, so if someone wanted to parse it, and process it, to send some kind of notification or publication from CI or something, that would work.

### Current Behavior

no upgrades are ever mentioned

### Context
I've considered writing my own plugin or hunting for one, the impact of this is that it's hard to find out when a new bugfix, or security release happens.

**Comment by dreis2211** [comment]
https://github.com/ben-manes/gradle-versions-plugin is reporting on Gradle versions as well if you're looking for something similar enough.

**Comment by donat** [comment]
Hi @xenoterracide! Thanks for the suggestion. I think this would be a nice feature. At the same time, given the current priorities of the Gradle team, there's little chance this story will get any attention on our side.

Also, Gradle has already too many features. If anything we should make it slimmer and offer better integration with extensions IMHO. 

I think the implementation has a better place in a third-party plugin than in the core codebase. You can use https://github.com/ben-manes/gradle-versions-plugin as suggested above, or you can implement your own solution. The version information is available in json format at [services.gradle.org](https://services.gradle.org/versions/).

**Comment by xenoterracide** [comment]
> Also, Gradle has already too many features. If anything we should make it slimmer and offer better integration with extensions IMHO.

I actually generally agree with this sentiment. I think that Gradle might be better off to move all of its core plugins into external plugins. External plugins that are still maintained by the Gradle team but not downloaded as part of the distribution. In part to make core gradle a lot lighter. Not that I really think the plugins are what's taking up a lot of space. It also might make the distinction of what's a plug-in and what's actually core functionality more obvious.

On that note I actually think it might be good to extract gradlew as well. That's in part due to the fact that I almost wished I was a different CLI for this stuff. I really like how great it works but I kind of hate both the gradlew CLI interface, and how it requires you to commit a binary to your repository, which is something I disagree with. I think now that Java allows you to write a java script that that's no longer necessary. But this is an entirely different issue. Obviously I don't see you guys writing an alternative CLI to gradlew that more reflects how other similar tools interfaces are.

That aside, I actually do believe this should be core functionality. A lot of software these days is self-updating, in part to avoid security and other bugs and people not updating. I don't think Gradle should adjust update on itself but I think It may be slightly irresponsible to not mention that an update is available. At least once like the notification that you have updated. To be honest I'd rather that latter notification actually go away, It's kind of annoying, like I know I just updated.

Just my two cents, can't force a change here.
