### ISSUE TITLE
Runtime add new dependsOn(task) from other task

### ISSUE THREAD

**Issue by Monax111** [gradle/gradle#15629]
I am creating a task for the application deployment.
I have task A (deployment), task B (rollback) and task C (release).
During the execution of task A, I understand that the release is not successful, then I want to add dependency C to task B.

### Expected Behavior
I expect that in this case, after completing task A, task B will be executed

### Current Behavior
task B is not executed

### Context
After not successful deployment rollback not executed. I need start it manual(

### Steps to Reproduce 
Execute task C
```
tasks{
    val a = register("A"){
        doFirst{
            val error = true //some runtime logic
            if(error){
                getByName("C") {
                    dependsOn(getByName("B"))
                    println("Now C must dependsOn B")
                }
                println("But in taskGraph C dependsOn:")
                gradle.taskGraph.getDependencies(getByName("C")).toSet().forEach {
                    println(it.name)
                }
            }
        }
    }
    val b = register("B"){
        doFirst{
            println("ROLLBACK")
        }
    }
    val c = register("C"){
        dependsOn(a)
    }
}
```

### Your Environment
https://scans.gradle.com/s/3g5ghfbft32gy

**Comment by Monax111** [comment]
I see the same situation when search for a docker image for a release. I have a task release, which depends on the task of searching for an image in the Nexus. If there is an image in the nexus (it is deleted after a certain time), then I can release it, and if it is not there, then I must rebuild and push it in nexus.

**Comment by Monax111** [comment]
onlyIf  - is not relevant, because rebuild depends on build. And even if I set up only if on my rebuild task, the build task will still be executed. 
The only way is to set all tasks in build only if and dependsOn to the search task. But in this case, if I just want to build the application (to check the PR),  search task will be executed. What I don't want.

**Comment by Monax111** [comment]
https://gradle-community.slack.com/archives/CA745PZHN/p1608545000309400
As I understand it, the only way to implement this is to take the logic and call external service to the configuration stage. I think it's bad way. 
**Maybe it is worth adding some mechanism for runtime adding tasks?**

**Comment by donat** [comment]
The fundamental problem with your example is that you are trying to add a task dependency too late. The `doFirst` is executed after the task graph configuration is finished and the tasks are being executed. You can probably model the use-case better with [task predicates](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:using_a_predicate) and [finalizer tasks](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:finalizer_tasks).
