### ISSUE TITLE
Gradle releases should be buildable with the most recent prior release

### ISSUE THREAD

**Issue by serebit** [gradle/gradle#15635]
### Expected Behavior
When building a Gradle release from source, such as v6.7.X, a Gradle distribution with version 6.6.X should be useable. That is to say, for any new major or minor release of Gradle, the prior release should be able to compile the new one. Ideally, the only wrappers provided in Gradle source distributions should be the most recent stable wrapper, not the most recent RC.

### Current Behavior
Typically, a new version of Gradle will require usage of one of its RCs to build, which is provided in the form of a Gradle wrapper in the released source.

### Context
For those who ship custom-built versions of Gradle, such as Linux distributions, download avoidance and ease of compilation is important. Requiring the use of a wrapper to compile new major and minor releases of Gradle only serves to complicate this process. I maintain Gradle for [Solus](https://getsol.us), and while I can bootstrap new bugfix releases on the prior release (such as building v6.7.1 with v6.7), I seemingly always have to modify the package buildscript with a new minor release of Gradle just to get it to build properly.

### Steps to Reproduce 
- Download the source for Gradle v6.7
- Install Gradle v6.6
- Attempt to build Gradle v6.7 with Gradle v6.6

**Comment by bmuskalla** [comment]
Thanks for raising this. Given we want to dog-food improvements and new features in our own build first, this is not really possible. Before releasing new features, we want to try them out on "real builds" including our own. Given each tagged release includes which wrapper is required to build it, I think that is good enough for now.
