### ISSUE TITLE
org.gradle.api.Task.html typos in documentation

### ISSUE THREAD

**Issue by sebbASF** [gradle/gradle#15630]
The https://docs.gradle.org/current/dsl/org.gradle.api.Task.html has two Method entries with the same Method summary:  

doFirst(action)

However, the first should be: doFirst(closure), as the parameter is a closure not an action.

Likewise it has two entries with the summary: doLast(action)
The same issue applies.

**Comment by bmuskalla** [comment]
`Action` is a `Single Abstract Method (SAM) interface` and can be used by Groovy and Kotlin. We try to move away from using the Groovy-specific `Closure` as a parameter in APIs that are used by both DSLs. I'm closing this for now but if you have a good idea how to make this more clear in the docs, please let us know
