### ISSUE TITLE
Transform not selected when non-default attribute value set (in module metadata or in a component rule)

### ISSUE THREAD

**Issue by TransLunarInjection** [gradle/gradle#15642]
As far as I can tell from debugging through gradle this occurs because `selectConfigurationUsingAttributeMatching` is called asking for the requested attributes for the current configuration and treats a missing attribute as a match.

selectConfigurationUsingAttributeMatching doesn't understand transforms. When an attribute is missing it treats it as matching any requested value and doesn't treat it as the default value.
Later, collectConsumerVariants and it treats it as the default value and will select a transform to run.

If the attribute is set (doesn't fall back to the default), selectConfigurationUsingAttributeMatching will find that the requested and provided attributes don't match, gets an empty list of matches and then throws `NoMatchingConfigurationSelectionException`. When this happens resolution fails and we never get far enough to search for transformers.

I added some extra logging into these two parts of dependency resolution to demonstrate the differece:

Matching when the attribute has a non-default value:
```
Matching [net.minecraft:minecraft:1.15.2 variant apiElements, net.minecraft:minecraft:1.15.2 variant runtimeElements] against {dev.minco.mapped.net.minecraft=net.fabricmc:yarn:1.15.2+build.9:v2:named, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=11, org.gradle.libraryelements=classes, org.gradle.usage=java-api}
selectConfigurationUsingAttributeMatching net.minecraft:minecraft:1.15.2 -> [] from [net.minecraft:minecraft:1.15.2 variant apiElements, net.minecraft:minecraft:1.15.2 variant runtimeElements] and null
matches -> []
```

Matching when the attribute has the default value:
```
Matching [net.minecraft:minecraft:1.15.2 configuration compile, net.minecraft:minecraft:1.15.2 configuration runtime, net.minecraft:minecraft:1.15.2 configuration platform-compile, net.minecraft:minecraft:1.15.2 configuration platform-runtime, net.minecraft:minecraft:1.15.2 configuration enforced-platform-compile, net.minecraft:minecraft:1.15.2 configuration enforced-platform-runtime] against {dev.minco.mapped.net.minecraft=net.fabricmc:yarn:1.15.2+build.9:v2:named, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=11, org.gradle.libraryelements=classes, org.gradle.usage=java-api}
selectConfigurationUsingAttributeMatching net.minecraft:minecraft:1.15.2 -> [net.minecraft:minecraft:1.15.2 configuration compile] from [net.minecraft:minecraft:1.15.2 configuration compile, net.minecraft:minecraft:1.15.2 configuration runtime, net.minecraft:minecraft:1.15.2 configuration platform-compile, net.minecraft:minecraft:1.15.2 configuration platform-runtime, net.minecraft:minecraft:1.15.2 configuration enforced-platform-compile, net.minecraft:minecraft:1.15.2 configuration enforced-platform-runtime] and net.minecraft:minecraft:1.15.2 configuration default
matches -> [net.minecraft:minecraft:1.15.2 configuration compile]
Matching [net.minecraft:minecraft:1.15.2 configuration compile] against {dev.minco.mapped.net.minecraft=net.fabricmc:yarn:1.15.2+build.9:v2:named, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=11, org.gradle.libraryelements=classes, org.gradle.usage=java-api}
doSelect for ({dev.minco.mapped.net.minecraft=net.fabricmc:yarn:1.15.2+build.9:v2:named, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=11, org.gradle.libraryelements=classes, org.gradle.usage=java-api}, net.minecraft:minecraft:1.15.2) are []
collectConsumerVariants matchResult for ({dev.minco.mapped.net.minecraft=net.fabricmc:yarn:1.15.2+build.9:v2:named, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=11, org.gradle.libraryelements=classes, org.gradle.usage=java-api}, {artifactType=jar, dev.minco.mapped.net.minecraft=net.fabricmc:intermediary:1.15.2:intermediary, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}) are [org.gradle.api.internal.artifacts.transform.ConsumerVariantMatchResult$ConsumerVariant@27912269]
Called RemapTransform.transform
```

### Expected Behavior
Transforms should be able to transform from any attribute value to the requested value for the configuration.

### Current Behavior
Transforms only seem to run for the default attribute value set in this way to the requested value:
```
project.getDependencies().getArtifactTypes().getByName(ArtifactTypeDefinition.JAR_TYPE).getAttributes().attribute(ATTRIBUTE HERE, DEFAULT HERE);
```

If an attribute is set to any value (including set to the same value as the default) resolution fails instead of running a transform which would allow resolution to succeed.

### Context
Same context as #13044

### Steps to Reproduce 
See this gist which includes a set of test cases and logs and a test repo/tag to check out to demonstrate the problem.
https://gist.github.com/TransLunarInjection/44fb57ca251a8bb884c6d856af530768#file-gradle-transforms-not-working-for-attr-value-from-module-or-rules-only-default-value

### Your Environment

Build scan URL: https://scans.gradle.com/s/663iig3zmqvig

**Comment by ljacomet** [comment]
This is a current limitation of transforms: the variant selection must succeed and then transformation can happen.

What you are requesting is a higher level feature which would be more like _variant transformation_ than simply artifact transformation. #8386 is the feature request you are looking for.

Closing this one as duplicate.
