### ISSUE TITLE
 ProjectBuilder.builder().withGradleUserHomeDir() ignores the gradle.properties file

### ISSUE THREAD

**Issue by davidobber** [gradle/gradle#15640]
In a unit test, if a project is created using ProjectBuilder, calling withGradleUserHomeDir() seems to be ignored.

### Expected Behavior
 ProjectBuilder.builder().withGradleUserHomeDir(gradleUserHomeDir) should lead to reading gradle.properties  (and init.gradle) from that directory

### Current Behavior
ProjectBuilder.builder().withGradleUserHomeDir(gradleUserHomeDir) doesn't have effect

### Context
I was trying to write Unit Test with Gradle test kit for a Plugin, using Spock 1.3

### Steps to Reproduce 
In attach there's a small example with just a test that shows the issue

### Your Environment
Gradle 6.7.1 
Windows 10
[gradle-test.zip](https://github.com/gradle/gradle/files/5729256/gradle-test.zip)

**Comment by fbaro** [comment]
I'm having the same problem. 
What I'm actually in need of is a way to let the ProjectBuilder find two extra properties which I normally expect to be defined in the gradle.properties files... is there another way to do this apart from withGradleUserHomeDir which appears not to work?

**Comment by davidobber** [comment]
As a workaround, I've added a plugin in my init.gradle. The plugin is applied to your build and you can add properties to every project in a single place.

~~~groovy
apply plugin: AddPropertiesPlugin

class AddPropertiesPlugin implements Plugin<Gradle> {
	
    void apply(Gradle gradle) {
		gradle.allprojects { project ->
			project.ext {
				propertyName = "propertyValue"
			}
		}
	}
}
~~~

**Comment by ljacomet** [comment]
Thinking more about it, we probably do not want to load things from the Gradle user home and other locations.

The example of the init script is a good one: it makes little sense for unit testing a plugin.

So closing this issue in favor of the one linked above where there would be a specific API to define Gradle properties in unit tests.

**Comment by dgeissl** [comment]
@ljacomet you only just mentioned the properties, but what about local init scripts and specifically prepared local caches or whatsoever for testing?

**Comment by ljacomet** [comment]
That is why I closed this issue. `ProjectBuilder` can only be used to test _configuration_ of a task, not its execution. It is not a real Gradle build. As such, running init scripts, attempting up-to-date checks or anything like that is out of scope.
