### ISSUE TITLE
Gradle 6.6.1 can't support version letters like '0.9.7.309-JS-3'

### ISSUE THREAD

**Issue by chensp0668** [gradle/gradle#15646]
While I upload the jar to nexus3,
![image](https://user-images.githubusercontent.com/3975296/102980996-59ffe500-4543-11eb-8bbc-0c45fb7ef85f.png)
The gradle can't fetch the jar in idea tools
![image](https://user-images.githubusercontent.com/3975296/102981174-92072800-4543-11eb-9275-f04f81022836.png)
But I can download the jar using the maven build.
### Expected Behavior

Does the gradle 6.6.1 not support the version like '0.9.7.309-JS-3',but the version like '2.1.7.js2' is well.
I expect gradle can support the special version letters.

As below while I download the net.sf.jasperreports:jasperreports:5.6.0,it's pom contants 'org.olap4j:olap4j:0.9.7.309-JS-3',so I update the jar madatory in nexus3

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
From the error message, the version number is supported alright. What is missing is the `olap4j-0.9.7.309-JS-3.jar` file itself.

I believe the issue is an environmental one where your Nexus mirror does not have all the files for a given dependency.
