### ISSUE TITLE
Transitive java testFixtures dependency stopped being pulled in Gradle >= 6.7

### ISSUE THREAD

**Issue by idarmans** [gradle/gradle#15652]
I have 3 modules: module-a, module-b, module-c
with module-a & module-b containing some testFixtures

module-b's build.gradle contains
```
dependencies {
    testFixturesCompile testFixtures(project(':module-a'))
}
```
and module-c's build.gradle contains
```
dependencies {
    compile testFixtures(project(':module-b'))
}
```

Classes in module-a's testFixtures used to be visible in module-c in Gradle 6.6.1, but any version higher than that broke compilation.

Current workaround is to modify module-b's build.gradle to use testFixturesApi instead of testFixturesCompile

### Expected Behavior

module-c should be able to see classes declared in module-a's testFixtures

### Current Behavior

In Gradle 6.6.1, module-c's compile succeeds
In Gradle >= 6.7, module-c's compile fails due to module-a's testFixtures no longer being pulled in

### Context

Last version that worked was 6.6.1. I tried 6.7, all the way to 6.8-rc4 and it's still broken.
Use case is module-c is supposed to hold only testFixtures, hence the structure is slightly different than the other modules

### Steps to Reproduce 

[test-fixtures-test.zip](https://github.com/gradle/gradle/files/5737336/test-fixtures-test.zip)
Attached is a sample project with Gradle 6.6.1. Upgrade Gradle to >= 6.7 to reproduce the issue

### Your Environment

Build scan URL:
6.6.1 https://scans.gradle.com/s/76ppiayohyucy
6.7 https://scans.gradle.com/s/qaqjm7ttwhe5m

**Comment by jjohannes** [comment]
> Current workaround is to modify module-b's build.gradle to use testFixturesApi instead of testFixturesCompile

This is not a workaround but the fix.

`compile` and `testFixtureCompile` are deprecated and are removed in Gradle 7.
