### ISSUE TITLE
Wrapper sources not available

### ISSUE THREAD

**Issue by mirabilos** [gradle/gradle#15657]
### Expected Behavior

A separate download containing only the corresponding source code to the wrapper should be available.

### Current Behavior

There is no official corresponding source for the wrapper JAR.

### Context

It is considered normal operation to commit the wrapper into version control. This is, however, a binary blob without sources, so at least the complete corresponding sources should be available so they can be manually downloaded, checksum-verified, and checked in alongside the binary wrapper JAR. (It would be better to check in the sources only and have the shell/batch file compile them locally on first use, but that’d be a separate feature request.)

Unavailablility of such sources is not a licence compliance issue given the licence used, but hindering licence compliance verifyability (“where does this binary blob come from?”).

I seem to have a `gradle-wrapper-5.6.4-sources.jar` file in my source repository, but I cannot find a corresponding file for version 6.7.1 which I consider a bug.

### Steps to Reproduce 

Try to figure out where the wrapper sources are, other than as part of the 146 MB full download.

### Your Environment

Debian GNU/Linux, but that’s not relevant here

**Comment by bmuskalla** [comment]
The sources for the wrapper are part of the Gradle open source repository (see [`wrapper` subproject](https://github.com/gradle/gradle/tree/master/subprojects/wrapper)). The [releases page](https://gradle.org/releases/) also contain download links to all version of Gradle in their *binary* (no sources) as well as *all* (with sources) variants

**Comment by mirabilos** [comment]
Benjamin Muskalla dixit:

>The sources for the wrapper are part of the Gradle open source

I *know* that. See how I wrote…

>>Try to figure out where the wrapper sources are, other than as part of
>>the 146 MB full download.

… and…

>>A separate download containing only the corresponding source code to
>>the wrapper should be available.

>as *all* (with sources) variants

Yes, but that’s huge, there’s no way I’m going to mirror that if
I don’t need to, but I *do* mirror things I’m shipping.

Fixing https://github.com/gradle/gradle/issues/11816 would be even
better. Or distributing the wrapper in source form and compiling it
the first time it’s used (ISTR an issue for that as well but cannot
find it again at the moment). In JRE 11+ you could even bundle it
all in one gradlew.java file and run java --source 11 gradlew.java,
no bytecode compilation needed.

I find the current state of affairs of having a binary JAR in the
repo of a FOSS project *very* distasteful; Maven does not do that.

Thanks for considering,
//mirabilos
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt
