### ISSUE TITLE
Support GCC/G++ from WSL for C++ gradle projects in Windows.

### ISSUE THREAD

**Issue by Articdive** [gradle/gradle#15656]
### Expected Behavior
I expect to be able to define the C++ Compiler, installed in the Windows Subsystem for Linux  (WSL), as the compiler for machines.linux.x86 (and x86_64) from my **Windows** machine and for Gradle to not tell me there is no toolchain available for my operating system. This is basically no different from Cygwin or MinGW it's simply WSL instead. 

TLDR: I want to compile my cpp files with my compiler installed in WSL and Gradle is not smart about it, since it thinks I'm trying to compile for my hostos, which does not have a compiler installed.

### Current Behavior
Gradle has no options for hooking into WSL, I've tried setting the executable to "wsl.exe gcc" (This would be the Windows way of accessing commands/executables in WSL) but it reduces to "wsl.exe" for some reason and fails in the metadata retrieval stage. As of now it does not seem to be possible to achieve the expected behaviour .

### Context
I'm working on a project that uses a CPP module and a Java module and instead of using two different build tools I wanted to merge them into Gradle that has a java module and a cpp module. I am using the Kotlin DSL and IntelliJ. 
As an extra note I am using WSL 2.

**Comment by lacasseio** [comment]
Thanks for this issue. It seems you tried configuring the toolchain registry without success. Could you post the configuration you tried as well? I believe it may be possible to get a valid configuration working but it may be a bit troublesome to get right given the incubating nature of the native toolchain configuration.

**Comment by Articdive** [comment]
Last night I managed to achieve the behaviour, at least it started the build phase :
I create a very basic plugin that mimics the behaviour of the Clang plugin and implemented it, it then had the problem of the paths not being Translated from WSL to Windows and vice versa. So even if the toolchain could be registered correctly (which it thankfully did with the plugin) the paths won't be translated therefore not allowing compilation
