### ISSUE TITLE
Gradle 'implementation' dependency isn't compile with correct code

### ISSUE THREAD

**Issue by zubchenok** [gradle/gradle#15660]
I have a compilation issue with **implementation** dependency when compiling with Gradle the following project that contains of 3 modules:
 - test-impl
 - test-lib
 - my-test

My error:
```
/Users/igor/projects/my-test/src/main/java/MyTest.java:4: error: cannot access TestImpl
        lib.foo("");
           ^
  class file for TestImpl not found
```

It is compiled when I change `implemention` to `api` or if I rename any of `foo` methods in `TestLib` class.

Gradle 6.0.1, Java 1.8.0_271-b09, OSX

Doesn't it look like a bug? Where to report?

All build.gradle files:
=
Module **test-impl** `build.gradle`:
```
apply plugin: 'java-library'
```
Module **test-lib** `build.gradle`:
```
apply plugin: 'java-library'

dependencies {
    implementation project(':test-impl')
}
```
Module **my-test** `build.gradle`:
```
apply plugin: 'java-library'

dependencies {
    api project(':test-lib')
}
```

All source codes:
=
`TestImpl.java` in **test-impl** module:
```
public class TestImpl {
}
```
`TestLib.java` in **test-lib** module:
```
public class TestLib {
    public void foo(String s) {
    }

    private void foo(TestImpl impl) {
    }
}
```
`MyTest.java` in **my-test** module:
```
public class MyTest {
    public void test() {
        TestLib lib = new TestLib();
        lib.foo("");
    }
}
```

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

`test-lib` says that `test-impl` is an implementation dependency however it leaks it in its API since it is a parameter method.
Either hide `TestImpl` or make the dependency an `api` one in `test-lib`.

See the [documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation) for details.

**Comment by zubchenok** [comment]
@ljacomet `TestImpl` is not leaked in its API, because it is a **private** method. This is the bug.

**Comment by zubchenok** [comment]
@ljacomet TestImpl is not leaked in its API, because it is a private method. This is a bug.

**Comment by vlsi** [comment]
@zubchenok , I believe this has nothing to do with Gradle, and the error comes from `javac`. So this is either `javac` bug, or it is expected behavior. In any case, Gradle works fine here.

Here's a pure `javac` reproducer for your sample:

```bash
#!/bin/sh -x

rm test-impl/*.class
rm test-lib/*.class
rm my-test/*.class

javac test-impl/TestImpl.java
javac -cp test-impl test-lib/TestLib.java

# Try building my-test without test-impl on the classpath
javac -cp test-lib my-test/MyTest.java
```

I get the following output:

```bash
$ ./build.sh
+ rm 'test-impl/*.class'
rm: test-impl/*.class: No such file or directory
+ rm 'test-lib/*.class'
rm: test-lib/*.class: No such file or directory
+ rm 'my-test/*.class'
rm: my-test/*.class: No such file or directory
+ javac test-impl/TestImpl.java
+ javac -cp test-impl test-lib/TestLib.java
+ javac -cp test-lib my-test/MyTest.java
my-test/MyTest.java:4: error: cannot access TestImpl
        lib.foo("");
           ^
  class file for TestImpl not found
1 error
```

**Comment by vlsi** [comment]
I've filed https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/356 to detect such cases.
