### ISSUE TITLE
Getting error "Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-3.5-bin.zip'."

### ISSUE THREAD

**Issue by sujata00** [gradle/gradle#15663]
I am facing the below error for my Gradle project:
===================================================================

Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-4.5-bin.zip'.
Could not create service of type JvmVersionDetector using BasicGlobalScopeServices.createJvmVersionDetector().
Could not determine java version from '15.0.1'.

I am using Gradle 3.5 wrapper.

**Output of** : ./gradlew --version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2018-01-24 17:04:52 UTC
Revision:     77d0ec90636f43669dc794ca17ef80dd65457bec

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_271 (Oracle Corporation 25.271-b09)
OS:           Mac OS X 10.16 x86_64

**The problem occurred after updating my MAC to Big Sur.** 

**Eclipse Version:** 

Version: 2020-12 (4.18.0)
Build id: 20201210-1552

**Note:** I am unable to see 'Project and Dependencies' structure for my project which means gradle is not working properly.

**Comment by jetztgradnet** [comment]
I have the same problem with Gradle 6.7, noticed when running from within Eclipse BuildShip (see eclipse/buildship#1050). For me this started either with JDK15 and/or macOS BigSur.

The cause seems to be that the JDK is not properly detected, it always seems to identify JavaHome as `/usr`, likely because the `PATH` containing `/usr/bin/java`. (I tried to get around this using various ways, but no luck so far, see eclipse/buildship#1050 for more details).
```
org.gradle.tooling.GradleConnectionException: Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.7-bin.zip'.
... [stacktrace]
Caused by: org.gradle.launcher.daemon.client.DaemonConnectionException: The newly created daemon process has a different context than expected.
It won't be possible to reconnect to this daemon. Context mismatch: 
Java home is different.
Wanted: DefaultDaemonContext[uid=null,javaHome=/usr,daemonRegistryDir=/Users/wschell/.gradle/daemon,pid=54956,idleTimeout=null,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=DE,-Duser.language=en,-Duser.variant]
Actual: DefaultDaemonContext[uid=67b2193f-8ed3-4ea6-8b7f-ad09ba5a14e3,javaHome=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home,daemonRegistryDir=/Users/wschell/.gradle/daemon,pid=67819,idleTimeout=10800000,priority=NORMAL,daemonOpts=--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=DE,-Duser.language=en,-Duser.variant]
... [stacktrace]
```

**Comment by jetztgradnet** [comment]
Eclipse also had to fix the logic to find the JDK on macOS BigSur (basically ignore `/usr/bin/java` and look for `JAVA_HOME` then), see https://bugs.eclipse.org/bugs/show_bug.cgi?id=565913#c30 and https://git.eclipse.org/r/c/equinox/rt.equinox.framework/+/167943/1/features/org.eclipse.equinox.executable.feature/library/cocoa/eclipseCocoa.c

**Comment by jetztgradnet** [comment]
I tried to find how Gradle comes to `/usr` as the Java Home (as indicated in the output above). This might be `org.gradle.internal.jvm.Jvm.findJavaHome()` which might work with `/usr/bin/java` as provided base location?
