### ISSUE TITLE
Application order of plugins in plugins block should be deterministic

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#15664]
Builds should be deterministic, and sometimes (unfortunately, undesirably), plugins are written poorly and create ordering issues. In such a scenario it should be possible for a user to ensure deterministic application of plugins, based on the order in which they're added to the `plugins` block. However, under certain circumstances, it seems that the order of declaration in the plugins block does not fully determine the order in which those plugins are actually applied by gradle.

### Expected Behavior
Given something like this:
```groovy
// subproject/build.gradle
plugins {
  id 'a' version ...
  id 'b' version ...
}
```
Plugin `'a'` should always be applied before plugin `'b'`.

### Current Behavior
If instead of the above we have the following:
```groovy
// root build.gradle
buildscript {
  dependencies {
    classpath 'coordinates for plugin a'
  }
}

// subproject/build.gradle
plugins {
  id 'a'
  id 'b' version ...
}
```
Then I see plugin `'b'` applied first.

### Context

I was actually just trying to explore how the build classpath works in gradle builds, and was experimenting with different ways of specifying plugins and then looking at build scans to help visualize the classpaths. This issue was unexpected. I asked about it in the [gradle community slack](https://gradle-community.slack.com/archives/CA7UM03V3/p1609220513181600) as well as the [kotlin-lang slack](https://kotlinlang.slack.com/archives/C0B8M7BUY/p1609270592104400). 

Ultimately, I'm filing this issue because it seems incorrect that the application order of plugins isn't deterministic.

### Steps to Reproduce 

Given the following scenario:

```groovy
// root build.gradle
buildscript {
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:4.2.0-alpha15'
  }
}

// subproject/build.gradle
plugins {
  id 'com.android.application'
  id 'org.jetbrains.kotlin.android' version '1.4.21'
}
```
Execute `./gradlew help` and observe it fails with:
```
* What went wrong:
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.android', version: '1.4.21']
> Failed to apply plugin 'org.jetbrains.kotlin.android'.
   > Extension with name 'android' does not exist. Currently registered extension names: [ext, kotlin, kotlinTestRegistry]
```

I am almost certain this is an ordering issue. When I run `./gradlew help -d` and examine the logs, I can see that, in this case, only the Kotlin plugin is ever applied, and it fails, as the Android plugin has not yet been applied and therefore has not yet added the `"android"` extension. This despite the fact that the Android plugin is added first in the `plugins` block. If instead of the above we have
```groovy
// root build.gradle
buildscript {
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:4.2.0-alpha15'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21"
  }
}

// subproject/build.gradle
plugins {
  id 'com.android.application'
  id 'kotlin-android'
}
```
Then `./gradlew help` succeeds, and `./gradlew help -d` shows that the Android plugin is applied before the Kotlin plugin.

**I am not proposing that this is a normal build script configuration. My point is that plugin application order should be deterministic, and should not depend on how the artifact coordinates are specified (explicitly vs implicitly).** Alternatively, I would like to know if this is expected behavior and, if so, why.

### Your Environment

Build scan URL (successful build): https://scans.gradle.com/s/leiuzdoz4i6k2
Build scan URL (failed build): https://scans.gradle.com/s/t7w3bwv3pingm

**Comment by CristianGM** [comment]
Agree order should be deterministic.

Did you open an issue at Kotlin so they can fix the plugin? (I had the same issue before and didn't invest the time on reporting it)

**Comment by autonomousapps** [comment]
@CristianGM ask and you shall receive: https://youtrack.jetbrains.com/issue/KT-44279

**Comment by Vampire** [comment]
The problem seems to lie in `org.gradle.plugin.use.internal.DefaultPluginRequestApplicator#applyPlugins(org.gradle.plugin.management.internal.PluginRequests, org.gradle.api.internal.initialization.ScriptHandlerInternal, org.gradle.api.internal.plugins.PluginManagerInternal, org.gradle.api.internal.initialization.ClassLoaderScope)`.

It separates plugins into two categories, `legacyActualPluginIds` and `pluginImpls`.
Then applies first the legacy ones, and after that the "normal" ones.
The question is whether this is some necessity or just a bug.
It should be relatively easy to instead collect the plugins in one list, then `defineScriptHandlerClassScope` and then apply the plugins in the correct order if it is just a bug.

Actually I also doubt the method and variable naming.
Because it lands in "legacy" if it is added from Plugin Repositories or from composite builds.

**Comment by Vampire** [comment]
I didn't add a test yet, but this change should fix the problem: https://github.com/gradle/gradle/compare/master...Vampire:fix-plugin-application-order
