### ISSUE TITLE
The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead.

### ISSUE THREAD

**Issue by sudhir-kunchakuri** [gradle/gradle#15661]
Hi I am getting this two below warnings.
Can someone tell me what should i need to do to overcome this..

1.The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead.
2. The testCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the testImplementation configuration instead.

**current dependencies in my project:**
dependencies {
    compile 'net.serenity-bdd:serenity-core:2.2.5'
    compile 'net.serenity-bdd:serenity-junit:2.2.9'
    compile 'net.serenity-bdd:serenity-cucumber5:2.2.5'
    compile 'net.serenity-bdd:serenity-ensure:2.2.10'
	compile 'org.apache.commons:commons-lang3:3.11'
    testCompile 'net.serenity-bdd:serenity-screenplay-webdriver:2.2.5'
    implementation 'org.projectlombok:lombok:1.18.12'
}

**Comment by ljacomet** [comment]
The message itself tells you what to do: "Please use the implementation configuration instead."

So you need to replace `compile 'net.serenity-bdd:serenity-core:2.2.5'` with `implementation 'net.serenity-bdd:serenity-core:2.2.5'` and similarly for other dependencies.

You may want to look at the [Gradle documentation](https://docs.gradle.org/current/userguide/declaring_dependencies.html) for understanding what you are writing.
