### ISSUE TITLE
Before resolve actions are not copied when a configuration is copied

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#1567]
### Expected Behavior

When a configuration is copied any before resolve actions registered with the configuration are registered with the copy. This would be consistent with the behaviour for actions registered with the configuration's resolution strategy.

### Current Behavior

Before resolve actions are not copied to the configuration copy.

### Context

This has caused some unexpected behaviour in the interactions between the [Dependency Management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) and the [Versions plugin](https://github.com/ben-manes/gradle-versions-plugin):

- https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/155
- https://github.com/ben-manes/gradle-versions-plugin/issues/123#issuecomment-258680712

### Steps to Reproduce (for bugs)

This script will reproduce the behaviour:

```groovy
apply plugin: 'java'

ext.beforeResolveAction = new BeforeResolveAction()
ext.eachDependencyAction = new EachDependencyAction()

configurations.compile.incoming.beforeResolve(beforeResolveAction)
configurations.compile.resolutionStrategy.eachDependency(eachDependencyAction)

repositories {
    mavenCentral()
}

dependencies {
    compile 'commons-logging:commons-logging:1.2'
}

task(resolveOriginal) {
    doLast {
        configurations.compile.resolve()
        assertActionsCalled()
    }
}

task(resolveCopy) {
    doLast {
        configurations.compile.copy().resolve()
        assertActionsCalled()
    }
}

def assertActionsCalled() {
    if (!eachDependencyAction.called) {
        throw new GradleException('Each dependency action was not called')
    }
    if (!beforeResolveAction.called) {
        throw new GradleException('Before resolve action was not called')
    }
}

class BeforeResolveAction implements Action<ResolvableDependencies> {

    boolean called

    void execute(ResolvableDependencies dependencies) {
        called = true
    }

}

class EachDependencyAction implements Action<DependencyResolveDetails> {

    boolean called

    void execute(DependencyResolveDetails details) {
        called = true
    }

}
```

Building the `resolveOriginal` task will succeed, but building the `resolveCopy` task will fail as the before resolve action hasn't been called.

### Your Environment

I do not believe that this behaviour is environment-specific. The problem exists in Gradle 2.x and 3.x.

**Comment by bmuschko** [comment]
Thanks for providing the example. I am not quite if there was some sort deliberate decision to not copy before resolve actions. 

@bigdaz Can you give some insight here?

**Comment by bigdaz** [comment]
I don't think this is intentional. For instance, we copy do copy the [Default Dependency Actions](https://github.com/gradle/gradle/blob/80710f3e6900e6c877c217140d472334c89dd07a/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L631-L631) when copying a configuration.

**Comment by bmuschko** [comment]
Thanks for the input, @bigdaz. @wilkinsona Would you be interested in providing a fix for this?

**Comment by wilkinsona** [comment]
@bmuschko Yeah, I'd like to do that.

**Comment by bmuschko** [comment]
@wilkinsona Good to hear. Thanks for putting in the work!

**Comment by wilkinsona** [comment]
I have a possible fix for this in [this branch](https://github.com/wilkinsona/gradle/tree/copy-resolution-listeners). I just need to sort out the CLA before opening a pull request. I'm not sure if Pivotal have already signed a corporate agreement.
