### ISSUE TITLE
testImplementation bug on Android Studio

### ISSUE THREAD

**Issue by mrkanet** [gradle/gradle#15672]
![image](https://user-images.githubusercontent.com/24584288/103456283-a5fe1700-4d05-11eb-8f67-bee5a5295457.png)

For 2 years, when I use a pc with Turkish language (Win10) this bug is come along. My friends also get this bug too.
Please fix this bug.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

Please share a reproducer, it is impossible to work with a screenshot as the only source of information.
