### ISSUE TITLE
Deprecate getters/setters that have a stable property as replacement since 7.0

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#15681]
Application plugin:
- JavaExecSpec.(g|s)etMain()
- CreateStartScripts.(g|s)etMainClassName()

Source set and compile task wiring (#11513) - commit preparing this: https://github.com/gradle/gradle/commit/db89003d12eec2e13ec36a1ba3b9f467da7cc463
- SourceDirectorySet.(g|s)etOutputDir()
- AbstractCompile.java.(g|s)etDestinationDir()

AbstractExecTask/JavaExec
- AbstractExecTask.getExecResult()
- JavaExec.getExecResult()

CompileOptions
- CompileOptions.(g/s)etAnnotationProcessorGeneratedSourcesDirectory()

Reporting
- Report.isEnabled()
- Report.getDestination()

Search the code base for more methods annotated with `@ReplacedBy` that we might have missed here.

**Comment by big-guy** [comment]
Check `AbstractArchiveTask`

**Comment by rieske** [comment]
JavaCompile/GroovyCompile getSource -> stableSources?

**Comment by jjohannes** [comment]
Yes, the replacement for `getSource()` is `getStableSources()`.

**Comment by rieske** [comment]
Deprecations in this one are done.
Follow-up to remove them in 8.0: https://github.com/gradle/gradle/issues/17151
