### ISSUE TITLE
CreateStartScripts should allow mainClassName to be set with an environment variable

### ISSUE THREAD

**Issue by nlwillia** [gradle/gradle#1569]
The application plugin's mainClassName property ends up embedded directly in the scripts produced by the CreateStartScripts task.  It would be useful if the value could be overridden with a {{MAIN_CLASS_NAME}} environment variable.  As discussed [here](https://discuss.gradle.org/t/support-for-multiple-application-scripts-in-application-plugin/508), there are ultimately ways to produce alternative script instances or even override how the scripts are produced entirely, but deployment isn't always organized in a way that makes the decision something that can be pushed up to the build script level.

An application may have multiple mains that need to be run on an ad hoc basis.  That's not terrific structure, but it happens, particularly with older code that is more monolithic.  Or there may be a utility or probe that is needed to test something about the application's configuration.  Downstream, there are any number of ways to manipulate the build script to replace the main, but it would be nice if this weren't necessary.

Example workaround for a unix script:
````
startScripts {
	doLast {
		unixScript.text = unixScript.text.replace(mainClassName, "\${MAIN_CLASS_NAME:-'$mainClassName'}")
	}
}
````

**Comment by bmuschko** [comment]
The post you found is fairly outdated. You can provide your own script template now (see Javadocs of [CreateStartScripts](https://docs.gradle.org/3.1/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html). In general I don't think we'll want to built in any magic environment variables. That's something that the consumer can decide by providing custom script logic.

**Comment by nlwillia** [comment]
For anyone else with this use case who finds this issue, here's a version of the template approach.
````
import java.util.regex.Matcher
import java.util.regex.Pattern

startScripts {
	unixStartScriptGenerator.template = resources.text.fromString(unixStartScriptGenerator.template.asString().replaceFirst(Pattern.quote('${mainClassName}'), Matcher.quoteReplacement('\\${MAIN_CLASS_NAME:-"${mainClassName}"}')))
}
````
I'll probably just stick with replacement at the output level.  It's somewhat fragile either way, but better than having to own the whole script template.
