### ISSUE TITLE
javaCompile's options.release is not respected when compiling groovy source

### ISSUE THREAD

**Issue by madorb** [gradle/gradle#15703]
### Expected Behavior
I would expect that when a project sets 
```
javaCompile {
  options.release = 8
}
```

that the byte code emitted from groovy source would have major version 52 

### Current Behavior
Bytecode emitted from the groovy project has major version 55 (or whatever version is used at compile time)

### Context
I was surprised to find that this works:

```
    apply plugin: 'groovy'
    sourceCompatibility = 1.8
    targetCompatibility = 1.8

```
but that this does not: 
```
    apply plugin: 'groovy'

    compileJava {
        options.release = 8
    }

```
does not. 

At the very least if it is not feasible to support reusing these `javaCompile` properties in `groovyCompile`, the documentation should reflect that.

**Comment by ljacomet** [comment]
A couple things are at play here:
* When you configure `compileJava`, you are configuring that task only, not other compilation tasks like `compileTestJava` or `compileGroovy`.
* Groovy itself does not support the `release` flag introduced for `javac`, so even if set on `groovyCompile.compileOptions.release` (which is an unfortunate consequence of type reuse), it will be ignored. Which is also a reason that `release` does not appear on the `java` extension.
* The Kotlin plugin is not developed at Gradle.
* Between recently introduced toolchains (to be supported by `GroovyCompile` in 6.8), the `*Compatibility` options and the `release` support, you have many ways of expressing what byte code version the compile task should produce.

Some of the complexity above is historical, some is inherited from the tools that end up being used.

I would like to better understand what would have helped in the documentation to clarify that `release`, while valid for Java (and only documented there) did not apply to Groovy compilation. Any suggestion?

**Comment by madorb** [comment]
Thanks!

It is only documented on the java plugin, BUT the OLD approach documented on the java plugin was _also_ the same approach used by the groovyCompiler (though i realize it was not task-specific). I think whether it was intended or not, my assumption was that, like the previous approach, this new one be inherited by groovy as well, and it was unexpected that it was not.  

Perhaps just an update to this (no reason for it to be java 6/7 specific) would be helpful. could just talk about how to set the desired JVM target - it being java 6/7 specific caused me to completely overlook it when looking at the documentation. 

https://docs.gradle.org/current/userguide/groovy_plugin.html#sec:groovy_cross_compilation

I recognize that gradle doesn't own the kotlin plugin, but it seems like it could be worthwhile for gradle to provide/recommend a common higher-level (not task specific) mechanism that plugins could use to inherit a singularly-set version (and implement that across all the gradle-owned plugins) (while still allowing it to be overridden at individual tasks if needed).

**Comment by ljacomet** [comment]
Thanks for clarifying and I see your point.
Note that the Groovy part will be updated in 6.8 because of toolchains, see [the documentation](https://docs.gradle.org/6.8-rc-5/userguide/groovy_plugin.html#sec:groovy_cross_compilation)

For the later point, I agree 100% with you and that is what we are trying to do with toolchains, which feel like a better general candidate for that. See [this issue](https://youtrack.jetbrains.com/issue/KT-43095) for example.

**Comment by madorb** [comment]
Ah, thank you, that approach totally makes sense! i'mma close this ticket!

**Comment by iNikem** [comment]
> Thanks for clarifying and I see your point.
> Note that the Groovy part will be updated in 6.8 because of toolchains, see [the documentation](https://docs.gradle.org/6.8-rc-5/userguide/groovy_plugin.html#sec:groovy_cross_compilation)
> 
> For the later point, I agree 100% with you and that is what we are trying to do with toolchains, which feel like a better general candidate for that. See [this issue](https://youtrack.jetbrains.com/issue/KT-43095) for example.

Sorry for posting on the closed issue, not sure if I should open a new one.

@ljacomet even in 6.8 toolchains support does not allow for Groovy compilation to produce bytecode level lower than that of toolchain. Is it planned?
