### ISSUE TITLE
How to download sources without intelliJ or eclipse plugin

### ISSUE THREAD

**Issue by loniszczuk** [gradle/gradle#1572]
Hi, 

I have a custom building process and I need gradle to download both the jars and the sources that my project depends on. 

The dependencies declared are only the jar classifiers. 

The following snipet allows me to print only the absolut path of the .jar files. But I also need to download and to print the path of the corresponding -sources.jar files.
```
task printGradleLibrariesForLibre {
    doLast {
        println rootProject.subprojects
                .collectMany { proj -> proj.configurations.all }
                .findAll { conf -> conf.isCanBeResolved() }
                .collectMany { conf -> conf.resolve() }
                .collect { dependency -> dependency.absolutePath }
                .toSet()
    }
}

```

Can you point me in the right direction to download sources files?

Environment:
Gradle wrapper 3.3

**Comment by bmuschko** [comment]
This is more of a question than an issue. Can you please open this as a question on the Gradle forum?
