### ISSUE TITLE
Dark mode for documentation

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#15726]
Please provide a dark mode for the Gradle documentation.

**Comment by JervNorsk** [comment]
Yes, I need it

**Comment by mlopatkin** [comment]
Unfortunately, we don't have the bandwidth to tackle this issue now. You can try to use some browser extension to show the docs in the dark mode.

**Comment by joffrey-bion** [comment]
It's sad that this issue was closed, will it ever be reconsidered? Browser extensions are usually quite suboptimal, and although I do value dark mode a lot, I never quite got hooked to such extensions.
