### ISSUE TITLE
Abbreviations for included builds referenced from command line

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#15728]
PR #14894 made tasks from included builds available to be called from command line.
Unfortunately you have to spell out the full included build name.
I'd have expected `gradlew b-s:depe` and `gradlew bS:depe`  to work, but I had to spell out `build-src:depe` to get it going.

**Comment by big-guy** [comment]
This was intentional decision because of collisions between included build and subproject names. We can easily check for exact matches, but if we allow fuzzy matching, then more things become ambiguous and surprising.
