### ISSUE TITLE
Gradle deletes all files and puts only changed files in build directory (only on exFAT fs)

### ISSUE THREAD

**Issue by mihett05** [gradle/gradle#15735]
I've tried to build simple project with gradle on exFAT file system, after second build gradle deletes all compiled files from build/classes/java and puts only changed files. And it's impossible to run a project (referenced classes/packages not found). Gradle builds normally the same project on NTFS .

### Expected Behavior

Gradle removes only files that have changed and puts changed files in build/classes directory.

### Current Behavior

Gradle removes all and puts only changed files in build/classes directory.

### Context

build.gradle file:
```gradle
plugins {
    id 'application'
}

repositories {
    jcenter()
}

dependencies {
    testImplementation 'junit:junit:4.13'
    implementation 'com.google.guava:guava:29.0-jre'
}

application {
    mainClassName = 'org.app.App'
}
```

### Steps to Reproduce 

1. Generate project by `gradle init` in directory on exFAT disk.
2. Build it first time
3. Build it again
4. Look to build/classes/java directory or try to `gradle run`

### Your Environment

File system: exFAT
OS: Windows 10 1909

Build scan URL for second `gradle build`: https://scans.gradle.com/s/cunw3wd2faz3e
Build scan URL for `gradle run` after second build: https://scans.gradle.com/s/t5tbhvxesquq6

**Comment by bmuskalla** [comment]
Supporting exFAT is tracked on #4329. Thanks for the report
