### ISSUE TITLE
services.gradle.org on HTTP does not work any longer from Gradle 1.x

### ISSUE THREAD

**Issue by dcoraboeuf** [gradle/gradle#1573]
### Expected Behavior

We are still using Gradle 1.x for many (> 500) legacy projects, which cannot be upgraded to Gradle 2.x.

Their `gradle-wrapper.properties` still uses:

```
distributionUrl=http\://services.gradle.org/distributions/gradle-1.11-bin.zip
```

and since last night (March 13th), the HTTP protocol does not work any longer. 

### Current Behavior

There is an actual redirection when we try this URL in a browser, but it does not seem to be compatible with Gradle 1.11.

### Your Environment

* Gradle 1.11 or 1.12
* CentOS 6 and 7
* Misc. JDK (Oracle & IBM / 1.6, 1.7 & 1.8)

**Comment by davemorrissey** [comment]
We're also seeing this, with a Cordova 6 Android project, which attempts to download http://services.gradle.org/distributions/gradle-2.2.1-all.zip

**Comment by bmuschko** [comment]
Thanks for reporting. We are going to look into the issue.

**Comment by dcoraboeuf** [comment]
FYI - no build can be performed any longer in our company (> 500 projects) because of this issue. Is there somewhere a channel where we could receive notification when there is a change of configuration (if there was indeed a change), like on Twitter or other? Thanks.

**Comment by bgabrhelik** [comment]
Well we came accross with gradle wrapper using gradle-1.12. I have reproduced the issue with the latest gradle distribution - 3.41
````
-bash-3.2$ mkdir test-gradle
-bash-3.2$ cd test-gradle/
-bash-3.2$ /Library/Gradle/gradle-3.4.1/bin/gradle wrapper --gradle-version 3.41
Starting a Gradle Daemon (subsequent builds will be faster)
:wrapper
BUILD SUCCESSFUL
Total time: 4.14 secs
-bash-3.2$ ./gradlew tasks
Downloading https://services.gradle.org/distributions/gradle-3.41-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle.org/distributions/gradle-3.41-bin.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:60)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
````

It seems that HTTP is redirected to HTTPS. But untrusted certificate for different domain is returned. It looks like SLI is not in effect.
````
[root@buildmaster]# wget http://services.gradle.org/distributions/gradle-1.12-bin.zip
--2017-03-14 06:27:25--  http://services.gradle.org/distributions/gradle-1.12-bin.zip
Resolving services.gradle.org... 104.16.174.166, 104.16.175.166, 104.16.173.166, ...
Connecting to services.gradle.org|104.16.174.166|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://services.gradle.org/distributions/gradle-1.12-bin.zip [following]
--2017-03-14 06:27:26--  https://services.gradle.org/distributions/gradle-1.12-bin.zip
Connecting to services.gradle.org|104.16.174.166|:443... connected.
ERROR: certificate common name “ssl473435.cloudflaressl.com” doesn’t match requested host name “services.gradle.org”.
To connect to services.gradle.org insecurely, use ‘--no-check-certificate’.
[root@buildmaster ~]# openssl s_client -showcerts -connect services.gradle.org:443
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2
verify return:1
depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = ssl473435.cloudflaressl.com
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=PositiveSSL Multi-Domain/CN=ssl473435.cloudflaressl.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO ECC Domain Validation Secure Server CA 2
-----BEGIN CERTIFICATE-----

````

**Comment by bmuschko** [comment]
@bgabrhelik You are using the wrong version identifier. The version should be `3.4.1` and not `3.41`.

**Comment by bgabrhelik** [comment]
@bmushko You are right. I am taking back my previous comment. It looks like some incompatibility with old wrapper.jar. Simply it downloads empty file.

**Comment by bgabrhelik** [comment]
It looks like old wrapper.jar doesn't handle properly _Subject Alternative Name_ in the certificate, so it doesn't trust the certificate.

Solution might be to regenerate the wrapper with the latest version of gradle.
see _5.2. Adding the Wrapper to a project_ on the page
https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by mark-vieira** [comment]
This looks to be a result of a change we made to services.gradle.org to force the use of HTTPs. We've since reverted this change. @dcoraboeuf can you please try again?

**Comment by dcoraboeuf** [comment]
It works on my machine :) I'll now test in production.

**Comment by dcoraboeuf** [comment]
Question: was there any kind of communication about this change? We had already some similar issue in the past, with the same consequences. The sheer volume of projects we manage does not allow us to switch all projects and branches to http, not quickly at least. We are working on local workarounds (local hosting of Gradle distributions + DNS redirection of services.gradle.org) to avoid some consequences in the future.

For recent projects, they already us https so they are fine. We're just stuck with the old ones.

I'll go back to you after we've tested in our CI production environment.

**Comment by dcoraboeuf** [comment]
It's working in production as well.

Thanks for the rollback.

**Comment by mark-vieira** [comment]
@dcoraboeuf we didn't communicate this as we expected this to be a mostly transparent change. The incompatibilities between old wrapper clients and the new SSL certs was an unforeseen issue. Our apologies for not communicating this better.

As for the other issues, this change is actually motivated by a desire to make services.gradle.org much more resilient. We are in the process of moving to a much more robust infrastructure for these services.

**Comment by dcoraboeuf** [comment]
OK, good to know. As mentioned, we are accelerating our plan to use some local distribution hosting, in order to not depend on services.gradle.org any longer.

Thanks,
Damien.
