### ISSUE TITLE
Central repository declaration does not work for Groovy

### ISSUE THREAD

**Issue by eekboom** [gradle/gradle#15742]
I tried the new "Central repository declaration" feature of gradle 6.8, but it did not work with groovy compilation.

### Expected Behavior
groovy compilation should pick up the repository defined in settings.gradle.

### Current Behavior

This is the exception I get when trying to start my application with "bootRun":

Execution failed for task ':compileGroovy'.
> Cannot infer Groovy class path because no repository is declared for the project.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:

> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileGroovy'.
> 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
> 	...
> 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
> Caused by: org.gradle.api.GradleException: Cannot infer Groovy class path because no repository is declared for the project.
> 	at org.gradle.api.tasks.GroovyRuntime$1.createDelegate(GroovyRuntime.java:98)
> 	at org.gradle.api.internal.file.collections.LazilyInitializedFileCollection.visitChildren(LazilyInitializedFileCollection.java:33)
> 

### Steps to Reproduce 

I reproduced this with a vanilla Spring Boot application from Spring Initializr: Selected "Project: Gradle Project" and "Language: Groovy".
Then I removed the "repositories { ..." declaration from build.gradle and moved it inside a "dependencyResolutionManagement {" in the settings.gradle.

See attached sample project:
[demo.zip](https://github.com/gradle/gradle/files/5795961/demo.zip)

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
Thanks for the report and there is indeed an issue with that feature and groovy projects.
Unfortunately, the Scala plugin will exhibit the same behavior.
