### ISSUE TITLE
Cannot change strategy of configuration ':jacocoAgent' after it has been resolved.

### ISSUE THREAD

**Issue by whgibbo** [gradle/gradle#1574]
Hi,
Just taking the time to upgrade to the latest version of gradle and have come across the following issue:

> Cannot change strategy of configuration ':jacocoAgent' after it has been resolved.

After a some looking around I have isolated it to following:

> configurations.all {
>     // Only required for Spring Boot 1.4.x, this will not be required for Spring boot 1.5.x
>     resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>         if (details.requested.group == 'org.springframework') {
>             details.useVersion "4.3.5.RELEASE"
>         }
>         else if (details.requested.name == "spring-data-jpa") {
>             details.useVersion "1.10.6.RELEASE"
>         }
>     }
> }  

As soon as I comment out the following:

>     resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>         if (details.requested.group == 'org.springframework') {
>             details.useVersion "4.3.5.RELEASE"
>         }
>         else if (details.requested.name == "spring-data-jpa") {
>             details.useVersion "1.10.6.RELEASE"
>         }
>     }
> 

The problem goes away.  I'm using jacoco 0.7.8, any suggestions ?

**Comment by bmuschko** [comment]
It's hard to say without seeing your project. Can you please provide a sample project on GitHub that reproduces the issue. Please also include the Wrapper so we know what version you refer to with "latest".

**Comment by oehme** [comment]
Closing as there is not enough information to give advice. Most likely a build script or plugin is eagerly resolving dependencies at configuration time, thus preventing further configuration. See #2298
