### ISSUE TITLE
After upgrading to 6.8, a project containing a properties file in src/test/resources with malformed unicode content fails to build

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#15740]
### Expected Behavior
A project with a properties file with deliberately malformed unicode content in `src/test/resources` can be built

### Current Behavior
The project fails to build due to `java.lang.IllegalArgumentException: Malformed \uxxxx encoding`.

### Context
This stopped working in 6.8. It works in 6.7.1.

We have a test for our properties file processing that verifies that malformed unicode content is handled correctly. Upgrading to Gradle 6.8 breaks our build.  This appears to be an unanticipated side-effect of https://github.com/gradle/gradle/pull/14710.

### Steps to Reproduce
1. Clone https://github.com/spring-projects/spring-boot
2. `./gradlew wrapper --gradle-version=6.8`
3. `./gradlew build`

### Your Environment
Build scan URL: https://ge.spring.io/s/6puqcik5prwyc

**Comment by jjohannes** [comment]
This is fixed for 6.8.1 by #15765
