### ISSUE TITLE
Regression in 6.8 regarding experimental Kotlin compiler features warning

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#15747]
With 6.7.1 it says
> \> Task :build-src:compileKotlin
The `kotlin-dsl` plugin applied to project ':build-src' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/6.7.1/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

Adding
```kts
kotlinDslPluginOptions {
    experimentalWarning.set(false)
}
```
makes it go away.

With 6.8 you get
> \> Task :build-src:compileKotlin
w: ATTENTION!
This build uses unsafe internal compiler arguments:
-XXLanguage:+NewInference
-XXLanguage:+SamConversionForKotlinFunctions
-XXLanguage:+ReferencesToSyntheticJavaProperties
This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!

no matter whether you told it to suppress the `experimentalWarning` or not.

@marcphilipp said this is also reproducible in the JUnit 5 build

**Comment by eskatos** [comment]
Hi @Vampire,
Thanks for the report.

I tried to reproduce but couldn't. There might be something specific to your setup that exhibits the problem.

Could you try to share a reproducer?

Or maybe augment my attempt at https://github.com/eskatos/gradle-15747-reproducer ?
I added you as a collaborator already, feel free to push there.

**Comment by marcphilipp** [comment]
For a reproducer, you can clone [junit5](https://github.com/junit-team/junit5/) and run `./gradlew help`:

```
$ git clone https://github.com/junit-team/junit5.git
Cloning into 'junit5'...
remote: Enumerating objects: 690, done.
remote: Counting objects: 100% (690/690), done.
remote: Compressing objects: 100% (373/373), done.
remote: Total 886849 (delta 239), reused 522 (delta 145), pack-reused 886159
Receiving objects: 100% (886849/886849), 579.48 MiB | 20.47 MiB/s, done.
Resolving deltas: 100% (721162/721162), done.
$ cd junit5/
$ ./gradlew --no-build-cache help
Downloading https://services.gradle.org/distributions/gradle-6.8-bin.zip
..........10%..........20%..........30%...........40%..........50%..........60%..........70%...........80%..........90%..........100%

Welcome to Gradle 6.8!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :buildSrc:compileKotlin
w: ATTENTION!
This build uses unsafe internal compiler arguments:

-XXLanguage:+NewInference
-XXLanguage:+SamConversionForKotlinFunctions
-XXLanguage:+ReferencesToSyntheticJavaProperties

This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!


> Task :help

Welcome to Gradle 6.8.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 2m 3s
1 actionable task: 1 executed

A build scan was not published as you have not authenticated with server 'ge.junit.org'.
```

**Comment by eskatos** [comment]
Right, thanks!

I found how to reproduce: turn warnings into errors!
https://github.com/eskatos/gradle-15747-reproducer/commit/78716edbc666578a78235f53b889124d1abbe52c
https://scans.gradle.com/s/lvxiezgxqseoi/console-log#L63

**Comment by Vampire** [comment]
I cloned your project and for me it reproduces the problem

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/15795

**Comment by Vampire** [comment]
@eskatos I still get this with 6.8.1 and 6.8.2

**Comment by Vampire** [comment]
Even with your reproducer
