### ISSUE TITLE
Gradle Daemon has large and increasing memory footprint.

### ISSUE THREAD

**Issue by mjpt777** [gradle/gradle#1575]
The Gradle daemon is ~0.5GB of memory after a single build of the project for [Aeron](https://gitter.im/real-logic/Aeron) and increases in size with each subsequent build. Over the course of this morning it grew to 1.5GB.

I'm building on Windows 10 with Gradle 3.4.1 and Java 1.8.0_121.

A heapdump shows the process is mostly char[]s and Strings.

**Comment by eriwen** [comment]
Thanks for the note. We are looking at this under #1582. Closing as duplicate.
