### ISSUE TITLE
Regression in war classpath copy handling from 3.3 to 3.4.x

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#1577]
When testing an upgrade to Gradle 3.4, we noticed a regression in how war classpaths are handled when using a Copy task to copy from a War task as a `with`.

In this case, we have a `provided` configuration that `minuses` itself from the war task classpath, however as of Gradle 3.4.x, that no longer works in multi-project configurations.

### Expected Behavior

The copied files do not include provided libraries:

    └── webapp-component
        ├── build
        │   ├── libs
        │   │   └── exploded
        │   │       ├── META-INF
        │   │       │   └── MANIFEST.MF
        │   │       └── WEB-INF
        │   │           └── lib
        │   │               └── shared-component.jar
        │   └── tmp
        │       └── war
        │           └── MANIFEST.MF

### Current Behavior

The copied files include the provided libraries:

    └── webapp-component
        ├── build
        │   ├── libs
        │   │   └── exploded
        │   │       ├── META-INF
        │   │       │   └── MANIFEST.MF
        │   │       └── WEB-INF
        │   │           └── lib
        │   │               ├── commons-lang3-3.3.2.jar
        │   │               └── shared-component.jar
        │   └── tmp
        │       └── war
        │           └── MANIFEST.MF

### Context
This breaks our legacy `provided` plugin that stood in for `compileOnly` in earlier Gradle releases.

### Steps to Reproduce
This reduced project will allow you to reproduce the issue, run the `explodedWar` task to demonstrate the behavior:

https://github.com/DanielThomas/provided-reduced

### Your Environment
Gradle 3.4.1

**Comment by bmuschko** [comment]
You mention a multi-project here specifically. Does the issue also expose itself in a single project build?

**Comment by DanielThomas** [comment]
That's right Ben, we have a single project that still works fine, but in our multiproject test we're now getting the provided jars in the war and included in the copy task.

The reduced example I provided gives you all the code, so you don't need to go hunting :)

My _guess_ is that it's got to do with this:

https://github.com/DanielThomas/provided-reduced/blob/master/buildSrc/src/main/groovy/ProvidedBasePlugin.groovy#L44-L47

**Comment by oehme** [comment]
This is pretty much the same issue as discussed with the Spring team, so I'll just [link](https://github.com/gradle/gradle/issues/1371#issuecomment-278436162) my answer :)

**Comment by oehme** [comment]
Closing as discussed in our chat today.
