### ISSUE TITLE
Document whether Compile avoidance for Kapt is still needed as of Gradle 6.8

### ISSUE THREAD

**Issue by LifeIsStrange** [gradle/gradle#15782]
gradle 6.8 has been released and mention compilation avoidance by default for Kotlin.
https://docs.gradle.org/6.8/release-notes.html#performance-improvements

Kapt, the Kotlin annotation processor supports compilation avoidance
https://kotlinlang.org/docs/reference/kapt.html#compile-avoidance-for-kapt-since-1320
by adding this gradle property
kapt.include.compile.classpath=false

Is this compilation avoidance now obscolete/redundant or is it complimentary/hortogonal with the 6.8 improvements ?

aside: I've heard that gradle team is working on an idiomatic/best practices project, maybe the answer to this issue should be included in such project ?

**Comment by darioseidl** [comment]
Afaiu, setting the property `kapt.include.compile.classpath=false` is still required. That property prevents the annotation processors that are declared with `dependencies { ... kapt(...)}` from being included in the compile classpath (they are only added to the kapt config then). This is a setting of kapt, not Gradle, and the latest kapt documentation still says they same:

> However, compile avoidance can't be used for annotation processors discovered in the compile classpath since any changes in them require running the annotation processing tasks.
>
> To run kapt with compile avoidance:
>
> -    Add the annotation processor dependencies to the kapt* configurations manually as described above.
>
> -   Turn off the discovery of annotation processors in the compile classpath by adding this line to your gradle.properties file:
>
>  kapt.include.compile.classpath=false

Gradle 6.8 only seemed to add compile avoidance for the Kotlin build script (`build.gradle.kts`) itself:

> Until now, any change to build logic in buildSrc required all of the build scripts to be recompiled. This release introduces compilation avoidance for Gradle Kotlin DSL scripts.
>
> Compilation avoidance will cause Gradle to only recompile build scripts when a change to shared build logic impacts the ABI (application binary interface) of the classpath of the build script. Changes to private implementation details of build logic, such as private methods or classes, bodies of non-private methods or classes, as well as internal changes to precompiled script plugins, will no longer trigger recompilation of the project's build scripts.
>
> Compilation avoidance also applies to changes in any JAR on the build script's classpath. That includes JARs added by plugins define in included builds and JARs added directly via the buildscript {} block.

I'm not sure how to test whether compile avoidance for kapt is working though.

**Comment by ljacomet** [comment]
Closing as there is nothing to be done in Gradle at this point.
