### ISSUE TITLE
Task not executed if `RegularFileProperty` task output is used as artifact (gradle 6.4+)

### ISSUE THREAD

**Issue by dpeger** [gradle/gradle#15792]
After updating from gradle 6.3 to 6.4+ `RegularFileProperty` task outputs used as artifact don’t seem to work anymore in terms of introducing corresponding task dependencies.

To order my build logic I implemented some basic task with a  `RegularFileProperty` ouput in a gradle file `gradle/tasks.gradle`. If I implement the defined task in a sub-project and use it’s outputs as dependency in another sub-project, gradle 6.4 and above will not add proper dependencies between the corresponding tasks. This has been working with gradle 6.3 and broke with the update to 6.4.

### Expected Behavior
According to the [documentation](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.ArtifactHandler.html) gradle should execute the corresponding task if it's output is used as artifact and is a `Property<RegularFile>`:

> The (artifact) notation can be one of the following types:
> ...
> * A `Provider` of `File`, `RegularFile` or `Directory`. The information for publishing the artifact is extracted from the file or directory name. When the provider represents an output of a particular task, that task will be executed if the artifact is required.

### Current Behavior
With gradle 6.3 this worked as desired. With gradle 6.4 the referenced task is not executed anymore, if the artifact is needed.

### Steps to Reproduce 
https://github.com/dpeger/gradle-issue15792-mvce

Running task `buildProject2` with gradle 6.4+ will not execute `buildProject1`:
```
PS C:\ws\misc\gradle-issue15792-mvce> .\gradlew wrapper --gradle-version 6.4

BUILD SUCCESSFUL in 731ms
1 actionable task: 1 executed
PS C:\ws\misc\gradle-issue15792-mvce> .\gradlew buildProject2 --dry-run
:project2:buildProject2 SKIPPED

BUILD SUCCESSFUL in 1s
```

Running the same task with gradle 6.3 will execute `buildProject1`:
```
PS C:\ws\misc\gradle-issue15792-mvce> .\gradlew wrapper --gradle-version 6.3

BUILD SUCCESSFUL in 776ms
1 actionable task: 1 executed
PS C:\ws\misc\gradle-issue15792-mvce> .\gradlew buildProject2 --dry-run
:project1:buildProject1 SKIPPED
:project2:buildProject2 SKIPPED

BUILD SUCCESSFUL in 988ms
```

### Your Environment
Any environment with gradle 6.4+

**Comment by wolfs** [comment]
The problem here was a missing `final` in front of the output property: https://github.com/dpeger/gradle-issue15792-mvce/blob/main/gradle/tasks.gradle#L5-L6
```
  @OutputFile
  RegularFileProperty outputFile = project.objects.fileProperty()
```

Property types must only have a getter a not a setter. When you run the task individually with Gradle 7.4, then the build fails with an exception, stating exactly this: https://ge.gradle.org/s/xxwonvsrw2lj4
```
A problem was found with the configuration of task ':project1:buildProject1' (type 'MvceTask').
  - Type 'MvceTask' property 'outputFile' of mutable type 'org.gradle.api.file.RegularFileProperty' is writable.
    
    Reason: Properties of type 'org.gradle.api.file.RegularFileProperty' are already mutable.
```

**Comment by dpeger** [comment]
@wolfs, thanks for your support. I'd never imagined that a `final` (or any other) modifier could lead to tasks being skipped or executed. Has there been a specific change in gradle 6.4 that introduced this behavior?

**Comment by wolfs** [comment]
I suppose 6.4 added some additional validation that Gradle doesn't attach the task dependency to mutable `Property` types, aka `Property` types with a setter.
