### ISSUE TITLE
Why gradle projects requires download some packages???

### ISSUE THREAD

**Issue by garawaa** [gradle/gradle#15794]
when build a gradle project. It every time requires some package download. It takes many time big internet bandwidth. Is there a way to download these packages previously and configure manually then build it completely offline? I really hate online build.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***
