### ISSUE TITLE
Promote Java Toolchains

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#15812]
### Summary

All DSL / APIs introduced in the context of https://github.com/gradle/gradle/issues/2203

- org.gradle.api.tasks.JavaExec.getJavaLauncher()
- org.gradle.api.tasks.compile.JavaCompile.getJavaCompiler()
- org.gradle.api.tasks.javadoc.Javadoc.getJavadocTool()
- org.gradle.api.tasks.testing.Test.getJavaLauncher()
- org.gradle.jvm.toolchain.JavaCompiler
- org.gradle.jvm.toolchain.JavaInstallationMetadata
- org.gradle.jvm.toolchain.JavaLanguageVersion
- org.gradle.jvm.toolchain.JavaLauncher
- org.gradle.jvm.toolchain.JavaToolchainService
- org.gradle.jvm.toolchain.JavaToolchainSpec
- org.gradle.jvm.toolchain.JavadocTool
- org.gradle.jvm.toolchain.JvmImplementation
- org.gradle.jvm.toolchain.JvmVendorSpec
- org.gradle.api.plugins.JavaPluginExtension.toolchain(action)
- org.gradle.api.plugins.JavaPluginExtension.getToolchain()
- org.gradle.api.tasks.compile.GroovyCompile.getJavaLauncher()
- Remove `[incubating]` from toolchain report task: https://github.com/gradle/gradle/blob/33c1018bc69dce6c925f0995dd333add68e66c0e/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/task/ShowToolchainsTaskConfigurator.java#L28

### Checklist
- [x] Validate whether we should de-incubate the API in the 7.0 release.
    - If the removal is not possible, create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=1195622786)
- [x] Update release notes (add API to promoted features)
- [x] Check User Manual (it might mention that the API is still incubating)
  - Think about updating snippets and samples to use this API
- [ ] Check Incubation Report on TeamCity ([example](https://builds.gradle.org/viewLog.html?buildId=40024670&buildTypeId=Gradle_Check_SanityCheck&tab=report_project951_Incubating_APIs_Report)) 
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit?ts=5fcfefb8#gid=0).

**Comment by shoaniki** [comment]
IntelliJ is telling me toolchains are still experimental in 7.0-RC1.  I think it might be because org.gradle.jvm.toolchain's package-info.java still has an @Incubating annotation?

**Comment by bmuskalla** [comment]
Thanks for raising this @shoaniki - this has been fixed on `release` for the 7.0 final release
