### ISSUE TITLE
Task dependencies is not set up correctly when using finalizeValueOnRead

### ISSUE THREAD

**Issue by ansman** [gradle/gradle#15815]
### Expected Behavior
When setting the value of a task input to the output of another task I expect the first task to get a dependency on the second task.

### Current Behavior
The expected does happen, but not if you call `finalizeOnRead` on the property.

### Context
I'm trying to make the output of one task the input of another task and I would like to avoid manually hooking up task dependencies.

### Steps to Reproduce 
Here is a repro, put this in a `build.gradle.kts` and run `task2`. It's expected that it would run both `task1` and `task2` but only `task2` runs. If you remove the calls to `finalizeOnRead` then it works as expected.

```kotlin
abstract class Task1 : DefaultTask() {
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        outputFile.finalizeValueOnRead()
    }
}

abstract class Task2 : DefaultTask() {
    @get:InputFile
    abstract val inputFile: RegularFileProperty

    init {
        inputFile.finalizeValueOnRead()
    }
}

val task1 = tasks.register<Task1>("task1") {
    outputFile.set(layout.buildDirectory.file("tmp/foo"))
}

tasks.register<Task2>("task2") {
    inputFile.set(task1.flatMap { it.outputFile })
}
```

### Your Environment
Gradle version 6.8

**Comment by wolfs** [comment]
I tried this out with Gradle 7.4, and it seems to work now.

**Comment by ansman** [comment]
Awesome! Thanks
