### ISSUE TITLE
StackOverflowError when loading project in IntelliJ IDEA with Gradle 6.8

### ISSUE THREAD

**Issue by fluidsonic** [gradle/gradle#15828]
After upgrading from 6.7.1 to 6.8 my Kotlin multiplatform project can no longer be synced in IntelliJ IDEA. The stacktrace indicates that it's a problem with Gradle.

### Expected Behavior

The Gradle sync should work just fine as it did with 6.7.1.

### Current Behavior

```
java.lang.StackOverflowError
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.NodeState.getResolvedVariant(NodeState.java:1243)	
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.getSelectedVariant(EdgeState.java:385)	
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.NodeState.findExternalVariant(NodeState.java:1267)	
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.NodeState.getResolvedVariant(NodeState.java:1252)	
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.getSelectedVariant(EdgeState.java:385)	
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.NodeState.findExternalVariant(NodeState.java:1267)	
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.NodeState.getResolvedVariant(NodeState.java:1252)	
at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.getSelectedVariant(EdgeState.java:385)	
<repeats>	
```

### Context

n/a

### Steps to Reproduce 

I cannot share a reproducible project, only a buildscan.
The project involves a `buildSrc` folder, several Kotlin multiplatform projects depending on each other as well as another multiplatform project with multiple subprojects added as a composite build.

I wasn't able to reproduce it to reproduce it on the command line yet.

### Your Environment

Build scan URL: https://scans.gradle.com/s/ex6n34x6ciiwm

**Comment by ljacomet** [comment]
@fluidsonic Any chance you could debug and identify the module causing the StackOverflow?
I wonder if there is a weird dependency out there that leverages `available-at` but points at itself in some way ...

**Comment by ljacomet** [comment]
@fluidsonic Could you try importing your project with the following Gradle version: `6.8.1-branch-ljacomet_dependency_management_available_at_stackoverflow-20210121210634+0000`

Update your wrapper with `./gradlew wrapper --gradle-version 6.8.1-branch-ljacomet_dependency_management_available_at_stackoverflow-20210121210634+0000`

It should prevent the `StackOverflowError` and print some information at `WARN` level which should be visible in the IJ sync window.

**Comment by fluidsonic** [comment]
Thank you for that special version @ljacomet. It does prevent the `StackOverflowError` and prints some cycles.

The two libraries in the output are actually my own. They're Kotlin/JS libraries. See [fluid-css](https://dl.bintray.com/fluidsonic/kotlin/io/fluidsonic/css/fluid-css/0.9.0/) for example.

```
Detecting cycle in external variants for io.fluidsonic.css:fluid-css:0.9.0
	\___io.fluidsonic.css:fluid-css:0.9.0

Detecting cycle in external variants for io.fluidsonic.react:fluid-react-router-dom:0.9.0
	\___io.fluidsonic.react:fluid-react-router-dom:0.9.0

Detecting cycle in external variants for io.fluidsonic.css:fluid-css:0.9.0
	\___io.fluidsonic.css:fluid-css:0.9.0

Detecting cycle in external variants for io.fluidsonic.react:fluid-react-router-dom:0.9.0
	\___io.fluidsonic.react:fluid-react-router-dom:0.9.0

Detecting cycle in external variants for io.fluidsonic.css:fluid-css:0.9.0
	\___io.fluidsonic.css:fluid-css:0.9.0

Detecting cycle in external variants for io.fluidsonic.react:fluid-react-router-dom:0.9.0
	\___io.fluidsonic.react:fluid-react-router-dom:0.9.0
```

**Comment by ljacomet** [comment]
So there is something wrong in the metadata of these libraries that is most likely exposed by the fixes done around `available-at` handling for Gradle 6.8.
As can be seen [in the metadata](https://dl.bintray.com/fluidsonic/kotlin/io/fluidsonic/css/fluid-css/0.9.0/:fluid-css-0.9.0.module), the library indicates that a variant is published through a different module _but then points back at itself_.
This should be considered an error and should be validated by Gradle really.

I will move this issue out of the 6.8.1 scope as the error is really on the publication side. I will however leave it open to be fixed by having Gradle prevent such cycles at metadata generation time.

It would be good if you can figure out how you end up with that cycle which must reflect a cycle between variants for the component.

**Comment by fluidsonic** [comment]
Thanks. I've raised [an issue](https://youtrack.jetbrains.com/issue/KT-44491) with the Kotlin team as this is likely an error in the Kotlin Gradle Plugin.

**Comment by ljacomet** [comment]
I'll answer both here and there:

For `ktor`, there is no issue. `ktor-client-core-js` uses `available-at` to point back to `ktor-client-core` (note the missing `-js` part) for the variants `metadataApiElements-published` and `commonMainMetadataElements-published` which are then local variants [in the metadata](https://repo.maven.apache.org/maven2/io/ktor/ktor-client-core/1.5.0/ktor-client-core-1.5.0.module) with artifacts and dependencies.

**Comment by fluidsonic** [comment]
Thanks, I've missed that detail. I'll check to see what's different in the other libraries' publications.

**Comment by fluidsonic** [comment]
Must have to do something with the way I publish a multiplatform library when it only has a single target:
https://github.com/fluidsonic/fluid-gradle/blob/8520b612117e95a6a00cd8e615bdd9c130cbb194/sources/LibraryModuleConfigurator.kt#L601-L615

I'll dig deeper.

**Comment by fluidsonic** [comment]
I've removed the offending publishing code from my library. It wasn't a clean way to modify the publication and interfered with the Kotlin plugin's setup of those in problematic ways.

I'm looking forward for seeing a validation on the publishing side. That would have made this mistake easier to spot 👍
