### ISSUE TITLE
Reduce default maximum heap and permgen for Gradle Daemon

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1582]
### Expected Behavior
1 gb for max heap is much larger than we should need for the vast majority of applications. We might consider a default of 256 mb, but TBD.

### Current Behavior
The Daemon currently defaults to 1 gb for max heap and 256 mb for permgen.

**Comment by mjpt777** [comment]
I'm still seeing this as a major issue even with version 4.0.2.  Having almost 800MB for a daemon on a machine that only has 4GB is not reasonable.

**Comment by pcdv** [comment]
I also suffer from this problem. I work on multiple projects simultaneously, which all spawn a gradle daemon by default. I often have to kill all gradle daemons to free up some memory.

I've played a bit with https://www.eclipse.org/mat/ to analyze heap dumps and compare dumps of a same daemon at various intervals. 

Here are some of the seemingly leaked objects:
```
Class Name                                                    |  Objects | Shallow Heap
----------------------------------------------------------------------------------------
org.gradle.api.internal.artifacts.DefaultModuleVersionSelector| +331 600 |   +7 958 400
org.gradle.model.internal.core.ModelReference                 |  +63 277 |   +2 531 080
org.eclipse.jgit.lib.ObjectId                                 |  +41 152 |   +1 316 864
org.gradle.internal.MutableActionSet                          |  +40 230 |     +643 680
org.gradle.model.internal.registry.RuleBindings$Reference     |  +36 068 |     +865 632
org.gradle.model.internal.registry.BindingPredicate           |  +36 068 |     +577 088
org.gradle.internal.metaobject.BeanDynamicObject              |  +34 269 |   +1 644 912
org.gradle.api.internal.tasks.DefaultTaskDependency           |  +32 463 |     +779 112
----------------------------------------------------------------------------------------
```

Grouping strings by value is another way to easily find waste. I find a lot of duplicated strings most of which seem to belong to multiple instances of org.tmatesoft.svn.core.internal.wc.SVNConfigFile.

Hope this helps!
