### ISSUE TITLE
New console shows failed tasks even if no tasks have been failing

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#1585]
I see two failed tasks in the status line of the console even though no tasks have failed

### Expected Behavior
Status line like this:
```
<============-> 99% EXECUTING [77% AVOIDED, 23% DONE]
```

### Current Behavior
But status line is like this:
```
<============-> 99% EXECUTING [2 FAILED, 77% AVOIDED, 23% DONE]
```

### Context
I am building Gradle itself on the release branch

### Steps to Reproduce (for bugs)
I was running `:baseServices:integTest`

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/o24wh5qozvlfy

**Comment by lacasseio** [comment]
Thanks @wolfs, I will have a look at it later today.

**Comment by lacasseio** [comment]
We decided to revert change 2617d6eb8e95275bbd17d63f0028bdcb1b28497e as task failure detection wasn't as trivial as we thought it would be.

**Comment by bmuschko** [comment]
Is it worth adding a milestone here? The issue was reported for a previously unreleased feature. The issue will show up in the release notes and reader might ask themselves what this is about.

**Comment by lacasseio** [comment]
Good point, I removed it from the milestone.
