### ISSUE TITLE
Kotlin Gradle Plugin fails with NullPointerException when built using OpenJDK 11

### ISSUE THREAD

**Issue by jsumedh** [gradle/gradle#15861]
When android application is built using OpenJDK 11 Kotlin Gradle Plugin 1.3.31 fails with NullPointerException. For details refer build scan here. [Build Scan](https://scans.gradle.com/s/pvhmabxo5canc)

### Expected Behavior
Build should be successful

### Current Behavior
An error while building android application written in Kotlin

### Context
I am not able to build application with this Kotlin Gradle Plugin. However if I update it to 1.3.72 it works.

### Steps to Reproduce 
Build a sample application in Kotlin
Add Kapt dependency
Build with Kotlin Gradle Plugin 1.3.21

### Your Environment
Build scan URL: https://scans.gradle.com/s/pvhmabxo5canc

**Comment by bmuskalla** [comment]
I believe this has been fixed on the [kapt side](https://youtrack.jetbrains.com/issue/KT-28311). Please let me know if you can still reproduce this and believe this is a defect in Gradle itself. You can use the Youtrack instance of logging defects for Kapt
