### ISSUE TITLE
Millions of directories/files created inside "caches/.../scripts-remapped" directory on Linux

### ISSUE THREAD

**Issue by seccanj** [gradle/gradle#1586]
After having issues with my Ubuntu/Linux system always running out of inodes, I found out that Gradle is creating millions of directories in its "caches/2.14.1/scripts-remapped" folder.

It looks like this directory is never cleaned up: it's a cache anyway.

I think there should be a better housekeeping of this directory, or maybe a different solution should be found for Gradle to reuse scripts as long as they are not changed.

Environment: 
- Ubuntu 16.04 LTS,
- EXT4 file system,
- Gradle 2.14.1 within a Liferay 7 project,
- both through Eclipse and directly on the command line (using gradlew),

**Comment by seccanj** [comment]
Opened an issue as suggested in the forum: https://discuss.gradle.org/t/scripts-remapped-directory-using-up-all-the-inodes-on-my-system/21883

**Comment by bmuschko** [comment]
Thanks for reporting. Have you tried a newer version of Gradle to see if that exposes the same issue?

**Comment by marcphilipp** [comment]
@seccanj Is this issue still relevant for you?

**Comment by plechev** [comment]
This is still an issue with 4.7. I can see a lot of content which exists in  `/caches/4.7/scripts/...` 
 is simply duplicated in `/caches/4.7/scripts-remapped/..` 
What purpose does this folder serve?

**Comment by big-guy** [comment]
[Gradle 4.10](https://docs.gradle.org/4.10/release-notes.html#periodic-cache-cleanup) added cache clean-up that will delete these directories if they're no longer used.

@plechev It's a way for Gradle to script compilation of build scripts that are identical in content, but are used by different projects (and need to be treated as separate classes). You can safely delete the scripts and scripts-remapped directories when no Gradle daemons are running.  On the next build, Gradle will recompile build scripts as needed.

**Comment by plechev** [comment]
@big-guy 👍
