### ISSUE TITLE
Cross-document links in userguide_single are broken

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#15866]
If you look at https://docs.gradle.org/current/userguide/userguide_single.html#part:native_projects the text "the older Native plugins" is a link, but links to `https://docs.gradle.org/current/userguide/userguide_single.html#` when it should link to `https://docs.gradle.org/current/userguide/userguide_single.html#native_projects_using_the_software_model`.

If you look at https://docs.gradle.org/current/userguide/userguide_single.html#native_projects_using_the_software_model on the other hand, there the text "replacement plugins" is a link to `https://docs.gradle.org/current/userguide/userguide_single.html#` while it should link to `https://docs.gradle.org/current/userguide/userguide_single.html#part:native_projects.

In the single page variant it is fine, https://docs.gradle.org/current/userguide/building_cpp_projects.html links to https://docs.gradle.org/current/userguide/native_software.html and the other way around.

We had the exact same problem and also with ADOC documentation in Spock.
I fixed it in this PR: spockframework/spock#1122, feel free to get inspiration there.
The problem is if you make cross-page links without any anchor, or at least for us this was the problem.
In the multi-page variant it works fine as it just links to the other HTML, but in the one-page variant all is the same page and thus only a self-link remains.
All cross-page links must have an anchor part for proper linking in multi- and single-page rendering.
I even added a task that verifies all cross-page links for having an anchor part to make sure there are no such links re-introduced, again feel free to take inspiration.

**Comment by ljacomet** [comment]
Thanks for raising this and providing potential solutions.

**Comment by ljacomet** [comment]
Moved to 7.0 for fixing. Might get backported to 6.8.x if we do another release in that line.
