### ISSUE TITLE
Turn 'Querying the mapped value of provider before producer has completed' into an error

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#15876]
### Summary
Turn nagging in `TransformBackedProvider.beforeRead()` into an error.

### Checklist
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation

**Comment by thumannw** [comment]
Please fix #15796 before, else this will introduce a regression.

**Comment by eskatos** [comment]
Done in https://github.com/gradle/gradle/pull/16393
