### ISSUE TITLE
Broken and outdated links in Kotlin DSL Primer

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#15874]
The Kotlin DSL Primer at https://docs.gradle.org/current/userguide/kotlin_dsl.html has some broken links, like to
`https://github.com/gradle/kotlin-dsl-samples/tree/master/samplesgroovy-interop` instead of
`https://github.com/gradle/kotlin-dsl-samples/tree/master/samples/groovy-interop`.

Additionally the whole `kotlin-dsl-samples` project is archived, I guess the samples were moved and are maintained somewhere else, so the links should probably be updated to that place instead.

Additionally there is a link to an issue in the `kotlin-dsl` repository which is was renamed to `kotlin-dsl-samples` and is the just mentioned archived repository. If there is a replacement issue for that in the normal Gradle repository, it should be linked instead as it currently coming from that looks like it's just ignored as it is an issue in an archived project that will not get any updates anymore.

**Comment by ljacomet** [comment]
#15887 has been merged, closing
