### ISSUE TITLE
Eclipse plugin cannot handle platform URLs in classpath

### ISSUE THREAD

**Issue by lukoerfer** [gradle/gradle#1590]
### Expected Behavior
When adding library entries manually to the _.classpath_ file of an Eclipse project and running the Gradle `eclipseClasspath` task afterwards, the Eclipse plugin should read the file and merge the dependency entries with the ones added manually, if the _.classpath_ file is still valid (can be interpreted by Eclipse).

### Current Behavior
Manually added classpath entries (lib) with the `javadoc_location` attribute cause the file to be unreadable by the Eclipse plugin, if the attribute value is based on one of the Eclipse ["platform" schemes](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fplatform-scheme-uri.html), even if Eclipse can read such files. This results in a Gradle execution failure:
> Cannot parse file 'C:\path\to\\.classpath'. Perhaps this file was tinkered with? In that case try delete this file and then retry.

### Context
The mentioned Eclipse platform URLs ("platform" scheme) are the only (?) way to use relative paths for the location of library javadocs. In my particular case, an Eclipse based IDE automatically adds entries (with this format for the javadocs) to the _.classpath_ file, causing the Gradle execution to fail. A simple workaround is to use the _cleanEclipseClasspath_ task (manually or in script) to delete the file, but this way one looses the merge feature. Generally speaking, the Eclipse plugin should be able to read any valid Eclipse .classpath file without failing.

### Steps to Reproduce (for bugs)
1. Create a minimal _build.gradle_ file with the Eclipse plugin:

```
apply plugin: 'java'
apply plugin: 'eclipse'
    
repositories {
    mavenCentral()
}

dependencies {
    compile 'junit:junit:4.10'
}
```

2. Execute `gradle eclipse`.
3. Manually add a library entry to the _.classpath_ file, e.g.

```
<classpathentry kind="lib" path="relative/path/to/lib.jar">
    <attributes>
        <attribute name="javadoc_location" value="jar:platform:/resource/project/relative/path/to/javadoc.jar!"/>
    </attributes>
</classpathentry>
````

4. Execute `gradle eclipse` a second time (e.g. after adding an additional dependency)

### My Environment
 * Build scan URL: https://scans.gradle.com/s/kzftgnhpn5x34

**Comment by bmuschko** [comment]
At the moment the plugin does simply not merge entries AFAIK. Why do you want to add something manually? You can define everything you need in your build script.

**Comment by lukegv** [comment]
For my special case I have to work with an IDE, that inserts classpath entries from time to time (and it uses relative paths for everything). Only for this particular case, I also insert my gradle dependency classpath entries via `file.whenMerged` to achieve relative paths, which works fine until I start the process again and it crashes due to the unreadable format. Yes, I know, this approach is not really how Gradle is designed, but I got this task, so I work on it.

The basic "bug" or wrong behavior in my eyes, is the fact that Gradle (respectivly the Eclipse plugin) crashes when reading and parsing a totally valid _.classpath_ file.

**Comment by bmuschko** [comment]
> For my special case I have to work with an IDE, that inserts classpath entries from time to time (and it uses relative paths for everything).

Let me guess: IBM Websphere RAD? ;-)

> The basic "bug" or wrong behavior in my eyes, is the fact that Gradle (respectivly the Eclipse plugin) crashes when reading and parsing a totally valid .classpath file.

Did you try to use just Buildship for your use case without generating the project files from the command line?

**Comment by lukegv** [comment]
> Let me guess: IBM Websphere RAD? ;-)

No, its the KUKA Sunrise.Workbench. The IDE ships and manages the libraries and tools based on a station setup. Additional dependencies can be added via Eclipse. This method is sufficient for some casual robot programming, but our team tries to establish a more powerful build environment with Gradle. Now I need to somehow put those parts together.

> Did you try to use just Buildship for your use case without generating the project files from the command line?

I do not know Buildship (and I'm also new to Gradle), but my mission right now is to write Gradle tasks equivalent to the Eclipse tasks (so-called Sunrise tasks) with some additional requirement like the availability of all dependencies in the project folder (so its portable for non Gradle users) and the classpath "merging" from different dependency sources.

As I already mentioned, I know that most of this plan it not Gradle-like, but thats how the IDE environment and the requirements affect my work.
I don't expect Gradle (or the Eclipse plugin) to support any of this, but I thought it should try to support the [Eclipse Platform URLs](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fplatform-scheme-uri.html) some day, so I created this issue. I hope I did no mistake in doing so.

**Comment by bmuschko** [comment]
> I do not know Buildship (and I'm also new to Gradle)...

I tried to use [Buildship](https://projects.eclipse.org/projects/tools.buildship) to see if that fixes your issue.

@oehme Can you give some additional advice here?

**Comment by oehme** [comment]
Buildship always overwrites and personally I never use `gradle eclipse` anymore because Buildship is so much more feature rich. 

If I had to use `gradle eclipse`, I'd always make it do a `cleanEclipse` before and make sure all dependencies are properly defined in the build script (potentially through the `whenMerged {}` hook).

That being said, I'm open to adding platform URL support to our content merger if someone wants to provide a pull request for that.

**Comment by lukegv** [comment]
Ok, thank you very much for your advice. As a workaround I'll try to somehow define the IDE generated dependencies in the buildscript and work with `cleanEclipse` to make sure that the mentioned error does not appear.

On a long term, I'll take a look on how implement the platform URL format for the Eclipse plugin and check, whether I have both the time and the qualification to do this.
