### ISSUE TITLE
Configurable test parallelization

### ISSUE THREAD

**Issue by bsideup** [gradle/gradle#1591]
Right now the users are limited to "per-class" parallel test execution. Would be nice to support different strategies like Maven Surefire plugin does (i.e. "suites", "classes", "methods") to make it possible to parallelize `@Parameterized" tests for instance.

### Expected Behavior
Configurable execution strategy where user is able to select how Gradle should parallelize the tests

### Current Behavior
No configuration provided, only classes are parallelized, not the methods or inner suites.

### Context
We run Parameterized tests and would like to run them in parallel with Gradle's built-in mechanism.

**Comment by bmuschko** [comment]
Would you interested in providing a pull request for this feature?

**Comment by bsideup** [comment]
@bmuschko I do have an interest but no free time, sorry :(

**Comment by bmuschko** [comment]
@bsideup Bummer! Maybe somebody else from the community would like to step in.
