### ISSUE TITLE
replace String.format with +

### ISSUE THREAD

**Issue by counter-reverse** [gradle/gradle#15936]
### Summary

String.format is used [here](https://github.com/gradle/gradle/blob/124712713a77a6813e112ae1b68f248deca6a816/subprojects/core/src/main/java/org/gradle/execution/commandline/CommandLineTaskConfigurer.java#L75). This function requires to use C-like operator (`%s`) to work. It is a waste of execution time, resources, maintainability and should be removed in favor of concatenation with `+`. See [here](https://redfin.engineering/java-string-concatenation-which-way-is-best-8f590a7d22a8l). For example you can do like [this](https://github.com/gradle/gradle/blob/master/.teamcity/.mvn/wrapper/MavenWrapperDownloader.java#L27).

### Checklist
- [X] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [X] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133). 

You can assign me. I am going to solve my own issue.

**Comment by ljacomet** [comment]
Same comment as on the PR - no changes planned in Gradle around this.
