### ISSUE TITLE
Provide support for repositories in POMs

### ISSUE THREAD

**Issue by no-preserve-root** [gradle/gradle#15932]
Maven supports reading additional repositories from dependencies' POM. I.e., if a library A depends on a second library B available via jitpack.io, an application using A would only need to declare a dependency on A, but not declare the repository. During dependency resolution, Maven will pick up the repository and add it to the build process. Gradle ignores `<repository>` elements in POMs and does not create the when publishing a release.

### Example

Consider a project `a` with `build.gradle.kts`:
```
plugins {
    `java-library`
    `maven-publish`
}

repositories {
    maven { url = uri("https://jitpack.io") }
}

group = "example"
version = "1.0"

dependencies {
    api("com.github.jitpack", "example", "1.1") // same with implementation
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
}
```

and a project `b` with `build.gradle.kts`:
```
plugins {
    `application`
}

repositories {
    mavenLocal()
}

group = "example"
version = "1.0"

dependencies {
    implementation("example", "a", "1.0")
}
```

### Expected Behavior

```
$ cd /path/to/a
$ ./gradlew publishToMavenLocal
$ cd /path/to/b
$ ./gradlew assemble
```
works.

### Current Behavior

When building `b`, Gradle complains that `com.github.jitpack:example:1.1` can not be found in the local repository, but does not check the jitpack.io repository:
```
Execution failed for task ':startScripts'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.github.jitpack:example:1.1.
     Searched in the following locations:
       - file:/home/name/.m2/repository/com/github/jitpack/example/1.1/example-1.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > example:a:1.0
```

### Context

This prevents the creation and use of libraries that depend on unusual repositories without manually adding the repositories to each dependent. The issue came up when using jitpack.io libraries in other libraries. It affects both the Maven publish plugin and the dependency mechanism.

#### Maven publish plugin

Ideally, the plugin would include repository information into the created POM (perhaps with a toggle). Alternatively, if dependencies not present on Maven Central were used, it should warn the user that the generated POM will not work out of the box. Addressing this would immediately yield artefacts that work in Maven. This feature can be emulated by adding the `<repositories>` element using XML writing in the publication.

#### Dependency mechanism

Ideally, the dependency mechanism would, either automatically or by adding, e.g., a `mavenDependencyRepository()` to the `repositories` block, add `<repositories>` from dependencies` POMs. Alternatively, a (suppressible) warning could be emitted that the user is responsible for adding all required repositories to the build script's `repositories` block when the element is encountered in a dependency's POM.

**Comment by ljacomet** [comment]
This is not the first time such a request is made. The answer remains that Gradle will never allow this.
While convenient in some scenarios, it is a serious security risk and Maven should really offer an opt-out of this feature.

**Comment by JLLeitschuh** [comment]
This is a security issue with an ongoing discussion.

https://twitter.com/tbroyer/status/1334163509496729600?s=20
https://github.com/gradle/gradle/issues/15406

I agree with @ljacomet, this is something we do not want to support in Gradle due to the security issues it inherently brings.

**Comment by ljacomet** [comment]
Clsoing as this is not something that is planned at all.
