### ISSUE TITLE
win10开启移动热点后，gradle编译会出现错误“你的主机中的软件中止了一个已建立的连接。”

### ISSUE THREAD

**Issue by xuyj89** [gradle/gradle#15939]
操作系统：windows 10
开发环境：android studio和idea都存在问题

复现步骤：
1.在开发工具上clean project
2.打开win10的网络设置，开启无线热点
3.在开发工具上编译项目

报错：
你的主机中的软件中止了一个已建立的连接。

**Comment by blindpirate** [comment]
Please don't open issues in Chinese, most of our team can't read Chinese.
