### ISSUE TITLE
After update Android Studio could not create parent directory for lock file

### ISSUE THREAD

**Issue by blackhawk389** [gradle/gradle#1593]
Updated android studio and plugins when sync, fails with could not create parent directory for lock file
wrapper properties:

`#Sun Mar 05 16:51:59 PKT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
`

build.gradle app module:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.sarahn.toyapplication"
        minSdkVersion 17
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
}
`

build.gradle(project)

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

tried downloading NDK, deleting .gradle folder from project and from installs but not going forward

Environment:
Windows 10

**Comment by bmuschko** [comment]
Can you please open an issue on the [Android bug tracker](https://www.google.de/search?q=android+bug+tracker&oq=android+bug+tracker&aqs=chrome..69i57j0l5.3488j0j7&sourceid=chrome&ie=UTF-8) instead?
