### ISSUE TITLE
Gradle build doesn't support customerized resource directory

### ISSUE THREAD

**Issue by EmilyRen** [gradle/gradle#1594]
### Expected Behavior

I have one resource folder name is drawable-mdpi-theme, when I tried gradle build, it failed with error "Invalid resource directory name".
Can gradle support customized resource directory such as drawable-*dpi-sth?

### Current Behavior

Gradle build is successful if resource directory name is drawable-mdpi, it doesn't work if resource directory name is drawable-mdpi-theme.

Error is:
:mergeDebugResources
res/drawable-mdpi-theme: Error: Invalid resource directory name
:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':mergeDebugResources'.
> res/drawable-mdpi-theme: Error: Invalid resource directory name

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

### Context

We need to support extra theme screen, which is not supported by android for now.

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Can you please open an issue on the [Android bug tracker](https://www.google.de/search?q=android+bug+tracker&oq=android+bug+tracker&aqs=chrome..69i57j0l5.3488j0j7&sourceid=chrome&ie=UTF-8) instead?
