### ISSUE TITLE
Improve toolchain documentation wrt default VM choice

### ISSUE THREAD

**Issue by meisenla** [gradle/gradle#15947]
### Expected Behavior
For the configuration

```
 java {
     toolchain {
         languageVersion = JavaLanguageVersion.of(11)
     }
 }

```

Gradle uses the installed Java 11 JDK

### Current Behavior
` ./gradlew -q javaToolchains` finds the installed JDK 11

```
$ ./gradlew -q javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + AdoptOpenJDK 11.0.9
     | Location:           C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-openj9
     | Language Version:   11
     | Vendor:             AdoptOpenJDK
     | Is JDK:             true
     | Detected by:        Current JVM
```

but `$ ./gradlew check -Porg.gradle.java.installations.auto-download=false` does not use this JDK:
```
$ ./gradlew check -Porg.gradle.java.installations.auto-download=false

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':application:test'.
> Could not resolve all dependencies for configuration ':application:testRuntimeClasspath'.
   > Failed to calculate the value of task ':application:compileJava' property 'javaCompiler'.
      > No compatible toolchains found for request filter: {languageVersion=11, vendor=any, implementation=vendor-specific} (auto-detect true, auto-download false)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

### Steps to Reproduce

1. Download the toolchains sample from https://docs.gradle.org/current/samples/zips/sample_jvm_multi_project_with_toolchains-groovy-dsl.zip
2. run `./gradlew check -Porg.gradle.java.installations.auto-download=false`

### Your Environment
Gradle: 6.8.1
Windows 10
AdoptOpenJDK 11 OpenJ9

Build scan URL:
https://scans.gradle.com/s/udxgxtb4ivgm4

**Comment by bmuskalla** [comment]
@meisenla Thanks for the report. This is actually intentional but not obvious in your case. Given the differences between HotSpot and J9 as JVM implementation, we decided to only consider hotspot VMs by default. If your build and application/library can actually handle J9, you can enforce to use a J9 JVM using
```
languageVersion = JavaLanguageVersion.of(11)
implementation = JvmImplementation.J9
```

See also the documentation for more details on [how to configure specific toolchains](https://docs.gradle.org/current/userguide/toolchains.html#selecting_toolchains_by_their_virtual_machine_implementation).

**Comment by meisenla** [comment]
Thanks, for the quick response. Maybe you can clarify that in the documentation. I misinterpreted "Acts as a placeholder and matches any implementation from any vendor (e.g. hotspot, zulu, …​)" as any implementation including J9.

**Comment by bmuskalla** [comment]
Good point. In case you have some time, I'd be happy to review a PR for this.

**Comment by swpalmer** [comment]
Is there a wildcard that can be specified for the implementation, so we can "by choice" have J9 auto-selected if it is the only one available?  I would imagine many projects just need to know that the correct major version is being used and the implementation isn't a factor.

The documentation here https://docs.gradle.org/current/userguide/toolchains.html fails to link to javadocs for JvmImplementation or JvmVendorSpec, so determining what the valid values are is more awkward than it needs to be. (Entering these in the"Search the docs" box doesn't help either.)
