### ISSUE TITLE
IncludedBuild.name is only the directory name, but not rootProject.name since gradle 6.0

### ISSUE THREAD

**Issue by dgeissl** [gradle/gradle#15944]
### Expected Behavior
configuring a projects `settings.gradle` like that:
```groovy
// otherProject/settings.gradle
rootProject.name='prjID'
println 'project settings evaluated'
```
sets the name regardless of the directory it is checked out
```groovy
// otherProject/build.gradle
println "my name is $name"
```
when using this in a composite build:
```groovy
// settings.gradle
includeBuild 'includedBuild'
println 'composite settings evaluated'
```
this should also be the name of the project when used as `includedBuild`
```groovy
// build.gradle
gradle.includedBuilds.each {build -> println "includedBuild name is: $build.name" }
```

so the output should be:
```
composite settings evaluated
project settings evaluated

> Configure project :prjID
my name is prjID

> Configure project :
includedBuild name is: prjID
```

### Current Behavior
with gradle 6 `includedBuild.getName()` returns the directory name regardless of the settings.gradle of the included build:
```
composite settings evaluated
project settings evaluated

> Configure project :otherBuild
my name is prjID

> Configure project :
includedBuild name is: otherBuild <-- this is wrong!
```

### Context
we use naming patterns to provide convinience tasks in a included build to start tasks implemented in the sub builds, much like having a multi module build, but only for a subset of tasks in a composite build environment. These mappings failed when we
upgraded to gradle 6 due to the fact that the subproject and the composite build do not operate with the same project name.

### Steps to Reproduce 
example is provided above

### Your Environment
Windows 10 (2004)
tested with: Gradle 6.0.1, 6.2.1, 6.3, 6.4.1, 6.5.1, 6.6.1, 6.7.1, 6.8, 6.8.1
last working example: Gradle 5.6.4

**Comment by mlopatkin** [comment]
This was an intentional change in 6.0 and it is documented:
https://docs.gradle.org/current/userguide/upgrading_version_5.html#changes_to_build_and_task_names_in_composite_builds
