### ISSUE TITLE
Cache entry for ScalaCompile task does not include compiled classes sometimes

### ISSUE THREAD

**Issue by gfjalar** [gradle/gradle#15961]
After the upgrade to `6.8` from `6.6.1`, I have noticed that sometimes (in some CI builds) class files created by `ScalaCompile` task are not correctly put into the remote cache entry. 

### Expected Behavior
When `ScalaCompile` populates `classes` directory with class files, they should all be a part of the cache entry that is send to the remote cache.

### Current Behavior
Sometimes, `ScalaCompile` task does not put its' `destinationDirectory` into the cache entry. Because of that, future builds using that cache entry are failing.

### Context
Because of this issue, our CI system has started to put faulty cache entries into the remote cache. Those cache entries were later used by other builds which lead to build failures.

### Steps to Reproduce 
The issue seems to be non-deterministic. So far, I've only seen it with one specific state of my company's repository which, unfortunately, I cannot publicly share. I've prepared a trimmed down version of the repository with private parts stripped out but I wasn't able to reproduce the issue there. However, let me describe the principle:

1. We start with this repository https://github.com/gfjalar/gradle-6.8-cache
2. We change `orgScalacheckVersion` from `1.14.0` to `1.14.1` https://github.com/gfjalar/gradle-6.8-cache/blob/master/gradle.properties#L15
3. We push the change, CI picks it up and starts the build (`gradle test-util:assemble test-util:testClassess test-util-user:assemble test-util-user:testClasses`)
4. The gradle build correctly notices that the dependencies of `test-util` changed so it performs `ScalaCompile` task https://github.com/gfjalar/gradle-6.8-cache/blob/master/test-util/build.gradle#L2
5. The build succeeded which indicates that `test-util` was compiled correctly and `test-util/build/classes` is populated correctly
6. We make a change to `test-util-user` code. Let's say we add a newline at the end https://github.com/gfjalar/gradle-6.8-cache/blob/master/test-util-user/src/test/scala/com/gfjalar/test_util_user/mockito/CustomMockitoSugarTest.scala
7. We push the change, CI picks it up and starts the build (`gradle test-util:assemble test-util:testClassess test-util-user:assemble test-util-user:testClasses`)
8. The gradle build correctly notices that nothing about `test-util` changed so it gets `ScalaCompile` task output from cache
9. The gradle build correctly notices that `test-util-user` changed so it performs `ScalaCompile` task
10. The compile task fails with `object test_util is not a member of package com.gfjalar`

### Your Environment

| Key | Value |
| --- | --- |
| Gradle | 6.8 |
| Gradle Enterprise plugin | 3.3.3 |
| Build Cache	| On |
| Configure on demand	| On |
| Continue on failure	| On |
| Parallel	| On |
| Task inputs file capturing	| On |
| Continuous	| Off |
| Daemon	| Off |
| Dry run	| Off |
| Offline	| Off |
| Re-run tasks	| Off |
| Refresh dependencies	| Off |
| Operating system	| Linux 5.4.0-1029-aws	 |
| CPU cores	| 8 cores	 |
| Max Gradle workers	| 8 workers	 |
| Java runtime	| AdoptOpenJDK OpenJDK Runtime Environment 1.8.0_275-b01	 |
| Java VM	| AdoptOpenJDK OpenJDK 64-Bit Server VM 25.275-b01 (mixed mode)	 |
| Max JVM memory heap size	| 3774 MB	 |
| Max JVM worker memory heap size	| 2925 MB |
| Locale	| English (United States)	 |
| Default charset	| UTF-8 |

###### :test-util:compileScala details

From the initial build that did perform the compilation (because there were no missing package errors further down the line) but stored only 3 files as part of the cache artifact.

<img width="510" alt="Screenshot 2021-01-28 at 10 37 48" src="https://user-images.githubusercontent.com/6688074/106119222-3ab53280-6155-11eb-8b25-d18b5f09129c.png">

From the subsequent a build performed after I manually deleted the `cc059aab8806465bc490639bbc80e8e7.artifact` from the remote cache which caused the recompilation. Notice that this time around it packed all 100 files.

<img width="511" alt="Screenshot 2021-01-28 at 10 38 12" src="https://user-images.githubusercontent.com/6688074/106119375-6c2dfe00-6155-11eb-9cd2-457fc59cc2ef.png">

Inputs difference between the two. Notice how there is a difference in jar inputs but the compilation in build A still succeeded.
<img width="803" alt="Screenshot 2021-01-28 at 10 58 02" src="https://user-images.githubusercontent.com/6688074/106121490-e790af00-6157-11eb-8d0d-c05bfa3153ab.png">

**Comment by wolfs** [comment]
@ljacomet I removed the execution label, since we won't be looking at this.

**Comment by bmuskalla** [comment]
@big-guy Do you intend to work on this further?

**Comment by mwos-sl** [comment]
Is there any progress on that? We are blocked with migration to newer gradle because of that.
