### ISSUE TITLE
Build requires Java 11 which is reported by a nested subproject

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#15978]
### Expected Behavior

Ideally the build can run on any JDK. If not, it should fail fast, not after taking many steps.

### Current Behavior

The build requires Java 9-11, but only fails when finally running this project `:build-logic:uber-plugins:generatePrecompiledScriptPluginAccessors`. If the build has a JDK requirement, it should be checked in the top-level build.gradle to provide fast feedback.

```
* What went wrong:
An exception occurred applying plugin request [id: 'gradlebuild.api-parameter-names-index']
> Failed to apply plugin 'gradlebuild.api-parameter-names-index'.
   > Could not create task ':build-logic:uber-plugins:generatePrecompiledScriptPluginAccessors:accessors12889617585402508915:compileGroovy'.
      > Must use JDK >= 9 and <= 11 to perform compilation in this build. It's currently OpenJDK 15 at /Users/aanuraag/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home.
```

Alternative to a top-level build error, using the toolchains feature could possibly allow the caller JVM to be 15 and still compile with Java 11.

### Context

First time building failed with the above error. It's unfortunate that this means the previous build gets completely invalidated by the java version change, leading to extra time spent / barrier to contribution. I think it's relatively easy to add a java version check to the top-level build to reduce the extra time spent.

**Comment by bmuskalla** [comment]
We're currently [migrating](https://github.com/gradle/gradle/pull/15926) the `gradle/gradle` build to toolchains so the JDK for running Gradle will not be as problematic as before.

**Comment by bmuskalla** [comment]
And thanks for the feedback, it's always good to hear what kind of struggles our contributors run into so we can improve the contribution workflow :)
