### ISSUE TITLE
Configuration Time Performance Improvements

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1597]
Improve Gradle's configuration time performance. 

- Analyse builds from users that suffer from long configuration time
- Improve analysis tooling for configuration time in [Gradle Build Scans](https://scans.gradle.com) and [Gradle Profiler](https://github.com/gradle/gradle-profiler)
- Improving guidance for optimising build configuration time - e.g. through Build Scans or Guides
- If discovered, improve on configuration time related performance bottlenecks in Gradle core

**Comment by jinge1936** [comment]
I see this epic were created two year ago, why the configuration performance is still too bad? why run a independent task requires configure all other tasks?  why configure-on-demand does not work? Can you speed up??

**Comment by jjohannes** [comment]
Analysing and improving configuration time is now done in context of the  `@configuration-cach` effort. See issue with the `@configuration-cach` label.

https://docs.gradle.org/current/userguide/configuration_cache.html
