### ISSUE TITLE
Build successful even though there is an unmappable character encoding error

### ISSUE THREAD

**Issue by sehenst** [gradle/gradle#15980]
### Expected Behavior
The build should fail when there is an unmappable character encoding error.

### Current Behavior
The build succeeds.

![image](https://user-images.githubusercontent.com/60508776/107346162-b358af00-6ac4-11eb-8943-a663110ea983.png)

### Context
`org.gradle.jvmargs=-Dfile.encoding=UTF-8` is set in `gradle.properties` in order to enforce `UTF-8` encoding. The idea is to make sure that every developer on the team uses the correct encoding. However, since the build succeeds it's not possible to enforce a specific encoding. Thus, there is a risk that a developer might use the wrong encoding and this will get merged and later on affect the rest of the development team.

### Steps to Reproduce 
I've created a repo and PR that shows the error: https://github.com/sehenst/unmappable_character/pull/1

### Your Environment

Build scan URL: https://scans.gradle.com/s/ml4vz5pstycbe

**Comment by bmuskalla** [comment]
This is still an issue with 7.9
