### ISSUE TITLE
Mysterious org.gradle.internal.resolve.ArtifactNotFoundException

### ISSUE THREAD

**Issue by wlnirvana** [gradle/gradle#16008]
### Expected Behavior
Project compiles

### Current Behavior
The following error
```
-----------
* What went wrong:                        
Cannot isolate parameters com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@21a76207 of artifact transform AarResourcesCompilerTransform
> Could not isolate value com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@21a76207 of type AarResourcesCompilerTransform.Parameters
   > Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
      > Could not find aapt2-4.1.0-alpha09-6422342-linux.jar (com.android.tools.build:aapt2:4.1.0-alpha09-6422342).
        Searched in the following locations:                                                                                                                                                  
            https://maven.aliyun.com/repository/google/com/android/tools/build/aapt2/4.1.0-alpha09-6422342/aapt2-4.1.0-alpha09-6422342-linux.jar
                                                                                                                                                                                              
* Try:                                                                                         
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
```

### Context
When build a small android project, I replaced the google maven repo with alibaba's mirror, which results in the error above. However, the URL reported in the exception actually has the wanted jar.

### Steps to Reproduce
My `build.gradle` is as follows:

```
buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        maven { url 'https://maven.aliyun.com/repository/google/' }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0-alpha09'
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google/' }
        mavenCentral()
        mavenLocal()
        jcenter()
    }
}
```

run `./gradlew assembleDebug` to reproduce the error.

The project is [attached](https://github.com/gradle/gradle/files/5915602/android_project.tar.gz) as well, but the android sdk and relevant environment variables have to be setup to run it.

### Your Environment
- OS: Ubuntu 20.04
- JDK: 11
- Android: 29

**Comment by wlnirvana** [comment]
I'm totally a newbie to gradle, but I managed to find the following facts (not sure if these are correct/helpful, though):

1. The aapt2 jar seems to be in fact locally cached:

```
~/.g/caches $ find . -name "*4.1.0-alpha09*" | grep "aapt2" | grep -v "aapt2-proto"
./modules-2/files-2.1/com.android.tools.build/aapt2/4.1.0-alpha09-6422342
./modules-2/files-2.1/com.android.tools.build/aapt2/4.1.0-alpha09-6422342/c8ccfffb2df7740b26a4061148f857429fe5accf/aapt2-4.1.0-alpha09-6422342.pom
./modules-2/files-2.1/com.android.tools.build/aapt2/4.1.0-alpha09-6422342/b786d1c6e4d0eb1d024bcbb18144d21454724333/aapt2-4.1.0-alpha09-6422342-linux.jar
./modules-2/metadata-2.96/descriptors/com.android.tools.build/aapt2/4.1.0-alpha09-6422342
./transforms-2/files-2.1/563824142f5394db411fb536fe40fc11/aapt2-4.1.0-alpha09-6422342-linux


~/.g/caches $ find ./modules-2/metadata-2.96/descriptors/com.android.tools.build/aapt2/4.1.0-alpha09-6422342
./modules-2/metadata-2.96/descriptors/com.android.tools.build/aapt2/4.1.0-alpha09-6422342
./modules-2/metadata-2.96/descriptors/com.android.tools.build/aapt2/4.1.0-alpha09-6422342/11cd36a7dcab7d14d0c14c5e6c7582e3
./modules-2/metadata-2.96/descriptors/com.android.tools.build/aapt2/4.1.0-alpha09-6422342/11cd36a7dcab7d14d0c14c5e6c7582e3/descriptor.bin
./modules-2/metadata-2.96/descriptors/com.android.tools.build/aapt2/4.1.0-alpha09-6422342/f0f296685294c1fab444efe078de1f11
./modules-2/metadata-2.96/descriptors/com.android.tools.build/aapt2/4.1.0-alpha09-6422342/f0f296685294c1fab444efe078de1f11/descriptor.bin
```

2. During `./gradlew assembleDebug`, the control flow always enter [this line](https://github.com/gradle/gradle/blob/1a04183c502614b5c80e33d603074e0b4a2777c5/subprojects/dependency-management/src/main/java/org/gradle/internal/resource/cached/AbstractCachedIndex.java#L63), at which point `key.toString()` is `f0f296685294c1fab444efe078de1f11:aapt2-4.1.0-alpha09-6422342-linux.jar (com.android.tools.build:aapt2:4.1.0-alpha09-6422342)`. However, `found.isMissing()` is actually `true`, which is unexpected. Is something missing here?

**Comment by wlnirvana** [comment]
Some further findings:

with this `build.gradle`

```
buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0-alpha09'
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google/' }                // <----------- ADDED MIRROR
        mavenCentral()
        mavenLocal()
        jcenter()
    }
}
```

The project compiles just fine. When `./gradlew assembleDebug` hits [this line](https://github.com/gradle/gradle/blob/1a04183c502614b5c80e33d603074e0b4a2777c5/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/CachingModuleComponentRepository.java#L472), the `delegate` variable has a `root` value of `https://maven.aliyun.com/repository/google/`, which is the mirror I set. This results in the key having a repositoryId of `f0f296685294c1fab444efe078de1f11`.

But with this `build.gradle`

```
buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0-alpha09'
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        jcenter()
    }
}
```

The issue occurs. The delegate at the same breakpoint is `https://dl.google.com/dl/android/maven2/`, and the repositoryId of the constructed key is `11cd36a7dcab7d14d0c14c5e6c7582e3`, which is different from the previous case when alibaba's mirror is used.

I suspect this repostoryId is later [used](https://github.com/gradle/gradle/blob/1a04183c502614b5c80e33d603074e0b4a2777c5/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/artifacts/ArtifactAtRepositoryKey.java#L54) in searching the `BTreePersistentIndexedCache`. Could there be some problem here?

**Comment by ljacomet** [comment]
The changing key is normal: Gradle tracks the origin repository of a dependency, which means that while the jar file is cached locally, Gradle will attempt to resolve it from the new repository to verify it is the same.

Could you produce a build scan of the failing build and link it here?
I wonder if the alibaba mirror you are using is not behaving well with regards to HEAD requests for example, which would prevent Gradle from working properly.

**Comment by wlnirvana** [comment]
I tried to produce a build scan but am currently having some issues with the proxy, which I reported [in another thread](https://github.com/gradle/gradle/issues/11384#issuecomment-772935718).

**Comment by wlnirvana** [comment]
Haven't been able to reproduce this issue recently, and the attached project compiles fine. It could be there was something wrong with alibaba's mirror, which is fixed now. So close this issue.

**Comment by SOUAD999** [comment]
Caused by: org.gradle.api.artifacts.transform.VariantTransformConfigurationException: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@7402ff71 of artifact transform D8BackportedMethodsGenerator

**Comment by Magzhan08** [comment]
> Caused by: org.gradle.api.artifacts.transform.VariantTransformConfigurationException: Could not isolate parameters com.android.build.gradle.internal.utils.D8BackportedMethodsGenerator$Parameters_Decorated@7402ff71 of artifact transform D8BackportedMethodsGenerator

I have the same problem.  Have you managed to solve this problem?
