### ISSUE TITLE
Version sorting performance

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#1600]
While evaluating perf flame graphs of dependency resolution, I noticed version sorting is expensive. We've also noticed some serious GC pressure during dependency resolution, and this appears to be a major culprit also.

### Regular expression compilation

Regular expression compilation occurs several times per comparison:

    private boolean isNumber(String str) {
        return str.matches("\\d+");
    }

Guava's Ints/Longs.tryParse would seem to be a high performance, and robust alternative. Also appears to be an opportunity to attempt parsing the parts once, and have a numeric array that holds the parsed value or null (which is what this API provides) as a further optimization for determining `isNumber` and having the parsed number to hand, once per comparison.

Perhaps add a `getNumericParts` to `DefaultVersion` and parse on construction.

### Version parsing and allocation

Versions are represented as strings on critical paths of dependency resolution, which leads to them needing to be parsed and allocated during version sorting. Short sample w/ allocation profiling:

<img width="1217" alt="screen shot 2017-03-20 at 5 20 38 pm" src="https://cloud.githubusercontent.com/assets/1479220/24127403/90dc50ec-0d91-11e7-8bd0-fdfb033b9601.png">

### Your Environment
Current Gradle master branch.

**Comment by DanielThomas** [comment]
@melix @oehme seeing as this is a comparator used in sort, and we have a _lot_ of potential candidates in conflict resolution, this could make a material difference.

**Comment by melix** [comment]
Thanks @DanielThomas , you're right, using `String#matches` is in general a very bad idea for performance. We should review our usage of this method but also of regular expressions in general.

**Comment by DanielThomas** [comment]
@melix added some notes on object allocation overhead I found.

**Comment by DanielThomas** [comment]
Ignore my last comment, misread some profiling output :)

**Comment by oehme** [comment]
This has been merged, thanks for the PR @DanielThomas !
