### ISSUE TITLE
Run by gradle or Intellij causes different result when I use testFixturesImplementation

### ISSUE THREAD

**Issue by seongahjo** [gradle/gradle#16012]
### Expected Behavior
![image](https://user-images.githubusercontent.com/10272119/106738041-ca2d7a80-665a-11eb-8635-8ecadf28378f.png)
![image](https://user-images.githubusercontent.com/10272119/106738057-d1ed1f00-665a-11eb-8e4b-338d3161bcd5.png)

import library from `testFixturesImplementation` for using in test module.

### Current Behavior
I can't build by gradle BUT I can build and run by Intellij
It was so confused

Gradle
```
import net.jqwik.api.Arbitraries;
                    ^
1 error
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
```

Intellij
![image](https://user-images.githubusercontent.com/10272119/106983874-f60b4600-67a9-11eb-96be-4c4f414d2fce.png)

### Context

CompileTestJava filters `testFixturesImplemenation` dependencies
But It is not worked in Intellij

since `testFixturesImplementation` should not leak into test compile path,
MAYBE should add some codes to IDEA for preventing different result.

### Steps to Reproduce 
* Download [repository](https://github.com/seongahjo/gradle-testFixtures-example)
* Run `./gradlew test`
* Run by Intellij

**Comment by bmuskalla** [comment]
I think the difference between IntelliJ and the command line is that you didn't configure IntelliJ to delegate to gradle. As IJ suggests, this may change the behavior as they implement their own dependency lookup. Further, I don't understand why you use `testFixturesImplementation` for adding test dependencies. I think you want to use `testImplementation` instead. [Test fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) are a different feature
