### ISSUE TITLE
Installation page doesn't include windows information for manual installation

### ISSUE THREAD

**Issue by SbSpider** [gradle/gradle#1601]
The installation page at https://gradle.org/install doesn't include information for Windows apart from suggesting using Chocolatey. One of the courses where I am therefore had a lot of confusion on how to install gradle, since their initial impression from the page was that the only way to install gradle on Windows must then be using chocolatey, or building from source. 

### Expected Behavior
Include information on how to run the commands on windows. e.g. show export PATH etc., but also set PATH for Windows users.

### Current Behavior
Currently it only shows commands for Linux, not for Windows.

**Comment by bmuschko** [comment]
Thanks for reporting. There's no limitation on installing Gradle on Windows manually. The instructions are just Unix-specific. You'd set the PATH for Windows like for any other executable.

We are going to expand on the installation section. It just won't have in the next couple of days.

**Comment by ysb33r** [comment]
@SbSpider We have added the necessary information and the updated install guide will be live this week.

**Comment by eriwen** [comment]
This is live https://gradle.org/install
