### ISSUE TITLE
eclipseWtp task hangs in composite build

### ISSUE THREAD

**Issue by donat** [gradle/gradle#16010]
### Expected Behavior

Composite build using project substitution should work when the user applies `eclipse-wtp` task.

### Current Behavior

The build hangs indefinitely. The debug log indicates that the build is waiting for a lock:

```

2021-02-03T10:12:18.916+0100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2021-02-03T10:12:18.916+0100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2021-02-03T10:12:18.916+0100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
(message displayed periodically, without end)
```

### Context

The issue was reported on the Buildship board: https://github.com/eclipse/buildship/issues/1033

### Steps to Reproduce 

- Download [sample project](https://github.com/gradle/gradle/files/5917290/multiple_war.zip)

- Run `./gradlew cleanEclipseWtp eclipseWtp`

**Comment by quentinflahaut** [comment]
Hello,

I'm also facing the same problem. In my composite this is not the eclipseWtp tasks but my own tasks.
I can reproduce in gradle 6.8 and 6.8.1

**Comment by donat** [comment]
We're investigating. In the meanwhile can you try running the `eclipseWtp` task with the `--parallel` flag?

**Comment by regrog** [comment]
I've tried out some tasks:
- Using command line `./gradlew cleanEclipseWtp eclipseWtp --parallel` success.
- Using command line `./gradlew cleanEclipseWtp eclipseWtp` locks.
- Using eclipse task view and running `eclipseWtp` having `org.gradle.parallel=true` success.
- Using eclipse task view and running `eclipseWtp` having `org.gradle.parallel=false` locks.
