### ISSUE TITLE
Auto-apply Gradle Enterprise Gradle plugin 3.6.1 in the 6.8.x stream

### ISSUE THREAD

**Issue by facewindu** [gradle/gradle#16021]
### Expected Behavior
We should auto-apply Gradle Enterprise Gradle plugin 3.5.2 instead of 3.5.1 if a new 6.8.x release is created.

**Comment by ljacomet** [comment]
@facewindu We are going to do a 6.9.
Can you submit a PR for this?

**Comment by guylabs** [comment]
@ljacomet created https://github.com/gradle/gradle/issues/16021
