### ISSUE TITLE
Allow visiting a CopySpec without copying

### ISSUE THREAD

**Issue by slavashvets** [gradle/gradle#1602]
### Feature Request Description
Please add support for exporting a `CopySpec` object (from War, Jar, etc.) to a map or text. This is a great feature that allows us to deploy exploded packages without actual copying, right from Gradle's:

* static resources folders (`src/main/webapp`, etc.)
* cached libraries (`~/.gradle/caches/modules-2/files-2.1/...`)
* output folder (`build/classes`, etc.)

[I've asked how to do this on stackoverflow](http://stackoverflow.com/q/41982306/2211754) some time ago and it seems there is no evident way until this is implemented as a Gradle feature.

### Example

Incoming file _build.gradle_
```groovy
war {
  destinationDir temporaryDir
  into 'META-INF/resources', { from 'src/html/index.html' }
  into 'META-INF/resources/static', { from 'src/css' }
  into 'META-INF/resources/static', { from 'src/images' }
}
```

Desired build mapping for Tomcat 7 - _$CATALINA_HOME/Catalina/localhost/myapp.xml_

```xml
<Context docBase="">
  <Resources className="org.apache.naming.resources.VirtualDirContext" extraResourcePaths="
    /META-INF/resources/index.html=C:/myapp/src/html/index.html,
    /META-INF/resources/static=C:/myapp/src/css,
    /META-INF/resources/static=C:/myapp/src/images
  "/>
</Context>
```

Desired build mapping for Weblogic - _.beabuild.txt_

```properties
C\:/myapp/src/html/index.html=META-INF/resources/index.html
C\:/myapp/src/css=/META-INF/resources/static
C\:/myapp/src/images=/META-INF/resources/static
```

**Comment by slavashvets** [comment]
**Could someone at least add labels for the issue?**

It seems to me that this feature request can speed up development build a lot.

**Comment by uklance** [comment]
Why don't you just use the convention and store everything under `src/main/webapp` instead of copying from various non standard locations? Then you could have a single mapping from `/` to `C:/myapp/src/main/webapp`

**Comment by slavashvets** [comment]
Hello @uklance . I've update my question on StackOverflow too. I can't just restructure a project because (just an example):

1. I have some excluded files that I don't want to bring to the output folder.
2. I want to map several source folders to one output folder (e.g. `build/classes` and `build/resorces` both should be added to the one virtual JAR).
3. I want to map existing gradle caches to the virtual JAR.

Example for EAR file (`.beabuild.txt` mapping file [used by Weblogic](https://docs.oracle.com/cd/E13155_01/wlp/docs103/quickstart/location.html)):

```properties
G\:/gradlehome/.gradle/caches/modules-2/files-2.1/org.springframework/spring-aspects/4.2.1.RELEASE/1ccea288d056d6b71839b07f09c5d663f9d98104/spring-aspects-4.2.1.RELEASE.jar = APP-INF/lib/spring-aspects-4.2.1.RELEASE.jar
G\:/gradlehome/.gradle/caches/modules-2/files-2.1/org.springframework/spring-instrument/4.2.1.RELEASE/88ae98a6ca8439e118807f8a3db8af2f1b8b1b65/spring-instrument-4.2.1.RELEASE.jar = APP-INF/lib/spring-instrument-4.2.1.RELEASE.jar
G\:/gradlehome/.gradle/caches/modules-2/files-2.1/org.springframework/spring-oxm/4.2.1.RELEASE/327df2a0b268a838492d9a15d015f0495debf42b/spring-oxm-4.2.1.RELEASE.jar = APP-INF/lib/spring-oxm-4.2.1.RELEASE.jar
G\:/gradlehome/.gradle/caches/modules-2/files-2.1/org.springframework.security/spring-security-web/4.0.2.RELEASE/86f6306aa201a69d37e84fa556bd15cf79752591/spring-security-web-4.0.2.RELEASE.jar = APP-INF/lib/spring-security-web-4.0.2.RELEASE.jar
C\:/repo/subprojects/wi/src/main/webapp = wi.war
C\:/repo/subprojects/wi/build/classes/main = wi.war/WEB-INF/classes
C\:/repo/subprojects/wi/build/resources/main = wi.war/WEB-INF/classes
```
