### ISSUE TITLE
Remove references to JCenter from Gradle

### ISSUE THREAD

**Issue by alblue** [gradle/gradle#16035]
Gradle recommends the use of JCenter in a number of places on the documentation website:

* https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:maven_jcenter
* https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:declaring_multiple_repositories
* https://docs.gradle.org/current/userguide/build_init_plugin.html#sec:java_application

The JCenter repository is being shut down at the end of April, and as such Gradle needs to be updated to not depend on it any more and instead revert to `mavenCentral()`

https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

**Comment by ice1000** [comment]
I suggest deprecating the `jcenter()` method from the `repositories` code block. Also, it would be nice to have similar helper methods for other popular artifact hosting services such as Sonartype or GitHub Packages.

**Comment by julian-alarcon** [comment]
Related: https://github.com/gradle/gradle/issues/16018

**Comment by donat** [comment]
Fixed in #16176
