### ISSUE TITLE
JavaPlugin documentation states wrong default.extendsFrom

### ISSUE THREAD

**Issue by dgeissl** [gradle/gradle#16043]
### Expected Behavior
configuration documentation should follow implementation

### Current Behavior
https://docs.gradle.org/6.8.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management says that the default configuration extends from `runtimeClasspath`:

> default extends runtimeClasspath

but actually it does from `runtimeElements`.

https://github.com/gradle/gradle/blob/31f14a87d93945024ab7a78de84102a3400fa5b2/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L466

### apiElements

I was also wondering about the implementation of the `apiElements` configuration.
My guess from the [documentation](https://docs.gradle.org/6.8.1/userguide/java_library_plugin.html#sec:java_library_configurations_graph) was, that this only exists in `java-library` projects. But it is actually created in the JavaPlugin:

https://github.com/gradle/gradle/blob/31f14a87d93945024ab7a78de84102a3400fa5b2/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L455-L459

and even stranger is that it extends the `runtime` configuration - even for backward compatibility this should be `compile` or not?

### environment

Gradle 6.8.1

**Comment by big-guy** [comment]
@ljacomet is this affected by the configuration removals in 7.0?

**Comment by ljacomet** [comment]
The documentation aspect will be fixed in upcoming Gradle 7.0.
