### ISSUE TITLE
Error on publishing in artifactory When root composite project refers to included builds

### ISSUE THREAD

**Issue by BrenoJorri** [gradle/gradle#16053]
### Expected Behavior

When run gradle command :core:DeployDevelop should publish lib on artifactory 

### Current Behavior

We received the follow error: Included build /Documents/native-sdk-android/core has build path :core-architecture which is the same as included build /Documents/native-sdk-android/core

### Context

We are not allow to publish libraries in artifactory

When we update gradle 5.4.1 to 6.6.1 and Gradle-Build-info-Extractor: 4.7.5 to 4.20.0. Our gradle script stop to work

### Your Environment
[artifactoryTasks.txt](https://github.com/gradle/gradle/files/5935472/artifactoryTasks.txt)
[deployTasks (1).txt](https://github.com/gradle/gradle/files/5935571/deployTasks.1.txt)

![image](https://user-images.githubusercontent.com/20288412/107092807-fa078a00-67e2-11eb-9ab2-8c07cedff431.png)

Build scan URL:

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

Did you follow [the upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_5.html)?
