### ISSUE TITLE
Gradle 7: skip dependency validation for disabled tasks

### ISSUE THREAD

**Issue by C-Otto** [gradle/gradle#16059]
See https://github.com/spring-projects/spring-boot/issues/25126 for more details.
The new validation with messages like shown below seems to also look at disabled tasks, in my case `bootJar { enabled = false }`. As `jar` and` bootJar` share the same output, this is regarded as a dependency misconfiguration.

```
> Task :sub2:compileJava
Validation failed for task ':sub2:compileJava', disabling optimizations:
  - Task ':sub2:compileJava' uses the output of task ':sub1:bootJar', without declaring an explicit dependency (using Task.dependsOn() or Task.mustRunAfter()) or an implicit dependency (declaring task ':sub1:bootJar' as an input). This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

**Comment by oehme** [comment]
I recommend giving your normal `jar` a different classifier, e.g. `non-boot`. Dependency verification is not the only one that gets confused when there are several jar tasks with the same output file. IntelliJ also creates broken project configuration in that case.

**Comment by C-Otto** [comment]
I think that's will be done as part of https://github.com/spring-projects/spring-boot/issues/23797. Until all the Spring Boot projects benefit from that fix, I fear this Gradle warning might confuse quite a lot of Spring Boot users. A fix in Gradle would be nice (if feasible).

**Comment by oehme** [comment]
I agree, I just wanted to mention that this creates other problems too.

**Comment by wolfs** [comment]
I just merged https://github.com/gradle/gradle/pull/16087 which ignores disabled tasks for missing task dependency checking.
