### ISSUE TITLE
Provide Credentials API for in memory keys signing plugin

### ISSUE THREAD

**Issue by gabrielittner** [gradle/gradle#16056]
Currently to set up signing with in memory keys you need to do this: 
```
signing {
    val signingKeyId: String? by project
    val signingKey: String? by project
    val signingPassword: String? by project
    useInMemoryPgpKeys(signingKeyId, signingKey, signingPassword)
    sign(tasks["stuffZip"])
}
```
https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys

Since the guide already recommends to set this up using properties it would be nice if you could provide an API like the following that uses the new `Credentials` API:

```
signing {
    credentials(InMemoryPgpKeyCredentials::class)
    sign(tasks["stuffZip"])
}
```

That would make it a lot easier to set up signing. It would also be more consistent with the default not in memory signing configuration which picks up properties automatically.

**Comment by eygraber** [comment]
@gabrielittner should this be re-opened? I think a lot of issues were closed as stale, but would be re-opened if were still necessary.

**Comment by gabrielittner** [comment]
Yes, I think this still makes sense, also with the additional use case of configuration cache and not storing the key in in it

**Comment by bitspittle** [comment]
> Yes, I think this still makes sense, also with the additional use case of configuration cache and not storing the key in in it

This issue is still marked "Closed as not planned"
