### ISSUE TITLE
Start Gradle as lower priority process

### ISSUE THREAD

**Issue by staffanf** [gradle/gradle#1606]
There should an option to start gradle and it's daemon as a lower priority process to increase system responsiveness when running parallel tasks/threads.
I would argue that this should be the default.

### Expected Behavior

Gradle should not hog all system resources at normal priority as a default. If the daemon is set to start with lower priority, very little performance is lost and system responsitivity increases a lot.

### Current Behavior

Currently the wrapper starts gradle at normal priority, with or without the daemon. I would argue that the should be a choice, maybe in the wrapper setting to select default priority level for the gradle process that is started.

I would argue that the default for this should be low prio, but that is not as important as given the user the choice. 

### Context
My user environment and local VMs grid to a halt when I do heavy parallel compiles using gradle.
Running a parallel gradle build on my 8 thread/24GB/i7 developer machine makes Cinnamon (Linux Mint Window Manager) slow and my local guest virtual machine pretty much stand still.

Instead running: `nice -n 15 ./gradlew --no-daemon --parallel build` makes the user environment completely usable during the whole build and the performance loss is less than 10%.

### Your Environment

Linux Mint, Ubuntu, Debian (all same results)

**Comment by DanielThomas** [comment]
Given parallel workers and the general push towards parallel by default, this can only get worse. My MacBook is regularly a stuttering mess when I'm running builds, and I either have to limit the maximum workers or `nice` the process as @staffanf does. This'd be a great improvement.

**Comment by dylan-chong** [comment]
An important thing to mention is that on Mac OS `nice` is broken (Apple knows about this) so for the meantime we can't even run `nice -n 15 ...` :(

**Comment by oehme** [comment]
If we want to change the default, 5.0 would be a good point to do that. We should do some measurements to see the impact on default performance vs default usability.

**Comment by oehme** [comment]
For 5.0, I'm going to add an option that you can configure in your user home. Once we have some positive experience with this, we can add auto-detection, e.g. based on whether Gradle is attached to a console.

**Comment by sarnobat** [comment]
Question: does --parallel make things worse? What about --daemon? I'm on Gradle 4.8.1 (not my choice). My machine is unusable when I run gradle and I am trying to narrow down what's causing it.

**Comment by TWiStErRob** [comment]
For anyone finding this, see docs:
 * [`org.gradle.priority=low|normal`](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties)
 * [`--priority=low|normal`](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_performance)
