### ISSUE TITLE
Cannot add a PluginDeclaration with name 'com.swardana' as a PluginDeclaration with that name already exists.

### ISSUE THREAD

**Issue by swardana** [gradle/gradle#16064]
I just started using Gradle 6.8.1 and organize my new project [using buildSrc](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources). 

I have created two projects using `gradle init`.
My first project works well without any isue, but not with my second project. After run `gradle init` and run task `build` I got exception:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':buildSrc'.
> Cannot add a PluginDeclaration with name 'com.swardana' as a PluginDeclaration with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Both project sure have same domain `com.swardana` since this is my own domain, but I'm not sure why this happening?

### Expected Behavior

Executing task `build` should successfully build my project.

### Current Behavior

Executing task `build` gives me an error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':buildSrc'.
> Cannot add a PluginDeclaration with name 'com.swardana' as a PluginDeclaration with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Context

I couldn't build my project with Gradle.

### Steps to Reproduce 

Create a new project using `gradle init` command.

```
$ gradle init

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4] 2

Select implementation language:
  1: C++
  2: Groovy
  3: Java
  4: Kotlin
  5: Scala
  6: Swift
Enter selection (default: Java) [1..6] 3

Split functionality across multiple subprojects?:
  1: no - only one application project
  2: yes - application and library projects
Enter selection (default: no - only one application project) [1..2] 2

Select build script DSL:
  1: Groovy
  2: Kotlin
Enter selection (default: Groovy) [1..2] 1

Project name (default: gradle-jpms): 
Source package (default: gradle.jpms): com.swardana.gradle_jpms

> Task :init
Get more help with your project: https://docs.gradle.org/6.8.1/samples/sample_building_java_applications_multi_project.html

BUILD SUCCESSFUL in 32s
2 actionable tasks: 2 executed
```

Then execute task `build` on the newly created project.

```
./gradlew build
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/b54mtv4zsott4

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

Something does not add up in your reproducing steps and the fact that the linked scans mentions a `buildSrc` issue.

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by paigeman** [comment]
The reason why you execute build task failed is the package name you entered is `com.swardana.gradle_jpms` . This would produce the `com.swardana.gradle_jpms.java-common-conventions.gradle` and `com.swardana.gradle_jpms.java-application-conventions.gradle` files in the `buildSrc` directory. But the gradle use `indexOf(".gradle")` to generate the plugin id, which means that `com.swardana.gradle_jpms.java-common-conventions.gradle` get the plugin id `com.swardana` and `com.swardana.gradle_jpms.java-application-conventions.gradle` get the same plugin id `com.swardana`, so the `./gradlew run` failed.
By the way, you can set a breakpoint at `PrecompiledGroovyScript#PrecompiledGroovyScript(File scriptFile, TextFileResourceLoader resourceLoader)` to verify :

```java
PrecompiledGroovyScript(File scriptFile, TextFileResourceLoader resourceLoader) {
        String fileName = scriptFile.getName();
        this.type = Type.getType(fileName);
        // set breakpoint here
        this.pluginId = type.toPluginId(fileName);
        this.precompiledScriptClassName = toJavaIdentifier(kebabCaseToPascalCase(pluginId.getId().replace('.', '-')));
        this.scriptSource = new PrecompiledScriptPluginSource(scriptFile, precompiledScriptClassName, resourceLoader);
        this.scriptTarget = new PrecompiledScriptTarget(type != Type.INIT);
}
```
