### ISSUE TITLE
FAILURE: Build failed with an exception. > Checkstyle rule violations were found. 

### ISSUE THREAD

**Issue by imb2020** [gradle/gradle#16065]
[ant:checkstyle] [ERROR] src/github.com/apache/beam/sdks/java/extensions/sql/udf-test-provider/src/main/java/org/apache/beam/sdk/extensions/sql/provider/UdfTestProvider.java:21: You are using raw guava, please use vendored guava classes. [ForbidNonVendoredGuava]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdks:java:extensions:sql:udf-test-provider:checkstyleMain'.
> Checkstyle rule violations were found. 
  Checkstyle files with violations: 1 : /root/Projects/Proj1/src/github.com/apache/beam/sdks/java/extensions/sql/udf-test-provider/src/main/java/org/apache/beam/sdk/extensions/sql/provider/UdfTestProvider.java

  Checkstyle violations by severity: [error:1]

Error Description | Line
--  --
You are using raw guava, please use vendored guava classes. | 21

**Comment by ljacomet** [comment]
There is nothing to report against Gradle core. Your build applies the checkstyle plugin and there are violations. They need to be fixed in your build.
