### ISSUE TITLE
Gradle for java 15.0.2

### ISSUE THREAD

**Issue by TEJASK111** [gradle/gradle#16060]
I want to ask when you will launch gradle for java 15.0.2 .

**Comment by szpak** [comment]
Looking at the declared Gradle compatibility in the [official documentation](https://docs.gradle.org/6.8.2/userguide/compatibility.html), I would say Java 15 is supported in 6.8:
> A Java version between 8 and 15 is required to execute Gradle. Java 16 and later versions are not yet supported.

Personally, I don't have any problems using it with 15.0.2. Did you encountered any?

Unless you think it could be a bug in Gradle, a better place to ask about such as things might be a [discussion forum](https://discuss.gradle.org/).

**Comment by TEJASK111** [comment]
When I saw the release note of v6.8 and greter than it . There was nothing written about java 15 . So I thought it might be available only till java 14 . Thanks for help . Can I use v6.7.1 or I have to use v6.8  .

**Comment by TEJASK111** [comment]
@szpak  thanks for help . V 6.8 release note does not show anything about java 15 so I thought it might be available for java 14 only .
