### ISSUE TITLE
Bug in task dependency validation

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#16061]
Given the following build script:

```
plugins {
    base
}

tasks {
    val prepareBuild by registering {
        outputs.file("app/foo.txt")
        doLast {}
    }

    val sources = fileTree("app") {
        include("**/*.txt")
        exclude("**/*generated*")
        builtBy(prepareBuild)
    }

    val generateA by registering {
        inputs.files(sources)
        outputs.file("app/src/generatedA.txt")
        doLast {}
    }

    val generateB by registering {
        inputs.files(sources)
        outputs.file("app/src/generatedB.txt")
        doLast {}
    }

    assemble {
        dependsOn(generateA, generateB)
    }
}
```

When I run `gradle assemble`, I get warned that `generateB` uses the output of `generateA`. This is not true though, because of the exclude in the file tree. Interestingly, this only happens when there is the `prepare` task that also writes something to that file tree. 

Use case: A Javascript code base where lots of tasks collaborate to create one `src` folder. Separate output folders for each tool are planned, but I still think the above is a bug and should be fixed.

**Comment by wolfs** [comment]
> Interestingly, this only happens when there is the prepare task that also writes something to that file tree.

If the sources are empty for the tasks, Gradle skips the task before it does the missing task dependency detection.

> This is not true though, because of the exclude in the file tree.

The `**` includes at the beginning are problematic here. `**` automatically includes all directories. The output declaration currently declares the output as a `file`, though finally does not create anything at the location. In theory, it could create a `app/src/generatedA.txt/included.txt`, which would be included again. So there is a potential overlap between the inputs and the outputs.

You can get rid of the warning by adding an explicit ordering between your tasks via `mustRunAfter`. Another option is to be more specific what parts of the input are created by which tasks.

As you said, the best option is to use separate output folders - or at least one folder for all the generated output.

We could try to fix something on the Gradle side, for example tracking whether a task used `file` or `dir` to declare an output.

**Comment by oehme** [comment]
> If the sources are empty for the tasks, Gradle skips the task before it does the missing task dependency detection.

It also happened when there were hand-written sources. The issue still only happened with the additional task.

Agreed on everything else :+1:

**Comment by wolfs** [comment]
This was a bug after all, thank you for finding it! Fixed via https://github.com/gradle/gradle/pull/16089.
