### ISSUE TITLE
Confusing inconsistency regarding default plugin versions in TOML files

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16078]
Confusing inconsistency between settings script and TOML way to set plugin versions.

In the TOML you can have a `versions` block where you can define versions.
This corresponds to the `version` method within a version catalog.
Both ways define a version that can then be used in version refs or via `catalogName.versions.versionName`.

In the TOML you can have a `dependencies` block where you define aliases.
This corresponds to the `alias` method within a version catalog.
Both ways define a dependency alias that can then be used in bundles or via `catalogName.aliasName`.

In the TOML you can have a `bundles` block where you define bundles.
This corresponds to the `bundle` method within a verison catalog.
Both ways define a bundle that can then be used via `catalogName.bundles.bundleName`.

That far that perfect and nice.
But what I find pretty strange confusing and inconsistens is the plugin versions.
You can have a `plugins` block in the TOML where you define plugin versions.
But these are not bound to the version catalog where this file is included to, but instead they break out of that namespace and set the version outside.
There is also no according setting within the version catalog builder api.
It is not even in the same top-level block `dependencyResolutionManagement` but in `pluginManagement`.

This break-out also manifests if you have the plugin in two TOML files for different version catalogs and the build then fails with an error that multiple default version for the plugin are not supported.

To me this is majorly confusing and inconsistent, as the scope of the TOML for me is the version catalog and not something outside it, namely the plugin management block.

I also want to be able to define versions in one central place like the TOML, but this is a bit awkward to me.

**Comment by ljacomet** [comment]
Thanks for the feedback.
As it stands now, the TOML file is indeed dependency catalog + plugin versions.
The conflicting case is interesting and probably needs further thoughts.

**Comment by Vampire** [comment]
I would probably have less problems with it, if there wouldn't be the scope difference.
Defining versions, dependencies and plugin versions in one file actually feels natural (just missing the ability to reuse the version declarations for the plugin version #16077).

Just to illustrate better what I mean here an additional example:
```
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            // from(files("gradle/libs.toml")) //4
            version("version", "1") //1
            alias("dep").to("foo:bar").versionRef("version") //2
        }
    }
}
pluginManagement {
    plugins {
        id("plugin") version "1" //3
    }
}
```

Line `4` can replace lines `1`, `2` and `3` which is what feels unnatural to me.
You reference the file in there to define the `libs` catalog but it affects the default plugin versions of the 2nd grade uncle configuration block and in the worst case get unexpected conflicts.

**Comment by melix** [comment]
It is indeed an _intentional_ tradeoff we had to take. Because there's an existing API for importing plugins (`pluginManagement`), the catalog actually delegates to this API. Obviously, it's not as rich as the new catalog API. That's something we can change in a future version.

**Comment by Vampire** [comment]
Some additional thought I had recently.

I guess to solve this inconsistency, either the API for defining a default plugin version has to move inside the version catalog declaration part so that it is consistent, or maybe better remove the possibility to declare default plugin versions in the TOML, but instead make the accessors (or at least the `VersionCatalogsExtension`) available in the `pluginManagement` block for the default catalog, this way the versions from the catalog can be used for the plugin version declaration.

I think I'd prefer the latter option. This would also solve the problem of having default plugin versions in multiple catalogs and remove the need for `excludePlugin` all together. Actually while thinking about it, there is also a semantical difference. All other things you define in the catalog are only part of a catalog you can pick from, while the default plugin versions directly affect the build, which is also the reason you need `excludePlugin` at all. By "just" making the accessors (or extension) available in the `pluginManagement` block, I think semantics and scopes suddenly align again. :-)

To be clear, I do not want to loose the ability to define the version per-se in the TOML file.
I even want to be able to re-use a version from the `versions` part for the plugin, as for example Kotlin plugin and Kotlin dependencies should be version-aligned.
But maybe a better way would be to have the default plugin version declaration where it used to be, but with a version value from the catalog.

**Comment by melix** [comment]
To be clear:

> This break-out also manifests if you have the plugin in two TOML files for different version catalogs and the build then fails with an error that multiple default version for the plugin are not supported.

See also #16079 which is fixed by #16234. There was a bug which prevented exclusions from working properly.

> I think I'd prefer the latter option. This would also solve the problem of having default plugin versions in multiple catalogs and remove the need for excludePlugin all together

This is one option, but there are at least 2 others at hand:

1. clarify in the docs that you shouldn't define plugin versions in the TOML file if you don't want them to be reused by consumers
2. isolate plugin versions in their own file

None of those require any change to the current APIs (`pluginManagement` or `dependencyResolutionManagement`).

**Comment by Vampire** [comment]
Of course you can use it so that it works.
If you have plugin versions in mutliple TOMLs you can exclude the plugin (after the fix is merged) and you can also just be aware of what you are doing if you know the traps.
That's just not the point of my issue here.

The point is, that
- you mix different scopes which at least confused me (you import the file inside a version catalog and it affect the 2nd grade uncle directly)
- and the default plugin versions are not following the nature of a catalog which is just a list of things to pick from if you want to use them, the default plugin versions directly affect the build actively.

Well, for the second point one could of course argue that you are picking from the catalog by applying the plugin without version and you are probably right about that, now that I think about it.

But what remains is the inconsistency I demoed at https://github.com/gradle/gradle/issues/16078#issuecomment-776056121.

Of course you can say that you don't care about it and want to keep it like it is, no problem.
It was just some feedback I felt and thought I let you know. :-)

But one more thought, we need your point 3. either way I think.
I assume you meant something like
```kts
pluginManagement {
    plugins {
        fromCatalog("libs")
    }
}
```
or
```kts
pluginManagement {
    plugins {
        id("plugin") version fromCatalog("libs")
    }
}
```
Why I say we need it anyway is settings plugins.

If we are now able to define all versions in one central place, it would be really nice to also be able to define settings plugins versions in the same place.
Currently this is of course not possible as settings plugins are applied before the version catalog is evaluated, but with such an option in `pluginManagement` it could be made possible.

**Comment by ljacomet** [comment]
> * and the default plugin versions are not following the nature of a catalog which is just a list of things to pick from if you want to use them, the default plugin versions directly affect the build actively.

That's a very good point and something we need to think about.

**Comment by ljacomet** [comment]
Thanks for the feedback provided here. The Gradle team decided to pull plugins support from the TOML file for now given the differences highlighted here.
We will investigate re-introducing a solution that does not have the same drawbacks at a later point.

**Comment by vab2048** [comment]
The reference docs (https://docs.gradle.org/current/userguide/platforms.html) say that "the [plugins] section is used to declare plugins". Is this outdated/wrong for Gradle 7.3? 

What is the current best way to declare a version once and use it among both dependencies and plugins?

I am thinking of the scenario where we declare the spring-boot version in the [versions] block, the BOM in the [libraries] block and the plugin in the [plugins] block. They all need access to the same version and currently I am duplicating this in the TOML file and the `pluginManagement` block in the settings.gradle

**Comment by vab2048** [comment]
Answering my own question from the previous post for others who have the issue in the future. Here is a complete example to have a single spring boot version defined in the toml file and getting everything to work:

./gradle/libs.versions.toml:

```
[versions]
spring-boot = "2.5.6"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
```

In the build.gradle file:
```
plugins {
    alias(libs.plugins.spring.boot)
    id 'java'
}
// ...

dependencies {
    implementation platform(libs.spring.boot.bom)
    implementation libs.spring.boot.starter.web

    testImplementation libs.spring.boot.starter.test
}
```
