### ISSUE TITLE
Avoid deprecation warning when accessing "properties" under Java Plugin

### ISSUE THREAD

**Issue by m9aertner** [gradle/gradle#1607]
Even simple access to "properties" triggers deprecation warnings on "JavaPluginConvention.getDependencyCacheDirName()", if the Java plugin is applied.

These warnings are not actionable on the user side, since they are caused by some Gradle-internal access within the Java plugin.

### Expected Behavior

Merely asking for a property  should not cause the warnings to be emitted.

### Current Behavior

Apply Java plugin, ask for some property `println(properties."abc")`, warning gets emitted.
Remove the Java plugin and the warnings go away.

### Context
A "clean" build for us has **no** warnings, ideally.

Surely that's not a bug  but more a cosmetic thing.

### Steps to Reproduce (for bugs)

Call `.../gradlew -Pabc=def` with a two-line build file:

```
apply plugin: 'java'

println(properties."abc")
```

Output:
```
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources NO-SOURCE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test SKIPPED
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
The JavaPluginConvention.getDependencyCacheDirName() method has been deprecated and is scheduled to be removed in Gradle 4.0.
        at build_p0s5phd54shk0n06m606ax3t.run(...\test\build.gradle:3)
The JavaPluginConvention.getDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
        at build_p0s5phd54shk0n06m606ax3t.run(...\test\build.gradle:3)
def
:help

Welcome to Gradle 3.4.1.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

BUILD SUCCESSFUL

Total time: 6.156 secs
```

### Your Environment

Gradle 3.4.1

**Comment by bmuschko** [comment]
You are using [Groovy's ExpandoMetaClass](http://docs.groovy-lang.org/2.4.7/html/api/groovy/lang/ExpandoMetaClass.html#getProperties()) here and not Gradle's properties mechanism. The way you [access the property](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#findProperty(java.lang.String)) is as follows: 

    project.findProperty('abc')

**Comment by m9aertner** [comment]
Oops. Thanks! Works. Sorry for the confusion. We _are_ using `project.findProperty()` elsewhere so I'll fix that on my side. Closing.
