### ISSUE TITLE
Test task added in afterEvaluate is only executed if test sourceset was compiled

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1608]
# Given

## *`build.gradle`*

```
apply plugin: 'java'

repositories {
    jcenter()
}

sourceSets {
    integTest
}

dependencies {
    testCompile 'junit:junit:4.12'
    integTestCompile 'junit:junit:4.12'
}

afterEvaluate {
    task integTest(type: Test) {
        testClassesDir sourceSets.integTest.output.classesDir
        classpath = sourceSets.integTest.runtimeClasspath
    }
}
```

## *`src/integTest/java/FooIntegTest.java`*
```
public class FooIntegTest {
    @org.junit.Test
    public void fooTest() {
        System.out.println("\n\n\n**********\nfoo integ test\n**********\n\n\n");
    }
}
```

## *`src/test/java/FooTest.java`*
```
public class FooTest {
    @org.junit.Test
    public void fooTest() {
        System.out.println("\n\n\n**********\nfoo test\n**********\n\n\n");
    }
}
```

# Problem

```
$ ./gradlew clean integTest
:clean
:compileIntegTestJava
:processIntegTestResources NO-SOURCE
:integTestClasses
:integTest NO-SOURCE

BUILD SUCCESSFUL

Total time: 1.271 secs
```

Adding `-i` reveals the line `file or directory '<PROJECT_HOME>\build\classes\test', not found` right before the line saying `:integTest NO-SOURCE`.

If you compile test first the integ tests are executed:

```
$ ./gradlew clean compileTestJava integTest
:clean
:compileJava NO-SOURCE
:processResources NO-SOURCE
:classes UP-TO-DATE
:compileTestJava
:compileIntegTestJava
:processIntegTestResources NO-SOURCE
:integTestClasses
:integTest

BUILD SUCCESSFUL

Total time: 1.827 secs
```

Commenting out the `afterEvaluate` in `build.gradle` also makes it work, but I need it added in `afterEvaluate` in our build.

I'm not sure what is causing this behaviour, but I strongly assume this is a Gradle bug and I also didn't find a work-around up to now besides adding a `dependsOn` from `integTest` to `compileTestJava`.

**Comment by Vampire** [comment]
Well, the reason is the `JavaBasePlugin` that has an `afterEvaluate` block in `configureTest` that executes on all tasks `withType(Test.class)`, assuming the `Test` tasks all exist already at this point in time and are configured properly. My `Test` task is added after that, which causes the closure to be run immediately on adding, before the configuration is done. The `configureBasedOnSingleProperty` method then sets input files with property name `nonEmptyCandidateClassFiles` from the candidate class files which are not set correctly yet at this point in time.

As a workaround I added my task now outside of `afterEvaluate`. It was necessary, because the task depends on another task and its output file that also needs to be added in an `afterEvaluate`. But I depen on it by task name as String now, add its output files as input files to my task from a closure for late evaluation and set the system property where I need the file path in a doFirst closure. This time up-to-date check should work properly while the task is configured as intended.

Despite this work-around I still think this is a Gradle bug.

**Comment by Vampire** [comment]
Actually in my specific case I don't need the input file, as I have `outputs.upToDateWhen { false }` anyway for this task as the result depends on the state of the database.

**Comment by Vampire** [comment]
@bmuschko do you really think this a question? I'd say this is a bug, not a question. :-)

**Comment by oehme** [comment]
@Vampire can you verify whether this is still the case in 4.1? I changed this code a while ago to only run right before the task is executed instead of using `afterEvaluate`.

**Comment by octylFractal** [comment]
Is this still an issue? If no reply in 7 days, I will close this issue.

**Comment by Vampire** [comment]
No, seems to work fine now, sorry for the delay.
