### ISSUE TITLE
Java toolchain support: failed to create parent directory /tmp/expandedArchives/...

### ISSUE THREAD

**Issue by matthiaskraaz** [gradle/gradle#16093]
### Expected Behavior
No exception during unpacking of downloaded JDK.

### Current Behavior
Exception during unpacking of downloaded JDK.

### Context
Linux

Gradle 6.8.2

build.gradle of user 1:

```
  test {
        javaLauncher = javaToolchains.launcherFor {
          languageVersion = JavaLanguageVersion.of(8)
          vendor = JvmVendorSpec.ADOPTOPENJDK
        }
  }
```

build.gradle of user 2:

```
  test {
        javaLauncher = javaToolchains.launcherFor {
          languageVersion = JavaLanguageVersion.of(11)
          vendor = JvmVendorSpec.ADOPTOPENJDK
        }
  }
```

Developer very happy about new toolchain feature of Gradle.

### Steps to Reproduce 

1. Run gradle with user 1 using toolchainspec A. 
2. Run gradle with user 2 on same host using toolchainspec B.
3. Observe exception:

```
   > Unable to download toolchain matching these requirements: {languageVersion=8, vendor=ADOPTOPENJDK, implementation=vendor-specific}
      > Could not copy tar entry /home/matthias/.gradle/jdks/adoptopenjdk-8-x64-linux.tar.gz!jdk8u282-b08/ to '/tmp/expandedArchives/adoptopenjdk-8-x64-linux.tar.gz_5e11782de1d81f0b251caf949abef794/jdk8u282-b08'.
         > Failed to create parent directory '/tmp/expandedArchives/adoptopenjdk-8-x64-linux.tar.gz_5e11782de1d81f0b251caf949abef794' when creating directory '/tmp/expandedArchives/adoptopenjdk-8-x64-linux.tar.gz_5e11782de1d81f0b251caf949abef794/jdk8u282-b08'
```

User 2 cannot unpack JDK, because user 2 tries to re-use temporary directory created by user 1.

### Your Environment
See context.

**Comment by matthiaskraaz** [comment]
Come on, people! Perfect reproduction instructions, culprit easily locatable in the source code, simple solution (random name for temporary directory instead of "expandedArchives"). This is low hanging fruit.

**Comment by jbartok** [comment]
Closing this issue, because it's obsolete. 
`/tmp/expandedArchives` is no longer involved in toolchain auto-provisioning in recent Gradle versions.
