### ISSUE TITLE
Nested included build is not visible from including build

### ISSUE THREAD

**Issue by AKhranovskiy** [gradle/gradle#16099]
There is a Gradle plugin project which is included in another Gradle plugin project which is included in the top-level project. The top-level project applies both plugins. The middle project applies the nested plugin.

Both plugins are available in the top-level project. But the middle project fails to resolve the nested plugin.

Note, that behavior is the same if the nested project is moved one level up, next to the middle project.
 
```
:top
+ build.gradle.kts
   plugins { 
      id("intermediate-plugin")
      id("nested-plugin")
   }
+ settings.gradle.kts
   includeBuild("middle-plugin")
\ :middle-plugin
  + build.gradle.kts
     plugins { id("nested-plugin") }
  + settings.gradle.kts
     includeBuild("nested-plugin")
  \ :nested-plugin
    + build.gradle.kts
    + settings.gradle.kts
```

### Expected Behavior
Included build can use project that it includes as build.

### Current Behavior
Included build cannot use project that it includes as build.

### Context

I have a plugin that adds some functionality to projects. Then I have another plugin that adds automatic versioning.
I need to use the versioning plugin in the main projects and in the plugin project. I want to make it via included builds.

### Steps to Reproduce 

https://github.com/AKhranovskiy/gradle-nested-include-builds

### Your Environment

Gradle 6.8.2 fails https://gradle.com/s/gjsqiehpivjdu
Gradle 7.0-milestone-1 works! https://gradle.com/s/wra35mqedot2u

**Comment by bmuskalla** [comment]
@AKhranovskiy Thanks for the reproducer. It sounds like this got solved with 7.0 (to be released within the next few days).

I'm closing this for now as there are no plans to backport composite-build changes at this point. Let me know if I overlooked sm
