### ISSUE TITLE
Gradle startup should fail explicitly when running on OpenJ9 JDK

### ISSUE THREAD

**Issue by donat** [gradle/gradle#16095]
Gradle does not support, nor have proper test coverage when operating on an OpenJ9 JDK. Gradle's behavior on OpenJ9 can be confusing to users: it might work, or it might just crash without any notifications: https://github.com/eclipse/buildship/issues/1060#issuecomment-776525221.

Gradle should fail at startup with an explicit message.

**Comment by bmuskalla** [comment]
We decided to not fail hard on J9 but investigate existing issues to see if there is any need for action wrt J9 support.
