### ISSUE TITLE
Strange behavior of the JavaExec.getCommandLine() method

### ISSUE THREAD

**Issue by rkhomenko** [gradle/gradle#16098]
### Expected Behavior
I wrote a simple plugin that adds a task `TestTask` to the project:
```java
public class TestPlugin implements Plugin<Project> {
    @Override
    public void apply(@Nonnull Project project) {
        TaskContainer tasks = project.getTasks();
        Task task = tasks.create("test-task", TestTask.class);
    }
}
```
I want to get command line arguments for `bootRun` task from `TestTask`:
```java
public class TestTask extends DefaultTask {
    @TaskAction
    void run() {
        var log = getLogger();
        TaskContainer tasks = getProject().getTasks();
        JavaExec bootRun = (JavaExec) tasks.findByName("bootRun");
        bootRun.getCommandLine().stream().forEach(l -> log.warn(l));
    }
}
```
```bash
./graldew test-task
```
In Gradle version 6.5.1 this code prints path to Java executable and all command line arguments.

### Current Behavior
In Gradle version 6.8.2 `getCommandLine()` method returns list with single null value.

### Context

I have a project with a lot of sub-projects, each of which is a SpringBoot application. For integration testing, I wrote a plugin that launches all services. To do this, I receive the `bootRun` task command line arguments, modify them somewhat and create processes using the `ProcessBuilder` class. In 6.8.2 version my plugin doesn't work as I can't get the command line arguments for the `bootRun` task.

### Steps to Reproduce 
I prepare [simple project](https://github.com/rkhomenko/gradle-getcommandline-bug-demo) to demonstrate the bug.

### Your Environment

ArchLinux, OpenJDK Runtime Environment (build 14.0.2+12)

Build scan URL: https://scans.gradle.com/s/l3l7ukhflixm4

**Comment by ptmt** [comment]
It seems that it fails because executable is not set. And executable is set only in `exec`: https://github.com/gradle/gradle/blob/06e40c03cdda4151f01e5f3529faea97c4abd08f/subprojects/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java#L152

There's an extremely fragile workaround: crafting the command line manually. 

Get the path to java via internal API: `org.gradle.internal.jvm.Jvm.current().getJavaHome()`

Add the jvm arguments:
```
String arguments = run.getAllJvmArgs().collect {
                        if (it != null && it.contains(" ")) "\"$it\"" else it
}.join(" ")
```

Classpath:

```
List<String> classPath = new ArrayList<String>()
classPath.add(org.gradle.util.CollectionUtils.join(File.pathSeparator, run.getClasspath()))
String classPathString = classPath.collect {
    if (it.contains(" ")) "\"$it\"" else it
}.join(" ")
```

The final result:

```
${org.gradle.internal.jvm.Jvm.current().getJavaHome()}/bin/java ${command} -cp $classPathString ${run.getMain()}"
```
