### ISSUE TITLE
Indicate Gradle's continued progress in absence of intra-operation updates

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1609]
Provide motion in output to indicate Gradle's working if build operations are long-running.

### Expected Behavior
Each worker status line has an additional suffix with the duration it has been executing.

This duration is formatted according to the smallest unit that can represent the duration in one number. For example:

```
 > [:foo:compileJava] 0.1s
 > [:bar:compileJava] 2s
 > [:baz:compileJava] 3m
```

This has the visual effect of updating frequently for small tasks and infrequently for larger tasks. We an also choose to add color as Buck does for long-running tasks to give focus to slow tasks when there are a large number of workers producing output.

### Current Behavior
The Gradle console looks like it's hung when workers are working in the background and not providing updates.

### Implementation
`Operations` data store knows the time since each operation was started. The 
`StatusBarFormatter` can choose to render an operation slightly differently depending on its lifespan.

### Open Issues
* How do we render timing of parent operations?
* ProgressOperations hierarchy is broken for buildSrc and included builds

**Comment by lacasseio** [comment]
This work was superseded in favor of https://github.com/gradle/gradle/issues/1653. We will go down the route of adding more granular progress tailored to the work in progress.
