### ISSUE TITLE
Build cache should preserve modification times

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#16103]
I was working on caching node_modules and noticed that Gradle's up-to-date checking was really fast even when npm was executed. I wondered how that could be (since all the files are recreated) and it's because npm uses fixed modification times for the files it creates. This is great because it means that the CachingFileHasher will already contain the hash for that file and so the post-execution snapshot is quick.

However, when node_modules comes from the build cache, all the modified timestamps are set to the current time, meaning that the CachingFileHasher no longer has information about them and Gradle has to do extra work the next time the VFS is invalidated.

I think the build cache should preserve modification times. Related to #1252

**Comment by lptr** [comment]
We used to have this functionality, but ultimately removed it: https://github.com/gradle/gradle/pull/2667

I couldn't find a definitive description of why we did this, but my assumption is a combination of the following:

- in general it is hard to handle file times when it comes to dates shared across computers, file systems and time zones,
- with restoring file dates it is possible for certain files to go "backwards in time," which can confuse the tools invoked to work with them,
- restoring file dates takes additional time.

We can re-evaluate this decision, though we'd need some strong evidence that it's worth it for a broad-enough use case. Would you be interested in providing that benchmark?

**Comment by oehme** [comment]
I'm afraid the node_modules case is the only one I can provide at the moment. Note sure how many other tools provide consistent timestamps like it.

**Comment by lptr** [comment]
How does `node_modules`'s consistent timestamps work? Does it use a fixed timestamp for all files? Does it reuse timestamps from the published artifacts?

**Comment by oehme** [comment]
It uses a fixed timestamp (Sat 26 Oct 1985 09∶15∶00 AM CET)

**Comment by jbartok** [comment]
@lptr is this still a relevant issue?

**Comment by lptr** [comment]
I don't think we want to do this, no.
