### ISSUE TITLE
Possibility for plugin to influence accessors generation for Kotlin DSL

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16107]
The case I have right now is, that I have a plugin with an extension.
The extension can be used to configure zero, one, two or three of the use-cases `A`, `B` and `C` in a `DomainObjectSet`.
Depending on the configured use-cases the plugin adds two tasks for each like `fooA`, `barA`, `fooC` and `barC` for use-cases `A` and `C`.
Due to the way the accessors are generated, there are no accessors for those tasks generated at all, as in the dummy project that is used for that, no use-case is configured of course.

It is probably problematic and error-prone to also copy the extension confiugration to the dummy project as the configuration can be rather complex and also use accessors and so on.

But maybe there can be a way found how the plugin can programmatically influence what accessors are generated.
The valid use-cases in my example are values of an enum so the possible set of tasks could easily be calculated.
Currently if I want to use accessors, I have to hand-code them and if I add a use-case, I also have to remember to add the accessors for it.

**Comment by vlsi** [comment]
Here's a relevant thread: https://gradle-community.slack.com/archives/CAD95CR62/p1598630780094100

**Comment by mlopatkin** [comment]
This is unlikely to get implemented because accessors are generated before we look into the build script so we cannot extract information from it. We can imagine an API for plugin to say "generate accessors A, B, C, I'll provide some of them later depending on the exact configuration" but this leaves us to decide what the accessor should do if, for example, the A thing isn't provided. The plugin authors can already provide the extension functions for A, B, C. It's true that they have to remember about that, but with potential API this will most likely be the case as well.

**Comment by vlsi** [comment]
> That is exactly what I request here.
>An API so that a plugin can contribute to the accessors generation.

@Vampire , could you please suggest an exact use case when the accessor is needed?
I don't understand the samples with A/B/C.

>then either it has to put them into the org.gradle.kotlin.dsl namespace, which I consider bad practice, or the consumer has to import the accessor

There are [203 packages which are imported by default](https://docs.gradle.org/current/userguide/writing_build_scripts.html#script-default-imports), and you could put the manually-created accessor to a **root package**. The accessors from the root package do not require imports.

**Comment by Vampire** [comment]
>> @Vampire , could you please suggest an exact use case when the accessor is needed?
>
> I don't understand the samples with A/B/C.

The use-case in the original description is a concrete use-case that I had in a real project, just anonymized.

> There are [203 packages which are imported by default](https://docs.gradle.org/current/userguide/writing_build_scripts.html#script-default-imports), and you could put the manually-created accessor to a root package. The accessors from the root package do not require imports.

So?
All are in the `org.gradle...` namespace, so should imho not be used by anyone but Gradle.
Putting classes in foreign packages is imho always bad practice and at most a work-around for something like monkey-patching something through parent classloader.
The same for the root package, putting classes in it is also bad practice.

Just think about JPMS (even though Gradle does not or not yet run on the module path). That even fails execution completely if multiple modules have classes in the same package, which also is a strong sign that this is not considered a good idea.

**Comment by vlsi** [comment]
I still do not understand the use case. Do you mean you want somehow ask Gradle to generate accessors for taskA, taskB, and taskC?
What if taskB does not exist? It looks like your plugin creates taskB only if the user creates B, so if the user does not create B, then the accessor for taskB would be invalid

**Comment by Vampire** [comment]
Exactly.
Well, the plugin can have any fancy logic, it could also parse the build script itself to find out what is configured and let Gradle generate accessors for it.

Or it can let it create accessors for all possibilities.
Yes, there might be accessors of things then not available at runtime, but when hard-coding the accessors it is just the exact same,
just that then you always have to hard-code any possible accessor you want to provide, while with a dynamic approach you could maybe calculate it.

In the example above it is about tasks, but it could be anything.

If you right now use cross-project configuration - though you shouldn't - you also have the same, as you can use the accessors of the cross-configurer on the cross-configuree, where the accessed elements might not be present, ...
