### ISSUE TITLE
Change default log level from lifecycle to warn

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1610]
### Expected Behavior

- Change the default log level from `LIFECYCLE` to `WARN`.
    - The option will apply when Gradle is executed from the command line.
    - The option will apply when Gradle is executed with the tooling API.
- Compiler warnings are rendered on `WARN` log level.
- [JVM test logging](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.logging.TestLoggingContainer.html) is rendered with `WARN` log level. Executing a build with `WARN` or `LIFECYCLE` delivers the same test log events: just failed tests.
- The build result summary and task execution statistics need to be rendered with `WARN` log level.
- Links for generated reports (e.g. [profile report](https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:profiling_build)) will be rendered with `WARN` log level.
- The [build comparison plugin](https://github.com/gradle/gradle/blob/master/subprojects/build-comparison/src/main/groovy/org/gradle/api/plugins/buildcomparison/gradle/CompareGradleBuilds.java#L285-L287) will render the report link for a failed comparison on `LIFECYCLE` level if the plugin was configured to ignore failures.
- [Incremental compilation warnings](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/IncrementalCompilerDecorator.java#L65-L85) will stay on `LIFECYCLE` log level as they do not necessarily need to be rendered.
- [Build output cleanup messages](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/cleanup/DefaultBuildOutputDeleter.java#L43-L51) will be rendered with `LIFECYCLE` log level instead of `QUIET`.
- [GradleRunner](https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/GradleRunner.html) will execute tests with the `LIFECYCLE` argument by default to ensure compatibility with existing test code. The `GradleRunner` is assumed to be tooling output which should expose the same output as `console=plain`.
- All documentation is updated to reflect the change.
    - Update user guide.
        - Information on general logging.
        - Information on test logging.
    - Clearly indicate the implications in the release notes.

After the release of 4.0 the following work needs to be performed:
- Plugin development guides and trainings are updated after the release of the feature (see https://github.com/gradle/gradle-private/issues/863).
    - Add new section to plugin development guides to ensure proper usage.
    - Update training material.

Users that still want to see additional output can change the log level to `LIFECYCLE`: https://github.com/gradle/gradle/issues/1920, https://github.com/gradle/gradle/issues/1919

### Current Behavior

The default log level is set to `LIFECYCLE` producing far more output than we want.

### Context
This is a substory of the design spec.

### Open issues

- Does this affect the [mapping of Ant log level to Gradle log levels](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/project/ant/AntLoggingAdapter.java#L103-L115) and needs to be changed accordingly?
- Building a model with the tooling API [does not render the same progress messages anymore](https://github.com/gradle/gradle/blob/master/subprojects/tooling-api/src/integTest/groovy/org/gradle/integtests/tooling/m5/ToolingApiModelCrossVersionSpec.groovy#L34). It also doesn't allow for passing in an argument for changing the logging. OK?

**Comment by eriwen** [comment]
From @bmuschko 

> Goal of the story:

Change the default log level from lifecycle to warn.
The option will apply when Gradle is executed from the command line.
The option will apply when Gradle is executed with the tooling API.
Introduce the new log level lifecycle to be able to switch back to the current default log level. The log level can be provided by command line in long and short notation.
The command line option is going to be -l or --lifecycle.
The command gradle -? renders the new command line option.
The new lifecycle option can be passed to the tooling API.
The build result and task execution statistics need to be rendered with warn log level. The outputs are rendered with default log level.
All documentation is updated to reflect the change.

**Comment by bmuschko** [comment]
PR: https://github.com/gradle/gradle/pull/1952
