### ISSUE TITLE
Tooling API TestProgressEvents ignore test display name

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#16115]
Tooling API TestProgressEvents do not contain test's display name modified by JUnit5 capabilities.

### Expected Behavior

Tooling API TestProgressEvents should contain information about test display name. Looks like, it should go into one of TestOperationDescriptor's fields

### Current Behavior

Nowhere inside TestProgressEvent one can find a test display name, set by JUnit framework

### Context

Truing to use TestProgressEvent to track test execution from JUnit test, decorated with 

    @DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)

### Steps to Reproduce 

* [sample with Junit5 tests and sample TAPI client](https://github.com/gradle/gradle/files/5964660/junit5-display-name-sample.zip), unpack it
* `cd` into `gradle-tapi-client`
* execute `gradlew run`
* output contains TestProgressEvents data, received while running a test. It should contain (mind space instead of underscore)
> successful test

 but it does not.

### Your Environment

Build scan URL: https://gradle.com/s/efromcoziqwne

**Comment by bmuskalla** [comment]
@melix started some of the work (see #15340) towards this. Would you be able to check whether this already satisfies your usecase? It will be part of the 7.0 release

**Comment by bmuskalla** [comment]
See also #5975

**Comment by nskvortsov** [comment]
@bmuskalla checking this would be as easy as changing wrapper versions in attached project ;-)

**Comment by nskvortsov** [comment]
Display name contains required string. This issue can be closed as resolved in 7.0

**Comment by bmuskalla** [comment]
Thanks, @nskvortsov for checking, and sorry for putting you on the spot there. The reproducer was super useful but I didn't investigate in detail as I was doing mass-triage :)
