### ISSUE TITLE
Support resolving build script dependencies against dependency constraints from a platform project

### ISSUE THREAD

**Issue by twwwt** [gradle/gradle#16113]
### Expected Behavior
If a build script declares build script dependencies; e.g.
```groovy
buildscript {
   dependencies {
        classpath group: 'commons-codec', name: 'commons-codec', version: '1.2'
    }
}
```
it should be possible to refer (implicitly) to a dependency constraint from a platform project. In particular, this should allow to specify just an artifact's group and name and resolve the version based on a constraint.

### Current Behavior
Buildscript dependencies must be specified including a version.

### Context
We want to make sure that, whenever needed, a build script dependency and a "normal" dependency specified for some configuration use precisely the same artifact, version.

**Comment by ljacomet** [comment]
You should be able to reference a plaftorm from the `dependencies` block in `buildscript`.

However there is no feature to guarantee consistency between buildscript classpath and application classpath in Gradle.

**Comment by twwwt** [comment]
> You should be able to reference a plaftorm from the `dependencies` block in `buildscript`.

Correct. The following works:
```groovy
buildscript {
   dependencies {
        classpath platform(project(':my-platform-project-that-defines-a-constraint-on-commons-codec'))
        classpath 'commons-codec:commons-codec'
   }
}
```
I wasn't aware of this when filing this issue.

This issue can be closed.

**Comment by ljacomet** [comment]
Just for completeness: https://docs.gradle.org/current/userguide/resolution_strategy_tuning.html#resolution_consistency

Though like I said, it does not work between buildscript classpath and regular project dependencies.
