### ISSUE TITLE
A version used in `[plugins]` doesn't compile if the plugin is applied in the root `settings.gradle.kts`.

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle#16125]
I am having problems with `[plugins]`, first image is working, but if I remove the plugin version from settings.gradle.kts and I add it to the TOML file, the project doesn't compile.
Stacktrace:
```
* What went wrong:
Plugin [id: 'com.pablisco.gradle.auto.include'] was not found in any of the following sources: 
```
![image](https://user-images.githubusercontent.com/7463564/107747847-6a009d80-6d18-11eb-862c-934629afe2fb.png)

![image](https://user-images.githubusercontent.com/7463564/107747859-6e2cbb00-6d18-11eb-9ed2-2a7c58cb3001.png)

**Comment by Vampire** [comment]
Additional info, if you do the programmatic version instead:
```kts
pluginManagement {
    plugins {
        id("com.pablisco.gradle.auto.include") version "1.3"
    }
}

plugins {
    id("com.pablisco.gradle.auto.include")
}
```
it works.

While this might not make too much sense for a settings plugin actually.
But when you define the version in the TOML, imho it would make more sense again.

The `pluginManagement` block is special. It is evaluated separately first, to also be able to define repositories, id->artifact mappings and default versions for settings plugins.
I guess the `dependencyResolutionManagement` does not follow that same pattern and thus it does not work for settings plugins.

If the solution is, that the `dependencyResolutionManagement` also is calculated separately first, that could also make it possible to provide the accessors for the TOML or version catalog in the settings script which would be nice.

**Comment by melix** [comment]
This is an expected limitation as described by @Vampire . It's a chicken and egg problem: so that a settings plugin can influence the `dependencyResolutionManagement` section, for example to introduce repositories or import catalogs, then it has to be loaded _before_ the `dRM` block. So it means that a settings plugin _cannot_ take its version from a catalog declared within the block itself.

**Comment by Vampire** [comment]
Oh, that's sad, so you can actually not declare all versions in one central place if you use TOML, only if you use the api. :-(

**Comment by melix** [comment]
It's not "only if you use the API". Even if you use the API _within the `dependencyResolutionManagement` block you'd have the problem. That's why you can have settings plugins too.

**Comment by JavierSegoviaCordoba** [comment]
Yeah, I think it is not even possible to try to get the version programmatically because it has to use a hardcoded `String`, sample:

```
internal val Project.autoIncludeVersion: String
    get() = File("$rootDir/gradle/gradle-plugin-dependencies.toml")
        .readLines()
        .first { it.contains("autoInclude") }
        .split("\"")[1]
```

**Comment by Vampire** [comment]
> It's not "only if you use the API". Even if you use the API _within the `dependencyResolutionManagement` block you'd have the problem. That's why you can have settings plugins too.

How would you define the plugin default version within the `dependencyResolutionManagement` block?
I meant using
```kt
pluginManagement {
    plugins {
        id("com.pablisco.gradle.auto.include") version "1.3"
    }
}

plugins {
    id("com.pablisco.gradle.auto.include")
}
```
which is the api-way to define the default plugin version, isn't it?

On the other hand, the `pluginManagement` block does not have the same constraint syntax the `plugins` block has, so there you do not need to use a `String` literal but could indeed read the version from the file programmatically.

So I think you could actually do
```kt
pluginManagement {
    plugins {
        id("com.pablisco.gradle.auto.include") version File("$rootDir/gradle/gradle-plugin-dependencies.toml")
            .readLines()
            .first { it.contains("autoInclude") }
            .split("\"")[1]
    }
}

plugins {
    id("com.pablisco.gradle.auto.include")
}
```
or use an actual TOML parser.

**Comment by ljacomet** [comment]
The version catalog feature will not have plugin support in the TOML file for this reason and others, see #16078.

We might consider adding support in a different form later.

**Comment by gabrielittner** [comment]
Is there a chance to also get `pluginManagement` support now that plugins are supported again by version catalogs?
