### ISSUE TITLE
Script file names in stack traces need a path

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16122]
If you have 50 projects and all have build script name `build.gradle.kts` and there is some exception, the exception stack trace always only contains the plain name. This makes it very hard to determine in which actual file the problem is and navigating from the stack trace most likely leads to the wrong file. The same for debugging the script if you have a breakpoint or navigate in the stack frames you are often taken to the wrong file.

Renaming the build script names is the only viable work-around.
I usually do that anyway except for the root build script but it is still unnice, especially if you work with other peoples builds where you are not allowed to change that.

**Comment by vlsi** [comment]
@Vampire , do you think this is a duplicate of https://github.com/gradle/gradle/issues/10823 ?

**Comment by Vampire** [comment]
indeed
