### ISSUE TITLE
`processDebugAndroidTestManifest` is wrongly out of date on second run with the configuration cache enabled

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#16133]
### Expected Behavior

`processDebugAndroidTestManifest` is up to date on second run with the configuration cache enabled

Two `DefaultPublishArtifact` instances pointing at the same artifact should be equal.

### Current Behavior

`processDebugAndroidTestManifest` is wrongly out of date on second run with the configuration cache enabled

Two `DefaultPublishArtifact` instances pointing at the same artifact are not equal because that types doesn't have an `eauals` method.

### Context
See discussions at 
* https://gradle.slack.com/archives/C01536UAXBL/p1613000317002100
* https://gradle.slack.com/archives/C10J6STFZ/p1613134680091300

### Steps to Reproduce 

Using this project: [default_publish_artifact.zip](https://github.com/gradle/gradle/files/5972516/default_publish_artifact.zip)

Run `./gradlew :app:proDATManifest --configuration-cache && ./gradlew :app:processDATManifest --configuration-cache` twice. Second run should be up to date.

**Comment by stephanenicolas** [comment]
I can confirm that the build `gradle-6.8.2-20210212000000+0000` fixes the issue. In 2 ways indeed:
1. the processDebugAndroidTestManifest task is now up to date on a second CC run.
2. when forced to re-execute with --rerun-tasks , the second run creates the same manifest files as in the first runs. The task is now idempotent. Yay !
Do you have a timeline for the fix to be publicly available ?

**Comment by eskatos** [comment]
Note that the build mentioned above isn't a published Gradle nightly but a local build with a tentative fix.

**Comment by eskatos** [comment]
`DefaultPublishArtifact` type is both mutable and potentially runs user code in order to decide where the artifact is. These means an `equals()` method is not a good idea, particularly given that this is a public type. Instead, we should be loading these values from the configuration cache in a way that either does not duplicate the values or where the values are immutable.

**Comment by stephanenicolas** [comment]
Do you have a timeline for the fix to be publicly available ? @eskatos

**Comment by eskatos** [comment]
The issue is not only that the task isn't up-to-date but also that the generated manifest content is different, incorrect.

@stephanenicolas, making some progress already. This issue will be updated in due time.

**Comment by eskatos** [comment]
Fix for 7.0 at https://github.com/gradle/gradle/pull/16226
Backport in 6.x at https://github.com/gradle/gradle/issues/16268
