### ISSUE TITLE
Support camelCase shourtcuts for configuration selection in dependencies/dependencyInsinght task

### ISSUE THREAD

**Issue by grossws** [gradle/gradle#16141]
Currently `--configuration` parameter in `dependencies` and `dependencyInsight` tasks requires user to type full configuration name.

I propose add `NameMatcher`-based support for camelCase in command line parameter to improve CLI UX like it done for projects and tasks selection.

In case of ambiguous configuration selected by camel case task should fail. 

### Expected Behavior
`gradle dependencies --configuration ruC` should work same as `gradle dependencies --configuration runtimeClasspath` if `ruC` there's only one configuration with such abbrev.

### Current Behavior
Configuration not found

### Context
Current zsh gradle autocompletion don't support configurations (and it would be be quite costly to do so) and when you investigate dependency resolution problems it would be useful.

Also I brought idea in gradle community [slack #general][1] and it found some support. 

[1]: https://gradle-community.slack.com/archives/CA7UM03V3/p1611706682059700

**Comment by ljacomet** [comment]
Thanks for the feature request.

I edited the first paragraph which mentions `--dependency` and not `--configuration`.

**Comment by grossws** [comment]
@ljacomet thanks for correction, it was around 3 am when I submitted this issue)

**Comment by donat** [comment]
@grossws Sorry for the late reply. Your PR makes sense. I'll give it a more thorough review.
