### ISSUE TITLE
Build cache miss when jars have been hashed with different normalization configuration

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#16144]
We've received multiple reports of cache misses on runtime normalization input properties for jar files that should be identical.  At least one reporter confirmed that using a different gradle user home resolved the issue.  It turns out some of the changes to runtime classpath normalization in 6.8 don't accurately capture changes to the normalization configuration, which can lead to a sequence of events like the following:

1. CI server runs a build that hashes a 3rd party library in a project without properties file normalization rules.  The hash of this file is cached in the resources cache.
2. Another build runs that does have properties file normalization rules, but when the hasher gets to the library, it does not properly capture the rules when calculating the key for the resources cache and calculates the _same_ key as the build without normalization rules.  Rather than hashing the file again, it gets a hit on the resources cache and incorporates this hash into the task's build cache key.
3. A build on another system that does not have the library's hash in the resources cache runs the build with the properties file normalization rules, gets a miss for that file in the resources cache, and does the fully normalized hash of the library.  The resulting hash is different which results in a different cache key for the task, causing a build cache miss.

### Expected Behavior
We should get.a build cache hit on the task.

### Current Behavior
The build cache key can be incorrectly calculated on one side or the other, causing a miss.

### Context
Poorer build perfomance due to cache misses.

### Steps to Reproduce 
See above.

**Comment by wolfs** [comment]
I created https://github.com/gradle/gradle/issues/16192 to backport the fix to 6.8.3.

**Comment by carstenhag** [comment]
Is it really a "critical bug" as per the 6.8.3 release notes? Seems like it's only performance relevant? :)

**Comment by wolfs** [comment]
This can lead to incorrect builds, which makes it a critical bug.
