### ISSUE TITLE
Document requirements for concurrent access restrictions of shared build services

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16169]
Today I learned, that if you want to restrict the concurrent access to a build service, you also have to call https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#usesService-org.gradle.api.provider.Provider- to register the task as a consumer of the service.

The documentation at https://docs.gradle.org/current/userguide/build_services.html#concurrent_access_to_the_service does not mention this requirement at all but gives the impression that it should work automagically.

The JavaDoc of that method is also not too enlightening, it just says "Registers a BuildService that is used by this task.".
For me this would mean it actually registers that build service which is not possible, because you first have to register the build service manually before you can give its provider to that method. It should probably better be something like "Registers that a BuildService is used by this task. This is necessary if the build service should have constrained concurrent access." or something similar.

So I'm asking here to improve the user guide to mention the necessity for calling that method and the JavaDoc of the method to make it clearer what it is used and needed for and when.

**Comment by bamboo** [comment]
Fixed by #19358

**Comment by bamboo** [comment]
Thanks for the suggestions, @Vampire, please let us know if you think the issue hasn't been address properly by the mentioned PR.
