### ISSUE TITLE
Simplify consumption of Shared Build Services

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16168]
If you have registered a shared build service with 6.8.2 like desribed here: https://docs.gradle.org/current/userguide/build_services.html, you still have to manually wire that build service into the classes where you need to use it.

Would be nice if you could instead `@Inject` those services just like you inject the built in services.

**Comment by abstratt** [comment]
The code is in 8.0, but we want to allow us more time to tweak the API if needed before we advertise this feature, so it will only be documented for 8.1.

**Comment by abstratt** [comment]
See demo project at:

https://github.com/abstratt/simplified-shared-build-service-demo

See  spec at: https://docs.google.com/document/d/15dlxPKI0SZvmwgoMLtdGjlr4DbXp1VqMOzXpLEEWgj4/view#

**Comment by abstratt** [comment]
This went into 8.0. Documentation and promotion will be covered by #23362.
