### ISSUE TITLE
Automatically register a build service user when it is wired to a managed property

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16170]
Currently you need to register build service users manually using `Task#usesService​` if you want to restrict concurrent access to the build service.
If the build service is wired to a managed task property (or injected if #16168 gets added) it would be nice if the task would be registered as a user of that service automatically without the need to call `usesService` manually.

**Comment by cloudshiftchris** [comment]
Likewise, register the task as a user of that service for indirect uses of a service, e.g. `someProp.set(someService.map { it.doSomething() }) - carry the buildService dependency along the provider chain.

**Comment by abstratt** [comment]
This is addressed as part of #16168.
