### ISSUE TITLE
Android sourceSets task does not show output in Gradle 6.8+

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#16186]
### Expected Behavior
I can run the Android Gradle task `sourceSets` on an Android module and see output.

### Current Behavior
No output is shown from the task.

### Context
The task works in Gradle 6.7.1 but not Gradle 6.8 or higher (and I've just checked a very recent 7.0 nightly as well). I suspect the cause is https://github.com/gradle/gradle/commit/4dac91ab87ea33ee8689d2a62b691b119198e7c7 since [SourceSetsTask](https://cs.android.com/android/platform/superproject/+/master:tools/base/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/tasks/SourceSetsTask.java;l=40?q=sourcesetstask) extends `AbstractReportTask` which had its `@TaskAction` removed by that commit.

I originally raised [this issue](https://issuetracker.google.com/issues/180116502) against Android's issue tracker but was told to raise against the Gradle project instead.

### Steps to Reproduce 
Open any Android project and run the `sourceSets` task in an Android module with Gradle 6.7.1 (works, prints output as expected) then switch to Gradle 6.8 and try again (does not show output).

### Your Environment
Gradle 6.8.2, AGP 4.1.2 on Windows

**Comment by ljacomet** [comment]
@bamboo Could you check this? I reproduced it.

**Comment by ljacomet** [comment]
This will be fixed in Gradle 7.0 and most likely backported to Gradle > 6.8.3
Follow #16621 for this.

**Comment by bamboo** [comment]
Thanks for the follow up, @ljacomet!
