### ISSUE TITLE
Configuration cache issue with :pluginUnderTestMetadata when both kotlin-jvm and java-gradle-plugin are applied

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#16183]
According to [the docs](https://docs.gradle.org/6.8.2/userguide/configuration_cache.html#config_cache:plugins) java-gradle-plugin supports configuration cache. I get deserialisation issue even on simple project without any sources. [java-gradle-plugin-cc.zip](https://github.com/gradle/gradle/files/5994080/java-gradle-plugin-cc.zip)

Gradle version: 6.8.2

Steps to reproduce:

1. ./gradlew build --dry-run
2. ./gradlew build --dry-run

> ./gradlew build --dry-run
> Configuration cache is an incubating feature.
> Reusing configuration cache.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not load the value of field `pluginClasspath` of task `:pluginUnderTestMetadata` of type `org.gradle.plugin.devel.tasks.PluginUnderTestMetadata`.
> > org.gradle.plugin.devel.plugins.JavaGradlePluginPlugin$$Lambda$867/295678601
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 511ms
> Configuration cache entry reused.
>

**Comment by eskatos** [comment]
This problem only surfaces when the Kotlin Gradle plugin is applied alongside the `java-gradle-plugin` plugin.
