### ISSUE TITLE
Upgrade Groovy to 2.4.10

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#1619]
There seems to be an issue with binary compatibility between 2.4.7 and 2.4.9 that is fixed in 2.4.10: https://issues.apache.org/jira/browse/GROOVY-8107

+review [REVIEW-6487](https://code-review.gradle.org/cru/REVIEW-6487)

**Comment by lptr** [comment]
Successful stage 5: https://builds.gradle.org/viewLog.html?buildId=2565904&tab=buildResultsDiv&buildTypeId=bt46

I think we're good.

**Comment by bmuschko** [comment]
@lptr Can you please close the issue when you think it's ready?
