### ISSUE TITLE
Consider publishing information based on the binary compatibility reporting

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#16204]
Possibly as part of the upgrade guide and/or release notes.

**Comment by jjohannes** [comment]
Should be considered as part of the release notes polishing https://github.com/gradle/gradle-private/issues/3315

**Comment by eskatos** [comment]
Our custom report is tailored for our use but not for general user consumption.
An alternative would be to publish the raw `japicmp` report just like other open source projects do.

**Comment by eskatos** [comment]
The raw `japicmp` report can't be configured with appropriate includes/excludes to only cover our public API so we'll have to rely on the "rich report" that has a better includes/excludes mechanism.
