### ISSUE TITLE
Add lazy `MavenArtifactRepository.url` property

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#16205]
When publishing to OSSRH, Nexus creates a staging repository implicitly as it receives artifacts. 

While this has been working so far, it can lead to split staging repositories where some files of the publication end up in one staging repository and others in another, making the publication quite cumbersome. This is especially true for Kotlin multiplatform builds that are built on multiple machines and where the frequency of split staging repositories seems to be even higher (and build times are high too making the retry process really cumbersome).

To fix this, we can ask Nexus to create a new staging repository and upload files there:

```kotlin
fun getNewStagingRepositoryUrl(): String {
  val stagingRepositoryId = nexusStagingClient.createRepository("my staging repo for version $version")
  return "https://oss.sonatype.org/service/local/staging/deployByRepositoryId/${repositoryId}/"
}

repositories {
  maven {
    name = "OSSRH"
    // Oh no, this is called during configuration 
    url = uri(getNewStagingRepositoryUrl())
  }
}
```

as outlined above, this is called during configuration time and will needlessly spend time on each build and create useless staging repositories. It would be nice if instead `url` were a `Property<String>`:

```kotlin
val stagingRepositoryProvider = objects.provider {
  val stagingRepositoryId = nexusStagingClient.createRepository("my staging repo for version $version")
  "https://oss.sonatype.org/service/local/staging/deployByRepositoryId/${repositoryId}/"
}

repositories {
  maven {
    name = "OSSRH"
    // Yessss, no time wasted during configuration 
    url.set(stagingRepositoryProvider)
  }
}
```

**Comment by melix** [comment]
Yes, the publishing APIs are not really provider-ready at this stage.

**Comment by vlsi** [comment]
`void setUrl(URI url);` supports `Provider<String>` instances.

Here's a sample use: https://github.com/gradle-nexus/publish-plugin/blob/a15a8bc2f5c573f2b3cfda8499017f4ad780abbb/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt#L149-L151

**Comment by martinbonnin** [comment]
Today I learnt! 

Sorry I missed the `void setUrl(Object url);`. Many thanks @vlsi 🙏

**Comment by melix** [comment]
Oh I got caught too. Because I'm used to do `url = `... Darn Kotlin not supporting this syntax for overloaded setters :/
