### ISSUE TITLE
Plugin Portal needs a bit more version comparison intelligence

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16231]
Plugin Portal needs a bit more version comparison intelligence it seems, or a way to order versions manually.

https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm displays as current verision 1.4.30-RC
as second newest version 1.4.30-M1
and only as third newest version the actual current 1.4.30.

**Comment by big-guy** [comment]
dupe https://github.com/gradle/gradle/issues/16292
