### ISSUE TITLE
Remove smoke test for 'org.samples.greeting' plugin

### ISSUE THREAD

**Issue by melix** [gradle/gradle#16243]
### Context

We have a smoke test, `GreetingSamplePluginSmokeTest`, which verifies the `org.samples.greeting`. This plugin currently throws a deprecation warning and is apparently used by the GE build.

However, in 7.0 the deprecation becomes an error. If it's really used, then a new version should be released which fixes the reported problem.

**Comment by wolfs** [comment]
The plugin has been removed from the GE build. So we now should remove the smoke test on our end.
