### ISSUE TITLE
Absolute path is not working when configuring Copy task

### ISSUE THREAD

**Issue by perqin** [gradle/gradle#16249]
I am creating a `Copy` task, providing an absolute directory to `into`. But the path is still resolved relatively.

### Expected Behavior

For the following build script:

```groovy
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

task copyTest(type: Copy) {
    destinationDir = projectDir
    from(file('gradlew')) {
        into new File('/Users/perqinxie/Workspaces/_demo/publishing-test/dest')
    }
}
```

I expect the `gradlew` file to be copied into `./dest/gradlew`.

### Current Behavior

Please see the screenshot below:

![image](https://user-images.githubusercontent.com/7088631/108710425-fdbf3e80-754e-11eb-9d93-b6c4abebb4ab.png)

### Your Environment

Gradle version:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.2-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by bmuskalla** [comment]
You should not wrap your `into` into the `from` and use `file`, they're both methods on the Copy itself:
```
task copyTest(type: Copy) {
    from file('gradlew')
    into file('/Users/bmuskalla/trash/aplPlugin15673/dest')
}
```

See also https://docs.gradle.org/current/userguide/working_with_files.html#sec:copying_single_file_example

**Comment by perqin** [comment]
I've thought that I could copy multiple files with different destination by wrapping `into` inside the `from`. Then how can I achieve this? Says that I want to copy "gradlew" into "./dest/bin", and "gradle.jar" into "./dest/lib". Is it possible to do this in one `Copy` task?
