### ISSUE TITLE
Avoid rendering `DefaultTask` for adhoc tasks

### ISSUE THREAD

**Issue by melix** [gradle/gradle#16264]
In validation error messages, we show `Type "DefaultTask"` for adhoc tasks. We should either hide it or display `Adhoc task` instead.

---
cc: @gradle/execution

**Comment by lptr** [comment]
What is the problem we are trying to handle here? I think `DefaultTask` is a good type to display when we want to talk about the type of the task.

If this is about displaying runtime properties as if they were properties of `DefaultTask`, I don't think this is the solution. Note that you can register additional properties for any task type, and we shouldn't display them as if they were properties of the type in that case either.

**Comment by wolfs** [comment]
Let's leave it as is now.
