### ISSUE TITLE
com.google.firebase:firebase-crashlytics-gradle:2.5.0 caused Android building errors

### ISSUE THREAD

**Issue by yanqinglu** [gradle/gradle#16281]
Use classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.0' in the build.grade, such as:

classpath 'com.android.tools.build:gradle:4.1.2'
classpath 'com.google.gms:google-services:4.3.5'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.5.0'

in app build.grade:
plugins {
    id 'com.android.application'
    id 'com.google.firebase.crashlytics'
    id 'com.google.gms.google-services'
}

crashlytics-gradle:2.5.0 introduces below building warnings:

> Task :app:injectCrashlyticsMappingFileIdDebug
Property 'mappingFileId' of mutable type 'org.gradle.api.provider.Property' is writable. Properties of this type should be read-only and mutated via the value itself. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.8.3/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
Property 'resourceFile' of mutable type 'org.gradle.api.file.RegularFileProperty' is writable. Properties of this type should be read-only and mutated via the value itself. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.8.3/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

### Expected Behavior
Should no such warnnings.

**Comment by blindpirate** [comment]
Hi thanks for reporting, but this doesn't seem like a Gradle issue because the plugin you're using is not controlled by Gradle. Please open issues in the issue tracker of the plugin authors.
