### ISSUE TITLE
Get Configuration Time insights from real world builds

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1628]
We ask our community to help us find the biggest performance problems during configuration time. Based on this we will provide more insights in [Gradle build scans](https://scans.gradle.com), so you can clearly see what is slowing your build down. We’ll also fix potential bottlenecks in the Gradle build tool, making it transparently faster for everyone.

Configuration time is the work that Gradle has to do on **every** invocation to create a model of your projects, apply all plugins and build scripts and calculate the graph of tasks to be run. Only after that can the actual task execution start. A short configuration time is key to a smooth user experience. 

If running `gradle help` from the command line takes more than 1s on your project, we want to know!

Please create a JFR snapshot and (if possible) a public build scan using the [Gradle profiler](https://github.com/gradle/gradle-profiler) like this:

- `gradle-profiler --profile jfr --warmups 10 --iterations 20 help` 
- `gradle-profiler --profile buildscan --warmups 10 help` 

This will measure the time it takes to call `gradle help`, which is a good approximation of pure configuration time. You can then upload these snapshots to some hosting service of your choice and link them here or send them privately to `performance@gradle.com`.

A note about Android builds: Please make sure you are using the new [Android plugin 3.x](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html) versions. Older Android plugin versions had significant configuration time performance issues that have since been fixed.

**Comment by oehme** [comment]
Thanks to everyone who submitted feedback to our performance mailing list so far. We have taken several steps based on the snapshots you provided:

- We have added a lot more stories to the "build scan insights" [epic](https://github.com/gradle/gradle/issues/1605).
- We have addressed several hotspots in Gradle's configuration time memory consumption. Please give the 4.0 nightlies a try and let us know if it made an impact for you.

Please keep those performance snapshots coming, they are helping us (and you 😉  ) a lot!

**Comment by oehme** [comment]
Updated the description to also invite feedback from Android developers, now that the Android plugin 3.0 previews are available. It didn't make sense before, because we already knew that 2.3 had major configuration time problems.

**Comment by jjohannes** [comment]
Analysing and improving configuration time is now done in context of the  `@configuration-cach` effort. See issue with the `@configuration-cach` label.

https://docs.gradle.org/current/userguide/configuration_cache.html
