### ISSUE TITLE
TestLauncher TAPI improvements

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#16295]
Initial usage of TestLauncher has arrived in IntelliJ 2021.1
At the time of opening this issue, it is disabled using internal Registry key `gradle.testLauncherAPI.enabled` (defaults to `false`)

There are some issues, outlined below in order of severity:

1. There is no single method that can receive patterns for classes, methods or packages. Distinguishing such patterns in client code (IntelliJ IDEA) would leak abstractions and is not always possible. OTOH, command line calls work without this information (required to be enabled by default)

2. A mix of test and non-test tasks can not be invoked, so currently the TestLauncher will only be invoked for a what is considered a "test-only task" call by the IDEA

3. Comparison information (expected and actual values) can not be extracted and delivered to IntelliJ IDEA using TestEvents in TAPI

4. Failure stacktrace can not be inspected to determine of it is an assertion failure, or runtime failure (to display proper status in UI)

**Comment by donat** [comment]
The requested features have been implemented and will be part of Gradle 7.6.
