### ISSUE TITLE
Chocolatey gradle package need update

### ISSUE THREAD

**Issue by netroby** [gradle/gradle#1631]
I am try to install gradle via choco , but seems it outdated.

```bash
PS C:\Windows\system32> choco install gradle
Chocolatey v0.10.3
Installing the following packages:
gradle
By installing you accept licenses for the packages.

gradle v3.1 [Approved]
```

Not up to latest gradle 3.4.1

**Comment by bmuschko** [comment]
Thanks for reporting. I created an issue with the Gradle package provider: https://github.com/mrdanielfsch/chocolatey-packages/issues/7. I am going to close the issue as it is maintained externally.

**Comment by zeljkot** [comment]
Chocolatey package is always late. Please provide official Gradle package with timely updates.

**Comment by lacasseio** [comment]
Thanks for your interest in this matter @zeljkot. Unfortunately, this has low priority on our list. We will discuss internally to see how we can improve the situation but I can't promise an ETA.
