### ISSUE TITLE
BuildEnvironment model should expose the Gradle home

### ISSUE THREAD

**Issue by donat** [gradle/gradle#1632]
### Expected Behavior

The `GradleEnvironment` interface should have a `getGradlehome()` method.

### Context

In Buildship we need to know what is the exact location of the used Gradle distribution on the disk. Currently, we can only approximate information from the import properties: https://github.com/eclipse/buildship/blob/master/org.eclipse.buildship.kotlin/src/main/java/org/eclipse/buildship/kotlin/GradleKotlinScriptTemplateProvider.java#L70

**Comment by adammurdoch** [comment]
Why do you need the exact location of the Gradle distribution? Sounds like a proxy for something else.

**Comment by oehme** [comment]
The real use case is getting the bootstrap(*) classpath for GSK without paying the price of configuring the project.

(*) When working with Kotlin in Eclipse or IntelliJ, we first need to pass it a classpath which contains the GSK version that is bundled with that Gradle version. This GSK version is then responsible for building the buildscript classpath model in a second request.

**Comment by oehme** [comment]
Thinking more about this, we should probably just get rid of this weird two-way-dance in GSK. There should be a gsk-client JAR that is published just like our tooling-api JAR and which can talk to any current and future GSK version. Clients should not depend on the contents of the Gradle distro.
