### ISSUE TITLE
DependencyHandler does not accept a Callable for a lazy dependency notation

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#16343]
In many places in Gradle that accept a Provider<T>, they also accept a Callable<T>, such as project.files(...). However, one place I've noticed that doesn't do this is DependencyHandler. It accepts a Provider<T> as a parameter to add(), but not a Callable<T>. This makes it so if you want to pass a callable, you actually have to also create a provider wrapper object around that callable, which is both confusing based on the other lazy apis, and also sometimes a pain as the way to create a provider manually is kind of hidden.

**Comment by alllex** [comment]
Sorry for the late reply

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by alllex** [comment]
@gradle/bt-jvm, can you also take a look at another related issue?
* https://github.com/gradle/gradle/issues/16419

**Comment by big-guy** [comment]
I don't think we want to make the dependency handler accept `Callable` as a sort of Provider. 

In cases where something expensive needs to be done, that can already be wrapped in a Property/Provider.

In other cases, an explicit `project.provider {}` would make things clearer that something unusual is happening. 

Accepting `Callable` would also close the opportunity to use `implementation { }` for something else in a dependencies block.
