### ISSUE TITLE
Support annotation processor in mixed scala+java project

### ISSUE THREAD

**Issue by SchrodingerZhu** [gradle/gradle#16347]
say, we have a java class 
```
@Generate
class A {
 //...
}
```
This gives us a generated class `AGen`.

meanwhile. in scala:
```
object XXX {
  // reference to AGen
}
```

**Comment by mlopatkin** [comment]
@SchrodingerZhu could you please provide a sample project that demonstrates what you are trying to achieve? With some simple annotation processor for java being set up.

**Comment by octylFractal** [comment]
As there has been no reply for nearly 6 months, I am closing this issue.
