### ISSUE TITLE
Transient failures in repositories lead to cache inconsistency

### ISSUE THREAD

**Issue by i7c** [gradle/gradle#1634]
Situation: one of our client’s repositories sometimes temporarily times out due to heavy load and (unfortunately) responds with a 404 for a JAR file.

Gradle seems to load the poms and jars in different steps and seems to assume that if the pom was loaded correctly (and is now in the local cache), the JAR file is also cached already. So it happened multiple times that gradle loads the poms, fails to load one specific JAR due to a transient timeout in the remote repository and thus fails to pull all dependencies. So far this is not a bug.

Here comes the bug: If you run gradle again, it does not perform any request against the remote repository but prints the error message that artifact XY was looked up at location https://ourrepository.com/some/path/XY.jar but not found there. I checked with wireshark, there is no network traffic at all.

### Expected Behavior

If gradle notes that a JAR file is missing in the local cache, it should check the remote repository again. Or in other words: the caching of a dependency should be somewhat transactional. Either it succeeds to load both the pom and the jars of a dep or none. It should consider an artifact "cached" only if all files of the artifact are really in the file system.

### Current Behavior

Running gradle again on an inconsistent cache leads to an error message that is not very helpful to the user. It claims it looked up a dependency at location http://xyz, which actually only happens once and if it fails, it is never retried.

### Context

I try to make gradle more resilient to misbehaving remote repositories or temporary network failures. :)

### Steps to Reproduce (for bugs)

Here it gets a bit tricky, I’ll try to provide steps to reproduce nonetheless.

1. I created an empty JAR + pom (without further dependencies) with the "groupId org.rliz.nothing" and artifactId "useless".

2. produce the directory structure as a remote repository would have it. I’ll refer to this as the "repo dir".

```
repo
└── org
    └── rliz
        └── nothing
            └── useless
                └── 1.0-SNAPSHOT
                    ├── useless-1.0-SNAPSHOT.jar
                    └── useless-1.0-SNAPSHOT.pom
```
3. Create a very simple build.gradle for a fake project. I’ll refer to this as the "project dir".

```
allprojects {
    repositories {
        maven {
            url "http://127.0.0.1:8000/"
        }
    }
}

apply plugin: 'java'

dependencies {
    compile group: 'org.rliz.nothing', name: 'useless', version: '1.0-SNAPSHOT'
}
```

4. Start our very professional local repository:
cd repo
python -m SimpleHTTPServer
(this is python2, not sure if it works with python3)

5. now move the useless-1.0-SNAPSHOT.jar out of the repo dir
mv useless-1.0-SNAPSHOT.jar /tmp/

6. In the project dir run gradle build -> fails because useless-1.0-SNAPSHOT.jar cannot be found
7. move useless-1.0-SNAPSHOT.jar back into the repo.
Up until this point we simulated a transient failure in the repo, but now everything is available and gradle should be able to pull the deps.

8. run gradle build in the project dir again: still fails!

```
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find useless.jar (org.rliz.nothing:useless:1.0-SNAPSHOT).
  Searched in the following locations:
      http://127.0.0.1:8000/org/rliz/nothing/useless/1.0-SNAPSHOT/useless-1.0-SNAPSHOT.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.561 secs
```

In the output of the SimpleHTTPServer you can see, that gradle does not perform any request against the repo server. If you click on the location where gradle claims to search, you can download the file.

We can fix this now by doing a 
rm -rf ~/.gradle/cache, but with the next transient failure, the cache will be in inconsistent state again.

### Your Environment

Linux + Gradle 3.4.1

**Comment by eriwen** [comment]
@i7c Thanks for the well-written issue.

Just to confirm: have you tried `--refresh-dependencies`?

**Comment by i7c** [comment]
Hi,

so I tried --refresh-dependencies in the artificial case above and it works, so the build succeeds. I remember that I tried it in the "real situation" as well, and it did not work. But now that I think about it, I obviously tried it right after a build had failed, so the error in the repository might have been present still. So, likely, I could have solved the issue by retrying with --refresh-dependencies until it succeeds.

On the other hand, do you think the caching behaviour is okay? From my point of view, it is at least somewhat confusing that gradle states "Searched in the following locations" when it means "I tried once to search the following location".

**Comment by eriwen** [comment]
@i7c IIRC we cache HTTP 404s some time. That cache would've expired after some time and perhaps this would work without `--refresh-dependencies` then. We do this to optimize performance — it's a trade-off as is everything. We don't want to check every repository for every dependency if we "know" it's not there. Doing `--refresh-dependencies` causes us to ignore the cache and should work at the cost of additional network overhead.

It sounds like the error message could be clearer if we are using a cached response. We did try at that location, after all.

**Comment by i7c** [comment]
Well, I personally think it’s not a smart idea to cache error responses, *especially* if an artifact could be served by several repositories and gradle then refuses to check alternative possibilities in favour of falsely claiming "well I didn’t find your artifact the first time, so it’s definitely still not available!". I have my workaround, so I’m fine with it, but for the usability of gradle  I think it would benefit from changing this behaviour to rather caching artifacts than HTTP responses.

That’s just my personal view, you may close this issue, if you don’t share my opinion. :)

**Comment by stefan1000** [comment]
While writing a custom transport protocol I think I'm running into the same issue (e.g. my VPN broke for a short period while gradle was fetching dependencies, now it thinks it cannot resolve the jars from this repository any longer). Is there any (official / internal) way to control the cache for these failed requests ?
