### ISSUE TITLE
AbstractCopyTask needs a ::from overload that takes some sort of deferred action

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#1636]
In groovy you can create a copy task like this:

```groovy

task extractSources(type: Copy) {
    from { // use of closure defers evaluation until execution time
        configurations.source.collect { zipTree(it) }
    }
    into "$projectDir/src/main/resources"
}
```

However, in gradle script kotlin there is no good way of doing this without doing some wacky closure magic.

The best solution is this:
```kotlin
task<Copy>("extractCustomizationSchema") {
    from(configuration.map { tarTree(it) })
    into("$buildDir/schema/schema_${it.second}")
}
```
Which of course pushes the resolution of the dependency to configuration time instead of run time.

### Expected Behavior
A type safe way of deferring resolution of a file in a copy task to task execution time.

### Your Environment
```
distributionUrl=https\://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170305000422+0000-all.zip
```

**Comment by bamboo** [comment]
An overload is not technically required since a `java.util.concurrent.Callable` instance can be used to defer resolution:

```kotlin
from(
  Callable {
      configurations["source"].map { zipTree(it) }
  })
```

An overload would make for a better API though.

**Comment by JLLeitschuh** [comment]
@bamboo Would this help as another getting started doc in the gradle script kotlin repo?

**Comment by eriwen** [comment]
@bamboo I'll assign this issue to you for any follow up actions or uh... closure.

**Comment by JLLeitschuh** [comment]
I'd like to add strongly typed methods for `Callable` so you can do:
```kotlin
from { [whatever] }
```
In the kotlin DSL without having to know that you need to import and use `Callable`.

I'm thinking the easiest way to do this is by adding default methods to the `CopySpec` and the `CopyProcessingSpec`.

**Comment by JLLeitschuh** [comment]
An alternative could be to add an extension function, but then that would only exist for the Kotlin DSL.
@bamboo What are your thoughts on adding this as an extension function?

**Comment by oehme** [comment]
I'd prefer a `map {}` overload on `FileCollection`, which keeps the build dependencies intact and doesn't eagerly resolve. We have something similar for `filter`, `plus` and `minus`

**Comment by JLLeitschuh** [comment]
That would be nice, but it would also be an API breaking change because for kotlin DSL users you'd be changing the behaviour of the `map` function in their code.

You'd want to do this before Gradle `5.0`.

**Comment by JLLeitschuh** [comment]
It is eager in kotlin. And the return type of `map` in kotlin is `List<File>`. So if you make it lazy and have a different return type. So, yes it will be a behavioral and return type change for newly compiled code.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map.html

```kotlin
inline fun <T, R> Iterable<T>.map(
    transform: (T) -> R
): List<R>
```
