### ISSUE TITLE
Dependency locking should not persist lock state on build failure

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#16364]
### Expected Behavior

When asking Gradle to persist lock state using the `--write-locks` CLI option, I may want to write custom validation tasks for my dependency graph. A failing build should not write lock files to disk.

### Current Behavior

Even if my custom validations fail the build, lock state is still persisted.

### Workaround
For now, my best thought will be to concatenate my validation step and persisting lock state as two separate Gradle invocations. This is obviously not desirable:

`$ gradle myCustomValidationTask && gradle resolveAndLockAll --write-locks`

### Context

As mentioned above, I would like to write custom validations about the expected state of the resolved configurations. If this expectation is not met, my custom task will throw a GradleException and fail the build.

More specifically, @ljacomet and I have discussed a potential future feature by which a centrally-declared dependency should take precedence over transitively-resolved versions of the same component. In the custom validation use-case which exposed this feature request, I am failing the build if the version of my first-order centrally-declared dependency is resolved to a higher version via transitive conflict management. I believe this would also be a nice-to-have feature.

**Comment by DPUkyle** [comment]
Perhaps a better description would be "Dependency locking API **should have an option to not persist lock state** on build failure". Otherwise this could be too severe of a modification to existing behavior.

**Comment by ljacomet** [comment]
Not writing the lock file on build error makes compete sense and it happening was an overlooked side effect of dealing with a single file per project.

This is planned for addition in Gradle 7.0.
