### ISSUE TITLE
Make sure localGroovy/embedded Groovy represents a "full" Groovy language distribution

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#16360]
localGroovy should expose all groovy modules to represent groovy-all
For everything that is not directly needed by Gradle, we should have a test reproducing the use case. We should not add things just because we thing they might be needed. This change is already breaking. We can remove things.

Look into missing extension methods (gradle-community.slack.com/archives/CA7UM03V3/p1614160294029600)

**Comment by bmuskalla** [comment]
See also [existing fixes](https://github.com/gradle/gradle/commit/1452fd7a8049fba0d68b50674ef19da7c6b4404a)and [question on this issue](https://github.com/gradle/gradle/issues/15566#issuecomment-784995561)

**Comment by jjohannes** [comment]
TODO: Add to update guide: What has changed (i.e. which modules are in localGroovy() now)?

**Comment by bmuskalla** [comment]
We'll leave this as discussed on the previous links for now
