### ISSUE TITLE
The application plugin corrupts binary output

### ISSUE THREAD

**Issue by plcarmel** [gradle/gradle#16370]
I was trying to write binary data to the standard output and, when I execute my application with the plugin, the output gets corrupted. It looks like output is interpreted as text and the encoding is changed, or something like that. I use the "--quiet" option, of course.

It works fine when I execute the application using a fat jar.

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (AdoptOpenJDK 11.0.10+9)
OS:           Linux 5.4.72-gentoo amd64

**Comment by bmuskalla** [comment]
@plcarmel Would you be able to provide a small reproducer to see this problem in action?

**Comment by plcarmel** [comment]
@bmuskalla, there you go: https://github.com/plcarmel/gradle-binary-corruption

See run.sh, it runs the small program both with Gradle and directly with Java and compute an md5 sum of the result. It also counts the bytes that are written to standard output.

The problem manifests itself for bytes that are negative.

```java
  public static void main(String[] args) throws IOException {
    final var bytes = new byte[] { -1, 2, -3, 4, -5, 6, -7, 8 };
    try (final var stdOut = new FileOutputStream(FileDescriptor.out)) {
      stdOut.write(bytes);
    }
  }
```

```sh
#!/bin/sh
./gradlew build
echo "###### With Gradle:"
gradle -q run --args "hello world" | md5sum
gradle -q run --args "hello world" | wc -c
cd ./build/classes/java/main || exit 1
echo "###### Directly with the java command:"
java net.plcarmel.gradlebinarycorruption.Main hello world | md5sum
java net.plcarmel.gradlebinarycorruption.Main hello world | wc -c
```
