### ISSUE TITLE
Add non-cacheablity category CACHING_DISABLED_BY_DEFAULT

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#16381]
After https://github.com/gradle/gradle/pull/16274 work marked with `@DisableCachingByDefault` is reported with `NOT_ENABLED_FOR_TASK` as its non-cacheability reason. We should introduce a new category called `CACHING_DISABLED_BY_DEFAULT` instead to allow build scans to show these tasks as a separate category.

---
cc: @gradle/execution

**Comment by lptr** [comment]
Should we add a new category for tasks marked with `@DisableCachingByDefault`, or should we add a new category for tasks that don't have either `@CacheableTask` nor `@DisableCachingByDefault` on them?

**Comment by lptr** [comment]
We haven't done this yet, and it doesn't seem to be a big issue. Let's not do this at all.

**Comment by guylabs** [comment]
Why has it been decided to not do this? It would be useful to have this in Build Scans as seen in this issue (referenced Slack conversation) #11983

**Comment by guylabs** [comment]
I'll keep it open on our side and with some guidance, we can surely create a PR is required if we prioritize this on our side. Thanks for the insights.
