### ISSUE TITLE
Model building hangs when using new parallel TAPI APIs

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#16398]
Using `IntelliJ IDEA 2021.1 EAP (Community Edition) Build #IC-211.6085.26, built on February 20, 2021` and the 
[project_hang_reproducer (2).zip](https://github.com/gradle/gradle/files/6076424/project_hang_reproducer.2.zip), sync fails to finish. 

Thread dump [threads.txt](https://github.com/gradle/gradle/files/6076428/threads.txt) does not point to any Kotlin/AGP code, so I'm not sure what's causing this. Also, parallel model building is disabled so that does not seem to be the root cause.

**Comment by yuriy-solodkyy** [comment]
> Also, parallel model building is disabled so that does not seem to be the root cause.
But it uses the new `Controller.run()` API to run nested actions.

**Comment by adammurdoch** [comment]
It looks like there are 2 issues here. One is that, according to the thread dumps, parallel build is still happening even though it is is disabled. What are you using to disable it?

The second issue is the deadlock itself. Looking at the thread dumps, this probably only happens when included builds are present. We should have a fix ready soon.

**Comment by adammurdoch** [comment]
The deadlock should be fixed now.

**Comment by gavra0** [comment]
I've also verified that:
- building gradle from https://github.com/gradle/gradle/commit/7c8357a247e621e38617e3cd97cc60c0a0ea39de
- using IJ `Build #IC-211.7142.13, built on April 21, 2021`
- enabling `gradle.tooling.models.parallel.fetch` in the options registry in the IDE

runs sync successfully (some dependencies do not resolve but that is unrelated).

The thread dumps were generated by @vladsoroka, so I'm not sure how the parallel mode was disabled.

**Comment by adammurdoch** [comment]
Thanks for testing it out. I might close this issue and we can open a new issue if there are problems with correctly disabling the feature.
