### ISSUE TITLE
Investigate what broke the composite build setup of our own build

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#16395]
After rebasing https://github.com/gradle/gradle/issues/15526 to latest master (~ 7.0-milestone-2) it no longer works. It worked in the beginning of Januar with the latest 7.0 nightly we had back then.

Investigate what broke and fix what is needed:
- ~Looks like #15950 broke an includeBuild use case (clarify which, reproduce, fix)~
- ~Looks like #16178 causes the build to hang (clarify, reproduce, fix)~
- The build hangs in error case (task is failing, but build is not finishing) even when the above are reverted (this might be an existing issue we missed before). This is also not always reproducible. It only seems to happen if the build is doing work in parallel in different builds and when other tasks are still running when the failing task finished.

**Comment by jjohannes** [comment]
Fix for the early build include issue: #16436

**Comment by jjohannes** [comment]
Fix for hanging build issue: #16449

**Comment by jjohannes** [comment]
Attempt to fix this (might be useless): https://github.com/gradle/gradle/compare/jjohannes/attempts-to-fix-16395

More context: https://gradle.slack.com/archives/C03A0MT6S/p1615968013009600

**Comment by ov7a** [comment]
Closing this as being obsolete.
