### ISSUE TITLE
Display brief task outcome statistics in Build Result

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1639]
Let's make the Build Summary better. We also have an opportunity to better position build scan links in there.

[Design Doc](https://github.com/gradle/gradle/blob/master/design-docs/improved-console.md#story-show-ratio-of-work-avoided-in-build-result)

### Expected Behavior
```
BUILD SUCCESSFUL in 3m 5s
Build Scan: https://scans.gradle.com/s/3rafycnw2n2pg
Tasks: 109/419 (26%) AVOIDED, 310/419 (74%) EXECUTED
```

### Current Behavior
Currently, all users only see a "BUILD SUCCESS/FAILED" message and the wall clock time. If the build cache is in use, stats about task outcomes are displayed.

```
BUILD SUCCESSFUL

Total time: 3 mins 5.652 secs

Publishing build information...
https://scans.gradle.com/s/3rafycnw2n2pg
```

### Context
We tried and removed a feature to show outcome stats during the build. @adammurdoch suggested that it'd be more useful after the build, and I wholeheartedly agree.

There is useful code perhaps in PR #1599

**Comment by lptr** [comment]
Stating both avoided and executed numbers (they should add up to 100% always, right?) looks a little redundant. I wonder if there's a way to display it in a way that avoids that.

**Comment by eriwen** [comment]
@lptr There's probably a better layout here — to be considered. Suggestions welcome, as always.

**Comment by eriwen** [comment]
Closing as delivered.

**Comment by eriwen** [comment]
This doesn't look so good for composite builds. Going to reopen this and solve it.

**Comment by eriwen** [comment]
Improved with https://github.com/gradle/gradle/commit/6d7b3ad3e509c365107670ba8f295f537c4fbeeb

**Comment by eriwen** [comment]
@w25r could I get a review of https://github.com/gradle/gradle/commit/6d7b3ad3e509c365107670ba8f295f537c4fbeeb please?

**Comment by w25r** [comment]
@eriwen Done.  One minor suggestion.  But good to go!
