### ISSUE TITLE
Could not load compiled classes for build file ... from cache with 7.0-m2 (worked with 6.x)

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#16425]
Playing with aggressive CI cache rebuilt prevention in subsequent builds (by always changing files removal), I've noticed after upgrade from 6.8.3 to 7.0-m2 the following error:

```
...
Caused by:
 org.gradle.api.GradleException: Could not load compiled classes for build file '/home/foobar/Code/.../build.gradle' from cache.
  at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ClassesDirCompiledScript.loadClass(DefaultScriptCompilationHandler.java:333)
  at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.getScript(DefaultScriptRunnerFactory.java:55)
...
    Caused by:
    java.lang.ClassNotFoundException: build_6kzfwwgec9yaz5hyu727nckx0
      at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ScriptClassLoader.loadClass(DefaultScriptCompilationHandler.java:371)
      at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$ClassesDirCompiledScript.loadClass(DefaultScriptCompilationHandler.java:328)
      ... 141 more
```

I was able to narrow it to removing `proj.jar` files:
`rm -f  $HOME/.gradle/caches/jars-*/*/proj.jar`

(in fact, just the one corresponding to a given project)

### Expected Behavior
Gradle is able to "fix" the problem and continue.

### Current Behavior
Gradle fails permanently.

### Context
I realize that my action is quite specific, however, the same could occur in a case of cache corruption, especially that the error is permanent, the following builds of that project fails the same way.

It wasn't a problem with 6.x, so maybe it could be handled gravcefully also in Gradle 7?

### Steps to Reproduce 

1. Build
2. `rm -f  $HOME/.gradle/caches/jars-*/*/proj.jar`
3. Build again

### Your Environment
Gradle 7.0-milestone-2 with OpenJDK 15 on Linux.

**Comment by ljacomet** [comment]
I am not able to reproduce this with 7.0 RC1 when using the Groovy or Kotlin DSL.
I tried a couple projects and did `gradle tasks` using a custom Gradle home.

Could you try again with RC1 in your setup?
And potentially share a reproducer?

**Comment by szpak** [comment]
Hmm, I cannot reproduce it with 7.0-rc1 as well. Maybe it was fixed in the meantime. Thanks for looking into that!

**Comment by ljacomet** [comment]
Great, thanks for following up!
