### ISSUE TITLE
nnndpi resource folder qualifier not supporting arbitrary density values

### ISSUE THREAD

**Issue by atimb** [gradle/gradle#16437]
Per official Android documentation, "drawable-200dpi" is a valid resource folder (https://developer.android.com/guide/topics/resources/providing-resources - see "nnndpi" definition). Gradle refuses to build project with resource folder with this name. If same project is built with Buck, it succeeds and the resource folder works as expected with the custom density on Android 10 device (which confirms that aapt/aosp handles this resource qualifier).

### Expected Behavior
APK should be built.

### Current Behavior
APK is not built, :packageReleaseResources fails.

22:03:23.522 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: <project_dir>/res/drawable-200dpi: Error: Invalid resource directory name
22:03:23.522 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.ide.common.resources.MergingException.throwIfNonEmpty(MergingException.java:152)
22:03:23.522 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:259)
22:03:23.522 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.ide.common.resources.ResourceSet.loadFromFiles(ResourceSet.java:55)
22:03:23.523 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:242)

### Context
We are building for custom hardware, that specifically uses 1.25x density (=200dpi), hence the need for this custom resource folder qualifier. We don't want to add larger assets just to be downsized by the runtime.
Here's code pointer to custom dpi values handled by AAPT: https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt/AaptConfig.cpp#320
Here's where parsing fails in Gradle, it handles the nnndpi pattern but then tries to match to buckets, does not allow arbitrary value (which is not in line with the SDK documentation): https://android.googlesource.com/platform/tools/base/+/588c433884c745cba0e09eb16a7f269dfee2c1aa/sdk-common/src/main/java/com/android/ide/common/resources/configuration/DensityQualifier.java#78

### Steps to Reproduce 
Simply add a resource folder called "drawable-200dpi" and place any asset (like a png) inside.

### Your Environment
Gradle 5.6.2
build tools/minsdk/targetsdk/app_platform=29

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
