### ISSUE TITLE
Android Projects not building with Gradle 7.0 and latest AGP

### ISSUE THREAD

**Issue by G00fY2** [gradle/gradle#16457]
I already created an issue on the Google Android issue tracker but they told I have to fill the issue here. Original issue: https://issuetracker.google.com/issues/181220769

### Expected Behavior
After updating AGP from 7.0.0-alpha07 to 7.0.0-alpha08/7.0.0-alpha09 projects should still build

### Current Behavior
Gradle fails with: `Cannot query the value of this property because it has no value available`

### Steps to Reproduce 
1. when building gradle throws "Cannot query the value of this property because it has no value available."
2. everything worked with 7.0.0-alpha07
3. error log and project to reproduce: https://travis-ci.com/github/G00fY2/DeveloperWidget/jobs/486487089

### Your Environment
Studio Build: Arctic Fox | 2020.3.1 Canary 8 (Build #AI-203.7148.57.2031.7165533)
Version of Gradle Plugin: 7.0.0-alpha08
Version of Gradle: gradle-7.0-milestone-2
Version of Java: OpenJDK Runtime Environment JBR-11.0.9.1.11-944.50-jfx_jcef
OS: MacOS 11.2.1
CI Build:  https://travis-ci.com/github/G00fY2/DeveloperWidget/jobs/486487089

**Comment by G00fY2** [comment]
I did some further investigations. The cause was an experimental Android flag in my Gradle properties:
`android.enableAppCompileTimeRClass=true`

After removing it, everything is working again.

**Comment by NLS-rajdeepdodiya** [comment]
Hello, @G00fY2 , where was this flag? I cannot find it in my project. But, I am still facing the same issue.

**Comment by G00fY2** [comment]
@NLS-rajdeepdodiya this was a custom flag set in my project level `gradle.properties` file.
