### ISSUE TITLE
7.0-M2 fails to build when using "withGroovyBuilder"

### ISSUE THREAD

**Issue by zsperske** [gradle/gradle#16461]
On 7.0-milestone2, if you use `invokeMethod` in a `withGroovyBuilder` block your build will fail with the following message. I also tried the nightly build from Thursday 3/4 (7.0-20210304230049+0000) and had the same error.

```
Build file '/gradlerepro/app/build.gradle.kts' line: 29

object is not an instance of declaring class
```

The code in question:

```
buildTypes {
    getByName("debug") {
      withGroovyBuilder {
        "FirebasePerformance" {
          // Set this flag to "false" to disable @AddTrace annotation processing and
          // automatic HTTP/S network request monitoring
          // for a specific build variant at compile time.
          invokeMethod("setInstrumentationEnabled", false)
        }
      }
    }
  }
```

### Expected Behavior
The app should compile.

### Current Behavior
The app doesn't compile.

### Context
This is preventing us from making sure we are ready to upgrade to gradle 7.0.

### Steps to Reproduce 
Download and try to build the following project:

https://github.com/zsperske/gradle-7.0M2-repro/tree/master

### Your Environment
Operating System: OSX 10.15.7

Build scan URL: https://gradle.com/s/hpak5zkirlqog

**Comment by zsperske** [comment]
@bmuskalla

**Comment by bmuskalla** [comment]
@donat Do you have any idea what could be causing this? It seems the last fix we did for this issue didn't resolve it completely

**Comment by donat** [comment]
Indeed this looks quite similar. I'll take a look.

**Comment by zsperske** [comment]
Thank you both!
