### ISSUE TITLE
Overwriting versions

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [gradle/gradle#16474]
Currently, overwriting a version is done by unsafe APIs.

```
    dependencyResolutionManagement {
        versionCatalogs {
            create("libs") {
                from("com.mycompany:catalog:1.0")
                // overwrite the "groovy" version declared in the imported catalog
                version("groovy", "3.0.6")
            }
        }
    }
```

The problem with this behavior is I have to know what is the name of a version used by a specific dependency (or multiple dependencies). So I have to go to the source code, which can be in another git repo, to check what is the version name or some workaround like going to another file to see what is the name generated, or prints the version, etc.

Should be great if they were overwritten (if possible) doing something like this:

```
    dependencyResolutionManagement {
        versionCatalogs {
            create("libs") {
                from("com.mycompany:catalog:1.0")
                versions {
                    libs.versions.groovy.use("3.0.6")
				}
            }
        }
    }
```

**Comment by ljacomet** [comment]
The proposed solution is not practical to implement: you would be using generated code from the data structure you are modifying.
There is currently no plan to change the existing overwrite mechanism for catalog imports.
