### ISSUE TITLE
Wrong plugin artifacts being searched in the custom repository

### ISSUE THREAD

**Issue by guai** [gradle/gradle#16488]
My build worked (from a PC with direct internet connection) until I tried to set up my custom repo for all the dependencies (plugins included) to be able to build inside a _Teamcity_ which only sees an _Artifactory_ server and no other hosts.

In my settings.gradle.kts I wrote:
```
pluginManagement.repositories {
	maven(url = "http://my-repo.example.com/artifactory/m2")
}
```
Now it tries to download wrong artifacts for gradle plugins:
```
Plugin [id: 'io.spring.dependency-management', version: '1.0.11.RELEASE'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.0.11.RELEASE')
  Searched in the following repositories:
    maven(http://my-repo.example.com/artifactory/m2)
```
it tries `io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.0.11.RELEASE` but it should be `io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE`

### Expected Behavior
for plugin `id("io.spring.dependency-management") version "1.0.11.RELEASE"` gradle should download `io.spring.gradle:dependency-management-plugin:1.0.11.RELEASE` artifact from given repository

### Current Behavior
but it tries `io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.0.11.RELEASE`

### Context
I need plugins to be loaded from my maven repo. **Also pls give me a workaround if any exists.**

### Your Environment
win 10, java 11, gradle 6.8.3

**Comment by ljacomet** [comment]
What you observe is the expected behavior.

When using the `plugins` block, Gradle will look for a _plugin marker_ artifact with the coordinates `<pluginId>:<pluginId>.gradle.plugin:<pluginVersion>`.

So if you want to isolate your build from public repositories, you will need to copy the matching plugin marker in addition to the plugin itself.

In your case, it can be found at https://plugins.gradle.org/m2/io/spring/dependency-management/io.spring.dependency-management.gradle.plugin/1.0.11.RELEASE/

**Comment by guai** [comment]
If that is an expected behaviour why wasn't I expecting it after reading docs? :)
And also there should be more informative error messages.

That is strange. My repo is an Artifactory's composite repo. So I believe if those pom files were ever requested they would be resolved. gradle's repo is there among others

**Comment by guai** [comment]
yes, those pom files are being served if requested from the browser...
