### ISSUE TITLE
eclipse构建多项目问题

### ISSUE THREAD

**Issue by MyDevelop007** [gradle/gradle#16497]
#问题
eclipse在创建一个gradle项目后，项目的格式；
|-父项目
|--子项目：默认项目名称：lib
|---子项目的build.gradle
|-settings.gradle
|-其他
在我不想使用命令创建多项目，我始终无法成功创建除了lib以外的其他任何项目，这让我感到十分的费解
#工具
名称 | 版本
eclipse | 2020-06 (4.16.0)
java | 1.8

**Comment by blindpirate** [comment]
Sorry but please don't use Chinese, most team members can't read Chinese. Also, please note that we only accept bug reports and feature requests in GitHub issues. If you have any questions regarding usage of Gradle please ask in StackOverflow or https://discuss.gradle.org/
