### ISSUE TITLE
Settings scripts and plugins should provide APIs to create RegularFile and Directory instances according to the settings layout

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#16506]
Settings scripts and plugins can currently only access `Settings.rootDir` or `Settings.settingsDir` which return `File` instances. Several Gradle APIs require `RegularFile` or `Directory` instances and creating them from a `File` is currently not convenient.

This issue is about providing convenient APIs to Settings scripts and plugins to work with APIs that require `RegularFile` or `Directory` instances.

On example of such API is `providers.fileContents(file)` that expects a `RegularFile`.

This could be done in the same way it is currently done for Project scripts and plugins that have the `ProjectLayout` available.

### Current Behavior

To use `providers.fileContents(file)` the convoluted following is currently required:

```groovy
def regularFile = services.get(ObjectFactory).fileProperty().tap {
    set(new File(rootDir, "path/to/some.txt"))
}.get()
providers.fileContents(regularFile)
```

Note that it requires using the internal service lookup.

### Expected Behavior

It should be convenient and only require public API instead, e.g.:

```groovy
providers.fileContents(layout.rootDirectory.file("path/to/some.txt"))
```

**Comment by cesar1000** [comment]
I think this issues is still relevant.

**Comment by jdochez** [comment]
We need such an API to properly declare inputs to configuration cache from settings plugin.

**Comment by abstratt** [comment]
@jdochez Last night's nightly has new API under `Settings` to retrieve a Settings-based file system layout service (SettingsLayout):

https://docs.gradle.org/nightly/javadoc/org/gradle/api/initialization/Settings.html#getLayout--

(also injectable as a service)

PTAL and let us know if it covers your use cases.

**Comment by abstratt** [comment]
This is now implemented (to be released in 8.5).

**Comment by abstratt** [comment]
The API is still WIP. Reopening.

**Comment by chris-hatton-tipmi** [comment]
I want to load a Version Catalog `from` a TOML file as one of the major conveniences of my in-house Settings Plugin.

Simply getting an acceptable reference to a `File` from the context of a Settings plugin is tortuous.

Why is this so hard!?  We definitely need a convenience here; as there are clearly use cases for it.
