### ISSUE TITLE
optional runtime dependencies should not be passed in

### ISSUE THREAD

**Issue by xiejx618** [gradle/gradle#16503]
![Dingtalk_20210312105800](https://user-images.githubusercontent.com/2609827/110886344-72ea8c00-8323-11eb-83ca-43807b0018a0.jpg)

### Expected Behavior
Do not resolve optional dependency transfers as runtime dependency. 

### Current Behavior
Resolve optional dependency transfers into runtime dependencies. 

### Steps to Reproduce 
A simple project introduces dom4j by "implementation('org.dom4j:dom4j:2.1.3')"
When packaging this project, the optional dependencies will be packaged together. 

### Your Environment
os version:win10 20h2
gradle version: 6.8.3

**Comment by ljacomet** [comment]
Looks like `org.dom4j:dom4j:2.1.3` was published [with Gradle Module Metadata](https://repo.maven.apache.org/maven2/org/dom4j/dom4j/2.1.3/) and there the dependencies are declared which means they are not optional as far as Gradle is concerned. When such metadata is present, the POM file is ignored.

If you believe that is a mistake, open an issue against the `dom4j` project about this.

Gradle behaves correctly in this case given the metadata.
