### ISSUE TITLE
Improve support for deprecation messages testing

### ISSUE THREAD

**Issue by melix** [gradle/gradle#16511]
Currently deprecation warnings are designed to spit out a single line of text. As soon as you want to display a richer message, with formatting and in particular multi-line strings, then things start to be complicated. In particular, our test fixtures recognize deprecation warnings in a very weak way, just by parsing lines and finding out if they contain the term "deprecated" (a bit more complicated but it's really purely output parsing).

This makes it extremely difficult to display nicer warnings to the user. We should fix this.

---
cc: @gradle/execution

**Comment by big-guy** [comment]
I think we emit build operations for deprecations, so we could potentially tap into that.
