### ISSUE TITLE
Packaging Gradle for Debian

### ISSUE THREAD

**Issue by the-loudspeaker** [gradle/gradle#16512]
I would like to use this thread as a point for discussion on how Gradle can be packaged into Debian.
An older version, 4.4.1 to be specific was packaged and is already present in Debian. It can be found [here](https://salsa.debian.org/java-team/gradle).

It has a lot of patches to make sure it builds in offline mode with free and opensource packages already present in Debian. Some patches are there to remove parts which are not present in Debian while some patches are there to use system folders to resolve artifacts. I am trying to update it to 6.4.1 [here](https://salsa.debian.org/theloudspeaker-guest/gradle). 

But because Gradle has changed vastly between these versions, it is turning out very difficult to package it into Debian. Here are some of the issues:
1. Gradle 4.4.1 cannot be used to build Gradle 6.4.1.
2. Gradle 6.4.1 needs kotlin. which is under works yet. [here](https://salsa.debian.org/samyak-jn/kotlin-1.3.30/).
3. Gradle needs proprietary plugins like gradle-enterprise plugin. We will need to figure out a way to build Gradle without enterprise plugin. I already created a issue about it. #16439 

Some of the solutions we tried, to these problems:
1. Using a bootstrap package. I have already created a bootstrap package [here](https://salsa.debian.org/theloudspeaker-guest/gradle-source-build/-/blob/master/gradle_6.4.1+bootstrap_all.deb).
2. Not building certain tasks of Gradle. Those are the tasks which need artifacts which are not present in Debian yet. disabling these doesn't affect core functioning of Gradle. They can be found [here](https://salsa.debian.org/theloudspeaker-guest/gradle/-/blob/testing2/debian/rules#L4).

While these methods gave us a roughly working Gradle, It still had many issues. 
So I ask for help of Gradle developers to find a easier and better way of packaging Gradle in Debian. A good starting point would be to help us in building Gradle without gradle-enterprise-plugin on the issue #16439 
After that we can discuss a way of removing other difficulties related to building gradle without scala and sbt, etc. Those are more complex issues.

**Comment by mlopatkin** [comment]
As stated in the linked issue, the current approach of using a bleeding-edge version of Gradle to build Gradle is not well suited for Debian packaging and it is unlikely that we change this approach. We also don't have the capacity to support the patched Debian version.

**Comment by the-loudspeaker** [comment]
> As stated in the linked issue, the current approach of using a bleeding-edge version of Gradle to build Gradle is not well suited for Debian packaging 

Can you suggest a way for us to be able to build gradle offline? Even basic gradle functionality to be able to just build itself would be enough.
