### ISSUE TITLE
Support for Scala3

### ISSUE THREAD

**Issue by tjarvstrand** [gradle/gradle#16527]
Now that Scala3 is maturing it would be great to see support for this in the Gradle Scala-plugin. I couldn't find any previously opened issues about it.

### Expected Behavior
Building applications/libraries with Dotty/Scala3 is supported by the Gradle Scala-plugin. Or documented, if this is already supported.

### Current Behavior
There is nothing about Dotty/Scala3 support in the plugin's current documentation.

### Context
I would like to move to scala3 without having to use sbt

**Comment by dubinsky** [comment]
I also would like to move to Scala 3, and I am _not_ switching to sbt.

Let's assume that Scala 3 library and compiler artifact names will start with `scala3-library` and `scala3-compiler` respectively,
like they do in the 3.0.0-RC1, and not `scala-library` and `scala-compiler` like they did for Scala 2.

It seems that a couple of classes may need need to change: [ScalaRuntime](https://github.com/gradle/gradle/blob/master/subprojects/scala/src/main/java/org/gradle/api/tasks/ScalaRuntime.java#L59) and possibly ZincScalaCompilerFactory...

**Comment by xhudik** [comment]
with the following buidl.gradle (zinc 1.5.0):
```
repositories {
    mavenCentral()
}

scala {
    zincVersion = "1.5.0"
}
dependencies {
    implementation group: 'org.scala-lang', name: 'scala3-library_3.0.0-RC2', version: '3.0.0-RC2'
}

application {
    mainClass = 'xhudik.hello'
}
```
I got error:
```
> Task :app:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileScala'.
> sbt.internal.inc.AnalyzingCompiler$.compileSources(Lscala/collection/Iterable;Ljava/io/File;Lscala/collection/Iterable;Ljava/lang/String;Lsbt/internal/inc/RawCompiler;Lsbt/util/Logger;)V

```

**Comment by Arthurm1** [comment]
Until there is built in Gradle Scala3 support, you can use [Bloop](https://scalacenter.github.io/bloop).

Add to your Gradle project...
```groovy
// download Bloop plugin
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'ch.epfl.scala:gradle-bloop_2.12:1.4.8'
    }
}

subprojects {
    // check if plugin is already applied to be compatible with Metals
    if (!plugins.hasPlugin('bloop')) {
        apply plugin: 'bloop'
    }

    bloop {
       // overrides the scala-library and compiler to use Dotty/Scala3
       dottyVersion = "latest"
       // or use a specific Scala3 version...
       // dottyVersion = "3.0.0-RC1"
    }

    // apply Scala plugin as normal
    apply plugin: 'scala'

    dependencies {
        // add scala2 library to path as normal
        implementation ("org.scala-lang:scala-library:2.13.5")
        // use Scala3 3rd party libraries instead of Scala2
        // implementation ("org.scala-lang.modules:scala-parallel-collections_2.13:1.0.2")
        implementation ("org.scala-lang.modules:scala-parallel-collections_3.0.0-RC1:1.0.2")
    }
}
```
then export the Gradle build to Bloop...
```bash
./gradlew bloopInstall
```

Then compile with Bloop if you want CLI compile/run/test functionality.

Or use [Metals](https://scalameta.org/metals/) or [Intellij BSP](https://www.jetbrains.com/help/idea/bsp-support.html) for IDE functionality

If you use Metals you don't need the `./gradlew bloopInstall` step, nor do you need to install Bloop.  Just run the `Import build` command from Metals after changing your `build.gradle` to incorporate the above.

Disclaimer: I contribute to this plugin

**Comment by xhudik** [comment]
Hi @Arthurm1 , interesting idea - i tried it but:
```
./gradlew bloopInstall

FAILURE: Build failed with an exception.

* What went wrong:
Task 'bloopInstall' not found in root project 'gradle_test'.
```
any idea why `bloopInstall` is not available?

**Comment by Arthurm1** [comment]
Ah my bad - you should probably apply the plugin to `allprojects` instead of `subprojects`

**Comment by xhudik** [comment]
@Arthurm1 still not there yet :(
my `build.gradle` for simple hello world scala 3 program:
```
buildscript {
      repositories {
        mavenCentral()
      }
      dependencies {
        classpath 'ch.epfl.scala:gradle-bloop_2.12:1.4.8'
      }
    }

   allprojects {

      apply plugin: 'bloop'
        bloop {
           dottyVersion = "3.0.0-RC2"
        }
        apply plugin: 'scala'
        apply plugin: 'application'
    
     repositories {
        mavenCentral()
    }
    dependencies {
        implementation 'org.scala-lang:scala-library:2.13.5'
    }

        application {
        mainClass = 'ach.ach'
    }
    }

```
from bloop it works well:
```
bloop run app
Hello world from Scala 3
```
However, no success with gradle:
```
./gradlew run

> Task :app:compileScala FAILED
[Error] scala3/app/src/main/scala/ach/hello.scala:6: expected start of definition
one error found

FAILURE: Build failed with an exception
```
It seems like gradle still works with older scala 2 compiler. 
Any idea why?

**Comment by Arthurm1** [comment]
Bloop is an alternative to Gradle for the compile/test/run stages.  If you want to use `./gradlew run` then you have to wait for Gradle to support Scala3.

Bloop gives you an option to try out Scala3 while Gradle doesn't support it and you can continue to use it to develop on afterwards while still using Gradle to define your build and do dependency resolution & deployment etc.

I encourage you to check out the [website](https://scalacenter.github.io/bloop/) and you can ask more questions on [gitter](https://gitter.im/scalacenter/bloop)

**Comment by xhudik** [comment]
now i got it - `bloop` is an alternative to Gradle. Even I read https://scalacenter.github.io/bloop/ I still thought of `bloop` as a plugin that helps gradle not as a tool that take over gradle role of compiling, running and debugging.

Yes, I have to invest more time to properly understand bloop and bsp. Thank you @Arthurm1  for your patience and explanation!

**Comment by unkarjedy** [comment]
Note that since Scala 3.0.0 the format of artifacts is as following:
`scala3-library_3-3.0.0`, `scala3-compiler_3-3.0.0`

Also, the classpath required for the Scala3 compiler has changed and can be found here:
https://github.com/lampepfl/dotty/blob/master/dist/bin/common#L166
```

library jars:
org\scala-lang\scala3-library_3\3.0.0\scala3-library_3-3.0.0.jar,
org\scala-lang\scala-library\2.13.5\scala-library-2.13.5.jar,

compiler jars:
org\scala-lang\scala3-compiler_3\3.0.0\scala3-compiler_3-3.0.0.jar,
org\scala-lang\scala3-interfaces\3.0.0\scala3-interfaces-3.0.0.jar,
org\scala-lang\tasty-core_3\3.0.0\tasty-core_3-3.0.0.jar,
org\scala-lang\modules\scala-asm\9.1.0-scala-1\scala-asm-9.1.0-scala-1.jar,
org\scala-sbt\compiler-interface\1.3.5\compiler-interface-1.3.5.jar,
org\jline\jline-reader\3.19.0\jline-reader-3.19.0.jar,
org\jline\jline-terminal\3.19.0\jline-terminal-3.19.0.jar,
org\jline\jline-terminal-jna\3.19.0\jline-terminal-jna-3.19.0.jar,
com\google\protobuf\protobuf-java\3.7.0\protobuf-java-3.7.0.jar,
org\scala-sbt\util-interface\1.3.0\util-interface-1.3.0.jar,
net\java\dev\jna\jna\5.3.1\jna-5.3.1.jar,
```

**Comment by dubinsky** [comment]
This issue is two and a half month old, and is not assigned or included in a project/milestone.
Did it slip through the cracks or was it decided that Gradle will not support Scala 3?
I am sure that I am not the only one who'd like to know the prognosis.
Thanks!

**Comment by MavenRain** [comment]
Any update here?

**Comment by MarcinAman** [comment]
I am trying to experiment by updating zinc to latest version, since afaik it supports scala 3. After that i'll have to figure out how to handle new way that compiler bridge is distributed :D

**Comment by GavinRay97** [comment]
If any of the Gradle dev folks are taking a look at this -- I recently added Scala 3 support to Quarkus using Java.

- https://github.com/quarkusio/quarkus/pull/18431

I'm not sure if this will be useful here because it doesn't use Zinc or incremental computation, but the implementation code is this:

- https://github.com/GavinRay97/quarkus/blob/feature/scala3/extensions/scala3/deployment/src/main/java/io/quarkus/scala3/deployment/Scala3CompilationProvider.java#L31-L160

Maybe it could be possible to use something like this in the `DaemonScalaCompiler.java` here?
- https://github.com/gradle/gradle/blob/37911bb86d02d26a5d2ce3f23e01c0d767e3bb91/subprojects/scala/src/main/java/org/gradle/api/internal/tasks/scala/DaemonScalaCompiler.java

**Comment by jlprat** [comment]
Closing this in favor of https://github.com/apache/kafka/pull/11025

**Comment by dubinsky** [comment]
Major build tool ignores a major update to a major programming language it used to support.
Months go by without any word from Gradle developers.
Is this a resources problem? Or a policy decision?

For me, sbt was [never an option](http://dub.podval.org/2011/11/08/sbt-why.html), 
and going back to Maven at this point would be extremely painful,
but I need to be able to use Scala 3 one way or the other,
and the lack of clarity about the future of Gradle's support for it is disturbing.

Can we get a word from someone in the know please? @ljacomet @jjohannes

**Comment by MavenRain** [comment]
> Major build tool ignores a major update to a major programming language it used to support.
> Months go by without any word from Gradle developers.
> Is this a resources problem? Or a policy decision?
> 
> For me, sbt was [never an option](http://dub.podval.org/2011/11/08/sbt-why.html),
> and going back to Maven at this point would be extremely painful,
> but I need to be able to use Scala 3 one way or the other,
> and the lack of clarity about the future of Gradle's support for it is disturbing.
> 
> Can we get a word from someone in the know please? @ljacomet @jjohannes

100% agree with this . . . this is a huge miss on the Gradle side

**Comment by tgodzik** [comment]
Together with @MarcinAman we've managed to get something working here: https://github.com/gradle/gradle/pull/18001

I am running some final tests on it, but it seems that Gradle should be able to compile Scala 3 after this is merged. I would appreciate any feedback or help to figure out if anything is missing (especially test wise.)

**Comment by jlprat** [comment]
Thanks a lot @tgodzik

**Comment by tgodzik** [comment]
Thanks @ljacomet !  Let me know if there are any urgent issues, my company (VirtusLab) is trying to help out within the Scala ecosystem and since Gradle is an important tool for many developers and we have some experience with it's internals, we would be happy to help out.

**Comment by pitzcarraldo** [comment]
Thanks @tgodzik @MarcinAman! You guys are heroes!  I can't wait!
And is there any easier way to try using your current working snapshot version while don't build a Gradle on my local machine? (Like a published version on another maven repo or github registry?) If there would be, many developers including me could test it on various environments and cases and it could be good for improving your current work.
BTW Thanks again for your contribution!

**Comment by tgodzik** [comment]
> Thanks @tgodzik @MarcinAman! You guys are heroes! I can't wait!
> And is there any easier way to try using your current working snapshot version while don't build a Gradle on my local machine? (Like a published version on another maven repo or github registry?) If there would be, many developers including me could test it on various environments and cases and it could be good for improving your current work.
> BTW Thanks again for your contribution!

No way to do it currently, I will work improving the PR so that it will be available to merge soon

**Comment by ljacomet** [comment]
Hey folks,

Thanks to @tgodzik 's dedication, the changes should land on the main branch today or tomorrow.
Once they are available, I'll update here as soon as nightly milestones contain them so that effectively they can be tested on a large scale without waiting for 7.3 RCs.

**Comment by ljacomet** [comment]
Support for Scala 3 is now available in [Gradle nightlies](https://gradle.org/nightly/). Make sure to test it and open issues if you find bugs.

**Comment by SimY4** [comment]
I think scaladoc task for scala3 is broken. Otherwise, it looks good.

**Comment by BarkingBad** [comment]
> I think scaladoc task for scala3 is broken. Otherwise, it looks good.

I am working on that, hopefully will present a PR by the end of the day.

**Comment by BarkingBad** [comment]
Hi, I know you had to wait for a little for this PR, but finally, it is ready. Can someone review the changes? :)

**Comment by unkarjedy** [comment]
JFTR: 
Looks like it automatically works fine with IntelliJ.
Checked with configuration:

```groovy
plugins {
    id 'scala'
    id 'application'
}

application {
    mainClass = 'org.example.App'
}

repositories {
    mavenCentral()
}

ext {
    scalaMajorVersion = '3'
    scalaVersion = "$scalaMajorVersion.0.2"
}

dependencies {
    implementation "org.scala-lang:scala3-library_3:$scalaVersion"
    testImplementation "org.scalatest:scalatest_$scalaMajorVersion:3.2.10"
}
```

**Comment by jlprat** [comment]
Could it still be released as an "experimental feature" under 7.3?

**Comment by ljacomet** [comment]
Not in the way it was broken. But thanks to @big-guy we may have a solution for 7.3 😉 
I was too quick in thinking it a blocker. Sorry for the noise.

**Comment by BarkingBad** [comment]
Thanks @unkarjedy for testing scaladoc fixes. I'll just leave one more snippet for all these people who wonder how to pass the additional parameters to configure scaladoc (for me it was not so obvious for the first time :P), for example project footer:

```
tasks.withType<ScalaDoc> {
    scalaDocOptions.additionalParameters = listOf("-project-footer", "My custom footer")
}
```

I guess it's obvious for gradle users, nonetheless, I don't know if it is somewhere documented for new users.

**Comment by unkarjedy** [comment]
@BarkingBad 
I was commenting more about the ticket in general "Support for Scala3" :) 
Scala Plugin detects Scala 3 SDK and treats the project as "scala 3 project"
