### ISSUE TITLE
AWS have modified session tokens for assumed roles, meaning that the current AwsImAuthentication no longer works for this.

### ISSUE THREAD

**Issue by glungley** [gradle/gradle#16531]
### Expected Behavior
AwsImAuthentication takes into account the role_arn associated with a profile specified with the environment variable AWS_PROFILE

### Current Behavior
AwsImAuthentication uses the AccessKey, SecretKey & SessionToken. These values are now all the same regardless of role/profile being assumed.

### Context

Broken on 6.8.3. Not working on any version as the change is in AWS's sts api.

Using aws s3 as a maven repo where access is permitted through assume roles is now no longer possible.

### Steps to Reproduce 

Setup an AWS account with an assumed role which has access to the s3 repo.
Setup a local profile to assume that role.
Set the AWS_PROFILE env var to point to that profile.
Try to pull a dependency from the repo using config similar to:
```
maven {
        url = 's3://<bucket>'
        authentication {
            awsIm(AwsImAuthentication)
        }
        metadataSources {
            artifact()
        }
    }
```

**Comment by ljacomet** [comment]
Sorry for the late reply

The issue is in the backlog of the relevant team and is prioritized by them.
***

however, this shoul be looked at only after Gradle migrates to the latest AWS SDK

Related:
* #27774
