### ISSUE TITLE
Gradle sometimes fails to link due to duplicate object files

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1654]
We generate a unique path for the object file from a source file's relative path in a project. This seems to be broken somehow because we sometimes generate a different path without changes to the source file or source path. 

Since we generate a different unique path, we do not remove the old .o files and the linker tries to link a new and an old object file into the same shared library.  This causes a link failure.

I haven't been able to reproduce it at will.

### Your Environment

macOS and clang, but I'm not sure the OS matters.

**Comment by lacasseio** [comment]
No additional work will be done on the software model plugins unless it's a blocker for current users. This should not be an issue with the new native plugins. Please reopen on [gradle/gradle-native](https://github.com/gradle/gradle-native) if it is.
