### ISSUE TITLE
Gradle kotlin-dsl plugin partially relies on jcenter

### ISSUE THREAD

**Issue by gabrielittner** [gradle/gradle#16540]
### Expected Behavior

`org.gradle.kotlin:gradle-kotlin-dsl-plugins:1.4.9` can be downloaded when jcenter is having issues and when it's shut down next year.

### Current Behavior

Gradle fails because it times out when trying to find the `.module` file on jcenter:
```
A problem occurred configuring project ':buildSrc'.
> Could not resolve all artifacts for configuration ':buildSrc:classpath'.
   > Could not resolve org.gradle.kotlin:gradle-kotlin-dsl-plugins:1.4.9.
     Required by:
         project :buildSrc > org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:1.4.9
      > Could not resolve org.gradle.kotlin:gradle-kotlin-dsl-plugins:1.4.9.
         > Could not get resource 'https://plugins.gradle.org/m2/org/gradle/kotlin/gradle-kotlin-dsl-plugins/1.4.9/gradle-kotlin-dsl-plugins-1.4.9.module'.
            > Could not GET 'https://jcenter.bintray.com/org/gradle/kotlin/gradle-kotlin-dsl-plugins/1.4.9/gradle-kotlin-dsl-plugins-1.4.9.module'.
               > Read timed out
```

### Context

This broke our builds even when jcenter was down today even though we don't rely on jcenter otherwise.

**Comment by ljacomet** [comment]
The plugin infrastructure of Gradle has ties into JCenter. The team is working on removing them.
Unfortunately that means for now JCenter disruptions impact Gradle builds that do not have all dependencies cached.

**Comment by ThadHouse** [comment]
@ljacomet And this is why I threw up a storm a few years ago when gradle started automatically deleting local caches... Things on the internet can an do go down. Seeing that for gradle to work currently caching is required, when at the same time gradle in the past has said don't depend on caching is just maximum irony.

**Comment by james-kan-shopify** [comment]
Hey @ljacomet , is there any updates on the timeline when a fix for the kotlin-dsl will be released? 

JCenter will be doing service brown-outs between April 12-26th (Mentioned here https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ ). This means that the same issue can occur multiple times. 

Is there an alternative suggestion on what can be done?

**Comment by ljacomet** [comment]
As of today, the Gradle plugin portal will no longer redirect to JCenter when a `.module` file, for coordinates hosted on the portal, is requested.

**Comment by szczepanskikrs** [comment]
> As of today, the Gradle plugin portal will no longer redirect to JCenter when a `.module` file, for coordinates hosted on the portal, is requested.

Still have the same issue but with `pom` files with version 2.1.7 using gradle 7.3 trying to download dependencies from Jcenter. 

```
   > Could not resolve org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.5.31.
     Required by:
         project :buildSrc > org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7 > org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7 > org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31
      > Could not resolve org.jetbrains.kotlin:kotlin-scripting-compiler-impl-embeddable:1.5.31.
         > Could not get resource 'https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-scripting-compiler-impl-embeddable/1.5.31/kotlin-scripting-compiler-impl-embeddable-1.5.31.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-scripting-compiler-impl-embeddable/1.5.31/kotlin-scripting-compiler-impl-embeddable-1.5.31.pom'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/127.0.0.1] failed: Połączenie odrzucone (Connection refused)

 ```

Any solution for this issue?

**Comment by szczepanskikrs** [comment]
Ok

We have found the solution for this one. Add following entry to your `build.gradle.kts` if you have this issue.  

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
```
