### ISSUE TITLE
Composite build issues

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#16556]
Trying to attach one project as composite build doesn't seem to work

### Expected Behavior
Compilation and test class running fine

### Current Behavior
Tons of unresolved [imports](https://gist.github.com/elect86/4a25ddbc0afa31b950adb799933fc14e)

### Context
I'd like [XtraDimensionVR](https://github.com/elect86/XtraDimensionVR) to include [scenery](https://github.com/scenerygraphics/scenery) as a build

### Steps to Reproduce 
Clone both projects and then simply add `includeBuild("../scenery")` in XtraDimensionVR `settings.gradle.kts` and comment out the scenery dependencies in XtraDimensionVR `build.gradle.kts`

### Your Environment
Outcome is the same for 6.8.3 and 7.0m3
[Build scan](https://scans.gradle.com/s/ht4s7mj7tssrg)

**Comment by Vampire** [comment]
Are you sure that is not a local problem?
```
$ git hub clone elect86/XtraDimensionVR
$ git hub clone scenerygraphics/scenery
$ cd XtraDimensionVR/
$ ./gradlew compileKotlin --include-build ../scenery
...
BUILD SUCCESSFUL
```

**Comment by elect86** [comment]
I got composite builds wrong, sorry
