### ISSUE TITLE
Gradle is generating a .m2/settings.xml

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1656]
For a particular build, I'm seeing a `~/.m2/settings.xml` generated. It contains references to a `env.MAVEN_LOCAL_REPO`, but I'm not sure where this is even coming from.  I suspect it has something to do with publishing to a local maven repository.

### Your Environment

macOS and Linux.

**Comment by bmuschko** [comment]
Is this issue still relevant? Have we found the root cause? If we didn't then I don't see a way forward with this issue.

**Comment by big-guy** [comment]
I haven't been able to recreate it locally, so I'm happy to close and see if it resurfaces.
