### ISSUE TITLE
Missing reference in Gradle User Manual Version 6.8.3

### ISSUE THREAD

**Issue by UdoW** [gradle/gradle#16560]
### Expected Behavior

I want to see the document `Task Configuration Avoidance`.

### Current Behavior

I clicked on the link `Task Configuration Avoidance` which points to the relative link `task_configuration_avoidance.pdf`. If you read the PDF https://docs.gradle.org/current/userguide/userguide.pdf locally then the document `task_configuration_avoidance.pdf` cannot be found. But it is also not found if you read the PDF online as the link `https://docs.gradle.org/current/userguide/task_configuration_avoidance.pdf` does not exist, too.

### Context

The document `Task Configuration Avoidance` is referenced multiple times in the Gradle User Manual 6.8.3 and I want to read it.
### Steps to Reproduce 

Browse to `https://docs.gradle.org/current/userguide/userguide.pdf` and jump to e.g. page 189 and click n the link `Task Configuration Avoidance` -> document not found.

### Your Environment

Just use any browser. Either watch the PDF `Gradle User Manual 6.8.3` directly in the browser or download it and watch in with a PDF reader.

**Comment by ljacomet** [comment]
This is caused by missing `task_configuration_avoidance.adoc` inclusion in the single page guide defined in `userguide_single.adoc`
