### ISSUE TITLE
Dependency verification's trusted keys is case sensitive

### ISSUE THREAD

**Issue by hrafnthor** [gradle/gradle#16587]
### Expected Behavior
Setting trusted key ids to uppercase should work for dependency verification. For instance:

`<trusted-key id="2E3A1AFFE42B5F53AF19F780BCF4173966770193" group="^org[.]jetbrains($|([.].*))" regex="true"/>`

### Current Behavior
Having trusted key ids in uppercase will fail dependency verification with a key verification error

    org.gradle.api.InvalidUserDataException: Dependency verification failed for configuration ':classpath':
    - On artifact annotations-13.0.jar (org.jetbrains:annotations:13.0) in repository 'MavenRepo': 
    Artifact was signed with key '2e3a1affe42b5f53af19f780bcf4173966770193' (IntelliJ IDEA Sign Key 
    <intellij-idea-sign-key-noreply@jetbrains.com>) and passed verification but the key isn't in your trusted keys list.

### Context
Testing out the dependency verification for the first time, I was using gpg to fetch the keys I needed, and copying them in. Having these keys fail the verification, left me a bit lost on what I needed to do to make it work. For instance for Jetbrains:

    gpg --keyid-format LONG -k 0xBCF4173966770193
    pub   rsa2048/BCF4173966770193 2013-12-10 [SC] [expires: 2023-12-08]
          2E3A1AFFE42B5F53AF19F780BCF4173966770193
    uid                 [ unknown] IntelliJ IDEA Sign Key <intellij-idea-sign-key-noreply@jetbrains.com>
    sub   rsa2048/C9F04E6E2DC4F7F8 2013-12-10 [E] [expires: 2023-12-08]

### Steps to Reproduce 
Setting any trusted-key id to uppercase seems to cause this issue.

### Your Environment
Ubuntu 20.04
Gradle 6.6.1
Android Gradle plugin 4.1.2

**Comment by bmuskalla** [comment]
@melix Do you remember if this might be for a good reason/by design or simply an oversight?

**Comment by melix** [comment]
This is an oversight.
