### ISSUE TITLE
Expanding properties breaks escaped characters in sources jar

### ISSUE THREAD

**Issue by alexstaeding** [gradle/gradle#16583]
### Expected Behavior
The following build script (kotlin dsl) should replace the `$foo` tokens in meta.json with "bar":
```groovy
plugins { `java-library` }
val foo: String by extra("bar")
java { withSourcesJar() }
tasks {
  named<Jar>("sourcesJar") {
    expand(project.properties)
  }
}
```
src/main/resources/meta.json:
```json
{
  "foo": "$foo"
}
```
I run `./gradlew sourcesJar`, and as expected, meta.json has the correct replacement in the produced jar. It is expected that source files without tokens should remain completely unaffected.

### Current Behavior
Expanding properties causes escaped character literals (such as \n, \r etc...) to become unescaped in the produced sources jar.
e.g. src/main/java/Main:
```java
public class Main {
  public static void main(String[] args) {
    String newLine1 = "\n";
    char newLine2 = '\n';
    String tab1 = "\t";
    char tab2 = '\t';
    String cr1 = "\r";
    char cr2 = '\r';
    String slash1 = "\\";
    char slash2 = '\\';
  }
}
```
becomes this in the sources jar:
```java
public class Main {
  public static void main(String[] args) {
    String newLine1 = "
";
    char newLine2 = '
';
    String tab1 = "	";
    char tab2 = '	';
    String cr1 = "
";
    char cr2 = '
';
    String slash1 = "\";
    char slash2 = '\';
  }
}
```

(Note: The classes in the sources jar are correct if I remove `expand(project.properties)`)

### Context
I am building a sources jar with Gradle to later be compiled at runtime. I discovered this when the runtime compilation strangely failed although IntelliJ said the code was correct.

### Steps to Reproduce 

1) Create a standard Gradle project with version 6.8.3
2) Add the following 3 files:

build.gradle.kts:
```groovy
plugins { `java-library` }
val foo: String by extra("bar")
java { withSourcesJar() }
tasks {
  named<Jar>("sourcesJar") {
    expand(project.properties)
  }
}
```
src/main/resources/meta.json:
```json
{
  "foo": "$foo"
}
```
src/main/java/Main.java
```java
public class Main {
  public static void main(String[] args) {
    String newLine1 = "\n";
    char newLine2 = '\n';
    String tab1 = "\t";
    char tab2 = '\t';
    String cr1 = "\r";
    char cr2 = '\r';
    String slash1 = "\\";
    char slash2 = '\\';
  }
}
```
3) run `./gradlew sourcesJar`
4) Unpack the sources jar and open Main.java (I used notepad++)
### Your Environment

Build scan URL: https://scans.gradle.com/s/3ij5k2efnp46i

**Comment by alexstaeding** [comment]
This is a pretty significant bug because it renders the generated source jar uncompilable. Is there any extra info I can provide or are there any debugging steps I can try?

**Comment by alexstaeding** [comment]
I have found a workaround that works for me:
```
filesMatching("meta.json") {
  expand(project.properties)
}
```

This is still an issue though; expanding properties should not break escaped literals in source files.

**Comment by mlopatkin** [comment]
We are adding an API to turn this unescaping off in issue #10492. Everyone interested should track progress there, I'm closing this one as a duplicate.
