### ISSUE TITLE
Dependency locking of settings classpath isn't properly persisted

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle#16593]
See discussion at https://gradle-community.slack.com/archives/CAH4ZP3GX/p1616012112013700

The generated the `settings-gradle.lockfile` only contains:
```
# This is a Gradle generated file for dependency locking.
# Manual edits can break the build and are not advised.
# This file is expected to be part of source control.
empty=
```

In 6.8.3 (using the same steps as below) correctly persists the settings classpath in `gradle/dependency-locks/settings-classpath.lockfile`.

### Current Behavior or error

Settings classpath is not persisted at all, so when combined with strict locking, build fails afterwards.

### Steps to Reproduce 

1. generate basic project with `gradle init` (I'm using the Kotlin DSL, in case that matters)
2. add the following to the `settings.gradle.kts`
```kotlin
plugins {
    id("com.gradle.enterprise") version "3.6"
}
buildscript {
    dependencyLocking {
        lockAllConfigurations()
        lockMode.set(LockMode.STRICT)
    }
}
gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
    }
}
```

3. run `./gradlew tasks --write-locks` → this generates a `settings-gradle.lockfile`, but it only contains an `empty=` line
4. run `./gradlew tasks`, it fails with `Locking strict mode: Configuration 'classpath' is locked but does not have lock state.`

### Your Environment

7.0-milestone-3

Build scan URL: with `--write-locks`: https://scans.gradle.com/s/op42azhrh5uqi
Following build that fails with strict locking doesn't generate a build scan as it fails too early.

**Comment by tbroyer** [comment]
When **not** using the `plugins {}` DSL, it works correctly though.

Replace the above snippet with the following:
```kotlin
import com.gradle.enterprise.gradleplugin.GradleEnterpriseExtension
buildscript {
    dependencyLocking {
        lockAllConfigurations()
        lockMode.set(LockMode.STRICT)
    }
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.gradle.enterprise:com.gradle.enterprise.gradle.plugin:3.6")
    }
}
apply(plugin = "com.gradle.enterprise")
configure<GradleEnterpriseExtension> {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
    }
}
```
and the `settings-gradle.lockfile` now contains:
```
# This is a Gradle generated file for dependency locking.
# Manual edits can break the build and are not advised.
# This file is expected to be part of source control.
com.gradle.enterprise:com.gradle.enterprise.gradle.plugin:3.6=classpath
com.gradle:gradle-enterprise-gradle-plugin:3.6=classpath
empty=
```

Simply adding
```kotlin
plugins {
    id("com.gradle.enterprise") version "3.6"
}
```
(in addition to the above, even with a different version; or a different plugin, I tried with `id("net.ltgt.errorprone") version "1.3.0" apply false`) is enough to trigger the issue: the lockfile is empty.

**Comment by ljacomet** [comment]
This is caused by internal state in Gradle causing the creation of two different dependency locking providers for settings. And the one that does not see any dependency resolution ends up overwriting the output of the other one.
