### ISSUE TITLE
Support Detekt/Ktlint as the first party plugin 

### ISSUE THREAD

**Issue by chao2zhang** [gradle/gradle#16592]
Context:
- We have [Checkstyle](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html) + [PMD](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Pmd.html) plugin for Java code static analysis.
- We also have [CodeNarc](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CodeNarc.html) for Groovy.

Given that we have Kotlin code in Gradle repository, and KTS support is also a first-class citizen, I would propose to integrate [Detekt](https://github.com/detekt/detekt) and/or [Ktlint](https://github.com/pinterest/ktlint) as the first-party plugin.

Benefits:
- Detekt is facing quite a number of issues with Kotlin versioning. It would be great if we can align the versioning in Gradle. This PR probably depends on https://github.com/gradle/gradle/issues/16345
- Detekt currently has an official gradle plugin so this is not a start from scratch. See https://github.com/detekt/detekt/tree/master/detekt-gradle-plugin
- Promote Kotlin as a first-class language supported by Gradle (Not sure if this is announced anywhere)

I would be happy to contribute, but I am opening this issue to discuss first the plan with the information that I do not know. For example, I am open to convert the detekt-gradle-plugin to groovy/detekt if necessary.

**Comment by ZacSweers** [comment]
I don't think this is a good idea and also don't think tying detekt's version to gradle makes sense.

**Comment by jjohannes** [comment]
Thanks for the suggestion, but we won't pull more plugins for third party tools into Gradle Core. We rather plan to move such plugins - like Checkstlyle, PMD, CodeNarc - out of Gradle Core at some point.

If there is a concrete issue in Gradle Core that causes problems with the Detekt/Ktlint plugins, please open a separate issue for that.
