### ISSUE TITLE
Toolchain downloads should ask before downloading

### ISSUE THREAD

**Issue by Leo40Git** [gradle/gradle#16599]
### Expected Behavior
The new [toolchains feature](https://docs.gradle.org/current/userguide/toolchains.html) should ask for confirmation before downloading a JDK.

### Current Behavior
Gradle automatically downloads a matching JDK, _without asking the user_.

### Context
A JDK is quite massive compared to usual dependencies. It's kinda scummy to download one without asking, no?

**Comment by LambdAurora** [comment]
Would like this to even go further and in addition to asking to download the matching JDK, have a third option to force the current installed JDK with a warning telling the user that the project requires a matching JDK and forcing another JDK might break stuff and to only do that if the user know what they're doing.

**Comment by melix** [comment]
You can see the toolchain as any other regular 3rd party dependency. We don't ask for each dependency to be downloaded, and some of them are quite massive too. Should you want to disable automatic download, you can: disable_auto_provision

**Comment by ljacomet** [comment]
As answered, you can disable this: https://docs.gradle.org/current/userguide/toolchains.html#sub:disable_auto_provision

There is no plan to change the default and no plan to have the tool request permission during execution.
