### ISSUE TITLE
Support auto-download of Java toolchains for more vendors than just AdoptOpenJDK

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#16596]
### Expected Behavior
Ideally, the auto-download feature for Java toolchains should work for *any* toolchain that can be auto-detected. As I acknowledge it's quite some work to support all platforms, at least more (commonly used) vendors than just AdoptOpenJDK should be supposed, esp. GraalVM.

### Current Behavior
Auto-download of Java toolchains only works for the AdoptOpenJDK vendor.

### Context
I was assuming I could leverage the toolchain support to bootstrap everything (JDK, Gradle, etc.) needed for a build to work on a freshly installed machine. But that's not the case for a project requiring GraalVM.

Also see my somewhat related issue #15535 (which already has PR #16595 pending).

**Comment by rkrisztian** [comment]
I need the same, i.e. making Gradle download a Zulu build of the OpenJDK.

**Comment by sschuberth** [comment]
Reopening this as it's related to https://github.com/gradle/build-tool-roadmap/issues/29.

**Comment by sschuberth** [comment]
I'm hoping for @melix' https://github.com/gradle/gradle/pull/18028 to resolve this issue!

**Comment by wolfs** [comment]
Will be fixed by https://github.com/gradle/gradle/pull/21082.
