### ISSUE TITLE
Clean up signing with useGpgCmd()

### ISSUE THREAD

**Issue by micheljung** [gradle/gradle#16597]
### Expected Behavior
Signing with GPG works as documented

### Current Behavior
Documentation and error messages are misleading

### Context
I'm trying to sign files.

| Command  | Result |
|---|---|
| `gradle sign -Psigning.gnupg.passphrase=1234` | No value has been specified for property 'signatory.keyId'. |
| `gradle sign -Psigning.gnupg.passphrase=1234 -Psignatory.keyId=ABC12345` | No value has been specified for property 'signatory.keyId'. |
| `gradle sign -Psigning.gnupg.passphrase=1234 -Psigning.gnupg.keyName=ABC12345` | A problem occurred starting process 'command 'gpg2'' |
| `gradle sign -Psigning.gnupg.passphrase=1234 -Psigning.gnupg.executable=gpg -Psigning.gnupg.keyName=ABC12345` | OK                                                          |

* The doc states that "the default key is used for signing" but that doesn't seem to be the case
* The error message that `signatory.keyId` needs to be specified is misleading.
* Gradle uses `gpg2` by default but `gpg2` seems to have been renamed to `gpg` a long time ago

See also:
- https://discuss.gradle.org/t/use-of-signing-plugin-with-gpg-agent-fails-with-gradle-5-x/38351
- #8657

### Steps to Reproduce 

Gradle 6.8.3

build.gradle
```
plugins {
  id "java"
  id "signing"
}

group = "com.example"
version = "1.0"

signing {
  useGpgCmd()
  sign configurations.archives
}
```

Dockerfile:
```
FROM gradle:6.8.3

RUN apt update && \
  apt install -y gpg

RUN export GNUPGHOME="$(mktemp -d)" && \
  echo 'Key-Type: default\n\
Key-Length: 1024\n\
Name-Real: Test\n\
Name-Comment: Test\n\
Name-Email: test@example.com\n\
Expire-Date: 0\n\
Passphrase: 1234\n\
%commit\n\
' > gen-key

RUN gpg --batch --generate-key gen-key

RUN gpg --list-secret-keys && \
echo '\
plugins {\n\
  id "java"\n\
  id "signing"\n\
}\n\
\n\
group = "com.example"\n\
version = "1.0"\n\
\n\
signing {\n\
  useGpgCmd()\n\
  sign configurations.archives\n\
}\n\
' > build.gradle

RUN gradle sign -Psigning.gnupg.passphrase=1234 -Psigning.gnupg.executable=gpg -Psigning.gnupg.keyName=$(ls /root/.gnupg/openpgp-revocs.d/ | cut -c33-40)
```

**Comment by ljacomet** [comment]
Need to check if this is only documentation or if the code does not behave as expected.

**Comment by hegyibalint** [comment]
I'm trying to unwrap the issues listed here, starting with choosing the correct `gpg` vs. `gpg2` command.

## The `gpg` vs `gpg2` selection
https://github.com/gradle/gradle/blob/6497c5f795967062eceba209c8fae163719d75bd/subprojects/security/src/main/java/org/gradle/security/internal/gnupg/GnupgSettings.java#L47-L53

Gradle, based on the `useLegacyGpg` parameter, can change which binary it should use, when `useGpgCmd()` is used.
It seems though, that this became in the last few years unusable, as distros moved by default to GPGv2.

## Analysis

I'm no GPG historian, but from what I know, GPGv1 is only used in embedded cases, and almost everybody uses GPGv2 from the shell. In many cases, `gpg2` will be just a symlink to `gpg`. The main concern here is that it seems that the `gpg2` symlink is not created by all parties - probably as the stable, and LTS releases are both coming from the `2.*` branches. 

I've checked some distros with docker and collected out which binaries exist:
| OS     | `gpg` | `gpg2` |
|-|-|-|
| Alpine  | :heavy_check_mark: | :heavy_check_mark: |
| Debian | :heavy_check_mark: | :x: |
| Ubuntu | :heavy_check_mark:  | :x: |
| CentOS | :heavy_check_mark: | :heavy_check_mark: |
| Arch   | :heavy_check_mark: | :heavy_check_mark: |

From which, it's obvious that Debian-based distros dropped the linked `gpg2` binary (at least in the simple case when `apt install gpg` is used).

# What to do

I think the most reasonable thing to do here is to:
 - Consider setting `gpg` as the new default
 - Deprecate the legacy flag, as the situation can change between distributions how this is handled.

But more research is needed, as this change is highly backward incompatible.

[1] - https://lwn.net/Articles/696561/

**Comment by hegyibalint** [comment]
> The doc states that "the default key is used for signing" but that doesn't seem to be the case

This one, I cannot reproduce - the test, and my test projects agree that the default key is picked up.
