### ISSUE TITLE
Support fork options in Javadoc task

### ISSUE THREAD

**Issue by mnlipp** [gradle/gradle#16602]
... or (better) move fork options to common anchestor.

### Context and Expected Behavior

Sometimes the JavaDoc task has to be executed in a forked JVM. Doclets such as the [ascii(doctor)doclet](https://github.com/chrisvest/asciidoclet) or the [markdown doclet](https://github.com/mnlipp/jdrupes-mdoclet) need access to some types that are by default hidden in a module and must be made accessible using JVM options. (Note that this is not due to bad doclet design but rather due to the bad design of the standard doclet).

Therefore the "fork options" available for the JavaCompile task should be available for the JavaDoc task as well.

### Current Behavior
Currently a doclet with these requirements can only be run with the JavaExec task.

**Comment by mnlipp** [comment]
It's still a problem...

**Comment by slovdahl** [comment]
@mnlipp does this work? Seems to work fine for me using Temurin 17.0.8 and Gradle 8.3 at least.


```groovy
configurations {
    javadocDoclet
}

dependencies {
    javadocDoclet 'org.jdrupes.mdoclet:doclet:3.1.0'
}

javadoc {
    options.docletpath = configurations.javadocDoclet.files.asType(List)
    options.doclet = 'org.jdrupes.mdoclet.MDoclet'

    options.setJFlags([
            '--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED',
            '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED'
    ])

    // ...
}
```

**Comment by mnlipp** [comment]
If it works for you, it should work for everybody. Maybe somebody did something with the gradle task after all.

I'll try with some of my projects in the next weeks and if I can confirm it, I'll update the documentation.

Thanks for giving it a try.

**Comment by mnlipp** [comment]
Looks good.
