### ISSUE TITLE
Visiting the same ZipFileTree multiple times is inefficient

### ISSUE THREAD

**Issue by jochenberger** [gradle/gradle#1660]
In my project, I have several subprojects each of which extracts a directory from a huge ZIP using `Sync` tasks with a `ZipFileTree` as their inputs.
Every time the `visit` method is called, `ZipFileTree` reads the entries from the underlying ZIP file (https://github.com/gradle/gradle/blob/v4.1.0/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipFileTree.java#L80). If the file has not changed, the `entriesByName` could be reused/memoized to speed up multiple iterations.

**Comment by bmuschko** [comment]
Are you interested in providing a pull request if you think the runtime behavior could be improved? Please also add a performance test if you happen to go for it.

**Comment by jochenberger** [comment]
No, I'm not because I don't want to sign a CLA.

**Comment by oehme** [comment]
I'm not sure how big of an issue the `entriesByName` part is, did you run it through a profiler? The biggest issue was probably #2716 - copying the zip contents to the temp dir on every visit.

**Comment by jochenberger** [comment]
Maybe #2716 will fix this. I'll have another look at this once a 4.2 pre-release is out.

**Comment by eriwen** [comment]
Can this now be closed @oehme and @jochenberger?

**Comment by oehme** [comment]
@jochenberger did you give 4.2 a go?

**Comment by jochenberger** [comment]
Yes, but it didn't seem to improve in that particular area. I haven't had a chance to perform any thorough tests yet. If you're positive that `getEntries()` is fast enough to be called on each `visit()`, we can close this. I can always reopen if I find out anything new.

**Comment by oehme** [comment]
I'm not sure they are fast enough, but their overhead would have been completely masked by the repeated copying that we did before. So I'm curious why performance wouldn't improve. It should do a lot less file IO now.

**Comment by jochenberger** [comment]
I only did some profiling with 4.1 and my build spent a lot of time in `org.apache.commons.compress.archivers.zip.ZipFile.readCentralDirectoryEntry(Map<ZipArchiveEntry, NameAndComment>)`. And that is called from the `ZipFile` constructor. In 4.2 (RC), the constructor is still called on every `visit`, so I guess that it hasn't improved in that regard. But I will need to do more tests. Unfortunately, I can't make any promises about when I'll find the time to do that.

**Comment by oehme** [comment]
Understood. If your build was bottlenecked by that, then that won't have changed in 4.2. How big is the zip in question?

**Comment by jochenberger** [comment]
20 MB, about 215MB uncompressed, 14459 files
