### ISSUE TITLE
Typo in API documentation for Project.afterEvaluate()

### ISSUE THREAD

**Issue by duanasq** [gradle/gradle#16615]
I think there is a typo [here in the API documentation of Project](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/Project.java#L1337). 

### Expected Behavior

I expected Project.afterEvaluate() to be called at the end of the configuration of the build file.

### Current Behavior

The javadoc says it happens at the end of the execution of the build file.

### Context

As a person learning gradle (and gradle plugins), I didn't know what "evaluate" meant in terms of the three phases "initialise, configure and execute". I was surprised to read the javadoc that says it means after _execution_ of the build file.

### Your Environment

Build scan URL:

Thank you! This is an amazing project, I am happy to make even the smallest contribution. Would be very satisfying to be able to change line 1337 :). (I would just change the first word "executed" to "configured".)

**Comment by ljacomet** [comment]
Hey,

Thanks for the feedback and the proposal to open a PR to fix it.
I believe it will require changing more than a single word, but happy to get your proposal on this to make it clearer for new Gradle users.

**Comment by duanasq** [comment]
ok thanks! will do
