### ISSUE TITLE
Task in apply from failed, but work from top level build.gradle file

### ISSUE THREAD

**Issue by mtrakal** [gradle/gradle#16613]
Have code:
```
task detektProjectBaseline(type: io.gitlab.arturbosch.detekt.DetektCreateBaselineTask) {
    description = "Overrides current baseline."
    ignoreFailures.set(true)
    parallel.set(true)
    buildUponDefaultConfig.set(true)
    setSource(files(rootDir))
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
    baseline.set(file("$rootDir/config/detekt/detekt-baseline.xml"))
    include("**/*.kt")
    include("**/*.kts")
    exclude("**/resources/**")
    exclude("**/build/**")
}
```
when this code is located in top level `build.gradle` file. Gradle sync and build work as expected. But when I just move it to external file and call `apply from 'file.gradle'` build failed on: 
> Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'io' for root project 'My Application' of type org.gradle.api.Project.

### Expected Behavior
Build work as expected

### Current Behavior
Build failed with error `Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'io' for root project 'My Application' of type org.gradle.api.Project.`

### Steps to Reproduce 
https://github.com/mtrakal/gradle-detekt-issue

https://github.com/mtrakal/gradle-detekt-issue/blob/master/config/detekt.gradle
https://github.com/mtrakal/gradle-detekt-issue/blob/master/build.gradle

I reported same issue to Detekt, because have no idea where is the root of cause: https://github.com/detekt/detekt/issues/3594

**Comment by big-guy** [comment]
`file.gradle` has a different classpath to the main `build.gradle` file, so the task types visible in `build.gradle` are not visible in `file.gradle`.

Take a look at [precompiled script plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins) as one way to break up your configuration into reusable chunks.
