### ISSUE TITLE
Module wide gradle.properties not working

### ISSUE THREAD

**Issue by letianxu** [gradle/gradle#16610]
android.useAndroidX=true in module wide gradle.properties doesn't work

### Expected Behavior
Module wide gradle.properties should take effect

### Current Behavior

Configuration `debugRuntimeClasspath` uses AndroidX dependencies, but the `android.useAndroidX` property is not enabled.
Set `android.useAndroidX=true` in the `gradle.properties` file and retry.

### Context

We want to rewrite UI by using jetpack composable so we upgrades gradle to latest one 6.8.3, the issue stalls our development process

We have a project including multiple modules including some android libraries, apps, and androidx is only enabled in app modules. On the project level gradle.properties android.useAndroidX=false, so that other libraries are still using android support. The solution is wokring before upgrade.

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
