### ISSUE TITLE
Gradle 6.3 version treat 6.3.65-snapshot as a Maven SNAPSHOT version ( not valid ) 

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [gradle/gradle#16624]
### Expected Behavior
6.x versions of Gradle(tested with Gradle 6.3) and maven-publish should have same working and not treat `6.3.65-snapshot` artifact version as SNAPSHOT artifact. This is not the same behavior with Gradle 4.x and Gradle 5.x versions

### Current Behavior
Gradle is interpreting 6.3.65-snapshot as a SNAPSHOT version and therefore trying to deploy SNAPSHOT version metadata.

### Context
 I m trying to upload artifact with version (6.3.65-snapshot) to Sonatype Nexus 3.x releases version policy repository.
I could successfully publish 6.3.65-snapshot to Sonatype Nexus 3.x repository having releases version policy set when I used 4.10.0 and 5.4.1 versions of Gradle. But when upgraded the same project to Gradle 6.3 version, seems like Gradle is treating `6.3.65-snapshot` version as SNAPSHOT version.

### Steps to Reproduce 

I don't have the project on my Github account. But replicating this scenario is straight forward, just by comparing publish task output with Gradle 5.x version and Gradle 6.x versions

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
This change happened over a major version and is intentional. Please use another suffix than `snapshot` case insensitive.
There is thus no plan to restore the past behavior.
