### ISSUE TITLE
Orphaned download build operations from `maven-publish`

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#1662]
### Current Behavior

Two pictures worth a thousand words:

![gradle-3 5-rc2-fix-1641-eclipse](https://cloud.githubusercontent.com/assets/132773/24311143/22ddd8b4-10d3-11e7-99ea-971008d3f57b.gif)

![gradle-3 5-rc2-fix-1641-idea](https://cloud.githubusercontent.com/assets/132773/24311147/28670ed6-10d3-11e7-9e96-d74367f1908c.gif)

### Expected Behavior
The download build operations should be wired to their context.

### Context

See #1641 and #1658 for details and discussion.

### Steps to Reproduce (for bugs)

Publish an artifact to a remote http repository using the `maven-publish` plugin with a version of the very same artifact already present in the target repository.

**Comment by oehme** [comment]
@ldaley Am I correct that this was fixed by https://github.com/gradle/gradle/commit/92e1617aac09b6f26bb921eccd7e3aa3131d049e#diff-afed11c0a1872ed31be4dfe32ed9bb23?
