### ISSUE TITLE
FileNotFoundException in TestKit tests: lib-android/build/20210320_1519030999411730848.compiler.options

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#16620]
In my end-to-end tests using TestKit, I non-deterministically get the above error in the `cleanup()` step of my Spock tests. In that step, I delete the temp build dir to prepare a clean slate for the next test. I am building and testing with Gradle 7M3 in this scenario.

### Current Behavior or error

Tests "fail" with `FileNotFoundException` during cleanup step. The file in question has unknown provenance.

### Steps to Reproduce 

1. Clone https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/tree/gradle7-build
2. Run `./gradlew functionalTest -DfuncTest.quick`
3. I expect this will lead to a small number of failures of this kind.

### Your Environment

I'm using milestone-3.

I could workaround this error by catching and suppressing the exception, but I'm reporting here in case in indicates a real problem. What is `<timestamp>.compiler.options`? Why does Apache `FileUtils` find it and then fail to delete it? I tried debugging locally, and noticed that this file is not even always created (or maybe it's always created but nondeterministically deleted by some other process).

Build scan URL: https://scans.gradle.com/s/2oixfh5ev6iqo/tests/:functionalTest/com.autonomousapps.android.AdviceSpec/can%20filter%20compileOnly%20dependencies%20(Gradle%207.0-milestone-3%20AGP%207.0.0-alpha05)

**Comment by donat** [comment]
I quickly tried to reproduce it by repeatedly running the build with the same JDK, but the FileNotFoundException never happened.

**Comment by donat** [comment]
The `compiler.options` file never appears on my file system when I run the build. This might be the reason why I cannot reproduce the issue.

**Comment by donat** [comment]
@autonomousapps Any ideas on how can I reproduce this issue locally?
- Does it happen only on CI or for you locally as well? 
- Does the flakiness happen with Gradle 6.x?
- Does it happen with the latest RC?

**Comment by big-guy** [comment]
@autonomousapps I couldn't reproduce this locally either, but I have a hunch.

I suspect there are two tests cleaning up at about the same time. I've seen these kind of weird failures with deleting files when you have two processes trying to delete the same file hierarchy, so when deleting `build/functionalTest/foo/bar`...

P1: Stat `build/functionalTest/foo/bar`
P2: Stat `build/functionalTest/foo/bar`
P1: Unlink `build/functionalTest/foo/bar`
P2: Unlink `build/functionalTest/foo/bar` -- BOOM

This can sometimes create the same UUID for two different tests because you can have two different test processes 
https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/bf87e4613974f892b86d20bffeabb7daf80f2127/src/functionalTest/kotlin/com/autonomousapps/fixtures/RootProject.kt#L11

I don't have any theories as to why this would be worse with 7.0.

There are two things I think you could try:
1. Add on the value of system property `org.gradle.test.worker`. This is a unique id for each test worker.
2. Base the name of the directory on the name of the test class + a shorter random value. This is what we do in the gradle/gradle build.

**Comment by autonomousapps** [comment]
@donat @big-guy thanks for the investigation. I have been unable to repro this on either my macbook pro or my ubuntu 20.04 machine. I've only seen it so far when using Github Actions (GHA), which run on [ubuntu-latest](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/.github/workflows/pr.yml#L18).

I tried to repro it again today on GHA, but got this weird failure instead. It said `:functionalTest` failed, but all the tests report green in a [build scan](https://scans.gradle.com/s/pxva4frbpsndw/tests).

Tonight or tomorrow, I will follow Sterling's advice and try to repro again. I will also bump to the latest 7.0 RC.

**Comment by autonomousapps** [comment]
I updated to RC1. I have tested this on Ubuntu 20.04 locally, macOS Big Sur 11.1, and on `ubuntu.latest` on GHA. I can only reproduce that on GHA, and then only intermittently.

Next step, I will actually follow Sterling's advice and see if that makes the problem go away for good.

**Comment by autonomousapps** [comment]
Interesting findings today.

First of all, even with updating the test path to include a classname and worker ID, I still see the issue. Take a look at the path [here](https://scans.gradle.com/s/i5h2yz65odqag/tests/:functionalTest/com.autonomousapps.android.AdviceSpec/can%20filter%20incorrect%20configuration%20dependencies%20(Gradle%207.0-rc-1%20AGP%204.2.0-beta04)?anchor=e30&focused-exception-line=0-0#1).

Second of all, I was able to reproduce locally on my macbook pro (macOS Big Sur 11.1), when running the tests from IDEA Ultimate. I specifically ran [AdviceSpec](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/blob/main/src/functionalTest/groovy/com/autonomousapps/android/AdviceSpec.groovy). I got this error:
> File does not exist: build/functionalTest/AdviceFilterProject-7f54a8fd-006c-45-11/app/build/20210401_12198697736304616692.compiler.options
> java.io.FileNotFoundException: File does not exist: build/functionalTest/AdviceFilterProject-7f54a8fd-006c-45-11/app/build/20210401_12198697736304616692.compiler.options

Note that all the tests are running sequentially here, not in parallel.

Thirdly, I introspected the file that is causing trouble, and it looks like a classpath, presumably for `kotlinc`. Here's a truncated version of that file:
```
"-Xallow-no-source-files" "-classpath" "/Users/trobalik/Development/personal/dependency-analysis-android-gradle-plugin/build/functionalTest/AdviceFilterProject-8b148d1e-111b-41-11/app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/release/R.jar: ... and on it goes ...
"-Xjava-source-roots=/Users/trobalik/Development/personal/dependency-analysis-android-gradle-plugin/build/functionalTest/AdviceFilterProject-8b148d1e-111b-41-11/app/build/generated/source/buildConfig/release" "-jvm-target" "1.8" "-module-name" "app_release" "-no-jdk" "-no-reflect" "-no-stdlib" "-Xcommon-sources=/Users/trobalik/Development/personal/dependency-analysis-android-gradle-plugin/build/functionalTest/AdviceFilterProject-8b148d1e-111b-41-11/app/src/main/kotlin/com/example/MainActivity.kt" "/Users/trobalik/Development/personal/dependency-analysis-android-gradle-plugin/build/functionalTest/AdviceFilterProject-8b148d1e-111b-41-11/app/src/main/kotlin/com/example/MainActivity.kt"
```
I reiterate that I've never seen this issue before Gradle 7, but even so I can't tell you if it's due to Gradle or something funky with the Kotlin plugin(s).

**Comment by autonomousapps** [comment]
Well, I now have two successful runs in a row, on GHA. No idea what's going on, but I'm willing to chalk it up to neutrinos. Also, from this discussion I've come to believe the issue is probably test cleanup related only, in which case it ought to be safe to just swallow the error.
