### ISSUE TITLE
Back-end (JVM) Internal error: Failed to generate function

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#16623]
As soon as I reference `rootDir` inside an `object`, the compilation crashes

### Expected Behavior
Sync should work just fine

### Current Behavior
I get 
> e: /home/elect/IdeaProjects/build-logic/build.gradle.kts:52:5: Back-end (JVM) Internal error: Failed to generate function addCommitPush
File being compiled: (52,5) in /home/elect/.gradle/.tmp/gradle-kotlin-dsl-8972668404569685282.tmp/build.gradle.kts
The root cause java.lang.UnsupportedOperationException was thrown at: org.jetbrains.kotlin.codegen.context.CodegenContext.getOuterExpression(CodegenContext.java:222)

### Context
I was grouping common git function for fast dev cycles in an unique object

### Steps to Reproduce 
Clone [this branch](https://github.com/kotlin-graphics/build-logic/tree/bug)

Remove `rootDir` from [here](https://github.com/kotlin-graphics/build-logic/blob/bug/build.gradle.kts#L52) to have the compilation succedes

### Your Environment
Gradle 7.0 rc-1 (but it was crashing with m3 as well)

Build scan URL: it cant make it to the scan

**Comment by big-guy** [comment]
Did this work in 6.8?

**Comment by elect86** [comment]
Neither in 6.8.3

**Comment by donat** [comment]
Here's a minimal reproducer Kotlin DSL script:

```kotlin
object myObject {
     fun myFunction() {
        println(project)
    }
}
````

**Comment by donat** [comment]
I'm not sure if it's valid though. The problem is that the `project` reference is not available in the context of `myObject`.
