### ISSUE TITLE
JavaExec debugOptions don't work in Gradle 6.6.1

### ISSUE THREAD

**Issue by jhale1805** [gradle/gradle#16622]
### Expected Behavior

According to [the documentation](https://docs.gradle.org/6.6.1/javadoc/org/gradle/api/tasks/JavaExec.html#reset:~:text=Also%2C%20debug%20configuration%20can%20be%20explicitly%20set%20in%20debugOptions(Action)%3A) a task of the following form should allow me to specify the port at which Gradle will direct the jvm to start a debugger.
```
task runApp(type: JavaExec) {
    ...
    debugOptions {
        enabled = true
        port = 5566
        server = true
        suspend = false
    }
 }
```

### Current Behavior

The flag `--debug-jvm` continues to start the debugger on port 5005 instead of the custom one that I set in the `debugOptions`

That said, directly supplying the debugging arguments directly to the JVM using `jvmArgs=["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5566"]` does work.

### Context

I'm wanting to debug a Java project built with gradle on a port other than 5005 (useful for debugging two programs like a client and server). 

### Steps to Reproduce 

I basically followed the documentation as written. A build task as follows along with a simple program with a few instructions in main() should do the trick.
```
task runServer(type: JavaExec) {
  classpath = sourceSets.main.runtimeClasspath
  description = "Run Server"
  main = 'Example.java'

  // Enable debugging on port 5566
  debugOptions {
    enabled = true
    server = true
    suspend = true
    port = 5566
  }
}
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/2km5bupf4eqki

**Comment by big-guy** [comment]
Hmm, I don't see this behavior. 

`--debug-jvm` only switches enabled on or off.

If you run `gradle runServer --info`, does it start with the right arguments? 

Are you maybe running a different task that hasn't been configured?

**Comment by ljacomet** [comment]
Closing as original reporter did not react to clarification request.
