### ISSUE TITLE
Typesafe accessors to version catalog do not work in the subprojects block

### ISSUE THREAD

**Issue by ogolberg** [gradle/gradle#16634]
With Gradle 7.0-RC1,  I cannot seem to refer to libraries defined in a .toml catalog via typesafe accessors from within a subprojects block.

Below is a simplified version of my project setup, where I try to define a common dependency across all subprojects.

settings.gradle.kts:

```
rootProject.name = "subproject-catalog"

enableFeaturePreview("VERSION_CATALOGS")

include(
    ":api",
    ":impl"
)
```

gradle/libs.versions.toml:

```
[versions]
junit = "4.13.1"

[libraries]
junit = {module = "junit:junit", version.ref = "junit" }
```

build.gradle.kts:

```
plugins {
    kotlin("jvm") version "1.4.31"
}

subprojects {
    apply(plugin = "kotlin")

    // this does not work
    dependencies {
        testImplementation(libs.junit)
    }
}

// this works
dependencies {
    testImplementation(libs.junit)
}
```

It errors out like so:

```
* Where:
Build file '<...>/build.gradle.kts' line: 10

* What went wrong:
Extension with name 'libs' does not exist. Currently registered extension names: [ext, kotlin, kotlinTestRegistry, defaultArtifacts, sourceSets, reporting, java, javaToolchains]
```

**Comment by tbroyer** [comment]
I suppose a workaround would be to use `rootProject.libs.junit` instead of `libs.junit`?

**Comment by henrik242** [comment]
@tbroyer Should this work in buildSrc plugins as well?  With e.g. `testImplementation(project.rootProject.libs.junit)` in `buildSrc/src/main/kotlin/MyPlugin.kt` I currently get  `Unresolved reference: libs` (ref. https://github.com/gradle/gradle/issues/16652)

**Comment by melix** [comment]
We don't plan to fix this short term. We discourage use of cross-configuration and there are 2 workarounds:

1. use `rootProject.projects` to access the catalog
2. use the Groovy DSL instead, in which case it doesn't matter if the extension exists or not

**Comment by mecoFarid** [comment]
@melix 

> "We discourage use of cross-configuration"

 Can you please add, at least, a reference to who "**we**" are and why it is discouraged and if it is discouraged why we have `subprojects` and `allprojects` anyway?

**Comment by aSemy** [comment]
> > "We discourage use of cross-configuration"
> 
> Can you please add, at least, a reference to who "**we**" are and why it is discouraged and if it is discouraged why we have `subprojects` and `allprojects` anyway?

@mecoFarid There is some documentation on why `subprojects` and `allprojects` are discouraged at the bottom of this page: https://docs.gradle.org/8.0.1/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration

There are also some mentions in these pages:

* https://docs.gradle.org/8.0.1/userguide/multi_project_configuration_and_execution.html#sec:decoupled_projects
* https://docs.gradle.org/8.0.1/userguide/performance.html#only_apply_plugins_where_theyre_needed

What it boils down to [composition vs inheritance](https://melix.github.io/blog/2021/12/composition-in-gradle.html). `allprojects {}` and `subprojects {}` makes Gradle configuration inherited, which in principle is fine (after all inheriting build config how Maven works, and that's a strong build tool), but generally it makes Gradle slower and it's easier to make mistakes.

**Comment by FyiurAmron** [comment]
> I suppose a workaround would be to use `rootProject.libs.junit` instead of `libs.junit`?

TBH, I just use
`val libs = rootProject.libs`
in my `subprojects` / `allprojects` , and then I go about my business. Is it a "bad practice", shunned by the _refined_ ones? Yes, perhaps. Will the future generations hate me for it? Unlikely, but possible.

Does it work and allow me to focus on actual programming?

Yes.
