### ISSUE TITLE
Android Gradle error: Could not find method dependencyResolutionManagement()

### ISSUE THREAD

**Issue by SaidiAli** [gradle/gradle#16647]
### Expected Behavior

Android Gradle should sync project

### Current Behavior

I used android studio yesterday very well, everything was okay, but suddenly today gradle is not syncing.
First I got an that the jdk location is wrong, then I select the location in the pop up but it happens again in subsequent restarts.
Also I get this error:

`A problem occurred evaluating settings 'Campus'.
> Could not find method dependencyResolutionManagement() for arguments [settings_82rgr53vi202j1gwh4gt9dzgt$_run_closure1@6ee75a30] on settings 'Campus' of type org.gradle.initialization.DefaultSettings.`

This was not a problem yesterday

### Steps to Reproduce 

create a new android project

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
Please indicate the Gradle and Android versions

**Comment by SaidiAli** [comment]
@ljacomet
`Android Studio Arctic Fox | 2020.3.1 Canary 12`
`Android Gradle plugin: 7.0.0-alpha12`
`Gradle version 6.1.1`

**Comment by ljacomet** [comment]
> Gradle version 6.1.1

There is your problem: that API was added in Gradle 6.8

**Comment by SaidiAli** [comment]
This actually helped, I bumped my gradle version to 6.8.2 and it synced. But I think android studio has a bug because was a new project and they had to do this out of the box. 
Thank you so much.

**Comment by astro-yoas** [comment]
hi, I also ecounter same problem with gradle version 7.0.4, this happens only when i run Gradle command
`Android Studio Arctic Fox | 2020.3.1 Patch 4
com.android.tools.build:gradle:7.0.4
https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip`
