### ISSUE TITLE
Add more Java installations detection options

### ISSUE THREAD

**Issue by lorenzleutgeb** [gradle/gradle#16645]
Hi!

@raboof and me [are wondering](https://discourse.nixos.org/t/auto-detecting-java-installations/4677) about a standard mechanism to discover JDKs on a system, particularly in the context of the [Nix](https://nixos.org/) package manager. We're aware of the `org.gradle.java.installations.{fromEnv,paths}` mechanisms that Gradle exposes, and that there are a number of heuristics implemented by Gradle.

I didn't manage to pass Java installations to Gradle via `{GRADLE,JAVA}_OPTS`:

```
JAVA_11JETBRAINS_HOME=/nix/store/r670i06rdg59g8zpzyzzdvv3w85k3kq7-jetbrains-jdk-11.0.7-b64
JAVA_11_HOME=/nix/store/zfwnw6bi1ljyfnwfs4n12ryxbxxa4wlg-openjdk-11.0.10+9
ORG_GRADLE_JAVA_INSTALLATIONS_PATHS=${JAVA_11JETBRAINS_HOME},${JAVA_11_HOME}
GRADLE_OPTS="-Dorg.gradle.java.installations.paths=${ORG_GRADLE_JAVA_INSTALLATIONS_PATHS}" gradle -q javaToolchains
JAVA_OPTS="-Dorg.gradle.java.installations.paths=${ORG_GRADLE_JAVA_INSTALLATIONS_PATHS}" gradle -q javaToolchains
```

Should that work?

I was wondering whether Gradle would be willing to make things a little easier here. Some options, in order of personal preference:
 1. Allow setting one of `org.gradle.java.installations.{fromEnv,paths}` via the environment, e.g. `ORG_GRADLE_JAVA_INSTALLATIONS_{FROMENV,PATHS}`.
 2. As a new convention, consider all `JAVA_*_HOME` variables to be candidates.
 3. Accept a new implementation of `InstallationSupplier` that scans `/nix/store` for Java installations.

Also, are there any JEPs, or similar efforts to unify ways of discovering JDKs?

/cc @bmuskalla

---

Edit: As of 2022-11 there are two new installation suppliers:

 * `IntellijInstallationSupplier` contributed by @rweisleder in #19890
 * `MavenToolchainsInstallationSupplier` contributed by @Okeanos in #19048
 
Edit: As of 2024-05-18 there is work ongoing for one more installation supplier:

 * `NixInstallationSupplier` by @lorenzleutgeb in #29214

**Comment by 3flex** [comment]
IntelliJ's built in support for downloading JDKs may benefit from this as well.

We could point to a directory (or have the autodetection check for the default IntelliJ download path, I think it's ~/.jdks) that we know contains multiple JDKs downloaded by IntelliJ, and use them in toolchains.

**Comment by lorenzleutgeb** [comment]
Yes, it looks like IntelliJ IDEA will default to downloading to `~/.jdks`. This could be added as an `InstallationSupplier` to Gradle.

Also, there's been work the other way round, to register JDKs downloaded by Gradle in IntelliJ IDEA: https://github.com/JetBrains/intellij-community/pull/1464

All of that works by supplying directories, with the JDKs being sub-directories. This would work for Nix as well, although the directory would have many more entries:

```
$ find /nix/store -maxdepth 1 -type d | wc -l
21646
```

```
$ find /nix/store -maxdepth 1 -type d -name '*jdk-*'
/nix/store/qsd848cffk29syl67r7yq19hgf1nmras-openjdk-8u272-b10-jre
/nix/store/0yjcz9q4p1nbwg7qr5x6mmrsap7m016q-openjdk-11.0.9+11
/nix/store/m5v6l2lmjslncl9hvyp493k3h2f947kx-jetbrains-jdk-11.0.7-b64
/nix/store/6ndz2aw3w61j999ydbykdpgczj6la2i0-openjdk-8u272-b10-jre
/nix/store/jq8bjsyk3qjidwi6npy844inz802fzky-openjdk-8u272-b10
/nix/store/x7zm8sdj4k42agpm2i5z7h0ygs4ng20w-openjdk-8u242-b08-jre
/nix/store/q0ap8aa5br4vr2y75n7hmacwlihmpdgq-openjdk-11.0.7-ga
/nix/store/g6l8fi6l0aq4713ba9cwsry85sqvzbaq-openjdk-8u242-b08
/nix/store/48ddc74sdlinbg5q5655i4z8kp6xasb0-openjdk-11.0.9+11
/nix/store/r670i06rdg59g8zpzyzzdvv3w85k3kq7-jetbrains-jdk-11.0.7-b64
/nix/store/526lsclbryma9qk5kadfqn2r6r7ndmsj-openjdk-8u272-b10-jre
/nix/store/cw580zrdvdqv8f0dk7cddf5p97pf84rw-openjdk-8u272-b10
/nix/store/7vj5k82kym6v0sljgw12qfkczhlwkp2w-openjdk-8u272-b10-jre
/nix/store/npnlqndq25wimi3nyp334c8hznhxwwik-openjdk-8u272-b10
/nix/store/m9qyc7zdrm42m809dhpgcvbgwifab2xi-openjdk-8u272-b10-jre
/nix/store/fmzyx4vadw5sy7y8zjw7ysv0952p4fpc-openjdk-8u272-b10
/nix/store/avwbx0mfdbqgh9dr0lhfpls7ys54bj07-jetbrains-jdk-11.0.7-b64
/nix/store/qpc15fcpmr93fpsv4s0rhwz5b6dbjsvl-openjdk-11.0.9+11
/nix/store/6njnlhvz2q5bd516pwdd09vrv4h0b7f0-openjdk-8u272-b10-jre
/nix/store/dff8y658p4xlppwspm2sbwwb77mx3s6k-openjdk-8u272-b10
/nix/store/8dsfl02y2i3xivpwynyxgnphf7nfd082-jetbrains-jdk-11.0.7-b64
/nix/store/zfwnw6bi1ljyfnwfs4n12ryxbxxa4wlg-openjdk-11.0.10+9
/nix/store/n1i0dnrky3wdmxlvkpg19bfw8l9ik732-openjdk-15.0.1-ga
/nix/store/6b2k015akivwvlmps54h7r1nqy6cjck6-openjdk-11.0.10+9
```

The problem being that this is not really reproducible. I'd prefer to explicitly specify a list of JDKs when wrapping Gradle, but I failed to do so via only environment variables (as mentioned in the initial description of the issue).

**Comment by raboof** [comment]
> This would work for Nix as well (...) The problem being that this is not really reproducible

Aside from reproducibility there are some more reasons this is not a great approach for Nix: most importantly, by looking at /nix/store 'manually' you might refer to things that are not in your 'current environment', which means Nix might garbage-collect them from under your feet unexpectedly (Nix of course takes care not to garbage-collect things that are part of active environments, but you lose that protection by scanning the store directly). Also, the internal directory structure of different JDK packages is not consistent: for example the `JAVA_HOME` for `openjdk15` is `/nix/store/b40bz6ylignrgpnidz4951j42k6a8l4y-openjdk-15.0.1-ga/lib/openjdk`, while for `adoptopenjdk-hotspot-bin-15` it's `/nix/store/k4snz9ny9b4qxaj98imxmhm28p8bjjzs-adoptopenjdk-hotspot-bin-15.0.2` - without the `/lib/openjdk`. The latter could perhaps be fixed, but it doesn't feel like the right direction.

I like the idea of scanning any environment variables of the form `JAVA_*_HOME` for JDK's. While not a widespread convention at this point, there is some precedent for it (https://www.google.com/search?hl=en&q=%22JAVA_8_HOME%22), and it seems to serve a need that isn't otherwise met yet.

**Comment by lorenzleutgeb** [comment]
> > This would work for Nix as well (...) The problem being that this is not really reproducible
> 
> Aside from reproducibility there are some more reasons this is not a great approach for Nix: most importantly, by looking at /nix/store 'manually' you might refer to things that are not in your 'current environment', which means Nix might garbage-collect them from under your feet unexpectedly (Nix of course takes care not to garbage-collect things that are part of active environments, but you lose that protection by scanning the store directly). Also, the internal directory structure of different JDK packages is not consistent: for example the `JAVA_HOME` for `openjdk15` is `/nix/store/b40bz6ylignrgpnidz4951j42k6a8l4y-openjdk-15.0.1-ga/lib/openjdk`, while for `adoptopenjdk-hotspot-bin-15` it's `/nix/store/k4snz9ny9b4qxaj98imxmhm28p8bjjzs-adoptopenjdk-hotspot-bin-15.0.2` - without the `/lib/openjdk`. The latter could perhaps be fixed, but it doesn't feel like the right direction.
> 
> I like the idea of scanning any environment variables of the form `JAVA_*_HOME` for JDK's. While not a widespread convention at this point, there is some precedent for it (https://www.google.com/search?hl=en&q=%22JAVA_8_HOME%22), and it seems to serve a need that isn't otherwise met yet.

Yeah, maybe I was using the word "reproducibility" incorrectly, but the first problem (profiles, GC) is what I meant. I just didn't expand any further, because I thought that the people working on Gradle might not be interested in those details :) But anyway, it's good to mention!

I am actually a bit surprised to hear that the `$JAVA_HOME` varies by package. By saying "it doesn't feel like the right direction", you refer to scanning `/nix/store` again, right? Because I would think that harmonizing `$JAVA_HOME` across JDK packages would be a good thing.

**Comment by raboof** [comment]
> I thought that the people working on Gradle might not be interested in those details :)

Yeah, fair enough, sorry for rambling ;)

> I would think that harmonizing `$JAVA_HOME` across JDK packages would be a good thing.

I agree it would be an improvement from an "it is nice when things are consistent" perspective, but actually *relying* on it (thus making it a somewhat-obscure 'rule') feels questionable.

**Comment by Okeanos** [comment]
Just had a quick look at the documentation and afterwards stumbled upon this issue. I am surprised no one mentioned [Maven Toolchains](https://maven.apache.org/plugins/maven-toolchains-plugin/), specifically the `~/.m2/toolchains.xml` file as a source of JDK locations that could be 'autodetected' by Gradle.

This would be particularly useful when migrating from Maven to Gradle to ease the transition or when having different projects that use either but require particular JDKs.

**Comment by lorenzleutgeb** [comment]
@ljacomet kindly asking for feedback from Gradle.

**Comment by ljacomet** [comment]
Toolchains installation locations are passed as _Gradle properties_ not system properties. What you tried should work by changing the `-D` to `-P` and passing that as a paramtere of the `gradle` command.

Regarding the different questions:
1. It feels weird to allow environment variables to be defaults for Gradle properties, especially when one of them is used to know which environment variables to read.
2. We do something similar in our test infrastructure. It makes me wonder about having an SPI for detection of JDKs instead of adding this kind of support natively.
3. Given the conversation, that seems like a tricky thing to support. So maybe it fits better as an external option if Gradle had an SPI for that.

@Okeanos That is a very good point and something which would make sense inside Gradle. If you are up for it, feel free to file an issue and propose a PR 😉

**Comment by Okeanos** [comment]
@ljacomet I am willing to take a look at it at the very least, however, would very much appreciate a few basic pointers, e.g. where to look inside the Gradle project for the _current_ toolchain detection implementation for instance. I have used Gradle but never worked on the project itself before.

**Comment by lorenzleutgeb** [comment]
@Okeanos If I were you I'd start from https://github.com/gradle/gradle/blob/4d54b872e15f36eb892f53f37a65717f2d16758d/subprojects/jvm-services/src/main/java/org/gradle/jvm/toolchain/internal/LinuxInstallationSupplier.java

**Comment by lorenzleutgeb** [comment]
FWIW in Nixpkgs, I took the `org.gradle.java.installations.fromEnv` route, see https://github.com/NixOS/nixpkgs/pull/119444

**Comment by big-guy** [comment]
Sorry, we don't want to add more built-in options.

I opened a new issue that describes roughly our approach: https://github.com/gradle/gradle/issues/29508

We want a mechanism so 3rd parties can add support for different package manager options and not require changes to Gradle to support them. Eventually, we would remove the existing options.
