### ISSUE TITLE
Create an Installer for installing Gradle

### ISSUE THREAD

**Issue by AvIsBeastMC** [gradle/gradle#16644]
I have had so many problems in installing Gradle for Cordova, yet still, not solved. I have been trying to install Gradle using the Steps that include Changing the Environment Variables, like changing User Variable Path and add the Location of the gradle folder and stuff like that, GRADLE_HOME and more..., I see it working for a lot of the people who did it by simply following the steps, they just don't work when I try entering gradle in cmd, bash and even on powershell. Hoping for a Solution like an Installer.

**Comment by AvIsBeastMC** [comment]
also to clarify, I have Java installed too...

**Comment by jjohannes** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

There are no plans for a specific Gradle installer.

Please find more information about how to install Gradle here:
- Using a package manager: https://docs.gradle.org/current/userguide/installation.html#installing_with_a_package_manager
- Installing manually: https://docs.gradle.org/current/userguide/installation.html#installing_manually
- You can also just use the [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper) by downloading [one of the samples](https://docs.gradle.org/current/samples/index.html) and then run `gradlew` located in the folder of the sample.
