### ISSUE TITLE
Signing build time regression (4s->41m) when upgrading from 6.5 to 6.7.x or 6.8.x

### ISSUE THREAD

**Issue by fwh-dc** [gradle/gradle#16651]
### Expected Behavior

We expect that build times does not degrade when upgrading the gradle versions.

### Current Behavior

We experience that building a release ```./gradlew assembleRelease :app:bundleRelease``` takes 3 times longer on version 6.7.1, 6.8.2 and 6.8.3 than on 6.5.

### Context

In order to support Jetpack compose in our Android app we want to upgrade gradle from version 6.5 to 6.8.3 and com.android.tools.build:gradle from 4.1.2 to 7.0.0-alpha09'

### Your Environment

We are building using a docker image that has Java 11 and commandlinetools-linux-6858069_latest.zip installed

~~When adding --debug or --info or --profile to the gradlew command the problem disappears on 6.8.3.~~

On 6.8.2 and 6.7.1 the profiler reveals:
:app:signOfficialReleaseBundle | 41m5.38s

On 6.5 that number is 
:app:signOfficialReleaseBundle | 4.546s

**Comment by fwh-dc** [comment]
UPDATE

We did some more testing. It turned out that the issue could be isolated to upgrading the plugin "com.android.tools.build:gradle" from 4.1.2 to 7.0.0-alpha09. 

Further testing revealed that
com.android.tools.build:gradle:4.1.2 does NOT have the defect. 
com.android.tools.build:gradle:4.1.3 does NOT have the defect. 
com.android.tools.build:gradle:4.2.0-beta06 has the regression.
com.android.tools.build:gradle:7.0.0-alpha09 has the regression.
com.android.tools.build:gradle:7.0.0-alpha12 has the regression.

Please feel free to close the issue if this is not the correct place to file the issue.

**Comment by bmuskalla** [comment]
This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
