### ISSUE TITLE
Very long syntax when using type-safe project accessors

### ISSUE THREAD

**Issue by henrik242** [gradle/gradle#16653]
The new Gradle 7 type-safe project accessors are cool, but some of the syntax becomes pretty involved.

Example: 
```
tasks {
  dependsOn(":my-app:assemble")
}
```
 .. becomes ...
```
tasks {
  dependsOn(project.projects.myApp.dependencyProject.tasks.assemble)
}
```
Is there a simpler way?  Or are there plans on improving the syntax?

SEO: `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")`

**Comment by jjohannes** [comment]
Thanks, this is good feedback.I don't hink there is a simpler syntax for this right now when using accessors. Maybe we can improve this in the future.

**Comment by melix** [comment]
FWIW: https://discuss.gradle.org/t/very-long-syntax-when-using-type-safe-project-accessors/39423

**Comment by jjohannes** [comment]
To clarify: It's still considered good practice to wire up lifecycle tasks (tasks without actions, inputs, outputs) via `dependsOn`. We may introduce a better API for such lifecycle tasks in the future. `assemble` is such a task.

This issue could be addressed by introducing an explicit "lifecycle task" concept in Gradle with a new API to wire these lifecycle tasks.
