### ISSUE TITLE
Configured repositories are ignored when building a plugin through plugin dependency substitution

### ISSUE THREAD

**Issue by ingokegel** [gradle/gradle#16654]
Gradle version: 7.0-RC1,  OS: Windows,  Java version: 11.0.10

In a composite build, if a plugin is substituted from an included build by adding 

```
pluginManagement {
    includeBuild("included-build")
}
```

to `settings.gradle.kts`, the included build ignores the configured repositories and only tries to resolve artifacts in `https://plugins.gradle.org/m2` .

Please see [this attached project ](https://github.com/gradle/gradle/files/6213067/gradle-repositories-bug.zip) and run `gradle` in the extracted directory.  The error message is:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gradle-repositories-bug'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.install4j:install4j-gradle:9.0.2-PRE2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/install4j/install4j-gradle/9.0.2-PRE
/install4j-gradle-9.0.2-PRE2.pom
     If the artifact you are trying to retrieve can be found in the repository
ut without metadata in 'Maven POM' format, you need to adjust the 'metadataSour
es { ... }' of the repository declaration.
     Required by:
         project : > project :included-build

```
but the configured repository is `https://maven.ej-technologies.com/repository` where this artifact exists.

**Comment by jjohannes** [comment]
Although in this scenario it may be unintuitive at first, this is the intended behaviour:
- When the plugins is assembled in the included build, it uses the repo declared there. This is the same as if you would run that build in isolation.
- When the plugin is **used** in the main build, it does not look at any repositories from the build providing the plugin. This is the same with how repository declarations are handled in Gradle everywhere (i.e. they are not transitive). You explcitly need to add it as a _plugin repository_ of the main build.
 

Your `settings.gradle.kts` should look like this:

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://maven.ej-technologies.com/repository")
    }
    includeBuild("included-build")
}
```

**Comment by maxim5** [comment]
> Although in this scenario it may be unintuitive at first, this is the intended behaviour:

God, literally spent the whole day trying to figure out why jitpack.io repo is always ignored before I found this issue.
This is counter-intuitive indeed. Actually, the fact it is composite build related was the last thing I considered.

From the official docs:

> Composite builds allow you to:
> - Combine builds that are usually developed **independently**, for instance, when trying out a bug fix in a library that your application uses.
> - Decompose a large multi-project build into smaller, more isolated chunks that can be worked on **independently** or together **as needed**.

Notice it mentions independence twice. The current designed behaviour is against this principle, because the nested project fails to build only when it's included. It respects nested `repositories` on its own.

Not to mention this forces duplicate `repositories` declarations.

**Comment by sureshg** [comment]
yeah, agree with @maxim5 ..spent a few days [trying to figure out this issue](https://github.com/JavierSegoviaCordoba/kopy/issues/37#issuecomment-2325417923) for a newly developed gradle plugin.  It's not intuitive at all.

**Comment by JavierSegoviaCordoba** [comment]
Can this be re-open to at least consider adding a better error message?
