### ISSUE TITLE
Remove jcenter from init scripts

### ISSUE THREAD

**Issue by ncimino** [gradle/gradle#16655]
Per the JFrog JCenter announcement here:

- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Brown-outs will happen on 4/12 and 4/26, so these build scripts will break on those days. 2/1/2022 it will be closed indefinitely.

It's too bad this will break older Gradle releases init functionality.

**Comment by ncimino** [comment]
FWIW, to reproduce:

```
./gradlew init
```

Select Java application and you will see `jcenter` added.

**Comment by jjohannes** [comment]
This is already fixed in 7.0-rc-1
