### ISSUE TITLE
Configuration Cache does not persist `int`

### ISSUE THREAD

**Issue by aaschmid** [gradle/gradle#16657]
On my [gradle-cpd-plugin](https://github.com/aaschmid/gradle-cpd-plugin) I have a task property named `minimumTokenCount` which was of type `int`. Besides an other issue with new `configuration-cache` I get `> Task 'cpdCheck' requires 'minimumTokenCount' to be greater than zero.` on the second run if I use `int`for the `minimumTokenCount` `@Input` property. Changing this to `Integer` makes the reproducer test case green again.

### Expected Behavior

I would except that `int` property could be configuration cached as `boolean`s does as well. Haven't found any documentation that it should not work.

### Current Behavior

`int` properties cannot be used with `configuration-cache`.

### Context

I try to enable my plugin to be usable with `--configuration-cache`, as requested in https://github.com/aaschmid/gradle-cpd-plugin/issues/54.

### Steps to Reproduce 

1. `git clone git@github.com:aaschmid/gradle-cpd-plugin.git`
1. Checkout reproducer branch: `git checkout reproduce.config.cache.problem.on.int`
1. Execute `./gradlew integTest --tests "de.aaschmid.gradle.plugins.cpd.test.CpdAcceptanceTest.Cpd task can be loaded from the configuration cache"`
1. Check for failure `> Task 'cpdCheck' requires 'minimumTokenCount' to be greater than zero.` on standard output of test results
1. Change to `Integer` by `git revert 0851999`
1. Execute the test again and see that it is working

### Your Environment

* MacOS Big Sur with OpenJDK 1.8.0_202
* Travis CI -> https://travis-ci.org/github/aaschmid/gradle-cpd-plugin/jobs/764663141
* Circle CI -> https://app.circleci.com/pipelines/github/aaschmid/gradle-cpd-plugin?branch=reproduce.config.cache.problem.on.int

**Comment by aaschmid** [comment]
Meanwhile - thank to @c-otto - I saw https://github.com/gradle/gradle/pull/14628/files#diff-239c622f1af32f1bee008aa813579ded9fffeb072f25557cf8eb27801268c770 where you changed `int` to `Property<Integer>`. `Property` was not necessary for me but if this would be the desired way forward, maybe documentation about this would be enough.

On the other side would supporting `int` increase backward compatibility. If you have a hint where a change would be necessary, maybe I can give it a shot.

**Comment by bamboo** [comment]
Hi @aaschmid, could you confirm the latest Gradle version you have been able to reproduce this issue with?

**Comment by aaschmid** [comment]
On the using side of the plugin I had the problem with 6.6, 6.7, and 7.0-RC1. On the building side - does that matter? - I used 6.6 only.

Should I test something in addition?

**Comment by bamboo** [comment]
Thanks, @aaschmid. The building side shouldn't matter.

At first I cannot reproduce the problem with [a simple test case](https://github.com/gradle/gradle/pull/16680/files) so I wonder what else might be different in your plugin's case. Possibly the interaction with convention mapping setup by [CpdPlugin](https://github.com/aaschmid/gradle-cpd-plugin/blob/6fd2c8ae57282337f523a5fa76d4a8cb7ecd88e3/src/main/java/de/aaschmid/gradle/plugins/cpd/CpdPlugin.java#L116). Let's see.

**Comment by aaschmid** [comment]
Thanks for the update and your reproducer seems fine. But can you reproduce it with my reproducer?

**Comment by bamboo** [comment]
Yes, I can reproduce the test failure you described.
