### ISSUE TITLE
Clean old logs

### ISSUE THREAD

**Issue by cdalexndr** [gradle/gradle#16663]
### Expected Behavior
Delete old logs.

### Current Behavior
My `C:\Users\<user>\.gradle\daemon\6.5.1` folder contains  ~3GB worth of logs files and counting...
This is garbage.

### Context
Logs occupy increasing disk space until there is no space left...

**Comment by jjohannes** [comment]
This feature request is already described in more detail in #2688. Please upvote there.

Closing this as duplicate.
