### ISSUE TITLE
Configuring a subproject using a 'buildscript' block from root build.gradle cannot apply plugins by id

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#1668]
When configuring subprojects using the `project(':subproject-name') {}` block and applying a `buildscript`, the configuration fails to apply plugins brought in with `classpath` configurationand using `apply plugin: 'id'` from within that `project(':subproject-name') {}` block.

### Expected Behavior

Should be able to apply plugins by Id in `project` block when that dependency is on the `classpath` from the `buildscript`.

### Current Behavior

Build fails with `Plugin with id 'kotlin' not found.`

### Context

I was trying to reproduce what I believe to be a compiler regression in Kotlin 1.0 vs Kotlin 1.1 by applying different plugins to different subprojects

### Steps to Reproduce (for bugs)

_build.gradle_

```groovy
plugins {
  id "com.gradle.build-scan" version "1.6"
}

buildScan {
  licenseAgreementUrl = 'https://gradle.com/terms-of-service'
  licenseAgree = 'yes'
}

model {
  tasks {
    wrapper {
      gradleVersion = '3.5-rc-1'
    }
  }
}

subprojects {
  apply plugin: 'java'
  repositories {
    mavenCentral()
    jcenter()
  }
}

project(':1.0.7') {
  buildscript {
    ext.kotlin_version = '1.0.7'

    repositories {
      jcenter()
      mavenCentral()
    }

    dependencies {
      classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
  }

  apply plugin: 'kotlin'

  dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version")
  }
}

project(':1.1.1') {
  buildscript {
    ext.kotlin_version = '1.1.1'

    repositories {
      jcenter()
      mavenCentral()
    }

    dependencies {
      classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
  }

  apply plugin: 'kotlin'

  dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version")
  }
}
```

_settings.gradle_

```groovy
include '1.0.7'
include '1.1.1'
```

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/tb5y6c5gln5hk

**Comment by bmuschko** [comment]
That's a limitation of declaring projects in just the root project. You would need to define buildscript classpath on the root level. However, in your case it wouldn't work as you will want to have two versions of the same plugin.

You can make it work by creating separate `build.gradle` files per subproject. It's definitely the better option anyway for organizing multi-project builds in regards to separation of concerns and maintainability.

**Comment by mkobit** [comment]
@bmuschko I definitely agree on the organization part, and that is generally how I organize projects. When using the `plugins` DSL I use the `apply false` anyways and selectively apply to subprojects, so this just came about from a "reduce code down as much as possible for minimal files demonstrating the issue" This probably isn't a more general use case. I do wonder if different plugin versions in the `plugins` DSL would be useful, but that is an entirely different use case.

The _expected_ behavior I listed above may not be the best user experience. Possibly having an error message when trying to apply `buildscript` blocks to `subprojects` might make more sense to a user, but this is something I don't think most users will run into.
