### ISSUE TITLE
File dependencies not being added as artifact transform dependencies

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#16698]
Android Gradle Plugin received a bug report (https://issuetracker.google.com/issues/183632445) where file based dependencies are missing from artifact transform dependencies when AGP desugars the library module with an artifact transform. This causes library source files to be desugared incorrectly. For more details, please refer to the bug linked above.

### Expected Behavior

Gradle should add file based dependencies as dependencies of artifact transform.

### Current Behavior

File dependencies are missing from artifact transform dependencies.

### Context

Here is an attempt to address this issue. https://github.com/gradle/gradle/pull/16689

**Comment by bingranl** [comment]
I am okay of closing this ticket for now because we are moving away from file dependencies IIRC

**Comment by hungvietnguyen** [comment]
We're seeing this issue being reported again: https://issuetracker.google.com/265195801.

Currently, users will need to disable dexing transforms which is not great for their build performance. It also prevents AGP from enforcing using transforms for dexing (https://issuetracker.google.com/225900051).

**Comment by bingranl** [comment]
Hung, is [File dependencies not being added as artifact transform dependencies](https://github.com/gradle/gradle/issues/16698#top) the root cause of "java.lang.NoSuchMethodError occurs when submodule access the static method in interface of dependences"? Or file dependencies is happen to use in the reporter project?

**Comment by hungvietnguyen** [comment]
Yes, I found that it is the root cause when I debugged the sample project provided at https://issuetracker.google.com/265195801#comment1.
