### ISSUE TITLE
gradle.properties JVM options not applied

### ISSUE THREAD

**Issue by sfrank-mc** [gradle/gradle#16695]
Gradle ignores the JVM options set in `gradle.properties` when creating the java command to execute.

### Expected Behavior
The generated command should be as seen when running `make get-correct-command`.
If you run `make run-correct-command` the SSL debug info is displayed correctly.

### Current Behavior
Java command generated (can be view using `make get-command`) doesn't contain the JVM args set in https://github.com/sfrank-mc/gradle-bug/blob/master/gradle.properties as documentation maintains.

If you run `make with-gradle` or `make run-command` no SSL debug info is displayed

### Context
Sometime you need to run the application setting a JVM option using -D.... for example to debug SSL handshake.

### Steps to Reproduce 
- Locally clone https://github.com/sfrank-mc/gradle-bug
- CD to folder
- Run `make with-gradle`
- Not no debug info is displayed for SSL.

### Your Environment
```
------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.7 (AdoptOpenJDK 11.0.7+10)
OS:           Mac OS X 10.15.7 x86_64
```

**Comment by bmuskalla** [comment]
@sfrank-mc Thanks for the detailed report. Luckily enough, this is not a defect but a shortcoming with your build script. The `org.gradle.jvmargs=-Djavax.net.debug=all` in your `gradle.properties` refers to the JVM arguments of your Gradle daemon (Gradle code), not the application that is launched (your code). Please ensure you provide the right JVM arguments as part of your `application` block (or `test` block if you try to see them in tests).

```
application {
    mainClass = 'ttt.App'
    applicationDefaultJvmArgs = ['-Djavax.net.debug=all']
}
```

See also docs about the [Application Plugin](https://docs.gradle.org/current/userguide/application_plugin.html#application_plugin) and the [Daemon](https://docs.gradle.org/current/userguide/build_environment.html)
