### ISSUE TITLE
Change net.gradleutil.aws.* to same key/secret as net.gradleutil.*

### ISSUE THREAD

**Issue by gradleutil-code** [gradle/gradle#16692]
Accidentally used the incorrect key/secret to push `net.gradleutil.aws.*` (the main plugin and several "sub-plugins") a while ago, could we please change that to be the same key/secret as `net.gradleutil.gradle-jte` or `net.gradleutil.gradle-conf` instead?

Sill have the old key/secret if there's an API to change it, just can't log into the portal with the old user name, as the account has since been linked to github with a different user name.

**Comment by ljacomet** [comment]
Hello, for such requests related to the plugin portal, can you please open an issue on https://github.com/gradle/plugin-portal-requests/issues ?

I will  close this as there is nothing to be done in gradle/gradle.
