### ISSUE TITLE
Wrong licensing legal advice in application plugin documentation?

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16697]
The docs at https://docs.gradle.org/current/userguide/userguide_single.html#sec:application_licensing say:
> The Gradle start scripts that are bundled with your application are licensed under the Apache 2.0 Software License. This does not affect your application, which you can license as you choose.

But isn't that majorly wrong?
If you for example release a project under GPLv2, this is not compatible with ASLv2.
So you could not ship those start scripts as long as they are licensed under ASLv2.

IANAL, but if you for example look at https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses
or https://www.apache.org/foundation/license-faq.html#GPL
I'd say that you cannot ship ASLv2 licensed start scripts with your GPLv2 program.

So the legal advice in the docs that you can freely combine those seem to be very wrong to me.

**Comment by melix** [comment]
GPL'd code can use AL2 code, but not the other way around. So it would only be a problem if the scripts were licensed under GPL.

**Comment by Vampire** [comment]
GPLv3 code can use ASLv2 code.
GPLv2 code can not use ASLv2 code as the mentioned links explain.

**Comment by Vampire** [comment]
Following that wiki page image, ASLv2 code can also not be used in MIT or BSD licensed code.

**Comment by Vampire** [comment]
That those start scripts are ASLv2 licensed also has other implications.
For example afair the typical replace tricks in build scripts needed for some use-cases are probably all illegal unless you also add a prominent statement that you changed the file.

From ASLv2 clause 4b:
> You must cause any modified files to carry prominent notices stating that You changed the files; and

**Comment by vlsi** [comment]
I wonder if dual licensing (Apache-2.0 OR CC0) of startup scripts and the wrapper jar would solve the issue.

I guess CC0 (public domain) should cover the rare cases when AL2 is not suitable for some reason.

**Comment by Vampire** [comment]
Why dual-license if one of the licenses effectively is public domain?
Who should then ever choose to use ASLv2?

**Comment by vlsi** [comment]
> Why dual-license if one of the licenses effectively is public domain?

It should not hurt though.
For instance, AL2.0 might be helpful for backward compatibility (it would probably be easier for the ones who already use the scripts under AL2.0, so they don't need to redo the paperwork for AL2->CC0 switch)

**Comment by Vampire** [comment]
Again, IANAL,
but actually if it is public domain, you should also be free to redestribute it under any license you wish,
so those people would probably not "need" to change anything, would they?

**Comment by vlsi** [comment]
Every comment here takes 10 or so minutes from several people 😢 
The current licensing is good enough for me, so I'm not much into pushing this issue any further 🤷‍♂️ 

You might be right, and it might be CC0 is just enough.
