### ISSUE TITLE
`Configuration.shouldResolveConsistentlyWith` does not force-upgrade Maven dependency to project dependency

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#16694]
### Gradle Version

7.0-rc-1 (probably also earlier)

### Steps to Reproduce

Use this sample project: [GradleBug.zip](https://github.com/gradle/gradle/files/6243925/GradleBug.zip)

This project has this setup:
```
configurations {
    configOne 
    configTwo 
    configTwo.shouldResolveConsistentlyWith(configOne) // <---- Testing this API
}

dependencies {
   configOne "org.example:lib:1.0"
   configOne project(':lib') // <---- This project publishes "org.example:lib:2.0"
   configTwo "org.example:lib:1.0"
}
```

Run ```./gradlew :app:dependencies --configuration configOne```, the following result is as expected, showing that `"org.example:lib:1.0"` can be upgraded to `project(':lib')` if they are in the same configuration:
```
configOne
+--- org.example:lib:1.0 -> project :lib
\--- project :lib
```

Run ```./gradlew :app:dependencies --configuration configTwo```, the following result is NOT as expected, as  `"org.example:lib:1.0"` in `configTwo` was not upgraded to `project(':lib')` (i.e., `configTwo.shouldResolveConsistentlyWith(configOne)` does not take effect):
```
configTwo
\--- org.example:lib:1.0
```

**Comment by liutikas** [comment]
Can we reopen and re-evaluate this bug? 

The issue is present and it continues to cause issues for Gradle plugins. The latest instance is https://youtrack.jetbrains.com/issue/KT-69571/ where Gradle does not correctly swap the dependency as expected.
