### ISSUE TITLE
Version catalog doesn't work for allprojects dependencies in a multi project gradle kotlin dsl (gradle 7.0-rc-2)

### ISSUE THREAD

**Issue by jtonic** [gradle/gradle#16708]
## Context

I've tried to integrate the version catalog, having:
- a multi project gradle kotlin kts
- gradle version: 7.0-rc-2
- java 11
- the version catalog file: gradle/libs.versions.toml (using the example from https://docs.gradle.org/7.0-rc-2/release-notes.html#new-features-and-usability-improvements)

### Expected Behavior
The gradle build task to work fine with version catalog referenced in allprojects dependencies.

### Current Behavior
It does not work when I've tried to refer the libs from version catalog in allprojects dependencies. It all worked fine in sub projects dependencies section.

### Exception
```
Extension with name 'libs' does not exist. Currently registered extension names: [ext, kotlin, kotlinTestRegistry, defaultArtifacts, sourceSets, reporting, java, javaToolchains, detekt, spotbugs]
```

### Steps to Reproduce 
A multi-project Gradle kotlin DSL based on the information in the above section `Context`.

### Your Environment

Build scan URL:

**Comment by tbroyer** [comment]
This is the same as #16634 and #16636

**Comment by ljacomet** [comment]
See https://github.com/gradle/gradle/issues/16634#issuecomment-809345790 for why this is not planned for fixing and how to make it work.

**Comment by mecoFarid** [comment]
@ljacomet That comment actually does not elaborate in any way. It just says we discourage without any reference or reasoning. I mean why there is `subprojects` and `allprojects` if it is discouraged?
