### ISSUE TITLE
Gradle daemon should retain/host details about a failed build

### ISSUE THREAD

**Issue by nlwillia** [gradle/gradle#1670]
When a build fails, the default message isn't always sufficient to diagnose the problem.

````
FAILURE: Build failed with an exception.

* What went wrong:
...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.276 secs
````

The "Try:" part of this experience, if necessary, is always a bit frustrating.  You have to modify your run command, wait for your build to rerun and then scan through a bunch of text in a terminal interface.  Ideally, this would always be instantaneous and perfectly repeatable, but depending on your project and build setup it may not be.

It would be an improvement if Gradle upon detecting a build failure would immediately start capturing detail in the daemon's memory.  At the very least, it would have the full trace.  There may be debug level detail it could capture throughout the build by default to augment the profile it could build after an error (in memory, this might not have an appreciable impact on performance).  This snapshot held in the daemon's memory could be instantly recalled with a builtin task or flag.  Even better, start a tiny embedded http server on a random port (with a self-signed cert if necessary for transport security concerns) and print a randomized url after the error message.  Many terminals let you click on links.  Now instead of having to wait and strain your eyes with the terminal output you get a nice HTML formatted view of the trace, etc. in your browser.  Make the error stand out in a way that it never will in text mode.  Link task names and stack frames to guide/DSL/API documentation.  Go a step further and make this interactive giving the user a quick way to rerun the build (if necessary) with various diagnostic flags instead of having to figure out the command line syntax and type it all out themselves.

This would be a significant boost to ergonomics and usability at one of the most potentially frustrating points in the build experience.  Some of it might be more plugin territory, but [BuildExceptionReporter](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/buildevents/BuildExceptionReporter.java) is an internal, so at lest some core support would likely be needed to make it possible.

**Comment by oehme** [comment]
What you describe is a [build scan](scans.gradle.com). Give it a try :)

**Comment by nlwillia** [comment]
Maybe if build scans were always automatically available at a private local url, but as it stands they require more steps than just rerunning with --stacktrace.  Not going to dispute the "won't fix" (no one else has voted for it), but the point was that Gradle has a persistent, local service footprint that it could utilize to help with the ergonomics at a frustrating point in the usage experience.

**Comment by oehme** [comment]
You can [automatically publish](https://docs.gradle.com/build-scan-plugin/#publishing_every_build_run) a scan for every build, as well as publish a scan for the [previous build](https://docs.gradle.com/build-scan-plugin/#publishing_on_demand) if publishing was not enabled back then. If you have activated one scan on the public instance, you will be remembered and further scans can be opened immediately. 

If you use Gradle enterprise there is no activation step at all and you have a private installation. 

Serving the same kind of information locally may eventually become an option, but our focus is on the pain points of larger enterprises who benefit more from a centralized collection than a local tool.
