### ISSUE TITLE
Dependency resolution differs in 6.8.3 and 7.0

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#16706]
Using [project_sub.zip](https://github.com/gradle/gradle/files/6251277/project_sub.zip) project and running `gw :app:assembleDAT` passes with 6.8.3 and fails with 7.0-rc-1.

Running ` gw :app:dependencyInsight --configuration debugAndroidTestCompileClasspath --dependency androidx.arch.core:core-runtime` with Gradle 6.8.3, the `project(":core-runtime")` is used because
```
- By constraint : debugAndroidTestRuntimeClasspath uses version 2.1.0
- By conflict resolution : between versions 2.2.0 and 2.1.0
```

i.e 6.8.3 is able to apply both constraints when resolving the androidTest compile classpath, and it chooses the higher version (project).

However, in `7.0-rc-1` this fails with
```
          - Cannot find a version of 'androidx.arch.core:core-runtime' that satisfies the version constraints:
               Dependency path 'ProjectSubTest:app:unspecified' --> 'androidx.arch.core:core-runtime:2.1.0'
               Constraint path 'ProjectSubTest:app:unspecified' --> 'androidx.arch.core:core-runtime:{strictly 2.1.0}' because of the following reason: debugAndroidTestRuntimeClasspath uses version 2.1.0
               Dependency path 'ProjectSubTest:app:unspecified' --> 'project :core-runtime'
```

While 7.0-rc-1 behavior looks good (strict constrains should really be strict), I want to make sure that this change is intentional and documented in the release notes.

**Comment by melix** [comment]
I'm going to take a look into this now, but I don't remember any _intentional_ change in 7.0 in terms of dependency management in this area. It might be a side effect of removal of some configurations.

**Comment by melix** [comment]
So the new behavior definitely seems correct, but I'm having hard times figuring out what caused the old behavior to be fixed. This seems to be specific to project substitutions.
