### ISSUE TITLE
Custom jars in default configuration are not triggered for build for dependent projects

### ISSUE THREAD

**Issue by ilya-g** [gradle/gradle#1671]
Turns out that since gradle 3.4 the following two ways of specifying project dependency produce different results:

```
        compile project(':module-a')
        compile project(path: ':module-a', configuration: 'default')
```

In case if I disable standard `Jar` task in `module-a` and use some `customJar(type: Jar)` task to produce an artifact (which I include in the default artifact configuration), that customJar task is not triggered when starting clean build of `module-b`.

### Expected Behavior
Both ways of specifying project dependency triggers all artifacts from the default configuration to be built.

### Context
I'm doing some custom jar transformations, such as relocating packages, proguarding etc, so I need to disable standard jar task and use my custom instead.

### Steps to Reproduce (for bugs)
https://github.com/ilya-g/gradle-issue-1671
https://scans.gradle.com/s/yrgwbhlxr5lsq#summary

**Comment by oehme** [comment]
The `default` configuration is no longer used for Java projects, please use `apiElements` or `runtimeElements` as appropriate.

Also, your customJar task needs a classifier, otherwise it will override the original jar, breaking incremental builds.

**Comment by ilya-g** [comment]
>The default configuration is no longer used for Java projects, please use apiElements or runtimeElements as appropriate.

The documentation doesn't state that, see https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management

> Also, your customJar task needs a classifier, otherwise it will override the original jar, breaking incremental builds.

No, the `customJar` artifact doesn't need a classifer, because I want to produce an artifact that would otherwise be produced by the standard Jar task. In order not to overwrite the latter I've disabled the standard Jar task (`jar.enabled false`)
