### ISSUE TITLE
Gradle endlessly starts OpenJDK Platform Binaries

### ISSUE THREAD

**Issue by Sunney-X** [gradle/gradle#16722]
### Expected Behavior

Running Gradle task 'assembleDebug'...  to finish
### Current Behavior

It just spawns OpenJDK Platform Binaries until it takes up all the RAM
### Context

I'm trying to start my application. The issue occurs on a newly created project on Android Studio + A newly created Flutter app on VS Code as well
### Steps to Reproduce 

The issue occurs on a newly installed Windows 10 with default settings
### Your Environment

Build scan URL:

After completely taking up the RAM the following error gets printed

## Error:
```                                                
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.7/userguide/gradle_daemon.html
Process command line: E:\Programs\Android Studio\jre\bin\java.exe -Xmx1536M -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\sunny\.gradle\wrapper\dists\gradle-6.7-all\cuy9mc7upwgwgeb72wkcrupxe\gradle-6.7\lib\gradle-launcher-6.7.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.7
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for object heap


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 

* Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done            
```

Downgrading Gradle to 6.0 and Gradle Build Tools to 3.6.0 Solved the issue

**Comment by bmuskalla** [comment]
Would you please be able to share the error with the debug options enabled as suggested in the output?

```
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
```

See also [Configure the JVM memory](https://docs.gradle.org/6.7/userguide/build_environment.html#sec:configuring_jvm_memory) to learn about increasing the memory for your builds. Depending on your build scripts, this may be necessary.

If the problem persists, it would be great to get [a heap dump ](https://dzone.com/articles/how-to-capture-java-heap-dumps-7-options) to see if there are any leaks.

Also, have you tried running your build using a more recent version (e.g. Gradle 7.0)?

**Comment by bmuskalla** [comment]
Closing for now. @Sunney-X please let me know if you got more information and we can reopen
