### ISSUE TITLE
Log overflow type when receiving overflow file system watching event

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#16723]
Here we are not logging the type, which can tell us whether it was the OS or our internal queue that overflew:

https://github.com/gradle/gradle/blob/679e14442a12af29b45cb1568960d5e2fdb9330b/subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/DefaultFileWatcherRegistry.java#L96-L107

It's also a bit confusing to re-use the `INVALIDATED` event type that might lead someone to think that this has something to do with a change to the watched root on macOS. We probably should handle this without mentioning `INVALIDATED`.

---
cc: @gradle/execution

**Comment by wolfs** [comment]
This has been fixed.
