### ISSUE TITLE
Build init plugin should support creating Kotlin applications and libraries

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#1673]
The [Build init plugin](https://docs.gradle.org/current/userguide/build_init_plugin.html) should support creating app and library template projects for the [Kotlin language](https://kotlinlang.org/).

### Expected Behavior

These should work to create Kotlin template projects:

    gradle init --type kotlin-application
    gradle init --type kotlin-library

### Current Behavior

Currently, the `kotlin-application` and `kotlin-library` types are not implemented.

### Context

Getting started with Kotlin would be easier if Gradle provided these templates, esp. as depending on the Gradle / Kotlin version the plugin needs to be applied differently.

**Comment by pioterj** [comment]
Thanks for opening the issue, @sschuberth. 

I think it would make most sense for the maintainers of Kotlin Gradle Plugin to maintain also the build init template. 

3rd party templates are currently not possible. I opened an issue for it: https://github.com/gradle/gradle/issues/1686.

**Comment by sschuberth** [comment]
Thanks @pioterj. Should we probably also merge this issue into https://github.com/gradle/gradle/issues/1685, and adjust its description to contain Kotlin?

**Comment by adammurdoch** [comment]
Added in https://github.com/gradle/gradle/pull/6489.

**Comment by sschuberth** [comment]
Thanks @adammurdoch for implementing this. I just tested this as part of the 5.0 RC1 binary distribution, and I'm wondering why the *kotlin-library* template does not apply the `java-library` plugin (to benefit from the `api` vs `implementation` separation) like the *java-library* template does. Is that on purpose?
