### ISSUE TITLE
End-of-build summary on console should report tasks from included builds

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#16743]
Looking at this build scan of the Gradle build: https://ge.gradle.org/s/kzkth4dgjfyfa/console-log#L989-L990

The console says:

```text
BUILD SUCCESSFUL in 1m 17s	
433 actionable tasks: 1 executed, 432 up-to-date
```

But if on the performance tab of the scan the information is different:

![image](https://user-images.githubusercontent.com/495366/113980404-b82cab80-9846-11eb-8715-0589d1f807f6.png)

The difference is because of included build like `:build-logic` are not reported on the console. So while the build scan shows everything happening, on the console we log only the main build’s numbers. Let's fix this and make sure scans and console logs display matching information.

---
cc: @gradle/execution

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/17017
