### ISSUE TITLE
Repository definitions in pluginManagement of injected settings plugins of source dependency are not available early enough

### ISSUE THREAD

**Issue by elmart-devo** [gradle/gradle#16752]
I have a project which has a source dependency on an external project.
The external project doesn't have a gradle build, so I inject one.
It works fine, until I pretend to use some dependency in the injected plugin.
The dependency is an internal one, not present in public repos like Gradle Plugin Portal.
So I add a repository definition to the injected plugin project.

### Expected Behavior
Gradle honours the repo definition, finds my dependency, and I can use it in the injected plugin code.

### Current Behavior
Gradle ignores the repo definition, and only searches in Gradle Plugin Portal. Any dependency not present there is not found.

### Context

I am working on a project to create Java JNI binding for a C++ library.
Having a source dependency on the C++ library, and an injected plugin adapting the cmake build to a gradle build seemed an awesomely clean way of having everything integrated in one build, with proper up-to-date checks and ease to change the external library version.

It also seemed factible, from what I saw at  https://github.com/gradle/native-samples/tree/master/cpp/cmake-library.
I have it working, in fact, but when I try to use any kind of internal dependency in the injected plugin, the show stops.
That ruins the possibility of extracting the cmake integration logic to a plugin residing in corporate repos.

### Steps to Reproduce 
I have setup a minimal project to reproduce the issue here:
https://github.com/elmart-devo/gradleissue
README contains instructions to reproduce.

### Your Environment
MacOS 11.2.3
Java 11

I can't perform a build scan, as it is not supported when source dependencies are used.

**Comment by jjohannes** [comment]
I think this is not a problem with source dependencies directly. But the confusion that you need to declare the repository twice if you build and use custom plugins that require additional repos:

1. You need to declare it in the plugin build to **build** the plugin (that's what you do)
2. Your need to declare it in `pluginManagement { ... }` of the build to **use** the plugin

I am not sure how this plays into source dependencies, but in you reproducer you also do an "includeBuild" and the issue is with that. 

You should add this to the settings Gradle:

```
pluginManagement {
  repositories {
    maven {
      name "atlassian-public"
      url "https://packages.atlassian.com/content/repositories/atlassian-public/"
    }
  }
}
```

If there is another issue that was just hidden by this, please update the reproducer and clarify. I will reopen the issue in that case.

**Comment by elmart-devo** [comment]
I updated the reproducer as you suggested, adding the `pluginManagement` section in every gradle settings (both main project, plugins subproject, and even the injected settings), but it continues to fail the same. The only repo that is searched seems to be Gradle Plugin Portal.

I can also confirm it fails the same if `pluginManagement` section is configured globally in my `init.gradle`, as that is in fact my normal setup for corporate repos, and the one I had when this first hit me.

**Comment by jjohannes** [comment]
In your reproducer there is a type on the dependency ('.' at the end)

If I fix it:
```
-  implementation "com.atlassian.activeobjects:activeobjects-confluence-spi:3.3.1."
+  implementation "com.atlassian.activeobjects:activeobjects-confluence-spi:3.3.1"
```

And then add this to the root "settings.gradle":

```
pluginManagement {
 repositories {
  maven {
    name "atlassian-public"
    url "https://packages.atlassian.com/content/repositories/atlassian-public/"
  }
  gradlePluginPortal()
 }
}
```

I get a different error -- `Could not find com.atlassian.pom:base-pom:5.0.26.` -- but the repo is definitely used.

**Comment by jjohannes** [comment]
But I see now that the error message is not mentioning the repository which is weird. Can you fix the dependency declaration, and investigate why the base-pom is not found and clarify if there still is an issue (apart from the error message being wrong/confusing)?

**Comment by elmart-devo** [comment]
I'm very sorry about the typo. But it's not going to be the issue here, as I originally had the problem with another dependency which was well written and that loads ok in other parts of the same project.
I confirm once I correct the type, I get the same error as you.
I will continue investigating and update the reproducer accordingly.

**Comment by elmart-devo** [comment]
I have continued to investigate this and definitely there is something weird. It works when using public repos, but doesn't work when using private ones. Let me explain:

I have updated the reproducer to use another public repo (https://repo.spring.io/plugins-release/) and another dependency (cglib:cglib-nodep:3.0).
Then, when you run the build, it works but you can see this in the logs:
```
Downloading https://plugins.gradle.org/m2/cglib/cglib-nodep/3.0/cglib-nodep-3.0.pom to /private/var/folders/c6/zrvrw04d4kn9dt67grlz1kpw0000gn/T/gradle_download21564516027956710bin
Downloading https://plugins.gradle.org/m2/cglib/cglib-nodep/3.0/cglib-nodep-3.0.jar to /private/var/folders/c6/zrvrw04d4kn9dt67grlz1kpw0000gn/T/gradle_download2337662221994112511bin
Downloading https://repo.spring.io/plugins-release/cglib/cglib-nodep/3.0/cglib-nodep-3.0.pom to /private/var/folders/c6/zrvrw04d4kn9dt67grlz1kpw0000gn/T/gradle_download4877289696935741463bin
```
So, it seems it is using Gradle Plugin Portal (https://plugins.gradle.org/m2) first, instead of the specified repo.
Now here comes the weird thing:
The moment I change the repo definition to a private corporate one, and the dependency to one that only exists there (this is, that is not in Gradle Plugin Portal or any other public repo), then it doesn't work anymore, and I get the following error:
```
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/devo/foundations/devo-foundations-jnice/0.1.0-SNAPSHOT/maven-metadata.xml]
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/devo/foundations/devo-foundations-jnice/0.1.0-SNAPSHOT/devo-foundations-jnice-0.1.0-SNAPSHOT.pom]

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
Could not find com.devo.foundations:devo-foundations-jnice:0.1.0-SNAPSHOT.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/com/devo/foundations/devo-foundations-jnice/0.1.0-SNAPSHOT/maven-metadata.xml
    - https://plugins.gradle.org/m2/com/devo/foundations/devo-foundations-jnice/0.1.0-SNAPSHOT/devo-foundations-jnice-0.1.0-SNAPSHOT.pom
 ```
So, what it seems to me, is that Gradle Plugin Portal is being used always under the hoods, and when you succeed with another public repo, it's because that public repo contents is also present in Gradle Plugin Portal (directly or via delegation to jcenter).
I have tried to find a public repo containing a package that is not under Gradle Plugin Portal or jcenter, but I haven't been able to. So I can't prove that. But if you change the repo definition to a private one and the dep to a private package that is only there, it should fail for you too.

Please give it a try.

**Comment by elmart-devo** [comment]
I have downloaded gradle sources (v6.8.3), to try to do some debugging.
I'm placing breakpoints in ModuleVersionNotFoundException constructors, as that's the exception I get as the root cause using --stacktrace in the command line.
The exception gets fired and the debugger stops.
I then check that the exception effectively refers to the package residing on my private repo.
A couple of frames above the exception I find that the `RepositoryChainComponentMetadataResolver` object being used, only has one repository defined, which happens to be Gradle Plugin Portal.
<img width="611" alt="Screen Shot 2021-04-15 at 09 58 16" src="https://user-images.githubusercontent.com/54622299/114836289-c93f6480-9dd2-11eb-9a3e-ffa79b6e8f73.png">
Which seems to confirm my suspicions that for some reason only Gradle Plugin Portal is being used for injected plugins.
From what I can understand in the stack frame, all this happens while resolving the injected project (:dummylib in this case) default configuration.
Of course, I know nothing of this codebase and could be very wrong. But just in case it helps.

I attach full screenshot below.

<img width="2032" alt="Screen Shot 2021-04-15 at 09 54 16" src="https://user-images.githubusercontent.com/54622299/114837183-b9745000-9dd3-11eb-839d-f1a68dff2c66.png">

So, could you please try to see if you reproduce the problem once using a private repo/dep?

**Comment by jjohannes** [comment]
@elmart-devo Thanks for the additional information. I now understand the problem. I don't know all the details of the plugin injection mechanism in source dependencies. But as far as I know you can only inject _Settings_ plugins. The dependencies are not actually needed for the "Settings" part (I assume) but for the root project part of the plugin (which would usually be the configuration in "build.gradle"). Now the settings plugins are injected very early. And since the repositories are only added by the plugin itself, they are not yet available when the classpath of the plugin is resolved. But since everything is in that one plugin, we have an ordering issue. You can't add more repositories, before resolving the classpath of the actual build.

In "normal" Gradle, this is solved by the separation of "settings.gradle" and "build.gradle" in the lifecycle. Looks like this is missing in the injection mechanism.

I can't say when we will be able to do something on this. The injection mechanism is quite premature as this shows. Unfortunately, the source dependencies feature is nothing that is actively worked on right now. But I will keep this issue open so that it may be picked up at some point in the future.

The only **workaround** I can think of is that you actually add a "settings.gradle" to the cloned repo with the `pluginManagement {}` block. I guess you could automate this with some code in settings, that adds such a file to folders in `.gradle/vcs-1/...`. You would have to figure the right moment to do so.

**Comment by Vampire** [comment]
> I have tried to find a public repo containing a package that is not under Gradle Plugin Portal or jcenter, but I haven't been able to. So I can't prove that

Actually I told you in the forum thread how to find a good example for reproducing the issue. ;-)
If you use `cglib:cglib-nodep:3.0`, even if it is from a different public repo, that's not good for showing the issue, as Plugin Portal will delegate to JCenter which will delegate to Maven Central, so the dependency will be found.
I figured one out for you quickly, make your reproducer with `com.hortonworks.beacon:beacon-cli:1.0.0.1.5.2.0-38` in `https://repo.hortonworks.com/content/repositories/releases` and you get the expected error that it cannot resolve it from plugin portal.

**Comment by elmart-devo** [comment]
Just commenting to keep this open.
