### ISSUE TITLE
gradle test kit fills up /tmp with per user .gradle-test-kit folders

### ISSUE THREAD

**Issue by martinda** [gradle/gradle#1675]
Gradle creates a folder under `/tmp` for the Gradle Test Kit (the file is actually `/tmp/.gradle-test-kit-$USER`) and this fills the disk over time.

### Expected Behavior
Gradle should not put any disk at risk of a disk full event.

### Current Behavior
When running tests that use the Grade Test Kit, a folder called `/tmp/.gradle-test-kit-$USER` is created. Gradle never erases this file, and it keeps growing over time, until the disk is full.

### Context
We encountered a disk full situation on a network host. Multiple users were affected and unable to work because `/tmp` had become full. We identified that the largest file on `/tmp` was a `.gradle-test-kit` file which kept growing and growing over the course of one month.

### Steps to Reproduce (for bugs)
Run the Gradle Test Kit and observe the `/tmp/.gradle-test-kit-$USER` folder consume more and more disk space at each run.

### Your Environment
Linux, multiple users per host. The capacity of `/tmp` is irrelevant, because we can make `/tmp` bigger and postpone the problem, or we could shorten the data retention policy on `/tmp` and this only postpones the problem. The fact is that Gradle assumes infinite storage on `/tmp`, which IMO is wrong. We tried this with Gradle 3.4.1.

**Comment by martinda** [comment]
This was found on line 169 of [testing-user-build-logic.md](https://searchcode.com/file/94566778/design-docs/testing-user-build-logic.md).

> There is no attempt to auto delete the .gradle-test-kit dir after test execution. The management of the directory to run in is not in scope, and will likely be handled by other mechanisms in the future (e.g. JUnit rule @TemporaryFolder).

**Comment by eskatos** [comment]
Hi Martin, thanks for the detailed report!

As you found out, the Test Kit temporary directory is not managed. Would you be interested in working on a design for providing that temporary directory to tests for lifecycle and assertion?

That temporary directory is actually set to `"${System.properties['java.io.tmpdir']}/.gradle-test-kit-$USER"`. To work around this limitation you could set the `java.io.tmpdir` system property to a known path, e.g.:

```groovy
yourTestTask {
  systemProperty 'java.io.tmpdir', file("$buildDir/tmp/${yourTestTask.name}-test-kit")
}
```

**Comment by eskatos** [comment]
Quoting myself:
> As you found out, the Test Kit temporary directory is not managed. Would you be interested in working on a design for providing that temporary directory to tests for lifecycle and assertion?

Actually, I don't see the need to get that directory into tests (e.g. JUnit @TemporaryFolder rule). It's a temporary directory so we should not need it for assertion purpose. But it should definitely be cleaned at some point.

Test Kit sets the ["gradle user home" to be inside that temporary directory](https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/DefaultGradleRunner.java#L272). So, it holds Gradle caches. AFAIU deleting it after each test (run/suite/task) would mean re-downloading everything each time.

@bmuschko could you please shed some light upon us? 😃

**Comment by martinda** [comment]
The workaround proposed works. I can see that the test kit tmp folder grows at each run. According to the `du -s -h` command, it started at 2.9M, then it grew to 4.1M the second time, and to 5.3M the third time.

**Comment by martinda** [comment]
Another workaround is:
```
test {
    systemProperty 'org.gradle.testkit.dir', file("${buildDir}/tmp/test-kit")
}
```

**Comment by bmuschko** [comment]
The idea behind the "custom" Gradle user home is the fact that you want to have an isolated environment just for testing. It shouldn't pick up the settings configured in your usual Gradle user home directory. If you really wanted you could reuse the standard Gradle home directory but I wouldn't necessarily recommend it.

There's currently no clean up built-in. Generally speaking that's an issue we have with the Gradle cache per se. You can see a related issues in https://github.com/gradle/gradle/issues/1586 and https://github.com/gradle/gradle/issues/1085. It would be interesting to know what exactly is growing in your tmp TestKit directory. Could you provide information on that?

**Comment by martinda** [comment]
@bmuschko , I hope this helps:
```
$ diff -r test-kit-1 build/tmp/test-kit
Binary files test-kit-1/caches/3.4.1/fileHashes/fileHashes.bin and build/tmp/test-kit/caches/3.4.1/fileHashes/fileHashes.bin differ
Binary files test-kit-1/caches/3.4.1/fileHashes/fileHashes.lock and build/tmp/test-kit/caches/3.4.1/fileHashes/fileHashes.lock differ
Only in build/tmp/test-kit/caches/3.4.1/scripts: 9etvihbxie690dsk0584h0qf1
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_15nepignl4a6tn00mjsjt7fr5
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_21gussmucyqm70vdbomkmvq8d
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_6tut5clg4say5h0od0mglddpy
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_707xdju0ybqye4zxctp6f3jrr
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_7b6kx0ghouqdwc1g9rmxv5ddn
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_7lruvr7binubflyp9ut7xz8cp
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_90x6z6091kyfsset701w6kfsz
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_9adrs6hhyfzp4z316g1c6rfi7
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_b5j18726gc82jtqetvjyc6pdm
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_e4imnrjjkri68ojq1ulrqskwh
Only in build/tmp/test-kit/caches/3.4.1/scripts-remapped: build_eh31u9inc8fsrccwerb71uj81
Only in build/tmp/test-kit/test-kit-daemon/3.4.1: daemon-19261.out.log
Binary files test-kit-1/test-kit-daemon/3.4.1/registry.bin and build/tmp/test-kit/test-kit-daemon/3.4.1/registry.bin differ
Binary files test-kit-1/test-kit-daemon/3.4.1/registry.bin.lock and build/tmp/test-kit/test-kit-daemon/3.4.1/registry.bin.lock differ
```
Looks like new directories get created.

**Comment by bmuschko** [comment]
I'd be more interested in the diff of files between two build invocations. Could you provide that instead? My guess is that the # of `build/tmp/test-kit/caches/3.4.1/scripts-remapped` directories will increase (which is the same issue as https://github.com/gradle/gradle/issues/1586) and the size of the `daemon-19261.out.log` which would be expected to be honest.

**Comment by martinda** [comment]
I am not sure what files you mean when you say "the diff of files between two build invocations", but there are no changes in the sources between the two calls to `./gradlew test`.

**Comment by bmuschko** [comment]
I am talking about the diff in `build/tmp/test-kit` between two build invocations that keep growing on your machine over time. What files/directories are increasing in size/number specifically?

**Comment by martinda** [comment]
Here is the list of what increases:
* The number of directories under `build/tmp/test-kit/caches/3.4.1/scripts-remapped`. Under this directory tree, files are being added at each run, but files from the previous runs are not changed.
* The number of directories under `build/tmp/test-kit/caches/3.4.1/scripts`. Ditto: files are added, but old files are not changed.
* The size of `build/tmp/test-kit/caches/3.4.1/fileHashes/fileHashes.bin` increases by a few hundred bytes at each run.

The size of the `daemon-*.log` files do not change, but a new one is created at each run (which is logical).

**Comment by martinda** [comment]
I ran the same experiment with Gradle 3.5 and I am noticing a major improvement. The growth between test runs is now limited to a single temporary file called `build/tmp/test/jar_extract_<random_number>_tmp` which for me is quite small at about 3 kilobytes.

**Comment by chuckmarcotte** [comment]
I am experiencing /tmp running out of inodes before running out of disk space.
I am using the code below as a workaround:
`
```
test {
    doLast {
        // Cleanup the Gradle test kit temporary files
        java.nio.file.Path deletePath = java.nio.file.Paths.get(System.getProperty('java.io.tmpdir') +'/.gradle-test-kit-' + System.getProperty('user.name') + '/caches')
        def mapPathToFile = { path -> path.toFile() }
        def deleteFile = { file -> file.delete() }
        logger.quiet("\nCleaning up Gradle test kit temporary files.  Deleting files in path: " + deletePath.toString() + "\n")
        java.nio.file.Files.walk(deletePath)
                .sorted(Comparator.reverseOrder())
                .map(mapPathToFile)
                .forEach(deleteFile)
    }
}

````

**Comment by rkrisztian** [comment]
@chuckmarcotte, doesn't the following work?

```groovy
test {
    doLast {
        delete "${System.properties.'java.io.tmpdir'}/.gradle-test-kit-${System.properties.'user.name'}/caches"
    }
}
```
