### ISSUE TITLE
Improvements for the single-page documentation.

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16760]
The single-page documentation is missing content from the multi-page version.
I almost exclusively use the single-page version and thus did not find any information about the `project-reports` plugin as it is missing.
There are three changes I'd like to suggest:

1. Add the `project-reports` doku and any other non-intentionally missing pages to the single-page version
2. Add some test that makes sure that only intentional pages are left out and not just forgotten
3. Add and enforce a title convention for plugin chapters like `The <name> Plugin`
   ![grafik](https://user-images.githubusercontent.com/325196/114170644-847b7f80-9933-11eb-9e87-a23b4bd41d09.png)

**Comment by Vampire** [comment]
https://docs.gradle.org/7.0/userguide/implementing_gradle_plugins.html and similar pages are also missing

**Comment by Vampire** [comment]
https://docs.gradle.org/current/userguide/build_services.html too

**Comment by Vampire** [comment]
https://docs.gradle.org/6.8.3/userguide/resolution_strategy_tuning.html too

**Comment by Vampire** [comment]
https://docs.gradle.org/7.1/userguide/upgrading_version_7.html too

**Comment by Vampire** [comment]
https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html too

**Comment by Vampire** [comment]
This also does not only affect the single-page html documentation of course, but also the PDF version of the user guide.

**Comment by Vampire** [comment]
@lkasso How about splitting the PDF and HTML single-page docs then?
I guess for the HTML you would not have that size problem.
For me that would be fine, as I mostly not use the PDF version anyway.
Would be sad if the HTML single-page docs cannot be extended just because a PDF size limit is reached.

**Comment by lkasso** [comment]
@Vampire, this is likely something I will do in the future but it's much lower priority than many other improvements I am planning for the docs.
