### ISSUE TITLE
Allow for included modules with mirrored names 

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [gradle/gradle#16778]
Hey 👋 checking out Gradle 7 and am a big fan so far.  One thing that is _fantastic_ is the type safe project accessors.  However, I think there is a restriction that is a little short sighted, and that I think will cause many backwards compatibility issues.  

Currently, the generated sources seem unable to handle the case where the `rootProject.name` is equal to the name of an included project.  A pretty standard scenario is to have a library repository, with the actual library as a child module.  

For example, I am starting work on a library named `kompendium`.  I want to have (at least) two child projects, one for the actual library, also (hopefully 😄) named `kompendium` and a testing bench named `playground`.  So my `settings.gradle.kts` would look something like this 

```kotlin
rootProject.name = "kompendium"
include("kompendium")
include("playground")

// Feature Previews
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
enableFeaturePreview("VERSION_CATALOGS")
``` 

Unfortunately, this spits out the following error on build

```
org.gradle.api.internal.catalog.GeneratedClassCompilationException: Unable to compile generated sources:
  - File RootProjectAccessor.java, line: 29, method getKompendium() is already defined in class org.gradle.accessors.dm.RootProjectAccessor
> Unable to compile generated sources:
    - File RootProjectAccessor.java, line: 29, method getKompendium() is already defined in class org.gradle.accessors.dm.RootProjectAccessor
``` 

Is it the end of the world? Not by a long shot, you can do something as simple as `project("kompendium").name = "lib"` and you are on your merry way, _but_ it feels like a workaround more than a solution.

### Expected Behavior

Projects and child modules should be allowed to have the same name, without the need for workarounds like renaming. 

### Current Behavior

Currently this is not possible

### Context

Hopefully this is enough context 😸

**Comment by mateuszkwiecinski** [comment]
it looks like a duplicate of https://github.com/gradle/gradle/issues/16608

**Comment by rgbrizzlehizzle** [comment]
indeed 👍
