### ISSUE TITLE
Add option to disable Kotlin version warnings in kotlin-dsl

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#16779]
### Expected Behavior

If using a custom kotlin version, it would be nice to disable warnings until #16345 is resolved

### Current Behavior

With Gradle 7, using Kotlin 1.4.32 results in this warning:

```
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.31` that might work differently than in the requested version `1.4.32`.
```

### Context

This is quite noisy in builds, especially when we know it's not an issue on our end.

**Comment by ZacSweers** [comment]
It looks like Kotlin offers a `-Xsuppress-version-warnings` compiler argument that may help with this, but Gradle needs to pass it in with its invocation of kotlinc.

https://github.com/JetBrains/kotlin/blob/92d200e093c693b3c06e53a39e0b0973b84c7ec5/compiler/cli/cli-common/src/org/jetbrains/kotlin/cli/common/arguments/CommonCompilerArguments.kt#L355-L359

**Comment by Tapchicoma** [comment]
@ZacSweers with Kotlin `1.5.10` release Gradle should not produce this warning. Could you verify it? (though some 3rd party plugins could still bring stdlib dependency)

**Comment by andreimarcut** [comment]
It's still happening on a Gradle configuration version of 7.0.0 and \`kotlin-dsl\` with kotlin-gradle-plugin version 1.5.10
```
> Configure project :
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.4.31` that might work differently than in the requested version `1.5.10`.

BUILD SUCCESSFUL in 982ms
```

**Comment by CMingTseng** [comment]
The Compose Multiplatform, by JetBrains  also 

can run this demo 

https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp

**Comment by ZacSweers** [comment]
Closing due to lack of feedback from Gradle

**Comment by IGR2014** [comment]
Gradle 7.4.1 - can confirm this while building my own plugin which uses `kotlin-dsl`.
Kotlin version set as 1.6.10

Got this:
```
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.5.31` that might work differently than in the requested version `1.6.10`.
```

**Comment by ljacomet** [comment]
Other issues are asking for similar things, like #22647 which is still open. I am marking this one as a duplicate, even though it was filed before.
