### ISSUE TITLE
Broken link in `Copy` error message when upgrading to Gradle 7.0

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#16785]
Upgrading a project to Gradle 7 yields the following error message: 

```
Entry META-INF/gradle-plugins/com.osacky.fulladle.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0/dsl/org.gradle.api.file.CopySpec.html#org.gradle.api.file.CopySpec:duplicatesStrategy for details. 
```

The error message has a broken link.

It should probably be: https://docs.gradle.org/7.0/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy
or
https://docs.gradle.org/7.0/javadoc/org/gradle/api/file/CopySpec.html#setDuplicatesStrategy-org.gradle.api.file.DuplicatesStrategy-

Here is a build scan of the error:
https://scans.gradle.com/s/gbgserqxkezai/console-log#L9

Steps to reproduce:
Check out: https://github.com/runningcode/fladle
Run `./gradlew wrapper --gradle-version 7.0`

**Comment by big-guy** [comment]
@gradle/execution could you guys fix this one?
