### ISSUE TITLE
Allow iterating over dependencies declared in a version catalog

### ISSUE THREAD

**Issue by lwasyl** [gradle/gradle#16784]
Context: in a modular project, I'd like to keep all the dependencies versions consistent across modules. This can be done using `java-platform` plugin or by manipulating resolution strategy manually. In order to do that, we need to know which dependency should use which version exactly.

When using version catalogs, the documentation suggests the following for pinning specific versions using a platform:
```groovy
plugins {
    id 'java-platform'
}

dependencies {
    constraints {
        api(libs.mylib)
    }
}
```

It would be great if I could iterate over all dependencies in a version catalog and for each of them add a constraint. This would essentially make version catalog part of dependency resolution, but as a very explicit opt-in.

**Comment by elect86** [comment]
.. or push this even further and simply do something like 

```
dependencies {
    constraints {
        api(catalog("my:catalog:0.0.1"))
    }
}
```

**Comment by RaffaeleSgarro** [comment]
So how can we use the catalog in the constraints of a platform?

**Comment by ljacomet** [comment]
You have to add a platform entry for each catalog entry. The PR that fixed this issue allowed to do that by leveraging the [type unsafe API](https://docs.gradle.org/current/userguide/platforms.html#sub:type-unsafe-access-to-catalog).

You would do something like:
```
plugins {
    id 'java-platform'
}

def versionCatalog = extensions.getByType(VersionCatalogsExtension).named("libs") // or your catalog name
dependencies {
    constraints {
        versionCatalog.libraryAliases.each { alias ->
            api(versionCatalog.findLibrary(alias).get())
        }
    }
}
```

**Comment by RaffaeleSgarro** [comment]
Thank you. We already do that and thought there were a more idiomatic way because we don't like programming (loops, conditions) in build scripts but anyway it works.
