### ISSUE TITLE
Enable deprecation logging for deprecated methods currently used by Kotlin plugin

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#16783]
Kotlin plugin uses the following methods that are being deprecated:
- `AbstractCompile.getDestinationDir()`
- `AbstractArchiveTask.setAppendix()` -> `archiveAppendix`
- `AbstractArchiveTask.setClassifier()` -> `archiveClassifier`

When a new version of Kotlin plugin is released, update the plugin in Gradle, update the tests and reevaluate whether deprecation logging can be enabled for those methods.

This requires version 1.5.20 of the Kotlin plugin.

**Comment by rieske** [comment]
For reference: https://youtrack.jetbrains.com/issue/KT-46019

**Comment by jjohannes** [comment]
If the corresponding Koltin Plugin release does not happen before the 7.1 release branching, please move the milestone to `7.2 RC1`.

**Comment by rieske** [comment]
Kotlin 1.5 is out: https://github.com/JetBrains/kotlin/releases/tag/v1.5.0

**Comment by big-guy** [comment]
blocked by #17465
