### ISSUE TITLE
Enable deprecation logging for deprecated methods currently used by Android plugin

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#16782]
Android plugin uses the following methods that are being deprecated:
- `DependencySubstitutions.Substitution.with`
- `AbstractCompile.setDestinationDir(Provider<File>)`
- `CompileOptions.setAnnotationProcessorGeneratedSourcesDirectory(File)`

When a new version of Android plugin is released, update the tests and reevaluate whether deprecation logging can be enabled for those methods.

This requires 7.0.0 line of the Android plugin.

**Comment by jjohannes** [comment]
If the corresponding Android Plugin release does not happen before the 7.1 release branching, please move the milestone to `7.2 RC1`.

**Comment by tresat** [comment]
CompileOptions removal: https://github.com/gradle/gradle/pull/17105
AbstractCompile removal: https://github.com/gradle/gradle/pull/21660
DependencySubstitutions removal: https://github.com/gradle/gradle/issues/21661

As these deprecated methods are already removed/being addressed by other 8.0 issues, I'm closing this issue.
