### ISSUE TITLE
Minor grammar issue

### ISSUE THREAD

**Issue by jvasileff** [gradle/gradle#16798]
The text linked below (`Jvm.java` line 195) should have "can be *run*", not "can be *ran*".

https://github.com/gradle/gradle/blob/ade02d02f35609082e8c3a17a688d7af84b5baa6/subprojects/base-services/src/main/java/org/gradle/internal/jvm/Jvm.java#L195

**Comment by jjohannes** [comment]
Thanks @jvasileff good catch. Fixed it directly. Only took us 10 years. :)
