### ISSUE TITLE
VisitableURLClassLoader leak.

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#16797]
After upgrading to 7.0, I see some class loader leaks. In particular, VisitableURLClassLoader is leaking each time the classpath is updated. 

I have traced down some of the references to the leaked classloader to 
```
subprojects/core/src/main/java/org/gradle/cache/internal/DefaultCrossBuildInMemoryCacheFactory.java
```
in particular, line 92 
```
retainValuesFromCurrentSession(valuesForThisSession.values());
```
where constructor references are cached across builds. seems like an optimization that might be causing more harm than good, or at least that cache should be invalidated as soon as a new build starts and the previous cached values are not usable. 

In any case, after removing that caching, it removed some of the incoming references to the leaked class loader but not all.
The next set of references are coming from contextClassLoader on "jar transforms" threads. 

The weird thing is that `ManagedExecutorImpl::stop` is called correctly and some of the threads are indeed stopped but not all of them: 
I can see `org.gradle.internal.concurrent.ThreadFactoryImpl$1` still being reachable because they are still in the `ManagedExecutorImpl` workers list.

I will continue investigating why these threads are still dangling but I would appreciate any advices/hints as I don't know this code too well.

**Comment by jdochez** [comment]
Ok I have traced why the "jar transforms" threads are still using the VisitableURLClassLoader as a context class loader. 

1. the "jar transforms" executor is a daemon based service meaning it is not shutdown until the daemon shuts down.
2. the thread created by the "jar transforms" executor service inherit the parent thread context class loader at the time of creation, so when the threads are created, the context class loader is set to the current build script class loader
3. when the build finishes, all executor services shutdown but not the "jar transforms".
4. until the threads are used in a different build, they will continue to hold on to one the previous build class loaders.

after a small fix to remedy to the above situation, I cannot see any incoming references to the classloaders so good news. However, I have not verified the behavior because the daemon is aggressively killed (due to metadata near exhaustion before the VM has the opportunity to remove all weak/soft references objects like those classloader instances. Is there a way to disable the health monitoring of the Gradle daemon ?

**Comment by xaviarias** [comment]
Hey @jdochez following your [comment](https://github.com/gradle/gradle/pull/17385#issuecomment-857789223), did you have the chance to check if the issue is resolved?

**Comment by jbartok** [comment]
Pls. open a new issue if there are follow-ups.
