### ISSUE TITLE
Performance regression after incremental compiler change

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#16806]
### Context

https://github.com/gradle/gradle/pull/16536 seems to introduce some performance regression, which can be ~6% in some scenario:

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestSlowLinuxbucket11/42534158:id/results/performance/build/test-results-largeMonolithicJavaProjectPerformanceTest.zip!/performance-tests/report/tests/clean-assemble-with-empty-local-cache---largeMonolithicJavaProject---TaskOutputCachingJavaPerformanceTest.html#result1990747628

Bisect to https://github.com/gradle/gradle/commit/a59133ca10bd660cf47802adc634b05b344d6419

Or 1%~2% in other scenarios:

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestTestLinuxbucket33/42539557:id/results/performance/build/test-results-largeMonolithicGroovyProjectPerformanceTest.zip!/performance-tests/report/tests/assemble-for-non-abi-change---largeMonolithicGroovyProject---JavaIncrementalExecutionPerformanceTest.html#result1990747628

https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestSlowLinuxbucket5/42534152:id/results/performance/build/test-results-largeJavaMultiProjectPerformanceTest.zip!/performance-tests/report/tests/clean-checkout---largeJavaMultiProject---JavaFirstUsePerformanceTest.html

I'll have to rebaseline all to unblock `master`.

**Comment by blindpirate** [comment]
CC @oehme @melix @gradle/execution

**Comment by oehme** [comment]
This is expected, as stated in the PR. We are doing a bit more work at the end of the task now, to get cacheability.

**Comment by wolfs** [comment]
As @oehme said, this is expected. Let's close this issue.
