### ISSUE TITLE
Compiling efficiency is also too low, the same project Maven 20 seconds, Gradle more than ten minutes to complete

### ISSUE THREAD

**Issue by zxiaozhou** [gradle/gradle#16803]
### Context
Compiling efficiency is also too low, the same project Maven 20 seconds, Gradle more than ten minutes to complete,why、why......
![image](https://user-images.githubusercontent.com/62740686/114487784-c4e44180-9c42-11eb-800a-ec7fd64f56fb.png)

### Your Environment
os: mac big sur( macbook pro )
![image](https://user-images.githubusercontent.com/62740686/114487535-543d2500-9c42-11eb-89bf-ee5dfdcecb38.png)
gradle: 7.0
tools: idea
gradle.properties:
```
org.gradle.daemon=true  
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 
org.gradle.parallel=true  
org.gradle.configureondemand=true   
```

**Comment by jjohannes** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. We don't know what's inside your project, so we cannot can not analyse what's causing the slowness. A reproducer project would help us track down and fix your problem.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.
