### ISSUE TITLE
Daemon not invalidated when certificate is added to JDK trust store

### ISSUE THREAD

**Issue by fcurts** [gradle/gradle#16801]
When a Gradle build fails due to a missing certificate in the JDK trust store, and the missing certificate is added to the JDK, subsequent Gradle builds will still fail, until I remember to run `./gradlew --stop`.

### Expected Behavior
A new daemon is started when the state of the trust store has changed.

### Current Behavior
Changed state of trust store doesn't take effect until daemon is manually stopped.

### Context
Accessing company internal Maven repos requires a company internal certificate. Every time a dev updates their JDK, this certificate must be reinstalled. If this step is forgotten, local Gradle builds will fail. The fact that builds keep failing after reinstalling the certificate creates a lot of confusion.

### Steps to Reproduce 
1. Run a Gradle build that starts a daemon
2. Add a certificate to the JDK trust store
3. Run another Gradle build - certificate isn't picked up

### Your Environment
Gradle 6.8.2
macOS 11.2.3
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)

I've seen this problem for a long time. I don't think it's limited to the above environment.

**Comment by jjohannes** [comment]
Thanks for reporting this @fcurts.
