### ISSUE TITLE
TYPESAFE_PROJECT_ACCESSORS feature doesn't respect project.name 

### ISSUE THREAD

**Issue by kuFEAR** [gradle/gradle#16815]
After update to gradle 7, with enabled TYPESAFE_PROJECT_ACCESSORS, it doesn't work in CI environment https://github.com/gradle/gradle/issues/16804#issuecomment-818800754

### Expected Behavior
Can define custom name for root and child modules

`rootProject.name = "custom-root-name"`

### Current Behavior
It inherit folder name
```
* What went wrong:
[17:29:58]	org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
[17:29:58]	  - Cannot generate project dependency accessors because project '2b0df1bb2775dc3c' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
[17:29:58]	> Cannot generate project dependency accessors:
[17:29:58]	    - Cannot generate project dependency accessors because project '2b0df1bb2775dc3c' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
```

### Steps to Reproduce 
add enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS") to settings.gradle.kts and run on CI(teamcity) https://www.jetbrains.com/help/teamcity/build-checkout-directory.html#Checkout+Process where the root name become \<Agent Work Directory\>/\<VCS settings hash code\>

### Your Environment
teamcity
gradle 7.0
openjdk 11

**Comment by xmlking** [comment]
same error for me. my project name `μservice`
```
 What went wrong:
org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
  - Cannot generate project dependency accessors because project 'μservice' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
> Cannot generate project dependency accessors:
    - Cannot generate project dependency accessors because project 'μservice' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Comment by ljacomet** [comment]
Sorry for the late reply

Java does not allow identifiers starting with a number, so that folder name, which implicitly becomes the root project name is not valid _in the current system_.

We have conversations about having an accessor for the root project be a specific name, instead of the real name.
See:
* #24295

Related:
* #16780
