### ISSUE TITLE
Switch to Gradle 7.0 causes "plugin not found"

### ISSUE THREAD

**Issue by hannesa2** [gradle/gradle#16822]
When I switch to Gradle 7.0 https://github.com/ytai/ioio/pull/250/files I run into 
`Plugin with id 'maven' not found`
https://github.com/ytai/ioio/pull/250/checks?check_run_id=2339920975

### Expected Behavior
No error should appear

### Current Behavior
It run into `Plugin with id 'maven' not found`

### Steps to Reproduce 
https://github.com/ytai/ioio/pull/250/files

### Your Environment

Here you see the error https://github.com/ytai/ioio/pull/250/checks?check_run_id=2339920975

**Comment by jjohannes** [comment]
The `maven` plugin has been removed in Gradle 7.0 after it has been deprecated for a while.

Please replace it with `maven-publish`. See: https://docs.gradle.org/current/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin
