### ISSUE TITLE
Allow for creation of customised capability instances

### ISSUE THREAD

**Issue by AmrAfifiy** [gradle/gradle#16839]
In AGP we are working on supporting testFixtures feature in the plugin, part of that is declaring a capability for the testFixtures artifacts that matches the Gradle testFixtures capability. To do this we need to either use the internal [ProjectDerivedCapability](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ProjectDerivedCapability.java) or have our own capability implementation. To avoid depending on an internal class and since implementing Capability is not supported by Gradle, a public API to create capability instances would solve the issue.

**Comment by melix** [comment]
Related: `Capability` actually misses the `@HasInternalProtocol` annotation.
