### ISSUE TITLE
Checkstyle config_loc is not generated and fails de build on Gradle 7.0

### ISSUE THREAD

**Issue by CristianGM** [gradle/gradle#16837]
### Expected Behavior
When I run `./gradlew checkstyleMain` it should work

### Current Behavior

> * What went wrong:
> Execution failed for task ':checkstyleMain'.
> > Unable to create Root Module: config {/home/travis/build/CristianGM/config_loc-issue-reproducer/whatever/checkstyle.xml}, classpath {/home/travis/build/CristianGM/config_loc-issue-reproducer/build/classes/java/main:/home/travis/build/CristianGM/config_loc-issue-reproducer/build/resources/main}.

https://scans.gradle.com/s/nbi4hm4cjl5sy/failure#1

Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property ${config_loc} has not been set	

### Context
We have a conventions plugin, it uses by default the checkstyle from another artifact, unless the user has his own checkstyle.xml
optionally it supports a suppresions file, like this:
`<property name="file" value="${config_loc}/checkstyle-suppressions.xml"/>`

The issue is that `config/checkstyle` folder doesn't exist, so Gradle doesn't add the `config_loc` but it was working on Gradle 6.8.3

I tried adding `default=""` but then Checkstyle fails with:
`ava.lang.StringIndexOutOfBoundsException: String index out of range: 0`

### Steps to Reproduce 
Reproducer: https://github.com/CristianGM/config_loc-issue-reproducer

In Travis I ran 2 jobs, one with 6.8.3 and another with 7.0, and both uploading scans
https://www.travis-ci.com/github/CristianGM/config_loc-issue-reproducer/builds/223050662

### Your Environment
Build scan URL: https://gradle.com/s/nbi4hm4cjl5sy

**Comment by CristianGM** [comment]
I've found a workaround for my convention plugin:
```
  configDirectory.set(layout.dir(provider {
    val userConfig = File(rootDir, CHECKSTYLE_CONFIG_PATH)
    if  (userConfig.exists()) userConfig else File(rootProject.buildDir, CHECKSTYLE_CONFIG_PATH)
  }))
```

but that won't work is someone uses `setConfig` instead of `setConfigFile`, I mean, if they don't have a folder that exist to set as `configDirectory`, even though we could set any arbitrary folder that exists...

Is that really the desired behavior?

**Comment by ljacomet** [comment]
This might be tied to changes in #15482 in particular the fact that it changed [this test](https://github.com/gradle/gradle/pull/15484/files#diff-c9f801f3e7e397d9d5644ba06dd45ec8e10babb22d9a7ed1183a4ce8c179d4f6R63).

**Comment by big-guy** [comment]
@CristianGM could you give `7.0.1-20210430041714+0000` a try?

**Comment by CristianGM** [comment]
Tried, it works perfectly!
Thanks!
