### ISSUE TITLE
Gradle should have a way to compute/modify jvm arguments before the daemon is started

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#16843]
### Current Behavior

Currently `org.gradle.jvmargs` are statically defined in gradle.properties or from the command line. Even if one adds it dynamically to `ext` early in the build, it is too late.

This causes a number of headaches for a build:
* Some of these arguments may be env-dependent.
  * A classic example of this is assigning heap memory (xms/xmx) flags, where a statically defined amount may not be viable for multiple developers on a team working on different laptops.
  * One solution given for this is to put your own properties in `~/.gradle/gradle.properties`, but this then imposes this on _all_ gradle projects on that machine
* Some of these arguments may need to be computed.
  * Extrapolating from the above, one might compute a fraction of the heap to use for different areas of the heap (i.e. `NewSize` args)
* Some of these may be JVM-specific.
  * Example: Later versions of Java added the `--illegal-access` flag, but it is an error to include this flag on older Java versions.
    * This will be particularly frustrating for developers testing JDK 16, which changed the default of this flag.

### Proposed API

In settings.gradle
```
daemonManagement {
  // Default values are sourced from the normal gradle.properties/command line arguments
  jvmArgs += [...]
}
```

Or a non-DSL option could be to source a local `daemon_init.sh` script that sets appropriate env vars or a lightweight configuration language like Starlark. 

### Context

See above

**Comment by autonomousapps** [comment]
I've often wished I could union JVM args from more than one place. There are the default args in the project root directory itself (`gradle.properties`), and then I might want to modify just one of them in my personal `~/.gradle/gradle.properties`. For example, I might be running in a context that has way more memory, so I can increase the `-Xmx` arg. Currently, the easiest way to do that is just to modify the project's properties file, and then remember not to check it in.

**Comment by ZacSweers** [comment]
I'd be curious if Gradle folks have a recommended pattern other than `~/.gradle/gradle.properties`, such as maybe unique gradle home dirs per-project to separate jvm arg configurations?

**Comment by ZakTaccardi** [comment]
Would having official `local.properties` support solve this issue?

https://github.com/gradle/gradle/issues/12283

**Comment by ZacSweers** [comment]
Yeah I don't think (more) static configuration is the right solution.

**Comment by melix** [comment]
There are 2 aspects of this:

1. the ability to have _project local_ daemon options. I agree that the `gradle.properties` in the user home isn't nice for this.
2. the fact of having _dynamic_ configuration

While 1. is reasonably doable, for example by supporting a `local.properties` file or something similar, 2. is much more problematic. In particular, the format you are suggesting, using `settings.gradle`, just doesn't work: the script needs to be compiled, and therefore a daemon needs to be spawned (or something which can compile Gradle scripts, which would be a single use daemon if you will). We clearly don't want to spawn a daemon, partially evaluate settings to extract daemon specific options, just to realize that the options are not compatible with the version which was started to evaluate the settings, then shutdown the daemon and start another... Would be really overkill.

Alternative options for dynamic daemon options would have to be implemented in a lightweight way, in a cross-platform environment. Something in the shell scripts, probably, but which would be supported for multiple OS...

Another option I have in mind is using something like [Dhall](https://dhall-lang.org) to generate a `local.properties` file (or something similar supported by Dhall, e.g a json config file). That said I'm not sure what dynamic information you'd need which would also be available from a Dhall config file. Eventually we clearly don't want to evaluate a script for each invocation...

**Comment by LouisCAD** [comment]
Kotlin scripts could work well.

**Comment by melix** [comment]
Kotlin is very slow to compile. It would also imply that the Kotlin compiler is available, which is not the case before we start a daemon. It would also imply introducing some kind of "compile avoidance", which is again already available in the daemon but not from anything which starts _before we start Gradle_. I would strongly advise against any such solution. To me it's much more reasonable to be static, or to use a _lightweight_ configuration language.

**Comment by ZacSweers** [comment]
Starlark maybe?

**Comment by LouisCAD** [comment]
Kotlin scripts are already cached, so if you don't touch them, they run instantly without compilation step.

That said, wouldn't it be possible to bypass setting the JVM heap size altogether and manage it automatically, just like non JVM programs do?

I think I read that in recent JVMs (don't remember starting which version), you can have dynamic/automatic heap size, where the OS can reclaim unused memory back so that a JVM doesn't hold RAM needlessly.

**Comment by ZacSweers** [comment]
Another point I wanted to mention after seeing @melix's mention of project-local properties is that this becomes a significant problem across multiple projects on the same machine. In my case, I work in a lot of OSS projects that do not safely support JDK 16 (kapt and some other tools all require special jvm args), but they all would be subject to the same home gradle.properties configuration. Same applies for memory usage, where some projects may not warrant the larger heap size that other projects do.

**Comment by melix** [comment]
I'm not sure what you mean @ZacSweers . I said I agreed that the way home `gradle.properties` works isn't great. For me it breaks the principle of least surprise, that is that the "closest" wins (project local should override whatever is in Gradle home). It's been per design. That's why I think it would be good to have a `local.properties` or whatever which takes precedence when present. Or another mechanism to have overrides per project in the home properties, or whatever.

Really, the difficult part in your feature request is _not_ this, it's the "dynamic" aspect, which is a performance and bootstrapping challenge.

**Comment by ZacSweers** [comment]
I was agreeing with you 👍. Just emphasizing that the current state (i.e. using `~/.gradle/gradle.properties` leaks those properties across multiple projects as a result, not just a problem of the same project running in different environments.

**Comment by ZacSweers** [comment]
Closing due to lack of feedback from Gradle
