### ISSUE TITLE
Init scripts should be able to declare build logic inputs

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#16849]
Init scripts should be able to declare build logic inputs using `ProviderFactory` functions such as `gradleProperty(name)` or `systemProperty(name)`  just like settings and project scripts.

### Expected Behavior

Init scripts are able to declare build logic inputs by using the `ProviderFactory` just like settings and project scripts.

```kotlin
val inputProp = providers.systemProperty("someName")
```

### Current Behavior

The `ProviderFactory` is not available in a convenient way to init scripts.

### Context
See https://github.com/gradle/gradle/pull/16757/files/0caa6ef02dedd9491a756ef6d501cb701b883b8b#r611029474

**Comment by eskatos** [comment]
It is still an issue

**Comment by mlopatkin** [comment]
This is going to be solved as part of the more general https://github.com/gradle/gradle/issues/13121.

**Comment by abstratt** [comment]
Similar: https://github.com/gradle/gradle/issues/29678
