### ISSUE TITLE
Add an option to easily create a bundle containing all libs recorded in the given catalog

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#16854]
### Expected Behavior

I'd like to easily create a bundle with all the registered aliases within a catalog.

For example [here](https://github.com/elect86/sciJava-catalogs/blob/30.0.0/src/main/kotlin/sciJava/catalogs/sciJava.kt), I'd like to just type at the end something like

`bundle("all", aliases)`

where aliases is a list containing all the aliases registered so far (either that, or expose the aliases themselves and then I'll `map`)

Another option could be to automatically provide by default for each catalog a bundle containing all the entries (I'd love that)

### Current Behavior

I have to type in every single alias manually

`bundle("all", listOf(..))`

### Context

In this way I can easily use my catalog as a platform, by constraining simply on all the complete bundle(s) of all my catalogs

**Comment by bmuskalla** [comment]
Thanks for reporting this @elect86 - marking as a dup of #16784

**Comment by elect86** [comment]
ok, but this may still be useful outside the context I'm planning for, just saying

**Comment by bmuskalla** [comment]
True, please feel free to share more thoughts on #16784
