### ISSUE TITLE
Support native languages in build init plugin

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#1685]
Add [Build Init Plugin](https://docs.gradle.org/current/userguide/build_init_plugin.html) types for native languages supported by Gradle.

### Expected Behavior

Build init plugin can generate projects using native languages that are supported out of the box:
- C
- C++
- Objective-C
- Objective-C++
- Assembly
- Windows resources

### Current Behavior

Build init plugin can only generate projects using JVM languages (Java, Groovy and Scala).

### Context

Adding build init types for native languages would make it easier to get started with Gradle for native developers.

**Comment by big-guy** [comment]
Issue moved to [gradle/gradle-native #498](https://github.com/gradle/gradle-native/issues/498) via [**ZenHub**](https://www.zenhub.com/)
