### ISSUE TITLE
DependencyHandler create method is missing configure with Action overload

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#16865]
### Expected Behavior
I would expect `project.dependencies.create(notation) { // configuration }` approach will work when using Kotlin.

### Current Behavior
Currently method only accepts Groovy closure for dependency configuration.

### Context

Should make a little easier to write Gradle plugins or build scripts using Kotlin language.

**Comment by grossws** [comment]
Still relevant

**Comment by eskatos** [comment]
This has been fixed in https://github.com/gradle/gradle/pull/20554 and will ship in Gradle 7.6

Thanks you @grossws for your contribution!
