### ISSUE TITLE
Gradle fails with a NullPointerException when using --profile

### ISSUE THREAD

**Issue by fkruege** [gradle/gradle#16872]
### Expected Behavior
Gradle profiler should not crash.

### Current Behavior
Gradle profiler is crashing with a NPE,

```
1: Task failed with an exception.
-----------
* What went wrong:
java.lang.NullPointerException (no error message)
* Try:
 Run with --scan to get full insights.
* Exception is:
java.lang.NullPointerException
	at org.gradle.profile.ProfileEventAdapter.beforeResolve(ProfileEventAdapter.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```
### Context
This is occurring in our prod app.  We have a gradle profiler job that captures build metrics and we use this to understand our build performance. This used to work in Gradle 6.8.3 but stopped working when we upgraded to Gradle 7.0. 

### Steps to Reproduce 

 I created a sample project that duplicates the error.

Sample project: https://github.com/fkruege/KotlinGradleProfilerNPE
Command to run: `gradle-profiler --gradle-user-home ./gradle_new --benchmark --iterations 1 --project-dir ./ --scenario-file ./profiler.scenarios ci_clean`

[log_crash.txt](https://github.com/gradle/gradle/files/6327542/log_crash.txt)

### Your Environment
Gradle Profiler 0.16

Build scan URL:

**Comment by bmuskalla** [comment]
Issue moved to [gradle/gradle-profiler #330](https://github.com/gradle/gradle-profiler/issues/330) via [**ZenHub**](https://www.zenhub.com/)

**Comment by bmuskalla** [comment]
@fkruege I just moved it over

**Comment by bmuskalla** [comment]
@wolfs When you have a moment, it would be great if you can share how you reproduced this on `master`.
```
./gradlew baseServices:compileJava --profile`
```
works fine for me: https://ge.gradle.org/s/5gyigemrpw6jw

**Comment by wolfs** [comment]
It fails with an NPE when using this init script: 
```
import com.gradle.enterprise.gradleplugin.GradleEnterprisePlugin
import com.gradle.scan.plugin.BuildScanPlugin
import org.gradle.util.GradleVersion

initscript {
    def pluginVersion = "3.5"

    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.gradle:gradle-enterprise-gradle-plugin:${pluginVersion}")
    }
}

def isTopLevelBuild = gradle.getParent() == null

if (isTopLevelBuild) {
    def gradleVersion = GradleVersion.current().baseVersion
    def atLeastGradle5 = gradleVersion >= GradleVersion.version("5.0")
    def atLeastGradle6 = gradleVersion >= GradleVersion.version("6.0")

    if (atLeastGradle6) {
        settingsEvaluated {
            if (!it.pluginManager.hasPlugin("com.gradle.enterprise")) {
                it.pluginManager.apply(GradleEnterprisePlugin)
            }
            configureExtension(it.extensions["gradleEnterprise"].buildScan)
        }
    } else if (atLeastGradle5) {
        rootProject {
            pluginManager.apply(BuildScanPlugin)
            configureExtension(extensions["buildScan"])
        }
    }
}

void configureExtension(extension) {
    extension.with {
        publishAlways()
        if (server == null || server == 'https://ge.spring.io') {
//            server = "https://e.grdev.net"
            server = "https://ge.gradle.org"
        }
    }
}
```

**Comment by big-guy** [comment]
@fkruege could you give `7.0.1-20210505181542+0000` a try?

**Comment by fkruege** [comment]
It's working now.  Thank you for fixing.
