### ISSUE TITLE
gradle --version should give easier to parse info

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#16879]
currently gradle gives:
```
> gradle --version

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-03-09 20:40:53 UTC
Revision:     <unknown>
...
```
please give something easier to parse, like:
```
> gradle --version
Gradle: 6.8.3
Build time:   2021-03-09 20:40:53 UTC
Revision:     <unknown>
...
```

**Comment by bmuskalla** [comment]
Would you mind sharing what you're trying to achieve with parsing this information? "easier to parse" is relative depending on the tools you have at your disposal. Also, the current output is intended for humans, not machines (which is a fair feature request in itself)

**Comment by bmuskalla** [comment]
We currently have no plans to address this. If you can provide more information what you intend to do, please let me know.
