### ISSUE TITLE
Gradle Koans: sample challenges for getting familiar with Gradle

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#16875]
### Expected Behavior

There should be a guide with challenges so people can get familiar with Gradle by solving small tasks.

It would be great if the tool (standalone? IDE plugin?) could automatically verify the solutions as well.

### Current Behavior

It looks like Koans are missing: https://gradle.org/guides/

### Context

https://play.kotlinlang.org/koans/overview

**Comment by alllex** [comment]
Sorry for the late reply

This seems like a resource that would be useful for the community.
This idea overlaps with the recently launched [DPE University](https://dpeuniversity.gradle.com/app) that contains free course about Gradle build tool basics, as well as deeper topics.

---

@oleg-nenashev, what do you think about having a dedicated resource for Koans?

**Comment by oleg-nenashev** [comment]
I think it would be a good addition for the Gradle cookbook where we try to consolidate tool and solution specific guidelines https://community.gradle.org/cookbook/

**Comment by lkasso** [comment]
Thank you for the suggestion. At this point in time we are focusing on more tutorials and samples in the documentation but it is unlikely that we will add something like Koans.
