### ISSUE TITLE
403 answer from maven repo for artifacts that don't exist

### ISSUE THREAD

**Issue by andham** [gradle/gradle#16881]
### Expected Behavior
When proxying/mirroring your maven repo (https://plugins.gradle.org/m2/) and requesting an artifact that DON'T exist, I expect a 404 answer. This is also what tools like Nexus expect. I believe this is also what used to be responded.

### Current Behavior
Currently it seems as a redirect to https://jcenter.bintray.com/ARTIFACT_PATH which returns a 403 (Forbidden) response. This causes a tool like Nexus proxying the repo to report errors when it shouldn't. There is not error, the artifact simply doesn't exist.

### Context
We've recently started to receive many error messages related to this from our Nexus instance. We haven't seen this earlier and possibly it's related to the jcenter shut down process.
These error messages from Nexus are confusing and causes extra job to understand if it's a real problem or just noise.

### Steps to Reproduce 
It can be reproduced by trying to access https://plugins.gradle.org/m2/org/acme/acme/1.0/acme-1.0.pom

### Your Environment
Any web browser or Sonatype Nexus repo manager (tested with v2.14.20-02).

**Comment by bmuskalla** [comment]
@big-guy @JLLeitschuh Is this intentional?

**Comment by JLLeitschuh** [comment]
This sounds like unannounced changes in behaviour by JFrog. 🤔

**Comment by JLLeitschuh** [comment]
Supposedly, if you use a Gradle or Maven user agent, you'll get the traditional 404 response

**Comment by andham** [comment]
Investigating this further it seems that it's not a problem. Testing with curl and specifying a Nexus user agent I get 404 responses. We're still seeing issues in Nexus with your repo, but the issue doesn't seem to be what I described here. I'm closing and might open a new ticket when I figured out the correct root cause.
