### ISSUE TITLE
Make sure build operations have unique display names

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1688]
Unique display names should be derived from their context. Which should be unique (e.g. each `Apply plugin 'org.gradle.java'` should have a different parent).

We should not compute them at the moment we create an operation (but when we need them to be displayed).

**Comment by oehme** [comment]
The `displayName` concept was used when bridging between build operations and progress logging. With the new console, this might no longer be an issue, but let's wait what the core team has to say about it.

In the meantime, we should fix those names above. It should be name = "Project :" and displayname = "Configuring Project :" for the project configuration. It should be name = "Apply plugin pluginId" and displayName "Apply plugin pluginID to target" for the plugin. It should be name = "Apply script scriptName" and displayName = "Apply script scriptName to target" for the script application. Sorry for getting you on the wrong track there @jjohannes . Can you create a quick PR for those fixes?

**Comment by adammurdoch** [comment]
The display name would be used in places like:

- A UI that displays the current operation, but not the tree, for example a progress bar.
- Error messages when an operation fails.
- Logging messages.

We _could_ synthesise a display name from a hierarchy of operations, but I'm not fully convinced that we _should_. I'm ok with us trying this out to see how it looks.

**Comment by jjohannes** [comment]
Thanks for the explanations. I am also not very convinced anymore about _synthesising_ the display names from the hierarchy. I guess what we want is not computing names we do not need. So if, for example, the `displayName` is not used in a build execution from console, we should not calculate it upfront (or if only `displayName` name is used but not `name`, it should be the other way around). 

Maybe we just need the possibility to do this lazily in cases where it is needed. Then there are cases where name and display are similar and static, where we would not need that. As one of them will almost always been used. For example:
https://github.com/gradle/gradle/blob/980e84d18907707c6370f75f61cae3c41c613273/subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationProjectConfigurator.java#L36-L38

Here is a PR following @oehme's suggestions for the new build operations: https://github.com/gradle/gradle/pull/1781

It also addressed some concerns mentioned here (regarding script application operations):  https://github.com/gradle/gradle/issues/1682#issue-217490329

Anyway, having a _unique_ display name for every operation (as the title of this issue suggests) is not something that we should/can keep up. Maybe it is still true for certain leaf operations. When we are more certain about what we expect, we should adjust the `ProgressEvents` test fixture.

**Comment by jjohannes** [comment]
<img width="503" alt="ops_new" src="https://cloud.githubusercontent.com/assets/1963746/24804460/cd0ec45c-1bae-11e7-8c2b-419c8a2a4ee8.png">
