### ISSUE TITLE
Repo libs-releases-local outdated, not containing artifacts after 6.1.1

### ISSUE THREAD

**Issue by voidzcy** [gradle/gradle#16884]
Looks the last updated date for https://repo.gradle.org/gradle/libs-releases-local/org/gradle/ is 24-Jan-2020 for 6.1.1 release. After that, nothing has been pushed there. Plugin developers depending on APIs of Gradle subprojects (e.g., protobuf-gradle-plugin using kotlin-dsl's extension APIs) are not able to upgrade.

There is an API change for kotlin-dsl made in 6.8, [`NamedDomainObjectContainer<T>.invoke(kotlin.Function1)`](https://docs.gradle.org/6.8/userguide/upgrading_version_6.html#using_NamedDomainObjectContainer_invoke_kotlin_Function1). But protobuf-gradle-plugin is not able to migrate away from it, as no artifact containing the changed API definition can be found.

(#15508 reverted the API deletion, but I guess Gradle is still suggesting to migrate.)

### Expected Behavior

Be able to find the latest version of Gradle subproject artifacts (e.g., `org.gradle:gradle-kotlin-dsl:6.8.3`).

### Current Behavior

Third-party plugins are not able to migrate usages of APIs from Gradle subprojects.

### Context

NA

### Steps to Reproduce 

NA

### Your Environment

NA

Build scan URL:

**Comment by ljacomet** [comment]
Gradle API should be consumed by adding the embedded dependency to `gradleApi()` in dependency declaration.

There is no immediate plan to publish these binaries as they expose way more than the public API.

Can you be more specific as why there is a use case where `gradleApi()` is not enough?

**Comment by voidzcy** [comment]
Specifically, the protobuf-gradle-plugin has an API for users to configure `NamedDomainObjectContainer`, something like

```gradle
protobuf {
   plugins {  // <== NamedDomainObjectContainer<PluginOptions>
      id("grpc") {
        artifact = "io.grpc:protoc-gen-grpc-java:1.37.0"
      }
   }
}
```

In Groovy, this is just delegated by [`ConfigureUtil.configure(Closure, T)`](https://github.com/gradle/gradle/blob/104c63f9682c43804b8961ace58c5942e9a3aea7/subprojects/model-core/src/main/java/org/gradle/util/ConfigureUtil.java#L109). In Kotlin DSL, it uses [`<T : Any, C : NamedDomainObjectContainer<T>> C.invoke(configuration: NamedDomainObjectContainerScope<T>.() -> Unit)`](https://github.com/gradle/gradle/blob/104c63f9682c43804b8961ace58c5942e9a3aea7/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/NamedDomainObjectContainerExtensions.kt#L54).

However, Gradle is changing the Kotlin DSL API to `<T : Any, C : NamedDomainObjectContainer<T>> C.invoke(configuration: Action<NamedDomainObjectContainerScope<T>>)` as in https://github.com/gradle/gradle/commit/593001e74f21a67ecc8d6f6c6174818f02eab007. Although #15508 added the `T.() -> Unit` overloading back, I guess in the long term Gradle is still suggesting plugins to migrate.

So, protobuf-gradle-plugin would need compile-time access to the `<T : Any, C : NamedDomainObjectContainer<T>> C.invoke(configuration: Action<NamedDomainObjectContainerScope<T>>)` API, which is provided by `org.gradle:gradle-kotlin-dsl`.  `gradleApi()` doesn't seem to provide this.

**Comment by iNikem** [comment]
This issue looks like Gradle 8.0 will break all builds which use `protobuf-gradle-plugin` but does not provide any means for plugin authors to migrate to the recommended API. I assume that "do not upgrade to Gradle 8" will be the official answer of the Gradle team? Or is there a way for a community to resolve this issue? Either here or in `protobuf-gradle-plugin` repo?

**Comment by big-guy** [comment]
The specific issues around protobuf-gradle-plugin have been addressed by https://github.com/google/protobuf-gradle-plugin/pull/577 (a part of v0.9.0).

The "official" Gradle API is the one produced by `gradleApi()` and not the published libraries on repo.gradle.org.
