### ISSUE TITLE
Misleading documentation about uploading gradle plugins & manual approval

### ISSUE THREAD

**Issue by kshchepanovskyi** [gradle/gradle#16898]
On this page there's a section about manual review: https://plugins.gradle.org/docs/submit

> Some plugins require manual acceptance by the Plugin Portal maintainers, and will not be made available immediately when they are published. This is only the case when you have specified a custom “group ID” for your plugin artifact. The plugin publishing plugin will tell you if your plugin is pending acceptance when you publish.

Also here: https://plugins.gradle.org/docs/publish-plugin

> If you would like to have a non-prefixed coordinate group, you can do so by setting the group in a mavenCoordinates block. Note that non-prefixed groups require manual approval the first time one is published. See the Full Example below.

Documentation says that if I do not change group id, plugin will be enabled automatically. However, it's not happening as policy was changed in 2020, all plugins are reviewed manually now: https://discuss.gradle.org/t/plugin-pending-approval-questions/35017

These sections should be removed from documentation, it should say that all new plugins are manually reviewed.

P.S. Raising this issue because I spent some time figuring out why my plugin wasn't enabled right away. Most likely somebody else also wasted time due to this issue.

**Comment by ljacomet** [comment]
Issue moved to [gradle/plugin-portal-requests #94](https://github.com/gradle/plugin-portal-requests/issues/94) via [**ZenHub**](https://www.zenhub.com/)
