### ISSUE TITLE
Avoid unnecessary String computation during build operation creation

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1690]
(Display) names might only be needed later (or not at all). They could be derived from context instead of being computed up-front.

Related: #1688

**Comment by oehme** [comment]
I'm pretty sure the display name is always needed. The moment you create a build operation, you know it is going to be executed. And when it is executed, it will get logged on the console, captured by build scans etc. So being lazy here won't help.

**Comment by jjohannes** [comment]
I started the discussion here (as both issues are strongly connected):
https://github.com/gradle/gradle/issues/1688#issuecomment-292194496

Closing this one.
