### ISSUE TITLE
Checkstyle `reports` docs incorrect

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#16905]
### Expected Behavior
Example given in DSL docs are valid.

### Current Behavior
Unless I'm missing something obvious, this config doesn't work (this is copied from the Javadoc but I've corrected the task name in my own examples):
```groovy
 checkstyleTask {
   reports {
     html {
       destination "build/checkstyle.html"
     }
   }
 }
```

Giving the error `> No signature of method: build_dqdccbp3yn3o2586tc0966gkh.checkstyleMain() is applicable for argument types: (build_dqdccbp3yn3o2586tc0966gkh$_run_closure2) values: [build_dqdccbp3yn3o2586tc0966gkh$_run_closure2@71647e9a]`

Source:
https://github.com/gradle/gradle/blob/e4c8f4cf86353f1ecd4ad079817a7106a4468f63/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java#L98-L135

### Context
Examples in docs should be accurate.

**Comment by ljacomet** [comment]
`checkstyleTask` is an example and needs to be changed to point at the right task name.

Can you please craft a complete reproducer?

**Comment by ljacomet** [comment]
Closing given there was no reproducer provided.
