### ISSUE TITLE
Removal of StartParameter.isSearchUpwards breaks our build setup

### ISSUE THREAD

**Issue by calvertdw** [gradle/gradle#16911]
### Expected Behavior

We use the StartParameter.isSearchUpwards value to determine if the build is currently the root of the composite build. That way, only the root build searches for builds to include.

The code can be found here:
https://github.com/ihmcrobotics/ihmc-build/blob/c9ca6201c58b503499f26a5996c808a2c18df5c7/src/main/kotlin/us/ihmc/build/IHMCSettingsConfigurator.kt#L51

### Current Behavior

Since the API for StartParameter.isSearchUpwards is removed, we get the error:
```
java.lang.NoSuchMethodError: org.gradle.StartParameter.isSearchUpwards()Z
```

### Context

Our build setup at [IHMC Robotics](https://github.com/ihmcrobotics) uses the composite build feature of Gradle heavily. We have a Gradle plugin that identifies locally cloned repositories and sets them up as source dependencies in the build instead of resolving the published artifact versions.

If there were another value to check that would allow our build to determine if it is the root build, that would solve our problem.

### Steps to Reproduce 

1. Clone our open source repository: https://github.com/ihmcrobotics/ihmc-open-robotics-software
2. Run `gradle` with no arguments with Gradle 7.0

### Your Environment

Build scan URL: https://gradle.com/s/qdr2hovxarvoe

**Comment by ljacomet** [comment]
This deprecation was announced in Gradle 5 and was a target for removal in 7 for a long time.
There will be no going back.

Can you describe and point as to where you used that to determine if the build was the root one? You should be able to reproduce the internal logic in your own setup effectively.

**Comment by big-guy** [comment]
You could also check `gradle.parent == null` to find the root build.

**Comment by calvertdw** [comment]
`gradle.parent == null` appears to work. Thanks @big-guy :smile:
