### ISSUE TITLE
Please update the URL in the Gradle ManPage. It leads to a 404.

### ISSUE THREAD

**Issue by TechAndNews** [gradle/gradle#1691]
![gradle-manpage-url-is-404](https://cloud.githubusercontent.com/assets/7966743/24421476/5b8c0124-13c4-11e7-9636-cf9783771f26.png)

![gradle-userguide-404](https://cloud.githubusercontent.com/assets/7966743/24421481/601aef84-13c4-11e7-86fa-3d121417ce80.png)

**Comment by big-guy** [comment]
Hi @TechAndNews 

We don't ship man pages with Gradle, so I suspect this is coming from your distributions re-packaging of Gradle.  Which OS and which version of Gradle are you using?

**Comment by TechAndNews** [comment]
I think I got Gradle with AndroidStudio-2.3 (2017-03-27), but when I typed [ gradle tasks ] in Bash, it said Gradle wasn't installed. 

After doing [ apt-cache search gradle ], I discovered:

gradle 
gradle-doc 
libgradle-core-java 
libgradle-plugins-java

And then ran:
sudo apt-get install gradle gradle-doc libgradle-core-java libgradle-plugins-java

$ gradle -v
------------------------------------------------------------
Gradle 1.4
------------------------------------------------------------
Gradle build time: Monday, September 9, 2013 8:44:25 PM UTC
Groovy: 1.8.6
Ant: Apache Ant(TM) version 1.9.3 compiled on April 8 2014
Ivy: non official version
JVM: 1.7.0_121 (Oracle Corporation 24.121-b00)
OS: Linux 3.19.0-32-generic amd64

LinuxMint 17.3 - 64-bit - 4GB RAM

When installing AndroidStudio-2.3 from the official website, it suggested these packages that were already installed: 

libc6:i386 
libncurses5:i386 
libstdc++6:i386 
lib32z1 
libbz2-1.0:i386

**Comment by bmuschko** [comment]
Gradle 1.4 is extremely old and would suggest installing the latest version required by the Android plugin. Gradle Inc. is not maintaining the package resolvable by `apt-get`. Please refer to the documentation for installing a newer version: https://gradle.org/install

**Comment by TechAndNews** [comment]
OK. Thank You. Will [ apt-get purge ] those 4 packages and use the steps on your website to get the newest version. 

If I don't use Gradle from the commandline, will the version that ships with AndroidStudio-2.3 be sufficient for basic use in creating Android Apps?

**Comment by bmuschko** [comment]
AndroidStudio calls of to the Gradle tooling API which is shipped with Gradle. It's going to use the Gradle version that you configure in AndroidStudio. I am not super familiar what they usually recommend. I suggest you look at the manual for the [Gradle Android plugin](https://developer.android.com/studio/releases/gradle-plugin.html).

**Comment by TechAndNews** [comment]
OK. Thank You.

**Comment by TechAndNews** [comment]
Removed all these. Thanks for your help. You can close this Ticket. 

sudo apt-get purge gradle gradle-doc libgradle-core-java libgradle-plugins-java

The following packages were automatically installed and are no longer required:
  ant ant-optional antlr aspectj bnd bsh checkstyle groovy ivy java-wrappers
  junit junit4 libaether-java libantlr-java libaopalliance-java
  libapache-pom-java libasm3-java libasm4-java libaspectj-java
  libasync-http-client-java libatinject-jsr330-api-java
  libavalon-framework-java libbatik-java libbcel-java libbcpg-java
  libbcprov-java libbsf-java libbsh-java libcdi-api-java libcglib-java
  libclassworlds-java libcodenarc-groovy-java libcommons-beanutils-java
  libcommons-cli-java libcommons-codec-java libcommons-collections3-java
  libcommons-configuration-java libcommons-dbcp-java
  libcommons-httpclient-java libcommons-io-java libcommons-lang-java
  libcommons-logging-java libcommons-net2-java libcommons-parent-java
  libcommons-pool-java libconstantine-java libdom4j-java libdoxia-java
  libeasymock-java libecj-java libfop-java libganymed-ssh2-java
  libgeronimo-interceptor-3.0-spec-java libgeronimo-jpa-2.0-spec-java
  libgeronimo-jta-1.1-spec-java libgeronimo-osgi-support-java
  libgmetrics-groovy-java libgnuinet-java libgnujaf-java libgnumail-java
  libgoogle-gson-java libguava-java libguice-java libhamcrest-java
  libhawtjni-runtime-java libhttpclient-java libhttpcore-java libitext1-java
  libjackrabbit-java libjaffl-java libjansi-java libjansi-native-java
  libjarjar-java libjaxen-java libjaxp1.3-java libjcifs-java
  libjcip-annotations-java libjcommander-java libjdom1-java
  libjetty-extra-java libjetty-java libjffi-java libjffi-jni libjline-java
  libjnr-posix-java libjnr-x86asm-java libjsch-java libjsoup-java
  libjsr305-java libkryo-java liblog4j1.2-java liblogback-java
  libmaven-ant-tasks-java libmaven-parent-java libmaven-scm-java
  libmaven2-core-java libminlog-java libmockobjects-java libmodello-java
  libmx4j-java libnative-platform-java libnative-platform-jni libnekohtml-java
  libnetbeans-cvsclient-java libnetty-java libobjenesis-java
  libosgi-compendium-java libosgi-core-java libosgi-foundation-ee-java
  libplexus-ant-factory-java libplexus-archiver-java
  libplexus-bsh-factory-java libplexus-build-api-java libplexus-cipher-java
  libplexus-classworlds-java libplexus-classworlds2-java libplexus-cli-java
  libplexus-container-default-java libplexus-containers-java
  libplexus-containers1.5-java libplexus-i18n-java
  libplexus-interactivity-api-java libplexus-interpolation-java
  libplexus-io-java libplexus-sec-dispatcher-java libplexus-utils-java
  libplexus-utils2-java libpolyglot-maven-java libqdox-java libreflectasm-java
  libregexp-java librhino-java libservlet2.5-java libsisu-guice-java
  libsisu-ioc-java libslf4j-java libtomcat7-java libwagon-java libwagon2-java
  libxalan2-java libxbean-java libxerces2-java libxml-commons-external-java
  libxml-commons-resolver1.1-java libxmlgraphics-commons-java libxpp2-java
  libxpp3-java libxstream-java libyaml-snake-java maven testng

Use 'apt-get autoremove' to remove them.

The following packages will be REMOVED:
  gradle* gradle-doc* libgradle-core-java* libgradle-plugins-java*

0 upgraded, 0 newly installed, 4 to remove and 0 not upgraded.
After this operation, 39.5 MB disk space will be freed.
Do you want to continue? [Y/n]

Removing gradle (1.4-2ubuntu1) ...
Removing gradle-doc (1.4-2ubuntu1) ...
Removing libgradle-plugins-java (1.4-2ubuntu1) ...
Removing libgradle-core-java (1.4-2ubuntu1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for doc-base (0.10.5) ...
Processing 1 removed doc-base file...
Registering documents with scrollkeeper...
