### ISSUE TITLE
`ResolvedArtifactResult.getVariant().getCapabilities()` is empty if artifact comes from an `ArtifactCollection`

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#16919]
In AGP, we are attempting to go through 2 different Gradle APIs to get a proper graph view of the dependencies, and also get additional information about each artifact. This would allows us to reconcile both views and come up with a graph where we know
- whether a sub-project node is Android or Java
- the location of the extracted information in case of an external AAR dependency (because we have quite a few transforms applied to AARs, we need to get these values via an `ArtifactView` to get the exact, transformed, location.)

So first, we go through `ResolutionResult` and `DependencyResult`. Looking at the `ResolvedVariantResult`, we can see the proper list of `Capability`.
Then, we query for an `ArtifactCollection`. However in this case, looking inside the `ResolvedVariantResult` found inside the `ResolvedArtifactResult`, the list of capabilities is always empty.

Our understanding is that in order to reconcile these two views, we need to match entries found via both APIs, and we cannot use `ComponentIdentifier`, because of the test fixtures case. We are therefore using `ResolvedVariantResult` instead but because the list of capabilities is not the same, we cannot actually match both APIs. Is this expected? Is there a different way to match results from both APIs to achieve what we want?

I've attached a small project that reproduces the lack of capability [here](https://github.com/gradle/gradle/files/6347193/resolved-variant-capabilities.zip). It contains 2 sub-projects, one consuming the other which has the `java-test-fixtures` plugin applied. A custom plugin (in `buildSrc`) creates a task called `dumpGraph` which queries for an `ArtifactView` and dump the file and capabilities of each artifact.

The output looks like this:
```
> Task :library1:dumpGraph
Artifact: project :library2
  - artifact: /.../resolved-variant-capabilities/library2/build/libs/library2-test-fixtures.jar
  - capabilities: None
---------
Artifact: project :library2
  - artifact: /.../resolved-variant-capabilities/library2/build/libs/library2.jar
  - capabilities: None
---------
```

As you can see there are 2 artifacts in the view, for both the library and its fixtures but the capabilities is missing from the latter.

**Comment by ljacomet** [comment]
So this is indeed missing information when using the `ArtifactCollection`, the capabilities information was not wired in.

Looking into fixing this for the next release.

**Comment by ducrohet** [comment]
Hi, any update on when this might land? We're trying to land our new model but this cannot work with this bug.

We have a work around for test fixtures for Java library but it cannot work for test fixtures in android library projects.

thanks!

**Comment by ducrohet** [comment]
This is not completely correct.
While this work for the case where there are capabilities (e.g. test-fixtures), for the case where there isn't any (ie just a normal dependency), the `ResolvedArtifactResult` shows an empty list. However `ResolvedDependencyResult.resolvedVariant` always contains a capability, even if it's just (`"build-name"`, `"project-name"`, `"unspecified"`). 

This means the 2 APIs still aren't consistent.

**Comment by ducrohet** [comment]
I've now done a bit more test and it looks like if the artifacts gotten via the `ArtifactCollection` have been process through an `ArtifactTransform`, the capabilities are lost.

I've created an [updated version](https://github.com/gradle/gradle/files/6866336/resolved-variant-capabilities.zip) of the repro case where I added an android-app sub-project that depends on a published android library that contains test fixtures. Querying for an artifact that's processed via transform does not provide the capability information.

Just run `dumpGraph` on the project as before. The output will be:
```
> Task :android-app:dumpGraph
Artifact: com.example:aar:1
  - artifact: /Users/xav/.gradle/caches/transforms-3/4d9bd7aca6fd6cde438091a3f71bd2a5/transformed/aar-1-test-fixtures
  - capabilities: None
---------
Artifact: com.example:aar:1
  - artifact: /Users/xav/.gradle/caches/transforms-3/14d8a5a61f168eeb98deb9cd1de70cdd/transformed/aar-1
  - capabilities: None
---------

> Task :library1:dumpGraph
Artifact: project :library2
  - artifact: /Users/xav/Downloads/resolved-variant-capabilities/library2/build/libs/library2-test-fixtures.jar
  - capabilities: [resolved-variant-capabilities:library2-test-fixtures:unspecified]
---------
Artifact: project :library2
  - artifact: /Users/xav/Downloads/resolved-variant-capabilities/library2/build/libs/library2.jar
  - capabilities: None
```

The bottom shows that library1 sees the sub-project (java) library with the right capability. This is when querying for `jar` `artifactType`. The top shows the result of querying for `android-exploded-aars` which is transformed but the capabilities are missing.

**Comment by ljacomet** [comment]
Thanks for testing out the fix!
We will be looking into these additional reports.

**Comment by ducrohet** [comment]
I have found another case where this is broken. The issue stems from using an `AttributeCompatibilityRule`, a task that has an `ArtifactCollection` field and configuration caching. I've prepared a repro project [here].(https://github.com/gradle/gradle/files/6957812/resolved-variant-capabilities-v2.zip)

Running `dumpViaConfigCache` will normally display:
```
Artifact: com.android.support.constraint:constraint-layout:1.0.2
  - artifact: /Users/xav/.gradle/caches/modules-2/files-2.1/com.android.support.constraint/constraint-layout/1.0.2/4f47352b754e5b418b481dce696d7b92bf870f64/constraint-layout-1.0.2.aar
  - capabilities: [com.android.support.constraint:constraint-layout:1.0.2]
---------
Artifact: com.android.support.constraint:constraint-layout-solver:1.0.2
  - artifact: /Users/xav/.gradle/caches/modules-2/files-2.1/com.android.support.constraint/constraint-layout-solver/1.0.2/b9cd8fc6bd15cb915735d34535db30ece0c44603/constraint-layout-solver-1.0.2.jar
  - capabilities: [com.android.support.constraint:constraint-layout-solver:1.0.2]
---------
```

However, if running with `--configuration-cache` twice, the result will be:
```
Artifact: com.android.support.constraint:constraint-layout:1.0.2
  - artifact: /Users/xav/.gradle/caches/modules-2/files-2.1/com.android.support.constraint/constraint-layout/1.0.2/4f47352b754e5b418b481dce696d7b92bf870f64/constraint-layout-1.0.2.aar
  - capabilities: None
---------
Artifact: com.android.support.constraint:constraint-layout-solver:1.0.2
  - artifact: /Users/xav/.gradle/caches/modules-2/files-2.1/com.android.support.constraint/constraint-layout-solver/1.0.2/b9cd8fc6bd15cb915735d34535db30ece0c44603/constraint-layout-solver-1.0.2.jar
  - capabilities: None
---------
```

This will make all our `Lint` task non compatible with configuration caching (once we land a bunch of improvements). This is tracked on our side via https://issuetracker.google.com/195978143

**Comment by ducrohet** [comment]
Actually this has nothing to do with `AttributeCompatibilityRule`. You can simply remove the compat rule, and make the query be just `"aar"` and run it twice with config caching and it'll fail too.

**Comment by adammurdoch** [comment]
Should be fixed now, via https://github.com/gradle/gradle/pull/17994
