### ISSUE TITLE
Jacoco execution data is not a task output of test task

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16927]
If in Gradle 7.0 a task uses the output of another task without having an explicit or implicit dependency on the task,
you now get a deprecation warning and the message that some optimizations were disabled.

I guess those optimizations are crucial and only work properly if the dependencies are set up properly.

Now what I observed is, that the `JacocoReport` task uses output of the `Test` task without imposing any dependency and without getting that deprecation warning and optimization disabling.

The JaCoCo execution data file is not registered as task output, which probably is the cause there is no warning. But effectively it is an output of that task, isn't it?

If you currently execute `jacocoTestReport` it is skipped, if the execution data file is not present and executed if it is there.
But independent of the test task being executed actually.

**Comment by ljacomet** [comment]
While you are right in theory, in practice it was decided to not do this strong link between Jacoco report and the test task.

Instead it is left up to the user to decide how much linking is desired - see example 2 in https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_getting_started

**Comment by OrangeDog** [comment]
@ljacomet I tried following that example, and get one of these depending on where I put it:

> A problem occurred evaluating root project 'MyProject'.
> Could not find method test() for arguments [build_5u3n3jhmu2t1xgt7nfyd1omzo$_run_closure3@3a765e94] on root project 'MyProject' of type org.gradle.api.Project.

> A problem occurred evaluating project ':app'.
> Could not find method test() for arguments [build_agbp1opkla91p8kpz3d975cxw$_run_closure2@a0fd867] on project ':app' of type org.gradle.api.Project.

> A problem occurred evaluating project ':app'.
> No signature of method: build_agbp1opkla91p8kpz3d975cxw.android() is applicable for argument types: (build_agbp1opkla91p8kpz3d975cxw$_run_closure1) values: [build_agbp1opkla91p8kpz3d975cxw$_run_closure1@2c756573]

**Comment by ov7a** [comment]
Sorry for the late reply.

Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
