### ISSUE TITLE
Cannot inject services into extension created on a task

### ISSUE THREAD

**Issue by oesolutions** [gradle/gradle#16936]
When creating an extension on a task, Gradle fails to inject services (ObjectFactory, ProviderFactory, etc).

### Expected Behavior
When adding extensions to the project or objects created using `ObjectFactory.newInstance`, services are correctly injected into the extension's constructor. This does not work for extensions created on tasks, but probably should.

### Current Behavior
Creation of the task extension fails with `missing parameter of type <service>, or no service of type <service>`.

### Steps to Reproduce
```groovy
class MyExt {
    Property<String> myProp
    @javax.inject.Inject
    MyExt( ObjectFactory objectFactory, String target ) {
        println "target: ${target}, service: ${objectFactory}"
        myProp = objectFactory.property( String )
        myProp.set( target )
    }
}
interface MyType {
}

[
    project: project,
    object: objects.newInstance( MyType ),
    task: tasks.create( 'myTask' )
].each { t, o ->
    o.extensions.create( 'myExt', MyExt, t )
    println o.myExt.myProp.get()
}
``` 

### Your Environment
Tested on Gradle 6.8.3, 7.0.

**Comment by big-guy** [comment]
This is surprising/not intended behavior. I checked as far back as Gradle 5.4 and this has never worked.

You can workaround this by doing something like:
```
extensions.create(MyExt, "myExt", project.objects.newInstance(MyExt))
```

You don't need to explicitly inject `ObjectFactory`, so `MyExt` could just be (abstract class works too):

```
interface MyExt {
    Property<String> getMyProp
}
```

I added a reproducer in https://github.com/gradle/gradle/pull/17402

**Comment by asodja** [comment]
There was an attempt to fix that, see https://github.com/gradle/gradle/pull/29823, but it's kinda breaking change. Our Gradleception tests fail with:
```
Execution failed for task ':tasks'.
> Could not create task ':asciidoctor'.
   > Could not create task of type 'AsciidoctorTask'.
      > Could not create an instance of type org.asciidoctor.gradle.jvm.AsciidoctorJExtension.
         > Class AsciidoctorJExtension has no constructor that is annotated with @Inject.
```
