### ISSUE TITLE
user manual page not found

### ISSUE THREAD

**Issue by yinkanchn** [gradle/gradle#16937]
`https://docs.gradle.org/current/samples/sample_jvm_multi_project_build.html` is page not found.
There are problems from version 6.7 to version 7.0. version 6.6.1 is ok.
The original link location is on word `sample` on page `https://docs.gradle.org/current/userguide/migrating_from_maven.html#migmvn:multimodule_builds`

**Comment by bmuskalla** [comment]
Thanks for reporting @yinkanchn
