### ISSUE TITLE
DependencyGraphBuilder internal classes used in HashSets do not implement hashCode

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#1693]
After #1600, the next major contributor to raw resolve times appears to be classes used heavily in `HashSet`s, particularly `org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder.DependencyEdge`. They don't implement `hashCode()`, so they're falling through to the native `java.lang.Object.hashCode()`.

These classes appear to be immutable, so can implement `hashCode()` and store the result on a field an additional optimization.

### Your Environment
Gradle `master` branch.

**Comment by eriwen** [comment]
@oehme Would you please prioritize or close this?

**Comment by oehme** [comment]
@melix this is the issue we talked about on the call. If there is potential for improvement in here, let me know :)

**Comment by ljacomet** [comment]
Closing this as obsolete since much has changed in this area, both at the code and performance levels.
