### ISSUE TITLE
Incremental Task @Classpath inputs have two FileChanges of the same file

### ISSUE THREAD

**Issue by Firestar99** [gradle/gradle#16933]
All Incremental Tasks with inputs annotated with `@Classpath` or `@CompileClasspath` are potentially affected. If such a Task queries their FileChanges for these inputs the returned `Iterable<FileChange>` may contain a file twice, first `removed` and then `added` instead of just being `modified`. This is triggered by the input having a new file added (which is handled correctly) but all other files which are after this file's name alphabetically are first `removed` and then `added` right afterwards in the `Iterable`. In most implementations all the outputs of removed files are first removed and then the new files generated so that the effect isn't noticed, if the order is however reversed the effect is that an output file may be deleted which shouldn't be.

### Potentially affected tasks: 
- Incremental Tasks with inputs annotated with `@Classpath` or `@CompileClasspath`
- JavaCompile is NOT affected for some reason, may be due to extra filtering it does? (see `:failTest` task below not needing recompile).  

### Expected Behavior
Incremental Task with inputs annotated with `@Classpath` or `@CompileClasspath` have a `modified` entry of the file.

### Current Behavior
Not have of two entries `removed` then `added` of the same file. Workaround: use `@PathSensitive(PathSensitivity.RELATIVE)`.

### Context
I was using a custom Task to do code manipulation with ByteBuddy after a JavaCompile Task to either decorate the classes with additional fields or methods or to generate entirely new classes based to replace the compiled ones.

### Steps to Reproduce 
Repo: https://github.com/Firestar99/gradle-incremental-classpath-source-bug

I've made a custom minimalistic task in the `build.gradle` called `fail` which prints out any of such removed then added FileChanges. At the beginning we have the 3 source classes `Foo0`, `Foo1`, `Foo2`.

1. execute `./gradlew fail`
Output:
```
> Task :fail
non-incremental execution, try again!
```
2. remove the file `/src/main/java/Foo1.java` (or add it back)
3. execute `./gradlew fail`
Output: 
```
> Task :fail
changes added and removed: 
	Foo2.class
```

Observe that the input changes had 3 entries: first that Foo1 was removed as expected, but then that Foo2 was removed and then added, which the task detected and printed out about it. Foo0 was unaffected as it is alphabetically lower than Foo1, but Foo2 was affected due to it being higher.

Also note that the classpath property of JavaCompile is unaffected, see `:failTest` task being UP-DO-DATE. This makes multi-project builds pretty much unaffected.

### Your Environment
Ubuntu 20.04 aka Linux
Gradle 6.8 and 7.0
Build scan URL: https://scans.gradle.com/s/uif2dbm5wfgrm

**Comment by wolfs** [comment]
Great, thank you for reporting! Make sure you re-process any of the entries which have been added and removed, given that their contents may have changed as well. In your example above, if you remove `Foo1.class` and modify `Foo2.class`, you would get the same changes: `Foo1.class`: removed, `Foo2.class`: added, `Foo2.class`: removed.
