### ISSUE TITLE
maxParallelForks cannot be greater than the number of processors.

### ISSUE THREAD

**Issue by anyone-can-test** [gradle/gradle#1694]
### Expected Behavior
when maxParallelForks = 6, 6 executors are executed.

### Current Behavior
when maxParallelForks = 6, only 4 executors are executed.

### Context
I think that the limit of maxParallelForks is the number of cpus.
This machine has 4 processors.
if a machine has over 8 processors and maxParallelForks = 6, 6 executors are executed.

Any way to set maxParallelForks over the number of processors?

**Comment by eskatos** [comment]
Hi Hyunil,

`test.maxParallelForks` is caped at `max-workers`.
`max-workers` defaults to the number of processors available to the JVM.

If you want to set `test.maxParallelFork` to a value higher than your available processors you have to also set `max-workers`, either by using the `--max-workers` command line option or by setting the `org.gradle.workers.max` property.

HTH

**Comment by eriwen** [comment]
Indeed, the solution here is to set max workers as well. I think we can consider this answered. @anyone-can-test let us know if you encounter further issues.
