### ISSUE TITLE
Unresolved reference: MergedFlavor

### ISSUE THREAD

**Issue by NikolaDespotoski** [gradle/gradle#16944]
I'm developing plugin that will beside replacing resources provided from Jenkins config, it also changes the Android `applicationId` of all product flavors declared in the project (and flavors of all variants)

After upgrading to plugin 4.1.3 and gradle 6.5 I'm experiencing failure when finding `MergedFlavor` class

This the snippet that I have. 

  ```kotlin
override fun updateApplicationidFromConfig(project: Project, config: MyConfig, flavor: BaseFlavor, myExtension: MyExtension) {
        project.android.app.applicationVariants.all { variant ->
            val mergedFlavor = variant.mergedFlavor as MergedFlavor
            mergedFlavor.applicationId = config.bundleIdentifier.android
            true
        }
        config.run {
            flavor.resValue("string", "app_launcher_name", appName)
            flavor.resValue("string", "product_number", productNumber)
        }
    }
```
Although the import `import com.android.build.gradle.internal.core.MergedFlavor` is present, it can't recognize it for some reason. Is it because that it's form `.internal.core` package?
What I'm doing wrong?  How can I update applicationId alternatively?

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
