### ISSUE TITLE
Property<String> should behave more like a String property

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#16949]
When converting legacy plugins to use the Gradle provider API, a `Property<String>` behaves differently than a String property when using Groovy DSL dynamic setters *and* a provider with a type (where `ProviderInternal#getType()` is not null). For example, a String property would implicitly convert an Object to a String using `Object#toString()`. It is then valid to `stringProp = true` or `stringProp = file('foo')` both of which would convert to String without any issue.

If the type of the provider is non-null and not assignable to String (aka not a String), the `setFromAnyValue` will throw an exception. However, if you `Provider#map` which happens to erase the type (as the mapped provider doesn't hold a type), then setting the value is fine as the check is ignored. I believe this behaviour can be quite confusing for users trying to migrate their code to be Provider ready.

### Expected Behavior

`setFromAnyValue` for Provider should be more forgiving on the type matching to better reflect a non-provider property behaviour (using setter/getter instead of `Property` objects).

### Current Behavior

If the provider has a type, they need to be fully compatible even if the real providing type would be compatible. If we take a different example, setting `Foo` type in a `Property<Object>` (created as `objects.property(Object)`) would have the explicit `Object` type making it incompatible with a `Property<Foo>` event though the type inside the property is `Foo` (compatible). If you simply map the `Property<Object>` it would magically become compatible:

```
class Foo {}
abstract class Extension {
    abstract Property<Foo> getFoo()
}

def extension = objects.newInstance(Extension)
def objProperty = objects.property(Object).value(new Foo())

// extension.foo = objProperty  // throw exception because objProperty's type is Object and incompatible with Foo
extension.foo = objProperty.map { it } // works because mapped provider has no type
```

String is a more particular case as implicit conversion is possible using `Object#toString()`.

### Context

Migrating legacy Gradle code to provider API would be much easier.

**Comment by lacasseio** [comment]
Stale go away! Do not close!

**Comment by lptr** [comment]
We explicitly don't want to support auto-conversion to `String`. This is not something that happens in Kotlin DSL, and it is also not something the IDE can help with. It is also rarely the desired behavior to auto-convert things to strings.
