### ISSUE TITLE
Gradle 7.0 - Kotlin DSL - Linux - Running multi-module project stops daemon unexpectedly

### ISSUE THREAD

**Issue by Mordag** [gradle/gradle#16959]
### Expected Behavior

The build should successfully on all platform. It is running fine on Windows and MacOS.

### Current Behavior

When running a Gradle 7.0 multi-module (Android) project written with Kotlin DSL on Linux, the daemon will stop unexpectedly without providing the actual root cause of the issue.

This is the relevant part in the logs:

> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
> 2021-04-22T16:12:06.832-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:249)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:222)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:184)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:147)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:98)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:212)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:275)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:247)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:92)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:38)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:240)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.Main.doAction(Main.java:35)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.lang.reflect.Method.invoke(Method.java:497)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.GradleMain.main(GradleMain.java:31)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.lang.reflect.Method.invoke(Method.java:497)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
> 2021-04-22T16:12:06.833-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org

The log mentions that the build has an error but the only reference of an error is the following single line:

> 2021-04-22T16:12:06.815-0700 [DEBUG] [org.gradle.internal.remote.internal.inet.SocketConnection] Discarding EOFException: java.io.EOFException

I have been able to reproduce this issue on multiple machines running Linux. All machines were using Java 8.

### Context
The project is using Gradle 7.0 and the build scripts are written in Kotlin DSL.

I will try to provide an example project sometime in the next 1-2 weeks which demonstrates this issue.

**Comment by ljacomet** [comment]
Can you check if this works on Gradle 6.8.3?

**Comment by Mordag** [comment]
Yep Gradle 6.8.3 works fine for Linux.

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem I'll close this for now. If you happen to be able to share more information, please let me know and I can reopen the issue.
