### ISSUE TITLE
Version catalogs should work in buildscript dependencies

### ISSUE THREAD

**Issue by swankjesse** [gradle/gradle#16958]
This was previously reported as [part 2 of Issue 16652](https://github.com/gradle/gradle/issues/16652).

### Expected Behavior

I expect centralized dependency versions to work everywhere I specify dependencies. This includes my `buildscript` clause.

In `myproject/settings.gradle.kts`:

```
enableFeaturePreview("VERSION_CATALOGS")
...
```

In `myproject/gradle/libs.versions.toml`:

```
[libraries]
shadowJarPlugin = "com.github.jengelman.gradle.plugins:shadow:6.1.0"
```

In `myproject/build.gradle.kts`:

```
buildscript {
  dependencies {
    classpath(libs.shadowJarPlugin)
  }
}
...
```

### Current Behavior

```
> Configure project :
e: /Users/jwilson/Development/myproject/build.gradle.kts:20:15: Unresolved reference: libs
```

### Context

I’m using Gradle 7.

### Workaround

This is a workaround. It is verbose, doesn’t have IDE support, and is inconsistent with my other dependencies blocks.

```
buildscript {
  fun libs(lib: String): String {
    val versionCatalog = project.extensions.getByType(VersionCatalogsExtension::class).named("libs")
    val dep = versionCatalog.findDependency(lib).get().get()
    return "${dep.module.group}:${dep.module.name}:${dep.versionConstraint.displayName}"
  }

  dependencies {
    classpath(libs("shadowJarPlugin"))
  }
}
```

**Comment by PaulWoitaschek** [comment]
@swankjesse 
Better workaround that allows for typesafely accessing the versions:
```kotlin
buildscript {
  repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
  }
  dependencies {
    val libs = project.extensions.getByType<VersionCatalogsExtension>().named("libs") as org.gradle.accessors.dm.LibrariesForLibs
    classpath(libs.sqlDelight.gradlePlugin)
  }
}

```

**Comment by tpodg** [comment]
I have a similar problem, but in a different place. I tried to define dependencies from service catalog for sub-projects and it does not work either. 

Example:
```
subprojects {
   dependencies {
      implementation(libs.abc)
   }
}
```

Extension with name 'libs' does not exist. Currently registered extension names: ...

**Comment by rock3r** [comment]
> I have a similar problem, but in a different place. I tried to define dependencies from service catalog for sub-projects and it does not work either.
> 
> Example:
> 
> ```
> subprojects {
>    dependencies {
>       implementation(libs.abc)
>    }
> }
> ```
> 
> Extension with name 'libs' does not exist. Currently registered extension names: ...

Looks like you're having [this](https://github.com/gradle/gradle/issues/16634) issue, which is unrelated

**Comment by piyush-kukadiya** [comment]
@swankjesse Is this feature `VERSION CATALOG` supported by Android Studio? I tried it but autocomplete ain't working.

**Comment by jeffdcamp** [comment]
What version of Gradle should this fix show up in?  (I just tested Gradle 7.1 and this seems to still be broken)

**Comment by krzdabrowski** [comment]
I just tested it too with 7.1 and it doesn't work yet. I guess it was fixed too late to come into 7.1. Hopefully it will be included in next release.

**Comment by konnovdev** [comment]
Paul's answer in Groovy
```
        def libs = project.extensions.getByType(VersionCatalogsExtension).named("libs") as org.gradle.accessors.dm.LibrariesForLibs
        classpath(libs.gradlePluginHiltAndroid)
```

**Comment by Maragues** [comment]
On Gradle 8.5, the solutions above didn't work. In Groovy, this is working

```groovy
buildscript {
    dependencies {
        def libs = project.extensions.getByType(VersionCatalogsExtension).named("libs")

        classpath(libs.findLibrary("myPlugin").get())
    }
}
```

`libs` can't be casted to `org.gradle.accessors.dm.LibrariesForLibs`. The type is `org.gradle.api.internal.catalog.VersionCatalogView`, which exposes `findXX` functions that return `Optional`.

**Comment by RuslanKuziak** [comment]
I had a problem accessing Version Catalog dependency from my Groovy `build.gradle` file.

Used the following syntax to 'fix' it:

```
buildscript {
        dependencies {
            classpath "${libs.plugins.your.awesome.plugin.get()}"
        }
    }
```

`get()` simply returns a full String version of your dependency. In my case, I can use it normally in `classpath`.
