### ISSUE TITLE
IntelliJ sync keeps trying to download library-sources.source.asc

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#16956]
Whenever there are new dependencies in `gradle/gradle`, the IntelliJ sync spends a ton of time trying to download `library-sources.source.asc`. These files don't exist and I don't understand what is making Gradle look for them. It seems to be related to dependency verification. I would expect it to look for `library-sources.jar.asc`, but not for `library-sources.source.asc`. 

The source artifact is a jar file not a ".source" file. See for example Guava on what the file names to look for should be: https://repo.maven.apache.org/maven2/com/google/guava/guava/30.1.1-jre/

**Comment by melix** [comment]
I could confirm the same behavior today. This is clearly a bug in the way dependency verification handles classified artifacts.
