### ISSUE TITLE
Allow Provider properties for ComponentMetadataRule

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#16963]
### Expected Behavior

ComponentMetadataRule should be able to receive `Provider<T>` arguments.
The provider should be queried at `.get()` time

### Current Behavior

Gradle freezes the provider at `withModule<...>(...)` time, so `Provider<String>` is not different from a regular `String`
The workaround is to use inline `withModule(...) { withVariants(...`.

Sample:

`./gradlew dependencies --configuration testRuntimeClasspath`

```kotlin
class AddCommonsText @Inject constructor(
    val commonsTextVersion : Provider<String>
) : ComponentMetadataRule {
    override fun execute(context: ComponentMetadataContext) {
        context.details.withVariant("runtime") {
            withDependencies {
                add("org.apache.commons:commons-text:${commonsTextVersion.get()}")
            }
        }
    }
}

val commonsTextVersion = objects.property<String>()

dependencies {
    components {
        withModule<AddCommonsText>("junit:junit") {
            params(commonsTextVersion) // <-- it looks like Gradle freezes property value here :(
        }
    }
}

 // I want the end users to configure the property
commonsTextVersion.set("43")

dependencies {
    testImplementation("junit:junit")
}
```

```
org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this property because it has no value available.
    at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:86)
    at Build_gradle$AddCommonsText$execute$1$1.execute(build.gradle.kts:26)
    at Build_gradle$AddCommonsText$execute$1$1.execute(build.gradle.kts:20)
    at org.gradle.internal.component.external.model.VariantMetadataRules$VariantAction.maybeExecute(VariantMetadataRules.java:177)
    at org.gradle.internal.component.model.DependencyMetadataRules.executeDependencyRules(DependencyMetadataRules.java:85)
    at org.gradle.internal.component.model.DependencyMetadataRules.execute(DependencyMetadataRules.java:77)
    at org.gradle.internal.component.external.model.VariantMetadataRules.applyDependencyMetadataRules(VariantMetadataRules.java:86)
    at org.gradle.internal.component.external.model.DefaultConfigurationMetadata.getDependencies(DefaultConfigurationMetadata.java:134)
```

### Context

I prepare a `ComponentMetadataRule` for `allure-gradle` so Allure dependencies are automatically added in case test engine is present. However, I want `allure` version to be declared as a `Property`.

**Comment by vlsi** [comment]
> If this is in a plugin, I would define both – component metadata rule and constraint – in the plugin.

I can't add constraints since I don't know the configuration names where the original dependency is declared.
The metadata rule enabled me to adjust "junit" dependency in all the places user declares it :)

I do not expect much dynamism there, however, I would still like to use `Property<...>` for version of the added dependency.

**Comment by vlsi** [comment]
Here's the use-case for the end users: https://github.com/allure-framework/allure-java implement multiple adapters for different dependencies to capture extra data from the test executions.
For instance, `allure-junit5` adds JUnit5 listener which captures JUnit5 test executions, and creates an execution log file for building Allure report.

Of course, users might add "junit5" adapters manually, however, it might be slightly better to provide a DSL for it:


```kotlin
allure {
    gather {
        adapters {
            junit5 // activate junit5 integration, so the relevant allure-junit5 dependency is automatically added
        }
    }
}
```

I'm not sure if the use of ComponentMetadataRule is abuse here, however, it seems to be pretty much in line: "every time user has junit5 dependency, allure-junit5 should be added as well". At the same time, I do not know if the user has custom sourceSets, and I do not want to hard-code configuration names like `testRuntimeOnly`.

**Comment by vlsi** [comment]
I think this is still relevant

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
We're not convinced this is a valid pattern we want to support.

It looks like we're isolating the parameters earlier than we could. We could make this more dynamic, but component metadata rules are usually used for making static changes.  Making this more lazy/dynamic would make caching more complicated.  We would need a few more examples of how this feature would be useful relative to other ways of accomplishing something similar.

If you can be more specific or have more examples, feel free to open a new issue and link to this one.
