### ISSUE TITLE
DefaultAntBuilder always uses script directory as basedir

### ISSUE THREAD

**Issue by klaraward** [gradle/gradle#1698]
DefaultAntBuilder always uses script directory as basedir
See also https://issues.gradle.org/browse/GRADLE-2039

### Expected Behavior
basedir value defined in ant script is used

### Current Behavior
basedir is always set to script directory

### Context
When importing an ant script from gradle
### Steps to Reproduce (for bugs)
build.gradle
```
ant.importBuild 'build.ant'
```

build.ant
```
<?xml version="1.0" encoding="UTF-8"?>
<project name="docker" default="images" basedir="../..">
  <echo message="${basedir}"/>
<target name="foo"/>
</project>
```

gradlew foo
Excpect to see the directory two levels up from the script directory.

### Your Environment
MacOSX

**Comment by mjorive** [comment]
I'm new working with Gradle... sorry in advance 

Originally I had a java project and I used ANT to compile and build .jar file. In this project we used some Ant Tasks created by our developers to create code dinamically.
These tasks use log4j to log its process and do some other operations with files...
- In the .xml used to configure log4j the path to log files is specified as a relative path.
- When executed logs are created inside "working directory" using the relative path.

I've created the build.gradle which reproduces the operations done in the old build.xml.
I'm not importing a build.xml but defining the tasks in my build.gradle.

From command line, located in the same directory of build.gradle we invoke **gradlew build** and everything works fine.

I've imported my Gradle in Eclipse and tried to invoke build task.
Problem is that the Ant Task are executed using as working directory Eclipse root; so my logs get created in an unespected path and tasks don't find configured files...

**From Console output:**
```
Working Directory: C:\java\localWork\monorepos.eclipseworkspace\git\project-java
Gradle User Home: C:\Users\mjorive\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 4.7
Java Home: C:\java\jdk1.8.0_77
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: build
```
```
> Configure project :
Root project:   root project 'project-java'
  rootDir:      C:\java\localWork\monorepos.eclipseworkspace\git\project-java
  projectDir:   C:\java\localWork\monorepos.eclipseworkspace\git\project-java
  user.dir:  C:\java\eclipse-jee-oxygen-3a-win32-x86_64\eclipse
```
If I'm not undestanding wrong, my problem is the same as the one discussed here.

Any news or workarounds (other than execute those tasks from command line, of course ;) )

**Comment by kejn** [comment]
I have an idea for fixing this issue. My idea is to extend the `org.gradle.api.AntBuilder` with 2 new abstract methods, which will be simply overloading the existing `importBuild()` methods, allowing to explicitly specify the *baseDirectory* for the imported Ant tasks. This change will also require to add new implementations in `org.gradle.api.internal.project.ant.BasicAntBuilder` and `org.gradle.api.internal.project.DefaultAntBuilder`.

I already prepared the necessary code adjustments. They are posted below. Please let me know if you would rather like to review them in a pull request, or if I should create the pull request only after the review of changes.

----
**AntBuilder.java**
```diff
--- a/subprojects/core-api/src/main/java/org/gradle/api/AntBuilder.java
+++ b/subprojects/core-api/src/main/java/org/gradle/api/AntBuilder.java
@@ -57,7 +57,37 @@ public abstract class AntBuilder extends groovy.util.AntBuilder {
      */
     @Incubating
     public abstract void importBuild(Object antBuildFile, Transformer<? extends String, ? super String> taskNamer);
-
+
+    /**
+     * Imports an Ant build into the associated Gradle project, specifying the base directory for Gradle tasks that correspond to Ant targets.
+     * <p>
+     * By default the base directory is the Ant build file parent directory. The relative paths are relative to {@link Project#getProjectDir()}.
+     * <p>
+     * For each Ant target that is to be converted to a Gradle task, the given {@code taskNamer} receives the Ant target name as input
+     * and is expected to return the desired name for the corresponding Gradle task.
+     * The transformer may be called multiple times with the same input.
+     * Implementations should ensure uniqueness of the return value for a distinct input.
+     * That is, no two inputs should yield the same return value.
+     *
+     * @param antBuildFile The build file. This is resolved as per {@link Project#file(Object)}.
+     * @param baseDirectory The base directory. This is resolved as per {@link Project#file(Object)}.
+     */
+    @Incubating
+    public abstract void importBuild(Object antBuildFile, Object baseDirectory);
+
+   /**
+    * Imports an Ant build into the associated Gradle project, specifying the base directory and potentially providing alternative names
+    * for Gradle tasks that correspond to Ant targets.
+    * <p>
+    * By default the base directory is the Ant build file parent directory. The relative paths are relative to {@link Project#getProjectDir()}.
+    *
+    * @param antBuildFile The build file. This is resolved as per {@link Project#file(Object)}.
+    * @param baseDirectory The base directory. This is resolved as per {@link Project#file(Object)}.
+    * @param taskNamer A transformer that calculates the name of the Gradle task for a corresponding Ant target.
+    */
+    @Incubating
+    public abstract void importBuild(Object antBuildFile, Object baseDirectory, Transformer<? extends String, ? super String> taskNamer);
+
     /**
      * Returns this AntBuilder. Useful when you need to pass this builder to methods from within closures.
      * @return this

```
----
**BasicAntBuilder.java**
```diff
--- a/subprojects/core/src/main/java/org/gradle/api/internal/project/ant/BasicAntBuilder.java
+++ b/subprojects/core/src/main/java/org/gradle/api/internal/project/ant/BasicAntBuilder.java
@@ -62,13 +62,25 @@ public class BasicAntBuilder extends org.gradle.api.AntBuilder implements Closea
         throw new UnsupportedOperationException();
     }

+    @Override
     public void importBuild(Object antBuildFile) {
         throw new UnsupportedOperationException();
     }

+    @Override
     public void importBuild(Object antBuildFile, Transformer<? extends String, ? super String> taskNamer) {
         throw new UnsupportedOperationException();
     }
+
+    @Override
+    public void importBuild(Object antBuildFile, Object baseDirectory) {
+        throw new UnsupportedOperationException();
+    }
+
+    @Override
+    public void importBuild(Object antBuildFile, Object baseDirectory, Transformer<? extends String, ? super String> taskNamer) {
+        throw new UnsupportedOperationException();
+    }

     @Override
     protected void nodeCompleted(Object parent, Object node) {

```
----
**DefaultAntBuilder.java**
```diff
--- a/subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultAntBuilder.java
+++ b/subprojects/core/src/main/java/org/gradle/api/internal/project/DefaultAntBuilder.java
@@ -89,14 +92,28 @@ public class DefaultAntBuilder extends BasicAntBuilder implements GroovyObject {
         return castMap;
     }

+    @Override
     public void importBuild(Object antBuildFile) {
         importBuild(antBuildFile, Transformers.<String>noOpTransformer());
     }
-
+
+    @Override
+    public void importBuild(Object antBuildFile, Object baseDirectory) {
+       importBuild(antBuildFile, baseDirectory, Transformers.<String>noOpTransformer());
+    }
+
+    @Override
     public void importBuild(Object antBuildFile, Transformer<? extends String, ? super String> taskNamer) {
-        File file = gradleProject.file(antBuildFile);
-        final File baseDir = file.getParentFile();
+       importBuild(antBuildFile, null, taskNamer);
+    }

+    @Override
+    public void importBuild(Object antBuildFile, Object baseDirectory, Transformer<? extends String, ? super String> taskNamer) {
+        File file = gradleProject.file(antBuildFile);
+
+        Optional<Object> baseDirectoryOptional = Optional.ofNullable(baseDirectory);
+        File baseDir = gradleProject.file(baseDirectoryOptional.orElse(file.getParentFile().getAbsolutePath()));
+
         Set<String> existingAntTargets = new HashSet<String>(getAntProject().getTargets().keySet());
         File oldBaseDir = getAntProject().getBaseDir();
         getAntProject().setBaseDir(baseDir);

```

**Comment by kejn** [comment]
Hi @oehme, please see my solution proposal above.

**Comment by qradimir** [comment]
Any plans to fix this?

**Comment by kejn** [comment]
@qrdimir I'll create PR soon, let's see if it is accepted

**Comment by cogonide** [comment]
@kejn Was your PR ever merged and the issue just not referenced here?

**Comment by omerfarman2** [comment]
* text eol=lf

#
# The above will handle all files NOT found below
# https://help.github.com/articles/dealing-with-line-endings/
# https://github.com/Danimoth/gitattributes

# These are explicitly windows files and should use crlf
*.bat           text eol=crlf

# These files are text and should be normalized (Convert crlf => lf)
*.bash          text eol=lf
*.css           text diff=css
*.htm           text diff=html
*.html          text diff=html
*.java          text diff=java
*.sh            text eol=lf


# These files are binary and should be left untouched
# (binary is a macro for -text -diff)
*.a             binary
*.lib           binary
*.icns          binary
*.png           binary
*.jpg           binary
*.jpeg          binary
*.gif           binary
*.ico           binary
*.mov           binary
*.mp4           binary
*.mp3           binary
*.flv           binary
*.fla           binary
*.swf           binary
*.gz            binary
*.zip           binary
*.jar           binary
*.tar           binary
*.tar.gz        binary
*.7z            binary
*.ttf           binary
*.pyc           binary
*.gpg           binary
*.bin           binary
