### ISSUE TITLE
Change default configuration for buildSrc project jar tasks

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#16981]
Change default configuration for buildSrc project jar tasks. Today, adding the following to `buildSrc/build.gradle.kts`: 
```
tasks.withType(Jar::class.java) {
	println("isReproducibleFileOrder: ${isReproducibleFileOrder()} \nisPreserveFileTimestamps: ${isPreserveFileTimestamps}")
}
```

### Expected Behavior
isReproducibleFileOrder is true and isPreserveFileTimestamps is false

### Current Behavior
```
isReproducibleFileOrder: false 
isPreserveFileTimestamps: true
```

This means buildSrc jars do not use reproducible order and they keep timestamps, both of which negatively impact incrementality and reproducibility.

### Context
We are manually overriding these values in our build, we'd like that to be the default behavior as it is a general win.

### Steps to Reproduce 
See above

### Your Environment
N/A

**Comment by wolfs** [comment]
How do `buildSrc` JARs with non-deterministic order and timestamps influence incrementality? When Gradle uses those JARs then they will be normalized so that timestamps and order are ignored.

**Comment by wolfs** [comment]
I'll close this now since there hasn't been any more activity.
