### ISSUE TITLE
Show previous warnings when a task doesn't need to rerun

### ISSUE THREAD

**Issue by KotlinIsland** [gradle/gradle#16984]
So if a task outputs warnings and then the build is rerun, the warning does not show because the task doesn't need to rerun.
But guess what, the warning is still in the code :flushed:.

given:
```kt
package main

fun main() {
    1
}
```

When build is invoked(twice):
```
>gradlew :jvm:build
Type-safe project accessors is an incubating feature.

> Task :jvm:compileKotlin
w: C:\...\jvm\src\main\kotlin\main\foo.kt: (4, 5): The expression is unused

BUILD SUCCESSFUL in 12s
3 actionable tasks: 3 executed

>gradlew :jvm:build
Type-safe project accessors is an incubating feature.

BUILD SUCCESSFUL in 6s
3 actionable tasks: 3 up-to-date
```
### Expected Behavior
I would think that if the warning is still valid then Gradle should re show the warning, even if that task doesn't re run.

### Current Behavior
Hidden warnings :pensive:

### Context
This totally affected me because I thought that my code was valid, but wasn't :astonished:

Also I was like "why aren't these warnings showing? do I have the wrong logging options set?" and wasted a bunch of time messing with logging options, only to realize that gradle wasn't running that task and wasn't showing the warnings 🙄

**Comment by KotlinIsland** [comment]
I think you misunderstood my point, I don't want to output errors and the kotlin configuration is not the issue.

The issue is that when a task logs warnings and is then re-run, the output doesn't reflect the REAL state of the build.

In my opinion, Gradle should remember the warnings that were logged by tasks, and when the task is skipped on subsequent runs, the saved warnings should be shown in the build log.

The current behaviour is misleading.

**Comment by myarcana** [comment]
@bmuskalla  With current gradle behaviour, how can an annotation processor log something (but not an error) on every single `gradle test` even if that task doesn't need to rerun?

KotlinIsland's feature request provides the obvious solution to this (also was my expected behaviour), but maybe there currently exists a good workaround for my specific case (annotation processors).

**Comment by myarcana** [comment]
I agree.

If I ask gradle to run a task, I would expect to see that task's output every time. If gradle isn't going to show me that task's output, it should make that clear to me so I am not misled.

So, if current behaviour is kept, it should at least not say "BUILD SUCCEEDED"; it should say "not running task (already up-to-date)" or some equivalent

**Comment by leonard84** [comment]
@myarcana you can run with `--console=plain` ([Customizing log format](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_customizing_log_format)) if you want to see the individual outcomes of the task.
