### ISSUE TITLE
CachingDirectedGraphWalker NPE and wrong results on particular inputs.

### ISSUE THREAD

**Issue by vprotasov** [gradle/gradle#16999]
I have found 3 serious problems while running CachingDirectedGraphWalker with my 10K nodes input: 

1) NPE when calling CachingDirectedGraphWalker.findValues()
in .doSearch(CachingDirectedGraphWalker.java:158)
https://github.com/gradle/gradle/blob/master/subprojects/base-services/src/main/java/org/gradle/internal/graph/CachingDirectedGraphWalker.java

2) It does not find correctly all Strongly Connected Components with particular test input which has one cycle but cycle length is different for different start nodes, tested against Tarjan classic implementation.

As result It does not correctly find transitive dependencies for particular inputs - some are missing while there is clearly a path from the source node to the missing dependency.

https://github.com/vprotasov/gradle_caching_directed_graph_walker_bug_report

**Comment by bmuskalla** [comment]
While looking into this, may I ask what you're using this for? Be aware that CachingDirectedGraphWalker is internal (and not API). Do you see these problems also when using it through public APIs?

**Comment by vprotasov** [comment]
Hi,

I am not using CachingDirectedGraphWalker in production, but I was trying
to use it to validate my code which implements Gradle interview challenge.

Cheers,
Vlad

**Comment by bmuskalla** [comment]
Closing this for now as there is no user-facing problem with this. If you encounter this without reaching into internals, please let me know and we can reopen the issue.
