### ISSUE TITLE
Deadlock when task outputs are calculated from input configuration

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#17013]
In attempting to refactor the `ProGuard` plugin to better track all task inputs, I encountered an unexpected deadlock. I've created a small reproducer that shows that this issue will occur whenever calculating the task outputs involves resolving an input `Configuration`.

### Background
In order to track all inputs to the `ProGuardTask`, it was necessary to build a complete `proguard.Configuration` instance out of any provided Proguard configuration files as well as any input/output jars configured programmatically in Gradle. I then wrapped this `proguard.Configuration` instance in a `@Nested` task property that represents all of the task inputs and outputs. You can see the main part of the refactoring here: https://github.com/Guardsquare/proguard/commit/b5fbefb87cc44d20e10042df7c00cd73cdcf3280.

This worked well in testing, but when trialled in a real-world project a deadlock was seen. [This gist](https://gist.github.com/bigdaz/56c3658a280a76c39d6cd736bbd6dfc1) shows a thread-dump with the most relevant threads at the time of deadlock.

### Expected Behavior
Resolve an input configuration to determine task outputs should be permitted (and succeed), or it should be prohibited and fail. Deadlocks are very difficult to diagnose and debug.

### Current Behavior
Gradle will deadlock when attempting to inspect the Task outputs.

### Context
This is a true JVM-level deadlock, where 1 thread holds a synchronization lock, and this thread spawns another thread that is blocked waiting on the same lock.

Here's what happens:
1. `DefaultPlanExecutor.executeNextNode` locks the `ResourceLockCoordinationService` while attempting to find the next task to execute.
2. While this lock is held, `DefaultExecutionPlan.selectNext()` is called, which iterates over available tasks to see if any can be executed.
3. Part of determining if a task can be executed involves resolving the output property values. In this case, calculating the output property value involves resolving files for a dependency configuration.
4. If the dependency configuration resolves to multiple files, we attempt to download these in parallel, in separate threads.
5. Each thread needs to acquire a worker lease, and to get this lease it needs to use the `ResourceLockCoordinationService`
6. The `ResourceLockCoordinationService` is still locked by the main `executeNextNode` thread, and deadlock ensues.

### Steps to Reproduce 

Clone this repository and follow the instructions in `README.md`: https://github.com/bigdaz/gradle-outputdeadlock

**Comment by bigdaz** [comment]
I was why I couldn't get a similar deadlock from an `@InputFiles` property that resolved a configuration in it's implementation: it turns out that we only unpack the value of _outputs_ when we are selecting the next task to execute. Unpacking of _inputs_ doesn't happen until we actually enter the execution pipeline, and after the `ResourceLockCoordinator` is released.

So `GetOutputFilesVisitor.visitOutputFileProperty` ends up calling `PropertyValue.getUnprocessedValue()`, but `GetInputFilesVisitor.visitInputFileProperty` does not.

**Comment by tjni** [comment]
I believe I am running into this in a build at work and need some guidance.

Has there been a design discussion already about how to fix this, leaving only the work to be done (in which case I can help contribute), or does that need to happen?

**Comment by oppih0** [comment]
Out of my curiosity, any update on this issue?

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/20141
