### ISSUE TITLE
consider publishing gradle-ide-3.x.jar in artifact repository

### ISSUE THREAD

**Issue by greensopinion** [gradle/gradle#1701]
I'm interested in extending the functionality of the Eclipse IDE plugin, which can be found in a Gradle installation in the plugins folder, e.g. `${gradle.home}/lib/plugins/gradle-ide-3.3.jar`

From the package naming, it looks like the plugin is designed for extension (i.e. there is a distinction between internal and API classes)
The sources for this plugin are at [subprojects/ide](https://github.com/gradle/gradle/tree/master/subprojects/ide)

Plugin developers can consume most Gradle dependencies from Artifactory, e.g. https://repo.gradle.org/gradle/libs-releases-local/ however from what I can gather Gradle plugins are not available there.  Poking around https://jcenter.bintray.com/org/gradle/ I can't seem to find the ide plugins either.

Would it be possible to publish gradle-ide-x.x.jar in Artifactory along with the rest of Gradle?  This would facilitate extensions and code reuse.

**Comment by greensopinion** [comment]
In case it helps, this is what I'm working on: https://github.com/greensopinion/gradle-android-eclipse

**Comment by eriwen** [comment]
Thanks for the note and context @greensopinion. I know we discussed this a few times, and I need to remind myself why we haven't done this.

**Comment by greensopinion** [comment]
Thanks for the quick response.  Is there anything that I can do to help move this forward?

**Comment by bmuschko** [comment]
@greensopinion Is there a specific reason for _not) using `gradleApi()` to reference the IDE classes when writing the plugin? That's what I would do.

**Comment by greensopinion** [comment]
All of the examples of `gradleApi()` that I've seen are groovy-based.  Is there a way to make this work with plugins implemented in Java?

**Comment by bmuschko** [comment]
@greensopinion The Gradle API _is_ written in Java. You should be able to implement the same logic as part of a Java-based plugin. Except maybe for some exceptions it should work as is. Can you give me an example?

**Comment by greensopinion** [comment]
@bmuschko sure, 

see the FIXME in the pom here: https://github.com/greensopinion/gradle-android-eclipse/blob/master/pom.xml

you can see how the classes are referenced here:  
https://github.com/greensopinion/gradle-android-eclipse/blob/master/src/main/java/com/greensopinion/gradle/android/eclipse/AndroidSdkLibraryDependenciesAction.java
https://github.com/greensopinion/gradle-android-eclipse/blob/master/src/main/java/com/greensopinion/gradle/android/eclipse/GenerateLibraryDependenciesAction.java

what am I missing?

**Comment by bmuschko** [comment]
Oh, you are building the Gradle plugin with Maven. Why did you decide to go with Maven here and not with Gradle?

**Comment by greensopinion** [comment]
> Why did you decide to go with Maven here and not with Gradle?

Primarily familiarity.

**Comment by bmuschko** [comment]
OK, I'd go with Gradle and use the `gradleApi()` dependency. If you want to stick with Maven then there's no way to implement the functionality without use publishing the JAR file first. I'd encourage you to go with Gradle all the way.

**Comment by greensopinion** [comment]
That's fair, I'll switch to a Gradle-based build.  Feel free to close this as won't fix.

Thanks so much for your help.

**Comment by bmuschko** [comment]
Sounds good. Let us know if you need further assistance.

**Comment by greensopinion** [comment]
Well that was pretty painless!  

If anyone's interested, I replaced the Maven build with this Gradle build script: https://github.com/greensopinion/gradle-android-eclipse/blob/master/build.gradle

**Comment by bmuschko** [comment]
> If anyone's interested, I replaced the Maven build with this Gradle build script.
Small comment about your code. The [Eclipse plugin configuration](https://github.com/greensopinion/gradle-android-eclipse/blob/master/build.gradle#L25-L30) you have in there is not required. All of the values you set are defaults (please see relevant Javadocs).

**Comment by greensopinion** [comment]
Thanks for the tip!
