### ISSUE TITLE
When I comment out the non-incremental processor and need to delete the build folder to make another incremental processor take effect again.

### ISSUE THREAD

**Issue by fanmingyi** [gradle/gradle#17034]
My English is not good, so the expression is not very clear.

https://github.com/fanmingyi/bugAptIncremental

My project has an incremental processor `dagger` and a non-incremental processor `arouter`. 

When I only use dagger, the annotation processor increment is normal.
Every time the relevant files are changed AnnotateStudy/app/build/generated/source/kapt will change accordingly, instead of deleting the entire folder.

```groovy

implementation 'com.google.dagger:dagger:2.35.1'
kapt 'com.google.dagger:dagger-compiler:2.35.1'

implementation 'com.alibaba:arouter-api:1.5.1'
//Use only the dagger
//kapt 'com.alibaba:arouter-compiler:1.5.1'

```

When I use the two together, the annotation processor increment is invalid(All the files in the `app/build/generated/source/kapt` folder will be generated when the current relevant code changes).

```groovy

implementation 'com.google.dagger:dagger:2.35.1'
kapt 'com.google.dagger:dagger-compiler:2.35.1'

implementation 'com.alibaba:arouter-api:1.5.1'

kapt 'com.alibaba:arouter-compiler:1.5.1'

```

```kotlin
//arouter
@Route(path = "/test/my")
class MainActivity : AppCompatActivity() {
  
}
```

```java
//dagger
@Component
interface MyCom {
}


//Comment out  @Component  below and recompile, and then check the changes in the app/build/generated/source/kapt folder
@Component
interface MyCom2 {

}
```

When I Comment out  the `kapt 'com.alibaba:arouter-compiler:1.5.1'`, the annotation processor increment still fails(Modifying the relevant code will regenerate all classes).

```groovy

implementation 'com.google.dagger:dagger:2.35.1'
kapt 'com.google.dagger:dagger-compiler:2.35.1'

implementation 'com.alibaba:arouter-api:1.5.1'
//Comment the code below,
//kapt 'com.alibaba:arouter-compiler:1.5.1'

```

When I deleted the app/build folder, the increment of the dagger annotation processor was successful again.

I think some cache of the build folder under gradle is causing this problem.

**Comment by fanmingyi** [comment]
When I comment out the non-incremental processor and need to delete the build folder to make another incremental processor take effect again.

**Comment by bmuskalla** [comment]
@fanmingyi Has your problem been fixed by using an `aggregating` processor instead of an isolated one as suggested in your linked PR?

**Comment by fanmingyi** [comment]
You can write a non-incremental annotation processor combined with dagger test, and then make the non-incremental annotation processor incremental to reproduce this problem.
