### ISSUE TITLE
eachFile in Sync task is does not handle up to date checks properly

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#17031]
With a `Sync` task, I basically changed:

```kotlin
// 1
task.eachFile { fileCopyDetails ->
    fileCopyDetails.name = "$subprojectId${fileCopyDetails.name}"
}
```

to 

```kotlin
// 2 
task.eachFile { fileCopyDetails ->
    fileCopyDetails.name = "$subprojectId-${fileCopyDetails.name}"
}
```

I had already ran the task, and realized that I forgot the `-` so my files were named `subprojectIdclasses.jar` instead of `subprojectId-classes.jar`.

Obviously this is super tricky to make reliably incremental

using `7.0-milestone-2`

**Comment by ZakTaccardi** [comment]
might be a duplicate of https://github.com/gradle/gradle/issues/1191

**Comment by bmuskalla** [comment]
Marked as dup of #1191
