### ISSUE TITLE
gradle build failed

### ISSUE THREAD

**Issue by Rimsha-Razzaq** [gradle/gradle#17038]
Build file 'F:\MusicPlayer\build.gradle' line: 28

Could not compile build file 'F:\MusicPlayer\build.gradle'.
 What went wrong:
Could not compile build file 'F:\MusicPlayer\build.gradle'.
> startup failed:
  build file 'F:\MusicPlayer\build.gradle': 28: only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on discuss.gradle.org or stackoverflow.com where to get answers by the community of Gradle users.
