### ISSUE TITLE
Follow up on JavaExecHandleBuilder.setMain(String) deprecation with third-party plugins

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#17048]
The deprecation of `JavaExecHandleBuilder.setMain(String)` broke the following smoke tests:

- `AsciidoctorPluginSmokeTest.asciidoctor plugin #version`
- `FreefairAspectJPluginSmokeTest.freefair aspectj plugin`
- `GrettySmokeTest.run with jetty`

We should follow up with the respective plugin authors as necessary, and add a link to the issue where fixing the deprecation is tracked:

- [x] Asciidoctor plugin
- [x] Freefair AspectJ plugin
- [x] Gertty plugin

See https://github.com/gradle/gradle/pull/17044 for details on why the deprecations were not detected earlier.

**Comment by rieske** [comment]
I notified and updated the following as the smoke tests did fail while I was doing the deprecations:
AspectJ: https://github.com/freefair/gradle-plugins/pull/325
and
Gretty: https://github.com/gretty-gradle-plugin/gretty/pull/221#issuecomment-818119880

**Comment by lptr** [comment]
Thanks, I added links to those issues in #17044. We only miss a followup for Asciidoctor now.

**Comment by rieske** [comment]
Asciidoctor issue: https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/602

**Comment by lptr** [comment]
I think everything is followed up on here, let's close the issue.

**Comment by lptr** [comment]
Thanks @rieske.
