### ISSUE TITLE
Follow up on Report.enabled deprecation with third-party plugins

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#17049]
The deprecation of `Report.enabled` broke the following smoke tests:

- `NebulaPluginsSmokeTest.nebula plugin plugin`

We should follow up with the respective plugin authors as necessary, and add a link to the issue where fixing the deprecation is tracked:

- [x] Nebula plugin plugin

See https://github.com/gradle/gradle/pull/17044 for details on why the deprecations were not detected earlier.

**Comment by rieske** [comment]
https://github.com/nebula-plugins/nebula-plugin-plugin/pull/66

**Comment by lptr** [comment]
Thanks, I've linked to the issue in #17044.
