### ISSUE TITLE
Gradle's publish task has an implicit dependency on signing task

### ISSUE THREAD

**Issue by gabrielittner** [gradle/gradle#17043]
### Expected Behavior

No warnings are printed when publishing a signed publication

### Current Behavior

```
> Task :signMetadataPublication
Execution optimizations have been disabled for task ':signMetadataPublication' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/gabriel/Downloads/maven-publish/build/libs/maven-publish-metadata-1.0.0-sources.jar.asc'. Reason: Task ':publishKotlinMultiplatformPublicationToMavenLocal' uses this output of task ':signMetadataPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gabriel/Downloads/maven-publish/build/libs/maven-publish-metadata-1.0.0.jar.asc'. Reason: Task ':publishKotlinMultiplatformPublicationToMavenLocal' uses this output of task ':signMetadataPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :publishMetadataPublicationToMavenLocal
Execution optimizations have been disabled for task ':publishMetadataPublicationToMavenLocal' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/gabriel/Downloads/maven-publish/build/libs/maven-publish-metadata-1.0.0-sources.jar.asc'. Reason: Task ':publishMetadataPublicationToMavenLocal' uses this output of task ':signKotlinMultiplatformPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/gabriel/Downloads/maven-publish/build/libs/maven-publish-metadata-1.0.0.jar.asc'. Reason: Task ':publishMetadataPublicationToMavenLocal' uses this output of task ':signKotlinMultiplatformPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

### Context

After updating to Gradle 7 I'm getting these warnings when publishing a Kotlin multiplatform project with signing enabled. 

The signing is set up like this 
```
publishing {
    publications.all {
        signing.sign(this)
    }
}
```

Since both the publishing tasks and the signing tasks are configured on Gradle's side I'm filing this here. 

### Steps to Reproduce 

Download the project, run `./gradlew publishToMavenLocal`
[maven-publish.zip](https://github.com/gradle/gradle/files/6411053/maven-publish.zip)

### Your Environment
Build scan URL: https://scans.gradle.com/s/ectoznmojah3m

**Comment by wolfs** [comment]
Thank you for reporting. I suppose the `metadata` and the `kotlinMultiplatform` publication come from the Kotlin multi-platform plugin. If I interpret the printout above correctly, then the `metadata` JAR is also part of the `kotlinMultiplatform` publication. That causes the problem that there are now two sign tasks (`signMetadataPublication ` and `signKotlinMultiplatformPublication`), both which are going to sign the `metadata` publication artifacts and which try to create the signature at the same location - `maven-publish/build/libs/maven-publish-metadata-1.0.0.jar.asc`.

If my interpretation is correct, then the two sign tasks write to the same output, which may cause the actual signatures to be uploaded different depending on the order of tasks. The Kotlin multi-platform plugin could fix this by moving the metadata JAR out of the `kotlinMultiplatform` publication, so that the artifacts are distinct between the publications.

**Comment by gabrielittner** [comment]
>  I suppose the metadata and the kotlinMultiplatform publication come from the Kotlin multi-platform plugin.

Yes, those are created by Kotlin. Should I open a issue with them and close this one here?

**Comment by wolfs** [comment]
> Yes, those are created by Kotlin. Should I open an issue with them and close this one here?

That would be great!

**Comment by gabrielittner** [comment]
Filed here https://youtrack.jetbrains.com/issue/KT-46466
