### ISSUE TITLE
gradle upgrade to 3.3, findbugs can't exclude some files

### ISSUE THREAD

**Issue by SivanLiu** [gradle/gradle#1704]
In detail, I upgrade the gradle wrapper version to 3.3,that is change the `distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip` in gradle-wrapper.properties, **I found the findbugs plugin did not working with the exclude config**,But if I keep `the distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip` as before ,it is normal.
And did anyone have encountered the problem?
If I upgrade the gradle to 3.3,the findbugs can not **exclude** some class that I do not do findbugs check.

**Comment by blindpirate** [comment]
@YaFengYi I'm interested in this, could you please provide some examples?

**Comment by blindpirate** [comment]
Closed due to unresponsiveness.
