### ISSUE TITLE
Follow up on deprecations in ThirdPartyGradleModuleMetadataSmokeTest.publish()

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#17050]
The following deprecations are breaking `ThirdPartyGradleModuleMetadataSmokeTest`:

- `RepositoryHandler.jcenter()`
- `Adding a Configuration as a dependency is a confusing behavior which isn't recommended`
- `AbstractCompile.destinationDir`
- `AbstractTestTask.binResultsDir`

Let's check why these are emitted and follow up with any third-party plugin authors to get them fixed.

See https://github.com/gradle/gradle/pull/17044 for details on why the deprecations were not detected earlier.

---
cc: @gradle/execution

**Comment by lptr** [comment]
Definitely looks like that.

**Comment by ov7a** [comment]
Fixed by:
* https://github.com/gradle/gradle/pull/26800
