### ISSUE TITLE
gradle 7.0-1: Configuration with name 'compile' not found. Arch/Manjaro

### ISSUE THREAD

**Issue by slrslr** [gradle/gradle#17051]
i did $ pamac build muwire-git

and the build failed:

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Configuration with name 'compile' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 57s
==> ERROR: A failure occurred in build().
    Aborting...

```

pamac build muwire-git in [more context](https://bin.disroot.org/?6b5bc811196820c9#EL7mKigcq5SMXf2Cpu8TLEDUH9bA5ZakLdk1Lsmh3AB8)

### Your Environment

**Build scan URL (scans.gradle.com)**: https://bin.disroot.org/?7e37f1b6b3612fe9#3xEqxrzizrMDZ6RwDdTWYqQbzXzZ9MPpRfYRQD3t24cR

so the mentioned failure is:
Task 'build' is ambiguous in root project 'keystore'. Candidates are: 'buildEnvironment', 'buildScanPublishPrevious'.

**Comment by melix** [comment]
This isn't a bug. The `compile` configuration has been removed, see https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

**Comment by JayNewstrom** [comment]
Looks like it was removed as part of gradle 7, see https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

I'll update the project.
