### ISSUE TITLE
Kotlin 1.5 ".kts" build source, invoke-dynamic for SAM wrappers, and gradle tasks not up to date

### ISSUE THREAD

**Issue by madsager** [gradle/gradle#17052]
When using Kotlin 1.5 `.kts` build files, the Kotlin compiler will use `invoke-dynamic` and lambda metafactory to generate classes for some Kotlin lambdas. That will make Kotlin lambdas suffer the same up-to-date checking issues [that exist for Java lambdas](
https://github.com/gradle/gradle/issues/5510) and users will get tasks that are never up to date (but were with the previous version of the Kotlin compiler). 

An example of a not up-to-date message:

```
Task ':appsearch:appsearch-local-storage:packageDebugAndroidTest' is not up-to-date because:
  Additional action for task ':appsearch:appsearch-local-storage:packageDebugAndroidTest': was implemented by the Java lambda 'androidx.build.AndroidXPlugin$$Lambda$1060/0x0000000800c16440'. Using Java lambdas is not supported, use an (anonymous) inner class instead.
The input changes require a full rebuild for incremental task ':appsearch:appsearch-local-storage:packageDebugAndroidTest'.
```

The workaround is to pass the flag `-Xsam-conversions=class` to the Kotlin compiler when compiling `.kts` build script sources.

Could that flag always be passed by gradle when building from `.kts` script sources with a Kotlin compiler version 1.5 or later?

If that is not feasible, at least this bug report could be helpful to make it easier to find the workaround for users encountering this.

**Comment by eskatos** [comment]
Counterpart issue on Kotlin's tracker https://youtrack.jetbrains.com/issue/KT-46445
Kotlin issue about the change to use `invoke-dynamic` in Kotlin 1.5 https://youtrack.jetbrains.com/issue/KT-44278

**Comment by eskatos** [comment]
Related issues https://github.com/gradle/gradle/issues/10751, https://github.com/gradle/gradle/pull/17087, https://github.com/gradle/gradle/issues/17086

**Comment by liutikas** [comment]
Any updates here, Jetbrains seems to claim it should be fixed in Gradle?

**Comment by eskatos** [comment]
This also affects the configuration cache, see https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:not_yet_implemented:storing_lambdas

**Comment by jbartok** [comment]
Confirmed as still unsolved.

**Comment by eskatos** [comment]
I will take care of it

**Comment by LouisCAD** [comment]
Thank you for fixing this! 🙏🏼
