### ISSUE TITLE
Shutdown of jcenter - please provide a way to handle this change for archived dependencies 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [gradle/gradle#17060]
Original post here:
https://discuss.gradle.org/t/shutdown-of-jcenter-please-provide-a-way-to-handle-this-change-for-archived-dependencies/39832
Also wrote this here:
https://issuetracker.google.com/issues/186941689

About this:
https://blog.gradle.org/jcenter-shutdown

I work on apps that use various dependencies from various sources.
Some of them were sadly archived, so they won't move to mavenCentral or anywhere else.
They will stay on jcenter forever.
Example is this one:
https://github.com/twitter-archive/twitter-kit-android

I've tried various ways to still use it, but without jcenter, and failed:
1. Took and used the AAR files from the cache (on C:\Users\User.gradle) 
2. Import the project and see what I can do (got errors).
3. Use Jitpack (because it's on Github), but it got errors shown right on the website itself
4. Building AAR file for each module and using them all (got a runtime crash).

Please provide a way to automate and safely use the dependency, by converting it to a completely local one (all files that the project will need).

Don't just deprecate. Add a quick fix for Android Studio (and IntelliJ) of "convert remote dependency to local dependency".

**Comment by big-guy** [comment]
JFrog has decided to keep JCenter running read-only indefinitely, so it's less important to get rid of JCenter now. 

I'm closing this for now.

**Comment by AndroidDeveloperLB** [comment]
@big-guy I'd prefer to be less dependent on this, as maybe one day they will change their mind and give very little time like last time they did it.
