### ISSUE TITLE
Add the concept of progress to BuildOperations

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1706]
### Expected Behavior
BuildOperations API allows reporting of progress (e.g. 45%)

### Current Behavior
Build operations are only able to report start and complete. Nested build operations gives some more granular feedback, but there are a bunch of cases where this doesn't provide the UX we want.

### Context
This was just added to the Tooling API for the distribution download, and should be rolled out widely.

**Comment by bmuschko** [comment]
As discussed in meeting:

- `DefaultBuildOperationExecutor` already contains and uses a `ProgressListener`.
- Add another callback on the `ProgressListener` instance that is can be called by the user.
- Potentially expose a handle to the progress logger on `BuildOperationContext`.

**Comment by adammurdoch** [comment]
We should forward these events on to the tooling api client as `StatusEvent` or at least be able to forward these events. Currently, these model progress as 'completed' and 'total' counts rather than an arbitrary string.

**Comment by oehme** [comment]
Looks good overall, just two questions:

- What's the difference between null and empty message?
- Would it make sense to have `BuildOperationContext#getProgressLogger()` instead, so we can add more methods and don't have to put them all on `BuildOperationContext´ later?

**Comment by bmuschko** [comment]
@adammurdoch OK, I'll look into this.

@oehme 

> What's the difference between null and empty message?

The difference would be "" (empty message) vs. null. That's what you are asking right?

> Would it make sense to have BuildOperationContext#getProgressLogger() instead, so we can add more methods and don't have to put them all on `BuildOperationContext´ later?

I see two problems with this approach:
1. `BuildOperationContext` is defined in the `base-services` module which doesn't have a reference to `ProgressLogger` from the logging module. We'd have to move `BuildOperationContext` to `core` I guess.
2. Exposing the `ProgressLogger` through `BuildOperationContext` kind of exposes implementation details. Consumers (really only Gradle core developers) might call methods like `started()` or `completed()`. However, these methods have already been called as part of the implementation logic in `DefaultBuildOperationExecutor`. From a consumer's perspective that could be confusing or at least not be obvious.

**Comment by oehme** [comment]
> The difference would be "" (empty message) vs. null. That's what you are asking right?

Yes, that is my question. So what's the difference? How would a client display an empty message differently from no message?

> I see two problems with this approach:

I'm not referring to the `ProgressLogger`from `logging`. I'm talking about a lightweight object that has methods like `progress(String)` or `progress(current, total)`. I just don't have a better word for it, maybe `ProgressMonitor`.

**Comment by bmuschko** [comment]
> Yes, that is my question. So what's the difference? How would a client display an empty message differently from no message?

I just pulled through this information from [`org.gradle.internal.logging.progress.ProgressLogger.progress(String)`](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/progress/ProgressLogger.java#L111) because that's we are calling off to internally. `org.gradle.internal.logging.progress.ProgressLogger` handles [a null as "" (empty String)](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/progress/DefaultProgressLoggerFactory.java#L157). If that's not what you mean that I am misunderstanding you and we should have a short call.

> I'm not referring to the `ProgressLogger` from `logging`.

Ah, OK. That wasn't clear to me. Yes, that makes sense. I will add that.

**Comment by oehme** [comment]
If null=="", why are we allowing null at all? The fact that null is allowed tells me as a user that null has a special meaning in the API. If it doesn't we shouldn't allow it.

**Comment by bmuschko** [comment]
> If it doesn't we shouldn't allow it.

Fair enough. It's weird that we do that for `org.gradle.internal.logging.progress.ProgressLogger.progress(String)` though. Probably worth to clean it up as well.

**Comment by bmuschko** [comment]
@adammurdoch Currently `StatusEvent` lives in the `tooling-api` module. Is it correct to assume that we'll want to break that out of there as a more wide-used interface/concept?

**Comment by bmuschko** [comment]
As discussed in the standup deferring this issue to later.

**Comment by adammurdoch** [comment]
No, the tapi's view of `StatusEvent` would stay there, along with it's view of build operations. Instead, we'd add a similar kind of event to live with `BuildOperationListener` and friends.
