### ISSUE TITLE
Generate BuildOperations from BuildProgressLogger

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1707]
This is used to log things like Initialization, Configuration, and Execution progress (ya know `<==--> 50% EXECUTING`). This currently uses `ProgressLogger` and should be changed to use BuildOperations.

Should consider BuildOperation hierarchy here. Must ensure the correct parent operation is set.

**Comment by lacasseio** [comment]
There are already `BuildOperation` generated for each stage of the build. Maybe this could be solved by using those `BuildOperation` and wire in the concept of progress. This would move the rendering of the progress bar and percentage inside the console where we would consume the `BuildOperation` progress events.

**Comment by lacasseio** [comment]
This work was differed for https://github.com/gradle/gradle/issues/1816.
