### ISSUE TITLE
Struggling to define KotlinCompileDaemon params with gradle 7.0

### ISSUE THREAD

**Issue by mattt-seek** [gradle/gradle#17075]
Our android build specifies Kotlin JVM args as follows:
org.gradle.jvmargs=..... -Dkotlin.daemon.jvm.options=-Xmx1g  ....

### Expected Behavior
jps -v will show these values during a build e.g.
82861 KotlinCompileDaemon -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx1g

### Current Behavior
The KotlinCompileDaemon seems to be inheriting the GradleDaemon args.

### Context

Works in 6.8.3, not in 7.0

We are in a memory constrained environment so trying to keep resource use under tight control

### Steps to Reproduce 
Set -Dkotlin.daemon.jvm.options
in org.gradle.jvmargs
Try on gradle 6.8.3 then on 7.0

**Comment by mattt-seek** [comment]
Noticed that this is only happening with JDK 11 (gradle 7 + JDK8 is OK, and gradle 6.7.1 + JDK 11 is OK)

```
java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6916264, mixed mode)
```

gradle.properties setttings are:

`org.gradle.jvmargs=-Xmx3500m -XX:MaxMetaspaceSize=2g -XX:+UseParallelGC -XX:NewRatio=4 -Dkotlin.daemon.jvm.options="-Xmx1g,-XX:MaxMetaspaceSize=256m" -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8`

Leads to (note 3500m assigned to the KotlinCompileDaemon)

```
37084 GradleDaemon -XX:MaxMetaspaceSize=2g -XX:+UseParallelGC -XX:NewRatio=4 -XX:+HeapDumpOnOutOfMemoryError --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx3500m -Dfile.encoding=UTF-8 -Duser.country=AU -Duser.language=en -Duser.variant

37103 KotlinCompileDaemon -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx3500m -XX:MaxMetaspaceSize=2g --illegal-access=permit -Dkotlin.environment.keepalive -ea
```

**Comment by Tapchicoma** [comment]
@mattt-seek you could validate how Kotlin daemon was started by enabling info loglevel (`--info`) and searching for the string starting with: `i: starting the daemon as:`

**Comment by donat** [comment]
I was able to reproduce the issue with the following steps:
- Put Java 11 and Gradle 7.0.2 on PATH
- Run the following commands on [sample project](https://github.com/gradle/gradle/files/6589981/17075.zip):

```
    gradle lib:clean lib:ass --info
    jps -v
```

The output of the `compileKotlin` task is the following

```
> Task :lib:compileKotlin
Watching 1 directory hierarchies to track changes
Caching disabled for task ':lib:compileKotlin' because:
  Build cache is disabled
Task ':lib:compileKotlin' is not up-to-date because:
  Output property 'destinationDirectory' file /Users/donat/Development/bt-support/17075/lib/build/classes/kotlin/main has been removed.
  Output property 'destinationDirectory' file /Users/donat/Development/bt-support/17075/lib/build/classes/kotlin/main/META-INF has been removed.
  Output property 'destinationDirectory' file /Users/donat/Development/bt-support/17075/lib/build/classes/kotlin/main/META-INF/lib.kotlin_module has been removed.
The input changes require a full rebuild for incremental task ':lib:compileKotlin'.
file or directory '/Users/donat/Development/bt-support/17075/lib/src/main/java', not found
file or directory '/Users/donat/Development/bt-support/17075/lib/src/main/java', not found
file or directory '/Users/donat/Development/bt-support/17075/lib/src/main/java', not found
file or directory '/Users/donat/Development/bt-support/17075/lib/src/main/java', not found
Using Kotlin/JVM incremental compilation
i: starting the daemon as: /Users/donat/.sdkman/candidates/java/11.0.9.hs-adpt/bin/java -cp /Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.31/6451ea797cef544e81f507b0d9959cd97ae09c0/kotlin-compiler-embeddable-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.31/63db9d66c3d20f7b8f66196e7ba86969daae8b8a/kotlin-reflect-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.31/a58e0fb9812a6a93ca24b5da75e4b5a0cb89c957/kotlin-stdlib-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.31/183616b52cfb8ddaa8a2a15bf926e87dfcddcde3/kotlin-script-runtime-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/1.4.31/10faf8ac3dd5975ed972b2bc395b4ffc7ffde246/kotlin-daemon-embeddable-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20181211/216c2e14b070f334479d800987affe4054cd563f/trove4j-1.0.20181211.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.31/6dd50665802f54ba9bc3f70ecb20227d1bc81323/kotlin-stdlib-common-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx16384m --illegal-access=permit -Dkotlin.environment.keepalive -ea org.jetbrains.kotlin.daemon.KotlinCompileDaemon --daemon-runFilesPath /Users/donat/Library/Application Support/kotlin/daemon --daemon-autoshutdownIdleSeconds=7200 --daemon-compilerClasspath /Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.31/6451ea797cef544e81f507b0d9959cd97ae09c0/kotlin-compiler-embeddable-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.31/63db9d66c3d20f7b8f66196e7ba86969daae8b8a/kotlin-reflect-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.31/a58e0fb9812a6a93ca24b5da75e4b5a0cb89c957/kotlin-stdlib-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.31/183616b52cfb8ddaa8a2a15bf926e87dfcddcde3/kotlin-script-runtime-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/1.4.31/10faf8ac3dd5975ed972b2bc395b4ffc7ffde246/kotlin-daemon-embeddable-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20181211/216c2e14b070f334479d800987affe4054cd563f/trove4j-1.0.20181211.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.31/6dd50665802f54ba9bc3f70ecb20227d1bc81323/kotlin-stdlib-common-1.4.31.jar:/Users/donat/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar
i: Received the message signalling that the daemon is ready
i: new daemon started, trying to find it
i: found daemon on port 17111 (19 ms old), trying to connect
i: connected to the daemon
Options for KOTLIN DAEMON: IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, targetPlatform=JVM, reportCategories=[0], reportSeverity=2, requestedCompilationResults=[0]kotlinScriptExtensions=[kt, kts, java]), areFileChangesKnown=false, modifiedFiles=null, deletedFiles=null, workingDir=/Users/donat/Development/bt-support/17075/lib/build/kotlin/compileKotlin, multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/Users/donat/Development/bt-support/17075/lib/build/kotlin/compileKotlin/build-history.bin, useModuleDetection=false), usePreciseJavaTracking=trueoutputFiles=[/Users/donat/Development/bt-support/17075/lib/build/classes/kotlin/main, /Users/donat/Development/bt-support/17075/lib/build/kotlin/compileKotlin])
:lib:compileKotlin (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 3.662 secs.
:lib:compileJava (Thread[Execution worker for ':' Thread 2,5,main]) started.
```

Also, `jps` reports a different `Xmx` value for the Kotlin Compiler daemon, than the specified `1025` in the `gradle.properties file`:

```
12264 KotlinCompileDaemon -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx16384m --illegal-access=permit -Dkotlin.environment.keepalive -ea
```

**Comment by mattt-seek** [comment]
@Tapchicoma i get...

i: **starting the daemon as**: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/java -cp /Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.32/b4fc9be460ca88eecea2303e142ce2920bd14775/kotlin-compiler-embeddable-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.32/ce852b166d97f0f1991b5130c2bb02e2ef6c554e/kotlin-reflect-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.32/461367948840adbb0839c51d91ed74ef4a9ccb52/kotlin-stdlib-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.32/bac50b0748be017dbc13fc1cb7231b1c9da0e106/kotlin-script-runtime-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/1.4.32/b40c5de5adea26ebb4e5fc36945c482ac20acee2/kotlin-daemon-embeddable-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20181211/216c2e14b070f334479d800987affe4054cd563f/trove4j-1.0.20181211.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.32/ef50bfa2c0491a11dcc35d9822edbfd6170e1ea2/kotlin-stdlib-common-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar -Djava.awt.headless=true -Djava.rmi.server.hostname=127.0.0.1 -Xmx1g -XX:MaxMetaspaceSize=256m -Dkotlin.environment.keepalive -ea org.jetbrains.kotlin.daemon.KotlinCompileDaemon --daemon-runFilesPath /Users/mattt/Library/Application Support/kotlin/daemon --daemon-autoshutdownIdleSeconds=7200 --daemon-compilerClasspath /Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.4.32/b4fc9be460ca88eecea2303e142ce2920bd14775/kotlin-compiler-embeddable-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.32/ce852b166d97f0f1991b5130c2bb02e2ef6c554e/kotlin-reflect-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.32/461367948840adbb0839c51d91ed74ef4a9ccb52/kotlin-stdlib-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-script-runtime/1.4.32/bac50b0748be017dbc13fc1cb7231b1c9da0e106/kotlin-script-runtime-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-embeddable/1.4.32/b40c5de5adea26ebb4e5fc36945c482ac20acee2/kotlin-daemon-embeddable-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.intellij.deps/trove4j/1.0.20181211/216c2e14b070f334479d800987affe4054cd563f/trove4j-1.0.20181211.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.32/ef50bfa2c0491a11dcc35d9822edbfd6170e1ea2/kotlin-stdlib-common-1.4.32.jar:/Users/mattt/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar
i: Received the message signalling that the daemon is ready

**Comment by donat** [comment]
There's a workaround in the JPMS support that causes this: https://github.com/gradle/gradle/blob/d6383fa764b5be77ff17a2ec468a4c72c10f6734/subprojects/base-services/src/main/java/org/gradle/internal/jvm/JpmsConfiguration.java#L58-L60

**Comment by donat** [comment]
@rieske Could you please take a look?
