### ISSUE TITLE
Improve the error message about lambdas used as additional action

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#17086]
Kotlin `1.5` now [uses `invokedynamic` to perform SAM conversions](https://kotlinlang.org/docs/whatsnew15.html#sam-adapters-via-invokedynamic). This is typically the case when using `doLast {}` in a plugin:

```kotlin
task.doLast {
  // something
}
```

Such a task will never be `up-to-date` if compiled with Kotlin `1.5` with the following message:

```
Task ':fooBar' is not up-to-date because:
  Additional action for task ':fooBar': was implemented by the Java lambda XYZ

Using Java lambdas is not supported, use an (anonymous) inner class instead.
```

This all seems reasonable and using an object instead of a Kotlin SAM works well. This issue is about the wording of the message as that can be surprising. Maybe mention Kotlin `1.5` or `invokedynamic` instead of Java ? Or redirect to https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:how_does_it_work that explains why it's not possible to track `invokedynamic` lambdas?

```
Java lambda classes are created at runtime with a non-deterministic classname. Therefore, the class name does not 
identify the implementation of the lambda and changes between different Gradle runs.
```

**Comment by jjohannes** [comment]
See also: #17052

**Comment by LouisCAD** [comment]
A better alternative would be to take a crossinline lambda for Kotlin callers that gets called inside a serializable type from Gradle Kotlin DSL internals.
