### ISSUE TITLE
Publishing times out

### ISSUE THREAD

**Issue by marandaneto** [gradle/gradle#17082]
Gradle maven-publish times out too much, sometimes I need to try for days to be able to publish all the artifacts to maven central, I'm not sure if it's the Gradle uploader or Maven central API and sometimes just works.

Related issue https://github.com/vanniktech/gradle-maven-publish-plugin/issues/232 and https://github.com/vanniktech/gradle-maven-publish-plugin/issues/170

### Expected Behavior
Publish artifacts to maven central without problems

### Current Behavior
Often it times out (Operation timed out (Read failed), broken pipe, TLS errors

### Context
Gradle 7, but also tried with 6.8.x
Java 8

### Steps to Reproduce 
Running `publishMavenPublicationToMavenCentralRepository` task for all artifacts or specific artifact, sometimes it hangs always for the same artifacts, not even calling the module's task directly works.
I use the plugin https://github.com/vanniktech/gradle-maven-publish-plugin for a multimodule Gradle project (Android and Java modules)
https://github.com/getsentry/sentry-java

### Your Environment

Build scan URL: https://scans.gradle.com/s/5tmoskdvnmbvi

Ps: also tried with `Daemon` on/off already 20 times today

[log.txt](https://github.com/gradle/gradle/files/6427139/log.txt)

**Comment by bmuskalla** [comment]
The problem with these timeouts is that it's not safe to simply retry as we might have already publishes some parts. @ljacomet I know you have thought about this more, is this something we can realistically fix at some point?
