### ISSUE TITLE
Gradle 7.0 cannot use api，also cannot use compile

### ISSUE THREAD

**Issue by xingyun86** [gradle/gradle#17140]
When I use Gradle 6.6, api()->compile() work ok.
Gradle 7.0 cannot use api()，also cannot use compile().
How I can package jar into my project?
My code is：
```
dependencies {
    // Use JUnit test framework.
    testImplementation 'junit:junit:4.13.1'

    // This dependency is used by the application.
    implementation 'com.google.guava:guava:30.0-jre'
    api 'org.ojalgo:ojalgo-commons-math3:3.0.0'
    api 'net.sf.phat:sphinx4-core:5prealpha'
}
```
```
PS F:\WorkProj\test> gradle build

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\WorkProj\test\app\build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method api() for arguments [org.ojalgo:ojalgo-commons-math3:3.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

```

**Comment by xingyun86** [comment]
> 
> 
> When I use Gradle 6.6, api->compile work ok.
> Gradle 7.0 cannot use api，also cannot use compile.
> How I can package jar into my project?
> My code is：
> 
> ```
> dependencies {
>     // Use JUnit test framework.
>     testImplementation 'junit:junit:4.13.1'
> 
>     // This dependency is used by the application.
>     implementation 'com.google.guava:guava:30.0-jre'
>     api 'org.ojalgo:ojalgo-commons-math3:3.0.0'
>     api 'net.sf.phat:sphinx4-core:5prealpha'
> }
> ```
> 
> ```
> PS F:\WorkProj\test> gradle build
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'F:\WorkProj\test\app\build.gradle' line: 30
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > Could not find method api() for arguments [org.ojalgo:ojalgo-commons-math3:3.0.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> ```

I also resolved it by myself. Thanks Gradle very much!!!

**Comment by xingyun86** [comment]
I can use api(), but also cannot package jar into my project jar. Please give me some help.

**Comment by blindpirate** [comment]
Gradle 7.0 removes `compile` so it's expected.

> but also cannot package jar into my project jar

Can you provide a minimal reproducible project? We're sorry we can't help if you just say "cannot package jar into my project jar".

**Comment by xingyun86** [comment]
> 
> 
> Gradle 7.0 removes `compile` so it's expected.
> 
> > but also cannot package jar into my project jar
> 
> Can you provide a minimal reproducible project? We're sorry we can't help if you just say "cannot package jar into my project jar".

But I use gradle 6.6 package 3rd jar into my project. why not Gradle 7.0?

**Comment by xingyun86** [comment]
> 
> 
> > Gradle 7.0 removes `compile` so it's expected.
> > > but also cannot package jar into my project jar
> > 
> > 
> > Can you provide a minimal reproducible project? We're sorry we can't help if you just say "cannot package jar into my project jar".
> 
> But I use gradle 6.6 package 3rd jar into my project. why not Gradle 7.0?

I also resolved it by myself. I can package 3rd jar into my jar file. Well done!
