### ISSUE TITLE
Remove deprecated getters/setters that have a stable property as replacement since 7.0

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#17151]
- [x] JavaExec: https://github.com/gradle/gradle/pull/17079
- [x] Application plugin: https://github.com/gradle/gradle/pull/17083
- [x] SourceDirectorySet: https://github.com/gradle/gradle/pull/17098
- [x] Exec task: https://github.com/gradle/gradle/pull/17100
- [x] CompileOptions: https://github.com/gradle/gradle/pull/17105
- [x] AbstractTestTask: https://github.com/gradle/gradle/pull/17106
- [x] Report: https://github.com/gradle/gradle/pull/17107
- [x] AbstractArchiveTask: https://github.com/gradle/gradle/pull/17123

Note: I'm using checked items to track what is merged into `master` and closed.

**Comment by timnick-snow** [comment]
AnnotationProcessor is deprecated. What's the alternative?

**Comment by tresat** [comment]
Everything is either finished or rescheduled for Gradle 9.0.
