### ISSUE TITLE
Sync task "disappears" from timeline when from() is passed a RealFileProvider from a failing task

### ISSUE THREAD

**Issue by rock3r** [gradle/gradle#17153]
In an Android project, I have a `Sync` task:

```kotlin
tasks {
  register<Sync>("collectSarifReports") {
    val androidLintRelease = named<AndroidLintTask>("lintRelease")
    mustRunAfter(androidLintRelease)

    from(androidLintRelease.get().sarifReportOutputFile) {
      rename { "android-lint.sarif" }
    }

    into("$buildDir/reports/sarif")
  }
}
```

### Expected Behavior
If I run this task as above, it'll always be executed, regardless of the outcome of the `lintRelease` task.

### Current Behavior
If the `lintRelease` task succeeds, the `collectSarifReports` task will work just fine. But if the `lintRelease` task fails, the `collectSarifReports` vanishes entirely after it's configured (I can trace its configuration being run by putting a `println()` in the task configuration lambda).

Running:

```powershell
$  .\gradlew.bat clean lintRelease collectSarifReports --continue --no-daemon --scan
```

Results in the `myTask` never being executed, as if it disappeared entirely from the build:

![image](https://user-images.githubusercontent.com/153802/117696120-420ec200-b1c1-11eb-9dcc-ac64ebfa29d0.png)

You can see the full scan [here](https://gradle.com/s/64jmunkcvdef4).

### Context
I need to collect SARIF reports generated by various static analysis tools, so that I can publish them at the end of the CI runs.
The project in which I observe the issue is: https://github.com/rock3r/Bundel

This was the fix:
https://github.com/rock3r/Bundel/commit/7f209018fac2cff6abc561f89a7f16480dfea110

In particular, explicitly getting the files out of the `RealFileProvider` made the task work even when the `lintRelease` task exploded:

```diff
- from(androidLintRelease.get().sarifReportOutputFile) {
+ from(androidLintRelease.get().sarifReportOutputFile.get().asFile) {
```

### Steps to Reproduce 
1. Clone https://github.com/rock3r/Bundel and checkout  commit `e34079086836c6b3d5827adcae73bc4c7cdf085e`.
2. Run `.\gradlew.bat clean staticAnalysis collectSarifReports --continue`
3. Observe that `collectSarifReports` is never run

### Your Environment
Windows 10, Gradle 7.0, AGP 7.0.0-alpha15, using Kotlin DSL (and Kotlin 1.4.32)
Build scan URL: https://gradle.com/s/64jmunkcvdef4

**Comment by ljacomet** [comment]
What you see is expected behavior:
`from(androidLintRelease.get().sarifReportOutputFile)` preserves the task dependency an implicitly makes `collectSarifReports` `dependsOn` `androidLintRelease`. And when a task fails, even with `--continue`, its dependent tasks are not run.

So what you figured out is indeed a possible fix since you break the task dependency.
A better way to express what you want would be to create a location for that file and configure both tasks with it, clarifying that you do not expect it to create a strong dependency.

**Comment by rock3r** [comment]
Thanks @ljacomet — that's a good idea. One thing I'm not clear on is how to specify it's not a strong dependency, in terms of code. Any pointers would be appreciated, thanks 🙏

**Comment by ljacomet** [comment]
What I was referring at was something like:
```
val lintOutput = project.layout.buildDirectory.file('some/relative/path/file.out')
tasks.named<AndroidLintTask>("lintRelease") {
    sarifReportOutputFile.set(lintOutput)
}
tasks.named<Sync>("collectSarifReports") {
    from(lintOutput) { ... }
}
```
(coded in Github, might have some errors)

Is that what you were after?
If not, please clarify what kind of pointer you are looking for.

**Comment by rock3r** [comment]
Thanks! That's what I was thinking, I think I just misinterpreted what you initially said as to mean I would have to somehow explicitly express in code that the dependency is a weak one. I realised that the code actually does that already :) Thanks again for the help
