### ISSUE TITLE
Add deprecation logging for Project.getConvention() and HasConvention.getConvention()

### ISSUE THREAD

**Issue by donat** [gradle/gradle#17176]
We'll deprecate the concept of conventions in Gradle 7.1. Still, many external plugins (like the kotlin gradle plugin) make use of it. To minimize the disturbance, we'll only add the `@Deprecated` annotation in Gradle 7.1 without any deprecation logging message. We create this issue not to forget about adding the deprecation message later, most likely in Gradle 7.2.

**Comment by donat** [comment]
https://youtrack.jetbrains.com/issue/KT-47047 Is scheduled for Kotlin 1.6.

**Comment by eskatos** [comment]
This was release in Kotlin 1.7.20

**Comment by ljacomet** [comment]
This is already done:
* #24231
