### ISSUE TITLE
Better error message for typed deps from a TOML file.

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#17170]
put this in your version catalog TOML: 
```
test-containers = { module = "org.testcontainers:testcontainers", version.ref = "testContainers" }
test-containers-junit = { module= "org.testcontainers:junit-jupiter", version.ref="testContainers" }
```

### Expected Behavior

Error message with more detail and a suggested remediation.
```
org.gradle.api.InvalidUserDataException: Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
> Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
[test-containers] conflicts with [test-containers-junit], add a suffix to [test-containers] to avoid this issue. 
E.g. change [test-containers] to [test-containers-mysuffix] 
```

### Current Behavior

you will get this error:
```
org.gradle.api.InvalidUserDataException: Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
> Cannot generate accessors for test because it contains both aliases and groups of the same name: [containers]
```

**Comment by docent** [comment]
I just ran into the same issue:
```
commons-logging = { module = "commons-logging:commons-logging", version = "1.1.1"}
commons-logging-api = { module = "commons-logging:commons-logging-api", version = "1.1.1"}
> Cannot generate accessors for commons because it contains both aliases and groups of the same name: [logging]
```
I do not understand why having these, seemingly unique, alias names leads to conflicting accessors being generated, and why in this case it's "logging".
I predict that the users will run into this issue a lot, and it will be confusing to them. Having a better error message is one thing, bu the algorithm itself seems to be confusing.

**Comment by octylFractal** [comment]
I would like to push for this to go even further, and actually _allow_ this sort of declaration. Adding a suffix is okay, but it makes the name of the alias and the name of the module differ, which is a little annoying. I know that this has [already been considered](https://melix.github.io/blog/2021/03/version-catalogs-faq.html#_why_can_t_i_have_nested_aliases_with_the_same_prefix), but I want to make sure that it is revisited at some point to try and get it working.
