### ISSUE TITLE
Use Provider and PropertyState in all Gradle core plugins

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1717]
After establishing the concept in https://github.com/gradle/gradle/issues/1664 adapt all Gradle core plugins to use the concept consistently.

**Comment by ajoberstar** [comment]
When you guys look at this, it would be nice for top-level Project properties like `version` to be `Property` capable as well.

I rely on the oddity in the API that version is an `Object`  that gets evaluated in most usage via `toString` in [gradle-git](https://github.com/ajoberstar/gradle-git) and [reckon](https://github.com/ajoberstar/reckon). While I don't expect that to break, it feels like Property/Provider provides a better way forward here.

Back in [the old days](http://gradle.1045684.n5.nabble.com/MavenPublish-Evaluation-Timing-Issue-td5712584.html), I planned to do this in a task, but some plugins (maven-publish) evaluated the version before the task could execute. A Property should do the trick nicely (ideally, along with something to address #5126).

**Comment by ov7a** [comment]
See
* https://github.com/gradle/build-tool-roadmap/issues/28
