### ISSUE TITLE
dependencyResolutionManagement default configurations

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#17181]
for transient depenencies it would be nice if they could be specified as `*runtimeOnly` meaning if I specify say... 

```kts
implementation("org.springframework.boot:spring-boot-starter-json")
testImplementation("org.springframework.boot:spring-boot-starter-test")
```

all of the Jackson dependencies included would be `runtimeOnly` by default, and junit would be `testRuntimeOnly`. My motivation is to prevent transient leaks, maybe something like this

```kts
    dependencyResolutionManagement {
        versionCatalogs {
            create("libs") {
                version("groovy", "3.0.5")
                version("checkstyle", "8.37")
                alias("groovy-core").to("org.codehaus.groovy", "groovy").versionRef("groovy")
                alias("groovy-json").to("org.codehaus.groovy", "groovy-json").versionRef("groovy")
                alias("groovy-nio").to("org.codehaus.groovy", "groovy-nio").versionRef("groovy")
                alias("commons-lang3").to("org.apache.commons", "commons-lang3").version {
                    strictly("[3.8, 4.0[")
                    prefer("3.9")
                }
                bundle("groovy", runtimeOnly("groovy-core", "groovy-json", "groovy-nio"), implementation("something"))
            }
        }
    }
```
```kts
dependencies {
    use(libs.groovy)
}
```

this is to reach a better, but more powerful parody of starters. Primary motivation is that I don't actually want to have to worry about each import scope, and I don't want all this dependency bleed of imports that really shouldn't be available.

**Comment by vlsi** [comment]
@xenoterracide , would you please clarify the use case? 

What is the purpose of `spring-boot-starter-json` if you move jackson to `runtimeOnly`?
If you think `jackson` should not be on the compile path, then what do you think of convincing Spring Boot team to declare the dependencies as `implementation`? (see https://github.com/spring-projects/spring-boot/blob/e9adb1ab88d2778b65e8643e008814c085111649/spring-boot-project/spring-boot-starters/spring-boot-starter-json/build.gradle#L10-L13)

**Comment by xenoterracide** [comment]
firstly this is not specifically about jackson, I just picked that as an example as it's what I'm currently mucking with.

> If you think jackson should not be on the compile path, then what do you think of convincing Spring Boot team to declare the dependencies as implementation

I know @wilkinsona I'm pretty sure he'd say no. Even if he didn't, I'm not yet aware of a platform that is gradle specific, meaning that implementation isn't available from the platform bom.

> What is the purpose of spring-boot-starter-json if you move jackson to runtimeOnly?

to me, starters are just collections of dependencies that I want to manage the actual scopes of the ones I want as compile-time, and generally, in a multi-project where this feature shines, I'll want to use that configuration over and over. Rather, I think that's what a bundle should be, to avoid unnecessary proliferation of things to the compile classpath, so that developers don't use classes that were never meant to be exposed (oh woe is me why did you use that function from infinispan's object utils because you were too lazy to see that it was an import on a transient (or whatever) (yes this has happened, it was maven, but still)).  It also seems to me that having a bundle like this might be a performance boost for some projects, but I'm not sure and haven't measured.

for example (continuing with Jackson), I personally would prefer to have this as my default replacement for their starter

```kts
  bundle("jackson") { // maybe this is closer to a better api? but using short names instead
        api("com.fasterxml.jackson.core:jackson-annotations")
	runtimeOnly(project(":spring-boot-project:spring-boot-starters:spring-boot-starter"))
	testRuntimeOnly("org.springframework:spring-web") // actually, I'm inclined to have an argument about this dependency, hence the "test"
	runtimeOnly(*"com.fasterxml.jackson.core:jackson-databind")
	runtimeOnly("com.fasterxml.jackson.module:jackson-module-parameter-names")
   }
```

Most of the time, I don't actually want anything other than the annotations at compile time. If I did I could always add it in dependencies after.

There are many other examples too, I mean, do you ever actually want the junit runner at compile time? rarely (and by rarely I mean I have never once wanted this).

as it is, the only way I know that I could do this is by making a plugin, which is less nice in my opinion.

**Comment by vlsi** [comment]
> as it is, the only way I know that I could do this is by making a plugin, which is less nice in my opinion.

```kotlin
plugins {
  id("java-library")
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.7.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}
```

`./gradlew dependencies`

```
testCompileClasspath - Compile classpath for source set 'test'.
+--- org.junit:junit-bom:5.7.1
|    +--- org.junit.jupiter:junit-jupiter:5.7.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-api:5.7.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-params:5.7.1 (c)
|    \--- org.junit.platform:junit-platform-commons:1.7.1 (c)
\--- org.junit.jupiter:junit-jupiter -> 5.7.1
     +--- org.junit:junit-bom:5.7.1 (*)
     +--- org.junit.jupiter:junit-jupiter-api:5.7.1
     |    +--- org.junit:junit-bom:5.7.1 (*)
     |    +--- org.apiguardian:apiguardian-api:1.1.0
     |    +--- org.opentest4j:opentest4j:1.2.0
     |    \--- org.junit.platform:junit-platform-commons:1.7.1
     |         +--- org.junit:junit-bom:5.7.1 (*)
     |         \--- org.apiguardian:apiguardian-api:1.1.0
     \--- org.junit.jupiter:junit-jupiter-params:5.7.1
          +--- org.junit:junit-bom:5.7.1 (*)
          +--- org.apiguardian:apiguardian-api:1.1.0
          \--- org.junit.jupiter:junit-jupiter-api:5.7.1 (*)

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.junit:junit-bom:5.7.1
|    +--- org.junit.jupiter:junit-jupiter:5.7.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-api:5.7.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-params:5.7.1 (c)
|    +--- org.junit.jupiter:junit-jupiter-engine:5.7.1 (c)
|    +--- org.junit.platform:junit-platform-commons:1.7.1 (c)
|    \--- org.junit.platform:junit-platform-engine:1.7.1 (c)
\--- org.junit.jupiter:junit-jupiter -> 5.7.1
     +--- org.junit:junit-bom:5.7.1 (*)
     +--- org.junit.jupiter:junit-jupiter-api:5.7.1
     |    +--- org.junit:junit-bom:5.7.1 (*)
     |    +--- org.apiguardian:apiguardian-api:1.1.0
     |    +--- org.opentest4j:opentest4j:1.2.0
     |    \--- org.junit.platform:junit-platform-commons:1.7.1
     |         +--- org.junit:junit-bom:5.7.1 (*)
     |         \--- org.apiguardian:apiguardian-api:1.1.0
     +--- org.junit.jupiter:junit-jupiter-params:5.7.1
     |    +--- org.junit:junit-bom:5.7.1 (*)
     |    +--- org.apiguardian:apiguardian-api:1.1.0
     |    \--- org.junit.jupiter:junit-jupiter-api:5.7.1 (*)
     \--- org.junit.jupiter:junit-jupiter-engine:5.7.1
          +--- org.junit:junit-bom:5.7.1 (*)
          +--- org.apiguardian:apiguardian-api:1.1.0
          +--- org.junit.platform:junit-platform-engine:1.7.1
          |    +--- org.junit:junit-bom:5.7.1 (*)
          |    +--- org.apiguardian:apiguardian-api:1.1.0
          |    +--- org.opentest4j:opentest4j:1.2.0
          |    \--- org.junit.platform:junit-platform-commons:1.7.1 (*)
          \--- org.junit.jupiter:junit-jupiter-api:5.7.1 (*)
```

Note that `junit-jupiter-engine` is not on the test compile classpath, and it is on test runtime classpath only.

-----

Have you seen https://docs.gradle.org/current/userguide/java_platform_plugin.html ?

`settings.gradle`

```
include(":starter")
```

`build.gradle`

```groovy
plugins {
  id("java-library")
}

project(":starter") {
    apply plugin: "java-platform"
    dependencies {
      api("org.junit.jupiter:junit-jupiter-api:5.7.1")
      runtime("org.junit.jupiter:junit-jupiter-engine:5.7.1")
    }
    repositories {
        mavenCentral()
    }
    javaPlatform {
        allowDependencies()
    }
}


repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform(project(":starter")))
}
```

`./gradlew dependencies`

```
testCompileClasspath - Compile classpath for source set 'test'.
\--- project :starter
     \--- org.junit.jupiter:junit-jupiter-api:5.7.1
          +--- org.junit:junit-bom:5.7.1
          |    +--- org.junit.jupiter:junit-jupiter-api:5.7.1 (c)
          |    \--- org.junit.platform:junit-platform-commons:1.7.1 (c)
          +--- org.apiguardian:apiguardian-api:1.1.0
          +--- org.opentest4j:opentest4j:1.2.0
          \--- org.junit.platform:junit-platform-commons:1.7.1
               +--- org.junit:junit-bom:5.7.1 (*)
               \--- org.apiguardian:apiguardian-api:1.1.0

testRuntimeClasspath - Runtime classpath of source set 'test'.
\--- project :starter
     +--- org.junit.jupiter:junit-jupiter-api:5.7.1
     |    +--- org.junit:junit-bom:5.7.1
     |    |    +--- org.junit.jupiter:junit-jupiter-api:5.7.1 (c)
     |    |    +--- org.junit.jupiter:junit-jupiter-engine:5.7.1 (c)
     |    |    +--- org.junit.platform:junit-platform-commons:1.7.1 (c)
     |    |    \--- org.junit.platform:junit-platform-engine:1.7.1 (c)
     |    +--- org.apiguardian:apiguardian-api:1.1.0
     |    +--- org.opentest4j:opentest4j:1.2.0
     |    \--- org.junit.platform:junit-platform-commons:1.7.1
     |         +--- org.junit:junit-bom:5.7.1 (*)
     |         \--- org.apiguardian:apiguardian-api:1.1.0
     \--- org.junit.jupiter:junit-jupiter-engine:5.7.1
          +--- org.junit:junit-bom:5.7.1 (*)
          +--- org.apiguardian:apiguardian-api:1.1.0
          +--- org.junit.platform:junit-platform-engine:1.7.1
          |    +--- org.junit:junit-bom:5.7.1 (*)
          |    +--- org.apiguardian:apiguardian-api:1.1.0
          |    +--- org.opentest4j:opentest4j:1.2.0
          |    \--- org.junit.platform:junit-platform-commons:1.7.1 (*)
          \--- org.junit.jupiter:junit-jupiter-api:5.7.1 (*)
```

**Comment by xenoterracide** [comment]
in the 1st, that was exactly what I said was possible, but for the 2nd, no I had not seen that. hmm... sorry.

side question, should I create a bug to generate the `libs.foo` style accessors for `projects` so you don't have to use strings?

**Comment by vlsi** [comment]
Have you tried

```kotlin
enableFeaturePreview("VERSION_CATALOGS")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
```
?

See https://github.com/junit-team/junit5/blob/6359e512436a642ad1efc986f754105344b94ff3/settings.gradle.kts#L130-L131
https://github.com/junit-team/junit5/blob/6359e512436a642ad1efc986f754105344b94ff3/junit-jupiter-engine/junit-jupiter-engine.gradle.kts#L13-L16

**Comment by xenoterracide** [comment]
I'm using the first (hence this "bug"), but I didn't know about the 2nd

**Comment by vlsi** [comment]
PS. You could adjust api vs runtime dependencies (e.g. for org.springframework.boot:spring-boot-starter-json) with a help of ComponentMetadataRule: https://docs.gradle.org/current/userguide/component_metadata_rules.html

**Comment by xenoterracide** [comment]
that first example in that has `params(7)` and subsequently `params(8)` #MagicNumbersAreBad

**Comment by vlsi** [comment]
I guess your sample is close to https://docs.gradle.org/current/userguide/component_metadata_rules.html#fixing_wrong_dependency_details

```kotlin
@CacheableRule
abstract class SpringBootJsonDependenciesRule: ComponentMetadataRule {
    override fun execute(context: ComponentMetadataContext) {
        context.details.withVariant("compile") { // or "runtime"
            withDependencies {
                removeAll { it.group.startsWith("com.fasterxml.jackson.") }
            }
        }
    }
}
```

```kotlin
dependencies {
    components {
        withModule<SpringBootJsonDependenciesRule>("org.springframework.boot:spring-boot-starter-json")
    }
    implementation("org.springframework.boot:spring-boot-starter-json")
}
```

Of course, you would like to hide `SpringBootJsonDependenciesRule` and `dependencies.components` in a plugin.

**Comment by vlsi** [comment]
> params(7) and subsequently params(8) 

They mean `param(Java7)` and `param(Java8)`

However, I agree the first example is not the most trivial one :)

**Comment by xenoterracide** [comment]
that example should remove the magic number ;) `val java7 = 7` ;)

**Comment by xenoterracide** [comment]
so, I'm sure this is answered somewhere, but if I wanted to publish the starter using the `project(":starter")` approach, how would I do that? always published jars with pom's so...

**Comment by vlsi** [comment]
You publish it with `maven-publish`: https://docs.gradle.org/current/userguide/java_platform_plugin.html#sec:java_platform_publishing

**Comment by vlsi** [comment]
```groovy
plugins {
  id("java-platform")
  id("maven-publish")
}

dependencies {
  api("org.junit.jupiter:junit-jupiter-api:5.7.1")
  runtime("org.junit.jupiter:junit-jupiter-engine:5.7.1")
}
repositories {
    mavenCentral()
}
javaPlatform {
    allowDependencies()
}

group = "com.example"
version = "1.0"

publishing {
    publications {
        binary(MavenPublication) {
            from components.javaPlatform
        }
    }
    repositories {
        maven {
            name = "testRepo"
            url = uri("$buildDir/$name")
        }
    }
}
```

```
% ./gradlew publishAllPublicationsToTestRepoRepository

BUILD SUCCESSFUL in 686ms
```

```
% tree build/testRepo
build/testRepo
└── com
    └── example
        └── gradle-bug-reproducers
            ├── 1.0
            │   ├── gradle-bug-reproducers-1.0.module
            │   ├── gradle-bug-reproducers-1.0.module.md5
            │   ├── gradle-bug-reproducers-1.0.module.sha1
            │   ├── gradle-bug-reproducers-1.0.module.sha256
            │   ├── gradle-bug-reproducers-1.0.module.sha512
            │   ├── gradle-bug-reproducers-1.0.pom
            │   ├── gradle-bug-reproducers-1.0.pom.md5
            │   ├── gradle-bug-reproducers-1.0.pom.sha1
            │   ├── gradle-bug-reproducers-1.0.pom.sha256
            │   └── gradle-bug-reproducers-1.0.pom.sha512
            ├── maven-metadata.xml
            ├── maven-metadata.xml.md5
            ├── maven-metadata.xml.sha1
            ├── maven-metadata.xml.sha256
            └── maven-metadata.xml.sha512
```

```xml
% cat build/testRepo/com/example/gradle-bug-reproducers/1.0/gradle-bug-reproducers-1.0.pom
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>gradle-bug-reproducers</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>5.7.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.7.1</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```
```

**Comment by xenoterracide** [comment]
yeah, but in that example, you're not using the same API, and you don't get the typesafe accessors, and it's subject to the limitations of the maven metadata (not sure if that really matters). overall the new feature feels like an improvement, but looking at how to achieve what I'd like to achieve, doesn't feel like any of this is quite where I think it should be. in my  example you'll notice that I have a `testRuntimeOnly` dependency. You can't do that with this suggestion.

```kts
  bundle("jackson") { // maybe this is closer to a better api? but using short names instead
        api("com.fasterxml.jackson.core:jackson-annotations")
	runtimeOnly(project(":spring-boot-project:spring-boot-starters:spring-boot-starter"))
	testRuntimeOnly("org.springframework:spring-web")
	runtimeOnly(*"com.fasterxml.jackson.core:jackson-databind")
	runtimeOnly("com.fasterxml.jackson.module:jackson-module-parameter-names")
   }
```

you can of course do this with a plugin, from a readability perspective though, a plugin feels like maybe it's hiding that stuff.

I guess looking at this feature I was hoping for a BOM, typed accessors, and starters with better configuration scoping in one. realistically looks like plugins are still the only solution for this, and you'd have to publish a lot of them. you'd have to generate the plugin and publish that. 

Even then you lose the typed accessors though don't you? are those even publishable?

**Comment by vlsi** [comment]
>Even then you lose the typed accessors though don't you? are those even publishable?

You can import catalog from a file, so you can publish it.

> You can't do that with this suggestion .. `testRuntimeOnly`

Suppose the user declares **multiple** test source sets.
What do you mean by `testRuntimeOnly` there? Does it mean "apply to all test-looking sourcesets"?

In other words, the notion of "test dependency" is not really defined, so it has to be either a plugin or some modeling of the test sourcesets.

---

There's a test fixtures feature (see https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures ), and it can even heal your case with `testRuntimeOnly`, however, the problem is undecidable in general: you have no solid ground to define what `testRuntimeOnly` means.

For instance, suppose there's Kotlin Multiplatform project. What do you mean for `testRuntimeOnly` there? Is it a dependency for **all** the platforms or just for a subset of them?
