### ISSUE TITLE
Provider implements Buildable and can be used for task inference

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1718]
Spec: https://github.com/gradle/gradle/blob/master/design-docs/internal-apis-made-public.md#story-provider-implements-buildable-and-can-be-used-for-task-inference

**Comment by adammurdoch** [comment]
We might close this or re-title it. Providers can already be used for task inference, and I don't think we necessarily want `Provider` to implement `Buildable` as we might want better ways to express the things we need. For example:

- Not every provider is actually buildable or even potentially buildable
- Some providers require work other than tasks to be completed before they can be queried, for example, some input value must be configured first.
- When the provider represents something that is actually buildable, we need a way to say "I want a provider for the location but not the contents" (i.e I don't care whether the tasks that produce the contents have run or not, but I do need the tasks that calculates the locations to have run)  and "I want a provider for the location _and_ the contents" (i.e. I need the tasks that build the thing to have run).

`Provider extends Buildable` doesn't really capture any of these.

**Comment by adammurdoch** [comment]
I'm going to close this. We most likely won't make `Provider` extend `Buildable` for the reasons mention above, and task inference works for the most part. There are some edge cases and missing features with task inference, but these are covered by other issues.
