### ISSUE TITLE
tools:@keep for android resources not working on gradle version 6.7.1

### ISSUE THREAD

**Issue by JochimY** [gradle/gradle#17189]
Hi, I was using the code below to keep my proj resources from shrinking as [this link](https://developer.android.com/studio/build/shrink-code#keep-resources) says.

`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
tools:keep="@layout/l_used*_c,@layout/l_used_a,@layout/l_used_b*"
/>
`

But after update my Android Studio to 4.2.0 and gradle version to 6.7.1, the code seems not working. When i unzipped my released apk, the resource of i want to keep is renamed too.Trying tools:shrinkMode to safe or strict is not helping either. And the 6.1.1 gradle version is ok though.
So does anyone know why this is happening and help me to solve it. Many thanks.

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

**Comment by JochimY** [comment]
OK! Thank you.
