### ISSUE TITLE
Add Gradle-JDK compatibility chart

### ISSUE THREAD

**Issue by ysb33r** [gradle/gradle#17192]
### Context

It will be really helpful on the compatibility page (https://docs.gradle.org/current/userguide/compatibility.html) to also have a listing on the minimum supported version per JDK.

I find that I have to search through Release Notes on many occasions just to dteermine whther I can run Gradle with a specific JDK version. Thus a lookup table will be really useful

Such a table could simply list the JDK vs Gradle i.e. as below (I've already done the compilation work :smile: )

* 8 - 2.0
* 9 - 4.3
* 10 - 4.7
* 11 - 5.0
* 12 - 5.4
* 13 - 6.0
* 14 - 6.3
* 15 - 6.7
* 16 - 7.0

**Comment by bmuskalla** [comment]
Thanks @ysb33r for the suggestion and tracking down the data

**Comment by ysb33r** [comment]
@bmuskalla I just looked at it in the published 7.2 docs. It looks good.
