### ISSUE TITLE
Pre-Java 9 toolchains should be selected deterministically

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#17195]
In the issue #13892 it was proposed that the toolchain with the highest tool version should be used. However this doesn't hold for the per-Java 9 toolchains. This probably happens because of the different `java.version` format.

### Expected Behavior
When multiple versions of JDK 8 are installed and detected the latest one is expected to be used.

### Current Behavior
The actual used version of JDK 8 seems to be randomly selected.

### Steps to Reproduce 
1. Install two versions of AdoptOpenJDK 8 in parallel: 1.8.0_292 into  `~/.jdks/adopt-openjdk-1.8.0_292` and 1.8.0_282 into `~/.jdks/adopt-openjdk-1.8.0_282`
2. Ensure that these JDKs are available to the gradle build, e.g. by adding `gradle.properties`.
3. Use the following project: https://gist.github.com/mlopatkin/34489245b3e184b046b137bc4bf3ee4e
4. Execute `./gradlew compile` several times and observe the path to the JDK printed to the console.

The actual output seems to be affected by several non-deterministic things (parallel streams and hash map iteration order) so the reproducer may occasionally show correct toolchain (`~/.jdks/adopt-openjdk-1.8.0_292`).

### Your Environment
Reproduced with Gradle 6.8 as well as ToT on AdoptOpenJDK 11.0.11+9/Ubuntu 20.04 x86_64.

Build scan URL: https://scans.gradle.com/s/fcvkkinn72lxm

**Comment by bmuskalla** [comment]
Might be worth checking out `JavaToolchainComparator` and its `JavaToolchainComparatorTest` whether that is already flawed

**Comment by mlopatkin** [comment]
> Might be worth checking out `JavaToolchainComparator` and its `JavaToolchainComparatorTest` whether that is already flawed

I think that the version parsing of `VersionNumber` is the culprit. The debugger shows both versions as `0.0.0` so the comparator cannot do anything meaningful there. I haven't yet investigated what exactly is going wrong in the parsing code.
