### ISSUE TITLE
Get configuration error when try to substitute module with project in Gradle 6.7.1

### ISSUE THREAD

**Issue by SinoReimu** [gradle/gradle#17201]
### Expected Behavior
Dependency Resolver run well

### Current Behavior
Dependency Resolver failed
![image](https://user-images.githubusercontent.com/13306932/118382449-566f1680-b628-11eb-9d60-ef77a41c4677.png)

### Context
Our project upgrade Gradle 6.7.1 in last few days, and we use substitute to switch some aars to projects for compiling.

### Steps to Reproduce 
Very easy to reproduce! First we need 2 normal modules test1 and test2, and add those content in test1 module
```
//// some origin content
dependencies {
    implementation "com.test:test:1.0.0" // any artifact, will be replace by substitute
    //project(":test2")
}

// substitute it with project , nothing special in test2
configurations.all {
    resolutionStrategy.dependencySubstitution {
        // Substitute project and module dependencies
        substitute module('com.test:test') with project(':test2')
    }
}

// trigger a custom resolve process after evaluate, this action will fail in  `runtimeClassPath.resolvedConfiguration`
afterEvaluate {
    configurations.all {
        if (it.name == "releaseRuntimeClasspath") {
            def runtimeClassPath = it
            runtimeClassPath.resolvedConfiguration.firstLevelModuleDependencies.each {
                println it
            }
        }
    }
}
```

### Your Environment
Nothing but upgrade Gradle from 5.6 to 6.7.1

Build scan URL: https://gradle.com/s/ghgd6pyq6de5c

Thanks for your hardworking again, I'm desiring for your reply and suggest solution.

**Comment by SinoReimu** [comment]
Add a copy of text stack info here:

A problem occurred configuring project ':test'.
> Could not resolve all dependencies for configuration ':test:releaseRuntimeClasspath'.
   > Could not resolve com.test:test:1.0.0.
     Required by:
         project :test
      > No matching configuration of project :test2 was found. The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' but:
          - None of the consumable configurations have attributes.

**Comment by SinoReimu** [comment]
I have tried adding breakpoint in the error class, I found a strange appearance. 
![image](https://user-images.githubusercontent.com/13306932/118382620-05602200-b62a-11eb-8676-fdd6c28984dd.png)

**Comment by SinoReimu** [comment]
Not a bug, ignore this

**Comment by jkasten2** [comment]
@SinoReimu How did you overcome this part of the error?
```
 The consumer was configured to find a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'default' with value 'flavor' but:
          - None of the consumable configurations have attributes.
```

I am guessing since the project doesn't have the same attributes but how do I override that?

**Comment by yuezk** [comment]
@donat I encountered the same problem, and the minimal reproducible repo is https://github.com/yuezk/test-gradle-17201
