### ISSUE TITLE
Not able to send build scan when configuration cache is enabled

### ISSUE THREAD

**Issue by guilherme-pereira-ifood** [gradle/gradle#17217]
### Expected Behavior
Correctly send the build scan even when configuration cache is enabled. Or at least some logs to help me spot if the issue is on my side.

### Current Behavior
At the end of the build, I receive the message `This build uses Gradle features that are incompatible with build scans (code: late-load-build-op).`, but the logs doesn't show why. Even when running with `--debug`, this is the only message:

```
2021-05-18T09:48:30.391-0300 [WARN] [com.gradle.enterprise.gradleplugin.GradleEnterprisePlugin] 
This build uses Gradle features that are incompatible with build scans (code: late-load-build-op).
```

### Context
I've been using the [adoption steps](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:adoption) to get my project ready for Configuration Cache. The docs are great, I could get my project to work with Configuration Cache and migrate some custom tasks and custom buildscripts we have to be Configuration Cache compliant. But, one important thing for us is the build scan generated at the end of the build.

The first execution of any task, the build scan is correctly published. The second execution of the same task, the build scan is not published, returning the code `late-load-build-op`. 

### Steps to Reproduce 
Any task that I run twice (or more) causes the issue: `help`, `app:assembleDebug`, etc. I'll try to build a repro project.

### Your Environment
Gradle Enterprise Plugin 3.6.1
Android Gradle Plugin 4.2.0
Kotlin 1.5.0
Gradle 7.0.2
JDK 11
macOS Big Sur 11.3.1

**Comment by bamboo** [comment]
Hi @guilherme-pereira-ifood, the fix should be in the latest nightly, would you be so kind as to let me know whether it works for you?

```
./gradlew wrapper --gradle-version 7.1-20210522220043+0000
```

**Comment by bamboo** [comment]
Fixed by #17186

**Comment by bamboo** [comment]
Thanks for the report, @guilherme-pereira-ifood. The fix will be available in Gradle 7.1 RC1.

**Comment by guilherme-pereira-ifood** [comment]
Sorry @bamboo, I opened the issue and left for 15 days of vacation 🙈 

Just tried with Gradle 7.1-rc2 and its working 🎉 

Thanks!

**Comment by bamboo** [comment]
No worries :) Thanks for confirming it's working!
