### ISSUE TITLE
redis remote

### ISSUE THREAD

**Issue by Rbsn-joses** [gradle/gradle#17220]
good afternoon, I have been trying to find a way to test my repository with a remote redis at the time of the gradlew test, I would like to know if you have any configuration of the type.

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on discuss.gradle.org or stackoverflow.com where to get answers by the community of Gradle users.

You may also have a look at the [Testcontainers](https://www.testcontainers.org/) project.
