### ISSUE TITLE
gradle 4.1.2 on Android executed dependsOn tasks in wrong order

### ISSUE THREAD

**Issue by gmavenis** [gradle/gradle#17222]
My task:
task buildDemo(dependsOn: [
        "task1",
        "task2",
        "task3",
        "task4"]) {
doLast {....}
}
task2.mustRunAfter task1
task3.mustRunAfter task2
task4.mustRunAfter task3

When I run command: gradlew buildDemo, the tasks don't run in correct order.

**Comment by blindpirate** [comment]
Not able to reproduce. Can you share your whole `build.gradle`? 

This is my test:

```
$ cat build.gradle 
task task1 {
   doLast { println("task1") }
} 
task task2 {
   doLast { println("task2") }
} 
task task3 {
   doLast { println("task3") }
} 
task task4 {
   doLast { println("task4") }
} 

task buildDemo(dependsOn: [
"task1",
"task2",
"task3",
"task4"]) {
doLast { println('buildDemo') }
}
task2.mustRunAfter task1
task3.mustRunAfter task2
task4.mustRunAfter task3
```

```
$ ./gradlew buildDemo

> Task :task1
task1

> Task :task2
task2

> Task :task3
task3

> Task :task4
task4

> Task :buildDemo
buildDemo
```

Also, please note that Gradle and AGP are different stuff. There's no Gradle 4.1.2. Which version of Gradle you're using?

**Comment by gmavenis** [comment]
I can propose more details below, my project has multi modules.
task4 always runs first then error occurs due to no Apks to copy.

task buildDemo(dependsOn: [
        "task1",
        "task2",
        "task3",
        "task4"]) { doLast {} }
task task1(dependsOn: [":ModuleLib1:assemble"]) { doLast {} }
task task2(dependsOn: [":ModuleLib2:assemble"]) { doLast {} }
task task3(dependsOn: [":ModuleLib3:assemble"]) { doLast {} }
task task4(dependsOn: [
        ":ModuleLib1:copyApk",
        ":ModuleLib2:copyApk",
        ":ModuleLib3:copyApk"]) { doLast {} }

task4.mustRunAfter task3
task3.mustRunAfter task2
task2.mustRunAfter task1

**Comment by gmavenis** [comment]
Dear @blindpirate 

My project was running well on gradle 2.1.2, then error happens when it is upgrade to gradle 4.1.2.

**- File build.gradle (version 4.1.2)**
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.2"
        
**- File gradle-wrapper.properties**
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip

**Comment by blindpirate** [comment]
You're mixing Gradle version and AGP version, they're two different things. `4.1.2` is AGP version and `6.5` is Gradle version. Also, AGP `2.1.2` is a very old version (2016), which should not be working with Gradle `6.5`. I think you missed a lot of details, we can't help you without a reproducer project.

**Comment by gmavenis** [comment]
You can try this demo source code: https://github.com/gmavenis/demo
- Module app:

task buildDemo(dependsOn: [
        "buildModuleApks",
        "copyModuleApks"
]) { doLast { println("=== buildDemo done") } }

task buildModuleApks(dependsOn: [
        ":module1:buildApk",
        ":module2:buildApk"
]) { doLast { println("=== buildModuleApks") } }

task copyModuleApks(dependsOn: [
        ":module1:copyApk",
        ":module2:copyApk"
]) { doLast { println("=== copyModuleApks") } }

copyModuleApks.mustRunAfter buildModuleApks


- Module 1:

task buildApk(dependsOn: ["assembleDebug"]) { doLast {} }

task copyApk(type: Copy) {
    from 'build/outputs/apk/debug'
    include '*.apk'
    into '../app/src/main/assets'
}

- Module 2:

task buildApk(dependsOn: ["assembleDebug"]) { doLast {} }

task copyApk(type: Copy) {
    from 'build/outputs/apk/debug'
    include '*.apk'
    into '../app/src/main/assets'
}

===================
Actually there are no module Apk files copied to folder "/app/src/main/assets" at the first run ./gradlew buildDemo. But they will appear at the second time running this command, so confused.

**Comment by blindpirate** [comment]
You only specified the order of `copyModuleApks` and `buildModuleApks`, but not `buildApk` and `copyApk`. So it's possible that tasks are executed in the order:

- `copyApk`
- `buildApk`
- `buildModuleApks`
- `copyModuleApks`

The order can be seen with `--console=plain`.
