### ISSUE TITLE
Cannot use nested `build-logic` as included build for build logic

### ISSUE THREAD

**Issue by melix** [gradle/gradle#17228]
### Expected Behavior

The idiomatic Gradle effort suggests to use `build-logic` instead of `buildSrc` and include builds using `includeBuild 'build-logic'`. However, this recommendation breaks as soon as another included project itself uses the recommendation! I rediscovered this while working on a talk...

### Current Behavior

If 2 included builds include `build-logic` themselves, then build fails with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Included build /tmp/nested-build-logic/other/build-logic has build path :build-logic which is the same as included build /tmp/nested-build-logic/build-logic
```

### Context

Trying to use the best practice. The only workaround is to rename `build-logic` in one of the included builds to something else. This is IMO a blocker for the adoption of this pattern.

### Steps to Reproduce 

Unzip the attached project, run `gradle help`.

[nested-build-logic.tar.gz](https://github.com/gradle/gradle/files/6508950/nested-build-logic.tar.gz)

### Your Environment

Build scan URL: https://scans.gradle.com/s/zzaovdtsn52uc

**Comment by jjohannes** [comment]
Note:

The general issue is that (right now) two builds can not have the same name in a composite.

You don't need to rename any builds/folders. You can always change a name in the root build (which is under your control, even if some of the included builds is not):

In the reproducer, you can do this for example in the root's settings file:
` includeBuild('other/build-logic') { name = 'other-build-logic' }`

**Comment by melix** [comment]
mmm, the workaround doesn't work because the build I'm including is `other`, _not_ `other/build-logic`.

**Comment by jjohannes** [comment]
You still would still need to include `other` but explicitly include `other/build-logic` in addition to change the name of it.

**Comment by melix** [comment]
mmm I tried this and it fails:

```
includeBuild 'build-logic'
includeBuild 'other'
includeBuild('other/build-logic') {
   name = 'other-build-logic'
}
```

https://gradle.com/s/sv5t3dvplcpw2
