### ISSUE TITLE
Add --buildSrc-cache-dir command line option (similar to --project-cache-dir)

### ISSUE THREAD

**Issue by EdGue42** [gradle/gradle#17224]
### Expected Behavior

Allow to to override the "default" of gradle using "buildSrc/.gradle", similar to the `--project-cache-dir` command line option.

### Current Behavior

There is no way to override the "default" of gradle using "buildSrc/.gradle".

### Context

The existing cmd line option `--project-cache-dir` allows to instruct gradle to use other folders than "root-project/.gradle" for its internal caching. 

When a "buildSrc" folder exists within the project, gradle creates a separate ".gradle" folder within the "buildSrc" folder. 

Today, people who need to control the "cache" on this level can only do that for the root project folder. 
But when you need that level of control (to isolate builds from each other), then "buildSrc/.gradle" causes the exact same issues.

Adding a new command line option `--buildSrc-cache-dir` would fill that gap and make things more consistent overall.

**Comment by ov7a** [comment]
Addressed by
* https://github.com/gradle/gradle/pull/28105
