### ISSUE TITLE
Removal of deprecated classes/methods in `jvm` modules

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1722]
Classes with `@Deprecated` annotation:

- [x] ~language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/GroovyJavaJointCompiler.java~ (shouldn't be removed for backward compatibility reasons)
- [x] language-java/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJavaCompileSpec.java
- [x] language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompileSpec.java
- [x] language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java
- [x] language-java/src/main/java/org/gradle/api/tasks/compile/DependOptions.java
- [ ] ~language-java/src/main/java/org/gradle/api/tasks/compile/ForkOptions.java~
- [x] language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java
- [x] language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java (replacement addressed here: https://github.com/gradle/gradle/issues/1456)
- [x] language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/DefaultJvmLanguageCompileSpec.java
- [x] language-jvm/src/main/java/org/gradle/api/internal/tasks/compile/JvmLanguageCompileSpec.java
- [x] platform-jvm/src/main/java/org/gradle/api/java/archives/Manifest.java
- [x] platform-jvm/src/main/java/org/gradle/api/java/archives/internal/CustomManifestInternalWrapper.java
- [x] platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifest.java
- [x] ~plugins/src/main/java/org/gradle/api/internal/java/JavaLibrary.java (used by Shadow plugin)~
- [x] plugins/src/main/java/org/gradle/api/plugins/JavaPluginConvention.java

**Comment by bmuschko** [comment]
Please also see comments in https://github.com/gradle/gradle/issues/1081 in regards to `CompileOptions`.

**Comment by eriwen** [comment]
Filed https://github.com/CtripMobile/DynamicAPK/issues/86 as a courtesy to this project.

**Comment by eriwen** [comment]
Closing as complete
