### ISSUE TITLE
Allow wrapper to reuse the existing credential in the system properties

### ISSUE THREAD

**Issue by payneChen** [gradle/gradle#17223]
Allow wrapper to reuse the existing credential in the system properties

### Expected Behavior
```
systemProp.repoUsername=****
systemProp.repoPassword=****
systemProp.gradle.wrapperUserKey=repoUsername
systemProp.gradle.wrapperPasswordKey=repoPassword
```

### Current Behavior
```
systemProp.repoUsername=****
systemProp.repoPassword=****
systemProp.gradle.wrapperUser=****
systemProp.gradle.wrapperPassword=****
```

### Context

We are using the internal Jfrog Artifactory as the central dependency repositories and also the static binary sites (gradle distributions), which means actually the wrapper username and password are same as the repository user name and password. For now the credentials are duplicated to support dependency resolving and Gradle distribution downloading, but we'd like to allow wrapper to reuse the existing credential in the system properties, then easily maintain the credentials in the future if the credentials of Artifactory changed.

One solution is as following:
https://github.com/oehme/gradle/blob/master/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L175
```
        String usernameKey = System.getProperty("gradle.wrapperUserKey");
        String passwordKey = System.getProperty("gradle.wrapperPasswordKey");
        String username = usernameKey != null ? System.getProperty(usernameKey): System.getProperty("gradle.wrapperUser");
        String password = passwordKey != null ? System.getProperty(passwordKey): System.getProperty("gradle.wrapperPassword");
```

**Comment by payneChen** [comment]
> I think one downside of such fallback is that we may send the credentials to external repositories that don't belong there. @JLLeitschuh any thoughts on this?

Hi @bmuskalla , the use case to use this feature is that downloading wrapper and repositories are using the same credentials, could you elaborate more about your concern?

**Comment by JLLeitschuh** [comment]
If, on one machine, you have multiple Gradle projects that you are building, and some of these projects resolve your Gradle distribution from your internal repository, and some pull it from `services.gradle.org`, you'd end up sending your internal credentials to our server at `services.gradle.org`.

Maybe we could fix this by adding another setting in the `gradle.properties` that says, in this case, use the creds from the centralized Gradle properties.

**Comment by payneChen** [comment]
> If, on one machine, you have multiple Gradle projects that you are building, and some of these projects resolve your Gradle distribution from your internal repository, and some pull it from `services.gradle.org`, you'd end up sending your internal credentials to our server at `services.gradle.org`.
> 
> Maybe we could fix this by adding another setting in the `gradle.properties` that says, in this case, use the creds from the centralized Gradle properties.

Hi @JLLeitschuh , the scenario you posted could be another use case that we could get benefit from the new wrapper properties:
```
~/.gradle/gradle.properties (centralized credentials)
|----a-project
|.      |----gradle.properties
|.      |----gradle
|.      |.      |----wrapper
|.      |.      |.      |----gradle-wrapper.jar
|.      |.      |.      |----gradle-wrapper.properties (the default distributionUrl)
|----b-project
|.      |----gradle.properties (new wrapper properties added here: systemProp.gradle.wrapperUserKey and systemProp.gradle.wrapperPasswordKey)
|.      |----gradle
|.      |.      |----wrapper
|.      |.      |.      |----gradle-wrapper.jar
|.      |.      |.      |----gradle-wrapper.properties (distributionUrl is customized to new url which requires authentication )
```
In the above example, `systemProp.gradle.wrapperUserKey` and `systemProp.gradle.wrapperPasswordKey` are only added in "gradle.properties" of the b-project, a-project could access the default distributionUrl without credentials. Also `systemProp.gradle.wrapperUserKey` and `systemProp.gradle.wrapperPasswordKey` could be committed in to source code of different projects without security concern.

**Comment by donat** [comment]
The security concern is just one aspect of this story. From the maintenance point-of-view, basically what you are asking is to provide variable substitution in `gradle.properties`, at least for a specific use case. This would be (yet another) obscure feature that makes too complex only to benefit a few. If anything, we're trying to get rid of these features relase-by-release.
