### ISSUE TITLE
Configuration on Demand + Kotlin DSL + KMP is flaky

### ISSUE THREAD

**Issue by kurtisnelson** [gradle/gradle#17232]
After upgrading from `6.5` to `6.7.1`, our CI builds went from pretty flaky to extremely flaky.

### Expected Behavior
CI and local builds to fail similarly.

### Current Behavior
`Caused by: org.gradle.api.internal.provider.MissingValueException: Cannot query the value of task ':appCore:compileKotlinIos' property 'compilation' because it has no value available.` happens nearly every run on CI. I have not been able to reproduce locally on a Macbook or a Linux workstation, with or without a daemon.

### Context
This project is a Kotlin-multiplatform project, using `kotlin-dsl`. CI is running on CircleCI using the latest version of their Android Orb (with a manual patch for https://github.com/CircleCI-Public/android-orb/issues/21).

### Steps to Reproduce 
Removing `--configure-on-demand` fixed the flake.

### Your Environment
Build scan URL: Can provide privately.

```
Build Cache | On
Configure on demand | On
Daemon | On
Parallel | On
Background build scan publication | Off
Continue on failure | Off
Continuous | Off
Dry run | Off
Offline | Off
Re-run tasks | Off
Refresh dependencies | Off
Task inputs file capturing | Off
Configuration Cache | Not captured
File system watching | Not captured
```
```
Operating system | Linux 4.15.0-1092-aws
CPU cores | 10 cores
Max Gradle workers | 10 workers
Java runtime | Oracle OpenJDK Runtime Environment 11.0.10+9
Java VM | Oracle OpenJDK 64-Bit Server VM 11.0.10+9 (mixed mode, sharing)
Max JVM memory heap size | 1 GiB
```

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can also try a more recent version of Gradle (6.9 or 7.0.2 at this time).

**Comment by mlopatkin** [comment]
Please note that we still [don't recommend](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html#before_you_start_migrating) using configuration-on-demand with Kotlin DSL.

**Comment by mlopatkin** [comment]
The issue lacks the reproducer, so we cannot proceed. The Kotlin DSL is known to be unstable around configuration on demand.

**Comment by kurtisnelson** [comment]
This issue was opened by request of Nelson as a tracking issue/search issue. It is definitely still buggy, I'd leave the issue open until the stability is improved.
