### ISSUE TITLE
Removal of deprecated classes/methods in `logging` module

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1723]
Classes with `@Deprecated` annotation:

- [x] logging/src/main/java/org/gradle/logging/LoggingManagerInternal.java
- [x] logging/src/main/java/org/gradle/logging/ProgressLoggerFactory.java
- [x] logging/src/main/java/org/gradle/logging/StandardOutputCapture.java
- [x] logging/src/main/java/org/gradle/logging/StyledTextOutputFactory.java

**Comment by bmuschko** [comment]
Additional context in this issue: https://github.com/gradle/gradle-private/issues/83

**Comment by lacasseio** [comment]
@adammurdoch Do you think we should remove those types in Gradle 4.0? We are having the same discussion as in the issue linked by @bmuschko and would like to have your opinion on this.

**Comment by adammurdoch** [comment]
We shouldn't remove these types until they no longer leak. Currently these types are reachable from `DefaultTask` and so backed into byte code. We should first plug the leak.

**Comment by bmuschko** [comment]
@lacasseio I am not sure if we'll be able to tackle deeper changes anymore for 4.0. WDYT? We should close this issue otherwise.

**Comment by lacasseio** [comment]
I was thinking about the same thing. I will create [another issue](https://github.com/gradle/gradle/issues/1824).
