### ISSUE TITLE
Removal of deprecated classes/methods in `tooling-api` module

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1724]
Classes with `@Deprecated` annotation:

- [ ] tooling-api/src/main/java/org/gradle/tooling/model/eclipse/EclipseProjectDependency.java
- [x] tooling-api/src/main/java/org/gradle/tooling/model/idea/IdeaModuleDependency.java

The following are not being removed
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/BuildActionRunner.java
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/BuildOperationParametersVersion1.java
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/BuildParametersVersion1.java
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/ConnectionVersion4.java
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/InternalBuildActionExecutor.java
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/InternalConnection.java
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/LongRunningOperationParametersVersion1.java
- [ ] tooling-api/src/main/java/org/gradle/tooling/internal/protocol/ModelBuilder.java

**Comment by w25r** [comment]
We are closing this as it is not going to make 4.0.  I will open a new issue to be done for 5.0.

Many of the deprecated methods in the Tooling API must remain, to be able to maintain backwards and forward compatibility with different Gradle versions.  The decision was made that we SHOULD remove the deprecated public (non-internal) APIs in EclipseProjectDependency and IdeaModuleDependency.  However, this has not been done before, and will require careful thought and testing.  @adammurdoch gave a good explanation of the approach we will need to take [here](https://github.com/gradle/gradle/pull/1840#discussion_r114228491)
