### ISSUE TITLE
`gradle-test-kit` depends on `org.codehaus.groovy:groovy-all:jar`, but groovy-all has `<packaging>pom</packaging>`

### ISSUE THREAD

**Issue by cpovirk** [gradle/gradle#17249]
https://github.com/google/auto/pull/1095 attempts to upgrade our Maven project to `gradle-test-kit` 7.0.

### Expected Behavior
successful Maven build

### Current Behavior
> Could not resolve dependencies for project com.google.auto.value.it.functional:functional:jar:HEAD-SNAPSHOT: Could not find artifact org.codehaus.groovy:groovy-all:jar:3.0.7 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

### Context
My guess from https://github.com/geb/issues/issues/586#issuecomment-501741588 is that `gradle-test-kit` should be declaring its dependency on `groovy-all` as [having type `pom`](https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/3.0.7/groovy-all-3.0.7.pom), not [the default `jar`](https://repo1.maven.org/maven2/dev/gradleplugins/gradle-test-kit/7.0/gradle-test-kit-7.0.pom).

Presumably this worked OK for us with the old `gradle-test-kit` 6.8.3 because the old version's `groovy-all` dependency [was `optional`](https://repo1.maven.org/maven2/dev/gradleplugins/gradle-test-kit/6.8.3/gradle-test-kit-6.8.3.pom).

### Steps to Reproduce 
https://github.com/google/auto/pull/1095

```
mvn clean install -Dtest.include=DoesNotMatchAnything -Dmaven.javadoc.skip -f build-pom.xml
```

### Your Environment
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)

---

I'd try to put together a PR, but I don't know Gradle well enough. I'm not even sure if I'm reporting this in the right repo -- sorry if not. And of course sorry even more if I've misdiagnosed things.

**Comment by mlopatkin** [comment]
The test kit dependency that you are using is a third-party one. The POM file suggests that it lives in https://github.com/gradle-plugins/toolbox. There is nothing we can do from our side.

**Comment by cpovirk** [comment]
Oh, weird, its `<scm>` info points here. But that would certainly explain why I couldn't find the relevant code in this repo :) Thanks. Maybe I can get them to fix their metadata, too.
