### ISSUE TITLE
Add /usr/lib64/jvm as Linux Toolchain location

### ISSUE THREAD

**Issue by DJViking** [gradle/gradle#17252]
OpenJDK installed through Linux package manager is not detected by Gradle.
This is because *Common Linux Locations* contains location for 32bit installations `/usr/lib/jvm`, but not 64bit installatios `/usr/lib64/jvm`.

**Comment by bmuskalla** [comment]
@DJViking Thanks for reporting this! It would be great if you could provide a PR for this.

**Comment by DJViking** [comment]
Already submitted a PR for this.

**Comment by DJViking** [comment]
Just want to mention. I thought this was a 32bit/64bit issue.\
Turns out Ubuntu and Fedora stores their 64bit OpenJDK in `/usr/lib/jvm`.\
I am using OpenSUSE which stores it in `/usr/lib64/jvm`. Not sure why it is different.

**Comment by bmuskalla** [comment]
Thanks again for the contribution @DJViking - this will be released as part of Gradle 7.1
