### ISSUE TITLE
Dependency warning emitted despite builtBy having been specified

### ISSUE THREAD

**Issue by jimgoog** [gradle/gradle#17250]
Despite having specified a `builtBy` dependency, we are seeing a warning which states: 
```
Task ':compose:material:material-icons-core:sourceJarRelease' uses this output of task ':compose:material:material-icons-core:generateCoreIconsAllVariants' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

It is our understanding/expectation that specifying an explicit `dependsOn` would not be necessary if the input files specify that they were `builtBy` the task.

Details in this thread: https://android-review.googlesource.com/c/platform/frameworks/support/+/1713192/5/compose/material/material/icons/generator/src/main/kotlin/androidx/compose/material/icons/generator/tasks/IconSourceTasks.kt#47

**Comment by mlopatkin** [comment]
@gradle/execution Could you please take a look at that? Is there a chance of false warning here?

**Comment by wolfs** [comment]
@jimgoog Gradle should respect the `builtBy` dependency.  Can you share a reproducer for the problem? I wonder if this is related to https://github.com/gradle/gradle/issues/16962.

**Comment by wolfs** [comment]
@jimgoog Can you try with a 7.2 nightly to see if the problem persists? Please re-open this issue with a reproducer if so.
