### ISSUE TITLE
Add typed variant of `ExtensionContainer.findByName` function

### ISSUE THREAD

**Issue by osipxd** [gradle/gradle#17254]
It would be great to have a typed variant of `ExtensionContainer.findByName` function.
I've created this extension-function for my own project:

```kotlin
@Suppress("extension_shadowed_by_member")
inline fun <reified T : Any> ExtensionContainer.findByName(name: String): T? =
    findByName(name)?.let {
        it as? T
            ?: error(
                "Element '$name' of type '${it::class.java.name}' from container '$this' cannot be cast to '${T::class.qualifiedName}'.",
            )
    }
```

If this extension-function is correct, I can create Pull Request with this.

### Expected Behavior

There should be a typed variant of `findByName` similar to `getByName`:
https://github.com/gradle/gradle/blob/06140ac5fbdce282f868197064156b9b1753012f/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ExtensionContainerExtensions.kt#L50

### Current Behavior

There no such function.

### Context

- Gradle 7.0.2
- Gradle Kotlin DSL

**Comment by bmuskalla** [comment]
@osipxd Thanks for the detailed request! Would you be willing to contribute this?

**Comment by osipxd** [comment]
@bmuskalla, yes, I'll create a pull request soon

**Comment by osipxd** [comment]
@bmuskalla, I've created [a pull request](https://github.com/gradle/gradle/pull/17269) and left there some comments. Can you take a look?

**Comment by osipxd** [comment]
🙃 
Should I rebase it?

**Comment by ljacomet** [comment]
* Replaced by #25342
