### ISSUE TITLE
Cryptic IllegalArgumentException

### ISSUE THREAD

**Issue by tomas-pluskal** [gradle/gradle#17264]
Hi,
One of my builds contains a transitive dependency on uk.ac.ebi.pride.architectural.pride-logging. This artifact should be available from this repository: https://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/uk/ac/ebi/pride/architectural/pride-logging/1.0.0/
Currently, the repository is broken - it contains only the .pom file but not the corresponding .jar file.
Therefore, it is not surprising that the gradle build fails. However, it fails with a rather cryptic IllegalArgumentException:
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.IllegalArgumentException: /Users/plusik/.gradle/caches/modules-2/files-2.1/uk.ac.ebi.pride.architectural/pride-logging/1.0.0/63df375258e700783e6e134f690bbb0d22491a94/pride-logging-1.0.0.pom
```

### Expected Behavior
More meaningful error message from gradle.

### Current Behavior
Not very meaningful exception.

### Your Environment
OS: macOS 10.15.7
Gradle version: 7.0.2
Build scan URL: https://gradle.com/s/m6rolizm3zitk

**Comment by bmuskalla** [comment]
@tomas-pluskal Can you please share the snippet how you declare the dependency in your project? It seems we're trying to parse the pom file as a JPMS module (which is clearly wrong). Do you mind trying to come up with a reproducer? Thanks!

**Comment by tomas-pluskal** [comment]
This is the complete source (contains only the module declaration)

[gradle_exception_test.zip](https://github.com/gradle/gradle/files/6538867/gradle_exception_test.zip)

**Comment by donat** [comment]
Thank you for creating a reproducer so fast. I'll take a look soon.

**Comment by donat** [comment]
I was able to reproduce the problem using your sample project.
The `org.openjfx.javafxplugin` plugins applies the `org.javamodularity.moduleplugin` that seems to be the source of trouble. It seems like that the plugin modifies the `compileJava` task configuration and fails to omit poms from the module path.

**Comment by tomas-pluskal** [comment]
Is `org.javamodularity.moduleplugin` part of gradle, or is that an external plugin?

**Comment by donat** [comment]
I've reported the issue on the plugin: https://github.com/java9-modularity/gradle-modules-plugin/issues/190

**Comment by tomas-pluskal** [comment]
Thanks!
