### ISSUE TITLE
build failed, not authenticated with server 'ge.gradle.org'.

### ISSUE THREAD

**Issue by Marvinmw** [gradle/gradle#17265]
A build scan was not published as you have not authenticated with server 'ge.gradle.org'.
I git clone and cofigure git account. and then I build the project but it failed with not authenticated with server 'ge.gradle.org'.

**Comment by Marvinmw** [comment]
I use the command , ./gradlew build

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. What build do you refer to? Do you mean `gradle/gradle` itself? Ensure you have a look at the [contribution guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
