### ISSUE TITLE
Max open file limits are not considered on MacOs 

### ISSUE THREAD

**Issue by jonnybbb** [gradle/gradle#17274]
The default max open file limits on recent mac os is `10240`. To exceed this limits system wide settings can be configured e.g. 
This value can be changed by changing `ulimit -n 20000` for the current shell session.
To make the limit persistent the values must be stored in `/Library/LaunchDaemons/limit.maxfiles.plist` and loaded via launchctl. (Please note this XML may vary between Mac OS versions - the below example is for Big Sur)

```bash
sudo launchctl load -w /Library/LaunchDaemons/limit.maxfiles.plist
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple/DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
    <dict>
      <key>Label</key>
        <string>limit.maxfiles</string>
      <key>ProgramArguments</key>
        <array>
	  <string>sudo</string>
          <string>launchctl</string>
          <string>limit</string>
          <string>maxfiles</string>
          <string>655360</string>
          <string>1048576</string>
        </array>
      <key>RunAtLoad</key>
        <true />
    </dict>
  </plist>
``` 
To apply this limit for a Java process on Mac OS it is required to pass the JVM argument `-XX:-MaxFDLimit`.
> Disables the attempt to set the soft limit for the number of open file descriptors to the hard limit. By default, this option is 
> enabled on all platforms, but is ignored on Windows. The only time that you may need to disable this is on Mac OS, where
> its use imposes a maximum of 10240, which is lower than the actual system maximum. 
(https://docs.oracle.com/en/java/javase/11/tools/java.htm)

### Expected Behavior

Adding `-XX:-MaxFDLimit` to the gradle.properties file should have the desired effect and allow for more than the default `10240` open files. 

### Current Behavior

Adding `-XX:-MaxFDLimit` to the `gradle.properties` file does not get passed effectively to the build process. Therefor a build cannot be configured to have more than `10240` open files on a MacOS agent. To extend the limits to what is configured on system level the `gradlew` scripts has to be extend with something like 
```bash
if $darwin; then
    JAVA_OPTS=-XX:-MaxFDLimit
fi 
```
and 
```properties
org.gradle.jvmargs=-XX:-MaxFDLimit 
```
needs to be added to `gradle.properties`

### Steps to Reproduce 

A more detailed reproducer repository is available here: [too-many-open-files-reproducer](https://github.com/jonnybbb/too-many-open-files-reproducer) 

### Context 

Discussions on slack: 
- https://gradle.slack.com/archives/CRH3WF1S6/p1616660804019500
- https://gradle.slack.com/archives/C31L7J0P8/p1619021308050300

How to configure it in Teamcity
- https://gradle.slack.com/archives/CDH5M7FAT/p1621954130029200

A bit unrelated and might actually be a another bug uncovering this one as it holds too many open files probably from `buildSrc` build cache compilation https://gradle.slack.com/archives/CDYR952SH/p1621865413039500

### Your Environment

Mac OS Big Sur

### Other build tools
Other buildtools are also considering the `-XX:-MaxFDLimit` flag in one way or the other.

Bazel: https://github.com/bazelbuild/bazel/commit/30dd8715847e4c797cd28da13e14eab7721b518d
Pants: https://github.com/triplequote/pants/commit/0e1c89618d34c05934041af56fec1872af260475

**Comment by donat** [comment]
I'm trying to assess the situation. I've set up the `limit.maxfiles.plist` file from above locally. From what I see, I can pass `XX:-MaxFDLimit` JVM args from the command line just fine. If I run the following commands

    gradle help -Dorg.gradle.jvmargs="-XX:-MaxFDLimit"
    jcmd <daemon_pid> VM.flags

Then the `XX:-MaxFDLimit` shows up in the list of JVM flags. At the same time, `ManagementFactory.operatingSystemMXBean.maxFileDescriptorCount` still returns the default value.

**Comment by jonnybbb** [comment]
What if you do  

    export JAVA_OPTS=-XX:-MaxFDLimit
    gradle help -Dorg.gradle.jvmargs="-XX:-MaxFDLimit"
    jcmd <daemon_pid> VM.flags

**Comment by donat** [comment]
That works, but  in that case, you don't even need to specify the JVM args:

export JAVA_OPTS=-XX:-MaxFDLimit
gradle help
jcmd <daemon_pid> VM.flags # -XX:-MaxFDLimit is present

**Comment by donat** [comment]
Do we set the JVM args too late for the daemon?

**Comment by jonnybbb** [comment]
@big-guy mentioned yesterday that `org.gradle.launcher.daemon.configuration.DaemonParameters` would need to be adjusted. 
To get the non default limit I actually had to set both args `export JAVA_OPTS=-XX:-MaxFDLimit` **and**  `org.gradle.jvmargs=-XX:-MaxFDLimit`

**Comment by donat** [comment]
I've performed a few experiments and now I have a better understanding of how `MaxFDLimit` behaves on MacOS. 

`-XX:-MaxFDLimit` is a non-standard JVM argument, so we need to do further research on how it behaves on different JVMs if we wanted to add it to our sources.

Also, the flag has very particular behavior because it considers the state of the parent process:
- If the parent (Java) process doesn't have `-XX:-MaxFDLimit` set then it has the default open file limit *and* the same limit is enforced to the child processes, no matter what JVM arguments are passed to them.
- If the parent process does have `-XX:-MaxFDLimit` set then it enables the children processes to configure the open file limits. If the child processes are executed with `-XX:-MaxFDLimit` then they have increased limits.

Gradle has the parent-children setup with the daemon. Problem is, there are multiple ways to invoke Gradle:
- wrapper script
- `bin/gradle` executable
- IDE with Tooling API
- TestKit

To consistently let MaxFDLimit work for all scenarios, we'd need to add `MaxFDLimit` everywhere in the process tree, which I don't see how can we do consistently at the moment. For example in IDE, you'd need to launch the IDE itself with `-XX:-MaxFDLimit`.

I think a fair solution for this problem is to set the flag in `JAVA_OPTS` and launch Gradle with the same flag.

At the same time, I'd like to assess how the default file limit is not enough for Gradle. I think such cases should be investigated first. If it turns out, that having so many files open is not a bug and we indeed need to increase the limit then I'd come back investigate how can we do easier (wo/the workaround above) it on the Gradle side.

**Comment by Rodrigolmti** [comment]
This problem still happens on Gradle 7.4.2. I'm working on an Android project, and we started to face this problem a while ago, after 3 gradle sync the build fails with  (Too many open files).

I tried to set JVM flags but the same problem happens:

> org.gradle.jvmargs=-XX:-MaxFDLimit

I also tried to increase the macOS open files limit but no luck.

**Comment by pablobaxter** [comment]
> This problem still happens on Gradle 7.4.2. I'm working on an Android project, and we started to face this problem a while ago, after 3 gradle sync the build fails with (Too many open files).
> 
> I tried to set JVM flags but the same problem happens:
> 
> > org.gradle.jvmargs=-XX:-MaxFDLimit
> 
> I also tried to increase the macOS open files limit but no luck.

If you are seeing this issue while syncing on your IDE (ex. IntelliJ, Android Studio), you need to add the `-XX:-MaxFDLimit` to the IDE vmoptions. `Help -> Edit Custom VM options...` and add `-XX:-MaxFDLimit` to the last line. Restart your IDE and retry syncing.

**Comment by Rodrigolmti** [comment]
Hello, thanks for the answer. It does not fix the problem, adding it to the VM options. Something that helped was running these commands:

`#!/bin/bash
pkill -f "java|studio"

# Check the current hard limit of files
current_limit=$(ulimit -Hn)
echo "Current hard limit of files: $current_limit"

# Calculate the new value as 10% less than the current limit
new_limit=$(echo "$current_limit * 0.9" | bc | awk '{print int($1)}')

# Set the new value as the ulimit
ulimit -n "$new_limit"

# Export the ulimit command to the bash profile
echo "ulimit -n $new_limit $new_limit" >> "$HOME/.zshrc"

# Source the bash profile to apply the changes
source "$HOME/.bash_profile"

# Add kern.maxfiles and kern.maxfilesperproc values to sysctl.conf
echo "kern.maxfiles=$new_limit" | sudo tee -a /etc/sysctl.conf
echo "kern.maxfilesperproc=$new_limit" | sudo tee -a /etc/sysctl.conf

# Apply the changes using sysctl
sudo sysctl -w kern.maxfiles="$new_limit"
sudo sysctl -w kern.maxfilesperproc="$new_limit"

echo "New ulimit value set: $new_limit"
echo "Commands executed successfully!"
` 

But when you run these the computer starts to get really slow. So I cannot use this solution.
