### ISSUE TITLE
Feature toggle should warn user if no longer required

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#17276]
if I upgrade gradlew there's no way to tell that I can clean up existing enable features. just makes the required research harder.

**Comment by ljacomet** [comment]
Can you please share a reproducer?

There is code in place in `DefaultSettings.enableFeaturePreview` to add a deprecation warning when you use a feature preview that is no longer active.

**Comment by xenoterracide** [comment]
```
import java.nio.file.Files

rootProject.name = "brix"
enableFeaturePreview("VERSION_CATALOGS")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
enableFeaturePreview("ONE_LOCKFILE_PER_PROJECT")


file("modules").walkTopDown().maxDepth(3).onEnter { f ->
  f.isDirectory
}.asIterable()
  .filter { f -> Files.exists(f.toPath().resolve("build.gradle.kts")) }
  .map { f -> f.toPath().toString() }
  .map { path -> path.substringAfter(File.separator + "modules") }
  .forEach { relPath ->
    val proj = relPath.replace(File.separator, ":")
    include(proj)
    project(proj).projectDir = file("modules$relPath")
  }
```

```
❯ ./gradlew compileJava                                                                                                                              # brix -> master !
Type-safe dependency accessors is an incubating feature.
Type-safe project accessors is an incubating feature.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
15 actionable tasks: 15 up-to-date
```

**Comment by ljacomet** [comment]
And as indicated by the general deprecation message, if you use `--warning-mode all` you will see the explicit message about `ONE_LOCKFILE_PER_PROJECT` being deprecated.

**Comment by ljacomet** [comment]
I have confirmed this on a reproducer:
> enableFeaturePreview('ONE_LOCKFILE_PER_PROJECT') has been deprecated. This is scheduled to be removed in Gradle 8.0. The feature flag is no longer relevant, please remove it from your settings file. See https://docs.gradle.org/7.1.1/userguide/feature_lifecycle.html#feature_preview for more details.
        at settings_3oyje1r9b6upwz51d3lequolf.run(/Users/ljacomet/Development/Gradle/TK/publish-jar-with-changes/settings.gradle:4)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
