### ISSUE TITLE
Adding custom `PublishArtifact` to `MavenPublication` fails

### ISSUE THREAD

**Issue by sebersole** [gradle/gradle#17273]
Attempting to add an artifact which is a custom implementation of `PublishArtifact` to a `MavenPublication` fails because at some point the internals attempt to cast this to a `PublishArtifactInternal`.

What I expect to happen is defined in the user-guide: https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html#org.gradle.api.publish.maven.MavenPublication:artifact(java.lang.Object)

To paraphrase:

> The artifact method can take a variety of input:
> 
> * A PublishArtifact instance. Extension and classifier values are taken from the wrapped instance.
> * ...

According to the documentation, any object implementing `PublishArtifact` should be allowed.  but effectively only internally created artifacts are allowed due to this bug.

My (pseudo) code:

```
class ShadowPublishArtifact implements PublishArtifact, TaskDependency {
    ...
}

void doStuff() {
    ShadowPublishArtifact shadowPublishArtifact = ...;
    shadowMavenPublication = publishingExtension.getPublications().create( "mavenShadowArtifacts", MavenPublication.class );
    shadowMavenPublication.artifact( shadowPublishArtifact )
}
```

What actually happens:

```
* What went wrong:
A problem occurred evaluating project ':real-jakarta'.
> Could not create an instance of type org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact.
   > class org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact cannot be cast to class org.gradle.api.internal.artifacts.PublishArtifactInternal (org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @33d8bfc8; org.gradle.api.internal.artifacts.PublishArtifactInternal is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @240f8312)

....

Caused by: java.lang.ClassCastException: class org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact cannot be cast to class org.gradle.api.internal.artifacts.PublishArtifactInternal (org.hibernate.build.gradle.jakarta.shadow.ShadowPublishArtifact is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @33d8bfc8; org.gradle.api.internal.artifacts.PublishArtifactInternal is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @240f8312)
	at org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact.<init>(PublishArtifactBasedMavenArtifact.java:29)
	at org.gradle.api.publish.maven.internal.artifact.PublishArtifactBasedMavenArtifact_Decorated.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:1969)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:468)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	... 180 more
```

My env:

```
------------------------------------------------------------
Gradle 6.8
------------------------------------------------------------

Build time:   2021-01-08 16:38:46 UTC
Revision:     b7e82460c5373e194fb478a998c4fcfe7da53a7e

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.6 (AdoptOpenJDK 11.0.6+10)
OS:           Linux 5.10.8-100.fc32.x86_64 amd64

```

**Comment by vlsi** [comment]
@sebersole , I guess you should add the artifact to an outgoing configuration, and add the configuration to the softwarecomponent

**Comment by sebersole** [comment]
And all of that will somehow turn `ShadowPublishArtifact` into a `PublishArtifactInternal` implementation?

**Comment by bmuskalla** [comment]
We understand that the docs are misleading. `PublishArtifact` is marked as `@HasInternalProtocol` and thus is tied to our implementation. I think we should rework this to not have internal protocol so any implementation of `PublishArtifact` can be used. The internal protocol around `shouldBePublished` should be true for custom implementations.

**Comment by sebersole** [comment]
So I understand... are you saying that y'all will consider change this?  Or discuss changing it?  Or can the documentation at least be updated?

For what it is worth, adding the artifact with the parts of the artifact works (as a work-around):

```
shadowMavenPublication.artifact(
        shadowPublishArtifact.getFile(),
        (mavenArtifact) -> {
                mavenArtifact.setClassifier( shadowPublishArtifact.getClassifier() );
                mavenArtifact.setExtension( shadowPublishArtifact.getExtension() );
        }
);
```

**Comment by vlsi** [comment]
AFAIK, the issue with adding artifacts "as files" is that the added file will not carry metadata.
That is consumers won't really understand what is in the file.

In other words, if you publish a file as "file with classifier", then you have no clear way to specify "which classifier should be used", and you'll make it hard for the consumers to add a proper dependency (see https://blog.gradle.org/guava).

**Comment by mlopatkin** [comment]
> So I understand... are you saying that y'all will consider changing this? Or discuss changing it? Or can the documentation at least be updated?

Yes, the current plan is to change code to allow custom implementations of the `PublishArtifact`.

**Comment by sebersole** [comment]
@vlsi I am not sure what you mean.  It does include a classifier.  Did you not look at the "code that works"?  And `PublishArtifact` does define classifier : https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/PublishArtifact.html#getClassifier--

Thanks @mlopatkin and @bmuskalla !  Appreciate it

**Comment by vlsi** [comment]
@sebersole , here are the references which highlight that classifiers are poor modeling: https://github.com/gradle/gradle/issues/17169#issuecomment-838775662 , https://github.com/gradle/gradle/issues/15674#issuecomment-812390172, https://github.com/gradle/gradle/issues/16665#issuecomment-809613071

Of course, you can make "publish the file with classifier". However, that would result in an awkward user experience for those who would use the published artifact.

**Comment by sebersole** [comment]
I assume you mean variants.  I did check out variants.  The problem with
that is that a project like Hibernate gets consumed by many build tools.
Variants are unusable by other build systems, or at least Maven which is
the other build system we need to be sure these can be consumed by.  And by
the way, the classifiers were talking about here are default, sources and
javadoc - hardly unusual.

Please correct me if I'm wrong about variance, I'd love to use variants

**Comment by vlsi** [comment]
> The problem with that is that a project like Hibernate gets consumed by many build tools.

The published variants would be consumable by Maven and other build tools.

Gradle publishes variants as "files with classifiers" + extra metadata which adds extra features for Gradle.
Then Maven consumers would still be able to use regular `<classifier>whatever</classifier>` notation and Gradle consumers would be able to use rich metadata.

**Comment by sebersole** [comment]
So people usually publish sources and javadoc jars as variants?

**Comment by vlsi** [comment]
They don't always publish Gradle Metatada, but when they do they publish javadocs and sources as variants.

For instance: https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.8.0-M1/ -> junit-jupiter-engine-5.8.0-M1.module  ->

```json
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.8.0-M1-javadoc.jar",
          "url": "junit-jupiter-engine-5.8.0-M1-javadoc.jar",
          "size": 376572,
          "sha512": "2e60f4898ad5b902974a753ab6d19d4a50ebb8c71f55bab4a45bc825d3944f2a5bdd6ae80c083b07923fe17214737bcdfe9e4afa6f352464aa8ff5c24d80a4fe",
          "sha256": "3d871407404f10432bb086bf62a6d396479dbeaf9e4abeadce491cc1ec73b475",
          "sha1": "97e441563847c76075e619cfa91e97b36b7bade8",
          "md5": "b7ec35340c051c131783ce9920f69f7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.8.0-M1-sources.jar",
          "url": "junit-jupiter-engine-5.8.0-M1-sources.jar",
          "size": 122580,
          "sha512": "50045f125a7ed25807ef57557861fcb9228a1b8feb9da2df0fa076b088b1a9e977b856fcf89ecbe6d555ac2c0896bd9acb9b754e4f21a10ba2211f723e16c1f3",
          "sha256": "924b55c50d769b590cf56172c337283281c464da10fc648c9303af60054d7633",
          "sha1": "89d20bb7528e1c2f80f7302d58a10e0f76a88dd0",
          "md5": "429f1b7d27fb7e77a61e2164a469bc63"
        }
      ]
    }
```

Note how it lists attributes like `"org.gradle.docstype": "javadoc"`.
Then Gradle-based consumers can add a dependency like `org.junit.jupiter:junit-jupiter-engine:5.8.0-M1` + specify "I want javadocs", and Gradle resolves `-javadoc` artifact.

**Comment by sebersole** [comment]
I'll definitely look into this for Hibernate builds.  We have that (publishing Gradle metadata) as an item.

But for this particular item, are you saying that you think it is easier to programatically create variants compared to simply adding an artifact w/ classifier?  I looked at those APIs and they did not seem trivial.

**Comment by vlsi** [comment]
Even though I agree variants is not the most trivial feature, it is not that hard:

```kotlin
group = "com.acme"
version = "1.0"

// Here's a configuration to declare the outgoing variant
val buildScript by configurations.creating {
    description = "Declares build script outgoing variant"
    isCanBeConsumed = true
    isCanBeResolved = false
    attributes {
        // See https://docs.gradle.org/current/userguide/variant_attributes.html
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category.DOCUMENTATION))
        attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named("gradle.build"))
    }
}

// Here we add an artifact. It can be added from a task or whatever
buildScript.outgoing.artifact(file("build.gradle.kts")) {
    classifier = "gradle-kts"
}

// This is probably the most non-trivial incantation: adding the variant to "java" component
(components["java"] as AdhocComponentWithVariants).addVariantsFromConfiguration(buildScript) {
}

// This is a regular publication
publishing {
    repositories {
        maven {
            name = "test-repo"
            url = uri(layout.buildDirectory.dir("test-repo"))
        }
    }
    publications {
        create<MavenPublication>("test") {
            from(components["java"])
        }
    }
}
```

`./gradlew publishAllPublicationsToTest-repoRepository`

```
% tree build/test-repo
build/test-repo
└── com
    └── acme
        └── testng-extensions
            ├── 1.0
            │   ├── testng-extensions-1.0-gradle-kts.kts
            │   ├── testng-extensions-1.0-gradle-kts.kts.md5
            │   ├── testng-extensions-1.0-gradle-kts.kts.sha1
            │   ├── testng-extensions-1.0-sources.jar
            │   ├── testng-extensions-1.0-sources.jar.md5
            │   ├── testng-extensions-1.0-sources.jar.sha1
            │   ├── testng-extensions-1.0.jar
            │   ├── testng-extensions-1.0.jar.md5
            │   ├── testng-extensions-1.0.jar.sha1
            │   ├── testng-extensions-1.0.module
            │   ├── testng-extensions-1.0.module.md5
            │   ├── testng-extensions-1.0.module.sha1
            │   ├── testng-extensions-1.0.pom
            │   ├── testng-extensions-1.0.pom.md5
            │   └── testng-extensions-1.0.pom.sha1
            ├── maven-metadata.xml
            ├── maven-metadata.xml.md5
            └── maven-metadata.xml.sha1
```

`testng-extensions-1.0.module` ->

```json
    {
      "name": "buildScript",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "gradle.build"
      },
      "files": [
        {
          "name": "testng-extensions-1.0-gradle-kts.kts",
          "url": "testng-extensions-1.0-gradle-kts.kts",
          "size": 1258,
          "sha512": "3e5c71fb7acaf25d173781ffe0b9396116a4b01194d460d2b0b67378080fd013fa60b6e6ddee4bbd96b4d4845c38746cd7329bff110a3a18ebd0479d74c40159",
          "sha256": "591d7b1956e06f6c5708b4da4baf99ae144362b533b2427989f54db947096588",
          "sha1": "3a4c63d1c250b26d236906c27e0b68442243ee88",
          "md5": "f1ef06510c567e953683ce48b3b1e6a1"
        }
      ]
    }
```

**Comment by vlsi** [comment]
In practice, a shadow plugin contains a more-or-less the same code: https://github.com/johnrengelman/shadow/blob/7eaffb78a020e024a3618b9c6f9c54730b8f23c0/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/ShadowJavaPlugin.groovy#L37-L57 , so if you are publishing a shaded jar, then shadow plugin should be enough.

**Comment by sebersole** [comment]
You are showing that in groovy code. The recommended approach, which I
totally agree with, is to write plugins in Java.  Or used to be.  So it's
not going to be that simple from the little research I've done.  But I'll
try to map out your example to Java calls.

As far as I understand the shade plugin won't work.  It's not that simple.
The point of the plugin is to apply transformation,not just combining
things into one jar.  Maybe shade can do that :shrug:.

**Comment by vlsi** [comment]
> You are showing that in groovy code

I show Kotlin code.

> The recommended approach, which I totally agree with, is to write plugins in Java

Really? :(

If you use the plugins for Hibernate build only, you should be fine to use whatever Gradle+Kotlin version you like. They won't affect the consumers be them Maven or Gradle.

I highly recommend trying Kotlin for plugins: it is type-safe, concise, and the great thing is you can use pretty much the same syntax within `build.gradle.kts` and in the plugin code (especially if you write plugins as precompiled script plugins in `plugin-name.gradle.kts`)

If you intend to publish Gradle plugins, then you need to pick a minimal supported Gradle version.
For instance, if you want to support Gradle 5.0+, then you should be fine writing plugins with Gradle 6.8..6.9 + Kotlin that comes with Gradle.

Here's one of my recent cases (it includes integration tests with Gradle 5.0): https://github.com/allure-framework/allure-gradle/pull/61

> As far as I understand the shade plugin won't work.  It's not that simple.
>The point of the plugin is to apply transformation,not just combining
>things into one jar.  Maybe shade can do that

Frankly speaking, `shadow` plugin never really worked the way I like, so when I use the shade plugin, I use it with `apply false` mode so the plugin does **not** create its tasks and so on, then I just create a shadowing task the way I like it.

**Comment by sebersole** [comment]
I had intended to publish it.  The whole EE javax -> Jakarta is such a big cluster-f* and this transformer is absolutely needed for both implementors and users.  So I thought it would be nice to make it generic and more generally usable.  But that project is really just pissing me off.  Its completely impossible to get help there.  To the point I am really re-thinking supporting Jakarta "EE" at all and just staying on JPA 2.2. 

I very much like Kotlin... for scripts.  I am a Java developer and there is already a learning curve writing each of these plugins I write just learning new parts of Gradle.  I'm not really interested in adding yet another (granted smaller) learning curve on top of that.  And anyway, this is all stuff that is doable from Java as well.  No need to switch just to switch.

**Comment by vlsi** [comment]
> a learning curve writing each of these plugins I write just learning new parts of Gradle

Take your time, however, Kotlin did make it easier for me both writing Gradle scripts and understanding how it works.
Funny enough, that was my first Kotlin experience as well (I was like ~15 years Java/SQL before that :) ).

Of course, your experience and tastes might be different, yet I would definitely recommend giving Kotlin a try as there are more Gradle-related examples in Kotlin than in Java. Of course, the barrier is non-zero, yet the community is helpful, and it is indeed helpful that you can start writing the transformer right inside `build.gradle.kts` (I often do like that), and some time later you can copy-paste it to a plugin as-is.

> learning curve on top of that.

I guess you can relate :) https://twitter.com/VladimirSitnikv/status/1396849945764941824

**Comment by mlopatkin** [comment]
Custom implementations of `PublishArtifact` should be safe for now but I suggest switching to [Gradle-provided configurable implementation](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/ArtifactHandler.html#add-java.lang.String-java.lang.Object-org.gradle.api.Action-) and use `builtBy` to express task dependencies. We'll probably add a deprecation warning for custom implementations in the future.

**Comment by sebersole** [comment]
@mlopatkin I did not see / understand that part about the specific `ArtifactHandler#add` form.  Thanks!

@vlsi The thing I still don't understand about using variants here is that, if they really do map to classifiers in Maven, classifiers use the dependencies of the main artifact.  The "real" module (hibernate-core e.g.) uses various Java EE (javax.*) dependencies; the "shadowed" one uses Jakarta EE (jakarta.*).  These artifacts contain the same classes, just in different packages.  Trying to use `org.hibernate.orm:hibernate-core` with the "jakarta" classifier will use the Java EE dependencies which will be a runtime error for the user/consumer.  I really don't think variants / classifiers will work here
