### ISSUE TITLE
Jar.archiveBaseName doesn't make sense in multi project context

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#17292]
problem arose due to Spring Boot's use of `Copy` and the default `archiveBaseName` of `Jar`

### Expected Behavior

the `Jar` task should behave like this, in my opinion (without the println's)

```kts
tasks.withType<Jar> {
  println(archiveBaseName.get())
  archiveBaseName.set(project.path.replace(":","-").substring(1))
  println(archiveBaseName.get())
}
```

### Current Behavior

`:app` has the spring boot plugin, and `build` will fail on `BootJar` because I use `api` as more than one subproject

```
Root project 'brix'
+--- Project ':app'
+--- Project ':cli'
|    +--- Project ':cli:api'
|    \--- Project ':cli:config'
+--- Project ':config-loader'
|    +--- Project ':config-loader:api'
|    +--- Project ':config-loader:service'
|    \--- Project ':config-loader:yaml'
+--- Project ':dispatch'
+--- Project ':processor'
|    +--- Project ':processor:api'
|    \--- Project ':processor:pebble'
\--- Project ':util'
     +--- Project ':util:file'
     +--- Project ':util:lang'
     \--- Project ':util:test'
```

### Context

this is just a nuisance, also the error is misleading on how to fix

```
> Entry BOOT-INF/lib/api.jar is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

an alternative fix that might be more obvious by the error would be to have a `DuplicateStrategy.RENAME` that prefix's or maybe suffix's pre extension. Not certain if that has an unforeseen consequences in the case of jar bundling.

**Comment by bmuskalla** [comment]
I think the real solution would be for Spring Boot to use `DuplicateStratey#FAIL`. This would improve the error message as the fix needs to be done on the projects themselves. Having a `RENAME` strategy might make sense but is still confusing as builds tend to look up things by name as well and may run into other problems depending on how those files are renamed. Changing the default basename would be too large of a breaking change (and the default is in line with how maven repositories are usually using the artifactId as their name).
