### ISSUE TITLE
Provide access to input hashes to incremental tasks

### ISSUE THREAD

**Issue by slavashvets** [gradle/gradle#1729]
### The Question

How to get a Cache Key (hashsum - MD5, SHA1, SHA256, etc.) for task inputs or outputs?

I've tried to find public API for this without success. I know Gradle uses hashsum for *TaskInputs* and *TaskOutputs* under the hood and I'd like to use this to avoid double publication to a repository of binaries.

### Vital Example
Assume we have:

* Multiproject build with two subprojects: **core** and **web**
* CI job executed every Git push: `./gradlew publish`

**Goal: Avoid publication of both modules if one of them is already published.**

### Actual workaround
I have to use custom function to compute SHA1 of outputs and attach it to artifactory properties. E.g.:

```gradle
def computeCheckSum = { FileCollection fileCollection ->
  Vector<InputStream> streams = [new FileInputStream(*fileCollection.files.toSorted())]
  SequenceInputStream combinedStream = new SequenceInputStream(streams.elements())
  return DigestUtils.sha1Hex(combinedStream)
}

artifactory {
  publish {
    defaults {
      properties = ['checksum': "${ -> computeCheckSum(generateResources.outputs.files)}"]
    }
  }
}
```

### Desired behaviour
The same, but don't compute twice (use existing hashsum from Gradle). E.g.:

```gradle
artifactory {
  publish {
    defaults {
      properties = ['checksum': "${ -> generateResources.outputs.cacheKey}"]
    }
  }
}
```

**Comment by eriwen** [comment]
Thank you @slavashvets for the well-written issue. I don't think this is available, so I think we might consider this a feature request to add a public API.

**Comment by lptr** [comment]
Gradle's hashes have their own internal format, and thus aren't meant to be used externally.
