### ISSUE TITLE
Use build cache API for dependency cache

### ISSUE THREAD

**Issue by rnett** [gradle/gradle#17301]
### Expected Behavior
Gradle's dependency cache should use the build cache API or provide a similar one.  Currently you are limited a pre-populated read only cache or copying the cache around.  You could potentially use a custom setup, but the you have to handle versioning and hashing yourself.  This is non-trivial, but gradle already does it for you, so it would be nice if you could take advantage of that by providing a key-and-blob style cache API for dependencies.  This happens to be the same as what the build cache (and configuration cache) uses.  I don't know enough details of the dependency caching to know if everything is cachable, but at least the large downloads (i.e. JARs) should be, and I think transforms already are.

This would also unify the backends of all of gradle's caching mechanisms (those I know about, at least).  Currently the dependency cache is the odd one out, which is annoying when trying to use a single cache backend for the whole build.

Hopefully this would apply to everything that gets put in `jars`, as well as `modules` (does `jars` copy from `modules`?  Seems like it).

### Current Behavior
 Currently you are limited a pre-populated read only cache or copying the cache around.  You could potentially use a custom setup, but the you have to handle versioning and hashing yourself.

### Context
I'm trying to cache dependencies for my GitHub actions CI.  I can cache the entire folder (using GitHub's cache action), but the cache can't be updated so any change in dependencies (like say by running on a different OS, with something like Kotlin Multiplatform) results in either a cache invalidation or the new dependency not being cached.  This seems to be fairly standard for CI caching mechanisms (i.e. they only cache non-updatable bundles).  A fine-grained key-and-blob based API would allow me to implement my own cache backend, either using GitHub actions' cache or external solutions like a cloud provider.  I played with the idea of implementing one myself based on just the file system, but ensuring that everything is the right version is hard and error prone, and gradle already does it.

See also: https://discuss.gradle.org/t/cache-dependencies-in-build-cache-server/25319

**Comment by ljacomet** [comment]
The evolution of ephemeral CI puts some pressure indeed on the way Gradle caches dependency downloads. The solution of providing a repository mirror is not always practical for these setups.
The introduction of the read-only cache layer was made to provide a solution to this problem. The layer can be populated regularly, made available to the CI agents in general and downloads are then limited to new dependencies. But I can understand how that's a different mechanism than providing a build cache and thus one more step to configure and manage.

It would be great if cloud CI providers could effectively offer, at least for the JVM ecosystem, a mirror of popular repositories which would be co-located with the agent nodes, effectively reducing the cost of downloading dependencies.

Changing the way dependency caching works in Gradle is quite unlikely to happen in the short or medium term with the current priorities of the team.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

After further review, we can't see this as a core Gradle feature. It can be solved by having a custom artifact repository near/inside your CI. For ephemeral CI leveraging by syncing the dependency cache to the cache infrastructure.
