### ISSUE TITLE
Gradle runs dependencies of disabled tasks

### ISSUE THREAD

**Issue by jochenberger** [gradle/gradle#17306]
First of all, sorry for not posting this in the forums, but I can't seem to login using SSO and neither can I reset my password (getting a HTTP 403 from the server).
Anyway.
I observed that Gradle runs task dependencies of disabled tasks and I wonder if that's intended and - if it is - why that is the case.
Consider this example build file:
```groovy
task task1 {
  doLast {
    println "Hello from task 1"
  }
}

task task2 {
  doLast {
    println "Hello from task 2"
  }
}

task task3 {
  doLast {
    println "Hello from task 3"
  }
}

task3.dependsOn(task2)
task2.dependsOn(task1)

task2.enabled = false
```
If you run `gradle -i task3`, it correctly skips task2 but it runs task1 and task 3. I would have expected only task3 to run.
```
$ ./gradlew -i task3
Initialized native services in: /home/jochen/.gradle/native
The client will now receive all logging from the daemon (pid: 7400). The daemon log file: /home/jochen/.gradle/daemon/7.0.2/daemon-7400.out.log
Starting 7th build in daemon [uptime: 23 mins 53.9 secs, performance: 98%, non-heap usage: 32% of 256 MiB]
Using 4 worker leases.
Now considering [/tmp/sample] as hierarchies to watch
Watching the file system is enabled if available
Starting Build
Settings evaluated using settings file '/tmp/sample/settings.gradle'.
Projects loaded. Root project using build file '/tmp/sample/build.gradle'.
Included projects: [root project 'sample']

> Configure project :
Evaluating root project 'sample' using build file '/tmp/sample/build.gradle'.
All projects evaluated.
Selected primary task 'task3' from project :
Tasks to be executed: [task ':task1', task ':task2', task ':task3']
Tasks that were excluded: []
:task1 (Thread[Execution worker for ':',5,main]) started.

> Task :task1
Caching disabled for task ':task1' because:
  Build cache is disabled
Task ':task1' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Hello from task 1
:task1 (Thread[Execution worker for ':',5,main]) completed. Took 0.004 secs.
:task2 (Thread[Execution worker for ':',5,main]) started.

> Task :task2 SKIPPED
Skipping task ':task2' as task onlyIf is false.
:task2 (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:task3 (Thread[Execution worker for ':',5,main]) started.

> Task :task3
Caching disabled for task ':task3' because:
  Build cache is disabled
Task ':task3' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Hello from task 3
:task3 (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.

BUILD SUCCESSFUL in 1s
2 actionable tasks: 2 executed
```

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

What you are describing is the intended behavior, though maybe the [documentation](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:skipping_tasks) is a bit unclear. It mentions that all ways to disable the task actually disable the actions of the task. It is implied that disabling the task doesn't affect its dependencies because the status is only checked when task is about to be executed - so the dependencies are already completed at this point.
I agree that we can be a bit more explicit there to avoid confusion.

What you can try to do is to use `-x task2` [command line switch](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:excluding_tasks_from_the_command_line) to disable the task _and_ its dependencies.

**Comment by jochenberger** [comment]
Thanks for the explanation. Yes, `-x` does work. I think that, regardless of the exact wording in the docs, that behavior is not exactly intuitive, but I guess that it isn't negotiable at this point in the Gradle.lifecycle. :wink:

**Comment by martinbonnin** [comment]
If anyones comes here, you can also call `-x` programmatically by doing this:

```kotlin
gradle.startParameter.setExcludedTaskNames(listOf(...))
```
(from @Vampire answer on the [Gradle slack](https://linen.dev/s/gradle-community/t/8480656/can-i-disable-a-task-and-make-sure-its-dependencies-are-not-))
