### ISSUE TITLE
Potential memory leak in gradle daemon related to build scan plugin

### ISSUE THREAD

**Issue by kohlerm** [gradle/gradle#1730]
### Expected Behavior
no memory leaks in gradle daemon

### Current Behavior
See 
https://discuss.gradle.org/t/memory-leak-in-build-scan-plugin/22138

I've got 45 instances of org.gradle.launcher.daemon.server.scaninfo.DefaultDaemonScanInfo$2
with each of them retaining around 300Kbyte (a JSON string):

Those instances are retained by the DefaultListenerManager

### Context
I'm trying to reduce the memory footprint of the gradle daemon, because we had problems with the daemon using to much memory or running the GC too often.  

### Steps to Reproduce (for bugs)
Just run a couple of builds 

### Your Environment
Linux, latest gradle (from trunk), running build scan plugin 1.6 reporting to an internal server

**Comment by eriwen** [comment]
@oehme @ghale would one of you please consider this? The relevant code seems to have mostly been added in June and July, but perhaps you're aware of recent changes that would be the cause?

**Comment by lhotari** [comment]
I was looking for something easy to fix and picked this one. :) I made the PR #1736 to fix this problem.

**Comment by kohlerm** [comment]
Looks good to me. No instances leaked anymore in my tests!
