### ISSUE TITLE
Test.forkEvery property awkward to use from Kotlin because of getter/setter nullability mismatch

### ISSUE THREAD

**Issue by EdGue42** [gradle/gradle#17305]
### Expected Behavior
When configuring a java test task, I expect `forkEvery = 1` to work as **assignment**,  the same as  I can **assign** a value like `maxParallelForks=2`, independent whether I am using kotlin or grovy. 

### Current Behavior
For some reason, the `forkEvery` property can **only** be changed using the setter method `setForEvery(1)` when using **Kotlin**.

When using the assignment, `forkEvery = 1` gradle gives a compilation error:

> Val cannot be reassigned

Whereas using `maxParallelForks=2` just compiles nicely. 

In other words: the Test class offers various properties, they are all documented the **same** way, but some can be assigned, others can only be set using the setter method. 

### Context
This cost me like 30 minutes not understanding why I could use the one property, but the other wouldn't allow assignment.
I then had a look at the source code for the Test task, the only difference I can see is that the fork-setter takes `Long` whereas the maxpar-setter takes `int`.

### Steps to Reproduce 

```
plugins {
    `java-library`
}

tasks.withType<Test> { 
    // works
    maxParallelForks = 2;
    // works, too
    setForkEvery(1)
    // not worksy in kotlin
    forkEvery = 1
}

```

### Your Environment
Gradle 7.02 on MacOs 11.4

**Comment by mlopatkin** [comment]
> the only difference I can see is that the fork-setter takes Long

That actually is the culprit. Kotlin uses getter's return type to determine the type of the property, then tries to look up a matching setter. However, the getter for `forkEvery` has the type `Long` which isn't compatible with the nullable `Long?` argument of the setter, so the synthesized property ends up being read-only.

**Comment by eskatos** [comment]
Fixed in 
* https://github.com/gradle/gradle/pull/23435

This will be in Gradle 8.1
