### ISSUE TITLE
Specifying project status on the command line

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#17315]
### Expected Behavior
In many projects we do not specify a version and let our CI infra to provide it with `-Pversion=...`

We'd like to also be able to specify `-Dstatus=...` to override the default status.

### Current Behavior
Now we are trying to apply the same pattern with project status, and it doesn't seem to work:

Consider the build:

```
logger.lifecycle("before: $status")
if (status=='release') status = 'snapshot'
logger.lifecycle("after: $status")
```

The expectation is that if we run with `-Pstatus=release` the project will have status `release`, in all other cases - `snapshot`. In practice, the status is always `snapshot`

This works, but is way overwrought:

```
logger.lifecycle("before: $status")
project.status = (ext.properties.status ?: gradle.startParameter.projectProperties.get('status'))=='release' ? 'release' : 'snapshot'
logger.lifecycle("after: $status")
```

### Context
Some of our builds have conditional behavior, which makes sense to model as build status, except that we are triggering it with nonstandard property (i.e. `myCompanyBuildStatus`). Using `status` in the same way we use `version` would make it cleaner and more intuitive.

**Comment by bmuskalla** [comment]
Something is a bit off in your description:

> In practice, the status is always snapshot

Which makes sense given your code:
```
if (status=='release') status = 'snapshot'
```

Could you create a small reproducer to show this problem? Thanks

**Comment by oesolutions** [comment]
I suspect the code was supposed to be `if (status != 'release) ...`, however that doesn't explain why the command line specified status value is ignored.
`project.status is documented as having a default value of `release` but my project is reporting `integration` by default. Going on a bit of a hunt I found that the `base` plugin sets status to `integration` when applied, and therefore is overwriting anything set from the command line.
https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePlugin.java#L87
If I try an empty project that does not apply the `base` plugin then setting `status` from the command line works as expected.

**Comment by donat** [comment]
> Going on a bit of a hunt I found that the base plugin sets status to integration when applied, and therefore is overwriting anything set from the command line.

That was a [bug](https://github.com/gradle/gradle/issues/16946) that we've just fixed. You'll be able to set the project status anywhere in your build script in Gradle 7.2.

**Comment by donat** [comment]
This should work with the latest Gradle 7.2 snapshot.

**Comment by ddimtirov** [comment]
@bmuskalla apologies, too much coding in notepad I reversed a condition somewhere. The 7.2 fix should work for me.
