### ISSUE TITLE
DefaultManifestMergeSpec should support provider values

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#17311]
### Expected Behavior

`Provider<?>` values should work when `DefaultManifestMergeSpec` is used.

### Current Behavior

`provider(?)` is printed to the manifest.

### Context

shadow plugin uses `DefaultManifestMergeSpec`

https://github.com/johnrengelman/shadow/blob/7eaffb78a020e024a3618b9c6f9c54730b8f23c0/src/main/groovy/com/github/jengelman/gradle/plugins/shadow/tasks/DefaultInheritManifest.groovy#L31-L37

Gradle calls `Provider#toString()`: https://github.com/gradle/gradle/blob/c2512b44c9259a6a4afa17a849315252bfa9245c/subprojects/platform-jvm/src/main/java/org/gradle/api/java/archives/internal/DefaultManifestMergeSpec.java#L125

### Steps to Reproduce 

```
plugins {
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

tasks.shadowJar {
    manifest.attributes["hello"] = provider { "world" }
}
```

<img width="1257" alt="Снимок экрана 2021-05-29 в 00 03 30" src="https://user-images.githubusercontent.com/213894/120041887-c199ef00-c011-11eb-866a-2bca347e3eff.png">

### Your Environment

Gradle 7.0.2

**Comment by bmuskalla** [comment]
Marking this as a dup of #14972
