### ISSUE TITLE
Improve versions numbering on GitHub

### ISSUE THREAD

**Issue by pvegh** [gradle/gradle#17329]
One page 3 versioning schemes.
Can you guess which one is correct?
We can't really :)

<img width="628" alt="gradle ver fail" src="https://user-images.githubusercontent.com/3873889/120271631-f9bc5e80-c2ab-11eb-9ed3-5207970ff467.png">

**Comment by ljacomet** [comment]
I understand that the different notation are not ideal. They are however clear for a human reading them.
Can you share the context in which you would want to get a version from this page?

**Comment by pvegh** [comment]
Having used Gradle 6 for a while, we have been increasing it for many months, remembering it like 6.8.3.
Then 7.0 was released and we tried to switch by changing it to 7.0.0, which just doesn't work. Then it's a trial and error to find the right notation.
Just an unnecessary hurdle.

**Comment by ljacomet** [comment]
Indeed major Gradle versions always have only two digits: 5.0, 6.0 and 7.0

Were you changing the wrapper properties by hand or using the `wrapper` task?
I think the later would benefit from being lenient to trailing `.0` on major versions.

**Comment by pvegh** [comment]
Thanks for that tip.
By hand, because the wrapper command is not easily remembered by all. It's also more keystrokes, and you need to open a terminal for it, and cd into the right place. Much more effort than changing a string

**Comment by ljacomet** [comment]
I will be closing this as there is no plan to change the versioning scheme or the different ways it appears in tools.
