### ISSUE TITLE
DefaultArtifactResolutionResult.getResolvedComponents() can return UnresolvedArtifactResult

### ISSUE THREAD

**Issue by Nourepide** [gradle/gradle#17320]
After clean start Gradle 7.0.2 and execute getResolvedComponents() I can get objects with type UnresolvedArtifactResult.

<img width="1351" alt="screenshot" src="https://user-images.githubusercontent.com/22074527/120186702-828bb980-c21c-11eb-9921-5bdd5d8aa992.png">

### Expected Behavior

I will get ResolvedArtifactResult.
### Current Behavior

After clean start I can get UnresolvedArtifactResult.
### Context

Migration after 6.8.3 to 7.0.2
### Steps to Reproduce 

Delete .gradle and build, start execute task

### Your Environment

macOS 10.15.7 OpenJDK 16

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by mlopatkin** [comment]
We can't really proceed without a reproducer here. Sorry about that.
