### ISSUE TITLE
JVM toolchains support should prioritize ARM over x86 JVMs on ARM environments

### ISSUE THREAD

**Issue by bsideup** [gradle/gradle#17323]
Hi! The toolchains support is super awesome, thanks for adding it!

One thing I noticed after adding it is that my build became significantly slower (22s vs 8s). Apparently, the culprit was that AdoptOpenJDK x86 build (vs Azul's Zulu ARM). I am not Apple M1, so both work, but the x86 one is getting translated with Rosetta 2 its performance isn't as good as the ARM build.

### Expected Behavior
ARM build is preferred over x86

### Current Behavior
AdoptOpenJDK's x86 build gets selected by Gradle

### Context
- Mac OS X
- Apple Silicon M1 processor
- Rosetta 2 installed
- 
```shell
% ../gradlew javaToolchains

> Task :example:javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + AdoptOpenJDK 16.0.1
     | Location:           /Library/Java/JavaVirtualMachines/adoptopenjdk-16.jdk/Contents/Home
     | Language Version:   16
     | Vendor:             AdoptOpenJDK
     | Is JDK:             true
     | Detected by:        macOS java_home

 + Zulu JDK 16.0.1
     | Location:           /Library/Java/JavaVirtualMachines/zulu-16.jdk/Contents/Home
     | Language Version:   16
     | Vendor:             Zulu
     | Is JDK:             true
     | Detected by:        Current JVM
```

FTR setting `vendor = JvmVendorSpec.AZUL` makes it fast again :)

**Comment by gwinstanley** [comment]
Certainly this is still an issue on Gradle 8.4; additionally it would ideally be possible to specify which architecture should be selected by Gradle, with default to auto-select current architecture, which would allow to optionally use Rosetta when needed (e.g. using x86_64 JavaFX, or cross-building an x86_64 runtime via jlink).

**Comment by ov7a** [comment]
Sorry for the late reply.

The issue is in the backlog of the relevant team and is prioritized by them.

***

Gradle should do the sorting.

Currently, Gradle will prefer the installed x86 toolchain over requesting an ARM version to be provisioned. It's unlikely that it will be changed.
