### ISSUE TITLE
resolvedVariant.attributes has wrong Attribute key for platform dependencies, so getAttribute(Category.CATEGORY_ATTRIBUTE) returns null

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#17338]
### Expected Behavior

`resolvedVariant.attributes.getAttribute(Category.CATEGORY_ATTRIBUTE)` should return the value of `category`

### Current Behavior

Gradle returns `null`

### Context

I want to resolve a dependency tree, and cherry-pick certain dependencies from there and add them to another configuration for building a shaded jar.
However, I can't identify if a particular variant resolved to a platform or not since `getAttribute(Category)` yields `null`.

### Steps to Reproduce 

settings.gradle.kts:

```kotlin
include(":bom")
```

build.gradle.kts:

```kotlin
plugins {
    `java-library`
}

group = "com.example"
version = "1.0"

project(":bom") {
    apply(plugin = "java-platform")
}

dependencies {
    implementation(platform(project(":bom")))
}

val resolveClasspath by tasks.registering {
    doLast {
        val c = configurations.compileClasspath.incoming.resolutionResult.allDependencies.first()
        c as ResolvedDependencyResult
        val attrs = c.resolvedVariant.attributes
        println("resolvedVariant.attributes: $attrs")
        println("resolvedVariant.attributes.getAttribute(Category.CATEGORY_ATTRIBUTE): ${attrs.getAttribute(Category.CATEGORY_ATTRIBUTE)}")
    }
}
```

Execute `./gradlew resolveClasspath`

Actual output is

```
> Task :resolveClasspath
resolvedVariant.attributes: {org.gradle.category=platform, org.gradle.usage=java-api}
resolvedVariant.attributes.getAttribute(Category.CATEGORY_ATTRIBUTE): null
```

Here's a relevant debug view. Note that the map stores key with `Attribute(...type=class String)` while `Category.CATEGORY_ATTRIBUTE` is `Attribute(...type=interface Category)`

<img width="1224" alt="getAttribute debug view" src="https://user-images.githubusercontent.com/213894/120385044-9b38c400-c32f-11eb-9c57-a3f2fab26984.png">

### Your Environment

Gradle 7.0

**Comment by melix** [comment]
This isn't a bug but a consequence of "desugaring": when you see the resolved graph, what you see is the "desugared" view of the dependency tree. That is, when attributes are typically read from external dependencies, the attributes are "untyped" in the sense that everything is a `String`. So the category attribute that you will see in this API will be typed `String`. I do agree that this is not super intuitive, and believe me it led to quite some hair pulling (I wouldn't say that's the reason why I lost mine, though).

**Comment by mlopatkin** [comment]
This one looks similar to the #16919

**Comment by vlsi** [comment]
Do you mean the issue is metadata does not store the type of attributes?

**Comment by melix** [comment]
That's not really that it doesn't store the type, it's that the type interpretation is up to the consumer. In module metadata, you'd see, for example:

```
"org.gradle.category": "library"
```

where there's nothing saying that `org.gradle.category` must be of type `Category`. It's even more complicated with composite builds, where typically the attribute types may come from different classloaders, so there wouldn't be a consistent way to get "the right type".

So the rule of thumb is that within a single project, to _declare_ and _reason about_ attribute selection, you have to apply a plugin which declares the schema and reasons about attributes _within the context of the project_, but for anything which crosses the project boundaries, which is the case with a resolved dependency graph, then things are "desugared".

**Comment by vlsi** [comment]
My use case is within a single project.

I create a configuration, resolve it, then I want to examine a resolution result and I want to cherry-pick some of the resolved components and add them to `runtimeElements` and `apiElements`, so the selected items appear in `pom.xml`.

My PR is https://github.com/cbeust/testng/pull/2564.
The issue I have is that sometimes the resolution result contains "regular dependencies", and sometimes it contains "platform dependencies". If I want to convert them back to a dependency, I need to know if I should wrap the dependency in `platform(...)` call or not.

Here's how I do it now: https://github.com/vlsi/testng/blob/split_modules/build-logic/publishing/src/main/kotlin/buildlogic/DependencyHandlerExtensions.kt#L18

Do you suggest that when accessing resolution results I should manually craft `Attribute<String>` for `org.gradle.category`? That sounds sad :-/
What I do currently is I just iterate over all the keys and find the attribute by its name

> where typically the attribute types may come from different classloaders

Oh, that is complicated :(

Of course, it is tempting to make the attributes "text-only" with convenience typed setters. For instance, `enum DefaultCategories implements Category { LIBRARY, PLATFORM; }` while the internal storage could still remain string-based.

**Comment by ljacomet** [comment]
There is no plan to change the way attributes behave even though it is not ideal. If you have suggestion on how documentation could be improved that would be great.
