### ISSUE TITLE
PlayTestPlugin compile task does not manage resources

### ISSUE THREAD

**Issue by zdglagola** [gradle/gradle#1734]
Noticed this today when i tried to load resources from my Play on Gradle test classes. Looking at the PlayTestPlugin https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayTestPlugin.java#L59 it looks like the compile task is of type PlatformScalaCompile, which isn't bad, but doesn't seem to manage resource files on the classpath and instead only pays attention to compile-able java/scala code. From my understanding of the JavaPlugin, all defined source sets support a resource dir options, and JavaPlugin leverages the Copy task under the hood to set those resources on the classpath. Creating a small Copy task and having the test commands depend on them does the trick... although, because of Play's directory structure (test/resources) making it Intellij IDEA compatible means appending the /resources to the path which is a bit ugly.

Anyways, hope this is relevant and improves the platform :)

build.gradle
```
apply plugin: 'play'

dependencies {
  ...
}

model {
    components {
        play {
            platform play: '2.4.0', scala: '2.10', java: '1.8'
        }
    }
}
```
Env:
gradle 3.5-rc-1

**Comment by lacasseio** [comment]
It seems more like a feature request then a regression. Can you confirm this was working previously (Gradle 3.4) and was broken with Gradle 3.5 RC1?

**Comment by zdglagola** [comment]
Sorry, clarification. It wasn't working in any version.
