### ISSUE TITLE
Reading project.properties triggers configuration of any DeferredConfigurable extensions

### ISSUE THREAD

**Issue by rodney757** [gradle/gradle#1735]
[This is a previous bug on JIRA](https://issues.gradle.org/browse/GRADLE-2754)

That is still present on 3.4.1

### Expected Behavior
DeferredConfigurable should not be triggered until as late as possible

### Current Behavior
accessing project.properties instance will trigger the publishing configuration to be resolved

**Comment by oehme** [comment]
Duplicate of #2496
