### ISSUE TITLE
Can't use `credentials(HttpHeaderCredentials)` without body in repositories

### ISSUE THREAD

**Issue by utybo** [gradle/gradle#17369]
The docs in [here](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials) seem to suggest I can use HTTP header authentication for my secured repos while keeping the header's name and value as properties somewhere else, but I can't actually do that. The [code here](https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/model-core/src/main/java/org/gradle/api/internal/provider/CredentialsProviderFactory.java#L63) seems to be the culprit.

### Expected Behavior

I can use this in my `build.gradle`:

```groovy
maven {
    name = "foobar"
    url = "https://my.awesome.repo.example.com"
    credentials(HttpHeaderCredentials)
    authentication {
        header(HttpHeaderAuthentication)
    }
}
```

By putting this in some properties file (e.g. `~/.gradle/gradle.properties`):

```properties
foobarName = Private-Token
fobarValue = MyVeryPrivateToken
```

### Current Behavior

I get the following error:

```
* What went wrong:
A problem occurred configuring root project 'project-name-here'.
> Failed to notify project evaluation listener.
   > Unsupported credentials type: interface org.gradle.api.credentials.HttpHeaderCredentials
   > Unsupported credentials type: interface org.gradle.api.credentials.HttpHeaderCredentials
```

Note that I can still use this repository by providing the name and value within a lambda as described [here](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:http-header-auth)

### Context

I am trying to log in to a private repository. I expected to be able to do what was [said in the documentation](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials) to do this cleanly, but turns out that I can't.

### Steps to Reproduce 

* Get a private Maven repository
* Try to authenticate to it using what I described in "expected behavior"
* Try to build or do anything that requires authenticating to the repo.

### Your Environment

Build scan URL: I do not think I can provide a build scan as this was done in a private, non-disclosable repository.

**Comment by utybo** [comment]
Possible workaround: manually set the name and value to the property you want to use, e.g.:

```
maven {
    name = "foobar"
    url = "https://my.awesome.repo.example.com"
    credentials(HttpHeaderCredentials) {
        name = "Header-Name-Isnt-Really-Secret-Is-It"
        value = superSecretValueStoredInProperty
    }
    authentication {
        header(HttpHeaderAuthentication)
    }
}
```

```properties
superSecretValueStoredInProperty = ItsDangerousToGoAlone
```

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

I agree that the documentation doesn't clearly state that only a subset of `Credentials` can be used this way. It is possible to add support for the `HttpHeaderCredentials` as well. Would you like to submit a pull request for this as you've already found the relevant piece of code?

**Comment by utybo** [comment]
Sure! I can give it a try.
