### ISSUE TITLE
Treat Maven snapshot dependencies as dynamic versions

### ISSUE THREAD

**Issue by cshannon** [gradle/gradle#1737]
This is a follow on issue opened after discussion about https://github.com/gradle/gradle/issues/1397 on the developers list.

As discussed on the developers list it would be beneficial to allow the dynamic versions dependency resolution feature to be expanded to support unique maven snapshots.  This would allow the newest time stamped version to be use.

As described in issue 1397, normally with maven snapshot dependencies are used as a changing module.  The problem with this is that many times it is desirable to get the latest snapshot regardless of where it lives.  The main example is having a maven local repository and a remote repository.  A typical workflow is to want to check the remote repository and maven local and use whichever version is newer.

See https://groups.google.com/forum/#!topic/gradle-dev/7HSrC5XC_VU for the full history of the discussion.

### Expected Behavior
During dependency resolution gradle will look across all repositories for the latest unique snapshot version.  This is the same behavior now as dynamic versions but expanded to snapshots.  One issue with this is how to handle maven local artifacts.  Deployed snapshots to a server are time stamped but artifacts deployed locally are a bit different.

### Current Behavior
Currently when using snapshots it is configured as a changing module.  The repositories are searched in order and the first repository to have the snapshot will be used.  This means that even if a repository has a newer version it will never get used if it is second in the repository list.

### Context
This issue has come up a lot in large teams with independent projects.  I work in an environment where independent teams work on their own projects and each team shares the latest code by snapshots during new development.  Also sometimes developers are working on projects that are independent but have dependencies on each other.  In this case snapshots might be deployed to maven local or deployed to a server (like nexus) most of the time it is desirable to have the latest version used automatically across the repositories.

**Comment by cshannon** [comment]
The main issue I see here is handling maven local and how to determine the timestamps.  Just relying on the filesystem time on the metadata isn't good enough because the pom won't always be updated when a new version is pulled down if it hasn't changed.  (Such as if another maven project uses the dependency).

For comparing timestamps for a Maven local repository both the maven-metadata-local.xml and maven-metadata-snapshots.xml usually need to be checked for the last updated timestamp.  Both files have to be checked because maven-metadata-local.xml will be updated if a "mvn install" has been run on a project to install it locally and the "maven-metadata-snapshots.xml" will be updated if a maven build pulls down the latest snapshot.

**Comment by Dunemaster** [comment]
Any news on this feature?

**Comment by cshannon** [comment]
I am still hoping to work on this when I get a chance but I have been pretty busy with work recently.  Any one else who has time can also take a look at implementing this as well.

**Comment by iwan-aucamp-cs** [comment]
related gradle/gradle#1397

**Comment by vehovsky** [comment]
Hi,

I also see this as quite big issue for coexisting gradle and maven projects.

I took a look on it over the weekend and seems to me that the ground work is already in place.

There were few missing bits and pieces of course. Would someone from Gradle core team be so kind and gave it a quick look, please?
https://github.com/vehovsky/gradle/commit/33a8979d62a6b152bdccee50527cfa873104314a

It's not ready for pull request at all, as I'm missing unit tests / integration tests / documentation.

I would also be interested in opinions if the search should include all remotes? Stop on first remote? Make it configurable?

Thanks

**Comment by chhex** [comment]
From my point view, the way both Gradle and Buildship deal with Maven SNAPSHOTS, is a big reasons why still so many use Maven.  SNAPSHOT is a Maven "creation" , Gradle should adopt the Maven SNAPSHOTS in back compatible way, both in Buildship and Standalone, Currently neither does that in satisfactory way
