### ISSUE TITLE
Junit 5 XML report does not respect dynamic test containers

### ISSUE THREAD

**Issue by ecopoesis** [gradle/gradle#17384]
When running Junit 5 dynamic tests, container names are ignored by the test reporter that creates XML files.

### Expected Behavior

In Junit 5 when using nested test classes each test class gets its own XML file. This test file:
```java
package org.miker;

import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class StaticTest {

    @Test
    public void topLevelTest() {
        assertTrue(true);
    }

    @Nested
    class Inner {
        @Test
        public void middleTest() {
            assertTrue(true);
        }

        @Nested
        class Deep {
            @Test
            public void deepTest() {
                assertTrue(true);
            }
        }
    }
}
```

creates the XML files:
```
TEST-org.miker.StaticTest$Inner$Deep.xml
TEST-org.miker.StaticTest$Inner.xml
TEST-org.miker.StaticTest.xml
```

I would expect `DynamicContainer` to work like the nested classes, but it does not.

### Current Behavior

A dynamic version of the test from above:

```java
package org.miker;

import org.junit.jupiter.api.DynamicNode;
import org.junit.jupiter.api.TestFactory;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.DynamicContainer.dynamicContainer;
import static org.junit.jupiter.api.DynamicTest.dynamicTest;

public class DynamicTest {

    @TestFactory
    public List<DynamicNode> factory() {
        return new ArrayList<>(){{
            add(dynamicTest("topLevelTest", () -> assertTrue(true)));
            add(dynamicContainer("Inner",
                    new ArrayList<>(){{
                        add(dynamicTest("middleTest", () -> assertTrue(true)));
                        add(dynamicContainer("Deep",
                                new ArrayList<>(){{
                                    add(dynamicTest("deepTest", () -> assertTrue(true)));
                                }}
                        ));
                    }}
            ));
        }};
    }
}
```

creates only a single XML file:
```
TEST-org.miker.DynamicTest.xml
```

This behavior is the same regardless of the setting of `reports.junitXml.outputPerTestCase`.

### Context

I have a dynamic test class that generates ~250,000 individual tests. Their results all end up in the same XML which our CI system (Team City) is slow to process. Many, smaller XML will be easier for Team City to process. Also a file per container would be my expectation: the dynamic container / test hierarchy maps to the static class / test hierarchy. Tools like IntelliJ handle this case, I expect Gradle's XML output to behave similarly.

<img width="246" alt="Screen Shot 2021-06-08 at 2 53 59 PM" src="https://user-images.githubusercontent.com/1123109/121241419-6a91e680-c869-11eb-8cd8-5e4caf4a056b.png">

Here are some related issues that may help with resolving this:
https://github.com/gradle/gradle/issues/4424
https://github.com/gradle/gradle/issues/4438
https://github.com/gradle/gradle/issues/5975
https://github.com/gradle/gradle/issues/10983

### Steps to Reproduce 

This project has both the static and dynamic versions of the tests: https://github.com/ecopoesis/junit-5-reporting-bug

### Your Environment

Build scan URL: https://scans.gradle.com/s/lq2jqtd66cy4a

**Comment by ljacomet** [comment]
@marcphilipp Can you confirm that's a valid expectation and something Gradle should handle vs. Junit doing it?

**Comment by marcphilipp** [comment]
Generating ~250,000 individual tests is rather extreme -- I'm not surprised parsing that is slow. Are you sure that would be faster if it was ~250,000 individual files?

`reports.junitXml.outputPerTestCase` controls on which level stdout/stderr is written into the XML report of the test class, not the granularity of XML report files being generated. Hence, this is certainly not a bug but works as designed.

**Comment by ljacomet** [comment]
@ecopoesis Given the comment from Marc above, could you please follow up and make sure that the difference in behaviour is caused by Gradle compared to what would happen with a plain JUnit 5 execution?

If there is no difference, then the request would need to be filed against JUnit and not Gradle.

**Comment by marcphilipp** [comment]
The JUnit Platform currently writes one XML file per test engine, i.e. an even broader one.

**Comment by ansman** [comment]
Still an issue with 8.10.2
