### ISSUE TITLE
providedRuntime is added to compileClasspath when using the war plugin

### ISSUE THREAD

**Issue by BigMichi1** [gradle/gradle#17415]
I'm currently investigating an issue reported here: https://github.com/gradle-dependency-analyze/gradle-dependency-analyze/issues/192 
and it looks like that with Gradle 7 there was a change that I was not able to find documentation for that the providedRuntime configuration is now also added to the compileClasspath configuration while it was not added in Gradle before version 7

### Expected Behavior
by reading the documentation of the war plugin the providedRuntime should not be part of the compileClasspath only providedCompile

### Current Behavior
providedRuntime configuration is part of the compileClasspath

### Context
this issue affects now how the gradle-dependency-analyze detects unused dependencies. it currently does it by considering everything that is on the compileClasspath and check if classes from these artifacts are used. as now also providedRuntime is part of the compileClasspath this results in errors because the plugin detects no class usages from these artifacts

### Steps to Reproduce 
there is a test case showing that behaviour difference between 6.9 and 7.0 in the linked issue/pr

https://github.com/gradle-dependency-analyze/gradle-dependency-analyze/pull/193/files

### Your Environment
Gradle 6.9 and Gradle 7.0.2

**Comment by ljacomet** [comment]
This change was done following #16406

**Comment by ljacomet** [comment]
This is indeed a bug that happened when removing the legacy `compile` and `runtime` configurations.
Working on a fix for Gradle 7.3.
