### ISSUE TITLE
PMD shows "Error during type resolution" while reported class is available on runtimeClasspath

### ISSUE THREAD

**Issue by huxi** [gradle/gradle#17410]
I reported pmd/pmd#3330 but was informed that this is [actually a Gradle bug](https://github.com/pmd/pmd/issues/3330#issuecomment-857835037).

### Expected Behavior
No "Error during type resolution" should be reported.

### Current Behavior
The class mentioned in the error message is part of `runtimeClasspath` so it should be available to the plugin.

```
> Task :project2:pmdMain
Error during type resolution of field 'BZIP' in class project1.Compression due to: java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/bzip2/BZip2CompressorOutputStream

BUILD SUCCESSFUL in 5s
8 actionable tasks: 8 executed
```

See [README](https://github.com/huxi/pmd-type-resolution/blob/main/README.md) for more output like dependency tree.

### Context
I'm not sure about the exact impact but I suspect the PMD plugin isn't working as expected and might
miss issues in the checked code.

Even if that's not the case, the false error message is cluttering the build output.

### Steps to Reproduce 

- clone https://github.com/huxi/pmd-type-resolution
- execute `./gradlew`

### Your Environment
```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 11.4 x86_64
```

**Comment by adangel** [comment]
I'm not sure, this is a problem of the runtime classpath (I've checked maven-pmd-plugin and there we use just the compile-classpath as well).

Here's the dependency configuration:

```
def project1 = project(':project1') {
    dependencies {
        implementation 'org.apache.commons:commons-compress:1.20'
    }
}

project(':project2') {
    dependencies {
        implementation project1
        // implementation 'org.apache.commons:commons-compress:1.20'  // adding this line would fix the problem
    }
}
```

The missing class comes in from commons-compress. project2 depends on project1, which depends on commons-compress. It looks like that gradle doesn't resolve transitive dependencies when you have a project dependency?

The missing class is found, if the dependency is explicitly added to project2.

**Comment by mlopatkin** [comment]
>gradle doesn't resolve transitive dependencies when you have a project dependency?

When you add a dependency `commons-compress` to the project1 as an `implementation`, it is not added to the compilation classpath of the project2 - this is the intended behavior of the `implementation` scope. The `common-compress` is considered an implementation detail of the project1. AFAIK, Maven has no similar `implementation` concept and just adds all transitive dependencies to the compilation classpath thus avoiding the problem. PMD expects a more or less "closed" classpath so Maven's approach works better there.

Adding a runtime classpath solves the issue but only of `implementation` scope. There is a `compileOnly` scope that isn't on the runtime classpath but dependencies may reference classes from this scope.
