### ISSUE TITLE
Gradle task execution hangs when gradle home dir is an input

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#17420]
Repro snippet:

```kotlin
internal abstract class Example : DefaultTask() {
  @get:PathSensitive(PathSensitivity.ABSOLUTE)
  @get:InputDirectory
  abstract val gradleHomeDir: DirectoryProperty
  
  companion object {
    fun register(project: Project): TaskProvider<Example> {
      return project.tasks.register<Example>("example") {
        val gradleHome = project.gradle.gradleUserHomeDir
        gradleHomeDir.set(gradleHome)
      }
    }
  }
}

// Now run "./gradlew example" and observe that gradle hangs up when trying to run the task
```

### Expected Behavior
It should not hang

### Current Behavior
It hangs when executed. The task inputs are computed but it never begins executing the task

### Context
This used to work. We use this in a one-off task for bootstrapping our repo for local development

### Steps to Reproduce 
See above. This used to work around gradle 6.x times but it's been awhile since I last checked. In any case, it seems like a bug for it to just hang up like this.

### Your Environment

Build scan URL: N/A because it hangs.

macOS 11.4, multiple java versions.

**Comment by ZacSweers** [comment]
In our case we use this task to prepare the user's local environment for development. The example above is just a trivial repro case

**Comment by lptr** [comment]
You can now use an `@UntrackedTask` for this.
