### ISSUE TITLE
Regression in latest nightly around `dependencyInsight` changes

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#17423]
### Expected Behavior

ConfigurationContainer rules should be accounted for when searching for configuration by name. The suggested fix is to `findByName` first and if the result is `null`, then proceed with a name matcher using `getAsMap()`. This way the rules have a chance to trigger and create any of the required configurations. Then, if nothing is found, we may be using a short name which we can try to find among all configurations (current and generated by rules).

### Current Behavior

The changes in https://github.com/gradle/gradle/pull/16142 don't account for rules anymore. It uses [`getAsMap()`](https://github.com/gradle/gradle/commit/c190a1ba9997db532884c0f0a443dc4b29c638d2#diff-9c98c9ba8979d3a753ca3ebdc39a2c5d84bef93c3889132cc0ff67bf8702eedaR30) which doesn't trigger any rules.

### Context

See https://github.com/gradle/gradle/pull/16142#issuecomment-859076187

### Your Environment

Build scan URL:

**Comment by donat** [comment]
I've reverted the changes and notified the contributor about the broken behavior: https://github.com/gradle/gradle/pull/17428
