### ISSUE TITLE
The application plugin's "run" task should be able to take program arguments

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#1743]
The [application plugin](https://docs.gradle.org/current/userguide/application_plugin.html) provides a `run` task which should be able to take command line arguments that get passed to the application's main class.

### Expected Behavior

After applying the `application` plugin, it should work to pass command line arguments like e.g. `-s` and `--long` to the main class' `main` method like

    ./gradlew run -args -s --long

### Current Behavior

Gradle interprets `-args` as `-a -r -g -s` arguments to Gradle itself (not to the `run` task) and says:

```
$ ./gradlew run -args -s -long

No argument was provided for command-line option '-g'.

USAGE: gradlew [option...] [task...]
```

### Context

To test command line applications, using the `run` task is more convenient that manually running `java -jar` with the proper classpath set to run the application. But for that `run` needs a way to pass command line arguments for the application.

### Your Environment

Running Gradle 3.4.1 on Windows 10 64-bit.

**Comment by JakeWharton** [comment]
Perhaps trivially solvable now with https://docs.gradle.org/4.6/release-notes.html#tasks-api-allows-custom-command-line-options? `--args="-s -long"`, although that makes nested strings annoying but oh well...

**Comment by sschuberth** [comment]
Unfortunately, it's not as trivial as just adding the `@Option` annotation to a setter as the `run` task [is created programmatically](https://github.com/gradle/gradle/blob/cfafbafbf5f9f856f83c18a79e6bf7058bd8620f/subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPlugin.java#L122).
