### ISSUE TITLE
Either make the shared service registry thread-safe, or document/enforce that it shouldn't be used from tasks

### ISSUE THREAD

**Issue by AlexLandau** [gradle/gradle#17434]
We were periodically seeing some of our builds hang with CPU usage, and tracked it down to code that ran in the daemon process with the following stacktrace, on several threads:

```
	at java.util.TreeMap.getEntry(java.base@11.0.5/TreeMap.java:357)
	at java.util.TreeMap.get(java.base@11.0.5/TreeMap.java:277)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$UnfilteredIndex.get(DefaultNamedDomainObjectCollection.java:594)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.findByNameWithoutRules(DefaultNamedDomainObjectCollection.java:311)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.findByName(DefaultNamedDomainObjectCollection.java:288)
	at org.gradle.api.services.internal.DefaultBuildServicesRegistry.registerIfAbsent(DefaultBuildServicesRegistry.java:95)
	at com.palantir.gradle.conjure.GradleExecUtils.exec(GradleExecUtils.java:32)
	at com.palantir.gradle.conjure.CompileIrTask.generate(CompileIrTask.java:135)
	...
```

In fact, we saw this stacktrace on seven different threads, with a corresponding 700% CPU usage. The problem with the plugin code is that [it was trying to register a shared service](https://github.com/palantir/gradle-conjure/blob/3287599de6872b2f9d2dcafddcd77fc81c5cf919/gradle-conjure/src/main/java/com/palantir/gradle/conjure/GradleExecUtils.java#L30-L32) during task execution time.

As-is, the Gradle shared services registry (`project.getGradle().getSharedServices()`) is not thread-safe, and if used from multiple threads it can fail in a way that results in an infinite loop. (This is a possible outcome of concurrent unsynchronized edits to a TreeMap, according to this blog post: https://ivoanjo.me/blog/2018/07/21/writing-to-a-java-treemap-concurrently-can-lead-to-an-infinite-loop-during-reads/)

In other words, these `register` calls should only be made during the Gradle configuration process, not during task execution.

The [current build services documentation](https://docs.gradle.org/current/userguide/build_services.html) (as of 7.0.2) does guide the user through the correct way of setting up a shared service, but it doesn't explicitly warn not to use this during task execution (i.e. for caching purposes), which may be appealing due to being much simpler code. 

Some possible improvements to avoid people running into this in the future:
1. Make the registry thread-safe. (If configuration-in-parallel is in Gradle's future, this might be the best option.)
2. Throw an exception if the user tries to add to the registry during the wrong phase of the build, or otherwise prevent its use. (Might need to wait for a major-version release, but a warning could be added immediately.)
3. Point out in the documentation that this is a problem. (Might be hard to find.)

I can try to create a public repro if it would be helpful.

**Comment by bamboo** [comment]
FTR: Registering a shared build service has been made thread-safe in de745540d69e659dc7e10827076664d5938d2f3a.

**Comment by AlexLandau** [comment]
Closing per #20204.
