### ISSUE TITLE
cannot find symbol class error getting after upgrade gradle to 'com.android.tools.build:gradle:4.0.0' from 'com.android.tools.build:gradle:3.2.1

### ISSUE THREAD

**Issue by vaibhavi-sm** [gradle/gradle#17441]
### Expected Behavior
Should not give any error after upgrade Gradle

### Current Behavior
cannot find symbol class error getting after upgrade gradle to 'com.android.tools.build:gradle:4.0.0' from 'com.android.tools.build:gradle:3.2.1. I am creating runtime classes in gradle:3.2.1 it is working correctly but not for gradle 4.0.0

### Context
That issue is blocked me for upgrade support version 28.0.0 to androidx. It blocked the release.

### Steps to Reproduce 
upgrade gradle to 'com.android.tools.build:gradle:4.0.0' from 'com.android.tools.build:gradle:3.2.1

### Your Environment

Build scan URL:

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days unless you can provide more information.

**Comment by vaibhavi-sm** [comment]
I am using com.squareup:javapoet:1.11.1 library for generating runtime classes and methods. It was correctly working for com.android.tools.build:gradle:3.2.1. but the same code giving error for com.android.tools.build:gradle:4.0.0

**Comment by mlopatkin** [comment]
Could you please provide a self-contained project that reproduces the issue in the archive or as a Github repo?

**Comment by vaibhavi-sm** [comment]
We can't provide code. I can share detailed information. We have created runtime java classes with help of com.squareup:javapoet:1.11.1 library. For creating runtime classes we give a complete path to the class. For that path cannot find symbol class error getting after upgrade gradle to 'com.android.tools.build:gradle:4.0.0' from 'com.android.tools.build:gradle:3.2.1.

**Comment by mlopatkin** [comment]
From what you describe it seems that this is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
