### ISSUE TITLE
Removal of deprecated classes/methods in `reporting` module

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1744]
Classes with `@Deprecated` annotation:

- [x] reporting/src/main/java/org/gradle/api/reporting/ConfigurableReport.java

**Comment by lacasseio** [comment]
PR: https://github.com/gradle/gradle/pull/1764

**Comment by bmuschko** [comment]
The deprecation didn't see go through a full deprecation cycle yet. We won't remove the method for 4.0-rc1.

See comment: https://github.com/gradle/gradle/pull/1764#issuecomment-292996210
