### ISSUE TITLE
Upgrade embedded Kotlin to 1.5.x

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#17465]
What needs to be done:
- update embedded Kotlin version
- configure the kotlin dsl script compilation and plugin to use language level and api 1.4 for backwards compatibility
- release kotlin-dsl plugins with updated version + nightly out + update wrapper
- Remove JDK16 workaround: https://github.com/gradle/gradle/pull/17437

**Comment by big-guy** [comment]
https://github.com/gradle/gradle/issues/17052 This might cause problems

**Comment by eskatos** [comment]
1.5.20 is now available https://github.com/JetBrains/kotlin/releases/tag/v1.5.20

**Comment by big-guy** [comment]
@bamboo could you take a look at this?

**Comment by bamboo** [comment]
> @bamboo could you take a look at this?

👍
