### ISSUE TITLE
Doc - Groovy referenced, but not explained

### ISSUE THREAD

**Issue by GoodMirek** [gradle/gradle#1746]
### Expected Behavior
Explain whether Gradle uses Groovy script for all of its configuration scripts. Are there any limitations to Groovy as used in Gradle? What is relationship of Gradle configuration DSL and Groovy script?

### Current Behavior
On line https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/dsl/dsl.xml#L122 there is written: 

> A build script is also a Groovy script, and so can contain those elements allowed in a Groovy script, such as method definitions and class definitions.

The word "also" seems to refer to some other script, which is also Groovy script, but it is not clear what else is Groovy script.

### Context
I am first time reader of the Gradle DSL doc.

**Comment by bmuschko** [comment]
That should probably say "By default a build script is based on the language Groovy...". There's no other script implied here.

> Are there any limitations to Groovy as used in Gradle?

Almost no limitations.

> What is relationship of Gradle configuration DSL and Groovy script?

The DSL (which is defined in Gradle and is written mostly with Java) is simply evaluated by Groovy at runtime as the build script is evaluated by Groovy. You might have read about it but we are currently also working on a Kotlin-based build scripts meaning you'd have to write your build script in Kotlin and not in Groovy.

**Comment by bmuschko** [comment]
Does this answer your questions? Can we close the issue?

**Comment by bmuschko** [comment]
I am going to close the issue. I think the questions have been answered sufficiently. Please continue the discussion on the Gradle forum as needed.
