### ISSUE TITLE
JUnit 5 @EnabledIfEnvironmentVariable environment variable change is not honored by the daemon on Raspberry Pi

### ISSUE THREAD

**Issue by climategadgets** [gradle/gradle#17461]
JUnit 5 `@EnabledIfEnvironmentVariable` does not behave as expected on Raspberry Pi

### Expected Behavior
`@EnabledIfEnvironmentVariable` current value must be honored

### Current Behavior

`@EnabledIfEnvironmentVariable` current value is only honored if the daemon is explicitly killed (then the current value at the moment of the daemon start is picked up and reused), or `--no-daemon` flag is specified

### Context

This was discovered while working on a hardware driver for a Raspberry Pi peripheral. Driver tests sometimes need to be only enabled in very specific circumstances to avoid damaging hardware that may be connected to peripherals the drivers are being written for.

### Steps to Reproduce 

The whole project is still in private development mode, public release expected in a few weeks. For now:

Execute this test case to reproduce the problem:
```
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;

class GradleBugTest {

    @Test
    @EnabledIfEnvironmentVariable(named = "GRADLE_BUG", matches = "present")
    void gradleBug() {
        System.err.println("GRADLE_BUG=" + System.getenv("GRADLE_BUG"));
    }
}
```
* Execute the test with `./gradlew test`.
* When executed with `--no-daemon` flag, the behavior is exactly as expected, both in case of exported environment variable and variable specified on the command line.
* When executed without `--no-daemon` flag, the behavior of `@EnabledIfEnvironmentVariable` depends only on the value of the environment variable the moment the daemon was started. Current value of the variable is ignored.

### Your Environment

This bug was only observed under the following circumstances:
* Raspbian GNU/Linux 10 (buster) OS
* 3B 1.2 1GB Sony UK Raspberry Pi
* JUnit 5.7.2
* Gradle 6.9 & 7.0.2, the latter is
Build time:   2021-05-14 12:02:31 UTC  
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e  
Kotlin:       1.4.31  
Groovy:       3.0.7  
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020  
JVM:          11.0.11 (Raspbian 11.0.11+9-post-Raspbian-1deb10u1)  
OS:           Linux 5.10.17-v7+ arm  
* `java -version`:  
openjdk version "11.0.11" 2021-04-20  
OpenJDK Runtime Environment (build 11.0.11+9-post-Raspbian-1deb10u1)  
OpenJDK Server VM (build 11.0.11+9-post-Raspbian-1deb10u1, mixed mode)

Elsewhere, the feature behaves as expected.

Build scan URL:
Not available yet - only after public release

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

I wasn't able to reproduce the issue. I don't have Raspbian at hand to reproduce the exact environment. Is the issue not reproducible on desktop Linux distros like Ubuntu on x86_64? Could you please provide a small reproducer project in an archive or as a GitHub repo to be sure that we don't miss anything important?

**Comment by climategadgets** [comment]
Correct, this bug doesn't appear on conventional Linux distributions.
I've published the project here: https://github.com/home-climate-control/automation-hat-driver - the test in question is https://github.com/home-climate-control/automation-hat-driver/blob/main/src/test/java/com/homeclimatecontrol/autohat/pi/PimoroniAutomationHatTest.java, search for `DZ_TEST_HAT`, steps to reproduce in the original submission should be sufficient (tests will fail with no hardware connected, but that would actually make it easier to spot).
If that doesn't allow to reproduce the bug, please let me know - I'll package a rudimentary project with just the test case posted above.

**Comment by climategadgets** [comment]
Update: this bug is confirmed to appear on Raspberry Pi 4 with 4GB RAM (I originally thought that it was related to tight memory, but 4GB should be sufficient, it looks rather a platform or JVM issue). Here's the signature:

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Raspbian 11.0.11+9-post-Raspbian-1deb10u1)
OS:           Linux 5.10.17-v7l+ arm
```

**Comment by mlopatkin** [comment]
Unfortunately, we do not have the bandwidth to support this somewhat exotic environment. I can only suggest continuing to disable the daemon as a workaround. Feel free to comment there or submit a PR if you or someone else with access to the hardware is willing to investigate further and fix the issue.
