### ISSUE TITLE
Gradle 7.0 Lint Error when using local custom view library - Android

### ISSUE THREAD

**Issue by ArcherEmiya05** [gradle/gradle#17475]
### Expected Behavior
Should be able to detect local library

### Current Behavior
I am using a custom view library and add it as one of the project's module. Everything works fine and it is running, however when I tried to run `gradlew lint` the it fails with the message

```
C:\Users\USERNAME\Desktop\Projects\Android\Personal Product\App\app\src\main\res\layout\activity_main.xml:62 Error: Class referenced in the layout file, com.library.custom.view, was not found in the project or the libraries [MissingClass]
        <com.library.custom.view
```

### Context
Good to have lint running on each pipeline 

### Steps to Reproduce 
Gradle: 7.0
Gradle Plugin: 7.1.0-alpha02

### Your Environment
Android Studio Bumblebee | 2021.1.1 Canary 1
Build #AI-203.7717.56.2111.7361063, built on May 14, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0

Build scan URL:

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
