### ISSUE TITLE
org.gradle.testkit.runner throwing compilation issue when upgrading to gradle 6.8.1 from 4.10.1

### ISSUE THREAD

**Issue by sumitblore** [gradle/gradle#17473]
org.gradle.testkit.runner throwing compilation issue when upgrading to gradle 6.8.1 from 4.10.1.

### Expected Behavior
org.gradle.testkit.runner should not throw any compilation issue when upgrade to gradle 6.8.1.

### Current Behavior
org.gradle.testkit.runner  throwing compilation issue when upgrade to gradle 6.8.1.

### Context
Compilation  is failling in my workspace.Not able to build the project.

### Steps to Reproduce 
gradleVersion = '6.8.1'
complie 'org.codehaus.groovy:groovy-all:2.5.12'

testCompile 'junit:junit:4.12'
testCompile 'org.spockframework:spock-core:1.3-groovy-2.5'

Try running test with testKit. Its not able to find any testKit imports.

### Your Environment

Build scan URL:

**Comment by sumitblore** [comment]
Below is error:

unable to resolve class org.gradle.testkit.runner.UnexpectedBuildFailure
 @ line 5, column 1.
   import org.gradle.testkit.runner.UnexpectedBuildFailure
   ^

unable to resolve class org.gradle.testkit.runner.TaskOutcome
 @ line 4, column 1.
   import org.gradle.testkit.runner.TaskOutcome
   ^
unable to resolve class org.gradle.testkit.runner.GradleRunner
 @ line 3, column 1.
   import org.gradle.testkit.runner.GradleRunner

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by mlopatkin** [comment]
I can't really help you much without a reproducer. Upgrading two major versions ahead at once always risks breaking something. A couple of things that may help you:
- Add `testImplementation gradleTestKit()` to the `dependencies` blocks of the projects that use testkit
- Check upgrade guides and adjust your build files accordingly:
  - [From 4 to 5](https://docs.gradle.org/current/userguide/upgrading_version_4.html)
  - [From 5 to 6](https://docs.gradle.org/current/userguide/upgrading_version_5.html)

**Comment by sumitblore** [comment]
Add testImplementation gradleTestKit() to the dependencies blocks of the projects that use testkit - This solution worked.All the compilation issues are resolved after adding this.
