### ISSUE TITLE
Stopped daemons never actually go away

### ISSUE THREAD

**Issue by aram535** [gradle/gradle#1747]
### Expected Behavior
After you stop a daemon after some time they should go away.  They never seem to.

### Current Behavior
If you --stop a daemon or somehow the daemon crashes, it never seems to clear out of the --status screen.

### Steps to Reproduce (for bugs)
On each iteration of gradlew execution you see:
```
"Starting a Gradle Daemon, 6 stopped Daemons could not be reused, use --status for details"

This is not how I got into this mess, but the easiest way of "replicating" the issue in 3.4.1 is: 
Open two windows ... output is from a live system so it shows more me "testing" this replication.  Normally you just see 1 or 2 that never go away.
S1) $ ./gradlew -t build 
S2) $ ./gradlew --stop 
S1) $ ./gradlew -t build 
S2) $ ./gradlew --status
   PID STATUS   INFO
138540 BUSY     3.4.1
 10608 STOPPED  (stop command received)
192432 STOPPED  (stop command received)
137392 STOPPED  (stop command received)
106476 STOPPED  (by user or operating system)
107976 STOPPED  (by user or operating system)
120568 STOPPED  (by user or operating system)
```

Waited for 12 hours and recheck... all still there. 

Obviously a reboot clears all of them out. 

### Your Environment
OS: Windows 10 x64 

Terminal: Bash-GUI (from git-scm) - mintty 2.7.3 (x86_64-pc-msys)

I do use a RAM disk (o:\) to cache my jdk install - it's just an exact copy of jdk1.8.0_102
```
------------------------------------------------------------
Gradle 3.4.1
------------------------------------------------------------

Build time:   2017-03-03 19:45:41 UTC
Revision:     9eb76efdd3d034dc506c719dac2955efb5ff9a93

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Windows 10 10.0 amd64

$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

$ cat ~/.gradle/gradle.properties
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.daemon.idletimeout=600
org.gradle.daemon.performance.logging=false
//org.gradle.java.home=e:\\Program Files\\Java\\jdk1.8.0_102
org.gradle.java.home=o:\\
// org.gradle.java.home=e:\\Program Files\\Java\\jdk-9
```

**Comment by eriwen** [comment]
Those stopped daemons should be listed for an hour after they're stopped. Are the processes still running (as if the daemon is erroneously marked as STOPPED)?

I notice that you're using `--continuous` build. Do you see the same behavior running outside continuous mode?

**Comment by aram535** [comment]
I actually have no idea how this issue starts since most of the time i'm in coding in the IDEs (eclipse, IntelliJ).  Every once in a while I run the gradlew and I see that it has multiple unusable daemons running.  
In this case, I used (-t --continuous) just to replicate the issue but I do use it on occasion - very useful.

```
$ ./gradlew --status
   PID STATUS   INFO
100020 BUSY     3.4.1
138540 STOPPED  (by user or operating system)
109328 STOPPED  (by user or operating system)

$ kill 109328
bash: kill: (109328) - No such process
```
but 100020 and 138540 are both java processes.

**Comment by eriwen** [comment]
Hmm.. glad that the daemons aren't actually staying, just that `--status` reports them longer than I'd hope at worst. In that case, we'll look into the possible causes non-urgently and follow up with questions. I think perhaps the process that's cleaning up STOPPED daemons may not have run for some reason.

**Comment by aram535** [comment]
Sorry I guess buried the lead story here ... the other problem I'm facing is that when the daemon does run, it doesn't stick around to be re-used. 

Apr 04, 2017 3:57:11 PM$ gw build && gw build
Starting a Gradle Daemon, 3 stopped Daemons could not be reused, use --status for details
[... ]
:build

BUILD SUCCESSFUL

Total time: 1 mins 20.935 secs
Starting a Gradle Daemon, 3 stopped Daemons could not be reused, use --status for details
:generateAPJooqSchemaSourceApr 04, 2017 3:58:33 PM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : E:\src\ap\build\tmp\jooq\config.xml
[... ]
:build

BUILD SUCCESSFUL

Total time: 1 mins 20.114 secs

**Comment by eriwen** [comment]
@aram535 `org.gradle.daemon.idletimeout=600` from above is quite short. That will kill unused Daemons after 10 minutes (less if your machine encounters memory strain). 

I would recommend you specify a higher value. I believe IntelliJ IDEA did some improvements here to their own daemon reuse in 2017.1 or so. 

You can take a look in the logs under `~/.gradle/daemon/[version]/` and they'll tell you why a daemon was terminated.

**Comment by eriwen** [comment]
@aram535 Please let me know if my suggestions helped so I can close this issue or if there's some specific thing to fix.

**Comment by aram535** [comment]
@eriwen didn't help in getting rid of the other daemons, but I ended up deleting my ~/.gradle directorie and no issues with daemons since.

**Comment by Sharpkhodakarami** [comment]
It was due to update in my case. I browsed to  `./gradle` directory in my project and noticed that there are two folders inside. 
I simply deleted the older one and the problem solved.
The error is gone.

**Comment by aashishg** [comment]
I had the same problem, `gradle clean` solved it for me.

**Comment by aram535** [comment]
Must have been a coincidence, AFAIK gradle clean has nothing to do with daemons and wouldn't clean anything related to the issue.

**Comment by smaudet** [comment]
You can also delete ~/.gradle/daemon/3.5/registry.bin and ~/.gradle/daemon/3.5/registry.bin.lock (assuming you have no running daemons).

Why there isn't a ./gradlew --clean-daemons or something to do this less haphazardly...I don't know.

**Comment by saisatya525** [comment]
im still having the am issue....

**Comment by ChampIsMe** [comment]
> @eriwen didn't help in getting rid of the other daemons, but I ended up deleting my ~/.gradle directorie and no issues with daemons since.

Please guide me here, android studio/gradle always bringing my computer to a standstill, is there a way I can make sure that after running/building, all other processes are stopped. You may show me the directory to delete please.

**Comment by E3V3A** [comment]
It should be said that `gradle --status` does not always show that the daemons are *paused/stopped*. Instead it shows:
1. why a daemon was stopped
2. which daemons has been running lately (default is last 3 hours)
3. if a daemon is in fact running, it will show as **`IDLE`**.

However! Sometimes the Java process become defunct, and will still be shown as running in process explorer (on Windows etc). Then you need to kill it. For windows you can check processes with SysInternals **`pslist64.exe`**.

```bash
# tree .gradle/daemon/ 

.gradle/daemon/
└── 5.3.1
    ├── daemon-3212.out.log
    ├── daemon-3276.out.log
    ├── daemon-5812.out.log
    ├── daemon-6048.out.log
    ├── daemon-6588.out.log
    ├── registry.bin
    └── registry.bin.lock
```

**Comment by ramanasha** [comment]
hey, guys, I got an error when build app using Cordova please help me


Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/home/ramana_sharma/Android/Sdk/tools (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '/home/ramana_sharma/Desktop/hello/platforms/android/CordovaLib/cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':app'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
/home/ramana_sharma/Desktop/hello/platforms/android/gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Script '/home/ramana_sharma/Desktop/hello/platforms/android/CordovaLib/cordova.gradle' line: 68

* What went wrong:
A problem occurred evaluating project ':app'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by MoeMamdouh** [comment]
Because gradle clean or stop didn't working with me, i stopped the java process Activitey Monitor
this is work for me

**Comment by pjammula** [comment]
I ran into similar issue today. Following didn't work:
1. gradle clean
2. delete  ~/.gradle/daemon/5.3/registry.bin & ~/.gradle/daemon/5.3/registry.bin.lock

What fixed the issue?
**Delete ~/.Gradle folder**

**Comment by filipstoklasa** [comment]
Quitting java process in Activity monitor on Mac worked fro me.

**Comment by alfdev** [comment]
Hi all,

the only way to fix this on osx has been to delete ./gradle/daemon folder

**Comment by lylest** [comment]
what I tried so far
1. deleting .gradle folder in c:/users/.gradle
2. also tried to delete registry bin and registry lock file in C:\Users\MACOWIGO\.gradle\daemon\6.7 but it still didn't worked
3. I uninstalled and installed jdk but still did not wrok

**Comment by devjaw** [comment]
I got this from the log : 
`[DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false`

it works after turn off the hotspot !!!!!!

**Comment by Muhammad-Hamad0343** [comment]
> Hi all,
> 
> the only way to fix this on osx has been to delete ./gradle/daemon folder

Not Working.....

**Comment by atemiz** [comment]
Deleting `~/.gradle/daemon` folder (ubuntu) solved the issue for me.

**Comment by nmateo** [comment]
Seems like it should not be closed, running Linux 6.1 and i have to kill daemon after use every time, highly annoying.

**Comment by guichazan** [comment]
In Android Studio, if you start a debugging session and you kill the debug pressing the red rectangle, the Gradle process remains executing. The only way to get rid of them is with this Windows cmd command:

taskkill /f /im java.exe

I have a bat file that calls that and i do this from time to time because otherwise my memory gets exhausted.

**Comment by FastJack24** [comment]
Hi!
Still reproduces on Gradle 8.13,
Steps:
1) Triggrer daemon start by using build/clean/dependency/... etc. command
2) Stop daemon any way you want (e.g. with --stop or by turning off the computer)
3) 'gradle --status' shows stopped daemons for no reason after significant amount of time
