### ISSUE TITLE
Lacking definition of "project" in docs

### ISSUE THREAD

**Issue by alexsapps** [gradle/gradle#17489]
Gradle docs talk everywhere about projects, but what is a project?

If it's a `Project` as defined by the API, then there is conflicting information in the docs:

"There is a one-to-one relationship between a `Project` and a build.gradle file."
https://docs.gradle.org/current/dsl/org.gradle.api.Project.html

"Note that the root project does not have a Gradle build file, only a settings file that defines the subprojects to include."
https://docs.gradle.org/current/userguide/multi_project_builds.html

**Comment by davidburstrom** [comment]
I agree that it's a little unclear.

In the first example, it is clarified a little later in the same section that "Finally, evaluate each Project by executing its build.gradle file, *if present*" (emphasis by me). Maybe it should say "[...] and an optional build.gradle file [...]" instead.

In the second example, it should read as "Note that the *example* root project [...]", or maybe changed into "The root project does not contain a `build.gradle` file as no root project specific configuration is needed"?

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
