### ISSUE TITLE
Docs - Scoop link is broken on main Installation page

### ISSUE THREAD

**Issue by prestontim** [gradle/gradle#1748]
On the [install guide page](https://gradle.org/install), the link to **Scoop** leads to a 404.

As a side-note, didn't this reference something called [**Chocolatey**](chocolatey.org) yesterday morning?

**Comment by ysb33r** [comment]
I am not quite sure what the state is of Chocolatey as the available Gradle distributions are not being kept up to date - that is what it has been removed. 

The link to Scoop has been fixed and the update will roll out soon. IN the mean time you can look at http://scoop.sh. Thanks for reporting.

**Comment by chaficnajjar** [comment]
This issue was closed automatically due to merging a pull request that was referencing this issue. The link is still broken. Re-opening.

**Comment by chaficnajjar** [comment]
The link to Scoop has been fixed, thanks @ysb33r!
