### ISSUE TITLE
Java-Gradle-Project compiles only once, then throws “cannot find class” error

### ISSUE THREAD

**Issue by Janinus** [gradle/gradle#17481]
Hey there,

I already asked this question on "StackOverflow", but it looks like no one has an idea, where/what my problem is.
And I already thought, the problem solved itself, because I once created a project and everything works fine. 
But every new project has these issues. 

I recently wanted to learn more about Gradle. So I created a new Gradle Project (Im using IntelliJ IDEA 2021.1.2), which imports Java as an external Library. After that, I created a simple class called "Main" in the "java"-src-folder, which simply prints out "Hello World!", when the included main method is called. I didn't change anything in the build.gradle-file.

And here's the issue: When I run the main method for the first time, everything works completely fine, as it should. But when I try to run the main method again, without changing anything, I get two errors:

1.) Could not find or load main class Main 

2.) Process command "/path to jdk/bin/java.exe" finished with non-zero exit value 1

But every time I change something in the build.gradle-file, I can run the main method again, one more time, but then throws those two errors again, when I want to run it again, without changing anything.

I already tried to fix these errors, by adding 'mainClassName' into the build.gradle-file, editing the run-configurations, reinstalled IntelliJ and Gradle, tried with other JDKs, but nothing worked.

I would be really thankful if somebody could help me out with these issues because, with them, I am not able to use Gradle (in IntelliJ) for my Java Projects.

![Output_after_second_compiling_LI](https://user-images.githubusercontent.com/81978067/122438738-518ce200-cf9b-11eb-99f6-2f0def47b853.jpg)
![Output_after_first_compiling_LI](https://user-images.githubusercontent.com/81978067/122438743-52257880-cf9b-11eb-9ef9-821e82af1968.jpg)

**Comment by alexnavarrogarcia** [comment]
I'm not sure if this is the same issue I had a couple of days ago, however, I hope it can give you an idea:
I'm working on Flutter and realized that if Git is activated, it creates a folder called .gradle. With this, Flutter is unable to identify which one is the right folder, so it crashes. You have two alternatives: either disable Git for the project or delete the .gradle folder each time you get this error.

**Comment by Janinus** [comment]
@alexnavarrogarcia Thank you very much. And yes, you are right. Everytime I delete the .gradle folder it works again.  Well, I always need to remove the folder before I can compile, but still this is a huge progress.

**Comment by mlopatkin** [comment]
That isn't the intended behavior. @Janinus, could you please provide a broken project in an archive so we can investigate what is going on?

**Comment by mlopatkin** [comment]
Closed because of the lack of response from the reporter.
