### ISSUE TITLE
Strange behavior with snapshot dependencies

### ISSUE THREAD

**Issue by alexander-shustanov** [gradle/gradle#17499]
I faced with a very strange problem. I have some SNAPSHOT dependencies in my project that are published to my Nexus repository. The artifacts are cleaned from time to time, and sporadically, Gradle fails a build with the message:
```gradle
Could not find jmix-ui-starter-1.0.0-SNAPSHOT.jar (io.jmix.ui:jmix-ui-starter:1.0.0-SNAPSHOT:20210514.104239-315).
```
It references old SNAPSHOT, but the repository already has a new one. Launching Gradle with --refresh-dependencies does not help. I found, that Gradle caches the full artifact version in ~/.gradle/caches/modules-2/metadata-2.97/descriptors/io.jmix.ui/jmix-ui-starter/1.0.0-SNAPSHOT, and deleting the directory solves the issue. Also, waiting for 86400 seconds (default cache update period) solves the problem too. By the way, should Gradle download the latest  SNAPSHOT version, if the previous became unavailable?

**Comment by ljacomet** [comment]
I understand that this might be surprising. You are effectively "removing" a changing dependency that the Gradle considers valid for period of time. Unique `-SNAPSHOTS` are cached based on their unique name and not under the `-SNAPSHOT` one.

You have two options: keep snapshots in your repository for longer than the default grace period of Gradle (24 hours) or decrease [the time for which a changing version is cached](https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:controlling_dependency_caching_programmatically) in your build.

Given the current priorities of the team, any behaviour change on the Gradle side is unlikely at this point in time.

The one concern I have with the report is that `--refresh-dependencies` does not resolve the problem. Could you provide a reproducer, using a local repository for example, with instructions that show this problem?

**Comment by StevenPG** [comment]
I can add that this is an issue for my team. 

We use `resolutionStrategy.cacheChangingModulesFor 0, 'seconds'` as per the documentation and snapshots are never updated. The issue doesn't seem to happen locally, which --refresh-dependencies forcing a new dependency update as it is supposed to work.

Deleting the directory does not always work for our developers on OSX machines, though it seems to for Windows users.

**Comment by ljacomet** [comment]
Closing as without a reproducer this will not be investigated.
