### ISSUE TITLE
Support specifying to("group:artifact") in versionCatalogs

### ISSUE THREAD

**Issue by SerVB** [gradle/gradle#17492]
### Expected Behavior

Would be cool to merge parameters like this:

```kt
val selenide = version("selenide", "5.13.1")
alias("selenide").to("com.codeborne:selenide").versionRef(selenide)
```

### Current Behavior

Currently, only `to` with two parameters is functional.

```kt
val selenide = version("selenide", "5.13.1")
alias("selenide").to("com.codeborne", "selenide").versionRef(selenide)
```

`to` with one parameter returns `Unit`, so can't be used with version ref.

### Context

Specifying a single parameter is faster and more compact.

**Comment by mlopatkin** [comment]
This is unlikely to happen. Currently, the API is designed to prevent potential misuses so you either have to specify all components at once (`void to(String)` throws if something is missing) or you can use builder-like notation. And it is just three extra characters anyway.
