### ISSUE TITLE
Confusing behavior of "vendor" selection with Java toolchains

### ISSUE THREAD

**Issue by melix** [gradle/gradle#17509]
### Expected Behavior

Consider the following Java toolchain spec:

```
    languageVersion = JavaLanguageVersion.of(8)
    vendor = JvmVendorSpec.matching("GraalVM Community")
```

I would expect Gradle to pick up a JVM which is compatible with Java 8 and a vendor matching "GraalVM community".

### Current Behavior

This would return an `AdoptOpenJDK` VM, which is not the intended behavior, as this VM would not provide the expected GraalVM support.

### Context

I am working on the GraalVM official Gradle plugin and would like to leverage toolchain support, but unfortunatly this doesn't quite work in my case.

### Steps to Reproduce 

Use the following script:

```

plugins {
   id 'java-base'
}

def toolchain = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(8)
    vendor = JvmVendorSpec.matching("GraalVM")
}

println toolchain.get().metadata.vendor
```

Running `./gradlew help` when running on JDK 11 (Adopt) will trigger the download of an AdoptOpenJDK JDK 8 release.

See https://scans.gradle.com/s/ovmabuxf3d6zs/console-log#L0

There are two problems:

1. it will return an AdoptOpenJDK release instead of a GraalVM one
2. it downloads a JDK 8 release although the current one is perfectly capable of providing Java 8 support

Now, change your JAVA_HOME to point to GraalVM and update the build script to use language level 11:

```
$ sdk use java 21.1.0.r16-grl
$ ./gradlew help
```

Now we have https://scans.gradle.com/s/j5d2gzebiioui/console-log#L0:

```
GraalVM Community
```

let's move now to an OpenJDK 11 release:

```
$ sdk use java 11.0.11.hs-adpt
$ ./gradlew help
```

https://scans.gradle.com/s/knv4zlaw5q4sq/console-log#L0

again it selects `GraalVM Community`, which is extremely confusing. Basically the only way to get the correct JDK is to have installed a version which actually uses the **same** version of the language version. We can confirm by adding this:

```
println toolchain.get().metadata.installationPath.asFile
```

which then shows:

```
/home/cchampeau/.sdkman/candidates/java/21.0.0.2.r11-grl
```

Note the `r11`...

**Comment by mlopatkin** [comment]
I was able to reproduce the issue with a bit of setup.

>update the build script to use language level 11

I suspect that you have GraalVM 11 and 16 installed with sdkman but not GraalVM 8, is it right?

>it will return an AdoptOpenJDK release instead of a GraalVM one

This definitely looks like a couple of bugs in the toolchain logic here. We won't start a download if the vendor is specified and there is no auto-provisioned AdoptOpenJDK for the requested language version. However if the auto-provisioned JDK is available then we'll unpack it (every time) and use it then.

>the only way to get the correct JDK is to have installed a version which actually uses the same version of the language version

This is tracked in #17444. Currently, toolchain selection doesn't consider backward compatibility of the newer java version. We're discussing introducing something like `JavaLanguageVersion.atLeast(8)` to cover this use case.

**Comment by melix** [comment]
> I suspect that you have GraalVM 11 and 16 installed with sdkman but not GraalVM 8, is it right?

That's correct.
