### ISSUE TITLE
Overriding Task#getGroup and Task#getDescription throws validation error in Gradle 7.x

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle#17500]
I ran into this validation error which is sort of awkward IMO:
https://scans.gradle.com/s/245cxh52pctww/tests/:test/nu.studer.gradle.credentials.Cre[…]ution?anchor=e30&focused-exception-line=0-34&top-execution=1

I’m overriding `getDescription` from DefaultTask and Gradle 7 complains that it is not annotated properly (it is not all). But, the annotation is present on the parent class:
```
    @Internal
    public String getDescription() {
        return this.description;
    }
```

**Comment by lptr** [comment]
Is there a use case for doing this? I think we should make these methods final at some point.

**Comment by etiennestuder** [comment]
I don't see a use case. +1 to not allowing it, if there is no use case for it.
