### ISSUE TITLE
Gradle uses incorrect default value for org.gradle.jvm.version on resolution

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#17513]
Gradle uses the value of `release` as the current default value for `org.gradle.jvm.version` when resolving the compile classpath. However, this is incorrect. The default value should instead be the version of the compiler itself, because with e.g. a JDK 16 `javac`, Java 16 classes can be used in the classpath of a `--release 8` compilation. This can be demonstrated using [this project](https://github.com/octylFractal/gradle-uses-wrong-default-target-jvm-version).

### Expected Behavior
The linked project should build when `./gradlew build` is executed.

### Current Behavior
```java
Could not determine the dependencies of task ':java8-lib:compileJava'.
> Could not resolve all task dependencies for configuration ':java8-lib:compileClasspath'.
   > Could not resolve project :java16-lib.
     Required by:
         project :java8-lib
      > No matching variant of project :java16-lib was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability gradle-uses-wrong-default-target-jvm-version:java16-lib:unspecified declares an API of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
          - Variant 'runtimeElements' capability gradle-uses-wrong-default-target-jvm-version:java16-lib:unspecified declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 16 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
```

### Context
I am trying to maintain Java 8 compatibility with a library that needs to optionally use some Java 16 libraries. Gradle (by default) does not let me use the Java 16 libraries, but as demonstrated in the linked project this can be worked around by explicitly declaring the JVM version as 16.

### Steps to Reproduce 
Build [this project](https://github.com/octylFractal/gradle-uses-wrong-default-target-jvm-version).

### Your Environment
Build scan URL: https://scans.gradle.com/s/5nx3dpuhikeja

**Comment by mlopatkin** [comment]
Could you please elaborate a bit on why you want such a dependency? In my understanding, the goal of using the "--release" is to ensure that the resulting classes are usable on previous JVM. If you add a dependency on classes compiled for newer JVM then you may accidentally try to load some of them at runtime and get the `UnsupportedClassVersionError`.

**Comment by octylFractal** [comment]
As I mentioned, these are optional dependencies - at runtime we may be running without these and want to retain the ability to run on e. g. Java 8.

**Comment by mlopatkin** [comment]
Allowing unrestricted usage of higher API levels when `--release` is specified seems to be dangerous in a general case. Given the fact that the workaround exists for those who need it, it is unlikely that something will be changed there.

You may need to change the attribute for some other configurations (runtime and test ones) though.
