### ISSUE TITLE
Test runtime classpath does not contain plugin metadata file 'plugin-under-test-metadata.properties' when upgrading to gradle 6.8.1 from 4.10.1.

### ISSUE THREAD

**Issue by sumitblore** [gradle/gradle#17516]
Test runtime classpath does not contain plugin metadata file 'plugin-under-test-metadata.properties' when upgrading to gradle 6.8.1 from 4.10.1.

### Expected Behavior

Integration test case should run without any issue when running test case with gradleTestKit().

### Current Behavior

Getting below issue when running integration  test case with  gradleTestKit().
Test runtime classpath does not contain plugin metadata file 'plugin-under-test-metadata.properties' when upgrading to gradle 6.8.1 from 4.10.1.

### Steps to Reproduce 

gradleVersion = '6.8.1'
complie 'org.codehaus.groovy:groovy-all:2.5.12'

testCompile 'junit:junit:4.12'
testCompile 'org.spockframework:spock-core:1.3-groovy-2.5'

Run any test case gradleTestKit().

### Your Environment

Build scan URL:

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by sumitblore** [comment]
Please try running any project with below configuration.

gradleVersion = '6.8.1'
complie 'org.codehaus.groovy:groovy-all:2.5.12'

testCompile 'junit:junit:4.12'
testCompile 'org.spockframework:spock-core:1.3-groovy-2.5'

Try running test with testKit. 
When I am trying to run any intergration Test ,Always receive below error:
Test runtime classpath does not contain plugin metadata file 'plugin-under-test-metadata.properties

I don't have any reproducer project for this & can't share my code.

**Comment by mlopatkin** [comment]
There isn't enough information for me to proceed. Could you please try to create a simple reproducer? We don't need much code - build files with dependencies and plugins applied, skeletal plugin, and dummy integration test should be enough if the issue can be reproduced there. You can check [Stackoverflow's guidelines](https://stackoverflow.com/help/minimal-reproducible-example) too. Gradle is a very flexible tool so without deeper knowledge of your situation we are not able to help.

**Comment by mlopatkin** [comment]
This issue lacks necessary information to be actionable.

**Comment by sumitblore** [comment]
I fixed this issue by adding 'plugin-under-test-metadata.properties' file in my src/resources folder as I noticed classpath is reading from src folder.
