### ISSUE TITLE
[Configuration cache] Task not up-to-date for SantaTracker

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#17548]
Using Gradle `7.1` and [SantaTracker](https://github.com/gradle/santa-tracker-android/commit/3930e2bccc74a2cb134754f29069bddc15235792), and running:
```
rm -rf .gradle/configuration-cache
gw  -DagpVersion=7.0.0-beta04 -DkotlinVersion=1.5.10 clean --configuration-cache  --no-build-cache  -i --configuration-cache-problems=warn
gw  -DagpVersion=7.0.0-beta04 -DkotlinVersion=1.5.10  :common:bundleLibCompileToJarDebug --configuration-cache  --no-build-cache  -i --configuration-cache-problems=warn
gw  -DagpVersion=7.0.0-beta04 -DkotlinVersion=1.5.10  :common:bundleLibCompileToJarDebug --configuration-cache  --no-build-cache  -i --configuration-cache-problems=warn
```

shows that `:common:bundleLibCompileToJarDebug` is not up-to-date and `santa-tracker-android/common/build/intermediates/compile_library_classes_jar/debug/classes.jar` is missing Kotlinc classes (they are present after the 1st run).

This looks related to https://github.com/gradle/gradle/issues/17542, but fixing it does not fix this issue. Root cause is that in
```
fun FileCollection.getDirectories(projectDirectory: Directory): Provider<List<Directory>> =
    elements.map {
        it.filter { file -> file.asFile.isDirectory }
            .map {
                fileSystemLocation -> projectDirectory.dir(fileSystemLocation.asFile.absolutePath)
        }
    }
```
filter runs to soon, during configuration cache storing.

**Comment by mlopatkin** [comment]
@gradle/configuration-cache please take a look at this issue

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/17585
