### ISSUE TITLE
[Documentation] Document behaviour of --scan parameter changing build classpath when debugging build cache

### ISSUE THREAD

**Issue by nhoughto** [gradle/gradle#17556]
When debugging build-cache misses, reading this useful page - https://docs.gradle.org/current/userguide/build_cache_debugging.html#diagnosing_cache_miss

One of the suggestions is to try `--scan` which gives some great visibility into how things are being processed, it does however change the gradle build classpath (adds the gradle enterprise plugin) which changes the build cache key for all the tasks in the build!

I was going through the various tests, reproducible/relocatable etc, and was very confused tried to figure out why my build cache key was changing when otherwise I was doing everything correctly, when I realised it was because of the `--scan` parameter the I was sometimes including to get greater visibility of things. Maybe a warning on that page that using `--scan` will effect your cache keys so readers are aware of the effect 👍

**Comment by mlopatkin** [comment]
@gradle/execution could you please take a look at this?

**Comment by nhoughto** [comment]
It is workaround-able by manually adding gradle enterprise plugin to your settings.gradle
```
plugins {
    id "com.gradle.enterprise" version "3.6"
}
```

that way whether you --scan or not, the classpath always contains the plugin, so makes it more stable 👍

**Comment by wolfs** [comment]
@nhoughto Your workaround is exactly what you should do - always apply the Gradle Enterprise plugin. `--scan` is then only used to turn scan publishing on or off.

Regarding the documentation: The page about debugging build cache misses talks about using Gradle Enterprise. You'll need the input file comparison from there to actually debug build cache misses. The free version scans.gradle.com does not provide this feature. So the assumption there is that you already are producing build scans for your builds by always applying the Gradle Enterprise plugin and the page doesn't even talk about using the `--scans` flag.

So I wonder where the documentation that `--scans` changes the plugin classpath should go, and if it makes sense to mention this at all.

I'll close the issue. Please re-open/comment if you disagree.
