### ISSUE TITLE
Builds takes 21s extra in the "End of build" stage

### ISSUE THREAD

**Issue by louis993546** [gradle/gradle#17554]
### Expected Behavior
It is clear that what the "End of build" step is doing

### Current Behavior
The "End of build" step often takes 21s, and I have no idea what it is doing

Link to screen recording: [here](https://www.youtube.com/watch?v=eVEHuls8KYM)
It looks like it's not related to any specific tasks or flags, but when you change flag, it's more likely to trigger the extra end of build time

Log of each run:

1. `clean detekt`, **takes extra time**
1. `clean detekt`
1. `clean detekt`
1. `clean detekt --profile`
1. `clean detekt --profile --full-stacktrace`
1. `clean detekt --scan`, **takes extra time**
1. `clean detekt --scan`
1. `clean detekt --no-daemon`
1. `clean detekt --no-daemon --no-build-cache`, **takes extra time**
1. `clean detekt --no-daemon --no-build-cache`
1. `clean detekt --no-daemon --no-build-cache`

### Context

First reported to [Android Studio bug tracker](https://issuetracker.google.com/issues/190140491), as it was affecting my development workflow.

### Steps to Reproduce 

1. Clone  [The repo](https://github.com/louis993546/Compose-Composer)
2. Run any tasks (detekt/assemble/test/etc. It seems they all have the same behaviour)

### Your Environment
* Windows 10 Pro (Build 21390.co_release.210521-1658)
* `java version "1.8.0_281"`

Build scan URL: 

* Short tasks: https://scans.gradle.com/s/dwtgv3cg5w5qo/performance/build#build-time-end-of-build
* Long tasks: https://scans.gradle.com/s/6atcegbw23zgo/performance/build#build-time-end-of-build

**Comment by donat** [comment]
I tried to reproduce the issue but the attached build never reproduces behavior. It might be that there's an issue in your environment. Can you check if the slow "end of build" stage still occurs if you run your build with an empty gradle home?

    gradle clean build --gradle-user-home local-gradle-user-home

In the meanwhile, I fire up a windows VM and check the issue there.

**Comment by donat** [comment]
I don't see an extra time at the end of the build on Windows either. I'm going to close this as not reproducible. If you find more clues that can further the investigation then I'll reopen the issue.
