### ISSUE TITLE
Gradle erroneously detects missing task dependency between missing output file and input filter containing **

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#17561]
Copied from #16980 and originally reported by @m-koops:

And here I have another small sample demonstrating the false positive.  It turns out the warning is triggered as soon as both tasks foo and bar get a filetree as input, although each task has a different filetree. Without the inputs, no warning.

```
val foo by tasks.registering() {
    description = "Foo"

    inputs.files(fileTree(projectDir) {
        include("**/*.foo")
    })
    val reportPath = "${buildDir}/foo.txt"
    outputs.file(reportPath)

    doLast {
        println("foo")
        file(reportPath).writeText("foo")
    }
}

val bar by tasks.registering() {
    description = "Bar"

    inputs.files(fileTree(projectDir) {
        include("**/*.bar")
    })
    val reportPath = "${buildDir}/bar.txt"
    outputs.file(reportPath)

    doLast {
        println("bar")
        file(reportPath).writeText("bar")
    }
}

val fooBar by tasks.registering {
    dependsOn(foo, bar)
}
```

---
cc: @gradle/execution

**Comment by wolfs** [comment]
The problem in your example is the **/ kind of include. This include matches all directories. Currently, we consider non-existing files as it would possibly be a directory, so the filter matches. When you run the build a second time in your example, you will see that the warning went away since the output file exists now.

We should probably change the check to assume that the location is a file when it doesn't exist, so there are fewer matches.

Using something like fileTree(projectDir) { include '**/...' } is discouraged, since it has quite a bad performance impact: Gradle needs to scan the whole project directory and filter all the files every time it tries to run the task. So that means especially scanning all the files in build as well. Normally, that is not a good idea. If you can restrict your search to some subdirectories or at least exclude the build directory you are much better of and your build will be faster.

**Comment by matejdro** [comment]
@wolfs What would be the project-isolation way to properly do this?

We have a task that collects lint report files from every subproject. But there is no good way to add a folder of the every subproject, because, to achieve project isolation, we cannot iterate through subprojects in any way. Only solution is to use filsystem to collect every `**/build/report` folder.
