### ISSUE TITLE
Provisioned toolchain X could not be probed.

### ISSUE THREAD

**Issue by christyjacob4** [gradle/gradle#17565]
### Expected Behavior
The project should compile

### Current Behavior
> * What went wrong:
> Could not determine the dependencies of task ':javadoc'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Provisioned toolchain '/root/.gradle/jdks/jdk8u292-b10' could not be probed.

### Context
I use IntelliJ when building my library on my local machine where I use Adopt Openjdk 8 and everything builds fine.
Here's the part where I configure my `java-library` gradle plugin.
```groovy
java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
        vendor = JvmVendorSpec.ADOPTOPENJDK
    }
}
```
However, when I run tests on my CI where I use an `openjdk:8-jdk-alpine` docker image to run the tests, the library fails with the aforementioned error. 

This is the docker command I'm using.
`docker run --rm -v $(pwd):/app -w /app/tests/sdks/kotlin openjdk:8-jdk-alpine sh -c "./gradlew :test -q` 

### Steps to Reproduce 
1. Clone https://github.com/appwrite/sdk-for-kotlin/tree/dev and import it into IntelliJ
2. Try to build the project. ( Succeeds ) 
3. Run the following command from your project root
` docker run --rm -v $(pwd):/app -w /app openjdk:8-jdk-alpine sh -c "./gradlew :assemble -q"` 

### Your Environment
Local: 
Ubuntu 20.04
Gradle 6.8
Adopt OpenJDK 8

CI: 
Alpine Linux
Gradle 6.8
OpenJDK 8

I'm unable to produce a build scan since the project fails to build

**Comment by ljacomet** [comment]
You are forcing Gradle to use the AdoptOpenJDK vendor. But from what we know, this does not work on Alpine.

What happens if you remove that condition `vendor = JvmVendorSpec.ADOPTOPENJDK`?

**Comment by christyjacob4** [comment]
When I remove `vendor = JvmVendorSpec.ADOPTOPENJDK` and build it runs fine both locally and on the CI :+1:

**Comment by christyjacob4** [comment]
Im unsure if this is a bug. But I just wanted to bring it to your notice. 

Ideally should it matter which JDK vendor I used for building my project and which JDK vendor is used to run it as long as the versions are the same? 

I would expect this to work irrespective of the JDK vendor. Let me know if I'm missing something .

**Comment by ljacomet** [comment]
The `vendor` part of the toolchain specification is designed for builds that have a strong tie with the vendor implementation of a given Java version.
So when you specify it in Gradle, it is interpreted as a strong constraint.

Most builds should not care about the vendor indeed and thus should not specify it.

Given your explanation, I would say that in your case you have no strong vendor tie and so should omit that configuration.

This means there is nothing to do in Gradle at this stage, so closing.

**Comment by christyjacob4** [comment]
Alright @ljacomet  Thanks . That makes sense :+1:
