### ISSUE TITLE
Findbugs should not always write progress to console

### ISSUE THREAD

**Issue by aburmeis** [gradle/gradle#1756]
Currently the FindBugs plugin always activates `-progress` regardless of any console setting.

### Expected Behavior
I would expect an option to turn off that progress on console because it is polluting the logs. Either turn if off if console is set to plain or offer a config option.

### Current Behavior
The findbugs progress is polluting my docker console.

### Context
Reading logs gets much harder.

### Steps to Reproduce (for bugs)
call `gradle check` and redirect output to a file.

### Your Environment
jenkins build running on an image based on openjdk:8u111-jdk

**Comment by eriwen** [comment]
@aburmeis What version of Gradle?

**Comment by blindpirate** [comment]
I encounter the same question...it occurs both on `3.4.1` and `3.5` for me...I will try to figure out this.

**Comment by bmuschko** [comment]
I am going to close this issue as duplicate of https://github.com/gradle/gradle/issues/1307.
