### ISSUE TITLE
Improve documentation for Test filters to indicate/explain the difference between "package*" and "package.*"

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#17579]
In the [Testing in Java & JVM projects - Test filtering](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering) section exists the 2 samples (they are not together )

```
# all classes at specific package (recursively)
gradle test --tests 'all.in.specific.package*'

....

gradle test --continuous --tests "com.mypackage.foo.*"
```

I tested both, the latter without `--continuous` - and both practically do the same, it runs the test classes from the package declared and all its sub-packages.

So I think is fair indicate for the developer in the official documentation _what is the difference_ between `package*` and `package.*` (it according from `foo.*`) and furthermore when is mandatory (and why) use an approach over the other

Thanks for your understanding

**Comment by ljacomet** [comment]
This is actually documented as part of [this section](https://docs.gradle.org/current/userguide/java_testing.html#full_qualified_name_pattern):

> Note that the wildcard '*' has no special understanding of the '.' package separator. It’s purely text based. So --tests *.SomeTestClass will match any package, regardless of its 'depth'.
