### ISSUE TITLE
Project substitution causing issues with missing task dependency detection

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#17577]
Using the project [missing_dep.zip](https://github.com/gradle/gradle/files/6741380/missing_dep.zip) and running:
```
cd testThatFails/project
./gradlew aDAT --warning-mode=fail
```

produces
```
> Task :app:mergeDebugAndroidTestResources
Execution optimizations have been disabled for task ':app:mergeDebugAndroidTestResources' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/gavra/AndroidStudioProjects/testThatFails/project/lib/build/intermediates/packaged_res/debug'. Reason: Task ':app:mergeDebugAndroidTestResources' uses this output of task ':lib:packageDebugResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a problem with the following location: '/Users/gavra/AndroidStudioProjects/testThatFails/project/lib/build/intermediates/packaged_res/debug'. Reason: Task ':app:mergeDebugAndroidTestResources' uses this output of task ':lib:packageDebugResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
All files: [/Users/gavra/AndroidStudioProjects/testThatFails/project/lib/build/intermediates/packaged_res/debug, /Users/gavra/AndroidStudioProjects/testThatFails/project/app/src/androidTest/res, /Users/gavra/AndroidStudioProjects/testThatFails/project/app/src/androidTestDebug/res]
```
(`All files:` logging are all file inputs for the `app:mergeDebugAndroidTestResources` task, added in `doFirst` in `app/build.gradle`)

Directory `testThatFails/project/lib/build/intermediates/packaged_res/debug` is produced by `:lib:packageDebugRes` task (run it to verify), and running `./gradlew :app:mergeDebugAndroidTestResources --dry-run` does not run that task i.e the dependency seems to be really missing.

If `app/build.gradle` is modified to contain `androidTestImplementation project(":lib")` instead of `"com.test:lib:1.0"`, the issue is fixed.

**Comment by wolfs** [comment]
The warning seems to be correct:
When running only `:app:mergeDebugAndroidTestResources` (https://ge.gradle.org/s/hvdb5hzfsna2k/timeline), then the task `:app:mergeDebugAndroidTestResources` does not run. So there is no task dependency. The task dependency only seems to be there when actually adding `project(":lib")` to `androidTestImplementation`. Interestingly, the dependency on `project(":lib")` is part of `debugAndroidTestRuntimeClasspath` even without adding anything to `androidTestImplementation`.

This seems to be a genuine missing task dependency. Though I don't understand why the task dependency is lost.

**Comment by gavra0** [comment]
Adam's comment from https://github.com/gradle/gradle/issues/15889#issuecomment-790130277 summarise the root cause. The issue is that AGP adds `project(:lib)` to `debugAndroidTestRuntimeClasspath` in `beforeResolve`, which is after dependencies have been computed.

We can close this issue, as this requires changes in AGP.
