### ISSUE TITLE
Let Gradle test a specific package but ignoring/without the sub-package(s)

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#17580]
Considering that exists the following packages and classes in `src/test/java`

    com.something.one
        AlphaTest
        BetaTest
        DeltaTest 
    com.something.one.more
        OmicronTest
        ZuluTest

With any of the two following commands:

```
    ./gradlew  :module-name:test --tests "com.something.one*"
    ./gradlew  :module-name:test --tests "com.something.one.*" // observe it ends now with .*
```

The `com.something.one` and `com.something.one.more` packages were executed. Until here it is expected.

But, what if is need it to test _only_ the `com.something.one` package and **not** the `com.something.one.more` sub-package?
So:

I have already read:

* [Testing in Java & JVM projects - Test filtering](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering)

But _'seems'_ is not possible. The option to change the sub-package name to other  different than the parent package is not always an option. Of course - if exists the option, should be indicated in the documentation - therefore, currently it is missing
   
If not exists, please consider to add that feature, perhaps with a new parameter such as `--no-subpackages`, therefore

```
    ./gradlew  :module-name:test --tests "com.something.one*"  --no-subpackages
    ./gradlew  :module-name:test --tests "com.something.one.*" --no-subpackages
```

Thanks for your understanding

**Comment by ljacomet** [comment]
As indicated in the documentation, the feature is purely test name based and does a simple text matching.
If you have a need for isolating tests from a parent package from ones from a child package, you will need to figure out something in the test naming that allows you to select only one group and not the other.

Given the current priorities of the team, the requested change is unlikely to be done.
