### ISSUE TITLE
Support ANSI characters in gradle output

### ISSUE THREAD

**Issue by ColtonIdle** [gradle/gradle#17581]
https://github.com/JakeWharton/mosaic/discussions/36

I'm trying Mosaic which is Jake Wharton's tool for building command line apps with Jetpack Compose.

Unfortunately running Mosaic via gradle doesn't work which requires you to build a binary instead of showing correctly in the terminal.

https://github.com/JakeWharton/mosaic

According to Jake:
"Both IntelliJ's terminal and Gradle's output will remove ANSI control characters. They are separate, but perform the same action which prevents Mosaic (or anything using ANSI characters) from working."

More discussion on it here: https://github.com/JakeWharton/mosaic/discussions/36#discussioncomment-923506

**Comment by ljacomet** [comment]
What happens if you run the build with `--console=plain`?

Gradle itself uses ANSI control characters for its rich console. I am not surprised that ones coming from user code are stripped to not interfere with the Gradle ones.

**Comment by ColtonIdle** [comment]
This is the output when I try to run in terminal on my mac

```
coldtonidle@mac16 untitled2 % ./gradlew run --console=plain
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :run
The count is: 0
The count is: 1
The count is: 2
The count is: 3
The count is: 4
The count is: 5

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
3 actionable tasks: 2 executed, 1 up-to-date
```
