### ISSUE TITLE
Provide resources how to integrate with python

### ISSUE THREAD

**Issue by brainbytes42** [gradle/gradle#17603]
Given the gradle.org main page saying this...

> Build Anything
> Write in Java, C++, **Python** or your language of choice. 
[added bold formatting]

### Expected Behavior
... I expect to find at least a little hint how to get started with python in gradle. Is there an official plugin (which could be expected, when mentioning on the main page) or at least a go-to community-plugin? How to get started with a default and seimple hello-world-configuration?

### Current Behavior
- Neither using google, nor the webpage's search, there seems to any helpful resource about python and gradle.
- From google (and a short forum post from 2017), I found linkedin's PyGradle, which seems to somewhat useful, but also outdated - the github page says it's aimed at gradle 5.0
- There are a bunch of community-plugins searchin for "python", but at least for me it's not clear, in which order they are presented (obviously not latest date...) or how useful / reliable / community-tested / ... they are.

### Context
Coming from Java + gradle as an extensive user, I now consider integrating python with gradle, as some projects seem to be tending into the python-world for me, but being related to som other Java/gradle-ones...
I wouldn't have strted that python/gradle-journey, if it hadn't been mentioned on the webpage - but having it mentioned there and the finding nothing about ist, is quite frustrating...

**Comment by ljacomet** [comment]
I can understand the frustration and we should at least link to the Gradle plugin portal and make it clear that this is a community driven integration.

When [searching on the plugin portal](https://plugins.gradle.org/search?term=python), you can find a number of plugins. Some have recent releases and are documented. I would recommend to start there.

Will leave this open so that the claim in the documentation can be clarified.

**Comment by ljacomet** [comment]
@Natemooney Is this something you could look into?

It is about the "Build anything" section on https://gradle.org/.

**Comment by ljacomet** [comment]
Sorry, pinged the wrong person.

@nathan-contino please see above ☝️
