### ISSUE TITLE
Parallel test execution might not honor maxWorkers

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1760]
Currently `MaxNParallelTestClassProcessor` is handling the parallel test execution. We should use the capabilities of `BuildOperationProcessor` instead.

The concrete issue is that tests may execute without holding a worker lease. `WorkerLeaseHolderTestClassProcessor`, which wraps `MaxNParallelTestClassProcessor`, is adding a lease only to scheduling but not executing the tests.

So we do not respect `maxWorkers` with respect to test execution.

A solution should probably replace `WorkerLeaseHolderTestClassProcessor` and `MaxNParallelTestClassProcessor` with something new that uses BuildOperationProcessor between the place where all test classes are collected (`DefaultTestClassScanner`) and the chain of test class processors.
https://github.com/gradle/gradle/blob/f24146cc5f956a1b03a515bbee4225e6f861b6ab/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScanner.java#L63-L70

The `BuildOperationProcessor` should then keep care of running parallelisation. We could use `BuildOperationQueue.waitForCompletion()` to implement `maxParallelForks`.

**Comment by eskatos** [comment]
@jjohannes here is a proposal PR with fix that don't necessitate to rewrite the whole parallel test execution: https://github.com/gradle/gradle/pull/1802

**Comment by eskatos** [comment]
The PR https://github.com/gradle/gradle/pull/1802 has been merged. I'll reword the title of this issue to better represent what was done before closing.
