### ISSUE TITLE
Unable to set some system properties

### ISSUE THREAD

**Issue by hsrinara** [gradle/gradle#17616]
Gradle always prepends the D before the system property and assumes they are always key value pairs. 

https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/process/internal/JvmOptions.java#L107
https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/process/internal/JvmOptions.java#L109

Some system properties aren't key value pairs, and some system properties don't start with -D but -XX.

**Comment by blindpirate** [comment]
`-XX` is VM arguments, they are not system properties.
