### ISSUE TITLE
DependencyHandler#add kapt not work.

### ISSUE THREAD

**Issue by ParadiseHell** [gradle/gradle#17614]
### Expected Behavior

I want to wrote a Plugin to auto load a dependency which will be process by `kapt`.

### Current Behavior

The dependency is loaded but not in `kaptClasspath`, so my dependency doesn't work.

### Context

The code is follwing:
```kotlin
project.afterEvaluate {
    project.dependencies.add("kapt", "group:artifactId:version")
}
```

After I use `dependencies` command, I got this as following:

```txt
kaptClasspath_kaptDebugKotlin
No dependencies

...

kaptDebug
\--- group:artifactId:version
```

But if I add kapt in build.gradle it works, And the dependencies result is as following:
```txt
kaptClasspath_kaptDebugKotlin
\--- group:artifactId:version

...

kaptDebug
\--- group:artifactId:version
```

Because the dependency is not included in `kaptClasspath`, so I think it dosen't work.

### Your Environment

Gradle version: 6.7.1
Java version: 1.8

So how to fix it?

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with the Kotlin Gradle Plugin which is developed by JetBrains and cannot be addressed in the core of the Gradle Build Tool.

Please open such Kotlin-related issues on the Kotlin Issue Tracker at https://youtrack.jetbrains.com/issues?q=project:%20Kotlin%20

---

It might be that the KAPT configuration setup also uses an after evaluate to create the exact dependencies. And thus your `afterEvaluate` might end up happening too late.
