### ISSUE TITLE
Incremental compilation does not kick in when unused classes are added/removed

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle#1761]
Have an `app` project that has Java classes that consume Java classes in a `library` project. If you add a new class to the `library` project (or remove an unused class), the `app` classes will be recompiled despite the new class (or removed class) not being used at all by the classes in the `app` project.

### Expected Behavior
The `app` sources should not be recompiled, i.e. incremental compilation should kick in.

### Current Behavior
The `app` sources are recompiled, i.e. incremental compilation does not kick in.

### Context
Bug in incremental compilation. Discussed with and shown to @melix who agreed that this looks like a bug.

### Steps to Reproduce (for bugs)
See attached sample project. Add a new (unused) class to the library project and rebuild the project --> app classes are recompiled. Remove the unused class --> app classes are recompiled.

[compile-avoidance.zip](https://github.com/gradle/gradle/files/896111/compile-avoidance.zip)

### Your Environment
Not environment specific.
 * Build scan URL of build that should not have recompiled anything in the `app` project when unused class is added: https://scans.gradle.com/s/durvenctauqvi/log#L2
 * Build scan URL of build that should not have recompiled anything in the `app` project when unused class is removed: https://scans.gradle.com/s/ycfaaqf5fnnga/log#L2

**Comment by etiennestuder** [comment]
The same problem exists if you add (and possibly remove) a new public method to a class and that method is not used by anyone in any project.

**Comment by etiennestuder** [comment]
@pioterj I reported this issue because it happened to me within the first 10 minutes of trying out incremental compilation. Thus, it seems to me that it would deserve to be fixed soon since others will most likely stumble across it quickly, too. //cc @melix @oehme

**Comment by melix** [comment]
Did you see the problem again using M2 or master, @etiennestuder? It has been fixed already.
