### ISSUE TITLE
Make Gradle's memory management work appropriately in memory constrained docker containers

### ISSUE THREAD

**Issue by Thrillpool** [gradle/gradle#17610]
Gradle experiences some problems inside memory constrained docker containers, it reads from /proc/meminfo when attempting to determine the free memory which will be the hosts memory inside a container.

### Expected Behavior
When using Gradle inside a docker container, if the memory of the container is limited and the files /sys/fs/cgroup/memory/memory.usage_in_bytes and /sys/fs/cgroup/memory/memory.limit_in_bytes exist. These files should be used to determine the total memory and the available memory.

### Current Behavior
At present /proc/meminfo is used and incorrect numbers are read, leading to the container potentially using more memory than it has been allocated and being killed by the host. This occurs with any settings, e.g. no-daemon and no parallelism.

### Context
Our Jenkins pipeline uses docker container agents with limited memory. We were repeatedly having the agents be killed by Jenkins. Builds were also very very slow.

We are now using a patched version of the Gradle process-services jar where we overwrote the DefaultOsMemoryInfo class file with my implementation which reads from the cgroup files. We are no longer having agents killed by Jenkins and the performance is significantly better. Until this issue with Gradle is resolved, we will be patching the process-services jar for each version of Gradle that we use.

I tried some alternatives, but they were not very successful. 

One alternative was to add a task to gradle which got the MemoryManager.class and called requestFreeMemory every so often with a huge amount of memory, which effectively enforced that all inactive worker daemons be killed off. This sort of worked, but not always, and had a significant performance hit.

Another alternative was to split up our multi module build into several steps by first determining an appropriate order to build the modules in. This resolved the memory issue, but was extremely slow.

Another alternative I did not pursue was to increase the memory the agents were limited to, it was already a lot and the team responsible for managing Jenkins would not have gone for it.

I know for a fact this is an issue that impacts many people, but probably few have delved into the code and identified the root cause, most instead have just upped the memory of the agents in Jenkins.

I propose, adding some code to DefaultOsMemoryInfo which in the case of operatingSystem.isLinux(), determines if the cgroup files are available and appropriate to use (e.g. there is this 9223372036854771712 value which is indicative of the container not being memory limited), then a new implementation of OsMemoryInfo called CGroupMemoryInfo is used, which reads from these cgroup files.

I have the relevant code already written, but actually it is all quite trivial, essentially just read from the two cgroup files, parse them as longs, determine the available memory as one minus the other and create a new OsMemoryStatus.

**Comment by ljacomet** [comment]
Given that you have the changeset available, would you mind sharing it? 
It can be in the form a PR initially.
This could help the team get this change integrated faster.

**Comment by Thrillpool** [comment]
Yep that is fine

https://github.com/gradle/gradle/pull/17628

I am happy to work on this myself, but equally will be happy to support anyone who picks it up.

**Comment by nsutcliffe** [comment]
Hi; we're having the same problem, would be great if the merge request could go in. Happy to help if needed!

**Comment by Thrillpool** [comment]
What is the state of this? Mr MR ended up getting closed (which I'm partly to blame for, sorry), this issue is still existing and still not really announced as a limitation by Gradle. I've seen several Gradle issues which look like they're effectively this problem, e.g. https://github.com/gradle/gradle/issues/20821

At present I have been applying this patch on top of latest gradle versions as we upgrade and has been good.

I am happy to reopen an MR, and I can probably put a bit more time into it this time as I can probably make it a ticket ay my work, as I would like to stop patching this.

**Comment by bantonsson** [comment]
Hi, I'm also interested in the state of this. We are currently running a patched version of `gradle` that uses cgroups to avoid the daemon disappearing due to OOM. Is there anything that I can do to help moving this issue forward?
