### ISSUE TITLE
"gradle wrapper" no longer works in empty directory since 7.0

### ISSUE THREAD

**Issue by tkgregory** [gradle/gradle#17625]
### Expected Behavior

In previous versions of Gradle if I run `gradle wrapper` in an empty directory it will create the wrapper script.

```
$ gradle wrapper
> Task :wrapper
BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

$ ls -l
total 12
drwxr-xr-x 1 Tom 197121    0 Jul  6 14:10 gradle/
-rwxr-xr-x 1 Tom 197121 5766 Jul  6 14:10 gradlew*
-rw-r--r-- 1 Tom 197121 2763 Jul  6 14:10 gradlew.bat
```

### Current Behavior

An error is shown:

```
$ gradle wrapper
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Executing Gradle tasks as part of an undefined build is not supported. Make sure that you are executing Gradle from a folder within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root folder.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

### Context
Works in version `6.9`
Stopped working in version `7.0`

The other way to create the wrapper is using `gradle init`, but you don't always want to generate the full skeleton project.

### Steps to Reproduce 
1. Ensure you have Gradle 7.0+ installed locally
1. Create an empty directory
1. Navigate into that directory
1. Run `gradle wrapper`
1. See the error mentioned above

### Your Environment
No build scan available since this is a pre-build problem.

**Comment by ljacomet** [comment]
The output explains what's wrong:
> Executing Gradle tasks as part of an undefined build is not supported. Make sure that you are executing Gradle from a folder within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root folder.

This is the consequence of a [breaking change](https://docs.gradle.org/current/userguide/upgrading_version_6.html#executing_a_gradle_build_without_a_settings_file_is_now_an_error) introduced in Gradle 7.0.
In short, for a Gradle invocation to be valid, you need a `settings.gradle(.kts)`. `init` remains the exception to that behaviour.
