### ISSUE TITLE
Build fails with a DomainObjectSet parameter in a build service or worker action

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#17632]
An attempt to use `DomainObjectSet` as a parameter to a build service fails the build when attempting to acquire the service with the following exception:

```
Could not create an instance of type Build_gradle$MyBuildService$Parameters.
> class java.util.LinkedHashSet cannot be cast to class org.gradle.api.DomainObjectSet (java.util.LinkedHashSet is in module java.base of loader 'bootstrap'; org.gradle.api.DomainObjectSet is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @7cd62f43)
```
The bug repros in both Gradle 7.1.1 and the latest nightly as of today (7.2-20210704221017+0000). I put up a repro here: https://github.com/cesar1000/invalid-domain-object-set.

**Comment by eskatos** [comment]
Thanks for the report Cesar!

I assume the same happens with Worker API parameters.

Yep, here's a reproducer for the Worker API:

```kotlin
interface MyWorkParams : WorkParameters {
    val mySet: DomainObjectSet<String>
}

abstract class MyWorkAction : WorkAction<MyWorkParams> {
    override fun execute() = Unit
}

abstract class MyTask : DefaultTask() {

    @get:Inject abstract val workerExecutor: WorkerExecutor

    @TaskAction fun action() {
        workerExecutor.noIsolation().submit(MyWorkAction::class) {}
    }
}

tasks.register<MyTask>("myTask")
```

**Comment by cesar1000** [comment]
Thanks, Paul! Also, this is not specific to the configuration cache, since it happens consistently, whether the cache is enabled or not. The implementation class generated by Gradle for the parameters seems to be consistently invalid.

**Comment by eskatos** [comment]
Yes this is unrelated to the configuration cache indeed.
It's more about parameters isolation. I assume this also affects Transforms.
