### ISSUE TITLE
Gradle publish plugin shouldn't trigger realization of all tasks

### ISSUE THREAD

**Issue by melix** [gradle/gradle#17643]
### Expected Behavior

Applying the `com.gradle.plugin-publish` should only configure the minimum amount of work.

### Current Behavior

Applying the plugin triggers the realization of all tasks, killing all laziness and preventing a legit build from running.

### Context

I figured out that the culprit is at:

```
        at com.gradle.publish.PublishTask.useAutomatedPublishing(PublishTask.java:319)
        at com.gradle.publish.PublishPlugin$4.execute(PublishPlugin.java:223)
        at com.gradle.publish.PublishPlugin$4.execute(PublishPlugin.java:219)
```

by adding the following code snippet to my build script:

```
tasks.withType(DefaultTask).configureEach {
    if (it.name == 'wrapper') {
        throw new RuntimeException()
    }
}
```

This affects me because it triggers configuration of unnecessary tasks in a composite, and the build fails because of missing toolchains that it shouldn't need because the tasks should never be realized.

### Steps to Reproduce 

Use the following script:

```
plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'com.gradle.plugin-publish' version '0.15.0'
}

tasks.withType(DefaultTask).configureEach {
   if (it.name == 'wrapper') {
      throw new RuntimeException("oh noes, why did you get configured?!")
   }
}
```

Run `./gradlew help` and see the build fail. Comment out the `maven-publish` plugin, run again and see the build pass.

### Your Environment

The build scan below shows the problem on a real world build

Build scan URL: https://scans.gradle.com/s/nnklofn2aw2gc/performance/configuration?details=code-unit-com.gradle.plugin-publish!:native-gradle-plugin&openScriptsAndPlugins=WyJjb2RlLXVuaXQtY29tLmdyYWRsZS5wbHVnaW4tcHVibGlzaCJd

**Comment by ljacomet** [comment]
This will be fixed in the next version of the `plugin-publish` plugin although the chain of tasks for generating Gradle Module Metadata will still be realised. This will only apply when the plugin is used in combination with the `maven-publish` plugin, although that is now the recommended way.

**Comment by ljacomet** [comment]
[Version 0.16.0](https://plugins.gradle.org/plugin/com.gradle.plugin-publish/0.16.0) of the `plugin-publish` has some improvements in that area.
It will no longer causes eager realization of all tasks but still creates a number eagerly itself.
