### ISSUE TITLE
Using composite build to include plugin into buildSrc

### ISSUE THREAD

**Issue by iNikem** [gradle/gradle#17652]
I have a project which tries to use some plugin in its `buildSrc` script. That plugin is also developed by me and I try to composite build to include local plugin version into main project's `buildSrc`. Is it possible? Sor far all my attempts fail.

[Here is the minimal project](https://github.com/iNikem/buildSrcInclude/tree/main) that demonstrates the problem. Please read its README file.

**Comment by ljacomet** [comment]
`buildSrc` is a special build which is not really part of the build tree.
So if you want to include a build in `buildSrc`, you have to do it by declaring it inside the `settings.gradle(.kts)` of `buildSrc` itself.

**Comment by iNikem** [comment]
@ljacomet I tried that and got:
```
Cannot include build 'projectA' in build 'buildSrc'. This is not supported yet.
```
Is it expected?

**Comment by ljacomet** [comment]
A quick search through the doc did not find anything, but the error is quite specific, so I would say that including a build in `buildSrc` is indeed not supported.

What you could do is replace `buildSrc` by an included build itself and then it would support including another build. We are effectively aiming at removing some of the specifics / limitations of `buildSrc` by having it behave like a composite.
