### ISSUE TITLE
Improve type and method names around ResourceSnapshotterCacheService

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#17653]
Followup on https://github.com/gradle/gradle/pull/17514/files/ada661fa1790be693cbe049177af64cfcdb2f66d#diff-039507c8b86caf912beacb8d3598532166a6bee0fdcb7232fdc725c9ef5bd568.

https://github.com/gradle/gradle/blob/a2ea10896cbdca85a4fb7b0e30d638f57dbe1533/subprojects/normalization-java/src/main/java/org/gradle/api/internal/changedetection/state/ResourceSnapshotterCacheService.java#L28-L34

The difference between the two methods is that the one taking `FileSystemLocationSnapshot` is expected to hash "root" input file entry as a whole, while the one taking a `RegularFileSnapshotContext` hashes some sort of "sub" entry, i.e. a file in a directory hierarchy, or a ZIP entry.

It would be good to find names for these concepts and then call these methods and the `RegularFileSnapshotContext` accordingly. It might even make sense to remove `RegularFileSnapshotContext` and just pass the `relativePathSegmentSupplier` directly to the method here.

---
cc: @gradle/execution

**Comment by wolfs** [comment]
We probably won't do this anytime soon.
