### ISSUE TITLE
Unable to use configOptions in gradle plugin

### ISSUE THREAD

**Issue by aakshaydev** [gradle/gradle#17661]
rev.jsonschema2pojo-gradle-plugin=1.1.1
rev.openapi-generator-gradle-plugin=5.1.1

distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip

rev.swagger-parser=2.0.1
rev.swagger-ui=3.14.2
rev.swagger-annotations=1.5.14

build.gradle:
openApiGenerate {
	configOptions = [
			dateLibrary: "java8",
			java8: true,
			hideGenerationTimestamp: true
	]
when I pass boolean in configOptions, it says:

Execution failed for task ':modules:types:api:openApiGenerate'.
> Failed to calculate the value of task ':modules:types:api:openApiGenerate' property 'configOptions'.
   > Failed to query the value of extension 'openApiGenerate' property 'configOptions'.
      > Cannot get the value of a property of type java.util.Map with value type java.lang.String as the source contains a value of type java.lang.Boolean.
Caused by: java.lang.IllegalArgumentException: Cannot get the value of a property of type java.util.Map with value type java.lang.String as the source contains a value of type java.lang.Boolean.

When I pass String as java8: "true", it says:

java.lang.NullPointerException
Execution failed for task ':modules:types:api:openApiGenerate'.
Caused by: org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 1
Errors: 
        -null
Warnings: 
        -null

**Comment by ljacomet** [comment]
This is most likely an issue in [the openapi generator plugin](https://plugins.gradle.org/plugin/org.openapi.generator) and either is indicated in the documentation or you might need to file an issue against that plugin.

There is nothing that can be done in Gradle core for this.
