### ISSUE TITLE
gradle task don't support  reading private variable or  invoking  the private method in a lambda

### ISSUE THREAD

**Issue by xuewan-seven** [gradle/gradle#17669]
invoke in lambda . 
![image](https://user-images.githubusercontent.com/53112178/125060619-218ab780-e0df-11eb-8f92-8583d5c6de30.png)
![image](https://user-images.githubusercontent.com/53112178/125060673-2f403d00-e0df-11eb-8cd0-5a3c20b39592.png)

reading private variable .
![image](https://user-images.githubusercontent.com/53112178/125060813-5139bf80-e0df-11eb-8573-97f6a6c85408.png)
![image](https://user-images.githubusercontent.com/53112178/125060890-61519f00-e0df-11eb-9709-408742e4aca9.png)

Then I tried it in groovy helloworld program and it was ok

**Comment by melix** [comment]
I suppose your task is written in Groovy. In this case you should, as the type hint implies, prefix your code with `it.` since the decoration that you usually have in build scripts, which allow getting rid of the `it.` is not available for tasks written this way.

**Comment by blindpirate** [comment]
Thanks @melix 

Closing because this is not a Gradle issue.
