### ISSUE TITLE
Jacoco plugin configuration is too picky

### ISSUE THREAD

**Issue by thejohnfreeman** [gradle/gradle#1766]
### Expected Behavior

This should work:

```groovy
dependencies {
    jacocoAgent files("path/to/jacocoagent.jar")
}
```

Like other configurations, we pass a list of relevant jars.

### Current Behavior

The plugin complains (excerpted from an [old report from another user](https://discuss.gradle.org/t/illegalstateexception-when-using-jacocagent-as-a-local-jar-dependency/17047)):

```
Expected ZIP 'path/to/jacocoagent.jar' to contain exactly one file, however, it contains no files.
```

Looking at [the code](https://github.com/gradle/gradle/blob/c92fc0f5c9007605d20eaaea7cff81b5dd2ba56a/subprojects/jacoco/src/main/java/org/gradle/internal/jacoco/JacocoAgentJar.java#L66), we see the plugin is expecting a zip file that contains a file named `jacocoagent.jar`, but we tried to pass the jar itself. This is how Jacoco is distributed, but once unpacked, there is no way to configure Gradle's Jacoco plugin.

### Context

Much like that other user, my employer disallows us from using the Maven Central Repository for dependencies, and instead we use local dependencies, even for build and test tools.

### Proposal

Change the plugin to accept a single jar in the configuration. Users who still have the jar packed in a zip file can use the `zipTree -> filter` pattern from the current plugin implementation as part of their configuration.

**Comment by bmuschko** [comment]
We should probably have a more graceful check. Would you be interest in providing a fix for it?

**Comment by thejohnfreeman** [comment]
Sure thing, I'll give it a shot.

**Comment by YusiZhang** [comment]
are there any updates on this issue?

**Comment by mngenius** [comment]
if you want to run the sonarqube task by specifying the instrumentation in the test section:

test {
        jvmArgs "-javaagent:${configurations.jacoco.asPath}=destfile=${buildDir}/jacoco.exec,includes=org.your.project.*"
    }

 you will to remove the block:
apply plugin: jacoco

**Comment by bmuskalla** [comment]
@thejohnfreeman Thanks for writing up this request. At this point, we don't have the capacity to look further into this as there is a reasonable workaround. If you still feel this should be fixed in Gradle itself, please feel free to reopen this issue with a PR. Let me know if you need any help with that.
