### ISSUE TITLE
Add GradleRunner#run method in TestKit

### ISSUE THREAD

**Issue by melix** [gradle/gradle#17671]
### Expected Behavior

It would be nice to have a `run` method in addition to `build` and `buildAndFail` which doesn't verify the actual build result. The rationale for this is that when you have a test which expects the build to pass but fails, or a build which is expected to fail but passes, then it's not possible to add a breakpoint in the test _after_ the `build` or `buildAndFail` method to check the test state. Instead, one has to change the method call to `buildAndFail` (or `build`, respectively), in order to get past.

It would be more convenient, for writing better test fixtures, to let the user control what to expect, by possibly storing the `BuildResult` in a fixture, _then_ checking the actual result of execution.

### Current Behavior

Currently when writing tests with TestKit, you have to choose between two methods to execute a build:

- `build()`, which expects the build to pass
- `buildAndFail()` which expectes the build to fail

**Comment by melix** [comment]
Don't close it, I really think this is needed, having to change your code to debug a failing test is extremely annoying.

**Comment by jvandort** [comment]
Implemented by #23086
