### ISSUE TITLE
Tilde prefix not considered absolute path

### ISSUE THREAD

**Issue by nicolashaan** [gradle/gradle#17670]
This relates to https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#file-java.lang.Object-
It seems that paths starting with tilde(~) are not considered absolute path but relative to the project.

### Steps to Reproduce 
1. Create a simple project with gradle init
2. Patch app/build.gradle.kts with the following (adapt second path to your local config):
```
application {
    // Define the main class for the application.
    mainClass.set("gradle.path.AppKt")
    println("Tilde absolute path: ${file("~/.gitconfig").absolutePath}")
    println("Absolute path: ${file("/Users/nico/.gitconfig").absolutePath}")
}
```

### Expected Behavior
```
Tilde absolute path: /Users/nico/.gitconfig
Absolute path: /Users/nico/.gitconfig
```

### Current Behavior
```
Tilde absolute path: /Users/nico/dev/gradle-path/app/~/.gitconfig
Absolute path: /Users/nico/.gitconfig
```
### Context

Is it an intended behavior or a bug?

### Your Environment
macOS 11, gradle 7.0
Build scan URL:

**Comment by melix** [comment]
The tilde `~` symbol is a bash-specific expansion. You shouldn't expect any Java program to interpret it, since its meaning is dynamically defined by the bash environment.

**Comment by ljacomet** [comment]
This is the expected behavior.
If you want to access the user home, you should use `System.getProperty("user.home")` instead, which has semantics defined by the JVM.
