### ISSUE TITLE
eclipse-wtp EJB projects are not compatible with eclipse "jst.ejb" facet

### ISSUE THREAD

**Issue by HvB** [gradle/gradle#17681]
When you want to create an EJB project with gradle and eclipse-wtp, the project, by default, is just defined as _a JEE utility project_.
In order to let eclipse recognize it as an EJB project, you can activate the "jst.ejb" facet as in the configuration below:
```
apply plugin: 'java'
apply plugin: 'eclipse-wtp'
repositories {
    mavenCentral()
}
dependencies {
    compileOnly  group: 'jakarta.platform', name: 'jakarta.jakartaee-api', version: '8.0.0'
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
eclipse.wtp.facet { 
    facet name: 'jst.ejb', version: '3.2'
}
```
However since eclipse-wtp define such a project as an eclipse JEE utility project, the projects has then both facets "jst.utility" and "jst.ejb" installed. 
The these two facet are incompatible for eclipse (as describe in [eclipse wtp proposal](https://www.eclipse.org/webtools/development/proposals/WtpProjectFacets.html))

### Expected Behavior
When you add the "jst.ejb" facet, eclipse-wtp should remove "jst.utility" facet, installed by default

### Current Behavior
The generated eclipse project has both "jst.utility" and "jst.ejb" facets installed.
In the eclipse project properties,  the project facet tab states that "EJB module and Utility module cannot both be selected"

You can manually deselect the utility module checkbox. However, since the eclipse configuration is defined using the eclipse-wtp plugin, the problem will reappear.

### Context
I'm trying to convert JEE eclipse projects as gradle projets.
Developers are using Eclipse IDE and gradle is used in CI/CD.
The CI/CD works great, however the developer aren't happy because the eclipse facets are not well defined.

### Steps to Reproduce 
In eclipse clone and import as a gradle projet the example project, https://github.com/HvB/ExampleEjb 
Open the project properties and go to the facet tab.

### Your Environment
Eclipse 2021.06 (but we have the same problem with previous versions)
gradle 7.1 (we have also the same problem with previous versions)

**Comment by HvB** [comment]
The only workaround I found is to remove the "jst.utility" facet in _whenMerge_ action. 

`eclipse.wtp.facet.file.whenMerged { it.facets = it.facets.findAll { it.name != 'jst.utility' }}`

So it's somehow similar to #945

Also, to correctly mimic the behavior of the Eclipse IDE wizard, the "jst.ejb" facet should also be defined as _fixed_.

**Comment by ljacomet** [comment]
This is unlikely to get attention from the team at this point in time.
You offered a PR for #945, if you have the capacity and interest, please consider doing the same for this issue.

**Comment by HvB** [comment]
There is still a pending pull request for this bug awaiting review...
