### ISSUE TITLE
Android Gradle Plugin - Kotlin DSL - Can't set buildFeatures databinding

### ISSUE THREAD

**Issue by AnastasiaRainMaker** [gradle/gradle#17689]
I am migrating to Kotlin dsl and I can't set buildFeatures property databinding any more. It is missing from AppExtension class. It is happening in dynamic feature module.

Steps to reproduce:

1. Convert to kotlin dsl for gradle file.
2. Try to enable databinding in android extension in a dynamic feature module.

I am on AGP 4.2.1. Android Studio Android Studio Arctic Fox | 2020.3.1 Beta 4

Here is code sample:

I have tried

```
android {
   buildFeatures {
     dataBinding = true
   }
}
```

and

`buildFeatures.dataBinding = true
`
Error is:  

`Unresolved reference: dataBinding
`
some screenshots attached.
<img width="361" alt="Screen Shot 2021-07-12 at 3 47 51 PM" src="https://user-images.githubusercontent.com/33650124/125358244-47f26200-e32e-11eb-8a51-0a502573f7e2.png">
<img width="736" alt="Screen Shot 2021-07-12 at 3 48 02 PM" src="https://user-images.githubusercontent.com/33650124/125358247-488af880-e32e-11eb-8a4b-d43253db1ec7.png">
<img width="299" alt="Screen Shot 2021-07-12 at 3 48 14 PM" src="https://user-images.githubusercontent.com/33650124/125358254-49bc2580-e32e-11eb-8a8d-a3dc2544680c.png">

**Comment by mlopatkin** [comment]
@AnastasiaRainMaker could you please provide a small reproducer project in an archive or as a github repo?

**Comment by AnastasiaRainMaker** [comment]
Google replied on their issue tracker https://issuetracker.google.com/issues/193452960
