### ISSUE TITLE
Add support to ModularitySpec for fixed module mode

### ISSUE THREAD

**Issue by kemuri-9** [gradle/gradle#17697]
Currently `ModularitySpec` only has two modes of operation which affects how `JavaModuleDetector` is utilized:
"Not a module" and "Scan for a module-info file, and **only if it exists** -> execute as a module"

There is no way to specify "Do not scan, execute as a module"

As to why this is necessary is for one style of testing modules in module mode:
Such tests are written without a module-info because they are expected to be **patched into the module** itself.
By patching into the module, full unrestricted access is granted to the module internals for rather in-depth white-box testing without requiring --add-opens arguments for every package in the module, or some other mechanism of module cracking.

Since `ModularitySpec` has been this way since 6.4, the current functionality feels a bit "settled" or "standardized" so I'm not sure
of what way would be to update `ModularitySpec`, but for the most part there are 2 clear options.

1) Add a second boolean property, e.g. `getIsModular()`:
* By default it is not specified and falls back to existing `getInferModulePath()`
* But if it is specified, this takes priority and skips scanning for module-info altogether.
** `TRUE` -> is a module, setup module-path and similar settings for modular execution.
** `FALSE` -> is not a module, setup classpath alone.
Long term this feels a bit clumsy in having two boolean properties to control the behavior, but leads to less API interference compared to the below option.

2) Add a new Enumerated property, that has options :
** `IS_MODULAR` -> is a module, setup module-path and similar settings for modular execution.
** `INFER` or `SCAN` -> scan for module-info, setup modular execution if found. This would be the default setting
** `NOT_MODULAR` -> is not a module, setup classpath mode execution.
This would effectively replace and deprecate the existing `getInferModulePath()` option, where `getInferModulePath()` could be removed in a later major release.

**Comment by mlopatkin** [comment]
It isn't exactly clear what are you trying to achieve. We have covered a similar issue in [the documentation](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_testing_modular_patching). If this isn't suitable for you than can you please share an example project that shows what are you trying to do (assuming that the feature you're asking for exists)?

**Comment by kemuri-9** [comment]
yes I read that documentation. The issue i have is with the requirement on having a module-info.java in the test source.
the requirement gradle has on the test module-info.java is arbitrary and induces additional maintenance work.
I am requesting for a way to gradle to execute "module mode" without an associated module-info.java.

Does this make sense?

**Comment by kemuri-9** [comment]
Hmm, my request may not make sense as Gradle is following a convention that tests will have their own module-info and `main` is patched into `test` in these scenarios.
But for the scenarios I've been working with it's actually the reverse case: `test` is patched into `main`.
This is likely a byproduct of different tools utilizing different conventions, as there is not quite any decent standard for these scenarios.
For example eclipse not supporting multiple module-info's in one project: the entire project fails at the existence of a second module-info. But eclipse also does a lot of JPMS modifications for test execution as well.
So, is there any interest in Gradle supporting other testing conventions, or is the mindset "fixed" on it's current style?

**Comment by mlopatkin** [comment]
Thanks for the update, now I understand your use case better. The current style isn't set in stone but this area is unlikely to get attention in the short term.

**Comment by kemuri-9** [comment]
OK, thanks for checking at least.
If a direction is made on this and help is needed on implementing it, then I may be able to help out. I have some time here and there, but not that much overall.
