### ISSUE TITLE
npm version specification syntax for java dependencies

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#17703]
So, I'm not sure if the js version for gradle has this, it might. I'd like to use the  styles defined here https://docs.npmjs.com/about-semantic-versioning#using-semantic-versioning-to-specify-update-types-your-package-can-accept

specifically

```
1.x
^1.0.3
```

I can see having *just* the number be problematic. So my understanding is that these would be semver compliant, and should not potentially pick up versions you don't want, such as a `-beta`, `RC` or `milestone`.

the equivalent of the above specification I think is

```
[1.0.3,2)
```

which I personally find hard to remember over `1.x`, `1.+` having the problem that it, in a backwards-compatible way, will pick up beta's, rc's and the like, and potentially some other unintended behaviour. Yes, I have written rules to avoid these versions, but it's kind of annoying to have to include them in every project. There was [a bug](https://github.com/gradle/gradle/issues/8126#issue-394778716) for that. I'm hoping this could work as a solution for everyone, that doesn't require adding this code to every project ever

```kt
configurations.configureEach {
  resolutionStrategy {
    componentSelection {
      all {
        if (!this@configureEach.name.matches(Regex("^spotbugs.*"))) {
          val nonRelease = Regex("^[\\d.]+-(M|ea|beta).*$")
          if (candidate.version.matches(nonRelease)) reject("no pre-release")
        }
      }
    }
  }
}
```

**Comment by ljacomet** [comment]
There is no plan on supporting this syntax in Gradle.

**Comment by xenoterracide** [comment]
:'(
