### ISSUE TITLE
resolutionStrategy.dependencySubstitution substitute module with project error

### ISSUE THREAD

**Issue by Ryan-Shz** [gradle/gradle#17720]
I tried to replace the remote aar with the local project, so i added the following code to the root project's build.gradle:
```
subprojects {
    configurations.all {
        resolutionStrategy.dependencySubstitution {
             substitute module("com.xxx") using project(':xxx')
        }
    }
}
```
but when compiling I got the following error:
```
Execution failed for task ':xxx:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':xxx:debugCompileClasspath'.
> Could not find xxx.aar (project :xxx).
```

I tried many ways but still can't solve it. any help would be very much appreciated!

**Comment by mlopatkin** [comment]
The issue #15533 is probably related to this one if not a duplicate.

**Comment by Ryan-Shz** [comment]
@mlopatkin so is this a known issue? Is there any idea to solve it?
