### ISSUE TITLE
Outdated Gradle Version problem

### ISSUE THREAD

**Issue by MasterGaeX** [gradle/gradle#17727]
### Context

I created a new Fabric project for MC 1.17.1 and when I opened it in VSCode, it showed two errors (the other problem got resolved), and one of them was that I was using an outdated version of Gradle (3.6) and that Gradle 7 or higher was required. I installed Gradle 7.1.1 and I verified it in cmd.exe and in the VSCode's console. But still the problem remains. I restarted the PC, recreated the project 3-4 times and still there's the problem.

### Your Environment

I'm using Windows 10 and VSCode

**Comment by beatbrot** [comment]
Would be interesting how you created the gradle project.

Maybe you are (accidently) using [the gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) that downloads & runs a way older version of gradle just for your project.

**Comment by MasterGaeX** [comment]
I used [this script](https://github.com/ExtraCrafTX/GeneratorFabricMod) to create the skeleton of the project

**Comment by mlopatkin** [comment]
@MasterGaeX could you please attach the project you've created to this issue in an archive?

**Comment by MasterGaeX** [comment]
[TEST.zip](https://github.com/gradle/gradle/files/6828991/TEST.zip)
This is the project

**Comment by mlopatkin** [comment]
>an outdated version of Gradle (3.6) 

Are you sure that the error mentions 3.6 and not 6.3? The latter is the one that is set in the gradle wrapper.

You can upgrade the Gradle version by running the following command in the root folder of the project
```
gradlew.bat wrapper --gradle-version=7.1.1
```

It seems that the GeneratorFabricMod script you're using is the one what generates the build with gradle 6.3 so I suggest to report this issue to the maintainer of the script. Actually, I think that https://github.com/ExtraCrafTX/GeneratorFabricMod/issues/21 covers this.

**Comment by MasterGaeX** [comment]
> > an outdated version of Gradle (3.6)
> 
> Are you sure that the error mentions 3.6 and not 6.3? The latter is the one that is set in the gradle wrapper.
> 
> You can upgrade the Gradle version by running the following command in the root folder of the project
> 
> ```
> gradlew.bat wrapper --gradle-version=7.1.1
> ```
> 
> It seems that the GeneratorFabricMod script you're using is the one what generates the build with gradle 6.3 so I suggest to report this issue to the maintainer of the script. Actually, I think that [ExtraCrafTX/GeneratorFabricMod#21](https://github.com/ExtraCrafTX/GeneratorFabricMod/issues/21) covers this.

Yeah, it was 6.3, I didn't notice when I was writing the post. Anyway, it still doesn't work.
![Immagine 2021-07-16 104756](https://user-images.githubusercontent.com/81831281/125920404-192cf4ef-f321-4f34-b0f2-ff9830dc785d.png)
This is what happens if I run it in cmd.exe in the root folder.
And it doesn't recognize the command in the VSCode console

**Comment by MasterGaeX** [comment]
I looked at [this page](https://docs.gradle.org/current/userguide/gradle_wrapper.html) and now it works
`gradle wrapper --gradle-version 7.1.1 --distribution-type all`
