### ISSUE TITLE
use version catalog accessors with exclude

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#17723]
I want to be able to simply provide an exclude with a version catalog accessor

this is what I'm asking for

```kt
  testImplementation(libs.neo4j.test) {
    exclude(libs.slf4j.nop)
  }
```

this works as an existing workaround

```kt
  testImplementation(libs.neo4j.test) {
    val module =  libs.slf4j.nop.get().module
    exclude(group = module.group, module = module.name)
  }
```

**Comment by melix** [comment]
Makes sense :+1: (but think twice before adding excludes ;))

**Comment by xenoterracide** [comment]
of course, but this particular exclude is recommended by the spring data neo4j docs ;) they just did it in maven.
