### ISSUE TITLE
Broken sample: Reporting code coverage with JaCoCo (aggregation)

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#17749]
### Expected Behavior
I can use sample from https://docs.gradle.org/7.1.1/samples/sample_jvm_multi_project_with_code_coverage.html to aggregate JaCoCo reports. The report contains only my sources.

### Current Behavior
The code from this sample includes all compile dependencies, including open-source libraries.

### Context
My code is organized into several subprojects. Often classes are not tested in the same subproject, but rather in a downstream subproject. Per-project JaCoCo coverage reports are useless in my code, because they report classes with zero coverage, when they in fact have 100% coverage. I have to use aggregated report.

I used to use a plugin to aggregate JaCoCo reports, but it crashes on Gradle 7 and is no longer maintained: https://github.com/wrlyonsjr/gradle-aggregate-jacoco/issues/1

The sample looks like it works but does not. It only gives this impression because it is too simplified: there are no external dependencies.

I agree with  #15534: this is a use case that should be handled by a Gradle-prepared plugin and not a sample that is not tested for regressions. But in the short term, the sample should be fixed.

### Steps to Reproduce 
1. Download ZIP from the top links of https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage.html
2. Append the following text to `list/build.gradle.kts`:
```kotlin
dependencies {
    implementation("com.google.guava:guava:30.1.1-jre")
}
```
3. Run `./gradlew check`
4. Open code-coverage-report/build/reports/jacoco/codeCoverageReport/html/index.html

The report is completely unreadable – project sources are lost between dependencies.

### Your Environment
```
------------------------------------------------------------
Gradle 7.1.1
------------------------------------------------------------

Build time:   2021-07-02 12:16:43 UTC
Revision:     774525a055494e0ece39f522ac7ad17498ce032c

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Ubuntu 11.0.11+9-Ubuntu-0ubuntu2)
OS:           Linux 5.11.0-22-generic amd64
```

**Comment by mlopatkin** [comment]
@gradle/core could you please take a look at this?

**Comment by pkubowicz** [comment]
Closing as Gradle 7.4 has a working solution with good sample projects.
