### ISSUE TITLE
Gradle TAPI passes all client JVM system properties to build process

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#17745]
When a Gradle Tooling API client launches a task or builds a model, all system properties of the client's JVM are passed to the build evaluation process, including forked JVM executions (tests or any JavaExec).

### Expected Behavior
TAPI client can control what system properties are set in the Gradle build.

### Current Behavior
TAPI client has no control over set of system properties being passed to the Gradle build.

### Context
IntelliJ IDEA has quite large number of system properties set. Some of them affect Gradle tasks, e.g. `java.system.class.loader` 
more details in JetBrains tracker https://youtrack.jetbrains.com/issue/IDEA-271340

### Your Environment

Build scan URL:

**Comment by donat** [comment]
I've created a local prototype for defining a filter for system properties and the concept seems plausible. We can do the filtering on the provider side (i.e. in the target Gradle version): https://github.com/gradle/gradle/blob/84aa2a6b3042df33a34f9e076f8b884f095ca447/subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/DaemonBuildActionExecuter.java#L43

**Comment by nskvortsov** [comment]
I'd expect TAPI to have something high-level, like `BuildLauncher.setSystemProperties(Map<String, String> effectiveProperties)` and these `effectiveProperties` to be used in https://github.com/gradle/gradle/blob/6ccf8a2cc74c8060992bd36189dec929143caed7/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java#L151 instead of `System.getProperties()`
