### ISSUE TITLE
In a multi variant kotlin library, all the variants get compiled for jdk8

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#17754]
As titled, I'm trying to produce multiple variants out of the same (kotlin) library: specifically jdk8 and jdk11. But when I publish to a local folder repository, both are compiled for jdk8, no matter what `kotlinOption.jvmTarget` or `.jdkHome` specify

`build.gradle.kts` [here](https://github.com/kotlin-graphics/kotlin-unsigned/blob/jdk9variant/build.gradle.kts)

If I print `jvmTarget` and `jdkHome` for the two tasks, I do get:

```
1.8
/usr/lib/jvm/java-8-openjdk-amd64
11
/home/elect/.gradle/jdks/jdk-11.0.10+9
```

which theoretically looks fine and expected, but the produced jars tell a different story

### Expected Behavior
`library-1.1.jar` should be compiled with jdk11, while `library-1.1-jdk8.jar` with jdk8

### Current Behavior
Both are compiled against jdk8

```
elect@5800x:~/IdeaProjects/kotlin-unsigned/repo/org/gradle/sample/library/1.1$ file library-1.1/unsigned/ArraysKt.class 
library-1.1/unsigned/ArraysKt.class: compiled Java class data, version 52.0 (Java 1.8)
elect@5800x:~/IdeaProjects/kotlin-unsigned/repo/org/gradle/sample/library/1.1$ file library-1.1-jdk8/unsigned/ArraysKt.class 
library-1.1-jdk8/unsigned/ArraysKt.class: compiled Java class data, version 52.0 (Java 1.8)
```

### Context
I'm trying to have multiple variants produced out of the same kotlin library
MCVE is [this branch](https://github.com/kotlin-graphics/kotlin-unsigned/tree/jdk9variant)

### Steps to Reproduce 
- clone the project (at the given branch: `jdk9variant`)
- run `publishMavenPublicationToProvaRepository`

### Your Environment
Gradle 7.1.1

Build scan [URL](https://gradle.com/s/pvjqdwmvmwldu)

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

This is an issue with the Kotlin Gradle Plugin which is developed by Jetbrains and cannot be addressed in the core of the Gradle Build Tool.

Please open such Kotlin-related issues on the Kotlin Issue Tracker at https://youtrack.jetbrains.com/issues/KT

**Comment by elect86** [comment]
[Done](https://youtrack.jetbrains.com/issue/KT-47788)

Thanks for pointing me that

**Comment by Vampire** [comment]
Just as reference here too, it is not a Kotlin plugin issue, just a bad build script.

I've had a quick look, what did you expect?
You have the `main` source set, and create additionally the `jdk8` and `jdk11` source sets.
You configure `jdk8` and `jdk11` source sets to your likings.
Then you only create a feature variant for `jdk8`.
So when you publish, the `main` variant and the `jdk8` variant are published which are both compiled with Java 8 which is the default for Kotlin.
If you e. g. replace `val jdk11 = sourceSets.create("jpms") ...` by `val jdk11 = sourceSets["main"]`, then you get the result you expected as fas as I understood what you want.
```bash
$ find repo -type f -name '*.jar' -not -name '*-sources.jar' -not -name '*-javadoc.jar*' -exec sh -c 'echo; echo {}; unzip -p {} $(zipinfo -1 {} | grep "\.c
lass$" | head -n 1) | file -k -' \;
repo/org/gradle/sample/library/1.1/library-1.1-jdk8.jar
/dev/stdin: compiled Java class data, version 52.0 (Java 1.8)\012- data
repo/org/gradle/sample/library/1.1/library-1.1.jar
/dev/stdin: compiled Java class data, version 55.0 (Java SE 11)\012- data
```
