### ISSUE TITLE
Provide a concise output format

### ISSUE THREAD

**Issue by xeruf** [gradle/gradle#17750]
When running `gradle` through a script, I would like to receive concise output in case of errors.

### Current Behavior
I can use the `--quiet` flag, but if there is an error, I get this monstrosity:
```sh
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':player:playerTest'.
> Timeout has been exceeded

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

### Expected Behavior
Either implicitly with the `--quiet` flag or with an additional `--concise` flag shorten the output on error to something like this:
```sh
Execution failed for task ':player:playerTest'.
> Timeout has been exceeded
BUILD FAILED in 6s
```

### Context
As an avid gradle user, I want to see the actual issue and only that when a script encounters an error. All the advice and pretty stuff around it is not appropriate in that context.

**Comment by mlopatkin** [comment]
This request is unlikely to get attention from us because of the limited bandwidth of the team. Would you or someone else from the community be interested in providing a PR implementing this?

**Comment by xeruf** [comment]
Maybe, but I also have quite a backlog of contributions ^^ how about adding a help-wanted label?
