### ISSUE TITLE
Project.afterEvaluate execution order is not specified in documentation

### ISSUE THREAD

**Issue by mhsmith** [gradle/gradle#1775]
Examination of the source code shows that items passed to `Project.afterEvaluate` are executed in the same order they were passed. However, this isn't specified in the documentation, so I am concerned about relying on it.

**Comment by grv87** [comment]
+1 for this.

See also an old thread in forum: https://discuss.gradle.org/t/are-multiple-afterevaluate-executed-in-the-sequence-on-how-they-are-defined/5785

**Comment by grv87** [comment]
I think I hit a situation where `afterEvaluate` blocks are executed not in the same order they were added.

In the following code:
```
      ...
      project.pluginManager.apply 'com.gradle.plugin-publish'

      ...

      project.afterEvaluate {
        project.plugins.findPlugin(JvmBasePlugin)?.with {
          sourcesJar.set project.tasks.withType(Jar).named('publishPluginJar')
          ...
        }
      }
```

`apply` in `com.gradle.plugin-publish` plugin  has `afterEvaluate` block that should create `publishPluginJar` task.
My `afterEvaluate` is after, but I got an exception that `publishPluginJar` doesn't exist.

**Comment by mhsmith** [comment]
The documentation still doesn't specify this, and 10 people have voted for the issue, so I think it should remain open.

**Comment by fsgjlp** [comment]
Tomorrow will be the fifth anniversary of this issue, [this thread](https://discuss.gradle.org/t/are-multiple-afterevaluate-executed-in-the-sequence-on-how-they-are-defined/5785) is almost eight years old.
We just need the answer like "yes, you can rely on this behavior" or "no, you can't rely on this behavior because..."

**Comment by mhsmith** [comment]
In practice I've been relying on it for the last 4 years without any problem. But as long as it's not part of the API contract, it's still possible that it might break in the future. I'd like to make sure that doesn't happen.

**Comment by nathan-contino** [comment]
Thanks for raising this issue. I just opened a PR to document this behavior. Those of you still lurking on this issue -- please let me know if this solution seems amenable to you, either here, or in the community slack, where I'd be happy to chat about this issue in more detail.

Apologies it's taken 5 years to address this.

**Comment by nathan-contino** [comment]
Merged in the PR fix -- thanks for reporting this issue! I'm slowly working through some of our documentation backlog, so expect to see more docs fixes in the coming days and weeks.
