### ISSUE TITLE
Support XDG Base Directory Specification

### ISSUE THREAD

**Issue by itaranto** [gradle/gradle#17756]
Please support the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux/*nix systems.

Right now gradle dumps everything user related to `~/.gradle` which is **not** nice for several reasons.

If you think that splitting this data between cache, config and user data is not feasible to do right now, **at the bare minimum** put everything under `$XDG_DATA_HOME/gradle` (with a fallback to `~/.local/share/gradle`)

I'm aware of the `GRADLE_USER_HOME` environment variable but I have two issues with that:
- XDG directories must be used by default without any user configuration
- gradle still puts some stuff under `~/.gradle/daemon` even with `GRADLE_USER_HOME` pointing elsewhere.

**Comment by mlopatkin** [comment]
This request makes sense. If you or someone is willing to make a PR for this then it will likely be accepted.

**Comment by donat** [comment]
A few reasons are listed [here](https://github.com/gradle/gradle/issues/8262#issuecomment-475847888) why the implementation would be problematic.
