### ISSUE TITLE
Script performance regression (+10s) when adding a buildscript block

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#17767]
### Expected Behavior
Adding a `buildscript` block to a script should not cause a major build performance regression.

### Current Behavior
If I add a `buildscript` block to a script, then I can observe in a build scan that configuration time for that script increases by 10s. 

### Context

I first noticed this when trying to understand why configuration times had blossomed from roughly 47s to 67s (per `gradle-profiler --benchmark help`). I manually compared build scans for `help` for each scenario, and noticed that I could pin the entire increase on two scripts, each of which had seen an increase of about 10s to configure. When I looked at those scripts, the only major change between the two scenarios was the addition of the `buildscript` block in the slower scenario. This block had been added after migrating a module out of `buildSrc` and into an included build. Because the module was no longer on the classpath by default, it had to be specified via `buildscript`. As an experiment, I removed the buildscript block and copied the relevant code directly into the script, and ran my benchmark + scans again: the regression disappeared.

The two scripts I'm talking about are each applied in about 2000 modules. Whatever cost `buildscript` carries seems to be getting multiplied by 2000. Other scripts also needed the addition of a `buildscript` block, but as they were only applied a handful of times, their performance (per build scans) did not degrade noticeably.

### Steps to Reproduce 
I haven't tried a _minimal_ reproducer, but here's how I verified this in my project. Consider a script `foo.gradle` that is applied in **2000** projects:
```
buildscript {
  repositories {
    mavenCentral() // actually we mirror this in a private Artifactory repository
  }
  dependencies {
    // This is not the dependency we added, but I've confirmed it doesn't matter if it's a first-party or
    // third-party dependency.
    classpath "org.apache.commons:commons-collections4:4.0"
  }
}
```
If I now run `./gradlew help --scan`, then I can see that the configuration time for this script (via **Performance > Configuration**) has gone up by 10s. I can confirm that overall configuration has also increased via `gradle-profiler --benchmark help`.

### Your Environment
Build scan URL: Private only, but can be provided via secure channels.

**Comment by donat** [comment]
> The two scripts I'm talking about are each applied in about 2000 modules. Whatever cost buildscript carries seems to be getting multiplied by 2000. 

That sounds about right. I think there's no caching involved when you modify the classpath of the build script.

What are you trying to achieve here? Judging from the sample, you want to use `commons-collections` in your scripts. For me, this is a good indicator that the build script's content should be refactored to a (binary, or maybe a precompiled script) plugin.

**Comment by autonomousapps** [comment]
This was the result of an intermediate step towards the long-term goal of having binary plugins, as you suggest. We had a bunch of stuff in buildSrc (which, as you know, is on every classpath by default). We moved that to an included build, which is no longer on the classpath by default. As such, we had to add `buildscript` blocks to some of our scripts so they would still work. These scripts are slated for deletion once we finish our migration / code cleanup. I was just shocked to see such a huge cost.

**Comment by big-guy** [comment]
The `buildscript` block gets compiled and evaluated separately as if it were another build script. Is the +10s regression happening on every configure or only on first use?

If you're just adding some non-plugin dependencies temporarily to the build script classpath, you could also do this only in the root (with `buildscript {}`) and let all of the children inherit the extra jar.

**Comment by autonomousapps** [comment]
The +10s configure seems to happen on every build. This is based on
running a benchmark with gradle profiler and looking at the final build
scan (of 10 runs). 

Regarding adding to the root, I tried that and it didn't work. I will
try again tomorrow to be certain. 

I can share a fair amount of information through private channels if
this seems an interesting problem. 

On July 20, 2021, GitHub ***@***.***> wrote:
> The buildscript block gets compiled and evaluated separately as if it
> were another build script. Is the +10s regression happening on every
> configure or only on first use?
>
> If you're just adding some non-plugin dependencies temporarily to the
> build script classpath, you could also do this only in the root (with
> buildscript {}) and let all of the children inherit the extra jar.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gradle/gradle/issues/17767#issuecomment-883780955>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABJG5PNZ4Y74I3WSZZRBGILTYYEYBANCNFSM5AUEA3JA>.

**Comment by jbartok** [comment]
Sorry for the late reply.

Instead of applied scripts we recommend the usage of convention plugins, so could you try and see if those work better in your case?

Given your example project, we are talking about 5ms per sub-project, which doesn't sound that unreasonable, depending on the circumstances (we don't know much about the environment you're running in).

Please open a new issue if you are still having problems with convention plugins and recent versions of Gradle.
