### ISSUE TITLE
Gradle plugin sources are not published to Plugin Portal when `maven-publish` plugin is applied

### ISSUE THREAD

**Issue by ileasile** [gradle/gradle#17760]
I'm writing a Gradle plugin, using `java-gradle-plugin` and `com.gradle.plugin-publish` plugins as described in [the instruction](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html). When I trigger `publishPlugins` task, everything works fine, and it publishes javadoc and sources jars, i.e.:
```
Publishing plugin ru.ileasile.kotlin.doc version 0.0.34-dev
Publishing plugin ru.ileasile.kotlin.publisher version 0.0.34-dev
Publishing artifact build/libs/kotlin-libs-publisher-0.0.34-dev.jar
Publishing artifact build/libs/kotlin-libs-publisher-0.0.34-dev-sources.jar
Publishing artifact build/libs/kotlin-libs-publisher-0.0.34-dev-javadoc.jar
Publishing artifact build/publish-generated-resources/pom.xml
Activating plugin ru.ileasile.kotlin.doc version 0.0.34-dev
Activating plugin ru.ileasile.kotlin.publisher version 0.0.34-dev
```

But when I apply `maven-publish` plugin in order to setup a local repository for the publication, `publishPlugins` task starts to work differently and doesn't publish the sources and javadoc jars, i.e.:
```
Publishing plugin ru.ileasile.kotlin.doc version 0.0.33-dev
Publishing plugin ru.ileasile.kotlin.publisher version 0.0.33-dev
Publishing artifact build/libs/kotlin-libs-publisher-0.0.33-dev.jar
Publishing artifact build/publications/pluginMaven/pom-default.xml
Publishing artifact build/publications/pluginMaven/module.json
Activating plugin ru.ileasile.kotlin.doc version 0.0.33-dev
Activating plugin ru.ileasile.kotlin.publisher version 0.0.33-dev
```

### Expected Behavior
I expect that `publishPlugin` task should continue publishing source and javadoc jars 

### Current Behavior
Sources and javadoc jars are published only if `maven-publish` plugin is not applied, so you have to choose between the ability to publish source jars and publish plugin locally. Moreover, I don't know a correct workaround for it, because adding a sources artifact manually to all maven publications doesn't fix the problem for publishing to portal.

### Context

I want to have an ability to publish my plugin locally and to portal, and with sources and javadoc jars.

### Steps to Reproduce 

Here is the example project: https://github.com/ileasile/kotlin-libs-publisher/blob/master/build.gradle.kts
You may uncomment corresponding lines to reproduce the incorrect behavior.

### Your Environment

Build scan URL:
https://scans.gradle.com/s/eaz765kb5j2s2

There is also a part of a build log with --info:
```
> Task :publishPluginJar
Caching disabled for task ':publishPluginJar' because:
  Build cache is disabled
  Caching has not been enabled for the task
Task ':publishPluginJar' is not up-to-date because:
  Output property 'archiveFile' file C:\Projects\kotlin-libs-publisher\build\libs\kotlin-libs-publisher-0.0.34-dev-sources.jar has been removed.
:publishPluginJar (Thread[Execution worker for ':',5,main]) completed. Took 0.059 secs.
:javadoc (Thread[Execution worker for ':',5,main]) started.

> Task :javadoc NO-SOURCE
Skipping task ':javadoc' as it has no source files and no previous output files.
:javadoc (Thread[Execution worker for ':',5,main]) completed. Took 0.001 secs.
:publishPluginJavaDocsJar (Thread[Execution worker for ':',5,main]) started.

> Task :publishPluginJavaDocsJar
file or directory 'C:\Projects\kotlin-libs-publisher\build\docs\javadoc', not found
Caching disabled for task ':publishPluginJavaDocsJar' because:
  Build cache is disabled
  Caching has not been enabled for the task
Task ':publishPluginJavaDocsJar' is not up-to-date because:
  Output property 'archiveFile' file C:\Projects\kotlin-libs-publisher\build\libs\kotlin-libs-publisher-0.0.34-dev-javadoc.jar has been removed.
file or directory 'C:\Projects\kotlin-libs-publisher\build\docs\javadoc', not found
:publishPluginJavaDocsJar (Thread[Execution worker for ':',5,main]) completed. Took 0.014 secs.
:publishPlugins (Thread[Execution worker for ':',5,main]) started.

> Task :publishPlugins
Caching disabled for task ':publishPlugins' because:
  Build cache is disabled
Task ':publishPlugins' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Publishing plugin ru.ileasile.kotlin.doc version 0.0.35-dev
Publishing plugin ru.ileasile.kotlin.publisher version 0.0.35-dev
Publishing artifact build/libs/kotlin-libs-publisher-0.0.35-dev.jar
Publishing artifact build/publications/pluginMaven/pom-default.xml
Publishing artifact build/publications/pluginMaven/module.json
Activating plugin ru.ileasile.kotlin.doc version 0.0.35-dev
Activating plugin ru.ileasile.kotlin.publisher version 0.0.35-dev
:publishPlugins (Thread[Execution worker for ':',5,main]) completed. Took 3.979 secs.
```

Here we can see that sources and javadoc jars were actually created by `publishPluginJar` and `publishPluginJavaDocsJar`, but were not loaded to plugin portal actually - rather strange thing, to be honest.

**Comment by ileasile** [comment]
Even adding this to the publishing extension configuration doesn't fix the issue 
```
    afterEvaluate {
        publications {
            withType<MavenPublication> {
                artifact(tasks["sourceJar"])
            }
        }
    }
```

Though, it has been possibly working, judging by this 2-year old example: https://github.com/marcphilipp/gradle-sandbox/blob/85e934d13b413df2fccd752591f631128e7e7734/plugin-maven-publish/build.gradle#L23-L44

**Comment by ileasile** [comment]
By the way, it is very likely that the problem in `com.gradle.plugin-publish`, but I was unable to find its sources on the internet. Are they closed?
The last available sources are here: https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/0.9.1/
Sources of this plugin are not published since v. `0.9.2` - and I'm not sure it was done by intention

**Comment by ljacomet** [comment]
@ileasile The `plugin-publish` plugin is closed source, more for historical reasons than anything.

Can you try using the following in your project and let us know if it works then?
```
java {
    withSourcesJar()
    withJavadocJar()
}
```

**Comment by ileasile** [comment]
Whoa, it worked! Thanks, @ljacomet.
But it was somewhat misleading, maybe behavior should be unified here.

**Comment by ljacomet** [comment]
Closing as this is resolved by using core constructs
