### ISSUE TITLE
Get semantic information from build script

### ISSUE THREAD

**Issue by CsCherrYY** [gradle/gradle#17773]
Hello,

I'm looking for a way to get the semantic information (or compilation information) from a build script. For example, given a part of `build.gradle` script:
```
dependencies {
    compile gradleApi()
}
```
for symbol `dependencies`, it will be the method call `dependencies()` of interface `org.gradle.api.Project` in execution. For symbol `gradleApi()`, it will call `gradleApi()` in `org.gradle.api.artifacts.dsl.DependencyHandler`. Is there any API or way to get this semantic information programmatically for a script? I just tried to get some information from `Project` instance in a custom gradle plugin or directly use tooling API, but nothing found. 

Thanks in advance!

**Comment by blindpirate** [comment]
Please take a look at https://groovy-lang.org/closures.html#_delegation_strategy

The gradle build script is simply a Groovy file which complies with Groovy `Closure` delegation strategy.
