### ISSUE TITLE
Unit Testing Gradle Plugins: Dependency Resolution fails due to race condition

### ISSUE THREAD

**Issue by jptrn** [gradle/gradle#17774]
Our unit tests for a Gradle plugin involve creating a Gradle project using `ProjectBuilder` and then resolving the dependencies of a given configuration with `configurations.<...>.resolvedConfiguration.resolvedArtifacts`. 

When the same dependency is added twice in different configurations, the resolution will occasionally fail due to what looks like a race condition:

```groovy
    project.dependencies.add("api", "org.joda:joda-convert:2.1.1")
    project.dependencies.add("implementation", "org.joda:joda-convert:2.1.1")
```

Gradle will determine that it needs to download the metadata of `org.joda:joda-convert:2.1.1` twice (`DependencyGraphBuilder#maybeDownloadMetadataInParallel`), from which point, the following seems to be happening:

* Two threads will try to download the dependency
* One thread creates a file lock for the `descriptor.bin` file ([`DefaultPathKeyFileStore#doAdd:143`](https://github.com/gradle/gradle/blob/v7.1.1/subprojects/core/src/main/java/org/gradle/internal/resource/local/DefaultPathKeyFileStore.java#L143)), e.g.: `<...>/userHome/caches/modules-2/metadata-2.97/descriptors/org.joda/joda-parent/1.1.2/<...>/descriptor.bin.fslck`
* The other thread finds the file already existing and updates the file's modified-date ([`GFileUtils#touch:68`](https://github.com/gradle/gradle/blob/v7.1.1/subprojects/base-services/src/main/java/org/gradle/util/GFileUtils.java#L68))
* The first thread deletes `descriptor.bin.fslck` after it is done
* The second thread tries to update the modified-date, but since the file is already gone, will throw a `NoSuchFileException` which is ultimately translated into a `ResolveException`

The issue seems to happen on both Windows and Linux. I've tested it on AdoptOpenJDK 1.8.0_282-b08, AdoptOpenJDK 11.0.10+9 and AdoptOpenJdk 16.0.1+9. I've only been able to see this issue occur in unit tests using the method described above. I've not been able to replicate it using `GradleRunner`, or in real builds.
I've reproduced the issue with Gradle versions 7.1, 7.0, 6.8.2 and 6.1.1.

[Here is a small example repository](https://github.com/jptrn/FlakyGradlePluginTest) with a unit test that runs until triggering the failure. Note that the exception that is thrown in the test is a `IllegalStateException` - this is because Gradle tries to annotate the `ResolveException`, but fails because there is no `Settings` object in a test environment. This appears to be unrelated.

**Comment by Vampire** [comment]
This is a duplicate of #11752
