### ISSUE TITLE
Add userguide section for Maven artifact relocation

### ISSUE THREAD

**Issue by Marcono1234** [gradle/gradle#17772]
### Expected Behavior
Extend ["Maven Publish Plugin" userguide](https://docs.gradle.org/current/userguide/publishing_maven.html) to describe Maven artifact relocation (see [Maven "Guide to relocation"](https://maven.apache.org/guides/mini/guide-relocation.html)).

### Current Behavior
Artifact relocation is not documented.

### Context
Maven artifact relocation seems to be a little-known feature, however multiple projects encounter the need to change their groupId or artifactId during their development.
The advantage of artifact relocation is that it allows users to understand why no new releases are published under a Maven coordinate, and what they need to do to upgrade. Note that this heavily depends on tool support, but for example MVN Repository shows this information ([example](https://mvnrepository.com/artifact/ant/ant)) and the Maven command line tool emits a warning when you have a dependency on a relocation POM.

Without relocation POMs it is often not obvious to users what they need to do to upgrade dependencies.

#### Suggested changes
(Note that I am not completely familiar with the matter, but I can try drafting a pull request if that is desired.)

- Add a section "Publishing Maven artifact relocation information" (or similar) below the section "Publishing to Maven Local" of the ["Maven Publish Plugin" userguide](https://docs.gradle.org/current/userguide/publishing_maven.html).
- The section should contain examples (here is a demo project which might help: https://github.com/Marcono1234/gradle-relocation-test, see commits and published artifacts on the right)
- The section should mention:
  - Relocation information should be removed from the Gradle build file once it has been published
  - Relocation information can be published retroactively (and can even refer to a "lower" version for the new artifact, e.g. when numbering has started at 1.0.0 again).
  However, in that case the version numbering of the old, relocated artifact should probably continue and refer to the new artifact version corresponding to that version, e.g. when project `com.new-example:10.0` retroactively publishes a relocation POM for `com.example` it should be `com.example:3.0` → `com.new-example:3.0` (assuming 3.0 was when the rename happened) instead of `com.example:3.0` → `com.new-example:10.0` or `com.example:10.0` → `com.new-example:10.0`, to simply migration for the user (i.e. they first switch to the new artifact coordinates and then upgrade the version if they want to).
  - That configuration can be tested locally by publishing the relocation POM to the local Maven repository and then creating a test project depending on it
  - That a module might also want to [publish capability metadata](https://docs.gradle.org/current/userguide/dependency_capability_conflict.html#sub:declaring-component-capabilities) to avoid both the old and the new artifact being on the classpath when they both use the same package names

Maybe it could also refer to the documentation for [`MavenPomRelocation`](https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPomRelocation.html).

**Comment by mlopatkin** [comment]
Thank you for the suggestion! If you want to contribute a PR then please go ahead.
