### ISSUE TITLE
Circular dependency between tasks

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#17784]
Hi Gradle folks, when building a project with some particular setup, the build fails with "Circular dependency between the following tasks". Note this issue is not specific to Android project.

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Circular dependency between the following tasks:
> :A:lib:compileJava
> \--- :A:lib:compileJava (*)
> 
> (*) - details omitted (listed previously)

The structure of this project is:

root
 -----A:lib (has a dependency on B:lib)
 -----B:lib

And one important thing of this setup is both of them has same group and version.

```
// from build.gradle of root project
allprojects {
  version = '0.1'
  group = 'a.b.c'
}
```

### Context

AGP has a check to make sure the combination of group & project name is unique across projects, but we would like to remove this check cause it is obsolete and not compatible with project isolation. Currently, with this check, we fail earlier so we won't hit the above circular dependency issue. But once we remove the check, this issue is uncovered. 

### Steps to Reproduce 

Please use the sample project attached and run `gradle build`

[circularDependency.zip](https://github.com/gradle/gradle/files/6850700/circularDependency.zip)

**Comment by blindpirate** [comment]
You need to keep `A:lib` and `B:lib` have different names, because a module is uniquely identified by `group:name:version`. In your project, both `A:lib` and `B:lib` has same `a.b.c:lib:1.0`, so they're recognized as same module, i.e. "circular dependency". This is expected behavior.

Workaround: 


in settings.gradle:

```
project(":B:lib").name = 'libB'
```
in A/lib/build.gradle:

```
api project(':B:libB')
```

**Comment by mlopatkin** [comment]
The issues #847 and #16986 have more context about this issue. We are considering adding a warning for duplicate project names to the Gradle core but there is no particular timeline for this.

**Comment by itshash01** [comment]
implementation project(':app')

**Comment by HerrDerb** [comment]
Just stumbled into this issue.

For my perception `a:runtime` and `b:runtime` have clearly a name as the parent project is part of it. Is there any better solution to it than manually renaming this projects? this is really confusing for a multi project repo.
