### ISSUE TITLE
Cannot create service of type DefaultBuildEventsListenerRegistry

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#17783]
Context: https://issuetracker.google.com/193859160

Using the [MyApplication.zip](https://github.com/gradle/gradle/files/6850261/MyApplication.zip) and running `cd buildSrc && gw test`, this fails with `Caused by: org.gradle.internal.service.ServiceCreationException: Cannot create service of type DefaultBuildEventsListenerRegistry using DefaultBuildEventsListenerRegistry constructor as required service of type BuildEventListenerFactory for parameter #1 is not available.`

It seems that when using the `ProjectBuilder` to create a test project, not all services are created. This is an issue because plugins applying AGP in tests will fail as AGP registers an `OperationCompletionListener` instance during application.

**Comment by th-jtullgren** [comment]
Hi is there any workaround for this issue?  Half of our unit tests for our Gradle plugin (which depends on the Android Gradle Plugin) now fail.

Thanks!

**Comment by donat** [comment]
@th-jtullgren issuetracker.google.com/193859160 contains a workaround.

**Comment by donat** [comment]
The issue is still present in Gradle 7.1.1.

**Comment by th-jtullgren** [comment]
The workaround found in issuetracker.google.com/193859160 worked for me. thanks

**Comment by sdeleuze** [comment]
This bug impacts likely any project testing Kotlin Gradle plugin as of version 1.6.0, see https://youtrack.jetbrains.com/issue/KT-49547 for more details, Spring is impacted.

**Comment by eskatos** [comment]
Duplicate of https://github.com/gradle/gradle/issues/16774
