### ISSUE TITLE
bash wrapper and start scripts are veeery slow (20 s) on Cygwin with mounted network drives that are available right at the root directory

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17806]
The shell scripts do for the Cygwin path translation to find path arguments to be translated the command `find -L / -maxdepth 1 -mindepth 1 -type d`.
This should list all top-level directories to find absolute paths in the arguments.

The problem is, if you
- have mapped network drives (we have 11+ at work)
- maybe are additionally connected via VPN
- have the drives available at `/...` via symlinks to `/cygdrive/...`,

then this `find` command is majorly slow, so that you have to wait around 20 seconds (in words: twenty seconds, this is not a typo) until the actual Gradle process is actually started and prints something.

Maybe it could be somehow made faster by not using `find` but for example `ls -1 --color=none` which works blazingy fast.
It also matches files at the root directory, but I'd say it is even more correct to also do the `cygpath` call for those.

### Expected Behavior
bash start scripts start fast even with mapped network drives

### Current Behavior
it is veeery slow

### Your Environment
Gradle 7.1.1

**Comment by big-guy** [comment]
@Vampire could you try generating gradlew/start scripts with the 7.2 nightly? You can still keep using an older version of Gradle, just update the scripts.

These scripts were revamped and that find was removed.

**Comment by Vampire** [comment]
I had a look at the changes and as the problematic find is gone, I assume it will be fast now.
I'll let the colleague test it that had the problem as I'm not using Cygwin anymore.
I'll close it for now and reopen it if there should still be the issue, but I don't think so, thanks.

**Comment by Vampire** [comment]
Works perfectly fine now.
Still a bit slow if you actually have one of the mapped network drives as path (2 seconds) but as long as you do not reference any path or reference only local paths, it works perfectly fine now regarding speed.

**Comment by GunnarBernsteinHH** [comment]
possibly related to #17955 
still waiting on disconnected network drives
