### ISSUE TITLE
Gradle init is destructive even when cancelled

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#17803]
There are a couple intertwined issues about running `gradle init`:

1) even if you hit `Ctrl+C`, some files will be created in the current directory,
2) accidentally running `gradle init` in your home directory leads to disappointing results (even if you hit `Ctrl+C` to cancel):
  - you get files like `gradlew.bat` in your user home
  - your `~/.gradle` directory will be deleted, with all the locally cached data, which leads to things having to be re-downloaded and re-built,
  - it will also delete your `~/.gradle/gradle.properties` and `~/.gradle/init.d` directories that can hold hard to recover custom configuration; it is also hard to notice that your custom configuration has been removed.

**Comment by lptr** [comment]
Some things we could do to avoid these problems:

- only create files once the user has finished and agreed to create the new project,
- check if there's a `.gradle` directory already in the current folder, and warn/fail,
- display the path where the new project will be created,
- keep Gradle's user configuration files and local state according to the XDG spec (see #17756) to prevent them being removed in this way.

**Comment by adammurdoch** [comment]
This PR removes the deleting of the `.gradle` directory (plus some other stuff): https://github.com/gradle/gradle/pull/17853

btw, running `gradle init` in your home directory was actually the only Gradle invocation that would not delete the `~/.gradle` directory. Instead, it would happen on any other invocation, for example when running `gradle` or `gradle help` or `gradle build`.

**Comment by jbartok** [comment]
> This PR removes the deleting of the `.gradle` directory (plus some other stuff): #17853
> 
> btw, running `gradle init` in your home directory was actually the only Gradle invocation that would not delete the `~/.gradle` directory. Instead, it would happen on any other invocation, for example when running `gradle` or `gradle help` or `gradle build`.

Thank you, I will look into reverting the changes of this PR.

**Comment by jbartok** [comment]
@lptr should we create a separate issue for `Ctrl+C` not working properly with `gradle init`? That's a specific problem with init, while the general destructiveness was what has been addressed so far.

**Comment by lptr** [comment]
I'd be fine with both creating a new issue and closing this one, or removing (~~crossing out~~) the stuff from this one that has been resolved already. Take your pick!

**Comment by jbartok** [comment]
Unresolved part will be picked up in #18080
