### ISSUE TITLE
Linux to Windows path transformation in bash wrapper and start scripts do not work with a cygdrive mount at root

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17807]
This is related to #17805, but a different detail.

If you use a cygdrive mount at the root directory, the path transformation logic does not work properly for drives.
If you want to have things like `/c`, `/d` and so on available in Cygwin, there are two possibilities.
You can either keept the default mount line in `/etc/fstab` (something like `none /cygdrive cygdrive binary 0 0` and then add symlinks like `/c -> /cygdrive/c`.
But the usually better approach is, to just change the mount line to `none / cygdrive binary 0 0`, so that the drives are directly mounted at `/...`.

The problem with this approach is, that neither `ls /` nor `find /` will see these mounted drives and thus the path transformation is not done. On msys (or at least Git for windows) this is the default behaviour, but it does not make problems and even is better because then the msys logic that already transforms the paths does it properly as mentioned in #17805.

But on Cygwin there is no built-in path transformation and as `find /` does not see those mountpoints, the according paths are not recognized as absolute paths that need to be transformed using `cygpath`.

The script could either parse the output of `mount` where those paths are listed, but this again is slow. Not as slow as what I describe at #17806, but still noticable (around 2 seconds). So maybe as an approximation with some hope all paths just consisting of slash and one character or starting with slash, one character, slash, could also be considered an absolute path.

### Expected Behavior
Giving a Linux path on Cygwin with custom cygpath mount works

### Current Behavior
The paths are used as relative paths

### Your Environment
Gradle 7.1.1

**Comment by big-guy** [comment]
@Vampire could you check this again with 7.2? https://github.com/gradle/gradle/issues/17806#issuecomment-885190533

**Comment by Vampire** [comment]
Nice, without the listing and instead just checking whether it is there it works much better, thanks.
