### ISSUE TITLE
Linux to Windows path transformation in bash wrapper and start scripts are erroneous

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17805]
If you use the bash wrapper script, within msys environment, for example `C:\Program Files\Git\usr\bin\bash.exe -l -i` from Git for Windows, the translation of paths does not work properly. Most probably it is the same for Cygwin, but I didn't test it, but it is the same code path.

If you for example do `./gradlew -p /bin`, then you get `./gradlew: line 152: Files/Git/usr/bin: No such file or directory`  and then `An empty argument was provided for command-line option '-p'.`, an inserted `declare -p APP_ARGS` shows:
```
declare -- APP_ARGS="'-p' \\
'' \\
 "
```
I think this is because of the space in the Windows path that is not escaped properly somewhere.

Furthermore on msys environment, the translation for things like class path might be necessary, but the single-argument path translation should just not be done in the script as msys already does that for you unless you disable it.

For example if you do `ls -alh /` or what the script does `find -L / -maxdepth 1 -mindepth 1 -type d`, then the Windows drives like `/c` and so on are not shown, but they can magically be used anyway. So if you for example do `./gradlew -p /c`, then the script does not touch it (which you can see from the error when doing `MSYS_NO_PATHCONV=1 ./gradlew -p /c` which complains that the `c` directory under the current work directory does not exist) but msys properly translates the path including spaces.

If you comment out the lines that do the single argument path translation (151, 152, 153, 155), then `./gradlew -p /bin` properly fails with the message that it couldn't create `C:\Program Files\Git\usr\bin\.gradle` as now msys did the path translation properly and also escaped the spaces as needed.

So I'd suggest to not do the path translation (or at least the single-argument one) in the msys case, but just in the cygwin case, and if the some translation remains to happen, test that spaces are handled properly.

### Expected Behavior
Path with spaces and system drive paths are transformed and forwarded properly.

### Current Behavior
They are not

### Your Environment
Gradle 7.1.1

**Comment by big-guy** [comment]
@Vampire could you check this again with 7.2? https://github.com/gradle/gradle/issues/17806#issuecomment-885190533

**Comment by Vampire** [comment]
The spaces work properly now, thanks.

What still is to be thought about is, why for msys the path translations are done at all, as msys does it already and there the user is even able to enable or disable the behavior.

Is it better that the script does the translation always, no matter how the user has set the MSYS environment variable, or is it better to let msys do the translation and let the user choose whether the translation should be done or not?

**Comment by big-guy** [comment]
@Vampire This may be a relatively new addition (7.1): https://github.com/gradle/gradle/pull/17241

The special casing of msys has always been there, but we started treating more operating systems (reported by uname) as MSYS because people reported this as broken. MSYS was treated the same as MINGW.

Is it possible that MSYS's automatic translation only works for certain cases, but fails for something like a path list (`path/to/jar:path/to/another/jar`)?

We don't have exhaustive tests that try different combinations of POSIX-like environments, so I wouldn't be surprised if we're doing something wrong.

**Comment by Vampire** [comment]
Actually I don't see why it shouldn't work except if disabled using environment variable:
```
$ java -jar /c/Program\ Files
Error: Unable to access jarfile C:/Program Files
$ java -jar /c/Program\ Files:/d/Sourcecode/
Error: Unable to access jarfile C:\Program Files;D:\Sourcecode\
$ MSYS_NO_PATHCONV= java -jar /c/Program\ Files
Error: Unable to access jarfile /c/Program Files
$ MSYS_NO_PATHCONV= java -jar /c/Program\ Files:/d/Sourcecode/
Error: Unable to access jarfile /c/Program Files:/d/Sourcecode/
```
But I'm also no msys expert, so I might be wrong as well.

How about keeping the `cygpath` logic in the script template also for msys,
but allowing to disable it on demand with some environment variable like `<the built program>_NO_PATHCONV` or `<the built program>_ARG_CONV_EXCL="*"`?
In the MSYS from which Git for Windows is built, it is `MSYS_NO_PATHCONV` which when set suppresses the conversion completely, in MSYS2 it is `MSYS2_ARG_CONV_EXCL` where you can configure specific excludes which is better of course and you can disable conversion completely using `MSYS2_ARG_CONV_EXCL="*"`.
This should then though maybe only work on user-given paths and on the internal paths like `JAVACMD` it should still be done I guess.

**Comment by ov7a** [comment]
Thanks for your interest in Gradle!

@Vampire Sorry for the late reply. While I don't have a good answer for your last question here, since some changes were done in Gradle 7.2, I'm closing this issue as being (partially) solved. Please open a new one with a specific request if you still have some issue with that setup.
