### ISSUE TITLE
Root level files get not path-translated for Cygwin (and msys) in the generated shell scripts

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17815]
The generated shell scripts in 7.1.1 and also the revamped ones in 7.2-20210722005157+0000 only translate paths from Linux notation to Windows notation if they are absolute and starting with an existing directory.

While it might be questionable why only _existing_ directories are translated, it is probably the most common case.
But if you have a root level file as argument like `/LICENSE.txt`, this is not translated to a windows path.
On msys it works nontheless if you didn't disable the automatic path translation msys already does, but the Gradle generated script also there does not do its work.

The reason in the 7.2 snapshot is, that `[ -d "$t" ]` is tested and thus only directories are considered.
If this check would be changed to test for existence `[ -e "$t" ]` it would also work properly for files.

### Your Environment
Gradle 7.2-20210722005157+0000

**Comment by mlopatkin** [comment]
@big-guy could you please take a look at this as well, as you were touching the relevant bits recently?

**Comment by big-guy** [comment]
I believe this is fixed in https://github.com/gradle/gradle/pull/17854
