### ISSUE TITLE
GRADLE_CYGPATTERN should be injected into the template adjusted to the built application like GRADLE_OPTS

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17816]
The `unixStartScript.txt` template directly uses the variable `GRADLE_CYGPATTERN` which is meant to be supplied by the user of the script for adding patterns that should be sent through `cygpath`.

For the Gradle wrapper script this is perfectly fine, but the same template is also used for other applications built using the `application` plugin. And there the variable name should probably better be adapted to the built application name like `GRADLE_OPTS` is too by injecting the variable name from the user of the template.c

Or if all applications built with Gradle should benefit from the same variable someone set for his local system which might also be desirable, then at least it should get a more generic name that does not contain `GRADLE`, maybe just `CYGPATTERN`.  Or maybe a generic `CYGPATTERN` that can work for all applications coming from that template and a specific `<APPLICATION>_CYGPATTERN`, just like with `JAVA_OPTS` and `GRADLE_OPTS`.

### Your Environment
Gradle 7.2-20210722005157+0000

**Comment by mlopatkin** [comment]
@big-guy could you please take a look at this as well, as you were touching the relevant bits recently?

**Comment by big-guy** [comment]
I decided to just remove this (https://github.com/gradle/gradle/pull/17854) since we handle detecting paths in a different way now.
