### ISSUE TITLE
Configuration cache should report a problem when variable declared with unsupported type is captured by a lambda

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#17821]
For example:

```kotlin
// build.gradle.kts
tasks.some {
    val files: Configuration = ....
    doLast {
        doSomethingWith(files)
    }
}
```

Capturing `Configuration` instances is unsupported. With the above no problems are reported but the build reusing the configuration cache fails with `Caused by: java.lang.ClassCastException: class org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection cannot be cast to class org.gradle.api.
artifacts.Configuration`.

The Kotlin lambda capturing `files` declared with type `Configuration` is the culprit. The configuration cache problem detection misses this.

Changing this build logic to the following fixes the issue:
```
// build.gradle.kts
tasks.some {
    val files: FileCollection = ....
    doLast {
        doSomethingWith(files)
    }
}
```

### Expected Behavior

The problem should be reported always, whatever is the code construct (Java/Groovy/Kotlin lambdas, anonymous classes etc...)  that captures faulty members.

### Current Behavior

In some cases the problem is not reported.

### Context

Problem seen in a real world build, the lack of reporting made it hard to troubleshoot.

**Comment by bamboo** [comment]
Do we already report it for arbitrary bean fields?

**Comment by eskatos** [comment]
@bamboo yes

**Comment by bamboo** [comment]
Related to #19047

**Comment by h0tk3y** [comment]
I see that, at least in some cases, it's already working as expected now.
For instance, in this provided example:
```
val some by tasks.registering {
    val conf = myConfiguration
    doLast {
        println(conf.files)
    }
}
```
the problem is now reported as follows during an attempt to store the configuration cache entry:
```
- Task `:some` of type `org.gradle.api.DefaultTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
```
So we need to check which cases have not been covered by some changes yet.

**Comment by bamboo** [comment]
@h0tk3y Is that with Kotlin already emitting JVM lambdas or still with SAM classes? I'd expect the latter to work but not the former. 

Do you get the same behavior in Java?

**Comment by h0tk3y** [comment]
@bamboo
> Is that with Kotlin already emitting JVM lambdas or still with SAM classes? I'd expect the latter to work but not the former.

I've double checked it, and with a Kotlin plugin or script, I get a properly detected problem with the SAM conversion both to an anonymous class (by default in 1.7.21) and to a lambda instantiated using the metafactory (with `-Xlambdas=indy`; tried this only in a plugin, not the build script directly).

```
1 problem was found storing the configuration cache.
- Task `:some` of type `org.gradle.api.DefaultTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
```

Property trace for SAM conversion to an abstract class:

> cannot serialize object of type `org.gradle.api.internal.artifacts.configurations.DefaultConfiguration`, a subtype of `org.gradle.api.artifacts.Configuration`, as these are not supported with the configuration cache.
> * field `$configuration` of `com.example.MyPlugin$apply$1$1`
>     * bean of type `com.example.MyPlugin$apply$1$1`
>         * field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper`
>             * bean of type `org.gradle.api.internal.AbstractTask$TaskActionWrapper`
>                 * field `actions` of `org.gradle.api.DefaultTask`
>                     * task `:some` of type `org.gradle.api.DefaultTask`

Property trace for an `invokedynamic`-instantiated lambda: 

> ️cannot serialize object of type `org.gradle.api.internal.artifacts.configurations.DefaultConfiguration`, a subtype of `org.gradle.api.artifacts.Configuration`, as these are not supported with the configuration cache.
> * field `arg$1` of `com.example.MyPlugin$$Lambda$2255/0x0000000802298420`
>     * bean of type `com.example.MyPlugin$$Lambda$2255/0x0000000802298420`
>         * field `capturedArgs` of `java.lang.invoke.SerializedLambda`
>             * bean of type `java.lang.invoke.SerializedLambda`
>                 * field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper`
>                     * bean of type `org.gradle.api.internal.AbstractTask$TaskActionWrapper`
>                         * field `actions` of `org.gradle.api.DefaultTask`
>                             * task `:some` of type `org.gradle.api.DefaultTask`

<hr>

> Do you get the same behavior in Java?

Unfortunately, not. The Java lambdas instantiated using the metafactory don't seem to be properly detected when they capture a `Configuration`. The state is stored, and the build then fails during the load:

```
* Exception is:
org.gradle.api.GradleException: Could not load the value of field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper` bean found in field `actions` of task `:some` of type `org.gradle.api.DefaultTask`.
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:108)
        ...
Caused by: java.lang.ClassCastException: class org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection cannot be cast to class org.gradle.api.artifacts.Configuration (org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection and org.gradle.api.artifacts.Configuration are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @3b95a09c)
        at com.example.MyPluginJava.$deserializeLambda$(MyPluginJava.java)
        ...
```

This is quite unexpected to me, given that it worked for Kotlin. I think I'll have to take a closer look at this behavior with Java.

**Comment by bamboo** [comment]
@h0tk3y Interesting! So it seems the Kotlin compiler is still emitting a proper class to hold the captured environment (as evidenced by the `bean of type com.example.MyPlugin$$Lambda$2255/0x0000000802298420` trace).

**Comment by h0tk3y** [comment]
Yes, that's what I found, too. In short, instead of instantiating the `Action`-implementing lambda directly, the Kotlin code first instantiates a `Function1` (with the actual lambda, using `LambdaMetaFactory`) that captures `Configuration` and then instantiates an `Action` which captures the `Function1` (and only invokes it in the implementation).

And this causes more problems: the `Function1` is not `Serializable`, and the instruction instantiating it does not seem to be transformed to enable serialization, and therefore the `Function1` instance does not have `writeReplace` returning `SerializedLambda`. So when Gradle configuration cache serializes the outer `Action`, the `Function1` is not serialized correctly. An attempt to run the build from such a cache entry fails as follows:

```
org.gradle.api.GradleException: Could not load the value of field `capturedArgs` of `java.lang.invoke.SerializedLambda` bean found in field `action` of `org.gradle.api.internal.AbstractTask$TaskActionWrapper` bean found in field `actions` of task `:some` of type `org.gradle.api.DefaultTask`.
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:108)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt$readPropertyValue$1.invokeSuspend(BeanPropertyReader.kt)
        ...
Caused by: java.lang.ClassNotFoundException: com.example.MyPlugin$$Lambda$1208/0x0000000801654420
        at org.gradle.configurationcache.serialization.DefaultReadContext.readClass(Contexts.kt:285)
        at org.gradle.configurationcache.serialization.codecs.BeanCodec.decode(BeanCodec.kt:44)
        at org.gradle.configurationcache.serialization.CombinatorsKt$reentrant$1$decodeLoop$1.invokeSuspend(Combinators.kt:165)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        ... 160 more
```

**Comment by h0tk3y** [comment]
Also, I found one more way to break things with Kotlin, even without a non-serializable nested `Function1`.

If you extract the `Action<Task>` into a variable rather than pass the lambda to the `register` call, like this:

```
target.tasks.register("some") { task ->
    val configuration: Configuration = myConfiguration
    val function = Action<Task> {
        println(configuration.files.toList())
    }
    task.doLast(function)
}
```

Then the Kotlin code produced with `-Xlambdas=indy` does not instantiate the intermediate `Function1` and directly instantiates an `Action`. In this case, the behavior is the same as that with Java: in deserializing, the file collection fails to cast to `Configuration`:

```
Caused by: java.lang.ClassCastException: class org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection cannot be cast to class org.gradle.api.artifacts.Configuration 
```

**Comment by h0tk3y** [comment]
So, this whole thing is still rather broken for Kotlin indy lambdas when they don't capture something that is not allowed. 

It's just this corner case when we are able to detect a captured `Configuration` in a nested non-serializable `Function1` lambda that works correctly, but we probably don't want it to work that way.
