### ISSUE TITLE
Inconsistent task selector behavior in multi-projects build

### ISSUE THREAD

**Issue by Fiouz** [gradle/gradle#17829]
### Expected Behavior

I expect Gradle to honor the task selector documentation regarding multi-project builds, so that I can execute multiple tasks that share the same name, by only specifying the unqualified task name.

https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#executing_tasks_in_multi_project_builds

> You can also run a task for _all_ subprojects by again using a task _selector_ that consists of the task name only.

https://docs.gradle.org/7.1.1/userguide/intro_multi_project_builds.html#sec:executing_tasks_by_name

> The command `gradle test` will execute the `test` task in any subprojects, relative to the current working directory, that have that task. If you run the command from the root project directory, you’ll run `test` in _api_, _shared_, _services:shared_ and _services:webservice_. If you run the command from the _services_ project directory, you’ll only execute the task in _services:shared_ and _services:webservice_.

The following execution:
```
gradle taskNameThatExistsInMoreThanOneProject
```
... should result in more than 1 task execution (provided that such task exists in more than 1 project).

There should be no special cases that do not follow that documented behavior, in order to provide a consistent user experience.

### Current Behavior

Gradle does not always apply the documented behavior, and even `dependencies` is documented as not following the rule:

https://docs.gradle.org/7.1.1/userguide/viewing_debugging_dependencies.html#sec:listing_dependencies

> The `dependencies` task will only execute on a _single_ project. If you run the task on the root project, it will show dependencies of the root project and not of any subproject

(to be pedantic, I think the author meant "the `dependencies` task _selector_" instead of the _task_ itself, as 1 task is always tied to 1 project only)

https://docs.gradle.org/7.1.1/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution

> Note that in a multi project setup, `dependencies` only is executed on one project, the root one in this case.

Other tasks that are not recursively resolved:

- `help` (not that it matter much, but it is only executed for the root project)

### Context

In the context of [dependency locking](https://docs.gradle.org/7.1.1/userguide/dependency_locking.html), I want to be able to resolve all configurations at once by using the _standard_ [`dependencies` task](https://docs.gradle.org/7.1.1/userguide/viewing_debugging_dependencies.html#sec:listing_dependencies), recursively in all projects.

Wished behavior:
```
gradle --write-locks dependencies
````

I do not want to resort to [implementing a _custom_ task](https://docs.gradle.org/7.1.1/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution) for that purpose:
```
gradle --write-locks customTaskThatPerformConfigurationResolution
```

That suggested approach (custom task) seems side-effect of the `dependencies` task selector not following the general rule regarding task resolution.

Furthermore, that approach is made less reliable by some plugins contributing configurations that are not really resolvable (e.g. Scala #6854 or the Kotlin multiplatform "common libraries").

### Steps to Reproduce 

1. Create multi-projects, say `:` (root project), `:foo` and `:bar`
2. Execute `gradle dependencies`
3. See that it executes `:dependencies`; it does not execute `:foo:dependencies` and `:bar:dependencies`

Alternatively:

1. Read the documentation regarding [task selector](https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#executing_tasks_in_multi_project_builds) / [task execution in a multi-projects build](https://docs.gradle.org/7.1.1/userguide/intro_multi_project_builds.html#sec:executing_tasks_by_name) and learn that you can use `gradle <taskName>` syntax for multiple tasks execution
2. Read [other parts of the documentation](https://docs.gradle.org/7.1.1/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution) that contradict the previously read documentation when it comes to how tasks are resolved, despite following the same syntax

### Your Environment

Gradle 7.1.1

**Comment by Fiouz** [comment]
@mlopatkin, seeing that you removed the _a:bug_ label and added the _a:documentation_ label instead, it seems the Gradle position on the reported behavioral inconsistency is an intended design that will not change.

😕 I was initially hoping for a more streamlined experience where the "special treatment" of reporting task names to be dropped (and documentation updated accordingly), to make it easier for people to reason about what is going to happen (no need to know "special values"), instead of keeping the current "special behavior" with a documentation update only.

**Comment by ljacomet** [comment]
You are correct, there is no plan to remove this concept of tasks that are only executed on the top level project and not any subprojects.
So the _fix_ will indeed be about documenting this better.

**Comment by sschuberth** [comment]
> I was initially hoping for a more streamlined experience where the "special treatment" of reporting task names to be dropped

I can only second that. Even if now documented, the special behavior of tasks like "dependencies" is unexpected and unnatural to most users IMO, and the docs also offer no justification why this special behavior would make sense. If the arguments was that users are likely to only be interested in the dependencies of a single project, they could easily do that by executing ":dependencies" instead.
