### ISSUE TITLE
Way to group dependencies with the same version when using VersionCatalogs

### ISSUE THREAD

**Issue by BugsBunnyBR** [gradle/gradle#17822]
I would like to have a way to specify a group of dependencies in a way that they share the same version, so it would be less verbose than the current way.

### Expected Behavior
If we could have something like this, it would be less verbose.
``` groovy
dependencyResolutionManagement {
    versionCatalogs {
        libs {
            aliasGroup('groovy', '3.0.5') {
                alias('core').to('org.codehaus.groovy', 'groovy')
                alias('json').to('org.codehaus.groovy', 'groovy-json')
                alias('nio').to('org.codehaus.groovy', 'groovy-nio')
           }
         }
    }
}
```

``` groovy
implementation libs.groovy.core
```
### Current Behavior

``` groovy
dependencyResolutionManagement {
    versionCatalogs {
        libs {
            version('groovy', '3.0.5')
            alias('groovy-core').to('org.codehaus.groovy', 'groovy').versionRef('groovy')
            alias('groovy-json').to('org.codehaus.groovy', 'groovy-json').versionRef('groovy')
            alias('groovy-nio').to('org.codehaus.groovy', 'groovy-nio').versionRef('groovy')
         }
    }
}
```
I need to set `versionRef('groovy')` for every dependency.

### Context
Having to declare dozens (or even hundreds) of dependencies and versions in the same file makes it hard to keep a list of "versions" and another for "libraries". Having those lists makes it hard to locale the current version of a dependency. If we can have a way to bring the version closer of the dependencies declaration by some sort of grouping it would reduce the mental workload to manage it.

Thanks

**Comment by ljacomet** [comment]
The `version` method returns a `String` so you can define a local variable from it and then use that inside the `versionRef`.

It is unlikely we will change the DSL the way you request it. While it ends up being a bit more compact, it does so at the cost of masking aliases. That does not seem like a good result.

**Comment by BugsBunnyBR** [comment]
> The `version` method returns a `String` so you can define a local variable from it and then use that inside the `versionRef`.
> 
> It is unlikely we will change the DSL the way you request it. While it ends up being a bit more compact, it does so at the cost of masking aliases. That does not seem like a good result.

Sorry, but I disagree. The current implementation is way too verbose for common a use case. Forcing us to set the reference the `versionRef` for each dependency give us no benefit. Masking aliases? What does that mean? My suggestion would have many benefits for the developers. Easier to read and write with less verbosity and allow grouping of dependencies.

Well, all I did was a suggestion of implementation to exemplify the verbosity problem that I noticed in an API that is experimental. I thought you folks would be more open to to change.

**Comment by ljacomet** [comment]
What I mean by masking alias is that you can read `alias('json')` but need to pay attention that the real alias is `groovy.json` since there is a `aliasGroup('groovy')` somewhere above it.
Also what would the rules around nesting `aliasGroup`?
Should we do one without version?

I understand that API design is complicated and that getting everyone in agreement is tough.

**Comment by BugsBunnyBR** [comment]
> What I mean by masking alias is that you can read `alias('json')` but need to pay attention that the real alias is `groovy.json` since there is a `aliasGroup('groovy')` somewhere above it.
> 
> I understand that API design is complicated and that getting everyone in agreement is tough.

Ok, got your point about masking. Still, I understand that the grouping would be shallow most of the time (not many layers or nesting) and that IDE support could offer auto complete to all `json` declarations as it does with classes that have similar name.


> Also what would the rules around nesting `aliasGroup`?
> Should we do one without version?

I would say that the version is optional and if a `versionRef` is provided by an `alias` inside the group.
If the aliasGroup version is not provided and neither the alias `versionRef`, it should behave as it does today when a version is not provided at all.
