### ISSUE TITLE
Stop gradle build when "gradle detects a problem"

### ISSUE THREAD

**Issue by Fachher** [gradle/gradle#17824]
Hi,

### Expected Behavior

I want to have the ability to break the build if gradle detects a problem. Something like ./gradlew --break-on-problems. As these problems could be serious.

### Current Behavior
Quietly logged and mostly overseen.

```
Execution optimizations have been disabled for task ':foobar:server:checkstyleMain' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Projects/workspace/foobar/server/target/resources/main'. Reason: Task ':foobar:server:checkstyleMain' uses this output of task ':foobar:server:writeGitPropertiesFile' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.1.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

### Context
Incorrect results being produced will be overseen

**Comment by blindpirate** [comment]
You need to clarify what is "problem". If you mean break on any warning output, you can customize logging and abort the build upon any warning logs, or any specific texts. https://docs.gradle.org/current/userguide/logging.html

**Comment by Fachher** [comment]
Whenever gradle logs "Gradle detected a problem with the following", the build should be terminated. I want it to be reliable. Not that the gradle team change the wording and then my logchecker does not work anymore.

**Comment by blindpirate** [comment]
I see, I'm reopening it, but I don't thing it would be implemented in a short term.

**Comment by obecker** [comment]
There is already `--warning-mode fail` that does what is requested.

**Comment by Fachher** [comment]
Build will fail if in case of using deprecated method which will be removed in next version.
