### ISSUE TITLE
Better Error reporting for name mismatch in catalog dependencies

### ISSUE THREAD

**Issue by ccanning** [gradle/gradle#17839]
In my version catalog using lbs.versions.toml, I have:

```
[versions] #library versions

spring-boot = "2.5.3"

[libraries] #each library dependency

sprin-gboot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
```

In my build.gradle.kts, I have 

```
dependencies {
    implementation(platform(libs.spring.boot.dependencies))
}
```

and here is the error:

```
Cause: org/gradle/accessors/dm/LibrariesForLibs$SpringBootLibraryAccessors (wrong name: org/gradle/accessors/dm/LibrariesForLibs$SprinGbootLibraryAccessors)
```

It would be very nice if it alluded to the fact that there is a name mismatch or if any searches related this error to the naming comvention: SprinGbootLibraryAccessors translates into sprin-gboot* in the [libraries] section.

**Comment by octylFractal** [comment]
This no longer fails with an obscure error due to changes in version catalog API, it now produces:
```
Script compilation error:

  Line 11:     implementation(platform(libs.spring.boot.dependencies))
                                            ^ Unresolved reference: spring
```
Which is 100% correct and clear.
