### ISSUE TITLE
TaskProvider serialization support for Configuration cache

### ISSUE THREAD

**Issue by augi** [gradle/gradle#17858]
I'm trying to adapt [Gradle Docker Compose plugin](https://github.com/avast/gradle-docker-compose-plugin/) to the [Configuration cache](https://docs.gradle.org/7.1.1/userguide/configuration_cache.html) feature.

We have an extension that defines _regular_ properties set by users and read by tasks, and also few `TaskProvider` instances that are useful for users, mainly to setup correct dependencies between tasks. Thus used in configuration phase only.

As we reference this extension from our tasks, the Configuration cache fails on error messages like `cannot serialize object of type com.avast.gradle.dockercompose.tasks.ComposeBuild, a subtype of org.gradle.api.Task, as these are not supported with the configuration cache.`

### Expected Behavior
We are able to enable Configuration cache for projects with plugins that expose `TaskProvider` in their extensions.

### Current Behavior
Configuration cache fails on error like `cannot serialize object of type com.avast.gradle.dockercompose.tasks.ComposeBuild, a subtype of org.gradle.api.Task, as these are not supported with the configuration cache.`

**Comment by eskatos** [comment]
A task holding a reference to another task will never be supported with the configuration cache. One way to fix things in the context you described would be to stop referencing your extension from your task and instead wire only the required properties.
