### ISSUE TITLE
Capability resolution isn't always applied as expected

### ISSUE THREAD

**Issue by NielsDoucet** [gradle/gradle#17855]
When applying the [logging-capabilities plugin](https://github.com/ljacomet/logging-capabilities) and enforcing logback, it still allows slf4j-simple to be on the runtime classpath, alongside logback.
Some other module's metadata is preventing the capability resolution to function as expected.

### Expected Behavior

Only logback should be on the runtime classpath, due to the conflict resolution provided by the plugin.
```
$ ./gradlew dependencyInsight --configuration runtimeClasspath --dependency org.slf4j:slf4j-simple
> Task :dependencyInsight
ch.qos.logback:logback-classic:1.2.4
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library
      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]
   Selection reasons:
      - By constraint : dependency was locked to version '1.2.4'
      - By conflict resolution : On capability dev.jacomet.logging:slf4j-impl Logging capabilities plugin selected Slf4J binding
org.slf4j:slf4j-simple:1.7.30 -> ch.qos.logback:logback-classic:1.2.4
\--- org.owasp.antisamy:antisamy:1.6.3
     \--- runtimeClasspath
```

### Current Behavior

Both logback and slf4j-simple are on the runtime classpath.
The selection reason is `Forced By ancestor`, so it appears some other module's metadata is preventing the capability resolution to function as expected.
```
$ ./gradlew dependencyInsight --configuration runtimeClasspath --dependency org.slf4j:slf4j-simple
...
org.slf4j:slf4j-simple:1.7.32
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library
      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 8
   ]
   Selection reasons:
      - By constraint : dependency was locked to version '1.7.32'
      - By constraint : belongs to platform dev.jacomet.logging.align:slf4j:1.7.32
      - Forced
      - By ancestor
...
```

### Context

The capability resolution should solve the problems described in the logging-capabilities' [README](https://github.com/ljacomet/logging-capabilities/#logging-capabilities-gradle-plugin). Due to this bug, we still need to do more cleanup in order to get reliable logging in place by forcefully removing slf4j-simple from the runtime classpath.
```
components.all {
    allVariants {
        withDependencies {
            removeAll { it.name in listOf("slf4j-simple") }
        }
    }
}
```

### Steps to Reproduce 

https://github.com/NielsDoucet/logging-capabilities-reproducer
Note that this reproducer is not complete, but further information is provided in its README.md.

### Your Environment

Gradle version: 6.8.3
logging-capabilities plugin version: 0.9.0
See the reproducer's README.md for a build scan on demand.

**Comment by ljacomet** [comment]
Gradle 7.3 RC1 should be released soon and has a fix that could resolve the issue mentioned here.
Could you test with it and report the result?
