### ISSUE TITLE
Source Dependency for GitHub doesn't work + no recent Documentation

### ISSUE THREAD

**Issue by brainbytes42** [gradle/gradle#17859]
### Expected Behavior
Following this gradle-blog's post introducing [source dependencies](https://blog.gradle.org/introducing-source-dependencies), I tried to include a project from GitHub as a dependency. I need to use the latest commit, not the latest release, so I can't use the published artifact but need the latest snapshot.

I expected to have the latest code from head checked oud and compiled by my project.

### Current Behavior
The dependency won't be resolved, giving this error:
```
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all task dependencies for configuration ':compileClasspath'.
   > Git repository at https://github.com/failsafe-lib/failsafe.git did not contain a project publishing the specified dependency.
```
I tried the same for the library in the blog's example, but this wouldn't resolve as well.

### Context
I need the latest commit from a GitHub repo as dependency. It has no tag, but even the existing tags wouldn't help.

### Steps to Reproduce 
``settings.gradle``:
```
rootProject.name = 'playground'

sourceControl {
    gitRepository(uri("https://github.com/failsafe-lib/failsafe.git")) {
        producesModule("net.jodah:failsafe")
    }
}
```

``build.gradle``
```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

dependencies {
    implementation 'net.jodah:failsafe'
}
```

For the implementation dependency, I tried as well ``'net.jodah:failsafe:failsafe-2.4.1'`` (latest tag), but even that didn't work.

Note that I added ``uri(...)`` for the Repository, which wasn't there in the blog, but it seems necessary now. But without is the same result nontheless.

*I didn't find anny current documentation for this topic. It would be helpful to have this covered in the docs.*

### Your Environment
I could reproduce this with gradle-wrapper v. 6.7 and 7.1, both in a single-project-build and a multi-project-build.

**Comment by mlopatkin** [comment]
The build you're referring to is not a Gradle build but a Maven build. Using Maven builds as a source dependency (or included build) is not supported.
