### ISSUE TITLE
Manifest attributes should accept Provider/Callable

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1786]
A common configuration time pitfall is configuring the JAR manifest with some expensive computation:

```
jar {
  manifest {
    attributes(
        'Class-Path': computeClasspathString(configurations.runtime)
    )
  }
}
```

Unfortunately, our `Manifest` class does not support Provider/Callable as a value. If a user uses a Closure as the value, then the Closure's toString representation ends up in the manifest file instead.

We should make the following work:

```
jar {
  manifest {
    attributes(
        'Class-Path': { computeClasspathString(configurations.runtime) }
    )
  }
}
```

Workaround: Configure the manifest in a `doFirst {}` block while making sure to add `configurations.runtime` as an input to the `jar` task, so changes are still picked up.

**Comment by ljacomet** [comment]
This was done for a `Provider` in Gradle 6.0.
Gradle 6.4 added support for a `Provider` where `isPresent()` returns false.
In that case, the Manifest entry is simply skipped.

However, this does not add the `Provider` source as an input to the task AFAICT.
