### ISSUE TITLE
Provider.map { null } does not drop implicit task dependency

### ISSUE THREAD

**Issue by li-wjohnson** [gradle/gradle#17907]
Gradle 7.1

Example:

```
def t1 = tasks.register("task1")
def t2 = tasks.register("task2") { t ->
    t.dependsOn(t1.map { null })
}
```

Even though `t1.map { null }` clearly returns null, the task dependency is still added: both task1 and task2 are run. I assume this is because `t1.map { <anything> }` has an implicit dependency on `t1`. Is this expected?

**Comment by li-wjohnson** [comment]
This is a contrived example -- I'm trying to have a conditional dependency on task1, based on the return value of some provider. Ideally I'm looking for:
```
!someProvider.isPresent {
  task.dependsOn(otherTask)
}
```
without eagerly evaluating `someProvider`. I had tried 
```t2.dependsOn(t1.map { t -> if (someProvider.isPresent) null else t })```
but that didn't work because of this issue.

**Comment by wolfs** [comment]
@li-wjohnson Thank you for reporting this issue. Can you describe why you want to have the optional dependency on another task? Is there may be some other way to achieve this?
