### ISSUE TITLE
java.io.IOException: The pipe is being closed -

### ISSUE THREAD

**Issue by LongshotTeam** [gradle/gradle#17908]
> Task :processTestResources NO-SOURCE
file or directory 'C:\Users\cdora\Desktop\swm-common-userinterfaceclient-entitlementorderservice\src\test\resources', not found
Skipping task ':processTestResources' as it has no source files and no previous output files.
:processTestResources (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:testClasses (Thread[Execution worker for ':',5,main]) started.

> Task :testClasses
Skipping task ':testClasses' as it has no actions.
:testClasses (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
:test (Thread[Execution worker for ':',5,main]) started.
Could not write standard input to Gradle Test Executor 16.
java.io.IOException: The pipe is being closed
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
        at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)

> Task :test FAILED
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  Task has failed previously.
Running tests on classpath
Starting process 'Gradle Test Executor 16'. Working directory: C:\Users\cdora\Desktop\swm-common-userinterfaceclient-entitlementorderservice Command: C:\Program Files\Java\jdk-11.0.8\bin\java.exe -Dawt.toolkit=sun.awt.windows.WToolkit -Dfile.separator=\ -Djava.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment -Djava.awt.printerjob=sun.awt.windows.WPrinterJob -Djava.class.path=D:\gradle-7.0.2\lib\gradle-launcher-7.0.2.jar -Djava.class.version=55.0 -Djava.home=C:\Program Files\Java\jdk-11.0.8 -Djava.library.path=C:\Program Files\Java\jdk-11.0.8\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/Java/jdk-11.0.8/bin/server;C:/Program Files/Java/jdk-11.0.8/bin;C:\Python39\Scripts\;C:\Python39\;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk-11.0.8\bin;C:\cassandra\apache-cassandra-3.11.3\bin;C:\Program Files\Perforce;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;D:\FNO-Installer\FlexNet Operations\components\wildfly\bin;D:\FNO-Installer\FlexNet Operations\components\ant\bin;D:\FNO-Installer\FlexNet Operations\components\jvm\bin;C:\Program Files (x86)\scala\bin;C:\zookeeper-3.4.12\bin;D:\Redis3.2.100;C:\Program Files\MongoDB\Server\4.0\bin;D:\JC\TEMP\sqljdbc4.jar;C:\Ruby24-x64\bin;D:\gradle-7.0.2\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\Python27;D:\Terraform;C:\apache-maven-3.6.3\bin;C:\kubectl;C:\ProgramData\chocolatey\bin;C:\Go\bin;C:\Program Files (x86)\GnuWin32\bin;C:\MinGW\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Users\cdora\go\bin;C:\Program Files (x86)\Yarn\bin\;C:\nodejs\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;";C:\Users\cdora\AppData\Local\GitHubDesktop\bin;C:\Users\cdora\AppData\Local\Microsoft\WindowsApps;D:\Terraform;C:\Users\cdora\go\bin;C:\Users\cdora\AppData\Local\Programs\Microsoft VS Code\bin;C:\Python39\Scripts;C:\Program Files\Oracle\VirtualBox;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;C:\Users\cdora\AppData\Roaming\npm;C:\Users\cdora\AppData\Local\Programs\Fiddler;C:\Users\cdora\AppData\Local\Yarn\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.3\bin;;C:\WINDOWS\system32;;. -Djava.runtime.name=Java(TM) SE Runtime Environment -Djava.runtime.version=11.0.8+10-LTS -Djava.specification.name=Java Platform API Specification -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=11 -Djava.vendor=Oracle Corporation -Djava.vendor.url=https://openjdk.java.net/ -Djava.vendor.url.bug=https://bugreport.java.com/bugreport/ -Djava.vendor.version=18.9 -Djava.version=11.0.8 -Djava.version.date=2020-07-14 -Djava.vm.compressedOopsMode=32-bit -Djava.vm.info=mixed mode -Djava.vm.name=Java HotSpot(TM) 64-Bit Server VM -Djava.vm.specification.name=Java Virtual Machine Specification -Djava.vm.specification.vendor=Oracle Corporation -Djava.vm.specification.version=11 -Djava.vm.vendor=Oracle Corporation -Djava.vm.version=11.0.8+10-LTS -Djdk.debug=release -Dkotlin.daemon.jvm.options=--illegal-access=permit -Dlibrary.jansi.path=C:\Users\cdora\.gradle\native\jansi\1.18\windows64 -Dline.separator=
 -Dorg.gradle.appname=gradle -Dorg.gradle.internal.worker.tmpdir=C:\Users\cdora\Desktop\swm-common-userinterfaceclient-entitlementorderservice\build\tmp\test\work -Dorg.gradle.native=false -Dos.arch=amd64 -Dos.name=Windows 10 -Dos.version=10.0 -Dpath.separator=; -Dsun.arch.data.model=64 -Dsun.boot.library.path=C:\Program Files\Java\jdk-11.0.8\bin -Dsun.cpu.endian=little -Dsun.cpu.isalist=amd64 -Dsun.desktop=windows -Dsun.io.unicode.encoding=UnicodeLittle -Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.0.2 -Dsun.java.launcher=SUN_STANDARD -Dsun.jnu.encoding=Cp1252 -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Dsun.os.patch.level -Duser.dir=C:\Users\cdora\Desktop\swm-common-userinterfaceclient-entitlementorderservice -Duser.home=C:\Users\cdora -Duser.name=CDora -Duser.script -Duser.timezone -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.5.jar_6a2df60c47de373ea127d14406367999/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false @C:\Users\cdora\.gradle\.tmp\gradle-worker-classpath6001814065395378291txt -Xmx512m -Dfile.encoding=Cp1252 -Djava.io.tmpdir=C:\Users\cdora\AppData\Local\Temp\ -Duser.country=US -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 16'
Successfully started process 'Gradle Test Executor 16'
Error: Could not find or load main class VS
Caused by: java.lang.ClassNotFoundException: VS

Junit Test result: SUCCESS
Junit Test summary: 0 tests, 0 succeeded, 0 failed, 0 skipped
:test (Thread[Execution worker for ':',5,main]) completed. Took 0.561 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 16' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 8s
5 actionable tasks: 5 executed
Watched directory hierarchies: [D:\JC\JCTemp\swm-common-userinterfaceclient-entitlementorderservice, C:\Users\cdora\Desktop\swm-common-userinterfaceclient-entitlementorderservice]

**Comment by LongshotTeam** [comment]
![image](https://user-images.githubusercontent.com/40361258/127740609-d1b988df-c723-4303-8850-5dcdf06bedb8.png)

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

The stack trace looks similar to the #15895 though.

**Comment by mlopatkin** [comment]
>The stack trace looks similar to the #15895 though.

Actually, disregard that. This is the symptom of the worker process dying unexpectedly. The real issue is likely
```
Error: Could not find or load main class VS
Caused by: java.lang.ClassNotFoundException: VS
```

It is strange to have such issue in the test run so it is impossible to proceed without a reproducer.

**Comment by atuljadon** [comment]
Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain
Caused by: java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain
Could not write standard input to Gradle Worker Daemon 1.
java.io.IOException: The pipe is being closed
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle:compileGroovy'.
> Failed to run Gradle Worker Daemon
   > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Error: Gradle task assembleDebug failed with exit code 1

I am facing it in simple scratch app . Please respond asap .
