### ISSUE TITLE
(no error message) when trying to parse a pom file.

### ISSUE THREAD

**Issue by dmodoomsirius** [gradle/gradle#1791]
### Expected Behavior

Ability to parse a pom file is failing https://gist.github.com/dmodoomsirius/d8b5f0a324926607f38b822b136c7a25

### Current Behavior

 Fails to parse pom with java.lang.NullPointerException (no error message).

### Context

I am unable to compile a project that is down stream from the project with the pom file. @AbrarSyed has attempted to help me fix this issue via a irc channel but we have had no luck. 

### Steps to Reproduce (for bugs)

add the dependency to the pom. 
pom is linked in the gist above. as well as the full gradle log.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/u77lymgvclumu
https://github.com/MinecraftForge/ForgeGradle

**Comment by bmuschko** [comment]
There are two potential issues I see with the published POM.

1. I am not sure if `<version>[1.7.10]1.0.2-160-dev</version>` is even a valid version.
2. I am not sure if the following exclusion is properly parsed and handled by Gradle.

```
<exclusions>
    <exclusion>
        <artifactId>*</artifactId>
        <groupId>*</groupId>
    </exclusion>
</exclusions>
```

Do you feel strongly about getting it fixed and would like to investigate?

**Comment by dmodoomsirius** [comment]
I would like to get this fixed so i am able to limit the amount of things i have in my gradle scripts repo and my projects.

**Comment by dmodoomsirius** [comment]
I am willing to fix this issue.

**Comment by jjohannes** [comment]
This report is for an issue in Gradle 2.14.1

The issue that the real error is hidden by an NPE has been fixed in https://github.com/gradle/gradle/commit/b1dfb2c7188f8178d4c436f467ea9e88a7975e69 already.

Parsing the linked pom still fails though, as it is missing `groupId`s in some dependencies.
