### ISSUE TITLE
a "error" about build-scan buildScanPublished interface

### ISSUE THREAD

**Issue by JadeWu233** [gradle/gradle#17912]
Hi,First of all thanks for your gradle tool.

When I was using buildscan, I wanted to access the website to get information immediately after publishing, so I called back the buildScanPublished interface. And I set UploadingBackground to false.
The documentation of buildScanPublished stated that the upload of the build information should be completed at this time, but my visit has been in the Uploading state.I think published means that the upload has been completed at this time, not that it is still uploading.

The IDE I use is AndroidStudio，buildScan's version is 3.6.3.

I hope you can give me a reply or a solution to this matter. Thank you very much. I would be very grateful if you can get a reply.

**Comment by ldaley** [comment]
Hello @JadeWu233. 

The documentation is outdated and incorrect. There is currently no way to be notified when the the uploading has completed from the plugin.

You will need to poll/retry the link given until the upload has completed.
