### ISSUE TITLE
Path sensitivity `NONE` in incremental task causes same file to be added then removed

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17916]
If you have an incremental task with an input with path sensitivity `NONE` and run that task incrementally, you get two changes in `inputChanges.getFileChanges(inputWithoutPathSensitivity).forEach { ... }`, first an `ADDED` for the changed file, then a `REMOVED` for the same file.

This can of course be appropriate, as I defined I'm not interested in the file path, just in the content.
But it nevertheless confused me majorly that I first got an `ADDED` then a `REMOVED` for the same file.
I would at least have expected to first get `REMOVED`, then `ADDED`.

Or maybe actually even a `MODIFIED`.
Even if I do not have a dependency on the file name, but only on the content, it might be more appropriate to get a `MODIFIED` change, as that is what happened.

At the very least the behavior in the `NONE` case should imho be more clearly documented as I didn't spontaneously find some description of this behavior.

### Steps to Reproduce 
- Have an incremental task with a task input with path sensitivity `NONE`
- Run the task so that all inputs are processed successfully
- Modify one of the input files
- Rerun the task

### Your Environment
Gradle 7.1.1

**Comment by wolfs** [comment]
Hey, thank you for reporting! Could you provide the use case for having path sensitivity NONE for a collection of inputs on an incremental task? For me it seems strange to have path sensitivity NONE for incremental tasks or for collections of input files in general.

**Comment by Vampire** [comment]
In my case I have a set of XML files that I validate for conforming schema and some custom rules.
I'm absolutely uninterested in the file names, I only validate the content of those files.
So I have
```kt
   @get:SkipWhenEmpty
   @get:InputFiles
   @get:PathSensitive(NONE)
   abstract val myInputFiles: ConfigurableFileCollection
```
And in the task action I then have
```kt
inputChanges.getFileChanges(myInputFiles).forEach { /* validate the file content */ }
```

**Comment by wolfs** [comment]
> I'm absolutely uninterested in the file names, I only validate the content of those files.

If you only validate the contents of the XML files, why do you listen to `REMOVED` events at all? For your incremental task, it should be enough to validate the added and modified files, right?

Another thing to note: I suppose if the validation fails, you'd print out which file had the error. So I suppose you'd at least care about the file name in the validation.

**Comment by Vampire** [comment]
> If you only validate the contents of the XML files, why do you listen to REMOVED events at all? For your incremental task, it should be enough to validate the added and modified files, right?

Yes, that's what I do in that specific task.
Nevertheless I found it majorly confusing that I don't get a `MODIFIED` or at least a `REMOVED` followed by an `ADDED` but instead got an `ADDED` followed by a `REMOVED`, and that there is no documentation about the behaviour, just as I described in the original issue description. :-)

> Another thing to note: I suppose if the validation fails, you'd print out which file had the error.

Of course.

> So I suppose you'd at least care about the file name in the validation.

Probably a matter of definition / point of view.
The file name is not an input.
If the same content is in a different file, the task can stay up to date as it will still be valid content.
Just if vaidation fails, the name is used as part of the output.
And actually the task even fails execution if a violation was found.

**Comment by lptr** [comment]
For some _thing_ to be `MODIFIED` there needs to exist some sort of identity to go with that thing that Gradle can use to connect the past and present state of the thing. With path sensitivity set to `NONE` Gradle doesn't have anything to identify individual files by, and thus it can't produce a `MODIFIED` event. We have similar behavior for classpath inputs.

I've added https://github.com/gradle/gradle/pull/23462 to clarify this in the docs.

**Comment by Vampire** [comment]
I fully get, that we will not get a `MODIFIED`.
But what about at least getting `REMOVED`s before `ADDED`s? :-)
In my concrete use-case it doesn't matter as I just validate the added or modified ones and don't care about the removed ones.
But it would feel more expected (at least to me) in that order. :-)
