### ISSUE TITLE
Disallow usages locale-dependent toLowerCase() and toUpperCase() calls in the codebase 

### ISSUE THREAD

**Issue by donat** [gradle/gradle#17926]
Gradle had several regressions because the source code contains several calls to `String.toLowerCase()` and `String.toUpperCase()` which is locale-specific. An Archunit-based approach was implemented in #17657, but there's an ongoing debate whether that's the right approach. A couple of ways we can go about it:
- Reopen and merge #17657
- Set up IntelliJ inspection rules
- Introduce Spotbugs (and other tools for Kotlin sources)

**Comment by ov7a** [comment]
This is essentially fixed with the introduction of the ErrorProne.
