### ISSUE TITLE
Have a conditional version of includeBuild.

### ISSUE THREAD

**Issue by ysb33r** [gradle/gradle#1792]
Using `includeBuild` in setting.gradle is really useful, but I am seeing tha pattern of a conditional include becoming more wide-spread. I would like to suggest

### Expected Behavior
```groovy
includeBuildIfExists '../other-project'
```

A more generic version could be

```groovy
includeBuildIf '../other-project', { 
  /* some condition * 
}
```
But at this point I think the initial suggestion to replace the file check is what is most important.

### Current Behavior
```groovy
if( file('../other-project').exists) {
  includeBuild '../other-project'
}
```

### Context

There are many cases where people work on multiple projects together, but some of their peers of open-source colleagues might not work on a subset. The pattern for conditional includes in composite builds is quite useful.

One particular one that springs to mind is the very complex Ceylon build which I have been helping to migrate to Gradle. 

I have actually used the pattern myself in quite a number of other projects too.

**Comment by oehme** [comment]
I don't see why we would add another overload for something that is so simple to do with an if-statement or for-loop.

**Comment by ysb33r** [comment]
Readability: i'ts looks more DSL and less like code.

**Comment by hameno** [comment]
Yes, please. Also add something to prevent nested included builds (which currently do not work)

**Comment by oehme** [comment]
Closing for the reason given before - the necessary APIs are there and if someone wants to provide a stronger convention (e.g. include only if exists and not nested), this can be done with a plugin.
