### ISSUE TITLE
exclusiveContent looks that are not applied

### ISSUE THREAD

**Issue by pjgg** [gradle/gradle#17942]
Based on [Gradle 7.0 doc](https://docs.gradle.org/current/userguide/dependency_management.html#declaring_content_exclusively_found_in_one_repository) looks that now is possible declare an exclusive repository content, for example:

```
repositories {

    // This repository will _not_ be searched for artifacts in io.quarkus
    // despite being declared first
    mavenCentral()

    exclusiveContent {
         forRepository {
            jcenter ()
        }
        filter {
            // this repository *only* contains artifacts with group "io.quarkus"
            includeGroup "io.quarkus"
        }
    }
}

```

However, I still get the following log trace:

```
Attempting to resolve component for io.quarkus:quarkus-resteasy-jackson:2.1.0.Final using repositories [MavenRepo, BintrayJCenter]
```

Please find on this link a reproducer: https://github.com/pjgg/gradle-exclusiveContent-reproducer
You can run the following command: `./gradlew quarkusDev --debug | grep "io.quarkus:quarkus-resteasy-jackson"`

### Expected Behavior
Log trace: 
```
Attempting to resolve component for io.quarkus:quarkus-resteasy-jackson:2.1.0.Final using repositories [BintrayJCenter]
```

**Comment by mlopatkin** [comment]
I've checked and it is just logs being slightly misleading - the log entry mentions all available repositories; the filtering is applied later.

**Comment by rsvoboda** [comment]
It's a bit misleading, maybe there should be another log entry to say that filtering was applied.
