### ISSUE TITLE
Unexpected behaviour of java toolchain detection

### ISSUE THREAD

**Issue by iNikem** [gradle/gradle#17940]
I have installed AdoptOpenJDK Java 16 with J9 VM. Gradle can detect it correctly:

```
./gradlew -q javaToolchains --no-build-cache -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.paths=/Users/inikem/.sdkman/candidates/java/16.0.1.j9-adpt

 + Options
     | Auto-detection:     Disabled
     | Auto-download:      Disabled

 + AdoptOpenJDK 16.0.1+9
     | Location:           /Users/inikem/.sdkman/candidates/java/16.0.1.j9-adpt
     | Language Version:   16
     | Vendor:             AdoptOpenJDK
     | Is JDK:             true
     | Detected by:        system property 'org.gradle.java.installations.paths'


```
For demonstration purpose I disable auto-detect and download.

In my Gradle build script I specified that I want a java toolchain for java16, without specifying vendor nor implementation. Reading [Gradle manual](https://docs.gradle.org/current/userguide/toolchains.html#selecting_toolchains_by_their_virtual_machine_implementation) I assumed that this means "give me java 16 from any vendor with any implementation". Instead I get this:

```
./gradlew test -PtestJavaVersion=16 --no-build-cache -Porg.gradle.java.installations.auto-download=false -Porg.gradle.java.installations.auto-detect=false -Porg.gradle.java.installations.paths=/Users/inikem/.sdkman/candidates/java/16.0.1.j9-adpt

> Configure project :benchmark
Inferred project: opentelemetry-java-instrumentation, version: 1.5.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':instrumentation:grpc-1.6:testing'.
> Failed to query the value of task ':instrumentation:grpc-1.6:testing:test' property 'javaLauncher'.
   > No compatible toolchains found for request filter: {languageVersion=16, vendor=any, implementation=vendor-specific} (auto-detect false, auto-download false)
```
"Failed to query the value of task" is from my debugging println.

As soon as I specify `implementation.set(JvmImplementation.J9)` this problem goes away. So it seems that Gradle actually works not like 

> give me java 16 from any vendor with any implementation

but more like

> give me java 16 from any vendor with that vendor's default implementation

which contradicts the documentation:

> VENDOR_SPECIFIC
> Acts as a placeholder and matches any implementation from any vendor (e.g. hotspot, zulu, …​)

**Comment by anuraaga** [comment]
Just for some context / 2 cents, if Gradle behaved as per the manual and automagically matched "any implementation", then we may have accidentally run a test intended for J9 with Hotspot in our build. So the greater determinism of the current behavior seems good to me and I think updating the docs would be safer than changing the behavior.

**Comment by mlopatkin** [comment]
Currently, you have to specify J9 as an implementation explicitly in the toolchain spec to be able to use it. @ljacomet, could you please shed some light on why we decided to go this way?

>automagically matched "any implementation", then we may have accidentally run a test intended for J9 with Hotspot in our build. 
@anuraaga isn't it vice versa? If you have J9-specific tests, you should have an appropriate implementation selector in the toolchain spec for them. OTOH, if Gradle changes its behavior as described then tests that have no specific implementation specified may end up running in J9 as well.

**Comment by anuraaga** [comment]
@mlopatkin Ah sorry, I guess it's a bit tricky. In our build, we have tests for both Java 8 and 15 running on GitHub Actions. GitHub Actions runner includes Java 8 by default but not Java 15. So we updated the build configuration such that we ended up with

- Java 8 GitHub runner, including Java 8 Hotspot that is the default of the actions runner and Java 8 J9 which we downloaded explicitly
- Java 15 GitHub runner, only with Java 15 J9 since the runner doesn't include 15 by default

In this situation, the Java 8 build passed (we had no assertion that the test is running on J9 explicitly) but the Java 15 build failed since it could not find 15 Hotspot which it was looking for. I could imagine us merging without noticing this if Java 15 automatically used the J9 we downloaded.

**Comment by ljacomet** [comment]
The reason we went with the current behavior is that most vendors only effectively have one implementation.
And for the few (the one?) that have more, it is usually an explicit decision to go with the non standard one. Based on that it seemed that sticking with the default implementation was a safe choice while allowing users to opt into a different one when / if needed.

I believe the documentation should be updated indeed to say something like:
> VENDOR_SPECIFIC
> Acts as a placeholder and matches the default implementation from any vendor (e.g. hotspot, zulu, …​)

**Comment by Fiouz** [comment]
Unfortunately, the current (7.4.2) behavior makes builds that only care about the Java version (`languageVersion.set(JavaLanguageVersion.of(XX))` without `implementation.set(JvmImplementation.J9)`) less portable:
* Environments with access to a matching HotSpot VM will happily build
* Environments with only access to a J9 VM will not be able to build, hence forcing affected users to modify the source code of the build (unless I missed a way to change that behavior from a Gradle property), which may break workflows (e.g. dirty Git working directory)

**Comment by jbartok** [comment]
As of Gradle `7.6` `JvmImplementation.VENDOR_SPECIFIC` matches anything, not just the "default implementation" of the vendor. See [here](https://github.com/gradle/gradle/blob/daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainMatcher.java#L56).
