### ISSUE TITLE
`kotlinx` function for adding plugins and dependencies

### ISSUE THREAD

**Issue by CommanderTvis** [gradle/gradle#17956]
### Expected Behavior
 Add functions `kotlinx` to add dependencies in group `org.jetbrains.kotlinx` to the `kotlin-dsl` plugin.

Possible use:

1. Adding dependencies by https://github.com/Kotlin
```kotlin
dependencies {
  implementation(kotlinx("coroutines-core", "1.5.1"))
}
```
2. Adding plugins by https://github.com/Kotlin
```kotlin
plugins {
  kotlinx("benchmark") version "0.3.1"
}
```

### Current Behavior

Dependencies are added as usual:
1. Adding dependencies by https://github.com/Kotlin
```kotlin
dependencies {
  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1")
}
```
2. Adding plugins by https://github.com/Kotlin
```kotlin
plugins {
  id("org.jetbrains.kotlinx.benchmark") version "0.3.1"
}
```

**Comment by gildor** [comment]
Because stable versions catalog feature is coming, and will be recommended solution for dependency declarations, those shortcuts become bad practice and do not add any value

Also it will be inconsistent with kotlin() shortcut, which allows omit dependency version, but it cannot be done for kotlinx

**Comment by CommanderTvis** [comment]
> Because stable versions catalog feature is coming, and will be recommended solution for dependency declarations, those shortcuts become bad practice and do not add any value
> 
> Also it will be inconsistent with kotlin() shortcut, which allows omit dependency version, but it cannot be done for kotlinx

Version catalogs don't cover `plugins` use case, do they?

**Comment by gildor** [comment]
It does in Gradle 7.2: https://docs.gradle.org/7.2-rc-2/release-notes.html

**Comment by CommanderTvis** [comment]
> It does in Gradle 7.2: https://docs.gradle.org/7.2-rc-2/release-notes.html

Wow, then I'm not personally interested in these functions.
