### ISSUE TITLE
Add Single Page release notes

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#17960]
The current release notes (https://docs.gradle.org/current/release-notes.html) are super detailed and very welcome to check what changed in a particular version but it's much more complicated to lookup a version where a certain feature or behaviour change was introduced.

It would be nice to have a one-page release notes document where we could search for keywords without going back and forth between versions like there is the [single-page doc](https://docs.gradle.org/current/userguide/userguide_single.html).

**Comment by ov7a** [comment]
Sorry for the late reply.

This feature request is in the backlog of the relevant team and is prioritized by them.
