### ISSUE TITLE
Support TestReport stdout/stderr modification and filtering

### ISSUE THREAD

**Issue by carterkozak** [gradle/gradle#17966]
I have a large set of services I'm testing which are built to produce structured logging (currently JSON, however the format itself isn't terribly relevant) which is fantastic for computers, but substantially less so for humans debugging test failures.
This means the "Standard Output" and "Standard Error" tabs in the generated html report aren't useful to humans unless they copy data elsewhere, and run another tool on the results.

### Expected Behavior
I'd like a way to transform standard stream data from test reports prior to generating html/xml/etc. Currently the `AbstractTestTask`/`Test` tasks don't allow for custom `TestReporter` implementations, and the `TestReporter` itself lives within `org.gradle.api.internal`. I can hack my way into forcing it to work via the `VisibleForTesting` `setTestReporter` method, but that's not sustainable.

### Current Behavior
No way to format logging in my stdout or provide a custom report implementation.
While support for custom reports would be fantastic, I'd love to leverage the existing high-quality html reporter and simply modify the stdout/stderr data for human readability.

### Context
The obvious alternative is to configure tests to write logs in a human-readable format, however this service is not built to allow logging configuration because that introduces risk that test-only options will be enabled at runtime.

I'd really appreciate your feedback on this idea, and any alternative suggestions you may be able to provide. Thanks!

**Comment by donat** [comment]
You should be able to configure all `Test` tasks to:
- suppress stdout and stderr with `testLogging.showStandardStreams = true`
- capture stdout and stderr with `onOutput(Closure)`
- process captured output at the end of the test execution.

I can imagine this being implemented in a plugin. Let me know what you think.

**Comment by donat** [comment]
Closing as inactive.
