### ISSUE TITLE
Provide a way to use plugin definition from version catalog without version

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17968]
If you apply a plugin to root project, it is part of the class path.
If you then also apply it to a subproject, it must not contain a version definition or Gradle errors out.
Same if you have a plugin as dependency in `buildSrc` and then want to use that plugin in the main build.
Currently (Gradle 7.2-rc-2) this is not really well supported with version catalogs.

- you cannot define a plugin without version in the version catalog
- you cannot set the version to `null` manually

Things that would be nice if supported and would help here:
- Being able to define a plugin without version in the version catalog like
  ```
  [plugins]
  kotlin-withoutVersion = { id = "org.jetbrains.kotlin.jvm" }
  ```
  so that you can use it like `plugins { alias(libs.plugins.kotlin.withoutVersion) }` if the plugin somehow already landed in the class path, like for example having it as dependency in `buildSrc`.
- Being able to unset a version for a plugin accessor for example like
  `plugins { alias(libs.plugins.kotlin) version null }` or
  `plugins { alias(libs.plugins.kotlin) withoutVersion() }` or
  `plugins { alias(libs.plugins.kotlin.withoutVersion()) }` or

**Dirty hack-around for Kotlin DSL**:
in the root build script
```kts
alias(libs.plugins.kotlin)
```
and in the subproject build script
```kts
alias(libs.plugins.kotlin).apply {
    javaClass.getDeclaredField("version").apply { isAccessible = true }.set(this, null)
}
```
In Groovy DSL I didn't find a hack-around, as the AST transformation validates that only `id` or `alias` is done on top-level and that only `apply` or `version` are called on the `PluginDependencySpec`.

**Comment by kenshin171** [comment]
for kotlin DSL this is what (hack) i did
```
plugins {
    id(libs.plugins.kotlin.get().pluginId)
}
```

**Comment by Vampire** [comment]
Ah, that's much better of course, and should also work with Groovy DSL, thanks.

But I'm keeping this open for the consideration to be able to declare without version in the catalog right away.

**Comment by utybo** [comment]
The workaround does not seem to work with the Groovy DSL. For example, with this `libs.versions.toml` file:

```toml
[versions]
kotlin = "1.5.30"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
```

and the following plugins block:

```groovy
plugins {
    id(libs.plugins.kotlin.get().getPluginId())
}
```

I get the following error:

```
* Exception is:
org.gradle.groovy.scripts.ScriptCompilationException: Could not compile build file '[snip]\build.gradle'.
    [huge stack trace removed]
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
build file '[snip]\build.gradle': 2: argument list must be exactly 1 literal String or String with property replacement

See https://docs.gradle.org/7.2/userguide/plugins.html#sec:plugins_block for information on the plugins {} block

 @ line 2, column 5.
       id(libs.plugins.kotlin.get().getPluginId())
       ^
```

It seems that anything other than a literal string or a literal string with interpolation from project properties is not accepted here... This makes plugins in version catalogs useless for multi-module projects, which is a shame :(

**Comment by octylFractal** [comment]
Will be partially fixed by #19015, another PR will be made for specifying without versions in the catalog, and this issue shall be left open until then.

**Comment by marvk** [comment]
Just as an FYI, currently the error message suggests that `withoutVersion` already exists on `PluginAliasBuilder`:

```
Possible solutions:
  1. Call `.version()` to give the alias a version.
  2. Call `.withoutVersion()` to explicitly declare that the alias should not have a version.
```

**Comment by octylFractal** [comment]
Yes, but IIRC there's no way to do it in TOML, that's what my comment / linked issue was about.

**Comment by JavierSegoviaCordoba** [comment]
Is it planned to still allow declaring plugins without versions? I am still getting issues with precompiled plugins in a `build-src` included build.

**Comment by Vampire** [comment]
Just leave out the version in the toml, or use `withoutVersion()` in the DSL

**Comment by JavierSegoviaCordoba** [comment]
@Vampire I am getting `plugin version '' is invalid: cannot be null or empty` if I remove the version and I only have the `id`.

`withoutVersion()` doesn't exist.

I am on Gradle 7.5

**Comment by JavierSegoviaCordoba** [comment]
I can't do the second, it fails because it says there is an unknown version on the classpath.

I am doing the first one, but it is annoying, to be honest, I am going to try the third one, thank you!

**Comment by Vampire** [comment]
Ah, no, I mixed up things again.
Even in the settings DSL it only works for libs, not for plugins, sorry.

**Comment by Vampire** [comment]
If the second fails, then because you somehow get the plugin version in using an unsupported way - in terms of that feature.
You could potentially change that.

**Comment by JavierSegoviaCordoba** [comment]
How? I am creating some precompiled plugins in an included build that is not `buildSrc`. But I am not adding them to the classpath, I guess this is being done automatically, but not sure how to avoid that.

The third doesn't work as you said, it only works for libraries.

**Comment by remcomokveld** [comment]
How do y'all use `withoutVersion()`? I'm getting this error
> Could not find method withoutVersion() for arguments [] on object of type org.gradle.api.internal.catalog.DefaultVersionCatalogBuilder$DefaultPluginAliasBuilder.

Looking at the [source](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java) the method exists for `DefaultLibraryAliasBuilder` but not for `DefaultPluginAliasBuilder`

**Comment by Vampire** [comment]
We don't

**Comment by remcomokveld** [comment]
I thought that's what you said you were doing here? https://github.com/gradle/gradle/issues/17968#issuecomment-1189078037

**Comment by Vampire** [comment]
Read on, two comments below that one for example. ;-)

**Comment by Odaym** [comment]
version catalogs is a disaster

**Comment by unshare** [comment]
A proposed fix: #27200

**Comment by afganhalbana** [comment]
until the MR from @unshare got merged, to make it clear, the work around right know that is working from me based on @Vampire`s explanation

`libs.versions.toml`
```
[versions]
jacoco = "_"

[plugins]
jacoco = { id = "jacoco", version.ref = "jacoco" }
```

`build.gradle`
```
plugins {
    libs.plugins.jacoco.get().pluginId
}
```

**Comment by viluon** [comment]
Has this functionality regressed? I'm getting
```
> Invalid catalog definition:
    - Problem: In version catalog libs, dependency alias builder 'foo.bar' was not finished.
      
      Reason: A version was not set or explicitly declared as not wanted.
      
      Possible solutions:
        1. Call `.version()` to give the alias a version.
        2. Call `.withoutVersion()` to explicitly declare that the alias should not have a version.
      
      For more information, please refer to https://docs.gradle.org/8.11/userguide/version_catalog_problems.html#alias_not_finished in the Gradle documentation.
```
but `.withoutVersion` doesn't exist for plugins.

**Comment by Vampire** [comment]
I'd say that might be two new issues that you should report.
1. `plugin("foo.baz", "foo.baz")` should not suggest adding `withoutVersion()` if it does not exist and should imho also not talk about "dependency alias builder" but "plugin alias builder"
2. A `withoutVersion()` should probably be added to the settings script API. Currently you can work-around it using `plugin("foo.baz", "foo.baz").version {}`.
