### ISSUE TITLE
Documentation for 'TestLogging.exceptionFormat' is incomplete

### ISSUE THREAD

**Issue by transentia** [gradle/gradle#17970]
This is a Trivial-ish documentation issue.

### Current Behavior
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.logging.TestLogging.html#org.gradle.api.tasks.testing.logging.TestLogging:exceptionFormat

```
TestExceptionFormat exceptionFormat
The format to be used for logging test exceptions. Only relevant if showStackTraces is true.
```

My build.gradle has:

```
tasks.withType(Test) {
    testLogging {

        // set options for log level LIFECYCLE; want them to show on console
        events TestLogEvent.STANDARD_OUT,
                TestLogEvent.FAILED
        // doco says: "Only relevant if showStackTraces is true." but actually also relevant here
        exceptionFormat "full"
    }
}
```

I see that exceptionFormat STILL affects what is shown, even though I am not specifying 'showStackTraces' anywhere.

I GUESS this means that 'showStackTraces' defaults to true(?) but this isn't specified anywhere I can see...maybe the doco should note default values in such situations?

**Comment by Shawlaw** [comment]
Yes, the default value of `showStackTraces` is true in the class `DefaultTestLogging`, you can see it [here](https://github.com/gradle/gradle/blob/d5a5beb36ff72629bc563da2c43345288be16ffe/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/logging/DefaultTestLogging.java#L37).
