### ISSUE TITLE
File watching not detecting changed files - Docker running Windows 2019 server

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#17979]
Android Studio CI runs Gradle performance tests on Docker containers with Windows 2019 server. The docker image used is `mcr.microsoft.com/windows/servercore:ltsc2019`.

After updating to Gradle `7.2.-rc1` tests for incremental builds started failing as the changed files were not detected, causing tasks to be up-to-date (when they should run). Disabling file watching with `org.gradle.vfs.watch=false` fixed the issue.

I've attached debug log which contains 2 builds. The first one is a clean build after which a source file is modified (I've verified the file is correctly written to disk). Second build is runs but it is fully up to date, causing it to fail with `package or bundle task was unexpectedly skipped for a non-noop build.` (this is our own check to make sure the build actually runs).

Log: [test (2) (1).log](https://github.com/gradle/gradle/files/6954738/test.2.1.log)
Gradle version: 7.2-rc1

**Comment by donat** [comment]
Gradle 7.2-rc-2 contains some changes that might fix your use-case: https://github.com/gradle/gradle/pull/17922
Could you check your build with that version?

**Comment by gavra0** [comment]
Once we upgrade to 7.2-rc-2 we can try to re-enable file watching in those tests. However, after talking with Lorant, I'm pretty confident that these fixes do not work for us, as we modify a single source file in-place.

**Comment by donat** [comment]
@gradle/execution please take a look

**Comment by lptr** [comment]
There's no specific fix in `7.2-rc-2`. I'm on this.

**Comment by lptr** [comment]
I tried to reproduced this, and started an instance via:

```powershell
docker run --it mcr.microsoft.com/windows/servercore:ltsc2019
```

Then I cloned `https://github.com/gradle/native-platform`, bumped it to use `7.2-rc-2` and ran `assemble` then changed a file using:

```powershell
echo "// Testing" >> FileEvents.java
```

The event has been properly triggered:

```log
2021-08-12T14:57:54.668+0200 [DEBUG] [org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem] Handling VFS change
MODIFIED C:\Users\ContainerAdministrator\Temp\issue-test\native-platform\file-events\src\main\java\net\rubygrapefruit\pl
atform\file\FileEvents.java
```

Rebuilding indeed caused the changes to be detectd:

```text
> Task :file-events:compileJava FAILED
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
C:\Users\ContainerAdministrator\Temp\issue-test\native-platform\file-events\src\main\java\net\rubygrapefruit\platform\fi
le\FileEvents.java:111: error: class, interface, or enum expected
"// Testing"
^
1 error
3 warnings
```

So I couldn't simply reproduce this. :(

**Comment by lptr** [comment]
`:file-events:compileJava` executed after some changes:

https://ge.gradle.org/s/emavvn4l42hao/timeline?details=jau7xjgddmty6&outcome=SUCCESS

**Comment by bingranl** [comment]
Any updates on this issue? :)

**Comment by wolfs** [comment]
Yes, this has been fixed by https://github.com/gradle/gradle/pull/18205 in Gradle 7.3. The fix is that we probe the file system if we receive events, and if we don't we drop the VFS state.
