### ISSUE TITLE
Documentation: Incorrect instructions to increase inotify limits

### ISSUE THREAD

**Issue by anilkumarmyla** [gradle/gradle#17974]
Documentation at  the end of this page https://docs.gradle.org/current/userguide/gradle_daemon.html shows instructions to increase inotify limits as

```
echo 524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p --system
```

Which I assume are incorrect. Could have been either
`sudo sysctl -w fs.inotify.max_user_watches=524288`
or
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf`
followed by reloading sysctl

Let me know if it needs to be corrected and I can submit a pull request

**Comment by wolfs** [comment]
@anilkumarmyla Thank you for spotting this! We would be happy to receive a PR from you.
