### ISSUE TITLE
gradle wrapper task fails if local distribution is higher than wrapper distribution 

### ISSUE THREAD

**Issue by mrothe-ai** [gradle/gradle#17977]
Executing  `gradle wrapper --gradle-version 6.8` with a local gradle distribution of version 7.1 fails if the configuration of the project contains deprecated features for version 7.

### Expected Behavior

gradle wrapper task should execute successfully 
command: `gradle wrapper --gradle-version 6.8`

### Current Behavior

gradle wrapper task fails as the configuration for the project contains deprecated configurations (e.g. testCompile method() )

`Could not find method testCompile() for arguments [io.rest-assured:spring-mock-mvc:3.0.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`

### Context

I tried to refresh the gradle configuration for a project using gradle 6.8 with a fresh wrapper for version 6.8 with a local gradle distribution of version 7.1

Two alternative workarounds:
1. temporary using a local gradle of version < 7 to create the wrapper for the project and afterwards switch back to gradle 7 when the v6.8 gradle wrapper was successfully created
2. create the wrapper for 6.8 in a project without deprecated features for version 7 (e.g. an new empty project) and copy the wrapper configuration to the project where it is needed.

### Steps to Reproduce 

[wrapper_testing.zip](https://github.com/gradle/gradle/files/6953241/wrapper_testing.zip)
extract and run `gradle wrapper --gradle-version 6.8` (with a local gradle-distribution >= 7)

### Your Environment

Java 1.8
Gradle 7.1

Build scan URL:
https://scans.gradle.com/s/bf57cb67j3jgy

**Comment by mlopatkin** [comment]
The `wrapper` task is just a Gradle task and can be configured in the `build.gradle` files (for example, setting a custom distribution URL). Therefore Gradle has to configure the build to be able to execute the task. If the build configuration is incompatible with the current version of Gradle then it fails. Currently, we don't have plans to revisit this behavior.
