### ISSUE TITLE
ANDROID_SDK_ROOT is ignored. only sdk.dir at local.properties is used

### ISSUE THREAD

**Issue by jgmy** [gradle/gradle#17985]
This is probably old but it made me get a headache and I don't find it on the solved bugs

I installed gradle and android-sdk in an arm64 debian console.
I tried to compile an android project.
build failed with "can't find ANDROID SDK, set ANDROID_SDK_ROOT or sdk.dir on local.properties"

### Expected Behavior
Should work once ANDROID_SDK_ROOT is set

### Current Behavior
Failed.
Failed after
  ANDROID_HOME=$ANDROID_SDK_ROOT
Failed after 
   PATH=$PATH:$ANDROID_SDK_ROOT
Worked after
   echo sdk.dir=$ANDROID_SDK_ROOT>>local.properties

### Context
It made me pass hours downloading different android platform sdks with my low speed cell line.
### Steps to Reproduce 

Trying to compile github.org/lexica/lexica on a termux session on android with a minimal debian with packages git, gradle, android-sdk. gradle 6.4 debian 

### Your Environment

----                                                    Gradle 6.5                                              ------------------------------------------------------------                                                                                                            Build time:   2020-06-02 20:46:21 UTC                   Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4                                                          Kotlin:       1.3.72                                    Groovy:       2.5.11                                    Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019                                        JVM:          11.0.11 (Debian 11.0.11+9-post-Debian-1deb10u1)                                                   OS:           Linux 4.4.111-21737876 aarch64

Build scan URL:

**Comment by donat** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
