### ISSUE TITLE
Use same versioning on releases between archive and git tag

### ISSUE THREAD

**Issue by Jawnnypoo** [gradle/gradle#1799]
Hi there,

I have created a [plugin](https://github.com/Commit451/updatewrapper) which updates the Gradle wrapper to the latest released version of Gradle to make things easier on developers. It uses the GitHub API to get the latest release from this repo, and uses the tag name as the version number (minus the `v` in the beginning).

The problem I am running into is that when versions are released, such as `3.5`, the tag in git does not actually match the archive version. I could assume that if the version ends in `.0` to just remove that part of the version, but it is just a bit confusing/misleading that the tag and the archive versions do not exactly match. 

Thoughts on this?

**Comment by big-guy** [comment]
I would treat the `REL_xxx` tags as the real tag.  So 3.5 exists as https://github.com/gradle/gradle/releases/tag/REL_3.5

The `v3.5.0` tags are only there so we can manually add release notes to them.

**Comment by Jawnnypoo** [comment]
Okay great! Thanks for the tip! 👍
