### ISSUE TITLE
FindBugs plugin should not assume the jar has the version number in it

### ISSUE THREAD

**Issue by thejohnfreeman** [gradle/gradle#1800]
Similarly to [Jacoco plugin](https://github.com/gradle/gradle/issues/1783), FindBugs plugin should stop  [trying to parse the version number from the jar](https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/findbugs/FindBugsClasspathValidator.java#L50).

### Expected Behavior

This should work:

```groovy
dependencies {
    findbugs files("path/to/findbugs.jar", ...)
}
```

### Current Behavior

```
Execution failed for task ':findbugsMain'.
> Unable to infer the version of FindBugs from currently specified FindBugs classpath: [findbugs.jar, ...]
```

**Comment by petermn** [comment]
The FindBugs version number is later used to verify it vs Java version. What is expected behaviour if the FindBugs jar doesn't have a version number?

**Comment by petermn** [comment]
I don't think we can me sure about the manifest containing the version number. What is the name of the attribute where the version number should be? And if it's not there, should we keep on searching in the file name?

**Comment by petermn** [comment]
Any thoughts, @thejohnfreeman or @bmuschko? Is the property maybe Specification-version? What if it's empty, continue by extracting version number from jar file name? 
I'd love to try to fix this task, as my first contribution to Gradle/Gradle plugins :)

**Comment by thejohnfreeman** [comment]
I haven't dug into the manifest, but whether it has a version string or not, the plugin should accept a configuration parameter to override it.

**Comment by petermn** [comment]
@thejohnfreeman, @bmuschko :
Ok, so I'd check parameter, then manifest and if no version exist we'll continue parsing the Jar name?
I could look into this if you want? Should I create a small design doc (if yes, any guidelines?), or is it sufficient with this discussion and then a pull request?

**Comment by jjohannes** [comment]
The _Findbugs_ plugin is removed in Gradle 6.0.

Please use an alternative plugin like https://plugins.gradle.org/plugin/com.github.spotbugs
