### ISSUE TITLE
API discrepancy around getting Build identifier

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#18000]
In AGP we are trying to figure out the unique ID of a build in order to properly populate our dependency model.

We are approaching this from 3 different angles:

1. while processing the dependency graph of a project. 
`ProjectComponentIdentifier` returns `org.gradle.api.artifacts.component.BuildIdentifier` which only provides a `name` for the build that contributed the project.

2. While building the model of a given project.
If we want to project the project's information (path and build), then there's no way to get any unique ID for the current build. `org.gradle.api.invocation.Gradle` has a list of included builds but now information about the current build.
Now that the included builds do provide good information as `org.gradle.api.initialization.IncludedBuild` provides both a `name` and a `projectDir`.

3. Inside the Tooling model action, one can get a `org.gradle.tooling.model.BuildIdentifier` which returns a `rootDir`. I'm guessing that `rootDir` here is the same as `IncludedBuild.projectDir` but sadly the name of the property is not consistent.

There are 2 problems with this:

1. Attempting to match the build unique ID for each projects and what is provided by our dependency graph is impossible because the only reliable information we have for each project is `rootDir` from inside the model action, while the dependency graph only gives us `name.

2. It would also be more convenient if we could get that information from inside the `ToolingModelBuilder` because doing it from inside the model action means we have to mutate the model to add this information. So adding the info to `Gradle` would allow us to put it in our model directly.

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by ov7a** [comment]
Related:
* https://github.com/gradle/gradle/pull/24648
* https://github.com/gradle/gradle/pull/24963
