### ISSUE TITLE
Module exclusion causes massive increase in build time on 3.5

### ISSUE THREAD

**Issue by sonicsnes** [gradle/gradle#1801]
It seems that somehow #1298 has made our builds with many exclusions MUCH slower, rather than faster. The resolve time of our worst build has increased from 8 minutes to several hours.

### Expected Behavior

Resolving an ivy module with several excludes should be at least as performant as 3.4.1.

### Current Behavior

It seems that ivy modules with tons of excludes have actually increased in build time.

### Context

This is blocking us from upgrading to 3.5 since the resolve time for our modules has increased so severely. Modules with few or no excludes do not seem to be affected.

### Your Environment

Gradle 3.5
Here are the hot spots of a cpu profile after running it for about 10 minutes:
![screenshot from 2017-04-10 23-14-29](https://cloud.githubusercontent.com/assets/517502/24892638/be1cfdd2-1e43-11e7-82f1-7d188a1cace9.png)

**Comment by sonicsnes** [comment]
I was unable to reproduce this publicly, but after updating to 3.5 final and digging in a bit with a debugger, I believe I've discovered the cause. The issue only occurs with a large utilization of ivy pattern matcher exclude rules.

IvyPatternMatcherExcludeRuleSpec isn't ever merged (see IntersectionExclusion.canMerge), so as these patterns are pulled in via hundreds or thousands of edges, thousands of rule spec instances pile up, each attempting to be merged against each other on every node.

**Comment by sonicsnes** [comment]
I'm not sure about the correctness of this patch, but it's reduced the resolve time from hours to under 30 seconds on our large builds.

Changing the inner loop of ModuleExclusions to
```
           // See if we can merge any of the following specs into one
            for (int j = i + 1; j < specs.size(); j++) {
                if (spec.equals(specs.get(j))) {
                    specs.remove(j);
                    merged = spec;
                    break;
                }
                merged = maybeMergeIntoUnion(spec, specs.get(j));
                if (merged != null) {
                    specs.remove(j);
                    break;
                }
            }
```

Since the vast majority of our IvyPatternMatcherExcludeRuleSpec instances are identical, I'm assuming they can be merged by simply choosing one with no side effects?

**Comment by melix** [comment]
Thanks, your patch seems reasonable to me. I slightly updated it to:

```
AbstractModuleExclusion other = specs.get(j);
                if (spec.equals(other)) {
                    merged = spec;
                } else {
                    merged = maybeMergeIntoUnion(spec, other);
                }
```

I still need to check if the additional `equals` call has an impact on our exclude rule merging performance test, but I'll come back to you soon.

**Comment by oehme** [comment]
We should also add this case to our exclude rule merging performance test.
