### ISSUE TITLE
javaCompile.source replacedBy stableSources but there isn't such a property in 7.1.1

### ISSUE THREAD

**Issue by robstoll** [gradle/gradle#18014]
### Expected Behavior
Better pointers in deprecated messages

### Current Behavior
I don't know if stableSources was not added as planned or if the message should be improved

### Steps to Reproduce 
See deprecated warning for JavaCompile.source

### Your Environment
gradle 7.1.1

**Comment by wolfs** [comment]
@robstoll Thank you for reporting. Where do you see the deprecation warning? Is this something Gradle produces or the IDE?

**Comment by robstoll** [comment]
Its in the source code of gradle (according to the  sources jar the IDE shows)

**Comment by wolfs** [comment]
@robstoll Do you maybe have a custom inspection showing `ReplacedBy` as deprecated? I can't see any deprecation warning here. 
![image](https://user-images.githubusercontent.com/423186/129760277-e0479ecd-7d08-4849-9482-9f67a37217ec.png)

**Comment by robstoll** [comment]
I have not setup anything special in intellij 2021.2 but I will check which inspection shows me the ReplacedBy

**Comment by robstoll** [comment]
surprise, surprise... I don't see it as deprecated any more, there is not even the suggestion popping up to replace it :man_shrugging:
Anyway, as it seems you already improved something so it looks like the glitch of intellij was helpful after all :grin:
