### ISSUE TITLE
Gradle 7.0.2 no longer will deploy to S3 buckets with a dot and digit and throws NPE

### ISSUE THREAD

**Issue by andrewegel** [gradle/gradle#18022]
## Context

Our organization has been using gradle through the years to build a Java/Scala project. We have proprietary build scripts and staging S3 buckets we use for deploying maven artifacts.

We recently attempted to deploy a release using gradle to an s3 bucket that would follow the pattern `${BUCKET_NAME}-${VERSION_WITH_DOTS}`

This was working up till 7.0.2 (Before we were using `6.8.1`). It is throwing an NPE exception (version 7.0.2's is bellow):

```
13:03:59  Caused by: java.lang.NullPointerException
13:03:59  	at org.gradle.internal.resource.transport.aws.s3.S3RegionalResource.getBucketName(S3RegionalResource.java:84)
13:03:59  	at org.gradle.internal.resource.transport.aws.s3.S3RegionalResource.configure(S3RegionalResource.java:73)
13:03:59  	at org.gradle.internal.resource.transport.aws.s3.S3RegionalResource.<init>(S3RegionalResource.java:39)
13:03:59  	at org.gradle.internal.resource.transport.aws.s3.S3Client.putSingleObject(S3Client.java:132)
13:03:59  	at org.gradle.internal.resource.transport.aws.s3.S3Client.put(S3Client.java:124)
13:03:59  	at org.gradle.internal.resource.transport.aws.s3.S3ResourceConnector.upload(S3ResourceConnector.java:85)
13:03:59  	at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceUploader.upload(ProgressLoggingExternalResourceUploader.java:39)
13:03:59  	at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.put(AccessorBackedExternalResource.java:182)
13:03:59  	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$3.call(BuildOperationFiringExternalResourceDecorator.java:100)
13:03:59  	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator$3.call(BuildOperationFiringExternalResourceDecorator.java:97)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
13:03:59  	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
13:03:59  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
13:03:59  	at org.gradle.internal.resource.BuildOperationFiringExternalResourceDecorator.put(BuildOperationFiringExternalResourceDecorator.java:97)
13:03:59  	at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher$ModuleArtifactPublisher$1.run(AbstractMavenPublisher.java:272)
13:03:59  	at org.gradle.api.internal.artifacts.repositories.transport.NetworkOperationBackOffAndRetry.withBackoffAndRetry(NetworkOperationBackOffAndRetry.java:50)
13:03:59  	at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher$ModuleArtifactPublisher.putResource(AbstractMavenPublisher.java:269)
13:03:59  	at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher$ModuleArtifactPublisher.publish(AbstractMavenPublisher.java:230)
13:03:59  	at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher$ModuleArtifactPublisher.publish(AbstractMavenPublisher.java:223)
13:03:59  	at org.gradle.api.publish.maven.internal.publisher.AbstractMavenPublisher.publish(AbstractMavenPublisher.java:81)
13:03:59  	at org.gradle.api.publish.maven.internal.publisher.MavenRemotePublisher.publish(MavenRemotePublisher.java:61)
13:03:59  	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:50)
13:03:59  	at org.gradle.api.publish.maven.tasks.PublishToMavenRepository$1.publish(PublishToMavenRepository.java:109)
13:03:59  	at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:43)
13:03:59  	... 121 more
```

I can provide a larger stack trace, but I don't think its needed as this seems to be a behavior from `java.net.URI`, which is coming from here: https://github.com/gradle/gradle/blob/v7.0.2/subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3RegionalResource.java#L73

### Expected Behavior
Gradle bellow version 7.0.2 was working with buckets URLs with values `s3://my-awesome-bucket-7.0.0/maven`, this seems to be a problem now when parsed through `java.net.URI`.  So this would be classified as a regression of behavior.

### Steps to Reproduce 
Rather simple java program:

```
import java.net.URI;
import java.net.URISyntaxException;

class S3URI {
    public static void main(String[] args) {
        try {
            URI uri1 = new URI("s3://my-awesome-bucket-7-0-0/maven");
            System.out.println("Parses Correctly: " + uri1.getHost());
            URI uri2 = new URI("s3://my-awesome-bucket-7.biz/maven");
            System.out.println("Still parses: " + uri2.getHost());
            URI uri3 = new URI("s3://my-awesome-bucket-7.0.0/maven");
            System.out.println("No longer parses: " + uri3.getHost());
        } catch(URISyntaxException e) {
            System.out.println("ERROR" + e.toString());
        }
    }
}
```

```
javac S3URI.java && java S3URI
Parses Correctly: my-awesome-bucket-7-0-0
Still parses: my-awesome-bucket-7.biz
No longer parses: null
```

## What do I hope to achieve?

I'm putting in a workaround on my end [1], this is just to log an issue/regression.

[Edit]
Ideally this scenario is checked for (Check if URI.getHost() returns null) and raise a more informative error message such as "invalid bucket name" (even though S3 would accept it as a valid name)
[/Edit]

[1] It was high time we stopped including `.` in our bucket names which throws off AWS S3's SSL Cert when accessing objects through the DNS endpoint (ie: `https://my-bucket.s3.us-west-2.amazonaws.com/my/key`)

**Comment by jbartok** [comment]
@andrewegel , I have looked into this and I can confirm the problem you describe. Will work on fixing it. 

What is unclear to me is why it has worked for you before, because I can reproduce the same exact NPE with any Gradle and JDK version I try. As far as I can tell, those basket names with dotted versions in them should have never worked... Could you maybe put together a reproducer? Or any ideas on what might be different in your setup?

**Comment by andrewegel** [comment]
> As far as I can tell, those basket names with dotted versions in them should have never worked... Could you maybe put together a reproducer? Or any ideas on what might be different in your setup?

I had to dig into some crufty code and found something - I think it was working "before" because we were using the `org.springframework.build:aws-maven:5.0.0.RELEASE` plugin to do the deployment to S3, so in re-reviewing my assumptions here, this isn't a bug in Gradle, because we were never using Gradle's libraries to deploy, and were instead relying on an external maven plugin to do the work, where I guess S3 buckets with dots in the name do work.

I appreciate you putting in a fix for this anyways, but I understand with this new information if you wanted to pull it back out.

**Comment by jbartok** [comment]
@andrewegel thank you for sorting it out. The issue in Gradle is genuine in that it wasn't working as expected, so I think the fix will remain and is useful. A win-win I guess ;)
