### ISSUE TITLE
Stepwise tests; order is wrong in Gradle report

### ISSUE THREAD

**Issue by transentia** [gradle/gradle#18037]
Spock tests.
Testing spring webflow, so each class is annotated as @Stepwise.

Intellij shows that Gradle IS actually executing the tests in the appropriate stepwise defined order:

<img width="430" alt="stepwise-ij" src="https://user-images.githubusercontent.com/105110/129495174-20da12b4-5750-4804-8c8c-90c166292bf5.png">

BUT the generated gradle test report does not respect the stepwise execution; tests are shown in alphabetic order:

![stepwise-gradle-report](https://user-images.githubusercontent.com/105110/129495201-fa51e754-3920-4061-8da4-ed932e0cbcbb.jpg)

This is confusing my users...

The gradle report should reflect the execution order.

### Your Environment
Gradle 7.1.1, java 16.0.2, windows 10

**Comment by jbartok** [comment]
I can confirm the problem. HTML test results always display the tests in alphabetical order, regardless of the actual running order. XML test results however don't have the same problem, actual running order is preserved in those, so this should be a problem specific to HTML results.

**Comment by transentia** [comment]
I'm GUESSING (based on my very first quick look around the source...instant 'expert' here) that this traces to the use of TreeSet in org.gradle.api.internal.tasks.testing.report.ClassTestResults?

![image](https://user-images.githubusercontent.com/105110/129878326-41746229-be4e-4d14-abed-f0b489e71519.png)

By default, TreeSet won't preserve insertion order.

**Comment by jbartok** [comment]
@transentia we have discussed this internally and the conclusions are as follows. 

Your request is a bit a-typical in the sense that in our opinion many users of these HTML reports would probably prefer alphabetical order over execution order. HTML is for human consumption and then, as a person, if you want to find something on a long list, alphabetical order is preferred. 

However, we're sure that execution order does make sense in some scenarios. If we would have much more resources than we do, then probably the best solution would be to make the HTML reports sortable, on various columns, one of which might be the execution start time (assuming that can be done without increasing the report generation cost for every scenario). 

The reality is that we don't have the resources for this right now, but we happily accept contributions....

What you could do to solve your concrete problem is to use some other test result report, for example the XML ones and extract the information you need from there.
