### ISSUE TITLE
javadoc options.links canot follow redirects http 302 moved

### ISSUE THREAD

**Issue by AoEiuV020** [gradle/gradle#1803]
### Expected Behavior

javadoc success,

### Current Behavior

> :javadocjavadoc: warning - Error fetching URL: https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.7.25/

**Notice the last character '/'**
https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.7.25/
will redirect to 
https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.7.25

### Context

I want to auto link all dependencies's javadoc
```
apply plugin: 'java-library'
repositories {
    jcenter()
}
dependencies {
    implementation 'com.google.guava:guava:20.0'
    implementation 'org.slf4j:slf4j-api:1.7.25'
    testImplementation 'org.slf4j:slf4j-simple:1.7.25'
    testImplementation 'junit:junit:4.12'
}
def linksList=new LinkedList<>();
linksList.add "https://docs.oracle.com/javase/8/docs/api"
configurations.implementation.dependencies.each {
    linksList.add "https://www.javadoc.io/doc/$it.group/$it.name/$it.version" as String
}
tasks.withType(Javadoc) {
    options {
        links linksList.toArray([] as String[])
    }
}
```

### Steps to Reproduce (for bugs)

build.gradle
```
apply plugin: 'java-library'
tasks.withType(Javadoc) {
    options {
        links 'https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.7.25'
    }
}
```
`./gradlew cleanJavadoc javadoc`
### Your Environment

archlinux,oracle jdk,java version "1.8.0_121",
gradle wrapper,
distributionUrl=https\://services.gradle.org/distributions/gradle-3.4.1-bin.zip

**Comment by AoEiuV020** [comment]
![screenshot from 2017-04-11 16-48-40](https://cloud.githubusercontent.com/assets/11682198/24900552/d11a5f5e-1ed6-11e7-86d0-ca189c059572.png)

**Comment by AoEiuV020** [comment]
![screenshot from 2017-04-11 16-53-17](https://cloud.githubusercontent.com/assets/11682198/24900748/6d7ca83e-1ed7-11e7-8e0b-43cd4d7361b2.png)

**Comment by AoEiuV020** [comment]
same with gradle 3.5
![screenshot from 2017-04-11 17-00-48](https://cloud.githubusercontent.com/assets/11682198/24901060/7cc45764-1ed8-11e7-8397-0570c2a858f9.png)

**Comment by AoEiuV020** [comment]
Build scan URL: https://gradle.com/s/eaqh3kys54g2s

**Comment by blindpirate** [comment]
I'm afraid there's nothing Gradle can do, the warning is from `javadoc` command.

Try the following command and you'll get the same result:

```
cd src/main/java && javadoc <youpackage> -link https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.7.25/ 1>/dev/null
```

**Comment by bmuschko** [comment]
Given that it is plain Javadoc behavior I don't think we'll do something on the Gradle side. Closing this issue. Feel free to reopen if you have additional questions.
