### ISSUE TITLE
Unable to build Gradle 7.1.1 bin distribution from source on Arm64 due to selected nodejs architecture

### ISSUE THREAD

**Issue by duntonr** [gradle/gradle#18053]
### Expected Behavior
`./gradlew :distributionsFull:binDistributionZip` on an Arm64 box should produce the binary zip

### Current Behavior
`./gradlew :distributionsFull:binDistributionZip`  fails on `Task :kotlinNpmInstall`.  

More info:
```
...
> Task :distributions-full:emptyClasspathManifest FROM-CACHE
> Task :ear:processResources
> Task :rootPackageJson
Download https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz
> Task :enterprise:processResources
> Task :scala:processResources
Error while receiving file changes
net.rubygrapefruit.platform.NativeException: wstring_convert::from_bytes
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.executeRunLoop0(Native Method)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.access$100(AbstractFileEventFunctions.java:157)
	at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher$1.run(AbstractFileEventFunctions.java:171)
Stopping file watching and invalidating VFS after an error happened
> Task :kotlinNpmInstall FAILED
> Task :ide:processResources
/root/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node: 1: /root/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node: ELF: not found
/root/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node: 12: /root/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node: Syntax error: word unexpected (expecting ")")
> Task :messaging:classpathManifest
> Task :distributions-full:dslMetaData
Parsed 1535 classes in 10.734 seconds
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':kotlinNpmInstall'.
> Process 'Resolving NPM dependencies using yarn' returns 2
  
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 35m 4s
...
```

### Context
This issue prevents recent Gradle versions bins from building on Arm64

### Steps to Reproduce 
I am using this GitLab CI / Jenkins-ish build file:
```yaml
stages:
    - build
    - release

variables:
    GRADLE_VERSION: "7.1.1"

build:
    stage: build
    image: registry.gitlab.com/therackio/base-images/openjdk-zulu-arm64:buster-11
    tags:
        - arm64-aws-xlarge
    script:
        - apt update
        - export DEBIAN_FRONTEND=noninteractive && apt install -y --no-install-recommends git unzip
        - apt -y full-upgrade
        - git clone https://github.com/gradle/gradle.git
        - cd gradle
        - git fetch
        - git checkout tags/v$GRADLE_VERSION
        - sed -i "s/dev12\.gradle\.org\/artifactory\/gradle-plugins/repo\.grdev\.net\/artifactory\/gradle-plugin-portal-prod/i" ./gradle/shared-with-buildSrc/mirrors.settings.gradle.kts
        - chmod +x ./gradlew
        - ./gradlew :distributionsFull:binDistributionZip
        - ls -al ./subprojects/distributions-full/build/distributions/   
        - mkdir -p ./dist
        - cp ./subprojects/distributions-full/build/distributions/gradle-$GRADLE_VERSION-bin.zip ./dist
    artifacts:
        paths:
            - gradle/dist/gradle-$GRADLE_VERSION-bin.zip
        expire_in: 1 hour
```

The base image here is just a recent zulu/buster/ Java 11 container and the sed monkey patch is to handle whats working its way  into a release from: https://github.com/gradle/gradle/pull/17597/files

Specifically, then `ELF: not found` and `Syntax error: word unexpected (expecting ")")` errors look like C arch mismatch type wonkyness.  

This isn't surprising since `/root/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node:` shows Gradle picked the x64 version of nodejs to cache, which I suspect is the root of the issue

### Your Environment
Arm64v8 host (AWS ARM64 EC2)
Alpine docker build/ci container

**Comment by duntonr** [comment]
the issue also applies to Gradle 7.2

**Comment by mlopatkin** [comment]
The code that [determines NodeJS' architecture](https://github.com/JetBrains/kotlin/blob/v1.5.21/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/nodejs/NodeJsPlatform.kt) in the Kotlin plugin was a bit suspicious. I don't have access to the Arm64 machine right now to check though. @duntonr, could you please check what `System.getProperty("os.arch")` returns in this Docker image?

**Comment by duntonr** [comment]
@mlopatkin - sorry for the delay in responding, I was out last week.

the value is: `aarch64`

I set up an extremely basic test build project here: https://gitlab.com/therackio/build-tools/helper-images/java-buildtools-diagnostic-arm64 and build output here: https://gitlab.com/therackio/build-tools/helper-images/java-buildtools-diagnostic-arm64/-/pipelines to be able to run additional tests if needed

**Comment by mlopatkin** [comment]
Thanks for the reply! The `aarch64` is indeed breaking the Kotlin plugin which is responsible for downloading NodeJS. [The fix for this](https://github.com/JetBrains/kotlin/commit/021d053cfe3881634e81a1133d7f7e2ea505ce4f) has already landed on master but I don't know when it will make it into the release (it already missed 1.5.30).

I'll reply there when we update the Kotlin plugin to the fixed version but I cannot give any estimation of when it happens.

**Comment by duntonr** [comment]
Thank you for the update!

**Comment by meMuszr** [comment]
@mlopatkin That patch landed in `1.6.0`. Any update on this?

**Comment by duntonr** [comment]
For what its worth, I did try with Gradle 7.3.3...same issue with kotlin so hasnt made it to Gradle yet
`> Task :kotlinNpmInstall FAILED> Task :kotlinNpmInstall FAILED`

**Comment by mlopatkin** [comment]
Most likely, we'll update to Kotlin 1.6 in Gradle 7.5.
