### ISSUE TITLE
Allow declaring untracked task properties

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#18068]
Design spec: https://docs.google.com/document/d/1TUBFw0l0t1-lM_b9qXAjyz4sVS7i2eSkWipn_EGCe2s/edit#heading=h.34e7q65b9q1k

# Background

There are some instances when tasks declare input or output files, though the actual contents of those files cannot or should not be tracked by Gradle. Typical examples:

* Install files/applications into their target locations, like /usr/bin
* Installing war files into application servers ([Copy fails if target directory contains unreadable directory · Issue #9576 · gradle/gradle](https://github.com/gradle/gradle/issues/9576)) 
* Using a tool with its own up-to-date checking
    * Doing a git checkout (since git is handling the changes in the output directory)
    * Running Node or Yarn
    * Running CMake
* Collecting log files from a partially unreadable directory hierarchy: [FileTree from directory with complex permissions AcessDeniedException · Issue #2639 · gradle/gradle](https://github.com/gradle/gradle/issues/2639)

There seem to be use-cases for input and output properties, though the output property use-cases seem to be more important/common.

This change is also related to [Disable caching and up-to-date checks completely for task · Issue #9095 · gradle/gradle](https://github.com/gradle/gradle/issues/9095), and solves the issue in a different way.

Finally, we want to drive this change forward since we want to implement [Use input snapshots to skip empty work · Issue #9980 · gradle/gradle](https://github.com/gradle/gradle/issues/9980). The problem there is that we use a MissingFileSnapshot to represent an unreadable file. Those are indistinguishable from actually missing files or broken symlinks. Currently, when an unreadable file is the root of a source tree (SkipWhenEmpty), then the build fails because it tries to resolve the source file collection. Though when using fingerprints, the fingerprint would consist of a single missing file fingerprint which we consider to be empty, so Gradle would skip the task. We want to keep the behavior and fail the build when an unreadable location is declared as an input.

As a result we’d have a concept of “tracked inputs” and “tracked outputs” that will always have to be snapshottable. If a tracked input or output is not snapshottable, we can fail. Untracked inputs and outputs mean we don’t try to snapshot them, nor store them in the VFS. This simplifies things around file system state tracking significantly.

# Functional design

## What already exists?

It is currently possible to make a task always out-of-date by using `upToDateWhen { false }`, though this still causes the inputs and outputs to be snapshotted. Another option is to not declare any outputs, though that prevents Gradle from making sure no other tasks which modifies the same outputs run in parallel.

We snapshot unreadable files as missing files and then treat them as those in file fingerprints.

## What will change?

The idea is to be able to declare that a task file property is untracked. The consequence of this declaration is that:

* Gradle will not try to snapshot/fingerprint the property
* The task is not cacheable and will never be up-to-date

Other things will still work as before:

* Tasks writing to the same output location will not run in parallel
* We will invalidate the VFS at the output location before the task starts executing
* Tasks can be wired up via input and output properties, even though they are untracked

This way Gradle can avoid snapshotting unreadable files completely and we can fail when we try to snapshot them.

Untracked file properties can be considered as “locations Gradle is not supposed to understand”. Given that distinction, we can make sure that everything in the VFS is understood completely by Gradle.

Regarding the public API, we want to declare this kind of behavior similar to the already existing options for fingerprinting/snapshotting. So we would introduce

* An annotation `@Untracked` which can be added on task file properties, except for `@LocalState` and `@Destroyable`. The annotation is task-specific, and cannot be used for artifact transforms, where we want to ensure that everything is well understood by Gradle.
* A runtime API method `TaskFilePropertyBuilder.untracked(boolean = true)`
* Finally, in order to support the above use-cases for the Copy task, we add a property either to Copy or to CopySpec to declare a destination directory to be untracked.

## What are some alternatives that were considered?

We considered introducing a new snapshot file type for unreadable files, so we could distinguish them from missing files (see [https://github.com/gradle/gradle/pull/15033](https://github.com/gradle/gradle/pull/15033)). Gradle would then fail when trying to convert an unreadable file snapshot into a file fingerprint. That introduced quite some complexity, which we would like to avoid.

# Questions/Problems

* Should it be possible to allow ArtifactTransforms to declare untracked properties
    * No, artifact transforms need to be understood correctly by Gradle, so all the inputs and outputs need to be tracked/trackable.

**Comment by melix** [comment]
FWIW the design spec is not available without asking for permission ;)
