### ISSUE TITLE
Configuration cache issue with :pluginUnderTestMetadata when java-gradle-plugin has project dependency

### ISSUE THREAD

**Issue by andygoossens** [gradle/gradle#18064]
### Expected Behavior
My build, which uses java-gradle-plugin, shouldn't fail with a deserialization error when configuration cache is enabled.

### Current Behavior
The build fails for a simple Java Gradle plugin which depends on another project when using the configuration cache.

### Context
I tried to get my own Java Gradle plugin to build with the configuration cache enabled.

Note that this issue looks similar to #16183. But while that particular issue got fixed before 7.0, what I am seeing now is reproduceable with Gradle versions 7.1.1 and 7.2-rc3.

### Steps to Reproduce
Here is minimalistic project that reproduces the issue: [my-java-gradle-plugin-cc.zip](https://github.com/gradle/gradle/files/6999298/my-java-gradle-plugin-cc.zip)

Steps to reproduce:
1. ./gradlew build
2. ./gradlew build

Results in:

> $ ./gradlew build
> Configuration cache is an incubating feature.
> Calculating task graph as no configuration cache is available for tasks: build
> 
> BUILD SUCCESSFUL in 14s
> 8 actionable tasks: 8 executed
> Configuration cache entry stored.
> 
> $ ./gradlew build
> Configuration cache is an incubating feature.
> Reusing configuration cache.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not load the value of field `collection` of `org.gradle.api.internal.file.AbstractFileCollection$ElementsProvider` bean found in field `provider` of `org.gradle.configurationcache.serialization.codecs.ProviderBackedFileCollectionSpec` bean found in field `pluginClasspath` of task `:my-plugin:pluginUnderTestMetadata` of type `org.gradle.plugin.devel.tasks.PluginUnderTestMetadata`.
> > org.gradle.plugin.devel.plugins.JavaGradlePluginPlugin$$Lambda$2590/0x0000000841e73440
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> CONFIGURE FAILED in 916ms
> Configuration cache entry reused.

### Your Environment
Build scan URL:
https://gradle.com/s/xwuvoafg2ufky

**Comment by andygoossens** [comment]
And as Gradle 7.2 got released moments ago: the failure is still present in 7.2.

**Comment by gavra0** [comment]
This is the lambda that fails to serialize - https://github.com/gradle/gradle/blob/78887e621a869da7a6ef7277aaf984a7d8dca52e/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java#L189.
