### ISSUE TITLE
The wrapper script generated by Gradle 7.2 contains weird `#(` comments

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#18066]
### Expected Behavior

There are no superfluous / empty comments in the generated wrapper script.

### Current Behavior

There are several lines with trailing "comments" in the form `#(` (but nothing else).

### Context

This was discovered during a code review in a project that upgrades Gradle and the wrapper script to version 7.2.

### Steps to Reproduce

In a project using Gradle 7.1.1, run `./gradlew wrapper --gradle-version=7.2 --distribution-type=all` *twice* so that also the local wrapper scripts gets updated, and look at the [diff](https://github.com/oss-review-toolkit/ort/pull/4368/files#diff-e9721dc750619a21053ddea8a5d04929a608877d8c5daec1b57d243d3424e745R110):

![image](https://user-images.githubusercontent.com/349154/129727005-96112cae-741c-4a22-ba6a-b65d01eaef71.png)

### Your Environment

Windows 10, Gradle 7.2 (coming from Gradle 7.1.1)

**Comment by mlopatkin** [comment]
This is intentional though the necessity of this technique here is questionable. I'm not a shell guru but it seems that the "comment" approach originates in the [autoconf manual](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Balancing-Parentheses.html).
