### ISSUE TITLE
java.lang.NullPointerException: VersionCatalogsExtension::class.java does not exist

### ISSUE THREAD

**Issue by mgingios** [gradle/gradle#18078]
After upgrading to Gradle 7.2, I cannot access the VersionCatalogExtension.  In version 7.1.1, my code worked.  The attached example shows this issue.  In version 7.1.1, I did not use the alias( Provider<PluginDependency>) function but id(string).

### Expected Behavior
I expect to find the version catalog extension and use it to resolve versions and dependencies from the catalog.

### Current Behavior
I receive a NullPointerException when trying to find the VersionCatalogsExtension, and the following message is reported:
"Using dependency catalogs requires the activation of the matching feature preview."

```
pluginManagement {
    // Set the default plugin versions for all projects.
    plugins {
        extensions.findByType(VersionCatalogsExtension::class.java)?.let { versionCatalogsExtension ->
            versionCatalogsExtension.named("libs").apply {
                alias(findPlugin("kotlin_jvm_gradle").get())
                alias(findPlugin("kotlin_reflect_gradle").get())
                alias(findPlugin("kotlin_stdlib_jdk8").get())
            }
        }?: throw kotlin.NullPointerException("VersionCatalogsExtension::class.java does not exist")
    }
}
```

### Context
I want to use the version catalog in a project, but it does not seem to work in Gradle 7.2.x.
I am able to use the version catalog in a Gradle 7.1.1 project, with slight changes due to new features in 7.2.x.

### Steps to Reproduce 
I have attached a project that can be used to reproduce the issue.  Simply try to build it and the NPE will be reported.

### Your Environment

Build scan URL: https://gradle.com/s/u67bcnp3ffryu/activate/zeqyifqau7gne

Since the build would not complete with the code, above, I commented out throwing the NPE when the VersionCatalogsExtension was not found, and generated the build scan.  The data should still be helpful concerning the build environment.
[versions.zip](https://github.com/gradle/gradle/files/7011399/versions.zip)

**Comment by mlopatkin** [comment]
Could you please attach the sample that worked with 7.1.1? I did minor modifications to your reproducer but it failed to me with the same error message when I run it with 7.1.1.

**Comment by ljacomet** [comment]
I am pretty sure this is a duplicate of #18050 :
In order to improve what you can do with alias hierarchy, `kotlin_jvm_gradle` is always transformed to `kotlin.jvm.gradle` including for the non type safe API.

Can you confirm updating your alias references then works?

**Comment by mgingios** [comment]
Hi guys, I will change the aliases and report back.  If the issue persists, I will package up a version with Gradle 7.1.1.  Thanks for the quick response!

**Comment by mgingios** [comment]
Hello Guys, Based on yogurtearl's response, it looks like I am using incorrect aliases? If so, please tell me what to correct in the version2 sample that I've posted, and I can let you know the results. I continued to investigate with that project and found that whenever I try find the VersionCatalogsExtension in the following code, it fails and returns a null. If I comment out that code and don't set global plugin versions in that block of code, then everything is okay. I tried the same tests using a version catalog in a Jar, with the same results. Please advise if I can help validate a solution with my versions2 mini-app.


    // Set the default plugin versions for all projects.
    plugins {


//        extensions.findByType(VersionCatalogsExtension::class.java)?.let { versionCatalogsExtension ->
//            versionCatalogsExtension.named("libs").apply {
//                alias(findPlugin("kotlin.jvm.gradle").get())
//            }
//        }?: throw kotlin.NullPointerException("VersionCatalogsExtension::class.java does not exist")
    }

    // Set the plugin repositories for all projects.
    repositories {
        gradlePluginPortal()
    }
}

**Comment by mlopatkin** [comment]
@mgingios since 7.2 you should use dot-separated alias string (`kotlin.jvm.gradle`). However, NPE happens before that, so the root cause is different there.

Could you please provide a sample that worked for you with 7.1?

**Comment by mgingios** [comment]
Hi Guys, I had a chance to amend the project to use dots and recommended, and the issue was resolved.  I agree with your assessment that more clarity in the docs and/or examples would be helpful.
