### ISSUE TITLE
Specify project dependency configuration with type-safe project accessors

### ISSUE THREAD

**Issue by petertrr** [gradle/gradle#18075]
### Expected Behavior
Be able to specify configuration of the project when adding it as a dependency in multi-project build.

### Current Behavior
Old way of setting project dependencies has a version with `configuration` parameter:
```kotlin
fun DependencyHandler.project(
    path: String,
    configuration: String? = null
): ProjectDependency
```
However, as far as I can see, it's not yet implemented with type-safe project dependencies via `projects`:
```kotlin
projects.common
```
calls `TypeSafeProjectDependencyFactory#create(String path)` without possibility to set configuration.

It would be nice to have this feature with type-safe accessors, e.g. like
```kotlin
project.common(configuration = "distribution")
```
or
```kotlin
project.common {
    configuration = "distribution"
}
```

Maybe this already is on a roadmap, but I couldn't find an issue.

**Comment by U1F984** [comment]
I would also like this feature, it would be even better if the generated accessors also generated the configurations (not sure if this is possible).

At the moment we use this workaround, maybe it is useful for someone else:

```kts
implementation(project(projects.common.dependencyProject.path, "distribution"))
```

**Comment by ljacomet** [comment]
This is already possible although not explicitly documented:

```
    implementation(projects.utilities) {
        targetConfiguration = "runtimeElements"
    }
```

What you get from the typesafe accessor is of public type `ProjectDependency` which inherits `targetConfiguration` from `ModuleDependency`.

The reason for not explicitly documenting this is that we want to discourage the pattern as builds should leverage variant aware resolution and use attributes on configurations for doing this kind of selection.

**Comment by ljacomet** [comment]
Closing as resolved since there is a way to achieve the desired result.
