### ISSUE TITLE
Scrolling in `cmd.exe` cause artifact to appear in the console

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#1807]
### Expected Behavior
Scrolling in `cmd.exe` have no negative effect on the console.

### Current Behavior
Artifacts appear in the console as the user scroll in the command line.

### Context
Seen on Windows 10.

### Steps to Reproduce (for bugs)

Starts a build and scroll down in the console.

**Comment by mpereztr** [comment]
what happened with this??? i have dragle 4.6 and still happening

**Comment by mpereztr** [comment]
What happened? i have gradle 4.6 and still `happening!!!!!!![
![proof](https://user-images.githubusercontent.com/36317618/37792650-b486a0de-2de2-11e8-9650-2c6ac487e7c9.jpg)
](url)`

**Comment by lacasseio** [comment]
This issue is still a bit problem on Windows.
