### ISSUE TITLE
Upgrading Gradle from 6.8.2 to 7.1.1 - Checkstyle Plugin

### ISSUE THREAD

**Issue by venkycdmbrm98** [gradle/gradle#18081]
I have read in the documentation that config has been changed to configDirectory in checkstyle Plugin - gradle 7.1.1. But config has parameters of file type, whereas configDirectory has DirectoryProperty.

Gradle 6 - build.gradle

String path = "/abc/xyz";
apply plugin : 'checkstyle'

checkstyle { 
    config file(path) 
}
How do I convert the path to a directoryProperty? i.e., how do I write the same in gradle 7.1.1

I tried the same,

String path = "/abc/xyz";
apply plugin : 'checkstyle'

checkstyle { 
    configDirectory file(path) 
}
But I'm getting this error, while running gradle build,

Could not find method configDirectory() for arguments [.... path...] on extension 'checkstyle' of type org.gradle.api.plugins.quality.CheckstyleExtension.

**Comment by mlopatkin** [comment]
Could you please point me to the documentation that suggests replacing `config` with `configDirectory`? Also, the Gradle 6 version you're showing won't work: the `config` is a `TextResource`, you cannot assign a file to it. In both cases you need to use `=`:
```
checkstyle {
    configDirectory = file('config/checkstyle/')
}
```

**Comment by venkycdmbrm98** [comment]
@mlopatkin
It has stated as getters and setters for configDir has been deprecated. [https://docs.gradle.org/current/userguide/upgrading_version_6.html](url)

**Comment by mlopatkin** [comment]
Thanks, now I see what you've meant. Just use `configDirectory = file(....)`. You were talking about `config` initially which is a completely different property.

As this is a question rather than an issue with Gradle, I'm closing it.
