### ISSUE TITLE
Cancelling `gradle init` leaves leftovers lying around

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#18080]
Even if you hit Ctrl+C, after having started `gradle init`, some files will be created in the current directory.
Continuation of #17803, separates this problem from the others reported there.

### Expected Behavior
Nothing should be created in the current directory, if `gradle init` is aborted (at any stage, especially during the configuration wizard.

### Current Behavior
By the time the configuration wizard starts some files are already created by `gradle init`, so aborting leaves them there.

**Comment by eskatos** [comment]
Still an issue

**Comment by arthursmel** [comment]
Hi Gradle folks, I am working on a solution for this one.

**Comment by ppazos** [comment]
Still happening.

**Comment by alllex** [comment]
@ppazos, could you provide more details or file a new issue if the problem still happens with Gradle 8.6+?
