### ISSUE TITLE
Composite builds IDEA integration should de-duplicate submodule names

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#1808]
When 2 composite participants have submodule with the same name, `gradle idea` only results in one of those submodules appearing in IDEA as a proper Java "module" (e.g. with code to compile, etc.). The other one ends up as a directory in IDEA. 

Our workaround was to rename one of the submodules to something else and this helped.

https://issues.gradle.org/browse/GRADLE-3551
https://discuss.gradle.org/t/composite-builds-idea-integration-should-de-duplicate-submodule-names/19391

**Comment by eriwen** [comment]
@bigdaz is this still intended for 4.0?

**Comment by bigdaz** [comment]
@eriwen Yep, this feature is in. I'll get @big-guy to review so we can close it off.
