### ISSUE TITLE
Allow JVM debug options to be configurable

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#18084]
Currently the debug JVM options are hard-coded in Gradle, so if you use `org.gradle.debug = true` or use `--debug-jvm`, you always get the same debug options which is, it listens on port 5005 for the debugger and waits for it to attach.

There are various reasons for wanting to configure those, for example you already have some other process listening on 5005, or you want the IDE to listen on 5005 and have the debugee connect to the IDE instead or not wait for the IDE to attach.

You can of course always use manual ways like configuring jvm options on the test task or the java exec task and so on, but that would always mean a change of the build scripts. It would be nice if the debug jvm args are simply configurable e. g. using a Gralde property, so that you can adapt them to your local situation easily.

### Expected Behavior
Have some Gradle Property that defines the debug options used in various places like for debuging Gradle itself or debugging JVM-based tasks like test or java exec.

### Current Behavior
The options are hard-coded,

**Comment by donat** [comment]
I added the `onboarding` tag for the `--debug-jvm` use-case.

**Comment by platan** [comment]
I'd like to do this feature. I've already added `org.gradle.debug.port` property which allows defining port. [Debug options](https://docs.gradle.org/current/javadoc/org/gradle/process/JavaDebugOptions.html) have also `server` and `suspend` options. Would you like to support them as well? Is adding `org.gradle.debug.server` and `org.gradle.debug.port.suspend` properties a good way to configure them? Or maybe you thought about one property that allow defining all debug options?

**Comment by donat** [comment]
@platan Thank you for your contribution!
