### ISSUE TITLE
In which Gradle version did Java 6 source/target get removed?

### ISSUE THREAD

**Issue by Katharsas** [gradle/gradle#18099]
This more of a documentation bug (?).

The Gradle 6 [documentation](https://gradle.org/whats-new/gradle-6/) says the following:
`Gradle supports running on JDK8 through JDK13. JDK6 and 7 can still be used for compilation and testing.`

This does not seem to be true. When i try to compile a project that is configured with `sourceCompatibility = 1.6` using Gradle 6.9.1 on AdoptOpenJdk-15.0.2.7, i get the following error on `.\gradlew.bat compileJava`:

```
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
```

Im just trying to find out since which gradle version the support for Java 1.6 has been dropped, but i can find no information on this anywhere.

**Comment by blindpirate** [comment]
That's the limitation of JDK. You need to use lower version JDK to compile to Java 6 byte code.

**Comment by Katharsas** [comment]
Oh ok thanks, looks like it was removed in JDK 12
