### ISSUE TITLE
7.0.2 - supplied javaHome not found (error message shows wrong path)

### ISSUE THREAD

**Issue by rompic** [gradle/gradle#18092]
### Expected Behavior
The provided javaHome shall be used

### Current Behavior
gradle uses a javaHome from a different folder than the one provided and fails as it has been deleted
```
14:58:50  C:\jenkins\workspace\or_PR-5263>gradlew.bat project:subproject:task -Dorg.gradle.java.home=C:\jenkins\workspace\or_PR-5263/buildfiles/tool_BuildEnv/tools/jdk_x86_64/win32_1.8.0_121/ 
14:58:51  
14:58:51  FAILURE: Build failed with an exception.
14:58:51  
14:58:51  * What went wrong:
14:58:51  The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\jenkins\workspace\or_PR-5234\buildfiles\tool_BuildEnv\tools\jdk_x86_64\win32_1.8.0_121\bin\java.exe
14:58:51  
14:58:51  * Try:
14:58:51  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
14:58:51  
14:58:51  * Get more help at https://help.gradle.org

```

### Your Environment

```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Windows 10 10.0 amd64
```
Windows 10

**Comment by ljacomet** [comment]
This was supposed to be fixed in 7.0.1 through #16925
Maybe there is something specific to Windows that breaks the check.

Gradle will not necessarily start a new daemon if there is a running one that is compatible.

**Comment by ljacomet** [comment]
Can you confirm whether or not the folder `C:\jenkins\workspace\or_PR-5234\buildfiles\tool_BuildEnv\tools\jdk_x86_64\win32_1.8.0_121` exists when this fails?
In short, Gradle will check if the old `JAVA_HOME` folder still exists. And given the way Windows handles deletion, I am guessing that the folder is still around although it cannot be used properly.

**Comment by rompic** [comment]
what does compatible mean in this regard? (also same javaHome?)

Please don't ask me why, but the project where this happens checks out jdk from somewhere in the workspace and uses it from there. My assumption is that this happens if the e.g. the other workspace disappears (e.g. PR is merged) and the gradle daemon is still running.

**Comment by ljacomet** [comment]
There is some explanation of what is considered for daemons to be compatible in [the documentation](https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:why_is_there_more_than_one_daemon_process_on_my_machine). And for example `JAVA_HOME` is not part of it but the Java version is.

I think the easiest fix in your setup is to run builds with `--no-daemon` in your CI environment which will make sure that a daemon is single use only.

**Comment by kenyee** [comment]
FYI, this still happens on Windows 11 with Gradle 9.1.0.

The "fix" was to remove the old JAVA_HOME folder...in my case,, it was complaining that:
```
The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\Program Files\Eclipse Adoptium\jdk-17.0.16.8-hotspot\bin\java.exe
```
Removing that folder fixed the problem.  I had upgraded to temurin21 and uninstalled temurin17 via chocolatey but the folder still remained.

Leaving this here in case anyone else has this problem and hopefully Google will index this comment...
