### ISSUE TITLE
Test Hooks need a native gradle API

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#18104]
this is some copy-pasta, but from what I've found there's no clean way to do `afterSuite` and the hooks. This particular thing can be done with a listener which is a little nicer, but I'm not sure if that'll work for failing the suite.

```
  afterSuite(
    KotlinClosure2<TestDescriptor, TestResult, Unit>(
      { descriptor, result ->
        if (descriptor.parent == null) {
          logger.lifecycle("Tests run: ${result.testCount}, Failures: ${result.failedTestCount}, Skipped: ${result.skippedTestCount}")
        }
        Unit
      })
  )
```

#7452 and #5431 probably more, but, the point is this needs a native kotlin api.

**Comment by mlopatkin** [comment]
Are you asking to add a nicer overload for Kotlin DSL so KotlinClosure2 thing goes away?

**Comment by xenoterracide** [comment]
Yes, that's exactly it. Some form of nicer API, whether it's an overload or whatever, I want the KotlinClosure2 to go away.

**Comment by mlopatkin** [comment]
I'll reopen #5421 to track this work then because it has more context.

**Comment by xenoterracide** [comment]
> I'll reopen #5421 to track this work then because it has more context.

That PR has more context? Did you get the wrong number?

**Comment by mlopatkin** [comment]
>That PR has more context? Did you get the wrong number? I glanced at it, I don't even see that it references an issue ;)

Mistyped the number, fixed, thanks!

**Comment by xenoterracide** [comment]
ok, that's fine, I mean it fits the other ticket I mentioned too, but fair. Thanks!
