### ISSUE TITLE
Gradle 7.2 Version Catalog Plugins gives an IDE error "'val Project.libs: LibrariesForLibs' can't be called in this context by implicit receiver. Use the explicit one if necessary"

### ISSUE THREAD

**Issue by EdricChan03** [gradle/gradle#18107]
### Expected Behavior

Plugin libraries defined in a Version Catalog file should be accessible in the `plugins` block with no issues

### Current Behavior

Plugin libraries _are_ accessible in the `plugins` block (and the buildscript builds fine), but a red squiggly line can be seen on the `libs` part in the IDE with the error:

![Screenshot of IDE hovercard on libs](https://user-images.githubusercontent.com/20047125/130593759-6822704d-ba7e-467f-ab00-e6101511a046.png)

(Text version:)
```
'val Project.libs: LibrariesForLibs' can't be called in this context by implicit receiver. Use the explicit one if necessary
```

This [Google IssueTracker comment about the same issue](https://issuetracker.google.com/issues/195827750#comment2) points out that:

> That error comes from the Kotlin plugin. I think Kotlin wants you to refer to `libs` more explicitly using syntax like `this@<ImplicitReceiver>.libs`.

However, this syntax doesn't appear to work no matter what I've tried.

Using either version of the classes that the IDE suggests:

![Suggested classes](https://user-images.githubusercontent.com/20047125/130593153-14289d36-6695-46b1-a6b3-4c04a3a6dcd3.png)

```kts
plugins {
    alias(this@<kotlin.reflect.jvm.internal.impl.resolve.scopes.receivers.ImplicitReceiver>.libs.plugins.buildProperties)
    // OR
    alias(this@<org.jetbrains.kotlin.resolve.scopes.receivers.ImplicitReceiver>.libs.plugins.buildProperties)
}
```

Gives another error:

```
Function invocation 'this@<kotlin.reflect.jvm.internal.impl.resolve.scopes.receivers.ImplicitReceiver>(...)' expected
```
```
Function invocation 'this@<org.jetbrains.kotlin.resolve.scopes.receivers.ImplicitReceiver>(...)' expected
```

### Context

Trying to update defined build plugins to use the new Version Catalogs API for easier version management

### Steps to Reproduce 

`gradle/lib.versions.toml`

```toml
[plugins]
buildProperties = "com.novoda.build-properties:0.4.1"
```

`app/build.gradle.kts`

```kts
plugins {
    alias(libs.plugins.buildProperties)
}
```

([GitHub project](https://github.com/EdricChan03/StudyBuddy-android/tree/repro/gradle-version-catalog-plugin-error))

#### IDE

Android Studio Bumblebee | 2021.1.1 Canary 9
Build #AI-211.7628.21.2111.7653804, built on August 19, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true, documentation.show.toolbar=true
Non-Bundled Plugins: org.toml.lang (0.2.153.4056-211), org.jetbrains.kotlin (211-1.5.21-release-328-AS7442.40)

#### Build scan

URL: https://gradle.com/s/ostfhaxrfyjna

**Comment by dsvensson** [comment]
Issue is tracked in IDEA here, https://youtrack.jetbrains.com/issue/KTIJ-19369

**Comment by mlopatkin** [comment]
Looks like an IDEA/AS bug per the comment above.

**Comment by TWiStErRob** [comment]
Duplicate of https://github.com/gradle/gradle/issues/22797
