### ISSUE TITLE
How do you use allprojects to configure a plugin for your submodule?

### ISSUE THREAD

**Issue by SchlauFuchs** [gradle/gradle#18113]
Using Gradle 7.2 in a multimodule project, I was attempting to configure a plugin to be applied to all modules, configured in the root project - here the relevant block::

```
allprojects {
    apply {
        plugin("io.gitlab.arturbosch.detekt")
    }
    tasks {
        val detect = register<io.gitlab.arturbosch.detekt.Detekt>("detect") {
            autoCorrect = true
            config.setFrom(files(rootProject.relativePath("default-detekt-config.yml")))
            setSource( files(
                "*.kts", "*.gradle", "src/main/kotlin", "src/test/kotlin"
            ))
        }

        withType<KotlinCompile> {
            finalizedBy(detect)
        }
    }
}
```
### Expected Behavior
Submodules will execute the "detect" plugin after the kotlin compilation, using the configuration in the code example above, which states the configuration should be sourced from the file "default-detekt-config.yml" in the root project.

### Current Behavior
Exception is thrown: 
`Execution failed for task ':module1:detect'. > Provided path 'C:\[...]\project\**module1**\default-detekt-config.yml' does not exist!`
Either `rootProject.relativePath` is not returning the expected path in a module, or the configuration is not applied and it goes for a default configuration instead, looking in the base path of the module.

### Context
This is a refactoring attempt to centralize some configurations like managing dependencies used in the multimodule project. In previous configuration it was executing the detect plugin only in the root project, with each modules source folders listed.

### Your Environment
Windows 10
Build scan URL:

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

In this particular case, you are misusing `relativePath`. You give an already relative path to it so it is returned unchanged. Then you pass this relative path to `files` which interprets it as a path relative to the current project dir. Using `config.setFrom(rootProject.files("default-detekt-config.yml"))` instead should be enough to get a proper result.
