### ISSUE TITLE
org.gradle.ea: Property for enabling assertions

### ISSUE THREAD

**Issue by sellmair** [gradle/gradle#18126]
Currently, when executing Gradle with enabled assertions seem to be only possible by providing necessary jvmargs
`-Dorg.gradle.jvmargs=-ea`. 

However, this is might not be very convenient for integration tests, since projects often want to supply their own 'jvmargs' in their gradle.properties file which would get overwritten when providing jvmargs when starting Gradle. 

A property like `org.gradle.ea` or `org.gradle.enableAssertions` would be very helpful here.

**Comment by ljacomet** [comment]
Can you clarify where you want assertions to be enabled?
* For the JVM running Gradle? Because you run integration tests for Gradle plugins
* For test JVMs?
* Something else?

**Comment by sellmair** [comment]
Yes, of course: 
Here are the jetbrains/kotlin Gradle integration tests, where I would like to enforce that the JVM running Gradle has assertions enabled:

https://github.com/JetBrains/kotlin/blob/862d4e6ab6c555ecef154e24cf245c3b369de4c8/libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/BaseGradleIT.kt#L997

However, this is not merged, since adding this would overwrite testProjects that also would like to set jvmargs in their `gradle.properties`
