### ISSUE TITLE
Incremental compile not working Gradle 7.2

### ISSUE THREAD

**Issue by justin-michel-boeing** [gradle/gradle#18132]
I narrowed it down a bit, and it seems like something that was supposed to be working. 

If I change a private string within a XXX.java file then I see:

Skipping task ':foo:compileJava' as it is up-to-date.

However, if I instead change a "public static final String" constant in the same file then I get:

Task ':foo:compileJava' is not up-to-date because:
  Input property 'classpath' file XXX.class has changed.

This looks like the same issue described in #6482, but that was supposed to be fixed in April with #16495.

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

**Comment by oehme** [comment]
@justin-michel-boeing what exactly is the problem? Can you provide a reproducer? If a public constant changes, every class that transitively depends on it needs to be recompiled. That is normal. If something gets recompiled even though it doesn't depend on the constant in any way, that would be a bug.

**Comment by justin-michel-boeing** [comment]
I will try to find time to make an example, but maybe we can just decide that it is working as designed. 
Given a situation where I have 2 projects A and B where B depends on A:
If I add a new unused public static final String to A that B does NOT use, then B is recompiled.

This is a very common situation in our giant codebase, because B might be a test project for A, where non-test projects that use A will not use these global constants. 

The INFO message indicates that B is recompiled because classpath changed for X.class within A, but if we change a private String in the X.java file, then that class is also changed, but it doesn't force a recompile.

Maybe this just isn't solveable? Is it because the compiler will inline those Strings? Maybe we could add a compile option to avoid that or translate all public Strings into public string accessors of private Strings?

Thanks,
Justin

**Comment by oehme** [comment]
Dependency analysis is currently class based, not symbol based. If B uses A, then any change to the API of A will trigger a recompilation of B. This is unrelated to constants and applies to public methods, fields etc. too. 

We have considered going down to the symbol level (i.e. tracking each method, field, constant etc. individually) but that would significantly complicate the compiler and make the analysis files much larger. So for now I think staying class based is the right trade off.
