### ISSUE TITLE
Add automatedPublishing flag to CatalogPluginExtension like the one on GradlePluginDevelopmentExtension

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#18133]
### Expected Behavior

In a version catalog plugin project like:
```
plugins {
    id 'version-catalog'
    id 'maven-publish'
}
```
It should be possible to set:
```
catalog {
    automatedPublishing = true
}
```

As a similar behavior is implemented for the 'java-gradle-plugin' in its projects:
https://docs.gradle.org/current/javadoc/org/gradle/plugin/devel/GradlePluginDevelopmentExtension.html#isAutomatedPublishing--

Also, `automatedPublishing = true` should then be the default behavior for `version-catalog` projects.

### Current Behavior
`automatedPublishing` is not supported

### Context
current implementation requires extra boilerplate code, to explicitly declare the version catalog publication:
```
publishing {
    publications {
        maven(MavenPublication) {
            from components.versionCatalog
        }
    }
}
```

**Comment by ljacomet** [comment]
This is related to #18120 and might help convention over configuration.
