### ISSUE TITLE
add a api to create PolymorphicDomainObjectContainer with factory with name and type

### ISSUE THREAD

**Issue by anatawa12** [gradle/gradle#18143]
Currently, there's a way to create PolymorphicDomainObjectContainer with type-specific factories.
However, When I want to add a container of what has a general way to create an instance, it's not enough.
I want an API to create (Extensible)PolymorphicDomainObjectContainer with a factory with two arguments, Class and name.

### Current Behavior

Register factory for each types to ExtensiblePolymorphicDomainObjectContainer.
it's a task easy to forget.

### Context

I want to do something like `TaskContainer`.

**Comment by ljacomet** [comment]
Can you please share a use case or describe what you are trying to achieve?

**Comment by anatawa12** [comment]
I found it's enough to use TaskContainer in my use case so closing.
