### ISSUE TITLE
A convention of the property annotated with @InputFile is always resolved for disabled task

### ISSUE THREAD

**Issue by hsz** [gradle/gradle#18146]
Hey, folks! I just faced an unexpected issue with a lazy configuration.
In the [Gradle IntelliJ Plugin](https://github.com/JetBrains/gradle-intellij-plugin), I have an `IntelliJInstrumentCodeTask` task with a `javac2` property annotated with `@InputFile`:

```
@InputFile
@Optional
val javac2: RegularFileProperty = objectFactory.fileProperty()
```

This `javac2` also has some convention configured – calculated value is a bit heavyweight – and required only when the task is actually run.

Sometimes users want to disable this task through the extension: `intellij.instrumentCode = false`, and it the mentioned task, I have something like:

```
it.onlyIf { instrumentCode.get() }
```

So if the task is disabled that way, I’d expect `javac2` not to be calculated at all. However, it is!
Everything is because of the `@InputFile` annotation. If I change it to `@Input` only, `javac2`'s convention isn’t even touched.

Is that expected?

### Expected Behavior
Skip resolving conventions of properties that are not accessed.

### Current Behavior
Convention of the property annotated with `@InputFile` is always resolved for the disabled tasks.

### Context
The task is fetching extra resources from the Internet to get binaries required for its evaluation. Sometimes it is unnecessary to run that task, so folks are disabling it, but such resources are fetched anyway.

### Steps to Reproduce 
1. Clone https://github.com/hsz/gradle-convention-issue
2. Run tests

### Your Environment

Build scan URL: https://scans.gradle.com/s/5p6a5eijn25ue

**Comment by hsz** [comment]
Such a workaround makes it working as expected:

```
@Suppress("unused")
open class MyPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.tasks.register("myTask", MyTask::class.java) {
            it.myProperty.convention(project.layout.file(project.provider {

                // chect if task is disabled and skip resolving the convention
                if (!it.enabled) {
                    return@provider null
                }

                Throwable().printStackTrace()
                project.file("build.gradle")
            }))

            it.onlyIf { false }
        }
    }
}
```

**Comment by wolfs** [comment]
@hsz Yes, this is expected since Gradle needs to call the property getter to decide whether or not the task depends on other tasks. Gradle runs dependent tasks even if the current task is disabled.

**Comment by hsz** [comment]
Thanks for the answer, @wolfs. There's still one thing I can't understand – if I change the `myProperty` to a `Property<String>` with an `@Input` annotation, like:

    @Input
    @Optional
    val myProperty: Property<String> = objectFactory.property(String::class.java)

It doesn't get queried at all when the task is disabled. Why is that?

**Comment by wolfs** [comment]
> if I change the type of `myProperty` to a `Property<String>` with an `@Input` annotation, it doesn't get queried at all when the task is disabled.

Since `Property`s which are not file properties can't be task outputs, we don't query them for task dependencies. That is why we don't need to evaluate them when determining the task dependencies.

**Comment by hsz** [comment]
All right, that makes sense. Thanks for the explanation, Stefan!
