### ISSUE TITLE
VersionParser instances not reused

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#18144]
There are four locations where VersionParser instances are created. Would probably make sense for this to be globally provided so it lives between executions and back it with a LRU cache instead of a plain concurrent map:

```
subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java
645:        return new VersionParser();

subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultRepositoryContentDescriptor.java
58:        this.versionSelectorScheme = new DefaultVersionSelectorScheme(new DefaultVersionComparator(), new VersionParser());

subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/builder/ModuleSelectors.java
38:    private static final VersionParser VERSION_PARSER = new VersionParser();

subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/graph/selectors/SelectorStateResolverResults.java
36:    private static final VersionParser VERSION_PARSER = new VersionParser();
```

### Expected Behavior
VersionParser instances are reused avoiding parsing overhead on hot dependency management paths.

### Current Behavior
VersionParser instances are instantiated in several places leading to unnecessary additional parsing.

### Context
An aside: it would be _super_ useful to be able to `@Inject` the VersionParser at any scope, as we use them to implement several version related features, such as status rules, component metadata rules, etc.

### Steps to Reproduce 
None - see code references.

### Your Environment
Gradle 7.2

**Comment by abstratt** [comment]
PR has been merged. Note we did not make version parser an API yet. Also, we left it as using a concurrent hash map. 

@DanielThomas Would you be able to give it a try in your projects (will be in tonight's [nightly](https://gradle.org/nightly/)? This is scheduled for 7.6 (we are RC'ing 7.5 now), but would be nice to have some early indication on whether this brought the expected benefit. 

The PR includes a comment on how to verify it using jmap.
