### ISSUE TITLE
Provide the binary Gradle distribution as a tar.gz file

### ISSUE THREAD

**Issue by veita** [gradle/gradle#18158]
### Expected Behavior

https://services.gradle.org/distributions/ should additionally provide downloads of the binary distribution as `tar.gz`.

### Current Behavior
https://services.gradle.org/distributions/ contains ZIP files only

### Context
Unlike `tar.gz` ZIP files cannot be processed in an easy and efficient way. E.g an automated download like

```
curl https://services.gradle.org/distributions/gradle-7.2-bin.tar.gz | tar -xz
```
would extract the archive to disk while the download proceeds. No intermediate copy in memory or on disk is required. This can not be achieved with ZIP files.

Also, zip tools are not very prevalent on Linux systems.

**Comment by jbartok** [comment]
@veita Makes sense, but right now we don't have the resources to allocate to it. Will put it in our backlog.

**Comment by big-guy** [comment]
I'm going to close this issue. I don't think we should do this for a few different reasons:
- The Gradle wrapper only knows how to download zip files, so most users never need a separate distribution format.
- There are other ways to install Gradle if you can't use the wrapper (brew and sdkman to name two) and those use ZIPs
- You can get the same effect with `jar`, which anyone running Gradle will have available:

> curl -L -v https://services.gradle.org/distributions/gradle-7.2-bin.zip | jar xv
