### ISSUE TITLE
Allow Copy tasks to mark their output as untracked

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#18159]
After https://github.com/gradle/gradle/pull/18110 tasks with unreadable outputs will fail. We need an API to allow users to mark a `Copy` task as untracked to allow copying things into directories that cannot be snapshot, i.e. a directory that contains named pipes etc.

This is a different kind of fix for https://github.com/gradle/gradle/issues/9576.

The user should be able to mark the output of the `Copy` task as untracked:

```groovy
tasks.register("copy", Copy) {
    /* ... */
    destinationDir = /* ... */
    doNotTrackOutputs() // <-- This is the way
}
```

Once marked as untracked the task cannot be marked as tracked again.

**Comment by wolfs** [comment]
We decided to only add this new method to the `Copy` task and not to the `Sync` task, since it doesn't make much sense to `Sync` a directory without being able to track the state of the target directory.
