### ISSUE TITLE
Could not compile build file. Error in SDK 27.0.3

### ISSUE THREAD

**Issue by Rehan-05** [gradle/gradle#18156]
FAILURE: Build failed with an exception.

Where:
Build file 'E:\Office\LOS\reaction-apps\android\app\build.gradle' line: 144

What went wrong:
Could not compile build file 'E:\Office\LOS\reaction-apps\android\app\build.gradle'.

startup failed:
build file 'E:\Office\LOS\reaction-apps\android\app\build.gradle': 144: unexpected token: 3 @ line 144, column 31.
targetSdkVersion 27.0.3
^

1 error

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

=============================================================================
Android plugin version: 4.1.1
Gradle version: 6.7

Error in code=======>>>>>
defaultConfig {
applicationId "com.landofsneakerproject"
minSdkVersion rootProject.ext.minSdkVersion
targetSdkVersion rootProject.ext.targetSdkVersion
versionCode 1
versionName "1.0"
vectorDrawables.useSupportLibrary = true

    **targetSdkVersion 27.0.3      // here is the issue**
}
==============

![sdk](https://user-images.githubusercontent.com/72587992/131457484-be102520-897a-4348-a020-f1cf8a29d16d.PNG)

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
