### ISSUE TITLE
In version catalog libs, alias 'jme3-plugins' is not a valid alias — Works in 7.1.1, fails in 7.2

### ISSUE THREAD

**Issue by Thunderforge** [gradle/gradle#18167]
When using a version catalog, the dependency [jme3-plugins](https://mvnrepository.com/artifact/org.jmonkeyengine/jme3-plugins) can be declared in `libs.versions.toml` like so:

```toml
[versions]
jmonkeyengine = "3.4.0-stable"

[libraries]
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jmonkeyengine" }
```

And then in `build.gradle`:

```groovy
dependencies {
    implementation libs.jme3.plugins
}
```

### Expected Behavior
The dependency should resolve successfully in Gradle 7.1.1 and 7.2 because the alias `plugins` is *not* [a reserved alias name](https://docs.gradle.org/7.2/userguide/version_catalog_problems.html#reserved_alias_name) in 7.2 (although the singular `plugin` is).

If the plural `plugins` is supposed to be a reserved alias, then the documentation should reflect that.

### Current Behavior
In Gradle 7.1.1, the dependency resolves successfully and the project can be compiled.

In Gradle 7.2, the build fails with the following error:

```
org.gradle.api.InvalidUserDataException: Invalid catalog definition:
  - Problem: In version catalog libs, alias 'jme3-plugins' is not a valid alias.
```

### Context

<!--- In the rare cases where this is infeasible, we will also accept a detailed set of instructions. -→
1. Unzip [Jme3Plugins.zip](https://github.com/gradle/gradle/files/7087122/Jme3Plugins.zip)
2. From the root directory, run `gradlew build`.

It is currently set to wrapper 7.2 and fails to build with the above error. 

If you change it to wrapper 7.1.1, it will successfully build.

**Comment by jbartok** [comment]
Documentation needs to mention that plurals of reserved words are also reserved.

**Comment by melix** [comment]
I think some of the naming restrictions can be lifted now that things are namespaced.
