### ISSUE TITLE
`project.sync` is not allowing to specify `preserve` even though the `Sync` task does and the documentation explicitly mentions it

### ISSUE THREAD

**Issue by kristian** [gradle/gradle#18177]
[`Project.sync`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#sync-org.gradle.api.Action-) is documented to behave equal to the `Sync` task, explictely mentioning:

> Note that you can preserve output that already exists in the destination directory:
> ```
>  project.sync {
>      from 'source'
>      into 'dest'
>      preserve {
>          include 'extraDir/**'
>          include 'dir1/**'
>          exclude 'dir1/extra.txt'
>      }
>  }
> ```

This is not true. `Project.sync` only accepts a `CopySpec`, which does not allow to specify `preserve` patterns.

### Expected Behavior
`Project.sync` to allow specifying the same options as in the `Sync` task, e.g. by accepting a (new) `SyncSpec` instead of a `CopySpec`.

### Current Behavior
The `preserve` option of `Project.sync` is not available.

### Context
Renaming files in a directory, by preserving the files that already had been renamed.

### Steps to Reproduce 
Try calling the command that is documented in the JavaDoc of `Project.sync`:
```
project.sync {
    from 'source'
    into 'dest'
    preserve {
        include 'extraDir/**'
        include 'dir1/**'
        exclude 'dir1/extra.txt'
    }
}
```

### Your Environment
Every environment.

**Comment by tresat** [comment]
Confirmed documentation status and failure occurs as described.

![image](https://user-images.githubusercontent.com/44197/132220836-f5a1b859-a3fb-4e4c-b883-cc08f24b7c79.png)

Thank you for reporting.
