### ISSUE TITLE
Can't use a version catalogue library in `enforcedPlatform`

### ISSUE THREAD

**Issue by kezz** [gradle/gradle#18174]
### Expected Behavior

When using `enforcedPlatform` with the version catalogue system, I would expect to be able to write code like `enforcedPlatform(libs.foo.bar)`.

### Current Behavior

Instead, the following error is displayed:
```
Cannot convert the provided notation to an object of type Dependency: provider(?).
The following types/formats are supported:
  - Instances of Dependency.
  - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
  - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
  - FileCollections, for example files('some.jar', 'someOther.jar').
  - Projects, for example project(':some:project:path').
  - ClassPathNotation, for example gradleApi().
 ```

### Context

For reference, adding a `.get()` at the end (i.e. `enforcedPlatform(libs.foo.bar.get())`) will continue the build as normal without the error mentioned above.

### Steps to Reproduce 

Create a build file in which you use the `enforcedPlatform` dependency handler and pass in a version catalogue.

### Your Environment

Version: 7.2

**Comment by jbartok** [comment]
Duplicates https://github.com/gradle/gradle/issues/17849.
