### ISSUE TITLE
providers.gradleProperty to avoid invalidating the configuration cache but need to read the property at configuration time to disable the task

### ISSUE THREAD

**Issue by michaelzhon** [gradle/gradle#18186]
When using `providers.gradleProperty("some-property").forUseAtConfigurationTime().isPresent` to avoid invalidating the configuration cache but you have to read the property to disable a task. This is bad behavior as this means that if the property changes, the configuration process would be repeated. 
This should be changed so that `task.setEnabled` should also accept a `Provider<Boolean>`

### Expected Behavior
We should be able to disable the task without invalidating the configuration cache

### Current Behavior

Current behavior would invalidate the configuration cache. If configuration cache is enabled and attempts to read it without the function call it would result in a crash.

### Context

Attempting to disable tasks without invalidating the configuration cache

**Comment by bamboo** [comment]
This is still relevant.

**Comment by mlopatkin** [comment]
This is currently solvable with providers and `onlyIf` clause, but not for the gradle properties. Currently, all Gradle properties are the implicit inputs to the build configuration, so changing any invalidates the configuration cache regardless of if the property is actually used for anything. Future Gradle versions will introduce finer-grained tracking. In the meantime, you can use system property or environment variable providers:

```gradle
tasks.register("hello") {
    def taskEnabled = providers.systemProperty("sayHello")

    onlyIf { taskEnabled.present }

    doLast {
        println "Hello"
    }
}
```
