### ISSUE TITLE
 "Provisioning toolchain" is done for every build

### ISSUE THREAD

**Issue by ewirch** [gradle/gradle#18182]
On each build Gradle says to "Provisioning toolchain" for 16s. "Each" means also those build runs which should be cached, actually.

The performance view of a cached build scan says, task graph calculation is the culprit: https://scans.gradle.com/s/wu73fzbxhjtvs/performance/configuration#summary-task-graph

### Expected Behavior
A cached build should finish very quickly.

### Current Behavior
Even completely cached builds take 17s for my project.

### Context

We use the `toolchain` feature:
```
java {
    consistentResolution {
        useCompileClasspathVersions()
    }
    toolchain {
        languageVersion = JavaLanguageVersion.of(16)
        vendor = JvmVendorSpec.ADOPTOPENJDK
    }
}
```

### Steps to Reproduce 

Create a java-application Gradle project:
```
gradle init --type java-application
```

Build the project. 
```
./gradlew compileJava
```

For me it completes in 600ms.

Now add toolchain configuration:

```
java {
    consistentResolution {
        useCompileClasspathVersions()
    }
    toolchain {
        languageVersion = JavaLanguageVersion.of(16)
        vendor = JvmVendorSpec.ADOPTOPENJDK
    }
}
```

Now re-build. Now it takes 3-4s for me. Even consecutive executions, which should be cached actually.

Remove the toolchain configuration, build completes in 600ms again.

For my production project, the time difference added by `toolchain` is 16s! On each run!

**Comment by jbartok** [comment]
As a workaround try *NOT* specifying the vendor, that should help (OpenJDK migration to Eclipse Foundation is causing this problem; because this a new download is happening every time, that's where the delay is coming from). We are trying to fix it properly in future versions. See #18027.
