### ISSUE TITLE
Only first execution generates build/compilation artifacts

### ISSUE THREAD

**Issue by ebhgw** [gradle/gradle#18188]
[project.zip](https://github.com/gradle/gradle/files/7104948/project.zip)
### Expected Behavior
A second compilation/build of unmodified sources should leave untouched artifacts

### Current Behavior
A second compilation/build of unmodified artifacts removes .class file, jar files leaving only empty directories under build directory

### Context
I created a simple project via gradle init with the following command

gradle init --type groovy-library --project-name QueryEVIncident --package it.zebco.rma.noc.ev

First time I run compileGroovy I may find generated .class files under lib/build/classes/groovy/main/it...
If I run a second time, groovy will remove all directories and files under lib/build/classes/groovy

I experienced this issue with various Gradle version and projects

### Steps to Reproduce 
I attached a zip file with the project I generated.

### Your Environment
Java version is 1.8.301 (jdk)
OS is Windows 10 Pro 21H1
CPU AMD Ryzen 7
Build scan URL: https://gradle.com/s/7hmt2thgm5gvi

**Comment by jbartok** [comment]
@ebhgw Could you pls. tell us if by any chance your using an `exFAT` file system? If that's the case, then that could be the cause, because it's not supported by Gradle (due to serious issues on it). In that case the workaround would be: a) try Gradle 7.2, which fixes the issues b) if you can't upgrade, just use an `NTFS` mount point.

**Comment by ebhgw** [comment]
Hi,
thank you very much, I checked and the disk was exFAT. I moved the project to a non exFAT disk and it worked fine. This solves the issue.
By the way, in the meantime I discovered that it is possible to force compilation and generate artifacts using the --rerun-tasks.

Best regards
Evelino Bomitali
