### ISSUE TITLE
Plugin [id: 'com.gradle.internal.test-selection', version: '0.5.3-rc-1'] was not found.

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#18199]
Hi，gralde team!

I clone this repo and then I checkout `v7.1.0` tag. Now I execute `./gradlew buildE`. But I got error: 

```bash
VFS> Statistics since last build:
VFS> > Stat: Executed stat() x 0. getUnixMode() x 0
VFS> > FileHasher: Hashed 0 files (0 bytes)
VFS> > DirectorySnapshotter: Snapshot 0 directory hierarchies (visited 0 directories, 0 files and 0 failed files)
Received 0 file system events since last build while watching 0 hierarchies
Virtual file system retained information about 505 files, 52 directories and 0 missing files since last build

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/jianxinli/gradle/settings.gradle.kts' line: 12

* What went wrong:
Plugin [id: 'com.gradle.enterprise.test-distribution', version: '2.1-milestone-1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle.enterprise.test-distribution:com.gradle.enterprise.test-distribution.gradle.plugin:2.1-milestone-1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    maven(https://repo.gradle.org/gradle/libs-releases)
    maven2(https://repo.gradle.org/gradle/enterprise-libs-release-candidates-local)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 ```

So I search `com.gradle.enterprise.test-distribution` in gradle plugin store : https://plugins.gradle.org/plugin/com.gradle.enterprise.test-distribution/2.1

As you see, the version is 2.1 so I change '2.1-milestone-1' to `2.1`.

Then I execute `./gradlew buildE` again. However another crash blocked me:

```bash
VFS> Statistics since last build:
VFS> > Stat: Executed stat() x 0. getUnixMode() x 0
VFS> > FileHasher: Hashed 0 files (0 bytes)
VFS> > DirectorySnapshotter: Snapshot 0 directory hierarchies (visited 0 directories, 0 files and 0 failed files)
Received 0 file system events since last build while watching 0 hierarchies
Virtual file system retained information about 505 files, 52 directories and 0 missing files since last build

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/jianxinli/gradle/settings.gradle.kts' line: 12

* What went wrong:
Plugin [id: 'com.gradle.internal.test-selection', version: '0.5.3-rc-1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle.internal.test-selection:com.gradle.internal.test-selection.gradle.plugin:0.5.3-rc-1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    maven(https://repo.gradle.org/gradle/libs-releases)
    maven2(https://repo.gradle.org/gradle/enterprise-libs-release-candidates-local)
```

This time, I didn't find `com.gradle.internal.test-selection'` in gradle store.  I guess this plugin is your internal plugin. 

So how can I fix this crash?

**Comment by blindpirate** [comment]
This is usually due to a network failure when resolving that plugin from `repo.gradle.org`, especially builds behind GFW. It silently tries next repo instead of failing the build, thus results in confusing failure.

You need to configure your build JVM with proxy settings to bypass GFW.

**Comment by CoXier** [comment]
> This is usually due to a network failure when resolving that plugin from `repo.gradle.org`, especially builds behind GFW. It silently tries next repo instead of failing the build, thus results in confusing failure.
> 
> You need to configure your build JVM with proxy settings to bypass GFW.

However I didn't find this plugin in plugin store.

**Comment by blindpirate** [comment]
Gradle allows custom plugin to be published in private repo. Not every gradle plugin is in plugin portal.

https://repo.gradle.org/ui/native/enterprise-libs-release-candidates/com/gradle/internal/test-selection-gradle-plugin/0.5.3-rc-1

Note: being able to access this url in browser DOESN'T mean it's accessible for JVM. You'd better configure proxy for JVM.
