### ISSUE TITLE
IDEA/Eclipse plugins aren't downloading sources when mavenLocal() is used

### ISSUE THREAD

**Issue by mjustin** [gradle/gradle#1819]
This is a transfer of [GRADLE-2832](https://issues.gradle.org/browse/GRADLE-2832) from JIRA (originally from a post in the [Gradle Forums](https://discuss.gradle.org/t/idea-plugin-isnt-downloading-sources-when-mavenlocal-is-used/2160)).  I'm running into this issue myself, and I see that nobody has advocated for the issue, so it didn't get transferred to GitHub.  An identical issue was mentioned in regards to the Eclipse plugin in [a different forum post](https://discuss.gradle.org/t/eclipse-plugin-not-downloading-source-if-jar-found-in-mavenlocal/2182/4).

The problem occurs when the mavenLocal() repository does not have the source JAR, but another repository declared after it does.  In this case, the IDEA/Eclipse plugin will not search any of the later repositories for the artifact sources.

Per the comments on the forums, the crux of the issue seems to be that Maven tools treat the local repository differently than Gradle does.  Namely, the Maven tools will recognize that when only some of the artifacts are in the local repository, it should fetch the others when needed.  Gradle, on the other hand, appears to treat the local repository the same as any other repository: if the artifacts aren't there, then it doesn't bother checking elsewhere for them.

Here is a simplified version of the example from the old IDEA ticket:

```
apply plugin: 'maven'
apply plugin: 'idea'

repositories {
        mavenLocal()
        mavenCentral()
    }
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
```

I should note that I'm having this issue within IDEA itself, and not using the plugins as part of the build.  I'm guessing that this issue has the same cause as the plugin issue, though I haven't thoroughly investigated whether that's the case.

**Comment by AlexCzar** [comment]
Is there any progress or comment for this? The issue is extremely annoying and forces to change order of repositories each time before and after downloading needed sources. Also for security sensitive projects it may be a security issue, since by making public repository first one to check names of internal dependencies may be exposed to it.

**Comment by mjustin** [comment]
While this isn't the most upvoted issue ever, it looks like there is still some interest from the community other than myself in seeing this resolved.

**Comment by reinhapa** [comment]
Our company is in the transition of the old build system to Gradle and most of our developers use Eclipse this is one of the most annoying problems our developers also run into. A change of the behaviour would be great here.

**Comment by mjustin** [comment]
I don't think it was the case when the issue was originally filed, but the [Gradle documentation](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local) now states that `mavenLocal()` should generally not be used as a repository, with a few exceptions that should be carefully configured.  I think the right answer if possible is to switch your builds to no longer use `mavenLocal()`, or to configure it to only narrowly be used in the contexts where it's necessary.

> As a general advice, you should avoid adding `mavenLocal()` as a repository. There are different issues with using `mavenLocal()` that you should be aware of:
> 
> * Maven uses it as a cache, not a repository, meaning it can contain partial modules.
>   * For example, if Maven never downloaded the source or javadoc files for a given module, Gradle will not find them either since it searches for files in a single repository once a module has been found.
> * As a local repository, Gradle does not trust its content, because:
>   * [...]
> * To mitigate the fact that metadata and/or artifacts can be changed, Gradle does not perform any caching for local repositories
>   * [...]
> 
> There are a few cases where you might have to use `mavenLocal()`:
> * For interoperability with Maven
>   * For example, project A is built with Maven, project B is built with Gradle, and you need to share the artifacts during development
>   * It is always preferable to use an internal full featured repository instead
>   * In case this is not possible, you should limit this to *local builds only*
> * For interoperability with Gradle itself
>   * In a multi-repository world, you want to check that changes to project A work with project B
>   * It is preferable to use composite builds for this use case
>   * If for some reason neither composite builds nor full featured repository are possible, then `mavenLocal()` is a last resort option
> 
> After all these warnings, if you end up using `mavenLocal()`, consider combining it with a repository filter. This will make sure it only provides what is expected and nothing else.

**Comment by ljacomet** [comment]
Sorry for the late reply

This is the intended behavior, and there is no plan to change it. Therefore, this issue will be closed.

***

See [documentation](https://docs.gradle.org/current/userguide/supported_repository_types.html#sec:case-for-maven-local)
