### ISSUE TITLE
[TYPESAFE_PROJECT_ACCESSORS] Allow custom name

### ISSUE THREAD

**Issue by RinOrz** [gradle/gradle#18201]
Maybe like this
```kotlin
accessorsName = "otherProjects"
```
or something

**Comment by jbartok** [comment]
Could you pls. detail a bit what you are trying to achieve? Are you trying to rename a specific project or the accessor root ("projects")?

**Comment by RinOrz** [comment]
> accessor root ("projects")

Yep, I want to rename it to another name

**Comment by jbartok** [comment]
We don't really see why anybody would need such a rename. Could you pls. explain a bit more why you need such a thing?

**Comment by RinOrz** [comment]
`projects` conflicts with the extension name of my existing plugin.

**Comment by jbartok** [comment]
Sorry, but atm we can't dedicate resources to make this possible. We would recommend you use a different extension name in your plugin.
