### ISSUE TITLE
Why TestOptions incompatible when gradle api  changed  from 4.0.1 to 7.01 

### ISSUE THREAD

**Issue by kumarjitendra** [gradle/gradle#18203]
### Expected Behavior
For Gradle api 4.0.1  
**TestOptions**  import `com.android.build.gradle.internal.dsl`
But for gradle api 7.0.1 
**TestOptions**  import `com.android.build.api.dsl.TestOptions'` which is marked unstable with @Incubating

functionality of TestOptions.UnitTestOptions should be same 

### Current Behavior
because of change of package from 
`com.android.build.gradle.internal.dsl `
to 
`com.android.build.api.dsl.TestOptions`
it's not possible to implement below code 
```
@Suppress("UNCHECKED_CAST")
private fun TestOptions.UnitTestOptions.all(run: Test.() -> Unit) = all(closureOf(run) as Closure<Test>)
```

### Context
Ultimately I want to implement below chunks of code 
// TODO: Not compatible when updated the AGP version from 4.0.1 to 7.0.1 
```
        testOptions {
           unitTests.all {
                jacoco {
                    isIncludeNoLocationClasses = true
                }
            }
        }
```
Here I would like to specify option for how the Android plugin should run local and instrumented tests.

### Your Environment
------------------------------------------------------------
Gradle 7.0.1
------------------------------------------------------------

Build time:   2021-05-10 16:08:58 UTC
Revision:     67e618faef187783dadd03a34fdab9dc71b85b19

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.12 (Oracle Corporation 11.0.12+8-LTS-237)
OS:           Mac OS X 11.5 x86_64

Build scan URL: 
https://scans.gradle.com/s/rzc5yxrxewqac/activate

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
