### ISSUE TITLE
Add operation descriptor to `Configure project` build operation and distinguish it from cross-project configuration

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1821]
This build operation is missing a descriptor containing details about the project it is configuring. See:

https://github.com/gradle/gradle/blob/713722271465d82f3ea888b46bbde68a36134275/subprojects/core/src/main/java/org/gradle/api/internal/project/BuildOperationProjectConfigurator.java#L142-L145

A possible candidate is the `ProjectDescriptor` object. We would need to pass the descriptor into the `DefaultProject` at creation time. Currently, we pass `projectDescriptor.getName()` and `projectDescriptor.getProjectDir()`. We could replace that with passing the complete descriptor.

https://github.com/gradle/gradle/blob/c8143c9bcf412a2d19053b8c926c7787c1dc8087/subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectFactory.java#L41-L41

And make the descriptor accessible. 

E.g.: 
`BuildOperationDetails.displayName(name).operationDescriptor(project.getProjectDescriptor())`

We should probably work with an immutable copy/snapshot of the `ProjectDescriptor`.

**Comment by adammurdoch** [comment]
I would add a new type that exposes only the information that the consumers need.

**Comment by oehme** [comment]
Merged
