### ISSUE TITLE
Latest nightly realize `:clean` task on no-op build

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#18214]
### Expected Behavior

The clean task should not be realized on a no-op build, e.g. calling `help`.

### Current Behavior

The clean task is realized when invoking Gradle on `help` task.

### Context

The Well-behaving plugin tests in Nokee project are failing only for the latest nightly Gradle. Given the failure only happen on JNI library plugin, I'm assuming it has to do with some of the core JVM plugins.

### Your Environment

Build scan URL: https://scans.gradle.com/s/mxuzmiof7sszq/tests/:platformJni:functionalTestLatestNightly/dev.nokee.platform.jni.JniLibraryWellBehavedPluginTest/does%20not%20realize%20all%20possible%20tasks?top-execution=1

**Comment by lacasseio** [comment]
I haven't debugged any further as without any changes the tests for the latest GA (7.2) and minimum supported version (6.2.1) all succeed. It is almost certain the bug slipped in a recent commit on the Gradle side.

**Comment by lacasseio** [comment]
The same behaviour can be seen on all three major OS:
- Windows: https://scans.gradle.com/s/mxuzmiof7sszq/tests/failed
- macOS: https://scans.gradle.com/s/qfo5ypbhp6z4o/tests/failed
- Linux: https://scans.gradle.com/s/hfur7rae2qdjg/tests/failed

**Comment by lacasseio** [comment]
It seems like the behaviour is outlined here: https://github.com/gradle/gradle/blob/f1be77b1b0661db9cb83e5bf340b0e59a961d780/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/WellBehavedPluginTest.groovy#L135-L136

However, we can confirm that it's only failing on the latest nightly (7.3). The latest GA (7.2) works without issues.

**Comment by lacasseio** [comment]
Testing against nightly (7.3-20210921225821+0000) and GA (7.2), using the following build script:

```
plugins {
	id 'dev.nokee.jni-library' version '0.4.0'
}

tasks.configureEach {
	println "realizing $it"
}
```

We can see the `clean` task being realize in latest nightly and not in latest GA.

#### Latest nightly
```
$ ./gradlew help       
realizing task ':help'
realizing task ':clean'

> Task :help

Welcome to Gradle 7.3-20210921225821+0000.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see more detail about a task, run gradlew help --task <task>

To see a list of command-line options, run gradlew --help

For more detail on using Gradle, see https://docs.gradle.org/7.3-20210921225821+0000/userguide/command_line_interface.html

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 4s
1 actionable task: 1 executed
```

#### Latest GA

```
$ ./gradlew help
realizing task ':help'

> Task :help

Welcome to Gradle 7.2.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 648ms
1 actionable task: 1 executed
```

**Comment by big-guy** [comment]
@lacasseio We're going to keep this behavior. In previous releases, this same thing happened if any task to be executed had outputs. The reason for this happening may be removed in the future, but it's tied into output clean up and isn't something we're going to change soon.
