### ISSUE TITLE
Issue with applying plugins when `buildSrc` exists

### ISSUE THREAD

**Issue by vvb2060** [gradle/gradle#18216]
https://github.com/vvb2060/gradle_bug

### Expected Behavior
`./gradlew` command executed successfully.

### Current Behavior
build.gradle.kts
```
plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("plugin.parcelize")
    kotlin("kapt")
}
```
Command Output
```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.plugin.parcelize', version: '1.5.30']
> Failed to apply plugin 'org.jetbrains.kotlin.plugin.parcelize'.
   > Extension with name 'android' does not exist. Currently registered extension names: [ext, kotlin, kotlinTestRegistry]
```

### Context
I use `pluginManagement` to manage plugins, and `buildSrc` to avoid duplicate configuration of submodules.

### Steps to Reproduce 
git clone https://github.com/vvb2060/gradle_bug
cd gradle_bug
./gradlew

### Your Environment
GitHub Actions: https://github.com/vvb2060/gradle_bug/actions/runs/1208814124

**Comment by jbartok** [comment]
Does changing the order of the plugins fix the issue? Also, could you try one of the latest nightly builds (https://gradle.org/nightly/)?

**Comment by vvb2060** [comment]
https://github.com/vvb2060/gradle_bug/commit/f66cd10a55d33021538c28cce23210161b7db5e8 Fixed! Thanks!
