### ISSUE TITLE
The Kotlin-DSL in a Java project causes Maven-publish to publish bad Request 400

### ISSUE THREAD

**Issue by SirZhao** [gradle/gradle#18224]
### Expected Behavior
I added the Kotlin-DSL plugin to my Java project, and when I publish, I don't want it to do multiple uploads, it causes bad Request 400

The Kotlin-DSL plug-in is removed from the Java project and works fine

<img width="360" alt="expect" src="https://user-images.githubusercontent.com/19420535/132440312-1be21a2c-c0a1-4151-b0c0-0ec3bbcc6554.png">

### Current Behavior
<img width="395" alt="current" src="https://user-images.githubusercontent.com/19420535/132440365-b3acfca9-312c-4f17-b17d-a4304debd3f4.png">

### Context
I want to upload the jar to Maven

### Steps to Reproduce 

Create the Java Library using Android Studio

plugins {
    `java-library`
    `kotlin-dsl`
    `maven-publish`
}

### Your Environment
Gradle 7.0.2
Android Studio Arctic Fox | 2020.3.1 Patch 2
Mac

**Comment by jbartok** [comment]
The `kotlin-dsl` plugin is for writing plugins in Kotlin. Are you sure that's what you are trying to do, or you just want to build a kotlin project? We suspect what you need is Kotlin's Gradle plugin: https://kotlinlang.org/docs/gradle.html

**Comment by SirZhao** [comment]
> The `kotlin-dsl` plugin is for writing plugins in Kotlin. Are you sure that's what you are trying to do, or you just want to build a kotlin project? We suspect what you need is Kotlin's Gradle plugin: https://kotlinlang.org/docs/gradle.html

I created the Android Studio Plugin project and used Kotlin instead of Groovy,so I used Kotlin-Dsl

**Comment by SirZhao** [comment]
I created the Android Studio Plugin project and used Kotlin instead of Groovy,so I used Kotlin-Dsl

**Comment by SirZhao** [comment]
> The `kotlin-dsl` plugin is for writing plugins in Kotlin. Are you sure that's what you are trying to do, or you just want to build a kotlin project? We suspect what you need is Kotlin's Gradle plugin: https://kotlinlang.org/docs/gradle.html

I created the Android Studio Plugin project and used Kotlin instead of Groovy,so I used Kotlin-Dsl

**Comment by ljacomet** [comment]
You do not need the `kotlin-dsl` plugin to use the Gradle Kotlin DSL.
That plugin should be named otherwise but as indicated above is only required if you want to develop a _Gradle plugin_ in Kotlin.
