### ISSUE TITLE
Ignore empty directories on Java sourcepath compile option

### ISSUE THREAD

**Issue by guylabs** [gradle/gradle#18228]
The `sourcepath` compile option is missing the `@IgnoreEmptyDirectories` annotation to ignore empty directories. This improves cacheability when empty folders are included in a dirty local environment.

### Expected Behavior
Empty directories in the `sourcepath` inputs must be ignored for cache key computation.

### Current Behavior
Empty directories in the `sourcepath` inputs are taken into account for cache key computation.

### Context
We get build cache misses on compile tasks when empty directories are existent in the defined `sourcepath`.

### Steps to Reproduce 
See the linked pull request which has an integration test.

**Comment by wolfs** [comment]
Fixed via #18223.
