### ISSUE TITLE
 Gradle 7.1 + IntellJ Ultimate 2021.2.1 -> Error: could not find or load main class while running java application on usb / removable drive.

### ISSUE THREAD

**Issue by BBArikL** [gradle/gradle#18225]
### Expected Behavior
Gradle should build and run the java application on any drive.

### Current Behavior
Error: could not find or load main class: <main_class_name> , when running project from a removable drive (USB).

### Context
Every time I try to run my Java application which is stored on a removable drive (usb, FAT32), I get this message. Same project works great on main drives (NTFS).

### Steps to Reproduce 
1. Create a new Gradle project with SDK 14 on a removable drive / USB on IntellJ Ultimate edition 2021.2.1 . (Not tested with other IDEs)
2. Create package and main class.
3. Add the correct class name to the build.gradle options file.
4.  Run the gradle task to run the application.
5. First time should work.
6. Retry.
7. Gradle cannot find the main class.
8. All tasks works (even build), but not run.

#### Workaround 1
1. Modify the main class name **in the build.gradle options file** to anything you want.
2. Run the gradle task to run the application.
3. Gradle cannot find the main class (Expected since we changed the main class name in the options).
4. Modify the main class name **in the build.gradle options file** to the correct class name.
5. Step 2.
6. It works. Spoiler: Retrying after gives the same error and it is back to step 1.

Problem: Inconvenient when wanting to test code effectively.

#### Workaround 2:
1. Put project on main drive.

Problem: Inconveniant when project needs to be constantly accessed and moved on different computers which don't have necessarily internet connection available (No git project then). Putting the project on the desktop main drive ruins the portability of said project.

### Your Environment
Windows 10
Intellj IDEA Ultimate 2021.2.1
Gradle 7.1

Build scan URL: <Would post if the scan was not that much invasive into unecessary data collection (ex: IP, Usernames, etc..)>

**Comment by jbartok** [comment]
Should be fixed in 7.2, pls. give that a try. If the problem persists, pls. reply here.

**Comment by jbartok** [comment]
Fixed in #17551
