### ISSUE TITLE
Precompiled Kotlin DSL scripts fix the JVM target to 8

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#18227]
### Expected Behavior
Precompiled Kotlin DSL scripts should allow configuring the JVM target, by setting it in the `kotlin-dsl` target instead of hardcoding it in the precompiled script templates (like [here](https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt#L46)).

### Current Behavior
Precompiled script templates hardcode the JVM target for all precompiled scripts to 8.

### Context
Being able to optionally target JVM 11 is gradually becoming more relevant as more and more libraries switch their JVM target to 11.

**Comment by eskatos** [comment]
Hi Cesar,

`KotlinInitScript`, `KotlinSettingsScript` and `KotlinBuildScript` are templates for the build scripts.
The templates for precompiled script plugins are in [PrecompiledScriptTemplates.kt](https://github.com/gradle/gradle/blob/205f18c704f2b4a7ab394e7251c54a35becfdc3b/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/precompile/v1/PrecompiledScriptTemplates.kt) and they don't enforce any `jvmTarget`.

Here is a precompiled script plugin using Java 11 opened in IDEA:

![Screenshot_20220602_111541](https://user-images.githubusercontent.com/132773/171598003-a897d9e5-3063-4870-bdff-58a665841d6c.png)

The build configuration contains:
```kotlin
plugins {
    `kotlin-dsl`
}

kotlinDslPluginOptions {
    jvmTarget.set("11")
}
```

We were missing some test coverage for setting jvmTarget to something else than 8, added in https://github.com/gradle/gradle/pull/20907.

I'm going to close this issue as invalid. Please open another one with a reproducer if you encounter any issue using precompiled scripts with other `jvmTarget` than 8.

**Comment by cesar1000** [comment]
Ohhh that's excellent. Thanks, Paul!

**Comment by cesar1000** [comment]
I run into a tangentially related issue when referencing JVM11 utilities from my `build.gradle.kts`. Reported in #21041.
