### ISSUE TITLE
Remove internal `:logging` project class leakage 

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#1824]
### Expected Behavior
No internal class from `:logging` project is leaked in the public API (`DefaultTask`).

### Current Behavior
These types are leaked in the public API:
- [ ] logging/src/main/java/org/gradle/logging/LoggingManagerInternal.java
- [ ] logging/src/main/java/org/gradle/logging/ProgressLoggerFactory.java
- [ ] logging/src/main/java/org/gradle/logging/StandardOutputCapture.java
- [ ] logging/src/main/java/org/gradle/logging/StyledTextOutputFactory.java

### Context
See issue https://github.com/gradle/gradle/issues/1723

**Comment by adammurdoch** [comment]
Should also include all the other internal types that leak via `DefaultTask`.
