### ISSUE TITLE
Add documentation to user manual for test suite API

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#18241]
## DSL reference
- Add a new section to subprojects/docs/src/docs/dsl/dsl.xml for "Test types"
- Include the Test task, TestSuite, JvmTestSuite, TestSuiteTarget, JvmTestSuiteTarget and TestingExtension
- For each type above, create a <FQCN>.xml in subprojects/docs/src/docs/dsl. Look at the other files in that directory to get an idea of what the format is.
- For each type, you'll need to define the properties and methods we want to expose as part of the DSL. 

## User manual
I think the majority of your changes will need to be done in two places:
- https://docs.gradle.org/nightly/userguide/test_suite_plugin.html
- https://docs.gradle.org/current/userguide/java_testing.html

For test_suite_plugin, I think we should rename this to match the plugin id (jvm-test-suite) and expanded to contain a few things. Take a look at the [checkstyle plugin](https://docs.gradle.org/nightly/userguide/checkstyle_plugin.html) for what we're looking for.
- Usage: we can show how to apply it, but also say it's automatically applied with the Java plugin.
- Tasks: we only create a `test` task automatically and a task of type `Test` for every test suite target in each test suite.
- Project layout: I think this doesn't need to be mentioned. It's a little hard to describe since it's going to look a lot like the Java plugin's chapter.
- Dependency management: I think this doesn't need to be mentioned.

The Checkstyle plugin has a "Configuration" section, but I think we should split this up a bit:
- Terminology/modeling (explaining what the different parts of the model are, you can pull from the design spec for this)
- Configuration examples. 
    - Users can add new test suites (which imply certain other things are created)
    - Users can configure the built-in "test" test suite
    - Users can configure dependencies for a test suite
    - Users can configure source directories for a test suite
    - Users can configure the test task for a test suite target
- I think we also need to call out how useJUnit/useJUnitJupiter is different from the Test level methods that look similar. These methods 1) automatically add dependencies and 2) configure the Test task. 

For java_testing, the big problem with this chapter is that it's super `Test` task focused. We need to eventually get to a point where we describe things as a higher abstraction layer than individual properties on a task, but we don't need to do this first. I think that means we put most of the new stuff in the new chapter about the plugin (above) and link to this chapter in a NOTE block as a new feature.  We can do that from the top of the chapter and "Configuring integration tests". 

We also have some references to setting up functional/integration tests for Gradle plugins. For now, I think we should leave those examples as-is because the new APIs are incubating and may change; however, I think we should provide breadcrumbs back to the new documentation/test suites by linking back to java_testing and explaining that Gradle plugins are just Java projects ultimately. Take a look at these two chapters and see where that would best fit in. 

- https://docs.gradle.org/current/userguide/test_kit.html#example_automatically_injecting_the_code_under_test_classes_into_test_builds
- https://docs.gradle.org/current/userguide/testing_gradle_plugins.html#modeling_test_types

I think we should be proactive in trying to avoid confusion around the very similar useJUnit methods. I took a stab at [updating the documentation in Test](https://github.com/gradle/gradle/pull/18326). I think we can try to explain this in a section in the java_testing chapter.

## Samples

Tom's done a good job with updating the samples with his init changes, so I don't think we'll need dedicated samples created for anything. When updating the user manual, you can create any snippets as you need them or reuse parts of our samples.

## Testing/building documentation locally

You should sanity check the documentation by running `./gradlew docs:serveDocs` and going to localhost:8008 to look around when it's ready (the build will not complete).

**Comment by DPUkyle** [comment]
Starting progress on this now
