### ISSUE TITLE
GC overhead limit exceeded after upgrade from 6.6 to 7.2.

### ISSUE THREAD

**Issue by SheliakLyr** [gradle/gradle#18255]
### Expected Behavior
I expected the build to finish successfully on version 7.2, or require only a minor increase in heap size.

### Current Behavior
Build fails with `GC overhead limit exceeded`.  I can also see some related messages in the logs: `Expiring Daemon because JVM heap space is exhausted`.

### Context
I"ve upgraded my build from gradle 6.6 to 7.2. Some minor changes were required (mostly compile -> api/implementation). My project is very large, contains hundreds of modules and uses Scala as its primary language.

After the upgrade, I cannot build my project. I have the following settings:
{code}
org.gradle.jvmargs=-Xmx2600m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.priority=low
org.gradle.workers.max=2
{code}

I tried increasing Xmx slightly (to 3000m) and the problem still occurs. Looking at the heap dump (cannot provide it, sorry), I can see very large caches that hold a lot of `SerializableFileCollectionFingerprint`s. The biggest one of those caches weights over 850MB. It has a max size set to 33100 (when XMX=3000m), but holds only ~5000 records. I would like to limit its size to sub-1000, but from what I can see it is scaled to XMX and cannot be manually operated.

I use a bunch of plugins. I suspect that jar building by biz.aQute.bnd:biz.aQute.bnd.gradle might put some pressure on memory, as OOM usually happens during "jar" tasks. Also, heap dump analysis shows that a lot of those `SerializableFileCollectionFingerprint`s refer to classfiles (which are the inputs of the "jar" task).

### Steps to Reproduce 
Very difficult, but I can apply some fixes locally and test them if needed.

**Comment by SheliakLyr** [comment]
FYI: Build finally passed with -Xmx4000m -> gradle 7.2 requires 53% more memory then 6.6.

**Comment by ljacomet** [comment]
@gradle/execution Can you take a look?
Wondering if you have other reports along those lines.

**Comment by SheliakLyr** [comment]
Some additional info:
![Zrzut ekranu z 2021-09-13 15-49-12](https://user-images.githubusercontent.com/6319267/133096329-fccf4149-6919-488d-8944-1a7eb204de2c.png)
![Zrzut ekranu z 2021-09-13 15-49-01](https://user-images.githubusercontent.com/6319267/133096334-4cfa8da4-f58b-423e-bf80-1c911a3f2dbe.png)

Interesting facts:
 - hashes take A LOT of space
 - fingerprints for the 'classpath' property in ScalaCompile are very big. Sometimes, this collection contains over 70000 records.

**Comment by wolfs** [comment]
@SheliakLyr Thank you for reporting. I currently need more information to understand what is going on.

It would be good if you could find out which Gradle version introduced the breakage. So it would be very helpful if you could try out Gradle 6.7, 6.8, 7.0 and 7.1 as well and see if the build also uses a big amount of memory with these versions. Another thing you could try is to turn of file system watching with Gradle 7.x by using the `--no-watch-fs` command line flag and see if that changes something. Or turn on file system watching with Gradle 6.x by using `--watch-fs`.

**Comment by SheliakLyr** [comment]
@wolfs Tracking this problem is very difficult. My results are very non-deterministic. Even with 6.7, build sometimes throws an OOM exception when daemon is reused (for this reason we disable gradle daemon on all our CI servers). State of the build cache is very important and greatly influences the results. Using --no-build-cache somehow lessens the problems (maybe those hashes are not computed/stored?), so I cannot disable the build cache in order to have more deterministic results.

Still, I am pretty sure, that the problem was introduced between 6.9 (last ok) and 7.0. I tested both of those versions with the following settings:
```
org.gradle.jvmargs=-Xmx2700m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.priority=low
org.gradle.workers.max=2
org.gradle.cache.reserved.mb=1000
org.gradle.vfs.watch=false
```

Sometimes, build on 7.0 succeeds. Running it again with some small changes to the code base (which invalidates build cache) on the same daemon will almost always result in a failure due to OOM.

7.0 is also the first version in which I can see o lot of memory being allocated to `SerializableFileCollectionFingerprint`s. I still think that those caches are incorrectly sized. In one scenario, I set Xmx to 3GB and the cache with `SerializableFileCollectionFingerprint`s grew to almost 1GB. 

Whould you be willing to accept a simple fix that allows one to customize this cache?

**Comment by SheliakLyr** [comment]
I have built gradle with the following fix: https://github.com/SheliakLyr/gradle/commit/03c4a6789b7e5374806764757782f314d1613f65

This change seems to solve the issue. Max weight of the cache drops to 1400 (500 is scaled to 1400 by cache sizer), cache hits the max size and entries can be evicted.

**Comment by SheliakLyr** [comment]
The proposed solution in MR had some problems, but after some additional digging I managed to find a solution. Just add the option following:
`-Dorg.gradle.java.compile-classpath-packaging=true`.

This issue can be closed. It might useful to add this workaround to documentation. I think it is necessary for very large builds.

**Comment by SheliakLyr** [comment]
No, I was testing exclusively on Linux (Arch). I might have seen that article but chose to ignore it because of "windows" label. 

In my case, this setting is absolutely necessary. Currently I am using Xmx=3700m for my gradle build. Without ```compile-classpath-packaging=true``` that build fails with OOM for much larger heaps (5GB and more) and is very unstable.
