### ISSUE TITLE
[feature request] @SuppressDepricationWarning or @SuppressWarning for specific line/operation

### ISSUE THREAD

**Issue by paulvi** [gradle/gradle#18266]
Gradle 7.2 and before can give warning

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

```

I did, learned there is exactly one problem,
e.g. `jcenter` deprecation,
commented within `build gradle` for that line

But the default build still gives me 

> Deprecated Gradle features were used in this build,  

And I don't if and when newly added line produce one more 

### Expected Behavior

I'd like to be able to suppress warning or deprecation warning for specific line. 
(e.g. using something line annotation @SuppressDepricationWarning or @SuppressWarning ), 
so that specific warning would not appear by default, and so there would not be that deprecated feature section several line,  

but that I would get that warning section when new build script line introduce some other outdated features.

### Current Behavior

Currently there is no way to customize that.

### Context

https://stackoverflow.com/questions/69133878/how-to-suppress-gradle-warning-about-deprecated-gradle-features

**Comment by jbartok** [comment]
You could get rid of the warning by accommodating it, ie. replace the `jcenter` method with a maven repository pointing to the jcenter URL. (We won't allow to silence the deprecation, its purpose is precisely to get you to update something that will end up not working at all at a later point in time.)

**Comment by jayanmn** [comment]
The requirement in this case may sound narrow but could have helped in some other places.  We are migrating from 6.9 to 7.2. Ability to suppress certain  class of deprecation could help in keeping build clean
 (the feature request looks very close to what intellij does)
