### ISSUE TITLE
JavaCompile ignores custom `-sourcepath` since 7.0

### ISSUE THREAD

**Issue by TheMrMilchmann** [gradle/gradle#18262]
The `-sourcepath` specified in `CompileOptions` for a `JavaCompile` task seems to be ignored starting in Gradle 7.0.

### Expected Behavior

Up to Gradle 6.9.1, the custom source path was passed to the compiler as expected.

### Current Behavior

Starting with 7.0, the task fails with and running with debug logging enabled reveals that `-sourcepath D:\GW2ToolBelt\GW2ML\src\main\java-jdk9` is used instead of `-sourcepath D:\GW2ToolBelt\GW2ML\src\main\java;D:\GW2ToolBelt\GW2ML\src\main\java-jdk9`.

### Context

I ran into this issue while updating from Gradle 6.8.2 to 7.2 in a project that uses a custom `compileJava9` task to compile a module descriptor for a multi-release jar:

```kotlin
val compileJava9 = create<JavaCompile>("compileJava9") {
    destinationDirectory.set(File(buildDir, "classes/java-jdk9/main"))

    val java9Source = fileTree("src/main/java-jdk9") {
        include("**/*.java")
    }

    source = java9Source
    options.sourcepath = files(sourceSets["main"].java.srcDirs) + files(java9Source.dir)

    classpath = files()

    options.release.set(9)

    afterEvaluate {
        options.compilerArgs.add("--module-path")
        options.compilerArgs.add(compileJava.get().classpath.asPath)
    }
}
```

The full project is available at https://github.com/GW2ToolBelt/GW2ML/tree/f7fa2104772345f249ad1d28199376aff7391545.

### Steps to Reproduce 

1. Clone https://github.com/GW2ToolBelt/GW2ML
2. Run `gradlew compileJava9 --debug`

**Comment by asodja** [comment]
Something like that should fix it:
```
+++ b/build.gradle.kts
@@ -65,12 +65,7 @@ tasks {
     val compileJava9 = create<JavaCompile>("compileJava9") {
         destinationDirectory.set(File(buildDir, "classes/java-jdk9/main"))
 
-        val java9Source = fileTree("src/main/java-jdk9") {
-            include("**/*.java")
-        }
-
-        source = java9Source
-        options.sourcepath = files(sourceSets["main"].java.srcDirs) + files(java9Source.dir)
+       source = (files(sourceSets["main"].java.srcDirs) + files("src/main/java-jdk9")).asFileTree
 
         classpath = files()
```

**Comment by asodja** [comment]
@TheMrMilchmann can you explain the use case, why you decided to use `options.sourcepath` and not `source` for JavaCompile? I would like to understand the use case and what is correct way of handling it.

**Comment by TheMrMilchmann** [comment]
I'm not sure if I recall all issues that factored into this decision but I do remember that there were several issues when using `source`. One important effect of specifying these files in `options.sourcepath` instead of `source` is that the compiled results include just the compilation results of the files present in the actual "Java 9"-specific sources. Additional required files are silently compiled by javac. (It is actually fairly tricky to track which source file a class belongs to which makes creating the actual archive non-trivial.)
Also, now that I'm reading the spec again, I think that the output could potentially reuse the compilation results from the "common" compilation if they were added to the classpath. This could be especially useful when working with larger projects that don't want to recompile everything just to build a handful of version-specific classes for MR jars. (I'll have to experiment some more once this issue is fixed.)

**Comment by tbroyer** [comment]
Fwiw, `sourcepath` is overwritten in `JavaCompile#createSpec` when building a module: https://github.com/gradle/gradle/blob/6cba9aaa19d95b050ea0a39399ca2a285f2d36f8/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L298-L300
So it looks like the "culprit" is the change of `inferModulePath`'s default from `false` to `true` in Gradle 7.0, and indeed adding `modularity.inferModulePath.set(false)` to the task fixes the build.
