### ISSUE TITLE
3.5 regression: org.gradle.parallel=false still enables parallel build

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1827]
### Expected Behavior
Same as 3.4, `-Dorg.gradle.parallel=false` should have parallel off

### Current Behavior
Currently, users must omit `-Dorg.gradle.parallel` or set `-Dorg.gradle.parallel=` (empty) to ensure it's off

### Context
https://discuss.gradle.org/t/org-gradle-parallel-false-triggers-parallel-build-in-gradle-3-5/22331

### Steps to Reproduce (for bugs)
Set `org.gradle.parallel=false` in `gradle.properties`. 

### Your Environment
 * Build scan URL: https://e.grdev.net/s/jscu36nndzjka/switches

**Comment by lacasseio** [comment]
The current workaround is to use `org.gradle.parallel=` instead of `org.gradle.parallel=false`.

**Comment by w25r** [comment]
Fixed with #1828
