### ISSUE TITLE
Build failed by Gradle7.1.1

### ISSUE THREAD

**Issue by scientificCommunity** [gradle/gradle#18283]
Hi,  Gradle team!

I have cloned this repo and then check out the v7.1.1 tag. But I got an error as follows when I execute ./gradlew build.
```
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/xxx/IdeaProjects/gradle/settings.gradle.kts' line: 12

* What went wrong:
Plugin [id: 'com.gradle.enterprise.test-distribution', version: '2.1-milestone-1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle.enterprise.test-distribution:com.gradle.enterprise.test-distribution.gradle.plugin:2.1-milestone-1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    maven(https://repo.gradle.org/gradle/libs-releases)
    maven2(https://repo.gradle.org/gradle/enterprise-libs-release-candidates-local)
```
then I try to execute ./gradlew -Dhttp.proxyHost=xxx -Dhttp.proxyPort=xxx build, help nothing

### Expected Behavior

project to build

### Current Behavior

build failed

### Your Environment
mac os 10.15.8
java 8

**Comment by blindpirate** [comment]
Usually this is because you're GFWed and your proxy is somehow not working.

**Comment by scientificCommunity** [comment]
However, I didn't find this plugin in the plugin store. @blindpirate

**Comment by blindpirate** [comment]
It's not in plugin portal: https://repo.gradle.org/ui/native/enterprise-libs-release-candidates/com/gradle/enterprise/test-distribution-gradle-plugin

**Comment by scientificCommunity** [comment]
666! thanks
