### ISSUE TITLE
Unable to load class 'org.gradle.api.publication.maven.internal.MavenPomMetaInfoProvider'.

### ISSUE THREAD

**Issue by sanketkumbhare** [gradle/gradle#18284]
Working fine with gradle 6.7.1 but when I try to update to gradle 7.0+ error occurs

**Comment by big-guy** [comment]
Is it possible you're using https://github.com/dcendents/android-maven-gradle-plugin?

If you run with `-s`, that might give you a clue which plugin is looking for that class.
