### ISSUE TITLE
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method install() for arguments [installv1_aa8fna578spme8ylgrygrmkzk$_run_closure1@6b439832] on project  of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by sanketkumbhare** [gradle/gradle#18295]
After upgrading to gradle 7.0+ this error occurs

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

**Comment by sanketkumbhare** [comment]
Hi,
the issue occurs when I try to add the sdk to my project with the gradle version more than 7.0+
here is the method which gradle failed to find


install {
    repositories.mavenInstaller {
        // This generates POM.xml with proper parameters
        pom {
            project {
                packaging 'aar'
                groupId publishedGroupId
                artifactId artifact

                // Add your description here
                name libraryName
                description libraryDescription
                url siteUrl

                // Set your license
                licenses {
                    license {
                        name licenseName
                        url licenseUrl
                    }
                }
                developers {
                    developer {
                        id developerId
                        name developerName
                        email developerEmail
                    }
                }
                scm {
                    connection gitUrl
                    developerConnection gitUrl
                    url siteUrl

                }
            }
        }
    }
}

**Comment by sanketkumbhare** [comment]
group = publishedGroupId                               // Maven Group ID for the artifact

install {
    repositories.mavenInstaller {
        // This generates POM.xml with proper parameters
        pom {
            project {
                packaging 'aar'
                groupId publishedGroupId
                artifactId artifact

                // Add your description here
                name libraryName
                description libraryDescription
                url siteUrl

                // Set your license
                licenses {
                    license {
                        name licenseName
                        url licenseUrl
                    }
                }
                developers {
                    developer {
                        id developerId
                        name developerName
                        email developerEmail
                    }
                }
                scm {
                    connection gitUrl
                    developerConnection gitUrl
                    url siteUrl

                }
            }
        }
    }
}

Gradle 7.0+ cannot find the method install in this file

**Comment by ljacomet** [comment]
As documented in [the upgrade notes](https://docs.gradle.org/current/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin), the `maven` plugin has been removed from Gradle 7.0.
You will need to migrate your publication setup to the `maven-publish` plugin.
Your build should have emitted deprecation warnings about this.
