### ISSUE TITLE
Unexpected behavior of Java toolchains

### ISSUE THREAD

**Issue by melix** [gradle/gradle#18290]
This is following a conversation with @ilopmar who was puzzled by this behavior and @ljacomet who suggested to raise an issue for discussion.

### Expected Behavior

If the Java version which Gradle runs on is compatible with the requested toolchain, then this version should be preferred over other detected toolchains.

### Current Behavior

Currently, even if the current Java version is compatible with the toolchain requirements, a different _compatible_ toolchain can be selected by Gradle.

### Context

The [native image plugin](https://github.com/graalvm/native-build-tools/) makes use of the toolchain mechanism to select the right version of `native-image` to call. This is configured this way:

```java
        getJavaLauncher().convention(
                toolchains.launcherFor(spec -> {
                    spec.getLanguageVersion().set(JavaLanguageVersion.of(JavaVersion.current().getMajorVersion()));
                    if (GradleUtils.isAtLeastGradle7()) {
                        spec.getVendor().set(JvmVendorSpec.matching("GraalVM"));
                    }
                })
        );
```

which, basically, means that we set the language version to the current Java version (that Gradle uses). We have to do this because there's no public API allowing to tell what version to use from either the `java { toolchain { ... } }` spec, nor the old `targetCompatibility`. However, you'll notice that it simply makes sure that if you run on Gradle with say, Java 8, then it's going to use a GraalVM JDK 8 release. The user can override this default using our DSL:

```gradle
graalvmNative {
    images {
        main {
            javaLauncher = javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(11)
                vendor = JvmVendorSpec.matching("GraalVM")
            }
        }
    }
}
```

Now, imagine that you have multiple GraalVM installations that Gradle is capable of detecting. Typically, here, multiple versions installed via SDKMAN! There might be different folders containing different releases of GraalVM, and in particular more than one version compatible with Java 11: 21.1.0, 21.2.0, ...

If the requirement is set to `JavaLanguageVersion.of(11)` and that you start a build with AdoptOpenJDK 8, then Gradle will determine that it's not compatible, but it will find an appropriate JDK via auto-detection and SDKMAN!. You won't be able to tell which one you prefer, but that's probably fine (this should ideally be modeled as another property of the spec).

Now, imagine that instead, you start the build with GraalVM 21.2.0 for Java 11. This toolchain _is_ compatible with the requirement. However, when started, we can see that the version of GraalVM which is used to start `native-image` is a _different one_:

```
> Task :nativeCompile
Executing [
/home/ivan/.sdkman/candidates/java/graal-jdk11-master-patch-resources/bin/java \ <----
```

So despite the fact that the _current version_ is compatible, Gradle prefers to use a different one, which is also technically speaking compatible, but unexpected.

The consequence is that for users who are used to the "old way" of switching JDKs from command-line to build with a different JDK get confused by the selection. The only workaround is to disable detection (`-Porg.gradle.java.installations.auto-detect=false` **and** to set the toolchains locations explicitly, e.g `org.gradle.java.installations.fromEnv=JAVA_HOME`.

IMO, if the current Java version is compatible, it should be preferred over other detected installations.

**Comment by ljacomet** [comment]
One idea could be to add an explicit flag to the spec to say that Gradle should prefer the current JVM if it is compatible.

**Comment by melix** [comment]
I understand the surprise you're talking about, but IMO it's much more understandable. If you don't have a compatible VM today, Gradle already selects a compatible one from its detected locations, so that's not much different IMHO.

**Comment by melix** [comment]
Merging https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/228 is blocked until a decision is made on this one.

**Comment by jameskleeh** [comment]
I think if you have a compatible JVM currently on the path that is an improvement over the current behavior, however it still leaves open the possibility of not using the correct JVM for the application, which I believe is the main benefit of the toolchain. 

I think support should be added to specify a specific sub-version. This would redefine what compatibility would mean. In that case if the current JVM is compatible (matches version and sub-version) then there should be no issue preferring that over searching for one.

**Comment by ljacomet** [comment]
We will implement this change for Gradle 7.4. We are discussing adding more selection criteria as well so that sub-version can be matched.

There is one corner case to be aware of: Disabling auto-detection disables the selection of the current Jvm as a candidate. This means that when auto-detection is off, there is no concept of current Jvm for toolchains. This means that even if a Jvm matching the current one is passed amongst the possibilities, it will not be prioritized.

**Comment by melix** [comment]
> Disabling auto-detection disables the selection of the current Jvm as a candidate.

Can this be changed, so that disabling auto-detection simply means "look no further"?

**Comment by jbartok** [comment]
> > Disabling auto-detection disables the selection of the current Jvm as a candidate.
> 
> Can this be changed, so that disabling auto-detection simply means "look no further"?

Yes, after further discussions we came to the same conclusion.

**Comment by ljacomet** [comment]
To be clear: disabling auto detection means the Jvm running Gradle will not be considered a candidate. Only the ones that are provided by the explicit Gradle properties will be. However if the current Jvm is one of those, it will take precedence iff it is compatible.

**Comment by rpost** [comment]
> To be clear: disabling auto detection means the Jvm running Gradle will not be considered a candidate.

This is super confusing.
