### ISSUE TITLE
Included build name is ignored

### ISSUE THREAD

**Issue by iNikem** [gradle/gradle#18325]
Here is my `settings.gradle.kts`:

```
rootProject.name = "included-name"

includeBuild("included-build/javaagent2")
include(":javaagent")
```

Here is the `settings.gradle.kts` file from the included build "included-build/javaagent2" :

```
rootProject.name = "sub-agent"
```

Here is the output of `./gradlew projects` for the main build:

```

> Task :projects

------------------------------------------------------------
Root project 'included-name'
------------------------------------------------------------

Root project 'included-name'
\--- Project ':javaagent'

Included builds
\--- Included build ':javaagent2'

```

As you can see, the name of the included build is `:javaagent2` and not `sub-agent` as configured in the included build's settings file.

### Expected Behavior
Settings file from the included build is fully evaluated and included build project name is correctly set.

### Current Behavior
Project name is not changed.

### Context
My original problem was that included build lives in a folder "included-build/javaagent" and thus my first attempt to include it failed with 

```
Included build in /Users/nsalnikovtarnovski/Documents/workspace/included-name/included-build/javaagent has name 'javaagent' which is the same as a project of the main build.
```

although I do change included project name in settings file.

### Steps to Reproduce 
Demo project is here: https://github.com/iNikem/included-name

**Comment by dgeissl** [comment]
Reported this already in https://github.com/gradle/gradle/issues/15944 but they said this was intentional.
But I am with you - this is not working as one would expect.

**Comment by ljacomet** [comment]
Indeed this is a change done in 6.0 and documented. Link is in #15944
