### ISSUE TITLE
Dynamic work-in-progress on console by default

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1833]
### Expected Behavior
The default behavior of the console shall be that it shows only the number of lines necessary for the parallel work-in-progress. That is, if all operations are processed serially, the console only shows 1 line; it adds lines as needed dynamically.

### Current Behavior
If `--parallel` isn't on, we only [show 1 item in progress](https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionFactory.java#L236-L240) (even though we have test workers and other stuff running already)

### Context
`ParallelismConfigurationCommandLineConverter` and `CommandLineActionFactory` are the interesting spots for this.

**Comment by lacasseio** [comment]
This should be implemented as growing the worker lines as needed until we cap to half the size of the console in height. Care should be taken to minimize the number of time we check the console size.

**Comment by eriwen** [comment]
Closing as delivered!
