### ISSUE TITLE
Property values from gradle.properties files are missing in init scripts

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#18351]
Property values from gradle.properties files and the command line `-P` options are missing in init scripts

### Expected Behavior
I should be able to access the property values from gradle.properties files in my init scripts, just like I do from my settings.gradle and build.gradle scripts.

### Current Behavior
Throws MissingPropertyException

### Context
I'm working on putting together some custom Gradle distributions targeting Gradle 7+ (like what's described here: https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:custom_gradle_distribution ).

For this custom Gradle distribution, I'm trying to augment the static default property values which I have configured via a gradle.properties file and included in the root of my distribution with some dynamically generated "default" property values that I configure via an `init.d/ci.init.gradle` script which I'm also including in the distribution.

This has not been an easy task. The init scripts are not doing basic things that I've grown to expect from working in the settings.gradle and build.gradle scripts. It feels like everywhere I turn I need to dig through the Gradle source files to figure out another "work-around" to get things going again.

I would like this experience to be better, so I'll be filing 5 tickets with hope that we can to improve this situation.

This is ticket 2 of 5

### Steps to Reproduce 
using file: ci.init.gradle
```
println "property: myPropVal=${myPropVal}"
```

run:
```
./gradlew help --init-script ci.init.gradle --stacktrace -PmyPropVal=hello
```

see:
```
groovy.lang.MissingPropertyException: Could not get unknown property 'myPropVal' for build of type org.gradle.invocation.DefaultGradle
```

### Your Environment
Gradle 7.2

**Comment by steffenyount** [comment]
For reference I've provided a PR ^^^ that makes the property values from gradle.properties files available in the init scripts.

The PR does this by injecting the property values into the `Gradle` object after the files have been loaded and before the init scripts are evaluated (in the `GradlePropertiesHandlingSettingsLoader`). The implementation is basically a copy/paste of the injection code used inside the `ScriptEvaluatingSettingsProcessor`'s call to `settingsFactory.createSettings()` which is responsible for injecting the property values into the `Settings` object before the `settings.gradle` script is evaluated.

**Comment by ljacomet** [comment]
As discussed in #18350, this is something the team has decided against.
