### ISSUE TITLE
couldn't use scala classes in java coding in scala-java polyglot gradle project using kotlin dsl

### ISSUE THREAD

**Issue by rajcspsg** [gradle/gradle#18355]
I have scala 2/java polyglot project [gradle-scala-java-polyglot-project](https://github.com/rajcspsg/gradle-scala-java-polyglot-project) build using gradle kotlin dsl. I want the compilation of java and scala mixed. 

### Expected Behavior
If I use scala files in java code the compilation should be successful.

### Current Behavior
If I use java files in scala the compilation is successful. But if I use scala files inside java then compilation fails.

### Context
I'm not able to build the project which uses scala code inside java.

### Steps to Reproduce 

The self contained simple example project with only few files in this repository https://github.com/rajcspsg/gradle-scala-java-polyglot-project.
I've asked this question in [stackoverflow](https://stackoverflow.com/questions/69263809/couldnt-use-scala-classes-in-java-coding-in-scala-java-polyglot-gradle-project) and [reddit](https://www.reddit.com/r/gradle/comments/psxv8f/couldnt_use_scala_classes_in_java_coding_in/) as well.

**Comment by JintaoXIAO** [comment]
in my understanding, gradle will first compilejava code, which failed where,  after change to below configuration,
it works. 
we just let javacompile's source to be empty

```
sourceSets {
    main {
        java {
            setSrcDirs(listOf<String>())
        }
        scala {
            setSrcDirs(listOf("src/main/java", "src/main/scala"))
        }
    }
}
```

**Comment by rajcspsg** [comment]
okay I tried your suggestion and got below error

```
gradle clean build       

> Configure project :
e: /Users/rajkumar.natarajan/Documents/Coding/misc/adserver-flink-streaming/build.gradle.kts:47:13: Unresolved reference: setSrcDirs

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rajkumar.natarajan/Documents/Coding/misc/adserver-flink-streaming/build.gradle.kts' line: 47

* What went wrong:
Script compilation error:

  Line 47:             setSrcDirs(listOf("src/main/java", "src/main/scala"))
                       ^ Unresolved reference: setSrcDirs

1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

**Comment by rajcspsg** [comment]
@JintaoXIAO your suggestion works closing the issue.
