### ISSUE TITLE
Overload resolution ambiguity: Plugins { version(null) }

### ISSUE THREAD

**Issue by RinOrz** [gradle/gradle#18356]
> Overload resolution ambiguity:  public abstract fun version(p0: String?): PluginDependencySpec! defined in org.gradle.plugin.use.PluginDependencySpec public open fun version(p0: Provider<String!>!): PluginDependencySpec! defined in org.gradle.plugin.use.PluginDependencySpec

```kotlin
plugins { `kotlin-dsl`.version(null) }
```

**Comment by blindpirate** [comment]
What do you expect? Why did you pass `null` to `version()`? The current error is totally expected.

**Comment by RinOrz** [comment]
@blindpirate The parent project has applied `kotlin-dsl`. If I also apply `kotlin-dsl` in the child project, the following error will be thrown:

> Caused by: org.gradle.api.GradleException: Error resolving plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '2.1.6']
> 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:216)
> 	... 163 more
> Caused by: org.gradle.plugin.management.internal.InvalidPluginRequestException: Plugin request for plugin already on the classpath must not include a version

**Comment by blindpirate** [comment]
```
plugins {
    `kotlin-dsl` apply false
}
```

**Comment by blindpirate** [comment]
Please search before you ask: https://www.google.com/search?q=Plugin+request+for+plugin+already+on+the+classpath+must+not+include+a+version&oq=Plugin+request+for+plugin+already+on+the+classpath+must+not+include+a+version&aqs=chrome..69i57j69i64&sourceid=chrome&ie=UTF-8

**Comment by RinOrz** [comment]
@blindpirate I know this, but I think this is not what I want, the parent project should apply it, and this is not working:

For `:root:foo` build.gradle.kts
```kotlin
`plugins { kotlin; `kotlin-dsl` apply false }`
```

For `:root:foo:bar` build.gradle.kts
```kotlin
`plugins { kotlin; `kotlin-dsl` }`
```

> org.gradle.internal.exceptions.LocationAwareException: Build file 'root/foo/bar/build.gradle.kts' line: 23
Error resolving plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '2.1.6']

> Caused by: org.gradle.plugin.management.internal.InvalidPluginRequestException: Plugin request for plugin already on the classpath must not include a version
	at org.gradle.plugin.use.resolve.internal.AlreadyOnClasspathPluginResolver.resolve(AlreadyOnClasspathPluginResolver.java:62)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:213)
	... 163 more


But if I use:
`id("org.gradle.kotlin.kotlin-dsl")`
I meet the expected work, but the string is not easy to write, so I prefer `kotlin-dsl version null`
