### ISSUE TITLE
java.beans.Introspector chokes on Gradle DSL object properties in init scripts

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#18350]
The `java.beans.Introspector` is choking on the `org.gradle.api.invocation.Gradle` DSL object when Introspecting for dynamic object property access in init scripts.

In particular:
1) The `java.beans.Introspector` is miscategorizing methods like `Gradle.settingsEvaluated()` as a bean property named `tingsEvaluated`.

2) `BeanDynamicObject.getProperties()` is not ignoring bean properties where `MultipleSetterProperty.getGetter() == null`.

3) accessing properties from an init script is throwing:
    "java.lang.IllegalStateException: The default project is not yet available for build."

E.g: with init script:
```
properties.forEach { name, value ->
    println "property: ${name}=${value}"
}
```

### Expected Behavior
I should be able to access properties in the Gradle object context provided to the init script

### Current Behavior
1) The `java.beans.Introspector` is miscategorizing methods like `Gradle.settingsEvaluated()` as a bean property named `tingsEvaluated`

2) Fails on misguided attempt to call `MultipleSetterProperty.getGetter()` for the `Gradle.settingsEvaluated()` functions

3) Throws IllegalStateException

### Context
I'm working on putting together some custom Gradle distributions targeting Gradle 7+ (like what's described here: https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:custom_gradle_distribution ).

For this custom Gradle distribution, I'm trying to augment the static default property values which I have configured via a gradle.properties file and included in the root of my distribution with some dynamically generated "default" property values that I configure via an `init.d/ci.init.gradle` script which I'm also including in the distribution.

This has not been an easy task. The init scripts are not doing basic things that I've grown to expect from working in the settings.gradle and build.gradle scripts. It feels like everywhere I turn I need to dig through the Gradle source files to figure out another "work-around" to get things going again.

I would like this experience to be better, so I'll be filing 5 tickets with hope that we can to improve this situation.

This is ticket 1 of 5

### Steps to Reproduce 
using file: ci.init.gradle
```
properties.forEach { name, value ->
    println "property: ${name}=${value}"
}
```

run:
```
./gradlew help --init-script ci.init.gradle --stacktrace
```

see failures like:
```
java.lang.IllegalStateException: The root project is not yet available for build.
```

### Your Environment
Gradle 7.2

**Comment by ljacomet** [comment]
Accessing `Gradle.properties` without being in a callback at all is too early indeed.
Given the question here and in #13362, we are trying to clarify this in the documentation.
There is however no plan at this time to change when properties are loaded in the build lifecycle.

**Comment by steffenyount** [comment]
Regardless of timing, I expect the BeanDynamicObject.getProperties() function should not throw exceptions when being called on the Gradle object from inside of an init script.

Please, see the PR I've provided ^^^ for my suggested fixes.

**Comment by ljacomet** [comment]
The PR linked gives access to properties. The discussion within team concluded that we do not want to give access. And so the failure is OK in that context.
