### ISSUE TITLE
Add Gradle.initScriptsEvaluated() and BuildListener.initScriptsEvaluated() callbacks

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#18354]
The Gradle.settingsEvaluated() and Gradle.projectsEvaluated() callbacks allow us to augment our Settings evaluation and Project evaluation by registering actions/closures which then run in the same evaluation contexts respectively.

I would like to have a similar capability for init script evaluation where the registered actions/closures would be run after all the init scripts have been evaluated but before the Settings object has been initialized.

### Expected Behavior
I'd like to be able to register an action/closure to run within this same scope as the init scripts, after all the init scripts have been evaluated. 

I could imagine this being made accessible within init scripts via the Gradle interface like:
```
public interface Gradle extends PluginAware {
...
    void initScriptsEvaluated(Closure closure);
    void initScriptsEvaluated(Action<? super Gradle> action);
...
}
```
that way I could write an init script that follows-up on the work of other init scripts like:
ci.init.gradle
```
startParameter.rerunTasks = true

initScriptsEvaluated {
    println "init scripts result: rerunTasks=${startParameter.rerunTasks}"
}
```

### Current Behavior
Init scripts execute within the context of a Gradle object, after the gradle.properties files have been loaded, but before the Settings object has been initialized. There is currently no callback function whereby I could register an action/closure to run in this same scope, before the Settings object has been initialized.

### Context
I'm working on putting together some custom Gradle distributions targeting Gradle 7+ (like what's described here: https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:custom_gradle_distribution ).

For this custom Gradle distribution, I'm trying to augment the static default property values which I have configured via a gradle.properties file and included in the root of my distribution with some dynamically generated "default" property values that I configure via an `init.d/ci.init.gradle` script which I'm also including in the distribution.

This has not been an easy task. The init scripts are not doing basic things that I've grown to expect from working in the settings.gradle and build.gradle scripts. It feels like everywhere I turn I need to dig through the Gradle source files to figure out another "work-around" to get things going again.

I would like this experience to be better, so I'll be filing 5 tickets with hope that we can to improve this situation.

This is ticket 5 of 5

**Comment by ljacomet** [comment]
Could you use the `Gradle.beforeSettings` hook for that?

**Comment by steffenyount** [comment]
Things are run in the following order:
1. `gradle.properties` values are loaded
2. init scripts are evaluated
3. the Settings object is created and the GradleProperties values are injected into it
4. the Gradle.beforeSettings hook is evaluated
5. the settings.gradle script is evaluated

The proposed Gradle.initScriptsEvaluated hook would allow actions to execute in the same context as the init scripts between steps 2 and 3. I.e: before the the Settings object is created and the GradleProperties values are injected into it.

This capability would be particularly useful if the changes for #18353 which allow the GradleProperties to be modified in the init scripts gets merged, but it would also allow BuildTools to register init script equivalent listeners at this stage in the run order.

**Comment by ljacomet** [comment]
We discussed this within the team and there is no plan to offer these callbacks.
