### ISSUE TITLE
Provide a mechanism to either make `dependsOn` lenient or test for the existence of a task in an includedBuild

### ISSUE THREAD

**Issue by Mahoney** [gradle/gradle#18368]
I’ve got a task `downloadDependencies` (defined as a plugin in an included build) that I use to try and ensure the build subsequently works offline.

I want to call it at the top level - `./gradlew downloadDependencies` - and be done.

For that to work I need that task in the root project to depend on the `downloadDependencies` task of the included builds if they have the plugin applied themselves. Some of them, e.g. settings plugins, cannot.

### Expected Behavior

I'd like to either be able to query `IncludedBuild` to see if it has a task with a name (or query `TaskReference` to see if the reference resolves?), or else have something like `dependsOnIfPresent` that just silently skips over references to tasks that don't exist.

### Current Behavior

When I add a `dependsOn(includedBuild.task(":downloadDependencies"))` for an included build that doesn't have that task I, correctly, get this error:
```
Could not determine the dependencies of task ':downloadDependencies'.
> Task with path ':downloadDependencies' not found in project ':include-build-conventions'.
```

### Context
This is my plugin code:
```kotlin
class DownloadDependenciesPlugin : Plugin<Project> {

  override fun apply(project: Project) {

    val task = project.tasks.register<DownloadDependenciesTask>("downloadDependencies")

    if (project.isRoot) {

      val includedBuildTasks = project.gradle.includedBuilds
        .map { it.task(":downloadDependencies") }
        .toTypedArray()

      task.configure {
        dependsOn(*includedBuildTasks)
      }
    }
  }
}

private val Project.isRoot get() = parent == null

```

My ugly workaround is to add the following to the `build.gradle.kts` of all included builds that are upstream of the plugin:
```kotlin
tasks.register("downloadDependencies") {
  // dummy to allow the build to pass!
}
```

**Comment by ov7a** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.
