### ISSUE TITLE
Application plugin should offer a convenient way to install applications so that they are visible in the user's PATH

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#1836]
I use the application plugin to develop some command-line tools (gradle-profiler, for example). I would like some convenient way to install an application into some well known location on my machine that I can point my $PATH at.

In other words, I want to be able to _install_ the application ready for use on the machine.

### Expected Behavior

Something like this:

First, I do some initial setup on my machine once, say by pointing my PATH at some directory under my user home dir, and maybe configuring something in ~/.gradle to point to this directory as well.

I do this setup once per machine. Bonus if the application plugin offers to do this for me.

Then, for a given application I run `./gradlew <some-task-name>` to install the current version of the application to some well known location. I can now use this version of the application from the command-line.

Bonus if this is nicely integrated with the system's concept of install and uninstall, but is certainly useful without this.

### Current Behavior

I _can_ cobble this kind of thing together myself, but I don't want to do this every time I create an application and I want this to work nicely with other people's application that I may build from source.

I think such a feature could be used as a building block to automate other interesting workflows, such as having the Gradle build provision the tools required by the build, on CI or a dev machine or for a VM/container.

**Comment by lacasseio** [comment]
I couldn't agree more. Some scenario I saw in the past are native toolchain installation and NodeJS installation. To some extent, this concept is already been used by some project and it makes CI and dev machine extremely easy to configure.
