### ISSUE TITLE
IntelliJ Gradle plugin fails to load a project with double included builds on Gradle 7.2

### ISSUE THREAD

**Issue by AndreyKhranovsky-TomTom** [gradle/gradle#18367]
A project has 2 included builds, and one included build also includes another.

```
+ Sample // includeBuild(platform), includeBuild(product)
-- platform
-- product // includeBuild(platform)
```

IntelliJ Gradle plugin fails to sync the project using Gradle 7.2.0 but works well with Gradle 7.1.0.
Both Gradle versions works well from the terminal using Gradle wrapper.

### Expected Behavior
Project is synced in IntelliJ Idea

### Current Behavior
IntelliJ Idea fails to sync the project

```
No model of type 'TurnOffDefaultTasks' is available in this build.
> No builders are available to build a model of type 'org.jetbrains.plugins.gradle.model.internal.TurnOffDefaultTasks'.
```

### Steps to Reproduce 

Open project in Idea
https://github.com/AKhranovskiy/gradle-nested-include-builds/tree/android-studio-sync

### Your Environment

Gradle 7.2
Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Gradle 7.1
Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

IntelliJ Gradle plugin 203.7717.56.2031.7678000
IntelliJ Gradle plugin 212.5284.40
IntelliJ Gradle plugin 211.7628.21.2111.7699744

[IntelliJ Idea ticket](https://youtrack.jetbrains.com/issue/IDEA-278803)

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the core of the Gradle Build Tool.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/

----

If this also does not work on the command line, please add information to reproduce the CLI problem.
