### ISSUE TITLE
403 Forbidden when try to download dependency in customized maven repository

### ISSUE THREAD

**Issue by liuzqt** [gradle/gradle#18374]
I added a customized maven repository like this:
```
repositories {
    maven {
        url 'https://url/to/my/customized/maven/repository'
        credentials {
            username System.getenv('JFROG_USERNAME')
            password System.getenv('JFROG_PASSWORD')
        }
    }
}

```

I put it in one gralde file under `{projectRoot}/buildSrc` and import it as a plugin in the `build.gradle` in one of my subproject, when it try to download dependency from this repo, got 403 Forbidden error.

The weird thing is that, when I put this customized repository in the `build.gralde` in my subproject directly, it works well....

So I suppose there is something to do with `buildSrc`, usually I put some common things under this folder and import it in many sub projects. 

### Your Environment
gradle 7.0.2

**Comment by ljacomet** [comment]
Please share a reproducer. Without it, it is impossible to provide any advice. Both places to declare this should work.
