### ISSUE TITLE
Reading a resource in a jar from submodule dependency fails intermittently

### ISSUE THREAD

**Issue by safetytrick** [gradle/gradle#18376]
### Expected Behavior
The resulting jar from building a dependent sub-module should be completely built and readable before it is accessed by another the build of another module in the same project. 

### Current Behavior
The submodule jar is not reliably accessible, this fails intermittently for me. 

### Context
Full context is here in this issue: https://github.com/davidmc24/gradle-avro-plugin/issues/174 

My project structure looks like this:

/settings.gradle
/common/src/main/resources/common-file.txt
/other-module/

other-module has a dependency on common like this:
``` implementation project(":common") ```

The build for other-module effective does something like this:

```
classloader = new UrlClassloader(project.configurations['runtimeClasspath'].map { toUrl }) // this includes common-1.0.0.jar
classloader.getResource("common-file.txt")
```

I believe that plugin's dependency on the classpath of the current project should be sufficient to allow exposing the jar from the common build? 

Intermittently reading the resource fails with this exception:

```
java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:1003)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:1013)
        at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:468)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.github.davidmc24.gradle.plugin.avro.GenerateAvroProtocolTask$DelegatingClassloader.getResource(GenerateAvroProtocolTask.java:145)
        at org.apache.avro.compiler.idl.Idl.findFile(Idl.java:101)
        at org.apache.avro.compiler.idl.Idl.ImportIdl(Idl.java:450)
        at org.apache.avro.compiler.idl.Idl.ProtocolBody(Idl.java:338)
        at org.apache.avro.compiler.idl.Idl.ProtocolDeclaration(Idl.java:227)
        at org.apache.avro.compiler.idl.Idl.CompilationUnit(Idl.java:117)
        at com.github.davidmc24.gradle.plugin.avro.GenerateAvroProtocolTask.processIDLFile(GenerateAvroProtocolTask.java:97)
```

I think that is a bug with gradle but it's possible that dependency isn't expressed correctly? I couldn't find proof that there was any better way to do it.

There is also a question about the gradle daemon's behavior when plugins access jar URLs from that classpath? By default I think those are cached. That caused me to run into this behavior: https://discuss.gradle.org/t/gradle-daemon-corrupts-resources-in-snapshot-jars/18183/2

Is there a better way for plugins to be accessing URL resources?

### Steps to Reproduce 
I will try to put together a project to reproduce.

### Your Environment

    Gradle Version [e.g. 6.6.1]
    Apache Avro Version [e.g. 1.10.2]
    Gradle-Avro Plugin Version [e.g. 1.2.1]
    Java Version [e.g. 11.0.6]
    OS: [Ubuntu 20.04]

**Comment by safetytrick** [comment]
The more I think about this the more I think accessing any jar urls for jars that aren't immutable from the daemon is just fundamentally unsafe. My build failure is just incidental, the impact is just as likely to be an out of date read that doesn't cause a complete failure as it is to end in caching a failed read. 

The description in this [forum thread](https://discuss.gradle.org/t/gradle-daemon-corrupts-resources-in-snapshot-jars/18183/2) describes the exact same problem, the only difference is that I am referencing a changing jar from `project(":common")` and they are referencing a changing jar deployed into `mavenLocal()`.

Is there a better way for a plugin to access these kinds of resources?

**Comment by ljacomet** [comment]
Please provide a reproducer as it may allow us to pinpoint a missing task dependency. There should not be any issue when reading a JAR from the classpath at runtime.

**Comment by safetytrick** [comment]
@ljacomet here you go: https://github.com/safetytrick/gradle-classpath-access

`./stress.sh ` will typically reproduce in a few iterations
