### ISSUE TITLE
configuration cache with included build causes --profile unable to create directory

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#18386]
### Expected Behavior
If I run a build that uses an included build, has configuration caching enabled, and uses the --profile argument, I'd like the process of generating the profile report to succeed.

### Current Behavior
Currently if I do the above, I observe that Gradle says it cannot create the report directory:

```
Could not stop build 'doclava'.
org.gradle.api.UncheckedIOException: Could not write to file 'reports/profile/profile-1969-12-31-19-00-00.html'.
	at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:152)
	at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:127)
	at org.gradle.internal.IoActions.writeTextFile(IoActions.java:45)
...
Caused by: java.io.IOException: Unable to create directory 'reports/profile'
	at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:142)
```

### Context
This makes it slightly more difficult to enable configuration caching in androidx ( https://android.googlesource.com/platform/frameworks/support/ )

### Steps to Reproduce 
See https://github.com/mathjeff/gradle-samples/tree/master/included-build-configuration-cache-profile

### Your Environment
Build scan URL: https://scans.gradle.com/s/22l2n2jlpv5ac

Note that the failure is in generating the profile report file, which happens after publishing the build scan, and so the build scan might not mention the failure to create the profile report file

**Comment by mathjeff** [comment]
Also interesting, if I run `mkdir reports`, that seems to cause the build to succeed

**Comment by mathjeff** [comment]
It seems that in this situation, Gradle is trying to put the reports into `./reports` whereas it would be nice for them to go into something more like `${rootProject.buildDir}/reports`

**Comment by sandipchitale** [comment]
FWIW, in the IntelliJ debugger, I see that the canonical path for 'reports/profile' resolves to '~/.gradle/daemon/7.4.2/reports/profile' and the [mkdirs()](https://github.com/gradle/gradle/blob/849f51d5e873906dbf5af951781a3019ab7c3961/subprojects/base-services/src/main/java/org/gradle/internal/IoActions.java#L141) call below fails with the exception.

```
                File parentFile = file.getParentFile();
                if (parentFile != null) {
                    if (!parentFile.mkdirs() && !parentFile.isDirectory()) {
                        throw new IOException(String.format("Unable to create directory '%s'", parentFile));
                    }
                }
```

**Comment by RicardoJiang** [comment]
same question

**Comment by Gozdeee1** [comment]
Same here

**Comment by klboke** [comment]
same question +1

**Comment by VitalyVPinchuk** [comment]
Hi, same here.
But I created `reports/profile` manually in the folder where I run `./gradlew` from.
So the report was successfully created, though Gradle reported it was created in `~/.gradle/daemon/7.6/reports/profile/profile-1969-12-31-20-00-00.html`

Any ideas?

**Comment by jandry** [comment]
Still same issue today using gradle 8.3

**Comment by franckrasolo** [comment]
Likewise with Gradle 8.6

**Comment by esafirm** [comment]
With `reports` directory exist, this error could be avoided, but it seems the report content also not correct.

![CleanShot 2024-03-06 at 09 31 15@2x](https://github.com/gradle/gradle/assets/1691440/679763e5-97da-4245-afa2-21a911173fd4)

**Comment by mucst** [comment]
I had this problem. Turns out I used the wrong JDK version. The project was an old one (java8) and I had java 21 on my system path and JAVA_HOME
