### ISSUE TITLE
Gradle daemon on NFS share pollutes across hosts

### ISSUE THREAD

**Issue by ccheetham** [gradle/gradle#1839]
Assume a home NFS-mounted directory across a LAN.  Gradle, on a particular host, is confused because it sees artifacts from daemons on other hosts.

### Expected Behavior

Gradle should be able to run daemon on hosts autonomously.  Perhaps something a simple as tracking daemon state at, for example, `$GRADLE_USER_HOME/daemon-$HOST`.   

### Current Behavior

Gradle doesn't maintain separate state for for separate hosts.  Daemon state is tracked at `$GRADLE_USER_HOME/daemon`.  

### Context

We have a several dozen hosts with NFS shares for homes.  User accounts workaround by setting `GRADLE_USER_HOME` to a local (non-NFS) path.  The downside is reusable cache files are unnecessarily replicated.

### Steps to Reproduce (for bugs)

Run a gradle daemon on one host.  Daemon status looks something like:

```
# hostA
% gr --status
   PID STATUS   INFO
 82521 IDLE     3.4.1
```

On another host, run `gradle --status`.

```
# hostB
% gr --status
No Gradle daemons are running.
   PID STATUS   INFO
 82521 STOPPED  (by user or operating system)
```

Back on original host run check status.
```
# hostA
% gr --status
No Gradle daemons are running.
   PID STATUS   INFO
 82521 STOPPED  (after the daemon was no longer found in the daemon registry)
```

### Your Environment

Unix-y environment where homes are mounted over NFS.  Host operating system include OSX, several versions of Solaris, many Linux distros.  One common aspect besides NFS is the use of JDK8 (Oracle) as the Gradle JVM.

**Comment by cebaa** [comment]
Based on comments in https://github.com/gradle/gradle/issues/851, there might be other things that are in `$GRADLE_USER_HOME` that cannot be shared due to how gradle works internally. In other words, changing `$GRADLE_USER_HOME/daemon` to `$GRADLE_USER_HOME/daemon-$HOST` might not be enough.

I *really* hope I'm wrong, since I have the same issue on my end. I guess some of the issues may be resolved due to efforts in e.g. https://github.com/gradle/gradle/issues/1338.

Would someone from gradle team be able to shed some light on this issue?

**Comment by jvandort** [comment]
Sorry for the late reply.

Generally we would recommend not sharing a Gradle User Home across machines. During a build Gradle performs many IO operations against the caches in your GUH, and the added network latency would likely affect performance. 

In scenarios where user home directories are mounted on an NFS share, we recommend using an environment variable to set the Gradle User Home of the machine to a local directory.

The Gradle User Home can be set using the `GRADLE_USER_HOME` environment variable: 
https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home

If you have a use case other than shared home directories, please open a new feature request
