### ISSUE TITLE
Error: "package sun.rmi.registry is declared in module java.rmi, which does not export it to the unnamed module" in gradle kotlin dsl

### ISSUE THREAD

**Issue by rajcspsg** [gradle/gradle#18392]
I've a simple java 11 project build using gradle kotlin dsl. The class in the project uses `sun.rmi.registry.RegistryImpl`.

There is a class in the program which uses sun.rmi.registry.RegistryImpl from restricted java.rmi module.
```
package org.example.management;

import sun.rmi.registry.RegistryImpl;

class JMXServer {

 // 
}
```

I added below snippet as well to the build file to use java.rmi module.

```
tasks.withType<JavaCompile> {
    val compilerArgs = options.compilerArgs
    compilerArgs.addAll(listOf("--add-exports", "java.rmi/sun.rmi.server=ALL-UNNAMED",  "--add-exports", "jdk.management.agent/jdk.internal.agent=ALL-UNNAMED"))
}
```

### Expected Behavior
The compilation should be successful.

### Current Behavior
The compilation fails with below error.

```
>/Users/rajkumar.natarajan/Documents/Coding/misc/gradle-rmi-issue/src/main/java/org/example/management/JMXServer.java:18: error: package sun.rmi.registry is not visible >import sun.rmi.registry.RegistryImpl; ^ 
>(package sun.rmi.registry is declared in module java.rmi, which does not export it to the unnamed module)
```

### Context

Not able to build the java project which uses java.rmi module.

### Steps to Reproduce 
The code is in github [here](https://github.com/rajcspsg/gradle-rmi-issue)
I asked [stackoverflow](https://stackoverflow.com/questions/69306905/error-package-sun-rmi-registry-is-declared-in-module-java-rmi-which-does-not) question as well 
### Your Environment

Build scan URL:

**Comment by asodja** [comment]
Changing `java.rmi/sun.rmi.server=ALL-UNNAMED` to `java.rmi/sun.rmi.registry=ALL-UNNAMED` should fix the issue. 

You can find this from ther error: package `sun.rmi.registry` is declared in module `java.rmi` -> `java.rmi/sun.rmi.registry`

**Comment by asodja** [comment]
I will close this issue. If that does not solve it feel free to comment on this issue.
