### ISSUE TITLE
Is it possible for gradle to be like maven and not depend on a specific jdk version

### ISSUE THREAD

**Issue by fantasy0v0** [gradle/gradle#18411]
### Expected Behavior
Is it possible for gradle to be like maven and not depend on a specific jdk version

### Current Behavior
developers need to download a new gradle every time when update Jdk

**Comment by ljacomet** [comment]
A number of libraries used by Gradle require updates when new JDK versions appear.
So indeed to leverage the latest JDK you often need to upgrade Gradle.
This is not going to change though we want to improve this. One solution is to rely on toolchains to decouple the JDK running Gradle from the one compiling / testing your code.
