### ISSUE TITLE
dependency-verification-*.xsd schema is incomplete

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#18410]
Gradle [dependency verification](https://docs.gradle.org/current/userguide/dependency_verification.html) has a schema (https://schema.gradle.org/dependency-verification/dependency-verification-1.1.xsd) for `gradle/verification-metadata.xml`, but it is missing entry for `<key-servers>`. That is a [valid and working tag](https://docs.gradle.org/current/userguide/dependency_verification.html#sec:ignoring-keys)

### Expected Behavior
dependency-verification-*.xsd is complete

### Current Behavior
dependency-verification-*.xsd is missing key-servers tag.

### Context
Due to schema incompleteness `gradle/verification-metadata.xml` fails XML validation tools, e.g. Intellij will warn `Element key-servers is not allowed here`.

### Steps to Reproduce 
```
<?xml version="1.0" encoding="UTF-8"?>
<verification-metadata xmlns="https://schema.gradle.org/dependency-verification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://schema.gradle.org/dependency-verification https://schema.gradle.org/dependency-verification/dependency-verification-1.1.xsd">
   <configuration>
      <verify-metadata>true</verify-metadata>
      <verify-signatures>true</verify-signatures>
      <key-servers enabled="false"/>
      <trusted-artifacts>
         <trust file=".*-javadoc[.]jar" regex="true"/>
         <trust file=".*-sources[.]jar" regex="true"/>
      </trusted-artifacts>
   </configuration>
</verification-metadata>
```

### Your Environment
N/A

**Comment by asodja** [comment]
Interesting. Can you it check again? It looks like schema 1.1 contains key-servers:
```
    <xs:complexType name="key-serverType">
        <xs:attribute type="xs:string" name="uri"/>
    </xs:complexType>
    <xs:complexType name="configurationType">
        <xs:sequence>
            <xs:element type="xs:boolean" name="verify-metadata"/>
            <xs:element type="xs:boolean" name="verify-signatures"/>
            <xs:element type="trusted-artifactsType" name="trusted-artifacts"/>
            <xs:element type="ignored-keysType" name="ignored-keys"/>
            <xs:element type="trusted-keysType" name="trusted-keys"/>
            <xs:element type="key-serversType" name="key-servers"/>
        </xs:sequence>
    </xs:complexType>
```

**Comment by liutikas** [comment]
It looks like IJ was loading 1.0 version instead of 1.1 for some reason. Probably Intellij bug then. Sorry!
