### ISSUE TITLE
the springboot plugin is not found using linux gradle

### ISSUE THREAD

**Issue by Leewt** [gradle/gradle#18419]
the springboot plugin is not found using linux gradle distribution .

### Current Behavior

FAILURE: Build failed with an exception.

* Where:
Build file '/home/lee/Project/Atest/build.gradle' line: 2

* What went wrong:
Plugin [id: 'org.springframework.boot', version: '2.4.5'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.springframework.boot:org.springframework.boot.gradle.plugin:2.4.5')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Context

plugins {
    id 'org.springframework.boot' version '2.4.5'
    id 'java'
}

version = '1.0.2'
group = 'org.gradle.samples'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:2.4.5')

    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}

tasks.named('test', Test) {
    useJUnitPlatform()
}
### Steps to Reproduce 

gradle build
### Your Environment

Build scan URL:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

lee@optiplex:~/Project/Atest$ gradle build --scan

FAILURE: Build failed with an exception.

* Where:
Auto-applied by using --scan

* What went wrong:
Plugin [id: 'com.gradle.enterprise', version: '3.6.3', artifact: 'com.gradle:gradle-enterprise-gradle-plugin:3.6.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle:gradle-enterprise-gradle-plugin:3.6.3')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 518ms

**Comment by blindpirate** [comment]
It's usually because you're GFWed. Upon such errors, gradle silenly tries next repo instead of failing the build.
