### ISSUE TITLE
$APP_HOME is not getting populated in Gradle 7.2

### ISSUE THREAD

**Issue by kmgowda** [gradle/gradle#18425]
### Expected Behavior
"-Dhome=$APP_HOME"  to java vm should evaluate the $APP_HOME to value assigned to APP_HOME variable of the executable created by gradle
for example if APP_HOME="/user/local/gradle" then $HOME_APP. should yeild the value "/user/local/gradle"

### Current Behavior
"-Dhome=$APP_HOME" is  evaluating to $APP_HOME. but it is yielding $HOME_APP

### Context
problem occured while setting  applicationDefaultJvmArgs.
 applicationDefaultJvmArgs = ['-Dhome=\$APP_HOME']

### Steps to Reproduce 
create any java application with gradle 7.2 and set the java -d variable as follows
applicationDefaultJvmArgs = ['-Dhome=\$APP_HOME']

you will see the home is set to $APP_HOME , actually $APP_HOME it not evaluated tot get the value assigned to APP_HOME.

### Your Environment

gradle 7.2 with SDK 1.17 on macos.

Build scan URL: https://github.com/kmgowda/SBK/pull/248/checks?check_run_id=3712936240

**Comment by blindpirate** [comment]
If you want the variable in GString to be evaluated, please use double quote. That's Groovy syntax and has nothing to do with Gradle.

**Comment by kmgowda** [comment]
with gradle 7.2 , you create a simple java application to extract $APP_HOME  via -D in gradle and in java program ystem.getProperty, you will get to know the problem..

**Comment by blindpirate** [comment]
Can you provide a reproducer instead of a few instructions? Otherwise we may not understand you well.

**Comment by kmgowda** [comment]
yes..

1. clone this code : https://github.com/kmgowda/SBK/tree/kmg-jdk17-2
2. ./gradlew installDist
3.  run this command:  build/install/sbk/bin/sbk 
you will see this output:
2021-09-27 17:50:22 INFO sbk.appHome: $APP_HOME

this comes from : https://github.com/kmgowda/SBK/blob/kmg-jdk17-2/build.gradle#L105

The name : SBK_APP_HOME alternative name to $APP_HOME , it comes from : https://github.com/kmgowda/SBK/blob/kmg-jdk17-2/gradle/application.gradle#L42

In gradle 6.6 , it was workiing.. I migrated my open source project : SBK to gradel 7.2 , it am seeing the described bug.

**Comment by China-zoupanpan** [comment]
in the script file of the  old version,
`DEFAULT_JVM_OPTS='"Dlogback.configurationFile=$APP_HOME/config/logback.xml"'`
`eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $logback.configurationFile=$APP_HOME/config/logback.xml -classpath "\"$CLASSPATH\"" xxx.xxx.xxx.MainApp "$APP_ARGS"
`

in the script file of the new version,
`DEFAULT_JVM_OPTS='"Dlogback.configurationFile=$APP_HOME/config/logback.xml"'`
`eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $THOR_GUARDIAN_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'`

**Comment by China-zoupanpan** [comment]
execute print $@. **Dlogback.configurationFile=/opt/app/config/logback.xml** can be printed in the old version but **Dlogback.configurationFile=$APP_HOME/config/logback.xml** is printed in the new version.

**Comment by China-zoupanpan** [comment]
i mean. it's the right way by the following way。
`unixStartScriptGenerator.template = resources.text.fromFile('unixStartScript.txt')`
