### ISSUE TITLE
Gradle build not getting latest version of jar when there is a internal dependnacy and another added seperately

### ISSUE THREAD

**Issue by swamigmv** [gradle/gradle#18422]
Hi,

I have a gradle project for a helidon based microservice. The helidon dependency internally refers to mockito 2.23.4, while i added 3.12.4 explicitly as another dependancy. But the gradle was always picking up 2.23.4. I guess the ideal behaviour is to pickup the latest version which should be 3.12.4.

code snippet:
dependencies {
  implementation enforcedPlatform("io.helidon:helidon-dependencies:${project.helidonversion}")
  testImplementation 'org.mockito:mockito-core:3.12.4'
  testImplementation 'org.mockito:mockito-inline:3.12.4'
}

Here it always downloaded 2.23.4 which was internally dependency for "io.helidon:helidon-dependencies"

Currently I excluded explicitly like
implementation enforcedPlatform("io.helidon:helidon-dependencies:${project.helidonversion}"){
    exclude group: 'org.mockito', module: 'mockito-core'
}

but this was a manual task of finding out which dependency was internally referring to this lower version. 

Environment:
Windows 10, gradle 7.1.1, JDK - 16.0.2

**Comment by blindpirate** [comment]
Can you share a full project instead of just a few lines of code snippet? We may not have enough experience on helidon and have no idea what `project.helidonversion` is in your code snippet.

**Comment by blindpirate** [comment]
> Here it always downloaded 2.23.4 which was internally dependency for "io.helidon:helidon-dependencies"

Can you try 

```
implementation enforcedPlatform("io.helidon:helidon-dependencies:${project.helidonversion}")
implementation 'org.mockito:mockito-core:3.12.4'
implementation 'org.mockito:mockito-inline:3.12.4'
```

Because `implementation` is evaluated independent of `testImplementation`. I guess that's the issue.

**Comment by swamigmv** [comment]
i think i got the issue. Below is the config in helidon depencies
<dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${version.lib.mockito}</version>
            </dependency>

if test scope is added here , will it work? if so will get in touch with helidon group....

**Comment by ljacomet** [comment]
This works as designed:
You are using an `enforcedPlatform` which means all versions defined in the platform are considered as "forced" version by Gradle.
If that's not the behaviour you want, do not use `enforcedPlatform` and then Gradle will do the expected version conflict resolution which will pick the highest version seen.
