### ISSUE TITLE
Terminal automatically scrolls down on never ending tasks with the new console

### ISSUE THREAD

**Issue by felipefzdz** [gradle/gradle#1843]
Regarding the console, the new timer on `98% EXECUTING [1m 51s]` is pretty cool. However, when executing tasks that conceptually never end (like our build scan service), there is some UX caveat. Let's say that there was some interesting log message during the startup of my service. If I want to read it, I'll scroll up on the CLI. However, as that clock is continuously updated, the terminal (at least Terminator on Linux Mint), automatically scrolls down to that changing output, i.e. I need to stop the service/kill the build to being able to read the logs. Not sure if Gradle is aware of 'infinite' tasks, so then it can disable that timer for that use case.

**Comment by eriwen** [comment]
@felipefzdz You mean using `--continuous` build?

**Comment by felipefzdz** [comment]
@eriwen that might be also, but I was referring to whatever task that triggers something designed to be executed without a fixed end, like an application server. In the particular example that I faced, I was running a Ratpack service through a [JavaExec](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html) task.

**Comment by eriwen** [comment]
Thanks for the clarification. For now, we recommend using `--console plain` until we come up with something better. Ideally, we'd have logs available outside the build output, even more ideally in a build scan.

**Comment by felipefzdz** [comment]
Cool, that's a good workaround. Thanks!

**Comment by eriwen** [comment]
Let's handle this with the solution proposed in https://github.com/gradle/gradle/issues/2252 and close this as a duplicate
