### ISSUE TITLE
[BUG] combined --console plain --quiet is no more silent

### ISSUE THREAD

**Issue by childnode** [gradle/gradle#1845]
the messages from the gradle wrapper when downloading the distribution - not existing locally yet - is printed to stdOut but is not hidden when run in `--quiet`/`-q` mode in combination with the -new, non standard option- `--console plain` (which is needed to switch back for the "old" output behaviour in 3.5+ >> https://docs.gradle.org/3.5/release-notes.html#console-upgrade)

----

**UPDATE**

it is reproducable with `--console plain -q [ :task]` since `plain` is someway interpretes as task upon parameter evaluation. 
`--console=plain -q  :task` works as expected as long `-q --console plain :task`

it is NOT restricted to 3.5 but also reproducable with 3.4.1 ... perhaps earlier I didn't tested yet ... don't know when `--console` option was added?!

----

### Expected Behavior
shut up, be quiet, do it silently in the background and only yell on errors ... as you did before ;)

### Current Behavior
yells progress and info to StdOut in --quiet mode when `--console plain` is enabled

### Steps to Reproduce (for bugs)
```
gradle init

## silent download of dist
rm -rf ~/.gradle/wrapper/dists/
./gradlew -q

## no more silent download
rm -rf ~/.gradle/wrapper/dists/
./gradlew --console plain -q

## works as expected (again)
rm -rf ~/.gradle/wrapper/dists/
./gradlew --console=plain -q
```

### Your Environment
apple, mac, sierra.4

#### changelog / releasenotes
> **Progress events for Gradle distribution download**
> The Tooling API can now report progress when it downloads of the Gradle distribution. A new type of ProgressEvent, called StatusEvent, is passed to the ProgressListener.statusChanged() method as the download proceeds.

**Comment by bmuschko** [comment]
Are you saying that the behavior changed between 3.4 and 3.5?

**Comment by childnode** [comment]
mhh .. since I thought the `--console plain` option was new in 3.5 .. yes, but I was wrong ... I see the option already exist in 3.4.1 (and lower?!) so the problem is the same for these versions. at least reproduced with 3.4.1 too. ... I'll change the topic

**Comment by bmuschko** [comment]
OK, thanks. The way you use this option is `--console=plain`. `--console plain` will not work.

**Comment by childnode** [comment]
so, then, we should update the doc, releasenotes, --help ... ;)
fun fact: it works, 'plain' is applied indeed but any option behind is ignored I think while upcoming tasks are executed as expected, so despite the fact `-q` is ignored, `./gradlew --console plain -q :test` is the same as `./gradlew --console=plain -q :test`

**Comment by eriwen** [comment]
@childnode Thanks for the additional detail. I messed up the release notes here and should've added `=`. I'll consider this a documentation bug for now.

**Comment by adammurdoch** [comment]
`--console plain` is identical to `--console=plain`. You can use either, or even both.

**Comment by childnode** [comment]
so, BUG (if space is valid) or FUG (documentation is wrong and space works unintentionally)?

**Comment by adamdougal** [comment]
This also happens if you have the quiet flag after the task you're trying to run e.g. `./gradlew tasks -q`.

I can't find anywhere in the [logging docs](https://docs.gradle.org/current/userguide/logging.html) that says these flags have to come before everything else.

**Comment by big-guy** [comment]
@adamdougal `./gradlew tasks` is always going to print something, regardless of `-q` or the order.  The order of the different logging flags relative to the tasks is not meaningful, please open a new issue if you're seeing this.

**Comment by childnode** [comment]
@adamdougal in addition to @big-guy I agree that this is a different "issue" because there even can be tasks that consume parameters, so -q|--quiet is a gradle option, not a task option, so it has to be set in front of any task|target

Btt: it is indeed weired, while it is common to allow to pass values to a parameter bei either using an equal sign or seperate it by blank

@adammurdoch as you can read above: it is not that irrelevant what you use ... that's why we have this FUG

I still don't see any clear positions, neither documentation nor any clear concept.. if one of it "should not" work, we should make it "not to work" to reduce confusion

**Comment by adamdougal** [comment]
Thanks for the explanation, I have raised a new issue https://github.com/gradle/gradle/issues/5098
