### ISSUE TITLE
JVM - Testing with nested modules doesn't execute all tests after failure in parent module

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#18452]
Hey,
My project contains nested modules. Each module has its own tests.
If any tests in the parent module fails, the tasks/tests in the nested modules are not executed too.
This results into wrong test coverage, and different number of executed tests.

### Expected Behavior

According to https://docs.gradle.org/current/userguide/java_testing.html#sec:test_execution:
`Note that, by default, the Test task always executes every test that it detects, irrespective of this setting.`, I would expect, Gradle executes all tests in all modules, even if some failed.

The sample contains 5 total tests, I would expect, all 5 tests are executed.

### Current Behavior

If tests in the parent module fails, the tasks/tests of nested modules are not executed at all.

The sample contains 5 total tests, only 2 are executed.

### Context
I have a big monolithic project with many nested modules. When running `test` on the root project, the `test` task of  nested modules is only called, when the `test` task of the parent module finished successfully. This results into not executed tests, a lower test coverage and different test execution time and flanky tests.

### Steps to Reproduce
See attached project, which contains 5 nested modules, each contains 1 test:

- a (test pass)
- - b (test failed)
- - - c (test not executed)
- - - - d (test not executed) 
- - - - - e (test not executed)

1. Run `./gradlew test` in root project

### Your Environment
Gradle 7.2
macOS 12 or Ubuntu 20.04 (CI)
Kotlin 1.5.31
Happen when executed in Terminal as well as in IntelliJ 2021.2

[testingGradle.zip](https://github.com/gradle/gradle/files/7242585/testingGradle.zip)
<img width="1440" alt="Bildschirmfoto 2021-09-28 um 10 58 49" src="https://user-images.githubusercontent.com/22521688/135057139-c94cddee-675f-4b27-a92f-85595dbc55df.png">
<img width="1440" alt="Bildschirmfoto 2021-09-28 um 10 59 17" src="https://user-images.githubusercontent.com/22521688/135057157-123ea877-6c4a-4aa4-bf83-13cb2c820d73.png">

**Comment by ljacomet** [comment]
As indicated by the documentation, tests _from the given task_ will all execute even if some fail.
However, Gradle will stop the build as soon as a _task_ fails.

If you want other tasks to be executed, use the [`--continue` flag](https://gradle.slack.com/archives/C012L0276KF/p1632759658089600).

**Comment by hfhbd** [comment]
@ljacomet Thank you!
