### ISSUE TITLE
The 'maven-publish' plugin to 'org.springFramework. boot' version 2.5.5 will automatically concatenate a 'plain' string

### ISSUE THREAD

**Issue by zxiaozhou** [gradle/gradle#18464]
### Current Behavior

1. When using maven-publish packaging, 'org.springFramework. boot' is version 2.5.5, and the jar name of the pushed Maven repository is automatically concatenated with a plain string after the version number
2. 'org.springFramework. boot' works when it is not 2.5.5, such as 2.4.5
![image](https://user-images.githubusercontent.com/62740686/135203554-8692ade8-6a92-4dbd-b3a5-7f9e0aed0ed2.png)
![image](https://user-images.githubusercontent.com/62740686/135203621-7b63acc1-c826-411e-87c9-e20346958844.png)

3. If org.springframework. boot is 2.5.5, the packaging value in the POM file description is also defined as POM
![image](https://user-images.githubusercontent.com/62740686/135205876-e51cd6ba-9031-42b8-8534-bd5dbf914fef.png)
![image](https://user-images.githubusercontent.com/62740686/135206161-80fe1a2c-0647-45ce-bb6f-f1df7133c13c.png)

**Comment by blindpirate** [comment]
That is called "classifier", which can be configured by plugin or in build script. If that behavior changes between spring boot plugin, it's possible that spring boot plugin does something different. You should report in spring boot plugin maintainer or manually "fix" it in your build script. 

Reference: https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html
https://docs.gradle.org/current/userguide/publishing_maven.html

**Comment by astellingwerf** [comment]
@zxiaozhou did you log a ticket with the Spring Boot plugin? Can you post a link to it here?
