### ISSUE TITLE
Design public API for retrieving elapsed time for build

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1846]
### Expected Behavior

Design a public API to retrieve the elapsed time for a build time.

### Current Behavior

Plugins have to use the internal and deprecated API `BuildRequestMetaData.getBuildTimeClock()` to retrieve the elapsed time for a build.

### Context

Currently, the build scan plugin is using this API.

**Comment by adammurdoch** [comment]
What would be the use case for this?

**Comment by bmuschko** [comment]
For more context see https://github.com/gradle/gradle/pull/1844. Do you have a better idea on how to approach this problem?

**Comment by adammurdoch** [comment]
I wouldn't add a public API if there's no public use case. I would also look at solving this by exposing a build operation start event with the appropriate timestamp on it rather than a new API.
