### ISSUE TITLE
if `--offline --scan` then fail fast

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#18474]
### Expected Behavior
If the user specifies "--offline" and "--scan" as command line arguments to Gradle, it would be nice for Gradle to fail early in the build to inform the user that the scan won't be published.

### Current Behavior
If the user specifies "--offline" and "--scan" as command line arguments to Gradle, Gradle runs the build and then at the end of the build, doesn't publish the scan

### Context
Our continuous integration builds specify "--offline" to improve reproducibility.
Sometimes it is useful to know what the continuous integration build is doing, so I ran the CI script and asked it to also make a build scan. When I did this I found that it ran the build but didn't make the scan, so it didn't give me very much helpful information. If Gradle specifies upfront that "--scan" is unsupported with "--offline" then the user can more easily decide sooner to remove "--offline" and try again.

### Workarounds
I'm planning to add this check into our gradlew

**Comment by psliwa** [comment]
@jbartok I've just provided PR: https://github.com/gradle/gradle/pull/18667

**Comment by big-guy** [comment]
@mathjeff You can still publish a build scan from a build that ran with `--scan` and `--offline`. 

There's a special task added by the build scan plugin that will publish the previous build's scan `gradle buildScanPublishPrevious`.

**Comment by mathjeff** [comment]
Oh cool

Your suggestion in https://github.com/gradle/gradle/pull/18667#issuecomment-949262978 to make this be mentioned in the scan message sounds to me like a good idea

Thanks
