### ISSUE TITLE
ProjectBuilder does not initialize settings so resolve() fails to throw useful exceptions in unit tests

### ISSUE THREAD

**Issue by tsmock** [gradle/gradle#18475]
### Expected Behavior
If a unit test is testing behavior when a specific exception is thrown (e.g., a `ModuleVersionNotFoundException` when attempting to resolve custom modules), it should receive the original exception _instead of a `new IllegalStateException`_.

### Current Behavior
As ProjectBuilder does not initialize settings, we get an [`IllegalStateException("The settings are not yet available...")`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java#L207-L212).

### Context
This modified behavior was introduced in f3274cb569f272d800e3b122178b37be2af14700.

In this case, I am using ProjectBuilder for unit tests, and one of the tests that was passing is now failing due to an IllegalStateException. While I was expecting an exception in that test, it was a GradleException. This did work with Gradle 6.4, but does not work with 7.2 (and probably 6.8).

Relevant code snippets from gradle (at 9f41801418d004596469f812f325ec934e7d9dad -- replace master in links below if needed):
* https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1390-L1397
* https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1412-L1424
* https://github.com/gradle/gradle/blame/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L739-L763

Relevant code snippets from project:
* https://gitlab.com/floscher/gradle-josm-plugin/-/blob/master/plugin/src/main/kotlin/org/openstreetmap/josm/gradle/plugin/util/JosmDependencyUtil.kt#L46-L55
  * The GradleException thrown is `org.gradle.internal.resolve.ModuleVersionNotFoundException` which is expected

Useful links:
* https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/testfixtures/ProjectBuilder.java

### Steps to Reproduce 
Repo in question: https://gitlab.com/floscher/gradle-josm-plugin
PR for updating gradle to 7.2: https://gitlab.com/floscher/gradle-josm-plugin/-/merge_requests/8 (note: the PR may have code working around this bug for unit tests)

### Solutions
* Have ProjectBuilder initialize settings
* Surround the `return` statement on DefaultConfiguration.java#L55 with a try-catch statement

Of the two, having ProjectBuilder initialize settings is probably the better option (maybe with a `withSettings` method).

**Comment by ov7a** [comment]
Sorry for the late reply!

`ProjectBuilder`is just a mock for some simple cases. Dependency resolution is beyond its scope. You should use a proper build for testing in your case. 

The problem is that your plugin (back then) did too much at configuration time, which is not compatible with `ProjectBuilder` and we do not have plans to support that.

This issue will be closed.
