### ISSUE TITLE
Stronger modeling of boolean CLI flags

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1847]
We have a bunch of build flags (daemon, parallel, configure-on-demand, build cache, etc) that should all work the same way and consistently.

### Expected Behavior
Avoid recurrence of bugs like #1827

### Current Behavior
Each boolean flag is implemented ad-hoc.

### Context
From Adam in #1828:

> it would be much better to model these using a type that represents a build flag and have command-line handling and property handling use this information to consistently implement support for build flags.

**Comment by alkemist** [comment]
I recently hit a case where I needed to know whether or not `--no-build-cache` was present. In other words, was caching explicitly disabled or just not explicitly enabled? Currently, we encode the default enabled-ness for build cache into `StartParameter`. It would likely be better to have this elsewhere and have `StartParameter` (and similar) just represent the inputs (i.e. separate the transform to effective inputs to be somewhere else).
