### ISSUE TITLE
String index out of range: 0 - FAILURE: Build failed with an exception. (App Center)

### ISSUE THREAD

**Issue by Aleksandern** [gradle/gradle#18500]
I can't build Android release on Microsoft App Center. But I can build locally without any problem.
Maybe somebody has any suggestions what's the problem?

My command
```
[command]/Users/runner/work/1/s/mobile/android/gradlew -DAPPCENTER_KEYSTORE_PASSWORD=*** -DMOBILECENTER_KEYSTORE_PASSWORD=*** -DAPPCENTER_KEYSTORE_FILE_ID=***.keystore -DMOBILECENTER_KEYSTORE_FILE_ID=***.keystore -DAPPCENTER_KEY_ALIAS=*** -DMOBILECENTER_KEY_ALIAS=*** -DAPPCENTER_KEY_PASSWORD=*** -DMOBILECENTER_KEY_PASSWORD=*** -p mobile/android clean :app:assembleRelease
```

I've got the error.
```
Starting a Gradle Daemon (subsequent builds will be faster)
Gradle 6.9
FAILURE: Build failed with an exception.
* Where:
Settings file ‘/Users/runner/work/1/s/mobile/android/settings.gradle’ line: 2
* What went wrong:
A problem occurred evaluating settings ‘ projname’.
> String index out of range: 0
```

`android/settings.gradle`
```
rootProject.name = 'projname'
apply from: new File(["node", "--print", "require.resolve('react-native-unimodules/package.json')"].execute().text.trim(), "../gradle.groovy"); includeUnimodulesProjects()
apply from: new File(["node", "--print", "require.resolve('@react-native-community/cli-platform-android/package.json')"].execute().text.trim(), "../native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

```

`build.gradle`
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "23.0.7599858"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.1")
    }
}
```

`gradle-wrapper.properties`
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

### Expected Behavior
Android apk file

### Current Behavior
error
```
FAILURE: Build failed with an exception.
* Where:
Settings file ‘/Users/runner/work/1/s/mobile/android/settings.gradle’ line: 2
* What went wrong:
A problem occurred evaluating settings ‘projname’.
> String index out of range: 0
```

### Context
I need to build Android release automatically after the master branch is updated but It doesn't work.

### Steps to Reproduce 
using Microsoft App Center

### Your Environment
Build scan URL: 
https://scans.gradle.com/s/yexdafzmped7y

**Comment by blindpirate** [comment]
The error already told you where the problem is, you need to fix your `settings.gradle` line 2. This is not a Gradle issue.

**Comment by Aleksandern** [comment]
@blindpirate 
But what should I fix in that file? Do you think it's related to 'react-native-unimodules' library or it's something with `settings.gradle` file ?

**Comment by blindpirate** [comment]
I have no idea, that's what you need to figure out. I don't have your code and can't reproduce it, also, the build scan you provided doesn't include the error at all, it's impossible for anyone to troubleshoot with the information you provided. Either figure it out yourself, or provide more information (code, reproducer, correct build scan).
