### ISSUE TITLE
buildSrc plugin using AWS conflicts with impldep AWS

### ISSUE THREAD

**Issue by dsvensson** [gradle/gradle#18534]
Just tried to create a plugin under buildSrc that updates an AWS Lambda function, and it fails with `java.lang.NoSuchFieldError: DOCUMENT` when deserializing response from the AWS service due to `MarshallingType` interface being found in `org.gradle.internal.impldep.com.amazonaws.protocol`, which is of an older version than I'm using in buildSrc (2.17.15).

The problem is similar to that of BouncyCastle, #16605

Using Gradle 7.1, Java 11, Ubuntu 21.04.

**Comment by breskeby** [comment]
Do you have the source of that plugin available so we can reproduce the problem. Or maybe create a stripped down reproducible sample to make reproducing this issue?

**Comment by dsvensson** [comment]
buildSrc/main/kotlin/foo
```kotlin
package foo

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.property
import software.amazon.awssdk.services.lambda.LambdaClient

open class AwsLambdaUpdateCodeTask : DefaultTask() {
	@Input val functionName: Property<String> = project.objects.property()
	@Input val imageUri: Property<String> = project.objects.property()

	@TaskAction
	fun execute() {
		if (!functionName.isPresent)
			throw GradleException("functionName is mandatory")
		if (!imageUri.isPresent)
			throw GradleException("imageUri is mandatory")

		val client = LambdaClient.create()

                         // breaks here when deserializing first message due to using wrong class
                        // java.lang.NoSuchFieldError: DOCUMENT
			client.updateFunctionCode { req ->
				req.functionName(functionName.get())
				req.imageUri("bah")
			}

			client.waiter().waitUntilFunctionUpdated { req ->
				req.functionName(functionName.get())
			}

	}
}
```

```kotlin
package foo

import org.gradle.api.Plugin
import org.gradle.api.Project

class AwsPlugin : Plugin<Project> {
	override fun apply(project: Project) {
		project.tasks.register("updateLambdaImage", AwsLambdaUpdateCodeTask::class.java)
	}
}
```

buildSrc/build.gradle.kts
```kotlin
plugins {
	`kotlin-dsl`
}

repositories {
	mavenCentral()
}

dependencies {
	implementation(libs.aws.sdk.lambda)
}

gradlePlugin {
	plugins {
		create("awsLambda") {
			id = "foo"
			implementationClass = "foo.AwsPlugin"
		}
	}
}
```

**Comment by dsvensson** [comment]
Annoying. Prepped a separate repo for this and it works. Do you have any suggestions on how to continue troubleshooting? It fails reliably in my main repository. 

I've added the same set of plugins without apply: false to the top script, but without using them, hoping that will load them, added similar dependencies {} to the only subproject that uses the buildSrc plugin described here.

The main projects is close to a hundred of modules (i've made one in the test proj) so it's not really possible to create something identical, but it doesn't feel like dependencies {} should be causing this right? Those shouldn't be in the build system class path? 

If plugins don't load even if omitting apply: false, then perhaps that might not be enough to determine if any other plugin is to blame. 

The test proj doesn't use version catalog, but tried removing it from the main repo for buildSrc and that didn't change anything.

**Comment by dsvensson** [comment]
Found it! The problem was that the main repo used the `com.github.burrunan.s3-build-cache` plugin in settings.build.kts which leaks its outdated AWS dependency. Still curious of if it's possible to list classloading in a way that would show this problem.
