### ISSUE TITLE
Update Kotlin logo in the documentation samples

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#18532]
### Expected Behavior

Gradle documentation should use the current Kotlin logo:

<img width="55" alt="the new Kotlin logo" src="https://user-images.githubusercontent.com/213894/135964907-f4052e7d-f4a3-4d55-8049-7f4a16977af8.png">

### Current Behavior

Gradle uses an old logo:
<img width="289" alt="old Kotlin logo in Gradle documentation" src="https://user-images.githubusercontent.com/213894/135964965-8547809b-b397-48f7-a73e-93a78113d9cd.png">

### Context

https://blog.jetbrains.com/kotlin/2021/07/adding-volume-to-the-kotlin-identity/
See the `download new logo` link in the article: https://resources.jetbrains.com/storage/products/kotlin/docs/kotlin_logos.zip

**Comment by jvandort** [comment]
Fixed by #21295
