### ISSUE TITLE
Add support for macros and include files in assembler sources

### ISSUE THREAD

**Issue by javaJake** [gradle/gradle#1853]
I'm carrying an issue over from JIRA: https://issues.gradle.org/browse/GRADLE-3398

> Assembler files can have include files (like #include, but syntax varies between assemblers). Assemblers can also define macros (like the other native languages). Right now, these files aren't included as inputs, so incremental build does not work when includes are used. Macros can be defined, but they must be done at a lower level (directly manipulating the assembler args).

### Expected Behavior
Gradle should have a good enough understanding of macros to process all #include directives.

### Current Behavior
Gradle assumes a large amount of C++ is out-of-date and compiles too many files when one header changes.

### Context
This is a big deal when making and testing incremental changes, particularly when debugging. Adding a debug log message, for example, causes a lot of rebuilding.

### Steps to Reproduce (for bugs)
I don't have a good set of steps. Hopefully this issue is self-explanatory?

### Your Environment
Gradle 3.5 using the "c" and "cpp" plugins.

**Comment by lacasseio** [comment]
This issue is mostly tracked by https://github.com/gradle/gradle-native/issues/302. I'm closing this in favour of the other issue.
