### ISSUE TITLE
Update Java plugin documentation to mention new Configurations

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1854]
Now that the `java-library` plugin has seen some action, the fact that we don't document the new Configurations in the `java` plugin user guide is causing some confusion. We want to deprecate `compile` and `runtime` in favor of `implementation` and `runtimeOnly` in the long run, but currently we're only telling users about them in the `java-library` section of the user guide. 

We should change the user guide such that it is clear that `compile` and `runtime` are deprecated and explain `implementation` and `runtimeOnly` instead. We should also point them at the `java-library` plugin if they need to define an `api`.

**Comment by oehme** [comment]
@eljobe Assigning to you as this user guide chapter could use a fresh perspective. The chapter for the `java-library` plugin already shows the new configurations, but please feel free to improve that one as you see fit as well.

**Comment by eljobe** [comment]
I've opened a pull request, but I'm not really that excited about what I've written. I'm not sure how to make the situation better though.
