### ISSUE TITLE
Using internal sourcesJar task with gradle 7.2 and java>8 with modules prints deprecations warnings

### ISSUE THREAD

**Issue by patton73** [gradle/gradle#18563]
Java version: 16
gradle version: 7.2

build.gradle code

task sourcesJar(type: Jar) {
    from sourceSets.main.allSource
    classifier = 'sources'
}

deprecation warnings:

Execution optimizations have been disabled for task ':sourcesJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '../build/classes/module-info'. Reason: Task ':sourcesJar' uses this output of task ':compileModuleInfoJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a problem with the following location: '../build/classes/module-info'. Reason: Task ':sourcesJar' uses this output of task ':compileModuleInfoJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.

**Comment by patton73** [comment]
Using 

java {
    withSourcesJar()
    withJavadocJar()
}

leads to the same exact error/warning. Nothing changed.

```
Execution optimizations have been disabled for task ':sourcesJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: 'xx/build/classes/module-info'. Reason: Task ':sourcesJar' uses this output of task ':compileModuleInfoJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
Gradle detected a problem with the following location: 'xx/build/classes/module-info'. Reason: Task ':sourcesJar' uses this output of task ':compileModuleInfoJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Execution optimizations are disabled to ensure correctness. See https://docs.gradle.org/7.2/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

For investigating this, we need a full reproducer to understand why Gradle complains.

**Comment by donat** [comment]
> Do you mean you need a complete project?

Yes.

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue is no longer relevant for newer versions of Gradle. It fails with a proper error with Gradle 8.2 now. Most probably it was caused by a modularity plugin, `org.javamodularity.moduleplugin`. The reason behind this error is that all outputs to `sources` should be registered.

Please open a new issue if you still have problems with Gradle 8.0+ and you can confirm it is not caused by the plugin.

See also this issue:
* https://github.com/java9-modularity/gradle-modules-plugin/issues/220
