### ISSUE TITLE
Gradle removes C/C++ tasks from execution plan when the source is not initially available, even if it's available later

### ISSUE THREAD

**Issue by javaJake** [gradle/gradle#1856]
### Expected Behavior
Gradle should always include native build tasks, regardless of whether source is available at execution planning time or not.

### Current Behavior
Gradle silently ignores libraries that do not have source present on disk at execution planning time.

### Context
This affects me specifically because I use an external dependency resolver tool. A simple "dependsOn" is used to ensure that the external tool is run before the library is built (and even works with parallel execution).

I noticed that on the first run, Gradle silently drops the libraries that had their source downloaded during a custom task from the execution plan, which means of course their dependent libraries fail to link. On the following runs, because the source is now downloaded and available, Gradle includes the libraries' tasks in the execution plan, and they finally compile in time for linking to occur.

### Steps to Reproduce (for bugs)
1. Write a "dependency" NativeLibrarySpec component.
2. Write a "dependent" NativeLibrarySpec component.
3. Move the source of the "dependency" component so it is not visible to Gradle.
4. Run Gradle.

Gradle will silently ignore the "dependency" build tasks and attempt to build "dependent". Gradle should either error (since there are dependent tasks that can't run without "dependency" building) or warn.

### Your Environment
Gradle 3.5 with the "c" and "cpp" plugins included.
Windows 7 64-bit, Visual Studio 2013 Express Edition for Windows Desktop

**Comment by javaJake** [comment]
For the time being, removing the hasOutputs check wrapping the `return AbstractNativeLibraryBinarySpec.this.getBuildDependencies();' line in AbstractNativeLibraryBinarySpec works around the issue for me.

**Comment by javaJake** [comment]
Actually, that workaround didn't work at all. This one did:

```
	source {
		srcDir '.'
		include '.empty.h'
	}
```
(where .empty.h has a simple line of no-op code to keep the compiler happy.)

**Comment by lacasseio** [comment]
Thanks for reporting this @javaJake. Have you tried [`generatedBy`](https://github.com/gradle/gradle/blob/master/subprojects/platform-base/src/main/java/org/gradle/language/base/LanguageSourceSet.java#L38) on as shown in the [IDL sample](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/native-binaries/idl)?

**Comment by javaJake** [comment]
@lacasseio thanks for the idea. Unfortunately, that does not work here because the "NativeComponentModelPlugin.Rules#configureGeneratedSourceSets" rule fails to apply as the task I give it to be "generatedBy" does not have a sourceDir.

I suspect there is a bug here too, since the private method "maybeSetSourceDir" there is a check to see if task.property is not null, which I suspect is a check to see if it exists. The task.property method actually throws a MissingPropertyException instead of/in addition to returning null, which causes Gradle to quit with an error.

**Comment by lacasseio** [comment]
No additional work will be done on the software model plugins unless it's a blocker for current users. This is not a blocker so I'm closing this issue. Reopen on [gradle/gradle-native](https://github.com/gradle/gradle-native).
