### ISSUE TITLE
Add Official API to resolve deferred construct

### ISSUE THREAD

**Issue by anatawa12** [gradle/gradle#18562]
Until Gradle 7.1, We unofficially can use DeferredUtil to resolve deferred construct. But it's removed in 7.1 so I'm looking for a replacement for it.
I want to support Gradle until 5.1 so I don't want to write my own DeferredUtil and without official API, I can't support additional ways of deferred construct in the future.

### Expected Behavior

Provide API to resolve deferred construct.

### Current Behavior

No official API to resolve deferred construct. It's possible to call `org.gradle.utils.internal.DeferredUtil`, internal library.

**Comment by anatawa12** [comment]
I want to implement properties which accepts something like Callable as properties like SigningExtension#required does.

**Comment by wolfs** [comment]
@anatawa12 How about you use a `Property<Boolean>`? That is evaluated lazily and can be wired up to other tasks/extensions.

**Comment by grossws** [comment]
IIRC you could use `property.convention(providers.provider(Callable))` in such case, see https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java#L55

**Comment by ov7a** [comment]
Sorry for the late reply.

We believe this issue is no longer relevant. Please file a new issue if necessary.
