### ISSUE TITLE
org.gradle.configureondemand causes build failure in multi module project

### ISSUE THREAD

**Issue by aaudin90** [gradle/gradle#18583]
After upgrading AGP from 4.2 to 7.0.2 I get a similar error:

```
What went wrong:
Execution failed for task ':core-testing:dependencies'.
> Could not resolve all dependencies for configuration ':core-testing:debugRuntimeClasspath'.
   > A problem occurred configuring project ':features-core'.
      > java.lang.IllegalStateException: Accessing GradleBuildProject.Builder through AnalyticsConfiguratorService is not allowed after AnalyticsService is created.
```
But setting `org.gradle.configureondemand = false` solves the problem.

Use:
gradle-7.2
AGP-7.0.2

**Comment by aaudin90** [comment]
I cannot identify any features. 

Can you tell me what this error means, maybe it will lead to certain thoughts?
`java.lang.IllegalStateException: Accessing GradleBuildProject.Builder through AnalyticsConfiguratorService is not allowed after AnalyticsService is created.`

**Comment by EdricChan03** [comment]
This is definitely from AGP's side: seems that an [issue was filed on February of 2023](https://issuetracker.google.com/issues/270731522), so I'm guessing it can be closed
