### ISSUE TITLE
Race condition with build service registration and configuration on demand

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#18587]
Some build services may be registered during execution phase (with configuration on demand enabled), and this may result in race condition. E.g https://youtrack.jetbrains.com/issue/KT-49043.

Currently in the Kotlin Gradle plugin, registration of build services [synchronizes](https://github.com/JetBrains/kotlin/blob/360c0170bec6fa96ac26c2be40717eb8ce5e31e8/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/Tasks.kt#L156) on `Gralde.sharedServices` instance to avoid this issue, but I'd be great to fix this in Gradle.

**Comment by gavra0** [comment]
This issue is now more common with parallel model building.

**Comment by bamboo** [comment]
The fix will be backported to 7.4.2.

**Comment by bamboo** [comment]
Fixed in 7.4.2.

**Comment by gavra0** [comment]
Can we please reopen the issue as it is pretty easy to run into race condition, given the API that exposes `registration` and encourages patterns such as `registrations.getByName(...)`? Can we consider deprecating that API and exposing `getByName()` on the `BuildServiceRegistry` directly? //cc @adammurdoch

**Comment by hungvietnguyen** [comment]
FYI: I filed https://github.com/gradle/gradle/issues/32239 to address the remaining issue ("`gradle.sharedServices.registrations.getByName()` is not thread safe").
