### ISSUE TITLE
Unable to find Gradle tasks to build: [:]

### ISSUE THREAD

**Issue by kitkatRC** [gradle/gradle#18592]
Unable to find Gradle tasks to build: [:]. 
		Build mode: SOURCE_GEN. 
		Tests: None.

**Comment by lijiaxiss** [comment]
Unable to find Gradle tasks to build: [:]. Build mode: COMPILE_JAVA. Tests: All.

**Comment by blindpirate** [comment]
Closed due to inactivity.
