### ISSUE TITLE
NPE in comparing enums with constant bodies

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#1861]
A NullPointerException may be thrown when task input is a enum with constant body.

### Expected Behavior

No NPE thrown.

### Current Behavior

NPE thrown.

### Context & Steps to Reproduce

It's easy to reproduce this issue. For example, we have a enum class (it must be `.java`, since `groovyc` will handle this in a slightly different way described below):
```
public enum TestEnum {
    A {
        @Override
        public void foo() {
        }
    },
    B {
        @Override
        public void foo() {
        }
    };

    public abstract void foo();
}
```
and `build.gradle`:
```
class EnumIssueTask extends DefaultTask {
    @Input
    TestEnum getEnum() {
        if (System.currentTimeMillis() % 2 == 0) {
            return TestEnum.A
        } else {
            return TestEnum.B
        }
    }

    @OutputDirectory
    File getDir() {
        return getProject().getRootDir()
    }
}

task hello(type: EnumIssueTask)
```

Run `gradle hello` several times and you can get
```
* Exception is:
java.lang.NullPointerException
        at org.gradle.util.DiffUtil.checkEnumEquality(DiffUtil.java:80)
        at org.gradle.util.DiffUtil.checkEquality(DiffUtil.java:65)
        at org.gradle.util.DiffUtil.diff(DiffUtil.java:57)
        at org.gradle.api.internal.changedetection.rules.InputPropertiesTaskStateChanges.addAllChanges(InputPropertiesTaskStateChanges.java:42)
        at org.gradle.api.internal.changedetection.rules.SimpleTaskStateChanges.iterator(SimpleTaskStateChanges.java:29)
...
```

The reason is that according to [JLS](http://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.9),

> The optional class body of an enum constant implicitly defines an anonymous class declaration (§15.9.5) that extends the immediately enclosing enum type.

enums with class bodies will be implemented as anonymous classes, which results in [`getCanonicalName()`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/util/DiffUtil.java#L80) returning `null`.

```
    /**
     * Returns the canonical name of the underlying class as
     * defined by the Java Language Specification.  Returns null if
     * the underlying class does not have a canonical name (i.e., if
     * it is a local or anonymous class or an array whose component
     * type does not have a canonical name).
     * @return the canonical name of the underlying class if it exists, and
     * {@code null} otherwise.
     * @since 1.5
     */
     public String getCanonicalName()
```

Note that this issue won't be triggered by enums written in Groovy. `groovyc` will compile enum with class body into class file without [EnclosingMethod Attribute](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.7), which just avoids this issue.

### Your Environment

OS X 10.12, JDK1.8_121

**Comment by bmuschko** [comment]
Thanks for reporting. Is this an issue that only occurs with Gradle 3.5 or does it also occur with earlier versions?

**Comment by blindpirate** [comment]
I observed this issue in both `3.4.1` and `3.5`. According to [the history](https://github.com/gradle/gradle/commit/9bde5622cc4ef9cdb8e1625d26b6dd5f748d61fa), it seems to be imported in July, 2016.

**Comment by bmuschko** [comment]
Thanks for feedback and the PR. We'll review soon.
