### ISSUE TITLE
7.3-rc-1 --project-cache-dir incompatible with org.gradle.vfs.watch=true

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#18626]
### Expected Behavior
`./gradlew :help` should succeed even when passing `--project-cache-dir somedir` and setting `org.gradle.vfs.watch=true`.

### Current Behavior
I observe that `./gradlew --project-cache-dir gradle-project-cache :help` fails when setting `org.gradle.vfs.watch=true`:

```
/usr/local/google/workspace/gradle-samples/project-cache-dir-watch (master)$ ./gradlew --project-cache-dir gradle-project-cache :help

FAILURE: Build failed with an exception.

* What went wrong:
Should be in state Finished.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 642ms
```

### Context
AndroidX uses both of these features and this causes our builds to fail with version 7.3-rc-1 of Gradle. Our builds succeed with Gradle 7.2, however.

### Steps to Reproduce
See https://github.com/mathjeff/gradle-samples/tree/master/project-cache-dir-watch

**Comment by lptr** [comment]
This is a legitimate error, as with our current setup we cannot probe the build directory without a project cache directory right underneath it. What we'll do here is improve the error message to be clear what the user has to do to avoid it, see #18635.
