### ISSUE TITLE
Update bundled JUnit 5 launcher

### ISSUE THREAD

**Issue by Marcono1234** [gradle/gradle#18627]
It appears Gradle currently bundles an outdated JUnit 5 version ([version 5.7.2](https://github.com/gradle/gradle/blob/7f0fa1a9da21adaeef7ab0763397fdf2e6ef4e22/subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmTestSuite.java#L48)?)
This issue was originally reported as https://github.com/junit-team/junit5/issues/2730.
I think it is also unexpected that Gradle's bundled JUnit 5 version seems to have higher precedence than the version explicitly specified by the user. But maybe that is intended?

(The newly added [`JvmTestSuite.useJUnitJupiter​(String version)`](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/jvm/JvmTestSuite.html#useJUnitJupiter-java.lang.String-) seems to be affected as well)

### Expected Behavior
- Gradle should use a recent JUnit 5 version, e.g. currently 5.8.1
- Gradle should prefer the explicitly specified JUnit 5 dependency version over the bundled version (?)

### Current Behavior
- Gradle uses a slightly outdated JUnit 5 version
- Unless specified with `testRuntimeOnly` Gradle seems to prefer its bundled JUnit 5 version over the user specified version

### Context
See https://github.com/junit-team/junit5/issues/2730

**Comment by arjenzhou** [comment]
Hi, it there any progress? 
Or any help I can made? Though it may cost days or months for a newbie for gradle.

**Comment by jjohannes** [comment]
This issue exists for several Gradle versions now. I would classify this as a bug.

Is there anything blocking Gradle from updating the bundled launcher?

I agree with https://github.com/gradle/gradle/issues/18627#issuecomment-944124855 that the better solution would be to not bundle at it all. But for now, could the bundled launcher be upgraded?

**Comment by alllex** [comment]
This was fixed in #20703, but the link to the PR has been missing
