### ISSUE TITLE
gradle capabilities

### ISSUE THREAD

**Issue by wind57** [gradle/gradle#18655]
I am reading the documentation here : https://docs.gradle.org/current/userguide/dependency_capability_conflict.html#sub:capabilities

Specifically, I am looking at this:

> Each component defines an implicit capability corresponding to its GAV coordinates (group, artifact, version)

My understanding is that if I have a very simple `build.gradle`:

```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.0-alpha5'
    implementation 'ch.qos.logback:logback-classic:1.3.0-alpha10'
    implementation 'org.slf4j:slf4j-simple:2.0.0-alpha5'

    configurations.all {
        {
            x -> x.getResolutionStrategy().getCapabilitiesResolution().all({ y -> println y })
        }
    }
}
```

I would see them in the output, but this does not happen. Is this me miss-understanding something?

**Comment by donat** [comment]
I've checked your sample again. The immediate problem with your sample is that you have double curly braces after `configurations.all`.
```
configurations.all {
        {
// ...
        }
    }
```

This yields to a closure declaration when the `all` action is being executed.
