### ISSUE TITLE
Gradle task input validation: Warn about use of `PathSensitivity.RELATIVE` on a `RegularFileProperty`

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#18668]
### Context
We recently ran into a bug in the Android Gradle plugin where we had the following task input:

```
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val listingFile: RegularFileProperty
```

where the path of `listingFile` is used in the task action.

When we used `PathSensitivity.RELATIVE`, the intention was that it should be relative to the project root. (*)

However with Gradle, for a `RegularFileProperty`, [`PathSensitivity.RELATIVE`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitivity.html#RELATIVE) is exactly the same as [`PathSensitivity.NAME_ONLY`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitivity.html#NAME_ONLY), so the path to the file is actually not part of the task's inputs (only its name), and we had a bug where the file path changes but the task does not re-run.

### Feature Request

I suspect the misconception at (*) is common because while it's not according to the Gradle docs, it is very intuitive.

When `PathSensitivity.RELATIVE` is used on a `DirectoryProperty`, it's hard to tell which way the user interprets `RELATIVE`. But when `PathSensitivity.RELATIVE` is used on a `RegularFileProperty`, it is likely that it is misused, as shown above.

So it would be nice if there was a warning about use of `PathSensitivity.RELATIVE` on a `RegularFileProperty`.

**Comment by lptr** [comment]
Thanks for the feedback! We recognize that there is room for improvement here. However, we'd like to address this in a more holistic manner. The idea that we'd like to implement is to "merge" `NAME_ONLY` and `RELATIVE` into a new `PathSensitivity.DEFAULT` that would basically mean what `RELATIVE` means currently for directory structures, and `NAME_ONLY` for individual root elements in a file collection.
