### ISSUE TITLE
Move Untracked annotation to task level

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#18660]
In Gradle 7.3 we made the distinction explicit between stuff on the file system that Gradle is supposed to understand (and optimize execution using that understanding when possible), and stuff that Gradle is not supposed to understand (and hence no optimization).

We implemented this via the `@Untracked` annotation on task input and output properties (as well as an `untracked()` method in the runtime task input/output API).

From feedback on 7.3-rc-1 it seems that the resulting API is somewhat confusing, and moving the annotation and runtime method to the task level makes more sense.

Doing so actually simplifies things inside Gradle as well, as the effect of marking any of the inputs or outputs of a task with `@Untracked` already meant that we treated the task itself as untracked.

Furthermore, it makes the case of the `Copy` task more consistent, since instead of introducing a new method for `Copy` to mark it untracked, the general mechanism to mark any task untracked can be used by `Copy` as well.

---
cc: @gradle/execution

**Comment by wolfs** [comment]
The changes are on `release` now.
