### ISSUE TITLE
[IntelliJ][Run/Debug configuration] Upgrading from 3.3 to 3.5 in a multi-module spring boot project added NoClassDefException of my main class

### ISSUE THREAD

**Issue by kopax** [gradle/gradle#1867]
I am using Gradle wrapper in a multi module spring-boot project.

When I tried to upgrade to **Gradle 3.5**, I have a **NoClassDefException** error on my main application class which is at the root project. 

This error only happen when trying to launch in **IntelliJ** with the **Run/Debug configuration**

It is also the only class in the root project and take care of enabling spring boot application with the annotation `@EnableSpringBootApplication` and configuration with the annotation `@EnableAutoConfiguration`.

I have also tested with **v3.4** and the **error appeared** on  **Gradle 3.4**!

Reverting to **Gradle 3.3** corrected the issue.

I wonder if this is due to a new synthax that make my `build.gradle` files obsoletes.

**Project structure**

    api [api_main]
        | src/main/java/com/domain/api/ApiAplication.java
        | build.gradle
        | gradle.properties
        | settings.gradle
        | application [module api-application]
           | build.gradle
        | core [module api-core]
           | build.gradle
        | user [module api-user]
           | build.gradle

```


### Expected Behavior

```bash
$    ./gradlew wrapper --gradle-version 3.5
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_33v9e3ca9ijszapnqmfnqb7f5.run(/workspace/git.domain.com/domain/api/build.gradle:50)
:wrapper

BUILD SUCCESSFUL

Total time: 1.411 secs

$ cat gradle/wrapper/gradle-wrapper.properties 
#Fri Apr 21 15:08:47 ICT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-bin.zip


```

I then run a build 

    ./gradlew clean build

And start my application using **Run/Debug configuration** of IntelliJ

### Current Behavior

Starting with IntelliJ fail with this error : 

```
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Dspring.output.ansi.enabled=always -Didea.launcher.port=7533 -Didea.launcher.bin.path=/opt/idea/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar:/workspace/git.domain.com/domain/api/build/classes/main:/workspace/git.domain.com/domain/api/build/resources/main:/opt/idea/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain com.domain.api.ApiApplication --debug
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at com.kopaxgroup.api.ApiApplication.main(ApiApplication.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

Process finished with exit code 1
```

Using the jar directly work fine : 

    ./gradlew build --info && java -jar build/libs/app.jar

### Context

Using this version of Intellij:

    IntelliJ IDEA 2016.1.3
    Build #IU-145.1617, built on June 3, 2016
    JRE: 1.8.0_76-release-b198 amd64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I created a new **Run/Debug Configuration**

    Main class: com.domain.api.ApiApplication
    Use classpath of module: api_main
    Enable debug output: true

### Your Environment

```
$ uname -a
Linux dev-01 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
$ java -version
java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by bmuschko** [comment]
Try to upgrade to the latest version of IntelliJ. I believe there was a bug.

**Comment by bmuschko** [comment]
@kopax Could you solve your problem?

**Comment by kopax** [comment]
@bmuschko I couldn't. I am trying to get to the point where I have enough time to retest fully this.

**Comment by bmuschko** [comment]
@kopax OK, just as a heads up: I am going to close if I don't hear back from you within a week. I don't want to keep this issue open for ever more. If you happen to check it later and still have the issue then we can reopen.

**Comment by kopax** [comment]
Agree, I will reopen it as soon as I have more information. Thanks for being around!
