### ISSUE TITLE
Scala class files appearing twice in classes output dir

### ISSUE THREAD

**Issue by Arthurm1** [gradle/gradle#18681]
Using the 7.3-20211016025230+0000 nightly.

Intermittently I get Scala class output files appearing in both `.../build/classes/scala/...` and `.../build/classes/java/...`

Sometimes, but not always, this then causes the Jar creation to error with `Entry XXX$.class is a duplicate but no duplicate handling strategy has been set`

I have a mixed Java/Scala multi-project setup but this will happen in a subproject that has purely Scala sources although seems to happen more often when a project has both java and scala sources.

The project can repeatedly compile correctly and then I'll run `gradlew classes` and a sub-project, that was already built and didn't need recompiling and had only a `.../build/classes/scala/...` directory, will suddenly gain a `.../build/classes/java/...` directory with the same contents as `.../build/classes/scala/...` but with timestamps that are later

Sorry - it's an internal project so I can't share the code.

### Your Environment
Mixed Scala 3/Java project with multiple sub-projects
Gradle: 7.3-20211016025230+0000
platform: Windows 10
java: 17

**Comment by ljacomet** [comment]
Related issue #12638
