### ISSUE TITLE
`signing` plugin doesn't sign all files

### ISSUE THREAD

**Issue by vvb2060** [gradle/gradle#18686]
### Steps to Reproduce 
```sh
git clone https://github.com/LSPosed/AndroidHiddenApiBypass.git
cd AndroidHiddenApiBypass
#echo signing.keyId=xxx >>gradle.properties
#echo signing.secretKeyRingFile=xxx >>gradle.properties
#echo signing.password=xxx >>gradle.properties
./gradlew publishToMavenLocal
ls ~/.m2/repository/org/lsposed/hiddenapibypass/hiddenapibypass/2.1/
```

### Expected Behavior
`hiddenapibypass-2.1-javadoc.jar.asc` exists

### Current Behavior
`hiddenapibypass-2.1-javadoc.jar.asc` not found

### Context
After remove `withSourcesJar()`, the javadoc.jar can be signed properly.
https://github.com/LSPosed/AndroidHiddenApiBypass/blob/main/library/build.gradle#L39
```
    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
```
Edit to:
```
    publishing {
        singleVariant("release") {
            withJavadocJar()
        }
    }
```
Since both sources.jar and javadoc.jar are generated normally, only one signature file is missing, I think there might be a problem with gradle.

### Your Environment
GitHub Actions: https://github.com/LSPosed/AndroidHiddenApiBypass/actions/runs/1355419256

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
