### ISSUE TITLE
org.gradle.parallel=false is broken

### ISSUE THREAD

**Issue by dzwicker** [gradle/gradle#1869]
### Expected Behavior
Using -Dorg.gradle.parallel=false on the command line should disable parallel execution of tasks

### Current Behavior
Task are executed in parallel

```
00:00:17.183 + ./gradlew --no-daemon --project-prop jacoco=true --exclude-task classes --exclude-task jar -Dorg.gradle.parallel=false -Dorg.gradle.configureondemand=false check dependencyCheck sonarqube
00:00:19.928 Parallel execution is an incubating feature.
```

**Comment by bmuschko** [comment]
Thanks for reporting. It already has been reported so I am closing your issue as duplicate: https://github.com/gradle/gradle/issues/1827.
