### ISSUE TITLE
Wrapper task API for configuring DEFAULT_JVM_OPTS

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#1871]
### Expected Behavior
It would be awesome if the wrapper task had a variable that you could set to configure the `DEFAULT_JVM_OPTS` argument in the generated wrappers.

### Current Behavior
Current required code:
```kotlin
task<Wrapper>("wrapper") {
    distributionUrl = "https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170404014535+0000-all.zip"
    distributionType = Wrapper.DistributionType.ALL

    // Custom JVM args that we want to always run gradle with
    val jvmOpts = "-Xmx3072m -Xms256m"
    // Make sure you make the args an input incase they change
    inputs.property("jvmOpts", jvmOpts)

    doLast {
        // Write these variables to the JVM ops variable in the wrappers.
        val optsEnvVar = "DEFAULT_JVM_OPTS"
        scriptFile.writeText(scriptFile.readText().replace("$optsEnvVar=\"\"", "$optsEnvVar=\"$jvmOpts\""))
        batchScript.writeText(batchScript.readText().replace("set $optsEnvVar=", "set $optsEnvVar=$jvmOpts"))
    }
}
```
This is the kotlin version of the code that this project already uses here:
https://github.com/gradle/gradle/blob/a7cbf8a695de33cbea9b921739435a361d9e5b87/gradle/wrapper.gradle#L41-L47

### Context
If you hardcode the `DEFAULT_JVM_OPTS` in your wrapper every time you update gradle and regenerate the wrapper code the variable gets blown away.

### Your Environment
Gradle Version: `3.5-20170404014535+0000l`
```
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

**Comment by jbartok** [comment]
Sorry for the late reply. 

This feature request is in the backlog of the relevant team and is prioritized by them.
***
The Application plugin provides the needed options, and exposing them in the Wrapper task could make sense.
