### ISSUE TITLE
Make gradle-wrapper.jar downloadable on demand

### ISSUE THREAD

**Issue by happylynx** [gradle/gradle#18718]
Allow `gradle-wrapper.jar` to be downloaded when neede (when not present) instead of forcing users of gradle wrapper to commit `gradle-wrapper.jar` into VCS.

### Expected Behavior

Gradle wrapper files that are expected to be managed by VCS:
```
gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/wrapper-downloader.java
gradlew
gradlew.bat
```

`gradle/wrapper/gradle-wrapper.jar` is moved to outside of `gradle/wrapper/` to e.g. `.gradle/`

When user invokes `gradlew` it checks for presence of `.gradle/gradle-wrapper.jar`. If not present it invokes `gradle/wrapper/wrapper-downloader.java` using single source file launch ([JEP330](https://openjdk.java.net/jeps/330)) that downloads `.gradle/gradle-wrapper.jar` and verifies it's checksum. Then `gradlew` delegates to `.gradle/gradle-wrapper.jar` as it currently does. 

### Current Behavior

Gradle wrapper files that are expected to be managed by VCS:
```
gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.jar
gradlew
gradlew.bat
```

### Context

The change allows to
* save space in VCS history
* avoid saving binary blobs in VCS which is often considered a bad practice

Current setup forces users to manage `gradle-wrapper.jar` by a versioning system even though keeping history of Gradle binaries brings little of benefit.

Proposed setup allows to store text files only in VCS, that have relatively small probability of change among Gradle versions. `gradle-wrapper.jar` is changed every Gradle release. As a compressed binary file it is difficult to compress using diff compression (as git packed objects do it).

Alternative could be using local Gradle installation for price of losing guaranteed uniform build environment and an extra step during project setup when Gradle is not locally installed.

**Comment by vlsi** [comment]
I believe this issue duplicates
* https://github.com/gradle/gradle/issues/11816

@happylynx , would you please double-check and close 18718?

**Comment by happylynx** [comment]
Duplicate of #11816

**Comment by JOHNB5266** [comment]
my wrapper is not present in my graddle
