### ISSUE TITLE
Gradle doesn't correctly kill subprocesses on interrupt on Windows. It should.

### ISSUE THREAD

**Issue by doctorpangloss** [gradle/gradle#18716]
1. Use Windows.
 2. Open a console of any kind, in any Windows environment - `cmd`, `powershell` or the `bash` that ships with `git`.
 2. Start a `gradle` task with an `exec` that never finishes.
 3. Hit Ctrl+C or any preferred interrupt method.
 4. Observe the process started by `exec` is not terminated.

Numerous people report issues related to this: #7603 #6114 #3093 #1128 #1109

I fixed this issue in NuProcess - https://github.com/brettwooldridge/NuProcess/pull/133 - which you should use instead of `ProcessBuilder` on Windows. You will need to ping them to merge my PR.

You can trap Ctrl+C and use it to kill the subprocesses using NuProcess, or permit Ctrl+C to kill the daemon and using NuProcess, result in the child processes being terminated correctly.

Otherwise, Gradle is working really great for me.

**Comment by ov7a** [comment]
Sorry for the late reply!

Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/7603

Please add your use case and 👍 to that issue.

***

#7603 has a PR with a fix. Unfortunately, we don't have the capacity to push it right now, but it is in the backlog of the relevant team.
