### ISSUE TITLE
Copy task filter closure returning null shows an error in Intellij IDEA

### ISSUE THREAD

**Issue by msogrin** [gradle/gradle#18714]
Copy task filter method accepts a `Transformer<String, String>` closure, where the return value could be null indicating that a line should be removed.

When using Kotlin DSL, IntelliJ IDEA highlights such null as an error, despite it being valid code.

### Expected Behavior

No error highlighted in IDEA.

### Current Behavior

<img width="463" alt="image" src="https://user-images.githubusercontent.com/9539622/138125490-95300f34-f9af-40af-ac43-783cd061487a.png">

### Steps to Reproduce 

Minimal example code in Kotlin DSL:
```
tasks.register<Copy>("copy") {
    filter { null }
}
```

### Your Environment

Gradle 7.2
IntelliJ IDEA 2021.2.1

I understand that the issue could be redirected to Jetbrains, however IDEA works by analyzing Gradle's code, and it's likely that fix should be in Gradle to somehow indicate that the return type of Transformer is nullable.

**Comment by donat** [comment]
The PR closing this issue fixes more than just this particular issue. To close this issue, we introduced `nullableTransformer`:
https://github.com/gradle/gradle/blob/master/subprojects/docs/src/snippets/files/copy/kotlin/build.gradle.kts#L221-L223

**Comment by octylFractal** [comment]
This issue will unfortunately be unfixed by #19515 as this causes regressions in other areas. You can track #12388 for when the full fix will land, hopefully in Gradle 8.
