### ISSUE TITLE
Test suites should auto-configure IDEA plugin with test sources root(s)

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#18723]
### Expected Behavior
Apply plugins:
```kotlin
plugins {
    kotlin("jvm")
    idea
}
```

Configure test suites with:
```kotlin
testing {
    suites {
        register("functionalTest", JvmTestSuite::class)
    }
}
```

Then after running `:idea` I should get an IDEA module config file generated that specifies `/src/functionalTest/kotlin` as a test sources root in IntelliJ IDEA.

### Current Behavior
`/src/functionalTest/kotlin` is treated as a standard sources root:

![image](https://user-images.githubusercontent.com/170028/138190409-47071641-b638-4c76-adf1-d67006f24696.png)

### Context
Configuring IDEA plugin manually is problematic and multiple users have struggled (see from [this comment](https://youtrack.jetbrains.com/issue/IDEA-151925#focus=Comments-27-4614854.0-0) onwards in https://youtrack.jetbrains.com/issue/IDEA-151925)

Since the new test suites feature sets up most standard configuration it seems reasonable that the IDEA plugin is configured appropriately when it's applied and test suites are used.

**Comment by tresat** [comment]
This is on hold for now.
