### ISSUE TITLE
Resources with identical content but different names causes tasks using `@Classpath` to be out-of-date 

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1873]
### Expected Behavior

<3.5 behavior.  Visiting resources with identical content in different orders should not generate different cache keys.

### Current Behavior

When a task uses the `@Classpath` annotation, Gradle uses a specialized snapshotter that ignores file order, jar content timestamps (and order) and some other things. We cache the result of snapshotting each file by keying off the MD5 hash of the _content_ of the file.  This is fine if the contents of the file is the only thing that goes into calculating the snapshot/signature.

I believe this can occur on a single machine when switching between different GRADLE_USER_HOME (or clearing Gradle's internal caches), but it's most visible when using a remote build cache.

### Steps to Reproduce (for bugs)

Reproducing this is difficult.  This is what you need to have to reproduce:

- Resources on the classpath (anything other than a .jar or .class) need to have different names, but identical contents
- Resources need to appear in different orders across machines.  This usually means they have to be in the same directory (or directory hierarchy).  It would be difficult to make this happen with files that are in different projects.
- The sequence is:
   - You have resources A and B. md5(A) == md5(B).
   - Gradle sees A first and records hashForA for the md5(A) key.  hashForA is a combination of md5(A) + A's name.
   - Gradle then sees B. It reuses hashForA, since the file has the same md5. This is wrong.
   - The cache key is created by using 2*hashForA.
   - On another machine...Gradle sees B first and records hashForB for the md5(B) key.  hashForB is a combination of md5(B) + B's name.
   - Gradle then sees B. It reuses hashForA, since the file has the same md5. This is wrong.
   - The cache key is created by using 2*hashForB.
   - hashForA != hashForB, so the second machine would experience a cache miss.

### Your Environment

This becomes an big issue when using the build cache, since the file-visiting order is OS dependent.  macOS-only builds would probably never see a problem (since the ordering seems to be consistent).

**Comment by wolfs** [comment]
I guess this is not a bug with `3.5-rc-2`?
If we need a bugfix release we could probably fix it by not appending the name [here](https://github.com/gradle/gradle/blob/54c8ef34654358d9249161856788b19376726e0b/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/DefaultClasspathEntryHasher.java#L121-L121), right? The name will be hashed anyway when we calculate the hash for the `FileCollectionSnapshot` when appending the name of the file with relative path sensitivity and the signature of the file. We only need to respect the path for files in jars.
