### ISSUE TITLE
gradle7.0元素类型 "manifest" 必须后跟属性规范 ">" 或 "/>"。

### ISSUE THREAD

**Issue by travelto** [gradle/gradle#18742]
### Expected Behavior

gradle 7.0 提示：元素类型 "manifest" 必须后跟属性规范 ">" 或 "/>"。

### Current Behavior

./gradlew assembleRelease

### Your Environment
gradle 7.0
Build scan URL:

**Comment by dayday0769** [comment]
> 

gradle 7.0 tip: Element type "manifest" must be followed by attribute specification ">" or "/>".

**Comment by blindpirate** [comment]
This doesn't look like a Gradle issue. Most likely to be AGP issue.
