### ISSUE TITLE
BuildInit: Generate java/groovy/scala into a package folder

### ISSUE THREAD

**Issue by ysb33r** [gradle/gradle#1877]
When doing `gradle init --tyle=(java|groovy|scala)-library`, create a package folder structure to place the `Library.*` file within in. IOW create something like `src/main/(java|groovy|scala)/com/example`.

### Current Behavior

Currently when doing `gradle init --tyle=(java|groovy|scala)-library` it creates the `Library.*` file in `src/main/(java|groovy|scala)` as a default package.

### Context

It just makes it slightly easier for users to follow the 99%-common practice of placing JVM source code in packages.

**Comment by aadrian** [comment]
@ysb33r IMO  `gradle init` should accept a parameter for the package too, or have some global settings for these.

Other build tools allow users to input several parameters that are defined in the project template (but also have default values): https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html

Some tools even have interactive user input built in: http://yeoman.io/codelab/scaffold-app.html to allow a more flexible customization of the generated initial project.

**Comment by adammurdoch** [comment]
Fixed in https://github.com/gradle/gradle/pull/6489. The source package is also configurable via the `--package` command-line option and there's even some interactive user input now.
