### ISSUE TITLE
The file checkstyle-noframes-sorted.xsl is actually LGPL, not Apache 2.0

### ISSUE THREAD

**Issue by smancill** [gradle/gradle#18818]
The file `subprojects/code-quality/src/main/resources/checkstyle-noframes-sorted.xsl` was introduced by #505, which took the file from the Apache Hive repository, as it has the standard ASF header and so it was tough to be licensed under Apache 2.0.

The Apache Hive introduced that file on commit https://github.com/apache/hive/commit/84a96667844810e9925598886201de444d9b60d4, from the Jira issue [HIVE-990](https://issues.apache.org/jira/browse/HIVE-990). The contributor added the ASF header to the file as it is mandatory for any file added to an ASF repository.

But the problem is that `checkstyle-noframes-sorted.xsl` is actually a LGPL file part of the Checkstyle distribution. It is currently located at the [checkstyle/contribution](https://github.com/checkstyle/contribution/blob/master/xsl/checkstyle-noframes-sorted.xsl) repository with a LPGL license, but it was added to the main Checkstyle repository by https://github.com/checkstyle/checkstyle/commit/28086be0e207153372f4e499ac0f68afc28776f9, which is a modified copy of the original file introduced by https://github.com/checkstyle/checkstyle/commit/946f15a105c800ad1ae4d6d1fcf9453255ef4b4d.

My understanding is that a project using a permissive license cannot include source files licensed under LGPL, because it would require the whole project to be LGPL.

My understanding is also that the file should not have been added to Apache Hive because the ASF doesn't allow LGPL inclusions. And the file should not have been modified to add the standard ASF header making it seem to be Apache 2.0, because that changes the license of the file, which leads to the inclusion here.

But `checkstyle-noframes-sorted.xsl` is only used as part of the build process, not included in the final binaries. If so, is it allowed to be part of the repository? Or it should be removed?

I took the file from this repo to be used in my own repos and I just found that it is not Apache 2.0 licensed. That's why I decided to ask here what's the right resolution.

**Comment by ljacomet** [comment]
Thanks for reaching out on this. Will follow up and keep you posted.

**Comment by smancill** [comment]
Apache Hive issue:

https://issues.apache.org/jira/projects/HIVE/issues/HIVE-25665
