### ISSUE TITLE
Wrong Gradle 7.2 documentation for version conflict resolution when only ranges involved

### ISSUE THREAD

**Issue by tnikulin** [gradle/gradle#18823]
- Project depends on ```a``` and ```b```.
- ```a``` depends on ```leaf``` with a version range ```[2,6]```
- ```b``` depends on ```leaf``` with a version range ```[4,8]```

### Expected Behavior

According to Gradle 7.2 documentation version ```8``` for ```leaf``` should be choosen.

"If there are only ranges, the highest existing version of the range with the highest upper bound will be selected"
(https://docs.gradle.org/7.2/userguide/dependency_resolution.html#sub:resolution-strategy)

### Current Behavior

Version ```6``` choosen.

Current behavior test - "chooses highest version that is included in both ranges" (https://github.com/gradle/gradle/blob/v7.2.0/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy)

### Context

I think that documentation should be fixed according to current behavior.

**Comment by hegyibalint** [comment]
Hi @tnikulin 

Thanks for this, you are correct about this, and thanks for the legwork!
Indeed, the selection depends on whenever all the ranges intersect, or not:
 - If they do, the intersections' max is going to be the version - this is reasonable, as there is a solution to select a version which satisfies all the constraints. [Test](https://github.com/gradle/gradle/blob/v7.2.0/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy#L970)
 - If there isn't, then Gradle's default max version selection kicks in, and selects the max ranges. [Test](https://github.com/gradle/gradle/blob/v7.2.0/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy#L1113)

We are going to put this into the docs, as this detail was left out.
