### ISSUE TITLE
Default init --type groovy-library to not depend on groovy-all

### ISSUE THREAD

**Issue by w25r** [gradle/gradle#1882]
### Expected Behavior
A generated build.gradle with a dependency on the `groovy` core jar
```groovy
dependencies {
    compile 'org.codehaus.groovy:groovy:2.4.10'
}
```
### Current Behavior
A dependency on the `groovy-all` fat jar
```groovy
dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.4.10'
}
```

### Context
I initially brought up this discussion [here](https://github.com/gradle/guides/issues/76#issuecomment-295331733).  I think that depending on `groovy-all` is a bad practice, and we shouldn't propagate it in our examples.  

### Steps to Reproduce (for bugs)
    gradle init --type groovy-library

## Code review

- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by adammurdoch** [comment]
If we change the template, it will also need to deal with spock dragging in `groovy-all`

**Comment by ysb33r** [comment]
I reckon that's fine. the usual

```groovy
testCompile '...spock...', {
  exclude module : 'groovy-all'
}
```

The latter is actually quite common in gradle-groovy projects, so should be of little surprise to many people.

**Comment by szpak** [comment]
It was changed [years ago](https://github.com/gradle/gradle/pull/254/files), but it seems to be reverted in the meantime.

**Comment by w25r** [comment]
I've also logged an enhancement to Spock to publish a version not dependent on groovy-all.

https://github.com/spockframework/spock/issues/723

**Comment by adammurdoch** [comment]
The correct solution isn't to change all the libraries in the world to use only groovy or groovy-all. The correct solution to ensure the template build has the correct dependency resolution rules applied so that Gradle knows that groovy-all can be used in place of groovy, ideally by baking this into the groovy plugin.

**Comment by w25r** [comment]
@adammurdoch so your suggestion would be adding something like this
```groovy
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.name == 'groovy-all') {
            //prefer 'groovy' over 'groovy-all':
            details.useTarget group: details.requested.group, name: 'groovy', version: details.requested.version
        }
    }
}
```
to the groovy-plugin?

That code block is taken straight from our DSL docs, so it shouldn't shock anyone too much.

**Comment by adammurdoch** [comment]
Not quite. We don't want to _replace_ groovy with groovy-all. We want to say "if something in the dependency graph needs groovy-all and something else in the dependency graph needs groovy, then select groovy-all". Or, put another way, we want to say "groovy-all provides groovy".
