### ISSUE TITLE
Java Toolchains are Incompatible with `--add-exports` for System Modules

### ISSUE THREAD

**Issue by carterkozak** [gradle/gradle#18824]
Java toolchains _always_ set the `--release` flag, which is incompatible with some `javac` options

```bash
> Task :compileJava FAILED
error: exporting a package from system module java.management is not allowed with --release
1 error
```

### Expected Behavior
Ideally I should be able to use a compiler toolchain matching the bytecode version I'd like to produce in conjunction with the `--add-exports` option for internal functionality, for example to access safepoint time in https://github.com/palantir/jvm-diagnostics using `--add-exports java.management/sun.management=ALL-UNNAMED`. Toolchains are fantastic for this problem because I can specify exactly the compiler version I want, so the `--release` flag is unnecessary.

### Current Behavior
Unfortunately `--release` is incompatible with `--add-exports` for internal packages, and gradle always sets `--release` when a toolchain is used: https://github.com/gradle/gradle/blob/37911bb86d02d26a5d2ce3f23e01c0d767e3bb91/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java#L141-L158

### Context
I'm unable to set the correct args to build projects which reference internal components, and unable to use annotation processors which reference said components (e.g. code formatting in annotation processors without launching a new jvm: https://github.com/palantir/goethe/pull/53)

### Steps to Reproduce 
Reproducer project here: https://github.com/carterkozak/gradle-toolchain-exports

**Comment by alexander-schubert** [comment]
This seems to be a viable work-around:
```
tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = 17
}
```
Note that `sourceCompatibility` needs to be set on the task and can't be set on the project/extension level (`java { sourceCompatibility = 17 }`), as that just results in a different error:
```
> The new Java toolchain feature cannot be used at the project level in combination with source and/or target compatibility
```

This behavior is somewhat inconsistent but is enabled by the logic that automatically enables the `release` option when a toolchain is used for Java compilation:
https://github.com/gradle/gradle/blob/v7.3.3/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L353-L362

**Comment by ljacomet** [comment]
Given the report and the workaround, it might be simpler to _never_ add `-release` but instead keep what Gradle was doing in the past with adding `-source` and `-target`, extracted from the toolchain, when nothing else is provided.

I would recommend doing that at the time of Gradle 8 as the behaviour change might break some custom build logic.
