### ISSUE TITLE
Cannot use testLogging DSL to log events at error loglevel

### ISSUE THREAD

**Issue by sambsnyd** [gradle/gradle#1884]
### Expected Behavior
[TestLogging](https://docs.gradle.org/3.4.1/dsl/org.gradle.api.tasks.testing.logging.TestLogging.html)  looks like it can be used to route test events to stderr with code like this:

```gradle
test {
    testLogging {
        error {
            // For sake of example, usually you probably wouldn't want all these events going to stderr
            events = ['STARTED', 'PASSED', 'SKIPPED', 'FAILED', 'STANDARD_OUT', 'STANDARD_ERROR']
        }
    }
}
```

It is expected that after this configuration those events could be seen in the stderr stream

### Current Behavior
`test.testLogging.error.events` appears to do nothing at all regardless of how it's configured. 
Whether I set `events = []` or `events = [ /* all of the events */]` the exact same text is logged to stderr:
```
1 test completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':workgroup:src:silos:tsm:interfaces:tab-tabadmin-interfaces:test'.
> There were failing tests. See the report at: file:///D:/enlistment/near/build/reports/test/tab-tabadmin-interfaces/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
And the message I actually *wanted* to go to stderr is still logged to stout:
```
com.foo.AlwaysFailTest > AssertFalse FAILED
    java.lang.AssertionError at AssertFalse .java:43
```

### Context
The issue can be worked around by providing custom closures to the various test event listeners. e.g.:
```gradle
test {
    afterTest { descriptor, result ->
        if(result.getResultType() == TestResult.ResultType.FAILURE) {
            logger.error( "${descriptor.className}.${descriptor.name} failed with exception ", result.exception)
        }
    }
}
```

### Steps to Reproduce (for bugs)
1. Run a test task
2. Observe what ends up in stderr
3. Configure `testLogging.error.events = [ /* any event */]` for that test task
4. Run the test task again
5. Observe that what ends up in stderr is exactly the same as in step 2

### Your Environment
Gradle 3.4.1
Windows 10
Java project/JUnit test case

### Build scan 
See attached scan-dump: [wi36tqyjoqxjm.zip](https://github.com/gradle/gradle/files/953473/wi36tqyjoqxjm.zip)

**Comment by alekseyp555** [comment]
You a save my day!
