### ISSUE TITLE
Validate that plugin types have type-safe properties

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#1885]
Plugin types, tasks, extensions, conventions? expose JavaBean properties.

These properties can be read-only, i.e. only have a getter.
Or read-write, i.e. have a getter and setter(s).

Read-write properties should always provide a setter whose parameter type is the return type of the property getter, i.e. provide type-safe read-write accessors.

This issue is about validating that plugin types expose properties in a type-safe manner.

Validation should emit warnings at runtime.

When using the plugin development plugin, validation should also happen at build time and possibly fail the build.

- [ ] Validate Tasks properties
- [ ] Validate Extensions properties
- [ ] Validate Conventions properties?

### Context
See https://github.com/gradle/gradle/pull/1866, in particular this https://github.com/gradle/gradle/pull/1866#issuecomment-296847906

**Comment by adammurdoch** [comment]
Also do this at runtime, for those things not built using the plugin dev plugin, and also apply validation of other plugin types, such its extensions.
