### ISSUE TITLE
Deprecate tar tree without a backing file

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#18854]
Tar tree without a backing file is now the only "generic" file tree left, i.e. the only file tree which ends up in `FileCollectionStructureVisitor.visitGenericFileTree()`. I wonder if we could get rid of this case and only support archive trees backed by files.

For users, that would mean that they need to have a task or something else to create the tar file first, and then they can use a tar tree for that file. This also would have the advantage that the task could declare some inputs which affect the creation of the tar file, so you could avoid doing this every time.

---
cc: @gradle/execution

**Comment by lptr** [comment]
This would mean we could drop `GenericFileTree` as a concept altogether, right?

**Comment by wolfs** [comment]
> This would mean we could drop GenericFileTree as a concept altogether, right?

Yes, we could remove the `visitGenericFileTree` method, since then there would only be two types of file trees left:
- files in a directory (aka regular file trees)
- file trees backed by files (archive trees)

**Comment by bamboo** [comment]
> we could remove the visitGenericFileTree method
Please?
