### ISSUE TITLE
Wrapper task messes up wrapper script encoding when run with non-utf-8 charset on Windows

### ISSUE THREAD

**Issue by rbrindl** [gradle/gradle#18860]
We use an additional wrapper task to create wrapper scripts specifically for AWS. 
The task is configured like this:
```
tasks.register('wrapperAWS', Wrapper) {
	distributionUrl = "https://our-aws-cache.org/repo/${gradleDistUrl}"
	distributionSha256Sum = gradleVersionDistributionSha256Sum
	scriptFile = 'gradlew-aws'
	jarFile = 'gradle/wrapper/gradle-wrapper-aws.jar'
}

tasks.named('wrapper', Wrapper).configure {
	distributionUrl = "https://our-internal-chache/repo/${gradleDistUrl}"
	distributionSha256Sum = gradleVersionDistributionSha256Sum

	dependsOn 'wrapperAWS'
}
```

### Expected Behavior
On a windows system with the default encoding set to utf-8 (according to Powershell `[System.Text.Encoding]::Default`):
This sequence of command should leave the wrapper script unmodified:

Our wrapper script `gradlew-aws` has been created with
 ```
gradlew wrapperAWS -Dfile.encoding=UTF-8
```
and commited to git. 

This command should leave the wrapper script `gradlew-aws` unmodified:
 ```
gradlew cleanWrapperAWS wrapperAWS 
```

### Current Behavior
The current behavior when executing above command is that the `wrapper-aws` script file is modified, since it contains some UTF-8 characters (since gradle 7.x). Those characters are only in comments and don't break anything, but still it is annoying to users to have this file modified in their workspace. 

Most people don't set their `file.encoding` property explicitly. They usually also don't bother to execute the wrapper task, but when you import your project to IntelliJ, it calls the `wrapper` task, and this in turn depends on `wrapperAWS`.

Of course, they do not execute the `cleanWrapperAWS` task explicitly, but it seems like the task is not up-to-date from time to time. Also , some of our users seem to have committed the modified file, which leads to ripple effects all over the place and more users seem to have the problem.

### Context
Stopped working when we changed from gradle 6.9.2 to gradle 7.2

In "real life" we only experience this with the additional custom task `wrapperAWS`, but with
 ```
gradlew cleanWrapper wrapper
```
this can also be reproduced on the default wrapper task.

### Possible root cause
[StartScriptGenerator#generateUnixScript](https://github.com/gradle/gradle/blob/v7.2.0/subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/StartScriptGenerator.java#L111) calls [IoActions#writeTextFile(File output, Action<? super BufferedWriter> action)](https://github.com/gradle/gradle/blob/a773786b58bb28710e3dc96c4d1a7063628952ad/subprojects/base-services/src/main/java/org/gradle/internal/IoActions.java#L54). This again uses `Charset.defaultCharset()`.
Instead it should use [IoActions#writeTextFile(File output, String encoding, Action<? super BufferedWriter> action)](https://github.com/gradle/gradle/blob/a773786b58bb28710e3dc96c4d1a7063628952ad/subprojects/base-services/src/main/java/org/gradle/internal/IoActions.java#L44) and supply `"utf-8"` as encoding. 
Because the TextResource for the unixScript was explicitly read with UTF-8 encoding in [DefaultTemplateBasedStartScriptGenerator.java](https://github.com/gradle/gradle/blob/v7.2.0/subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/DefaultTemplateBasedStartScriptGenerator.java#L93)

### Steps to Reproduce 
On a windows machine: 
 ```
gradlew cleanWrapper wrapper
```
make sure, `file.encoding` is not set and left at it's "default" value, for me that is windows-1252

I added the following closure to my `wrapperAWS` task to see the default charset:
```
	doFirst {
		println "default charset: ${java.nio.charset.Charset.defaultCharset().name()}" 
	}
```

### Your Environment
This was on a windows-10 machine with Cygwin, but it was also reproduced on "pure" windows-10 machines from cmd. 
As said, the problem seems to appear when importing to IntelliJ, which calls the wrapper task.

```
PS C:\Users\ronald.brindl> [System.Text.Encoding]::Default


BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001
```

**Comment by jbartok** [comment]
Might be related to #18618

**Comment by jbartok** [comment]
(Closed because it's the same issue mentioned above)
