### ISSUE TITLE
Gradle sourceSet java/groovy cross-compilation functionality differs from 3.4.1 to 3.5 using Build Cache

### ISSUE THREAD

**Issue by edeandrea** [gradle/gradle#1887]
With Gradle 3.4.1 and below everything works fine, but once moving to Gradle 3.5 I am seeing behavior where code in the groovy test source set does not see code in the java test source set (i.e. things in `src/test/groovy` do not see things in `src/test/java`, even though the things in `src/test/java` were compiled first.

### Expected Behavior
I would expect if I have some java code in src/main/java and groovy code in `src/test/groovy`, the groovy code in `src/test/groovy` can reference the java code in `src/main/java`.

### Current Behavior
Anything in `src/test/groovy` can reference java code in `src/test/groovy`

### Steps to Reproduce (for bugs)
Put some groovy code in `src/test/groovy` which references some java code in `src/test/java`. Run `gradlew clean build`. Compilation will fail.

### Your Environment
Java 8, Gradle 3.5

**Comment by eriwen** [comment]
@edeandrea Could you please provide a sample project that demonstrates the issue?

**Comment by big-guy** [comment]
Do you happen to have the build cache enabled?

**Comment by big-guy** [comment]
This is a known issue with 3.5 and the build cache (the "mixed compilation" mentioned in https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_known_issues_correctness). There are safety rails in master to detect this kind of problem and disable caching automatically and I'm currently fixing this in master so that the Java and Groovy compilation tasks do not share an output directory (so both can be cached).  The workaround is to put Java sources into `src/{main or test}/groovy` and let the Groovy compilation task do all the work.

**Comment by edeandrea** [comment]
But it continues to happen even after I remove `org.gradle.caching=true` from `root/gradle.properties`?

**Comment by eriwen** [comment]
Thanks for the additional detail @edeandrea. This will be fixed in 4.0, due out next month.

**Comment by edeandrea** [comment]
So to add a follow-up - I think the switching to use the build cache & then turning it off got something messed up. I removed my `<user_home>/.gradle` & `<project_root>/.gradle` directories (& included in my Jenkinsfile something which does the same) and now I am good (with build cache turned off). I've moved my Java sources back into `src/test/java` and everything is now good.

**Comment by eriwen** [comment]
@edeandrea Cool. Thanks very much for the follow up and sorry for the troubles. I'm glad you're all good for now.

**Comment by big-guy** [comment]
@edeandrea Thanks, I think you may have been able to fix it with `--rerun-tasks` and a clean build or just deleting the project `.gradle` directory.

What happens is that the build cache mixes the outputs of the two tasks and up-to-date checks filter out files that do not change.  This makes it hard to tell which outputs really belong to each task and Gradle does the wrong thing (and this wrong information is cached in the project cache dir).

**Comment by oehme** [comment]
@big-guy is there anything left to do here or can this be closed?

**Comment by edeandrea** [comment]
I think I'm good.
