### ISSUE TITLE
Should the 7.3 RC Kotlin DSL also target Java 17?

### ISSUE THREAD

**Issue by blundell** [gradle/gradle#18888]
Kotlin Build Script DSL on the Grade 7.3 branch still targets java 1.8 (when the branch is about support Java 17)

See here: https://github.com/gradle/gradle/blob/v7.3.0-RC5/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt#L46

Release notes here: https://docs.gradle.org/7.3-rc-5/release-notes.html

### Expected Behavior

Either the plugin could target Java 17 or it should allow the target to be overridden.

### Current Behavior

Targetting 1.8 with the code:

```
@ScriptTemplateAdditionalCompilerArguments(
    [
...
        "-jvm-target", "1.8",
...
```

### Context

Moving to a world where all our code targets Java 17.

### Steps to Reproduce 

See above link.

### Your Environment

All Env's
n/a

**Comment by jbartok** [comment]
The target we have set for running Gradle is a lower bound for what Java versions we support, so 1.8 is where we want to be. You can still use Java 17 for your own code.

**Comment by blundell** [comment]
> Gradle now supports running on and building with Java 17.

@jbartok if my plugin uses the Gradle kts plugin, I have to target java 8 because of this line of code 

I'd like to target java 11, not even 17 :D 

Or do you know a way around this?

**Comment by donat** [comment]
IIUC now,  you are trying to implement a precompiled script plugin in Kotlin. That needs to be aligned with the runtime that Gradle uses, which is Java 8. There's no way around that. You can write a "classic" Gradle plugin in Kotlin which doesn't have a limitation (i.e. use the `kotlin-gradle-plugin`).

**Comment by blundell** [comment]
Reading in teh area https://blog.jetbrains.com/kotlin/2021/11/gradle-jvm-toolchain-support-in-the-kotlin-plugin/

**Comment by blundell** [comment]
Related: https://github.com/gradle/gradle/issues/18227
