### ISSUE TITLE
Provide a generic support for .gitignore, .gitattributes, and .editorconfig properties

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#18882]
### Expected Behavior

There should be a way to use `.gitignore`, `.gitattributes`, and `.editorconfig` attributes in a commonly understood way that is compatible with Gradle UP-TO-DATE and FROM-CACHE behaviors.

For instance:
* Exclude files from license header verification if they are excluded by `.gitignore`
* Set `executable` bit when including a file into `.tar` archive in case the file is marked as `executable` via `.gitattributes`
* Filter file with `eol=lf` and `eol=crlf` according to `.gitattributes` when including the file into zip archive
* Trim whitespace at the end of lines for files that have `trim_trailing_whitespace = true` setting in `.editorconfig`

### Current Behavior

The nature of `.gitignore`, `.gitattributes`, and `.editorconfig` files is that they are hierarchical, so there's often a file in the repository root, and its contents affects all the subfolders, including subfolders for subprojects.
I have a task that locates all `.gitignore` files, and the task is smart enough so it does not walk into `ignored` directories. In other words, it tries to find `.gitignore` file first, and if the file is present, then it is added to the discovered list. Then the walk uses all the exclusions. That allows the task to automatically skip `build` directories, etc.

I guess the workaround is to mark "input directory" for "findGitAttributes task" as `@Internal`, so Gradle does not try to figure out "mismatching inputs".

`FindGitAttributes` task (Apache 2.0 code ahead): https://github.com/vlsi/vlsi-release-plugins/blob/83c85c5faa4c7cd1fe0173b75c1cba5e60c3f209/plugins/crlf-plugin/src/main/kotlin/com/github/vlsi/gradle/git/FindGitAttributes.kt#L31-L42
implementation (Apache 2.0 code ahead): https://github.com/vlsi/vlsi-release-plugins/blob/83c85c5faa4c7cd1fe0173b75c1cba5e60c3f209/plugins/crlf-plugin/src/main/kotlin/com/github/vlsi/gradle/git/GitignoreFinder.kt#L41-L49

However, that behavior drives Gradle nuts, and Gradle produces lots of warnings:

```
> Task :release:gitProps
Execution optimizations have been disabled for task ':release:gitProps' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:checkstyleMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:checkstyleTest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:compileJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:compileTestJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:fmppMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:jandexMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:jandexTest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:javaCCMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:processJandexIndex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:processResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:processTestResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/runner/work/calcite/calcite'. Reason: Task ':release:gitProps' uses this output of task ':babel:sourcesJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
...
```

### Context

The issue results in lots of warnings in Apache Calcite, and Apache JMeter projects.

**Comment by lptr** [comment]
This sounds like great functionality for a Git plugin, but not something we'd support in Gradle as a core feature.

**Comment by vlsi** [comment]
I believe, Gradle provides no way to write such a plugin without running into "Gradle detected a problem with the following location" issues.

**Comment by vlsi** [comment]
Then, `.editorconfig` is a pretty-much standard thing, which covers more ecosystems than `checkstyle`.

**Comment by wolfs** [comment]
@vlsi I think you should be able to change the default excludes in settings to ignore those locations. See here: https://docs.gradle.org/current/userguide/working_with_files.html#sec:file_trees

**Comment by vlsi** [comment]
@wolfs , the thing is:
1. I do not want to duplicate configuration across `.gitignore` and `gradle.kts`
1. That implies I need to discover `.gitignore` files
1. That implies I need to create a task that "scans all the directories starting from the root, and locates all `.gitignore` files"
1. Unfortunately, I do not remember quite well why I use `[Files.walkFileTree](https://github.com/vlsi/vlsi-release-plugins/blob/83c85c5faa4c7cd1fe0173b75c1cba5e60c3f209/plugins/crlf-plugin/src/main/kotlin/com/github/vlsi/gradle/git/GitignoreFinder.kt#L41-L49)` instead of Gradle's `fileTree(..).matching { exclude {...} }`

Most likely the matching-exclude does not allow me to skip subdirectories. For instance, I start from the root, and from the root `.gitignore` file I learn that `/build` should be ignored. AFAIK, there's no way to tell `fileTree` that I do not want to enter `/build` since it tries to locate files first. I'm not sure that is the case.

**Comment by vlsi** [comment]
An alternative option could probably be something like `build service` that collects all the files going up the hierarchy.
I do not remember why did I settle on top-down approach :-/

**Comment by vlsi** [comment]
Ok, I released the task on 19 Jul 2019 , and Shared Build Services appeared in Gradle 6.1 on Jan 15, 2020

**Comment by wolfs** [comment]
@vlsi I see that the plugin needs to do quite some work to detect all the `.gitignore` files and parse them. That is another reason why I wouldn't want to build this into Gradle core. Though I also don't object to having a plugin which supports this feature.

So the question is if it is already possible to write such a plugin, or if you'd need some additional APIs from Gradle. And if you need some additional APIs from Gradle, maybe we should create them to enable you write the plugin.

**Comment by vlsi** [comment]
I'm quite sure currently there's now way to create a top-down approach (a task that walks the file tree and discovers `.gitignore` files).

On the other hand, a `build service` that answers queries like "is this file ignored?" could be a workable solution.
Let me see that is a good enough solution.

**Comment by wolfs** [comment]
I agree that a task isn't the right solution. You'd need to discover the `.gitignore` files at configuration time, while running `settings.gradle`. Since this is the only time you could configure the default excludes.

**Comment by vlsi** [comment]
@wolfs , I am afraid `shared build services` are not enough to implement `gitignore` filtering.

* Gradle does not track copyspec filters: https://github.com/gradle/gradle/issues/1191
* So users have to resort to configuring task properties **before task execution**
* So users have to incorporate **all** `.gitignore`, `.gitattributes`, and `.editorconfig` files to the task properties, which is bad for configuration time

The ways out seem to be:
A) Implement solution for https://github.com/gradle/gradle/issues/1191. For instance, something like https://github.com/gradle/gradle/blob/73c41dc5074a3a348b2a51bb99806c960f5900a9/subprojects/snapshots/src/main/java/org/gradle/internal/snapshot/impl/DirectorySnapshotter.java#L415 should consider the applicable properties for the filters, filteringCharset, and so on.
B) Implement native solution for gitattributes/gitignore/editorconfig

WDYT?

---

There are several issues:
1) It would be time-consuming to walk over all the project files and search for `.gitignore` files when evaluating settings.
Even though the implementation is "just" check `.gitignore` file in all the directories except the ones whe know have been already excluded, the project might still contain many directories (e.g. Java packages), so the walk would take time
2) It is not clear how to model `the set of attributes applicable to a file` input dependency (more on this later)

What we need is to have something that would answer `CopySpec` questions `should I include file x/y/z/file.txt?`. A more efficient `shared build service` would take `x/y/z/file.txt` and check all its parent directories for the presence of `.gitignore`.
That would be super-efficient as `.gitignore` could be cached, and it would query only the minimal number of `.gitignore` files.

However, if we implement that optimized approach, it is unclear how to model `CopySpec depends on certain gitignore files` dependency. A dumb way would be to compute a combined hash of all the gitignore files and add it to every task, however, it would trigger unwanted invalidations.

`.gitignore` is a trivial attribute "file included" vs "file excluded". The current `CopySpec.exclude` supports it (as far as I understand, it performs input snapshot, and it would walk the tree).

However, `.gitattributes` and `.editorconfig` can't be supported with the current `CopySpec` implementation.
For instance, they could configure "the desired end-of-line markers (LF/CRLF)". However, Gradle does not currently track `filter/eachFile` into up-to-date considerations: https://github.com/gradle/gradle/issues/1191, so it is not clear how to model "CopySpec depends on `end_of_line` property in `.editorconfig`".
