### ISSUE TITLE
Baffling behavior: gradle consistently checks dependencies yet doesn't pull updates

### ISSUE THREAD

**Issue by eepstein** [gradle/gradle#1890]
### Expected Behavior

Gradle has trouble figuring out that it should update changing dependencies.  Adding the `changing: true` modifier seems to have little effect.  Setting the `resolutionStrategy.cacheChangingModulesFor` similarly seems to have little to no impact. 

Gradle checks repo even for things that aren't changing (why, I have no idea) and then... DOES NOTHING ever for things that are changing.  Puzzling.

Maven correctly checks remote repos for updates to -SNAPSHOT dependencies and (depending on settings) when an update is found, downloads it.  (Hurrah!  Snapshots "just work.")

Much more puzzling is that gradle seems quite intent on always pinging repos to confirm that it's got the expected version, but then DOES NOTHING WHATSOEVER after checking.  Truly bizarre behavior and adds to Gradle's already existing problems of being abysmally slow.  

Gradle should:  check repos for SNAPSHOTs and other "changing: true" dependencies and then, update them if they've changed.  (Seems like a no-brainer of a feature.)

### Current Behavior

Gradle unnecessarily checks repo for non-changing dependencies.
Gradle doesn't actually update the changed dependencies for changing: true ones.

### Context

1. It's slow.
2. I have to change the build to use local project references as a work-around.
3. But then when we push projects to our build server the relative references don't apply and the build breaks.
4. So we end up juggling back-and-forth and don't have environmental consistency.

The baseline bar for Gradle in the java world should be maven.  The fact that the baseline of Gradle's behavior - now at v3.x no less - doesn't even do this, is disappointing and regrettable.

### Steps to Reproduce (for bugs)

Google away.  100s of folks have this problem.

### Your Environment

Mac OS.  Java 8.

**Comment by bmuschko** [comment]
Can you please provide a reproducible sample project or at least the relevant code you are using?

**Comment by oehme** [comment]
> Gradle unnecessarily checks repo for non-changing dependencies.

> Gradle doesn't actually update the changed dependencies for changing: true ones.

Neither of these behaviors are normal or expected for Gradle. Please provide an example project showing the problem, so we can investigate.
