### ISSUE TITLE
Confusing error messages when archiveDestinationDirectory is not set in the Jar task

### ISSUE THREAD

**Issue by jmini** [gradle/gradle#18918]
Given a simple structure:

```
.
├── build.gradle
└── folder
    ├── file.txt
    └── other.txt
```

The goal is to build a jar with the content of that folder, using a custom Jar task.

I am using the newest gradle version (7.2).

---

With following `build.gradle` file:

```
task customJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'Gradle Jar File Example',  
                   'Main-Class': 'xxx.aaa.Bbb'
    }
    from 'folder'
}
```

If you run `./gradlew customJar`, you will get this error:

```txt
> Task :customJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':customJar' (type 'Jar').
  - Type 'org.gradle.api.tasks.bundling.Jar' property 'archiveFile' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'archiveFile'.
      2. Mark property 'archiveFile' as optional.
    
    Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#value_not_set for more details about this problem.
```

----
You might try to set `archiveFile` directly in the `build.gradle` file to:

```
task customJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'Gradle Jar File Example',  
                   'Main-Class': 'xxx.aaa.Bbb'
    }
    archiveFile = 'custom-jar'
    from 'folder'
}
```

But then you will get:

```txt
FAILURE: Build failed with an exception.

* Where:
Build file '/<path to my project>/build.gradle' line: 101

* What went wrong:
A problem occurred evaluating root project 'tmp'.
> Cannot set the value of read-only property 'archiveFile' for task ':customJar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**NOTE:** I guess this error is generic. If possible it would be already great if at this point you could indicate that you must set `destinationDirectory` and `archiveFileName` (or one of its components like `archiveBaseName`).

---

Then you can look at the [dsl for the Jar Task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar) you understand that you could set `archiveBaseName`.

```
task customJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'Gradle Jar File Example',  
                   'Main-Class': 'xxx.aaa.Bbb'
    }
    archiveBaseName = 'custom-jar'
    from 'folder'
}
```

This does not have any impact (you are back to the first error message indicating that `archiveFile` is not set, from the first case). In reality, this is because `archiveDestinationDirectory` is not set.

**NOTE:** It would be great to have an ERROR or a WARNING reported, explaining that you should set `archiveDestinationDirectory`.

---
While performing some tests, I also noticed that if you set only `archiveDestinationDirectory` like this:

```
task customJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'Gradle Jar File Example',  
                   'Main-Class': 'xxx.aaa.Bbb'
    }
    destinationDirectory = layout.buildDirectory.dir("libs")
    from 'folder'
}
```

Then you get a `BUILD SUCCESSFUL` when the task is executed (`./gradlew customJar`), but in this case you have nothing in your build directory. `tree build/` returns:

```
build/
├── libs
└── tmp
    └── customJar
        └── MANIFEST.MF
```

---

For the reference, this is one possible solution:

```
task customJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'Gradle Jar File Example',  
                   'Main-Class': 'xxx.aaa.Bbb'
    }
    destinationDirectory = layout.buildDirectory.dir("libs")
    archiveBaseName = 'custom-jar'
    from 'folder'
}
```

It producing the expected jar. See my [stackoverflow question](https://stackoverflow.com/a/69894797).

----

### Expected Behavior
The error messages could help you to understand better what is missing and how to set the required properties.

### Current Behavior
See my description of the different cases.

### Context
I lost a lot of time, not understanding what was wrong. Only with the help of @melix on stackoverflow, I was able to understand my mistake.

**Comment by donat** [comment]
Please note that the conventional values are defined in the base plugin. Try applying the `base` or the `java-library` plugin.

**Comment by ov7a** [comment]
Sorry for the late reply. 

This is a valid issue, but I'll close this as a duplicate of

* https://github.com/gradle/gradle/issues/24444

Because it has more comments and an implementation spike.
