### ISSUE TITLE
I want to use gradle commit my sdk‘s jar to jcenter .how should i do?

### ISSUE THREAD

**Issue by liveLC1993** [gradle/gradle#1892]
I want to use gradle commit my sdk‘s jar and so file  to jcenter  ,how should i do? 
 and so file

**Comment by szpak** [comment]
@liveLC1993 Maybe it would be better to ask using the [forum](http://discuss.gradle.org/)?

**Comment by lacasseio** [comment]
Thanks @szpak for pointing the user in the right direction. @liveLC1993 please use the [forum](http://discuss.gradle.org/) for any question regarding the usage of Gradle.
