### ISSUE TITLE
gradle 7.0.2 android parse failed

### ISSUE THREAD

**Issue by EdisonLiao** [gradle/gradle#18926]
### Expected Behavior
gradle build success

### Current Behavior
gradle build failed

### Context
I have upgraded gradle version from 6.7.1 to 7.0.2, and I found that 7.0.2 do not contain groovy, so I added groovy-xml:3.0.9 sidely,
my build.gradle look like bellow:
![image](https://user-images.githubusercontent.com/14108176/141077420-7d5a0bc3-de87-427d-ad2e-16225be61c32.png)

but I get an error, it says : org.xml.sax.SAXParseException; lineNumber: 52; columnNumber: 171; manifest must end with ">" or "/>"

### Steps to Reproduce 
Custom a task in build.gradle, and use gradle 7.0.2, and build the project

### Your Environment
Android Studio Arctic Fox
gradle 7.0.2
groovy-xml:3.0.9

Build scan URL:

**Comment by donat** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by EdisonLiao** [comment]
### Steps to Reproduce
- Create an android project with gradle version 6.7.1  and custom a task in app's build.gradle like this:
```applicationVariants.all { variant ->
 
        variant.outputs.each { output ->
  
            output.processManifestProvider.get().doLast {
                def festmaniOutFile = new File(multiApkManifestOutputDirectory.get().getAsFile(), "AndroidManifest.xml")
                def festmaniXml = new XmlParser().parseText(festmaniOutFile.getText("UTF-8"))
                def nameSpace = "http://schemas.android.com/apk/res/android"
                for (Node activityNode : festmaniXml.application[0].activity) {
                    def nameValue = activityNode.attributes().get(new QName(nameSpace, "name"))
                    if (!nameValue.toString().startsWith("com.xx.xx.xx") &&
                            !nameValue.toString().contains(activityNoHistoryWhiteList)) {
                        activityNode.attributes().put(new QName(nameSpace, "taskAffinity", "android"), "xxx")
                        activityNode.attributes().put(new QName(nameSpace, "label", "android"), "@string/empty")
                        activityNode.attributes().put(new QName(nameSpace, "icon", "android"), "@drawable/transparent_drawable")
                        activityNode.attributes().put(new QName(nameSpace, "excludeFromRecents", "android"), "true")
                        activityNode.attributes().put(new QName(nameSpace, "noHistory", "android"), "true")
                    }
                }

                def serialize = XmlUtil.serialize(festmaniXml)
                festmaniOutFile.write(serialize, 'UTF-8')
            }
        }
    }
```
- Upgrade gradle to 7.0.2, and rebuild project, problem shows up

**Comment by octylFractal** [comment]
This looks like an issue with the Android Gradle Plugin. Please file an issue with [Google](https://source.android.com/setup/contribute/report-bugs) about this.

**Comment by CarSmallGuo** [comment]
@EdisonLiao excuse me , Have you found a solution to this problem
