### ISSUE TITLE
Unable to refer classes from extenal plugins in other *.gradle files

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#1894]
### Expected Behavior
Referring to classes from already applied plugins should work fine in other `*.gradle` files applied from `build.gradle`.

### Current Behavior
Gradle fails to resolve a class from a plugin with:
```
> Could not get unknown property 'org' for root project 'plugin-class-other-script'
of type org.gradle.api.Project.
```

for any class reference (from **not** `build.gradle`), e.g.:
```
task fromOther(type: org._10ne.gradle.rest.RestTask) { ... }
```

It works fine if used from `build.gradle` or if in a separate file the whole `buildscript` section is repeated.

### Context
To improve readability of the Gradle build it is useful to put connected parts to a separate `*.gradle` files (applied from `build.gradle`). Not all code can be moved due to the aforementioned limitation.

### Steps to Reproduce (for bugs)
```
//build.gradle
buildscript {
  repositories { ... }
  dependencies {
    classpath "org._10ne.gradle:rest-gradle-plugin:0.4.2" //any external plugin can be used
  }
}

apply plugin: "org.tenne.rest"

task fromMain(type: org._10ne.gradle.rest.RestTask) { //works fine
  //...
}

apply from: 'gradle/other.gradle'
```

```
//other.gradle
task fromOther(type: org._10ne.gradle.rest.RestTask) { //fails
  //...
}
```

```
FAILURE: Build failed with an exception.

* Where:
Script '/tmp/plugin-class-other-script/gradle/other.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'org' for root project 'plugin-class-other-script' of type org.gradle.api.Project.
```

### Your Environment
All modern Gradle versions (tested up to 3.5). That issue was reported years ago, but was lost in the migration.

**Comment by eriwen** [comment]
This seems to be the same as #1262 as you said @szpak. Let's continue discussion there. I'll close this as a duplicate.

**Comment by szpak** [comment]
After you edited the original issue it seems to be a very good idea.
