### ISSUE TITLE
When that happend,It won't stop.how can I make my process exit with code 0

### ISSUE THREAD

**Issue by softtiny** [gradle/gradle#18943]
https://github.com/gradle/gradle/blob/f7b6c07456f24fa6b29d70869b4151a57dc861df/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/DefaultDaemonConnection.java#L93

**Comment by big-guy** [comment]
Hey @softtiny 

I'm not sure what problem you're running into. Could you open a new issue with some more details?

Thanks!
