### ISSUE TITLE
Missing upgrade docs from 6.9 to 7.0

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#18957]
### Expected Behavior
Section called "Upgrading from 6.9"

### Current Behavior
The last section is "Upgrading from 6.8", as if 6.9 didn't exist or has no migrations/deprecations.

### Context
If that's the case, please add a section for 6.8 to 6.9 with the message.

### Steps to Reproduce 
Open https://docs.gradle.org/current/userguide/upgrading_version_6.html

### Your Environment
Have a project with Gradle 6.9.1
Have an intent to upgrade to 7.3

**Comment by donat** [comment]
I know the naming of the chapters is a bit misleading, but the documentation is available: https://docs.gradle.org/current/userguide/upgrading_version_7.html#changes_7.1

**Comment by TWiStErRob** [comment]
Really confusing. So "7 and earlier" section is 6.9 to 7.1?
Where are the changes from 6.9 to 7.0?

**Comment by TWiStErRob** [comment]
The outcome of this might be twofold in my reading:

1. Rename sections to be clear. The main use case of that document is that you have a project using X Gradle and have a target Y version you want to upgrade to. It's really hard to use it like this.

2. Split/add sections to document 6.8 to 6.9, 6.9 to 7.0, 7.0 to 7.1 upgrades as independent sections. (Whichever is actually missing out of these.)

**Comment by ljacomet** [comment]
Will be fixed in 8.0
