### ISSUE TITLE
Gradle wrapper does not respect `--gradle-user-home` when downloading distribution 

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#1895]
When using the gradle wrapper and adding `--gradle-user-home` or `-g` commandline option as last argument, the download destination ignores the provided custom gradle user home. 

### Expected Behavior

`gradlew build  -g ghome` should behave exactly like `./gradlew -g ghome build` and respect the configured gradle user home.

### Current Behavior

- `./gradlew -g ghome build` respects `ghome` when downloading the gradle distribution.
- `gradlew build  -g ghome` does not respect `ghome` when downloading the gradle distribution.

**Comment by w25r** [comment]
This was logged on behalf of a contributor as a [support issue](https://gradle.zendesk.com/agent/tickets/1592).  As such I've changed the label to `from:contributor`.

**Comment by DPUkyle** [comment]
I have encountering this too. My workaround is to skip `-g` or `--gradle-user-home` and instead set `-Dgradle.user.home=...` on the command line.
