### ISSUE TITLE
feature request: ability to add a task timeout handler/lambda

### ISSUE THREAD

**Issue by kenyee** [gradle/gradle#18964]
### Expected Behavior
Thanks for this: https://github.com/gradle/gradle/issues/6739
and this: https://github.com/gradle/gradle/pull/6643
Would like to be able to add a task timeout callback/lambda/handler so the gradle enterprise scan can be tagged as "TimedOut" and/or do something to try fixing the issue (would be nice if the callback has access to the stack trace) and retrying the task.

### Current Behavior
Can currently add a timeout to a task, but there's no way to hook a failure to do other things.

### Context
Trying to add a way to tag a build as TimedOut in gradle enterprise.

**Comment by ljacomet** [comment]
You should be able to tag your build by using a build service to listen to task execution, see [docs](https://docs.gradle.org/current/userguide/build_services.html#operation_listener).

**Comment by kenyee** [comment]
Looks like it's not compatible with config caching (which we're using)?
https://githubmemory.com/repo/gradle/gradle/issues/18520
Was looking for an example (the docs should provide a snippet and going to the listener doc doesn't have a snippet on how to write one either) when I stumbled on that issue...

**Comment by ov7a** [comment]
Given that there's no reply we assume that the advice work and thus closing this as a question.
