### ISSUE TITLE
java-gradle-plugin produces redundant package in maven publication

### ISSUE THREAD

**Issue by koral--** [gradle/gradle#18970]
Affected plugin: https://plugins.gradle.org/plugin/pl.droidsonroids.pitest
Source code (Gradle itself and all the used plugins updated to their latest versions at the time of writing):
https://github.com/koral--/gradle-pitest-plugin/tree/359e051d1998a3c06a7dc9c943ab251b97412213
I'm using this plugin: https://github.com/vanniktech/gradle-maven-publish-plugin to automate publishing to maven central along with closing and releasing repositories there.

After invoking `./gradlew publish --no-daemon --no-parallel` the staging repository on maven central contains 2 packages:
![image](https://user-images.githubusercontent.com/3340954/141654980-6cc30f63-ff25-4456-8002-eadab249645d.png)

Related configuration block:
```
gradlePlugin {
    testSourceSets sourceSets.funcTest
    plugins {
        pitest {
            id = 'pl.droidsonroids.pitest'
            implementationClass = 'pl.droidsonroids.gradle.pitest.PitestPlugin'
        }
    }
}
```

Staging repo content: https://oss.sonatype.org/service/local/repositories/pldroidsonroids-1299/content/pl/droidsonroids/

### Expected Behavior
Only the upper part of content is expected.

### Current Behavior
Resulting repository contains an extra package having coordinates equal to plugin id. The lower part contains only POMs, XMLs and checksums. It seems to be caused by `gradlePlugin` configuration. If I change id there, that parts also gets changed.

### Context
Id of the plugin is `pl.droidsonroids.pitest`
However, the coordinates on maven central are: `pl.droidsonroids.gradle:gradle-pitest-plugin`
I want to keep those ids.

### Steps to Reproduce 
1. Configure or disable signing: https://github.com/vanniktech/gradle-maven-publish-plugin#gradle-maven-publish-plugin
2. Change coordinates for maven central to something you have control of.
3. Invoke `./gradlew publish --no-daemon --no-parallel`

### Your Environment
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
MacOS 12.0.1

**Comment by ljacomet** [comment]
This is by design.
The secondary set of coordinates is the plugin marker, which allows the `plugins` notation:
```
plugins {
  id("pl.droidsonroids.pitest")
}
```
Note that if not published to the plugin portal, the above will require to configure a repository, `mavenCentral()` in this case.

This works by having a convention to go from plugin ID to GAV and publishing a POM file at those coordinates.

If you do not want this marker to be published to Maven Central, just publish the plugin publication, ignoring the other one.

**Comment by koral--** [comment]
> just publish the plugin publication, ignoring the other one.

Can I achieve that by appending some snippet to my buildscript or it is the responsibility of `gradle-maven-publish-plugin`?

**Comment by ljacomet** [comment]
The plugin publication is the one named `pluginMaven`. Either invoke only that one - using `./gradlew tasks` to get its full name.

Or you could remove the other publication from the `publications` container as there is no API to disable a publication.
