### ISSUE TITLE
Gradle not handling Maven parent POMs with version-range

### ISSUE THREAD

**Issue by MichaelWeir** [gradle/gradle#1898]
Gradle seems to be ignoring version-ranges in Maven POM parents.
### Expected Behavior
Gradle should handle version ranges in parent POMs in encounters transitively.

### Current Behavior
When a version range is specified in a build.gradle file, e.g. 

    compile group: 'com.company.platform', name: 'abc-common', version: '[11.0,12.0['

Gradle first requests the versions of the component and selects the highest version. When it looks for transitive dependencies and finds one with a parent with a version-range, Gradle uses the version-range string as-is. 

    Loading http://nexus.company.com:8081/.../corporate-parent/[11.0.7,11.0.8)/corporate-parent-[11.0.7,11.0.8).pom

### Context
I'm required to consume dependencies from a corporate Nexus repo. If I can't get this to work fairly soon, I'll have to convert our build to Maven. I'm hoping for a quick fix, even if it's only on humanitarian grounds.

### Steps to Reproduce (for bugs)
I have a Gradle build that needs to fetch dependencies from a Nexus repo that has been populated using Maven. Some of the POMs there use version-ranges when specifying a parent POM.

In my build.gradle I put a dependency:

    compile group: 'com.company.platform', name: 'abc-common', version: '[11.0,12.0['

The Gradle logs show that a request is made for the versions of abc-common, and its POM and its parent's POM are fetched:

    abc-common-11.0.7-17042111.pom:
    <parent>
        <groupId>com.company.platform</groupId>
        <artifactId>abc-parent</artifactId>
        <version>11.0.7-17042111</version>
        <relativePath>..</relativePath>    
    </parent>

    abc-parent-11.0.7-17042111.pom:
    <parent>
        <groupId>com.company.corporate</groupId>
        <artifactId>corporate-parent</artifactId>
        <version>[11.0.7,11.0.8)</version>
        <relativePath/>
    </parent>

But Gradle fails to fetch the corporate-parent POM. Instead of requesting what versions are present on the repo, it tries to fetch using the version-range literal:

    Loading http://nexus.company.com:8081/.../corporate-parent/[11.0.7,11.0.8)/corporate-parent-[11.0.7,11.0.8).pom

### Your Environment
Gradle version 3.5

I can't upload any details.

**Comment by eriwen** [comment]
@MichaelWeir did this work in a previous version of Gradle to your knowledge?

**Comment by MichaelWeir** [comment]
It's a new project. It didn't work in Gradle 3.4.

**Comment by blindpirate** [comment]
It seems not like a bug. It's a feature of [Maven 3.2.2](https://maven.apache.org/docs/3.2.2/release-notes.html) which Gradle doesn't implement. Could I try to provide a pull request? @eriwen

**Comment by stevenkaza** [comment]
Hey guys, any update on this? 
It would be really useful!
Thanks

Steve

**Comment by blindpirate** [comment]
I guess maybe I could have a try.

**Comment by blindpirate** [comment]
Closed by #2730 .
