### ISSUE TITLE
Feedback for VERSION_CATALOGS: good code red in buildSrc/build.gradle.kts in IntelliJ

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#18999]
### Expected Behavior
Everything syntax highlighted nicely without errors.

### Current Behavior
As described in https://youtrack.jetbrains.com/issue/KTIJ-20166
![image](https://user-images.githubusercontent.com/2906988/141958337-7aa2715a-df75-42d3-b68d-60b01f638e1d.png)

### Context
I reported this in https://youtrack.jetbrains.com/issue/KTIJ-20166, but I believe the fix might lie in Gradle itself, but it's based on my limited knowledge of the integration. I think this because as far as I know IntelliJ is using the Gradle tooling API to extract classpath from Gradle runtime. Therefore they don't have control over what's put on the classpath by Gradle.

### Steps to Reproduce 
1. https://github.com/TWiStErRob/repros/tree/master/idea/gradle-versionCatalogs-classpath
2. Import to IntelliJ IDEA as Gradle project
3. Observe error in buildSrc/build.gradle.kts

### Your Environment

Build scan URL: N/A

### Workaround
Use a different libraries extension name in buildSrc.

**Comment by ljacomet** [comment]
Given that on the IntelliJ side, the issue ends up linking to https://youtrack.jetbrains.com/issue/IDEA-262280, I do not think Gradle has to do anything to make this work.
If this changes, we have communication channels with Jetbrains.
