### ISSUE TITLE
Old version of gradle daemon spinning up when buildSrc is building

### ISSUE THREAD

**Issue by eygraber** [gradle/gradle#18996]
### Expected Behavior
When building a project, a random Gradle daemon shouldn't be started

### Current Behavior
When building a project, a random Gradle daemon is started

### Context
I'm using SDKMan on Ubuntu 20.04 to manage local Gradle installations. My current default is set to 7.3

When I build my project, usually while buildSrc is getting built (but I've also noticed it at other times), a Gradle 6.8 daemon is started. Nothing in Gradle's output or scans indicates that another daemon is getting started, but I can see the process in my process manager.

I looked at the [6.8 daemon logs](https://github.com/gradle/gradle/files/7542812/daemon-2582810.out.log) (, and it seems like it tries to build my project's buildSrc, but fails (which makes sense because I'm using features introduced after 6.8).

I'm not able to share the project where this is happening, and I haven't had time to try and repro it yet.

Not sure if this would be related, but I started noticing this after I started getting frequent GC overhead OOM errors after updating to AGP 7.1.0 Beta.

**Comment by ljacomet** [comment]
We've had similar reports where somewhere between the IDE integration and the Gradle tooling API, the wrong daemon ends up being used.
This is usually observed after a branch switch where the two branches have a different wrapper configuration.

**Comment by eygraber** [comment]
In this case it happens when building from the command line, and I'm using a local installation of Gradle and not the wrapper.

Short of a repro, what info can I provide to help figure this out?

**Comment by ljacomet** [comment]
Are you sure you do not have build logic tests in `buildSrc` which would use a hardcoded Gradle version to run, via `TestKit`?

**Comment by eygraber** [comment]
Not as far as I know. 

Here's the `build.gradle.kts`:

```
@file:Suppress("UnstableApiUsage")

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  `kotlin-dsl`
}

repositories {
  mavenCentral()
  google()
}

tasks.withType<KotlinCompile>().configureEach {
  kotlinOptions {
    allWarningsAsErrors = true
  }
}

dependencies {
  implementation(files(libs.javaClass.superclass.protectionDomain.codeSource.location))
  implementation(libs.buildscript.android)
  implementation(libs.buildscript.kotlin)
  implementation(libs.buildscript.detekt)
  implementation(libs.kotlinx.serialization)
  implementation(libs.ejson)
}
```

And `settings.gradle.kts`:

```
enableFeaturePreview("VERSION_CATALOGS")

dependencyResolutionManagement {
  versionCatalogs {
    create("libs") {
      from(files("../gradle/libs.versions.toml"))
    }
  }
}
```

**Comment by eygraber** [comment]
I also have an included build as part of my project (wrapper version is 7.3 as well). Here's the `build.gradle.kts`:

```
@file:Suppress("UnstableApiUsage")

import io.gitlab.arturbosch.detekt.Detekt
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  kotlin("jvm") version libs.versions.kotlin.get()
  id("java-gradle-plugin")
  alias(libs.plugins.detekt)
}

tasks.withType<JavaCompile> {
  sourceCompatibility = libs.versions.jdk.get()
  targetCompatibility = libs.versions.jdk.get()
}

kotlin {
  jvmToolchain {
    (this as JavaToolchainSpec).languageVersion.set(JavaLanguageVersion.of(libs.versions.jdk.get()))
  }
}

tasks.withType<KotlinCompile>().configureEach {
  kotlinOptions {
    jvmTarget = libs.versions.jdk.get()

    freeCompilerArgs = freeCompilerArgs + listOf(
      "-Xopt-in=kotlin.RequiresOptIn"
    )

    allWarningsAsErrors = true
  }
}

gradlePlugin {
  plugins {
    create("com.myapp.build") {
      id = "com.myapp.build"
      implementationClass = "com.myapp.build.MyBuildPlugin"
      version = "1.0.0"
    }
  }
}

detekt {
  toolVersion = libs.versions.detekt.get()

  source.from("build.gradle.kts")

  autoCorrect = true
  parallel = true

  buildUponDefaultConfig = true

  config = project.files("${project.rootDir.parentFile}/detekt.yml")
}

tasks.withType<Detekt>().configureEach {
  // Target version of the generated JVM bytecode. It is used for type resolution.
  jvmTarget = libs.versions.jdk.get()
}

repositories {
  mavenCentral()
}

dependencies {
  implementation(gradleApi())

  implementation(libs.build.githubApi)
  implementation(libs.build.jgit)
  implementation(libs.build.mordantLogging)
  implementation(libs.build.semver)
  implementation(libs.build.slf4j)
  implementation(libs.build.square.retrofit.gson)
  implementation(libs.square.retrofit)
  implementation(libs.square.okHttpLoggingInterceptor)

  detektPlugins(libs.detekt)
  detektPlugins(libs.detektEygraber.formatting)
  detektPlugins(libs.detektEygraber.style)
}
```

And `settings.gradle.kts`:

```
enableFeaturePreview("VERSION_CATALOGS")

dependencyResolutionManagement {
  versionCatalogs {
    create("libs") {
      from(files("../gradle/libs.versions.toml"))
    }
  }
}

val isCI = System.getenv("IS_CI")?.toBoolean() ?: false

buildCache {
  local {
    isEnabled = !isCI

    isPush = !isCI
  }

  remote(HttpBuildCache::class) {
    isEnabled = isCI

    setUrl("redacted")
    isPush = isCI

    credentials {
      username = System.getenv("BUILD_SERVER_USERNAME") ?: ""
      password = System.getenv("BUILD_SERVER_PASSWORD") ?: ""
    }
  }
}
```

**Comment by ljacomet** [comment]
Could you share the log from that unrelated Gradle version?

**Comment by eygraber** [comment]
It should be linked in the original message.

**Comment by ljacomet** [comment]
🤦

**Comment by eygraber** [comment]
I believe this ended up being an issue with Android Studio where included builds were built separately. They now build them as part of the main project, and I haven't seen this issue since then.
