### ISSUE TITLE
Gradle 7.4 nightly breaks artifact transforms

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#19003]
Scan: https://ge.androidx.dev/s/ao3lcr3kfuauk/failure#1

To reproduce:
- repo: https://github.com/androidx/androidx repository branch `gradle74`
- `cd navigation`
- `./gradlew :hilt:hilt-navigation-fragment:hiltAggregateDepsDebugUnitTest`
- results in https://ge.androidx.dev/s/m5rzjpyd2iah2

**Comment by wolfs** [comment]
It seems like #17837 caused this. We treat the input artifacts of artifact transforms like if they had a `SkipWhenEmpty` annotation, which we shouldn't. This wasn't a problem before, since we empty source checking was only done for tasks.
