### ISSUE TITLE
Automatic Groovy to Kotlin DSL migration

### ISSUE THREAD

**Issue by almogtavor** [gradle/gradle#19013]
### Expected Behavior

I think the ability to migrate from Groovy DSL to Kotlin DSL in an automatic way is a pretty wanted feature. The ideal situation in my opinion would be if it was a `gradle init` kind of flag. In the exact same behavior as for the Maven to Gradle migration. I know it is not an easy one, but to my opinion, there are some basic steps that can be done so most of the simple `build.gradle` files would succeed the migration (e.g. replacing ' to ", add brackets, and more). I think that for too complex cases it sounds legitimate to tell the user which function should he migrate himself, and help him only with basic (and Sisyphean) stuff.

### Current Behavior

I am currently not aware of such an option of migrating Groovy DSL files into Kotlin DSL. [This README](https://github.com/jnizet/gradle-kotlin-dsl-migration-guide) is pretty useful though. And [this tool](https://github.com/bernaferrari/GradleKotlinConverter) seems to do exactly what I wish for, even though it is not maintained and not official.

### Context

Many Gradle users are going through the conversion from Groovy to Kotlin. I think this feature request is pretty common (we can see it in the amount of the stars of the GradleKotlinConverter tool).

**Comment by jbartok** [comment]
Unfortunately, for the moment we have no plans of providing this, due to lack of capacity.
