### ISSUE TITLE
GeneratePluginDescriptors.declarations triggers deprecation warning

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#19029]
`org.gradle.plugin.devel.tasks.GeneratePluginDescriptors#getDeclarations` missing @Nested annotation for use of `org.gradle.plugin.devel.PluginDeclaration`; according to the docs.

### Expected Behavior
```
No output
```

### Current Behavior
```
> Task :plugin:pluginDescriptors UP-TO-DATE
Using objects as inputs that have a different serialized form but are equal has been deprecated. This is scheduled to be removed in Gradle 8.0. Type 'org.gradle.plugin.devel.PluginDeclaration' has a custom implementation for equals(). Declare the
property as @Nested instead to expose its properties as inputs. See https://docs.gradle.org/7.3/userguide/upgrading_version_7.html#equals_up_to_date_deprecation for more details.
```

### Context
Configuration Cache triggers the warnings, but the warning seems to be about general Task declarations.
https://docs.gradle.org/7.3/userguide/upgrading_version_7.html#equals_up_to_date_deprecation

Note: https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:plugins:core lists "Java Plugin Development" as supported. I guess it is supported, because it works, but that warning is unnecessary.

### Steps to Reproduce 
1. https://github.com/TWiStErRob/repros/tree/master/gradle/configurationCache-pluginDescriptors-upToDate
2. `gradlew :pluginDescriptors`
3. `gradlew :pluginDescriptors`

### Your Environment

Build scan URL: N/A

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/20050.
