### ISSUE TITLE
Replace `com.jcraft:jsch` with `com.github.mwiede:jsch` so ed25519 SSH keys can be used

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#19028]
I'd be surprised if this idea hasn't been discussed before, but I couldn't find any mention of it, so I thought I'd make an issue.

### Behavior

Gradle does not use up to date dependencies that support ed25519 SSH keys.

### Context

Gradle declares a dependency on `com.jcraft:jsch:0.1.55`.

https://github.com/gradle/gradle/blob/4d54b872e15f36eb892f53f37a65717f2d16758d/build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt#L93

https://github.com/gradle/gradle/blob/4d54b872e15f36eb892f53f37a65717f2d16758d/subprojects/distributions-dependencies/build.gradle.kts#L102

This library has not been updated since 2018. It does not support ed25519 SSH keys, which is probably related to the following issues

* https://stackoverflow.com/q/56062772/4161471
* https://github.com/gradle/gradle/issues/8245
* https://github.com/gradle/gradle/issues/10585

Fortunately there's a quick fix. `com.github.mwiede:jsch:0.1.70` is a drop in replacement. From the README on https://github.com/mwiede/jsch:

> ### Why should you use this library?
> * OpenSSH will disable ssh-rsa in the future release 8.8 per default and you need a library which supports rsa-sha2-256 and rsa-sha2-512.
> * Drop in replacement: just change dependency coordinates and you are good to go.
> * No active maintenance of JSch at SourceForge.
> * Stay in sync with OpenJDK features so there is no need for additional dependencies.

Because Gradle already depends on `bcprov-jdk15on` I hope this is a quick fix that will allow ssh-ed25519 keys to be used.

**Comment by ljacomet** [comment]
Looks like the license is compatible, would you be willing to attempt a PR that does the switch?

**Comment by aSemy** [comment]
https://github.com/gradle/gradle/pull/19060

I've made a pull request, but I'm not able to verify that it's correct. The project is too large and I run out of memory. I'm also unable to exclude the existing dependency and replace it with the drop-in. I also get an error when doing the 'sign off'. Would someone be able to help fix these mistakes?

**Comment by martin-braun** [comment]
Thank you for this, [the JGit team doesn't really react](https://www.eclipse.org/forums/index.php?t=msg&th=1110330) on this issue.
