### ISSUE TITLE
Configuration cache issue when loading JNA lib during configuration

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#19027]
`com.sun.jna.Native.<clinit>` accesses system properties `java.io.tmpdir` and `jna.platform.library.path` --> [jna code](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Native.java).

This means that any Gradle plugin that loads a jna library at configuration time is unable to run with configuration cache on. In AGP we need that to find out if we are running on Rosetta or not, which is currently incompatible.
```
fun isRosetta() : Boolean {
  val clazz = try {
    @Suppress("UNCHECKED_CAST")
    Class.forName("com.sun.jna.platform.mac.SystemB") as? Class<Library> ?: return false
  }
  catch (e: ClassNotFoundException) {
    return false
  }
}
```

**Comment by bamboo** [comment]
Starting with Gradle 7.4, undeclared system property accesses will no longer fail the build. They will still be collected in the report as _inputs_.

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/18722 for Gradle 7.4
