### ISSUE TITLE
Configuration cache false positive when changing gradle.properties

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#19043]
### Context
I enabled `org.gradle.unsafe.configuration-cache=true` on a project and was running `:test`s. These tests use a property from `gradle.properties`. I was changing the properties file and running the tests as I would normally, but tests didn't execute.

### Expected Behavior
`:test` re-executed after change.

### Current Behavior
When changing the properties (file change) the configuration cache didn't get invalidated and still ran with the old values.

### Steps to Reproduce 
1. https://github.com/TWiStErRob/net.twisterrob.gradle/tree/fe1e4927cf74b0cabdec21a9357d455d8533d5f5 (specific commit, because I'll disable the cache)
2. `gradlew :plugin:test --tests "net.twisterrob.gradle.android.tasks.AndroidInstallRunnerTaskTest"`  
(the fastest test in the project, no need to run the whole thing)
3. Change `net.twisterrob.test.android.pluginVersion` to `4.1.3` in `gradle.properties`
4. `gradlew :plugin:test --tests "net.twisterrob.gradle.android.tasks.AndroidInstallRunnerTaskTest"`

Note: the properties are propagated and explicitly declared as input in `./build.gradle.kts` > `allprojects` > `projectsEvaluated` > `tasks.withType<Test>().configureEach {` > `properties.forEach`.

Add `properties.forEach { println(it) }` to see the actual values.

### Your Environment

Build scan URL: N/A, but happy to produce one if relevant.

**Comment by bamboo** [comment]
Thanks for the report!

This issue has been fixed in #19079 and the fix will be available in the upcoming 7.4 RC1
