### ISSUE TITLE
Unable to Resolve Class From Parent Object

### ISSUE THREAD

**Issue by theskylinetech** [gradle/gradle#19074]
A working project demo is attached

<img width="741" alt="Screen Shot 2021-11-21 at 11 48 22 AM" src="https://user-images.githubusercontent.com/60714626/142862177-ce697667-f447-4131-aa81-7149f59cb3c0.png">
<img width="1379" alt="Screen Shot 2021-11-21 at 12 20 32 PM" src="https://user-images.githubusercontent.com/60714626/142862180-cb4fa611-7574-4777-9e91-0dd164885ad3.png">
[inheritance-issue.zip](https://github.com/gradle/gradle/files/7580973/inheritance-issue.zip)

### Expected Behavior
Gradle should be able to compile the project

### Current Behavior
Gradle build complains that Builder cannot be resolved

### Context
The project cannot be built even though the IDE recognizes and resolves the class

### Steps to Reproduce 
-- A working project with all details implemented is attached
1. Create a new Gradle project with Groovy framework support
2. Create a new package called 'parents'
3. Create 2 new abstract classes
4. The second abstract class should extend the first
5. The first should have a generic Builder pattern
6. Create a third object that is dependent on the second abstract class

### Your Environment
Build scan URL:
https://scans.gradle.com/s/7dm6d6j6qj3o6

**Comment by octylFractal** [comment]
This is a bug in the Groovy compiler, not Gradle. Please report it to them.

Proof:
```bash
$ groovyc src/main/groovy/**.groovy
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
src/main/groovy/ThirdObject.groovy: 5: unable to resolve class Builder <ThirdObject>
 @ line 5, column 33.
       protected ThirdObject(final Builder<ThirdObject> builder) {
                                   ^

1 error
```
