### ISSUE TITLE
Sync fails because it couldn't resolve a dep, but compilation works just fine

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#19071]
Synchronization always fails, but compilation of the very same module passes fine, same for `:tasks`, it runs fine

### Expected Behavior
Sync'ing without issues

### Current Behavior
> Could not resolve kotlin.graphics:uno-core:0.7.10.
Required by:
    project :core
> Possible solution:
> - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

### Context
I'm trying to import [this dependency](https://github.com/kotlin-graphics/imgui/blob/bug/core/build.gradle.kts#L16) in the `core` module:
`implementation("kotlin.graphics:uno-core:0.7.10")`
My guess is that Gradle might have some issue importing JPMS packages with dashes inside their artifact naming

### Steps to Reproduce 
Clone [this branch](https://github.com/kotlin-graphics/imgui/tree/bug) and sync

### Your Environment
Gradle 7.3
OpenJdk 11
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Licensed to Assimp kotlin port / Giuseppe Barbieri
Subscription is active until March 2, 2022.
For non-commercial open source development only.
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-21-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins: org.toml.lang (0.2.155.4114-212), com.jetbrains.ChooseRuntime (1.2), com.intellij.nativeDebug (212.5284.19), com.4lex4.intellij.solarized (2.4.0), GLSL (1.19), com.intellij.guice (212.5080.8), com.kaylerrenslow.plugin.armaplugin.id (2.0.2), org.jetbrains.kotlin (212-1.6.0-release-799-IJ5457.46), org.jetbrains.compose.desktop.ide (1.0.0-beta6-dev474), kotest-plugin-intellij (1.1.41-IC-2021.1), com.jetbrains.plugins.ini4idea (212.5457.62), com.jetbrains.php (212.5457.49), Pythonid (212.5457.59), com.jetbrains.edu (2021.10-2021.2-627)
Kotlin: 212-1.6.0-release-799-IJ5457.46
Current Desktop: ubuntu:GNOME

**Comment by elect86** [comment]
I [narrow down](https://github.com/kotlin-graphics/build-logic/blob/master/base/src/main/kotlin/base.gradle.kts#L143) the issue:
```kotlin
configurations {
    named("jdk8Implementation") {
        extendsFrom(implementation.get())
    }
}
```
Of course `uno-core` is also multivariant

**Comment by jbartok** [comment]
Could you pls. provide us with a simpler reproducer? Or at least the full stack trace of the error?

**Comment by elect86** [comment]
Clone the branch I linked above under `Steps to Reproduce`. I noticed now you also need to have locally clone [build-logic](https://github.com/kotlin-graphics/build-logic) for the composite build. 

Then just sync `imgui` and you'll get the error. Comment out `extendsFrom` in `build-logic` and it'll sync fine

Can I generate a stacktrace from synchronizing?

**Comment by elect86** [comment]
Any news?

**Comment by ov7a** [comment]
Sorry for the late reply.

Can you confirm that this issue is still reproducible with the latest version of Gradle?

**Comment by elect86** [comment]
Sorry, I went further and I don't remember what I did now
