### ISSUE TITLE
Using Groovy runtime classes not exposed by Gradle in build script cause class loading errors

### ISSUE THREAD

**Issue by mozhuanzuojing** [gradle/gradle#19070]
I want to customize and use `JsonParserLax` to parse and modify the annotated JSON text, but now I run it and report an error.

### Expected Behavior
run successful. and can parse and modify annotated JSON text.

### Current Behavior
run error!
```log
Execution failed for task ':testJSON'.
> loader constraint violation: loader org.gradle.internal.classloader.VisitableURLClassLoader @322975c1 wants to load interface org.apache.groovy.json.FastStringService. 
A different interface with the same name was previously loaded by org.gradle.internal.classloader.VisitableURLClassLoader @1eb44e46. 
(org.apache.groovy.json.FastStringService is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @1eb44e46, parent loader org.gradle.internal.classloader.VisitableURLClassLoader @6f2b958e)
```
### Steps to Reproduce 
1. add task `testJSON` in rootDir/build.gradle
```gradle
buildscript {
   repositories {
        mavenCentral()
    }
   dependencies {
        // see org.gradle.api.internal.initialization.DefaultScriptClassPathResolver always exclude gradleApi and localGroovy
        classpath 'org.codehaus.groovy:groovy-json:3.0.9'
    }
}

import org.apache.groovy.json.internal.JsonParserLax
task testJSON(){
     group "json-test"
     doLast {
         def jsontext = """
             {
                 // Annotation
                 "files.encoding": "utf8"
             }
         """
         def jpl = new JsonParserLax()
         def res = jpl.parse(jsontext)
         println(res)
     }
 }
```
2. execute task `testJSON`

### Your Environment

Build scan URL: https://gradle.com/s/obvzyonjijsuy
- Gradle: 7.3
- JDK: 17
- OS: windows10

**Comment by jbartok** [comment]
Please provide a reproducer project and a build scan showing the error, because the one linked doesn't.

**Comment by donat** [comment]
I've reproduced the isssue: https://scans.gradle.com/s/6jifhynu2gbt2

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by mlopatkin** [comment]
The root cause is that Gradle limits the scope of the Groovy runtime that it exposes to the build scripts, and this may cause double-loading when Groovy runtime modules are re-added to the buildscript classpath.

A better solution in this case is to use a [`JavaExec` task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html) with a separate classpath, because even the isolated workers of the Worker API use Gradle runtime classloader as the base.

FWIW, `org.apache.groovy` classes are exposed starting from Gradle 8.0, so the original issue no longer reproduces (and the explicit dependency is no longer necessary).

What can be done in this issue is to ensure that Groovy runtime dependencies that duplicate existing Gradle-provided ones cannot be added.

**Comment by mozhuanzuojing** [comment]
> The root cause is that Gradle limits the scope of the Groovy runtime that it exposes to the build scripts, and this may cause double-loading when Groovy runtime modules are re-added to the buildscript classpath.
> 
> A better solution in this case is to use a [`JavaExec` task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html) with a separate classpath, because even the isolated workers of the Worker API use Gradle runtime classloader as the base.
> 
> FWIW, `org.apache.groovy` classes are exposed starting from Gradle 8.0, so the original issue no longer reproduces (and the explicit dependency is no longer necessary).
> 
> What can be done in this issue is to ensure that Groovy runtime dependencies that duplicate existing Gradle-provided ones cannot be added.

thank you for your reply. it work when i use gradle 8.6
