### ISSUE TITLE
[Build Scans] Class-based Settings Plugin breaks build scans when using pluginManagement.includeBuild(...)

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#19077]
Running the following build prints
`This build uses Gradle features that are incompatible with build scans (code: late-load-build-op).`
instead of publishing a build scan.
https://github.com/jjohannes/gradle-demos/tree/main/settings-plugin-late-load-build-op-issue/product

### Expected Behavior
A build scan should be produced.

### Current Behavior
No build scan, but info message printed.

### Context
This is likely caused by the fact that if the Settings Plugin is implemented as a class, the `pluginManagment.includeBuild(...)` is evaluated later compared to pre-compiled script plugins. As done [here](https://github.com/jjohannes/gradle-demos/blob/740191c539a759736b6ad37518267354069d477b/settings-plugin-late-load-build-op-issue/settings-plugin/src/main/java/MySmartSettingPlugin.java#L18) in the reproducer.
The issue does not exist with pre-compiled script plugins written in Groovy or Kotlin DSL.

It's unclear, if this is an issue with Gradle, the GE Plugin, or GE itself.

### Workaround

Use a pre-compiled script plugin instead of a Class-based plugin.

### Steps to Reproduce 
See instructions in:
https://github.com/jjohannes/gradle-demos/tree/main/settings-plugin-late-load-build-op-issue/product#readme

**Comment by DPUkyle** [comment]
Comment from the Gradle Enterprise team:
> We will take a look, but likely ... in the second half of December.

**Comment by facewindu** [comment]
@jjohannes Gradle Enterprise Gradle plugin 3.10 has just been released and it lifts the `late-load-build-op` restriction when a build runs before the root build.
This allows to capture build scans for builds where:
- a settings plugin includes a build coming from a class-based plugin, as here
- a Git source dependency is declared

**Comment by jjohannes** [comment]
Thanks @facewindu! I can confirm that this issue is fixed and works as expected with _Gradle Enterprise Gradle Plugin 3.10_.
