### ISSUE TITLE
bug templates missing after completing github login redirect

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#19093]
(not sure if this is something to do with Github itself or something about Gradle's bug templates)

Steps to reproduce:
1. Have a github account
2. Make sure you're logged out (push the button at the top right and then "Sign out")
3. Go to github.com/gradle/gradle
4. Click Issues
5. Click New Issue
6. Click Sign in, and complete authentication
7. Notice that no bug templates (Bug, Feature Request, etc) are visible, the url is simply https://github.com/gradle/gradle/issues/new rather than https://github.com/gradle/gradle/issues/new/choose .

**Comment by ljacomet** [comment]
Thanks for the report but this should go against Github itself. Our issues templates are pretty straightforward and I do not see how they could impact the login flow.

**Comment by mathjeff** [comment]
Thanks, after some more research it looks like this is https://github.com/github/feedback/discussions/4696
