### ISSUE TITLE
settings.gradle configuration caching support to declare property as input

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#19094]
### Expected Behavior
It would be nice if there were a way for settings.gradle to declare a property as an input in the same way that a project can do so (something like `project.providers.gradleProperty(ENABLE_FLAG_NAME).forUseAtConfigurationTime().isPresent`)

### Current Behavior
I haven't been able to find a way for settings.gradle to declare that the set of projects in the build depends on the value of a property (and that when that property changes, the set of projects in the build must be recomputed)

### Context
To allow more easily opening our projects in Android Studio (which takes more time to start as more projects are added), AndroidX has augmented our settings.gradle to check a property that if specified will restrict the set of projects participating in the build to just a specific project subset.

We also have a test (via gradle testkit) to make sure that each of these subsets can build successfully.

However, there was a breakage that this test didn't catch because the test was sharing the configuration cache between builds.

It also turns out that running this passes

`./gradlew -Pandroidx.projects=main help && ./gradlew -Pandroidx.projects=compose help`

whereas this fails with the correct error:

`./gradlew -Pandroidx.projects=main help && ./gradlew -Pandroidx.projects=compose help && ./gradlew -Pandroidx.projects=compose help --no-configuration-cache`

```
/usr/local/google/workspace/aosp-androidx-git/frameworks/support (work)$ gw -Pandroidx.projects=compose help --no-configuration-cache
Configuration on demand is an incubating feature.
Type-safe dependency accessors is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/google/workspace/aosp-androidx-git/frameworks/support/compose/integration-tests/docs-snippets/build.gradle' line: 48

* What went wrong:
A problem occurred evaluating project ':compose:integration-tests:docs-snippets'.
> Project with path ':window:window' could not be found in project ':compose:integration-tests:docs-snippets'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
19 actionable tasks: 19 up-to-date

For help with unexpected failures, see development/diagnose-build-failure/README.md

Failed: /usr/local/google/workspace/aosp-androidx-git/frameworks/support/gradlew -Pandroidx.projects=compose help --no-configuration-cache
```

### Workarounds
I can pass --no-configuration-cache in to the test, which at least causes the test to fail in the correct cases.

**Comment by eskatos** [comment]
Thank you for your report @mathjeff!

Since Gradle 6.8 and https://github.com/gradle/gradle/issues/14465 you should be able to use `providers.gradleProperty(...)` in a settings script, see https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/Settings.html#getProviders--

Does that work for your use case?

**Comment by mathjeff** [comment]
Thanks! That works

I'd checked

https://docs.gradle.org/7.2/dsl/org.gradle.api.initialization.Settings.html
but not
https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/Settings.html

**Comment by eskatos** [comment]
Thanks for confirming, closing
