### ISSUE TITLE
Restore Test Option Fail Fast Behavior for Gradle 8

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#19090]
After [this PR](https://github.com/gradle/gradle/pull/19087) makes it down to master, start a new branch reverting the reversion for Gradle 8.

There should be TODOs in the PR which mark the work to be done.

**Comment by big-guy** [comment]
@tresat is this done with the changes to `useJUnit()` and `options`?

**Comment by tresat** [comment]
I'll check on this.

**Comment by tresat** [comment]
This is no longer needed, other changes have impacted this behavior.
