### ISSUE TITLE
Eclipse Adoptium installations not found on MacOS

### ISSUE THREAD

**Issue by larsgrefer** [gradle/gradle#19117]
### Expected Behavior

I'd expect `./gradlew javaToolchains` to list all Eclipse Adoptium installations in `/Library/Java/JavaVirtualMachines/`

### Current Behavior
Gradle auto-provisions a JDK 8 to `/Users/larsgrefer/.gradle/jdks/jdk8u312-b07/Contents/Home` although I have one available at `/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home`

### Steps to Reproduce 
Install multiple Adoptium versions using homebrew:
`brew install temurin temurin8 temurin11`

Run `./gradlew javaToolchains`

### Your Environment

Build scan URL: https://scans.gradle.com/s/5usjdj3pmffh2

**Comment by ljacomet** [comment]
Can you try with `-d` for debug and see why these installations are not found?
Could you also share the output of `/usr/libexec/java_home -V` since this is what is used to find JVMs in `/Library/Java/JavaVirtualMachines`?

**Comment by larsgrefer** [comment]
`/usr/libexec/java_home -V` outputs:

```
Matching Java Virtual Machines (1):
    11.0.13 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 11" /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
```

but when I unset the `JAVA_VERSION` environment variable I get this:

```
atching Java Virtual Machines (3):
    17.0.1 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 17" /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    11.0.13 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 11" /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
    1.8.0_312 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 8" /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
```
