### ISSUE TITLE
Remove "clean with --parallel" warning

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1911]
We fixed the `clean build --parallel` issue and we will introduce the `@Destroys` annotation for the more exotic `build clean --parallel` use case. We should remove the warning that tells users that `clean and --parallel are not safe`. We should fix this for 4.0 to emphasize that we invested a lot in the safety of our execution engine.

**Comment by eriwen** [comment]
Is this still intended for 4.0?

**Comment by oehme** [comment]
Yes, it is.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/2043

**Comment by ghale** [comment]
This has been merged.
