### ISSUE TITLE
`GradleProperties has not been loaded yet` error when re-using stored configuration cache entry

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#19114]
I'm seeing the following error when re-using a stored configuration cache entry.

```
java.lang.IllegalStateException: GradleProperties has not been loaded yet.
```

This occurs when running the following task (only when re-using a stored configuration cache entry). On the first run when there is no stored configuration cache entry, the task works as expected.

```
./gradlew :printProps
```

```kts
tasks.register("printProps", PrintPropsTask::class) { }

abstract class PrintPropsTask @Inject constructor(
    private val providers: ProviderFactory
): DefaultTask() {

    @org.gradle.api.tasks.TaskAction
    fun doWork() {
       // occurs on this line
        logger.lifecycle(providers.gradleProperty("some.gradle.property").get())
    }
}
```

### Steps to Reproduce 
I don't have a reproducer at the moment - but could potentially try and make one later

### Your Environment
Gradle 7.3

**Comment by ZakTaccardi** [comment]
I don't think it's related to https://github.com/gradle/gradle/issues/15114 as I have not enabled dependency verification

**Comment by abstratt** [comment]
This looks like a duplicate of #19793, which involves included builds. @ZakTaccardi please reopen if you are positive your scenario did not involve included builds.

**Comment by abstratt** [comment]
Forgot to close. Added a test case mentioning #19793 that replicates the problem in the presence of included builds, which I am assuming was the case of the OP here. If it turns out it can be reproduced without involving included builds, please provide a reproducer and reopen.
