### ISSUE TITLE
Wrong receiver types shown for precompiled script plugins in composite builds in Intellij

### ISSUE THREAD

**Issue by cfraenkel** [gradle/gradle#19120]
### Expected Behavior

When editing a precompiled Script plugin included via composite build in IntelliJ the receiver should be correct.

### Current Behavior

Receivers are sometimes shown as "it" instead of "this".

![image](https://user-images.githubusercontent.com/20723556/143450228-d60b8589-2aa3-40f2-adb3-04423198a954.png)

### Context

I'm using precompiled script plugins in a multi-module project to maintain common configuration for all projects. The script plugin is included in the Build using `includeBuild()` in the root settings.xml.
When I edit the Plugins as a standalone project syntax highlighting works correctly and the correct receiver is chosen. When I include the plugin project using `includeBuild()` then the receiver is often `it` instead of `this`.

**To clarify: In either case the build works perfectly fine. It seems to be an Intellij / integration issue related to composite builds and precompiled script plugins**

### Steps to Reproduce 

[plugin-dev-kotlin.zip](https://github.com/gradle/gradle/files/7603431/plugin-dev-kotlin.zip)

### Your Environment

Build scan URL: https://scans.gradle.com/s/lfliknpqhoxhm

IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Kotlin: 212-1.6.0-release-799-IJ5457.46

**Comment by cfraenkel** [comment]
This might solely be an intellij issue - here's the corresponding youtrack issue: https://youtrack.jetbrains.com/issue/KTIJ-19958

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the core of the Gradle Build Tool.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/
