### ISSUE TITLE
Add `RepositoryHandler.google()`

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1912]
Google is creating its own public Maven repository. It would be great for them if we added them to the small list of "blessed" repositories that make it onto our public API, like `mavenCentral()` and `jcenter()`.

Considerations:

Ideally this could easily be added by a plugin, but there is no such infrastructure at the moment. Also, the maintenance burden for us is minimal.

**Comment by jbduncan** [comment]
That sounds interesting! Do you have a source for this information, like an announcement of some kind?
