### ISSUE TITLE
Make ConfigurationInternal.beforeLocking() public API 

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#19131]
### Expected Behavior
I can do `configuration.beforeLocking {}` in Kotlin DSL or in Plugins implemented as Classes without casting to `ConfigurationInternal` - `beforeLocking()` is a method on the `Configuration` interface.

### Current Behavior
I need to cast to `ConfigurationInternal`.

### Context
There is currently no public API to *modify the Attributes of a Configuration at the latest possible point*. Since setting Attributes is not lazy (i.e. does not support the Provider/Property API) it is necessary to be able to set attributes at this point in a build, because if attributes are set earlier, Plugins might override them if they use some method to "lazily" set an attribute ([Example in the BndPlugin where it is done during task configuration](https://github.com/bndtools/bnd/blob/66a5ee3232436e72efb044f682b28b3892945ee7/gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndUtils.java#L165-L178)),

Gradle's core plugins are themselves aware of this and [use](https://github.com/gradle/gradle/blob/e7f61eedc9331754b34d2671fc8e7c1972b8e94c/subprojects/plugins/src/main/java/org/gradle/api/plugins/jvm/internal/DefaultJvmPluginServices.java#L136) the `ConfigurationInternal.beforeLocking()` API for such a use case. Also, Gradle's own build [is using it](https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/build-logic/basics/src/main/kotlin/gradlebuild.minify.gradle.kts#L65).

Note: Both `Configuration.withDependencies()` and `Configuration.getIncoming().beforeResolve()` are not suitable as both can lead to a `Cannot change attributes of dependency configuration '...' after it has been resolved` error.

I think when `beforeLocking` was introduced it was done as internal API with the intend to replace it with "something better" soon. But since that did not happen for 3 years, I think it is time to just make it public.

I am happy to provide a PR for this if it will be processed and intergrated.

**Comment by ljacomet** [comment]
The support for lazy attribute values was actually added recently - see #18936

Can you check whether that would help your use case?

**Comment by jjohannes** [comment]
Thanks for making me aware. I will check as soon as I have the chance and report back.

**Comment by lacasseio** [comment]
This issue is very similar to https://github.com/gradle/gradle/issues/15729. However, in my case, I need to squeeze parent domain object configuration to ensure the `Configuration` is fully configured due to nested domain objects realized lazily.

**Comment by vlsi** [comment]
Just wondering if there should be `getAttributeProvider` method so plugins could adjust provider's values

**Comment by jjohannes** [comment]
@ljacomet attribute providers do not solve my use case.

The issue I have is that the plugin sets the attribute late. For doing that, it reads the current value and overwrites it. If I use a provider, the value is realized when that is done. So it effectively makes no difference.

In this case you can argue that the plugin is "doing things wrong". It should probably not set the value that late. And definitely not during task configuration as it does right now. Maybe the plugin itself could use the new provider API if it wants  to make a decision late. I don't understand all the details of that particular plugin.

Picking up @vlsi 's remark: could someone elaborate why properties are not used here? I could imagine having `getAttributeProperty()` (instead of `attributeProvider(...)`) which would then also allow a plugin to set a `convention(...)`.  (This is probably a discussion for another issue though...)

All in all, I think the discussion if `ConfigurationInternal.beforeLocking()` should be public is independent of attribute providers. There can always be cases where Plugins do "weird" things and you want to be able to react. @lacasseio 's remark also show that there are other cases where this is usefule.

For me, `ConfigurationInternal.beforeLocking()` clearly marks a good point in time where you want to put in some late configuration code. It might not be very "nice" but it is better than things like "afterEvaluate". In my head, it also fits what methods like `withDependencies{}` offer.

That's why my take on this is **to make it public to allow build authors to use this as fallback when there is no other solution**.

If you (Gradle team) do not agree, feel free to close this issue. If you agree, I am happy to open a PR if that helps you to get this one done.

**Comment by jjohannes** [comment]
Closing, as the method has been removed: https://github.com/gradle/gradle/pull/25126

My arguments for this having been a good fallback still stands. Luckily, in the project we needed this we reached a point were it now works without - by not using certain 3rd party plugins and by redesigning some of the project setup.
