### ISSUE TITLE
Incremental compile does not detect some classpath changes

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1913]
This just happened to me:

1. `baseServices:compileJava`
2. Remove Guava dependency
3. `baseServices:compileJava` UP-TO-DATE
4. `clean baseServices:compileJava` FAILED

**Comment by wolfs** [comment]
@oehme Was that on `master` with the wrapper from there (i.e. `4.0-20170426102539+0000`)? I just merged some changes which should fix problems like the one described.

**Comment by oehme** [comment]
I think I was on an earlier version when this happened, but please do give this a try yourself.

**Comment by adammurdoch** [comment]
Should add some coverage for changing the order of the classpath before closing this, I think

**Comment by melix** [comment]
I have submitted a new PR to fix the missing code coverage (and indeed, revealed a bug). See https://github.com/gradle/gradle/pull/2094

**Comment by melix** [comment]
Closing now that test coverage has been added and performance regression fixed.
