### ISSUE TITLE
Centralize build operation queue

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1914]
Right now, each call to `BuildOperationExecutor.runAll` creates its own queue that batches access to worker leases. This already improved things over acquiring a worker lease for each single build operation, but doesn't help when `runAll` is called a lot with only a few operations per call (e.g. dependency resolution).

Instead, we should have a single queue that batches across different calls to `runAll()` and only provide a thin layer on top of that so that each call still only waits for its own items to complete.

**Comment by eriwen** [comment]
@oehme Is this on the performance team to address? I don't think the Core team can get to this by 4.1 RC1

**Comment by oehme** [comment]
No and it's not as simple as I made it sound here. I'll just close this, since it's also not showing up as a hotspot in any recent snapshots.
