### ISSUE TITLE
Local plugin is not applied to non-root includeBuild project when doing gradle composite build

### ISSUE THREAD

**Issue by xinchao-zhang** [gradle/gradle#19148]
### Expected Behavior

When working on a Gradle plugin project, I would like to test my change in a **composite build** setup before releasing it. I am expecting my local plugin project, when I `includeBuild` it, will get applied to both the root project, and any other `includeBuild` project that depends on the plugin. For example:

root project: **foo** (depends on **bar**, and uses **my-plugin**)
includeBuild projects: **bar** (uses **my-plugin**), **my-plugin**

I am expecting the local version of my-plugin to be applied to **both foo and bar**

### Current Behavior

The local version of my-plugin is only applied to project foo (e.g. the root), but **NOT** to bar

### Context

We have a reasonable large setup of in-house developed interdependent projects. They all share the common software development lifecycle workflow which is extracted into a dedicated gradle plugin. So almost all projects depend on the plugin.

Usually a change to such a plugin is a cross-cutting concern (i.e. code-gen related), and we would like to test the plugin before making it visible to others. And to test such a change, we have to make a composite build over several projects which all uses the plugin, and check the overall result. We are also very particular about that this plugin needs to work under composite build setup, given multiple projects are being developed at the same time.

Because the plugin is only applied to the root project, we have to revert back to the old style (where there was no composite build) by publishing the plugin to` mavenLocal()` whenever we change it.

### Steps to Reproduce 

1. make three projects: **foo**, **bar** and **my-plugin**. my-plugin is the Gradle plugin that both foo and bar use. foo depends on bar
2. make a composite build rooted at foo, include both bar and my-plugin in the build. At this stage gradle won't even build the root because it complains not able to find my-plugin for bar.
3. if my-plugin is published to maven local, it will make the gradle happy, but any change in  my-plugin will only be reflected on foo but not on bar.

[gradle-composite-build-reproduce.tar.gz](https://github.com/gradle/gradle/files/7616467/gradle-composite-build-reproduce.tar.gz)

### Your Environment

Gradle Version: 7.2
OS: Ubuntu 21.10 impish (x86-64)

**Comment by ljacomet** [comment]
Just in case you were not aware, please check the following in documentation: https://docs.gradle.org/current/userguide/composite_builds.html#included_plugin_builds
(I did not look at your reproducer)

**Comment by jbartok** [comment]
Sorry for the late reply.

One way to fix your reproducer is to add `includeBuild '../my-plugin'` in `bar/settings.gradle`.
Once the composite layout is fixed, you could move back to using the `plugins` block instead of the old, imperative `apply`.

On the other hand, we would need to verify if this behavior for plugins matches the behavior of regular dependencies and if it's transitive in the same way.
