### ISSUE TITLE
./gradlew build fails on task checkstyleMain Unable to create a Checker with most XML files.

### ISSUE THREAD

**Issue by erikmartinessanches** [gradle/gradle#1916]
I'm trying to use the checkstyle plugin with Gradle, following the steps [in the gradle checkstyle docs](https://docs.gradle.org/current/userguide/checkstyle_plugin.html)

The XML file is in config/checkstyle/checkstyle.xml. I've used [this one](https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml)

My build.gradle file:

<pre>//This buildscript section applies to the execution of this buildscript itself,
//and not to the compilation or execution of the project.
buildscript {
	ext {
		springBootVersion = '1.5.3.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

repositories {
	mavenCentral()
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'checkstyle'
apply plugin: 'application'

mainClassName = 'hello.Application'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

// List of dependencies for building the project, used when running
// for example "gradlew build" to build the app.
dependencies {
	//compile('org.springframework.boot:spring-boot-starter-actuator')
	//compile('org.springframework.boot:spring-boot-starter-data-jpa')
	//compile('org.springframework.session:spring-session')
	compile('org.springframework.boot:spring-boot-starter-web')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

//This task sets the version for gradlew when running "gradle wrapper" to build
//the wrapper.
task wrapper(type: Wrapper) {
	gradleVersion = '3.5'
}

test {
	//ignoreFailures = true
	// This should allow output statements like System.out.println() to produce output
	// from the test cases when running "gradlew test".
	// May or may not be useful for simple debugging.
	testLogging.showStandardStreams = true
}

//You can upgrade or downgrade the version of Checkstyle with
//checkstyle {
////	toolVersion = '7.1'
//	configFile = rootProject.file('checkstyle/checkstyle.xml')
//}
</pre>

### Expected Behavior

Running  ./gradlew build should perform style check, report errors or build the project.

### Current Behavior

Running ./gradlew build --info produces:

<pre>
Initialized native services in: /Users/erik/.gradle/native
Connected to daemon DaemonInfo{pid=30718, address=[ebf05916-6285-45db-a972-3758eaba809e port:65132, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1493613256061, context=DefaultDaemonContext[uid=92d1eac0-67f9-40fd-8ef6-6587b082081e,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home,daemonRegistryDir=/Users/erik/.gradle/daemon,pid=30718,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=SE,-Duser.language=sv,-Duser.variant]}. Dispatching request Build{id=3585d724-7f2a-412b-a8cb-1f9d5e99ad1f.1, currentDir=/Users/erik/Documents/Dev/repos/appartifact}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@7d9e8ef7 from daemon DaemonInfo{pid=30718, address=[ebf05916-6285-45db-a972-3758eaba809e port:65132, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1493613256061, context=DefaultDaemonContext[uid=92d1eac0-67f9-40fd-8ef6-6587b082081e,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home,daemonRegistryDir=/Users/erik/.gradle/daemon,pid=30718,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=SE,-Duser.language=sv,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 30718). The daemon log file: /Users/erik/.gradle/daemon/3.5/daemon-30718.out.log
Starting 154th build in daemon [uptime: 3 hrs 16 mins 49.534 secs, performance: 97%, no major garbage collections]
Executing build with daemon context: DefaultDaemonContext[uid=92d1eac0-67f9-40fd-8ef6-6587b082081e,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home,daemonRegistryDir=/Users/erik/.gradle/daemon,pid=30718,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=SE,-Duser.language=sv,-Duser.variant]
Creating new cache for plugin-use-metadata, path /Users/erik/.gradle/caches/3.5/plugin-resolution/plugin-use-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@46d5ac20
Creating new cache for client-status, path /Users/erik/.gradle/caches/3.5/plugin-resolution/client-status.bin, access org.gradle.cache.internal.DefaultCacheAccess@46d5ac20
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/Users/erik/Documents/Dev/repos/appartifact/build.gradle'.
Included projects: [root project 'appartifact']
Evaluating root project 'appartifact' using build file '/Users/erik/Documents/Dev/repos/appartifact/build.gradle'.
Creating new cache for metadata-2.23/module-metadata, path /Users/erik/.gradle/caches/modules-2/metadata-2.23/module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@5ab9166d
Creating new cache for metadata-2.23/artifact-at-repository, path /Users/erik/.gradle/caches/modules-2/metadata-2.23/artifact-at-repository.bin, access org.gradle.cache.internal.DefaultCacheAccess@5ab9166d
Using 4 worker leases.
Creating new cache for fileHashes, path /Users/erik/Documents/Dev/repos/appartifact/.gradle/3.5/taskHistory/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@3ffafdb4
Applying dependency management to configuration 'apiElements' in project 'appartifact'
Applying dependency management to configuration 'archives' in project 'appartifact'
Applying dependency management to configuration 'compile' in project 'appartifact'
Applying dependency management to configuration 'compileClasspath' in project 'appartifact'
Applying dependency management to configuration 'compileOnly' in project 'appartifact'
Applying dependency management to configuration 'default' in project 'appartifact'
Applying dependency management to configuration 'implementation' in project 'appartifact'
Applying dependency management to configuration 'runtime' in project 'appartifact'
Applying dependency management to configuration 'runtimeClasspath' in project 'appartifact'
Applying dependency management to configuration 'runtimeElements' in project 'appartifact'
Applying dependency management to configuration 'runtimeOnly' in project 'appartifact'
Applying dependency management to configuration 'testCompile' in project 'appartifact'
Applying dependency management to configuration 'testCompileClasspath' in project 'appartifact'
Applying dependency management to configuration 'testCompileOnly' in project 'appartifact'
Applying dependency management to configuration 'testImplementation' in project 'appartifact'
Applying dependency management to configuration 'testRuntime' in project 'appartifact'
Applying dependency management to configuration 'testRuntimeClasspath' in project 'appartifact'
Applying dependency management to configuration 'testRuntimeOnly' in project 'appartifact'
Applying dependency management to configuration 'checkstyle' in project 'appartifact'
Configuring agent
All projects evaluated.
Selected primary task 'build' from project :
Creating new cache for annotation-processors, path /Users/erik/Documents/Dev/repos/appartifact/.gradle/3.5/fileContent/annotation-processors.bin, access org.gradle.cache.internal.DefaultCacheAccess@2f2e277a
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':findMainClass', task ':startScripts', task ':distTar', task ':distZip', task ':bootRepackage', task ':assemble', task ':checkstyleMain', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':checkstyleTest', task ':test', task ':check', task ':build']
Creating new cache for jvmClassSignatures, path /Users/erik/Documents/Dev/repos/appartifact/.gradle/3.5/taskHistory/jvmClassSignatures.bin, access org.gradle.cache.internal.DefaultCacheAccess@3ffafdb4
Creating new cache for fileSnapshots, path /Users/erik/Documents/Dev/repos/appartifact/.gradle/3.5/taskHistory/fileSnapshots.bin, access org.gradle.cache.internal.DefaultCacheAccess@3ffafdb4
Creating new cache for taskHistory, path /Users/erik/Documents/Dev/repos/appartifact/.gradle/3.5/taskHistory/taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@3ffafdb4
:compileJava (Thread[Daemon worker Thread 48,5,main]) started.
:compileJava
Putting task artifact state for task ':compileJava' into context took 0.001 secs.
Task :compileJava class loader hash: 41621835a1ddfd325406e64eb3109d65
Task :compileJava actions class loader hashes: [0dbc41bc5f1da000c3c3bb6c0c1522db, 750e1d72030581ace81f7325929812f4, 41621835a1ddfd325406e64eb3109d65]
Resolving dependency management for configuration 'compileClasspath' of project 'appartifact'
Resolving dependency management for configuration 'compileOnly' of project 'appartifact'
Resolving dependency management for configuration 'implementation' of project 'appartifact'
Resolving dependency management for configuration 'compile' of project 'appartifact'
Resolving global dependency management for project 'appartifact'
Excluding [commons-logging:commons-logging]
Executing task ':compileJava' (up-to-date check took 0.2 secs) due to:
  Output property 'destinationDir' file /Users/erik/Documents/Dev/repos/appartifact/build/classes/main has changed.
  Output property 'destinationDir' file /Users/erik/Documents/Dev/repos/appartifact/build/classes/main/hello has been removed.
  Output property 'destinationDir' file /Users/erik/Documents/Dev/repos/appartifact/build/classes/main/hello/Application.class has been removed.
All input files are considered out-of-date for incremental task ':compileJava'.
Compiling with JDK Java compiler API.
:compileJava (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.243 secs.
:processResources (Thread[Daemon worker Thread 48,5,main]) started.
:processResources
Putting task artifact state for task ':processResources' into context took 0.0 secs.
Task :processResources class loader hash: 41621835a1ddfd325406e64eb3109d65
Task :processResources actions class loader hashes: [750e1d72030581ace81f7325929812f4]
Executing task ':processResources' (up-to-date check took 0.002 secs) due to:
  Output property 'destinationDir' file /Users/erik/Documents/Dev/repos/appartifact/build/resources/main has changed.
  Output property 'destinationDir' file /Users/erik/Documents/Dev/repos/appartifact/build/resources/main/application.properties has been removed.
  Output property 'destinationDir' file /Users/erik/Documents/Dev/repos/appartifact/build/resources/main/static has been removed.
:processResources (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.01 secs.
:classes (Thread[Daemon worker Thread 48,5,main]) started.
:classes
Skipping task ':classes' as it has no actions.
:classes (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.001 secs.
:jar (Thread[Daemon worker Thread 48,5,main]) started.
:jar
Putting task artifact state for task ':jar' into context took 0.001 secs.
Task :jar class loader hash: 41621835a1ddfd325406e64eb3109d65
Task :jar actions class loader hashes: [750e1d72030581ace81f7325929812f4]
Executing task ':jar' (up-to-date check took 0.006 secs) due to:
  Output property 'archivePath' file /Users/erik/Documents/Dev/repos/appartifact/build/libs/appartifact-0.0.1-SNAPSHOT.jar has changed.
:jar (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.011 secs.
:findMainClass (Thread[Daemon worker Thread 48,5,main]) started.
:findMainClass
Putting task artifact state for task ':findMainClass' into context took 0.0 secs.
Executing task ':findMainClass' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:findMainClass (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.0 secs.
:startScripts (Thread[Daemon worker Thread 48,5,main]) started.
:startScripts
Putting task artifact state for task ':startScripts' into context took 0.0 secs.
Task :startScripts class loader hash: 41621835a1ddfd325406e64eb3109d65
Task :startScripts actions class loader hashes: [750e1d72030581ace81f7325929812f4, 41621835a1ddfd325406e64eb3109d65]
Resolving dependency management for configuration 'runtimeClasspath' of project 'appartifact'
Resolving dependency management for configuration 'runtimeOnly' of project 'appartifact'
Resolving dependency management for configuration 'runtime' of project 'appartifact'
Excluding []
Executing task ':startScripts' (up-to-date check took 0.008 secs) due to:
  Output property 'outputDir' file /Users/erik/Documents/Dev/repos/appartifact/build/scripts has changed.
  Output property 'outputDir' file /Users/erik/Documents/Dev/repos/appartifact/build/scripts/appartifact has been removed.
  Output property 'outputDir' file /Users/erik/Documents/Dev/repos/appartifact/build/scripts/appartifact.bat has been removed.
:startScripts (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.033 secs.
:distTar (Thread[Daemon worker Thread 48,5,main]) started.
:distTar
Putting task artifact state for task ':distTar' into context took 0.0 secs.
Task :distTar class loader hash: 750e1d72030581ace81f7325929812f4
Task :distTar actions class loader hashes: [750e1d72030581ace81f7325929812f4]
Executing task ':distTar' (up-to-date check took 0.002 secs) due to:
  Output property 'archivePath' file /Users/erik/Documents/Dev/repos/appartifact/build/distributions/appartifact-0.0.1-SNAPSHOT.tar has changed.
:distTar (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.103 secs.
:distZip (Thread[Daemon worker Thread 48,5,main]) started.
:distZip
Putting task artifact state for task ':distZip' into context took 0.0 secs.
Task :distZip class loader hash: 750e1d72030581ace81f7325929812f4
Task :distZip actions class loader hashes: [750e1d72030581ace81f7325929812f4]
Executing task ':distZip' (up-to-date check took 0.009 secs) due to:
  Output property 'archivePath' file /Users/erik/Documents/Dev/repos/appartifact/build/distributions/appartifact-0.0.1-SNAPSHOT.zip has changed.
:distZip (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.673 secs.
:bootRepackage (Thread[Daemon worker Thread 48,5,main]) started.
:bootRepackage
Putting task artifact state for task ':bootRepackage' into context took 0.0 secs.
Executing task ':bootRepackage' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Setting mainClass: hello.Application
Excluding []
:bootRepackage (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.079 secs.
:assemble (Thread[Daemon worker Thread 48,5,main]) started.
:assemble
Skipping task ':assemble' as it has no actions.
:assemble (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.0 secs.
:checkstyleMain (Thread[Daemon worker Thread 48,5,main]) started.
:checkstyleMain
Putting task artifact state for task ':checkstyleMain' into context took 0.001 secs.
Task :checkstyleMain class loader hash: 41621835a1ddfd325406e64eb3109d65
Task :checkstyleMain actions class loader hashes: [750e1d72030581ace81f7325929812f4, 41621835a1ddfd325406e64eb3109d65]
Excluding []
Resolving dependency management for configuration 'checkstyle' of project 'appartifact'
Executing task ':checkstyleMain' (up-to-date check took 0.015 secs) due to:
  Output property 'reports.enabledFileReportDestinations.html' file /Users/erik/Documents/Dev/repos/appartifact/build/reports/checkstyle/main.html has changed.
  Output property 'reports.enabledFileReportDestinations.xml' file /Users/erik/Documents/Dev/repos/appartifact/build/reports/checkstyle/main.xml has changed.
:checkstyleMain FAILED
:checkstyleMain (Thread[Daemon worker Thread 48,5,main]) completed. Took 0.633 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> Unable to create a Checker: configLocation {/Users/erik/Documents/Dev/repos/appartifact/config/checkstyle/checkstyle.xml}, classpath {/Users/erik/Documents/Dev/repos/appartifact/build/classes/main:/Users/erik/Documents/Dev/repos/appartifact/build/resources/main:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-web/1.5.3.RELEASE/37469baf2a75a9d2230391a5038f49d4018d2bcc/spring-boot-starter-web-1.5.3.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter/1.5.3.RELEASE/3b966d5e3d422474b7af2e73ae0d371ae02718b/spring-boot-starter-1.5.3.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-tomcat/1.5.3.RELEASE/1b71416805e0bbf6885ee65aae440adbad0afe60/spring-boot-starter-tomcat-1.5.3.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.hibernate/hibernate-validator/5.3.5.Final/622a9bcef2eed6d41b5b8e0662c36212009e375/hibernate-validator-5.3.5.Final.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.8.8/bf88c7b27e95cbadce4e7c316a56c3efffda8026/jackson-databind-2.8.8.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework/spring-web/4.3.8.RELEASE/ec1b675c2e234b0c776d36ed56c691520030026f/spring-web-4.3.8.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/4.3.8.RELEASE/7a00452c350de0fb80ecbcecfb8ce0145c46141e/spring-webmvc-4.3.8.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/1.5.3.RELEASE/5fedde3489afd5dbd82f9122aaec4c9f6da3d564/spring-boot-1.5.3.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/1.5.3.RELEASE/b2b4d4a704f039bf22787cc412b1dd34741821fc/spring-boot-autoconfigure-1.5.3.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-starter-logging/1.5.3.RELEASE/ae7f1d938755553b228dd7a7f98aebb0a683c099/spring-boot-starter-logging-1.5.3.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/4.3.8.RELEASE/cce6c251249e48f0a86aa578c2a0e262efa5a1e0/spring-core-4.3.8.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.17/7a27ea250c5130b2922b86dea63cbb1cc10a660c/snakeyaml-1.17.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/8.5.14/7ce577af04cadd7ab4b36f71503fc688d5d52ccf/tomcat-embed-core-8.5.14.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-el/8.5.14/9e8a7cd67420d9857dbc62f84a3082c2a4b4b3eb/tomcat-embed-el-8.5.14.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-websocket/8.5.14/254667b21d391dac7b1bc241c24be271d772caf7/tomcat-embed-websocket-8.5.14.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/8613ae82954779d518631e05daa73a6a954817d5/validation-api-1.1.0.Final.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.jboss.logging/jboss-logging/3.3.1.Final/c46217ab74b532568c0ed31dc599db3048bd1b67/jboss-logging-3.3.1.Final.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/com.fasterxml/classmate/1.3.3/864c8e370a691e343210cc7c532fc198cee460d8/classmate-1.3.3.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.8.0/45b426f7796b741035581a176744d91090e2e6fb/jackson-annotations-2.8.0.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.8.8/d478fb6de45a7c3d2cad07c8ad70c7f0a797a020/jackson-core-2.8.8.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework/spring-aop/4.3.8.RELEASE/2ee7e60f8838bff13c5def48fab571ab10553e5d/spring-aop-4.3.8.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework/spring-beans/4.3.8.RELEASE/9d39133bb80e13d643bfefd731fe86cab3aa2bd7/spring-beans-4.3.8.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework/spring-context/4.3.8.RELEASE/944073ac58ab78b78a7694d2c53d4ae9f634c815/spring-context-4.3.8.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.springframework/spring-expression/4.3.8.RELEASE/204f7e241f42f46b16baa3d190752703efd7797/spring-expression-4.3.8.RELEASE.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.1.11/ccedfbacef4a6515d2983e3f89ed753d5d4fb665/logback-classic-1.1.11.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/1.7.25/f8c32b13ff142a513eeb5b6330b1588dcb2c0461/jcl-over-slf4j-1.7.25.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.slf4j/jul-to-slf4j/1.7.25/af5364cd6679bfffb114f0dec8a157aaa283b76/jul-to-slf4j-1.7.25.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.slf4j/log4j-over-slf4j/1.7.25/a87bb47468f47ee7aabbd54f93e133d4215769c3/log4j-over-slf4j-1.7.25.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.1.11/88b8df40340eed549fb07e2613879bf6b006704d/logback-core-1.1.11.jar:/Users/erik/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 2.62 secs
Stopped 0 worker daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':checkstyleMain'.] from daemon DaemonInfo{pid=30718, address=[ebf05916-6285-45db-a972-3758eaba809e port:65132, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1493613256061, context=DefaultDaemonContext[uid=92d1eac0-67f9-40fd-8ef6-6587b082081e,javaHome=/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home,daemonRegistryDir=/Users/erik/.gradle/daemon,pid=30718,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=SE,-Duser.language=sv,-Duser.variant]} (build should be done).
</pre>

### Context

I'm not able to use the stylecheck plugin as described [in the gradle checkstyle docs](https://docs.gradle.org/current/userguide/checkstyle_plugin.html)
### Steps to Reproduce (for bugs)

Set up an IntelliJ Gradle project, follow the steps [in the gradle checkstyle docs](https://docs.gradle.org/current/userguide/checkstyle_plugin.html) using my build.gradle file above and the XML file I've linked to above. Then run ./gradlew build. This will fail.

### Your Environment

I'm using Intellij IDEA 2016.3.4
Gradle Plugin Version: 163.12024.16 (for IDEA)

My java classes are in a package 'hello' inside src/main/java. I don't have any test classes at the moment.

 * Build scan URL:

**Comment by bmuschko** [comment]
It's likely the same or a similar issues as described in this [post](https://discuss.gradle.org/t/checkstyle-checker-cannot-be-created-with-gradle-3-5/22474).

**Comment by erikmartinessanches** [comment]
I tried putting in a checkstyle version into gradle.build as suggested in the linked post:
```
checkstyle {
    toolVersion "7.6.1"
}
```
And even Using Me65's XML:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">        
        <module name="OperatorWrap">
            <property name="option" value="nl"/>
            <property name="tokens" value=METHOD_REF"/>
        </module>
    </module>
</module>
```

After running `./gradlew clean build`I still get the error I mentioned in the original post:

```
[...]
* What went wrong:
Execution failed for task ':checkstyleMain'.
> Unable to create Root Module: configLocation [...]
```

**Comment by erikmartinessanches** [comment]
There was a type in the Me65, XML above, once it was fixed it worked! 

I also tried a [different XML](https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/sun_checks.xml). Works nicely.

I'm using
```
checkstyle {
	toolVersion "7.6.1"
}
```

User error, closing issue.

**Comment by erikmartinessanches** [comment]
However, when using Me65's XML:
```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name = "Checker">
    <module name="TreeWalker">
        <module name="OperatorWrap">
            <property name="option" value="nl"/>
            <property name="tokens" value="METHOD_REF"/>
        </module>
    </module>
</module>
```
without 
```
checkstyle {
	toolVersion "7.6.1"
}
```
the error is 
```
* What went wrong:
Execution failed for task ':checkstyleMain'.
> Unable to create a Checker: configLocation 
```

**Comment by FriedrichFroebel** [comment]
See the [post by jjustinic](https://discuss.gradle.org/t/checkstyle-checker-cannot-be-created-with-gradle-3-5/22474/4) which describes the error you get when not specifying a version. The Checkstyle version used by Gradle 3.5 when not specifying any is 6.19 according to the release notes.

**Comment by bmuschko** [comment]
I am closing this issue as a solution has been provided. Thanks for everyone helping out! Great community support.

**Comment by tbanj** [comment]
@erikmartinessanches adding the
checkstyle {
	toolVersion "7.6.1"
}
works for me thanks
