### ISSUE TITLE
403 Forbidden error on package repository

### ISSUE THREAD

**Issue by aritranagnordcloud** [gradle/gradle#19181]
Hi, Gradle team!

I have cloned this repo. But I got an error as follows when I execute ./gradlew build.
`* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:classpath'.
   > Could not determine artifacts for io.quarkus:io.quarkus.gradle.plugin:1.13.3.Final
      > Could not get resource 'https://husqvarnadss.jfrog.io/artifactory/plugins-release/io/quarkus/io.quarkus.gradle.plugin/1.13.3.Final/io.quarkus.gradle.plugin-1.13.3.Final.jar'.
         > Could not HEAD 'https://husqvarnadss.jfrog.io/artifactory/plugins-release/io/quarkus/io.quarkus.gradle.plugin/1.13.3.Final/io.quarkus.gradle.plugin-1.13.3.Final.jar'. Received status code 403 from server: Forbidden
`

Expected Behavior
Build Project Successful

Current Behavior
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:classpath'.
   > Could not determine artifacts for io.quarkus:io.quarkus.gradle.plugin:1.13.3.Final
      > Could not get resource 'https://husqvarnadss.jfrog.io/artifactory/plugins-release/io/quarkus/io.quarkus.gradle.plugin/1.13.3.Final/io.quarkus.gradle.plugin-1.13.3.Final.jar'.
         > Could not HEAD 'https://husqvarnadss.jfrog.io/artifactory/plugins-release/io/quarkus/io.quarkus.gradle.plugin/1.13.3.Final/io.quarkus.gradle.plugin-1.13.3.Final.jar'. Received status code 403 from server: Forbidden

Your Environment
mac os 11.6
Java 11
Gradle 7.3

**Comment by octylFractal** [comment]
Unless you are intending to get the Quarkus plugin from that repository, you likely have something that is adding the repository, and we consider a 403 a hard failure because having different resolution between being logged in or not can be surprising. You should remove this repository, or list the Plugin Portal first.

Also, please use the community slack or forums for support issues such as this in the future.
