### ISSUE TITLE
ClassNotFoundException when applying custom plugin

### ISSUE THREAD

**Issue by ansman** [gradle/gradle#19189]
### Expected Behavior
A custom plugin should be able to refer to a potentially missing class if guarded by a `target.pluginManager.withPlugin` statement.

### Current Behavior
When Gradle tries to apply the plugin a `java.lang.ClassNotFoundException` is found if the optional dependency is not found on the classpath.

### Context
We have a custom plugin that helps us configure the Kotlin Gradle Plugin. The plugin looks like this:
```
target.pluginManager.withPlugin("org.jetbrains.kotlin.jvm") {
    target.extensions.configure(JavaPluginExtension::class.java) {
        it.sourceCompatibility = JavaVersion.VERSION_1_8
        it.targetCompatibility = JavaVersion.VERSION_1_8
    }
    target.tasks.withType(KotlinCompile::class.java).configureEach {
        it.kotlinOptions.configure()
    }
}
target.pluginManager.withPlugin("org.jetbrains.kotlin.android") {
    target.extensions.configure(JavaPluginExtension::class.java) {
        it.sourceCompatibility = JavaVersion.VERSION_1_8
        it.targetCompatibility = JavaVersion.VERSION_1_8
    }
    target.extensions.configure<BaseExtension>("android") { android ->
        android.kotlinOptions.configure()
    }
}
target.pluginManager.withPlugin("org.jetbrains.kotlin.kapt") {
    target.extensions.configure<KaptExtension>("kapt") {
        it.includeCompileClasspath = false
    }
}
```

The plugin support many types of Kotlin plugins among them is the Kotlin plugin for Android. Our plugin has a `compileOnly` dependency on the Android Gradle Plugin since not all consumers use Android. For these consumers the second config block should never be executed but when using Gradle 7+ applying the plugin causes an exception when Gradle tries to scan the plugin:
```
Caused by: java.lang.NoClassDefFoundError: com/android/build/gradle/BaseExtension
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:70)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:56)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:36)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:272)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:211)
        ... 247 more
Caused by: java.lang.ClassNotFoundException: com.android.build.gradle.BaseExtension
        ... 252 more
```

### Steps to Reproduce 
To reproduce you need to create a library project that refers to some dependency using `compileOnly` and some class in that dependency should be referenced inside a `pluginManager.withPlugin` block.

The consumer should then try to apply this plugin.

### Your Environment
This is using Gradle 7.3

**Comment by donat** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.


Also, could you please try reproducing the issue without the configuration cache enabled?

**Comment by aperevozchykov** [comment]
I had the same issue with a custom plugin in the android app. My plugin was in `buildSrc`, it had AGP `compileOnly` dependency as:
```kotlin
dependencies {
    compileOnly("com.android.tools.build:gradle:7.3.0")
}
```
and I was applying this plugin on my android library module so the library module for sure had AGP in the classpath. I was getting:
```
Caused by: java.lang.NoClassDefFoundError: com.android.build.api.variant.LibraryAndroidComponentsExtension
```
during the gradle sync. Plugin code:
```kotlin
class MyPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            val extension = extensions.getByType<LibraryAndroidComponentsExtension>() // fails here
        }
    }
}
```
 I was able to resolve it by moving the plugin from `buildSrc` into a standalone module `build-logic` and having this module as included build:
```
pluginManagement {
    ...
    includeBuild('build-logic')
}
```
It solved the issue with no other code changes, only by moving it out of `buildSrc`. Hope it will help someone but would be great to get the explanation from the Gradle team on the root of the issue.

**Comment by ljacomet** [comment]
We appreciate the effort that went into adding details to this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.

**Comment by louie-wh** [comment]
I also happen to the problem 
when write plugin at buildSrc and depency     dependencies {
    compileOnly("com.android.tools.build:gradle:7.3.0")
}
