### ISSUE TITLE
Named argument notation not supported for dependencies in test suite plugin

### ISSUE THREAD

**Issue by markslater** [gradle/gradle#19192]
### Expected Behavior
When declaring [dependencies of a test suite](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#configure_dependencies_of_a_test_suite), it should be possible to use map notation like in top level dependency declarations (e.g. `group = "org.junit.jupiter", name = "junit-jupiter", version = "5.8.2"`), rather than be forced to use string notation (e.g. `"org.junit.jupiter:junit-jupiter:5.8.2"`)

For example, the following should be valid:

```kotlin
testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
            dependencies {
                implementation(group = "org.junit.jupiter", name = "junit-jupiter", version = "5.8.2")
                runtimeOnly(group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.8.2")
            }
        }
    }
}
```

### Current Behavior
The test suite plugin requires dependencies to be declared using string notation.  The example above has to be rewritten as:

```kotlin
testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
            dependencies {
                implementation("org.junit.jupiter:junit-jupiter:5.8.2")
                runtimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
            }
        }
    }
}
```

### Context
In the interests of consistency, and hence ease of migration and also intuitiveness, test suite dependencies should be declared in the same ways as regular module dependencies.

In my opinion, map notation is easier to understand, and less prone to fat-finger errors.

### Steps to Reproduce 
See [example project](https://github.com/markslater/gradle-examples/tree/13356368fdc2e7f7356ed573e2a4e3830d62b051)

### Your Environment
Using Gradle 7.3.1

**Comment by donat** [comment]
@gradle/core could you please take a look?

**Comment by markslater** [comment]
> This is on hold for now.

Can you clarify - is it something you intend to support, but not for the time being, or has map notation been put on hold across Gradle as a whole?

**Comment by tresat** [comment]
@markslater Test suite work in general is on hold at the moment as we focus on other priorities.  Adding support for map notation, as well as other types of dependencies in suites is something that is still planned for when focus returns to this feature.

**Comment by tresat** [comment]
A quick update: we're currently working on improving dependency declarations for test suites and definitely want to ensure map notation works correctly regardless of DSL.  Expect something in Gradle 7.6, per issue #32 on the [Gradle roadmap](https://github.com/orgs/gradle/projects/31/views/1).

**Comment by markslater** [comment]
Awesome!  In a similar vein, please note #20786 / #16498 regarding support for map notation for BOMs in the Kotlin DSL... seems to be mostly getting tumbleweed so far :(

**Comment by tresat** [comment]
We're working on test suites first to try things on a slightly smaller scale before addressing the top-level dependencies handler.  I took a look at the issues you linked and updated them.  We're still experimenting with exactly how we want to evolve the test suites' `dependencies` block, and it may end up looking differently from the top-level `dependencies` block.

**Comment by octylFractal** [comment]
Edited title to reflect the actual notation used here, as it isn't Map notation but Kotlin's named arguments.

**Comment by octylFractal** [comment]
Closing as this was done as part of #21209.
