### ISSUE TITLE
apply plugin alias supported?

### ISSUE THREAD

**Issue by test210820** [gradle/gradle#19209]
![image](https://user-images.githubusercontent.com/65008815/144609121-a74d3b22-294f-4ebb-a015-fd49b3157b2b.png)

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

**Comment by lost22git** [comment]
```gradle
apply {
  plugin(libs.plugins.spotless.get().getPluginId())
}
```
