### ISSUE TITLE
Project failing to build because "Unsupported class file major version 61"

### ISSUE THREAD

**Issue by papuSpartan** [gradle/gradle#19205]
I'm trying to build a project but for some reason it errors out within less than a second.
[https://gist.github.com/papuSpartan/4bc9c4d7220f4092d759a8dccef38447](url)

### Expected Behavior
Gradle builds the project

### Current Behavior
Gradle fails to build

### Context
Trying to get a project to build

### Steps to Reproduce 
- clone https://github.com/paulevsGitch/BCLib.git
- sh gradlew build

### Your Environment
Build scan URL: https://gradle.com/s/2baemnv6lseee

**Comment by donat** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

I've tried your reproducer and got this:
```
An exception occurred applying plugin request [id: 'fabric-loom', version: '0.8-SNAPSHOT']
> Failed to apply plugin 'fabric-loom'.
   > You are using an outdated version of Java (11). Java 16 or higher is required.
     The JAVA_HOME environment variable is currently set to (/Users/donat/.sdkman/candidates/java/current).
```

You probably need to use a more recent Java version as well.

**Comment by papuSpartan** [comment]
I got it to build by using java 16 instead of 17

**Comment by asodja** [comment]
@papuSpartan I think updating the Gradle version to 7.3.1 might help you with that then. I see your project uses 7.0:
https://github.com/paulevsGitch/BCLib/blob/main/gradle/wrapper/gradle-wrapper.properties

Gradle officially supports Java 17 with 7.3  and later (but if you update use the latest 7.3.1):
https://docs.gradle.org/current/userguide/compatibility.html#java
