### ISSUE TITLE
Allow user to specify LIFECYCLE log level via CLI

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1920]
### Expected Behavior
- Add a command line option that sets the default log level to `LIFECYCLE`.
- The log level can be provided by command line in long and short notation.
    - The command line option is going to be `-l` or `--lifecycle`.
    - The command `gradle -?` renders the new command line option.
- All documentation is updated to reflect the change.

### Current Behavior
All other log levels have a switch `--quiet`, `--warn` etc. but lifecycle does not.

### Context
This is related to #1610 and #1919. We need a convenient way for users to go back to v3.x behavior if they wish

**Comment by bmuschko** [comment]
PR: https://github.com/gradle/gradle/pull/1921
