### ISSUE TITLE
Mismatch between published version and tagged version

### ISSUE THREAD

**Issue by vanniktech** [gradle/gradle#19215]
Gradle released version 7.3. It can be downloaded from `https://downloads.gradle-dn.com/distributions/gradle-7.3-all.zip`
However the Git tag is `7.3.0` - https://github.com/gradle/gradle/releases/tag/v7.3.0

Trying to download with `https://downloads.gradle-dn.com/distributions/gradle-7.3.0-all.zip` does not work.

Would it be possible to use the same version name again?

This started happening with Gradle 7.0

**Comment by ljacomet** [comment]
This is a historical difference, nothing has changed.
https://github.com/gradle/gradle/releases/tag/v6.8.0 and its download URL have the same issue.

There is no plan on fixing that though.
https://services.gradle.org/distributions/ is the source for locating the different distributions.
