### ISSUE TITLE
Add "withGroup" method to ProjectBuilder

### ISSUE THREAD

**Issue by thahnen** [gradle/gradle#19212]
### Expected Behavior
When creating a new Gradle project (e.g. in testing) using *ProjectBuilder* we'd like to chain a method like *withGroup* to automatically add a group when *ProjectBuilder.build* gets invoked. Just like the *withName* method does.

### Current Behavior
This is not possible yet. Currently we set a project group manually like here:
```kotlin
val project = ProjectBuilder.builder().withName("testName").build()
project.group = "com.testxyz"
```

### Context
We often have to create an object just to change add a group. Just not practicable when you want to add a project to any method via parameter as you always have to create the object, change the group, pass the object when it is not used afterwards.
It would be nicer when you could do sth. like this
```kotlin
fun testXYZ() {
    Testrunner.invokeTest(
        ProjectBuilder.builder().withName("testName").withGroup("com.testxyz").build(),
        testFunction
    )
}
```
instead of
```kotlin
fun testXYZ() {
    val project = ProjectBuilder.builder().withName("testName").build()
    project.group = "com.testxyz"
    Testrunner.invokeTest(
        project,
        testFunction
    )
}
```

This example is just a simple one - most of our use cases are much more complex!

**Comment by lacasseio** [comment]
In my personal opinion, you could wrap the API to be more fluent according to your needs. Recently, I turned on parallel test execution on JUnit and the ProjectBuilder # API is not thread safe. Thankfully, I previously wrapped the API so it was easy to synchronize it.

More over, withName builder method is for changing something that becomes immutable once the project os built. The group is never immutable which wouldn't make sense for the builder to have.

**Comment by blundell** [comment]
> We often have to create an object just to change add a group. Just not practicable when you want to add a project to any method via parameter as you always have to create the object, change the group, pass the object when it is not used afterwards.

Use `also`

```
fun testXYZ() {
    Testrunner.invokeTest(
        ProjectBuilder.builder().withName("testName").build().also { it.group = "com.testxyz" },
        testFunction
    )
}
```

**Comment by thahnen** [comment]
I actually did not know about this fine solution!
This will work, thank you very much :+1: 

Closed to usable solution!
