### ISSUE TITLE
Gradle daemon crashes with memcpy issue & worker jvms stays forever

### ISSUE THREAD

**Issue by dhamudeva** [gradle/gradle#1922]
We are moving to gradle from ant. We started using gradle 3.5 for building. The daemon crashes with memcpy issue. It mostly happens in pmd worker thread. 

### Expected Behavior
1. The build daemon should not be crashing.  
2. Even when it crashes the worker jvms are still up and running in the system, it has to be manually killed/cleaned up. They do not go away after 3 hours of inactivity.
3. Specifying jvmargs in project's gradle.properties with org.gradle.jvmargs is not getting passed to gradle daemon process. It should work.

### Current Behavior
1. When the gradle build runs, the daemon is crashing with memcpy issue.
2. Worker daemons stay forever in the background and does not get cleaned up after crash
3. Passing args to org.gradle.jvmargs do not get passed to gradle daemon.

### Context
I am using the gradle for java projects. We are newly moving to gradle. We found that it crashes every time in PMD worker thread with memcpy issue. I tried to find a similar issue and I could find this issue - https://issues.gradle.org/browse/GRADLE-3370 and it is already in resolved state. 

I tried to set the jvmargs for daemon in project's gradle.properties like
org.gradle.jvmargs=-Dsun.zip.disableMemoryMapping=true

but it has no effect on daemon, it does not run with it. 

dhamod   12128     1 28 16:15 ?        00:10:56 /x/eng/utils/java/Linux-x64/jdk1.8.0_51/bin/java -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /x/eng/rtpbld00/scratch/dhamod/bard_map_gradle/modules/gradle-user-home/wrapper/dists/gradle-3.5-bin/roeukcn9w7va46qickrhooc3/gradle-3.5/lib/gradle-launcher-3.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 3.5

### Steps to Reproduce (for bugs)
I just run the gradle build with java plugin and it tries the pmd check. During the pmd check, it fails. I have attached the error log. I am not sure I have sample project that can reproduce this issue. 
We are inside a firewall, we may not be able to run the build scan. Is there way I can build scan inside firewall and upload it to scans.gradle.com?

### Your Environment
 ./gradlew --version
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------
Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Linux 2.6.32-642.6.1.el6.x86_64 amd64

The project is hosted on NFS location - /x/eng/rtpbld00/scratch/dhamod/bard_map_gradle/modules/

[hs_err_pid20993.txt](https://github.com/gradle/gradle/files/968793/hs_err_pid20993.txt)

**Comment by dhamudeva** [comment]
Anyone is looking at this issue?

**Comment by lacasseio** [comment]
Thanks @dhamudeva for submitting this issue. Do you think you could provide us with a reproducible sample?

**Comment by dhamudeva** [comment]
Our gradle build consists of 44 projects. I am not sure I can provide reproducible sample. Doesn't the hs_err_pid*.txt file help?

**Comment by Keridos** [comment]
Also experiencing this with a project of mine: https://github.com/OpenModularTurretsTeam/OpenModularTurrets
Try cloning this, and then run "gradle setupDecompWorkspace build" and it should crash with the memcpy issue.

**Comment by dhamudeva** [comment]
Hello,

any update on this issue? I am seeing this error often in gradle 4.5

**Comment by dhamudeva** [comment]
Stack trace from hs_err_pid* file is listed below, does it provide any clue?

`Stack: [0x00007fe336bfc000,0x00007fe336cfd000],  sp=0x00007fe336cf81d8,  free space=1008k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x89993]  memcpy+0x2e3
C  [libzip.so+0x11f2f]  ZIP_GetEntry2+0xff
C  [libzip.so+0x3d30]  Java_java_util_zip_ZipFile_getEntry+0xf0
J 237  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007fe3c544100e [0x00007fe3c5440f40+0xce]
J 8951 C2 java.util.zip.ZipFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (86 bytes) @ 0x00007fe3c6dff6bc [0x00007fe3c6dff380+0x33c]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 237  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007fe3c5440f98 [0x00007fe3c5440f40+0x58]
J 8951 C2 java.util.zip.ZipFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (86 bytes) @ 0x00007fe3c6dff6bc [0x00007fe3c6dff380+0x33c]
J 78431 C2 sun.net.www.protocol.jar.JarURLConnection.connect()V (147 bytes) @ 0x00007fe3ce6df0d8 [0x00007fe3ce6defc0+0x118]
J 45872 C2 sun.net.www.protocol.jar.JarURLConnection.getInputStream()Ljava/io/InputStream; (97 bytes) @ 0x00007fe3c575fbf8 [0x00007fe3c575fbc0+0x38]
J 102222 C1 net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.getImportedClasses(Ljava/lang/String;)Ljava/util/Map; (212 bytes) @ 0x00007fe3cb02639c [0x00007fe3cb024300+0x209c]
J 102134 C1 net.sourceforge.pmd.lang.java.typeresolution.ClassTypeResolver.visit(Lnet/sourceforge/pmd/lang/java/ast/ASTCompilationUnit;Ljava/lang/Object;)Ljava/lang/Object; (223 bytes) @ 0x00007fe3c86f3adc [0x00007fe3c86f34a0+0x63c]
J 102129 C1 net.sourceforge.pmd.lang.java.AbstractJavaHandler$5.start(Lnet/sourceforge/pmd/lang/ast/Node;)V (19 bytes) @ 0x00007fe3c696ac6c [0x00007fe3c696a7a0+0x4cc]
J 102125 C1 net.sourceforge.pmd.SourceCodeProcessor.usesTypeResolution(Lnet/sourceforge/pmd/lang/LanguageVersion;Lnet/sourceforge/pmd/lang/ast/Node;Lnet/sourceforge/pmd/RuleSets;Lnet/sourceforge/pmd/lang/Language;)V (54 bytes) @ 0x00007fe3c8044404 [0x00007fe3c8044180+0x284]
J 102104 C1 net.sourceforge.pmd.SourceCodeProcessor.processSource(Ljava/io/Reader;Lnet/sourceforge/pmd/RuleSets;Lnet/sourceforge/pmd/RuleContext;)V (100 bytes) @ 0x00007fe3cbf2c33c [0x00007fe3cbf2bdc0+0x57c]
J 101250 C1 net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(Ljava/io/Reader;Lnet/sourceforge/pmd/RuleSets;Lnet/sourceforge/pmd/RuleContext;)V (111 bytes) @ 0x00007fe3c84cac14 [0x00007fe3c84ca200+0xa14]
J 101249 C1 net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(Ljava/io/InputStream;Lnet/sourceforge/pmd/RuleSets;Lnet/sourceforge/pmd/RuleContext;)V (58 bytes) @ 0x00007fe3c75cc11c [0x00007fe3c75cbdc0+0x35c]
j  net.sourceforge.pmd.processor.MonoThreadProcessor.processFiles(Lnet/sourceforge/pmd/RuleSetFactory;Ljava/util/List;Lnet/sourceforge/pmd/RuleContext;Ljava/util/List;)V+185
j  net.sourceforge.pmd.PMD.processFiles(Lnet/sourceforge/pmd/PMDConfiguration;Lnet/sourceforge/pmd/RuleSetFactory;Ljava/util/List;Lnet/sourceforge/pmd/RuleContext;Ljava/util/List;)V+50
j  net.sourceforge.pmd.ant.internal.PMDTaskImpl.doTask()V+517
j  net.sourceforge.pmd.ant.internal.PMDTaskImpl.execute()V+32
j  net.sourceforge.pmd.ant.PMDTask.execute()V+33
j  org.apache.tools.ant.UnknownElement.execute()V+25
j  sun.reflect.GeneratedMethodAccessor22844.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+36
J 5126 C2 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (62 bytes) @ 0x00007fe3c62cd9ec [0x00007fe3c62cd960+0x8c]
j  org.apache.tools.ant.dispatch.DispatchUtils.execute(Ljava/lang/Object;)V+518
j  groovy.util.AntBuilder.performTask(Lorg/apache/tools/ant/Task;)Ljava/lang/Object;+66
J 102719 C2 groovy.util.AntBuilder.nodeCompleted(Ljava/lang/Object;Ljava/lang/Object;)V (622 bytes) @ 0x00007fe3c8b30688 [0x00007fe3c8b2fa40+0xc48]
J 102824 C2 sun.reflect.GeneratedMethodAccessor22803.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (74 bytes) @ 0x00007fe3ccf28820 [0x00007fe3ccf28720+0x100]
J 93170 C2 org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(Ljava/lang/String;[Ljava/lang/Object;)Lorg/gradle/internal/metaobject/DynamicInvokeResult; (229 bytes) @ 0x00007fe3cb329874 [0x00007fe3cb3293e0+0x494]
J 71996 C2 groovy.util.BuilderSupport.doInvokeMethod(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (572 bytes) @ 0x00007fe3c8dfb4e8 [0x00007fe3c8dfa780+0xd68]
J 44718 C2 groovy.util.BuilderSupport.invokeMethod(Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object; (14 bytes) @ 0x00007fe3c7bb83b0 [0x00007fe3c7bb8360+0x50]
J 50555 C2 org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (95 bytes) @ 0x00007fe3c7e92220 [0x00007fe3c7e91e60+0x3c0]
J 42991 C1 org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (42 bytes) @ 0x00007fe3c6891a14 [0x00007fe3c6891500+0x514]
j  org.gradle.api.plugins.quality.internal.PmdInvoker$_invoke_closure2.doCall(Ljava/lang/Object;)Ljava/lang/Object;+131
j  sun.reflect.GeneratedMethodAccessor22996.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+40
J 23369 C2 org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;ZZ)Ljava/lang/Object; (892 bytes) @ 0x00007fe3c70855f8 [0x00007fe3c7084f00+0x6f8]
J 22477 C2 groovy.lang.Closure.call([Ljava/lang/Object;)Ljava/lang/Object; (30 bytes) @ 0x00007fe3c695b5ec [0x00007fe3c695b560+0x8c]
J 9970 C2 groovy.lang.Closure.call(Ljava/lang/Object;)Ljava/lang/Object; (13 bytes) @ 0x00007fe3c714effc [0x00007fe3c714ef60+0x9c]
J 14000 C2 org.gradle.api.internal.ClosureBackedAction.execute(Ljava/lang/Object;)V (133 bytes) @ 0x00007fe3c64d4ad4 [0x00007fe3c64d49e0+0xf4]
j  org.gradle.api.internal.ClosureBackedAction.execute(Ljava/lang/Object;Lgroovy/lang/Closure;)V+9
j  org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(Lorg/gradle/api/internal/project/antbuilder/CachedClassLoader;)V+68
j  org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder$2.execute(Ljava/lang/Object;)V+5
j  org.gradle.api.internal.project.antbuilder.ClassPathToClassLoaderCache.withCachedClassLoader(Lorg/gradle/internal/classpath/ClassPath;Lorg/gradle/api/internal/classloading/GroovySystemLoader;Lorg/gradle/api/internal/classloading/GroovySystemLoader;Lorg/gradle/internal/Factory;Lorg/gradle/api/Action;)V+231
j  org.gradle.api.internal.project.antbuilder.DefaultIsolatedAntBuilder.execute(Lgroovy/lang/Closure;)V+33
j  org.gradle.api.internal.project.IsolatedAntBuilder$execute$0.call(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;+17
j  org.gradle.api.plugins.quality.internal.PmdInvoker.invoke(Lorg/gradle/api/plugins/quality/Pmd;)V+555
j  org.gradle.api.plugins.quality.Pmd.run()V+1
j  sun.reflect.GeneratedMethodAccessor22982.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+36
J 43534 C2 org.gradle.internal.reflect.JavaMethod.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (74 bytes) @ 0x00007fe3caa487a0 [0x00007fe3caa48700+0xa0]
J 56903 C1 org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(Lorg/gradle/api/Task;Ljava/lang/String;)V (22 bytes) @ 0x00007fe3c546ea2c [0x00007fe3c546e4e0+0x54c]
J 46292 C1 org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(Lorg/gradle/api/Task;)V (56 bytes) @ 0x00007fe3cc1016cc [0x00007fe3cc1000c0+0x160c]
J 46291 C1 org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(Ljava/lang/Object;)V (9 bytes) @ 0x00007fe3c8901934 [0x00007fe3c8901740+0x1f4]
J 56902 C1 org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Lorg/gradle/api/Task;)V (54 bytes) @ 0x00007fe3cc005f3c [0x00007fe3cc0049c0+0x157c]
J 56901 C1 org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Ljava/lang/Object;)V (9 bytes) @ 0x00007fe3c62b6fc4 [0x00007fe3c62b6e40+0x184]
J 52410 C1 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(Lorg/gradle/internal/operations/BuildOperationContext;)V (195 bytes) @ 0x00007fe3cc189e9c [0x00007fe3cc189b00+0x39c]
J 25879 C2 org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(Lorg/gradle/internal/operations/BuildOperation;Lorg/gradle/internal/operations/BuildOperationWorker;Lorg/gradle/internal/progress/DefaultBuildOperationExecutor$DefaultBuildOperationState;)V (394 bytes) @ 0x00007fe3ca321e40 [0x00007fe3ca320e00+0x1040]
J 23376 C2 org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Lorg/gradle/internal/operations/RunnableBuildOperation;)V (38 bytes) @ 0x00007fe3c70185d0 [0x00007fe3c7018500+0xd0]
J 45950 C1 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)Lorg/gradle/api/GradleException; (219 bytes) @ 0x00007fe3cb984a8c [0x00007fe3cb9835a0+0x14ec]
J 45947 C1 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (141 bytes) @ 0x00007fe3cc4ea8f4 [0x00007fe3cc4ea160+0x794]
J 45946 C1 org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (111 bytes) @ 0x00007fe3c86800cc [0x00007fe3c867f660+0xa6c]
J 13025 C1 org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (109 bytes) @ 0x00007fe3c55a0dec [0x00007fe3c559fb40+0x12ac]
J 12577 C1 org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (108 bytes) @ 0x00007fe3c6749b1c [0x00007fe3c6748500+0x161c]
J 12575 C1 org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (125 bytes) @ 0x00007fe3c650cf54 [0x00007fe3c650be20+0x1134]
J 23947 C1 org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (359 bytes) @ 0x00007fe3c9905d04 [0x00007fe3c9901be0+0x4124]
J 65912 C2 org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (161 bytes) @ 0x00007fe3c65d7458 [0x00007fe3c65d70a0+0x3b8]
J 96017 C2 org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (91 bytes) @ 0x00007fe3cd3c0fdc [0x00007fe3cd3beda0+0x223c]
J 12365 C1 org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (62 bytes) @ 0x00007fe3c68ac1e4 [0x00007fe3c68ab980+0x864]
J 12364 C1 org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(Lorg/gradle/api/internal/TaskInternal;Lorg/gradle/api/internal/tasks/TaskStateInternal;Lorg/gradle/api/internal/tasks/TaskExecutionContext;)V (24 bytes) @ 0x00007fe3c673bd34 [0x00007fe3c673bc20+0x114]
J 11844 C1 org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(Lorg/gradle/internal/operations/BuildOperationContext;)V (135 bytes) @ 0x00007fe3c5ec2b3c [0x00007fe3c5ec21e0+0x95c]
J 25879 C2 org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(Lorg/gradle/internal/operations/BuildOperation;Lorg/gradle/internal/operations/BuildOperationWorker;Lorg/gradle/internal/progress/DefaultBuildOperationExecutor$DefaultBuildOperationState;)V (394 bytes) @ 0x00007fe3ca321e40 [0x00007fe3ca320e00+0x1040]
J 72272 C2 org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(Lorg/gradle/internal/work/WorkerLeaseRegistry$WorkerLease;Lorg/gradle/api/Action;)Z (62 bytes) @ 0x00007fe3cdf0b990 [0x00007fe3cdf0b500+0x490]
J 14487 C1 org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run()V (125 bytes) @ 0x00007fe3c7b3e9a4 [0x00007fe3c7b3df20+0xa84]
J 14724 C2 org.gradle.internal.concurrent.ManagedExecutorImpl$1.run()V (57 bytes) @ 0x00007fe3c7be7758 [0x00007fe3c7be7020+0x738]
J 78759 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007fe3cb60d360 [0x00007fe3cb60cf40+0x420]
J 78382 C2 org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run()V (13 bytes) @ 0x00007fe3ce65df70 [0x00007fe3ce65de40+0x130]
J 74848 C2 java.lang.Thread.run()V (17 bytes) @ 0x00007fe3cdfeeda8 [0x00007fe3cdfeed60+0x48]
v  ~StubRoutines::call_stub
`

**Comment by big-guy** [comment]
This looks like a problem with jar caching (the JDK does this) where the jar is overwritten.  When this occurs, can you tell if the Gradle build is compiling/creating jars for other projects?  Is the gradle user home shared with any other Gradle build (that could be happening at the same time)?  Could the build directory be shared with any other Gradle build at the same time?

Which version of PMD are you using? the Gradle default?

**Comment by dhamudeva** [comment]
>> When this occurs, can you tell if the Gradle build is compiling/creating jars for other projects? 

Yes, it is very much possible. We have parallel build enabled and we have ~50 projects. It is quite possible that while PMD runs for one project, jar creation happens for some other project.

>> Is the gradle user home shared with any other Gradle build (that could be happening at the same time)?

No, it is specific to perforce client. It is set at <p4clientroot>/modules/build-cache. I am the only one building on gradle today. We are migrating from ant to gradle. 

GRADLE_USER_HOME=/x/eng/rtpbld00/scratch/dhamod/bard_main_gradle/modules/build-cache

>> Could the build directory be shared with any other Gradle build at the same time?
No, only one build runs at a time.

>> Which version of PMD are you using? the Gradle default?
pmd version is - 5.2.2

**Comment by dhamudeva** [comment]
As per this link - https://stackoverflow.com/questions/38326183/jvm-crashed-in-java-util-zip-zipfile-getentry if I pass '-Dsun.zip.disableMemoryMapping=true', it should avoid the crashing. 

Can you pls let me know how can I pass this argument to gradle worker processes?

**Comment by davidburstrom** [comment]
@dhamudeva You should be able to set the parameter in the `JAVA_OPTS` environment variable, or modify the `gradlew` wrapper script and add it to the `DEFAULT_JVM_OPTS`, which might be easier option to work around the issue in a corporate environment.
