### ISSUE TITLE
Gradle 3.5 Application plugin sets incorrect classpath

### ISSUE THREAD

**Issue by ashlineldridge** [gradle/gradle#1923]
### Expected Behavior
Execution of the `distTar` / `distZip` task should produce an artefact containing `bin` scripts which correctly set the classpath to include the version of the application artefact being built regardless of the distribution archive name.

### Current Behavior
Executable script created by the Application plugin in Gradle 3.5 incorrectly sets the classpath when the execution of `distTar` / `distZip` is not preceded by `clean` and older artefacts exist in the `build` directory. This does not occur when I downgrade Gradle to 3.0.

### Steps to Reproduce (for bugs)
I've created the following repo which demonstrates the issue: https://github.com/ashlineldridge/foobar
Run the following:
```
./gradlew distTar -Pversion=0.0.1
./gradlew distTar -Pversion=0.0.2
```

The file `bin/foobar` inside `build/distributions/foobar.tar` should specify version 0.0.2 of the application jar to be on the classpath but it specifies 0.0.1. If you downgrade Gradle to be version 3.0 this problem does not occur.

### Your Environment
```
./gradlew --version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.12.4 x86_64
```

**Comment by lacasseio** [comment]
Could you help us out and narrow the version range for us to search for the regression? Could you also link [build scans](https://gradle.com/scans/get-started) for both of your steps to reproduce?

**Comment by ashlineldridge** [comment]
@lacasseio I can confirm that the regression occurs in 3.5. I can't reproduce the bug in 3.4.

Using 3.5 build scan for `./gradlew distTar -Pversion=0.0.1 --scan` is https://gradle.com/s/rpgy3j3geg7d6
And build scan for `./gradlew distTar -Pversion=0.0.2 --scan` is https://gradle.com/s/bsy7yaiopxdnk

**Comment by lacasseio** [comment]
PR https://github.com/gradle/gradle/pull/1936 will resolve this bug and should be part of Gradle 4.0.

**Comment by lacasseio** [comment]
Merged in master.
