### ISSUE TITLE
JavaToolchainService not available on JVM ecosystem projects

### ISSUE THREAD

**Issue by melix** [gradle/gradle#19234]
### Expected Behavior

The `JavaToolchainService` service should be available on projects which do not apply the `java` base plugin, but are still working in the Java ecosystem.

### Current Behavior

In order to use toolchains, a project must apply the `JavaBasePlugin` plugin.

### Context

I have a multi-project build where most of the subprojects are Java project, and the root project is an aggregator. As part of aggregation, it needs to generate some Javadocs. The aggregation only requires the application of the `JvmEcosystemPlugin` (to get the usual disambiguation rules for dependency resolution). However, in order to use toolchains for Javadocs, I need to apply the `JavaBasePlugin` which does _too much_ and risks that folks would reintroduce things on the root project that they shouldn't.

It would be good if the toolchains service was created as part of the `JvmEcosystemPlugin`, or, possibly, as part of its own plugin which would then be applied by the `JavaBasePlugin`, but that one could apply independently in their own plugin.

### Steps to Reproduce 

Create a project which only applies the `jvm-ecosystem` plugin: the `JavaToolchainService` service isn't available as an extension.

### Your Environment

Build scan URL: https://ge.micronaut.io/s/n7fjvvx2lrvjq

**Comment by h0tk3y** [comment]
The proposed fix is to move the registration of the `javaToolchains` extension to a separate plugin, `jvm-toolchains`. This is preferable over moving it to the `jvm-ecosystem` plugin in the sense that there are use cases involving running Java (with `JavaExec` tasks, which support `javaLauncher`s provided by toolchains) without the need for anything else in the JVM ecosystem (dependency resolution, source sets infrastructure).
