### ISSUE TITLE
Gradle 5.0 issue with Apple Silicon (M1) with creating new files

### ISSUE THREAD

**Issue by brbulic** [gradle/gradle#19249]
Gradle bug with version 5.0 when running on Apple Silicon (M1) with a ARM64 java JDK with creating files in gradle jobs. The issue has been isolated in the github repository attached to this ticket.

### Expected Behavior
When running the same gradle job the Intel (x86_64) based JDK distribution executes the job and creates a file - either via Rosetta or on an Intel Mac

### Current Behavior
```
A build exception is thrown with an error that file doesn't exist even if file exists.
java.io.FileNotFoundException: build/files/testFile.txt (No such file or directory)
> build/files/testFile.txt (No such file or directory)
```

### Context
Executing gradle tasks and compiling Java code for our enterprise project on Gradle 5.0 and JDK 11 on Intel Machines work fine.

The company depends on first-party and third-party Gradle plugins which are written against Gradle 5, and those cannot compile on Developer machines running M1 macs.

### Steps to Reproduce 
Here is a github project with the issue: https://github.com/brbulic/gradle-m1-file-bug. 

### Your Environment
Build scan URL: https://scans.gradle.com/s/eslzsknlvgyoy

Specs:
16" Macbook Pro M1 Max
12.0.1 (21A559) Monterey
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS) ARM64e

**Comment by big-guy** [comment]
I'm not sure if Gradle 5 will work with an ARM JDK.

If you replace `def outputDir = new File(path)` with `def outputDir = file(path)`, does it work for both JDKs?

**Comment by brbulic** [comment]
When changing to `file(path)` it works. Thanks!

Why doesn't File object work in Gradle 5 and 6, but works with Gradle 7?

**Comment by ov7a** [comment]
Sorry for the late reply.

In short, `file(path)` is a [safer](https://docs.gradle.org/current/userguide/working_with_files.html#sec:single_file_paths) alternative to `File`.

I'm closing this as a question.
