### ISSUE TITLE
`apply false` plugin modifier does not appear to always work in precompiled script plugins

### ISSUE THREAD

**Issue by matejdro** [gradle/gradle#19247]
### Expected Behavior

`id("com.android.library") apply false` should only add the plugin to the script's classpath, but it should not actually apply the plugin

### Current Behavior

Plugin is applied (at least in this case)

### Context

In gradle kts precompiled plugin in the Android app, I need access to the `implementation` and `api` dependency extensions. 

To get access to that, I need to add one of the android plugins to the classpath. However, since this plugin is used by both app and library modules, I don't want to actually apply the plugin, only add it to the classpath. But not applying the plugin does not appear to work.

### Steps to Reproduce 

1. Download [ApplyTest.zip](https://github.com/gradle/gradle/files/7674245/ApplyTest.zip)
2. Run `./gradlew assemble` on the above project
3. Note that build will fail with `Failed to apply plugin 'com.android.internal.library'`. But this plugin should not have been applied in the first place since it has `apply false`

**Comment by rivancic** [comment]
I have similar issue.

I am creating a precompiled plugin where I need to follow a specific order of how plugins are applied. If I do this in normal project then _apply false_ flag is respected.

Precompile script plugin PSP:
```
plugins {
  id "A" apply false
  id "B" apply false
  id "C" apply false
}

// some plugin specific logic

// then apply plugins
/*
apply plugin: "A"
apply from: "https://remote-plugin"
apply plugin: "B"
apply plugin: "C"
```


Main project
```
plugins {
  id "PSP" version "0.1.0" 
}
...
```


I receive exception that plugin A could not be applied as some methods/tasks are missing. And this is correct. as precompiled script plugin PSP contains some logic to add those tasks before plugin A is being actually applied. And if apply false flag would be respected then plugin A would only be applied after the tasks would be added.

The only solution I see ATM is to wrap everything again in another precompiled script plugin that would invoke those plugins in order

Wrapper precompiled plugin WPSP:
```
plugins {
  id "PSP"
  id "A" 
  id "B" 
  id "C"
}
```

And then in the main project apply Wrapper precompiled script plugin:
```
plugins {
  id "WPSP" version "0.1.0" 
}
```

**Comment by Vampire** [comment]
This is a duplicate of #14437.
`apply false` in a precompiled script plugin does not make any sense and should throw an exception it not even compile.

**Comment by matejdro** [comment]
You are right. Will close my issue.
