### ISSUE TITLE
'Dependency lock state out of date' after running resolveAndLock

### ISSUE THREAD

**Issue by nivsa** [gradle/gradle#19265]
We applied lockfiles in our projects and almost immediately we started seeing issues with dependencies which are not locked even though they should be. We run the `resolveAndLock --write-locks` task and it creates the lockfiles but after that when we run `./gradlew clean build` it fails with:

```
> Could not resolve all files for configuration ':project:runtimeClasspath'.
   > Resolved 'com.google.code.findbugs:annotations:2.0.0' which is not part of the dependency lock state
```

Output from `./gradlew dependencyInsight --configuration runtimeClasspath --dependency com.google.code.findbugs:annotations`

```
com.google.code.findbugs:annotations:2.0.0 FAILED
   Selection reasons:
      - By constraint : Dependency locking
   Failures:
      - Dependency lock state out of date:
          - Resolved 'com.google.code.findbugs:annotations:2.0.0' which is not part of the dependency lock state

com.google.code.findbugs:annotations:2.0.0 FAILED
+--- runtimeClasspath
(can't share the following due to legal limitations but I can tell it contains BOM that sets the version as a constraint and a dependency which brings it transitively without a specified version)
```

Lockfiles code snippet:
```
dependencyLocking {
    lockAllConfigurations()
}


tasks.register('resolveAndLockAll') {
    doFirst {
        assert gradle.startParameter.writeDependencyLocks
    }
    doLast {
        configurations.findAll {
            // Add any custom filtering on the configurations to be resolved
            it.canBeResolved
        }.each { it.resolve() }
    }
}

dependencyLocking {
    lockMode = LockMode.STRICT
}
```

Is there anything else we can check on the environment to get more details why the dependency resolution failed or why didn't the `resolveAndLock` resolve this dependency?

### Expected Behavior

Building the project after executing `resolveAndLock` should pass successfully.

### Current Behavior

Building the project after executing `resolveAndWriteLocks` fails on dependency lock state

### Context

This issue brings a lot of inconvenience into working with lockfiles. The current workarounds we found for the issue are either adding the problematic dependency to the specific project where it fails, or excluding the dependency from all configurations in that project.

### Steps to Reproduce 

Due to legal restrictions we can't share an example project. We did try to reproduce it on a toy project but it didn't reproduce.

### Your Environment
Gradle versions tested (where the bug still reproduce) - 6.7.1, 6.9.1, 7.3.1
Lockfiles applied with STRICT mode

**Comment by MatanSabag** [comment]
I witnessed the same behavior in some of our projects

**Comment by ljacomet** [comment]
It would be interesting to get the `dependencies` output for `runtimeClasspath` without locking and with locking in lenient mode.
There must be a resolution bug that changes the resolution result when locking is applied.

It will be unfortunately quite hard to track without a reproducer or a good idea of how the dependency graph looks like.

**Comment by jskillin-idt** [comment]
If it helps the reporter, this _may_ be related to #22525

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
