### ISSUE TITLE
Error aapt2 gradle android develops

### ISSUE THREAD

**Issue by miqueias9889** [gradle/gradle#19271]
So I have named 32bit linux an aapt2 version 3.+ which has the functional function for gradle, but gradle uses its own aapt2 version which is not compatible with my 32bit linux, if I could make gradle use the aapt2 I have could generate .aab on my 32bit linux.

Is there any way to define or modify which aapt2 gradle will use?
OR
Could I trick gradle into using my aapt2 that I set?

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
