### ISSUE TITLE
Disabling transitive dependencies for a nested configuration doesn't work

### ISSUE THREAD

**Issue by TeodoroFilippini** [gradle/gradle#19277]
Defining `transitive = false` on a configuration doesn't work, if that configuration is in turn used by another configuration.

### Expected Behavior

With the following `configurations` block:
```
configurations {
        configurationOne {
                transitive = false
        }
        configurationTwo {
                dependsOn configurationOne
        }
}
```

Evaluating  `configurationOne` or `configurationTwo` results in the transitive dependencies of `configurationOne` being correctly ignored. 

### Current Behavior

Evaluating  `configurationOne` results in the transitive dependencies being correctly ignored. 
However, **evaluating `configurationTwo` results in all the transitive dependencies of `configurationOne` being evaluated**.

The current solution is to set `transitive = false` on each of the dependencies of `configurationOne`. This is verbose and counterintuitive. Why should it work when the flag is set on single dependencies and not if the flag is set for the whole configuration?

### Context

We have a configuration with numerous dependencies provided by an external entity. We want to include these dependencies in our `war` configuration, but we don't want the transitive dependencies to come with them.

### Your Environment

------------------------------------------------------------
Gradle 6.6
------------------------------------------------------------

Build time:   2020-08-10 22:06:19 UTC
Revision:     d119144684a0c301aea027b79857815659e431b9

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_291 (Oracle Corporation 25.291-b10)
OS:           Windows 10 10.0 amd64

**Comment by ljacomet** [comment]
`resolutionStrategy` is per configuration. So what you observe (assuming you meant `extendsFrom` and not `dependsOn`) is the expected result.
You should only mark _resolvable_ configurations as `transitive = false` and this property does not inherit.
It is for example impossible to express that with _resolvable_ C which `extendsFrom` A and B, you want A non transitive and B transitive.

**Comment by TeodoroFilippini** [comment]
Hey @ljacomet 

Thank you for your comment. I did mean `extendsFrom`. So for my situation I need to mark the single dependencies in `configurationOne` as non-transitive? That's quite verbose. I'd expect something like

```
configurations {
        configurationOne 
        configurationTwo {
                dependsOn configurationOne {
                          transitive = false
                 }
                 dependsOn configurationThree //transitive
        }
}
``` 

To be possible, but that doesn't work (it makes the whole `configurationTwo` non-transitive).

**Comment by ljacomet** [comment]
Indeed that's not possible, that's what my last sentence was describing.

Out of curiosity, what is the use case?

**Comment by TeodoroFilippini** [comment]
I see. I thought you were referring to a theoretical impossibility, but this is a missing feature. 

We have a configuration for dependencies whose transitives we don't want to take due to some conflicting versions. They are coming from an external source. We already checked the versions one by one and know this filtering is okay. 

We will keep disabling transitivity explicitly. Thank you again for your input and your time.
