### ISSUE TITLE
Support JDK 18

### ISSUE THREAD

**Issue by sormuras** [gradle/gradle#19283]
As mentioned in https://github.com/gradle/gradle/issues/18465#issuecomment-991057986 an upgrade to [ASM 9.2](https://asm.ow2.io/versions.html) is required to support scanning/parsing/reading classes compiled to Java 18.

**Comment by ice1000** [comment]
It's now a week before JDK 18 GA :)

**Comment by octylFractal** [comment]
Keeping track of the issues with console encoding (these stem from the console default charset no longer aligning with `Charset.defaultCharset()`):
- Need unicode output tests for the following:
  - [ ] TestKit
  - [ ] `Test` task
  - [ ] JVM metadata detection
  - [ ] GCC metadata detection
  - TODO find more places we capture console output with the default encoding.

**Comment by sormuras** [comment]
Fine!

Now, on to https://github.com/gradle/gradle/issues/20372

**Comment by danielpeintner** [comment]
> We still need to add JDK18 to compatibility guide, release notes and release features

I think updates to Compatibility Matrix are still missing...
https://docs.gradle.org/current/userguide/compatibility.html

If you are aware of it and want to wait for the official 7.5 release it is fine..

**Comment by danielpeintner** [comment]
What I meant was that the [website](https://docs.gradle.org/current/userguide/compatibility.html) is not yet showing the update but that might be because 7.5.x has not been officially published. Thanks!
