### ISSUE TITLE
Document where to find Options from tasks

### ISSUE THREAD

**Issue by mgrazebrook** [gradle/gradle#19296]
The command line help text does not document the rather useful --args parameter.

### Expected Behavior
Given --args actually comes from the 'application' plugin, a link in the HTML docs and possibly the command line help text would be useful. Possibly in a 'see also' section of --help (a bit like old-school man pages?)

### Current Behavior
No hint about how one could set a command line arg

### Context
I'm a newb, new to both Java and gradle. I was working through a [tutorial](http://www.slf4j.org/manual.html). I though: "Let's try to use a command line parameter" and first attempted gradle --help. No help. I googled "gradle run with command line params" and selected this link (not the first one) as I thought gradle.org would be authoritative: no luck. https://docs.gradle.org/current/userguide/command_line_interface.html.

Only after I'd found the solution from here: https://www.baeldung.com/gradle-command-line-arguments did I work out a targeted search which could give me an answer:
"site:https://docs.gradle.org/ --args"

So I see that it's actually the application plugin which introduces --args; however wanting to run with --args is (in my newb imagination) a common enough requirement that surely it deserves at least a link and searchability from the main sources of documentation? 

### Steps to Reproduce 
```
./gradlew --help 
```

### Your Environment
% ./gradlew --version

------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.13 (Amazon.com Inc. 11.0.13+8-LTS)
OS:           Mac OS X 12.0.1 x86_64

**Comment by octylFractal** [comment]
Due to how `@Option` works, this information cannot be collected in `--help` as it is only known after the task graph is created. This information is already exposed via `gradle help --task=run`, where you can specify any task to get information on its options.

**Comment by mgrazebrook** [comment]
What about this: Note in --help (which will often be used by newbs) that plugins can introduce new arguments (and maybe a hint on how to find out more) while the online command line arguments page could target this explicitly?

**Comment by octylFractal** [comment]
Sure. I will adjust this issue to be about documenting that.

**Comment by mgrazebrook** [comment]
Thanks. I must say I'm impressed at how quickly and well you've dealt with this!
