### ISSUE TITLE
Circular dependency error for identically named sub modules on different paths

### ISSUE THREAD

**Issue by chrispoulsen** [gradle/gradle#19320]
I was messing around with a multi module build and had the following modules:

:api:model:area
:impl:model:area

Both modules use the java library plugin and :impl:model:area has an implementation dependency on project(':api:model:area')

When I try to issue ./gradlew build it complains about :impl:model:area having a circular dependency against itself. 

Maybe the identical :area parts confuses gradle ?

### Expected Behavior
Either the build should work or if it is an expected error it should have a better description.

### Current Behavior
An error saying that :impl:model:area has a circular dependency against itself

### Context
I was trying to have "api" and "impl" nicely separated while communicating that they are about the same thing ("model:area")

I ended up flattening the modules into ":api-model-area" and ":impl-model-area" its not as nice though as there are several different other modules  in play (values for "model" and "area").
After flattening things the build worked.

### Your Environment
Java 17 (openjdk - preview features enabled), gradle 7.3.1, linux

**Comment by jbartok** [comment]
Dupicates #16986
