### ISSUE TITLE
gradlew publishToMavenLocal  Cannot resolve placeholder 'USERPROFILE' in value '${USERPROFILE}/.m2/repository'

### ISSUE THREAD

**Issue by roebi** [gradle/gradle#1932]
### Expected Behavior

gradlew publishToMavenLocal should publish a Zip to MavenLocal. ( application Plugin )

### Current Behavior

Error Message:

:publishZipPublicationToMavenLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishZipPublicationToMavenLocal'.
> Failed to publish publication 'zip' to repository 'mavenLocal'
   > Cannot resolve placeholder 'USERPROFILE' in value '${USERPROFILE}/.m2/repository'

### Context

Can not use Gradle Wrapper with gradle-3.5-bin.zip

### Steps to Reproduce (for bugs)

I use Windows 8.1 Enterprise in a Commandline oder in a Git Bash Shell - both have the same Error.

### Workaround
in the Git Bash Shell, works:

    ./gradlew publishToMavenLocal -DUSERPROFILE=${USERPROFILE}

in the Windows Commandline works:

    gradlew.bat publishToMavenLocal -DUSERPROFILE=%USERPROFILE%

### Your Environment

I use Windows 8.1 Enterprise in a Commandline oder in a Git Bash Shell - both have the same Error.

**Comment by lacasseio** [comment]
Have you tried without `-DUSERPROFILE=...`?

**Comment by roebi** [comment]
without -DUSERPROFILE the Error Message is
Cannot resolve placeholder 'USERPROFILE' in value '${USERPROFILE}/.m2/repository'

**Comment by roebi** [comment]
Sorry @lacasseio - build scan is not possible, due restrictions.

I minimized the Build to build-minimized.gradle
Run with

    gradlew tasks -b build-minimized.gradle

Content of build-minimized.gradle

    buildscript {
      repositories {
        // https://github.com/gradle/gradle/issues/1932
        // mavenLocal() // Gradle 3.5 Cannot resolve placeholder 'USERPROFILE' in value '${USERPROFILE}/.m2/repository'
        maven { url getProperty('mavenResolveUrl') }
      }
    }

    repositories {
      // https://github.com/gradle/gradle/issues/1932
      mavenLocal() // Gradle 3.5 Cannot resolve placeholder 'USERPROFILE' in value '${USERPROFILE}/.m2/repository'
      maven { url getProperty('mavenResolveUrl') }
    }

The additional maven Repo entries are not relevant for the Bug itself, it is to show we use other Repos.
The Property mavenResolveURL is defined in gradle.properties and point to a internal Artifactory:

    mavenResolveUrl=http\://internalartifact.test.com/artifactory/repo/

Play around with enable / disable the two mavenLocal() Lines to get the Error :-)

**Comment by lacasseio** [comment]
Gradle will try to [fetch the `mavenLocal()` path from various location](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/mvnsettings/DefaultLocalMavenRepositoryLocator.java#L43-L70). Given your exception is coming from [this code](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/mvnsettings/DefaultLocalMavenRepositoryLocator.java#L72-L85), it lead me to believe you have a `settings.xml` file laying around. Gradle will consume this file accordingly. I suggest you either remove that file if you aren't working with Maven, change `${USERPROFILE}/.m2/repository` to `${env.USERPROFILE}/.m2/repository` in `settings.xml` or add `sysprops.USERPROFILE=C:\Users\<username>` to your `gradle.properties` inside `%USERPROFILE%\.gradle`. For more information on configuring the Maven local path, see [this thread on the user forum](https://discuss.gradle.org/t/override-location-of-the-local-maven-repo/7511).

In the future, consider asking questions on the [user forum first](https://discuss.gradle.org/).

**Comment by roebi** [comment]
@lacasseio you're right - in my settings.xml in my userhome in .m2 directory I had the Line

    <localRepository>${USERPROFILE}/.m2/repository</localRepository>

this worked in Gradle Version prior 3.5 but NOT work in Gradle Version 3.5

I removed the File settings.xml - this work with Gradle 3.5

Thank you for the Hint.

---

For documentation I tested in Windows 8.1 Enterprise in a Commandline
Various Lines, where ALL work :-)

    

    // Your recommendation
    <localRepository>${env.USERPROFILE}/.m2/repository</localRepository>

    // From Apache Maven https://maven.apache.org/settings.html
    <localRepository>${user.home}/.m2/repository</localRepository>

    // My trying - Linux Variable without {}
    <localRepository>$USERPROFILE/.m2/repository</localRepository>

    // My trying - Windows Variable
    <localRepository>%USERPROFILE%/.m2/repository</localRepository>
    
I guess the change come from

https://github.com/gradle/gradle/blame/v3.5.0/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/mvnsettings/DefaultLocalMavenRepositoryLocator.java#L67

and the Combination of my possible wrong Maven Setting in settings.xml localRepository .
