### ISSUE TITLE
Problems reading data from Binary store in /private/var/folders/6n/5bjtch856nj5rkch9t2dnqzc0000gn/T/gradle1030692378674898310.bin offset 45585202 exists? true

### ISSUE THREAD

**Issue by f2tt** [gradle/gradle#19326]
### Expected Behavior
gradle should work with multiple projects, Run normally on Android studio terminal.

#### The operating environment is as follows:

- Mac big sur 11.6.2
- Android  studio 4.1.1
- gradle 6.5
-  classpath "com.android.tools.build:gradle:4.0.0"

 When trying to do anything (except CLEAN) i get this error:
Could not determine the dependencies of task ':module_question:compileEnv_testOfficialReleaseUnitTestKotlin'.
> Could not resolve all dependencies for configuration ':module_question:env_testOfficialReleaseUnitTestRuntimeClasspath'.
   > Problems reading data from Binary store in /private/var/folders/6n/5bjtch856nj5rkch9t2dnqzc0000gn/T/gradle1030692378674898310.bin offset 45585202 exists? true

### Context
trying to build my android projects using gradle

I have removed my ~/.gradle folder, Also deleted the .idea and .gradle files in the app. all the .gradle folders in the enclosing folder all to no avail. I deleted the running gradle daemons.

**Comment by ljacomet** [comment]
This issue usually comes from bugs in the dependency resolution engine. Without a reproducer they are very hard to track down.
Gradle 6.5 is also not the most recent version and a number of fixes have been done in that area.

Could you test with Gradle 7.3.3 ideally? Or with Gradle 6.9.2?

If none of these versions work, could you try extracting a reproducer?

Note also that #19260 will resolve two such issues as well and should be released with 7.4

**Comment by f2tt** [comment]
I tested for Gradle 6.9.2 is ok

**Comment by ljacomet** [comment]
Thanks for following up, closing as fixed in 6.9.2 / 7.3.3
