### ISSUE TITLE
Build launched via TAPI ignores logger level settings of target build

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#19340]
When a client launches a build using Tooling API, a logging level option in `gradle.properties` file is ignored and the build is configured with `LIFECYCLE` logging level output.

### Expected Behavior

Logging level in `gradle.properties` of target build is respected.

### Current Behavior

the build is configured with "LIFECYCLE" logging level output.

### Context

Users have problems starting sync or build with debug level in IJ IDEA 
https://youtrack.jetbrains.com/issue/IDEA-191119
https://youtrack.jetbrains.com/issue/IDEA-197187

### Steps to Reproduce 
see attached archive. Execute test `my.example.app.AppTest#toolingApiCallRespectsLoggingLevel` in project `gradle-tapi-client`

[gradle-tapi-with-client.zip](https://github.com/gradle/gradle/files/7733586/gradle-tapi-with-client.zip)

**Comment by donat** [comment]
This is an artifact of the early days. The TAPI logging level is controlled with the `DefaultGradleConnector.setVerboseLogging(boolean)` method. This configures the daemon logging level here: 
https://github.com/gradle/gradle/blob/cd8e40fdfe8fb8abcc2a15fc0d78888fe6ba06a5/subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/ProviderConnection.java#L119

I'd say it's not a bug but rather a missing feature.
