### ISSUE TITLE
Wrong checksum for gradle-7.3.2-all.zip for some cloudflare regions

### ISSUE THREAD

**Issue by bayandin** [gradle/gradle#19341]
Downloading https://services.gradle.org/distributions/gradle-7.3.2-all.zip returns wrong file (sha256: `8d4b75c97c5b74fcda1b049d1e9a3ef45c0d8af4974b2d384cc26d69deb8d46b`) (for some cloudflare regions, I guess; Atlanta GA for example)

### Expected Behavior
- Checksum for https://services.gradle.org/distributions/gradle-7.3.2-all.zip should be `dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb103184582` (as per https://services.gradle.org/distributions/gradle-7.3.2-all.zip.sha256) for all regions

### Current Behavior
- Checksum is wrong `8d4b75c97c5b74fcda1b049d1e9a3ef45c0d8af4974b2d384cc26d69deb8d46b` for Atlanta GA region
- Checksum is correct `dd54e87b4d7aa8ff3c6afb0f7805aa121d4b70bca55b8c9b1b896eb103184582` for Dublin region

### Context

We're trying to update `gradle` to 7.3.2 in homebrew (https://github.com/Homebrew/homebrew-core/pull/91372) and macOS arm64 runners downloads file with the wrong checksum (arm64 runners in Atlanta GA, Intel runners in Dublin)

### Steps to Reproduce 
- Download https://services.gradle.org/distributions/gradle-7.3.2-all.zip from Atlanta GA — checksum will be wrong

### Your Environment

Build scan URL: N/A

**Comment by big-guy** [comment]
@bayandin we're looking at this

**Comment by ljacomet** [comment]
We had an issue with the release and restarted the process. Looks like some caches out there still have the first version.

Note that the following checksums are the ones for the first attempt and so are "safe":
* `8d4b75c97c5b74fcda1b049d1e9a3ef45c0d8af4974b2d384cc26d69deb8d46b` for `gradle-7.3.2-all.zip`
* `b7e08c7d95f6c5024c3ccabbb8f4845fcef0fcce11b23b3937e0265e6904d09a` for `gradle-7.3.2-bin.zip`

**Comment by big-guy** [comment]
I think the cache has been purged now.  I've checked the download from a couple of different locations, but please let us know if you're still seeing the wrong distribution.

**Comment by bayandin** [comment]
That helped, thanks!
