### ISSUE TITLE
gradle's mavenBom is invalid in allproject

### ISSUE THREAD

**Issue by hy1131468749** [gradle/gradle#19349]
```
allprojects{
    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR9"
        }
    }
}
```

Submodule project：

    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

After this configuration, the dependencies of the module project cannot download the package

**Comment by donat** [comment]
This is a problem with the Spring dependency management plugin. This has to be fixed on their side.

**Comment by hy1131468749** [comment]
If I write like this in the subproject, I can download org.springframework.cloud:spring-cloud-starter-openfeign'

`dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR9"
    

    }
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
 
}
`
But if I write dependencyManagement into the allprojet of the parent project, it cannot be downloaded .I am using gradle version 7.3
`allprojects{
    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR9"
        }
    }
}
dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
 
}
`
