### ISSUE TITLE
Weird memory issue after upgrading to Gradle 7.3.2 from Gradle 7.3.0

### ISSUE THREAD

**Issue by GianfrancoMS** [gradle/gradle#19371]
### Expected Behavior

Compilation finishes without warning or errors.

### Current Behavior

The VM is generating a heap dump.

### Context

We just updated to Gradle 7.3.2 from Gradle 7.3.0 and we are presenting weird memory issues. Our project is a big Android application with many modules and a lot of code; however, it has been working just fine until the update to Gradle 7.3.2.

### Steps to Reproduce 

Unfortunately, I can't share our Android repo because it is private; however, it's been working fine until we updated to Gradle 7.3.2. (We were in version 7.3.0)

It is generating a heap dump even before executing our command (`./gradlew :app:bundleDebug`), so it's really weird. And we haven't changed our CI machines configuration for a while.

[dump.txt](https://github.com/gradle/gradle/files/7748055/dump.txt)
[daemon-182.out.log](https://github.com/gradle/gradle/files/7770591/daemon-182.out.log)

### Your Environment

- Gradle 7.3.2
- OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
javac 11.0.13
- Jenkins 2.190.1
- Build Cache Node 9.11

**Comment by pgrpmichel** [comment]
Funny, we had the same issues.  We hadn't tuned our jvm for the gradle process in a while, and already knew we needed to work on the unit test memory configs.  After increasing the max heap for the unit tests and turning on parallel GC, we were fine.

**Comment by GianfrancoMS** [comment]
@pgrpmichel Would you mind sharing your `gradle.properties` file?

**Comment by pgrpmichel** [comment]
@GianfrancoMS no problem. 

Here's our jvm settings for the gradle build (build.properties):

```org.gradle.jvmargs=-Xms512M -Xmx4g -XX:MaxPermSize=1024m -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dkotlin.daemon.jvm.options="-Xmx1g" -Dfile.encoding=UTF-8```

Here's our jvm settings for the unit tests (build.gradle):

```maxHeapSize = "2g" minHeapSize = "1024m"```

**Comment by ljacomet** [comment]
Which version did you upgrade from?

With the information provided, tracking this will be quite complicated.

**Comment by GianfrancoMS** [comment]
@ljacomet I upgraded from version 7.3.0

**Comment by GianfrancoMS** [comment]
I'm attaching the demon log. At the end I can see this error: `Discarding EOFException: java.io.EOFException `
[daemon-182.out.log](https://github.com/gradle/gradle/files/7770585/daemon-182.out.log)
