### ISSUE TITLE
Docker images gradle:6.9.2-jdk11-alpine & gradle:6.9.2-jdk8 cannot be pulled

### ISSUE THREAD

**Issue by Mazgis47** [gradle/gradle#19394]
### Expected Behavior
'docker pull gradle:6.9.2-jdk11-alpine' command should pull image without the error

### Current Behavior
> docker pull gradle:6.9.2-jdk11-alpine
6.9.2-jdk11-alpine: Pulling from library/gradle
no matching manifest for linux/amd64 in the manifest list entries
> docker pull gradle:6.9.2-jdk8
6.9.2-jdk8: Pulling from library/gradle
no matching manifest for linux/amd64 in the manifest list entries

### Context
I am trying to pull by the most concrete tag and it fails. These tags announced at https://hub.docker.com/_/gradle

These tags are available and work fine:
'docker pull gradle:6.9-jdk8'
'docker pull gradle:6.9-jdk11-alpine'

### Steps to Reproduce 
Run:
docker pull gradle:6.9.2-jdk11-alpine
or
docker pull gradle:6.9.2-jdk8

### Your Environment
Mac OS Big Sur 11.6.1
Docker version 20.10.7, build f0df350

**Comment by ljacomet** [comment]
You will have to see with the contributor maintaining those images - https://github.com/keeganwitt/docker-gradle
