### ISSUE TITLE
Exclude has no effect for file in res/raw

### ISSUE THREAD

**Issue by Tinker-S** [gradle/gradle#1940]
### Expected Behavior
When I add this code to build.gradle 
    `packageOptions {
         exclude 'res/raw/config'
     }`
The generated apk should not contain the file 'config' any more.

### Current Behavior
exclude in packageOptions seems to only have effect for file in libs dir.

**Comment by bmuschko** [comment]
I am assuming this is about the Android plugin? Would you mind asking on the [Google forum](https://code.google.com/p/android/issues) about this? Google is maintaining the plugin and is much better suited to give you a qualified answer.
