### ISSUE TITLE
Documentation "Developing Custom Gradle Plugins"

### ISSUE THREAD

**Issue by matthiaskraaz** [gradle/gradle#19425]
Points for improvement regarding the instructions in https://docs.gradle.org/current/userguide/custom_plugins.html
for how to create a plugin in buildSrc.

1. Imagine someone following your document top to bottom: Someone
copies your example to build.gradle, modifies it match someone needs,
then tries to move it to buildSrc. Now someone has to remove from

```
class GreetingPlugin implements Plugin<Project> {
  void apply(Project project) {
...
  }
}
```

everything but ...

You are hinting at this implicitly in your example, but it would be better to make it explicit.

2. You are inconsistent with regards to the example script name
(my-plugin.gradle vs. java-library-convention.gradle)

3. "Behind the scenes" is confusing. The title implies the following are things
that happen automagically (which actually is the case). But "you need to provide a properties file"
tells the opposite.

4. In "Behind the scenes", you could go full circle and describe the automagically generated
groovy-dsl-plugins/output/adapter-src/*Plugin.java, solving the mystery why a)
you have to leave out the Plugin class declaration (see point 1 above) and b) where
the class "org.example.GreetingPlugin" in the generated properties file comes from now.

**Comment by ov7a** [comment]
Sorry for the late reply. 

The page has changed a bunch of times since the issue was opened, and the remarks listed here are obsolete.

Closing this as obsolete, feel free to open a new issue if you have issues with the documentation.

**Comment by matthiaskraaz** [comment]
The documentation in question has improved a lot, indeed. Thanks for the good work!
