### ISSUE TITLE
Identify and fix integration tests that heavily depend on console output

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1942]
### Expected Behavior

Integration tests will rely less strongly on the output of a build execution e.g. the task logging header:

```
:helloWorld
Hello World!
```

After the change of the log level it would look as such:

```
Hello World!
```

Such a test should rather assert the executed tasks if possible and relax the assertions made for the console output. This change might require switching the internal testing infrastructure to use an implementation of `org.gradle.tooling.events.ProgressListener` instead of `org.gradle.integtests.fixtures.executer.OutputScrapingExecutionResult` to capture executed tasks.

To identify problematic tests the following branch has been set up that executes integration tests with `QUIET` log level: https://github.com/gradle/gradle/tree/bm-quiet-integ-tests. A first result shows 640 failed tests. We'll need to go through all of them and touch them up accordingly with the goal in mind that the log output will change.

### Current Behavior

Integration tests rely on the scraped output of a build execution on `LIFECYCLE` log level.

### Context

The default log level is going to be changed from `LIFECYCLE` to `WARN` (https://github.com/gradle/gradle/issues/1610). As a result less output will be available to assert on. Given this change some integration tests will fail as they might depends on the explicit output of `LIFECYCLE`. In the interim integration tests will be executed explicitly on `LIFECYCLE` log level.

**Comment by eriwen** [comment]
Let's defer this since we are not changing the default.

**Comment by bmuschko** [comment]
@eriwen We might have to touch up some test cases here and there as we are still planning to _not_ show the task headers. As a result the `OutputScrapingExecutionResult` wouldn't capture the task paths. But overall I agree. Let's not do it right now if we can avoid it.

**Comment by bmuschko** [comment]
Closing this as we reverted the change of the log level.
