### ISSUE TITLE
Execute with lifecycle log level when not attached to a terminal

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1943]
### Expected Behavior

Executing a Gradle build when not attached to a terminal or with output > redirected | piped

### Current Behavior

The default log level `LIFECYCLE` provides console output for external tools to scrape for information e.g. task executions. Most of these tools run on `console=plain`. Optimally, these tools would use the tooling API but some simply don't do that at the moment.

### Context

The default log level is going to be changed from `LIFECYCLE` to `WARN` (https://github.com/gradle/gradle/issues/1610). Tooling that used to rely on this console output previously available usually run with `console=plain` (e.g. Jenkins plugin, IDE etc.). For them to continue working as before sufficient output needs to be available.

## Test Cases

- From a terminal the build renders output on `WARN` log level.
- From a terminal the build renders output on `LIFECYCLE` log level if configured with `--console=plain`.
- From a terminal the build renders output on provided log level if command line option is provided.
- From Jenkins/IDE the build renders output on `LIFECYCLE` log level.
- From Jenkins/IDE the build renders output on `LIFECYCLE` log level if configured with `--console=plain`.
- From Jenkins/IDE the build renders output on provided log level if command line option is provided.

Setting `WARN` log level by command line option or system property is going to be ignored for this issue. In it's currently form it will render `LIFECYCLE` log level if not terminal is available.

**Comment by eriwen** [comment]
This is blocked somewhat by #1610

**Comment by bmuschko** [comment]
I don't think it's necessarily blocked. What we'd do is to just set to `LIFECYCLE`. However, we would really see a change in behavior before #1610 is merged.

**Comment by w25r** [comment]
It's blocked in that the tests will fail until #1610 is merged.  But I suppose it's not technically blocked until it is ready to merge.  Right now it's just `mustComeAfter`

**Comment by eriwen** [comment]
> From a terminal the build renders output on LIFECYCLE log level if configured with --console=plain

I'm not sure we should consider `--console plain` at all

**Comment by bmuschko** [comment]
Decided to implement it in a different way.
