### ISSUE TITLE
Throws TimeoutException during configuration (after 1 minute, Gradle Kotlin IO impl)

### ISSUE THREAD

**Issue by nomisRev** [gradle/gradle#19446]
The Gradle Kotlin DSL interenal `IO` implementation is hard-coded to throw after `1 minute`, this is causing our CI (https://github.com/arrow-kt/arrow) extremely flaky. We're currently unable to publish an artifact, since during our publish step we run 7 Gradle builds and it's so unstable that 1 out of 7 always fails cancelling all others.

### Expected Behavior

Stable build that doesn't timeout during configuration, undependent of the host.

### Current Behavior

Flaky build due to "random" `TimeoutException` depending on the performance of the host.

### Context

This is currently making our Github Action CI fail 95% of the time when trying to publish our project.
I'm looking for a solution to this problem, a workaround would be sufficient since a 1 minute default value is definitely good.

Otherwise I propose to make the value configurable through a `gradle.property` similar to `http.socketTimeout`.

### Steps to Reproduce 

It's reproducible, almost consitently on CI.
I have not been able to reproduce it locally, but I've pinpointed the problematic code.
A hard coded value to `pending?.get(1, TimeUnit.MINUTES)`, which results in `TimeoutException`.
https://github.com/gradle/gradle/blob/f361ac5305a5b5e3bece1ea587bd17144b23c71c/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/concurrent/BuildServices.kt#L61

I tried to reproduce by sleeping in a task during configuration but this didn't yield the same result.

### Your Environment

Build scan URL: https://gradle.com/s/4tb3u4vtk3zqo

**Comment by eskatos** [comment]
This was contributed by @urdak  in https://github.com/gradle/gradle/pull/21211, thanks again!
This will be in Gradle 7.6 as in _internal_ system property (subject to change).
