### ISSUE TITLE
AdoptOpenJdkRemoteBinary doesn't respect libc

### ISSUE THREAD

**Issue by BerndFarkaDyna** [gradle/gradle#19465]
AdoptOpenJdkRemoteBinary doesn't respect the libC on Linux, for example if you run you build on Alpine it should add the parameter for MUSL libC to the REST Url which would be supported by the api.adoptjdk.net

### Expected Behavior
If the build is running on Alpine Linux the correct SDK should be fetched.

### Current Behavior
The libC parameter isn't set -> defaulting to GlibC

### Context
Running a Gradle build on an Alpine Container with enabled JVM Auto Provisioning

**Comment by jbartok** [comment]
`AdoptOpenJdkRemoteBinary` will be removed in Gradle `8.0`, so getting it fixed will most likely not happen.
However, it's being replaced by [Toolchain Resolver plugins](https://docs.gradle.org/current/userguide/toolchain_plugins.html) and example of which is the [Foojay Toolchains Plugin](https://github.com/gradle/foojay-toolchains).
And there there is already an [open issue](https://github.com/gradle/foojay-toolchains/issues/5) for handling this problem, so I will be closing this one.
