### ISSUE TITLE
Could not find method dependencyResolutionManagement()

### ISSUE THREAD

**Issue by astro-yoas** [gradle/gradle#19461]
Hi I'm working on new project, build with button run and debug are fine, but when i tried to run gradle command its failing
my environment:
`arctic fox 2020.3.1 patch 4`
`https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip`
`com.android.tools.build:gradle:7.0.4`

### Expected Behavior

gradle run successfully

### Current Behavior

show error 
`> Could not find method dependencyResolutionManagement() for arguments [settings_9od9c2tr6j1qkv3kyo2nos18e$_run_closure1@22690f55] on settings 'astro-android' of type org.gradle.initialization.DefaultSettings.`

### Steps to Reproduce 

build with gradle comamnd `gradle --build`

### Your Environment

Build scan URL:

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool. You are using a beta version of Android Studio, issues like this are possible to happen.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

**Comment by CHUURISU** [comment]
find a solution? this is driving me nuts
