### ISSUE TITLE
Make component report task configurable without afterEvaluate

### ISSUE THREAD

**Issue by childnode** [gradle/gradle#1948]
changing some settings by `dependentComponents {}` in the `build.gradle` works as long they are not set in an external `reports.gradle` file that is sourced / applied

long story short: https://gitlab.com/childno.de/bugreports/gradle-multiproject-incubating-reports

### Expected Behavior
no need of a `gradle.projectsEvaluated {}` needed in the `reports.gradle`

### Current Behavior
need of a `gradle.projectsEvaluated {}` in the `reports.gradle` to wrap configuration of `dependentComponents` (and other incubating help task, too)

somehow the internal "Help" Plugin seem to be somewhere applied later on in the configuration phase

### Context
* gradle multiproject with allprojects definition
* using an external build script for organization purposes as documented in https://docs.gradle.org/current/userguide/organizing_build_logic.html#sec:configuring_using_external_script

### Steps to Reproduce (for bugs)
again: [have a look at the example project](https://gitlab.com/childno.de/bugreports/gradle-multiproject-incubating-reports)

**Comment by oehme** [comment]
This is due to these tasks being added by the rule engine and not Gradle's traditional configuration model. We are slowly deprecating the rule engine and will fix this problem as we go.
