### ISSUE TITLE
Clarify jvm_test_suite_plugin documentation

### ISSUE THREAD

**Issue by dawi** [gradle/gradle#19488]
I have a few things regarding the `jvm_test_suite_plugin` [documentation](https://docs.gradle.org/7.3.3/userguide/jvm_test_suite_plugin.html). 

First I wanted to ask this on stackoverflow, but then I thought that it might be worth to update the docs. So here we go:

1. It is not clear to me which framework is used per default for new test suites.
The documentation only mentions that JUnit4 is used in the built-in test suite for backwards compatibility reasons.
It seems that `useJUnitJupiter()` is the default for custom test suits, but it is not stated in the docs. 

2. It is not clear to me what happens if `useJUnitJupiter()` is used. For example if I have already configured a specific junit jupiter version via `spring-boot-dependencies` and `spring-boot-starter-test`, which version will then be used? Or in other words, how can I let gradle use the libraries that are already on the test classpath.

3. Is it ok to mix both kind of configuration? Or does it have any disadvantages?
E.g. I liked the possibility to configure common parameters for all test tasks in one place.

```kotlin
testing {
    suites {
    
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
        }

        val integrationTest by registering(JvmTestSuite::class) { 
            useJUnitJupiter()
            dependencies {
                implementation(project) 
            }
        }
        
        val webMvcTest by registering(JvmTestSuite::class) { 
            useJUnitJupiter()
            dependencies {
                implementation(project) 
            }
        }
    }
}

tasks.withType<Test> {

    useJUnitPlatform()

    filter.isFailOnNoMatchingTests = false

    testLogging.exceptionFormat = TestExceptionFormat.FULL
    testLogging.showStandardStreams = false
    
    systemProperties["config.directory"] = if (isGitLab) ...
}
```

4. An example of how to use test fixtures for custom test suits would be nice. 
I still have not figured out how to configure this. I expected something like this to work:

```
val integrationTest by registering(JvmTestSuite::class) { 
    dependencies {
        implementation(project)
        // implementation(testFixtures(project)) this is not working as in `DependencyHandlerScope`.
    }
}
```

Regards, Daniel

**Comment by donat** [comment]
@tresat could you please give an answer?

**Comment by dawi** [comment]
Thanks for your detailed explanation, it helped me a lot. Only this one is still not completely clear to me:

> This is incorrect, you have to explicitly call this method to use Jupiter in additional test suites.

I tried this [example](https://docs.gradle.org/7.3.3/userguide/jvm_test_suite_plugin.html#declare_an_additional_test_suite) from the docs with Gradle 7.3.3. and it seems that Jupiter is used as default for additional test suits, so I don't have to explicitly call this method. Regarding the build in test suite, everything behaves as stated in the docs. There I have to add `useJUnitJupiter()`. 

Did I understand correctly that after #19471 the default is Jupiter also for the default test suite?

Anyway, to be on the safe side, I will add `useJUnitJupiter()` to all test suites, as long as it is not the default everywhere.

Regarding the test fixtures, I am currently using the following workaround:

```
dependencies {
    add("webMvcTestImplementation", testFixtures(project))
    add("integrationTestImplementation", testFixtures(project))
}
```

**Comment by tresat** [comment]
That workaound should give you the same behavior.  Good luck.
