### ISSUE TITLE
Bug with test in integrationTest(JvmTestSuite) - class file not found (failure to compile).

### ISSUE THREAD

**Issue by vab2048** [gradle/gradle#19497]
### Expected Behavior

Test should not fail to compile.

### Current Behavior

Test in the 'test' suite is working fine.

Exact same test in the 'integrationTest' suite fails to compile.

### Steps to Reproduce 

See https://github.com/vab2048/gradle-testsuite-bug-demo for demo and steps to reproduce.

**Comment by tresat** [comment]
You need to add the `'org.springframework.boot:spring-boot-starter-web'` dependency to the `integrationTestImplementation` configuration, as it contains `org.springframework.http.MediaType`.

You can do this either in the same way you've added the other spring deps for integration testing:

```
    integrationTestImplementation platform("org.springframework.boot:spring-boot-dependencies:2.6.2")
    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-test'
    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-web'
```

or directly to the suite, like this:

```
    integrationTest(JvmTestSuite) {
        dependencies
               implementation project 
               implementation 'org.springframework.boot:spring-boot-starter-web'
        }
    }
```

**Comment by vab2048** [comment]
Can I ask why don't need to add it for the normal 'test' suite but it needs to be added to the 'integrationTest' one?

**Comment by tresat** [comment]
So what you're running into here is the difference between the `api` and `implementation` configurations.  For a project with the [`java-library` plugin applied](https://docs.gradle.org/current/userguide/java_library_plugin.html#header), both will be available.  The `java` plugin [has been superseded](https://docs.gradle.org/current/userguide/java_plugin.html) by either the `java-library` or `application`.

A dependency in the `api` configuration will be transitively exported to the project's consumers (which your `integrationTest` suite is) for use at compilation time.  Those in `implementation` will only be made available at runtime.

So, as visible when running a Build Scan:

![Screen Shot 2022-01-06 at 4 55 49 PM](https://user-images.githubusercontent.com/44197/148457775-a6471a78-4956-461f-bad7-53d353a91b28.png)

You get a project dependency on your integration suite's test compile and runtime classpaths, but the transitive deps which you added via `implementation` are only transitively present on the test runtime classpath.  The `integrationTest` task would run fine, it just won't compile.

If you change your build file to:
```
plugins {
    id 'org.springframework.boot' version '2.6.2'
    id 'java-library'
}

//...
dependencies {
    implementation platform("org.springframework.boot:spring-boot-dependencies:2.6.2")
    api 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    integrationTestImplementation platform("org.springframework.boot:spring-boot-dependencies:2.6.2")
    integrationTestImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

You get a different dependency graph:

![Screen Shot 2022-01-06 at 5 05 34 PM](https://user-images.githubusercontent.com/44197/148458839-f3258a0d-167a-4260-ad80-01d2b19baca3.png)

With the `spring-boot-starter-web` transitively available for your integration tests to compile against.

For the case of running the default/unit tests with your original setup, `implementation` is no longer a transitive dependency, `testImplementation` extends it and everything added to it is available directly when compiling the unit tests:

![Screen Shot 2022-01-06 at 5 07 22 PM](https://user-images.githubusercontent.com/44197/148459186-15c90287-5cc1-4de7-8ac8-27eaa1409058.png)

Please let me know if you have any further questions, I'm going to close this issue now as this appears to be working as intended.

**Comment by vab2048** [comment]
Thank you @tresat for the great explanation.

I guess I have two further questions:
1. How can I have a test suite (say, it is called `integrationTest`) defined in the new `suites` block which behaves in the exact same way as the default `test` suite (having it extend instead)?
2. The `java` plugin being superseded is news to me. Especially since currently, the Gradle template used by start.spring.io still uses it. What would be the correct plugin to use for a spring boot application? `java-library` or `application`? I'm assuming the latter but wanted to confirm.

**Comment by dawi** [comment]
@tresat I ran into exact the same issue and I am also interested in an answer to @vab2048 first question.

I am currently migrating a larger codebase to use test suites and didn't expect that I have to adjust the test dependencies in certain places. I can understand that implementation dependencies should not leak into the test classpath, but this shouldn't it be true for the default test suite as well? Or is it for backward compatibility reasons?

At least it would be good to mention this different behavior in the docs.

**Comment by tresat** [comment]
> How can I have a test suite (say, it is called integrationTest) defined in the new suites block which behaves in the exact same way as the default test suite (having it extend instead)?

You could always do this:

`configurations.integrationTestImplementation.extendsFrom configurations.implementation`

> The java plugin being superseded is news to me. 

This change is from 2019.  I think there are many projects which haven't migrated away yet.  The recommendation for new projects is definitely *not* to use the plain Java Plugin, however, in favor of one of these more specific ones.

> What would be the correct plugin to use for a spring boot application? 

I'm not a Spring expert, but if the project represents something you expect to run directly, application would usually be correct.

**Comment by tresat** [comment]
> I can understand that implementation dependencies should not leak into the test classpath, but this shouldn't it be true for the default test suite as well? Or is it for backward compatibility reasons?

Yep, we wanted to ensure backwards compatibility with the default test task.

> At least it would be good to mention this different behavior in the docs.

It's [already there](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#declare_an_additional_test_suite):

"By convention, only the built-in test suite will automatically have a dependency on the production code of the project."

But I agree this could be made clearer.

**Comment by dawi** [comment]
> It's already there:
> 
> "By convention, only the built-in test suite will automatically have a dependency on the production code of the project."

@tresat Ahhh, ok. My interpretation of that sentence was, that custom test suits have no dependency to the project whatsoever and therefore `implementation(project)` has to be added. My expectation was, that after adding this configuration the custom test suits would behave exactly the same as the standard one (extend api and implementation configuration). But I understand that the current behavior (extending only api) is the correct one in the long run.

Thanks for your clarification. :)

**Comment by vab2048** [comment]
@dawi 
> My expectation was, that after adding this configuration the custom test suits would behave exactly the same as the standard one.

This was also my reading of the documentation and the actual desired behaviour from me, but thankfully @tresat has cleared up my misunderstanding.

**Comment by vab2048** [comment]
@tresat 

> You could always do this:
> `configurations.integrationTestImplementation.extendsFrom configurations.implementation`

So, I changed it to:

```groovy
testing {
    suites {
        // Add an additional 'integrationTest' source set.
        integrationTest(JvmTestSuite) {}
    }
}

configurations.integrationTestImplementation.extendsFrom configurations.implementation

```

And it works, thanks! But it seems slightly off in that I need to add the extra bit outside of the testing block (which I would ideally like to be self contained).

Is it possible to amend/augment the testing block so that it initialises the JvmTestSuite just so it works like the 'test' source set? If not, do you think adding that toggling functionality is worth a feature request?

**Comment by tresat** [comment]
I don't think we'd be invested in adding a toggle for that, since the only reason the default test suite works differently is for back compatibility. 

You could always add this extends behavior in a convention plugin applied across your whole build.  That would keep it out of each project's buildscript.

**Comment by vab2048** [comment]
Thanks @tresat for being patient and answering all our questions. 

Hopefully the feedback from me and @dawi has convinced you guys over at Gradle some more clarity is needed in the documentation - but that is for a separate documentation related issue. 

I will close this issue since the reported 'bug' is clearly not a bug at all but intended behaviour.
