### ISSUE TITLE
Extend `PropertyReportTask` to allow specifying which property to query

### ISSUE THREAD

**Issue by jamietanna** [gradle/gradle#19493]
### Expected Behavior

It would be ideal to be able to query specific project properties from Gradle, so we can perform checks like the version of the project, such as:

```sh
./gradlew properties --console=plain -q -Dproperty=version
7.3.0-SNAPSHOT
```

### Current Behavior

All properties are listed, which requires either writing a custom task, or using a [shell pipeline such as](https://stackoverflow.com/questions/24936781/gradle-plugin-project-version-number#comment95929927_48616954):

```sh
./gradlew properties --console=plain -q | grep "^version:" | awk '{printf $2}'
7.3.0-SNAPSHOT
```

Because by default all properties are shown, and requires parsing:

<details>

<summary>Example output from <code>./gradlew properties --console=plain -q</code></summary>

```
./gradlew properties --console=plain -q
------------------------------------------------------------
Root project 'reporting-plugin' - Cucumber reporting plug-in
------------------------------------------------------------

allDeps: ...
allprojects: ...
ant: ...
antBuilderFactory: ...
archivesBaseName: ...
artifacts: ...
asDynamicObject: ...
autoTargetJvmDisabled: ...
base: ...
baseClassLoaderScope: ...
buildDir: ...
buildFile: ...
buildPath: ...
buildScriptSource: ...
buildscript: ...
childProjects: ...
class: ...
classLoaderScope: ...
clean: ...
compileJava: ...
compileTestJava: ...
components: ...
configurationActions: ...
configurationTargetIdentifier: ...
configurations: ...
convention: ...
crossProjectModelAccess: ...
defaultArtifacts: ...
defaultTasks: ...
deferredProjectConfiguration: ...
dependencies: ...
dependencyLocking: ...
dependencyMetaDataProvider: ...
depth: ...
description: ...
detachedState: ...
displayName: ...
distsDirName: ...
distsDirectory: ...
docsDir: ...
docsDirName: ...
ext: ...
extensions: ...
fileOperations: ...
fileResolver: ...
generateMetadataFileForMavenJavaPublication: ...
generatePomFileForMavenJavaPublication: ...
gradle: ...
group: ...
idea: ...
identityPath: ...
inheritedScope: ...
internalStatus: ...
jacoco: ...
jacocoTestReport: ...
java: ...
javaToolchains: ...
layout: ...
libsDirName: ...
libsDirectory: ...
listenerBuildOperationDecorator: ...
logger: ...
logging: ...
model: ...
modelIdentityDisplayName: ...
modelRegistry: ...
name: ...
nexusPublishing: ...
normalization: ...
objects: ...
org.gradle.parallel: ...
owner: ...
parent: ...
parentIdentifier: ...
path: ...
pluginContext: ...
pluginManager: ...
plugins: ...
processOperations: ...
project: ...
projectConfigurator: ...
projectDir: ...
projectEvaluationBroadcaster: ...
projectEvaluator: ...
projectPath: ...
properties: ...
providers: ...
publicType: ...
publishing: ...
reporting: ...
reportsDir: ...
repositories: ...
resources: ...
rootDir: ...
rootProject: ...
rootScript: ...
script: ...
scriptHandlerFactory: ...
scriptPluginFactory: ...
serviceRegistryFactory: ...
services: ...
signMavenJavaPublication: ...
signing: ...
signing.gnupg.keyName: ...
signing.keyId: ...
sonarqube: ...
sonatypePassword: ...
sonatypeUsername: ...
sourceCompatibility: ...
sourceSets: ...
spotless: ...
spotlessApply: ...
standardOutputCapture: ...
state: ...
status: ...
subprojects: ...
systemProp.sonar.host.url: ...
systemProp.sonar.login: ...
targetCompatibility: ...
taskThatOwnsThisObject: ...
tasks: ...
test: ...
testReportDir: ...
testReportDirName: ...
testResultsDir: ...
testResultsDirName: ...
testing: ...
version: 7.3.0-SNAPSHOT
```	

</details>

### Context

I've used this before to track version numbers when running CI/CD, and am planning on using this to allow GitLab CI to not build a branch if it's not a SNAPSHOT version.

**Comment by donat** [comment]
Your proposal makes sense, although we don't have the capacity for the implementation. Would you be interested in providing a pull request?

Regarding the design, I think a task option would be better than a JVM property. The proposed functionality should work like this:

    ./gradlew properties --property version

**Comment by jamietanna** [comment]
Sounds like a plan - just to confirm (and to leave breadcrumbs for myself when implementing) this would be using an `@Option` that would need to set a field in the class ([example from the docs](https://docs.gradle.org/current/userguide/custom_tasks.html#example_declaring_a_command_line_option) that would then be queried?

**Comment by donat** [comment]
Exactly.

**Comment by jamietanna** [comment]
Thanks! I've raised #19500 as a WIP PR because I'm seeing the return value of the task to be:

```
------------------------------------------------------------
Root project 'o0raw'
------------------------------------------------------------

group: org.gradle.api
```

Whereas I'd prefer it to be:

```
org.gradle.api
```

Any thoughts as to whether this is something we'd be able to control, or whether this is how we should leave it?

**Comment by donat** [comment]
> Any thoughts as to whether this is something we'd be able to control, or whether this is how we should leave it?

I'd keep it simple for the time being and use the same renderer as before. We should discuss this separately.
