### ISSUE TITLE
Running gradle wrapper on windows puts the wrapper in .gradle/ instead of gradle/

### ISSUE THREAD

**Issue by wheelerlaw** [gradle/gradle#1950]
Running gradle 3.5. If I run `gradle wrapper` in a project without gradle or an empty directory, it creates `gradle`, `gradle.bat`. as expected, however it puts the wrapper jar and properties file in `.gradle/` instead of `gradle/`.

**Comment by bmuschko** [comment]
That's not what I see. Can you elaborate? How did you install Gradle?

```
$ mkdir wrapper
$ cd wrapper
$ gradle -v

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.12.4 x86_64

$ gradle wrapper
$ tree
.
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
└── gradlew.bat

2 directories, 4 files
```

**Comment by wheelerlaw** [comment]
@bmuschko Installed dy downloading the [binary](https://services.gradle.org/distributions/gradle-3.5-bin.zip), unzipping it into a folder, and adding the `bin` folder to my `PATH` environment variable. I then create a new folder, and inside it run `gradle wrapper`. This is the output:
![image](https://cloud.githubusercontent.com/assets/3081566/25808148/2d249b6a-33d7-11e7-8d9a-d5a82867febc.png)

The `.gradle\` directory contains the correct contents, but it has a dot prepending the name, which AFAIK it shouldn't.

**Comment by bmuschko** [comment]
@wheelerlaw The `.gradle` is unrelated to the `gradle` and serves a different purpose. `.gradle` hold task input and output caches so it's totally fine that it is there. I just wondering about where your `gradle` directory is.

**Comment by wheelerlaw** [comment]
The `gradle` directory is not being created. What is supposed to end up in `gradle` is instead ending up inside `.gradle`:

![image](https://cloud.githubusercontent.com/assets/3081566/25809077/fe742ad0-33d9-11e7-949b-dc322ad283cf.png)

**Comment by wheelerlaw** [comment]
Note: this is seemingly only happening in Windows. I can't replicate the issue on OS X or Linux.

**Comment by lacasseio** [comment]
I just tried with a Windows 10 VM and I get the right result:
```
> mkdir wrapper
> cd wrapper
> gradle -v

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Windows 10 10.0 amd64

> gradle wrapper
> tree
Folder PATH listing
Volume serial number is 0000008D 5810:6436
C:.
├───.gradle
│   ├───3.5
│   │   ├───file-changes
│   │   └───taskHistory
│   └───buildOutputCleanup
└───gradle
    └───wrapper

> dir gradle\wrapper
 Volume in drive C has no label.
 Volume Serial Number is 5810-6436

 Directory of C:\Users\vmadmin\Downloads\wrapper\gradle\wrapper

05/08/2017  07:56 AM    <DIR>          .
05/08/2017  07:56 AM    <DIR>          ..
05/08/2017  07:56 AM            54,783 gradle-wrapper.jar
05/08/2017  07:56 AM               236 gradle-wrapper.properties
               2 File(s)         55,019 bytes
               2 Dir(s)  62,877,999,104 bytes free
```

@wheelerlaw Could you give us more information on the system you are seeing this bug?
* Windows version? Windows 7, 8, 8.1, 10, etc.
* The language of Windows? English, French, etc.
* The Region & Language configuration? What keyboard layout/language are you using (believe it or not this was a problem for a member of a previous team I was in)?
* File system format? NTFS or FAT?
* Any unconventional modification you may have done from the baseline installation? We are looking at modification such as installed drivers that may interact with the file system driver stack. Anti-virus and anti-malware usually mess with the file system driver stack. Which one have you installed?
* Command line emulation? cmd.exe, Cygwin or another one?

If you don't feel comfortable sharing that information on the issue, don't hesitate to send me a private message.

**Comment by lacasseio** [comment]
@wheelerlaw Could you also try with previous versions such as Gradle 3.4, 3.3 and 3.2 to see if it's a regression on your system or if it's a consistent behavior.

**Comment by lacasseio** [comment]
@wheelerlaw One last thing to check, do you have any code that may be modifying the behavior of the `Wrapper` task inside a `build.gradle` script or similar. The code would look something like this:
```
tasks.withType(Wrapper) {
    doLast {
        println jarFile
    }
}
```

It could also be an init script added to your `%USERPROFILE%\.gradle\init.d\` folder some time ago.

**Comment by wheelerlaw** [comment]
System information: 
- Windows 7
- English
- Region and Language formats: [1], Keyboard configuration: English (US) [2]
- Filesystem: NTFS
- Anti-virus: McAfee VirusScan Enterprise + AntiSpyware Enterprise 8.8.0
- I've tried in cmder, git bash, and cmd.exe and all produced the same result. 

Result of `tree` from using 2.14.1:
```
C:\Users\wlaw\Downloads\gradle-2.14.1\bin>tree
Folder PATH listing for volume OSDisk
Volume serial number is 02DB-BA55
C:.
└───.gradle
    ├───2.14.1
    │   └───taskArtifacts
    └───wrapper
```
Going to try with 3.4 next. Then I'll boot into safemode to see if the virus scanner is messing with things.

**Comment by wheelerlaw** [comment]
Just noted some interesting behavior here. I just tried with 3.4.1 and it seems as if it is trying to write to `gradle` instead of `.gradle`, since I ran `.\gradle.bat wrapper` from within the `bin` directory and it complained about `gradle` already existing, as a file. However, if I create a subdirectory, and run the `..\gradle.bat wrapper` from within it, it does not write to `gradle`:

**Comment by wheelerlaw** [comment]
Okay, so safemode didn't work for some reason, but I ended upgrading to W10 anyways, and the issue did not persist, so I'm going to call it a day on this issue.

**Comment by lacasseio** [comment]
The behavior you experienced is really a one of a kind scenario. Thanks for following up with this.
