### ISSUE TITLE
FAILURE: Build failed with an exception，org.codehaus.groovy.runtime.StringGroovyMethods.capitalize(Ljava/lang/String;)Ljava/lang/String;

### ISSUE THREAD

**Issue by wickywe** [gradle/gradle#19503]
---
cc: @gradle/execution

PS:情况说明，就使用了gradle-wrapper，导入项目刷新就报错，还没到Build那一步。
环境： jdk -> 1.8.0_152version

Type-safe dependency accessors is an incubating feature.
> Task :wrapper

BUILD SUCCESSFUL in 326ms
1 actionable task: 1 executed
Type-safe dependency accessors is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
org.codehaus.groovy.runtime.StringGroovyMethods.capitalize(Ljava/lang/String;)Ljava/lang/String;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 384ms

![image](https://user-images.githubusercontent.com/20527574/148512906-068f0001-5559-4ff3-9e18-b35a7c2355ac.png)

**Comment by Whkun** [comment]
问题解决了吗

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.
