### ISSUE TITLE
`com.gradle.plugin-publish` Unable to add new plugin to group

### ISSUE THREAD

**Issue by turansky** [gradle/gradle#19528]
Unable to add one more plugin to group `com.github.turansky.kfc`

### Steps to Reproduce
0. Existed plugins:
    * `com.github.turansky.kfc.application`
    * `com.github.turansky.kfc.library`
1. Add:
    * `com.github.turansky.kfc.react`
2. Publish all plugins
    
### Expected Behavior
2. All plugins published

### Current Behavior
2. Publish error for new plugin
```
Execution failed for task ':kfc-gradle-plugin:publishPlugins'.
> Failed to post to server.
  Server responded with:
  Group id must not start with 'gradle.plugin'
  Plugin id 'com.github.turansky.kfc.react' and group id 'gradle.plugin.com.github.turansky.kfc' must use same top level namespace, like 'gradle.plugin' or 'com.github'
```

### Context
* [KFC plugins](https://github.com/turansky/kfc-plugins)
* [Add plugin commit](https://github.com/turansky/kfc-plugins/commit/b41d920e7f12ca7780d929bcc1ec96c893c9fac1)

**Comment by ljacomet** [comment]
Hello,

We have updated the [approval rules](https://plugins.gradle.org/docs/publish-plugin#approval) for the plugin portal.
While you will be able to continue updating existing plugins, new plugins have stricter naming rules.

**Comment by vlsi** [comment]
Do you think you could improve the error message saying "please update the group id to `io.github`?"

Is there a way to "relocate" `com.github` plugin to `io.github` coordinates?
I know [Maven Relocation](https://maven.apache.org/guides/mini/guide-relocation.html) exists, however, does it work for Gradle plugins?
