### ISSUE TITLE
Support Kotlin language/api 1.7 in Kotlin DSL build scripts and plugins

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#19568]
This is a breaking change and can only be done on a major Gradle version.

----

Related

- Gradle 7.5
  - #19539
     Kept script compilation and `kotlin-dsl` plugin targeting Kotlin 1.4 language and api for backwards compatibility.

Implementation notes
  - `-Xsuppress-version-warnings` should be removed from the compiler arguments configured by the `kotlin-dsl` plugin.

**Comment by Mahoney** [comment]
If I've got a plugin as an included build will I need to wait for Gradle 8 to use kotlin 1.6, or is it only in kts files that I will need to wait for Gradle 8?

**Comment by Martmists-GH** [comment]
Plugin development could become a lot easier with the introduction of Context Receivers in Kotlin 1.6.20, is there any reason not to update to this more recent version?

**Comment by eskatos** [comment]
Gradle 7.5 will ship with Kotlin 1.6.21 but still target language/api 1/4 for backwards compatibility reasons. This can only be changed in a major version, next one being Gradle 8.0.

You can't change which language is used in build scripts but for plugins there are ways if you know what you are doing.
See https://handstandsam.com/2022/04/13/using-the-kotlin-dsl-gradle-plugin-forces-kotlin-1-4-compatibility/

**Comment by aSemy** [comment]
Since this issue was created Kotlin has released 1.7. Since Gradle major releases are much more slow than Kotlin, can this ticket be changed to target [Kotlin 1.8](https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/org/jetbrains/kotlin/jvm/org.jetbrains.kotlin.jvm.gradle.plugin/1.8.0-dev-1/)? Then maybe Gradle can catch up with Kotlin?
