### ISSUE TITLE
Support `ScalaCompile` as a cacheable task

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1956]
### Expected Behavior

Scala compilation can be cached in the [build cache](https://docs.gradle.org/current/userguide/build_cache.html).

### Current Behavior

Scala compilation is not not cached.

### Implementation details

1. We need to create a similar test to `org.gradle.groovy.compile.CachedGroovyCompileIntegrationTest`, but for Scala.
1. We need to add `@CacheableTask` to `org.gradle.api.tasks.scala.ScalaCompile`
1. We need to review `ScalaCompile`'s inputs for missing or improperly annotated properties (this can happen after the PR is accepted).
1. We need to update documentation in the build cache chapter.

**Comment by fkorotkov** [comment]
BTW @big-guy, we(Airbnb) are really interested in this feature. Let me know if we can test/help somehow.

**Comment by wolfs** [comment]
That has been fixed by #2399 and will be included in Gradle 4.1.
