### ISSUE TITLE
Can't use inline functions with inline/noinline block

### ISSUE THREAD

**Issue by NiazBikbaev** [gradle/gradle#19563]
When trying to use inline function compiled with Java 17 in buildscript it fails to compile with the following error:

```
Cannot inline bytecode built with JVM target 17 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option
```

### Expected Behavior
The code using inline functions compiled with java 17 methods should compile and run

### Current Behavior
It fails to compile

### Context
I'm developing custom plugin which provides some extension functions to `Project`

```kotlin
inline fun <reified T : Publication> Project.artifactoryPublishing(
    publicationName: String,
    noinline configuration: T.() -> Unit
) {
...
}
```
When i'm trying to use this function in other project, gradle reports error

### Steps to Reproduce 
1. Declare function which consumes inline/noinline block as an argument 
2. Compile with JVM 17
3. Try to use this function in another project

### Your Environment
1. Gradle 7.3.3
2. JVM 17
3. Kotlin 1.6.10

**Comment by ljacomet** [comment]
This is a limitation imposed by the Kotlin language and the Gradle runtime.

As indicated in the error message, Kotlin will not inline Java 17 bytecode in Java 8 bytecode. That later version comes from Gradle's own runtime.
So the answer is to make sure you setup your plugin build to target Java 8 bytecode.
