### ISSUE TITLE
jar file in src/main/resources can not be excluded from jacoco

### ISSUE THREAD

**Issue by adhamhf** [gradle/gradle#1957]
Hi,

I'm building an app that needs to have a jar file in src/main/resources.  I also want to have code coverage and fail the build if the is insufficient coverage.  Currently, I can not get this jar file excluded from the jacocoTestReport or jacocoTestCoverageVerification.  

I have attached a sample app the demonstrates this problem using the gradle-wrapper.jar.  I have places this jar in src/main/resources.  Next I run `./gradlew clean test jacocoTestReport jacocoTestCoverageVerification`.  Then I see `./build/reports/jacoco/test/html/org.gradle.cli` and `./build/reports/jacoco/test/html/org.gradle.wrapper` in the test coverage reports.  I don't want to have the gradle jar covered.

Here's how I have tired to exclude gradle from the reports.  I've tried more things but nothing seems to work.  I can exclude classes that are in src/main/java easily.  I'm wondering if excludes from src/main/resources are ignored for some reason.

```
jacocoTestCoverageVerification {
    violationRules {
        rule {excludes = ['org.gradle.*']
            limit { counter = "LINE"
                minimum = 0.90 }
        }
    }
}

jacocoTestReport {
    reports { xml.enabled false
        csv.enabled false
        html.enabled true }
    afterEvaluate {
        classDirectories = files(classDirectories.files.collect {
            fileTree(dir: it, excludes: [ 'org/gradle/**' ]) })
    }
}
```
Here's a same project.

[jacoco-resources.zip](https://github.com/gradle/gradle/files/981774/jacoco-resources.zip)

**Comment by musketyr** [comment]
I have a similar problem. We're having the JAR file in `src/main/resources` which is also analyzed and I can't figure out how to ignore it.

**Comment by piacenti** [comment]
Same problem still

**Comment by ShamanVirk** [comment]
I also had jar file in resources, following configuration for jacoco executions worked for me.

`
<excludes>
    <exclude>**/myJar.jar/**</exclude>
</excludes>
`

**Comment by piacenti** [comment]
@ShamanVirk that looks like maven
This is my hacky work around for a situation where I had a zip that contained a jar inside
task moveGradleFileOut{
    doLast {
        new File("$buildDir/resources/main/files/gradlew.zip").renameTo("$projectDir/gradlew.zip")
    }
}
task moveGradleFileIn{
    doLast {
        new File("$projectDir/gradlew.zip").renameTo("$buildDir/resources/main/files/gradlew.zip")
    }
}
jacocoTestReport.dependsOn moveGradleFileOut
jacocoTestReport.finalizedBy moveGradleFileIn

jacocoTestCoverageVerification.dependsOn moveGradleFileOut
jacocoTestCoverageVerification.finalizedBy moveGradleFileIn

**Comment by Ielay** [comment]
This solution is worked for me:
```   jacocoTestReport {
        afterEvaluate {
            classDirectories.setFrom(files(classDirectories.files.collect {
                fileTree(dir: it, exclude: [
                        '**/myJar.jar/**'
                ])
            }))
        }
```
Gradle version: `6.0.1`
The source folder of jar: `src/main/resources/.../myJar.jar`
The target folder of jar: `build/resources/main/.../myJar.jar`
