### ISSUE TITLE
Improve naming in DirectorySnapshotter for filtered snapshots

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#19571]
On #19365 there was some discussion how we should call "filtered" snapshots in `DirectorySnapshotter`: https://github.com/gradle/gradle/pull/19365#discussion_r783976888

We should follow up there and make the naming clearer.

---
cc: @gradle/execution

**Comment by lptr** [comment]
Let's do this the next time we work in that area. I expect the need to come up naturally.
