### ISSUE TITLE
Run build failed on apple silicon chips as ADOPTIUM not being avaliable

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle#19595]
### Expected Behavior
Run `./gradlew build` to build and test.

### Current Behavior
Blocked on download `ADOPTIUM` or `ADOPTOPENJDK` failures.

### Context
See square/okhttp/issues/6943.
After I bumped Gradle to 7.4-rc-1, it still not works.

### Steps to Reproduce 
See Goooler/okhttp/pull/25.

### Your Environment
MacBook Pro 14-inch with Apple M1 Pro
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)

**Comment by Goooler** [comment]
```kotlin
  configure<JavaPluginExtension> {
    toolchain {
      languageVersion.set(JavaLanguageVersion.of(11))
      vendor.set(JvmVendorSpec.ADOPTIUM)
    }
  }
```

**Comment by ljacomet** [comment]
Your toolchain request cannot be satisfied on Apple Silicon as there is no arm64 build available for Adoptium Java 11.

You will need to change your toolchain spec, there is nothing Gradle can do here.

**Comment by Goooler** [comment]
One more question, if migrate to `ADOPTIUM`, will still download JDK from `https://api.adoptopenjdk.net` instead of `https://api.adoptium.net/` automatically, is this a bug?

**Comment by ljacomet** [comment]
That is expected, see https://docs.gradle.org/7.4-rc-1/userguide/toolchains.html#sec:provisioning

**Comment by Goooler** [comment]
Use zulu with:
```kotlin
  jvmToolchain {
      languageVersion.set(JavaLanguageVersion.of(8))
      vendor.set(JvmVendorSpec.AZUL)
  }
```
but:
```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to calculate the value of task ':ktlint:compileJava' property 'javaCompiler'.
No compatible toolchains found for request filter: {languageVersion=8, vendor=AZUL, implementation=vendor-specific} (auto-detect true, auto-download true)

```

**Comment by Goooler** [comment]
Still blocking https://github.com/gradle/gradle/issues/19140.

**Comment by chylek-qr** [comment]
> Your toolchain request cannot be satisfied on Apple Silicon as there is no arm64 build available for Adoptium Java 11.
> 
> You will need to change your toolchain spec, there is nothing Gradle can do here.

So how do you set the toolchain spec to download the x86_64 build instead of aarch64? There seems to be no such option in `JavaToolchainSpec`.
