### ISSUE TITLE
incrementalScalaAnalysisFormain failed on initial project (gradle init)

### ISSUE THREAD

**Issue by tischober** [gradle/gradle#19600]
### Expected Behavior

I created with Gradle init a small scala project. Then I run ./gradlew :app:dependencies 
and I expected there no errors, because it is a initial project without any changes.
### Current Behavior

But I got errors for incrementalScalaAnalysisFormain and incrementalScalaAnalysisFortest

part of the logs:
incrementalScalaAnalysisFormain - Incremental compilation analysis files for main
+--- org.scala-lang:scala-library:2.13.1 FAILED
\--- com.google.guava:guava:30.1.1-jre FAILED

incrementalScalaAnalysisFortest - Incremental compilation analysis files for test
+--- org.scala-lang:scala-library:2.13.1 FAILED
+--- com.google.guava:guava:30.1.1-jre FAILED
+--- junit:junit:4.13.2 FAILED
+--- org.scalatest:scalatest_2.13:3.2.9 FAILED
\--- org.scalatestplus:junit-4-13_2.13:3.2.2.0 FAILED

### Steps to Reproduce 
gradle init ( for scala with Gradle config in Kotlin)
./gradlew :app:dependencies

### Your Environment

Build scan URL:

**Comment by jbartok** [comment]
Duplicates #6854
