### ISSUE TITLE
Custom test suite named unitTest conflicts with default test suite

### ISSUE THREAD

**Issue by dawi** [gradle/gradle#19603]
We have configured multiple `JvmTestSuites` to have their source roots under `src/test`. E.g.

```
src/test/unitTest
src/test/webMvcTest
src/test/integrationTest
src/test/seleniumTest
```

Instead of using the default test suite for unit tests, we have decided to add a custom unit test test suite as follows:

```
val unitTest by registering(JvmTestSuite::class) {
    sources {
        java {
            setSrcDirs(listOf("src/test/unitTest/java"))
        }
        resources {
            setSrcDirs(listOf("src/test/unitTest/resources"))
        }
    }
    dependencies {
        implementation(project)
    }
}
```

So we don't use the default test suite at all.

Now, with Gradel 7.4.0-RC1, the following error occurs:

```
Could not configure suite: 'unitTest'. Another test suite: 'test' uses the type: 'unit-test' and has already been configured in project: 'gradle-build'.
```

The obvious solution is to use the default test suite for unit tests again.
I still wanted to file this issue, because I am not sure why this kind of setup should not be supported.

And one last point: The release notes say that the IntelliJ IDEA Plugin plugin will now automatically mark all source directories used by a JVM Test Suite as test source directories within the IDE.

This does not work for our custom integrationTest test suite. Maybe this is due to the fact that we have the test under src/test/integrationTest.

**Comment by tresat** [comment]
You can continue to use a custom suite for your unit tests, but what you can't do is have 2 different test suites (the default + `unitTest`) which use the same `TestSuiteType` value.  More details of this will be exposed in DSL reference and samples for the final 7.4 docs, but the note on [Test Suite Type here](https://docs.gradle.org/7.4-rc-1/userguide/jvm_test_suite_plugin.html#sec:jvm_test_suite_configuration) is a good start.

To fix this error, since you can either set a different type on your custom suite like this:

```
val unitTest by registering(JvmTestSuite::class) {
   testType.set('custom-unit-test')
   //...
}
```

or change the (unused) default suite's type, like this: 

```
test {
    testType = 'default-unit-test'
}
```

Either of these should work.

IDEA is properly detecting the test suites for me, when set up in the same directories you have listed after fixing this type error.

If this does not work for you, please update this issue with a reproducer and re-open.  Thanks.

**Comment by dawi** [comment]
@tresat Thanks, for your response.

Regarding the naming conflict: Updating the default test suit type as you suggested solves the issue.

Regarding the issue that IntelliJ does not recognize my source folders as test sources: This issue still exists.
I have attached a screenshot and the build.gradle.kts that can be used to reproduce the issue.

<img width="380" alt="intellij project layout screenshot" src="https://user-images.githubusercontent.com/129870/150300398-5f383bbf-91f0-4a7f-adb7-ce4a0cc134c1.png">

#### build.gradle.kts

```
plugins {
    `java-library`
    `jvm-test-suite`
    idea
}

repositories {
    mavenCentral()
}

testing {
    suites {

        val unitTest by registering(JvmTestSuite::class) {
            sources {
                java {
                    setSrcDirs(listOf("src/test/unitTest/java"))
                }
                resources {
                    setSrcDirs(listOf("src/test/unitTest/resources"))
                }
            }
            dependencies {
                implementation(project)
            }
        }

        val integrationTest by registering(JvmTestSuite::class) {
            sources {
                java {
                    setSrcDirs(listOf("src/test/integrationTest/java"))
                }
                resources {
                    setSrcDirs(listOf("src/test/integrationTest/resources"))
                }
            }
            dependencies {
                implementation(project)
            }
        }

        val test by getting(JvmTestSuite::class) {
            testType.set("default-unit-test")
        }
    }
}
```

If I configure the test sources manually like below, IntelliJ recognizes them correctly. But `testSourceDirs` are now deprecated and I couldn't figure out yet, how to configure the proposed alternative `testSources` via Kotlin DSL. The examples for are only written in Groovy. Or maybe it is the same issue there, and I had configured them correctly and IntelliJ just does not configure the test sources accordingly.

```
idea {
    module {
        testSourceDirs = setOf(
            file("src/test/unitTest/java"),
            file("src/test/integrationTest/java")
        )
        testResourceDirs = setOf(
            file("src/test/unitTest/resources"),
            file("src/test/integrationTest/resources")
        )
    }
}
```

**Comment by tresat** [comment]
Taking another look.

**Comment by dawi** [comment]
@tresat  I have just opened another ticket for this (https://github.com/gradle/gradle/issues/19645), because I could not reopen the issue as you said.
