### ISSUE TITLE
TargetJvmVersion attribute should be set without locking configurations against further mutation

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#19606]
Continuation of work on https://github.com/gradle/gradle/pull/19561.

Possibly replace with a provider based on the code in `configureDefaultTargetPlatform()` in `DefaultJvmPluginServices` which calculates this value whenever attributes are requested.

This would allow the outgoingVariants and resolvableConfigurations reports to run without locking against further mutation, which is desirable.

**Comment by DPUkyle** [comment]
@lptr another great example where API evolution could come in handy.

**Comment by lptr** [comment]
Thanks, added to the list here: https://docs.google.com/document/d/1T9iHrnfqMaS89qNs8TEngl8PVtsjmaIfJoDXHlYahvI/edit#heading=h.oh977tuyb4rs

**Comment by tresat** [comment]
After some investigation, this cannot be done due to https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaPluginExtension.html#org.gradle.api.plugins.JavaPluginExtension:disableAutoTargetJvm().  

This attribute should only be added if that flag is not set.  So adding the attribute automatically as part of creating the configuration is too early - this is why the code currently waits until the configuration is locked using a `beforeLocking` callback to do this.

Investigating this led to a couple of interesting findings:

1) The `DefaultMutableAttributeContainer` class doesn't handle adding lazy and eager values for the same `Attribute` well.  The desired behavior should be "last update wins" regardless of which update used lazy vs. eager values.
2) The `toString` call which modifies the container class makes debugging particularly difficult.

This Issue is being closed.  See the new linked issue for work to address those problems.

**Comment by tresat** [comment]
Linked issue: #19753
