### ISSUE TITLE
Remove https://keys.fedoraproject.org from key servers

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#19605]
From: [https://fedoraproject.org/wiki/Infrastructure/graveyard](https://fedoraproject.org/wiki/Infrastructure/graveyard):
```
- Keys. keys.fedoraproject.org was for looking up and adding GPG key data for users. 
  However due to problems with the SKS keysystem being hacked, we ended service.
  For lookups, users should look at other services like keys.openpgp.org
```

So we should remove it.

**Comment by ljacomet** [comment]
Given the way you discovered this, I wonder if we should not add a blacklist system as well.
That is stop hitting a server after it fails to answer for a given number of times.

**Comment by asodja** [comment]
That would make sense. For a quick fix, I guess this is good enough. But maybe we could improve it additionally.
