### ISSUE TITLE
jacoco-report-aggregation does not handle dependencies without version

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#19604]
### Expected Behavior
[jacoco-report-aggregation](https://docs.gradle.org/7.4-rc-1/release-notes.html#generate-a-single-jacoco-code-coverage-from-multiple-projects) works when one of project declares a dependency without a version, thanks to importing a platform (BOM).

### Current Behavior
The new plugin stops working when you add a dependency without a version. Code compiles, tests run, standard jacocoTestReport works, but `testCodeCoverageReport` task crashes.

### Context
I use Spring Boot BOM to omit versions for some dependencies.

### Steps to Reproduce 
See the GitHub action result in
https://github.com/pkubowicz/gradle-jacoco-aggregation-platform-bug

### Your Environment
Gradle 7.4-rc-1
Build scan URL: https://scans.gradle.com/s/3vp6wbtg7ps2a

**Comment by DPUkyle** [comment]
@pkubowicz thank you for reporting - we are testing a fix now.
