### ISSUE TITLE
fail to apply custom plugin in buildSrc to settings.gradle

### ISSUE THREAD

**Issue by liao123abc** [gradle/gradle#19601]
### Expected Behavior
apply custom plugin in buildSrc to settings.gradle should work

### Current Behavior
- custom plugin in buildSrc module
    - in kotlin or groovy
- when apply to settings.gradle file , it fail in high version gradle
    - gradle 5.4.1 works
    - gradle 7.0.2 fail
        - I try gradle 6.1.1, always fail

> fail in gradle 7.0.2
```
A problem occurred evaluating settings 'gradle702'.
> Plugin with id 'init-in-groovy' not found.
```

### Context
custom plugin development,  I tried to develop a plugin which should apply on the init phase.

```kotlin
class RootPluginKotlin: Plugin<Settings> {

    override fun apply(settings: Settings) {
        println("yes, I'm working on kotlin")
    }
}
```

```groovy
class RootPluginInGroovy implements Plugin<Settings> {

    @Override
    void apply(Settings settings) {
        println("yes, I'm working on Groovy")
    }
}

```

### Steps to Reproduce 

- Clone the [sample project](https://github.com/liao123abc/gradle702)
- run any tasks

> note that [it works on gradle 5.x.x](https://github.com/liao123abc/gradle541.git)

### Your Environment

[it works on gradle 5.x.x](https://github.com/liao123abc/gradle541.git)

> success

```
$ ./gradlew -v
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_302 (Amazon.com Inc. 25.302-b08)
OS:           Mac OS X 12.1 x86_64
```

[fail in higher versions](https://github.com/liao123abc/gradle702.git)

> fail 

```
$ ./gradlew -v
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_302 (Amazon.com Inc. 25.302-b08)
OS:           Mac OS X 12.1 x86_64

```

**Comment by jbartok** [comment]
Pls. see (this is a breaking change in 6.0): https://docs.gradle.org/current/userguide/upgrading_version_5.html#classes_from_buildsrc_are_no_longer_visible_to_settings_scripts
