### ISSUE TITLE
Does `project(path: ':xxx', configuration: 'testArtifacts')` deprecated in 7.X

### ISSUE THREAD

**Issue by Shoothzj** [gradle/gradle#19615]
Does `project(path: ':xxx', configuration: 'testArtifacts')` deprecated in 7.X ?
I have searched for github issues and google, but I can't find doc related.

Any help will be greatful. Thanks :)

**Comment by ljacomet** [comment]
This is still a valid declaration even though we advise to leverage variant aware dependency management instead.
