### ISSUE TITLE
jacoco-report-aggregation should gracefully handle missing execution data

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#19634]
### Expected Behavior
When a dependency of the aggregation project is missing execution data the JaCoCo report aggregation task should not fail.

### Current Behavior
A project may have the jacoco & JVM test suite plugins applied to subprojects through usage of a conventions plugin applied to all projects, but some subprojects may not have any tests. Because there are no tests, there will be no JaCoCo test coverage generated, and the aggregation task will fail.

### Context
I'm trying to migrate from the old manual code coverage aggregation setup in a project which is closely aligned to the [existing sample](https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage.html), though with transitive dependencies disabled on `coverageDataPath` configuration.

The behaviour of the new plugin is surprising because in general Gradle gracefully handles cases like missing test sources by skipping related tasks with `NO-SOURCE`, so I would expect similar behaviour when lack of tests means no coverage data is created.

I acknowledge that changes to the build setup could work around this issue, but it means creating a separate conventions plugin for "untested" projects vs "tested" projects, which is extra overhead and makes adoption more difficult. On balance I would instead just stick with the working manual config instead of using the new plugin.

### Steps to Reproduce 
1. Download sample https://docs.gradle.org/7.4-rc-1/samples/sample_jvm_multi_project_with_code_coverage_standalone.html
2. Delete `utilities/src/test`
3. Run `gradlew :testCodeCoverageReport`
4. See failure: `Unable to read execution data file C:\path\to\sample_jvm_multi_project_with_code_coverage_standalone-kotlin-dsl\utilities\build\jacoco\test.exec`

### Your Environment
Build scan URL: N/A

**Comment by big-guy** [comment]
Thanks for reporting this @3flex - this will be fixed in the next RC (RC2).
