### ISSUE TITLE
isAllowInsecureProtocol is ignored for buildSrc

### ISSUE THREAD

**Issue by Shusek** [gradle/gradle#19644]
### Current Behavior
After upgrade to gradle 7.+ `isAllowInsecureProtocol` has stopped working properly for buildSrc module.

### Context
When gradle build `buildSrc` with insecure repositories error occured:

> A problem occurred configuring project ':buildSrc'.
> Could not resolve all dependencies for configuration ':buildSrc:classpath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven(http://myproxy/)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.3.3/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 

### Steps to Reproduce 
1) Put inside buildSrc/build.gradle.kts
```
plugins {
    id("org.gradle.kotlin.kotlin-dsl") version "2.2.0"
}

repositories {
    maven {
        setUrl("http://myproxy/")
        isAllowInsecureProtocol = true
    }
}

```
2) Build project

Error occured only with gradle 7.+, does not exist for the version 6.+.

### Your Environment
Gradle version from 7.0 to 7.3.3
Java 11
Ubuntu
Android project (but it doesn't seem like a google problem)

**Comment by ljacomet** [comment]
Trying to reproduce, your example does not compile:
```
* What went wrong:
A problem occurred evaluating project ':buildSrc'.
> Could not set unknown property 'isAllowInsecureProtocol' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.
```

And if I use `allowInsecureProtocol = true` then the build does not fail with the shared message.

Given this, I will close the issue. If you still have a problem, please provide [a full reproducer](https://github.com/gradle/gradle-issue-reproducer) illustrating the issue.

**Comment by Davadesolateness** [comment]
在gradle文件夹下的init.gradle中使用了http开头的连接，所以出现此报错，此时将http改成https即可，或者加上  maven { ArtifactRepository repo -> 
        // 判断属性是否存在，之后再设置
            if(repo.metaClass.hasProperty(repo, 'allowInsecureProtocol')){
                allowInsecureProtocol true
            }
            url REPOSITORY_URL
     }
