### ISSUE TITLE
The IntelliJ IDEA Plugin does not mark JVM Test Suite sources as test source in the IDE

### ISSUE THREAD

**Issue by dawi** [gradle/gradle#19645]
### Expected Behavior

According to the [gradle 7.4-rc-1 release notes](https://docs.gradle.org/7.4-rc-1/release-notes.html#idea-test-sources), the [IntelliJ IDEA Plugin](https://docs.gradle.org/7.4-rc-1/userguide/idea_plugin.html) should mark all source directories used by a JVM Test Suite as test source directories within the IDE.

### Current Behavior

I have created an example build file where this does not work as expected. 
All source directories are marked as "sources" (blue) instead of "tests" (green).

<img width="380" alt="intellij project layout screenshot" src="https://user-images.githubusercontent.com/129870/150300398-5f383bbf-91f0-4a7f-adb7-ce4a0cc134c1.png">

### Context

* IntelliJ IDEA 2021.3.1 (Ultimate Edition)
* Build #IU-213.6461.79, built on December 28, 2021

#### build.gradle.kts

```kotlin
plugins {
    `java-library`
    `jvm-test-suite`
    idea
}

repositories {
    mavenCentral()
}

testing {
    suites {

        val unitTest by registering(JvmTestSuite::class) {
            sources {
                java {
                    setSrcDirs(listOf("src/test/unitTest/java"))
                }
                resources {
                    setSrcDirs(listOf("src/test/unitTest/resources"))
                }
            }
            dependencies {
                implementation(project)
            }
        }

        val integrationTest by registering(JvmTestSuite::class) {
            sources {
                java {
                    setSrcDirs(listOf("src/test/integrationTest/java"))
                }
                resources {
                    setSrcDirs(listOf("src/test/integrationTest/resources"))
                }
            }
            dependencies {
                implementation(project)
            }
        }

        val test by getting(JvmTestSuite::class) {
            testType.set("default-unit-test")
        }
    }
}
```

If I configure the test sources manually like below, IntelliJ recognizes them correctly. But `testSourceDirs` are now deprecated and I couldn't figure out yet, how to configure the proposed alternative `testSources` via Kotlin DSL. The examples for are only written in Groovy. Or maybe it is the same issue there, and I had configured them correctly and IntelliJ just does not configure the test sources accordingly.

```kotlin
idea {
    module {
        testSourceDirs = setOf(
            file("src/test/unitTest/java"),
            file("src/test/integrationTest/java")
        )
        testResourceDirs = setOf(
            file("src/test/unitTest/resources"),
            file("src/test/integrationTest/resources")
        )
    }
}
```

**Comment by tresat** [comment]
So upon further investigation, whether you see the correct or incorrect highlighting depends on how you import the project into IntelliJ IDEA.

Starting from a fresh project with no IDEA-related files present.  If you generate the IDEA files _prior_ to opening the project in the IDE, by running `gradle idea` from the command line, you can see that they are correctly highlighted.  If you do not do this, and open the project in the IDE without this file existing, you will see the directories are not correctly highlighted.  Either way of importing _should_ work, but at the moment only the first does.

The work on the Gradle side to support test suite source highlighting was done here: https://github.com/gradle/gradle/pull/18790.  It is entirely concerned with ensuring that source dirs are properly marked as `isTestSource` in the `.iml` files used by IDEA to keep track of the project's structure.  This is done by the `idea` plugin and is happening correctly in the first scenario - you can open the generated `*.iml` files to confirm this.

Unfortunately, there is another plugin at work here: https://github.com/jetbrains/gradle-idea-ext-plugin which is not owned by Gradle.  This plugin has not yet been updated to work with the just released version 7.4-rc-1, so it has not been tested with these changes.

We've reached out to the maintainers of this plugin and let them know about this, they've said they'll look into it.  I'll leave this issue open for now and update it when I hear further, but this does not appear to be a Gradle problem.

**Comment by nskvortsov** [comment]
IntelliJ IDEA respects existing mechanisms of Gradle `idea` plugin:
> If I configure the test sources manually like below, IntelliJ recognizes them correctly.

Is there a reason why `idea.module.testSourceDirs` and `idea.module.testResourceDirs` do not contain JVM Test Suite information?

**Comment by dawi** [comment]
In Gradle 7.4, `idea.module.testSourceDirs` and `idea.module.testResourceDirs` are deprecated.
Therefore my guess is that they didn't see the need to add this information to an already deprecated feature.

**Comment by nskvortsov** [comment]
Thank you for the deprecation note! It is used in IntelliJ IDEA though. What should be used instead?

**Comment by dawi** [comment]
I am afraid that I cannot help any further. Maybe @tresat can.

**Comment by tresat** [comment]
The reason those two methods are deprecated is that they are backed by `Set<File>` collections, which makes it very difficult to wire up add directories in a lazy manner vs `ConfigurableFileCollection`s.  If you look at `org.gradle.plugins.ide.IdeaPlugin#configureModuleForTestSuites(Project)` you can how we use the new `getTestSources()` and `getTestResources()` methods to access the new live collections.  These methods make sure that any test suites which are configured after the `idea` plugin is applied correctly add test suites to these collections prior to them being used to generate any XML.

The `getTestXYZDirs()` methods are deprecated and have notes in the javadoc pointing users towards the new methods - please switch to using these and the test suite directories should be available in addition to any other directory values.

**Comment by dawi** [comment]
So, if I want IntelliJ IDEA to recognize my test sources as such I have the following options:

1. Generate iml files using the idea plugin.
2. Use the deprecated `testSourceDirs` until IDEA also interprets `getTestSources()`.

Now I am uncertain which one to choose. On one hand I liked the fact that we don't have iml files inside the project anymore, but on the other hand it may have advantages to still use them.

**Comment by nskvortsov** [comment]
@tresat thank you for the response! I will make sure we change the IDEA properly. We will be able to support `getTestSources()` and `getTestResources()`  in upcoming IDEA 2022.1 and maybe backport this support to IDEA 2021.3.3 bugfix release.
To keep 7.4 better compatible with earlier IDEA verions, may I suggest you take a look at opportunity to add JVM Test Suites information to already deprecated methods. E.g., as a workaround for the case of native imort (can be detected by system property `idea.sync.active`)

**Comment by tresat** [comment]
@nskvortsov - We did spend some time trying to get this working with the existing sets, but due to the order that test suites could be added and the directories configured on them, we could always find scenarios where some test directories were missed.  Also, the new collections are part of an overall effort to move towards these more capable collection types which support our lazy APIs where possible.

@dawi - Generating `.iml` files ahead of import is something we support, but definitely don't want to require.  Sounds like a fix for a future version of IDEA is on the way, if you can wait I wouldn't recommend anything.

**Comment by tresat** [comment]
@dawi We're going to be un-@Deprecating the old properties for now in the next 7.4 RC.  The plan is to go through at least one minor revision cycle so that the replacements can be promoted to stable first, prior to deprecating the methods they are replacing.  Note that even though the replacement methods are @Incubating, there is every intention to proceed down this path.  Please see the linked PR.

**Comment by nskvortsov** [comment]
JFYI
I've opened the ticket in JB tracker: [IDEA-287571](https://youtrack.jetbrains.com/issue/IDEA-287571)
After an initial investigation, it turns out that IDEA no longer applies Gradle `idea` plugin under the hood, so adding information about test suits to `IdeaModule` model would not help anyway.

I will add code to explicitly query the `testing` project extension for source sets information.

**Comment by lbenedetto** [comment]
For anyone else coming accross this thread: With Gradle 7.6, these fields are deprecated again. 
`testResourceDirs += blah` 
should be replaced with
`testSources.from(blah)`

**Comment by alexanderankin** [comment]
They're not even marked deprecated? lost about half a week due to this, solution is using the incubating property getTestSources() but _the users will never know without an `@Deprecated`_

**Comment by alexanderankin** [comment]
can confirm the annotation is back on 7.6, would have been really great if it was already there on a 7.5.x release, esp since if you use the -all distribution, you can see that there is a comment saying it will be deprecated again. gradle deprecations are a meme no less than frontend engineers re-writing their applications from scratch every year; we've already learned to love this process, but we can't kick off the usual mechanisms if we don't know something is deprecated.

/rant
