### ISSUE TITLE
DependencyReportTask not showing all dependencies

### ISSUE THREAD

**Issue by MBelniak** [gradle/gradle#19643]
### Expected Behavior
Running `gradle allDeps` in buildSrc, where allDeps is a task of type DependencyReportTask should list groovy-dateutil-3.0.9.
### Current Behavior
groovy-dateutil-3.0.9 is not listed in the log created by allDeps task.

### Context
I'm using DependencyReportTask to gather information on all thirdparty libraries that my project needs, because I need to add them to a private repository. That's because my project must be built correctly without the access to public mvn repos.
groovy-dateutil is not listed in DependencyReportTask, so I don't know my project will need it and the build fails if only the private repo is available.

### Steps to Reproduce 
Repro repo with steps: https://github.com/MBelniak/gradle-bug-repro

### Your Environment
Gradle 7.3.3, Ubuntu 16.04.7 LTS, Java openjdk-8

**Comment by MBelniak** [comment]
I noticed that groovy-dateutil comes from detachedConfiguration1 added by groovy plugin. Maybe DependencyReportTask should take detached configurations into consideration as well.

**Comment by MBelniak** [comment]
Also, pom dependencies are not printed, neither by DependencyReportTask nor `gradle <task> -q dependencies`. 
When I run `gradle compileTestGroovy` I get 
``` 
Execution failed for task ':compileTestGroovy'.
> Could not resolve all files for configuration ':testCompileClasspath'.
       // ...
       Could not find org.junit:junit-bom:5.5.2.
                       Searched in the following locations:
                       // repo urls...
```
, but then when I run `gradle compileTestGroovy -q dependencies` I don't get any info about junit-bom:5.5.2.

**Comment by ljacomet** [comment]
Hello,

This report task is not designed to do what you need for your use case. Also it cannot account for detached configurations.

You should be interested in things like #18986

**Comment by MBelniak** [comment]
Hi @ljacomet,
Yes, it looks like the PR you linked is targeting my case. I will handle POMs/BOMs in a special manner until that PR is ready and merged.
