### ISSUE TITLE
Corrupt serialized resolution result when using composing builds.

### ISSUE THREAD

**Issue by KaiyuanZhao** [gradle/gradle#19656]
### Expected Behavior

Resolve dependencies successfully when using composing builds with platform and boms.

### Current Behavior

We have some repositories using platform and boms to sync our app's dependencies. When we `includeBuild` these repositories in our app, it always says `Corrupt serialized resolution result`. However, if we remove/add some dependencies, or even remove an exclusion configuration, it will be fixed automaticlly. Gradle failed in `Gradle6.9.2/7.2/7.3.3/7.4-rc-1/7.5nightly`, but succeeded in `Gradle6.7.1/6.9.1/7.0/7.1`

### Context

It makes us impossible to build our app.

### Steps to Reproduce 

It's really hard to reproduces this issue on a small poject, our app has hundreds of dependencies.

### Your Environment

Windows/Linux/Mac
Java 11
Failed in `Gradle6.9.2/7.2/7.3.3/7.4-rc-1/7.5nightly`
Succeeded in `Gradle6.7.1/6.9.1/7.0/7.1`

### Stacktrace
Gradle6.9.2
[stack.txt](https://github.com/gradle/gradle/files/7911028/stack.txt)

@ljacomet I saw that you have fixed several similar problems recently, and I was wondering if you could help solve our problem.

**Comment by ljacomet** [comment]
Hello,

Unfortunately, tracking those without a reproducer is a really hard problem.
Any chance you can produce an anonymized version of your project with its set of dependencies?

**Comment by KaiyuanZhao** [comment]
> Hello,
> 
> Unfortunately, tracking those without a reproducer is a really hard problem. Any chance you can produce an anonymized version of your project with its set of dependencies?

Any way to send our demo to you privately? Even though I hid all the jars and aars, I still didn't want to expose other files.

**Comment by KaiyuanZhao** [comment]
@ljacomet Any updates? I submit a new issue with demo in https://github.com/gradle/gradle/issues/21057

**Comment by ov7a** [comment]
Closing this as a duplicate of 
* #21057
