### ISSUE TITLE
[Checkstyle plugin] - Gradle cannot find "configFile" location

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#1967]
### Expected Behavior
Under `3.3` and `3.4`, this plugin worked correctly by finding the `checkstyle.xml` at the `configFile`.

### Current Behavior
Under `3.5`, this plugin does not seem to find the `configFile`. See here: https://travis-ci.org/JakeWharton/butterknife/builds/230085258#L2074.

### Context
When upgrading Butterknife to Gradle 3.5, the `Checkstyle` task has trouble finding the `configFile`.

Example PR: https://github.com/JakeWharton/butterknife/pull/948

### Steps to Reproduce (for bugs)
git clone https://github.com/JakeWharton/butterknife
gradlew wrapper --gradle-version 3.5
gradlew wrapper
gradlew build

### Your Environment
Repo: https://github.com/JakeWharton/butterknife
PR: https://github.com/JakeWharton/butterknife/pull/948
Build: https://travis-ci.org/JakeWharton/butterknife/builds/230085258#L2074

### Workaround
Copy the `config` folder into the failing `java` module:
Example: https://github.com/jaredsburrows/android-gradle-java-mutli-module-template/tree/master/java-library

**Comment by bmuschko** [comment]
I think the problem you are seeing is not the fact that the `checkstyle.xml` cannot be found anymore. It's more the fact the the rules you are using are not compatible with the version of Checkstyle anymore. [Checkstyle was upgraded to a newer version with Gradle 3.5.](https://docs.gradle.org/current/release-notes.html#version-of-checkstyle-has-been-upgraded) Please see [this question on the forum](https://discuss.gradle.org/t/checkstyle-checker-cannot-be-created-with-gradle-3-5/22474) which seems to be similar. Also consider to downgrade the Checkstyle version if that's not an option.

**Comment by jaredsburrows** [comment]
@bmuschko Thanks for pointing me in the right direction. It turns out `RedundantThrows ` was removed: https://github.com/checkstyle/checkstyle/issues/473. I now updated my PR. I was confused because the error was misleading. Thanks!
