### ISSUE TITLE
Update Kotlin logo in the Gradle user Manual

### ISSUE THREAD

**Issue by KotlinIsland** [gradle/gradle#19670]
https://docs.gradle.org/current/userguide/userguide.html

Expoected:
![image](https://user-images.githubusercontent.com/213894/135964907-f4052e7d-f4a3-4d55-8049-7f4a16977af8.png)
(Except with an aqua filter)

Actual:
![image](https://user-images.githubusercontent.com/65446343/150633699-32faf262-7993-4cd0-95a1-f5b2602155b2.png)

**Comment by jbartok** [comment]
Duplicates #18532
