### ISSUE TITLE
Project dependency jar does not exist when resolving project dependency 

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#19683]
When upgrading to Gradle 7.4, the AndroidX project is getting an exception when resolving a dependency configuration that contains a project dependency.

Build scan with the failure: https://ge.androidx.dev/s/5o64irjkosg5q/failure#1

On completion of the build, the target file `/home/runner/work/androidx/androidx/out/lifecycle-playground/lifecycle-playground/lifecycle/lifecycle-common/build/libs/lifecycle-common-2.5.0-alpha01.jar` does exist.

### Steps to Reproduce 

- Clone fork of AndroidX: https://github.com/bigdaz/androidx
- `cd lifecycle`
- `./gradlew clean buildOnServer --no-configuration-cache --max-workers=2`

Note that this fails consistently with `--max-workers=2` and does not seem to fail when run with `--max-workers=8`. 
This build does not fail when executed with `Gradle 7.3.3`.

### Your Environment

Build scan URL: https://ge.androidx.dev/s/5o64irjkosg5q

**Comment by adammurdoch** [comment]
This should be fixed now via https://github.com/gradle/gradle/pull/19724
