### ISSUE TITLE
Program Crashes when I build it with Gradle and then try to use VisualVM to profile it.

### ISSUE THREAD

**Issue by Angular-Angel** [gradle/gradle#19685]
### Expected Behavior
The program should not crash and I should be able to profile it with VisualVM.

### Current Behavior
When I run my application and start profiling it with Visualvm while it's on it's menu screen, it works okay, but I get a bunch of warnings in console:

`OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Profiler Agent: Waiting for connection on port 5140 (Protocol version: 20)
Profiler Agent: Established connection with the tool
*** Profiler engine warning: Cannot use ClassLoader.findLoadedClass() and/or ClassLoader.findBootstrapClass() in ClassLoaderManager`

If I then try and launch the actual game, the game crashes:

`Profiler Agent: Local accelerated session
*** Profiler engine warning: class jdk.internal.reflect.GeneratedMethodAccessor49 loaded by *** Profiler Agent Communication Thread
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.lang.StackWalker$StackFrame.getFileName()" is null
org.lwjgl.system.StackWalkUtil.isSameMethod(StackWalkUtil.java:44) at org.lwjgl.system.StackWalkUtil.isSameMethod(StackWalkUtil.java:38) at org.lwjgl.system.StackWalkUtil.lambda$stackWalkCheckPop$4(StackWalkUtil.java:72) at java.base/java.lang.StackStreamFactory$StackFrameTraverser.consumeFrames(StackStreamFactory.java:534) at java.base/java.lang.StackStreamFactory$AbstractStackWalker.doStackWalk(StackStreamFactory.java:306) at java.base/java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(Native Method) at java.base/java.lang.StackStreamFactory$AbstractStackWalker.beginStackWalk(StackStreamFactory.java:370) at java.base/java.lang.StackStreamFactory$AbstractStackWalker.walk(StackStreamFactory.java:243) at java.base/java.lang.StackWalker.walk(StackWalker.java:498) at org.lwjgl.system.StackWalkUtil.stackWalkCheckPop(StackWalkUtil.java:62) at org.lwjgl.system.MemoryStack$DebugMemoryStack.pop(MemoryStack.java:200) at org.lwjgl.system.MemoryStack.close(MemoryStack.java:168) at com.samrj.devil.game.Mouse.getPos(Unknown Source) at net.angle.omnicraft.client.world.entities.ClientPlayer.<init>(ClientPlayer.java:54) at net.angle.omnicraft.client.world.entities.ClientPlayer.<init>(ClientPlayer.java:42) at net.angle.omnicraft.client.GameScreen.<init>(GameScreen.java:62) at net.angle.omnicraft.client.DebugClient.startSinglePlayerGame(DebugClient.java:157) at net.angle.omnicraft.client.WorldSelectScreen.lambda$createMenuWindow$0(WorldSelectScreen.java:45) at com.samrj.devil.gui.Button.activate(Button.java:87) at com.samrj.devil.gui.DUI.mouseButton(Unknown Source) at net.angle.omnicraft.client.MenuScreen.mouseButton(MenuScreen.java:65) at net.angle.omnicraft.client.DebugClient.mouseButton(DebugClient.java:89) at com.samrj.devil.game.Game.lambda$run$3(Unknown Source) at com.samrj.devil.game.Mouse.button(Unknown Source) at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) at org.lwjgl.system.JNI.invokeV(Native Method) at org.lwjgl.glfw.GLFW.glfwPollEvents(Unknown Source) at com.samrj.devil.game.Game.run(Unknown Source) at net.angle.omnicraft.client.Client.run(Unknown Source) at net.angle.omnicraft.client.DebugClient.main(Unknown Source)`

 VisualVM continues just fine. I was able to use VisualVM to profile the game before - but that was when I was building it with Maven. I recently switched to building it with Gradle. The game includes Lombok - I think that may be the issue, that lombok is changing things during runtime, or something? Not sure why this happens with Gradle but didn't happen with Maven.

### Context
I am attempting to profile my game so I can increase it's performance.

### Steps to Reproduce 
I'm still trying to figure out how to reproduce this in a self contained example project. For the moment, you can reproduce it with my main project:
1. Build the maven branch of: https://gitlab.com/AngularAngel/devilutil
2. Build the gradle branch of: https://gitlab.com/AngularAngel/omnicraft,
3. Run the game
4. Run VisualVM and start profiling the game.
5. Click 'Local Game' and then 'Play'

### Your Environment
Build scan URL: https://scans.gradle.com/s/rb6e2lqivs2l4

**Comment by Angular-Angel** [comment]
I also made an issue of this for VisualVM: https://github.com/oracle/visualvm/issues/377

**Comment by Angular-Angel** [comment]
Hey, fixed my problem! Apparently, if your project included lombok, you need to add a plugin for it:

```id "io.freefair.lombok" version "6.3.0"```, from: https://plugins.gradle.org/plugin/io.freefair.lombok

instead of directly adding it as a dependency and an annotation processor:
```
    compileOnly 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'```

**Comment by ljacomet** [comment]
Thanks for your interest in Gradle.

I fail to see how the _building_ of the code could be the culprit in this scenario.
Unless you can point at a specific issue with Gradle, this looks like either an issue in your code itself or an issue between VisualVM and the Java VM you run your code with. The build scan indicates that you are using GraalVM at least for the Gradle build. I would investigate that combination first.

**Comment by Angular-Angel** [comment]
Yeah this turned out to be something with LWJGL. I thought Gradles handling of annotation processors might have been involved, but it seems actually not.

**Comment by JohnLavender474** [comment]
> Yeah this turned out to be something with LWJGL. I thought Gradles handling of annotation processors might have been involved, but it seems actually not.

Hi, can you elaborate what the issue with LWJGL was? I'm currently facing a very similar issue right now.
