### ISSUE TITLE
Dependency management (transitively) does not work as expected in an IVY/Maven mixed repository environment

### ISSUE THREAD

**Issue by sanderkerel** [gradle/gradle#19701]
An ivy dependency, which transitively refers to a maven dependency using the 'master' configuration should deliver only the library itself, without transitive dependencies. We found that this works correctly without applying plugins, but that this fails when the java plugin is applied; in that case the transitive dependencies of the maven dependency are _also_ delivered.

### Expected Behavior
When specifying a configuration on any (transitive) dependency, it should honor this.
Specifically on "configuration=master", it should only deliver the master library of the dependency, not its transitive dependencies.

### Current Behavior
The behavior is as expected when using core Gradle.
However when applying the gradle java plugin, suddenly also transitives of the dependencies of the dependency specifying "configuration=master" are delivered. This is unwanted.

### Context

The problem occurs when the following conditions are met:
- the dependency (B) referred to in the project (A) build has a transitive dependency (C) which is referred to in combination with the "configuration=master"  (only the module library itself (C) is the dependency, no transitive dependencies)
- dependency B is stored in an IVY repository
- dependency C is stored in a Maven repository
- the gradle java plugin is applied as addition to the gradle core

My build/application has to deal with above situation. Our own modules are published into a local IVY repository. All external libraries (previously stored in a local IVY repository) are now referenced directly from a Maven remote repository.
The "configuration=master" is used a lot in our projects/modules referring to the external libraries.

We now move from an (old/previous) approach where external libraries were stored in a local IVY repository to a new approach to referencing external libraries directly from a Maven remote repository.
Now the referencing of these particular external libraries (with "configuration=master") no longer works properly. The extra delivered (transitive) libraries cause all kind of problems.

We thought about using an alternate approach using the syntax "transitive=false" on these particular dependencies, which means a lot of modification. Since the "configuration=master" is a valid supported construction and basically works (unless using the java plugin), we would like to report this problem/bug and hope that it can be fixed soon.

### Steps to Reproduce

Build script of project B, in a directory 'projectB', to publish B into an IVY (file) repository:

```
// to be able to publish  (locally)
apply plugin: "java"

repositories {
    mavenCentral()
}

configurations {
  deps
}

project.version="1.0.0.0-1"
project.group="com.mysoftware"

dependencies {
  deps (
    [group: 'javax.xml.ws', name: 'jaxws-api', version: '2.3.1', configuration: 'master'],
  )
}

tasks.uploadArchives {
  repositories {
    ivy {name="myrepo"; url "c:/DEV/DS-1069/depmaintest/publish"}
  }
}
```
Build script of project A that refers to dependency module (project) B:

```
// if java plugin is enabled (applied), the transitive dependency (jaxws-api) of the first level dependency (depmaintest) will faultly deliver transitive dependencies as well if
// the transitive dependency (jaxws-api) is stored in a maven repository
// apply plugin: "java"

repositories {
    mavenCentral()
    ivy {
        name "SF_mylocal"
        url "file:C:/DEV/DS-1069/depmaintest/publish"
        allowInsecureProtocol=true
    }      
}

configurations {
  tools
}

dependencies {
  tools (
    [group: 'com.mysoftware', name: 'projectB', version: '1.0.0.0-1', configuration: 'deps'],
  )
}
```
Execute project B to publish this module into the IVY repository:
`gradlew -b projectB.gradle uploadArchives`

Execute project A to show the dependencies of the project (java plugin not yet enabled in A):
`gradlew -b projectA.gradle dependencies`

Output:
```
------------------------------------------------------------
Root project 'projectA'
------------------------------------------------------------

tools
\--- com.mysoftware:projectB:1.0.0.0-1
     \--- javax.xml.ws:jaxws-api:2.3.1
```
Now enable the java plugin in project A (uncomment line 3);
Execute again project A to show the dependencies of the project:
`gradlew -b projectA.gradle dependencies`

Output (partial):
```
------------------------------------------------------------
Root project 'projectA'
------------------------------------------------------------
(other configurations  (added by the java pluging))

tools
\--- com.mysoftware:projectB:1.0.0.0-1
     \--- javax.xml.ws:jaxws-api:2.3.1
          +--- javax.xml.bind:jaxb-api:2.3.1
          |    \--- javax.activation:javax.activation-api:1.2.0
          +--- javax.xml.soap:javax.xml.soap-api:1.4.0
          \--- javax.annotation:javax.annotation-api:1.3.2
```

### Your Environment

- windows 10
- gradle 6.9.1
- jdk 11.0.2  (adopt open jdk)

**Comment by eskatos** [comment]
Sorry for the late reply.
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by ljacomet** [comment]
This is most likely caused by variant derivation for Maven dependencies, which is activated by applying the Java plugin.

Without it, Gradle respects the configuration selection and is Ivy compliant. With it, we use variant resolution and ignore the configuration and its impact.

**Comment by ghale** [comment]
We don't think that depending on the master configuration should cause the dependency to be non-transitive.  Have you seen this behavior documented anywhere?  In any case, in our model, Maven dependencies do not have configurations and we have [deprecated the ability to specify maven dependencies by configuration](https://github.com/gradle/gradle/pull/30287).

If you would like to have dependencies resolved non-transitively, the "transitive=false" flag is the supported approach.
