### ISSUE TITLE
Make dependency verification compatible with configuration cache 

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#19716]
There are some issues with dependency verification and configuration cache I notice:
- changes to `verification-keyring.gpg`, `verification-keyring.keys`, `verification-metadata.xml` are not detected and the configuration cache is reused but it shouldn't be
- writing verification data (e.g. `./gradlew --write-verification-metadata pgp,sha256 --export-keys --configuration-cache`) should not reuse configuration cache

**Comment by asodja** [comment]
Hmm, thinking about it, the second one might actually be ok.

**Comment by bamboo** [comment]
Fixed via #23282

**Comment by adammurdoch** [comment]
More fixes in https://github.com/gradle/gradle/pull/23301. There is still a false cache hit after running `--write-verification-metadata` that should be fixed.

**Comment by bamboo** [comment]
Fixed via #24238.
