### ISSUE TITLE
Configuration cache captures system property value set by the build logic causing no cache hits afterward

### ISSUE THREAD

**Issue by chrisjenx** [gradle/gradle#19710]
Gradle 7.4-rc1 Configuration Cache will incorrectly detect `java.awt.headless` as changed.

### Expected Behavior
`java.awt.headless` is not set (null). Configuration cache should NOT be busted when re-running.

### Current Behavior
Gradle 7.4-rc1 will 100% of the time bust configuration cache due to `java.awt.headless` being null.

### Context
Regression in 7.4-rc1, reverted back to 7.3.3 and works as intended, does not get busted for every run.
Configurations are not being cached, this is regression in performance
This might be related to common user gradle plugin - but I belive that is a redherring as that does not even track that property

### Steps to Reproduce 
- Enable configuration-cache
- Run `./gradlew tasks` see cache be stored
- Run `./gradlew tasks` again, Gradle will complain about `java.awt.headless` changing and recompile cache

### Your Environment
Gradle 7.4-rc1, Java 17 (Zulu) - Linux (Ubuntu)

Enterprise server, please reach out for build scan

**Comment by mlopatkin** [comment]
Gradle 7.4 tracks system property reads at the configuration time more rigorously, there is no need to use a `providers.systemProperty()` - `System.getProperty/getProperties` work the same. However, it means that much more reads are now tracked. The common user data plugin uses an unfortunate access pattern that isn't well supported yet, making inputs out of all properties. However, it shouldn't matter if the property doesn't change.

It is possible to have this excessive invalidation if the system property in question is modified at the configuration phase by the build script/plugins, as the configuration cache records the value of the property when it is read first and doesn't track writes at all (yet).

@chrisjenx could you please check if the `java.awt.headless` stays unset while your build is running? Dumping its value in `TaskGraph.whenReady` callback should be late enough to confirm.

**Comment by chrisjenx** [comment]
So in my case it's not even unset, its set to true (not sure who or where, but it's consistently set)

```
gradle.taskGraph.whenReady {
    val headless = System.getProperty("java.awt.headless")
    logger.warn("Track java.awt.headless[${headless}]")
}
```
Runs
```
//Run 1:
Track java.awt.headless[true]
//Run 2
Track java.awt.headless[true]
```

**Comment by mlopatkin** [comment]
Thanks for the update, this confirms my assumptions. Changes of the system properties at the configuration phase aren't handled well at the moment, we'll try to address these in Gradle 7.5.

There are a few possible workarounds to have in the meantime, not all of them may be applicable:
1. Remove the read of the property at the configuration time. This is typically a preferred solution but in this case, it requires changes in the plugin.
2. Remove the property update at the configuration time. With this, the first run will capture the initial (unset) value of the property and consequent cached runs will not invalidate the cache.
3. Define the property to its expected value beforehand with `-Djava.awt.headless=true` switch or with `systemProp.java.awt.headless=true` in `gradle.properties`. With this the value cached build sees will match the expected value.
4. Make configuration cache capture the property eagerly at the start of the build, before it changes. for example, in `settings.gradle` or in the init script. Just calling `System.getProperty("java.awt.headless")` is enough. The cache captures the value at first use.

I should also note that the handling of changes wasn't completely correct in 7.3 as well: while the cache wasn't invalidated, the execution phase was seeing a wrong (unset) value of the property, see #18432.

**Comment by chrisjenx** [comment]
I tried defining it, then something else pops up so we'll need playing
whack a mole, I'll see if we can update the plugin to use the recommended
way now. Hopefully that fixes it.

**Comment by runningcode** [comment]
@chrisjenx did you ever find out where this was being read from? Was it a third party plugin?

**Comment by runningcode** [comment]
@mlopatkin could it be that the AGP lint plugin is setting the value? https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/java/com/android/build/gradle/LintPlugin.kt;l=91?q=java.awt.headless&start=1

**Comment by chrisjenx** [comment]
It was the gradle enterprise custom info plugin, we've got that patched
now.
