### ISSUE TITLE
Gradle cannnot resolve some dependencies

### ISSUE THREAD

**Issue by huylv** [gradle/gradle#19737]
Simple Gradle project cannot resolve dependencies, although similar project in Maven works just fine. The issue only started to come up recently. We have been working with the same set of dependencies for more than a year.

### Expected Behavior

Gradle should resolve, download and build the project

### Current Behavior

Error: Could not resolve org.eclipse.hudson:hudson-remoting:3.0.3

### Steps to Reproduce 

1. Create a new Gradle project with `build.gradle` as follows:

```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.eclipse.hudson:hudson-remoting:3.0.3'
}
```
2. Run `./gradlew build`. Error:
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.eclipse.hudson:hudson-remoting:3.0.3.
     Required by:
         project :
      > Could not resolve org.eclipse.hudson:hudson-remoting:3.0.3.
         > inconsistent module metadata found. Descriptor: org.eclipse.hudson:hudson-remoting:3.0.4-SNAPSHOT Errors: bad version: expected='3.0.3' found='3.0.4-SNAPSHOT'
```

### Your Environment

```
./gradlew -v

------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Mac OS X 10.16 x86_64
```

Build scan URL:

**Comment by ljacomet** [comment]
The published metadata is totally wrong, the version at https://repo.maven.apache.org/maven2/org/eclipse/hudson/hudson-remoting/3.0.3/ is actually `3.0.4-SNAPSHOT`
It is unfortunate that Maven has no issue with it, but I do not see Gradle accepting that. You might be able to use only the jar with `@jar` suffix to the dependency declaration - though I did not test it.

**Comment by huylv** [comment]
Hi @ljacomet,

I notice that too, but why has it been working until recently?

**Comment by asodja** [comment]
Something like this might work:
```
repositories {
    repositories {
        mavenCentral()
        mavenCentral() {
            name = "Download only jars repo"
            metadataSources { artifact() }
            content {
                // Use this repo just for affected artifact
                includeVersion("org.eclipse.hudson", "hudson-remoting", "3.0.3")
            }
        }
    }
}

dependencies {
    implementation('org.eclipse.hudson:hudson-remoting:3.0.3')
    implementation('commons-codec:commons-codec:1.4') {
        because("hudson-remoting requires it and we don't download a pom for hudson-remoting since its pom is broken")
    }
}
```

I see `commons-codec:commons-codec` is the only required of an `org.eclipse.hudson:hudson-remoting` so I added it by hand (others are test or provided dependencies so they are not needed).

I also tried it with some old versions of Gradle (6.1 and 5.1) and it failed in both. So maybe you used a different version of `hudson-remoting` or you used a fixed version from some other repo.
