### ISSUE TITLE
Upgrade embedded Kotlin to 1.7.10

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#19734]
When the next version of Kotlin is released, we need to upgrade it inside Gradle.

Through doing this, we need to revisit the NodeJs version bump done in `gradlebuild.internal.kotlin-js.gradle.kts` to support building Gradle on Apple Silicon.

**Comment by ljacomet** [comment]
@eskatos Since you are trying Kotlin upgrades, could you check this one?

**Comment by eskatos** [comment]
The NodeJS version bump is now in https://github.com/gradle/configuration-cache-report
Create https://github.com/gradle/configuration-cache-report/issues/3 about this

**Comment by eskatos** [comment]
The embedded Kotlin was upgraded to 1.7.10 in https://github.com/gradle/gradle/pull/21032 for Gradle 7.6.
