### ISSUE TITLE
make name for Eclipse resource filters configurable

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1974]
With the newly introduced Eclipse resource filter DSL for eclipse, you can now configure resource filters for the generated project file. But the name tag is intentionally left blank always. This makes the feature useless for certain usecases. If you e. g. want to exclude everything in `build` except of `build/classes/eclipse`, you need a resource filter on the `build` directory that non-recursively `INCLUDEs_ONLY` `FILES_AND_FOLDERS` with `1.0-name-matches-true-false-classes` and a second resource filter on the `build/classes` directory that non-recursively `INCLUDEs_ONLY` `FILES_AND_FOLDERS` with `1.0-name-matches-true-false-eclipse`. The directory on which the resource filter is effective is configured by the name of the resource filter. So the config to be generated is 

```
<filteredResources>
	<filter>
		<id>1</id>
		<name>build</name>
		<type>13</type>
		<matcher>
			<id>org.eclipse.ui.ide.multiFilter</id>
			<arguments>1.0-name-matches-true-false-classes</arguments>
		</matcher>
	</filter>
	<filter>
		<id>2</id>
		<name>build/classes</name>
		<type>13</type>
		<matcher>
			<id>org.eclipse.ui.ide.multiFilter</id>
			<arguments>1.0-name-matches-true-false-eclipse</arguments>
		</matcher>
	</filter>
</filteredResources>
```

This is currently not possible as there is no setting for the name and the code says `filterNode.appendNode("name"); // always empty`.

You can reproduce the wanted behavior with Eclipse by selecting the `build` directory and pressing Alt+Enter, then add the `classes` resource filter, then selecting the `classes` directory and pressing Alt+Enter, then add the `eclipse` resource filter.

**Comment by Vampire** [comment]
Also related, existing `resourceFilters` are overwritten and not merged with the ones from the build file and neither in `beforeMerged`, nor in `whenMerged` the `resourceFilters` field is filled, even though there are resource filters defined in the build file.

**Comment by bmuschko** [comment]
Could you please elaborate what you mean by "newly introduced Eclipse resource filter DSL for eclipse"?

**Comment by Vampire** [comment]
https://github.com/gradle/gradle/pull/846

**Comment by oehme** [comment]
This might be due to our misunderstanding of the resource filter API. I had assumed that "name" is a human-readable name for the filter, but found out that Eclipse would just throw exceptions whenever I give it a value. Thanks for clarifying that.

Would you be interested in fixing this with a PR?

**Comment by Vampire** [comment]
@oehme I guess if it would be just the DSL for the name, I would have done it, not sure about the merging and filling in beforeMerged and whenMerged. 

The main problem is, that I have a workaround. I did create this configuration even before this DSL. I mainly create PRs for stuff that really bugs me and for which I don't have a workaround, or that are easy to fix. :-)

**Comment by ams-tschoening** [comment]
There seems to be a [workaround](https://stackoverflow.com/questions/27437201/what-is-the-syntax-for-project-relative-path-in-eclipse-resource-filter), because `name` is not the only matcher one can configure. `projectRelativePath` can be used instead, actually allowing the relative path otherwise managed by `name`. The following in `build.gradle`:

	// Remove "buildSrc/build", "name" is not supported:  https://github.com/gradle/gradle/issues/1974
	eclipse.project.resourceFilter
	{
		appliesTo	= 'FOLDERS'
		type		= 'EXCLUDE_ALL'
	
		matcher
		{
			id			= 'org.eclipse.ui.ide.multiFilter'
			arguments	= '1.0-projectRelativePath-matches-false-false-buildSrc/build'
		}
	}

Leads to the following filter properly only removing `build` in the one mentioned directory:

	<filteredResources>
		<filter>
			<id>1</id>
			<name></name>
			<type>26</type>
			<matcher>
				<id>org.eclipse.ui.ide.multiFilter</id>
				<arguments>1.0-projectRelativePath-matches-false-false-buildSrc/build</arguments>
			</matcher>
		</filter>
	</filteredResources>

The important thing to note is that `recursive` needs to be `true` for this filter to work for some reason. But that's the default value anyway.

My project contains code in a package using "[...].build.[...]" and without `projectRelativePath` that would be unnecessary difficult to implement.

**Comment by Vampire** [comment]
@ams-tschoening I'm not fully sure, but I thought I tried using `projectRelativePath` but it didn't work for the descried use-case.
What you describe is a different use-case.
Did you try to do this with my use-case, which is excluding `build` except of `build/classes/eclipse`?
