### ISSUE TITLE
Provide an access to project like objects from a composite build while specifying dependencySubstitution for that compositeBuild

### ISSUE THREAD

**Issue by little-fish** [gradle/gradle#19741]
My use case is to simply allow substitution for projects whose version is equal to requested version.

Currently, there is no way to obtain such an information:

```groovy
includeBuild('...') {
    dependencySubstitution {
        all { dependency ->
            if (dependency.requested instanceof ModuleComponentSelector) {
                def targetProject = /* need to find a project within the composite build whose name matches with requested.module */
                if (dependency.requested.version == targetProject?.version) {
                    // allow the substitution.
                }
            }
        }
    }
}
```

### Expected Behavior
There is a way for receiving more information about projects from composite build while declaring dependency substitution rules.

### Context
I do not want substitution to happen if a version of substituted project doesn't match version of requested dependency.

Thank you.

**Comment by ljacomet** [comment]
Thanks for your interest in Gradle.

I do not think Gradle should support that use case.

By definition, composite builds are designed to offer the replacement of binary dependencies by their included equivalent. Having this tied to a version sounds quite complex.

Note that you can leverage `ResolutionStrategy#getUseGlobalDependencySubstitutionRules` to disable global substitutions for a given configuration.
