### ISSUE TITLE
SimpleHttpFileServerFactory doesn't properly close down the socket leaving it running

### ISSUE THREAD

**Issue by chubbard** [gradle/gradle#19756]
When using the `SimpleHttpFileServerFactory` to create a server the `SimpleHttpFileServer` is passed a `Stoppable` in to shutdown the server when `stop()` method is called.  However, inside that `Stoppable` defined in `SimpleHttpFileServerFactory` it calls the wrong thing to stop and doesn't properly close the socket.  Since the gradle process continues to run in the background after the task is over the socket stays open and can't be closed without killing the process.  Here is an example of how to reproduce this:

    ext {
        httpHome = property("user.home")
        port = 8085
    }

    task serve {
       doLast {
                SimpleHttpFileServerFactory factory = new SimpleHttpFileServerFactory()
                HttpFileServer server = factory.start(ext.httpHome, ext.port)
                try {
                    println("URL: http://localhost:8085/index.html")
                    println("Server Started on ${server.port} enter to kill it")
                    System.in.read()
                } finally {
                    server.stop()
                }
       }
    }

If you press enter the task completes successfully, but the server is still running even though you've called `stop()`.  I think when the author wrote this they used `Ctrl+c` which killed the process and that just happened to free up the server, but when running these in Intellij or other IDEs using `Ctrl+c` is often ignored.

Here is the code containing the bug from `SimpleHttpFileServerFactory`(line 30):

            final Server server = new ContainerServer(container);
            Connection connection = new SocketConnection(server);
            InetSocketAddress address = new InetSocketAddress(port);
            InetSocketAddress usedAddress = (InetSocketAddress)connection.connect(address);
            return new SimpleHttpFileServer(contentRoot, usedAddress.getPort(), new Stoppable() {
                public void stop() {
                    try {
                        server.stop();     // this should be connection.close()
                    } catch (IOException var2) {
                        throw new UncheckedIOException(var2);
                    }
                }
            });

So calling `server.stop()` doesn't close the socket because the socket is owned by `SocketConnection`, and it's `close` method is never called.  Futhermore, all you need to do is swap `Server.stop()` for `SocketConnection.close()` because `SocketConnection.close()` will call `Server.stop()`.

**Comment by jbartok** [comment]
This code (the JavaScript plugin in general) is no longer part of Gradle. We could fix this IF we ever get to do a `6.9.3` version, so adding that milestone.

**Comment by ljacomet** [comment]
Closing this as we are doing a 6.9,3 but I would not add anything to that release that is not a backport.
