### ISSUE TITLE
buildship cannot build project preview

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#1976]
I have a complex Gradle build that I tried opening with Buildship.
Eclipse complains that some property cannot be found.
Situation is as follows in this project:

- In the root project gradle file there is
```
ext.foo = 'bar'
```
- In `buildSrc` there is some plugin that uses `project.foo` or even `project.rootProject.foo`
- In a sub-projects gradle file this `buildSrc` plugin is applied

Now when Buildship tries to build the project preview, it fails, complaining that there is no property `foo` on the sub-project, or the root project, depending on whether `project.foo` or `project.rootProject.foo` is used.

Normal Gradle builds via the commandline work fine with this 3.5 build.

**Comment by Vampire** [comment]
Having Eclipse metadata already present from `gradlew eclipse`, the import dialog can correctly build the project preview.

**Comment by oehme** [comment]
Can you please move this issue to the [Buildship repository](https://github.com/eclipse/buildship)? Also, please  provide a reproducible example project on GitHub.

**Comment by bmuschko** [comment]
Closing as it is better suited to be asked in the Buildship repo.
