### ISSUE TITLE
Tooling model request should not fully configure the Project

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#1977]
Some tooling model don't need a configured project to be built.

### Expected Behavior
When requesting a tooling model then the project should not be fully configured.
Only settings should be evaluated by default.
Each model builder should then force-evaluate what it needs.

### Current Behavior
Any tooling model request fully configures the project.

### Context
Writing a tooling model builder that doesn't need a configured project.
On large builds the configuration is taking time and we don't want to pay that cost when it's not needed.

**Comment by oehme** [comment]
> Each model builder should then force-evaluate what it needs.

There's a chicken-and-egg problem here. The model builders are currently registered as part of project evaluation. We'd first have to come up with a better way to do that.
