### ISSUE TITLE
Support xfs for file watching. Report file system type when found to be unsupported

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#19786]
We've switched to `xfs` by default on our Linux machines which means file system watching no longer works:

```
19:12:37 Watching the file system is configured to be enabled if available
19:12:37 Not watching /mnt/data/agent/workspace since the file system is not supported
19:12:37 File system watching is active
```

Where `/mnt` is:
```
/dev/nvme1n1 on /mnt type xfs (rw,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
```

I assume that support isn't actually an implementation problem, but it's an allow list of known compatible filesystems? Would also be useful if the warning reporting the file system type in the "the file system is not supported" message.

### Expected Behavior
`xfs` should be supported.

### Current Behavior
`xfs` is not supported.

### Context
Gradle 7.3

**Comment by wolfs** [comment]
Hi Daniel, thank you for reporting. Can you run the build with `--watch-fs` and check if you receive file system events? We didn't add `xfs` to the list of supported file systems, since we didn't test it.

**Comment by wolfs** [comment]
This is our current list: https://github.com/gradle/gradle/blob/05b0d9072b112c34ab89b65575a0ee040d1441b4/subprojects/file-watching/src/main/java/org/gradle/internal/watch/vfs/impl/DefaultWatchableFileSystemDetector.java#L32-L51

**Comment by DanielThomas** [comment]
@wolfs looks good to me:
```
Received 2372 file system events during the current build while watching 1 locations
Virtual file system retains information about 4462 files, 584 directories and 9 missing files until next build
VFS> Statistics during current build:
VFS> > Stat: Executed stat() x 6,339. getUnixMode() x 3,542
VFS> > FileHasher: Hashed 6,168 files (1,035,071,594 bytes)
VFS> > DirectorySnapshotter: Snapshot 28 directory hierarchies (visited 420 directories, 2,163 files and 0 failed files)
```

**Comment by wolfs** [comment]
XFS will be supported for file system watching in Gradle 7.5.

**Comment by DanielThomas** [comment]
@wolfs these are AWS instances with ephemeral SSD storage (`m5d`, `i3`, etc) and we use xfs for RAID support so those instances with multiple devices get presented as a single filesystem.
