### ISSUE TITLE
Running tests from IDE always breaks configuration cache when running different test suites

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#19782]
### Expected Behavior

Rerunning tests from IntelliJ/Studio with changed sources should be able to reuse configuration cache

### Current Behavior

It breaks because of some random init script that gradle is factoring in from the IDE?

```
Executing tasks: [:services:drafts:testReleaseUnitTest] in project /Users/zsweers/dev/slack/slack-android-ng

Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused because content of 3rd init script, '../../../../../private/var/folders/2k/xmqm2vp118q00xsnp80x6lrh0000gp/T/ijtestinit3.gradle', has changed.
Type-safe project accessors is an incubating feature.
```

### Context

It prevents use of configuration cache benefits

### Steps to Reproduce 

Run a specific junit test suite from the IDE, observe it breaks CC when you run a different suite from the same project.

### Your Environment

Gradle 7.4-rc-1

**Comment by jbartok** [comment]
This will be solved once IntelliJ makes use of newly developed features.

**Comment by jbartok** [comment]
Relates to #19759

**Comment by NikolayMetchev** [comment]
Is there a YouTrack issue for idea to fix this?

**Comment by donat** [comment]
Currently, IntelliJ uses an init script-based approach to define filtering when running tests. This means that the init scripts change if different tests are executed, and consequently the configuration cache entry cannot be reused.

To fix the issue, IntelliJ needs to adapt Gradle's TestLauncher API which is compatible with the configuration cache. Up until now, there were missing features on that API that prevented the adoption. Gradle 7.6 will contain [all the missing features](https://github.com/gradle/gradle/issues/16295). The IntelliJ side of things are tracked [here](https://youtrack.jetbrains.com/issue/IDEA-232317).
