### ISSUE TITLE
Console sometimes does not show all work-in-progress

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1981]
### Expected Behavior
What's shown should be identical to the handling of Gradle 3.5 display. We're missing some progress events displayed (or an "empty" event is attached).

### Current Behavior
Sometimes the console shows all `> IDLE`, especially outside of `--parallel` mode.

### Context
There is either some merge conflict or semantic conflict between Ben and my recent changes. 

### Steps to Reproduce (for bugs)
Run a nightly build without `--parallel`

**Comment by lacasseio** [comment]
PR https://github.com/gradle/gradle/pull/1988 created.
