### ISSUE TITLE
A flag to turn `buildSrc` into a composite build

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#19829]
We've been using `buildSrc/` for a long time. 

Per [Current limitations and future plans for composite builds](https://docs.gradle.org/current/userguide/composite_builds.html#current_limitations_and_future_work):

> Making the implicit `buildSrc` project an included build.

I'd like to turn `buildSrc` into an included build via a specific flag or gradle property to better understand the limitations of composite builds, while gaining the benefits of composite builds - without introducing large git breaking changes to our project. This would make it easier to get to a point where we can leverage only composite builds in the future.

**Comment by yogurtearl** [comment]
related to/dup of https://github.com/gradle/gradle/issues/2531 ?

**Comment by adammurdoch** [comment]
This is more or less implemented in Gradle 8.0 via https://github.com/gradle/gradle/pull/22540. There are still a few differences, but is this already enough for what you need?

**Comment by adammurdoch** [comment]
Closing this issue as complete. If there are further improvements you'd like to see, please create new issues for those improvements.
