### ISSUE TITLE
In a multi-project build of java modules, gradle eclipse plugin does not add projects to eclipse module path

### ISSUE THREAD

**Issue by nhwalker** [gradle/gradle#19827]
The eclipse plugin does not seem to generate the .classpath entry for project(":some-sibling-project") style dependencies correctly when that project is a module.  It adds the dependency as a normal classpath entry, causing compile problems in eclipse. 

### Expected Behavior

If two subprojects in the same build have a module-info.java file and one depends on the other, then the generated eclipse .classpath file should add the dependency project to the module path

### Current Behavior

It adds it to the classpath instead of the module path

### Context

Without a fix, I cannot use gradle+eclipse to develop modern java applications split across multi-projects.

### Steps to Reproduce

See https://github.com/nhwalker/reproduce-gradle-multiproject-jpm-error

This project is the default multi-project application generated by the gradle init task with the following modifications:

1. eclipse plugin applied to all projects
2. all projects have a module-info.java file in src/main/java

./gradlew build and ./gradlew eclipse both build successfully.  But if the projects are imported into eclipse they do not compile because the projects don't recognize each other as modules to depend on with "requires" in the module-info.java file.

### Your Environment

I've tested this in gradle 7.3.3 and 7.3.4-rc2 and saw the same problem both times

**Comment by Sm0keySa1m0n** [comment]
I can confirm this issue is still occurring in 7.4.1
