### ISSUE TITLE
Build result should be easy to see relative to other logging

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1982]
BUILD SUCCESSFUL or FAILED is the most important piece of output, and yet it is not highlighted in any way other than color sometimes.

### Expected Behavior
Let's make that bolded at least, if not add color in more cases

### Current Behavior
![screen shot 2017-05-09 at 11 37 38 am](https://cloud.githubusercontent.com/assets/51534/25866629/efc0230e-34ab-11e7-8ddb-3ae58936b840.png)

**Comment by adammurdoch** [comment]
I think the title should be something like "build result should be easy to see relative to the other logging" to avoid locking in a specific solution to the problem. We don't _have_ to make it bold to solve this. For example, we might unbold the task headers.

**Comment by eriwen** [comment]
@adammurdoch Good feedback. I think overall if we want to achieve the "promotion" from console to logs, we should keep the headers bolded. Personally, I think it looks much better and makes it very clear that they are headers.

I will still change the title because I agree we don't want to prescribe too much here.

**Comment by adammurdoch** [comment]
There's no functional test coverage for this. We shouldn't close this issue until there is.

**Comment by w25r** [comment]
@adammurdoch added in #2078
