### ISSUE TITLE
Enhance user experience when artifacts are deleted from repositories

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#19820]
Currently, if an artifact is deleted, Gradle (correctly) only attempts to retrieve it from that same repo, even if other repositories have it. Unfortunately, this isn't very obvious to end users, who will only see Gradle using one repository and wonder why it isn't checking the others.

Gradle should indicate in some way that this is happening, and provide advice on how to fix it (content filters, removing the relevant cached metadata file, reordering repositories).

**Comment by big-guy** [comment]
We should see if this is the case when just an artifact is deleted, artifact+metadata or something else.

**Comment by octylFractal** [comment]
I couldn't figure out how to reproduce this. It may be fixed now.
