### ISSUE TITLE
Add JDKs downloaded by IntelliJ IDEA to Java Toolchains detection

### ISSUE THREAD

**Issue by rweisleder** [gradle/gradle#19830]
### Expected Behavior
When using the current [Java Toolchains detection mechanism](https://docs.gradle.org/current/userguide/toolchains.html) the [JDKs downloaded by IntelliJ IDEA](https://www.jetbrains.com/help/idea/sdk.html#jdk-from-ide) should be evaluated and added to the final set of JDK options.

IntelliJ IDEA stores downloaded JDKs in `~/.jdks` (Linux, Windows) or in `~/Library/Java/JavaVirtualMachines` (Mac), see [JdkInstaller.kt](https://github.com/JetBrains/intellij-community/blob/524a283980bb425b09339d6f15378c1ed0f44806/platform/lang-impl/src/com/intellij/openapi/projectRoots/impl/jdkDownloader/JdkInstaller.kt#L135-L142).

On my machine, this directory contains a `.<directory-name>.intellij` file for each directory. This file is a JSON file which (among others) contains the directory name. I'm not sure if we should simply treat every directory as JDK or if we should parse these files.

### Current Behavior
The Java Toolchains detection mechanism supports various OS platforms and package managers. JDKs downloaded by IntelliJ IDEA are skipped.

### Context
This feature request was originally mentioned in #16645. But since that issue has a different focus, the request was probably not followed further. So I'm taking the liberty of extracting that request into this separate issue.

I'd like to work on this and create a PR.

**Comment by jbartok** [comment]
We would welcome a PR for this. If it helps, pls. look at #19046, which added Maven Toolchain support.
