### ISSUE TITLE
Ability to preprocess Ivy metadata parsed from Ivy descriptors that are not Gradle-friendly

### ISSUE THREAD

**Issue by pantherdd** [gradle/gradle#19832]
### Context

I have a local Ivy repository that I need to use with Gradle. This repository contains legacy `ixy.xml` descriptors that look like this:
```xml
<artifact name="mylib" type="jar"     ext="jar"         conf="runtime"/>
<artifact name="mylib" type="src"     ext="src.jar"     conf="runtime"/>
<artifact name="mylib" type="javadoc" ext="javadoc.jar" conf="runtime"/>
```

Unfortunately when I add a dependency on MyLib's `runtime` configuration in Gradle, this kind of descriptor causes two important issues:
* source attachments don't work in the IDE (IntelliJ IDEA),
* all three JARs end up on the classpath, and in the application distribution.

This Ivy repository is still being used by legacy Ant builds, so I can't change the Ivy descriptors on disk.

I have looked at Gradle's extensive [dependency substitution](https://docs.gradle.org/current/userguide/resolution_rules.html#sec:substitution_with_classifier) and metadata fixup features, including [component metadata rules](https://docs.gradle.org/current/userguide/component_metadata_rules.html), but I was unable to find a solution that would allow Gradle to correctly consume such Ivy modules.

### Expected Behavior

It should be possible to somehow preprocess the metadata after it's been parsed from `ivy.xml` but before it gets used. For example:
```kotlin
repositories {
    ivy {
        artifact("/ivy-files/[organisation]/[module]/[revision]/lib/[artifact].[ext]")
        ivy("/ivy-files/[organisation]/[module]/[revision]/ivy.xml") {
            preprocess { parsed: IvyModuleParsedMetadata ->
                val fixedConfigurationDefinitions = parsed.configurationDefinitions.map { ... }
                val fixedArtifactDefinitions = parsed.artifactDefinitions.map { ... }
                IvyModuleParsedMetadata(
                    parsed.from,
                    parsed.dependencies,
                    fixedConfigurationDefinitions,
                    fixedArtifactDefinitions,
                    parsed.excludes)
            }
        }
    }
}
```
(In this example, `IvyModuleParsedMetadata` is a class containing the parameters of the [`IvyMutableModuleMetadataFactory.create`](https://github.com/gradle/gradle/blob/v7.3.3/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/IvyMutableModuleMetadataFactory.java#L61-L76) method, allowing that data to be preprocessed before it gets transformed into a `MutableIvyModuleResolveMetadata`.)

If that's not possible, I should be able to simply exclude artifacts based on a custom predicate (e.g. `excludeArtifacts { it.type != "jar"}`). This would not solve the source attachment issue, but the classpath would at least become clean.

### Current Behavior

Such preprocessing does not seem to be possible, or at least not in a clean and supported way.

I was only able to come up with a hacky and fragile solution: I subclassed `IvyMutableModuleMetadataFactory` overriding its `create` method, then used reflection to replace `IvyArtifactRepository`'s built-in instance with my own.

**Comment by ljacomet** [comment]
You should be able to achieve what you want with the help of [component metadata rules](https://docs.gradle.org/current/userguide/component_metadata_rules.html#header) and leverage variant derivation.

There are no plans to add more features for specific Ivy needs in Gradle itself.

**Comment by PantherDD** [comment]
@ljacomet, could you give an example of how I would separate the 3 artifacts, that are all in the `runtime` Ivy configuration, into separate configurations or variants using this feature?

I ran into this [`VariantMetadata.withFiles`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/VariantMetadata.html#withFiles-org.gradle.api.Action-), but [`MutableVariantFilesMetadata`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/MutableVariantFilesMetadata.html) does not allow me to actually make **adjustments** to the artifacts that were defined by the Ivy descriptor, all I'm able to do is to remove all of them, or add specific files. The problem is that I don't know the name of the files that I should add once I removed all of them. Could you please elaborate how to separate the files?

**Comment by PantherDD** [comment]
@ljacomet can you elaborate on how this would be possible with the tools you suggested?

**Comment by PantherDD** [comment]
@ljacomet Thanks for confirming that this is not currently possible. If you guys aren't planning improvements in this area , would you be open to my company contributing a feature that would let us hook into this part of the Ivy resolution process? Thanks :)

**Comment by PantherDD** [comment]
@ljacomet Would you guys be open to us contributing a change that would allow users to fix such nonstandard Ivy descriptors at runtime?

**Comment by pantherdd** [comment]
@ljacomet We would really like to implement this feature, if you're okay with the general idea of allowing users to do some custom post-processing of Ivy descriptors when they are loaded by Gradle.
