### ISSUE TITLE
Provide an API to list all Gradle properties in a Settings plugin

### ISSUE THREAD

**Issue by PhilGlass** [gradle/gradle#19840]
### Expected Behavior
There should be an API I can use to list all Gradle properties in a `Plugin<Settings>`.

### Context
I can use `ProviderFactory` to access the value of an individual property, but I don't think there's a public API I can use to list all properties without access to a `Project`. Injecting a `GradleProperties` instance works (like `GradlePropertyValueSource`), but that's an internal API with no stability guarantees.

I want to use this to attach all relevant Gradle properties to a build scan, along these lines:

```
gradleEnterprise.buildScan.buildFinished { 
    properties.forEach { (key, value) ->
        value("gradleProp.$key", value.toString())
    }
}
```

**Comment by ljacomet** [comment]
You could use: `providers.gradlePropertiesPrefixedBy("")` which would give you all properties starting with that _empty_ prefix.

Would that work for your use case?
