### ISSUE TITLE
`publish` task from `maven-publish` plugin should work with configuration cache

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#19842]
With gradle `7.4-rc-2`

### Expected Behavior

`publish` task from `maven-publish` plugin "just works" with config cache

### Current Behavior

```
cannot serialize object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository📋, a subtype of org.gradle.api.artifacts.repositories.ArtifactRepository📋, as these are not supported with the configuration cache.[ ?](https://docs.gradle.org/7.4-rc-2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types)
⌄fieldrepository📋 of org.gradle.api.publish.maven.tasks.PublishToMavenRepository$RepositorySpec$UnsupportedRepositorySpec📋
⌄bean of type org.gradle.api.publish.maven.tasks.PublishToMavenRepository$RepositorySpec$UnsupportedRepositorySpec📋
⌄fieldrepository📋 of org.gradle.api.publish.maven.tasks.PublishToMavenRepository$PublishSpec📋
⌄bean of type org.gradle.api.publish.maven.tasks.PublishToMavenRepository$PublishSpec📋
⌄fieldvalue📋 of org.gradle.internal.Try$Success📋
⌄bean of type org.gradle.internal.Try$Success📋
⌄fieldresult📋 of org.gradle.internal.serialization.Cached$Fixed📋
⌄bean of type org.gradle.internal.serialization.Cached$Fixed📋
⌄fieldspec📋 of org.gradle.api.publish.maven.tasks.PublishToMavenRepository📋
■taskpublishMavenPublicationToExampleRepository📋 of type org.gradle.api.publish.maven.tasks.PublishToMavenRepository📋
```

### Context

Would like to be able to use config cache when publishing

### Steps to Reproduce 

Use `publish` task from `maven-publish` plugin with config cache turned on.

**Comment by abstratt** [comment]
@yogurtearl Michael, could you please share a simple reproducer project here? I am new to the team, having a hard time reproducing this.

**Comment by abstratt** [comment]
Ok, managed to reproduce this. Will share a repository shortly.

**Comment by abstratt** [comment]
There is already (negative) test coverage for this missing feature:

https://github.com/gradle/gradle/blob/master/subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishHttpIntegTest.groovy#L55

A fix should include removing that `@ToBeFixedForConfigurationCache` annotation from as many places as possible.

**Comment by 3flex** [comment]
Also see https://github.com/gradle/gradle/issues/13468 - this issue is almost a duplicate.
