### ISSUE TITLE
Trying to resolve a configuration leads to a StackOverflowError

### ISSUE THREAD

**Issue by derklaro** [gradle/gradle#19848]
### Expected Behavior
Resolving a configuration used to be possible like this in Gradle 7.3.3:
```kotlin
    libraries.resolvedConfiguration.resolvedArtifacts.forEach {
      dependencies.add(DependencyUtils.convertToDependency(it, it.moduleVersion.id))
    }
```

### Current Behavior
Resolving the configuration results in an StackOverflowError.

### Context
I made a plugin which resolves the dependencies of a configuration and writes the result into a json file. The main plugin class is available here: https://github.com/CloudNetService/juppiter/blob/stable/src/main/kotlin/eu/cloudnetservice/gradle/juppiter/JuppiterPlugin.kt

When the plugin gets applied I add a new task and a provider to my module configuration which will eventually resolve the previously added configuration. This used to work completly fine in 7.3.3 but throws an exception in gradle 7.4.

I hope this is not my fault by using something which worked by accident :)

### Steps to Reproduce 
https://github.com/derklaro/gradle-7.4-regression-demo

### Your Environment
Build scan URL: https://scans.gradle.com/s/7x4hzesuo3oku / Full Error Gist: https://gist.github.com/derklaro/0b15ec06117fbdaf4e16a6b4f7f170e5

**Comment by ov7a** [comment]
Sorry for the late reply!

This issue is no longer reproducible with 8.2 and later versions of Gradle
