### ISSUE TITLE
Normalize or unify task logging headers in LIFECYCLE output

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1985]
### Expected Behavior
```
> :lib1_2:compileDebugJavaWithJavac
:lib1_2:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

:lib1_2:processDebugJavaRes NO-SOURCE
```

### Current Behavior
```
:lib1_2:compileDebugJavaWithJavac

> Task :lib1_2:compileDebugJavaWithJavac
:lib1_2:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

:lib1_2:processDebugJavaRes NO-SOURCE
```

### Context
This is odd, but not a deal-breaker because it's no longer the default behavior, nor does it affect tool-invoked builds like CI.

### Test Cases
* Jenkins and TeamCity should still be able to parse test output/build scan

**Comment by adammurdoch** [comment]
Is there test coverage for this? I didn't see any in the PR. If not, we shouldn't close this issue until there is.

**Comment by eriwen** [comment]
@adammurdoch There's test coverage in `OutputEventRendererTest` and of course unit tests for GroupingLogEventGenerator in https://github.com/gradle/gradle/pull/2027. Any specific additions you'd recommend?

**Comment by adammurdoch** [comment]
is there _functional_ test coverage?

**Comment by eriwen** [comment]
No, there's not. I'll reopen this and add some.
