### ISSUE TITLE
Give a brief indication of build cache effectiveness in build summary

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1987]
In 4.0 right now we have:
```
BUILD SUCCESSFUL in 9s
5 actionable tasks: 1 executed, 4 avoided (80%)
```

We do not provide detail of why work was "avoided". Either it was loaded `FROM-CACHE` or `UP-TO-DATE`. 

### Context
It may be preferable for users to always be made aware of how much work came from the cache.

What we really want is: "You saved 5m 7s by using --build-cache"... maybe, it is debatable whether the average user would care about this, and difficult to make a data-driven decision on this.

**Comment by lptr** [comment]
Another way of looking at this: before 4.0 we printed `FROM-CACHE` for every task that was loaded from cache. This gave a warm fuzzy feeling of things being right and fast because of this newly introduced feature called build cache. Not seeing `FROM-CACHE` all over the place also gave an indication that something was wrong.

With the reduced logging in 4.0 we give no indication whatsoever of the cache being useful or not. If you have build scans you can at least recover the information, but if you don't, you are left without any info.

**Comment by lptr** [comment]
I'm not sure if producing a meaningful "You saved 5m 7s by using --build-cache" message is achievable. Instead, what we want here is some simple indication that the cache was used successfully during the build. I think we should move any "time saved by cache" discussion to somewhere else.

**Comment by lptr** [comment]
One way to provide some feedback about the cache would be:

```text
BUILD SUCCESSFUL in 9s
5 actionable tasks: 1 executed, 4 avoided (40% no work, 40% from cache)
```

We might only show the split between `no work` (= `up-to-date` + `no-source`) and `from cache` only when `--build-cache` is enabled.

**Comment by wolfs** [comment]
👍 to what @lptr suggested. I would only show the distinction between `no work`/`from cache` if something came from the cache. The we wouldn't even need to check if the cache was enabled.

**Comment by lptr** [comment]
If we don't change the current behavior, we'll need to make changes to documentation like this:

> ### What does it look like
> 
> Let us start with a project using the Java plugin which has a few Java source files. We run the build the first time.
> 
> ```text
> $> gradle --build-cache compileJava
> Build cache is an incubating feature.
> Using local directory build cache (location = /home/user/.gradle/caches/build-cache-1), push is enabled.
> :compileJava
> :processResources
> :classes
> :jar
> :assemble
> 
> BUILD SUCCESSFUL
> ```

https://github.com/gradle/gradle/blob/4e4cfcbf4f12bf1d7d20a51f897f8c761fc489b9/subprojects/docs/src/docs/userguide/buildCache.adoc#what-does-it-look-like

**Comment by lptr** [comment]
```text
$> gradle --build-cache assemble
Build cache is an incubating feature.
Using local directory build cache (location = /home/user/.gradle/caches/build-cache-1), push is enabled.
:compileJava FROM-CACHE
:processResources
:classes
:jar
:assemble

BUILD SUCCESSFUL
```

**Comment by lptr** [comment]
Summarizing the [discussion](https://gradle.slack.com/archives/C0WTFHWT1/p1494426695238951) between @eriwen, @wolfs and @lptr:

We are going to add cached tasks, the output's going to look like this:

```text
XX actionable tasks: YY executed, ZZ from cache, WW up-to-date
```

(The ordering is more-work-done -> less-work-done)

**Comment by lptr** [comment]
This has been merged.
