### ISSUE TITLE
JVM Test Suite Plugin for integrationTest, how to add all test dependencies to integrationTest task in multi module project

### ISSUE THREAD

**Issue by xmlking** [gradle/gradle#19870]
I am trying to use new JVM Test Suite Plugin (Gradle version 7.3+). 
I have difficulty to add all `test` dependencies to `integrationTest` task at top level in a multi-module project.
 please advise if there is a clean way set it in root project that apply to all sub projects in https://github.com/xmlking/micro-apps

my env: Gradle v7.4

New

```kotlin
            testing {
                suites {
                    val test by getting(JvmTestSuite::class) {
                        useJUnitJupiter()

                        targets {
                            all {
                                testTask.configure {
                                    useJUnitPlatform {
                                        excludeTags("slow", "integration")
                                    }
                                    filter {
                                        isFailOnNoMatchingTests = false
                                    }
                                    // maxParallelForks = Runtime.getRuntime().availableProcessors() // FIXME: port conflict for quarkus
                                    testLogging {
                                        exceptionFormat = FULL
                                        showExceptions = true
                                        showStandardStreams = true
                                        events(PASSED, FAILED, SKIPPED, STANDARD_OUT, STANDARD_ERROR)
                                    }
                                    finalizedBy("jacocoTestReport")
                                }
                            }
                        }
                    }

                    val integrationTest by registering(JvmTestSuite::class) {
                        sources {
                            java {
                                setSrcDirs(listOf("src/test/kotlin", "src/test/java"))
                            }
                            resources {
                                setSrcDirs(listOf("src/test/resources"))
                            }
                        }

                        dependencies {
                            implementation(project)
                            //testImplementation(project(path = ":ontrack-extension-casc", configuration = "tests"))
                            implementation(project(":apps:classifier-pipeline"){ configurations { "testRuntime" } })
                            // implementation("org.assertj:assertj-core:3.22.0")
                        }

                        targets {
                            all {
                                testTask.configure {
                                    useJUnitPlatform {
                                        includeTags("integration", "e2e")
                                    }
                                    filter {
                                        isFailOnNoMatchingTests = false
                                    }
                                    testLogging {
                                        exceptionFormat = FULL
                                        showExceptions = true
                                        showStandardStreams = true
                                        events(PASSED, FAILED, SKIPPED, STANDARD_OUT, STANDARD_ERROR)
                                    }
                                    shouldRunAfter(test)
                                    finalizedBy("jacocoTestReport")
                                }
                            }
                        }
                    }
                }
            }
```

Old
```kotlin
            test {
                useJUnitPlatform {
                    excludeTags("slow", "integration")
                }
                filter {
                    isFailOnNoMatchingTests = false
                }
                // maxParallelForks = Runtime.getRuntime().availableProcessors() // FIXME: port conflict for quarkus
                testLogging {
                    exceptionFormat = FULL
                    showExceptions = true
                    showStandardStreams = true
                    events(PASSED, FAILED, SKIPPED, STANDARD_OUT, STANDARD_ERROR)
                }
                finalizedBy("jacocoTestReport")
            }

            register<Test>("integrationTest") {
                useJUnitPlatform {
                    includeTags("integration", "e2e")
                }
                filter {
                    isFailOnNoMatchingTests = false
                }
                testLogging {
                    exceptionFormat = FULL
                    showExceptions = true
                    showStandardStreams = true
                    events(PASSED, FAILED, SKIPPED, STANDARD_OUT, STANDARD_ERROR)
                }
                shouldRunAfter(test)
                finalizedBy("jacocoTestReport")
            }
```

**Comment by tresat** [comment]
So we're still discussing the best way to implement avoiding the need to relist the same dependencies in every test suite, but I can say with some confidence it probably isn't this.  The names of the particular configurations created for each test suite are _currently_ based on the name of the sourceSet, which matches the name of the Test Suite, but **these configuration names should be treated as an implementation detail and not be relied upon** to the greatest extent possible.  

We're working to expand the functionality offered by Test Suites and each suite's `dependencies` block to the point that referencing the configurations directly won't be necessary.  Expect some changes in this direction in Gradle 7.6.  The docs probably need to be more explicit about this point as well.

**Comment by tresat** [comment]
Please this linked PR, which will be coming to the docs soon, for some better options: https://github.com/gradle/gradle/pull/21012.

**Comment by Zordid** [comment]
So, guys, what is the solution to this? I clicked through ALL of the links in here but did not find an answer. I am using JvmTestSuite way to define my integrationTest - but HOW do I state that the int tests should depend on the normal unit tests???
```
integrationTest {
            val testContainersVersion = "1.17.6"
            dependencies {
                implementation(project())
                ... // HOW?????
            }
}
```

**Comment by Zordid** [comment]
HERE https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html
is where this needs to be documented! Right at the (5) where you depend on the project, almost everybody would need to know how to extent on the normal unit test module... 👎

**Comment by raymank26** [comment]
For me the following works (Groovy syntax):

```
configurations {
    integrationTestImplementation.extendsFrom testImplementation
}
```

This section should be a top-level declaration in the `build.gradle` file.

**Comment by sobelfall** [comment]
> For me the following works (Groovy syntax):
> 
> ```
> configurations {
>     integrationTestImplementation.extendsFrom testImplementation
> }
> ```
> 
> This section should be a top-level declaration in the `build.gradle` file.

Yes on top level build.grqdle 👍🏿

configurations {
	integrationTestImplementation.extendsFrom testImplementation
	acceptanceTestImplementation.extendsFrom testImplementation
}

**Comment by ChristianCiach** [comment]
I think a major reason why people want to re-use the dependencies of the `test` suite is because the `test` suite is the only suite that depends on the `implementation` dependencies of the project.

Whenever I find myself trying to use the `jvm-test-suite` plugin I always have to add *tons* of dependencies that are already `implementation` dependencies of the project. This is a lot of redundant work, and since we are currently not using version catalogs (because of its many shortcomings regarding subproject configurations), there is also extra work to keep the dependency versions in sync between the `implementation` dependencies of the project and the `implementation` dependencies of the `integrationTest` suite.

**Comment by rkrisztian** [comment]
> This section should be a top-level declaration in the `build.gradle` file.

So you mean the following has to be configured in the subproject that defines the test task, right? (In this example I'm referring to the `acceptanceTest` task)

```none
configurations {
    acceptanceTestImplementation.extendsFrom testImplementation
}
```

Because I have a problem that I would like to generalize this setting in the root project for every test task in every subproject, and currently I can't find an easy way to do. Especially if, let's say some subprojects don't have acceptance tests (or some other test task). Let's say some subprojects don't have Java test at all (because it wraps an NPM project). So now we're in a situation where we can't replace the gradle-testsets-plugin easily, yet it's still not compatible with Gradle 8...
