### ISSUE TITLE
the custom maven repository is invalid  when use command  `gradle init`

### ISSUE THREAD

**Issue by feng-sword** [gradle/gradle#19884]
1、setting custom maven repository in $GRADLE_USER_HOME/.gradle/init.gradle  

when i execute `gradle build` this is setting is useful，but when i execute `gradle init` for a already existing java project, and gradle request to https://repo.maven.apache.org.and my linux can not connect outside network，just connect my custom  maven repository ,so...What should I do.  

![image](https://user-images.githubusercontent.com/34203626/153534411-7dd5aa0e-2788-4c2e-b3ee-d3619471fc03.png)

**Comment by ljacomet** [comment]
Is your custom maven repository also configured for the maven project?
If yes, where? In settings?

Again, if yes, could you try with configuring it inside the maven project POM itself?

**Comment by feng-sword** [comment]
> 

no.the pom do not hava any repository configuration,and then I setting my custom repository in project pom.xml,But it didn't work，`gradle init` still use https://repo.maven.apache.org/maven2/
this is my gradle global setting:  
![image](https://user-images.githubusercontent.com/34203626/153568056-53b25687-1e42-47fc-bff3-323367c604fa.png)
this is my pom.xml:  
![image](https://user-images.githubusercontent.com/34203626/153568580-39c74de9-d70a-4ffb-a66d-c7310fff1216.png)

**Comment by ljacomet** [comment]
What happens if you define a mirror in Maven `settings.xml`?
My memory of Maven is that Central is always a repository unless you proxy it in settings.

**Comment by feng-sword** [comment]
> 

I have solved the problem。thanks for your help.  @ljacomet   
we need install maven , and setting maven environment variable, example:  
  `export M2_HOME=/opt/maven/apache-maven-3.6.1`  
  `export PATH=$M2_HOME/bin:$PATH`  
setting maven configuration  in settings.xml change default maven mirror to myself, and `gradle init `will use new maven mirror

**Comment by ljacomet** [comment]
Thanks for following up, closing

**Comment by semih-toprak** [comment]
I am having the same issue, but settings.xml did not fix it. Maybe its's because I use Windows. Plus, there is no reason for gradle to ignore my init.gradle settings, even when i explicitly tell it to use it by -I command.
