### ISSUE TITLE
IntelliJ Idea sync does not mark test suite sources

### ISSUE THREAD

**Issue by SgtSilvio** [gradle/gradle#19899]
Using Gradle 7.4 which has the new feature to "Mark additional test source directories as tests in IntelliJ IDEA" (https://docs.gradle.org/current/release-notes.html#idea-test-sources)

### Expected Behavior

When the jvm-test-suite plugin and the idea plugin are applied, the IntelliJ sync should mark the source folders of the test suites as test sources in the IDE. I expect this because of the release notes for Gradle 7.4: https://docs.gradle.org/current/release-notes.html#idea-test-sources

### Current Behavior

When the jvm-test-suite plugin and the idea plugin are applied, the IntelliJ sync does not mark the source folders of the test suites as test sources in the IDE, but rather normal sources.

### Context

The following is my guess what the problem is, it might be wrong:
`IdeaModule.getTestSourceDirs` does not delegate to the new API method `IdeaModule.getTestSources` and the IntelliJ sync directly relies on the old method.
Maybe it would make sense to implement the old method like so:
```
    public Set<File> getTestSourceDirs() {
-        return testSourceDirs;
+        return testSources.getFiles();
    }
```

### Steps to Reproduce 

- Using Gradle 7.4: `./gradlew wrapper --gradle-version=7.4`
- build.gradle.kts:
  ```kotlin
  plugins {
      java
      idea
  }
  
  testing {
      suites.register<JvmTestSuite>("integrationTest") {
      }
  }
  ```
- Sync in IntelliJ and see that `src/integrationTest/java` is not marked as test sources

**Comment by tresat** [comment]
This looks like it's caused by the same root issue as: https://github.com/gradle/gradle/issues/19645.  We're waiting on a fix from JetBrains, now that 7.4 is officially released and can be tested.  Please see the linked IDEA ticket in the comments for more information.
