### ISSUE TITLE
Spring Boot plugin requires Gradle 6.8.x, 6.9.x, or 7.x. The current version is Gradle 6.4 (On Gradle 7.4!)

### ISSUE THREAD

**Issue by elmsleypass** [gradle/gradle#19896]
I am using spring boot 2.6.2.  The filter is wrong.

Spring Boot plugin requires Gradle 6.8.x, 6.9.x, or 7.x. The current version is Gradle 6.4

--
And this is after i typed:
"gradle wrapper --gradle-version 7.4"

Which is weird because it's saying 6.4, but it should be detecting 7.4.

**Comment by elmsleypass** [comment]
Ah. This does work, and changing the property file directly works too!  

    ./gradlew wrapper --gradle-version 7.4

**Comment by jbartok** [comment]
Seems like the problem is solved, pls. let us know otherwise.

**Comment by elmsleypass** [comment]
Hmm, I still think it may be gradle

    
	private void verifyGradleVersion() {
		GradleVersion currentVersion = GradleVersion.current();
		if (currentVersion.compareTo(GradleVersion.version("6.8")) < 0) {
			throw new GradleException("Spring Boot plugin requires Gradle 6.8.x, 6.9.x, or 7.x. "
					+ "The current version is " + currentVersion);
		}
	}

If this says 6.4, then GradleVersion.current() is what is returning that value.

**Comment by bjornvester** [comment]
Are you sure you are running the wrapper (`gradlew` with a `w`) and not a manually downloaded distribution (`gradle` with no `w`) you have put in your path variable?

**Comment by elmsleypass** [comment]
Ah!  You are right, sorry for the confusion.  my installed gradle happened to be 6.4.  After updating that version, I have no issues. Thanks!

**Comment by AndyLau223** [comment]
Thanks, the solution works fine for me!!
