### ISSUE TITLE
improve documentation of feature variants

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#19898]
[plantuml](https://plantuml.com/pdf) allows to generate pdf, and for it needs additional libraries. they try to keep the basic jar slim. the maven build has a profile which allows to create a jar with dependencies.

i tried to convert this to gradle, using feature variants, from a producer perspective. it just behaved like one would add normal dependencies, and produces the fat jar. there is a question here: https://discuss.gradle.org/t/build-variant-command-line/42193 .

which left me a little unsure - if this is a bug, or a missing sentence in the documentation of [feature, producer part](https://docs.gradle.org/current/userguide/feature_variants.html), or just my stupidity.  in any case a sentence how to deal with such a use case including how to call it would be appreciated.

**Comment by donat** [comment]
Hi! Thank you for sharing this with us. I understand that there's room for improvement when it comes to the documentation of variant-aware dependency management. I don't think, however, that we'll revisit this section specifically. We'd rather want to focus on a larger documentation refactoring. In the meanwhile, I think the [Gradle forum](https://discuss.gradle.org/) is a better place to discuss the topic.
