### ISSUE TITLE
Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by khalidahmada** [gradle/gradle#19907]
Could not determine the dependencies of task ':unimodules-permissions-interface:compileDebugKotlin'.
> Could not resolve all files for configuration ':unimodules-permissions-interface:kotlinCompilerClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50.
     Required by:
         project :unimodules-permissions-interface
      > Could not resolve org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.50.
         > Could not get resource 'https://dl.bintray.com/okta/com.okta.android/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.50/kotlin-compiler-embeddable-1.3.50.pom'.
            > Could not GET 'https://dl.bintray.com/okta/com.okta.android/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.50/kotlin-compiler-embeddable-1.3.50.pom'. Received status code 502 from server: Bad Gateway

**Comment by rpalcolea** [comment]
looks like you have a repo configuration in your build pointing to https://dl.bintray.com/okta/ which doesn't exist anymore

Bintray disappeared last year, more info can be found in https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Ideally, you should be able to remove such configuration from your build to unblock yourself. Definitely not a Gradle issue. here

**Comment by ljacomet** [comment]
As indicated by @rpalcolea, this is a configuration issue in your build and not something that can be fixed in Gradle.
