### ISSUE TITLE
Extend `PropertyReportTask` to allow specifying which project to query

### ISSUE THREAD

**Issue by jamietanna** [gradle/gradle#19917]
### Expected Behavior

As a follow-up to #19493, it'd be great to be able to specify a `--project` to list the property/properties for, for instance:

```sh
./gradlew properties --console=plain --property version --project :
# or
./gradlew properties --console=plain --property version --project root
# or
./gradlew properties --console=plain --property version --project :nested:project
```

### Current Behavior

Listing properties for a multi-module prints all modules' matching properties.

### Context

As per #19493, this allows i.e. listing a specific project's `version` property, but could also allow other automagic interactions.

**Comment by ljacomet** [comment]
What you are asking goes against the way Gradle works.
Instead you should invoke that task on a single project if you want only that result only.
