### ISSUE TITLE
Application plugin startScripts task uses deprecated JavaExec.main and CreateStartScripts.mainClassName properties

### ISSUE THREAD

**Issue by swpalmer** [gradle/gradle#19921]
### Expected Behavior
Using ```--warning-mode all``` with the application plugin should not result in warnings the user has no control over.

### Current Behavior
Using ```--warning-mode all``` with the application plugin results in:
```
> Task :startScripts
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.4/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
The CreateStartScripts.mainClassName property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.4/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html#org.gradle.jvm.application.tasks.CreateStartScripts:mainClassName for more details.
```
### Context
Warning-free builds with ```--warning-mode all``` should be possible

### Steps to Reproduce 
Apply the 'application' plugin, then execute:
```gradle --warning-mode all build```

### Your Environment
Gradle 7.4 on macOS 12.2.1 with JDK 17.0.2

**Comment by hegyibalint** [comment]
Hi @swpalmer,

Hmm, I mostly see these warning messages through IDEA, as its generated buildscript contains this property.
I tried to replicate this simply, with the following script:
```gradle
plugins {
    `java-library`
    application
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("org.gradle.sample.Main")
}
```
But to no avail.
I've checked the codebase and found no invocations for respective getters/setters in `JavaExec`'s nor `CreateStartScripts`.

Can you share a buildscript that causes the issue for you? For the time being, I'm puzzled; I can't find good leads on this one.

**Comment by aaron-613** [comment]
I am getting these too, for mainClassName:

```
Starting a Gradle Daemon (subsequent builds will be faster)
The CreateStartScripts.mainClassName property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.4.1/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html#org.gradle.jvm.application.tasks.CreateStartScripts:mainClassName for more details.
```

However, I don't use `mainClassName` anywhere in my project.  I use `mainClass`.

```
$ grep -R -i mainClassName *
 < NOTHING! >
$ grep -R -i mainClass *
sniffer/build.gradle://    mainClass = 'com.solace.aaron.sniffer.TopicSniffer'
sniffer/build.gradle:  //mainClass = 'org.gradle.test.Main'
sniffer/build.gradle:        mainClass = className
solcache-scan/build.gradle://    mainClass = 'com.solace.aaron.sniffer.TopicSniffer'
solcache-scan/build.gradle:  //mainClass = 'org.gradle.test.Main'
solcache-scan/build.gradle:        mainClass = className
```

Not sure why it's complaining?  I updated to latest 7.4.1 but still issue persists.

## _15 minutes later_

Ok, I figured out my problem.  One of the projects had included `plugin id 'org.beryx.runtime' version '1.12.7'`.  When I commented that out, the warnings went away.

Is there any way for Gradle to tell you _where_ the offending line/property is located..?

Thanks!

**Comment by hegyibalint** [comment]
> Is there any way for Gradle to tell you where the offending line/property is located..?

No easy way that I know of - it's hard to locate the place of deprecation, this could be a place for improvement. If you feel adventurous, you can debug Gradle, and set a breakpoint on the getter method of the `mainClassName`:
https://github.com/gradle/gradle/blob/1c4b1a21342171d06d47d0e5e841279ddb40f13f/subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java#L253-L267

Then you should be able to see the place of invocation.

**Comment by swpalmer** [comment]
Sorry for not getting back to this sooner.  I've been busy and I can't remember the project that I was getting this on before.  I just tried a new project and can't reproduce it now either, so I suspect there was another plugin involved.  The report of "CreateStartScripts" in the application plugin referencing the property lead me to believe that it was the application plugin that was at fault.  I still don't understand it exactly.

**Comment by hegyibalint** [comment]
No problems at all!

I would close this issue for now, as it seems that another plugin is probably causing the issue, and not Gradle itself (I would've been really surprised, as Gradle's build should fail if we use any deprecated elements). Regardless, keep us posted in here if you find something which would suggest that it's on our side!
