### ISSUE TITLE
Promote configuration caching as a stable feature

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#19933]
The [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) is an incubating feature that significantly improves build performance by caching the result of the [configuration phase](https://docs.gradle.org/current/userguide/build_lifecycle.html#build_lifecycle) and reusing this for subsequent builds.

This issue is about promoting the feature to stable.

This issue is not about making the configuration cache the default.

Once this issue is resolved the configuration cache can be considered a stable feature and requires to opt-in in order to use it.

**Comment by ljacomet** [comment]
Done through #24061
