### ISSUE TITLE
Public API to allow tools to resolve build layout / root directory

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#1994]
Tooling need a public stable way to detect a Gradle build, resolve the root directory of a Gradle build etc..

For example IDEs need to detect a Gradle build when doing "smart project import".

When in IDEA you do `File > Open` and choose the directory of a build, it detects the build system in use and shows the Gradle project import wizard if either a `build.gradle` or `settings.gradle` file is present. To work around that detection you can do `File > New > Project from existing sources` instead ; this allows you to explicitly say "this is a Gradle build".

Eclipse/Buildship does not suffer from this issue as it does not support "smart import" yet, see https://github.com/eclipse/buildship/issues/356

This issue is about providing a stable public API to such tools so they can reliably and consistently implement Gradle build detection. It would also allow us to own the evolution of such detection.

### Expected Behavior

Gradle should provide a stable public API that allows tools to detect/recognize a Gradle build and its root directory.

### Current Behavior

Tools implement ad-hoc detection, often based on the presence of a `settings.gradle` file.

### Context

Looking at supporting Kotlin settings scripts, that is `settings.gradle.kts` files, see https://github.com/gradle/kotlin-dsl/issues/56
Implementation in Gradle and the Gradle Kotlin DSL is not an issue.
But it breaks some tools that rely on a e.g. `settings.gradle` file presence or have their own ad-hoc build layout detection.

**Comment by adammurdoch** [comment]
Should be implemented as a tooling API model, and reuse the detection that the tapi client does.

**Comment by big-guy** [comment]
Doesn't `GradleBuild` basically provide this? I *think* if you ask for a `GradleBuild` model from a subproject, you'll get information about the root.

**Comment by oehme** [comment]
`GradleBuild` requires configuring the whole build at the moment. Whatever solution we come up with here needs to be very fast. Users might be browsing through a file tree and we want to quickly show if they are currently looking at something that might be (part of) a Gradle build. If we first have to download Gradle and buildscript dependencies and configure the project, then that would be a terrible user experience.

Ideally we'd have something that's completely client-side to tell whether something is a Gradle build. Something that is independent of the build script language as well. That might for instance be the wrapper.properties file.

**Comment by adammurdoch** [comment]
It should be client-side. There are a couple of options:

1. reuse the logic that the tapi client uses to figure out the build layout. It uses this, for example, to locate the wrapper properties files.
2. add another model that is similar to `BuildEnvironment`, which is calculated by the provider.

The upside of option 1. is that it's _fast_. We don't need to download a Gradle distribution or load up the provider.

The upside of option 2 is that it's _accurate_, in that it can take version-specific settings and logic into account.

We've gone with option 1 in the tapi itself, so we probably should be consistent and use exactly the same logic. We can look at options for how the tapi and this model would later take version-specific settings into account later.
