### ISSUE TITLE
Provide ability to automatically re-write repository URLs

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#19941]
Our company blocks `mavenCentral()`, `jcenter()`, `google()`, `gradlePluginPortal()` etc automatically.

For internal company projects - it's easy enough to avoid declaring these. However, when working on open source projects it becomes problematic. I have to find every usage of external non-company repos and remove them, and manually inject our company maven repo.

I'd like a feature where I can have gradle automatically remap `mavenCentral()`, `google()`, etc to a specified url for all builds by my machine.

**Comment by LouisCAD** [comment]
@ZakTaccardi I think you can already do it with an init script or an init script plugin.

**Comment by ljacomet** [comment]
This is not something we plan on offering. You can see [this example](https://github.com/gradle/gradle/blob/16006ce8a5b3765e577a78785fb461ba7c1f2946/gradle/shared-with-buildSrc/mirrors.settings.gradle.kts) for how we handle this for the `gradle/gradle` build itself.
As answered above, putting that logic in an init script is also possible.
