### ISSUE TITLE
Composite Builds Hierarchical Multirepo Sample - fails when following the instructions 

### ISSUE THREAD

**Issue by maol74** [gradle/gradle#19953]
### Expected Behavior

When download groovy sample zip for example https://docs.gradle.org/current/samples/sample_composite_builds_hierarchical_multirepo.html, unpack it and following the instruction the build fails 

- when running `.\gradlew publishDeps` it fails, example uses maven repo during publish not Ivy as configured
- after cloning commons-lang, when running `gradle --project-dir modules/commons-lang build` the build fails during javadoc 
- after cloning commons-lang, when running  `gradle build` the build fails with following error 
```
* What went wrong:
Circular dependency between the following tasks:
:commons-lang:classes
\--- :commons-lang:compileJava
     \--- :commons-lang:jar
          \--- :commons-lang:classes (*)

(*) - details omitted (listed previously)
```

### Current Behavior

Build fails, see description above

### Steps to Reproduce 

See description above

### Your Environment

Build scan URL:
Using gradlew bundled in the example

**Comment by ljacomet** [comment]
Looks like that sample expects too much to happen with defaults only. It most likely need a number of changes so that hat it documents work ... and keeps working.

**Comment by maol74** [comment]
I was most concerned about the Circular dependency error, can´t understand why that happens, could that be a bug?

**Comment by jvandort** [comment]
There were definitely a lot of things wrong with this sample. Personally, I was not able to reproduce the circular dependency error you were seeing, but I was able to reproduce the rest. Following the directions line-by-line did not produce the circular dependency problem. Did you make any manual modifications to the sample files which may have caused that error?

**Comment by maol74** [comment]
Hi!
You should be able to reproduce the "Circular dependency" error by doing this when clone the commons-lang project

1. git clone http://gitbox.apache.org/repos/asf/commons-lang.git modules/commons-lang --branch master --depth 1
2. ./gradlew --project-dir modules/commons-lang init
I choose yes, 1, yes in the init questions
3. ./gradlew run

Note that I´m using gradlew from root project, standing in root dir. I also cloned out master instead. Could also be the init choices perhaps, I choose yes, 1, yes?
