### ISSUE TITLE
notCompatibleWithConfigurationCache failed to force errors into warnings

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#19959]
### Context
Android Gradle Plugin is adopting the new API `notCompatibleWithConfigurationCache` to let Gradle know which tasks are not compatible with config caching.

### Steps to Reproduce 

With the sample project attached, "androidDependencies" task has been specified as incompatible with config cache in app build file.

1. run `./gradlew androidDependencies`, and expect the build to finish
2. run `./gradlew androidDependencies --configuration-cache`, the build would fail unexpectedly

### Expected Behavior

With `notCompatibleWithConfigurationCache`, Gradle would force config cache errors into warnings

### Current Behavior

The build failed hard with errors like 

```
Configuration cache state could not be cached: field '__nestedComponents__' from type 'com.android.build.gradle.internal.tasks.DependencyReportTask': error writing value of type 'org.gradle.api.internal.provider.DefaultListProperty'
> Configuration cache state could not be cached: field 'delegate$delegate' from type 'com.android.build.api.component.impl.AndroidTestImpl': error writing value of type 'kotlin.SynchronizedLazyImpl'
   > Configuration cache state could not be cached: field 'value' from type 'kotlin.InitializedLazyImpl': error writing value of type 'com.android.build.api.component.impl.AndroidTestCreationConfigImpl'
      > Configuration cache state could not be cached: field 'globalScope' from type 'com.android.build.api.component.impl.AndroidTestCreationConfigImpl': error writing value of type 'com.android.build.gradle.internal.scope.GlobalScope'
         > Configuration cache state could not be cached: field 'extension' from type 'com.android.build.gradle.internal.scope.GlobalScope': error writing value of type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension'
            > Configuration cache state could not be cached: field 'publicExtensionImpl' from type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension': error writing value of type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated'
               > Configuration cache state could not be cached: field 'sdkComponents$delegate' from type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated': error writing value of type 'kotlin.SynchronizedLazyImpl'
                  > Could not create an instance of type com.android.build.gradle.internal.dsl.SdkComponentsImpl.
                     > Unable to determine constructor argument #6: missing parameter of type Provider, or no service of type Provider<Provider<List<RegularFile>>>.
```

[TaskNotCompatibleWithConfigCache.tar.gz](https://github.com/gradle/gradle/files/8093423/TaskNotCompatibleWithConfigCache.tar.gz)

**Comment by bingranl** [comment]
New findings: 

If you use the `notCompatibleWithConfigurationCache` API with ` :app:signingReport` task(just like what I did for `androidDependencies`) and run with config caching enabled, Gradle also fails to force error into warnings. See build output below.

---------------------------------------------------------------------------------------------------------------------

Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: signingReport

149 problems were found storing the configuration cache, 3 of which seem unique.
- Task `:app:signingReport` of type `com.android.build.gradle.internal.tasks.SigningReportTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:signingReport` of type `com.android.build.gradle.internal.tasks.SigningReportTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer', a subtype of 'org.gradle.api.artifacts.ConfigurationContainer', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:signingReport` of type `com.android.build.gradle.internal.tasks.SigningReportTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///usr/local/google/home/bingran/AndroidStudioProjects/TaskNotCompatibleWithConfigCache/build/reports/configuration-cache/3wbdeznuq9yzyrp4za8zccu7k/11gmfs5xydkv4cjdfo210s5nw/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field 'components' from type 'com.android.build.gradle.internal.tasks.SigningReportTask': error writing value of type 'com.google.common.collect.RegularImmutableList'
> Configuration cache state could not be cached: field 'elements' from type 'com.google.common.collect.ImmutableList$SerializedForm': error writing value of type '[Ljava.lang.Object;'
   > Configuration cache state could not be cached: field 'androidTest' from type 'com.android.build.api.variant.impl.ApplicationVariantImpl': error writing value of type 'com.android.build.api.component.impl.AndroidTestImpl'
      > Configuration cache state could not be cached: field 'delegate$delegate' from type 'com.android.build.api.component.impl.AndroidTestImpl': error writing value of type 'kotlin.SynchronizedLazyImpl'
         > Configuration cache state could not be cached: field 'value' from type 'kotlin.InitializedLazyImpl': error writing value of type 'com.android.build.api.component.impl.AndroidTestCreationConfigImpl'
            > Configuration cache state could not be cached: field 'globalScope' from type 'com.android.build.api.component.impl.AndroidTestCreationConfigImpl': error writing value of type 'com.android.build.gradle.internal.scope.GlobalScope'
               > Configuration cache state could not be cached: field 'extension' from type 'com.android.build.gradle.internal.scope.GlobalScope': error writing value of type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension'
                  > Configuration cache state could not be cached: field 'publicExtensionImpl' from type 'com.android.build.gradle.internal.dsl.BaseAppModuleExtension': error writing value of type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated'
                     > Configuration cache state could not be cached: field 'sdkComponents$delegate' from type 'com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated': error writing value of type 'kotlin.SynchronizedLazyImpl'
                        > Could not create an instance of type com.android.build.gradle.internal.dsl.SdkComponentsImpl.
                           > Unable to determine constructor argument #6: missing parameter of type Provider, or no service of type Provider<Provider<List<RegularFile>>>.

**Comment by eskatos** [comment]
Another example with a reproducer available in https://github.com/gradle/gradle/issues/20275#issuecomment-1082510514

**Comment by racka98** [comment]
This seems to have come back in gradle `7.6`

```
Configuration cache state could not be cached: field `sdkComponents$delegate` of `com.android.build.gradle.internal.dsl.LibraryExtensionImpl$AgpDecorated` bean found in field `extension` of `com.android.build.api.extension.impl.VariantApiOperationsRegistrar` bean found in field `variantApiOperations` of `com.android.build.gradle.internal.plugins.LibraryPlugin$LibraryAndroidComponentsExtensionImplCompat` bean found in field `value` of `kotlin.InitializedLazyImpl` bean found in field `androidComponentsExtension$delegate` of `com.android.build.gradle.internal.plugins.LibraryPlugin` bean found in field `this$0` of `com.android.build.gradle.internal.plugins.BasePlugin$dslServices$2$1` bean found in field `versionedSdkLoaderServiceProvider` of `com.android.build.gradle.internal.services.DslServicesImpl` bean found in field `dslServices` of `com.android.build.gradle.internal.variant.VariantPathHelper` bean found in field `paths` of `com.android.build.gradle.internal.variant.LibraryVariantData` bean found in field `testedVariantData` of `com.android.build.gradle.internal.variant.TestVariantData` bean found in field `variantData` of `com.android.build.gradle.internal.api.TestVariantImpl` bean found in field `testVariant` of `com.android.build.gradle.internal.api.LibraryVariantImpl` bean found in field `androidVariant` of `org.jetbrains.kotlin.gradle.plugin.mpp.KotlinJvmAndroidCompilation` bean found in field `map` of `org.gradle.api.internal.DefaultNamedDomainObjectCollection$UnfilteredIndex` bean found in field `index` of `org.gradle.api.internal.FactoryNamedDomainObjectContainer` bean found in field `compilations` of `org.jetbrains.kotlin.gradle.plugin.mpp.KotlinAndroidTarget` bean found in field `$kotlinAndroidTarget` of `org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$configureTarget$1` bean found in field `function` of `org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt$sam$org_gradle_api_Action$0` bean found in field `val$action` of `org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1` bean found in field `delegate` of `org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction` bean found in field `actions` of `org.gradle.internal.ImmutableActionSet$SetWithFewActions` bean found in field `addActions` of `org.gradle.api.internal.collections.DefaultCollectionEventRegister` bean found in field `eventRegister` of `org.gradle.api.internal.DefaultDomainObjectSet` bean found in field `libraryVariantList` of `com.android.build.gradle.LibraryExtension` bean found in field `$androidExtension` of `dev.icerock.gradle.MultiplatformResourcesPlugin$configureGenerators$setupAndroid$1$1$1` bean found in field `getAndroidRClassPackage` of `dev.icerock.gradle.generator.android.AndroidStringsGenerator` bean found in field `generators` of `dev.icerock.gradle.generator.android.AndroidMRGenerator` bean found in field `generator` of task `:compose-common:components:generateMRandroidMain` of type `dev.icerock.gradle.tasks.GenerateMultiplatformResourcesTask`: error writing value of type 'kotlin.SynchronizedLazyImpl'
> Could not create an instance of type com.android.build.gradle.internal.dsl.SdkComponentsImpl.
   > Unable to determine constructor argument #6: missing parameter of type Provider, or no service of type Provider<Provider<List<RegularFile>>>.
```

**Comment by vahe23** [comment]
This same problem for gradle `8.4`


`./gradlew androidDependencies --configuration-cache`

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 551 out of bounds for length 167
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
        at org.gradle.configurationcache.serialization.CombinatorsKt.readList(Combinators.kt:221)
        at org.gradle.configurationcache.serialization.codecs.FileCollectionCodec.decodeContents(FileCollectionCodec.kt:75)
        at org.gradle.configurationcache.serialization.codecs.FileCollectionCodec.decode(FileCollectionCodec.kt:67)
        at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.decode(BindingsBackedCodec.kt:59)
        at org.gradle.configurationcache.serialization.DefaultReadContext.read(Contexts.kt:269)
        at org.gradle.configurationcache.serialization.beans.BeanPropertyReaderKt.readPropertyValue(BeanPropertyReader.kt:106)
        ... 172 more
```
