### ISSUE TITLE
Could not find method getSourceSets()

### ISSUE THREAD

**Issue by 24glinka** [gradle/gradle#19951]
When compiling our project, it fails giving that error.

### Expected Behavior

The expected behaviour is: it compiles our project, using nebula plugin.

### Current Behavior

gradle wrapper --gradle-version 7.4

An exception occurred applying plugin request [id: 'nebula.plugin-plugin', version: '16.2.0']
> Failed to apply plugin 'nebula.source-jar'.
   > Could not find method getSourceSets() for arguments [] on extension 'java' of type org.gradle.api.plugins.internal.DefaultJavaPluginExtension

### Context

It stopped with 7.4, it works perfectly with previous ones.

We cannot upgrade. In any case, if future versions of Gradle cannot compile with Nebula plugin, we have to change it. So, it is a major change for us.

Our plugins and versions.

plugins {
    id 'war'
    id 'java'
    id 'java-library'
    id 'nebula.plugin-plugin' version '16.2.0'
    id "nebula.node" version "2.0.1"
    id "nebula.gulp" version "2.0.1"
    id 'com.github.sahara3.tomcat-runner' version '0.2.1'
}

### Your Environment

Build scan URL: https://gradle.com/s/wvcs3owc6ek7u

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

A full reproducer would really help figuring out what is wrong, can you provide one?

**Comment by 24glinka** [comment]
Sorry, for _full reproducer_ what do you mean?

**Comment by rpalcolea** [comment]
I think he meant a sample repo that reproduces the issue. This is definitely strange as that method definitely exists https://github.com/gradle/gradle/blob/v7.4.0/subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/DefaultJavaPluginExtension.java#L187 

And we have definitely used 7.4 with that version of plugin-plugin

A sample project will definitely help to find the problem 

(Nebula maintainer here btw)

**Comment by kelemen** [comment]
@24glinka Given your stacktrace, you are probably running this command with an old Gradle version (not 7.4). Try checking `gradle --version` first.

**Comment by ljacomet** [comment]
`gradle` will use the Gradle version the path. You can perfectly update the wrapper with the wrapper.
What happens when you run your command using `./gradlew` instead?

**Comment by ljacomet** [comment]
Given that the method was added in Gradle 7.1, using an older Gradle version on the path is the most likely issue. Closing for now. Will re-open if more information is provided and indicates another problem.

**Comment by 24glinka** [comment]
> `gradle` will use the Gradle version from the path. You can perfectly update the wrapper with the wrapper. What happens when you run your command using `./gradlew` instead?

I totally missed that method was available only since version 7.1. On the path I have Gradle 7.0, that was the reason why. Using **gradlew** solved. Thanks to all.
