### ISSUE TITLE
Gradle build stuck during test execution

### ISSUE THREAD

**Issue by abbas-gadhia** [gradle/gradle#19976]
I have a build that gets stuck everytime we execute our tests. The build is a multi-project build. We're running gradle 7.3.3 with jdk 11.

With a thread dump, I see 3 TaskProcessors all trying to stop the tests but all of them seem to be waiting on a condition that i cant seem to figure out. It seems that i can't reproduce this issue on a physical machine, but this is occurring consistently within a docker container. The docker container base image is centos 7. Also, interestingly, when the build is executed a second time on the same folder, it doesnt get stuck.

Following is the thread dump. 
https://gist.github.com/abbas-gadhia/b3cf0eed9552795e67dbd02b5d44e71b

Please help if possible.

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We suspect that it's the tests that are stuck, not Gradle. (The `stop()` method is not an indicator that Gradle is trying to actively stop the tests.) A **reproducer project** could really help us track down and fix your problem quicker. 

Also, it would be useful to get a thread dump of your test JVM, as opposed to the dump from the Gradle Daemon's JVM.

**Comment by abbas-gadhia** [comment]
You were right! After looking at the Gradle Worker Main thread dump, we identified that it was our code blocking on a future. I didnt know that the daemon delegates to another jvm to run the tests. Closing this issue. Thanks for your advice!

**Comment by csguys** [comment]
> You were right! After looking at the Gradle Worker Main thread dump, we identified that it was our code blocking on a future. I didnt know that the daemon delegates to another jvm to run the tests. Closing this issue. Thanks for your advice!

@abbas-gadhia I'm facing the same issue. Can you assist me in identifying the correct process to troubleshoot? I've tried using the `jps -lv` command to list all the running JVM processes, but there are multiple processes related to Gradle running.
