### ISSUE TITLE
executionHistory.bin is too big!17G

### ISSUE THREAD

**Issue by gezihua123** [gradle/gradle#19978]
### Expected Behavior
ExecutionHistory.bin is too big!17G
Maybe ,We can record data by relative path ,It repeats too many times.

### Context
android 3.4.2
gradle 5.3.1

**Comment by jbartok** [comment]
Could you maybe try with some more recent version of Gradle pls?

**Comment by gezihua123** [comment]
Thanks! Which gradle version ?

**Comment by jbartok** [comment]
Latest is 7.4 (https://gradle.org/releases/), so... let's say at least 6.9.2 (migration guide here: https://docs.gradle.org/current/userguide/upgrading_version_5.html), ideally latest.

**Comment by gezihua123** [comment]
hi! 
Firstly,I build an android project by 6.9.2 ,the executionHistory.bin still repeat paths.
Secondly! I  read 5.3.1 and  6.9.2  code ,I can not find any file remove operation.

**Comment by lptr** [comment]
This is a duplicate of https://github.com/gradle/gradle/issues/5178.
