### ISSUE TITLE
gradleTestKit() bypasses dependency resolution mechanics and breaks users

### ISSUE THREAD

**Issue by artem-zinnatullin** [gradle/gradle#19973]
Hi Gradle team, I have a multi-module project where I enforce same Kotlin lib versions across modules:

```kotlin
configurations.all {
    resolutionStrategy.eachDependency {
        // Use same version for all Kotlin deps to avoid compile/runtime errors.
        if (requested.group == "org.jetbrains.kotlin") {
            useVersion("1.6.10")
        }
    }
}
```

When I add `testImplementation(gradleTestKit())` in one of the modules, it **forces** kotlin 1.5.31 on the module despite the fact that I specifically override that.

I've tried forcing version like this too:

```kotlin
testImplementation("org.jetbrains.kotlin:kotlin-stdlib-common") {
    version {
        strictly("1.6.10")
    }
}
```

This ends up breaking my code because I depend on `kotlin.time.Duration` functions that changed between these releases.

If I **comment out** `testImplementation(gradleTestKit())`, Gradle resolves Kotlin libraries to the version I set.

I've created a tiny project that clearly shows the issue https://github.com/artem-zinnatullin/gradle-testkit-problems

Investigating it showed that when `gradleTestKit()` is present, it adds dependencies to the beginning of compiler classpath **bypassing** Gradle dependency resolution mechanics:

```java
./gradlew clean classes --debug | grep -i kotlin-stdlib
[DEBUG] [org.gradle.api.Task] [KOTLIN] :compileKotlin Kotlin compiler args: -Xallow-no-source-files 
-classpath /Users/user/.gradle/caches/7.4/generated-gradle-jars/gradle-test-kit-7.4.jar:/Users/user/.gradle/caches/7.4/generated-gradle-jars/gradle-api-7.4.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-ant-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-astbuilder-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-console-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-datetime-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-dateutil-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-groovydoc-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-json-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-nio-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-sql-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-templates-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-test-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/groovy-xml-3.0.9.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/javaparser-core-3.17.0.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-1.5.31.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-common-1.5.31.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-jdk7-1.5.31.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-stdlib-jdk8-1.5.31.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/kotlin-reflect-1.5.31.jar:/Users/user/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/gradle-installation-beacon-7.4.jar:/Users/user/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.10/b8af3fe6f1ca88526914929add63cf5e7c5049af/kotlin-stdlib-1.6.10.jar
```

You can see that `kotlin-stdlib-common-1.5.31` is in front of classpath, **despite** my use of `version { strictly("1.6.10") }`.

### Expected Behavior

`gradleTestKit()` should respect Gradle dependency resolution mechanics.

### Current Behavior

`gradleTestKit()` bypasses Gradle dependency resolution mechanics and adds its dependencies to the front of classpath which breaks users.

What's worse, Gradle `dependency` and `dependencyInsight` are completely useless in this case!! Because of how impudently  `gradleTestKit()` injects its dependencies! I was pulling my hear fighting the issue.

### Context

It breaks my project compilation and (if I solve it) runtime.

### Steps to Reproduce 

Tiny project that shows the issue: https://github.com/artem-zinnatullin/gradle-testkit-problems

### Your Environment

Gradle 7.4.

Related issue: https://github.com/gradle/gradle/issues/16557

**Comment by artem-zinnatullin** [comment]
It also breaks SL4J:

```java
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/user/.gradle/caches/7.4/generated-gradle-jars/gradle-api-7.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/user/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.10/f69d97ef3335c6ab82fc21dfb77ac613f90c1221/logback-classic-1.2.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext]
```

And now my logs don't work :/

**Comment by artem-zinnatullin** [comment]
In the meantime I was able to find workaround, apparently a group of Gradle plugin developers extract `gradleTestKit()` dependencies and publish them on Maven Central:

- https://search.maven.org/artifact/dev.gradleplugins/gradle-test-kit
- https://github.com/gradle-plugins/toolbox

I was able to swap `testImplementation(gradleTestKit())` to `testImplementation("dev.gradleplugins:gradle-test-kit:7.3.3")` and got all my dependency version resolved according to how I actually configured the build.

**Comment by ljacomet** [comment]
The issue relates to a number of other issues opened around the exact Kotlin version supported by Gradle at runtime.
The fact that you use test kit indicates plugin development, and in that context, the Kotlin version to use should really be the one of Gradle. So in that sense, the classpath is "more correct" as it matches what your code will see in Gradle itself.

While you seem to have a solution for your problem, note that the resulting build logic / plugin may fail at runtime if it leverages Kotlin features that are not yet available in Gradle.

Regarding the point about visualizing this in `dependencies`, `dependencyInsight` or `buildEnvironment` is indeed a long standing issue, see #8301, for which there is no solution at this time.

As indicated in [this comment](https://github.com/gradle/gradle/issues/16345#issuecomment-931437640), this is not a limitation we are ready to lift, so closing for now.

**Comment by artem-zinnatullin** [comment]
>The issue relates to a number of other issues opened around the exact Kotlin version supported by Gradle at runtime.

The way `gradleTestKit()` injects its dependencies in front of compiler and runtime classpath is breaking not just Kotlin, but also SL4J, Groovy, and all/any other dependencies it injects.

>The fact that you use test kit indicates plugin development, and in that context, the Kotlin version to use should really be the one of Gradle.

Incorrect, I never stated that I am developing a Gradle plugin :) I need to run Gradle as part of integration tests of the project. 

And this is why I am specifically sad, because I don't care which Kotlin/SL4J/etc versions Gradle depends on. All I needed is API to run Gradle and check run results (`ProcessBuilder` + strict output parser basically).

>The fact that you use test kit indicates plugin development, and in that context, the Kotlin version to use should really be the one of Gradle.

Kotlin version to use should be the one of Gradle, I agree, and Gradle has whole bunch of configuration resolution mechanics to enforce that, yet the team chose to forcibly bypass them and inject deps directly to classpath, just because you're developing a build system doesn't make it good to bypass your own APIs and rely on internal ones.

>As indicated in https://github.com/gradle/gradle/issues/16345#issuecomment-931437640, this is not a limitation we are ready to lift, so closing for now.

I've seen https://github.com/gradle/gradle/issues/16345, and I think it's a very different problem from `gradleTestKit()`.

For `gradleTestKit()` you could do something like this:

```kotlin
testImplementation("org.jetbrains.kotlin:kotlin-stdlib-common") {
    version {
        strictly("1.5.31") // Internal Gradle dep
    }
}
```

While allowing downstream users to override this if they agree to consequences.

In my case not only it broke compile time, but when I fixed it bunch of other code that was compiled against 1.6.10 started to fail because in runtime I still got 1.5.31 in a non-plugin module. 

It's just blatanly wrong that Gradle does this I think and breaks its own mechanism of investigation, you can imagine that I was going crazy because EVERYTHING Gradle provided me to investigate the issue said I was using 1.6.10 while it was wrong.

>Regarding the point about visualizing this in dependencies, dependencyInsight or buildEnvironment is indeed a long standing issue, see https://github.com/gradle/gradle/issues/8301, for which there is no solution at this time.

I think https://github.com/gradle/gradle/issues/8301 is a different issue, `gradleTestKit()` broke compile and runtime classpath in my module, not the buildSrc classpath.

With all due respect, I think this blatant classpath hijacking should be redesigned and this issue should be reopened.

**Comment by ljacomet** [comment]
Thanks for clarifying the context. I agree that the issue should be re-opened. I can also tell you that given the primary goal of test kit is to support plugin authors, the way it works is less of an issue in that context. And what I really mean by that is that this might not be fixed soon.

**Comment by perlun** [comment]
> I can also tell you that given the primary goal of test kit is to support plugin authors

I want to also chime in that we, similarly to @artem-zinnatullin, are using Gradle TestKit for non-plugin development.

Our use case is that we build the releases for our software as a set of `.zip` and `.war` files (which then get aggregated into a full "release" file). This release building is controlled by a particular Gradle project in our multi-project Gradle build, which has "intermediate complexity" (about 130 sub-projects when I do a rough count).

Once the release is built, we want to be able to test things like:

* Does it contain the expected files?
* Does it _not_ contain files that we expect to be excluded?
* Have we messed up dependency resolution? Are any dependencies that are expected to be part of file `foo` present in any of the `bar` files?
* etc

The Gradle TestKit is a pretty invaluable tool for things like this. It would of course be _possible_ to just run a child process for spawning Gradle manually, with the right system properties and environment variables set, for running the particular Gradle task... but is that even a supported scenario? :thinking: Running Gradle to spawn some JUnit tests, which in turn runs Gradle (to launch some other Gradle tasks) in the same project... :see_no_evil:
