### ISSUE TITLE
DependencyManagement is not available to consumer during runtime?

### ISSUE THREAD

**Issue by hanct** [gradle/gradle#19975]
Gradle v7.4

I have a project application depending on a library that in turn depends on spring-cloud-starter-openfeign. 

In my library's build.gradle, i have
```
 implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'
```

This means that this openfeign will NOT be exposed to the consumer (my project application), but will be available only to the runtime classpath of my consumer.   

However, there is also the below in the library's build.gradle, which the openfeign need to rely on. Yet this dpendencyManagement is not available to the consumer during runtime, forcing me to have no choice, but to duplicate it into the consumer's build.gradle. 
```
dependencyManagement {
  imports {
    mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
  }
}
```

Is this a bug? or suppose to work in that way?  Is there anyway to enhance gradle, to make dependencyManagement setting available to consumer during runtime.

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

Also, do you also have this problem with older Gradle versions, like 7.3.3?

**Comment by hanct** [comment]
Thanks. I never know Gradle has a native BOM support!

**Comment by hanct** [comment]
Hopefully there is no disadvantage of using gradle native BOM as compared to using spring dependency management plugin
