### ISSUE TITLE
Please stop "depreciating" useful features.

### ISSUE THREAD

**Issue by gregko** [gradle/gradle#19983]
Gradle 7.2 is giving me the following warnings:

Subproject ':utillib' has location 'C:\android\atVoiceLibs\utillib' which is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.2/userguide/upgrading_version_7.html#deprecated_flat_project_structure

This is completely useless and unintuitive. Why a library project, which I use in several apps, must be suddenly located in the "project root", which is specific to only one app? Am I supposed to create separate copies of my library module for each app? Who thought of such stupid thing?

Greg

**Comment by vlsi** [comment]
@gregko , have you considered composite builds?

**Comment by gregko** [comment]
No, because I have no idea what they are. When I develop or debug the app, it's convenient to have the library modules in the same workspace of IntelliJ Idea or Android Studio, so that I could at the same time debug and modify or enhance the library modules as needed (and my other project that use the same modules would benefit from these changes. I know I could develop the libraries in separate workspaces and include them as .jar or .aar files into the apps, but why go around, when the current solution works so well, and the only problem is that it's inconvenient to the gradle tool developers and forces them to go an extra mile to monitor the directories properly?

Greg

**Comment by vlsi** [comment]
> No, because I have no idea what they are

Check https://docs.gradle.org/current/userguide/composite_builds.html#defining_composite_builds

> it's convenient to have the library modules in the same workspace of IntelliJ Idea or Android Studio, so that I could at the same time debug and modify or enhance the library modules as needed 

I have not used Android projects, however, composite build allows edit and debug regular Java and Kotlin projects in a single IDE, including breakpoints and stuff.

> but why go around, when the current solution works so well

1. There's a solution -- composite build, which is more scalable (see https://docs.gradle.org/current/userguide/structuring_software_products.html)
2. The intention to deprecate "subprojects outside of project root" is specified in the deprecation warning, and this time, I do support the intention. It really complicates things (e.g. for plugin developers) if projects can be located outside of the root.

Even though I see how deprecations might be frustrating, it does not sound fair to use words from the issue description.

**Comment by gregko** [comment]
I'm sorry, but it is impossible to comprehend. I spent half of a day trying to convert to:

includeBuild '../../atVoiceLibs/utillib'

int the settings.gradle file, and in the app build.gradle any combination of:

implementation 'com.hyperionics.utillib:1.0'
implementation 'com.hyperionics:utillib:1.0'
implementation 'com.hyperionics.utillib'
implementation 'com.hyperionics:utillib'

and everything else I could think of. All I get are messages like "Failed to resolve com.hyperionics:utillib:1.0" or similar.

***

In my opinion, this whole matter resembles a car maker who decided that an essential feature of a car is inconvenient to build or service, and eliminated it. Passenger seats? Who needs them, if a solution exists - just hitch a trailer for the passengers? This will be easier to build, easier to service, and easier for "plugin developers" (e.g. seat cushions makers)...

Well, if it was a car, I would instantly abandon it and go to competition. But, there is no competition for gradle for Android app developers, so we are constantly abused by this tool developers for their own convenience. So sad.

Greg

**Comment by vlsi** [comment]
If you have specific questions, it would really help if you try minimal samples. It would help as well, if you try creating a minimized copy of your project.

It does not really help if you share frustration without really trying to fix things. It does not help Gradle developers, and, what is way worse is it demotivates them.

Your "issue" does not seem to be actionable at this point: I guess the deprecation can't be reverted as it would complicate a lot many things. At the same time, your use case seems to be solvable with composite builds, yet you provide no clue why it does not work for you (no demo project on GitHub, etc).

Of course, composing builds is not the easiest thing, however, it is not really complicated.

Please check samples. They work.
https://docs.gradle.org/current/samples/index.html#build_organization

**Comment by big-guy** [comment]
@gregko This deprecation was reverted in 7.4. We didn't intend for this to cause so much frustration.

Please keep the community's [code of conduct](https://gradle.org/conduct/) in mind. We're people too.

**Comment by gregko** [comment]
Great, thank you so much! I'm sorry for reflecting my frustration in these posts
