### ISSUE TITLE
'compileOnly' dependency fails if the version comes from the platform BOM

### ISSUE THREAD

**Issue by serpro69** [gradle/gradle#19980]
### Expected Behavior

The bom has a dependency declared:

```xml
      <dependency>
        <groupId>org.apache.cxf</groupId>
        <artifactId>cxf-rt-core</artifactId>
        <version>2.3.6</version>
      </dependency>
```

The project adds the bom as `platform` dependency, and adds the `cxf-rt-core` dependency without the version information:

```
dependencies {
    compileOnly("org.apache.cxf:cxf-rt-core")
}
```

This should resolve to a dependency with effective version from the bom. From `gradle dependencies` task:

```
compileOnly - Compile only dependencies for compilation 'main' (target  (jvm)).
\--- org.apache.cxf:cxf-rt-core -> 2.3.6
```

Note that the same works as expected if dependency is declared as `implementation`, or an explicit version is set with `compileOnly`.

### Current Behavior

The dependency resolution fails:

```
compileOnly - Compile only dependencies for compilation 'main' (target  (jvm)).
\--- org.apache.cxf:cxf-rt-core FAILED
```

### Steps to Reproduce 

1. `git clone git@github.com:serpro69/gradle-compileOnly-with-bom.git --branch kotlin-dsl`
2. `./gradlew dependencies --configuration compileOnly | grep -i failed`
```
\--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.32 FAILED
```
3. change `compileOnly` to `implementation` and run `./gradlew dependencies --configuration implementation` - dependency is resolved

**Comment by vlsi** [comment]
@jbartok , what do you mean by resolving compileOnly configuration?
If you want to figure out compile classpath, you need to resolve compileClasspath or something like that

**Comment by serpro69** [comment]
Hi @vlsi ,
Sorry, probably said one thing and meant another :D So to give a little context - I was moving a project from Maven to Gradle, and for maven's `provided` scope was using `compileOnly` configuration in gradle. I noticed compilation was failing, and ran `dependencies` task to check what's going on and saw a bunch of `FAILED` dependencies there. A little debugging showed me that those were dependencies declared through `compileOnly` configuration that were missing explicit version information (which is supposed to be provided via the `platform` bom)

**Comment by vlsi** [comment]
Please provide a test-case with expected and actual outputs :)

I guess "failed for compileOnly" should not really impact project build outcome.

**Comment by serpro69** [comment]
> Please provide a test-case with expected and actual outputs :)

I have provided that in the 'Steps to Reproduce' section. Or do you mean something else?

**Comment by vlsi** [comment]
compileOnly should not be resolvable, and it should have 
isCanBeResolved=false: https://github.com/gradle/gradle/issues/8585#issuecomment-480291188

However, the configuration is quite old, so lots of builds would break if Gradle just forbids resolving compileOnly.

**Comment by vlsi** [comment]
>I have provided that in the 'Steps to Reproduce' section. Or do you mean something else?

See #8585 and similar issues. It just makes no sense to "resolve" `compileOnly` configuration, and it is just a known bug of `dependencies` task to attempt resolving it if it does.

What is your Gradle version by the way? AFAIK `compileOnly` is not really resolvable for quite a while now.

**Comment by serpro69** [comment]
I see, so then it is kind of "expected behavior".

Gradle version is 7.3.1.

**Comment by vlsi** [comment]
Are you 100% regarding 7.3.1?

Here's what I get with 7.3.1 (note an explicit `configuration is not meant to be resolved`):


```kotlin
dependencies {
    compileOnly("test:test")
}
```

```
> Task :dependencies

------------------------------------------------------------
Project '...'
------------------------------------------------------------

compileOnly - Compile only dependencies for source set 'main'. (n)
\--- test:test (n)

(n) - Not resolved (configuration is not meant to be resolved)

A web-based, searchable dependency report is available by adding the --scan option.
```

**Comment by vlsi** [comment]
>I guess in this case the issue can be closed.

Just do it™ 😃

**Comment by serpro69** [comment]
> Are you 100% regarding 7.3.1?

No, `7.3` actually :D https://github.com/serpro69/gradle-compileOnly-with-bom/blob/3484d5960f71e4f67b3cc883c92becf33dfb0643/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by vlsi** [comment]
> No, 7.3 actually

Ok, your issue is caused by `kotlin("jvm") version "1.5.31"`, and it seems to be resolved in `1.6.10`:

```kotlin
plugins {
    kotlin("jvm") version "1.6.10"
}

group = "io.github.serpro69"

description = "gradle bug reproducer"

dependencies {
    platform("org.jetbrains.kotlin:kotlin-bom")
    compileOnly("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}
```

```
> Task :dependencies

------------------------------------------------------------
Root project 'reproducer-project' - gradle bug reproducer
------------------------------------------------------------

compileOnly - Compile only dependencies for compilation 'main' (target  (jvm)). (n)
\--- org.jetbrains.kotlin:kotlin-stdlib-jdk8 (n)

(n) - Not resolved (configuration is not meant to be resolved)
```

**Comment by serpro69** [comment]
Oh yeah, I thought it could be the kotlin plugin causing this as well. I'll upgrade and see if that fixes it. Thanks a lot!

**Comment by ljacomet** [comment]
Thanks @vlsi for following up and clarifying!
