### ISSUE TITLE
Make it possible to disable writing to the execution history

### ISSUE THREAD

**Issue by AlexLandau** [gradle/gradle#20005]
First: This is a niche request, and it may not impact a lot of other users. Nonetheless, it would have a significant impact on the performance of our CI builds, as explained below, so we’re hoping you’ll consider merging some version of [our PR](https://github.com/gradle/gradle/pull/20006).

**Background:** For our pre-merge CI builds, we run a very large number of tests in parallel by checking out VMs from a cloud service, making several containers per VM using Docker, and running tests in each of those containers. Before this happens, we run compilation (and some other tasks) using Gradle, and include the resulting files in the docker image we send to VMs. Each container process then runs a certain set of tests using Gradle.

One issue we’ve run into is that executionHistory.bin becomes huge in our builds -- currently 5.9 GB after running compilation tasks plus a second set of tasks with similar classpath inputs. This is an issue because of the copy-on-write behavior from using Docker and overlayfs. When Gradle runs, it writes to this file, which prompts Docker to make a copy of the entire file. Even though we’re using an in-memory filesystem, which reduces the runtime impact of this copy, the 6 GB added to memory usage from each container is large enough to significantly reduce the amount of parallelism we can do -- it’s about 25% of our memory used.

(Why is it 5.9 GB? I’ve poked around in the related code. This is mostly an issue of how it scales with both number of projects and number of source files. For a single task, the stored information includes an entry for each .class file elsewhere in the repo that is included in the task’s dependencies. There’s no sharing of this information among tasks. Our largest tasks store 14MB each, with 11000 tasks run from 770 projects.)

**The request:** We’d like to be able to disable writing to the executionHistory.bin file during a given Gradle invocation. I expect this would happen via a system property or other suitably obscure method, and it would be undocumented and clearly unstable/unsafe (“this will void your warranty”). We aren’t asking for future support, beyond “please don’t remove this for no reason”.

We have tested this approach, and it works for us (with one caveat: we also have to set the file to read-only in the filesystem, or else it will get copied when it is opened anyway).

If the executionHistory.bin could be made smaller, that would also serve our needs, but I expect that would be a much more difficult undertaking.

**Comment by jbartok** [comment]
Duplicates #19978

**Comment by jbartok** [comment]
Could you pls. let us know the Gradle version you are using?

**Comment by AlexLandau** [comment]
This is with Gradle 7.3.3.

**Comment by lptr** [comment]
IIUC, there are some tasks in your build that work with a large number of inputs that result in this behavior. One thing you can try is to disable up-to-date checks for just those tasks: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:disable-state-tracking

**Comment by AlexLandau** [comment]
Are you asking me to disable up-to-date checks for all my `compileJava`/`compileTestJava` tasks in my downstream projects? 😕

**Comment by lptr** [comment]
I'm not sure about the "downstream projects" part, but I believe yes. I also don't understand the disappointed face. If you disabled writing to the execution history, you'd get no up-to-date checks or incremental execution for any of your tasks. How is my recommendation worse than that?

**Comment by AlexLandau** [comment]
We write to the execution history in a build that compiles everything and runs other preparatory work. Then we run a second build (in the containers) that runs some tests, but reuses the compilation, etc. from the first run. Only the second run would use a read-only execution history.

**Comment by lptr** [comment]
I'm lacking some serious context here, but you could also use the local cache to keep your downstream builds from repeating compilation. Less efficient, but avoids writing to the execution history, which was the stated goal.

To take a step back, I don't see us implementing this functionality in this way as the resulting complexity would not be worth it. If we invested here, it would be more useful to de-dupe the execution history. It would decrease the size of the history file, and would increase performance for other builds, too. We have some plans to do that, but unfortunately it's not high on the priority list at the moment.

**Comment by wolfs** [comment]
@AlexLandau One more question: Which `executionHistory.bin` is using 6GB? Is it the one in the Gradle user home or the one in the project directory?

**Comment by AlexLandau** [comment]
@wolfs: This is the one in the project directory.

@lptr: I agree that read-only execution history shouldn't be a supported feature or an area that Gradle devs put time into. The most I'm hoping for is if https://github.com/gradle/gradle/pull/20006 could be considered, to spare us the pain of maintaining a fork or equivalent hacks.

**Comment by lptr** [comment]
With #20006 we'd need to add a lot more testing, make sure it's properly documented and available as a public feature. I once again don't think it's something we'll have bandwidth for, and even if we had it, there are better ways to invest here. Sorry about that.

We have decreased memory consumption in Gradle in #20002. Maybe this will help your use case already; we've seen it save a lot of heap for one of our customers with a large build.
