### ISSUE TITLE
Failure with configuration cache: Could not find build 'buildSrc'

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#20001]
If `OperationCompletionListener` is registered in `BuildEventsListenerRegistry` at `buildSrc` module, any Gradle invocation fails on configuration cache reuse with weird message `Could not find build 'buildSrc'`. 

Reproducer project is attached. Just invoke `./gradlew help` twice to reproduce it.

[operation-compeletion-listener-buildsrc.zip](https://github.com/gradle/gradle/files/8118475/operation-compeletion-listener-buildsrc.zip)

**Comment by ALikhachev** [comment]
With Gradle 7.4 build that reuses configuration cache fails with another message: `BuildServiceRegistration with name 'my_build_service_228510203' not found.`

**Comment by eskatos** [comment]
Thank you for the report with reproducer Alexander

**Comment by bamboo** [comment]
Fixed in Gradle 7.4.1.
