### ISSUE TITLE
Syntax Error in Wrapper_init.gradle

### ISSUE THREAD

**Issue by MbusoKotobe** [gradle/gradle#20024]
Folder Usernames that contain single quotes in them cause a syntax error to occur in the wrapper_init.gradle

### Expected Behavior
After creating a new project out of the box using IntelliJ, I expect it to build run without any errors out of the Box.

### Current Behavior
After the project is created and builds automatically the build fails with error with a Syntax Error.

### Context
I was trying to create a project for class today but failed to do so and we couldn't resolve the error.

### Steps to Reproduce 

1. Have Gradle installed in a username folder that contains a quote(s) in it. e.g user-folder-name = john's pc
2. Create a new Kotlin Project in IntelliJ IDEA/Community Edition
3. Choose Gradle as building tool
4. After creating the project, the initial build will fail
5. Gradle will generate a wrapper_init.gradle file with the contents below

`
gradle.projectsEvaluated { gr ->
  def wrapper = gr.rootProject.tasks["wrapper"]
  if (wrapper != null) {
    if (wrapper.jarFile.exists()) {
      wrapper.jarFile = new File('john's pc\\AppData\\Local\\Temp\\wrap4loc\\gradle-wrapper.jar')
      wrapper.scriptFile = new File('john's pc\\AppData\\Local\\Temp\\wrap4loc\\gradlew')
    }
    wrapper.doLast {
      def fileWithPathToProperties = new File('john's pc\\AppData\\Local\\Temp\\wrap4loc\\path.tmp')
      fileWithPathToProperties.write wrapper.propertiesFile.getCanonicalPath()
    }
  }
}
`

The Single Quote in [john's pc] broke the filePath string leaving it with an unclosed Single Quote at the end

### Your Environment
OS: Windows 10 H2
IntelliJ IDEA 2021.3.2 (Ultimate Edition)
Build scan URL:

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the core of the Gradle Build Tool.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/

---

This `wrapper_init.gradle` is a file generated by IntelliJ IDEA, not Gradle. And indeed that quote should be escaped!

**Comment by MbusoKotobe** [comment]
Thank you for the feedback and enlightenment.
Much appreciated!
