### ISSUE TITLE
Since Gradle 7.4, compileJava does not recognize symbols in generated source directory

### ISSUE THREAD

**Issue by Toldry** [gradle/gradle#20046]
When running `./gradlew clean build -xtest`, the compiler fails to find symbols in `[project root]/proto/build/tmp/protoGeneratedSrc` which is a directory produced by a build script we wrote.
 
This happens in multiple different projects since upgrading from Gradle 7.3.3 (where there was no problem) to Gradle 7.4 (where this problem does occur)

Some strange findings:
- Running `./gradlew clean build` (omitting the test exclusion) results in a successful build ✅
- Running `./gradlew clean ; ./gradlew build -xtest` (separating `clean` and `build -xtest` into two separate invokations) results in a successful build ✅

### Expected Behavior
Running `./gradlew clean build -xtest` should result in a successful build.

### Current Behavior
Running `./gradlew clean build -xtest` results in a compilation error with the following stack trace:

```
> Task :[REDACTED]:compileJava
[REDACTED: file path].java:1167: error: package [REDACTED] does not exist
      [REDACTED: line of code];
                                                                 ^
[REDACTED: 5 similar errors]
                                                       ^
6 errors

> Task :[REDACTED]:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':[REDACTED]:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
```

### Context

Gradle 6.7.1 no error ✅

Gradle 6.8.3 no error ✅

Gradle 7.0 no error ✅

Gradle 7.1 no error ✅

Gradle 7.2 no error ✅

Gradle 7.3 no error ✅

Gradle 7.3.3 no error ✅

Gradle 7.4 error occurs ❌

This issue is slowing us from upgrading from Gradle 6 to 7. 

### Steps to Reproduce 

I will try to give a self-contained example project where this occurs, but so far I haven't been able to untangle the dependencies of our projects from this error. I will update this bug once (if) I manage to overcome this.

### Your Environment

- Happens with both JDK 8 and 11
- Happens in both MacOS and Linux

**Comment by ljacomet** [comment]
This looks like a problem in input/output declaration and might have to do with changes on how `clean` is now checking that it should not run _after_ a producing task.

It would be great if you could share a build scan as it might help confirm that.

Unfortunately, without a scan or a reproducer, it is going to be hard to figure out what's the root cause.

**Comment by ghale** [comment]
Can you share the output with `--console=plain` so we can see the order of tasks executed (both with 7.4 and pre-7.4)?  I suspect it is a task ordering problem related to how the dependencies are declared between tasks, but it's hard to theorize without understanding exactly what's happening.  Obviously, a reproducer would be best, but until you have that, just seeing the task order might help.

**Comment by Toldry** [comment]
Sorry for the delayed response.

We found that creating a reproducer is infeasible, so there's sadly no way to progress in this bug on Gradle's side.

However, on our side, we found a way to restructure the project's task dependencies such that this bug no longer occurs.

With that, I'll close this bug.
