### ISSUE TITLE
Gradle hangs indefinitely after running tests

### ISSUE THREAD

**Issue by cpirie-intuit** [gradle/gradle#20040]
### Expected Behaviour

Tests to run successfully and Gradle worker to exit when completed

### Actual Behaviour

Tests run successfully, see the message `Application Daemon Shutdown Hook shutting down` however the worker never exits hanging indefinitely, and process GradleWorkerMain needs to be force killed.

### Context

Issue started in as of v7.2-rc-1 and still exists in v7.4 but does not happen in v7.1.1. 

Running jcmd on java processes doesn't show any BLOCKED threads.

Might be related to passing a `javaagent` argument in jvmArgs, specifically JMockit (v1.47). Removed the javaagent argument and process no longer hangs, but tests fail.

```
tasks.withType(Test) {
    jvmArgs "-javaagent:${classpath.find { it.name.contains("jmockit") }.absolutePath}"
}
```

**Comment by cpirie-intuit** [comment]
Dropping a note that the root cause to this was due to a "graceful" shutdown of tomcat process we have that calls `Thread.currentThread().join()` to wait for other tasks to finish. For some reason the `join()` no longer exits when upgrading from 7.1.1 to Gradle 7.2-rc-1.

We were able to remove this from our code which solves our problem. Not saying it won't happen to others though 😄

**Comment by ljacomet** [comment]
Thanks for following up. I will close for now as there is not enough information unfortunately to reproducer this and potentially identify an issue in Gradle.

If anyone else experiences something similar, please attempt to provide a reproducer so this has a chance to get looked at.

**Comment by wyesparrow** [comment]
@ljacomet kindly take a look at the repository below and consider reopening the issue.

[https://github.com/wyesparrow/gradle-hang.git](url)

Gradle 8.0.2, Oracle OpenJDK version 17.0.6,  IntelliJ IDEA 2023.1
