### ISSUE TITLE
如何使用SwingBuilder().edt {dialog ，手动输入修改编译时signingConfigs

### ISSUE THREAD

**Issue by hnty545** [gradle/gradle#20051]
请教一下，我最近升级gradle6.1.1，发现之前的脚本用不了了
之前在app脚本里加入gradle.taskGraph.addTaskExecutionListener(new TaskExecutionListener()的beforeExecute(Task task)
判断 if (task.name.startsWith("package") && task.name.endsWith("Release"))来捕获需要签名的打包任务，showPwdDialog打开SwingBuilder().edt {dialog 手动输入签名的信息
android.signingConfigs.release.storePassword = new String(input1.password)
android.signingConfigs.release.keyAlias = new String(input2.password)
android.signingConfigs.release.keyPassword = new String(input3.password)
以前版本的gradle是可以的，但是现在版本不可以了。
测试后发现，只能在projectsEvaluated之前修改是有效的。
请问比如运行assembleNormalProductRelease这个任务
1、在gradle的projectsEvaluated之前获取到任务名字，让我弹出输入框来修改signingConfigs？
2、或者在某个时间点捕获到package...Release的task，可以修改编译时的signingConfigs打包成功？
给我点建议，非常感谢！

**Comment by blindpirate** [comment]
Hi @hnty545 please describe in English, most team members don't understand Chinese.

Regarding your problem, unfortunately the described behavior seems to be from AGP (did you upgrade AGP as well?) - which is not maintained by Gradle team. Gradle provides APIs for the plugin, how and when these APIs are invoked is decided by the plugin, so there's nothing we can do. I'd suggest you to read the source code of corresponding tasks in AGP.
