### ISSUE TITLE
Gradlew stuck on mergeDebugResources

### ISSUE THREAD

**Issue by Robbie2725** [gradle/gradle#20056]
I am attempting to build an Android application APK using gradle on Android Studio, and have been doing so without issue for 6+ months. However, last week I started encountering an issue where the build would get stuck on the 'mergeDebugResources' step. I've tried waiting as long as possible to see if things were just slow on my PC (60+ minutes), but this did not resolve the issue. Most of the time, even if I attempt to cancel the build process, Android Studio seems to crash and freeze when gradle reaches this step (and even other applications on my PC seem to stop working properly). I have done some troubleshooting myself, and I have determined that it is not related to the code I have written, as this issue arises even with examples provided by Android studio. Also, I have tried re-installing both Gradle and Android studio, but this did not resolve the issue. Furthermore, I tried building with different versions of Gradle (7.2 and 6.1.1), but both resulted in the same issue. I have determined that it isn't due to something with Android studio, as this same issue occurs even when running gradle on the command line (I did not see any error/warning messages that might be causing this to happen). I have saved the command line printout after running 'gradlew -d -s assembleDebug', but I am hesitant to post it here since it states debug level logging will leak security information (and I am using my work computer). However, in this log, you can see gradle reach the mergeDebugResources step, but then just alternates between DefaultFileLockManager messages related to acquiring/releasing a lock on daemon address registry and a set of 'Compiling XML table' messages by ResourceCompilerRunnable$Companion. This seems to happen indefinitely until I terminate the process. Additionally, after re-running gradle, it complains about it being unable to acquire the journal cache lock and fails after about a minute. This error also points to the PID holding this lock, which is a java.exe process that I am unable to terminate using the 'taskkill' windows command. I am all out of ideas as to how to fix this issue, as it seems related to something gradle is doing behind the scenes. Any help would be immensely appreciated, as I need to be able to build this app for my job.

**Comment by Robbie2725** [comment]
I've tried letting the build run as long as possible (even when Android studio freezes), and now after it unfreezes I'm getting error messages stating daemon's have failed to shut down. It urges me to report this issue, so [here](https://github.com/gradle/gradle/files/8172915/timeout_log.txt) is the log messages after running gradle build with the scan option.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
