### ISSUE TITLE
java-library plugin: implementation becomes transitive, when deployed via mavenDeployer

### ISSUE THREAD

**Issue by scr** [gradle/gradle#2005]
### Expected Behavior
When using the implementation configuration of the java-library plugin, I would expect that the pom.xml that's generated and deployed does NOT include things from that configuration.

### Current Behavior
external dependencies declared in the implementation configuration become "runtime" dependencies.  Runtime dependencies are considered by gradle to be transitive.

### Context
Specifically, this issue pertains to using slf4j correctly - you're supposed to only make slf4j-api be transitive and not any implementation choice for the logger.  If I put implementation 'org.slf4j:slf4j-simple:+', and deploy the library, then anyone depending on it pulls in slf4j-simple too.

### Steps to Reproduce (for bugs)
1) make one library which has api 'org.slf4j:slf4j-api:+' and implementation 'org.slf4j:slf4j-simple:+'
2) Deploy or install it
3) make another library that depends on the first from the deployed or installed location
4) Run ./gradlew dependencies
- expect to not see slf4j-simple in the dependencies.
### Your Environment

 * Build scan URL:

**Comment by scr** [comment]
Ok - please check out this repo showing off the issue https://github.com/scr/gradle-transitive-deps/ apparently, it's worse than I thought - even without publishing; adding a dependency causes the implementation to leak!

**Comment by w25r** [comment]
I see the behavior your describing, but believe it to be intentional, and as documented.  Implementation dependencies ARE needed at runtime.

It would only be a 'leak' if the `implementation` dependencies leaked into the `compileClasspath`.  Does that make sense?

**Comment by scr** [comment]
Yeah, I get it - read the fine print and all - man, that dependency part of maven/gradle is so complicated - I really wish it could be cleared up _hand waivy_ somehow :D

**Comment by scr** [comment]
I guess I find it funny that optional is a plugin; not a first-class declaration. Optional really is the only way to describe something you want to run but don't want others to have and is probably specific to this slf4j stuff and probably only a few other cases like jsr305 annotations...
