### ISSUE TITLE
Please, take measures to avoid concurrent Gradle daemons

### ISSUE THREAD

**Issue by LouisCAD** [gradle/gradle#20068]
Hello dear Gradle folks,

For some reasons, I keep having multiple Gradle daemons occupying the RAM of my computer.

The 2 screenshots below shows how far it can go, and I find that insane:

<img width="508" alt="Screenshot 2022-03-02 at 10 36 48" src="https://user-images.githubusercontent.com/6975237/156335866-b93b8e3e-7ceb-406b-b552-6642a1f79f59.png">

<img width="429" alt="Screenshot 2022-03-02 at 10 52 08" src="https://user-images.githubusercontent.com/6975237/156338064-3b3bbe97-d0c3-4f3f-9f8f-88b2e760e88a.png">

It's very possible that this is linked to an IDE issue as well.
As for Gradle, I'd like that we have a way to tell Gradle: Don't start more than one daemon for a given Gradle version on that machine, and fail otherwise.

That way, IDE issues and other configuration problems that would normally affect the developer machine performance and battery life would surface immediately.

I believe it's something worth addressing, for all the developers that don't have the luck and the money to buy a machine where they can afford to waste gigabytes of RAM, and for the ones that can afford 64GB of RAM machines but don't want it to just go to waste, consumed by tools that are inefficient in some ways.

I you agree, I'll be happy to help in designing a solution for that.

Have a great day!
Louis CAD

**Comment by jbartok** [comment]
Dear Louis.

Sorry that you're having trouble with Gradle! I hope you also realize that Gradle has millions of users and if this would be a generic problem affecting everybody, somebody else would have pointed it out sooner. 

Now, let's figure out why you are having this issue. If you go into your Gradle Home directory (should be `~/.gradle`), you should be able to find a `daemon` folder in it, which in turn contains folders for various Gradle versions. Let's say you are using Gradle 7.4, then you need to go into `~/.gradle/daemon/7.4`. In there are daemon log files. You can match them to the processes you see in your screenshot via the process ID (PID), which is in the log file names. Pls. attach one or two logs for stuck daemons. 

Also, with the help of the PID you can get a stack trace of a stuck daemon, by using the `jstack PID_COMES_HERE` command. Pls. send us the stack traces too for the stuck daemons you give us the log files.

Hopefully, we should be able to help you, when we get that information.
