### ISSUE TITLE
Timeout waiting to lock daemon addresses registry with no owner PID

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#20061]
We're occasionally seeing these on our CI hosts:

```
09:20:31 org.gradle.cache.LockTimeoutException: Timeout waiting to lock daemon addresses registry. It is currently in use by another Gradle instance.
09:20:31 Owner PID: unknown
09:20:31 Our PID: 23530
09:20:31 Owner Operation: unknown
09:20:31 Our operation: 
09:20:31 Lock file: /mnt/gradle-home/3/daemon/7.4/registry.bin.lock
```

It's unclear what the cause of the locking failure is, if there's a defunct daemon, otherwise. Can the instrumentation/cause of this be improved to help find the cause?

### Your Environment
Gradle 7.4

**Comment by ljacomet** [comment]
Sorry for the late reply!

***

Is this something you are still experiencing with more recent Gradle versions?

If yes, could you add information about the environment setup?
* Bare machine vs. virtual vs. container
* OS and JDK versions
* And anything else that could help us figure this out

Possibly related:
* #4329

**Comment by DanielThomas** [comment]
Thanks @ljacomet. We can't help there anymore I'm afraid, because we've switched to single shot CI runners, so we don't have daemon reuse anymore.

**Comment by ov7a** [comment]
Thanks for the clarification! Let's close it as obsolete
