### ISSUE TITLE
Gradle on macOS deletes `.gradle` folder every time my internet is not connected

### ISSUE THREAD

**Issue by JulyWitch** [gradle/gradle#20066]
I'm using Gradle to run android applications,
I have this problem and it bothers me every time I don't have a good connection it just deletes 10GB files and starts to download them again.

### Expected Behavior

Keep the previous cache and do not redownload them.

### Current Behavior

Deletes all contents of the `.gradle` folder when the internet is not connected properly.

### Steps to Reproduce 

1. Start the Gradle build
2. Disconnect your internet

### Your Environment

```
-> uname -a
 Darwin MacBook-Air.local 21.1.0 Darwin Kernel Version 21.1.0; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64 arm

->./gradlew -v
------------------------------------------------------------
Gradle 6.7
------------------------------------------------------------

Build time:   2020-10-14 16:13:12 UTC
Revision:     312ba9e0f4f8a02d01854d1ed743b79ed996dfd3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.11 (JetBrains s.r.o. 11.0.11+0-b60-7772763)
OS:           Mac OS X 12.0.1 aarch64
```

**Comment by jbartok** [comment]
Might be related #17803. We would recommend you try a more recent Gradle version and check if the problem still persists. If it does, pls. provide more reproduction info. 

Another workaround would be to never run Gradle in your home directory but in subdirectories.
