### ISSUE TITLE
Version catalogs run into unexpected namespace conflicts

### ISSUE THREAD

**Issue by lchen8** [gradle/gradle#20060]
I've noticed that when parsing a version catalog, the namespace `x.y` will result in some type of conflict with the namespace `xy`.
Concretely, when I have the following two lines in my version catalog toml file:
```
com-googlecode-json-simple = "com.googlecode.json-simple:json-simple:1.1.1"
com-google-code-gson = "com.google.code.gson:gson:2.8.2"
```
The second line fails with the error:

```
> Could not create an instance of type org.gradle.accessors.dm.LibrariesForLibs.
   > org/gradle/accessors/dm/LibrariesForLibs$ComGooglecodeLibraryAccessors (wrong name: org/gradle/accessors/dm/LibrariesForLibs$ComGoogleCodeLibraryAccessors)
```

The lowercase "code" in `ComGooglecodeLibraryAccessors` suggests that it's searching in the `googlecode` namespace and not `google-code`.

I've done my best to verify that this behavior shows up if and only if I have both `xy` and `x.y` in the toml file.

### Expected Behavior
Gradle can parse this version catalog without error.

### Current Behavior
Gradle runs into the error described above.

### Context
We noticed this error while migrating to using version catalogs.
Firstly, the error message was vague and hard to debug.
Secondly, this requires us to manually edit these namespace "conflicts" which shouldn't be really conflicts.

### Steps to Reproduce 
This error is reproducible with my following sample repo: https://github.com/lchen8/gradle-bug-test-application/
It fails upon trying to sync/config with Gradle.
Within the sample repo, I've commented in [libs.versions.toml L9](https://github.com/lchen8/gradle-bug-test-application/blob/main/gradle/libs.versions.toml#L9) where the problem stems from.

### Your Environment
This problem appears both during Gradle sync (from Android studio) and any gradle command from terminal
Edited to add: We are using Gradle 7.4

Build scan URL: (The build scan was not published due to a configuration problem.)

**Comment by handstandsam** [comment]
This issue is with Gradle `7.4`.  Thank you!
