### ISSUE TITLE
Eclipse Doesn't See Members on java-test-fixtures Classes 

### ISSUE THREAD

**Issue by bobpaige** [gradle/gradle#20071]
JUnit tests executed in Eclipse that access classes in a subproject that use the java-test-fixtures plugin fail with an exception that the members don't exist.

### Expected Behavior
Executing tests in Eclipse that extend classes from a java-test-fixtures subproject are successful.

### Current Behavior
Executing tests in Eclipse that extend classes from a java-test-fixtures subproject fail with a NoSuchMethodError.

I'm trying to use the test-fixtures-plugin where one subproject has base classes for junit tests, imported by other subprojects for their tests. 
For example, a "mytestbase" subproject has a class "SampleBaseTest" with a method "getName()". Another subproject has a test "ExtnededSampleBaseTest" that extends "SampleBaseTest" and calls "getName()". This works from Gradle/CLI, but when I import the Gradle project into Eclipse, the tests fail to execute, claiming the methods don't exist on the base class.

### Context
I am trying to reuse base classes and utilities across subprojects in a single Gradle project. For example, environment initialization is in a "SampleBaseTest" class and other subprojects extend that class.

### Steps to Reproduce 
Sample project: https://github.com/bobpaige/SampleTestFixtures

1. Clone project and build with "./gradlew build"; success
2. Import project into Eclipse as a Gradle project and run the "ExtendedSampleBaseTest" class; failure

This test executes appropriately from the CLI, as verified by the junit HTML output (all tests from the base and extended class are executed with no errors).
BUT, when running within Eclipse, tests from the base class are not attempted and anything that calls "getName()" fails with a NoMethodFoundException.

Further, I tried, in the extended class, to use reflection to list the declared methods (calling "SampleBaseTest.class.getDeclaredMethods()"). This returns an empty array. Repeating that but calling "SampleBaseTest.class.getMethods()" returns an array of just the methods from Object ("wait", "getClass", "notify", etc.).

### Your Environment
Eclipse: Spring Tool Suite 4, Version 4.10.0.RELEASE, BuildId: 202103111225
Java: Coretto-11.0.9.12.1

**Comment by bobpaige** [comment]
FYI, I tried applying this fix, to no avail: https://github.com/gradle/gradle/issues/11845#issuecomment-572521754

**Comment by bobpaige** [comment]
Seeing very inconsistent behavior in Eclipse. As reported at first, it fails. 
When first applying the change mentioned immediately above, it still didn't work.

After carefully deleting all the .project, .classpath, and .settings files/directories and re-building, it worked.

THEN, after reverting the fixes, deleting all the hidden files, and running tests again (effectively my initial state), it WORKS. Which makes _no sense_.

Anyway, with this workaround in hand, I'm going to close this issue.

**Comment by mweber03** [comment]
I'm seeing this same issue after switching from 7.42 to 7.5.1. I think should be reopened.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This seems like an issue with Eclipse, which cannot be addressed in the Gradle Build Tool project.

Please open such Eclipse-related issues on their Issue Tracker at https://bugs.eclipse.org/bugs/.

If you believe that this is a grade issue, please provide an isolated reproducer. The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.
