### ISSUE TITLE
There should be a default parameter for `gradle_installPath`

### ISSUE THREAD

**Issue by NatoBoram** [gradle/gradle#20078]
### Expected Behavior

`gradle install` should have a default value that's inside the repo, hidden by `.gitignore`

### Current Behavior

It complains about unset `gradle_installPath` after building for a solid 13 minutes and one second.

> You can't install without setting the `gradle_installPath` property.

### Context

I'm trying to build it from source. I have the repo under `~/Applications/gradle`. I want to install it somewhere in `~/Applications/gradle`. I don't care *where* inside that folder, I just want it to work.

Running `gradle install` was suggested by [Installing from source](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#installing-from-source). I'm not proficient with gradle, but it seems like suggesting `gradle build` there, in a sidenote or something, could help. The build takes a dozen minutes so I have to wait for quite a while before `gradle install` fails; it would be worth it to add a default parameter. Or just intercept it and show that error message at the beginning, at least, so it could suggest to run `gradle build` instead.

### Steps to Reproduce 

```sh
git clone git@github.com:gradle/gradle.git
cd gradle
gradle install
```
And then get away from the computer for 13 minutes and one second

### Your Environment

~~Build scan URL:~~

**Comment by ov7a** [comment]
Sorry for the late reply. After discussing this, we decided that we didn't want to add the default location.
The docs indicate that the installation requires the parameter.
