### ISSUE TITLE
Gradle doesn't recognize disabled parameterized junit5 tests 

### ISSUE THREAD

**Issue by andrgn** [gradle/gradle#20081]
### Expected Behavior
If there's disabled parameterized test then after execution `./gradlew clean test` there's information in console-log that this test is skipped (e.g. `ParameterizedTest > parameterizedTest() SKIPPED`) and also in `*.xml` file located in `build/test-results/` there's information about this test with skipped attribute

### Current Behavior
Gradle doesn't indicate disabled parameterized tests as skipped tests or as tests at all and there isn't information about this tests in console-log and in `*.xml`

### Context

So, I'm trying to get reliable information about executed tests wich can help me to analyse what is checked and what isn't

### Steps to Reproduce 

- clone [this repo](https://github.com/andrgn/gradle-disabled-parameterized-test-issue)
- execute `./gradlew clean test`

### Your Environment

Build scan URL: https://scans.gradle.com/s/otul5mw7yy75u

### P.S.
I've looked into this problem and found out that junit5 works properly (It recognizes such tests). And the behaviour is correct too, if maven is used instead of gradle. 
![mvn-1](https://user-images.githubusercontent.com/23133790/156775965-dba731d7-27e9-48b4-9948-4093d3323883.png)
![mvn-2](https://user-images.githubusercontent.com/23133790/156776009-ec84518c-b824-4f14-80c0-10dff4891b69.png)

Thus the problem is on gradle side, to my knowledge

**Comment by toolateitsme** [comment]
+1 for this issue. I understand, that @ParameterizedTest is on @TestTemplate policy and has a different lifecycle than the obvious @Test 

Sad but true, but JUnit5 processes parameterized tests correctly (simple lifecycle in default DisabledCondition extension)

But gradle makes xml report incorrectly, while maven makes that correctly
