### ISSUE TITLE
Any plan for Gradle-Publish plugin?

### ISSUE THREAD

**Issue by hannah23280** [gradle/gradle#20091]
Hi,
  I learn about maven-publish plugin for gradle, that allow us to publish our project to local maven repository (i.e .m2 folder, by default)
  Is there any plan for gradle-publish plugin, such that it allow us to publish to our local .gradle folder, instead of .m2 folder. 
   It seems weird to have to maintain 2 different folders (.gradle and .m2)

**Comment by vlsi** [comment]
@hanct , what do you want to achieve?

**Comment by hanct** [comment]
I hope to have one of my gradle project to use another of my gradle project (think of the latter as a a library).  One way to achieve this isk via subprojects.   But i hope that gradle would provide another alternative to achieve this without involving subprojects, and that would be to publish the "library" gradle project to a local .mvn folder using maven-publish plugin, as learnt from online.

For the latter case, it is weird to have the project external dependencies installed in .gradle project, and my "library" gradle project's artefact to be inside the .mvn folder.  That is why I raised this query.   I am not the only one to query this, but another person has raised similar query at https://stackoverflow.com/questions/35460534/gradle-is-it-possible-to-publish-to-gradles-own-local-cache

**Comment by vlsi** [comment]
As answered here, Gradle cache is not a repository, and there's no way to "publish into .gradle": https://stackoverflow.com/a/35461207/1261287

**Comment by hanct** [comment]
> As answered here, Gradle cache is not a repository, and there's no way to "publish into .gradle": https://stackoverflow.com/a/35461207/1261287

In that case, is there a way for me to control the location of the .m2 ?   Cos i have set the GRADLE_USER_HOME to a custom location, so that the .gradle will appear in that location.  I wish the .m2 folder  to be customized to the same location as well, rather than the default user home directory.

**Comment by vlsi** [comment]
`-Dmaven.repo.local=...`

However, I would recommend trying composite builds instead: https://docs.gradle.org/current/samples/sample_composite_builds_basics.html

The drawback with "maven local" repository is that you need to publish there in a correct order, and you never know which artifacts are there.

On the other hand, with composite builds Gradle knows when tasks need to be rebuilt.
