### ISSUE TITLE
Dependency verification fails for signed klib artifacts

### ISSUE THREAD

**Issue by dsaff** [gradle/gradle#20098]
### Expected Behavior
(On Linux)
1. Check out [androidx-main](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main)
2. Verify that native tests pass:

```
cd frameworks/support
./gradlew --offline --no-configuration-cache -Pandroidx.kmp.linux.enabled=true collection2:collection2:linuxX64Test
```

3. Comment out the checksum entries for atomicfu-linuxx64, which should be unnecessary, because we have signatures for these libraries:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:gradle/verification-metadata.xml;l=958;drc=b272bd6b539052144693f444342085d10cf9943b

4. Repeat command from step 2.

5. Expect that this command also passes.

### Current Behavior

5. Fails with

```
> Task :collection2:collection2:compileKotlinLinuxX64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':collection2:collection2:compileKotlinLinuxX64'.
> Dependency verification failed for configuration ':collection2:collection2:linuxX64CompileKlibraries':
    - On artifact atomicfu-cinterop-interop.klib (org.jetbrains.kotlinx:atomicfu-linuxx64:0.14.4) in repository 'maven2': checksum is missing from verification metadata.
    - On artifact atomicfu.klib (org.jetbrains.kotlinx:atomicfu-linuxx64:0.14.4) in repository 'maven2': checksum is missing from verification metadata.
  
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.4/userguide/dependency_verification.html#sec:troubleshooting-verification
  
  These files failed verification:
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/5327c22844c66040e3ef8023f47cd1a6db8ab4e5/atomicfu.klib
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/d8fae915484834b47fab9a42596349589b3b03dd/atomicfu-cinterop-interop.klib
  
  GRADLE_USER_HOME = /usr/local/google/home/saff/.gradle
  
  These files failed verification:
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/5327c22844c66040e3ef8023f47cd1a6db8ab4e5/atomicfu.klib
    - GRADLE_USER_HOME/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-linuxx64/0.14.4/d8fae915484834b47fab9a42596349589b3b03dd/atomicfu-cinterop-interop.klib
```

### Context
We want to verify signatures on all of our dependencies, for build chain security.

**Comment by gavra0** [comment]
In this particular case, it seem that pgp key for `379CE192D401AB61` is missing from the `*.keys` file.

Related to this, using this project [verify.zip](https://github.com/gradle/gradle/files/8287090/verify.zip), and running:
```
rm -rf gradle/verification-* && ./gradlew --write-verification-metadata pgp,sha256 --export-keys
```

fails to retrieve key `379CE192D401AB61`, which does exist at https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x379CE192D401AB61. Also, this key server is listed  as a default one https://github.com/gradle/gradle/blob/d5e521483f43c5b0132c3bd3159395d2aac00bec/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/verification/DefaultKeyServers.java#L26.

**Comment by gavra0** [comment]
It actually seems like the location of the `.asc` file is not computed correctly for klib artifacts. See the attached debugger screenshot.
<img width="1206" alt="Screenshot 2022-03-31 at 21 46 35" src="https://user-images.githubusercontent.com/3955778/161146654-2a42d947-7064-47da-8445-4affd5fcb4f7.png">

In the debug logs, there is also
```
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/atomicfu-linuxx64/0.14.4/atomicfu-0.14.4.klib.asc]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/atomicfu-common/0.14.4/atomicfu-metadata-0.14.4.jar.asc]
```

Thanks @asodja for helping to debug this!

**Comment by liutikas** [comment]
What should the correct asc file URL be?

**Comment by gavra0** [comment]
It is `https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/atomicfu-linuxx64/0.14.4/atomicfu-linuxx64-0.14.4.klib.asc`.

**Comment by dsaff** [comment]
Thank you, this will be great!
