### ISSUE TITLE
Exec task output is not grouped with it's task output

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2009]
### Expected Behavior
Output from exec task should be grouped with other task output.

### Current Behavior
Output from exec task is also orphaned — e.g. using `gradle run` with the application plugin we don’t get a task header before the output from the executable.

### Context
It seems like output from forked processes isn't being properly associated with a build operation.

Helpful resources for debugging:
https://github.com/gradle/gradle/pull/1838/files
https://gist.github.com/eriwen/60a70242b518357986b9a5aedd34e28e

**Comment by lacasseio** [comment]
Discussion around how to implement this can be found [here](https://gradle.slack.com/archives/C03A0MT6S/p1494948728435799).
