### ISSUE TITLE
Packaging gradle 7.4.0 for openSUSE

### ISSUE THREAD

**Issue by frispete** [gradle/gradle#20096]
## Objective
Attempt to package the current gradle 7.4.0 as rpm [here](https://build.opensuse.org/project/monitor/home:frispete:java)

### Steps, being taken
Prepared a gradle-kit package (a helper package, that provides the full offline environment for building and using gradle)
After I found out, that building the gradle-kit package in a path containing colons fails, I managed to build it in a colon free area and that seemed to be working fine.

### Building gradle
The gradle build itself fails with:
```
[  124s] * What went wrong:
[  124s] Execution failed for task ':base-annotations:compileJava'.
[  124s] > Error while evaluating property 'javaCompiler' of task ':base-annotations:compileJava'
[  124s]    > Failed to calculate the value of task ':base-annotations:compileJava' property 'javaCompiler'.
[  124s]       > No compatible toolchains found for request filter: {languageVersion=11, vendor=ADOPTIUM, implementation=vendor-specific} (auto-detect false, auto-download false)
[  124s] 
```
but no matter, how I treat the java.toolchain in build-logic/jvm/src/main/kotlin/gradlebuild.unittest-and-compile.gradle.kts

- vendor.set(JvmVendorSpec.ADOPTOPENJDK)
- switch to other language versions (8)
- setting specific implementations implementation.set(JvmImplementation.VENDOR_SPECIFIC)
 
it results in variations of above error.

### General concerns
The major problem with packaging is, that everything needs to be available (offline build) in order to be reproducible.

It would be nice to limit the number of used JVMs for the build to just one, if possible. We have 8, 11, 12, 13, 14, 15, 16, 17 available.

### Environment
openSUSE Tumbleweed 
Kernel 5.16.11
Most packages are pretty current

[Full debug build log](https://build.opensuse.org/public/build/home:frispete:java/openSUSE_Tumbleweed/x86_64/gradle/_log)

**Comment by jbartok** [comment]
Hi.

In order to build and package Gradle you should need a single JDK. Here is the documentation of how auto-detection works: https://docs.gradle.org/current/userguide/toolchains.html#sec:auto_detection

If you are actually running tests, then yes, you will need more. Unfortunately, we don't really have the bandwidth to help you create the packages. 

Rgds
