### ISSUE TITLE
Regression in 7.4 from 7.3.3

### ISSUE THREAD

**Issue by tlf30** [gradle/gradle#20102]
### Expected Behavior
When using `com.github.ben-manes.versions` plugin on a project with kotlin dependencies, the dependency versions should resolve correctly. 

### Current Behavior
The dependencies fail to determine the correct version. See https://github.com/ben-manes/gradle-versions-plugin/issues/471#issuecomment-1058830284

### Context
Stopped working 7.4, was working in 7.3.3.
This is impacting the ability to generate accurate dependency version reports. 

### Steps to Reproduce 
Sample gradle.build:
```
plugins {
  id 'com.github.ben-manes.versions' version '0.42.0'
  id 'java-library'
}

repositories {
  mavenCentral()
}

dependencies {
  api 'org.jetbrains.kotlin:kotlin-script-runtime:1.1.0'
}
```

### Your Environment
Tested in Window 11, and in debian based CI container. Using gradle wrapper. JDK 17.

**Comment by ljacomet** [comment]
This is a consequence of the addition of extra consumable configurations like `mainSourceElements` and `testResultsElementsForTest` which are designed to be consumed leniently only as the requested variant may not always exist, especially for published libraries.

And combined with the fact that the versions plugin attempts to resolve them directly is what causes the issue. These configurations are explicitly marked as `canBeResolved=false` and so should not be resolved that way.

**Comment by ov7a** [comment]
We believe this issue is no longer relevant. Please file a new issue if necessary.
