### ISSUE TITLE
Documentation in PDF

### ISSUE THREAD

**Issue by eximius313** [gradle/gradle#2012]
Some people (me including) when starting with a new tool, prefer to read documentation from start to the end. PDF is convenient way to do it (you can even read it offline). Wicket is a great example how to do it well: https://wicket.apache.org/learn/#guide and I think it should be an option for Gradle as well.

**Comment by bmuschko** [comment]
Gradle does provide a [PDF version of the user guide](https://docs.gradle.org/current/userguide/userguide.pdf) though it doesn't seem to be linked anymore on the web page. I'll forward that information to get it fixed.

**Comment by eximius313** [comment]
thanks
