### ISSUE TITLE
Configuration cache should report problems when dehydrating `Closure`s

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#20126]
The configuration cache currently discards any delegate, owner and `this` objects attached to `Closure`'s, since this behavior is not safe and can cause problems when restoring from the cache, a problem should be reported.

**Comment by eskatos** [comment]
A good example report of the current confusing behaviour can be found in https://github.com/gradle/gradle/issues/20126

**Comment by adammurdoch** [comment]
It probably shouldn't discard these things, but instead attempt to serialize them in the usual way and report any issues discovered. If these objects can be successfully serialized, then all is good and the closure can be dehydrated. If the closure references something that cannot be serialized (a script object for example) then treat this as a regular problem.

**Comment by adammurdoch** [comment]
Some improvements to error handling for Groovy closures in https://github.com/gradle/gradle/pull/22843

**Comment by bamboo** [comment]
Fixed via #22843.
