### ISSUE TITLE
Remove the noisy and unactionable warning "Unsupported Kotlin plugin version"

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#20132]
For many months I've seen this message in the log messages during a Gradle execution

```
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.5.31` that might work differently than in the requested version `1.6.10`.
```

There are several problems with this message.

1. It's undocumented. Unlike [some errors](https://github.com/gradle/gradle/blob/0c88b5ba8be8f1c2486743c35ed84f2301cba28e/subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/validation/ValidationMessageCheckerTest.groovy#L72) there's no official documentation on what the problem is. Search results are filled with hacky workarounds that don't properly describe the root cause or how to fix it.
2. It's non-actionable. What am I, a Gradle user, supposed to do with this error? I'm not writing plugins or crafting build scripts. I just run `./gradlew build`. 
3. It's non-specific. What exactly is going on? What's the problem? Where? When? Who is the warning for? Plugin authors? Or general users? Does it _always_ need to be displayed? Why isn't it only shown when relevant? 
4. What does the warning mean? Does 'unsupported' mean 'not blessed by the Gradle maintainers, use at your own risk'? Or it's unsupported for technical or legal reasons? What are the potential consequences?
5. It doesn't seem to describe an actual problem. I've never seen any consequence of this error message. So what if the Kotlin plugin version is unsupported? It doesn't seem to cause any problems. What am I being warned about? What's the danger?

### Expected Behavior

Either the error is made useful and actionable, or it is removed.

### Current Behavior

Whenever I perform any Gradle action, this warning message is logged.

```
WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.5.31` that might work differently than in the requested version `1.6.10`.
```

### Your Environment

Currently, Gradle 7.4 and Kotlin 1.6.10

### See also 

* https://github.com/gradle/gradle/issues/17016
* https://github.com/gradle/gradle/issues/16779
* https://github.com/gradle/gradle/issues/13020
* https://github.com/gradle/gradle/issues/10223
* https://github.com/gradle/gradle/issues/7666
* https://github.com/gradle/gradle/issues/22647

**Comment by jbartok** [comment]
Not sure if this helps or is needed, but I've encountered this warning by running `gw :test-kit:embeddedIntegTest --tests "org.gradle.kotlin.dsl.caching.BuildCacheIntegrationTest"` on `gradle/gradle` (master).

**Comment by kazemcodes** [comment]
still getting this issue in kotlin 1.7.0 and using latest Gradle version

**Comment by shoaniki** [comment]
It's extra fun right now: apparently "the `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.8.0-RC2` that might work differently than in the requested version `1.8.0`."

I really, really hope that's not literally true!

**Comment by Tapchicoma** [comment]
Also related issue - #22647

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/13020

Please add your use case and 👍 to that issue.
