### ISSUE TITLE
 plugins.gradle.org/m2/ giving a blank page

### ISSUE THREAD

**Issue by scharanjit** [gradle/gradle#2014]
| Grails Version: 3.2.3
| Groovy Version: 2.4.7
| JVM Version: 1.8.0_121

I have below code in **build.gradle** file. 

buildscript {
	repositories {
                  mavenLocal()
                 maven { url "https://repo.grails.org/grails/core" }
		 maven { url "https://plugins.gradle.org/m2/" }
	}
        dependencies {
                 classpath  "gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:1.4.17"
    }
}

**https://plugins.gradle.org/m2/**  is returning a blank page.

I have referred this link (https://discuss.gradle.org/t/problems-with-https-plugins-gradle-org-m2/13554/2) but could get any working solution
Would deeply appreciate any help

**Comment by lacasseio** [comment]
The GitHub issues are reserved for feature request and bug. Please use the [user forum](https://discuss.gradle.org/) for any question related to Gradle usage. In the event your question does turn out to be a valid GitHub issue, please follow the [contribution guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).

I responded on [the user forum thread](https://discuss.gradle.org/t/problems-with-https-plugins-gradle-org-m2/13554/8).
