### ISSUE TITLE
publish using maven-publish resulting in shrinked pom.xml version

### ISSUE THREAD

**Issue by axet** [gradle/gradle#20142]
Hello!

Publishing my gradle plugin using maven-publish plugin to maven central repository producing shrieked pom.xml version. This shrieked version only contains artifact information and dependencies which is leading to fail publication on maven central.

Replacing maven-publish plugin with:

```
    dependencies {
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.19.0'
    }

apply plugin: "com.vanniktech.maven.publish"
``` 

Allows me to publish to maven central, since this plugin crates not filtered pom.xml.

For some reason output of maven-publish generatePomFileForPublication - is correct. Only problem with maven-publish it filter pom.xml when uploading to repository or local maven repo (looks like it also failed to update signatures, so pom file is unsigned in the result)

My projects are open source:

* https://gitlab.com/axet/gradle-android-dx

To make 'com.vanniktech.maven.publish' plugin to work update gradle.wrapper to the 7.0

You can see pom.xml here:

* https://plugins.gradle.org/m2/com/github/axet/gradle-android-dx/0.0.6/

**Comment by jbartok** [comment]
You are using the wrong publication name, it should be named `pluginMaven`.

**Comment by jbartok** [comment]
We need to improve the docs to make this clearer.

**Comment by axet** [comment]
Thanks!

Replacing 'mavenJava' with 'pluginMaven' causing following error:

"Maven publication 'pluginMaven' cannot include multiple components"

My guess gradle publish two components for:

/home/axet/.m2/repository/com/github/axet/dxplugin/com.github.axet.dxplugin.gradle.plugin/0.1.1

and

/home/axet/.m2/repository/com/github/axet/gradle-android-dx/0.1.1

I'm afraid moving to one component will affect 'gradle publishGradle' and will prevent it to work'? Can booth repositories to work gradle plugin repo and maven central at the same time?

**Comment by ljacomet** [comment]
The plugin takes care of the setup, only handle the `pom` part and it should be good.

As for the publication: `publish` should take care of the publication to repositories of your choice. You might need to enhance the plugin marker POM as well for Maven Central. And `publishPlugins` will take care of the portal publication.
Both will end up relying on the configured publications.

**Comment by axet** [comment]
Here is an explanation. Looks like documentation need to be updated, and some how fixing pom.xml overwriting without updating asc.

Correct upload command is:

`./gradlew publishMavenJavaPublicationToMavenLocal publishMavenJavaPublicationToMavenRepository`

* https://discuss.gradle.org/t/maven-publish-does-not-create-full-features-pom-xml/42395/6

**Comment by jbartok** [comment]
Linked PR will enhance the `java-gradle-plugin` documentation, clearly describing the Maven publications it generates (when used together with the `maven-publish` plugin).
