### ISSUE TITLE
Add ability to disable caching of transforms in Gradle

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#20152]
When a transform fails to upload to the remote build cache for whatever reason, caching for transforms and Gradle tasks is disabled for the rest of the build.

An example: `413: Request Entity Too Large` when a transform produces a very large output would cause the remote build cache to be disabled for the rest of the build.

### Request
Add an API similar to what one would do with a Gradle task: `outputs.cacheIf { false }` in order to disable caching of the transform.

**Comment by lptr** [comment]
How would this method be called? How would you select which transforms you'd want to disable caching for? Can you give an example?

**Comment by runningcode** [comment]
I don't know all the specifics but maybe it could be called `cacheIf { false }` just like the method for Gradle tasks.

Without any visibility in to transforms in builds scans I would simply disable the transform which caused the entity too large exception which I would see in the logs. Once transforms appear in build scans, I would disable all those which are more disk based transforms and take longer to retrieve from the cache than to re-execute.

**Comment by lptr** [comment]
Transforms don't have the same sort of IDs as tasks. With tasks, you can do `tasks.named("lajos").outputs.cacheif { false }` or `tasks.withType(JavaCompile) { outputs.cacheIf { false } }` but there are no equivalents for transforms. E.g. we don't have `transforms.withType()` nor do have transforms have names the way tasks have. So the question is still how you'd imagine explaining to Gradle which transforms to not cache.

**Comment by lptr** [comment]
Considering our plans with fixing negative savings by speculative execution in the foreseeable future, do you think we can put this away and check if we still need it once we have that feature?

**Comment by runningcode** [comment]
Sounds good to me! Thanks
