### ISSUE TITLE
`gradle init` is skipped after generating one project with the configuration cache enabled

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#20156]
If you have the configuration cache enabled and generate a project with `gradle init`, you cannot generate another project (even in another directory) until you disable configuration caching or delete the first project.

### Expected Behavior

You should be able to run `gradle init` many times with the configuration cache enabled.

### Current Behavior

You can only run `gradle init` once if configuration cache is enabled unless you delete the first project generated.

### Context

The reproducer below uses `--configuration-cache`, but this was found because @tresat had the configuration cache enabled in his ~/.gradle/gradle.properties.

This was reproduced with 7.3 and 7.4, but not 7.2.

If you look at the `--debug` output from the build, it looks like the configuration cache is using `~/.gradle/undefined-build` as the project cache dir and this gets shared across all builds.

### Steps to Reproduce 

This script will reproduce the problem:
```
#!/bin/sh

rm -rf first second

mkdir first
mkdir second

echo ">>>> creating the first project"
cd first
gradle --configuration-cache init --type basic </dev/null

echo ">>>> creating the second project, init will be skipped, but it shouldn't"
cd ../second
gradle --configuration-cache init --type basic </dev/null

echo ">>>> clearing the first project, and rerunning init in second works now"
rm -rf ../first
gradle --configuration-cache init --type basic </dev/null
```

**Comment by abstratt** [comment]
For a simple fix, suggested this: https://github.com/gradle/gradle/issues/22188#issuecomment-1257897243
