### ISSUE TITLE
Signing plugin only signs the first File artefact when they have the same name.

### ISSUE THREAD

**Issue by davidjlynn** [gradle/gradle#20166]
When publishing, it is possible to add arbitrary files which should be published, this can be done by path, and these files then get published to maven local.

These files can be differentiated by providing the "classifier" and "extension" information to the publication.

However, the signing plugin is intended to sign all files in a publication. When this is applied, only the first publication by a certain file name will be signed. This does not seem like intended behaviour.

### Expected Behavior
The signing plugin signs all files in the publication.

### Current Behavior
The signing plugin only signs the first file with a certain filename.

### Context

While trying to publish to Maven Central, all files need to be signed.
This bug meant that following the default publication steps the artefacts could not be published.

Please note that this can be worked around by renaming files, for example I worked around this bug using the following task:
```
// A strange issue with signing meant that only the first files (with the same name) got signed.
// To workaround this, rename all executables to include architecture.
tasks.register('flattenDistDirectory', Copy) {
  from("$projectDir/dist") {
    include "**/test"
    include "**/test.txt"
    eachFile { file ->
      file.name = file.relativePath.parent.lastName
      file.relativePath = new RelativePath(true, file.relativePath.segments.drop(1))
    }
    includeEmptyDirs = false  
  }
  into "$buildDir/dist"
}

publish.dependsOn flattenDistDirectory
signMavenPublication.mustRunAfter flattenDistDirectory 
```
However this workaround should really not be needed.

### Steps to Reproduce 
I created a simple demo here:
https://github.com/davidjlynn/gradle-signing-fail-example

I tested this by providing my GPG keys and running `./gradlew publishToMavenLocal`.
The resulting files were:
```
tree /f
Folder PATH listing
C:.
└───gradle-snapshot-fail-example
    │   maven-metadata-local.xml
    │
    └───0.0.1
            gradle-snapshot-fail-example-0.0.1-base.txt
            gradle-snapshot-fail-example-0.0.1-base.txt.asc
            gradle-snapshot-fail-example-0.0.1-fail.txt
            gradle-snapshot-fail-example-0.0.1-pass.txt
            gradle-snapshot-fail-example-0.0.1-pass.txt.asc
            gradle-snapshot-fail-example-0.0.1.pom
            gradle-snapshot-fail-example-0.0.1.pom.asc
```
Notice the missing .asc file for `gradle-snapshot-fail-example-0.0.1-fail.txt`

### Your Environment

Build scan URL:

**Comment by hegyibalint** [comment]
Found the culprit:
https://github.com/gradle/gradle/blob/d5e521483f43c5b0132c3bd3159395d2aac00bec/subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java#L228-L233

The signature generation takes a "sanitized" input. The only problem is that the mentioned `toKey` method does not take the file path into account here:
https://github.com/gradle/gradle/blob/d5e521483f43c5b0132c3bd3159395d2aac00bec/subprojects/signing/src/main/java/org/gradle/plugins/signing/Signature.java#L400-L402

I'm thinking if we need this method at all...
