### ISSUE TITLE
Document how dependency versions are ordered

### ISSUE THREAD

**Issue by ilya-g** [gradle/gradle#2017]
Gradle reference has a section about resolving dependency version conflicts. https://docs.gradle.org/current/userguide/dependency_management.html#sub:version_conflicts

One of  the resolution strategies is _newest_:
> Newest: The newest version of the dependency is used. This is Gradle's default strategy, and is often an appropriate choice as long as versions are backwards-compatible.

That imposes that there is some order on versions, that is used to determine which version is newest. Please document how that order is established.

### Context

I'm trying to select appropriate versioning scheme for my maven artifacts. Maven provides the [reference](https://cwiki.apache.org/confluence/display/MAVENOLD/Versioning) how it compares versions and gradle doesn't.

**Comment by bmuschko** [comment]
Thanks for raising it. In fact in most can I found it be self-explanatory especially when it comes down to semantic versioning. Do you have concrete use case that you are unclear about?

Either way I think it would be great if we could get this documented? Would you be interested in providing a pull request for this?

**Comment by ilya-g** [comment]
Some of questions that should be addressed:
- how do different delimiters affect the precedence, e.g. which is greater: `1.1-2.3` or `1.1.2-3`
- missing components padding: is `1.0.0` equal to `1.0` (as in maven)
- how mixed alphanumeric components are compared, like `1.1-M9` and `1.1-M10`
- do some version components have special meaning and precedence: `dev`, `alpha`, `beta`, `rc`, `SNAPSHOT` and so on

>self-explanatory especially when it comes down to semantic versioning

I suspect there could be some differences between the [semver](http://semver.org/#spec-item-11) version precedence and gradle's one, would be also nice to highlight them.

**Comment by bigdaz** [comment]
Here's the sort of confusion that results from our current version ordering: https://github.com/gradle/gradle/issues/1872

**Comment by bigdaz** [comment]
@ilya-g I've pushed some improvements to the docs, that address your specific questions: 489524e3693b542abc4280a4e70a0e5467dd831c
Thanks for your feedback.

**Comment by svermeulen** [comment]
I wish gradle would have just matched maven's way of comparing versions, which IMO is a lot more intuitive.  For example, with maven:

```
4.1.0-alpha.7 < 4.1.0-alpha.7-branch.Foo
0.2.0-alpha.16 < 0.2.0-alpha.16-branch.Foo1
1.0.0-alpha.55 < 1.0.0-SNAPSHOT
```

But with gradle, it's the opposite for each of these.
