### ISSUE TITLE
Add "threads" configuration option to PmdExtension

### ISSUE THREAD

**Issue by DavidOpDeBeeck** [gradle/gradle#20178]
Currently it is not possible to configure the amount of threads that are used by the PMD process. The `threads` configuration option is already supported in the [PMD CLI documentation](https://pmd.github.io/pmd/pmd_userdocs_cli_reference.html) and the [PMDTask class](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/ant/PMDTask.java).

### Expected Behavior
Multi threaded performance when running the PMD task on large sourceSets.

### Current Behavior
Single threaded performance when running the PMD task on large sourceSets.

### Context
We see a worse performance when running the PMD task for large sourcesets. The `threads` configuration option is already present in the PMD library, so this change would be minimal in complexity.

### Proposed change

Adding a new field `int threads` to [PmdExtension.java](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdExtension.java) and adding a mapping from the new field to the `antPmdArgs` in [PmdInvoker.groovy](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy)

**Comment by ljacomet** [comment]
This could be a nice contribution to Gradle indeed. However the added API should be [a `Property`](https://docs.gradle.org/7.4.1/userguide/lazy_configuration.html#lazy_properties).
