### ISSUE TITLE
Failed to calculate the value of task ':lib-common:compileDebugJavaWithJavac' property 'options.generatedSourceOutputDirectory'.

### ISSUE THREAD

**Issue by wangdaqi77** [gradle/gradle#20199]
### Expected Behavior
Let the task execute successfully

### Current Behavior
Failed

### Steps to Reproduce 
https://github.com/wangdaqi77/P2M/tree/adapt_AGP7.0/example

./gradlew clean assembleDebug -s -i

```
Execution failed for task ':lib-common:compileDebugJavaWithJavac'.Failed to calculate the value of task ':lib-common:compileDebugJavaWithJavac' property 'options.generatedSourceOutputDirectory'. > Querying the mapped value of map(java.io.File property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, /Users/wongki/AndroidStudioProjects/P2M/example/lib-common/build/generated/ap_generated_sources/debug/out)) org.gradle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@7d9cb9cf) before task ':lib-common:compileDebugJavaWithJavac' has completed is not supported
```

not actively fetching `options.generatedSourceOutputDirectory` in place，but running the task is failing

### Your Environment
Gradle 7.4,**Android Gradle plugin 7.1.2**,Kotlin 1.5.21,macOS 10.14.6 (18G87)
Build scan URL:https://scans.gradle.com/s/f7bcx5rnry2ws

**Comment by thang510023** [comment]
@wangdaqi77 Can you tell me how to fix it?
