### ISSUE TITLE
Add CACHEDIR.TAGs to all cache directories

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#20209]
### Expected Behavior
Gradle should indicate which directories are caches for other tools using the [CACHEDIR.TAG specification](https://bford.info/cachedir/). This is supported by many tools to avoid indexing, backing up, or searching in cache directories.

### Current Behavior
No way for a tool to know if a directory, e.g. `build`, `~/.gradle/caches`, or `.gradle` is a cache dir. This can be manually specified, but it is hard to generically exclude `build` as that is a legitimate package name that could be used.

### Context
My backup software often backs up the contents of `build` or `.gradle` in its default configuration since it doesn't know that it shouldn't. This results in multiple GB of unneeded content in my backups.

**Comment by DPUkyle** [comment]
Will macOS support this spec? Seems like [maybe not](https://app.bountysource.com/issues/92822906-mark-temporary-directories-as-excluded-from-macos-spotlight)...

**Comment by big-guy** [comment]
ref https://github.com/borgbackup/borg/issues/641

**Comment by octylFractal** [comment]
Closing as #21444 was merged, the rest of the directories to mark are tracked in #23692.
