### ISSUE TITLE
Using a Version Catalog plugin in the `plugins` block still produces an `@Incubating` warning in 7.4.1

### ISSUE THREAD

**Issue by EdricChan03** [gradle/gradle#20203]
### Expected Behavior

A plugin defined in a Version Catalog should not produce an incubating feature warning when used in the `plugins { }` block.

### Current Behavior

An incubating feature warning is produced:

```
'alias(org.gradle.api.provider.Provider<org.gradle.plugin.use.PluginDependency>)' is unstable because its signature references unstable interface 'org.gradle.plugin.use.PluginDependency' marked with @Incubating 
```

![Warning when using Version Catalog plugin in `plugins` block](https://user-images.githubusercontent.com/20047125/158829613-635b2a73-d275-46d2-a28e-f49ac4b89e8b.png)

### Context

The Version Catalogs feature was [promoted to a stable feature in 7.4.0](https://docs.gradle.org/7.4.1/release-notes.html#promoted-features), and an additional fix was pushed to address any existing incubating warnings to do with Version Catalogs, especially when used with the `plugins` block (#19940). However, the underlying `PluginDependency.java` class used for declaring plugins is still annotated with the `@Incubating` annotation:

https://github.com/gradle/gradle/blob/d5e521483f43c5b0132c3bd3159395d2aac00bec/subprojects/core-api/src/main/java/org/gradle/plugin/use/PluginDependency.java#L26-L27

### Steps to Reproduce 

1. Create a new Gradle project.
2. Set the Gradle wrapper version (in `gradle/wrapper/gradle-wrapper.properties`) to 7.4.1:
    ```properties
    distributionBase=GRADLE_USER_HOME
    distributionPath=wrapper/dists
    distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.1-bin.zip
    zipStoreBase=GRADLE_USER_HOME
    zipStorePath=wrapper/dists
    ```
3. Create a Version Catalogs TOML file (`gradle/libs.versions.toml`) with the following contents:
    ```toml
    [plugins]
    gradleVersions = "com.github.ben-manes.versions:0.42.0"
    gradleVersions-catalog = "nl.littlerobots.version-catalog-update:0.3.1"
    ```
4. In the `build.gradle.kts` file, insert the following:
    ```kts
    @Suppress("DSL_SCOPE_VIOLATION")
    plugins {
        alias(libs.plugins.gradleVersions)
        alias(libs.plugins.gradleVersions.catalog)
    }
    ```
5. `alias` should be marked as yellow in the IDE, with the following warning:

    ![Reproduction of `alias` warning](https://user-images.githubusercontent.com/20047125/158829929-7baeda8f-d080-47fd-a138-2d2af9d18cdf.png)

### Your Environment

Build scan URL: (N/A)

#### IDE
Android Studio Chipmunk | 2021.2.1 Beta 4
Build #AI-212.5712.43.2112.8233820, built on March 1, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true, documentation.show.toolbar=true
Non-Bundled Plugins: com.wakatime.intellij.plugin (13.1.14)

**Comment by ljacomet** [comment]
`PluginDependency` should have been promoted stable indeed.

**Comment by jakoss** [comment]
And what about the `DSL_SCOPE_VIOLATION`? Can we get rid of that too?

**Comment by ljacomet** [comment]
The `DSL_SCOPE_VIOLATION` is to be fixed by the IDE side unless I am missing something.

For the remaining incubating APIs: the whole `dependencyResolutionManagement` block is still incubating. We will most likely lift that in 8.0 but not before.
