### ISSUE TITLE
Download source file wrong when resolve eclipseClassPath when has classifier

### ISSUE THREAD

**Issue by chdw** [gradle/gradle#2020]
apply plugin: 'java'
apply plugin: 'eclipse'
repositories {
	mavenCentral()
}

dependencies {
	compile (
			'net.sf.json-lib:json-lib:2.4:jdk15'
	)
}

When try to run gradle eclipseClasspath

Gradle download json-lib-2.4-jdk15.jar OK
But will not download json-lib-2.4-jdk15-source.jar.

It seem gradle try to download json-lib-2.4-source.jar which is wrong name

**Comment by bmuschko** [comment]
This is likely a bug where we don't use the classifier for resolving the corresponding sources JAR file. Would you be interested in providing a fix for it?
