### ISSUE TITLE
Allow control of log level, console from init scripts

### ISSUE THREAD

**Issue by adrian-skybaker** [gradle/gradle#20214]
We have a "CI" init script that we put into the `USER_HOME/.gradle/init.d/` folder. As well as a few other things it does, there are several important settings it cannot currently control, specifically:

- Set `--info` for CI builds (but not locally)
- Force `--console=plain` on CI builds, because sometimes they mistakenly use rich output
- Enable `--stacktrace` in CI builds (but not locally).

Worse, attempting to set these is entirely allowed and documented in the [API](https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html), but these calls are silently ignored.

Resorting to setting these using command line flags across multiple gradle invocations is painful at best, and in some cases impossible (for example when gradle is invoked indirectly via other tools both locally and on build servers, my current example is AWS CDK).

Using `gradle.properties` instead of an init script for this is also painful for several reasons:
- you end up with a mixture of CI specific behaviour spread across init scripts and gradle.properties, and your CI builds have to arrange the application of both.
- there's no equivalent of the `$USER_HOME/.gradle/init.d/` for gradle.properties. This means you have to pick between some fiddly and not-great options:
  1. concat your CI properties onto the current project `gradle.properties` (or create if it doesn't exist), which can cause issues as it will mark your local git checkout as dirty (eg in the past I've generated semver version qualifiers based on git status and tags).
  2. concat your CI properties into `$GRADLE_USER_HOME/gradle.properties` (or create if it doesn't exist), which will creates possibility you are repeatedly modifying and leaving dirty a shared file with duplicate or conflicting config.

Any initial concat command often forgets some `gradle.properties` files don't end with carriage returns.

All of this pollutes builds with somewhat tedious non-portable scripting that is normally best folded into gradle, but cannot be.

See also:
- https://github.com/gradle/gradle/issues/3844
- https://stackoverflow.com/questions/29977196/how-can-i-make-gradle-stacktrace-the-default
- https://stackoverflow.com/a/19686585/5473824

**Comment by ljacomet** [comment]
The main issue here is that these flags are evaluated very early in the life of the Gradle daemon. As such, an init script is already too late. And there is also the case of running without a daemon.

The fact that `StartParameter` is mutable is a inheritance from the past and is indeed misleading as most of the changes are not honored if done too late in the lifecycle of the build.

So `gradle.properties` or environment variables through `GRADLE_OPTS` are your best options.

There is no plan on providing ways for init scripts to control those properties.

**Comment by adrian-skybaker** [comment]
Thanks for the clarification.

>There is no plan on providing ways for init scripts to control those properties.

In that case, would it not then make sense to:
1. Deprecate the mutable subset of the `StartParameter` API.
2. Document the limitation in https://docs.gradle.org/current/userguide/init_scripts.html (the current doc, or at least my reading of it, leads you towards thinking that an init-script is the right place to control these aspects, and the API leads you towards thinking it's possible).

Also, to better support injecting CI-specific `gradle.properties`, what about supporting a set of these in the `USER_HOME/.gradle/init.d/` directoy, similar to how multiple init-scripts can be injected this way? This would make it simpler to inject a fixed CI-specific set of properties, without having to pick an existing properties location to try and merge with.

**Comment by ljacomet** [comment]
Both these points are valid, added a reference to a more general issue talking about disabling mutations of `startParameter`
