### ISSUE TITLE
Toolchain not using latest minor version if older minor is currently in use

### ISSUE THREAD

**Issue by at055612** [gradle/gradle#20228]
The following JDKs are installed via SDKMan
Temurin 17.0.1
Temurin 17.0.2
OpenJDK 15.0.2
Zulu 15.0.2

17.0.1 is in use (`sdk use java 17.0.1`).  When gradle runs it selects 17.0.1 for compilation rather than 17.0.2 for a languageVersion of `17`.

If however 15.0.2-zulu is in use (`sdk use java 15.0.2-zulu`) Gradle correctly uses 17.0.2 for compilation.

### Expected Behavior
Gradle should use the latest minor version of 17 given that both 17 JDKs are from the same vendor (as I understand it from the docs).

### Current Behavior
Gradle is using 17.0.1 instead of 17.0.2 when 17.0.1 is the in-use JDK.

### Context
I was changing our build to use toolchain but wanted some certainty that it was using the JDK version I would expect.

Incidentally is there a neater/easier way to output the JDK that toolchain has selected?  It would be nice to have some output of which JDK gradle has selected.

### Steps to Reproduce 
[toolchain_bug.zip](https://github.com/gradle/gradle/files/8315539/toolchain_bug.zip)

The above project was created using `gradle init` for a java application project and then `gradle wrapper --gradle-version 7.4.1`
```
sdk install java 17.0.1-tem
sdk install java 17.0.2-tem
sdk use java 17.0.1-tem
unzip toolchain_bug.zip
cd toolchain_bug
./gradlew clean compileJava
```
When I run it, it outputs
```
------------------------------------------
/home/dev/.sdkman/candidates/java/17.0.1-tem
------------------------------------------
```
but I would expect it to output `.....17.0.2-tem`.

Change to using 15 as the active JDK and it works fine:
```
sdk use java 15.0.2-zulu
./gradlew clean compileJava
```
which outputs
```
------------------------------------------
/home/dev/.sdkman/candidates/java/17.0.2-tem
------------------------------------------
```

### Your Environment
```
./gradlew -q javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + Eclipse Temurin JDK 17.0.1+12
     | Location:           /home/dev/.sdkman/candidates/java/17.0.1-tem
     | Language Version:   17
     | Vendor:             Eclipse Temurin
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM

 + Eclipse Temurin JDK 17.0.2+8
     | Location:           /home/dev/.sdkman/candidates/java/17.0.2-tem
     | Language Version:   17
     | Vendor:             Eclipse Temurin
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        SDKMAN!

 + OpenJDK 15.0.2+7-27
     | Location:           /home/dev/.sdkman/candidates/java/15.0.2-open
     | Language Version:   15
     | Vendor:             Oracle
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        SDKMAN!

 + Zulu JDK 15.0.2+7
     | Location:           /home/dev/.sdkman/candidates/java/15.0.2-zulu
     | Language Version:   15
     | Vendor:             Zulu
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        SDKMAN!
```

**Comment by donat** [comment]
This is by design. The relevant section of the [docs](https://docs.gradle.org/current/userguide/toolchains.html#sec:precedence) says:

> Precedence
> 
> Gradle will sort all the JDK/JRE installations matching the toolchain specification of the build and will pick the first one. > Sorting is done based on the following rules:
> 
>   1. the installation currently running Gradle is preferred over any other

**Comment by at055612** [comment]
Apologies, I had looked at that page in the docs but must have missed that line.  Thanks for the response.
