### ISSUE TITLE
Correct URL for maven-metadata.xml file when using maven publication plugin to push to codeartifact

### ISSUE THREAD

**Issue by FlightToFreedom** [gradle/gradle#20239]
### Expected Behavior
The plugin should create a URL for the maven-metadata.xml which contains the artifact version specified in the repository, this happens correctly for the artifact and the pom.xml file
### Current Behavior
For the maven-metadata.xml the plugin creates a URL which does not include the artifact version, as a consequence, AWS codeartifact will respond with a 400 Bad Request
### Context
Although the specified artifact and pom.xml file are uploaded correctly, the task fails, so i get a red build on Jenkins.

### Steps to Reproduce 
Define a publishin task:
```
publishing {
  publications {
    publicMyArtifact(MavenPublication) {
      def branchName = System.getenv('BRANCH_NAME')
      if(!branchName)
        branchName = 'local'
      def buildNumber = System.getenv('BUILD_NUMBER')
      if(!buildNumber)
        buildNumber = '-'
      groupId = 'com.company.project'
      artifactId = 'my-artifact.jar'
      version = 'v1'
      from components.java
      artifacts = ['build/libs/my-artifact.jar']
    }
  }
}
```
Define the repository:
```
 maven {
          name 'codeartifactRelease'
          url 'https://my-AWSaccount.d.codeartifact.us-east-1.amazonaws.com/maven/project/module/submodule'
          credentials {
            username = 'aws'
            password = System.getenv('CODEARTIFACT_AUTH_TOKEN')
          }
        }
```
Invoke the task:
```
  sh "./gradlew -i --full-stacktrace :publishPublicMyArtifactPublicationToCodeartifactReleaseRepository"
  
```
For the pom.xml and the artifact we will get the URL:
`https://my-AWSaccount.d.codeartifact.us-east-1.amazonaws.com/maven/project/module/submodule/com/company/project/submodule/my-artifact.jar/v1/myartifact.jar-v1.pom
`
But for the maven-metadata.xml we will get:
`https://my-AWSaccount.d.codeartifact.us-east-1.amazonaws.com/maven/project/module/submodule/com/company/project/submodule/my-artifact.jar/myartifact.jar-v1.pom
`
The version is missing causing codeartifact to reject the request.
### Your Environment
My build is running on a Java-8 node on Jenkins.
Java version: 8
Gradle version: 7.2
Some informations have been hidden due privacy reasons but i hope the explanation of the problem is clear.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle.

This behaviour is expected and matches [the Maven layout](https://cwiki.apache.org/confluence/display/MAVENOLD/Repository+Metadata). `maven-metadata.xml` is not per version but per `<groupId>:<artifactId>`.
A publisher is supposed to download that file, update it and upload it again with the just published version information.

You will have to figure out how to allow this on the repository you are publishing to.
