### ISSUE TITLE
Consider removing the deprecation on catalog names

### ISSUE THREAD

**Issue by melix** [gradle/gradle#20243]
### Expected Behavior

Users should be able to declare whatever name they prefer for catalogs. 

### Current Behavior

Currently, if the name doesn't end with `Libs`, Gradle emits a deprecation warning: https://ge.micronaut.io/s/zoa7cpf3aejqy/deprecations#16

### Context

The documentation for the deprecation states:

> Each catalog will generate an extension applied to all projects for accessing its content. As such it makes sense to reduce the chance of collisions by picking a name that reduces the potential conflicts. Gradle will emit a deprecation warning if a catalog does not have a name that ends with Libs.

However I would argue that this is true for _any_ extension, for _any_ plugin, not just catalogs. There are always risks of collision. Moreover, this is counterintuitive, since it requires users to `create` or `register` with a `String` which will always end up with `Libs`. This is not user-friendly. In addition, this deprecation will require changing a lot of build files for something which is passing today, and would still pass tomorrow.

While I can understand the intent, I think deprecating is _not_ the right solution: it would be better to detect name clashes and _warn_ the user instead. There's no reason, IMHO, to prevent the users from using a name they think is fit "just in case".

Thank you!

**Comment by melix** [comment]
Did you have a chance to discuss this? I'm getting regular deprecation which sound pretty arbitrary: https://ge.micronaut.io/s/7vuyvrw3oyj36/deprecations#0

**Comment by melix** [comment]
ping :)

**Comment by melix** [comment]
@ljacomet we're seeing this error in many projects. This deprecation would break most of our Micronaut builds when moving to 8: https://ge.micronaut.io/s/t6fmw6qmjrubo/deprecations?expanded=WyIzIl0&expanded-stacktrace=WyI1Il0#4

**Comment by melix** [comment]
@ljacomet sorry to insist but we need visibility on this one. Will this really break in 8?

**Comment by ljacomet** [comment]
Let me get a confirmation from the team about what we do in 8.0 for this.

**Comment by melix** [comment]
Great, thank you!
