### ISSUE TITLE
Dependency Catalog: Sources JARs

### ISSUE THREAD

**Issue by thahnen** [gradle/gradle#20242]
I'd like the Gradle TOML syntax to be able to parse sources JAR files often uploaded to Maven Nexus alongside the actual artifact JAR.
E.g. when generating Eclipse files from artifacts a sources JAR is quite neat for accessing the actual build logic without JIT decompilation.

On another occasion we needed the actual sources JAR in our build process for evaluation.

I found nothing in the Gradle documentation or similar issues searched by me (2k open issues is a mess).

### Expected Behavior

Add the ability to add sources JARs in dependency catalog like the following sample based on GSON library:
> gson = { module = "com.google.code.gson:gson", version = "2.9.0" }
> gson-sources = { module = "com.google.code.gson:gson:sources", version = "2.9.0" }

And in build.gradle:
> dependencies {
>   implementation libs.gson
>   runtimeOnly libs.gson.sources
> }

### Current Behavior

This is not possible, you can define the actual artifact in the TOML as usual but not the sources JAR:
> gson = { module = "com.google.code.gson:gson", version = "2.9.0" }

And in build.gradle
> dependencies {
>   implementation libs.gson
>   runtimeOnly "com.google.code.gson:gson:2.9.0:sources"
> }

### Context

A workaround I considered is to link myself in the dependency resolution. I actually don't know how, so this is just theoretic: When the dependency is evaluated I try to check if there is something available what looks like a sources JAR and include it using the same method (implementation, runtimeOnly, testImplementation, ...) as well.

If this feature won't be done, I'd only ask for somebody to help me with my workaround 😄

**Comment by donat** [comment]
We've discussed this option before and the conclusion was that the version catalog will not support selecting variants. If you are interested, check out the discussion at #20074.

**Comment by thahnen** [comment]
Thank you for that! As I understand it, it is a definite design decision, sad but true 😢 

Meaning: I have to create a plugin for that (if it is even possible) ...
If you have any further information regarding this topic, please let me know 😃
