### ISSUE TITLE
Groovy enums parsing using GroovyRecognizer

### ISSUE THREAD

**Issue by KeyrisXdSnow** [gradle/gradle#20244]
Hello team,
We recently upgraded to gradle version 7.4.1 and ran into problem with parsing groovy enums.

Environment:

- Java SDK 11
- Gradle 7.4.1
- Groovy 2.5.15 ( This is version of our project, but parser and all the required entities are imported from gradle -> groovy 3.0.9)

We try parse groovy enums using GroovyRecognizer. Groovy code:

```
SourceBuffer sourceBuffer = new SourceBuffer()
UnicodeEscapingReader unicodeReader = new UnicodeEscapingReader(new StringReader(‘ExampleEnum.groovy'), sourceBuffer)
GroovyLexer lexer = new GroovyLexer(unicodeReader)
unicodeReader.setLexer(lexer)
parser = GroovyRecognizer.make(lexer)
parser.setSourceBuffer(sourceBuffer)
parser.compilationUnit()

```

Enum example:

```
@API
public enum ExampleEnum implements Serializable {
	@API
	ITEM1(1),
	@API
	ITEM2(2),
	@API
	ITEM3(3);
	
	private Integer value;

	public TaggableClasses(Integer value) {
		this.value = value;
	}

	public Integer getValue() {
		return this.value;
}	
```

.compilationUnit() method throws an exception "Parsing failed for 'ExampleEnum.groovy' due to: unexpected token: 2"
Token is value of ITEM2.
Groovy class and interfaces parsing work correctly.

Could you please advise how we can solve this problem?
Thanks.

**Comment by donat** [comment]
Is this happening in the context of Gradle scripts (i.e. Gradle plugins, build scripts, init scrits, etc), or is it a Groovy problem in a project that happens to be built with Gradle?

For the latter, we'll probably need to ask you to report it on the Groovy issue tracker. Nonetheless, please provide a minimal reproducer. project

**Comment by KeyrisXdSnow** [comment]
We are trying to use this functionality in plugins. But you can reproduce it any way you like.

I created a test project that reproduces the issue.
https://github.com/KeyrisXdSnow/GradleReproducer.git
