### ISSUE TITLE
Gradle CodeNarcPlugin : codenarcClasspath property not available

### ISSUE THREAD

**Issue by sdelamo** [gradle/gradle#2025]
I am trying to add a Custom Codenarc Rule to `codenarcMain` task.

I am unable to supply the rule jar to the codenarc classpath. 

The Gradle API Docs [talk about codenarcClasspath](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CodeNarc.html#org.gradle.api.plugins.quality.CodeNarc:codenarcClasspath)):  

I've tried to add a Jar file with a custom rule to the class path as follows: 

```
apply plugin: 'codenarc' 

codenarc {
    toolVersion = '0.27.0' 
    configFile = file("${rootProject.projectDir}/config/codenarc/rules.groovy") 
    reportFormat = 'html' 
    ignoreFailures = true
	codenarcClasspath += file("${rootProject.projectDir}/codenarc-rule/build/libs/codenarc-rule.jar") 
}
```

Apparently `codenarcClasspath`property is not accesible
```
$ ./gradlew app:codenarcMain
Cannot resolve reloading agent JAR: Could not resolve all dependencies for configuration ':app:agent'.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sdelamo/git/grailsguides/grails-codenarc/complete/gradle/codenarc.gradle' line: 11

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'codenarcClasspath' for object of type org.gradle.api.plugins.quality.CodeNarcExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Any idea how can I pass a custom rule Jar to codenarcMain?

**Comment by jlstrater** [comment]
It looks like codenarcClasspath isn't a property on [CodenarcExtension](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeNarcExtension.java). :(

**Comment by bmuschko** [comment]
@jlstrater is right. You'll need to set the property on the task.

```
tasks.withType(CodeNarc) {
    codenarcClasspath = ...
}
```

**Comment by bmuschko** [comment]
I think we can close the issue. Please reopen if you still see an issue.
