### ISSUE TITLE
app:mapDebugSourceSetPaths failed when used with gradle 7.4.1 and Firebase implemented Android App Project 

### ISSUE THREAD

**Issue by freindlytech** [gradle/gradle#20253]
![Screenshot_20220323-015627](https://user-images.githubusercontent.com/94637042/159627781-5f7575ed-8c22-47e5-a76a-3a190549f910.png)

Can you fix it bro it only occurs in gradle 7.4.1  whenever I implement firebase in my app , if I didn't implement firebase in android then it will successfully build and if I use gradle 7.4 it can build with firebase too successfully with no errors.
### Expected Behavior
Gradle Will Successfully build the android app project in gradle 7.4.1 with firebase implemented in project

### Current Behavior
Gradle build is failed while running with  gradle 7.4.1 in android project with firebase implemented

### Steps to Reproduce 
Run the gradle build in project with firebase implemented and make sure to run in gradle 7.4.1

### Your Environment
 I am running it in termux app in my android phone 8.1(Oreo)
64 bit

**Comment by donat** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

**Comment by freindlytech** [comment]
> Thank you for your interest in Gradle!
> 
> This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.
> 
> Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

But if it's a issue in Android Gradle Plugin then how it is successfully working in gradle version 7.4

**Comment by freindlytech** [comment]
Ok I understand and now I will use previous aapt2 plugin maybe of 7.3.0-alpha03

**Comment by donat** [comment]
Does this mean you've found a solution to your problem?
