### ISSUE TITLE
Introduce `kotlin-gradle-plugin` for plugin development in Kotlin

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#20270]
Gradle plugin development is already possible using the `kotlin-dsl` plugin. But its historical name makes it confusing now that Gradle has `java-gradle-plugin` and `groovy-gradle-plugin` for Java or Groovy plugin development.

Initially the plugin would simply apply `kotlin-dsl` but could at some point fully replace it.

**Comment by 3flex** [comment]
I built plugins with kotlin-dsl in the past but it affected backwards compatibility as there were functions added in newer versions that meant the plugin wouldn't work on older Gradle versions.

Granted this isn't unique to usage of kotlin-dsl plugin, as this issue can come about when building plugins that are then run on older Gradle versions when the plugin uses kotlin-stdlib for example, but it will be another thing to remember when doing plugin dev.

As far as I know there's no officially supported way to build a plugin for older Gradle versions when the plugin uses an older Gradle version e.g. using Gradle 7 for the build while limiting the plugin API usage to Gradle 6 APIs. It would be great to have a solution for this.

**Comment by ljacomet** [comment]
@3flex This is indeed a problem we want to solve, but not in the context of this issue.

Regarding the idea described, there are some complicating factors:
* `kotlin-gradle-plugin` as a plugin ID would end up being confusing with the Kotlin Gradle plugins done by Jetbrains which are about developing Kotlin code built with Gradle. We could solve this by coming up with a convention for naming the plugins for developing Gradle plugins in a consistent way. But this increases the scope of the change a lot.
* `kotlin-dsl` is actually published on the plugin portal. This might have code implications on how the `kotlin-dsl` entry is interpreted in the `plugins` block and what we could do with a different bundled plugin trying to apply it.

**Comment by aSemy** [comment]
Regarding naming: what about a utility function? Similar to how there's the `kotlin("jvm")` plugin helper, there could be a 'Gradle plugin development' helper.

```kotlin
plugins {
  gradlePlugin("java")        // equivalent: `java-gradle-plugin`

  // or a more explicit name
  gradlePluginDevelopment("kotlin") // equivalent: `kotlin-gradle-plugin`

  // or a wrapper function that's compatible with id(), that adds some prefix/suffix to the string
  id(gradlePluginDevelopment("kotlin"))
}
```

I've used strings as the arguments here, but the helper function could also accept a typed-safe argument.

```kotlin
sealed interface GradlePluginDevelopmentLanguage {
  val pluginId: String
 
  object Java: GradlePluginDevelopmentLanguage {
    override val pluginId = "java-gradle-plugin"
  }
 
  object Kotlin: GradlePluginDevelopmentLanguage {
    override val pluginId = "kotlin-gradle-plugin"
  }
}

fun PluginDependenciesSpec.gradlePluginDevelopment(target: GradlePluginDevelopmentLanguage) {
  //...
}
```


I also agree that the `kotlin-dsl` plugin should be replaced. It would also be nice to allow configuration of the defaults that the `kotlin-dsl` plugin applies via an extension function.


```kotlin
plugins {
  gradlePluginDevelopment("kotlin") // replacement for `kotlin-dsl`
}

gradlePluginDevelopment {
  kotlin {
    enableSamWithReceiver.set(false)
  }
}
```

**Comment by martinbonnin** [comment]
> Initially the plugin would simply apply kotlin-dsl but could at some point fully replace it.

3 objections to relying on `kotlin-dsl` by default:

1. It uses the current Gradle version for both `gradleApi()` and `kotlin-stdlib`. This is typically not what you want if you distribute your plugin and want to be compatible with older versions of Gradle. This wouldn't be too much of an issue if there was a way of ensuring at build time compatibility with a given (anterior) version. But I don't think there is yet?
2. It puts `gradleKotlinDsl()` in the compileClasspath. While it's adding nice sugar for Kotlin callers, it's also increasing the API surface to check (see 1.) So I'd prefer it to be opt-in
3. It applies `"org.gradle.kotlin.kotlin-dsl.precompiled-script-plugins"` which slows down build times. See https://github.com/android/nowinandroid/issues/39 for an example.

All in all I'd vote for 2 different plugins (naming up for grabs):

* `kotlin-convention-plugin` for convention plugins would do more or less everything `kotlin-dsl` is doing.
* `kotlin-distributed-plugin` for distributed plugins would do a lot less.

**Comment by ljacomet** [comment]
Actually #15219 is a better idea than this one, closing here
