### ISSUE TITLE
Tasks that show up later on the command line can be mysteriously skipped

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#20272]
There is an issue in the logic introduced in 7.4 to better ensure command line order is honored.  When a task gets pulled in from an earlier command line selector has a `mustRunAfter` relationship to a task that does not get executed, tasks pulled in by later command line selectors can be skipped.

For example, if I run `clean build` on the command line, and clean has `mustRunAfter foo` but the foo task is not a part of the build (i.e. neither clean nor build pull in foo), then the producer tasks pulled in by build will get skipped.

### Expected Behavior
All tasks should execute

### Current Behavior
Tasks from selectors later on the command line simply do not execute

### Steps to Reproduce 
```
plugins {
    id 'java'
}


task foo
clean.mustRunAfter foo
```

Run: `clean build`

**Comment by DPUkyle** [comment]
I verified the reproducer. Thanks Gary!
