### ISSUE TITLE
How to set the time zone for maven-publish snapshot version

### ISSUE THREAD

**Issue by wxiaole** [gradle/gradle#20278]

**Comment by donat** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
