### ISSUE TITLE
Daemon log fills with less than useful information when daemon is idle

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#2028]
When a daemon becomes idle, we reset the logger to DEBUG.  Since we have some periodic checks that run while the daemon is idle (like memory monitoring), this produces messages like this in the daemon log:

> 15:50:43.268 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17179869184, Free: 5623406592}
> 15:50:43.268 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17179869184, Free: 5623406592}
> 15:50:43.268 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 2058354688, Committed: 2064121856}
> 15:50:48.269 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17179869184, Free: 5624094720}
> 15:50:48.269 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17179869184, Free: 5624094720}
> 15:50:48.269 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 2058354688, Committed: 2064121856}
> 15:50:48.777 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
> 15:50:48.778 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 15:50:48.778 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
> 15:50:48.779 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> 15:50:48.779 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 15:50:48.779 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
> 15:50:48.780 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> 15:50:48.780 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 15:50:48.780 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
> 15:50:48.781 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.

It would be nice to limit this, possibly by increasing the logging level in an idle daemon to INFO or better.

**Comment by big-guy** [comment]
The logging isn't too crazy right now. We're producing ~1MB an hour.

**Comment by JankiGohel-Inteloom** [comment]
@big-guy did you find any solution? please help
