### ISSUE TITLE
Gradle build cause system to hang, forcing a hard reset

### ISSUE THREAD

**Issue by Nattle** [gradle/gradle#20290]
### Expected Behavior
Gradle builds, either via cli or Android studio should not effect OS stability. 

### Current Behavior
The symptom is OSX locks up in an unrecoverable way. A hard reset is required. Killing or attempting to kill Android Studio or Gradle build processes does not recover the system state.

When run with --debug and --info the log fills up with "_cannot acquire project lock for node :module:Step_" and "_cannot acquire project lock for node work action Parameters of ..._".

### Fix which seems to work:
Setting `org.gradle.parallel=false` appears to mitigate the issue. Unfortunately, this fix leads to about 50% longer build times on CircleCi. 

### Context
I had my machine wiped to a clean OS, installed Android Studio, checked out our codebase, and this issue again occurred immediately. I'm able to reproduce this issue on every build. Removing ~/.grade and ~/.android seems to allow a small number of builds before returning to the broken state. 

When in this state things which _seemingly_ depend on memory only are able to continue, for example video calls, messaging on slack, and tabbing between applications work as if there is no issues. Things which seem to write state in some way fail to resolve or only resolve after 10's of minutes. A simple `ls` in the terminal does not return, nor does ctrl-c return. New browser tabs are unable to open and I'm unable to close applications either with force quit via the UI or Activity Monitor. Force quitting Android Studio and/or gradle processes also does not recover this state.

Activity Monitor, htop, and top  all report no issues with cpu or disk usage and only about half of memory is in use. In Activity monitor I see a new bash process being created somewhat regularly (around 1 per minute on average) and those processes do not die. I use zsh for my shell so I'm not sure what process is spawning these.

This occurs on gradle-7.3.3 on my Intel Mac. It _seems_ to not occur on my personal m1 macbook. I have tried updating to 7.4.1 and the issue still occurs. 

### Steps to Reproduce 
Simply checking out our source code and building causes the issue. It does not occur on every machine but once in this state it reliably happens every build.  `./gradlew clean assembleDebug` is sufficient to cause the hang. 

### Your Environment
OSX Monterey, intel i9 cpu, 16gb of memory, ~400gb free disk space
Gradle 7.4.1
17 modules, a few of which are pure java libraries. 

gradle.properties
```
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
android.useAndroidX=true
org.gradle.vfs.watch=true
org.gradle.configureondemand=true
org.gradle.caching=true
android.nonTransitiveRClass=true
org.gradle.unsafe.configuration-cache=false
```
gradle-wrapper.properties
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by Nattle** [comment]
[Photos-001.zip](https://github.com/gradle/gradle/files/8353524/Photos-001.zip)

see attached photos for log output. I can't capture these to disk since writing to disk seems to be entirely blocked.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!
Sorry for you having such an issue.
Did you run a health check on your disk? 
For us, doing something about this issue would be very hard without a specific reproducer (it's not a general issue experienced by others too).

**Comment by Nattle** [comment]
I did some investigate with my IT department. We started with an un-manged install of OSX and I slowly built up my dev environment. 
Once we installed Sophos the issue cropped up, so it's some interaction between gradle / Sophos. My IT dept is reaching out to Sophos for more info, but either way it shouldn't be possible to take down the whole OS. 
My rough guess is that both processes are creating files / inodes like crazy and the OS runs out ability to do that.

**Comment by Nattle** [comment]
I worked with my local IT to get onto a newer version of Sophos, currently 10.3.5. They also put me in a 'test group' with lower requirements, but I'm not sure what that is. 

I'm still struggling with Sophos in that opening a new console can take 4-10 seconds if I'm building, so it's not great.

**Comment by Nattle** [comment]
@rcardin 
We had some luck downgrading as well, but it turned out to only be a temporary patch. Sophos eventually caught up and hung our machines.

**Comment by dennismayr** [comment]
This happens to me as well when building Android projects.
`org.gradle.parallel=false` does indeed mitigate the problem.

I use IBM's Semeru JDK with the OpenJ9 JVM.
Haven't tried with HotSpot yet, but I will.

**Comment by moskauerst** [comment]
I had the same problem with gradle on macbook m1 pro. And I could resolve it by disabling "Ransomware Detection (CryptoGuard)" in sophos.

**Comment by dennismayr** [comment]
Update: 

After experimenting on my M1 Mac, I've found that `org.gradle.parallel=false` works sometimes, sometimes not.
Mind you, this is a managed machine (for the next couple of years), so I cannot deactivate any security software.

However, I found out that the cause of the system lockup was _Gradle_ core-dumping non-stop under the global directory (e.g.  `~/.gradle` in my case); a `~/.gradle/daemon/7.3.3/core.20220520.182831.28584.0001.dmp` file got larger by the second at a rate of almost _1 Gb/s_ or more.

As the system drive quickly got full, the OS became unresponsive, forcing a hard reset.

Has this happened to any of you here?

**Comment by Nattle** [comment]
@dennismayr 

I didn't get as far as finding core dumps since it locked up pretty quick for me. 

My IT department reached out to Sophos and they (I think) did some work on their side. Then my laptop got a newer version of Sophos and maybe a policy change from my IT dept. Once that was in place things were back to normal. 

If you IT team can't help then Sophos probably knows how to fix it.
