### ISSUE TITLE
Add OpenJDK vendor to the toolchain support

### ISSUE THREAD

**Issue by nlisker** [gradle/gradle#20312]
The Gradle toolchain allows the user to specify the vendor. It seems that the reference implementation of OpenJDK is not offered. I suggest to add it. Example URL for Java 18: https://jdk.java.net/18/

**Comment by donat** [comment]
Can you use Oracle as a vendor to select OpenJDK for toolchains?

**Comment by donat** [comment]
Before I left my comment I checked the following

```
$ sdk list java
...
 Java.net      |     | 19.ea.15     | open    |            | 19.ea.15-open
               |     | 19.ea.14     | open    |            | 19.ea.14-open
               |     | 19.ea.4.lm   | open    |            | 19.ea.4.lm-open
               |     | 19.ea.1.pma  | open    |            | 19.ea.1.pma-open
               |     | 18           | open    | installed  | 18-open
...
```

```
$ sdk use java 18-open
$ java -XshowSettings:properties -version
...
java.vm.vendor = Oracle Corporation
...
```

Even though the java.net JDK is an OpenJDK, Oracle is still reported as a vendor.
I don't know how the vendor matching is implemented in the Gradle toolchain support. It might be enough that the value of `java.vm.vendor` contains the `Oracle` substring.

**Comment by nlisker** [comment]
It makes sense that the OpenJDK has Oracle as its vendor, but there are still 2 different distributions: `Oracle JDK` and `OpenJDK JDK`. I would want to be able to choose which one I want even if they have the same vendor technically. If I choose the `Oracle` one right now which one do I get? The docs don't say.

**Comment by jbartok** [comment]
@nlisker specifically for your situation you can use the [method suggested in the manual](https://docs.gradle.org/current/userguide/toolchains.html#sec:vendors), specifically:

`vendor.set(JvmVendorSpec.matching("Oracle Corporation"))`

On a general note: yes, we agree with you that things could be improved upon, but our current strategy is to separate Toolchain provisioning from core Gradle functionality by offering an SPI for it, so we are channeling our limited resources towards that effort.
