### ISSUE TITLE
@Option is not used if the task name is not explicitly listed on the command line

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#2032]
When we run a task and we specify an option `--like-this foo` (using the `@Option` annotation), it would work if the task is explicitly mentioned as part of the command, but fail if the task is added to the task graph as dependency.

See https://discuss.gradle.org/t/options-for-a-dependent-task/22275 

### Expected Behavior
Any tasks using an `--option` should be able to pick the value if the option was specified on the command line.

### Current Behavior
Only tasks explicitly mentioned on the command line can recognize the option. This is especially confusing when the options ave defaults (i.e. `gradle myTask --my-option foo` works fine; `gradle build --my-option foo` still runs, but `my-option` is silently ignored )

### Context
I have got a plugin that automatically creates a task corresponding to any code coverage report to upload it to an online service. There is an aggregator task depending on all upload tasks, that allows us to upload the coverage of integration and unit tests with one command. The online service requires a project token that can be specified as part of the environment or passed on the command line.

In the case of the project token defined in environment, the aggregator task works fine. If we try to specify the token on the command line, it fails because the aggregated tasks do not receive the token.

For practical example, see here:
https://github.com/ddimtirov/codacy-gradle-plugin#usage

**Comment by jameskleeh** [comment]
Just ran into this with `--fail-fast` with `check`
