### ISSUE TITLE
Provide a way to suppress incubating warnings

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#20328]
APIs annotated as `@Incubating` show up in IntelliJ as nasty yellow warnings. It's good that you're calling out unstable APIs, but when I'm using those knowingly, I want to be able to clear these warnings.

<img width="943" alt="incubating" src="https://user-images.githubusercontent.com/1302775/160946092-1b414eb7-74b5-443b-80b0-aee68e58b553.png">

### Expected Behavior
I should be able to add a suppress annotation locally, or a compiler flag globally, to clear the warning highlights in code.

### Current Behavior
No such annotation or compiler flag exists.

### Context
The misleading warnings take time away from real ones. IntelliJ also shows more useful warnings that are code bugs (like NPE), but get lost among the incubating warnings.

**Comment by TWiStErRob** [comment]
These warnings are coming from you IDE, not Gradle.
All Gradle does, is use the annotations properly on non-stable (subject to change/break) code.

Have you tried using the standard suppressions?

![image](https://user-images.githubusercontent.com/2906988/160948329-0c22d2a0-6d88-4246-9f09-1bf059d34694.png)
->
![image](https://user-images.githubusercontent.com/2906988/160948354-d2d4cc7e-ad36-4684-8d7c-629e6e0f3fdb.png)

Note: in some cases IDEA doesn't know that it could put the suppression on the statement or parent block, it only suggests `@file:Suppress`, I strongly recommend scoping your suppressions to the lowest possible scope:

```
class BuildTimeTrackerPlugin @Inject constructor(
	private val registry: @Suppress("UnstableApiUsage") BuildEventsListenerRegistry
) : Plugin<Project> {
```

**Comment by asarkar** [comment]
Thank you for your response. I can confirm that `@Suppress("UnstableApiUsage")` does have the desired effect. Two follow up questions:

1. Is the suppression string documented somewhere because I couldn't find it.
2. I'd still like to be able to suppress globally by adding a compiler flag. I understand the risk that the suppression should be applied to the lowest scope.

**Comment by TWiStErRob** [comment]
It's the name of the **IDEA Inspection**. You cannot add a compiler flag, because it's *in the IDE*. You can add it by the menu item I'm showing, or once you learn it, manually. You can also press "Disable inspection" or "Edit inspection profile settings" (which shows the docs). In edit, you can tune it to your liking: e.g. you can remove the Gradle annotation from the list, or tune down the level to weak warning, typo, or other.

**Comment by asarkar** [comment]
Thanks.
