### ISSUE TITLE
Dependency verification should treat a matching hash as verified even if the signature is untrusted

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#20326]
### Expected Behavior
If gradle/verification-metadata.xml mentions trusting a specific hash of artifact, then an artifact with that hash should be considered trusted, even if that artifact also has an untrusted signature.

### Current Behavior
We've observed that even if gradle/verification-metadata.xml mentions trusting the hash of an artifact, then the artifact isn't trusted if an untrusted signature is present.

### Context
We've observed a failure at https://ge.androidx.dev/s/k5ioamh3ghics/failure#1

saying:

```
Dependency verification failed for configuration ':buildSrc:plugins:cacheableImplementation'
One artifact failed verification: jvnet-parent-4.pom (net.java:jvnet-parent:4) from repository MavenRepo
If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.4/userguide/dependency_verification.html#sec:troubleshooting-verification

Open this report for more details: file:///home/runner/work/androidx/androidx/activity/build/reports/dependency-verification/at-1648660387370/dependency-verification-report.html
```

However, https://android.googlesource.com/platform/frameworks/support/+/bc472e51cadc3d8a66f890c8b06c6e7d36476960/gradle/verification-metadata.xml#940

says this:

```
<component group="net.java" name="jvnet-parent" version="4">
  <artifact name="jvnet-parent-4.pom">
  <sha256 value="471395735549495297c8ff939b9a32e08b91302020ff773586d27e497abb8fbb" origin="Generated by Gradle"/>
  </artifact>
</component>
```

We observe that the hash of the .pom matches the hash listed in the verification-metadata.xml, though. We've also found that if we add the .asc file into our Maven repository directory then this failure appears in an offline build and if we remove the .asc file from our Maven repository directory then this failure stops appearing.

Note that this issue wouldn't be as important if https://github.com/gradle/gradle/issues/20194 were resolved, because then it would be less common for us to have a sha256 entry for an artifact for which a signature also exists somewhere (but which we didn't manage to download when regenerating the file, see that bug )

**Comment by melix** [comment]
Checksums are here to verify integrity, while signatures are here to check provenance. IMHO Gradle should _not_ do this.

**Comment by mathjeff** [comment]
Yeah - I believe that for normal usage the idea is that all artifacts should be signed and those signatures should all be available all the time and so eventually it should be uncommon for `gradle/verification-metadata.xml` to mention anything about hashes.

The trouble occur if there is an artifact that isn't signed, or that didn't appear to be signed when `gradle/verification-metadata.xml` was generated ( note that https://github.com/gradle/gradle/issues/20194 can cause some files to appear unsigned that are actually signed). In that case it might be necessary to verify and to specify in `gradle/verification-metadata.xml` that the specific hash should be trusted rather than the (unavailable) signature. This satisfies Gradle's dependency verification. If a signature later becomes available for this artifact, though, then it appears that Gradle no longer trusts the previously trusted artifact due to the presence of a new signature.

I agree that hashes in places other than `gradle/verification-metadata.xml` shouldn't imply trust, and that we'd like to remove hashes listed in `gradle/verification-metadata.xml` when possible as signatures become available

**Comment by jbartok** [comment]
We will investigate the linked issue, but not change this behaviour.
