### ISSUE TITLE
Feature Request - Exclusions within version catalog

### ISSUE THREAD

**Issue by jifeiiii** [gradle/gradle#20332]
### Expected Behavior

I'd like to be able to exclude within the dependency resolution management.
Something like this:
```groovy
dependencyResolutionManagement {
    versionCatalogs {
        libs {
            library('commons-lang3', 'org.apache.commons', 'commons-lang3').exclude {
                group: "org.x.y", module: "z"
            }
        }
    }
}
```

### Current Behavior

Its impossible. The only customization option is within a strict version.

### Context

See [the stackoverflow question to support this issue](https://stackoverflow.com/questions/71680935/how-to-exclude-dependencies-from-gradle-version-catalog/71686827#71686827).

**Comment by jbartok** [comment]
Version catalog is about declaring versions, not about any kind of metadata level customization. This is to be done where using the catalog entries.
