### ISSUE TITLE
Start signing pom files in Gradle Plugin portal

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#20349]
Start signing pom files in Gradle Plugin portal.

Today, none of the pom files in Gradle Plugin portal have .asc files associated with them even if the rest of the artifact is signed (e.g. jars). Examples of these include `gradle-enterprise-gradle-plugin` (as of 3.9), `common-custom-user-data-gradle-plugin` (as of 1.6.5)

**Comment by jbartok** [comment]
We are soon releasing version `1.0.0` of the Plugin Publish Plugin, which will properly do this signing (all you will need to do is apply the `signing` plugin, the rest will happen automatically). We already have `1.0.0-rc-1` out, but it's still being tested: https://plugins.gradle.org/plugin/com.gradle.plugin-publish/1.0.0-rc-1. Feel free to try it, some preliminary documentation is here: https://plugins.grdev.net/docs/publish-plugin

**Comment by uttz-my** [comment]
Thanks


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gradle/gradle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 下午4:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [gradle/gradle] Start signing pom files in Gradle Plugin portal (Issue #20349)





 
We are soon releasing version 1.0.0 of the Plugin Publish Plugin, which will properly do this signing (all you will need to do is apply the signing plugin, the rest will happen automatically). We already have 1.0.0-rc-1 out, but it's still being tested: https://plugins.gradle.org/plugin/com.gradle.plugin-publish/1.0.0-rc-1. Feel free to try it, some preliminary documentation is here: https://plugins.grdev.net/docs/publish-plugin
