### ISSUE TITLE
Unexpected resolution of dependencies in multi-module project using api platform

### ISSUE THREAD

**Issue by JBodkin-Amphora** [gradle/gradle#20347]
Dependencies in other modules are being resolved in a multi-module project when using the java-library api dependency handler.

### Expected Behavior

project1/build.gradle
```
dependencies {
    api platform("org.springframework.boot:spring-boot-dependencies:2.6.5")
    api "org.springframework.boot:spring-boot-starter-logging"
}
```

project2/build.gradle
```
dependencies {
    implementation project(":project1")
    implementation "org.springframework.boot:spring-boot-starter-web"
}
```

I would expect that the spring-boot-starter-web dependency should not be resolved, since the `implementation project(":project1")` is missing the `platform` declaration. I would expect the following to be present if I wanted to resolve the dependency `implementation platform(project(":project1"))`

### Current Behavior

The spring-boot-starter-web dependency is resolved in the second project.

### Context
I'm looking to be able to define specific dependencies from a bom at a project level and reuse those dependencies in other modules. At the moment I've been testing using a multi-module project but would also like to compose builds using `includeBuild` as well.

### Steps to Reproduce 
[project.zip](https://github.com/gradle/gradle/files/8396571/project.zip)

**Comment by jbartok** [comment]
Working as expected, because you are declaring your platform in `api` in the first project, so it's visible transitively.

**Comment by JBodkin-Amphora** [comment]
What are the options in this instance? I would like to be able to use spring boot's bom to define the logging version but don't want to expose the bom transitively. Defining the logging version explicitly is something that I would like to avoid

**Comment by ljacomet** [comment]
In that case, you will need to create a custom configuration where you will declare the `platform`
Then that configuration should be added to the `extendsFrom` of the `*Classpath` configurations but not to the `*Elements` ones.

If you do not know how to do that, consider asking such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where you can get answers by the community of Gradle users.
