### ISSUE TITLE
Build lifecycle documentation is wrong - Responding to the lifecycle in the build script

### ISSUE THREAD

**Issue by guenthermahr** [gradle/gradle#20359]
Related documentation: https://docs.gradle.org/current/userguide/build_lifecycle.html
Example 2 doesn't work 

 

### Expected Behavior

According to the docu, Example 2 should work
### Current Behavior

The code results in errors because neither "project.hasTests" is found  nor the variable hasTests in project-a can be set.
### Steps to Reproduce 

In the following way I was able to make it work: 
1. I replaced "project.hasTests" by project.hasProperty("hasTests") 
2. I changed the task name to textx (obviously test is already one of the standard tasks)
3. I declared "hasTests" as an external variable like:
ext {
   hasTests="true"
}
Please correct and explain more thoroughly!

### Your Environment

Gradle: 7.4.2
MacOS 15.2.1

Build scan URL:

**Comment by hegyibalint** [comment]
Hi @guenthermahr,
You are right about this, only copy-pasting the example doesn't work, as an important piece of information is not presented there: that a default is set for all the projects.

https://github.com/gradle/gradle/blob/6f07e5dd58553214bbfacce887b2d16498fefede/subprojects/docs/src/snippets/buildlifecycle/projectEvaluateEvents/kotlin/build.gradle.kts#L16-L18

I think the best would be if the default would be moved into the main block, so it becomes part of the example.
