### ISSUE TITLE
test --tests does not work with packages which contain capital letters

### ISSUE THREAD

**Issue by ChrisJefferson** [gradle/gradle#20350]
I am on ubuntu 22.04, and used sdkman to install a fresh gradle 7.4.2

I use `gradle init` to create a package using: application, java, no, groovy, yes, JUnit jupiter. At the end I either name the project `myproject`, or `MyProject`.

If I call it `MyProject`, then `gradle test --tests="MyProject.*"` finds no tests. If I call it `myproject`, then `gradle test --tests="myproject.*"` works as expected.

### Expected Behavior

Either forbid package names with capital letters (if they are not intended to be supported), or fix `--tests` filtering to work when packages contain capital letters.

**Comment by donat** [comment]
The command-line test pattern matching was designed with Java conventions in mind. You can address test classes in two ways: 
- with their fully-qualified name: `gradle :test --tests org.example.MyTest`
- with simple name: `gradle :test --tests MyTest`

The distinction is based on whether the first character of the pattern is upper case:
https://github.com/gradle/gradle/blob/9b19add723ddfaae7722ee11134955e4517564a4/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/filter/TestSelectionMatcher.java#L152-L153

Unfortunately, this means that you cannot address your class only with its fully qualified name if the package name starts with an upper-case letter. At the same time, you can work around the issue by:
- using the simple name
- prefix the pattern with a `*` character.

**Comment by donat** [comment]
It might make sense to provide an alternative way to target any test patterns, for example by enabling regular expression based test filtering.
