### ISSUE TITLE
Toolchains not working in Gradle 7.4.2 for JDK 9

### ISSUE THREAD

**Issue by DanySK** [gradle/gradle#20369]
### Expected Behavior

It is possible to use Java 9 in the toolchains with the default toolchain provider

### Current Behavior

Build fails with
``
java.io.FileNotFoundException: /home/danysk/LocalProjects/multi-jvm-test-plugin/build/tmp/test/work/.gradle-test-kit/jdks/jdk-9.0.4+11/legal/jdk.dynalink/dynalink.md (Permission denied)
``

### Context

I maintain a Gradle plugin that [pre-configures the toolchains to run tests with multiple JDKs](https://github.com/DanySK/multi-jvm-test-plugin). The test suite includes verifying that Java 9 works. The update to Gradle 7.4.2 fails due to the aforementioned problem.

I could not understand why it does so, the JDK 10 works flawlessly. I inspected the contents/permissions of the tar files downloaded and they seem to match.

![image](https://user-images.githubusercontent.com/1991673/161595103-6336ae64-fcd1-4f24-b203-46ab26a006b2.png)

### Steps to Reproduce 
```bash
git clone https://github.com/DanySK/multi-jvm-test-plugin.git
cd multi-jvm-test-plugin
git checkout renovate/gradle-7.x # Note: as I'm writing it is commit fe39ebf1b4fdd4b58511e6cfb753a32529fb3751, but the PR will update with rebase
./gradlew check
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/h6i3qezgyu634

**Comment by DanySK** [comment]
Yes, I confirm. Same issue. It is blocking my adoption of Gradle 7.4.

**Comment by jbartok** [comment]
Problem has been solved by #20057. To have access to the fix pls. use the [current release candidate](https://gradle.org/release-candidate/) (version `7.5-rc-1`) and then `7.5`, once it's released.

**Comment by DanySK** [comment]
Under test right now, thanks.

**Comment by DanySK** [comment]
Seems to work for me at DanySK/multi-jvm-test-plugin#140
