### ISSUE TITLE
Configuration cache failure in 7.4.2 caused by kapt

### ISSUE THREAD

**Issue by AlecStrong** [gradle/gradle#20371]
### Expected Behavior
The configuration cache should be used when running the same task twice

### Current Behavior
Attempting to use the configuration cache crashes on successive runs

### Context
We are building an android application. We're able to reproduce this issue by running `:app:assembleInternalDebug` which populates the configuration cache, and then changing a file and running again. The second run then fails with:

```
> ./gradlew :app:assembleInternalDebug --no-daemon --stacktrace

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
Configuration cache is an incubating feature.
Reusing configuration cache.

FAILURE: Build failed with an exception.

* What went wrong:
Failed requirement.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.IllegalArgumentException: Failed requirement.
        at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec$readSuccessorReferencesOf$5.invoke(WorkNodeCodec.kt:142)
        at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec$readSuccessorReferencesOf$5.invoke(WorkNodeCodec.kt:141)
        at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.readSuccessorReferences(WorkNodeCodec.kt:170)
        at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.readSuccessorReferencesOf(WorkNodeCodec.kt:141)
        at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.readNode(WorkNodeCodec.kt:85)
        at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.readNodes(WorkNodeCodec.kt:65)
        at org.gradle.configurationcache.serialization.codecs.WorkNodeCodec.readWork(WorkNodeCodec.kt:45)
        at org.gradle.configurationcache.ConfigurationCacheState.readWorkGraph(ConfigurationCacheState.kt:261)
        ...
```

### Steps to Reproduce 
I'm not entirely sure how to reproduce outside of our product, but I've stepped through gradle with a debugger to get more info during the crash.

[This change](https://github.com/gradle/gradle/commit/da914b3b18e8cbb252a141af3b55d011ecb80815) is what caused the crash (introduced in 7.4.2).

This is the relevant node which is not a TaskNode during read
![image](https://user-images.githubusercontent.com/1675456/161626216-21889fce-8a29-4ab1-abdd-5edc9a0f03b0.png)

And here is the parent node which this read is happening under
![image](https://user-images.githubusercontent.com/1675456/161626406-a52797b9-242c-4819-83c4-c12ed2bf6573.png)

it looks like its evaluating the kapt task of one of our modules `:service:api`, which uses an annotation processor in the same repo `:retrofit-return-type-keeper`, but that annotation processing step is a `TransformNode` instead of a `TaskNode` so it crashes. Previously in 7.4.1 we were able to successfully use the configuration cache.

If there is more information I can provide or debugging I can do let me know.

Thanks!

**Comment by adammurdoch** [comment]
Thanks for the detailed issue. This should be fixed via https://github.com/gradle/gradle/pull/20400. Would you be able to try out a recent Gradle 7.5 nightly and see whether this is the case?

**Comment by ljacomet** [comment]
@AlecStrong Any chance you can try a 7.5 nightly to check if this is fixed?

**Comment by eric-labelle** [comment]
I tried with `gradle-7.5-20220411230515+0000-all.zip` but we have a lot of other problems with our app on 7.5 requiring changes that prevent me from confirming the initial problem is gone. 🤷‍♂️

**Comment by AlecStrong** [comment]
the other issues we're seeing are because 7.5 forbids external processes during the configuration phase which we do (and shouldn't do - very useful error!), so gonna try fixing that and then can confirm that this is resolved.

**Comment by AlecStrong** [comment]
Alright testing this is likely blocked on https://github.com/gradle/gradle/issues/20563 😰

**Comment by big-guy** [comment]
@AlecStrong could you give `7.5-20220504153215+0000` a try?

**Comment by AlecStrong** [comment]
yes! it works! yay!
