### ISSUE TITLE
Display requested task regardless of logging output

### ISSUE THREAD

**Issue by w25r** [gradle/gradle#2038]
### Expected Behavior
Users may want to know which of their requested tasks ran and whether they succeeded.

A task requested at command line shows up in the output, either in the logging with outcomes and/or in the summary.

### Current Behavior
If the task requested has no logging, then it doesn't show up in the output.  

### Context
Output like this will be confusing, as users don't know whether or not their task ran.  
```console
Gradles-MBP:playground Gradle$ /tmp/gradle-pr/bin/gradle clean build

BUILD SUCCESSFUL in 1s
8 actionable tasks: 8 executed
```

**Comment by w25r** [comment]
This was initially brought up by @wolfs and seconded by @adammurdoch

**Comment by eriwen** [comment]
Idea from @big-guy https://asciinema.org/a/371y3x5z47h7fmjau26l38k68

**Comment by wolfs** [comment]
I like @big-guy variant. I would probably drop `gradle` from the status line. So instead of showing
```
gradle assemble: 5 executed
```
I would show
```
assemble: 5 executed
```

**Comment by w25r** [comment]
I think having just the task name is potentially very confusing.  Especially if the task name is not very descriptive.  It could end up with

`task1: 12 executed`

I think we could go with something wordy:

`Request: 'clean build' yielded 8 actionable tasks: 8 executed`

but what if we simply add a `lifecycle` message that simply logs the tasks that were requested at the command line?

```console
Gradles-MBP:playground Gradle$ /tmp/gradle-pr/bin/gradle clean build
Starting build for primary tasks 'clean build'

BUILD SUCCESSFUL in 1s
8 actionable tasks: 8 executed
Gradles-MBP:playground Gradle$
```
