### ISSUE TITLE
Toolchain not downloading Java18 for specific vendor

### ISSUE THREAD

**Issue by mdeinum** [gradle/gradle#20406]
We currently have a build with a toolchain using Java 17. We decided we want to move to Java 18. However this failed. Initially I figured this is due to using the `api.adoptopenjdk.net` and I switched to `api.adoptium.net`, however the result is the same. 

The URL that is **always** being used is `https://api.adoptium.net/v3/binary/latest/18/ga/windows/x64/jdk/hotspot/normal/adoptopenjdk` even when explicitly setting the vendor to `ADOPTIUM`. When manually entering the URL `https://api.adoptium.net/v3/binary/latest/18/ga/windows/x64/jdk/hotspot/normal/adoptium` a proper JDK for Java 18 is downloaded. It looks like that the Vendor property is totally ignored for downloading a JDK. 

### Expected Behavior
Downloading the proper JDK based on the provided vendor. 

### Current Behavior
Not downloading the JDK based on the Vendor specified, it will always download the AdoptOpenJdk one. 

### Context
We are trying to move our build (locally and on the server) to Java 18, currently this is impossible as no Java 18 is being downloaded. I can locally do a manual install of Java18 I cannot do this on our server. 

When supplying a Vendor the proper URL should be used to download the JDK requested and not always the AdoptOpenJdk one. 

### Steps to Reproduce 
Create a java project with a toolchain for java 18, try to build and it will fail. 

### Your Environment
Windows 10, Intellij IDEA (but the command line fails likewise).
Gradle 7.4.2 through the Gradle Wrapper

The issue with not using the vendor should have been fixed with https://github.com/gradle/gradle/issues/17148 (but apparently not for other vendors). 

Probably related: https://github.com/gradle/gradle/issues/20344

See also: https://discuss.gradle.org/t/java-toolchain-for-java-18-on-windows-failing/42641

**Comment by jbartok** [comment]
Will be fixed by https://github.com/gradle/gradle/pull/20403, just like https://github.com/gradle/gradle/issues/20344.

**Comment by jamesward** [comment]
@mdeinum Did you find a temporary workaround?

**Comment by mdeinum** [comment]
> @mdeinum Did you find a temporary workaround?

No I didn't. The only workaround is to download and manually install into one of the known locations. However that doesn't really sit well with an integration server. 

I also doubt it will actually be fixed by what is proposed, as it just simply seems to download the wrong vendor JDK all together (it seems to ignore the `vendor` and always download the `adoptopenjdk` one.
