### ISSUE TITLE
Build cache uses the same cache key for tasks with the same type but different custom actions defined in the same build script

### ISSUE THREAD

**Issue by vydra** [gradle/gradle#2040]
Two tasks with same inputs but different behavior produce same cache keys.

### Expected Behavior
Different tasks should always produce different cache keys

### Current Behavior
 have three (similar) tasks defined in DSL that are generating the same cache key:

Cache key for task ':au-V4:au-V4-service:generateHdbDbScripts' is 7176956a4eaa4c8841d85152bf237895
Cache key for task ':au-V4:au-V4-service:generateOracleDbScripts' is 7176956a4eaa4c8841d85152bf237895
Cache key for task ':au-V4:au-V4-service:generateOracleXeDbScripts' is 7176956a4eaa4c8841d85152bf237895

### Context

problem was fixed by:

inputs.property('taskpath', path)

**Comment by lptr** [comment]
Thanks @vydra for reporting this bug. Different tasks should always have different build cache keys, there's no need to track the task path for that (nor would it be a sufficiently complete solution). The fix for this will be released as part of Gradle 4.0.

**Comment by mondrejko** [comment]
Agreed about using the task path. I did that initially to get something that worked, later used another input property that would be unique and accurate/consistent for all environments. But, even that still seemed arbitrary.

--
Michael Ondrejko
