### ISSUE TITLE
Kotlin stdlib extension functions cannot be used when applying the precompiled kotlin script plugin (`kotlin-dsl`) 

### ISSUE THREAD

**Issue by raphiz** [gradle/gradle#20424]
### Expected Behavior
It should still be possible to use extension functions from the Kotlin stdlib (eg. [`Path.writeText`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io.path/java.nio.file.-path/write-text.html)) when applying the `kotlin-dsl` plugin. When the code compiles without it, it should continue to compile when this plugin is applied.

```kotlin
plugins {
    `kotlin-dsl`
    id("org.jetbrains.kotlin.jvm") version "1.5.31"
}
```

```kotlin
// REGULAR Kotlin code (not DSL / *.kts)
import java.nio.file.Path
import kotlin.io.path.writeText

fun thisShouldCompile() {
    Path.of("thisDoesNotWork").writeText("Hello World")
}
```

### Current Behavior
When the `kotlin-dsl` plugin is applied, some extension functions from the Kotlin stdlib  (eg. [`Path.writeText`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io.path/java.nio.file.-path/write-text.html)) are not recognized anymore, resulting in a compilation failure:

```
$ ./gradlew compileKotlin

> Task :plugin:compileKotlin FAILED
'compileJava' task (current target is 17) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
e: /path/to/gradle-kotlin-dsl-plugin-issue/plugin/src/main/kotlin/com/example/Example.kt: (9, 32): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun File.writeText(text: String, charset: Charset = ...): Unit defined in kotlin.io

FAILURE: Build failed with an exception.

```

### Context
I have a set of [convention plugins](https://docs.gradle.org/current/samples/sample_convention_plugins.html#compiling_convention_plugins) implemented as [precompiled script plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins) in the Gradle Kotlin DSL.
I now want to add additional "regular" Kotlin code in the same project, for example to define custom tasks. In this additional, non-DSL Kotlin code, I should be able to use all available Kotlin stdlib extension functions.

### Steps to Reproduce 
I created a [repository](https://github.com/raphiz/gradle-kotlin-dsl-plugin-issue) which illustrates problem.
Only If you comment out the [`kotlin-dsl` plugin](https://github.com/raphiz/gradle-kotlin-dsl-plugin-issue/blob/main/plugin/build.gradle.kts#L3), the code will compile.

### Your Environment

I created two build scans, one [with the `kotlin-dsl` plugin enabled](https://scans.gradle.com/s/5cnexspclfpiu) and one [without it](https://scans.gradle.com/s/odmfhlkdjssue)

**Comment by vlsi** [comment]
You can't use Kotlin 1.5 stdlib in precompiled script plugins and in other Gradle plugins yet 🤷‍♂️ 

You need to wait while Gradle bumps the embedded Kotlin version.
It is likely 1.5 would be available only in Gradle 8+, see https://github.com/gradle/gradle/pull/19539#issue-1098971760

**Comment by raphiz** [comment]
Thanks for the quick response. That of course explains it. With this pointer, I was able to find [the corresponding section in the documentation](https://docs.gradle.org/current/userguide/compatibility.html#kotlin) as well.
I was also able to see the target Kotlin version changing from `null`  to `1.4` in the `kotlinOptions` when applying the `kotlin-dsl` plugin.
```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    doFirst {
        println("apiVersion: ${kotlinOptions.apiVersion}")
        println("languageVersion: ${kotlinOptions.languageVersion}")
    }
}
```
