### ISSUE TITLE
`ServiceLoader.load(ToolProvider.class)` execute in `Gradle Task`, `JDK Service Provider` not found

### ISSUE THREAD

**Issue by mozhuanzuojing** [gradle/gradle#20430]
I want to find and use `com.sun.tools.jdeps.Main$JDepsToolProvider` in `Gradle Task` via execute `ServiceLoader.load(ToolProvider.class)`.

### Expected Behavior

All service providers of `JDK17` can be found via execute `Gradle Task`.

### Current Behavior

no `JDK17` service provider has been found.

### Context

- gradle script and gradle plugin cannot use jdk's service provider. E.g `javadoc`, `jmod`, `jlink`, `javac`, `javap`, `jdeps`, `jar`, `jpackage`
- I want to call `jdeps` in gradle script or gradle plugin to analyze dependencies of class.
- No solution found so far.

### Steps to Reproduce 

1. git clone https://gitee.com/mozhuanzuojing/gradle-jdeps.git
2. open `gradle-jdeps` and wait build.
3. open file `build.gradle`, please notice task `jdeps`.
4. execute task `gradle-jdeps` -> `jdeps` -> `jdeps`

> Screenshots

![image](https://user-images.githubusercontent.com/63572041/162612043-0eb764be-c612-41db-acd5-f1b310cf7d8d.png)
![image](https://user-images.githubusercontent.com/63572041/162612198-139ae1f7-298e-4491-b413-346f5223ef58.png)

### Your Environment

Build scan URL: `https://gradle.com/s/aqo7oundhddws`

**Comment by jbartok** [comment]
This is not the usual way Gradle interacts with these tools. You would probably be better off using an `Exec` task and invoke `jdeps` as an external process.

What's your exact use case? Did you search the Portal for plugins that might help?

**Comment by mozhuanzuojing** [comment]
@jbartok Just found that the following method can get `jdeps`! But I still want to understand why `ServiceLoader` doesn't work.

```gradle
Optional<ToolProvider> jdeps = ToolProvider.findFirst("jdeps");
System.out.println(jdeps);
```

**Comment by mozhuanzuojing** [comment]
@jbartok The problem is solved, the solution is as follows：

> successfully loaded into the `jdeps` instance
```java
// Disable Thread.currentThread().getContextClassLoader() from org.gradle.api.internal.AbstractTask.doExecute L746  
ServiceLoader<ToolProvider> sl = ServiceLoader.load(ToolProvider.class, null);
```
