### ISSUE TITLE
JaCoCo Report Aggregation Plugin uses JARs not class directories in allCodeCoverageReportClassDirectories configuration

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#20432]
### Expected Behavior
When I apply `jacoco-report-aggregation` plugin to a project and use `jacocoAggregation` to declare project dependencies, the `allCodeCoverageReportClassDirectories` configuration will resolve to class directories for the dependencies, not JAR files.

[Current docs](https://docs.gradle.org/7.4.2/userguide/jacoco_report_aggregation_plugin.html#sec:dependency_management) say the `allCodeCoverageReportClassDirectories` configuration

> Consumes the project dependencies to from the jacocoAggregation configuration to collect **_all classes directories_**.

### Current Behavior
`allCodeCoverageReportClassDirectories` configuration resolves to JAR output of the dependencies declared with `jacocoAggregation`.

### Context
The project I use embeds some dependencies in the generated JAR of one of the projects. These are then reported in the generated report. If class directories were resolved the dependencies bundled in the JAR would be correctly excluded.

I also can't control which project classes are reported either as it's not possible (or easy?) to exclude elements of the JAR file.

### Steps to Reproduce 
I have simply added a task to print the resolved files from the `allCodeCoverageReportClassDirectories` configuration in `code-coverage-report` project - run `./gradlew :code-coverage-report:printAllCodeCoverageReportClassDirectories` to see the resolved files are JARs.

![image](https://user-images.githubusercontent.com/170028/162648736-b042a4d4-6624-4d12-9d6c-0273ebd72483.png)

[sample_jvm_multi_project_with_code_coverage_standalone-kotlin-dsl.zip](https://github.com/gradle/gradle/files/8460317/sample_jvm_multi_project_with_code_coverage_standalone-kotlin-dsl.zip)

### Your Environment

Build scan URL:

**Comment by DPUkyle** [comment]
Thank you for reporting; will have a look now.
