### ISSUE TITLE
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Não foi possível resolver todos os arquivos para configuração ':app:debugCompileClasspath'

### ISSUE THREAD

**Issue by Alexandre05** [gradle/gradle#20451]
I'm creating an app to adopt street animals, I need to use images to show a carousel, but there's no way. How to solve this problem, when trying to download dependency on android stuido version Bumblebee?

**Comment by Alexandre05** [comment]
Obrigado, edeiei a pergunta.

**Comment by Alexandre05** [comment]
edit the question.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
