### ISSUE TITLE
Publish Gradle Metadata as a Maven artifact with a special "gradle-metadata" classifier alternative to .module to make it available in any Maven repo types

### ISSUE THREAD

**Issue by protobufel2** [gradle/gradle#20466]
Currently, Gradle publishes module's Gradle Metadata as a .module file.
However, there are many Maven repositories not supporting such capability, e.g. in some Artifactory setups.
Moreover, the pom.xml has the Gradle Metadata marker, whereas the .module file is absent, making it an error!
Yes, one can turn the Gradle Metadata publishing off, but that's a forced unwanted downgrade.  

### Expected Behavior
Hence, as an alternative (which should be user configurable) Gradle should publish the same .module file as the artifact's classifier, e.g. "gradle-metadata" and then refer to it in the pom.xml, not unlike it does for the .module, but referring to the classifier instead.
  
### Current Behavior

This would allow with a simple boolean flag the enablement of Gradle Metadata on any Maven repository.
 
### Context
My internal remote Maven repo, due to CI or some other settings not under my control, doesn't publish .module files, hence eliminating one of the Gradle most compelling features. I think the proposed is a big deal affecting large communities while easy to implement.

**Comment by ljacomet** [comment]
This seems like an overcomplicated solution for a repository setup problem.
Maven allows files with different _extensions_ to be published by default. This is what the `.module` file leverages.
Even if we were to offer that option, which _extension_ should we use? `json`?
Would your repository accept this?
We cannot use `jar` or `xml` for sure.

So all in all, the simpler solution is to make sure your repository properly accepts `module` as a file extension if you have a configured whitelist for these.

There is no plan to change this in Gradle.
