### ISSUE TITLE
"--offline" execution option should be considered as configuration input

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#20461]
### Expected Behavior

Gradle should take `--offline` as configuration input which means configuration cache should be invalid when `--offline` value is changed.

### Current Behavior

Configuration cache is reused when `--offline` value is changed.

### Context

AGP respects `--offline`  when download sdk components. Currently the downloading of sdk components(e.g. bootstrap classpath) is triggered during task graph is being built although the computing of sdk component is wrapped by provider.  Basically, if `--offline` option changes, we could do different things regarding to sdk downloading in the configuration phase of the second run, but configuration cache is re-used in the second run which prevents us from going through sdk downloading again

**Comment by bingranl** [comment]
Can you share what version this fix would be included? (e.g. 7.6-rc1, 7.6-rc2 .... )

**Comment by abstratt** [comment]
> Can you share what version this fix would be included? (e.g. 7.6-rc1, 7.6-rc2 .... )

7.6-rc1 (or any nightlies from now on)

**Comment by bingranl** [comment]
Thanks @abstratt
