### ISSUE TITLE
Possible unexpected state in scheduler causing deadlock

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#20508]
One of our integration tests has become [flaky](https://gradle.slack.com/archives/C03A0MT6S/p1650461456149339?thread_ts=1650411083.369809&cid=C03A0MT6S), and only when run with the parallel executor.

git-bisect tells us the flakiness started with bd4e7a0, but we think there could be related changes in #20419 also.

We suspect a concurrency issue where a TaskNode fails and is marked EXECUTING -> EXECUTED, but before its dependency successors can be canceled, a successor's state also shifts to EXECUTED, which is unexpected.

If not for the assertion in [Node:266](https://github.com/gradle/gradle/blob/bf05b8f38f733b04fcf6071dd31f5d82b29bf1ab/subprojects/core/src/main/java/org/gradle/execution/plan/Node.java#L266) exposed by the test, this would look like a deadlock in production code and Gradle might hang indefinitely.

Steps to reproduce:
1. Apply this patch:
```
Index: subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy b/subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy
--- a/subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy	(revision 64d7940e8dc191a460604b31e88d9e45134d9150)
+++ b/subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/TestReportAggregationPluginIntegrationTest.groovy	(date 1650472828541)
@@ -423,7 +423,7 @@
             """
 
         when:
-        fails(":application:testAggregateTestReport")
+        fails(":application:testAggregateTestReport", "--parallel")
 
         then:
         failure.assertHasDescription("Execution failed for task ':direct:test'.")

```
2. Run `$ ./gradlew :plugins:embeddedIntegTest --tests "org.gradle.api.plugins.TestReportAggregationPluginIntegrationTest.test verification failure prevents creation of aggregated report" -is`. 
3. The project under test will fail as expected, but throw an exception after 30 seconds from `org.gradle.execution.plan.Node.cancelExecution(Node.java:266)`.

More details in this slack [thread](https://gradle.slack.com/archives/C03A0MT6S/p1650411083369809).

**Comment by DPUkyle** [comment]
Possibly related to #20254

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/20570

**Comment by adammurdoch** [comment]
Fixed on the wrong branch

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/20588
