### ISSUE TITLE
gradle build --refresh-dependencies doesn't work as it expected.

### ISSUE THREAD

**Issue by mannyonfire** [gradle/gradle#20519]
### Expected Behavior

Use this command to refresh the snapshot dependencies which has been changed some code except version and uploaded to the remote maven repository

### Current Behavior

1. After "gradle build --refresh-dependencies" finished successfuly, the dependencies are still "old version". i decompile the jar from remote maven repository and it's "new version".
2. Remove .gradle/caches/* and excute again then everything work fine

### Context

Somehow -refresh-dependencies seems not ignore the caches, should "gradle build --refresh-dependencies" be equivalent to remove .gradle/caches/* and rebuild manually？

### Steps to Reproduce 

1. Project A is dependent on  A-SNAPSHOT and it cached in your local.
2. Update some A-SNAPSHOT's code and dont change the version then upload to your own nexus repository.
3. Try use "gradle build --refresh-dependencies" to get the lastest A-SNAPSHOT

### Your Environment

Gradle version: 7.4.2
OpenJDK: 11

Build scan URL:

**Comment by mannyonfire** [comment]
And i'm using Android Gradle Plugin-7.0.4

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

P.S. In general this works in Gradle, we have proper test coverage for it, so whatever problem you are having must have a part specific to your project.

**Comment by mannyonfire** [comment]
This might be a IDE bug, thanks for you time will close it.

**Comment by Nailik** [comment]
2 years later, issue still exists. Don't understand why this was closed in the first place.
