### ISSUE TITLE
Consuming platform fails without helpful error message

### ISSUE THREAD

**Issue by lkoe** [gradle/gradle#20527]
When consuming a faulty platform definition gradle fails the consumer project without any helpful error information.

By mistake I created a faulty platform definition and published it to the local maven repo.

```
dependencies {
    api(platform("org.springframework.boot:spring-boot-dependencies:2.6.7"))
    constraints {
        api("org.apache.xmlgraphics:batik-transcoder.1.14") // <-- Typo here
    }
}
```

Upon consuming the platform from another project gradle fails with a NPE without any detail information (nor stacktrace unless `-XX:-OmitStackTraceInFastThrow` is added to the gradle JVM args).

```
Execution failed for task ':example-platform-consumer:compileJava'.
> Could not resolve all files for configuration ':example-platform-consumer:compileClasspath'.
   > Could not resolve org.example:example-platform-bom:1.0.0-SNAPSHOT.
     Required by:
         project :example-platform-consumer
      > java.lang.NullPointerException (no error message)
```

In my case - because the published platform was reasonably complex - it was very hard to track down the cause of the issue (my typo), in the end I needed to attach a debugger to the build and catch the NPE to see where/why it was failing.

A few related observations/oddities:

1. It appears the faulty platform can only be published if it imports another platform/bom. If that is not the case, the faulty dependency definition gets spotted upon publishing the platform
2. The published Maven POM does *not* contain the faulty reference, only the gradle module metadata of the platfom contains it
3. The error is not triggered if the consumer imports the plugin via project references

### Expected Behavior
Gradle should provide more helpful information for failing platform dependencies, something like:
 "Failed importing platform, version of dependency definition `org.apache.xmlgraphics:batik-transcoder.1.14` cannot be determined"
 
 This way the problem in the platform definition could be spotted more easily

### Current Behavior
Gradle fails inconspicuously with a NPE (providing no stacktrace on the NPE unless `-XX:-OmitStackTraceInFastThrow`). 

### Steps to Reproduce 
Please see the attached reproducer project:
[gradle-platform-exception.zip](https://github.com/gradle/gradle/files/8537483/gradle-platform-exception.zip)

1. Publish the platform to local Maven repo: `gradlew :example-platform-bom:publishToMavenLocal`
2. Build the consumer project to trigger the exception: `gradlew :example-platform-consumer:build`

### Your Environment
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Amazon.com Inc. 11.0.12+7-LTS)
OS:           Windows 10 10.0 amd64
```

**Comment by jbartok** [comment]
Duplicates #20182
