### ISSUE TITLE
Problem with Whitebox testing of JPMS-based Java module

### ISSUE THREAD

**Issue by gleguern** [gradle/gradle#20530]
### Expected Behavior

Without a module-info.java file in test/java, Gradle should generate a test command relying on java's --class-path argument (cf https://docs.gradle.org/current/userguide/java_testing.html#whitebox_unit_test_execution_on_the_classpath).

### Current Behavior

Gradle generates a test command relying on JPMS-related arguments (--module-path, --patch-module, ...).

### Context

I'm using Gradle 7.4.2. Trying to test (build and run works, at least the Gradle part) project https://gitlab.com/sosl/sosl/-/tree/Modularization

### Steps to Reproduce 

Clone project https://gitlab.com/sosl/sosl; checkout branch Modularization; run "./gradlew --info build"

```
git clone --branch Modularization https://gitlab.com/sosl/sosl.git
git checkout e80315b2f7838c854d50646b6059ebe156772cd9
./gradlew --info clean test
```

### Your Environment

Build scan URL: https://gradle.com/s/uepka7o37c4sm (old one https://gradle.com/s/ykpxd3dgukk2y)

**Comment by gleguern** [comment]
The problem with the command currently generated by Gradle (.../java ... --module-path ...build/classes/java/main:...build/classes/scala/main:... ... --patch-module sosl=...) is probably linked to the fact that ...build/classes/scala/main does not contain a module-info.class file.
Either:
- I have a problem with my build setup, and Gradle should generate a command based on --class-path instead of --module-path ;
- module-info.java should be in both directories build/classes/java/main et build/classes/scala/main, but I doubt Java would like it ;
- the argument "--patch-module sosl=..." should include the '.../build/classes/scala/main' which it does not currently.

**Comment by jbartok** [comment]
Not a regression, behaves the same way with all recent Gradle versions. Re-classifying it as a bug.

**Comment by gleguern** [comment]
There is probably a problem with the build of the above-mentioned project (I'll investigate that point next).

I however did an MCVE (git clone --branch JPMS https://gitlab.com/mko-mcve/mcve-gradle-junit-scala-jpms.git) and there are 1 nonobvious constraint and 2 points "incorrectly" handled by Gradle natively when using Gradle with JPMS and sources in Java and Scala.

1. Java and Scala sources must not share packages (a Java class and a Scala class declared to be in the same package). As Java classes and Scala classes end up in 2 different directories, there is no way to combine them at "runtime". If using JPMS, java seems to expect classes in the same package to be in the same directory (potentially linked to the fact that the content of packages can not be declared in different modules). 
2.  Natively, Gradle assumes Scala sources depend on Java sources. Inverting this dependency is not "natural".
3. When compiling the java sources (which contain the file module-info.java), scala classes must be added to the classpath and the compiled module must be declared to "read" the unnamed module.

The 2 last points are potentially linked to the fact that I was unable to "properly" invert the dependency between Scala and Java sources.

**Comment by gleguern** [comment]
It seems it was not a bug or regression after all. However, with the default conventions, projects mixing Scala, Java, and JPMS do not work out of the box. I was able to 'fix' an MCVE (https://gitlab.com/mko-mcve/mcve-gradle-junit-scala-jpms/-/tree/JPMS) with the help of Vampire on the Slack community.

The bottom line (in addition to having to set the dependencies between scala and java if not using the ones from the convention) seems to be that Java compilation tasks rely on the classes directory to find modules. It does not work if the sources of a single module are built by different tasks (as is sometimes the case in a project mixing Scala and Java). A 'better' approach may be to rely on already built Jar libraries. It however requires interlacing compilation tasks with jar tasks (jar libraries must be built after contained class files have been produced and before the compilation of sources relying on those libraries).
