### ISSUE TITLE
IllegalStateException: Unexpected parent dependency id

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#20548]
### Expected Behavior

Gradle should finish the build without errors.

### Current Behavior

Gradle fails the build with following exception:
```
Caused by: java.lang.IllegalStateException: Unexpected parent dependency id 185. Seen ids: [128, 129, 257, 2, 130, 258, 131, 259, 132, 260, 133, 261, 134, 262, 135, 136, 137, 138, 139, 267, 140, 268, 141, 142, 15, 143, 271, 16, 144, 17, 145, 18, 146, 19, 20, 278, 23, 279, 280, 28, 29, 157, 158, 159, 160, 161, 164, 293, 294, 295, 296, 297, 298, 179, 180, 181, 182, 183, 184, 190, 193, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 206, 79, 80, 81, 82, 83, 86, 219, 220, 221, 222, 229, 230, 231, 234, 252, 127]
```
when build is using `dependencyResolutionManager` to force dependency version:
```gradle
dependencyResolutionManagement {
    components {
        withModule("com.google.code.gson:gson") {
            allVariants {
                withDependencies {
                   add("com.google.code.gson:gson") {
                       version {
                           it.require('2.8.9')
                       }
                       because("Force using same gson version because of https://github.com/google/gson/pull/1991")
                    }
                }
            }
        }
    }
}
```

### Steps to Reproduce 
- Comment [this line](https://github.com/JetBrains/kotlin/blob/4f8ef8c315bd6ebc2f03c56ea5f1e9c088f7b079/libraries/tools/kotlin-gradle-plugin-api/build.gradle.kts#L17) in Kotlin repo
- Run `./gradlew :kotlin-gradle-plugin-api:generatePomFileForMainPublication -s` task and observe the exception

If I change [in this line](https://github.com/JetBrains/kotlin/blob/4f8ef8c315bd6ebc2f03c56ea5f1e9c088f7b079/settings.gradle#L54) to less strict constaint - Gradle finishes the build without error.

**Comment by ov7a** [comment]
Sorry for the late reply.

I can no longer reproduce this issue, and I believe it's obsolete now. One of the hard parts was that this version of Kotlin sources was dependent on the Java 6 toolchain. If anyone stumbles across a similar issue, please open a new issue.
