### ISSUE TITLE
Creator-destroyer relationship for tasks from different projects not upheld during parallel execution

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#20559]
Investigating the flakiness in [DestroyerTaskCommandLineOrderIntegrationTest](https://github.com/gradle/gradle/blob/0510103d4925465e5b1336ae514aaf3fdf8aa540/subprojects/core/src/integTest/groovy/org/gradle/api/DestroyerTaskCommandLineOrderIntegrationTest.groovy#L49) revealed that the problem is not with the test, but looks like a genuine bug.

Seems like when a task in one project creates a file and another task in another project destroys that same file, they are no longer ordered. I would guess this is a recent regression introduced on the 10th of March.

Details on the behavior [here](https://ge.gradle.org/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Asia/Shanghai&tests.container=org.gradle.api.DestroyerTaskCommandLineOrderIntegrationTest&tests.sortField=FLAKY&tests.unstableOnly=true).

**Comment by wolfs** [comment]
This set of tests in `ParallelTaskExecutionIntegrationTest ` have the same problem I think: https://github.com/gradle/gradle/blob/ee3879682e7feac3ff034b4ea398a565772c0a5e/subprojects/core/src/integTest/groovy/org/gradle/execution/taskgraph/ParallelTaskExecutionIntegrationTest.groovy#L359-L436

**Comment by adammurdoch** [comment]
Should be fixed now via https://github.com/gradle/gradle/pull/20645
