### ISSUE TITLE
osgi plugin ignores jar.mainfest.license

### ISSUE THREAD

**Issue by ddekany** [gradle/gradle#2056]
Setting jar.mainfest.license doesn't  create `Bundle-License` entry in `META-INF/MANIFEST.MF`. It has no effect apparently. `instruction "Bundle-License", "Apache License, Version 2.0"` has no effect either.

### Steps to Reproduce (for bugs)

Create a java project with some class in it, with this `build.gradle` and Gradle 3.5:

```
group 'com.example'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'osgi'

println "Running gradle version: $gradle.gradleVersion" // 3.5

jar {
    manifest {   // org.gradle.api.plugins.osgi.OsgiManifest
        // Has no effect:
        license "Apache License, Version 2.0"

        // This doesn't work either:
        // instruction "Bundle-License", "Apache License, Version 2.0"

        // This works:
        // attributes(
        //        "Bundle-License": "Apache License, Version 2.0"
        // )

    }
}
```

### Your Environment
 * Build scan URL: https://gradle.com/s/jsiijfpwvej3a

**Comment by big-guy** [comment]
Thanks @ddekany.  This is a bug in our plugin.

You can use your workaround for now.  This will be fixed in the next release.
