### ISSUE TITLE
Re-use Scala compiler between runs

### ISSUE THREAD

**Issue by ashwinpankaj** [gradle/gradle#20579]
Relates to https://github.com/gradle/gradle/issues/13274

I am trying to resurrect https://github.com/gradle/gradle/pull/14835.

### Expected Behavior
```
Compiling with Zinc Scala compiler.
Prepared Zinc Scala inputs: 0.443 secs
Compiling 1 Scala source to /home/alpar/work/elastic/cloud/scala-services/util/build/classes/scala/main ...
Done compiling.
Completed Scala compilation: 5.929 secs
```
### Current Behavior
```
Prepared Zinc Scala inputs: 0.075 secs
Compiling 1 Scala source to /home/alpar/work/elastic/cloud/scala-services/util/build/classes/scala/main ...
Done compiling.
Completed Scala compilation: 0.694 secs
```
### Context
As discussed in 14835 , we need an option to keep Scala compiler alive across builds

**Comment by ljacomet** [comment]
Thanks for reviving this. I would encourage you to ask help from the users of the Gradle Scala plugins so that they can verify this works as expected.

**Comment by ljacomet** [comment]
Done through #20580
