### ISSUE TITLE
Laziness issue between historical metadata and GMM metadata for publishing

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#20581]
When using the publish plugin, it is possible to have the historical metadata and GMM metadata diverge in major ways.

* The GMM task generation is fully lazy. It will account for all changes to the component being published up to the point it is run.
* The historical metadata generation works by "realizing" the publication, that is extracting information from the component bound to it.

However eager "realization" of the component in the publication can happen if the following methods are called:
* for Maven
  * `publication.getArtifacts()`
* for Ivy
  * `publication.getArtifacts()`
  * `publication.getConfigurations()`
  * `publication.configurations(Action)`

Gradle should detect this and any later changes to the component should be reported as problematic as they will make the two metadata files diverge.

**Comment by xaviarias** [comment]
Implemented a reproducer project [here](https://github.com/xaviarias/issue-20581-lazy-publish).

**Comment by xaviarias** [comment]
The workaround is to avoid Maven populate the publication from component before modifying the GMM components (e.g. by skipping variants).
