### ISSUE TITLE
End of build log of included build is not shown in build scans

### ISSUE THREAD

**Issue by guylabs** [gradle/gradle#20600]
End of build log build operations are of type `org.gradle.api.internal.tasks.testing.operations.TestListenerBuildOperationAdapter$OutputProgress` but they should be of type `org.gradle.internal.operations.logging.StyledTextBuildOperationProgressDetails`.  See an example here of the attached build operations trace:
```
...
{
    "time": 1650974778365,
    "details": {
        "output": {
            "destination": "StdOut",
            "message": "BUILD SUCCESSFUL"
        }
    },
    "detailsClassName": "org.gradle.api.internal.tasks.testing.operations.TestListenerBuildOperationAdapter$OutputProgress"
},
...
```

Executing the build within IDEA, the logs are properly shown within IDEA.

### Expected Behavior
The end of build log is shown in build scans.

### Current Behavior
The end of build log is not shown in build scans.

### Context
Here a build operations trace of a build where this is happening: [trace.zip](https://github.com/gradle/gradle/files/8585575/trace.zip)

### Steps to Reproduce 
Run a task of any included build.

### Your Environment
Gradle `7.4.2`

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by wolfs** [comment]
I tried reproducing this with Gradle 7.4.2 and Gradle 8.3 though I couldn't. I'll close this. Please re-open if you see it happening again.
