### ISSUE TITLE
Task headers should continue to be displayed when using --dry-run

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2060]
### Expected Behavior
Using the `--dry-run` flag should log task headers at lifecycle level.

### Current Behavior
Usage `--dry-run`, by default, no longer displays all tasks due to logging changes in 4.0

### Context
[Slack discussion](https://gradle.slack.com/archives/C03A0MT6S/p1494981953140101)

[Related discussion](https://gradle.slack.com/archives/C03A0MT6S/p1495399738726111?thread_ts=1495221695.025781&cid=C03A0MT6S)

### Steps to Reproduce (for bugs)
Execute any build with `--dry-run` using a nightly like 20170516

**Comment by eriwen** [comment]
Spiked in https://github.com/gradle/gradle/commit/6fa1d5f60c1b8466333b506a5c2fb8f3ed7d2556

**Comment by lacasseio** [comment]
The functional test for composite builds is missing. Will close once this is done.
