### ISSUE TITLE
Documentation for how to access gradle.properties values in settings.gradle could be enhanced

### ISSUE THREAD

**Issue by AAverin** [gradle/gradle#20626]
It's either not possible or completely unclear from documentation how to access values defined in `gradle.properties` within `settings.gradle` where new dependencyResolutionManagement and repositories are defined.

Methods `findProperty` and `property` are not available on Settings class.

**Comment by bamboo** [comment]
Hi @AAverin, properties from `gradle.properties` are available in `settings.gradle` via dynamic Groovy access.

Given the following `gradle.properties` file:
```
fooBar=42
```

All of the following expressions will access the `fooBar` value property:
```
println settings.fooBar
println settings["fooBar"]
println fooBar 
```

**Comment by AAverin** [comment]
I got very confused by dot-notation properties. To use those, one has to write 
```
"${'property.with.dots'}"
```
Took me a few hours to figure out that it doesn't work any other way.
It would be great to have some actual example in the documentation on how to use properties in `settings.gradle`, it's not really mentioned anywhere.

**Comment by AAverin** [comment]
One month later and it doesn't work anymore.
@bamboo Could you provide a clear example on how to dotted property values defined in `gradle.properties` in the settings.gradle?

**Comment by AAverin** [comment]
What have worked so far is `settings["property.with.dots"]`.
I can test "${property.with.dots}" and report here if it also works.

**Comment by eskatos** [comment]
You are correct. Only the array notation works with dotted properties.
`"${property.with.dots}"` will cause an error saying that the property `property` cannot be found.
Sorry for the confusion.

This chapter really needs to be enhanced.
