### ISSUE TITLE
Tasks that show up earlier on the command line can be mysteriously skipped

### ISSUE THREAD

**Issue by jing928** [gradle/gradle#20623]
We have an application that just got upgraded to using Gradle 7.4.2 and we noticed an issue similar to https://github.com/gradle/gradle/issues/20272, but slightly different, as in my case, the task that's specified **earlier** gets skipped.

We have two tasks, A and B, and when we run:

`./gradlew A B -s`

Task A gets skipped and it only runs Task B.

We tried the `dry-run` option, with `dry-run` option, both tasks will show up, in the correct order, but when it actually runs, Task A simply disappears and there is no evidence of Task A in the console output.

### Expected Behavior

It should execute Task A and then Task B.

### Current Behavior

It only executes Task B.

### Context

The behavior only happens when we upgraded Gradle to 7.4.2, and the last working version that we know was 7.4.
Once we specify `tasks["taskB"].mustRunAfter(tasks["taskA"])`, the issue seems fixed.

### Steps to Reproduce 

Unfortunately this doesn't happen every time locally but consistently fail on CI when run inside Docker container via `docker-compose`. I understand that no steps to reproduce may make investigation difficult, I am trying to provide an explanation of what happened and what we observed, and in the meantime we are trying to find ways to consistently reproduce this issue.

### Your Environment

CI piepline running inside Docker container using OpenJDK 17.0.2.

**Comment by adrianbk** [comment]
@jing928 I think the task dependencies are as follows which might help the diagnosis: 

```
tasks["taskA"].dependsOn(tasks.findByPath(":a-different-subproject:buildAppImage"))
```

Where the task type `BuildImageTask` is from an internally published plugin:

```
tasks.register<BuildImageTask>("buildAppImage") {
    buildArgs = mapOf(
        "SOURCE_BUILD_VERSION" to buildInfo.version,
        "BUILD_TIMESTAMP" to buildInfo.timestamp
    )
    directory = file("$projectDir/app")
    tag = localImageTag
}
```

**Comment by hegyibalint** [comment]
Can you try to see if the nightly release solves this issue?
https://gradle.org/release-nightly/

The explicit dependency should not be needed, but this can be used as a workaround for now.

**Comment by ljacomet** [comment]
Closing as we know issues around this were fixed recently and without a reproducer it is impossible to be more specific.
