### ISSUE TITLE
The supplied javaHome seems to be invalid

### ISSUE THREAD

**Issue by cdietrich** [gradle/gradle#20624]
when switching to gradle 7.4.2 wrapper (from 7.4.1) i am getting this on my windows machine
(um not sure if this is related to the gradle version change or adiption changing folder name)

```
Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.
The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin\java.exe

org.gradle.tooling.GradleConnectionException: Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:55)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter.run(DefaultPhasedBuildActionExecuter.java:63)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter.run(DefaultPhasedBuildActionExecuter.java:31)
	at org.eclipse.buildship.core.internal.workspace.EclipseModelUtils.runPhasedModelQuery(EclipseModelUtils.java:111)
	at org.eclipse.buildship.core.internal.workspace.EclipseModelUtils.runTasksAndQueryCompositeModelWithRuntimInfo(EclipseModelUtils.java:86)
	at org.eclipse.buildship.core.internal.workspace.EclipseModelUtils.runTasksAndQueryModels(EclipseModelUtils.java:60)
	at org.eclipse.buildship.core.internal.workspace.DefaultModelProvider.lambda$null$4(DefaultModelProvider.java:75)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$GradleConnectionOperation.runInToolingApi(DefaultGradleBuild.java:329)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:58)
```

i have no idea where the `C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\bin\java.exe`
is picked from

similar problem on cmd line
```
```
it also does not work with an old style java home
```C:\PROGRA~1\ECLIPS~2\jdk-11.0.15.10-hotspot```

```
HOMEPATH=\Users\cdietrich
JAVA_HOME=C:\PROGRA~1\ECLIPS~2\jdk-11.0.15.10-hotspot
Path=C:\Program Files\Eclipse Adoptium\jdk-11.0.15.10-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\GnuPG\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Git\cmd;C:\Users\cdietrich\AppData\Local\Microsoft\WindowsApps;C:\Users\cdietrich\Downloads\apache-maven-3.6.3\bin;
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
windir=C:\WINDOWS
```

any idea where to start digging?

**Comment by cdietrich** [comment]
it loks like the uninstaller of adoptium left
`C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot\lib`
when renaming to
`C:\Program Files\Eclipse Foundation\jdk-11.0.12.7-hotspot_\lib` it works as another jvm seems to be picked

is it possible to enhance this magic search for a jvm?

**Comment by hegyibalint** [comment]
It really seems like this is a local setup issue. Currently, we have no plans to attempt to search for _valid_ JVMs, or at least detect if it's a broken one.

**Comment by Lothrazar** [comment]
if anyone in future is reading this, yes its a local setup issue. the local-setup fix is to delete any old lingering folders similar to 
`C:\Program Files\Eclipse Foundation\jdk-11.0.12`
in the above comments, keeping only the ones for Working jdks. (and so the root folder only has one jdk for your main java version) . in my case i had the same error but in java 17 when i installed 17.0.4.1+1 and it uninstalled 17.0.12.something and left the libs.

So yeah cleanup the folder, reboot your pc, confirm your 'java--version' and then the gradle picks it up and runs .

**Comment by dsound-zz** [comment]
> if anyone in future is reading this, yes its a local setup issue. the local-setup fix is to delete any old lingering folders similar to `C:\Program Files\Eclipse Foundation\jdk-11.0.12` in the above comments, keeping only the ones for Working jdks. (and so the root folder only has one jdk for your main java version) . in my case i had the same error but in java 17 when i installed 17.0.4.1+1 and it uninstalled 17.0.12.something and left the libs.
> 
> So yeah cleanup the folder, reboot your pc, confirm your 'java--version' and then the gradle picks it up and runs .

This is exactly what happened to me on Windows 11. Uninstalled Adoptium yet the folder remained. Was driving me nuts.

**Comment by Jayasubin** [comment]
> if anyone in future is reading this, yes its a local setup issue. the local-setup fix is to delete any old lingering folders similar to `C:\Program Files\Eclipse Foundation\jdk-11.0.12` in the above comments, keeping only the ones for Working jdks. (and so the root folder only has one jdk for your main java version) . in my case i had the same error but in java 17 when i installed 17.0.4.1+1 and it uninstalled 17.0.12.something and left the libs.
> 
> So yeah cleanup the folder, reboot your pc, confirm your 'java--version' and then the gradle picks it up and runs .

I faced the same issue; Java 19 folder was left there after uninstalling Java 19. Deleting it fixed the issue

**Comment by NatumanyaGuy** [comment]
> 

Worked for me!!! Thanks

**Comment by pazoozooCH** [comment]
This seems to get me all the time - this time, installed a newer version of Andriod Studio and apparently, the deinstallation left a dangling `jre` folder. Why doesn't Gradle respect the `JAVA_HOME` environment variable?

**Comment by ljacomet** [comment]
> Why doesn't Gradle respect the `JAVA_HOME` environment variable?

Gradle launch scripts do respect this env var.

Most of the reported problems here happen with the usage of the tooling API by an IDE. You may want to file these issues with VSCode itself.

**Comment by atennapel** [comment]
I definitely have had this issue with the Gradle CLI. The launch scripts work correctly and use the right JVM but then Gradle starts and somehow decides to not use the `JAVA_HOME` JDK but an older one (which was uninstalled and left an empty dir).

**Comment by yoav-klein** [comment]
I had this on my work laptop, a Windows machine which is patched and managed by the IT department. It happened with Gradle 7.5.1, and it happened after they installed a new Zulu version (23), and the old version (17) left it's root directory in `C:\Program Files\Zulu\zulu-17`. 

In my case, I couldn't remove this directory, so I upgraded the Gradle version and it fixed.

**Comment by muhammad-fiaz** [comment]
i had similar issue by doing uninstalling my oracle `jdk 24` and installed jdk 25 by [ Temurin® JDK ](https://adoptium.net/en-GB/temurin/releases) and my flutter project go this invalid java issue

```bash
FAILURE: Build failed with an exception. * What went wrong: The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\Program Files\Java\jdk-24\bin\java.exe * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. Running Gradle task 'assembleDebug'... 1,356ms Error: Gradle task assembleDebug failed with exit code 1
```

 and i have resolved this issue by

1. first adding to env path in system

<img width="736" height="248" alt="Image" src="https://github.com/user-attachments/assets/c555d1c9-8e0e-47b9-863a-34d5cf0bd93c" />

after adding the above open `path` edit

<img width="263" height="252" alt="Image" src="https://github.com/user-attachments/assets/c554c60e-3424-458e-9d3b-bf1600f44e1b" />

after that add `%JAVA_HOME%\bin` (make sure no duplicate java_home there)

<img width="504" height="82" alt="Image" src="https://github.com/user-attachments/assets/4414874d-0339-4d8b-9c37-b867a4ac802b" />

now done and also delete the `C:\Users\<USERNAME>\.gradle` Folder whole and try running your application again it works for me :)
