### ISSUE TITLE
Gradle cannot download jython (among others) from behind a web proxy

### ISSUE THREAD

**Issue by slbruce** [gradle/gradle#2063]
I am behind a corporate firewall.  As part of the jar task the jythonDownload task is called.  Even though the proxy is setup correctly in gradle.properties gradle seems to not use the proxy and always fails

### Expected Behavior
Gradle should use the proxy (either http or https) as defined in the gradle.properties file in the Gradle home directory and download the correct files.

### Current Behavior
```
9:59:38 AM: Executing external tasks 'clean jar'...
:clean
:compileJava UP-TO-DATE
:jythonDownload
Downloading Jython library: requests with version 2.13.0
:jythonDownload FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jythonDownload'.
> javax.net.ssl.SSLHandshakeException: Received fatal alert: access_denied

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
It is important to note that other files that gradle needs to download are downloaded successfully.  It is when it comes to this resource - it fails.  It seems that the SSLSocket is not being passed the proxy information in this case

### Context
Trying to set up a gradle project.  It means that I cannot perform any task from behind the corporate firewall since this task "jythonDownload" is blocked because it does not utilise the proxy correctly.

### Steps to Reproduce (for bugs)
Trying to build this project: [https://github.com/xebialabs-community/xlr-hpe-alm-octane-plugin](https://github.com/xebialabs-community/xlr-hpe-alm-octane-plugin)
I have added the correct gradle.properties to my home directory, to the directory of the project and as system properties to the gradle build.

### Your Environment
Grunt 2.13
Happens on both Windows 10 and Linux CentOS machines
Proxy is correctly set in properties
[grade.output.txt](https://github.com/gradle/gradle/files/1006841/grade.output.txt)

 * Build scan URL:

**Comment by bmuschko** [comment]
I am assuming `jythonDownload` comes from the external plugin `com.github.hierynomus.jython`. You might want to ping that project first to see if it is even evaluating those proxy properties.

**Comment by slbruce** [comment]
@bmuschko you are right.  This is an issue with that project itself.  I will close the issue.

Thanks for your input
