### ISSUE TITLE
Missing Example Project Link on Docs

### ISSUE THREAD

**Issue by rifqimfahmi** [gradle/gradle#20640]
Docs on [this page](https://docs.gradle.org/current/userguide/core_dependency_management.html) doesn't provide the `example project` link that user can refer to. doc snippet:

```
....We’ll explore the main concepts with the help of an example project....
```

### Expected Behavior

There is external link user can refer to as example project 

### Current Behavior

no external link to look at the example project

### Your Environment

Build scan URL:

**Comment by jbartok** [comment]
Instead of linking to a sample, we should just rephrase the text to mention that we are using an imaginary project to explain the concept.

**Comment by Scrappers-glitch** [comment]
I think this could be fixed easily by just interpreting this diagram: 

![image](https://user-images.githubusercontent.com/60224159/226206114-69ab0f0b-a1a6-4c5b-943d-bf701e06531b.png)

Into a `build.gradle` file, for example: 
```java
/** 1) Define artifacts sources, the repositories closure: */
repositories {
   /** 2) Defime remote and local repositories, those are the repositories used for 'dependency resolution' */
    google()
    mavenCentral()
    mavenLocal()
}

/** 3) Define the dependencies closure for downloading artifacts from remote repos or use local artifacts: */
dependencies {
   /** 4) Your requested artifacts go here: */
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.google.guava:guava:31.1-jre'
}
```

If that is okay with you, you can give me a chance to submit a PR.

**Comment by lkasso** [comment]
While some of this has already been addressed in old commits, I have made a complete update/edit of this page to close this issue.
