### ISSUE TITLE
antlr dependency configuration ignores classifier

### ISSUE THREAD

**Issue by NikiAtSalesforce** [gradle/gradle#20666]
### Expected Behavior

When using the antlr plugin with a forked version of antlr that includes a classifier in the maven coordinate the gradle antlr dependency configuration should include the classifier when searching for the dependency.

### Current Behavior

build.gradle:
```
dependencies {
  antlr 'org.antlr:antlr4:4.5-fork:complete'
}
```

The task :generateGrammarSource fails on gradle version >= 6, with the following error message:
```
Execution failed for task ':generateGrammarSource'.
> Could not resolve all files for configuration ':antlr'.
   > Could not find org.antlr:antlr4:4.5-fork.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/antlr/antlr4/4.5-fork/antlr4-4.5-fork.pom
       - file:/data/m2/repository/org/antlr/antlr4/4.5-fork/antlr4-4.5-fork.pom
       - https://<PRIVATE MAVEN REPO>/org/antlr/antlr4/4.5-fork/antlr4-4.5-fork.pom
     Required by:
         project :
```

### Context

I have a project that depends on a forked version of antlr. This project is currently using gradle version 4.10.2 and works as expected. I attempted to update to gradle 7+ and have been unable to due to this issue. Through trial and error I have determined that this behavior started on gradle 6 and I have been able to update the project to gradle 5.6.4.

### Steps to Reproduce 

include an antlr dependency that uses a classifier in build.gradle. Run the task :generateGrammarSource

I have stepped through gradle in a debugger and it seems like the issue is in the method [AbstractRepositoryMetadataSource::parseMetadataFromArtifact](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/AbstractRepositoryMetadataSource.java#L76). This method assumes there is no classifier on the artifact. The calling method, [AbstractRepositoryMetadataSource::create](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/AbstractRepositoryMetadataSource.java#L67) has a ComponentOverrideMetadata parameter that contains a list of type IvyArtifactName which includes a field 'classifier'. However this parameter is not passed along to the parse method.

### Your Environment

Ubuntu 20.04
OpenJDK 11
Gradle 7.4.2 (also tested with 7.0.1, 6.9, 6.0, working on 4.10.2 and 5.6.4)

**Comment by ljacomet** [comment]
Gradle is attempting to resolve the _metadata_ of your library. A maven POM file has no classifier concept.
If what you are looking for is a bare jar, you will have to tell Gradle to accept that situation. See the documentation on [metadata sources](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources).

**Comment by ljacomet** [comment]
Closing as this is likely to be a setup issue and not a Gradle bug.
