### ISSUE TITLE
Display Build Completion Time in Console Output

### ISSUE THREAD

**Issue by mbach979** [gradle/gradle#20676]
While developing I often kick off a command line build (or think I do), then either get distracted by or switch to another task.   Depending on levels of sleep and/or caffeine, this often leads me to forget whether I kicked off the build or not, and given that I use the same terminal to start builds, I often have a nice "BUILD SUCCESSFUL in XXXs" but often don't know when that was and have to rerun the build.  It would be nice to have a timestamp in the final build step.  I know that I can do shell commands to print the datetime after the completion, but that is just annoying. 

### Expected Behavior
Print something like the following at the completion of the build to the console:

`BUILD SUCCESSFUL in 123s @ 2345-06-07 12:34+01:00`

Time format TBD but should include day, time, and time zone/offset.  ISO-8601 formatted date time would be fine too.

### Current Behavior

`BUILD SUCCESSFUL in 123s`

### Context

Would just be a quality of life improvement for me/other developers who use the command line.

**Comment by hegyibalint** [comment]
We find it improbable that we are going to spend some time on this. Also, there is a lot of expectation about the last line, and would probably break a lot of systems.

We had the idea that if you want to achieve this:
 - Use a CLI prompt, which displays time
 - Write a script which aliases `gradle`, and prints the start/end times
 - So on and so forth...
