### ISSUE TITLE
Error: Not found wrapperScript: /home/vsts/work/1/s/gradlew

### ISSUE THREAD

**Issue by yugeshmothukuru** [gradle/gradle#20671]
Hi Team,
we are facing wrapper script not found issue even though provided with right path where the file present.
Please let us know what would be the issue.

thanks,
Yugesh

**Comment by yugeshmothukuru** [comment]
- task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: '$(System.DefaultWorkingDirectory)/xyz-repo'
        tasks: 'build --stacktrace --info'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false

**Comment by ljacomet** [comment]
@yugeshmothukuru This does not look like the setup of the Gradle provided GitHub action for running Gradle builds.

Check with the provider of the action you are using or switch to [the recommended way](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle).
