### ISSUE TITLE
New console output is misleading with continuous build

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#2068]
When I run with continuous build, the build remains "EXECUTING" with a timer that counts up and a worker listed as "IDLE".  Nothing is actually happening and the build is waiting for changes.

Here's an example:
https://asciinema.org/a/clq87m7hdpabzz5cs90njex5n

**Comment by big-guy** [comment]
And I've noticed that the build timer doesn't reset whenever the build does re-execute.

**Comment by w25r** [comment]
What do you think the ideal behavior would be?

The timer resetting when the build restarts?  Hiding the progress bar while it's waiting for changes?

**Comment by big-guy** [comment]
I think hiding the progress bar makes sense initially.  The timer should reflect the time of the current build and not the overall time.

Maybe in the future, we could display something about the actively running deployments (these are processes that continue running after the build is complete).

**Comment by eriwen** [comment]
I think the UX here should be that we show `<------> WAITING` and the `> IDLE` workers remain as they do today. We want to do this in a way that it doesn't flicker at the end of the build and of course works for non-continuous builds.

If it would take a lot of rework to achieve this we can probably hide the build status and see what it looks like.

We can listen to the RootBuildLifecycle events to manage this.
