### ISSUE TITLE
Set number of daemons to be kept fresh

### ISSUE THREAD

**Issue by vojkny** [gradle/gradle#20698]
### Expected Behavior

We are using gradle to build modules in long-lived CI environment. It happens that we build up to 20 modules in parallel and we often wait on these:

> Starting a Gradle Daemon, 1 busy and 32 stopped Daemons could not be reused, use --status for details

The daemon takes some time to start and significantly slows down the pipelines.

It would be great if we could set something like:

```
export GRADLE_MINIMUM_FRESH_DAEMONS=20
```

And gradle would try to keep these fresh and ready to use.

### Current Behavior
Gradle stops daemons after their use.

### Context
This would significantly speeds up our CI.

**Comment by knyttl** [comment]
No, these are long-lived custom gitlab runners. Gitlab runner will not kill any gradle process.

> Can you see the daemon's log and see why they are stopped ($GRADLE_HOME/daemon/*.log,

I guess these are stopped, once they are not used for some time:

```
2022-05-09T18:46:07.205+0000 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Removing daemon address: [80370979-ec8e-45a0-8b50-60861e58ef0f port:37335, addresses:[localhost/127.0.0.1]]
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
2022-05-09T18:46:07.205+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
2022-05-09T18:46:07.205+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2022-05-09T18:46:07.205+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

> Check that you don't use the --no-deamon option (as it stops the daemon after the build)

No I don't use this feature.

**Comment by ljacomet** [comment]
According to [documentation](https://docs.gradle.org/current/userguide/gradle_daemon.html#header), a daemon will stop after 3 hours idle or if there is memory pressure on the machine.

You can change that first value if you want. See [documentation](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) about `org.gradle.daemon.idletimeout`.

If you believe that there should be no 3 hours pauses between builds, you will have to keep investigating why daemons disappear.

**Comment by knyttl** [comment]
> if there is memory pressure on the machine.

How do you distinguish this? Would it be possible to extend the daemon logs so we know the reason of the daemon finishing? Eg.

1.

> Removing daemon address: [80370979-ec8e-45a0-8b50-60861e58ef0f port:37335, addresses:[localhost/127.0.0.1]]
Daemon vm is shutting down **because of memory pressure**.

2.

> Removing daemon address: [80370979-ec8e-45a0-8b50-60861e58ef0f port:37335, addresses:[localhost/127.0.0.1]]
Daemon vm is shutting down **because of 3h timeout**.

3.

> Removing daemon address: [80370979-ec8e-45a0-8b50-60861e58ef0f port:37335, addresses:[localhost/127.0.0.1]]
Daemon vm is shutting down **because of manual user request**.

**Comment by ov7a** [comment]
Sorry for the late reply.

For the original request - This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

For shutting down reasons, please follow on this one:
* https://github.com/gradle/gradle/issues/15492
