### ISSUE TITLE
Initial heap size set to a larger value than the maximum heap size

### ISSUE THREAD

**Issue by yugeshmothukuru** [gradle/gradle#20699]
Hi Team,
We are facing Heap Size issue while running gradle task in multi repository at Azure devops.
could you please help us to sort out this issue.
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        
        tasks: 'build -x test'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false

Thanks,
Yugesh

**Comment by ljacomet** [comment]
@yugeshmothukuru This does not look like the setup of the Gradle provided GitHub action for running Gradle builds.

Check with the provider of the action you are using or switch to [the recommended way](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle).
