### ISSUE TITLE
Update Kotlin logo used on code snippets

### ISSUE THREAD

**Issue by mahozad** [gradle/gradle#20700]
The Kotlin language has updated its branding, including its logo ([YouTrack issue](https://youtrack.jetbrains.com/issue/KT-46792/Update-community-graphic-assets-to-the-new-Kotlin-visual-style), other [YouTrack issue](https://youtrack.jetbrains.com/issue/KT-44340/Design-a-new-Kotlin-visual-style)).

Update the icon used on code snippets in Gradle website to the new one.
The new logos can be grabbed from the [Kotlin official website](https://kotlinlang.org/docs/kotlin-logo.html)

| Old | New |
| ---- | ----- |
|  ![Old icon](https://user-images.githubusercontent.com/29678011/167393385-31e815f9-cd64-4011-9b41-a84ac6b32272.png) |  ![New icon](https://user-images.githubusercontent.com/29678011/167393478-d660506f-11fc-431c-8d1f-8d0e40337760.png) |

### Expected Behavior
Code snippets should show new Kotlin logo.

### Current Behavior
They show old Kotlin logo.

### Context
Gradle website and documentation.

**Comment by jvandort** [comment]
Fixed by #21295
