### ISSUE TITLE
Progress bar does not stay visible on Windows 10

### ISSUE THREAD

**Issue by w25r** [gradle/gradle#2070]
When running a build with lots of output, the output pushes the progress bar off the visible screen, until the output slows down, and then behaves as expected.

### Expected Behavior

Progress bar should always be at the bottom of the terminal screen, as it is on other terminals (or at least Mac)

### Current Behavior

Fast output pushes the progress bar down out of sight, and it returns when output slows.

### Context

It is more aesthetic than a functional problem.  

### Steps to Reproduce (for bugs)

Clone `gradle/gradle` on a Windows 10 machine and run `gradlew clean --info --parallel`

### Your Environment
Windows 10 
Command prompt

**Comment by eriwen** [comment]
@w25r Is this only the case when there's lots of output?

**Comment by w25r** [comment]
I think what happens is that each line of output causes the progress bar to be pushed off the visible screen, and then when the progress bar is updated, it redraws in the right position... but if there is fast enough output that the progress bar isn't updating fast enough, it is pushed out of site altogether.  

Is there an equivalent to https://asciinema.org/ for Windows?

**Comment by big-guy** [comment]
It's probably easiest to just record the screen on Windows.

**Comment by lacasseio** [comment]
The way it's currently rendering the parallel console is the same on both Windows and *nix system. On Mac, it seems to be fast enough that you don't see any problem. On Windows, I'm not sure if it's due to running in a VM or if it also happens on actual hardware. I remember trying to change the rendering by only updating the output area when we flush the console but didn't see much improvement. We could revisit this solution.

**Comment by w25r** [comment]
I'm not running in a VM, I'm running on physical hardware.

**Comment by w25r** [comment]
I tested on an older, slower mac and saw the same problem.  So this may not be an issue at all.  Perhaps the new console just looks better with a super fast processor.

**Comment by pun-ky** [comment]
I also cannot see progress bar on 4.02 and 4.1 when running git bash on windows. But when I use embedded terminal in IntelliJ with Git Bash it is visible. Very strange :/

**Comment by lacasseio** [comment]
Rich console is still an issue on Windows. I don't think it's wise to disregard these issues.
