### ISSUE TITLE
Only build and deploy affected modules in a Gradle Monorepo / Multi-Module Project

### ISSUE THREAD

**Issue by mklueh** [gradle/gradle#20705]
I'm trying to setup my monorepo for quite some time now to contain multiple applications, but only build and release those that are affected by direct or indirect changes (of module dependencies).

For my frontend project I'm using [NX](https://nx.dev/) which simply allows to do this in my Github Actions workflow.yml:

```
- run: nx affected --target=build --parallel=3
- run: nx affected --target=deploy-netlify --parallel=3
```

The first line builds all modules of the dependency tree that have changes.
The second line deploy all modules with changes (that were built previously)

I'm no frontend guy but this approach was straight forward and I got that up and running easily.

I'd like to have something similar in Gradle and I've tried some third-party libraries for that with no success (outdated, not maintained, not working for some reason or because I configured something wrong)

Are there plans to integrate the described feature in some way one can set it up easily within hours instead of days / weeks, or is there a common approach already I have overlooked?

**Comment by dsilvasc** [comment]
You can do this yourself for now with:

```kotlin
fun addTransitiveConsumersTask(root: Project, taskName: String, vararg dependencyNames: String) {
  root.allprojects {
    val project = this
    val newTask = project.tasks.register(taskName)

    newTask.configure { dependsOn(dependencyNames) }

    if (project.state.executed) {
      val tasks = project.tasks
      for (name in dependencyNames) {
        try {
          tasks.named(name)
        } catch (e: UnknownTaskException) {
          tasks.register(name)
        }
      }
    } else afterEvaluate {
      val tasks = project.tasks
      for (name in dependencyNames) {
        try {
          tasks.named(name)
        } catch (e: UnknownTaskException) {
          tasks.register(name)
        }
      }
    }
    // delay querying the dependency graph in a closure, because this task gets defined before projects define
    // their dependencies
    newTask.configure {
      dependsOn(Callable {
        project.configurations
          .findByName("runtimeClasspath")
          ?.getTaskDependencyFromProjectDependency(false, taskName)
    })
    }
  }
}

allprojects {
  transitiveConsumers.addTransitiveConsumersTask(project, "checkDependents", "check")
  transitiveConsumers.addTransitiveConsumersTask(project, "releaseDependents", "release")
}
```

and then this will run the `check` task for `some-library` and all projects in the repo that consume it directly or transitively as a compile or runtime dependency:

```bash
./gradlew some-library:checkDependents
```

**Comment by gad2103** [comment]
i would also love something like this as part of gradle itself

**Comment by ov7a** [comment]
Sorry for the late reply

Thank you for your interest in Gradle!

There’s no plan to change it. This issue will be closed.

***

For building code, the Gradle story is based on remote caching, configuration cache, and UP-TO-DATE checks which give you work avoidance. For deploying, Gradle does not have specific support as the core deploy tasks are never up-to-date.

**Comment by mklueh** [comment]
I've solved it using https://nx.dev/ in the meantime. 

Although this involves Node additionally, it works perfectly
