### ISSUE TITLE
Dependencies declared with a project's buildscript() method are not available to the build scripts of all its sub-projects

### ISSUE THREAD

**Issue by basil** [gradle/gradle#2072]
[Section 43.6](https://docs.gradle.org/current/userguide/organizing_build_logic.html#sec:build_script_external_dependencies) of the documentation states that for multi-project builds, "the dependencies declared with a project's `buildscript()` method are available to the build scripts of all its sub-projects." But I have found that this is not the case for one particular repository.

### Steps to Reproduce (for bugs)

Clone [this Git repository](https://github.com/basil/buildscript), then run `./gradlew clean`.

### Expected Behavior

The clean task should run successfully.

### Current Behavior

The build fails with this exception:

```
Could not compile build file 'docker/postgres/build.gradle'.
> startup failed:
  build file 'docker/postgres/build.gradle': 1: unable to resolve class com.bmuschko.gradle.docker.tasks.image.DockerPullImage
   @ line 1, column 1.
     import com.bmuschko.gradle.docker.tasks.image.DockerPullImage
     ^
  
  1 error
```

This shouldn't happen, because the dependency that can't be resolved in `:docker:postgres` is declared in `:docker`. The documentation states that "the dependencies declared with a project's buildscript() method are available to the build scripts of all its sub-projects", so the dependencies declared in `:docker` should be available to the build script of `:docker:postgres`.

Even more strange: if you copy the `buildscript` block from `:docker` to `:docker:postgres` (which shouldn't be necessary, per the documentation), the `clean` task fails with a different error:

```
Could not compile build file 'docker/build.gradle'.
> startup failed:
  build file 'docker/build.gradle': 1: unable to resolve class com.bmuschko.gradle.docker.tasks.image.DockerPullImage
   @ line 1, column 1.
     import com.bmuschko.gradle.docker.tasks.image.DockerPullImage
     ^
  
  1 error
```

Notice that the class can't be resolved in `docker/build.gradle` (as opposed to `docker/postgres/build.gradle` as in the previous). This is weird because `:docker` _still has_ the `buildscript` block which adds the dependency! So why is the import not found in `:docker`!?

### Context

I'm trying to create Docker tasks from two separate projects and running into the import quandary described above.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/td7mqicaf4rd6

**Comment by oehme** [comment]
By calling `tasks.getByPath(':docker:postgres:pullImage')` you are forcing `:docker:postgres` to be configured before `:docker` has been configured, so the classpath is not yet set up correctly.

Instead just do 

`tasks.clean.dependsOn(':docker:postgres:pullImage')`

**Comment by basil** [comment]
Hi @oehme, thanks for your reply, and I definitely appreciate the workaround of using `dependsOn` with a String argument rather than a Task argument. But this workaround isn't always feasible, and the problem still exists in the general case. To see why, look at this [new example](https://github.com/basil/buildscript/commit/309f17012c1f5f913e7fb73a88de7744053feff7) I came up with. In this case, the same problem still exists when you execute `./gradlew clean`. And like the previous example, adding the `buildscript` block to `:docker:postgres` weirdly breaks `:docker`. But your workaround cannot be applied in this scenario. I think there is a more general issue here, namely that if a subproject is evaluated before its parent subproject (which seems legitimate, given my use case here), and if it adds classes to its `buildscript` environment, and then its parent is evaluated, those classes cannot be used in its parent. This is a bug.

**Comment by oehme** [comment]
Reaching across project boundaries like this is very prone to ordering bugs, so I can only recommend not doing it. Projects should interact via artifacts and dependencies, not by reaching into each other's model. E.g.

```

configurations {
  distContent
}

dependencies {
  distContent project(':docker:postgres')
}

distributions.main.contents.from distContent
```

Also I strongly recommend putting all your buildscript dependencies in the root project.

I agree on your point that the second exception is a bug, though one that can easily be worked around by putting all buildscript dependencies in the root project.

**Comment by basil** [comment]
Hi @oehme, thanks for clarifying that using `tasks.getByPath()` causes projects to be coupled. I thought that it didn't. Perhaps [the documentation for decoupled projects](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:decoupled_projects) could be updated to mention this.

I'm glad you agree that the second exception is a bug, and thanks also for the workaround of putting all `buildscript` dependencies in the root project (this worked for me).

Regarding your point about projects interacting via artifacts and dependencies, not by reaching into each other's model, I can't see how this would work if one wants to include the files from one subproject's distribution into another subproject's distribution. See, for example, my attempt [here](https://github.com/basil/buildscript/commit/2ae98aba8e8607979a9963df0251a11c958a48cb). Running the `:installDist` task shows `NO-SOURCE`, even though I'm trying to use the sub-project distribution contents through a custom configuration. (Not shown, I tried to use various permutations of `builtBy` to no avail.) And might I add, this decoupled version (which doesn't even work) is a lot more verbose than the coupled version and required me to declare the custom configuration twice (both in the producer subproject and consumer subproject), so something feels wrong.
