### ISSUE TITLE
Make gradle properties comply with modern standards

### ISSUE THREAD

**Issue by BastienAr** [gradle/gradle#2074]
Currently it's not possible to add dotted properties in grande.properties like we do in java (domain.subdomain.property1, domain.subdomain.property2, etc...). In addition, all properties are treated as String, so it's really not user-friendly to use a property as - let's say - boolean.

As-is, gradle.properties file is pretty basic and not really useful in a complex environment.

**Comment by bmuschko** [comment]
I don't see why Gradle would not be able to use properties with dot characters in them e.g.

__gradle.properties__:

    domain.subdomain.property1=helloworld

__build.gradle__:

    println project.findProperty('domain.subdomain.property1')

Apart from that project properties behave like system properties. System properties also just evaluate to Strings. Sure we could make an educated guess by evaluating the runtime value but with your argument I am surprised you don't complain about Java.

**Comment by oehme** [comment]
Closing in favor of #2885
