### ISSUE TITLE
Remember to double check the releases.xml update after RC2 is built

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#20780]
The promotion build did not automatically update this last time, if may need to be manually updated after RC2 is built.

See: https://github.com/gradle/gradle-promote/pull/92

**Comment by ice1000** [comment]
Is this blocked? I can't wait to see 7.5 RC 2!!

**Comment by tresat** [comment]
This ticket exists to ensure we don't forget to double-check a potential internal issue after we do release 7.5 RC 2.  It will have no effect on the timing of the release.

**Comment by ice1000** [comment]
Thanks!
