### ISSUE TITLE
`ResolvedArtifactResult` cannot be fingerprinted when there are outputs in 7.5-rc-1

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#20785]
### Expected Behavior

I expect this to work

### Current Behavior

It does not and only works if there are no outputs defined.

```
Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':libraries:core-lib:printreleaseRuntimeClasspathComponents'.
> Cannot fingerprint input property 'resolvedArtifacts': value '[<all artifacts listed but removed for brevity>]' cannot be serialized.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================
```

### Context

I was trying to reuse the new `ArtifactCollection.getResolvedArtifacts()` API in Gradle 7.5-rc-1 to make some tasks compatible with configuration caching.

### Steps to Reproduce 

```kotlin
import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.artifacts.Configuration
import org.gradle.api.artifacts.result.ResolvedArtifactResult
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.TaskProvider
import org.gradle.internal.component.external.model.ModuleComponentArtifactIdentifier

public abstract class ExampleTask : DefaultTask() {
  @get:Input public abstract val resolvedArtifacts: SetProperty<ResolvedArtifactResult>
  @get:OutputFile
  public abstract val outputFile: RegularFileProperty

  @TaskAction
  public fun doStuff() {
    val identifiersToVersions =
      resolvedArtifacts
        .get()
        .map { it.id }
        .filterIsInstance<ModuleComponentArtifactIdentifier>()
        .associate { component ->
          val componentId = component.componentIdentifier
          val identifier = "${componentId.group}:${componentId.module}"
          identifier to componentId.version
        }

    outputFile.asFile.get().writeText(identifiersToVersions.toString())
  }

  public companion object {
    public fun register(project: Project, configuration: Configuration): TaskProvider<ExampleTask> {
      return project.tasks.register(
        "print${configuration.name}Components",
        ExampleTask::class.java
      ) {
        resolvedArtifacts.set(configuration.incoming.artifacts.resolvedArtifacts)
        outputFile.set(project.layout.buildDirectory.file("reports/example/$name.txt"))
      }
    }
  }
}
```

Then simply register the above task and run it to reproduce the previous message + failure. IF you remove the `outputFile` property, it works again.

### Your Environment

Build scan URL:

**Comment by ZacSweers** [comment]
After looking at examples [here](https://docs.gradle.org/7.5-rc-1/userguide/more_about_tasks.html#sec:task_input_using_dependency_resolution_results) and [here](https://docs.gradle.org/7.5-rc-1/samples/sample_tasks_with_dependency_resolution_result_inputs.html), I noticed that the result is always mapped into some other type. I suppose this implies it must always be mapped and confirmed it does work if I do this in the provider. Maybe this is intended use, but in that case I think it would help if the docs made this extremely explicit as they currently seem to just do the mapping as examples of slicing the data rather than out of necessity.

**Comment by eskatos** [comment]
>  I suppose this implies it must always be mapped and confirmed it does work if I do this in the provider. Maybe this is intended use, but in that case I think it would help if the docs made this extremely explicit as they currently seem to just do the mapping as examples of slicing the data rather than out of necessity.

This is the case yes. `ResolvedArtifactResult` can't be used as input directly because it contains both metadata and files and it is impossible to annotate it properly. You have to map it to inputs you can annotate.

This is already called out in the documentation at: https://docs.gradle.org/7.5-rc-1/userguide/more_about_tasks.html#:~:text=Given%20the%20ResolvedArtifactResult%20type%20contains%20both%20metadata%20and%20file%20information%2C%20instances%20need%20to%20be%20transformed%20to%20metadata%20only%20before%20being%20wired%20to%20an%20%40Input%20property

If this needs more clarification, could you please make a proposal for documentation change?

**Comment by eskatos** [comment]
Thanks for reporting this Zac.
Fix https://github.com/gradle/gradle/pull/20826 will be in 7.5 RC2

**Comment by ZacSweers** [comment]
Thanks!
