### ISSUE TITLE
Gradle Module Metadata should not have constraint with null version

### ISSUE THREAD

**Issue by kostya3264** [gradle/gradle#20791]
### Expected Behavior
If there is  at least one  dependency constraint without any version,  Gradle Module Metadata should not be generated. 
Validation should fail (based on the documentation https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md#variants-value)

### Current Behavior
The Gradle Module Metadata can have  a dependency  constraint without any version. Validation fails only if all constraints don't have a version.

### Context
We are trying  to add  a library which contains dependency constraint with Null version. Our build is failing with the following exception:
```
  Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve {lib_with_incorrect_dep_constraint}.
  Required by:
     project {project-name}
  Caused by: java.lang.NullPointerException
```
Is there any way to suppress reading Gradle Module Metadata file from dependency?

### Steps to Reproduce 
Create a constraints section in build.gradle with several  dependencies, at least one of them should have a version, the other one should be without any version (the order doesn't matter), something like this

```
dependencies {
      constraints {
        implementation 'commons-io:commons-io'
        implementation 'joda-time:joda-time:2.9.9'
    }
}
```

### Your Environment
Gradle 6.9.2

**Comment by hegyibalint** [comment]
The fix will come with Gradle 7.5: #20182
If we are going to do a 6.9.3, we are also going to fix this issue (#20189).
