### ISSUE TITLE
Unqualified hasProperty does not work in afterEvaluate block

### ISSUE THREAD

**Issue by nlwillia** [gradle/gradle#2080]
I've noticed that property checking in an `afterEvaluate` block only works if `project.hasProperty` is called.
````
println "        hasProperty('prop') = " + hasProperty('prop')
println "project.hasProperty('prop') = " + project.hasProperty('prop')

ext.prop = true

println "        hasProperty('prop') = " + hasProperty('prop')
println "project.hasProperty('prop') = " + project.hasProperty('prop')
println "                       prop = $prop"


afterEvaluate {
	println "        hasProperty('prop') = " + hasProperty('prop')
	println "project.hasProperty('prop') = " + project.hasProperty('prop')
	println "                       prop = $prop"
}
````
Results in:
````
        hasProperty('prop') = false
project.hasProperty('prop') = false
        hasProperty('prop') = true
project.hasProperty('prop') = true
                       prop = true
        hasProperty('prop') = null # not what I expected
project.hasProperty('prop') = true
                       prop = true
````
The same thing happens in an allprojects block.  What seems to be happening is that `hasProperty` is not delegating to the project, and is instead defaulting to Groovy's [hasProperty](http://docs.groovy-lang.org/latest/html/api/groovy/lang/MetaObjectProtocol.html#hasProperty-java.lang.Object-java.lang.String-) which unlike Project can return null.  This is surprising when other Project elements (ex: `name`) delegate contextually.

This is in Gradle 3.5.

**Comment by blindpirate** [comment]
I think the reason is that Groovy's `hasProperty` has higher priority than method in closure's `delegate` and `owner` in method selection. `hasProperty` has the same priority with `is`/`with`/`println`, etc. It seems that there's little thing Gradle can do.

**Comment by blindpirate** [comment]
Closed due to unresponsiveness.
