### ISSUE TITLE
GitHub scheduled "Code scanning - action" runs on forks

### ISSUE THREAD

**Issue by markslater** [gradle/gradle#20808]
### Expected Behavior
Scheduled GitHub actions should not execute on forks because it uses up contributors' GitHub CI/CD credit.

See discussion about solving this problem [here](https://github.community/t/do-not-run-cron-workflows-in-forks/17636/3).

### Current Behavior
The "Code scanning - action" runs every day on my fork of `gradle/gradle`

### Context
Having recently fetched latest from upstream, I get notification of [a (failing) GitHub action on master](https://github.com/markslater/gradle/actions) every day.  The "Code scanning - action" runs for ~20 minutes using up the credit in my free tier GitHub account.
### Steps to Reproduce 
Fork `grade/gradle`.  Wait for 24 hours.
### Your Environment
N/A

**Comment by blindpirate** [comment]
Hi @markslater , thanks for reporting. I've managed to reproduce it, and I believe it's fixed in https://github.com/gradle/gradle/commit/0109a3c028c6ac8c6040c5dfcbdec2e5a9c51539 . Can you sync with `gradle/gradle` repo?

**Comment by markslater** [comment]
Hi @blindpirate, the action is still running on forks, e.g. https://github.com/markslater/gradle/actions/runs/2382324636.

That said, it *is* passing now, which is certainly better :)
