### ISSUE TITLE
Deprecate SourceDirectorySet.getSrcDirTrees()

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#20801]
The implementation says that the feature is broken as it doesn't take filtering into account:

https://github.com/gradle/gradle/blob/bea45ecd2cf08c7ffc0a0bc11bda21ddc03a77e0/subprojects/core/src/main/java/org/gradle/api/internal/file/DefaultSourceDirectorySet.java#L252-L262

---
cc: @gradle/execution

**Comment by jvandort** [comment]
We will not deprecate this method. Instead we documented the existing behavior.
