### ISSUE TITLE
Expose `StartParameter#isConfigurationCacheEnabled()`

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#20815]
### Expected Behavior

It should be possible to check if the configuration cache is enabled. The intention is not for conditional build logic but for information reporting such as custom error reporting or custom build scan tagging.

### Current Behavior

The API is currently available on `StartParameterInternal` and is marked as deprecated (because of Kotlin). At the moment, the _public_ way to check is error-prone (can only check for Gradle/system property of `org.gradle.unsafe.configuration-cache`) and has a gap when it's only enabled via the command-line flag. It also lack symmetry against other similar features like build-cache (`StartParameter#isBuildCacheEnabled()`), parallel execution (`StartParameter#isParallelProjectExecutionEnabled()`), configuration on-demand (`StartParameter#isConfigurationOnDemand()` which lack `Enabled` suffix, meh).

### Context

There are three reasons for such API that I can think of right now:
- Symmetry with other APIs
- Data collection by custom plugins (for example, custom error reporting)
- Custom build scan tagging

**Comment by mlopatkin** [comment]
We already have a request for this in #14375, though this one has a nicer description. I'm closing it as a duplicate, as the older one has upvotes and other duplicates linked.
