### ISSUE TITLE
Buildscript jars are not keeping their original compression

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#20824]
Using the attached [cache-compression.zip](https://github.com/gradle/gradle/files/8715265/cache-compression.zip) project, and running `./gradlew help`, the compression of `myJar.jar` is not maintained. E.g:
```
gavra@gavra-linux-top:~/projects/cache-compression$ zipinfo myJar.jar 
Archive:  myJar.jar
Zip file size: 465 bytes, number of entries: 1
-rw-r--r--  3.0 unx      291 bx stor 22-May-18 10:55 build.gradle
1 file, 291 bytes uncompressed, 291 bytes compressed:  0.0%
gavra@gavra-linux-top:~/projects/cache-compression$ find ~/.gradle/caches/ -name myJar.jar
/usr/local/google/home/gavra/.gradle/caches/jars-9/fd440d87bd09d4901d22d1d60c379d2e/myJar.jar
gavra@gavra-linux-top:~/projects/cache-compression$ zipinfo /usr/local/google/home/gavra/.gradle/caches/jars-9/fd440d87bd09d4901d22d1d60c379d2e/myJar.jar
Archive:  /usr/local/google/home/gavra/.gradle/caches/jars-9/fd440d87bd09d4901d22d1d60c379d2e/myJar.jar
Zip file size: 434 bytes, number of entries: 1
-rw----     2.0 fat      291 bl defN 80-Feb-01 00:00 build.gradle
1 file, 291 bytes uncompressed, 296 bytes compressed:  -1.7%
```

This prevents Gradle plugins from shipping data that can be memory-mapped, to avoid loading it into memory.

**Comment by mlopatkin** [comment]
@gavra0 is it necessary to preserve the alignment of the data as well, like [zipalign](https://developer.android.com/studio/command-line/zipalign) does?

**Comment by gavra0** [comment]
I think alignment should also be kept as-is.

**Comment by mlopatkin** [comment]
> I think alignment should also be kept as-is.

I looked a bit more into it. The alignment is only necessary if you mmap a whole file and expect it regions to be aligned. You don't need the alignment if you just want to mmap a file segment. OTOH, maintaining the alignment is a complex task, even more so if you have to infer the correct alignment from the source without prior knowledge; adding the alignment just-in-case introduces unnecessary overhead. There is also a usual workaround that we suggest to everyone who tries to infer JAR location from the classpath - use a separate configuration and resolve it to get the original JARs.

Given that, I'd rather not to implement the alignment support for now. We also have a plan to change the way the instrumentation works to avoid exposing instrumented jars to the users, so the problem will go away eventually.
