### ISSUE TITLE
Building a target with `--write-verification-metadata` fails with `Multiple entries with same key`

### ISSUE THREAD

**Issue by staktrace** [gradle/gradle#20823]
### Expected Behavior
Build completes successfully as it did with gradle 7.3.2

### Current Behavior
Get the following error:
```
Multiple entries with same key: io.temporal:temporal-sdk:1.12.0-SNAPSHOT=org.gradle.api.internal.artifacts.verification.model.ImmutableComponentVerificationMetadata@77b6ccf5 and io.temporal:temporal-sdk:1.12.0-SNAPSHOT=org.gradle.api.internal.artifacts.verification.model.ImmutableComponentVerificationMetadata@28cd70bd
```

### Context
The steps to reproduce below work (i.e. produce a passing build) when the gradle wrapper is at version 7.3.2. With gradle version 7.4.2 it fails. The reason we are using the `--write-verification-metadata` flag is to provide additional information during CI builds to guard against supply chain attacks. I can provide a little more detail here if needed but we get into what's probably proprietary information very quickly.

### Steps to Reproduce 
1. Clone self-contained reproducer test case at https://github.com/staktrace/20220517-verification-metadata
2. Run `./gradlew shadowJar --write-verification-metadata sha256`

### Your Environment
I can reproduce locally on macOS 12.3.1 but it was also occurring in our CI environment which is running some Linux docker thing. ~~I tried to publish a build scan using my local machine but the server returned a 405 error; build scan server is unavailable.~~ Build scans working now: https://gradle.com/s/npztkmeuvlv4o

**Comment by qyzhao1991** [comment]
Hi, @staktrace,
Is there any update about this issue? I met the same problem with gradle 7.5.

**Comment by staktrace** [comment]
I don't have any updates, no.
