### ISSUE TITLE
Add an option to only generate plaintext and not binary for `--export-keys`

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#20834]
For dependency verification, would like to be only generate `gradle/verification-keyring.keys` and not generate `gradle/verification-keyring.gpg`

related docs: 
https://docs.gradle.org/current/userguide/dependency_verification.html#sec:local-keyring

### Expected Behavior

- `--export-keys text` only generates `gradle/verification-keyring.keys`
- `--export-keys gpg` only generates `gradle/verification-keyring.gpg`
- `--export-keys gpg,text` generates both
- `--export-keys` generates both

### Current Behavior

`--export-keys` always generates both `gradle/verification-keyring.keys` and `gradle/verification-keyring.gpg`

### Context

Our use case is that we want to only use `gradle/verification-keyring.keys` so that we can see changes in the pull request diff. 
We added `gradle/verification-keyring.gpg` to `.gitignore` , but if someone does `--export-keys` on branch A and then changes over to branch B, the `gradle/verification-keyring.gpg` file might cause issues because gradle ignores the `.keys` file if the `.gpg` file is present.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

***

Note that Gradle does not support options that have optional values. However we could implement this by generating both when no configuration exist and have a configuration option in the XML that indicates which format to use for key export.
