### ISSUE TITLE
Incorrect warning in "Working with files" documentation

### ISSUE THREAD

**Issue by joffrey-bion** [gradle/gradle#20857]
As [discussed on the forum](https://discuss.gradle.org/t/confusing-doc-on-working-with-files/42996), there are a couple warnings in the "Working with files" section of the doc, about using `new File()` with relative paths.

In [Single files and directories](https://docs.gradle.org/current/userguide/working_with_files.html?&_ga=2.97871967.112824274.1653426566-1576328757.1650215366#sec:single_file_paths):

> Never use new File(relative path) because this creates a path relative to the current working directory (CWD)

In [File collections](https://docs.gradle.org/current/userguide/working_with_files.html?&_ga=2.97871967.112824274.1653426566-1576328757.1650215366#sec:file_collections):

> Although the files() method accepts File instances, never use new File(relative path) with it because this creates a path relative to the current working directory (CWD)

Given that the code snippets showcasing `file()` and `files()` both include a call to those functions with a `new File(relativePath)` as argument, I believe those warnings should be rephrased to include that it's ok to pass `File` objects with relative paths to those functions, and related functions like `from()`.

**Comment by ljacomet** [comment]
Improvement will be released in Gradle 7.6
