### ISSUE TITLE
Continuous build and Play reload make it difficult to know when a change is incorporated

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#2085]
When running `runPlay` in continuous build, if you reload the application in the middle of a build after making a change, the application will immediately refresh without reloading any changes.  This makes it difficult to know when your changes have taken affect without looking at the console output.

### Expected Behavior

The Play application waits for the in-progress build to complete before reloading or returning to user control.

### Current Behavior

If the application classloader needs to be reloaded, the application is reloaded on refresh.
If the application classloader does not need to be reloaded, the application is not reloaded, even if a build is under way.

**Comment by big-guy** [comment]
partially fixed in #2069 -- this blocks when a change is happening, but there are still scenarios where changes are missed until the next refresh from the application.

**Comment by eriwen** [comment]
@big-guy is the intent that you will work on this for 4.1?

**Comment by bigdaz** [comment]
For review: https://github.com/gradle/gradle/pull/2590

**Comment by bigdaz** [comment]
For review: https://github.com/gradle/gradle/pull/2655

**Comment by bigdaz** [comment]
I have some suggestions for improvements to:
- integration test coverage (to make it more readable)
- DeploymentHandle API

But I think we should close this issue and do that work as part of #2550
