### ISSUE TITLE
Broken application plugin start scripts on Linux when snapshot artifacts are in classpath

### ISSUE THREAD

**Issue by altavir** [gradle/gradle#2089]
`installDist` copies all dependency jars into lib directory and generates start script for Linux and Windows. In case some of jar has ` - SNAPSHOT` prefix, these start scripts work fine on Windows, but do not work on Linux.

### Expected Behavior
It should work on both systems.

### Current Behavior
Works on Windows (both batch file and shell script) but on Linux gives error like 
```
<script name>: 67: <script name>: -: not found
```
Surrounding snapshot class path entries with quotes fixes the problem.

### Steps to Reproduce (for bugs)
Well, just `installDist` with snapshot dependency (I believe that any dependency with whitespaces will do).

### Your Environment
gradle 3.5
Windows 10 / Ubuntu 16.04

**Comment by big-guy** [comment]
could you post an example of the broken script?

**Comment by altavir** [comment]
Something like that:
[msp.zip](https://github.com/gradle/gradle/files/1015877/msp.zip)

Can't test it right now on Linux, but it was not working last time I checked. For now I just removed SNAPSHOT qualifiers and it works.

**Comment by altavir** [comment]
Still is broken on `4.5`. If jar artifacts names contain white-spaces, start scripts do not work on Ubuntu. It starts working after double-quoting those jar paths.

**Comment by marcphilipp** [comment]
Did you quote them in the script manually?

**Comment by altavir** [comment]
Yes, after installation is done. I am working mostly on windows, so I usually do not see this problem (It works fine on windows). But on Ubuntu it just does not work without quoting.

**Comment by marcphilipp** [comment]
Adding quotes around the `CLASSPATH="..."` declaration should probably be sufficient.

@altavir Would you be interested in providing a fix?

**Comment by altavir** [comment]
Thanks for suggestion. It definitely looks easier, than searching for all corrupted entries.

Sadly, I currently do not have time even for small fix.
