### ISSUE TITLE
Gradle buildSrc model broken when using specific --includeBuild

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#20898]
During the IDEA sync, TAPI client fails to query models of `buildSrc` of nested builds.

### Expected Behavior
project opens successfully.

### Current Behavior
Exception "No model of type 'TurnOffDefaultTasks' is available"

### Context
https://youtrack.jetbrains.com/issue/IDEA-276738
This happens during the second TAPI call, that tries to obtain data from `buildSrc` project.
Since Gradle version 6.7 included composite builds should be available to the `buildSrc`. To achieve this IDEA adds `--include-build` during TAPI call.
Since Gradle 7.2 this trick does not work for `buildSrc` subprojects of included builds. IDEA's import action fails to obtain custom models for `buildSrc` causing exceptions like "No model of type 'TurnOffDefaultTasks' is available"

give composite build
`C -> B -> A -> buildSrc`

when doing a TAPI call to `buildSrc` with `--include-build B` TAPI action ends up in an environment with _two_ instances of `buildSrc` gradle projects, of which one has no model builders attached.

### Steps to Reproduce 
Try opening https://github.com/TheMrMilchmann/MCVE/tree/IDEA-276738 in IDEA 2022.1

**Comment by donat** [comment]
I was able to reproduce the problem. The import works with Gradle 7.1.1 and breaks with 7.2.

**Comment by donat** [comment]
I've done a bit of investigation on the topic. Passing init scripts to `buildSrc` would be a solution. There's a [pending PR](https://github.com/gradle/gradle/pull/19487) implementing that, but it cannot be merged before Gradle 8.0 as it introduces a breaking change.

A real alternative is to extend to Tooling API to replace using an init script for injecting custom Tooling API model builds. We'll discuss if and when can we implement this feature.

**Comment by nskvortsov** [comment]
Is there any workaround I could implement on IDEA side? E.g., do not pass included builds that reside outside the project cotaining `buildSrc`? Will it be against the https://docs.gradle.org/6.7/release-notes.html#build-src ?

**Comment by donat** [comment]
I did some investigation, and unfortunately, I don't find any solution that would make your current setup work (i.e. specifying `buildSrc` as project root and using `--include-build` statements to add the main build).

I'm still trying to figure out what would be the best approach. My understanding is that the `buildSrc` _builds_ are independent of the main build. In other words, `buildSrc` build configuration cannot be changed from the root/subprojects. This means that an independent TAPI call can query its configuration.

With that in mind, you could write a Tooling API client that
- traverses the build tree via `BuildController`
- Queries the custom models from the root projects
- Returns the `buildSrc` locations via `BuildController.getEditableBuilds()`

Then in a second pass, you could query the custom model on the `buildSrc` builds without the `--include-build` statements. Does this make sense?

**Comment by nskvortsov** [comment]
@donat thank you for the investigation. So far, IDEA can not perform second pass without `--include-build`: Plugins implementation and dependencies substitutions will not work. These cases were metioned in this https://github.com/gradle/gradle/issues/2531#issuecomment-691638531 and this https://github.com/gradle/gradle/issues/2531#issuecomment-703314288, reported to JetBrains as [IDEA-250774](https://youtrack.jetbrains.com/issue/IDEA-250774) and [IDEA-252140](https://youtrack.jetbrains.com/issue/IDEA-252140) respectively.
Here is our "helper" to handle these: https://github.com/JetBrains/intellij-community/blob/27b4397f9e92cd0c5e2210c5b44c2398851d807c/plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/GradleBuildSrcProjectsResolver.java#L190

**Comment by donat** [comment]
Ah, I missed plugin substitution. You are right.

**Comment by nskvortsov** [comment]
Is there a switch to disable  https://github.com/gradle/gradle/issues/14563 ?

**Comment by donat** [comment]
Unfortunately, there's no way to disable it. 
We are looking into multiple approaches to solve this issue.

**Comment by nskvortsov** [comment]
IDEA 2022.2 will be release with a workaround. Evaluation of a BuildSrc project will not include any composite parts that transitively include the parent of the buildSrc.

**Comment by donat** [comment]
I've verified that the latest version of IntelliJ IDEA can successfully import projects with the reported structure.

Also, Gradle 8 has a new behavior. Plugins applied via inits script are also applied on `buildSrc`. With that, tooling providers can inject custom model builders and request the models for all builds in the build tree including `buildSrc`. /cc @nskvortsov

**Comment by donat** [comment]
@nskvortsov I think there's no need for a workaround for Gradle 8.0+ builds and IntelliJ can get all Tooling models in a single request.

**Comment by donat** [comment]
Got it. Thanks for the feedback, @nskvortsov!
