### ISSUE TITLE
Gradle Tooling API 7.5-rc-1 not compatible with Java 17

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#20915]
Regular Gradle (not the tooling API) 7.5-rc-1 works perfectly for me with Java 17. However, the tooling API throws the following: 

```
No matching variant of matt.KJ:kbuild:1654196619201 was found. The consumer was configured to find a runtime of a library compatible with Java 16, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.5-rc-1' but:
GRADLE ERR:          - Variant 'apiElements' capability matt.KJ:kbuild:1654196619201 declares a library, packaged as a jar, and its dependencies declared externally:
GRADLE ERR:              - Incompatible because this component declares an API of a component compatible with Java 17 and the consumer needed a runtime of a component compatible with Java 16
```

`matt.KJ:kbuild` is a local gradle plugin developed in java 17. I might be able to build it in 16 so it might not be a huge issue. But I wanted to check here if my assumption is correct that this is my only option for now, and also to check if there are plans to update the tooling api to java 17?

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.
