### ISSUE TITLE
AAPT: error: failed to deserialize resource table: configuration has invalid locale 'be-' after updating AGP

### ISSUE THREAD

**Issue by madhurgupta10** [gradle/gradle#20939]
### Expected Behavior

Should be able to build project without any errors.

### Current Behavior

Unable to build project with the following error.

```
AAPT: error: failed to deserialize resource table: configuration has invalid locale 'be-'.
```

### Context

Project repository - https://github.com/commons-app/apps-android-commons

### Steps to Reproduce 

Before (worked fine)
```
classpath 'com.android.tools.build:gradle:4.0.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.10"
```

Now (error)
```
classpath 'com.android.tools.build:gradle:7.2.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
```

### Your Environment

Build: AI-212.5712.43.2112.8609683, 202205181650,

AI-212.5712.43.2112.8609683, JRE 11.0.12+7-b1504.28-7817840x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 6720.0x3780.0

AS: Chipmunk | 2021.2.1 Patch 1; Kotlin plugin: 212-1.6.10-release-923-AS5457.46; Android Gradle Plugin: 7.2.1; Gradle: 7.3.3; Gradle JDK: version 11.0.12;

**Comment by h0tk3y** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
