### ISSUE TITLE
Docker image 7.4.2-jdk17 is broken on 4.15 kernel

### ISSUE THREAD

**Issue by up-to-you** [gradle/gradle#20960]
java --version results in:
`Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 8k, detached.`

Found similar fresh issue https://github.com/flyway/flyway/issues/3457
Someone argue that problem is not reproducible with `alpine` version.

Most probably due to new 17.0.3 `temurin` jdk build.

### Expected Behavior
Gradle images use more robust JDK distributions

### Current Behavior
`Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 8k, detached.`

### Steps to Reproduce 
Kernel 4.15.
Dockerfile:
```
FROM gradle:7.4.2-jdk17

RUN ulimit -s
RUN /opt/java/openjdk/bin/java --version
```

### Your Environment
Linux kernel 4.15

**Comment by up-to-you** [comment]
worth point to gradle' forum thread with no feedback: 
https://discuss.gradle.org/t/bitbucket-pipelines-oom-with-gradle-7-4-works-with-gradle-7-2/43032/1

**Comment by h0tk3y** [comment]
@up-to-you 
This Docker image is not maintained by the Gradle team. Could you please report this issue to the [Github repository](https://github.com/keeganwitt/docker-gradle/issues) of the Docker image?
