### ISSUE TITLE
Turn off "what went wrong" message

### ISSUE THREAD

**Issue by blazmrak** [gradle/gradle#20964]
I would like to be able to turn off failure "help" that gets displayed when build fails. It is repetitive and gives no value when developing.

### Expected Behavior
```
BUILD FAILED in 2s
```

### Current Behavior
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: <file>

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

### Context
This would be really useful when developing locally when running `gradle -t test`, because this way there would be no need to scroll up/make console full screen to see what the failure was.

**Comment by vlsi** [comment]
Sometimes "what went wrong" is useful, however I fully agree "Execution failed for task ':test'" adds absolutely no value.
It would be much better if Gradle printed the test failure summary or something like that. Running with stacktrace or info or debug rarely helps to diagnose test failures.

**Comment by big-guy** [comment]
@gradle/bt-core-runtime-maintainers @gradle/bt-ide-experience I'm not sure who should own this, but it's not the JVM team for now.

**Comment by reinsch82** [comment]
@blazmrak The noise has been reduced a bit with newer versions.
Would you be able to check with a newer version, whether this already helps your case enough?

A current example of a failing test looks like this:

```
65 tests completed, 1 failed
Cleaning up daemons...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wrapper:forkingIntegTest'.
> There were failing tests. See the report at: file:///Users/reinholddegenfellner/IdeaProjects/gradle-feature/platforms/core-runtime/wrapper/build/reports/tests/forkingIntegTest/index.html

BUILD FAILED in 2m 39s
```
