### ISSUE TITLE
Artifact transforms execute before all dependencies are ready

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#20975]
This issue documents/tracks the root cause of #20778 

When a software component exists in the dependency graph of an artifact transform as *both* a project dependency and an external dependency, optimizations to the execution graph will "erase" the external dependency and include only the project dependency. This optimization exposed a regression in the above issue.

One proposed fix is to spike new logic to “discover” these conflicting node dependencies at execution time prior to running the transform, so that it does not run until all of its upstream dependencies are built. We have a few situations where it would be useful to be able to “explode” a node into several other nodes (for example, a “configure this project” node might be able to split into “compile plugins block”, “resolve classpath”, “compile script body”, “run script body” nodes, each with their own dependencies. Or a “resolve this dependency graph” might split into nodes to resolve the metadata for each dependency). We started down this path in 7.5, with splitting task nodes into a “resolve mutations” node and a “run actions” node, so we could take another step by using this to split a transform node when we discover the conflicts.

More internal details are available in a private slack thread [here](https://gradle.slack.com/archives/CH43P3A10/p1652713167611929)

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/21292

**Comment by bamboo** [comment]
Closing as completed for 7.6 RC1.

@adammurdoch, I don't recall why the issue was reopened but if there's additional work related to this issue, would you mind opening a new ticket?
