### ISSUE TITLE
Task definition fails for subprojects when using rule-based model configuration

### ISSUE THREAD

**Issue by bkeyser** [gradle/gradle#2098]
When using rule-based model configuration where the model is defined for a projects subprojects, the variables of a model are not recognized.

### Expected Behavior
A model value should be recognized by a task defined for subprojects.

### Current Behavior
An error is returned concerning an invalid variable name

### Context
Tasks may not be defined for subprojects using the mechanism defined in [Rule based model configuration](https://docs.gradle.org/current/userguide/software_model.html#dsl-rule-input-dependencies)

### Steps to Reproduce (for bugs)
The model definition for the project is

```groovy
subprojects {
    apply plugin: 'some.plugin'

    model {
        packaging {
            repository {
                id = 'repository-id'
                url = 'repository-url'
            }

            artifact {
                version = 'LATEST'
            }
        }
        
        tasks {
            simple(Task) {
                def pkg = $.packaging

                doLast {
                    println "$pkg.repository.url"
                }
            }
        }
    }
}
```

The model definition for a subproject is

```groovy
model {
    packaging {
        artifact {
            groupId = 'org....'
            artifactId = 'someartifact'
        }
    }
}
```

When performing any gradle command

```bash
$ ./gradlew model
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test NO-SOURCE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bkeyser/projects/pkg-dgcs/build.gradle' line: 30

* What went wrong:
Could not compile build file '/Users/bkeyser/projects/pkg-dgcs/build.gradle'.
> startup failed:
  build file '/Users/bkeyser/projects/pkg-dgcs/build.gradle': 29: Invalid variable name. Must include a letter but only found: $
  . At [29:27]  @ line 29, column 27.
                     def pkg = $.packaging
                               ^
  
  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.268 secs
```

### Your Environment
 * Build scan URL: https://gradle.com/s/coq4kf7tgx7t6

**Comment by bkeyser** [comment]
If the task is removed from the project and added to the subproject the build succeeds

```groovy
model {
    packaging {
        artifact {
            groupId = 'org...'
            artifactId = 'someartifact'
        }
    }

    tasks {
        simple(Task) {
            def pkg = $.packaging

            doLast {
                println "$pkg.repository.url"
            }
        }
    }
}
```

**Comment by bkeyser** [comment]
This issue is also present when using extensions.  Following the example above and adjusting the _simple_ task  for syntax, the project and subproject will compile, but does not complete as expected.  For the case mentioned above and the following project build specification

```groovy
subprojects {
    packaging {
        artifact {
            version 'LATEST'
        }
    }
}

task simple {
    println "${project.extensions.packaging.artifact.groupId}"
}
```

the output does not find the variable as signified by the output of **null**

```bash
$ ./gradlew simple
...
null
```

If the task references the variables (in this case the OtherTask simply prints information) with a project build specification of

```groovy
subprojects {
    packaging {
        artifact {
            version 'LATEST'
        }
    }

    task other(type: OtherTask) {
        groupId = project.extensions.packaging.artifact.groupId
        artifactId = project.extensions.packaging.artifact.artifactId
        version = project.extensions.packaging.artifact.version
    }
}
```

and a subproject definition of

```groovy
packaging {
    artifact {
        groupId 'org....'
        artifactId 'artifact'
    }
}
```

The variables defined in the subproject are not found as shown in the following output

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':subproject:other'.
> No value has been specified for property 'groupId'.
> No value has been specified for property 'artifactId'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.769 secs
```

In both cases, if the task is included directly in the subproject then it completes successfully

**Comment by lacasseio** [comment]
Thanks for the information on this @bkeyser. This is a known limitation of the Groovy Rule base engine. To support `$` as a way to access model element, Gradle has a special handler when compiling the script file to replace with the right code. Unfortunately, the handler doesn't support nesting the code inside `subproject` and the like. To support nesting inside other code blocks, it is suggested to use [`RuleSource` plugin as explained here](https://github.com/gradle/gradle/issues/1002#issuecomment-303697096). I hope this helps you.

**Comment by bkeyser** [comment]
Thanks for the explanation @lacasseio!  I apologize for not finding the issue you referenced in my search and the duplicate explanation.  What would you think about updating the User Guide to include a note to help explain this limitation to other users?
