### ISSUE TITLE
Files added directly as dependencies are not added to distribution zip correctly.

### ISSUE THREAD

**Issue by zapper59** [gradle/gradle#2099]
I created a simple project to show this error:
https://github.com/zapper59/GradleTest

The GradleTest folder is what is produced after the command:
`gradle clean build || unzip build/distributions/GradleTest.zip -d .`

### Expected Behavior
I would expect either for the libs-1 folder to be added directly to the libs folder in the distribution zip and CLASSPATH to point to %APP_HOME%\lib\libs-1, or for the contents of libs-1 to be added and the CLASSPATH variable to point to %APP_HOME%\lib.

### Current Behavior
The CLASSPATH variable of GradleTest.bat points to %APP_HOME%\lib\lib-1 but instead the contents of lib-1 were added to the the libs folder.

### Context
I was trying to add binaries and configuration files to the distribution, without having them end up inside of a jar file (thus why I can't just put them in src/main/resources).  Having the classpath variable corrupted as it is makes it difficult to write clean code to track down where these files are from inside of an application.  It seems that either of the expected behaviors I listed would be appropriate solutions.

### Steps to Reproduce (for bugs)
Download the repo listed at the top and do:
`gradle clean build || unzip build/distributions/GradleTest.zip -d .`

### Your Environment
Tested in Cygwin and Ubuntu using gradle 3.5.

**Comment by big-guy** [comment]
Thanks @zapper59.  The `runtime` configuration is really intended to be used for runtime jar dependencies.

You can customize the contents of the distribution:
https://docs.gradle.org/current/userguide/distribution_plugin.html#sec:distribution_contents

Although, I think the easier thing to do in your case would be to put `libs-1` into `src/main/dist`.  By default, that's included in the distribution as-is.

**Comment by oehme** [comment]
The line `files("libs1")` doesn't really work. That's telling Gradle to put the directory "libs1" on the classpath, which Java doesn't support. What you probably wanted was `fileTree("libs1")`, which gives you all the jars *inside* libs1.

The incorrect part is that Gradle added the libs directly under the distribution `libs` directory. Instead the whole dir should have been added. But still Java wouldn't have accepted that I think.
