### ISSUE TITLE
IncludeBuild Incremental not working 

### ISSUE THREAD

**Issue by VickyBox** [gradle/gradle#20997]
I'm an android developer using kotlin. My projects are using IncludeBuild. when A Project depend on B Project. and B Project depend on C Project. following these steps:
1. I compiled three projects.
2. then I add one line code in C project,  after compiled，I find B project is compiled all code. Incremental not working. 

kotlin：1.5.21
gradle version: 6.7.1
gradle.properties:
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx5120M

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

***

Given the Gradle and Kotlin versions, which are somewhat old, that might be the cause. And if this is purely about Android written in Kotlin, this place is the wrong one. You will have to open an issue against the Android or Kotlin Gradle plugin projects.
