### ISSUE TITLE
Misdetected cycle issue after upgrading to 7.5-rc-2

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#21000]
After upgrading the [junit5 build](https://github.com/junit-team/junit5/) to 7.5-rc-2 (I also tried 7.5-20220610230151+0000) and running `./gradlew build`, I'm getting the [following failure](https://ge.junit.org/s/kvdaeazhemeym/failure#1):

> Misdetected cycle between :junit-jupiter-params:jar and :junit-jupiter-params:jar. Help us by reporting this to https://github.com/gradle/gradle/issues/2293

### Expected Behavior
`./gradlew build` continues to work when upgrading from 7.4.2 to 7.5-rc-2

### Current Behavior
Above error.

### Steps to Reproduce
1. Clone [junit5](https://github.com/junit-team/junit5/)
2. Run `./gradlew wrapper --gradle-version=7.5-rc-2` twice
3. Run `./gradlew build`

### Your Environment

Build scan URL: https://ge.junit.org/s/kvdaeazhemeym/failure#1

**Comment by marcphilipp** [comment]
@bamboo At a glance this looks related to the issue you fixed recently.

**Comment by bamboo** [comment]
Thanks, @marcphilipp, I'll take a look.

**Comment by mlopatkin** [comment]
I identified the range in which the regression was introduced. The first commit bd4e7a02d8e65e910c49069367d20e549894c83e breaks the reproducer, but not in the reported way; it deadlocks instead. The following commit ceef737add6b6a84019f69b478fb2f8342f30d35 makes the reproducer to fail with the aforementioned problem.

**Comment by marcphilipp** [comment]
I'm afraid this has regressed in 7.5-rc-4

**Comment by adammurdoch** [comment]
Fixed (again) via https://github.com/gradle/gradle/pull/21212

**Comment by marcphilipp** [comment]
Comfirmed to be fixed in 7.5-20220711060358+0000: https://ge.junit.org/s/w5pd52pq57ixg
