### ISSUE TITLE
maven-publish randomly publishes empty pom

### ISSUE THREAD

**Issue by knyttl** [gradle/gradle#21038]
I created a demo project here: https://gitlab.com/knyttl/kotlin-1.6.20-publishing-demo/-/tree/main

When you run 

```
gradle clean build publish --info --warning-mode all; cat m2/demo/demo/ci/demo-ci.pom
```

It will randomly generate two different kind of poms:

1. correct one: https://gist.github.com/knyttl/abba960ae07afe1c361c4959e5d3cb25
2. empty one: https://gist.github.com/knyttl/d9574b6589828d5b5aec10a347a8ea59

On my local computer I can have it consistently as follows:
- kotlin version 1.6.10 -> correct behaviour
- kotlin version 1.7.0 -> empty pom

However, on some other testing environment, I could get random results independently on kotlin version.

### Expected Behavior

The resulting pom should always be the same.

### Current Behavior

The resulting pom differs randomly.

### Context

This completely brakes our builds. Either there is some race condition or I am missing some setting.

The strange is that the empty `pom.xml` contains `<packaging>pom</packaging>` whereas the correct one does not have it.

This is probably something to do with the fact that there are two published artifacts.

### Steps to Reproduce 

See above.

### Your Environment
```
gradle 7.4.2
different environments
```

**Comment by knyttl** [comment]
I believe this is the same issue like here: https://stackoverflow.com/questions/48999867/gradle-publish-jars-with-different-classifiers-dependency-missing

**Comment by knyttl** [comment]
I believe this is a bug, not a question as the publishing is not deterministic.

**Comment by donat** [comment]
https://gitlab.com/knyttl/kotlin-1.6.20-publishing-demo/-/blob/main/build.gradle.kts#L49

should be something like

    (project.name + "-" + testArtifact.name).toLowerCase().replace(":", "-")

**Comment by knyttl** [comment]
> (project.name + "-" + testArtifact.name).toLowerCase().replace(":", "-")

that does not make any difference as the result is `demo-demo`

**Comment by knyttl** [comment]
The problem then is that the artifact becomes inaccessible with

```
implementation(project(":demo", "testJar"))
```
