### ISSUE TITLE
Buildship - cannot resize "Gradle Tasks" treeview

### ISSUE THREAD

**Issue by mimmoz81** [gradle/gradle#2103]
When using Buildship, if you have a large task name, in Gradle Tasks treeview the name itself is truncated (and the same applies to the description). See screen below:

![immagine](https://cloud.githubusercontent.com/assets/14213760/26298464/b1fcd20c-3ed7-11e7-9e3b-cd48d7f70f67.png)

It would be better to have some splitpane-like control between the name and the description, to be able to resize the view accordingly to user need.

### Expected Behavior
A control like a splitpane should be placed between task name and description, to be able to resize the view and see the full name.

### Current Behavior
Cannot resize the view

### Your Environment
Gradle 3.4.1
Buildship 2.0.2
Eclipse 4.6.3

**Comment by bmuschko** [comment]
Would you mind raising an issue with the [Buildship project](https://github.com/eclipse/buildship)? You question is much better suited to be handled over there. Thanks!

**Comment by mimmoz81** [comment]
ops.. sorry my mistake..
here it is.. https://github.com/eclipse/buildship/issues/475

**Comment by bmuschko** [comment]
Great, thank you so much!
