### ISSUE TITLE
Do not fix JVM target to 8 when compiling build.gradle.kts files

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#21041]
### Expected Behavior
Compilation of `build.gradle.kts` files should allow configuration of the JVM target.

### Current Behavior
Gradle currently seems to fix the JVM target to 8 when compiling Kotlin build files ([here](https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt#L344)).

### Context
This is troublesome if using utilities targeting JVM 11 in build files. In particular, inline functions (like reified functions) can't be used, since the Kotlin compiler refuses to inline JVM11 functions in a JVM8 target.

**Comment by eskatos** [comment]
This sets the JVM target for script compilation
https://github.com/gradle/gradle/blob/0d3a6e10e0edef9a7005c014f91d405eedee9726/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt#L344

This sets the JVM for IDE support and is a static declaration
https://github.com/gradle/gradle/blob/0d3a6e10e0edef9a7005c014f91d405eedee9726/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/KotlinBuildScript.kt#L46

The current plan is to raise this to the minimally supported JVM version to run Gradle when this minimum changes. That can only happen in a major version.

Making the JVM target for script compilation configurable would be technically feasible. But there's currently no mechanism to reflect that in the IDE. This would create an undesirable and confusing mismatch.

If the IDE uses the JVM version used to run Gradle in the context of scripts by default, then removing the constraint on the IDE side and using the current JVM on the script compilation side could be an option.

I'll experiment with this idea and discuss with JetBrains folks.

**Comment by cesar1000** [comment]
Thanks for looking into this!

As for the IDE configuration, is that only used with `build.gradle.kts` files, or is it only used in Kotlin script binary plugins? Would that cause a problem if setting the JVM target with {{kotlinDslPluginOptions}}?

**Comment by eskatos** [comment]
This issue is about the build scripts (init/settings/project) but not about the "precompiled script plugins" aka. `.gradle.kts` files present in source sets of project applying the `kotlin-dsl` plugin.

Precompiled script plugins don't specify the jvm target for the IDE. They compile to `kotlinDslPluginOptions.jvmTarget` already.

**Comment by cesar1000** [comment]
Cool, thanks for confirming!

**Comment by big-guy** [comment]
@eskatos is there anything we need to do for this in 8.0?

**Comment by eskatos** [comment]
@big-guy, took me a little while to get to it, here's the PR
* https://github.com/gradle/gradle/pull/22967
