### ISSUE TITLE
specifiy replacement for jcenter() convenience function

### ISSUE THREAD

**Issue by matkoniecz** [gradle/gradle#21043]
### Expected Behavior
https://docs.gradle.org/7.3.3/userguide/upgrading_version_6.html#jcenter_deprecation mentions how convenience function can be replaced by something not emitting warning (I still need to get library hosted on jcenter)

### Current Behavior
https://docs.gradle.org/7.3.3/userguide/upgrading_version_6.html#jcenter_deprecation just mentions removal, no info how to continue using jcenter without getting deprecation warning

### Context
yes, I am aware that new uploads to jcenter are possible - but for now jcenter will be kep in read only state, sufficient in this case

and library was abandoned already so jcenter situation is not making it worse (`org.sufficientlysecure:html-textview:3.9` in StreetComplete if anyone is curious)

**Comment by matkoniecz** [comment]
To clarify: I expect that many (hundreds? thousands?) will get deprecation message with link there and will need to keep `jcenter` reference, just without that convenience function as dependency is no longer being updated and is on `jcenter`

I found for example https://stackoverflow.com/a/68244110/4130619 - and I have no idea is gradlePluginPortal actually mirroring jcenter or not? Someone else claims that mavenCentral is drop in replacement...

I can either ignore deprecation message (and have even more pointless text in my gradle task output) or spend few hours on researching this. And then next developer will need to do the same.

Maybe it would be better to either undeprecate it or provide clear migration path in docs?

**Comment by matkoniecz** [comment]
And there is

> We recommend that you consider [using](https://docs.gradle.org/7.3.3/userguide/declaring_repositories.html#declaring-repositories) mavenCentral(), google() or a private maven repository instead.

but has either commited to mirroring jcenter? Yes, I can simply try testing - but is there a risk of getting not mirrored code but one with malicious extra additions? Are they mirroring code or is there risk of a supply chain attack?

**Comment by donat** [comment]
The `repositories { jcenter() }` snippet does not do anything special, it is only a shorthand for a repository declaration and it is equivalent to writing:
```
maven {
   url = uri("https://jcenter.bintray.com/")
}
```

So you are correct here:
> I found also somewhere else that
> 
>     maven {
>        url = uri("https://jcenter.bintray.com/")
>         content {
>             includeGroup("org.sufficientlysecure")
>         }
>     }
> 
> is a proper replacement for
> 
>     jcenter {
>         content {
>             includeGroup("org.sufficientlysecure")
>         }
>     }

Regarding 
> I found for example [stackoverflow.com/a/68244110/4130619](https://stackoverflow.com/a/68244110/4130619) - and I have no idea is gradlePluginPortal actually mirroring jcenter or not? Someone else claims that mavenCentral is drop in replacement...

Please don't do that. The fact that `gradlePluginPortal` uses jcenter artifacts is an implementation detail and is subject to change in the future.
