### ISSUE TITLE
build.gradle.kts   Exclude files

### ISSUE THREAD

**Issue by HuangJAndroid** [gradle/gradle#21046]
### Expected Behavior
Exclude these files when generating apk

### Current Behavior
of no avail

### Context

```
kotlin {
    sourceSets{
        named("main"){
            resources.exclude("src/main/debug/", "src/main/java/com/test/app/debug/")
        }
    }
}
```

or

```
sourceSets.named("main"){
        resources.filter.exclude("src/main/debug/", "src/main/java/com/test/app/debug/")
 }
```

**Comment by donat** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

**Comment by HuangJAndroid** [comment]
> Thank you for your interest in Gradle!
> 
> Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.
> 
> If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.
> 
> If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

All of them have been tried，But  there are still those files in apk

**Comment by aspic-fish** [comment]
could you try this?
```
packagingOptions {
        resources.excludes.add("src/main/debug/")
        resources.excludes.add("src/main/java/com/test/app/debug/")
}
```

**Comment by jbartok** [comment]
What you are filtering are just the resources, not the sources. To filter the sources you need to figure out which language your sources are in and then reference that. So `java.exclude` or `kotlin.exclude`. For more question try the Android community. The setup there might be different.
