### ISSUE TITLE
Corrupt serialized resolution result when using composing builds with platform bom and exclude spec

### ISSUE THREAD

**Issue by KaiyuanZhao** [gradle/gradle#21057]
### Expected Behavior

Resolve dependencies successfully.

### Current Behavior

Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module

### Context

Failed in **Gradle6.9.2/7.2/7.3+/7.4+/7.5-rc**
Succeeded in Gradle6.7.1/6.9.1/7.0/7.1

We have some repositories using `platform` to sync our app's dependencies. When we includeBuild these repositories in our app with some certain exclude spec, it always says `Corrupt serialized resolution result`.

**This is caused by pr https://github.com/gradle/gradle/pull/18131 with issue https://github.com/gradle/gradle/issues/17964**

I cloned Gradle7.4.2 source code and did some debugging. I found out something wrong in `org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.NodeState`. 

In `cacheFilteredDependencyStates`, `dependencyState = maybeSubstitute(dependencyState, resolveState.getDependencySubstitutionApplicator()); (line 512)` is always creating **a new `DependencyState` instance** by `return dependencyState.withTarget(details.getTarget(), details.getRuleDescriptors()); (line 634)` when we using `includeBuild`. And then `boolean sameDependencies = dependencies(newResolutionFilter).equals(oldStates); (line 355)` in `excludesSameDependenciesAsPreviousTraversal(ExcludeSpec newResolutionFilter)` is always false.

After I tried to add a cache for `dependencyState.withTarget`, problem solved. This problem has been bothering us for several months. I hope you could find a suitable way to solve it. @ljacomet 

Releated to https://github.com/gradle/gradle/issues/19656

### Steps to Reproduce 

[resolution.zip](https://github.com/gradle/gradle/files/8949350/resolution.zip)

- unzip `resolution.zip`
- cd to `resolution` dir
- failed when `./gradlew :include:hammering:dependencies --configuration releaseRuntimeClasspath -S -PEXCLUDE`
- succeeded when `./gradlew :include:hammering:dependencies --configuration releaseRuntimeClasspath -S`
- In order not to expose some information, I used a random dictionary to obfuscate our dependency names.

### Your Environment

Windows/Linux/Mac
Java 11

**Comment by KaiyuanZhao** [comment]
https://github.com/gradle/gradle/issues/23680 solved this issue for me.
when will it be backported to 7.*? https://github.com/gradle/gradle/issues/23681

**Comment by ljacomet** [comment]
@KaiyuanZhao Gradle 7.6.2 will have the fix backported.

Can you confirm that `7.6.2-20230624061709+0000` fixes the issue?

**Comment by ov7a** [comment]
@KaiyuanZhao Given the absence of a reply, I assume that issue was fixed. Feel free to ping us if you have any additional details.
