### ISSUE TITLE
Cannot access project from included build as dependency using composite build

### ISSUE THREAD

**Issue by kubabar1** [gradle/gradle#21075]
### Expected Behavior
It should be possible to access project dependency from included build in composite build.

### Current Behavior
Accessing project from included build as dependency is impossible without workaround described in section **Context**.

### Context
I’m struggling with a problem with Gradle composite build. I have 2 separate gradle builds - **project1** and **project2**. In **project2** all dependencies are defined in a separate file **module-specific-dependencies.gradle**, which is applied inside project2/build.gradle, e.g.:

**module-specific-dependencies.gradle**
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation project(':module1')
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

**project2/build.gradle**
```
apply from: 'module-specific-dependencies.gradle'
```

Now **project2** is included into **project1** and I want to use **module-specific-dependencies.gradle** file inside that project - I tried to do that using `gradle.includedBuild`:

```
apply from: file("${gradle.includedBuild('project2').projectDir}/module-specific-dependencies.gradle")
```

now, if I’m trying to run project2 it works fine, but for project1 I receive below error:

```
Project with path ':module1' could not be found in root project 'project1'.
```

Problem is caused by below project dependency from **module-specific-dependencies.gradle:**
```
implementation project(':module1')
```

I tried to change that dependency to:
```
implementation 'com.examplemod2:module1:0.0.1-SNAPSHOT'
```

after that problem was fixed for **project1**, but below problem occurred during launching **project2**:

```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.examplemod2:module1:0.0.1-SNAPSHOT.
     Required by:
         project :
```

only below solution worked for me:

```
implementation project.findProject(':module1') != null ? project.findProject(':module1') : 'com.examplemod2:module1:0.0.1-SNAPSHOT'
```

but it seems to be too big workaround - how in this case I can use project dependency, assuming that project structure cannot be changed (dependencies have to be defined inside separate file)?

### Steps to Reproduce 
I created example project with this problem: https://github.com/kubabar1/GradleCompositeBuildTrial
Currently I used described above workaround. To recreate problem You need to open file **project2/module-specific-dependencies.gradle** and replace:

```
implementation CompositeBuildUtils.resolveProjectDependency(project, ':module1', 'com.examplemod2', 'module1', '0.0.1-SNAPSHOT')
```

by:

```
implementation project(':module1')
```

(now after run `./gradlew build` from **project1** error described in section **Context** should occur)

or:

```
implementation 'com.examplemod2:module1:0.0.1-SNAPSHOT'
```

(now after run `./gradlew build` from **project2** error described in section **Context** should occur)

### Your Environment
Gradle 7.4.1

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

---

Applying a script file across included build project boundaries. This is not the right way to approach the problem. We have other ways of centralizing dependencies and versions. Pls. explore version catalogs or platforms.
