### ISSUE TITLE
Gradle tools - forTasks()

### ISSUE THREAD

**Issue by jzeferino** [gradle/gradle#2107]
I'm using gradle tools to run a `task` in multiple modules. 

### Expected Behavior
So, I have 7 modules. In each module I have a gradle task called `upload`.
I've created an array of task with the module name like `{module1:upload,module2:upload,module3:upload,module4:upload,module5:upload,module6:upload,module7:upload}`.

Then I call:

```
gradleConnection.newBuild()
                .forTasks(tasks)
                .run();
```

I was expecting that all tasks execute.

### Current Behavior
Only the last task executes.

### Steps to Reproduce (for bugs)
Create a list of tasks and call `.forTasks` and then `.run()`.

### Your Environment
IntelliJ IDEA 2017.1.3
Build #IC-171.4424.56, built on May 12, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Comment by big-guy** [comment]
I don't see this behavior.  Are you sure you're passing the list you expect to `forTasks()`?

You should be able to also just use `upload`, which will match any tasks called `upload` in any subprojects.

**Comment by jzeferino** [comment]
@big-guy I'm sure I'm passing the list of tasks.
I could try that second approach.
ATM I'm iterating through the list of tasks and calling the `forTasks` for each of one.

**Comment by big-guy** [comment]
Sorry for the late reply. Are you doing this now?
```
buildLauncher = gradleConnection.newBuild();
for (String task : tasks) {
   buildLauncher.forTasks(task);
}
buildLauncher.run();
```

That's different from your example above and would make sense that you're only seeing the last task executed.  `forTasks` sets the list, it doesn't append to it.

**Comment by jzeferino** [comment]
@big-guy I ended up calling the task name and it runs all the modules that have that task.

**Comment by bmuschko** [comment]
Sounds like the issue has been solved. I am going to close it. Feel free to reopen if you have further questions.
