### ISSUE TITLE
Do not track implementation of nested input

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#21085]
We are currently adding the implementation of a nested input as an input to the task: https://github.com/gradle/gradle/blob/06a728bc89c235edc621d02f0656b4ae244c3dd9/subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/NestedRuntimeBeanNode.java#L39-L42

We don't remember why we added this tracking exactly. The only use-case we could think of is if you add some object with a behavior without any properties as an input, and then you want to track changes to that object. For example when you have a strategy as an input. Though that seems to work against the meaning of `@Nested`, which is that the nested bean should declare its inputs.

This would solve some problems, like for example `CommandLineArgumentProvider`s added in build scripts would not be affected by build script changes, only when the embedded properties change.

Removing the implementation of the nested input is a breaking change, since some tasks may now be up-to-date or from the cache when the implementation of the nested input changed. So it could also be seen as a bug that changes to the implementation of the nested input causes the task to be out of date.

---
cc: @gradle/bt-execution

**Comment by wolfs** [comment]
We discussed this, and it is still important to track the implementation of the nested element for certain use-cases. I think especially when some methods on the types are not `getters` or when some `getters` are annotated with `@Internal` then the implementation can matter, since there is more an input than just the raw data.

**Comment by lptr** [comment]
FTR, one example is `CommandLineArgumentProviders` where the actual string value that ends up on the command-line is up to the implementation to decide, and is not captured as an input by itself.
