### ISSUE TITLE
Configuration cache should support non-serializable lambdas

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#21109]
Currently configuration cache supports only lambdas directly implementing `java.io.Serializable` or lambdas whose backing classes conform to certain other serialization-related conventions (#13588).

Lambdas backed by simple functional interfaces such as `java.util.function.Consumer` do not fit into these constraints and therefore are not supported by the configuration cache. However, as an example, lambdas of this type could appear in task inputs as nested properties.

Related test: `org.gradle.api.tasks.LambdaInputsIntegrationTest#task with nested property defined by non-serializable Java lambda disables execution optimizations`

**Comment by h0tk3y** [comment]
This has been fixed by https://github.com/gradle/gradle/pull/23124, which forces all lambdas that come from build logic classes and are instantiated with the `LambdaMetaFactory` to be serializable (by transforming their instantiation call sites).
