### ISSUE TITLE
Composite builds depenendcy substitution not applied to testCompileClasspath and tesRuntimeClasspath

### ISSUE THREAD

**Issue by EugenMayer** [gradle/gradle#21112]
When using `includeBuild` with a depedencyResolution, the substituted projects are used the right way in the `compileClasspath` and `runtimeClasspath`. 

The problem is, that in the `testCompileClasspath` and `testRuntimmClasspath` the dependencies are not substituted.

### Expected Behavior
The dependency that has been configured to be substituted, should be substituted find  `testCompileClasspath` and `testRuntimmClasspath`  too.

### Current Behavior
Substitution works for `compileClasspath` and `runtimeClasspath`, but does not work  `testCompileClasspath` and `testRuntimmClasspath`

### Context
We are using composite builds for our project, one library that is used as a platform library (non test) is loaded via usual substitution.

### Steps to Reproduce 

Library
---
Create a library 'platform' in the folder platform and put some kind of test bean there
```java
@Component
public class TestBeanV1 {

}
```

Compile an publish to your nexus as a snapshot `0.0.0`

Now refactor `TestBeanV1` to `TestBeanV2` (and do not publish to your nexus, we want to use this as a composite build)

----
App

Create the most simple spring boot starter app in the folder app.

```
put this in your `settings.gradle`
```

```groovy
includeBuild('../platform') {
    dependencySubstitution {
        substitute module('de.example:platform') using project(':');
    }
}
```

then use this dependencies
```
dependencies {
    implementation(
            "de.example:platform:0.0.0-SNAPSHOT"
    )
}
```

Now in your application

```java
@SpringBootApplication
public class Application
{
  public static void main(String[] args)
  {
    context = SpringApplication.run(Application.class, args);
  }
}
```

resolve that bean
```java
@Configuration
public class SomeConfig
{
	@Autowired
	TestBeanV2 testBean;
}
```

Now add a smoke test for the application

```java
@ExtendWith(SpringExtension.class)
@SpringBootTest
class ApplicationTest
{
  @Test
  void main() {
    // dummy
  }
}
```

When you run the test, you should get a `ClassNotFound` exception for the `TestBeanV2` class - while `TestBeanV1` would actually work

### Your Environment
gradle 7.4.2
spring boot 2.6.8 (if interesting at all, does not matter for that case)

**Comment by donat** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by EugenMayer** [comment]
After digging around we could limit the scope of the issue. 

The problem only can be seen if the `group-id/artifact` based resolution would work means.
E.g. we publish as `com.example:mylib` into the nexus and in the project itself, the project is also named `mylib` and gradles `group-id` is configured to be `com.example`.

With the above setup, usually we do not need to use any substitution configuration but rather could just use `includeBuild '../mylib'` and it should work.


```
includeBuild('../mylib')
```

In those cases, we found that the substitution only works in the compile/runtime classpath's, not in the test classpath.
Naming the subproject 'mylib-foo', then providing this substitution

```
includeBuild('../mylib') {
    dependencySubstitution {
        substitute module('com.exampl') using project(':mylib-foo')
    }
}
```

**Comment by alllex** [comment]
Thank you for clarification. It is helpful to limit the scope of the issue.

However, there are still many unclear parts. Could you please provide a minimal project that reproduces the problem?

**Comment by alllex** [comment]
If the reproducer is provided at a later point the issue could get reopened
