### ISSUE TITLE
StackOverflowError thrown from internal Gradle code.

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#21116]
When building a project I sometimes get a `StackOverflowError`. If I run `./gradlew --stop` and then build the project again, I do not get the error for at least one build. Therefore, it has something to do with running more than 1 build with the same daemon.

### Expected Behavior

To not get a `StackOverflowError`.

### Current Behavior

[error.txt](https://github.com/gradle/gradle/files/9003083/error.txt)

### Context
Currently, I have to run `./gradlew --stop` every couple of runs, so it's intrusive to my workflow.

I have tried setting the stack size much higher in gradle.properties like so:
`-XX:ThreadStackSize=400000 -XX:CompilerThreadStackSize=400000`. The effect of this is strange in that sometimes setting the number higher works as a temporary fix but eventually, the issue starts occurring again.

### Steps to Reproduce 
I'm not able to provide a reproducer right now. I'm wondering if there is any quick insight anyone might have? If the problem continues, I'll try to work on a reproducer.

### Your Environment

Mac OSX 12.4
Gradle 7.5-rc-2-all

Build scan URL: https://scans.gradle.com/s/huleoj3bbbaxg

**Comment by donat** [comment]
Can you please check if it's also happening with 7.4? It might be a regression.

**Comment by mateuszkwiecinski** [comment]
I think I'm observing the same, in multiple projects, on multiple environments. 
Happens on `7.5.1` but not on `7.4.2`

Build scan: https://gradle.com/s/d4njl74ts5fz2

Sample failure:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/36954793/184620083-1edb48c7-69eb-459f-b5fd-3c574d6f791f.png">

**Comment by ganadist** [comment]
I have an similar issue.
After updated Gradle 7.5.1, whenever gradle failed build, I can get 2 errors on gradle scan.
One is actual error, and the other is `StackOverflowError` 
```
at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)
at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)
at org.gradle.execution.plan.Node.isCanCancel(Node.java:232)
at org.gradle.execution.plan.FinalizerGroup.isCanCancel(FinalizerGroup.java:155)
at org.gradle.execution.plan.CompositeNodeGroup.isCanCancel(CompositeNodeGroup.java:101)

```

**Comment by tprochazka** [comment]
I'm getting the same as @ganadist, but not sure if it is related to this issue.

**Comment by francescocervone** [comment]
The StackOverflowError printed in https://github.com/gradle/gradle/issues/21116#issuecomment-1228005104 happens also in our Android project. Gradle wrapper 7.5.1.
It looks it started to pop up randomly after enabling configuration cache, but that is just a guess.

**Comment by sschuberth** [comment]
Another build scan with the same issue: https://scans.gradle.com/s/evytma3z24kfw/console-log?page=3#L2089

**Comment by sschuberth** [comment]
> This is not using a composite build, though.

So interestingly, although our build is not a composite build, the [stacktrace](https://scans.gradle.com/s/evytma3z24kfw/failure?expanded-stacktrace=WyIxIl0&focused-stack-frame=1-5#2) indeed refers to `CompositeNodeGroup.isCanCancel`.

**Comment by sschuberth** [comment]
So the recursion seems to happen here if `group == this`:

https://github.com/gradle/gradle/blob/d1daa0cbf1a0103000b71484e1dbfe096e095918/subprojects/core/src/main/java/org/gradle/execution/plan/CompositeNodeGroup.java#L99-L101

**Comment by TimvdLippe** [comment]
Yesterday we upgraded from Gradle 7.4.2 to 7.5.1 and ran into this issue as well. This is our stacktrace:

```
at org.gradle.internal.logging.text.AbstractLineChoppingStyledTextOutput.doAppend(AbstractLineChoppingStyledTextOutput.java:41)
at org.gradle.internal.logging.text.AbstractStyledTextOutput.text(AbstractStyledTextOutput.java:82)
at org.gradle.internal.logging.text.AbstractStyledTextOutput.append(AbstractStyledTextOutput.java:39)
at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:267)
at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:287)
at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:287)
at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:287)
at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:287)
at org.gradle.internal.logging.text.TreeFormatter.writeNode(TreeFormatter.java:287)
```
