### ISSUE TITLE
Adding files to variants created from ComponentMetadataRules does not work when SNAPSHOT versions are used

### ISSUE THREAD

**Issue by britter** [gradle/gradle#21111]
### Expected Behavior

A ComponentMetadataRule that derives a new variant and adds files to that variant should work with SNAPSHOT dependencies where the file's name actually contains a timestamped version. 

### Current Behavior

It's not possible to add files to a variant using `withFiles { addFile("") }`. Gradle will construct the wrong file name.

### Context

I've a plugin that adds a `ComponentMetadataRule` for downloading POM files that live alongside the other artifacts inside a repository. I need to POM files in order to extract data form the `licenses` element in the POM. My rule does the following:

```kotlin
withFiles {
    removeAllFiles()
    addFile("${context.details.id.name}-${context.details.id.version}.pom")
}
```

However when this rule processes a snapshot version, I'm seeing the following error:

```
Cannot fingerprint input file property 'rootSpec$1': Could not resolve all files for configuration ':poms'.
> Could not resolve all files for configuration ':poms'.
  > Could not find commons-lang3-3.2.2-SNAPSHOT-3.2.2-SNAPSHOT.pom (org.apache.commons:commons-lang3:3.2.2-SNAPSHOT:20140111.132309-5).
    Searched in the following locations:
        https://repository.apache.org/content/repositories/snapshots/org/apache/commons/commons-lang3/3.2.2-SNAPSHOT/commons-lang3-3.2.2-SNAPSHOT.pom
```

### Steps to Reproduce 

1. Clone  https://github.com/britter/gradle-sandbox/
2. `cd component-metadata-rules-SNAPSHOTS/build.gradle.kts`
3. `./gradlew downloadPoms`

### Your Environment

Build scan URL: https://scans.gradle.com/s/hi2dnfy5yvhnk/failure#1

**Comment by ljacomet** [comment]
Change is merged
