### ISSUE TITLE
Improve documentation and logging around 'daemons'

### ISSUE THREAD

**Issue by Thrillpool** [gradle/gradle#21129]
I would like to understand, without reading the Gradle source code, what the various daemons are.

### Expected Behavior
I should read the documentation, and understand that there is a 'master' daemon which somehow manages the build, and 'worker' daemons which somehow do the work.

I should also not be confused when invoking gradle with --no-daemon spawns a load of processes with 'daemon' in the name.

I would also like to understand what is done in the 'master' daemon and what can drive its memory up, i.e. when it is appropriate that I should increase org.gradle.jvmArgs Xmx

Furthermore, when a worker daemon can not be reused, I would like to opt into logging that details to me why no existing worker daemon could be reused.

### Current Behavior
Presently everyone I know is baffled when --no-daemon spawns processes with the word 'daemon', similarly it is hard to argue when it is correct that I need to increase the memory of org.gradle.jvmArgs, or some rough metrics for what this memory should be given a large project.

When a worker daemon cannot be reused, due to https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/process/internal/DefaultJavaForkOptions.java#L225 returning false. No log is produced telling me why there was a miss, i.e. what things were not matching, so it's hard for me to optimise my build to reuse workers as much as possible.

### Context
I'm trying to optimise my gradle build, but it is made difficult by not really having much notion of what 'right' behaviour looks like. For instance the jvmArgs thing, at one point we needed 6G of jvmArgs. 

Nothing online really was concrete as to whether this was 'right', in the end it ended up being the spring dependency management plugin using too much memory due to caching poms. From my perspective I would concretely say that it is 'wrong' to have to set such a large Xmx for the 'master' daemon

The worker daemon vs master daemon thing makes it confusing just to discuss this matter with people.

**Comment by ljacomet** [comment]
Sorry for the late reply.

[Daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html) and [worker](https://docs.gradle.org/current/userguide/worker_api.html) documentation was updated since you filed this, we have a [blog post series](https://blog.gradle.org/how-gradle-works-3) that covers some of this topic. 

Would you consider this issue resolved or are there still missing pieces?
