### ISSUE TITLE
Please delete the Kotlin options preset of `kotlin-dsl` plugin

### ISSUE THREAD

**Issue by chachako** [gradle/gradle#21151]
https://github.com/gradle/gradle/blob/v7.5.0-RC3/subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt#L48-L49

Or can anyone explain why `kotlin-dsl` needs such an `afterEvaluate` setup? It's messing up my plugin development. 

When writing tests for the developed Gradle plugin, some code doesn't compile because the `1.4` level still uses the old Kotlin JVM backend. And if I write the plugin with some new Kotlin API, it will also say `NoSuchMethod` error, for example using the `kotlin.duration` API

Everything changed for the better when I unapplied the `kotlin-dsl` plugin. So this feels really bad, but please forgive me if I got something wrong 😪

**Comment by aSemy** [comment]
> Gradle plugins written in Kotlin target Kotlin 1.4 for compatibility with Gradle and Kotlin DSL build scripts, even though the embedded Kotlin runtime is Kotlin 1.5.

https://docs.gradle.org/7.4.2/userguide/compatibility.html#kotlin

In 7.5 the Kotlin target will still be set to 1.4 https://docs.gradle.org/7.5-rc-3/userguide/compatibility.html#kotlin

It will be changed to 1.6 in Gradle 8.0 https://github.com/gradle/gradle/issues/19568, but that ticket has taken so long it's already a version behind.

There was some discussion about this restriction here: https://github.com/gradle/gradle/issues/16345 but nothing came of it as far as I know. 

It's annoying that Gradle is so very behind on Kotlin versions.

**Comment by chachako** [comment]
> In 7.5 the Kotlin target will still be set to 1.4 [docs.gradle.org/7.5-rc-3/userguide/compatibility.html#kotlin](https://docs.gradle.org/7.5-rc-3/userguide/compatibility.html#kotlin)

That's too bad. So I think I should give up using the `kotlin-dsl` plugin

**Comment by aSemy** [comment]
What do you need in 1.6 that's missing in 1.4?

**Comment by chachako** [comment]
> What do you need in 1.6 that's missing in 1.4?

I think I need at least 1.5 for the IR-backend, and some APIs compiled by it

**Comment by aSemy** [comment]
> I think I need at least 1.5 for the IR-backend, and some APIs compiled by it

It's possible to override `kotlin-dsl`'s preference to be 1.6 (Normally I'd recommend sticking with 1.4)

https://handstandsam.com/2022/04/13/using-the-kotlin-dsl-gradle-plugin-forces-kotlin-1-4-compatibility/

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    `kotlin-dsl`
}

afterEvaluate {
    tasks.withType<KotlinCompile>().configureEach {
        kotlinOptions {
            apiVersion = "1.6"
            languageVersion = "1.6"
        }
    }
}
```

For other readers who want to use 1.6, I'll re-emphasise: just use 1.4. It's fine. There's no major differences. I'm saying this because I had some weird compilation issues when I tried setting 1.6 despite the warnings. So, as a message to my past self: save your time! Just use `sealed class` instead of `sealed interface`!

**Comment by h0tk3y** [comment]
The Kotlin language level for Gradle scripts is set to 1.4 in Gradle 7.x and it will only change in a major release. This is a constraint of the Gradle runtime that bundles specific versions of the Kotlin libraries.
