### ISSUE TITLE
New `--show-version` option captures Nokee task option

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#21152]
Nokee has a task option [`--show-version`](https://github.com/nokeedev/init.nokee.dev#nokee-task) to show the version of Nokee used by the project.

We added `-V` and `--show-version` in 7.5.  Due to the way we parse command-line options, we see `gradle nokee --show-version` as if it's our option and no longer show the Nokee version.

A simple fix is to rename `--show-version` to `--show-gradle-version` so we're less likely to conflict with other task options

**Comment by abstratt** [comment]
It seems this is a recurring risk, we where just lucky to have learned about this in time this time around. Probably too late for heed that suggestion here, but I think we should have a strategy for avoiding that Gradle options clash with task options.

Actually, it seems we should not consume global options until we know a task cannot handle them. If somehow that is not technically possible, then a naming strategy, or stricter rules for where Gradle options may appear would do. Thoughts?

**Comment by big-guy** [comment]
Yes, you're right.  All of the options available from `gradle -h` are potential problems with all task options.

> it seems we should not consume global options until we know a task cannot handle them. If somehow that is not technically possible, then a naming strategy, or stricter rules for where Gradle options may appear would do. Thoughts?

There are a few options that never run a build (`--status`, `--help`, `--stop`).  And all(?) of the other options affect the build before we know about any of the tasks. I think maybe `--rerun-tasks` is the only one that matters after the tasks are known.

OK, I typed a bunch of ideas here, but I just realized we already fixed this, it's just completely undocumented.

If you have this build:
```
abstract class MyTask extends DefaultTask {
    @Option(option="profile", description="foobar")
    void setProfile(String value) {
        System.out.println("Called setProfile")
    }
}

task mytask(type: MyTask)
```

If you run `gradle mytask --profile`, Gradle swallows the `--profile` as an option.

If you run `gradle -- mytask --profile=foo`, we treat `--profile` as a task option.

I opened https://github.com/gradle/gradle/issues/21158

I still think it's a good idea to rename show-version to show-gradle-version.

**Comment by abstratt** [comment]
Thanks for sharing that

> I still think it's a good idea to rename show-version to show-gradle-version.

Would you say that is a special case? Or should we have a default strategy to name gradle options so they never/are unlikely to clash with task options?

**Comment by big-guy** [comment]
I think it depends on the option.  I would pick good names first and then consider the impact.
