### ISSUE TITLE
Unix start script is overwriting the `APP_NAME` env var value

### ISSUE THREAD

**Issue by bcmedeiros** [gradle/gradle#21164]
### Expected Behavior
When using the application plugin and running my apps using the generated start script, I expect any environment variable that I set from outside to be available to be consumed by my app.

### Current Behavior
If I set a environment variable called `APP_NAME`, the value for this variable is overwritten by the start script (Unix version only, Windows version works fine).

### Context
I run hundreds of containers in a cloud container service, and as a standard in all environments, we always set `APP_NAME` and `APP_VERSION` environment variables to be consumed by loggers.
Now that we are migrating to Gradle, we noticed that, regardless of what we set for `APP_NAME`, Gradle start scripts overwrites this to what it _thinks_ is the app name.

### Steps to Reproduce 
1. Create a simple java application that prints the `APP_NAME` env var
2. Enable the `application` plugin and the dist package, unzip it
3. run `APP_NAME=my-custom-name-from-outside ./app`
4. `app` will be printed, instead of `my-custom-name-from-outside`

### Your Environment
Gradle 7.4.2 in any Unix OS

**Comment by medeirosb** [comment]
Any updates on this?

Removing the variable definition seems a no-brainer to me, the variable is not used in the script, the windows counterpart does not have the same variable, and there is a PR with tests.

Anything else I could do to speed this up?

**Comment by ljacomet** [comment]
The fact that the windows script do not have the equivalent makes it looks like a clean up indeed. However some apps out there might depend on it. So it could be a breaking change.

Given the above, we can do this but in 8.0. So it will stay around for a while before being fixed and your PR merged.

**Comment by Fleshgrinder** [comment]
The real problem is that the script uses uppercase variable names, which are reserved for Shell internal variables and environment variables. This would never have been an issue if proper lowercase variables would be used within the script for all its own variables. I think that the proposed patch for Gradle 8 is not going far enough, and that we should clean up the script more than this.

**Comment by bcmedeiros** [comment]
@Fleshgrinder I agree!

I can submit additional patches after this one is merged.

**Comment by bcmedeiros** [comment]
Just went to rebase the PR, it seems `APP_NAME` has been removed already.

**Comment by bcmedeiros** [comment]
In commit b85d728c0f5f66408a2ddefb6dd1118006dbe46c
