### ISSUE TITLE
FileCopyDetails.setMode should have a better API for Kotlin DSL

### ISSUE THREAD

**Issue by hakanai** [gradle/gradle#21171]
`FileCopyDetails.setMode` currently forces us to provide the file mode as an int.

But the value the docs tell us to pass in as an example is in octal, and Kotlin doesn't support octal literals. So we have to jump through hoops to pass in an appropriate value.

### Expected Behavior

A method like `mode(action: FileModeDetails.() -> Unit)` could pass a details object into the action, which then has a number of methods available to set the file mode. After the action returns, it can convert this back to an int, if that's how it prefers to work with file modes internally.

So we could then write something like:

```kotlin
        if (path.startsWith("bin/")) {
            mode {
                executable = true
            }
        }
```

Or `setExecutableForAll(true)`, or whatever.

### Current Behavior

Currently we're forced to either provide the file mode in decimal or hex, or to use a string and convert it ourselves at runtime.

```kotlin
        if (path.startsWith("bin/")) {
            mode = "755".toInt(radix = 8)
        }
```

But even this doesn't clearly describe the intent. The reader doesn't necessarily know that this is adding the ability to execute. Maybe they don't know that it's a UNIX file mode without reading the docs. Or maybe I'm setting the mode to _reduce_ permissions on the file.

### Context

Files packed inside a jar tend to have lost their modes. This means if you have a jar which contains executable files, you have to do something like this:

```kotlin
val copyStuff by tasks.registering(Copy::class) {
    from(zipFilePath)
    eachFile {
        if (path.startsWith("bin/")) {
            mode = "755".toInt(radix = 8)
        }
    }
}
```

Kotlin themselves seem to think that nobody should be using octal anymore, so it's highly unlikely they will ever add octal literals.

Reference: [Kotlin feature request for octal literals (declined)](https://youtrack.jetbrains.com/issue/KT-44409).

**Comment by eskatos** [comment]
With an explicit DSL you would need 9 properties (e.g. `ownerRead`, `ownerWrite`, `ownerExecute`, `groupRead`, `groupWrite`, `groupExecute`, `otherRead`, `otherWrite`, `otherExecute`,).

Another option would be to reuse `java.nio.file.attribute.PosixFilePermission` from the JDK.

**Comment by hakanai** [comment]
You'd probably also want `allRead`, `allWrite`, `allExecute`.

In the 755 example even, the intent isn't "set the mode to 755", but rather "set a+x".

**Comment by ephemient** [comment]
Why not leverage [java.nio.file.attribute.PosixFilePermissions](https://docs.oracle.com/javase/8/docs/api/java/nio/file/attribute/PosixFilePermissions.html)? Gradle doesn't support running on Java 6 anymore so it's always available.

**Comment by Vampire** [comment]
Btw., besides that it seems there is some API soon, you can not only use hex and decimal, you can also use binary, which is practically identical to the "rwx" form and is the ultimate firm, because with any form or api you just set flags.

So for example for `755` which is `rwxr-xr-x`, you can also use `0b0111_0101_0101`.
