### ISSUE TITLE
Unable to specify configuration when substituting module with project dependency.

### ISSUE THREAD

**Issue by kasobol-msft** [gradle/gradle#21177]
Extracting from https://github.com/gradle/gradle/issues/21017#issuecomment-1172988060 (see discussion there for more context).

Lack of `org.gradle.api.artifacts.DependencySubstitutions.project(path, configuration)` that would mirror `org.gradle.kotlin.dsl.DependencyHandler.project(path, configuration)` is a painful gap to work around to.

I have created reproducer with readme here https://github.com/kasobol-msft/gradle-issue-reproducer/blob/project-sub/README.md 

Short description:
- I'm trying to migrate from Maven.
- In my setup there are modules that produce artifact (jar) that's composed from main and additional source set compilation outcomes (in my real application it's MRJAR or JDK8 + module-info, other examples could be generated sources).
- For cross module dependencies this require `implementation(project(":projectA", "customConfiguration"))`, otherwise types from extra source sets are not visible during compilation.
- Some of the modules normally depend on last release of other modules (i.e. version from maven central, not sources). But we have workflows where we'd like to substitute them with "modules from sources", i.e. 
  ```
  configurations.all {
    resolutionStrategy.dependencySubstitution {
          substitute(module("org.apache.commons:commons-lang3")) // let's pretend that this is projectA jar published to maven 
  central.
              .using(project(":projectA"))
              .because("why not")
      }
  }
  ```
  Unfortunately, this makes types from extra source roots invisible to the module that's making substitution.

### Expected Behavior
Either:
- types from extra source roots should be visible to modules depending on it without need to create extra configuration. (end of the day they all contribute to same artifact).
- there should be a way to substitute module with specific configuration of a module, i.e. 
    ```
    configurations.all {
      resolutionStrategy.dependencySubstitution {
          substitute(module("org.apache.commons:commons-lang3")) // let's pretend that this is projectA jar published to maven 
  central.
              .using(project(":projectA", "customConfiguration"))
              .because("why not")
      }
  }
  ```

### Current Behavior
I'm unable to compile modules that substitute modules with a project. They don't see types from extra source roots.

### Context

For the context. I'm prototyping a migration of Azure SDKs for Java where:

I create a custom configuration on the top of Java Library Plugin to get cross JDK8 and JDK9+ composite build. See
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/buildSrc/src/main/kotlin/com.azure.java-conventions.gradle.kts#L52-L62
This is to make multi-module builds notice both JDK8 and 9 compilation products.

Then I declare dependencies in few places like:
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/sdk/core/azure-core-amqp/build.gradle.kts#L10

But there are areas where I don't by default like:
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/sdk/eventhubs/azure-messaging-eventhubs/build.gradle.kts#L11

However we have a couple of workflows where we'd like to use module substitution in both this place or programmatically as a global option. The latter example here.
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/buildSrc/src/main/kotlin/com.azure.java-conventions.gradle.kts#L331-L340

However, lack of substituting with previously defined custom configuration leads to compile errors (which were the reason configuration got developed in the first place).

I have tried to "solve" the problem by getting rid of that custom configuration and rigging javaCompile to compile both 8 and 9+ (hacky but worked). 

This has worked mostly, until I realized that I have a need to substitute "test jar" with dependency on "tests" configuration in the test project...
https://github.com/kasobol-msft/azure-sdk-for-java/blob/489f78446b1ec13b44f8b04f12d3b8150742083e/sdk/eventhubs/azure-messaging-eventhubs/build.gradle.kts#L14
Which in turn brings me back to lack of  `org.gradle.api.artifacts.DependencySubstitutions.project(path, configuration)` API.

**Comment by kasobol-msft** [comment]
@ljacomet Thank you. The below worked. It would be great though if java plugin could infer how secondary variant should look like from the primary one.
Full commit can be seen [here](https://github.com/kasobol-msft/azure-sdk-for-java/commit/c8f32e50a356cde0b4e2f87751cde212fc759a73).
```
// See https://github.com/gradle/gradle/issues/21177#issuecomment-1179118965
sourceSets.getByName("moduleInfo").output.classesDirs.files.forEach {
    configurations.apiElements.get().outgoing.variants.getByName("classes")
        .artifact(it) {
            type = ArtifactTypeDefinition.JVM_CLASS_DIRECTORY
            extension = ""
            builtBy(tasks.getByName("compileModuleInfoJava"))
        }
}
```

**Comment by kasobol-msft** [comment]
Now I'm running into another problem that could be solved by adding `org.gradle.api.artifacts.DependencySubstitutions.project(path, configuration)`. I have one project that publishes 2 artifacts. I.e. additional test jar. I.e.
```
val testJar = tasks.register<Jar>("testJar") {
    from(sourceSets.test.get().output)
    archiveClassifier.set("tests")
}

configurations {
    create("tests") {
        extendsFrom(testImplementation.get())
    }
}

artifacts.add("tests", testJar)

tasks.named("build") {
    dependsOn("testJar")
}
```

In other projects I depend on "tests" variant, i.e.
```
dependencies {
    testImplementation("com.azure","azure-core-test", version="<version>", classifier = "tests")
}
```

How can I substitute that with project("azure-core-test", "tests") ?

**Comment by Vampire** [comment]
Maybe you want to have a look at the `test-fixtures` plugin.

**Comment by kasobol-msft** [comment]
Thanks for the pointer @Vampire this looks like a promising alternative.

**Comment by ljacomet** [comment]
As @Vampire indicated, this is again something that should be solved with declaring and consuming variants.

Closing this as the original issue is resolved.
