### ISSUE TITLE
resolveConsistentlyWith can't downgrade directly declared dependencies

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#21182]
Given configurations A and B, where B extends A, B is set to resolve consistently with A. If B directly declares a dependency on a module from A in a higher version compared to what was resolved in A, Gradle can't resolve the version for B.

### Expected Behavior
Given the request for the "consistent" version resolution, the same version as A should be enforced.

### Current Behavior
Resolution fails.

### Context
We are trying to develop a plugin to allow users easily build modules for a specific java-based product. As such, we inject some dependencies through the plugin for test and compilation. Users can add their own dependencies. The test harness has a number of dependencies, but we'd like the test classpath to eventually use the same versions as the compile classpath. Tried using the consistent resolution and it works as long as it has to upgrade the dependencies. Downgrade though does not work.

### Steps to Reproduce 
Minimal build:
```groovy
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

configurations {
    testCompileClasspath.shouldResolveConsistentlyWith(configurations.compileClasspath)
}

dependencies {
    implementation 'org.apache.commons:commons-text:1.9'
    testImplementation 'org.apache.commons:commons-lang3:3.12.0'
}
```
Here `commons-text` has a transitive on `commons-lang3:3.11.0`. But specifying a dependency on `3.12.0` breaks the build:
```
> Task :dependencyInsight
org.apache.commons:commons-lang3:3.11 FAILED
   Selection reasons:
      - By constraint : version resolved in configuration ':compileClasspath' by consistent resolution
   Failures:
      - Could not resolve org.apache.commons:commons-lang3:{strictly 3.11}.
          - Cannot find a version of 'org.apache.commons:commons-lang3' that satisfies the version constraints:
               Dependency path ':gradletest:unspecified' --> 'org.apache.commons:commons-lang3:3.12.0'
               Constraint path ':gradletest:unspecified' --> 'org.apache.commons:commons-lang3:{strictly 3.11}' because of the following reason: version resolved in configuration ':compileClasspath' by consistent resolution
               Dependency path ':gradletest:unspecified' --> 'org.apache.commons:commons-text:1.9' (compile) --> 'org.apache.commons:commons-lang3:3.11'
```

I believe this is part of the `strictly` logic - if people declared a certain dependency there must be a reason, so we should raise an issue. But I don't find it particularly intuitive. The downgrade instead works just fine if the downgrade happens for a transitive dependency, i.e. this couple of dependencies
```
    implementation 'org.apache.commons:commons-text:1.7'
    testImplementation 'io.bitbucket.5faces:common:1.0.4'
```
causes `commons-lang3` `3.12.0` requested by the test dependency to be downgraded correctly to the `3.9` version resolved in the compile classpath

**Comment by donat** [comment]
That's a design decision of the dependency management engine. We want you to fix your dependency declarations.
