### ISSUE TITLE
Dark style for Gradle Build Scan

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#21181]
The Gradle Build Scan webpage is very bright and hard on the eyes. I suggest an ability to specify the style within the buildscript so that when you click the link it is already a different style.

Some syntax ideas:

``` kotlin
gradleEnterprise {
  buildScan {
	style = BuildScanStyle.DARK
    // OR
    style = File("myCustomStyle.css")
   // OR
   style.primaryColor = "#FFFFFF"
   style.secondaryColor = "#000000"
  }
}
```

**Comment by donat** [comment]
The build scan feature belongs to the Gradle Enterprise team. Please reach out to them with your request.
In any case, the build scan style won't be configurable from the build script.
