### ISSUE TITLE
Document dependencies report output key

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#21197]
When I run the `dependencies` task it prints a key at the end for the various annotations used:

```
(c) - dependency constraint
(*) - dependencies omitted (listed previously)
(n) - Not resolved (configuration is not meant to be resolved)
```

It would be nice if that key was also included in the docs, perhaps under ["Viewing and debugging dependencies"](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html#sec:listing_dependencies).

It would be a good opportunity to elaborate on the different annotations, and possibly also link to other relevant sections of the docs. For example, what does "Not resolved (configuration is not meant to be resolved)" really mean (when should I expect it, why is it not meant to be resolved, etc.)?

### Context
I'd like to better understand the output of this report.

**Comment by vlsi** [comment]
Relevant issue: https://github.com/gradle/gradle/issues/17339

**Comment by nathan-contino** [comment]
Addressed by https://github.com/gradle/gradle/pull/22456
