### ISSUE TITLE
`@Option`s should be applied before task is configured

### ISSUE THREAD

**Issue by jeremy-im** [gradle/gradle#21207]
currently it very easy to add CLI options to a task, but very difficult to use them to affect the task configuration.

### Expected Behavior

the code in the user's gradle scripts should never see different values for the `@Option`s.

### Current Behavior

the task configuration code sees the `@Option` default values before they are set from the command line, while the task execution code sees the values after having been set.

### Context

fixing this would (among other things) make it possible for a task to `dependOn` different stuff according to the command line.

### Steps to Reproduce 

my fork of the gradle-issue-reproducer: https://github.com/jeremy-im/gradle-task-option

### Your Environment

_(this is specified by the reproducer action, which I did not change)_

**Comment by donat** [comment]
This is expected. You can only read the task options during execution time, not at configuration time. You'd need to use something like a project property to affect project configuration.

**Comment by jeremy-im** [comment]
if this is expected, then it should be mentioned prominently in the documentation:
https://docs.gradle.org/current/userguide/custom_tasks.html#limitations
