### ISSUE TITLE
Unable to configure buildSrc pluginManagement with init script and Gradle.settingsEvaluated for buildSrc/settings.gradle.kts

### ISSUE THREAD

**Issue by ZSmallX** [gradle/gradle#21204]
I try to use Gradle init script to specify pluginsManagement#repositories to custom maven. In the init script, I use Gradle#settingsEvaluated to set the pluginsManagement#repositories. 

### Expected Behavior

Unable to set pluginsManagement#repositories for buildSrc plugins to custom maven repo.

### Current Behavior

Set pluginsManagement#repositories for buildSrc plugins and take effect to custom maven repo.

### Context

Uses Gradle init script to automake builds, each project does not need a configuration on buildSrc plugins pluginsManagement#repositories.

### Steps to Reproduce 

command:

```
./gradlew --init-script=init.gradle.kts --info
```

init.gradle.kts

```
settingsEvaluated {
    pluginManagement {
        repositories {
            maven(url = "http://mymaven/repository/")
        }
    }
}
```

buildSrc/build.gradle.kts

```
// ...
// Uses plugins in buildSrc.
plugins {
    `kotlin-dsl`
}
// ...
```

settings.gradle.kts

```
// ... Without congifuring pluginManagement#repositories.
```

### Your Environment

Build scan URL: None

It's a local build. Had tried Gradle7.4.2, it has the same question.

**Comment by donat** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.



---
Have you tried using the `gradle.beforeSettings` callback?

**Comment by ZSmallX** [comment]
> Sorry that you're having trouble with Gradle!
> 
> Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.
> 
> Have you tried using the `gradle.beforeSettings` callback?

Sorry for late reply.

I had tried `gradle.beforeSettings`, it does not work for buildSrc as well.

Reproducer project: https://github.com/ZSmallX/gradle-issue-reprocuder-21204

Sample tooling script see`my-tooling-script.sh`.

**Comment by jbartok** [comment]
Duplicates #1055
