### ISSUE TITLE
Introduce Strongly Typed Dependency Block

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#21209]
Improve the discoverability and other aspects of dependency handling with a more strongly-typed dependency block.

Spec: https://docs.google.com/document/d/1jKKRdFMCsYQ0b0poPK5wHKb01Ng1f1_0Ou9VOhqCO3E/edit?usp=sharing

**Comment by octylFractal** [comment]
Related work: #20868

**Comment by melix** [comment]
Spec not readable :(

**Comment by octylFractal** [comment]
Unfortunately, I can't make it public, so please request access and I will grant permissions to view.
