### ISSUE TITLE
Task graph discarded due to ever changing JAVA_MAIN_CLASS_<PID> variable 

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#21224]
On MacOS, the JVM sets an environment variable called [JAVA_MAIN_CLASS_\<PID\>](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/macosx/bin/java_md_macosx.c#L967-L982). Even though we seem to have filters for that variable at places, it seems that variable still trips the configuration cache (although not in a consistent way - haven't found a good pattern yet).

### Expected Behavior

Configuration cache can be reused across gradle runs. 

### Current Behavior

Configuration cache cannot be reused due to an internal environment variable set by the JDK on MacOS.

### Steps to Reproduce 

This is reproducible with Gradle's own repo. 

First, delete the configuration cache area within the project:

```
rm -Rf .gradle/configuration-cache/
````

Running a Gradle test should store the configuration entry.

```

 ./gradlew :configuration-cache:test --tests "ConfigurationCacheKeyTest"
Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused because environment variable 'JAVA_MAIN_CLASS_94216' has changed.
Type-safe project accessors is an incubating feature.

0 problems were found storing the configuration cache.

See the complete report at file:///Users/rafael/sources/gradle/build/reports/configuration-cache/eegk8i62vn2j6om1e8649enbw/6l98ox4wro44bs36jxkavda1h/configuration-cache-report.html

BUILD SUCCESSFUL in 4s
564 actionable tasks: 564 up-to-date

A build scan was not published as you have not authenticated with server 'ge.gradle.org'.
Configuration cache entry stored.

```

Running a second time with the same command line should successfully reuse the existing configuration cache entry created in the previous run. 

```

./gradlew :configuration-cache:test --tests "ConfigurationCacheKeyTest"
Configuration cache is an incubating feature.
Calculating task graph as configuration cache cannot be reused because environment variable 'JAVA_MAIN_CLASS_94252' has changed.
Type-safe project accessors is an incubating feature.

0 problems were found storing the configuration cache.

See the complete report at file:///Users/rafael/sources/gradle/build/reports/configuration-cache/eegk8i62vn2j6om1e8649enbw/9wo60ay4bps9ogtwuzx4q2g8a/configuration-cache-report.html

BUILD SUCCESSFUL in 4s
564 actionable tasks: 564 up-to-date

A build scan was not published as you have not authenticated with server 'ge.gradle.org'.
Configuration cache entry stored.

```

Running it again results in similar output, with a different variable name due to the changing PID. 

### Your Environment

MacOSX

$ uname -prsm  
Darwin 21.5.0 arm64 arm

$ java --version
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)

**Comment by xmlking** [comment]
same problem with java 17 and gradle 8.1 on MacOS Apple silicon

**Comment by franckrasolo** [comment]
I can confirm that this issue is [fixed](https://bugs.openjdk.org/browse/JDK-8274397) for macOS as of Java 19.

**Comment by mlopatkin** [comment]
There are now ways to query subsets of environment variables ([prefixedBy provider](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#environmentVariablesPrefixedBy-java.lang.String-) and ValueSource) without making all of them build configuration inputs, so the build author can avoid accidentally making `JAVA_MAIN_CLASS_xxx` the input to the configuration cache.

Please report if the `gradle/gradle` build is still prone to invalidation because of this.
