### ISSUE TITLE
gradle init --type java-library creates wrong version in dependency for JUnit

### ISSUE THREAD

**Issue by nantoka69** [gradle/gradle#2123]
### Expected Behavior
Creating a java library project directory with `gradle init --type java-library` should create a JUnit test case that compiles with the JUnit version specified in the `testCompile` dependency in the generated `build.gradle` file.

### Current Behavior
Creating a java library project directory with `gradle init --type java-library`  creates a Class `LibraryTest.java` that starts with `import org.junit.Test;`. This is the correct import for JUnit version 4 but creates the famous "package org.junit does not exist" error when used with JUnit version 3. Unfortunately the generated `build.gradle` file contains the dependency `testCompile 'junit:junit:3.8.2'` Manually updating the version to 4.12 solved the problem.

### Context
Being familiar with JUnit but not being the super expert who writes test cases on a day to day base it took me quite a bit to find out what was wrong. Especially as googleing for "package org.junit does not exist" shows numerous entries who explain how to integrate JUnit properly with Gradle and the generated code did it exactly this way.

### Steps to Reproduce (for bugs)
Run `gradle init --type java-library`
Run `./gradlew test` in the top level directory of the generated project and you get the compile error. 

### Your Environment
Gradle 2.10
------------------------------------------------------------

Build time:   2016-01-26 15:17:49 UTC
Build number: none
Revision:     UNKNOWN

Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on July 8 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.4.0-78-generic amd64

**Comment by eriwen** [comment]
@nantoka69 This is working as of Gradle 3.5 and probably much earlier. I encourage you to update, as I expect we will not have a maintenance release to fix this in 2.10.

Please let me know if something is still amiss and i'll reopen this issue.
