### ISSUE TITLE
How to use msys2 with gradle

### ISSUE THREAD

**Issue by aleluiah** [gradle/gradle#21230]
Hi, please can you guild me on how to use msys2 for gradle please check the link below
https://stackoverflow.com/questions/51226596/gradle-file-paths-too-long-for-windows

**Comment by donat** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
