### ISSUE TITLE
wrapper task generates an invalid distributionUrl link

### ISSUE THREAD

**Issue by rentalhost** [gradle/gradle#21245]
### Problem

After modifying the file `gradle.properties` and set `wrapper.gradleVersion` property to `7.5.0-rc-5` (although it happened with earlier versions) and running the `wrapper` task, the `gradle-wrapper.properties` file is updated with an invalid `distributionUrl`. It seems correct to me, but the file is not distributed through the indicated link (`https://services.gradle.org/distributions/gradle-7.5.0-rc-5-bin.zip`), but with the link `https://services.gradle.org/distributions/gradle-7.5-rc-5-bin.zip` (`7.5` instead of `7.5.0`).

So in practice whenever the `wrapper` is updated I need to manually update the correct link.

### Context

I'm developing a plugin for IntelliJ platform, the code can be found in https://github.com/hammer-tools/php-hammer.

### Steps to Reproduce 

Change the `gradle.properties` file, setting the `wrapper.gradleVersion` property to a version `7.5.0-rc-5` and run the `wrapper` task.

### Your Environment

Windows 10

**Comment by nevack** [comment]
AFAIKб you should use version specified at https://gradle.org/releases/ as value to `wrapper.gradleVersion`.
So in your case you should use `7.5-rc-5`, not `7.5.0-rc-5` (is it git tag?)

**Comment by rentalhost** [comment]
@nevack it make sense. For some reason after I upgraded from `7.4.2` to `7.5.0-rc-x` I kept the `major.minor.patch` schema and it doesn't work. However, when using only the version like `7.5-rc-x`, without the `patch` definition, everything works as expected.
