### ISSUE TITLE
Build fails after upgrading gradle to 7.3.3

### ISSUE THREAD

**Issue by rushikesh997** [gradle/gradle#21257]
Since gradle 7.3.3 does not support using insecure repositories, I have moved one of the maven repositories from insecure one to secure one in my android gradle project.
Basically from
insecure - maven ("http://developer.huawei.com/repo/") to
secure - maven ("https://developer.huawei.com/repo/")

The build works fine on local mac machine. But on remote jenkins machine hosted on AWS EC2, we are facing an issue while building the app. The error is 

``` 2022-07-14T12:35:46.415+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]             > Could not GET 'https://developer.huawei.com/repo/com/huawei/hms/log/5.0.0.300/log-5.0.0.300.pom'.
2022-07-14T12:35:46.416+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]                > Certificate for <developer.huawei.com> doesn't match any of the subject alternative names: [a248.e.akamai.net, *.akamaihd-staging.net, *.akamaihd.net, *.akamaized-staging.net, *.akamaized.net]
```
Before, I was using gradle 6.5 and insecure repository which worked fine without any issues.

**Comment by donat** [comment]
I'm afraid that we can't do much here as this is an issue with certificates within your organization. 

FYI you can use insecure repositories by calling [allowInsecureProtocol](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.repositories.MavenArtifactRepository.html#org.gradle.api.artifacts.repositories.MavenArtifactRepository:allowInsecureProtocol).
