### ISSUE TITLE
Incremental Java compiler fails with compile errors due to incorrect classpath, while full compilation works

### ISSUE THREAD

**Issue by simon-spinner** [gradle/gradle#21255]
If a Java class with the same fully-qualified name exists in a compile dependency of a module and also in the module itself, the incremental Java compiler picks the definition provided by the dependency. Only if the sources of the class in the module did 
change, the incremental compiler will resolve to the local one.

### Expected Behavior
Incremental compile should always succeed if a full compilation succeeds and vice versa. It should also consistently select the same definition of a class in case of conflicting definitions.

### Current Behavior
If a class that depends on a class with conflicting definitions is changed, the incremental compilation may fail if the two conflicting definitions are not compatible. If the conflicting class in the local module did also change, the incremental compiler passes it as a changed source file to the compiler. Then the compiler resolves any references for this class to the local definition. If the conflicting class did not change, the class files from the previous compilation of the module are appended to the **end** of the classpath. This gives them the lowest priority during resolution. As a result, references will be resolved to the definition exposed by the external dependency. 

A full rebuild after the failed build succeeds.

### Context
We have multiple occurrences of such conflicting classes in a large code base. The developers often have to trigger a gradle build multiple times until it succeeds (especially after changing Git branches).

#### Module base

BaseClass.java:
```java
package org.example;

public class BaseClass {

}
```

#### Module impl

This module depends on the base module.

BaseClass.java
```java
package org.example;

public class BaseClass {

    public void method() {}

}
```

Impl.java
```java
package org.example;

public class Impl extends BaseClass {

    public void repro(Impl i) {
        i.method();
    }
}
```
Archive containing example:
[duplicateclasses.zip](https://github.com/gradle/gradle/files/9111874/duplicateclasses.zip)

Steps to reproduce:
- Do a full build of the project
- Change Impl.java, but not BaseClass.java
- Trigger another build (now using the incremental compiler)
- Build fails with:

```
  duplicateclasses\impl\src\main\java\org\example\Impl.java:6: error: cannot find symbol
        i.method();
         ^
  symbol:   method method()
  location: variable i of type Impl
```

### Your Environment
Gradle 7.5-RC2 (but also observed on older versions)
Java 11

**Comment by simon-spinner** [comment]
The code adding the destination directory at the end of the classpath is in org.gradle.api.internal.tasks.compile.incremental.recomp.AbstractRecompilationSpecProvider#includePreviousCompilationOutputOnClasspath

**Comment by jpenilla** [comment]
From my testing moving the previous compilation outputs to the front of the classpath does allow the incremental compile to run. However, it seems like Gradle can still get confused by the duplicate named elements and end up requesting more files to be recompiled than is actually needed. Which no doubt is better than a failure but in some cases will negate the benefit of an incremental compile.

**Comment by Shivaansh-Agarwal** [comment]
Facing this in gradle 7.2 
Can someone please suggest any fixes/work-arounds for the same?
