### ISSUE TITLE
Use `version-catalogs` in `plugins` block of `build.gradle.kts` could not compile in idea.

### ISSUE THREAD

**Issue by blling** [gradle/gradle#21264]
Use `version-catalogs` in `plugins` block of `build.gradle.kts` could not compile in idea.

### Expected Behavior
no compile error

### Current Behavior
compile error

### Context
idea script error with red line

### Steps to Reproduce 
Use `version-catalogs` in `plugins` block of `build.gradle.kts` could not compile in idea.
![image](https://user-images.githubusercontent.com/26540808/179146231-f909227e-dc9c-407b-8773-d8a649695704.png)

`setting.gradle.kts`:
![image](https://user-images.githubusercontent.com/26540808/179146712-7f33e557-9209-405c-acab-faaf3cc11e39.png)

### Your Environment
idea: 2022.1.3 Community Edition
gradle: 7.5

**Comment by JavierSegoviaCordoba** [comment]
Known issue which is not a Gradle problem. It is reported on YouTrack and there is a IntelliJ plugin to remove that incorrect error, because it compiles in CLI.

**Comment by donat** [comment]
For future reference, here's the IntelliJ issue: https://youtrack.jetbrains.com/issue/KT-49161
