### ISSUE TITLE
Support SARIF format in Checkstyle plugin

### ISSUE THREAD

**Issue by dantonyuk** [gradle/gradle#21266]
Allow to turn on the SARIF output format for the Gradle Checkstyle plugin.

### Expected Behavior

When defined something like the following is defined (similar to `xml` / `html`):

```groovy
checkstyleTask {
  reports {
    sarif {
      required = true
    }
  }
}
```

generate the SARIF report by using SARIF output format (https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/SarifLogger.html)

### Current Behavior

Currently, there is no way to generate SARIF output.

### Context

GitHub supports SARIF format and generates code anotations looking like code-review comments. It is very convenient to have them this way so we can see the warning write next to the code it relates to.

**Comment by jknair0** [comment]
Hi. I would like to work on this. Can I pick this up ?

**Comment by jknair0** [comment]
Gradle currently uses ant task to execute the checkstyle. The CheckstyleAntTask current doesnt support the option of 'sarif'. I have raised a request there at https://github.com/checkstyle/checkstyle/issues/11985. 

Should we wait for that to release or Should we attempt to implement Sarif Logger like we do for html ?
