### ISSUE TITLE
Jacoco merge tests reports for different test suites and use merged report for JacocoCoverageVerification

### ISSUE THREAD

**Issue by swanandvk** [gradle/gradle#21279]
### Expected Behavior

jacoco plugin should allow option to configure test source roots for generating merged jacoco test report eg: unit + integrationTest which in turn should be used for JacocoCoverageVerification.

### Current Behavior

JacocoCoverageVerification only uses unit tests source root configured using JVM Test Suite Plugin

### Steps to Reproduce 

- apply JVM Test Suite Plugin
- create two test suite config for integrationTest and test (unit test)
- do `gradle build`

Observation:

- generated report fails to apply JacocoCoverageVerification rules defined as part of combined report.
### Your Environment

Build scan URL:

**Comment by reinsch82** [comment]
Sorry for the late reply.

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/23223

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

related
 - https://github.com/gradle/gradle/issues/30445
