### ISSUE TITLE
Generate Kotlin DSL accessors for test suite tasks

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#21285]
### Expected Behavior
I can write the following in a build script:
```kotlin
testing {
    suites {
        register("functionalTest", JvmTestSuite::class)
    }
}

tasks.functionalTest {
    // config
}
```

### Current Behavior
![image](https://user-images.githubusercontent.com/170028/179707243-0ad17c57-c657-4305-970a-2e7dfd689653.png)

### Context
I expect tasks generated by built-in Gradle features will all have Kotlin DSL accessors generated for them which I can then use in the build script to configure the tasks.

**Comment by jbartok** [comment]
Unfortunately, it's not really something we can do, with the way things work currently. More info here: https://docs.gradle.org/current/userguide/kotlin_dsl.html#type-safe-accessors
