### ISSUE TITLE
kali linux apt install gradle and then gradle -v failed,Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true  FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by passerbyo** [gradle/gradle#21296]
### Expected Behavior
type gradle -v and then shows me version

### Current Behavior
gradle -v
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

FAILURE: Build failed with an exception.

* What went wrong:
org/fusesource/jansi/AnsiOutputStream

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

### Context
affect greatly

### Steps to Reproduce 
apt install gradle and type gradle -v.Then failed.

### Your Environment
gradle -v
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

FAILURE: Build failed with an exception.

* What went wrong:
org/fusesource/jansi/AnsiOutputStream

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

uname -a
Linux kali 5.15.0-kali3-amd64

java --version
```Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1, mixed mode, sharing)```

**Comment by donat** [comment]
Please note that Gradle is not involved in the maintenance of the Gradle apt package. I had a quick look and it seems like the latest package contains Gradle 4.8, which is not compatible with Java 11, hence the error message. I strongly suggest installing Gradle from the recommended sources: https://gradle.org/install/.
