### ISSUE TITLE
Question marks in Ivy repository's patternLayout are incorrectly encoded

### ISSUE THREAD

**Issue by HoldYourWaffle** [gradle/gradle#21297]
### Expected Behavior
- Gradle should not encode a '?' character in `patternLayout` as `%3F`, or there should be a mechanism to 'escape' this behavior.
- Gradle should not put misleading URL's in the 'searched in the following locations' section of a failed build :(

### Current Behavior
Given a declaration like this:
```groovy
repositories {
    ivy {
        // ...
        patternLayout {
            artifact '/download?file=[module].[ext]'
        }
        // ...
    }
}
```

Gradle tries to send a request to:
```
(...)/download%3Ffile=XXX.YYY
```

While giving the following error:
```
> Could not find XXX
     Searched in the following locations:
       - (...)/download?file=XXX.jar
```

Note that the URL is not encoded in the error message. This creates the strange situation where copying the exact location Gradle (supposedly) looked at into a browser downloads the jar just fine...

### Context

I need to download a dependency from a slightly archaic (non-maven) download site.
[This answer](https://stackoverflow.com/a/34327202/) on StackOverflow lead me to the Ivy-workaround.

### Steps to Reproduce 
[Example project](https://github.com/HoldYourWaffle/gradle-21297-redirecting-ivy-dependencies)

This project contains 3 modules:
- `library` containing some beautiful re-usable code
- `repository` which hosts the jar built from `library` at the URL format described above
- `consumer` which tries to pull a dependency on `library` from the `repository` server, but fails with the above error

Note that `repository:run` must be running for `consumer` to even attempt building.

### Your Environment
Build scan URL: https://scans.gradle.com/s/c3wbqfswcrlmi

**Comment by reinsch82** [comment]
Sorry for the late reply.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
We may have addressed this recently.  Could you try with the latest Gradle release (8.11)?

**Comment by wjglerum** [comment]
@big-guy & @reinsch82 I can confirm this is still an issue on recent Gradle versions, for example on version 9.3.1 but also on version 8.11 that you reference earlier.

Any chance this can be picked up again?

**Comment by wjglerum** [comment]
We tried to use this for example with the Bitbucket REST API to get a repository as a zip archive at a given version. See https://developer.atlassian.com/server/bitbucket/rest/v815/api-group-repository/#api-api-latest-projects-projectkey-repos-repositoryslug-archive-get

I also tried a source dependency instead, but it seems like that is extremely limited as you can't do a sparse checkout or specify a git sha.
