### ISSUE TITLE
User guide makes confusing claims about plugin dependency isolation

### ISSUE THREAD

**Issue by rschmitt** [gradle/gradle#21293]
[This section](https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations) of the user guide makes it sound like there is some kind of classloader/dependency isolation between plugins when they are loaded using the `plugins` DSL block:

> This way of adding plugins to a project is much more than a more convenient syntax. The plugins DSL is processed in a way which allows Gradle to determine the plugins in use very early and very quickly. This allows Gradle to do smart things such as [...] allow[ing] different plugins to use different versions of dependencies.

I [mentioned this](https://gradle-community.slack.com/archives/CA745PZHN/p1658187858194079?thread_ts=1657944560.799889&cid=CA745PZHN) on the Gradle Community Slack workspace and nobody seemed to know what it was referring to, so this claim should evidently be clarified or removed.

**Comment by eskatos** [comment]
Done in https://github.com/gradle/gradle/pull/21448 for Gradle 7.6
