### ISSUE TITLE
dependencySubstitution not working for included projects

### ISSUE THREAD

**Issue by martin-braun** [gradle/gradle#21303]
### Expected Behavior
Gradle should be able to include a project that leverages a dependency substitution to include a local build module without failing to resolve the local module.

### Current Behavior
A project that includes a build / module using dependency substitution manages to resolve such local dependency without any error. However, if the project will be included in another project the dependency substitution of the included project will fail with the message: 

> Failed to resolve: com.example:lib

### Context

I build an app using Capacitor. I also build a Capacitor plugin. I also build a gradle module (java lib). Now I try to use dependency substitution to include my gradle module in my Capacitor plugin. Works well, no errors at this point. Now in my app project I included my Capacitor plugin. Capacitor includes its plugins using include project directives. This fails, because it cannot resolve my gradle module (java lib).

### Steps to Reproduce 

First create an empty gradle project / lib (let's call it "example-module", package name: com.example). I followed this tutorial: https://docs.gradle.org/current/samples/sample_building_java_libraries.html

Now build a second project (let's call it "example-project") and include the build of the first project:

*settings.gradle*
```groovy
includeBuild("/Users/user/Projects/example-module") {
    dependencySubstitution {
        substitute(module("com.example:lib"))
                .with(project(":lib"))
    }
}
```

*build.gradle*
```groovy
dependencies {
    implementation 'com.example:lib'
	...
}
```

This works. Gradle Sync does not complain. 

Now create a third project and include the second project like so: 

*settings.gradle*
```groovy
include ':my-plugin'
project(':my-plugin').projectDir = new File('/Users/user/Projects/example-project')
```

Gradle sync on the third project will fail with: 

> Failed to resolve: com.example:lib

### Your Environment
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.1.1 (Oracle Corporation 18.0.1.1+2-6)
OS:           Mac OS X 12.4 x86_64
```

Capacitor 2

**Comment by martin-braun** [comment]
Luckily I found a work-around. I can simply put

```groovy
includeBuild("/Users/user/Projects/example-module") {
    dependencySubstitution {
        substitute(module("com.example:lib"))
                .with(project(":lib"))
    }
}
```

in the settings.gradle of the primary project that includes the 2nd project that leverages the dependency substitution. This should not be necessary, because it introduces redundancy. This should be fixed, it wasted some time on my end.

**Comment by eskatos** [comment]
Hi,
Sorry that you're having trouble with Gradle!

Could you please consider sharing a complete reproducer for this issue?

A complete reproducer can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

**Comment by jbartok** [comment]
By just including the project and not the build, you are effectively ignoring the `settings.gradle` of the `example-project`. Using an included build should solve your problem.
