### ISSUE TITLE
gradle build failed when using annotationProcessor but intellij idea build and run successfully

### ISSUE THREAD

**Issue by brainy0214** [gradle/gradle#21310]
```
Cause: superclass access check failed: class org.example.processor.SetterProcessor$1 (in unnamed module @0x1acf0bc3) cannot access class com.sun.tools.javac.tree.TreeTranslator (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x1acf0bc3
```

When I use the compilation and operation of intellij idea, it can run normally. This error occurs when I switch to gradle

- **processor** info

 _module-info.java_

```
module annottation.processor.demo.processor {
    requires jdk.compiler;
    requires java.compiler;
    requires annottation.processor.demo.annotation;

    exports org.example.processor;
}
```
_build.gradle_
```
dependencies {
    implementation project(":annotation")
}

tasks.withType(JavaCompile) {
    options.compilerArgs = [
            "--add-exports=jdk.compiler/com.sun.tools.javac.api=annottation.processor.demo.processor",
            "--add-exports=jdk.compiler/com.sun.tools.javac.tree=annottation.processor.demo.processor",
            "--add-exports=jdk.compiler/com.sun.tools.javac.util=annottation.processor.demo.processor",
            "--add-exports=jdk.compiler/com.sun.tools.javac.code=annottation.processor.demo.processor",
            "--add-exports=jdk.compiler/com.sun.tools.javac.processing=annottation.processor.demo.processor",
    ]
}
```

- **demo** info

_build.gradle_
```
dependencies {
    implementation project(":annotation")
    annotationProcessor project(":processor")
}
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.2 (Oracle Corporation 17.0.2+8-LTS-86)
OS:           Windows 10 10.0 amd64

**Comment by donat** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by abelom** [comment]
I've noticed that cause mentions ``to _unnamed_ module`` while --add-exports use explicit module name not the ALL-UNNAMED

Any chance that ALL-UNNAMED would work better?

On the other hand you are trying to name your module wonder why is error message referring as unnamed?

**Comment by donat** [comment]
Closing as stale. If there's a stable reproducer, we'll reopen the issue.

**Comment by abelom** [comment]
@donat [I believe that](https://github.com/gradle/gradle/issues/22065) is potentially a duplicate and there is a sample project over there
