### ISSUE TITLE
How can setting Global template build.properties

### ISSUE THREAD

**Issue by TarryHoo** [gradle/gradle#2132]
Hey man
    By what way you can modify a new gradle project generated by build.properties?

I want to create a gradle when the automatic generation of some of the tasks I have always needed so I do not have to go somewhere else copy and paste.Is there any place to let me do that?

**Comment by bmuschko** [comment]
I am not sure I understand the question. Are you asking about a way to provide a custom template for project generation? If you want to share tasks then I'd suggest to write a plugin which can be shared by projects.

**Comment by TarryHoo** [comment]
@bmuschko hmm, Simply put it when a gradle project is created, its build.properties file will be introduced by Jar, which should have a template to do this thing. I want to modify this template. Let it add some more tasks.
For example, maven configuration.
Whenever I create a project, i need to add a task using mavneLocal (). It should be an existing Task, do not need my own hand to write a task,if i have been waiting for this is not it?
