### ISSUE TITLE
Issue when upgraded to Gradle 7.5

### ISSUE THREAD

**Issue by bizzi-vinhvo** [gradle/gradle#21326]
### Expected Behavior

Gradle build still work

### Current Behavior

Run with `gradle build`

```
> Task :model:jandex FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/internal/classpath/Instrumented
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.indexFile(JandexMain.java:172)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.visitFile(JandexMain.java:160)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain$ClassFileVisitor.visitFile(JandexMain.java:147)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.execute(JandexMain.java:98)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.run(JandexMain.java:124)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexMain.main(JandexMain.java:111)
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.classpath.Instrumented
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 8 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':model:jandex'.
> Process 'command '/Users/myuser/.sdkman/candidates/java/17.0.3-tem/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
13 actionable tasks: 4 executed, 9 up-to-date

```

### Context

build.gradle

```
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id 'org.kordamp.gradle.jandex' version "${jandexVersion}"
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-smallrye-graphql'
    implementation("io.quarkus:quarkus-hibernate-validator")
    implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVerion}"
    implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVerion}"
}

```

gradle.properties

```
jandexVersion=0.12.0
```

### Your Environment

Gradle: 7.5
Java 17.0.3 [Eclipse Temurin](https://projects.eclipse.org/projects/adoptium.temurin)
Quarkus: 2.10.3.Final

**Comment by eskatos** [comment]
Hi @bizzi-vinhvo,

Thank you for your report.

Unfortunately I'm not able to reproduce with the provided information.

A reproducer project can really help us track down and fix your problem quicker. 
We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by re-thc** [comment]
Issue exists with the Jandex gradle plugin, not gradle itself.

**Comment by bizzi-vinhvo** [comment]
> 

Nope, still working with Gradle version 7.4.x

**Comment by bizzi-vinhvo** [comment]
> Issue exists with the Jandex gradle plugin, not gradle itself.

Nope, still working with Gradle version 7.4.x

**Comment by re-thc** [comment]
> > Issue exists with the Jandex gradle plugin, not gradle itself.
> 
> Nope, still working with Gradle version 7.4.x

See this [issue](https://github.com/kordamp/jandex-gradle-plugin/issues/18).

**Comment by bizzi-vinhvo** [comment]
> > > Issue exists with the Jandex gradle plugin, not gradle itself.
> > 
> > 
> > Nope, still working with Gradle version 7.4.x
> 
> See this [issue](https://github.com/kordamp/jandex-gradle-plugin/issues/18).

Thanks @re-thc, but some changes happened on Gradle make jandex fail. Need to be checked by both.

**Comment by bizzi-vinhvo** [comment]
> > > Issue exists with the Jandex gradle plugin, not gradle itself.
> > 
> > 
> > Nope, still working with Gradle version 7.4.x
> 
> See this [issue](https://github.com/kordamp/jandex-gradle-plugin/issues/18).

Thanks @re-thc, but some changes happened on Gradle make jandex fail. Need to be checked by both.

**Comment by re-thc** [comment]
> > > > Issue exists with the Jandex gradle plugin, not gradle itself.
> > > 
> > > 
> > > Nope, still working with Gradle version 7.4.x
> > 
> > 
> > See this [issue](https://github.com/kordamp/jandex-gradle-plugin/issues/18).
> 
> Thanks @re-thc, but some changes happened on Gradle make jandex fail. Need to be checked by both.

The plugin strictly needs to use new APIs as the old 1s in use are no longer supported. Don't see why it's a Gradle issue.

**Comment by mlopatkin** [comment]
As mentioned in the linked jandex-plugin's issue, it's the problem with the classpath construction for the JavaExec tasks that eventually invokes `jandex`. The plugin [tries to reuse the buildscript classpath](https://github.com/kordamp/jandex-gradle-plugin/blob/9199c2e02a210bca6095159a488a87062ad2221f/src/main/groovy/org/kordamp/gradle/plugin/jandex/tasks/JandexTask.groovy#L139) to construct the classpath for the task. However, JARs on the buildscript classpath are not the originals but instrumented by Gradle to do some internal stuff (e.g. trace configuration inputs for the configuration cache in this particular case), and the resulting bytecode references some Gradle-internal classes. In 7.5 we've added the instrumentation of the `FileInputStream` constructors, and the plugin code happens to use one, that's why it was working before but stopped in 7.5.

Reusing the buildscript classpath's JARs was never really supported; the recommended solution is to use a configuration to declare a dependency to the original JAR and resolve it.
