### ISSUE TITLE
Cpp and Swift plugin classes use `Optional.orElse` inefficiently

### ISSUE THREAD

**Issue by Marcono1234** [gradle/gradle#21334]
### Current Behavior
It looks like several Cpp and Swift plugin classes use Java's `Optional.orElse` inefficiently, see code snippets below. This causes all the alternative values to be computed, even if they are not needed. Maybe they should use `Optional.orElseGet` to only evaluate the alternative value if it is really needed.

- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppApplicationPlugin.java#L87-L92
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppLibraryPlugin.java#L102-L105
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/testing-native/src/main/java/org/gradle/nativeplatform/test/cpp/plugins/CppUnitTestPlugin.java#L114-L116
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftApplicationPlugin.java#L91-L96
- https://github.com/gradle/gradle/blob/0a73d542dde7e7ed101f7318f3097bdcaaa0426b/subprojects/language-native/src/main/java/org/gradle/language/swift/plugins/SwiftLibraryPlugin.java#L103-L106

I have not measured the performance difference, but just noticed this (probably) ineffecient usage of `Optional`; hopefully this bug report is useful nonetheless.

**Comment by donat** [comment]
Would you be interested in providing a pull request?

**Comment by Marcono1234** [comment]
Have created #21343
