### ISSUE TITLE
CheckStyle fails because it has no javaLauncher configured

### ISSUE THREAD

**Issue by musketyr** [gradle/gradle#21353]
We are having a custom `CheckStyle` task to provide aggregated results from the subprojects. After upgrading to Gradle 7.5 it fails with following reason.

```
* What went wrong:
A problem was found with the configuration of task ':aggregateCheckstyle' (type 'Checkstyle').
  - Type 'org.gradle.api.plugins.quality.Checkstyle' property 'javaLauncher' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'javaLauncher'.
      2. Mark property 'javaLauncher' as optional.
    
    Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#value_not_set for more details about this problem.
```

### Expected Behavior

The Java Launcher is optional and if not configured then the task falls back to the original behavior using `CheckstyleInvoker.invoke(this)`.

### Current Behavior
When the `javaLauncher` is not optional then the root project for our aggregated Checkstyle project would have to apply the Java plugin to get access to the Toolchains and Launcher which does not make any sense.

### Context
The behavior is broken in Gradle 7.5

### Steps to Reproduce 
Clone https://github.com/musketyr/aggregate-checkstyle-issue and run `AggregateCheckstyleReportsPluginSpec` test.

### Your Environment

Build scan URL: https://scans.gradle.com/s/4vfibe753v3fs

**Comment by asodja** [comment]
Thanks for the report. It seems we have to handle case where Checkstyle plugin is not applied one way or another. 

Nevertheless, I have a question: what is the reason you don't apply a Checkstyle plugin to root? E.g. a change like this makes your tests pass:

```
--- a/plugins/aggregate-checkstyle-reports/src/main/java/com/agorapulse/gradle/root/checkstyle/AggregateCheckstyleReportsPlugin.java
+++ b/plugins/aggregate-checkstyle-reports/src/main/java/com/agorapulse/gradle/root/checkstyle/AggregateCheckstyleReportsPlugin.java
@@ -37,6 +37,7 @@ public class AggregateCheckstyleReportsPlugin implements Plugin<Project> {
 
     @Override
     public void apply(Project rootProject) {
+        rootProject.getPluginManager().apply(CheckstylePlugin.class);
         CheckstyleExtension rootExt = createExtension(rootProject);
 
         rootProject.getTasks().register(AGGREGATE_CHECKSTYLE_TASK_NAME, Checkstyle.class, new Action<Checkstyle>() {
@@ -130,7 +131,7 @@ public class AggregateCheckstyleReportsPlugin implements Plugin<Project> {
     }
 
     private static CheckstyleExtension createExtension(Project project) {
-        CheckstyleExtension extension = project.getExtensions().create("checkstyle", CheckstyleExtension.class, project);
+        CheckstyleExtension extension = project.getExtensions().getByType(CheckstyleExtension.class);
         extension.setToolVersion(DEFAULT_CHECKSTYLE_VERSION);
 
         File configFile = getConfigFile(project);
```

**Comment by musketyr** [comment]
Thank you, Anže! Sincerely, I can't remember. Maybe I didn't want to apply the plugin to the root project because it itself contains no sources. I will try with your suggestions.
