### ISSUE TITLE
Share more information (licensing, repo url) about the Kotlin DSL Plugin both on the Plugin Page and in the published Maven POM

### ISSUE THREAD

**Issue by akiraly** [gradle/gradle#21355]
I am trying to use the Kotlin DSL Plugin for a buildSrc project (in an enterprise setting) but I hit a blocker because of missing meta data (can't find the license of this plugin).
Apparently the Kotlin DSL Plugin is not part of the Gradle distribution but a separate plugin. To be able to use a new plugin we would need to verify the license - but I can't find that anywhere.

### Expected Behavior
- The plugin page ( https://plugins.gradle.org/plugin/org.gradle.kotlin.kotlin-dsl ) should either have a different link (instead of https://github.com/gradle/kotlin-dsl ) or that link should point to the actual repo instead of redirecting to a different, archived repo
- The published maven POM-s (for both `org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin` and `org.gradle.kotlin:gradle-kotlin-dsl-plugins`) should have at least the licensing and the organization (name, url) section filled out to help automated onboarding processes

### Current Behavior
- The plugin page ( https://plugins.gradle.org/plugin/org.gradle.kotlin.kotlin-dsl ) only has an url: https://github.com/gradle/kotlin-dsl but that url redirects to https://github.com/gradle/kotlin-dsl-samples which is an archived repository. So either the https://github.com/gradle/kotlin-dsl link is incorrect or maybe the repo is not public.
- I checked the contents of the published maven POM-s and jar files but I couldn't find any licensing information there either.

**Comment by eskatos** [comment]
Hi @akiraly,

Sorry that you're having trouble with Gradle!

The `kotlin-dsl` plugin is not shipped with the Gradle distribution but it is built alongside it.
You can find the sources here https://github.com/gradle/gradle/tree/master/subprojects/kotlin-dsl-plugins
It's license is the same as the Gradle Build Tool: the [Apache-2.0 license](https://github.com/gradle/gradle/blob/master/LICENSE).

That being said, you are correct that the above should be trivial to find. Let's use this issue to fix those problems.

**Comment by akiraly** [comment]
Hi @eskatos,

Could you please check #23499?

**Comment by eskatos** [comment]
Thank you for your contribution !

This was fixed in
* https://github.com/gradle/gradle/pull/23499

This will ship with Gradle 8.1

**Comment by akiraly** [comment]
Great, thanks!
