### ISSUE TITLE
Kotlin Gradle plugin does not emit Java Toolchain usage events when loaded from configuration cache

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#21368]
This is most likely happening due to Kotlin plugin extracting values from a `JavaLauncher` and storing them in a custom data structure.

https://github.com/JetBrains/kotlin/blob/ca193a89d2d0408d4720a5dceff004af9f539244/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/tasks/DefaultKotlinJavaToolchain.kt#L206-L228

Once this is adjusted on the Kotlin plugin side, a corresponding test should be fixed in `JavaToolchainBuildOperationsIntegrationTest`.

**Comment by wolfs** [comment]
This may be solved by #21314
