### ISSUE TITLE
Findbugs plugin: passes all source files to "-sourcepath <sourcedirs>" parameter

### ISSUE THREAD

**Issue by cal101** [gradle/gradle#2138]
### Expected Behavior
The findbugs plugin should pass only the directories containing the source code instead of all files.

### Current Behavior
The findbugs plugin as of gradle 3.5 passes the whole source set to the "-sourcepath" parameter.
For big projects findbugs takes minutes to just pass that mess before even starting to analyze.

### Context
Instead of taking 6 minutes for the analysis it takes ~~18~~ 40 minutes.

### Workaround
```
findbugsMain {
...
    extraArgs = [ '-sourcepath', 'src/main/java']
}

tasks.withType(FindBugs) {
    // Bug workaround: per default the findbugs plugin passes ALL source files 
    // per command line to the "-sourcepath" parameter that expects just a few 
    // src DIRECTORIES.
    source = fileTree("src/main/NOTEXISTS")
}
```

### Fixing
I can fix this issue myself and provide a pull request if someone familiar with gradle philosophy 
in general and plugin behavior tells me
- how one should transform source sets to a minimal set of directories or 
- is it ok to just use the top level srcDir directories 
- how to access the top level src dirs from the sourcesets.

The real input for findbugs is the list of classes, not the source dir so I expect it to be OK to just list the top level src dirs.

**Comment by bmuschko** [comment]
> Instead of taking 6 minutes for the analysis it takes 40 minutes.

Are these time measurement you provided a comparison of the execution time between Gradle 3.4 and 3.5?

**Comment by cal101** [comment]
No. It's the diference between using the workaround and using findbugs plugin out of the box.

**Comment by bmuschko** [comment]
OK, I am just trying to confirm that this is not a regression that happened in 3.5 specifically.

**Comment by jjohannes** [comment]
The _Findbugs_ plugin is removed in Gradle 6.0.

Please use an alternative plugins like https://plugins.gradle.org/plugin/com.github.spotbugs
