### ISSUE TITLE
Update Zinc used by Scala plugin to 1.7.1

### ISSUE THREAD

**Issue by ijuma** [gradle/gradle#21392]
Zinc 1.7.1 includes a number of bug fixes including under-compilation when Java annotation changes.

Release notes:
* https://github.com/sbt/zinc/releases/tag/v1.7.0
* https://github.com/sbt/zinc/releases/tag/v1.7.1

Diff: https://github.com/sbt/zinc/compare/v1.6.1...v1.7.1

**Comment by gabrieljones** [comment]
We're now up to [1.8.0](https://github.com/sbt/zinc/releases)

**Comment by ljacomet** [comment]
We have a PR to update to the latest - Zinc 1.9.3
* #25887 

Any reason to be cautious?
