### ISSUE TITLE
Scala compilation fails with 'rt.jar (class sbt.internal.inc.DummyVirtualFile) is not supported'

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#21400]
The upgrade to the Zinc compiler introduced this failure in Scala projects internally:

https://github.com/gradle/gradle/commit/597d8133a18171451a8295cac6b1f726584c2fda#diff-08c249a9aa06c1271f91ea8a6f37375c76844b9261f2d1a6bf632594fd8ff1fd

Reported also against sbt, scala-maven-plugin and Zinc itself:

- https://github.com/sbt/sbt/pull/5522
- https://github.com/davidB/scala-maven-plugin/issues/615
- https://github.com/sbt/zinc/issues/1102

### Your Environment
Gradle 7.5

**Comment by big-guy** [comment]
Hey @DanielThomas - to reproduce this, do we need to use a particular version of Scala + Zinc + JDK?

**Comment by DanielThomas** [comment]
Sorry @big-guy, was hoping to have better steps to reproduce by the time you came to triage but we could no longer reproduce on the machine having the problem. You might still want to make a defensive change like sbt did to avoid the problem, because there's not a fix in zinc yet.

Scala 2.11, Zinc 1.6.1, JDK 1.8.0_312.

**Comment by ljacomet** [comment]
Given the links and the issue, we should apply a workaround similar to what `sbt` and `scala-maven-plugin` have been doing.

**Comment by ljacomet** [comment]
Fix has been merged
