### ISSUE TITLE
Can GradleBuild task prefix their logging?

### ISSUE THREAD

**Issue by nik9000** [gradle/gradle#2141]
### Expected Behavior
Can GradleBuild tasks prefix the tasks they log somehow? It'd be lovely if they prefixed with the path to the GradleBuild task. This is especially nice when you have many GradleBuild tasks and/or when the GradleBuild subtasks invoke very similar looking builds.

### Current Behavior
Right now tasks of the type GradleBuild log whatever that gradle build logs prefixed by the name of directory in which the GradleBuild is rooted.

### Example
Right now it looks like:
```
...
:distribution:bwc:buildBwcVersion  <--- This is a GradleBuild task.
:checkout-5.x:buildSrc:compileJava
:checkout-5.x:buildSrc:compileGroovy
...
```

It'd be nice if it looked like this:
```
...
:distribution:bwc:buildBwcVersion  <--- This is a GradleBuild task.
:distribution:bwc:buildBwcVersion:buildSrc:compileJava
:distribution:bwc:buildBwcVersion:buildSrc:compileGroovy
...
```

or:
```
...
:distribution:bwc:buildBwcVersion  <--- This is a GradleBuild task.
:distribution:bwc:buildBwcVersion:checkout-5.x:buildSrc:compileJava
:distribution:bwc:buildBwcVersion:checkout-5.x:buildSrc:compileGroovy
...
```

**Comment by bmuschko** [comment]
In most cases I'd try to stay away from `GradleBuild`. I can say from experience that it sometimes caused side-effects that are hard to diagnose. What's the use case for having so many external builds?

> Right now tasks of the type GradleBuild log whatever that gradle build logs prefixed by the name of directory in which the GradleBuild is rooted.

The alternative is to put the build file into a separate directory and provide a settings file that sets the desired project name.

**Comment by nik9000** [comment]
We use GradleBuild to build different branches of our project for backwards
compatibility testing. We use other tasks to set up a git checkout of those
old branches. We do backwards compatibility testing against released
artifacts where possible, but for unreleased versions we use this because
it is less error prone then waiting on snapshot builds from ci.

We could look into changing the name in the build file  some other way.
It'd certainly be cleaner for us if it were supported. We've had trouble in
the past because we did things to our build that were unsupported hacks and
gradle changed out from under us. Totally fair, but it does push me to
wanting to stay with supported configurations.

**Comment by bmuschko** [comment]
> We use GradleBuild to build different branches of our project for backwards
compatibility testing.

In those cases I'd suggest you use TestKit or the Tooling API.

**Comment by nik9000** [comment]
> TestKit

That looks like it is for testing the gradle build. We're testing that the artifacts produced by the current branch are backwards compatible with the artifacts produced by the HEAD of a previous branch. The docs for TestKit don't make it look like it is for that. It is neat to know about and might be useful for other things though.

> Tooling API

This looks like it is for embedding gradle into other software. If we tried to use this I think we'd end up reimplementing GradleBuild which seems like a mistake.

**Comment by bmuschko** [comment]
> That looks like it is for testing the gradle build. We're testing that the artifacts produced by the current branch are backwards compatible with the artifacts produced by the HEAD of a previous branch.

You can point TestKit to an existing build script and run a build against it. _What_ you verify is up to you.

> This looks like it is for embedding gradle into other software.

You basically just run Gradle by invoking a programmatic API. Embedded Gradle into an IDE is just one example of how the tooling API can be used.

**Comment by bmuschko** [comment]
I'd suggest you try out one of the proposed approaches. I don't see us investing a lot into `GradleBuild` in the near future. Feel free to provide a pull request if you'd like but I strongly believe that the proposed solutions are better options.
