### ISSUE TITLE
--property option is not recognized when running ./gradlew <project>:properties --property <myProp>

### ISSUE THREAD

**Issue by rasaha91** [gradle/gradle#21416]
Per the [documentation](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:listing_properties), when running `./gradlew <project>:properties`, there is a way to query a specific property through the `--property` option.

### Expected Behavior

Using the `--property` option should work and you should be able to query the value of the property.

### Current Behavior

We hit an unknown command-line option error:

* What went wrong:
Problem configuring task :ReactAndroid:properties from command line.
> Unknown command-line option '--property'.

### Context

We need to query the value of a property for use outside the gradle build and would like to do it via the documented command line option. We have a work around, but it would be ideal if the gradle command worked.

### Steps to Reproduce 

1. Clone facebook/react-native - https://github.com/facebook/react-native
2. In the cloned directory, run `./gradlew ReactAndroid:properties --property libsDirName`
3. Observe the aforementioned failure

### Your Environment

Output of `./gradlew --version`:

Gradle 7.3.3

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (Ubuntu 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OS:           Linux 5.10.102.1-microsoft-standard-WSL2 amd64

**Comment by jbartok** [comment]
This is a [feature introduced in Gradle 7.5](https://docs.gradle.org/7.5/release-notes.html), so you will need to use that version in order to have it work.
