### ISSUE TITLE
have gradlew lazily create gradle-wrapper.jar if missing

### ISSUE THREAD

**Issue by pjfanning** [gradle/gradle#21414]
### Expected Behavior
./gradlew should work even if gradle/wrapper/gradle-wrapper.jar is missing

### Current Behavior
./gradlew only works if gradle/wrapper/gradle-wrapper.jar exists

### Context
OSSF Scorecard and other initiatives to improve the security of OSS and related CI builds -- OSSF Scorecard demerits projects if they have checked in binary artifacts. -- [Example](https://github.com/pjfanning/excel-streaming-reader/security/code-scanning/1)
Gradlew is very useful for encouraging uniformity in build experience.
It would be great if gradlew could download the gradle-wrapper.jar if it is not checked in (eg if git is configured to ignore the file).

As an example, mvnw does not need its equivalent wrapper jar to be present ([docs](https://maven.apache.org/wrapper/#usage-without-binary-jar)).

Apologies if a similar issue has been raised, I did look over issues for the last few months.

**Comment by vlsi** [comment]
I guess this issue duplicates https://github.com/gradle/gradle/issues/11816

**Comment by pjfanning** [comment]
Thanks @vlsi - I'll close this
