### ISSUE TITLE
 “-XX:MaxHeapSize” not work in jvmArgs, but can work int test blcok, it is a bug or intentional ？

### ISSUE THREAD

**Issue by lfygh** [gradle/gradle#21420]
### Expected Behavior

 “-XX:MaxHeapSize” work in jvmArgs

### Current Behavior
```
build.gradle
test {
    jvmArgs(
            "-XX:+PrintCommandLineFlags",
            "-XX:MaxHeapSize=8G"
    )
}
```
run app and out put:

> -XX:ConcGCThreads=2 -XX:G1ConcRefinementThreads=8 -XX:GCDrainStackTargetSize=64 -XX:InitialHeapSize=268435456 -XX:MarkStackSize=4194304 **-XX:MaxHeapSize=536870912** -XX:MinHeapSize=6815736 -XX:+PrintCommandLineFlags -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC 

the MaxHeapSize config in jvmArgs not work? but  the `"-XX:+PrintCommandLineFlags"` jvmArgs is effected.

**and then move MaxHeapSize to test block**
```
build.gradle
test {
   jvmArgs(
           "-XX:+PrintCommandLineFlags",
   )
}
maxHeapSize = "8G"
```
run app and output
> -XX:ConcGCThreads=2 -XX:G1ConcRefinementThreads=8 -XX:GCDrainStackTargetSize=64 -XX:InitialHeapSize=268435456 -XX:MarkStackSize=4194304 **-XX:MaxHeapSize=8589934592** -XX:MinHeapSize=6815736 -XX:+PrintCommandLineFlags -XX:ReservedCodeCacheSize=251658240 -XX:+SegmentedCodeCache -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC 

ok, it‘s work。 why it does not work when using “-XX:MaxHeapSize=8G” in jvmArgs? it is a bug or intentional？

### Environment
```
$ gradle --version

------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4 (Azul Systems, Inc. 17.0.4+8-LTS)
OS:           Mac OS X 11.4 aarch64
```

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

@gradle/bt-jvm Please decide if it's an expected behavior that should be addressed in the docs, or if it's a bug that should be fixed.

**Comment by big-guy** [comment]
I think if you used `-Xmx` instead of `-XX:MaxHeapSize`, this would have worked the way you expected.  I would prefer to use the modeled property (`maxHeapSize`) since Gradle generates the correct `-Xmx` command-line from that.
