### ISSUE TITLE
Support getting first-order plugins

### ISSUE THREAD

**Issue by Meijuh** [gradle/gradle#21441]
### Expected Behavior
I would like to see the `PluginManager` having the feature to give me all "first-order" plugins. I.e. the plugins that were applied by a project itself, and not by external plugins.

### Current Behavior
Currently the `PluginManager` only provides me the option to get all plugins: first-order (those applied by the project itself) and higher-order (those applied by external plugins).

### Context
I would like to enforce conventions (through the `groovy-gradle-plugin`) whenever I have specified conventions for a particular Gradle plugin. In other words, I have a `groovy-gradle-plugin`, called `java-conventions`. I would like to have a `root-conventions` plugin that checks for each (sub) project whether `java-conventions` is applied if Gradle's `java` plugin is applied. Currently I can not write this check because external plugins (like `groovy-gradle-plugin`, if I am correct) also apply the `java` plugin. However, I do not want to enforce my `java-conventions` on projects that only apply `groovy-gradle-plugin`. To give an example, I would like my `root-conventions` to look as follows.
```groovy
// root-conventions.gradle
allprojects {
    if (getPluginManager().hasPlugin('java', PluginOrder.FIRST) && !getPluginManager().hasPlugin('java-conventions')) {
        throw new InvalidUserCodeException("Project $name applies plugin 'java', hence must also apply 'java-conventions'")
    }
}
```
Plugin `java-conventions` looks like:
```groovy
// java-conventions.gradle
plugins {
    id 'java'
}
if (!rootProject.getPluginManager().hasPlugin('root-conventions')) {
    throw new InvalidUserCodeException("Root project $rootProject.name must apply 'root-conventions'")
}

// configure PMD
// configure SpotBug
// etc
```
Note that we could also have `PluginOrder.HIGHER` which is used to denote plugins also applied by external plugins. Furthermore, the default behavior of `PluginManager#hasPlugin(name: String)` should be to call `PluginManager#hasPlugin(name, PluginOrder.HIGHER)` to maintain backwards compatibility.

Now in my project, if I were to have the following subproject:
```groovy
// /gradle-plugin/build.gradle
plugins {
    id 'groovy-gradle-plugin`
}
```
And the following subproject:
```groovy
// /app/build.gradle
plugins {
   id 'java-conventions'
}
```
And the following root project:
```groovy
// /build.gradle
plugins {
    id 'root-conventions'
}
```
Then my build will incorrectly fail (for project `gradle-plugin`) if I simply call `PluginManager#hasPlugin('java')` in `root-conventions` (because `groovy-gradle-plugin` applies the `java` plugin).

Note that the purpose of enforcing these conventions is to detect a case that does not apply `java-conventions` like:
```groovy
// /another-app/build.gradle
plugins {
    id 'java'
}
```
Maybe Gradle already supports this behavior, but I could not find it.

**Comment by ov7a** [comment]
Sorry for the late reply.

We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

***

The main question here is why you don't want to enforce it in some cases.

> However, I do not want to enforce my java-conventions on projects that only apply groovy-gradle-plugin

Plugins are basically jars on the build script classpath. If the plugin is applied transitively, then there's no difference from the case when it was applied directly: all features from the plugin are available to a user in the same way. So, in your example, users can use java features and write java code when `groovy-gradle-plugin` is applied. This means that the conventions should also be applied.

For now, there is no solid reason to differentiate between directly applied plugins vs. transitively applied ones.
