### ISSUE TITLE
Deprecate and remove :model task

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#21454]
The model task fails if tried with configuration cache enabled.

```
$ gradle model --configuration-cache
```

```
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: model

> Task :model

------------------------------------------------------------
Root project 'hello-prj'
------------------------------------------------------------

project path: :
+ tasks
      | Type:           org.gradle.model.ModelMap<org.gradle.api.Task>
      | Creator:        Project.<init>.tasks()
...
<regular task output>
...

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Task `:model` of type `org.gradle.api.reporting.model.ModelReport`: invocation of 'Task.project' at execution time is unsupported.

```

**Comment by abstratt** [comment]
Might use an approach similar to #21419. However, #15023 suggests we may dropping this task altogether currently marked for deprecation).

**Comment by bamboo** [comment]
Software model is out of scope for the configuration cache.

**Comment by abstratt** [comment]
> Software model is out of scope for the configuration cache.

Just

`notCompatibleWithConfigurationCache("Software model is out of scope for the configuration cache");`

then?

**Comment by bamboo** [comment]
Almost but not quite due to `notCompatibleWithConfigurationCache` semantics.

**Comment by abstratt** [comment]
Which semantics, Rodrigo? Not failing a build in case of CC problems? Or preventing the cache entry from being saved? The latter would be what we were after, the former not so much, but maybe harmless?

**Comment by bamboo** [comment]
I meant problems would still be reported with `notCompatibleWithConfigurationCache` and that's undesirable.
