### ISSUE TITLE
Android project fails to build with 7.5 due to "Incompatible because this component declares a component, as well as attribute 'artifactType' with value 'orbit' and the consumer needed a component, as well as attribute 'artifactType' with value 'android-classes-jar'"

### ISSUE THREAD

**Issue by bubbleguuum** [gradle/gradle#21452]
```
-----------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.16 (Oracle Corporation 11.0.16+8-suse-1.1-x8664)
OS:           Linux 5.18.12-1-default amd64
```

A large Android project that used to build fine with 7.4.2 fails to build with 7.5 (and latest gradle master as of the date of this report), resulting in:

```
> Could not resolve all files for configuration '<edited>'.
   > No variants of org.eclipse.jetty.orbit:javax.servlet:2.5.0.v201103041518 match the consumer attributes:
       - org.eclipse.jetty.orbit:javax.servlet:2.5.0.v201103041518 configuration runtime declares a runtime of a component:
           - Incompatible because this component declares a component, as well as attribute 'artifactType' with value 'orbit' and the consumer needed a component, as well as attribute 'artifactType' with value 'android-classes-jar'
           - Other compatible attributes:
               - Doesn't say anything about asm-transformed-variant (required 'NONE')
               - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.2.1')
               - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
               - Doesn't say anything about com.android.build.api.attributes.ProductFlavor:mode (required 'bubbleupnp')
               - Doesn't say anything about dexing-enable-desugaring (required 'true')
               - Doesn't say anything about dexing-is-debuggable (required 'true')
               - Doesn't say anything about dexing-min-sdk (required '21')
               - Doesn't say anything about its target Java environment (preferred optimized for Android)

```

I believe this is caused by `org.eclipse.jetty.orbit:javax.servlet:2.5.0.v201103041518` using `<packaging>orbit</packaging>` in its [pom](https://repo1.maven.org/maven2/org/eclipse/jetty/orbit/javax.servlet/2.5.0.v201103041518/javax.servlet-2.5.0.v201103041518.pom)

This used to work, so shall it be considered a regression ? If it is not, how can it be worked-around so it builds ?

**Comment by bubbleguuum** [comment]
Any news on this ? It also happens on v7.5.1. It worked fine on v7.4.2 and below.

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.

**Comment by bubbleguuum** [comment]
I tried to make a simple (Android) project to reproduce this issue but failed.
It only happens in my rather complicated Android app.

It is caused by the `org.eclipse.jetty.orbit:javax.servlet:2.5.0.v201103041518` dependency of my project having `<packaging>orbit</packaging>` instead of the more usual `jar` packaging.
In Gradle 7.4.2 it does not cause a problem, but it does starting with 7.5.0 with the error I reported.

`org.eclipse.jetty.orbit:javax.servlet` is pulled as a dependency of `org.eclipse.jetty:jetty-server:7.6.21.v20160908` (old version of Jetty I'm stuck with) and I tried to override the packaging type with snippet below, but it has no effect:

```
  implementation (group:'org.eclipse.jetty.orbit', name:'javax.servlet') {
        artifact {
            name = 'javax.servlet'
            type = 'jar'
        }
    }
```

Interestingly, if I use that snippet above with Gradle 7.4.2 but with  type = 'orbit' (or any other invented value) I get the exact same error than in first post.

So something has regressed with how the `orbit` packaging type is handled in v7.5. Before it was equivalent to `jar` (I believe), but not anymore.

**Comment by bubbleguuum** [comment]
Still having this issue with Gradle master compiled as of the date of this report.
The workaround consisting in the artifact transform above to change type from 'orbit' to 'jar' is not working at all.
Let alone that this (supposed) workaround was not necessary in v7.4.2.
I still cannot update to v7.5+...

**Comment by courville** [comment]
FYI, I have the same issue for my Android application https://github.com/nova-video-player/aos-AVP, I cannot upgrade to v7.5+

**Comment by bubbleguuum** [comment]
I worked-around this issue by changing in my local maven repo the problematic maven project that declares `<packaging>orbit</packaging>` in its `.pom` and change it to `<packaging>pom</packaging>` . Prior to v7.5, Gradle did this automatically with I believe special detection of this `orbit` packaging.

**Comment by bubbleguuum** [comment]
And also had to make the local maven repo have precedence for the modified dependency to force its use.
In `settings. gradle`:

```
dependencyResolutionManagement {
    repositories {

        mavenLocal() {
            content {
                includeModule("org.eclipse.jetty.orbit", "javax.servlet");
            }
        }

       // other repos follow
       ...
    }
}
```

Ideally, this regression should be best fixed in Gradle to avoid that ugly work-around.

**Comment by stefanpledl** [comment]
does someone have another workaround?
i cannot get it to work with:

`    implementation 'org.eclipse.jetty:jetty-server:8.2.0.v20160908'
    implementation 'org.eclipse.jetty:jetty-servlet:8.2.0.v20160908'
    implementation 'org.eclipse.jetty:jetty-client:8.2.0.v20160908'
`

**Comment by courville** [comment]
FYI on my side now it works (builds and no `NoClassDefFoundError`) adding to `build.gradle`:
````
    implementation group: 'javax.servlet', name: 'javax.servlet-api', version: '3.1.0'
```
and using gradle 7.5 and AGP 7.4.2

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Even if you can't write a simple reproducer, please provide us with instructions on how to reproduce it on a public project.
