### ISSUE TITLE
Gradle generated incorrect build/scripts/app and build/scripts/app.bat 

### ISSUE THREAD

**Issue by cogitaria-admin** [gradle/gradle#21458]
The generated "app" script sets CLASSPATH=$APP_HOME/lib/app.jar:...

There is no **/lib** folder so it throws ClassNotFoundException but there a **/libs** folder was generated. Adding an "s" fixes the script. Same typo is in the distribution/app.tar and app.zip. 

### Expected Behavior

Generated build/scripts need to have correct CLASSPATH with **libs** rather than **lib** folder. 

### Context

Run generated script to run the executable jar.

### Steps to Reproduce 

Run gradlew init and build and note the typo in the build/scripts/app file: lib versus libs

### Your Environment

Build scan URL:

------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Mac OS X 10.15.7 x86_64

**Comment by big-guy** [comment]
I don't believe this is the case.

Here's the directory structure for the application project generated by `gradle init` with 7.5:

> app/build/install/
> └── app
>     ├── bin
>     │   ├── app
>     │   └── app.bat
>     └── lib
>         ├── app.jar
>         ├── checker-qual-3.12.0.jar
>         ├── error_prone_annotations-2.7.1.jar
>         ├── failureaccess-1.0.1.jar
>         ├── guava-31.0.1-jre.jar
>         ├── j2objc-annotations-1.3.jar
>         ├── jsr305-3.0.2.jar
>         └── listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar


*lib* is the correct path.

**Comment by CoXier** [comment]
@big-guy 
Can I ask you a question about how do you generate above file three output/

**Comment by big-guy** [comment]
@CoXier it's just [tree](https://linux.die.net/man/1/tree)

**Comment by CoXier** [comment]
> @CoXier it's just [tree](https://linux.die.net/man/1/tree)

Thanks a lot.
