### ISSUE TITLE
Missing documentation for ANTLR plugin

### ISSUE THREAD

**Issue by MagnusMG** [gradle/gradle#21450]
The documentation of the ANTLR plugin (https://docs.gradle.org/current/userguide/antlr_plugin.html) is incomplete. When I tried to find a way of specifying where the generated java files would end up, all I could find was the general property `arguments` in `generateGrammarSource`. In the ANTLR documentation (https://github.com/antlr/antlr4/blob/master/doc/tool-options.md) it is said that the option `-o` can be used to specify the destination directory for the generated java files. However, this does not seem to work with the plugin. Instead, there in a separate option `outputDirectory` under `generatedGrammarSource` that works. 

I could have reported this as a bug, but I strongly suspect it is just missing documentation. Are theer other undocumented options available?

I am not fluent enough in gradle to say wether this is some kind of general feature of this type of plugins -- that you can specify destination directory with `outputDirectory` -- but if that is the case there should be some kind of reference to this in the documentation.

### Expected Behavior
At he bottom of the page, under Example 3, there should be a paragraph roughly like this:

The destination directory of the generated files defaults to `build/generated-src`, but can be changed with the option `outputDirectory`:

````
generateGrammarSource {
    maxHeapSize = "64m"
    arguments += ["-visitor", "-long-messages"]
    outputDirectory = file('src/my-special-directory')
}
````

### Current Behavior
There is no mentioning of this at all.

### Context
I needed to change the destination directory in order to make the files part of a java module. The file `module-info.java` has to be placed in a super directory of the source files of the module, and I could not get that whole thing to work if the source files were placed under the `build` directory. Several solutions are suggested in various discussion fora, but the one I got to work was to simply let ANTLR put the generated files under the `source` directory, next to the 'hand written' source code.

**Comment by jbartok** [comment]
Pls. note that the documentation you need is there, just not on the main manual page. Usually, we would expect people to discover these properties by looking at the DSL, particularly at the details of the 
[AntlrTask](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.antlr.AntlrTask.html), which is linked from the plugin's page.

**Comment by MagnusMG** [comment]
Ah! AntlrTask is some kind of superclass for generateGrammarSource  and the other tasks! Probably obvious for people more used to Gradle...

Thanks. Sorry for bothering you.
