### ISSUE TITLE
do build or compileTestJava action Failed

### ISSUE THREAD

**Issue by albert-flex** [gradle/gradle#21466]
### Expected Behavior
No Error. Build Or CompileTestJava Successfully.

### Current Behavior
Report That Module Name Error.
there has the error info following:
```
D:\Artifact\Code\bug-gradle-test-demo\demo\src\test\java\module-info.java:1: 错误: 模块名称 test 与预期名称 demo 不匹配
module test {
^
D:\Artifact\Code\bug-gradle-test-demo\demo\src\test\java\module-info.java:2: 错误: 涉及 demo 的循环被依赖对象
    requires demo;
             ^
2 个错误
```

### Context
I wanna run Module Test with module-info.java in test correctly.
that is ok when no javafx dependency in module, while now is error with javafx depdency.

### Steps to Reproduce 
My Repository:
https://github.com/albert-flex/bug-gradle-test-demo.git

### Your Environment
- JDK 17
- Gradle 7.4

**Comment by jbartok** [comment]
Actual failure in English:

```
> Task :compileTestJava FAILED
/Users/jozsef/Work/bt-support/21466/bug-gradle-test-demo/demo.2/src/test/java/module-info.java:1: error: module name test does not match expected name demo
module test {
^
/Users/jozsef/Work/bt-support/21466/bug-gradle-test-demo/demo.2/src/test/java/module-info.java:2: error: cyclic dependence involving demo
    requires demo;
             ^
error: cannot access module-info
  cannot resolve modules
warning: module name in --add-reads option not found: demo
3 errors
1 warning
```

**Comment by jbartok** [comment]
This looks like an error in your project setup, not in Gradle. You need to fix your module definitions, based on the errors provided by the compiler.

**Comment by albert-flex** [comment]
Had you have a look at the demo project？ there is no big different about setup between these two projects.
Ok If you think that is not gradle's error, forget this issue then.




| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | József ***@***.***> |
| Date | 08/19/2022 16:35 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [gradle/gradle] do build or compileTestJava action Failed (Issue #21466) |

This looks like an error in your project setup, not in Gradle. You need to fix your module definitions, based on the errors provided by the compiler.
