### ISSUE TITLE
Don't clear `distributionSha256Sum` when updating Gradle wrapper

### ISSUE THREAD

**Issue by ccjernigan** [gradle/gradle#21463]
When updating Gradle, configuring the correct Gradle SHA is difficult because the SHA gets cleared automatically.

### Expected Behavior
`distributionSha256Sum` is not affected by updating the Gradle wrapper.

### Current Behavior
`distributionSha256Sum` is removed from gradle-wrapper.properties when generating an updated wrapper.

### Context
When updating to new versions of Gradle, I have to do a silly little dance that goes like this:

1. Update the Gradle version in gradle/wrapper/gradle-wrapper.properties
2. Update the [Gradle SHA](https://gradle.org/release-checksums/) in gradle/wrapper/gradle-wrapper.properties
3. Update the Gradle wrapper by running ./gradlew wrapper
4. Re-add the [Gradle SHA](https://gradle.org/release-checksums/) to gradle/wrapper/gradle-wrapper.properties

Step 4 should be necessary and is the reason for this bug report.

### Steps to Reproduce 
1. Create a Gradle project
2. Add the correct sha to gradle-wrapper.properties under `distributionSha256Sum`
3. Run `./gradlew wrapper`
4. Look at the gradle-wrapper.properties, specifically `distributionSha256Sum`

**Comment by vlsi** [comment]
Does this duplicate https://github.com/gradle/gradle/issues/12412?

**Comment by ccjernigan** [comment]
No, this is a separate issue. This issue is that the `distributionSha256Sum` is known and I have set it, but Gradle clears it.  That other issue is about inserting the `distributionSha256Sum` automatically which requires a very different implementation.

**Comment by vlsi** [comment]
Well, you mention wrapper update, and you want to keep sha256. Do you suggest the subsequent executions should fail?

**Comment by ccjernigan** [comment]
If the sha256 is wrong, it should fail.
