### ISSUE TITLE
Gradle's failure to load *.module file may cause a failing build

### ISSUE THREAD

**Issue by zogmn** [gradle/gradle#21464]
### Description

It seems that in some cases Gradle does not respect `published-with-gradle-metadata` in POM file, and therefore fails to load module file, thus missing some necessary dependencies, and resulting in unstable or failing build.

### Example

In a project I am working on we have a dependency to `io.insert-koin:koin-android:3.2.0`, which, in absence of ~/.m2/repository will result with the following part of the dependency tree:

    +--- io.insert-koin:koin-android:3.2.0
         +--- io.insert-koin:koin-core:3.2.0
              \--- io.insert-koin:koin-core-jvm:3.2.0

In our code we use classes from `io.insert-koin:koin-core-jvm:3.2.0` library.

However, if there is a local Maven repository available and `io.insert-koin:koin-core:3.2.0` is already downloaded by Maven, Gradle will read the `koin-core-3.2.0.pom` file. That POM file contains the hint `published-with-gradle-metadata`, which should, to my understanding, cause Gradle to also download `koin-core-3.2.0.module` file, and add `io.insert-koin:koin-core-jvm:3.2.0` to the dependency tree.

However, this **does not** happen, and it results in the dependency tree where `io.insert-koin:koin-core-jvm:3.2.0` is missing:

    +--- io.insert-koin:koin-android:3.2.0
         \--- io.insert-koin:koin-core:3.2.0

which will result in a failing build.

### Steps to reproduce

  0. Install Maven, version e.g. 3.8.4
  1. Delete Gradle cache (\~/.gradle/caches) and local Maven repo (\~/.m2/repository), if they exist
  2. Force download of `io.insert-koin:koin-core:3.2.0` dependency to local Maven repo with `mvn org.apache.maven.plugins:maven-dependency-plugin:3.3.0:get -DrepoUrl=https://repo1.maven.org/maven2/ -Dartifact=io.insert-koin:koin-core:3.2.0`
  3. Confirm that `~/.m2/repository/io/insert-koin/koin-core/3.2.0/koin-core-3.2.0.pom` exists and it contains string `published-with-gradle-metadata` in the comment
  4. Unpack the attached example project, change local.properties accordingly, and build it with `./gradlew build`
  5. The build will fail because of missing classes from koin-core-jvm

### Expexted result

  5. The build passes
  
### Workaround

  6. Stop Gradle daemons (`./gradlew --stop`)
  7. Delete local Maven repo (`~/.m2/repository`)
  8. Repeat the build
  9. The build will pass
  
Note: I used Gradle 7.4.2 and Maven 3.8.4, tested on Windows 10.

### Tiny example project demonstrationg the issue

[gradle-unstable-build.zip](https://github.com/gradle/gradle/files/9275144/gradle-unstable-build.zip)

**Comment by jbartok** [comment]
Pls. check out the following section of the documentation: https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local

In short: since your Maven local repo doesn't have the module file, Gradle will only use the pom.
