### ISSUE TITLE
Gradle 7: Linter does not recognize dependency from subpackage

### ISSUE THREAD

**Issue by robingenz** [gradle/gradle#21462]
### Expected Behavior

When linting a project which references a dependency of a sub-package in the `AndroidManifest.xml`, the error `Unresolved class ...` should not appear.

### Current Behavior

I get the following error when linting a project which references a dependency of a sub-package in the [`AndroidManifest.xml`](https://github.com/robingenz/capacitor-firebase-authentication-demo/blob/c35019ec86c1530221c4a2d1eee61eb745cfd8e9/android/app/src/main/AndroidManifest.xml#L22):

```
> Task :app:lintDebug FAILED
Lint found 2 errors, 13 warnings. First failure:

C:\Users\robin\Documents\GitHub\capacitor-firebase-authentication-demo\android\app\src\main\AndroidManifest.xml:22: Error: Class referenced in the manifest, com.facebook.FacebookActivity, was not found in the project or the libraries [MissingClass]
            android:name="com.facebook.FacebookActivity"
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The full lint text report is located at:
  C:\Users\robin\Documents\GitHub\capacitor-firebase-authentication-demo\android\app\build\intermediates\lint_intermediate_text_report\debug\lint-results-debug.txt
```

See GitHub Actions run: https://github.com/robingenz/capacitor-firebase-authentication-demo/runs/7703158307?check_suite_focus=true

### Context

I am maintaining an [Android project](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/authentication/android) that uses [`com.facebook.android:facebook-login:14.1.0`](https://developers.facebook.com/docs/facebook-login/android/) as a dependency. 
So far (with Gradle 4) this dependency has been detected by the particular Android app that uses my project and there have been no errors when linting.
Since the update to Gradle 7, this dependency of the sub-package is unfortunately no longer recognized (see https://github.com/capawesome-team/capacitor-firebase/issues/117).

![grafik](https://user-images.githubusercontent.com/13857929/183244988-a8cb3d06-df67-4618-a432-f3832d44ede2.png)

This is the Android project: https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/authentication/android
This is the Android app: https://github.com/robingenz/capacitor-firebase-authentication-demo/tree/feat/capacitor-4/android

I use Java 11.

I don't have much experience with Gradle yet and hope it's actually an issue and I didn't miss anything in the documentation. 
Thanks for this great project!
Please let me know if you are missing any information.

### Steps to Reproduce 

1. Clone this repository:
	  ```
	  git clone https://github.com/robingenz/capacitor-firebase-authentication-demo.git
	  ```
1. Change to the root directory of the project:
	  ```
	  cd capacitor-firebase-authentication-demo
	  ```
1. Install all dependencies:
	  ```
	  npm i
	  ```
1. Perform web build:
	  ```
	  npm run build
	  ```
1. Prepare the Android app:
	  ```
	  npx ionic cap sync android
	  ```
1. Lint with Gradle:
	  ```
	  cd android
	  ./gradlew lint
	  ```

### Your Environment

Build scan URL: https://scans.gradle.com/s/txgkvlm5lvake

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
