### ISSUE TITLE
How to download my gradle transitive dependencies to a specific folder

### ISSUE THREAD

**Issue by yhl3692319** [gradle/gradle#2147]
### Expected Behavior
As a user, I met a problem when using transitive dependencies for compiling.

For example:

Defining an executable that depends on library A that depends on library B, and B has transitive dependency C.

When compiling A, it need header file b.h in B, and B need header file c.h in C.
```
configurations {
  package-A
}

dependencies {
  package-A (group: 'your.group', name: 'package-B', version: '1.0', ext: 'zip') {
    transitive = true
  }
}

task downloadPackageA() << {
  copy {
    configurations.package-A.asFileTree.each {
      from( zipTree(it) )
    }
    into file(package-A_download_dir)
  }
}
```

### Current Behavior
When executing `gradle build`, it downloads all dependencies in one folder(for example in folder package-A), so when compiling, it can not find the correct path of c.h file. what I want is that it can download transitive dependencies to a transitive folder 

Current Result
```
package-A/
├── include
│   ├── b.h
│   ├── c.h
├── lib
│   ├── b.a
│   ├── c.a
```

Expected Result
```
package-A/
├── package-B/
│   ├── package-C/
│   │   ├── include
│   │   │   ├── c.h
│   │   ├── lib
│   │   │   ├── c.a
│   ├── include
│   │   ├── b.h
│   ├── lib
│   │   ├── b.a
```
I'm a new user of gradle,  Any guidance or suggestions?

**Comment by lacasseio** [comment]
Thanks for following the contribution guide. The GitHub issues are reserved for feature request and bug. This issue feels more like a question. Please use the [user forum](https://discuss.gradle.org/) for any question related to Gradle usage. In the event your question does turn out to be a valid GitHub issue, please provide detail regarding the feature or bug.
