### ISSUE TITLE
Report usages of commonly used APIs for cross project access when isolated projects is enabled

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#21485]
Add some more problems for some common APIs:

On `Project`

- [x] `Project.rootProject`
- [x] `Project.parent`
- [x] `Project.allprojects` (the getter)
- [x] `Project.subprojects` (the getter)
- [x] `Project.project()`
- [x] `Project.findProject()`
- [x] `Project.childProjects`
- [x] `Project.getAllProjects()` (both the keys and values)
- [x] `Project.getTasksByName()`
- [x] `Project.properties` and `getProperty()`
- [x] `Project.evaluationDependsOn()` (returns project)

On `Gradle`

- [x] `Gradle.rootProject`
- [x] `Gradle.parent`
- [x] `Gradle.beforeProject`
- [x] `Gradle.afterProject`
- [x] `addProjectEvaluationListener(...)` (`ProjectEvaluationListener` receives `Project` in `beforeEvaluate` and `afterEvaluate`)
- [x] `addBuildListener(...)`
- [x] `addListener(...)` – the user-provided listener object can implement:
    * `ProjectEvaluationListener` (same as above), 
    * `TaskExecutionGraphListener` (a `TaskExecutionGraph` is passed to the user code),
    * `BuildListener` (`Gradle` and `Settings` references might be passed to the user code).

On `Settings`

- [x] `Settings.getGradle()`, we want it to return an object that still tracks the referring project, if it's there.

Other places (split these out to other cards)

- [x] Tasks returned by `Buildable.taskDependencies`
- [x] Tasks returned by various `TaskGraph` methods.
- [x] Project returned by `ProjectDependency.dependencyProject` (should deprecate this)
- [x] Group and version on `ProjectDependency`.
- [x] Inherited properties.

Reconsider

- [x] ~Should `Project.files()`, etc be usable via another project instance? They don't reference any mutable state.~

**Comment by h0tk3y** [comment]
Some leftover corner cases after the current stage:
* https://github.com/gradle/gradle/issues/22633

**Comment by h0tk3y** [comment]
>Reconsider 
>*  Should `Project.files()`, etc be usable via another project instance? They don't reference any mutable state.

In fact, the `project.files()` implementation is project-dependent in some details, such as project isolation compliance checks, which would require more complicated implementations to support using a `files()` collection created by one project in another. 

We need to weigh the increased implementation complexity against the potential benefits of supporting such use cases, which are not clear for now.

**Comment by h0tk3y** [comment]
Completed in the following sets of changes:
* https://github.com/gradle/gradle/pull/21600
* https://github.com/gradle/gradle/pull/21838
* https://github.com/gradle/gradle/pull/22433
* https://github.com/gradle/gradle/pull/22445
* https://github.com/gradle/gradle/pull/22475

**Comment by bamboo** [comment]
🎉
