### ISSUE TITLE
Deprecation message after migration to 7.4.2 with 'org.gradle.parallel'

### ISSUE THREAD

**Issue by zoldater** [gradle/gradle#21492]
Valid reproducer of the issue could be found at https://youtrack.jetbrains.com/issue/KTIJ-21619
The problem looks similar to https://github.com/gradle/gradle/issues/17039 expect of the project structure.

### Expected Behavior

Gradle Sync in Intellij IDEA should finish without any issues.

### Current Behavior
Deprecation message appears: `Resolution of the configuration :build-logic:base-plugins:detachedConfiguration1 was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. See https://docs.gradle.org/7.4/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors for more details.`

### Context

Isuue started happening after migration from Gradle 6.9.2 to 7.4.2

The issue disappears if remove the nested project from `includeBuild` one.

### Steps to Reproduce 

1. Open the reproducer attached to https://youtrack.jetbrains.com/issue/KTIJ-21619
2. Make Gradle Sync and observe the message in log
3. Comment `include` statement from settings.gradle.kts within the composite project
4. Make Gradle Sync again, no message in log

### Your Environment

Build scan URL: https://scans.gradle.com/s/l74gcqpcjvlss/

**Comment by jjohannes** [comment]
Note: The problem also exists with Gradle `6.9.2`. I don't know of any Gradle version that, in combination with latest IDEA, does not have this problem.

**Comment by Omico** [comment]
I am still facing the same issue in 7.5.1 with Intellij IDEA 2022.2.

**Comment by jjohannes** [comment]
Is there anything planned to do about this? I had several folks wondering and asking me about this.

I would be interested in why this is an issue on the Gradle side as it only appears in IDEA. Is this somewhere in the `idea` plugin? Maybe someone can share what was discussed when this issue was moved here from IDEA issue tracker.

**Comment by Omico** [comment]
> Is there anything planned to do about this? I had several folks wondering and asking me about this.
> 
> I would be interested in why this is an issue on the Gradle side as it only appears in IDEA. Is this somewhere in the `idea` plugin? Maybe someone can share what was discussed when this issue was moved here from IDEA issue tracker.

Great points! I realize that if we use IDEA, it will add some init scripts inside the `StartParameter`. These scripts add and apply some jars for classpath, which may contain some deprecations' operation on it.

**Comment by donat** [comment]
[Reproducer project](https://github.com/gradle/gradle/files/9525553/21492.zip)

**Comment by donat** [comment]
I think the problem is on both sides. To extract structural information from the Gradle build, IDEA needs to inject custom plugins which are done via an init script. At the same time, Gradle doesn't cover all use-cases to inject plugins, so IDEA needs use workarounds for the injection which causes warnings such as the one reported in this issue.

**Comment by donat** [comment]
Related to https://github.com/gradle/gradle/issues/20898

**Comment by ljacomet** [comment]
@donat Could you decide what to do with this issue for Gradle 8.1?

**Comment by ljacomet** [comment]
See also
* #15522
