### ISSUE TITLE
application.defaultJvmArgs aren't applied when running from the configuration cache

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#21505]
The application plugin's `run` command doesn't respect `defaultJvmArgs` set in the build file when the build reuses the configuration cache.

A simple build file:
```gradle
plugins {
    application
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

application {
    mainClass.set("Main")
    applicationDefaultJvmArgs = listOf(
        "-Dconfig.resource=local.conf"
    )
}
```
### Expected Behavior
`defaultJvmArgs` should be applied to the started JVM regardless of the configuration cache status.

### Current Behavior
`defaultJvmArgs` are only applied if the configuration cache isn't reused.

[app-plugin-cc-problem.zip](https://github.com/gradle/gradle/files/9310217/app-plugin-cc-problem.zip)

**Comment by mlopatkin** [comment]
This might or might be not related to #15239.

**Comment by natros** [comment]
I'm trying to use configuration cache in all my projects and this is my biggest problem.
Is there any estimate to fix this?

**Comment by rlconst** [comment]
Any change to be backported to 7.x?
