### ISSUE TITLE
google() needs to point to 'https://dl.google.com/dl/android/maven2'

### ISSUE THREAD

**Issue by jmslau** [gradle/gradle#2151]
We have confirmation from our China team that https://maven.google.com is blocked in China. As such, can we please change the google() shortcut to point to 'https://dl.google.com/dl/android/maven2'? That URL is not blocked.

**Comment by lacasseio** [comment]
@jmslau Our concern is `maven.google.com` is redirecting to `dl.google.com/dl/android/maven2` and we don't know when that redirection may change. We want to avoid dependencies with Google infrastructure. Thanks for your input.

**Comment by bmuschko** [comment]
URL has been changed.

**Comment by jmslau** [comment]
Awesome, thanks!

**Comment by snowdream** [comment]
maven { url "https://dl.google.com/dl/android/maven2/" }

**Comment by yangyudaddy** [comment]
I can't visit  this url "https://dl.google.com/dl/android/maven2/"

**Comment by bmuschko** [comment]
@yangyudaddy The direct repository URL is not browsable. You can have a look at the content here: https://dl.google.com/dl/android/maven2/index.html.

**Comment by yangyudaddy** [comment]
@bmuschko Thank you.

**Comment by nb312** [comment]
but I can not access yet.
