### ISSUE TITLE
Can't inject project services into artifact transforms

### ISSUE THREAD

**Issue by DenWav** [gradle/gradle#21525]
When attempting to inject a service into an artifact transform as you would with a task, such as:
```kt
@get:Inject
abstract val layout: ProjectLayout
```

### Expected Behavior
I would expect services to be available to artifact transforms in the same manner as they are to tasks.

### Current Behavior
Gradle will throw an error about not being able to find said service:
```
         > Could not create an instance of type Filter.
            > No service of type interface org.gradle.api.file.ProjectLayout available.
```

### Context
I have an artifact transform which looks at files in the project, so the `ProjectLayout` service is the easiest option. In this particular instance I can rewrite my logic to collect the file info in the build script and pass it in as a parameter, but that would not handle all of the utilities the different services provide.

### Steps to Reproduce 
Define an artifact transform exactly as shown in [the documentation](https://docs.gradle.org/current/userguide/artifact_transforms.html):
```kt
val artifactType = Attribute.of("artifactType", String::class.java)
val filtered = Attribute.of("minified", Boolean::class.javaObjectType)

dependencies {
    attributesSchema {
        attribute(filtered)
    }

    artifactTypes.getByName("jar") {
        attributes.attribute(filtered, false)
    }

    registerTransform(Filter::class) {
        from.attribute(filtered, false).attribute(artifactType, "jar")
        to.attribute(filtered, true).attribute(artifactType, "jar")
    }

    implementation(kotlin("stdlib-jdk8"))
}

abstract class Filter : TransformAction<TransformParameters.None> {
    @get:Inject
    abstract val layout: ProjectLayout

    override fun transform(outputs: TransformOutputs) {}
}
```

Execute `./gradlew dependencies` to see the error.

### Environment
```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (Azul Systems, Inc. 11.0.13+8-LTS)
OS:           Mac OS X 13.0 x86_64
```

**Comment by big-guy** [comment]
This is intentional. To make sure that the artifact transform runs at the right time, Gradle needs to know what the inputs to the artifact transform are.  Arbitrary access to the project layout would defeat that. 

Take a look at the `ClassRelocator` further down that page in the documentation.  You can use some of the same input annotations as a task to mark inputs to the transform.
