### ISSUE TITLE
Broken link to processResources on the Java Plugin doc page

### ISSUE THREAD

**Issue by pfurbacher** [gradle/gradle#21522]
Navigate to [The Java Plugin](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_tasks). 

Scroll down to "processResources" entry. 

Press the link [ProcessResources](https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html)

Result: "This page does not exist."

**Comment by ljacomet** [comment]
PR has been merged
