### ISSUE TITLE
getConfigurations().getByName("compile").getResolvedConfiguration() doesn't contain api dependencies.

### ISSUE THREAD

**Issue by SetoKaiba** [gradle/gradle#2155]
getConfigurations().getByName("compile").getResolvedConfiguration() doesn't contain api dependencies.

In the 3.5, java-library plugin is introduced. Previously, the line above will return compile and providedCompile dependencies. API should be some kind of compile scope I think. But it doesn't contain them.

**Comment by oehme** [comment]
Please use `compileClasspath` if you want to know all dependencies used for compilation.
