### ISSUE TITLE
Document integration of Scala plugin with toolchains and problems with `target` flag

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#21551]
In the current toolchain docs it says that toolchains work with Scala:
https://docs.gradle.org/current/userguide/toolchains.html#sec:consuming

However, there is a problem with the `target` flag of the Scala compiler, that has been discussed here:
https://github.com/gradle/gradle/issues/19456#issuecomment-1004460716

As such, toolchains do not work with Scala as smoothly as expected and these complications should at least be documented.

**Comment by wakingrufus** [comment]
Is there at least a known workaround for this issue other than going back to java 8?

**Comment by vlushn** [comment]
Is this same issue as https://github.com/gradle/gradle/issues/20180 ?

**Comment by ljacomet** [comment]
* Fixed by #23926
