### ISSUE TITLE
high version gradle can't find  version through BOM in child dependency

### ISSUE THREAD

**Issue by qlql489** [gradle/gradle#21568]
zeue-core is a java jar , part of it's  bom like this
```
<dependencies>
<dependency>
   <groupId>cglib</groupId>
   <artifactId>cglib</artifactId>
   <scope>runtime</scope>
<exclusions>
<exclusion>
</dependencies>
<dependencyManagement>
   <dependencies>
      <dependency>
        <groupId>com.wb.zeus</groupId>
        <artifactId>zeus-root</artifactId>
        <version>1.0-SNAPSHOT</version>
       <scope>import</scope>
       <type>pom</type>
     </dependency>
   </dependencies>
</dependencyManagement>
```
i use  java-platform build  com.wb.zeus:zeus-root
it constraints   api 'cglib:cglib:3.3.0'
another project testSub  implementation zeus-core like
```
implementation('com.wb.zeus:zeus-core:1.0-SNAPSHOT')
```
use gradlew 4.10.1 ,it can build success,but when user gradlew 6.9.1,build error:
```
Could not find cglib:cglib:.
     Required by:
         project :testSub > com.wb.zeus:zeus-core:1.0-SNAPSHOT:20220816.064812-13
```

### Expected Behavior
use new gradle version,project can implement com.wb.zeus:zeus-core  not implement  com.wb.zeus:zeus-root

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.
