### ISSUE TITLE
`PathSensitivity.RELATIVE` does not ignore order of `InputArtifactDependencies`

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#21573]
### Context

When building Android projects having dynamic features, during the dexing step, the Android Gradle plugin may request Gradle to transform the same [`InputArtifact`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/transform/InputArtifact.html) multiple times, and we expect that only the first transform does the actual work, and subsequent transforms should be UP-TO-DATE. 

However, as filed at [Gradle issue 21250](https://github.com/gradle/gradle/issues/21250), the order of [`InputArtifactDependencies`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/transform/InputArtifactDependencies.html) can change for the same `InputArtifact`, and therefore the transform is repeated multiple times for *each* `InputArtifact`. This causes a **huge** performance impact for users, as reported at https://issuetracker.google.com/169266011.

To provide a workaround for users while the above issue is not yet fixed, we want to use `PathSensitivity.RELATIVE` on `InputArtifactDependencies`, so that the order can be ignored.

However, the following sample project shows that the order is still NOT ignored.

### Steps to Reproduce
1. Open the attached project: [DynamicFeatureProject.zip](https://github.com/gradle/gradle/files/9376061/DynamicFeatureProject.zip)

2. Run `rm lib/build/.transforms -rf && ./gradlew --stop && ./gradlew :dynamicfeature:mergeLibDexDebug :dynamicfeature2:mergeLibDexDebug` *twice* (the first one is just a warm-up). Observe the following:
```
> Transform classes.jar (project :lib) with DexingWithClasspathTransform
Processing classes.jar with classpath: [jetified-core-ktx-1.8.0-runtime.jar, core-1.8.0-runtime.jar, lifecycle-runtime-2.3.1-runtime.jar, core-runtime-2.1.0-runtime.jar, core-common-2.1.0.jar, versionedparcelable-1.1.1-runtime.jar, collection-1.0.0.jar, jetified-concurrent-futures-1.0.0.jar, lifecycle-common-2.3.1.jar, annotation-1.2.0.jar, jetified-kotlin-stdlib-1.7.0.jar, jetified-kotlin-stdlib-common-1.7.0.jar, jetified-annotations-13.0.jar, jetified-annotation-experimental-1.1.0-runtime.jar, jetified-listenablefuture-1.0.jar] 

> Transform classes.jar (project :lib) with DexingWithClasspathTransform
Processing classes.jar with classpath: [jetified-core-ktx-1.8.0-runtime.jar, core-1.8.0-runtime.jar, versionedparcelable-1.1.1-runtime.jar, collection-1.2.0.jar, lifecycle-runtime-2.3.1-runtime.jar, core-runtime-2.1.0-runtime.jar, core-common-2.1.0.jar, jetified-concurrent-futures-1.0.0.jar, lifecycle-common-2.3.1.jar, annotation-1.2.0.jar, jetified-kotlin-stdlib-1.7.0.jar, jetified-kotlin-stdlib-common-1.7.0.jar, jetified-annotations-13.0.jar, jetified-annotation-experimental-1.1.0-runtime.jar, jetified-listenablefuture-1.0.jar] 
```

The above log is produced by this code in `buildSrc` that patches the Android Gradle plugin's code:
```
// In buildSrc/.../DexTransform.kt

// Line 112
System.err.println("Processing ${input.name} with classpath: ${computeClasspathFiles().map { it.name }} ")

// Line 320
@get:PathSensitive(PathSensitivity.RELATIVE) // Workaround for https://github.com/gradle/gradle/issues/21250, previously this was @get:CompileClasspath
@get:InputArtifactDependencies
abstract val classpath: FileCollection
```

The log shows that:
  - Even though the input to be transformed (`classes.jar` in `project :lib`) is the same, the `InputArtifactDependencies`'s order has changed -- this is [Gradle issue 21250](https://github.com/gradle/gradle/issues/21250)
  - The change in `InputArtifactDependencies`'s order is not ignored by `PathSensitivity.RELATIVE` -- this is this issue

### Expected Behavior
When `PathSensitivity.RELATIVE` is used on `InputArtifactDependencies`, the change in the `InputArtifactDependencies`'s order should be ignored. (In the above project, it means that the second transform should be UP-TO-DATE.)

**Comment by wolfs** [comment]
@hungvietnguyen How do you know `classes.jar` didn't change? Note that when changing from `@Classpath` to `@PathSensitivity(RELATIVE)` that timestamps and order in jar files matters again. So when the recreated JAR files contain different timestamps, or are not byte-for-byte equivalent, then Gradle will consider them changed.

**Comment by hungvietnguyen** [comment]
`classes.jar` is published from `project :lib`, so it it produced only once.

To confirm that, I printed more details on the `InputArtifact`:
```
// In buildSrc/.../DexTransform.kt - Line 112
System.err.println("Processing ${input.path} (timestamp: ${input.lastModified()}, size: ${input.length()}) with classpath: ${computeClasspathFiles().map { it.name }} ")
```

and got the following log:
```
> Transform classes.jar (project :lib) with DexingWithClasspathTransform
Processing DynamicFeatureProject/lib/build/intermediates/runtime_library_classes_jar/debug/classes.jar (timestamp: 1660926444958, size: 1500) with classpath: [jetified-core-ktx-1.8.0-runtime.jar, core-1.8.0-runtime.jar, versionedparcelable-1.1.1-runtime.jar, collection-1.2.0.jar, lifecycle-runtime-2.3.1-runtime.jar, core-runtime-2.1.0-runtime.jar, core-common-2.1.0.jar, jetified-concurrent-futures-1.0.0.jar, lifecycle-common-2.3.1.jar, annotation-1.2.0.jar, jetified-kotlin-stdlib-1.7.0.jar, jetified-kotlin-stdlib-common-1.7.0.jar, jetified-annotations-13.0.jar, jetified-annotation-experimental-1.1.0-runtime.jar, jetified-listenablefuture-1.0.jar] 

> Transform classes.jar (project :lib) with DexingWithClasspathTransform
Processing DynamicFeatureProject/lib/build/intermediates/runtime_library_classes_jar/debug/classes.jar (timestamp: 1660926444958, size: 1500) with classpath: [jetified-core-ktx-1.8.0-runtime.jar, core-1.8.0-runtime.jar, lifecycle-runtime-2.3.1-runtime.jar, core-runtime-2.1.0-runtime.jar, core-common-2.1.0.jar, versionedparcelable-1.1.1-runtime.jar, collection-1.0.0.jar, jetified-concurrent-futures-1.0.0.jar, lifecycle-common-2.3.1.jar, annotation-1.2.0.jar, jetified-kotlin-stdlib-1.7.0.jar, jetified-kotlin-stdlib-common-1.7.0.jar, jetified-annotations-13.0.jar, jetified-annotation-experimental-1.1.0-runtime.jar, jetified-listenablefuture-1.0.jar] 
```

As we can see, `classes.jar` is unchanged, but the transform for it happened twice.

**Comment by wolfs** [comment]
I checked your dependencies, and this is the diff:
```
collection-1.2.0.jar' / ea4ff982a914d2aaede5987b58c2d1f0
vs.
collection-1.0.0.jar' / 8f827fc99905c6f99292afbffb03b2ae
```

So one variant is using collection-1.2.0.jar while the other one is using collection-1.0.0.jar. You can also see this in your printouts above. So not only the order is different, the contents are as well.

I'll close this issue now, please comment if you have a similar problem or a different reproducer.

**Comment by hungvietnguyen** [comment]
Thanks for pointing that out Stefan! I was completely unaware that the version has changed too. Added this finding to https://github.com/gradle/gradle/issues/21250#issuecomment-1228272262.
