### ISSUE TITLE
Scala compilation with sbt/zinc

### ISSUE THREAD

**Issue by dforsl** [gradle/gradle#2158]
Gradle currently supports Scala compilation with the [typesafe/zinc](https://github.com/typesafehub/zinc)-compiler, which is in maintenance mode.

However, new development is now ongoing under [sbt/zinc](https://github.com/sbt/zinc). It would be great if the scala-plugin could support this new initiative that is actively further developing Scala compilation.

**Comment by ijuma** [comment]
sbt/zinc includes much improved incremental compilation:

```This depends on some factors such as how your classes are organized, but you can see 3x ~ 40x improvements. The reason for the speedup is because it compiles fewer source files than before by untangling the classes from source files. In the example adding a method to scala/scala’s Platform class, sbt 0.13’s name hashing used to compile 72 sources, but the new Zinc compiles 6 sources.```
https://developer.lightbend.com/blog/2017-04-18-sbt-1-0-roadmap-and-beta1/#zinc-1-class-based-name-hashing

Also, my understanding is that there is/will be a supported Java API.

**Comment by dforsl** [comment]
Maybe this should be put in it's own ticket, and probably thought of already, but I just wanted to say that it would be absolutely brilliant if this also utilised the new worker api for parallelism within the same project!

**Comment by jjohannes** [comment]
I checked if I could do a quick update to sbt/zinc and run it through our test pipeline. Unfortunately the API seems to be quite different compared to typesafe/zinc. So it is not only a matter of changing the namespace.

If anyone here is more familiar with sbt/zinc and would be willing to provide a PR, I will happily review and merge it.

The integration is encapsulated in [ZincScalaCompiler.java](https://github.com/gradle/gradle/blob/6cbcfdcd042d756ad23399f21fd87a4af8a702d1/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompiler.java) and [ZincScalaCompilerFactory.java](https://github.com/gradle/gradle/blob/6cbcfdcd042d756ad23399f21fd87a4af8a702d1/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java). Ideally we would only need to adjust these two classes.

**Comment by dforsl** [comment]
I'm pretty short on time unfortunately, but can perhaps point to a some place that could be of use if anyone else would like to give it a shot.

As @ijuma hinted, there appears to be a task to provide a proper Java API through https://github.com/sbt/zinc/issues/300. The ticket also points Pants' implementation for Scala compilation with zinc, which could perhaps be of help.

**Comment by ijuma** [comment]
A blog discussing the impressive performance improvement in the new release: http://scala-lang.org/blog/2017/11/03/zinc-blog-1.0.html

**Comment by izhangzhihao** [comment]
I'm just using sbt/zinc in my build.gradle like this
```
zinc "org.scala-sbt:zinc_2.12:1.0.3"
```

And I got 
```
> Task :compileScala 
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc_2.12/1.0.3/8ab1630f052b87799fcb3e18d148326d53609a19/zinc_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc-core_2.12/1.0.3/91bd6057c43e8bae3361a831e7a5d91a69982911/zinc-core_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-core_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc-apiinfo_2.12/1.0.3/5a9b2965adaf30671b8ca02d1878f1b98b8b50bb/zinc-apiinfo_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-apiinfo_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/compiler-interface/1.0.3/36f8626a127d80a0776de7702b39654dcc9711f/compiler-interface-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:compiler-interface:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc-classfile_2.12/1.0.3/1a826de7140b5fab4db4d259ef37c9954aca82d1/zinc-classfile_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-classfile_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc-classpath_2.12/1.0.3/2a712827ca8a1e161e30bb82846a80b9ccbacece/zinc-classpath_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-classpath_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc-persist_2.12/1.0.3/76e3669952f9708f930ac0a429699c4340b72e72/zinc-persist_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-persist_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc-compile-core_2.12/1.0.3/4281ebb6af340a2e12c5f6dbd613abde2d4507b8/zinc-compile-core_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-compile-core_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/zinc-ivy-integration_2.12/1.0.3/fdeb03f818d9c58ced1630548673e721ab81f4d1/zinc-ivy-integration_2.12-1.0.3.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-ivy-integration_2.12:1.0.3
Errors occurred while build effective model from /Users/zhazhang/.gradle/caches/modules-2/files-2.1/org.scala-sbt/librarymanagement-core_2.12/1.0.0/b586d6d3ae551d5576402654b39011ed842a4d0e/librarymanagement-core_2.12-1.0.0.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:librarymanagement-core_2.12:1.0.0


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> com/typesafe/zinc/Setup

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
3 actionable tasks: 3 executed

```

Is there any work around? thanks.

**Comment by wolfs** [comment]
@yawaramin Can you try setting `moduleType = ModuleType.REQUIRES_JAVA_8` in https://github.com/gradle/gradle/blob/0bc46b683cff3f4700544a548a1a9c8746ee3ddb/subprojects/language-scala/language-scala.gradle.kts#L17-L20

That should do the trick.

**Comment by yawaramin** [comment]
@wolfs thank you, that worked! Now on to the next error :-)

**Comment by lunaticare** [comment]
@yawaramin found code for migration to new Zinc API by @samskivert https://github.com/scaled/scala-compiler/commit/c62a27fdbd919f122d3c25a054fb1a0648277d02
Commit message explains a lot 😄 
Hope it helps!

**Comment by Crazyjavahacking** [comment]
With this change, could we extend the Scala plugin DSL to be able to plug-in custom Scala compiler?

**Comment by jvican** [comment]
@eyalroth Thanks for name dropping bloop in this important discussion!
  
As a zinc core maintainer, I recommend integrating with bloop over Zinc. We're focusing on improving the developer experience of Scala users and it's important that a custom zinc integration doesn't happen because it is suboptimal in performance, complicates the life of clients (gradle team), doesn't support the whole of the Scala ecosystem and adds work for zinc maintainers downstream.
  
Would someone from the Gradle team be open to discuss next steps to integrate with bloop? The integration will be simpler than zinc's and will provide more guarantees when it comes to performance and correctness. I'm happy to help out in any way I can.

**Comment by pedjak** [comment]
@big-guy I have submitted https://github.com/gradle/gradle/pull/8485 that upgrades zinc compiler to version 1.2.5 It has been used in our organization internally since Gradle 4.9 without any issues. The incremental compile times decreased significantly.

**Comment by klass-ivan** [comment]
I got an error when disabling incremental compilation by force = true
Process 'command '/home/klass/.sdkman/candidates/java/8.0.191-oracle/bin/java'' finished with non-zero exit value 1

**Comment by snazy** [comment]
@big-guy @wolfs is there any chance that this will make it into 5.5?
Just ran into an issue with Zinc 0.3.15 from Gradle 5.4.1 today with Scala 2.11.12, that doesn't happen without zinc 0.3.15.

**Comment by TheElectronWill** [comment]
@snazy Have a look at [Bloop](https://scalacenter.github.io/bloop/docs/build-tools/gradle), a Scala build server made by the official Scala Center. It integrates with Gradle and could solve your issue. :smiley: "`Gradle uses a three years old version of Zinc`" is even an pro-bloop argument used in its documentation.

**Comment by yawaramin** [comment]
@TheElectronWill hi, Bloop has been brought up before, see above comments :-)

**Comment by snazy** [comment]
@TheElectronWill I took a look at bloop and the concept is promising. However, there are a bunch of issues with bloop that makes it super difficult to use. bloop doesn't support builds against multiple JDK versions (say: different source sets / artifacts built against Java 8 and/or 11 or 12 or ...). So you'd have to manually write a bunch of Gradle code to support that.
It is by far not really integrated into Gradle (yet). So developers have to use both Gradle (to get the bloop configuration) and bloop on the command line to compile it.
It also requires a manual setup of Bloop, which can be quite error prone, especially if you're dealing with different versions/projects and want to keep stuff separate.
I haven't tried bloop via Gradle in IntelliJ...

At least for my use case, because of these issues, bloop is not an option. When bloop is tightly integrated into Gradle, so it is a seamless "developer experience" - i.e. a simple `./gradlew build` just works with bloop without additional configuration, it's fine. I suspect that's all "just work", but I also suspect that it's a lot of work. There are a lot of things that you can do in Gradle, which aren't quite yet possible with bloop.

However, (incremental) Scala compilation in Gradle is not in the best shape, so getting this one in for Gradle 5.5 would be a *huge* improvement. Looking at the most recent version of bloop, I doubt, that a viable bloop integration can be available for maybe Gradle 5.5 or 5.6.

**Comment by big-guy** [comment]
@snazy No, 5.5 is in the final stages of release and only regression fixes are allowed.  We're trying to upgrade the version of Zinc we integrate with for 5.6 or the next release.

**Comment by jvican** [comment]
> bloop doesn't support builds against multiple JDK versions (say: different source sets / artifacts built against Java 8 and/or 11 or 12 or ...)
  
What kind of support are you thinking about? Bloop allows build targets to tweak java options and java home, so it should be possible to do that. Feel free to drop by our Gitter channel to continue this discussion (I don't want to spam this thread 😛 ) https://gitter.im/scalacenter/bloop
  
>  So developers have to use both Gradle (to get the bloop configuration) and bloop on the command line to compile it. It also requires a manual setup of Bloop, which can be quite error prone, especially if you're dealing with different versions/projects and want to keep stuff separate.
  
Yes, at the moment these two steps need to be run independently. That would be solved by a built-in integration. However if you're intending to use bloop in your gradle build via Metals, note that [Metals](https://scalameta.org/metals/) will have its in next version an "Import from Gradle" command that will automatically import your build.

**Comment by rpalcolea** [comment]
This is part of 6.x nightly -> https://github.com/gradle/gradle/pull/9573

**Comment by eyalroth** [comment]
@rpalcolea I see. It doesn't seem to be all that stable (regardless of Scala). I guess I'll wait for the RC.

**Comment by eyalroth** [comment]
Upgraded to 6.0-rc1 and was able to compile a project on WSL but not on native Windows. 

First I got access denied on some JNI file:
```
C:\Users\eyal\repos\java-scala-gradle-project>gradlew.bat build

> Task :common:compileScala
## Exception when compiling 3 sources to C:\Users\eyal\repos\java-scala-gradle-project\common\build\classes\scala\main
java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/win32-x86-64/jnidispatch.dll library: Access is denied
com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962)
com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
com.sun.jna.Native.<clinit>(Native.java:190)
com.sun.jna.platform.win32.Kernel32.<clinit>(Kernel32.java:42)
sbt.internal.io.WinMilli$.getHandle(Milli.scala:264)
sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:289)
sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:260)
sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:61)
sbt.internal.io.Milli$.getModifiedTime(Milli.scala:360)
sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:12)
sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
sbt.internal.io.Retry$.impl$1(Retry.scala:38)
sbt.internal.io.Retry$.apply(Retry.scala:52)
sbt.internal.io.Retry$.apply(Retry.scala:24)
sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
sbt.internal.inc.caching.ClasspathCache$.fromCacheOrHash$1(ClasspathCache.scala:44)
sbt.internal.inc.caching.ClasspathCache$.$anonfun$hashClasspath$1(ClasspathCache.scala:53)
scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:656)
scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:647)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:436)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


> Task :common:compileScala FAILED
== Build Time Summary ==
??????????????????????????????????????? 100% :common:compileScala (0:29.314)

== BUILD FAILED ==

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:compileScala'.
> Failed to create temporary file for /com/sun/jna/win32-x86-64/jnidispatch.dll library: Access is denied

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 34s
1 actionable task: 1 executed
```

And on subsequent build I got Kernel32 initialization error:
```
C:\Users\eyal\repos\java-scala-gradle-project>gradlew.bat build

> Task :common:compileScala FAILED
## Exception when compiling 3 sources to C:\Users\eyal\repos\java-scala-gradle-project\common\build\classes\scala\main
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.win32.Kernel32
sbt.internal.io.WinMilli$.getHandle(Milli.scala:264)
sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:289)
sbt.internal.io.WinMilli$.getModifiedTimeNative(Milli.scala:260)
sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:61)
sbt.internal.io.Milli$.getModifiedTime(Milli.scala:360)
sbt.io.IO$.$anonfun$getModifiedTimeOrZero$1(IO.scala:1373)
scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:12)
sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
sbt.internal.io.Retry$.impl$1(Retry.scala:38)
sbt.internal.io.Retry$.apply(Retry.scala:52)
sbt.internal.io.Retry$.apply(Retry.scala:24)
sbt.io.IO$.getModifiedTimeOrZero(IO.scala:1373)
sbt.internal.inc.caching.ClasspathCache$.fromCacheOrHash$1(ClasspathCache.scala:44)
sbt.internal.inc.caching.ClasspathCache$.$anonfun$hashClasspath$1(ClasspathCache.scala:53)
scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:656)
scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:647)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:436)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:436)
java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

== Build Time Summary ==
??????????????????????????????????????? 100% :common:compileScala (0:02.490)

== BUILD FAILED ==

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:compileScala'.
> Could not initialize class com.sun.jna.platform.win32.Kernel32

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
1 actionable task: 1 executed
```

Full version info:
```
C:\Users\eyal\repos\java-scala-gradle-project>gradlew.bat --version

------------------------------------------------------------
Gradle 6.0-rc-1
------------------------------------------------------------

Build time:   2019-10-18 19:24:16 UTC
Revision:     5ed5fea1446b3300afa321c661d6e865ab3157a1

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 10 10.0 amd64
```

**Comment by eyalroth** [comment]
Also, 2.13 compilation fails on WSL with a pretty straightforward exception:
```
eyal@eyal:~/eyal/repos/java-scala-gradle-project$ ./gradlew build
> Task :common:compileScala FAILED
== Build Time Summary ==
99% :common:compileScala (0:00.174)

== BUILD FAILED ==

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:compileScala'.
> The version of 'scala-library' was changed while using the default Zinc version. Version 2.13.0 is not compatible with org.scala-sbt:zinc_2.12:1.3.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
1 actionable task: 1 executed
```

Version info:
```
eyal@eyal:~/eyal/repos/java-scala-gradle-project$ ./gradlew --version

------------------------------------------------------------
Gradle 6.0-rc-1
------------------------------------------------------------

Build time:   2019-10-18 19:24:16 UTC
Revision:     5ed5fea1446b3300afa321c661d6e865ab3157a1

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Linux 4.4.0-18362-Microsoft amd64
```
