### ISSUE TITLE
Could not set system property in the new Checkstyle task and finally failed by NPE when using "ENTITY" feature in configuration files

### ISSUE THREAD

**Issue by payneChen** [gradle/gradle#21624]
### Expected Behavior
```
checkstyle {
  systemProperty 'checkstyle.enableExternalDtdLoad', 'true'
}
```
### Current Behavior
No way to set system property since new checkstyle task would create new processes on its own, finally checkstyle would fail when using "ENTITY" feature.
> Caused by: org.apache.tools.ant.BuildException: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "this.fTableOfNOTATIONAttributeNames" is null
--

### Context & Steps to Reproduce 
Here is the example:
https://checkstyle.sourceforge.io/config_system_properties.html#Enable_External_DTD_load

When setting up checkstyle configuration xml files as the example, checkstyle would be failed by NPE since no way to set system properties "checkstyle.enableExternalDtdLoad=true" for the isolated processes.

### Your Environment
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.14 (SAP SE 11.0.14+9-LTS-sapmachine)
OS:           Mac OS X 12.5.1 x86_64

**Comment by asodja** [comment]
Thanks for the report and sorry you are having trouble with Gradle 7.5.1.

Could you maybe try if it works if you pass a property as a [config property](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:configProperties)? 

Something like:
```
checkstyle {
    configProperties = ['checkstyle.enableExternalDtdLoad': 'true']
}
```

**Comment by payneChen** [comment]
> Thanks for the report and sorry you are having trouble with Gradle 7.5.1.
> 
> Could you maybe try if it works if you pass a property as a [config property](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:configProperties)? Something like:
> 
> ```
> checkstyle {
>     configProperties = ['checkstyle.enableExternalDtdLoad': 'true']
> }
> ```

I have tried but it does not help, looks `configProperties` is mostly used for the properties in https://checkstyle.org/config.html, but not for https://checkstyle.org/config_system_properties.html.

**Comment by asodja** [comment]
We will have to add this option then, I don't think we can workaround it anyway with 7.5 :/.

**Comment by payneChen** [comment]
> We will have to add this option then, I don't think we can workaround it anyway with 7.5 unfortunately.

Thanks, is it possible to be fixed in new patch and release like 7.5.2 in one or two week? Since we are preparing and trying to pick up one new gradle version for the half year usage, if the answer is no, we may roll back to 7.4.2.

Regards
Payne

**Comment by asodja** [comment]
After some discussion: we won't release 7.5.2, since 7.6 is planned for September (🤞). So I think it makes sense for you to wait for 7.6. Would that work for you?

**Comment by payneChen** [comment]
> After some discussion: we won't release 7.5.2, since 7.6 is planned for September (🤞). So I think it makes sense for you to wait for 7.6. Would that work for you?

Is it in the beginning of September or in the end of September? Since we are preparing the internal release which is planned in the beginning of Oct and hope the testing including new Gradle version could be done in Sep.

**Comment by asodja** [comment]
Sorry for late reply. From still opened issues it seems like the second part of September.
