### ISSUE TITLE
Gradle doesn't get POM dependency from plugin

### ISSUE THREAD

**Issue by LikeTheSalad** [gradle/gradle#21638]
I have a [Gradle plugin](https://github.com/LikeTheSalad/android-stem) for which I recently released a new version, 2.2.0, and for this version I manually built its POM dependencies, because I started to use the Shadow plugin to include some of my subprojects into the main artifact. The thing is that, there's one subproject called `common-tools` that isn't added to the fat jar, so I added it to the [POM file](https://oss.sonatype.org/service/local/repositories/releases/content/com/likethesalad/android/stem-plugin/2.2.0/stem-plugin-2.2.0.pom) of the main artifact. However, when I add this plugin to a consumer project, Gradle throws a "NoClassDefFoundError" error because it couldn't find a class which is part of `common-tools`. However, it is strange because, `common-tools` is listed in the dependencies for the main artifact, so, shouldn't the dependencies be fetched before starting the Gradle configuration process?

### Expected Behavior
That Gradle would read and fetch all the dependencies from my artifact's [POM file](https://oss.sonatype.org/service/local/repositories/releases/content/com/likethesalad/android/stem-plugin/2.2.0/stem-plugin-2.2.0.pom) before starting its configuration of the project process.

### Current Behavior

Apparently the dependency listed in the POM file, named `common-tools` isn't being fetched in time, or ever.

### Steps to Reproduce 

Apply this plugin in an android application project: [`com.likethesalad.stem`](https://plugins.gradle.org/plugin/com.likethesalad.stem) version 2.2.0. And trigger the Gradle "load changes" action.

### Your Environment

Build scan URL: https://scans.gradle.com/s/b5dyxlaljbeai

**Comment by ljacomet** [comment]
The problem is that you are publishing your plugin to [the Gradle plugin](https://plugins.gradle.org/m2/com/likethesalad/android/stem-plugin/2.2.0/) portal as well. And there it is published with a Gradle Module Metadata file, which is what Gradle consumes.

So all your dependency manipulations must be done on the published variants and not directly on the POM, otherwise your metadata are not consistent.
