### ISSUE TITLE
allprojects / subprojects closure delegation results in unexpected multiproject configuration

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#2163]
Given a multiproject build with the following 2 build scripts:

**root/build.gradle**:

    apply plugin: 'groovy'

    allprojects {
        repositories {
          mavenCentral()
        }
        test {
            exclude '**/*SystemTest.class'
        }
    }

and 

**root/sub/build.gradle**:

    apply plugin: 'groovy'
    dependencies {
        testCompile "junit:junit:4.12"
    }

the test task configuration for the `sub` project is not applied. Instead the `test` task of the root project is referenced as when the configuration block is evaluated no test task for the subproject yet exists. 
This is misleading and counter intuitive. IMO gradle should be stricter here and fail early when a task referenced in the subproject closure is not found in the subproject itself but delegating to   

Currently there are two workarounds I can think of:

1. Add `evaluationDependsOnChildren` to the root build.gradle file.
2. wrap test task configuration in a `plugins.withType` block. 

### Expected Behavior
two options I see to improve this:

1. be smart and detect required configuration ordering (seems quite tricky)
2. fail early here and require the configured task to exist for this particular subproject.
 
### Current Behavior
root projects task is configured and not the subprojects task, resulting in misleading behaviour.

**Comment by big-guy** [comment]
Has this behavior changed recently?
