### ISSUE TITLE
[Question] About ProviderFactory#gradleProperty method

### ISSUE THREAD

**Issue by ahamana** [gradle/gradle#21651]
Can we get properties from "gradle.properties" of a sub-project through the ProviderFactory#gradleProperty method?

### Current Behavior
```
* Project Structure
├── settings.gradle.kts
├── build.gradle.kts
├── gradle.properties
└── sub
       ├── build.gradle.kts
       └── gradle.properties
```

```
* Sub-project task
tasks.register("hello") {
    doLast {
        println("Root property (from ProviderFactory#gradleProperty) is " + providers.gradleProperty("root.foo.bar").orElse("not found").get())
        println("Sub-project's property (from ProviderFactory#gradleProperty) is " + providers.gradleProperty("sub.baz.qux").orElse("not found").get())
        println("Sub-project's property (from Project#findProperty) is " + findProperty("sub.baz.qux").toString())
    }
}

* Output
$ gradlew.bat :sub:hello

> Task :sub:hello
Root property (from ProviderFactory#gradleProperty) is foo.bar
Sub-project's property (from ProviderFactory#gradleProperty) is not found
Sub-project's property (from Project#findProperty) is baz.qux
```

### Steps to Reproduce 
[root.zip](https://github.com/gradle/gradle/files/9417388/root.zip)

### Your Environment
Gradle: 7.5.1

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

---

No, you can't read the properties of a subproject, from the parent project. Not how the model works.

**Comment by Goooler** [comment]
Duplicate of #13302
