### ISSUE TITLE
Validate unknown implementation snapshots earlier

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#21692]
We currently validate that implementations of units of work are known in `ValidateStep`. Though we could do the validation already when we try to create the implementation snapshot, since the build would fail anyway when trying to use an unknown implementation.
When doing this, we need to make sure that the error message still points to the right location, e.g. the task implementation or the input property we are currently snapshotting.

---
cc: @gradle/bt-execution

**Comment by lptr** [comment]
As discussed, one downside with turning the validation error into an exception is that the user will not be able to learn about other errors and warnings until they fix this one.

The benefit of doing this is that we'll simplify the code by eliminating the need to track unknown implementations.

**Comment by lptr** [comment]
Let's do this when we bump into it again, if we ever do.
