### ISSUE TITLE
but it can't be used as a project dependency because it isn't intended for consumption by other components.

### ISSUE THREAD

**Issue by venkateshwarlu808** [gradle/gradle#21691]
HI ,

I am facing below issue .

 Could not resolve project :xxxxxxxxejb.
     Required by:
         project :xxxxxxxxxxxear
      > Selected configuration '**implementation**' on 'project :xxxxxxxxxejb' but it can't be used as a project dependency because it isn't intended for consumption by other components.

Kinldy help on this .

Venkat.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
