### ISSUE TITLE
18.0.2 coming up as incompatible with 7.5.1

### ISSUE THREAD

**Issue by JT122406** [gradle/gradle#21694]
IntellIJ Keeps saying that JDK 18.0.2 isn't compatible with Gradle 7.5.1
(JDK 18.0.2 isn't compatible with Gradle 7.5.1. Please fix JAVA_HOME environment variable.)

### Expected Behavior

Based on 7.5/7.5.1 Change log 18.0.x should be supported no issues

### Current Behavior

JDK 18.0.2 isn't compatible with Gradle 7.5.1. Please fix JAVA_HOME environment variable.

### Context

Is just very annoying as it then defaults to JDK 11 which doesn't work for my project that requires newer JDK Versions

### Steps to Reproduce 

Load Gradle 7.5.1 with JDK 18

### Your Environment

Build scan URL:

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the core of the Gradle Build Tool.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/

**Comment by nskvortsov** [comment]
Related issue in JetBrains tracker: https://youtrack.jetbrains.com/issue/IDEA-299557
