### ISSUE TITLE
Can't exclude composite build tasks

### ISSUE THREAD

**Issue by tomasAlabes** [gradle/gradle#21708]
### Expected Behavior
We should be able to exclude a composite build task, as stated in [the docs](https://docs.gradle.org/current/userguide/composite_builds.html#interacting_with_composite_builds)

### Current Behavior

Using [gradle's sample project](https://docs.gradle.org/current/samples/sample_structuring_software_projects.html) (without touching anything):

```shell
❯ ./gradlew :server-application:build -x :server-application:test

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':domain-model:release'.
> A problem occurred configuring project ':server-application:app'.
   > This build's work graph is currently in use by another thread.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

### Context

In my own project I can't do this either, either because of the above error or because of:

```shell
> Expected vintage state of build 'spring-app' to be in state SettingsLoaded or later but is in state SettingsLoaded and transitioning to Configured.
```

I stopped all gradle daemons but it didn't help.

### Steps to Reproduce 

Download gradle's sample project: https://docs.gradle.org/current/samples/zips/sample_structuring_software_projects-kotlin-dsl.zip
And run `./gradlew :server-application:build -x :server-application:test`

### Your Environment

Gradle: 7.5.1
Kotlin: 1.6.21
OS: MacOS Monterey 12.5 (M1 Pro)

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/21835
