### ISSUE TITLE
Sub modules are not included in the project if these modules end with the same name

### ISSUE THREAD

**Issue by ddivin-sc** [gradle/gradle#21730]
I have the following multiproject structure

```
<root>
 |
 +- app
 |  |
 |  +- src/java/Main.java
 |  |
 |  +- build.gralde
 |
 +-libs
 |  |
 |  +- lib
 |  |   |
 |  |   +- module
 |  |        |
 |  |        +- src/java/A.java
 |  |        |
 |  |        +- build.gradle
 |  |
 |  +- lib2
 |      |
 |      +- module
 |           |
 |           +- src/java/B.java
 |           |
 |           +- build.gradle
 |
 +- build.gradle
 |
 +- settings.gradle
```

app depends on the following submoudles

```
implementation project(":libs:lib2:module")
implementation project(":libs:lib:module")
```

I get the following compilation error when I can trying to build subproject

```
> Task :app:compileJava FAILED
~/sources/gradle-test/test/app/src/main/java/Main.java:5: error: cannot find symbol
      A a = new A();
      ^
  symbol:   class A
  location: class Main
~/sources/gradle-test/test/app/src/main/java/Main.java:5: error: cannot find symbol
      A a = new A();
                ^
  symbol:   class A
  location: class Main
2 errors
```

But If I swap these sub modules dependencies in the application build script

```
implementation project(":libs:lib:module")
implementation project(":libs:lib2:module")
```

I get another compilation error

```
> Task :app:compileJava FAILED
~/sources/gradle-test/test/app/src/main/java/Main.java:4: error: cannot find symbol
      B b = new B();
      ^
  symbol:   class B
  location: class Main
~/sources/gradle-test/test/app/src/main/java/Main.java:4: error: cannot find symbol
      B b = new B();
                ^
  symbol:   class B
  location: class Main
2 errors
```

I have the following assumption: if two or more submodules are included with the same name at the end, then only the last one is included

### Expected Behavior
I expect the project to build successfully

### Current Behavior
Compilation failed

### Steps to Reproduce 
- Unzip attached example [test.zip](https://github.com/gradle/gradle/files/9450005/test.zip)
- Trying to build the multiproject

### Your Environment
- java version "17.0.4" 2022-07-19 LTS
- Gradle 7.5.1
- macOS Monterey 12.4
Build scan URL: https://gradle.com/s/xvbeoxfgo6fqs

**Comment by jbartok** [comment]
Duplicates #16986
