### ISSUE TITLE
Configuration cache should report Task.getProject access inside Task.onlyIf, TaskOutputs.cacheIf, and TasksOutputs.upToDateWhen predicates

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#21742]
Currently, the configuration cache forbids calling `Task.getProject`, but at execution time only. This means that the restriction only applies to code inside task actions (`@TaskAction` and `doFirst`/`doLast` callbacks). The motivation is that the returned `Project` is not completely functional when restoring the build from the cache entry. However, task actions aren't the only user code that is executed when running from the cache. `onlyIf` predicates are also executed before running the task to determine if it should be skipped. The predicate has access to the `Task` instance and may invoke `getProject` on it. Consider the following snippet:
```gradle
project.ext.skipTaskIfSet = true

tasks.register("myTask") {
  onlyIf { task ->
    !task.project.hasProperty("skipTaskIfSet")
  }
}
```

and run `myTask` it twice with the configuration cache enabled.

### Expected Behavior
The first build fails because of illegal `Task.getProject` access. Alternatively, both builds skip the task.

### Current Behavior
The first build skips the task, stores the configuration cache. 
```
Configuration cache is an incubating feature.
Calculating task graph as no configuration cache is available for tasks: myTask
> Task :myTask SKIPPED

BUILD SUCCESSFUL in 1s
Configuration cache entry stored.

```
The second build reuses the cache, but runs the task.
```
Configuration cache is an incubating feature.
Reusing configuration cache.
> Task :myTask UP-TO-DATE

BUILD SUCCESSFUL in 796ms
Configuration cache entry reused.
```
### Steps to Reproduce 
1. Run `gradle --configuration-cache --console=plain myTask` with the build file provided above. 
2. Run `gradle --configuration-cache --console=plain myTask` one more time.

**Comment by mlopatkin** [comment]
The same logic actually applies to `TaskOutputs.cacheIf` and `TaskOutputs.upToDateWhen` predicates, though the reproducer is more involved, especially for the `cacheIf`.

**Comment by h0tk3y** [comment]
Fixed by https://github.com/gradle/gradle/pull/23210
