### ISSUE TITLE
CCH22-Example-1: Adjust the `snippets/dependencyManagement/customizingResolution-attributeSubstitutionRule` sample for configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#21766]
The sample project located under `subprojects/docs/src/snippets/dependencyManagement/customizingResolution-attributeSubstitutionRule` does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-dependency-management-customizing-resolution-attribute-substitution-rule_groovy_resolve.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-attribute-substitution-rule_groovy_resolve.sample)
    ```
    Could not get unknown property 'configurations' for task ':consumer:resolve' of type org.gradle.api.DefaultTask.
    ```

* `snippet-dependency-management-customizing-resolution-attribute-substitution-rule_kotlin_resolve.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-attribute-substitution-rule_kotlin_resolve.sample)
    ```
    Task `:consumer:resolve` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-dependency-management-customizing-resolution-attribute-substitution-rule_groovy_resolve.sample" \
    --tests "*snippet-dependency-management-customizing-resolution-attribute-substitution-rule_kotlin_resolve.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/resolution_rules.adoc`;

**Comment by mlopatkin** [comment]
Fixed in #21555.

**Comment by bamboo** [comment]
I want to work on this.

**Comment by mlopatkin** [comment]
> I want to work on this.

Go ahead, good luck!
