### ISSUE TITLE
Support setting Jigsaw module version in jar task

### ISSUE THREAD

**Issue by jyemin** [gradle/gradle#2177]
The module version is a class attribute of the module-info class for the module and is accessible from java.lang.module.ModuleDescriptor#rawVersion and java.lang.module.ModuleDescriptor#version.  See [the Jigsaw language spec extension](http://cr.openjdk.java.net/~mr/jigsaw/spec/lang-vm.html#jigsaw-2.2) for details.

The jar tool in Java 9 supports setting the module version with the --module-version command line option.  

The jar task in Gradle should do the same.

For reference: this functionality is implemented in Open JDK's jar tool via the sun.tools.jar.Main class in the jdk.jartool module, which relies on the jdk.internal.module.ModuleInfoExtender class in the java.base module (which exports jdk.internal.module to jdk.jartool).

**Comment by jjohannes** [comment]
The `JavaCompile` task in 6.4 supports setting the `Version` (and `MainClass`) attributes of `module-info.class` during compilation. It defaults to the project version, if set.

Eexample (version in project):
```
version = "0.9-beta"
compileJava {
    modularClasspathHandling.inferModulePath.set(true)
}
```

Example (setting version on task):
```
tasks.compileJava {
    modularClasspathHandling.inferModulePath.set(true)
    options.javaModuleVersion.set("0.9-beta")
    options.javaModuleMainClass.set("org.some.Main")
}
```
