### ISSUE TITLE
gradlew init should set parallel and caching to true

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#21786]
If you create a new project using `./gradlew init`, it currently creates a project that has `org.gradle.caching=false` and `org.gradle.parallel=false` since those are the default values for Gradle. Given these are brand new projects and these newly initialized projects are compatible with both parallel execution and caching, we should just set these values in `gradle.properties`

**Comment by jbartok** [comment]
Sounds reasonable as long as the user opts in for the incubating features in the generator options.

**Comment by liutikas** [comment]
These are *not* incubating features. They should always be on for new projects.

**Comment by jbartok** [comment]
Parallel and caching are not enabled in Gradle by default (generally speaking), so `build init` also doesn't set them by default. That is why we should put them now behind the incubating flag.
