### ISSUE TITLE
"withVariantReselection" API broken

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#21781]
### Expected Behavior

The[ "withVariantReselection" API](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ArtifactView.ViewConfiguration.html) should work and the [demo project](https://github.com/gradle/source-resolution-demo) should work.
### Current Behavior

The demo project doesn't work and the API is broken.
### Context

Android Gradle Plugin is trying to integrate that API to have better support of reading javadoc and source from Android Studio.
### Steps to Reproduce 

It can be easily reproduced with the demo project.

**Comment by DPUkyle** [comment]
@bingranl I doublechecked the instructions in the [demo project](https://github.com/gradle/source-resolution-demo)'s README and it's now working fine for me. I think @big-guy had to make two or three small changes after you reported this issue.

Please give it another try and confirm the example is working for you.

**Comment by bingranl** [comment]
Yeah, this works for me now. Thanks!

**Comment by bingranl** [comment]
Actually the demo is not using a normal nightly version but with `gradle-7.6-branch-sg_76_artifact_resolution-20220831231945+0000`. So if I use the latest nightly version, it won't work. So I wonder if the fix is checked in to main? @big-guy

**Comment by big-guy** [comment]
@bingranl the changes were merged yesterday and will be in a nightly shortly

**Comment by bingranl** [comment]
Thanks for the updates, @big-guy !
