### ISSUE TITLE
Report deprecation of Provider.forUseAtConfigurationTime()

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#21796]
It is already soft deprecated (`@Deprecated` annotation).
This issue is about adding deprecation reporting/logging for invocations.

This issue needs to be fixed and a KGP version available with the fix before we can add the nagging.

* [KT-53823 - Kotlin Gradle Plugin uses deprecated Gradle API: Provider.forUseAtConfigurationTime()
](https://youtrack.jetbrains.com/issue/KT-53823)

This issue in the Protobuf plugin needs to be fixed first:
* https://github.com/google/osdetector-gradle-plugin/issues/29

All requirements have been met, this is actionable!

**Comment by eskatos** [comment]
This can't be done just yet as the Kotlin Gradle Plugin still uses that function
https://youtrack.jetbrains.com/issue/KT-53823/Kotlin-Gradle-Plugin-uses-deprecated-Gradle-API-ProviderforUseAtConfigurationTime

**Comment by yogurtearl** [comment]
KT-53823 is marked as fixed in `1.8.0-Beta-49`

**Comment by ljacomet** [comment]
@gradle/bt-configuration-cache Pre-requisites are handled. Could you add this in 8.2?

**Comment by ejona86** [comment]
https://github.com/google/protobuf-gradle-plugin/releases/tag/v0.9.3 just released and upgraded the dependency of osdetector-gradle-plugin to the fixed version.

**Comment by eskatos** [comment]
Thank you @ejona86!
