### ISSUE TITLE
De-incubate or remove ExternalPluginValidationPlugin

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#21792]
the `@Incubating` type `org.gradle.plugin.devel.plugins.ExternalPluginValidationPlugin` is part of the public API, but is not documented. It is unclear how this plugin is useful to users, but it is used by some external plugins currently.

We should either de-incubate and document it, or move it to a Gradle build-only scope.

**Comment by lptr** [comment]
According to https://cs.github.com/?scopeName=All+repos&scope=&q=validate-external-gradle-plugin it is used by (apart from our smoke tests):

- @bigdaz (we know this guy): https://cs.github.com/bigdaz/gradle-plugin-verification/blob/441d4887f9592f9917d487bdd7361a7253bd8f3b/verified-plugins/validate-plugin-init.gradle?q=validate-external-gradle-plugin#L2
- Kotlin Gradle plugin: https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin-integration-tests/src/test/kotlin/org/jetbrains/kotlin/gradle/SimpleKotlinGradleIT.kt#L234-L249

**Comment by bigdaz** [comment]
My project that references this was just an experiment and I'm not at all concerned if the type is removed.

**Comment by lptr** [comment]
Thanks @daz. I talked to the JetBrains team, and something like this will allow them to remove the problematic integration test, too:

https://gist.github.com/lptr/4d456815e10127fa3b5bac1e5988f1cb
