### ISSUE TITLE
CCH22-7: Adjust the `snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule` sample for configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#21804]
The sample project located under [`subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/dependencyManagement/customizingResolution-classifierSubstitutionRule) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-dependency-management-customizing-resolution-classifier-substitution-rule_groovy_resolve.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-classifier-substitution-rule_groovy_resolve.sample)
    ```
    Could not find co.paralleluniverse:quasar-core:0.7.12_r3.
    ```

* `snippet-dependency-management-customizing-resolution-classifier-substitution-rule_kotlin_resolve.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-dependency-management-customizing-resolution-classifier-substitution-rule_kotlin_resolve.sample)
    ```
    Could not find co.paralleluniverse:quasar-core:0.7.12_r3.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-dependency-management-customizing-resolution-classifier-substitution-rule_groovy_resolve.sample" \
    --tests "*snippet-dependency-management-customizing-resolution-classifier-substitution-rule_kotlin_resolve.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/resolution_rules.adoc`;

**Comment by p1729** [comment]
@h0tk3y I would like to work on this. Could you please assign this to me?

**Comment by bamboo** [comment]
Hi, @p1729. Take it away!

**Comment by p1729** [comment]
@bamboo I made a [commit](https://github.com/p1729/gradle/commit/25c44a55a321a2d457a5704f8a31c84d339b368a) which seems to fix the problem. However, if I uncomment `inputs.files(classpath)` the fix fails. Could you please guide me on the issue?

**Comment by h0tk3y** [comment]
Let me take a look!

**Comment by h0tk3y** [comment]
@p1729 It seems that the dependency in the `:lib` project cannot be resolved from the Maven Central repository. This interferes with configuration cache trying to serialize the inputs of the `:lib`'s tasks as well (since those appear on the task graph for `:consumer:resolve`). I'd suggest replacing the `:lib`'s dependency `implementation("co.paralleluniverse:quasar-core:0.7.12_r3:jdk8")` version to something that can be found in Maven Central. It works fine for me with `0.7.10`.

**Comment by p1729** [comment]
Thanks, @h0tk3y 👍 . My bad, I missed checking the dependency.
I have raised the PR #22035 and have made the change to the adoc as well.
