### ISSUE TITLE
CCH22-21: Adjust the `snippets/kotlinDsl/multiProjectBuild` sample for configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#21818]
The sample project located under [`subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/kotlinDsl/multiProjectBuild) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build script in the `kotlin` part of the sample project needs to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-kotlin-dsl-multi-project-build_kotlin_build.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket1SnippetsTest/snippet-kotlin-dsl-multi-project-build_kotlin_build.sample)
    ```
    Could not resolve all files for configuration ':domain:compileClasspath'.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-kotlin-dsl-multi-project-build_kotlin_build.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc`;

**Comment by molmsted98** [comment]
Hello, I'd like to work on this one.

**Comment by abstratt** [comment]
@molmsted98 thanks, have fun!

**Comment by hythloda** [comment]
@molmsted98 how's it going? Need any guidance or resources?

**Comment by nevack** [comment]
Hi, I would like to claim this :)

**Comment by abstratt** [comment]
Hack away!

**Comment by nevack** [comment]
Ready for review!
