### ISSUE TITLE
CCH22-18: Adjust the `snippets/java/crossCompilation` sample for configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#21815]
The sample project located under [`subprojects/docs/src/snippets/java/crossCompilation`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/java/crossCompilation) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-java-cross-compilation_groovy_java7CrossCompilation.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-java-cross-compilation_groovy_java7CrossCompilation.sample)
    ```
    Could not get unknown property 'docsDir' for task ':checkJavadocOutput' of type org.gradle.api.DefaultTask.
    ```

* `snippet-java-cross-compilation_kotlin_java7CrossCompilation.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-java-cross-compilation_kotlin_java7CrossCompilation.sample)
    ```
    Task `:checkJavadocOutput` of type `org.gradle.api.DefaultTask`: invocation of 'Task.project' at execution time is unsupported.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-java-cross-compilation_groovy_java7CrossCompilation.sample" \
    --tests "*snippet-java-cross-compilation_kotlin_java7CrossCompilation.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/jvm/building_java_projects.adoc`;

**Comment by nevack** [comment]
Note: https://github.com/gradle/gradle/blob/master/subprojects/docs/build.gradle#L604-L607

**Comment by nevack** [comment]
I have some rather speculative fix for this.
This is hard to test, as this sample requires JDK7 and Linux machine.
JDK7 is not available on modern distros.
By the way, I can claim it and give reviews to take a look at this fix.

**Comment by hythloda** [comment]
Thanks @nevack This one is indeed a different set of challenges.

**Comment by nevack** [comment]
Ready for review!

**Comment by abstratt** [comment]
@bot-gradle test and merge

**Comment by abstratt** [comment]
Looks good - tested under GitPod.
