### ISSUE TITLE
CCH22-15: Adjust the `snippets/files/archiveNaming` sample for configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#21812]
The sample project located under [`subprojects/docs/src/snippets/files/archiveNaming`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/files/archiveNaming) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-files-archive-naming_groovy_archiveNaming.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-files-archive-naming_groovy_archiveNaming.sample)
    ```
    Could not find method relativePath() for arguments [task ':myZip' property 'destinationDirectory'] on task ':myZip' of type org.gradle.api.tasks.bundling.Zip.
    ```

* `snippet-files-archive-naming_kotlin_archiveNaming.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-files-archive-naming_kotlin_archiveNaming.sample)
    ```
    Task `:myZip` of type `org.gradle.api.tasks.bundling.Zip`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-files-archive-naming_groovy_archiveNaming.sample" \
    --tests "*snippet-files-archive-naming_kotlin_archiveNaming.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/authoring-builds/working_with_files.adoc`;

**Comment by gabrielrodriguez2746** [comment]
I want to work in this issue 🤓

**Comment by hythloda** [comment]
Have fun @gabrielrodriguez2746 !

**Comment by gabrielrodriguez2746** [comment]
Sorry I will try to upload a draft pr in around an hour, my bad. I thought I have to wait for the confirmation to start, I am on it 💪

**Comment by gabrielrodriguez2746** [comment]
Jeejeje got it, but I get why you were worried 😅

**Comment by gabrielrodriguez2746** [comment]
I think it will take longer than an hour, I am finishing reading some documentation to work on it actively. Tomorrow morning (GMT+2) time would probably be the pr moment

**Comment by abstratt** [comment]
No worries, @gabrielrodriguez2746 - you were only granted the issue yesterday anyways. Feel free to reach out if you have questions.

**Comment by gabrielrodriguez2746** [comment]
@abstratt here is the pr https://github.com/gradle/gradle/pull/21905
