### ISSUE TITLE
Gradlew behind proxy issue

### ISSUE THREAD

**Issue by oikonomopo** [gradle/gradle#2182]
When executing `gradlew` (gradle wrapper) behind proxy, although proxy settings are provided, some urls are cut and so can't continue my project build!

### Expected Behavior

I (am trying to) develop an ionic mobile app. I use a template project. When i build my project when gradlew runs, should take into account the provided proxy settings, fetch what it needs and continue the build!

### Current Behavior
When i build my project, i have an exception due to gradle wrapper! My proxy is cutting the urls! It should take into account the provided proxy settings, fetch what it needs and continue the build!

### Context

I try to build an `ionic v1` with `ionic CLI v3` mobile app based to a template project on osx/windows

### Steps to Reproduce

Following [ionic start guide](https://github.com/driftyco/ionic-cli):

Provided Node 6 LTS (latest) && npm 3+:

1. `$ npm install -g ionic`

2. Start a new project
```
$ npm install -g ionic@latest
$ ionic start myNewProject blank --type=ionic1
$ cd ./myNewProject
$ ionic serve
```
3. Edit for Android development.
```
$ npm install -g cordova
$ npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
$ ionic cordova --help
$ ionic cordova run android
```
Build fails due to gradlew:
```
➜  android ./gradlew cdvBuildDebug -b /Users/oikonomopo/Projects/myApp/platforms/android/build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m -Pandroid.useDeprecatedNdk=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.2.3.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:2.2.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom'.
               > http://squid.proxy.com
BUILD FAILED
```

### Environment
At terminal ../myApp/platform/android `$ ./gradlew -v `:                                                                                                                                                                     
```
------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------
Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b
Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.12.2 x86_64
```

My proxy settings /Users/oikonomopo/.gradle/gradle-wrapper.properties and  ../gradle.properties:
```
systemProp.http.proxyHost=http://squid.proxy.com
systemProp.http.proxyPort=8080
systemProp.https.proxyHost=http://squid.proxy.com
systemProp.https.proxyPort=8080
```

### Additional info
I can access the url from web browser and from terminal with `wget`! But not with `gradlew`!

I have already tried: https://stackoverflow.com/questions/30219065/gradle-cant-connect-to-maven-repo-through-corporate-proxy-need-to-configure-t/30243902#30243902

Also i 've tried to provide directly proxy settings to command parameters:
`gradlew -Dhttp.proxyHost=http://squid.proxy.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=http://squid.proxy.com -Dhttps.proxyPort=8080  cdvBuildDebug -b /Users/oikonomopo/Projects/myApp/platforms/android/build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m -Pandroid.useDeprecatedNdk=true `

**Comment by oehme** [comment]
> systemProp.http.proxyHost=http://squid.proxy.com

Have you tried using `systemProp.http.proxyHost=squid.proxy.com` instead?

**Comment by basvandenbrink** [comment]
I have similar issues with the Gradle wrapper. Setting the systemProp settings or DEFAULT_JVM_OPTS doesn't work for me, while similar settings do work for SBT and Maven.

**Comment by oehme** [comment]
Please open a new issue with reproduction instructions.

**Comment by RedaZZ** [comment]
Hi everyone i have the same issue oikonomopo has, why this issue was closed without being resolved?

**Comment by oehme** [comment]
The issue was resolved for @oikonomopo. If you have a similar problem, please open a new issue with a reproducible example.
