### ISSUE TITLE
CCH22-23: Adjust the `snippets/tasks/incrementalBuild-customTaskClass` sample for configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#21820]
The sample project located under [`subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/tasks/incrementalBuild-customTaskClass) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-tasks-incremental-build-custom-task-class_groovy_customTaskClassWithInputOutputAnnotations.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_groovy_customTaskClassWithInputOutputAnnotations.sample)
    ```
    Task `:processTemplates` of type `org.example.ProcessTemplates`: invocation of 'Task.project' at execution time is unsupported.
    ```

* `snippet-tasks-incremental-build-custom-task-class_groovy_incrementalAdHocTask.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_groovy_incrementalAdHocTask.sample)
    ```
    Could not find method copy() for arguments [build_5yks5tcxomo6e692nd30tvva1$_run_closure2$_closure9$_closure10@2b7489cb] on task ':processTemplatesAdHoc' of type org.gradle.api.DefaultTask.
    ```

* `snippet-tasks-incremental-build-custom-task-class_groovy_inferredTaskDep2.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_groovy_inferredTaskDep2.sample)
    ```
    Task `:processTemplates` of type `org.example.ProcessTemplates`: invocation of 'Task.project' at execution time is unsupported.
    ```

* `snippet-tasks-incremental-build-custom-task-class_groovy_inferredTaskDep.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_groovy_inferredTaskDep.sample)
    ```
    Task `:packageFiles` of type `org.gradle.api.tasks.bundling.Zip`: cannot serialize object of type 'org.example.ProcessTemplates', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
    Task `:processTemplates` of type `org.example.ProcessTemplates`: invocation of 'Task.project' at execution time is unsupported.
    ```

* `snippet-tasks-incremental-build-custom-task-class_kotlin_customTaskClassWithInputOutputAnnotations.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_kotlin_customTaskClassWithInputOutputAnnotations.sample)
    ```
    Task `:processTemplates` of type `org.example.ProcessTemplates`: invocation of 'Task.project' at execution time is unsupported.
    ```

* `snippet-tasks-incremental-build-custom-task-class_kotlin_incrementalAdHocTaskNoSource.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_kotlin_incrementalAdHocTaskNoSource.sample)
    ```
    Task `:processTemplatesAdHocSkipWhenEmpty` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

* `snippet-tasks-incremental-build-custom-task-class_kotlin_incrementalAdHocTask.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_kotlin_incrementalAdHocTask.sample)
    ```
    Task `:processTemplatesAdHoc` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

* `snippet-tasks-incremental-build-custom-task-class_kotlin_inferredTaskDep2.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_kotlin_inferredTaskDep2.sample)
    ```
    Task `:processTemplates` of type `org.example.ProcessTemplates`: invocation of 'Task.project' at execution time is unsupported.
    ```

* `snippet-tasks-incremental-build-custom-task-class_kotlin_inferredTaskDep.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-build-custom-task-class_kotlin_inferredTaskDep.sample)
    ```
    Task `:packageFiles` of type `org.gradle.api.tasks.bundling.Zip`: cannot serialize object of type 'org.example.ProcessTemplates', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
    Task `:processTemplates` of type `org.example.ProcessTemplates`: invocation of 'Task.project' at execution time is unsupported.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-tasks-incremental-build-custom-task-class_groovy_customTaskClassWithInputOutputAnnotations.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_groovy_incrementalAdHocTask.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_groovy_inferredTaskDep2.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_groovy_inferredTaskDep.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_kotlin_customTaskClassWithInputOutputAnnotations.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_kotlin_incrementalAdHocTaskNoSource.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_kotlin_incrementalAdHocTask.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_kotlin_inferredTaskDep2.sample" \
    --tests "*snippet-tasks-incremental-build-custom-task-class_kotlin_inferredTaskDep.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/running-builds/performance.adoc`;
- `subprojects/docs/src/docs/userguide/authoring-builds/more_about_tasks.adoc`;

**Comment by vmmaldonadoz** [comment]
I can work on this 😄

**Comment by bamboo** [comment]
Take it away, @vmmaldonadoz!

**Comment by vmmaldonadoz** [comment]
I just created the PR draft https://github.com/gradle/gradle/pull/21965 for fixing this issue. 
I need to add a few comments, but I don't have the time right now to add them. So, I'll do it today as soon as I can and will put the PR ready to review.

**Comment by vmmaldonadoz** [comment]
The PR is ready for review https://github.com/gradle/gradle/pull/21965 🥳

**Comment by abstratt** [comment]
@vmmaldonadoz Just a reminder that your PR needs more work in order to be accepted. Will you have a chance to look into it?

**Comment by vmmaldonadoz** [comment]
@abstratt Sorry for the delay, I've been busy these last few days but I will be able to solve the comments during the weekend.
