### ISSUE TITLE
CCH22-24: Adjust the `snippets/tasks/incrementalTask` sample for configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#21821]
The sample project located under [`subprojects/docs/src/snippets/tasks/incrementalTask`](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/snippets/tasks/incrementalTask) does not meet [the configuration cache requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements).

The build scripts in the `groovy` and `kotlin` parts of the sample project need to be adjusted to follow the requirements.
### Context
This issue is a part of the [Gradle Configuration Cache Hackathon 2022](https://github.com/gradle/cc-hackathon-2022).

If you wish to participate and contribute the fix, please follow [the suggested workflow](https://github.com/gradle/cc-hackathon-2022/blob/main/workflow.md).
### Expected behavior

- The sample project is fixed so that the related documentation tests pass with configuration cache enabled.
- The tests related to this sample project are removed from the `testsToBeFixedForConfigurationCache` list in `subprojects/docs/build.gradle`. You can find the test IDs below.
- The doc pages that include the snippets from this sample project might need to be updated to be consistent with the sample. Feel free to ask the team for help with this! You can find the pages listed below.
### Test failure details
These tests running in `:docs:docsTest` check the sample project and are failing with configuration cache enabled:
* `snippet-tasks-incremental-task_groovy_incrementalTaskChangedProperty.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_groovy_incrementalTaskChangedProperty.sample)
    ```
    Could not find method file() for arguments [inputs] on task ':originalInputs' of type org.gradle.api.DefaultTask.
    ```

* `snippet-tasks-incremental-task_groovy_incrementalTaskFirstRun.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_groovy_incrementalTaskFirstRun.sample)
    ```
    Could not find method file() for arguments [inputs] on task ':originalInputs' of type org.gradle.api.DefaultTask.
    ```

* `snippet-tasks-incremental-task_groovy_incrementalTaskNoChange.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_groovy_incrementalTaskNoChange.sample)
    ```
    Could not find method file() for arguments [inputs] on task ':originalInputs' of type org.gradle.api.DefaultTask.
    ```

* `snippet-tasks-incremental-task_groovy_incrementalTaskRemovedInput.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_groovy_incrementalTaskRemovedInput.sample)
    ```
    Could not find method file() for arguments [inputs] on task ':originalInputs' of type org.gradle.api.DefaultTask.
    ```

* `snippet-tasks-incremental-task_groovy_incrementalTaskRemovedOutput.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_groovy_incrementalTaskRemovedOutput.sample)
    ```
    Could not find method file() for arguments [inputs] on task ':originalInputs' of type org.gradle.api.DefaultTask.
    ```

* `snippet-tasks-incremental-task_groovy_incrementalTaskUpdatedInputs.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_groovy_incrementalTaskUpdatedInputs.sample)
    ```
    Could not find method file() for arguments [inputs] on task ':originalInputs' of type org.gradle.api.DefaultTask.
    ```

* `snippet-tasks-incremental-task_kotlin_incrementalTaskChangedProperty.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_kotlin_incrementalTaskChangedProperty.sample)
    ```
    Task `:originalInputs` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

* `snippet-tasks-incremental-task_kotlin_incrementalTaskFirstRun.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_kotlin_incrementalTaskFirstRun.sample)
    ```
    Task `:originalInputs` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

* `snippet-tasks-incremental-task_kotlin_incrementalTaskNoChange.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_kotlin_incrementalTaskNoChange.sample)
    ```
    Task `:originalInputs` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

* `snippet-tasks-incremental-task_kotlin_incrementalTaskRemovedInput.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_kotlin_incrementalTaskRemovedInput.sample)
    ```
    Task `:originalInputs` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

* `snippet-tasks-incremental-task_kotlin_incrementalTaskRemovedOutput.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_kotlin_incrementalTaskRemovedOutput.sample)
    ```
    Task `:originalInputs` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

* `snippet-tasks-incremental-task_kotlin_incrementalTaskUpdatedInputs.sample`[(Build Scan)](https://ge.gradle.org/s/wkszl3ueqiln2/tests/:docs:docsTest/org.gradle.docs.samples.Bucket2SnippetsTest/snippet-tasks-incremental-task_kotlin_incrementalTaskUpdatedInputs.sample)
    ```
    Task `:originalInputs` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
    ```

### How to reproduce
To reproduce the failure in the Gradle documentation tests, run the following in the `gradle/gradle`repository:
```sh
./gradlew :docs:docsTest \
    -PrunBrokenConfigurationCacheDocsTests=true \
    -PenableConfigurationCacheForDocsTests=true \
    --tests "*snippet-tasks-incremental-task_groovy_incrementalTaskChangedProperty.sample" \
    --tests "*snippet-tasks-incremental-task_groovy_incrementalTaskFirstRun.sample" \
    --tests "*snippet-tasks-incremental-task_groovy_incrementalTaskNoChange.sample" \
    --tests "*snippet-tasks-incremental-task_groovy_incrementalTaskRemovedInput.sample" \
    --tests "*snippet-tasks-incremental-task_groovy_incrementalTaskRemovedOutput.sample" \
    --tests "*snippet-tasks-incremental-task_groovy_incrementalTaskUpdatedInputs.sample" \
    --tests "*snippet-tasks-incremental-task_kotlin_incrementalTaskChangedProperty.sample" \
    --tests "*snippet-tasks-incremental-task_kotlin_incrementalTaskFirstRun.sample" \
    --tests "*snippet-tasks-incremental-task_kotlin_incrementalTaskNoChange.sample" \
    --tests "*snippet-tasks-incremental-task_kotlin_incrementalTaskRemovedInput.sample" \
    --tests "*snippet-tasks-incremental-task_kotlin_incrementalTaskRemovedOutput.sample" \
    --tests "*snippet-tasks-incremental-task_kotlin_incrementalTaskUpdatedInputs.sample"
```
In the test build outputs, which you can find in the test report, the configuration cache problems are listed along with the URL pointing to the detailed HTML problems report that can help investigating the violation. 
You can find more instructions on working with the sample projects in the [FAQ](https://github.com/gradle/cc-hackathon-2022/blob/main/faq.md).
### Docs including the snippets from this sample project
The following doc pages include the snippets from this sample project: 
- `subprojects/docs/src/docs/userguide/extending-gradle/custom_tasks.adoc`;

**Comment by 3flex** [comment]
I have a fix for this - can I claim this please? FYI I've also requested to claim #21817, as I saw in Slack that the restriction on claiming more than one issue at a time could be loosed a little...

**Comment by hythloda** [comment]
I saw your other submitted PR, so this one is ready for you to claim too.  Have fun!

**Comment by 3flex** [comment]
Ready for review: #21896
