### ISSUE TITLE
Support CodeQualityPlugins as a cacheable task

### ISSUE THREAD

**Issue by fkorotkov** [gradle/gradle#2184]
I don't see a reason why `AbstractCodeQualityPlugin` shouldn't provide a cacheable tasks. For now if someone uses let's say FindBugs it will be always executed and not cached when I run `./gradlew check`

**Comment by big-guy** [comment]
FindBugs, Checkstyle, CodeNarc, and Pmd all are.

e.g.: https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/FindBugs.java#L68
