### ISSUE TITLE
7.5+ - Eclipse cannot resolve types from projects with text fixtures

### ISSUE THREAD

**Issue by mweber03** [gradle/gradle#21853]
Classes from `src/main/java` in projects containing text fixtures can no longer be resolved in Eclipse (i.e. `Xyz cannot be resolved to a type`). It works with 7.4.2, but does not work with 7.5 or 7.5.1.

### Expected Behavior
Eclipse should be able to resolve the classes, as it previously did.

### Current Behavior
The classes from `src/main/java` cannot be resolved in Eclipse.

### Steps to Reproduce 
1. Clone https://github.com/mweber03/gradle-test
2. Import into Eclipse
4. In Eclipse, `Gradle > Refresh Gradle Project` (note the clean build, no red Xs on classes)
5. Upgrade project to Gradle 7.5.1 (`./gradlew wrapper --gradle-version 7.5.1`)
6. In Eclipse, `Gradle > Refresh Gradle Project` (note classes can no longer be resolved)

### Your Environment
Build scan URL: https://gradle.com/s/lpfpi33q6j54o

**Comment by mweber03** [comment]
Not sure if this is a Gradle or Buildship issue, so I wrote up the Issue in both: https://github.com/eclipse/buildship/issues/1201

**Comment by donat** [comment]
This is expected. In Gradle 7.5 we improved classpath separation for Eclipse. Gradle and Buildship now rely on the `test` and the `without_test_code` classpath attributes when generating projects, source directories, and dependencies in the Eclipse workspace.

In your case, the build script declares a dependency to a project in the `implementation` and in the `testImplementation` configuration as well. The former is mapped to project dependency with a `test=false` classpath attribute, whereas the latter needs a ` test=true` classpath attribute. It was a design decision to use `test=true` in this case. It might not be ideal but the alternative is equally problematic.

You can fix your setup by adjusting the classpath attributes in your build script in the `eclipse.classpath.file.whenMerged{}` block. Also, you can read more about test separation in the [Gradle 7.5 release notes](https://docs.gradle.org/7.5/release-notes.html).

**Comment by jokimaki** [comment]
I have a similar setup with an implementation dependency and a testImplementation dependency to the same project. While debugging with `eclipse.classpath.file.whenMerged{}` it showed that there would be classpath entries for both. It took me some time to notice that there was however only one entry for the project in Java Build Path > Libraries > Project and External Dependencies. That entry had `Visible only for test sources: Yes`, which of course caused that the main sources were not visible and the project wouldn't compile in Eclipse. So, in my case the solution was to remove the entry with `test=true`. In Groovy DSL:

```
eclipse.classpath.file {
    whenMerged { classpath ->
        def testDependencies = classpath.entries.findAll { entry -> entry instanceof org.gradle.plugins.ide.eclipse.model.ProjectDependency && entry.entryAttributes.test }
        classpath.entries.removeAll testDependencies
    }
}
```

I hope this helps others who run into this issue.

**Comment by AlanMasciangelo** [comment]
@donat Why is the alternative problematic? Isn't this inconsistent with how non test fixture dependencies behave?

**Comment by AlanMasciangelo** [comment]
Thanks @jokimaki! For anyone else, outright removing the entry causes issues in projects that only include the testFixtures for a project. This worked best for me in both cases

```groovy
eclipse.classpath {
    file.whenMerged { classpath ->
        classpath.entries.findAll { entry -> entry instanceof org.gradle.plugins.ide.eclipse.model.ProjectDependency && entry.entryAttributes.test }
        	.each { it.entryAttributes['test'] = 'false' }
	}
}
```

This covers both cases

```gradle
dependencies {
    testImplementation testFixtures(project(':my-project'))
}
```
and 
```gradle
dependencies {
    implementation project(':my-project')
    testImplementation testFixtures(project(':my-project'))
}
```

**Comment by stefanrybacki** [comment]
@donat so you basically rendered text-fixtures non-working for buildship based IDEs? It should be fairly normal to have a dependency like this when using test-fixtures (it is acutally the sample from the gradle documentation):

```
dependencies {
    implementation(project(":lib"))

    testImplementation(testFixtures(project(":lib")))
}
```

**Comment by HerrDerb** [comment]
I also find this very unlucky.

**Comment by flozano** [comment]
> It was a design decision to use test=true in this case. It might not be ideal but the alternative is equally problematic.

I agree about the direction of this decision being somewhat one-sided and prone to cause trouble to any project using this kind of layout (I have many, I can only guess I'm not alone on this)

**Comment by ssi-ips** [comment]
What is the recommended project layout for gradle >=7.5? Test Fixtures in seperate project?
```
dependencies {
    implementation(project(":lib"))

    testImplementation(testFixtures(project(":lib-test-fixtures")))
}
```

Manually editing the classpath is not a good option. At least there should be an option to manually set the `test` flag like there is `containsTestFixtures = true`

**Comment by stefanrybacki** [comment]
@ssi-ips the seperate project solution is the one we are leaning forward to as well, however we rather like to have a real solution by either gradle or buildship. I mean it used to work before with separating classpath in fixtures and main sources. But, I do not have alot of hope this will be fixed, as we can see this ticket is closed as "it is like that, we decided something, deal with it"

**Comment by flozano** [comment]
> as we can see this ticket is closed as "it is like that, we decided something, deal with it"

I still hope the project owners reconsider

**Comment by stefanrybacki** [comment]
I believe we might have more luck here https://github.com/eclipse/buildship/issues/1206 and https://github.com/redhat-developer/vscode-java/issues/2784 as it is more a buildship problem than gradle

**Comment by effad** [comment]
> In your case, the build script declares a dependency to a project in the `implementation` and in the `testImplementation` configuration as well. The former is mapped to project dependency with a `test=false` classpath attribute, whereas the latter needs a ` test=true` classpath attribute. It was a design decision to use `test=true` in this case. It might not be ideal but the alternative is equally problematic.

Why should the alternative be equally problematic? 

You have a dependency with test=false and again with test=true; test means "test only"; Obviously the correct solution in that case to have test=false, because the dependency is NOT only for tests.

I'm seriously fed up with gradle breaking things again and again :-(
