### ISSUE TITLE
Init command does not warn if the current directory is non-empty

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#21867]
Many CLI applications related to creating and managing projects have a command similar to `gradle init`. From the user perspective, each tool arbitrarily chooses whether the command is going to populate the current directory or prompt about creating a new sub-directory. In case of Gradle, the current directory is used and the `init` command does not warn if the directory is not empty. Moreover, it can potentially override existing files or add files to existing directories.

From the user perspective this is very unintuitive and could result into manually figuring out what files and directories where created, if the `init` command was executed in a wrong directory.

The `init` command should detect presence of files in the current directory and warn the user that they could be overwritten.

**Comment by arthursmel** [comment]
Hi Gradle folks 👋 I'd like take this one, thanks!
