### ISSUE TITLE
ProviderFactory: provide a way to get Gradle properties by a prefix

### ISSUE THREAD

**Issue by monosoul** [gradle/gradle#21876]
### Expected Behavior
`ProviderFactory` provides a way to get all Gradle properties by prefix (has a method `Provider<Map<String, String>> gradlePropertiesPrefixedBy(String variableNamePrefix);`).

### Current Behavior
There's no way to get a map of Gradle properties with `ProviderFactory`, neither a full one, nor filtered by the prefix.

### Context

At the moment [ProviderFactory](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java) provides no way to get a list of Gradle properties by a prefix, while there are `systemPropertiesPrefixedBy` and `environmentVariablesPrefixedBy`.

Because of that `ProviderFactory` can't really be considered as an alternative to using `project.properties` when adopting [configuration cache](https://docs.gradle.org/7.5.1/userguide/configuration_cache.html#config_cache:requirements).

I.e. with `Project` I can do something like `project.properties.filterKeys { it.startsWith(prefix) }`, but I can't do the same with `ProviderFactory`.

**Comment by eskatos** [comment]
Thank you for your contribution @monosoul!
[#21877](https://github.com/gradle/gradle/pull/21877) was merged
This will be in Gradle 8.0
