### ISSUE TITLE
Upgrade the embedded Kotlin to 1.7.20

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#21897]
Releases
* https://github.com/JetBrains/kotlin/releases/tag/v1.7.20-Beta

Related
* https://github.com/gradle/gradle/issues/21882

**Comment by franckrasolo** [comment]
Hi @eskatos

Since you're upgrading the embedded Kotlin, could it please be [1.7.21](https://github.com/JetBrains/kotlin/releases/tag/v1.7.21) released a few days ago?

Thanks

**Comment by eskatos** [comment]
Duplicate of https://github.com/gradle/gradle/issues/22101
