### ISSUE TITLE
Add deprecation logging to org.gradle.util.CollectionUtils.stringize(collection)

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#21903]
This could not be done in https://github.com/gradle/gradle/pull/21843 for Gradle 7.6 because the Asciidoctor Gradle Plugin still uses that method via the Grolifant library.

A new release of the Asciidoctor Gradle Plugin with the following fixes needs to happen first:

* https://gitlab.com/ysb33rOrg/grolifant/-/issues/85

asciidoctor-gradle-plugin 4.0.0-alpha-1 is the first version published with the fix
https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/release_4_0_0_alpha_1/gradle.properties#L15

**Comment by eskatos** [comment]
Still no stable version of the asciidoctor plugin with the fix.
Postponing again one last time before adding the nagging.

@ysb33r, any chance you could look into solving this situation on the asciidoctor side of things?

**Comment by ljacomet** [comment]
From a quick look, still no version having the changes. Pushing out.

**Comment by cobexer** [comment]
A [4.0.0 release](https://github.com/asciidoctor/asciidoctor-gradle-plugin/releases/tag/release_4_0_0) of the asciidoctor plugin dropped last friday 🎉
