### ISSUE TITLE
API and implementation separation for Java libraries

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2191]
This epic covers all work required to support API and implementation separation for Java libraries. It's worth noting that it's a follow up to the first milestone, which was the introduction of the [Java Library Plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html) and more specifically separation of API and implementation _dependencies_.

This epic is about separation of API and implementation of the library itself. In particular, we will want to support declaring which classes belong to the API of a library.

This is **not** about supporting Jigsaw modules, nor the `module-info.java` format: this should work
whatever version of the JDK is used.

**Comment by jjohannes** [comment]
Work is now tracked through the [in:api-impl-separation](https://github.com/gradle/gradle/labels/in%3Aapi-impl-separation) label.
