### ISSUE TITLE
How to embed some file after the jar is built?

### ISSUE THREAD

**Issue by wsq93** [gradle/gradle#21924]
I try to migrate a build from Maven. Now, I want to write a script to solve this problem at once. 

It's a bit like what this code does: 
`jar -uf lib.jar readme.md`

However, I tried several times and failed. 

Who can give me a code example? Thank you!

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
