### ISSUE TITLE
Remove timestamps from org/gradle/build-receipt.properties

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#21921]
Inside of gradle distribution zip there is lib/gradle-build-services.jar. This jar contains org/gradle/build-receipt.properties with two build timestamp inside of it. These timestamp are breaking gradle distribution reproducibility (checking out the release sha, running `./gradlew :distributions-full:binDistributionZip -PfinalRelease`).

### Expected Behavior
`./gradlew :distributions-full:binDistributionZip -PfinalRelease` of a release tag of gradle git repository produces identical zip as the one published by gradle.

### Current Behavior
The produced zip contains a jar with a timestamp inside of it

### Context
We want to be able to verify that the binaries shipped by Gradle are exactly what is in the repository for build chain security purposes.

### Steps to Reproduce 
- Clone https://github.com/gradle/gradle
- `./gradlew :distributions-full:binDistributionZip -PfinalRelease`
- Compare `subprojects/distributions-full/build/distributions/gradle-7.5.1-bin.zip` and https://services.gradle.org/distributions/gradle-7.5.1-bin.zip

### Your Environment
N/A

Ideally, the timestamps are not there or the timestamps are checked into the repository.

**Comment by liutikas** [comment]
I was able to find that Gradle property `buildTimestamp` can override it, but that requires downloading gradle published distribution, looking inside of the jar inside of the zip. Ideally, this timestamp is not set at all, especially given that the API that returns it is deprecated and marked to be removed for 8.0.

https://cs.android.com/android-studio/gradle/+/master:subprojects/base-services/src/main/java/org/gradle/util/GradleVersion.java;l=89

**Comment by wolfs** [comment]
Thank you for bringing up this topic!
We currently don't have plans to remove the build timestamp from `build-receipt.properties` and that is also not necessary for reproducible builds. See [this comment](https://github.com/gradle/gradle/pull/21923#issuecomment-1531053118). I'll close the issue now.
