### ISSUE TITLE
No transients at compile time scope

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#21950]
a scope that doesn't import transients

```kts
implementation(libs.spring.boot.autoconfigure)
```

allows me to write

```kt
import org.springframework.beans.factory.config.Scope
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
```

### Expected Behavior

should fail at compile time as I didn't import the correct things

### Current Behavior

compiles

### Context

I want to avoid accidental imports as developers don't often know better. I think for exporting my own modules that I can use `compileOnly` and `runtimeOnly` to avoid accidental exports... though I need to test. If using Java, I could use java modules, but people choose unfortunate languages.

**Comment by jbartok** [comment]
If you want to disable transitive dependencies, you can do it per dependency, or per configuration (for resolvable configurations). Also, you could request from the publisher of "autroconfigure" that it does API-implementation separation (assuming it doesn't do so already).
