### ISSUE TITLE
testAggregateTestReport task is not run when tests fail

### ISSUE THREAD

**Issue by hutchiko** [gradle/gradle#21966]
The Test Report Aggregation Plugin does not generate an aggregated report if any of the dependent Test tasks fail. 

### Expected Behavior

Aggregate test report should be generated regardless of success or failure of test runs. This would mirror the behavior of the reports generated by the individual Test tasks.

It very helpful to see the test report for failed test runs.

### Current Behavior

No Aggregate test report generated when dependent Test tasks fail. 

### Steps to Reproduce 

https://github.com/hutchiko/testAggregateTestReport-bug-report

To reproduce the issue run:

```
./gradlew clean testAggregateTestReport 
```

Note that there is no aggregated report generated: 
```
find build/reports/tests -type f -name index.html | grep aggregated  
```

However there is a non aggregated report:
```
 find build/reports/tests -type f -name index.html  
```

Both an aggregated and non-aggregated report should be generated. These reports are most helpful when tests fail so 
it's vital that the aggregated report is still generated on test failure.

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.

**Comment by hutchiko** [comment]
@jbartok I've added more details on how to reproduce.

**Comment by DPUkyle** [comment]
Hi @hutchiko.  The `test-report-aggregation` plugin can do what you want, but requires the `--continue` flag on the CLI to avoid stopping at the first failed `Test` task.  This is a clear gap in the documentation and I'll file a bug to reconcile this.

I [reran](https://scans.gradle.com/s/msdcqrlvtxsdq) your example and see the aggregated report is available under `build/reports/tests/unit-test/aggregated-results/`.
