### ISSUE TITLE
7.5: mustRunAfter(configuration) causes ActionNode cannot be cast to TaskNode

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#21962]
### Expected Behavior

`Task#mustRunAfter` should work with dependencies on `Configuration`, `Buildable`, etc according to the javadoc.

The use-case is as follows:
1) `allureServe` task launches a web-server that displays test report
2) However, `allureServe` does NOT have `dependsOn("test")` dependency, as it would cause test re-execution on every "start report server", and test execution would be too long

So the approach in `allure-gradle` was to have `mustRunAfter(resultsDir)`, where `resultsDir` is `Property<Configuration>` that aggregates reports from the relevant modules (e.g. it aggregates test execution data from multiple subprojects).

https://github.com/allure-framework/allure-gradle/blob/1d1b0583e319e4f069f0d327bcd7b0c66646c021/allure-base-plugin/src/main/kotlin/io/qameta/allure/gradle/base/tasks/AllureExecTask.kt#L71

Here's where `resultsDir` is populated: https://github.com/allure-framework/allure-gradle/blob/e956a156f3ea5de121925ac77217e7ec4fe1289a/allure-report-plugin/src/main/kotlin/io/qameta/allure/gradle/report/AllureReportPlugin.kt#L93-L125

I just checked and `mustRunAfter(resultsDir)` did work in Gradle 7.4.2
For instance, if I add the following task, then running `./gradlew dependOnBothAllureServeAndTest` does arrange "test first, allureServe last" if `mustRunAfter(resultsDir)` is present.

```kotlin
tasks.register("dependOnBothAllureServeAndTest") {
  dependsOn("allureServe")
  dependsOn("test")
}
```

### Current Behavior

Gradle 7.5.1 fails with `org.gradle.execution.plan.ActionNode cannot be cast to class org.gradle.execution.plan.TaskNode`.
Gradle 7.4.2 works as expected.

### Context

* https://github.com/allure-framework/allure-gradle/issues/90

### Steps to Reproduce 

```sh
git clone https://github.com/allure-framework/allure-gradle
cd allure-gradle/sandbox
update gradle/gradle-wrapper.properties to 7.5.1
./gradlew :dsl-kotlin:allureServe
```

Actual output (see build scan for full output):

```
* What went wrong:
class org.gradle.execution.plan.ActionNode cannot be cast to class org.gradle.execution.plan.TaskNode
(org.gradle.execution.plan.ActionNode and org.gradle.execution.plan.TaskNode are in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @204f30ec)
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/pboyd4r77skuw/failure?expanded-stacktrace=WyIwIl0&focused-stack-frame=0-0#1

**Comment by vlsi** [comment]
The workaround for Gradle 7.5+ is to replace `mustRunAfter(resultsDirs)` with `mustRunAfter(resultsDirs.map { it.elements })`

**Comment by adammurdoch** [comment]
Thanks for reporting the issue. It should be fixed now, via https://github.com/gradle/gradle/pull/22000
