### ISSUE TITLE
Depending on multiple configurations leads to broken buildship classpath

### ISSUE THREAD

**Issue by netmikey** [gradle/gradle#21968]
### Expected Behavior

Given subproject A:

```gradle
apply plugin: 'java'

configurations {
    testConfig
}

// [...]
```

and subproject B:
```
apply plugin: 'java'

dependencies {
    implementation project(':A')
    testRuntimeOnly project(path: ':A', configuration: 'testConfig')
}
```

Things should work like before: subproject B has an implementation dependency on the main configuration and a test dependency on an additional configuration of subproject A. Those dependencies should work in buildship like in Gradle.

### Current Behavior

There's only a test dependency in buildship, no implementation dependency.

### Context

We use multiproject builds extensively. We usually have one core subproject and a bunch of other subprojects. The other subprojects often rely on some common test resources from the core subproject like logging configurations, test configurations, test keystores etc. So naturally, our subprojects depend on the code from the core subproject for their `implementation` classpath and depend on the test resources (exported in their own "configuration") for their `testRuntimeOnly` classpath.

This stopped working in Gradle 7.5.

### Steps to Reproduce 

I created a minimal project reproducing this error: [buildship-bug.zip](https://github.com/gradle/gradle/files/9546202/buildship-bug.zip)

Unzip it, the build should work when building on the command-line. However, importing this into Eclipse/Buildship, the compiler complains because of the aforementioned classpath issues.

### Your Environment

Windows 10, Java 11, Gradle 7.5.1

**Comment by mfussenegger** [comment]
Looks like this is still an issue in Gradle 7.6 as well.

**Comment by netmikey** [comment]
Looks like this is still an issue in Gradle 8.0 as well.

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by donat** [comment]
This is due to the fact that Buildship has only an approximate classpath mapping from Gradle. You can try adjusting the classpath entries in the `eclipse.classpath.file.whenMerged {}` hook to work around the issue. 
We have some ideas on how to tackle this problem in a general way, but we don't have the capacity to work on it in the near future.
