### ISSUE TITLE
includeGroupByRegex with exclusiveContent  can be easily misconfigured leading to poor security

### ISSUE THREAD

**Issue by codefish1** [gradle/gradle#21967]
Within your build.gradle.kts file you can define exclusive content such, to limit where dependencies may be pulled form.  I quite often see people use the regex like in the example below, which works, but matches to a much wider set of groups than they expect.

```
repositories {
  exclusiveContent {
    forRepository { maven("https://....") }
    filter {
      includeGroupByRegex("com.google.*")      
    }
  }
```

In this instance the regex should be something like

`includeGroupByRegex("com\\.google(?:\..+|\Z)")`

which will pull anything in **com.goggle:foo** and **com.google.bar:foo**

### Expected Behavior

Add a new option for including, prehaps includeGroupByPrefix which automatically adds the regex for you correctly so you can just do 

`   includeGroupByPrefix("com.google")      `

**Comment by yogurtearl** [comment]
```includeGroupByRegex("com.google.*")```

will also match things like `com_google.foo` and `com.googleandroid`
