### ISSUE TITLE
 7.5 now requires access to signing certificate when deploying signed artifact

### ISSUE THREAD

**Issue by promme** [gradle/gradle#21969]
### Context
Since Gradle 7.5 (works fine in Gradle 7.4.x) it is now necessary that the signing certificate is present during the deployment step of a signed binary

### Expected Behavior
We don't need to have the signing certificate present during the publishReleasePublicationToMavenRepository task.
Worked in 7.4.x

### Current Behavior
Without the signing certificate we fail with the error: 
> Execution failed for task ':application:validateSigningRelease'.
> Keystore file 'KEYSTORE FILE LOCATION' not found for signing config 'release'.

### Current Workaround
Make sure that signing certificate is still present during deployment

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.

**Comment by alixwar** [comment]
This issue can only be reproduced in a CI environment where the available data is different between the different CI jobs, so I don't see how a minimum reproducer is possible without making it a major effort. I think this can be explained in words and hopefully resolved without too much headache.

The relevant gradle tasks in question are these two chunks:

1. gradle assembleRelease app:signingReport 

Comment: In this step the PKCS#12 signing certificate is available

2. gradle publishDebugPublicationToMavenRepository

Comment: This step fails unless the PKCS#12 signing certificate is still available

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

---

The task requiring the certificate doesn't seem to be a Gradle task, hence our suspicion that this is actually an Android issue.

**Comment by alixwar** [comment]
Now reported [here](https://issuetracker.google.com/issues/247054683)
