### ISSUE TITLE
Consume most specific variant of a platform-aware local Java library

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2196]
Make sure consumers select the most appropriate version of a library, for compile and for runtime. For example, if a Java 7 consumer is faced with a producer that has a Java 7 and a Java 8 variant, then it should select the Java 7 version.

If a consumer is targetting Java 8, but a consumer only provides a Java 6 and Java 7 version, then the Java 7 version should be selected.

The rules can be copied from the existing implementation in the _Java software model_. This ticket is basically about backporting the existing behavior to the Java plugins.

**Comment by jjohannes** [comment]
This works since `5.3` through the `org.gradle.jvm.version`.
