### ISSUE TITLE
Catalog from a TOML file not available for buildSrc common-conventions

### ISSUE THREAD

**Issue by alessandroToninelli** [gradle/gradle#21970]
importing the toml file into the settings gradle using the following script in the settings.gradle.kts of buildSrc
```
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("path to toml file"))
        }
    }
}
```
dependencies are not seen from the common-convention.gradle.kts file which resides inside 
``
buildSrc / src / kotlin / common-conventions-gradle.kts.
``

Toml File

```
[versions]
ktor = "2.1.1"


[libraries]
ktor-server-core = {module = "io.ktor:ktor-server-core", version.ref = "ktor"}

```

Is there any way to make it possible?

**Comment by jbartok** [comment]
Duplicates #15383
