### ISSUE TITLE
Load tasks from the configuration cache in the same build they are stored

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#21985]
When there is a configuration cache miss, Gradle recalculates the task graph and stores the result in the configuration cache. Gradle then runs that task graph, rather than the cached graph. Only on the next cache hit is the task graph loaded from the cache. However, there are a couple of disadvantages to this approach:

1. Deserialization problems are not discovered until there is a cache hit.
2. Tasks are not run in parallel in the build that stores the task graph, leading to a potential performance penalty and issues related to inconsistent execution modes.

### Expected Behavior

When the configuration cache is enabled, Gradle always runs tasks loaded from the configuration cache, even when there is a cache miss.

### Current Behavior

Gradle does not run tasks loaded from the configuration cache when there is a cache miss.

### Next Steps
- [ ] fix configuration cache incompatible tests
  - [x] composite builds 
- [x] build scans
- [x] parallel execution - covered by `ConfigurationCacheParallelTaskIntegrationTest`
- [x] build service lifecycle
- [ ] remove internal flag
- [x] releasing memory
- [ ] improve problem reporting for unsupported types and features, such as source dependencies (currently get 2 problems reported)

**Comment by TimvdLippe** [comment]
FYI if deserialization would happen on the first run, it could potentially already fix #21671

**Comment by adammurdoch** [comment]
First round of changes in https://github.com/gradle/gradle/pull/22209

**Comment by adammurdoch** [comment]
Another round of changes in https://github.com/gradle/gradle/pull/22231

**Comment by adammurdoch** [comment]
Some test fixes in https://github.com/gradle/gradle/pull/22284

**Comment by adammurdoch** [comment]
More fixes in https://github.com/gradle/gradle/pull/22526

**Comment by adammurdoch** [comment]
More test fixes in https://github.com/gradle/gradle/pull/22923

**Comment by adammurdoch** [comment]
More test fixes in https://github.com/gradle/gradle/pull/22941

**Comment by adammurdoch** [comment]
More test fixes in https://github.com/gradle/gradle/pull/22958

**Comment by adammurdoch** [comment]
More test fixes in https://github.com/gradle/gradle/pull/22969

**Comment by adammurdoch** [comment]
Enable by default, plus fix a bunch of tests in https://github.com/gradle/gradle/pull/22990

Fixes to release project state in https://github.com/gradle/gradle/pull/23042, https://github.com/gradle/gradle/pull/23065 and https://github.com/gradle/gradle/pull/23103

**Comment by adammurdoch** [comment]
Split out #23139

**Comment by adammurdoch** [comment]
Some artifact transform fixes in https://github.com/gradle/gradle/pull/23915

**Comment by adammurdoch** [comment]
Split out #24240 to improve the reporting for unsupported types.

**Comment by adammurdoch** [comment]
Closing this as finished.
