### ISSUE TITLE
Windows user profil folder with accent

### ISSUE THREAD

**Issue by JoseIANEZ** [gradle/gradle#22005]
Hello,

I am a French developer and for 10 years I have been using a French IDE called "Windev Mobile" under Windows from PCSOFT to develop applications running on Android.
In 2018, my coding environment (Windev Mobile version 23) was using Gradle version 2.14.1 to build Android apps and I'm still using this version which works well.
A week ago I purchased the latest Windev Mobile version 27 update which now uses Gradle version 7.0.2 and I have an issue that PCSOFT seems to attribute to Gradle.
In fact, my user profile folder contains an accent (C:\Users\José) and apparently Gradle no longer works if this directory contains an accent.
I remind you that with this profile I have no problem with Gradle v2.14.1.
So I would like to know if you are aware of this regression and if there is a solution.

Thanks.

_Originally posted by @JoseIANEZ in https://github.com/gradle/gradle/issues/15977#issuecomment-1246507594_

**Comment by jbartok** [comment]
Unless you can prove that this is a bug in Gradle and not the same root cause as the linked issue, there is nothing we can do about it.
