### ISSUE TITLE
Provide a way to declare JDKs and JREs

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2200]
Backport the _Java Software Model_ toolchain declaration support to the Java plugins:

- we should support declaring JDKs and JREs separately
- we should allow declaring multiple JDKs/JREs for a specific version (typically, one might want to build with OpenJDK and test on both OpenJDK and IBM JDK)

**Comment by melix** [comment]
See #1652.

As an example, here's how the software model let's one declare Java toolchains:

```
model {
    javaInstallations {
        openJdk6(LocalJava) {
            path '/usr/lib/jvm/jdk1.6.0-amd64'
        }
        oracleJre7(LocalJava) {
            path '/usr/lib/jvm/jre1.7.0'
        }
        ibmJdk8(LocalJava) {
            path '/usr/lib/jvm/jdk1.8.0'
        }
    }
}
```

**Comment by bmuskalla** [comment]
@ljacomet What we have for now should be sufficient for this or do you think we also need to provide the service as API already? I'd start with having the internal service and expose it as API once we have all the dots connected

**Comment by ams-tschoening** [comment]
Looking at the hard-coded paths, two questions come into mind: Where are those toolchains declared and do the paths support environment variables?

For Maven, the config for toolchains is maintained in the local `.m2`-directory part of the user executing Maven. While that means all users need to maintain that file on their own, all of those files can have hard-coded paths to arbitrary local paths without interfering with any other user or project. The paths in your example are most likely different between users using Windows and non-Windows already.

So if those toolchains would be part of `build.gradle`, which is maintained as part of a project and part of some SCM most likely, those paths wouldn't easily fit different local deployments of the project to work on. This could be somewhat worked around by allowing e.g. resolving environment variables, though even those are different across platforms. It would make the toolchains unnecessary complex if configs would need to be maintained for each OS, like in the following example:

    openJdk6NonWin(LocalJava) {
            path '/usr/lib/jvm/jdk1.6.0-amd64'
    }
    openJdk6Win(LocalJava) {
            path 'C:/Program Files/Java/jdk-6'
    }

**Comment by bmuskalla** [comment]
Sorry @ams-tschoening for the confusion. Right now, we're working on the internal support for toolchains, how they wire up with the tasks, etc. How to configure them from the outside (build dsl, auto detection, ...) is still under discussion. And you're completely correct pointing out that absolute paths in build scripts are a problem (even in settings) and thus would just introduce another indirection as you'd have to configure them using env/sytem props. Once we have the basic internals working, we'll get back to how to best expose them to our users (and I'm sure there are multiple different ways depending on the usecase that make sense). Thanks for the feedback though
