### ISSUE TITLE
Java compile tasks should select the most appropriate toolchain

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2201]
Whenever Java toolchains are declared (or detected?), we should select the most appropriate toolchain to compile, depending on the [target platform](#2198). The selection rules are already implemented in the Java Software Model. We need to backport them.

Things to consider: what to do with "path to executable", which is deprecated.

**Comment by bmuskalla** [comment]
> selection rules are already implemented in the Java Software Model
@melix Would you be able to point me to the corresponding rules?

**Comment by melix** [comment]
mmm, I don't remember where it lives and can't find it after a quick search :/

**Comment by bmuskalla** [comment]
Closing this for now as this is going to be replaced by the toolchain dsl.
