### ISSUE TITLE
`test-report-aggregation` docs are missing mention of `--continue` flag

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#22013]
As evidenced by #21966, our docs are completely missing any mention of the `--continue` flag, which is necessary to allow aggregation to proceed despite broken tests.

We should update these two pages:
* https://docs.gradle.org/7.5.1/userguide/test_report_aggregation_plugin.html
* https://docs.gradle.org/7.5.1/userguide/jacoco_report_aggregation_plugin.html

**Comment by DPUkyle** [comment]
I don't think this quite covers it.  Please also mention this option on the jacoco_report_aggregation_plugin.adoc and test_report_aggregation_plugin.adoc pages.

**Comment by nathan-contino** [comment]
@DPUkyle can you take a look at the PR again? The PR wasn't final when you looked at it yesterday, those pages are now covered.

**Comment by nathan-contino** [comment]
Addressed!
