### ISSUE TITLE
Detect local Java installations

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2202]
Declaring local Java installations is nice, but sometimes (CI environment, typically), we don't want to hardcode paths to installations, or rely on environment variables/system properties. We already have some internal APIs to detect installations, so we should just make detection possible (probably disabled by default).

**Comment by eskatos** [comment]
Here's the spike we did last year on this: https://github.com/gradle/gradle/commit/fddb82f967533f7386eaf2f1f7726e922937b019

**Comment by melix** [comment]
Interesting I thought it was merged...

**Comment by eskatos** [comment]
Nah, we didn't get to that point ;) But it's in a pretty good shape.

**Comment by bmuskalla** [comment]
Initial support for this has been merged in the form of the `SharedJavaInstallationRegistry`. I'll create separate issues for candidates (operating systems, package managers) that should supply local installation locations.
