### ISSUE TITLE
Java toolchains

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2203]
This epic is about adding support for Java toolchains to the Java plugins.

**Comment by wolfs** [comment]
I guess https://github.com/gradle/gradle/issues/1652 should be part of this epic or being replaced by this epic.

**Comment by melix** [comment]
Thanks, I added it to the epic. We can discuss if we want to close one issue or the other later.

**Comment by bmuskalla** [comment]
The initial version of Java toolchains has been delivered [with Gradle 6.7](https://docs.gradle.org/6.7/release-notes.html). Additional support for vendors, implementation and the `javaToolchains` task is going to be released with the [upcoming 6.8](https://github.com/gradle/gradle/blob/release/subprojects/docs/src/docs/release/notes.md). 
Closing this epic. Further enhancements and issues are tracked using the [`in:toolchains`](https://github.com/gradle/gradle/labels/in%3Atoolchains) label
