### ISSUE TITLE
Configuration cache fails when using includeBuild(".")

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#22046]
When adding `includeBuild(".")` to enable the _root_ build to refer to its own subprojects via coordinates (see [docs](https://docs.gradle.org/current/userguide/composite_builds.html#included_build_declaring_substitutions)), the configuration cache stops working.

### Expected Behavior
A build using `includeBuild(".")` should work with `--configuration-cache`.

### Current Behavior
The build fails with:

```
1 problem was found reusing the configuration cache.
- Gradle runtime: cannot deserialize object of type 'java.lang.Thread' as these are not supported with the configuration cache.
```

### Steps to Reproduce 
In an empty folder create the following setup:

**settings.gradle**
```
includeBuild(".")
```

**build.gradle**
```
plugins { id("java-library") }
```

Run two times:
`gradle build --configuration-cache`

### Your Environment
_Build fails to early to produce a build scan_

Gradle version: **7.5.1** (also reproduced with 7.4.2)

**Comment by bamboo** [comment]
Fixed by #21589
