### ISSUE TITLE
Contact authors of downstream dependencies using Project.getConvention()

### ISSUE THREAD

**Issue by donat** [gradle/gradle#22054]
We're planning to emit deprecation warning for all usages of conventions. At the same time, several plugins still make use of this feature. If we flipped the switch right now, almost all builds out there would be affected. To minimize the impact, we should coordinate with the authors of those plugins.

Related PR: https://github.com/gradle/gradle/pull/17226

- [ ] Update our internal publish plugin to use `JavaPluginExtension` instead of `JavaPluginConvention`
- [ ] Run our internal smoke tests and see how many things break
- [ ] The `kotlin-gradle-plugin` needs to be updated. We give JetBrains a heads-up [here](https://gradle.slack.com/archives/CDH5M7FAT/p1621423960007500).
- [ ] Check the failing smoke tests
- [ ] FreefairAspectJPluginSmokeTest
- [ ] AndroidSantaTrackerSmokeTest
- [ ] DockerPluginSmokeTest
- [ ] SpringBootPluginSmokeTest
- [x] TestRetryPluginSmokeTest
- [ ] PlayPluginSmokeTest
- [ ] ShadowPluginSmokeTest
- [ ] BuildScanPluginSmokeTest
- [ ] SpotBugsPluginSmokeTest
- [ ] KotlinPluginSmokeTest
- [ ] ErrorPronePluginSmokeTest
- [ ] ThirdPartyGradleModuleMetadataSmokeTest
- [ ] AsciidoctorPluginSmokeTest
- [ ] GradleVersionsPluginSmokeTest
- [ ] JGitPluginSmokeTest
- [ ] KotlinPrecompiledScriptPluginsSmokeTest
- [ ] SpringDependencyManagementPluginSmokeTest
- [ ] NebulaPluginsSmokeTest
- [ ] ProtobufPluginSmokeTest
- [ ] AndroidPluginsSmokeTest

**Comment by ljacomet** [comment]
@donat Is this still relevant?

**Comment by donat** [comment]
No, we can close this issue.
