### ISSUE TITLE
[4.0-rc-1] Empty test suite while running unit tests written in kotlin in android project.

### ISSUE THREAD

**Issue by jozzi05** [gradle/gradle#2206]
Gradle doesn't execute kotlin unit tests in android project. Tests written in Java work as expected but there is some problem with Kotlin files.

### Expected Behavior

Command `./gradlew test` should execute unit tests written in kotlin in android project.

### Current Behavior

Currently command  `./gradlew test` ends with success even though there are failing unit tests written in kotlin.

### Context

Am I missing something? Is there any extra setup I need to add to run kotlin unit tests? There was no difference between Kotlin and Java files before. 

### Steps to Reproduce (for bugs)

1. Clone [github repo](https://github.com/jozzi05/gradle_unit_tests_bug) with example android project. 
2. Run `./gradlew test`

Expected:
2 failing tests (one written in kotlin and second written in Java)

Currently:
Only one failing test(written in java).

### Your Environment
MacOS

**Comment by eskatos** [comment]
Thanks for the report @jozzi05!
Was this working with a previous Gradle version?

Both Java and Kotlin unit tests source files sits in `src/main/java`.

The Java test compiled `.class` file can be found in: 
`app/build/intermediates/classes/test/debug/pl/dmalantowicz/gradle/ExampleJavaUnitTest.class`

The Kotlin test compiled `.class` file can be found in:
`app/build/tmp/kotlin-classes/debugUnitTest/pl/dmalantowicz/gradle/ExampleUnitTest.class`

At first sight this looks related to the [kotlin-gradle-plugin](https://kotlinlang.org/docs/reference/using-gradle.html) and maybe to the change in 4.0 to [split the `classes` directories per language](https://docs.gradle.org/release-candidate/release-notes.html#location-of-classes-in-the-build-directory) /cc @big-guy

**Comment by jozzi05** [comment]
@eskatos I've created branch [gradle_3.5_build_tools_2.3.2](https://github.com/jozzi05/gradle_unit_tests_bug/tree/gradle_3.5_build_tools_2.3.2) with gradle 3.5 and build tools in version 2.3.2 and tests work correctly.

**Comment by vanta** [comment]
The same issue I have with units written in Groovy: in my custom source set `integrationTest` I have tests written in Java and Groovy. Before (Gradle `3.5`) tests from both folders were picked up. With Gradle `4.0-rc-1`, only tests from Java are run.

![image](https://cloud.githubusercontent.com/assets/2153370/26649722/42286140-4647-11e7-8b18-af616da32864.png)

**`3.5`:**
```
:rest-tests:integrationTest

+--------------------------------------------------------+
|  Project: Gradle Test Run :rest-tests:integrationTest  |
+--------------------------------------------------------------------------------------+
|  Results: SUCCESS (37 tests, 36 successes, 0 failures, 1 skipped). Took 129.886 ms.  |
+--------------------------------------------------------------------------------------+
```

**`4.0-rc-1`:**
```
> Task :rest-tests:integrationTest

+--------------------------------------------------------+
|  Project: Gradle Test Run :rest-tests:integrationTest  |
+-----------------------------------------------------------------------------------+
|  Results: FAILURE (8 tests, 6 successes, 2 failures, 0 skipped). Took 43.354 ms.  |
+-----------------------------------------------------------------------------------+

```

Additionally, some tests fails under `4.0-rc-1`, while in `3.5` were fine.

**Comment by big-guy** [comment]
@vanta that's a similar issue to this.  Do you get one or two deprecation warnings in your build related to your integrationTest task?

In <Gradle 4.0, all compilation tasks used the same output directory.  The test task would only need to look in that single directory for tests.

In Gradle 4.0, each compilation task uses a separate output directory, which makes it possible to safely cache the output of each compilation task in the build cache.  The test task now needs to look in multiple class directories to find all of the tests.  This is what's described in the release notes: https://docs.gradle.org/4.0-rc-1/release-notes.html#multiple-class-directories-for-a-single-source-set

We're going to update some documentation and release notes for this (#2216) to make the impact more clear.   You should be able to get your build to work by fixing the deprecation warnings.  So something like:

`integrationTest.testClassesDirs = sourceSets.integrationTest.output.classesDirs`

**Comment by vanta** [comment]
Thanks for answer. Yes, I have warnings:
```
Using a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
        at build_2j3id4wj0rdb88ykb363j05mj$_run_closure3$_closure11.doCall(/Users/vanta/src/calendar/build.gradle:109)
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
        at build_2j3id4wj0rdb88ykb363j05mj$_run_closure3$_closure11.doCall(/Users/vanta/src/calendar/build.gradle:109)
```

In line `109` I have:

```
108:    task integrationTest(type: Test, dependsOn: jar) {
109:        testClassesDir = sourceSets.integrationTest.output.classesDir
```
so I believe this is equivalent of your line, or not? But they are only warnings so they should be still compiled?

**Comment by big-guy** [comment]
@vanta 
> so I believe this is equivalent of your line, or not? But they are only warnings so they should be still compiled? 

The tests are still compiled, but the test task is only looking for tests in the Java classes directory.

> Btw. I see classes from groovy sourceset compiled in build/classes/groovy/integrationTest but not run... I believe the test task was updated to hadle these separate output dirs?

It was for the built-in `test` task, but your `integrationTest` task...
```
testClassesDir = sourceSets.integrationTest.output.classesDir
```
...only looks in a single directory.  That line causes both warnings, `sourceSets.integrationTest.output.classesDir` assumes there is a single output directory and setting `testClassesDir` configures the test task to only look in a single directory.

Alternatively, you can change the source set to have the old behavior (a single output directory):
`sourceSets.integrationTest.output.classesDir = new File(buildDir, "classes/integrationTest")`

But this will prevent the build cache from working for the Java and Groovy compilation tasks for that source set.

**Comment by eskatos** [comment]
@vanta,

Kotlin unit-tests not present on the test classpath is an issue on the Android plugin, see https://issuetracker.google.com/issues/38454212

About your custom `integrationTest` source set, @big-guy's advice above should allow you to fix it.

I'm closing this issue, feel free to reopen if needed.

**Comment by vanta** [comment]
Thanks, I changed it to:
`testClassesDirs = sourceSets.integrationTest.output.classesDirs`
and it works fine with no warnings and all tests are run.

However some container (Weld) based tests are failing, but used to work in `3.5`

**Comment by eskatos** [comment]
@vanta 
> However some container (Weld) based tests are failing, but used to work in 3.5

Could you please open another issue to discuss this different topic?
If you could provide a reproducer build or [build scans](https://gradle.com/scans/get-started) with both 4.0-rc-1 and 3.5 in the new issue that could help us understand what's at stake.
