### ISSUE TITLE
Gradle build failed when using annotationProcessor but works fine with IDE

### ISSUE THREAD

**Issue by nbokka** [gradle/gradle#22065]
When I use the compilation and operation of intellij idea, it runs normally. This error occurs when I switch to gradle.

I see same issue reported #https://github.com/gradle/gradle/issues/21310

Cause: superclass access check failed: class com.devexperts.uilocalizer.AddLocalizationNodesVisitor (in unnamed module @0x7dda3124) cannot access class com.sun.tools.javac.tree.JCTree$Visitor (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x7dda3124

**Gradle 7.5.1**

Kotlin: 1.5.31
Groovy: 3.0.9
JVM: 17.0.2 

see the attachment for issue to recreate and workaround solution .

[devexperts-17-issue.zip](https://github.com/gradle/gradle/files/9586557/devexperts-17-issue.zip)
[devexperts-17-workaround.zip](https://github.com/gradle/gradle/files/9586558/devexperts-17-workaround.zip)

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
