### ISSUE TITLE
Build Cache documentation link to Gradle Enterprise is broken 

### ISSUE THREAD

**Issue by rpygithub** [gradle/gradle#22063]
The "Implement your Build Cache" [section](https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_implement) links to Gradle Enterprise. Once you click on the link in the live documentation, a redirect adds additional URL query parameters and the visitor ultimately ends up on an error page.

### Expected Behavior
The link should correctly redirect the visitor to https://gradle.com/gradle-enterprise-solutions/build-cache/

### Current Behavior
Redirect is broken, ending up on an error page.

**Comment by rpygithub** [comment]
@jbartok this relates to the GBT documentation, which I assume is maintained by the GBT team? Who is the best point of contact to get this resolved, if not?

**Comment by hythloda** [comment]
@nathan-contino Could you add this to your TODO for the week?

**Comment by nathan-contino** [comment]
I cannot reproduce the "additional URL query parameters and the visitor ultimately ends up on an error page" -- the link loads fine for me. Tested in Firefox, Chrome, and Safari and I can't reproduce.

Can someone else reproduce this or verify that this is still a problem? Happy to update the link, just skeptical of making a change when I can't see the problem in practice.

**Comment by nathan-contino** [comment]
Fixed.
