### ISSUE TITLE
Checkstyle error in `7.5.1`: Must specify at least one of 'file' or nested 'fileset' or 'path'.

### ISSUE THREAD

**Issue by Prikalel** [gradle/gradle#22073]
Using template from https://github.com/sevntu-checkstyle/checkstyle-samples I tried to check java code with embedded Checkstyle gradle plugin and got an error. See my fork at https://github.com/Prikalel/checkstyle-samples (where I just solved insecure protocol issue and upgrade gradle up to 7.5.1).

### Expected Behavior
Checkstyle should work with `7.5.1` version of gradle. Or you should have a section in docs, where the way to pass 'file' or nested 'fileset' or 'path' to checkstyle is specified.

### Current Behavior
```
> Task :checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > Must specify at least one of 'file' or nested 'fileset' or 'path'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
3 actionable tasks: 3 executed

```

### Context
1) _Which version did this stop working with? Which version do you know it works?_
It works fine with gradle `7.4.2`.
2) _How has this issue affected you? What are you trying to accomplish?_
I'm trying to use Checkstyle with the most recent gradle version, but I can not find any resources (or documentation) on that error.

### Steps to Reproduce 

1) Clone https://github.com/sevntu-checkstyle/checkstyle-samples and navigate to `gradle-project` folder.
2) Now run `./gradlew check`, as you see all is fine:
```

> Task :checkstyleMain
[ant:checkstyle] [ERROR] /home/alex/Загрузки/checkstyle-samples/gradle-project/src/main/resources/messages.properties:1: Файл не заканчивается пустой строкой. [NewlineAtEndOfFile]
[ant:checkstyle] [ERROR] /home/alex/Загрузки/checkstyle-samples/gradle-project/src/main/java/com/github/sevntu/checkstyle/Sample.java:6:17: Method declares to return Boolean and returns null. [ReturnNullInsteadOfBoolean]
Checkstyle rule violations were found. See the report at: file:///home/alex/Загрузки/checkstyle-samples/gradle-project/build/reports/checkstyle/main.html
Checkstyle files with violations: 2
Checkstyle violations by severity: [error:2]


BUILD SUCCESSFUL in 883ms
4 actionable tasks: 4 executed
```
3) Upgrade gradle: `./gradlew wrapper --gradle-version 7.5.1`
4) Run the same command again: `./gradlew clean check` and now you get the error:
```
> Task :checkstyleMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkstyleMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > Must specify at least one of 'file' or nested 'fileset' or 'path'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 523ms
4 actionable tasks: 4 executed
```

### Your Environment
Build scan URL:
https://gradle.com/s/ynitpaqmrntdc

**Comment by 6hundreds** [comment]
Thanks for the reporting @Prikalel
However I wasn't able to reproduce the issue with STR you provided. Could you make sure that STR are correct?

**Comment by Prikalel** [comment]
And I tried it on another Debian 11 machine with fresh java-17 installed using gradle-wrapper and got the same error: https://gradle.com/s/2fxragbaqmst2

**Comment by 6hundreds** [comment]
@Prikalel I'm tried to reproduce at exactly same environment that you are using. It's behaves correctly.
Are you sure that you don't have any not committed changes in your local repo?

**Comment by 6hundreds** [comment]
@Prikalel What we would ask you is use the following template with a Gradle GitHub action set up to showcase your problem: https://github.com/gradle/gradle-issue-reproducer

**Comment by Prikalel** [comment]
))
Finally, I realized that this issue is a duplicate of https://github.com/checkstyle/checkstyle/issues/12057 (https://github.com/gradle/gradle/issues/21524).
My path of all gradle projects is 
```
/home/alex/Документы/**
```
So when I moved project folder from `/home/alex/Документы/gradle-issue-22073-reproducer` to just `/home/alex/gradle-issue-22073-reproducer` it started to work properly, so I guess I can not reproduce this issue with https://github.com/gradle/gradle-issue-reproducer.
