### ISSUE TITLE
can't use java library with fully qualified name in kotlin dsl

### ISSUE THREAD

**Issue by RoadRoller01** [gradle/gradle#22072]
### Expected Behavior
```
2:09:05 AM: Executing 'getCurrentTime'...


> Task :getCurrentTime
Sun Sep 18 02:09:05 AST 2022

BUILD SUCCESSFUL in 89ms
1 actionable task: 1 executed
2:09:05 AM: Execution finished 'getCurrentTime'.
```

### Current Behavior
```
e: build.gradle.kts:8:31: Unresolved reference: util

FAILURE: Build failed with an exception.

* Where:
Build file 'build.gradle.kts' line: 8

* What went wrong:
Script compilation error:

  Line 8:         logger.lifecycle(java.util.Date().toString())
                                        ^ Unresolved reference: util
```

### Context 
the expected behavior code
```kotlin
import java.util.Date

plugins {
    id("java")
}

task("getCurrentTime") {
    group = "time stuff"
    doLast {
        logger.lifecycle(Date().toString())
    }
}
```

the current behavior code
```kotlin
plugins {
    id("java")
}

task("getCurrentTime") {
    group = "time stuff"
    doLast {
        logger.lifecycle(java.util.Date().toString())
    }
}
```
when i go to the java declaration it was
```kotlin
val org.gradle.api.Project.`java`: org.gradle.api.plugins.JavaPluginExtension get() =
    (this as org.gradle.api.plugins.ExtensionAware).extensions.getByName("java") as org.gradle.api.plugins.JavaPluginExtension
```
in the gradle-kotlin-dsl-7.4.jar that came with the java(\`java-library\`),
 if i removed the java plugin it's will work but i need the java plugin 
for the implementation() stuff

**Comment by eskatos** [comment]
Hi @RoadRoller01, thank you for your report.

This is as expected. The project extension contributed by the Java plugin named `java` materializes as a `val java: JavaPluginExtension` that shadows the `java` package name.

The same would happen in a class that has a field named `java`, it would shadow the `java` package name.

Here's how it looks in a plain Kotlin file:
![Screenshot_20220921_171714](https://user-images.githubusercontent.com/132773/191543814-95689791-9a98-4374-8a0e-3afddc12dbcb.png)

In Java it's the same:
![Screenshot_20220921_171511](https://user-images.githubusercontent.com/132773/191543862-a904c9fe-882e-4a58-a530-0cd65abcb6f1.png)



To make things work, simply use imports.
