### ISSUE TITLE
Works with 3.5, breaks with 4.0 RC1

### ISSUE THREAD

**Issue by BruceEckel** [gradle/gradle#2207]
To Reproduce:

Clone https://github.com/BruceEckel/OnJava8-Examples

First test with 3.5 to verify: `gradlew run` (should execute successfully)

Now upgrade: `./gradlew wrapper --gradle-version=4.0-rc-1`

Now re-run:

`gradlew clean`

`gradlew run`

And you'll see the error. This seems to happen because 4.0 has changed directory structure. Not sure what else breaks so I'm sticking with 3.5.

**Comment by bmuschko** [comment]
Hi Bruce,

I can reproduce the issue in your build. 

```
* What went wrong:
Execution failed for task ':annotations:AUComposition'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

However, given that your `run` task is a custom functionality you'll need to do some more digging on your end and provide us with additional information. Compiling your code with `./gradlew compileJava` works fine. 

You'll need to identify why your custom `JavaExec` fails. We can have a deeper look from there.

**Comment by bmuschko** [comment]
I am going to close this issue as we haven't heard back. Feel free to reopen if can provide more information.

**Comment by BruceEckel** [comment]
I'm just sticking with 3.5


-- Bruce Eckel
www.MindviewInc.com <http://www.mindviewinc.com/>
Blog: BruceEckel.github.io
www.WinterTechForum.com
www.AtomicScala.com
www.Reinventing-Business.com
http://www.TrustOrganizations.com <http://www.ScalaSummit.com>
