### ISSUE TITLE
4.0-rc-1 takes longer for resolving configurations than 3.5

### ISSUE THREAD

**Issue by kageiit** [gradle/gradle#2208]
Clone https://github.com/kageiit/android-studio-gradle-test

on 3.5 (default upon checkout)

Run `rm -f build/okbuck.success; time ./buckw --version` a few times to get a warm daemon and get an estimate of the total build time (note that the task execution heavily relies on resolving configurations)

Now update gradle to 4.0-rc-1

Run `rm -f build/okbuck.success; time ./buckw --version` a few times to get a warm daemon and get an estimate of the total build time

### Expected Behavior
Configuration resolution time during task execution should be as good as or better than 3.5

### Current Behavior
Degradation in overall build performance as it takes longer for task execution
It seems to be resolving dependencies and files separately in 4.0 which was not the case in 3.5

**Comment by kageiit** [comment]
The Android Gradle plugin at 3.0.0 removes many apis and breaks the project so updating is not an option. I also do not understand why that would matter? Can you elaborate why that might influence this?

Because even with the outdated plugin, Gradle 3.5 has better performance.

**Comment by oehme** [comment]
There will be no Android 2.4. We should either test with 2.3 or 3.0-preview. Testing a version that will never go out would be wasted effort.

**Comment by kageiit** [comment]
I can easily downgrade to 2.3.2 . That should not be a problem

**Comment by oehme** [comment]
Cool, let me know if the same happens with 2.3.2. That would be a high priority. We have tests on CI that verify 2.3 performance though and they don't show any regression.

**Comment by kageiit** [comment]
2.3.2 with a warm daemon is very close in performance for both gradle versions. It seems like only a problem with 2.4.0-alpha*.

I will try to get the project to build with 3.0.0-alpha* somehow to see how it performs on the latest versions of the android gradle plugin.

Thanks!

**Comment by adammurdoch** [comment]
I've done some improvements for 4.0-rc-2 that should make both the old `ResolvedConfiguration` and the new `ArtifactCollection` APIs faster. Measuring with `perf-android-large` with Android 2.3.2, `gradle okbuck` is a a little less than 3 seconds faster on my machine with these changes.

**Comment by kageiit** [comment]
Thanks @adammurdoch I have further tested on the latest nightly for 4.0 and can confirm the resolution is definitely much faster. Thanks for your improvements!
