### ISSUE TITLE
Progress bar and work-in-progress info is sometimes rendered in build output

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#2210]
### Expected Behavior

Progress bar and work-in-progress info is never rendered in the build output. Task output is properly grouped.

### Current Behavior

Progress bar and work-in-progress info is sometimes rendered in build output when it shouldn't be rendered. This is an issue with the synchronization code that determine the cursor position.

### Context

The console output is should properly render build output.

### Steps to Reproduce (for bugs)

Issue occurs in the last 30 seconds on the video.

![bad-grouping](https://cloud.githubusercontent.com/assets/440872/26608718/0be9df78-456b-11e7-9586-2b84b1fc4766.gif)

**Comment by bmuschko** [comment]
It looks to me as if sometimes portions of the work-in-progress information and progress bar get mixed into the build output:

```
<============-> 97% EXECUTING [34s]
objc[12923]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java (0x1019444c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1039a24e0). One of the two will be used. Which one is undefined.

com.bmuschko.gradle.tomcat.TomcatBasePluginFunctionalTest > Start and stop Tomcat 6x with myTomcatRun without supporting web app directory STARTED
> Task :plugin:functionalTesttests completed
com.bmuschko.gradle.tomcat.TomcatBasePluginFunctionalTest > Start and stop Tomcat 6x with myTomcatRun without supporting web app directory PASSED

com.bmuschko.gradle.tomcat.TomcatBasePluginFunctionalTest > Start and stop Tomcat 6x with myTomcatRunWar without supporting web app directory STARTED
> IDLE
com.bmuschko.gradle.tomcat.TomcatBasePluginFunctionalTest > Start and stop Tomcat 6x with myTomcatRunWar without supporting web app directory PASSED
```

**Comment by lacasseio** [comment]
We had a similar error previously with this exact scenario and it was caused by a miss alignment of the console state. I will see what I can do for this one.

**Comment by lacasseio** [comment]
@bmuschko Let's sync our work on this issue as it's similar to https://github.com/gradle/gradle/issues/2217 and it may be hard to find.

**Comment by bigdaz** [comment]
![image](https://cloud.githubusercontent.com/assets/179734/26693857/d70ddf4e-46c2-11e7-8f7c-84ff3045220c.png)

**Comment by bmuschko** [comment]
Snapshot containing the fix: https://services.gradle.org/distributions-snapshots/gradle-4.0-20170605192746+0000-bin.zip
