### ISSUE TITLE
Use annotations for declaring that tests need to run on local executors

### ISSUE THREAD

**Issue by hegyibalint** [gradle/gradle#22169]
So all our subprojects can run with test distribution.

**Comment by wolfs** [comment]
This is where we exclude the file system watching tests: https://github.com/gradle/gradle/blob/6ef40e6fb0b410c55d40c302359f8c89a047aa77/.teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt#L200-L213

You can bind tests to local executors by using an annotation: https://docs.gradle.com/enterprise/test-distribution/#gradle_executor_restrictions_annotation_matcher

Let's leave the docs tests alone for now.

**Comment by hegyibalint** [comment]
We can use [gradle-enterprise-testing-annotations](https://github.com/gradle/gradle-enterprise-testing-annotations), so we don't need to define our own set of annotations for TD/local executors.

**Comment by hegyibalint** [comment]
An [important snippet](https://github.com/gradle/gradle/blob/6ef40e6fb0b410c55d40c302359f8c89a047aa77/.teamcity/src/main/kotlin/model/FunctionalTestBucketGenerator.kt#L202-L215) to be (probably) modified in order to discern where we might need to place the annotations.

**Comment by blindpirate** [comment]
This is done, right?

**Comment by wolfs** [comment]
Yes. Fixed via https://github.com/gradle/gradle/pull/22223 and https://github.com/gradle/gradle/pull/22225.
