### ISSUE TITLE
Refactor IsolatedAntBuilderMemoryLeakIntegrationTest

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#22172]
`org.gradle.integtests.IsolatedAntBuilderMemoryLeakIntegrationTest#CodeNarc does not fail with PermGen space error` needs refactoring.

It seems the original intent of this test was to expose memory leaks from repeated use of ant invocations within the same daemon.

However, I believe we terminate the daemon at the end of each unrolled invocation.

Secondly, we now invoke ant for CodeNarc in a worker process, so this is also unlikely to expose the problem this test was originally intended to detect.

I propose a significant refactoring.  Instead of iterating ~12 times, the test setup should create a project-under-test with at least ~12 subprojects and max worker count of 1.

The CodeNarc or Checkstyle executions would then be forced to run in the same worker process within a single Gradle invocation, and if they eventually cause memory pressure we'd expect the worker daemon to crash.

**Comment by big-guy** [comment]
@ghale did this already
