### ISSUE TITLE
JavaCompile api does not write compiled classes until all tasks end

### ISSUE THREAD

**Issue by RoadRoller01** [gradle/gradle#22182]
### Expected Behavior
```cool
13:61:70 GUS: Executing 'printMoney'...

Starting Gradle Daemon...
Gradle Daemon started in 1 s 395 ms
> Task :compilePrinter 

> Task :printMoney
sus
```

### Current Behavior
```cool
Execution failed for task ':printMoney'.
> Could not get unknown property 'me' for task ':printMoney' of type org.gradle.api.DefaultTask.
```

### Context 
the code
```groovy
buildscript {
    dependencies {
        classpath(files("build/classes/java/main/"))
    }
}

task compilePrinter (type: JavaCompile) {
    source = sourceSets.main.java.srcDirs
    include 'me/roadroller01/Printer.java'
    classpath = sourceSets.main.compileClasspath
    destinationDirectory = sourceSets.main.output.classesDirs[0]
}


task printMoney{
    dependsOn(compilePrinter)

    me.roadroller01.Printer.print("sus")
    
}
```
when you add (JavaCompile) to dependsOn, the JavaCompile task will execute but it will not write the compiled classes until all tasks end,
that means if i run the task again it will work,
the second try log
```cool
13:61:69 GUS: Executing 'printMoney'...

> Task :compilePrinter UP-TO-DATE

> Task :printMoney
sus
```
thx

**Comment by RoadRoller01** [comment]
for some reason, if you use debugger it will randomly work :), fuck dynamic

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

-----

Gradle just doesn't work this way. You can't use classes compiled as part of the build, in the same build script (the build classpath is computed before the compilation is executed).

**Comment by RoadRoller01** [comment]
@jbartok is't that bug, because when you add dependsOn it should execute that, then the task

**Comment by ljacomet** [comment]
This is the first and last reminder that we have a [code of conduct](https://gradle.org/conduct/) and your last comment is a clear violation of it.
