### ISSUE TITLE
[4.0-rc-1] - Gradle tasks looks like it is not resolving variables

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#2218]
## Issue:
```
$ gradlew tasks

> :app > Resolve dependencies :app:classpath > maven-reporting-api-${project.prerequisites.maven}.pom
```

## Expected behavior:
I believe `${project.prerequisites.maven}` should resolve to the appropriate `String`.

**Comment by bmuschko** [comment]
Do you have small example project with maybe one or two dependencies that reproduces the issue? I think `${project.prerequisites.maven}` is probably the Maven property in the POM that hasn't been replaced with the value from the parent POM.

**Comment by bmuschko** [comment]
One more question from our end: Is `${project.prerequisites.maven}` a Gradle property that you declared in your build script? If that is the case please also provide the relevant example source code for that.

**Comment by jaredsburrows** [comment]
@bmuschko Not at all. I can try and find the dependency which is causing this.

**Comment by jaredsburrows** [comment]
By searching in Gradle cache, it looks like you are right:

```
$ find . -iname "*.pom" | xargs grep -is "project.prerequisites"
./junit/junit/4.12/35fb238baee3f3af739074d723279ebea2028398/junit-4.12.pom:                                        should be ${project.prerequisites.maven}, or higher!
./junit/junit/4.12/35fb238baee3f3af739074d723279ebea2028398/junit-4.12.pom:                                    <version>[${project.prerequisites.maven},)</version>
./junit/junit/4.13-SNAPSHOT/500d789db584298c765242215c0938359b474810/junit-4.13-SNAPSHOT.pom:                                        should be ${project.prerequisites.maven}, or higher!
./junit/junit/4.13-SNAPSHOT/500d789db584298c765242215c0938359b474810/junit-4.13-SNAPSHOT.pom:                                    <version>[${project.prerequisites.maven},)</version>
./junit/junit/5.0-SNAPSHOT/78598b672f6e3a058f23a9d19327b1f813920a25/junit-5.0-SNAPSHOT.pom:                                        should be ${project.prerequisites.maven}, or higher!
./junit/junit/5.0-SNAPSHOT/78598b672f6e3a058f23a9d19327b1f813920a25/junit-5.0-SNAPSHOT.pom:                                    <version>[${project.prerequisites.maven},)</version>
./org.jacoco/jacoco-maven-plugin/0.7.4.201502262128/364ef102ef20fc5fd37965762efe905cc8e1e586/jacoco-maven-plugin-0.7.4.201502262128.pom:      <version>${project.prerequisites.maven}</version>
./org.jacoco/jacoco-maven-plugin/0.7.4.201502262128/364ef102ef20fc5fd37965762efe905cc8e1e586/jacoco-maven-plugin-0.7.4.201502262128.pom:      <version>${project.prerequisites.maven}</version>
./org.jacoco/jacoco-maven-plugin/0.7.4.201502262128/364ef102ef20fc5fd37965762efe905cc8e1e586/jacoco-maven-plugin-0.7.4.201502262128.pom:      <version>${project.prerequisites.maven}</version>
./org.jacoco/jacoco-maven-plugin/0.7.6.201602180812/b17539014884235ff433bf48ce3e45ba380b4710/jacoco-maven-plugin-0.7.6.201602180812.pom:      <version>${project.prerequisites.maven}</version>
./org.jacoco/jacoco-maven-plugin/0.7.6.201602180812/b17539014884235ff433bf48ce3e45ba380b4710/jacoco-maven-plugin-0.7.6.201602180812.pom:      <version>${project.prerequisites.maven}</version>
./org.jacoco/jacoco-maven-plugin/0.7.6.201602180812/b17539014884235ff433bf48ce3e45ba380b4710/jacoco-maven-plugin-0.7.6.201602180812.pom:      <version>${project.prerequisites.maven}</version>
```

@bmuschko So maybe this is a false alarm?

**Comment by bmuschko** [comment]
I can see in `${project.prerequisites.maven}` in the POM of [`org.jacoco:jacoco-maven-plugin:0.7.9`](https://search.maven.org/remotecontent?filepath=org/jacoco/jacoco-maven-plugin/0.7.9/jacoco-maven-plugin-0.7.9.pom).

```
<dependency>
    <groupId>org.apache.maven.reporting</groupId>
    <artifactId>maven-reporting-api</artifactId>
    <version>${project.prerequisites.maven}</version>
</dependency>
```

The value seems to be resolved from here:

```
<prerequisites>
    <maven>2.2.1</maven>
</prerequisites>
```

I am kind of surprised that we even support the [Prerequisites](https://maven.apache.org/pom.html#Prerequisites) construct. At least I was wasn't aware that we do.

In the dependency report the property doesn't even seem to be replaced. I think this behavior has already been there in Gradle 3.5 and earlier. You probably simply never noticed as the dependency wasn't rendered in the console.

```
compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
\--- org.jacoco:jacoco-maven-plugin:0.7.9
     +--- org.apache.maven:maven-plugin-api:${project.prerequisites.maven} -> 2.0.10
     +--- org.apache.maven:maven-project:${project.prerequisites.maven} -> 2.0.10
```

**Comment by jaredsburrows** [comment]
It must be a plugin that I am using that is maven based. When I run `gradlew dependencies`, I do not see what you see. Did you want to add support for `prerequisites`?

**Comment by bmuschko** [comment]
> It must be a plugin that I am using that is maven based.

I am not sure I understand this statement. I think you are saying that a Gradle plugin you use in your build is declaring dependencies with the group ID `org.apache.maven` e.g. `reporting-api`. Correct?

> Did you want to add support for `prerequisites`?

I don't think we were planning to do so. That doesn't make too much sense in the context of Gradle I think.

**Comment by bmuschko** [comment]
I am going to de-scope the issue for 4.0. We already saw this behavior with earlier versions of Gradle.

**Comment by jaredsburrows** [comment]
@bmuschko Yes, I believe I am plugin I am using must be using that maven plugin. Since this is not planned to be apart of Gradle, I will close this issue. Thanks @bmuschko!
