### ISSUE TITLE
Error unsuported class 62

### ISSUE THREAD

**Issue by Celse2021** [gradle/gradle#22184]
Error when building https://github.com/lambda-plugins/ElytraBot I dont know a lot of gradle but here is the the info with stacktrace (if you want debug info sumbit a comment telling it) Im building with jdk 8.

https://pastebin.com/jTHn8Ddg

**Comment by jbartok** [comment]
You are most likely using a dependency that has been compiled with Java 18 and you are trying to build against it with Java 8. Also you are using a Gradle version which doesn't support Java 18 yet. You would need at least 7.5 for that. (See https://docs.gradle.org/current/userguide/compatibility.html).
