### ISSUE TITLE
`init` task does nothing in 7.5.1 when configuration cache is enabled

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#22188]
### Expected Behavior
Running `gradle init` should work, similar to below:
```shell
$ sdk u gradle 7.5

Using gradle version 7.5 in this shell.

$ gradle init
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration cache is an incubating feature.
Reusing configuration cache.

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4]
```

### Current Behavior

In 7.5.1 (but not in 7.5), `gradle init` does nothing for me. Note that I have CC enabled globally in my `~/.gradle/gradle.properties`.
```shell
$ sdk u gradle 7.5.1

Using gradle version 7.5.1 in this shell.

$ gradle init
Configuration cache is an incubating feature.
Reusing configuration cache.

> Task :init SKIPPED
The settings file 'settings.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 406ms
1 actionable task: 1 up-to-date
Configuration cache entry reused.
```

Note that the message `"The settings file 'settings.gradle' already exists. Skipping build initialization."` is not true:
```shell
$ ls
# no output
```

When configuration cache is disabled, it works as expected:
```shell
gradle init --no-configuration-cache

Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
Enter selection (default: basic) [1..4]
```

### Context

Since I have CC enabled globally (to dogfood it), I was surprised when `gradle init` recently just didn't work. I use that task regularly for creating small sandbox projects to investigate issues in a more manageable context.

### Steps to Reproduce 

Use SDKMAN to manage your gradle installation, and then:
1. `sdk install gradle 7.5.1` (or `sdk use gradle 7.5.1`)
2. `gradle init --configuration-cache`
3. Observe.

Although, since in my case I can see gradle reusing the configuration cache, I'm not entirely sure how to get into that state in the first place. My recollection is that I had _just_ installed 7.5.1 globally and that was the first time I was using `gradle init` with that version, but that may not be true.

### Your Environment

I cannot produce a scan for this situation:
```
$ gradle init --scan
Configuration cache is an incubating feature.
Reusing configuration cache.

> Task :init SKIPPED
The settings file 'settings.gradle' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 380ms
1 actionable task: 1 executed
Configuration cache entry reused.
```

Note that no build scan URL was published for this.

**Comment by abstratt** [comment]
Can reproduce this with 7.4.2 as well. `gradle init --configuration-cache` will only do anything the first time it is invoked for a given Gradle version (unless you specify anything that would result in a cache miss, such as specifying a Gradle property).

**Comment by abstratt** [comment]
See also: https://github.com/gradle/gradle/issues/13456 - IOW, the `init` plugin is not compatible with configuration cache yet. One could argue it shouldn't have to be, and declaring its tasks as incompatible would give us correctness with no loss of performance in practice.

**Comment by bamboo** [comment]
> declaring its tasks as incompatible would give us correctness with no loss of performance in practice.

👍

**Comment by big-guy** [comment]
I think this is a dupe too https://github.com/gradle/gradle/issues/20156
