### ISSUE TITLE
Artifact names should be unique for subprojects with the same project name. 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#22201]
Consider a set up like below with 3 projects,  and then run `distTar` on this project: 

`settings.gradle.kts` :
```kotlin
pluginManagement.repositories.mavenCentral()
dependencyResolutionManagement.repositories.mavenCentral()

include("foo:bar:whevs", "hello:world:whevs", "allendpoints")
```

`foo/bar/whevs/build.gradle.kts` : 
```kotlin
plugins {
    kotlin("jvm")
}
```

`foo/bar/whevs/src/main/kotlin/foo/bar/Whevs.kt`: 
```kotlin
package foo.bar
fun whevs() = "foo bar"
```

`hello/world/whevs/build.gradle.kts` : 
```kotlin
plugins {
    kotlin("jvm")
}
```

`hello/world/whevs/src/main/kotlin/hello/world/Whevs.kt` :
```kotlin
package hello.world
fun whevs() = "hello world"
```

`allendpoints/build.gradle.kts` : 
```kotlin
plugins {
    kotlin("jvm")
    application
}

application {
    mainClass.set("foo.AllEndpointsKt")
}

dependencies {
    implementation(project(":foo:bar:whevs"))
    implementation(project(":hello:world:whevs"))
}
```

`allendpoints/src/main/kotlin/foo/AllEndpoints.kt` : 
```kotlin
package foo    
    
fun main() = println(hello.world.whevs() + " " + foo.bar.whevs())
```

### Expected Behavior

`distTar` should "just work" in the above project, because the default artifact names should, ideally, always be unique.

### Current Behavior

Causes duplicate errors when running  `distTar` task because both "foo:bar:whevs" and "hello:world:whevs" produce `whevs.jar`

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':allendpoints:distTar'.
> Entry allendpoints/lib/whevs.jar is a duplicate but no duplicate handling strategy has been set.
```

#### Workaround

If you add this in all your `build.gradle.kts` it will work around the issue. 

```kotlin
plugins {
    base
}
base {
    archivesName.set("${projectPathWithDots(path)}.$name")
}

fun projectPathWithDots(projectPath: String) =
    // convert project path to use dots (":foo:baz:whevs" -> "foo.baz")
    (projectPath.split(':').drop(1).dropLast(1)).joinToString(".")
```

See here: https://docs.gradle.org/current/userguide/base_plugin.html#sec:base_plugin_extension

### Your Environment
Gradle 7.5.1
macOS 12.5.1
JDK 17

**Comment by jbartok** [comment]
Duplicates #21028
