### ISSUE TITLE
Gradle options to control default caching policy times

### ISSUE THREAD

**Issue by MarkRx** [gradle/gradle#22228]
The default caching time for dynamic, changing, and missing artifacts is 24 hours. While this can be configured on a per-project level it would be useful to be able to configure it system wide in an enterprise build environment (such as Jenkins).

At present it is necessary to always run `--refresh-dependencies` in a build environment when using dynamic versions to ensure the latest version is pulled. Unfortunately this is more expensive than it needs to be as it does more than check of dynamic version updates and may be slow due to the lack of dynamic version lookup being resolved in parallel (https://github.com/gradle/gradle/issues/15071). 

### Expected Behavior
The dynamic, changing, and missing artifacts default cache time can be changed with a java property. These properties could be set globally with GRADLE_OPTS and be picked up by every build.

See https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolutionstrategy/DefaultCachePolicy.java#L59-L61

### Current Behavior
The dynamic, changing, and missing artifacts cache time can only be set on a per repository level. In a micro-service micro-repository environment this may require modifications in 100's of repositories. Additionally it may be desirable to have this value be different between build environments and local environments.

### Context
The lack of plugin BOM support in plugins management prevents us from being able to pull a single dynamic BOM with concrete dependency versions (https://github.com/gradle/gradle/issues/10315).

We can't just pull a "mother of all dependencies" dependency as not every dependency is needed in every case. This would result in unnecessary resolution and downloads.

Version catalogs would be a possibility but that would likewise require an effort to update 100's of repositories. Additionally the number of possible plugin combination permutations is high.

**Comment by rpalcolea** [comment]
Hello!

i think you should be able to accomplish this by shipping your CI agents with an init script in the gradle/user home folder https://docs.gradle.org/current/userguide/init_scripts.html

from the script you can definitely apply default behavior to projects, in this case changing the resolution strategy https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:controlling_dependency_caching_programmatically

with that said, it might also help to use dependency locks to make the build reproducible locally and CI and they will reduce your resolution time pain in addition to better build reproducibility. Gradle has support for this already https://docs.gradle.org/current/userguide/dependency_locking.html

**Comment by MarkRx** [comment]
The init script should work in this situation. I'll look in to it. Thanks.

We intentionally sacrifice potential build reproducibility in favor of having consumers automatically pull latest versions of our in-house gradle plugins as coordinating upgrades across a large enterprise is a many-month process.

Closing as using an init script is a reasonable way to achieve the stated objectives without requiring Gradle changes.
