### ISSUE TITLE
:ideaModule task does not contains all information about module

### ISSUE THREAD

**Issue by rougsig** [gradle/gradle#22233]
[Sample project](https://github.com/rougsig/gradle-idea-report-problem) 

### What's wrong
In `build.gradle` user adds these lines:
```groovy
sourceSets {
  custom {
    java {
      srcDir 'src/custom/java'
    }
  }
}
```

Idea recognise `srs/custom/java` as source root.
![image](https://user-images.githubusercontent.com/18681794/192882322-2b4a687f-0d8d-4b81-9a74-4dbe9528b3b3.png)
But `:ideaModule` task does not add `src/custom/java` as `sourceFolder`.

Result file from `:ideaModule` task `gradle-idea-report-problem.iml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module relativePaths="true" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output/>
    <orderEntry type="inheritedJdk"/>
    <content url="file://$MODULE_DIR$/">
      <sourceFolder url="file://$MODULE_DIR$/src/main/java" isTestSource="false"/>
      <excludeFolder url="file://$MODULE_DIR$/.gradle"/>
      <excludeFolder url="file://$MODULE_DIR$/build"/>
    </content>
    <orderEntry type="sourceFolder" forTests="false"/>
  </component>
  <component name="ModuleRootManager"/>
</module>
```

### How to reproduce
1. `git clone https://github.com/rougsig/gradle-idea-report-problem`
2. Open project in IDEA
3. Run `rm gradle-idea-report-problem.iml && ./gradlew ideaModule`
4. Compare `gradle-idea-report-problem.iml` report with `File > Project Structure`

### Questions
1. That difference between report and idea logic is expected behaviour?
2. If yes, How can I check in unit test what the IDEA knows about the `custom` sourceSet?

**Comment by donat** [comment]
This is expected. The `idea` plugin creates only one module per project which contains the main and test sources only. If you want to add another source set to the module you need to configure that explicitly
```
idea {
  module {
    sourceDirs += file('src/custom/java')
  }
}
```

Please note, that the `idea` plugin is now obsolete. The recommendation is to use IDEA's import functionality which uses a separate configuration model. The IDEA import can be customized via JetBrains' `idea-ext` [plugin](https://github.com/JetBrains/gradle-idea-ext-plugin/wiki).

**Comment by donat** [comment]
It is unlikely that this feature will be prioritized anytime soon by the Gradle team (due to reasons I've mentioned previously), so I'm closing this as not planned. At the same time, contributions are always welcome.
