### ISSUE TITLE
4.0 context error

### ISSUE THREAD

**Issue by zoe-sky** [gradle/gradle#2225]
当：
classpath 'com.android.tools.build:gradle:3.0.0-alpha2'
时候

public class ******Activity extends BaseActivity {

private BaseActivity context;

然后这么用的时候，编译没有问题，但context一直有红色下划线错误提示。
                Intent intent = new Intent();
                intent.setClass(context,nextActivity.class);
                startActivity(intent);

gradle 换成：
classpath 'com.android.tools.build:gradle:2.4.0-alpha7' 时候，一切安好。

**Comment by zoe-sky** [comment]
基本上工程里所有的context出问题了

**Comment by bmuschko** [comment]
Hi @zoe-sky,

I believe none of our team mates speaks your language. Could you please phrase your question in English? It also seems that your question is about the Android plugin. Would you mind asking on the [Google forum](https://code.google.com/p/android/issues) about this? Google is maintaining the plugin and is much better suited to give you a qualified answer.

**Comment by eriwen** [comment]
@zoe-sky 这似乎是Android工具的问题。 请通过https://developer.android.com/support.html提出问题
