### ISSUE TITLE
Gradle 7.6 (UnsupportedOperationException  -> PreResolvedResolvableArtifact.getModuleVersion)

### ISSUE THREAD

**Issue by gurpreetsingh85** [gradle/gradle#22279]
Builds after 7.6-20220920234319+0000 release are failing with above error. 
### Expected Behavior

Build should pass 

### Current Behavior

Build is failing when starting with a clean cache directory
### Context

Our jenkins pipelines clean caches before every build, hence we are unable to build with latest nightly releases

### Steps to Reproduce 

I have attached a demo project to try with

grade-wrapper.properties file has both release versions mentioned
distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-7.6-20220920234319+0000-all.zip
distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-7.6-20220930142900+0000-all.zip

There is no issue with builds using 20220920234319 release but every release after this is having this issue

Start by deleting `caches` directory in ~/.gradle folder.
running ./gradlew clean build --stacktrace will fail the first time (With 20220930142900)
running ./gradlew clean build --stacktrace will pass next time (With 20220930142900)

[demo.zip](https://github.com/gradle/gradle/files/9686755/demo.zip)
[stacktrace.txt](https://github.com/gradle/gradle/files/9686748/stacktrace.txt)

### Your Environment

MacOS - 12.6
JDK - 17
Spring Boot - 2.7.4

Build scan URL:

**Comment by jbartok** [comment]
Confirmed regression in `7.6`, behaves exactly as described.

**Comment by ljacomet** [comment]
Thanks a lot for trying out nightlies and reporting discovered issues!

The issue was introduced [in these commits](https://github.com/gradle/gradle/compare/9edc2fc6945a6968d7ac71985d77e04593480a61...d4f94bd96c2dfb7374cd71abbc4b1f628a2d6a2b) and is still present on the latest nightly.

Following up to get this fixed.
