### ISSUE TITLE
Allow to download gradle-wrapper.jar instead of checking it into the project.

### ISSUE THREAD

**Issue by raphw** [gradle/gradle#22290]
### Expected Behavior
Currently, Gradle Wrapper requires storing *gradle-wrapper.jar* within the project. While this is a minor file, it is a binary file and can be problematic to store in a project that is supposed to only contain source code.  To avoid this, I adjusted my scripts to download the wrapper file if it is not checked in, and I want to suggest to make this a [feature of Gradle](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-gradle-plugin/gradlew#L191). 

### Current Behavior
It is required to check in the *gradle-wrapper.jar*.

### Context
Many project health tools mark binary code within a project as problematic. Maven Wrapper offers an option to avoid this.

**Comment by vlsi** [comment]
This is a duplicate of https://github.com/gradle/gradle/issues/11816

**Comment by raphw** [comment]
I see. Thanks!
