### ISSUE TITLE
Dependency management issue of composite builds

### ISSUE THREAD

**Issue by vitaliyGoncharenko** [gradle/gradle#22294]
**Expected Behavior:**
- my plugin use dependency management block for versions of dependencies which are used in my plugin
`dependencyManagement {
    dependencies {
        dependency 'com.google.guava:guava:30.1.1-jre'
    }
}`
- include my plugin via plugin management block to app
`pluginManagement {
    repositories {
        gradlePluginPortal()
    }

    includeBuild("../../libs/myplugin")
}`
- apply plugin in plugins block
`plugins {
    id("myplugin.greeting")
}`

**Current Behavior:**
 I get an exception 'Could not find com.google.guava:guava:.'
Separately, the plugin was assembled successfully.

**Steps to Reproduce:**
To reproduce you can find code here https://github.com/vitaliyGoncharenko/gradle-composite-builds.
You should build myapp. 

**Build scan URL:** 
https://gradle.com/s/m5pgfuzmy4beu

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org/) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

----

When resolving plugins across included builds, the resolution context is the one of the resolving project. It consumes publications from the plugins build. The spring dependency management plugin only affects the project it is applied to.

I order to fix your use case you should tell your plugin build to publish resolved dependencies version.
See https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies Unfortunately the spring-dependency-management plugin doesn't work with composite builds.

Another avenue would be to not use the spring-dependency-management plugin but the Gradle's built-in support for BOM which is supported in composite builds. To achieve that you would need to add a `platform` project to your plugin build to declare dependencies, and then use the bom in the plugin build. See https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import

**Comment by tronku** [comment]
@eskatos how to use composite build along with BOM in gradle? it's failing, and there's no documentation regarding this, whether it's possible or not, can you please help?
