### ISSUE TITLE
Substitutking dependencies  by an included build is not work on rootproject but subProject

### ISSUE THREAD

**Issue by xhvvvv** [gradle/gradle#22291]
It seem likes a few people like to use gradle as there build tool，they are still would like to use the fucking old maven. So I hava no one to share my fucking questions for long fucking time, god dame, its too hard to find a gradle developer in chinese, every one is waiting for feed, no body wanner research.

### Expected Behavior

Substitutking dependencies  by an included build is should be work on rootproject.

### Current Behavior

Substitutking dependencies  by an included build is  worked on subprojects.

### Context

I hava many subprojces they must rely on one same project, I hope I just finish this in root build script that provide a allprojects block, but now I have to configure this with one by one in subprojces. 

Im creating a composing build project which has two included builds , one called A，the other is B.
Project A contains two subprojects  they are A1 and A2, also B contains many subprojects. 
when I try to rely on A1 in project B root build script，its not work and print the message like :
  "Could not resolve group:A1.
  Required by:
      project :B
  "
But when I try to rely on A1 in project B any subproject build script, its just be done. Im completely confused. Its there any configurations I had forget? 

### Steps to Reproduce 

Here is configurations :
~~~kotlin
Projects
rootProject.name = "Projects"
includeBuild("./Bomd")
includeBuild("./Basedement")
~~~
~~~kotlin
Bomd
    rootProject.name = "Bomd"
    include("Basic")
~~~
~~~kotlin
Basedement
    rootProject.name = "Basedement"
    include("MyHttp")
    include("JavaEntity")
    include("Tools")
    includeBuild(".")
~~~
hers is Bomd build.gradle.kts, it could not work.
~~~kotlin
allprojects {
    ......
    dependencies{
        api(group = "com.wxfactory", name ="JavaEntity")
    }
}
~~~
hers is Bomd's subproject Basic build.gradle.kts, it can be work.
~~~kotlin
dependencies {
    api(group = "com.wxfactory", name ="JavaEntity")
}
~~~
### Your Environment

Gradle V7.2 & JDK 17

**Comment by eskatos** [comment]
I would start by kindly reminding you that we have a code of conduct, so mind your language.

That being said, thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be better answered on our forums or StackOverflow. We have several resources on [help.gradle.org](https://help.gradle.org/) that you should check out first.

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
