### ISSUE TITLE
`Configuration.extendsFrom` throws `ClassCastException` if I pass in a custom implementation of the `Configuration` interface

### ISSUE THREAD

**Issue by PantherDD** [gradle/gradle#22327]
If I pass a custom implementation of the `Configuration` interface to `Configuration.extendsFrom`, the build fails with the following `ClassCastException` as the root cause:
```
Caused by: java.lang.ClassCastException: Build_gradle$MyConfiguration cannot be cast to org.gradle.api.internal.artifacts.configurations.ConfigurationInternal
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.extendsFrom(DefaultConfiguration.java:412)
	...
```

### Expected Behavior
According to its signature, `Configuration.extendsFrom(Configuration... extendsFrom)` should be able to handle any input object as long as it implements the `Configuration` interface.

### Current Behavior
Gradle's built-in implementation of the `Configuration` interface, `DefaultConfiguration` throws a `ClassCastException` when its `extendsFrom` method is called with a custom `Configuration` implementation, because it tries to [cast it to `ConfigurationInternal`](https://github.com/gradle/gradle/blob/v7.5.1/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L412). The only user-side solution to this would be to implement `ConfigurationInternal`, but the fact that it's both in a package named "internal" and is itself called "internal" tells me this would be against the intentions of the Gradle development team.

### Context
This is probably irrelevant to the issue itself, but I'll give you some context on why I was trying to call `Configuration.extendsFrom` with a custom `Configuration` class.

I created a `Configuration` decorator class that I wanted to use in a plugin as a means to track the configurations added to `configA`'s "extends" list by the plugin, and to be able to distinguish those from the ones added by the user manually. I am hoping it will also allow proper handling of use-cases where the plugin adds `configB` to the "extends" list, then the user may or may not add `configB` as well, then the plugin tries to remove the `configB` it has added. Without the decorator class, I have no way of knowing at the time the plugin needs to remove its own addition whether `configB` was also added by the user or not.  To make the plugin intuitive to use, it should not remove anything that the user has added manually.

### Steps to Reproduce
I created a `Configuration` decorator like so (Kotlin):
```kts
class MyConfiguration(private val configuration: Configuration) : Configuration by configuration {
    override fun toString(): String {
        return "my-" + super.toString()
    }
}
```
Then I tried to add a decorated `Configuration` to the "extends" list of another:
```kts
val baseConfig by configurations.creating
val extendedConfig by configurations.creating {
    extendsFrom(MyConfiguration(baseConfig))
}
```
This results in `ClassCastException: MyConfiguration cannot be cast to ConfigurationInternal`.

Reproduction available at: https://github.com/PantherDD/gradle-issue-22327

### Your Environment
Tested with Gradle `6.0` and `7.5.1`.

**Comment by jbartok** [comment]
Configurations aren't intended to be implemented by build authors, they weren't designed with that in mind.
