### ISSUE TITLE
[configruation cache] chained provider cache doesn't get invalidated on delegate change

### ISSUE THREAD

**Issue by monosoul** [gradle/gradle#22328]
### Expected Behavior

Invalidation of a provider's cache should cause invalidation of the cache of other providers dependent on it.

### Current Behavior

Invalidation of a provider's cache doesn't trigger invalidation of other providers' cache dependent on it.

### Context
Imagine a task having the following set of properties:
```kotlin
@InputFile
@PathSensitive(PathSensitivity.RELATIVE)
val someFile = objectFactory.fileProperty().convention(
    projectLayout.projectDirectory.file("src/main/resources/some_file.txt")
)

@Input
val maybeSomeFileContent = objectFactory.property<String>().convention(
    someFile.map { it.asFile.readText() }
)
```

Where `maybeSomeFileContent` by default has `someFile`'s content as it's value, but might have a different value (if the plugin user decides to configure it differently).

If you run the task once Gradle will remember it's state and next time you run it it will be reported as `up-to-date`.

If you change the content of `some_file.txt`, Gradle will mark the task as `out-of-date` and will run it again.

Without configuration cache everything will work as expected and `maybeSomeFileContent`'s value will change next time you run the task after changing `some_file.txt`.

With configuration cache enabled Gradle will run the task again, but `maybeSomeFileContent`'s value will not change (cached value will be used).

### Steps to Reproduce 
Here's a reproducer repo: https://github.com/monosoul/gradle-configuration-cache-issue

`GradleConfigurationCacheIssuePluginFunctionalTest` there has 2 test cases to demonstrate the behavior with and without configuration cache. The test case with configuration cache enabled [fails at the moment](https://github.com/monosoul/gradle-configuration-cache-issue/actions/runs/3196976824).

### Your Environment
Reproducible with Gradle 7.5.1 (and probably older releases having configuration cache).

**Comment by monosoul** [comment]
Just in case: I tested this with Gradle 7.6 and the latest release nightly (`8.0-20221210002516+0000`), still reproducible

**Comment by mlopatkin** [comment]
Looks like configuration cache machinery cannot infer the fact that the value of `someFile.map { it.asFile.readText() }` can change between builds - we don't look into the provided transform.

You can work around this issue by being a bit more explicit about your intentions:
```kotlin
 @Input
 val maybeSomeFileContent = objectFactory.property<String>().convention(providers.fileContents(someFile).asText)
```
where `providers` is an instance of `ProviderFactory`. The meaning of `fileContents` is known to Gradle, so the resulting provider can be properly cached with change tracking enabled.

**Comment by monosoul** [comment]
Hey @mlopatkin , thanks, that did the trick!
