### ISSUE TITLE
How about adding JBR as known java toolchain vendor?

### ISSUE THREAD

**Issue by tmvkrpxl0** [gradle/gradle#22329]
Currently `JvmVendorSpec` does not have entry for Jetbrain runtime, so java toolchain configuration can't choose it as an option. I think it would be good to add it.

### Expected Behavior

I expected Gradle to know JBR's existence and recognize it as one of vendors.

### Current Behavior
It's not aware of JBR and can't use it as an option.

### Context

It doesn't affect me much since I just set project's sdk as JBR from Intellij Idea so it is used as default for gradle.
The strength of JBR is that it works quite well with code hot-swapping, it even has DCEVM built-in. that is why I feel like there would be significant number of people using it with gradle.

**Comment by jbartok** [comment]
You should be able to request the JetBrains Runtime like this: `JvmVendorSpec.matching("JetBrains")`.
Yes, a named entry should be coming at some point.

**Comment by eskatos** [comment]
Fixed in Gradle 8.4 by
* https://github.com/gradle/gradle/pull/26014
