### ISSUE TITLE
Build issue with Jenkins..its getting stuck 

### ISSUE THREAD

**Issue by Sushilk-31** [gradle/gradle#22343]
Started by user [admin](http://54.251.211.233:8080/user/admin)
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/buildjobgradle
The recommended git tool is: NONE
using credential 00ac0571-894f-486e-9c1e-32573e175c45
 > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/buildjobgradle/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/Sushilk-31/Jenkins-Demo.git # timeout=10
Fetching upstream changes from https://github.com/Sushilk-31/Jenkins-Demo.git
 > git --version # timeout=10
 > git --version # 'git version 2.37.1'
using GIT_ASKPASS to set credentials github
 > git fetch --tags --force --progress -- https://github.com/Sushilk-31/Jenkins-Demo.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/dev^{commit} # timeout=10
Checking out Revision a62d4612a2a6df1c71f09ae6e7000f2f32c0aed7 (refs/remotes/origin/dev)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a62d4612a2a6df1c71f09ae6e7000f2f32c0aed7 # timeout=10
Commit message: "Merge pull request #2 from sureshwadzpay/dev_suresh"
 > git rev-list --no-walk a62d4612a2a6df1c71f09ae6e7000f2f32c0aed7 # timeout=10
[Gradle] - Launching build.
[buildjobgradle] $ /opt/gradle/bin/gradle --scan -s gradlew clean build
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

![image](https://user-images.githubusercontent.com/115229070/194698187-1ba44a7b-b27f-4f05-b001-db2c7ddaf214.png)

**Comment by brandon1024** [comment]
@Sushilk-31 This is a very poor issue; there's very little to go off of here. You'll want to include more details if you want any chance of getting help.

Here are some items you may want to include in your description:
- the gradle version used
- information about the environment (where/how is jenkins hosted? memory/sizing of the jenkins host? networking/proxying?)
- does gradle build successfully when run locally?
- what have you tried to diagnose these issues? have you tried without '--scan'? have you tried splitting up each task as a separate command? have you tried running without a daemon?

What does the 'gradlew' task do? I've never heard of it, so I can only assume it's a custom task. Do you mean 'wrapper'?

**Comment by blindpirate** [comment]
Agree with @brandon1024 .

In theory, you can easily write a build script with `Thread.sleep(100000)` to get the build stuck, so it's impossible to help without more  information. What I would do is:

- ssh to the machine, i.e. `54.251.211.233`.
- Run `jps` to find out which process is stuck.
- Run `jstack <the_pid_of_stuck_JVM>` to see what's going on.

Closing this as it doesn't seem like a Gradle issue.
