### ISSUE TITLE
Application start scripts don't let the java command process @argfile arguments

### ISSUE THREAD

**Issue by joffrey-bion** [gradle/gradle#22356]
When running my application using `java` directly, I can run:

```
java @args-file.txt
```

With `args-file.txt` containing:
```
-cp
"build/install/arg-file-tester/lib/annotations-13.0.jar;\
build/install/arg-file-tester/lib/arg-file-tester-1.0-SNAPSHOT.jar;\
build/install/arg-file-tester/lib/kotlin-stdlib-1.7.0.jar;\
build/install/arg-file-tester/lib/kotlin-stdlib-common-1.7.0.jar;\
build/install/arg-file-tester/lib/kotlin-stdlib-jdk7-1.7.0.jar;\
build/install/arg-file-tester/lib/kotlin-stdlib-jdk8-1.7.0.jar"
com.example.ArgFileTesterKt
arg1
arg2 arg3
```

And in that case my program outputs:
```
Arguments (surrounded with [] to highlight whitespace):
0: [arg1]
1: [arg2]
2: [arg3]
```

Now, if I run it via the Gradle-generated start script (when packaged with the application plugin) like this:

```
./build/install/arg-file-tester/bin/arg-file-tester @arg-file.txt
```

I get:
```
Arguments (surrounded with [] to highlight whitespace):
0: [@arg-file.txt]
```

### Expected Behavior

Gradle start script doesn't prevent Java's arg file expansion.

### Current Behavior

Gradle start script prevents args file expansion. Probably that start script escapes arguments in a way that prevents the `java` command from performing the expansion.

### Context

I am facing long command lines issues when running my app on Windows, and args files are a nice way to work around this.
I noticed I cannot use args files by default when packaging my app with Gradle, so it forces me to implement it myself inside the application.

### Steps to Reproduce 

See attached project. Unzip it, run `./gradlew installDist` and then run either `./run-with-argfile-bin.sh` or `./run-with-argfile-java.sh` to see the 2 different behaviours.

[arg-file-tester.zip](https://github.com/gradle/gradle/files/9757989/arg-file-tester.zip)

### Your Environment

I'm building and running this on Windows. I run the shell scripts inside IDEA's terminal using Git bash.

**Comment by big-guy** [comment]
When calling the script generated by Gradle for your application, you're passing the application arguments, not the Java arguments for the JVM running the application. 

If you wanted to change the JVM arguments, there are environment variables you can set or you can adjust the generated script. `@arg-file` doesn't really fit into either of these. 

If your arg file only contained:
```
arg1
arg2 arg3
```
You could add support for an `@arg-file` to your own application.  I don't think you want to include the main class name or classpath.
