### ISSUE TITLE
Signing publications should be idempotent

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#22375]
Signing a publication more than once causes the following error:

```
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'signMavenJavaPublication' as a task with that name already exists.
```

The plugin should be idempotent for this situation and potentially other cases (e.g. configuration signing).

**Comment by vlsi** [comment]
This is a duplicate of https://github.com/gradle/gradle/issues/21857

**Comment by jbartok** [comment]
> This is a duplicate of #21857

@vlsi , thank you for pointing that out.
