### ISSUE TITLE
Console output rendering issue

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#2238]
I noticed weird rendering issue with the new console in 4.0 RC1:

Sometimes the status line is mixed with task status:

<img width="327" alt="screen shot 2017-06-02 at 16 36 36" src="https://cloud.githubusercontent.com/assets/1292566/26730706/18a08124-47b2-11e7-9d8b-a5c9286e916f.png">

Sometimes task status completely replaces the status line (the following is displayed instead of EXECUTING etc):

<img width="334" alt="screen shot 2017-06-02 at 16 36 28" src="https://cloud.githubusercontent.com/assets/1292566/26730701/1516e084-47b2-11e7-94d0-2aaae0e33074.png">

**Comment by eriwen** [comment]
This is very similar to #2210. Can you think of any particular interaction or thing about your project that might make this issue distinct from others?

**Comment by pioterj** [comment]
I can't think of anything special. I'll try again on nightly once https://github.com/gradle/gradle/pull/2234 is merged.

**Comment by lacasseio** [comment]
I'm almost positively sure it's related to #2234.

**Comment by eriwen** [comment]
@pioterj Ben has merged a fix. Can you please verify by trying what's on `release`?

**Comment by bmuschko** [comment]
@pioterj Please make sure to build a local installation. The wrapper has not been updated yet.

**Comment by pioterj** [comment]
I checked on installation from release branch and I don't see it anymore.

**Comment by pioterj** [comment]
Actually, I can't reproduce on 4.0-rc-1 either. Looks like it wasn't deterministic. I think it's fine to close it.
