### ISSUE TITLE
Provide a public API for plugin authors in order to add deprecation warnings to builds

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#22407]
One of the great features of Build Scans is the ability of seeing deprecation warnings for my build.  Unfortunately, there isn't a public API to contribute to these warnings.

Historically, we relied on `BuildOperationProgressEventEmitter` which is very internal and already changing in future versions of the tool per https://github.com/gradle/gradle/commit/36157128988a0b980a729be074c63bcece0da1a2#diff-3e4a4167ab308c5595d823159fa43c783a9759a5bb09dc98b7038e87e6da391a

Another option is to use `DeprecationLogger` but it has very specific Gradle level DSL and also it has evolved over time and it is difficult for backwards compatibility when trying to build plugins 

### Expected Behavior
Ideally as plugin author I should be able to add a deprecation warning with similar context:

* `summary`
* `removalDetails`
* `advice`
* `documentationUrl` 

In addition, shipping these deprecations to build scans would be a great to have in order to surface these to users

### Current Behavior
As plugin author I have to rely on internal APIs, not ideal as the tool evolves and keeping backwards compatibility is challenging

**Comment by jbartok** [comment]
Duplicate #15021
