### ISSUE TITLE
ResolvableDependencies.artifactView() always returns file dependencies on top

### ISSUE THREAD

**Issue by agolubev** [gradle/gradle#22438]
Created test project to illustrate the idea 

Dependencies look like following
```
dependencies {
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation project(':patch')
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation files('../deps/app-release.aar')
    implementation 'com.google.android.material:material:1.6.1'
    implementation project(':patch2')
....
```
Following code in custom task print dependencies as return by Gradle API
```
        Configuration config = configurations.debugRuntimeClasspath {
            transitive = false
        }
        // prints dependencies in declaration order
        def rc = config.getAllDependencies()
        for (def rs in rc) {
            if (rs.resolve().toString() == 'null' || rs.resolve().toString() == "[]") 
                println(rs) else println(rs.resolve())
        }

        // prints dependencies with file import on top
        def artifactType = Attribute.of('artifactType', String)
        config
                .incoming
                .artifactView {
                    attributes {
                        it.attribute(artifactType, "android-res")
                    }
                    it.lenient(false)
                }.files.each { println "artifact file: ${it}" }
```

### Expected Behavior
Probably `artifactView` should mimic other APIs and return dependencies in the same order as declared 

### Current Behavior
artifactView returns file dependency always on the top. Repository and module dependencies stays in the declared order.

### Context
Experimented with android project but dependency API is from Gradle

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.

----

Pls. provide a FULL reproducer to make our investigation a bit easier.
