### ISSUE TITLE
Imported class is not recognized in the root build.gradle.kts 

### ISSUE THREAD

**Issue by Drjacky** [gradle/gradle#22444]
root build.gradle.kts:
```kotlin
import com.example.buildsrc.Depends
.
.
.
plugins {
    id("org.sonarqube") version com.example.buildsrc.Depends.Versions.sonarqubeVersion //OK
    id("org.sonarqube") version Depends.Versions.sonarqubeVersion //NOT OK
```

> e: .../build.gradle.kts:6:49: Unresolved reference: Depends

**Comment by jbartok** [comment]
That is expected. The `plugins` block is evaluated in isolation so the code it has access to is very limited. 
Pls. see here: https://docs.gradle.org/current/userguide/plugins.html#plugins_dsl_limitations
