### ISSUE TITLE
User Guide for Groovy Quickstart doesn't work, project won't build

### ISSUE THREAD

**Issue by wodencafe** [gradle/gradle#2245]
I have followed the instructions from the Gradle 3.5 User Guide, for "Groovy Quickstart" found here:
https://docs.gradle.org/3.5/userguide/tutorial_groovy_projects.html

![screen05](https://cloud.githubusercontent.com/assets/9727493/26763274/c841fb08-4915-11e7-95f1-8e46d5946dc9.png)

My build.gradle is configured exactly like in the guide, and I have a settings.gradle including only this project.

**Main.java:**
```
package com.foo.main;
import com.foo.main.GroovyClass;
public class Main {
	public static void main(String[] args) {
		GroovyClass gc;
	}
}
```
**GroovyClass.groovy:**
```
package com.foo.main
class GroovyClass {
}
```

Eclipse is perfectly happy with this setup, but on the Command Line, when I run a gradle build, Main class cannot see GroovyClass.

```
~/workspaces/jobe/GroovyTest ./gradlew build                                                                                                                                     
:compileJava                                                                                                                                                                                         
/home/wodencafe/workspace/GroovyTest/src/main/java/com/foo/main/Main.java:3: error: cannot find symbol                                                                                             
import com.foo.main.GroovyClass;                                                                                                                                                                     
                   ^
  symbol:   class GroovyClass
  location: package com.foo.main
/home/wodencafe/workspace/GroovyTest/src/main/java/com/foo/main/Main.java:8: error: cannot find symbol
                GroovyClass gc;
                ^
  symbol:   class GroovyClass
  location: class Main
2 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
```
 
### Expected Behavior
This should build just like other projects. Gradle classes should be visible and usable to Java classes.

### Current Behavior
For some reason, Main does not know about GroovyClass.
This looks like a bug, as Eclipse itself is perfectly happy with this and not reporting any errors.

### Context
We are working on a mixed Groovy - Java project and would like to use Gradle to build it. 

### Steps to Reproduce (for bugs)
I uploaded this sample project here: https://github.com/wodencafe/example-groovy-gradle-bug
Using these instructions, you can replicate this bug (these may be different if you are on Windows):
```
git clone https://github.com/wodencafe/example-groovy-gradle-bug
cd example-groovy-gradle-bug
./gradlew build
```

### Your Environment
```
Ubuntu 17.04 Zesty (Kernel: 4.10.0-21-generic)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.10.0-21-generic amd64
```

**Comment by bmuschko** [comment]
You are using Java and Groovy source code in the same project which requires additional configuration. You'll need to enable joint compilation.

```
sourceSets.main.java.srcDirs = []
sourceSets.main.groovy.srcDirs = ['src/main/java', 'src/main/groovy']
```

I am not quite sure why Eclipse works.

[Chapter 55. Groovy Quickstart](https://docs.gradle.org/3.5/userguide/tutorial_groovy_projects.html) refers to the sample project in `samples/groovy/quickstart` which only uses Groovy sources.

**Comment by wodencafe** [comment]
Hi @bmuschko , thanks for the follow up, this change did fix the behavior.
