### ISSUE TITLE
Module export rules needed with java17 defined via options.compilerArg are not applied to annotation processor

### ISSUE THREAD

**Issue by abelom** [gradle/gradle#22453]
### Expected Behavior
There should be a way to specify module export rules for those to apply to annotation processor

### Current Behavior
only able to set module rules via global gradle JVM gradle.properies

### Context
We have a happy codebase which works fine under java 11. JDK17 imposes additional module export requirments around javac internal API usages by our annotation processor, we are unable to set such rules locally just for specific compilation task. As a workaround we set export rules globally. Both problematic and workaround versions are attached.

How we believe it export rules should be added does not get the job done see attached project
```
compileJava {
    options.compilerArgs += ["--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
                             "--add-exports=jdk.compiler/sun.nio.ch=ALL-UNNAMED"]
   }
```

how we work around the issue
```
org.gradle.jvmargs= --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
 --add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
 --add-exports=jdk.compiler/sun.nio.ch=ALL-UNNAMED \
 --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
```
[devexperts-17-workaround.zip](https://github.com/gradle/gradle/files/9822041/devexperts-17-workaround.zip)
[devexperts-17-issue.zip](https://github.com/gradle/gradle/files/9822042/devexperts-17-issue.zip)

This adds steps-to-reproduce for https://github.com/gradle/gradle/issues/21310
This is a duplicate of https://github.com/gradle/gradle/issues/22065 where we have failed to express ourselves

**Comment by xaviarias** [comment]
Hi @abelom, I've tried to reproduce your issue but the project without the workaround builds successfully using Java 17 Temurin and Gradle 7.5.1.

Indeed the project fails to build when removing the `add-exports` from the build file:

```
* What went wrong:
Execution failed for task ':compileJava'.
> superclass access check failed: class com.devexperts.uilocalizer.AddLocalizationNodesVisitor (in unnamed module @0x7ba528ef) cannot access class com.sun.tools.javac.tree.JCTree$Visitor (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.tree to unnamed module @0x7ba528ef
```

Could you please provide more details on your issue in order to reproduce it? Thanks

**Comment by xaviarias** [comment]
Closing as not reproducible. Please feel free to reopen when providing the required information.

**Comment by xxDark** [comment]
Faced the same problem. Setting `org.gradle.jvmargs` did nothing.
What worked:
```groovy
    tasks.withType(JavaCompile).configureEach {
        options.forkOptions.jvmArgs += ['--add-opens=java.base/java.lang=ALL-UNNAMED']
        options.fork = true
    }
```
```kotlin
plugins {
    id("dev.xdark.betterrepeatable") version "1.2"
}
```
[AP](https://github.com/xxDark/better-repeatable) in question.
