### ISSUE TITLE
Issue with parallel project model building

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#22464]
7.6 nightlies have introduced a regression in the support for parallel project model building with the tooling API.

Users are seeing issues like:
* Cannot query the value of this property because it has no value available. - caused by task being configured from multiple threads
* java.lang.ArrayIndexOutOfBoundsException: Index 50331648 out of bounds for length 162
* Caused by: java.util.ConcurrentModificationException:

There is supposed to be some synchronization and memoization around the artifacts, so that it’s safe to do dependency resolution from multiple model builders in parallel.

**Comment by adammurdoch** [comment]
Should be fixed via https://github.com/gradle/gradle/pull/22488

**Comment by ljacomet** [comment]
Fix has been confirmed, closing
