### ISSUE TITLE
Update java-library compatibility workaround for 4.0-rc1

### ISSUE THREAD

**Issue by fkorotkov** [gradle/gradle#2246]
Workaround for `java-library` plugin to work correctly with other plugins described [here](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_known_issues_compat):

```
configurations {
    apiElements {
        outgoing.variants.getByName('classes').artifact(
            file: compileGroovy.destinationDir,
            type: JavaPlugin.CLASS_DIRECTORY,
            builtBy: compileGroovy)
    }
}
```

is failing with:

```
> No such property: CLASS_DIRECTORY for class: org.gradle.api.plugins.JavaPlugin
```

**Comment by bmuschko** [comment]
The constant now lives in a different class: `ArtifactTypeDefinition.JVM_CLASS_DIRECTORY`. You'll need to check the [documentation for 4.0-rc1](https://docs.gradle.org/4.0-rc-1/userguide/java_library_plugin.html#sec:java_library_known_issues_compat) instead.
