### ISSUE TITLE
Build cache messages are relatively noisy for new console output

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2247]
For a composite build with build cache enabled, the default console output is something like:
```
Parallel execution is an incubating feature.                                                                                                                                                                     
Build cache is an incubating feature.                                                                                                                                                                            
Using local directory build cache for build ':buildSrc' (location = /Users/sterling/.gradle/caches/build-cache-1).                                                                                               
[composite-build] Configuring build: /Users/sterling/gits/tmp/java-mp/shared                                                                                                                                     
Build scan data will not be captured due to this build being a Composite Build.                                                                                                                                  
Using local directory build cache for the root build (location = /Users/sterling/.gradle/caches/build-cache-1).                                                                                                  
Using local directory build cache for build ':shared' (location = /Users/sterling/.gradle/caches/build-cache-1).                                                                                                 
```

In the interest in removing non-actionable logging from the default view, I'd suggest that the 3 `Using local directory build cache for` lines should be logged at `--info` instead of `lifecycle`.
I'm going to remove the `[composite-build]` line from here too.

**Comment by big-guy** [comment]
+1 for this.  We only added the message because it was hard to find this information any other way and it was difficult to configure the build cache before we had the DSL.

**Comment by eriwen** [comment]
@big-guy I trust you to make the call on whether we include this in 4.0 or not.

**Comment by eriwen** [comment]
☝️ or @lptr or @wolfs since technically it's on them ;)

**Comment by wolfs** [comment]
I agree that we should move the logging to the info log level.
Still, I think we should not make the change for 4.0 but for 4.1. The main reason is that I would want to change as little as possible between RCs. This would also mean that for 4.0 the build cache is still a little bit more prominent in the logs.

**Comment by wolfs** [comment]
We are logging the build cache configuration on info level on `master`: https://github.com/gradle/gradle/commit/2e4f82fee4cfea71f540e2af28549d78c70879fe
