### ISSUE TITLE
Disable Https check so hard

### ISSUE THREAD

**Issue by TianJieYouYue** [gradle/gradle#22474]
Gradle use apache http client download files, not HttpsURLConnection.
Some env ,https need to be disable,

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.
