### ISSUE TITLE
Input snapshotting fails if an input class is removed

### ISSUE THREAD

**Issue by melix** [gradle/gradle#22476]
### Expected Behavior

Input snapshotting shouldn't try to load classes which are not present anymore.

### Current Behavior

Input snapshotting probably wants to compare inputs from a previous build, where a type existed, with the current build, where it doesn't, failing with a `ClassNotFoundException`.

### Context

In Micronaut Core, we had a branch which showed a suspicious class not found exception: https://ge.micronaut.io/s/gll4myo3ifrry/failure?expanded-stacktrace=WyIwLTEtMi0zIl0#1

The class which is mentioned is `io.micronaut.build.internal.japicmp.RemovedPackages` which is _not_ found in [the branch being built](https://github.com/micronaut-projects/micronaut-core/pull/8199).

However, that class is present on the "main" branch:

https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/core/build.gradle#L49-L53

So if you build with the `4.0.x` branch first, _then_ switch to the failing branch, the snapshotter tries to compare inputs and on the new branch, the `RemovedPackages` class is _missing_, but it shouldn't fail: it should simply say out of date.

### Steps to reproduce

1. checkout https://github.com/micronaut-projects/micronaut-core.git
2. switch to the `4.0.x` branch
3. run `./gradlew :core:japiCmp`, [see the build pass](https://ge.micronaut.io/s/odkzsjngii54g)
4. checkout the `deprecate-status` branch, run `./gradlew :core:japiCmp` and [see the build fail](https://ge.micronaut.io/s/ovlybkmxiuatu
)
5. delete the execution history: rm -Rf .gradle/7.5.1/executionHistory
6. run `./gradlew japiCmp` to discard the task execution history, and [see the build pass](https://ge.micronaut.io/s/zp4xtfr7cc7og)

### Your environment

Gradle 7.5.1

**Comment by wolfs** [comment]
@melix Thank you for raising the issue. I think this is because Gradle did fall back for using equals when comparing input values. Gradle 8 won't do this anymore and I think https://github.com/gradle/gradle/pull/21605 should fix the issue. Can you try out with an 8.0 nightly if this still is a problem?

**Comment by melix** [comment]
I can confirm the issue is gone with a snapshot version of Gradle 8, thanks!
