### ISSUE TITLE
java.sourceSets.main.output.classesDirs no longer depends on the classes task in Gradle 7.6

### ISSUE THREAD

**Issue by scott-pollom** [gradle/gradle#22484]
Breaking change starting with Gradle 7.6-20221014231703+0000.

See [this AGP bug](https://issuetracker.google.com/issues/253219347#comment12) for context.

`java.sourceSets.main.output.classesDirs` no longer depends on the `classes` task.

In the attached [bug_repro.zip](https://github.com/gradle/gradle/files/9843555/bug_repro.zip), running `./gradlew bar --dry-run` has the following output with Gradle 7.4:

```
:compileJava SKIPPED
:foo SKIPPED
:processResources SKIPPED
:classes SKIPPED
:bar SKIPPED
```

But with Gradle 7.6-20221014231703+0000 it has the following output:

```
:compileJava SKIPPED
:bar SKIPPED
```

The issue is that the bar task adds `java.sourceSets.main.output.classesDirs` to its input, which has a dependency on the `classes` task in Gradle 7.4, but has a dependency on only the `javaCompile` task starting with Gradle 7.6-20221014231703+0000.

**Comment by liutikas** [comment]
Note the regression happened via one of these commits https://github.com/gradle/gradle/compare/bc01957e03b6ee2f2c7163390eda0295db8430df...96a78dfc1ee9fc8146b73197ff37a787e3e0450a

**Comment by jvandort** [comment]
Fixed by https://github.com/gradle/gradle/pull/22498
