### ISSUE TITLE
publishToMavenLocal does not generate checksums

### ISSUE THREAD

**Issue by JacksonBailey** [gradle/gradle#22482]
### Expected Behavior

`publishToMavenLocal` (and `publish<publication name>ToMavenLocal`) should behave the same as `publish` *(apart from where the files get sent of course)*

### Current Behavior

`./gradlew publish` will properly make checksums (e.g., `<artifactId>-<version>.jar.sha256`) but `./gradlew publishToMavenLocal` does not.

### Context

I am using `publishToMavenLocal` to easily test that the settings I have in my build would properly make everything I need to publish to Maven Central. I would expect `publishToMavenLocal` to behave the same as `publish` as most of the documentation seems to suggest it does. [For example,](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:install)

> The Maven Publish Plugin makes this easy to do by ***automatically creating a [PublishToMavenLocal](https://docs.gradle.org/current/javadoc/org/gradle/api/publish/maven/tasks/PublishToMavenLocal.html) task for each [MavenPublication](https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html) in the publishing.publications container.*** The task name follows the pattern of publishPubNamePublicationToMavenLocal. Each of these tasks is wired into the publishToMavenLocal aggregate task. You do not need to have mavenLocal() in your publishing.repositories section.

[And here,](https://docs.gradle.org/current/userguide/publishing_setup.html)

> #### What to publish
>
> Gradle needs to know what files and information to publish so that consumers can use your project. This is typically a combination of [artifacts](https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_artifact) and metadata that Gradle calls a [publication](https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_publication). Exactly what a publication contains depends on the type of repository it’s being published to.
>
> For example, a publication destined for a Maven repository includes:
>
> - One or more artifacts — typically built by the project,
>
> - The Gradle Module Metadata file which will describe the variants of the published component,
>
> - The Maven POM file will identify the primary artifact and its dependencies. The primary artifact is typically the project’s production JAR and secondary artifacts might consist of "-sources" and "-javadoc" JARs.
>
> ***In addition, Gradle will publish checksums for all of the above***, and [signatures](https://docs.gradle.org/current/userguide/publishing_signing.html#publishing_maven:signing) when configured to do so. From Gradle 6.0 onwards, this includes SHA256 and SHA512 checksums.

I don't think I am alone in getting confused by this behavior. While I was trying to figure out what is going on I stumbled on this [StackOverflow post](https://stackoverflow.com/q/56860757/1858327) but someone who was trying to prep for upload to Maven Central (just like me)

> I have a Java project that makes use of Gradle to build and package. My purpose is to create artifacts that are published to Maven Central.
> 
> As a first step, I configured my Gradle project as shown in the following example from the documentation:
> 
> https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example
> 
> When I run `gradle publishToMavenLocal`, I get the following files installed in my local repository:
> 
> > maven-metadata-local.xml   
> > my-library-1.0.2-SNAPSHOT.jar  
> > my-library-1.0.2-SNAPSHOT.jar.asc  
> > my-library-1.0.2-SNAPSHOT-javadoc.jar  
> > my-library-1.0.2-SNAPSHOT-javadoc.jar.asc  
> > my-library-1.0.2-SNAPSHOT.pom   
> > my-library-1.0.2-SNAPSHOT.pom.asc  
> > my-library-1.0.2-SNAPSHOT-sources.jar  
> > my-library-1.0.2-SNAPSHOT-sources.jar.asc
> 
> The files are all OK. ***The only issue I have is that checksum files (md5 and sha1) are not generated. However, checksum files are a requirement to have artifacts deployed on Maven Central via OSS Sonatype.***
> 
> How can I generate the missing checksum files? It seems the _maven-publish_ or _signing_ plugins do not have an option for this purpose? what is wrong?

### Steps to Reproduce 

Repro repo: https://github.com/JacksonBailey/publish-local-bug

1. `git clone https://github.com/JacksonBailey/publish-local-bug.git`
2. `cd publish-local-bug`
3. `git switch kotlin-dsl`
4. `./gradlew build publish publishToMavenLocal --info` (`--info` is just for logs)
5. Compare the contents of Maven Local `ls -al ~/.m2/repository/org/example/reproducer-project/1.0.2/` to the "real" repository `ls -al build/publishing-repository/org/example/reproducer-project/1.0.2/`.

The GitHub Action shows the output [here](https://github.com/JacksonBailey/publish-local-bug/actions/runs/3300559616/jobs/5445182176), just expand the tasks beginning with `ls -al`.

Here's the local output.

```
$ ls -al ~/.m2/repository/org/example/reproducer-project/1.0.2/
total 16
drwxr-xr-x 1 Jackson 197609    0 Oct 21 17:19 ./
drwxr-xr-x 1 Jackson 197609    0 Oct 21 17:19 ../
-rw-r--r-- 1 Jackson 197609  763 Oct 21 17:19 reproducer-project-1.0.2.jar
-rw-r--r-- 1 Jackson 197609 1921 Oct 21 17:19 reproducer-project-1.0.2.module
-rw-r--r-- 1 Jackson 197609  773 Oct 21 17:19 reproducer-project-1.0.2.pom

$ ls -al build/publishing-repository/org/example/reproducer-project/1.0.2/
total 32
drwxr-xr-x 1 Jackson 197609    0 Oct 21 17:19 ./
drwxr-xr-x 1 Jackson 197609    0 Oct 21 17:19 ../
-rw-r--r-- 1 Jackson 197609  763 Oct 21 17:19 reproducer-project-1.0.2.jar
-rw-r--r-- 1 Jackson 197609   32 Oct 21 17:19 reproducer-project-1.0.2.jar.md5
-rw-r--r-- 1 Jackson 197609   40 Oct 21 17:19 reproducer-project-1.0.2.jar.sha1
-rw-r--r-- 1 Jackson 197609   64 Oct 21 17:19 reproducer-project-1.0.2.jar.sha256
-rw-r--r-- 1 Jackson 197609  128 Oct 21 17:19 reproducer-project-1.0.2.jar.sha512
-rw-r--r-- 1 Jackson 197609 1921 Oct 21 17:19 reproducer-project-1.0.2.module
-rw-r--r-- 1 Jackson 197609   32 Oct 21 17:19 reproducer-project-1.0.2.module.md5
-rw-r--r-- 1 Jackson 197609   40 Oct 21 17:19 reproducer-project-1.0.2.module.sha1
-rw-r--r-- 1 Jackson 197609   64 Oct 21 17:19 reproducer-project-1.0.2.module.sha256
-rw-r--r-- 1 Jackson 197609  128 Oct 21 17:19 reproducer-project-1.0.2.module.sha512
-rw-r--r-- 1 Jackson 197609  773 Oct 21 17:19 reproducer-project-1.0.2.pom
-rw-r--r-- 1 Jackson 197609   32 Oct 21 17:19 reproducer-project-1.0.2.pom.md5
-rw-r--r-- 1 Jackson 197609   40 Oct 21 17:19 reproducer-project-1.0.2.pom.sha1
-rw-r--r-- 1 Jackson 197609   64 Oct 21 17:19 reproducer-project-1.0.2.pom.sha256
-rw-r--r-- 1 Jackson 197609  128 Oct 21 17:19 reproducer-project-1.0.2.pom.sha512
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/wccl7ryjygt5c

**Comment by ljacomet** [comment]
The behavior of Gradle is actually matching what happens with `mvn install` which also do not create any checksum files in the local maven repository.
Maven local just behaves weirdly in a number of ways due to the way it works in Maven itself.


The real way to validate what you will publish is correct is to use a dedicated file based repository. as you discovered yourself.

We could clarify that in the documentation so that folks having the same question can figure that out.

**Comment by JacksonBailey** [comment]
Thanks, I think specifying that somewhere in the docs would be super useful. Getting things into Maven Central feels like a puzzle almost haha, but a lot of that is due to their (understandable) strictness, not Gradle. This will help guide people in the right direction.
