### ISSUE TITLE
Init script plugins do not respect the classpath set via GradleRunner.withPluginClasspath 

### ISSUE THREAD

**Issue by assimd** [gradle/gradle#2250]
I have an [init script plugin](https://docs.gradle.org/3.5/userguide/init_scripts.html#sec:init_script_plugins) that configures all the `allprojects` by accessing a class and adding it as a convention and I am trying to write a functional tests for the same using GradleRunner. 

`GradleRunner.withPluginClasspath` is setting the correct classpath in  `build/pluginUnderTestMetadata/plugin-under-test-metadata.properties` and build script can access the plugin via its `id`. But Init script plugin can't use `id` and it does not have the classpath set and so fails to access the plugin via its fully qualified class name.

In real world, we have a `initscript` block in our init script which sets the classpath, but I would not expect to that when using `withPluginClasspath`.

### Expected Behavior
* Init script should respect the classpath set via `GradleRunner.withPluginClasspath`. Or
* If this is not a supported feature, it should be clearly documented and provide the workaround for the same.

### Current Behavior
* Init script is not able to find class `org.gradle.sample.HelloWorldPlugin`

### Context
* No ability to write functional test for init script plugins.

### Steps to Reproduce (for bugs)
* Build scan URL: https://scans.gradle.com/s/rdv5uwyg2iqnw
* Minimal test case to reproduce the bug:  [automaticClasspathInjectionQuickstart.tar.gz](https://github.com/gradle/gradle/files/1055054/automaticClasspathInjectionQuickstart.tar.gz). Its a modified version of *automaticClasspathInjectionQuickstart* sample project.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/rdv5uwyg2iqnw

**Comment by bmuschko** [comment]
At the moment the settings file does not support using the plugins DSL. AFAIK we want to tackle streamlining how to consume plugins in the course of this year. That would also mean being able to use the plugins DSL in the setting file.

You can still test your settings plugin. However, you will not be able to use `plugins(Action)`. You will have to [configure the classpath manually](https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-classpath-injection).
