### ISSUE TITLE
[Request] Scan dependencies on .gradle folder for vulnerabilities

### ISSUE THREAD

**Issue by Drjacky** [gradle/gradle#22504]
### Expected Behavior
It'd be cool if we could run a command to scan all dependencies located in our machine (I mean for example for macOS: `/Users/[username]/.gradle/HERE`) for vulnerabilities with the help of a third-party plugin such as
- https://github.com/sonatype-nexus-community/scan-gradle-plugin
- https://github.com/jeremylong/DependencyCheck

So if there is a version that has vulnerability(s), if we passed a `-r` argument, for example, it would remove the folder/local cache; or just list them and the developer can decide what to do next.

**Comment by jbartok** [comment]
Unfortunately, we don't have the resources at the moment to address this concern. For the moment purging the cache is the only solution available.
