### ISSUE TITLE
Regression in dependency resolution with conflict resolution and different variants between conflicted versions

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#22510]
From a quick analysis of the error and reproducer, it seems that Gradle 7.6 incorrectly resolves the variant against `kotlin-gradle-plugin-api:1.7.10` while `1.7.20` is selected. And since `1.7.10` does not have the `gradle71RuntimeElements` variant which was introduced in `1.7.20` only, we end up with a selection of incompatible variants as both `gradle70RuntimeElements` (lifted from 1.7.10) and `gradle71RuntimeElements` end up in the graph.

With Gradle 7.5.1, selection succeeds and correctly resolves `gradle71RuntimeElements`.

So it looks like something changed in the resolution system that causes unexpected node selection.

Error:
```
* What went wrong:
Execution failed for task ':plugin:generatePrecompiledScriptPluginAccessors'.
> Could not resolve all files for configuration ':plugin:runtimeClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20.
     Required by:
         project :plugin > org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle70RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-runtime}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle71RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.1, org.gradle.status=release, org.gradle.usage=java-runtime}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20.
     Required by:
         project :plugin > org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20
         project :plugin > org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20 > org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.7.20
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle70RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-runtime}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle71RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.1, org.gradle.status=release, org.gradle.usage=java-runtime}

   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.10.
     Required by:
         project :plugin > org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.4.1 > org.jetbrains.kotlin:kotlin-sam-with-receiver:1.7.10
      > Multiple incompatible variants of org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 were selected:
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle70RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.0, org.gradle.status=release, org.gradle.usage=java-runtime}
           - Variant org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20 variant gradle71RuntimeElements has attributes {org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.plugin.api-version=7.1, org.gradle.status=release, org.gradle.usage=java-runtime}

```

Reproducer: https://github.com/cesar1000/kotlin_dependency_ambiguity

**Comment by ljacomet** [comment]
Further investigations have revealed that the issue is not in dependency management, but rather in the way the metadata works for the `kotlin-gradle-plugin` and `kotlin-sam-with-receiver` libraries.

In Gradle 7.5:
* The [plugin development plugins](https://docs.gradle.org/current/userguide/java_gradle_plugin.html) do not request the `org.gradle.plugin.api-version` attribute when resolving `runtimeClasspath`.
* `org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.4.1` depends on `kotlin-sam-with-receiver:1.7.10`
* `kotlin-sam-with-receiver:1.7.10` resolves to variant `runtimeElementsWithFixedAttribute` since there is no `org.gradle.plugin.api-version` attribute requested
* Which in turns resolves the same name variant in `kotlin-gradle-plugin-api`, which was already resolved anyway.

This means that resolution succeeds with Gradle < 7.6.

In Gradle 7.6:
* The development plugins do add the attribute. This fix is needed and consistent.
* `org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.4.1` depends on `kotlin-sam-with-receiver:1.7.10`
* It ends up selecting the `gradle70RuntimeElements` in `kotlin-sam-with-receiver:1.7.10` since that is the variant matching the requested attributes, in particular with the inclusion of `org.gradle.plugin.api-version`
* That variant depends on `kotlin-gradle-plugin-api` with a specific _capability_ `org.jetbrains.kotlin:kotlin-gradle-plugin-api-gradle70`.
* This means that selection ends up picking the `gradle70RuntimeElements` for `kotlin-gradle-plugin-api:1.7.20` in addition to the `gradle71RuntimeElements`

And then resolution fails because these two variants are _incompatible_ given the difference in values for `org.gradle.plugin.api-version`.

One solution on the Gradle side is to make sure that `org.gradle.kotlin:gradle-kotlin-dsl-plugins` expresses a _strictly_ version requirement for the Kotlin dependencies. So that any deviation from the supported setup breaks early.

**Comment by ljacomet** [comment]
Note that a workaround is to add a constraint:
```
constraints {
    implementation("org.jetbrains.kotlin:kotlin-sam-with-receiver:1.7.20")
}
```

**Comment by ljacomet** [comment]
Closing as there is nothing to do in Gradle for this

**Comment by eskatos** [comment]
The issue on the Kotlin side is https://youtrack.jetbrains.com/issue/KT-54691/Kotlin-Gradle-Plugin-libraries-alignment-platform

**Comment by martinbonnin** [comment]
> That variant depends on `kotlin-gradle-plugin-api` with a specific capability org.jetbrains.kotlin:kotlin-gradle-plugin-api-gradle70.

Can you elaborate on that part? I thought `7.0` was an [attribute](https://docs.gradle.org/current/userguide/implementing_gradle_plugins.html#plugin-with-variants) named `org.gradle.plugin.api-version`. And that attribute was the minimum version of Gradle required by a given dependency. So even if `kotlin-sam-with-receiver:1.7.10` declares `org.gradle.plugin.api-version=7.0`, there should be no issue resolving  `kotlin-gradle-plugin-api` to `1.7.20` with variant `gradle71RuntimeElements`?

Or are capabilities something different there? It feels weird that a dominator dependency forces their minimum version of Gradle on all dependencies.
