### ISSUE TITLE
As for Gradle 6.7 or lower, org.gradle.api.Action conversion from Groovy may be incompatible with Kotlin DSL.

### ISSUE THREAD

**Issue by jmatsu** [gradle/gradle#22529]
`org.gradle.api.Action` calls from Kotlin DSL cause a build failure if the functions are originally written in Groovy.

### Expected Behavior

Builds succeed without any failure. Or personally, I'd be happy if this restiction is noted in the documents.

### Current Behavior

Builds fail due to missing lambda's classes.

### Context

I"m writing Gradle plugins in Groovy and wanna support both of Groovy DSL and Kotlin DSL properly. I'm following https://docs.gradle.org/current/userguide/kotlin_dsl.html to fit Kotlin DSL users' usecases but the issue happened.

### Steps to Reproduce 

- Write a plugin and create a function that takes `org.gradle.api.Action` in Groovy
- Create a project that uses Gradle 6.7 or lower
- Call the function from Kotlin DSL

A reproducable project is here. https://github.com/jmatsu/repro-kotlin-dsl-bug-gradle-plugin-written-in-groovy

This happens only when, the all following conditions are met.

- The functions are written in Groovy
- Gradle at runtime are ver. 6.7 or less

There is a workaround that is rewriting classes that have functions with `org.gradle.api.Action` from Groovy to Java.

### Your Environment

Build scan URL: N/A

**Comment by big-guy** [comment]
I'm not sure where you're getting those version numbers from. Gradle stopped at 5.6.4 and went to 6.0, so 5.7/5.8 do not exist.

If you're going to write your plugins in Groovy, I would always add `@groovy.transform.CompileStatic`. Does that avoid the issue?

**Comment by jmatsu** [comment]
So sorry, 5 is wrong but 6 is correct. Let me modify these typos. 

Okay, I′ll try CompileStatic.

**Comment by jmatsu** [comment]
`@groovy.transform.CompileStatic` solved the issue. Should we always add this annotation as much as possible?

**Comment by big-guy** [comment]
Yes, I would. That's [what we recommend](https://docs.gradle.org/current/userguide/performance.html#statically_compile_tasks_and_plugins) for other reasons.

**Comment by jmatsu** [comment]
Make sense.

After reinvestigation, I found this happened because of Kotlin's type inference algorithm. The old inference algorithm that Kotlin has used in 1.3 or lower doesn't work with Groovy's Dynamic compilation. Gradle 6.8 upgraded Kotlin to 1.4 and use 1.3 version mode for the compatibility concern. However, Kotlin's new type inference algorithm (ref: https://kotlinlang.org/docs/whatsnew14.html#new-more-powerful-type-inference-algorithm) became active regardless of the configuration. 

We should use dynamic compilation iff we need it. Thank you for your help!
