### ISSUE TITLE
Groovy and Java joint compilation failure on Java class private dependency change

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#22531]
When compiling Groovy and Java in joint compilation incrementally, Groovy compiler can fail with `NoClassDefFoundError`. 

Error from gradle/gradle: https://ge.gradle.org/s/nchdihafkxkzs.

Groovy compiler throws an error through reference:
ResolveTestFixture.configurationCacheEnabled -> GradleContextualExecuter -> AbstractDelegatingGradleExecuter -> AbstractGradleExecuter:

```
:internal-integ-testing:compileGroovy FAILED
startup failed: General error during conversion: java.lang.NoClassDefFoundError: org.gradle.integtests.fixtures.executer.AbstractGradleExecuter
```

A simple reproducer can be seen [here](https://github.com/gradle/gradle/blob/69b48824dd62c46530f1606f8901f1bc4166f4a1/subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/CrossTaskGroovyJavaJointIncrementalCompilationIntegrationTest.groovy#L29-L45).

This seems like an old issue that surfaced with latest changes to `ResolveTestFixture`. It happens because we delete `.class` files before we invoke Groovy compiler. But Groovy compiler wants to resolve some types when analyzing Groovy code. And if these types are from Java source, this can fail.

**Comment by abstratt** [comment]
A simple workaround seems to be to make a simple change to that source file for the missing class (say, subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java).
