### ISSUE TITLE
Custom bom cannot find the third bom version in 'annotationProcessor'

### ISSUE THREAD

**Issue by zxiaozhou** [gradle/gradle#22533]
### Context

1. Custom bom cannot find the third bom version in 'annotationProcessor'. What does it take to fix it.
2. It's not friendly to use the platform multiple times.For example：
```
api platform(project(':custom-bom'))
annotationProcessor platform(project(':custom-bom'))
compileOnly platform(project(':custom-bom'))
```
3. Or how to inherit the annotationProcessor version number of an external bom to avoid using platform multiple times
4. If you can only use platform multiple times, I feel the tool is poor

**Comment by eskatos** [comment]
`annotationProcessor` doesn't extend from `api` so you have to repeat the platform.
Same with `compileOnly`.
This is working as expected and there are no plans to change this.
