### ISSUE TITLE
JavaCompile cache key takes into account empty directories and directories with only file other than *.java

### ISSUE THREAD

**Issue by lrpg** [gradle/gradle#2255]
inputPropertyHash for 'source' of a JavaCompile task is different between 2 compilations when empty directories or directories with only files other than *.java are present in the sourceSet 

### Expected Behavior
I would expect the intputPropertyHash for the 'source' task to:
* Ignore directories where only files other than *.java are found
* Ignore empty directories

I was able to find that directory with only files other than *.java and  empty directories were the source of the error by:
- Adding breakpoint on line 54 of this file https://github.com/gradle/gradle/blob/REL_3.5/subprojects/core/src/main/java/org/gradle/caching/internal/tasks/TaskCacheKeyCalculator.java
- Inspecting this variable: ((DefaultFileCollectionSnapshot)((com.google.common.collect.ImmutableEntry)entry).getValue()).snapshots

I haven't dug deeper than than, but it is sufficient to get the list of files/directories .

### Current Behavior
Empty directories and directories containing only files other than *.java are taken into account when building the inputPropertyHash for 'source' for JavaCompile tasks

### Context
This is affecting the hit rate on the shared remote cache.
Each local repo might have a different set of empty directories and/or directories with only files others than java, producing a different hash.
* There are different files that can be present on disk due to multiple factors
  * Can be due to versioning system leaving .orig, .rej files, etc
  * Added *.properties files or other resources having no impact on the JavaCompile
  * Other temporary files

### Workaround
Explicitly modify the sourceset for JavaCompile tasks to restrict it to use only .java files and exclude empty directories.
        import org.codehaus.groovy.runtime.IOGroovyMethods
    
    import java.nio.file.FileSystems
    import java.nio.file.Files
    import java.nio.file.Path
    import java.nio.file.PathMatcher
    
    sourceSets.all {
        tasks.withType(JavaCompile) {
    
            //Workaround for Gradle 3.5 issue: In Gradle 3.5, the 'source' hash takes empty folders and folders with other files than java
            PathMatcher javaFilePatternMatcher = FileSystems.getDefault().getPathMatcher("glob:**.java")
    
            it.exclude(
                    new Spec<FileTreeElement>() {
                        @Override
                        boolean isSatisfiedBy(FileTreeElement element) {
                            return element.isDirectory() && !hasJavaFile(element.file)
                        }
    
                        boolean hasJavaFile(File file) {
                            Path path = file.toPath()
    
                            if (!file.isDirectory()) {
                                return javaFilePatternMatcher.matches(path)
                            }
    
                            boolean result = false
    
                            IOGroovyMethods.withCloseable(Files.newDirectoryStream(path), { directoryStream ->
                                for (Path f : directoryStream) {
                                    result |= hasJavaFile(f.toFile())
                                    if (result) {
                                        break
                                    }
                                }
                            })
    
                            return result
                        }
                    }
            )
        }
    }

### Steps to Reproduce (for bugs)
1. Create a simple java project with at least one java class including java plugin
2. Enable local cache on this project
3. Run gradlew --build-gradle clean compileJava --debug and note the inputHash of the 'source'
4. Add an empty directory and/or a directory with a file other than a *.java file
5. Run gradlew --build-gradle clean compileJava --debug and note the inputHash of the 'source'
6. Compare the 2 inputHash(es), which should be different

This should also be reproducible with any java project

Example in attached project: [gradle-cache-issue.zip](https://github.com/gradle/gradle/files/1058888/gradle-cache-issue.zip)

### Your Environment
Gradle 3.5
Windows 7
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

### Additional information
After writing this, I realize the issue might also lie in: 
* JavaCompile's sourceSet(s), which could by default exclude such directories
* JavaCompile's TasksInputs, which could by default exclude such directories

**Comment by bmuschko** [comment]
@lptr @wolfs You you mind having a look?

**Comment by lptr** [comment]
We are planning to handle the empty directory case at some point. It is probably going to be part of input normalization, similar to how we handle runtime classpaths. I'm not sure when we're going to get around to doing this yet.

About filtering non `*.java` files: you can separate actual Java sources in `src/main/java` and other resources in `src/main/resources`.

Any generated sources or resources should go under `$buildDir`. Whatever tasks generate those files can make sure to not produce any empty directories, too.

**Comment by lptr** [comment]
This is the issue to watch for empty directory filtering: https://github.com/gradle/gradle/issues/2463
