### ISSUE TITLE
OutOfMemoryError on workers used by checkstyle

### ISSUE THREAD

**Issue by apflieger** [gradle/gradle#22562]
Our project reached a limit where checkstyle is not executable anymore because we get `java.lang.OutOfMemoryError: Java heap space`

### Current Behavior
Workers are started with a default 512 MB heap space. I profiled the execution. Here's the worker that crashes :

![Capture d’écran 2022-10-31 à 11 18 19](https://user-images.githubusercontent.com/3698901/198985714-c2e66f3c-4bfa-4071-9bb0-a0048bad4346.png)

Here's a summary of the corresponding heap dump (I couldn't link the file because it's too big) :

![Capture d’écran 2022-10-31 à 11 21 04](https://user-images.githubusercontent.com/3698901/198986259-c46680e7-ba7a-419d-8384-ce682d7b5507.png)

As you can see, most of the heap is filled with org.antlr classes, which is the java parser used bu checkstyle.

### Context
The checkstyle plugin doesn't offer any way to configure the heap size of it's workers. Nor does gradle itself, in a generic way.
Because of the way checkstyle configuration is designed, we can't even exclude some files/packages to reduce memory footprint.
I don't find any solution.

I didn't find any bug report on checkstyle or antlr about memory leak or whatever. Apparently they are even aware that antlr needs a lot. I'm surprise that we discovered that because or project is not that big, we are only 2-3 developpers.
**Update:** the problem seems to come from a single java source file that is a bit big (800 lines) so it's not related to the overall project size. Note that even without this file, we are always around 400 MB + of usage. Having this fixed 512 MB for checkstyle workers is living on the edge.

### Steps to Reproduce 

If you need to reproduce it, let me know in private. I can't give a public access to our code.

### Your Environment
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9-61)
OpenJDK 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)

Build scan URL: https://gradle.com/s/lvwufspi72e6m

We use checkstyle 10.3.2

**Comment by asodja** [comment]
With Gradle 7.5.x that use workers, you can configure workers heap size with a property directly on a Checkstyle task, example:
```
tasks.withType<Checkstyle>().configureEach {
    maxHeapSize.set("2g") // you can use 'g' suffix for gigabytes or 'm' for megabytes  
}
```

**Comment by apflieger** [comment]
Oh yeah. I didn't see that! Marked as `@Incubating`, but that's fine to me.
Thanks
