### ISSUE TITLE
The erorr is very not specific

### ISSUE THREAD

**Issue by feldman10** [gradle/gradle#22563]
I am trying to run my project but I am getting an error like this "Username must not be null!" but i dun`t know where and in which library to loke where it`s missing the user name

maby it`s should give a link to where the user name is missing or it`s should give any more specific referrence

 so it`s not building and  I can`t do my work

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
