### ISSUE TITLE
When I was building the flutter environment in Android Studio, Tag mismatch appeared! I don't know how to do it. Can you help me?

### ISSUE THREAD

**Issue by pwjcw** [gradle/gradle#22571]
![image](https://user-images.githubusercontent.com/52821333/199141185-2e65f9d8-ff20-4984-a09c-e2171129a736.png)

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
