### ISSUE TITLE
Project.files enters into an infinite loop when passing a nio Path instance

### ISSUE THREAD

**Issue by kelemen** [gradle/gradle#2259]
When calling `Project.files` with a `java.nio.file.Path` instance, resolving with the returned `FileCollection` will loop forever. The cause is that `java.nio.file.Path` implements `Iterable<Path>` and Gradle will try to resolve this infinitely nested collection.

I will create pull request in a minute solving this bug (including tests).

**Comment by w25r** [comment]
This is a duplicate of https://github.com/gradle/gradle/issues/1973 which already has a PR https://github.com/gradle/gradle/issues/2144

**Comment by kelemen** [comment]
Sorry, didn't notice the other report.
