### ISSUE TITLE
Provide a hook to run code at the end of a build script, but before `afterEvaluate { }`

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#22606]
I have a custom gradle extension for my convention plugins:

```kts
plugins { id("myCompany.convention.library.android") }

myCompany {
  // configuration options
}

dependencies { .. }

// I want to evaluate the value of `myCompany` here, immediately before `afterEvaluate { }`
```

The `myCompany` extension allows devs to control how we internally configure _other_ plugins, like AGP. However, AGP throws an exception when configuring their extension in `afterEvaluate { }`. But because `myCompany { }` is an entry point into AGP configuration, we have a problem.

The workaround I came up with was:

```
config = myCompany { .. }
```

When `myCompany { }` is assigned to `config`, the `myCompany { }` extension is finalized and begins to configure AGP (and other plugins.

Ideally, I would like to avoid this workaround. Could Gradle provide an API to make this possible?

Note: we can't add a function like: `fun myCompany(block: MyCompanyGradleExtension.() -> Unit)` because different convention plugins have different values emitted into `myCompany { .. }`.

Gradle Slack [thread](https://gradle-community.slack.com/archives/CAHSN3LDN/p1667417506722479) on this.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

***

This is what the `Property`/`Provider` API is supposed to provide. We will not add another order sensitive callback.
If both your extension and AGP DSL are `Property`/`Provider` based you can chain configuration values.
If not, you need to change your extension and/or ask AGP to do the same.
