### ISSUE TITLE
Error:- Execution failed for task ':app:processDebugResources

### ISSUE THREAD

**Issue by RatikantAppstango** [gradle/gradle#22627]
Hello,

In my working project I am getting this error while running the code.
"Execution failed for task ':app:processDebugResources'"

While updating gradlew I am getting this error 
"Gradle sync failed: Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer"

Is there any solution available please provide me.

Thankyou

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.
