### ISSUE TITLE
does not work in windows 11 22h2

### ISSUE THREAD

**Issue by Danjhop4** [gradle/gradle#22628]
the script will not load in windows 11 22h2 it just blinks up a window then crashes lastest version of everything 
think its due to changes to command prompt

**Comment by Danjhop4** [comment]
needs to be redone to work

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.
