### ISSUE TITLE
java toolchain greater than `jvm-8` fails with scala 2.12.17

### ISSUE THREAD

**Issue by tnielens** [gradle/gradle#22622]
scala 2.12.x does not support `-target` > `jvm-1.8`. The option is deprecated in https://github.com/scala/scala/pull/10109 for scala 2.12.17.

### Expected Behavior
Compilation should succeed.

### Current Behavior
Compilation fails.

### Context
I can't upgrade a project to latest scala version with a jvm toolchain.

### Steps to Reproduce 
Compiling some scala code with a toolchain greater than jvm 8 fails with:
```
> Task :compileScala
'jvm-1.11' is not a valid choice for '-target'
bad option: '-target:jvm-1.11'
```
with this toolchain configuration:
```gradle
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
```

### Your Environment
gradle 7.5.1
scala 2.12.17
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

----

Related issues

* https://github.com/gradle/gradle/issues/19456
* #20180 
* #21551
