### ISSUE TITLE
Add API to configure SourceSetOutput classesDirs

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#22629]
There is no API to configure the `classesDirs` of a SourceSetOutput. In `DefaultSourceSetOutput`, `classesDirs` is a `ConfigurableFileCollection`, but in `SourceSetOutput`, it is only advertised as a `FileCollection`. Gradle internally leverages `classesDirs` configurability, but does not allow external users to do so. This leaves a hole in the API and forces any plugin author or user who wants to add additional tasks which produce classes to do custom wiring to get their classes to be included in build outputs.

**Comment by big-guy** [comment]
Let's add documentation that it's safe to cast to `ConfigurableFileCollection` in 8.x and in 9.0 we can make this the proper type.

Add documentation to user manual for adding a compile task to classesDirs.

**Comment by big-guy** [comment]
Make a new issue for 9.0 work

**Comment by jvandort** [comment]
Follow up-task here: https://github.com/gradle/gradle/issues/23932

We will resolve this issue by documenting that this property can be casted to a `ConfigurableFileCollection`. We will avoid documenting the procedure for adding to `classesDirs` for now until the linked issue is resolved -- in order to avoid directing users to a procedure which will change shortly.
