### ISSUE TITLE
Gradle prerequisites / specify min gradle version in build.gradle 

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#2263]
During the years, gradle releases have often broken forward compatibility. The `build.gradle` should definitely require some sort of prerequisites in the file, like the pom schema version of maven.

### Expected Behavior

On a a project without wrapper or with outdated wrapper, when I run `gradle build`, Gradle should report wether or not the build-script is compatible, showing the minimum versions to run the script. If the gradle version is too recent eventually suggest that there was baking changes between the actual gradle version and the minimum gradle version indicated in the build script.

### Current Behavior

Gradle fails in various unexpected ways if using a gradle version that isn't compatible with the build script / plugins.

I have my own plugin with :

```groovy
GradleVersion minGradle = GradleVersion.version('3.3')
if (GradleVersion.current() < minGradle) {
    throw new GradleException("${minGradle} or above is required to build this project")
}
```

However this error is not raised if I use other incompatible plugin, instead the build will then fail with an exotic error.

Some say that one should use wrapper with gradle, **but** projects don't always have a wrapper, jars in the source control is not always accepted as a good practice and the wrapper can be outdated as well.

Also _a priori_ small changes can break the build, and make it difficult for the beginner to identify that he is using a wrong gradle version, e.g. checking out a branch with a plugin imported directly or not that is incompatible with can backfire in various (and sometime mysterious) ways.

Having this requirement explicit at the very beginning of his own `build.gradle` could help a lot.

### Your Environment
I have seen gradle 0.x to gradle 4.x.

**Comment by bmuschko** [comment]
> On a a project without wrapper or with outdated wrapper...

IMHO using the Wrapper _is_ best practice. It establishes the notion of compatibility of your build script with a specific version of Gradle. If the Wrapper gets outdated then you are not running your build on CI which is definitely a best practice as well.

> However this error is not raised if I use other incompatible plugin, instead the build will then fail with an exotic error.

I'd definitely like to see some meta-data that can be provide with a plugin to indicate its compatibility with specific Gradle versions. However, keep in mind you can only really verify that by running cross-version compatibility tests. In a perfect world the Gradle plugin portal would do that automatically whenever you publish a new version.

**Comment by oehme** [comment]
Plugins and build scripts can already check the current Gradle version (`project.gradle.gradleVersion`) and fail the build if they know that that version won't work.

All projects should be using the wrapper. If this is a problem for some, we should make it easier, e.g. by making the wrapper itself an installable program, so that only the `gradle-wrapper.properties` file needs to be checked in.
