### ISSUE TITLE
JUnit 5 build worked with 4.0 RC1, fails with RC2

### ISSUE THREAD

**Issue by sormuras** [gradle/gradle#2264]
See PR: https://github.com/junit-team/junit5/pull/873
Failing under [Windows](https://ci.appveyor.com/project/marcphilipp/junit5/build/1123) and [Linux](https://travis-ci.org/junit-team/junit5/jobs/240861273) with same error:

```
gradlew --refresh-dependencies clean assemble
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```
and
```
gradlew -version
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

Wrapper command used to upgrade to 4.0-rc-2:
```
18:42:24: Executing external tasks 'wrapper --gradle-version=4.0-rc-2'...
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
:wrapper UP-TO-DATE

BUILD SUCCESSFUL in 5s
1 actionable task: 1 up-to-date
18:42:31: External tasks execution finished 'wrapper --gradle-version=4.0-rc-2'.
```

`gradle/wrapper/gradle-wrapper.jar` is `54.711` bytes large and contains the `org.gradle.wrapper.GradleWrapperMain` class.

**Comment by sormuras** [comment]
Locally it works:
```
gradlew --version

------------------------------------------------------------
Gradle 4.0-rc-2
------------------------------------------------------------

Build time:   2017-06-07 15:22:36 UTC
Revision:     14679a04a9d5afc2038c57d9392a36d8cc2e850e

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64
```

**Comment by bmuschko** [comment]
Could you please be more specific about what is working and what isn't? In your initial report you show the error message `Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain` and then later you say it works _locally_. What do you mean by _locally_? Does it refer to your development machine vs. on CI?

**Comment by bmuschko** [comment]
Generally speaking 4.0-rc2 should not have an issue on Travis CI. I just tested another project.

- [Commit](https://github.com/gradle-guides/gradle-site-plugin/commit/3f6a92b8b453062fc1e393bfc69196a1c3457ee9)
- [CI build](https://travis-ci.org/gradle-guides/gradle-site-plugin)

**Comment by sormuras** [comment]
I'm trying to upgrade to 4.0-rc-2 on a fresh branch (master is on Gradle 3.5) and will report back.

The error only happens on AppVeyor (Windows link in initial issue description) and Travis CI (Linux link in initial description).

Locally, on my dev machine, the build using Gradle 4.0-rc-2 works.

**Comment by sormuras** [comment]
Create the new branch at https://github.com/junit-team/junit5/compare/gradle_4.0

The `gradle-wrapper.jar` is corrupted, when it comes from Github.

On my dev machine, everything's fine. The JAR contains 50 "objects", including various `.properties` file and a `cli` package. Size of the JAR: `54.953 Bytes`

The JAR loaded from the branch only contains 16 "objects", no `.properties` file and no `cli` package. Size of JAR: `54.710 Bytes`

I guess, it's a line feed mangling issue...

**Comment by sormuras** [comment]
...for some reason, git treated the jar file as text.

Build is running now as expected: https://travis-ci.org/junit-team/junit5/builds/240915063

Closing this non-issue.
