### ISSUE TITLE
Kotlin and JPMS: Error occurred during initialization of boot layer: Module not found

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#22658]
### Expected Behavior
Java Platform Module System modules implemented in Kotlin should run when the module-info.java file is located under 'src/main/kotlin'.

### Current Behavior
Per #17271, the Application plugin's `run` task only succeeds if the module-info.java file is located under 'src/main/java':

```
> Task :run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.ianbrandt.jpms not found
```

### Context
Generally, both [Kotlin and Java sources can be placed in either 'src/main/kotlin' or 'src/main/java'](https://kotlinlang.org/docs/gradle.html#kotlin-and-java-sources). For a Kotlin-only project that should be built as a JPMS named module, it's not obvious that the module-info.java file can't be located under 'src/main/kotlin'.

### Steps to Reproduce 
Reproducer here: https://github.com/ianbrandt/gradle-kotlin-jpms/tree/module-info-in-kotlin-src.

As is, `gradlew run` fails. If the module-info.java file is moved from 'src/main/kotlin' to 'src/main/java', it succeeds.

### Your Environment
Gradle 7.5.1
Kotlin 1.7.21

**Comment by eskatos** [comment]
We are not sure if this is a Gradle or Kotlin Gradle Plugin issue yet. We are still investigating.

**Comment by eskatos** [comment]
Related
* https://github.com/gradle/gradle/issues/22657

**Comment by Tapchicoma** [comment]
It is intentional that Java compilation does not anything about `.java` files under `src/main/kotlin`. To fix your issue you need to move `module-info.java` into `src/main/java`.

**Comment by gotohigher** [comment]
C:\Program Files\gradle-8.7\bin>gradle

Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found


How to fix it?
