### ISSUE TITLE
Allow directory listing to be an input to config cache.

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#22656]
Use directory listing (the list of files and subdirectories in a given directory) as an input to config cache. 

### Expected Behavior
If I do `settingsDir.list()` and use the result to dynamically include projects, then config cache should be invalidated when the results of `settingsDir.list()` (or any directory listing I read) is changed. 

### Current Behavior
I can read from `settingsDir.list()` during config, but if a new file or directory show up later, the config cache will not be invalidated. Instead config cache is reused when it should not be reused, and the new value of `settingsDir.list()` is not used to recalculate config.

### Context

Do something with a similar effect as this 👇 , but it should work well with config cache (and build cache)
https://proandroiddev.com/gradle-kotlin-dsl-dynamically-discover-project-modules-25204096c3b

**Comment by yogurtearl** [comment]
Haven't tried it, but I might be able to use `ProviderFactory.of` and `ValueSource` to make config cache aware of the directory listing.

**Comment by h0tk3y** [comment]
Closing this as fixed. Gradle should be able to track calls to `File.listFiles` and report them as configuration inputs. More APIs serving the same purpose will be added to tracking later.

**Comment by yogurtearl** [comment]
Note to my future self: looks like this fix is targeted at gradle 8.1 ( #23636 , #23266 )
