### ISSUE TITLE
Images in docs need recolored

### ISSUE THREAD

**Issue by hythloda** [gradle/gradle#22655]
### Expected Behavior
The images at [https://docs.gradle.org/7.6-rc-1/userguide/userguide.html](https://docs.gradle.org/7.6-rc-1/userguide/userguide.html) should not be color scaled to meet their brand guidelines. 

### Current Behavior
They are in our colors.

**Comment by lkasso** [comment]
This has been fixed and will be public in 8.3: https://docs.gradle.org/nightly/userguide/userguide.html
