### ISSUE TITLE
buildscript issue loading new classes during garbage collection

### ISSUE THREAD

**Issue by SteveHigham** [gradle/gradle#2265]
There seems to be a problem with buildscript dependencies during garbage collection at the end of a gradle run. I have seen this in gradle 3.3 installed natively and 3.5 using the wrapper.

I'm creating a dedicated build logger using log4j2 as follows:
@log4j2
class BuildLogger {}
def buildLogger = new BuildLogger ()
buildLogger.log.warn 'Test'

The dependencies are set up in the buildscript closure. However after the script completes I get a NoClassDefFoundError caused by a ClassNotFoundExcpetion for class org.apache.logging.log4j.core.util.NameUtil

There is a simple workaround by preloading this class in the main script as follows:
NameUtil.getSubName ''

However this is not elegant and I suspect other use cases causing this problem may not be so easy to fix.

**Comment by bmuschko** [comment]
Can you clarify where the annotation `log4j2` is coming from? A reproducible example would be helpful.

**Comment by SteveHigham** [comment]
Hi bmuschko

The log4j2 config file is as follows:

<?xml version="1.0" encoding="UTF-8"?>
<Configuration> 
  <Appenders>
    <Console name="console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm} [%t] %-5level %logger{0} - %msg%n" />
    </Console>
  </Appenders>
  <Loggers>
    <Root level="trace">
      <AppenderRef ref="console" />
    </Root>
    <logger name="BuildLogger" level="trace" additivity="false">
      <AppenderRef ref="console" />
    </logger>
  </Loggers>
</Configuration>

My build.gradle is as follows:

/**
 * Gradle build script to test gradle defect
 */

import groovy.util.logging.Log4j2

import org.apache.logging.log4j.core.util.NameUtil

//import org.apache.logging.log4j.Logger
//import org.apache.logging.log4j.LogManager

buildscript {
  repositories {
    mavenCentral ()
  }
  
  dependencies {
    classpath 'org.apache.logging.log4j:log4j-api:2.8.2'
    classpath 'org.apache.logging.log4j:log4j-core:2.8.2'
  }
}

// We get a clean up exception if the NameUtil class has not been preloaded!
//NameUtil.getSubName ''

@Log4j2
class BuildLogger {}

def buildLogger = new BuildLogger () // LogManager.getLogger 'buildlogger'
buildLogger.log.warn 'Test'

// End of file.

This is reproducing the defect I originally saw on my Linux laptop on my iMac.
An alternative version of the build.gradle file not using @Log4j2 is below. I have seen this produce the same defect but this version seems to be very intermittant on my iMac.

/**
 * Gradle build script to test gradle defect
 */

// import groovy.util.logging.Log4j2

import org.apache.logging.log4j.core.util.NameUtil

import org.apache.logging.log4j.Logger
import org.apache.logging.log4j.LogManager

buildscript {
  repositories {
    mavenCentral ()
  }
  
  dependencies {
    classpath 'org.apache.logging.log4j:log4j-api:2.8.2'
    classpath 'org.apache.logging.log4j:log4j-core:2.8.2'
  }
}

// We get a clean up exception if the NameUtil class has not been preloaded!
//NameUtil.getSubName ''

//@Log4j2
//class BuildLogger {}

def buildLogger = LogManager.getLogger 'buildlogger' // new BuildLogger () 
buildLogger.warn 'Test'


// End of file.

I'm testing this by executing './gradlew tasks' with a gradle version of 3.5. I am not running the gradle daemon.

Cheers,  Steve

**Comment by SteveHigham** [comment]
[log4j2-test.xml.txt](https://github.com/gradle/gradle/files/1069718/log4j2-test.xml.txt)
Included my log4j2 config file as this doesn't seem to have been captured in my previous post.

**Comment by bmuschko** [comment]
Can you describe why you need to add your own logging libraries? Gradle has its own logging system based on Slf4J. In a build script you can just use the implicit variable `logger` to write out log messages.

**Comment by SteveHigham** [comment]
Hi Benjamin,

Great to chat. Your book is my bible to Gradle and really appreciated.

I like to have independent control of my logger output against the Gradle system. Frequently I want the Gradle logger on the default "warn" level whereas my "buildlogger" will be on "trace". Once my build script is working as intended the buildlogger goes back to "warn" again. 

I think this is how loggers should be used. Frequently I have a logger per class. Furthermore what I really like about Groovy is the ease of getting the various technologies to work together.

Cheers,  Steve

**Comment by bmuschko** [comment]
> Great to chat. Your book is my bible to Gradle and really appreciated.

Glad you like it!

I think what we want to introduce in the long run is a way to configure logging for specific subsystems, plugins or components in Gradle. Often times users only want to see logging output for specific portions e.g. tasks defined by a plugin.

**Comment by oehme** [comment]
This works fine for me on 4.10, please reopen with a reproducible example project if this is still a problem.
