### ISSUE TITLE
IllegalArgumentException: Received a failure event for test with unknown id

### ISSUE THREAD

**Issue by payneChen** [gradle/gradle#22675]
We migrated from Gradle + TestNG to Gradle 7.4.2 + JUnitPlatform + TestNG Engine 1.0.4 + TestNG 6.14.3, when `org.jmockit:jmockit` used and any error/exception happened in BeforeClass/BeforeMethod
"IllegalArgumentException: Received a failure event for test with unknown id" happened and finally no TestNG html report generation

### Expected Behavior
IllegalArgumentException shall not happen and TestNG html report link would be shown in the log. like:

> * What went wrong:
> Execution failed for task ':test'.
> > There were failing tests. See the report at: file:///.../gradle-sandbox/testng-class-level-failure/build/reports/tests/test/index.html

### Current Behavior

> ~/S/gradle-sandbox/testng-class-level-failure defect/test-with-unknown-id !1 ❯ gw test --console=rich
> Using gradle at '/.../gradle-sandbox/testng-class-level-failure/gradlew' to run buildfile '/.../gradle-sandbox/testng-class-level-failure/build.gradle':
> 
> 
> > Task :test FAILED
> 
> SomeTest > executionError FAILED
>     java.lang.ClassCastException at SomeTest.java:18
> 
> 2 tests completed, 1 failed, 1 skipped
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':test'.
> > Received a failure event for test with unknown id '28.3'. Registered test ids: '[:test, 28.1, 28.2]'
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 2 actionable tasks: 2 executed

### Context
This error breaks the html report generation and hard to check the test failures.

### Steps to Reproduce 
Here is the project to reproduce: https://github.com/marcphilipp/gradle-sandbox/pull/31

### Your Environment
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.16.1 (SAP SE 11.0.16.1+1-LTS-sapmachine)
OS:           Mac OS X 13.0 x86_64

**Comment by marcphilipp** [comment]
Root cause of the issue is that JMockIt throws a `NullPointerException` from here (which happens when an exception is thrown from a `@BeforeClass` method):
https://github.com/jmockit/jmockit1/blob/1c6bd62f200e8da2d0beaa2d8752b7418540788c/main/src/mockit/integration/testng/TestNGRunnerDecorator.java#L96

This `NullPointerException` then causes TestNG to report the `test()` method first as skipped and then as failed. The TestNG engine and Gradle only expect it to be skipped or failed.

Updating to TestNG 7.0 or later resolves the issue.
