### ISSUE TITLE
forkOptions.jvmArgs.addAll() silently ignored

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#22671]
### Expected Behavior
It would be nice if forkOptions.jvmArgs could be made immutable (so that attempting to modify it fails, prompting us to call `jvmArgs()`) or if modifications to this list could be incorporated into the original list.

### Current Behavior
Currently, modifications to this list appear to do nothing

### Context
In https://issuetracker.google.com/issues/258704137 we discovered some code that was doing this:

```
forkOptions.jvmArgs?.addAll(executionOptions.get().jvmArgs)
```

and discovered that this had no effect.

This appears to be because [DefaultJavaforkOptions.getJvmArgs](https://github.com/gradle/gradle/blob/7df281862d35b7370845ad484ee26b77713255e2/subprojects/core/src/main/java/org/gradle/process/internal/DefaultJavaForkOptions.java#L77) calls [JvmOptions.getJvmArgs](https://github.com/gradle/gradle/blob/7df281862d35b7370845ad484ee26b77713255e2/subprojects/core/src/main/java/org/gradle/process/internal/JvmOptions.java#L175) which copies the list of arguments before returning them.

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.
