### ISSUE TITLE
NPE when signing.* properties are present but null

### ISSUE THREAD

**Issue by colindean** [gradle/gradle#2267]
### Expected Behavior

I expect one of two outcomes when I run `./gradlew assemble` and I'm using the `signing` plugin but have not configured the environment variables supplying the keyId or password.

1. No signing action occurs because the requirement is not met (in my configuration below, `bintrayUpload` is not in the task graph).
2. A helpful error shows when the `GPG_KEY_ID` or `GPG_PASSPHRASE` environment variables are unset, thus returning `null` from the `System.getenv` call.

### Current Behavior

I see a NPE [here](https://github.com/gradle/gradle/blob/master/subprojects/signing/src/main/java/org/gradle/plugins/signing/signatory/pgp/PgpSignatoryFactory.java#L95) when the `signing.keyId` property is null and [here](https://github.com/gradle/gradle/blob/master/subprojects/signing/src/main/java/org/gradle/plugins/signing/signatory/pgp/PgpSignatoryFactory.java#L97) when the `signing.password` property is null.

When at least _set_ these environment variables, the error is more helpful:

    GPG_KEY_ID='' GPG_PASSPHRASE='' gw assemble --stacktrace

    java.lang.IllegalStateException: The key ID must be in a valid form (eg 00B5050F or 0x00B5050F), given value:

Although it's a separate problem that the signing system initializes at all when the `required` property has not been met. I'm still looking into how to manage that so that I don't have to do locally signed builds all the time.

### Context

I want to only sign artifacts in my build system, not on local builds.

### Steps to Reproduce (for bugs)

I have in my `build.gradle`:

```groovy
ext.'signing.keyId' = System.getenv('GPG_KEY_ID')
ext.'signing.secretKeyRingFile' = "${System.getenv('HOME')}/.gnupg/secring.gpg"
ext.'signing.password' = System.getenv('GPG_PASSPHRASE')
…
apply plugin: 'signing'
…
signing {
  sign configurations.archives
  required { gradle.taskGraph.hasTask('bintrayUpload') }
}
```

In my local environment, I don't want to have the `GPG_KEY_ID` or `GPG_PASSPHRASE` environment variables set. I don't want to have to use a `gradle.properties` with them set, either.

### Your Environment

 * Build scan URL: 

I cannot supply a scan because the failure happens during the configuration step.

```
 ./gradlew -version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.11.6 x86_64
```

**Comment by bmuschko** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6558

**Comment by eriwen** [comment]
Closing as delivered!
