### ISSUE TITLE
DependencyHandler create methods do not support version catalogs

### ISSUE THREAD

**Issue by oesolutions** [gradle/gradle#22672]
Adding a dependency to a configuration via the `DependencyHandler#add` methods allows libraries from a version catalog to be specified for the dependency notation. However, the `DependencyHandler#create` methods do not.

### Expected Behavior
Version catalogs should be usable with both `add` and `create` methods since they both accept dependency notations.

### Current Behavior
Version catalogs entries are not accepted as valid dependency notations when using the `create` methods.

### Context
This issue arose when trying to replace other dependency notations with version catalogs when using one of our plugins. Internally the plugin uses `DependencyHandler#create` to delegate dependency creation to Gradle.

### Steps to Reproduce
Create a project that uses a version catalog. Then use that version catalog to create a dependency.
```
// fails with; Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert the provided notation to an object of type Dependency: provider(?).
dependencies.create( libs.mylib )
```

https://github.com/oesolutions/gradle-issue-dephandler-create-catalog

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

----

What you get out of a version catalog is already a `Dependency`, there's no need to `create`. You should directly use `add` instead.

**Comment by oesolutions** [comment]
@eskatos Any proposed course of action to move forward with something else in our plugins? Gradle has effectively added a new dependency notation with version catalogs, yet you're saying that only part of the API supports it. Is create unofficially deprecated then?
