### ISSUE TITLE
Race condition in org.gradle.api.internal.file.archive.ZipFileTree.DetailsImpl#getFile

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#22685]
The [`org.gradle.api.internal.file.archive.ZipFileTree.DetailsImpl#getFile`](https://github.com/gradle/gradle/blob/3a78b35de8a1aa2f169dae38006986d89385976f/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipFileTree.java#L161) method contains a race condition problem when it's accessed from two or more concurrent tasks accessing the same archive

```mermaid
stateDiagram-v2
  [*] --> Task1
  Task1 --> !fileExists
  !fileExists --> expandFile
  expandFile --> useFile

  [*] --> Task2
  Task2 --> fileExists
  fileExists --> useFile
```

### Expected Behavior
All the accessing tasks should get properly expanded to a temporary directory file from an archive

### Current Behavior
While the `Task1` doesn't finished to expand the file, `Task2` may decide that the file already exists and read it incorrectly

### Context
The issue causes problems with configuration cache in the [Kotlin project](https://github.com/JetBrains/kotlin/) due to ability to execute tasks from the same project in parallel.
https://ge.jetbrains.com/s/g2cmfvr55ckpg/failure#1

### Steps to Reproduce 

1. Checkout the [Kotlin project](https://github.com/JetBrains/kotlin/) at the b6eb2b362014446b68def84037a1e186f3e81b14 revision
2. Invoke `./gradlew install --configuration-cache`
3. Make changes to any `.kt` files under the `libraries/tools/kotlin-gradle-statistics/src/common` and `libraries/tools/kotlin-gradle-plugin/src/common` directories
4. Invoke `./gradlew install --configuration-cache`
5. Repeat steps 3 and 4 until you get a build failure caused by `ArrayIndexOutOfBoundsException`

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

---
A workaround would be to create explicit dependencies between task 1 and task 2 so they cannot run in parallel.
