### ISSUE TITLE
Error: Unknown Tag @NonNullApi in package-info.java

### ISSUE THREAD

**Issue by szsoftware** [gradle/gradle#22681]
Expected behavior:
Gradle is building an customized distribution, passing all tests under the following circumstances

Build-System: Ubuntu 22.04
Gradle Version checkout: 7.5.1 (sources to build)
Gradle Version BuildTool: 7.5.1
JavaVersion: OpenJdk 16 (11 tried too)

Current behavior:
Build failed with: Error: Unknown Tag @NonNullApi in package-info.java

**Comment by xaviarias** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

**Comment by xaviarias** [comment]
Closing as not reproducible. Please feel free to reopen when providing the required information.

**Comment by Yeregorix** [comment]
I'm experiencing the same error on a fresh clone (commit d94e21e0a8d3e2d24a0bbade29109ad9115fe1d8) imported into Intellij IDEA when running task `gradle build` using the IDE. I have tried both Oracle JDK 11.0.12 and Temurin 11.0.17.

Logs: https://pastebin.com/ZyZX8vk0
