### ISSUE TITLE
DependencySet#isEmpty can return false for sets of size 0

### ISSUE THREAD

**Issue by fawind** [gradle/gradle#22707]
In some circumstances it can happen that `DependencySet.size()` returns `0` but `DependencySet.isEmpty()` returns `false`.

This can happen when the backing [`AbstractIterationOrderRetainingElementSource`](https://github.com/gradle/gradle/blob/aad6435fa98afe2873fd1e07c4f2e700e8be1145/subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java) contains an [`Element`](https://github.com/gradle/gradle/blob/aad6435fa98afe2873fd1e07c4f2e700e8be1145/subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java#L290) in its [`inserted`](https://github.com/fawind/gradle/blob/78493cbbafca85ae284251d1b97d72f9f5322adf/subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java#L48-L50) list where `Element#size` evaluates to `0` (i.e. an element backed by an empty collection provider).

In this case, calling `.size()` evaluates to `0`, because the method sums up the size of all inserted elements:

https://github.com/gradle/gradle/blob/aad6435fa98afe2873fd1e07c4f2e700e8be1145/subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java#L73-L79

However, calling `.isEmpty()` evaluates to `false`, because the `inserted` list contains an element:

https://github.com/gradle/gradle/blob/aad6435fa98afe2873fd1e07c4f2e700e8be1145/subprojects/core/src/main/java/org/gradle/api/internal/collections/AbstractIterationOrderRetainingElementSource.java#L63-L65

### Expected Behavior

If `DependencySet#size == 0` then it should hold that `DependencySet#isEmpty == true` (given `DependencySet` extends `java.util.Set` for which this is an invariant).

### Current Behavior

It is possible to have an instance of `DependencySet` where `DependencySet#size == 0` but `DependencySet#isEmpty == false`.

#### Minimal reproducer:

[Failing test](https://github.com/gradle/gradle/compare/master...fawind:gradle:fw/is-empty-repro)

```groovy
def "when size == 0 then isEmpty == true"() {
    Collector<CharSequence> collector =
            new Collectors.ElementsFromCollectionProvider<>(new DefaultListProperty<>(null, CharSequence.class))

    when:
    source.inserted.add(new Element<>(CharSequence.class, collector, {}))

    then:
    source.size() == 0
    // With the current implementation, this assertion fails
    source.isEmpty() == true
}
```

#### Real world example:

https://github.com/fawind/gradle-is-empty-repro

This example simulates a minimal real-world Java project. The broken invariant can be observed by calling `configuration.getDependencies()` on the `apiElements` and `runtimeElements` configurations. To reproduce, run `./gradlew`.

### Your Environment
Reproduced on latest commit on master (aad6435fa98) and 7.5.1.

**Comment by fawind** [comment]
Thinking about a fix, I don't see a way around `AbstractIterationOrderRetainingElementSource#isEmpty` having to evaluate its inserted elements for emptiness. Unfortunately, this breaks constant time access which is among others needed for `ElementSource#constantTimeIsEmpty`.

Given this interface states ["Returns false if this source is not empty or it is not fast to determine this"](https://github.com/gradle/gradle/blob/a138710ab109e271b17ee48dc49b359284cd3f66/subprojects/core/src/main/java/org/gradle/api/internal/collections/ElementSource.java#L37-L39), maybe it's okay if `isEmpty` deviates from `constantTimeIsEmpty`? Are there precedents for this in the Gradle codebase? Do you think this is an acceptable trade-off or would this cause even more confusion?

If you think this is acceptable, I'm happy to contribute a fix!

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before a fix is made.

**Comment by eskatos** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

----

@fawind, thanks for your offer to contribute. I think it is okay that `constantTimeIsEmpty` deviates, it's separate for a reason. Please go ahead and open a PR, we'll see what the test suite says.

**Comment by ljacomet** [comment]
Removing the help wanted label as the attempt uncovered that fixing this is more complicated than expected.
