### ISSUE TITLE
Allow to exclude only some artifacts of a transitive dependency

### ISSUE THREAD

**Issue by mahozad** [gradle/gradle#22704]
I am using the [org.bytedeco:ffmpeg-platform](https://mvnrepository.com/artifact/org.bytedeco/ffmpeg-platform/5.1.2-1.5.8) library which is, I think, an aggregator dependency like [junit-jupiter](https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter) except that *junit-jupiter* aggregates some separate dependencies but *ffmpeg-platform* aggregates some artifacts of [a single dependency (org.bytedeco:ffmpeg)](https://repo1.maven.org/maven2/org/bytedeco/ffmpeg/5.1.2-1.5.8/).

The problem is, it brings many JARs that in total are about 250 MB and I don't need them all for my GUI application for one OS/architecture. How can I use the *org.bytedeco:ffmpeg-platform* library and exclude some of the transitive **artifacts** it brings?

For example, I tried to use classifiers like the following to exclude `linux-x86` JAR artifact but it doesn't work:

```kotlin
implementation("org.bytedeco:ffmpeg-platform:5.1.2-1.5.8") {
    exclude(group = "org.bytedeco", module = "ffmpeg:linux-x86")
}
```

### Expected Behavior
To be able to exclude some **artifacts** of transitive dependencies.

### Current Behavior
Gradle brings all artifacts of transitive dependencies.

### Context
My current solution is to not use the *org.bytedeco:ffmpeg-platform* aggregator dependency and use the *org.bytedeco:ffmpeg* directly and include my desired artifacts one by one with classifiers:

```kotlin
implementation("org.bytedeco:ffmpeg:5.1.2-1.5.8") // The main artifact
implementation("org.bytedeco:ffmpeg:5.1.2-1.5.8:windows-x86")     // My first desired artifact
implementation("org.bytedeco:ffmpeg:5.1.2-1.5.8:windows-x86_64") // My second desired artifact
```

#### Another example library
For another similar aggregator dependency which brings artifacts of another dependency see  [jna-platform](https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform/5.12.1) which brings [jna artifacts](https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.12.1/).

**Comment by eskatos** [comment]
Thank you for your interest in Gradle.

We have no plans to provide that feature in Gradle.
If you don't need all of architectures, specifying exactly the dependencies you need is the way to go.
