### ISSUE TITLE
Custom HTTP build cache timeout

### ISSUE THREAD

**Issue by TysonMN** [gradle/gradle#22708]
I work from home, and although my internet connection has 80 Mb/s down, I often have trouble obtaining entries from my company's remote build cache.  A workaround that I was hoping existed was using a larger timeout when accessing the cache, but [`HttpBuildCache`](https://docs.gradle.org/current/dsl/org.gradle.caching.http.HttpBuildCache.html) doesn't have a setting for that.

A similar request was made in issue #5520.

### Expected Behavior
I would like it if a setting could be added to `HttpBuildCache` to allow for a custom timeout.

### Current Behavior
Sometimes large remote build cache entires take a long time to download.  After downloading for what appears to be 20 seconds, I get an error message that looks something like this.

> Could not load entry a18255ad572ca471eb46c2400afd914c from remote build cache: Truncated chunk (expected size: 907,126; actual size: 668,502)

or

> Could not load entry f0bb04e3a6ae15e5437000d53cba8db9 from remote build cache: Premature end of chunk coded message body: closing chunk expected

When this happens, I usually cancel the command and try again.  I have four gradle workers, so usually there are four remote build cache entries being downloaded at the same time.  If it keeps happening, then eventually three gradle workers sit idle while one downloads the large cache entry.  This is usually successful, but it wasn't today, possibly because my kids were streaming a movie at the same time.

### Context

```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.3 (Azul Systems, Inc. 17.0.3+7-LTS)
OS:           Mac OS X 12.6 x86_64
```

**Comment by eskatos** [comment]
Thank you for submitting this issue.

This issue needs a decision for the team responsible for that area. They have been informed, response time may vary.

**Comment by lptr** [comment]
As you found, we have two settings for HTTP timeouts. We should document those, so we'll follow up on https://github.com/gradle/gradle/issues/5520 as you suggested. We don't plan to support an individual timeout setting for just the HTTP build cache.
