### ISSUE TITLE
Gradle wrapper task blocked by plugins requiring higher Gradle version

### ISSUE THREAD

**Issue by Mauin** [gradle/gradle#2271]
The lastest Android Gradle Plugin previews require at least Gradle 4.0-milestone-1. When using a lower gradle wrapper version (v3.5 in my case) executing the Gradle wrapper task is blocked.

To update Gradle I'm running: `./gradlew wrapper --gradle-version=gradle-4.0-milestone-1`

### Expected Behavior
The gradle wrapper task should be able to update the wrapper to use a newer version, regardless of what the applied gradle plugins require of the current Gradle version.

### Current Behavior
The Gradle task fails with:

```
>>> ./gradlew wrapper --gradle-version=gradle-4.0-milestone-1                                                            
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/.../build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 4.0-milestone-1. Current version is 3.5. If using the gradle wrapper, try editing the distributionUrl in /.../gradle/wrapper/gradle-wrapper.properties to gradle-4.0-milestone-1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.865 secs

0 tasks in build, out of which 0 (0%) were executed
```

### Context
Manually updating the `gradle-wrapper.properties` file works to update the Gradle version to a supported version. But running the `./gradlew wrapper` task can be more convenient at times and should only update the affected files and the Wrapper without checking the current gradle version against applied plugins. 
It might make sense to check the version to be applied against plugins and print a warning if it is incompatible with the plugins.

### Steps to Reproduce (for bugs)
Running `./gradlew wrapper` on a gradle version that is lower than the minimum required version of the plugins applied in the project.

**Comment by bmuschko** [comment]
This check is implemented in the Android plugin. Would you mind [opening an issue with Google on the respective forum](https://code.google.com/p/android/issues)? They are creating the plugin as well as Android Studio and are far more likely you help you with this.

BTW: Instead of using 4.0 M1 I'd go to 4.0 RC-2 right away. The release candidate contains far more improvements than the milestone release.

**Comment by Mauin** [comment]
@bmuschko I had already opened an issue on the Android Issue Tracker. The response is that Gradle "should not configure plugins when running infrastructure commands like gradlew wrapper. Pleas file a bug in their bug tracking system."

See: https://issuetracker.google.com/issues/37555718

The versions I used in the issue were just for the example. 👍 Thanks for the note on RC-2!

**Comment by bmuschko** [comment]
At least at the moment Gradle will always configure the whole build script when running a task. That also means executing applied plugins. I could imagine only configuring what is really needed for a specific but a very long shot as it's currently unplanned.

**Comment by oehme** [comment]
The wrapper task is not some special "infrastructure command". It's a task like any other . I don't see this changing for a long time. The best thing you can do when a plugin update fails is to revert the plugin update, then update the wrapper, then update the plugin again.
