### ISSUE TITLE
Artifacts and their tasks are configured eagerly when any configuration is resolved

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#22719]
### Expected Behavior
Resolving an arbitrary configuration should not incur artifact and task configuration of the default artifacts.

### Current Behavior
Tasks are eagerly configured when any configuration is.

### Context
The eager configuration of tasks is extra processing that does not necessarily need to be performed. For example, the `jar`, `compileJava`, `processResources`, and more tasks may be configured because of this, even if you were just running `gradle tasks`.

### Steps to Reproduce 
https://github.com/octylFractal/gradle-reproducer-configurations-eagerly-resolve-artifacts -- simply run `./gradlew verifyNotRealized`.

### Your Environment
Build scan URL: https://scans.gradle.com/s/p3vu5i4xai33e

**Comment by big-guy** [comment]
We fixed this
