### ISSUE TITLE
7.6 RC3: DependencyAdder.invoke cannot be called with the arguments supplied

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#22720]
### Expected Behavior
Precompiled script plugins [configuring a project dependency for an additional test suite](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#declare_an_additional_test_suite) via the JVM Test Site Plugin continue to compile after upgrading to Gradle 7.6 RC3.

### Current Behavior
The script fails to compile:

```stacktrace
e: C:\Dev\Repos\SDKotlin\sd-kotlin-talks\build-logic\src\main\kotlin\org.sdkotlin.build.test.integration-test-suite.gradle.kts: (20, 5): None of the following functions can be called with the arguments supplied: 
public operator fun DependencyAdder.invoke(dependencyNotation: CharSequence): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(dependency: Dependency): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(files: FileCollection): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(dependency: Provider<out Dependency>): Unit defined in org.gradle.kotlin.dsl
public operator fun DependencyAdder.invoke(externalModule: ProviderConvertible<out MinimalExternalModuleDependency>): Unit defined in org.gradle.kotlin.dsl

FAILURE: Build failed with an exception.
```

### Context
I'm unable to upgrade to Gradle 7.6.

### Steps to Reproduce 
Reproducer: https://github.com/sdkotlin/sd-kotlin-talks/tree/a54afe81013c1806550ff23478efe48973033deb

Line in error: https://github.com/sdkotlin/sd-kotlin-talks/blob/a54afe81013c1806550ff23478efe48973033deb/build-logic/src/main/kotlin/org.sdkotlin.build.test.integration-test-suite.gradle.kts#L20

### Your Environment
Gradle 7.6-rc3
Kotlin 1.7.21
Java 11.0.17

**Comment by tresat** [comment]
Hi Ian, this is an expected change to the `@Incubating` Test Suites API we're making with Gradle 7.6.  This is part of an effort to make the API used to add dependencies more discoverable and strongly typed.  It should have the benefit of making it easier the `testing` DSL easier to work with in your IDE.

Take a look at the [Introduced strongly-typed dependencies block for JVM test suites](https://docs.gradle.org/7.6-rc-3/release-notes.html) section in the release notes and the [updated example in the JVM Test Suite Plugin page](https://docs.gradle.org/7.6-rc-3/userguide/jvm_test_suite_plugin.html#declare_an_additional_test_suite) of the user guide.  In short, you need to switch from referencing the current project via `project` to calling the `project()` method.

The methods used to add dependencies to Test Suites differ from those used in the top-level block.  In Gradle 7.6, Test Suites make use of a new type [DependencyAdder](https://docs.gradle.org/7.6-rc-3/dsl/org.gradle.api.artifacts.dsl.DependencyAdder.html), which accepts a `ProjectDependency`, **not** a `Project`, as in the top-level `dependencies` block.  You need to call the `project()` method to obtain one of these.

This is a subtle change, and definitely a possible stumbling block.  Thanks for pointing it out!  We'll add a note to the upgrade guide.

**Comment by ianbrandt** [comment]
Thanks @tresat, I was able to upgrade to 7.6 RC3 successfully [using `project()` instead of `project`](https://github.com/sdkotlin/sd-kotlin-talks/commit/4a82d2368fdf3020fcac88f4dbb649bd37b331b9#diff-1d2ab750de346813cbd579cbfa2ecc61d8813a999ad93c68e2cec44133277d97R20).

**Comment by bric3** [comment]
For people discovering this issue with versions catalog items, you need to change the declarations this way

```diff 
  testing {
      suites {
          val test by getting(JvmTestSuite::class) {
              useJUnitJupiter(libs.versions.junit.jupiter.get())
              dependencies {
-                 implementation(libs.assertj)
+                 implementation.add(libs.assertj)
-                 implementation(libs.bundles.batik)
+                 implementation.bundle(libs.bundles.batik)
              }
          }
```

To find the relevant method, inspect [`DependencyAdder` doc](https://docs.gradle.org/7.6-rc-3/dsl/org.gradle.api.artifacts.dsl.DependencyAdder.html).

As this isn't clearly explained in neither the [release note](https://docs.gradle.org/7.6/release-notes.html) nor the [_differences doc_](https://docs.gradle.org/7.6/userguide/jvm_test_suite_plugin.html#differences_between_the_test_suite_dependencies_and_the_top_level_dependencies_blocks). There's only a mention of the bundle lost in a long list. I believe some examples would have been better in this case.

**Comment by tresat** [comment]
> As this isn't clearly explained in neither the [release note](https://docs.gradle.org/7.6/release-notes.html) nor the [_differences doc_](https://docs.gradle.org/7.6/userguide/jvm_test_suite_plugin.html#differences_between_the_test_suite_dependencies_and_the_top_level_dependencies_blocks). There's only a mention of the bundle lost in a long list. I believe some examples would have been better in this case.

@bric3 - Finally got around to updating the docs here: https://github.com/gradle/gradle/pull/28828.  Thank you for pointing this out!
