### ISSUE TITLE
Gradle 8.0-milestone-3 regression: Transform selection algorithm has changed (longer chain is selected)

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#22735]
### Version
Regression in **Gradle 8.0-milestone-3** compared to Gradle 7.5

### Issue
Suppose `:lib` publishes artifact types `A` and `B`, and `:app` has 2 transforms from `A` to `B` and `B` to `C`. 

Scenario 1: If `:app` requests `B`, Gradle will get artifact `B` published from `:lib` directly without running the transform to convert `A` to `B`. This is the case in both Gradle 7.5 and Gradle 8.0-milestone-3.

Scenario 2: If `:app` requests `C`, the behavior in the two versions are different.
  - a) In Gradle 7.5, Gradle will get `B` from `:lib` and run only 1 transform to convert `B` to `C`.
  - b) In Gradle 8.0-milestone-3, Gradle will get `A` from `:lib` and run 2 transforms to convert `A` to `B`, then `B` to `C`. => **This is a behavior change from Gradle 7.5**, it is inconsistent with scenario 1, and it is also inefficient (longer chain is selected). It is breaking one of our tests in AGP when we try to update to Gradle 8.0-milestone-3.
  
### Steps to reproduce
  1. Open the attached project: [MyApplication.zip](https://github.com/gradle/gradle/files/10014520/MyApplication.zip)
  2. Run `./gradlew --stop && ./gradlew clean :app:printArtifacts`. Observe that 2 transforms are executed (this corresponds to scenario 2b above):
```
> Transform full.jar (project :lib) with CustomTransform
Running CustomTransform on MyApplication/lib/build/intermediates/full_jar/debug/full.jar to produce MyApplication/lib/build/.transforms/5423cd115abb5d76cca6a332703a7b9c/transformed/full.jar.transformed

> Transform full.jar (project :lib) with CustomTransform
Running CustomTransform on MyApplication/lib/build/.transforms/5423cd115abb5d76cca6a332703a7b9c/transformed/full.jar.transformed to produce MyApplication/lib/build/.transforms/0814f6542c157e4e9bc67383f208a4f1/transformed/full.jar.transformed.transformed

> Task :app:printArtifacts
artifactFiles contain: [MyApplication/lib/build/.transforms/0814f6542c157e4e9bc67383f208a4f1/transformed/full.jar.transformed.transformed]
```

3. In `gradle-wrapper.properties`, switch to using Gradle 7.5 and run the above command again. Observe that only 1 transform is executed (this corresponds to scenario 2a above):
```
> Transform debug (project :lib) with CustomTransform
Running CustomTransform on MyApplication/lib/build/intermediates/consumer_proguard_dir/debug to produce MyApplication/lib/build/.transforms/a4bb0cfcffa01a919b9e4293031893a2/transformed/debug.transformed

> Task :app:printArtifacts
artifactFiles contain: [MyApplication/lib/build/.transforms/a4bb0cfcffa01a919b9e4293031893a2/transformed/debug.transformed]
```

#### Expected behavior

In scenario 2, case (2a) should happen and case (2b) should not happen for all versions of Gradle.

**Comment by wolfs** [comment]
@hungvietnguyen Can you please check the behaviour for Gradle 7.6 RC3 as well?

**Comment by gavra0** [comment]
@wolfs There is a sample project attached in the 1st comment. If you change the Gradle version to 7.6, do you get the 7.5 output or 8.0?

**Comment by wolfs** [comment]
I get the 7.5 output when using 7.6, so the change seems to have happened in between.

**Comment by hungvietnguyen** [comment]
Yes, the behavior of Gradle 7.6-rc-3 is the same as Gradle 7.5.

**Comment by wolfs** [comment]
I debugged this and I think it is this change: https://github.com/gradle/gradle/commit/1263f2b79b6d47383d4739305be0f0264dcb3967
We seem to try to disambiguate between the two variants coming in via the two transform chains (one of length one, the other one of length two). The longer chain wins since it has the extra `org.gradle.libraryelements` attribute. I don’t know why we did the change above, nor why we don’t eliminate longer transform chains already earlier in the disambiguation.

**Comment by hungvietnguyen** [comment]
Side note:
  - It would be great to have a doc to describe the exact, unambiguous transform selection algorithm.
  - IIUC, `org.gradle.libraryelements=jar` is added implicitly to jars by Gradle, so it slightly adds to the complexity (i.e., it is hard for the users to reason about the behavior if they are not aware of this fact).
