### ISSUE TITLE
Specify maxHeapSize for checkstyle task does not work

### ISSUE THREAD

**Issue by dietzsch** [gradle/gradle#22736]
Hi,

we have a multi-module Java project that is using the checkstyle plugin. Till Gradle 7.5 the build for that project worked fine. With the migration to Gradle 7.5/7.5.1 we are running in an OOM error during checkstyle. In the release notes we found the remark on the changes to the checkstyle plugin. There you state that you should set the minHeapSize/maxHeapSize to overcome the OOM error.
Problem is that these two properties are not defined on the checkstyle extension. I have seen that class org.gradle.api.plugins.quality.Checkstyle contains the methods to set these properties, but in our case we have the task not at hand. We just apply the checkstyle plugin and provide the configuration vie checkstyle extension.
I tried to overwrite the task to set the maxHeapSize, but I couldn't as I could not overwrite. Now I'm stuck, on how to set these properties, but I would like to prevent disabling the checkstyle plugin at all.

Any hint on how to set these properties when using the plugin would be very helpful.

Thank you in advance!

best regards,
Alex

**Comment by jvandort** [comment]
You can easily configure all `Checkstyle` tasks with: 
```groovy
tasks.withType(Checkstyle).configureEach {
    maxHeapSize = '2g'
}
```
Does this solve your problem?

**Comment by dietzsch** [comment]
@jvandort Yes, that resolved the issue. Thanks a lot for your support!
