### ISSUE TITLE
Aggregration plugins not working with custom JVM Test Suites

### ISSUE THREAD

**Issue by LarsKaulen** [gradle/gradle#22744]
### Expected Behavior

When configuring a custom JVM Test Suite in a multi-project-build and applying the `test-report-aggregation` and/or `jacoco-report-aggregation` plugin, the custom suite should be considered for all projects.

### Current Behavior

The custom JVM Test Suite is only considered in projects explicitly added to `jacocoAggregation` (standalone project) respectively in the application project (application/distribution project).

### Context

I tried the four samples at https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage_standalone.html, https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage_distribution.html, https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_test_aggregation_standalone.html and https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_test_aggregation_distribution.html.

Each of those use only a `test` test suite. For this the behavior is as expected, as when running the `check` task, `testCodeCoverageReport` is run and therefore also `:utilities:test`, `:list:test` and `:application:test` are executed.

I tried to expand these samples using a custom `integrationTest` test suite.
But if I do so, when running the `check` task, `integrationTestCodeCoverageReport` is run, but only `:application:integrationTest` is executed, not `utilities:integrationTest` and `:list:integrationTest`.

This is the case for all four mentioned samples, in the reproducer below I demonstrate it for the sample https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage_standalone.html.

### Steps to Reproduce 

https://github.com/LarsKaulen/gradle-aggregation-reproducer

### Your Environment

Tested with Gradle 7.5.1 and 7.6-rc-3

**Comment by big-guy** [comment]
Thanks for taking a look at this!

We've made some improvements to this in master/8.0.  Could you take a look with `8.0-20221116231019+0000`?

You can update with:
`gradle wrapper --gradle-version=8.0-20221116231019+0000`

For 7.6+, you'll need to change: `implementation project` to `implementation project()`.

8.0 will be going to RC soon.

**Comment by LarsKaulen** [comment]
Ahh yes of course, should have tested with the most recent as well.

Looks good to me!
