### ISSUE TITLE
Windows start script exit code is always 1

### ISSUE THREAD

**Issue by EugeneAzhogin** [gradle/gradle#2274]
When running bat file generated with :distZip task on Windows, in case of any error bat file exits with code 1, but Java code was

```
public static void main(String[] args) {
   System.exit(42);
}
```
### Expected Behavior
When I ran java console application using generated bat file on Windows I have expected that exit code will be 42, not 1.

### Current Behavior
 In cmd.exe following commands

```
MyJavaApp.bat
echo %ERRORLEVEL%
```
should print 42, but it prints 1.

### Context
I am using exit codes of the exteranl console application to determine a type of the error occurred.

### Steps to Reproduce (for bugs)

1. Create simple java application with gradle
2. Main function looks like
```
public static void main(String[] args) {
   System.exit(42);
}
```
3. build gradle looks like
```
apply plugin: 'application'
mainClassName = 'com.example.MyJavaApp'
sourceCompatibility = 1.8
targetCompatibility = 1.8
```
4. Create distribution with :distZip task
5. In CMD.exe execute generated bat file
```
MyJavaApp.bat
echo %ERRORLEVEL%
```

### Your Environment

Microsoft Windows 10
Intel Core i7
16 Gb RAM

### Research

I have found that using that [windows start script template](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt) for generating windows bat file. It contains following lines
```
:fail
rem Set variable ${exitEnvironmentVar} if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
if  not "" == "%${exitEnvironmentVar}%" exit 1
exit /b 1
```
We can see that any non-zero exit code of java.exe program translates in exit code 1. I suppose the lines should look like
```
:fail
rem Set variable ${exitEnvironmentVar} if you need the _script_ return code instead of
rem the _cmd.exe /c_ return code!
if  not "" == "%${exitEnvironmentVar}%" exit %ERRORLEVEL%
exit /b %ERRORLEVEL%
```

**Comment by bmuschko** [comment]
Thanks for raising the issue. Would you be interested in contributing a pull request for your proposed changed? If you are interested then we should make sure that the same behavior is observed for the *nix-based script.

**Comment by EugeneAzhogin** [comment]
@bmuschko  Yes, I can make a pull request.
Where can I find a contribution rules?

**Comment by lacasseio** [comment]
@EugeneAzhogin Here's the [contribution guideline](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).

**Comment by EugeneAzhogin** [comment]
Workaround of the issue is using custom start script template

In build.gradle add

```
startScripts {
    windowsStartScriptGenerator.template = resources.text.fromFile("customWindowsStartScript.txt")
    unixStartScriptGenerator.template = resources.text.fromFile("customUnixStartScript.txt")
}
```

customWindowsStartScript.txt could be based on [Windows  start script](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/windowsStartScript.txt)

See more [here](https://docs.gradle.org/3.5/javadoc/org/gradle/api/tasks/application/CreateStartScripts.html)
