### ISSUE TITLE
Docs: USER_HOME vs GRADLE_USER_HOME vs HOME?

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#22750]
https://docs.gradle.org/7.5.1/userguide/init_scripts.html#sec:using_an_init_script

The docs say to add init scripts in `USER_HOME/.gradle/` or  `GRADLE_HOME/init.d/`, but does not explain what `USER_HOME` or `GRADLE_HOME` are (environment variables I guess?) or what the values should be. 

It's confusing because `GRADLE_USER_HOME` is documented in the ['build environment' docs](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables), but `GRADLE_USER_HOME` is not used in the 'init script' docs. 

It is unclear whether init scripts should be placed inside `$GRADLE_USER_HOME`, or `$HOME/.gradle` (these two paths might be different!).

`USER_HOME` is mentioned in the 'build environment' docs, but not explained. Does it mean the standard POSIX environment variable `HOME`?

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.
