### ISSUE TITLE
Gradle-8.0

### ISSUE THREAD

**Issue by zph666** [gradle/gradle#22767]
A problem occurred configuring project ':app'.
> Could not create task ':app:transformClassesWithAPMSPluginForDebug'.
   > Cannot use @TaskAction annotation on method IncrementalTransformTask.transform() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.

error  7.3.1->8.0-milestone-1

**Comment by ljacomet** [comment]
This is a [breaking change in Gradle 8.0](https://docs.gradle.org/nightly/userguide/upgrading_version_7.html#legacy_artifacttransform_api), the code needs to be adapted.
