### ISSUE TITLE
Gradle signing plugin doesn't work with GPG 2.1.20

### ISSUE THREAD

**Issue by rahulsom** [gradle/gradle#2277]
This is my version of gpg

```
# gpg --version
gpg (GnuPG) 2.1.20
libgcrypt 1.7.6
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/rahul/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

It doesn't generate a `secring.gpg` anymore. (https://www.gnupg.org/faq/whats-new-in-2.1.html)

```
# ls -1 ~/.gnupg
S.dirmngr
S.gpg-agent
S.gpg-agent.browser
S.gpg-agent.extra
S.gpg-agent.ssh
crls.d
dirmngr.conf
gpg.conf
openpgp-revocs.d
private-keys-v1.d
pubring.kbx
pubring.kbx~
trustdb.gpg
```

The gradle signing plugin doesn't work with this. Is there a setting that allows signing of artifacts with the newer format?

### Expected Behavior
The signing plugin and its documentation should be updated to support the newer format

### Current Behavior
There doesn't seem to be any documentation for the new format.

### Context
I'm unable to use the signing plugin which is a must for publishing to oss.sonatype.org

**Comment by bmuschko** [comment]
There's no setting to make the signing plugin with newer versions of GPG. Would you be interested in looking into a fix?

**Comment by rahulsom** [comment]
Thanks @bmuschko. I'll try working on it.

**Comment by rahulsom** [comment]
I looked at gradle's implementation and it uses bouncy castle. 

Bouncy castle, AFAICT does not yet support the `.kbx` format - http://bouncy-castle.1462172.n4.nabble.com/GnuPG-2-1-New-file-formats-td4658595.html

----

Do you have any thoughts on what's the best way to proceed?

**Comment by emlun** [comment]
One possible solution is PR #2724, which would make it possible for plugins such as [gradle-gpg-signing-plugin][gpg-signing] to provide custom signing backend implementations.

[pull]: https://github.com/gradle/gradle/pull/2724
[gpg-signing]: https://github.com/Yubico/gradle-gpg-signing-plugin

**Comment by eriwen** [comment]
Let's continue the discussion in #888; this is a duplicate.
