### ISSUE TITLE
"Unable to make progress running work" redux3

### ISSUE THREAD

**Issue by jimshowalter** [gradle/gradle#22780]
You closed https://github.com/gradle/gradle/issues/22761 as a duplicate of https://github.com/gradle/gradle/issues/22734, which is also closed.

But, the bug I reported in https://github.com/gradle/gradle/issues/22761 is in the latest rc candidate (7.6-rc-3), which means it's not fixed.

Why are you closing bug reports for bugs that aren't fixed?

**Comment by eskatos** [comment]
Hi @jimshowalter,
Sorry about the confusion, the issue reported against 7.6 RC3 will be fixed in 7.6 RC4.
See my https://github.com/gradle/gradle/issues/22761#issuecomment-1319740555 on how to try a nightly.
I'm closing this issue, please open another issue if RC4 will not work for you.
