### ISSUE TITLE
issues.gradle.org has incorrect instructions

### ISSUE THREAD

**Issue by rahulsom** [gradle/gradle#2278]
If you go to issues.gradle.org, it shows you this:

![image](https://user-images.githubusercontent.com/193047/27007341-e4e2e62a-4e04-11e7-9a1a-7c5e0228c84f.png)

Searching for "gradle issue tracker" on google led me there. Trying to create a "bug" post on discuss.gradle.org was not possible. I suppose this is because that has been deprecated in favor of github issues.

The banner on that page should be updated to reflect this change.

Also, if possible, `robots.txt` should be updated so google doesn't lead people to that site.

**Comment by bmuschko** [comment]
Thanks for reporting! I changed the banner.

**Comment by rahulsom** [comment]
Thanks @bmuschko. The "Introduction" section is fixed. The banner on the top still needs fixing.

**Comment by bmuschko** [comment]
@rahulsom Done. Hadn't noticed that before.

**Comment by rahulsom** [comment]
[![LGTM](http://lgtm.in/p/wCjdLiCln)](http://lgtm.in/i/wCjdLiCln)

[:+1:](http://lgtm.in/u/wCjdLiCln) [:-1:](http://lgtm.in/r/wCjdLiCln)
