### ISSUE TITLE
Building gradle itself fails during toolchain download: permission denied copying a file within `.gradle/jdks`

### ISSUE THREAD

**Issue by smowton** [gradle/gradle#22796]
### Expected Behavior

Able to build Gradle

### Current Behavior

Building Gradle fails as of roughly September 30th if a JDK11 toolchain needs to be downloaded, failing during unpacking the downloaded JDK with a permission error while copying `.gradle/jdks/OpenJDK11U-jdk_x64_mac_hotspot_11/...some-read-only-file` to `.gradle/jdks/eclipse_adoptium-11-x86_64-os_x/...some-read-only-file`

Build works as expected if the needed JDK is found through detection on your local system, or was in `.gradle/jdks` already, including because of a previous failure building this project.

### Steps to Reproduce 

1. `git clone https://github.com/gradle/gradle; cd gradle; git checkout 4595851c30a4dc95a68c460e9b95259ca60b8060` (current `master` as of time of writing)
2. Clear `$HOME/.gradle/jdks` to ensure the build will try to download a toolchain
3. `./gradlew -Dorg.gradle.java.home=/some/jdk11/home/ -Porg.gradle.java.installations.auto-detect=false` (using auto-detect=false to ensure a local JDK isn't picked up)

Result:

```
A problem occurred configuring root project 'gradle'.
> Could not determine the dependencies of null.
   > Could not resolve all dependencies for configuration ':classpath'.
      > Failed to calculate the value of task ':build-logic:lifecycle:compileJava' property 'javaCompiler'.
         > Unable to download toolchain matching the requirements ({languageVersion=11, vendor=ADOPTIUM, implementation=vendor-specific}) from 'https://api.adoptium.net/v3/binary/latest/11/ga/mac/x64/jdk/hotspot/normal/eclipse'.
            > Could not copy file '/Users/myusername/.gradle/jdks/OpenJDK11U-jdk_x64_mac_hotspot_11/jdk-11.0.17+8/Contents/Home/legal/java.management.rmi/LICENSE' to '/Users/myusername/.gradle/jdks/eclipse_adoptium-11-x86_64-os_x/jdk-11.0.17+8/Contents/Home/legal/java.management.rmi/LICENSE'.
               > /Users/myusername/.gradle/jdks/eclipse_adoptium-11-x86_64-os_x/jdk-11.0.17+8/Contents/Home/legal/java.management.rmi/LICENSE (Permission denied)
```

The specific file varies, and can be any file in the JDK tarball with a read-only mode, e.g. the LICENSE or README files, or various `.md` files in the legal subdirectory. The failure results because we're trying to truncate and overwrite a read-only file. Given the simplicity of `provisionFromArchive` (https://github.com/gradle/gradle/blob/master/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/install/JdkCacheDirectory.java#L120), I suspect this is a case of mistakenly calling that routine twice without cleaning up the install directory, so the first unpack goes as expected, then the second tries to overwrite the first and fails due to these read-only files.

I first noticed this because lgtm.com started failing to build `gradle/gradle` on September 30th; the times of its regular builds allow us to isolate the problem to this commit range: https://github.com/gradle/gradle/compare/764ed77dcea33db8840d0a2afd9ae4f284e1daf4...5eb959671e9d45827b9482e5003c8572410551ab

### Your Environment

This is reproducible on many platforms: lgtm.com's workers as mentioned above are based on Ubuntu 20.04, but I can also reproduce the problem on MacOS Ventura with the same symptoms. Reproducibility can vary based on the JDKs available locally, but clearing `.gradle/jdks` and using `-Porg.gradle.java.installations.auto-detect=false` to insist on a downloaded toolchain seems to reliably reproduce the problem.

**Comment by joel-jeremy** [comment]
I am encountering a similar issue. Although my workflow is using JDK 19 instead of JDK 11. 

See `Build with Gradle` error here: https://github.com/joel-jeremy/externalized-properties/actions/runs/3545156602/jobs/5953063148

**Comment by shakuzen** [comment]
If another data point helps, we're seeing what I think is the same issue in the Micrometer build (see, for example, https://ge.micrometer.io/s/vxhaweu5wfjhm) which we're tracking with https://github.com/micrometer-metrics/micrometer/issues/3549.

**Comment by jbartok** [comment]
Thank you all for the information and reproducers. We now understand what is causing the problems and are working on a fix.
