### ISSUE TITLE
Custom Scripting Language support

### ISSUE THREAD

**Issue by U1F984** [gradle/gradle#22793]
At the moment, Gradle supports two scripting languages for build scripts: Groovy and Kotlin. This decision was implemented in commit 45be6604a83fc7ab582c25fcbeef450de45ec864, where the previous SPI mechanism was removed (it is still referenced in the `ScriptPluginFactorySelector ` documentation). It would be helpful if the supported script languages would be extensible again.

### Expected Behavior
It is possible to extend the supported scripting languages.

### Current Behavior
The supported scripting languages are hardcoded in `org.gradle.internal.scripts.ScriptingLanguages#ALL`.

### Context
In our specific case we would like to use configuration-based build files (e.g. JSON or TOML), but there could be other usecases.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

----

Note that we're working on improving script compilation performance, parallel configuration and configuration avoidance.
