### ISSUE TITLE
Init task generates deprecated code for plugin in Kotlin language

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#22795]
If you use the `init` task to generate a Gradle plugin build with Kotlin language, it generates code that is immediately deprecated.
The generated plugin registers an ad-hoc task using a Kotlin lambda that is now without further measures compiled to comparable bytecode like a Java lambda and so if you use that plugin, you get a deprecation warning, that Java lambdas as task actions are deprecated.

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

---

Hi @Vampire,

Could you please provide an example of build-init choices that produces problematic code. Also please share the deprecation message you get. Sorry for being pedantic here but we're trying to handle issues uniformly. I'm sure you'll appreciate the value of this.

Cheers
