### ISSUE TITLE
[Feature Request] - Please add Gradle's plugin repository to DefaultRepositoryHandler

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#2280]
I recently saw that `google()` was added to the `DefaultRepositoryHandler` here: https://github.com/gradle/gradle/blob/e3ab5bcfd22114c1ca88256017f069e33933e6ef/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultRepositoryHandler.java#L89.

I made a PR(https://github.com/gradle/gradle/pull/613) a while ago to add "https://plugins.gradle.org/m2/" to `DefaultRepositoryHandler`. **Why was Google's third party maven repository added before Gradle's very own plugin repository?**

For people that cannot use the `plugins` block because of Android projects(Android Gradle plugin is not in the Gradle plugin repository, 3.0 is in `maven.google.com`), we have to manually specify our `buildscript` `repositories` like this(for example):

```
buildscript {
  repositories {
    jcenter()
    mavenCentral()
    google()
    maven { url "https://plugins.gradle.org/m2/" } <-- We still have to manually add this
    ...
  }

  dependencies {
    classpath "com.android.tools.build:gradle:3.0.0-alpha3"
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4"
    ...
  }
}

repositories {
  jcenter()
  mavenCentral()
  google()
  maven { url "https://plugins.gradle.org/m2/" } <-- We still have to manually add this
  ...
}
```

Since we know that `maven { url "https://plugins.gradle.org/m2/" }` mirrors both `jcenter()` and `mavenCentral()`, I can simply remove both `jcenter()` and `mavenCentral()`:

```
repositories {
  google()
  maven { url "https://plugins.gradle.org/m2/" } <-- We still have to manually add this
  ...
}
```

It would be great to simply this with it's own repository handler, such as `pluginRepo()`.

**Comment by jaredsburrows** [comment]
Any update on this? Can I revive my PR for this?

**Comment by bmuschko** [comment]
> Since we know that `maven { url "https://plugins.gradle.org/m2/" }` mirrors both `jcenter()` and `mavenCentral()`, I can simply remove both `jcenter()` and `mavenCentral()`

Our standpoint hasn't changed in this regard. That's why we didn't want to add it in the first place. Please see [our discussion on the dev list](https://groups.google.com/forum/#!topic/gradle-dev/mghxM_9vvv8).

> Why was Google's third party maven repository added before Gradle's very own plugin repository?

The Google repository does not mirror Maven Central or any other repository to my knowledge. It's also fully managed by Google so we don't have to get involved in the management of that repository.

**Comment by jaredsburrows** [comment]
@bmuschko Alright. I guess I will close this.
