### ISSUE TITLE
Release notes of Gradle 4.0 for gradle-script-kotlin version are wrong

### ISSUE THREAD

**Issue by GFriedrich** [gradle/gradle#2283]
In #2205 it was stated that the version for the gradle-script-kotlin version is wrong in the release notes. So it was changed from 0.9.0 to 0.9.1
This is not correct: Gradle 4.0 still ships with version 0.9.0 (see the dependency in build.gradle file)
Either revert the change that was made in #2205 or additionally merge 8111419 to Gradle 4.0

**Comment by bamboo** [comment]
Thanks for the heads-up, @GFriedrich!

**Comment by GFriedrich** [comment]
You're very welcome @bamboo (... and wow - that was a fast re-release ;) )
