### ISSUE TITLE
JavaToolchainService.compilerFor will provide a JRE in case that is the only toolchain available

### ISSUE THREAD

**Issue by sorin-florea** [gradle/gradle#22831]
Currently, `JavaToolchainService.compilerFor` will return a JRE in case no JDK is available, and only a JRE is detected. 

### Expected Behavior
`JavaToolchainService.compilerFor` should never return something backed by a JRE.

### Current Behavior
Currently, it will take [JDK over JRE](https://github.com/gradle/gradle/blob/419f98937994b291ad48ba3cdf04d94d42009bf3/subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/internal/JavaToolchainComparator.java#L30) however, there is no check in case only a JRE is available.

### Steps to Reproduce 
Run it on a machine where only a JRE is detected.

### Proposal
I propose to enhance `JavaToolchainSpec` also to be able to request specific capabilities and request a `JAVA_COMPILER` capability when calling `JavaToolchainService.compilerFor`

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

**Comment by big-guy** [comment]
@sorin-florea when 8.10 RC1 comes out, could you take a look that this fixes your issue and if you're able to use toolchains in the DV build in more places?

**Comment by vkarppinen** [comment]
Hello.

We have experienced that the merge request #29704, fixing this issue, causes a different problem.

Now, we've started getting the following error in our CI after updating to gradle 8.10:
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':test'.
> Could not resolve all dependencies for configuration ':testRuntimeClasspath'.
   > Failed to calculate the value of task ':compileTestJava' property 'javaCompiler'.
      > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=17, vendor=any vendor, implementation=vendor-specific} for LINUX on x86_64.
         > No locally installed toolchains match and toolchain download repositories have not been configured.
 ```
 
So we are running our test suites in the CI using a JRE image which does not contain `javac` or `javadoc` executables.
This gives us confidence that the code runs fine in production environments as well. The particular test job does not need to do any compilation.

We noticed that if we include the `javac` or `javadoc` executables in to the image, resolving the toolchain works just fine.
Referring to the following integration tests:
- ["fails if no toolchain has a javadoc tool"](https://github.com/gradle/gradle/blob/b0ce272a85977d3407a9921e4313596f21b63c9b/platforms/jvm/language-java/src/integTest/groovy/org/gradle/api/tasks/javadoc/JavadocToolchainIntegrationTest.groovy#L191-L215)
- ["fails if no toolchain has a compiler"](https://github.com/gradle/gradle/blob/b0ce272a85977d3407a9921e4313596f21b63c9b/platforms/jvm/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileToolchainIntegrationTest.groovy#L382-L406)

Is it a valid requirement that `javac` and `javadoc` executables are required?

Any advice?

**Comment by vkarppinen** [comment]
Thanks for getting back @octylFractal 🙂 

Our projects are mainly written in Kotlin, tests included, and thus for `compileTestJava` task there are no sources.
In higher level we are running builds, including compilation of main and test sources, in CI pipelines in different "jobs" than we do run the actual tests. We utilize build cache and transfer it from a job to another. This means that the test job depending on the build job does not need to do any compilation.

In my opinion this requirement for the toolchain resolving to check whether the compiler or the javadoc tool do exist is a bit vague.
Why don't just let the the actual task (here `compileTestJava`) that depends on for example the compiler, to fail on missing classes?

All of the above is just my personal opinion. We can very well workaround the problem easily by including the needed executables into our job runner image.

**Comment by octylFractal** [comment]
> Why don't just let the the actual task (here compileTestJava) that depends on for example the compiler, to fail on missing classes?

That is actually the intention here, this is inside of the provider given by `compilerFor` so the requirement for a compiler is to ensure the provider's path is valid. 

This is a valid issue, I've opened #30264 to track it.
