### ISSUE TITLE
[Ask for help]:  explanation on these issues tags

### ISSUE THREAD

**Issue by bodhili** [gradle/gradle#22872]
hi, 
    I don't know the current description of these issues labels, so I would like to ask if there is any documentation about these issues labels, for example: label:"onboarding" and  label:"a:chore"?  And  have any suggestions for new contributors?   thanks.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to contribute to Gradle. Your question might be answered in Gradle [contributing guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

`CONTRIBUTING.md` explains `onboarding` and `help-wanted` labels. Other should be either self explanatory or have a description that you can find here https://github.com/gradle/gradle/labels Some might be missing descriptions though.

HTH

**Comment by bodhili** [comment]
> Thank you for your interest in Gradle!
> 
> Your issue appears to be a question about how to contribute to Gradle. Your question might be answered in Gradle [contributing guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).
> 
> `CONTRIBUTING.md` explains `onboarding` and `help-wanted` labels. Other should be either self explanatory or have a description that you can find here https://github.com/gradle/gradle/labels Some might be missing descriptions though.
> 
> HTH

Yes, it is. I'm looking forward to contributing to gradle, but I'm currently learning gradle design and source code. Thank you for the help and have a nice day
