### ISSUE TITLE
Inconsistencies between resolved SNAPSHOT artifact and resolved SNAPSHOT parent POM

### ISSUE THREAD

**Issue by britter** [gradle/gradle#22884]
- Given a module `com.example:foo` with version `4.0.0-SNAPSHOT`
- Given `com.example:foo` references a parent POM called `com.example:foo-parent:4.0.0-SNAPSHOT`
- Given my build that wants to consume a timestamp version of `com.example:foo` by declaring `implementation("com.example:foo:4.0.0-20221030.075154-12")`
- When there is a later SNAPSHOT of `com.example:foo-parent` available in the repository
- Then Gradle will resolve that later version of the parent POM leading to inconsistencies
- And there is no was to control this behavior

### Expected Behavior

The parent POM should be resolved consistently with the timestamped SNAPSHOT version of the artifact or there should be a programmatic way to influence this.

### Current Behavior

As described about, the latest SNAPSHOT of the parent POM will always be selected.

### Context

I'm trying to build something against `org.apache.maven:maven-core:4.0.0-alpha-3-SNAPSHOT` so I've defined a dependency to `org.apache.maven:maven-core:4.0.0-alpha-3-20221030.075154-12`. In `org.apache.maven:maven` parent POM controls some of the version of the modules that are used in the maven build. In [this commit](https://github.com/apache/maven/commit/c6ecff9923088d854d4621e17d602f1c70dda806) the version of `org.apache.maven.resolver:maven-resolver-impl` was updated from 1.8.2 to 1.9.2. Since Gradle started to resolved the SNAPSHOT of the parent that had this change, my build started failing because I have `resolutionStrategy.failOnVersionConflict()` enabled and Gradle resolved a conflict between version 1.8.2 and 1.9.2 of `org.apache.maven.resolver:maven-resolver-impl`.

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
If I understand correctly, what you would like is a way to say my main component is version `4.0.0-alpha-3-20221030.075154-12` so any of its parent POMs should use versions `<=` to that one.
Because there is no guarantee that you can use that exact snapshot version for the whole hierarchy for example.

Does anyone know if Maven works that way at all?

**Comment by britter** [comment]
@ljacomet Yeah, I guess this is my expectation. I'm not sure how Maven behaves in this case but I believe it won't work there either. So maybe it's just my very specific use case. As a work around we've deployed a named version of the module, it's parent pom and all referenced modules that had the same SNAPSHOT version to our internal repository.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.
