### ISSUE TITLE
Android plugin unable to find `com.android.ide.common.resources.AssetSet` after updating to 7.6

### ISSUE THREAD

**Issue by clayburn** [gradle/gradle#22891]
After updating the [Android Cache Fix Plugin](https://github.com/gradle/android-cache-fix-gradle-plugin) to use Gradle 7.6 from 7.5.1, it seems that compilation fails due to some missing Android classes. In particular, compilation is unable to find `com.android.ide.common.resources.AssetSet`. This can be pretty easily worked around by adding a dependency to `com.android.tools:sdk-common`, which contains the missing class. It also seems that removing the `@CompileStatic` annotation solves the problem. What isn't clear is why this would be needed on Gradle 7.6 but not Gradle 7.5.1.

### Expected Behavior
Groovy compilation finds `com.android.ide.common.resources.AssetSet` without needing to add any new dependencies.

### Current Behavior
The build fails to find `com.android.ide.common.resources.AssetSet`.

### Context

This worked all the way up to 7.5.1 but first broke on 7.6. This slowed down upgrading the plugin to use Gradle 7.6. Adding the dependency explicitly may be a good solution, but it would be good to know _why_ adding this explicitly is necessary with Gradle 7.6.

### Steps to Reproduce 

Reproducer repo: https://github.com/cdsap/Gradle7.6Issue

Notice that the `compileGroovy` task succeeds on the `main` branch (7.5.1), but fails on the `gradle_7_6` branch. Additionally, the 7.6 branch can be made to work by either:
* Removing the `@CompileStatic` annotation from the `Foo` class
* Adding a dependency to `implementation("com.android.tools:sdk-common:30.0.4")`

### Your Environment

Build scan URLs:
Working on 7.5.1: https://gradle.com/s/t2nvszm366m4g
Failing on 7.6: https://gradle.com/s/hzujkiawsxzli

**Comment by ljacomet** [comment]
This is a behavior change that comes through the Groovy upgrade.

See the [draft PR](https://github.com/cdsap/Gradle7.6Issue/pull/2) illustrating how to reproduce the problem with Gradle 7.5.1

This is noted as a [potential breaking change](https://docs.gradle.org/current/userguide/upgrading_version_7.html#upgrade_to_groovy_3_0_13) although you might want to open an issue on the [Groovy bug tracker](https://issues.apache.org/jira/projects/GROOVY/summary).

So while this is a regression, we will not downgrade Groovy again, so we are accepting it.
