### ISSUE TITLE
Nag for deprecation of BasePluginExtension members

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#22908]
* `String getDistsDirName();`
* `void setDistsDirName(String distsDirName);`
* `String getLibsDirName();`
* `void setLibsDirName(String libsDirName);`
* `String getArchivesBaseName();`
* `void setArchivesBaseName(String archivesBaseName);`

This should happen in 8.1 with a message that says it will become an error in 9.0.

Soft deprecated in 7.1 by

* https://github.com/gradle/gradle/pull/16900

This can't be done until Kotlin plugin for android remove deprecated usages

* https://youtrack.jetbrains.com/issue/KT-56421 - DONE in Kotlin 1.8.10

PR with the added deprecation nagging

* https://github.com/gradle/gradle/pull/23813

**Comment by iiasceri** [comment]
And how to do it now? archivesBaseName
