### ISSUE TITLE
Strict dependency locking doesn't allow for optional dependencies

### ISSUE THREAD

**Issue by ccjernigan** [gradle/gradle#22922]
### Expected Behavior
If strict dependency locking is enabled AND a dependency is present in the lock files but not used by the application, the build should still succeed.

### Current Behavior
`> Did not resolve 'x:y:123' which is part of the dependency lock state`

### Context

I would like to use strict dependency locking. My threat model is about third party libraries or Gradle plugins that don't use exact dependency versions, causing my builds to be either A. inconsistent or B. vulnerable to the dependency being replaced with a malicious newer version.

As currently implemented, strict locking fails if a dependency called for in the locks is not consumed by the project.  Therefore strict locking doesn't work with a variety of common development patterns such as:
 - Using machine learning libraries with architecture or GPU specific implementations (e.g. I develop on an M1 Mac but run CI on an x86 Linux GitHub Actions worker)
 - Swapping between database implementations for local development (SQLite) and server deployment (Postgres)

The best solution I have currently is to use LENIENT mode, but that is not strict enough because it allows another team member to add a new dependency and forget to update the locks.

Examples of how I currently manage my dependency declarations, which might help make this pain point more clear:

Switching between SQLite and Postgres
```
        val jvmMain by getting {
            dependencies {
                implementation(libs.bundles.exposed)

                if (gradle.startParameter.isWriteDependencyLocks) {
                    // Include all when updating dependency locks
                    implementation(libs.postgres)
                    implementation(libs.xerial)
                } else {
                    // Both Postgres and SQLite cannot be compiled in at the same time; it'll cause runtime failures
                    if (isDeployedDb) {
                        implementation(libs.postgres)
                    } else {
                        implementation(libs.xerial)
                    }
                }
            }
        }
```

Switching between different machine learning backend engines, each of which has platform specific classifiers.
```
                if (gradle.startParameter.isWriteDependencyLocks) {
                    implementation(libs.djl.engine.mxnet)
                    runtimeOnly(project.dependencies.variantOf(libs.djl.engine.mxnet.cpu) { classifier("linux-x86_64") })
                    runtimeOnly(project.dependencies.variantOf(libs.djl.engine.mxnet.cpu) { classifier("osx-x86_64") })
                    runtimeOnly(project.dependencies.variantOf(libs.djl.engine.mxnet.cpu) { classifier("win-x86_64") })

                    implementation(libs.djl.engine.pytorch)
                    runtimeOnly(project.dependencies.variantOf(libs.djl.engine.pytorch.cpu) { classifier("linux-x86_64") })
                    runtimeOnly(project.dependencies.variantOf(libs.djl.engine.pytorch.cpu) { classifier("osx-x86_64") })
                    runtimeOnly(project.dependencies.variantOf(libs.djl.engine.pytorch.cpu) { classifier("win-x86_64") })
                } else {
                    when (defaultBackend) {
                        DjlBackend.MxNet -> {
                            implementation(libs.djl.engine.mxnet)
                            runtimeOnly(project.dependencies.variantOf(libs.djl.engine.mxnet.cpu) { classifier(libs.versions.djlMxnetCpuClassifier.get()) })
                        }
                        DjlBackend.PyTorch -> {
                            implementation(libs.djl.engine.pytorch)
                            runtimeOnly(project.dependencies.variantOf(libs.djl.engine.pytorch.cpu) { classifier(libs.versions.djlPytorchCpuClassifier.get()) })
                        }
                    }
                }
```

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

----

The strict mode will not be made lenient.
The current lenient mode is just about that, being lenient with dependencies that are not consumed.

If you want to make the strict mode work for you, you should change how your dependencies are declared to put the different sets of dependencies into separate configurations. Those configurations would then be strictly locked. And the compile task would use one or the other depending on your build invocation.
