### ISSUE TITLE
gradle daemon - ci builds with forked javac frequently fail

### ISSUE THREAD

**Issue by cal101** [gradle/gradle#2292]
(Platform: Linux)
We are migrating legacy projects from ant to gradle.
To avoid coupling the java compiler to the java runtime used by gradle we let gradle fork the java compiler.
That means the daemon gets into play using SingleUseDaemonClient.
You want to avoid the daemon on a CI server but that seems not to be possible when forking the compiler is enabled. 

Option 1: Make forking the compiler possible without using a daemon.

We have lots of single calls of "./gradlew --no-daemon" because migration is done piece by piece.
That means a lot of short lived daemons get started.
The builds are done by jenkins on a 40 core machine HAVING SLOW IO.
The daemons fight for access to the registry file and a lot of calls of gradle fail with timeouts.

Option 2: Do not use the global registry for short lived daemons but use a separate setting. 
(Can be related to https://github.com/gradle/gradle/issues/1839)

Explicitly ENABLING the daemon on the CI server in the gradle calls reduced the problems somewhat
because there is less contention but the builds are fragile.

Is there is any workaround or fix available?

If not: I am willing to fix that issue if someone from the team tells me how they want it to be done:

How should the solution look like?

I imagine something like providing an UUID for single daemon calls and either using that
for the single call registry or trying to avoid the registry at all. 
I saw some UUID generation in the daemon related code already.
If easy to solve I may also fix https://github.com/gradle/gradle/issues/1839 on the way.

Let's discuss how the solution should look like and I do it.

**Comment by jjohannes** [comment]
@cal101 did I understand correctly that you want to run many independent Gradle builds on one machine, but they interfere too much because they fight for access to the daemon registry file?

A workaround can be to make each build isolated (which includes using it's own daemon registry) by giving each build it's own gradle home directory (`--gradle-user-home=`).

**Comment by cal101** [comment]
@jjohannes Exactly!

Sounds like a viable workaround. Thanks! 
To avoid downloading the gradle wrapper stuff multiple times some soft links may be needed but thats 
just details.
I will try that.

**Comment by cal101** [comment]
@jjohannes The work around works. So far no gradle related timeouts! Thanks!

**Comment by oehme** [comment]
> You want to avoid the daemon on a CI server but that seems not to be possible when forking the compiler is enabled.

There seems to be some misunderstanding here. The Gradle daemon is completely independent of whether you use forked compilation. 

Instead I think your problem might be that you specified `org.gradle.jvmargs` in your gradle.properties, which forces a single-use daemon to honor those args. If you want to force Gradle to run the build inside the client VM, you need to put your VM args into the `GRADLE_OPTS` evironment variable instead and leave `org.gradle.jvmargs` empty.

**Comment by cal101** [comment]
@oehme Looks like you are indeed right. We have org.gradle.jvmargs set. I am trying now without and come back afterwards.

**Comment by cal101** [comment]
@oehme Many thanks! Removing org.gradle.jvmargs from gradle.properties made it possible to disable the use of the daemon.
