### ISSUE TITLE
Task project access becomes an error in 9.0 with STABLE_CONFIGURATION_CACHE

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#22929]
APIs unsupported with configuration caching deprecated in 7.4

* https://github.com/gradle/gradle/pull/19389

Note that this applies only with the `STABLE_CONFIGURATION_CACHE` feature flag enabled.

**Comment by mlopatkin** [comment]
We need to decide first if/how we want to use `STABLE_CONFIGURATION_CACHE` now, when CC itself is stable. Maybe we can start deprecating the behavior without the feature flag first?

**Comment by mlopatkin** [comment]
Our current stance is that we'll get rid of the vintage (non-CC) mode in Gradle 10, so doing stuff under `STABLE_CONFIGURATION_CACHE` isn't needed. I've filed #30860 to track deprecation in 8.x timeline.
