### ISSUE TITLE
Generated Gradle Kotlin DSL API docs might be outdated

### ISSUE THREAD

**Issue by EdricChan03** [gradle/gradle#22953]
Are there plans to update the [generated Gradle Kotlin DSL API documentation](https://gradle.github.io/kotlin-dsl-docs/api/)? I've noticed that the last commit in the gradle/kotlin-dsl-docs repository appears to be from [4 years ago](https://github.com/gradle/kotlin-dsl-docs/commit/f8ada733747c63632d652933af1812bc8221325e), and the Gradle Kotlin DSL has likely been updated since then.

----

Also see
* https://gradle.slack.com/archives/C10J6STFZ/p1673458853606139

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

May I ask, where did you find the link?

**Comment by EdricChan03** [comment]
![Screenshot of Gradle documentation, with "Kotlin DSL API" highlighted in red](https://user-images.githubusercontent.com/20047125/208874853-d696b5b3-6086-4924-b676-239f7fac8823.jpg)


I found it via the "Kotlin DSL API" link in the "Gradle DSLs and API" section of the Gradle documentation

**Comment by eskatos** [comment]
Looking at Dokka again to assess if it can be used.

* The plugin doesn't work on Gradle 8.0
  https://github.com/Kotlin/dokka/issues/2796
* The plugin can't aggregate documentation
  https://github.com/Kotlin/dokka/issues/1752

**Comment by aSemy** [comment]
Hi @eskatos, if you're interested in a version of the Dokka Gradle Plugin that's compatible with the Gradle API, please take a look at my re-write: https://github.com/adamko-dev/dokkatoo/. I'm collaborating with the Dokka devs on it, and the plan is to merge Dokkatoo upstream (eventually).
