### ISSUE TITLE
Show usage information (e.g. description) when @Option is specified incorrectly on command line

### ISSUE THREAD

**Issue by alanv** [gradle/gradle#22955]
Using Gradle 7.6, when a developer fails to correctly specify an `@Option` input correctly, Gradle will fail like:

```
$ ./gradlew :core:core:updateApi --overridePolicyWithApproval

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :core:core:updateApi from command line.
> No argument was provided for command-line option '--overridePolicyWithApproval'.
```

Where the option is specified as:

```
    @get:Option(
        option = "overridePolicyWithApproval",
        description = "Buganizer ID where overriding Semantic Versioning policy was approved."
    )
    @get:Input
    @get:Optional
    abstract val overridePolicyWithApproval: Property<String>
```

However, it might be more informative to the user to fail with the option's description:

```
$ ./gradlew :core:core:updateApi --overridePolicyWithApproval

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :core:core:updateApi from command line.
> No argument was provided for command-line option '--overridePolicyWithApproval' with description:
> Buganizer ID where overriding Semantic Versioning policy was approved.
```

This is enough for the user to understand how they should have specified the argument.

### Expected Behavior
Fails with description:
```
> No argument was provided for command-line option '--overridePolicyWithApproval' with description:
> Buganizer ID where overriding Semantic Versioning policy was approved.
```

### Current Behavior
Fails with no extra information:
```
> No argument was provided for command-line option '--overridePolicyWithApproval'.
```

**Comment by alanv** [comment]
If this sounds reasonable, I'd be happy to put together a PR updating [`CommandLineParser`](https://cs.android.com/android-studio/gradle/+/master:subprojects/cli/src/main/java/org/gradle/cli/CommandLineParser.java;l=448).

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by ljacomet** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by bodhili** [comment]
I submitted a PR about this issue #23006 ,  and we can discuss the feasibility of this solution.  thanks
