### ISSUE TITLE
Incremental compilation is not observed for Scala 3

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#22964]
The same integration test observes Scala 2 incremental compilation, but shows that with Scala 3 all the classes are recompiled.

The relevant tests in `ZincScalaCompilerIntegrationTest` are marked with the link to this issue.

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before a fix is made.

----

Related

* #20101

**Comment by ljacomet** [comment]
* Fixed through #22786
