### ISSUE TITLE
Inconsistency between javadocElements and javadoc variants

### ISSUE THREAD

**Issue by SgtSilvio** [gradle/gradle#22960]
Since Gradle 7.5, Gradle derives not only the `compile` and `runtime` variants from Maven components without Gradle Module Metadata, but also the `javadoc` and `sources` variants.
`compile` and `runtime` act as substitutes for Gradle's `apiElements` and `runtimeElements` variants.
`javadoc` and `sources` should also act as substitutes for `javadocElements` and `sourcesElements`, but they are inconsistent regarding transitive dependencies.

### Expected Behavior

The derived `javadoc` and `sources` are consistent with the `javadocElements` and `sourcesElements` variants.
Two options:
1. The derived `javadoc` and `sources` variants should NOT have any transitive dependencies (preferred)
2. The `javadocElements` and `sourcesElements` variants should also have transitive dependencies from the `runtimeElements` variant (this would be a more breaking change)

### Current Behavior

The derived `javadoc` and `sources` variants have transitive dependencies from the `runtime` variant.
The `javadocElements` and `sourcesElements` variants do NOT have any transitive dependencies.

### Context

Theses variants are important for plugins that process javadoc files. For example, changes/workarounds are required for my plugin: https://github.com/SgtSilvio/gradle-javadoc-links

As the new derived variants were not mentioned in the release notes (afaict), I looked at Gradle's code to find out how it works.  Maybe the links are helpful for this issue:
- commit where the javadoc and sources variants were added: https://github.com/gradle/gradle/commit/0ff23f0db7f35d1903b6966c644a215f2afcaf0c#diff-b5a80424a8414c52e6f50e67353fb9c5a5269dab80c2bc7ee1fc7c30d99d920d
- javadoc and sources use runtimeConfiguration as base: https://github.com/gradle/gradle/blob/c5566ea98bdc48ca42c1bcedae04cc9bd3cd9b1d/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/JavaEcosystemVariantDerivationStrategy.java#L59

### Steps to Reproduce 

The following `build.gradle.kts` shows the difference between dependencies with a `javadocElements` variant (components with Gradle Module Metadata or Gradle Projects) and a dependency with a derived `javadoc` variant:
```kotlin
plugins {
    `java`
}

java {
    withJavadocJar()
}

val foo: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    attributes {
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category.DOCUMENTATION))
        attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named(DocsType.JAVADOC))
    }
}

dependencies {
    // dependency without Gradle Module Metadata -> "javadoc" configuration derived from pom
    foo("io.netty:netty-handler:4.1.85.Final")
    // dependency with Gradle Module Metadata -> "javadocElements" configuration
    foo("com.hivemq:hivemq-mqtt-client:1.3.0")
    // project dependency -> "javadocElements" configuration
    foo(project)
}

afterEvaluate {
    println("dependency without Gradle Module Metadata -> \"javadoc\" configuration derived from pom -> has transitive dependencies")
    foo.files(dependencies.create("io.netty:netty-handler:4.1.85.Final")).forEach { println("> $it") }
    println()
    println("dependency with Gradle Module Metadata -> \"javadocElements\" configuration -> no transitive dependencies")
    foo.files(dependencies.create("com.hivemq:hivemq-mqtt-client:1.3.0")).forEach { println("> $it") }
    println()
    println("project dependency -> \"javadocElements\" configuration -> no transitive dependencies")
    foo.files(dependencies.create(project)).forEach { println("> $it") }
}
```

### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
This behavior is consistent with Maven behavior.

When you declare the following dependency in a pom file:
```
 <dependency>
  <groupId>com.google.inject</groupId>
  <artifactId>guice</artifactId>
  <version>3.0</version>
  <classifier>sources</classifier>
</dependency>
```
then `dependency:tree` shows:
```
[INFO] \- com.google.inject:guice:jar:sources:3.0:compile
[INFO]    +- javax.inject:javax.inject:jar:1:compile
[INFO]    \- aopalliance:aopalliance:jar:1.0:compile
```

Meaning that you get the regular dependencies of the module.

Gradle has a better understanding of metadata and thus knows to not replicate the `api` or `runtime` dependencies for the `sources` and `javadoc` variants when it publishes a project.

However, when a module was not produced by Gradle and only has a POM file, Gradle does as little changes as it can with regards to the metadata content.
And so it will include `runtime` dependencies for the `sources` and `javadoc` variants, matching the Maven behavior.

I am not sure we should decide to always prune `sources` and `javadoc` variants to have no dependencies.

I'll however let the team responsible for adding that feature make the final decision.

**Comment by big-guy** [comment]
I agree that the current behavior can be confusing.

It comes down to a trade off between translating a Maven module to something close to Gradle's view or interpreting it close to Maven's view. We currently do the latter, but it's not clear to me that either way is much better.  Even the API/runtime variants we derive are not 100% the same as if Gradle had produced them, so I think we'll stick with the current behavior unless something changes.

You can sidestep this difference by changing how you're getting Javadoc. Instead of resolving a configuration with "javadoc attributes", you can instead use an ArtifactView on top of the existing runtimeClasspath. 

```
def artifactView = configurations.runtimeClasspath.incoming.artifactView {
    withVariantReselection()
    attributes {
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.DOCUMENTATION))
        attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.EXTERNAL))
        attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named(DocsType, DocsType.SOURCES))
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
    }
}
// iterate over artifactView.files
```

This will resolve the dependency graph as if it were a runtimeClasspath and then walk that resolution result and find any dependency that has a matching variant for those attributes.
