### ISSUE TITLE
[Buildscans] Make stdout of tests preformatted and monospace

### ISSUE THREAD

**Issue by rahulsom** [gradle/gradle#2297]
Take a look at https://scans.gradle.com/s/jfso376y7trha/tests/nuzaumrfo6cam
It currently looks like this

![image](https://user-images.githubusercontent.com/193047/27141853-2d347c1e-50de-11e7-9026-d77ee082d15d.png)

If the stdout is made preformatted and monospace, it becomes more readable. Like this:

![image](https://user-images.githubusercontent.com/193047/27141969-8927b504-50de-11e7-9c37-99bfe4340fec.png)

**Comment by facewindu** [comment]
Hi

This has just been fixed, will be deployed during the day on scans.gradle.com, and on the next GE release.

Thanks for reporting!
