### ISSUE TITLE
DefaultWorkerProcessBuilder asking for too little memory

### ISSUE THREAD

**Issue by bantonsson** [gradle/gradle#22977]
### Expected Behavior

When the `DefaultWorkerProcessBuilder` creates a new [`MemoryRequestingWorkerProcess`](https://github.com/gradle/gradle/blob/daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8/subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessBuilder.java#LL257C32-L257C32) it should ensure that the amount of memory it asks for can accomodate the maximum heap of the new process.

### Current Behavior

The code uses the minimum heap which leads to overcommitting the physical memory of the machine and starting too many processes in parallel.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

----

We qualified this as a feature request and this would be an impacting change that we need to fully understand before implementing.

**Comment by bantonsson** [comment]
Hi @eskatos, that is an interesting categorization. This _feature_ together with the fact that gradle doesn't handle cgroups memory constraints #17610, makes our build fall over as can be seen [here](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/19304/workflows/0c29afdd-a9b4-4af3-a415-1dfc9b4f9d76/jobs/488879/resources) where the build fails with:
```
org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
	at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:269)
	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:242)
	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:204)
	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:54)
...
```
<img width="1170" alt="Screen Shot 2022-12-07 at 14 12 19" src="https://user-images.githubusercontent.com/805830/206188494-1707ad38-f780-4478-97f8-efce1067d2d4.png">

We've been running patched versions of gradle `7.5.x` and now `7.6.x` with this fixed as well as cgroups support since end of September and they are [solid](https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/19343/workflows/a838f4fb-d7ff-455b-a6b5-3d7db5b003db/jobs/490282/resources)
<img width="1170" alt="Screen Shot 2022-12-07 at 14 17 26" src="https://user-images.githubusercontent.com/805830/206189474-89fb688a-c8f7-4992-b507-da433b34c6f5.png">

**Comment by Thrillpool** [comment]
I am still very keen to resolve this also. My company has been using this for now well over a year and it's such a game changer. It can't be just a small selection of people impacted by this bug, but I can believe it's just a small selection of people who have managed to find the resolution...

Incidentally @bantonsson is your patch substantially different from the one I proposed, perhaps if so you can assist in https://github.com/gradle/gradle/pull/17628 which I have now revived.

**Comment by bantonsson** [comment]
Hey @Thrillpool, we have two patches that we are using:
* The one this ticket is talking about is this https://github.com/bantonsson/gradle/commit/bb78be8141710c97e0d041a415958a3d2e4ae185
* The other one that maps to #17628 is this not as nice as yours, and is here https://github.com/bantonsson/gradle/commit/87a7e851ac383cb4a03919d2a4ee6d8166903500
