### ISSUE TITLE
Add PluginManager.hasPluginProvider/withPluginProvider

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#22991]
### Expected Behavior

```kotlin
val androidPlugin = pluginManager.withPluginProvider("android")
val kotlinJvmPlugin = pluginManager.withPluginProvider("kotlin-jvm")

androidPlugin.zip(kotlinJvmPlugin) { android, kotlinJvm ->
// configure android with Kotlin jvm applied tasks.
}
...
```
### Current Behavior
```kotlin
afterEvaluate {
  val androidJvmOnly = pluginManager.hasPlugin("android") && pluginManager.hasPlugin("kotlin-jvm")
  val androidKotlinMMP = pluginManager.hasPlugin("android") && pluginManager.hasPlugin("kotlin-multiplatform")
  val mmpOnly = pluginManager.hasPlugin("kotlin-multiplatform")

  if (androidJvmOnly) {
    // configure your tasks depending on kotlin/android only
  }  else if (androidKotlinMMP) {
    // configure your tasks depending on kotlin multiplatform and android
  }  else if (mmpOnly) {
   ...
  }
}
```

### Context
Often you need to check the applied plugins when developing custom plugins to configure your tasks. 

A typical example is the Kotlin plugin. To depend on configs provided by the Kotlin plugin you often use `pluginManager.withPlugin("kotlin")`. 
But there is not only one Kotlin plugin, but three: a JVM, a JS, and a multiplatform plugin, each configuring different sourceSets/tasks. So you have to use the `withPlugin` api, because you can only apply one kotlin plugin per project.
```kotlin
withPlugin("kotlin-jvm") { } 
withPlugin("kotlin-js") {}
withPlugin("kotlin-multiplatform") {}
```
The `withPlugin` api lazily performs the block when this plugin is applied. If the plugin was applied before, this config is executed immediately, otherwise, it will execute after applying the specified plugin (or it won't if the plugin is not applied at all).

While these checks are powerful, also depending on the Android plugin makes these checks more complicated, now you have to check the presence of multiple plugins: `android, kotlin-jvm, kotlin-multiplatform, kotlin-js`.
Because it is possible to apply the plugins in any order and you need to configure different tasks/sourceSets for android/kotlin-jvm or android/kotlin-multiplatform. This is only possible by using `hasPlugin` and `afterEvaluate`.

But using `afterEvaluate` has many drawbacks. The "old" `withPlugin` api was lazily executed, `hasPlugin` is not.

So how do you get the old laziness api? 
Fortunately, Gradle already has a powerful lazy api: `Provider`, and there is already a `zip` api to depend on multiple plugins.
This api should also support applying the plugins in any order.

**Comment by jbartok** [comment]
Duplicates:
- #18848
