### ISSUE TITLE
Gradle API JARs are not true MR-JARs

### ISSUE THREAD

**Issue by aalmiray** [gradle/gradle#23002]
### Expected Behavior
The `gradle-api` JARs (re-published by Nokee at https://mvnrepository.com/artifact/dev.gradleplugins/gradle-api) should comply with the rules for MR-JARs https://docs.oracle.com/javase/10/docs/specs/jar/jar.html#multi-release-jar-files

### Current Behavior
JARs are missing a `MANIFEST.MF` file. Without it they can't set the `Multi-Release:` attribute.
Also, there are 3 versioned classes at the wrong location (for the 6.9.2 release):

```
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/
      868  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/module-info.class
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/org/
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/org/junit/
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/org/junit/platform/
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/org/junit/platform/commons/
        0  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/org/junit/platform/commons/util/
     5111  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils$ModuleReferenceScanner.class
    11253  02-01-1980 00:00   org/gradle/internal/impldep/META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils.class
```

They should be at

```
        0  02-01-1980 00:00   META-INF/
        0  02-01-1980 00:00   META-INF/versions/
        0  02-01-1980 00:00   META-INF/versions/9/
      868  02-01-1980 00:00   META-INF/versions/9/module-info.class
        0  02-01-1980 00:00   META-INF/versions/9/org/
        0  02-01-1980 00:00   META-INF/versions/9/org/junit/
        0  02-01-1980 00:00   META-INF/versions/9/org/junit/platform/
        0  02-01-1980 00:00   META-INF/versions/9/org/junit/platform/commons/
        0  02-01-1980 00:00   META-INF/versions/9/org/junit/platform/commons/util/
     5111  02-01-1980 00:00   META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils$ModuleReferenceScanner.class
    11253  02-01-1980 00:00   META-INF/versions/9/org/junit/platform/commons/util/ModuleUtils.class
```

For Gradle 7.6, versioned bouncycastle classes were relocated to `org/gradle/internal/impldep/META-INF/versions/9`, `org/gradle/internal/impldep/META-INF/versions/11`, and `org/gradle/internal/impldep/META-INF/versions/15`. A few classes from Jakarta and Glassfish are also at the wrong location.

### Context
This becomes an issue when using these JARs as direct dependencies (via the nokee publications) when either Maven or Gradle enforcer EnforceBytecodeVersion rule is used, as (supposedly) versioned classes won't be filtered appropriately and trigger build failures as a result.

### Steps to Reproduce 

1. Download https://repo1.maven.org/maven2/dev/gradleplugins/gradle-api/7.6/gradle-api-7.6.jar
2. Unzip and inspect. Note there's no `MANIFEST.MF` file and versioned classes are at the wrong location.

### Your Environment

Build scan URL:

**Comment by aalmiray** [comment]
As I understand those JARs are taken directly from what the `gradleApi()` creates in which case Gradle would be at fault no matter if Gradle itself does not publish said JARs.

**Comment by eskatos** [comment]
@aalmiray if we wanted to publish those jars we would make them consumable, but it's not the case yet

**Comment by aalmiray** [comment]
I understand Gradle did not wish for these JARs to be consumable outside of the Gradle Build Tool itself. Yet, here we are. 

I have no clue who decided how to build said JARs but the fact remain is those JARs do not follow the MR-JAR guidelines. I understand why Gradle Core could not use the Gradle shadow plugin to create proper fatjar/uberjar/shaded MR-JARs. OTOH just cobbling together all classes with a simple name relocation technique falls short of doing things right. 

Nokee (or someone else outside of Gradle for that matter) could repackage those JARs but then the chain of ownership and authenticity would be broken, wouldn’t it? And that would cause even bigger problems with trust, ownership, security, and more. 

So why don’t nip it at the bud and build proper MR-JARs from the get go? What’s the hold up?

**Comment by lacasseio** [comment]
In general, there should only be a `compileOnly` (or `compileOnlyApi`) dependency on the Gradle API given they are supposed to execute within Gradle environment (where the API is provided). The outlined issue is not Nokee's problem; it's how the `gradleApi()` or `gradleTestKit()` generates the JARs. If that poses any issue, you should be able to see the same issue if you use the generated Gradle JAR with the appropriate Java version. **If you can confirm this if true, that would be great.**

>I have no clue who decided how to build said JARs but the fact remain is those JARs do not follow the MR-JAR guidelines. I understand why Gradle Core could not use the Gradle shadow plugin to create proper fatjar/uberjar/shaded MR-JARs. OTOH just cobbling together all classes with a simple name relocation technique falls short of doing things right.

If I remember correctly, the Gradle shadow technique pre-dates the shadow plugin. It worked back then and today, so why change it? Nokee offers the generated Gradle API JARs as if they were external dependencies. The [process is public and welcomes](https://github.com/gradle-plugins/gradle-api) any improvements. I think what would be beneficial to the conversation is having a concrete example(s) that demonstrate the process poses issues. Then we can look at which side should be fixed (producer or consumer).

> Nokee (or someone else outside of Gradle for that matter) could repackage those JARs but then the chain of ownership and authenticity would be broken, wouldn’t it? And that would cause even bigger problems with trust, ownership, security, and more.

The security concern is valid for everything not hosted on gradle.org, meaning SDK manager, Homebrew, etc. At Nokee, we use transparency. The [process is public](https://github.com/gradle-plugins/gradle-api), and everyone is welcome to verify that the JARs produced match the process. If they don't please raise an issue so we can address it.
