### ISSUE TITLE
Build script cache causes incorrect behavior

### ISSUE THREAD

**Issue by mhsmith** [gradle/gradle#2301]
Gradle 3.3 on Windows 7.

I'm working on a test harness which runs Gradle repeatedly with various different build scripts. I've observed that if the test harness changes the build script file immediately after a build, and then runs the build again, Gradle will run the old build script, which no longer exists in the filesystem. Repeated manual runs will continue to run the old script until the script is changed once more. Using `--no-daemon` does not resolve the situation, but `--no-daemon --recompile-scripts` does.

I would speculate that the daemon is caching the compiled build script after returning control to the client, but it's using the state of the build script at *that* moment to construct the cache key, rather than the state when the script was actually compiled.

I apologize that I have no time to provide a minimal test case, but I'm sure those who understand this area will know whether this explanation is plausible.

**Comment by oehme** [comment]
Build scripts are cached synchronously as they are compiled, so the race condition described above does not exist. There must be something else going on. A reproducible example would be the easiest way to move forward with this issue.

**Comment by mhsmith** [comment]
OK, I'll try to provide one.

**Comment by mhsmith** [comment]
It seems to have something to do with the timestamps. The test harness was updating the build script by copying from another location, and both of the source scripts had the same timestamp to within a few hundredths of a second (they were saved at the same time by the same editor). If the source files have different timestamps, or the copy process doesn't preserve timestamps, the issue disappears.

Here's a hopefully reproducible example:
```
smith@xanadu:~/tmp/repro$ ll -R
.:
total 5
drwxr-xr-x 1 smith None   0 Jun 14 19:47 base
drwxr-xr-x 1 smith None   0 Jun  8 20:09 one
drwxr-xr-x 1 smith None   0 Jun 14 19:55 project
-rwxr-xr-x 1 smith None 388 Jun 14 19:54 test.py
drwxr-xr-x 1 smith None   0 Jun  8 20:09 two

./base:
total 17
drwxr-xr-x 1 smith None    0 Jun 14 19:50 app
-rw-r--r-- 1 smith None    0 Jun 14 19:49 build.gradle
drwxr-xr-x 1 smith None    0 Jun  1 16:08 gradle
-rw-r--r-- 1 smith None  730 Apr  4 12:32 gradle.properties
-rwxr-xr-x 1 smith None 4971 Apr  4 12:32 gradlew
-rw-r--r-- 1 smith None 2314 Apr  4 12:32 gradlew.bat
-rw-r--r-- 1 smith None   15 Apr  4 16:46 settings.gradle

./base/app:
total 1
-rw-r--r-- 1 smith None 428 Jun 14 15:12 build.gradle

./base/gradle:
total 0
drwxr-xr-x 1 smith None 0 Jun 14 17:03 wrapper

./base/gradle/wrapper:
total 57
-rw-r--r-- 1 smith None 53636 Apr  4 12:32 gradle-wrapper.jar
-rw-r--r-- 1 smith None   230 Jun 14 17:09 gradle-wrapper.properties

./one:
total 0
drwxr-xr-x 1 smith None 0 Jun 14 19:46 app

./one/app:
total 1
-rw-r--r-- 1 smith None 14 Jun 14 15:12 build.gradle

./project:
total 0

./two:
total 0
drwxr-xr-x 1 smith None 0 Jun 14 19:46 app

./two/app:
total 1
-rw-r--r-- 1 smith None 14 Jun 14 15:12 build.gradle
```

`test.py`
```
#!/usr/bin/env python

from distutils.dir_util import copy_tree
import os
import subprocess

def run():
    os.chdir("project")
    subprocess.check_call(["gradlew.bat","--console", "plain", ":app:build"])
    os.chdir("..")

copy_tree("base", "project")
copy_tree("one", "project")
run()
copy_tree("two", "project", preserve_times=True)  # Change to False and the issue disappears
run()
```

`one/app/build.gradle`
```
println "one"
```

`two/app/build.gradle`
```
println "two"
```

Output:
```
smith@xanadu:~/tmp/repro$ ./test.py
one
:app:buildEnvironment
-----------------------------------------------------
Project :app
------------------------------------------------------------

classpath
No dependencies

BUILD SUCCESSFUL

Total time: 1.72 secs
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
one
:app:buildEnvironment

------------------------------------------------------------
Project :app
------------------------------------------------------------

classpath
No dependencies

BUILD SUCCESSFUL

Total time: 1.717 secs
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
```

Output after changing timestamps to be different: 
```
smith@xanadu:~/tmp/repro$ touch two/app/build.gradle
smith@xanadu:~/tmp/repro$ ./test.py
one
:app:buildEnvironment

------------------------------------------------------------
Project :app
------------------------------------------------------------

classpath
No dependencies

BUILD SUCCESSFUL

Total time: 1.705 secs
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
two
:app:buildEnvironment

------------------------------------------------------------
Project :app
------------------------------------------------------------

classpath
No dependencies

BUILD SUCCESSFUL

Total time: 1.724 secs
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
```

**Comment by big-guy** [comment]
@oehme I think the issue here is that we use the timestamp+file length to check if the build script changed.  So if the build scripts have the same timestamp and the same file length (`println "one"` and `println "two"` are the same length), we think it hasn't changed.

**Comment by oehme** [comment]
That's right, this is consistent with how all our other caching works. If a file has the same length and timestamp, we don't hash it again. This is such an important performance optimization that we accept the fact that we fail to detect this corner case.

@mhsmith I think the simplest workaround in your setup would be to touch the files before calling Gradle.
