### ISSUE TITLE
library "libc++_shared.so" not found in Android Emulator during gradle android tests

### ISSUE THREAD

**Issue by BigSquirrel2000** [gradle/gradle#23023]
During gradle android tests with android emulator, I load rust native library with java System.loadLibrary. Loading fails because dlopen can't find "libc++_shared.so" in android emulator. According to https://developer.android.com/ndk/guides/cpp-support, gradle should handle this, but supposedly it isn't.

Related stack issue: https://stackoverflow.com/questions/72723278/libc-shared-is-present-in-apk-but-not-found-when-loading-libraries-during-exec

### Expected Behavior

Java should load rust native library and dlopen should find libc++_shared.so in android emulator.

libc++_shared.so should be accessible in android emulator during gradle android tests

### Current Behavior
During gradle android tests in android emulator, following error occurs:
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found: needed by /lib/x86_64/libtokenizers.so in namespace classloader-namespace at java.lang.Runtime.loadLibrary0(Runtime.java:1087)`

### Context

I couldn't run rust native library in android emulator

### Your Environment
gradle version: 6.7.1
gradle android plugin version: 4.2.1 (compatible according to: https://developer.android.com/studio/releases/gradle-plugin)
android {
    defaultConfig {
        minSdkVersion 26
        compileSdkVersion 30
        targetSdkVersion 30
}

Android emulator:
sdkmanager --install "system-images;android-30;google_apis;x86_64"

**Comment by BigSquirrel2000** [comment]
Seems like problem might lie somewhere between android emulator and gradle:
https://github.com/KeepSafe/ReLinker/issues/77

**Comment by BigSquirrel2000** [comment]
Problem also occurs on real device with android (the same error), so it seems that it is not related to android emulator

**Comment by BigSquirrel2000** [comment]
My current quickfix solution is that I take libc++_share.so from ndk bundle, e.g.
ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so

and copy it to jniLibs directory specified in gradle.
Then I explicity load libc++_shared.so in java, with System.loadLibrary("c++_shared")

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug

**Comment by balazsbanto** [comment]
Hi everybody,

I also run into this issue: loading a simple *.aar file which expects shared C++ lib (libc++_shared.so). Are we sure that this is a  Android Gradle Plugin? @BigSquirrel2000 did you maybe created a ticket for this on android issue tracker?

**Comment by BigSquirrel2000** [comment]
Hi, yes I made issue: https://issuetracker.google.com/issues/262255235
