### ISSUE TITLE
change title of upgrade doc for "7.x to latest" to "7.x to 8.0"

### ISSUE THREAD

**Issue by reinsch82** [gradle/gradle#23021]
the name of the [7.x upgrade page](https://docs.gradle.org/current/userguide/upgrading_version_7.html) should renamed to "7.x to 8.0"
the menu entry on the left needs to be updated too, around [here](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/main/resources/header.html#L102)

**Comment by Rajakavitha1** [comment]
This has been addressed in https://github.com/gradle/gradle/pull/22938/. Just noting it here.
