### ISSUE TITLE
Option to suppress 'dependencies-without-versions' validation error in GenerateModuleMetadata task

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#23030]
### Expected Behavior

The additional validation performed by the `GenerateModuleMetadata` when generating `.module` metadata is great for most cases to avoid broken setups. However, there are use cases where the validation is too strict.

The task already supports the suppression of validation errors:

````
@Input
public SetProperty<String> getSuppressedValidationErrors()
````

However, the error `dependencies and/or constraints without a version` cannot be suppressed by this method. My suggestion is to allow suppression of this kind of error.

### Current Behavior

We would like to do something like this which is currently not possible:

````
tasks.withType(GenerateModuleMetadata).configureEach {
    suppressedValidationErrors.add('dependencies-without-versions')
}
````

Instead we get:

```
> Invalid publication 'mypub':
    - Publication only contains dependencies and/or constraints without a version. You need to add minimal version information, publish resolved versions (https://docs.gradle.org/7.4.2/userguide/publishing_maven.html#publishing_maven:resolved_dependencies) or reference a platform (https://docs.gradle.org/7.4.2/userguide/platforms.html)
```

### Context

In our setup, we would like to publish the metadata without versions, because all versions are managed by a _platform_. When one of our components is used, we expect the consumer to also add a platform dependency, with a platform version, in addition. For different reasons, we do not want to publish a dependency to the platform in the metadata of the components. One reason is that there are many platform versions and we want to avoid certain conflicts between the platform versions. We always want a consumer to explicitly select **one platform version** that then provides versions for **all** components and their dependencies.

 👋  **I can contribute a PR for this change.**

**Comment by jjohannes** [comment]
I ran into this issue now two more times. It's always in a situation where libraries are published in a "closed context" (i.e. company artifactory) where we know, and expect, **all** consumers to explicitly choose **all** versions through a platform. 

From my point of view, the use case is valid. Would you agree and if I provide a PR with an implementation, would that get accepted?

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented.

****

If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

***

Yeah, this is something that would be appreciated. Thanks!

**Comment by jjohannes** [comment]
It's Friday afternoon.... so here it is: #26324
