### ISSUE TITLE
Allow configuration of Eclipse build directory

### ISSUE THREAD

**Issue by fbricon** [gradle/gradle#23032]
Currently the [eclipse.classpath.defaultOutputDir](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html#org.gradle.plugins.ide.eclipse.model.EclipseClasspath:defaultOutputDir) (The default output directory where Eclipse puts compiled classes.) is pretty useless. Nothing outputs anything there by default and it's ignored by all sourcesets. eg.:
```
eclipse {
  classpath {
    defaultOutputDir = file('build-eclipse')
  }
}
```
will generate the following, when imported in Eclipse Buildship:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest,native-test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest,native-test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-17/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="build-eclipse"/>
</classpath>
```
Each sourceset will, no matter what, generate something under the `bin/` directory.
What is actually needed is a  defaultBuildDir, that would allow each sourceset to generate an output directory composed of `${defaultBuildDir}/${configuration}`

And no, rewriting .classpath files after the fact is not a serious solution.

### Context
VS Code Java uses BuildShip under the hood. Its users have been complaining about those bin/ directories being created, classes being added to existing bin/ directories with other legit content. See
- https://github.com/redhat-developer/vscode-java/issues/634
- https://github.com/redhat-developer/vscode-java/issues/1615
- https://github.com/redhat-developer/vscode-java/issues/2344

See related Buildship request
- https://github.com/eclipse/buildship/issues/1131

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and prioritized by them.
