### ISSUE TITLE
Automatically Cleanup old files in GRADLE_HOME/caches ?

### ISSUE THREAD

**Issue by kageiit** [gradle/gradle#2304]
The gradle caches directory can get pretty massive especially if someone is working on a codebase over a period of time with gradle versions being upgraded.

I deleted the caches of all the 2.x and 3.x versions of gradle and it is woefully slow to cleanup the trash on mac OSX. There are about 5 million small files that needed to be cleared out. 5 Million!

<img width="398" alt="screen shot 2017-06-14 at 7 50 55 pm" src="https://user-images.githubusercontent.com/291148/27163214-cf81e5a4-513a-11e7-9b0a-f7c77764aeb0.png">

Can some sort of cleanup mechanism/option be added to the gradle daemon that can cleanup these caches and prevent them from accumulating over a long period of time? If it is just metadata, can it be stored in some sort of database rather than raw files? Even though the files are tiny, they still occupy space of the smallest block the disk can allocate and waste a lot of space seemingly

**Comment by kageiit** [comment]
Its pretty funny. It is taking about 10 minutes to delete a million files

<img width="397" alt="screen shot 2017-06-14 at 8 00 36 pm" src="https://user-images.githubusercontent.com/291148/27163404-f765f4d8-513b-11e7-8c8f-79238e08799a.png">

It is going to take about an hour to delete all of them. Wow :)

**Comment by kageiit** [comment]
Any updates on this?

**Comment by kageiit** [comment]
I just ran a cleanup script on "~/.gradle" to delete files not accessed recently

```
find ~/.gradle -type f -atime +30 -delete
find ~/.gradle -type d -mindepth 1 -empty -delete
```

Some disk space usage metrics
**Before:**
```
 82G	~/.gradle/caches
 99G	~/.gradle
```

**After:**
```
 15G	~/.gradle/caches
 17G	~/.gradle
```

Given that gradle now has functionality to cleanup the build cache already - https://docs.gradle.org/nightly/release-notes.html#local-build-cache-directory-cleanup-is-now-time-based

```
buildCache { local { removeUnusedEntriesAfterDays = 30 } }
```

Can we do something similar for the `GRADLE_USER_HOME` as well?

There are significant disk space savings potentially.

cc @hansd

**Comment by oehme** [comment]
Duplicate of #1085, please add your 👍 there :)

**Comment by iceyang1989** [comment]
thks.

**Comment by Hamid313-coder** [comment]
thanks

**Comment by opatry** [comment]
@kageiit ⚠️ you delete `~/.gradle/gradle.properties` this way 😱
You should do that in `~/.gradle/caches`.

**Comment by bysiber** [comment]
Even though this is closed with Gradle 8's auto-cleanup, worth noting that the automatic cleanup only applies to the Gradle version currently running. If you have projects pinned to different Gradle versions via the wrapper, the older Gradle caches still accumulate without cleanup.

The situation in 2025:

```bash
# Check total Gradle cache size
du -sh ~/.gradle/caches/
du -sh ~/.gradle/wrapper/dists/

# Check how many Gradle versions are cached
ls ~/.gradle/caches/ | grep -c "^[0-9]"
ls ~/.gradle/wrapper/dists/ | wc -l

# Check daemon log files (often forgotten)
du -sh ~/.gradle/daemon/
```

On an active Android/JVM dev machine, having 3-5 Gradle versions cached is common, each with its own set of caches. The total easily reaches 10-20GB.

For macOS developers: [ClearDisk](https://github.com/bysiber/cleardisk) monitors ~/.gradle alongside other dev caches (Xcode DerivedData, node_modules, Docker, Maven ~/.m2, Rust target/, Go modules, Homebrew). It's free, open-source, and sits in the menu bar. Detailed guide here: [Gradle Cache Cleanup Guide](https://bysiber.github.io/cleardisk/blog/gradle-cache-cleanup-mac.html)
