### ISSUE TITLE
Deprecate using non-String keys for nested map properties

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#23045]
When a task or transform parameters object declares a `@Nested Map<X, Y>` property, we resolve each key in the map to a sub-property. To get the name for each key, we currently call `X.toString()`, and this is problematic. It can lead to property name collisions, and the names we get this way might not be human well readable (e.g. when falling back to `Object.toString()`).

We should emit a deprecation warning for `@Nested Map<X, Y>` properties where `X != String`.

---
cc: @gradle/execution

**Comment by wolfs** [comment]
There may be some corner cases when the keys of the maps are `GString`s in Groovy. Because of type erasure Groovy probably won't convert them to `String`s when you add them to the map. Though I am not sure this is a problem in practice.
