### ISSUE TITLE
Auto-provisioning/auto-detection of IBM Semeru toolchains is broken with Gradle 7.6

### ISSUE THREAD

**Issue by simon-spinner** [gradle/gradle#23053]
### Expected Behavior
Build works with gradle 7.5.1 and jdks are auto provisioned as declared in build.gradle:

```
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
        vendor = JvmVendorSpec.IBM_SEMERU
        implementation = JvmImplementation.J9
    }
}
```

### Current Behavior

Upgrading to gradle 7.6 the build now fails with:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':buildSrc:compileGroovy'.
> Could not resolve all dependencies for configuration ':buildSrc:compileClasspath'.
   > Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
      > Unable to download toolchain matching the requirements ({languageVersion=11, vendor=IBM_SEMERU, implementation=J9}) from 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk'.
         > Toolchain provisioned from 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk' doesn't satisfy the specification: {languageVersion=11, vendor=IBM_SEMERU, implementation=J9}.
```

### Context

Auto-detection/auto-provisioning of Gradle toolchains is broken with gradle 7.6

### Your Environment

Detected toolchains:

```
❯ ./gradlew -q javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Enabled

 + IBM JDK 11.0.17+8
     | Location:           ~/.gradle/jdks/ibm-semeru-open-jdk_x64_linux_11/jdk-11.0.17+8
     | Language Version:   11
     | Vendor:             IBM
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Auto-provisioned by Gradle

 + IBM JDK 11.0.15+10
     | Location:           ~/.gradle/jdks/ibm_semeru-11-x64-openj9-linux/jdk-11.0.15+10
     | Language Version:   11
     | Vendor:             IBM
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Auto-provisioned by Gradle
```

**Comment by AdamBrousseau** [comment]
@jbartok could you please provide clarity on your previous statement? I don't quite understand where you/Gradle are getting `Vendor: IBM Semeru Runtimes` from. Perhaps it is a value set by SDKMAN?
When we released 11.0.15 this year (2022) we corrected the `java.vendor` property back to `IBM Corporation`. I don't believe we have any system properties that are set to `IBM Semeru Runtimes`. I could be missing something.

Thanks,
Adam

**Comment by EdGue42** [comment]
@jbartok 

I assume this means that one of the next nightly builds could be used for verifying your changes?

**Comment by jbartok** [comment]
> @jbartok
> 
> I assume this means that one of the next nightly builds could be used for verifying your changes?

Yes, [https://gradle.org/release-nightly/ ](https://gradle.org/release-nightly/ )should contain the fix (but this is a nightly for the upcoming 8.0 version). 
`7.6.1` should contain the fix too, but I don't see any nightlies available for that atm. Let me know if the above mentioned nightly is not ok for you to test with.

**Comment by EdGue42** [comment]
For reasons that I really don't get ... I can't reproduce the problem for me on MacOs.
I downloaded Semeru 11.0.17+8, and when I run our build with gradle 7.6, there

**Comment by EdGue42** [comment]
I changed my build setup to use jdk-11.0.17+8 and then pointed to gradle-8.0-20221216001954:

> JAVA_HOME=/Users/xxxx/java/ibm/jdk-11.0.17+8/Contents/Home ./gradlew -q javaToolchain
> 
>  + Options
>      | Auto-detection:     Enabled
>      | Auto-download:      Enabled
> 
>  + IBM JDK 11.0.17+8
>      | Location:           /Users/guenthne/java/ibm/jdk-11.0.17+8/Contents/Home
>      | Language Version:   11
>      | Vendor:             IBM
>      | Architecture:       x86_64
>      | Is JDK:             true
>      | Detected by:        Current JVM

So, that part is working.
