### ISSUE TITLE
Easier debugging of CompileTransaction path selection in incremental task execution

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#23066]
### Expected Behavior
It would be nice if the filepaths selected by [CompileTransaction](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransaction.java) could be made easier to understand, perhaps one of:

A) making these selections consistent regardless of whether the task previously succeeded
B) logging (at debug() level) what the selected paths were and why they were selected (because of running in incremental mode, I think)
C) perhaps when a task fails it could mention to the user whether it was running in incremental mode or not

### Current Behavior
Currently, it seems that CompileTransaction can be used by incremental task executions and unused in clean task executions, and when it is used, it can change the filepaths of some compilation tasks in ways that are confusing

### Context

In https://issuetracker.google.com/issues/261866061 we discovered in AndroidX that our builds were intermittently failing with an error like:

```
> Task :camera:camera-core:runErrorProne
$OUT_DIR/androidx/camera/camera-core/build/tmp/runErrorProne/compileTransaction/compile-output/androidx/camera/core/imagecapture/AutoValue_JpegBytes2Disk_In.java:45: error: [ObjectToString] ImageCapture.OutputFileOptions is final and does not override Object.toString, so converting it to a string will print its identity (e.g. `OutputFileOptions@4488aabb`) instead of useful information.
         + "outputFileOptions=" + outputFileOptions
    (see https://errorprone.info/bugpattern/ObjectToString)
 ```
 
We found that this was because we had configured ErrorProne to [exclude paths containing "build/generated"](https://android.googlesource.com/platform/frameworks/support/+/a0e5dacc6f344d31596d98b7a45bf6747c04840f/buildSrc/private/src/main/kotlin/androidx/build/ErrorProneConfiguration.kt#143) but we hadn't configured ErrorProne to exclude paths containing "compileTransaction/compile-output"

Then, because Gradle appeared to be putting these generated source files [at a different path](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/transaction/CompileTransaction.java#L75) for incremental builds where the task had executed in a previous build, sometimes this exclusion wouldn't apply and we would get inconsistent results.

Thanks

**Comment by asodja** [comment]
Hey Jeff, this is due to changes to incremental compilation in 7.6. We change compile output to `build/tmp/<task-name>/compileTransaction` so we can restore outputs back in case of a failure. And as you notice this happens only on incremental build (so never on first build, but on second/third/forth if they are incremental).

I would like that users wouldn't need to know about these special tmp paths, but maybe there is no other way. I will get back to you.

**Comment by asodja** [comment]
@mathjeff can you show me where you setup `build/generated` in your build?

**Comment by asodja** [comment]
So after inspecting this some more, we might solve this issue, but we would need to keep original folder name. So I guess if we would output to `build/tmp/<task-name>/compileTransaction/build/generated` everything would work fine.

**Comment by mathjeff** [comment]
Good question. After double-checking, it looks like the generated java files in a clean build actually go into "build/errorProne" rather than the "build/generated" that I indicated above. It appears that we configure this [here](https://android.googlesource.com/platform/frameworks/support/+/a0e5dacc6f344d31596d98b7a45bf6747c04840f/buildSrc/private/src/main/kotlin/androidx/build/ErrorProneConfiguration.kt#304). The build/generated directory seems to actually be coming from `compileDebugJavaWithJavac`.

I'm not completely sure where the "/generated" path comes from. We have files generated at
```
$OUT_DIR/androidx/camera/camera-core/build/generated/ap_generated_sources/debug/out
```
and I notice `ap_generated_sources` [mentioned in the Android Gradle Plugin](https://android.googlesource.com/platform/tools/base/+/3b4bfa4e1b39f2ba6b4748762ebe6b20d2a4bcbd/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/JavaCompile.kt#88) and `generated` [mentioned in the Java plugin](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#N292B3)

We do configure our ErrorProne task to ignore build/generated and build/errorprone [here](https://android.googlesource.com/platform/frameworks/support/+/a0e5dacc6f344d31596d98b7a45bf6747c04840f/buildSrc/private/src/main/kotlin/androidx/build/ErrorProneConfiguration.kt#143)

**Comment by asodja** [comment]
We decided we will not implement special paths for now, since this could brought up other problems.

What will we do for 8.0 and 7.6.1: 
- we will document a behaviour
- we will allow users to have old behaviour with `option.incrementalAfterFailure = false`, although this will disable incremental compilation after failure optimization done in 7.6
- in future will will try to get rid of that behaviour, but we need to improve local caching, to better fit such usages

**Comment by asodja** [comment]
Documentation was updated in https://github.com/gradle/gradle/pull/23251. We might get rid of a behaviour maybe already in 8.1 (https://github.com/gradle/gradle/pull/23226), but we still need to verify the solution.

**Comment by asodja** [comment]
https://github.com/gradle/gradle/pull/23226 is merged to master. With that Gradle 8.1 won't change the output directories anymore and adding `compileTransaction/compile-output` for ErrorProne won't be needed anymore.
