### ISSUE TITLE
Docs: Build Lifecycle starts halfway through a point

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23074]
The very first sentence of [Build Lifecycle](https://docs.gradle.org/current/userguide/build_lifecycle.html) starts with:

> We said earlier that the core of Gradle is a language for dependency based programming. In Gradle terms this means that you can define tasks and dependencies between tasks. 

This is quite strange to read. If I land directly on this page from a link or Google, then I don't know what was said earlier. 

Suggestions:

* Directly link to the part in the docs that explains what 'dependency based programming' is
   ```markdown
   [We said earlier](https://docs.gradle.org/current/link-to-relevant-docs-page.html] that...
   ```
* Rephrase to read more naturally
   ```markdown
   Gradle is a language for dependency based programming. In Gradle terms this means that you can define tasks and dependencies between tasks. 
   ```

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

---
If you're interested we might take a contribution to it but maybe should mention the dependency based programming concept.
