### ISSUE TITLE
Gradle Init w/ incubating features does not place conventions plugins into build-logic when migrating maven projects

### ISSUE THREAD

**Issue by madorb** [gradle/gradle#23084]
Despite the [release notes](https://docs.gradle.org/current/release-notes.html) which state 
> When generating builds with the init task and opting in to incubating features, Gradle now places convention plugins under the build-logic directory instead of in buildSrc.

When I attempt to generate a gradle build from an existing maven multi-module project, opting into incubating features, gradle still generates the conventions plugins into `buildSrc` and not `build-logic`

Unsure if this is expected behavior or not, but if so, it would be good to update the release notes for the callout.

### Expected Behavior
Expect the generated conventions plugin to be placed into `build-logic`

### Current Behavior
The conventions plugin is placed in `buildSrc`

### Your Environment
```
❯ gradle --version
executing gradlew instead of gradle

------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Amazon.com Inc. 17.0.5+8-LTS)
OS:           Mac OS X 12.6 aarch64
```

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.

---

The reproducer is a simple Maven project created with the Java library archetype, and then migrating that to Gradle.

**Comment by xaviarias** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by Chaoba** [comment]
@xaviarias Could you please take a look at the ☝️ PR, thank you.
