### ISSUE TITLE
Gradle 4.0 task configuration closures types are over-restrictive, cause compilation errors with @CompileStatic

### ISSUE THREAD

**Issue by jsotuyod** [gradle/gradle#2309]
Up to gradle 3.5, one could write a code such as:

```groovy
project.task('myCopyTask', type:Copy) { Copy it ->
  from file('in.txt')
  into file('out.txt')
}
```

Since Gradle 4.0 if using Groovy's `@CompileStatic` this fails at compile time with:

> Expected parameter of type org.gradle.api.Task but got org.gradle.api.tasks.Copy.
> [Static type checking] - Cannot find matching method org.gradle.api.Task#from(java.io.File). Please check if the declared type is right and if the method exists
> [Static type checking] - Cannot find matching method org.gradle.api.Task#into(java.io.File). Please check if the declared type is right and if the method exists

I double checked the release notes and I found no reference to this being an intended API change (nor have I seen proper warnings).

### Expected Behavior
I expect the old code to still work, and the argument passed to the configuration closure to be the type of the task being configured.

### Current behavior
Compile errors for methods not found / wrong parameter types.

### Steps to Reproduce (for bugs)

Run `gradle myCopyTask`

```groovy
@groovy.transform.CompileStatic
def setup(Project project) {
  project.task('myCopyTask', type:Copy) { Copy it ->
    from file('in.txt')
    into file('out.txt')
  }
}

setup(project)
```

### Workaround

Disable `@CompileStatic` or rewrite as:

```groovy
@groovy.transform.CompileStatic
def setup(Project project) {
  project.task('myCopyTask', type:Copy) {
    def copyTask = it as Copy
    copyTask.from file('in.txt')
    copyTask.into file('out.txt')
  }
}

setup(project)
```

### Context
Some plugins can't be compiled against Gradle 4.0. Plugins' code need to be updated to target 4.0 and manually cast the argument to a local var.

**Comment by jsotuyod** [comment]
So, the problem stems from the fact Gradle 4.0 added a `@DelegatesTo(Task.class, strategy = Closure.DELEGATE_FIRST) @ClosureParams(ReturnType.class)` annotation to these methods (done on [this commit](https://github.com/gradle/gradle/commit/5bff30b17d9416d8b3f683b2b4f18208536c2889)).

The thing is, those checks are actually over-restrictive. You are not actually passing `Task` to the closure but a `<T extends Task>`, which is given by the `type` passed or defaults to `DefaultTask`. The change now forces us to either drop all static compilation on our end, or take it as a Task, and manually cast it to the proper type within the `Closure`.

**Comment by melix** [comment]
Your analysis is correct, @jsotuyod . Another workaround is to write it this way:

```
@groovy.transform.CompileStatic
def setup(Project project) {
  project.tasks.create('myCopyTask', Copy) {
    it.from file('in.txt')
    it.into file('out.txt')
  }
}
```

**Comment by jsotuyod** [comment]
@melix are you confirming this is a bug and unintentionally breaking valid code? Otherwise I see no reason to assume `project.tasks.create` won't be annotated the same way on a future gradle release...

I'd really rather wait for a fixed gradle release than update all my plugins.

**Comment by melix** [comment]
Yes, I confirm it should be fixed. Either by reverting, or by implementing proper compiler hints. I'm just not sure what solution is best today.

**Comment by bmuschko** [comment]
@melix What's the status on this? Did you decide to revert the change?

**Comment by jsotuyod** [comment]
Any news on this? 4.1 is out and still no feedback, I'd really appreciate being able to build my plugins against the latest gradle version without having to rework my code.

**Comment by oehme** [comment]
I'm scheduling this for 4.2. The simplest thing would be to revert, but I'll let @melix decide.

**Comment by melix** [comment]
+1 for reverting, I thought we had done it already.

**Comment by oehme** [comment]
@melix could you tackle that this week?

**Comment by melix** [comment]
yes, I will

**Comment by melix** [comment]
Pull request: https://github.com/gradle/gradle/pull/2718
