### ISSUE TITLE
in android studio java

### ISSUE THREAD

**Issue by NoObMaStr** [gradle/gradle#23104]
![image](https://user-images.githubusercontent.com/73227567/206903836-b8f9b4a9-c12d-4203-b1ea-db5fcb9eca8f.png)
![image](https://user-images.githubusercontent.com/73227567/206903866-32f12eec-1b07-46a5-b4cd-08289d12e7c5.png)

help me to fix it

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
