### ISSUE TITLE
New modeling for inter JVM language dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#2311]
In 4.0, we [split the JVM classes](https://docs.gradle.org/4.0/release-notes.html#multiple-class-directories-for-a-single-source-set) up so that each collection of sources would have its own output directory (this is usually divided by JVM language).

By default, Groovy and Scala compilation depend on the output of Java compilation. But there's no built-in way to describe the relationships between Groovy and Scala, to reverse the relationship between Groovy/Scala and Java or to add your own relationships (e.g., for Kotlin or other languages).

**Comment by oehme** [comment]
This strong modeling should also keep track of which task produces which classes dir. This is necessary to enable the java-library plugin to automatically pick up classes of new languages (e.g. Kotlin). Currently it only works with Java out of the box and other languages need additional configuration.

**Comment by oehme** [comment]
Also, the output dir should not be on `SourceDirectorySet`, but on a new concept. There are composite `SourceDirectorySet`s for which an output directory doesn't make sense. That interface was not meant to have a deeper meaning than "A bunch of source directories".

**Comment by piotrklibert** [comment]
Working on a quite peculiar, Groovy+Scala joint project set up with Gradle, I've run into this issue. I'm new to both JVM and Gradle, and this issue took me hours to resolve. It was hard to find the workaround given in https://github.com/gradle/gradle/issues/2312 - no matter how I searched, there was no mention of the problem in the docs for Groovy or Scala plugins (nor in the docs in general, but maybe I wasn't searching hard enough). It was kind of frustrating to learn that the issue has been known for two years already with no change in its status. Coming from outside the ecosystem it made me question if Gradle is actively maintained? At the very least, the issue should be acknowledged in the docs, and the workaround should be mentioned there.

I hope my comment will bring some attention to the issue - I'm not expecting it to be fixed, as it looks like a deeper issue, but it would be great to at least start the conversation about it again. I'd also like to see the workaround put into the docs - it could save people like me a lot of time and frustration.
