### ISSUE TITLE
Ant closures are broken with Gradle 7.6

### ISSUE THREAD

**Issue by demonti** [gradle/gradle#23111]
I have various Gradle build files that use the "ant" task in conjunction with a closure which contains a set of ant tasks. Running the build files with Gradle 7.6, the build fails. Using the previous version 7.5.1, the build succeeds.

Here is a simple test that fails:

```
task test {
  doLast
  {
    ant
    {
      echo (message: 'hello world!')
    }
  }
}
```
### Expected Behavior

expected the output of 
```
[ant:echo] hello world!
```
### Current Behavior

```
Execution failed for task ':test'.
> Problem: failed to create task or type call
  Cause: The name is undefined.
  Action: Check the spelling.
  Action: Check that any custom tasks/types have been declared.
  Action: Check that any <presetdef>/<macrodef> declarations have taken place.
```
### Context
The given test case works with 7.5.1, but not with 7.6.

As I was unsure whether it is a bug or intended behavior, I asked in the Gradle forum about it (see [here](https://discuss.gradle.org/t/ant-closures-no-longer-working-in-7-6/44440/1)). I was told that this is likely not intended and may relate to the [pull request 21242](https://github.com/gradle/gradle/pull/21242).

### Steps to Reproduce 
place the example in a "build.gradle" file, add an empty "settings.gradle". Run "gradle test" with the respective versions of Gradle.

### Your Environment
Linux, Java 8 (Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode))

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.
