### ISSUE TITLE
Missing 'archiveName' attribute in eclipse wtp

### ISSUE THREAD

**Issue by Tiller** [gradle/gradle#23129]
### Expected Behavior
When generating the `.settings/org.eclipse.wst.common.component` file with the eclipse plugin, project dependencies should include an attribute named 'archiveName' and generated war from Eclipse should include the dependency.

```xml
<dependent-module archiveName="lib.jar" deploy-path="/WEB-INF/lib" handle="module:/resource/lib/lib">
    <dependency-type>uses</dependency-type>
</dependent-module>
```

```bash
$ unzip -l out.war | grep "lib.jar"
1308484  2022-12-13 10:36   WEB-INF/lib/lib.jar
```

### Current Behavior
The 'archiveName' attribute is not generated leading Eclipse to print a warning and the generated war to miss the library.

```xml
<dependent-module deploy-path="/WEB-INF/lib" handle="module:/resource/lib/lib">
    <dependency-type>uses</dependency-type>
</dependent-module>
```

```bash
$ unzip -l out.war | grep "lib.jar"
<no result>
```

![image](https://user-images.githubusercontent.com/831119/207284204-47f18d54-51e8-446a-83ce-640ce3cb71b2.png)

### Context
Trying to generate a WAR with eclipse to deploy in JBoss

### Steps to Reproduce 
Run `./gradlew eclipse` on https://github.com/Tiller/gradle-eclipse-issue. Import project, and check 'Deployment Assembly' or export war from Eclipse.

### Your Environment
Gradle 7.6, Linux, Java 11

**Comment by xaviarias** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by Chaoba** [comment]
@xaviarias I have tried to fix this issue in this [PR](https://github.com/gradle/gradle/pull/23288).

**Comment by xaviarias** [comment]
I have quickly reviewed the PR and looks OK.

@donat do you want to take a looks? Thanks!
