### ISSUE TITLE
`ValidatePlugins` task fails if configured Java Toolchain > Java running the build

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#23125]
The `:validatePlugins` task contributed by the `java-gradle-plugin` plugin fails if configured Java Toolchain > Java running the build.

### Expected Behavior

`:validatePlugins` should work.

### Current Behavior

`:validatePlugins` fails with
```
> Task :validatePlugins FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':validatePlugins'.
> There was a failure while executing work items
   > A failure occurred while executing org.gradle.plugin.devel.tasks.internal.ValidateAction
      > example/MyPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
https://scans.gradle.com/s/qchj6qg7eke42
https://github.com/eskatos/gradle-plugin-toochains-issue/actions/runs/3679778575/jobs/6224627010#step:4:155

### Steps to Reproduce 

* clone https://github.com/eskatos/gradle-plugin-toochains-issue
* use Java < 17 to run the build
* run `./gradlew validatePlugins`

### Context

Discovered while working on

* https://github.com/gradle/gradle/pull/23118

----

The `ValidatePlugins` task loads plugin classes in an isolated classloader (using the Worker API) in the build daemon JVM. This fails if the plugin is built targeting a Java version that is more recent than the one running the build. In that case the task should use an isolated process running with the configured toolchain.

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.
