### ISSUE TITLE
Build services closed twice with configuration cache in 8.0

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#23121]
Version: `8.0-milestone-5`

Using a project with a build service, if configuration cache is enabled, the `close` method on a build service is invoked twice:
- once during the task graph serialization
- the second time during deserialization

This is a problem as build services may have side-effects. E.g. AGP has a build service that writes a file when `close` is invoked.

With `-Dorg.gradle.configuration-cache.internal.load-after-store=false` the `close` method is invoked only once, as expected.

---

See https://gradle.slack.com/archives/C10J6STFZ/p1670870065971169?thread_ts=1670858488.093889&cid=C10J6STFZ

**Comment by adammurdoch** [comment]
Fixed via ~https://github.com/gradle/gradle/issues/23121~ https://github.com/gradle/gradle/issues/23139

**Comment by eskatos** [comment]
Fix confirmed by @gavra0, closing
