### ISSUE TITLE
Gradle 4.0 and scala custom tasks not working

### ISSUE THREAD

**Issue by eschizoid** [gradle/gradle#2313]
My project compiles correctly. However, the following custom task does not run any tests and always returns success:

```
task("unitTest", group: "Test", dependsOn: ['classes'], type: JavaExec) {
    description 'Run unit tests.'
    classpath = sourceSets.unitTest.runtimeClasspath
    main = 'org.scalatest.tools.Runner'
    args = ['-R', 'build/classes/unitTest', '-o']
}
```

```
> Task :compileUnitTestScala
Pruning sources from previous analysis, due to incompatible CompileSetup.

> Task :unitTest
Discovery starting.
Discovery completed in 65 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 131 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.


BUILD SUCCESSFUL in 30s
8 actionable tasks: 8 executed
```

**Comment by eschizoid** [comment]
@big-guy 

> I think it would be worthwhile trying to get your ScalaTests to run with JUnit (http://www.scalatest.org/user_guide/using_junit_runner) so you can use a regular Gradle Test task. You'll get parallel test execution, build cache support and better reporting.

that is not possible since I have `integrationTest` `endToEndTest` just to mention a few...


>You'll need to pass all of the classes directories instead of a single directory (build/classes/unitTest).

im already doing that

```
task("unitTest", group: "Test", dependsOn: ['classes'], type: JavaExec) {
    description 'Run unit tests.'
    classpath = sourceSets.unitTest.runtimeClasspath
    main = 'org.scalatest.tools.Runner'
    args = ['-R', 'build/classes/unitTest', '-o']
}

task("integrationTest", group: "Test", dependsOn: [], type: JavaExec) {
    description 'Run integrationTest tests.'
    classpath = sourceSets.integrationTest.runtimeClasspath
    main = 'org.scalatest.tools.Runner'
    args = ['-R', 'build/classes/integrationTest', '-o']
    systemProperties System.getProperties()
}

task("endToEndTest", group: "Test", dependsOn: [], type: JavaExec) {
    description 'Run end-to-end tests.'
    classpath = sourceSets.endToEndTest.runtimeClasspath
    main = 'org.scalatest.tools.Runner'
    args = ['-R', 'build/classes/endToEndTest', '-o']
    systemProperties System.getProperties()
}
```

**Comment by eschizoid** [comment]
should we reopen the ticket?

**Comment by big-guy** [comment]
> > I think it would be worthwhile trying to get your ScalaTests to run with JUnit (http://www.scalatest.org/user_guide/using_junit_runner) so you can use a regular Gradle Test task. You'll get parallel test execution, build cache support and better reporting.

> that is not possible since I have integrationTest endToEndTest just to mention a few...

I think I wasn't clear before.  If your tests can run from JUnit, you would be able to do something like:
```
task integrationTest(type: Test) {
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
}
```

Instead of using `JavaExec` directly.  Then you'll get the benefits I described for those tests.

**Comment by eschizoid** [comment]
awesome thanks!
