### ISSUE TITLE
docs: Exec commandLine option repeated

### ISSUE THREAD

**Issue by griffingarland** [gradle/gradle#2314]
This is an extremely minor bug but I thought I would report it anyway.
If you look at the gradle docs for task type Exec:
https://docs.gradle.org/4.0/dsl/org.gradle.api.tasks.Exec.html

Under methods, It says:
commandLine(args) and commandLine(arguments), and also args(args) and args(args)
Which as far as I'm aware is the same thing repeated twice each.

EDIT: 

Actually now that I look over the docs more closely, I notice this in several places, is this intentional?

**Comment by abishek3876** [comment]
I think those are for different overloaded methods. But yeah, the description could be updated with the argument type to distinguish them.

**Comment by griffingarland** [comment]
What about args(args) repeated twice? I'm a total novice when it comes to both Java and Gradle but that just seems wrong to me in any language.

**Comment by blindpirate** [comment]
I believe you could submit a pull request bravely. Gradle guys are nice, if there's anything inappropriate, they will point out it.

**Comment by bmuschko** [comment]
If you click on the link of one of the methods you will see that the parameter types are different: https://docs.gradle.org/4.0/dsl/org.gradle.api.tasks.Exec.html#org.gradle.api.tasks.Exec:commandLine(java.lang.Iterable). The list of methods doesn't render the types.
