### ISSUE TITLE
Gradle totally unsupports corporate proxy

### ISSUE THREAD

**Issue by chromatograph** [gradle/gradle#23154]
Maven just works, but Gradle fails constantly.
Spent hours and no result

Make it work like Maven or something

**Comment by xaviarias** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

**Comment by chromatograph** [comment]
well, the problem was in certificates - so i needed to manually add cert chains from [https://plugins.gradle.org/](https://plugins.gradle.org/) to java cacerts. So I opened browser under proxy settings, followed to gradle sites, downloaded certificate chains and added them to cacerts with keytool.

Maybe my corporate proxy MITMs certificates,  or jdk or smth)))

Please add option to not to check ssl, like in maven https://stackoverflow.com/a/21266642
