### ISSUE TITLE
Installation Guide: improvement suggestion

### ISSUE THREAD

**Issue by jerome-leroux** [gradle/gradle#23184]
### Expected Behavior
As a novice user of Gradle, following the installation guide should be easy.

### Current Behavior
Several links and instructions are misleading in the following installation guides:
- https://gradle.org/install/
- https://docs.gradle.org/current/userguide/installation.html

See below for more information.

### Context

I am a novice user of Gradle and take this opportunity to share some suggestions for the installation documentation. For every user, there is only one first installation of a tool, so I think it is a valuable feedback to consider. 

I followed the instructions from the page [Gradle | Installation](https://gradle.org/install/) but later noticed another guide titled [Installing Gradle](https://docs.gradle.org/current/userguide/installation.html?).

Here is my experience from reading the [Gradle | Installation](https://gradle.org/install/) page.

In the first paragraph, the sentence with a link “You can download binaries and view docs for all Gradle versions from the releases page.” is misleading. So I clicked on the link, got into a new page in the same tab, and started reading the instructions on this page. I got confused; it was not the right thing to do. After a while, I went back to the initial page. I understand it makes sense to give a link to this “releases page,” but it should probably be referenced somewhere else. Actually, it is also referenced in the sections “Installing manually” (“Need to work with an older version? See the releases page.”) and “Older Releases.”

Then, for a user who just wants to install Gradle, the “Additional resources” section is not helpful at this step of the installation. It is confusing too. It should be moved to the end of the page.

The “Installing with a package manager” section is fine. However, as a Windows user, it could be interesting to explicitly say if this is the best way to install Gradle. It requires some extra steps to make the package managers compatible with Windows.

So finally, I really started the installation with the “Installing manually” section. Again, the link in “Step 1. Download the latest Gradle distribution” is confusing. Users should not click on it. They will end up on the “Releases” page, which is not what we want to do. The direct download links to the binary-only and complete versions are great.

The other installation documentation named [Installing Gradle](https://docs.gradle.org/current/userguide/installation.html?) is very similar. The introduction section is good.

The same comment for the “Installing with a package manager” section: it could explicitly say if Windows user should follow this way.

In the “Installing manually” section, again, remove the link on the word “Download.” Users should not click on it. Direct download links are missing for “Binary-only” and “Complete.” It would be interesting to put the sentence: “If in doubt, choose the binary-only version and browse docs and sources online.”

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

**Comment by lkasso** [comment]
The issues regarding the [User Manual docs](https://docs.gradle.org/current/userguide/installation.html) portion of the installation process have been addressed in https://github.com/gradle/gradle/pull/24831 (the installation section has been re-written as part of this PR).

The PR does not address issues at: https://gradle.org/install/

**Comment by jerome-leroux** [comment]
Hello @lkasso . Thanks for the update. 
I think the comments in this issue have been address in https://github.com/gradle/gradle/pull/24913 (and not in https://github.com/gradle/gradle/pull/24831).
I will take a look at it and try to provide some feedback.

**Comment by lkasso** [comment]
This has been fully updated in 8.3 docs.
