### ISSUE TITLE
compileScala throws java.lang.UnsupportedOperationException since 8.0-milestone-5

### ISSUE THREAD

**Issue by wolfseifert** [gradle/gradle#23193]
The following <code>build.gradle.kts</code>
<pre>
plugins {
  scala
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("org.scala-lang:scala3-library_3:3.2.1")
}

tasks.withType<ScalaCompile> {
  scalaCompileOptions.additionalParameters = mutableListOf("-feature") // OK
  scalaCompileOptions.additionalParameters = listOf("-feature") // runtime java.lang.UnsupportedOperationException
}
</pre>
compiles but fails to <code>compileScala</code>.

This happens since <code>8.0-milestone-5</code>, <code>8.0-milestone-4</code> and <code>7.6</code> work fine.

There have been made some changes to <code>AbstractScalaCompile.java</code> on Dec 1, 2022. This may explain why milestone 4 works and milestone 5 fails.

This [scalaproject.zip](https://github.com/gradle/gradle/files/10242701/scalaproject.zip) contains the Scala project which does not work.

### Expected Behavior

<pre>$ gradlew compileScala</pre>

should run without errors.
### Current Behavior

<pre>$ gradlew compileScala
Task :compileScala FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':compileScala'.
 java.lang.UnsupportedOperationException (no error message)
</pre>
The build script compiles but fails to <code>compileScala</code>.
### Context

Fails with <code>8.0-milestone-5</code>, works with <code>8.0-milestone-4</code> and <code>7.6</code>.
### Steps to Reproduce 

Unpack the attached <code>scalaproject.zip</code> and run <code>gradlew compileScala</code>.
### Your Environment

Build scan URL:

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.

---

Thank you for testing a milestone.
