### ISSUE TITLE
Project isolation compatibility with build scripts tracing

### ISSUE THREAD

**Issue by 6hundreds** [gradle/gradle#23196]
After introducing missing build scripts tracing for CC, bunch of PI tests start failing.

The reason probably is project script files (e.g. build.gradle) are now being observed **before** the project itself is considered to be under configuration. 

And so it gets dispatched to build scoped sink instead of the project scoped one, what ends up invalidating the whole build configuration instead of just the subset of projects affected by the script change.

**Comment by bamboo** [comment]
Fixed via #25290
