### ISSUE TITLE
Upgrade 6.x -> 7.x: numerous errors "Project#afterEvaluate ... cannot be executed in the current context"

### ISSUE THREAD

**Issue by xtracoder** [gradle/gradle#23216]
Hello, 

I've made an attempt to upgrade my multi-module project from Gradel 6.x to 7.x and finally failed becasuse of errors like "_Project#afterEvaluate ... cannot be executed in the current context_". The problem is that it is absolutely not possible to grasp the reason of this error. Somehow I was able to suppress it in some context but it appears at some further flow of the build.

It would be helpful if Gradle team:

**1.** Provides in documentation description of "_which contexts are considered to be acceptable and which are not_". 

https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:afterEvaluate(groovy.lang.Closure)
The only mentioned failure condition is "_If the project has already been evaluated, this method fails_" and it seems it is not the my case (note: build was working OK for years at Gradle 6.x)

It appears absolutelly same thing happens to "gradle.afterProject" (these methods can functionally replace each other) and documentation also does not mention which contexts are "bad"
https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html#org.gradle.api.invocation.Gradle:afterProject(groovy.lang.Closure)

**2.** I tried to dig in the Gradle's source code for the actuall reason and it is hardly possible to catch the particular cause of my errors.
As far as i understand, problem occurs when `Project#afterEvaluate` occurs withing action invoked using `AbstractMutationGuard.withMutationDisabled(Action<? super T> action)`. I guess **adding name to such context and printing it out during error** will significantly help with identification of root cause of fault conditions.

**Comment by xaviarias** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

---

Please take a look at [this entry](https://docs.gradle.org/current/userguide/upgrading_version_6.html#calling_project_afterevaluate_after_project_evaluation_is_now_an_error) in the upgrade guide. Your build in 6.x should be emmiting deprecation warnings.
