### ISSUE TITLE
Add global cache key to invalidate all existing cache

### ISSUE THREAD

**Issue by wisechengyi** [gradle/gradle#2322]
Hi,

### Context
Sometimes the cache can get into an non ideal state, and we want to nuke all of them. However that is not always feasible because there might be local cache on many hosts. It can be time consuming to manually do it, or potentially dangerous to automate for deleting the wrong thing.

### Expected Behavior

Therefore I think it would be handy to add a global cache key, so when we bump it, it will invalidate all the existing cache, so we don't have to worry about the stale ones.

Same as `--cache-key-gen-version` in Pants, http://www.pantsbuild.org/options_reference.html

Thanks,
Yi

**Comment by big-guy** [comment]
Hi @wisechengyi!

Do you have an example of an 'non ideal state' that would not be fixed by 1) fixing the task implementation, 2) adding inputs to the task, 3) adding/removing outputs of the task or changing the build script in some way?

**Comment by wisechengyi** [comment]
Yes gladly :) As an occasional Pants developer, we ran into similar scenario before:

For example, it can get tricky when gradle's own code changes, for some task:
Before the change: input X, output Y, stores it in cache
After: input X should result output Y'

The cache key is the hash of input (+ others we assume remain constant here), so after an gradle upgrade, it sees the input is still X, then go ahead and fetch the cache for X which is Y, whereas Y is not correct anymore.

Yes this can be fixed by fingerprinting the task itself into the cache key. Although in practice, there can be here and there we can miss, and having this feature would be handy.

**Comment by big-guy** [comment]
The version of Gradle is built into the cache key, so upgrading Gradle would generate a new cache key.

The implementation of the task and any of the task's actions are also a part of the cache key.  So if you change the code for the task, we would generate a new cache key. This happens automatically for all tasks.

> Although in practice, there can be here and there we can miss

I think you meant "we can miss inputs"?  In that case, fixing the task (adding those inputs) would change the cache key.

Does that cover what you were thinking?

**Comment by wisechengyi** [comment]
Yes in this particular case.

> I think you meant "we can miss inputs"? In that case, fixing the task (adding those inputs) would change the cache key.

Correct, but fixing the tasks and deploy them takes a longer time than bump the cache key. Iterating in this mode isn't feasible from operation's standpoint. We want to deliver the workaround asap then work on the actual fix.

Given the gradle version is already in the cache key, it should not be hard to inject another user defined key, and it will give us the leeway to get out of sticky situations.

**Comment by oehme** [comment]
I don't yet understand the use of this global key yet. What would one-off-fixing the cache do for you? If your task is broken then the cache will go bad again. There is no way around fixing the broken task.

That being said, this requirement is trivial to implement without being a core feature. Just add a project property as an input to every task.

**Comment by wisechengyi** [comment]
Thanks for the pointer, @oehme! Looks like I can use that for https://issuetracker.google.com/issues/62678772 :)

I agree it is generally not needed, although the point is that it would be handy in those sticky situations, as a plan B, from operation's point of view.

Another scenario is that cache could get corrupted, which does happen occasionally and it is hard to determine which one is bad, so the question is: does gradle explicitly verify the integrity of the cache?

**Comment by oehme** [comment]
> which does happen occasionally 

You mean you've seen Gradles cache get corrupted? If so please open an issue with more details, we'd be very interested in that.

I'm closing this issue as the requested feature is already there in the form of input properties.

**Comment by wisechengyi** [comment]
```
tasks.all {
  inputs.property "globalKey", findProperty("globalKey")
}
gradle someTask -PglobalKey=12345
```
does not seem to invalidate the cache...i'll try to attach the repro in a bit.
