### ISSUE TITLE
Could not connect to the Gradle daemon.

### ISSUE THREAD

**Issue by guobj** [gradle/gradle#23235]
I encountered this problem when I was using gradle 6.9.3 and 7.5.1, how to solve this problem

ERROR：
Could not connect to the Gradle daemon.
Daemon uid: 99744fdf-cd72-43de-802b-9547987bab39 with diagnostics:
Daemon pid: 3401386
  log file: /root/.gradle/daemon/7.5.1/daemon-3401386.out.log
----- Last  20 lines from daemon log file - daemon-3401386.out.log -----
2022-12-20T11:03:32.578+0800 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Is this a loopback interface? false
2022-12-20T11:03:32.578+0800 [DEBUG] [org.gradle.internal.remote.internal.inet.InetAddresses] Adding remote address /fe80:0:0:0:399a:a397:eab3:564f%enp189s0f0

**Comment by xaviarias** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.
