### ISSUE TITLE
Configure target directory for start scripts

### ISSUE THREAD

**Issue by demurgos** [gradle/gradle#2323]
Hi,
I would propose a new feature: to be able to configure the location of the start scripts. Currently it is only possible to set its name, it would be great to be able to set the target directory too.

### Expected Behavior

You should be able to set the complete location of startup script, either with `applicationName` and a new property `applicationDirectory`, or a single new variable `applicationPath`.
For example,
```
task example1(type: CreateStartScripts, dependsOn: jar) {
  applicationName = "example1"
  applicationDirectory = ""
}
```
would produce:
```
|
+--+-- libs/
   +-- example1
   +-- example1.bat
```
And this config
```
task example2(type: CreateStartScripts, dependsOn: jar) {
  applicationName = "example2"
  applicationDirectory = "foo/bar"
}
```
would produce:
```
|
+--+-- libs/
   +-- foo/
      +-- bar/
         +-- example2
         +-- example2.bat
```

### Current Behavior

The target directory is hard-coded to `bin`:
[See this line](https://github.com/gradle/gradle/blob/dcd1e0d5e3663a39cfe75a14da19de4669804450/subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java#L272). It is not configurable.

### Context

I am trying to output my build scripts at the root of the zip produced by `distZip` instead of being in a subdirectory. I'd like to be able to do something like in the first example. This is also similar to the start-script used by gradle itself: `./gradle` is at the root instead of being inside the `bin` directory.

**Comment by k-mack** [comment]
See https://discuss.gradle.org/t/change-startscripts-relative-path-from-bin-to-something-else/22912. You can extend CreateStartScripts and chang the relative script path. However, I agree that it'd be better to configure this via the DSL.

**Comment by demurgos** [comment]
Thank you for this link, it helped me to solve my issue but I am happy that we agree that it should be simpler. I was about to implement this solution myself but I wasn't comfortable importing classes from a package named "internal".

**Comment by bmuschko** [comment]
I think this could be solved fairly easily by exposing a new property. Would you be interested in providing a pull request for this?

**Comment by demurgos** [comment]
I am not familiar enough with Gradle or Groovy and to be honest I don't have much time right now to learn how the link between the DSL and the Java code I found works. I did not research it yet, but if you have an article explaining how it works, I'd be interested. Java is not my main technology so it was a punctual problem for me: even if Gradle is great, I do not expect to use it much.

What I mean by that is that I'd like to help, but I cannot guarantee that I'll provide a PR.

**Comment by bmuschko** [comment]
OK, thanks for your feedback. I added the tag `help-wanted` if somebody from the community wants to pick this up.

**Comment by xz64** [comment]
Hi @bmuschko , I'd like to work on this feature. This is my first time changing code inside gradle code. I have implemented the feature but still need to add tests / documentation. 

Can you help me out with a few things?

- How do I run one specific integration test from the command line?
- Can I submit a WIP pull request for a code review of the feature (before having written any tests)? I can add the tests / documentation later once the implementation passes code review.

Here are my changes so far:

https://github.com/gradle/gradle/compare/master...xz64:custom_start_scripts_dir

**Comment by demurgos** [comment]
I'm closing this issue now that #2977 was merged.
