### ISSUE TITLE
Version catalogs aren't available for code inside of `build[logic/Src]/src`, so they're not compatible with the guidelines for multi-module projects

### ISSUE THREAD

**Issue by GavinRay97** [gradle/gradle#23233]
I structured our org's project using the Gradle guidelines for multi-module builds:

![image](https://user-images.githubusercontent.com/26604994/208531577-c7886259-99e2-4cc2-8f6c-9807c51cfc6c.png)

The problem is, if you use a version catalog to aggregate your dependencies in one place, you can't actually use this (from what I understand) in code inside of `buildSrc/src` -- e.g., `buildSrc/src/main/kotlin/my-kotlin-library-conventions.kts`

- https://stackoverflow.com/questions/67795324/gradle7-version-catalog-how-to-use-it-with-buildsrc

I've put this in my `buildSrc/settings.gradle.kts`:

```kt
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("../gradle/libs.versions.toml"))
        }
    }
}
```

But it's only available in `buildSrc/build.gradle.kts,` not the contents of `src/**`

Is there any way around this? It's like the crack in the wall of the dam when the rest of your very large project has entirely managed versions.

Thank you

**Comment by GavinRay97** [comment]
Actually on second thought, if you specify the full version in the version catalog, and you always use it from the catalog, then the net effect is the same as providing a constraint I suppose.

There's still the larger question of whether the other information in the version catalog is meant to be present/accessible inside of the `src` files

**Comment by xaviarias** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

**Comment by melix** [comment]
Duplicate of https://github.com/gradle/gradle/issues/15383

**Comment by GavinRay97** [comment]
Ah whoops, my apologies!
