### ISSUE TITLE
Dependency Management Resolution not possible with modules

### ISSUE THREAD

**Issue by flemminglundahl** [gradle/gradle#23255]
When using the Dependency Management Resolution in combination with modules extensions are not available when used in either allporjects or subprojects in the root build.gradle.

### Expected Behavior
Would be able to use dependency extensions in the same way it is possible in buildscript and subprojects.

### Current Behavior
`Extension with name 'libs' does not exist. Currently registered extension names: [ext, base, defaultArtifacts, sourceSets, reporting, javaToolchains, java, testing, scalaRuntime, scala]
`

### Context
Trying to align dependencies as intended with the Dependency Management Resolution feature.

### Steps to Reproduce

Root build.gradle.kts
```
plugins {
  kotlin("jvm") version "1.6.21"
}

buildscript {
  dependencies {
    classpath(libs.scala.library)
  }
}

allprojects {
  apply(plugin = "java")
  apply(plugin = "scala")

  dependencies {
//    implementation(libs.scala.library)
  }
}
```

```
rootProject.name = "dependency-management-resolution-modules-issue-sample"

dependencyResolutionManagement {
  repositories.mavenLocal()

  versionCatalogs {
    create("libs") {
      library("scala-library", "org.scala-lang:scala-library:2.13.6")
    }
  }
}

include("child")
```

The child module is not important, it just has to be there.
A project with this setup will be able to create the gradle project. But the the dependency implementation(libs.scala.library) in allrpojects is included, it will fail with the mentioned error. The error can then again be removed by excluding the child module. The same issue can be reproduced with subprojects instead of allprojects. Since buildscripts works fine I assume that there is an issue with applying this when subprojects are available. There is no issue using this feature in the subprojects/modules themselves. It is only when using either allprojects or subprojects.

I created a sample-project where the issue is reproduceable, but wasn't able to either upload it to this issue or create a branch on this repo for it. Let me know if more information is needed.

### Your Environment
Reproduced with versions 7.5.1 and 7.6.

**Comment by xaviarias** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

---

Thanks for adding reproducible code, but please add a valid reproducer using our template.

**Comment by flemminglundahl** [comment]
Must have missed this reproducer template description somewhere. But I've added one and hopefully this will show the issue. I've used the reproducer template here: https://github.com/flemminglundahl/Dependency-Management-Resolution-module-issue

**Comment by melix** [comment]
This is a duplicate of https://github.com/gradle/gradle/issues/16708 (itself duplicate of several issues). In a nutshell, you should avoid `allprojects`/`subprojects` and use convention plugins instead.

**Comment by flemminglundahl** [comment]
Sorry for not looking thorough enough for older issues. 

I guess that makes sense and wouldn't be an issue for me to implement instead. But why are allprojects and subprojects not just being deprecated if the gradle team wants Devs to use convention plugins instead?
