### ISSUE TITLE
Successful check tasks stay up-to-date after clean if they only report to console

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#2326]
This concerns the following _check_ plugins: _Checkstyle_, _Pmd_, and _CodeNarc_

For _CodeNarc_, the issue is a bit heavier, as it only allows one report type at a time (`codenarc { reportFormat = '' }`). For the others, a workaround is to produce at least one file-based report in addition to the console report.

### Expected Behavior
- After a clean, the `check` task should be re-executed

### Current Behavior
- If `check` is successful and **only** prints to console (i.e. does not produce any output from the Gradle perspective), the task stays up-to-date even after `clean`.

### Context
- This was discovered/discussed in the context of #1481, which added `console` support to CodeNarc.
- The issue does only affect the not-so-important case, where the check is successful and an explicit clean was performed. If the task fails, it re-executes. If a task input (e.g. source code) changes, it re-executes.

### Steps to Reproduce
- Failing integration tests: https://github.com/gradle/gradle/commit/f299fe9aadbea42a69dcaa306bd776440287f4f5

**Comment by oehme** [comment]
You could argue that's correct, because no input and no output changed, so there would be no point in rerunning.

**Comment by JLLeitschuh** [comment]
Related #3095

**Comment by jjohannes** [comment]
As this is the expected behavior, it will stay like it is for now.
