### ISSUE TITLE
Is it possible to prevent gradle daemon to run competing tasks?

### ISSUE THREAD

**Issue by srmurguia** [gradle/gradle#2328]
### Expected Behavior
When there are tasks that compete for the same resources (for example, cleaning and building the same project) simultaneously, gradle should fail with a description of what it cannot do.  

### Current Behavior
While calling a clean from Android Studio while a build is running, sometimes a message like this is generated:

Error:Execution failed for task ':app:clean'.
> Unable to delete file: ... .jar

### Context
This was caused while building an app on Android Studio but should be reproducible from command line

### Steps to Reproduce (for bugs)
From Android Studio create a new Android Studio project, go to Build -> . Make Project and immediately after that go to Build -> Clean, you will hit this issue sometimes, this is an sporadic problem

### Your Environment
Gradle 3.3 called from:

Android Studio 2.3.1
Build #AI-162.3871768, built on April 1, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by oehme** [comment]
When you launch two commands at the same time then you get two Gradle daemons. Making them coordinate builds of the same project would certainly be interesting, but might break other use cases where this is desired.

 I think it would be simpler if AS blocked the clean button while a build is already in progress.

**Comment by bmuschko** [comment]
I'd suggest you ask for support on the Google Android forum. They might provide a solution as suggested by @oehme.

**Comment by srmurguia** [comment]
There is something like that in the works at this moment from AS (not allowing cleaning while building), just wanted to know if that could be checked also in Gradle for other  cases when there are conflicts with shared resources. Build and clean is one of those cases and I was wondering if we should keep an eye on similar issues.

**Comment by bmuschko** [comment]
I am going to close the issue for now as AS might provide a satisfactory solution. We are currently not working on something to help with this.
