### ISSUE TITLE
Use testSourceSets.add(sourceSets.functionalTest) instead of testSourceSets(sourceSets.functionalTest)

### ISSUE THREAD

**Issue by stewartbryson** [gradle/gradle#23298]
### Expected Behavior

When using the `init` task to create a `groovy-gradle-plugin`, the following is written to `plugin/build.gradle`:
```
gradlePlugin.testSourceSets(sourceSets.functionalTest)
```
Instead, it should write:
```
gradlePlugin.testSourceSets.add(sourceSets.functionalTest)
```

### Current Behavior

The current behavior invalidates the built-in `test` sourceSet .

### Context

It took me forever to figure out why the standard `test` sourceSet did not automatically apply the TestKit in the initialized project. It's not intuitive to people getting started with `JvmTestSuite` from older Gradle releases.

### Steps to Reproduce 

Run: `gradle init --type groovy-gradle-plugin`
Create any test in: `plugin/src/test/groovy`
Run: `gradle test`
The output: `unable to resolve class org.gradle.testkit.runner.GradleRunner`

### Your Environment

Build scan URL:
https://scans.gradle.com/s/pmtdqlhzc4fzc

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.
