### ISSUE TITLE
Should avoid publishing an artifact if the task that created it was skipped

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#23299]
In the process of making [Ivy publish compatible with the configuration cache](https://github.com/gradle/gradle/issues/13469), we saw [this old issue come back to life](https://github.com/gradle/gradle/issues/5136), or at least that regression test that we have for it started to fail. The test was temporarily disabled. The present issue is meant so we investigate and fix it again.

**Comment by adammurdoch** [comment]
I wouldn't make publishing lenient, as that opens the door to all kinds of silent and confusing behavour when things are misconfigured. Instead, I would think about making publishing stricter (ie fail if any registered artifact is not present) and instead look at ways to give people more control over overriding the conventions.

**Comment by abstratt** [comment]
It looks like this was reported in haste, these commits by @bamboo addressed the regression less than an hour after this was reported:

* https://github.com/gradle/gradle/commit/c98c782ca1263550fde851061a657301d65fd7ac
* https://github.com/gradle/gradle/commit/8f50c5d7f87dde91ed9802f129236a37df6aa248
