### ISSUE TITLE
Every time I try to use my mod in a world It give me a error

### ISSUE THREAD

**Issue by Jromefan1** [gradle/gradle#23326]
"A crash in JVM native code was detected. Don't worry!"

It says that every time I try to start up my mod. I tried reinstalling but nothing happened and now I can't run my mods. I tried and tried to start my mod but it won't work. 

![Screenshot 2022-12-28 103651](https://user-images.githubusercontent.com/121569525/209843846-9d397018-2b71-4b75-912a-13b6a17ef323.png)

**Comment by quat1024** [comment]
This is the Gradle issue tracker, not MCreatir's

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
