### ISSUE TITLE
shell support in groovy plugin

### ISSUE THREAD

**Issue by robokaso** [gradle/gradle#2333]
### Expected Behavior
`gradle shell` would  launch groovysh with the classpath reflecting project dependencies

### Current Behavior
An interactive shell would enable REPL-style development as a complement to the supported compile-test-package workflow

### Context
REPL is invaluable for exploratory data science workflows as well as ETL development, where you need to experiment with transformations on data loaded in the memory. To achieve this I currently use an adhoc groovysh script that grabs the same dependencies declared in build.gradle.

There is an [unmaintained groovysh plugin](https://github.com/tkruse/gradle-groovysh-plugin) that almost worked for me except for invoking previous/next command (using arrow keys or Ctrl-N/Ctrl-P). Still I feel like groovysh should be part of the official groovy plugin rather than a 3rd party addon.

In the competitive maven camp [GMavenPlus](https://github.com/groovy/GMavenPlus/wiki/Examples#groovy-shell) provides comprehensive Groovy support including the requested shell

**Comment by mkobit** [comment]
I brought something similar up in https://github.com/gradle/gradle/issues/1251#issuecomment-297840054

**Comment by bmuschko** [comment]
Just wondering...is the Groovy web console not a viable option or do you necessarily need dependencies declared in your build script?

For experimenting with Gradle build code isn't running a build script good enough. Maybe you can describe your use case on a deeper level.

**Comment by bmuschko** [comment]
I think we should start by gather concrete use cases if you are still interested in the functionality. IMHO it's good enough for users to change a build script and run it to the see effect of a change.

**Comment by bmuschko** [comment]
I am pretty sure we'll work on this anytime soon. Please provide a concrete spec with use cases and an implementation approach if you'd like to see the feature. Maybe a good start might be to work on this as an external plugin. I am going to close the issue for now. Feel free to reopen the issue if you are ready to provide a spec in a PR.
