### ISSUE TITLE
Compiling Multi Project/Module JDK 9 Build

### ISSUE THREAD

**Issue by jamespedwards42** [gradle/gradle#2334]
I am testing out JDK 9 support against 4.1-milestone-1 with a multi project build, where each project is a single Jigsaw module and some modules depend on other modules.

```
Root project 'parent'
+--- Project ':core'
+--- Project ':module-a' (Depends on :core)
```

module-info.java for `core`
```
module namespace.core {
  exports namespace.core.package;
}
```

module-info.java for `module-a`
```
module namespace.module_a {
  requires namespace.core;
}
```

### Expected Behavior
Compilation of module-info.java files with inter-project/module dependencies should succeed.  I know official Jigsaw support has been postponed for a later release, but I was hoping that maybe compilation would be available sooner?

### Current Behavior
```
> ./gradlew compileJava
module-info.java:2: error: module not found: namespace.core
  requires namespace.core;
```

### Environment
Gradle 4.1-milestone-1
Build time:   2017-06-20 17:05:46 UTC
Revision:     3ad5af92d482b963cc6b00fb5ad53b608606d657

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-ea (Oracle Corporation 9-ea+173-jigsaw-nightly-h6494-20170608)
OS:           Mac OS X 10.12.5 x86_64

**Comment by bmuschko** [comment]
4.1 is aiming for using JDK 9 to build a project. I don't think we are supporting building Jigsaw modules yet.

**Comment by jjohannes** [comment]
You should be able to build Java modules now with the latest `6.4` nightly - see https://github.com/gradle/gradle/issues/890#issuecomment-603289940 for details. Please comment there if you still face any issues.
