### ISSUE TITLE
Existing version not resolved

### ISSUE THREAD

**Issue by sultan** [gradle/gradle#23353]
The artifact resolver fails to find artifacts if they exist outside maven metadata.

### Current Behavior
The artifact resolver fails to find artifacts if they exist outside maven metadata.
The dependency tree fails to show there exist a version 1.2.6 for my dep
+--- org.glassfish.web:jakarta.servlet.jsp.jstl:1.2.+ FAILED

### Expected Behavior
Artifact resolver should search versions before calling it a day.
1. The resolver can check the metadata first to speed up the search
2. If no version found then search within the html page instead.

### Context
trying to keep a tidy dependency tree using an update range in same minor
the resolver fails to find the existing deps
had to manually manage a fixed version value, this becomes tiring the more i have to do it

### Steps to Reproduce
1. build.gradle file with :
dependencies {
	runtimeOnly group: 'org.glassfish.web', name: 'jakarta.servlet.jsp.jstl', version: '1.2.+'
}
3.  run dependencies --write-locks

### Workaround (tiring)
runtimeOnly group: 'org.glassfish.web', name: 'jakarta.servlet.jsp.jstl', version: '1.2.6'

### Your Environment
Gradle 7.6

**Comment by sultan** [comment]
* Maven has the same problem and cant resolve the range dependency
* a related problem is that maven central is not curated and metadata are not checked for correctness

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

---

As a less tiring workaround you could try with [Maven style ranges](https://docs.gradle.org/current/userguide/single_versions.html).

**Comment by ljacomet** [comment]
The [maven metadata](https://repo.maven.apache.org/maven2/org/glassfish/web/jakarta.servlet.jsp.jstl/maven-metadata.xml) for that dependency is incorrect. Maybe Maven Central could fix it. I would suggest to reach out to them.

An alternative in Gradle would be to use a [custom version lister](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/repositories/MetadataSupplierAware.html#setComponentVersionsLister-java.lang.Class-). Unfortunately, that feature does not have much documentation but you could look at [tests](https://github.com/gradle/gradle/blob/a2323758d4b3b8ed24d9700cdaf1b0535d757a11/subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepositoryTest.groovy#L230-L245) inside Gradle itself.

There is no plan to change the behavior in Gradle. When a `maven-metadata.xml` is found, we assume it is correct.

**Comment by sultan** [comment]
thank you for this clear answer.
