### ISSUE TITLE
gradlew and gradlew.bat scripts difference between Github and wrapper task execution

### ISSUE THREAD

**Issue by eirnym** [gradle/gradle#23364]
### Expected Behavior

* Gradle wrapper downloads wrapper the same scripts as shown [on GitHub](https://raw.githubusercontent.com/gradle/gradle/release7x/gradlew). Script below will show no difference, thus nothing to commit.
* UTF-8 file encoding flag is included in DEFAULT_JVM_OPTS

### Current Behavior

Gradle wrapper scripts has some important differences:
* some space differences at the end of line (minor issue) for 
* DEFAULT_JVM_OPTS has no `file.encoding` set

```diff
diff --git a/gradlew b/gradlew
index 5580fce..65dcd68 100755
--- a/gradlew
+++ b/gradlew
@@ -86,7 +86,7 @@ APP_BASE_NAME=${0##*/}
 APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
 
 # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='-Dfile.encoding=UTF-8 "-Xmx64m" "-Xms64m"'
+DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -144,7 +144,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
         # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC3045
+        # shellcheck disable=SC3045 
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
@@ -152,7 +152,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
       '' | soft) :;; #(
       *)
         # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC3045
+        # shellcheck disable=SC3045 
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
```

### Context
Default file encoding is not UTF-8 per java standard and all Windows developers are affected as their locale is not UTF-8.

I've tried:
* run wrapper task under various Linux, macOS and Windows versions
* explicitely set locale to non-UTF-8 locale on all systems above using LANG environment variable

Manual downloading the scripts is not a solution.

### Steps to Reproduce 
version `7.6` and `release7x` branch were chosen arbitrarely as they currently the same  at the moment of writing the issue to minimize difference and script complexity

1. Download via curl to an empty folder 
2. make a commit
3. fetch the wrapper with the same version
```zsh
$ mkdir empty && cd empty && git init
$ curl -sSLo gradle/wrapper/gradle-wrapper.properties https://github.com/gradle/gradle/raw/release7x/gradle/wrapper/gradle-wrapper.properties
$ curl -sSLo gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/release7x/gradle/wrapper/gradle-wrapper.jar
$ curl -sSLo gradlew  https://github.com/gradle/gradle/raw/release7x/gradlew
$ curl -sSLo gradlew.bat https://github.com/gradle/gradle/raw/release7x/gradlew.bat 
$ chmod +x gradlew
$ echo 'gradlew text eol=lf' >> .gitattributes
$ echo 'gradlew.bat text eol=crlf' >> .gitattributes
$ git add gradle* .gitattributes
$ git commit -m test
$ ./gradlew wrapper --gradle-version=7.6
$ git diff
$ # there should be no differences shown
```

### Your Environment

tested on macOS, various Linux and Windows 10 & 11.

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by xaviarias** [comment]
Hi @eirnym, the UTF-8 encoding on the Gradle wrapper scripts is [expected](https://github.com/gradle/gradle/blob/master/build-logic/build-update-utils/src/main/kotlin/gradlebuild.wrapper.gradle.kts#L10) and only applies to the Gradle project itself.

The way to use the wrapper is though the wrapper task, not downloading it, so unless there is a problem with the JVM option not being present, there is no issue on our side.

> Default file encoding is not UTF-8 per java standard and all Windows developers are affected as their locale is not UTF-8.

Could you please specify how Windows users are affected? Thanks.

**Comment by eirnym** [comment]
We have test java classes resources with UTF-8 text and when we test the application, discrepancy is shown. If we specify the `file-encoding` flag, tests are passing. 

Otherwise, we have to add it to the every build.gradle(.kts) file or specify in init.gradle(.kts), which is quite annoying. I know that java set it as a standard only since Java 18. But many applications are still using Java 8.

I don't see much on GitHub that this flag, so I don't know how users handle that in their repositories.

**Comment by eirnym** [comment]
By the way, why wrapper updates the `gradlew`/`gradlew.bat` files at all? could we have a switch to disable these files to be upgraded if nothing major has been changed?

**Comment by xaviarias** [comment]
Is it possible that you are not using the Gradle daemon in your project? That might explain why the wrapper JVM options are used to run the tests. To be sure I would need a [valid reproducer](https://github.com/gradle/gradle-issue-reproducer) of your issue.

**Comment by eirnym** [comment]
it's allowed to be used and used in most cases, e.g. in Intellij Idea IDE, or by building and/or running an application from a terminal. I believe that daemon takes the setting from the argument from above.

Linux and macOS users and CI are not affected, as locale is rarely is not  UTF-8 nowadays.

On CI we explicitly switch off daemon as we use one-time pod to build an app.

**Comment by xaviarias** [comment]
> it's allowed to be used and used in most cases

What are you refering to? The Gradle wrapper can be used from the script, but it normally starts a daemon with its own JVM arguments.

> On CI we explicitly switch off daemon as we use one-time pod to build an app.

So this might be the reason why these are taken into account.

**Comment by xaviarias** [comment]
> By the way, why wrapper updates the gradlew/gradlew.bat files at all? could we have a switch to disable these files to   be upgraded if nothing major has been changed?

Those files are generated by the wrapper and they should not change, unless you have an altered version like the one you are downloading.

**Comment by eirnym** [comment]
they are changing with every next version of gradle. We found these changes recently and nobody wants to return back, while we want to have maintenance updates did by the wrapper task.

**Comment by eirnym** [comment]
Also we found that downloading few files from the gradle repository is the fastest way to initialize the project. 
Files are:

* gradlew
* gradlew.bat
* gradle/wrapper/gradle-wrapper.jar
* gradle/wrapper/gradle-wrapper.properties

then touch settings.gradle(.kts) and build.gradle(.kts)

**Comment by xaviarias** [comment]
> they are changing with every next version of gradle. We found these changes recently and nobody wants to return back, while we want to have maintenance updates did by the wrapper task.

That's it, if you change your Gradle version you might get changes in the wrapper files.

**Comment by xaviarias** [comment]
> Also we found that downloading few files from the gradle repository is the fastest way to initialize the project. Files are:
> 
> * gradlew
> * gradlew.bat
> * gradle/wrapper/gradle-wrapper.jar
> * gradle/wrapper/gradle-wrapper.properties
> 
> then touch settings.gradle(.kts) and build.gradle(.kts)

Downloading these files from a Gradle release is up to you, but they are not the standard generated wrapper files. Any difference might get overridden by the wrapper task. 

Again, this is the expected behavior. If you want to have the encoding added to your `gradlew` script files, you can add this code snippet to your `build.gradle.kts` file:

```kotlin
tasks.withType<Wrapper>().configureEach {
    val jvmOpts = "-Dfile.encoding=UTF-8"
    inputs.property("jvmOpts", jvmOpts)
    doLast {
        val optsEnvVar = "DEFAULT_JVM_OPTS"
        scriptFile.writeText(scriptFile.readText().replace("$optsEnvVar='", "$optsEnvVar='$jvmOpts "))
        batchScript.writeText(batchScript.readText().replace("set $optsEnvVar=", "set $optsEnvVar=\"$jvmOpts\" "))
    }
}
```

Alternatively, you can place the snippet in a pre-compiled script plugin and apply it to your project build.
