### ISSUE TITLE
unzipped-distribution - Log4j Vulnerability on Enterprise File System Scans

### ISSUE THREAD

**Issue by EarthCitizen** [gradle/gradle#23378]
The files downloaded into `$HOME/.gradle/caches/transforms-3/<..some ID..>/transformed/unzipped-distribution/gradle-7.5.1` contain the following JARs:

```
./subprojects/docs/src/snippets/antMigration/fileDeps/kotlin/libs/log4j-1.2.8.jar
./subprojects/docs/src/snippets/antMigration/fileDeps/groovy/libs/log4j-1.2.8.jar
```

These show up on enterprise file scans as a vulnerability on the dev machines. Please remove or upgrade this JAR from `unzipped-distribution`.

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

**Comment by eskatos** [comment]
This will be in Gradle 8.0

* Fixed in https://github.com/gradle/gradle/pull/23424
