### ISSUE TITLE
Provide a way to register additional classesDirs on SourceSetOutput

### ISSUE THREAD

**Issue by sergeykad** [gradle/gradle#2338]
FindBugs plugin does not see classes added via `sourceSets.main.output.dir(output, builtBy: 'taskName')`

### Expected Behavior
FindBugs scans all classes in `sourceSets.main.output`

### Current Behavior
FindBugs issues warnings about missing classes: "The following classes needed for analysis were missing" with a list of classes that are not in the default classes folder.

### Steps to Reproduce (for bugs)
Move some of the classes to a separate output directory configured via `sourceSets.main.output.dir(output, builtBy: 'taskName')`

### Your Environment
Gradle 4.0 with latest FindBugs plugin

**Comment by bmuschko** [comment]
Can you explain what you are trying to achieve?

**Comment by sergeykad** [comment]
I am just trying to scan my code with Findbugs, but getting a warning that it cannot find some of the classes. 
The classes that it cannot find are not in the default output directory, but in one added via `sourceSets.main.output.dir(output, builtBy: 'taskName')`

**Comment by oehme** [comment]
`output.dir` is for adding resource directories. There is currently no public equivalent for registering a classes directory.
