### ISSUE TITLE
Adding this artifact unexpectedly transits its test dependencies into the compile classpath

### ISSUE THREAD

**Issue by jearton** [gradle/gradle#23396]
### Expected Behavior

Should not transit the test dependencies of the artifact `org.apache.logging.log4j:log4j-spring-boot:2.17.2` into the compile classpath.

### Current Behavior

When I add the artifact `org.apache.logging.log4j:log4j-spring-boot:2.17.2`, its test modules withs the group  `org.junit.vintage` and `org.junit.jupiter` will transit into my project.

### Context

To fix this problem, I had to exclude them. It seems to be a very temporary solution.

```gradle
    implementation('org.apache.logging.log4j:log4j-spring-boot:2.17.2') {
        exclude group: 'org.junit.vintage'
        exclude group: 'org.junit.jupiter'
    }
```

### Steps to Reproduce 

You can reproduce it with such codes in build.gradle
```gradle
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'java'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation('org.apache.logging.log4j:log4j-spring-boot:2.17.2')
}
```

### Your Environment

Gradle 7.6
Java 11
IDEA 2022.3

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

***

The metadata for the jar (pom) contains these test dependencies, so Gradle works as it's supposed to. Maybe this jar is intended to be used only for testing by the Spring Boot team. If you need help pls. contact the Spring Boot community.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

***

The pom file associated with that Spring Boot jar clearly adds these test dependencies, so Gradle's handling of the jar is correct. Maybe this jar was never intended by the Spring Boot team to be used in non-test code. Pls. reach out to the Spring Boot community in case you need further help.
