### ISSUE TITLE
Gradle 8 upgrade docs missing for TestReport removals

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#23390]
### Expected Behavior
`TestReport`'s `testResultDirs` (and maybe others) removal mentioned like all the others at https://docs.gradle.org/8.0-rc-1/userguide/upgrading_version_7.html#removed_apis_and_features

### Current Behavior
```
e: mycode.kt:101:9 Unresolved reference: testResultDirs
```

### Context
Just for completeness of the upgrade docs.

---

Note also that earlier mention of the `TestReport` deprecations:
https://docs.gradle.org/8.0-rc-1/userguide/upgrading_version_7.html#replacement_methods_in_org_gradle_api_tasks_testing_testreport
contain invalid function names.

It's called [`testResultDirs`](https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.testing.TestReport.html#org.gradle.api.tasks.testing.TestReport:testResultDirs), not `testResultsDirs`.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

**Comment by tresat** [comment]
@TWiStErRob - Thank you for pointing this out, I did indeed miss this property when cataloging the deprecation removals.

**Comment by TWiStErRob** [comment]
No worries, there are as so much removed 👏!

Did TestReport.destinationDir end up with the same faith?

**Comment by TWiStErRob** [comment]
Also for some reason "fixes" didn't do its job and this is still open.

**Comment by tresat** [comment]
> Did TestReport.destinationDir end up with the same faith?

That property was originally scheduled for removal, but was [restored](https://github.com/gradle/gradle/commit/0aec4558b13a1570502558844937a9f77044245e#diff-d1c1fb2ff9358e7a8cb38523a435f99f29350de85bff8c4faf72fd20ac0d099e), as it was in use by widely used plugins which haven't yet migrated away from it.  It will now remain until Gradle 9.0.
