### ISSUE TITLE
Gradle Sync Failed after updating to Canary 4 and gradle to 3.0.0-alpha4

### ISSUE THREAD

**Issue by VeeraAnudeep** [gradle/gradle#2340]
``Error:Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=devDebug, filters=[]}} of type `com.android.build.gradle.internal.api.ApkVariantOutputImpl.``

``applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFile = new File(
                    output.outputFile.parent,
                    output.outputFile.name.replace(".apk", "-${variant.versionName}.apk"))
        }
    }
``
This is the code where outputFile is being used.

**Comment by radityagumay** [comment]
@VeeraAnudeep Have you fix this issue? i have same problem.

**Comment by VeeraAnudeep** [comment]
@radityagumay  https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html 
Try these and see if it solves for you as well

**Comment by oehme** [comment]
Closing as this is a change in the Android plugin, not in Gradle. Please see their migration guide.

**Comment by MLlgy** [comment]
do you have any idea about it ?

**Comment by oehme** [comment]
Again, please look at the [migration guide](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_api), this exact issue is explained there.

**Comment by zdl411437734** [comment]
android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "${variant.name}-${variant.versionName}.apk"
    }
}

**Comment by shenhuanet** [comment]
how to fix it?

**Comment by tianzhijiexian** [comment]
```
static def releaseTime() {
    return new Date().format("yyyy-MM-dd", TimeZone.getTimeZone("UTC"))
}

android {
    buildTypes {
       // ...
    }
    
    android.applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def fileName = outputFile.name.replace("app", 
                        "${defaultConfig.applicationId}_${defaultConfig.versionName}_${releaseTime()}")
                outputFileName = fileName
    
            }
    
        }
    }
}
```

**Comment by eric-grab** [comment]
Where did the `outputFileName ` variable come from @tianzhijiexian ? Did you mean `outputFile ` from this line?
```
def outputFile = output.outputFile
```

**Comment by tianzhijiexian** [comment]
classpath 'com.android.tools.build:gradle:3.0.0-beta5'

gradle4.1

@eric-grab

**Comment by jp1017** [comment]
https://medium.com/@AndreSand/android-studio-3-0-fix-apk-naming-issue-when-updating-to-gradle-4-0-639da9d863cd

**Comment by PHPirates** [comment]
For people coming here after updating to gradle 4 (AS 3.0), do exactly as jp1017 linked to:
```
Change ‘each’ -> to ‘all’
Change ‘output.outputFile’ -> to ‘outputFileName’
```
Stupid name changes...

**Comment by tarasokunev** [comment]
@PHPirates 
**you should not replace at every place**: ‘output.outputFile’ -> to ‘outputFileName’
output.outputFile.parent should stay as before.

**Comment by PHPirates** [comment]
@tarasokunev thanks good catch! Forgot to write that down.

**Comment by MarcoMirisola** [comment]
Hi there!
right now I'm using this piece of code to rename an AAR library, and it works perfectly!

` libraryVariants.all { variant ->
        variant.outputs.all { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.aar')) {
                def fileName = "${archivesBaseName}-${android.defaultConfig.versionName}.aar"
                outputFileName = fileName
            }
        }
    }`

**Comment by dariobrux** [comment]
@MarcoMirisola your solution saved my life. thanks

**Comment by wiket** [comment]
@tianzhijiexian your solution only modifies the filename， how to change the dir of output.outputFile？

**Comment by MarcoMirisola** [comment]
@wiket I think that it can't be possible, you cannot set the value of read-only property 'outputFile'. Gradle 4.1 now saves APK in sub-folders named after the variant.

**Comment by TugbaGonultas** [comment]
Hi. I changed to outpufile. But now I get a another error:

`Error:No such property: parent for class: java.lang.String`

Any idea?

**Comment by wiket** [comment]
```
applicationVariants.all { variant ->
        variant.assemble.doLast { assemble ->
            //copy apk file to other directories        
        }
}
```

**Comment by PHPirates** [comment]
@TugbaGonultas 
Did something like the following work for you?
```
android {
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def newName = outputFileName
            newName.replace(".apk", "-${variant.versionName}.apk")
            outputFileName = new File(newName)
        }
    }
}
```

**Comment by TugbaGonultas** [comment]
@PHPirates Yes, it is look like my solution. Before i changed only outputFile->outputFileName. But i found this solution, I am not getting error now. I hope i did it right?
`outputFileName = "${variant.name}-${variant.versionName}.apk"`

**Comment by PHPirates** [comment]
@TugbaGonultas Yes, that's also fine of course, thanks for the feedback!

**Comment by rahman9909** [comment]
It worked for me as below: 

`applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def newName = outputFileName
            newName.replace(".apk", "-${variant.versionName}.apk")
            outputFileName = new File(newName)
        }
    }`

**Comment by oehme** [comment]
Locking this issue, as the solution is given in the Android 3.0 [migration guide](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#variant_output).
