### ISSUE TITLE
Add SAM with receiver and  compiler settings link to the Gradle Kotlin DSL page under the `kotlin-dsl` plugin 

### ISSUE THREAD

**Issue by borisf** [gradle/gradle#23409]
### Expected Behavior
The third bullet of the `kotlin-dsl` [plugin desciption](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin) should have the following text:

*Configures the Kotlin compiler with the SAM with receiver plugin <link> and [same settings](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin_compiler_arguments) that are used for Kotlin DSL scripts, ensuring consistency between your build logic and those scripts.*

### Current Behavior
The third bullet of the `kotlin-dsl` [plugin desciption](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin) has the following text:

*Configures the Kotlin compiler with the same settings that are used for Kotlin DSL scripts, ensuring consistency between your build logic and those scripts.*

### Context
To have a full control over build

### Steps to Reproduce 
Go the the [page](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin)

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.
