### ISSUE TITLE
ivy patternLayout resolving with incorrect value when retrieving artifact

### ISSUE THREAD

**Issue by thomasgregoryNML** [gradle/gradle#23415]
I am trying to retrieve a .jar file from an internal non-standard Nexus repository location.  The actual url to retrieve it from is:

https://nexus.mycompany.com/repository/raw-hosted/mqsadmin/mqsutilclient/0.60/mqsadminmqsutilc.jar

In Nexus it has the following values:
Repository -> raw-hosted
Group -> /mqsadmin/mqsutilclient/0.60
Name -> mqsadmin/mqsutilclient/0.60/mqsadminmqsutilc.jar
Most popular version -> {N/A}

I set up my repositories: 
```
repositories {
    maven {
        url = uri("https://nexus.mycompany.nml.com/repository/maven-central/")
    }
    ivy {
        url = uri("https://nexus.mycompany.com/repository/raw-hosted/")
        patternLayout{
            artifact("[organization]/[module]/[revision]/[artifact].[ext]")
            setM2compatible(true)
        }
        metadataSources{
            artifact()
        }
    }
}

```
and my dependencies:
```
dependencies {
    implementation("mqsadmin:mqsutilclient:0.60:mqsadminmqsutilc.jar")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")
}
```
and receive the following error message:
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find mqsadmin:mqsutilclient:0.60.
     Searched in the following locations:
       - https://nexus.mycompany.nml.com/repository/maven-central/mqsadmin/mqsutilclient/0.60/mqsutilclient-0.60.pom
       - https://nexus.mycompany.com/repository/raw-hosted/mqsadmin/mqsutilclient/0.60/mqsutilclient.jar
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
The problem is that if you compare the correct url to the incorrect url the [module] value has been substituted in for the [artifact} value.

```
    https://nexus.mycompany.com/repository/raw-hosted/mqsadmin/mqsutilclient/0.60/mqsutilclient.jar
    https://nexus.mycompany.com/repository/raw-hosted/mqsadmin/mqsutilclient/0.60/mqsadminmqsutilc.jar
```

I have found a workaround.  By hardcoding the name of the .jar into the patternLayout I can force gradle will resolve the url properly.

```
repositories {
    maven {
        url = uri("https://nexus.mycompany.nml.com/repository/maven-central/")
    }
    ivy {
        url = uri("https://nexus.mycompany.com/repository/raw-hosted/")
        patternLayout{
            artifact("[organization]/[module]/[revision]/mqsadminmqsutilc.jar")
            setM2compatible(true)
        }
        metadataSources{
            artifact()
        }
    }
}

dependencies {
    implementation("mqsadmin:mqsutilclient:0.60")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")
}
```

I am running gradle 7.5.1

**Comment by aSemy** [comment]
I have no idea where this is documented, if anywhere, but in the string dependency notation the extension is specified using an `@` symbol.

```
                         artifact            classifier
                             ↓                   ↓
implementation("mqsadmin:mqsutilclient:0.60:mqsadminmqsutilc@jar")
                   ↑                    ↑                     ↑ 
                 module              revision                ext  
```

There's also a 'map notation' for dependencies, which in the Kotlin DSL looks like this


```
  implementation(
    group = "mqsadmin",
    name = "mqsutilclient",
    version = "0.60",
    configuration = "mqsadminmqsutilc",
    ext = "jar",
    // classifier = ,
  )
```

I don't know how to set 'organization' in either. The documentation isn't clear to me.

**Comment by thomasgregoryNML** [comment]
Thank you aSemy.  Your post was helpful to me.  I'm new to gradle and I'm learning it as best I can from the documentations and the online training gradle offeres.  
Your mention of the "@" symbol pointed me to part of the documentation that I had skipped previously.  I've been reading and experimenting with this today and I don't have a "good" answer to the problem, but I have found a few different things that do work and I've learned a lot along the way.

There is one big issue that prevents that particular example you provided of implementation() from working.  It appears that "module" and "artifact" are the same value.  So trying to use :
`implementation("mqsadmin:mqsutilclient:0.60:mqsadminmqsutilc@jar")`
results in losing '**mqsadmin**' entirely and getting a URL of 
`...raw-hosted/mqsutilclient/mqsutilclient/0.60/mqsadminmqsutilc.jar`

When the implementation() method parses the string it assigns:
 -the first value to "group" 
 -the second value gets assigned to **two** variables, both "module" and "artifact."
 -the third value is assigned to "version"
 -the fourth value is assigned to "classifier"
 
 - One other thing that may interest you is that setting the metadataSources to artifact causes gradle to **automatically** append the extension for .jar.
`        metadataSources{
            artifact()
        }`
 will work with both 
     `implementation("mqsadmin:mqsutilclient:0.60:mqsadminmqsutilc@jar")`
and
    `implementation("mqsadmin:mqsutilclient:0.60:mqsadminmqsutilc")`
 
- Also, I found I could set the pattern layout with 'mqsutilclient' not being in square brackets
`            artifact("[organization]/mqsutilclient/[revision]/[module].[ext]")`
  and then use: 
   ` implementation("mqsadmin:mqsadminmqsutilc:0.60")`
   
   I didn't like that, but it led me to the solution I'm going to run with for now:
   `patternLayout{
   artifact("[organization]/[revision]/[module].[ext]")`
   and 
   `dependencies {
   implementation("mqsadmin/mqsutilclient:mqsadminmqsutilc:0.60")`
where _organization_ is "mqsadmin/mqsutilclient"

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Glad that you've found a solution because it's unlikely we could do fixes in this area.
