### ISSUE TITLE
File system watching causing super slow build  

### ISSUE THREAD

**Issue by doniwinata0309** [gradle/gradle#23426]
### Expected Behavior
File system watching should not significantly reduce build speed

### Current Behavior
Enabled file system watching sometimes slowing build significantly

### Context
Hi my local build slowing down significantly only when file system watching enable. These are task that 5x-10x longer to build:
1. kaptGenerateStubsKotlin
2. Clean build
3. Requesting remote gradle cache
4. PackageResources task

I am not sure if this happen on every build, but mostly after clean or full build (non incremental)
Do you have some advice to debug this issue ? or which profiler i should use to profile file system watching ?
Thank you in advance

### Your Environment
Android Gradle plugin 7.3.0
Gradle: 7.5.1
Kotlin: 1.7.21
Number of modules 300++
OS: MacOS M1

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.
