### ISSUE TITLE
Display a progress message when probing Java toolchains

### ISSUE THREAD

**Issue by melix** [gradle/gradle#23428]
### Expected Behavior

If you use Java toolchains, for example:

```gradle
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
```

Then Gradle will probe (and cache) the result of probing each of the recognized JVMs, but it won't indicate in the progress bar that it's doing so.

### Current Behavior

When you have a lot of JDKs installed in "standard" locations that Gradle can detect (e.g SDKMan!), probing the JVMs can take a few seconds, resulting in a build apparently "stuck" when it's actually probing the JVMs.

### Context

This scan shows a very basic app which doesn't use toolchains: https://scans.gradle.com/s/x335gxpgydqhg

Now add the following code snippet to your build script:

```gradle
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
```

In this [build scan](https://scans.gradle.com/s/ldafezebxmwzg) it only took 2s, but in my previous test it took up to 11s (I guess because there's a cache of probed JDKs living somewhere or that now I have my OS caches warm).

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by jbartok** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
