### ISSUE TITLE
Inconsistent latest gradle version displayed on scans.gradle.com

### ISSUE THREAD

**Issue by fejese** [gradle/gradle#2344]
### Expected Behavior
When running a scan with the latest Gradle version (4.0), then on the summary page it is correctly denoted. However, right now, as 3.5.1 was released after 4.0, on the performance suggestions page the green note saying that the latest version _is_ used mentions 3.5.1 even though 4.0 was used.

The same logic should be used to determine whether the latest version was used and to display the latest version, probably the former case is correct where the latest version is determined based on version rather than date.

### Current Behavior
Running a build scan with 4.0 make the suggestion mention that 3.5.1 was used.
It should display 4.0

### Context
Slightly confusing when checking the suggestions.

### Steps to Reproduce (for bugs)
https://scans.gradle.com/s/x4tferjcy2quq

### Your Environment
https://scans.gradle.com/s/x4tferjcy2quq

**Comment by etiennestuder** [comment]
Hi @fejese. Thanks for the report. We have already identified and fixed this issue. The fix will be available with the next production upgrade of scans.gradle.com

**Comment by fejese** [comment]
Cool! Quick reaction :)
