### ISSUE TITLE
Backport JUnit5 dynamic test logging bug fix

### ISSUE THREAD

**Issue by robmoore-i** [gradle/gradle#23458]
- See #23285

**Comment by robd** [comment]
Hi - is there a possibility that this will be backported to 7.x?

**Comment by robmoore-i** [comment]
It should be - that's what this issue is for. @ljacomet can you give an update here? Also why wasn't this included in the most recent 7.x patch?

**Comment by robd** [comment]
Hi - is there anything I can do to help get this backported to next 7.x release?

**Comment by ljacomet** [comment]
Items in the 7.x backport milestone were explicitly not in scope for Gradle 7.6.1.

The Gradle team still need to agree on plans for a Gradle 7.6.2 or 7.7 depending on the scope of the backports. This will not happen until Gradle 8.1 is released though.

**Comment by robd** [comment]
Ok thanks - let me know if there's anything I can do to help

**Comment by ljacomet** [comment]
Done in #25137
