### ISSUE TITLE
Kotlin set to level 1.4 in buildSrc in Gradle 8.0RC1

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23453]
### Expected Behavior

I am able to use Kotlin 1.5 features in `buildSrc/main/kotlin`

### Current Behavior

Opposite of expected

### Context

I have a Gradle project that I upgraded to 8.0RC1

```sh
gradle wrapper --gradle-version 8.0-rc-1
```

I have the following config in `./buildSrc/build.gradle.kts`

```kotlin
plugins {
  `kotlin-dsl`
}

dependencies {
  val kotlinVer = "1.8.0"
  implementation(platform(kotlin("bom", kotlinVer)))
  implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVer")
  implementation("org.jetbrains.kotlin:kotlin-serialization:$kotlinVer")
}

kotlin {
  jvmToolchain {
    languageVersion.set(JavaLanguageVersion.of("11"))
  }
}
```

Since Gradle 8 updated Kotlin to 1.8, I expect that I am able to use sealed interfaces, which requires a minimum of Kotlin level 1.5. 

```kotlin
// src/buildSrc/src/main/kotlin/test.kt

sealed interface X
```

However, I when I try to compile this code I get an error.

```text
> Task :buildSrc:compileKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings
8 actionable tasks: 1 executed, 7 up-to-date
e: /.../my-project/buildSrc/src/main/kotlin/buildsrc/test.kt: (5, 1): The feature "sealed interfaces" is only available since language version 1.5

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

I am able to workaround the issue by overriding the Kotlin language level using the `afterEvaluate {}` trick.

```kotlin
// buildSrc/build.gradle.kts

...


afterEvaluate {
  tasks.withType<KotlinCompile>().configureEach {
    kotlinOptions.languageVersion = "1.5"
  }
}
```

### Your Environment

Build scan URL:

**Comment by eskatos** [comment]
Hi @aSemy,

Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

----

I tried to reproduce and created: https://github.com/eskatos/gradle-23453

It works ok in this minimal reproducer: https://gradle.com/s/4ib4nxnqpqjmm

Please provide a reproducer showing the problem so we can take a closer look.

**Comment by aSemy** [comment]
I made a mistake when running the wrapper command, I missed an `=`

* wrong: `gradle wrapper --gradle-version 8.0-rc-1`
* right: `gradle wrapper --gradle-version=8.0-rc-1`

Why didn't the wrong command return an error? I would expect that because the value of `gradle-version` was missing, the task should throw an error.

**Comment by eskatos** [comment]
Well both `gradle wrapper --gradle-version 8.0-rc-1` and `gradle wrapper --gradle-version=8.0-rc-1` syntax work.
The problem must have been elsewhere.
