### ISSUE TITLE
Add warning and/or error when programmatic task registers inputs/outputs without name, path sensitivity

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#23456]
### Expected Behavior

Gradle should warn users that they should configure `path sensitivity`, `input names`, etc.

Sample:

```kotlin
tasks.register(taskName) {
    inputs.file("$baseDir/$style")
    inputs.file("$baseDir/$projectFile")
```

Gradle should warn the users that the inputs miss sensitivity and name in this case.
The users should update to something like

```kotlin
inputs.file("$baseDir/$style").withPathSensitivity(PathSensitivity.RELATIVE).withPropertyName("styleDir")
inputs.file("$baseDir/$projectFile").withPathSensitivity(PathSensitivity.RELATIVE).withPropertyName("projectDir")
```

A1) An alternative option would be adding structured block-like way to register inputs like:

```kotlin
input("styleDir") {
    file("$baseDir/$style")
    pathSensitivity(PathSensitivity.RELATIVE)
}
```

A2) or even add an API that takes both `propertyName` and `pathSensitivity` as mandatory parameters.
Note that `pathSensitivity` could default to `RELATIVE` in this case. The API would be new, so it would be not a problem to default it to RELATIVE.

```kotlin
// explicit form
inputFiles(propertyName = "styleDir", pathSensitivity = PathSensitivity.RELATIVE) {
    files(...)
}
inputFiles("styleDir") {
    files(...)
}
```

A3) Yet another possibility would be adding creator delegates:

```
task.register(...) {
    val styleDir by inputs.file(/*pathSensitivity=PathSensitivity.RELATIVE*/) {
        file("src/main/...")
    }
}
```

Then `styleDir` could produce `Property<...>` objects on get, so the users would be able to use them transparently within `doLast`, and it would be coherent with the way the other DSL objects can be created/retrieved (e.g. `val newTask by tasks.registering`)

It might play well with https://github.com/gradle/gradle/issues/21456.

A4) Yet another possibility is to add `@CheckReturnValue` annotation on top of `org.gradle.api.tasks.TaskInputFilePropertyBuilder` (or on top of `org.gradle.api.tasks.TaskInputs#file`)
Then IDEs would produce warnings that users should do something with the resulting `TaskInputFilePropertyBuilder`.
Unfortunately, there's no explicit `TaskInputFilePropertyBuilder.build()` method, so with current API the users won't be able to escape the warning "TaskInputFilePropertyBuilder is unused".

See https://youtrack.jetbrains.com/issue/IDEA-265263/Generalise-Stream-missing-terminal-operation-inspections-to-warn-about-missing-calls-to-terminal-operations-of-third-party#focus=Comments-27-4804303.0-0
See https://youtrack.jetbrains.com/issue/KTIJ-7061

### Current Behavior

Gradle provides no warnings, and it silently degrades the performance of Gradle Build Cache.

Frankly speaking, I incline there should be a way to make the build fail in case `name` and `sensitivity` are missing.

### Context

See https://github.com/apache/jmeter/pull/5757

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

**Comment by 0722845078** [comment]
My website has an error 404

**Comment by lptr** [comment]
Thanks for the detailed submission @vlsi.

The immediate plan to go with this is captured here: https://github.com/gradle/gradle/issues/10847. The idea is to enable the same validations we have for tasks declared via custom types for runtime-declared inputs.

As to whether we want to deprecate runtime properties declared without a name is not clear at this time. The reason is that unnamed properties are just one part of the problems with the runtime API and how `doLast {}` etc. work today. A bigger problem is that it is way too easy to prepend/append task actions that use undeclared inputs or produce undeclared outputs.

We might want to introduce a new notation instead that enforces inputs and outputs to be declared. That plan isn't fully formed yet, though.

**Comment by lptr** [comment]
Let's track this work as part of https://github.com/gradle/gradle/issues/10847. Whether we deprecate unnamed properties is a question we can investigate as part of that work, too.
