### ISSUE TITLE
The JAR of this class file belongs to container 'Gradle Dependencies' which does not allow modifications to source attachments on its entries.

### ISSUE THREAD

**Issue by yin-bp** [gradle/gradle#2345]
Use gradle 4.0 in eclipse. I debug a java programe ,when debug into a class in other dependence jar,can not open the source of the dependence class. The issue is:
The JAR of this class file belongs to container 'Gradle Dependencies' which does not allow modifications to source attachments on its entries.

**Comment by oehme** [comment]
Please provide a reproducible example project on GitHub. The message above is normal and no cause for concern, because Gradle automatically downloads sources for you. Make sure the library you're trying to debug actually provides sources.

**Comment by yin-bp** [comment]
ExampleProject:
https://github.com/bbossgroups/bboss-plugins
junit test java file:
/bboss-plugin-log4j/src/test/java/org/gradle/Invoke.java
`@Test
    public  void log() {
    	long interval = 0;
    	while(true) {
		
			log_invoke.info("日志信息");
		
			if(interval > 0) {
				try {
					Thread.currentThread().sleep(interval);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}

		}
    }	`
when debug  intoto [log_invoke.info("日志信息");] ,log4j classes can not be trace in.

**Comment by yin-bp** [comment]
Eclipse IDE for Java Developers

Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

Use Gradle 3.x,All is ok. But after upgrade to Gradle 4  ,debug into other classes can not work normal.

**Comment by yin-bp** [comment]
Eclipse IDE for Java Developers

Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

Use Gradle 3.x,All is ok. But after upgrade to Gradle 4  ,debug into other classes can not work normally.

Now I must to use IDEA,that's work normally.but I'm an eclipse lover.

**Comment by oehme** [comment]
I checked out that project and all sources are attached as expected. Did you try with a fresh worksapce?

**Comment by yin-bp** [comment]
I do this in a new workspace,but the problem is not resolved.

**Comment by oehme** [comment]
That's not the official Gradle plugin. Please use [Eclipse Buildship](https://projects.eclipse.org/projects/tools.buildship)
