### ISSUE TITLE
Groovy 4 Gradleception build runs OOM sometimes

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#23475]
This appears to be happening about 1% of the time: https://ge.gradle.org/scans/failures?search.tags=Gradleception%2CGroovy4&search.timeZoneId=America/New_York

### Expected Behavior

Gradleception build should be able to complete without running OOM.

### Current Behavior

The Gradleception build is able to build a distribution of Gradle with Groovy 4 (while using Groovy 3) and then build Gradle again while using Groovy 4.

It then fails to run tests with the second Gradle-with-Groovy-4 distribution. This makes sense because we run very few GroovyCompile tasks until this step. 

### Steps to Reproduce 

The last step in the build was disabled in: https://github.com/gradle/gradle/pull/23465
This will need to be reverted to see the failure again.

We should be able to reproduce this locally by:
- Building a distribution with the enableGroovy4 flag
- Compiling all Groovy code with the distribution from above 

No GroovyCompile daemons should persist across builds, so I suspect this may require the most expensive projects to all run on the same daemon?

### Your Environment
Build scan URL: https://ge.gradle.org/s/qpkewsx5ijdcm

**Comment by big-guy** [comment]
When looking at this again, let's pair on this - @big-guy

**Comment by octylFractal** [comment]
We've been running this for a month without this issue recurring as far as I can tell by looking at the DV failures page. Closing this since it looks fixed now.
