### ISSUE TITLE
[Bug][4.0] - "com.gradle.build-scan" 1.8 takes 5 seconds to configure

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#2347]
Adding the "com.gradle.build-scan" plugin, simply running `gradlew` takes 5 seconds to configure. Simply commenting/removing this plugin from the build, Gradle configures the project in 0 seconds.

### Expected Behavior
Configure in 0 to 1 seconds. Based on @oehme's talk https://summit.gradle.com/conference/palo_alto/2017/06/session?id=39265 (https://www.youtube.com/watch?v=TGUwevlaNNU).

### Current Behavior
Configure time is 5 seconds.

### Steps to Reproduce (for bugs)
git clone https://github.com/jaredsburrows/android-gif-example
cd android-gif-example
gradlew --profile

Output:
```
$ gradlew --scan

> Task :help

Welcome to Gradle 4.0.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>


BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed

Publishing build scan...
https://gradle.com/s/yvqy32v2awegi
```

### Your Environment
Gradle 4.0
 * Build scan URL: https://gradle.com/s/6deelh56dord6

**Comment by oehme** [comment]
You are being affected by this [MacOs Sierra bug](https://thoeni.io/post/macos-sierra-java/). We forwarded the problem to Apple and hope it will be patched out at some point. Until then the blog post linked above has a simple workaround.

**Comment by jaredsburrows** [comment]
@oehme I was going to simply wrap the "applying" the plugin with a property flag.

Something like:

```
buildscript {
  apply from: rootProject.file("gradle/versions.gradle")

  rootProject.ext.ci = rootProject.hasProperty("ci")

  repositories {
    maven { url "https://plugins.gradle.org/m2/" }
  }

  dependencies {
    if (rootProject.ext.profile) classpath plugs.buildScanPlugin
  }
}

if (rootProject.ext.profile) apply from: rootProject.file("gradle/scan.gradle")

```

This works well for all developer builds. Then when I want CI to run the scans or to profile, I can simple run `./gradlew --scan -Pci`.

**Comment by oehme** [comment]
Why do that instead of fixing your machine? The issue I linked above does not just affect Gradle, it slows down *any* tool trying to resolve localhost, like TomCat or Spring Boot.

**Comment by jaredsburrows** [comment]
@oehme I did read the blog post and the fix does work. I just needed to be able to toggle this on/off when working with a team of developers rather than asking them all to fix their machine based on that blog post. Thanks again.
