### ISSUE TITLE
Confusing Licensing Information in Gradle User Manual

### ISSUE THREAD

**Issue by JacobKfromIRC** [gradle/gradle#23471]
Hello, I'm looking to update [Gradle's entry in the Free Software
Directory](https://directory.fsf.org/wiki/Gradle), and I noticed some files in the user manual that have
confusing licensing information.

A couple of files in [the user guide](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/docs/userguide
) say that the "Gradle user manual
and DSL reference manual are licensed under Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International License." This
sentence appears in [licenses.adoc](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/licenses.adoc) and [userguide.adoc](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/userguide.adoc). Both of
these files have an invisible Apache license header ([example](https://raw.githubusercontent.com/gradle/gradle/master/subprojects/docs/src/docs/userguide/licenses.adoc)), but
not all of the files in the userguide directory have those headers. For
example, [extending-gradle/custom_gradle_types.adoc](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc) [does not have
that header](https://raw.githubusercontent.com/gradle/gradle/master/subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc).

Is some of the user guide dual-licensed, and are the files without
Apache headers CC-BY-NC-SA only? What was the intended license for the
documentation?

### Expected Behavior

The Gradle User Manual should have clear licensing information in which invisible headers match visible text. If the text is meant to be dual-licensed, both the invisible headers and visible text should have both licenses.

### Current Behavior

The Gradle User Manual has some files with invisible headers that do not match what the visible text says about licensing. As a result, the licensing of the Gradle User Manual is unclear.

### Context

I want to update Gradle's entry in the [Free Software Directory](https://directory.fsf.org/wiki/Main_Page), so that free software that uses Gradle as a dependency can be added to the directory more easily. For Gradle to be added to the Free Software Directory, the source repository should not contain nonfree documentation. For documentation to be free, it needs a free license, which would include Apache but not CC-BY-NC-SA. Resolving the documentation issue is a step towards updating Gradle's entry in the Free Software Directory.

### Steps to Reproduce 

Go to https://raw.githubusercontent.com/gradle/gradle/master/subprojects/docs/src/docs/userguide/licenses.adoc and see the Apache header at the top as well as the text towards the bottom that mentions "Creative Commons Attribution-NonCommercial-ShareAlike 4.0".

### Your Environment

Build scan URL: not applicable

It probably doesn't matter which web browser you use, but the licensing information appears in both Abrowser 108.0 and curl 7.68.0.

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This is a valid issue that we will address.
