### ISSUE TITLE
Display requested tasks and outcomes in logs

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2348]
### Expected Behavior
Log task headers for any tasks that match the requested task(s). 

### Current Behavior
Currently no outcomes are logged and no task headers don't show up unless the task had logs. 

### Context
Users have requested to know what the outcomes of requested tasks are.

**Comment by oehme** [comment]
That would be pretty verbose, I don't think we should do this. If I call `gradle clean` on a 100 project build, then I'll get 100 messages for each clean task. That negates a lot of the benefit of the new console.

The only time I care about this is when I debug an incremental build issue. That's what build scans or info logs are for. We could also put the outcomes in the profile report.

**Comment by w25r** [comment]
@oehme You're assuming that the only solution would be to print 100 messages.  There are other solutions that could be considered.  There are other ways to give feedback to the user

```console
>./gradlew clean
Executing task 'clean' for 100 projects
BUILD SUCCESSFUL
>
```

**Comment by oehme** [comment]
That wouldn't solve the use case described above. The reason users are asking for this is to know the outcome for each task.

**Comment by w25r** [comment]
My mistake.  I was confusing this with #2038.  Should this be renamed to "Display the outcome(s) of requested task(s)" to avoid confusion?  The are related, but not the same thing.

**Comment by eriwen** [comment]
Let's group this with #2038 and close as dupe
