### ISSUE TITLE
Add documentation for Kotlin DSL assignment overloads

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#23504]
We need some documentation in user manual.

**Comment by lptr** [comment]
Let's mention the new option on https://docs.gradle.org/current/userguide/lazy_configuration.html

**Comment by asodja** [comment]
We should also mention that enabling the assignment can cause build failures with allWarningsAsErrors, check here:
https://github.com/gradle/gradle/pull/23547#discussion_r1085340416

**Comment by asodja** [comment]
Merged to release branch.
