### ISSUE TITLE
Make Kotlin DSL assignment overload a stable feature

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#23503]
We need to:

- [x] release experimental version https://github.com/gradle/gradle-private/issues/3590: **Fixed in Gradle 8.1**
- [ ] remove incubating message
- [ ] upgrade samples to use new notation
	- [x] remove experimental message from Kotlin compiler plugin: **Fixed in Kotlin 1.8.20**
- [ ] upgrade to Kotlin 1.9 after [KT-56221](https://youtrack.jetbrains.com/issue/KT-56221) is fixed

Remaining IntelliJ issues:

- [x] [KTIJ-17783](https://youtrack.jetbrains.com/issue/KTIJ-17783) (related to [KT-56221](https://youtrack.jetbrains.com/issue/KT-56221)): **Fixed in Kotlin 1.8.20**
- [x] [KTIJ-24417](https://youtrack.jetbrains.com/issue/KTIJ-24417): **Fixed in Kotlin 1.8.20**
- [ ] [IDEA-311252](https://youtrack.jetbrains.com/issue/IDEA-311252)

---
cc: @gradle/bt-execution

**Comment by asodja** [comment]
Done with https://github.com/gradle/gradle/pull/25689
