### ISSUE TITLE
Gradle sync failed: unable to load class 'org.gradle.api.publication.maven.internal.MavenPomMetaInfoProvider'

### ISSUE THREAD

**Issue by teoprovenz82** [gradle/gradle#23505]
### Expected Behavior
Successfull Gradle Sync of my Cordova project

### Current Behavior
Gradle sync failed: Unable to load class 'org.gradle.api.publication.maven.internal.MavenPomMetaInfoProvider'.
This is an unexpected error. Please file a bug containing the idea.log file. (3 s 923 ms)

### Context
I'm trying to build my project after upgrade of Gradle

### Your Environment
[build.gradle.zip](https://github.com/gradle/gradle/files/10400931/build.gradle.zip)

[idea.log](https://github.com/gradle/gradle/files/10400890/idea.log)

Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
Runtime version: 11.0.11+0-b60-7772763 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.20-release-275-AS7442.40)

------------------------------------------------------------
Gradle 7.4.1
------------------------------------------------------------

Build time:   2022-03-09 15:04:47 UTC
Revision:     36dc52588e09b4b72f2010bc07599e0ee0434e2e

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_322 (Azul Systems, Inc. 25.322-b06)
OS:           Mac OS X 13.1 aarch64

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

https://docs.gradle.org/current/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin

Also, AGP 7 requires Gradle 7: https://developer.android.com/studio/releases/gradle-plugin
