### ISSUE TITLE
Provide a project isolation compatible way of listing subproject path

### ISSUE THREAD

**Issue by eygraber** [gradle/gradle#23515]
I'm currently using `subprojects.forEach { it.path }` in order to get a list of all subproject paths (use case is https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/844).

### Expected Behavior
Having an API I could use that doesn't violate project isolation.

### Current Behavior
The only sane way I could think of doing this is with `subprojects`, but this violates project isolation.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and prioritized by them.

**Comment by martinbonnin** [comment]
@eygraber I think this is supported with 8.8-rc1? ([changelog](https://docs.gradle.org/8.8-rc-1/release-notes.html))

```kotlin
gradle.lifecycle.beforeProject { project ->
    project.isolated.path
}
```

**Comment by eygraber** [comment]
Yes I believe it is 😁

**Comment by alllex** [comment]
The original use case with accessing subprojects paths with `subprojects { it.path }` has been supported in Isolated Projects for a while now (no need for the most recent Gradle version).

There are also no immediate plans to stop supporting this existing API in the IP mode. The violation of isolation normally happens only when some project accesses a _mutable_ state of another project. As long as this is not happening, Gradle tries to keep existing APIs functional.

Thus, getting a list of projects via something like `subprojects` is safe. So as accessing the majority of the immutable properties of the `Project`, such as `path`, `projectDir`, etc. There are more methods described in the [docs](https://docs.gradle.org/8.7/userguide/isolated_projects.html#build_logic_constraints).

In Gradle 8.8, we also introduced the `IsolatedProject` type, which explicitly provides access to safe information. It can be used in build scripts in conjunction with old school callbacks such as `subprojects` and `allprojects`.
```
subprojects { it.isolated.path }
```
