### ISSUE TITLE
JVM Test Suite should create a JaCoCo task

### ISSUE THREAD

**Issue by esfomeado** [gradle/gradle#23542]
When applying the `jvm-test-suite` to a project I expect a JaCoCo report task to be created for the new test suite. 

The [Test Sets plugin](https://github.com/unbroken-dome/gradle-testsets-plugin/blob/v4.0.0/src/main/kotlin/org/unbrokendome/gradle/plugins/testsets/TestSetsPlugin.kt#L184) does this and it's really useful.

I'm aware that the `jacoco-report-aggregation` plugin exists but it aggregates the reports and in my case I don't want that to happen so I have to manually create a task that extends `JacocoReport` to generate a report per module.

### Expected Behavior
A new `jacocoReport` task is created per each new test suite.

### Current Behavior
If I don't want to aggregate the reports I have to manually create a new task.

### Context
I want to have a `jacocoReport` per each test suite without aggregating the results at the end.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

**Comment by jvandort** [comment]
Is there a reason you can't just apply `jacoco-report-aggregation`, which creates a report task per test-suite, and ignore the aggregating task?
