### ISSUE TITLE
Invalid artifactId is used in pluginMarkerMaven POM

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#23551]
### Context
I have a certain project structure on the file system, this does not match one to one with artifact names generated in `mavenCentral()`. I think this is quite usual setup. I recently wanted to enable marker publication, but the markers are not working, because their POM contains invalid artifact IDs which point to the directory structure rather than the actual artifact ID under which the project is published. Example below will make this very clear.

### Steps to Reproduce
1. Clone https://github.com/TWiStErRob/repros/tree/master/gradle/gradlePluginMarker-earlyArtifactId
2. `gradlew publishToMavenLocal`  
   (or more specifically `gradlew generatePomFileForPluginMavenPublication generatePomFileForMyPluginPluginMarkerMavenPublication`)

<details><summary>Observe the output POM files</summary>

Observe these two files:
 * `published/build/publications/pluginMaven/pom-default.xml`
 * `published/build/publications/myPluginPluginMarkerMaven/pom-default.xml`

Or alternatively the published artifacts in your `~/.m2` (`mavenLocal()`) folder:
 * `~/.m2/com/example/different-name/1.2.3/different-name-1.2.3.pom`
 * `~/.m2/com/example/my-plugin/com.example.my-plugin.gradle.plugin/1.2.3/com.example.my-plugin.gradle.plugin-1.2.3.pom`

Note: the name and location of these files are all correct based on the setup, which is in short:
```kotlin
group = "com.example"
version = "1.2.3"
afterEvaluate {
    publishing.publications.named<MavenPublication>("pluginMaven").configure { artifactId = "different-name" }
}
gradlePlugin.plugins.create("myPlugin") { id = "com.example.my-plugin" }
```
</details>

### Current Behavior
This is the marker POM.
The referenced artifact doesn't exists, it assumes that the folder name is the same as the published artifact ID.
```xml
<project>
  <groupId>com.example.my-plugin</groupId>
  <artifactId>com.example.my-plugin.gradle.plugin</artifactId>
  <version>1.2.3</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>published</artifactId> <!-- ................... PROBLEM HERE -->
      <version>1.2.3</version>
    </dependency>
  </dependencies>
</project>
```

### Expected Behavior
```xml
<project>
  <groupId>com.example.my-plugin</groupId>
  <artifactId>com.example.my-plugin.gradle.plugin</artifactId>
  <version>1.2.3</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>different-name</artifactId> <!-- ................... CORRECT HERE -->
      <version>1.2.3</version>
    </dependency>
  </dependencies>
</project>
```

### Your Environment

Build scan URL: don't think it's relevant given the details below

### Further details
I actually found the problem here:
`org.gradle.plugin.devel.plugins.MavenPluginPublishPlugin#createMavenMarkerPublication`
 * This method reads the coordinates into local variables `pluginGroupId`, `pluginArtifactId` and `pluginVersion`.
 * Then afterEvaluate in my build.gradle executes
 * Then `generatePomFileFor...Publication` task executes the `getPom().withXml` block
 * Which reads the cached local variables

I'm forced to use `afterEvaluate` in build.gradle because of the `afterEvaluate` in `MavenPluginPublishPlugin#apply`.

There's literally no way to correctly configure this whether using the `plugins` block or `apply(plugin =`.

Bar rewriting the two plugins with full `Property<T>` support, the solution would be to capture the `coordinates` variable in the `Action<XmlProvider>` block and read the group/artifact/version lazily during task execution.

### Workaround
The only thing I can do is to either re-do the work of `java-gradle-plugin` (`MavenPluginPublishPlugin`) by registering the publication myself or by generating the marker myself. Neither of these is acceptable given the complexity and all the laziness work that has been done in Gradle over the last years to solve exactly these kinds of problems.

**Comment by TWiStErRob** [comment]
I managed to work around it with this beauty in the example project:
```kotlin
named<MavenPublication>("myPluginPluginMarkerMaven").configure {
	pom.withXml {
		asElement()
			.getElementsByTagName("dependencies").item(0)
			.let { it as org.w3c.dom.Element }
			.getElementsByTagName("dependency").item(0)
			.let { it as org.w3c.dom.Element }
			.getElementsByTagName("artifactId").item(0)
			.textContent = "different-name"
	}
}
```
I'm curious if this scales to the real project where I have many plugins.

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

***

If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by eirnym** [comment]
@ov7a the fix PR for this issue has been supplied. Is there any chance to review it soon?
