### ISSUE TITLE
failing java toolchain download should have a more detailed error message.

### ISSUE THREAD

**Issue by reinsch82** [gradle/gradle#23563]
If [this test](https://github.com/gradle/gradle/blob/b867464ee426c2c2564bedeb5a42983a39db1ab5/subprojects/soak/src/integTest/groovy/org/gradle/jvm/toolchain/JavaToolchainDownloadSoakTest.groovy#L52) is executed on an m1 mac with version 14 the error message is
```
Execution failed for task ':compileJava'.
> Error while evaluating property 'javaCompiler' of task ':compileJava'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=14, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.1-20230116230000+0000/userguide/toolchains.html#sec:auto_detection) and the configured toolchain download repositories aren't able to provide a match either (see https://docs.gradle.org/8.1-20230116230000+0000/userguide/toolchains.html#sub:download_repositories).
```

### Expected Behavior

The error message shows all relevant information to understand what is missing.
in this case the architecture is missing. This is the reason foojay api cannot provide a jdk for the platform.

### Current Behavior
only implementation, languageversion and vendor is shown.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by artemptushkin** [comment]
what to do in case of this error? how to troubleshoot? It's not clear, I have a JDK inside my image but it fails still

**Comment by jbartok** [comment]
> what to do in case of this error? how to troubleshoot? It's not clear, I have a JDK inside my image but it fails still

In order for us to be able to help pls. open an issue containing a reproducer of your problem.

**Comment by mauritssilvis** [comment]
For those who encounter the above error and don't know what to do: The readme of the [Foojay toolchain plugin](https://github.com/gradle/foojay-toolchains) shows which options for configuring you have:

- **Either** include the `foojay-resolver-convention` plugin in your `settings.gradle.kts` file:

        plugins {
            id("org.gradle.toolchains.foojay-resolver-convention") version "0.4.0"
        }

- **Or** include **and** configure the `foojay-resolver` plugin in your `settings.gradle.kts` file:

        plugins {
            id("org.gradle.toolchains.foojay-resolver") version "0.4.0"
        }

        toolchainManagement {
            jvm {
                javaRepositories {
                    repository("foojay") {
                        resolverClass.set(org.gradle.toolchains.foojay.FoojayToolchainResolver::class.java)
                    }
                }
            }
        }

If you use the `foojay-resolver` plugin without configuring it, you may see the failure of the OP, as I experienced in [this issue](#24591).
