### ISSUE TITLE
option to install a  x86-64 JDK on an m1 mac because it can run with Rosetta 2

### ISSUE THREAD

**Issue by reinsch82** [gradle/gradle#23569]
When using the toolchain declaration and there is no JDK for the aarch64 architecture available on a mac. there should be an option to also allow usage of a x86-64 JDK since [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2) allows it to execute.

### Expected Behavior
It could be a command line option `--allow-x86-64` or an option in the toolchain declaration

### Current Behavior
older JDKs can't be used on m1 macs

**Comment by ljacomet** [comment]
We will not do this in Gradle itself, as Gradle will happily use a detected compatible JVM.

However the [Foojay plugin](https://github.com/gradle/foojay-toolchains/issues) could indeed offer this option.
