### ISSUE TITLE
Adding to eclipse.classpath.testSourceSets discards initial testSourceSets

### ISSUE THREAD

**Issue by lennartfricke** [gradle/gradle#23571]
Adding a testSourceSets to the eclipse classpath via ```testSourceSets``` discards the source sets that are added by default by gradle.
This is because the default is applied as convention and thus only used if nothing is done to testSourceSets.

This leads to the following problem: When applying custom plugins it is difficult to add to the testSourceSets.
See code below and expected behaviour.

```gradle
class DevelPlugin implements Plugin<Project> {
  void apply(Project project) {
     def devel = project.sourceSets.create('developmentTools')
     project.pluginManager.withPlugin('eclipse') {
       project.eclipse.classpath {
         testSourceSets = testSourceSets.get() + [devel]
       }
     }
  }
}


apply plugin: 'eclipse'
apply plugin: 'java-library'
apply plugin: DevelPlugin
apply plugin: 'java-test-fixtures'

println eclipse.classpath.testSourceSets.get()
```

### Expected Behavior
testSourceSets should contain 'test', 'testFixtures' and 'developmentTools' no matter what the order of plugin application is.

### Current Behavior
testSourceSets onyl contains 'test' and 'developmentTools'.
If DevelPlugin is applied after 'java-test-fixtures' all are present.

### Proposed Fix
Create an initial set of testSourceSets to add to and do not use a convention for this.

**Comment by ljacomet** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

---

Note that another workaround would be to add your entry to the convention as well

**Comment by lennartfricke** [comment]
Just a question about the workaround. How can I access the convention of a property? The backing collection of this convention is private to the eclipse plugin.

**Comment by ljacomet** [comment]
You should be able to do something like the following:
`testSourceSets.convention(testSourceSets.get() + [devel])`
