### ISSUE TITLE
Include pom.properties in jars by default

### ISSUE THREAD

**Issue by candrews** [gradle/gradle#23578]
### Expected Behavior
When Gradle creates a jar, it should include a `pom.properties` [Maven Descriptor](https://maven.apache.org/shared/maven-archiver/) file in the produced jar by default just as the Maven Archiver does. The file should be located in the jar at `META-INF/maven/${groupId}/${artifactId}/pom.properties`. The contents of this file should be the [maven coordinates](https://maven.apache.org/pom.html#Maven_Coordinates), like this (example for [Spring Boot 3.0.1](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot/3.0.1)):
```
groupId=org.springframework.boot
artifactId=spring-boot
version=3.0.1
```

### Current Behavior
Gradle produced jars do not include `pom.properties`.

### Context
Currently, given a jar produced by Gradle with no other information, there's no way to tell where to find it in Maven. It would be really nice to be able to open the jar and tell what the jar's Maven coordinates are, just as one can do with jar's produced by Maven itself.

This functionality has been previously requested, but that request wasn't answered: https://github.com/gradle/gradle/issues/1278 It's currently possible for Gradle projects to include `pom.properties` in their jars as described in this issue, but its manual - each project must do that itself. This problem would much better be solved globally, by default, for all Gradle projects.

There is further indication of demand for this functionality as demonstrated by the [org.kordamp.gradle.minpom](https://kordamp.org/kordamp-gradle-plugins/#_org_kordamp_gradle_bom) plugin too.

Security tools (such as Trivy) often encounter jars with no other information (no `pom.xml` or `build.gradle` or anything else) when scanning docker images or file systems. The security tool needs to know the Maven coordinates of the jar so it can search for vulnerabilities related to it. Today, it's very difficult for tools to perform this task; Maven Central's search service has to be used to search for the jar by its hash, and that service isn't completely reliable nor is it available offline, see https://github.com/aquasecurity/trivy/issues/3421. By including `pom.properties` in the jar, tools can trivially easily discover the Maven coordinates and perform effective, accurate security analysis, avoiding complex and unreliable solutions as as those being explored in https://github.com/aquasecurity/trivy/issues/3427.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

**Comment by candrews** [comment]
@melix why the :-1: ?

**Comment by jvandort** [comment]
Ideally, we'd want a solution that was Maven-independent. Gradle artifacts have extra information which cannot be encoded in the maven context, meaning that some published jars cannot be located by a `pom.properties` file.  We would likely prefer to standardize on a more general solution, which would require collaboration with other organizations in the ecosystem. 

For now, we do not plan to support writing `pom.properties` files in published Jars. Something like this may be better implemented in a community plugin.
