### ISSUE TITLE
Mark SourceDirectorySet.outputDir as Incubating

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#2360]
This API is new in 4.0, but wasn't marked `@Incubating`. This is even worse since this API is definitely wrong, so we want to change it. We should mark it incubating for 4.0.1, so no one starts depending on it.

**Comment by big-guy** [comment]
I don't think we should deprecate an existing API without providing another stable API (if we think we should support the use case) to move to.  That was the thinking for not making  `SourceDirectorySet.outputDir` incubating (right or wrong).

**Comment by oehme** [comment]
Alternatively we should fix the design, but that might be a tall order for a hotfix release. As discussed with @wolfs, this should go on `SourceSetOutput`, just like the methods for resource directories.

**Comment by jjohannes** [comment]
@wolfs @oehme can one of you make the change, reflecting what you two discussed, to the hotfix branch: https://github.com/gradle/gradle/commits/release_4.0.1 (or prepare a PR based on the branch). Thanks!

**Comment by oehme** [comment]
I've marked it as [incubating](https://github.com/gradle/gradle/commit/106503ff99fb1185f47b5cf2cc401788f73004ef) and changed the [deprecation message](https://github.com/gradle/gradle/commit/51de04a99087c4caa85fffcdd21fda4340b214b2) to point to a non-incubating API (telling users to change the corresponding compile tasks's output dir).

**Comment by jjohannes** [comment]
Thanks @oehme!

Any remaining concerns @big-guy @wolfs?

Otherwise I assume this is good to go.

**Comment by wolfs** [comment]
Good to go from my side.
