### ISSUE TITLE
Dependency added in compileOnly gets also added in jar file after build which should not be there

### ISSUE THREAD

**Issue by akash-saha-jmh** [gradle/gradle#23608]
I am using gradle with groovy, and inside dependecies I have only added this,
dependencies {
    compileOnly "org.yaml:snakeyaml"
..............}
run command: gradle clean war
but after exploding war I can see the snakeyaml jar

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
