### ISSUE TITLE
Duplicate dependency artifacts in ArtifactCollection

### ISSUE THREAD

**Issue by hfmehmed** [gradle/gradle#23604]
I have got a simple gradle project with build.gradle file:

```
repositories {
        google()
        mavenCentral()
}

configurations {
	customConfig
}

dependencies {
	 customConfig 'androidx.core:core:1.7.0'
	 customConfig "androidx.appcompat:appcompat:1.5.1"
}
println "=========================================="
println "files of incoming dependencies : " + configurations.customConfig.incoming.files.size()
println "=========================================="

println "artifacts of incoming dependencies : " + configurations.customConfig.incoming.artifacts.size()
configurations.customConfig.incoming.artifacts.forEach {
    println it.variant
}
```

The output when I build is:
<pre>
> Configure project :
==========================================
files of incoming dependencies : 42
==========================================
artifacts of incoming dependencies : 45
androidx.appcompat:appcompat-resources:1.5.1 variant releaseVariantReleaseRuntimePublication
androidx.appcompat:appcompat:1.5.1 variant releaseVariantReleaseRuntimePublication
androidx.fragment:fragment:1.3.6 variant releaseRuntimePublication
androidx.activity:activity:1.5.1 variant releaseVariantReleaseRuntimePublication
androidx.loader:loader:1.0.0 configuration default
<b>androidx.lifecycle:lifecycle-viewmodel:2.5.1 variant releaseVariantReleaseRuntimePublication</b>
<b>androidx.lifecycle:lifecycle-viewmodel:2.5.1</b>
androidx.lifecycle:lifecycle-viewmodel-savedstate:2.5.1 variant releaseVariantReleaseRuntimePublication
androidx.core:core-ktx:1.8.0 variant releaseVariantReleaseRuntimePublication
androidx.drawerlayout:drawerlayout:1.0.0 configuration default
androidx.emoji2:emoji2-views-helper:1.2.0 variant releaseVariantReleaseRuntimePublication
androidx.emoji2:emoji2:1.2.0 variant releaseVariantReleaseRuntimePublication
androidx.vectordrawable:vectordrawable-animated:1.1.0 configuration default
androidx.vectordrawable:vectordrawable:1.1.0 configuration default
androidx.viewpager:viewpager:1.0.0 configuration default
androidx.customview:customview:1.0.0
<b>androidx.core:core:1.8.0 variant releaseVariantReleaseRuntimePublication</b>
<b>androidx.core:core:1.8.0</b>
androidx.cursoradapter:cursoradapter:1.0.0 configuration default
androidx.lifecycle:lifecycle-process:2.4.1 variant releaseVariantReleaseRuntimePublication
androidx.lifecycle:lifecycle-runtime:2.5.1 variant releaseVariantReleaseRuntimePublication
androidx.resourceinspection:resourceinspection-annotation:1.0.1 variant runtimeElements
androidx.savedstate:savedstate:1.2.0 variant releaseVariantReleaseRuntimePublication
androidx.concurrent:concurrent-futures:1.0.0 configuration default
androidx.versionedparcelable:versionedparcelable:1.1.1 configuration default
androidx.startup:startup-runtime:1.1.1 variant releaseVariantReleaseRuntimePublication
androidx.tracing:tracing:1.0.0 variant releaseRuntimePublication
androidx.collection:collection:1.1.0 configuration default
androidx.lifecycle:lifecycle-livedata:2.0.0
<b>androidx.lifecycle:lifecycle-livedata-core:2.5.1 variant releaseVariantReleaseRuntimePublication</b>
<b>androidx.lifecycle:lifecycle-livedata-core:2.5.1</b>
androidx.arch.core:core-runtime:2.1.0 configuration default
androidx.arch.core:core-common:2.1.0 configuration default
androidx.lifecycle:lifecycle-common:2.5.1 variant runtimeElements
androidx.interpolator:interpolator:1.0.0
androidx.annotation:annotation:1.3.0 variant runtimeElements
androidx.annotation:annotation-experimental:1.1.0 variant releaseRuntimePublication
org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.1 variant runtimeElements
org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.1 variant jvmRuntimeElements-published
org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.0 configuration default
org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.0 configuration default
org.jetbrains.kotlin:kotlin-stdlib:1.7.10 configuration default
org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10 configuration default
org.jetbrains:annotations:13.0 configuration default
com.google.guava:listenablefuture:1.0 configuration default
</pre>

As seen there are 3 duplicate artifacts resolved via different variants which point to the same file.

What is the reason for this behaviour and is it intended?

Gradle version: Tested on version from 7.2 up to 8.0-rc01 and all of them have this behaviour

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

You should not resolve dependencies without not specifying attributes (see [here](https://docs.gradle.org/current/userguide/variant_attributes.html)).
The lack of Android plugins can also be a problem. 
One thing that we should improve in the future is listing artifacts as files, but that's covered by other issues.
