### ISSUE TITLE
Can't create same name version catalog aliases in the included build with its own version catalog file

### ISSUE THREAD

**Issue by borisf** [gradle/gradle#23613]
I have a [project.zip](https://github.com/gradle/gradle/files/10477903/project.zip) with an Android app and included build (convention plugin). The included build has its own version catalog file.

### Expected Behavior
In the settings.gradle.kts of the included build, I would expect the following alias catalog definition:

```
 versionCatalogs {
        create("libs") {
            from(files("gradle/libs.versions.toml"))
        }
    }
```

### Current Behavior
I see the following error
```
FAILURE: Build failed with an exception.

* Where:
Build file '/XXXX/perVariantManifestPlaceholder/build.gradle.kts' line: 17

* What went wrong:
Error resolving plugin [id: 'com.android.application', version: '8.1.0-alpha01', apply: false]
> Invalid catalog definition:
    - Problem: In version catalog libs, you can only call the 'from' method a single time.
      
```

I guess this is related to issue that both main project and ncluded build project can't have the same alias (libs) when using different version catalog files. 

Workaround

```
 versionCatalogs {
        create("buildlibs") {
            from(files("gradle/libs.versions.toml"))
        }
    }
```

**Comment by jbartok** [comment]
If you don't create the `libs` in the included build, it works.
You should not attempt to load the default toml file into the default catalog. This is done by Gradle.

**Comment by borisf** [comment]
After talking to the team, here are more clarifications if someone would want to implement included build with version catalogs: 

1. It is recommended to have a catalog file per included build, otherwise the build would not work in isolation
2. If you have a version catalog file in your included build, you can access the catalog directly as you do in your main project
3. If the included build is always included, you can have a single catalog in `<rootbuild>/gradle/libs.versions.toml`

And load it from your included build `settings.gradle.kts`

```
versionCatalogs {
    create("libs") {
        from(files("../gradle/libs.versions.toml")) // as many .. as required depending on depth
    }
}
```

**Comment by swpalmer-cl** [comment]
@borisf  How do you get this to work?

> It is recommended to have a catalog file per included build, otherwise the build would not work in isolation

The included build always tries to resolve things from the main project's version catalog and since the main project knows nothing of the included build's needs the references aren't resolved.

In other words, it seems to behave as if you always have:
```
versionCatalogs {
    create("libs") {
        from(files("../gradle/libs.versions.toml")) // as many .. as required depending on depth
    }
}
```

But I almost never want that.

Basically #2 above is false.  When the project is an included build version catalogs break. The included build's catalog becomes invisible to that project and is replaced by the main project's catalog.
