### ISSUE TITLE
Java toolchain auto-detection on linux should look in /usr/local/java

### ISSUE THREAD

**Issue by pwagland** [gradle/gradle#23620]
On Linux, when installing a local java tool chain, not using one of the package managers, it is customary to install it in `/usr/local`, and usually, for Java, in `/usr/local/java`. It would be good if this location could be added to https://github.com/gradle/gradle/blob/master/subprojects/jvm-services/src/main/java/org/gradle/jvm/toolchain/internal/LinuxInstallationSupplier.java#L36.

### Expected Behavior
Gradle should find JVM installations under /usr/local/java/*

### Current Behavior
It doesn't.

### Context
On our linux boxes we have java installed under `/usr/local/java`, and these are not found by gradle. We can work around this by putting in "installation files" for one of the "approved" package managers.

**Comment by kurahaupo** [comment]
Updating a java source file to locate the java compiler leaves a chicken-and-egg problem: you can't use the updated information until after you've compiled groovy using it.

By default `gradlew`  looks for a Java installation in `$JAVA_HOME`, and if that is not set, it looks for `java` using `$PATH`, so either of these should resolve this problem:
* `export JAVA_HOME=/usr/local/java`
* `PATH+=:/usr/local/java/bin`

That said, the patch you're asking for is quite trivial, so it's a good example to learn about how to make a pull request on Github.

**Comment by ljacomet** [comment]
@pwagland Do you have resources that show that `/usr/local/java` is a customary location?

**Comment by ega4l** [comment]
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html here you can find why and what for /usr/local is used.
means if you install java from a tarball "best practices" would be to install it in /usr/local or in /opt so it doesn't conflict with any packages installed from distro-repository.
@kurahaupo we use Java-toolchain in our projects and need two different java versions for our projects, so setting JAVA_HOME is set anyway and doesn't resolve the problem
