### ISSUE TITLE
CompileOnly dependency gets added to final build jar though it should not be added as it is as a replacement to provided scope as per Gradle official documentation.

### ISSUE THREAD

**Issue by akash-saha-jmh** [gradle/gradle#23648]
I am using gradle with groovy, and inside dependencies I have only added this,
dependencies {
compileOnly "org.yaml:snakeyaml"
..............}
run command: gradle clean war
but after exploding war I can see the snakeyaml jar, though it should not be added as it is as a replacement to provided scope as per Gradle official documentation.

**Comment by ljacomet** [comment]
This issue will be closed as a duplicate of

* #23608

---

Re-opening an issue without adding more information is not going to help.
