### ISSUE TITLE
Bug in Gradle Logger with "\r" at the end

### ISSUE THREAD

**Issue by scheruga** [gradle/gradle#2364]
When the following gradle build file is executed, it fails with 
String index out of range: -1

Content if one liner build.gradle file:
getLogger().quiet("test\r");

**Comment by stovocor** [comment]
Please specify your Gradle version and build environment. I cannot reproduce this with Gradle 3.5 or 4.0 on Arch Linux.

**Comment by bmuschko** [comment]
I cannot reproduce the issue with 4.0 either. I am going to close the issue as we haven't heard back in almost a week.

**Comment by scheruga** [comment]
Sorry I missed your first answer.
I am using the following versions
D:\x>gr -version

------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Windows 7 6.1 amd64

______________________________________________________________________________
Everything works fine for me under Win10 64bit

**Comment by lacasseio** [comment]
@bmuschko This is indeed a problem that is fixed by https://github.com/gradle/gradle/pull/2291. The reason I haven't merge the PR is I may have found another problem and wanted to confirm it wasn't caused by the PR. I will find some time to merge and fix the issue hopefully soonish.

**Comment by bmuschko** [comment]
@lacasseio OK, thanks. It seems like this issue here is a duplicate of https://github.com/gradle/gradle/pull/2291.
