### ISSUE TITLE
Can't use extension function defined on settings.kts.gradle inside pluginManagement block

### ISSUE THREAD

**Issue by fabiorosa-sn** [gradle/gradle#23659]
Currently we can centralize the repository declaration on settings.gradle.kts using dependencyResolutionManagement{}
for libs and pluginManagement{} for plugins. 
Defining a custom maven repository could demand some extra boiler plate do handle authentication.
To make things cleaner, we would like to extract the boiler plate to a function inside settings.gradle.kts that could be used inside both dependencyResolutionManagement{} and  pluginManagement{}.

### Expected Behavior
I should be able to use a function defined inside my kts script inside both dependencyResolutionManagement{} and pluginManagement{}

### Current Behavior
The function is available on at  dependencyResolutionManagement{} , but not at pluginManagement{}

### Context
Its expected to be able to factor out repetitive code that can be reused on different parts of the kts script, to avoid boilerplate copy paste

### Steps to Reproduce 
```
rootProject.name = "my-project"

fun RepositoryHandler.myAuthenticatedArtifactory(): MavenArtifactRepository =
    maven {
        url = uri("<MY_ARTIFACTORY_URL>")
        val artifactoryTokenUser: String? by settings
        val artifactoryTokenEnv = System.getenv("ARTIFACTORY_ACCESS_TOKEN")
        (artifactoryTokenEnv ?: artifactoryTokenUser)?.let { artifactoryToken ->
            credentials(HttpHeaderCredentials::class) {
                name = "Authorization"
                value = "Bearer $artifactoryToken"
            }
            authentication { create<HttpHeaderAuthentication>("header") }
        } ?: throw RuntimeException("⚠️⚠️⚠️️NO ARTIFACTORY TOKEN FOUND⚠️⚠️⚠️")
    }

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
        myAuthenticatedArtifactory()
    }
}

pluginManagement {
    repositories {
        gradlePluginPortal()
        myAuthenticatedArtifactory()
    }
}
```
### Your Environment
MacOs Ventura
Gradle: 7.6

**Comment by ljacomet** [comment]
What you are trying to achieve is not possible because Gradle does a special evaluation, in isolation of `pluginManagement` since it needs to be computed even before plugins are applied to `Settings`.

You might be able to extract this into an init script, although I have not tested it and it may still not work.

This is not a limitation we are planning on lifting at this point.
