### ISSUE TITLE
Dependency verification documentation snippets should reference XSD

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#23662]
When getting started with dependency verification, the [docs](https://docs.gradle.org/current/userguide/dependency_verification.html) suggest creating `gradle/verification-metadata.xml` but do not mention the XML schema.

### Expected Behavior

For a better editing experience, the XML snippets should reference the XML schema:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<verification-metadata xmlns="https://schema.gradle.org/dependency-verification" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://schema.gradle.org/dependency-verification https://schema.gradle.org/dependency-verification/dependency-verification-1.1.xsd">
   <configuration>
      <verify-signatures>true</verify-signatures>
   </configuration>
</verification-metadata>
```

### Current Behavior

Currently, the XML schema is not referenced:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<verification-metadata>
   <configuration>
      <verify-signatures>true</verify-signatures>
   </configuration>
</verification-metadata>
```

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

**Comment by ljacomet** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
