### ISSUE TITLE
JavaVersion.current() Incorrect For Java Toolchain

### ISSUE THREAD

**Issue by austinarbor** [gradle/gradle#23670]
### Expected Behavior

When evaluating JavaVersion.current(), I would expect the jdk version of the toolchain executing the task(s) to be returned

### Current Behavior

When evaluating JavaVersion.current(), it returns the version of the jdk which invoked `gradle`, rather than the version of the jdk that is specified by the java toolchain
### Context

I am trying to get the java version from the toolchain currently compiling the code

### Steps to Reproduce 

build.gradle:
```groovy
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

compileJava {
    doFirst {
        print("Java Version: " + JavaVersion.current())
    }
}
```

Run `./gradlew build` with any jdk in your environment other than 11, and note that it will print that version instead of 11

### Your Environment
gradle 7.6

Build scan URL:

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

`JavaVersion.current()` returns the JVM running that code.
`doFirst {}` is executed in the Gradle JVM, hence the result you get.

The configured toolchain is used to fork a new JVM for the actual Java compilation.

In your build script you can query what is the configured toolchain.

```groovy
compileJava {
    doFirst {
        print("Java Toolchain Version: " + javaCompiler.get().metadata.languageVersion)
    }
}
```
