### ISSUE TITLE
Order of tasks in JVMTestSuite plugin is not kept when shouldRunAfter is specified

### ISSUE THREAD

**Issue by Zordid** [gradle/gradle#23678]
I use the JVMTestSuite plugin to define integration tests. Those tests must run after the normal unit tests have been executed, not the other way around.

So, I defined this:
```
testing {
    suites {
        val jUnitVersion = "5.9.2"
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter(jUnitVersion)
        }

        val integrationTest by registering(JvmTestSuite::class)
        integrationTest {
            dependencies {
                implementation(project)
            }

            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(test)
                    }
                }
            }
        }
    }
}
```

### Expected Behavior
When I do a `./gradlew :build`, I expect FIRST the unit test and after that the integration tests task to be executed.

### Current Behavior
The integrationTest task is always executed first...

### Context
I see this in Gradle 7.5.1 and 7.6, the "shouldRunAfter" seems to be ignored. "mustRunAfter" is not correct, because that forces integration tests to be executed even if you just want test...

### Your Environment

Build scan URL:
https://scans.gradle.com/s/v77ms75oxijm6/timeline

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

----

`shouldRunAfter` allows Gradle to run them in a different order
See https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:ordering_tasks

If your use case is stricter then `mustRunAfter` would be better.

`mustRunAfter` doesn't mandate that the first task is always executed. `finalizedBy` is about that.
