### ISSUE TITLE
sourceCompatibility does not work as expected

### ISSUE THREAD

**Issue by jie-huang** [gradle/gradle#23675]
### Expected Behavior
```
java {
  sourceCompatibility = JavaVersion.VERSION_11
}
```
It should use only Java 11 features to compile.

### Current Behavior
When using new features, e.g. a Java API in new version, it does not report error.

### Context
When build a java lib, using sourceCompatibility does not detect the version compatibility problem.

### Steps to Reproduce 
```
# build.gradle file
plugins {
    id 'java-library'
}

group = 'jie'
version = '1.0.0'

dependencies {
}

java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(11)
//    }

    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
```

```
// Java file to test
import java.util.Random;

public class Hello {
  public long getRandom() {
    Random r = new Random();
   // nextLong(long, long) is available in Java 17
    return r.nextLong(100L, 500L);
  }
}
```

1. run `./gradlew build`, it passed
2. comment out sourceCompatibility, and use toolchain config, run `./gradlew build` again, it failed as expected because the api version
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}
```
result: `error: method nextLong in class Random cannot be applied to given types;`

### Your Environment
$ ./gradlew --version
```
------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18 (Oracle Corporation 18+36-2087)
OS:           Mac OS X 12.6.3 aarch64
```

```
$ java --version
openjdk 18 2022-03-22
OpenJDK Runtime Environment (build 18+36-2087)
OpenJDK 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
```

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

----

What you are looking for is the `release` option:
https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html#option-release
