### ISSUE TITLE
Plugin gradle-aspectj does not support JDK7

### ISSUE THREAD

**Issue by ksiczek** [gradle/gradle#2368]
Hi,
I hope it is the right place to get some help with that.

### Expected Behavior
Plugin gradle-aspectj works with JDK7

### Current Behavior
After configuring the plugin build fails with an error 
> java.lang.UnsupportedClassVersionError: aspectj/AspectJGradlePlugin : Unsupported major.minor version 52.0

### Context
I have found an aspectj plugin that seems to be official - https://plugins.gradle.org/plugin/aspectj.gradle so I tried migrating from eveoh to the new one. Unfortunately there is no decant documentation to the plugin yet.

### Steps to Reproduce (for bugs)
I believe that using the plugin in JDK7 project will always lead to the error.

### Your Environment
------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_111 (Oracle Corporation 24.111-b13)
OS:           Linux 4.4.0-83-generic amd64

**Comment by oehme** [comment]
This is a community plugin, please get in touch with the author to see if they would consider Java 7 support.
