### ISSUE TITLE
[ViewBinding] Get the `View` instead of `XxxxBinding` when using the <include /> and the layout file is in the classes (aar)

### ISSUE THREAD

**Issue by jun-wu-tw** [gradle/gradle#23701]
I can **NOT** get the matched binding class but `View` when the layout file is in the class (aar).

I checked the source code of `databinding-compiler-common-7.2.0-sources.jar!/main/kotlin/android/databinding/tool/writer/ViewBinder.kt:163`

I suppose we don't add the `binding` into the binding list without the related task for the `aar`.
```kotlin
        // Check to make sure that the ID matches a binding. Ignored tags like <merge> or <fragment>
        // might have an ID but not have an actual binding. Only use ID if a match was found.
        val rootBinding = bindings.singleOrNull { it.id == id }
        if (rootBinding != null) {
            return RootNode.Binding(rootBinding)
        }
```

Do we have any workaround for that? 
Or we can add new feature like the configuration for this case.
```groovy
     android {
          buildFeatures {
             viewBinding {
                enable = true // enable ViewBinding feature
                supportLibrary = true // for using the `XxxBinding` for `include` tag without check
             }
          }
     }
```

### Expected Behavior

That's from the [blog](https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc) of using `ViewBinding`. I highlight the key point. 🙏 

<img width="714" alt="image" src="https://user-images.githubusercontent.com/86994424/215309737-f976fd5d-11ca-4903-84ff-3ff9c2a274e6.png">

### Current Behavior

<img width="711" alt="image" src="https://user-images.githubusercontent.com/86994424/215309758-a3c8d0b8-eca0-4bec-9dcc-cedaf359fbfc.png">

### Steps to Reproduce 

1. Create a module and enable the ViewBinding feature
2. Introduce the `layout` file into the module from an `aar`
3. Check the module's layout generated code `Xxx1Binding`
4. The `layout` file from the `aar`'s type is `View` instead of `Xxx2Binding`

### Your Environment

AGP version: 7.2.0

Build scan URL:

**Comment by jun-wu-tw** [comment]
**I'd like to confirm that we might support it or not in the future.**
So that I can choose the suitable solution for current case. 🙏

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug
