### ISSUE TITLE
Make `dependencyInsight` work with CC/load-after-store

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#23732]
The following test suites have many failures due to mismatches between expected and actual outputs. 

org.gradle.api.tasks.diagnostics.DependencyInsightReportVariantDetailsIntegrationTest
org.gradle.api.tasks.diagnostics.DependencyInsightReportTaskIntegrationTest

Some samples:

<img width="1202" alt="Screenshot 2023-02-01 at 20 48 21" src="https://user-images.githubusercontent.com/2187522/216195731-d4a367ad-c2e9-4bd5-aa55-7cbdff1026aa.png">

<img width="1202" alt="Screenshot 2023-02-01 at 20 48 08" src="https://user-images.githubusercontent.com/2187522/216195718-b82d3473-0efc-460b-994c-57020d737629.png">

**Comment by abstratt** [comment]
@adammurdoch I suspect these may be related to the issues you found in the dependency management module. Could you recheck this issue while you verify your fixes for that module?

**Comment by bamboo** [comment]
Fixed via #24350
