### ISSUE TITLE
Gradle fails to load JDBC driver after changes in build-logic directory

### ISSUE THREAD

**Issue by redraiment** [gradle/gradle#23737]
When executing the Gradle command immediately after any changes occur in the build-logic directory, the JDBC driver cannot be loaded correctly.

### Expected Behavior

There is a simple task that defined in build-logic folder (`build-log/src/main/kotlin/jdbc.gradle.kts`) to list JDBC drivers:

```kotlin
import java.sql.DriverManager

task("list") {
    doLast {
        logger.quiet("Drivers:")
        val drivers = DriverManager.getDrivers()
        while (drivers.hasMoreElements()) {
            val driver = drivers.nextElement()
            logger.quiet("  Driver: ${driver.javaClass.name}")
        }
    }
}
```

The expected behavior is display JDBC driver list.

### Current Behavior

The current behavior is show empty list.

### Context

I'd like to create a custom task to check database schema, but it fails with cannot obtain connection issue by above issue.

### Steps to Reproduce 

Reproducer repository: https://github.com/redraiment/gradle-issue-reproducer/tree/kotlin-dsl

```sh
$ git clone https://github.com/redraiment/gradle-issue-reproducer.git
$ cd gradle-issue-reproducer
$ git checkout -b kotlin-dsl origin/kotlin-dsl
$ ./gradlew list -q
Drivers:
  Driver: org.h2.Driver
  Driver: org.postgresql.Driver
$ sed -i '' -e 's#"Drivers:"#"After Change:"#' build-logic/src/main/kotlin/jdbc.gradle.kts # do some changes in build-logic
$ ./gradlew list -q # Cannot load drivers now
After Change:
```

### Your Environment

Build scan URL: https://gradle.com/s/5xhwroa5qdhsm

**Comment by eskatos** [comment]
Hi @redraiment ,

Thank you for your report.

Fiddling with a reproducer, I was able to reduce it by removing the `build-logic` included build and down to a single build script:

```kotlin
import java.sql.DriverManager
buildscript {
    repositories { mavenCentral() }
    dependencies {
        classpath("com.h2database:h2:2.1.214")
        classpath("org.postgresql:postgresql:42.5.1")
        classpath("mysql:mysql-connector-java:8.0.33")
        classpath("org.xerial:sqlite-jdbc:3.42.0.0")
    }
}
tasks.register("list") {
    doLast {
        logger.quiet("Drivers:\n${DriverManager.getDrivers().asSequence().map { "  ${it::class.java.name}" }.joinToString("\n")}")
    }
}
```

The problem boils down to https://bugs.openjdk.org/browse/JDK-8146872 which is a JDK bug open in 2015 and still not fixed. There's nothing Gradle can do about it.

If you know the class names of the drivers you want to be able to detect from the dynamic build logic classpath you can load and register them. This is the most frequent workaround for this problem in JVM applications.

Here's an example that works:
```kotlin
import java.sql.Driver
import java.sql.DriverManager

buildscript {
    repositories { mavenCentral() }
    dependencies {
        classpath("com.h2database:h2:2.1.214")
        classpath("org.postgresql:postgresql:42.5.1")
        classpath("mysql:mysql-connector-java:8.0.33")
        classpath("org.xerial:sqlite-jdbc:3.42.0.0")
    }
}

tasks.register("list") {
    doLast {
        val knownDrivers = listOf(
            "org.h2.Driver",
            "org.postgresql.Driver",
            "org.sqlite.JDBC",
            "com.mysql.cj.jdbc.Driver",
        )
        knownDrivers.forEach { driverName ->
            try {
                val driver = javaClass.classLoader.loadClass(driverName).getDeclaredConstructor().newInstance()
                DriverManager.registerDriver(driver as Driver)
            } catch (e: Exception) {
                logger.debug("Driver '$driverName' not present")
            }
        }
        logger.quiet("Drivers:\n${DriverManager.getDrivers().asSequence().map { "  ${it::class.java.name}" }.joinToString("\n")}")
    }
}

```

**Comment by redraiment** [comment]
> Fiddling with a reproducer, I was able to reduce it by removing the `build-logic` included build and down to a single build script:

Thank you so much for the explanation. The workaround works well for me!
