### ISSUE TITLE
Dump stacktrace to file

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#2373]
When an error occurs, users don't always have `--stacktrace` enabled, which makes debugging some problems hard. They can rerun the build with the option enabled, but this takes time and effort (as opposed to running a `clean` build), and it doesn't work for transitive errors.

We could dump the stacktrace to a file, even when `--stacktrace` is not enabled, similar to `hs_err_pidXXX.log` files generated by the JVM. The file would be useful when reporting problems on the forums, too.

**Comment by wolfs** [comment]
Note that if you have build scans enabled then you can look there to see the stacktrace. Even if you didn't publish the scan for the failing build you can publish the scan afterwards with `buildScanPublishPrevious`.

**Comment by lacasseio** [comment]
I think such a feature would really help with Gradle development. Especially when the exception is hard to reproduce.
