### ISSUE TITLE
Failed to create MD5 hash for file content

### ISSUE THREAD

**Issue by ArtanBerisha1** [gradle/gradle#23741]
Out of no where gradle started to fail for a specific Android Studio project of mine (on Ubuntu 20.04.5 LTS), with the current error:

```
\`\* What went wrong:
There was a failure while populating the build operation queue: Failed to create MD5 hash for file content.
Failed to create MD5 hash for file content.
Input/output error

* Try:
  Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
  com.intellij.openapi.externalSystem.model.ExternalSystemException: There was a failure while populating the build operation queue: Failed to create MD5 hash for file content.
  Failed to create MD5 hash for file content.
  Input/output error\`
```

I searched but couldn't find anything useful, I already have tried:

1. Invalidate caches and restart on Android Studio
2. I tried to clean gradle, ./gradlew clean and rebuild the project
3. Restarted my laptop
4. Deleted the repository and cloned again (after rebooting device)
5. Changed the gradle version ( current one is 7.0.2 )
6. Deleted .gradle/ and .idea/ files and build again
7. Updated Android Studio to Android Studio Electric Eel | 2022.1.1
8. With other project it working, but when I tried with this specific project its failing, I tried to give all permissions to this folder with the command: sudo chmod -R 777 /Projects/MyProject

checked the official discuss.gradle.org, there were some similar issues but with no reply.

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

**Comment by ArtanBerisha1** [comment]
Hi @eskatos,

I turns out I had some corrupted file on my system, I am not sure which one it was or why it happened (I suspect that a software update of Ubuntu did that). Either way when I reformatted my laptop and now gradle its working fine, so it looks that this is not an issue on gradle side.
