### ISSUE TITLE
Rename Java Gradle Plugin Development Plugin

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#2375]
We refer to this plugin with a number of names:

* the "Java Gradle plugin development Plugin" (in [user guide](https://docs.gradle.org/4.0/userguide/javaGradle_plugin.html))
* the `java-gradle-plugin` (build scripts)
* we also call it the "java plugin plugin" (when talking about it)

This is problematic because the name is long and confusing. For example the plugin should have nothing to do with "Java," as the plugin under development could be written in Groovy or Kotlin, too.

Proposal:

* call the plugin the "Gradle plugin development plugin" in the user guide (without "Java")
* rename the plugin ID to "plugin-dev"
* call it the "plugin-dev plugin" when talking about it

**Comment by bmuschko** [comment]
I think the idea was to [indicate that the plugin automatically applies the Java plugin](https://github.com/gradle/gradle/blob/master/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/JavaGradlePluginPlugin.java#L119). If we'd follow that logic then we'd also need to have another plugin for Kotlin- or Groovy-based plugins. Generally speaking, the plugin helps with developing JVM-based plugins. Given that all plugins are written in a JVM language there's no need to indicate it specifically. If users want to write a Groovy-based plugin then there's no harm in applying the Groovy plugin. I am not aware of any conflicts between the Java plugin and the Jetbrains Kotlin plugin.

**Comment by adammurdoch** [comment]
To rename it, we should separate the assumption in the plugin that Java will be used as an implementation language. Currently, it is a plugin for implementing Gradle plugins _in Java_.

**Comment by ldaley** [comment]
> To rename it, we should separate the assumption in the plugin that Java will be used as an implementation language.

IIRC, the awkwardness in doing this at the time of this plugin's inception (or perhaps, lack of willingness to invest at that time) is the reason why it is the way it is.

**Comment by adammurdoch** [comment]
Right. Part of that awkwardness was the state of the software model at the time, I think. This is much clearer now and the investment would be much smaller.

But it's still an investment. I would like to see what patterns and infrastructure come out of the native work before shuffling around the JVM plugins in this way.
