### ISSUE TITLE
Warn when gradleApi() is used without the plugin development plugin

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#2376]
We are doing more and more validation in the plugin development plugin for tasks and plugins. It would be nice to enforce the use of this plugin. A good entry point is when `gradleApi()` is used as a dependency.

**Comment by adammurdoch** [comment]
Why is it an error to use gradleApi() without the plugin development plugin applied?

**Comment by ldaley** [comment]
I have the same question.

**Comment by lptr** [comment]
Maybe "warn" is not the right word here. The idea is that we do validation that is necessary for well-behaved tasks in the plugin-dev plugin. We might also want to add extra metadata to plugins (like the version of Gradle used to compile them) etc. In the future it would be great if all Gradle plugins and tasks went through these steps. Informing the user about the existence of the plugin-dev plugin when they use `gradleApi()` seems like a good entry point.

**Comment by bmuschko** [comment]
I think there are valid use cases for `gradleApi()` without the plugin dev plugin. We might just have to make the plugin more prominent in the Gradle community.

1. Better documentation
2. Usage of the plugin in all guides

I actually like @kageiit's idea of checking for the plugin manifest to emit a warning.

**Comment by lptr** [comment]
There seems to be two things here:

1. Warn if the plugin development plugin is not used when developing actual plugins. For this I also like @kageiit's idea.
2. Force people to use _something_ to validate task implementations. Currently this is done by the plugin development plugin, too, but it doesn't necessarily have to be like that. We could introduce a task development plugin, too, for example, which could be applied by default to `buildSrc` projects. We could warn about it if `gradleApi()` is used, _and_ we also find a class that extends `Task` among the compiled output.

**Comment by ldaley** [comment]
> task development plugin

Seems too heavy, doesn't need to be a plugin. It could just be a task that people doing this (which is the minority) wire up manually.

**Comment by lptr** [comment]
Let's do this instead: https://github.com/gradle/gradle/issues/22124
