### ISSUE TITLE
Document 'required attributes' (which are mentioned, but not documented)

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23778]
### Expected Behavior

'Required attributes' are mentioned, but not documented

### Current Behavior

'Required attributes' are documented

### Context

I am trying to figure out how Gradle works, but the documentation regarding configuration attributes is very confusing.

I want to create a Configuration that produces files that are 'tagged' with an attribute. I want that attribute to be required (because at the moment it looks like there's a bug #23776 and attributes aren't required).

I found a reference to a 'required attribute' in the docs

https://github.com/gradle/gradle/blob/8d3589259a9fe039129044431bc7ae825e85657f/subprojects/docs/src/docs/userguide/dep-man/04-modeling-features/variant_model.adoc?plain=1#L235

> Other attributes are presented second, this includes _required_ and _compatible_ ones as well as all extra _producer_ attributes that are not requested by the consumer.

But I can't find out what this means, or more importantly, how to create one.

'Attributes' are listed in the [terminology](https://docs.gradle.org/8.0-rc-2/userguide/dependency_management_terminology.html#sub:terminology_attribute), but there's nothing about making one 'required'. 

'Required' isn't mentioned in the [variant attributes](https://docs.gradle.org/8.0-rc-2/userguide/variant_attributes.html#variant_attributes) doc page

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/897017/216770354-d657ffe3-892b-4916-90fe-d7459ad4b56f.png">

### Related

* #23776
* #18846

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.
