### ISSUE TITLE
Document Configuration resolution methods

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#23772]
### Expected Behavior

Resolving a Configuration is documented

### Current Behavior

Opposite of expected

### Context

I want to use a Configuration to download some dependencies. However, it seems there is a dozen different ways to get the files.

```kotlin
val pluginsClasspath = project.configurations.create("pluginsClasspath")

// which one do I use...?
pluginsClasspath.resolve()
pluginsClasspath.dependencies
pluginsClasspath.incoming
pluginsClasspath.incoming.artifacts
pluginsClasspath.incoming.artifactView { }.artifacts.artifactFiles
pluginsClasspath.incoming.artifactView { }.artifacts.artifactFiles.elements
pluginsClasspath.incoming.artifactView { lenient(true) }
pluginsClasspath.incoming.artifactView { lenient(true) }.files
pluginsClasspath.incoming.artifactView { lenient(true) }.artifacts
pluginsClasspath.incoming.resolutionResult
pluginsClasspath.incoming.resolutionResult.allComponents
pluginsClasspath.incoming.resolutionResult.allDependencies
pluginsClasspath.incoming.resolutionResult.allComponents {  }
pluginsClasspath.incoming.resolutionResult.root.dependencies
pluginsClasspath.incoming.resolutionResult.rootComponent.map { it.dependencies }
pluginsClasspath.artifacts
pluginsClasspath.artifacts.files
pluginsClasspath.resolvedConfiguration.files
pluginsClasspath.resolvedConfiguration.lenientConfiguration.firstLevelModuleDependencies
pluginsClasspath.resolvedConfiguration.lenientConfiguration.files
pluginsClasspath.resolvedConfiguration.lenientConfiguration.getFirstLevelModuleDependencies { true }
pluginsClasspath.resolvedConfiguration.getFirstLevelModuleDependencies { true }
```

Some of these options aren't documented

<img width="406" alt="image" src="https://user-images.githubusercontent.com/897017/216730125-974fe013-8a2e-4ed1-ad96-3de50f6ab283.png">

<img width="479" alt="image" src="https://user-images.githubusercontent.com/897017/216730338-6d29425a-8897-41e7-ab52-ce609853fd5e.png">

I can't find any place in the location where all of these options are compared, so that I can decide which option to use, and in what circumstances. Why are there so many? Maybe some of them are planned for removal? Which of them are lazy? Which should I use as input for a task? What should I put into `ConfigurableFileCollection.from()`?

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Those methods are documented in the Javadoc.
Here is your starting point https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Configuration.html

**Comment by aSemy** [comment]
> Those methods are documented in the Javadoc. Here is your starting point https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Configuration.html

1. I can't find the answers to any of my questions in the Javadoc. 
2. The Javadoc is not easily discoverable (when I search for them in the docs, there are no results)
3. I can't find any documentation that compares the myriad of options and which should be used in which situations

**Comment by jvandort** [comment]
We really should have a "Dependency management crash course" page. I agree our existing pages that describe [variants](https://docs.gradle.org/current/userguide/variant_model.html) and [such](https://docs.gradle.org/current/userguide/variant_attributes.html) never end up discussing the _basics_/how to leverage the API. 

This is definitely something that needs to be worked on. 

To answer your original question -- the `Configuration` class has way too many APIs. 

`resolve()` and `files()` do the same thing. This is usually what you want
`artifacts` and `incoming.artifacts` do the same thing give you the artifacts that `files()` would give you (artifacts are files + metadata about those files)

Anything on `resolutionResult` lets you inspect the graph without looking at the files. 

Do not use `resolvedConfiguration` and `resolvedConfiguration.lenientConfiguration`. These are legacy types. 

`artifactView` is more advanced, and with `withVariantReselection` can do some really cool stuff. See: [link](https://github.com/gradle/gradle/issues/26007#issuecomment-1883995175)
Using `artifactView` with `lenient=true` allows you to ignore missing dependencies
Using `artifactView` with `componentFilter` lets you filter out certain dependencies from your results.
