### ISSUE TITLE
Gradle generates broken links in logs

### ISSUE THREAD

**Issue by SimonMarquis** [gradle/gradle#23785]
### Current Behavior

When running out of memory, Gradle outputs the following log message:

```
The Daemon will expire after the build after running out of JVM Metaspace.
The project memory settings are likely not configured or are configured to an insufficient value.
The daemon will restart for the next build, which may increase subsequent build times.
These settings can be adjusted by setting 'org.gradle.jvmargs' in 'gradle.properties'.
The currently configured max heap space is '512 MiB' and the configured max metaspace is '256 MiB'.
For more information on how to set these values, visit the user guide at https://docs.gradle.org/8.0-rc-2/userguide/build_environment.html#configuring_jvm_memory
To disable this warning, set 'org.gradle.daemon.performance.disable-logging=true'.
Daemon will be stopped at the end of the build after running out of JVM Metaspace
```

The provided link is not right, and should be changed to

```diff
-https://docs.gradle.org/8.0-rc-2/userguide/build_environment.html#configuring_jvm_memory
+https://docs.gradle.org/8.0-rc-2/userguide/build_environment.html#sec:configuring_jvm_memory
```

### Steps to Reproduce 

Not a real "steps to reproduce" but here is a link to a GitHub Actions job that triggers it: https://github.com/SimonMarquis/SealedObjectInstances/actions/runs/4097340460/jobs/7065637485#step:4:156
I guess we could also reduce the java allowed memory amount to something very small to trigger it every time.

### Your Environment

Build scan URL: not relevant, but here it is https://scans.gradle.com/s/ylkb4lwsl6u3y

### Solution

Fix broken URLs used with `DocumentationRegistry.getDocumentationFor(String id, String section)`.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by SimonMarquis** [comment]
Thanks, and fyi I've prepared a corresponding PR here if that helps:

- #23786
