### ISSUE TITLE
Gradle dependencies gives different results for pom dependencies in map string notation vs group version notation

### ISSUE THREAD

**Issue by somakdutta** [gradle/gradle#23783]
For a gradle project with pom type dependencies , executing gradle dependencies provides different results.

Results when using say api 'org.lunarray.model:bom:1.0' : https://scans.gradle.com/s/3gliwpn4dgcnu 
Results when using say api group: 'org.lunarray.model', name: 'bom', version: '1.0', ext: 'pom': https://gradle.com/s/smxdzgr2yepi2/activate/kykfkofbdlmks

Specifically when we use api group: 'org.lunarray.model', name: 'bom', version: '1.0', ext: 'pom' , we get something like 
```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.apache.logging.log4j:log4j-bom:2.19.0
+--- org.lunarray.model:bom:1.0
\--- junit:junit:4.13
     \--- org.hamcrest:hamcrest-core:1.3
```

However when we use api 'org.lunarray.model:bom:1.0'

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.lunarray.model:bom:1.0
|    +--- org.lunarray.common:base:1.0
|    |    \--- org.lunarray.common:bom:1.0
|    |         \--- commons-lang:commons-lang:2.6
|    +--- org.lunarray.common:event:1.0
|    |    +--- org.lunarray.common:bom:1.0 (*)
|    |    \--- org.lunarray.common:base:1.0 (*)
|    \--- org.slf4j:slf4j-api:1.7.7
+--- org.apache.logging.log4j:log4j-bom:2.19.0
\--- junit:junit:4.13
     \--- org.hamcrest:hamcrest-core:1.3
```

### Expected Behavior
I am expecting results to be same

### Current Behavior
POM type dependencies are resolved when using map notation but not resolved when using group string notation

### Steps to Reproduce 
[build.txt](https://github.com/gradle/gradle/files/10610871/build.txt)
Create a gradle java project and replace build.gradle with contents in the attached
Execute the command gradle dependencies

### Your Environment
[build.txt](https://github.com/gradle/gradle/files/10610871/build.txt)
Gradle Version : 

------------------------------------------------------------
Gradle 6.9.2
------------------------------------------------------------

Build time:   2021-12-21 20:18:38 UTC
Revision:     5d94aa68c0fdbe443838bb977080e3b9f273e889

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.16.1 (Homebrew 11.0.16.1+0)
OS:           Mac OS X 13.0.1 aarch64

Build scan URL:

**Comment by xaviarias** [comment]
You reproducer gives the expected results.

With the dependency `api group: 'org.lunarray.model', name: 'bom', version: '1.0', ext: 'pom'`:

```
$ gw dependencies --configuration=compileClasspath

compileClasspath - Compile classpath for source set 'main'.
\--- org.lunarray.model:bom:1.0
```

with the dependency `api 'org.lunarray.model:bom:1.0'`:

```
$ gw dependencies --configuration=compileClasspath

compileClasspath - Compile classpath for source set 'main'.
\--- org.lunarray.model:bom:1.0
     +--- org.lunarray.common:base:1.0
     |    \--- org.lunarray.common:bom:1.0
     |         \--- commons-lang:commons-lang:2.6
     +--- org.lunarray.common:event:1.0
     |    +--- org.lunarray.common:bom:1.0 (*)
     |    \--- org.lunarray.common:base:1.0 (*)
     \--- org.slf4j:slf4j-api:1.7.7
```

The difference is on the `ext: 'pom'` which filters non POM artifacts.
