### ISSUE TITLE
@HasImplicitReceiver doesn't seem to be supported in IDEA

### ISSUE THREAD

**Issue by klunnii** [gradle/gradle#23799]
### Expected Behavior

Our project has a `.gradle.kts` build script with the following snippet:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/9988112/217016929-8c1b4020-a1f8-4e63-9ecd-18cec798c121.png">

`AttributeContainer`/`ArtifactHandler` are explicit lambda receivers that should be available via `this` reference. 
Although the Kotlin docs state differently (it should be `it` as on the screenshot) the trick is possible thanks to `org.gradle.api.HasImplicitReceiver` annotation.
Annotation handler is a Kotlin compiler plugin that should be available for IDE mode (but it doesn't seem to be the case).

### Current Behavior

Kotlin compiler for IDE is aware of `@HasImplicitReceiver` annotation and makes receivers available via `it` reference. 

### Steps to Reproduce 

1. Try to declare a property in a .gradle.kts file as follows:
```
val conf: Configuration by configurations.creating {
    attributes {
        attribute(/* whatever */)   
    }
}

```
2. IDEA highlights `attribute` as an unresolved reference. CLI mode works fine.
3. If you try adding `it.` prefix IDEA becomes aware of it due to the reasons described above.

### Your Environment

Gradle 7.5.1 + IDEA 2022.2/3.

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

----

Hi Andrei,

Thanks for the report. I cannot reproduce with either Gradle 7.5 nor a Gradle 8.1 nightly.
Here's what I get in the IDE for both a standalone `build.gradle.kts` script or a precompiled script residing in a Kotlin source set:

![image](https://user-images.githubusercontent.com/132773/217534969-0e97802a-88ff-490a-a2f6-c54c819ea480.png)

**Comment by klunnii** [comment]
Hi Paul,

I apologize and admit that the root cause of the issue is on our side.
The project that I used for the complaint investigation utilizes a custom build of the KGP (Kotlin Gradle Plugin).
After switching to the "standard" `org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0` the problem escaped.

Sorry for disturbing and thank you for your support!
