### ISSUE TITLE
Add --type gradle-plugin to init task

### ISSUE THREAD

**Issue by balazsbanyai** [gradle/gradle#2379]
When creating a gradle plugin from scratch, it would be great if the init task could create an empty plugin project scaffolding, including the package structure and META-INF files.

### Expected Behavior
It should work like:
gradle init --type gradle-plugin -Ppackage=com.my.plugin -PpluginClass=MyPlugin

_package_ is optional, defaults to default package
_pluginClass_ is optional, defaults to "MyPlugin"

1, Which would create the following folder structure:
```
.
  src
    main
      groovy
        com
          my 
            plugin
              MyPlugin.groovy
      resources
        META-INF
          gradle-plugins
            com.my.plugin.properties  
```

2, Init the project like a groovy library, but apply the plugin development plugin as well
```
apply plugin: 'java-gradle-plugin'
```

### Current Behavior
The current init task does not support creating plugin scaffolding projects.

### Context

I have created numerous plugins during my work, and always found it peculiar and error-prone to create plugin scaffoldings. There are certainly other ways to implements this feature, but when I read [this](https://docs.gradle.org/3.3/userguide/build_init_plugin.html) paper, I feel that this would be the right way.

**Comment by bmuschko** [comment]
We actually don't recommend [writing Gradle plugins with plain Groovy](https://guides.gradle.org/designing-gradle-plugins/#prefer_using_a_statically_typed_language_to_implement_a_plugin). I think build-init is the correct approach though there are multiple variable that would determine _what_ to create:

1. The language to be used
2. The default package
3. The default class
4. The domain that should be used for the properties file (which might be different from package)

As you can see it makes scaffolding a plugin very flexible but also more cumbersome to implement. What you are likely looking for is a [way to provide your own templates](https://github.com/gradle/gradle/issues/1686).

**Comment by adammurdoch** [comment]
This should be a built-in template. Those questions are easy to answer.

**Comment by balazsbanyai** [comment]
As I described above, these questions could be answered by parsing the optional parameters given into the build. 

@adammurdoch do you think that would be sufficient?

**Comment by adammurdoch** [comment]
Yes, I think so. We should try to make the approach consistent with the other types of projects you can create. For example, you currently select the implementation language for an application or library by specifying it in the type, eg using `gradle init --type java-library`. We might use the same approach for a Gradle plugin type as well. Or, if we add a separate option for the implementation language, we should refactor the other templates to work the same way.

The package and main class are also options that would make sense for both application and libraries as well as Gradle plugins, so if we add options for this it would be great to add them in a cross-cutting way.

I would suggest busting this up into several pieces that we implement in a few steps (eg as separate PRs):

1. Add a basic `gradle-plugin` type with no options, that uses a hardcoded language (either Java or Groovy) as the implementation language, so at least there's something.
2. Add support for both Groovy and Java and maybe Kotlin as implementation languages, either as new types or as a configuration option.
3. Add support for specifying the package and main class when creating an application, library or Gradle plugin.

**Comment by balazsbanyai** [comment]
I would be happy to implement this! I will get back to you with the first PR soon.

**Comment by adammurdoch** [comment]
That would be great, thanks for looking into this.

**Comment by balazsbanyai** [comment]
I would like to request some advice on this topic.

Please see my fork, where I added the first phase of the discussed modifications.

1, When I run the _buildInit:check_ task, I get a failing test, which reports that the 'java-gradle-plugin' could not be found 
2, When I execute the test from idea, the test passes
3, When I _install_ gradle, and test the built distribution manually, the generated project can be built and the tests are passing

Can you provide me with some directions about why the 'java-gradle-plugin' may not be found during the test?

**Comment by big-guy** [comment]
This is going to be in 5.5
