### ISSUE TITLE
Gradle plugin unable to load class from other plugin despite withPlugin() { ... }

### ISSUE THREAD

**Issue by staktrace** [gradle/gradle#23792]
### Expected Behavior
I have a gradle plugin which is trying to configure the KotlinCompile task from the kotlin gradle plugin. I expect that my plugin is able to successfully do `tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile::class.java).configureEach { ... }`.

### Current Behavior
When it tries to `tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile::class.java).configureEach { ... }` it throws a `java.lang.NoClassDefFoundError`. Even doing a `Class.forName("org.jetbrains.kotlin.gradle.tasks.KotlinCompile")` at this point fails to find the class.

### Context
The plugin we have is a proprietary plugin that we use internally in our company to configure other repos and set the kotlin jvm target version. However for some repos it fails with this error. I was able to reduce the test case to the one linked in this bug report.

### Steps to Reproduce 
Standalone project that reproduces this issue: https://github.com/staktrace/20230205-kotlincompile-task. Run `./gradlew :code:classes` (or really any task there, since the error is at configuration time).

### Your Environment
Gradle 7.6 on macOS 13.2.
Build scan URL: https://scans.gradle.com/s/n6emg7vjjc7m6

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

---

The link to the reproducer is a 404.

**Comment by staktrace** [comment]
@eskatos sorry about that, the reproducer repo was set to private. I've made it public now so you should be able to see it. Thanks!

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

---

Your plugin will be loaded in the `buildSrc` classloader that because of the `compileOnly` dependency doesn't have the Kotlin Gradle Plugin. When applying your plugin in the root project its code will try to load the `KotlinCompile` class from the `buildSrc` classloader hence the `ClassNotFoundException`.

You need to declare an `implementation` dependency in `buildSrc`  instead of a `compileOnly` one and then remove your buildscript classpath addition in the root project.

**Comment by staktrace** [comment]
@eskatos Thanks for the information (and sorry for the delayed response, I was away last week). Are there gradle docs somewhere on the different classloaders that get created? I was under the impression that the `buildSrc` classloader would be the same as the `buildscript` classloader, but I think my mental model is lacking in that area.

**Comment by eskatos** [comment]
These blog posts should help clarify this:
* https://dev.to/autonomousapps/build-compile-run-a-crash-course-in-classpaths-f4g
* https://dev.to/autonomousapps/a-crash-course-in-classpaths-build-l08
* https://dev.to/autonomousapps/abusing-gradle-s-class-loader-hierarchy-for-fun-and-profit-oca
* https://dev.to/autonomousapps/a-crash-course-in-classpaths-run-21go

**Comment by staktrace** [comment]
Aha, thank you very much! It makes sense now in my head, and I'll try and figure out a solution that satisfies my needs.
