### ISSUE TITLE
Corrupted configuration cache is persisted, resulting in guaranteed failure (until explicitly invalidated)

### ISSUE THREAD

**Issue by amichne** [gradle/gradle#23802]
In some scenarios, when the configuration cache is corrupted, this corrupted configuration is persisted to the cache instead of being cleared.

### Expected Behavior

This corrupted configuration should be cleared (or, if not possible to do partial evictions, the cache should be invalidated). The cache should be rebuilt on the next use, such that any errors due to configuration cache corruption are no longer observed (assuming a well-formed build script).

### Current Behavior

The corrupted configuration cache will be loaded upon even invocation of `./gradlew build`, resulting in failures in all futures attempts (until the cache is manually invalidated).

### Context

It took quite a bit of time to understand what the issue was, due to only a minimal amount of information being returned, combined with a _much much_ faster failure than I had ever observed prior for this project.

### Your Environment

Build scan URL: (cannot link, will provided all relevant information below)

Gradle 7.6

#### Local Console Output
```
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration cache is an incubating feature.
Reusing configuration cache.

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.internal.operations.BuildOperationInvocationException (no error message)
> java.io.EOFException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 5s

Publishing build scan...
https://gradle.***.com/s/***

Configuration cache entry reused.
```
#### Gradle Scan "Failure" tab output
```
Failure 1 of 1 (No message provided)

(No message provided)
> Buffer underflow.

Exception
org.gradle.internal.operations.BuildOperationInvocationException: (No message provided)	
  > at org.gradle.internal.operations.DefaultBuildOperationRunner.throwAsBuildOperationInvocationException(DefaultBuildOperationRunner.java:192)...
    Caused by: java.io.EOFException: (No message provided) 
    > at org.gradle.internal.serialize.kryo.KryoBackedDecoder.maybeEndOfStream(KryoBackedDecoder.java:80)...
      Caused by: com.esotericsoftware.kryo.KryoException: Buffer underflow.	
      > at com.esotericsoftware.kryo.io.Input.require(Input.java:181)	...
```

### Notes
* I believe this corruption only existed in the `./gradle build` cache, as I was able to run a module-specific task without any issues. 
* Once the cache was corrupted for `./gradlew build`, I observed failures 100% of the time, until I manually invalidated the cache via `rm -rf .gradle/configuration-cache`.
* For any failing commit, I was able to execute `./gradlew build` on my CICD pipeline, with zero failures observed.

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

----

Did you have `org.gradle.unsafe.configuration-cache.warn=true` set?

**Comment by shantanu-skylark** [comment]
> Did you have `org.gradle.unsafe.configuration-cache.warn=true` set?

@eskatos I had the same issue and `org.gradle.unsafe.configuration-cache.warn=true` was set.
Removing it fixes the issue...
