### ISSUE TITLE
Properties implemented via `@Inject` provide access to incorrect `Project` state in builds running from configuration cache

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#23803]
If a task or model class contains an abstract property of the `Project` type implemented via `@Inject`, then, when the property is accessed at the execution time in builds that run from the configuration cache, it silently returns a stub `Project` instance that may expose incorrect state.

Consider this example:

```
abstract class MyPlugin : Plugin<Project> {
    @get:Inject
    abstract val project: Project
    
    override fun apply(target: Project) {
        registerTask(target)
    }
    
    private fun registerTask(target: Project) {
        project.tasks.register("task", MyTask::class) {
            onlyIf { project.hasProperty("foo") }
        }
    }
}

open class MyTask : DefaultTask() {
    @TaskAction
    fun doSomething() {
        logger.quiet("done!")
    }
}
```

As opposed to capturing the `Project` in the fields of `MyPlugin`, this approach will lead to the task accessing the `project` property of `MyPlugin` at the execution time, obtaining a stub `Project` that, for instance, will not have its properties initialized from the command line parameters. Therefore, running `./gradlew task -Pfoo --configuration-cache` will result in the `task` being skipped in builds that run from the configuration cache.

### Expected Behavior
Accessing `@Inject`-implemented properties of non-serializable types should fail in builds that run from configuration cache, or it should be even reported as a problem in the build that produces the configuration cache entry.

### Current Behavior
Accessing the property is not reported as a problem in any way. The property getter silently returns a stub `Project` instance.

**Comment by 6hundreds** [comment]
Fixed https://github.com/gradle/gradle/pull/24727
