### ISSUE TITLE
Build compile BUG

### ISSUE THREAD

**Issue by TarryHoo** [gradle/gradle#2380]
**double compile error**
It took me two ways to reference the package.
1. compile 'com.g7.auto:account-roles-api:1.0.1'
2. compile group: 'com.g7.auto', name: 'account-roles-api', version: '1.0.1'

BUG:
1. form version 1.0 to 1.0.1 Introduction of failure
        (bash: gradle clean build invalid. remove cache jar refresh invalid)
2. success!(Without any operation)

When 1 and 2 exist together:
    annotation 2 of 1 introduction of success????
     remove 2 of 1 failure?
![image](https://user-images.githubusercontent.com/8907875/27814396-a276ef0e-60ae-11e7-9fd1-5ea01695fc38.png)

![image](https://user-images.githubusercontent.com/8907875/27814422-d11867b6-60ae-11e7-8268-144739e72e6b.png)
![image](https://user-images.githubusercontent.com/8907875/27814432-e451fb26-60ae-11e7-9337-ea6b689acf98.png)

**Comment by TarryHoo** [comment]
gradle version 3.3

**Comment by lacasseio** [comment]
I don't think I correctly understand the issue. Could you follow the [template when filling an issue](https://raw.githubusercontent.com/gradle/gradle/master/.github/ISSUE_TEMPLATE.md)? Also, could you post a [build scan](https://scans.gradle.com/get-started) for your succeeding and failing scenario?

**Comment by TarryHoo** [comment]
@lacasseio sorry, i'm reboot computer this bug disappear
