### ISSUE TITLE
CompileJava with wrong package,  build successful

### ISSUE THREAD

**Issue by iHearty** [gradle/gradle#2381]
I had a class named MissionUploadResource with wrong package, like:
![err_1](https://user-images.githubusercontent.com/10851527/27817628-c46ae384-60c4-11e7-9a76-d370ac534a68.png)

Usage: 
![err_2](https://user-images.githubusercontent.com/10851527/27818002-69a7d626-60c6-11e7-8a8e-c8fc2241cc21.png)

When i use gradle to run task "compileJava", the result is "BUILD SUCCESSFUL".
I think there should report a error.
![image](https://user-images.githubusercontent.com/10851527/27818064-b0ea75ca-60c6-11e7-9e10-d82836ae83b2.png)

**Comment by lacasseio** [comment]
This isn't a bug. It's the expected behavior shared by both Gradle and IntelliJ. The red squiggly is simply telling you that by convention the file path and package name should match but it's not required.
