### ISSUE TITLE
The 'plugins' directive is not available in injected builds

### ISSUE THREAD

**Issue by chriskilding** [gradle/gradle#23815]
### Expected Behavior
In injected builds, I should be able to define plugins using the modern `plugins {}` block directive e.g.

```groovy
class FooBuildPlugin implements Plugin<Settings> {
  void apply(Settings settings) {

    gradle.rootProject {
      // ...

      plugins {
        id 'org.hibernate.build.xjc' version '2.2.0'
      }

      // ...
    }
  }
}
```

### Current Behavior

Injected builds don't currently support the `plugins` block directive. Instead only the older `apply plugin` directive is supported e.g.

```groovy
apply plugin: '<some-plugin>`
```

This causes additional hassle because you have to define the `buildscript` directive as well. The connascence between these directives can lead to unintended bugs that are hard to diagnose e.g. 'plugin with ID ... not found' errors.

### Context

I have a regular Gradle project which contains a source dependency (using the `gitRepository(...)` directive in settings.gradle). The source dependency does not have a Gradle build of its own, so I'm injecting one using Gradle plugin injection. (This is described in <https://github.com/gradle/native-samples#application-uses-libraries-that-are-not-built-by-gradle-injected-plugins>)

Basically, injected builds should be able to do all the things that a regular top-level Gradle build script can do, but there appear to be unexpected limitations to their abilities. For example, the lack of support for newer Gradle build directives like `plugins {}`.

### Steps to Reproduce 

The project is private so I'm unable to share the source. What follows is a rough recreation of it:

1. Create a Gradle project.
2. Add a source dependency in `settings.gradle`, which fetches an upstream dependency from a Git repo. (Because Gradle's `gitRepository` directive does not support newer SSH key types, I recommend just using a public repo over HTTPS where authentication is not needed.)
3. Write the injected plugin (which defines the Gradle build to inject into the upstream project) and wire it up. An example is below:

```gradle
class FooPlugin implements Plugin<Settings> {
  void apply(Settings settings) {
    rootProject.name = 'foo'
    gradle.rootProject {
      group = 'com.example'

      repositories { mavenCentral() }

      plugins {
        id 'java'
        id 'org.hibernate.build.xjc', version '2.2.0'
      }

      // configure the xjc plugin as well if you like
    }
  }
}
```

### Your Environment

I am unable to generate a build scan

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

The `plugins {}` block is only available in scripts, this is expected.
https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block

**Comment by chriskilding** [comment]
While this may be expected behaviour for Gradle as it stands, I would say it's not desired behaviour, as it makes it impossible to apply most plugins in an injected build (only the most core plugins like `java` can be applied at the moment). That rules out using anything like the XJC plugin for example.

I'll open a new ticket for it - do you think it would be more appropriate as a bug ticket or as a feature ticket?

**Comment by eskatos** [comment]
For external plugins you should be able to add buildscript classpath dependencies and then use the imperative `apply`. Just like in any binary plugin.

**Comment by chriskilding** [comment]
Hmm, I did try the `buildscript` thing per the instructions, but the injected build was still unable to resolve the plugin.
