### ISSUE TITLE
Use `@Nullable` from JSR-305

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#2382]
Currently we mark `@Nullable` values with our own `@org.gradle.api.Nullable` annotation. There is a standard replacement for it in `@javax.annotation.Nullable`. Using the standard version has some benefits:

* no need to [configure IntelliJ](https://github.com/gradle/gradle/blob/0b74742a47593ba3e135e4c640c6cffde5790c3b/gradle/idea.gradle#L89-L112) to recognize our implementation
* Kotlin automatically generates Java interop so that:
  * `@Nonnull java.lang.String` => `String`
  * `@Nullable java.lang.String` => `String?`

**Comment by lptr** [comment]
PR: https://github.com/gradle/gradle/pull/2441

**Comment by lptr** [comment]
The PR has been merged.

**Comment by bamboo** [comment]
@lptr it seems the PR doesn't expose `javax.annotation.Nullable` and `javax.annotation.Nonnull` as part of the Gradle API so IntelliJ doesn't recognize the annotations when editing Kotlin scripts.

**Comment by wolfs** [comment]
@bamboo This has been fixed.

**Comment by bamboo** [comment]
Thanks, @wolfs. I can confirm `@Nullable` annotations are being recognized by IntelliJ when editing Kotiln scripts now.
