### ISSUE TITLE
Wrong project.gradle.parent

### ISSUE THREAD

**Issue by kalayda** [gradle/gradle#23837]
### Expected Behavior
`project.gradle.parent` points to the project's **immediate** parent, even if this project's parent has it's own parent

### Current Behavior
`project.gradle.parent` points to the **topmost** project, not for real parent

### Context
Such a behavior misleads when using nested composite builds, where some project includeBuild other project, wich, in turn, includeBuild third project.
For instance, it causes Android Gradle Plugin crash in `ModelBuilder.getBuildName()`

### Steps to Reproduce 
Let 3 projects: bottom, middle and top, laying in the same directory. i.e.
root/top
root/mid
root/bottom

top/settings.gradle.kts
```
rootProject.name = "top"
includeBuild("../mid")
```

mid/settings.gradle.kts
```
rootProject.name = "mid"
includeBuild("../bottom")
```

bottom/settings.gradle.kts
```
rootProject.name = "bottom"
```

All three projects have build.gradle.kts:
```
println("${project.name} parent is ${project.gradle.parent?.rootProject?.name}")
```

When running `./gradlew init` got output
```
Welcome to Gradle 8.0-rc-3!

For more details see https://docs.gradle.org/8.0-rc-3/release-notes.html

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :bottom
bottom parent is top

> Configure project :mid
mid parent is top

> Configure project :
top parent is null

> Task :init SKIPPED
The build file 'build.gradle.kts' already exists. Skipping build initialization.

BUILD SUCCESSFUL in 15s
```

As you see, parent of both `bottom` and `mid` is `top`.  
But I expect parent of `bottom` is `mid`

### Your Environment
Gradle 8.0 RC3
Build scan URL: https://scans.gradle.com/s/222bhbgxeuoka

**Comment by danielschroder** [comment]
I came to this issue from an answer to my [question in StackOverflow](https://stackoverflow.com/q/74453881/3576968). I'm linking it here as it might help to understand a simple use case for this situation.

**Comment by jbartok** [comment]
This definitely highlights a lack of documentation. I can't find anything detailing this behavior. 

So I'm speculating. Since any included build can include any other build in turn, the graph of included builds can have cycles and to work around that, so I guess internally we might somewhere store all included builds as direct descendants of the root build. 

The only clue in the documentation I could find is here: https://github.com/gradle/gradle/blob/7dec5105c7585151d7339beddfc549e04697a9cd/subprojects/tooling-api/src/main/java/org/gradle/tooling/model/gradle/GradleBuild.java#L67 (and this is not even the same thing that we are looking at).

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

**Comment by kalayda** [comment]
Thank you for attention to issue I had found.
But what is the reason to flatten nested composite build structure?
In my oppinion more useful would be preserve composition tree-like structure.

**Comment by ljacomet** [comment]
The main reason is that a given build can be included in multiple builds (think composites of composites), but for Gradle, it still is a single unique build.
