### ISSUE TITLE
Have a public API to tell if project isolation is enabled.

### ISSUE THREAD

**Issue by bingranl** [gradle/gradle#23840]
### Expected Behavior

Have a public API to tell if project isolation is enabled. Similar to https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html#isConfigurationCacheRequested--

### Current Behavior

No public API is available 

### Context

Some plugin author(like AGP) can select another code path to avoid project isolation issue which is a good thing for the project isolation adoption. Currently we rely on the internal API from `StartParameterInternal` but it is not ideal because it could break at some point and we have seen this happening in the past(e.g. https://issuetracker.google.com/issues/252848749)

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by alllex** [comment]
@bingranl, could you describe your use-case when the plugin needs to take a different code path depending on whether Isolated Projects is enabled or not?

**Comment by bingranl** [comment]
@alllex Sure, the use cases for `isProjectIsolationEnabled` and `isConfigurationCacheRequested` are similar 

1. Collect data on how many users switch to CC/project isolation for analytics purpose
2. Surface this info to users to encourage them to switch to CC/project isolation
3. Disable some incompatible minor features when CC/project isolation enabled to unblock making a third party plugin compatible with CC/project isolation -> Gradle doesn't need to worry about having a different code path. The plugin author is responsible for that.

**Comment by matejdro** [comment]
How to access this from the build script? `the<BuildFeatures>()` fails, saying that `Extension of type 'BuildFeatures' does not exist`

**Comment by alllex** [comment]
@matejdro, you can grab needed services in a script by instantiating an intermediate type:

```kotlin
// *.kts

interface MyServices {
    @get:Inject val buildFeatures: BuildFeatures
}

val myServices = project.objects.newInstance<MyServices>()

// use myServices.buildFeatures
```

It’s far from ideal, but it’s the current approach recommended by the documentation. E.g. for file operations:
https://docs.gradle.org/current/userguide/service_injection.html#filesystemoperations

---

Having said that, you should avoid having build logic that is conditional on the build features enabled. You should strive having build logic that is instead compatible with all features. Create new issues, if you have a use case that prevents you from having that.

**Comment by matejdro** [comment]
I have that, but I was hoping for a clearer solution.

My use case here is that, we have in our project several plugins that are not (yet?) isolated projects compatible. Since many of those plugins are non-essential or only used in some circumstances, it makes sense to just disable them when isolated projects is present, to allow using isolated projects in all other circumstances (and if user needs to use those plugins, he/she can just disable IP to make them work).

**Comment by alllex** [comment]
If these are the plugins that you own, I suggest moving the conditional of Isolated Projects into the plugin code, so that the plugin is applied unconditionally in the build script. This will keep build scripts more declarative, while highlighting the problematic part of the plugin in question.

You can inject the `BuildFeatures` directly into the plugin class, the same way you inject other services.

```kotlin
abstract class MyPlugin
@Inject constructor(private val buildFeatures: BuildFeatures) : Plugin<Project> {
    private val logger = LoggerFactory.getLogger("my-plugin")

    override fun apply(project: Project) {
        if (buildFeatures.isolatedProjects.active.get()) {
            logger.warn("Skipping MyPlugin, because Isolated Projects is enabled")
            return
        }

        // do stuff
    }
}
```

**Comment by matejdro** [comment]
No, unfortunately I do not own these.

**Comment by alllex** [comment]
Then you should reach out to the maintainers of those plugins and get them fixed. This, of course, will take time.

A general best practice is to have a [convention plugin](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_convention.html) that applies further plugins and configures the defaults. Once you have the convention plugin, as a temporary workaround, you can make the third-party plugin application conditional, using the first sample I shared, if it's a precompiled script plugin. Or the second sample, if it's a class-based plugin.

I've created an issue to document this better:
- https://github.com/gradle/gradle/issues/37449

**Comment by matejdro** [comment]
We did, but as you said, it takes time.

We have convention plugins in form of .gradle.kts precompiled script plugins - this is exactly where we need this.
