### ISSUE TITLE
Support the `plugins {}` directive in injected builds

### ISSUE THREAD

**Issue by chriskilding** [gradle/gradle#23862]
### Expected Behavior

In injected builds, I should be able to define plugins using the modern `plugins {}` block directive e.g.

```groovy
class FooBuildPlugin implements Plugin<Settings> {
  void apply(Settings settings) {

    gradle.rootProject {
      // ...

      plugins {
        id 'org.hibernate.build.xjc' version '2.2.0'
      }

      // ...
    }
  }
}
```

### Current Behavior

Injected builds don't currently support the `plugins` block directive. Instead only the older `apply plugin` directive is supported so you can only do this:

```groovy
gradle.rootProject {
  apply plugin: '<some-plugin>`
}
```

This means that it's only possible to use the most core plugins within injected builds e.g. `java`; it rules out using any other third-party plugins (even those from the official plugin site).

### Context

I am trying to inject a Gradle build into a source dependency (to deal with the fact that the dependency has a legacy Ant/Ivy build). I now need to replace the XJC code generation step in the Ant tasks with an equivalent Gradle plugin. There are several third-party Gradle plugins which could do this, and in a normal top-level project I'd be able to apply them in the `plugins {}` block without issue. However it appears that because `plugins` isn't available within injected builds, and the `apply plugin` directive can't resolve them either, I can't use them.

I have tried doing `apply plugin: 'org.hibernate.build.xjc'` by itself.

I have also tried putting the `buildscript` directive in the injected build as well, as recommended on the Gradle plugins site:

```groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "org.hibernate.build.gradle:gradle-xjc-plugin:2.2.0"
  }
}

apply plugin: "org.hibernate.build.xjc"
```

In both cases, the injected build is unable to resolve the plugin.

I can only conclude that this would work properly if the modern `plugins {}` directive was supported in injected builds, and would therefore like this to be added to Gradle.

**Comment by chriskilding** [comment]
This continues from https://github.com/gradle/gradle/issues/23815 where I originally thought that the lack of `plugins {}` support in injected builds was a bug. I was advised that this is expected behaviour given how Gradle currently works, and therefore have converted this to a feature request.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Our documentation is a bit lacking and we are going to work on that, but basically you need two things:

- a **regular** dependency on the jar of the plugin you want to apply in your own plugin (you can find the GAV of the jar via the page of the plugin on the Portal)
- a simple application of the used plugin in your own one

Some examples we could find for you:

- https://github.com/spring-projects/spring-boot/blob/ea6ed4b486757e746ca520ec19bd1114bec1da89/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/build.gradle#L24 (this is the dependency part)
- https://github.com/gradle/gradlecom/blob/d0fd61d921f9c538744c3b00e1a2e872dcdca57c/gradle-plugins/publish-plugin/src/main/java/com/gradle/publish/PublishPlugin.java#L65 (this is an application of such a plugin)

**Comment by chriskilding** [comment]
@jbartok This Issue is a feature request, not a question, and therefore it has been incorrectly closed. Please could you reopen it?

**Comment by eskatos** [comment]
The semantics of the `plugins {}` block are not only about applying a plugin but also about bringing it as a dependency.
This feature is designed for build scripts DSL. What you're doing is a binary plugin where you write imperative code. You need to both declare the plugin dependency and then apply it. For doing that you have to use the APIs and not the DSL. 

e.g.
```groovy
class FooBuildPlugin implements Plugin<Settings> {
  void apply(Settings settings) {
    gradle.rootProject {
      buildscript {
         dependencies {
            classpath 'org.hibernate.build.gradle:gradle-xjc-plugin:2.2.0'
         }
      }
      apply plugin: 'org.hibernate.build.xjc'
    }
  }
}
```
 
There's currently no plan providing the feature you are requesting.

**Comment by chriskilding** [comment]
Ah right, thanks for clarifying that.
