### ISSUE TITLE
change default .gradle folder location

### ISSUE THREAD

**Issue by regrog** [gradle/gradle#2387]
I'm using jenkins with RTC plugin, incremental build should be running correctly, but I noticed that every time my CI gets changes from RTC, the folder ".gradle" in my root project is lost. This behavior ruins in fact the incremental build feature...
Is there a way to change the default ".gradle" folder location so it's not deleted by my build process?
I'm using gradle 3.5.1, will soon update to 4.0

I also tried --build-cache but it's incubating and my needs are really simple.

Thanks

**Comment by bmuschko** [comment]
Does the Jenkins RTC plugin delete the `.gradle` folder? There's no point in doing so. If yes, I'd suggest that you open an issue with them. I am not aware of a way to change the default directory for the project's inputs/outputs cache.

**Comment by regrog** [comment]
Yes I think it's RTC plugin that delete the `.gradle` folder, but because gradle is highly configurable I thought that maybe there is a way to do that.

**Comment by regrog** [comment]
I found a solution.
I put the folder in ignore so the RTC doesn't delete it during the build phase.
