### ISSUE TITLE
`--no-rebuild` suddenly gone without new deprecation cycle and without the reason for its undeprecation being void

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#23888]
A little timeline of what happened:

Oct 4, 2017
https://github.com/gradle/gradle/issues/3077
"Deprecate --no-rebuild"
issue created

Oct 18, 2017
https://github.com/gradle/gradle/pull/3121
"Deprecate --no-rebuild"
flag deprecated

Aug 9, 2018
https://github.com/gradle/gradle/issues/6305
"Remove --no-rebuild"
issue created

Sep 27, 2018
https://github.com/gradle/gradle/pull/6917
"Remove -a/--no-rebuild command line option"
pull request created, but not merged
it was decided to not do this step until #6045 is resolved which it still is not
instead it was decided to undeprecate the flag
unfortunately #6305 was not closed along

Oct 1, 2018
https://github.com/gradle/gradle/issues/6968
"Undeprecate --no-rebuild and document its usefulness when working on buildSrc"
issue created

Oct 11, 2018
https://github.com/gradle/gradle/pull/7319
"Undeprecate --no-rebuild"
flag was undeprecated and is since then

Dec 6, 2022
https://github.com/gradle/gradle/pull/22992
"Remove --no-rebuild command line option"
now suddenly the flag got removed without prior warning, without deprecation, without the #6045 being resolved and without the flag being less useful for those who know to use it wisely

Please reintroduce the flag.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Good catch. We will fix that in the next 8.x release. Right now this is 8.1 but it might change if we decide to do an 8.0.1.

**Comment by ljacomet** [comment]
Will be fixed in 8.0.1

**Comment by Vampire** [comment]
Nice, many thanks for the quick restoration. :-)
