### ISSUE TITLE
Deprecate Test task default classpath and testClassesDirs

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#23883]
Standalone Test tasks are configured so that their `testClassesDirs` and `classpath` properties match those of the default `test` TestSuite. This convention is often unnecessary, as users should be configuring this themselves.

**Comment by iseki0** [comment]
So what should I use? There's no document tell me the replacement.

**Comment by jvandort** [comment]
The upgrade guide shows how to restore existing behavior https://docs.gradle.org/current/userguide/upgrading_version_8.html#test_task_default_classpath

**Comment by idontusenumbers** [comment]
Seems like I'm stuck between using the old way, resulting in a deprecation warning, or the new way, resulting in an incubation warning. Is this the intended outcome? Am I missing something?

**Comment by th3n3rd** [comment]
> Seems like I'm stuck between using the old way, resulting in a deprecation warning, or the new way, resulting in an incubation warning. Is this the intended outcome? Am I missing something?

@idontusenumbers I found an alternative that compiles with no warnings

```kotlin
tasks.register<Test>("myTestTask") {
    testClassesDirs = sourceSets["test"].output.classesDirs
    classpath = sourceSets["test"].runtimeClasspath
}
```
