### ISSUE TITLE
Configuration cache failure when tasks are excluded by path

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#23885]
If a project with Gradle 8.0 uses configuration cache and either excludes some tasks programatically or via CLI by providing a path, the build fails with either

> Project with path ':' not found in build 'buildSrc'

or

> Cannot locate excluded tasks that match [requested path] as project ‘[project of request path]’ not found in root project ‘[root project name]’.

### Steps to Reproduce 
https://github.com/ALikhachev/excluded-tasks-configuration-cache-repro
The repo contains a README file.

It shows how to reproduce the first failure. If you remove the `buildSrc` module, it will fail with the second failure.

Excluding tasks by name, e.g. `./gradlew -x jar` works fine.

**Comment by adammurdoch** [comment]
This was fixed as part of some other improvements in 8.1. Added some more test coverage for this case in https://github.com/gradle/gradle/pull/23906.
