### ISSUE TITLE
AwsCredentials for external maven repository

### ISSUE THREAD

**Issue by ViktorZieg** [gradle/gradle#23898]
### Expected Behavior

As states in the [documentation](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials) it should be possible to use `AwsCredentials` as the credential parameter when configuring an additional repository.
Example: 
```
repositories {
    mavenCentral()
    maven {
        name = "MyCodeArtifact"
        url =
            uri("https://myCodeArtifact.url/")
        credentials(AwsCredentials::class)
    }
}
```

### Current Behavior

When trying to use `AwsCredentials` I get an error saying 
> Credentials must be an instance of: org.gradle.api.credentials.PasswordCredentials or org.gradle.api.credentials.HttpHeaderCredentials

### Context

 In this case it is an CodeArtifact repository which I would like to use. `AwsCredentials` looks very convenient as it just needs an AccessKey and SecretKey to be used.

### Your Environment

Happens on Gradle 7.6 and 8.0

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

For using AWS you need to use a `s3://` url protocol.
https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials:~:text=Example%2025.-,Declaring%20an%20S3%20backed%20Maven%20and%20Ivy%20repository,-Kotlin

**Comment by eskatos** [comment]
Connecting to AWS CodeArtifact repositories doesn't use `AwsCredentials` but simple regular authentication. This is documented at https://docs.aws.amazon.com/codeartifact/latest/ug/maven-gradle.html
