### ISSUE TITLE
Improve interaction between native libaries and daemon

### ISSUE THREAD

**Issue by Lactose94** [gradle/gradle#23893]
Pushing a new version of a plugin while the daemon is running after an application of the plugin  leads to an invalid state, where the native can neither be loaded nor its functions are available.

### Expected Behavior
Initializing a native library with `System.loadLibrary("<native>")` or `System.load("<path-to-native>")` should work on subsequent applications of the plugin even if the daemon is running and if a new version of the plugin is pushed (to localMaven). 

### Current Behavior
Applying a plugin that loads a native library with `./gradlew <command>` (which starts the daemon), then pushing a new plugin version to localMaven and then running any other `./gradlew <command>` that involves loading of the native leads to an 
```
UnsatisfiedLinkError: Native <LIB> already loaded in another classloader
```
Detecting that the native is already loaded and skipping initialization following the steps [here](https://github.com/ninia/jep/issues/214) and then trying to use any native function, leads, for example, to
```
UnsatisfiedLinkError: 'java.lang.String <NATIVE-METHOD>(int)'
```
Thus, the plugin is in a state where it simultaneously already has and has not loaded the library (in the correct classloader). 

### Context

I am working on a Gradle plugin that for performance and reusability reasons depends on a native library that provides an JNI interface. 
Due to the unexpected behavior described above, testing of the plugin on a small app becomes then somewhat tedious, as frequent reloads of the daemon or running without it is necessary for each iteration of the plugin.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a native limitation for a long running process. We have no plans on lifting that limitation.

You have two options:
- use the Worker API with [process isolation](https://docs.gradle.org/current/userguide/worker_api.html#creating_a_worker_daemon) so you get a new process on  each invocation
- run with no Gradle daemon for testing
