### ISSUE TITLE
[Plugin Publish Plugin] Provide a publishing validation task

### ISSUE THREAD

**Issue by melix** [gradle/gradle#23908]
### Expected Behavior

There should be a task which you can run independently of `publishPlugins` which performs the validations that `publishPlugins` does.

### Current Behavior

Some errors only occur at publishing time.

### Context

After updating the plugin, I had builds passing (tests, `validatePlugins`, etc) and assumed that publishing would work.
What a mistake: I had 3, consecutive, errors:

- [Website URL missing](https://ge.micronaut.io/s/2pwjqtuxc45zc/failure?focused-exception-line=0-1-0#1)
- a [bug with tags](https://ge.micronaut.io/s/gc4mhkpi5ewwu/failure?focused-exception-line=0-1-0#1)
- then another [bug with tags which are apparently mandatory despite the `getTags()` method being incubating](https://ge.micronaut.io/s/kctxj5nz3hrmw/failure?focused-exception-line=0-1-0#1)

I would have appreciated a way to discover those problems _before_ releasing. Especially because we have lots of automation in place, and that a failing release implies manual fixing.

My suggestion is therefore to add a `validatePublishing` task, which performs the validation which is currently part of `publishPlugins` itself.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by ljacomet** [comment]
This feature will be available with the version `1.2.0` of the [`com.gradle.plugin-publish`](https://plugins.gradle.org/plugin/com.gradle.plugin-publish) plugin to be released later today.
