### ISSUE TITLE
Signing 6 jar files in parallel using Jarsigner command in gradle task produces .sig file for few instead of .jar extention after signing 

### ISSUE THREAD

**Issue by AnnapoorniS** [gradle/gradle#2390]
I am trying to sign the jar in dolast() of jar task  in parallel for 6 jars, some jars are produced with .sig extention instead of .jar extention

### Expected Behavior
All the signed jars should be of extention .jar  
Kindly let me know what changes should I do to get signed jar for all the modules when I run the task jar 

### Context
I need to publish the jars to artifactory and thus require replacing the  jar.archivePath with the signed jar 
I need the jar to be signed once created using the six java library from my android gradle task and publish the signed jars and poms to artifactory  

### Steps to Reproduce (for bugs)
jar << {
            def keystoreFile = 'sample.keystore'
            def keystorepass = 'password'
            def keyalias = 'sample'
            def exec_line = "jarsigner "+ " -keystore " + keystoreFile + " -storepass " +
                    keystorepass + " -keypass "+ keystorepass +" -verbose " + jar.archivePath +" "+ keyalias
    print  exec_line
    exec_line.execute()
}
### Your Environment
 Android 7.1 
Six java library module

Produces sample.jar.sig file. But, my requirement is sample.jar file i.e. signed sample.jar file in the same jar.archivePath so that I can publish.

**Comment by bmuschko** [comment]
[This portion of the user guide](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signing_tasks) explains how to sign JARs other than the one created by the Java plugin. Did you have a look at that?

**Comment by AnnapoorniS** [comment]
Yes l tried using the plugin but it produces a signature(.asc ) file along with unsigned jars. 
But, the requirement is to sign all my 6 jars in the jar archives with the same extention (.jar ) and need to push those signed jars into artifactory along with its pom. Kindly suggest me if there are any alternate ways in which I can achieve this 
Thanks in advance.

**Comment by PantherDD** [comment]
For the record: #1339 is a feature request for adding `jarsigner` support to Gradle.
