### ISSUE TITLE
Reduce `OutputEventRenderer.onOutput()` locking by refine lock granularity

### ISSUE THREAD

**Issue by TheDadda** [gradle/gradle#23919]
### Expected Behavior
Reduce `OutputEventRenderer.onOutput()` locking by refine lock granularity

### Current Behavior

Multithreading creates many lock races when finally calling `OutputEventRenderer.onOutput()` while logging, waiting about 500,000 times

### Context

We support parallel config on our gradle version to optimizing the configuration phase time, and i found that threads were waiting for `OutputEventReanderer.lock`.

I try to reduce locking by refine lock granularity：
- Remove OutputEventRenderer.lock invoked by onOutput()
- Add synchronization logics to OutputEventTransformer class. 

Lock waiting counts reduced from 50,0000 to 3k, and it can save about 4s - 6s.

Below are some screenshots during debugging:
![969acbe6-b213-4d03-986b-e5a654a38ccd](https://user-images.githubusercontent.com/125425242/219300424-bdbed084-928c-4d76-b25b-243309772db5.png)
![ef23bb61-87c3-43ed-81df-b37cb422197d](https://user-images.githubusercontent.com/125425242/219300563-e515df22-cc22-4f4e-a8b1-64c26d1f58d6.png)
![67713e27-f0b9-4e6c-b93d-6a550a97aa42](https://user-images.githubusercontent.com/125425242/219300580-c96be91b-02bd-4c1a-9b55-8269e0f87cfc.png)

**Comment by eskatos** [comment]
@bot-gradle test RFM, APT

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Thank you for the PR. The changes make sense and look good. We triggered CI validation and will follow up.
