### ISSUE TITLE
Backport "Use Compiler API data for incremental compilation after a failure" to 7.x

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#23922]
For Gradle 8.1 we improved incremental compilation after failure compared to previous implementation. We should backport that to 7.x.

- [x] #23119 – https://github.com/gradle/gradle/pull/23913
- [x] #23251 – https://github.com/gradle/gradle/pull/23913
- [ ] #23226

**Comment by lptr** [comment]
Merged in 7.6.1: https://github.com/gradle/gradle/pull/23913

**Comment by lptr** [comment]
We have a fix for the behavior, but we have a better solution in #23226 that can be backported to 7.7.

**Comment by asodja** [comment]
Fixed with https://github.com/gradle/gradle/pull/25183.
