### ISSUE TITLE
Update Spring Boot Gradle plugin smoke test to 3.x

### ISSUE THREAD

**Issue by donat** [gradle/gradle#23937]
Currently, we are smoke testing the 2.x stream.

Also update documentation snippets and samples.

**Comment by ljacomet** [comment]
Note that this will require to run these tests with Java 17 as it is the minimal supported version.

**Comment by eskatos** [comment]
Also note that there are snippets/samples currently using boot 2.x that should be updated too.

**Comment by tresat** [comment]
We're currently smoke testing [version 3.2.1](https://github.com/gradle/gradle/blob/7bc4e14fb25bf578b7adb5e93fd74c7094aaf0c5/subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy#L93).
