### ISSUE TITLE
Typo in v7.6 docs about disabling_the_daemon

### ISSUE THREAD

**Issue by abelsromero** [gradle/gradle#23941]
Silly typo, the command is `--no-daemon`, but the example misses a hyphen. v8.0. and 7.5 are correct.

![image](https://user-images.githubusercontent.com/5781153/219673266-0e82aa79-81a0-40b2-8511-06a60a73ff2d.png)

**Comment by ljacomet** [comment]
Thank you for the report. This has already been fixed and will be in the upcoming 7.6.1
