### ISSUE TITLE
Clean up Gradle configuration caches periodically

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#23957]
This issue is identical to #1085, except that it is about _configuration cache_, which currently does not appear to periodically be cleaned up. I noticed this after observing the `.gradle/configuration-cache` folder in my project was 15GB

![image](https://user-images.githubusercontent.com/1361086/219823168-da573cd1-c948-42d3-a031-417f8226c597.png)

**Comment by ghale** [comment]
There is already an automatic cleanup for the configuration cache which should occur no more than once every 7 days.  I suspect one of two things is happening: either the cleanup is not occurring, or it is occurring, but there is something in there that's consuming a lot of space and is not eligible for cleanup.

So, one thing you can check is whether there is a `.gradle/configuration-cache/gc.properties` file.  If there is, then we know that cleanup has occurred at least once.  The timestamp of that file will tell you when the cleanup last occurred.  It should be sometime within the last 7 days if it's working as expected.

**Comment by ZacSweers** [comment]
Apologies but I've already deleted this directory as I found out while trying to reclaim space on my machine. I'll keep an eye out. I've never seen a log after a build about cleaning old configuration cache entries though (compared to the build cache pruning), is it done silently?

**Comment by ghale** [comment]
I'm pretty sure it will output a progress message similar to the build cache, but I suspect it's fairly quick in comparison as the configuration cache is likely to have many, many fewer entries than the build cache, so searching for eligible entries is likely to be pretty fast.

**Comment by eskatos** [comment]
I can confirm I have a `.gradle/configuration-cache/gc.properties` file modified recently and a reasonable amount of entries in `.gradle/configuration-cache/`.

@ZacSweers, when that directory gets repopulated on your machine it would be interesting to drill down into large entries and see what takes so much space. You could use https://github.com/gradle/gcc2speedscope to figure out if some unneeded large object graphs aren´t needlessly serialized. Reducing state size would make the CC faster.

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

----

Configuration cache state cleanup is working. To investigate further we would need a way to reproduce. As I wrote above it might be because the state for your build is huge.

**Comment by ZacSweers** [comment]
I reproduced it again, currently at ~6GB and growing after just a few days. I see a `gc.properties` file present, but its contents are empty.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/1361086/221013345-fb0031a7-6d39-42f0-983b-cc24b45cb47c.png">

> figure out if some unneeded large object graphs aren´t needlessly serialized

This isn't super actionable to someone that doesn't work on Gradle, what are we looking for and what can we do about it? I can't reproduce this in a public project, I assume because it's largely dependent on the size of the project.

I'm also unable to create a `speedscope.json` file, it's been running for around 30 minutes now with no progress indication. Will let it continue running and, if it's successful, I could share it privately if that helps?

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/1361086/221015974-a3ca459e-3233-48a7-988c-aae174f650d1.png">

**Comment by ZacSweers** [comment]
Actually scratch that, it OOM'd right after my previous comment

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.LinkedHashMap.newNode(LinkedHashMap.java:257)
        at java.base/java.util.HashMap.putVal(HashMap.java:637)
        at java.base/java.util.HashMap.put(HashMap.java:618)
        at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:407)
        at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:578)
        at kotlin.collections.MapsKt__MapsKt.mapOf(Maps.kt:55)
        at gcc2speedscope.AppKt.speedscopeLogFor(App.kt:126)
        at gcc2speedscope.AppKt.parseConfigurationCacheDebugLog(App.kt:99)
        at gcc2speedscope.AppKt.main(App.kt:27)

```

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

**Comment by bamboo** [comment]
> it OOM'd right after my previous comment

Ouch. Thanks for the report.

**Comment by ZacSweers** [comment]
Thanks. Primary question still stands though

> This isn't super actionable to someone that doesn't work on Gradle, what are we looking for and what can we do about it?

**Comment by patsevanton** [comment]
i think my problems is this issue.
I have huge directory `/tmp/gradle/transforms-3` with 131.7 GiB:
with contents:
```
  110.4 MiB [##########] /faf07f1d98f11af2707b31caba941da0
  110.4 MiB [##########] /fa0e1f94e6958816ee3ddcd2a9cb1473                                                                                               
  110.4 MiB [##########] /f479af0e69acb8af1ddbf76b5b004173
  110.4 MiB [##########] /f20af54de037cc98903535470808fb77
  110.4 MiB [##########] /f1056cb16e7c0b645214774995843f73
  110.4 MiB [##########] /f089713037da127ff108711d6e69a279
  110.4 MiB [##########] /ea889084ec431c318fec034efb59826e
```
how do I set up so that the directory does not swell in size?

**Comment by bamboo** [comment]
Hi @patsevanton, 

You can adjust the retention period of the different Gradle caches, see [Configuring cleanup of caches and distributions](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:configure_cache_cleanup) in the Gradle user guide.
