### ISSUE TITLE
gradlew fails on POSIX systems that do not bundle which nor define JAVA_HOME

### ISSUE THREAD

**Issue by didot** [gradle/gradle#23960]
### Expected Behavior

The gradlew wrapper script works on POSIX systems that do not
bundle the `which` utility, and do not set the JAVA_HOME environment
variable either.

### Current Behavior

The gradlew wrapper script fails, printing the error message:

```
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

### Context

In order to workaround the issue, I either have to install which, or I
have to set the JAVA_HOME environment variable.

### Steps to Reproduce 

The following command reproduces the error message:

```
cd a-gradle-project
docker run --rm -it -v "$(pwd):$(pwd)" -w "$(pwd)" library/rockylinux:9-minimal sh -c "
  set -ex;
  microdnf --assumeyes install java-17-openjdk sudo;
  echo -e 'root ALL=(ALL:ALL) ALL\nDefaults runas_allow_unknown_id' >>/etc/sudoers;
  sudo -u '#$(id -u)' -g '#$(id -g)' ./gradlew --version || java --version"
```

The command prints:

```
(...)
+ sudo -u '#501' -g '#20' ./gradlew --version

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

+ java --version
openjdk 17.0.6 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-3.el9_1) (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-3.el9_1) (build 17.0.6+10-LTS, mixed mode, sharing)
```

### Your Environment

See 'Steps to Reproduce' section above.

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

***

Thank you for offering a PR. Maybe as a compromise, we could modify the script so it tries both `which` and `command` and will not fail as long as one of them is available.
