### ISSUE TITLE
Android studio 3.0 canary 5 Gradle 4.1-milestone-1

### ISSUE THREAD

**Issue by Paget96** [gradle/gradle#2396]
### Current Behavior
Application compiles fine, but when someone install application it makes another package inside /data/app

com.package.aaa-1 & com.package.aaa-2

Also right after installation is finished, other apps started to crash, first one is Google Play Services, then all other.

### Context
If device is not rooted there is no way to recover device since it starts rebooting over and over again falling into a boot loop.
For rooted, simple remove package from /data/app over TWRP
Reverting back to gradle plugin 2.3.3 and Gradle 4.0 solves the issue.

**Comment by bmuschko** [comment]
The issue you are experiencing is very likely a bug in the Android plugin or Android Studio. Would you mind [opening an issue with Google on the respective forum](https://code.google.com/p/android/issues)? They are creating the plugin as well as Android Studio and are far more likely you help you with this.
