### ISSUE TITLE
Gradle 8.0 log volume eats up disk space quickly

### ISSUE THREAD

**Issue by hkupty** [gradle/gradle#23974]
I noted recently by running a few tests and I noticed that gradle is logging a substantial amount if information.

While I think it is ok, in a span of just a few days from the release that I've been using it, it seems to have consumed ~570GB of disk space with the logs.

It can be that a) the arch linux package is being shipped with a very high debug level on (say trace) and/or b) gradle is lacking some cleanup/log rollout feature in the ~/.gradle/daemon/8.0.1 folder which makes this an ever increasing file.

### Expected Behavior

Gradle cleans up after old logs

### Current Behavior

gradle logs @ `~/.gradle/daemon/8.0.1/` are consuming disk space reasonably fast.

### Context

I got some notifications from intellij after running a few iteractions of JMH tests that my disk space was empty.
Given the jmh tests were not necessarily involving disk, I felt there was a bug in my app but, after investigating further I noticed the folder that was using the more disk space was located in my home directory, which turned out to be `~/.gradle`.

### Steps to Reproduce 

Not really sure if there's anything specific for reproducing my exact issue - consuming 570gb in a few days worth of test. But I can say that I've been running gradle continuously for my tests for the past days on my arch linux machine. 

### Your Environment
arch linux, fairly updated;
```

------------------------------------------------------------
Gradle 8.0.1
------------------------------------------------------------

Build time:   2023-02-17 20:37:16 UTC
Revision:     <unknown>

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (Oracle Corporation 17.0.6+10)
OS:           Linux 6.1.11-arch1-1 amd64
```

Build scan URL: not sure if relevant, but I can provide one if we decide that it is.

**Comment by alphanumericaracters** [comment]
Im workking wit flutter, gradle cache folder it's about 2.9 gb (now)

before flutter clean was 6.9 gb

![gradle](https://github.com/user-attachments/assets/7e6ac916-ee38-4b01-b042-d13cfe1ee7db)
