### ISSUE TITLE
Introduce build-session-scoped services

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#23984]
### Expected Behavior

For configuration cache compatibility, Gradle should provide means to register a shared service (like `BuildService`) that is not closed at the end of a build but at the end of a _build session_.

### Current Behavior

Currently, I'm not aware of any non-hacky way of doing this.

### Context

My use case is starting a local web server from within the build and using `--continuous` to re-generate the files it serves based on input changes.

**Comment by alllex** [comment]
Gradle project would benefit from this feature as well. Specifically, when working on the Gradle docs it would allow rebuilding the docs on changes, but keep the same server running and serving the docs locally.

- https://github.com/gradle/gradle/issues/23157

Possibly more context provided previously on the related topic:
- https://github.com/gradle/gradle/issues/1367#issuecomment-325425976

**Comment by melix** [comment]
Duplicate of https://github.com/gradle/gradle/issues/20867

**Comment by marcphilipp** [comment]
Duplicate of #20867
