### ISSUE TITLE
Provide option to not expire daemon when running out of memory

### ISSUE THREAD

**Issue by lwasyl** [gradle/gradle#24026]
Currently when gradle daemon is close to running out of memory, it will output:

```
The Daemon will expire after the build after running out of JVM Metaspace.
The project memory settings are likely not configured or are configured to an insufficient value.
The daemon will restart for the next build, which may increase subsequent build times.
These settings can be adjusted by setting 'org.gradle.jvmargs' in 'gradle.properties'.
The currently configured max heap space is '10.6 GiB' and the configured max metaspace is '7 GiB'.
For more information on how to set these values, visit the user guide at https://docs.gradle.org/8.0/userguide/build_environment.html#configuring_jvm_memory
To disable this warning, set 'org.gradle.daemon.performance.disable-logging=true'.
Daemon will be stopped at the end of the build after running out of JVM Metaspace
```

However, having an option to _not_ stop the daemon would be useful when debugging memory issues, where an OOM would trigger memory dump for analysis. Currently one has to manually trigger heap dump from an external tool, which requires carefully setting memory settings such that memory leak is noticeable but Gradle daemon doesn't stop so a heap dump can be captured.
Alternatively, Gradle could offer to capture a heap dump in such case itself.

**Comment by lwasyl** [comment]
I just stubled upon https://docs.gradle.org/current/userguide/gradle_daemon.html#performance_monitoring, which means
```
org.gradle.daemon.performance.enable-monitoring=false
```
is what I want? :thinking:

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Yes this will disable the monitoring.
If you want a heap dump on memory errors, use the JVM option `-XX:+HeapDumpOnOutOfMemoryError`.

Also FYI, see
* https://github.com/gradle/gradle/issues/23698
