### ISSUE TITLE
Add Groovy 4.0.9 to test coverage

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#24020]
- Changelog for [Groovy 4.0.9](https://groovy-lang.org/changelogs/changelog-4.0.9.html)
- Changelog for [Groovy 4.0.8](https://groovy-lang.org/changelogs/changelog-4.0.8.html)  [Released: 2023-01-19]
- ~Changelog for [Groovy 3.0.14](https://groovy-lang.org/changelogs/changelog-3.0.14.html)  [Released: 2022-12-21]~
  - Groovy 3.0.15 added here: https://github.com/gradle/gradle/pull/23887

**Comment by alllex** [comment]
It seems Groovy 3.0.14 still does not support Java 20, so this issue should be fixed after
- https://github.com/gradle/gradle/pull/24019

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is in the backlog of the relevant team and is prioritized by them.
