### ISSUE TITLE
Public API for defining and parsing custom command line options for tasks

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#2402]
Gradle defines an internal API for defining custom command line options for tasks in the package `org.gradle.api.internal.tasks.options`. Many users are interested in using the feature in their plugins.

### Expected Behavior

Tasks can define custom command line options for exposed properties with the help of a public API. The follow example demonstrates how the use of `@Option` could look like for a task that comes with the [Spring Boot plugin](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html).

```
task bootRun(type: BootRun)

public class BootRun extends DefaultTask {
    private String bootRunArg;
    private String bootRunJvmArg;
    private String profile;
    private List<String> multiValues;

    @Option(option = "bootRunArg", description = "The Spring Boot run arguments.")
    public void setBootRunArg(String bootRunArg) {
        this.bootRunArg = bootRunArg;
    }

    @Option(option = "bootRunJvmArg", description = "The Spring Boot JVM arguments.")
    public void setBootRunJvmArg(String bootRunJvmArg) {
        this.bootRunJvmArg = bootRunJvmArg;
    }

    @Option(option = "profile", description = "The active Spring profile.")
    public void setProfile(String profile) {
        this.profile = profile;
    }
    
    @Option(option = "multiValues", description = "A multi-value String.")
    public void setMultiValue(List<String> multiValues) {
        this.multiValues = multiValues;
    }
    
    @TaskAction
    public void run() {
        System.out.println("bootRunArg: " + bootRunArg);
        System.out.println("bootRunJvmArg: " + bootRunJvmArg);
        System.out.println("profile: " + profile);
        System.out.println("multiValues: " + multiValues);
    }
}
```

Usage from the command line:

```
gradle bootRun --multiValues=--spring.profiles.active=random --multiValues=--server.port=8080 --bootRunArg=--spring.profiles.active=random
```

### Current Behavior

Users have to use an internal API to define custom command line options for tasks. Internal APIs can change at any time and break published, external plugins.

### Context

- https://discuss.gradle.org/t/command-line-options-for-tasks/9686/7
- https://discuss.gradle.org/t/expose-the-org-gradle-api-internal-tasks-options-option-annotation-for-use-in-user-tasks/319
- https://discuss.gradle.org/t/parameterizing-tasks-with-option-in-org-gradle-tooling-gradleconnector/6343/3
- https://discuss.gradle.org/t/org-gradle-api-internal-tasks-options-option-not-available-for-own-tasks/21335

**Comment by adammurdoch** [comment]
There are some issues with the current implementation that we should consider addressing as part of adding a public API:

1. The task must be referenced on the command-line, eg I can't do `gradle check --tests abc` but instead need to do something like `gradle check test --tests abc`
2. There are no global options, which is arguably what `--tests` should be.
3. It's awkward for tasks that need to forward command-line arguments, e.g. I can't do something like `gradle run app-arg1 app-arg2 --some-arg-for-the-app` but must do something like `gradle run --args "app-arg1 app-arg2 --some-arg-for-the-app"`

We shouldn't block a public API on addressing these issues if we can't come up with a simple solution, because the current behaviour is fine. Just something to consider.

**Comment by wilkinsona** [comment]
This would be a welcome new feature for the users of Spring Boot's Gradle plugin. We have a long-standing [enhancement request](https://github.com/spring-projects/spring-boot/issues/1176) that led to me discussing this with @bmuschko at the recent Summit.

**Comment by bmuschko** [comment]
Thanks for your additional input, @wilkinsona. Would you be interested in providing a pull request for making the API public. Looks like nothing is speaking against the approach. Happy to provide the code review, feedback and anything need to get it merged!

**Comment by wilkinsona** [comment]
Yeah, I'm interested. It might be a little while before I can get some time to start taking a detailed look, though.

**Comment by wilkinsona** [comment]
I've taken a first pass at this and opened a [pull request](https://github.com/gradle/gradle/pull/2602) for review and refinement.
