### ISSUE TITLE
gradle cannot load HTTPS dependencies on RHEL8 in FIPS mode 

### ISSUE THREAD

**Issue by danielcranford** [gradle/gradle#24022]
Gradle dependency resolution over HTTPS uses buggy code copied from the httpclient project to instantiate the SSLContext used to make HTTPS connections. cf https://github.com/gradle/gradle/blob/master/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/DefaultSslContextFactory.java#L115-L258  This code was fixed in httpclient 4.2.4 ten years ago - cf https://issues.apache.org/jira/browse/HTTPCLIENT-1320 

When the user runs gradle using a jvm where the default keystore type is incompatible with the format of the JDK CA store, the SSLContext created by gradle is configured to have **zero CAs** which causes a fatal error when the SSL connection is made. When RHEL8 is running in fips mode, the RHEL8 jdk 11 default keystore type is `PKCS11` which is incompatible with the JDK CA store format of JKS.

 There is no guarantee that the system trust store is formatted in the default keystore format. The default system trust store may be obtained by calling `SSLContext.getDefault()` or by specifying `null` for the second argument to `SSLContext.init(..., null, ...)` or by initializing the TrustManagerFactory with a null keystore `TrustManagerFactory.init((KeyStore)null)`

Additionally, this error is not propagated, and gradle reports to the user that the resource is not available in the repository.
```
* What went wrong:
Plugin [id: 'com.dorongold.task-tree', version: '2.1.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.dorongold.task-tree:com.dorongold.task-tree.gradle.plugin:2.1.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
``` 

The SSL connection exception is not even logged by gradle, and thus not exposed even if the build is run with `--debug --stacktrace` The only way I could observe it was running in a JVM with `-Djavax.net.debug=ssl` set at JVM startup (since this logging property gets loaded into static class fields when JDK core classes get loaded). The lack of error seems like an HTTP client configuration error, since the SSL exception is correctly propagated when gradle's SSLContext is used by the default JDK HTTP client, `java.net.URL` via `HttpsURLConnection.setDefaultSSLSocketFactory()`

### Expected Behavior
In the absence of explicit configuration Gradle dependency resolution should use the system default SSLContext instead of trying to create one that is configured identically to the system default. Additionally, gradle should propagate SSL errors instead of pretending that an SSL connection error means the dependency is unavailable.

### Current Behavior
When gradle resolves a dependency from an HTTPS URL and the JDK default keystore type is neither `PKCS12` nor `JKS`, gradle creates and uses a SSLContext that fails to load the JDK provided cacerts keystore which leads to the SSL connection failing. Additionally, gradle fails to propagate the SSL error and instead reports to the user that the dependency was not present in the remote repository.

### Context
All our gradle builds will not work on RHEL8 when fips is enabled,

### Steps to Reproduce 
Reproducing is a lot more difficult due to #22292 and #2214 as they prevent setting command line system properties for the java process running the build. See https://github.com/danielcranford/gradle-ssl-bug for a simple build file that will demo bug when run in proper environment.

Normally, it would be sufficient to run a build in a java process that is **started** with -`Djava.security.properties=path/to/security-overrides.properties` where the contents of security-overrides.properties is 
```
keystore.type=PKCS11
```

Since this is difficult/impossible due to the aforementioned bugs, the easiest/only way to reproduce is to edit `$JAVA_HOME/conf/security/java.security` to set `keystore.type=PKCS11` (or `fips.keytore.type=PKCS11` if running in fips mode)

Note also, that the dependency being retrieved must not be present in the gradle cache, and the gradle daemon must be avoided via `--no-daemon` since security properties are retrieved at JDK class load time and thus are immutable within a single java process.

### Your Environment
Running on RHEL8 in fips mode with java-11-openjdk-11.0.17.0.8-2.el8_6.x86_64

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.
