### ISSUE TITLE
Android Gradle 7.4.2 with AGP 7.3.1 takes too long on first run when testCoverageEnabled is true

### ISSUE THREAD

**Issue by deepueg** [gradle/gradle#24048]
I have an android project that I am updating from Gradle `7.2 -> 7.4.2` along with AGP `7.1.2 -> 7.3.1`. The first `assembleDebug` run takes more than **1 hour** to complete with the following configuration. 

The gradle gets stuck at `~98%` on `mergeExtDexGoogleDebug` and takes more than 1 hour to complete ( first time only).  There are no logs printed ( with --debug) makes it difficult to debug this issue.  

The subsequent builds are quicker until the `~/.gradle/caches/build-cache-1` is cleared. Which means, we just need to clear the cache to reproduce this issue.  This is mainly problematic on our CI machines. 

```
android {
    buildTypes {
        debug {
            testCoverageEnabled = true
        }
    }
}
```

With `testCoverageEnabled = false` build completes normally. 

### Expected Behavior
Setting `testCoverageEnabled = true` should not impact total build time. If it does, a proper log or timeout with exception would help resolve this. 

### Current Behavior
First time `assembleDebug` on the android project takes more than one hour to complete with `mergeExtDexGoogleDebug` takes the longest to complete with zero logs.

### Context

Gradle 7.4.2
AGP 7.3.1

This affects the first build on developer machines and pretty much all CI jobs
Currently forced to disable test coverage to move forward with this version of gradle.

### Steps to Reproduce 

This might be related our project being large. The same setup on a sample android project works fine, but I guess the size of the project and dependencies are a matter here?  Ideally, not having anything in the logs during `mergeExtDexGoogleDebug` makes it harder to investigate this issue further.   

### Your Environment

Development

Build scan URL:

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug

***

Both dexing and testCoverageEnabled are AGP-specific things, so need to file this issue with them.

**Comment by deepueg** [comment]
Thanks @jbartok .  Got this working with AGP version 7.1.2 though it's not the compatible version of AGP recommended for 7.4 by google. Opened a ticket to track this: https://issuetracker.google.com/issues/270876605 Adding it here for reference.

**Comment by Prakhar-kuls** [comment]
@deepueg did you find anything on this?
