### ISSUE TITLE
Use colored progress bar to indicate build pass/failure state

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2404]
### Expected Behavior
Make the progress bar green unless any tasks have failed, then turn it red

### Current Behavior
Currently no color is used for console

### Context
This is a nice, visible improvement that should hopefully be quite simple.

**Comment by adammurdoch** [comment]
yes please. I'd love this on the task header as well.

**Comment by eriwen** [comment]
@adammurdoch ah, such a good idea, though I'd say just make failed tasks red (don't make successful tasks green)

**Comment by adammurdoch** [comment]
yes that's probably best

**Comment by jjohannes** [comment]
PR: https://github.com/gradle/gradle/pull/2447
