### ISSUE TITLE
Erroneous "Configure modules in XXX project" notification

### ISSUE THREAD

**Issue by ParticleCore** [gradle/gradle#24041]
### Expected Behavior
Shouldn't keep insisting to configure kotlin in the modules when they are already configured

### Current Behavior

Every single time a new build is compiled the following pop-up shows up:

> Configure Kotlin
> Configure modules in XXX project

And it auto suggests the latest available kotlin version, which can be a **beta** or even a unstable **alpha** versions, completely disregarding which flavor the developer currently has, especially if the current flavor is stable versions only.

Every module is already configured with the latest kotlin version, yet if I decide to continue with the suggestion it automatically adds the following dependency to the gradle of all modules:

`implementation("androidx.core:core-ktx:+")`

Which in turn throws the following warning as a result:

`Avoid using + in version numbers; can lead to unpredictable and unrepeatable builds (androidx.core:core-ktx:+)`

So not only it incorrectly detects kotlin use in gradle, but also the suggestion to correct that issue is not recommended.

As it is this feature is absolutely useless.

### Steps to Reproduce 
Install Android Studio Electric Eel Patch 1 and use any latest stable kotlin version on a module project, and then run the project.

### Your Environment
Android Gradle Plugin Version: 7.4.1
Gradle Version? 7.6

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is an issue with Android Studio which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug
