### ISSUE TITLE
Worker API doesn't support null parameters

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2405]
If a parameter used when configuring the worker is `null`, a `NullPointerException` is thrown. In practice, it means that we cannot use `null` parameters, which is very impractical.

### Expected Behavior

`null` should be allowed when configuring the worker:

```
workerExecutor.submit(JApiCmpWorkerAction.class, new Action<WorkerConfiguration>() {
            @Override
            public void execute(final WorkerConfiguration workerConfiguration) {
                 workerConfiguration.params(
                      nonNullValueIsAccepted,
                      null // should be accepted
            }
}
```

### Current Behavior

When the worker configuration block is executed, a null pointer exception is thrown, because we collect the argument types from the actual runtime values:

```
Iterable<Class<?>> paramTypes = CollectionUtils.collect(configuration.getParams(), new Transformer<Class<?>, Object>() {
            @Override
            public Class<?> transform(Object o) {
                return o.getClass();
            }
        });
```

### Context

I faced this problem when migrating my japicmp plugin to use the worker API. Some parameters are optional (HTML report file, TXT report file, ...). When `null`, it means that the report should not be generated. However, even if I decided to use a boolean to tell, I would still need to pass all parameters to the worker, which would mean passing `null`.

How I worked around this: I have created a serializable `JapiWorkerConfiguration` class, which wraps all the parameters, and is also used as a superclass of the runnable. It works but adds a bit of boilerplate, and it should be considered an anti-pattern.

**Comment by eriwen** [comment]
@ghale just curious if this is still in progress?

**Comment by ghale** [comment]
Actually, it's not.  I had started working on it, but then got pulled off on higher priority tasks.  This still needs to be fixed, and I am more than happy to do so, but I've moved it to the icebox for now as I am not sure when I'll be able to get back to it.

**Comment by k-mack** [comment]
@ghale I also ran into this, and I attempted to fix the issue. Not sure if it will be an acceptable solution, but I submitted a PR just in case.

**Comment by stmlange** [comment]
Sadly still an open issue :-(    

+1 on getting it fixed

**Comment by ymwang1984** [comment]
+1 on getting it fixed. It impacts developer productivity.

**Comment by grv87** [comment]
If you have Guava in classpath, you could use their serializable [`Optional`](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/Optional.html)

**Comment by eriwen** [comment]
@big-guy @ghale Szczepan and Yiming discussed with me at the SF Forum conference how this makes adopting the Worker API very painful. Is there more information we could provide such that this might get back on our radar on your team?
