### ISSUE TITLE
The source code of some javaFx classes is no longer accessible at debugging in Eclipse

### ISSUE THREAD

**Issue by Graou74** [gradle/gradle#24051]
### Expected Behavior
When in debug mode the program stops on a line of code, the code of the class is visible.

### Current Behavior
Only on part of the JavaFx classes, during the debug, instead of displaying the source code of the class, the editor displays "Source not found" with a button entitled "Edit source lookup path ...".

### Context
This issue manifests in Eclipse 4.26.0 while it does not in Eclipse 4.25.0. I tried combinations with different versions of Gradle (7.6.1 and 8.0), different versions of JavaFX (16 and 19.0.2.1), different versions of JavaFX Gradle plugin (0.0.10 and 0.0.13) and different versions of JDK (15.0.4 and 19.0.2) but the result is always the same: Eclipse 4.25.0 = success and Eclipse 4.26.0 = failure.
Because of this, debugging becomes much less comfortable than before when certain JavaFX classes come into play.

### Steps to Reproduce 
In Eclipse 4.26.0 put a breakpoint on the javafx.stage.Window class (on the class declaration line) then launch in debug mode a JavaFX example which opens a window.
The source code of the class will not be accessible.

### Your Environment
MacOS 12.2
Eclipse 4.26.0
JDK 19.0.2
JavaFX 19.0.2.1
Gradle 7.6.1
JavaFX Gradle plugin 0.0.13

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is an issue with Eclipse, which cannot be addressed in the Gradle Build Tool project.

Please open such Eclipse-related issues on their Issue Tracker at https://bugs.eclipse.org/bugs/.
