### ISSUE TITLE
User-customizable logging

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2408]
As a user, I want to be able to control the amount of information I see from my Gradle build and where I get that information from.

### Expected Behavior
[Logging Design Spec](https://github.com/gradle/gradle/blob/master/design-docs/improved-logging.md)

### Current Behavior
Currently, Gradle captures logs from JCL, JUL, and other logging frameworks and routes them through a globally declared Logger. Only the log level is configurable.

### Context

**Encountered User Concerns**
* Many User/Customer/Training attendees asked for more fine grained logging functionality like known from well known logging frameworks like log4j / logback, etc.
* It's hard to trace specific logging messages as we currently just support global log levels and not fine grained (e.g. package scoped) log levels
* Adding custom logging appender is not supported
* Customizable log format 
> like when on CI, I would like per-thread timing so I can understand the output

**Comment by ov7a** [comment]
Related:
* https://github.com/gradle/gradle/issues/1010

**Comment by mcumings** [comment]
An additional logging use case was raised in #32481 and Louis asked me to add the use case here.   Summarizing, but full details are on that issue:
- For large projects, must of the log is noise related to what could be construed as internal concerns of the build (e.g., whether a task was skipped, up-to-date, etc).
- The high volume of logging obscures the information that a dev would be able to act upon
- The high volume of logging makes web-based exposure of logged information unwieldy (multi-MB log files
- ANSI escapes, used in more concise output options currently offered, are not typically well handled in CI-based environments.

If seems as though the output requirements really boil down to:
- Demonstrating to the user that progress is being made
- Indicating to the user what (long running?) tasks are currently being executed
