### ISSUE TITLE
Introduce a `@Discouraged` annotation

### ISSUE THREAD

**Issue by melix** [gradle/gradle#24091]
### Expected Behavior

It should be possible to know which APIs are not yet deprecated, but are strongly discouraged. A typical example is the use of `allprojects` and `subprojects` blocks which introduce coupling between projects.

I would suggest to add an annotation like this:

```java
@Discouraged(explanation="This introduces coupling between projects and it can produce unreliable configuration by mutating other project's state", prefer="Use convention plugins if possible", documentation="https://docs.gradle.org/current/samples/sample_convention_plugins.html")
public void allprojects(...) {
}
```

### Current Behavior

Some methods just cannot be deprecated yet because either there are no alternatives, or their use should be last resort. Examples of these are `afterEvaluate` or `allprojects`. Sometimes, you _have_ to rely on those, but the long term goal is to remove them, so we should encourage users to use something else. Users should be able to understand that this will eventually be replaced, and the remaining calls should help gathering which use cases are not covered yet.

### Context

I have seen multiple times on Slack folks ignoring that using `allprojects`, `afterEvaluate` and other methods like these are discouraged. It is no surprise since there's no deprecation yet (for good reasons), but it prevents folks from moving to best practices.

**Comment by rschmitt** [comment]
What's the desired behavior? Would warnings be emitted when `@Discouraged` methods are invoked? Would their invocations be ~~struck through~~ in the IDE, as with `@Deprecated`?

**Comment by ov7a** [comment]
Thank for coining this idea, but we think this wouldn't be implemented. We think we have already enough feature lifecycle stages to deal with different situations similar to this one. The `@Deprecated` annotation combined with javadoc can be used for this:
- just javadoc to give a hint for a user
- javadoc +  `@Deprecated` to give an explanation and a warning
- javadoc +  `@Deprecated` + nagging to give a more intrusive, runtime deprecation warning.

**Comment by melix** [comment]
Right, the point of having an annotation was precisely because javadocs are not visible as warnings in build scripts, so miss IDE support, and that `@Deprecated` is too late.

**Comment by ov7a** [comment]
Could you please elaborate a bit about why do you think `@Deprecated` is too late? 
Using  `@Deprecated` would be shown in IDE and you could read about the deprecation in javadoc. For example, this could be applied today for `allprojects` and `subprojects`.

**Comment by melix** [comment]
`@Deprecated` is too late because it has to be used _when the thing is deprecated_. `afterEvaluate`, `Task#create` etc are _not_, for good reasons, but they are discouraged. Therefore this annotation could behave, in IDEs, like `@Deprecated`, but _before_ a method is actually deprecated.

**Comment by ov7a** [comment]
I think you are right that we could handle this better, and it's something that should be addressed in terms of polishing API's and making it harder to do a discouraged action. On the other hand, warnings can be ignored completely by a user and the same thing goes for the docs. Providing a better documentation and howtos is another thing that could be done. But the team decided that adding more stuff for feature lifecycle is not a best way to do it.
