### ISSUE TITLE
Docs on IOS Safari visual stutter bug

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#24106]
On IOS when clicking a link to view another document, the docs start shuddering violently.

Eg visit this page
https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html

Then click the link for `Provider`

### Expected Behavior

Docs site should be readable without shaking your head violently in sync with the web page. 😆 

### Current Behavior

Required to shake head violently to read the contents of the documentation on certain pages.

### Steps to Reproduce 

https://user-images.githubusercontent.com/1323708/222296847-480e0f11-71fa-4fe7-b29d-911728a68457.MOV

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.
