### ISSUE TITLE
Gradle command in Exec got an output different from plain command execution in Linux

### ISSUE THREAD

**Issue by almogtavor** [gradle/gradle#24104]
### Expected Behavior

I'm running command line commands through a custom Gradle Plugin I've created within Gitlab CI inside a `jdk17` Linux pod. When the plugin executes a `helm upgrade` command I get an error, but when I execute the same command from the Gitlab CI `scripts`, it works perfectly. I'd expect commands running within Gradle to work the same way as if they would get executed directly on the Linux machine.

### Current Behavior

I create a custom Gradle plugin that executes the `helm upgrade` command with the code of (inside of a class that extends `DefaultTask`:
```java
@TaskAction
public void command() {
    // code for building the commands array
    getProject().exec(t -> t.commandLine(commandsArray);
}
```
The command line that is generated is `/home/jboss/helm update -i my-release -f /builds/my/project/chart/values-prod.yaml/builds/my/project/chart/output/my-project-chart.tgz —set image.tag=“0.1.2”`.
When I execute it directly it works, but when Gradle executes it - it doesn't. It's important to note that it also works perfectly when Gradle executes it on Windows.

The error I get when I execute this within the Gradle plugin task is: `Error: UPGRADE FAILED: YAML parse error on my-project/helm-common/deployments.yml: error converting YAML to JSON: yaml: line 31: did not find expected key`. I would accept that I have some lint issues here, but it's working perfectly from anywhere but the Gradle execution engine. I would like to get some help understanding the differences that can occur between executing a command from Gradle vs. directly, and understanding how to fix this (I thought of running the command with the keyword `bash` at the beginning but it didn't help).

### Your Environment

I execute the command within this [JDK-17.0.2 image](https://hub.docker.com/layers/library/openjdk/17.0.2-jdk/images/sha256-98f0304b3a3b7c12ce641177a99d1f3be56f532473a528fda38d53d519cafb13?context=explore).

**Comment by almogtavor** [comment]
As a workaround, I've managed to get this work by executing `getProject().exec(t -> t.commandLine("bash", "-c", "'helm upgrade ...'")`.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

A process started from a shell started manually and a process started by Gradle might have different environment, this might be the source of your problem.
