### ISSUE TITLE
Extending an already resolved configuration no longer works correctly

### ISSUE THREAD

**Issue by DJtheRedstoner** [gradle/gradle#24109]
### Expected Behavior

Extending an already resolved configuration should include the resolved dependencies of that configuration in the sub configuration.

### Current Behavior

Dependencies from the already resolved super configuration are not included in the sub configuration.

### Context

This stopped working in Gradle 7.6.1 and 8.0 (also tested with 8.0.1). I noticed this issue with [our fork of](https://github.com/EssentialGG/architectury-loom) the [fabric-loom](https://github.com/FabricMC/fabric-loom/) gradle plugin. Because of the complex nature of the plugin a lot of things are done "out of order". A simple workaround for this issue exists (adding an `extendsFrom` in the buildscript/earlier in the plugin).

### Steps to Reproduce 

Run the following buildscript:
```gradle
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

configurations {
    superConfiguration
    subConfiguration
}

dependencies {
    superConfiguration "commons-io:commons-io:2.11.0"
}

// cause superConfiguration to be resolved
println configurations.superConfiguration.files

configurations.subConfiguration.extendsFrom(configurations.superConfiguration)

println configurations.subConfiguration.files
```

Note the difference in output between gradle 7.6
```
[C:\Users\admin\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.11.0\a2503f302b11ebde7ebc3df41daebe0e4eea3689\commons-io-2.11.0.jar]
[C:\Users\admin\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.11.0\a2503f302b11ebde7ebc3df41daebe0e4eea3689\commons-io-2.11.0.jar]
```
and 7.6.1
```
[C:\Users\admin\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.11.0\a2503f302b11ebde7ebc3df41daebe0e4eea3689\commons-io-2.11.0.jar]
[]
```

### Your Environment

Build scan URL (Gradle 7.6): https://scans.gradle.com/s/uqo7kw7crp4fq
Build scan URL (Gradle 7.6.1): https://scans.gradle.com/s/mpjt6aujq3loc

**Comment by ljacomet** [comment]
Fix has been merged

**Comment by DJtheRedstoner** [comment]
Thanks! Will there be a backport to 7.x with this fix?

**Comment by ljacomet** [comment]
Filed #24132 for this
