### ISSUE TITLE
Emit warning when deprecated configuration usage is used

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#24139]
When a configuration has deprecated marked for a particular usage, indicated by one of these flags set in DefaultConfiguration:

	private boolean consumptionDeprecated;
	private boolean resolutionDeprecated;
	private boolean declarationDeprecated;

and that usage is actually used (i.e., if a deprecated for consumption configuration is consumed, or a dependency is declared against a deprecated for declaration against configuration), a deprecation warning is emitted.

First cut at defining which methods are part of each usage, going through all public (including inherited) methods in `DefaultConfiguration` is in the Google Doc [here](https://docs.google.com/document/d/1YD7IgHrD28tvwkk8iXbQWJjsE5Dpa5ERTf8L7-JwJcA/edit#heading=h.iaxntumehbo4).

**Comment by jvandort** [comment]
It seems like there are a few here you've listed that are internal methods, including:
* `convertToOutgoingVariant`
* `getDependenciesResolver`
* `getResolvedState`
* `setReturnAllVariants`
* `toRootComponentMetadata`

It also looks like we're missing some which probably should be listed here like:

* `getBuildDependencies`
* `getTaskDependencyFromProjectDependency`
* All of the methods from `FileCollection` (I think these would be a blanket resolvable)
* `is/setVisible`

In general, I think many of these look correct, though I've got comments on a few of them. For the sake of discussion and commenting on specific methods, can we move this to a google doc, which lends itself better to inline comments?

**Comment by tresat** [comment]
Yes, I was looking at all public methods, not restricting to implementations of public API methods.

Moving the discussion to a Google Doc [here](https://docs.google.com/document/d/1YD7IgHrD28tvwkk8iXbQWJjsE5Dpa5ERTf8L7-JwJcA/edit#heading=h.iaxntumehbo4).
