### ISSUE TITLE
C++ plugin should work if all source is generated

### ISSUE THREAD

**Issue by noel-yap** [gradle/gradle#2413]
C++ plugin currently doesn't create a `compile*StaticLibrary*Cpp` task if it sees no static sources (ie all sources are generated).

### Expected Behavior

The `compile*StaticLibrary*Cpp` task should be created even if there are no static sources.

I'm suspecting there's some optimization in place so that the task isn't created if no sources are seen. If that's the case, remove this optimization. This may cause errors later if the task actually tries to compile sources that don't exist. I'm thinking if there are no sources, no object files should be created and no error should be emitted.

### Current Behavior

C++ plugin currently doesn't create a `compile*StaticLibrary*Cpp` task if it sees no static sources (ie all sources are generated).

The `compile*StaticLibrary*Cpp` task will be created even if there are no static sources.

### Context

The project I'm working on, a protobuf plugin, generates C++ code given proto files as input. Since nothing was being compiled, no static library was created causing errors further down in the build process.

### Steps to Reproduce (for bugs)

```
model {
  components {
    "${project.file(projectDir).name}"(NativeLibrarySpec) {
      targetPlatform osdetector.arch

      sources {
        cpp {
          source {
            srcDirs "${buildDir}/generated/source/proto/main/cpp"
          }

          exportedHeaders {
            srcDirs "${buildDir}/generated/source/proto/main/cpp"
          }
        }
      }
    }
  }
}

task generateSource << {
  // generate something in `${buildDir}/generated/source/proto/main/cpp`
}
```

`gradlew build`

The above is roughly what should reproduce the problem.

### Your Environment

$ uname -a
Linux lgud-nyap-2017 4.8.0-54-generic #57~16.04.1-Ubuntu SMP Wed May 24 16:22:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 * Build scan URL: 
https://gradle.com/s/ijna674f4p2a2

Building again succeeds since now the generated files are there:
https://gradle.com/s/7bsbmez43i2sy

**Comment by lacasseio** [comment]
Issue moved to [gradle/gradle-native #36](https://github.com/gradle/gradle-native/issues/36) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lacasseio** [comment]
Thanks @noel-yap for this opening this well-formated issue. Native support in Gradle is getting its own dedicated space under [`gradle/gradle-native`](https://github.com/gradle/gradle-native). We will continue the discussion there.
