### ISSUE TITLE
Improve parallel execution of tests for sub-projects

### ISSUE THREAD

**Issue by fkorotkov** [gradle/gradle#2414]
I have a multi-project with 60+ sub-projects and I'm experiencing the following behaviour when I run tests with 8 workers with parallel execution enabled.

Let say sub-project B depends on sub-project A. I can see that tests for project B are not executed until tests for project A passes. I would expect it to start execution of tests for project B once compilation outputs for projects A and B are available.

It looks for me like a possible huge optimization opportunity for large projects.

**Comment by oehme** [comment]
Are you using `forkEvery` on your test tasks`? If so, the behavior you're seeing would be normal, because project A is already using all your CPUs to run its tests. We don't display that in the console yet.

**Comment by fkorotkov** [comment]
No. I don't. The only caveat I have is that I use `java-library` plugin everywhere with a workaround to make it work with Kotlin:

```
configurations {
  apiElements {
    outgoing.variants.getByName('classes').artifact(
      file: compileKotlin.destinationDir,
      type: ArtifactTypeDefinition.JVM_CLASS_DIRECTORY,
      builtBy: compileKotlin)
  }
}
```

But I doubt it affect the behaviour.

**Comment by oehme** [comment]
Sorry I meant `maxParallelForks`.

**Comment by fkorotkov** [comment]
Also don't use it. The only test customization I have is:

```
test {
  testLogging {
    exceptionFormat = 'full'
  }
}
```

I can try to create an example project if you'd like. Do you expect everything to work as I described when A:test and B:test are executed in parallel?

**Comment by oehme** [comment]
Yep, that should work just fine. An example would be great.

**Comment by fkorotkov** [comment]
Interesting! Will try to extract it.

**Comment by fkorotkov** [comment]
Will close the issue until I have a repro example. Sorry for the noise. I thought it's expected 😅
