### ISSUE TITLE
 test task error  "No tests found for given includes" .

### ISSUE THREAD

**Issue by lfygh** [gradle/gradle#24168]
```
------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4 (Azul Systems, Inc. 17.0.4+8-LTS)
OS:           Mac OS X 13.1 aarch64

```

if I have no test class, gradle test task work well 
```java
test {
    useJUnitPlatform()
}
```

if I only have one test class, and I just exclude it, then the test task error  "No tests found for given includes" occurs.
```java
test {
    useJUnitPlatform()
    filter {
        excludeTestsMatching("**Test")
    }
}
```

so, what can I do to skip the error, and what is the diff between the two situations?

**Comment by sschuberth** [comment]
@lfygh did you find a solution? I'd also like my tests *not* to fail just because test filtering left no tests to execute.

**Comment by sschuberth** [comment]
Ah, I've found the answer in the duplicate over [here](https://github.com/gradle/gradle/issues/24174#issuecomment-1459847735).
