### ISSUE TITLE
Grey text invisible on Solarized Dark

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#2417]
The `IDLE` indicators are invisible on Solarized Dark, because it renders as bright black, and is invisible on this theme (to be accurate, there's very little contrast so it's _effectively_ invisible):

<img width="182" alt="screen shot 2017-07-07 at 2 21 54 pm" src="https://user-images.githubusercontent.com/1479220/27977463-bafed866-631f-11e7-9095-c03eb4d5227e.png">

Extensive discussion of this issue w/ other projects here:

https://github.com/altercation/solarized/issues/220

### Expected Behavior
Text should be rendered in a foreground color that is broadly supported by different color schemes.

### Current Behavior
Bright black text is invisible.

### Context
I didn't even realize there were `IDLE` indicators until I did an asciinema recording of my terminal!

### Steps to Reproduce (for bugs)
Use iTerm 2 w/ Solarized Dark theme. Note that the `IDLE` indicators are not shown.

### Your Environment
OSX Sierra, iTerm 2, Solarized Dark.

**Comment by eriwen** [comment]
I've noticed this depends on the terminal. In the IntelliJ terminal, it shows up, but in iTerm it doesn't.

The loss of "> IDLE" has pretty low impact as a bug, and we cannot control what a user maps to the ANSI colors, so I'm not sure if there's a fix that is easy enough to be worth it. 

I welcome others' ideas, and will mark this as `help-wanted` in case someone wants to come up with a scheme that works in all environments. I think one would start in the `DefaultWorkInProgressFormatter` class.

**Comment by eriwen** [comment]
@DanielThomas Sorry for the runaround. This is an easy fix, so this'll be improved in Gradle 4.1. See #2444. Closing as complete.
