### ISSUE TITLE
Pdf documentation contains (almost) blank pages

### ISSUE THREAD

**Issue by ov7a** [gradle/gradle#24191]
Take a look at the current version, [8.0.2](https://docs.gradle.org/8.0.2/userguide/userguide.pdf), pages 157, 417, 454, 461, etc.

These pages are almost empty. It seems like this issue is related to code snippets rendering. But there are also examples of [widows and orphans](https://en.wikipedia.org/wiki/Widows_and_orphans) (e.g. on page 151).

**Comment by lkasso** [comment]
Previously fixed.
