### ISSUE TITLE
Gradle Wrapper, GitLab SaaS CI, Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by black-snow** [gradle/gradle#24210]
Not sure if this is actually a bug in the Gradle wrapper but I currently don't know how to debug this further.

I've got some projects on GitLab SaaS that pull in dependencies from a private maven repo on GitLab. This used to work fine in the past, but now I end up with:

> Could not determine the dependencies of task ':shadowJar'.
Could not resolve all dependencies for configuration ':runtimeClasspath'.
Could not resolve a.b.c:d:3.4.0.
Required by:
project :
> Could not resolve a.b.c:d:3.4.0.
> Could not get resource 'https://gitlab.com/api/v4/groups/xxx/-/packages/maven/a/b/c/d/3.4.0/d-3.4.0.pom'.
> Could not GET 'https://gitlab.com/api/v4/groups/xxx/-/packages/maven/a/b/c/d/3.4.0/d-3.4.0.pom'.
> The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/8.0.2/userguide/build_environment.html#gradle_system_properties
> Received fatal alert: handshake_failure

### Expected Behavior
Wrapper succeeds in building the project.

### Current Behavior
Build fails.

### Context
It works fine on my local machine (Win11w/ IDEA as well as Ubuntu inside WSL2).  
It works fine with the `gradle:8.0.2-jdk8` OCI (which has the same version as the standalone temurin image) and not using the wrapper.

I also tried adding the root cert (keytool -import) for gitlab.com (Baltimore CyberTrust Root), killed the daemon and retried, but to no avail.

Browser and cURL state it's TLS 1.3.

For CI, I replace the private token with a job token but that used to work and you get a different error message with bad credentials.

### Steps to Reproduce 
* you'll probably need a private repo at GitLab.com (might work with public ones - not yet tested)
* OCI `eclipse-temurin:8-alpine@sha256:70ff71a0fa3b6e529fad68532a9368cdd1a67fdc4d99e924eeba69e38dfcf6a3` to build the image
* Gradle Wrapper 7.6, 8.0.1 or 8.0.2 (tested those)
* have the repo set up in `build.gradle`
```groovy
repositories {
    maven {
        url "https://gitlab.com/api/v4/groups/xyz/-/packages/maven"
        name "GitLab"
        credentials(HttpHeaderCredentials) {
            name = "Private-Token"
            value = your-token-here
        }
        authentication {
            header(HttpHeaderAuthentication)
        }
    }

    mavenCentral()
}
```
* run `./gradlew assemble` (or test or any task - I also use shadowJar but this doesn't seem essential)

regarding certs:
* `echo | openssl s_client -showcerts -partial_chain -servername https://gitlab.com -connect gitlab.com:443 -servername gitlab.com | awk '/BEGIN/,/END/{ if(/BEGIN/){a++}; out="cert"a".pem"; print >out}'`
* `keytool -import -alias baltimore -file cert2.pem -keystore /opt/java/openjdk/jre/lib/security/cacerts`
* `keytool -list -keystore /opt/java/openjdk/jre/lib/security/cacerts`
* `killall java`
* `./gradlew assmble`

### Your Environment
s. a.

### Refs

* https://docs.gitlab.com/ee/user/packages/gradle_repository/

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is an issue with GitLab which cannot be addressed in the Gradle Build Tool project.

Please open an issue on the GitLab Issue Tracker. 

***

Java specifies the requested TLS server protocols, the GitLab server doesn't accept them. Gradle does not play a role here.

**Comment by black-snow** [comment]
Why does it work with the *installed* gradle but not via the wrapper then?

Issue on GitLab: https://gitlab.com/gitlab-org/gitlab/-/issues/396377

**Comment by ov7a** [comment]
This might be a problem with environment or settings related to TLS.
