### ISSUE TITLE
Document GRADLE_LIBS_REPO_OVERRIDE

### ISSUE THREAD

**Issue by ciscoo** [gradle/gradle#24217]
### Expected Behavior

Document for `GRADLE_LIBS_REPO_OVERRIDE` so that users that work behind a company firewall/proxy can resolve dependencies against an internally hosted Maven repository proxy such as [Nexus](https://www.sonatype.com/products/nexus-repository)

### Current Behavior

No documentation exists for `GRADLE_LIBS_REPO_OVERRIDE` anywhere. The only reference I have found is https://github.com/gradle/gradle/issues/23163 and [this](https://github.com/gradle/gradle/issues/23163#issuecomment-1439011627) comment specifically sums up my situation being behind a company firewall/proxy.

### Context

I was trying to upgrade a private company project of mine to Gradle 8 from Gradle 7.6. I observed that IntelliJ would hang attempting to download `groovy-3.0.13.pom`. This puzzled me because I had configured both the [plugins repositories](https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories) _and_ a [custom repository](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:declaring_custom_repository) for application dependencies.

It wasn't until after I enabled a new security tool we have is when I was able to observe that `groovy-3.0.13.pom` along with other Groovy related dependencies were being downloaded from https://repo.gradle.org/gradle/list/libs-releases.

Puzzled again, I searched Gradle's code base and found the repository defined in [`DefaultGradleApiSourcesResolver`](https://github.com/gradle/gradle/blob/master/subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/resolver/DefaultGradleApiSourcesResolver.java). And it was there I learned of `GRADLE_LIBS_REPO_OVERRIDE`

**Comment by ciscoo** [comment]
Also, the project setup was:

**Version:** Gradle 8.0.2
**Distribution:** All
**DSL:** Kotlin

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

***

We believe that this should be definitely  addressed in the documentation, and maybe and explicit way should be available to configure this repository in build scripts. It's up to IDE team to decide. 

* Related: https://github.com/gradle/gradle/issues/18249

**Comment by SidB3** [comment]
@ciscoo - I stumbled across this issue after debugging why IntelliJ is trying to download the groovy libs every time.

Did you get this to work? How do I set an artifactory url with password?
