### ISSUE TITLE
Force run test when the full method path is specified on the command line

### ISSUE THREAD

**Issue by timnick-snow** [gradle/gradle#24225]
### Expected Behavior
When the command line specifies the full path to the test method, it should run, even if he does not match the filter.
Or there is a way, a parameter that allows it to run

### Current Behavior
```gradle
test{
    useJUnitPlatform()
    filter {
        // include all integration tests
        includeTestsMatching "*NeedTest"
        failOnNoMatchingTests false
    }
}
```
```java
public class SomeTest {
    @Test
    public void fun1() throws Exception {
        System.out.println("hello");
    }
}
```

then, run
```shell
gradlew test --tests "io.github.snow.SomeTest.fun1"
```
`fun1` will not be executed. Because it does not match *NeedTest.

However, for this test only, I need it to run the method I specified.

### Context
There are some methods that are not expected to run during the build process. These methods will not match the filter.
Is there a way to just run test tasks and force these methods to be able to run when specified

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

****
To achieve what you want, you should create another test task. There should be a test task which runs all tests, and you can pass filter there.  Please, refer [the docs](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering) for more details.
Also, this feature can break existing behavior.
