### ISSUE TITLE
It is not possible to create an implementation of SelfResolvingDependency

### ISSUE THREAD

**Issue by ysb33r** [gradle/gradle#2423]
As a plugin author it is not possible to create any implemetnation in the `Dependency` hierarchy without having to resort to internal APIs. This case is more subtle for a number of reasons.

### Current Behavior

Firstly I decided to write a class that implements `SelfReferencingDependency` as I though it wuld be a nice way to introduce an algorithm that resolves files from some sources that are not covered by curretn Gradle functionality. Let's just say something like

```groovy
class MySelfResolvingDependency implements SelfResolvingDependency {
  /* ... */
}
```

*Problem*: The above will ALWAYS fail to resolve and will THOW an exception, because deep in the Gradle codebase some logic is buried that wants a `FileCollectionDependency` instead.

Now having updated the code to 

```groovy
class MySelfResolvingDependency implements FileCollectionDependency {
  /* ... */
}
```

and implemented `getFiles()`, which by the way has no explanation as to its behaviour. Should `getFiles` call `resolve` if no files have been resolved, or should it just return empty?

*Problem*: Running this ends up in the following exception:

```
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':foobar'.
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$1.collectFiles(DefaultLenientConfiguration.java:153)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:810)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:376)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:372)
	at .....
Caused by: java.lang.ClassCastException: o.y.MySelfResolvingDependency cannot be cast to org.gradle.api.internal.artifacts.dependencies.SelfResolvingDependencyInternal
	at org.gradle.api.internal.artifacts.ivyservice.moduleconverter.dependencies.DefaultDependenciesToModuleDescriptorConverter$DefaultLocalFileDependencyMetadata.getComponentId(DefaultDependenciesToModuleDescriptorConverter.java:82)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.LocalFileDependencyBackedArtifactSet.visit(LocalFileDependencyBackedArtifactSet.java:67)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.visitArtifacts(DefaultLenientConfiguration.java:298)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.access$000(DefaultLenientConfiguration.java:70)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$1.collectFiles(DefaultLenientConfiguration.java:144)
```

Yes, it is trying to cast the public API to an internal API, which is fine, except that it should have some reasonable behaviour to allow an external implementation to survive.

My current solution is to also implement the `org.gradle.api.internal.artifacts.dependencies.SelfResolvingDependencyInternal` interface, which make me nervous. 

```groovy
class MySelfResolvingDependency implements FileCollectionDependency,  SelfResolvingDependencyInternal {
  /* ... */
}
```
### Expected Behavior

* Do not attempt cast `FileCollectionDependency` to `org.gradle.api.internal.artifacts.dependencies.SelfResolvingDependencyInternal`. It only adds one more method which uses a public API anyway - what about just pulling the method up to the public API?

* Document the expected behaviour `FileCollectionDependency.getFiles()`

### Environment

Was building this with Gradle 4.0 (I am planning to test down to Gradle 3.3).

**Comment by melix** [comment]
@ysb33r would you mind describing the higher level problem you are trying to solve?

**Comment by bmuschko** [comment]
@ysb33r I don't quite get what you are trying to do exactly. Could you please describe the actual use case?

**Comment by ysb33r** [comment]
@melix @bmuschko What I want to do is to add the ability to resolve something from a external repository such as Npm, Ruby or Conan without touching the RepositoryHandler part of Gradle. Primary reason is that I have gone down that rabbit hole before of trying to add a custom repository type and one soon ends up in internal API hell. If something does not look like Maven or Ivy effectively it cnnot be done using public APis.  I know there will be work done to eventually provide some public APIs, but they are not available yet.

There is also a fair use-case to this for extracting files out of a local Tar/Zip wihout manually unpacking it first with a `Copy` task.

So my approach was to dirty and side-step that, by using a SelfResolvingDependency to do the work of getting the files somewhere on disk. I know this is is not quite the intention of that specific interface, but it is the simpest way of allowing a user to at least use the `dependencies` and `configurations` as they would usually. It also hides the complexities of resolving the dependencies from them.

To a great extent the point that I am making with this issue is that there are a number of public APIs in the `Dependency` hierarchy, which should be usuable, but there are assumptions in the internal of the Gradle codebase about how they will being used, which contradicts what is documented on the public API.

**Comment by bmuschko** [comment]
I think we can close this issue in favor of https://github.com/gradle/gradle/issues/1400. It basically describes your need. Please upvote there.

**Comment by nallar** [comment]
Bit confused about why this got closed, the issue described is quite real? There's public API, you can't use it.

A dependency generated by a task would allow for plugins which need to generate dependencies not to try to bodge and do it at config time, or do it with global task hooks.

gradle already uses this for `gradleApi()`, proving that it's useful to do this.

**Comment by enveeed** [comment]
I've tested this with Gradle 6.6 and apparantly implementing the public API `FileCollectionDependency` works now, but I haven't tested anything further other than if it throws an exception and that it appears in the `dependencies` task output as expected. Using `SelfResolvingDependency` directly still does not work though.

**Comment by nallar** [comment]
@bmuschko could we get this reopened? see comments above

**Comment by enveeed** [comment]
So I just tried this again using Gradle 6.7 and the behavior is the same as in 6.6, any user implementation of `SelfResolvingDependency` fails because local component dependency metadata could not be constructed. `FileCollectionDependency` resolved without errors and shows up in the `dependencies` task, but currently the IntelliJ Gradle plugin fails to import any project using such an implementation cause it's attempting to cast it to `SelfResolvingDependencyInternal` in the current version, so that's not really a good way to deal with this either.
