### ISSUE TITLE
Nag for deprecation of registering conventions

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#24232]
This is a follow up to
* https://github.com/gradle/gradle/pull/24231

Note that we must have upgraded to a Kotlin Gradle Plugin version that includes a fix for
* [KT-52976](https://youtrack.jetbrains.com/issue/KT-52976) DONE in Kotlin 1.9.0, finished in 1.9.20

----
Blocked by
* https://github.com/gradle/gradle/issues/26764

**Comment by abstratt** [comment]
@eskatos Is this only about adding a call to `logConventionDeprecation()` to `DefaultConvention.getPlugins()`: https://github.com/gradle/gradle/blob/86298e04ae35b3da6c2b900d0404852533b4c860/platforms/core-configuration/model-core/src/main/java/org/gradle/internal/extensibility/DefaultConvention.java#L71

and then updating tests that rely on exact count of deprecation messages logged accordingly?

Are there other paths for "registering conventions"? And are there legitimate usages of `#getPlugins()` that we do not want to deprecate (say, querying would be fine, so then we would need to do something at the  returned `ConventionPluginsMap` instead)?  If not, I guess we could get rid of `ConventionPluginsMap` altogether?

**Comment by eskatos** [comment]
A lot of gymnastic was required to deprecate only accessing conventions in the past, but not convention registration. This could be cleaned up and simplified. Wether this happens now or when we can get rid of conventions is up to you.

I feel like we should simplify now and have `DefaultConvention.getPlugins()` emit a warning and remove all the unnecessary logs when you just access a convention. Otherwise users will get double warnings that are not meaningful.

**Comment by abstratt** [comment]
This depends on us bumping the version of KGP we use (at least 1.9.21), due to this last fix in KGP: https://youtrack.jetbrains.com/issue/KT-63499

**Comment by abstratt** [comment]
@eskatos When you say "double warnings", do you mean this:

```
Build file '/Users/rafael/sources/gradle/trees/tree03/subprojects/core/build/tmp/teŝt files/DynamicObje.Test/d12jq/build.gradle': line 3
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.7-20240118030000+0000/userguide/upgrading_version_8.html#deprecated_access_to_conventions
	at build_eesz3weruwmbvpx5mcnnnyuhm.run(/Users/rafael/sources/gradle/trees/tree03/subprojects/core/build/tmp/teŝt files/DynamicObje.Test/d12jq/build.gradle:3)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)
Build file '/Users/rafael/sources/gradle/trees/tree03/subprojects/core/build/tmp/teŝt files/DynamicObje.Test/d12jq/build.gradle': line 3
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.7-20240118030000+0000/userguide/upgrading_version_8.html#deprecated_access_to_conventions
	at build_eesz3weruwmbvpx5mcnnnyuhm.run(/Users/rafael/sources/gradle/trees/tree03/subprojects/core/build/tmp/teŝt files/DynamicObje.Test/d12jq/build.gradle:3)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)

```

for code like this:

```
convention.plugins.test = new ConventionBean()
```
?
