### ISSUE TITLE
Update gradle init to provide an option create and use a version catalog

### ISSUE THREAD

**Issue by akshayabd** [gradle/gradle#24258]
Version catalogs are the recommended way to centrally define dependency modules, plugins and their versions. It would be helpful if the `gradle init` task would have the option to create a catalog and have the build configuration use it. Eventually I would suggest making this option enabled by default.

### Expected Behavior
When running `gradle init` it should ask the user if they want a version catalog to be created. If yes, then a catalog should be created under the default location of `gradle/libs.versions.toml` and the build files use the catalog in the dependencies configuration.

### Current Behavior
`gradle init` does not ask if the user wants to create and use a version catalog, and there is no way to have the task create it.

### Context
This would also help increase adoption and usage of the version catalog.

CCing @borisf, @hythloda, @eskatos

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by ov7a** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by eskatos** [comment]
Version catalogs being a stable feature I would expect this to be the default in `gradle init`.
