### ISSUE TITLE
Installing gradle under $HOME deleted all folders and files there

### ISSUE THREAD

**Issue by s-usr** [gradle/gradle#24252]
### Problem
I was attempting to install gradle under $HOME so that the installation results in $HOME/.gradle [I acted recklessly by not working under $HOME/tmp just because I did not want the installation to end up as $HOME/tmp/.gradle]. As the compiler got the final stages, it erased all folders and files I have under $HOME/ including Documents, Downloads, Music, Video, some other working and data folders I created there, .local, .bin, and .bashrc and all other dot files. This is devastating as I lost so much material. 

Luckily, I managed to copy .bashrc from /etc/skel. I looked under Trash, /tmp/, /root/home/user, all to no avail. Everything is gone. I tried testdisk; it did not find anything. Please advise if the lost material is possible to be retrieved.

### Steps to reproduce
1. Under $HOME, git clone https://github.com/gradle/gradle
2. cd gradle; mv * ..; cd ..
3. gradlew install PinstallDir=.  [cannot remember the exact syntax]
4. Will have to work through some errors, like ignore java version and unlink.

### Actual behavior
Installation was completed with one error. Nevertheless, it erased all files, dot files, folders, and system folders under $HOME.

### Expected behavior
Complete installation without ever deleting folders and files that do not belong to 'gradle' itself. A security must be added that prevents the compiler on clean up from ever deleting .bashrc and/or system folders under $HOME or /usr/.... or /...

### Impact
The result is devastating as the compiler (seemingly on clean-up) deleted all personal and system folders and files under $HOME. This means that it could also have deleted everything under /... or /usr/... depending on where the user intended to install the package.

### Environment
Linux x86_64 Fedora version 37.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.
***

This can be mitigated in the future by checking that the target directory is either empty or contains something that looks like a gradle build.

**Comment by s-usr** [comment]
Thanks. Sad to hear this is not a priority because the issue creates much damage and the fix is straightforward. My questions are: Can the erased files be recovered? Can `make install` be reversed with `make uninstall`? The developers must have the answers and are welcome to advise.

**Comment by ov7a** [comment]
We understand your concern, but this feature is mostly for Gradle contributors and developers. There are many other (  more user-friendly) ways to [install Gradle](https://gradle.org/install/).

As for your files, the `install` task just wipes out the target directory without a backup. You can try to use a data recovery tool to get at least some of your data back.

**Comment by s-usr** [comment]
For the benefit of others, I add:
- `testdisk` did not detect the `btrfs filesystem`.
- part of the `btrfs-progs` package , `btrfs restore` - which has to be invoked with the disk unmounted - recovered what exists in the directory, but **not** the lost data/files.

**Comment by s-usr** [comment]
Thanks much. Great job. Should help many.
