### ISSUE TITLE
DependencyReportTask Parameters 

### ISSUE THREAD

**Issue by jingleiaf** [gradle/gradle#24259]
How can we set up a task for all project using this DependencyReportTask to show the dependencies tree, but only for runtimeClasspath and compileClasspath ?

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

**Comment by ljacomet** [comment]
You could look into the following code: https://github.com/gradle/gradle/blob/bce67a98584bec5758a96f1d62232a3a012b56f5/subprojects/diagnostics/src/main/java/org/gradle/api/plugins/HelpTasksPlugin.java#L77
