### ISSUE TITLE
Could not get unknown property 'resDir' for task ':app:processDebugResources' of type com.android.build.gradle.tasks.ProcessAndroidResources.

### ISSUE THREAD

**Issue by senthilkumar06** [gradle/gradle#2426]
Hi,
I am using Android studio 3.0 Preview Canary 4.
distributionUrl : https://services.gradle.org/distributions/gradle-4.0-rc-1-all.zip
gradle plugin : gradle-3.0.0-alpha4

My project doesn't build and gives me this error,
**Error:Could not get unknown property 'resDir' for task ':app:processDebugResources' of type com.android.build.gradle.tasks.ProcessAndroidResources.**

Any help would be appreciated.
Thanks in advance.

**Comment by bmuschko** [comment]
The issue you are experiencing is very likely a bug in the Android plugin. Would you mind [opening an issue with Google on the respective forum](https://code.google.com/p/android/issues)? They are creating the plugin as well as Android Studio and are far more likely you help you with this.
