### ISSUE TITLE
Flaky Tests in GitHub actions pipeline

### ISSUE THREAD

**Issue by LeoFuso** [gradle/gradle#24276]
### Expected Behavior

The Tests should be able to run remotely the same way I manage to run locally.

### Current Behavior

Tests keep failing with the same weird exceptions, e.g.

```text
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'org.gradle.api.plugins.JvmToolchainsPlugin'.
``` 

```text
java.lang.InternalError: java.lang.InternalError: late constant pool addition: org/gradle/api/internal/provider/ValueSourceProviderFactory$ComputationListener
``` 

### Context

I'm developing a Gradle Plugin, and to do so, I'm using TestKit with the GradleRunner to run a few Functional Tests.
They run in my local environment just fine, but in the CI environment, they're Flaky, failing from time to time.

I think there's something to do with the `ParameterizedTest`, something to do with its quantity, maybe a problem when loading a lot of daemons? Idk. I'm suspecting that there's something to do with the memory or CPU available.

The strange fact is that it's never the same "index" of the parameterized test, but always the same test that keeps failing.

I know it is not the best bug report, but I'm completely lost about the cause, especially with those weird exceptions and the lack of reproducibility.

### Steps to Reproduce 

I do not have another computer to try it and validate, neither I can reproduce it in my local environment, not for lack of trying.
What I do have is the pipeline failure itself, along with some test reports with some weird exceptions.

Here's the Pipeline

https://github.com/LeoFuso/argo/actions/runs/4381109109/jobs/7668998137

... and the project itself

https://github.com/LeoFuso/argo

### Your Environment
This issue only happens with Ubuntu images, specifically the `ubuntu-22.04` from GitHub actions.
It happens more often in Java 17 (regardless of the vendor), but still happens with Java 11.
All Gradle versions from `7.5` to `7.6`. I didn't manage to try Gradle 8.0.

My Local Environment:

Gradle Wrapper (7.6)
Java 17 - oracle

Ubuntu 22.04

```text
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  24
  On-line CPU(s) list:   0-23
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 9 5900X 12-Core Processor
    CPU family:          25
    Model:               33
    Thread(s) per core:  2
    Core(s) per socket:  12
    Socket(s):           1
    Stepping:            0
    Frequency boost:     enabled
    CPU max MHz:         4950,1948
    CPU min MHz:         2200,0000
    BogoMIPS:            7385.94
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmul
                         qdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext pe
                         rfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm
                         _total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmu
                         lqdq rdpid overflow_recov succor smca fsrm
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   384 KiB (12 instances)
  L1i:                   384 KiB (12 instances)
  L2:                    6 MiB (12 instances)
  L3:                    64 MiB (2 instances)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-23
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
``` 

Build scan URL:
https://scans.gradle.com/s/zbbism66ent2s

Here's the JaCoCo report
https://github.com/LeoFuso/argo/suites/11470897407/artifacts/592102890

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it. 

***

Unfortunately, right now don't have capacity to investigate this deeper, and the current report doesn't point at a Gradle issue, it might be an environment one. Maybe there is some kind of error related to jvm was shutdown prematurely.
