### ISSUE TITLE
Show users when Gradle is storing configuration cache

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#24274]
Currently, for projects that enable the configuration cache, when the cache is invalidated, there is a sizable time that Gradle takes to serialize and write the configuration cache to disk. Today, users see `100% CONFIGURING [3m 16s]` stuck on the screen with time ticking away but no visible progress.

Example:
![image](https://user-images.githubusercontent.com/1418185/224170390-bb2d9e75-e230-4785-ba19-af1b4c7240fc.png)

### Expected Behavior
It would be great if Gradle instead showed `x% STORING CONFIGURATION [3m 16s]` that shows the actual state and tells you the percentage of how much of it is complete. 

### Current Behavior
It shows you `100% CONFIGURING [3m 16s]`  as described above making look like Gradle is stuck.

### Context
As more and more people are trying out Gradle configuration cache, this will become a potential confusion for many.

**Comment by liutikas** [comment]
https://cs.android.com/android-studio/gradle/+/master:subprojects/logging/src/main/java/org/gradle/internal/logging/console/BuildStatusRenderer.java;l=72?q=%22CONFIGURING%22&ss=android-studio seems to be the place to hook into it. What would be a good place to get the status of serialization?

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by mlopatkin** [comment]
With project isolation we can potentially have multiple workers configuring/loading/storing stuff, so it would probably make sense to show it as a worker state (i.e. instead of IDLE markers in the OP picture).

**Comment by ericoporto** [comment]
This would be useful to help diagnosis in case of CI issues

**Comment by bamboo** [comment]
> What would be a good place to get the status of serialization?

Gradle already has [build operations around the configuration cache storing and loading operations](https://github.com/gradle/gradle/blob/5b5514c90d99f506f77d0b789b5d38dcf4bafd57/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuildOperations.kt#L57) but they are missing a [`progress display name`](https://github.com/gradle/gradle/blob/07bc78e796246a0abbe23c815fbff3900a2d811a/subprojects/build-operations/src/main/java/org/gradle/internal/operations/BuildOperationDescriptor.java#L83) and so they are not currently displayed in the progress updates. 

Setting a proper `progressDisplayName` in the [`CC BuildOperationDescriptor`](https://github.com/gradle/gradle/blob/5b5514c90d99f506f77d0b789b5d38dcf4bafd57/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/ConfigurationCacheBuildOperations.kt#L57). should do the trick.

**Comment by mlopatkin** [comment]
Fixed in 8.5. Potential follow up in #29941.
