### ISSUE TITLE
Configuration cache incorrectly captures task

### ISSUE THREAD

**Issue by melix** [gradle/gradle#24289]
### Expected Behavior

When using the notation:

```gradle
inputs.files(someTask)
```

The configuration cache shouldn't try to serialize the task.

### Current Behavior

Build fails with:

```
 What went wrong:
Configuration cache problems found in this build.

2 problems were found storing the configuration cache, 1 of which seems unique.
- Task `:reader` of type `org.gradle.api.DefaultTask`: cannot serialize object of type 'org.gradle.api.tasks.Copy', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.0.2/userguide/configuration_cache.html#config_cache:requirements:task_access

```

### Context

I am updating the internal Micronaut build plugins to support the configuration cache. As part of it I was confused by the cache reporting that a `Copy` task was captured, when I was declaring a task as an input.

### Steps to Reproduce 

1. Create a file named `source.txt` with the following text: "Hello, Gradle!"
2. Create a file named `build.gradle` with the following text:
```gradle
def copy = tasks.register("copy", Copy) {
   destinationDir = layout.buildDirectory.dir("copy").get().asFile
   from file("source.txt")
}

tasks.register("reader") {
    inputs.files(copy)
    doLast {
         println new File(copy.get().destinationDir, "source.txt").text
    }
}

defaultTasks = ["reader"]
```
3. Create a `settings.gradle` file with the following text: `rootProject.name="bug"`

Run `gradle --configuration-cache` and see the build fail.

Workaround is to map the output:

```gradle
inputs.files(copy.map(Copy::getDestinationDir))
```

### Your Environment

Build scan URL: https://scans.gradle.com/s/gavgwgv2amk3a

**Comment by ov7a** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.
