### ISSUE TITLE
Jacoco Aggregation Plugin ExternalSystemException during project configuration

### ISSUE THREAD

**Issue by romansavka-mq** [gradle/gradle#24318]
Unable to configure outgoing variant for `ArtifactTypeDefinition.BINARY_DATA_TYPE` for instrumented android test in the android module. Receiving an exception during sync: [stacktrace.txt](https://github.com/gradle/gradle/files/10968827/stacktrace.txt)

### Expected Behavior
More descriptive error if the script is wrong. More documentation on integrating custom outgoing variants.

### Current Behavior
Unable to pass fileTree for an outgoing variant for `ArtifactTypeDefinition.BINARY_DATA_TYPE`.

### Context

I am trying to set up JaCoCo Report Aggregation Plugin in a project with JVM and Android modules. By providing the missing [outgoing variants](https://docs.gradle.org/current/userguide/test_report_aggregation_plugin.html#sec:test_report_aggregation_tasks) for Android modules.
Setup with only android unit tests works fine, the problem is attaching android instrumented test execution data. Android instrumented test generates not a single execution data file but separate execution for each test stored under the directory (coverageDirectory).

### Steps to Reproduce 

I attach an empty project with a single module, which has scripts to configure outgoing variants. 
Child module configuration is in `/gradle/testCoverage.module.gradle`. For root project in `/gradle/testCoverage.project.gradle`
After opening the project not able to sync. Neither execute :testCodeCoverageReport task.

Tried gradle 7.6 and 8.0.2.
[MyApplication7.6.zip](https://github.com/gradle/gradle/files/10968843/MyApplication7.6.zip)
[MyApplication8.0.2.zip](https://github.com/gradle/gradle/files/10968844/MyApplication8.0.2.zip)

### Your Environment
Operating system: macOS Ventura 13.2.1
AGP: 7.4.2
Gradle: 7.6 / 8.0.2
Build scan URL: https://scans.gradle.com/s/z5qatslw3dalw (when trying to execute :testCodeCoverageReport task)

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

This might be an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the Gradle Build Tool project.

===

Please, ask Android community about integrating jacoco instrumented android tests.
