### ISSUE TITLE
Documentation for setting values in the build environment is confusing

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#24314]
The documentation in question: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables

When is `-D` setting a system property on the command line and when a Gradle property? Knowing the exact logic of how these properties are processed/read at the various levels (init script, settings, builds) and having that documented would clarify the docs a lot.

**Comment by FrauBoes** [comment]
A question that came up for me: Is the list of system and Gradle properties extensive? For example, the [org.gradle.testkit.dir](https://docs.gradle.org/current/userguide/test_kit.html#sec:controlling_the_build_environment) property is not listed. While it is specific to the TestKit library, it would be good to know where to find other properties than the ones listed in the documentation.
