### ISSUE TITLE
ResolvableDependencies#getResolutionResult javadocs are confusing

### ISSUE THREAD

**Issue by melix** [gradle/gradle#24326]
## Context

This is a follow-up to https://gradle-community.slack.com/archives/C013WEPGQF9/p1678809617245989.

I am working on making the GraalVM native build tools plugin compatible with the configuration cache. As part of this, I am facing problems where lambdas are capturing `Configuration` instances, and need to replace the use of `Configuration` with configuration cache compatible objects.

An example of such capture [can be found here](https://github.com/graalvm/native-build-tools/blob/7adaa46bc4c0243c803aee53b877e0191a685167/native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java#L371).

I can get rid of the error by extracting the resolution result _outside_ of the lambda, e.g:

```
ResolutionResult resolutionResult =  project.getConfigurations()
                .getByName(sourceSet.getRuntimeClasspathConfigurationName())
                .getIncoming()
                .getResolutionResult()
```

However, I remembered that `getResolutionResult()`, at least in my mind, _triggered resolution_, which means that by extracting the code out of the lambda, this would be done too early.

I checked the javadocs for `getResolutionResult()` which say:

> Returns the resolved dependency graph, performing the resolution if required. This will resolve the dependency graph but will not resolve or download the files.

Which, for me, confirms that the resolution is eager if you call `getResolutionResult()`. That's why I asked on Slack because it seems strange that the official way to support the configuration cache actually invoves eager resolution, so I talked to @eskatos who confirmed that the method is in fact lazy.

Therefore, I think that the documentation is confusing. I think it tries to say that "if resolution is triggered later in time by calling a method on the resolution result, then it will resolve the dependency graph, but it will not resolve nor download the artifacts", which makes more sense.

So I would suggest to rephrase the javadocs, in order to make it clear what is lazy and what is not.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.
