### ISSUE TITLE
Gradle 8+ breaks actionable "useJUnitPlatform" calls

### ISSUE THREAD

**Issue by arturdryomov** [gradle/gradle#24331]
When using Gradle 8+ (like 8.0.2), changing the `useJUnitPlatform` call from `()` to `{}` produces an error.

For example, this block of code will not work:

```kotlin
subprojects {
    tasks.withType<Test>().configureEach {
        useJUnitPlatform {
            includeEngines("spek")
        }
    }
}
```
```
The value for task ':redacted' property 'testFrameworkProperty' is final and cannot be changed any further.
```
However, this one will work fine:
```
subprojects {
    tasks.withType<Test>().configureEach {
        useJUnitPlatform()
    }
}
```
To demonstrate this, I’ve made a trivial change at detekt/detekt#5906. As you can see, [CI steps there fail](https://github.com/detekt/detekt/actions/runs/4423885495/jobs/7757061009).

I suspect this happens because [the actionable call sets options as a separate step](https://github.com/gradle/gradle/blob/v8.0.2/subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java#L1012-L1015), as such mutating options twice. The overarching issue was described at #18606 but this one seems to be an oversight.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Did it work in previous versions of gradle? If yes, which ones? If no, then it might be expected behavior.

**Comment by arturdryomov** [comment]
@ov7a, yes, 7+ work fine with both variants. We’ve started to experience this when attempting an upgrade from 7+ to 8+.

**Comment by ov7a** [comment]
Could you specify the exact 7.x version, please? Does it work for a version between 7.3 (inclusive) and 7.6 (inclusive)?

**Comment by arturdryomov** [comment]
@ov7a, correct, all 7+ versions work. We keep up with all releases, the last one working was 7.6.1, all versions before it as well.

**Comment by ov7a** [comment]
Thank you for a fast reply and for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.
