### ISSUE TITLE
Error building cache entry results in persistent build errors

### ISSUE THREAD

**Issue by wfhartford** [gradle/gradle#2434]
Gradle is encountering an error when creating a cache entry for the output of a task. The error message is:
>  Could not store entry 014392ed8d44ea026a89833378cb2719 in remote build cache
>  org.gradle.api.GradleException: Could not pack property '$1': java.io.IOException: request to write '4096' bytes exceeds size in header of '0' bytes for entry 'property-$1/DataDirectServiceImplService.wsdl'

This error does not fail the build, but it does disable further caching, displaying the following:
>  The remote build cache is now disabled because a non-recoverable error was encountered.

Despite disabling the remote cache, the entry with the hash code above does get created in the cache. Subsequent builds then fail with the following: 
>  Could not load entry 014392ed8d44ea026a89833378cb2719 from remote build cache
>  \> Cached result format error, no origin metadata was found.

Inspection of this cache entry indicates that is seems to be an empty gzip file (.gz extension added by me as required by github): [014392ed8d44ea026a89833378cb2719.gz](https://github.com/gradle/gradle/files/1136242/014392ed8d44ea026a89833378cb2719.gz)

### Expected Behavior
* Failure to generate a cache entry (for whatever reason), should not result in a corrupt cache entry being written to the remote cache.
* Retrieving a corrupt entry from the cache should not result in a build failure; the cache entry should be ignored.

### Current Behavior
A failure generating a cache entry produces a corrupt file, which then gets cached.
Subsequent builds fail when they attempt to use the corrupted cache entry.

### Context
This issue is typically encountered during a build on our CI server (jenkins), once the initial error is encountered, subsequent builds fail until certain code changes are made which change the cache key or the offending cache entry is manually removed from the cache server. The root cause only seems to happen on Windows build slaves.
* Build scan of the initial build producing the corrupt cache entry: https://gradle.com/s/tyatjju2i6dgk. The failure of this build is due to a subsequent test failure, not the caching issue.
Build scan of subsequent build which fails due to the corrupt cache entry: https://gradle.com/s/wojdr4yyzt7eg

### Steps to Reproduce (for bugs)
I have not tried to create an isolated project to reproduce this bug. If the build scans above do not provide enough detail, I can put some time in to see if that is possible.

### Your Environment
https://gradle.com/s/tyatjju2i6dgk
https://gradle.com/s/wojdr4yyzt7eg

**Comment by wfhartford** [comment]
I've uploaded the full stack trace for both parts:
The exception logged when the corrupt cache entry is created: [failure-create-cache.txt](https://github.com/gradle/gradle/files/1136408/failure-create-cache.txt)
The exception output when the build fails due to the corrupt entry: [failure-load-cache.txt](https://github.com/gradle/gradle/files/1136407/failure-load-cache.txt)

**Comment by wfhartford** [comment]
The failing cache entry is for the output of a task which generates a WSDL file and associated XSD files using the wsgen utility. The relavent portion of the build file is below:

```gradle
def wsgenResourcesDir = file("$buildDir/client/wsgen/resources")
def wsimportSourcesDir = file("$buildDir/client/wsimport/java")
sourceSets {
  ws {
    java {
      srcDir wsimportSourcesDir
    }
    resources {
      srcDir wsgenResourcesDir
    }
  }
}

idea {
  module {
    generatedSourceDirs += wsimportSourcesDir
    generatedSourceDirs += wsgenResourcesDir
  }
}

task wsgen(dependsOn: classes) {
  def wsgenGarbageDir = file("$buildDir/client/wsgen/garbage")
  inputs.dir(sourceSets.main.output.classesDirs)
  outputs.dir(wsgenResourcesDir)
  outputs.cacheIf {true}
  doLast {
    wsgenGarbageDir.mkdirs()
    wsgenResourcesDir.mkdirs()
    ant {
      taskdef(name: 'wsgen',
          classname: 'com.sun.tools.ws.ant.WsGen',
          classpath: configurations.wstools.asPath)
      wsgen(keep: false,
          sourcedestdir: wsgenGarbageDir,
          destdir: wsgenGarbageDir,
          resourcedestdir: wsgenResourcesDir,
          genwsdl: true,
          classpath: sourceSets.main.runtimeClasspath.asPath,
          sei: 'com.ze.datadirect.service.DataDirectServiceImpl')
    }
    delete(wsgenGarbageDir)
  }
}
```

**Comment by bmuschko** [comment]
@lptr @wolfs Could you guys have a look?

**Comment by ldaley** [comment]
@lptr @wolfs this is another (albeit edge)reason to pack first and then upload; we won't store partial artifacts due to packing errors.

**Comment by lptr** [comment]
This is going to be fixed in Gradle 4.1.

**Comment by lptr** [comment]
PR #2473 has been merged, the fix for this issue is going to be delivered in Gradle 4.1.

**Comment by ykhandelwal913** [comment]
>Inspection of this cache entry indicates that is seems to be an empty gzip file (.gz extension added by me as required by github): [014392ed8d44ea026a89833378cb2719.gz](https://github.com/gradle/gradle/files/1136242/014392ed8d44ea026a89833378cb2719.gz)

How did you add the .gz extension?
