### ISSUE TITLE
Support serialization of error output in DependencyInsightTask

### ISSUE THREAD

**Issue by 6hundreds** [gradle/gradle#24356]
Tests in `DependencyInsightReportTaskIntegrationTest` that expecting dependency resolution failed are not compatible with CC now. The reason is proper output should came from `DependencyInsightReportTask.errorHandler` as a `StyledTextOutput` which is not serializable now. 

Populating of `ResolutionErrorRenderer` is happening during finalization of `DependencyInsightReportTask.rootComponentProperty`.

**Comment by ov7a** [comment]
IIUC, this was fixed by
* https://github.com/gradle/gradle/pull/24701

See https://github.com/gradle/gradle/pull/24701/files#diff-221e2739e1c2317d979535df22279eba1eb4bbffdcdc7d61adc1f28ce859fa2bL307
