### ISSUE TITLE
Dependency verification output is not stable in Gradle 8+

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#24362]
This seems to only happen with Gradle `8.0.2`, didn't notice it with Gradle `7.6.1` 

Running gradle with ` --write-verification-metadata pgp,sha512` gives inconsistent output. 

The [public key for ee4j](https://keyserver.ubuntu.com/pks/lookup?search=aa70c7c433d501636392ec02153e7a3c2b4e5118&fingerprint=on&op=index) is put in different place in the xml output.

Sometimes it outputs `<trusted-key id=` and NOT  `<pgp value`  : 
```
<trusted-key id="aa70c7c433d501636392ec02153e7a3c2b4e5118" group="org.eclipse.ee4j" name="project" version="1.0.6"/>
```

And if I run it again, it outputs `<pgp value` and NOT the `<trusted-key id=` : 
```
      <component group="org.eclipse.ee4j" name="project" version="1.0.6">
         <artifact name="project-1.0.6.pom">
            <pgp value="aa70c7c433d501636392ec02153e7a3c2b4e5118"/>
            <sha512 value="f6270549d4f45621332ca934757655d8a12e3803d3838a7fbfe33c75466adbd222af468796db71bfed804d1ef1e05cfbaa7898c8babb336b2239703b7e9b4c58" origin="Generated by Gradle"/>
         </artifact>
```

### Expected Behavior
given the same inputs, I should be to re-run gradle with ` --write-verification-metadata pgp,sha512` 

### Current Behavior
Sometimes if give variations in the output, even with the exact same input. 

### Your Environment
Gradle `8.0.2`

**Comment by ljacomet** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to efficiently track down and fix your problem. Our available resources are severely limited and we must be sure we are looking at the exact problem you are facing.  

If we have a reproducer we may be able to also suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you provide more information.

***

If we can reproduce this, it would be considered a regression.
