### ISSUE TITLE
Make paths in console output clickable

### ISSUE THREAD

**Issue by donat** [gradle/gradle#24373]
Modern terminals have support for hyperlinks:
- https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#quick-example
- https://www.bleepingcomputer.com/news/microsoft/windows-terminal-14-released-with-hyperlink-and-jump-list-support/

We should check what file paths are printed to the console. If the rich console is being used, we should replace the paths with hyperlinks. We should also remove the `file://` prefix from any output (e.g. for test report output).

Clickable links may break in some console. We should ensure that the output is intact for major consoles on supported OSs. We should also think about unexpected path formats (i.e. file paths with whitespace).

Current output
```
* What went wrong:
Execution failed for task ':app:test'.
> There were failing tests. See the report at: file:///Users/donat/project/build/reports/tests/test/index.html
```

Proposed output
```
* What went wrong:
Execution failed for task ':app:test'.
> There were failing tests. See the report at /Users/donat/project/build/reports/tests/test/index.html
```

**Comment by donat** [comment]
@reinsch82 What should we do here? Should we even consider using the new URL approach, or should we abandon this idea and consider the current state good enough?

**Comment by reinsch82** [comment]
I wouldn't consider it high priority for now. 
So I lean towards: good enough
