### ISSUE TITLE
Provide task's help with:  gradle <task> --help

### ISSUE THREAD

**Issue by neblung** [gradle/gradle#2438]
From tools like `git` or `docker` you are used to get specific help with e.g.
```
git checkout --help
```
or
```
docker run --help
```
I would appreciate to get help for specific gradle tasks with e.g.
```
gradle test --help
```
instead of the hard to remember
```
gradle help --task test
```

**Comment by bmuschko** [comment]
From a user's perspective I'd agree that it would be preferable to have the same usage pattern. Unfortunately, the change would be a breaking change and I doubt that we'd make the change before Gradle 5.0. Would you be interested in looking into the amount of work involved in this change and/or provide a pull request?

**Comment by bmuschko** [comment]
Looks like this issue didn't get any traction or other votes from the community. I am going to close this for now. Please comment on this issue if you are planning to work on it.
