### ISSUE TITLE
Gradle build failing after upgrading to 8.0.2 Caused by Failed to apply plugin class 'org.gradle.api.plugins.JavaPlugin'

### ISSUE THREAD

**Issue by cv-prasad** [gradle/gradle#24407]
As per [documentation](https://docs.gradle.org/current/userguide/upgrading_version_7.html) I have upgraded gradle but build.gradle is failing with the following error :
```
Failed to apply plugin class 'org.gradle.api.plugins.JavaPlugin'.
> No signature of method: static org.gradle.api.plugins.internal.JvmPluginsHelper.configureDocumentationVariantWithArtifact() is applicable for argument types: (String, null, String, EmptyList, String, org.gradle.api.internal.file.DefaultSourceDirectorySet_Decorated...) values: [sourcesElements, null, sources, [], sourceJar, main source, ...]
 > No signature of method: static org.gradle.api.plugins.internal.JvmPluginsHelper.configureDocumentationVariantWithArtifact() is applicable for argument types: (String, null, String, EmptyList, String, org.gradle.api.internal.file.DefaultSourceDirectorySet_Decorated...) values: [sourcesElements, null, sources, [], sourceJar, main source, ...]

```

 Line causing this issue is 
   apply plugin: 'java-library'
 
 I have searched in documentation and trouble shooting guide but did not find anything. Documentation suggested to update plugins but I am not able to understand how to do that in case of java-library

**Comment by TWiStErRob** [comment]
Try to run with `gradlew ... --stacktrace`, it should reveal who is causing it. You might be getting a report for `java-library`, because some other plugin is doing `project.plugins.withId("java-library") { ... }`. And `...` seemingly includes calling an internal API that changed.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
