### ISSUE TITLE
8.1 RC1: Future of Idiomatic Gradle: includeBuild v. kotlin-dsl v. configureondemand

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#24408]
### Context
I have a traditional project setup:
 * `gradle/plugins` is hosting convention plugins with `kotlin-dsl` applied.
 * `pluginManagement { includeBuild("gradle/plugins") }` in root `settings.gradle`.
 * `org.gradle.configureondemand=true` in root `gradle.properties`.

I can't even use `configureondemand` with `gradlew -Dorg.gradle.unsafe.isolated-projects=true`, even though in that case it's not incubating.

### Repro
1. Clone https://github.com/TWiStErRob/net.twisterrob.colorfilters
2. Check out [a34cf1f](https://github.com/TWiStErRob/net.twisterrob.colorfilters/tree/a34cf1f0eda19d1d81c8bb25f33deb3cee0a96aa)
3. Upgrade Gradle to `8.1-rc-1` in `gradle/wrapper/gradle-wrapper.properties`
4. `gradlew` in root directory

### Current Behavior
> Using the configuration on demand feature with the Kotlin DSL. This behavior has been deprecated. This will fail with an error in Gradle 9.0. See https://docs.gradle.org/8.1-rc-1/userguide/kotlin_dsl.html#kotdsl:limitations for more details.

### Expected Behavior
Project "just works".

### Workaround
None known, tried adding `org.gradle.configureondemand=false` to `gradle/plugins/gradle.properties`, but since it's included in the root project the gradle.properties from the upper level is in play.

**Comment by eskatos** [comment]
Hi Róbert,
IIUC with 8.1 you get that deprecation warning when configure-on-demand is enabled. This is expected.
You can't enable configure-on-demand for only one build in a composite build tree, this option applies to the whole build invocation.

**Comment by TWiStErRob** [comment]
Yes, but I want to enable Configuration on demand for everything, it just happens to have an included build which has `kotlin-dsl` applied. So do we have to choose between "configuration on demand and project isolation with Groovy DSL", or "Kotlin DSL with no speedup"? Or to put it in another way: it is not supported and will never be considered to use configuration on demand with convention plugins (because `src/main/kotlin/foo/bar/baz.gradle.kts` requires `kotlin-dsl`)? (I thought moving from `allprojects` to convention plugins is the first step towards being able to use project isolation.)
