### ISSUE TITLE
8.1 RC1: Configuration cache only reused after second attempt

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#24421]
### Expected Behavior
I can run this command twice: `./gradlew --configuration-cache detektGenerateConfig`

The first invocation stores the cache. The second reuses it.

### Current Behavior
I have to run the command three times - only the third invocation reuses it.

### Context
I have a test that runs the command two times in a TestKit environment:

```kotlin
        @Test
        fun `can be loaded from the configuration cache`() {
            val gradleRunner = DslTestBuilder.kotlin().build()

            gradleRunner.runTasks("--configuration-cache", "detektGenerateConfig")
            val result = gradleRunner.runTasks("--configuration-cache", "detektGenerateConfig")

            assertThat(result.output).contains("Reusing configuration cache.")
        }
```

This has worked fine for many Gradle releases, but fails on Gradle 8.1-rc-1. The assertion failure says the output contains "Configuration cache entry stored" but this should have happened in the first invocation.

When I make this change:

```kotlin
        @Test
        fun `can be loaded from the configuration cache`() {
            val gradleRunner = DslTestBuilder.kotlin().build()

            gradleRunner.runTasks("--configuration-cache", "detektGenerateConfig")
            gradleRunner.runTasks("--configuration-cache", "detektGenerateConfig") //               << ADDED LINE
            val result = gradleRunner.runTasks("--configuration-cache", "detektGenerateConfig")

            assertThat(result.output).contains("Reusing configuration cache.")
        }
```

It passes again.

### Steps to Reproduce 
This is the tricky part - I've pulled the generated project used in the test and tried replicating on the command line but without success. So I don't have a self-contained reproducer.

I will provide any info I can. These are the changes made to the parent build to update to 8.1-rc-1: https://github.com/detekt/detekt/compare/main...3flex:detekt:gradle-8.1

Compare results from the base branch (Gradle 7.6.1, succeeds) vs my branch (Gradle 8.1-rc-1, fails): `./gradlew :detekt-gradle-plugin:functionalTest --tests 'io.gitlab.arturbosch.detekt.ConfigurationCacheSpec$Generate config task.can be loaded from the configuration cache'`

### Your Environment

Build scan URL: https://ge.detekt.dev/s/hwto3ncjzw3dw (from the parent build)

**Comment by bamboo** [comment]
Hi @3flex,

Gradle 8.1 has better detection of configuration inputs and it seems the first execution of `detektGenerateConfig` is changing files observed during the configuration phase:

```
Calculating task graph as configuration cache cannot be reused because the file system entry 'config\detekt\detekt.yml' has been created.
```

If `config/detekt` is not supposed to be detected as a configuration input then something is indeed wrong.

**Comment by TWiStErRob** [comment]
What you're describing sounds like normal behavior, `project.extensions.detekt.config` (a `FileCollection`) has the default value of `config/detekt/detekt.yml` which is used as input for Detekt and Baseline tasks, and output for GenerateConfig. So initially that file doesn't exist, but then after running `detektGenerateConfig` it's written. @bamboo does having it as task input, mapped like this:
![image](https://user-images.githubusercontent.com/2906988/226740004-ba5d5aca-1eca-465c-ab50-cf8cd858f018.png)
count as "configuration input"?

**Comment by TWiStErRob** [comment]
Related release notes section: https://docs.gradle.org/8.1-rc-1/release-notes.html#configuration-inputs-detection-improvements

**Comment by 3flex** [comment]
Ah thanks, yes that does make sense and I didn't look closely enough at the log to spot that line about the configuration cache not being reused because the file had been created. Sorry for the noise - this is just something we'll need to account for in that test.
