### ISSUE TITLE
8.1 RC1 Android Studio and IDEA Sync fails with `org.gradle.warning.mode=fail`

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#24432]
### Context
I'm trying to use `org.gradle.warning.mode=fail` in projects I work on, so that deprecations and changed behaviors are actioned as soon as necessary, not last minute when they break. Renovate upgraded all my projects to Gradle 8.1, and when syncing them in IDEA / Android Studio, I get a deprecation warning:
> The `org.gradle.util.VersionNumber` type has been deprecated.

This is coming from an internal init script in the Android plugin, so tracking the issue in [274469173](https://issuetracker.google.com/issues/274469173). Looking at [the osdetector issue](https://github.com/google/osdetector-gradle-plugin/issues/24), you might want to consider reverting the nagging and postponing it until users can upgrade to a stable version of Android Studio / IntelliJ IDEA that has the fix for [274469173](https://issuetracker.google.com/issues/274469173). cc @eskatos

### Expected Behavior
Be able to use `org.gradle.warning.mode=fail` and develop code with the protection of that flag.

### Current Behavior
`org.gradle.warning.mode=fail` is invalidated by deprecation nagging introduced in https://github.com/gradle/gradle/issues/21902, as it errors Gradle Sync in IDEA.

### Steps to Reproduce 
1. Change gradle wrapper to 8.1 RC1 in any project
2. Import the project in IDEA/Android Studio
3. See screenshot and logs at https://issuetracker.google.com/issues/274469173

### Your Environment
Build scan URL: not sure how to do this with IDEA Gradle Sync, but the repro and traces is quite trivial.

**Comment by eskatos** [comment]
Thank you for the report @TWiStErRob!

**Comment by eskatos** [comment]
@TWiStErRob, good point, done!

Deprecation warning log removed and postponed to a later Gradle 8.x

* https://github.com/gradle/gradle/pull/24449

This will be part of 8.1 RC2
