### ISSUE TITLE
Play plugin cannot compile Twirl templates other than HTML format

### ISSUE THREAD

**Issue by ymwang1984** [gradle/gradle#2443]
### Expected Behavior

Gradle's twirl engine should be able to compile templates other than html extension, such as js.

### Current Behavior

Compilation fails immediately for a sample Javascript template. So far so good for Html templates.

### Context

Product teams in my company are trying to migrate several production Play front-end projects from SBT to Gradle. But they cannot migrate due to this issue since they use various kinds of Twirl templates (i.e. not limited to html).

Probably take a look at the twirl compiler in Gradle? In [the official doc](https://docs.gradle.org/current/userguide/play_plugin.html), when I search Twirl, it seems to me that only HTML Twirl is supported.

### Steps to Reproduce (for bugs)

NA

Check out this very simple repo:

https://github.com/ymwang1984/play-on-gradle-twirl

It contains a very simple template under app/views/ which is generic.scala.js

"./sbt run" is able to compile the file and run the whole project.

But Gradle cannot compile this project due to inability to compile this generic.scala.js.

### Your Environment

Normal Mac and Linux (Red Hat). The above repo failed on both operating systems.

 * Build scan URL:

**Comment by ymwang1984** [comment]
@eriwen Not sure if you could take a look? Thank you!

**Comment by ymwang1984** [comment]
@eriwen looks like I can configure extra Twirl source set to get around this:

```
model {
components {
        play {
            sources {
                extraTwirl(TwirlSourceSet) {
                    source.srcDir "app"
                    source.include "**/*.js"
                }
            }
        }
    } 
}
```

**Comment by eriwen** [comment]
@ymwang1984 Yes, so are you still blocked?

**Comment by ymwang1984** [comment]
Not now, please close this one. Thank you.

But is there a way to modify the twirl filter besides the above method?

**Comment by eriwen** [comment]
@ymwang1984 Not that I'm aware of.

**Comment by big-guy** [comment]
@ymwang1984 Instead of adding an extra source set, you can configure the existing twirl source set.

Run `gradle components` to see the configuration of the play component:

```
Play Application 'play'
-----------------------

Source sets
    Java source 'play:java'
        srcDir: app
        includes: **/*.java
    JavaScript source 'play:javaScript'
        srcDir: app/assets
        includes: **/*.js
    JVM resources 'play:resources'
        srcDir: conf
    Routes source 'play:routes'
        srcDir: conf
        includes: routes, *.routes
    Scala source 'play:scala'
        srcDir: app
        includes: **/*.scala
    Twirl template source 'play:twirlTemplates'
        srcDir: app
        includes: **/*.html

Binaries
    Play Application Jar 'play:binary'
        build using task: :playBinary
        target platform: Play Platform (Play 2.4.0, Scala: 2.11, Java: Java SE 8)
        toolchain: Default Play Toolchain
        classes dir: build/playBinary/classes
        resources dir: build/playBinary/resources
        JAR file: build/playBinary/lib/play-on-gradle-twirl.jar
```

And then you can configure the `twirlTemplates` source set (from your example application):
```
model {
    components {
        play {
            injectedRoutesGenerator = true
            sources {
                twirlTemplates {
                    source {
                        include "**/*.js"
                    }
                }
            }
        }
    }
}
```

**Comment by ymwang1984** [comment]
@big-guy Thanks!
