### ISSUE TITLE
Alert Plugins of Special Case Exceptions Suppressing Deprecation Warnings 

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#24450]
Whether or not we choose to move forward with any sort of "strict mode" to display these warnings regardless, we should alert the plugin authors of potential problems with the "special cases" in `DefaultConfiguration` that do not emit warnings for behavior that should be considered deprecated.

This ticket is just to remember to do that after the 8.2 RC 1 release.  It should be moved to 8.2 RC 2 or 8.3 RC 1 immediately after either of those milestones are created.

**Comment by big-guy** [comment]
Follow up with KMP and AGP teams

**Comment by tresat** [comment]
It would be great to use #25810 for this

**Comment by big-guy** [comment]
Both teams are aware
