### ISSUE TITLE
ANTLR Plugin should output to a proper package

### ISSUE THREAD

**Issue by ty1824** [gradle/gradle#24452]
### Expected Behavior
I should be able to use ANTLR as it is specified - including grammar files in package directories and the generated source should properly output to those same directories (under `generated-src`).

Additionally, task dependencies should properly be configured to account for the generated source. I believe there may be issues already defined for this problem.

### Current Behavior
ANTLR fails to generate, complaining of missing tokens files

> error(114): com/workday/xols/ebe/EbeParser.g4:7:23: cannot find tokens file

Issues like this have been reported for a long time, with many instances of workarounds being used.
https://stackoverflow.com/questions/30642144/generating-antlr4-grammar-files-with-package-declaration-in-gradle

### Context
There is a companion issue under the ANTLR project: antlr/antlr4#4202

We have successfully used ANTLR in several projects with a workaround of:
1) Place ANTLR code directly under `src/main/antlr`
2) Manually specify the output directory 
3) Configure source sets

Workaround Project structure
```
root
|- src
|  |- main
|  |  |- antlr
|  |  |  |- MyLexer.g4
|  |  |  |- MyParser.g4
|  |  |- kotlin
...
```

Relevant gradle configuration is as follows (rest has been truncated)
```
plugins {
    kotlin("jvm")
    antlr
}

dependencies {
    antlr("org.antlr:antlr4:$antlrVersion")
}

tasks {
    generateGrammarSource {
        arguments.addAll(listOf("-visitor"))
        outputDirectory = File("${project.projectDir}/build/generated/antlr/main/java/com/workday/wal/parser/antlr")
    }

    compileKotlin {
        dependsOn(generateGrammarSource)
    }
}

sourceSets.getByName("main").java {
    srcDir("build/generated/antlr/main/java")
}
```

This is non-ideal. Every time we create a project, we have to repeat this configuration. This should not be necessary to obtain a properly structured project.

Ideal Project structure
```
root
|- src
|  |- main
|  |  |- antlr
|  |  |  |- com/example/my/package
|  |  |  |  |- MyLexer.g4
|  |  |  |  |- MyParser.g4
|  |  |- kotlin
...
```

Ideal gradle configuration is as follows (same as above but note the absence of unnecessary configuration)
```
plugins {
    kotlin("jvm")
    antlr
}

dependencies {
    antlr("org.antlr:antlr4:$antlrVersion")
}

tasks {
    generateGrammarSource {
        arguments.addAll(listOf("-visitor"))
    }
}
```

Specifying a configuration like this should _just work_, without requiring additional configurations.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

This might be an issue with Antlr. We actually have an [integration test ](https://github.com/gradle/gradle/blob/0c23eea3acc61f9ce9d7a440ac73e84bd0c93050/subprojects/antlr/src/integTest/groovy/org/gradle/api/plugins/antlr/Antlr4RelocationIntegrationTest.groovy) similar to your case and it works fine.

**Comment by elecharny** [comment]
Also note that the ```antlr-maven-plugin``` was working just fine WRT code generation (ie it used the package names to generate the proper directories)
