### ISSUE TITLE
Gradle precompiled convention plugins: Typesafe action block using pluginManager.withPlugin

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#24462]
### Expected Behavior
```kotlin
pluginManager.withPlugin("org.jetbrains.kotlin.jvm") { // this is KotlinPlatformJvmPlugin
  kotlin { // generated extensions accessor
  }
}
```

### Current Behavior
```kotlin
pluginManager.withPlugin("org.jetbrains.kotlin.jvm") { // this is Plugin<*>
  extensions.getByName<KotlinJvmProjectExtension>("kotlin") { // manual accessing the kotlin extension, could fail
  }
}
```

### Context
With precompiled plugins Gradle already extract the `plugins` block, applies the plugins and generates type safe accessors, like extensions.
But beside applying a plugin, some plugins needs to apply custom logic if the consumer applies another plugin. This is done using  `pluginManager.withPlugin("id", action)`. The action block is currently untyped, for example, you need to use `extensions.getByName("kotlin")` to get the kotlin extension if using `pluginManager.withPlugin("kotlin.jvm")`.
This is different when using `plugins { kotlin("jvm") }`. 
Adding type safe generated accessors would unify the behavior with `plugins {}`.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

***

What you are asking for would imply dynamic type discovery at the compile time, which is not possible.

**Comment by hfhbd** [comment]
> What you are asking for would imply dynamic type discovery at the compile time, which is not possible.

How is this different to the existing plugins block?

**Comment by eskatos** [comment]
This would be much more complex given `withPlugin(id)` can be invoked imperatively basically anywhere. This is very different than the `plugins {}` block. This is not something we want to do.
