### ISSUE TITLE
Please Improved China download speed

### ISSUE THREAD

**Issue by JingweiWang** [gradle/gradle#2446]
You maybe konw Chinese Network was block, so when I download the url `https://services.gradle.org/distributions/gradle-xxx-xxx.zip` very slowly.

So can you as [VS code](https://code.visualstudio.com/updates/v1_12#_china-downloads) as Improved China download speed?

Think you.

**Comment by bosskwei** [comment]
Stupid question, gou pi bu tong

**Comment by JingweiWang** [comment]
@bosskwei You can you up. We have had enough of phrases.
