### ISSUE TITLE
`--export-keys` is not compatible with the configuration cache

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#24461]
### Steps to Reproduce 
Run `./gradlew --export-keys` with `gradle/gradle` repository

### Expected Behavior
Builds suceeds, new keys are written

### Current Behavior
Builds fails with over 9000 of configuration cache errors like `Invocation of 'Task.project' by task ':architecture-test:compileArchTestGroovy' at execution time is unsupported.`

### Context
We fixed `--write-verification-metadata` mode, but `--export-keys` alone flew under radars. This mode causes all configurations to be resolved at the end of the build, materializing all tasks that contribute their outputs to these configurations. This is considered execution time, and task configuration code is not written to be execution-time compatible.

As a short-term workaround, we shouldn't use the configuration cache for `--export-keys`, just like we do not do that for `--write-verification-metadata`.

### Your Environment
Build scan URL: https://ge.gradle.org/s/ptgiz3aldqgfw

**Comment by 6hundreds** [comment]
Fixed in https://github.com/gradle/gradle/pull/24480
