### ISSUE TITLE
8.1-20230323001115: External Kotlin script compilation broken under specific circumstances

### ISSUE THREAD

**Issue by davidburstromspotify** [gradle/gradle#24481]
### Current Behavior

If an external Kotlin script is applied on a project AND that project has e.g. the `java-library` plugin applied AND the script has a non-empty `buildscript` block, the compiler cannot resolve e.g. `java.util.List` when used as a FQN.

### Context
This worked in 8.1-rc-1 and 8.1-20230322000730+0000, but not in 8.1-20230323001115+0000.

### Steps to Reproduce 

[gradle-8.1-20230324001534-external-script-fqn.zip](https://github.com/gradle/gradle/files/11060285/gradle-8.1-20230324001534-external-script-fqn.zip)

Run `./gradlew`, script compilation should fail. Check README.md and comments.

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.
