### ISSUE TITLE
Docs: add 'extra properties' example in 'Migrating build logic from Groovy to Kotlin'

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#24508]
### Expected Behavior

When migrating Gradle build logic from Groovy to Kotlin, I have trouble trying to determine how to migrate 'extra properties'.
Extra properties are not mentioned on the [Migrating build logic from Groovy to Kotlin](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html) page.

This is especially confusing because in Groovy extra properties are accessed via a different syntax: `ext` in Groovy, `extra` in Kotlin.

I think an example would be more clear:

> In Groovy [extra properties](https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:extra_properties) can be modified using the owning object's `ext` property.
>
> ```lang-groovy
> ext.springVersion = "3.1.0.RELEASE"
> project.ext.foo = ...
> task.ext.bar = ...
> ```
> 
> In Kotlin they are modified using owning object's `extra` property
> ```lang-groovy
> extra["springVersion"] = "3.1.0.RELEASE"
> val foo by project.extra ...
> val bar by task.extra ...
> ```
>
> See [the Kotlin DSL documentation](https://docs.gradle.org/current/userguide/kotlin_dsl.html#extra_properties) for more details...

This would help with being able to ctrl+f to find the `ext` code.

### Current Behavior

While ['extra properties' are documented on the Kotlin DSL page](https://docs.gradle.org/current/userguide/kotlin_dsl.html#extra_properties), there is no comparative example between Groovy and Kotlin. It's not easy to connect the `ext` used in Gradle to the `extra` properties in Gradle.

There is a comparative example [here](https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:extra_properties) that I think could be re-used and included on the 'Migrating build logic from Groovy to Kotlin' page.

### Context

Example of confusion: https://stackoverflow.com/questions/75845497/converting-build-gradle-to-build-gradle-kts-it-cant-not-got-error-like-unresolve

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

***

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
