### ISSUE TITLE
Having issues using test module from Vocarerum labs

### ISSUE THREAD

**Issue by Burruben** [gradle/gradle#24539]
Recently enrolled into a program school that my employer offers and was sent a link to test out skills through Vocareum Labs/Gradle. First lesson asks to create an empty file within a folder and then run "run-workflow step-01" to make sure it works. Currently pulling my hair out trying to see exactly what I did wrong but there isn't much to go on. Not sure if there is a forum for beginner programmers either as I'm really out at sea with this. Any help would be appreciated.
<img width="938" alt="Proof-01" src="https://user-images.githubusercontent.com/29074753/228325793-d0d2b776-9266-47d8-8da6-82ba0ca8aefa.PNG">
<img width="933" alt="Proof-02" src="https://user-images.githubusercontent.com/29074753/228325829-ebcfdf12-4fef-4d6b-a385-13c63edd6b7c.PNG">
<img width="939" alt="Proof-03" src="https://user-images.githubusercontent.com/29074753/228325852-7f626895-7d10-4369-944e-0a3c8e215236.PNG">
@bot-gradle

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
