### ISSUE TITLE
Test event in Gradle TAPI has incomplete or incorrect data

### ISSUE THREAD

**Issue by HackerMadCat** [gradle/gradle#24538]
I have investigated several cases where Gradle TAPI provides into IntelliJ IDEA incomplete or incorrect information in tests events. I have created [GradleTestEventConverter](https://github.com/JetBrains/intellij-community/blob/7edc9a8ce26efdc1d81005a68c71905943d8d788/plugins/gradle/java/src/execution/test/runner/events/GradleTestEventConverter.kt#L31) which converts and repairs data in events.

I can describe cases which I find:
 - Display name of method, parametrised method, suite, class events are quoted and has prefixes. E.g. `Test name()`, `Test name()(org.example.TestCase)` and `Test suite 'name(org.example.TestCase)'` should be `name`;
 - Display name for JUnit 5 method event by default has information about method arguments. E.g. `test()`, `test(int, String)`, etc should be `test`;
 - Display name for JUnit 4 class event has class with package prefix. E.g. `org.example.TestCase` should be `TestCase`;
 - Display name for parametrised intermediate method event (which class are annotated by `@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)`) has trailing space in name. E.g. `pretty name (int)[1]` should be `pretty name`;
 - Class and method names are absent for JUnit 5 parametrised and Spock intermediate method events;
 - Method name for JUnit 5 parametrised method event has suffix with parameter number.  E.g. `test(int)[1]`, `test(int)[2]`, `test(int)[3]`, etc should be `test`;
 - Method name has unparsed signature of test method. I prefer to see here only method name. E.g. `test()`, `test(int)`, `test(int)[1]`, etc should be `test`;

Method name in case with Junit 5 parametrised intermediate method event and @DisplayName annotation cannot be repaired. Because we don't have methodName and className. Also, displayName nothing describes about original method name.

Note: Intermediate method event is an event which happens between class and leaf method events. These event has non empty suite name.

I prepared project which covered all these cases.
[gradle-junit-project.zip](https://github.com/gradle/gradle/files/11092734/gradle-junit-project.zip)

Seems incorrect display name generates in [backwardsCompatibleDisplayNameOf](https://github.com/gradle/gradle/blob/1d3837010f046965262145f2354f2d45d66c9ef6/subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestOperationMapper.java#L115)

**Comment by Franziskus1988** [comment]
@HackerMadCat 

> Method name in case with Junit 5 parametrised intermediate method event and @DisplayName annotation cannot be repaired. Because we don't have methodName and className. Also, displayName nothing describes about original method name.

I executed your test project with the latest [Gradle Nightly](https://gradle.org/release-nightly/) and the result for the parameterized test `parametrized_test` in XML is still reported like this:
```
  <testcase name="[1] 1, first" classname="org.example.JavaTestCase" time="0.04"/>
  <testcase name="[2] 2, second" classname="org.example.JavaTestCase" time="0.001"/>
```

Do I understand it right that this and thus my issue (https://github.com/gradle/gradle/issues/28866) can't be fixed currently?

**Comment by HackerMadCat** [comment]
@Franziskus1988 Thank you for the notification! My issue was about the Gradle test events in the Gradle TAPI. I am not aware of how TAPI test events match the XML in the `build/test-results` folder.

However, after testing your case, I found that Gradle 8.8 loses information about the test's display name. The correct test display name is contained only inside the InternalTestDescriptor.
<img width="1120" alt="image" src="https://github.com/gradle/gradle/assets/11194423/e6a4a388-97d6-457e-b7d9-814980b051da">

### Test result in the Gradle 8.7
<img width="826" alt="image" src="https://github.com/gradle/gradle/assets/11194423/770ca80a-edf5-4677-926a-952c0c1f8df0">

### Test result in the Gradle 8.8 SNAPSHOT
<img width="620" alt="image" src="https://github.com/gradle/gradle/assets/11194423/9e66b6c5-9644-4007-919e-8e72356457ac">

@ov7a is it expected?

**Comment by ov7a** [comment]
@HackerMadCat thanks for testing this out!

It is expected. In #28019 the test display name was decoupled from the operation display name, so IDEs are expected to call `TestOperationDescriptor.getTestDisplayName()` to get test name (instead of parsing it from the operation display name).

However, it would be nice to preserve the old style of operation display name for some cases, so I plan to improve that.
