### ISSUE TITLE
A way to get current ABI name

### ISSUE THREAD

**Issue by paulocoutinhox** [gradle/gradle#24545]
Hi,

Can you add in gradle a way to we get current ABI name?

Example:

```
defaultConfig {
    minSdk 16
    targetSdk 33
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    consumerProguardFiles "consumer-rules.pro"
    externalNativeBuild {
        cmake {
            arguments "-DCMAKE_TOOLCHAIN_FILE=build/kotlin/${currentABI}/toolchain.cmake"
        }
    }
}
```

You can add a variable like `${currentABI}` to represent the current ABI.

Thanks.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug
