### ISSUE TITLE
Gradle test stuck indefinitely

### ISSUE THREAD

**Issue by thisisArjit** [gradle/gradle#24570]
It is happening quite frequently but definitely not always. Attaching thread dump for the stuck gradle test process.

ps -ef | grep gradle -> 
[gradle_processes.txt](https://github.com/gradle/gradle/files/11111013/gradle_processes.txt)

There are 3 processes
[daemon-td-25190.txt](https://github.com/gradle/gradle/files/11111017/daemon-td-25190.txt)
[gradle-td-24942.txt](https://github.com/gradle/gradle/files/11111018/gradle-td-24942.txt)
[worker-td-160595.txt](https://github.com/gradle/gradle/files/11111019/worker-td-160595.txt)

gradle version - 6.8.3

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to efficiently track down and fix your problem. Our available resources are severely limited and we must be sure we are looking at the exact problem you are facing.  

If we have a reproducer we may be able to also suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you provide more information.

***

Try upgrading to a more recent version of Gradle or provide a full reproducer.
