### ISSUE TITLE
Address performance regression in configuration cache for 8.1

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#24584]
After unconditionally enabling configuration cache encryption.

#### Context

This was observed during:
* pull-request https://github.com/gradle/gradle/pull/24293

#### All Performance Tests

https://builds.gradle.org/buildConfiguration/Gradle_Release_Check_AllPerformanceTests_Trigger/63132832

Original _performance regression issue_: https://github.com/gradle/gradle-private/issues/3771

**Comment by inktomi** [comment]
I've noticed this in our project as well. With Gradle 8.1 RC-2 and the configuration cache some of our tasks are taking over 2x their normal length, and frequently failing due to GC Overhead errors. A little under half the runtime is spent in GC, according to gradle enterprise. 

Disabling the configuration cache solved this for us.

**Comment by abstratt** [comment]
@inktomi Which previous version of Gradle did you compare 8.2 RC1 with?

**Comment by inktomi** [comment]
@abstratt I think it really got worse in RC2. I don't recall seeing nearly as many memory issues with RC1, though we did see a few.

**Comment by abstratt** [comment]
In your specific case (GC overhead failures, much slower execution, probably due to GC pressure), could you try increasing the max heap size (btw, what heap size did you have in place?)?

**Comment by inktomi** [comment]
Due to how our builds execute (Gradle Client, Gradle Daemon, Kotlin's Dameons) we set both -Xmx and -Xms at 13G. That puts us at the 40G limit our CI builds get to use.

**Comment by rohilchodankar** [comment]
We are seeing something similar with our builds, post trying out Gradle 8.0 with Configuration cache. GC Overhead error and Memory usage spiking to 95%. It works pretty well with Gradle 7.6.1  + Configuration cache. 
We also have tried updating max heap size from 16G to 32G

**Comment by abstratt** [comment]
We expect 8.2 to be slightly faster than 8.1 with configuration cache enabled. Also, we expect 8.3 to faster than 8.2 - at least that is the case ATM.

**Comment by abstratt** [comment]
Fixed by various PRs aiming to reduce object allocation rate/memory footprint that went into 8.2 and 8.3.

**Comment by abstratt** [comment]
Reopening this to consider re-updating the performance baseline commit.

**Comment by bamboo** [comment]
8.2 RC1 is unblocked.
