### ISSUE TITLE
Provide documentation about removing auto-provisioned toolchains

### ISSUE THREAD

**Issue by ov7a** [gradle/gradle#24581]
Gradle can [auto-provision toolchains](https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning).

There is documentation on that, but no instructions about how to properly remove an auto-provisioned toolchain.

A note about stopping gradle daemon should be added at least (to clear the cache)

**Comment by ov7a** [comment]
This is a valid documentation issue which we will address.

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by Anayverma** [comment]
hey @ov7a  I am a beginner and interested to contribute in this.

**Comment by ov7a** [comment]
@Anayverma Thank you!

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for guidelines.

You can also look at a [previous attempt](https://github.com/gradle/gradle/pull/26519) to fix this.

**Comment by JayWei1215** [comment]
Hi, I've submitted a PR:https://github.com/gradle/gradle/pull/28334 for this issue. Could you please review it for me? @ov7a
