### ISSUE TITLE
Gradle 8.1-RC breaks nested map properties with non-string keys without deprecation

### ISSUE THREAD

**Issue by shoaniki** [gradle/gradle#24594]
Previously, a `@Nested MapProperty` could have keys of any type.
It has been decided to deprecate this behavior and require keys to be strings (see #23045).
However, Gradle 8.1 appears already to assume that keys will be strings.

### Expected Behavior
Using a `@Nested MapProperty` with non-string keys should call `toString` on the keys, as before.
A deprecation warning should be emitted to notify users that this will be changed in a future release.

### Current Behavior
Gradle 8.1 assumes keys can be cast to String:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':reproduce'.
> class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
```
Since there is no warning, users are surprised that a build that worked fine in 8.0 is now broken.

### Context
Works in 8.0, broken in 8.1-RC-1 and 8.1-RC-2.

The new requirement for string keys is not a problem, but this is a breaking change that requires notice and explanation.

### Steps to Reproduce 
[gradle-repro.zip](https://github.com/gradle/gradle/files/11131765/gradle-repro.zip)

Run `./gradlew reproduce`.

### Your Environment
OpenJDK 17 on macOS

**Comment by lptr** [comment]
Thanks @shoaniki for the detailed report, this is now fixed and will be shipped in the upcoming 8.1-rc-3.
