### ISSUE TITLE
Toolchains: Support Environment Variables in Maven Toolchains Declarations

### ISSUE THREAD

**Issue by Okeanos** [gradle/gradle#24596]
With the introduction of Maven Toolchains based JDK detection in #19046 parsing the `toolchains.xml` to detect JDKs became possible. However, I recently noticed that one use case is not covered for now: `${env.var}` based declarations.

### Expected Behavior

Gradle should interpolate Maven `${env.var}` syntax in the `toolchains.xml` file and read the correct value from the environment.

### Current Behavior

Gradle interpretes all `jdkHome` contents as string literal and will try to parse `${env.var}` as is, without first checking what the intended value is.

### Context

Maven has supported this feature since [3.6.2](https://maven.apache.org/docs/3.6.2/release-notes.html) via [MNG-6665](https://issues.apache.org/jira/browse/MNG-6665) released on 2019-08-27.

Parsing the environment variables within the `toolchains.xml` file makes it easier to use the declarations file within CI/CD environments because a toolchain file such as displayed [here](https://github.com/B3Partners/kadaster-gds2/blob/b0cd5c392bc1f48dec11c83c828254a868264467/.github/ubuntu-toolchains.xml) (quickest public real world example I could find; even if no longer actively in use) would be sufficient for Maven & Gradle.

I would be willing to contribute the necessary changes.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by jbartok** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
