### ISSUE TITLE
Variant selection failure report: Better error message for GRADLE_PLUGIN_API_VERSION_ATTRIBUTE

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#24609]
### Expected Behavior
```
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not resolve dependency example:example:1.0.0.
          Gradle plugin requires version 8.0 or higher, this build uses Gradle version 7.5.1.
```

### Current Behavior
The massive wall of text contains all attributes.
```
- Incompatible because this component declares a component, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.2' and the consumer needed a component, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.1'
```
### Context
Although the variant error report has got some improvements in the last releases, it is still confusing due to the many details.
If Gradle wants to promote GRADLE_PLUGIN_API_VERSION_ATTRIBUTE, as min supported Gradle version and as well for multi-version Gradle plugin variants, a better error message is needed for users consuming Gradle plugins with this attribute.

Related #24608

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

***

Relates to: #12126
