### ISSUE TITLE
Azure blob storage as target for build cache

### ISSUE THREAD

**Issue by czietsman** [gradle/gradle#2461]
I tried to use Azure blob storage as target for a remote build cache. It seems to fail because the HttpBuildCacheService does not set content length.

### Expected Behavior
It should be possible to configure the HttpBuildCache to provide the Content-Length. This may require the currently implementation to write out to a temporary location and then upload to the provided HTTP url, since the current interface does not provide the content length at a convenient time.

### Current Behavior
The current implementation is not providing the Content-Length and the Azure blob storage service seem to require it and does not support Transfer-Encoding: chunked.

### Context

Our build server is running in Azure, therefore it makes sense to use the facilities provided by Azure to host the build cache. The same would apply for builds hosted in AWS.

**Comment by bmuschko** [comment]
@lptr @wolfs Could you have a look at this issue?

**Comment by lptr** [comment]
PR to fix: #2497.

**Comment by lptr** [comment]
PR merged, content length is going to be sent by the HTTP build cache in 4.1.
