### ISSUE TITLE
Non-interactive mode for `gradle init`

### ISSUE THREAD

**Issue by victorteokw** [gradle/gradle#24624]
Cannot run commands without interactive. I'm making a tool which can generate some code with gradle. I want it to run without prompts for user inputs.

### Expected Behavior
Expect something like this: `gradle init --non-interactive`

### Current Behavior
Cannot specify this option.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

There is a way to do this, but you need to provide all the options (see [here](https://docs.gradle.org/current/userguide/build_init_plugin.html#sec:what_to_set_up)).
But please be aware of this:
* https://github.com/gradle/gradle/issues/23918

**Comment by victorteokw** [comment]
Hi @jbartok, this is not asking for how to use gradle, but this is a missing feature. I searched your source code and found there isn't some command line flag argument I can input for some promptings. This issue exists because so few people write tools to generate projects with gradle. I'm not trying to pass `--no-incubating` or `--incubating=false`. Even the incubating one, these things are so simple while it's still not fixed.

**Comment by eskatos** [comment]
Do you mean that you would like Gradle to have a new flag to disable any user interaction and fail if one is required?

**Comment by victorteokw** [comment]
Hi @eskatos yes

**Comment by eskatos** [comment]
Thanks, this clarifies it.

**Comment by melix** [comment]
I had a similar need, in order to convert a Maven build into a Gradle one automatically. Unfortunately, there is no way for example to say "yes I want to convert" without interaction, so I ended up implementing my own converter.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

**Comment by janbodnar** [comment]
This would be a great addition to Gradle. However, not like `gradle init --non-interactive`, this would be very long awkward I would suggest to keep `gradle init` for interactive usage; any other syntax would be automatically non-interactive, aka classic. For instance `gradle -p application -l Groovy -b Groovy -j 17 -n com.zetcode.FirstApp`.

Rationale: 

- The majority of command-line apps are classic, non-interactive. Including scaffolding apps such as Micronaut `mn` tool or Symfony `bin/console` tool. (They create app structure among other tasks.) This is so common that I was quite surprised that Gradle does not have it. 

- Having non-interative syntax allows us to run Gradle project initializations in scripts. While corner cases, they still exist. 

- Classic usage is faster and more effective. 
- It is better in documentation. Seeing `$ gradle --project application --lang Groovy` is more clear than saying run gradle init and then select this and then that. Command line apps have both long options when clarity is preferred (--lang Groovy) and short equivalents for efficiency (-l Groovy). 
When option is not selected, the default is chosen. 

The JavaScript `npm` manager has the `-y` option which stands for yes to all default options. This creates the app structure quickly in one go. While it is quirky, you can see this option used a lot in text and video tutorials. It simply saves time.

**Comment by agarnier-dt** [comment]
If I understand the issue correctly, in the meanwhile `gradle init <<< /dev/null` seems to do the job.
