### ISSUE TITLE
Support using the gradle lock file as the source of truth when generating pom.xml

### ISSUE THREAD

**Issue by Spitfire1900** [gradle/gradle#24639]
Publishing version ranges in a pom.xml that is referenced by consumers is an anti-pattern. When using version range specifiers and the dependency locking feature generated pom.xml files reference the version range specified in the build.gradle.

In order to not break reproducible builds for consumers on my library I need to publish a static version in the pom.xml even if I specify a version range in the build.gradle.

### Expected Behavior

When running a generatePomFileForPubNamePublication task provide a `useLockFile true` property flag to use the gradle lockfile as the source of truth for which versions of dependencies to include in the generated pom.xml rather than the version range qualifier specified in build.gradle .

### Current Behavior

When using dependency locking with a version range specified in the build.gradle file running the generatePomFileForPubNamePublication task will use the version range included in the build.gradle file.

### Context

As a library maintainer for internal use applications I am unable to adopt version range specifiers and dependency locking in my gradle project unless all of my consumers adopt dependency locking also; otherwise their builds are not reproducible.

**Comment by rpalcolea** [comment]
Have you looked at [Publishing Resolved Dependencies](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies)?

Something like:

```groovy
publishing {
    publications {
        mavenJava(MavenPublication) {
            versionMapping {
                 allVariants {
                     fromResolutionResult()
                }
            }
        }
    }
}
```

should work

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

**Comment by Spitfire1900** [comment]
Thank you very much @rpalcolea.
