### ISSUE TITLE
incorrect .modules file without `files[]` section in published artifact

### ISSUE THREAD

**Issue by mikita-herasiutsin** [gradle/gradle#24644]
### Expected Behavior

The published artifact should have the correct .module file with `files[]` section and path to generated JAR

### Current Behavior

The issue is that generated artifact in maven repository .m2 (both local and artifactory) doesn't have `files[]` section in .module file (.m2\repository\...\dependency\X.X.X\{artifact name}.module) in a published artifact. Artifact is successfully checked by Gradle during the build, but it is absent on the classpath as JAR location is missing in .module file. Disabling the generation of .module file fixes an issue as the pom file is correct.

### Context
The idea is to publish generated OpenApi artifact and then use it in another project. Also, this publishable logic is located in another Gradle plugin and provides such functionality in the target project (buildSrc in the example below)

### Steps to Reproduce 
An example GitHub project https://github.com/mikita-herasiutsin/spike-variant-publish
Reproducing steps:
1. .`/gradlew publishToMavenLocal`. OpenApi will generate JAR from client-app\src\main\resources\api.yml and then publish it locally
2. `./gradlew build`. Build fails as it can't reference class from generated jar client-app\src\main\kotlin\org\spike\TestAppKt.kt
3. It can be fixed just by disabling the generation of .module file buildSrc\src\main\kotlin\com\spike\publish\Utils.kt:49

### Your Environment

It fails on both Windows and Linux environments

**Comment by melix** [comment]
Gradle module metadata will not properly handle the [`artifact` notation that you use](https://github.com/mikita-herasiutsin/spike-variant-publish/blob/main/buildSrc/src/main/kotlin/com/spike/publish/Utils.kt#L77) because it cannot associate it to any variant. This way of adding artifacts only works for pure Maven publications.

Instead, you must attach the artifacts to an _outgoing_ configuration. This looks close to [what you have here](https://github.com/mikita-herasiutsin/spike-variant-publish/blob/main/buildSrc/src/main/kotlin/com/spike/publish/Utils.kt#L57-L70) except that you **must not** use an existing configuration like `implementation` here. You must create an outgoing configuration, like:

```kotlin
val elements = configurations.create("myVariantElements") {
     isCanBeConsumed = true // outgoing configuration
     isCanBeResolved = false
     attributes {
        // set your attributes here
     }
    outgoing.artifact(myTask) // this is where you attach the artifact
}
```

**Comment by mikita-herasiutsin** [comment]
> Gradle module metadata will not properly handle the [`artifact` notation that you use](https://github.com/mikita-herasiutsin/spike-variant-publish/blob/main/buildSrc/src/main/kotlin/com/spike/publish/Utils.kt#L77) because it cannot associate it to any variant. This way of adding artifacts only works for pure Maven publications.
> 
> Instead, you must attach the artifacts to an _outgoing_ configuration. This looks close to [what you have here](https://github.com/mikita-herasiutsin/spike-variant-publish/blob/main/buildSrc/src/main/kotlin/com/spike/publish/Utils.kt#L57-L70) except that you **must not** use an existing configuration like `implementation` here. You must create an outgoing configuration, like:
> 
> ```kotlin
> val elements = configurations.create("myVariantElements") {
>      isCanBeConsumed = true // outgoing configuration
>      isCanBeResolved = false
>      attributes {
>         // set your attributes here
>      }
>     outgoing.artifact(myTask) // this is where you attach the artifact
> }
> ```

Thanks a lot! You saved a lot of time :) It works now in that branch https://github.com/mikita-herasiutsin/spike-variant-publish/tree/fix/correct_configuration_for_publishing
I guess ticket can be closed
