### ISSUE TITLE
Error when "cordova run android" in command line

### ISSUE THREAD

**Issue by nrsabrinaaa** [gradle/gradle#24659]
FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\USER\AndroidStudioProjects\CordovaProjectsApp\platforms\android\settings.gradle'

* What went wrong:
Could not compile settings file 'C:\Users\USER\AndroidStudioProjects\CordovaProjectsApp\platforms\android\settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 61

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
