### ISSUE TITLE
Running an asynchronous child task using JavaExec causes No current build operation error

### ISSUE THREAD

**Issue by vijayasaradhi-danda** [gradle/gradle#24653]
### Context
We have a plugin that starts [H2](https://www.h2database.com/html/main.html) server in the background. In other projects, we rely on this plugin to start H2. Then, liquibase changesets are applied to populate data and start the application.

To start H2 in background, we use JavaExec API along with CompletableFuture class. In Exec method (see StartH2Task.java from github repo), we asynchronously start h2 by calling the main class of org.h2.tools.Server.     

### Expected Behavior
When ./gradlew startH2 is called, the following must happen.
1. H2 must be started
2. Print H2 started information to stdout
3. H2 server must be running even after gradle task is completed

To test this we have testTasks_with_user_configured_db in H2PluginTest.java. 

### Current Behavior
When the testTasks_with_user_configured_db test is run, main gradle thread waits for ever. 

### Our analysis

On Debugging it we found that DefaultBuildOperationProgressEventEmitter throws an IllegalStateException for the asynchronous startH2 task and results in No current build operation.  This happens as current.getId returns null in emitForCurrent method.

### Steps to Reproduce 

1. Checkout our plugin code at https://github.com/umich-michr/h2-plugin
2. Run the H2PluginTest.testTasks_with_user_configured_db test in gradle version 7.3.0 using (./gradlew test --tests '*H2PluginTest.testTasks_with_user_configured_db'). It will pass
3. Upgrade gradle wrapper to version 8.0.2
4. The test hangs forever. (New thread spawned to start H2 server throws IllegalStateException)

Did not use https://github.com/gradle/gradle-issue-reproducer as it might be redundant to check in whole plugin code.  Please let me know if you think it is necessary, I will do the needful. 

### Your Environment

Java 11 with Gradle 7.3.1 works. Java 11 with Gradle 8.0.2 fails

**Comment by jvandort** [comment]
Gradle currently does not have adequate support for running background tasks. See https://github.com/gradle/gradle/issues/1367

In general, the solution of calling `super.exec` from a non-Gradle-managed thread is unsupported. 

Right now, I think the best solution for you would be to start the H2 process yourself, without using Gradle infrastructure to do so (`java.lang.ProcessBuilder`). A `BuildService` is likely the best place to implement a long-lived background process which should live across several task executions.
