### ISSUE TITLE
Classpath dependencies in `buildscript` block of settings.gradle.kts do not invalidate the configuration cache

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#24677]
In my `settings.gradle.kts` I add dependencies with `classpath(flieTree(myJarFolder))`. The variable `myJarFolder` is can change even when the source code of `settings.gradle.kts` stays the same because `myJarFolder` is assigned based on which files exist on my machine. 

### Expected Behavior

If `myJarFolder` changes, then the classpath used for the gradle execution changes. Therefore, I expect the configuration cache to be invalidated.

### Current Behavior

The configuration cache is reused.

### Context

I am building my own gradle plugins, and I load them locally by using `classpath(flieTree(myJarFolder))`. When I rebuild the gradle plugin, `myJarFolder` is automatically assigned to the latest build.

If I may change the behavior of a task that is configured in my gradle plugin, and then rebuild the plugin, I expect that gradle will see that its classpath has changed and invalidate the configuration cache.

I have a stable workaround, but it is not ideal. Every time I rebuild my gradle plugin, I write a random number to a file called `cache-invalidator.txt`. Then I read this file inside of a value source provider during my build.

The reason that this is not ideal is because it adds complexity and also because it doesn't take advantage of hashing to determine if files stayed the same, unless I manually hash myself.

### Steps to Reproduce 

1. Create a folder called "gradle-plugin-builds".
2. Build a gradle plugin to a folder called "gradle-plugin-builds/1".
3. In a new project, have something like the following inside of `settings.gradle.kts`:
```kotlin
buildscript{
    dependencies{
        classpath(fileTree(File("gradle-plugin-builds").listFiles().sortBy{it.toInt()}.last()))
    }
}
```
4. Run the gradle project that consumes the plugin, make sure the configuration cache is stored
5. Modify the plugin and build it to "gradle-plugin-builds/2"
6. Run the gradle project that consumes the plugin again. You would expect it to respect the modified plugin, but instead it re-uses the configuration cache

### Your Environment
Gradle Version 8.0.2

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by 6hundreds** [comment]
@mgroth0 Could you attach a reproducer?
