### ISSUE TITLE
Type use annotations are not present in an incremental processor when existing class file is used

### ISSUE THREAD

**Issue by Fanael** [gradle/gradle#24688]
When using an incremental annotation processor, if compile avoidance kicks in and an already-compiled class file is used for processing, type use annotations appear to be missing from annotation language model nodes, even if they're present in the class file.

I don't know if class files can be used for processing in any scenario other than compile avoidance; if they can be, it's possible the same issue applies there as well.

### Steps to Reproduce 

1. Build the `classes` target of [gradle-testcase.tar.gz](https://github.com/gradle/gradle/files/11180664/gradle-testcase.tar.gz).
2. Touch the source of either method in `bar.Main` (for example, by adding a new empty line) and build `classes` again.

Since the class `$0` generated from `bar.Victim` depends on `bar.Main`, `Victim` will be reprocessed.

### Current Behavior

The annotation processor gets angry, because it cannot see `@TypeUseAnnotation` on the type of Victim's field.

### Expected Behavior

The type use annotation is presented to the processor, as it is present in the class file of `Victim`:
```
  private java.lang.Object x;
    descriptor: Ljava/lang/Object;
    flags: (0x0002) ACC_PRIVATE
    RuntimeInvisibleTypeAnnotations:
      0: #12(): FIELD
        foo.TypeUseAnnotation
```

### Context

In my production code, the type use annotation happens to be `@org.checkerframework.checker.nullness.qual.Nullable`, with completely different code being generated depending on its presence or absence on any given type.

### Your Environment

Gradle 8.0.2, OpenJDK 17.0.6 and 19.0.1, Debian sid

**Comment by Fanael** [comment]
Might be related to [JDK-8225377](https://bugs.openjdk.org/browse/JDK-8225377)?

**Comment by asodja** [comment]
Yes, this looks like a compiler bug unfortunately, so it has to be fixed in the JDK. For that specific case you can workaround it by using `ElementType.FIELD` for `@TypeUseAnnotation`, e.g.:
```diff
 import java.lang.annotation.Target;
 
 @Retention(RetentionPolicy.CLASS)
-@Target(ElementType.TYPE_USE)
+@Target(ElementType.FIELD)
 public @interface TypeUseAnnotation {
 }
 ```
 
 and then you read annotations from `variableElement`, e.g.:
 ```diff
  VariableElement variableElement = (VariableElement) element;
  Messager messager = processingEnv.getMessager();
-TypeMirror type = variableElement.asType();
-messager.printMessage(Diagnostic.Kind.NOTE, type.toString(), element);
-if (variableElement.asType().getAnnotationMirrors().isEmpty()) {
+if (variableElement.getAnnotationMirrors().isEmpty()) {
      messager.printMessage(Diagnostic.Kind.ERROR, "barf", element);
+} else {
+    messager.printMessage(Diagnostic.Kind.NOTE, "ok: " + variableElement.getAnnotationMirrors(), element);
  }
```

Of course if you want to use `@TypeUseAnnotation` annotation anywhere else, you might not be that lucky.

Alternative is, that you mark you annotation processor as non-incremental. Which basically means that the project using the annotation processor will be fully recompiled every time. :/

**Comment by Fanael** [comment]
> For that specific case you can workaround it by using `ElementType.FIELD` for `@TypeUseAnnotation`
> […]
> Of course if you want to use `@TypeUseAnnotation` annotation anywhere else, you might not be that lucky.

Unfortunately, I cannot, because as I mentioned in the original message, the actual annotation is one of Checker Framework's, so it's not under under my control; even if it was, it still needs to be a type use annotation, because I need to be able to use it on type arguments.

I currently work around the problem by detecting if the processed element comes from a class file and simply failing if that's the case. Being occasionally forced to do full rebuilds beats doing full rebuilds every time, and changes that actually trigger this issue aren't very common in practice.

**Comment by asodja** [comment]
That is smart. Note: Gradle 7.6 and 8.x have incremental compilation after a failure, so might need to disable that behaviour. You can do that by setting `options.incrementalAfterFailure.set(false)` for the JavaCompile task.

**Comment by ljacomet** [comment]
Closing as this cannot be fixed in Gradle itself.
