### ISSUE TITLE
`outputs.upToDateWhen` should take effect no matter where in the task definition it's set

### ISSUE THREAD

**Issue by noel-yap** [gradle/gradle#2468]
Depending on where in the task definition `outputs.upToDateWhen` is defined, it will either take effect or not.

### Expected Behavior

In a declarative language, it shouldn't matter where in the task definition `outputs.upToDateWhen` is defined.

```
task updateChangelog {
  final outputFile = file("CHANGELOG.md")

  doLast {
    final changelog = outputFile.text

    outputFile.text = changelog.readLines().collect {
      it.toString().replaceAll(/^(#+ +)(\[Unreleased\])/, { array ->
        final prefix = array[1]
        final unreleased = array[2]

        "${prefix}${unreleased}\n\n${prefix}[${version}]"
      })
    }.join('\n')
  }

  outputs.file outputFile
  outputs.upToDateWhen {
    !unreleasedChangesExist(outputFile as String[])
  }
}
```

and:

```
task updateChangelog {
  final outputFile = file("CHANGELOG.md")

  outputs.file outputFile
  outputs.upToDateWhen {
    !unreleasedChangesExist(outputFile as String[])
  }

  doLast {
    final changelog = outputFile.text

    outputFile.text = changelog.readLines().collect {
      it.toString().replaceAll(/^(#+ +)(\[Unreleased\])/, { array ->
        final prefix = array[1]
        final unreleased = array[2]

        "${prefix}${unreleased}\n\n${prefix}[${version}]"
      })
    }.join('\n')
  }
}
```

should work identically.

### Current Behavior

In the first task definition, the result of `outputs.upToDateWhen` is ignored.

### Context

Not abiding by the `outputs.upToDateWhen` setting breaks the task's idempotent guarantee.

### Steps to Reproduce (for bugs)
1. Define a task with `doLast` then `outputs.upToDateWhen { false }`. Be sure `doLast` is before the `outputs.upToDateWhen` setting
2. Execute the task (be sure to use `--no-daemon` due to some other bug)
3. Task should be `UP-TO-DATE` but it's not
4. Swap the order of `doLast` and `outputs.upToDateWhen` definitions
5. Execute the task (be sure to use `--no-daemon` due to some other bug)
6. Task is now `UP-TO-DATE`

**Comment by big-guy** [comment]
I think your reproduction steps might be slightly off.  `outputs.upToDateWhen { false }` means "task is never up to date" so in step 3, the task should not be `UP-TO-DATE`.  And again in step 6, the task cannot be `UP-TO-DATE`.

**Comment by big-guy** [comment]
Based on what I said in https://github.com/gradle/gradle/issues/2467#issuecomment-315184626, I'm going to close this as a misunderstanding.
