### ISSUE TITLE
Result of `outputs.upToDateWhen` ignored when using `--no-daemon`

### ISSUE THREAD

**Issue by noel-yap** [gradle/gradle#2469]
The result of `outputs.upToDateWhen` is ignored when using the `--no-daemon` option even though `--no-daemon` is required to have the daemon refresh its cache.

### Expected Behavior

The result of `outputs.upToDateWhen` should be used regardless of the use of `--no-daemon`.

### Current Behavior

When changing the implementation of `outputs.upToDateWhen`, the task needs to be executed twice; once with `--no-daemon` then another time without `--no-daemon`. Doing this, though, breaks the idempotent guarantee of the task.

**Comment by big-guy** [comment]
Based on what I said in https://github.com/gradle/gradle/issues/2467#issuecomment-315184626, I'm going to close this as a misunderstanding.
