### ISSUE TITLE
`project(String)` method and others in gradle dsl should have `@Nonnull` or equivalent

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#2470]
Pasting a link to this issue here because it may require a change in the gradle API not the kotlin DSL:

https://github.com/gradle/kotlin-dsl/issues/420

**Comment by lptr** [comment]
We're close to merging #2441, then we can have `@Nonnull`, too.

**Comment by bamboo** [comment]
A PR with `@Nonnull` for `org.gradle.api.Project` is coming soon: 1e47c8d53b99a14fe3adc859a4d42ab9aca61a17

**Comment by lptr** [comment]
#2441 is merged, standard nullability annotations from `javax.annotations` are going to be available in Gradle 4.1.

**Comment by JLLeitschuh** [comment]
Lovely!

**Comment by bmuschko** [comment]
@lptr Given that your PR has been merged can we close this issue and put 4.1-rc1 as milestone?

**Comment by bamboo** [comment]
@bmuschko that PR is about `@Nullable` not `@Nonnull`.

**Comment by bmuschko** [comment]
@bamboo @lptr OK, thanks. Can you provide a little bit more background information on this issue here? What still needs to happen before we can close this issue? I think I referenced the wrong change. I meant this one: https://github.com/gradle/gradle/commit/1e47c8d53b99a14fe3adc859a4d42ab9aca61a17.

**Comment by bamboo** [comment]
@bmuschko we need to annotate `org.gradle.api.Project` members in a way that Kotlin and IntelliJ IDEA can understand that `org.gradle.api.Project` members such as `project(String)` always return non-null values. We're still discussing how to best achieve that in #2477.

**Comment by JLLeitschuh** [comment]
This got resolved in 4.1 right?

**Comment by bamboo** [comment]
Not yet, @JLLeitschuh. I'm planning to send a PR next week.

**Comment by bamboo** [comment]
Resolved in #2477.
