### ISSUE TITLE
Intercept getters (and setters) in Groovy closures

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#24716]
Groovy creates a different signature for getters in closures, e.g.:
```
tasks.register("myCheckstyle", Checkstyle) {
      maxErrors = 2
      int currentMaxErrors = maxErrors // <- getter call here
      assert currentMaxErrors == 2
}
```

We currently don't intercept that. Lets improve our logic and fix that.

**Comment by h0tk3y** [comment]
Progress in https://github.com/gradle/gradle/pull/24949

**Comment by h0tk3y** [comment]
Done in #24949.
