### ISSUE TITLE
Support upgrading method references for both getters and setters

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#24713]
E.g.:
`methodTakingConsumer(checkstyle::setMaxErrors)`
`methodTakingSupplier(checkstyle::getMaxErrors)`

We should write some integration tests first.

**Comment by asodja** [comment]
It seems upgrades of references doesn't work. One example is upgrade of JavaApplication.getApplicationName() that is used in Spring boot:
https://github.com/spring-projects/spring-boot/blob/de4b2d679f1821a3f0059264abb02da5c4edac6c/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/main/java/org/springframework/boot/gradle/plugin/ApplicationPluginAction.java#L93C3-L93C21

We get error like:
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.gradle.api.plugins.JavaApplication.getApplicationName()'
```
when running SpringBootPluginSmokeTest

**Comment by mlopatkin** [comment]
This also affects CC instrumentation, e.g. you can use `System::getenv` to bypass environment variable read detection. So it fits in the configuration cache adoption track.
