### ISSUE TITLE
Write a design how property (setter/getter) overrides should behave with property upgrades

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#24714]
Right now we don't have any design or idea of how overrides with getters and setters should behave. 

Let's write something down and then discuss with the team.

**Comment by lptr** [comment]
Spec: https://docs.google.com/document/d/1yVu9p5y81JNcEuJ6KAXQr7OEPNHnB9KKbScAemf0H_M/

**Comment by lptr** [comment]
Spec has been reviewed.
