### ISSUE TITLE
Dependency Management from OCI registries

### ISSUE THREAD

**Issue by geowalrus4gh** [gradle/gradle#24725]
### Expected Behavior

Gradle should resolve dependencies (OCI artifacts containing jars) from OCI registry. Then compose and create application container image and push to OCI registry like Harbor. 

### Current Behavior

We are currently using

1. Maven repository for application dependent module jars as artifacts
2. Harbor for application jar as container image(which assembles module jars from maven repo)

Using gradle, dependencies are loaded from maven repo, composed and create container image and then push to OCI registry like Harbor. 

### Context

Idea is to

1. Develop and push application module jars to OCI registry as artifact images.
2. A web application jar which assembles dependent (as given in .gradle or pom.xml file) jars from the OCI registry.
3. Push web application jar to OCI registry as container image.

This idea is to avoid maven repo and use Harbor OCI as only repository.

Can this idea implemented using gradle ?

**Comment by jbartok** [comment]
We have no plans for doing this in Gradle core. Instead, it's something that should be provided via plugins.

Actually, there are already plugins related to OCI: https://plugins.gradle.org/search?term=oci

**Comment by bdellegrazie** [comment]
Sadly none of those plugins address the requested issue - which is the ability to retrieve JAR dependencies from OCI registries.
