### ISSUE TITLE
Allow custom buildSrc project location

### ISSUE THREAD

**Issue by ericparton** [gradle/gradle#2472]
It would be nice to have the ability to change the location of the buildSrc directory. Currently, it must be located directly beneath the project root directory. This revives an old issue that didn't survive the migration to the new issue tracker:

https://issues.gradle.org/browse/GRADLE-2816

### Expected Behavior
The location of the buildSrc directory can be set to any directory relative to the project root directory. Maybe via an option in settings.gradle?

### Current Behavior
The buildSrc directory must be located directly within the project root directory.

### Context
This would allow more flexibility when it comes to project directory organization, especially in large projects where tooling related directories are grouped into one or more specific sub directories.

**Comment by big-guy** [comment]
We probably won't do this exactly, but instead phase out the specialness of `buildSrc`.

You can already sort of achieve what you want by using [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html).  `buildSrc` is a lot like a built-in included build that's automatically wired into your build script classpath.

If you do something like...

settings.gradle:
```
includeBuild 'gradle-plugins'
```

build.gradle:
```
buildscript {
   dependencies {
      classpath 'com.example:gradle-plugins:0'
   }
}
```

gradle-plugins/build.gradle:
```
group = 'com.example'
version = '1.0'
// normal Java/Groovy/whatever plugins
```

This will look like `buildSrc` in many ways.

**Comment by oehme** [comment]
Closing since this will be superseded by composite builds as Sterling suggested.

**Comment by ericparton** [comment]
@big-guy This is more syntactic sugar than anything else, but is there a way to include a dependency in the classpath of the buildscripts of each subproject without having to repeat the declaration in the buildscript blocks?

**Comment by oehme** [comment]
@ericparton You should only do it once, in the root project. That'll make it visible to all subprojects.

**Comment by ericparton** [comment]
Perfect, thanks!

**Comment by tmtron** [comment]
I am now using the CompositeBuild instead of `buildSrc` (as suggested by @big-guy  [here](https://github.com/gradle/gradle/issues/2472#issuecomment-315376378)) and it works fine.

One downside, that I see is that I can now not directly jump to the source code anymore:  
e.g. in Android Studio (and I guess also in IntelliJ) I can CTRL+click a class in `build.gradle` file and it will open this class in the Editor.

Any ideas how to reactivate this?  
e.g. maybe we just need to add the source files of the composite build to the jar, or something like this

**Comment by oehme** [comment]
This sounds like a limitation in Android Studio or IntelliJ. Maybe @vladsoroka can help out on this one? Is there some special handling of `buildSrc` that doesn't apply to other included builds?

**Comment by vladsoroka** [comment]
@oehme you're right, IntelliJ tries to discover implicit `buildSrc` project and it seems the logic doesn't work for included builds. I've created the issue at [https://youtrack.jetbrains.com/issue/IDEA-189037](https://youtrack.jetbrains.com/issue/IDEA-189037)

@tmtron As a workaround you can try to add the `buildSrc` to the included builds `settings.gradle` explicitly:
`include 'buildSrc'`

**Comment by tmtron** [comment]
> As a workaround you can try to add the buildSrc to the included builds settings.gradle explicitly:
> include 'buildSrc'

@vladsoroka: Can you please clarify what you mean? I don't have a `buildSrc` anymore. I've renamed it to e.g. `gradle-plugins` and use this in the `settings.gradle` file like so:
`includeBuild 'gradle-plugins'`

Maybe you suggest that I should specify it twice? Like this:
```
includeBuild 'gradle-plugins'
include 'gradle-plugins'
```
But this fails with an error:
`Included build 'gradle-plugins' collides with subproject of the same name.`

**Comment by vladsoroka** [comment]
@tmtron no, I meant, if your included builds also have `buildSrc`, IntelliJ will not create the IDE modules for such buildSrc gradle projects (like it does for the `buildSrc` of your main project).

> I don't have a `buildSrc` anymore.
I see, that's another issue with the included builds IntelliJ support. It seems the project dependencies from included builds can not be resolved in the context of the build scripts. I've created related issue at [https://youtrack.jetbrains.com/issue/IDEA-189333](https://youtrack.jetbrains.com/issue/IDEA-189333)

**Comment by oehme** [comment]
Thanks a lot @vladsoroka !

**Comment by joaocsousa** [comment]
I know this has been closed for a while now, by I managed to achieve this by creating a symlink. See https://stackoverflow.com/a/59928986/1003528

**Comment by matejdro** [comment]
includeBuild has a configuration duration downside: https://github.com/gradle/gradle/issues/8174
symlink does not work with IntelliJ: https://youtrack.jetbrains.com/issue/IDEA-329756/Importing-symlinked-Gradle-included-build-fails

So none of the workarounds work here 😐
