### ISSUE TITLE
`CommandLineArgumentProvider` documentation eagerly calls `get()` on provider

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#24726]
### Issue type

Wrong or misleading information

### Problem description

`CommandLineArgumentProvider` documentation creates a file provider and then immediately calls `get()` like `layout.buildDirectory.dir('dist').get()`. The sample code should instead pass the provider in to the `CommandLineArgumentProvider` and call .get() when used.

Here is the sample:
https://docs.gradle.org/current/userguide/caching_java_projects.html#dealing_with_file_paths

### Page with the problem

https://docs.gradle.org/current/userguide/caching_java_projects.html#dealing_with_file_paths

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
