### ISSUE TITLE
ResolutionStrategy.failOnDynamicVersions() is not included in DSL reference

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#24733]
### Issue type

Missing information

### Problem description

`ResolutionStrategy.failOnDynamicVersions()` is mentioned in the [User Guide](https://docs.gradle.org/current/userguide/resolution_strategy_tuning.html#reproducible-resolution) as well as the [Javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolutionStrategy.html), but is missing from the [DSL reference for this type](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html).

It appears that `failOnChangingModules` and `failOnNonReproducibleResolution` are also both missing from the reference.

### Page with the problem

https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by big-guy** [comment]
This was done in #25305
