### ISSUE TITLE
Javadoc error, referring to application plugin task

### ISSUE THREAD

**Issue by washtubs** [gradle/gradle#2475]
According to https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java#L51, the application plugin adds a task called `createStartScripts`. But it's actually just called `startScripts`. Or am I just very confused?

**Comment by bmuschko** [comment]
You are correct. Fixed: https://github.com/gradle/gradle/commit/b6f1a5140276cb5494fa9def70fb506b52d9f4ad
