### ISSUE TITLE
Document best practices for setting conventions on Gradle-provided Properties in tasks

### ISSUE THREAD

**Issue by EdricChan03** [gradle/gradle#24773]
### Issue type

Missing information

### Problem description

While the [Lazy Configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html) docs has a [section on applying a convention to a property](https://docs.gradle.org/current/userguide/lazy_configuration.html#applying_conventions), it doesn't show an example of hooking it up with one that would be defined as a Gradle-managed property. (Adapting the first example:)

```kt
abstract class Greeting : DefaultTask() {
    @get:Input
    @get:Optional
    abstract val greeting: Property<String> // Say you want to provide a default value for greeting if not specified

    @Internal
    val message: Provider<String> = greeting.map { it + " from Gradle" } 

    init {
        greeting.convention("Hello") // Here? This would show a "Accessing non-final property greeting in constructor" warning though, but seems to work perfectly fine
    }

    @TaskAction
    fun printMessage() {
        greeting.convention("Hello") // Or here?
        logger.quiet(message.get())
    }
}
```

### Context (optional)

I was trying to figure out the ideal method of setting a default value for a Gradle-managed property without having to resort to creating it manually.

Trying to find for usages on GitHub seems to mostly (I've only done a [single search for ".convention" that are in Kotlin and aren't forks](https://github.com/search?q=.convention+lang%3Akotlin+NOT+is%3Afork&type=code), and only viewed the first 20 results or so) yield results that use the `objects.property(...).convention(...)` approach

### Page with the problem

https://docs.gradle.org/current/userguide/lazy_configuration.html#applying_conventions

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
