### ISSUE TITLE
Adding tools.jar in the jdk in java 9 and newer breaks the gradle build process

### ISSUE THREAD

**Issue by naschwin** [gradle/gradle#24777]
### Expected Behavior

Gradle should be built with no errors

### Current Behavior

```
Downloading file:/D:/Java/Spring/demo2/demo/gradle/wrapper/gradle-8.0.2-bin.zip
...........10%............20%............30%............40%............50%............60%...........70%............80%............90%............100%

Welcome to Gradle 8.0.2!

Here are the highlights of this release:
 - Improvements to the Kotlin DSL
 - Fine-grained parallelism from the first build with configuration cache
 - Configurable Gradle user home cache cleanup

For more details see https://docs.gradle.org/8.0.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not create service of type BuildLifecycleController using ServicesProvider.createBuildLifecycleController().
   > Could not create service of type GradleInternal using ServicesProvider.createGradleModel().
      > Could not create an instance of type org.gradle.invocation.DefaultGradle.
         > Could not configure services using GradleScopeCompileServices.configure().

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

### Context (optional)

Way back, had a different error related to intelliJ, which required tools.jar, fixed that, then I had forgotten about, but a few days back had a job requirement for gradle, but had the above error, could not, for the love of god figure it out what went wrong. 
Found out that it's tools.jar that was causing the problem. Now i know manually adding the jar itself was a big no no, but even if someone did do that, please provide a proper error message

### Steps to Reproduce

Download jdk
Set JAVA_HOME, etc, etc
Add tools.jar in jdk's bin folder
Create a spring boot gradle project from spring initializer
Run the thing
Gradle will fail to build

### Gradle version

8.0.1

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

*** 

The benefit of fixing this for future versions would be very limited anyways. Please just don't use altered JDKs.

**Comment by naschwin** [comment]
Wouldn't an appropriate error message for that error be more responsible
