### ISSUE TITLE
Update and unify copyright years 

### ISSUE THREAD

**Issue by bmscomp** [gradle/gradle#24774]
### Issue type

Wrong or misleading information

### Problem description

Copyright year is set sometime to 2015-2022 and sometimes only 2015, I think this needs to be updated and unified in all files and scripts, a script that can unify automatically those values can be created, some files contains older year for example 2012 

### Page with the problem

generated scripts and copyright test in java classes

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #24751

Please add your use case and 👍 to that issue.

**Comment by bmscomp** [comment]
Thank you for the comment and remembering me that the topic is already discussed on issues
