### ISSUE TITLE
Gradle 8.1 configure freeCompilerArgs for Kotlin in buildSrc breaks build with unhelpful errors

### ISSUE THREAD

**Issue by apatrida** [gradle/gradle#24788]
### Expected Behavior

Expect code that works with Gradle 8.0.1 to work with Gradle 8.1 in `buildSrc` directory.

### Current Behavior

`buildSrc/build.gradel.kts` code:

```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_19)
        javaParameters.set(true)
        languageVersion.set(KotlinVersion.KOTLIN_1_8)
        freeCompilerArgs.set(listOf("-Xcontext-receivers"))
    }
}
```

or

```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.apply {
        jvmTarget = JavaVersion.VERSION_19.toString()
        languageVersion = KotlinVersion.KOTLIN_1_8.version
        javaParameters = true
        freeCompilerArgs = listOf("-Xcontext-receivers")
    }
}
```

works in previous Gradle, but in 8.1 causes all build scripts that are kotlin-script based to not have any Gradle context any more.

```
No script runtime was found in the classpath: class 'kotlin.script.templates.standard.ScriptTemplateWithArgs' not found. Please add kotlin-script-runtime.jar to the module dependencies.
```

then every line is an error of the script.

Cannot see another way to set this, i.e.

```
compilerOptions.compiler("kotlin").args(listOf("-Xcontext-receivers"))
```

is error as well.  Also  changing `KotlinCompile` to `KotlinJvmCompile` is no change.

The `freeCompilerArgs` works fine for plugins under `buildSrc/src/main/kotlin` but not in the `build.gradle.kts` 

Solution is to use

```
freeCompilerArgs.add("-Xcontext-receivers")
``` 

and not `set(...)` but nothing guides you there at all.  Just an explosion of nothing working anymore for the `buildSrc` code.

### Context (optional)

A regression not mentioned in release notes related to Kotlin and compiler arguments.

### Steps to Reproduce

see description above

### Gradle version

8.1

**Comment by apatrida** [comment]
note: kotlin docs show this as `add(...)` not `set(...)` but the set version worked prior and not sure where that code came from, if was an online example, or was from just using code completion.

**Comment by eskatos** [comment]
Thank you for the report Jayson,

This is due to us fixing
* https://github.com/gradle/gradle/issues/23955

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by ThiemoFischer** [comment]
I also experience this problem when trying to upgrade to 8.1 and using the kotlin-dsl plugin. https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
is this the same issue?
