### ISSUE TITLE
Gradle Plugin Portal ignores Gradle module metadata

### ISSUE THREAD

**Issue by Toldry** [gradle/gradle#24784]
### Expected Behavior

When using a plugin whose source repository is `gradlePluginPortal()`, then Gradle should use that plugin's Gradle module metadata.

### Current Behavior

Using `gradlePluginPortal()` ignores Gradle module metadata.

### Context (optional)

The [Gradle Documentation](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources) states:

> When searching for a module in a repository, Gradle, by default, checks for [supported metadata file formats](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:supported-metadata-formats) in that repository.[...] Gradle also looks for .module (Gradle module metadata) files.

However this is not true for `gradlePluginPortal()`, which ignores Gradle module metadata, as exemplified by [this bug](https://github.com/gradle/test-retry-gradle-plugin/issues/179).

### Steps to Reproduce

https://github.com/gradle/test-retry-gradle-plugin/issues/179

### Gradle version

8.1

**Comment by ljacomet** [comment]
The Gradle Plugin Portal does not ignore Gradle Module Metadata. It however behaves as other repositories:
* If the metadata source is not specified, it will load the `.pom` first.
* If that `.pom` has a redirect to the `.module`, then it will attempt to load the `.module`

In the case of the `test-retry-plugin`, the `.pom` does not have the redirect - see [this file](https://plugins.gradle.org/m2/org/gradle/test-retry-gradle-plugin/1.3.0/test-retry-gradle-plugin-1.3.0.pom).
However for a plugin properly published with GMM support, the redirect is present - see [this other file](https://plugins.gradle.org/m2/dev/jacomet/gradle/plugins/logging-capabilities/0.11.0/logging-capabilities-0.11.0.pom).

Note that the publication setup of the `test-retry-plugin` is broken and not GMM compatible and thus it is a good thing that the redirect is missing.

**Comment by Toldry** [comment]
@ljacomet  Thank you for the explanation.

Followup question: How do I configure my custom repository to behave the same as `gradlePluginPortal`? 

Should I simply omit the `metadataSources` section?
```
maven {
  url 'https://my.company.repository.org/m2'
}
```

OR

Should I only specify `mavenPom()` and omit `gradleMetadata()` ?

```
maven {
  url 'https://my.company.repository.org/m2'
  metadataSources {
      mavenPom()
  }
}
```

OR

some other solution?

**Comment by ljacomet** [comment]
This should be documented [here](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources)

But if you want the default behavior, then simply do not specify anything.
