### ISSUE TITLE
Gradle worker exits with exit value 1

### ISSUE THREAD

**Issue by sriram-musiri** [gradle/gradle#24791]
### Expected Behavior

Gradle worker continues running

### Current Behavior

Gradle is unable to connect to server. Logs from the failing task:

```
org.gradle.internal.remote.internal.ConnectException: Could not connect to server [bceb1740-8e37-408c-b5f4-fe7e66a54344 port:46203, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1]. |  
-- | --
  | at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67) |  
  | at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36) |  
  | at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:123) |  
  | at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71) |  
  | at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69) |  
  | at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74) |  
  | Caused by: java.net.ConnectException: Connection refused |  
  | at java.base/sun.nio.ch.Net.pollConnect(Native Method) |  
  | at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672) |  
  | at java.base/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1141) |  
  | at java.base/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1183) |  
  | at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:98) |  
  | at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81) |  
  | at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54) |  
  | ... 5 more
```

Elsewhere in the build scan, we see the error message:
```
Process 'Gradle Test Executor 23' finished with non-zero exit value 1
```

Build scans attached.
[fxb7zrpre7aha.scandump.zip](https://github.com/gradle/gradle/files/11256492/fxb7zrpre7aha.scandump.zip)

[f6vil4xv5blio.scandump.zip](https://github.com/gradle/gradle/files/11256500/f6vil4xv5blio.scandump.zip)

### Context (optional)

We see this failure several times a week in our CI.

### Steps to Reproduce

The failure doesn't seem attached to a particular task and has no deterministic repro we could find.

### Gradle version

Gradle 6.9.2-airbnb-2-20220607070000+0000,Gradle Enterprise plugin 3.10.3

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to efficiently track down and fix your problem. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.  

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
