### ISSUE TITLE
Gradle worker daemon crashes with exit code 143

### ISSUE THREAD

**Issue by sriram-musiri** [gradle/gradle#24790]
### Expected Behavior

The worker daemon doesn't crash

### Current Behavior

We see `Process 'Gradle Worker Daemon 53' finished with non-zero exit value 143` in the logs. The build fails. Scan dump is attached.

[2r6wse55drh2u.scandump.zip](https://github.com/gradle/gradle/files/11256465/2r6wse55drh2u.scandump.zip)

### Context (optional)

We see this error 2-3 times a week in our CI.

### Steps to Reproduce

The same job/task has succeeded several times; there's no clear repro.

### Gradle version

 6.9.2-airbnb-2-20220607070000+0000

**Comment by jbartok** [comment]
FYI, @ghale commented:

> Exit code 143 is signal 15 (143 - 128 = 15) which is a SIGTERM.  This is virtually always because some outside process is killing the daemon for some reason.  If this is happening on Linux, it's likely the OOM killer stopping the daemon because physical memory is low.

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to efficiently track down and fix your problem. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.  

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
