### ISSUE TITLE
gradle publishPlugins: success but the plugin is not visible on plugins.gradle.org

### ISSUE THREAD

**Issue by etienne-sf** [gradle/gradle#24805]
### Expected Behavior

I published a new release (2.0RC1c) of the [com.graphql_java_generator.graphql-gradle-plugin](https://plugins.gradle.org/plugin/com.graphql_java_generator.graphql-gradle-plugin) plugin.

I expected the new version to be available quickly after this publishing, like all the previous releases I did.

Note: I tried to publish several 'versions' of the 2.0RC1, as I thought the issue was on my PC. I hope I didn't pollute the gradle plugin portal.

### Current Behavior

When I executed `gradlew publishPlugins`, I got an output that finished by

```
> Task :publishPlugins
Publishing plugin com.graphql_java_generator.graphql-gradle-plugin version 2.0RC1c
Publishing artifact build/libs/graphql-gradle-plugin-2.0RC1c-javadoc.jar
Publishing artifact build/publications/pluginMaven/pom-default.xml
Publishing artifact build/libs/graphql-gradle-plugin-2.0RC1c.jar
Publishing artifact build/libs/graphql-gradle-plugin-2.0RC1c-sources.jar
Publishing artifact build/publications/pluginMaven/module.json
Activating plugin com.graphql_java_generator.graphql-gradle-plugin version 2.0RC1c

BUILD SUCCESSFUL in 8s
10 actionable tasks: 7 executed, 3 up-to-date
```

But:
* The 2.0RC1c release is not visible here: [com.graphql_java_generator.graphql-gradle-plugin](https://plugins.gradle.org/plugin/com.graphql_java_generator.graphql-gradle-plugin)
* If I try to republish the plugins, I got this error: 

```
> Task :publishPlugins FAILED
Publishing plugin com.graphql_java_generator.graphql-gradle-plugin version 2.0RC1c

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'com.graphql_java_generator.graphql-gradle-plugin', version: '2.0RC1c' exists already. It was created: 2023-04-18 20:00:31.939
```

### Steps to Reproduce

Trying to publish the plugin, [available here](https://github.com/graphql-java-generator/graphql-gradle-plugin-project.git).
The issue is on the `master_2.x` branch

The main files are:
* [build.gradle](https://github.com/graphql-java-generator/graphql-gradle-plugin-project/blob/master_2.x/graphql-gradle-plugin/build.gradle)
* [gradle.properties](https://github.com/graphql-java-generator/graphql-gradle-plugin-project/blob/master_2.x/graphql-gradle-plugin/gradle.properties)
* [settings.gradle](https://github.com/graphql-java-generator/graphql-gradle-plugin-project/blob/master_2.x/graphql-gradle-plugin/settings.gradle)

### Gradle version

7.6.1

### Build scan URL (optional)

https://scans.gradle.com/s/gztdifqik7t66

### Your Environment (optional)

I'm using:
* jdk17
* Gradle wrapper 6.3.1
* Windows
* I tried with and without a proxy, on two different computers

**Comment by ov7a** [comment]
@etienne-sf Sorry that you're having trouble with this!

Your plugin was flagged for manual review. I tried to reach you via the email specified on GitHub and Gradle Plugin Portal, but your email provider rejected my email with `550 unknown user`. Please, contact Plugin Portal Support <plugin-portal-support@gradle.com> for further details.
