### ISSUE TITLE
Gradle TAPI: ability to provide custom data for test failure events

### ISSUE THREAD

**Issue by HackerMadCat** [gradle/gradle#24801]
### Expected Behavior

We want providing custom exception data from Gradle to IDEA. I see there several solutions:
1. Gradle TAPI finds and serializes all public data in exception and puts it in dictionary by x-path.
2. Gradle TAPI allows to set up custom test event provider, where we can modify and add created test event on Gradle side.

Before using [org.gradle.tooling.events.ProgressListener](https://github.com/gradle/gradle/blob/7d8f92c58181e3d8ed5004fbfe582340d1d30311/subprojects/tooling-api/src/main/java/org/gradle/tooling/events/ProgressListener.java#L26) we created own test events and transferred it thought Gradle output by [IJTestEventLogger](https://github.com/JetBrains/intellij-community/blob/2005b258a3e52daef9bc7a45aa412e77730debb1/plugins/gradle/resources/org/jetbrains/plugins/gradle/IJTestLogger.groovy#L11).

### Context

IDEA has custom assertion exception: [com.intellij.rt.execution.junit.FileComparisonFailure](https://github.com/JetBrains/intellij-community/blob/2005b258a3e52daef9bc7a45aa412e77730debb1/java/java-runtime/src/com/intellij/rt/execution/junit/FileComparisonFailure.java#L8). This exception represent file comparison error which holds paths for expected and actual files. IDEA provides ability for edit expected data in diff view. Which shows when user clicks on link `<click to see difference>` in tests view.

Test Launcher API creates and transfers test events from Gradle process to IDEA. This API supports only popular comparison exception like TestNG, Junit and AssertJ. But we need collect and transfer data for our `FileComparisonFailure`. This exception is important for us and for our plugin-writers.

**Comment by donat** [comment]
It might make sense to declare the additional data publicly, for example in [opentest4j](https://github.com/ota4j-team/opentest4j/). 

Besides file comparison failures, are there any additional custom exception types you need to support that have custom data?

**Comment by HackerMadCat** [comment]
> It might make sense to declare the additional data publicly, for example in [opentest4j](https://github.com/ota4j-team/opentest4j/).

We will try providing file comparison failure into opentest4j.

**Comment by HackerMadCat** [comment]
https://github.com/ota4j-team/opentest4j/issues/73

**Comment by donat** [comment]
@HackerMadCat Can you please verify that https://github.com/gradle/gradle/pull/25382 would fix this issue? Are there other cases we need to consider adding in OT4J?

**Comment by HackerMadCat** [comment]
Hello! Currently https://github.com/gradle/gradle/pull/25382 isn't fix our issue. Because:
1. New data in test failure details don't contain paths to expected and actual files.
2. Our tests based on JUnit 3 and 4. We can provide `opentest4j` for our tests, but (as I can see) your fix doesn't support this case.

**Comment by donat** [comment]
@HackerMadCat: @hegyibalint completely reworked #25382. The changes should fix both of your concerns. Can you please take another look?

**Comment by hegyibalint** [comment]
Reopening, after automatic closure, as we are unsure if this was fixed.
@HackerMadCat PTAL if you have some time.

**Comment by HackerMadCat** [comment]
We found a way to fix this issue locally in the file comparison case.

Unfortunately in general this issue is still here. BUT currently we haven't practice cases when it can be needed.
I guess you can close this issue due to our original issue will be fixed by https://github.com/gradle/gradle/pull/25382

**Comment by hegyibalint** [comment]
Closing, thanks for the extra info.

**Comment by donat** [comment]
Superseded by #25792.
