### ISSUE TITLE
signature verification not importing keys for dependencies in buildSrc

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#24822]
### Expected Behavior

Running `./gradlew --write-verification-metadata pgp,sha256 --export-keys --dry-run :help` should export the keys for dependencies used in the build, even if those dependencies are declared in buildSrc

### Current Behavior

Currently I'm observing a case where `./gradlew --write-verification-metadata pgp,sha256 --export-keys --dry-run :help` isn't exporting keys for dependencies used in buildSrc

### Context (optional)

This makes it more difficult for AndroidX to establish trust for the artifacts that we use. (Most recently this is https://github.com/spdx/spdx-gradle-plugin)

### Steps to Reproduce

Download https://github.com/mathjeff/gradle-samples/tree/master/signature-verification-cannot-find-key and run `./test.sh`

### Gradle version

8.0

### Build scan URL (optional)

(original failure, not simpler repro case above)
https://ge.androidx.dev/s/lyqpxzp2ioeh4/failure

**Comment by ljacomet** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

***

It would be interesting to know if this worked in Gradle 7.6.

And maybe invoking `buildSrc:build` explicitly in Gradle 8+ helps.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

While this issue is reproducible with 8.0 and 7.6, it no longer triggers an error in 8.1 - there were some updates in this area.

Please update your Gradle distribution.

**Comment by mathjeff** [comment]
Great - thanks!
