### ISSUE TITLE
Remove Gradle-internal top of the configuration cache problem stacktrace

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#24854]
### Expected Behavior

The configuration cache problem should have a stacktrace with the problematic code on top, e.g. coming from an offending task code.

### Current Behavior (optional)

The stack trace has a long trace of Gradle internals dispatching the problem:

![image](https://user-images.githubusercontent.com/7620037/233605375-7c09ed94-8be0-46db-9d14-293f70a97a56.png)

### Context

Having too many internal frames makes debugging of configuration cache problems harder.

**Comment by adammurdoch** [comment]
When we implement this, we should reuse the existing logic in the deprecation logging that tries to do the same thing (and improve it if necessary) so that this logic is shared.

**Comment by bamboo** [comment]
The way I was thinking, the filtering would be done at the UI side (report logic) so it could be toggled on/off (for detailed visualization) and allow for custom regex filters.
