### ISSUE TITLE
How to solve Cannot snapshot output property 'outputDirectory'.

### ISSUE THREAD

**Issue by Roa-chen** [gradle/gradle#24853]
### Expected Behavior

I'm trying to build a react-native project created by default (so no problems normally), but when I use npx react-native run-android, I get the following error. When I run a program that I had already run before, since the outputs file exists, it does not cause any errors.

### Current Behavior

`C:\Users\arsen\OneDrive\Documents\ReactNativeProjects\test>npx react-native run-android
info JS server already running.
info Installing the app...
> Task :app:checkDebugAarMetadata FAILED
9 actionable tasks: 9 executed

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A build operation failed.
      Cannot snapshot output property 'outputDirectory'.
   > Cannot snapshot output property 'outputDirectory'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A build operation failed.
      Cannot snapshot output property 'outputDirectory'.
   > Cannot snapshot output property 'outputDirectory'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s

    at makeError (C:\Users\arsen\OneDrive\Documents\ReactNativeProjects\test\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\arsen\OneDrive\Documents\ReactNativeProjects\test\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\arsen\OneDrive\Documents\ReactNativeProjects\test\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\Users\arsen\OneDrive\Documents\ReactNativeProjects\test\node_modules\@react-native-community\cli\build\index.js:108:9)
info Run CLI with --verbose flag for more details.`

### Steps to Reproduce

Just build the project and this error appears in my case. I guess it's rare since I can't find any documentation about it.

### Gradle version

7.5.1

### Your Environment (optional)

I use react-native with an empty project (just the welcome script).

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the Android Gradle Plugin, which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug

***

Alternatively, you might need to reach out to the NPX community instead.

**Comment by safoun10** [comment]
facing exactly the same issue 😐

**Comment by Felkng** [comment]
Hello, there. I was facing this issue too. After several hours of searching I discovered that this error is caused due some corrupted cache files in gradle root directory. So I just deleted the C:\Users\<YOUR_USER>\.gradle\caches folder and sync my react-native project in Android Studio again and rebuild the project, after that my problem was solved.

**Comment by Satyaaam** [comment]
I am getting this error
* What went wrong:
org.gradle.internal.execution.OutputSnapshotter$OutputFileSnapshottingException: Cannot snapshot output property 'sources'.
> Cannot snapshot output property 'sources'.

please help me with this

**Comment by Rblemer** [comment]
Delete the `.gradle` folder from the project root and then do `File > Invalidates Caches...`

This worked in my project!
