### ISSUE TITLE
NoSuchMethodError after update to Gradle 8.1/8.1.1

### ISSUE THREAD

**Issue by veita** [gradle/gradle#24873]
### Expected Behavior

Gradle update should not break builds.

### Current Behavior

After update from Gradle 7.6 to Gradle 8.1 or 8.1.1 build fails with the following error message.

```
Execution failed for task ':modules:foo:test'. java.lang.NoSuchMethodError:
'void org.gradle.api.internal.tasks.testing.junit.JUnitTestFramework.<init>
(org.gradle.api.tasks.testing.Test, org.gradle.api.internal.tasks.testing.filter.DefaultTestFilter)'
```

Unfortunately the error message is not very helpful. It lacks the build script path and line number as well as the full stack trace.

The only changes made are
```
 modified:   gradle/wrapper/gradle-wrapper.jar
 modified:   gradle/wrapper/gradle-wrapper.properties
 modified:   gradlew
```

### Steps to Reproduce

The project contains 66 `build.gradle` files with over 6000 lines of code that run on a TeamCity server.
Given the above failure message I could not narrow down the cause of the problem in order to create a simple project that may reproduce it.

The issue seems to be related to this [constructor](https://github.com/gradle/gradle/blob/20d8fe53d9aa8753b9bd724c5c812b43d5fd5b64/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestFramework.java#L45) which does  not exist in 8.1.x.

### Gradle version

8.1.1

### Your Environment (optional)

The build runs on TeamCity.

**Comment by veita** [comment]
Our devops team enabled logging of stack traces `--stacktrace` what gave the hint to the cause of the error:
```
failure report] Caused by: java.lang.NoSuchMethodError: 'void org.gradle.api.internal.tasks.testing.junit.JUnitTestFramework.<init>(org.gradle.api.tasks.testing.Test, org.gradle.api.internal.tasks.testing.filter.DefaultTestFilter)'
[13:12:08]W:		 [Gradle failure report] 	at org.gradle.testretry.internal.executer.framework.JunitTestFrameworkStrategy.createRetrying(JunitTestFrameworkStrategy.java:31)
[13:12:08]W:		 [Gradle failure report] 	at org.gradle.testretry.internal.executer.RetryTestExecuter.execute(RetryTestExecuter.java:123)
[13:12:08]W:		 [Gradle failure report] 	at org.gradle.testretry.internal.executer.RetryTestExecuter.execute(RetryTestExecuter.java:38)
[13:12:08]W:		 [Gradle failure report] 	at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:464)
[13:12:08]W:		 [Gradle failure report] 	at org.gradle.api.tasks.testing.Test.executeTests(Test.java:692)
```

Updating the Test Retry Gradle plugin to the latest version solved the issue.

It would be nice if Gradle would report detailed information about errors by default.

**Comment by dhruvtyagi** [comment]
@veita can you please share how you changed the test retry gradle plugin? And also, which version did you update it to?
