### ISSUE TITLE
No support for Java8 parameter name reflection

### ISSUE THREAD

**Issue by baynezy** [gradle/gradle#2487]
### Expected Behaviour
The Groovy compiler (groovyc) [supports](http://docs.groovy-lang.org/docs/next/html/documentation/tools-groovyc.html) `-pa` or `--parameters` which enables parameter name reflection. I can see no way to pass this parameter from gradle

### Current Behaviour
See above

### Context
I am trying to enable parameter name reflection and need to be able to pass these compilation arguments to enable it.

**Comment by bmuschko** [comment]
I had a brief look at the code. The flag doesn't seem to be supported right now. Would you be interested in providing a pull request? I believe we'd want to add it to [`GroovyCompileOptions`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.GroovyCompileOptions.html).

**Comment by dejan2609** [comment]
@bmuschko it seems that Groovy version upgrade (to 2.5) is a prerequisite:
- https://issues.apache.org/jira/browse/GROOVY-7423 **_Access to Method parameter names at runtime_**
- http://docs.groovy-lang.org/docs/groovy-2.4.11/html/documentation/tools-groovyc.html 
- http://docs.groovy-lang.org/docs/groovy-2.5.0-beta-1/html/documentation/tools-groovyc.html
