### ISSUE TITLE
Race condition between stopping and notifying operation completion listener

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#24887]
### Expected Behavior

A build service may also be registered as a operation completion listener via `BuildEventsListenerRegistry.onTaskCompletion()`. Such listener should either be invoked even after the service is stopped (causing it to be reinstantiated), or not invoked at all. 

### Current Behavior

Right now, there is a race condition in which it is possible that a build service will be stopped while some other thread is trying to invoke `OperationCompletionListener.onFinish()` on the build service. The result is a NullPointerException like this:

 ```
java.lang.NullPointerException: Cannot invoke "org.gradle.internal.Try.get()" because "this.instance" is null	
at org.gradle.api.services.internal.RegisteredBuildServiceProvider.getInstance(RegisteredBuildServiceProvider.java:121)	
at org.gradle.api.services.internal.RegisteredBuildServiceProvider.calculateOwnValue(RegisteredBuildServiceProvider.java:111)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:73)	
at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:93)	
at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:261)	
at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$ForwardingBuildEventConsumer.handle(DefaultBuildEventsListenerRegistry.java:238)	
at org.gradle.internal.build.event.DefaultBuildEventsListenerRegistry$AbstractListener.run(DefaultBuildEventsListenerRegistry.java:180)	
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)	
at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)	
 ```
 

### Context (optional)

This method is not thread safe:

```
    private T getInstance() {
        listener.beforeGet(this);
        synchronized (this) {
            if (instance == null) {
                instance = instantiate();
            }
        }
        return instance.get();
    }
```

as we attempt to access a field that is mutated from different threads without synchronization.

Fixing the race condition so the NPE no longer happens would be easy, but it is unclear whether we would want the listener to be invoked while the service is stopped, have the service be reinstantiated, the listener not to be invoked at all, or something else. 

### Steps to Reproduce

This was spotted in Gradle's own builds:

https://ge.gradle.org/s/wiwsly5z2uwty/tests/:configuration-cache:embeddedIntegTest/org.gradle.configurationcache.ConfigurationCacheBuildServiceIntegrationTest/build%20service%20registered%20as%20listener%20in%20an%20included%20build%20with%20no%20work%20is%20not%20restored?expanded-stacktrace=WyIwIiwiMC0xLTIiXQ&top-execution=1

I was only able to reproduce it by tweaking the flaky test to run a thousand times (failed on attempt #684 for me, YMMV) :

```
---
Index: subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
===================================================================
diff --git a/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy b/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy
--- a/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy	(revision 9b74f67f363d2e5a25289f027afa222b869d645c)
+++ b/subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheBuildServiceIntegrationTest.groovy	(date 1682341864787)
@@ -43,6 +43,7 @@
 import org.gradle.tooling.events.task.TaskFinishEvent
 import spock.lang.IgnoreIf
 import spock.lang.Issue
+import spock.lang.Unroll
 
 import javax.inject.Inject
 import java.util.concurrent.atomic.AtomicInteger
@@ -718,6 +719,7 @@
     }
 
     @Issue("https://github.com/gradle/gradle/issues/23700")
+    @Unroll("test repeated #i time")
     def "build service registered as listener in an included build with no work is not restored"() {
         def onFinishMessage = "You won't see me!"
         withListenerBuildServicePlugin onFinishMessage
@@ -756,5 +758,8 @@
         then:
         configurationCache.assertStateLoaded()
         outputDoesNotContain onFinishMessage
+
+        where:
+        i << (1..1000)
     }
 }

``` 

Not completely sure the use of included builds is required to recreate the issue.

### Gradle version

8.1

### Build scan URL (optional)

https://ge.gradle.org/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.gradle.configurationcache.ConfigurationCacheBuildServiceIntegrationTest&tests.test=build%20service%20registered%20as%20listener%20in%20an%20included%20build%20with%20no%20work%20is%20not%20restored

**Comment by bamboo** [comment]
Another example is accessing a build service from a `buildScan.buildFinished` callback.

**Comment by abstratt** [comment]
Additional testing made the issue trivially reproducible (by running it multiple times) in the presence of included builds, but could not reproduce it without involving included builds.

**Comment by jamiesanson** [comment]
Is there a workaround for this issue?

**Comment by abstratt** [comment]
Not that I know of.

**Comment by pierrickrouxel** [comment]
I encounter this issue too with included builds.
