### ISSUE TITLE
Could not create parent directory for lock file C:\Program Files\Java\wrapper\dists\gradle-7.4-bin\c0gwcg53nkjbqw7r0h0umtfvt\gradle-7.4-bin.zip.lck

### ISSUE THREAD

**Issue by JulianHSC** [gradle/gradle#24897]
### Expected Behavior

I should be able to save my android studio files multiple times without this error message.

### Current Behavior

Error originally started in android studio eel version. Projects that are saved more than once have this error for unknown reasons.

### Context (optional)

Unable to save, continue work, modify and create .apk for practice purpose.

### Steps to Reproduce

I don't have to show you anything. Just download a copy of android eel or flamingo. Create a simple basic hello world. See https://issuetracker.google.com/issues/279270917?pli=1. You can get a copy of my project from this link.

### Gradle version

Not sure

### Build scan URL (optional)

NA/not known

### Your Environment (optional)

Android Studio Flamingo | 2022.2.1 on win 11.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

It's weird that you are using the path "C:\Program Files\Java\...", which is not the standard [Gradle user-home path](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home).
Are you sure you have write permissions in that path?

**Comment by mayuelantianyu** [comment]
Bro，have you solved this problem ? I also met this .

**Comment by JulianHSC** [comment]
Hello @mayuelantianyu, not yet. I'm still working on it. My problem might be from react native. It didn't suddenly appear in AS.

**Comment by mayuelantianyu** [comment]
All right. Thanks for your answer.🤜🤛

**Comment by mayuelantianyu** [comment]
> Hello @mayuelantianyu, not yet. I'm still working on it. My problem might be from react native. It didn't suddenly appear in AS.
> Update: I found a youtube video that shows the same thing as https://reactnative.dev/docs/environment-setup?guide=native. Whilst I cannot get my virtual running yet, lots of PATH settings in the computer was missing. Depending on what system you're using e.g. Mac, Linux, Windows, you have to check what you need to do. My error messages have changed to "Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details"

All right. Thanks for your answer.🤜🤛

**Comment by JulianHSC** [comment]
Hello @mayuelantianyu, I managed to solve my problems. At current time, I need to connect my physical phone to the android studio took and later yesterday, I even managed to connect the phone and install the react native wirelessly. I hope you solve your case. 
Note: I'll be unsubscribing from all emails as I no longer need to post anymore questions.

**Comment by PistonShot** [comment]
go to settings , under build, execution & deployment section, under build tools , go to gradle and change your gradle user home path

it should be referring to ${USER}/.gradle. In windows should be , C:\Users\(username)\.gradle. It will default to your java sdk if you have configured open jdk in your environment before u downloaded and setup android studio

 i would recommend to remove java in your pc environment (the jdk you configured on your own) to avoid any similar conflict  BEFORE you install android studio, such that it jdk will default to an android studio downloaded version path in future.
