### ISSUE TITLE
Gradle 4.0 not starting bootRun Error: Could not find or load main class

### ISSUE THREAD

**Issue by DayaMoon** [gradle/gradle#2489]
gradle (gradlew) bootRun works with Gradle 2.9, Gradle  3.5, but not starting with Gradle 4.0
OS Windows
### Expected Behavior
Gradle  2.9 or  Gradle 3.5

--------------- successfully  starting JVM --------------------
Starting process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe''. 
Working directory: 
C:\Users\one-user\Desktop\ABC\ABC-project Command: 
C:\Program Files\Java\jdk1.8.0_121\bin\java.exe 
	-cp C:\Users\one-user\Desktop\ABC\ABC-project\build\classes\main;C:\Users\one-user\Desktop\ABC\ABC-project\build\resources\main;C:\Users\one-user\Desktop\ABC\ABC-project\build\libs\ABC-project-pathing.jar 
	com.mycompany.Application
Successfully started process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe''

**The main class is under src/main/java**

### Current Behavior
`Starting process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe''. 
Working directory: 
C:\Users\one-user\Desktop\ABC\ABC-project Command: 
C:\Program Files\Java\jdk1.8.0_121\bin\java.exe 
	-cp C:\Users\one-user\Desktop\ABC\ABC-project\build\classes\main;C:\Users\one-user\Desktop\ABC\ABC-project\build\resources\main;C:\Users\one-user\Desktop\ABC\ABC-project\build\libs\ABC-project-pathing.jar 
	com.mycompany.Application
Successfully started process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe''

**Error: Could not find or load main class** com.mycompany.Application`

### Context

> OS Windows
> Java 8
> shell: CMD / git-bash
> The main class is under src/main/java
> Due to multiple  Jar dependencies we added a task to archive the classpath file. 
> See below archiveClasspath task

### Steps to Reproduce (for bugs)
In git-bash console on Windows OS 
`./gradlew wrapper --gradle-version 3.5`
`./gradlew  clean build bootRun`  // OK  the application starts, **bootRun depends on archiveClasspath** 

`./gradlew wrapper --gradle-version 4.0`
`./gradlew  clean build bootRun`  // FAIL to start  java.exe Error: Could not find or load main class 

### Your Environment
```
------------MANIFEST.MF-------------------------
`Manifest-Version: 1.0
Start-Class: com.mycompany.Application
Spring-Boot-Classes: WEB-INF/classes/
Spring-Boot-Lib: WEB-INF/lib/
Version: 1.0.0
Spring-Boot-Version: 1.5.3.RELEASE
Main-Class: org.springframework.boot.loader.WarLauncher`


---- fragment from build.gradle-------------------
springBoot {
    mainClass = "$theMainClass"
}
jar {
    baseName = projectName
    exclude("**/scss")
    exclude("**/bootstrap-select/*.scss")
    manifest {
        attributes 'Version': projectVersion,
                'Main-Class': "$theMainClass"
    }
}
war {
    baseName = projectName
    exclude("**/scss")
    exclude("**/bootstrap-select/*.scss")
    manifest {
        attributes 'Version': projectVersion,
                'Main-Class': "$theMainClass"
    }
}
bootRun {
    if (isWindowsOs()) {
        dependsOn 'archiveClasspath' // to fix Windows error=206, The filename or extension is too long
        doFirst {
            classpath = files("$buildDir/classes/main", "$buildDir/resources/main", archiveClasspath.archivePath)
        }
    }

}

task archiveClasspath(type: Jar) {
    dependsOn configurations.runtime
    appendix = 'pathing'
    doFirst {
        manifest {
            attributes "Class-Path": configurations.runtime.files.collect {
                it.toURL().toString().replaceFirst('/file:/+/', '/')
            }.join(' ')
        }
    }
}

```

**Comment by big-guy** [comment]
The output directories changed in Gradle 4.0:
https://docs.gradle.org/4.0/release-notes.html#location-of-classes-in-the-build-directory

Your build hardcodes the classpath to the old path:
>             classpath = files("$buildDir/classes/main", "$buildDir/resources/main", archiveClasspath.archivePath)

You should instead do something like:
>            classpath = files(sourceSets.main.output.files, archiveClasspath.archivePath)

**Comment by DayaMoon** [comment]
Thank you!
It worked!
