### ISSUE TITLE
Manual should contain a clear and exhaustive list for plugin and script types

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#24926]
### Issue type

Missing information

### Problem description

Starting with an example: the term "standalone script." We use it internally all the time, yet it shows up nowhere in our documentation. I have no idea what "standalone" is supposed to mean; I guess it's some legacy term we keep dragging around with us. 

Another example is "pre-compiled script plugin". This is not as bad; we do have a section on it in the user manual, but on page 1052 (out of 1350). 

The point I'm trying to get to is this: we should have summary pages in the manual, towards the beginning of it, which clearly list all the existing types of both scripts and plugins, with short definitions, and set the terminology straight from the get-go. 

### Page with the problem

https://docs.gradle.org/current/userguide/userguide.html

**Comment by vlsi** [comment]
See https://diataxis.fr/
Tutorials, how to guides, explanation and reference are documentation types that target different audience.

It is hard to agree that Gradle documentation should start with a 10 page reference that explains the terms.

On the other hand, adding a reference section to the documentation would help indeed.

**Comment by lkasso** [comment]
This was completed in 8.10: https://docs.gradle.org/current/userguide/custom_plugins.html
