### ISSUE TITLE
JVM Test Suite Plugin Kotlin sources can't reference Java sources

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#24920]
### Expected Behavior

If I register an integration test suite with the [JVM Test Suite Plugin](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html), and [configure both Kotlin and Java source directories in its source set](https://github.com/ianbrandt/gradle-jvm-test-suite-kotlin/blob/kotlin-dsl/build.gradle.kts#L22-L33), I would expect the Kotlin sources to be able to reference the Java sources. They can with the unit test suite and the main source set by default.

If this is user error, and it's just that further or different configuration is needed, perhaps this issue could stand as a request to document that with examples here: https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#configure_source_directories_of_a_test_suite.

### Current Behavior

I get a compilation error referencing Java sources from Kotlin sources.

An aside, IntelliJ does not show the compilation error in the editor. It only occurs when building with Gradle.

### Context (optional)

I'm trying to switch from the [Gradle TestSets Plugin](https://github.com/unbroken-dome/gradle-testsets-plugin) to the JVM Test Suite Plugin because the former is not currently compatible with Gradle 8 per unbroken-dome/gradle-testsets-plugin#131. I have legacy integration test fixtures written in Java that I want to reference from newer integration tests written in Kotlin. This works fine with the Gradle TestSets Plugin, and with unit test suites via the JVM Test Suite Plugin, but not with any other suites I create with the JVM Test Suite Plugin.

### Steps to Reproduce

Reproducer: https://github.com/ianbrandt/gradle-jvm-test-suite-kotlin/tree/kotlin-dsl.

Integration test suite source set configuration: https://github.com/ianbrandt/gradle-jvm-test-suite-kotlin/blob/kotlin-dsl/build.gradle.kts#L22-L33.

Kotlin integration test unsuccessfully referencing Java test fixture in same suite: https://github.com/ianbrandt/gradle-jvm-test-suite-kotlin/blob/kotlin-dsl/src/it/kotlin/KotlinIT.kt#L8.

Kotlin unit test successfully referencing Java test fixture in same suite: https://github.com/ianbrandt/gradle-jvm-test-suite-kotlin/blob/kotlin-dsl/src/test/kotlin/KotlinTest.kt#L8.

Kotlin main code successfully referencing Java main code: https://github.com/ianbrandt/gradle-jvm-test-suite-kotlin/blob/kotlin-dsl/src/main/kotlin/KotlinApp.kt#L2.

Compilation failure: https://github.com/ianbrandt/gradle-jvm-test-suite-kotlin/actions/runs/4810996487/jobs/8564402548#step:4:395.

### Gradle version

8.1.1

### Build scan URL (optional)

https://scans.gradle.com/s/dcpsim5p3rswm

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by ianbrandt** [comment]
@octylFractal, Thanks for the explanation. Compilation works with the change you outlined.

I filed #25000 as a feature request for higher-level DSL for this configuration.
