### ISSUE TITLE
Precompiled script plugins result in eagerly configure tasks

### ISSUE THREAD

**Issue by CharlieTap** [gradle/gradle#24931]
### Expected Behavior

Including builds containing precompiled script plugins using the kotlin-dsl results in 0 eagerly configured tasks.

### Current Behavior

Including builds containing precompiled script plugins using the kotlin-dsl results in 10 eagerly configured tasks.

Task types that were registered with the new API but were created anyways

class org.jetbrains.kotlin.gradle.tasks.KotlinCompile 2
class org.gradle.api.tasks.compile.JavaCompile 2
class org.gradle.api.tasks.bundling.Jar 1
class org.gradle.language.jvm.tasks.ProcessResources 1
class org.gradle.plugin.devel.tasks.PluginUnderTestMetadata 1
class org.gradle.api.tasks.testing.Test 1
class org.gradle.api.DefaultTask 1
class org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GenerateExternalPluginSpecBuilders 1
class org.jetbrains.kotlin.gradle.tasks.InspectClassesForMultiModuleIC 1
class org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GeneratePrecompiledScriptPluginAccessors 1
class org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.ExtractPrecompiledScriptPluginPlugins 1
class org.gradle.plugin.devel.tasks.GeneratePluginDescriptors 1
class org.gradle.api.tasks.Delete 1
class org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.CompilePrecompiledScriptPluginPlugins 1
class org.gradle.jvm.tasks.Jar 1
class org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GenerateScriptPluginAdapters 1

### Context (optional)

This is a follow up to a conversation with @Vampire  in the Kotlin Slack Gradle channel [here](https://kotlinlang.slack.com/archives/C19FD9681/p1682533908686959).

We're not sure if this is intentional, maybe precompiled script plugins are intended to hosted on a repository rather than being included builds. 

Interestingly I noticed you can never get the metric "Created during configuration" to 0 because Gradle eagerly creates a delete task for every project in the build also.

### Steps to Reproduce

https://github.com/CharlieTap/gradle-issue-repro-pcsp/actions/runs/4819906974

If you comment out the convention plugin application on the root project and rerun `gradle --scan help` you will see the number of tasks for "Created during configuration" drop by 10 on the scan. Similarly tasks like `class org.gradle.kotlin.dsl.provider.plugins.precompiled.tasks.GenerateScriptPluginAdapters` disappear from the output of the task.

If you take the config out of the precompiled script plugin and apply the versions plugin directly to the root project the number of tasks is unaffected which suggests the cause is the packaging the config in a precompiled script plugin.

### Gradle version

8.1.1

### Build scan URL (optional)

https://scans.gradle.com/s/oy2ea2bbtwdbc/performance/configuration

**Comment by Vampire** [comment]
The `Delete` task realization is tracked at #20864

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

Any task from a build that produce plugins consumed by the outer build will need to *run* before the outer build logic can be evaluated to configure the build. This is why these tasks are created, and run, even if you just run `:help`.
