### ISSUE TITLE
Convention annotation for Property values in Extensions?

### ISSUE THREAD

**Issue by TheSnoozer** [gradle/gradle#24947]
### Expected Behavior

Thank you for gradle and lazy properties!
I just had the thought that maybe a new "Convention" annotation would help reduce duplicated code and may make it clearer for plugin developers what default values are.

I guess what somewhat bugs me is that a plugin developers the actual defaults (convention) can be far away from the property in the extension.

Consider for example an interface extension where the convention is only set by the plugin:
```java
interface HelloWorldPluginExtension {
    Property<String> getGreeting();
}

public class HelloWorldPlugin implements Plugin<Project> {
    public void apply(Project project) {
        var extension = project.getExtensions().create(
                "helloWorld", HelloWorldPluginExtension.class);
        extension.getGreeting().convention("Hello World");
    }
}
```

one certainly can bring this a bit closer, by passing on the project to the extension:
```java
public class HelloWorldPluginExtension {
    Property<String> greeting;

    public HelloWorldPluginExtension(Project project) {
        greeting = project.getObjects().property(String.class).convention("Hello World");
    }
}

public class HelloWorldPlugin implements Plugin<Project> {
    public void apply(Project project) {
        var extension = project.getExtensions().create(
                "helloWorld", HelloWorldPluginExtension.class, project);
    }
}
```

With a large set of configuration options this can become messy really quickly. Especially when a project has various types of configurations (String, int, long, bool, ...) repeating the `project.getObjects().property(SomeObject.class)` feels painful.

Instead I'd propose a new Convention-Annotation that would work similar to the second example.
Roughtly I'd image that the second example could also be expressed as:

```java
public class HelloWorldPluginExtension {
    @Convention("Hello World")
    Property<String> greeting;

    // Is a constructor even needed? Why not make the extension an interface again? Open for suggestions and interpretation!
}

public class HelloWorldPlugin implements Plugin<Project> {
    public void apply(Project project) {
        var extension = project.getExtensions().create(
                "helloWorld", HelloWorldPluginExtension.class, project);
    }
}
```

if types are needed I guess it also would be ok to supply types `@Convention(String.class, "Hello World!")`, but this could get tricky for lists and files/directories. Ideally the `project` would be accessible in the convention since for directory properties one might often need the project (e.g. `project.getLayout().getProjectDirectory()....`).

Thank you for your time and consideration.

### Context

see above.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
@TheSnoozer Thanks for the suggestion. 

I think your first example (with the conventions in the plugin) is what we want to recommend for most use cases.

The annotation idea has come up before, but it has some issues:
1. The mental model we use is that conventions belong to the plugin. If there's an extension `Foo`, there can be multiple plugins with different conventions for the same property. Putting conventions directly into the extension would introduce another path for conventions that might be hard to explain.
2. The annotation is only convenient for things that can be known statically. Accessing project state is awkward and makes it easier to depend on unexpected things or invoke expensive calculations. 
3. We want to encourage plugin authors to structure their plugins into reusable chunks. If the extension also has conventions, there isn't a way for another plugin to reuse the "unconfigured" extension.  

In your second example, you could write:
```
public abstract class HelloWorldPluginExtension {
    public abstract Property<String> getGreeting();

    @Inject
    public HelloWorldPluginExtension() {
        getGreeting().convention("Hello World");
    }
}
```

This has some of the same problems as the annotation approach, but it avoids the need for injecting a `Project`.

**Comment by TheSnoozer** [comment]
Thank you for tacking the time to explain this in great detail! Also great thanks for your example where one would avoid the `project.getObjects().property(SomeObject.class)`. I'm not really sure if I can avoid a somewhat very long list of configurations. In the end I'm working on a project that has grown over years in the maven world and now finally have time to make it a thing under gradle...certainly I can keep multiple Extensions and your snippet in mind.

Since I read between the lines that you (or gradle) would rather avoid the extra complexity (which is what I somewhat expected) I'm going ahead and close this request since I don't think you want to add such annotations.

Thanks again for taking the time and thank you for the consideration.

Closing as "Won't fix / Won't do".

**Comment by TheSnoozer** [comment]
Thanks again for the suggestion!

Works great.

Perhaps if anyone else bumps over this:
The suggestion requires at least gradle 5.3.

A 5.1 fails with
```
* What went wrong:
A problem occurred evaluating root project
> Failed to apply plugin
   > Cannot create a proxy class for abstract class 'Extension'.
```
and a 5.2 and 5.2.1 fail with
```
* What went wrong:
A problem occurred evaluating root project
> Failed to apply plugin
   > Could not create an instance of type Extension.
      > Receiver class Extension_Decorated does not define or inherit an implementation of the resolved method 'abstract org.gradle.api.provider.Property getMessage()' of abstract class Extension.
```

Since the above also gets rid of the project one needs to find a replacement.
In my case all was available through the `ProjectLayout` which can be injected in the extension.

E.g.
```java
public abstract class HelloWorldPluginExtension {
    public abstract RegularFileProperty getHelloFile();

    @Inject
    public ProjectLayout getProjectLayout() {
        throw new IllegalStateException("Should have been injected!");
    }

    @Inject
    public HelloWorldPluginExtension() {
        getGenerateGitPropertiesFilename().convention(
            getProjectLayout().getBuildDirectory().file("hello.file"));
    }
}
```
