### ISSUE TITLE
Can't apply foojay-resolver-convention to the buildSrc project

### ISSUE THREAD

**Issue by roded** [gradle/gradle#24946]
### Expected Behavior

I should be able to apply the foojay-resolver-convention to both the root and buildSrc projects.

### Current Behavior

When utilizing toolchains in the buildSrc project, the foojay-resolver-convention plugin cannot be applied to the buildSrc project if it's already defined for the root project.

When specifying the plugin version, Gradle reports:

> Error resolving plugin [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.5.0']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.

When removing the plugin's version from the buildSrc's settings.gradle.kts, I suspect that behavior is non-deterministic in that it might work or fail as I've seen both happen in different environments. Can't prove this though.

### Context (optional)

Some more information here:

https://discuss.gradle.org/t/where-to-configure-precompiled-script-plugin-toolchain-repositories-and-toolchains/44880/12

### Steps to Reproduce

https://github.com/roded/gradle-buildsrc-toolchain

### Gradle version

7.6.1

**Comment by jbartok** [comment]
You must apply the plugin without a version in `buildSrc` settings.
However older IDEA or Android Studio integration could choke on that and if that's the case you need to add a buildscript classpath entry:

```kotlin
buildscript {
  dependencies {
    classpath("org.gradle.toolchains:foojay-resolver:0.5.0")
  }
}
```
