### ISSUE TITLE
S3 publishing fails for artifacts larger than 5GiB

### ISSUE THREAD

**Issue by judgeaxl** [gradle/gradle#2494]
When publishing artifacts to an S3-backed repository, the upload will fail if an individual artifact is larger than 5GiB.

The cause is that AWS S3 limits the file size to 5GiB when using the simple put object API, currently used in S3Client. The solution is to instead use the multi-part API, to transparently enable support for up to 5TiB files.

I've offered to implement multi-part support in this thread: https://groups.google.com/forum/#!topic/gradle-dev/auNi3fpg-f8

**Comment by bigdaz** [comment]
Hi @judgeaxl. Thanks for the offer to improve our S3 support, and apologies for being so unresponsive.

Regarding the comments you made in the email thread:

>  I need two settings, the size of each part, and the threshold at which it switches from simple put to multi-part. (I don't want to complicate the most common path, which should be files much smaller than 5GiB), Is there any practical place where I can put those? The most convenient, both for usage, and for testing, seem to be S3ConnectionProperties, but it feels somewhat misplaced.
> Since I'm skipping the configuration step for now, I'm just hard-coding something sensible; for instance make 50MiB chunks if the file is more than 100MiB. I suppose even if S3ConnectionProperties is the best place, it would later be configured on the repository level.

I think hard-coding some sensible defaults is the right approach. We are careful about adding configuration options unless there is a compelling use case for them.

> What's the best way to get some more information out of integration tests, both from console, and from IDEA? I get pretty much an assert from the integration test, but few or no details about the actual failures.

This depends on the integration test. If you use `./gradlew cleanIdea idea` to generate your IDEA project file, then you should be able to debug the integration tests directly without any additional configuration.

If that doesn't work for you, feel free to submit a PR with the code you have so far and we can provide more guidance.

(And you're right, the hardest part about this fix might be integration testing!)

**Comment by judgeaxl** [comment]
Just to keep this issue alive, I have this all working, and have been using it for quite some time. I just need to find a bit of spare time to prepare a pretty pull-request.
