### ISSUE TITLE
Unconsistent locks behaviour with variable platform versions

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#24955]
### Expected Behavior

Gradle should lock and try enforcing imported platforms versions using lockfiles.

### Current Behavior

We have a project where we use an imported platform (bom file) to suggest some dependencies versions. That version can be set through a project property. After creating the locks some developers reported that the locks stopped working if they happened to suggest a different (fixed) version of the bom. The result is gradle being unable to resolve the dependencies, and the resolution error is very confusing, like:
```
com.fasterxml.jackson:jackson-bom:2.14.2 FAILED
   Selection reasons:
      - By constraint: dependency was locked to version '2.14.2'
   Failures:
      - Could not resolve com.fasterxml.jackson:jackson-bom:{strictly 2.14.2}.
          - Cannot find a version of 'com.fasterxml.jackson:jackson-bom' that satisfies the version constraints:
               Dependency path ':platformlockstest:unspecified' --> 'com.fasterxml.jackson:jackson-bom:2.15.0'
               Constraint path ':platformlockstest:unspecified' --> 'com.fasterxml.jackson:jackson-bom:{strictly 2.14.2}' because of the following reason: dependency was locked to version '2.14.2'
               Dependency path ':platformlockstest:unspecified' --> 'com.fasterxml.jackson.core:jackson-core:2.14.2' (apiElements) --> 'com.fasterxml.jackson:jackson-bom:2.14.2'
```
where it seems that the bom got locked (from the `strictly`) but it somehow breaks. Instead, strangely, things seem to work out when you use a dynamic version. I.e. in the example above if you try to request the `2.+` bom resolution works correctly.

### Context (optional)

This was actually a misshaps by developers, who by mistake were requesting a different version of the bom during a test rebuild of the package. Yet they still expected things to work out correctly due to the lockfiles. Instead results were inconsistent and depending on the actual version passed through the build.

### Steps to Reproduce

consider this basic build:
```groovy
plugins {
    id('java-library')
}

repositories {
    mavenCentral()
}

dependencyLocking {
    lockAllConfigurations()
}

dependencies {
    implementation platform("com.fasterxml.jackson:jackson-bom:${project.findProperty('jacksonVersion')}")
    implementation 'com.fasterxml.jackson.core:jackson-core'
}
```
Create some lockfiles pretending you want version `2.14.2`:
```sh
./gradlew dependencies -PjacksonVersion=2.14.2 --write-locks
```
Then this works (versions picked from the locks):
```
./gradlew dependencies
```
this works too, forcing the version from the locks:
```
./gradlew dependencies -PjacksonVersion=2.+
```
this doesn't:
```
./gradlew dependencies -PjacksonVersion=2.15.0
```
And when you try getting more information about the failure:
```
./gradlew depIn --dependency jackson-bom -PjacksonVersion=2.15.0
```
you get something somehow cryptic:
```
> Task :dependencyInsight
com.fasterxml.jackson:jackson-bom:2.14.2 FAILED
   Selection reasons:
      - By constraint: dependency was locked to version '2.14.2'
   Failures:
      - Could not resolve com.fasterxml.jackson:jackson-bom:{strictly 2.14.2}.
          - Cannot find a version of 'com.fasterxml.jackson:jackson-bom' that satisfies the version constraints:
               Dependency path ':platformlockstest:unspecified' --> 'com.fasterxml.jackson:jackson-bom:2.15.0'
               Constraint path ':platformlockstest:unspecified' --> 'com.fasterxml.jackson:jackson-bom:{strictly 2.14.2}' because of the following reason: dependency was locked to version '2.14.2'
               Dependency path ':platformlockstest:unspecified' --> 'com.fasterxml.jackson.core:jackson-core:2.14.2' (apiElements) --> 'com.fasterxml.jackson:jackson-bom:2.14.2'
```
From which it seems that the constraint coming from the locks was not able to downgrade the dependency (but it somehow worked just fine when using `2.+`)

### Gradle version

7.6.1 and confirmed in 8.1.1

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

This is according to how version locking & version resolution works in Gradle. 
Gradle will complain if the changed version is incompatible with the locked one, exactly what happens here.
Please consult the documentation.

**Comment by sacchettom** [comment]
@jbartok in the example above `2.+` and `2.15.0` are actually supposed to be equivalent, and the locked one was `2.14.2`. I don't find particularly clear the reason why the first is deemed as compatible but the second is not. Furthermore, as I wrote, the error is cryptic - it shows for the same path a `strictly` constraint paired with a "normal" version. In these cases I'd expect the `strictly` to take over and eventually downgrade the other version. Maybe at least the error message could be made clearer?

**Comment by jbartok** [comment]
How `2.+` relates to `2.15.0` is irrelevant. How they both relate to `2.14.2`, that's what matters since that's the version you locked on. The message might not be perfect, but it explains the problem pretty well.
