### ISSUE TITLE
Gradle task produces unwanted `/bin` directory

### ISSUE THREAD

**Issue by djkeh** [gradle/gradle#24952]
### Expected Behavior

Gradle task should never create `/bin` directory in the root project to store build outputs or anything.

### Current Behavior

Gradle task(`test` or `build`) creates `/bin` directory when executed, but the reason is unclear.

![demo](https://user-images.githubusercontent.com/4949544/235602535-89127de6-93bd-4765-ac30-4a6ce42a329c.gif)

### Context (optional)

I first reported this issue to the jetbrains, but after the inspection they answered this seems not related to the IDE problem.

#### Reference

* https://youtrack.jetbrains.com/issue/IDEA-301675

### Steps to Reproduce

1. Create or clone a gradle project. I experienced this issue on some `java + spring + gradle` and `kotlin + spring + gradle` projects.
    * Sometimes `/bin` directory is instantly created right after this step.
2. Open the project using Intellij.
3. Make a decent file change.
4. Run a test or build it.

### Gradle version

Diverse. I've been experiencing this issue over a year. The latest one is `7.6`.

### Your Environment (optional)

* MacBook Pro 16 (M1) or MacBook Air (M1)
* macOS Ventura 13.3.1
* Intellij 2023.1 - Build #IU-231.8109.175, built on March 28, 2023
* Spring Boot Project initialized in `https://start.spring.io/`
	* Kotlin + Spring Boot + Gradle
	* Java + Spring Boot + Gradle

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

This doesn't look like a Gradle issue. For us to consider this an issue, we would need a self-contained reproducer that shows the problem on the CLI.
