### ISSUE TITLE
Config cache should support serializing `java.util.ArrayDeque`

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#24980]
### Expected Behavior

Config cache should support serializing `java.util.ArrayDeque`

### Current Behavior (optional)

Config cache does NOT support serializing `java.util.ArrayDeque`

### Context

See comment from @bamboo on this ticket: 
https://github.com/gradle/gradle/issues/22765#issuecomment-1339427241

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.
