### ISSUE TITLE
JVM Test Suite Plugin DSL support for changing test suite sources directory name

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#25000]
### Expected Behavior

The [Gradle TestSets Plugin](https://github.com/unbroken-dome/gradle-testsets-plugin) has a nice `dirName` DSL for [changing the directory name](https://github.com/unbroken-dome/gradle-testsets-plugin#changing-the-directory-name) for the sources of a test suite (for example, given a test suite name "integrationTest", 'src/it/java' instead of 'src/integrationTest/java'). It would be nice if the JVM Test Suite Plugin had a similarly high-level configuration option in its DSL.

### Current Behavior (optional)

Currently, changing the default sources directory involves a fair amount of boilerplate, more so for a Java + Kotlin project:

```kotlin
sources {
	val dirName = "it"
	java {
		setSrcDirs(listOf("src/$dirName/java"))
	}
	kotlin {
		setSrcDirs(
			listOf(
				"src/$dirName/kotlin",
				"src/$dirName/java",
			)
		)
	}
	resources {
		setSrcDirs(listOf("src/$dirName/resources"))
	}
}
```

Also, per #24920 for example, getting that configuration right is not entirely trivial.

### Context

I'm trying to switch from the Gradle TestSets Plugin to the JVM Test Suites Plugin because the former is not currently compatible with Gradle 8 per unbroken-dome/gradle-testsets-plugin#131. I'm lamenting how easy it was to change the sources directory with the Gradle TestSets Plugin.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by big-guy** [comment]
I don't think we want to add this to JVM test suites as a high-level feature. We think it's good that the directory structure follows the name of the test suite.  You can always add more directories to the source set. 

Some alternatives:
- Rename the test suite to follow the same conventions (this would mean calling it "it")
- Don't use a different directory structure than the convention
- Move the tricky configuration into a convention plugin and "hide" it from the build script
