### ISSUE TITLE
Some implicit imports for .gradle.kts are package private

### ISSUE THREAD

**Issue by klunnii** [gradle/gradle#25018]
### Expected Behavior

During the Gradle sync IDEA (Kotlin plugin) gets information about implicit imports for scripts.
`org.gradle.tooling.model.kotlin.dsl.KotlinDslScriptModel#getImplicitImports` is a function listing corresponding data. All these imports are expected to be available, i.e. there should be no private and package-private classes/interfaces among them.

### Current Behavior

Actual values returned from the `KotlinDslScriptModel#getImplicitImports` contain package-private classes. The new Kotlin K2 compiler is no longer that tolerant and reports corresponding errors.
Here is the list of classes reported for Gradle 8.1.1:
```
INVISIBLE IMPORT: org.gradle.api.publish.plugins.PublishingPluginRules
INVISIBLE IMPORT: org.gradle.api.tasks.diagnostics.ResolutionErrorRenderer
INVISIBLE IMPORT: org.gradle.api.tasks.wrapper.GradleVersionResolver
INVISIBLE IMPORT: org.gradle.ide.visualstudio.plugins.VisualStudioPluginRules
INVISIBLE IMPORT: org.gradle.plugin.devel.plugins.IvyPluginPublishingPlugin
INVISIBLE IMPORT: org.gradle.plugin.devel.plugins.MavenPluginPublishPlugin
```

### Context (optional)

Currently, the issue prevents the Kotlin K2 compiler from the script file analysis.
We'll probably add some tolerance mode for backward compatibility. But having the imports list correct is still important.

### Steps to Reproduce

Since the K2 support is currently in progress there is no publicly available IDEA (Kotlin plugin) version suffering from the issue. However, it's still possible to see the list of implicit imports. For example, one can activate Gradle sync and put a breakpoint at `org.jetbrains.kotlin.idea.gradleJava.scripting.importing.KotlinDslScriptModelProcessorKt#toListOfScriptModels`.

### Gradle version

8.1.1

**Comment by eskatos** [comment]
Thank you for the report!

The issue is in the backlog of the relevant team and is prioritized by them.
