### ISSUE TITLE
application plugin does not allow overwriting `lib` directory in ZIP file

### ISSUE THREAD

**Issue by The-Alchemist** [gradle/gradle#2501]
According to https://docs.gradle.org/current/userguide/application_plugin.html, the "All runtime dependencies and main source set class files." go into the `lib` dir, but this isn't configurable.

It would be great if you could set the location.

If someone points me to the right file/function, I can probably submit a PR to allow customizing this location.

**Comment by bmuschko** [comment]
I wrote a [spec for this functionality](https://github.com/gradle/gradle/blob/master/design-docs/application-plugin-improvements.md#custom-directory-structure-for-generated-application-files) a while ago. AFAIR the approach hasn't been agreed upon. Feel free to put your thoughts into this issue.
