### ISSUE TITLE
Composite builds hang with 4.0 and parallel dependency resolution

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#2502]
Reported on forums:
https://discuss.gradle.org/t/composite-build-hangs-after-upgrade-to-gradle-4-0/23236/12

### Expected Behavior

Build should not hang.

### Current Behavior

Build sometimes hangs.  This is difficult to trigger because it requires max-workers dependency resolution operations to occur at the same time as a included build execution.  

### Steps to Reproduce (for bugs)

I haven't been able to reliably recreate this with a test case, but two separate people reported the same problem with stacktraces that show:
1. Parallel dependency operations
2. A included build trying to build
3. Everything hung indefinitely.

We currently have test coverage for a more controlled scenario that no longer hangs (but appeared similar to the hang when it didn't work).

**Comment by nskvortsov** [comment]
JFYI it can be reliably reproduced with following set up:
* Android Studio 3.0.1
* Create new android project with a default activity (wrapper ver. 4.1 gets generated)
* `includeBuild` simple Gradle java project with at least 1 `compile` scope dependency
* Add an `implementation` dependency from android to included project 
* Re-run synchronization. 
Expected: sync successfull,
Actual:  sync hangs resolving compile dependencies of included build.
