### ISSUE TITLE
Test filters of TestLauncher should be respected when configuration cache is reused

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#25033]
### Expected Behavior

When tests are invoked with TestLauncher through TAPI, the test filters should be applied when the configuration cache is reused.

### Current Behavior

Test filters are ignored when the configuration cache is reused.

### Steps to Reproduce

See #25032

### Gradle version

7.6+

**Comment by bamboo** [comment]
Fixed via #25113.
