### ISSUE TITLE
Gradle fails catastrophically on multi-release jars with unsupported Java versions

### ISSUE THREAD

**Issue by jimshowalter** [gradle/gradle#25043]
### Expected Behavior

When Gradle encounters a multi-release jar (https://openjdk.org/jeps/238) with a Java version under META-INF that is not recognized by that version of Gradle, Gradle should just ignore the unrecognized version and continue working.

### Current Behavior

After upgrading jackson-core to 2.15.0, Gradle 7.4.2 failed with these errors:

`Failed to create Jar file /home/jenkins/workspace/ourProject/.gradle/caches/jars-9/bc33e077f18aab4d8905d3690c9e67e4/jackson-core-2.15.0.jar.`

`16:31:39  Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63`

Because the failure was complete, we couldn't use Gradle to try to debug the problem. For example, ./gradlew dependencies failed with the same "Failed to create Jar file" error.

### Steps to Reproduce

Create a project with a dependency on jackson-core 2.15.0 and Gradle 7.4.2, then try to run ./gradlew dependencies.

### Gradle version

7.4.2

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Please provide details about the environment you experience this problem in, especially the Java version you use to run Gradle (and possibly any toolchain versions you use). We suspect your problem to be not completely generic, hence asking for a concrete reproducer.
