### ISSUE TITLE
Classpath instrumentation of NIO.2 operations fails for paths in zip archives

### ISSUE THREAD

**Issue by netvl** [gradle/gradle#25044]
### Expected Behavior

Using `Files.readString` API in plugin code when reading non-default file systems should work correctly.

### Current Behavior

When some code which runs within Gradle (a custom plugin, in most cases) tries to execute `Files.readString` without specifying the charset against a `Path` instance created from a zip file system, this method call will fail due to incorrect instrumentation within Gradle:
```
java.lang.UnsupportedOperationException
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.toFile(ZipPath.java:674)
	at org.gradle.internal.classpath.Instrumented.filesReadString(Instrumented.java:419)
	at org.gradle.internal.classpath.declarations.NioFileInterceptors.intercept_readString(NioFileInterceptors.java:169)
	...
```

The reason, as it seems, is that the path is attempted to be converted into a `File` instance unconditionally: https://github.com/gradle/gradle/blob/709020ab2c636b5af11e9abda03bbc7bc198cef1/subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java#L427
This naturally fails for non-local file system paths.
It might be that some other similarly instrumented operations are affected as well.

### Context (optional)

`Files.readString` and other similar operations are very common in plugins, so it would make sense for it to work without hitches. It seems that this error started to happen relatively recently, probably because Gradle didn't do this kind of instrumentation earlier.

### Steps to Reproduce

Any way to execute `Files.readString()` against a `Path` inside a zip archive while within the instrumented Gradle classpath should demonstrate the issue. In our case, this method was called from within our internal plugin which uses zip file system to read zip archive contents.

### Gradle version

8.1.1

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by netvl** [comment]
Is there any chance of this being fixed sooner? Looking at the code and comparing two adjacent methods:
https://github.com/gradle/gradle/blob/eb27e930e9120bff77261c49818111fcfda2bcdc/subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java#L426-L429
https://github.com/gradle/gradle/blob/eb27e930e9120bff77261c49818111fcfda2bcdc/subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java#L431-L434
it looks like the fix will be a very simple one-liner, since the `readString(Path, Charset)` instrumented body looks correct.

**Comment by mlopatkin** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by wuyangnju** [comment]
Hi @mlopatkin, this is my first PR to Gradle, could you help me assign a reviewer? https://github.com/gradle/gradle/pull/26117
