### ISSUE TITLE
Document status of the JVM Test Suite Plugin

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#25045]
### Issue type

Wrong or misleading information

### Problem description

The current User Guide documentation for the JVM Test Suite Plugin shows use of `TestingExtension`, `JvmTestSuite`, etc., but makes no mention of them being incubating: https://docs.gradle.org/8.1.1/userguide/jvm_test_suite_plugin.html.

The API docs do clearly show them as incubating, e.g.: https://docs.gradle.org/8.1.1/dsl/org.gradle.testing.base.TestingExtension.html.

I would expect the User Guide to have a warning that the feature is still incubating, similar to how the Configuration Cache page did before that feature was promoted: https://docs.gradle.org/7.6.1/userguide/configuration_cache.html.

### Context (optional)

Going by just the User Guide led me to believe the feature was in [public state](https://docs.gradle.org/8.1.1/userguide/feature_lifecycle.html#sec:public), only to find that I got warnings in my IDE that it was in incubating state.

### Page with the problem

https://docs.gradle.org/8.1.1/userguide/jvm_test_suite_plugin.html

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by big-guy** [comment]
This was fixed in 8.7: https://docs.gradle.org/8.7-rc-1/userguide/jvm_test_suite_plugin.html
