### ISSUE TITLE
Improve test coverage for compiler daemons

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#2506]
While investigating the issue related to https://github.com/gradle/gradle/pull/2505 it became apparent that we don't have a lot of test coverage for verifying that compiler daemons get the correct configuration from the Compile task they are associated with.  We should better define what is and is not expected here and pin it down with some better test coverage.  Some questions that I had while looking at this:

- Should we warn when a user sets something on the Compile task that will not be honored in the compiler daemon (e.g. options.forkOptions.executable)?
- Are there settings on the Compile task that we do not currently respect that should be?
- There are some places where there are duplicate settings (e.g. options.forkOptions.memoryInitialSize vs groovyOptions.forkOptions.memoryInitialSize).  Right now, we merge the values - should we warn when these settings are different?
- Should we better document the behavior when options.fork = true in the user guide and/or dsl reference?

**Comment by bmuschko** [comment]
@ghale Is this something you are actively working on?

**Comment by ghale** [comment]
Not at the moment, no.
