### ISSUE TITLE
Dependencies Load from Unexpected Paths

### ISSUE THREAD

**Issue by rbm-crgl** [gradle/gradle#25091]
### Expected Behavior

I expect that Gradle will try to resolve dependencies based on their location in the files cache.

### Current Behavior

Gradle attempts to load transitive dependencies from their parent's folder. Here is a screenshot of the debugger output:

<img width="1159" alt="Screen Shot 2023-05-17 at 8 56 33 AM" src="https://github.com/gradle/gradle/assets/133886259/9d866459-d715-4478-b535-c14a27826b0d">

In this example, Gradle is looking for mchange-commons-java in a directory that only contains files for c3p0.

### Steps to Reproduce

Upgrade from Gradle 6 to 8, Spring Boot 2 to 3 and Java 11 to 17. After upgrade Gradle attempts to resolve some dependencies in the wrong location.

### Gradle version

8.1

### Your Environment (optional)

Environment is running in Intellij IDE on MacOS with the following configs:
<img width="503" alt="image" src="https://github.com/gradle/gradle/assets/133886259/35247313-e99e-461a-81bc-2f4c375805b9">

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
