### ISSUE TITLE
Parent poms missing from lockfiles

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#25111]
### Expected Behavior

`--write-locks` should add info about all transitive parent pom to the lockfiles. 

AND `LockMode.STRICT` should require that all transitive parent poms that are used be declared in the lockfile.

### Current Behavior

`--write-locks` doesn't write details of parent poms to the lockfiles.
AND `LockMode.STRICT` doesn't complain about missing details of parent poms

### Steps to Reproduce

1. add this dependency

```
implementation("org.apache.logging.log4j:log4j:2.20.0")
```

Notice the parent pom: 

See https://central.sonatype.com/artifact/org.apache.logging.log4j/log4j/2.20.0

Which contains: 
```
  <parent>
    <groupId>org.apache.logging</groupId>
    <artifactId>logging-parent</artifactId>
    <version>7</version>
    <relativePath />
  </parent>
```

in turn, if you then look at https://central.sonatype.com/artifact/org.apache.logging/logging-parent/7

You will see that it also has a parent pom: 
```
  <parent>
    <groupId>org.apache</groupId>
    <artifactId>apache</artifactId>
    <version>27</version>
  </parent>
```

But if you generate `--write-locks`, the parent poms info is completely omitted from the generated lock files.

### Gradle version

8.1.1

**Comment by jbartok** [comment]
What are you trying to achieve? This seems irrelevant because a POM file's hierarchy is fixed. A POM can't reference a parent with a range. So once you know which version was resolved, you know the hierarchy that has been resolved. Having this info in the lock-file would just be noise.

**Comment by yogurtearl** [comment]
In absence of dependency verification...

Sometimes poms for the same exact GAV coordinates differ between the gradle plugin portal and maven central, which means the parent pom could differ based on which repository the pom was loaded from.

Also, even within a single repository, the pom itself could theoretically change to point to a different parent pom, i.e. a new version of a pom was uploaded for the same GAV. (Yes, this is terrible and breaks lots of things).  

We want the lockfile to be a complete record of the resolved version of every external artifact including transitive parent poms.

**Comment by yogurtearl** [comment]
Additionally, seeing which versions of which parent poms where resolved as part of each configuration can be help. 

Also, dependency verification doesn't work reliably for parent poms, but even if it did, I would still want them to show up in the lockfiles. 

see https://github.com/gradle/gradle/issues/20194

**Comment by ov7a** [comment]
Sorry for the late reply.

This is the intended behavior, and there’s no plan to change it. 

*** 

This is a valid documentation issue that we will address. We should clarify explicitly in our documentation the reasons behind this decision.

**Comment by brianmcgee** [comment]
This also makes integrating with [Nix](https://nixos.org/) challenging since the locking and verification metadata mechanisms are not exhaustive. 

If this behaviour will not change, can we get better access to build operations, currently an internal API, to make it easier to write a plugin that generates a more desirable lock file without needing to fork Gradle itself? Or perhaps a simpler API could be exposed to make this easier?

**Comment by big-guy** [comment]
WRT lock files, since parent POMs cannot be dynamic versions, they don't necessarily belong in the lock file. We would need to allow multiple versions of the same parent to be listed in a lock file or resolve conflicts between parents (which isn't something we do today). 

https://github.com/gradle/gradle/issues/20194 is a valid issue and should be addressed.

**Comment by big-guy** [comment]
@brianmcgee lock files are intended to ensure dynamic versions are resolved consistently across builds.  They're not intended to be a complete report of every dependency artifact used by a project. 

Does Nix just need a way to capture/list all artifacts required by the build?

**Comment by brianmcgee** [comment]
@big-guy yeah, for Nix we need an exhaustive manifest of every dependency artefact ahead of time. I'll open a separate issue detailing things more clearly and the current workarounds etc. I've already been chatting with @britter about this on and off over the last couple months.
