### ISSUE TITLE
CreateStartScripts task generates classpath in wrong order

### ISSUE THREAD

**Issue by thhalm-talkwalker** [gradle/gradle#2513]
The transformation of the startscripts' classpath property to the relative classpath used inside the start scripts does not maintain the classpath order.

### Expected Behavior
Relative classpath must have the same order as the configured classpath

### Current Behavior
`getRelativeClasspath()` uses 
```
public static <R, I> Set<R> collect(Set<? extends I> set, Transformer<? extends R, ? super I> transformer) {
        return collect(set, new HashSet<R>(), transformer);
}
```
which uses a new HashSet instance to create the transformed Iterable and therefore the order is undefined.

[CreateStartScripts.java](https://github.com/gradle/gradle/blob/v4.0.1/subprojects/plugins/src/main/java/org/gradle/jvm/application/tasks/CreateStartScripts.java#L278)

### Steps to Reproduce (for bugs)
Bug is still on master, discovered in version 4.0.1

**Comment by big-guy** [comment]
Good find @thhalm.  Would you be interested in contributing a fix?

**Comment by thhalm** [comment]
Sure, I will create a pull request.

btw: I think only version >= 4.0 are affected. (in 3.5. it was still correct as ```com.google.common.collect.Iterables#transform``` was used)
