### ISSUE TITLE
declare git repository as dependency in android gradle?

### ISSUE THREAD

**Issue by aplha98** [gradle/gradle#25141]
### Expected Behavior

possible to declare git repository as dependency in android gradle?

### Current Behavior (optional)

not possible to declare git repository as dependency in android gradle?
a 

### Context

I am IOS developer, it is suger and easy to any git repo as dependency using cocoa pods or swift packaging

**Comment by melix** [comment]
Take a look at this plugin: https://melix.github.io/includegit-gradle-plugin/latest/index.html

**Comment by jbartok** [comment]
This is already implemented, but the feature is incomplete and undocumented (and not our roadmap for improvements for now).

Your best best is the plugin mentioned above.
