### ISSUE TITLE
testFixtures: project.providers.gradleProperty won't return value specified in ExtraPropertiesExtension

### ISSUE THREAD

**Issue by sellmair** [gradle/gradle#25158]
### Expected Behavior

When creating a test using Gradles testFixtures like
```kotlin
    @Test
    fun `gradle property`() {
        val project = ProjectBuilder.builder().build()
        project.extensions.extraProperties.set("foo", "bar")
        assertEquals("bar", project.findProperty("foo"))
        assertEquals("bar", project.providers.gradleProperty("foo").orNull)
    }
```

I expect the test to pass ✅

### Current Behavior

```
java.lang.AssertionError: expected:<bar> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
```

Evaluation of the `gradleProperty("foo").orNull`  will return null

### Context (optional)

Context: When writing Gradle plugin code, I would like to test the behaviour under different values for the `gradleProperty()`. Currently there seems no other way to provide the property using Gradle testFixtures.

### Steps to Reproduce

Create test above

### Gradle version

7.6.1

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by ljacomet** [comment]
We missed the importance of the `ProjectBuilder` context when triaging.

This is actually a duplicate of:
* #17638
