### ISSUE TITLE
compileClasspath in sourceSets doesn't work same as classpath option in javac

### ISSUE THREAD

**Issue by mahee96** [gradle/gradle#25171]
### Expected Behavior

`compileClasspath`of a sourceSet should recognize java sources and pick them up for compilation if they are dependencies **similar to javac compiler behavior**

### Current Behavior

compilation fails even when the dependent classes are provided as raw *.java files via `compileClasspath` of that sourceSet.

### Context (optional)

I am trying to keep all sources into the classpath  and compile them on-demand, only when the java files included for compilation requires them indirectly as dependencies.

I am aware that this can be accomplished with an alternative approach by adding them under `srcDirs` and `includes/excludes` patternSet of the SourceSet.

But `compileClasspath` of a sourceSet is expected to mimic the behavior of -classpath option of javac compiler which is not the case with gradle compilation.

I have used `java` plugin and the source being compiled is java source.

### minimal reproducible example project:
![image](https://github.com/gradle/gradle/assets/47920326/ffe672b2-b1d3-4ade-b657-61f302fbb0d9)

### build.gradle
![image](https://github.com/gradle/gradle/assets/47920326/ca3427f9-1fd1-4549-8dba-e083ae3f6600)

### org.car.deps.Engine.java
![image](https://github.com/gradle/gradle/assets/47920326/ef7a1b19-4ce1-4868-8d3d-da01330c51cb)

### Car.java
![image](https://github.com/gradle/gradle/assets/47920326/bd1e8142-1f70-4a2c-aad8-1b566405e282)

## Compilation fails
- executing the task `run` causes implicit dependent task `compileJava` to be triggered and **compilation fails**.

![image](https://github.com/gradle/gradle/assets/47920326/5d59a075-3c40-4583-b2f0-08dd88e6b9cf)

## Compilation and Run successful when using javac and java directly
![image](https://github.com/gradle/gradle/assets/47920326/ec767a19-29e4-48f0-b869-8931975175b0)
 

### Gradle version

8.0-all

### Build scan URL (optional)

N/A

### Your Environment (optional)

OS:   MacOS Ventura 13.4
java: OpenJDK-17.0.5
gradle: 8.0-all

**Comment by mahee96** [comment]
Sure @jbartok, I will add the proper reproducer and will report back here, Thanks.

**Comment by mahee96** [comment]
@jbartok, reproducer added:

issue-25171-reproducer: https://github.com/mahee96/gradle-issue-25171-reproducer
GH-action: https://github.com/mahee96/gradle-issue-25171-reproducer/actions/runs/5100307851/jobs/9168514587 

Thanks

**Comment by mahee96** [comment]
Hi, its there too please see the github action, it has both gradle and
javac jobs in the matrix on all windows, linux, macos taken from issue
reproducer template

**Comment by mahee96** [comment]
![image](https://github.com/gradle/gradle/assets/47920326/c5ef39ad-5274-4dc5-a20e-2ef4d2dbdff3)

Re attaching the screenshot for easier review

**Comment by mahee96** [comment]
Note: Both gradle and Java is using same source files!

**Comment by mahee96** [comment]
https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html

![image](https://github.com/gradle/gradle/assets/47920326/3ce5be8a-9b5a-4def-b759-912f1379d0fe)

**Comment by eskatos** [comment]
Thank you!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mahee96** [comment]
Thanks for taking up the issue

**Comment by mahee96** [comment]
Understood, Thanks for the reply. The expectation was in general in the sense that common java compilers such as javac from oracle, openjdk etc supported sources in classpath. 

Adding a `note` to the gradle docs would be helpful, because though gradle states that it has its own compiler implementation, when people switch newly from the javac compilers they have been used to it takes a great deal of effort to find it out the hard way.

Also gradle docs doesn't specify in detail what the compileClasspath can hold or take in for dependency/resource resolution.

**Comment by mahee96** [comment]
@tresat , your help will be much appreciated, Thanks!
