### ISSUE TITLE
Make Develocity plugin compatible with Isolated Projects

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#25177]
Including test distribution.

Depends on #22514

**Comment by adammurdoch** [comment]
Some discussion in this [slack thread](https://gradle.slack.com/archives/C593ELF5K/p1685051514392709)

**Comment by ljacomet** [comment]
@bamboo Can you please add a milestone and remove `to-triage` once done?

**Comment by bamboo** [comment]
Sure thing. The `to-triage` label was added by the github bot once I moved it to _Done_ 🤔
