### ISSUE TITLE
Spike a new classloading pipeline for instrumented JARs

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#25188]
Currently we use the `ClassPath` instance produced by the instrumenting code to find the original JARs to construct TransformingClassLoader from. If we want to use the ArtifactTransform to perform the transformation, we'd only get the transformed JARs. We need to find the way to connect transformed JAR to its original.

One potential option would be to package the original JAR into the transformed one and load it from there. Alternatively, we could add something to the JAR's manifest, but we should strive to make the resulting transformed JAR relocatable.

**Comment by bamboo** [comment]
Delivered to the Provider API task force.
