### ISSUE TITLE
maven-publish produces jar with source files not class files when multiple source dirs  and workaround for fake duplicates

### ISSUE THREAD

**Issue by carstenSpraener** [gradle/gradle#25208]
### Expected Behavior

When publishing with maven-publish the produced jar file should contain the compiled class files.

### Current Behavior

The published jar file contains the sources not the class files.

### Context (optional)

------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4.1 (Eclipse Adoptium 17.0.4.1+1)
OS:           Mac OS X 13.3.1 x86_64

### Steps to Reproduce

Create a project with the following build.gradle

```groovy
plugins {
    id 'java-library'
    id 'maven-publish'
}
group = 'my.group'
version = '0.0.1-SNAPSHOT'
sourceSets {
    src{
        main {
            java {
                srcDir('src/main/java')
                srcDir('src/main/java-gen')
            }
        }
    }
}
// WORKAROUND! If you comment this out gradle will report false duplicates
task sourcesJar(type: Jar) {
    duplicatesStrategy = 'exclude'
    from sourceSets.main.allSource
}
java {
    withJavadocJar()
    withSourcesJar()
}
publishing {
    publications {
        sonatype(MavenPublication) {
            from components.java
         }
    }
    repositories {
        maven {
            name = 'local'
            url="${project.rootDir}/repo"
        }
    }
}
```

Create a java File und src/main/java like:

```java
public class Main {
}
```
 
You can leave the source folder src/main/java-gen empty.
Start publishing with:

`gradle publishSonatypePublicationToLocalRepository`

List the content of published jar file:

```
❯ jar -tf repo/my/group/PublishError/0.0.1-SNAPSHOT/PublishError-0.0.1-*-1.jar
META-INF/
META-INF/MANIFEST.MF
Main.java
```

### Gradle version

8.1.1

### Your Environment (optional)

------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4.1 (Eclipse Adoptium 17.0.4.1+1)
OS:           Mac OS X 13.3.1 x86_64

**Comment by carstenSpraener** [comment]
Seems this bug is related to

https://github.com/gradle/gradle/issues/17236

I can't publish at the moment.

**Comment by remal** [comment]
@carstenSpraener

First of all, your Gradle script looks a bit strange:
```gradle
sourceSets {
    src{ // <-- What is it for? Are you defining `src` source set?
        main {
            java {
                srcDir('src/main/java')
                srcDir('src/main/java-gen')
            }
        }
    }
}
```

I suppose the issue is that you add a dir that is already added: `src/main/java`. By default, this dir is already presented in the `main` source set. So, the fix, I suppose, is to remove `srcDir('src/main/java')` line.

**Comment by carstenSpraener** [comment]
Yepp! That's it. Many thanks. Puh! Took me nearly a day of frustration. Gradle is great again.

(By the way... maybe the srcDirs should be a set, so that double entries do not bother)

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

----

Good you sorted it out!
