### ISSUE TITLE
Support `--continue` for composite builds

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2520]
Task references are not correctly handled for `--continue` by the `TaskPlanExecutor`.
See ignored tests in [CompositeBuildContinueOnFailureIntegrationTest](https://github.com/gradle/gradle/blob/master/subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildContinueOnFailureIntegrationTest.groovy#L26-L26).

**Comment by bigdaz** [comment]
We gather up all tasks for an included build and execute them in a single build invocation. Presently, this has multiple issues:

- We don't execute the included build with --continue, so some of the delegate tasks will never be attempted.
- If any task in an included build fails, we assume that failure applies to every delegated task (even if another task successfully executed)

**Comment by blindpirate** [comment]
@bigdaz If this isn't in progress, please remove `4.7RC1` milestone.
