### ISSUE TITLE
Gradle 8.2-milestone-1 The Project.getConvention() method has been deprecated. in Project.the()

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#25206]
### Expected Behavior

No warning, as can be seen in source code:
```kotlin
inline fun <reified T : Any> Project.the(): T =
    @Suppress("deprecation")
    typeOf<T>().let { type ->
        val c: org.gradle.api.plugins.Convention = DeprecationLogger.whileDisabled(Factory { convention })!!
        c.findByType(type) ?: c.findPlugin(T::class.java) ?: c.getByType(type)
    }
```

### Current Behavior

```
> Configure project :
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2-milestone-1/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin.addMavenRepositories(NexusPublishPlugin.kt:273)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin.access$addMavenRepositories(NexusPublishPlugin.kt:40)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin$configurePublishingForAllProjects$1$1$1.execute(NexusPublishPlugin.kt:157)
        at io.github.gradlenexus.publishplugin.NexusPublishPlugin$configurePublishingForAllProjects$1$1$1.execute(NexusPublishPlugin.kt:40)
```

### Context (optional)

The call is coming from
https://github.com/gradle-nexus/publish-plugin/blob/v1.3.0/src/main/kotlin/io/github/gradlenexus/publishplugin/NexusPublishPlugin.kt#L183

When I tried to debug it, the body of `the()` function and the line highlight was misaligned. So maybe the new kotlin-dsl is not applied? Yet I can see its source code.

### Steps to Reproduce

I tried reproducing with a simple build.gradle.kts:
```kotlin
interface MyExt
project.extensions.create("myExt", MyExt::class.java)
project.the<MyExt>()
```
but no result, so here's a more complex repro:
1. https://github.com/TWiStErRob/repros/tree/main/gradle/kotlinDsl-the-vs-ConventionDeprecation
2. `gradlew`

### Gradle version

Gradle 8.2-milestone-1

**Comment by eskatos** [comment]
Hi Róbert,

Thank you for the detailed report.

Accessing conventions is deprecated starting with Gradle 8.2
https://docs.gradle.org/8.2-rc-1/userguide/upgrading_version_8.html#deprecated_access_to_conventions

The Nexus plugin has been compiled against a previous Gradle version and it uses the `inline` extension function `Project.the<T>`. As you observed `inline` function bodies are inlined in client code at compilation time. The Nexus plugin has bytecode that calls `Project.getConvention()` without disabling deprecation warnings.

There are two ways forward:
1. recompile the Nexus plugin against Gradle 8.2.
2. change the Nexus plugin to not use the `inline` extension function and use the API instead: `extensions.getByType(T::class)`


This is a kind of trap with `inline` functions. In retrospect we would have implemented this particular extension function differently knowing conventions would go away. There isn't much we can do about it so I'm going to close this issue as a "won't fix".

---

Related to this you might be interested by this issue and its associated PR
* https://github.com/gradle/gradle/issues/25253

**Comment by TWiStErRob** [comment]
Ah, `inline` 🤦🏻‍♂️, makes sense, thanks for all the details!

Thanks for the heads up about the false deprecation warning, but I think that's fine in this case, since the extension must exist. Nexus is not using it to detect the extension's existence as far as I know.

I'll kindly ask @szpak to release a new version once Gradle 8.2 stable is out, PR incoming.
