### ISSUE TITLE
Resolved dependency URL is inconsistent

### ISSUE THREAD

**Issue by chayleaf** [gradle/gradle#25218]
### Expected Behavior

When resolving plugin `org.springframework.boot.gradle.plugin`, I get two different URLs on different machines, but they should be the same

### Current Behavior

The URLs consistently aren't the same.

- On my local machine, this file gets downloaded https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/3.0.6/spring-boot-gradle-plugin-3.0.6.pom
- On Github CI, this file gets downloaded https://plugins.gradle.org/m2/org/springframework/boot/org.springframework.boot.gradle.plugin/3.0.6/org.springframework.boot.gradle.plugin-3.0.6.pom

These files have different hashes and provide different info. The first one (downloaded by Gradle on my machine) produces the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.springframework.boot</groupId>
  <artifactId>org.springframework.boot.gradle.plugin</artifactId>
  <version>3.0.6</version>
  <packaging>pom</packaging>
  <name>Spring Boot Gradle Plugin</name>
  <description>Spring Boot Gradle Plugin</description>
  <url>https://spring.io/projects/spring-boot</url>
  <organization>
    <name>VMware, Inc.</name>
    <url>https://spring.io</url>
  </organization>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <name>Spring</name>
      <email>ask@spring.io</email>
      <organization>VMware, Inc.</organization>
      <organizationUrl>https://www.spring.io</organizationUrl>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:git://github.com/spring-projects/spring-boot.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/spring-projects/spring-boot.git</developerConnection>
    <url>https://github.com/spring-projects/spring-boot</url>
  </scm>
  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/spring-projects/spring-boot/issues</url>
  </issueManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-gradle-plugin</artifactId>
      <version>3.0.6</version>
    </dependency>
  </dependencies>
</project>
```

The second one (downloaded by Gradle on Github CI):

```xml
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.springframework.boot</groupId>
  <artifactId>org.springframework.boot.gradle.plugin</artifactId>
  <version>3.0.6</version>
  <packaging>pom</packaging>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-gradle-plugin</artifactId>
      <version>3.0.6</version>
    </dependency>
  </dependencies>
</project>
```

### Context (optional)

Right now I'm working on packaging [this Gradle app](https://github.com/FAForever/downlords-faf-client) for NixOS. To ensure clean state, this is being run between each build:

```bash
export GRADLE_USER_HOME=$(mktemp -d)
```

Additionally, `-SNAPSHOT` builds get replaced with `latest.integration`, gradle.lockfile and buildscript-gradle.lockfile are first produced (the original repo doesn't have one), and the builds are ran in a sandbox. I think this should ensure the maximum reproducibility, however that isn't currently the case.

The lockfiles are produced by using the following init script and running this task

```gradle
gradle.projectsLoaded {
  rootProject.allprojects {
    dependencyLocking {
      lockAllConfigurations()
    }
    buildscript {
      dependencyLocking {
        lockAllConfigurations()
      }
    }
    task downloadDependencies {
      doLast {
        configurations.findAll{it.canBeResolved}.each{it.resolve()}
        buildscript.configurations.findAll{it.canBeResolved}.each{it.resolve()}
      }
    }
  }
}
```

with `--write-locks`.

The Gradle binary is also exactly the same, byte-by-byte, ensured by Nix's reproducibility.

This should ensure that the same files get downloaded on any machine. However, they diverge, as mentioned above.

An important difference is Github CI is using a generic FHS-compliant Linux distro, while I am building it on NixOS. The sandbox hides those details, but this still might have contributed to the divergence to some extent. Different file order on the filesystem, or some other minor detail could cause it. However, none of that should affect dependency resolution.

The reason this is important is because I have to know the exact hash of the downloaded files on NixOS to ensure build reproducibility. If the hash differs, I can't properly package it. Of course I can write a .pom normalizer, but in my opinion it's better for this to be handled on Gradle's side.

### Steps to Reproduce

I don't know the exact reasons for different URLs being used, so I don't even know where to begin figuring out the reasons behind the issue. Any pointers are appreciated. If a Gradle developer is fluent in Nix, they can try debugging the [Nix derivation](https://github.com/chayleaf/nix-gaming/blob/1be6ed07a40653b90c327f3e2f6cb8f0b0b29f2b/pkgs/faf-client/default.nix) I'm writing (use this exact commit hash), and this is where the issue occurs.

I can collect further debugging info if necessary.

For reference, [here's the lockfile](https://raw.githubusercontent.com/chayleaf/nix-gaming/1be6ed07a40653b90c327f3e2f6cb8f0b0b29f2b/pkgs/faf-client/gradle-stable.lockfile) / [buildscript lockfile](https://raw.githubusercontent.com/chayleaf/nix-gaming/1be6ed07a40653b90c327f3e2f6cb8f0b0b29f2b/pkgs/faf-client/buildscript-gradle-stable.lockfile) (as a reminder, the upstream project is [here](https://github.com/FAForever/downlords-faf-client)).

### Gradle version

8.0.1

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

----

The two POMs you listed are both about the Spring Boot Gradle plugin but for different modules. The second one (plugin marker) depends on the first one (plugin artifact).

It seems either environment can't reach one of the two involved repositories (The plugin portal and maven central), or something similar.

Could you please share Gradle debug logs for the two invocations with a clean Gradle user home so we can pinpoint the difference?

**Comment by chayleaf** [comment]
The log for Github CI is available [here](https://github.com/chayleaf/nix-gaming/actions/runs/5121035239/jobs/9208274349)

My log: 
[log.txt](https://github.com/gradle/gradle/files/11645119/log.txt)

At the end the logs print the hashes of all .jar and .pom files downloaded.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

The `action/setup-java` GitHub action is doing some automatic caching of Gradle dependencies.
That explains the difference on the amount of dependencies downloaded by both builds.
See https://github.com/actions/setup-java

You should remove this line from your GitHub workflows if you want better reproducibility
https://github.com/FAForever/downlords-faf-client/blob/develop/.github/workflows/checks.yml#L24

----

Another thing is that the Spring Boot plugin metadata artifacts are downloaded from both Gradle's Plugin Portal and Maven Central. Could you try adding the following to your `settings.gradle`. It should tell your build to use mavenCentral() everywhere to resolve plugins from `plugins {}` blocks.

```groovy
pluginManagement {
    repositories { mavenCentral() }
}
```
