### ISSUE TITLE
`org.gradle.api.artifacts.VersionCatalog#findLibrary` is inneficient

### ISSUE THREAD

**Issue by erdi** [gradle/gradle#25226]
### Expected Behavior

Ideally, the size of the version catalog would not have impact on the time it takes to look up a library in it.

### Current Behavior

The bigger the version catalog the more time it takes for `org.gradle.api.artifacts.VersionCatalog#findLibrary` to complete.

### Context (optional)

Because `org.gradle.api.internal.catalog.VersionCatalogView#findLibrary` calls `org.gradle.api.internal.catalog.DefaultVersionCatalog#getLibraryAliases` which sorts the collection of library aliases in the catalog every time it is called, the bigger the catalog the slower the lookup will be even though libraries are stored in a map indexed with their aliases.

In our case we have a convention plugin which is applied to over 1000 subprojects. That convention plugin looks up and adds a couple of test dependencies listed in the catalog which has 400 entries. At that scale the inefficiency in `org.gradle.api.internal.catalog.VersionCatalogView#findLibrary` shows up as part of the configuration phase in build scans.

### Steps to Reproduce

Create a version catalog with 400 entries, perform a couple of lookups in a loop executed around 1000 times. Put a cache between the lookups and the code executing them and see a significant difference in execution time.

### Gradle version

8.1.1

**Comment by eskatos** [comment]
Thank you for providing a good report!

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by eskatos** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by erdi** [comment]
Thanks, @eskatos. I'm not a first time contributor and I'd be more than happy to provide a PR. I just have no idea what the testing strategy should be for this change (is it worth a micro benchmark using jmh? probably not...) but hopefully this can be discussed on the PR.

**Comment by eskatos** [comment]
@erdi We have a performance test suite that gets validated as part of PRs. AFAIK there's no scenario with a large version catalog but that could be added.

For inspiration this is the PR that added a small version catalog to our scenarios:
* https://github.com/gradle/gradle/pull/24985

**Comment by erdi** [comment]
Thanks, that's very helpful, I will take a closer look.
