### ISSUE TITLE
Gradle build fails with configuration cache enabled with warnings

### ISSUE THREAD

**Issue by artemptushkin** [gradle/gradle#25235]
### Expected Behavior

I expect that the configuration cache never fails the build with `warn` enabled, regardless of any issues in a plugin/configuration.

I have in `~/.gradle/gradle.properties`:

```properties
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
```

[JIB plugin](https://github.com/GoogleContainerTools/jib) defined:

```kotlin
jib {
	container {
		creationTime.set("USE_CURRENT_TIMESTAMP")
		mainClass = "com.my.MyApp"
	}
	from {
		image = "eclipse-temurin:17-jre"
	}
}
```

I run:
```shell
./gradlew jibDockerBuild
```

Build passes, I get no more than a warning from the configuration cache.

### Current Behavior

I get:
```txt
> Task :jibDockerBuild FAILED

10 problems were found storing the configuration cache, 2 of which seem unique.
- Task `:jibDockerBuild` of type `com.google.cloud.tools.jib.gradle.BuildDockerTask`: cannot deserialize object of type 'org.gradle.api.Project' as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.1.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:jibDockerBuild` of type `com.google.cloud.tools.jib.gradle.BuildDockerTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.1.1/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

See the complete report at file:///Users/artemptushkin/gitlab/IptiQ/dx/spring-cloud-config-server/build/reports/configuration-cache/dmnth65ek47ehgnuriyy459yl/ac38wk6b6wvejhas26wg0jngi/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jibDockerBuild'.
> Cannot invoke "org.gradle.api.Project.getProjectDir()" because "this.project" is null
```

### Context (optional)

* [Gradle thread forum](https://discuss.gradle.org/t/how-to-disable-build-failures-with-enabled-configuration-cache-in-gradle/45699)
* [Jib plugin issue](https://github.com/n0mer/gradle-git-properties/issues/225)

### Steps to Reproduce

See in "expected behaviour"

### Gradle version

8.1.0

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

---

`org.gradle.configuration-cache.problems=warn` allows you to let the build continue on problems but there's no guarantee that the build will work. It's useful for compatibility exploration or when you can make sure the problems of your build don't cause failures.

This is not explicitly said in the [Configuration Cache documentation](https://docs.gradle.org/current/userguide/configuration_cache.html) but it should probably be.

**Comment by eskatos** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by Vampire** [comment]
@eskatos do you really think this is a documentation issue?
With Gradle 7 it would have worked.
But with the change in Gradle 8, that the build is run from the CC deserialized state even on the CC-entry-storing run this fails the build as now the `project` is not set.
I would have thought, that with `warn` maybe the actually built state should then be used if there were problems like with Gradle 7?

**Comment by eskatos** [comment]
The behavior in 8.1 is the one for stable Configuration Cache.
With previous Gradle version you would have the same failure on the second build, surprisingly.

**Comment by Vampire** [comment]
Ah, right, because the `warn` would still save the CC entry and then reuse it on next run.
I forgot that again, as it is still not too intuitive to me. :-D
Then it's of course better to fail right away on the first run, forget that I said anything. :-)
