### ISSUE TITLE
Generate correct Eclipse metadata files for composite build

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2523]
@bigdaz commented on [Sun Apr 23 2017](https://github.com/gradle/composite-builds/issues/101)

Currently, `gradle idea` will generate correct metadata for a composite build, but `gradle eclipse` will not.

**Comment by calvertdw** [comment]
I did some research on composite builds in Eclipse. I was trying to get composite builds working on the source set or configuration level. Unfortunately Eclipse's classpath configuration only supports project level build dependencies which includes all output of that build (by default, the "bin" folder).

I'm forced to only use the main configuration of every project and configure what we previously had as a "test" source set into a sub-project with the name "project-test". Subprojects will be included in composite builds and Eclipse will use them as multiple projects, even if one project is a subfolder of another.
