### ISSUE TITLE
problem occurred configuring react native root project on run

### ISSUE THREAD

**Issue by AmirhoseinHeydariAmjad** [gradle/gradle#25232]
### Expected Behavior

i have all sdk and sdk tools and other dependencies and it should be built correctly(im okay with running expo cli projects)

### Current Behavior

im getting the following error:

> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.android.tools:sdk-common:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/30.3.1/sdk-common-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/sdk-common/30.3.1/sdk-common-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1 > com.android.tools.build:manifest-merger:30.3.1
      > Could not find com.android.tools:sdklib:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/30.3.1/sdklib-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/sdklib/30.3.1/sdklib-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1 > com.android.tools.build:manifest-merger:30.3.1
      > Could not find com.android.tools:repository:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/repository/30.3.1/repository-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/repository/30.3.1/repository-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.ddms:ddmlib:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/30.3.1/ddmlib-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/ddms/ddmlib/30.3.1/ddmlib-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
      > Could not find com.android.tools.build:aapt2-proto:7.3.1-8691043.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2-proto/7.3.1-8691043/aapt2-proto-7.3.1-8691043.pom        
          - https://repo.maven.apache.org/maven2/com/android/tools/build/aapt2-proto/7.3.1-8691043/aapt2-proto-7.3.1-8691043.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.build:aaptcompiler:7.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/aaptcompiler/7.3.1/aaptcompiler-7.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/build/aaptcompiler/7.3.1/aaptcompiler-7.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.analytics-library:crash:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/30.3.1/crash-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/analytics-library/crash/30.3.1/crash-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.analytics-library:shared:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/30.3.1/shared-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/analytics-library/shared/30.3.1/shared-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.lint:lint-model:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-model/30.3.1/lint-model-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/lint/lint-model/30.3.1/lint-model-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.lint:lint-typedef-remover:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-typedef-remover/30.3.1/lint-typedef-remover-30.3.1.pom     
          - https://repo.maven.apache.org/maven2/com/android/tools/lint/lint-typedef-remover/30.3.1/lint-typedef-remover-30.3.1.pom        
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find androidx.databinding:databinding-compiler-common:7.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/7.3.1/databinding-compiler-common-7.3.1.pom
          - https://repo.maven.apache.org/maven2/androidx/databinding/databinding-compiler-common/7.3.1/databinding-compiler-common-7.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find androidx.databinding:databinding-common:7.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/7.3.1/databinding-common-7.3.1.pom
          - https://repo.maven.apache.org/maven2/androidx/databinding/databinding-common/7.3.1/databinding-common-7.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.databinding:baseLibrary:7.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/7.3.1/baseLibrary-7.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/databinding/baseLibrary/7.3.1/baseLibrary-7.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.build:builder-test-api:7.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/7.3.1/builder-test-api-7.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/build/builder-test-api/7.3.1/builder-test-api-7.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:gradle-api:7.3.1
      > Could not find com.android.tools.layoutlib:layoutlib-api:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/30.3.1/layoutlib-api-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/layoutlib/layoutlib-api/30.3.1/layoutlib-api-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
      > Could not find com.android.tools.utp:android-device-provider-ddmlib-proto:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-device-provider-ddmlib-proto/30.3.1/android-device-provider-ddmlib-proto-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/utp/android-device-provider-ddmlib-proto/30.3.1/android-device-provider-ddmlib-proto-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.utp:android-device-provider-gradle-proto:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-device-provider-gradle-proto/30.3.1/android-device-provider-gradle-proto-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/utp/android-device-provider-gradle-proto/30.3.1/android-device-provider-gradle-proto-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.utp:android-test-plugin-host-additional-test-output-proto:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-host-additional-test-output-proto/30.3.1/android-test-plugin-host-additional-test-output-proto-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/utp/android-test-plugin-host-additional-test-output-proto/30.3.1/android-test-plugin-host-additional-test-output-proto-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.utp:android-test-plugin-host-coverage-proto:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-host-coverage-proto/30.3.1/android-test-plugin-host-coverage-proto-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/utp/android-test-plugin-host-coverage-proto/30.3.1/android-test-plugin-host-coverage-proto-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.utp:android-test-plugin-host-retention-proto:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-host-retention-proto/30.3.1/android-test-plugin-host-retention-proto-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/utp/android-test-plugin-host-retention-proto/30.3.1/android-test-plugin-host-retention-proto-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.utp:android-test-plugin-result-listener-gradle-proto:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/utp/android-test-plugin-result-listener-gradle-proto/30.3.1/android-test-plugin-result-listener-gradle-proto-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/utp/android-test-plugin-result-listener-gradle-proto/30.3.1/android-test-plugin-result-listener-gradle-proto-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools.build:bundletool:1.9.0.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/1.9.0/bundletool-1.9.0.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/build/bundletool/1.9.0/bundletool-1.9.0.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1
      > Could not find com.android.tools:common:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/common/30.3.1/common-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/common/30.3.1/common-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1 > com.android.tools.build:manifest-merger:30.3.1
      > Could not find com.android:signflinger:7.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/signflinger/7.3.1/signflinger-7.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/signflinger/7.3.1/signflinger-7.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
      > Could not find com.android.tools.analytics-library:protos:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/30.3.1/protos-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/analytics-library/protos/30.3.1/protos-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
      > Could not find com.android.tools.analytics-library:tracker:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/30.3.1/tracker-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/analytics-library/tracker/30.3.1/tracker-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1
      > Could not find com.android.tools:annotations:30.3.1.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/android/tools/annotations/30.3.1/annotations-30.3.1.pom
          - https://repo.maven.apache.org/maven2/com/android/tools/annotations/30.3.1/annotations-30.3.1.pom
        Required by:
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder-model:7.3.1
            project : > com.android.tools.build:gradle:7.3.1 > com.android.tools.build:builder:7.3.1 > com.android:zipflinger:7.3.1        

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

### Steps to Reproduce

i just created the project using react native cli 

### Gradle version

7.5.1

### Gradle version that used to work

7.5.1

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the Android Gradle Plugin, which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug
