### ISSUE TITLE
gradle-8.0.1 fails to build gatk: it fails to find one plugin in the cache why building gatk offline

### ISSUE THREAD

**Issue by yurivict** [gradle/gradle#25275]
### Expected Behavior

The FreeBSD port biology/gatk first builds the gradle cache and then builds gatk offline.

The offline build fails:
```
Welcome to Gradle 8.0.1!

Here are the highlights of this release:
 - Improvements to the Kotlin DSL
 - Fine-grained parallelism from the first build with configuration cache
 - Configurable Gradle user home cache cleanup

For more details see https://docs.gradle.org/8.0.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/wrkdirs/usr/ports/biology/gatk/work/gatk-4.3.0.0/build.gradle' line: 15

* What went wrong:
Plugin [id: 'de.undercouch.download', version: '4.1.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'de.undercouch.download:de.undercouch.download.gradle.plugin:4.1.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

The cache build command:
> cd /usr/ports/biology/gatk/work/gatk-4.4.0.0 && /usr/bin/env XDG_DATA_HOME=/usr/ports/biology/gatk/work  XDG_CONFIG_HOME=/usr/ports/biology/gatk/work  XDG_CACHE_HOME=/usr/ports/biology/gatk/work/.cache  HOME=/usr/ports/biology/gatk/work PATH=/usr/local/libexec/ccache:/usr/ports/biology/gatk/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/biology/gatk/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" gradle  --gradle-user-home /usr/ports/biology/gatk/work/gradle-gatk --project-cache-dir /usr/ports/biology/gatk/work/gradle-gatk   --build-cache localJar

The offline build command that fails:
> cd /usr/ports/biology/gatk/work/gatk-4.4.0.0 && /usr/bin/env XDG_DATA_HOME=/usr/ports/biology/gatk/work  XDG_CONFIG_HOME=/usr/ports/biology/gatk/work  XDG_CACHE_HOME=/usr/ports/biology/gatk/work/.cache  HOME=/usr/ports/biology/gatk/work PATH=/usr/local/libexec/ccache:/usr/ports/biology/gatk/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/biology/gatk/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" gradle  --gradle-user-home /usr/ports/biology/gatk/work/gradle-gatk --project-cache-dir /usr/ports/biology/gatk/work/gradle-gatk  --offline --build-cache localJar
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

gradle-8.0.1
gatk-4.4.0.0 and gatk-4.3.0.0
FreeBSD 13.2

### Current Behavior

see above

### Steps to Reproduce

see above

### Gradle version

8.0.1

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
