### ISSUE TITLE
TomlCatalogFileParser should use BufferedInputStream

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25270]
### Expected Behavior

`TomlCatalogFileParser#parse` should use `BufferedInputStream` for the version catalog files to ensure that we do not do too much I/O on the file.

### Current Behavior

`TomlCatalogFileParser#parse` uses `Files.newInputStream(catalogFilePath)` that leads to a larger number of IO calls than needed.

### Steps to Reproduce

Tracing gradle configuration phase with a profiler

### Gradle version

8.2-rc-1

**Comment by jbartok** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
