### ISSUE TITLE
Add a parseable output of build statistics from --profile

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25273]
### Expected Behavior

When Gradle is run with `--profile` (or a new flag) each invocation outputs:
- start up time
- settings evaluation time
- buildSrc build time
- configuration time
- build time

this data ideally is in a format (like json) that is easy to parse by tools.

### Context

We try to make sure that our build does not regress in configuration time in CI so we'd like to collect stats about it over time. Currently we are achieving this with --profile and [manually parsing the html output](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:busytown/impl/parse_profile_html.py) which is quite fragile.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by lptr** [comment]
We haven't maintained `--profile` for a while. I don't see us investing in this given that public scans are available. I'll come back with some plan about what we'll do with `--profile` in the long run.

**Comment by ov7a** [comment]
Sorry for the late reply.

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented.

***

It's unlikely that this feature will get attention in the near future. There is still no long-term plan for dealing with `--profile`.

**Comment by lptr** [comment]
Let's close this since we are not planning to work on it.
