### ISSUE TITLE
`RepositoriesMode.FAIL_ON_PROJECT_REPOS` does not fail for `subprojects` configurations

### ISSUE THREAD

**Issue by TimvdLippe** [gradle/gradle#25307]
### Expected Behavior

The addition of `repositories` in a `subprojects` block are blocked if you turn on `RepositoriesMode.FAIL_ON_PROJECT_REPOS`. In other words, it prints the following message:

```
A problem occurred evaluating project ':context:first'.
> Build was configured to prefer settings repositories over project repositories but repository 'maven-repository' was added by build file 'context/first/first.gradle'
```

### Current Behavior

The `repositories` definition in a `subprojects` block are allowed. With the section turned on, it fails to resolve the dependency and prints the following message:

```
> Could not resolve all dependencies for configuration ':context:first:compileJava'.
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/7.4.2/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find com.example.dependency:1.0.0.
     Searched in the following locations:
```

This happens when you invoke the task, rather than during configuration time.

### Context (optional)

We are trying to replace our custom initialization Gradle script to block repositories that we don't allow.

### Steps to Reproduce

`context/context.gradle`
```groovy
subprojects {
    apply plugin: "java"

    repositories {
        maven {
            <repository declaration here>
        }
    }
}
```
`context/context/first.gradle`
```groovy
dependencies {
    implementation 'com.example:dependency:1.0.0'
}
```
`settings.gradle`
```groovy
dependencyResolutionManagement {
    repositories {
        maven {
            <repository declaration here>
        }
    }

    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
}
```

### Gradle version

7.4

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.
