### ISSUE TITLE
Convert `buildSrc` to be an implicit, included build

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2531]
Note that if `buildSrc` is included within `gradle.includedBuilds`, then the BuildScan plugin will no longer have a way to identify a composite build.

There wouldn't be any substitution as such. Instead, this would be making the existing cross build dependency explicit to pick up all the other good stuff that composite builds provides (or will provide): visibility in the IDE model and events, sharing configuration between the main build and buildSrc build through configuration injection (or whatever mechanism), addressing the tasks of the buildSrc build from the main build and command-line, visibility in build scans, being able to lifecycle buildSrc outputs (publish them for example) and so on.

It would also open the door to dependency substitution in build logic classpaths (eg use a plugin instance built locally instead of from a binary repo).

---

@oehme commented on [Fri Aug 26 2016](https://github.com/gradle/composite-builds/issues/66#issuecomment-242695126)

I think plugin dependencies are already substituted when you have the plugin locally in your composite.

---

@big-guy commented on [Mon Mar 27 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-289506977)

And this would hopefully remove the need for nasty hacks like this: https://github.com/gradle/gradle/pull/1622

---

@adammurdoch commented on [Mon Apr 17 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-294620766)

Rather than treat this as a single large piece of work (which we'll probably never do), we should instead make sure that each feature we implement for composite builds works with all _nested_ builds rather than just _included_ child builds, where it makes sense for that feature. Given that `buildSrc` and included builds are different kinds of nested builds, this means that we'll incrementally close the gap between `buildSrc` and composite builds.

For example, IDE integration or configuration injection or dependency substitution or addressing tasks from the command-line would all make sense for nested builds.

---

@adammurdoch commented on [Mon Apr 17 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-294620983)

Of course, another approach would be to leave `buildSrc` alone and deprecate it as a thing, once an included build can contribute to the build script classpath of another build.

---

@oehme commented on [Mon Apr 17 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-294678973)

@adammurdoch included builds can already contribute to the buildscript classpath of other builds.

---

@adammurdoch commented on [Tue Apr 18 2017](https://github.com/gradle/composite-builds/issues/66#issuecomment-295027130)

Perhaps we should think about a soft deprecation of `buildSrc` then, for example by starting to change the guides/user guide/samples to use a composite build instead of `buildSrc`.

**Comment by LouisCAD** [comment]
Can't we simply have an option we can define in `settings.gradle(.kts)` to make `buildSrc` be treated as an includedBuild?

**Comment by realdadfish** [comment]
Any plans going forward here? I just learned by accident that included builds might be the rescue for my `buildSrc` pain, up until now I used them soley for compositing external git repos and wasn't aware that they can be used to provide dependencies for the build classpath.

**Comment by pioterj** [comment]
We are looking into this now and should have some news / recommendations to share soon. cc @big-guy @jjohannes

**Comment by ingokegel** [comment]
It's great that this will be implemented in 6.7, but unfortunately IntelliJ IDEA cannot handle the feature yet, for example when opening the new [example project](https://docs.gradle.org/6.7-rc-1/samples/sample_sharing_convention_plugins_with_build_logic.html).

Are you in contact with JetBrains to get this implemented?

**Comment by jjohannes** [comment]
Thanks for reporting @ingokegel. I can confirm that this is not working in IDEA with the linked sample. Seems we missed it. We are in touch with JetBrains. I'll post an update here once there are any news.

**Comment by ingokegel** [comment]
Wow this is fast: https://youtrack.jetbrains.com/issue/IDEA-250774

**Comment by ingokegel** [comment]
Unfortunately, only plugin substitution was implemented and dependency substitution in buildSrc still breaks the import.

I have created an issue with an example project: https://youtrack.jetbrains.com/issue/IDEA-252140

Anybody from Gradle who can add their voice to this issue?

**Comment by ingokegel** [comment]
Good news, https://youtrack.jetbrains.com/issue/IDEA-252140 is fixed in 2020.3.1 so dependency substitution in buildSrc now works as well.

**Comment by jjohannes** [comment]
One aspect here is also that the dependency on buildSrc from the root project should appear in buildEnvironment and in build scans.

**Comment by Sineaggi** [comment]
Can we un-stale this?

**Comment by jjohannes** [comment]
I would like to see this change _soonish_. In particular to guide new users into the best direction.

I am happy to provide a PR if this change is desired.

**Comment by adammurdoch** [comment]
This is more or less implemented now in Gradle 8.0, via https://github.com/gradle/gradle/pull/22540.

I'm going to close this issue now. There are still some differences between buildSrc and included plugin builds, please raise new issues to have each of those differences addressed.

**Comment by cortinico** [comment]
> There are still some differences between buildSrc and included plugin builds, please raise new issues to have each of those differences addressed.

Thanks for the update @adammurdoch. Could you briefly clarify which are those differences?

**Comment by TWiStErRob** [comment]
@cortinico it's in the PR OP.
