### ISSUE TITLE
Collect use-cases needed by the Kotlin JVM plugin for Project Isolation

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#25327]

**Comment by h0tk3y** [comment]
- `org.jetbrains.kotlin.gradle.plugin.PropertiesProvider` looks properties up dynamically
  - This should be possible to fix using the `providers.property` API, if it is still allowed with PI and if its behavior fits the use case.
- The code that prepares the incremental compilation info accesses tasks in the task graph
  - https://github.com/JetBrains/kotlin/blob/60016d3e5bb7c58d54bff3c082edfd53d0086218/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/compilerRunner/GradleKotlinCompilerRunner.kt#L319- 
- [Support configuration cache and project isolation for FUS statistics](https://youtrack.jetbrains.com/issue/KT-58768/)
  - Accessing the opt-out flag should be possible to fix using the `providers.property` API, if it is still allowed with PI.
  - The code also crawls over the task graph and all projects to collect the metrics.
    - https://github.com/JetBrains/kotlin/blob/833b5c12a1d35fb1e4902a17aed85a6d5e472c5e/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/plugin/statistics/KotlinBuildStatHandler.kt#L84
  - There's also a configuration input related to `~/.gradle/...` contents
  - May need more clarification from the KGP maintainers

**Comment by bamboo** [comment]
@gavra0 told us in the last sync that the current _incremental compilation info_ implementation will be removed soon. We should understand what the new structure will require.

**Comment by gavra0** [comment]
WRT Kotlin IC `buildModulesInfo` from `GradleKotlinCompilerRunner.kt` should not even run by default from KGP 1.8.20 as the new IC is being used. The new IC is fully  compatible with project isolation as it transforms classpath and extracts ABI with artifact transforms.

**Comment by h0tk3y** [comment]
@gavra0 Thanks, that's good to know! However, KGP still has use cases for transferring data between project boundaries in the Multiplatform plugin and analytics.
