### ISSUE TITLE
Allow tasks in an included build to be executed directly from composite build command line

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2533]
@bigdaz commented on [Thu Jul 21 2016](https://github.com/gradle/composite-builds/issues/42)

For example, allow `gradle my-included-build::task-name` to be executed in the root of a composite build.

**Comment by rgoldberg** [comment]
Will this not be implemented?

**Comment by jjohannes** [comment]
Related: Execute tasks of included build via TAPI (https://github.com/gradle/gradle/issues/14117)

**Comment by Vampire** [comment]
This is currently being addressed in #14894

**Comment by donat** [comment]
Closing as implemented.

The main difference between the proposal and the new implementation is that included builds can be references the same way as subprojects: `gradle :included-build:sub:myTask`.
