### ISSUE TITLE
TestSuite dependencies should allow the use of Catalog Bundles

### ISSUE THREAD

**Issue by MariusVolkhart** [gradle/gradle#25334]
### Expected Behavior

`JvmTestSuite` dependencies use a `DependencyAdder` to add `implementation` dependencies. The `DependencyAdder` does not have an overload for a `Provider<ExternalModuleDependencyBundle>`. This means Catalog Bundles can't be easily applied the way they can in the project `dependencies` block.

```kotlin
testing.suites.register<JvmTestSuite>("testDatabase") {
	dependencies {
		// This works
		implementation(libs.log4j.core)

		// This doesn't work
		implementation(libs.bundles.testcontainers)

		// This is a workaround
		libs.bundles.testcontainers.get().forEach { implementation(it) }
	}
}
```

Gradle version: 8.1.1
Kotlin build script

### Context

I just think the TestSuite `dependencies` block should work as well with Catalogs as project-level `dependencies`, otherwise TestSuites are kind of second-class.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

**Comment by big-guy** [comment]
Due to the way bundles are implemented, we couldn't support the notation `implementation(libs.bundles.testcontainers)` in the test suite dependencies block.

You need to use `bundle(...)`, so this should work in your example:
`implementation(bundle(libs.bundles.testcontainers))`

https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#sec:differences_with_top_level_dependencies

**Comment by Zordid** [comment]
> Due to the way bundles are implemented, we couldn't support the notation `implementation(libs.bundles.testcontainers)` in the test suite dependencies block.
> 
> You need to use `bundle(...)`, so this should work in your example: `implementation(bundle(libs.bundles.testcontainers))`
> 
> https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#sec:differences_with_top_level_dependencies

Which version of Gradle will support `bundle` function? 8.4 does not.

**Comment by Zordid** [comment]
Ok, I see the mistake. Your comment is wrong. It's `implementation.bundle(...)` and not `implementation(bundle(...))`...

**Comment by Zordid** [comment]
While we are at this, I still look for an easy way to add a dependency for my integration test to the normal test source set. I do not know how to add this and I cannot figure out which dependency relation those have.
So, within 
```
testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter(libs.versions.junit.get())
        }

        val integrationTest by registering(JvmTestSuite::class)
        integrationTest {
            dependencies {
                implementation(project())
                // what to put here to depend on test??
            }
        }
    }
}
