### ISSUE TITLE
Test assertion failure reported incorrectly in the Tooling API

### ISSUE THREAD

**Issue by HackerMadCat** [gradle/gradle#25350]
### Expected Behavior

[JUnitTestEventAdapter#getValueOfStringField](https://github.com/gradle/gradle/blob/eb4ff204762719a09b5dbdc8beb0e1b7311c9496/subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java#L107) should extract correctly expected and actual data from `junit.framework.ComparisonFailure` for failure which extends `junit.framework.ComparisonFailure`.

### Current Behavior

[JUnitTestEventAdapter#getValueOfStringField](https://github.com/gradle/gradle/blob/eb4ff204762719a09b5dbdc8beb0e1b7311c9496/subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java#L107) returns null for failure which extends `junit.framework.ComparisonFailure`.

### Context (optional)

Intellij IDEA has custom Junit comparison exceptions. For example, FileComparisonException which extends `junit.framework.ComparisonFailure`. Gradle [JUnitPlatformTestExecutionListener](https://github.com/gradle/gradle/blob/eb4ff204762719a09b5dbdc8beb0e1b7311c9496/subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java#L127) for Junit 5 extracts expected and actual data. But [JUnitTestEventAdapter](https://github.com/gradle/gradle/blob/eb4ff204762719a09b5dbdc8beb0e1b7311c9496/subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java#L41) uses `comparisonFailure.getClass().getDeclaredField(name)` for accessing private fields "fExpected" and "fActual". It fails with `java.lang.NoSuchFieldException` exception for objects with type: `FileComparisonException`.

### Steps to Reproduce

1. Download and open sample project in Idea [gradle-junit-4-demo.zip](https://github.com/gradle/gradle/files/11708772/gradle-junit-4-demo.zip);
2. Attach Gradle sources as project library into IDEA project or open Gradle in separate Idea window;
3. Put breakpoint into `org.gradle.api.internal.tasks.testing.junit.JUnitTestEventAdapter#getValueOfStringField`;
4. Run test in sample project;
5. Attach remote debugger (You need to create `Remote JVM Debug` run configuration if you use separate project);
<img width="1342" alt="image" src="https://github.com/gradle/gradle/assets/11194423/46ddf4d1-8776-4a28-9342-cee342575fb8">
6. See result of `getValueOfStringField` evaluation
<img width="1760" alt="image" src="https://github.com/gradle/gradle/assets/11194423/97aaaf8a-fa97-4473-89c2-71e49dbe148f">

### Gradle version

8.0

**Comment by ljacomet** [comment]
Can you please try with Gradle 8.1.1 or 8.2 RC2?

**Comment by HackerMadCat** [comment]
@ljacomet Yes it is reproduced on Gradle 8.2-rc-2
<img width="2000" alt="image" src="https://github.com/gradle/gradle/assets/11194423/b9419b44-4665-4f6b-a145-66dd2ca592d1">
<img width="1982" alt="image" src="https://github.com/gradle/gradle/assets/11194423/20b20cf8-bcfd-46a5-a527-9192d86e6010">

**Comment by hegyibalint** [comment]
Hi! 👋 

We've been working in the past weeks to introduce OpenTest4J assertions, and as a consequence, we completely reworked how assertions are processed.

Now, instead of working with fields, [`JUnitComparisonFailureMapper`](https://github.com/gradle/gradle/blob/donat/tapi/testinfo/subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/failure/mappers/JUnitComparisonFailureMapper.java) now works by using the public methods.

I've added your test case based on your reproducer to the PR: https://github.com/gradle/gradle/pull/25382/commits/a8d961c2a4667fbd05947908732397c203461da9
