### ISSUE TITLE
deconfuse -Xlint:deprecation

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#25356]
### Expected Behavior

what is written in the output as option can be really passed as option.

### Current Behavior

trying to blindly follow the output results in an error:
```
❯ gradle clean build

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

❯ gradle clean build -Xlint:deprecation

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :build from command line.
> Unknown command-line option '-X'.
```

### Steps to Reproduce

n/a

### Gradle version

8.1.1

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

What you see is the output of the Java compiler. So the advice need to be applied to the configuration of the `compileJava` task.
