### ISSUE TITLE
malformed lockfile when guava-32 is on the classpath

### ISSUE THREAD

**Issue by MatanSabag** [gradle/gradle#25378]
### Expected Behavior

After resolving locks (`./gradlew resolveAndLockAll --write-locks`) I will be able to build the project successfully. 

### Current Behavior

After resolving locks, I am running the build and it fails on one of the subprojects with the following error:

```
* What went wrong:
Could not determine the dependencies of task ':gcs-client:test'.
> Could not resolve all task dependencies for configuration ':gcs-client:testRuntimeClasspath'.
   > Resolved 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava' which is not part of the dependency lock state
```

I noticed that the lockfiles contains the following lines related to guava:

```
com.google.guava:guava:31.0.1-jre=annotationProcessor,errorprone,testAnnotationProcessor
com.google.guava:guava:31.1-jre=compileClasspath,implementationDependenciesMetadata
com.google.guava:guava:32.0.0-android=testCompileClasspath,testImplementationDependenciesMetadata
com.google.guava:guava:32.0.0-jre=default,runtimeClasspath,testRuntimeClasspath
```

If i'm modifying the `build.gradle` files and adding `testImplementation("com.google.guava:guava:31.1-jre") {force = true}`, the locks change to the following: 

```
com.google.guava:guava:31.0.1-jre=annotationProcessor,errorprone,testAnnotationProcessor
com.google.guava:guava:31.1-jre=compileClasspath,implementationDependenciesMetadata,testCompileClasspath,testImplementationDependenciesMetadata,testRuntimeClasspath
com.google.guava:guava:32.0.0-jre=default,runtimeClasspath
```

**and now the build passes successfully**

While this is a workaround, this is something we want to avoid (using "force") and lockfiles are inherent parts of our builds so we can't give them up. 

Any idea?

### Steps to Reproduce

Internal project, I can't share, if needed I will try to reproduce but i'm not sure how easy it is. 

### Gradle version

7.6.1

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
