### ISSUE TITLE
gradle 4.0.1 sets javac --source-path option which is not compatible with --module-source-path (JDK9)

### ISSUE THREAD

**Issue by prrace** [gradle/gradle#2537]
gradle 4.0.1 appears to set the --source-path when passing flags to javac.
Since JDK 9 supports the mutually exclusive --module-source-path flag this can lead to
failing builds.

The JavaFX component of JDK 9 has been unable to upgrade the version of gradle it uses to build
JDK 9 since before 3.4 - which seems to be the approximate release that introduced this, since
3.2 works.

### Expected Behavior
For gradle to support JDK 9 and later it needs to handle the --module-source-path option
in some way. Whether it is by not providing the conflicting --source-path option, at least
if the gradle build script is already specifying --module-source-path or by
specifying --module-source-path in some gradle aware way.

### Current Behavior
Build fails with
 javac: cannot specify both --source-path and --module-source-path 
### Context
This is a blocker for using gradle with JDK 9 and above.

### Steps to Reproduce (for bugs)
Download the javafx source from hg.openjdk.java.net/openjfx/9 and try to build
it with current gradle.
Also see https://bugs.openjdk.java.net/browse/JDK-8177778

**Comment by prrace** [comment]
This still fails with the 4.1 snaphot gradle-4.1-20170718061434+0000-bin.zip

**Comment by melix** [comment]
@eljobe would you mind checking this issue?

**Comment by eljobe** [comment]
I'm on it.  My plan is to detect `--module-source-path` and silently remove `-sourcepath` or `--source-path` if they have been added by Gradle's logic. I think it also makes sense to emit a warning if the user has explicitly specified both options but still just strip the `-sourcepath` or `--source-path` options when both are specified.

**Comment by melix** [comment]
@eljobe @eriwen worth delaying 4.1-rc-1?

**Comment by eljobe** [comment]
Tough call. I can imagine other java 9 developers wanting to be able to specify the `--module-source-path` flag if they are compiling multiple modules from the same Gradle project. But, I think we anticipated that most Gradle projects would map to exactly one Gradle project, so I think the use of that flag can be considered an advanced feature. As such, I'd be okay delivering this fix in `4.2`. But, it's also a pretty simple fix (should be done in the next hour or two.) So, maybe we should put it in `4.1` and have better support for this use case.

**Comment by melix** [comment]
This fix would unblock the JDK team, so I would consider it in 4.1.

**Comment by prrace** [comment]
Is there a snapshot build with this fix (and I guess that would also include the fix for
https://github.com/gradle/gradle/issues/2454) that I can try to see if it works .. or
if there is some other next blocker ?

**Comment by jjohannes** [comment]
@prrace We just release 4.1 RC1 which includes both fixes. Please let us know if it works for you!

https://discuss.gradle.org/t/gradle-4-1-rc-1-is-now-available-for-testing

**Comment by prrace** [comment]
A bit slow to reply but I have tested this and it does solve the problem. I needed to adjust
our build script to handle the updated default output build directories for 4.x which slowed me down a bit.
