### ISSUE TITLE
java-gradle-plugin plugin adds gradleApi() dependencies to api configuration

### ISSUE THREAD

**Issue by stefanrybacki** [gradle/gradle#25406]
### Expected Behavior

the gradleApi() dependency is only added to compileOnly

### Current Behavior

gradleApi() dependency is added to api configuration and cannot be execluded in dependent projects, which leads to e.g. poluting other projects classpath with unwanted Sl4j bindings

see Docu for info
![image](https://github.com/gradle/gradle/assets/29799350/a62b021b-608c-4424-909c-52158fec6ed2)

### Steps to Reproduce

* create gradle composite project with
* a gradle plugin (1) project using java-gradle-plugin plugin
* another project (2) in the composite project depending on the plugin project (1) and setup logback slf4j logging
* see something like the following then:
![image](https://github.com/gradle/gradle/assets/29799350/0153a706-ebca-47de-82aa-317d9cfac44f)

### Gradle version

7.4.2

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

----

Gradle is a runtime environment. If you have code in your "plugin" project that needs to be used by another project that doesn´t run in the Gradle environment then you should extract it to a third project.

**Comment by stefanrybacki** [comment]
Thank you for your answer, I still do not understand why it needs to be api and why implementation is not enough though

**Comment by eskatos** [comment]
You would have the same issue with `implementation`. The `java-gradle-plugin` plugin uses `api` because plugin code exposes Gradle types.

**Comment by mymx2** [comment]
For those encountering the same issue:

```Bash
LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.gradle.internal.logging.slf4j.OutputEventListenerBackedLoggerContext loaded from file:/C:/xxxx/.gradle/caches/8.6/generated-gradle-jars/gradle-api-8.6.jar).
```

If you are also using [publish-plugin](https://plugins.gradle.org/plugin/com.gradle.plugin-publish), you can try using an alternative plugin [publish-plugin](https://plugins.gradle.org/plugin/io.github.gradle-nexus.publish-plugin).
