### ISSUE TITLE
Some artifacts from Ivy module don't get refreshed

### ISSUE THREAD

**Issue by ZsoltGalambos** [gradle/gradle#2540]
Some of the changing dependencies from a multi-artifact ivy module are not refreshed properly sometimes.

### Context
Ivy module in remote repository:

my-service, version: 1.17-latest, multiple artifacts:
-> contract (my-service-contract-1.17-latest.jar)
-> impl (my-service-impl-1.17-latest.jar)
-> ...
If such a module is built, all artifacts are created and published again, furthermore e.g. build date is stored in MANIFEST.MF meaning SHA-1 hash is always changing.

Gradle modules (v 3.5):
- my-lib, dependencies: my-service-contract (changing)
- my-web, dependencies: my-lib (project), my-service-impl (changing)

### Current Behavior
In some cases only my-service-contract (+ ivy-1.17-latest.xml) is downloaded from the Ivy repo when building the Gradle modules, my-service-impl stuck with old version. As I see in the debug build logs (attached), the -impl dependency is not even checked whether it's expired, I guess based on the refreshes of ivy.xml/-contract it's considered up-to-date without any check.

I also implemented a check that compares the SHA-1 hash of the dependency .jar with the latest version stored in the Ivy repo when assembling my-web, it also confirms that only some of the artifacts are refreshed...
[buildlog.zip](https://github.com/gradle/gradle/files/1161643/buildlog.zip)

### Expected Behavior
- all king of changing dependencies are refreshed correctly

**Comment by bmuschko** [comment]
Did you [configure the TTL for your changing dependencies](https://docs.gradle.org/current/userguide/dependency_management.html#sec:controlling_caching) as described in the user guide. If you do could you please post your build file?

**Comment by ZsoltGalambos** [comment]
TTL is configured like this:

            project.configurations.all {
                resolutionStrategy.cacheChangingModulesFor 30, 'seconds'
                resolutionStrategy.cacheDynamicVersionsFor 30, 'seconds'
            }

Regarding the build file, well, I'm afraid I'm not allowed the share the whole script set. Could you please tell which part(s) you are interested?

Does the attached build log help?

Btw, when using --refresh-dependencies the SHA-1 check I mentioned above never fails...

**Comment by bmuschko** [comment]
Thanks, I was mostly interested in TTL configuration you have in place. Could you also talk about how you apply the code you posted above? I suspect that you only add and apply it to the root project of your multi-project build. AFAIU you want to apply it to all Java subprojects:

```
subprojects {
    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 30, 'seconds'
        resolutionStrategy.cacheDynamicVersionsFor 30, 'seconds'
    }
}
```

You might want to give that a shot. If you already happen to have these settings then we'll need to dig deeper.

**Comment by ZsoltGalambos** [comment]
Well, I can try explaining... First of all, yes, we have a huge multi-project build, with sub-projects that can also be built one-by-one, so not relying on any setting of the root project. There's a tweak that detects whether some well-known dependencies (aka, the sub-project) are available as project dependency, otherwise it configured as external dependency. In order not to multiply the build scripts we implemented couple of plugin-ins, each sub-project applies e.g. the 'build-lib' plug-in + defines the dependencies.

TTL is applied by the plug-in, project-by-project, so the code in my prev. comment comes from a plug-in's apply(Project) method.

The issue occurs on our Jenkins that builds the whole project as multi-project (with project dependencies between sub-projects). It's important to note that Gradle-built artifacts are published to Nexus, the problematic artifacts are external dependencies coming from an Ivy repository.

I just added the code you suggested to our root project's build.gradle, although I think it's already set correctly (other dependencies confirm that, also, -contract artifacts from Ivy are refreshed correctly all the times)

**Comment by ZsoltGalambos** [comment]
Looked again the build logs, isn't up-to-date checked on SHA-1 of ivy-<version>.xml checked only, at not on the .jar itself? I mean, if ivy-<version>.xml is up-to-date, e.g. because it was updated when -contract was updated, but when processing -impl, ivy.xml is fresh so the .jar is not even checked?

**Comment by ZsoltGalambos** [comment]
Any news on this topic?

**Comment by ZsoltGalambos** [comment]
Same issue with Gradle 4.1

**Comment by bigdaz** [comment]
Thanks for your detailed report @ZsoltGalambos. I'm a bit stumped looking at your logs: it seems like you might have a single Ivy module `my-service:1.17-latest` with separate `contract` and `impl` configurations published to `ivy.xml`. Is that correct?

Anything you can do to isolate this into a reproducible example would really help. Without being able to reproduce the issue, we can't fix it. And we don't have the capacity to spend a lot of time trying to reproduce issues like this.

**Comment by jjohannes** [comment]
Closing this until we have a reproducible example.
