### ISSUE TITLE
Provide a help task to list unused entries in version catalog

### ISSUE THREAD

**Issue by jnehlmeier** [gradle/gradle#25400]
### Expected Behavior

It would be nice to have a help task that lists all unused entries of the version catalog for easy cleanup of the version catalog.

### Current Behavior (optional)

Currently you have to manually check entries in version catalog against all Gradle build files, which can be quite a few if you have many modules.

### Context

Having a large project with many modules can lead to a long version catalog as it lists dependencies of all modules combined. As time goes by entries of the version catalog may become unused if the project evolves and dependencies are replaced or simply not needed anymore. It is easy to forget to remove these dependencies from the version catalog. Also if you remove a dependency from one module, the dependency might still be used by other modules. So you would need to check that before removing the dependency entry from the version catalog. A help task would simplify that.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

**Comment by jvandort** [comment]
This is not something we plan to implement
