### ISSUE TITLE
Add a temporary flag to disable considering File.exists() checks for configuration cache input

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25418]
### Expected Behavior

I am able to upgrade from Gradle 8.0 to Gradle 8.1 with configuration cache enabled while using popular plugins such as Kotlin Gradle Plugin, Android Gradle Plugin, Protobuf Gradle Plugin.

### Context

Gradle 8.1 started detecting `File.exists()` and similar calls to consider these files as input to configuration cache computation (yay). Sadly, there are many plugins in the ecosystem that now break configuration caching as it checks for existence of files in Gradle User Home or buildDir causing configuration cache invalidations.
 
- Android Gradle Plugin hotlist https://issuetracker.google.com/hotlists/5093540
- protobuf gradle plugin https://github.com/google/protobuf-gradle-plugin/issues/711
- Kotlin gradle plugin (yet to file the issue)

It will take a while for all of these bugs to be fixed. It would be awesome to add an escape hatch for this `org.gradle.configurationcache.ignorefilereadspleaseokthanks=true` to allow people to continue upgrading

**Comment by liutikas** [comment]
Another reason why this is important is that Android Gradle Plugin 8.1 requires Gradle 8.1 which will force folks to upgrade and hit all these issues. Without this escape hatch folks are not going to be able to move forward without taking configuration cache misses as a result.

**Comment by ZacSweers** [comment]
Another example of where this is problematic - the community obviously needs more time to prepare and even basic tooling in plugins like the Android Gradle Plugin are bitten by this if they use lock files.

```
Calculating task graph as configuration cache cannot be reused because the file system entry '../../../../.gradle/android.lock' has been created.
```

**Comment by h0tk3y** [comment]
See the spec for the fix of this issue: https://docs.google.com/document/d/17_421Wl3JAVCKVkzICIyS4n7XlxFMXZpSC9SBgPs1Pg/edit#heading=h.610fausqnpu6
