### ISSUE TITLE
HTTP cache push parameter

### ISSUE THREAD

**Issue by Anigif** [gradle/gradle#25415]
### Issue type

Missing information

### Problem description

This guide describes how to setup your client to use a HTTP cache: https://docs.gradle.org/current/userguide/build_cache.html

It mentions the `push`-parameter as a sidenote. But it's default `false` (I think becase it's not set by default) and thus the cache won't make sense to use if it's not set to `true`.

So my suggestion is to either make it default `true` or update the documentation should to mention that parameter from the start.

### Context (optional)

I was trying to call our http cache, but it didn't look like the build was faster and there were no entries in the remote cache.

### Page with the problem

https://docs.gradle.org/current/userguide/build_cache.html

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

----

This is actually explained in that section https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_configure

Agreed that it should be mentioned earlier in that chapter, probably in `Enable the Build Cache` section.

**Comment by Anigif** [comment]
Thanks for your response. It was also there I finally found out about the `push` parameter, but it was a bit "hidden", so sounds awesome you'll adress this.

**Comment by lptr** [comment]
Remote build cache makes sense in an environment where you have CI to upload things to the remote cache that developers (and other CI builds) can consume. We have a section describing how to set up remote caches for CI here: https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_configure_use_cases

**Comment by Anigif** [comment]
@lptr Did you at all read my suggestion or this thread? When setting up the remote cache, I spent a lot of time not figuring out why nothing worked until I found the second to last example that describes the most essential part of any cache - if you don't push to it, it doesn't make sense to have a cache at all. So my suggestion is to move that part up earlier in that section.

**Comment by lptr** [comment]
Would you be willing to provide a PR?
