### ISSUE TITLE
Tests are skipped when maxParallelForks number is low

### ISSUE THREAD

**Issue by lazar725** [gradle/gradle#25426]
### Expected Behavior

Should run all tests in tests folder

### Current Behavior

I have a Spring Boot app with Gradle and a few dozens of tests. The tests are divided into packages and all packages are located under the standard tests folder. Some of the tests run [test containers](https://java.testcontainers.org/). The build.gradle file contains a setting for maxParallelFork:

` useJUnitPlatform {
        maxParallelForks = 1
}`

I noticed that when maxParallelForks = 1, about half of the tests are simply skipped. When I open the Gradle test report, the tests are not marked as skipped, but simply don't appear in the report at all. When maxParallelForks is equal to half of the number of available processors, most of the tests are executed, but still some are skipped. Only when maxParallelForks is equal to the number of available processors, all tests are run and pass:

` useJUnitPlatform {
        maxParallelForks = Runtime.runtime.availableProcessors()
}`

That makes me wonder though, what will happen when more and more tests will be added, and the number of available processors won't be enough so tests again will get skipped.

My machine:
MacOS Apple M1 Pro, Ventura 13.4

Gradle 7.5.1
Spring Boot 2.7.12
Junit 5

### Steps to Reproduce

Create a few dozens of integration tests with test containers and run them with different values of maxParallelForks, preferably on Apple M1 Pro.

### Gradle version

7.5.1

**Comment by ljacomet** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
