### ISSUE TITLE
Check task no longer implicitly run in buildSrc

### ISSUE THREAD

**Issue by twbecker** [gradle/gradle#25439]
### Expected Behavior

We have a plugin setup to lint the contents of buildSrc when running `buildSrc:check`. This used to be run implicitly when running `build` on the main project, but that appears to no longer be the case in Gradle 8.1.1. I can't find any documentation wrt what tasks are actually run in the buildSrc project. 

### Current Behavior

Normal lifecycle tasks (e.g. build) for the buildSrc project seem not to be run by the main build. Trying to introduce a dependency with something like the following doesn't work either:
```kotlin
tasks.check {
    dependsOn("buildSrc:check")
}
```

### Steps to Reproduce

* Add a task that runs on `check` to buildSrc
* Build the main project
* Note your task does not run.

### Gradle version

8.1.1

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

---

This is a breaking change in Gradle 8.0 that is documented in the [upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_7.html#gradle_no_longer_runs_the_build_task_for_buildsrc_builds).
