### ISSUE TITLE
Add `MAVEN_CENTRAL_OVERRIDE_URL_PROPERTY` and `GOOGLE_OVERRIDE_URL_PROPERTY` 

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#25449]
### Expected Behavior

Similar to `PLUGIN_PORTAL_OVERRIDE_URL_PROPERTY`, please provide a `MAVEN_CENTRAL_OVERRIDE_URL_PROPERTY` property and a `GOOGLE_OVERRIDE_URL_PROPERTY` 

See https://github.com/gradle/gradle/blob/be698f4d3787fb0a96566703c210c439d43a2371/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/BaseRepositoryFactory.java#L29

Implementation would be here: 
https://github.com/gradle/gradle/blob/49e767c3f0b25154927fe2bf6a9b4db2c4a4cf56/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultBaseRepositoryFactory.java#L142-L176

### Current Behavior (optional)

The URLs for `mavenCentral()` and `google()` are hard coded with no way to override them. 

https://github.com/gradle/gradle/blob/49e767c3f0b25154927fe2bf6a9b4db2c4a4cf56/subprojects/core-api/src/main/java/org/gradle/api/artifacts/ArtifactRepositoryContainer.java#L52-L53

### Context

This would allow a work around for `gradle init` which uses `mavenCentral()` 
https://github.com/gradle/gradle/issues/4195

**Comment by ChristianCiach** [comment]
Yes please! And while you are at it, please promote these variables as a stable feature and officially document them.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle.

This is very unlikely to happen. We do not want an ability to have declared repositories actually talk to a different URL than what Gradle advertises. 

However we are aware that configuring repository for both the open world and a company internal repository is not as easy as it could be.

If you think we are missing a reason for considering this feature, please explain your use case.

**Comment by sphanley** [comment]
> However we are aware that configuring repository for both the open world and a company internal repository is not as easy as it could be.

@ljacomet, are there any resources on how to set a project up to work both in the open world and internally? My team is preparing to open-source a Gradle project, and we're struggling to figure out how to offer a clean version of the codebase that can be run in the "real world" while also ensuring that we can internally override the repositories with our private mirror. Something like this feature request, along with properties to optionally provide credentials, would make our use case massively more intuitive and easier.

**Comment by githendrik** [comment]
> @ljacomet, are there any documentation resources on how to set a project up to work both in the open world and internally with the current capabilities?

For most cases, this can help: https://docs.gradle.org/current/userguide/init_scripts.html#sec:init_script_plugins - you'd have your code set up so that it can build externally, but override the repos in an init script.

Or, your could parametrise your repo definition to allow for overrides with if / else statements.
