### ISSUE TITLE
Support Codenarc IDE-friendly output

### ISSUE THREAD

**Issue by ysb33r** [gradle/gradle#25452]
### Expected Behavior

Would like to be able to do

```groovy
tasks.named('codenarcMain',CodeNarc) {
  reports.getByName('ide').configure {
    required = true
  }
}
```

Having that can produce clickable links in IDEs such as Intellij when the build is run with `--info`

![image](https://github.com/gradle/gradle/assets/907624/60b15d0b-aa77-4f55-9c75-dc12ae3333ea)

### Current Behavior (optional)

Currently CodeNarc supports Xml, Html, Text & Console reports. Even though the latter is not specified in the `CodenarcReports`  interface, it is obtainable via `getByName('console') and can thus be configured and enabled.

### Context

This feature enhances Groovy dev productivity a lot as it is not necessary to open the COdeNarc report. INstead, one can just link in the console output.

Prior to Gradle 8.0 there was a way of hacking the DSL with the following

```groovy
tasks.withType(CodeNarc) { codenarcSourceSetTask ->
    def reportName = (codenarcSourceSetTask.name - 'codenarc').uncapitalize()
    def ideReport = reports.add(org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport, 'ide', reports.task)
    ideReport.enabled = true
    ideReport.destination = file( "${project.codenarc.reportsDir}/${reportName}.ide.txt")
}
```

and that would have achieved this result. It is still possible to get a nasty workaround in Gradle 8.x by doing

```groovy
tasks.withType(CodeNarc).configureEach { t ->
    ((org.gradle.api.plugins.quality.internal.CodeNarcReportsImpl)t.reports).add(TaskGeneratedSingleFileReport, ["ide", t] as Object[])

    final baseDir = project.extensions.getByType(ReportingExtension).baseDirectory
    final reportName = (t.name - 'codenarc').uncapitalize()

    t.reports.getByName('ide').configure {
        outputLocation = baseDir.file("codenarc/${reportName}.ide.txt")
        required = true
    }
}
```

Having this productivity supported natively in Gradle would be great. It should be achievable by updating the constructor of `CodeNarcReportsImpl` to have 

```java
this.add(TaskGeneratedSingleFileReport.class, new Object[]{"ide", task});
```

**Comment by big-guy** [comment]
This is what the console looks like today:
https://ge.gradle.org/s/cldqagjyfyclw/console-log?task=:core-api:codenarcTest

This is what the console will be in 8.3:
https://ge.gradle.org/s/h3n2lw6tumoxy/console-log?task=:core-api:codenarcTest

Is this good enough @ysb33r?
