### ISSUE TITLE
jacoco-report-aggregation: allCodeCoverageReportSourceDirectories

### ISSUE THREAD

**Issue by daniel-shuy** [gradle/gradle#25459]
### Expected Behavior

`jacoco-report-aggregation` in Gradle `7` used to add the aggregated source directories in the `allCodeCoverageReportSourceDirectories` dependency configuration (https://docs.gradle.org/7.6/userguide/jacoco_report_aggregation_plugin.html#sec:dependency_management)

### Current Behavior

`allCodeCoverageReportSourceDirectories` was removed without warning in Gradle `8` (https://docs.gradle.org/8.0/userguide/jacoco_report_aggregation_plugin.html#sec:dependency_management)

### Context (optional)

The `allCodeCoverageReportSourceDirectories` dependency configuration is used by the [coveralls-jacoco](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin) plugin to configure the source sets for JaCoCo:
https://github.com/nbaztec/coveralls-jacoco-gradle-plugin/blob/eb7ddc648e22ffe2dbb016638946316c7f2f2a43/src/main/kotlin/SourceReportParser.kt#L77

Because of this, the plugin cannot be used with Gradle `8`

### Steps to Reproduce

https://github.com/daniel-shuy/jacoco-report-aggregation-allCodeCoverageReportSourceDirectories

### Gradle version

8.0

### Gradle version that used to work

7.6

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Gradle 8 is a major version and breaking changes are possible. However they should be documented. Asking the responsible team to clarify this.

**Comment by big-guy** [comment]
Sorry that we broke you. The JaCoCo aggregation plugin is incubating and can change.

In this case, the plugin no longer needed that configuration, so it was deleted. We're not going to add it back.

I'm not sure that the configuration really worked the way you wanted it to. I believe this call always fails when the project has dependencies on external libraries (not other projects):
https://github.com/nbaztec/coveralls-jacoco-gradle-plugin/blob/eb7ddc648e22ffe2dbb016638946316c7f2f2a43/src/main/kotlin/SourceReportParser.kt#L77

This is one of the reasons we removed the configuration and switched to using an `ArtifactView`:
https://github.com/gradle/gradle/blob/1b293f01ea9d3ac172d2363348677b28f1c9c82e/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/plugins/JacocoReportAggregationPlugin.java#L83-L91

I'm not familiar enough with the plugin to suggest a better change. You could replicate some of what `JacocoReportAggregationPlugin` is doing to resolve the source directories in the same way.

**Comment by daniel-shuy** [comment]
> I'm not sure that the configuration really worked the way you wanted it to. I believe this call always fails when the project has dependencies on external libraries (not other projects):
https://github.com/nbaztec/coveralls-jacoco-gradle-plugin/blob/eb7ddc648e22ffe2dbb016638946316c7f2f2a43/src/main/kotlin/SourceReportParser.kt#L77

I see, that explains another issue I've been having!

> This is one of the reasons we removed the configuration and switched to using an ArtifactView
I'm not familiar enough with the plugin to suggest a better change. You could replicate some of what JacocoReportAggregationPlugin is doing to resolve the source directories in the same way.

I see, I'll try this out, thanks!

**Comment by daniel-shuy** [comment]
@big-guy Thanks for the suggestion, it worked! I've created [nbaztec/coveralls-jacoco-gradle-plugin#62](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin/pull/62/files#diff-b5776d699cca8b55e1a278144318717a7e821a00f199e8c0ce31578e7cffb7caR88-R102) to add support for Gradle `8+` to the plugin.
