### ISSUE TITLE
Spike: Better Console display for tasks that run indefinitely

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2546]
### Expected Behavior
It would be nice if Gradle would indicate that it is "WAITING" while running an application server, just like we do when running `--continuous` build.

### Current Behavior
Tasks like `run` with Ratpack still say `XX% EXECUTING` and shows the timer. 

### Context
Would be nice to reuse some of the logic in `WorkInProgressRenderer` to trigger the `WAITING` behavior when we are given information that a task will start a server and never complete.

**Comment by big-guy** [comment]
+1 for making this better. 

`run` should probably be implemented as a kind of deployment (which is related to the poorly named #2336).

In that case, I imagine the behavior would be:
1. `run` creates a deployment
1. Build continues as normal
1. Build finishes
1. Do we have running deployments? 
   a. No, do nothing.
   b. Yes, wait for a stop signal (ctrl+d) and show `WAITING`.

This is effectively a "one shot" continuous build. I don't think we want to have some special `WAITING` state for tasks while a build is still running.

**Comment by bmuschko** [comment]
I am going to close this issue. @eriwen and I agree that we need stronger modeling for solving this problem effectively. It's something we don't want to tackle at the moment. @big-guy Thanks for the pointer to your thoughts. I think that makes a lot of sense.
