### ISSUE TITLE
Improve rendering of test names in rich console

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2547]
Gradle 4.1-rc-1 comes with this very nice view of tests being currently executed:

> Executing test com.foo.bar.SomeTest

However, given the width of a terminal, it's not uncommon to see actually this:

> :test: Executing test com.foo.some.very.long
> :test: Executing test com.foo.some.very.long
> :test: Executing test com.foo.some.very.long
> :test: Executing test com.foo.some.very.long

Where the output on wide terminal would be:

> :test: Executing test com.foo.some.very.long.pkg.SomeClassTest
> :test: Executing test com.foo.some.very.long.pkg.AnotherClassTest
> :test: Executing test com.foo.some.very.long.pkg.sub.SubTest
> :test: Executing test com.foo.some.very.long.other.package.FooTest

### Expected Behavior

We could make it more readable, by making the test class name more prominent. Some suggestions:

> :test: Executing test SomeClassTest (com.foo.some.very.long.pkg.SomeClassTest)
> :test: Executing test SomeClassTest (com.foo.some.very.long.pkg)
> :test: Executing SomeClassTest (com.foo.some.very.long.pkg.SomeClassTest)
> :test: Executing SomeClassTest (com.foo.some.very.long.pkg)
> :test: Executing test com.foo....SomeClassTest
> :test: Executing com.foo....SomeClassTest
> :test: Executing test ...long.pkg.SomeClassTest
> :test: Executing ...long.pkg.SomeClassTest

### Context

It's worth noting that the problem may not be specific to tests. Any long display line will be truncated to the end. We could split this ticket into 2 different issues:

. make tests more readable (this specific issue)
. make the console smarter about long lines

The 2d point may require some smarts about things that are relevant, and things that can be collapsed. Then the console would automatically pick collapsible parts of the message when the width is not enough to display the full message.

**Comment by bmuschko** [comment]
I guess another option would be to only render the first letter of a package name e.g. as seen in some logging frameworks.

> :test: Executing test c.f.s.v.l.p.SomeClassTest

Thinking about it more do you think we'll need the package at all? Maybe the class name is just good enough.

**Comment by eriwen** [comment]
I like it fellas. I might advocate for your suggestion @bmuschko if it's low-risk if there's another RC.

**Comment by bmuschko** [comment]
@eriwen Changing any of the proposed solutions above should be low risk.

**Comment by eriwen** [comment]
@bmuschko let's chat about picking this up for RC2 then :)

**Comment by melix** [comment]
I feel guilty for not suggesting this sooner :p

**Comment by eriwen** [comment]
I wish I'd thought of this, but at least we _might_ have a chance to improve it for 4.1

**Comment by bmuschko** [comment]
I created a pull request based on the [community feedback from the Twitter poll](https://twitter.com/gradle/status/888424343885160448). Pull request is here: https://github.com/gradle/gradle/pull/2578

**Comment by melix** [comment]
I get that the most voted option is "keep as is", but I think it doesn't
solve the problem that is explained in this ticket. It even makes it worse,
since the label is now even longer. I wouldn't be surprised most people
didn't even read the ticket when answering. On the other hand, the total of
other options is not for fully qualified class name, so I'd be in favor of
changing to:

MyTest (org.my.example)

which is the 2d most voted option (and was curiously far beyond the other
options for the first hours of the poll).

Le 24 juil. 2017 8:00 PM, "Benjamin Muschko" <notifications@github.com> a
écrit :

**Comment by eriwen** [comment]
@melix I think users have their reasons for preferring the format they chose, and I feel strongly that we should stick to what was voted lest users feel slighted. 

However, this doesn't prevent us from being smarter about shortening packages, or that we have to keep other parts of the format like "Executing test". 

Tell you what: I have in mind an algorithm that would optimize the length of test names (by omitting package names in the middle) such that they are very likely to be fully displayed on an 80-character wide terminal. Perhaps I could have a bit of fun implementing it for Gradle 4.2 (probably too risky for RC2). That would take into account everyone's concerns I think. What do you say?

**Comment by mark-vieira** [comment]
> @melix I think users have their reasons for preferring the format they chose, and I feel strongly that we should stick to what was voted lest users feel slighted.

By this logic all the folks that voted for a different result will _also_ feel slighted.

There are many ways to interpret this data. We lack context here, as we don't know _why_ folks voted one way or the other. It could simply be that they haven't not encountered the issue in this ticket, therefore see no reason to change existing behavior.

**Comment by bmuschko** [comment]
It looks like there are a look of different opinions about this topic. How about we do leave the display as it is right now for 4.1? Then in 4.2 we can make a deliberate change based on further internal discussion and the community feedback trying out the final version.

**Comment by bmuschko** [comment]
@eriwen Where do we stand with your change on this?

**Comment by eriwen** [comment]
@bmuschko My PR #2581 is ready for review. IIRC it has passed Stage 4 on CI. Any takers?

**Comment by eriwen** [comment]
We solved this by abbreviating the middle in #2581. Hope you like it @melix!
