### ISSUE TITLE
TYPESAFE_PROJECT_ACCESSORS: `rootProject` naming should not lead to `InvalidUserDataException`

### ISSUE THREAD

**Issue by LouisCAD** [gradle/gradle#25475]
### Expected Behavior

The `TYPESAFE_PROJECT_ACCESSORS` feature (currently in preview) should not try to validate the `rootProject` name as it's not involved in the generated accessors.

### Current Behavior

Having something like `rootProject.name = "Charts.kt-samples"` in the `settings.gradle.kts` file leads to the error below if you have `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")`:

```stacktrace
java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: Cannot generate project dependency accessors:
  - Cannot generate project dependency accessors because project 'Charts.kt-samples' doesn't follow the naming convention: [a-zA-Z]([A-Za-z0-9\-_])*
	at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.generateAccessors(DefaultDependenciesAccessors.java:156)
	at org.gradle.configuration.BuildTreePreparingProjectsPreparer.generateDependenciesAccessorsAndAssignPluginVersions(BuildTreePreparingProjectsPreparer.java:92)
	at org.gradle.configuration.BuildTreePreparingProjectsPreparer.prepareProjects(BuildTreePreparingProjectsPreparer.java:55)
```

### Context (optional)

I need the root project to include dots and dashes for branding consistency reasons, and avoid confusing users (it'll be open source).

### Steps to Reproduce

1. Create a new empty Gradle project with Kotlin DSL and open the `settings.gradle.kts` file.
2. Remove any `rootProject.name = "something"` statement.
3. Add `rootProject.name = "Charts.kt-samples"`.
4. Add `enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")`
5. Run Gradle on the project (e.g. running the `help` task), or perform a Gradle sync in IntelliJ IDEA

### Gradle version

8.1.1

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

---

Relates to
* #24295 

The root project name is involved in the accessors generation and follows the same name pattern validation as intended.
