### ISSUE TITLE
`compileKotlin` task of build with `kotlin-dsl` applied emits warnings when configuration-cache is enabled

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#25483]
### Expected Behavior

No warning as when the configuration-cache is disabled.

### Current Behavior

With the configuration cache the warning silencer is discarded

https://github.com/gradle/gradle/blob/20edc4fbec838b4d4aad55664ddbac5d5e62b23c/subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt#L80

and the task produces a large scary warning:

```
> Task :compileKotlin
w: ATTENTION!
This build uses unsafe internal compiler arguments:

-XXLanguage:+DisableCompatibilityModeForNewInference
-XXLanguage:-TypeEnhancementImprovementsInStrictMode

This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!
```

### Steps to Reproduce

* `git clone https://github.com/eskatos/issue-reproducers.git`
* `cd issue-reproducers/gradle-25483`
* `./gradlew compileKotlin`

### Gradle version

8.1.1

### Build scan URL (optional)

https://scans.gradle.com/s/jus72kvlg5kky/console-log?page=1#L7

**Comment by bamboo** [comment]
CC support for `Task.logging.captureStandardOutput()` is also missing, https://github.com/gradle/gradle/blob/4aba237c7ebe088fe691baa4b7befb9417c22d57/subprojects/logging/src/integTest/resources/org/gradle/internal/logging/LoggingIntegrationTest/logging/project1/build.gradle#L36-L41

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by yogurtearl** [comment]
If you modularize you `build-logic` it prints this out for every subproject. 

Are there any workarounds that would allow us to suppress this in 8.3 pending the real fix?

**Comment by viluon** [comment]
I think this problem reappeared in Gradle 8.13.
