### ISSUE TITLE
Improve usability of Play reload support

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#2549]
When using Play reload and continuous build, there are a few scenarios to consider:

1. Play application requests reload when there are no changes.
2. Play application requests reload when there are pending changes, but no build (but a build may be imminent).
3. Play application requests reload when there is a build in progress.
4. Play application requests reload when there is a build in progress and pending changes (which will cause another build).

For 1) we do the right thing, we do nothing.
For 2) we may miss changes because we'll treat this as a do-nothing case.
For 3) we do the right thing, we block until the build is ready.
For 4) we make it hard to know if the application is fully up-to-date (#2085).

Additionally, for 2-4, we may be doing unnecessary work if the user hasn't finished making changes and the build is expected to fail/not be used (captured as #2550)

**Comment by bmuschko** [comment]
@big-guy says that it can be closed.
