### ISSUE TITLE
jfrog jars missing from plugins.gradle.org/m2

### ISSUE THREAD

**Issue by BalakrishnaPro** [gradle/gradle#25507]
### Expected Behavior

Jfrog "build-info-extractor" jars under https://plugins.gradle.org/m2/org/jfrog/buildinfo/ should be present

### Current Behavior

Jfrog build-info-extractory folder is completely missing under https://plugins.gradle.org/m2/org/jfrog/buildinfo/ path and the folders related to its transitive dependencies.

### Context (optional)

We are currently consuming the dependencies directly from https://plugins.gradle.org/m2/ and we have observed from 23/06/2023 the afore mentioned folders are missing hence not able to download the required jars.
Our application runs on a build server which tries to download the jars from the site every time the build is triggered.

### Steps to Reproduce

Navigate to https://plugins.gradle.org/m2/org/jfrog/buildinfo/
check for "build-info-extractor" folder and its transitive dependent folders.

### Gradle version

4.0.1

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

You should not directly consume your dependencies from the Gradle Plugin Portal, but from jCenter.
But, having that said, on Friday JFrog suddenly decided to redirect everything to Maven Central, so there were issues with accessing artefacts that are available on jCenter, but not on Maven Central.
They have reverted this change for now, but they will most likely do it again in the future.

Further info:
* https://status.gradle.com/incidents/7x4wqd7zv715
* https://blog.gradle.org/jcenter-shutdown
