### ISSUE TITLE
Allow convention mapping to work with ConfigurableFileCollection properties

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#25509]
For requirements of supporting old plugins after lazy-migration, we have to support also ConfigurableFileCollection with convention mapping in the same way as we did for properties: https://github.com/gradle/gradle/pull/24582

**Comment by lptr** [comment]
This is a blocker for the provider API migration right now. We can't convert `AbstractCompile.classpath` because of this problem.

**Comment by abstratt** [comment]
This didn't make 8.7, but should be there in 8.8.
