### ISSUE TITLE
Warn if project in settings.gradle has a non existent project directory

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25531]
### Expected Behavior

If I have `settings.gradle` file that has
```
include ':doesntexist'
```

and there is no `doesntexist/` directory, Gradle should warn the user about it.

Gradle has implicit projectDir based on the project path, e.g. `:foo:bar` -> `foo/bar`. Creating a project has has non-existent directory is 99% likely to be a mistake.

### Context

We found that our developers kept making mistakes (e.g. typo in the project name) and they didn't realize that the project is not actually included. We added our own check for this in settings.gradle, but with configuration cache enabled on Gradle 8.1, these projectDir.exists() checks lead to treating the whole projectDir as input to the configuration cache. We'd like to remove our own check and have gradle do this checking for us in CC safe way.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

*** 

A warning is a good first improvement to add.

There could be a failure mode for this too, but it shouldn't be the default, because introducing it could be a breaking change for some users.

**Comment by bamboo** [comment]
I feel this belongs to a `Settings` convention plugin.  It could be achieved by validating the included projects in a `gradle.settingsEvaluated` callback handler, for example.

**Comment by adammurdoch** [comment]
I would make this an error (via deprecation), as we don't know of any real use cases for the lenient behaviour. It turns out there are some valid use cases, we can add something to solve them - possibly some lenient behaviour or possibly something else, depending on the use case.

**Comment by tomasbjerre** [comment]
> I would make this an error (via deprecation), as we don't know of any real use cases for the lenient behaviour. It turns out there are some valid use cases, we can add something to solve them - possibly some lenient behaviour or possibly something else, depending on the use case.

@gastendonk has a use his use case described above.

We are also doing something similar. We have about 100 Git repositories with pure API (OpenAPI specs). We generate code from the spec and publish some different artifacts with code from different generators. We don't want to create all these empty folders (one folder per generator in each repository), it would mean creating hundreds of empty folders in these repositories. I described this in #34655
