### ISSUE TITLE
Gradle-property-induced CC invalidations have an unhelpful error message

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#25541]
### Expected Behavior

I would expect it to tell me which properties have changes so I can diagnose the cause

### Current Behavior

The message just says that "the set of properties" changed, with no indication of which

```
Calculating task graph as configuration cache cannot be reused because the set of Gradle properties has changed.
```

### Context (optional)

A major issue with gradle is vague or opaque error messages that only indicate something is wrong but not enough context to be actionable. This is one example.

### Steps to Reproduce

Change a gradle property used as an input during a build with CC enabled

### Gradle version

8.2-rc-2

```[tasklist]
### Tasks
```

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

----

CC, do you need any additional information for this issue?

**Comment by BMukhtar** [comment]
any news on this issue, having the same problem ?

**Comment by mlopatkin** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by ZacSweers** [comment]
Two canned responses on the same issue 9 months apart feels like a sign that I should just close this.
