### ISSUE TITLE
org.gradle.api.tasks.WriteProperties.setOutputFile deprecated but no suggested alternative

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#25586]
### Issue type

Missing information

### Problem description

org.gradle.api.tasks.WriteProperties.setOutputFile methods are marked deprecated but there is no suggested alternative.

### Page with the problem

https://docs.gradle.org/8.2/javadoc/org/gradle/api/tasks/WriteProperties.html#setOutputFile-java.io.File-

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

The alternative is `destinationFile`.
