### ISSUE TITLE
[Gradle 4.0.1][AntlrTask]Provide some way to specify arguments for antlr

### ISSUE THREAD

**Issue by danielsun1106** [gradle/gradle#2559]
### Expected Behavior
I expect AntlrTask provide some way to specify arguments for antlr(e.g. https://github.com/apache/groovy/blob/master/subprojects/parser-antlr4/build.gradle#L33 )

### Current Behavior
No way to specify arguments for antlr

### Context
We can not specify package name of generated sources.

### Steps to Reproduce (for bugs)
https://docs.gradle.org/current/dsl/org.gradle.api.plugins.antlr.AntlrTask.html
We have to use `apply plugin: 'me.champeau.gradle.antlr4'` instead.

### Your Environment
Java 8, Gradle 4.0.1

**Comment by big-guy** [comment]
Would https://docs.gradle.org/nightly/javadoc/org/gradle/api/plugins/antlr/AntlrTask.html#setArguments(java.util.List) work?  This is missing from the DSL docs, but it exists in the Javadoc.

@melix is there anything else that's special about your plugin?

**Comment by danielsun1106** [comment]
@big-guy Thanks for your quick reply. BTW, How can I use another version of antlr4(e.g. "com.tunnelvisionlabs:antlr4:4.6.0.3" )?

https://github.com/gradle/gradle/blob/master/subprojects/antlr/src/main/java/org/gradle/api/plugins/antlr/AntlrPlugin.java#L62

**Comment by big-guy** [comment]
https://docs.gradle.org/nightly/userguide/antlr_plugin.html#sec:antlr_dependency_management

**Comment by danielsun1106** [comment]
I see. Thanks again :)
