### ISSUE TITLE
Disabling a task does not work

### ISSUE THREAD

**Issue by martinandersson** [gradle/gradle#25593]
You have a sample for how to do Jacoco report aggregation in a standalone utility project ... [here](https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage_standalone.html).

In the file `./buildSrc/src/main/groovy/myproject.java-conventions.gradle`, you do this:

```groovy
// Do not generate reports for individual projects
tasks.named("jacocoTestReport") {
    enabled = false
}
```

But this has no effect. When I run `./gradlew tasks` the `jacocoTestReport` is alive and well, and can be executed 😂

### Gradle version

8.1 + 8.2

### Environment

Tested on Windows and Linux.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

The task is there, but its execution is skipped, as designed:

```
> ….
> Task :application:jacocoTestReport SKIPPED
> Task :list:jacocoTestReport SKIPPED
> Task :utilities:jacocoTestReport SKIPPED

BUILD SUCCESSFUL in 477ms
```
