### ISSUE TITLE
[Spike] Restore IntelliJ import for gradle/gradle project

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2560]
Spend 4-8 hours understanding why we cannot use IntelliJ import for gradle/gradle.

Expected outcome is issue(s) for options and next actions.

**Comment by bmuschko** [comment]
Notes on what I have observed when exploring the integration with IDEA 2017.2:

__Import__

- Opening the project with "Auto-import" freezes up IntelliJ. Default memory settings won't do. A user will have to change them.
- IDEA initially seems to index the local Maven repository which takes a long time. You can see the message `Updating Maven Repository Indices...`. We should contact Jetbrains about this. As a Gradle user I do not care about the Maven repository.
- The best option of importing the project is with the directory-based format `.idea`. Users can provide custom settings in individual files and check them into version control e.g. license header, code style settings.
- An import of `gradle/gradle` doesn't raise any issues right away.

__Compilation__

- Compiling the code base raises an issue with the `internal-android-performance-testing` module. The module assign the Android Tools JAR with a custom configuration which causes IDEA not to resolve the dependency and therefore fails to properly use Android imports. This is the [reason why the code looks as it does](https://github.com/gradle/gradle/commit/5331d638f08ec9f1ba5df141de81cc0bb51c2976). To get around the issue temporarily the code could be changed to `compile('com.android.tools.build:gradle:2.3.0-beta3') { ... }` though it requires a different solution.

__Running tests__
- Running unit tests seems to work properly.
- Running integration tests fails with the following error message. I suspect that we made this work by introducing `gradle/ideaTestSourcesWorkaround.gradle`:

```
java.lang.ExceptionInInitializerError
	at org.gradle.integtests.fixtures.executer.IntegrationTestBuildContext.getVersion(IntegrationTestBuildContext.java:73)
	at org.gradle.integtests.fixtures.executer.UnderDevelopmentGradleDistribution.<init>(UnderDevelopmentGradleDistribution.java:29)
	at org.gradle.integtests.fixtures.AbstractIntegrationSpec.$spock_initializeFields(AbstractIntegrationSpec.groovy:54)
Caused by: org.gradle.api.GradleException: Resource '/org/gradle/build-receipt.properties' not found.
	at org.gradle.util.GradleVersion.<clinit>(GradleVersion.java:54)
	... 3 more


java.lang.NoClassDefFoundError: Could not initialize class org.gradle.util.GradleVersion

	at org.gradle.integtests.fixtures.executer.IntegrationTestBuildContext.getVersion(IntegrationTestBuildContext.java:73)
	at org.gradle.integtests.fixtures.executer.UnderDevelopmentGradleDistribution.<init>(UnderDevelopmentGradleDistribution.java:29)
	at org.gradle.integtests.fixtures.AbstractIntegrationSpec.$spock_initializeFields(AbstractIntegrationSpec.groovy:54)
```

__Applying custom settings__

- Logic to be translated lives in `gradle/idea.gradle`.
- The changes described below have been checked into version control in the branch [`bm/idea-config`](https://github.com/gradle/gradle/tree/bm/idea-config).
- Code formatting has been added in `codeStyleSettings.xml`.
- License header has been added in directory `copyright`.
- Run configurations have been added in directory `runConfigurations`. Most run configuration cannot be executed yet as it can't resolve the class to execute. Here's an example of a warning: `Warning: Class 'org.gradle.debug.GradleRunConfiguration' not found in module 'integTest'`.
- Compiler process heap size has not be translate yet as it seems to be a workspace setting. To be determined with Jetbrains.

**Comment by wolfs** [comment]
> IDEA initially seems to index the local Maven repository which takes a long time. You can see the message Updating Maven Repository Indices.... We should contact Jetbrains about this. As a Gradle user I do not care about the Maven repository.

Are you sure it is only indexing the local maven repository? From what I understand this index is used so you can have command line completion for adding dependencies. This is interesting from a Gradle perspective, too.

> Compiling the code base raises an issue with the internal-android-performance-testing module. The module assign the Android Tools JAR with a custom configuration which causes IDEA not to resolve the dependency and therefore fails to properly use Android imports. This is the reason why the code looks as it does. To get around the issue temporarily the code could be changed to compile('com.android.tools.build:gradle:2.3.0-beta3') { ... } though it requires a different solution.

What happens if you run the task creating the dependencies is the directory (`renameAndroidTools`) manually before importing into IDEA? I would guess that using dependencies on disk should work for the IDEA import.

> Running integration tests fails with the following error message. I suspect that we made this work by introducing gradle/ideaTestSourcesWorkaround.gradle

I don't think this has something to do with `gradle/ideaTestSourcesWorkaround.gradle`. Did you import the project using the option `create separate Modules per SourceSet`? I think we should use this option. Having `/org/gradle/build-receipt.properties` missing means that `base-services/build/generated-resources/test/` is not added as a resources dir for integration tests. Could you also check if the file is in that directory, so IDEA has a chance to pick it up?

**Comment by bmuschko** [comment]
> Are you sure it is only indexing the local maven repository?

I am not sure about that. I am mostly baffled that it actually _does_ index the local Maven repository though we don't declare it as repository in our build. The indexing takes seriously more than 5 minutes on my machine. Sometimes it even freezes up IntelliJ and I had to restart.

> Did you import the project using the option create separate Modules per SourceSet? I think we should use this option. 

Yes, I did enable the option.

> What happens if you run the task creating the dependencies is the directory (renameAndroidTools) manually before importing into IDEA? I would guess that using dependencies on disk should work for the IDEA import.

Looks like that works.

> Having /org/gradle/build-receipt.properties missing means that base-services/build/generated-resources/test/ is not added as a resources dir for integration tests.

The file is there. I think it probably has something to do with making the file available to other modules. I'd have to dig deeper.

**Comment by wolfs** [comment]
>> What happens if you run the task creating the dependencies is the directory (renameAndroidTools) manually before importing into IDEA? I would guess that using dependencies on disk should work for the IDEA import.
> Looks like that works.

I think we can add a tasks which will executed when IDEA does a sync. But I don't know how. I think @oehme or @melix have more insights. We could then just add the `renameAndroidTools` task to that list.

**Comment by bmuschko** [comment]
I updated my comment above. For some of the issues above I conferred with Jetbrains and created issues.

**Comment by bamboo** [comment]
@bmuschko are all the YouTrack issues you created linked from this issue?

**Comment by bmuschko** [comment]
@bamboo Yes, I linked all YouTrack issues in my comment.

**Comment by eskatos** [comment]
> Run configurations have been added in directory runConfigurations. Most run configuration cannot be executed yet as it can't resolve the class to execute. Here's an example of a warning: Warning: Class 'org.gradle.debug.GradleRunConfiguration' not found in module 'integTest'.

They do work if you don't choose "One module per source set".
If you do, then you need to change `integTest` to `integTest_integTest`.

Same thing for configurations running  `org.gradle.testing.internal.util.GradlewRunner`, change `internalTesting` to `internalTesting_main`.

**Comment by xiantang** [comment]
@eskatos  I changed `Use classpath of module`  `internalTesting` to  `internalTesting.main` and run the code  but console print `java.lang.ClassNotFoundException: org.gradle.testing.internal.util.GradlewRunner`   and I import project choose "One moudle per source set"
