### ISSUE TITLE
TestKit unexpectedly stopped working with Gradle 2.x versions

### ISSUE THREAD

**Issue by donat** [gradle/gradle#25611]
Gradle 8.0 removed support for connecting to 2.x version via the Tooling API: https://docs.gradle.org/current/userguide/third_party_integration.html#sec:embedding_compatibility

This means that TestKit (being a Tooling API client) stopped supporting Gradle integration tests for 2.x versions. https://github.com/gradle/gradle/pull/24891 is completely blocked functionality. 

We should revert https://github.com/gradle/gradle/pull/24891 and replace the exception with a deprecation message stating that connecting old Gradle versions is unsupported.

**Comment by ljacomet** [comment]
* Fixed by #25613
