### ISSUE TITLE
Update Exec standard output to be compatible with configuration cache

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#25614]
### Expected Behavior

[Exec.getStandardOutput()](https://docs.gradle.org/8.2/javadoc/org/gradle/api/tasks/AbstractExecTask.html#getStandardOutput--) is compatible with configuration cache

### Current Behavior

[Exec.getStandardOutput()](https://docs.gradle.org/8.2/javadoc/org/gradle/api/tasks/AbstractExecTask.html#getStandardOutput--) is not compatible with configuration cache

```
> Task :getVersionInfo FAILED
bc00f347a22805f720fd975304b31335bd5fb665

2 problems were found storing the configuration cache.
- Task `:gitVersion` of type `org.gradle.api.tasks.Exec`: cannot deserialize object of type 'java.io.OutputStream' as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:gitVersion` of type `org.gradle.api.tasks.Exec`: cannot serialize object of type 'java.io.ByteArrayOutputStream', a subtype of 'java.io.OutputStream', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

```

### Context (optional)

I want to use Exec.standardOutput in a project that has Configuration Cache enabled.

### Steps to Reproduce

```kotlin
// build.gradle.kts
import java.io.ByteArrayOutputStream

val gitVersion by tasks.registering(Exec::class) {
  executable("git")
  args("rev-parse", "HEAD")

  val gitVersionFile = layout.projectDirectory.file("gitVersion.txt")
  outputs.file(gitVersionFile)

  standardOutput = ByteArrayOutputStream()

  doLast {
    val capturedOutput = standardOutput.toString()
    gitVersionFile.asFile.apply {
      parentFile.mkdirs()
      createNewFile()
      writeText(capturedOutput)
    }
  }
}
```

This code is based on the Javadoc example

https://github.com/gradle/gradle/blob/c9224537a77e25ff289ee072b078e9a2543c53cd/subprojects/core/src/main/java/org/gradle/api/tasks/Exec.java#L20-L41

### Gradle version

8.2

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.
