### ISSUE TITLE
Build not terminating for repo plugin since `8.2`. 

### ISSUE THREAD

**Issue by ennioVisco** [gradle/gradle#25634]
### Expected Behavior

It should move to another task in a few seconds.

### Current Behavior

<img width="537" alt="image" src="https://github.com/gradle/gradle/assets/740025/9dd850f6-a695-4a8d-8b46-44f06f6da84a">

### Steps to Reproduce

1. `git clone -b mfr-logic https://github.com/MoonLightSuite/MoonLight.git moonlight`
2. `./gradlew wrapper --gradle-version=8.2`
3. `./gradlew build`

Alternatively, one can skip the second step and notice that with `8.1.1` it builds correctly.

### Gradle version

8.2

### Your Environment (optional)

M1 Mac OS

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

----

I can't reproduce on a m2 mac with Java 17 (the minimum to build your project apparently).
There must be something different on your end. Can you reproduce on a different machine?

**Comment by ennioVisco** [comment]
Ok, it seems it was related to my local setup, I can confirm I was able to build from another machine. 
Closing the issue, thanks and I apologize for the time spent.
