### ISSUE TITLE
Play compiled Twirl templates fail to process annotations

### ISSUE THREAD

**Issue by ymwang1984** [gradle/gradle#2566]
### Expected Behavior

[Twirl templates](https://www.playframework.com/documentation/2.6.x/ScalaTemplates) is a type safe template engine mainly used in Play front ends. It is natively integrated with SBT (the default build tool of Play Framework). In Gradle, we also have the task "compilePlayBinaryPlayTwirlTemplates" to process the Twirl templates and we expect the compiled templates are the same as SBT.

### Current Behavior

In migrating production projects from SBT to Gradle, we found that Gradle compiled Twirl templates (used mainly in Play front ends) differ from those from SBT (e.g. cannot process certain annotations such as @JavaScript). And this difference causes rendering issues when the Play app is deployed.

### Context

It may cause more and more issues when more Play front-end apps are migrated from SBT to Gradle since Twirl templates are widely used.

### Steps to Reproduce (for bugs)

We set up a small repo to reproduce this issue: https://github.com/ymwang1984/play-on-gradle-twirl

The repo has [a small file](https://github.com/ymwang1984/play-on-gradle-twirl/blob/master/app/views/generic.scala.js#L7) under app/views/js/ with a @JavaScript annotation in it. 

Running `./sbt compile` and the compiled template "target/scala-2.11/twirl/main/views/js/generic.template.scala" has the correct class "play.twirl.api.JavaScriptFormat" in it.

Running `./gradlew compilePlayBinaryPlayTwirlTemplates` and the compiled template "build/src/play/binary/twirlTemplatesScalaSources/views/js/generic.template.scala" has the incorrect class "play.twirl.api.HtmlFormat" in it. This difference causes rendering issues.

The reporter inside my organization suggests that it may be caused by the following:

SBT includes more format [here](https://github.com/playframework/twirl/blob/master/sbt-twirl/src/main/scala/play/twirl/sbt/SbtTwirl.scala#L89-L94)

However, Gradle only accepts one format which is html [here](https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV22X.java#L86)

### Your Environment

 * Build scan URL: 

The issue can be reproduced in both Mac (OS Sierra) and Linux (Red Hat).

**Comment by ymwang1984** [comment]
@big-guy Please let me know if you need more information. Thank you in advance!

**Comment by big-guy** [comment]
Thanks @ymwang1984 -- great investigation.

Would you be interested in [submitting a PR](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md) to add the other formats? 

It would look something like:
1. Add a `templateFormats` property to `TwirlCompile` with the defaults as in sbt.  It can be read-only for now.
1. Wire `templateFormats` into `DefaultTwirlCompileSpec`.
1. From `TwirlCompiler` and `VersionedTwirlCompilerAdapter`, use `templateFormats` from `TwirlCompileSpec` to select the correct format vs the hardcoded HtmlFormat.
1. Adapt your example into a integration test and/or update our samples to use something other than HTML. (see `TwirlCompileIntegrationTest`)

**Comment by ymwang1984** [comment]
@big-guy 

Thank you for the reply! I will look a bit into it but there may be a bigger problem for Twirl for my company's use case.

In my company, there is a custom Twirl template called "stream". Many front-end applications use it so I am afraid we need to support custom template formats (read-only may not be good enough).

The code for the "stream" Twirl template is something like this (in SBT's Build.scala):

`import play.twirl.sbt.Import.TwirlKeys`
......
`.settings(TwirlKeys.templateFormats += ("stream" -> "com.linkedin.some.custom.format.class"))`
`.settings(TwirlKeys.templateImports ++= Seq("com.linkedin.some.custom.import.class._", "com.linkedin.some.other.custom.import.class._"))`

Let me see if I can form a minimal repo to demonstrate this use case. But it looks like Gradle's Play plugin has to support custom Twirl templates as SBT does. So just a heads-up.

**Comment by big-guy** [comment]
Yep, it's not a problem to add custom templates as a second step.  I would just like to get it working with the built-in types first.  We may want to model the custom template formats better, so it's best to keep it separate initially.

**Comment by big-guy** [comment]
@ymwang1984 Could you open a new issue that describes what you need to support your custom template format? If you can make a simple example for a custom template that works with SBT, I can adapt that into an integration test. 

Based on your comment in https://github.com/gradle/gradle/issues/2566#issuecomment-318917827, I think we need to be able to specify an extension, an implementation type and possibly a set of additional imports.  We can work out the details for that in the new issue.

**Comment by ymwang1984** [comment]
@big-guy 

Thank you for reply. I will open a new issue tomorrow about supporting custom format.

I updated the repo  https://github.com/ymwang1984/play-on-gradle-twirl

In it, the project registers "sh" extension with HTML format like this:

`import play.twirl.sbt.Import.TwirlKeys`

`lazy val root = (project in file("."))
  .enablePlugins(PlayJava)
  .settings(TwirlKeys.templateFormats += ("sh" -> "play.twirl.api.HtmlFormat"))
  .settings(TwirlKeys.templateImports ++= Seq("java.util.Random", "java.util.Map"))
`
I put a dummy sh file "demo.scala.sh" under "app/views".

Also I specified templateImports to always include "java.util.Random" and "java.util.Map" in the generated code. When we check all generate Scala files under "target/scala-2.11/twirl", those two import statements are always included.

In the end, the repo is still using a built-in format. But it should be a good start. I will see if I could find open source twirl templates to truly differ from built-in twirl formats. Or I can ask our internal teams to abstract a simple version of the custom stream format.

**Comment by big-guy** [comment]
Thanks, I think we'll want a simple example that uses a custom format so that we know we're passing the right classpath to the Twirl compiler.

Here's an example I found: https://vlarsen.wordpress.com/2014/04/08/custom-format-in-the-play-framework-templating-engine-example/

**Comment by ymwang1984** [comment]
Agreed. The example you gave is for Play 2.2 which I cannot use directly (Play 2.4).

I am not a Twirl user myself so I just added a "dummy" custom template called "CSV".

https://github.com/ymwang1984/play-on-gradle-twirl/blob/master/app/views/Csv.scala

And build.sbt:

https://github.com/ymwang1984/play-on-gradle-twirl/blob/master/build.sbt#L9

**Comment by ymwang1984** [comment]
@big-guy  I opened another issue: https://github.com/gradle/gradle/issues/2670
