### ISSUE TITLE
Not possible to define GCC-like toolchain without changing Gradle core

### ISSUE THREAD

**Issue by FranzKrainer** [gradle/gradle#2568]
We have a customized toolchain in hands which is indeed very similar to GCC. It is actually almost the same wrt. call interface, etc., but in terms of toolchain recognition it is different, not as verbose and capable as GCC. This is why it is actually not recognized.
We define like:
```
toolChains {
    ArmCc(Gcc) {
        path "${System.env.TOOLDISK}\\Keil_v5\\ARM\\ARMCC\\bin"
        eachPlatform {

            cCompiler.executable = 'armcc'
            cppCompiler.executable = 'armcc'
            staticLibArchiver.executable = 'armar'
            linker.executable = 'armlink'
            assembler.executable = 'armasm'
        }
    }
}

components {
    main(NativeExecutableSpec) {
    }
}
```
...and the toolchain is not recognized:
```
- executable 'main:executable': No tool chain is available to build for platform 'windows_x86':
    - Tool chain 'ArmCc' (GNU GCC): Could not determine GCC version: failed to execute armcc.exe -m32 -dM -E -
```

The only way around was/is so far to change Gradle core itself:
```
@Override
    public GccVersionResult getGccMetaData(File gccBinary, List<String> args) {
        List<String> allArgs = new ArrayList<String>(args);
        allArgs.add("-dM");
        allArgs.add("-E");
        allArgs.add("-");
        String output = transform(gccBinary, allArgs);
        if (output == null) {
            //Change from Patch (remove first line, add 4 lines)
            //return new BrokenResult(String.format("Could not determine %s version: failed to execute %s %s.", getDescription(), gccBinary.getName(), Joiner.on(' ').join(allArgs)));
            LOGGER.info("Could not determine {} version: failed to execute {} {}. Assume it cannot support UseCommandFile.", getDescription(), gccBinary.getName(), Joiner.on(' ').join(allArgs));
            Map<String, String> defines = new HashMap<String, String>();
            final ArchitectureInternal architecture = determineArchitecture(defines);
            return new DefaultGccVersionResult(new VersionNumber(0, 0, 0, null), architecture, clang);
        }
        return transform(output, gccBinary);
    }
```

### Expected Behavior
Very GCC-like toolchains where overall concept can be totally copied shall be accepted even though maybe not having the totally same call interface wrt. GCC version detection.
Looking into the GccVersionDeterminer.java it would be sufficient to replace two "return new BrokenResult" from the GccVersionResult function to an e.g. Logger warning to relax the situation.

### Current Behavior
Very GCC-like toolchains where overall concept is totally copied are unfortunately rejected due to GCC version detection being quite strict (method getGccMetaData). 

### Context
The issue means for us that every Gradle distro we get, we need to first alter and then re-compile. We did not find a non-code-changing way fwd.

### Steps to Reproduce (for bugs)
See descr. above

### Your Environment
Gradle 4.0.1 and every Gradle before (tried since 2.14.1). Using GCC-like ARMCC toolchain.

**Comment by w25r** [comment]
Some more context can also be found [on the forum post](https://discuss.gradle.org/t/native-plugin-has-restriction-when-defining-custom-toolchain/15050/4)

@lacasseio, I know that you had looked into this a bit previously.  Care to comment?

**Comment by lacasseio** [comment]
Thanks for the feature request @FranzKrainer. It is something we are looking at resolving with the current native effort. Defining new tool chains should be doable through public API. Recompiling Gradle at every release isn't an effective approach as you noted. Simply patching the code to return an unknown but valid version isn't good enough for us as we use this information to make decisions later on. There are two ways to move forward:
1. **Create a wrapper script around `ArmCC` to fake GCC.** This will enable you to keep the change in a self-contained location and should require a small amount of code to work.
2.  **Write your own `ArmCC` tool chain implementation plugin using the internal API.** This will enable you to have specific automation around `ArmCC` and provide your type:
```
model {
  toolChains {
    ArmCc(ArmCC)  // locating the tool chain could look in default location for this tool
  }
}
```
It would be the direction tool chain definition would look like in the future. However, at this stage, you would be relying on internal API which could break in future releases. The advantage is you won't need to recompile Gradle at every release. You will simply have to recompile the plugin if there is a breaking change.

Option 1 is the easiest but the hackiest. Option 2 would require more effort, but you would own the tool chain definition. Keep in mind that it would mostly be [duplicating some code from Gradle](https://github.com/gradle/gradle/tree/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal) into your plugin. As an example, I recently [prototyped the Swift compiler](https://github.com/gradle/gradle/tree/master/subprojects/platform-native/src/main/java/org/gradle/nativeplatform/toolchain/internal/swift) inside Gradle. You can have a [look at the commit for more context](https://github.com/gradle/gradle/commit/81319fd6faf8fd6f9659e0fb1090a88a2f3dcadb).

I hope this help and don't hesitate to follow the issues on [`gradle/gradle-native`](https://github.com/gradle/gradle-native/issues) to see when this work will get scheduled.

**Comment by FranzKrainer** [comment]
Hi,

thanks, @lacasseio!
Fully understood; already feared something like this actually ;-).
The own plug-in we always wanted to kind of avoid but I think this would be the correct way fwd. nonetheless. We did actually never truly invest into writing own plug-ins so far. We refrained from this to avoid effort but this created workarounds, as you see.
Ok, so, we can also wait until this gets made up finally when getting a public API allowing this and stick to our changing-Gradle-core which would be Option 0. Or we really go for Option 2 which is proper. I think Option 1 is another workaround which will be difficult to really explain :).

One last question:
https://docs.gradle.org/4.0.2/javadoc/org/gradle/nativeplatform/toolchain/GccCompatibleToolChain.html is not what we want and can work with, right?
Do not fully get the purpose of this one ;).

Thanks a lot in advance!
BR,
Franz

**Comment by lacasseio** [comment]
The class `GccCompatibleToolChain` was created as Clang has a GCC compatible command line interface. It's simply an abstract class to share the code between both Clang and GCC implementation. You could work with that class if it makes sense in your implementation for ArmCC. Keep in mind that the API for implementing a tool chain is internal and there is currently some work being done on them to simplify it and add parallelism by default. That shouldn't discourage you to try option 2 if you want.

One of Gradle's biggest power comes from plugins. You should embrace them and model what you are trying to do with them.

**Comment by FranzKrainer** [comment]
Hi,

okie, understood. Yes.
Finally an Option 2 would be best for us or waiting until - with official API - we can handle this more proper. Still I think stepping into plugin development is nonetheless necessary, also thinking about other toolchians that might come in on top and which are not supported potentially yet.

**Comment by FranzKrainer** [comment]
think we can close this one :-)!
Thanks & bye,
Franz
