### ISSUE TITLE
allWarningsAsErrors property doesn't work

### ISSUE THREAD

**Issue by WildOrangutan** [gradle/gradle#25681]
### Expected Behavior

When using `./gradlew assembleDebug -Porg.gradle.kotlin.dsl.allWarningsAsErrors=true`, build should fail, if there are any warnings present.

### Current Behavior

Build does not fail

### Steps to Reproduce

1. Make a warning in your code
2. Run something like following, from terminal
 `./gradlew assembleDebug -Porg.gradle.kotlin.dsl.allWarningsAsErrors=true`
 3. Build doesn't fail
 
 Please also see sample project, which demonstrates this bug https://github.com/WildOrangutan/gradle-bug-fail-on-warn
 

### Gradle version

8.2

### Your Environment (optional)

Linux

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
You're confusing the Kotlin compiler option (which is commented out in your reproducer's `build.gradle.kts`) and the Kotlin DSL option (which is passed by command-line arguments). The first one is about warnings in your Kotlin production code, the latter is about warnings in your build script.
