### ISSUE TITLE
Re-instrument all dependant jars for inherited methods when third party jar changes

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#25714]
We implemented instrumentation for inherited methods in https://github.com/gradle/gradle/pull/25064.

While this is good for initial upgrades, implementation needs an improvement for transitive dependant jars.

### Example
Let's say we have a third party class `A` in jar `a.jar` and third party class `B` in `b.jar`. Now let's say that
`A extends B` and `B` doesn't extend anything. Now when we run instrumentation we won't upgrade calls of `A` or `B`, since it doesn't extend any Gradle type that is instrumented.

But what if at one point user upgrades `b.jar` and in upgraded jar `B extends DefaultTask`? 
Well in that case, we will instrument `b.jar`, because it's a new jar. But we need to also instrument `a.jar` and also all other jars that depend on `b.jar`. So we basically need to reinstrument all jars that depends on `b.jar` transitively. 

That is currently not the case but could be a problem when using upgrades in production.

**Comment by lptr** [comment]
We expect this to work once we switch over to artifact transforms.

**Comment by asodja** [comment]
Fixed with https://github.com/gradle/gradle/pull/27698
