### ISSUE TITLE
MavenPublicationErrorChecker can have a more helpful error message

### ISSUE THREAD

**Issue by tomasbjerre** [gradle/gradle#25728]
### Expected Behavior

It would be very helpful if the error said:

- What artifact is modified. (Looks really strange that the code returns once it finds one not modified artifact, should it not check all artifacts in the list?)
- If `file` was modified, how does it differ in `source` and `mainArtifact`
- If `extension` was modified, how does it differ in `extension` and `mainArtifact`
- If `classifier` was modified, how does it differ in `classifier` and `mainArtifact`

### Current Behavior (optional)

I am getting the error `Cannot publish module metadata where component artifacts are modified.` here:
https://github.com/gradle/gradle/blob/e1c436fa6fc19867f34f6984f343981b28e511e7/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/validation/MavenPublicationErrorChecker.java#L54

```
* What went wrong:
Execution failed for task ':gradle-scripts:generateMetadataFileForGradleScriptsPublicationPublication'.
> Cannot publish module metadata where component artifacts are **modified.**
```

### Context

I am upgrading to Gradle 8.2.1.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.
