### ISSUE TITLE
Not able to download distrubutions from downloads.gradle-dn.com and it throws connection timeout error

### ISSUE THREAD

**Issue by gowdham26** [gradle/gradle#25739]
### Expected Behavior

Running the below command results in timeout error and not able to download graddle distribution anymore from this URL

curl -O https://downloads.gradle-dn.com/distributions/gradle-6.8-bin.zip

But running below command able to download:
curl -O https://services.gradle.org/distributions/gradle-6.8-bin.zip

Expected behavior is that when we download gradle distribution from downloads.gradle-dn.com, it should download as it worked before.

### Current Behavior

Not able to download gradle distribution from this url "https://downloads.gradle-dn.com/distributions"
This URL is not even opening in browser either.

$ curl -O https://downloads.gradle-dn.com/distributions/gradle-6.8-bin.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
curl: (28) Failed to connect to downloads.gradle-dn.com port 443 after 21032 ms: Timed out

### Steps to Reproduce

Run the below git command:

$ curl -O https://downloads.gradle-dn.com/distributions/gradle-6.8-bin.zip

Connection timeout will occur.

Or 
Open the URL  "https://downloads.gradle-dn.com/distributions/gradle-6.8-bin.zip"in browser  to see that it will result in connection timeout.

### Gradle version

6.8

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

This domain is currently unsupported. Please change it to either [services.gradle.org](http://services.gradle.org/) or [downloads.gradle.org](http://downloads.gradle.org/).

See also:
* https://github.com/gradle/gradle/issues/10164

**Comment by ov7a** [comment]
Yes, you are right. We are currently in the process of solving this issue, but setting up a CDN in China is hard, so it takes a while to wrap everything up.
