### ISSUE TITLE
Seems to be no way to set javadoc "packages header"

### ISSUE THREAD

**Issue by davidmichaelkarr** [gradle/gradle#2575]
In my Maven builds, I can configure the "maven-javadoc-plugin" to set various header strings, like "top", "bottom", "footer", and also "packagesheader".  That last one appears in the "Packages" list in the top-left frame.  I've managed to find a way to set all of these header strings with the standard Gradle javadoc configuration, but not "packagesheader".  Curiously, I don't even see a way to set this in the "javadoc" command-line tool.  However, as I said, the "maven-javadoc-plugin" is able to do this.

**Comment by bmuschko** [comment]
I don't see the option [in the official Javadoc documentation](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#options). Maybe they just forgot to document it. Based on [this issue](http://bugs.java.com/view_bug.do?bug_id=4766385) they must have added it with Java 1.4.2.

Please provide a pull request if you'd like to have the option. I don't think this issue will be high priority in the near future.

**Comment by davidmichaelkarr** [comment]
I see. The option does exist in the command-line tool, but as you note, they forgot to document it: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4770521 . I can live without it.

**Comment by bmuschko** [comment]
OK, I am going to close the issue then as I believe that not many people would be interested in this. Feel free to reopen if the needed arises.
