### ISSUE TITLE
Add support for 'threadpoolfactoryclass' parameter of TestNG

### ISSUE THREAD

**Issue by alex-postnov** [gradle/gradle#25759]
### Expected Behavior

There should be a way to pass 'threadpoolfactoryclass' to TestNG like in the example below:

useTestNG {
    threadPoolFactoryClass = "automation.framework.ThreadPoolExecutorFactory"
}

### Current Behavior (optional)

There is no way to pass 'threadpoolfactoryclass' launch parameter to TestNG when running tests via Gradle

### Context

'threadpoolfactoryclass' launch parameter was introduced some time ago. Link to PR where it was added: https://github.com/testng-team/testng/pull/2042

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

**Comment by alex-postnov** [comment]
Hi @ov7a, Thank you for your reply. I have implemented it and attached my [PR](https://github.com/gradle/gradle/pull/25760). It would be great if someone could assist with review there. Thanks.

**Comment by big-guy** [comment]
This should be in 8.7
