### ISSUE TITLE
Add actionable information to dependency locking error messages 

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#25756]
### Issue type

Missing information

### Problem description

Add actionable information to dependency locking failures

### Context (optional)

I'm a regular developer who has picked up an existing Gradle project that has enabled [dependency locking](https://docs.gradle.org/current/userguide/dependency_locking.html). When I try and build my project, I get an error:

```
Locking strict mode: Configuration ':app:kotlinCompilerPluginClasspathJvmMain' is locked but does not have lock state
```

I am not sure what to do. I understand there is a problem, but it's not clear how to resolve it.

Currently I have to Google around, but there's [no obvious matches for this error](https://www.google.com/search?q=Locking+strict+mode%3A+Configuration+is+locked+but+does+not+have+lock+state). The error message isn't in the [Gradle docs page](https://docs.gradle.org/current/userguide/dependency_locking.html), so there's no clear section I can jump to.

If I'm lucky I might find a StackOverflow answer that has a solution, or the Gradle docs (although these docs are not clear #25293).

It would be a much better user experience if the error message told me what my options are, and how to fix it.

For example:

```
Locking strict mode: Configuration ':app:kotlinCompilerPluginClasspathJvmMain' is locked but does not have lock state. 

To create the lock state, run `./gradlew <task name>`
```

This would make Gradle more helpful, and reduce the amount of work required to perform a simple update task.

It would also help new developers learn Grade.

### Page with the problem

n/a

**Comment by ov7a** [comment]
Thank you for providing a detailed description.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

---

You're right, the error message should be improved.

Some information about the error can be found [here](https://docs.gradle.org/current/userguide/dependency_locking.html#fine_tuning_dependency_locking_behaviour_with_lock_mode)
