### ISSUE TITLE
Dependency locking fails for Kotlin Multiplatform project: "Configuration ':kotlinScriptDefExtensions' is locked but does not have lock state"

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#25758]
### Expected Behavior

Dependency locking does not fail for Kotlin Multiplatform project

### Current Behavior

Dependency locking fails for Kotlin Multiplatform project

### Context (optional)

Given a Kotlin Multiplatform project with Dependency Locking enable, run `./gradlew check`.

Observe that Gradle fails with an unhelpful error

```
Execution failed for task ':urlencoder-lib:compileKotlinJvm'.
> Failed to calculate the value of task ':urlencoder-lib:compileKotlinJvm' property 'scriptExtensions$kotlin_gradle_plugin_common'.
   > Could not resolve all dependencies for configuration ':urlencoder-lib:kotlinScriptDefExtensions'.
      > Locking strict mode: Configuration ':urlencoder-lib:kotlinScriptDefExtensions' is locked but does not have lock state.
```

### Steps to Reproduce

Run `./gradlew check` in the attached project.

[urlencoder.zip](https://github.com/gradle/gradle/files/12038337/urlencoder.zip)

### Gradle version

8.2.1

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Related to
*  #25756 

See [docs](https://docs.gradle.org/current/userguide/dependency_locking.html#fine_tuning_dependency_locking_behaviour_with_lock_mode).

You need to generate a lock file for `kotlinScriptDefExtensions` in `urlencoder-lib`.
