### ISSUE TITLE
Gradle daemon picking doesn't look on user groups / Provide a way to customize choosing Gradle daemon

### ISSUE THREAD

**Issue by LDVSOFT** [gradle/gradle#25765]
### Expected Behavior

Imagine me running two Gradle task sets:
```
./gradlew testClasses
# Tests use Docker, allow access to it
sudo -g docker ./gradlew test
```
Since second one is launched with different primary group & supplementary group set, it should pick a different Gradle daemon (launching one if missing).

### Current Behavior (optional)

Of many things that Gradle takes into account when choosing a daemon to use, groups are not used for it.

Also, there is no way to provide Gradle some user information for daemon choosing, like custom disambiguation.

### Context

I am trying to lock down my Linux work machine a bit by not providing unrestricted Docker access to my Linux user, since [Docker access is essentially root access](https://docs.docker.com/engine/security/#docker-daemon-attack-surface). I am trying to work around this by using `sudo -g docker` for workloads requiring Docker access, and this works fine-ish. However, when I try running Gradle builds that involve Docker for test purposes (see [TestContainers](https://java.testcontainers.org/)), I have to either run the whole build with Docker group:
```
sudo -g docker ./gradlew ...
```
or, since I am trying to lock down machine a bit, only provide Docker access for step requiring it. However, as I've stated above, Gradle will try to reuse the daemon from the first step and fail.

This can be work-around by actually providing `--no-daemon` flag that will launch a one-off daemon, but that slows down every test launch.

Also, the problem isn't limited to this Docker setup or other things. One might look at other credentials (like key source for signing a release binary) and only expose them to tasks needing them. While not perfect (since Gradle will still re-verify all previous steps and possibly execute them), that can be a measure to short the window for credentials misuse.

Another process properties that could be considered are priorities. You could have two Gradle daemons: one with default priority for normal development and a separate background one with lower priority for some long-running tasks, and if Gradle would swap them that would be noticed by the end user.

Instead of providing Gradle information on how to select a daemon (we don't need another attribute-based mechanism here), probably option to start the daemon with user-specified disambiguation id and option to provide it to build launches would suffice.

P.S. Sorry for any typos, beta issue form is a bit annoying.

**Comment by ov7a** [comment]
The feature you're requesting would imply a lot of problems from a security point of view: file permissions, ownership, process isolation, etc. We won't support that because it adds more problems than solves.

For your use case, you can try one of the following:
1. Launch a build with another Gradle home dir. This would isolate the daemon.
2. Launch a build with sudo and another user. This would isolate the daemon because Gradle home dir would change.
3. Create a trusted environment or launch every Gradle daemon with sudo.

**Comment by ov7a** [comment]
> P.S. Sorry for any typos, beta issue form is a bit annoying.

@LDVSOFT Could you elaborate a bit on how we can improve our issue forms?

**Comment by LDVSOFT** [comment]
Another Gradle home dir sounds cool! I wouldn't want to avoid whole cache duplication, but I guess I can look into that, thanks. Still I'm sad there isn't an option to control the daemon I'm starting in special environment.

About forms: it had three input boxes (like the ones I'm writing this comment in), yet they weren't resizable vertically, only one of them with focus was a proper editor (others swtiched to non-monospace text areas, still not resizable) and there wasn't a proper preview for the whole thing. So while writing it and jumping between input boxes I couldn't properly see my draft in full: only non-editable parts and the one with a focus.

**Comment by ov7a** [comment]
Oh, so it is a GitHub UI problem, ok. Unfortunately, it's up to the GitHub team to improve this, consider contacting them.
BTW, you can resize an input box - there is a draggable bottom-right corner:
![image](https://github.com/gradle/gradle/assets/4946730/1b16a680-9eb9-44e3-bd4e-2d3d39ef29be)

**Comment by LDVSOFT** [comment]
The resize of small boxes in the form didn't work: the comment form has a bigger and actually working box ;)
