### ISSUE TITLE
Jacoco Problem with Gradle Transform Task #105

### ISSUE THREAD

**Issue by Nash123-start** [gradle/gradle#25785]
### Expected Behavior

The jacoco Instrumentation code should exist in final classes.jar after using ScopedArtifacts.Scope.ALL to transform the code

### Current Behavior

The jacoco Instrumentation code didn't exist in final classes.jar after using ScopedArtifacts.Scope.ALL to transform the code

### Steps to Reproduce

Hi, I use jacoco and ScopedArtifacts.Scope.ALL to do some transform work in my project.
The gradle tool version is 8.0
My project structure is as follows:
app
module a
module b
app includes module a and module b
in app I use ScopedArtifacts.Scope.ALL to write a gradle plugin
there is the code :

<img width="824" alt="plugin1" src="https://github.com/gradle/gradle/assets/97157482/38bd7a00-6439-4b60-8df0-31bb1c667f06">
<img width="724" alt="plugin2" src="https://github.com/gradle/gradle/assets/97157482/30ab3936-4c70-43da-8bd6-9132d3215336">

and I use jacoco in module A and module B too
there is the jacoco code:
<img width="622" alt="jacoco3" src="https://github.com/gradle/gradle/assets/97157482/f4a72626-2eca-4509-be46-a1c7e235e104">

now there comes the problem the jacoco task is execute before transform task
After the jacoco task is finished, the transform task will get the input dir and input jar( module A class.jar module B class.jar)
but when I print the path of input jar , I found that the input jar is still the original jar file without jacoco Instrumentation code.

example:
after jacoco task
the input jar   @get:InputFiles abstract val allJars: ListProperty<RegularFile>
class path in the plugin is
Module A/build/intermediates/runtime_library_class_jar/class.jar(without jacoco Instrumentation code)
Module B /build/intermediates/runtime_library_class_jar/class.jar(without jacoco Instrumentation code)

That means jacoco didn't work in my project due to the using of transform task by code mentioned above, because the transform task still use the original class jar ( module A class.jar without jacoco Instrumentation code and module B class.jar without jacoco Instrumentation code) to general the final class.jar that will finally saved in app/build/intermediates/classes/all/class.jar.
So how can I do to get the right class.jar of module A and module B that include jacoco Instrumentation code
and in gradle 7.0
I found that
Module A/build/intermediates/runtime_library_class_jar/class.jar
Module B /build/intermediates/runtime_library_class_jar/class.jar
include the jacoco Instrumentation code
but in gradle 8.0 it's not

### Gradle version

8.0.0

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Your configuration is applied to test execution. Jacoco runs with an agent, which is configured just for test runtime. You need to configure Jacoco for compilation.
