### ISSUE TITLE
Gradle Conflict Resolution documentation potentially has wrong logic for base version and qualifier parsing

### ISSUE THREAD

**Issue by tacascer** [gradle/gradle#25798]
### Issue type

Wrong or misleading information

### Problem description

Hi there!

I noticed that the table depicting the logic for parsing a **Base Version** and a **Qualifier** from an **Original Version** had a potentially wrong parsing.

In the example of `b1-2-3.3`, the base version is `b` and the qualifier is `2-3.3`. It seems that the `1` is simply dropped.

According to my understanding, should the qualifier be `1-2-3.3` instead?

Thank you for your help and attention!

### Page with the problem

https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:base-version-comparison

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

---

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by pratik2315** [comment]
Hey there! May I work on this issue if it's still available?

**Comment by ov7a** [comment]
@pratik2315 Yes, thank you!

**Comment by pratik2315** [comment]
Thanks, @ov7a !
I have created a PR, since it's my first time making a contribution here, would you please check if everything is okay with it and suggest changes if possible? Thanks again :)

**Comment by ov7a** [comment]
@pratik2315 Everything is ok, I've scheduled your pr to merge. Congrats on your first contribution! It's a small change, but it's honest work:)
