### ISSUE TITLE
Have a public API for creating org.gradle.cache.LockOptions

### ISSUE THREAD

**Issue by idlsoft** [gradle/gradle#25803]
### Expected Behavior

`org.gradle.cache.FileLockManager` is a a public API, but the `lock` method accepts `LockOptions`, which can only be created using `org.gradle.cache.internal.filelock.LockOptionsBuilder`.

We should be able to create `LockOptions` instances using public APIs.

### Context

Tried to `FileLockManager.lock` in my plugin.

**Comment by big-guy** [comment]
Sorry, FileLockManager is an internal API.  The package can be misleading. 

The public APIs are APIs documented in our Javadoc: https://docs.gradle.org/current/javadoc/index.html?overview-summary.html

**Comment by idlsoft** [comment]
Thanks for the prompt reply.
Wanted to use this for auto-installing a Python toolchain under `~/.gradle`.
Will find another way.

I understand extending the public API costs flexibility, but I'd like to see some utilities being accessible in the future:
file locking, progress bars.

Thanks again.
