### ISSUE TITLE
Build time started from -10

### ISSUE THREAD

**Issue by tasomaniac** [gradle/gradle#2580]
I couldn't reproduce it afterwards and I have no idea how it happened but running tests with `./gradlew test` started from -10 while building `buildSrc`. Then it counted up regularly until it is 0 and then continued normally of course. 

This was after I upgraded my Android plugin to `3.0.0-alpha7` and gradle to `4.1-rc-1`. I upgraded gradle via `./gradle wrapper --gradle-version=4.1-rc-1`

### Expected Behavior
The timer should start from 0 no matter what. 

### Your Environment
I have macOS with Android Studio 3.0.0 preview 7

**Comment by bmuschko** [comment]
> I couldn't reproduce it afterwards and I have no idea how it happened but running tests with ./gradlew test started from -10 while building buildSrc. Then it counted up regularly until it is 0 and then continued normally of course.

I am assuming you are referring to something that is rendered in Android Studio? Or is this about what you see on the command line?

> The timer should start from 0 no matter what.

Can you please add a screenshot that points to it?

**Comment by tasomaniac** [comment]
I am talking about command line. I didn't even have AS opened. 
It is the timer next to the percentage of execution. Unfortunately I didn't see it again. Feel free to close it if you think it doesn't make sense 🤷‍♂️ I can understand it is pretty hard without enough info.

**Comment by bmuschko** [comment]
> It is the timer next to the percentage of execution.

Just to make sure we are on the same page: we are talking about the timer e.g. `[5s]` in the [build progress bar](https://docs.gradle.org/current/userguide/console.html#sec:console_build_progress_bar) right?

> Feel free to close it if you think it doesn't make sense.

It might have to some correlation with the system clock on your machine. Did you run this on your local machine or on CI? Could you please also provide information on the OS? I don't think we'll be able to implement a fix without some strong evidence that it is reproducible.

**Comment by eriwen** [comment]
Based on my understanding of how the timer is implemented, I'm very surprised that it would ever be negative. 

I requested that @tasomaniac submit this issue even though we don't have a reproducible example to look into any logic that would even allow this to occur. 

@bmuschko perhaps you or I could double-check how the build start time is propagated through to logging and see if there are any faults and add test coverage. WDYT?

**Comment by eriwen** [comment]
@tasomaniac Can you think of any features about your build that you think are sufficiently unique that might be helpful? For example, I see that you mention `buildSrc`. That in itself is helpful. Another example of helpful info: Do you happen to be using composite builds, `GradleBuild` tasks, or `--configure-on-demand`?

**Comment by bmuschko** [comment]
@tasomaniac We identified the issue and put in a fix. Thanks again for reporting!
