### ISSUE TITLE
Build Cache NG builds fail because of incomplete outputs restored from the cache

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#25816]
### Expected Behavior

The build should complete normally.

### Current Behavior

Build logic build produces incomplete plugin JAR:
```
:build-logic-commons:gradle-plugin:compileKotlin FROM-CACHE	
:build-logic-commons:gradle-plugin:compileJava NO-SOURCE	
:build-logic-commons:gradle-plugin:classes	
:build-logic-commons:gradle-plugin:jar	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.ci-reporting.properties but the implementation class Gradlebuild_ciReportingPlugin was not found in the jar.	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.collect-failed-tasks.properties but the implementation class Gradlebuild_collectFailedTasksPlugin was not found in the jar.	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.build-logic.kotlin-dsl-gradle-plugin.properties but the implementation class Gradlebuild_buildLogic_kotlinDslGradlePluginPlugin was not found in the jar.	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.cache-miss-monitor.properties but the implementation class Gradlebuild_cacheMissMonitorPlugin was not found in the jar.	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.build-logic.groovy-dsl-gradle-plugin.properties but the implementation class Gradlebuild_buildLogic_groovyDslGradlePluginPlugin was not found in the jar.	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.ktlint.properties but the implementation class Gradlebuild_ktlintPlugin was not found in the jar.	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.code-quality.properties but the implementation class Gradlebuild_codeQualityPlugin was not found in the jar.	
:gradle-plugin:jar: A valid plugin descriptor was found for gradlebuild.test-retry.properties but the implementation class Gradlebuild_testRetryPlugin was not found in the jar.	
```

The plugin then fails to apply:
```
Could not find implementation class 'Gradlebuild_collectFailedTasksPlugin' for plugin 'gradlebuild.collect-failed-tasks' specified in jar:file:/home/tcagent1/.gradle/caches/jars-9/o_55c30d422a1fb05fd9b55299b446c568/gradle-plugin.jar!/META-INF/gradle-plugins/gradlebuild.collect-failed-tasks.properties.
> Gradlebuild_collectFailedTasksPlugin
```

### Context (optional)

It seems that not all cached outputs are fetched from remote and/or restored into the output directory. All failing builds seems to have `FROM-CACHE` execution of `compileKotlin` task, which has remote errors:
![image](https://github.com/gradle/gradle/assets/7620037/b1c5a4a0-7193-4ecb-bf66-5da8ce0efd19)
The producing build (https://ge.gradle.org/s/ozwm42wcuz6m6) produces more files than were fetched: 
![image](https://github.com/gradle/gradle/assets/7620037/d46e8166-9e8b-47c3-a4d9-49b34cfe8fec)

Building the same commit locally with build cache NG enabled and using the same cache node completes successfully (with fetching from the remote cache), which suggests that the remote has all the data.

### Steps to Reproduce

It sometimes happens on CI. I salvaged the build cache database from the linked build and can provide it upon request.

### Gradle version

release (8.3), master (8.4)

### Build scan URL (optional)

https://ge.gradle.org/s/e4jaowoopekrq

### Your Environment (optional)

https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_CompileAllBuild_BuildCacheNG/68663408

**Comment by asodja** [comment]
We will remove prototype in https://github.com/gradle/gradle/pull/26323 and after we will implement new cache with new API. So this is not relevant anymore.
