### ISSUE TITLE
When I enable caching I get thousands of javac errors

### ISSUE THREAD

**Issue by mjaggard** [gradle/gradle#25812]
### Expected Behavior

The project should compile the source code.

### Current Behavior

It seems that the code is never compiled but "FROM-CACHE" is printed even on the first compile.

### Steps to Reproduce

I haven't managed to separate the problem from my code yet but the steps are:
1. Complex code base with many classes in 4 projects
2. A conventions plugin sets most of the configuration
3. A `shared` project with most of the code
4. Three projects that depend on `shared:compileJava` through  `dependencies { implementation(project(':shared')) }`

### Gradle version

8.2.1

### Your Environment (optional)

Amazon Linux 2

**Comment by mjaggard** [comment]
A working build scan (with `org.gradle.caching=false`) https://gradle.com/s/q7dv3wityimva

**Comment by mjaggard** [comment]
Is there some debug logging or item on the filesystem that I can enable and look for that will give me a clue why it thinks this task that has never been run is cached?

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

---

You can run gradle with `--debug` flag to investigate this. The output should contain all information about computing cache keys. As an alternative, you can run `./gradlew :shared:compileJava --rerun` which would force the task to rerun and force cache entries to be recomputed.

**Comment by mjaggard** [comment]
Thanks. I can't reproduce it consistently myself anyway.
