### ISSUE TITLE
Error opening zip file or JAR manifest missing gradle-instrumentation-agent-8.2.1.jar when execute gradle -v

### ISSUE THREAD

**Issue by houjibo** [gradle/gradle#25829]
### Expected Behavior

Execute `gradle -v` and show the version information

### Current Behavior

```bash
gradle -v
Error opening zip file or JAR manifest missing : **\Gradle\gradle-8.2.1/lib/agents/gradle-instrumentation-agent-8.2.1.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

### Steps to Reproduce

Not in project, just execute `gradle -v` in cmd windows.

### Gradle version

8.2.1

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

This issue will be closed after 7 days unless you provide more information.

***

Unfortunately, we can reproduce the behavior you observing. It might be a problem with your installation and/or environment. Please, provide step-by-step instructions on how to get to this issue starting from the process of installation. Please provide more details on your OS version and any relevant environment details.

**Comment by hawkeyeflash** [comment]
Download gradle version gradle-8.6 version from https://gradle.org/install/#helpful-information

Microsoft Windows users
In File Explorer right-click on the This PC (or Computer) icon, then click Properties -> Advanced System Settings -> Environmental Variables.

Under System Variables select Path, then click Edit. Add an entry for C:\Gradle\gradle-8.6\bin. Click OK to save.

Step 4. Verify your installation
Open a console (or a Windows command prompt) and run gradle -v to run gradle and display the version, e.g.:

Type in the following command:

C:\Users\bless.000>gradle -v
Error opening zip file or JAR manifest missing : C:\Gradle\gradle-8.6/lib/agents/gradle-instrumentation-agent-8.6.jar
Error occurred during initialization of VM
agent library failed to init: instrument
