### ISSUE TITLE
Test suits dependencies block fails when adding a platform defined in Version Catalog

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#25828]
### Expected Behavior

Using libraries defined in the version catalog can be used as platforms in the `dependencies` block of Test Suits.

```
testing.suites {
    val test by getting(JvmTestSuite::class) {
        useJUnitJupiter()
        dependencies {
            implementation(platform(libs.junit.bom))
        }
    }
}
```

### Current Behavior

The build fails with an error:

```
Could not determine the dependencies of task ':test'.
Could not resolve all dependencies for configuration ':testRuntimeClasspath'.
> Minimal dependencies are immutable.
```

### Steps to Reproduce

Reproducer project: https://github.com/alllex/gradle-repro-test-suits-with-platform-deps/tree/kotlin-dsl

### Gradle version

8.3-rc-1

### Build scan URL (optional)

https://scans.gradle.com/s/mfnrzmq52xym4

**Comment by leonard84** [comment]
I ran into this myself, just a note for the given example is that you should use `useJUnitJupiter(libs.versions.junit5)` to manage the jupiter version. However, the problem persists for other platforms.
