### ISSUE TITLE
Applying the OSGi plugin with Java 9 fails with NPE due to outdated bnd dependency

### ISSUE THREAD

**Issue by akarnokd** [gradle/gradle#2583]
### Expected Behavior
Given a Java 9 project (running on JDK 9b179), when adding `apply plugin: osgi`, there should be no NPE.

### Current Behavior
The build prints NPE:
```
java.lang.NullPointerException
    at aQute.bnd.header.OSGiHeader.quote(OSGiHeader.java:150)
    at aQute.bnd.header.Attrs.append(Attrs.java:416)
    at aQute.bnd.header.Attrs.append(Attrs.java:397)
    at aQute.bnd.header.Parameters.append(Parameters.java:175)
    at aQute.bnd.header.Parameters.toString(Parameters.java:164)
    at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:788)
    at org.apache.felix.bundleplugin.ManifestPlugin.getAnalyzer(ManifestPlugin.java:298)
< rest omitted >
```
According to the developer of the **bnd** plugin, Gradle ships with an older version. Version 3.3.0 should be compatible with Java 9:

> The latest version of bnd has fixes regarding Java 9. Gradle seems to ship with an older version of bndlib. For example:
>
> $ find gradle-4.1-rc-1 -name "*bnd*"
> gradle-4.1-rc-1/lib/plugins/biz.aQute.bndlib-3.2.0.jar
>
> Bnd 3.2 does not know about Java 9 [...] The `null` value there is the cause of the NPE. Bnd 3.3 learned about Java 9

### Context
The build succeeds nonetheless, but probably fails to update the manifest file. We are currently in a testing phase thus doesn't affect us much.

I know Java 9 support is still incomplete, but worth thinking about upgrading the **bnd** dependency to version 3.3.0.

### Steps to Reproduce (for bugs)
Build output: https://travis-ci.org/akarnokd/RxJava2_9/builds/257275524#L556
Project: https://github.com/akarnokd/RxJava2_9

### Your Environment
Travis-CI

**Comment by eljobe** [comment]
The fix is in. Thanks for the excellent bug report @akarnokd. This change should make it into the 4.2 version of Gradle.
