### ISSUE TITLE
Decide what to do for plugins modifying upgraded properties at execution time

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#25836]
It seems some plugins modify property value in doFirst, e.g. ErrorPronePlugin does:
```
tasks.withType<JavaCompile>().configureEach {
  doFirst("Configure forking for errorprone") {
     options.isFork = true
  }
}
```
see [source](https://github.com/tbroyer/gradle-errorprone-plugin/blob/5d83185c2fbcfeddac59fee8bbe2562d06d4a1d2/src/main/kotlin/net/ltgt/gradle/errorprone/ErrorPronePlugin.kt#L139C21-L139C21).

And after property upgrade we get:
```
* What went wrong:
Execution failed for task ':compileJava'.
> The value for task ':compileJava' property 'options' property 'fork' is final and cannot be changed any further.
```

Should we/can we handle that somehow? I guess in the end such plugins will need an update to be compatible

Let's decide what to do here for old plugins. Right now it seems difficult to make such plugins work with property upgrades.

Should we already display some warning at execution time even for "raw" type properties?

**Comment by asodja** [comment]
We actually do the same in our code: 
https://github.com/gradle/gradle/blob/b9ac289f2335c3b55e5b5402c85e84c05172a512/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L240

This is related to finalization of properties.

**Comment by asodja** [comment]
So ErrorProne basically wants to make sure `fork = true` is really used. So it try to configure the task last with doFirst:
```
tasks.withType<JavaCompile>().configureEach {
  doFirst("Configure forking for errorprone") {
     options.isFork = true
  }
}
```

I guess with Property solution would be:
```
tasks.withType<JavaCompile>().configureEach {
     options.isFork = true
     options.isFork.finalizeValue()
}
```

I wonder if we should have `Property.finalizeValue` that fails on change and  `Property.finalizeValueNoException` that would just warn if value tries to be changed.

**Comment by lptr** [comment]
ErrorProne should probably configure `fork = true` via normal configuration, and then add a check during runtime, and fail if the user somehow forced it back to `false`.

**Comment by asodja** [comment]
I've opened https://github.com/tbroyer/gradle-errorprone-plugin/issues/97 for ErrorProne.

**Comment by lptr** [comment]
Can we close this now since we introduced lenient finalization for upgraded properties?

**Comment by asodja** [comment]
Yes we can. 

So we implemented lenient finalization for migrated properties in https://github.com/gradle/gradle/issues/30715, that fixes also this issue.
