### ISSUE TITLE
Decide on `@Nested` property upgrades

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#25838]
We have many `@Nested` properties that has a setter, e.g.
```
abstract class CompileOptions {
    @Nested
    public ForkOptions getForkOptions() {
        return forkOptions;
    }

    public void setForkOptions(ForkOptions forkOptions) {
        this.forkOptions = forkOptions;
    }
}
```

We should decide how to handle upgrades for such properties. Should we even upgrade them? Right now it seems we shouldn't.
But that opens other questions, should we keep the setter or should we remove it? And how to handle that properly in the code instrumentation.

**Comment by lptr** [comment]
https://gradle.slack.com/archives/C02V8UKCXPT/p1686233636284569

**Comment by jvandort** [comment]
@lptr @asodja How hard would it be to list the places where this pattern appears?

My initial thought is to remove the setters. 

With just fork options as an example, I'd definitely vote to remove that setter. We never call it ourselves. I wouldn't expect a user to instantiate a `ForkOptions` themselves and pass that to the setter. I'd hope users are not calling `setForkOptions` with an instance from _another_ `CompileOptions`.

**Comment by asodja** [comment]
To get a list is a good idea. I can assemble it.

**Comment by asodja** [comment]
I found these:
```
org.gradle.api.plugins.quality.Checkstyle.getConfig()
org.gradle.api.plugins.quality.CodeNarc.getConfig()
org.gradle.api.plugins.quality.Pmd.getRuleSetConfig()
org.gradle.api.reporting.CustomizableHtmlReport.getStylesheet()
org.gradle.api.tasks.JavaExec.getDebugOptions()
org.gradle.api.tasks.JavaExec.getModularity()
org.gradle.api.tasks.compile.CompileOptions.getDebugOptions()
org.gradle.api.tasks.compile.CompileOptions.getForkOptions()
org.gradle.api.tasks.compile.GroovyCompile.getGroovyOptions()
org.gradle.api.tasks.compile.GroovyCompile.getOptions()
org.gradle.api.tasks.compile.GroovyCompileOptions.getForkOptions()
org.gradle.api.tasks.compile.JavaCompile.getModularity()
org.gradle.api.tasks.compile.JavaCompile.getOptions()
org.gradle.api.tasks.javadoc.Groovydoc.getOverviewText()
org.gradle.api.tasks.javadoc.Javadoc.getModularity()
org.gradle.api.tasks.javadoc.Javadoc.getOptions()
org.gradle.api.tasks.scala.ScalaCompile.getScalaCompileOptions()
org.gradle.api.tasks.scala.ScalaCompile.getScalaCompileOptions()
org.gradle.api.tasks.scala.ScalaDoc.getScalaDocOptions()
org.gradle.api.tasks.testing.AbstractTestTask.getFilter()
org.gradle.api.tasks.testing.Test.getDebugOptions()
org.gradle.api.tasks.testing.Test.getModularity()
org.gradle.api.tasks.testing.Test.getOptions()
org.gradle.jvm.application.tasks.CreateStartScripts.getModularity()
org.gradle.language.scala.tasks.AbstractScalaCompile.getOptions()
org.gradle.language.scala.tasks.AbstractScalaCompile.getScalaCompileOptions()
org.gradle.language.scala.tasks.BaseScalaCompileOptions.getForkOptions()
org.gradle.language.scala.tasks.BaseScalaCompileOptions.getIncrementalOptions()
org.gradle.plugins.signing.Sign.getGeneratorsByKey()
org.gradle.plugins.signing.Sign.getSignatory()
org.gradle.plugins.signing.Sign.getSignatureType()
org.gradle.process.JavaExecSpec.getModularity()
org.gradle.process.JavaForkOptions.getDebugOptions()
org.gradle.testing.jacoco.tasks.JacocoCoverageVerification.getViolationRules()
```

**Comment by lptr** [comment]
I'd like to hear @big-guy's opinion. I think the goal should be to drive these towards some consistent pattern. Having just a getter for `@Nested` properties sounds like a good pattern.

I would remove this issue from the migration's scope. We can mark the affected properties as `@NotToBeReplacedByLazyProperty` and move on.

**Comment by asodja** [comment]
> I would remove this issue from the migration's scope. We can mark the affected properties as @NotToBeReplacedByLazyProperty and move on.

This looks like a good decision to me. I've marked this with `has:decision`. We can re-evaluation this decision if we figure during migration that it's needs a different solution.

**Comment by lptr** [comment]
Shall we remove it from `p:lazy-migration` and the migration board?

**Comment by jvandort** [comment]
This has been marked with `has:decision`. Can we close this now?

**Comment by jvandort** [comment]
Closing, as a decision has been made

**Comment by asodja** [comment]
Thanks @jvandort!

**Comment by lptr** [comment]
Decision: `@Nested` properties are only a way to organize sub-properties, no need for laziness, provenance etc. They should be magically instantiated and exposed via a simple Java bean getter. Existing setters should be deprecated.
