### ISSUE TITLE
Gradle daemon eats all my memory + ignores org.gradle.daemon=false

### ISSUE THREAD

**Issue by napstr** [gradle/gradle#2586]
### Expected Behavior

I would expect gradle to eat a reasonable amount of memory. If that's impossible, I would at least expect it to adhere to passed JVM args like Xmx.
Also while 3.x at least was killing itself from time to time due to `org.gradle.daemon=false`, since updating to 4.0.1 the daemon is never stopped.

### Current Behavior

Gradle daemon blows up its memory usage out of all proportions, while not bothered by any restricting Xmx JVM args or daemon restrictions.

### Context

I'm trying to develop things which is impossible when the Gradle daemon takes up to 2 gigs of RAM (and probabyl would take more if I let it) of a project that runs on a 128MB JVM in production.

### Steps to Reproduce (for bugs)

Run a few debug builds of a project in IntelliJ.
Here is my `~/.gradle/gradle.properties`:
```
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx256m
```

### Your Environment

 * Build scan URL: I prefer to not share a document that contains completely unnecessary data for this case like IP addresses on a public github, so here are some of the properties listed there:
```
Total build time	2m 12.082s	 	 
Startup	5.410s	 	 
Settings and buildSrc	1.586s	 	 
Loading projects	0.950s	 	 
Configuring projects	9.261s	 	 
Task execution	1m 54.832s	 	 
End of build	0.043s	 	 
Total garbage collection time	0.873s	 	 
Peak heap memory usage		 
PS Eden Space	78.64/78.64 MB (100.0%)	 	 
PS Survivor Space	15.72/21.50 MB (73.1%)	 	 
PS Old Gen	71.13/179.31 MB (39.7%)	 

com.github.johnrengelman.shadow	2.0.1	External	com.github.jengelman.gradle.plugins.shadow.ShadowPlugin
com.gradle.build-scan	1.8	External	com.gradle.scan.plugin.BuildScanPlugin
com.jfrog.bintray	1.7.3	External	com.jfrog.bintray.gradle.BintrayPlugin
com.sedmelluq.jdaction	1.0.2	External	com.sedmelluq.discord.jdaction.NoActionPlugin
(ShadowApplicationPlugin)	2.0.1	External	com.github.jengelman.gradle.plugins.shadow.ShadowApplicationPlugin
(ShadowBasePlugin)	2.0.1	External	com.github.jengelman.gradle.plugins.shadow.ShadowBasePlugin
(ShadowJavaPlugin)	2.0.1	External	com.github.jengelman.gradle.plugins.shadow.ShadowJavaPlugin
application	-	Gradle	org.gradle.api.plugins.ApplicationPlugin
base	-	Gradle	org.gradle.api.plugins.BasePlugin
binary-base	-	Gradle	org.gradle.platform.base.plugins.BinaryBasePlugin
component-base	-	Gradle	org.gradle.platform.base.plugins.ComponentBasePlugin
distribution	-	Gradle	org.gradle.api.distribution.plugins.DistributionPlugin
help-tasks	-	Gradle	org.gradle.api.plugins.HelpTasksPlugin
idea	-	Gradle	org.gradle.plugins.ide.idea.IdeaPlugin
java	-	Gradle	org.gradle.api.plugins.JavaPlugin
java-base	-	Gradle	org.gradle.api.plugins.JavaBasePlugin
language-base	-	Gradle	org.gradle.language.base.plugins.LanguageBasePlugin
lifecycle-base	-	Gradle	org.gradle.language.base.plugins.LifecycleBasePlugin
reporting-base	-	Gradle	org.gradle.api.plugins.ReportingBasePlugin

1 active switch
Daemon 	On
Build Cache 	Off
Configure on demand 	Off
Continue on failure 	Off
Continuous 	Off
Dry run 	Off
Offline 	Off
Parallel 	Off
Re-run tasks 	Off
Refresh dependencies 	Off

Operating system	Linux 4.8.0-59-generic
CPU cores	4 cores
Max Gradle workers	4 workers
Java runtime	Oracle Java(TM) SE Runtime Environment 1.8.0_131-b11
Java VM	Oracle Java HotSpot(TM) 64-Bit Server VM 25.131-b11 (mixed mode)
Max JVM memory heap size	239 MB
```

I decided to look into the gradle process and it appears to not be aware of the RAM usage at all.
Here are a few relevant screenshots:
![image](https://user-images.githubusercontent.com/6048348/28583805-bcfbe984-716a-11e7-8091-902343a9a260.png)
![image](https://user-images.githubusercontent.com/6048348/28583810-c5c6c480-716a-11e7-8136-dbaf6ea56d20.png)
![image](https://user-images.githubusercontent.com/6048348/28583817-cb86cc1c-716a-11e7-81b3-8e48d0228231.png)

**Comment by TheBoegl** [comment]
@napstr could it be that the System Monitor shows virtual memory allocation, which the JVM is not designed to limit? Your seconds screenshot shows the max heap in the correct magnitude...

**Comment by oehme** [comment]
@napstr the memory recordings you posted show that the JVM is sticking to the memory limits you specified. You might want to check meta space usage (which you didn't limit). There could potentially be a third party plugin with a classloader leak causing the memory usage to grow over time.

I'm going to close this issue since it is not actionable from our side without more information. If you find that there is a classloader leak, please attach a heapdump for analysis.

**Comment by sanakhan-cms** [comment]
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
