### ISSUE TITLE
When used with jdk20, the error output of the compileJava task is garbled   

### ISSUE THREAD

**Issue by JoyfulAndSpeedyMan** [gradle/gradle#25866]
### Expected Behavior

When a java file has syntax errors, the error message compiled with the `.\gradlew.bat compileJava` command should be normal natural language text, not gibber

 

### Current Behavior

When gradle is used with jdk20, the java compiler error message is garbled.

 

#### jdk verison
```
java version "20" 2023-03-21
Java(TM) SE Runtime Environment (build 20+36-2344)
Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)
```
#### The following is the project structure of the demo instance
![image](https://github.com/gradle/gradle/assets/51226051/d879e900-9e75-4fcc-a772-6a2f378f99c4)

##### gradle/wrapper/gradle-wrapper.properties
```
#Sat Jul 22 14:49:56 CST 2023
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.2.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```
##### org/example/Main.java(Have grammatical errors)
```
package org.example;

public class Main {
    public static void main(String[] args) {
        // Note that there is a syntax error and the ending is missing ''; character
        System.out.println("Hello world!")
    }
}
```
##### build.gradle.kts
```
plugins {
    id("java")
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}

tasks.test {
    useJUnitPlatform()
}
```
##### settings.gradle.kts
```
rootProject.name = "gradle-and-jdk"

```

#### Use jdk20
![1690010215944](https://github.com/gradle/gradle/assets/51226051/d00ae30e-096a-43f7-8454-9c64cd53374f)

As you can see, in jdk20, compiling with gradle is problematic, but using javac directly is fine
#### Use jdk17 (Correct behavior)
![1690010254683](https://github.com/gradle/gradle/assets/51226051/ea215641-526a-4907-87d3-7a4a45533ac3)
In jdk17, everything works
### Gradle version

8.2.1

**Comment by ov7a** [comment]
@JoyfulAndSpeedyMan Gradle 8.2.1 does not support running with JDK 20.  Could you please try 8.3 RC1 where JDK 20 support was added? Another option is to use JDK 20 as toolchain and run Gradle with a lower version.
