### ISSUE TITLE
Gradle 8.3 won't allow plugin authors to support Gradle <7.0

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#25868]
### Expected Behavior

Able to support more than 1 major backwards? I'm actually not sure, just want to start a discussion.

This move, as it is, will either speed up Gradle upgrades because plugin authors will drop support for Gradle <7.0, or make plugin authors get stuck on Gradle 8.2.1.

### Current Behavior

Kotlin 1.9 embedded into Gradle 8.3 removed support for Kotlin 1.3.
(However, I did not find any references to this in [Kotlin Compatibility Guide 1.9](https://kotlinlang.org/docs/compatibility-guide-19.html), nor [1.9 Release Notes](https://kotlinlang.org/docs/whatsnew19.html), raised [on YouTrack](https://youtrack.jetbrains.com/issue/KT-60618).)

```
KotlinVersion.KOTLIN_1_3
              ^ Using 'KOTLIN_1_3' is an error. Unsupported
```

One potential workaround would have been `@Suppress("DEPRECATION_ERROR") KotlinVersion.KOTLIN_1_3`, but that will error (even with `"-Xsuppress-version-warnings"`):
```
> Task :compileKotlin FAILED
e: Language version 1.3 is no longer supported; please, use version 1.4 or greater.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

### Context (optional)

I briefly tried to upgrade Gradle to 8.3-rc-1 in Gradle Nexus Publish Plugin. And compilation of build.gradle.kts failed because we're explicitly setting Kotlin api/language to 1.3.

Maybe we're doing this wrong? How else can we make sure that the compiled Kotlin code is compatible with Gradle 6.x (or 5.x)? https://docs.gradle.org/8.3-rc-1/userguide/compatibility.html#kotlin

Note: if we had a Gradle version usage distribution chart, similar to what [Android](https://www.androidauthority.com/wp-content/uploads/2023/06/Android-version-distribution-statistics-May-2023-988w-675h.jpg.webp) has, we could make informed decisions to drop older versions.

### Steps to Reproduce

```gradle.kts
plugins {
    `kotlin-dsl`
}
kotlin.target.compilations.configureEach {
    compileTaskProvider.configure {
        compilerOptions.apiVersion = @Suppress("DEPRECATION") KotlinVersion.KOTLIN_1_3
        compilerOptions.languageVersion = @Suppress("DEPRECATION") KotlinVersion.KOTLIN_1_3
    }
}
```

### Gradle version

8.3-rc-1

### Gradle version that used to work

8.2.1

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

----

The currently supported way to build plugins for multiple Gradle versions is to build the plugin with the oldest supported Gradle version.

That being said, we don't forbid doing the opposite and folks to (including me).
I added a note in the upgrading guide about Kotlin 1.9.0 dropping support for Kotlin language <1.4.

I also added two integration tests to cover the related boundaries:
* one that make sure we don't break targeting the latest supported Kotlin language version
* one that demonstrates a workaround to target older _unsupported_ Kotlin language versions

Both changes are in
* https://github.com/gradle/gradle/pull/25901

**Comment by TWiStErRob** [comment]
Thank you @eskatos for the quick and detailed response!

> The currently supported way to build plugins for multiple Gradle versions is to build the plugin with the oldest supported Gradle version.

If people actually did that, they would be stuck with the feature set that the earliest version supports, only being able to call new APIs with reflection. Calling new APIs is pretty much required if plugin developers want to support new versions of Gradle. Example: the recently swap between Report.destination/outputLocation. Huh, actually, in this case we have to reflect either way 😅. A better example might be supporting configuration cache by using the Flow API instead of `buildFinished` on higher Gradle versions. Anyway, using the latest tooling helps us migrate away from deprecated APIs/approaches by simply fixing compilation warnings.

Interestingly, this statement seem to clarify why AGP is bumping its minimum Gradle all the time (apart from the maintenance cost of "the matrix").

> I also added two integration tests to cover the related boundaries

Thank you, these are really useful! Could these make their way into the plugin authoring docs in some short form?

If I get the gist of this, the pattern I showed above is "the way". What I was missing is that we can upgrade Gradle higher and higher, but we'll have to leave `kotlin-dsl` plugin version behind on the Gradle 8.2.1 level as long as we support Gradle <7, because of [embedded Kotlin compatibility](https://docs.gradle.org/8.3-rc-1/userguide/compatibility.html#kotlin).

> WARNING: Unsupported Kotlin plugin version.
> The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.9.0` that might work differently than in the requested version `1.8.20`.

Is there way to remove/force-version-of the embedded KGP from classpath (a'la `assumeNonEmbeddedGradleExecuter()`), so that `id("org.jetbrains.kotlin.jvm") version "1.8.20"` can take effect?

**Comment by eskatos** [comment]
With the _unsupported_ workaround in the integration test, you have to live with the emitted warnings.

The way forward is multi-variant plugins that can support multiple Gradle versions.
* See https://github.com/gradle/gradle/issues/25132
