### ISSUE TITLE
How to list configurations in Graddle project (without changing the build script)?

### ISSUE THREAD

**Issue by hrstoyanov** [gradle/gradle#25888]
### Issue type

Missing information

### Problem description

>./gradlew dependencies 

No longer works, because it requires mandatory configuration. Smart! So, how can one obtain a list of all available configurations?
Well, there is certainly nothing in the Gradle docs:
https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html

So one would go an google for "gradle show configurations" and will find all sorts of SO crap and obsolete information ...

### Context (optional)

I was able to get a list of configurations for the ap plugin, but ws hoping this would be a lot more readily available in the tool

### Page with the problem

https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

```
./gradlew dependencies
```
does work without any specified configuration. However invoked like that it applies to the root project which can be empty. You may need to invoke it by 
```
./gradlew :your-project:dependencies
```
