### ISSUE TITLE
Gradle 4.1-rc1 fails with Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext

### ISSUE THREAD

**Issue by kageiit** [gradle/gradle#2588]
```
./gradlew test --refresh-dependencies
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'fievel'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve gradle.plugin.com.kageiit:jacobo-plugin:2.0.5.
     Required by:
         project :
      > Could not resolve gradle.plugin.com.kageiit:jacobo-plugin:2.0.5.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
```

Once I can `./gradlew --stop`, the command succeeded on the next try

**Comment by bmuschko** [comment]
This might be the [same issue as described on the forum](https://discuss.gradle.org/t/ssl-problem-when-downloading-plugin-from-openjdk-1-7/23430/3).

Is this only happening with 4.1-rc1 or does it also occur with older versions of Gradle? Where is the plugin hosted you are trying to download?

**Comment by kageiit** [comment]
I only tried on 4.1-rc1 . Hard to repo now as it happened once and not again after the daemon was stopped.

The plugin is hosted on the Gradle plugins repository

**Comment by NilsRenaud** [comment]
Same bug for me in gradle 4.2.1 with newly installed Java 9. Any solutions ?

```
------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-Ubuntu (Oracle Corporation 9-Ubuntu+0-9b161-1)
OS:           Linux 4.10.0-35-generic amd64
```

**Comment by bmuschko** [comment]
Is this still happening with Gradle 4.3.1?

**Comment by bmuschko** [comment]
@kageiit Does this still happen with the latest version of Gradle?

**Comment by kageiit** [comment]
Have not seen it on 4.3.1 so far

**Comment by bmuschko** [comment]
Thanks for the feedback. I am going to close the issue for now. Please let us know if should you see the issue with newer Gradle versions going forward.

**Comment by aloktech** [comment]
I faced the similar issue as well with the Gradle version 4.5.1. It is mentioned below
Could not resolve joda-time:joda-time:2.9.9.
 > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext

**Comment by legendtang** [comment]
I've faced the same issue when building Web Applications using Gradle v4.6.

java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
	java.base/java.lang.Class.forName0(Native Method)
	java.base/java.lang.Class.forName(Class.java:292)
