### ISSUE TITLE
Jacoco v0.8.10 with Java 17 shows 0% code coverage for Android application module, but not for library modules.

### ISSUE THREAD

**Issue by saurabh-somani-philips** [gradle/gradle#25881]
### Expected Behavior

Code coverage should be reported for all modules (in a multi-module project).

### Current Behavior

But Jacoco is not reporting code coverage for the application module. Jacoco report shows 0% code coverage for the app module only. Library modules report coverage as expected.

### Context (optional)

I recently updated one of my Android projects to use Java 17 instead of Java 8, and to support Jacoco for the same, I updated Jacoco to the latest version, i.e., v0.8.10. During my testing, I realised coverage is reported for v0.8.8, but not for v0.8.9 and v0.8.10.

I have asked the same question on StackOverflow as well. [Here](https://stackoverflow.com/questions/76754303/android-jacoco-0-8-10-shows-0-code-coverage-when-upgraded-to-java-17-from-java) is the link.

### Steps to Reproduce

For testing purpose, I created a sample project to test different versions of Jacoco with Java 17.
[Here is the GitHub repo link.](https://github.com/saurabh-somani-philips/CodeCoverageIssue/tree/coverage-issue)

Added one JUnit4 test class to test the code coverage. Just run 'jacocoTestReport' Gradle command for the app module. Jacoco report is generated, but the code coverage shown is 0%.

Sorry, writing this section in a hurry.

### Gradle version

8.0

### Gradle version that used to work

8.0

### Your Environment (optional)

IDE: Android Studio Flamingo
Build System: Gradle
System: Mac OS Monterey (Intel chip)

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the Android Gradle Plugin, which is developed by Google and cannot be addressed in the Gradle Build Tool project.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug
