### ISSUE TITLE
Add option for --use-compress-program on Tar Gradle Task

### ISSUE THREAD

**Issue by pal-npateel** [gradle/gradle#25882]
### Expected Behavior

Hi Gradle team!

I would like to be able to add options to the Tar Task type to use a `Compression` type that isn't GZIP or BZIP2 by using the `--use-compress-program` flag for tar. 

### Current Behavior (optional)

Currently, we can only use BZIP2 or GZIP right now.

### Context

Currently, I'm compressing 20GB worth of files on a beefy 12-core / 24-core vms. Currently, TAR tasks take way too long to execute because we can't use parallel libraries like [pigz](https://github.com/madler/pigz) and [lbzip2](https://github.com/kjn/lbzip2/) libraries instead of the standard gzip and bzip2. Allowing us to specify the `--use-compress-program` option would significantly speed up tar tasks (without having to do weird hacky things like use exec tasks instead -- some of our tooling requires a TAR task to be executed)

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

Such use case would be better addressed with custom tasks which triggers a proper tool for that. It's unfeasible for us to support all possible compression types.
