### ISSUE TITLE
ArtifactView withVariantReselection improperly reselects dependencies with explicit artifacts

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#25908]
### Expected Behavior

Consider the following buildscript, which attempts to fetch sources for three modules published to Maven.

The first dependency on `foo` requests classifier `jdk8`, which in this hypothetical scenario, is identical to the default artifact, except it is compiled for a different JDK version. Simply, it has the same sources. I would expect the sources of the default artifact to be resolved (`foo-sources.jar`). 

The second dependency on `bar` requests classifier `test-fixtures`, which in this hypothetical scenario, is a separate library compared to the default artifact, and therefore should resolve to a separate set of sources (`bar-test-fixtures-sources.jar`).

The third dependency on `baz` requests extension `zip`, which in this hypothetical scenario, has no sources artifact. I would expect no artifact to be selected for this dependency. 

```
plugins {
    id 'java'
}

dependencies {
    implementation "org:foo:1.0:jdk8"
    implementation "org:bar:1.0:test-fixtures"
    implementation "org:baz:1.0@zip"
}

task resolve {
    def files = configurations.runtimeClasspath.incoming.artifactView {
        withVariantReselection()
        attributes {
            attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
            attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.DOCUMENTATION))
            attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.EXTERNAL))
            attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named(DocsType, DocsType.SOURCES))
        }
    }
    doLast {
        println files.files
    }
}
```

However, in this scenario, given that the user is requesting classifiers/extensions by declaring artifacts on the dependency, as opposed to using native Gradle functionality such as attributes and capabilities, Gradle does not have enough information to select the "correct" sources.

Each of the 3 above example dependencies would require Gradle to use different heuristics. Given the three examples, the "proper" behavior would be 

1. Return the main sources
    - We would essentially allow reselection to access the original artifacts for variants other than the graph-selected variant (which has overridden attributes)
    - This behavior would incorrectly return the main sources for `bar`, which expects the test fixtures sources
2. Return the test-fixtures sources
    - This would require arbitrarily adding "-sources" to the original requested artifact, however determining this from the reselection attributes would rely on arbitrary heuristics, which is not a desirable solution. 
    - This behavior would incorrectly fail to find the main sources for `foo`, and instead request a non-existent `jdk8-sources` jar. 
3. Return nothing
    - This is the simplest solution, and will not be "wrong" in some cases like the above two solutions, but this differs from existing behavior as explained below. 

### Current Behavior

Currently, the original (overridden) artifact is always returned during re-selection. The re-selection attributes are not taken into account when re-selecting artifacts for variants that were referenced by dependencies with explicit attributes. 

In practice, this can lead to scenarios where like in the above example, the user wants all sources for their runtime classpath, but instead only gets sources for _some_ dependencies, while for all dependencies with declared classifiers, they get the compiled jar. 

### Context (optional)

This is particularly relevant, as we are currently attempting to replace the usage of `ArtifactResolutionQuery` for downloading sources and javadoc for IDE import in [`IdeDependencySet`](https://github.com/gradle/gradle/blob/master/subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/resolver/IdeDependencySet.java#L102)

A [prototype PR](https://github.com/gradle/gradle/compare/jvandort/hacks/avoid-arq-when-resolving-aux-artifacts-for-ide?expand=1) was created to replace this with `ArtifactView` and `withVariantReselection`, however this issue arose as a result. 

There are two likely solutions to this issue. We could go with behavior (1) from above or behavior (3). Behavior (2) should was ruled out since it relies on arbitrarily modifying the requested classifier based on the requested sources. 

Behavior (1) would maintain the most compatibility with the behavior of `IdeDependencySet` currently, as the main sources are always downloaded for any dependency with an explicit artifact -- regardless of whether the user "meant" for that artifact to have the same sources as the main jar (like the `jdk8` example), or different sources (like the `test-fixtures` example)

Behavior (3) would be more correct in general, as it will never produce the "wrong" result (as in returning the production sources as opposed to the test fixtures sources). This solution would likely be better for `withVariantReselection` as a whole, even when users are manually requesting sources, however this behavior is different to how `IdeDependencySet` currently downloads sources.

**Comment by tresat** [comment]
I think we'd want behavior 3 here.  Behavior 1, even if it is current, isn't doing what the user requested and should be seen as a bug to be patched rather than a something important to preserve.  It should be an easy change for anyone relying on that behavior to get the main sources by removing the classifier.
