### ISSUE TITLE
Getting `org.gradle.tooling.UnsupportedVersionException` on previously working branch

### ISSUE THREAD

**Issue by AdamMarton** [gradle/gradle#25917]
### Expected Behavior

My build should finish as before.

### Current Behavior

My build is broken due to the following:

```
org.gradle.tooling.UnsupportedVersionException:
The version of Gradle you are using (Gradle distribution 'https://services.gradle.org/distributions/gradle-8.2.1-all.zip')
does not support the BuildLauncher API. Support for this is available in Gradle 1.2 and all later versions.
```

### Context (optional)

This exception is related to a SonarCloud check.

### Steps to Reproduce

Can't really tell, this was working fine before and it suddenly started throwing exceptions.

### Gradle version

8.2.1

### Build scan URL (optional)

https://scans.gradle.com/s/muiajvvt6eibm

### Your Environment (optional)

Drone

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

@gradle/bt-ide-experience does the message rings a bell? @ljacomet  says you know something about it:)

**Comment by AdamMarton** [comment]
Hi @ov7a,

Thank you so much for the super quick response. I used Gradle Project Replicator, can you please let me know what's next?
What is the output you need from it (and how can I send that to you)?

Thanks,
Adam

**Comment by ov7a** [comment]
@AdamMarton The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). So, the output is a GitHub repository containing the Gradle project you obtained via Gradle Project Replicator, preferably with a GitHub action result containing the unsuccessful run with the issue.

**Comment by AdamMarton** [comment]
Thanks so much, @eskatos!

I'm afraid I'll be unable to send you this as this issue only happens in our Drone environment and I don't think I can spin up a new repository/pipeline for this.

However, can you please help me to understand the error message:

> The version of Gradle you are using (Gradle distribution 'https://services.gradle.org/distributions/gradle-8.2.1-all.zip')
does not support the BuildLauncher API. Support for this is available in Gradle 1.2 and all later versions.

Is 1.2 actually referring to Gradle version (which is 8.2.1) as you can also see in the message. Isn't this contradicting?

Thanks,
Adam

**Comment by eskatos** [comment]
It is contradicting and looks like a bug. But as explained we'd need a reproducer in order to track this down if the sole error message is not enough for our team to figure out where/what the problem is.

**Comment by AdamMarton** [comment]
I'm trying to work out how can I provide you a reproducer. In the meantime, may I ask if some traces would help in any way?

**Comment by AdamMarton** [comment]
Hi @eskatos,

This is the content of `build/project-structure.json`, not sure if it helps.
Oddly, it has no mention of sonar at all, while it is defined as a dependency.

```
{
  "gradle": "8.2.1",
  "agp": "n/a",
  "kotlin": "n/a",
  "properties": [],
  "rootModule": {
    "path": ":",
    "plugins": [
      "java"
    ],
    "javaSources": {
      "fileCount": 54
    },
    "javaResources": {
      "json": [
        1451,
        1491,
        1481,
        1471,
        1005,
        1037,
        1029,
        1021
      ],
      "xml": [
        424
      ]
    },
    "dependencies": [
      {
        "library": "au.com.dius:pact-jvm-consumer-junit_2.12:3.6.15",
        "method": "testImplementation"
      },
      {
        "library": "com.amazonaws:aws-java-sdk-s3:1.12.170",
        "method": "implementation"
      },
      {
        "library": "com.amazonaws:aws-lambda-java-core:1.2.1",
        "method": "implementation"
      },
      {
        "library": "com.amazonaws:aws-lambda-java-events:3.11.0",
        "method": "implementation"
      },
      {
        "library": "com.amazonaws:aws-lambda-java-log4j2:1.5.1",
        "method": "runtimeOnly"
      },
      {
        "library": "com.amazonaws:aws-xray-recorder-sdk-aws-sdk-core:null",
        "method": "implementation"
      },
      {
        "library": "com.amazonaws:aws-xray-recorder-sdk-aws-sdk-v2-instrumentor:null",
        "method": "implementation"
      },
      {
        "library": "com.amazonaws:aws-xray-recorder-sdk-aws-sdk-v2:null",
        "method": "implementation"
      },
      {
        "library": "com.amazonaws:aws-xray-recorder-sdk-bom:2.11.0",
        "method": "implementation"
      },
      {
        "library": "com.amazonaws:aws-xray-recorder-sdk-core:null",
        "method": "implementation"
      },
      {
        "library": "com.contentful.java:java-sdk:10.5.2",
        "method": "implementation"
      },
      {
        "library": "com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.13.1",
        "method": "implementation"
      },
      {
        "library": "com.github.contentful.rich-text-renderer-java:html:760b75e3db",
        "method": "implementation"
      },
      {
        "library": "com.github.javafaker:javafaker:1.0.2",
        "method": "testImplementation"
      },
      {
        "library": "com.github.spotbugs:spotbugs-annotations:4.7.3",
        "method": "compileOnly"
      },
      {
        "library": "com.sendgrid:sendgrid-java:4.8.3",
        "method": "implementation"
      },
      {
        "library": "junit:junit:4.13.2",
        "method": "testImplementation"
      },
      {
        "library": "org.apache.logging.log4j:log4j-api:2.17.2",
        "method": "implementation"
      },
      {
        "library": "org.apache.logging.log4j:log4j-core:2.17.2",
        "method": "implementation"
      },
      {
        "library": "org.apache.logging.log4j:log4j-slf4j18-impl:2.17.2",
        "method": "runtimeOnly"
      },
      {
        "library": "org.assertj:assertj-core:3.22.0",
        "method": "testImplementation"
      },
      {
        "library": "org.mockito:mockito-core:4.3.1",
        "method": "testImplementation"
      },
      {
        "library": "org.projectlombok:lombok:1.18.12",
        "method": "annotationProcessor"
      },
      {
        "library": "org.projectlombok:lombok:1.18.12",
        "method": "compileOnly"
      },
      {
        "library": "software.amazon.awssdk:secretsmanager:2.17.141",
        "method": "implementation"
      }
    ]
  },
  "modules": []
}
```

**Comment by AdamMarton** [comment]
Closing this, as the issue is related to the most recent Sonar plugin.

**Comment by lukaswickenhauser** [comment]
@AdamMarton did you resolve this issue? I am facing the same issue and dont know how to solve it

**Comment by AdamMarton** [comment]
Hey Lukas, I did by downgrading Sonar.
