### ISSUE TITLE
Remnants of build status remains during JMH execution

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2591]
### Current Behavior
Console display looks like this on Gradle 4.0.1 and Gradle 4.1 RC1

```
# Warmup Iteration   8: 47.794 ops/ss]
# Warmup Iteration   9: 45.496 ops/ss]
# Warmup Iteration  10: 44.607 ops/ss]
Iteration   1: 48.616 ops/sNG [4m 59s]
Iteration   2: 48.654 ops/sNG [5m 0s]
Iteration   3: 47.578 ops/sNG [5m 1s]
Iteration   4:  99% EXECUTING [5m 2s]
<============-> 99% EXECUTING [5m 3s]
> IDLE
> :core:jmh
```

### Expected Behavior
Notice the "NG [5m 0s]" and so on during the iterations. 

### Context
This isn't a deal-breaker but it definitely isn't the UX we're going for. 

### Steps to Reproduce (for bugs)
```
$ cd gradle/gradle
$ git checkout b808acc
$ ./gradlew :core:jmh
```

### Your Environment

 * Build scan URL: https://e.grdev.net/s/unvfyo7kk2oqg

**Comment by big-guy** [comment]
This also reproduces it (`gradle print`):
```
task print << {
   (1..100).each {
      print "Hello, "
      System.out.flush()
      Thread.sleep(150)
      println "World!"
  }
}
```

**Comment by eriwen** [comment]
Ah, thanks for short-circuiting the investigation @big-guy!
