### ISSUE TITLE
while running for sonarqube analysis of grdla build i got the below issue--Project 'sonar' not found in root project 'java-gradle-simple'.

### ISSUE THREAD

**Issue by venkatmeena** [gradle/gradle#2592]
### Your Environment

 * Build scan URL:

**Comment by bmuschko** [comment]
The [SonarQube plugin](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Gradle) is an external plugin. I suggest you ask over there.

Please also fill in the template for future issues you open here so we can better help you.
