### ISSUE TITLE
MavenPublication: properties of AbstractArchiveTask not considered

### ISSUE THREAD

**Issue by kuzuk** [gradle/gradle#2593]
MavenPublication can reference Jar and Zip tasks but does not consider the attributes (baseName, appendix, version, classifier and extension) of AbstractArchiveTask

```
task customJar(type: Jar, dependsOn: jar) {
    baseName 'my-custom-artifact'
    ....
}
assemble.dependsOn customJar
```

```
publishing {
	publications {
        	publishJars(MavenPublication) {
	            	from components.java
 			artifact customJar
	    	}
	}
}
```
### Expected Behavior
An artifact with artifactId 'my-custom-artifact' is published

### Current Behavior
An artifact with artifactId=project-name is published 
...or...
> Failed to publish publication 'publishJars' to repository 'maven'
> Invalid publication 'publishJars': multiple artifacts with the identical extension and classifier ('jar', 'null').

### Context
Jar tasks allow for defining custom jars in a nice way. MavenPublication should support publishing those jars naturally. However, it will not consider the baseName and AFAIU does not consider any of the other properties. Instead it uses the project name as artifactId. An artifactId can be defined in MavenPublication, but it then applies for the whole project. So again publishing different artifactIds is not possible.

### Steps to Reproduce (for bugs)
see snippets above

### Your Environment

> ------------------------------------------------------------
> Gradle 4.0
> ------------------------------------------------------------
> 
> Build time:   2017-06-14 15:11:08 UTC
> Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5
> 
> Groovy:       2.4.11
> Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
> JVM:          1.8.0_131 (Oracle Corporation 25.131-b31)
> OS:           Linux 2.6.32-696.3.2.el6.x86_64 amd64

**Comment by bmuschko** [comment]
As far as I know Maven does not support changing the base name, appendix or the version for artifacts that are published together. Makes sense to me as they will end up in the same place on the Maven repo. Please be aware that this is different from Ivy if that's what you are used to. 

However, changing the `classifier` and `extension` works fine and also [lines up with their documentation](https://maven.apache.org/pom.html#Maven_Coordinates). See the following example demonstrates the use case:

```
apply plugin: 'java'
apply plugin: 'maven-publish'

version = '1.0'
group = 'com.company'

task sourcesJar(type: Jar) {
    classifier 'sources'
    extension 'aar'
    from sourceSets.main.allSource
}

artifacts {
    archives sourcesJar
}

publishing {
    publications {
        mavenPub(MavenPublication) {
            from components.java
            artifact sourcesJar
        }
    }

    repositories {
        maven {
            url "$buildDir/repo"
        }
    }
}
```

**Comment by bmuschko** [comment]
Given my reasoning and example above I am going to close the issue. Feel free to further comment or reopen the issue if you want to discuss further.
