### ISSUE TITLE
Gradle 8.3-rc-2 complains about unsupported JDK 20

### ISSUE THREAD

**Issue by xRomZak** [gradle/gradle#25938]
### Expected Behavior

Build on JDK 20 w/o issues. No error on Gradle 8.3 rc-1

### Current Behavior

```
Unsupported Java. 
Your build is currently configured to use Java 20.0.2 and Gradle 8.3-rc-2.

Possible solution:
 - Use Java 19 as Gradle JVM: Open Gradle settings 
 - Open Gradle wrapper settings, change `distributionUrl` property to use compatible Gradle version and reload the project
 ```

### Steps to Reproduce

Gradle 8.3 rc-2 + Kotlin 1.9.0 + JDK 20

### Gradle version

8.3-rc-2

**Comment by natros** [comment]
I have seen this error, but only with intellij 2023.2

**Comment by xRomZak** [comment]
yeah, seems you are right. Just updated the Idea to the same version.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/newIssue?project=IDEA.
