### ISSUE TITLE
Dependency substitution doesn't work for boms of boms published not as a gradle module unless you include every build

### ISSUE THREAD

**Issue by Thrillpool** [gradle/gradle#25948]
### Expected Behavior

I find myself in this admittedly strange situation, I produce a bom via Gradle.

Someone other than me consumes my bom and produces another bom.

Later down the line I consume their bom.

I want to be able to in the place I consume their bom, do dependency substitution on my bom. It should be if I consume their bom and --include-build my bom, I can witness changes I make locally to my bom.

### Current Behavior

Instead, dependencies shows a sort of 'flattened' view, it doesn't reference my bom at all, instead it just references the top level bom and it extracts the relevant constraints from the nested bom.

### Context (optional)

Essentially I have a large project X, and a project Y that consumes X, plus some other stuff not in X. I want to develop on X and see my changes reflected in Y. This includes changes to the bom I produce in X. The people who produce the bom that contains my bom, they don't produce module metadata (everything works if all boms in the chain produce metadata).

### Steps to Reproduce

Go to 
https://github.com/Thrillpool/gradle-bom-repro

go to child-bom folder and do publishToMavenLocal
go to composite-bom folder and do publishToMavenLocal
go to project-using-composite and run dependencies

Now change 'com.fasterxml.jackson.core:jackson-databind:2.9.0' in child-bom to 'com.fasterxml.jackson.core:jackson-databind:2.4.0'

do `dependencies --include-build ../child-bom` in project-using-composite and observe that the 2.9.0 is still coming through

do `dependencies --include-build ../child-bom --include-build ../composite-bom` in project-using-composite and observe that now 2.4.0 is coming through

### Gradle version

8.0 in the reproduction, tried with 8.2 also.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is the expected behavior, and there’s no plan to change it. This issue will be closed.

***

This is a limitation of a maven pom format: `dependencyManagement` `import` is not visible as a dependency. Just like you said, Gradle module metadata will work.

**Comment by Thrillpool** [comment]
Fair enough, thank you for the prompt response. I worked out a way to work around it, it's not very nice but for future reference for people hitting this issue. At configuration time I download the bom that I don't control (composite-bom in this example) and I effectively reconstruct it in my project (project-using-composite  in this example), i.e. now in project-using-composite I dynamically get a enforcedPlatform on child-bom as well as pick up all the other constraints from composite-bom, and as such the compositing works.
