### ISSUE TITLE
Use of deprecated plexus-cipher plugin results in insecure randomness

### ISSUE THREAD

**Issue by mattdsteele** [gradle/gradle#25943]
### Expected Behavior

Hi, I recently performed a security scan of the most recent Gradle package using [JFrog X-Ray](https://jfrog.com/xray/), which identified a potentially insecure dependency.

In particular, reliance on `lib/plugins/plexus-cipher-1.7.jar` has a reported security in the `PBECipher.java` file.

More details on the vulnerability: https://bugzilla.redhat.com/show_bug.cgi?id=880279

This was fixed in a planned 1.8 release, but was never published in this line. The source code for `plexus-cipher`: https://github.com/sonatype/plexus-cipher/commit/6ab0e38df80beed9ab3227ffab938b21dcdf5505

A newer version of the `plexus-cipher` was published, but moved to a different groupId `org.codehaus.plexus`, rather than under the Sonatype group.

https://mvnrepository.com/artifact/org.codehaus.plexus/plexus-cipher/1.8

I only see one reference to the `plexus-cipher` dependency in this repo, but I'm not sure if there are any other references, so I held off on submitting a PR.

### Current Behavior

The bundled version of `plexus-cipher` in the `lib/plugins` directory of a Gradle build should be updated to use a version that does not include known vulnerabilities.

### Steps to Reproduce

You can reproduce by running an [X-Ray security scan](https://jfrog.com/xray/) on `gradle-8.2.1-bin.zip`. See the description for details on the vulnerability. 

### Gradle version

8.2.1

**Comment by ov7a** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

***

Please, report any security issues following [our policy](https://github.com/gradle/gradle/security/policy).

**Comment by jbartok** [comment]
This has already been done as part of 
* https://github.com/gradle/gradle/pull/18769
