### ISSUE TITLE
Comment in Unix wrapper code w.r.t. shell expansion of environment variables is wrong/misleading

### ISSUE THREAD

**Issue by tudortimi** [gradle/gradle#25958]
### Expected Behavior

The Unix wrapper contains the following code: https://github.com/gradle/gradle/blob/c8ca699854c0e8ee7f69c1db676bb25bff775de4/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt#L243-L247

This makes the user think that it's possible to use references to other environment variables in, for example, `GRADLE_OPTS`.

### Current Behavior

Any kind of "shellness" in the environment variables is actually explicitly ignored, because the wrapper actively escapes special characters.

### Context (optional)

I was trying to set the value of `gradle.user.home` using `GRADLE_OPTS` to `.gradle-${HOSTNAME}` and have Gradle expand `${HOSTNAME}` when it executes. The entire discussion is here: https://discuss.gradle.org/t/using-gradle-in-a-computer-cluster-causes-daemons-to-lock-each-other-out/46064.

### Steps to Reproduce

This issue is simple enough that it doesn't really need steps to reproduce.

### Gradle version

7.4.2 and beyond, but probably in older versions as well

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

Note that this behavior is expected due to [security advisory](https://github.com/gradle/gradle/security/advisories/GHSA-6j2p-252f-7mw8) and the documentation and the comment in the shell script should be adjusted accordingly.

**Comment by ov7a** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by Gauravpadam** [comment]
Hello, I'm a newcomer to Gradle and I'd like to assist in this issue. Can I be assigned to it?

**Comment by ov7a** [comment]
@Gauravpadam Yes! Thank you!

**Comment by Gauravpadam** [comment]
Hey @ov7a, I've been trying to setup up the gradle development environment but I keep getting some issues:
```
failed
:build-logic:integration-testing:generatePrecompiledScriptPluginAccessors
:build-logic:jvm:generatePrecompiledScriptPluginAccessors
org.gradle.api.plugins.InvalidPluginException: Could not find implementation class 'Gradlebuild_dependencyModulesPlugin' for plugin 'gradlebuild.dependency-modules' specified in jar:file:/C:/Users/haris/.gradle/caches/jars-9/o_b629fc574bd720b6c33fdb58d8c6da40/dependency-modules.jar!/META-INF/gradle-plugins/gradlebuild.dependency-modules.properties.
java.lang.ClassNotFoundException: Gradlebuild_dependencyModulesPlugin
Unable to load class 'Gradlebuild_dependencyModulesPlugin'
```

**What I've tried:**
1. Reinstalling JDK version 11, as suggested by [Contributing.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
2. I've tried running this on WSL and Ubuntu, But I keep facing the same issue
3. I've made sure that the path to _Java_ and _JAVA_HOME_ are set correctly

I can't figure out a solution, I'd really appreciate some help.

**Comment by ov7a** [comment]
Hey, @Gauravpadam! Sorry for the late reply, I was on vacation.

Given that your PR was merged I assume you figured out the solution. I assume it was a problem with your environment.

***

For the record, questions like these can be answered by our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/). You can receive help faster there.
