### ISSUE TITLE
ArtifactResolutionQuery.execute cannot be made lenient

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#2596]
We use this API to force download of javadoc/source artifacts during sync with the IDE (android studio). The code looks like this:

```
final DependencyHandler dependencies = project.getDependencies();

ArtifactResolutionQuery query = dependencies.createArtifactResolutionQuery();
query.forComponents(artifacts);

Class<? extends Artifact>[] artifactTypesArray = (Class<? extends Artifact>[]) new Class<?>[] {JavadocArtifact.class, SourcesArtifact.class};
query.withArtifacts(JvmLibrary.class, artifactTypesArray);
query.execute().getResolvedComponents();
```

The issue is that this may fail, which throws an exception and makes the whole sync fail (one instance a dev gave us was that the artifacts are on a custom Nexus instance with logging, which may fail due to incorrect cert, vpn, etc...).

We'd like this API to have a lenient mode, and a proper API to query for the failure, preferably not something like `ArtifactCollection.getFailures()` which returns hard to process `Throwable` instances.

**Comment by adammurdoch** [comment]
This method is already lenient (or supposed to be). Have you seen it fail with an exception? Do you have a stack trace?

**Comment by ducrohet** [comment]
I don't have a stacktrace (and won't be able to get one). The issue was not about the artifacts not being present, but about not being able to connect to the repo due to a missing custom certificate used for connection.

**Comment by adammurdoch** [comment]
It should be lenient for any failure, and give you a `UnresolvedComponentResult` in this case. Possibly there's something about that specific failure that causes it to escape out of the `execute()` method.

**Comment by ducrohet** [comment]
OK. I'm just going to wrap this code with a try/catch and just report possible errors to the users as warning.

If I get another report with an actual exception, I'll update this bug.

**Comment by oehme** [comment]
I'm going to close this issue. Please reopen it if it appears again.
