### ISSUE TITLE
Gradle reports build as long living from single use daemon

### ISSUE THREAD

**Issue by mark-vieira** [gradle/gradle#2597]
### Expected Behavior
The build scans plugin leverages `GradleBuildEnvironment.isLongLivingProcess()` to determine if the build was running using the daemon. This should only return `true` when the build is run in a *long lived* daemon process. That is, a daemon that has been, or could be, used for multiple builds.

### Current Behavior
Currently `GradleBuildEnvironment.isLongLivingProcess()` incorrectly returns `true` when a build is run with a single use daemon.

### Context
Build scans include information about the daemon, and whether it was used or not. Builds which run in a single use daemon due to JVM arguments will report in a build scans as having used the daemon, even if the daemon was not enabled or the user specified `--no-daemon` on the CLI. This is confusing as, while technically run in a daemon process, the daemon will never be reused, and will never have run another build, so the behavior would be the same had it been run in an embedded process.

Additional context in [Slack](https://gradle.slack.com/archives/C03A0MT6S/p1501869882612174)

### Steps to Reproduce (for bugs)
Create a gradle.properties file with `org.gradle.jvmargs=-Xmx6g`, then run a build with `--no-daemon`.

**Comment by adammurdoch** [comment]
This is the wrong method to be using to determine if we're running in the daemon, as there are other kinds of long living processes that aren't the daemon, such as using test kit in debug mode. The semantics of this method is simply that when it returns true, it is ok to retain state that can be reused in a subsequent build, not that the build is running in a daemon.

It might be better to add some new query methods that are more precise.

**Comment by big-guy** [comment]
+1 what Adam said.  I was thinking that it might be interesting to have information about daemon/single-use daemon/no daemon and the reasons why it was used.  So when we have a single use daemon, we could actually say "We had to start a daemon because the JVM was started with $fooArgs and the build requires $barArgs".

**Comment by mark-vieira** [comment]
The more nuanced the better. However, the testkit use case is something I hadn't considered, as we can produce build scans from this scenario as well. What _should_ we report in this scenario. I expect in any case where a process has run another build and might run another we would report as the daemon being used. Basically, in a build scan when we say the daemon was used it impacts the following:

1. Performance. Both the overhead of starting a new daemon, and the potential benefits of using a warm one. Either of which can be confirmed by looking the daemon tab in the performance section.

2. Reused state. That state from previous builds could have been reused in this build and affected its outcome.

I would say any environment that the above apply to should be reported (at least in a build scan) as the daemon being used.
