### ISSUE TITLE
Configuration cache space usage analysis broken with Gradle 8.3-rc-2

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#25975]
### Expected Behavior

I should be able to analyze configuration cache space usage using [gcc2speedscope](https://github.com/gradle/gcc2speedscope#gradle-configuration-cache-log-to-speedscope).

### Current Behavior

Gradle debug log in 8.3-rc-2 is incorrect and makes [gcc2speedscope](https://github.com/gradle/gcc2speedscope#gradle-configuration-cache-log-to-speedscope) fail to produce a valid speedscope file.

### Steps to Reproduce

[gcc2speedscope integration test](https://github.com/gradle/gcc2speedscope/blob/master/src/test/kotlin/gcc2speedscope/GradleIntegTest.kt#L25) is currently disabled due to the incompatibility.

### Gradle version

8.3-rc-2

### Gradle version that used to work

8.2.1

**Comment by ljacomet** [comment]
Fixed in #25968
