### ISSUE TITLE
When running `./gradlew --console=plain` no output is produced

### ISSUE THREAD

**Issue by mikeb01** [gradle/gradle#25972]
### Expected Behavior

When `./gradlew --console=plain` is run I would expect to see a log of the various tasks as they are running, i.e. the same information that is present when using `--console=rich` but as a simple serial log.

### Current Behavior

No output is produced.

### Context (optional)

In automated environment gradle is being run as a sub-process of another system and that is timing out.  It would be useful to have a log of the tasks completed.

### Steps to Reproduce

`./gradlew --console=plain`

### Gradle version

8.1.1

### Build scan URL (optional)

https://gradle.com/s/nbn6g3nga7bdm

### Your Environment (optional)

------------------------------------------------------------
Gradle 8.1.1
------------------------------------------------------------

Build time:   2023-04-21 12:31:26 UTC
Revision:     1cf537a851c635c364a4214885f8b9798051175b

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_345 (Azul Systems, Inc. 25.345-b01)
OS:           Linux 5.19.0-50-generic amd64

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Your build scan actually has a list of tasks as an output. Please, provide a proper isolated reproducer in you think you found a bug.
