### ISSUE TITLE
Provide better diagnostics for the "Unable to delete directory... Failed to delete some children..." error

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#25984]
### Expected Behavior

The "Unable to delete directory... Failed to delete some children..." error thrown by Gradle should be more helpful.

### Current Behavior

When running tests for the Android Gradle plugin, we occasionally run into the following flaky error:
```
Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:packageRelease'.
  ...
Caused by: java.io.IOException: Unable to delete directory 'C:\...\project\app\build\intermediates\incremental\packageRelease\tmp'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - C:\...\project\app\build\intermediates\incremental\packageRelease\tmp\release
	at org.gradle.internal.file.impl.DefaultDeleter.throwWithHelpMessage(DefaultDeleter.java:181)
	at org.gradle.internal.file.impl.DefaultDeleter.deleteRecursively(DefaultDeleter.java:114)
	at org.gradle.internal.file.impl.DefaultDeleter.ensureEmptyDirectory(DefaultDeleter.java:83)
	at org.gradle.internal.file.impl.DefaultDeleter.ensureEmptyDirectory(DefaultDeleter.java:75)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep$2.visitOutputProperty(RemovePreviousOutputsStep.java:121)
```

Note that the task names and directory names are not relevant as they may change. Our focus is on the error message.

The last lines of the error message just before the stack trace show the regular files or directories that Gradle is unable to delete (`packageRelease\tmp\release` in the above example).
   - If it is a regular file, the user can investigate that file with tools such as https://file-leak-detector.kohsuke.org, or report the issue to tools that are not Gradle.
   - However, if it is a directory, the user is stuck. **The error message doesn't say why the directory can't be deleted**. 
       + The most likely root cause in this case is the infamous `DirectoryNotEmptyException` on Windows where a deleting an empty directory might fail the first time but succeed if we retry. Here are some examples in [Gradle](https://github.com/gradle/gradle/blob/3dc80197fdc09fbf36e909951bd95aac4b769bc3/subprojects/files/src/main/java/org/gradle/internal/file/impl/DefaultDeleter.java#L148), [Apache Flink](https://github.com/zentol/flink/blob/edbccbb5c28b83b469385d8683b6751810598246/flink-core/src/main/java/org/apache/flink/util/FileUtils.java#L179), and the [Android Gradle plugin](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:common/src/main/java/com/android/utils/PathUtils.java?q=%22DirectoryNotEmptyException%20exception%22) where this retry logic is implemented.
       + It is possible to confirm this root cause by providing better diagnostics -- see below.
       
****Proposed Changes****       
I'm proposing 2 changes in Gradle to help with this error:
   1. In [DefaultDeleter](https://github.com/gradle/gradle/blob/3dc80197fdc09fbf36e909951bd95aac4b769bc3/subprojects/files/src/main/java/org/gradle/internal/file/impl/DefaultDeleter.java#L148), consider using "assertive" API such as `java.nio.file.Files.deleteIfExists` which throws instead of returning `false` when it can't delete a file/directory.
   2. In the retry logic of [DefaultDeleter](https://github.com/gradle/gradle/blob/3dc80197fdc09fbf36e909951bd95aac4b769bc3/subprojects/files/src/main/java/org/gradle/internal/file/impl/DefaultDeleter.java#L148), consider:
        - Adding more wait time between two retries (currently the wait time is 10ms)
        - Retrying a few more times (currently Gradle retries only once)
        - *(The [Android Gradle plugin](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:common/src/main/java/com/android/utils/PathUtils.java?q=%22DirectoryNotEmptyException%20exception%22) uses both strategies.)*       
        

### Steps to Reproduce

N/A (flaky error)

### Gradle version

8.2 (and earlier)

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.

**Comment by ov7a** [comment]
If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by hungvietnguyen** [comment]
Thank you for looking into this issue!

https://github.com/gradle/gradle/commit/40d03e20067b5ced795f4adfc89bd3d79c219dad improves the retry logic but unfortunately still doesn't address the main request of this bug, which is to provide the root cause of the "Unable to delete directory..." error.

Without knowing the root cause, it will be difficult for both the users and the software's authors to address the issue.

#### Request
1. **[Main request]** As proposed above, in [DefaultDeleter](https://github.com/gradle/gradle/blob/3dc80197fdc09fbf36e909951bd95aac4b769bc3/subprojects/files/src/main/java/org/gradle/internal/file/impl/DefaultDeleter.java#L148), please consider using "assertive" API such as `java.nio.file.Files.deleteIfExists` which throws instead of returning `false` when it can't delete a file/directory.
2. [Minor improvement] The retry logic in [DefaultDeleter](https://github.com/gradle/gradle/blob/3dc80197fdc09fbf36e909951bd95aac4b769bc3/subprojects/files/src/main/java/org/gradle/internal/file/impl/DefaultDeleter.java#L148) is suitable for the `java.nio.file.DirectoryNotEmptyException` only. It will not help for other exceptions. Therefore, consider running the retry logic only if the `DirectoryNotEmptyException` occurs (assuming request 1 has been implemented).

**Comment by hungvietnguyen** [comment]
Btw, here's a small example for why knowing the root cause is important:  https://github.com/gradle/gradle/commit/40d03e20067b5ced795f4adfc89bd3d79c219dad may not even be necessary if the root cause turns out to be some other issues different than `DirectoryNotEmptyException`.

**Comment by eskatos** [comment]
You're right, https://github.com/gradle/gradle/pull/26011 improve the behaviour but doesn't help with diagnosis.
