### ISSUE TITLE
Can i have multiple libs.versions.toml files in multi flavored android project?

### ISSUE THREAD

**Issue by akki2298** [gradle/gradle#25996]
### Expected Behavior

is there a way i can have multiple libs.versions.tom for each flavors and build that particular variant  with the actual dependencies it need  

### Context

My Android App have multiple flavors based on countries , i want to build particular set of dependencies based on country flavor and i am using version catalog for dependencies management so i am thinking if i can have multiple libs.versions.toml and i use libs.versions.toml based on country so that it only have dependencies that particular variant needs

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

You [can](https://docs.gradle.org/current/userguide/platforms.html#sec:multiple) use multiple `version.toml` files.
