### ISSUE TITLE
Updating gradle from 8.1.1 to 8.2.1 caused an error with isCanBeResolved

### ISSUE THREAD

**Issue by marlester-dev** [gradle/gradle#25998]
### Expected Behavior

Don't give an error, sync succesful.

### Current Behavior

Gives an error.
Updating gradle from 8.1.1 to 8.2.1 caused an error on this line:     ).onEach { it.isCanBeResolved = true }.
[Pastebin](https://pastebin.com/XFuXv9JJ) of the error.

### Context (optional)

In my build.gradle.kts
in shadowJar task I have
    configurations = listOf(
      project.configurations.implementation.get()
    ).onEach { it.isCanBeResolved = true }
to make implementation shadow.
Updating gradle from 8.1.1 to 8.2.1 caused an error on this line:     ).onEach { it.isCanBeResolved = true }.
[Pastebin](https://pastebin.com/XFuXv9JJ) of the error.

### Steps to Reproduce

1. Have gradle 8.1.1 kotlin dsl project
2. Have  project.configurations.implementation.get().isCanBeResolved = true or similar in your gradle executing somewhere
3. Update to 8.2.1 using ./gradlew wrapper --gradle-version=8.2.1
4. [Error ](https://pastebin.com/XFuXv9JJ)while sync!

### Gradle version

8.2.1 gives the error, 8.1.1 is fine.

### Your Environment (optional)

Intellij IDEA 2023.2 on windows.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

We weren't able to reproduce your problem using the steps you provided. Please provide a reproducer using the information above.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/newIssue?project=IDEA.

***

Note that we do not recommend setting `implementation` configuration to be resolvable. This will become an error in future versions of Gradle.
