### ISSUE TITLE
KTS allWarningsAsErrors option does not treat unused variables as errors

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#25997]
### Expected Behavior

When a build is configured with `org.gradle.kotlin.dsl.allWarningsAsErrors=true`, I would expect that adding `val unused = "foo"` to fail the build.

The following code with an unused `myTask` variable also succeeds but I would expect it to fail considering the unused variable.

```
val myTask by tasks.registering {
    doLast {
        println("Hello from myTask")
    }
}
```

Curiously, the following piece of code does cause the build to fail:

```
testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useKotlinTest("1.9.0")
        }
    }
}
```

### Current Behavior

In a build configured with `org.gradle.kotlin.dsl.allWarningsAsErrors=true` adding the following two code snippets cause a successful build:

1. 
`val unused = "foo"`

2.
```
val myTask by tasks.registering {
    doLast {
        println("Hello from myTask")
    }
}
```

This causes the build to fail:
3. 
```
testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useKotlinTest("1.9.0")
        }
    }
}
```

### Steps to Reproduce

Code snippets are above. Make sure the build has `org.gradle.kotlin.dsl.allWarningsAsErrors=true` in `gradle.properties`.

### Gradle version

8.2.1

### Build scan URL (optional)

https://ge.solutions-team.gradle.com/s/wnqvx7vtapxs2

**Comment by eskatos** [comment]
With Gradle 8.3 and Kotlin 1.9.0, in the `Current behavior` section, items 2/ and 3/ are now behaving correctly and uniformly: as item 2/ the variable is considered as used because the property delegate has side effects.
See https://youtrack.jetbrains.com/issue/KT-38871

Item 1/ is surprising though.

**Comment by eskatos** [comment]
Item 1/ reported as a Kotlin compiler bug at https://youtrack.jetbrains.com/issue/KT-60931

This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.
