### ISSUE TITLE
Document ArtifactView

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#26007]
### Expected Behavior

ArtifactView is documented

### Context

There is no documentation on `ArtifactView`. This is a very useful feature of Gradle and should be documented. 

Specifically, we should document
* Snippets which show common use-cases
* Solutions to common error cases
  * https://github.com/gradle/gradle/pull/25515#discussion_r1281234599
*

**Comment by Paraass** [comment]
I want to this. Could you please tell where is  documentation folder??

**Comment by ThadHouse** [comment]
For features that should be documented, it sounds like ArtifactView can be used to potentially resolve sources, javadocs, pom's and gradle module info for an artifact (Based on the comment at https://github.com/gradle/gradle/issues/10867). It'd be fantastic for that to be actually documented, I've been struggling for days on how to get that to actually work. ArtifactResolutionQuery doesn't work for gradle module files, and I need them explicitly.

**Comment by jvandort** [comment]
ArtifactView can be used to resolve sources and javadoc. This integ test shows how you would download sources for all dependencies in `runtimeClasspath`: https://github.com/gradle/gradle/blob/13e8484bae3825326c9d5cdfa0335bf7a3755751/platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/derived/JvmDerivedVariantsIntegrationTest.groovy#L82-L90

The code is similar for javadoc. 

You will have more difficulty with fetching metadata. I could see _maybe_ a way of doing this with using component metadata rules to generate custom variants using the metadata file as an artifact and selecting it with an artifact view -- though this would not fetch parent POMs.

**Comment by jvandort** [comment]
To those who landed on this page looking for some information on what an artifact view is, here is a short summary in lieu of an official documentation page.

Gradle splits up dependency resolution into two phases. Graph resolution and artifact selection. A `ResolutionResult` shows the output of the graph resolution. It is only concerned with nodes of a dependency graph. A Variant is a node of the graph. Dependencies are edges between nodes. 

An `ArtifactView` operates on top of the result of graph resolution. In general, you can think of a Configuration's `getFiles()` output to be an artifactView of the graph resolution using the same attributes as were used to build the graph. 

However, an explicit artifact view allows you to resolve artifacts from the dependency graph using _different_ attributes. Consider the following case:

I resolve the `runtimeClasspath` of a Java project. It uses the default attributes for that configuration (`category=library`, `usage=java-runtime`, etc) to build a graph. That means each dependency uses these attributes to find out what variant in the target component to point to. 

Using this graph, I can select attributes from it. For each node, I use _another_ set of attributes. For eacn node in the graph, I ask its owning component for a variant that matches these new attributes. So, if in the graph I have `runtimeElements` selected, I can _reselect_ (`withVariantReselection`) the node as if different attributes were originally requested. This for example is very useful for doing things like requesting all sources for all resolved jars, or requesting _test results_ for all resolved jars. In fact, jacoco and test report aggregation are built on top of variant reselection. 

In essence an `artifactView` (using variant reselection) allows you to select a _parallel_ variant for each variant in a graph. 

Using an `artifactView` without reselection IMO is not very interesting.

**Comment by cobexer** [comment]
As seen in 
* https://github.com/gradle/gradle/issues/27637 

we should also consider improving the error message when the underlying dependency resolution of an artifact view fails.

**Comment by Vampire** [comment]
Thanks for the explanation, even though I somehow still have the feeling this is a bit inconsistent with "lenient" with which an artifact view can resolve where the underlying configuration can not.

But one question regarding

> Using an artifactView without reselection IMO is not very interesting.

Is it not?
What about defining artifact transforms and then using an artifact view to get its results?
