### ISSUE TITLE
Gradle wrapper files changes without any noticeable change.

### ISSUE THREAD

**Issue by kiru** [gradle/gradle#2601]
### Expected Behavior

gradle-wrapper.properties should not change if I run `./gradlew wrapper`

### Current Behavior

gradle-wrapper.properties and gradle-wrapper.jar are recognized as changed from git.
This doesn't make any sense for me, because in the [documentation](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:wrapper_generation) it is stated, that all files in the gradle folder should be tracked by VCS, but why does the properties file keep a timestamp which changes each time I run the wrapper task?

### Context

I have a simple project, which uses gradle wrapper and is checked in in git. 

### Steps to Reproduce (for bugs)

Create a gradle project with the following setting:

```
group 'gradle'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.0.2'
}
```

Then run `./gradlew wrapper`. Add all files to git. Run the wrapper command again and see the following diff ( similar):

> $ git diff gradle/*
> diff --git a/gradle/wrapper/gradle-wrapper.jar b/gradle/wrapper/gradle-wrapper.jar
> index cfea593..6300110 100644
> Binary files a/gradle/wrapper/gradle-wrapper.jar and b/gradle/wrapper/gradle-wrapper.jar differ
> diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
> index c8a9510..3fc94ae 100644
> --- a/gradle/wrapper/gradle-wrapper.properties
> +++ b/gradle/wrapper/gradle-wrapper.properties
> @@ -1,4 +1,4 @@
> -#Thu Jul 27 12:01:59 CEST 2017
> +#Thu Jul 27 12:03:24 CEST 2017
>  distributionBase=GRADLE_USER_HOME
>  distributionPath=wrapper/dists
>  zipStoreBase=GRADLE_USER_HOME

### Your Environment

```
------------------------------------------------------------
Gradle 4.0.2
------------------------------------------------------------

Build time:   2017-07-26 15:04:56 UTC
Revision:     108c593aa7b43852f39045337ee84ee1d87c87fd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Mac OS X 10.12.5 x86_64

```

**Comment by lptr** [comment]
I think this has been fixed in 4.1-rc-1 already, see https://github.com/gradle/gradle/commit/18790288dfe4c3e4cd2fab6119a440f26f78e223. /cc @big-guy

**Comment by bmuschko** [comment]
I am pretty sure @lptr is correct here. @kiru Please try out 4.1-rc1 and let us know if it solves your problem.

**Comment by kiru** [comment]
@lptr @bmuschko can I test it with 4.1? ( I'm not sure because this issue is still open and 4.1 has been released). I it possible to backport this change to 3.x versions?

**Comment by big-guy** [comment]
@kiru If you generate the wrapper with 4.1, the wrapper jar and properties file should not change if you try to generate it again. 

We won't backport new features to 3.x (and I think a new 3.x release is unlikely in general), but you can use Gradle 4.1+ to generate a wrapper that downloads an older version of Gradle.

`gradlew wrapper --gradle-version=4.1`
`gradlew wrapper` (this downloads 4.1)
`gradlew wrapper --gradle-version=3.5` (the wrapper jar won't change)
