### ISSUE TITLE
Nested property types declared in kotlinx libraries are not supported since 8.3

### ISSUE THREAD

**Issue by shanshin** [gradle/gradle#26018]
### Current Behavior

When building a project that uses the [Kover Gradle plugin](https://github.com/Kotlin/kotlinx-kover) using Gradle version `8.3-rc-3`, warnings appear:
```
  - Type 'org.gradle.api.tasks.testing.Test' property 'jvmArgumentProviders' with nested type 'kotlinx.kover.gradle.plugin.appliers.JvmTestTaskArgumentProvider' is not supported. Reason: Nested types are expected to either declare some annotated properties or some behaviour that requires capturing the type as input. For more information, please refer to https://docs.gradle.org/8.3-rc-3/userguide/validation_problems.html#unsupported_nested_type in the Gradle documentation.
  - Type 'org.gradle.api.tasks.testing.Test' property 'toolVariant' with nested type 'kotlinx.kover.gradle.plugin.tools.KoverToolDefaultVariant' is not supported. Reason: Nested types are expected to either declare some annotated properties or some behaviour that requires capturing the type as input. For more information, please refer to https://docs.gradle.org/8.3-rc-3/userguide/validation_problems.html#unsupported_nested_type in the Gradle documentation.

```

### Expected Behavior

No warnings

### Context (optional)

The warning appears thanks to a [check](https://github.com/gradle/gradle/blob/e8b1b095f2872b229b45962e41a1f30a9ad7eaad/subprojects/model-core/src/main/java/org/gradle/internal/properties/annotations/NestedValidationUtil.java#L71) added in [this commit](https://github.com/gradle/gradle/commit/5c3aa7226330619bea30a73e974b20a47beef3f5).

Since the library classes are located in the `kotlinx.*` package (typical for many other non-std libraries, e.g. [coroutines](https://github.com/Kotlin/kotlinx.coroutines), [datetime](https://github.com/Kotlin/kotlinx-datetime) etc), they are not perceived as beans.

### Steps to Reproduce

Run tests in any Kotlin project with applied Kover Gradle Plugin

### Gradle version

8.3-rc-3

### Gradle version that used to work

8.2.1

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
