### ISSUE TITLE
Instrument plugins with artifact transform

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#26037]
We need this to instrument for property upgrades only plugins that were compiled with Gradle versions that don't have upgraded properties, example:
- plugin compiled with Gradle 8 -> instrument for cc + instrument for property upgrades 
- plugin compiled with Gradle 9 -> instrument for cc only

It seems artifact transform could be a good tool for that. Artifact transform will also simplify instrumentation a bit: no need for custom caching. 

Relates also to: https://github.com/gradle/gradle/issues/16181

**Comment by asodja** [comment]
Spikes:
https://github.com/gradle/gradle/pull/25444
https://github.com/gradle/gradle/pull/24942

**Comment by asodja** [comment]
Spike:
https://github.com/gradle/gradle/pull/26045

**Comment by lptr** [comment]
Changed to `a:chore` because this is a feature of the execution engine, but not a feature of the build tool itself.
