### ISSUE TITLE
Question: How to prevent tests to be run twice when having suites and singular tests

### ISSUE THREAD

**Issue by vjmaiky** [gradle/gradle#2603]
I have a Gradle project for mobile automation purpose.
Under the test/java structure i have a package "suites" (containing a suite) and a package containing 2 classes , each with 1 test (using junit whit annotation @).

SUITE:
@RunWith(Suite.class)
@Suite.SuiteClasses({
        Experiment.class,
        Experiment2.class
})
public class TestPrimer {
}

If i run the suite locally with Intelij (tests are run only 1).

PROBLEM:
if i run them with Jenkins, tests are run twice...
this is the task that i use in jenkins: -Dtest="TestPrimer.class" clean test -i

I read some forum posts that i need to exclude each test; but if i have 1mil tests? sounds impossible...

For sure i`m missing something. can someone help me/guide me?

Thanks.

Jenkins Gradle Plugin - 1.27.0
Platform Windows - Gradle version - 3.5 (updated it now to 4.0.2 and it is still happening) , Groovy 2.4.10

**Comment by bmuschko** [comment]
Could you please provide a simplistic sample project on GitHub so I can have a look?

**Comment by EtherealT** [comment]
Hi, I'm currently having this exact issue as well. Android studio runs the tests once, but when i run from gradle, it runs each test twice. @bmuschko you can recreate the problem with this repo: [EtherealT/me.-android](https://github.com/EtherealT/me.-android)

**Comment by EtherealT** [comment]
Well I'm no longer having the issue, I was specifying the suite file wrongly in the run command, I fixed that and the problem was fixed.

**Comment by bmuschko** [comment]
@vjmaiky We'll need to have a sample project to be able to reproduce your issue. Could you please provide one? I believe what is happening is that you include the suite class _and_ the test classes and therefore both are executed. If you just want to run the suite then you'll need to exclude the test classes via `test.exclude`.

**Comment by vjmaiky** [comment]
i`ll post it when i return from holiday; thanks

**Comment by vjmaiky** [comment]
ok so basically i have two tests:

public class Experiment2Test extends TestManager {
    @Test
    public void test1() {
    }
}

public class ExperimentTest extends TestManager {
    @Test
    public void test2() {
    }
}

and a suite:
@RunWith(Suite.class)
@Suite.SuiteClasses({
        ExperimentTest.class,
        Experiment2Test.class
})
public class TestSuite1{

}

On Jenkins i use:

Use Gradle Wrapper |  
  | Make gradlew executable
-Dtest="TestSuite1.class" clean test -i

and if i hit build test are run twice

**Comment by vjmaiky** [comment]
i managed to resolve my problem; thanks anyway.

**Comment by mmuszynska** [comment]
@vjmaiky but how?

**Comment by jlw8ke** [comment]
For the next poor soul that comes across this, using `@RunWith(Enclosed::class)` instead of `@RunWith(Suite::class)` should prevent the tests from being run twice.

**Comment by atulgpt** [comment]
@vjmaiky How did you resolve the issue?
