### ISSUE TITLE
Documentation: Provide a simple way to jump between released versions on the Gradle documentation

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#2604]
When I search Google for something like `sourceset gradle` the top link is https://docs.gradle.org/3.3/dsl/org.gradle.api.tasks.SourceSet.html

In order for me to go to the documentation for the version I am on I have to edit the url and go to the page.

It would be nice to have a more user-friendly method to switch between different documentation pages based on the Gradle version.

An example that I think is useful is the Docker documentation:

<img width="331" alt="Docker multiple versions select" src="https://user-images.githubusercontent.com/1447148/28679630-6f9d7766-72b9-11e7-95a2-5e5171b99530.png">

**Comment by eriwen** [comment]
Thanks for the feedback @mkobit! This is a good idea, and we may have some effort on the docs soon that can incorporate this idea — keep the suggestions coming.
