### ISSUE TITLE
build sourcecode

### ISSUE THREAD

**Issue by lianglinux5** [gradle/gradle#26054]
### Expected Behavior

Gradle:8.2.1

### Context

How to build and debug  by sourcecode
   Thanks!

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
