### ISSUE TITLE
Crash when use watch-fs in Windows

### ISSUE THREAD

**Issue by kobe2000** [gradle/gradle#26051]
### Current Behavior

gradle crashed in Windows when org.gradle.vfs.watch enabled

dump:
[hs_err_pid16972.log](https://github.com/gradle/gradle/files/12298937/hs_err_pid16972.log)

log with --debug:
[gradle.log](https://github.com/gradle/gradle/files/12299001/gradle.log)

### Expected Behavior

don't crash, build successfully

### Steps to Reproduce

Every time on my PC.

org.gradle.vfs.watch=true  --> crash
org.gradle.vfs.watch=false --> OK

### Gradle version

8.2.1

### Your Environment (optional)

Windows 10, JetBrains IDEA

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
