### ISSUE TITLE
Unable to make progress running work

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#26060]
### Current Behavior

Original issue: https://issuetracker.google.com/290954881

Check out project with `git clone git@github.com:android/nowinandroid.git && git reset --hard 0a20cb729b871514c056d91aa05244e0bfd86d24`.

Use Android Studio Hedgehog Canary 15 to import this project, and select `Build -> Rebuild Project` from the menu.

This results in: `Unable to make progress running work. There are items queued for execution but none of them can be started`

### Expected Behavior

Gradle should be able to execute requested tasks.

### Context (optional)

In Android Studio Hedgehog Canary 11, there was a change that modifies the order of tasks. Previously, Studio would request `:a:clean :b:clean :c:clean :a:assembleDebug :b:assembleDebug :c:assembleDebug`. In H C11+, the list of tasks is `:a:clean :a:assembleDebug :b:clean :b:assembleDebug :c:clean :c:assembleDebug` which seems to trigger an issue in Gradle.

### Steps to Reproduce

1. Check out project with `git clone git@github.com:android/nowinandroid.git && git reset --hard 0a20cb729b871514c056d91aa05244e0bfd86d24`.

2. Use Android Studio Hedgehog Canary 15 to import this project, and select `Build -> Rebuild Project` from the menu.

### Gradle version

8.2

**Comment by eskatos** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritised by them.

**Comment by asodja** [comment]
It can be reproduced with just:
```
./gradlew :app:assembleDemoDebug :ui-test-hilt-manifest:clean :ui-test-hilt-manifest:assembleDemoDebug  
```

**Comment by asodja** [comment]
It seems the problem is that `:app` depends on some output of `:ui-test-hilt-manifest` via:
```
debugImplementation(project(":ui-test-hilt-manifest"))
```

Due to that some tasks of `:ui-test-hilt-manifest` run before `:ui-test-hilt-manifest:clean` that was requested on the command line after `:app:assembleDemoDebug`, e.g.:
```
:ui-test-hilt-manifest:preBuild SKIPPED
:ui-test-hilt-manifest:preDemoDebugBuild SKIPPED
:ui-test-hilt-manifest:writeDemoDebugAarMetadata SKIPPED
:ui-test-hilt-manifest:generateDemoDebugResources SKIPPED
:ui-test-hilt-manifest:packageDemoDebugResources SKIPPED
:ui-test-hilt-manifest:extractDeepLinksDemoDebug SKIPPED
:ui-test-hilt-manifest:processDemoDebugManifest SKIPPED
:ui-test-hilt-manifest:compileDemoDebugLibraryResources SKIPPED
:ui-test-hilt-manifest:parseDemoDebugLocalResources SKIPPED
:ui-test-hilt-manifest:generateDemoDebugRFile SKIPPED
:ui-test-hilt-manifest:kaptGenerateStubsDemoDebugKotlin SKIPPED
:ui-test-hilt-manifest:kaptDemoDebugKotlin SKIPPED
:ui-test-hilt-manifest:compileDemoDebugKotlin SKIPPED
:ui-test-hilt-manifest:javaPreCompileDemoDebug SKIPPED
:ui-test-hilt-manifest:compileDemoDebugJavaWithJavac SKIPPED
:ui-test-hilt-manifest:transformDemoDebugClassesWithAsm SKIPPED
:ui-test-hilt-manifest:bundleLibCompileToJarDemoDebug SKIPPED
:ui-test-hilt-manifest:generateDemoDebugAssets SKIPPED
:ui-test-hilt-manifest:packageDemoDebugAssets SKIPPED
:ui-test-hilt-manifest:bundleLibRuntimeToJarDemoDebug SKIPPED
:ui-test-hilt-manifest:processDemoDebugJavaRes SKIPPED
:ui-test-hilt-manifest:mergeDemoDebugJniLibFolders SKIPPED
:ui-test-hilt-manifest:mergeDemoDebugNativeLibs SKIPPED
:ui-test-hilt-manifest:copyDemoDebugJniLibsProjectOnly SKIPPED
:app:assembleDemoDebug SKIPPED
:ui-test-hilt-manifest:clean SKIPPED
:ui-test-hilt-manifest:stripDemoDebugDebugSymbols SKIPPED
:ui-test-hilt-manifest:copyDemoDebugJniLibsProjectAndLocalJars SKIPPED
:ui-test-hilt-manifest:extractDeepLinksForAarDemoDebug SKIPPED
:ui-test-hilt-manifest:extractDemoDebugAnnotations SKIPPED
:ui-test-hilt-manifest:mergeDemoDebugGeneratedProguardFiles SKIPPED
:ui-test-hilt-manifest:mergeDemoDebugConsumerProguardFiles SKIPPED
:ui-test-hilt-manifest:prepareDemoDebugArtProfile SKIPPED
:ui-test-hilt-manifest:prepareLintJarForPublish SKIPPED
:ui-test-hilt-manifest:mergeDemoDebugJavaResource SKIPPED
:ui-test-hilt-manifest:syncDemoDebugLibJars SKIPPED
:ui-test-hilt-manifest:bundleDemoDebugAar SKIPPED
:ui-test-hilt-manifest:assembleDemoDebug SKIPPED
```

And since `:ui-test-hilt-manifest` tasks that run after clean depend on some task outputs that run before `clean`, but are cleaned, there seem to be somekind of deadlock.

**Comment by asodja** [comment]
Since Gradle tries to respect order of tasks on the command line, it's better you run all `clean` tasks first if you really need clean. 
We would need to investigate more, to figure if there is a solution to that. But we could do a better job here and warn user for such cases and fail with a better error message..

**Comment by asodja** [comment]
I believe a simpler version is something like:
```
tasks.register('preGenerateFoo') {
    outputs.file file('build/1')
}

tasks.register('preAssembleFoo') {
    dependsOn 'preGenerateFoo'
}

tasks.register('cleanFoo') {
   destroyables.register file('build')
}

tasks.register('generateFoo') {
    outputs.file file('build/2')
}

tasks.register('assembleFoo') {
    inputs.files preGenerateFoo
    inputs.files generateFoo
}
```
with:
```
./gradlew preAssembleFoo cleanFoo assembleFoo
```

**Comment by asodja** [comment]
To sum up: command line order and task dependencies coflicts. Android Studio will order tasks differently in next Android Studio Hedgehog versions. And Gradle should print more actionable error message in such cases. 

I will keep this open and it should be closed, once we implement better detection and error message for such conflicts.

**Comment by lptr** [comment]
@asodja please follow up here with the current status and next steps about this issue.

**Comment by fluxxion82** [comment]
I'm seeing this error with AS Iguana and Jellyfish - Hedgehog works fine. I've attached a reproducer in https://issuetracker.google.com/issues/315023802. The workaround listed in this issue works for my reproducer but not for my main project.

**Comment by asodja** [comment]
Please open a new issue with a reproducer if you have a problem, so team can triage it. While the message of the error could be the same, the source of a problem could be different.
