### ISSUE TITLE
settings.gradle.kts plugins error

### ISSUE THREAD

**Issue by lianglinux5** [gradle/gradle#26066]
### Current Behavior

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version("0.4.0")
}

### Expected Behavior

plugins {
    id("org.gradle.toolchains.foojay-resolver") version("0.4.0")
}

### Steps to Reproduce

plugins error

### Gradle version

8.2.1

**Comment by jbartok** [comment]
https://github.com/gradle/foojay-toolchains#usage
