### ISSUE TITLE
Disabling spotbugsIntegrationTest Task in Separate Gradle Configuration File

### ISSUE THREAD

**Issue by CedricNdong** [gradle/gradle#26070]
### Current Behavior

I receive the following error:
`Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'spotbugsIntegrationTest' for root project '...' of type org.gradle.api.Project.`

### Expected Behavior

The spotbugsIntegrationTest task should be disabled and not run during the build.

### Context (optional)

When attempting to disable the spotbugsIntegrationTest task in a separate spotbugs.gradle file and then applying this file in the main build.gradle, I encounter a groovy.lang.MissingPropertyException for the task spotbugsIntegrationTest, even though this task exists.

This issue has become a bottleneck in our development and CI/CD process. We use SpotBugs as a static analysis tool to ensure code quality. As part of our build pipeline, different types of tests, including integration tests, are executed. Being able to configure and disable certain SpotBugs tasks, like spotbugsIntegrationTest, based on our project's needs is crucial.

The inability to disable this task in a separate configuration file is affecting our build performance and introducing unnecessary complexity into our Gradle configuration. It is making our build process less modular, as I intended to break out configurations for easier management.

### Steps to Reproduce

1. Add the SpotBugs plugin with version 5.0.14 in the build.gradle file.

2. Create a new spotbugs.gradle file in the project's root directory with the content:
`spotbugsIntegrationTest.enabled = false 
`
![image](https://github.com/gradle/gradle/assets/92950547/2caa95b7-211a-418c-8d1d-9b32999bd9f9)

3. In the build.gradle file, apply the SpotBugs plugin with apply from: "$rootDir/spotbugs.gradle"
4. Execute the Gradle task to see the error:
5. See error

### Gradle version

 7.4.2

### Your Environment (optional)

SpotBugs plugin version: 5.0.14
Java version: openjdk 17.0.6 2023-01-17
Operating System: Windows 11

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
