### ISSUE TITLE
Gradle 8.3-rc-1 reports JDK 20 as unsupported in IntelliJ

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#26077]
### Current Behavior

After upgrading to Gradle 8.3-rc-1 (which promises fully JDK 20 compatibility), it continues to loudly warn in intelliJ that it's not supported.

<img width="1476" alt="image" src="https://github.com/gradle/gradle/assets/1361086/1f143ac5-1882-4a78-8b1e-195e74f35074">

### Expected Behavior

It should be supported

### Steps to Reproduce

Checkout https://github.com/slackhq/kotlin-cli-util, change Gradle to `8.3-rc-1`, open the project in IntelliJ 2023.2 (latest stable), sync gradle, run a build with a failing test (such as throwing an exception in one), observe the error.

### Gradle version

8.3-rc-1 and 8.3-rc-3

**Comment by yogurtearl** [comment]
same result with `8.3-rc-3` and nightlies?

**Comment by ZacSweers** [comment]
Yes same with rc-3, but only if there's a build failure

**Comment by natros** [comment]
https://youtrack.jetbrains.com/issue/IDEA-326038

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

***

@natros Thanks for the link to the issue!
