### ISSUE TITLE
Add a single command to clean build cache

### ISSUE THREAD

**Issue by mwisnicki** [gradle/gradle#26079]
### Expected Behavior

I want single obvious command that cleans build cache.

Document it in https://docs.gradle.org/current/userguide/build_cache.html

### Current Behavior (optional)

Currently it takes too much (when you factor in time for research for person unfamiliar with gradle) to do something that should be one liner.

Btw the instructions on https://docs.gradle.org/current/userguide/build_cache_debugging.html are incomplete, see  
https://stackoverflow.com/a/23029580/443422

### Context

Causes completely unnecessary waste of time

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

@gradle/bt-execution should this command be added and this issue be requalified as a feature?

**Comment by lptr** [comment]
What is your use case to need to clean the build cache?

**Comment by mwisnicki** [comment]
It looked like my program had stale code after move refactoring and my first suspect was gradle cache (I sometimes get some weird errors from gradle when refactoring, especially moving class from one java file to another (package private to public) so to eliminate that I wanted to clean the cache and found out it's not so simple :/

I usually just double-click tasks from Intellij so having standard cacheClean task would be a massive usability improvement and will also save other people looking for it some time.
