### ISSUE TITLE
--scan option overrides Gradle enterprise plugin version from includedBuild

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#26086]
### Current Behavior

[Kotlin repo](https://github.com/jetbrains/kotlin/) adds "com.gradle:gradle-enterprise-gradle-plugin" via includedBuild in build classpath. The version of this plugin (tested on [commit](https://github.com/JetBrains/kotlin/commit/bdd8cce69c9385f85f45fc0544eb19136e49019d)) is "3.12.4".

When a developer runs the build with `--scan` option, Gradle ignores the already added plugin and adds a new one with "3.13.4" version. Which leads to dependency verification error and build configuration failure on ignoring the verification.

### Expected Behavior

Using '--scan' considers added into the build Gradle plugins from build script included builds.

### Steps to Reproduce

- Checkout kotlin.git on the provided commit hash
- Run `./gradlew clean install --scan`

### Gradle version

8.2.1

### Build scan URL (optional)

https://ge.jetbrains.com/s/lz43qa76t2heo/failure

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by sorin-florea** [comment]
This is fixed in Gradle 8.4
