### ISSUE TITLE
Allow for specifying `--project-cache-dir` in `gradle.properties` file

### ISSUE THREAD

**Issue by bartekpacia** [gradle/gradle#26093]
### Expected Behavior

I don't want to have duplicated `.gradle` directories, so I usually run:

```
gradle --project-cache-dir ./android/.gradle :tasks --all
```

but I'd prefer to specify it in some `gradle.properties` file.

### Context

This is a very small feature that would make my work a tiny bit easier.

See also:
- [How to specify project cache dir from a gradle config](https://discuss.gradle.org/t/how-to-specify-project-cache-dir-from-a-gradle-config/45387)

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!
Have you tried using `org.gradle.projectcachedir` in the properties file?
Even if it works, this should be documented, will requalify the issue as a documentation one.

**Comment by bartekpacia** [comment]
Thanks for response @jbartok. Unfortunately that didn't work.

```
$ cat gradle.properties
org.gradle.projectcachedir=./android/.gradle
```

But the `.gradle` directory is still created in my `$PWD` instead of `$PWD/android`.

**Comment by jbartok** [comment]
Hmm... just tried it (with Gradle `8.3-rc-4`) and works as you would expect for me... What Gradle version are you using?

**Comment by bartekpacia** [comment]
`7.5`

**Comment by jbartok** [comment]
You are correct; it indeed doesn't work correctly in Gradle `7.5`. The smallest Gradle version I could find, where it does work correctly is `8.2.1`. Is upgrading to that version an option for you?

**Comment by bartekpacia** [comment]
~~Yeah, it's not a problem.~~ For no apparent reason, I'm getting `OutOfMemory` with `8.2.1`:

```
$ ./gradlew :android:app:assembleDebug
> Task :android:app:packageDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)
```

Thank you for support, I'll debug it and get back once I manage to fix it.

**Comment by bartekpacia** [comment]
Okay, it works. OOM disappeared.

Thank you!

**Comment by bartekpacia** [comment]
I'll leave it up to your whether to keep it open, because docs could surely be better :)

**Comment by lkasso** [comment]
Fixed in https://github.com/gradle/gradle/pull/25724.
