### ISSUE TITLE
Test reports not generating when a test fails after a clean

### ISSUE THREAD

**Issue by jjloneman** [gradle/gradle#2609]
### Expected Behavior

If I execute a `gradle clean runMySpec`, and if a test fails, there should still be a generated test report.

### Current Behavior

If I execute a `gradle clean runMySpec`, and if a test fails, Gradle does not generate a test report. However, if `runMySpec` succeeds, a test report will be generated. After a successful execution, if I then execute a `gradle runMySpec` (not doing a `clean`), and if a test fails, the test report will be updated to describe the failing tests.

### Context

I like to do a `clean` before I run any of my test tasks, because `Selenide`, which is a `Selenium` wrapper, automatically takes screenshots of failing tests and outputs it to the `tests/runMySpec/screenshots` directory. The directory will become littered with screenshots if I don't clean the directory each run. 

I suppose a workaround could be to do a custom clean on that directory alone every time I run the task, but the over-arching issue of the test report not automatically being generated on a clean build still exists.

### Steps to Reproduce (for bugs)

1. Perform a `gradle clean`.
2. Execute a test that will fail using Gradle.
3. Check the `$buildDir/reports/tests/customTestTask` directory to find a generated test report. It will not exist.
4. Execute a test that will succeed using Gradle.
5. Check the same directory, the generated test report will now exist and report that the test passed.
6. Execute a test that will fail using Gradle (do not perform a `clean`).
7. Open the same test report, which will now report the failing test.

### Your Environment

Due to corporate security policy, I cannot upload my build scan, but I can provide these details:

**IDE Details**
- IDE: IntelliJ IDEA 2017.2
- Build #IU-172.3317.76, built on July 15, 2017
- JRE: 1.8.0_152-release-915-b5 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**OS/Language/Gradle Details**
- Gradle version: 4.0
- Groovy version: 2.4.12
- Operating system: Windows 7 6.1
- CPU cores: 4 cores
- Max Gradle workers: 4 workers
- Java runtime: Oracle Java(TM) SE Runtime Environment 1.8.0_101-b13
- Java VM: Oracle Java HotSpot(TM) 64-Bit Server VM 25.101-b13 (mixed mode)
- Max JVM memory heap size: 954 MB
- Locale: English (United States)

**Comment by big-guy** [comment]
I suspect there's something else going on here.  Is `runMySpec` actually a `Test` task? You can check with `gradle help --task runMySpec`.

I did this:
1. Run `gradle init --type=java-library`
1. Run `gradle test`. Report is generated.
1. Change `src/main/java/Library.java` to return false
1. Run `gradle clean test`.  Report is still generated.
1. Run `gradle clean && gradle test`.  Report is still generated.

In case it was a problem with custom tasks, I also added this to `build.gradle`:
```
task myTest(type: Test) {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
}
```

And ran `gradle myTest` and I still had a report generated.

> I like to do a clean before I run any of my test tasks, because Selenide, which is a Selenium wrapper, automatically takes screenshots of failing tests and outputs it to the tests/runMySpec/screenshots directory. The directory will become littered with screenshots if I don't clean the directory each run.

You could do something like this to always delete the screenshots:
```
runMySpec {
   doFirst {
      project.delete(file("path/to/screenshots"))
   }
}
```

This could be fancier to only delete files older than a day, so you keep recent failures (if that's useful).

**Comment by jjloneman** [comment]
Huh, it may only be an issue with my project then. To answer your question: yes, `runMySpec` is a `Test` task, it looks like this:

```
task testDev09Menu(type: Test) {
    def testReportPath = "${testReportDir as String}/$name"
    def screenshotsPath = "$testReportPath/screenshots"

    outputs.upToDateWhen { false }
    systemProperties['selenide.reports'] = screenshotsPath

    doFirst {
        delete(file(screenshotsPath))
    }

    filter {
        includeTestsMatching '*Dev09MenuSpec'
    }

    testLogging {
        events 'PASSED', 'STARTED', 'FAILED', 'SKIPPED'
    }

    afterTest { descriptor, result ->
        if (result as String == 'FAILURE') {
            Desktop.desktop.browse(uri("$testReportPath/index.html"))
        }
    }
}
```

But, I did create a new test project like you, and Gradle did generate the failing test reports even after a clean, so maybe it's a fluke just for my project. Invalidating IntelliJ's caches and restarting, doing a Gradle clean/build and refresh, just doesn't seem to fix it.

I'll try to do a little more investigating and checking the log files to see if anything weird is going on.

Also, thanks for the deletion advice!

**Comment by big-guy** [comment]
What does the failure message look like? The only thing I can imagine is that the test fails in a way that's outside the normal type of failure and Gradle is out of the loop on it.

**Comment by jjloneman** [comment]
This is the error message:
```
C:\Workspace\IntelliJ\menu-test (feature/implement-selenium) 
λ gradlew testDev09Menu

> Task :testDev09Menu

com.mycompany.specs.menu.Dev09MenuSpec > Test first menu option click successfully loads general inquiry page on IE STARTED

com.mycompany.specs.menu.Dev09MenuSpec > Test first menu option click successfully loads general inquiry page on IE FAILED
    org.spockframework.runtime.ConditionFailedWithExceptionError at Dev09MenuSpec.groovy:37
        Caused by: com.codeborne.selenide.ex.ElementShould at Dev09MenuSpec.groovy:37

com.mycompany.specs.menu.Dev09MenuSpec > Test mouse hover on first menu option successfully highlights cell on IE STARTED

com.mycompany.specs.menu.Dev09MenuSpec > Test mouse hover on first menu option successfully highlights cell on IE PASSED

2 tests completed, 1 failed


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Workspace\IntelliJ\menu-test\build.gradle' line: 69

* What went wrong:
Execution failed for task ':testDev09Menu'.
> Failed to notify test listener.
   > Failed to open file:/C:/Workspace/IntelliJ/bos-web-menu-test/build/reports/tests/testDev09Menu/index.html. Error message: The system cannot find the file specified.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 22s
2 actionable tasks: 1 executed, 1 up-to-date
```

This is what is generated in the build directory - it produces the screenshots but no test information.
![image](https://user-images.githubusercontent.com/16791848/28727076-554fec56-7389-11e7-8232-8ca42989bc6a.png)

**Comment by big-guy** [comment]
OK, that makes sense.

This is breaking it:
```
    afterTest { descriptor, result ->
        if (result as String == 'FAILURE') {
            Desktop.desktop.browse(uri("$testReportPath/index.html"))
        }
    }
```

Gradle doesn't generate `"$testReportPath/index.html"` until after all tests have been executed, so on the first test failure, `Desktop.desktop.browse` tries to open a path that doesn't exist and causes Gradle to bail immediately.

When the build has been successful once, that path will exist, so opening it works (even though it's showing the previous test results).  I think it might try to open the same path multiple times if there are multiple test failures and this would never work on a headless CI server.

A few suggestions:
- If you don't mind clicking a link, you can just remove this code and when the build fails, there's a `file:///` url that is clickable in most consoles and IDEs.
- If you still want the report to open automatically as soon as it's available, I'd suggest using a [finalizer task](https://docs.gradle.org/current/userguide/more_about_tasks.html#taskFinalizers) that checks if `test` failed and then opens the report.  
- If you just want the report to open automatically at the end of the build if there are failures, I'd suggest using a `gradle.buildFinished {}` hook to look at all of the `Test` tasks and open any reports that have failures.
- I'd personally find the automatic-report-opening to be annoying and don't mind clicking the link, but I understand some people would like some automation. I would add a task like `openTestReport` and then someone can opt-in to when the report should open. The task would be the same as a finalizer, but you wouldn't use `test.finalizedBy openTestReport` and it wouldn't run unless someone put `openTestReport` on the command-line. Instead, you'd need `openTestReport.dependsOn test`.

**Comment by FabianoLothor** [comment]
I solve it changing

`classpath "org.springframework.boot:spring-boot-gradle-plugin:2.1.8.RELEASE"`

to

`classpath "org.springframework.boot:spring-boot-gradle-plugin:2.2.0.RELEASE"`
