### ISSUE TITLE
Migrating multi-module Gradle project leading to "Type mismatch: inferred type is Project? but Any was expected" when including local module as dependency

### ISSUE THREAD

**Issue by mklueh** [gradle/gradle#26092]
### Current Behavior

I'm trying to migrate from Groovy to Kotlin DSL in the hope to get past other blocking issues I'm facing with IntelliJ + Gradle + WSL, such as 

https://youtrack.jetbrains.com/issue/IDEA-319295/includeBuild-fails-on-WSL-with-Included-build-wsl-Ubuntu-20.04wslUbuntu-20.04...my-plugin-has-build-path-my-plugin-which-is-the

https://youtrack.jetbrains.com/issue/IDEA-326882/After-cancel-of-stuck-Importing-Gradle-Project-status-hangs-at-Stopping-Importing-Gradle-Project-and-Gradle-refresh-not-working

https://youtrack.jetbrains.com/issue/IDEA-324602/Tests-dont-run-in-WSL-its-stuck-at-testClasses

However, the migration does not work as flawlessly as I have hoped it would. This dependency implementation of a local Gradle modules

```
dependencies {
    implementation(findProject(":components:base"))
}
```

leads to

```
* What went wrong:
Script compilation error:

  Line 6:     implementation(findProject(":components:base"))
                             ^ Type mismatch: inferred type is Project? but Any was expected

```

### Expected Behavior

To work, as in the official migration post there is not a single word that something might be wrong with the implementation call

https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html

or to show the real cause if something else is the reason.

### Steps to Reproduce

root build.gradle.kts
```
apply(plugin = "java")
apply(plugin = "idea")

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project


subprojects {
    apply(plugin = "java")

    //noinspection GroovyAssignabilityCheck
    repositories {
        mavenCentral()
        mavenLocal()
    }

    dependencies {
        val implementation by configurations
        val testImplementation by configurations
        val annotationProcessor by configurations
        val testAnnotationProcessor by configurations

        val quarkusVersion = "3.2.3.Final"

        implementation(enforcedPlatform("io.quarkus.platform:quarkus-bom:$quarkusVersion"))
        implementation(enforcedPlatform("io.quarkus.platform:quarkus-google-cloud-services-bom:$quarkusVersion"))

      ///...general dependencies
    }

}

//not working with kotlin dsl
//tasks.test {
//useJUnitPlatform()
//testLogging {
//            showStandardStreams = true
//        }
//}

configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_19
    targetCompatibility = JavaVersion.VERSION_19
}

tasks.withType<Test> {
    systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
}
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-parameters")
}

```

base build.gradle.kts
```
plugins {
    id("io.quarkus")
    id("java-library")
}
```

library build.gradle.kts
```
plugins {
    id("java-library")
}

dependencies {
    implementation(findProject(":components:base"))
}

```

### Gradle version

8.3-rc3

**Comment by mklueh** [comment]
Edit: I found out that the project is running normally via the terminal, so this seems to be yet another IntelliJ problem occuring when the IDE tries to sync

**Comment by mklueh** [comment]
Concluded too early, running `./gradlew clean` via terminal produces the same error, but running the actual application works

**Comment by mklueh** [comment]
Seems to have to be `implementation(project("..."))` instead of `implementation(findProject("..."))`. Could anyone please explain why?

Seems like it isn't deprecated https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.initialization/-settings/find-project.html

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

You are looking at the wrong docs, you need `findProject` from `Project`, not `Settings`.

You can convert the optional type returned by `findProject(...)` with a `!!`, that will force it into a non-nullable type. 

Or, as you said, you can just use the `project` method, which has a non-nullable return type and handles not finding the project by throwing an exception. 

The two methods basically do the same thing, just handle errors differently.
