### ISSUE TITLE
Dependecy resolve wrong version

### ISSUE THREAD

**Issue by falltodis** [gradle/gradle#2610]
The elasticsearch dependency below in gradle would relove 
`compile "org.elasticsearch.client:transport:5.5.1"` to version `5.4.1`
![image](https://user-images.githubusercontent.com/7006864/28712249-206c005e-73bd-11e7-90f2-957ddd6369e4.png)
otherwise ,the maven would resolve 
![image](https://user-images.githubusercontent.com/7006864/28712274-385b59f8-73bd-11e7-848c-6b636ab61978.png)
the correct version

## Gradle repos
![image](https://user-images.githubusercontent.com/7006864/28712344-6f6689fe-73bd-11e7-89cd-87101a7b7077.png)

## maven repos
![image](https://user-images.githubusercontent.com/7006864/28712363-7f3a7b56-73bd-11e7-8c8f-7d68df479be4.png)

**Comment by bmuschko** [comment]
That's not what I see with Gradle 4.0.2 and the following build script:

```
apply plugin: 'java'

repositories {
    mavenCentral()
    maven {
        url 'https://repo.spring.io/snapshot'
    }
    maven {
        url 'https://repo.spring.io/milestone'
    }
}

dependencies {
    compile "org.elasticsearch.client:transport:5.5.1"
}
```

Output of `gradle dependencies --configuration compile` is the following:

```
compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
\--- org.elasticsearch.client:transport:5.5.1
     +--- org.elasticsearch:elasticsearch:5.5.1 <-
     |    +--- org.apache.lucene:lucene-core:6.6.0
     |    +--- org.apache.lucene:lucene-analyzers-common:6.6.0
     ...
```

Do you maybe force a specific version `org.elasticsearch:elasticsearch` somewhere in your build script? I'd need to see the rest of your code.

**Comment by falltodis** [comment]
This is all 
```
buildscript {
	ext {
		springBootVersion = '2.0.0.M2'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }

    }
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

jar {
	baseName = 'face-recognition'
	version =  '0.1.0'
}

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }

}


dependencies {
	compile "org.elasticsearch.client:transport:5.5.1"
    compile("org.apache.logging.log4j:log4j-core:2.8.2")
    compile('org.springframework.boot:spring-boot-starter')
	compile("org.springframework.boot:spring-boot-starter-web")
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

With command `gradle dependencies ` will get the follow logs
![image](https://user-images.githubusercontent.com/7006864/28719721-89f502ee-73dd-11e7-95d0-726c801369f4.png)

The env : 
![image](https://user-images.githubusercontent.com/7006864/28719761-a44f96a4-73dd-11e7-8ec2-4b51631eb35d.png)

**Comment by bmuschko** [comment]
I am pretty sure that's something the Spring Boot Gradle plugin does internally. The command `gradle dependencyInsight --dependency org.elasticsearch:elasticsearch --configuration compile` gives me the following output:

```
org.elasticsearch:elasticsearch:5.4.1 (selected by rule)

org.elasticsearch:elasticsearch:5.5.1 -> 5.4.1
\--- org.elasticsearch.client:transport:5.5.1
     \--- compile
```

In fact I should found a lengthy discussion about it [here](https://discuss.gradle.org/t/excluded-dependence-comes-back-when-spring-boot-plugin-is-applied/17945/2) plus a proposed solution. I am going to close this issue.

**Comment by mainaksethi** [comment]
Still not solved for me after overriding rule as well? Any proposed solution?
