### ISSUE TITLE
Gradle properties vs project properties vs system properties

### ISSUE THREAD

**Issue by joffrey-bion** [gradle/gradle#26107]
### Issue type

Wrong or misleading information

### Problem description

(sorry for the category, it's in-between the "wrong or misleading" and the "missing information")

I find the doc a bit confusing about the different types of properties that Gradle supports, what each configure, and their order of precedence.

#### Types/sets of props VS mechanisms to set them

On the surface, when looking at the [Build Environment doc](https://docs.gradle.org/current/userguide/build_environment.html), there are 3 sections about properties: Gradle properties, System properties, Project properties. The sections about Gradle properties and System properties also provide a list of properties, suggesting that those sections define *sets* (or subsets) of properties. However, all 3 sections also mention different *mechanisms* to set those properties: JVM system properties with `-D` on the command line, env vars like `JAVA_OPTS` and `GRADLE_OPTS` which can also make use of `-D` to define JVM system properties, `gradle.properties` files in various places, `-P` for project properties, etc.). There is no 1-to-1 mapping between the sets of properties and the mechanisms, which makes it rather unclear which properties are of which type and what this means.

All of them can be set via JVM system properties (`-D` on the CLI or in env vars), even the ones that are not defined in the [System properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties) section: `-Dorg.gradle.caching=true` is valid (a Gradle property), and so is `-Dorg.gradle.project.someProp=value` (a Project property).

All of them can be set in `gradle.properties` files, even the ones that are not defined in the [Gradle properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) section. However, some require the `systemProp.` prefix, and some don't (although as we established all of them could be set via system props too). An interesting consideration: what happens if I put a `systemProp.org.gradle.caching=true` in my root project's `gradle.properties`? Does it have the same effect as `org.gradle.caching=true`? Does it affect the precedence?

So, if those sections don't segregate properties based on the mechanism to set them, what is the separation about? What exactly is the difference between the JVM system properties that are Gradle properties and the JVM system properties that require `systemProp.` prefix in properties files? Do they affect/control different parts of Gradle? This leads me to the next point.

#### What each property type configures

***Gradle properties*** are said to *"configure the Java process that will be used to execute your build"*, which is unclear about whether this is about the client/daemon/build VM. But the intro paragraph carries on saying that *"it’s possible to configure these in your local environment via GRADLE_OPTS or JAVA_OPTS"* - and those are said to affect the client VM (not the build VM) in the docs about [Environment variables](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables). What I think this means is that the JVM system property mechanism used in `GRADLE_OPTS` and `JAVA_OPTS` (when using `-D` there) are indeed configuring JVM system properties of Gradle's *client* VM, but then that client can use the subset of these system props that we consider to be *Gradle properties* (the ones starting with `org.gradle.*`) to configure the daemon or build VM when it starts it. That's still unclear to me and just based on assumptions, so it'd be nice to clarify that.

The [System properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties) section reads: *"you can pass a system property to the JVM which runs Gradle"*. Again, not sure which of the client/daemon/build VM this is talking about. If we're specifically talking about the subset that requires the `systemProp.` prefix in properties files, do they configure the same thing as Gradle properties or something different? Are they used earlier in the process / are they more "meta"? What makes them different?

#### Precedence

In the very first intro paragraph of the [Build Environment doc](https://docs.gradle.org/current/userguide/build_environment.html) page, an order of precedence is mentioned. But this order mixes properties from different sets (for instance System and Gradle properties). If we consider these sets of properties independent, it is irrelevant to consider the precedence between them. The precedence should be between multiple *mechanisms* affecting the *same* property.

I believe it would be better to define an order of precedence for each type of property, listing all their mechanisms, just like it was done for Gradle properties:

* command line, as set using `-D`
* `org.gradle.foo=value` in `gradle.properties` in [GRADLE_USER_HOME](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home) directory.
* `org.gradle.foo=value` in `gradle.properties` in the project’s directory, then its parent project’s directory up to the build’s root directory.
* `org.gradle.foo=value` in `gradle.properties` in Gradle installation directory

(By the way, where are environment variables `GRADLE_OPTS` and `JAVA_OPTS` here? Are they at the end, like the intro paragraph mentioned?)

Applying the same idea for Project properties, we could define this one:

* command line argument `-Pfoo` / `-Dorg.gradle.project.foo` (by the way, which is first?)
* `foo=value` in `gradle.properties` in the [GRADLE_USER_HOME](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home) directory
* `foo=value` in `gradle.properties` in the project’s directory, then its parent project’s directory up to the build’s root directory
* `foo=value` in `gradle.properties` in Gradle installation directory
* `GRADLE_OPTS`/`JAVA_OPTS` with `-Dorg.gradle.project.foo` inside (does this work? is this the right precedence?)
* `ORG_GRADLE_PROJECT_foo` env var (is this the right precedence?)

Applying the same idea for System properties, we could define this one:

* command line argument `-Dfoo=value`
* `systemProp.foo=value` in `gradle.properties` in [GRADLE_USER_HOME](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home) directory
* `systemProp.foo=value` in `gradle.properties` in the project’s root directory
* `systemProp.foo=value` in `gradle.properties` in Gradle installation directory
* `GRADLE_OPTS`/`JAVA_OPTS` with `-Dfoo` inside (does this work? is this the right precedence?)

Sorry for the very long read. I hope this is useful nonetheless! 🙏 

### Page with the problem

https://docs.gradle.org/current/userguide/build_environment.html

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by tnielens-centrica** [comment]
Related to this issue, the relation between gradle properties and [project properties](https://docs.gradle.org/current/userguide/project_properties.html) and [unqualified groovy properties](https://docs.gradle.org/current/userguide/groovy_build_script_primer.html#groovy:properties) isn't clear from the documentation. Gradle properties are neither mentioned in the project properties page, nor in the groovy dsl primer page. From the doc, project and gradle properties seem distinct property scopes. A groovy build file property evaluation shouldn't lookup gradle properties but only project properties and associated scopes (ext, extensions, conventions, etc).

**Comment by gabrielfeo** [comment]
Adding to the confusion, while [the docs explicitly say that "Gradle properties" can be set using `-D`](https://github.com/gradle/gradle/blob/5479bbb152f69f27746c4528778b5c01e6eb794a/platforms/documentation/docs/src/docs/userguide/authoring-builds/other/build_environment.adoc?plain=1#L175), custom Gradle properties read with `providers.gradleProperty("foo")` cannot be set with `-Dfoo=bar`, only `-Pfoo=bar`.
