### ISSUE TITLE
Gradle docs specify unnecessary “junit-platform-launcher” for JUnit 5 tests

### ISSUE THREAD

**Issue by tkgregory** [gradle/gradle#26114]
### Issue type

Wrong or misleading information

### Problem description

The [Testing in Java & JVM projects documentation](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_testing_basics) suggests the following dependencies for setting up basic testing.

```
dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
```
However, my testing shows that only _junit-jupiter_ is required in order to run unit tests and **not** _junit-platform-launcher_:

* via the Gradle test task
* in IntelliJ IDEA

Here’s my example _build.gradle.kts_.

```
plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
```

My expectation is that the docs should not suggest unnecessary dependencies that clutter the Java classpath.

Is this documentation out of date or is there a use case I'm unaware of?

### Context (optional)

Question already asked on [Gradle Forums](https://discuss.gradle.org/t/why-do-gradle-docs-specify-junit-platform-launcher-for-junit-5-tests/46286/2).

### Page with the problem

https://docs.gradle.org/current/userguide/java_testing.html#sec:java_testing_basics

**Comment by cobexer** [comment]
Thanks for bringing this up!

The documentation is not out of date, but your testing relies on deprecated behaviour that is scheduled to be removed in Gradle 9.

Please have a look at the Upgrade Guide  https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#test_framework_implementation_dependencies for a more detailed explanation.

**Comment by tkgregory** [comment]
The documentation you've linked to states:

> If using JUnit 5, an explicit runtimeOnly dependency on junit-platform-launcher is required in addition to the existing implementation dependency on the test engine.

My point is that JUnit 5 tests work with Gradle fine _without_ junit-platform-launcher (see example _build.gradle.kts_ in previous comment).

Either I am missing something, or the documentation is unnecessarily recommending adding _junit-platform-launcher_ to the classpath.

**Comment by cobexer** [comment]
> My point is that JUnit 5 tests work with Gradle fine without junit-platform-launcher [...]

That is correct (currently) but will change!

The section of the documentation I linked to explains the issue and reads:

> In some cases, Gradle will load JVM test framework dependencies from the Gradle distribution in order to execute tests. This existing behavior can lead to test framework dependency version conflicts on the test classpath. To avoid these conflicts, this behavior is deprecated and will be removed in Gradle 9.0.

**Comment by tkgregory** [comment]
If I run `./gradlew dependencies --configuration testRuntimeClasspath` for the provided build script, I see the following dependency tree.

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
\--- org.junit.jupiter:junit-jupiter:5.10.0
     +--- org.junit:junit-bom:5.10.0
     |    +--- org.junit.jupiter:junit-jupiter:5.10.0 (c)
     |    +--- org.junit.jupiter:junit-jupiter-api:5.10.0 (c)
     |    +--- org.junit.jupiter:junit-jupiter-engine:5.10.0 (c)
     |    +--- org.junit.jupiter:junit-jupiter-params:5.10.0 (c)
     |    +--- org.junit.platform:junit-platform-commons:1.10.0 (c)
     |    \--- org.junit.platform:junit-platform-engine:1.10.0 (c)
     +--- org.junit.jupiter:junit-jupiter-api:5.10.0
     |    +--- org.junit:junit-bom:5.10.0 (*)
     |    +--- org.opentest4j:opentest4j:1.3.0
     |    \--- org.junit.platform:junit-platform-commons:1.10.0
     |         \--- org.junit:junit-bom:5.10.0 (*)
     +--- org.junit.jupiter:junit-jupiter-params:5.10.0
          |    +--- org.opentest4j:opentest4j:1.3.0
          |    \--- org.junit.platform:junit-platform-commons:1.10.0 (*)
          \--- org.junit.jupiter:junit-jupiter-api:5.10.0 (*)
```

It doesn't contain the *junit-platform-launcher* dependency in question.

Is Gradle currently adding additional test dependencies that aren't shown in the _dependencies_ report?

I assume the answer is yes, and this is the behaviour that is changing. Please let me know if I understand correctly now.
