### ISSUE TITLE
POM parser does not ignore spaces within `optional` tag and thus resolves differently than Maven

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#26110]
### Current Behavior

If you have a dependency that has a transitive dependency with `<optional> true </optional>` (mind the spaces around `true`), then Gradle treats this as `false` and includes the transitive dependency while Maven ignores it.

### Expected Behavior

Same resolution as with Maven, spaces around the tag content should be ignored.

### Steps to Reproduce

Put some POM with a dependency with `<optional> true </optional>` into some repository, then depend on it and use the `dependencies` task.

### Gradle version

8.2.1

**Comment by jbartok** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

**Comment by big-guy** [comment]
This would need to change in https://github.com/gradle/gradle/blob/1aa913547db41cb664313afc89cb681e4bb1a3f7/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/PomReader.java#L66

**Comment by Vampire** [comment]
@big-guy would it maybe make sense to even fix it in https://github.com/gradle/gradle/blob/master/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/PomDomParser.java#L38-L41, so that for non CDATA a `trim` is made, as usually XML should be whitespace-agnostic? Or are you aware of some part of POMs that indeed is whitespace-sensitive and could break with that?

**Comment by big-guy** [comment]
> Or are you aware of some part of POMs that indeed is whitespace-sensitive and could break with that?

It looks to me that every case is expecting a single text thing that could be trimmed where you suggest.

I'm not 100% sure though. I can't quite tell if it's reasonable to have multiple child nodes for a given element. In those cases, whitespace might be meaningful.

**Comment by stefanoskapa** [comment]
Not sure yet how significant it is, but it might be relevant if the change is done in **PomDomParser**:

According to the Maven [descriptor reference](https://maven.apache.org/ref/4-LATEST/maven-model/maven.html):
_"By default, every element content is trimmed, but starting with Maven 3.1.0, 
  you can add xml:space="preserve" to elements you want to preserve whitespace."_
  
So child nodes of  `<configuration>`  tags might come with that attribute.  It can be observed how Maven maintains the whitespace in that case with `mvn help:effective-pom `.
