### ISSUE TITLE
Be able to override the URL for Maven Central from the command line.

### ISSUE THREAD

**Issue by trandersen-ufst** [gradle/gradle#26128]
### Expected Behavior

In situations where network connectivity varies or is non-existent (expensive data or CI/CD environments needing to go through an internal repository) it makes the build files simpler if we can override the URL for `mavenCentral()` from the command line.  This allows developers to use `mavenCentral()` and then adjust externally if appropriate.

### Current Behavior (optional)

https://github.com/gradle/gradle/blob/ebd2d1858ab8d0663c8d41235ad3a52d1e2dcba1/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultBaseRepositoryFactory.java#L166 always sets the URL to the constant string.

If I understand the code correctly, there is no other special treatment, so allowing this value to be specified from the command line will most likely be enough.

### Context

It makes it cumbersome to write build scripts that works everywhere and require deeper knowledge of gradle intricates to e.g. manipulate repositories on the way.

A simple, documented way of doing this would be really nice as this seems to be a common problem.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented

**Comment by ciscoo** [comment]
Why would that need to be configurable? Calling `mavenCentral()` is more or less a shortcut for:

```kotlin
repositories {
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}
```

If you need something custom then you can define your own repository. For example, using a property:

```kotlin
repositories {
    maven {
        url = uri(property("exampleProp") as String)
    }
}
```

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

Indeed, the solution proposed by @ciscoo is straightforward and clean enough.

**Comment by karaatanassov** [comment]
There is a bit of a problem with the proposed solution. It requred source code edit.

For couple of scenarios editing the build source code may be undesirable:

1. Automating the build of 3rd party source. One does not want to edit build scripts they do not own.
2. Automating the build and test of sources meant for public use. When building and testing SDKs and interface libraries those should be easy to build by external parties. At the same time they should be built and tested on an internal build system. Ideally the published code would not differ from the tested code. Especially that we see a number of supply chain attacks coming from edits to build and test scripts not the core product code.

Note that corporate build systems are becoming ever more isolated from the internet to prevent supply chain attacks. For example it is not uncommon for build server to only have access to internally hosted maven repository with vetted content. 

If gradle permits overriding the mavenCentral() location with system property (much like [mavenLocal()](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.artifacts.dsl/-repository-handler/maven-local.html#:~:text=Adds%20a%20repository%20which%20looks,gradle.)) then the build scripts triggering Gradle can configure the use of internal secure maven repository without editing the source code.

If one happens to read this please reconsider the above verdict.
