### ISSUE TITLE
Java Gradle Plugin Plugin adds publishing rules pluginMaven and pluginIvy that are not modifiable

### ISSUE THREAD

**Issue by flstaats** [gradle/gradle#2612]
Java Gradle Plugin Plugin adds publishing rules for the publications "pluginMaven" and "pluginIvy" that are not modifiable.  These rules are in the https://github.com/gradle/gradle source files MavenPluginPublishingRules.java and IvyPluginPublishingRules.java.

### Expected Behavior
When using the Java Gradle Plugin Plugin we would like to be able to add artifacts with alternate classifiers using the publishing { publications { } } configuration block, such as a sources Jar, to the plugin that is being published.

### Current Behavior
The Java Gradle Plugin Plugin in the RuleSource you use in both MavenPluginPublishingRules.java and IvyPluginPublishingRules.java you used “create()” to crate the plugin publication:
 
```MavenPublication publication = publications.create("pluginMaven", MavenPublication.class);```
 
Rather than “maybeCreate()”:
 
```MavenPublication publication = publications. maybeCreate("pluginMaven", MavenPublication.class);```

### Context
This makes it harder to add additional classifier artifacts (e.g. a sources jar of the plugin for debugging) in the main build script using the normal publishing { publications { } } configuration block, since the Rule to create the pluginMaven or pluginIvy isn’t run until after the project configuration block is run.  If I separately create the same configuration then the Rule fails saying the publication already exists.  I’m using Kotlin-DSL that hasn’t yet implemented the model DSL “model {}” and using a custom RuleSource to add the publication in the @Finalize phase seems like it would be very hard to explain to my end users.I think that's a reasonable request. In the mid term we'll remove the rule engine from the publishing plugins, that'll make this easier again.

In a private email with Stefan Oehme he made the comment "I think that's a reasonable request. In the mid term we'll remove the rule engine from the publishing plugins, that'll make this easier again."  He also requested that I post this as an official issue.

### Your Environment
This behavior has been validated on Gradle 4.0.2 and 4.1-rc-1.

A pull request for the change would only be two lines however I'm currently in a situation where I can't sign a CLA without legal review which will take significant time to process.

**Comment by eskatos** [comment]
Thanks for the report @flstaats 

Fixed in a65ae89

Closing
