### ISSUE TITLE
Archive tasks (Zip/Jar/War/Ear) preserveFileTimestamps = false setting uses local time 

### ISSUE THREAD

**Issue by dustinjohnson13** [gradle/gradle#2614]
### Expected Behavior

When using preserveFileStamps = false, it would seem the file timestamp should be set to the same time in the same time zone regardless of geographic location.  In the current implementation, file timestamps are set to February 1, 1980 of the building machine's time zone.  

My suggestion is to set the file timestamps to February 1, 1980 in the UTC time zone (or really, any consistent time zone).  This way, regardless of geographic location, a reproducible build will truly be reproducible.   
### Current Behavior

This affects my team because our CI build server is in a different time zone than our development machines, so when the same build is compiled for the same git commit on CI machines or developer machines the hashes (MD5/SHA/etc.) are different due to the time zone used for file time stamping. 

### Context

We are trying to create reproducible build archives, and this is currently the only hiccup.  Our archives are fully reproducible for the same commit in the same geographic location, but the time zone file time stamping causes different hashes in different geographic locations.

### Steps to Reproduce (for bugs)

The steps to reproduce are to compile any simple gradle example project consisting of one or two files into a jar, using _reproducibleFileOrder = true_ and _preserveFileTimestamps = false_ in the configuration of the jar task.  Generate an md5/sha1 hash for the archive with a command-line utility.  Do a clean build and generate the same hash on the same machine (it should be the same).  Then build the same project on a machine in a different time zone.  The hash won't match the original.  

### Your Environment

I am in the Central time zone, and our CI server is in the Pacific.

 * Build scan URL:

**Comment by big-guy** [comment]
@wolfs does this look familiar?

**Comment by wolfs** [comment]
@dustinjohnson13 Actually, this should work as expected, see this comment: https://github.com/gradle/gradle/issues/2614#issuecomment-320082699

What Java version are you using? We tested this with Java 7 and 8 on Windows Linux and Mac and all the operating systems yielded the same zip files. Are you sure the timestamp in the zip is different?
We recently found out that the access modifiers for the zip matter, too. We currently don't do anything about that - i.e. we are not setting specific access modifiers for the zip. It seems like Linux Mint [changed its default umask](https://forums.linuxmint.com/viewtopic.php?f=42&t=192794?f=42&t=192794). May this be something you are seeing?

**Comment by dustinjohnson13** [comment]
@wolfs I'm using JDK 1.8.0_25 on both a Red Hat Linux server and a Sierra version of MacOS.  I do believe the problem is something else than I thought, however, as I grabbed both the compiled jar from the CI server and my Mac, and it turns out that there's a 1 byte difference between some (not all) of the compiled classes.  Here is a screenshot when I ran the sha sum on both classes and their file sizes.  I'm not sure what's causing the compilation differences, but maybe it's on Java's side and not Gradle?

![screen shot 2017-08-04 at 8 48 41 am](https://user-images.githubusercontent.com/5210461/28971555-fd92af76-78f1-11e7-992c-ce4be14fa5e4.png)

**Comment by dustinjohnson13** [comment]
Just to add a bit more information, it definitely seems like it's coming from Java for some reason.  I compared the verbose bytecode for both version, and there are definitely some differences:
 ```

**Comment by lptr** [comment]
This looks very similar to the difference we've seen between Oracle 7u40 and 7u79 (IIRC). Are you sure both versions are compiled with 8u25? Might it be for example that you fork the compilation with some other JVM?

**Comment by dustinjohnson13** [comment]
I'm fairly certain they're both 8u25 because I have 8u111 as well on my Mac (which is my default), and I specifically overrode it with `-Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home`, which resulted in different class file hashes.  There were a lot more differences when compiling with 8u111, so it was easy to tell that I was using the correct JDK.

As for the server, it seems like a legit 1.8.0_25 too:
```
jenkins@Jenkins~: which javac
/usr/bin/javac
jenkins@Jenkins~: javac -version
javac 1.8.0_25
jenkins@Jenkins~: echo $JAVA_HOME
/usr/java/latest
jenkins@Jenkins~: $JAVA_HOME/bin/javac -version
javac 1.8.0_25
```

**Comment by big-guy** [comment]
Could you share the source of one of the classes that has the problem?

**Comment by dustinjohnson13** [comment]
@big-guy Sure, I'll try to come up with a small reproducible example.  I'll ping you again as soon as I have something.

**Comment by dustinjohnson13** [comment]
@big-guy The problem appears to be how lambdas are named/linked in the bytecode.  A simple project with a README.md of instructions for duplication is located [here](https://github.com/dustinjohnson13/gradle-reproducible-build-issue).  Again, at this point I believe it's a JDK bug/difference and not really a Gradle issue.  I'd be curious to know whether or not you're able to duplicate it and what you think!

**Comment by big-guy** [comment]
Thanks, it may be this bug https://bugs.openjdk.java.net/browse/JDK-8067422, which is fixed in newer versions of JDK8

**Comment by dustinjohnson13** [comment]
Probably related, but I was using Oracle-proper JDKs.  The issue should still be closed though!
