### ISSUE TITLE
8.1 configuration is stuck at 100% for a while when signing is enabled

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#26154]
### Current Behavior

Follow up from [this slack thread](https://www.linen.dev/s/gradle-community/t/14160073/any-insights-what-could-explain-the-build-staying-stuck-just#dd0c57a4-d53b-4811-b821-0d4c63234182)

The configuration bar stays at 100% for minutes when trying to publish [our project](https://github.com/apollographql/apollo-kotlin):

```
<=============> 100% CONFIGURING [1m 35s]
> IDLE
```

When publishing all our modules, it goes up to 15min and more. You can see an example for 1 module in [this build scan](https://scans.gradle.com/s/7br4uchy5dvlw/timeline)

Upon investigation, this seems to be a regression in Gradle 8.1. A lot of time is spent in `computeCachedSignatures`, maybe [this commit about Signing + CC](https://github.com/gradle/gradle/pull/23262/files#diff-7300cc50bfad93a6bc8e7e7502550734c23b9798f476a2f1ecb3ae16c2dd75c3)?

Trying to publish a single module with 8.0 brings back the "stuck" time from ~1min (without CC) to ~10s (without CC) (which is already a lot but maybe there's not other way?)

We're using 2048 bit RSA keys for signing.

### Expected Behavior

Get the performance back to 8.0

Additionally, it'd be nice if:
* there was something output in the build instead of just `Configuring 100%`
* the "stuck" time was down to ~0? What is the reason to compute the signatures during configuration? Or looks like it's loading the private key several times? 

### Context (optional)

async-profiler output with SVG flame graph:

[profile-out-9.zip](https://github.com/gradle/gradle/files/12398096/profile-out-9.zip)

![Screenshot 2023-08-21 at 17 36 54](https://github.com/gradle/gradle/assets/3974977/66f342bf-5d98-46dc-8925-f058df217d47)

### Steps to Reproduce

Publish a large project with signing enabled. 

You can try with [apollo-kotlin](https://github.com/apollographql/apollo-kotlin):

```
export GPG_PRIVATE_KEY='-----BEGIN PGP PRIVATE KEY BLOCK-----
...
-----END PGP PRIVATE KEY BLOCK-----
'
GPG_PRIVATE_KEY_PASSWORD=foobar
./gradlew publishToMavenLocal
```

### Gradle version

8.3

### Gradle version that used to work

8.0

### Build scan URL (optional)

https://scans.gradle.com/s/7br4uchy5dvlw

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team.

**Comment by mlopatkin** [comment]
Follow up fixes for property-based signing configuration are tracked in #26256.

**Comment by LouisCAD** [comment]
On a 50-60 modules project, it would lead to a 20 minutes configuration time on an M1 Pro machine.

Thank you for linking this issue in the release notes, it helped me understand why upgrading Gradle again fixed this insane delay.
