### ISSUE TITLE
gradle application plugin: provide an option for forking of a process for the task run

### ISSUE THREAD

**Issue by shibumi** [gradle/gradle#2615]
### Expected Behavior
I have a multi-project like the following:
```
Root project 'rmi-tutorial'
+--- Project ':client'
+--- Project ':lib'
\--- Project ':server'
```

I have a dependency as the following for the build process:
`lib -> client`
`lib -> server`

I have a dependency as the following for the run process for local tests:
`server -> client`

When I invoke: `gradlew.bat run` It should build everything (that works) and should run first the server process and after it the client process. 

### Current Behavior
What is happening instead is that gradle waits for termination of the server process instead of forking the process to the background and running the client process.

### Context
I want to start my whole project for local tests without invoking `server:run` and `client:run` in two different terminals. Would be nice to have a `fork`-option in the run task of the application plugin.

**Comment by bmuschko** [comment]
Thanks for providing the issue. It's unlikely that we'll prioritize the issue anytime soon (that means at least within the next year or so). From my perspective it's not a deal breaker for most people plus there's viable workflow to get to the expected behavior. I would also expect the issue to require more work that it might look at first place.

Would you be interested in looking into providing a pull request?

**Comment by adammurdoch** [comment]
We should avoid jamming more stuff into the application plugin. The application plugin should simply build a command-line application. It's not a 'any and every possible kind of application' plugin. Instead we should add plugins to allow you to build and work with other kinds of applications. For example, we might add a 'daemon application' or 'service application' plugin to solve this use case.

**Comment by shibumi** [comment]
@bmuschko 
```
From my perspective it's not a deal breaker for most people plus there's viable workflow to get to the expected behavior
```

Do you have a link of a tutorial or something how I can achieve this behaviour? Because everything what I found was an unofficial plugin that doesn't work.

**Comment by bmuschko** [comment]
@shibumi As "workaround" I meant starting the two processes in different terminals.

**Comment by shibumi** [comment]
closing this, because I stopped using gradle and lost interest in it.
