### ISSUE TITLE
Build cache operation logging in 4.1 is misleading

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#2616]
Our implementation of progress logging for build cache activity causes confusion in that it creates the perception that the hit rate is far greater than it was. Misses in the remote cache are represented by an operation with description: `Loading from build cache`.

While this is technically accurate in that we internally use the term “load” to refer to a cache read that could end up being a hit or miss, users _are_ going to interpret this as effectively a hit. I in fact did this and was confused about what I was seeing. 

We should fix this before release. It _will_ confuse people.

**Comment by lptr** [comment]
What's your suggestion for the required changes?

**Comment by lptr** [comment]
Ah, there's a PR! Sorry.

**Comment by ldaley** [comment]
@lptr I'll leave this at your discretion as to whether it goes in to 4.1 or not. I've said my piece on it.

I think my PR improves the particular problem with people thinking they have hits when they don't, but it does introduce _more_ terms in this space (requesting, downloading and uploading). These were the only things that felt natural when I tried to communicate it how it would make sense to a user.

**Comment by lptr** [comment]
I merged it to `release`.
