### ISSUE TITLE
Shellcheck shows warnings for the wrapper shell script

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#26160]
### Current Behavior

The `gradlew` wrapper scripts for Gradle 8.3 (and the current 8.4 snapshot version of Gradle) contain warnings detected by Shellcheck integration with IntelliJ IDEA (via bundled Shell Script plugin).

![image](https://github.com/gradle/gradle/assets/2759152/a449d14a-7d46-4dd4-924e-741958e52245)

### Expected Behavior

No shell script warnings are reported

### Context (optional)

This is annoying also because IDEA detects those warnings as a part of the commit checks and points the user to them. The users are not supposed to edit the wrapper scripts, so there is no good way of fixing that rather than disabling the Shellcheck, which is most likely not desired.

One check is already ignored for those lines, and I guess we need to add another ignore for the https://github.com/koalaman/shellcheck/wiki/SC2039

### Steps to Reproduce

Generate a any project with `gradle init` and run Shellcheck on the `gradlew`

### Gradle version

8.4 master

**Comment by jbartok** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by alllex** [comment]
We have this test that actually runs Shellcheck and should have supposedly failed. I wonder where the disconnect is with what I observe in IntelliJ.

https://github.com/gradle/gradle/blob/f6d8c168a181e1003e991c075bc7ed99b9f67599/subprojects/plugins/src/integTest/groovy/org/gradle/api/plugins/ApplicationPluginUnixShellsIntegrationTest.groovy#L196

**Comment by alllex** [comment]
> And actually shellcheck doesn't fail on the script on my machine:

Yes, I also checked it locally, and to my surprise the test passes. At the same time, the original issue stands and users will see Shellcheck warnings in their projects after upgrading to Gradle 8.3+ wrapper. I believe it's a bad UX.

We could potentially just add the SC2039 to the disabled list, and do a manual validation in the IDE, since the test does not seem to be able to catch it.
