### ISSUE TITLE
Support providers to define capabilities of consumable configurations

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#26163]
### Expected Behavior

`Configuration.getOutgoing().capability(Object notation)` accepts providers and evaluates them late. Similar to how late attribute evaluation is supported (#18936).

For example, use cases like this are supported:

```
// early (e.g. in plugin)
configurations.create("somethingConsumable") {
  canBeResolved = false
  canBeConsumed = true
  ... // define attributes etc.
  outgoing.capability(provider { project.getGroup() + ":" + project.getName() + "-something:" + project.version })
}


// later (e.g. in build.gradle)
group = "org.example"
version = "1.1"
```

Concretely, I need this in a plugin:
https://github.com/gradlex-org/java-module-dependencies/blob/1f2dabe245a98e332d11e48436447828b0cf2da6/src/main/java/org/gradlex/javamodule/dependencies/JavaModuleVersionsPlugin.java#L64

### Context

In previous Gradle versions, `ConfigurationInternal.beforeLocking { }` could be used as a place to configure Configuration details such as capabilities late (#19131). This method has been removed in Gradle 8.3 (#25126).

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritised by them.
