### ISSUE TITLE
IntelliJ + WSL + local Gradle plugins fails with "Included build /wsl$/Ubuntu-20.04\\wsl$\Ubuntu-20.04\home\user\my-project\gradle-plugins has build path :gradle-plugins which is the same as included build /home/user/my-project/gradle-plugins"

### ISSUE THREAD

**Issue by mklueh** [gradle/gradle#26183]
### Current Behavior

I've been facing a bug that is probably either Gradle or IntelliJ-related for months now where the project is **only runnable via terminal, not via run configuration**, when on **WSL**. It is related to some **custom Gradle plugins** located within the project and included with **includeBuild** 

I've opened an issue on their YouTrack https://youtrack.jetbrains.com/issue/IDEA-319295/includeBuild-fails-on-WSL-with-Included-build-wsl-Ubuntu-20.04wslUbuntu-20.04...my-plugin-has-build-path-my-plugin-which-is-the with a reproducer but it's still not addressed.

So I decided to open it here as well, in case you guys could do something about the issue on your side. For some reason paths seem to be resolved incorrectly

Start fails with
```
* What went wrong:
Included build /wsl$/Ubuntu-20.04\\wsl$\Ubuntu-20.04\home\user\my-project\gradle-plugins has build 
path :gradle-plugins which is the same as included build /home/user/my-project/gradle-plugins`
```

I would appreciate any help in case you could do something

### Expected Behavior

To run normally and resolve paths correctly

### Steps to Reproduce

Open with IDEA, start via IDEA
[gradle-included-build-wsl-reproducer.zip](https://github.com/gradle/gradle/files/12436095/gradle-included-build-wsl-reproducer.zip)

### Gradle version

8.3

### Your Environment (optional)

Windows 11 + WSL2

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/newIssue?project=IDEA.

***

Given that this works on the CLI, it's most likely an integration problem.
