### ISSUE TITLE
When JUnit5 test is skipped because assumption fails build is marked as successful

### ISSUE THREAD

**Issue by akonarska** [gradle/gradle#26198]
### Current Behavior

Whenever assumption fails in JUnit5 Gradle will not report any of the tests in the suite to be run and the build will end with Success.

### Expected Behavior

Build should be reported as failed and all the tests that were not run should be reported as skipped.

### Context (optional)

Maven handles that correctly. The behaviour was also described here https://github.com/junit-team/junit5/issues/2178

### Steps to Reproduce

```
import static org.assertj.core.api.Assumptions.assumeThat;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

public class ExampleTest {
    @BeforeAll
    public static void setUp() {
        assumeThat(false).isTrue();
    }

    @Test
    public void test1() {
        assertTrue(false);
    }

    @Test
    public void test2() {
        assertTrue(true);
    }
}
```

Will show that no tests were run and build is successful when in reality the assumption failed and those 2 tests should have been marked as skipped and failed.

### Gradle version

8.3

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

https://junit.org/junit5/docs/5.0.0/api/org/junit/jupiter/api/Assumptions.html

***

The issue you link to is different, there's an exception there instead of an assumption.

**Comment by akonarska** [comment]
@jbartok Aborted test is something different than skipped test and very much different than a test that succeeds. 
When I decide my test should be skipped and I annotate it - I expect my test to not run.
When an assumption fails in my test - I don't expect this and I want my build to fail.
(This is how maven surefire acts like btw, so it's not like I'm the one who made it up)
The similar issue was (or even is?) there for Junit4 https://github.com/gradle/gradle/issues/5511.
The doc you mentioned clearly states that failed assumption throws `TestAbortedException` and that one is disregarded by gradle and I don't think that is a correct behaviour.
I'd also like to ping @marcphilipp since I've seen you commenting on similar issues before and you seem to have a lot of knowledge in the subject.

**Comment by marcphilipp** [comment]
@akonarska Gradle handles this correctly as far as I can tell: if a `@BeforeAll` method throws a `TestAbortedException`, Gradle reports all tests as skipped and the build fails. A failed assumption is similar to annotating the test class with `@Disabled`.

**Comment by akonarska** [comment]
@marcphilipp thanks for your quick reply.
Problem is that what you're saying is not what I see. Gradle will report those tests as skipped in correct amount (I must have got confused) but the build is very much successful. I'd say this should fail. Unless I am missing something.

This is the result when I run the above test using `./gradlew  clean test -i` (I skipped other tasks to keep the message short but I can add whole project + whole output)

```
> Task :test
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  Output property 'binaryResultsDirectory' file /Users/akonarska/work/test/build/test-results/test/binary has been removed.
  Output property 'binaryResultsDirectory' file /Users/akonarska/work/test/build/test-results/test/binary/output.bin has been removed.
  Output property 'binaryResultsDirectory' file /Users/akonarska/work/test/build/test-results/test/binary/output.bin.idx has been removed.
Starting process 'Gradle Test Executor 8'. Working directory: /Users/akonarska/work/test Command: /Users/akonarska/Library/Java/JavaVirtualMachines/openjdk-17.0.1/Contents/Home/bin/java -Dorg.gradle.internal.worker.tmpdir=/Users/akonarska/work/test/build/tmp/test/work -Dorg.gradle.native=false @/Users/akonarska/.gradle/.tmp/gradle-worker-classpath10467514729224457914txt -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 8'
Successfully started process 'Gradle Test Executor 8'

ExampleTest > test1() SKIPPED

ExampleTest > test2() SKIPPED
Finished generating test XML results (0.001 secs) into: /Users/akonarska/work/test/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.002 secs) into: /Users/akonarska/work/test/build/reports/tests/test
:test (Thread[Execution worker Thread 2,5,main]) completed. Took 0.946 secs.

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
```

**Comment by marcphilipp** [comment]
Sorry, I wrote "fails" when I wanted to write "succeeds". 🤦‍♂️

If you want the build to fail, use `Assertions` instead of `Assumptions` in your `@BeforeAll` methods.

**Comment by akonarska** [comment]
Oh, well, can happen to everyone 😄 I would then go with `Assert` instead - thanks for helping me out!
I would say though that there is a slight difference between a test that I decided to mark as `@Disabled` and a test that was `aborted` because some requirements were not met. It doesn't look like there is a good way to distinguish between those two at the moment...

**Comment by marcphilipp** [comment]
JUnit reports them differently (`@Disabled` is reported as _skipped_, while `TestAbortedException` leads to _aborted_) but Gradle does currently not differentiate between them.

**Comment by akonarska** [comment]
That could be a nice feature for gradle to do that actually. @jbartok should I create a separate issue for it?

**Comment by SimarMugattarov** [comment]
Got the same problem. The failed `Assumption` in `before` skip the test but doesn't print fails message. Error (TestAbortedException) is swallowed.
