### ISSUE TITLE
Option to store dependencies inside the project directory

### ISSUE THREAD

**Issue by wakaztahir** [gradle/gradle#26217]
### Expected Behavior

Package Managers like `NPM` & `Yarn` store dependencies inside the project directory, inside `node_modules`

I know this may have its own pros & cons, But if it can be done, Then it should be done, I understand that this is a big & complex task, I just wanted to put it out there, I also know that gradle can be configured to store all dependencies at a different location.

Users should be allowed to have an option that they can adjust in their `settings.gradle.kts`, which will cause that project's dependencies to be stored inside a directory specified by the user.

### Current Behavior (optional)

Gradle stores all dependencies in C:/

### Context

Currently Gradle manages my storage space automatically, It fails at that because all dependencies in one folder of all projects cause a ridiculous amount of storage usage in a single drive. To be able to store projects in different drives and manage the storage space, I need this option.

I would be able to decide which projects are causing my storage to be used this much.

This has its cons, You'd need to download all dependencies since every project has its own storage, There's no central cache, I think since users would be required to opt in so no worries about this one.

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

You can configure a separate Gradle home folder for each of your projects and that can be inside of the project, if you want to: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties
