### ISSUE TITLE
Gradle8.3 upgrade not working with IBM JDK

### ISSUE THREAD

**Issue by IloraSen** [gradle/gradle#26224]
### Current Behavior

I am trying to upgrade to Gradle 8.3, this works fine with oracle JDK 1.8.0_202 but gives me error with IBM JDK 1.8.0_361, I see some classpath inconsistency but not sure where to start looking from

Here are some snippets from logs

public abstract fun fileTree(args: (Mutable)Map<String!, *>!): ConfigurableFileTree! defined in org.gradle.api.Script
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.gradle.api.internal.AbstractTask, unresolved supertypes: java.lang.Object
    class org.gradle.api.internal.TaskInternal, unresolved supertypes: java.lang.Object
    class org.gradle.api.Task, unresolved supertypes: java.lang.Object
    class org.gradle.api.plugins.ExtensionAware, unresolved supertypes: java.lang.Object
    class org.gradle.util.Configurable, unresolved supertypes: java.lang.Object
    class org.gradle.api.internal.DynamicObjectAware, unresolved supertypes: java.lang.Object

* What went wrong:
Unable to compile Gradle Kotlin DSL API Extensions Jar

### Expected Behavior

Gradle gets upgraded to 8.3 version with IBM JDK 1.8.0_361

### Steps to Reproduce

Set JAVA_HOME = C:\IBM\WebSphere\AppServer\java\8.0  (IBM JDK 8.0 version) in environment variable
edit <Project path>/gradle/wrapper/gradle-wrapper.properties
   distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
Make required checksum updates in project if any

Run gradlew build

========================

Above steps completes successfully if JAVA_HOME is set to C:\Program Files\Java\jdk1.8.0_202

### Gradle version

8.3

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Does your previous version of Gradle work with that IBM jdk?
Can you compile random Java code with that JDK? For example a basic Java project?

**Comment by IloraSen** [comment]
Here are the steps to reproduce that I used


Steps to Reproduce
Set JAVA_HOME = C:\IBM\WebSphere\AppServer\java\8.0 (IBM JDK 8.0 version) in environment variable
JVM used : JDk1.0.0_361
edit /gradle/wrapper/gradle-wrapper.properties
distributionUrl=https://services.gradle.org/distributions/[gradle-8](https://issues.gradle.org/browse/GRADLE-8).3-all.zip
Make required checksum updates in project if any

Run gradlew build

========================

Above steps completes successfully if JAVA_HOME is set to C:\Program Files\Java\jdk1.8.0_202

Gradle version
8.3

Please let me know if any other details are required or you need a different format

**Comment by IloraSen** [comment]
Also when I apply a fix mentioned in issue (https://github.com/gradle/gradle/issues/22671) it resolves my problem but I still don't understand why 8.3 upgrade works with other JVM's and not with IBM JVM 1.8.0_361 without the above jvmArgs fix

**Comment by jbartok** [comment]
Please also answer our questions:
* Does your previous version of Gradle work with that IBM jdk?
* Can you compile random Java code with that JDK? For example a basic Java project?

**Comment by IloraSen** [comment]
- Yes my project worked fine with Gradle 8.2.1 IBM JDK 1.8.0_361
- Also java code compiles fine  with this jdk version, like I mentioned complete project currently runs on this specific jdk version.

**Comment by ov7a** [comment]
The underlying issue appears to be a [bug](https://youtrack.jetbrains.com/issue/KT-61836) in Kotlin. Let's wait for an answer from the Kotlin team.

**Comment by eskatos** [comment]
This is an issue with the Kotlin compiler, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please upvote https://youtrack.jetbrains.com/issue/KT-61836
