### ISSUE TITLE
Build Operation ids are not unique for nested builds

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#2622]
Since Gradle 3.3 (https://github.com/gradle/gradle/commit/a2e67851c687f979b60823a56be591e2422ee5f9) events from all builds, including nested ones, are forwarded to the Tooling API. Since then, build operations for all nested builds are created and used. A unique ID was ensured by placing the `BuildOperationExecutor` into the _global scope_ service registry.

With 4.0, we moved it into the build session scope (https://github.com/gradle/gradle/commit/0b1d93759fd5b2bca126e5af8aa26794575ab9c3) as part of merging it with the _build operation processor_, which was already build session scoped before.

We missed that this breaks the uniqueness of the build operation ids in cases where nested builds are used through the tooling API. This can lead to issues in progress logging where events are assigned to the wrong operations. As, for example, the error that was reported here: https://github.com/gradle/gradle/issues/2239#issuecomment-316139016.

The following PR adds test coverage for this issue and fixes it by adding a `BuildOperationIdFactory` as separate service in the global scope.

https://github.com/gradle/gradle/pull/2624

**Comment by oehme** [comment]
Why can't we move the whole thing up to gradle user home scope?

**Comment by jjohannes** [comment]
It currently depends on the `WorkerLeaseService` which is in build session scope.

**Comment by oehme** [comment]
I'm not sure how this breaks uniqueness yet. The build session encloses all nested builds. Can you elaborate?

**Comment by jjohannes** [comment]
Maybe the term _nested build_ is not clear here. [This example](https://github.com/gradle/gradle/blob/08a6eddb934e98b0ec782b680e61bb863d17ac1b/subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/GradleRunnerNestedBuildTest.groovy) breaks, which uses `GradleBuild` tasks to start nested builds.

The nested builds here are started through `NestedBuildFactory`, which is itself in global scope (through `GradleLauncherFactory`).

**Comment by oehme** [comment]
The NestedBuildFactory has a reference to the `BuildTreeScopeServices`, but doesn't use them for `GradleBuild` tasks. To me this seems like the real problem, because it means that these tasks are not reusing the same build tree/build session services. I'm sure there is a reason for that, but maybe it needs to be reevaluated.

I don't think pushing things up to global scope is the right solution.

Why is this marked as 4.1 RC3? If I understand correctly it has been there since 3.3.

**Comment by jjohannes** [comment]
No it was introduced with 4.0.

The `BuildOperationExecutor` has been in global scope since 3.3 and with 4.0 we moved it to build session scope.

**Comment by oehme** [comment]
That's what I meant, sorry. So this is not a regression in 4.1. In that case I think we shouldn't hold up 4.1 for a hotfix, but fix it properly for 4.2.

**Comment by eriwen** [comment]
+1 to @oehme's suggestion

**Comment by jjohannes** [comment]
Regarding how we fix this:

It looks to me as if nested builds started by a `GradleBuild` task do not fit into the concept of _build tree_ we have right now. Because these are completely independent builds which can even have a different gradle user home - see [GradleBuildTaskIntegrationTest](https://github.com/gradle/gradle/blob/56fc50c36cadbda2ce69c2fdd1c9c4b023133422/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/GradleBuildTaskIntegrationTest.groovy).

I lean towards merging the proposed fix (or something similar) for 4.2 as it restores the previous 3.3+ behavior. Unless I am missing some similar simple, but better, solution here.

@bigdaz do you have any additional thoughts on this?

**Comment by oehme** [comment]
I see, that's the difference I was looking for. I still wonder if there aren't other constraints that this violates. E.g. doesn't that also mean that `GradleBuild` tasks can exceed the max-worker limit of the outer build?

If a global counter was the original behavior, I'm fine with going back to that.

**Comment by ldaley** [comment]
Builds launched with GradleBuild should not be considered to be part of the same build tree. Logically, they are like shelling out another Gradle invocation.

The proposed solution of a global ID sequence seems like a reasonable step, but it _may_ just mask other problems. It seems like it's making stuff work by accident. That said, I don't really understand what non-unique IDs actually broke so this may be a non issue.

**Comment by big-guy** [comment]
Going down the "shelling out another Gradle invocation" line of thought... why are we getting build operations from a `GradleBuild` nested build?  Maybe we just need to cut that off more.

**Comment by jjohannes** [comment]
There is still a minimal amount of integration between the _root_ build and the builds started via `GradleBuild` task. Which is essentially that progress is logged for the `GradleBuild` task builds in the console or the IDE. For that we use the build operations. And it is a feature we should keep. I don't think there is much more to cut off.

I have merged the fix that restores the previous _global id_ behaviour.
