### ISSUE TITLE
com.gradle.plugin-publish should not use `afterEvaluate {}`

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#26236]
### Expected Behavior

com.gradle.plugin-publish does not use `afterEvaluate {}`

### Current Behavior (optional)

com.gradle.plugin-publish uses `afterEvaluate {}`

### Context

`afterEvaluate {}` causes strange, hard to diagnose behaviour. 

`afterEvaluate {}` is difficult to debug and causes interoperability issues with other plugins.

Using `afterEvaluate {}` means that Kotlin DSL accessors are not generated.

**Comment by jbartok** [comment]
Relates to:
* https://github.com/gradle/gradle/issues/21933

Could you provide a specific error or problematic use case?
