### ISSUE TITLE
Gradle won't find groovy versions if the version doesn't start with a digit.

### ISSUE THREAD

**Issue by MeneDev** [gradle/gradle#2623]
Gradle won't find groovy versions if the version doesn't start with a digit.

### Expected Behavior
Gradle finds groovy versions if the version starts with a lowercase hexadecimal digit.

### Current Behavior
Gradle doesn't find groovy versions if the version doesn't start with a digit.

### Context
I tried to use incubating features (macros) and thus wanted to use a recent commit version via jitpack. At first everything worked, because I was using commit 68acdae206. A lated update to ea60e33cb2 failed because the groovy jar could not be found.

### Steps to Reproduce (for bugs)
    plugins {
        id "groovy"
    }

    repositories {
        jcenter()

        maven { url 'https://jitpack.io' }
    }

    dependencies {
        compile 'com.github.apache.groovy:groovy-all:ea60e33cb2fd4b66ae3c6e87200005fa941dca2c'

        testCompile 'junit:junit:4.12'
    }

**Comment by eriwen** [comment]
@DerMene could you please confirm which version of Gradle you're using?

**Comment by DerMene** [comment]
Happens with 4.0.2 and 4.1-rc-2. I identified the code in current master and will provicde a fix.

**Comment by DerMene** [comment]
PR is open https://github.com/gradle/gradle/pull/2634 ;)

**Comment by eriwen** [comment]
@DerMene 👏  we'll take a look — thanks!

**Comment by jjohannes** [comment]
Related: #4360
