### ISSUE TITLE
Continuous Build - changes  to task inputs, or changes to input files?

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#26252]
### Issue type

Wrong or misleading information

### Problem description

The documentation says for Continuous Build 

> Continuous Build allows you to automatically re-execute the requested tasks when task inputs change. 

However, when I run a task I see a message

> Waiting for changes to input files... (ctrl-d then enter to exit)

So either

1. Continuous Build ignores changes to non-file based inputs, and so the website should be updated
2. Continuous Build does not ignore changes to non-file based inputs, so the log message should be updated

### Page with the problem

https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:continuous_build

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

1 is the right answer.
If you are willing to update the documentation, then you are welcome to.
