### ISSUE TITLE
Add `orEmpty` extension for `Provider<String>` type

### ISSUE THREAD

**Issue by Goooler** [gradle/gradle#26251]
### Expected Behavior

If I wanna `secretKey` with nullable value, could be something like:

```kotlin
val secretKey = providers.environmentVariable("SECRET_KEY").orEmpty()
```

### Current Behavior (optional)

```kotlin
val secretKey = providers.environmentVariable("SECRET_KEY").orNull.orEmpty()
```

### Context

We can add an extension for `Provider<String>`, it could be:

```kotlin
inline fun Provider<String>.orEmpty() = orNull ?: ""
```

or

```kotlin
inline fun Provider<String>.getOrEmpty() = orNull ?: ""
```

like the `String?.orEmpty()` in [Kotlin stdlib](https://github.com/JetBrains/kotlin/blob/e4a51dfa1b11d295970af6d0d01c4877dc8c5ad3/libraries/stdlib/src/kotlin/text/Strings.kt#L343-L345), this will be very useful for us.

**Comment by jbartok** [comment]
No, we can't add it as an extension function because we would need it for the Groovy DSL too, and possibly for the Java API. If you need it in your own build, you'll need to add it to your build logic.

We already have the `getOrElse` method, which is a more generic solution to the same problem.
