### ISSUE TITLE
Do not retry source download if response is 404

### ISSUE THREAD

**Issue by kozaxinan** [gradle/gradle#26277]
### Current Behavior

Gradle continues to retry to download the sources.jar even if response is 404 from server.

This situation doesnt exist with Gradle 8.0 but happens with Gradle 8.3.

### Expected Behavior

sources.jar that returns 404 should not be retried.

### Context (optional)

We have huawei dependency and they dont deploy sources.jar
https://developer.huawei.com/repo/com/huawei/agconnect/agcp/1.9.0.300/agcp-1.9.0.300-sources.jar
But the main dependency is there.
https://developer.huawei.com/repo/com/huawei/agconnect/agcp/1.9.0.300/agcp-1.9.0.300.jar

Gradle tries to download sources.jar of huawei dependencies over 800 times

<img width="522" alt="Screenshot 2023-09-04 at 23 19 35" src="https://github.com/gradle/gradle/assets/2559837/8c577da2-cc52-4380-b13b-258a524c68dc">

### Steps to Reproduce

Add huawei dependencies to android project
com.huawei.agconnect:agcp:1.9.0.300

sync android studio or intellij idea with gradle 8.3

### Gradle version

8.3

**Comment by kozaxinan** [comment]
We contacted Huawei about the issue. Their server returned 404 already but they changed the content of the response. Now with the updated version page data, gradle and android studio do not try to retry.
Also we noticed that we had local cache for gradle 8.0 and it worked okey until we delete gradle folder in user folder.

**Comment by big-guy** [comment]
@kozaxinan Gradle does cache 404 responses, so it shouldn't retry after the first time. 

Are you saying that you see 800 requests for the _same_ sources jar or in total (there are 800 Huawei dependencies)?

Do you see this in every sync or only on the first sync after changing to Gradle 8.3?

Now that Huawei has made changes, do you still the same problem when you delete the Gradle user home with 8.0?

**Comment by kozaxinan** [comment]
<img width="1193" alt="Screenshot 2023-09-06 at 15 12 38" src="https://github.com/gradle/gradle/assets/2559837/6113c14f-5df6-4a8e-a52e-aacadad389d2">

It is for group of dependency. But there is really high number for retry.

Also they still return 404 but they changed the response. (i dont have old response) If this appears again, if this gradle issue or intellij idea issue?

**Comment by kozaxinan** [comment]
Side note, problem was not about Gradle 8.3. We had a user on new machine experiencing same situation with gradle 8.0. I assume result was cached on my device.

**Comment by kozaxinan** [comment]
Not anymore because Huawei changed something on their side about what they returned for 404

**Comment by adammurdoch** [comment]
I don't think we should close this issue, as Gradle should not perform more than one HEAD request to a missing resource but seems to be doing many such requests. We should fix this as it unnecessarily impacts sync performance after some Gradle upgrades. The change to the Huawei repo didn't fix this issue, it just made it go away for a while.

**Comment by austinzh** [comment]
We have similar issue, because some sources.jar being quarantined by our internal nexus. Gradle try to download same file over 100 times and it cause us 15 minutes of network time on the --scan performance page.
