### ISSUE TITLE
Add @since annotation to Kotlin DSL reference

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#26286]
### Expected Behavior

Our current Javadocs distribution includes `@since` annotation that shows the version of Gradle in which a method was introduced.

![image](https://github.com/gradle/gradle/assets/2759152/58f9d6bc-b75f-4ee3-aa72-5c49878ac720)

### Current Behavior (optional)

Kotlin DSL shows no information about `@since`

<img width="972" alt="image" src="https://github.com/gradle/gradle/assets/2759152/ccfc3d26-377d-4ed2-9dd4-eb839bb16672">

### Context

It seems this is currently blocked on Dokka feature:

https://github.com/Kotlin/dokka/issues/1618

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritised by them.

**Comment by eskatos** [comment]
This was fixed already by
* https://github.com/Kotlin/dokka/pull/2967

This is part of Dokka 1.9.0 released last week

**Comment by eskatos** [comment]
We need a new version of Dokkatoo to be published before we can fix this

**Comment by alllex** [comment]
Thanks for taking care of this!

**Comment by jbartok** [comment]
Had to revert the PR fixing this... See
* https://github.com/gradle/gradle/issues/26479

**Comment by jbartok** [comment]
Dokatoo `v2.0.0` is out now and should do the job.

**Comment by jbartok** [comment]
Fixed in 
* https://github.com/gradle/gradle/pull/27697
