### ISSUE TITLE
Gradle doesn't expose a comparison failure in test exception causes

### ISSUE THREAD

**Issue by HackerMadCat** [gradle/gradle#26299]
### Current Behavior

Gradle submits a finish test event with an unrecognized nested Junit comparison failure (in the cause of the regular exception). This comparison exception is exposed as DefaultFailure.
![image](https://github.com/gradle/gradle/assets/11194423/760b3562-ce93-4428-9769-6676245ad695)

### Expected Behavior

Gradle should submit a finish test event that has the structure:
```
DefaultTestFinishEvent {
    result = DefaultTestFailureResult {
        failures = [DefaultTestFailure {
            className = "AssertionError"
            causes = [DefaultTestAssertionFailure {
                className = "AssertionFailedError"
                expectedText = "Expected text"
                actualText = "Actual text"
            }]
        }]
    }
}
```

### Context (optional)

Intellij Idea used `ProgressListener` for receiving Gradle events. In particular, we receive test events with comparison info. This info we use for showing detailed comparison view with highlighting of same and different lines. Our users have tests that can wrap exceptions from assertEquals by other exceptions with some additional information about a test or a test environment.

### Steps to Reproduce

1. Create a project with the test file:
```
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.opentest4j.AssertionFailedError

class TestCase {

    @Test
    fun `test wrapped comparison exception`() {
        try {
            Assertions.assertEquals("Expected text", "Actual text", "Assertion message")
        } catch (ex: AssertionFailedError) {
            throw AssertionError("Additional message", ex)
        }
    }
}
```
2. Create a project with Gradle tooling and configure `PregressListener` for `OperationType.TEST`:
```
public class GradleProgressListener implements ProgressListener {
  @Override
  public void statusChanged(ProgressEvent event) {
    if (event instanceof TestFinishEvent testFinishEvent) {
      if (testFinishEvent.getResult() instanceof FailureResult failureResult) {
        System.out.println("-----------");
        System.out.println("Result class: " + failureResult.getClass());
        for (Failure failure: failureResult.getFailures()) {
          System.out.println("Failure class: " + failure.getClass());
          if (failure instanceof TestFailure testFailure) {
            System.out.println("Failure exception: " + testFailure.getClassName());
            for (Failure cause: testFailure.getCauses()) {
              System.out.println("Cause class: " + cause.getClass());
              if (cause instanceof TestFailure causeFailure) {
                System.out.println("Cause exception: " + causeFailure.getClassName());
              }
            }
          }
        }
      }
    }
  }
}
```
3. Execute test task by BuildLauncher

Expected logs:
```
Result class: class org.gradle.tooling.events.test.internal.DefaultTestFailureResult
Failure class: class org.gradle.tooling.internal.consumer.DefaultTestFrameworkFailure
Failure exception: java.lang.AssertionError
Cause class: class org.gradle.tooling.internal.consumer.DefaultTestAssertionFailure
Cause exception: java.lang. AssertionFailedError
```
Actual logs:
```
Result class: class org.gradle.tooling.events.test.internal.DefaultTestFailureResult
Failure class: class org.gradle.tooling.internal.consumer.DefaultTestAssertionFailure
Failure exception: java.lang.AssertionError
Cause class: class org.gradle.tooling.internal.consumer.DefaultFailure
```

### Gradle version

8.4-20230905234741+0000

**Comment by hegyibalint** [comment]
Hi @HackerMadCat,

Could you have a peek at the new [test cases](subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r85/TestFailureProgressEventCrossVersionTest.groovy), and verify that this is exactly what you would like to see?
Feel free to interact on the PR. Thanks!

**Comment by HackerMadCat** [comment]
@hegyibalint I added comments in the review for the [mentioned](https://github.com/gradle/gradle/pull/26399) pull request. 
https://github.com/gradle/gradle/pull/26399#pullrequestreview-1631417739

**Comment by HackerMadCat** [comment]
@hegyibalint it is ok. This issue isn't a blocker for us. Thank you for fix!
