### ISSUE TITLE
Update documentation to describe how to use the descriptive types

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#2629]
Update user guide and plugin implementation guides to describe how to use the new `Directory` and `RegularFile` types to define and wire together task inputs and outputs, and why this is useful.

**Comment by eriwen** [comment]
@adammurdoch are you working on this already or should the core team pick this up?

**Comment by jjohannes** [comment]
So there is a lot one could do here I guess. Like updated existing samples to use this (if we want). But I am not sure where we stand and want to go.

Still to get this started I added a section to the _Writing Custom Plugins_ chapter of the user guide: #2816. Although this could go into a bunch of other places as well. 

@eriwen @adammurdoch We should probably do more here soon. Depending on where we go with documentation, it would help to open additional issues that state more clearly which parts of the doc we want/need to update with what.
I am happy to discuss that but currently I feel a bit lost regarding our documentation.

**Comment by bmuschko** [comment]
@jjohannes I could imagine a dedicated user guide section that talks about laziness and deferred types.

**Comment by adammurdoch** [comment]
I would hold off on this for a bit longer. I don't think the patterns are particularly well established yet for us to push users too hard down this path, and there are changes we want to make.

There are a few ways we might tackle this. I would start by updating the 'writing plugins' user guide chapter to be lazy-type centric, for example: change the samples to use the new types and provide a bit more introductory material about the lazy types earlier and some details about using these lazy types with files specifically.

Then we also have the 'writing tasks' chapter which should switch to using the lazy types, and bunch of samples, and the plugins and tasks guides as well to update.

I would also add some introductory material in 'how to write a build script' too.

**Comment by jjohannes** [comment]
Thanks @adammurdoch I had a quick chat with @bmuschko and we agree. Lets not do anything for 4.2.

**Comment by oehme** [comment]
@adammurdoch How about 4.3? Are we happier with the APIs by now? Or should we further postpone documenting them?

**Comment by adammurdoch** [comment]
My plan is to do something for 4.3, including some docs.

**Comment by lacasseio** [comment]
Here are the various elements to be done for this issue:
- [ ] Write a user guide chapter on deferred configuration
- [ ] Ensure all provider/property Javadoc make sense
- [ ] Ensure all guides are up-to-date with regards to provider/property API

### Open Questions
- Should we handle provider/property differently in the DSL reference documentation (e.g. [`CppCompile#compilerArgs`](https://docs.gradle.org/current/dsl/org.gradle.language.cpp.tasks.CppCompile.html#org.gradle.language.cpp.tasks.CppCompile:compilerArgs))?
- Should we have a topical guide on provider/property API?

**Comment by oehme** [comment]
We already have the provider API somewhat covered in the plugin implementation guide. That probably was too early, since it still changed a lot. Are we close to calling it stable now or should we pull it out of that guide?

**Comment by lacasseio** [comment]
It's stable enough to document it, however, it is hard to choose the right location for such documentation. I was planning to reuse what Jendrik did previously. I was thinking of building a new user guide chapters about deferring configuration in Gradle. I was just writing an outline of the chapter then asking for more feedback. I welcome any feedback as I write the outline.

**Comment by lacasseio** [comment]
Here is an extensive outline of what the [new user guide chapters covering providers could look like](https://docs.google.com/a/gradle.com/document/d/1TB-_beIENjAnI7j3YwgLiuMBE2EfHKy1_MGQ42ERldI/edit?usp=sharing). Please provide feedback.

@eriwen Given this outline/draft do you think it's a good fit for the user guide as well as its content?

**Comment by lacasseio** [comment]
The documentation has been moved to this PR: https://github.com/gradle/gradle/pull/3478. Please provide feedback as soon as possible so we can merge this in 4.4.

**Comment by lacasseio** [comment]
This has been merged to master. PR https://github.com/gradle-guides/implementing-gradle-plugins/pull/16 will be merge once Gradle 4.4 is out.
