### ISSUE TITLE
Why is there no transitive test code resolution?

### ISSUE THREAD

**Issue by stas-bob** [gradle/gradle#26301]
### Expected Behavior
dependencies {
  testApi project(":subproject:subproject2")
}

### Current Behavior (optional)

I have no idea how to do this

### Context

Im using testImplementation but that does not re-expose the dependency to a referencing project.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
