### ISSUE TITLE
Provide an API to allow a task output to be declared as an outgoing artifact of the project

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#2630]
Currently, there is no reliable and public API to allow a particular output of a task to be declared as an outgoing artifact of a project. The `artifacts { }` block and associated APIs basically accept either an `AbstractArchiveTask` or a `File` + 'builtBy' task reference.

For a task type other than `AbstractArchiveTask`, a plugin must use the later option, which means that the output file must be known when the artifact is declared, or the artifact declaration deferred until the output file is known (whenever that might be). Neither of these options is reliable when the build directory or task output is later changed.

There are other downsides to this pattern. From a performance perspective the work to calculate the `File`, which may include file system access to resolve/canonicalize/normalize/validate the output location, must be performed every time the build is configured, rather than on demand when the artifact is required, say via a project dependency. The pattern is also lossy in that the artifact represents the output of a specific task is not retained, meaning we have fewer options to help a user visualize the relationship.

### Expected Behavior

Continue to build on the `Provider<RegularFile>` and `Provider<Directory>` concepts introduced in #2305 to allow instances of these types to be used to declare an outgoing artifact. This will allow a plugin to easily and reliably wire in a task output that is defined using these types as an outgoing artifact.

### Current Behavior

See the description above. There is no reliable way to implement this important use case at the moment.

**Comment by adammurdoch** [comment]
This would be used by the C++ and Swift plugins to declare the outputs of a project. It should later be used to fix a number of issues with the `java-library` plugin.

**Comment by bmuschko** [comment]
@adammurdoch Is this still planned for 4.2-rc1?

**Comment by bmuschko** [comment]
@adammurdoch Could you please close this issue if you deem it ready for release? Otherwise let's just move the milestone to 4.3-rc1.

**Comment by adammurdoch** [comment]
@bmuschko sorry, i meant to close this yesterday. It's done now.
