### ISSUE TITLE
Bad error message when using the wrong Java version

### ISSUE THREAD

**Issue by AugustNagro** [gradle/gradle#26319]
### Current Behavior

simdjson-java ( https://github.com/simdjson/simdjson-java ) is the Java port of the industry-leading json library.

simdjson-java requires Java 20, as specified:

```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(20)
    }
    withJavadocJar()
    withSourcesJar()
}
```

However, when running tests with an older Java, the error message is over-complicated and opaque, especially for those less familiar with Java versioning.

![F5XKZOGWUAEQwM5](https://github.com/gradle/gradle/assets/6350134/e82d4c78-d3e7-4547-8780-56f78384592a)

### Expected Behavior

Java version mis-match is a common problem with any JVM build tool. Gradle should emit a simple and concise message like "Found Java X, required Java Y".

### Steps to Reproduce

Run the tests (or any build step) in https://github.com/simdjson/simdjson-java/tree/main

### Gradle version

8.2

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

The error message contains all the relevant information, however, it can be discussed should it be improved further.

**Comment by donat** [comment]
Here's the spec with the proposed improvements: https://docs.google.com/document/d/13-jwna2kTDpk4hu-69hdksD-QA8ulGkKr485haTROdw/edit?usp=sharing

**Comment by AugustNagro** [comment]
Looks good to me, wdyt @lemire

**Comment by lemire** [comment]
Looks better to me. (The Google Docs proposal.)
