### ISSUE TITLE
Non-interactive, non-DSL method to agree to Build Scan terms-of-service

### ISSUE THREAD

**Issue by msgilligan** [gradle/gradle#26316]
### Expected Behavior

I want to enable Build Scans without applying the Gradle Enterprise Plugin in my project _and_ agree to the terms-of-service non-interactively.

I can't use the `gradleEnterprise` or `buildScan` closure in either the project or an init-script because the plugin isn't installed.

Given that the **Gradle Enterprise Gradle Plugin User Manual** says:

> Be careful not to commit agreement to the terms of service into a project that may be built by others.

It seems like there should be a way to do this with a command-line option, environment variable, properties file or other mechanism that I can enable in my CI `.yml` files.

### Current Behavior (optional)

```
$ gradle build --scan

FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/sean/.gradle/init.d/build-scan-agree.gradle' line: 1

* What went wrong:
A problem occurred evaluating initialization script.
> Could not find method buildScan() for arguments [build_scan_agree_bjec7e8o82f6v8auo952om7on$_run_closure1@1a169943] on build of type org.gradle.invocation.DefaultGradle.

```

### Context

I am trying to create Build Scans in a CI environment on a project and for technical reasons (ultimately caused by Gradle not having a bootstrappable build that is Debian Free Software Guidelines compliant) I can't apply the Gradle Enterprise Plugin in either `build.gradle` or `settings.gradle`.

I can't use the `gradleEnterprise` or `buildScan` closure in either the project or an init-script because the plugin isn't installed.

**Comment by msgilligan** [comment]
Note: I commented on a closed issue https://github.com/gradle/gradle/issues/4526#issuecomment-1710814121 before deciding to open a new issue specific to this problem.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by msgilligan** [comment]
By the way, for me this issue is greatly complicated by the fact that I have to support building with Gradle 4.4.x. See: https://github.com/gradle/gradle/issues/26516

**Comment by wolfs** [comment]
This init script seems to work:

```
def isTopLevelBuild = gradle.getParent() == null

if (isTopLevelBuild) {
    def gradleVersion = GradleVersion.current().baseVersion
    def atLeastGradle6 = gradleVersion >= GradleVersion.version("6.0")
    if (atLeastGradle6) {
        settingsEvaluated { settings ->
            settings.pluginManager.withPlugin("com.gradle.enterprise") {
                configureExtension(settings.extensions["gradleEnterprise"].buildScan)
            }
        }
    } else {
        rootProject { root ->
            root.pluginManager.withPlugin("com.gradle.build-scan") {
                configureExtension(root.extensions["buildScan"])
            }
        }
    }
}

void configureExtension(extension) {
    extension.with {
        if (delegate.metaClass.respondsTo(delegate, 'setTermsOfServiceUrl')) {
            termsOfServiceUrl = "https://gradle.com/terms-of-service"
            termsOfServiceAgree = "yes"
        } else {
            licenseAgreementUrl = "https://gradle.com/terms-of-service"
            licenseAgree = "yes"
        }
    }
}
```

It works for Gradle 4.4 to 8.x at least. Is that enough?

**Comment by msgilligan** [comment]
Thanks @wolfs ! This is a beautiful solution. I just submitted a PR to **bitcoinj** with this script and it is passing in our GitHub Actions:
https://github.com/bitcoinj/bitcoinj/pull/3289

And it also works with Debian Gradle 4.4.x in our GitLab CI build scripts:
https://github.com/bitcoinj/bitcoinj/pull/3290

FYI: Gradle 4.4.x gives a warning:
```
Initialization script '/builds/bitcoinj/bitcoinj/build-scan-agree.gradle' is using GradleVersion from the private org.gradle.util package without an explicit import. Please either stop using these internal classes (recommended) or import them explicitly at the top of your build file. The implicit import is deprecated and will be removed in Gradle 5.0
```
See https://gitlab.com/bitcoinj/bitcoinj/-/jobs/5186695664 for details.

The warning is not an issue for us, though.

Thanks again!

**Comment by msgilligan** [comment]
I'm going to close this issue because the script that @wolfs provided works perfectly for us.

However, it might be a good idea to document this solution elsewhere, because others will likely find it helpful.
