### ISSUE TITLE
The `JavaExecHandleBuilder` generates invalid `Class-Path` entries

### ISSUE THREAD

**Issue by joakime** [gradle/gradle#26313]
### Current Behavior

When on windows, the behavior in `JavaExecHandleBuilder` to create `Class-Path` entries in the jar manifest is useful effort.

See #10544 and #10114

But the code in the `master` branch generates the entries with absolute URLs

https://github.com/gradle/gradle/blob/84a06b8c37547adcc2977ea696c4307ab2b3e0c3/subprojects/core/src/main/java/org/gradle/process/internal/JavaExecHandleBuilder.java#L405-L411

This is not what the JAR spec allows for the `Class-Path` attribute.

See: https://docs.oracle.com/en/java/javase/17/docs/specs/jar/jar.html#class-path-attribute

Those entries are supposed to be relative URL reference to the context of the jar file that contains those entries.

The absolute URL references are not considered valid.

See bullet point 2 of the above referenced javadoc (copy/pasted here)

> A Class-Path entry is valid if the following conditions are true:
> * It can be used to create a [URL](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URL.html#%3Cinit%3E(java.net.URL,java.lang.String)), by resolving it against the context JAR’s URL.
> * It is relative, not [absolute](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URI.html#isAbsolute()), i.e. it does not contain a scheme component, except for the case when the context JAR is loaded from the file system, in which case the file scheme is permitted for compatibility reasons.
> * The location of the JAR file or directory represented by this entry is contained within the containing directory of the context JAR. Use of "../" to navigate to the parent directory is not permitted, except for the case when the context JAR is loaded from the file system.  
>
> Invalid entries are ignored. Valid entries are resolved against the context JAR. If the resulting URL is invalid or refers to a resource that cannot be found, then it is ignored. Duplicate URLs are ignored.

### Expected Behavior

The `Class-Path` entries should be generated as relative URL references to the JAR file that has those entries.

### Steps to Reproduce

See examples at
* https://stackoverflow.com/q/77055635/775715
* https://stackoverflow.com/q/77017801/775715

### Gradle version

all

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

While you provided us a great explanation about why it might be a problem, we want to be 100% sure that this is a problem in practice.

**Comment by joakime** [comment]
> While you provided us a great explanation about why it might be a problem, we want to be 100% sure that this is a problem in practice.

There are 2 open questions that show the problem in practice on stackoverflow right now.
Both have examples, and logs, and details of the manifest.

* https://stackoverflow.com/q/77055635/775715
* https://stackoverflow.com/q/77017801/775715

Both happen to be on Windows.

**Comment by ov7a** [comment]
I agree that your analysis is great. However, could you please provide a reproducer which demonstrates the issue in isolation? The issues you're pointing at contain some steps, sure, however, we're not 100% sure that the problem is caused by Gradle and not some integration issues.

**Comment by joakime** [comment]
Do you have an example project that uses JavaExecHandleBuilder that I can build a reproducer from?

If you ask me to build one, it's going to require a Windows box with multiple drive letters accessible from Java.

**Comment by ov7a** [comment]
No, we don't have such a template. I think you can use the SO questions you mentioned and adapt the basic template I mentioned before. Creating a custom task with `create<JavaExec>` should be enough to reach `JavaExecHandleBuilder`.

We don't provide Windows boxes. I believe Microsoft has some free images available for testing.
