### ISSUE TITLE
Could not set unknown property 'website' for extension 'gradlePlugin' of type org.gradle.plugin.devel.GradlePluginDevelopmentExtension.

### ISSUE THREAD

**Issue by yechaoa** [gradle/gradle#26314]
### Current Behavior

Could not set unknown property 'website' for extension 'gradlePlugin' of type org.gradle.plugin.devel.GradlePluginDevelopmentExtension.

### Expected Behavior

./gradlew publishPlugins

### Steps to Reproduce

gradle 8.0、AGP 8.1.1

plugins {
    id 'com.gradle.plugin-publish' version '1.1.0'
}

group 'com.yechaoa.plugin'
version '1.0.0'

gradlePlugin {
    website = 'https://github.com/yechaoa/GradleX'
    vcsUrl = 'https://github.com/yechaoa/GradleX.git'
    plugins {
        dependenciesplugin {
            id = 'com.yechaoa.plugin.dependencies'
            implementationClass = "com.yechaoa.plugin.DependenciesPlugin"
            displayName = 'DependenciesPlugin'
            description = 'Show Dependencies Plugin'
            tags.addAll('dependencies', 'yechaoa', 'plugin')
        }
    }
}

Could not set unknown property 'website' for extension 'gradlePlugin' of type org.gradle.plugin.devel.GradlePluginDevelopmentExtension.

### Gradle version

gradle-8.0

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
