### ISSUE TITLE
Clean up next gen build cache prototype

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#26321]
We now have results we needed. We will rethink the API that will very likely be a lot different what we currently have with build cache. 

So lets remove current code and tests and stop CI, since they cause also some headaches to dev productivity team.

**Comment by sgammon** [comment]
@asodja is there a place to follow this development? we make a wire-compatible gradle build cache and want to make sure we can stay compatible

**Comment by asodja** [comment]
Hey @sgammon,
currently there is no public item or doc for the new caching. Also we don't actually have exact plan for it yet and we won't actively work on it at least till next year. 

When we will have better plan, we will add an item to [Gradle Roadmap](https://github.com/orgs/gradle/projects/31) and probably some public spec will also follow. There is also `in:build-cache` label that we normally use for PRs related to build cache if you are really interested.

**Comment by sgammon** [comment]
@asodja okay! thank you for the pointers 😄
