### ISSUE TITLE
Evaluate "true" and "false" properties set in gradle.properties or with -P to boolean variables

### ISSUE THREAD

**Issue by mauromol** [gradle/gradle#2632]
From: https://issues.gradle.org/browse/GRADLE-2306
See also: https://stackoverflow.com/questions/35078203/boolean-properties-in-gradle-properties-file-is-read-as-string

### Expected Behavior
Setting a variable in gradle.properties or through -P command line switch with value "true" or "false" (case insensitive?) evaluates to a boolean value when running the Gradle script.
This would be extremely useful when using such variables for switches. For example, let `enableIncrementalCompilation` be a variable set with any of those techniques and let it be set to "false", the following:

```
tasks.withType(JavaCompile) {
  options.incremental = enableIncrementalCompilation
}
```
should disable the incremental compilation.

### Current Behavior
All variables set in gradle.properties or through -P command line switch evaluate to strings. Because of Groovy Truth, the above example causes the incremental compilation to be enabled.

### Context
See above examples when using variables to implement switches.

### Steps to Reproduce (for bugs)
See above.

I think this would be much more natural and help on the "build happiness" concept ;-)

**Comment by vlsi** [comment]
I've been playing with properties for a bit, and it looks like there are different cases.

For instance:

```
Command line                         | Desired value
<empty>                              | true/false/throw
-PenableIncrementalCompilation       |  true/false/throw
-PenableIncrementalCompilation=abc   |  true/false/throw
-PenableIncrementalCompilation=true  |  true
-PenableIncrementalCompilation=false | false
```

Note that there might be 3^3 == 27 implementations of `getPropertyAsBool("enableIncrementalCompilation")`

As of now I'm using the following helper in `settings.gradle.kts`:

```kotlin
fun String?.toBool(nullAs: Boolean, blankAs: Boolean, default: Boolean) =
    when {
        this == null -> nullAs
        isBlank() -> blankAs
        default -> !equals("false", ignoreCase = true)
        else -> equals("true", ignoreCase = true)
    }

if (startParameter.projectProperties["localReleasePlugins"]
        .toBool(nullAs = false, blankAs = true, default = false)
) {
        // This enables to use local clone of vlsi-release-plugins for debugging purposes
        includeBuild("../vlsi-release-plugins")
}
```

It would be nice if user-friendly boolean accessor was added.

**Comment by mauromol** [comment]
Closed as not planned. That's unfortunate...

**Comment by ljacomet** [comment]
The recommended path in modern Gradle to get to a Gradle property is now `ProviderFactory.gradleProperty(name)` which returns a `Provider<String>`.
It is not desirable to have a `Boolean` conversation on `Provider`, which is a generic type.

We don't think that adding `ProviderFactory.booleanProperty` is worth having when you can `.map(Boolean::parseBoolean)` the returned provider where it makes sense for your build.
