### ISSUE TITLE
Task output is lost at the end of a build

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#2635]
### Expected Behavior
The output of a task should always be shown:
```
gradle (dl/xcode-ide-composite)*$ gw install
Parallel execution is an incubating feature.
Build cache is an incubating feature.

> Task :ideNative:compileJava
/Users/daniel/gradle/gradle/subprojects/ide-native/src/main/java/org/gradle/ide/xcode/plugins/XcodePlugin.java:308: error: cannot find symbol
            getLifecycleTask().dependsOn(new Callable<List<TaskDependency>>() {
                                             ^
  symbol:   class Callable
  location: class XcodePlugin
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ideNative:compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
272 actionable tasks: 33 executed, 239 up-to-date

Publishing build scan...
https://e.grdev.net/s/cntjwqbjfy356
```

### Current Behavior

The output of the task `:ideNative:compileJava` isn't shown (aka, the compiler output). Executing a second time, the output is shown as demonstrated above.
```
gradle (dl/xcode-ide-composite)$ gw install
Starting a Gradle Daemon (subsequent builds will be faster)
Parallel execution is an incubating feature.
Build cache is an incubating feature.

> Configure project :
Downloading the released versions from: https://services.gradle.org/versions/all

> Task :docs:dslMetaData
Parsed 1313 classes in 5.391 seconds

Download https://repo.gradle.org/gradle/libs-releases/biz/aQute/bnd/biz.aQute.bndlib/3.4.0/biz.aQute.bndlib-3.4.0.pom
Download https://repo.gradle.org/gradle/libs-releases/biz/aQute/bnd/biz.aQute.bndlib/3.4.0/biz.aQute.bndlib-3.4.0.jar

> Task :codeQuality:compileGroovy
Note: /Users/daniel/gradle/gradle/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :ide:compileGroovy
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ideNative:compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 2s
272 actionable tasks: 95 executed, 71 from cache, 106 up-to-date

Publishing build scan...
https://e.grdev.net/s/zzfrkibgrsczo
```

### Context

With parallel enabled, the output of the last task causing the build to fail isn't shown. It would seem this is a flaky behavior as the output is shown the second time I ran the task.

### Steps to Reproduce (for bugs)

In this case, the `compileJava` task failed resulting in the a build failure. Parallel is enabled and lots of tasks we out-of-date.

### Your Environment

 * Build scan URL:  See in build outputs.

**Comment by big-guy** [comment]
If you look at the build scan for the build that is missing output, it's not in the build scan log either. So it's probably not a problem with the new console.  It's probably something to do with the stdout/stderr not being flushed from the compiler daemon if the error happens quickly enough.

**Comment by ghale** [comment]
I've found a problem that sounds sneakily similar to this.  Basically, we use a cached thread pool for the threads that process output from sub-processes like this.  To write to our logging framework, we have a `LinePerThreadBufferingOutputStream` that captures stuff written to System.out or System.err.  This object has a thread local `PrintStream` object that handles all text written to it.  However, this object can be closed, which closes the `PrintStream` object, but doesn't remove it from the thread local.  This means that if this thread is re-used, you can get a `PrintStream` that has been closed has nothing underneath it, so anything sent to this object just gets dropped.  

Given that this affects only threads that are being re-used, it's much more likely to hit tasks later in the build.  I wouldn't be surprised if what you're seeing here is the same issue.
