### ISSUE TITLE
Dependency configuration testRuntime still exists in docs

### ISSUE THREAD

**Issue by Detybear** [gradle/gradle#26351]
### Issue type

Wrong or misleading information

### Problem description

The picture “figure 1” on the documentation page [Declaring Dependencies](https://docs.gradle.org/8.3/userguide/declaring_dependencies.html#sec:what-are-dependency-configurations) contains the dependency configuration _testRuntime_. However, _testRuntime_ has been removed since version 7 according to this [upgrading information](https://docs.gradle.org/8.3/userguide/upgrading_version_6.html).

### Page with the problem

https://docs.gradle.org/8.3/userguide/declaring_dependencies.html#sec:what-are-dependency-configurations

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by Detybear** [comment]
This image kept me long time from deeper understanding gradle dependency management. I'm using gradle for years now - most of the time just calling ready-to-use build scripts of our projects. Unfortunately many of these gradle scripts still contain (or contained) _testRuntime_ and unfortunately I didn't see that I only would have to go to an older document version to understand the meaning. I always thought _testRuntime_ is some sort of undocumented magic.

Even now (I structured a multi-project build a month ago), I'm not yet 100% confident with all of the dependency configurations documented for the Java plugin and the Java library plugin. It still feels like something's missing. But I think, I should open a new issue for that, once I can state that a bit more concrete...
