### ISSUE TITLE
Add a Locale dimension replacing the Flavor used to specify the locale

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle#2637]
Currently, Gradle suggest to use the Flavor for getting a localized build. This issue suggest an improvement by adding a specialized dimension for the locale as found in many C/C++ product, letting the Flavor dimension for other flavors like { Community, Professional, Enterprise }

### Expected Behavior
A Locale dimension defaulted to { en_US } .

### Current Behavior
Not relevant

### Context
Used for producing a multi lingual product

### Steps to Reproduce (for bugs)
Not relevant

### Your Environment
------------------------------------------------------------
Gradle 4.2-20170721201715+0000
------------------------------------------------------------

Build time:   2017-07-21 20:17:15 UTC
Revision:     78cd08b711e683bb56f97767d96c99bea1266e67

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_80 (Oracle Corporation 24.80-b11)
OS:           Windows 8.1 6.3 amd64

C:\Users\fandre\Documents\git\poco-gradle>

**Comment by bmuschko** [comment]
@lacasseio Could you have a look?

**Comment by lacasseio** [comment]
Thanks @zosrothko for raising this issue and confirming some discussion we were having internally. The flavor dimension is quite limiting as it is now. We are discussing how to better solve the variant issue for native. One solution path is to allow users to define their custom dimension. In your case, you would be able to declare a language dimension with your own modeling. This dimension would take part in the dependency resolution. By default, the same language would match binaries together, however, if a language binary is missing, you would be able to match it with a default language, like French for example. Follow the [`gradle-native` project](https://github.com/gradle/gradle-native) for more information once we start breaking down the work for implementation.
