### ISSUE TITLE
Reproduction template lacks basic info

### ISSUE THREAD

**Issue by Danjhop4** [gradle/gradle#26375]
### Issue type

Wrong or misleading information

### Problem description

You demand I use a template missing basic info for bug reports that will not even work then close bug because I won’t use that template even though it  is less the the minimum needed to compile

### Page with the problem

N/a

**Comment by big-guy** [comment]
I'm not sure how we can help. 

If you have a problem with Gradle and can provide a reproducer (with our template or any other way), we may be able to help.  Opening issues like this and saying the same thing over and over isn't working.
