### ISSUE TITLE
Include sample for configuring build cache via init script

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#2638]
We mention in various places that it's possible to configure the build cache via init scripts, but we don't provide an example in the user guide docs or build cache Gradle guide.

This would make a good standalone "Enable the Build Cache" guide if we don't want to include it in our distribution samples.

This is an example from our integration tests:
https://github.com/gradle/gradle/blob/REL_4.0.2/subprojects/core/src/integTest/groovy/org/gradle/caching/configuration/BuildCacheConfigurationIntegrationTest.groovy#L48-L61

**Comment by wolfs** [comment]
Fixed: https://docs.gradle.org/current/userguide/build_cache.html#example_init_script_to_configure_the_build_cache
