### ISSUE TITLE
Dependency configurations should be explained better

### ISSUE THREAD

**Issue by Detybear** [gradle/gradle#26389]
### Issue type

Missing information

### Problem description

Looking at the documentation page [The Java Plugin](https://docs.gradle.org/8.3/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) you can find the following explanations in the section dependency management:

```
implementation
	Implementation only dependencies.
compileOnly
	Compile time only dependencies, not used at runtime.
...
```

These remind me a little of [Monty Python Comments](https://github.com/Droogans/unmaintainable-code#monty-python-comments) as stated in the funny but (at least for me) instructive article “How to write unmaintainable code” written by Roedy Green.

My thoughts on these definitions are the following:

### Dependency configuration _implementation_

"Implementation" is a word, which can have various meanings depending on the context (see for example explanations on [Wiktionary](https://en.wiktionary.org/wiki/implementation), [Wikipedia](https://en.wikipedia.org/wiki/Implementation), or [Merriam Webster](https://www.merriam-webster.com/dictionary/implementation)). Maybe this word is not a good choice at all. Maybe however, it's the best word one could find. I don't want to judge on this. But knowing, that this word is vague, it would be good to describe, what it means in the gradle context.

For example: "Implementation dependencies. Meant are all dependencies needed both at compile and at runtime. That is, the normal dependencies of a ready-to-use software implementation."

BTW: the word "only" in the current text makes things worse rather than better. After all, these dependencies are used in two places, aren't they?

### Dependency configuration _compileOnly_
Despite "compile" has a very exact meaning in software industries,  it would be good to give some example(s) here. All I can think of at the moment are annotations with RetentionPolicy SOURCE. But then you probably need as well an annotation processor that is running at compile time. Such a processor will probably come in the same jar as the annotation and you should put the dependency under the dependency configuration _annotationProcessor_ - at least I think. Are their better examples for the existence of this somewhat awkward (or at least rarely used) dependency configuration?

This leads me to my next points corresponding to the

### Dependency configuration _annotationProcessor_

- The task _compileJava_ surely uses as well _annotationProcessor_, but that's not visible on figure 2 of this page. (There should be at least some hint that this dependency configuration has been omitted for the sake of simplicity.)
- Maybe it's a good idea to state, that these dependencies will be handed over to the javac --processor-path argument.
- BTW: Shouldn't there be something like a _testAnnotationProcessor_ as well? Did so far nobody use annotation processing while compiling the tests?

### Dependency configuration _runtimeOnly_
Basically the same as with _compileOnly_: an example would help here. At the moment I can only think of JDBC drivers but that's  maybe not quite exact the thing. At least if the application can be plugged to an arbitrary database. Then the developper does not even want to define this beforehand.

### Didactic thoughts on the sequence of the presentation
Finally, in the list of dependency configurations it is not yet clear that some of them are not intended to actually declare dependencies, like _compileClasspath_ and _runtimeClasspath_. If the reader does not read further, he might use these directly in the build script. At least he gets some brain overload, because he cannot understand at this point, why these dependency configurations are existing at all. For example: not yet knowing the background gives the impression, that _implementation_ and _compileClasspath_ are the same.

### Page with the problem

https://docs.gradle.org/8.3/userguide/java_plugin.html#sec:java_plugin_and_dependency_management

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
