### ISSUE TITLE
FileTree from directory with complex permissions AcessDeniedException

### ISSUE THREAD

**Issue by kevin-j-smith** [gradle/gradle#2639]
While working on a project to test the build of a project that is installed using root I am trying to gather log files from the install.   These log files are in a directory which has other directories owned by root:root and with permissions 660.  These other directories I am not interested in.   When I try to get the directory as a file tree I am experiencing java.nio.file.AccessDeniedException and org.gradle.api.GradleException: Could not read path.   

### Expected Behavior
I am expecting that the exclude behavior will work properly on files/directories even when they are not accessible.  IE.  I can read the requested directory but not inside the excluded directory.   When an AccessDeniedException occurs on a excluded ant filter it will be caught and skipped.  

### Current Behavior
Exceptions.   

### Context
I am trying to create a custom plugin which takes a filetree and does some basic validation on the files found in the tree.   

### Steps to Reproduce (for bugs)
mkdir -p tmp/foo
touch tmp/foo/x
sudo mkdir tmp/bar
sudo touch tmp/bar/y
sudo chmod 660 -R tmp/bar

build.gradle:
task printFileTree() {
        doLast {
                def ft = fileTree(dir: 'tmp', exclude: 'bar');
                ft.collect { relativePath(it) }.sort().each{ println it}
        }
}

// In this instance I would expect bar to be found but not accessible and that is why I am excluding it from the tree.  (also tried '**/bar','**/bar/**','bar/**','.*bar.*'...).   

### Current work around
Though I am not sure how to bypass converting ArrayList to FileTree to work in my environment (which other custom plugin classes are leveraging) I can get the list of files needed by:

def files = []
 tmpDir.traverse(
    type    : FileType.FILES,
    nameFilter : ~/.*.log/,
    maxDepth : 0,
    excludeFilter   : ~/ssl/
) { files << it }
return files

In this example I am searching the root directory for log files and excluding the constrained ssl directory.  

### Your Environment

 * Build scan URL: 
gradle --version

------------------------------------------------------------
Gradle 4.0.2
------------------------------------------------------------

Build time:   2017-07-26 15:04:56 UTC
Revision:     108c593aa7b43852f39045337ee84ee1d87c87fd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0 (IBM Corporation 2.8)
OS:           Linux 3.10.0-514.26.2.el7.x86_64 amd64

**Comment by adammurdoch** [comment]
The implementation needs some work before we can close this issue and release the fix. See the comments on the PR.

**Comment by kevin-j-smith** [comment]
Nice, thanks.  This will be helpful.
