### ISSUE TITLE
Test execution/performance is much slower than a hand-build test launcher script

### ISSUE THREAD

**Issue by transentia** [gradle/gradle#26410]
### Current Behavior

I have Geb/Spock tests.

Running via gradle tests the suite takes about 20 mins.

If I run via a simple Groovy script that uses Spcock's EmbeddedSpecRunner the tests take ~5 mins. That's a significant difference.

The script is (in essense):

```
protected static final ant = new AntBuilder()
protected static final CLASSES = "build/classes/groovy/test"
private static final CWD = new File(CLASSES).toPath().toAbsolutePath().toString()

final embeddedSpecRunner = new EmbeddedSpecRunner()
embeddedSpecRunner.throwFailure = false

def scanner = ant.fileScanner {
	fileset(dir: CLASSES_DIR) {
		include(name: "**/*Spec.class")
		exclude(name: "SomeUnwantedSpec.class")
	}
}

scanner.iterator().collectEntries { f ->
	def className = (((f.toString() - CWD - '.class')[1..-1]).replaceAll('\\\\', '.'))

	Class<GebReportingSpec> spec = Class.forName(className)
	def results = embeddedSpecRunner.runClass(spec)
	results.testEvents()
				.debug()
				.assertStatistics(stats -> {
					stats.failed(0)
				})

	[(className): (results.getTimeFinished() - results.getTimeStarted())]
	}
```

[SADLY (for MY situation)...something in the combination of Geb,Spock and (probably) Geb Spock Reports gets very confused and generates unusable reports...but the actual testing mechanics are performed OK.]

I have tried various combinations of gradle's forkEvery and Geb browser/driver caching, etc. To no avail.

I observe that my actual tests complete in 1-2 secs, but there are ~3s of 'hosekeeping' going on between each test.
--profile doesn't help. haven't run a build scan. Not sure it will help if profile doesn't. This would fit in with the idea (from the URL given below) that Gradle is spending a lot of time on "filter housekeeping"? If this IS the case...any suggestions how to speed things up?

I'm not really expecting any solution here but I thought that other people would find the existence of EmbeddedSpecRunner useful and worthy of having it appear in searches.

### Expected Behavior

Better performance would be nice!

### Context (optional)

I found this from history:
https://discuss.gradle.org/t/test-run-slow-when-running-with-test-com-example-footest/18489

Not sure if anything happened...

### Steps to Reproduce

Create a build.gradle with test tasks that have code like:

```
tasks.withType(Test).configureEach {
    testLogging {

        // doco says: "Only relevant if showStackTraces is true." but actually also relevant here 'cos
        // showStackTraces defaults to true
        exceptionFormat "short"
    }

    // should NEVER run THIS task, only the ones based on it
    outputs.upToDateWhen { true }

    ignoreFailures = true

    failFast = false

    // gradle properties
    useJUnitPlatform()

    reports {
        junitXml.required = false
        html.required = false
    }

    maxParallelForks = 1
}

tasks.register('testMyStuff', Test) {
    description = 'Runs tests.'
    group = 'verification'

    outputs.upToDateWhen { false }

    filter {
        includeTestsMatching 'stuff.*'

        excludeTestsMatching 'other.stuff.*'
        excludeTestsMatching 'more.stuff.*'
    }
}
```

### Gradle version

Tested on 8.3.1 but not specific to any version

### Your Environment (optional)

java 18.0.2.1 on windows

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
@transentia did you see if the amount of memory given to the standalone launcher script vs the test worker were comparable?  By default, test workers are limited to max heap of 512M and a standalone groovy script might be much larger. 

If memory was about the same, we'd need a more complete reproducer with example tests.
