### ISSUE TITLE
The compressed package file is incomplete

### ISSUE THREAD

**Issue by wds-job** [gradle/gradle#26424]
### Current Behavior

I tried to use gradle to package the project source to tar.gz. The.gitignore file is missing in the directory after the package was unzived. I tried to add "from .gitignore" but it didn't work

![image](https://github.com/gradle/gradle/assets/26320403/66df9f05-028b-440f-808c-91fc1b3ae2a9)

### Expected Behavior

The “.gitignore” file should be included in the zip package

### Context (optional)

Unable to fully package the project source code

### Steps to Reproduce

1. use idea create springboot project 
2. make file :build.gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.1.3'
    id 'io.spring.dependency-management' version '1.1.3'
}
group = 'cn.xcode'
version = '23.09.01'
sourceCompatibility = '17'
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}
repositories {
    mavenLocal()
    maven { url 'https://maven.aliyun.com/repository/public' }
    mavenCentral()
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
tasks.named('test') {
    useJUnitPlatform()
}
task src(type: Tar) {
    var tarGzName = "${project.name}-${project.version}-src.tar.gz" 
    compression = Compression.GZIP
    archiveFileName.set(tarGzName) 
    includeEmptyDirs.is(true) 
    destinationDirectory.set(file("$buildDir" + File.separator + "dist"))
    from (projectDir){
        exclude '.gradle/**'
        exclude 'build/**'
        exclude '.idea/**'
        exclude '.git/'
    }
}
3. exec shell : gradle clean src
4. Pressurize the compressed package in the dist directory to see if it contains “.gitignore” file

### Gradle version

7.6.2

### Your Environment (optional)

idea: 2022.3.1 
gradle: 7.6.2
system: win11

**Comment by wds-job** [comment]
![image](https://github.com/gradle/gradle/assets/26320403/d2d58816-e3e3-41aa-8777-1c23bdc1181d)

**Comment by wds-job** [comment]
project code : 
[xcode-bdp.zip](https://github.com/gradle/gradle/files/12655005/xcode-bdp.zip)

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Related:
* https://github.com/gradle/gradle/issues/11176

Please refer to default excludes documentation [here](https://docs.gradle.org/current/userguide/working_with_files.html)

**Comment by wds-job** [comment]
This seems to be a bug, testing the steps and configuration parameters and packaging, check out the zip package in the previous comment，Why close

**Comment by ov7a** [comment]
@wds-job Please, read the documentation.

> By default, fileTree() returns a FileTree instance that applies some default exclude patterns for convenience — the same defaults as Ant in fact. For the complete default exclude list, see [the Ant manual](http://ant.apache.org/manual/dirtasks.html#defaultexcludes).
> If those default excludes prove problematic, you can workaround the issue by changing the default excludes in the settings script:
