### ISSUE TITLE
Cannot wire `RegularFileProperties` using `Provider.map()`

### ISSUE THREAD

**Issue by tudortimi** [gradle/gradle#26429]
### Current Behavior

When I try to wire two `RegularFileProperties` together using `map()`, I get an error message stating that they are incompatible:

> Cannot get the value of task ':consume' property 'input' of type org.gradle.api.file.RegularFile as the provider associated with this property returned a value of type org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultRegularFileVar.

The task have an `OutputFile` and an `InputFile` property respectively:

```
abstract class ProducerTask extends DefaultTask {
    @OutputFile
    abstract RegularFileProperty getOutput()
}

abstract class ConsumerTask extends DefaultTask {
    @InputFile
    abstract RegularFileProperty getInput()
}
```

I'm using `register()` to create the tasks:

```
def produce = tasks.register('produce', ProducerTask) {
    output = file(new File(buildDir, 'some_file'))
}
def consume = tasks.register('consume', ConsumerTask) {
    input = produce.map { it.output }
}
```

### Expected Behavior

My expectation would be that it's possible to wire the two properties like this.

### Steps to Reproduce

The following `build.gradle` reproduces the issue:

```
abstract class ProducerTask extends DefaultTask {
    @OutputFile
    abstract RegularFileProperty getOutput()

    @TaskAction
    void produce() {
        output.get().getAsFile().text = 'produced'
    }
}

abstract class ConsumerTask extends DefaultTask {
    @InputFile
    abstract RegularFileProperty getInput()

    @TaskAction
    void produce() {
        println "Consuming: ${input.ge().getAsFile().text}"
    }
}

def produce = tasks.register('produce', ProducerTask) {
    output = file(new File(buildDir, 'some_file'))
}
def consume = tasks.register('consume', ConsumerTask) {
    input = produce.map { it.output }
}
```

Just call the `consume` task.

### Gradle version

7.5.1, 8.3

**Comment by tudortimi** [comment]
I've thought a bit about this. Is the user supposed to do the following to wire:

```
def consume = tasks.register('consume', ConsumerTask) {
    input = produce.map { it.output.get().getRegularFile() }
}
```

**Comment by tudortimi** [comment]
I'm actually debugging a different bigger issue and got confused with how to properly wire properties together using `map()`. I'm guessing `input = produce.map { it.output.get() }` is the way to go.

**Comment by asodja** [comment]
`produce.map { it.output }` returns `Provider<RegularFileProperty>`, but you don't want to wrap a `RegularFileProperty` in a `Provider`. To solve that you should use `flatMap`, e.g.:
`input = produce.flatMao { it.output }`.

**Comment by tudortimi** [comment]
@asodja Actually, one more question if I may. I get that the two forms are equivalent when it comes to what gets returned. Do both forms (the `map()` form I showed and the `flatMap()` form that you showed) behave the same when it comes to preserving task relationships?

**Comment by asodja** [comment]
They should both carry task dependencies in that case, yes. 

There is small difference in execution though, and I've seen some issues where task relationship get "lost" with `.map { it.something.get() }` with chaining, e.g.: https://github.com/gradle/gradle/issues/26363#issuecomment-1717733649.
Although that might be also Gradle bug.

**Comment by lptr** [comment]
FTR, we are considering supporting (via generated Kotlin extension methods, and some Groovy magic) a notation where you could write the above as:

```kotlin
input = produce.output
```

See https://github.com/gradle/gradle/issues/25755
