### ISSUE TITLE
Ear Plugin: XML Schema / xmlns in Ear Descriptor for Java EE 8, Jakarta EE 9 and Jakarta EE 10 is missing / invalid

### ISSUE THREAD

**Issue by p-schneider** [gradle/gradle#26438]
### Issue type

Polishing

### Problem description

I would expect the `version` Property for `ear.deploymentDescriptor` to fully support values up to `"10"` (Jakarta EE 10).

Currently the documentation of the `version` property (comment / javadoc in DeploymentDescriptor.java) states it only supports values up to "6" while in fact it currently already properly handles "7".
Higher values lead to a descriptor with invalid/missing xmlns.

A desciptor like this:
```gradle
ear {
    deploymentDescriptor {
        version = "10" // <--- it currently only fully supports values up to "7"
        applicationName = "example"
        displayName = "Just an Example"
        // ... remaining properties omitted here ...
    }
}
```
Should generate the descriptor like this:
_(With valid xmlns etc. according to the JAVA EE / Jakarta EE Schemas)_
```xml
<?xml version="1.0"?>
<application xmlns="https://jakarta.ee/xml/ns/jakartaee" xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/application_10.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="10">
  <application-name>example</application-name>
  <display-name>Just an Example</display-name>
  ... remaining elements omitted here ...
</application>
```

**However currently the application Element looks like this:**
```xml
<?xml version="1.0"?>
<application xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="10">
  <application-name>example</application-name>
  <display-name>Just an Example</display-name>
  ... remaining elements omitted here ...
</application>
```

- **xmlns is an empty string** for Versions 8, 9 and 10
- **xsi:schemaLocation is missing** for Versions 8, 9 and 10

### Context (optional)

The latest XSD Schemas can be found at https://jakarta.ee/xml/ns/jakartaee/

https://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/application_8.xsd (JAVA EE 8)
```xml
<application xmlns="http://xmlns.jcp.org/xml/ns/javaee"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee 
      	http://xmlns.jcp.org/xml/ns/javaee/application_8.xsd"
      version="8">
      ...
</application>
```
---
https://jakarta.ee/xml/ns/jakartaee/application_9.xsd (Jakarta EE 9)
```xml
<application xmlns="https://jakarta.ee/xml/ns/jakartaee"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee 
      	https://jakarta.ee/xml/ns/jakartaee/application_9.xsd"
      version="9">
      ...
</application>
```
---
https://jakarta.ee/xml/ns/jakartaee/application_10.xsd (Jakarta EE 10)
```xml
<application xmlns="https://jakarta.ee/xml/ns/jakartaee"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee 
      	https://jakarta.ee/xml/ns/jakartaee/application_10.xsd"
      version="10">
      ...
</application>
```

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

***

Thank you for the pull request!

**Comment by eskatos** [comment]
Thank you for the pull-request @p-schneider, this will be in Gradle 8.5.
