### ISSUE TITLE
Provide a build option to trade exhaustive checks for speed (e.g. rerun failed tests only)

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2644]
### Expected Behavior
`gradle :test --failed` would inspect the previous execution and filter by any test classes that failed.

If the previous test execution results do not exist or cannot be read, no filter is applied and we run all tests.

Demo: https://asciinema.org/a/alielycyjjkst2niborcey95w

### Current Behavior

This does not exist today, sadly.

### Context

Other build tools like Rake and SBT have a nice feature that allows one to re-run just failed tests. Some systems re-run the all tests if none have failed. 

This was spiked by @big-guy in #2036 and sadly died in discussion because we wanted to make it more generic. I believe that doing this much smaller amount of work (as opposed to generic `check --failed`) would do what 90% of users want and so I advocate for doing this.

**Comment by adammurdoch** [comment]
I don't think that discussion resulting in something bigger, just something more general.

**Comment by oehme** [comment]
As discussed on our meeting, we don't want to make it specific to test tasks. At the same time there is no need to to make it work for everything right away. We can introduce a build option (e.g. `--fast-feedback`) and then let the test task be the first that reacts to it.

**Comment by big-guy** [comment]
Related topic that this could evolve into: https://martinfowler.com/articles/rise-test-impact-analysis.html

**Comment by adammurdoch** [comment]
This isn't about trading off correctness, it's about narrowing the question that Gradle will answer so that it can give the answer more quickly. Gradle will (or should) still apply all the usual correctness constraints in answering the question.

**Comment by oehme** [comment]
Well, only rerunning failed tests for instance is not correct, my changes could have broken other tests that were green before. I'll change it to "so the user can trade corrrectness for speed". Gradle itself will of course answer the less rigid answer as correctly as usual.

**Comment by eriwen** [comment]
I'd like to suggest that @acourtneybrown pick this up as a very nice compliment after #1310

**Comment by eriwen** [comment]
Bummer that we deprioritized this. I thought this was very complementary to `--fail-fast` because one could run with `--fail-fast`, then `--failed-only` until passing, thus ensuring a tight development loop.

**Comment by oehme** [comment]
I don't see how that would work yet. Fail fast aborts on the first failure. Fast feedback would only rerun that single failed test. So you still wouldn't know about all the other things that might be broken. You would need to constantly alternate between the two. Better do a full test first and then fast feedback till all are fixed.

What do you mean by deprioritize? We just merged fail fast and are still ironing out its edges, so there really wasn't any time to design this yet.

**Comment by eriwen** [comment]
Well it went from "Sprint Backlog" to "Backlog", sir ;)

I suppose different projects and people will have different preferences on the use here, but I still think this'll be useful so I hope we can get to it, non-urgently.

**Comment by oehme** [comment]
Closing as we decided to go with always running failed tests first.
