### ISSUE TITLE
Classifiers & Version Catalogs lead to incomplete/broken Gradle module metadata

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#26468]
### Current Behavior

There is actually a bug in Gradle wrt classifiers and version catalogs.

The approach that is [recommended here](https://melix.github.io/blog/2021/03/version-catalogs-faq.html#_why_can_t_i_use_excludes_or_classifiers), like this one:
```
implementation(libs.orc.core) {
  artifact {
    classifier = 'nohive'
  }
}
```
leads to _broken_ published Gradle module metadata - consumers of the published Gradle module metadata encounter broken dependencies. I suspect that the recommended way to specify a different artifact is broken in the same way for consumers of published Gradle module metadata.

This ugly workaround however works:
```
implementation("${libs.orc.core.get().module}:${libs.versions.orc.get()}:nohive")
```

Another ugly workaround is to _not_ consume Gradle module metadata, [like this](https://github.com/projectnessie/nessie/blob/main/settings.gradle.kts#L46-L57).

See also:
* [Workaround in Apache Iceberg](https://github.com/apache/iceberg/pull/8588/)
* [IntelliJ issue](https://youtrack.jetbrains.com/issue/IDEA-327421/IJ-fails-to-import-Gradle-project-with-dependency-with-classifier)

/cc @melix

### Expected Behavior

Consumption of Gradle module metedata should work.

### Steps to Reproduce

see above

### Gradle version

8.3

**Comment by melix** [comment]
Please note that I left Gradle development more than 2 years ago, not sure mentioning me will help a lot :)

From what I read the issue is not with version catalogs, I would assume you'd get exactly the same result with a dependency declared using:

```
implementation("${libs.orc.core.get().module}:${libs.versions.orc.get()}) {
  artifact {
    classifier = 'nohive'
  }
}
```

but that's just a wild guess. I am however surprised that you'd get a different module metadata with the 2 notations :thinking:

**Comment by jbartok** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.
