### ISSUE TITLE
Upgrade Dokka/Dokkatoo to version 1.9, when fixed

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#26479]
Initially, we upgraded to Dokka 1.9/Dokkatoo 2.0.0 in this [PR](https://github.com/gradle/gradle/pull/26417).
Then we found out there is a [flaky bug in Dokka](https://github.com/Kotlin/dokka/issues/1599), the [fix for it](https://github.com/Kotlin/dokka/pull/3143) seems to have just missed the 1.9 release.
**We have reverted the upgrade** and have asked Jetbrains for a patch release. 
Even if they make one, Dokkatoo will need an upgrade too, before we can try bumping the version again.

**Comment by aSemy** [comment]
> Even if they make one, Dokkatoo will need an upgrade too,

Hopefully Dokkatoo won't need a separate release and you can just bump the Dokka version that Dokkatoo uses https://github.com/adamko-dev/dokkatoo/blob/1a73111312b347ac21598f514abfcaa4952078b2/modules/dokkatoo-plugin/src/main/kotlin/DokkatooExtension.kt#L122
