### ISSUE TITLE
Proxy authentication does not work for script plugins applied to init scripts

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2647]
Proxy authentication is configured using system properties, like `-Dhttp.proxyUser=foo -Dhttp.proxyPassword=bar`. These proxy settings are honoured for script plugins applied to `build.gradle` and to `settings.gradle`, but they are ignored when a script plugin is applied to an init script.

This problem exists because the system properties from the command line are not set on the process until after the init script is evaluated. In fact, it's a bit worse than this: because we cache the proxy settings on first use, as soon as any script plugin is applied to an init script, proxy authentication will fail for script plugins on `settings.gradle` and `build.gradle`.

This is not a new problem: prior to Gradle 4.2 we ignored proxy authentication config for _all_ script plugins. Now we honour it for script plugins applied to `build.gradle` and `settings.gradle`, but script plugins applied to `init.gradle` can break this.

**Comment by wheelerlaw** [comment]
@bigdaz As a workaround for this, you can set the `JAVA_TOOL_OPTIONS` environment variable, which will be picked up by the JVM no matter where it is run from (with a few exceptions). This is what I put at the end of my `/etc/environment` to get it to work with a proxy server:

    JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=<your-proxy-host> -Dhttp.proxyPort=<your-proxy-port> -Dhttps.proxyHost=<your-proxy-host> -Dhttps.proxyPort=<your-proxy-port>"

You can read more about `JAVA_TOOL_OPTIONS` [here](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html).

If you're especially curious, [here](http://cr.openjdk.java.net/~gbenson/zero-11-hotspot/hotspot/src/share/vm/runtime/arguments.cpp.html) is the OpenJDK source code for where `JAVA_TOOL_OPTIONS` is parsed.

**Comment by amp4045** [comment]
I know this an old closed ticket, but has a more formal solution been developed rather than JAVA_TOOL_OPTIONS?

**Comment by wheelerlaw** [comment]
@amp4045 It would appear that Gradle is dropping the ball on supporting enterprise networking.
