### ISSUE TITLE
native: changing the parentDir of a sharedLibraryLinkFile is not honored if different from the parentDir of the sharedLibraryFile

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle#2649]
Changing the parent directory of a sharedLibraryLinkFile is not honored when this parent directory is different from the parent of the sharedLibraryFile

### Expected Behavior
No error

### Current Behavior
```
 Task :linkMainDebugExecutable
LINK : fatal error LNK1104: cannot open file 'C:\Users\fandre\Documents\git\gradle\subprojects\docs\src\samples\native-binaries\cpp\lib\Pocohellod.lib'



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':linkMainDebugExecutable'.
> A build operation failed.
      Linker failed while linking maind.exe.
  See the complete log at: file:///C:/Users/fandre/Documents/git/gradle/subprojects/docs/src/samples/native-binaries/cpp/build/tmp/linkMainDebugExecutable/output.txt

```
### Context
I am trying to put all sharedLibraryFiles in a bin directory while putting all the corresponding sharedLibraryLinkFile in a lib directory
 
### Steps to Reproduce (for bugs)
Override the build.gradle in gradle\subprojects\docs\src\samples\native-binaries\cpp by the one in attachement and build the project.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/m3ndk5vg4tp4s#summary
[build.gradle.txt](https://github.com/gradle/gradle/files/1196383/build.gradle.txt)

**Comment by bmuschko** [comment]
@lacasseio Could you have a look?

**Comment by lacasseio** [comment]
Thanks for submitting this issue. It is effectively an overlook in term of functionality with regards to MSVC and MinGW. To work around this limitation, I suggest the following modification to the build script:

```
[...]
if (it instanceof SharedLibraryBinarySpec) {
    sharedLibraryFile = toBin(prefixByPoco(sharedLibraryFile))
    sharedLibraryLinkFile = toLib(prefixByPoco(sharedLibraryLinkFile))
							
    // WINDOWS ONLY
    linker.args "/implib:${sharedLibraryLinkFile}"  // For MSVC only
    // use the following for MinGW
    // linker.args "-Wl,--out-implib,${sharedLibraryLinkFile}"

    // This next part is simply to ensure the directory is created as the compiler (tested on MSVC only) won't create it
    def binary = it  // Simply to expose the binary in the `doFirst`
    tasks.withType(LinkSharedLibrary) {
        doFirst {
            binary.sharedLibraryLinkFile.parentFile.mkdirs()
        }
    }
} else if (...
```

**Comment by lacasseio** [comment]
This feature requires a bit more discussion as MSVC and MinGW provide linker flags to specify the output location of the import library but differ for other compilers in functionality. [This epic](https://github.com/gradle/gradle-native/issues/90) will track the solution for this issue. Until then, I'm closing this issue.
