### ISSUE TITLE
plugin-publish plugin does not handle dependency exclusions correctly

### ISSUE THREAD

**Issue by TheBoegl** [gradle/gradle#2650]
There seems to be a caching issue when applying a plugin with the plugins DSL, if the applied plugin depends on artifacts that have exclude statements. See TheBoegl/gradle-launch4j/issues/60 for such an example.

### Expected Behavior
 Gradle should honor these excluded artifacts.

For the given example it should exclude the abeille artifact:
`01:23:14.509 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] net.java.abeille:abeille is excluded from net.sf.launch4j:launch4j:3.11(runtime).`

### Current Behavior
Gradle tries to resolve the excluded artifacts.

For the given example it tries to resolve the abeille artifact and later fails with a 404-error because an excluded artifact jar is not in maven any more:
`01:16:45.300 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuilder] Selecting new module version net.java.abeille:abeille:3.0`

### Steps to Reproduce (for bugs)
Use an old cache. I can reproduce this issue by using a backup of the _metadata-23_ folder which I can upload if you like.

### Work around
Running `./gradlew jar --refresh-dependencies` fixes the _metadata-23_ cache files.
I've created full log files before and after issuing the above command: [issue60-full.zip](https://github.com/gradle/gradle/files/1197090/issue60-full.zip)

**Comment by oehme** [comment]
There is nothing special in terms of caching with regards to the plugin DSL. In the end it just downloads your POM them same way as if you used a `buildscript {}` block. So this must have been broken metadata in your local cache. 

Is there any chance that the plugin was published to two different locations with different metadata (e.g. to both bintray **and** the plugin portal)?

**Comment by TheBoegl** [comment]
I should have remembered that earlier: applying the plugin worked as expected though applying the plugin with the plugins DSL failed, which is why I opened this issue.

I think it is unlikely that the meta data broke on three of my build systems and on some of the plugin users at the same time. 
If my memory serves me well, I published the plugin to plugin portal and bintray one after the other without changing anything in the build. Anyway the erroneous artifact is not only excluded from my plugin but from the artifact that the plugin uses.

**Comment by oehme** [comment]
Can you please do the following check:

1. Create a sample using the `plugins` block
2. Run the build with an empty Gradle User Home `-g` option and see if it succeeds
3. Change the sample to use the `buildscript` block
4. Run it again with an empty user home and see if it succeeds.

If either of those fails, then the published metadata is broken.

**Comment by TheBoegl** [comment]
I stand corrected. The metadata is broken: the `<artifactId>*</artifactId>` entries are missing in the exclusions list, which results in the above mentioned error.
If I add this entry in the pom file in a local maven repo (and use it) the the build works.

Is this an issue in the `PomWriter` class of the plugin-publish plugin (com.gradle.plugin-publish) or am I supposed to exclude dependencies like `exclude(group: 'GROUP_ID', module: '*')` instead of `exclude(group: 'GROUP_ID')`?

**Comment by oehme** [comment]
Thanks for investigating! We should definitely fix the plugin publishing plugin then. In the meantime, if you can find a workaround that publishes the right pom, that would be great. Others might benefit from that until we fix the problem.

**Comment by TheBoegl** [comment]
The work around is to set the module to `module: '*'` instead of leaving it out.

**Comment by blindpirate** [comment]
@oehme A little curious, Could you please tell me where's the `plugin publishing plugin` code? I didn't find it in `gradle/gradle` repository.

**Comment by oehme** [comment]
It's in a private repo @melix will show you next week.

**Comment by blindpirate** [comment]
@oehme Thanks!
