### ISSUE TITLE
8.4-RC1: Release notes: Confusing sample of the configuration api

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#26504]
### Issue type

Wrong or misleading information

### Problem description

The sample of the old configuration api only sets the non-default properties to false. This code is correct, but confusing due the similar property names. Instead, also add the default value to highlight the new improved api:

```
configurations {
    create("implementation") { 
        isCanBeConsumed = false
        isCanBeResolved = false
        isCanBeDeclared = true
    }
    create("runtimeClasspath") { 
        isCanBeConsumed = false
        isCanBeResolved = true
        isCanBeDeclared = false
        extendsFrom(configurations["implementation"]) 
    }
    create("runtimeElements") { 
        isCanBeConsumed = true
        isCanBeResolved = false
        isCanBeDeclared = false
        extendsFrom(configurations["implementation"]) 
    }
}
```

Also, please, change the order of the new usage and use the same names:
```
configurations { 
    dependencyScope("implementation")
    resolvable("runtimeClasspath") {
        extendsFrom(configurations["apiElements"]) 
    }
    consumable("runtimeElements") { 
        extendsFrom(configurations["implementation"]) 
    }
}
```

### Context (optional)

I was unable to create a PR because I don't know where the release notes are stored, the master branch contains the new release notes of 8.5

### Page with the problem

https://docs.gradle.org/8.4-rc-1/release-notes.html

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

We should add an in-line comment on the declarations that match the default, to clary that they match the default:
`isCanBeDeclared = true // this is the default`

**Comment by jvandort** [comment]
@hfhbd PTAL https://github.com/gradle/gradle/pull/26524
