### ISSUE TITLE
Show transforms of external dependencies in build scans

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#26514]
### Expected Behavior

Build scans should provide detailed information about transforms, just like it does for tasks. Currently, only transforms on project dependencies are shown. Transforms on external dependencies should be shown as well.

### Context

In https://issuetracker.google.com/298888646, the user reported that the `Fingerprinting inputs` step of `:app:mergeExtDexDebug` takes an unusually long time to run. Upon investigation, we've found that this step consists mostly of running the transforms to construct the inputs to that task. It would be nice if the transforms were shown separately from the `Fingerprinting inputs` step in build scans.

**Comment by wolfs** [comment]
With [Develocity 2024.1](https://gradle.com/develocity/releases/2023.4#insights-into-gradles-artifact-transform-executions) artifact tranforms of external dependencies now can be observed in build scans.

**Comment by hungvietnguyen** [comment]
Woohoo, thanks Stefan!!
