### ISSUE TITLE
Expose `BuildLayout` root dir from `ProjectLayout`

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#26521]
@adammurdoch wrote:

Could we also either add ProjectLayout.getRootDirectory() or ProjectLayout.getBuildLayout()? Locating a file/directory relative to the root directory from project build logic or tasks is a very common use case that is easy to break in CC and IP. For example, when redirecting the build options or locating some shared configuration file.

[The BuildLayout implementation...] should not need a `Settings` instance. Its root directory should be the root directory of the build, taken from the `BuildLocations` rather than the mutable project directory of the root project.

[...]

[NB: ] It looks like `Settings.getRootDir()` is doing the wrong thing, but I would just leave that unchanged and we can deprecate it later.

_Originally posted by @adammurdoch in https://github.com/gradle/gradle/pull/26492#discussion_r1336430157_

**Comment by asodja** [comment]
Probably related: https://github.com/gradle/gradle/issues/13654

**Comment by alllex** [comment]
Whatever solution we choose here, I think we should make IP-safe from the start

**Comment by bamboo** [comment]
Superseded by #13654

**Comment by bamboo** [comment]
Superseded by https://github.com/gradle/gradle/issues/13654
