### ISSUE TITLE
empty coverage for buildType "debug"

### ISSUE THREAD

**Issue by Smatek** [gradle/gradle#26537]
### Current Behavior

With gradle 8.1.1 running task **createDebugUnitTestCoverageReport** results in correct coverage
![image](https://github.com/gradle/gradle/assets/13534663/f471881e-6814-4c74-aeb6-8da4125d8227)
However with gradle 8.2 or 8.3 running the same task results in empty coverage
![image](https://github.com/gradle/gradle/assets/13534663/2c3221d3-5f13-40f3-aab5-983eda17cfb4)

When running similar tasks for other buildTypes **createReleaseUnitTestCoverageReport** and **createSuperBuildTypeUnitTestCoverageReport** coverage is correct with all gradles 8.1.1 - 8.3

### Expected Behavior

Correct coverage for **debug** buildType

### Steps to Reproduce

Full repository is here https://github.com/Smatek/JacocoGradleBugSample
To reproduce this, change gradle version in **gradle-wrapper.properties**

### Gradle version

8.1.1 - 8.3

### Your Environment (optional)

Android Studio Giraffe | 2022.3.1 Patch 1
Tried on Mac and Windows

**Comment by jbartok** [comment]
Have you checked the [Android tracker](https://source.android.com/docs/setup/contribute/report-bugs) for this issue already being reported? 
Have you checked if the problem persists with different versions of the Android plugin?

**Comment by Smatek** [comment]
Updating AGP to 8.2.0-beta06 worked. Thanks for suggestion!
