### ISSUE TITLE
Support deleting windows files with read-only attribute

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#26539]
### Expected Behavior

Gradle `clean` task should be able to delete windows files with read-only attribute. 

### Current Behavior (optional)

Currently, Gradle `clean` task can't delete windows files with read-only attribute.

### Context

In Gradle there're some `version-control` integration tests that generate read-only git blob files, like this:

```
tcagent1@WINDOWS238 C:\tcagent1\work\f63322e10dd6b396>attrib C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.pack
A    R               C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAn
droidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.pack
```

The `R` attribute means it's a windows read-only file. They can be deleted by `del /f` but not `del` or `./gradlew clean`:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':performance:clean'.
java.io.IOException: Unable to delete directory 'C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.idx
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack\pack-a88a85c0b3bd27ed028ec4b02524810d7687f74a.pack
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects\pack
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git\objects
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild\.git
  - C:\tcagent1\work\f63322e10dd6b396\subprojects\performance\build\santaTrackerAndroidBuild
```

We need to call `File.setAccessible()` first: https://stackoverflow.com/questions/2877106/java-unmark-file-is-read-only

We have to workaround this issue by https://github.com/gradle/gradle/pull/26523

**Comment by jp196** [comment]
My Gradle build creates a read-only EXE file.  

In Gradle 8.3 and earlier, "gradle clean" deleted the file without issue.   In 8.4 and 8.5, it always fails with an IOException. 

So, something changed in Gradle 8.4.   Whether Gradle developers would consider this a "bug" or a "feature", I don't know, but it is a breaking change for me that will require a workaround.

Running on Windows 11, Java 17.0.7

**Comment by jp196** [comment]
This workaround worked for my situation:

```
// Workaround for an issue that started appearing in Gradle 8.4 where Gradle refused to delete a read only file,
// even though it worked in Gradle 8.3 and earlier.
task beforeClean(type: Exec) {
   commandLine 'cmd', '/c', "attrib -r build/jpackage/${appName}/${appName}.exe"         
}

clean.dependsOn(beforeClean)

```

**Comment by chschu** [comment]
Deleting read-only files worked before https://github.com/gradle/gradle/pull/26011.

The `File.delete()` previously used will delete a file even if it is read-only files, while `Files.deleteIfExists(Path)` throws a `java.nio.file.AccessDeniedException` in that case.

**Comment by ov7a** [comment]
Thanks, @chschu for pointing out the PR that broke the build!

**Comment by ov7a** [comment]
However, there is an issue with more discussion on the same topic:
* https://github.com/gradle/gradle/issues/26912
So closing this as a duplicate.
