### ISSUE TITLE
Deprecate AbstractOptions#define and AbstractOptions

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#26550]
### Issue type

Deprecation

### Problem description

`AbstractOptions#define` presents a non-type-safe API and relies on reflection. We should deprecate (and subsequently remove) this method, and all other methods that depend on it, including `fork` and `debug` in `GroovyCompileOptions` and `CompileOptions`. 

As a result, we should also deprecate the `AbstractOptions` type for removal

**Comment by lptr** [comment]
We should also deprecate `CompileOptions.debug(Map)` and `fork(Map)` and anything else that calls `define()`.

**Comment by lptr** [comment]
Based on bytecode analysis out of the top 100 plugins on plugin portal none reference `org.gradle.api.tasks.compile.AbstractOptions` statically. :tada:
