### ISSUE TITLE
configuring javahome with org.gradle.java.home

### ISSUE THREAD

**Issue by zeimao77** [gradle/gradle#26566]
### Expected Behavior

Can the runtime environment of Gradle be separated from the compilation and execution environment of the program

When using `org.gradle.java.home` configuration, an error will be directly reported when the execution environment of gradle is incompatible with the project jdk;

### Current Behavior (optional)

And the configuration of org.gradle.java.home seems to be related to caching, which can lead to success and failure

### Context

Old version gradle cannot compile jdk21

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Probably what you need is Java toolchains: https://docs.gradle.org/current/userguide/toolchains.html
If we misunderstood your need, let us know and we can reopen the issue.
