### ISSUE TITLE
Can't Build by JDK 21 on Gradle 8.4

### ISSUE THREAD

**Issue by hm9245** [gradle/gradle#26589]
### Current Behavior

Welcome to Gradle 8.4-20230928234018+0000!

Here are the highlights of this release:
 - Compiling and testing with Java 21
 - Faster Java compilation on Windows
 - Role focused dependency configurations creation

Starting a Gradle Daemon, 3 incompatible Daemons could not be reused, use --status for details

> Configure project :aidl
WARNING: The option setting 'android.enableParallelJsonGen=true' is experimental.
The current default is 'false'.
WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (8.1.0) was tested up to compileSdk = 33 (and compileSdkPreview = "UpsideDownCakePrivacySandbox").

You are strongly encouraged to update your project to use a newer
Android Gradle plugin that has been tested with compileSdk = 34.

If you are already using the latest version of the Android Gradle plugin,
you may need to wait until a newer version with support for compileSdk = 34 is available.

To suppress this warning, add/update
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':server:compileDebugKotlin'.
> Unknown Kotlin JVM target: 21

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

### Expected Behavior

Build Successful

### Steps to Reproduce

./gradlew :manager:assembleDebug

### Gradle version

8.4-20230928234018+0000

**Comment by Desoroxxx** [comment]
Same here

**Comment by AlexKovynev** [comment]
it is not a bug. Kotlin still not support JDK 21

**Comment by hm9245** [comment]
> it is not a bug. Kotlin still not support JDK 21

Okey,I know, thanks

**Comment by artemptushkin** [comment]
See https://github.com/gradle/gradle/issues/25574#issuecomment-1761314551

**Comment by vijaygopalbalasa** [comment]
Hi, you can check out this guide [https://androidstrike.com/fix-we-recommend-using-a-newer-android-gradle-plugin-to-use-compilesdk-34/](https://androidstrike.com/fix-we-recommend-using-a-newer-android-gradle-plugin-to-use-compilesdk-34/)

**Comment by Kreijstal** [comment]
8.7 still not java 21?

**Comment by Thelixist** [comment]
I'm not sure if this has been solved yet, But I just had this issue today and came across this post.

I resolved my issue by changing the Gradle JVM to Amazon Corretto version 21.0.2 and was able to compile with minimal to no errors.
