### ISSUE TITLE
add --java-version parameter to gradle init task

### ISSUE THREAD

**Issue by sombriks** [gradle/gradle#26598]
### Expected Behavior

```bash
gradle init \
  --type java-application \
  --dsl groovy \
  --test-framework junit-jupiter \
  --package sample.structure \
  --project-name my-gradle-project  \
  --no-split-project  \
  --java-version 17
```

### Context

the proposed command line presents us an error since the `--java-version` parameter does not exists.

when removed it ends up falling into the interactive mode where we can provide a value for java version.

my need (and maybe others as well) is to provision the new project without any interactive mode.

**Comment by jbartok** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by wkoyama** [comment]
> ### Expected Behavior
> ```shell
> gradle init \
>   --type java-application \
>   --dsl groovy \
>   --test-framework junit-jupiter \
>   --package sample.structure \
>   --project-name my-gradle-project  \
>   --no-split-project  \
>   --java-version 17
> ```
> 
> ### Current Behavior (optional)
> _No response_
> 
> ### Context
> the proposed command line presents us an error since the `--java-version` parameter does not exists.
> 
> when removed it ends up falling into the interactive mode where we can provide a value for java version.
> 
> my need (and maybe others as well) is to provision the new project without any interactive mode.

A necessary issue item. Thanks

**Comment by nfonrose** [comment]
There seem to be an issue with the `--java-version` option. It is taken into account by the `gradle init` task **BUT** gradle still enters the interactive mode and ask for the Java version anyway (which defeats the purpose of this option).

Here is how to reproduce the issue. Execute:
```bash
mkdir checkGradleJavaVersionOption
cd checkGradleJavaVersionOption
sdk use java 11.0.13-zulu
sdk use gradle 8.5
gradle init --type java-application \
  --dsl kotlin \
  --test-framework junit-jupiter \
  --package com.teevity.sandbox.gradle \         
  --project-name tee-sandbox-gradle  \
  --no-split-project  \
  --java-version 17
```

and you get:

```
Using java version 11.0.13-zulu in this shell.
Using gradle version 8.5 in this shell.
Enter target version of Java (min. 7) (default: 11):                                                                                                                                                                                                                                           
```

If you Ctrl+C at this point (without answering the question), you can see that the `build.gradle` which has been generated (even through we have Ctrl+Ced) contains the specified version. So it at least partially works:
  - Using `--java-version 11` leads to
```
cat ./app/build.gradle.kts | grep languageVersion.set
        languageVersion.set(JavaLanguageVersion.of(11))
```
  - Using `--java-version 17` leads to
```
cat ./app/build.gradle.kts | grep languageVersion.set
        languageVersion.set(JavaLanguageVersion.of(17))
```

I gave a look at the code changes in
https://github.com/sombriks/gradle/commit/ebf6a30bf9cd51418174caddbfccd121146ac27d#diff-295a5e54438bdcc210e645ee1b3f5815aa006bd78ca332072582bc29d10fa669 but couldn't the source of the problem.

**Comment by nfonrose** [comment]
> There seem to be an issue with the `--java-version` option. It is taken into account by the `gradle init` task **BUT** gradle still enters the interactive mode and ask for the Java version anyway (which defeats the purpose of this option).
> 
> Here is how to reproduce the issue. Execute:
> 
> ```shell
> mkdir checkGradleJavaVersionOption
> cd checkGradleJavaVersionOption
> sdk use java 11.0.13-zulu
> sdk use gradle 8.5
> gradle init --type java-application \
>   --dsl kotlin \
>   --test-framework junit-jupiter \
>   --package com.teevity.sandbox.gradle \         
>   --project-name tee-sandbox-gradle  \
>   --no-split-project  \
>   --java-version 17
> ```
> 
> and you get:
> 
> ```
> Using java version 11.0.13-zulu in this shell.
> Using gradle version 8.5 in this shell.
> Enter target version of Java (min. 7) (default: 11):                                                                                                                                                                                                                                           
> ```
> 
> If you Ctrl+C at this point (without answering the question), you can see that the `build.gradle` which has been generated (even through we have Ctrl+Ced) contains the specified version. So it at least partially works:
> 
> * Using `--java-version 11` leads to
> 
> ```
> cat ./app/build.gradle.kts | grep languageVersion.set
>         languageVersion.set(JavaLanguageVersion.of(11))
> ```
> 
>  * Using `--java-version 17` leads to
> 
> ```
> cat ./app/build.gradle.kts | grep languageVersion.set
>         languageVersion.set(JavaLanguageVersion.of(17))
> ```
> 
> I gave a look at the code changes in [sombriks@ebf6a30#diff-295a5e54438bdcc210e645ee1b3f5815aa006bd78ca332072582bc29d10fa669](https://github.com/sombriks/gradle/commit/ebf6a30bf9cd51418174caddbfccd121146ac27d#diff-295a5e54438bdcc210e645ee1b3f5815aa006bd78ca332072582bc29d10fa669) but couldn't the source of the problem.

Do prefer me to create an issue with this description?

**Comment by sombriks** [comment]
Hello @nfonrose please link the new issue here, it either shows a fragility in the current testsuite or somethng else crashed during the merge window time. When i have the time i'll investigate 👍🏽
