### ISSUE TITLE
Easy to fall into trap: Using a Property<ByteArray> in a custom gradle type

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#26596]
### Current Behavior

I tried to do the following:

```
interface MyWorkParams : WorkParameters {
   val byteArray: Property<ByteArray>
}
```

and got the following error:
```
Caused by: java.lang.ClassCastException: class [B cannot be cast to class [Ljava.lang.Object; ([B and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
```

### Expected Behavior

In Kotlin, the concept of primitives doesn't exist on the surface. And in the [gradle docs for custom types](https://docs.gradle.org/current/userguide/custom_gradle_types.html), searching for "array" or "primitive" or "bytearray" comes up with nothing. And the error message itself is very unfriendly to less experienced developers who have no idea what `[B` is. The following could all be helpful for this issue:
1. A better exception message. Catch the class cast exception, and throw a new exception with a more helpful message for Gradle users.
2. Clearer documentation. What should developers do when they want to use a type such as ByteArray in a custom gradle type?
3. Support ByteArray and similar types (arrays, primitives) directly. It seems like Gradle sees an Array and expects `[Ljava.lang.Object`. Is it possible it could be a bit more smart, and be prepared to see a `[B`?
4. If neccesarry, provide an ArrayProperty or ByteArrayProperty or PrimitveArrayProperty or PrimitiveProperty or whatever is neccesarry to support this. Though it would be ideal if it just worked inside of Property.

### Steps to Reproduce

The code above should be sufficient.

### Gradle version

8.3

**Comment by jbartok** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.
