### ISSUE TITLE
New Configuration shortcuts: Add RegisteringDomainObjectDelegateProvider/RegisteringDomainObjectDelegateProviderWithAction overload

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#26601]
### Expected Behavior

```kotlin
val myConfig: NamedDomainObjectProvider<ConsumableConfiguration> by configurations.consumable {
    
}

val myConfig: NamedDomainObjectProvider<ConsumableConfiguration> by configurations.consumable

// similar to 
val myConfig: NamedDomainObjectProvider<Configuration> by configurations.registering {

}
val myConfig: NamedDomainObjectProvider<Configuration> by configurations.registering
```

### Current Behavior (optional)

```kotlin
val myConfig: NamedDomainObjectProvider<ConsumableConfiguration> by configurations.consumable("myConfig") {
    
}
val myConfig: NamedDomainObjectProvider<ConsumableConfiguration> by configurations.consumable("myConfig")
```

### Context

I currently use the `configurations.registering` provider to only specify the name of the configuration once by using the variable name. The new api does not have this overload, so during migration to the new configurations types, I need to specify the configuration names twice.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

Thank you for providing a PR with a suggestion for implementation.

**Comment by big-guy** [comment]
https://github.com/gradle/gradle/pull/26611#issuecomment-1819490646
