### ISSUE TITLE
8.4 - New configuration shortcut: DependencyScopeConfiguration.invoke isn't available 

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#26602]
### Current Behavior

```kotlin
val c: NamedDomainObjectProvider<DependencyScopeConfiguration> by configurations.dependencyScope("c") {

}
dependencies {
    c("foo:foo:1") // Type mismatch. Required: TypeVariable(T).() → Unit, Found: String
}
```

### Expected Behavior

```kotlin
val c: NamedDomainObjectProvider<DependencyScopeConfiguration> by configurations.dependencyScope("c") {

}
dependencies {
    c("foo:foo:1") // no error
}
```

### Context (optional)

https://github.com/gradle/gradle/issues/24503

Underlaying issue is the Provider interface, which is written in Java, so it does not support Kotlin `out T`. To support the `invoke` operator, adding `out Configuration` to the introduced api should be enough.
AFAIK this is backward compatible.

### Steps to Reproduce

[gradle-issue-reproducer-kotlin-dsl.zip](https://github.com/gradle/gradle/files/12780346/gradle-issue-reproducer-kotlin-dsl.zip)

### Gradle version

8.4-RC-3

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

Thank you for providing a PR with a fix.
