### ISSUE TITLE
"published-with-gradle-metadata" missing from cpp-library pom file

### ISSUE THREAD

**Issue by matthewvon** [gradle/gradle#26606]
### Current Behavior

This is the pom file currently generated:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.facebook</groupId>
  <artifactId>rocksdb</artifactId>
  <version>6.20.3e-ubuntu-amd64</version>
  <packaging>pom</packaging>
</project>
```

### Expected Behavior

This is the pom file generated by 6.0.1:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.facebook</groupId>
  <artifactId>rocksdb</artifactId>
  <version>6.20.3e-centos-amd64</version>
  <packaging>pom</packaging>
</project>
```

### Context (optional)

We are upgrading from 6.0.1 to 8.x for multiple reasons.  One of the reason is to get Apple M1 native builds of our cpp-library projects.  But we only get M1 with 8.x, and now find 8.x cannot publish correctly.

The lack of the "do_not_remove: published-with-gradle-metadata" appears to prevent gradle from properly interpreting the c++ libraries.

### Steps to Reproduce

Below is one of our project files.  It will produce the erroneous pom file for "snappy" and correct pom file for "snappy_debug" and "snappy_release".  This project intentionally uses the build method of the third-party authors so that we do not have to convert their build method to gradle method on every third-party release.  Yes, it is not too cumbersome for snappy.  But conversion and maintenance for rocksdb and AWS S3 builds are a nightmare.

```
// Copyright (c) 2010 - present, Stardog Union. <http://www.stardog.com>
// For more information about licensing and copyright of this software, please contact
// sales@stardog.com or visit http://stardog.com


plugins {
    id 'maven-publish'
    id 'base'
    id 'cpp-library'
}

group = 'com.google'

// fix BUILD vs build confusion with java / mac
buildDir = "$projectDir/build_dir"

library {
    privateHeaders.from file('.')
    publicHeaders.from file("$buildDir/include")
    linkage = [Linkage.STATIC]
}

version = "1.1.8-" + OS + "-" + System.properties.get('os.arch')

/**
 * Step 1: Retrieve and unzip source files
 */
task downloadSource {
	DownloadFile( "https://github.com/stardog-union/snappy/archive/refs/tags/stardog-develop-1.2.zip",
				  buildDir, "stardog-develop-1.2.zip")
	outputs.file("$buildDir/stardog-develop-1.2.zip")
}

task unZipSource(type:Copy) {
    from(zipTree("$buildDir/stardog-develop-1.2.zip")) {
        eachFile { fcd ->
            fcd.relativePath = new RelativePath(true, fcd.relativePath.segments.drop(1))
        }
    }
    destinationDir projectDir
	outputs.dir(new File("$projectDir"))
	dependsOn downloadSource
}

/**
 * Step 2: Build the Release version
 */
// cmake in /usr/bin on linux, but /usr/local/bin on mac
task cmakeGenericLinuxRelease(type:Exec) {
    workingDir = "${projectDir}"
    environment("CXXFLAGS","-fPIC")

    commandLine 'cmake', "-CStardogCache.txt", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_INSTALL_LIBDIR=lib/main/release", "-B.", "-S."

	dependsOn unZipSource
}

task makeGenericLinuxRelease(type:Exec) {
    workingDir = "${projectDir}"

    commandLine 'cmake', '--build', '.', '--target', 'install'

	outputs.file(new File("$buildDir/lib/main/release", "libsnappy.a"))

	dependsOn cmakeGenericLinuxRelease
}

/**
 * Step 3: Build again, but this time the Debug version
 */
task cmakeGenericLinuxDebug(type:Exec) {
    workingDir = "${projectDir}"
    environment("CXXFLAGS","-fPIC")

    commandLine 'cmake', "-CStardogCache.txt", "-DCMAKE_BUILD_TYPE=Debug", "-DCMAKE_INSTALL_LIBDIR=lib/main/debug", "-B.", "-S."

	dependsOn makeGenericLinuxRelease
}

task makeGenericLinuxDebug(type:Exec) {
    workingDir = "${projectDir}"

    commandLine 'cmake', '--build', '.', '--target', 'install'

	outputs.file(new File("$buildDir/lib/main/debug", "libsnappy.a"))

	dependsOn cmakeGenericLinuxDebug
}


publishing {
    publications {
        PrebuiltLib(MavenPublication) {
            artifactId "snappy"
        }
    }

	repositories {
		maven {
			url buildRepositoryUrl
			name "BuildLibUpload"
			credentials {
				username artifactoryUsername
				password artifactoryPassword
			}
		}
	}
}


tasks.whenTaskAdded {task ->
	// clean up steps required for gradle before version 8.3
    if(task.name.contains("compileDebugCpp")) {
        task.enabled = false
		dependsOn "makeGenericLinuxDebug"
		inputs.files(makeGenericLinuxDebug.outputs.getFiles())
    }
    if(task.name.contains("createDebug")) {
        task.enabled = false
		dependsOn "makeGenericLinuxDebug"
		inputs.files(makeGenericLinuxDebug.outputs.getFiles())
    }

    if(task.name.contains("compileReleaseCpp")) {
        task.enabled = false
		dependsOn "makeGenericLinuxRelease"
		inputs.files(makeGenericLinuxRelease.outputs.getFiles())
	}
    if(task.name.contains("createRelease")) {
        task.enabled = false
		dependsOn "makeGenericLinuxRelease"
		inputs.files(makeGenericLinuxRelease.outputs.getFiles())
    }

	// clean up steps required for gradle 8.3
    if(task.name.contains("publishPrebuiltLib")) {
		dependsOn makeGenericLinuxDebug
	}
    if(task.name.contains("publishMainDebug")) {
		inputs.files(makeGenericLinuxDebug.outputs.getFiles())
		dependsOn makeGenericLinuxDebug
	}
    if(task.name.contains("publishMainRelease")) {
		inputs.files(makeGenericLinuxRelease.outputs.getFiles())
		dependsOn makeGenericLinuxRelease
	}
    if(task.name.contains("generateMetadataFileForMainDebug")) {
		inputs.files(makeGenericLinuxDebug.outputs.getFiles())
		dependsOn makeGenericLinuxDebug
	}
    if(task.name.contains("generateMetadataFileForMainRelease")) {
		inputs.files(makeGenericLinuxRelease.outputs.getFiles())
		dependsOn makeGenericLinuxRelease
	}
    if(task.name.contains("cppHeaders")) {
		dependsOn makeGenericLinuxDebug
		inputs.dir("$buildDir/include")
	}
}

// fix up internal tasks added by maven-publish & cpp-library in gradle 8.3
publishPrebuiltLibPublicationToBuildLibUploadRepository.dependsOn unZipSource

assemble.dependsOn "makeGenericLinuxDebug"

```
### Gradle version

8.3

### Gradle version that used to work

6.0.1

### Your Environment (optional)

processor	: 31
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 1201.547
cache size	: 20480 KB
physical id	: 1
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 47
initial apicid	: 47
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5210.28
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

mmaszewski@stardog2:~$ cat /proc/version 
Linux version 5.10.0-11-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.92-1 (2022-01-18)

mmaszewski@stardog2:~$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)

mmaszewski@stardog2:~/stardog$ ./gradlew -version

------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------

Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.18 (Debian 11.0.18+10-post-Debian-1deb11u1)
OS:           Linux 5.10.0-11-amd64 amd64

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

****

Could you provide us an isolated and complete reproducer, please? Could you try other Gradle versions and find out with which version of Gradle the observed behavior starts occurring?

**Comment by matthewvon** [comment]
You can leave this bug open, or close it.  I am moving on.

**Comment by matthewvon** [comment]
Add this settings.gradle file to the build.gradle earlier in the ticket to reproduce problem via "./gradlew publish"

```/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.0.1/userguide/multi_project_builds.html
 */

rootProject.name = 'snappy'
```

**Comment by matthewvon** [comment]
One last note:  it appears that the maven-publish and/or cpp-library plugin creates several publishing tasks that assume a MavenPublication object named "main".  The problems go away if build.gradle simply uses that name as "main(MavenPublication)".

**Comment by ov7a** [comment]
Ok! Closing this
