### ISSUE TITLE
Problem when the locale is set to Turkish.

### ISSUE THREAD

**Issue by karsibali** [gradle/gradle#2661]
gradle fails to work when the locale is set to Turkish. It is probably due to the well know Turkish "i" to "I" conversion problem.  The build.gradle file is as follows:
```
apply plugin: "java"
apply plugin: "eclipse"
apply plugin: "idea"

repositories {
  mavenCentral()
}

dependencies {
  testCompile "junit:junit:4.12"
}

test {
  testLogging {
    exceptionFormat = 'full'
    events = ["passed", "failed", "skipped"]
  }
}
```
When the gradle is run with the above build file in an environment where the locale is set to "tr_TR.utf-8" it fails with the following error:
```
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sarslan/exercism/java/hello-world/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'hello-world'.
> No enum constant org.gradle.api.tasks.testing.logging.TestLogEvent.FAİLED
```
As it can be seen from the last line the "failed" event in the build file is converted to "FAİLED" with the capital "İ" instead of "FAILED". This is due to the Turkish locale setting. 

### Expected Behavior

Since the word "failed" is an English word, it should be converted to uppercase using the English locale instead of using the system locale, which can be something else as in this case, where it is "Turkish". 
So, instead of using the system locale, use the English locale while converting the word "failed" or any other English words to uppercase.

### Current Behavior

While converting the words in the gradle build file to uppercase, gradle uses system locale. The system locale can be set to a language other than English. Trying to convert an English word to uppercase using a non-English locale results in unwanted behavior as in this case, where "failed" is converted to uppercase as "FAİLED" instead of "FAILED".

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Can you please provide a reproducible example project? As far as I remember these locale issues were fixed in recent Gradle versions.

**Comment by karsibali** [comment]
I came across this issue while I was trying the exercism.io java exercises. This was the first time I used gradle. Normally I do not use it. But the exercism.io java exercises are using it. Anyway even the most basic "Hello world" project failed due to this problem. It works correctly when I change my locale to en_US. But it fails when it is tr_TR.utf-8
I don't know how to provide that project here? But as I said you can download it from exercism.io web site. The project fails to work if you set your locale to Turkish (tr_TR.utf-8). But it works correctly if it is set to English. As I tried to explain above gradle thinks that "failed" word in the gradle build file is Turkish since the locale is Turkish. Because of that, it changes the word "failed" to uppercase using the Turkish locale settings. The word "failed" is correctly converted to uppercase as "FAİLED". But there is no enum constant 
`org.gradle.api.tasks.testing.logging.TestLogEvent.FAİLED`. This is due to the capital letter "İ" in the word "FAİLED". It should have been converted to uppercase using English locale, in which case it would be converted to uppercase correctly as "FAILED".
I tried to clarify the problem as good as I can.

**Comment by lacasseio** [comment]
@oehme We had an issue raised regarding a similar bug, but we only fixed it for a specific case. The following issue was opened to track this kind of error and have a more general fix in the code base: https://github.com/gradle/gradle/issues/1506. Note that it can be generalized to more than just `toLowerCase`.
