### ISSUE TITLE
8.4 – Test task that filters tests by JUnit 5 tag annotation emits deprecation

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#26623]
### Current Behavior

If I configure a custom test task to split up tests into categories like this...

```
tasks.register<Test>("testSlow") {
    testClassesDirs = sourceSets.test.get().output.classesDirs
    classpath = sourceSets.test.get().runtimeClasspath
    useJUnitPlatform {
        includeTags("slow")
    }
}
```

...I may get a deprecation warning (starting with Gradle 8.4):

```
No test executed. This behavior has been deprecated. This will fail with an error in Gradle 9.0. There are test sources present but no test was executed.
```

This situation is however by design, because I would like to register the additional test task(s) for all my subprojects. Some of them are not expected to contain tests of certain categories.

### Expected Behavior

There is no deprecation message emitted for the given setup or there is an option for the test task to say:
> Yes, I know that in some projects there are no tests and that is fine

### Context (optional)

A similar situation can be created using Gradle's native test filtering (filter by test name). For these cases, there seems to be a special handling in the code already. Maybe this can/should be extended to cover the other filtering mechanisms:

https://github.com/gradle/gradle/blob/master/platforms/software/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java#L535-L536

https://github.com/gradle/gradle/blob/master/platforms/software/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java#L555-L559

### Steps to Reproduce

- Get this sample: https://github.com/jjohannes/understanding-gradle/tree/main/21_Test_and_Code_Coverage_Reporting/my-project
- Run `gradle build --warning-mode=all `

### Gradle version

8.4 RC3

### Gradle version that used to work

8.3

### Build scan URL (optional)

https://scans.gradle.com/s/6in64hrajor2i

**Comment by eskatos** [comment]
In order to reproduce with the provided build you need to run `gradle --warning-mode=all testSlow`

**Comment by jjohannes** [comment]
Yes. I think it would be fine if you have to explicitly set `failOnNoMatchingTests=false`.
