### ISSUE TITLE
DSL docs for `Gradle` don't mention `beforeSettings`

### ISSUE THREAD

**Issue by tudortimi** [gradle/gradle#26659]
### Issue type

Wrong or misleading information

### Problem description

The DSL docs for [Gradle](https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html) don't mention `beforeSettings`. 

### Context (optional)

This is present in the API docs, but many people rely on the DSL docs. as seen [here](https://discuss.gradle.org/t/configure-plugin-repos-from-init-script-for-settings-plugins/42399/3?u=tudortimi).

### Page with the problem

https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by lkasso** [comment]
Fixed in https://github.com/gradle/gradle/pull/26830
