### ISSUE TITLE
After install JDK17 -Dorg.gradle.java.home can not work

### ISSUE THREAD

**Issue by JingLeiTalan** [gradle/gradle#26666]
### Current Behavior

Hello,
 
After I have switched to JDK 17, when i build one gralde project, i use ./gradlew build -Dorg.gradle.java.home="PATH_JAVA_8", this return un error: 

The newly created daemon process has a different context than expected.
It won't be possible to reconnect to this daemon. Context mismatch: 
Java home is different.

But when i was in Java 11, i set the path to JDK 8 and the build passed ...

### Expected Behavior

I want to specify the jdk path when build a gradle proejct

### Steps to Reproduce

Install java 17 and make it globally in the system
Run ./gradlew build -Dorg.gradle.java.home="PATH to java 8"

### Gradle version

5.4

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Please note that 5.4 is not maintained.
