### ISSUE TITLE
LinkageError with preview features

### ISSUE THREAD

**Issue by airsquared** [gradle/gradle#26664]
### Current Behavior

Using the gradle application plugin and the [unnamed variables](https://openjdk.org/jeps/443) preview feature of Java in source code produces a LinkageError at runtime. Using Java 21 and Gradle 8.4. Using the standard `javac` and `java` commands runs fine as expected. (you can see in the steps to reproduce)

Other preview features, like the more flexible main method, or string templates work fine and produce no errors anywhere. It's only this specific feature that produces an error at runtime.
```
> Task :run FAILED
Error: LinkageError occurred while loading main class error.Main
	java.lang.ClassFormatError: Illegal field name "" in class error/Main
```

### Expected Behavior

Should run with no errors, as `javac` and `java` do.

### Steps to Reproduce

https://github.com/airsquared/gradle_error
Make sure you hava Java 21 installed and run `./gradlew run`. You can also view the [GitHub Actions logs](https://github.com/airsquared/gradle_error/actions) of the repository.

### Gradle version

8.4

### Your Environment (optional)

Java 21 on all available GitHub Actions runners

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritised by them.

**Comment by octylFractal** [comment]
This is not a bug with Gradle, but with the preview feature you are enabling. The following commands reproduce this error without Gradle:
```sh
$ git clone https://github.com/airsquared/gradle_error
$ cd gradle_error/src/main/java
$ javac -g --release 21 --enable-preview error/Main.java
$ java --enable-preview -classpath . error.Main
Error: LinkageError occurred while loading main class error.Main
        java.lang.ClassFormatError: Illegal field name "" in class error/Main
```
Please report this to the [amber-dev mailing list](https://mail.openjdk.org/mailman/listinfo/amber-dev) instead.

**Comment by airsquared** [comment]
I see, thank you for checking. I'll report it there.

**Comment by airsquared** [comment]
This seems to only happen when the `-g` flag is passed to `javac`, is there a way to disable passing this flag?

**Comment by bdeneuter** [comment]
For reference: https://bugs.openjdk.org/browse/JDK-8313323
