### ISSUE TITLE
ivy repository URL String parsing broken with 8.3

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#26678]
### Current Behavior

Before gradle 8.3 we could pass our ivy repository url definition like this:

```
repositories {
    // Cloud builds bundle some beats
    ivy {
      name = 'beats'
      url "file://${buildDir}/artifacts/"
      patternLayout {
          artifact '/[organisation]/[module]-[revision]-[classifier].[ext]'
      }
    }
}
```

this is broken with Gradle 8.3 as we have a '+' in our CI project path (eg.: /usr/jenkins/elasticsearch+7.10/) as the plus sign gets interpreted as space. That should not be the case in file urls I think. 

### Expected Behavior

The plus sign in a file url is not interpreted as a special character or as an escape of a space sign.

### Context (optional)

Digging into the gradle sources I found a simple workaround by just passing a File object directly but I still think in general the change in behaviour was not intended and is wrong. 

### Steps to Reproduce

with a simple given build script:

```
repositories {
    // Cloud builds bundle some beats
    ivy {
      name = 'beats'
      url "/dev/jenkins/project+branch"
      println "repo url: $url"
      patternLayout {
          artifact '/[organisation]/[module]-[revision]-[classifier].[ext]'
      }
    }
}
```
if you run that with `./gradlew help` will print "repo url: /dev/jenkins/project branch"

### Gradle version

8.3

### Gradle version that used to work

8.2

### Your Environment (optional)

this issue is environment independant

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

**Comment by martinda** [comment]
> I found a simple workaround by just passing a File object directly

Can you please detail the workaround. Thanks in advance!
