### ISSUE TITLE
Using nebula.ospackage and upgrading from 7.6.3 to 8.0.2 fails

### ISSUE THREAD

**Issue by niclash** [gradle/gradle#26675]
### Current Behavior

System builds normally with 7.6.3.

Following the upgrade guide at https://gradle.org/whats-new/gradle-8/#how-to-upgrade.

When changing gradle-wrapper.properties to version 8.0.2, I get a strange build error;

```
> Configure project :
Inferred project: pipes, version: 1.1.0-dev.0.uncommitted+2e182de

FAILURE: Build failed with an exception.

* Where:
Build file '/home/niclas/dev/sensetif/pipes/apps/all/build.gradle' line: 73

* What went wrong:
A problem occurred evaluating project ':apps:all'.
> Could not create task ':apps:all:buildDeb'.
   > You can't map a property that does not exist: propertyName=version
```

And the `build.gradle:73` is the line ` buildDeb.dependsOn startScripts` and `startScripts` being

```
  startScripts {
    applicationName = "pipes-$projectName"
    defaultJvmOpts << '-XX:+UseG1GC'

    // Custom start scripts
    unixStartScriptGenerator.template = resources.text.fromFile("$projectDir/src/main/scripts/customUnixStartScript.txt")
  }
```

The `nebula` versions used was `15.3.1` for `nebula.release` and `8.5.6` for `nebula.ospackage` and upgrading those to `17.2.2` and `9.1.1` respectively doesn't change the output.
Likewise, gradle versions 8.1 and 8.4 has also been tested, with the same result.

If I remove 
```
//  buildDeb.dependsOn startScripts
//  assemble.dependsOn buildDeb
```
(must be both) then the build continues without any other errors, but of course I don't get any .deb files output.

### Expected Behavior

That the upgrade would be without problems and building of Debian package will be built as with 7.6.3

### Context (optional)

The immediare impact is low, as I can remain on Gradle 7.6.3 for quite a while and things work as expected. But eventually, I will be required to upgrade and this may become critical.

### Steps to Reproduce

It is a multi-project build that also depends on one other multi-project build and one simple project, so contact me if a build is required.

### Gradle version

8.x

### Build scan URL (optional)

https://gradle.com/s/rflfqnqwmfdqm for 8.0.2  and https://scans.gradle.com/s/l3usfjmedaacu for 7.6.3

### Your Environment (optional)

Linux Debian 12 (testing)

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***
It's unclear to us where
`You can't map a property that does not exist: propertyName=version`
is coming from without the reproducer.

**Comment by derhecht** [comment]
got the same issue. just using gradle 8.7 and e.g. nebula.deb 9.1.1 plugin and setup a debian task - would say this a plugin issue never the less.

**Comment by derhecht** [comment]
may this helps someone: we just changed plugin resolution/naming to get it working
plugins {
  old: id "nebula.deb" version "9.1.1"
  new: id "com.netflix.nebula.ospackage" version "11.8.1"
}
