### ISSUE TITLE
Lockfiles are not having transitive dependencies if using resolve method to write locks

### ISSUE THREAD

**Issue by jcraya** [gradle/gradle#26689]
### Current Behavior

Since we upgraded our project to Gradle 8.4 version we realized that content of gradle.lockfile differs if we run `gradle dependencies --write-locks` and if we run `resolveAndLockAll` task defined in here: https://docs.gradle.org/current/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution.
In the second case, transitive dependences are not included in the lockfile while when we use dependencies task, they are included.

### Expected Behavior

Both approaches of creating lock file should generate the same content.

### Context (optional)

That is happening only in Gradle 8.4, Gradle 8.3 was working fine for me.

### Steps to Reproduce

Create a project with `implementation` and `testImplementation` configurations and lock that project using  `gradle dependencies --write-locks` and `resolveAndLockAll` task and compare the results.

### Gradle version

8.4

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***
I could not replicate this issue with the Steps to reproduce listed above, so please take the time to create a reproducer as stated above.

**Comment by jcraya** [comment]
Hi @cobexer, thank you very much for taking the time to read the issue. I have been working these days in reproducing the issue with the reproducer template with no luck. On the other hand, it is clearly reproducible in my project with is internal and can't be shared externally unfortunately. I'll keep trying to reproduce the issue with the reproducer, but feel free to close this issue until then if I manage to get it.
