### ISSUE TITLE
Gradle daemon doesn't use correct java_home when run in a java process

### ISSUE THREAD

**Issue by JingLeiTalan** [gradle/gradle#26686]
### Current Behavior

When i run gradle in a java procss using ProcessBuilder, and set the environment like JAVA_HOME=path to jdk8, 
My java process is run in the jvm with a jdk17, but when i check the process: 

```
/home $ ps ax |grep java
  673 spring    0:04 /opt/java/openjdk/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx1536m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib/gradle-launcher-5.4.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.4.1
```

it doesn't use the correct JAVA_HOME that i set in the ProcessBuilder:
` processBuilder.environment().put("JAVA_HOME", "/usr/lib/jvm/java-8-openjdk");`

What's wrong with that ?

When i run the java ProcessBuilder in jdk11, everything it's okay... 

### Expected Behavior

It should use correct java home path

### Steps to Reproduce

Install JDK17 
Run a java code with processBuilder, inside set the JAVA_HOME to jdk8,

### Gradle version

5.4.1

**Comment by JingLeiTalan** [comment]
It seems the gradle daemon jvm don't use the JAVA_HOME set in the ProcessBuilder, but the gradle client jvm use it correctly, if i echo the JAVACMD in the gradlew file, i can got the correct JAVA_HOME pointed to jdk 8, but why the dameon don't use the correct java home ?

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Please check if the same behavior can be observed with the latest version of Gradle. If it is, please provide more detailed step-by-step instructions for us so we can reproduce the issue. 

Also, you're using a pretty old Gradle version with JDK17. See [Gradle compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html#java): your case is not there. You need to upgrade your Gradle.

**Comment by JingLeiTalan** [comment]
Hi @ov7a ,

Since i got this error in a java project, your template is for a gradle porject, 

In fact, as i mentioned in my ticket, i run a gradle project in a java process, and i dont really think it's a problem with Gradle compatibility matrix since i specifed that the JAVA_HOME to a jdk8, so noamlly, this gradle version can support jdk8... 

thanks for your help,

**Comment by ov7a** [comment]
@JingLeiTalan Please provide more detailed step-by-step instructions to reproduce your problem. I agree that you don't need to use the template, but please provide at least MWE with `processBuilder`.

**Comment by JingLeiTalan** [comment]
Hello @ov7a, 

Here is the whole class of my GradleBuilder.java:
 
```
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

public class GradleBuilder {
    public static void main(String[] args) {
        String gradleCommand = "./gradlew clean build --info"; // Replace with your Gradle command
        ProcessBuilder processBuilder = new ProcessBuilder(gradleCommand.split("\\s+"));
        // Optionally, set the working directory for the Gradle process
        processBuilder.environment().put("JAVA_HOME", "/usr/lib/jvm/java-8-openjdk");
        processBuilder.directory(new File("gradleprojectpath"));
        processBuilder.redirectErrorStream(true);

        try {
            Process process = processBuilder.start();
            InputStream inputStream = process.getInputStream();
            InputStreamReader inputStreamReader = new InputStreamReader(inputStream);
            BufferedReader bufferedReader = new BufferedReader(inputStreamReader);

            String line;
            while ((line = bufferedReader.readLine()) != null) {
                System.out.println(line); // Print the output of the Gradle command
            }

            int exitCode = process.waitFor();
            System.out.println("Gradle command exited with code " + exitCode);

        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

For the gradleproject, the wrapped version is 5.4.1 

All of this run on in docker image based on eclipse-temurin:17-alpine, inside of it, i have download java8 and java11

Thank you for your help

**Comment by ov7a** [comment]
I can't reproduce your issue.

I guess this is a problem with your environment. If you're confident that this is a Gradle issue, please provide a reproducer with a fully automatic docker container with the latest version of gradle demonstrating the issue.

You can also find help on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

**Comment by ov7a** [comment]
Thanks for providing a reproducer.

In the end, it's a duplicate of
* https://github.com/gradle/gradle/issues/24300

See the comments there and [the doc](https://docs.gradle.org/current/userguide/toolchains.html#sec:limitations).

You can solve this by switching to `jammy` docker images.
