### ISSUE TITLE
Usage of GRADLE_HOME for ephemeral builds is wrong

### ISSUE THREAD

**Issue by Phlegethon90** [gradle/gradle#26699]
### Issue type

Wrong or misleading information

### Problem description

> The path that can be copied is `$GRADLE_HOME/caches/modules-<version>`. The only constraint is placing it using the same structure at the destination, where the value of `GRADLE_HOME` can be different.

`GRADLE_HOME` is wrong. `GRADLE_USER_HOME` is right. 

### Page with the problem

https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:cache_copy

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

There is another instance of that error at https://docs.gradle.org/current/userguide/build_cache_performance.html#fully_cached_builds :
> Clean the cache directory to avoid any hits from previous builds (rm -rf $GRADLE_HOME/caches/build-cache-*)
