### ISSUE TITLE
Use Immutable artifact transforms for non-incremental project transforms

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#26694]
It seems we currently don't use Immutable artifact transforms for projects even if transforms are not incremental. See the code here:
https://github.com/gradle/gradle/blob/6d29f4806426f3a3145ba23f1d60b35d93aebe83/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/DefaultTransformInvocationFactory.java#L80-L109

Due to that we can have issues with "files being open" errors on Windows for instrumentation with artifact transforms for `buildSrc` and `included builds`, since project scoped ClassLoaders keep instrumented jars open.

It seems we could just use immutable transforms also for non-immutable project transforms without consequences. Let's try it out.

Relates to https://github.com/gradle/gradle/issues/26037.

See also [Slack discussion](https://gradle.slack.com/archives/C02V8UKCXPT/p1697009714033579?thread_ts=1696952543.292069&cid=C02V8UKCXPT) for more context.

**Comment by wolfs** [comment]
The choice that for project transforms the workspace is within the project is deliberate. So you can get rid of all the transformed files via clean. That is independent of whether the transform is incremental or not.

The project artifacts change much more often than the external artifacts - so I'd expect as well that if we move them two the immutable cache, then they'd fill that up much more quickly.

Before your changes, didn't instrumentation work in a way that it first copied the project artifacts in the jars cache and then did the transform there. I think that still makes sense. You also don't really care about the coordinates/dependency management information of the input artifact, so maybe converting the configuration to a file collection first and then doing the transform might make sense.

**Comment by asodja** [comment]
> Before your changes, didn't instrumentation work in a way that it first copied the project artifacts in the jars cache and then did the transform there. I think that still makes sense.

Yes, it works like that and lof of this work is basically to simulate this old behaviour, so I also think makes sense.

> So maybe converting the configuration to a file collection first and then doing the transform might make sense.
I didn't know that will work, nice trick. I can try that.

**Comment by asodja** [comment]
I [spiked](https://github.com/gradle/gradle/blob/b150a9b1db20fd60a640982bfbaa8dbed1ae17ab/subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultScriptClassPathResolver.java#L107-L113) the suggestion from Stefan and it works as we want for instrumentation with artifact transform.

Due to that we don't need to implement this. Closing the issue.

**Comment by asodja** [comment]
Reopened due to https://github.com/gradle/gradle/pull/26792

**Comment by lptr** [comment]
Changed to `a:chore` because this is a feature of the execution engine, but not a feature of the build tool itself.
