### ISSUE TITLE
Play plugin does not support custom Twirl format

### ISSUE THREAD

**Issue by ymwang1984** [gradle/gradle#2670]
### Expected Behavior

This issue is an extension of the issue [Play compiled Twirl templates fail to process annotations](https://github.com/gradle/gradle/issues/2566)

In Play framework, by defaults it supports 4 Twirl formats: [Html, Javascript, Xml and txt](https://github.com/playframework/twirl/blob/master/sbt-twirl/src/main/scala/play/twirl/sbt/SbtTwirl.scala#L89-L94). 

In addition, it supports [custom Twirl templates](https://www.playframework.com/documentation/2.4.x/ScalaCustomTemplateFormat) that users could specify. 

### Current Behavior

Currently, for Gradle [it only supports Html format](https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/platform-play/src/main/java/org/gradle/play/internal/twirl/TwirlCompilerAdapterV22X.java#L86). It does not support Javascript, Xml, Txt format. Neither does it support custom format.

### Context

Product teams in my company are trying to migrate Play applications from SBT to Gradle. But they are blocked by this issue since Twirl templates are widely used.

### Steps to Reproduce (for bugs)

We set up a small repo to reproduce this issue: https://github.com/ymwang1984/play-on-gradle-twirl

[Our simple custom template engine](https://github.com/ymwang1984/play-on-gradle-twirl/blob/master/app/views/Csv.scala) is called "Csv". And [the dummy Csv template](https://github.com/ymwang1984/play-on-gradle-twirl/blob/master/app/views/records.scala.csv) sits inside app/views.

And [build.sbt](https://github.com/ymwang1984/play-on-gradle-twirl/blob/master/build.sbt#L9):
`.settings(TwirlKeys.templateFormats += ("csv" -> "views.CsvFormat"))`
`.settings(TwirlKeys.templateImports ++= Seq("java.util.Random", "java.util.Map"))`

That settings point any csv Twirl template to be interpreted by the custom template engine. 

We also have addition template imports (java.util.Map, etc.) specified. This additional import seems missing as well in Gradle. Our production teams need this feature to correctly compile the custom templates.

`./sbt compile` would compile those templates. But Gradle won't be able to do that.

### Your Environment

 * Build scan URL: 

This issue can be reproduced on both my MacBook and my Linux.

**Comment by big-guy** [comment]
@ymwang1984 Could you try out a nightly:

`./gradlew wrapper --gradle-version=4.2-20170816181335+0000`

...and see if this is any better?

I would expect:
1) Gradle now generates code for HTML, JS, TXT and XML templates. 
2) You can define a custom Twirl template format (see https://docs.gradle.org/nightly/dsl/org.gradle.language.twirl.TwirlSourceSet.html)

I've checked that at least something is generated and everything compiles, but it would be helpful if you can confirm that all the pieces are working together.

Thanks!
