### ISSUE TITLE
Unable to rerun the failed test cases using -Dfailsafe.rerunFailingTestsCount={number of retries}

### ISSUE THREAD

**Issue by ajith1337** [gradle/gradle#26709]
### Current Behavior

I am trying to rerun the failed test scenarios from serenity with cucumber. For the retry I am using maven fail safe plugin 
https://maven.apache.org/surefire/maven-failsafe-plugin/examples/rerun-failing-tests.html 

Configured below properties in serenity.properties

test.retry.count=3
max.retries=4
junit.retry.tests=true
test.retry.count.cucumber=3

None of them worked with gradle. The same is worked with Maven. 

### Expected Behavior

Gradle build should rerun the failed scenarios using maven fail safe plugin. 

### Steps to Reproduce

In Serenity with Cucumber framework, 
Configure the below properties in serenity.properties 

test.retry.count=3
max.retries=4
junit.retry.tests=true
test.retry.count.cucumber=3

Run the below command 
gradlew clean test -Dfailsafe.rerunFailingTestsCount=3 -Dcucumber.filter.tags=@abc

### Gradle version

8.2.1

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

`-Dfailsafe.rerunFailingTestsCount=3` is maven plugin option.
