### ISSUE TITLE
GradleBuild task sometimes hangs up on Gradle 4.1-milestone-1 or later

### ISSUE THREAD

**Issue by zaki50** [gradle/gradle#2673]
`GradleBuild` task sometimes hangs up on Gradle 4.1-milestone-1 or later

Current work-around is to add `--console=plain` to command line.

### Expected Behavior

`GradleBuild` task always succeeds to build.

### Current Behavior

`GradleBuild` task sometimes hangs up during execution of sub project.

```
$ ./gradlew iRJ
Picked up _JAVA_OPTIONS: -Dfile.encoding=UTF-8 -Dgroovy.source.encoding=UTF-8
<=====--------> 40% EXECUTING [1s]
> :installRealm > Resolve dependencies :realm:realm-library:kaptAndroidTest
> IDLE
```
Time counting also stops when this bug happens.

### Context

I'm using Gradle in Realm project and this bug happened when I updated gradle wrapper to 4.1-milestone-1.

https://github.com/realm/realm-java/tree/my/agp_3.0-alpha5

### Steps to Reproduce (for bugs)

Checking out `my/agp_3.0-alpha5` branch from Realm's repository and then
executing `./gradlew installRealmJava` will reproduce this.
However, it requires some build environment setup, so I'll create small project that reproduce this.

### Your Environment
macOS Sierra + Gradle wrapper 4.1-milestone-1 to official release of 4.1

**Comment by oehme** [comment]
Thank you for the report, a small reproducible project would be much appreciated. Does the problem still occur with the final 4.1 release?

**Comment by zaki50** [comment]
@oehme Yes, I reproduced it with 4.1 release.

**Comment by zaki50** [comment]
Small java library project doesn't reproduce this issue...

**Comment by oehme** [comment]
Could you please attach a thread dump of a hanging build?

**Comment by zaki50** [comment]
@oehme here  https://gist.github.com/zaki50/8bd7417ed27ceb0c10d1d33335abe937

**Comment by oehme** [comment]
@eriwen this might actually be a symptom of https://github.com/gradle/gradle/issues/2622. If there can be duplicated IDs, then the map in the grouping listener can contain a cycle, leading to an infinite loop. So this might already be fixed by Jendrik's change.

**Comment by zaki50** [comment]
@oehme Oh, that's a good news. I'll try with latest nightly build to confirm that!

**Comment by zaki50** [comment]
Yes!!
I've tried `4.2-20170807235738+0000` and it works perfectly!

Thank you so much.

**Comment by oehme** [comment]
Thank you for verifying!
