### ISSUE TITLE
Wrong Windows instruction

### ISSUE THREAD

**Issue by tomaszs** [gradle/gradle#26748]
### Issue type

Wrong or misleading information

### Problem description

"Create a new directory C:\Gradle with File Explorer.

Open a second File Explorer window and go to the directory where the Gradle distribution was downloaded. Double-click the ZIP archive to expose the content. **Drag the content folder gradle-8.4** to your newly created C:\Gradle folder."

The wording is confusing. "Drag the content folder" is too similar to "Drag the content of a folder"

I propose to change the wording to "Drag the folder gradle-8.4 (...)"

### Page with the problem

https://gradle.org/install/

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by bgalek** [comment]
I'll fix it ;)

**Comment by lkasso** [comment]
I will be pushing the fix for this in my monthly doc cleanup PR.
Thank you @bgalek and @tomaszs.

**Comment by lkasso** [comment]
Closed with @bgalek's commit https://github.com/gradle/gradle/pull/26762
