### ISSUE TITLE
Add Version to Version Catalog Javadoc

### ISSUE THREAD

**Issue by jamesward** [gradle/gradle#26741]
### Expected Behavior

The generated javadoc for Version Catalog artifacts includes the artifact group and name but should also include the version.

### Current Behavior (optional)

![image](https://github.com/gradle/gradle/assets/65043/1087f6f3-ec34-4d44-9604-dd7148b365f4)

### Context

Just trying to improve the DX with version catalogs.

**Comment by jamesward** [comment]
cc @eskatos

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented.

**Comment by ljacomet** [comment]
Both plugins and dependencies are missing the version information in the generated javadoc.

However this information can be easily added. We have two cases:
* the version is defined inline,
* a `versionRef` is used

The proposal is to add an extra line to the javadoc of both plugins and dependencies that will say:
`with versionRef '<RefName>'` or `with version '<version>'` where that `<version>` element can be a simple value or a more complex rich version.
