### ISSUE TITLE
Document how bytecode instrumentation and upgrades work

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#26752]
### Issue type

Missing information

### Problem description

We should document how Gradle does bytecode instrumentation. This is currently used both for detecting problems that would prevent configuration cache from working properly, as well as upgrading the bytecode of plugins built against an older, incompatible version of Gradle.

### Page with the problem

This should be documented internally

**Comment by asodja** [comment]
A spec
https://docs.google.com/document/d/1g2ouFsYV57_UaWcK-W0hAaXPUX-YbM1NXvthTP2CDQc/edit#heading=h.610fausqnpu6
