### ISSUE TITLE
unable to create task based on code in documentation

### ISSUE THREAD

**Issue by XXY233** [gradle/gradle#26750]
### Issue type

Wrong or misleading information

### Problem description

I tried following the steps here: [Part 2: Running Gradle Tasks](https://docs.gradle.org/current/userguide/part2_gradle_tasks.html)

```
tasks.register("copyTask",Copy) {
    from("source")
    into("target")
    include("*.war")
}
```

But the IDE prompted me with wrong information.
![image](https://github.com/gradle/gradle/assets/46647646/a874ed5b-2838-4511-a553-f66d4f95a597)

### Page with the problem

https://docs.gradle.org/current/userguide/part2_gradle_tasks.html

**Comment by ciscoo** [comment]
The documentation snippet is for the Groovy DSL. Your screenshot shows that your are using the Kotlin DSL therefore you must convert the snippet:

```kotlin
tasks.register("copyTask", Copy::class) {
    from("source")
    into("target")
    include("*.war")
}
```

or

```kotlin
tasks.register<Copy>("copyTask") {
    from("source")
    into("target")
    include("*.war")
}
```

**Comment by ov7a** [comment]
Thanks., @ciscoo!

@XXY233 Your question might be answered on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

**Comment by XXY233** [comment]
@ov7a  I tried asking for help on the gradle forum before and people there told me it was a bug so I came here to report it.🤔

> This example and the following are indeed wrong.
They are showing the Groovy DSL variant.
When the Kotlin DSL became the default, Part 1 was adapted properly, so you have a Kotlin DSL build script.
But the further code examples were not changed accordingly.
You should report a bug about this documentation issue.

**Comment by ov7a** [comment]
Oh, I missed that. Thanks for the clarification! It's a valid documentation issue then.
