### ISSUE TITLE
The tar archive generated in Gradle 8+ is not compatible with "tar --delete" command in Linux

### ISSUE THREAD

**Issue by payneChen** [gradle/gradle#26763]
### Current Behavior

The tar archive generated in Gradle 8+ could be corrupted by "tar --delete" command in Linux
1. Here is the tar task:
```
tasks.register('packageDistribution', Tar) {
  it.compression = Compression.NONE
  it.from layout.projectDirectory.dir("resources")
}
```
2. Here is the command `tar --delete -f gradle-tar-error-1.0.0.tar lib` which breaks the archive.
3. Finally the archive could not be extracted successfully with the errors:

> tar: Skipping to next header
> tar: Exiting with failure status due to previous errors

### Expected Behavior

After run `tar --delete -f gradle-tar-error-1.0.0.tar lib`, the archive could still be extracted with the left members

### Context (optional)

In our pipeline, the generated tar.gz will be downloaded into the target environment and the deployment script would extract tar.gz but including multiple steps for the different purposes, one of the step is "tar --delete".

### Steps to Reproduce

Here is the repo to reproduce the problem: https://github.com/payneChen/gradle-tar-error
I extracted gradle 8.3 distribution into`resources` folder as example:
1. run `./gradlew packageDistribution`
2. go to `build/distribution` and run `tar --delete -f gradle-tar-error-1.0.0.tar lib` which used to remove lib folder in the archive
3. run `tar --list -f gradle-tar-error-1.0.0.tar` to verify the archive.

The result is as following:
```
~/gradle-tar-error/build/distributions$ tar --list -f gradle-tar-error-1.0.0.tar 
bin/
bin/gradle.bat
bin/gradle
LICENSE
tar: Skipping to next header
init.d/
init.d/readme.txt
tar: Exiting with failure status due to previous errors
~/gradle-tar-error/build/distributions$ tar xf gradle-tar-error-1.0.0.tar 
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

### Gradle version

8.3

### Gradle version that used to work

7.6.1

### Your Environment (optional)

------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------

Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.8.1 (SAP SE 17.0.8.1+1-LTS)
OS:           Linux 5.15.0-83-generic amd64

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

I've experimented a bit with this and strongly believe this is a problem with `tar`, not Gradle. 

Gradle uses [Apache Commons Compress](https://github.com/apache/commons-compress) for creating tar archives. One nuance that might matter is that it [pads header records with spaces](https://github.com/apache/commons-compress/blob/5353a191cc2d578b8846d549319250562224e1e9/src/main/java/org/apache/commons/compress/archivers/tar/TarUtils.java#L191). Another possible culprit might be zero-padding of files. 

`tar --delete` produces corrupted tars even for simple tars containing 3-5 files. You can observe this behavior using hex editor: first comes the header, then part of file content, then another header, then another part of the first file, etc.

Note the resulting tar produced by Gradle is valid.

Please [report the bug](https://www.gnu.org/software/tar/manual/html_node/Reports.html) for the `tar` utility.
