### ISSUE TITLE
Upgrade embedded Kotlin to 1.9.20 when available

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#26764]
As part of the upgrade we should revert 
* https://github.com/gradle/gradle/pull/26758

because Kotlin 1.9.20 will be doing just that:

https://github.com/JetBrains/kotlin/blob/v1.9.20-RC/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/tasks/DefaultKotlinJavaToolchain.kt#L219-L223

----

Upgrade unblocks
* https://github.com/gradle/gradle/issues/24232

----

Related
* https://github.com/gradle/gradle/pull/26344

**Comment by bulldog98** [comment]
fyi it's out now

**Comment by SaltOfTheFlame** [comment]
why not upgrade to version 1.9.21 ? (1.9.20 has some breaking issues)
