### ISSUE TITLE
Instrumentation with artifact transforms should normalize jars before instrumentation

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#26773]
This was spiked in [Normalized hash for immutable artifacts identity](https://github.com/gradle/gradle/pull/26765), but we found out that it causes a regression, see this [graph](https://github.com/gradle/gradle/assets/3939893/3401bc09-36dd-4505-a70b-d3b5cae2cbee).

The regression is caused, because when we walk an input of a work, where an input is a result of an artifact transform, we recalculate identity in uncached way, here: https://github.com/gradle/gradle/blob/a044b93ad0caf001b511890bea4dbd56e3bf9521/platforms/core-execution/execution/src/main/java/org/gradle/internal/execution/steps/IdentifyStep.java#L81-L95

One solution could be, that we cache result of normalized fingerprinting in [DefaultInputFingerprinter.visitInputFileProperty](https://github.com/gradle/gradle/blob/a044b93ad0caf001b511890bea4dbd56e3bf9521/platforms/core-execution/execution/src/main/java/org/gradle/internal/execution/impl/DefaultInputFingerprinter.java#L121).

This is a problem only for project plugin artifacts (e.g. `buildSrc` and included builds).

Other solutions could be:
- We normalize plugin artifacts via another transform
- We normalize plugins artifacts when they are built
 
This was already implemented for old instrumentation, see https://github.com/gradle/gradle/issues/14897.

 --
 
 Relates to https://github.com/gradle/gradle/pull/26045

**Comment by lptr** [comment]
We now normalize project dependencies, and we don't need normalization for other dependencies.
