### ISSUE TITLE
In Gradle 8.4, Project.getConfigurations() is marked unstable again

### ISSUE THREAD

**Issue by Omico** [gradle/gradle#26777]
### Current Behavior

![image](https://github.com/gradle/gradle/assets/14316223/fc1e6096-ac10-49d6-a83a-270d8a6a8ac4)

### Expected Behavior

![image](https://github.com/gradle/gradle/assets/14316223/3647a587-295d-4d43-a3e1-208429ec6bc3)

### Steps to Reproduce

See https://github.com/Omico/intellij-settings-hero/commit/0f4fb3774baccf88d194c2b8899e7a49fe1f2da4

### Gradle version

8.4

**Comment by jvandort** [comment]
I suppose we would solve this by de-incubating `ConfigurationContainerScope`? @big-guy

**Comment by big-guy** [comment]
Yes, that's what I was thinking
