### ISSUE TITLE
Deadlock in parallel model building with AGP

### ISSUE THREAD

**Issue by KaiyuanZhao** [gradle/gradle#26790]
### Current Behavior

Deadlock when resolve dynamic feature dependencies, especially when using a new GRADLE_USER_HOME.

Similar to https://github.com/gradle/gradle/issues/25416

### Expected Behavior

No deadlock when resolve dynamic feature dependencies.

### Context (optional)

I compiled a lot of Gradle versions by myself and I can confirm that this issue was caused by https://github.com/gradle/gradle/pull/24984.

I saw this pr was reverted in Gradle 8.2 by https://github.com/gradle/gradle/pull/25457. Maybe a rollback is needed in 8.3/8.4 as well.

### Steps to Reproduce

I can't provide a full reproducible demo because we use a lot of internal dependencies. But I can provide a similar project structure and a thread dump file.

thread dump for CI build:
[stack_for_CI.txt](https://github.com/gradle/gradle/files/13051893/stack_for_CI.txt)

thread dump for demo:
[stack_for_demo_resolve.txt](https://github.com/gradle/gradle/files/13051910/stack_for_demo_resolve.txt)

resolve demo:
[demo_resolve_upload.zip](https://github.com/gradle/gradle/files/13051943/demo_resolve_upload.zip)

step:
- add some dependencies into dependencies.txt
- using a new GRADLE_USER_HOME
- ./gradlew :app:printRuntimeClasspath
![image](https://github.com/gradle/gradle/assets/9658203/e586f09e-f3ab-4bb8-b8d5-65e2a20dae79)
- no deadlock occurs when adding --no-parallel into command

Not all dependencies cause a deadlock, but our internal dependencies are stuck 90% of the time, perhaps because of the long time it takes to resolve the dependencies.

### Gradle version

8.3-RC1/8.3/8.4

### Gradle version that used to work

8.2/8.2.1

### Your Environment (optional)

- java17
- agp7.4.2/agp8.1.2
- windows/linux
- a fresh GRADLE_USER_HOME

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by ghale** [comment]
Thanks for reporting this @KaiyuanZhao.  I believe I have a fix implemented.  Could you try the following nightly and see if this issue still happens for you?
```
$ gradlew wrapper --gradle-version=8.6-20231116190533+0000
```

**Comment by KaiyuanZhao** [comment]
@ghale Unfortunately our demo is still getting a deadlock when using 8.6-20231116190533+0000.

**Comment by KaiyuanZhao** [comment]
@ghale It seems gradle-8.6-20231118001259+0000 solved my issue, maybe you gave me the wrong version. I tried to cherry-pick https://github.com/gradle/gradle/pull/27015 to tag v8.4.0 and build a custom gradle locally, the issue was fixed too. Is there any chance to backport this patch to older version like 8.4 or 8.5?

**Comment by ghale** [comment]
Sorry, yes, I sent the wrong nightly version.  8.6-20231116190533+0000 did not have the fix.  

As far as backporting this, 8.5 will be releasing imminently and it's too late to slip anything new into it.  8.4 does not have a planned patch release right now.  If we do have to do another release of either, we might be able to add this fix, too.
