### ISSUE TITLE
Gradle 8.x bootJar fails resolving dependencies for productionRuntimeClasspath because of sources jar

### ISSUE THREAD

**Issue by jimshowalter** [gradle/gradle#26804]
### Current Behavior

With these dependencies:

|    |    |    |    |         +--- com.squareup.okhttp3:okhttp:4.12.0
|    |    |    |    |         |    +--- com.squareup.okio:okio:3.6.0
|    |    |    |    |         |    |    \--- com.squareup.okio:okio-jvm:3.6.0
|    |    |    |    |         |    |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.10
|    |    |    |    |         |    |         |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10
|    |    |    |    |         |    |         |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10
|    |    |    |    |         |    |         |    |    \--- org.jetbrains:annotations:13.0
|    |    |    |    |         |    |         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.10
|    |    |    |    |         |    |         |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.9.10 (*)
|    |    |    |    |         |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10
|    |    |    |    |         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21 -> 1.9.10 (*)
|    |    |    |    |         +--- com.squareup.okhttp3:okhttp-urlconnection:4.12.0
|    |    |    |    |         |    +--- com.squareup.okhttp3:okhttp:4.12.0 (*)
|    |    |    |    |         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21 -> 1.9.10 (*)

Execution failed for task ':bootJar'.
> Could not resolve all files for configuration ':productionRuntimeClasspath'.
   > Could not find okio-jvm-3.6.0-sources.jar (com.squareup.okio:okio-jvm:3.6.0).
     Searched in the following locations:
         https://box.jfrog.io/box/signedthirdpartymaven/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0-sources.jar

Note that it's looking for a sources jar, which isn't relevant to a production runtime classpath.

Reverting to Gradle 7.6.3 fixes the problem, but we want to use Gradle 8.4.

### Expected Behavior

Should not look for a sources jar when calculating dependencies for productionRuntimeClasspath.

### Steps to Reproduce

In a service project that has the bootRun task, using Gradle 8.x, and that has a dependency on com.squareup.okhttp3:okhttp:4.12.0 , try to execute bootRun.

### Gradle version

8.4

### Your Environment (optional)

Latest MacOS on M1 arm locally, and RHEL8 on Linux x86 in Google Cloud Platform.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
