### ISSUE TITLE
Broken link in "Declaring Repositories" page

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#26814]
### Issue type

Wrong or misleading information

### Problem description

A link to the Apache HttpClient library is broken [here](https://docs.gradle.org/8.4/userguide/declaring_repositories.html#sec:authentication_schemes).

The link hits `http://hc.apache.org/httpcomponents-client-ga/tutorial/html/authentication.html#d5e625`, redirecting to a 404.

This may be a bug with the Apache documentation redirect; I filed an issue there: [HTTPCLIENT-2304](https://issues.apache.org/jira/browse/HTTPCLIENT-2304)

### Page with the problem

https://docs.gradle.org/8.4/userguide/declaring_repositories.html#sec:authentication_schemes

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
