### ISSUE TITLE
gradle-wrapper.properties config for all new projects

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [gradle/gradle#2682]
Hi author,
    I want to config for my all new projects in /Applications/Android Studio.app/Contents/plugins/android/lib/templates/gradle/wrapper/gradle/wrapper/gradle-wrapper.properties.
   I config the distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip to  distributionUrl=http\://**mysite**/gradle/gradle-3.3-all.zip.
   But when I new a project in Android Studio, the gradle-wrapper.properties file had change to what it always be. I have to config it in project again.
   So, my question is how can I config the gradle-wrapper.properties distributionUrl to my own and I can make it work when I start a new project.
Thanks!

**Comment by oehme** [comment]
This question is better suited for the [Android Studio bug tracker](https://issuetracker.google.com/issues?q=componentid:192633%2B
). There's nothing we can do on the Gradle side to improve this.
