### ISSUE TITLE
EvaluationDependsOn BROKEN except in trivial case

### ISSUE THREAD

**Issue by cornergraf** [gradle/gradle#2684]
I want to configure a task for all subprojects that have the .war plugin using something like `configure(subprojects.findAll { it.plugins.hasPlugin('war') }`. However, this does not find any projects, even though some subprojects do have the war plugin applied. This happens even when using `EvaluationDependsOn` with the specific project, or using `EvaluationDependsOnChildren`. 

I do not feel comfortable pasting our company build files on the internet, but the trivial sample I have built does not show the problematic behavior, so instead I can show you the part of my build file that has the problem:

```
evaluationDependsOnChildren()

subprojects.findAll {
    println "$it.path has war: " + (it.plugins.hasPlugin('war'))
}

configure(subprojects.findAll { it.plugins.hasPlugin('war') }) {

    task extraWarStuff(dependsOn: 'war') {
        println "$project.name has plugin war"
    }
}
```

If gradle developers cannot very quickly point out just exactly what can prevent the above from working, this is a bug.

It does not matter if the behavior is somehow by design, build files must be easy to understand, and if the above snippet can be broken by some other declaration in (probably) another build file, then gradle is broken and unusable.

### Expected Behavior
I expect to see this output:

```
:project:with:war:plugin has war: true
warProject has plugin war
```

### Current Behavior
I get the output 

```
:project:with:war:plugin has war: false
```

### Context
I want to add a task to all projects with the war plugin, so that I may declare a task dependency in other gradle projects.

### Steps to Reproduce (for bugs)
I do not feel comfortable posting our full build scripts, and the trivial sample case I have built does not show this behavior.

### Your Environment
Gradle version: 3.5

**Comment by oehme** [comment]
Instead of using `evaluationDependsOn`, which is brittle (and which we'll probably remove at some point), you can use the appropriate callbacks instead:

```
subprojects {
  plugins.withId('war') {
    //react to war plugin
  }
}

**Comment by cornergraf** [comment]
Can I declare a task in such a block, which would exist for all war projects?

**Comment by oehme** [comment]
You can do anything inside that block, e.g.

```
subprojects {
  plugins.withId('war') {
    task extraWarStuff(dependsOn: 'war') {
    }
  }
}
```

**Comment by oehme** [comment]
Regarding `evaluationDependsOnChildren`: This only evaluates the *direct children*  of the project, not the whole tree. So if you war project is nested somewhere deeper down, it won't get evaluated.

**Comment by cornergraf** [comment]
Thanks a lot, this seems to solve my immediate problem.

It almost seems like magic, which is not necessarily a good thing because it is utterly unintuitive that this should work. And there is no way to search the documentation for something like this, because it requires knowing what exactly to search for :S

And good to know about evaluationDependsOnChildren, I could not understand why it did not work at all.

**Comment by oehme** [comment]
> it is utterly unintuitive that this should work

Could you elaborate why?

**Comment by cornergraf** [comment]
> Could you elaborate why?

Because the closure with the task declaration is an argument to a collection of plugins. But tasks are not typically declared in plugins (except during development of said plugin of course), instead tasks are declared in projects. Which is why I was looking for a solution to configure projects that had a specific plugin, it never occurred to me that I might be able to "modify" the plugin itself.

**Comment by oehme** [comment]
> occurred to me that I might be able to "modify" the plugin itself.

You don't modify the plugin. All this callback does is notify you that the plugin has been applied.

**Comment by cornergraf** [comment]
>You don't modify the plugin. All this callback does is notify you that the plugin has been applied.

That's good to know I guess, thank you.

However, without any hostility whatsoever, it still is very unintuitive. I realize it's not completely trivial, but configuring all projects that share some property needs to be a no-brainer, and there needs to be one right way that applies to all they ways you can configure a project.

If you have some special way to add tasks to all war projects, and some other way to change properties on all projects that are in a certain path, and a third way to do another thing... This needs to be consistent in the way that `configure(subprojects.findAll { <some-filter> }`  would be, if only it would work.

**Comment by oehme** [comment]
> configuring all projects that share some property needs to be a no-brainer

There are only a few properties of a project (its name, location and the location of its build script) that are known up-front and immutable. 

For everything else you need to listen for changes you are interested in, e.g. `plugins.withId('java') { //react to the java plugin being added }` or `tasks.withType(Jar) { //react to a Jar task being added}`. These two cover pretty much every case of "pushing more configuration into projects, depending on the 'kind' of project".
