### ISSUE TITLE
Bug in Tutorial Apply Plugin section

### ISSUE THREAD

**Issue by tjherring** [gradle/gradle#26861]
### Issue type

Wrong or misleading information

### Problem description

The section describes using the maven plugin.  The problem with the current documentation is this commit: 2252603f25005db5ffb6552b1609bd7d7aa32fbe

It removed the correct way to make the plugin publish correctly.

It should be:
create<MavenPublication>("maven") {
Not:
mavenJava(MavenPublication)("maven") {

I am a novice in gradle, but there seems to be some problem with the current tutorial.  The previous code in the documentation works correctly.

### Page with the problem

https://docs.gradle.org/8.4/userguide/part4_gradle_plugins.html

**Comment by tjherring** [comment]
Additionally, I found another issue.  The publishing section specifies a groupId of 'org.gradle.tutorial', but everywhere else in the tutorial a groupId of 'com.gradle.tutorial' is used.  Perhaps this should be fixed for consistency sake.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

The PR you referring to should be reverted.
