### ISSUE TITLE
Provide support for "per unit test coverage" reports in sonarqube

### ISSUE THREAD

**Issue by jayanmn** [gradle/gradle#2689]
From https://issues.gradle.org/browse/GRADLE-2895

I am trying to get jacoco+sonarqube+any build tool work report coverage-per-test.  It appears that maven works, I do know. Gradle is my tool of choice for all new project and it should have way to report coverage-per-test

SonarQube feature is buried under https://docs.sonarqube.org/display/PLUG/Code+Coverage+by+Unit+Tests+for+Java+Project

Essentially it works  by recording sessions with classname and method name in jacoco.exec file.

### Expected Behavior

Current targets:

` gradle test jacocoTestReport ` gets a coverage report. 
` gradle sonarqube`   sends data to sonarqube

 Some new target or parameters to new existing targets to get coverage report per test basis.

### Current Behavior
I do not know

### Context

Coverage per test is feature in SonarQube. I am trying to see it working with gradle
(actually tried with ant, maven - nothing really works)

we have about 5million line code covered by tens of thousands of test.  Once we get database of test vs line, we could reduce the number of tests for a given change.

Our current build tools is ant, hoping to push gradle  in new projects.

### Steps to Reproduce (for bugs)
Not a bug
### Your Environment
windows or linux
Java 8
Lot of CPU (16 cores) and memory(32G, 64G+)

 * Build scan URL:

**Comment by oehme** [comment]
This is a question for the sonarqube plugin, which is not maintained by us. Please ask on their issue tracker or forum.
