### ISSUE TITLE
Gradle 8.4: Failed to notify project evaluation listener.

### ISSUE THREAD

**Issue by lamba92** [gradle/gradle#26894]
### Current Behavior

When starting any task since Gradle 8.4, there is a random chance to get:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':kmp-modifier'.
> Failed to notify project evaluation listener.
   > org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublicationIdentity
```

### Expected Behavior

The build should just run...

### Steps to Reproduce

I cannot reliably reproduce the issue. I have logs of a private project, you cam DM me by email to share.

### Gradle version

8.4

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***
A stack trace would already help narrow down the area of the issue. We would however still prefer a reproducer, even if it requires multiple runs to trigger the issue.
