### ISSUE TITLE
"JaCoCo Report Aggregation Plugin" fails when configuration cache is enabled (gradle plugin project)

### ISSUE THREAD

**Issue by rmarma** [gradle/gradle#26922]
### Current Behavior

Build failed with an exception:
```
* What went wrong:
Could not load the value of field `elements` of `org.gradle.configurationcache.serialization.codecs.ResolutionBackedFileCollectionSpec` bean found in field `classDirectories` of task `:testCodeCoverageReport` of type `org.gradle.testing.jacoco.tasks.JacocoReport`.
> org.gradle.testing.jacoco.plugins.JacocoReportAggregationPlugin$$Lambda$1936/0x000000f801396530
```

### Expected Behavior

Aggregated report is successfully created.

### Context (optional)

Getting a aggregated report on test coverage in a multi-module gradle plugin project.

### Steps to Reproduce

1. Clone project https://github.com/rmarma/jacoco-report-aggregation-problem
2. Run:
```
./gradlew :testCodeCoverageReport 
```
----------
Running with `--no-configuration-cache` completes successfully.

When changing plugin `kotlin-dsl` to `kotlin-dsl-base` in a project that is added to `jacocoAggregation`, the build also completes successfully with the configuration cache.

### Gradle version

8.4

**Comment by ljacomet** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by simon-spinner** [comment]
This is not only an issue for JaCoCo report aggregation. I see the same error message when using the Test Report Aggregation Plugin only with the configuration cache enabled.
