### ISSUE TITLE
Updating Gradle from 3.3 to 4.1 yields No class directories configured for FindBugs analysis.

### ISSUE THREAD

**Issue by vanniktech** [gradle/gradle#2692]
### Expected Behavior

Running the `findbugs` task should not fail with `No class directories configured for FindBugs analysis.` when updating from Gradle 3.3 to Gradle 4.1.

### Current Behavior

I've got a project that uses findbugs and it works perfectly fine when using Gradle 3.3 or Gradle 3.5.

The moment I update to Gradle 4.0 or Gradle 4.1 it'll fail with `No class directories configured for FindBugs analysis.` when running `./gradlew clean findbugs`.

A sample of this can be found [here](https://github.com/vanniktech/lint-rules/pull/64).

The `findbugs` task is not created directly in this project but rather via a custom plugin as you can see [here](https://github.com/vanniktech/gradle-code-quality-tools-plugin/blob/6c45c13f01c85b66224c8081eef133a8077fb1cc/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPlugin.groovy#L164). There you can find the task creation as well as the configuration block for the `findbugs` extension.

What I have noticed though is that this kind of failure only happens on modules that have only the `java` plugin applied. When using `com.android.library` or `com.android.application` without `java` findbugs works normally.

I know this information might not be enough, if you need any further information or have any question feel free to ask.

**Comment by vanniktech** [comment]
Ah! I think I might know what's causing this. It seems like the build directory moved from `build/classes/main/` to `build/classes/java/main` with Gradle 4.0, correct?

Is there any API that I can use that is stable and will take care of those changes in the future if paths are changed again? Or preferably know which Gradle version the consumer of a plugin is running so that pre 4 I'll use `build/classes/main/` and otherwise `build/classes/java/main`?

**Comment by big-guy** [comment]
You should be using `sourceSets.main.output` (for classes + resources, any version), `files({ 
 sourceSets.main.classesDir })` (for classes only, pre-4.0) or `sourceSets.main.output.classesDirs` (for classes only, pre-4.0).

**Comment by athkalia** [comment]
@vanniktech can you share some code snippets for this? I am getting a similar error

**Comment by vanniktech** [comment]
Have a look at [this](https://github.com/vanniktech/gradle-code-quality-tools-plugin/pull/81)

**Comment by athkalia** [comment]
brilliant, thanks pal
