### ISSUE TITLE
Erro na classe scanner do java 21

### ISSUE THREAD

**Issue by Leedda** [gradle/gradle#26941]
### Current Behavior

Guys, I'm developing in netbeans with java and running gradle-8.3-rc-1

I have already uninstalled and reinstalled both java and netbeans, I made changes to the environment variable but it simply does not run and presents an error when I compile the code. If anyone can help me, I'd appreciate it.
Has anyone here ever experienced this situation?

cd C:\Users\Usuario\Documents\NetBeansProjects\Teste\app; ..\gradlew.bat --configure-on-demand -x check run
Configuration on demand is an incubating feature.
> Task :app:compileJava UP-TO-DATE
> Task :app:processResources NO-SOURCE
> Task :app:classes UP-TO-DATE

> Task :app:run FAILED
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.Scanner.throwFor(Scanner.java:945)
	at java.base/java.util.Scanner.next(Scanner.java:1486)
	at Principal.App.main(App.java:15)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:run'.
> Process 'command 'C:\Program Files\Java\jdk-21\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 254ms
2 actionable tasks: 1 executed, 1 up-to-date

### Expected Behavior

It should run the scanner class without any problems but that's not what happens.

### Steps to Reproduce

https://github.com/gradle/gradle/issues/25834

### Gradle version

gradle-8.3-rc-1-bin

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle

We require all issues to be filed using English. Unless you update the description, this issue will be closed in 3 days.

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Using Java 21 in toolchains is only supported in [Gradle 8.4+](https://docs.gradle.org/current/userguide/compatibility.html)
