### ISSUE TITLE
Gradle Convention Plugin does not publish marker artifact

### ISSUE THREAD

**Issue by renatoathaydes** [gradle/gradle#26951]
### Current Behavior

I have a minimal [Gradle Convention Plugin](https://docs.gradle.org/current/samples/sample_publishing_convention_plugins.html).

I want to publish it.

Here's the build file:

```groovy
plugins {
    id 'groovy-gradle-plugin'
    id 'maven-publish'
}

group = "com.me.gradle"
version = curityGradleConventionsVersion

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

tasks.named('publish') {
    dependsOn('check')
}
```

The convention plugin is located at `src/main/groovy/com.me.gradle.gradle-conventions.gradle`.

### Expected Behavior

When I publish it, a marker artifact is published along with the real artifact.

### Steps to Reproduce

You can test this by publishing to Maven local:

```
gradle publishToMavenLocal
```

With the sample provided above, it should be present at the following dir according to [the docs](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers):

```
ls ~/.m2/repository/com/me/gradle/gradle-conventions/com.me.gradle.gradle-conventions.gradle.plugin/
```

Publishing to a "real" remote repository does not work either.

### Gradle version

8.4

**Comment by renatoathaydes** [comment]
After converting the plugin to Kotlin, it worked :/
Seems to be a Groovy only problem.

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***
Could you please provide a full reproducer that shows the problem with groovy?

**Comment by renatoathaydes** [comment]
You don't need anything other than a build file (provided above) and an empty convention plugin file in the location I posted above.

**Comment by cobexer** [comment]
With the example provided I get both the plugin jar and the marker artifact published:
```bash
convention-plugins % find ~/.m2/repository/com/me/gradle
/Users/cobexer/.m2/repository/com/me/gradle
/Users/cobexer/.m2/repository/com/me/gradle/gradle-conventions
/Users/cobexer/.m2/repository/com/me/gradle/gradle-conventions/com.me.gradle.gradle-conventions.gradle.plugin
/Users/cobexer/.m2/repository/com/me/gradle/gradle-conventions/com.me.gradle.gradle-conventions.gradle.plugin/1.0
/Users/cobexer/.m2/repository/com/me/gradle/gradle-conventions/com.me.gradle.gradle-conventions.gradle.plugin/1.0/com.me.gradle.gradle-conventions.gradle.plugin-1.0.pom
/Users/cobexer/.m2/repository/com/me/gradle/gradle-conventions/com.me.gradle.gradle-conventions.gradle.plugin/maven-metadata-local.xml
/Users/cobexer/.m2/repository/com/me/gradle/convention-plugins
/Users/cobexer/.m2/repository/com/me/gradle/convention-plugins/1.0
/Users/cobexer/.m2/repository/com/me/gradle/convention-plugins/1.0/convention-plugins-1.0.pom
/Users/cobexer/.m2/repository/com/me/gradle/convention-plugins/1.0/convention-plugins-1.0.jar
/Users/cobexer/.m2/repository/com/me/gradle/convention-plugins/1.0/convention-plugins-1.0.module
/Users/cobexer/.m2/repository/com/me/gradle/convention-plugins/maven-metadata-local.xml
```
Unless you can provide a reproducer as requested above we will have to close this issue.
