### ISSUE TITLE
Adding a new public type and a method fails binary compatibility check

### ISSUE THREAD

**Issue by reinsch82** [gradle/gradle#26990]
### Current Behavior

I added  this class
```java
package org.gradle.api.problems;

import org.gradle.api.Incubating;

/**
 * A registry for {@link ProblemTransformer} class types.
 *
 * @since 8.6
 */
@Incubating
public interface ProblemTransformerRegistry {
    void register(Class<? extends ProblemTransformer> transformerClass);
}
```
It fails the binary compatibility check in our own gradle/gradle build

### Expected Behavior

It shouldn't fail it.

### Steps to Reproduce

Add a public type and a method that triggers kotlin extensions generation, e.g. with a function taking `Class`

### Gradle version

8.6

### Build scan URL (optional)

https://ge.gradle.org/s/tilygb53wzsgq

**Comment by eskatos** [comment]
There a two causes to this:
- we don't annotate generated files with `@file:Incubating` when needed
- we don't add `@since` Javadoc tag on generated extensions
