### ISSUE TITLE
Duplicated BOM imports in generated POMs

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#26996]
### Current Behavior

After upgrading the junit5 build to 8.5-rc-1 (see https://github.com/junit-team/junit5/pull/3547), platform dependencies are duplicated in the `dependencyManagement` section of generated POMs:

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>5.11.0-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>5.11.0-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

### Expected Behavior

They should not be duplicated (as they weren't in 8.4):

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>5.11.0-SNAPSHOT</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

### Steps to Reproduce

1. Check out branch from https://github.com/junit-team/junit5/pull/3547
2. Run `./gradlew :platform-tooling-support-tests:test --tests "platform.tooling.support.tests.MavenPomFileTests"` or `./gradlew pTML` and inspect the generated POMs (e.g. `junit-jupiter-api/build/publications/maven/pom-default.xml`)

### Gradle version

8.5-rc-1

### Build scan URL (optional)

https://ge.junit.org/s/ubygjpacvhj7o/tests/task/:platform-tooling-support-tests:test/details/platform.tooling.support.tests.MavenPomFileTests/jupiterAggregatorPomDependencies()?top-execution=1

**Comment by cobexer** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
