### ISSUE TITLE
Gradle ignores --enable-preview

### ISSUE THREAD

**Issue by palexdev** [gradle/gradle#27001]
### Current Behavior

Gradle doesn't enable preview features and build fails

### Expected Behavior

Don't ignore the '--enable-preview' directives and build

### Context (optional)

JDK 21 trying to use FFM and String templates

### Steps to Reproduce

tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("--enable-preview")
}

tasks.withType(Test).configureEach {
    it.jvmArgs += "--enable-preview"
}

tasks.withType(JavaExec).configureEach {
    it.jvmArgs += '--enable-preview'
}

This doesn't work

### Gradle version

8.4

**Comment by palexdev** [comment]
Fixed, apparently, even the Javadoc task needs the flags to enable preview features.
Add this:
```groovy
tasks.withType(Javadoc).configureEach {
    CoreJavadocOptions opt = options as CoreJavadocOptions
    opt.addStringOption("source", "21")
    opt.addBooleanOption("-enable-preview", true)
}
```


Gradle team, want an advice? Just make  a `enablePreviews()` method that does all the work for the user. As it is now, it's just a huge pita, made me lose one and a half hours of work

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

Feel free to open a feature request for this.
