### ISSUE TITLE
change in task property did not invalidate cache

### ISSUE THREAD

**Issue by wisechengyi** [gradle/gradle#2700]
Our code has:
```
tasks.all {
    // Global key into every task, so we can change it to invalidate all existing cache.
    inputs.property("globalKey", "key_20170810_01") // A brand new key
}
```
### Expected Behavior
With the newly injected property value, all tasks should rerun because each of them should have a new cache key, hence invalidating the old cache.

### Current Behavior
However in the build log it shows tasks are fetching from cache. Then looking at the buildscan, it shows the detection of key change, but somehow the cache key did not change. 

![screen shot 2017-08-10 at 11 11 04 am](https://user-images.githubusercontent.com/596358/29190016-71af8ed0-7dcd-11e7-8ece-8bd7ec3dc3a2.png)

### Context
We want to disable caching for production build, but found this issue. Cache invaldation approach is instructed by https://github.com/gradle/gradle/issues/2322#issuecomment-309194010

Initially filed https://issuetracker.google.com/issues/64569150, but I am not entirely sure if that's an android plugin issue.

**Comment by big-guy** [comment]
I think what you're doing looks right.

If you click the middle icon in the pop-up (that looks like a 3D box), it'll take you to the build scan for the build that produced that cache entry.  Maybe another task already ran with that particular "globalKey"?

**Comment by wisechengyi** [comment]
thanks for the tip! hmm interesting it took me to a build yesterday...so it's likely false alarm then. will re-open if the issue pops up again.
