### ISSUE TITLE
Add the ability to disable default artifact selection when variant not found

### ISSUE THREAD

**Issue by shanshin** [gradle/gradle#27019]
### Expected Behavior

Add a flag, like `org.gradle.api.artifacts.ResolutionStrategy.failOnVariantNotFound` which would change the [current resolve behavior](https://docs.gradle.org/current/userguide/variant_model.html#sec:variant-aware-matching) as follows: if no suitable variant was found in the dependency for specified attributes  in the current configuration, an error was thrown.

Or even more convenient, it would be possible to add an action that would be called in such cases and the user could throw an exception, or solve this situation.

### Current Behavior (optional)

According to the [documentation](https://docs.gradle.org/current/userguide/variant_model.html#sec:variant-aware-matching): `when a producer has no variants, a default artifact is chosen`

### Context

At the moment, if such a script is written in the root project:
```
val ATTRIBUTE = Attribute.of(
    "my-attr",
    String::class.java
)

val bucket = configurations.create("bucket") {
    isVisible = true
    isCanBeResolved = false
    isCanBeConsumed = false

    attributes {
        attribute(ATTRIBUTE, "request")
    }
}

val consumer = project.configurations.register("consumer") {
    isVisible = false
    isCanBeResolved = true
    // this config consumes modules from OTHER projects, and cannot be consumed by other projects
    isCanBeConsumed = false

    isTransitive = false

    extendsFrom(bucket)
}


dependencies {
    add("bucket", project(":subproject"))
}

tasks.register("testDeps") {
    doLast {
        println("Files = ${consumer.get().files}")
    }
}
```

and no artifact with the `my-attr` attribute is produced in subproject `:subproject`, then when the `testDeps` task is called, printed: `Files = [/.../subproject/build/libs/subproject.jar]`

### Use case
I need to write an aggregating Gradle plugin that will consume special files from subprojects and merge them into one.
At the same time, these files are produced as artifacts with a certain set of attributes in each subproject using the same plugin.

If the expected variant was not found in the specified dependency, this means that the plugin has not been applied in the subproject, and it is necessary to throw an error to the user with a clear description, like "plugin not applied in bproject 'X'". 

However, now instead I get a random file that breaks the aggregation behavior.

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
If your project doesn't have any configuration with attributes aka varaints then the legacy bahaviour is to select the default configuration, that will not change. However unless you are outside of existing gradle ecosystems (Android, Kotlin, JVM, ...) this should not be the case for most projects.

See the documentation [Variant-aware sharing of artifacts between projects](https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:variant-aware-sharing)
