### ISSUE TITLE
Allow cocoapods specRepos to be overridden fully

### ISSUE THREAD

**Issue by SivarajSubramanian1** [gradle/gradle#27026]
### Expected Behavior

Gradle kotlin native cocoapods plugin allows users to set the pods spec repo, but thats not overriding the current cocoapod cdn link, instead its just adding to the existing repo link. Some orgs doesnt allow pods to be downloaded from external sources and `https://cdn.cocoapods.org` is fully blocked. Because of this `podInstallSyntheticIos` tasks always fails.

We should have a method that should allow the specRepos to be overriden completely. 

This is the piece of code which is causing this problem

    class SpecRepos {
        @get:Internal
        internal val specRepos = mutableSetOf("https://cdn.cocoapods.org")

        fun url(url: String) {
            **specRepos.add(url)**
        }

        @Input
        internal fun getAll(): Collection<String> {
            return specRepos
        }
    }

### Context

podInstallSyntheticIos always fails and we are unable to use use KMP at work.

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please open such Kotlin-related issues on the JetBrains YouTrack at https://kotl.in/issue.
