### ISSUE TITLE
JacocoPluginExtension::applyTo can not be called from Kotlin

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#2702]
Full issue description here:
https://github.com/gradle/kotlin-dsl/issues/458

I'm also posting in this repo because I think this will be an API change that will end up being a PR against this repo.

**Comment by bmuschko** [comment]
@bamboo Do you require an issue for this on `gradle/gradle`? If we fix it then we'll fix it in both places anyway.

**Comment by bamboo** [comment]
@bmuschko it's not strictly required.

**Comment by bmuschko** [comment]
@bamboo OK, I am closing this issue for now.
@JLLeitschuh Please continue to track gradle/kotlin-dsl#458 to follow the progress.
