### ISSUE TITLE
ProgressEvent contains too much redundant information

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#2704]
With #2447 we added a _failing_ status to `ProgressEvent`. As this is sent **very** often, it introduced a performance regression. We should revert this and instead send a dedicated `StatusChangedEvent` the moment a build starts failing.

Experiment that removed the additional data and shows performance improvements:
https://github.com/gradle/gradle/compare/oehme/performance/ide-regression#diff-9e3134b8dd94faaa38e8eb7119f62a9dL30

**Comment by oehme** [comment]
Closing, as we've made other improvements that compensated for this.
