### ISSUE TITLE
Gradle daemon and SSHJ / java.security problem

### ISSUE THREAD

**Issue by pun-ky** [gradle/gradle#2708]
### Expected Behavior

Gradle working with SSHJ library with daemon running. Any help appreciated.

### Current Behavior

Integration of SSHj library only works when Gradle plugin using it is running with `--no-daemon` and/or ` -Dorg.gradle.debug=true` option.

### Context

I am trying to implement file download using SSHJ within one of tasks of my Gradle plugin.

### Steps to Reproduce (for bugs)

See: https://github.com/hierynomus/sshj/issues/347

### Your Environment

$ sh gradlew --version

------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64

**Comment by pun-ky** [comment]
yep, adding dependency to project using my plugin, solves problem 
```
    classpath group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.57'
```

but when I am adding it as compile dependency to plugin it is not working (same exception). still it will be not fully elegant that plugin users will have to add that dependency by their own. :/

**Comment by oehme** [comment]
Please provide a reproducible example project (attached as a zip or on GitHub). The information above is not enough for use to reproduce the problem.
