### ISSUE TITLE
BuildServiceParameters fails with convention plugins

### ISSUE THREAD

**Issue by dima-avdeev-jb** [gradle/gradle#27099]
### Current Behavior

BuildServiceParameters fails with convention plugins

`org.gradle.internal.snapshot.impl.IsolationException: Could not isolate value org.example.MyParameters_Decorated@33db25b2 of type MyParameters`

where MyParameters - it is my own interface
```Kotlin
interface MyParameters : BuildServiceParameters {
    val someInt: Property<Int>
}
```

### Expected Behavior

Better to support usage of BuildServiceParameters without workaround

### Context (optional)

I found workaround to call all paratemers in my custom BuildServiceParameters at least once.
All described in reproducer repository.

**Maybe where are some documentation that describe this behavior, or maybe related Issue already created?**

### Steps to Reproduce

Made reproducer here:
https://github.com/dima-avdeev-jb/gradle-build-service-parameters-issue

### Gradle version

8.4

### Build scan URL (optional)

https://gradle.com/s/voqsbvcxhvfcc

### Your Environment (optional)

 - MacOS 13.5.2 (22G91)
 - openjdk 17.0.8 2023-07-18 LTS

**Comment by cobexer** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by dima-avdeev-jb** [comment]
Is it good to access all properties at least once as a workaround for now?

**Comment by abstratt** [comment]
Seems same or similar to https://github.com/gradle/gradle/issues/19562

**Comment by eskatos** [comment]
FWIW, this impacts Kotlin and Compose plugins and makes their usage from convention plugins a pain because the build fails after having succeeded. Behavior seems to be different depending on which tasks are involved.

```
 * What went wrong:
Could not isolate value org.jetbrains.compose.internal.service.ConfigurationProblemReporterService$Parameters_Decorated@ccc1163 of type ConfigurationProblemReporterService.Parameters
> BuildScopeServices has been closed.
```

Exception is the same as in the buildscan from the description.

**Comment by LionZXY** [comment]
Since Kotlin 2.0 compose the plugin from JetBrains has been used for Android as well. 
So this problem is acute for android-pure Compose applications as well
