### ISSUE TITLE
Gradle fails to link binaries inside docker container (somehow generates the wrong path)

### ISSUE THREAD

**Issue by theofficialgman** [gradle/gradle#27105]
### Current Behavior

gradle produces the wrong path during the link operation when running inside a docker container on github actions
https://github.com/theofficialgman/Jamepad/actions/runs/6936137715/job/18867810888#step:39:62
simply use any project that required gradle to link with native code and add the container specifier to github actions eg: `container: ubuntu:20.04`

this does not happen when using gradle outside of the docker container

### Expected Behavior

gradle does not attempt to link the wrong path

### Steps to Reproduce

https://github.com/theofficialgman/Jamepad/tree/docker

### Gradle version

8.4

**Comment by theofficialgman** [comment]
blocking https://github.com/libgdx/Jamepad/pull/23

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
***
Please take the time to provide us with a minimal reproducer.

**Comment by theofficialgman** [comment]
still same linker error https://github.com/theofficialgman/Jamepad/actions/runs/8681588836/job/23804515917#step:39:74

sorry I am not capable of creating a minimal producer
CC @MrStahlfelge @SonicGDX
