### ISSUE TITLE
Introduce a method accepting a lambda on `Property`/`Provider`s if the corresponding value is present

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#27102]
### Expected Behavior

As titled, I'd like something like this

```
            fun <T> Provider<T>.ifPresent(block: (T) -> Unit) {
                if (isPresent)
                    block(get())
            }
```

or on `Property`

### Context

I'm querying tons of `Property`s right now and implemented this function manually, but I guess having this on stdlib could be useful for other people as well

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #13401

Please add your use case and 👍 to that issue.
