### ISSUE TITLE
HTTP/1.1 405 Method Not Allowed

### ISSUE THREAD

**Issue by YunlongYang** [gradle/gradle#2713]
CONNECT jcenter.bintray.com:443 HTTP/1.1
Host: jcenter.bintray.com
User-Agent: Gradle/4.1-rc-1 (Windows 7;6.1;amd64) (Oracle Corporation;1.8.0_60;25.60-b23)

HTTP/1.1 405 Method Not Allowed
Date: Sat, 12 Aug 2017 18:26:44 GMT
Server: Apache
Allow: GET,HEAD,POST,OPTIONS,TRACE
Content-Length: 235
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method CONNECT is not allowed for the URL /index.html.</p>
</body></html>

How can i fix this?

**Comment by bmuschko** [comment]
Could you please provide a simplistic build script that demonstrates the issue?

**Comment by YunlongYang** [comment]
Of course ，My project environment are presented below.
1.gradle 4.1-rc-1
2.Android Studio 3.0 Beta1
It never happens util I add a dependency like this:
implementation 'com.blankj:utilcode:1.8.0'

At first , I think it is IDE's problem,the I use console to execute the 'gradle build',it happends too,so I 
 capture packet by Wireshark.
The build script files are below:
1.[project-build.gradle](https://github.com/gradle/gradle/files/1228498/project-build.gradle.txt)
2.[module-build.gradle](https://github.com/gradle/gradle/files/1228503/module-build.gradle.txt)
The console's outputs are below:
   > Could not resolve com.blankj:utilcode:1.8.0.
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/blan
kj/utilcode/1.8.0/utilcode-1.8.0.pom'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/blankj/uti
lcode/1.8.0/utilcode-1.8.0.pom'. Received status code 405 from server: Method No
t Allowed
   > Could not resolve com.blankj:utilcode:1.8.0.
      > Could not get resource 'https://jcenter.bintray.com/com/blankj/utilcode/
1.8.0/utilcode-1.8.0.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/blankj/utilcode/1.8.0/
utilcode-1.8.0.pom'. Received status code 405 from server: Method Not Allowed
   > Could not resolve com.blankj:utilcode:1.8.0.
      > Could not get resource 'https://repo1.maven.org/maven2/com/blankj/utilco
de/1.8.0/utilcode-1.8.0.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/com/blankj/utilcode/1.8
.0/utilcode-1.8.0.pom'. Received status code 405 from server: Method Not Allowed

But When I visit the url(https://jcenter.bintray.com/com/blankj/utilcode/) in my browser , it can show the version list.

**Comment by YunlongYang** [comment]
It seems these websites not support HTTP/1.1 version's method CONNECT for now,is there some way to config the HTTP version or default method ?

**Comment by bmuschko** [comment]
The following build script works fine for me:

```
apply plugin: 'java-library'

repositories {
    jcenter()
}

dependencies {
    implementation 'com.blankj:utilcode:1.8.0'
}

task resolve(type: Sync) {
    from configurations.compileClasspath
    into "$buildDir/libs"
}
```

Can you try run the task `resolve` in your environment on the command line?

**Comment by bmuschko** [comment]
I am going to close the issue for now as I haven't back. Feel free to follow up as needed.

**Comment by YunlongYang** [comment]
I will try it later, too busy yesterday.

**Comment by YunlongYang** [comment]
![resolve -result](https://user-images.githubusercontent.com/9591161/29462647-a6c13358-8462-11e7-96aa-6fc26449b889.png)
It runs for so long time, I do not think it will end, ha ha.

**Comment by bmuschko** [comment]
I believe you have some network issue going on or a firewall. Try to turn off the firewall first and see if that helps.

**Comment by YunlongYang** [comment]
Neework is good,I can see the packet in Wireshark,
I do not know why it use HTTP /1.1 's CONNECT method to download the dependencies.
Could you use the Wireshark capture the packets when you add a new dependency?
I want to see the download HTTP method is GET or CONNECT.

**Comment by YunlongYang** [comment]
I fnd that it uses the port 80 to connect the server,but in its url ,it should be 443.
It may be the reason,but why it happens?

**Comment by YunlongYang** [comment]
I find the reason, in my gradle.properties file, I add the next properties to use the mirrors website.
`systemProp.https.proxyHost=mirrors.zzu.edu.cn`
`systemProp.http.proxyPort=80`
do you think it is the bug?

**Comment by bmuschko** [comment]
Not sure but you might have to set the proxy port for HTTPS explicitly via `systemProp.https.proxyPort`.
