### ISSUE TITLE
Gradle's published Javadocs are in a format that the `javadoc` tool in modern JDKs can't properly link to

### ISSUE THREAD

**Issue by pantherdd** [gradle/gradle#27149]
### Current Behavior

Gradle's current published Javadocs (https://docs.gradle.org/8.4/javadoc/)
* require HTML4 format fragments at the end of the links (e.g. [`Project.html#getName--`](https://docs.gradle.org/8.4/javadoc/org/gradle/api/Project.html#getName--)),
* but the supplemental files (`element-list`) trick the new, smart `javadoc` implementation into generating them in HTML5 format (e.g. [`Project.html#getName()`](https://docs.gradle.org/8.4/javadoc/org/gradle/api/Project.html#getName())),
* so the deep links don't work properly.

Also, Gradle's Javadocs are missing the links to JDK built-in classes.

### Expected Behavior

* Gradle plugin authors using the latest JDKs should be able to generate Javadocs that correctly deep-link into Gradle's Javadocs.
* Gradle's Javadocs should also have links to JDK built-in classes.

The possible solutions I see:
* Ideally, start using Java 17's `javadoc` and generate modern HTML5, which would also fix the links to JDK classes
  * https://github.com/gradle/gradle/blob/v8.4.0/build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleJavadocsPlugin.java#L106-L109
* If the docs have to stay in HTML4 format, remove the [`element-list`](https://docs.gradle.org/8.4/javadoc/element-list) file, keeping only [`package-list`](https://docs.gradle.org/8.4/javadoc/package-list), and use "offline linking" to add links to JDK built-in classes
  * [This `element-list` file being there is what misleads the new, smart `javadoc` implementation](https://github.com/openjdk/jdk17u-dev/blob/jdk-17.0.7+7/src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/toolkit/util/Extern.java#L435-L471) – if there is an `element-list`, then it calls `readElementList(in, urlpath, false, 0, false)`, otherwise it does the same with a `true` as the last parameter (`isOldFormDoc`)
  *  https://github.com/gradle/gradle/blob/v8.4.0/build-logic/documentation/src/main/groovy/gradlebuild/docs/GradleJavadocsPlugin.java#L113-L126
  * https://github.com/morganstanley/gradle-plugin-application/blob/v2.0.1/build.gradle.kts#L152-L216 (my previous solution using offline linking)

### Context (optional)

* Required here: https://github.com/morganstanley/gradle-plugin-application/pull/13
* Also relevant here: https://github.com/gradle/gradle/issues/18274#issuecomment-1825161020

### Steps to Reproduce

* Build a Gradle plugin using Java 17 toolchain (it can even be set to `--release 8`)
* Generate Javadocs for it via `javadoc -link 'https://docs.gradle.org/8.4/javadoc/'`
* Deep links to exact Gradle APIs won't work properly, because the URL fragment won't match the anchors in Gradle's Javadoc HTMLs

Reproduction: https://github.com/morganstanley/gradle-plugin-application/pull/13
* E.g. `build/docs/javadoc/com/ms/gradle/application/Application.html#finalizeProperties()` has this:
  > See Also:  
  > [`Property.finalizeValue()`](https://docs.gradle.org/8.4/javadoc/org/gradle/api/provider/Property.html#finalizeValue())

### Gradle version

8.4

**Comment by cobexer** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.
***
When fixing this we should make sure this is not a problem in the Gradle `Javadoc` task.
