### ISSUE TITLE
Configuration Cache can no longer be used since a few months

### ISSUE THREAD

**Issue by Obnotname** [gradle/gradle#27157]
### Current Behavior

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
203 problems were found storing the configuration cache, 6 of which seem unique.
- Task `:app:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer', a subtype of 'org.gradle.api.artifacts.ConfigurationContainer', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest`: cannot serialize object of type 'org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler', a subtype of 'org.gradle.api.artifacts.dsl.DependencyHandler', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest`: cannot serialize object of type 'org.gradle.api.internal.file.DefaultSourceDirectorySet', a subtype of 'org.gradle.api.file.SourceDirectorySet', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest`: cannot serialize object of type 'org.jetbrains.kotlin.gradle.plugin.PropertiesBuildService', a subtype of 'org.gradle.api.services.BuildService', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `compilationCompilerOptions` of `org.jetbrains.kotlin.gradle.plugin.sources.DefaultLanguageSettingsBuilder` bean found in field `languageSettings` of `org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSet` bean found in field `configuredKotlinSourceSets` of `org.jetbrains.kotlin.gradle.plugin.sources.android.KotlinAndroidSourceSetFactory` bean found in field `$factory` of `org.jetbrains.kotlin.gradle.plugin.sources.android.KotlinAndroidSourceSets$applyKotlinAndroidSourceSetLayout$2` bean found in field `val$action` of `org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1` bean found in field `delegate` of `org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction` bean found in field `actions` of `org.gradle.internal.ImmutableActionSet$SetWithFewActions` bean found in field `addActions` of `org.gradle.api.internal.collections.DefaultCollectionEventRegister` bean found in field `eventRegister` of `org.gradle.api.internal.FactoryNamedDomainObjectContainer` bean found in field `sourceSetsContainer` of `com.android.build.gradle.internal.dependency.SourceSetManager` bean found in field `sourceSetManager` of `com.android.build.gradle.internal.variant.LegacyVariantInputManager` bean found in field `$tmp0` of `com.android.build.gradle.internal.variant.LegacyVariantInputManager$3` bean found in field `val$action` of `org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1` bean found in field `delegate` of `org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction` bean found in field `actions` of `org.gradle.internal.ImmutableActionSet$SetWithFewActions` bean found in field `addActions` of `org.gradle.api.internal.collections.DefaultCollectionEventRegister` bean found in field `eventRegister` of `org.gradle.api.internal.FactoryNamedDomainObjectContainer` bean found in field `buildTypes` of `com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated` bean found in field `$extension` of `com.android.build.gradle.internal.tasks.factory.BootClasspathConfigImpl$1` bean found in field `isJava8Compatible` of `com.android.build.gradle.internal.tasks.factory.BootClasspathConfigImpl` bean found in field `value` of `kotlin.InitializedLazyImpl` bean found in field `bootClasspathConfig$delegate` of `com.android.build.gradle.internal.plugins.AppPlugin` bean found in field `this$0` of `com.android.build.gradle.internal.plugins.BasePlugin$dslServices$2$1` bean found in field `versionedSdkLoaderServiceProvider` of `com.android.build.gradle.internal.services.DslServicesImpl` bean found in field `services` of `com.android.build.gradle.internal.api.ApkVariantOutputImpl` bean found in field `value` of `groovy.lang.Reference` bean found in field `output` of `com.safedk.gradleplugin.configurators.ManifestConfigurator$_configure_closure1$_closure2` bean found in field `closure` of `org.gradle.api.internal.AbstractTask$ClosureTaskAction` bean found in field `actions` of task `:app:processDebugManifest` of type `com.android.build.gradle.tasks.ProcessMultiApkApplicationManifest`: error writing value of type 'org.jetbrains.kotlin.gradle.utils.FutureImpl'
> Future was not completed yet
### Expected Behavior

A normal successful build

### Context (optional)

Good Day,

I have the issue that since a few months my build always fails when using. I assume that it might be linked to one of my dependencies in use, however I found multiple other threads online having a similar issue. And honestly, I rather think this issue came up after a gradle update.
```
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
```

### Steps to Reproduce

Using 

```
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
```

### Gradle version

8.4

### Your Environment (optional)

Android Studio
Kotlin DSL (issue already existed prior)

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
To use the configuration cache you probably need updated versions of the android and kotlin plugins.
