### ISSUE TITLE
pluginManagement can not get the newest snapshot version for use

### ISSUE THREAD

**Issue by Jackyxie1** [gradle/gradle#27168]
### Current Behavior

![image](https://github.com/gradle/gradle/assets/55903201/3e820dcf-cdb0-425e-b650-12f94e7e814f) it is my plugins group convention project, in android project. It works well in maven artifacts push, the snapshot version was pushed successful every time, 
![image](https://github.com/gradle/gradle/assets/55903201/8d681828-ce00-42bc-9b5e-edad943c1c39), but in the android project, it works failed. it can always use the oldest version that i published first like xxx-SNAPSHOT. My android project settings.gradle.kts is 
![image](https://github.com/gradle/gradle/assets/55903201/ccb3621a-8716-479e-8371-b5bf712bd759)
The downloaded plugins jar never update below:
![image](https://github.com/gradle/gradle/assets/55903201/bbec376c-daf6-41f0-9cfd-2ac507c0d41a)

### Expected Behavior

Experted, it will use the newest version every time when i sync the android project, i know in library dependency it can use ```
configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}
```, but i can not found the solution in pluginManagement 

### Context (optional)

_No response_

### Steps to Reproduce

My description, thanks

### Gradle version

8.0

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

**Comment by Jackyxie1** [comment]
![image](https://github.com/gradle/gradle/assets/55903201/57d9fdc4-2b73-4989-8b87-785368d46765)
forgot my convention build.gradle.kts

**Comment by Jackyxie1** [comment]
> Sorry that you're having trouble with Gradle!
> 
> Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).
> 
> If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.
> 
> If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
> 
> The fix is to not cache changing versions:
> 
> ```kotlin
> resolutionStrategy.cacheChangingModulesFor(0, "seconds")
> ```

Your solution is dealing with cache changes for the normal dependency scope. I've already described earlier that it's not possible to update the snapshot version of the gradle plugin in this way, not the dependency.
![image](https://github.com/gradle/gradle/assets/55903201/72af5aae-63ff-4222-9dd0-90d14b9eb7fe)

**Comment by cobexer** [comment]
Sorry if this was not clear enough, but the `buildscript` also has configurations and allows you to configure the cache behavior as posted above:

in `settings.gradle.kts`
```kotlin
buildscript {
    configurations.all {
        resolutionStrategy.cacheChangingModulesFor(0, "seconds")
    }
}
```
Please let me know if this resolves your issue satisfactorily!

**Comment by Jackyxie1** [comment]
> Sorry if this was not clear enough, but the `buildscript` also has configurations and allows you to configure the cache behavior as posted above:
> 
> in `settings.gradle.kts`
> 
> ```kotlin
> buildscript {
>     configurations.all {
>         resolutionStrategy.cacheChangingModulesFor(0, "seconds")
>     }
> }
> ```
> 
> Please let me know if this resolves your issue satisfactorily!
Yes, I've tried adding this treatment of yours to the project's top-level build.gradle.kts, but it still doesn't work!

**Comment by Jackyxie1** [comment]
> > Sorry if this was not clear enough, but the `buildscript` also has configurations and allows you to configure the cache behavior as posted above:
> > in `settings.gradle.kts`
> > ```kotlin
> > buildscript {
> >     configurations.all {
> >         resolutionStrategy.cacheChangingModulesFor(0, "seconds")
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let me know if this resolves your issue satisfactorily!
> > Yes, I've tried adding this treatment of yours to the project's top-level build.gradle.kts, but it still doesn't work!

also settings.gradle.kts:)

**Comment by cobexer** [comment]
Ok, please take the time to create a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.
