### ISSUE TITLE
File system watching native run loop crashes on Windows 11

### ISSUE THREAD

**Issue by DayJun** [gradle/gradle#27185]
### Current Behavior

when i run `gradlew.bat test`, it fails and jvm crashes.

### Expected Behavior

successfully run tests

### Context (optional)

i can't use gradle to build my project, whichever command prompt or android studio

### Steps to Reproduce

clone https://github.com/pascal-lab/Tai-e-assignments
enter A1\tai-e\ folder
run `gradlew.bat clean test`
then the task failed, and crash log created.
crash log:
[hs_err_pid43976.log](https://github.com/gradle/gradle/files/13489408/hs_err_pid43976.log)

### Gradle version

i tried 7.4 and 8.4, both failed with the same reason.

### Your Environment (optional)

windows 11 22631.2428, jdk 17.0.2, gradle 7.4

**Comment by lptr** [comment]
@blindpirate could you please try to reproduce this?

**Comment by lptr** [comment]
Thanks @blindpirate. Let's close this for now. If @DayJun you can provide more information about how to reproduce this, please leave a comment and we can reopen the issue.
