### ISSUE TITLE
Work with JetBrains to get JetGradlePlugin compatible with Isolated Projects

### ISSUE THREAD

**Issue by 6hundreds** [gradle/gradle#27196]
- [x] Report existing issues to the shared Slack channel (ping Nikita and Sergei Vorobyov)
- [ ] IP safe access to project buildscript classpath #27195

**Comment by bamboo** [comment]
Waiting on [IDEA-341827](https://youtrack.jetbrains.com/issue/IDEA-341827) which in turn requires #22514

**Comment by alllex** [comment]
The upcoming IntelliJ IDEA release is expected to be free of incompatibilities.
We also track the existing violations in the sync smoke tests.
