### ISSUE TITLE
Gradle cannot load gradle enterprise plugin since 8.5-rc-4

### ISSUE THREAD

**Issue by ganadist** [gradle/gradle#27192]
### Current Behavior

```
$ git clone https://github.com/ganadist/VersionCodeDemo

$ ./gradlew :wrapper --gradle-version=8.5-rc-4 --no-configuration-cache
> Task :wrapper

BUILD SUCCESSFUL in 9s

$ ./gradlew :wrapper --gradle-version=8.5-rc-4 --no-configuration-cache
Downloading https://services.gradle.org/distributions/gradle-8.5-rc-4-bin.zip

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/ganadist/AndroidStudioProjects/VersionCodeDemo/settings.gradle' line: 15

* What went wrong:
Error resolving plugin [id: 'com.gradle.enterprise', version: '3.13.2']
> java.nio.file.NoSuchFileException: /Users/ganadist/.gradle/wrapper/dists/gradle-8.5-rc-4-bin/4toppiqfqviladkyw7xzeikpu/gradle-8.5-rc-4/lib/gradle-runtime-api-info-8.5.jar
```

### Expected Behavior

```
$ git clone https://github.com/ganadist/VersionCodeDemo

$ ./gradlew :wrapper --gradle-version=8.5-rc-3--no-configuration-cache
> Task :wrapper

BUILD SUCCESSFUL in 9s

$ ./gradlew :wrapper --gradle-version=8.5-rc-3 --no-configuration-cache
Downloading https://services.gradle.org/distributions/gradle-8.5-rc-3-bin.zip

> Task :wrapper UP-TO-DATE

BUILD SUCCESSFUL in 537ms
```

### Steps to Reproduce

Described at behavior.

### Gradle version

8.5-rc-4

### Gradle version that used to work

8.5-rc-3

### Your Environment (optional)

OS : MacOS 14.1.1
Java: OpenJDK 17

**Comment by Shahil093** [comment]
It seems like there's an issue with resolving the Gradle plugin 'com.gradle.enterprise' version 3.13.2.Follow these Steps:-

1.   Update the Gradle wrapper version in your 'gradle/wrapper/gradle-wrapper.properties '

2.  Update the version in your build.gradle file accordingly:-  

plugins {
    id 'com.gradle.enterprise' version '3.13.2'
}
3. Delete Gradle Cache:-

rm -rf ~/.gradle/caches/
rm -rf ~/.gradle/wrapper/

4. Check Gradle Distribution URL again if something is wrong!

5.  run the  ./gradlew :wrapper --gradle-version=8.5-rc-4 --no-configuration-cache  command again !

Thank you!

**Comment by ganadist** [comment]
I tried
1.  rm -rf ~/.gradle/wrapper/
2.  killall java

Then my error was disappeared.

Thank you for your comment.
