### ISSUE TITLE
Kotlin DSL property delegates for fixed-type configuration factory methods

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#27204]
### Expected Behavior

These should work to not need to specify the name as String like for other places in the Kotlin DSL, of course also as variant with `Action` parameter:
```kts
val foo by configurations.dependencyScope
val bar by configurations.resolvable
val baz by configurations.consumable
```

### Current Behavior (optional)

In Gradle 8.5 you have to duplicate the name as string:
```kts
val foo = configurations.dependencyScope("foo")
val bar = configurations.resolvable("bar")
val baz = configurations.consumable("baz")
```

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by big-guy** [comment]
To reduce the number of ways of doing things between Kotlin, Groovy and Java, we don't want to add these types of extensions.

**Comment by Vampire** [comment]
But that's inconsistent with the remaining Kotlin DSL. 😭
