### ISSUE TITLE
Running tests against JDK 9 module causes accessibility issues

### ISSUE THREAD

**Issue by sskorol** [gradle/gradle#2720]
### Summary

See original question: https://stackoverflow.com/questions/45673466/testng-tests-execution-against-jdk-9-module-causes-inaccessibleobjectexception

**Problem**: `src/test/java` packages are unexpectedly required to be accessible by main / external modules.

### Expected Behavior

Test packages are not required to be exported by the main module.

### Current Behavior

Seems like Gradle recognizes tests as a separate module and requests corresponding access by the main / external modules.

### Context

Trying to transform the following library to Java 9 module: https://github.com/sskorol/test-data-supplier

### Steps to Reproduce

See the following branch: https://github.com/sskorol/test-data-supplier/tree/35-java-9-support

When you try to run the tests, you'll get an exception mentioned on stackoverflow.
As a workaround I've tried to add `opens io.github.sskorol.testcases` with a dummy package within main module. It fixed the initial issue, but almost all the tests had failed due to similar problems, when main module requested access to test packages, that is weird (e.g. `joor` used in the main module couldn't see classes within `src/test/java`).

### Your Environment

 JDK 9 (build 9+181), Gradle 4.1, TestNG 6.11

**Comment by oehme** [comment]
@eljobe looking at the answer for the linked SO post, it seems that adding `--patch-module` has its own issues. I don't know enough about Java 9 to recommend a solution here.

**Comment by sskorol** [comment]
@oehme @eljobe I've applied Alan Bateman suggestion from one of SO answers, and came up with the following configuration:
```
test {
    inputs.property("moduleName", moduleName)
    doFirst {
        jvmArgs = [
                '--module-path', classpath.asPath,
                '--add-modules', 'ALL-MODULE-PATH',
                '--add-opens', 'io.github.sskorol/io.github.sskorol.testcases=testng',
                '--add-opens', 'io.github.sskorol/io.github.sskorol.testcases=joor',
                '--add-opens', 'io.github.sskorol/io.github.sskorol.datasuppliers=joor',
                '--add-opens', 'io.github.sskorol/io.github.sskorol.datasuppliers=testng',
                '--add-opens', 'java.base/java.util=streamex',
                '--add-opens', 'java.base/java.util.stream=streamex',
                '--patch-module', "$moduleName=" + files(sourceSets.test.java.outputDir).asPath
        ]
        classpath = files()
    }
}
```
Apart from module patching, we also need to specify a set of `--add-opens` commands for granting access to different test packages. Wondering if it could be handled automatically by Gradle?

Full configuration, which works with Java 9: https://github.com/sskorol/test-data-supplier/blob/35-java-9-support/build.gradle

**Comment by oehme** [comment]
Well, we could automatically open everything to JUnit/TestNG, but I don't see how we would automate this for other frameworks unless those frameworks publish some kind of metadata saying "I'm a testing framework doing fancy classloader things".

**Comment by sskorol** [comment]
@oehme what about adding some property or even interface (depending on meta-data complexity) to the `test` task's scope, so that other test frameworks could easily provide required info?

By default, this option could be enabled for TestNG / JUnit (or implemented in case of an interface).

I'm not familiar with Gradle internals / architecture, so unfortunately can't give more detailed thoughts on this.

**Comment by jjohannes** [comment]
`6.4` (current nightly [gradle-6.4-20200323230320+0000](https://services.gradle.org/distributions-snapshots/gradle-6.4-20200323230320+0000-bin.zip)) comes with support for compiling, running and testing Java modules.

This issue should not appear there anymore.

Hers is an example for how to run "whitebox" tests where the tests are defined in a module that patches the main module:

```
val moduleName = "org.module.b"

tasks.withType<JavaCompile> { modularClasspathHandling.inferModulePath.set(true) }
tasks.withType<Test> { modularClasspathHandling.inferModulePath.set(true) }

val patchArgs = listOf("--patch-module", "${moduleName}=${tasks.compileJava.get().destinationDirectory.asFile.get().path}")
tasks.compileTestJava {
    options.compilerArgs = patchArgs
}
tasks.test {
    jvmArgs = patchArgs
}
````
Full sample: https://github.com/jjohannes/gradle-jpms-experiments/tree/master/module-b

The reproducer in the description is no longer available, so I could not check this in detail. Please comment below or open a new issue if there is still a problem.
