### ISSUE TITLE
JavaDoc of `BuildFeature` claims you can inject it but not how

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#27205]
### Issue type

Wrong or misleading information

### Problem description

The JavaDoc of `BuildFeature` says you can inject an instance of it.
But it does not suggest how, and I doubt it is true, having a look at the implementation.
How wold you inject an instance of `BuildFeature` to check the state of configuration cache?
It is just a `DefaultBuildFeature` just like the one for project isolation.

My guess is, that this sentence should be on `BuildFeatures`.

Given that
```kts
interface BuildFeaturesProvider {
    @get:Inject
    val buildFeatures: BuildFeatures
}
println(objects.newInstance<BuildFeaturesProvider>().buildFeatures.configurationCache.active.get())
```
works as expected, supports this theory.

### Page with the problem

https://docs.gradle.org/8.5/javadoc/org/gradle/api/configuration/BuildFeatures.html

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
@alllex Is this just misplaced Javadoc or something else?

**Comment by alllex** [comment]
Thanks for reporting it!
The javadoc should have indeed been on the `BuildFeatures`
