### ISSUE TITLE
FileCopyDetails are incorrect if eachFile{} is called before rename{}

### ISSUE THREAD

**Issue by nishantghan** [gradle/gradle#2721]
Related forum post: https://discuss.gradle.org/t/how-to-access-final-name-of-a-file-specified-in-a-rename-closure-inside-eachfile-method/23673
### Expected Behavior

FileCopyDetails are correct irrespective of the order in which rename{} and eachFile{} are called.

### Current Behavior

FileCopyDetails are incorrect if eachFile{} is called before rename{}
### Context

We need to print a report of what all files are copied by a copy task with information such as final name of the file at destination, source file path etc. Currently if we call eachFile{} to achieve this, the 'getName()' method returns the name of the file before it is renamed by a rename{} closure which is called after eachFile{}. See example below.
### Steps to Reproduce (for bugs)

task A (type: Copy) {
     from 'abc.txt'
     into buildDir
     eachFile { fileCopyDetails ->
         println "Copying ${fileCopyDetails.getName()} from ${fileCopyDetails.getSourceName()}"}
}
 A.configure {
     rename 'xyz.txt'
 }
// Prints
Copying abc.txt from abc.txt
### Your Environment

Windows 7

**Comment by oehme** [comment]
Could you please attach a zipped-up example project (including Gradle wrapper, sample files...) so we can reproduce this as quickly as possible?

**Comment by nishantghan** [comment]
Attached.
[Gradle_issues_2721_reproduce.zip](https://github.com/gradle/gradle/files/1243287/Gradle_issues_2721_reproduce.zip)

**Comment by ov7a** [comment]
Still reproducible in 9.5.1
