### ISSUE TITLE
Gradle 8.5 deadlock

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/gradle#27221]
### Current Behavior

Upgrading from gradle 8.4 to 8.5 results in gradle hanging when running the following command
`./gradlew help --write-verification-metadata pgp,sha256 --export-keys --stacktrace`

This did not occur in the 8.5 rc-4 or previous release candidates.

### Expected Behavior

The command to succeed

### Steps to Reproduce

[hang.jstack.txt](https://github.com/gradle/gradle/files/13514183/hang.jstack.txt)

### Gradle version

8.5

### Your Environment (optional)

MacOS

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by NikolayMetchev** [comment]
there appears to be a workaround and that is to disable parallel

**Comment by big-guy** [comment]
@NikolayMetchev 8.5 RC4 and 8.5 GA contain the same changes, so I suspect this is an intermittent deadlock and may have been introduced in 8.4.

Could you try running this same command with 8.4 a few times?

**Comment by NikolayMetchev** [comment]
I can try, but I was definitely running it plenty on times with 8.4 and it never hung. It quite reliable hangs on 8.5

**Comment by jvandort** [comment]
This looks like this is caused by undeclared dependency resolution in the kotlinx.kover plugin: https://github.com/Kotlin/kotlinx-kover/blob/e8ffbda734f2210c8f9be56da2d61290c13e1c1d/kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/DependencyCheckListener.kt#L26-L56

**Comment by big-guy** [comment]
Can you check if this is still an issue with 8.8 or 8.9-RC1?

**Comment by NikolayMetchev** [comment]
This hasn't been an issue for quite some time

**Comment by jvandort** [comment]
Are you able to verify which version resolved the issue?

**Comment by NikolayMetchev** [comment]
no idea. Sorry.
