### ISSUE TITLE
Unify execution engines

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#27249]
Currently `ExecutionEngine` services are registered in two places:

- There is the "main" engine registered in the "Gradle" scope in [`ExecutionGradleServices`](https://github.com/gradle/gradle/blob/167fb9ac6126b4cbf12740c1897f2679c7ce6e89/subprojects/core/src/main/java/org/gradle/internal/service/scopes/ExecutionGradleServices.java#L132-L153). This one should be used for most everything. It supports the build cache and incremental/mutable execution.
- There is an "early" engine registered in [`DependencyManagementBuildScopeServices`](https://github.com/gradle/gradle/blob/167fb9ac6126b4cbf12740c1897f2679c7ce6e89/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DependencyManagementBuildScopeServices.java#L472-L512). This one is used to run some early transforms, i.e. things that need to happen before the `Gradle` instance is created for the build. It's somewhat unclear when this is, as `DependencyManagementBuildScopeServices` gets injected in different places during a build.

**Note:** Historically we also needed a project-scoped `ExecutionEngine` to allow for project-level customization of input normalization (see `Project.getNormalization()`). We don't need this anymore, since the project-bound fingerprinter is now injected via `UnitOfWork.getInputFingeprinter()`.

Having two different variants of the `ExecutionEngine` service in different scopes leads to confusion, as sometimes it's unclear which engine gets injected where. For an example of such confusion see:

- https://github.com/gradle/gradle/pull/27187

There is also the "problem" that we are creating a large number of these engines during the build, one early engine for each build script for example, and one for each subproject.

There are also some differences in behaviors between these engines:

- the "early" engine doesn't capture some of the build operations that the "main" one does
- it doesn't support build caching
- there is no "skip-when-empty" support in the "early" engine
- the "early" engine does not notify `OutputChangeListener`s when it executes work
- it also doesn't notify `WorkInputListener`s
- it doesn't support cancellation of the build

To solve these problems, we should merge the engines and have the single one be instantiated in `BuildTree` scope (or a future `BuildInvocation` scope). To do this we need to elevate some services that are currently not available in `BuildTree` scope.

These are the services we currently inject into the "main" engine, which is a superset of the services needed for the "early" engine:

## Problematic ones

* `BuildCacheController` Created in Gradle scope, should be elevated to `BuildTree` (or `BuildInvocation`), but this will be hard
* `OutputChangeListener` is `Gradle` scoped, should replace with global `FileSystemAccess.WriteListener` -- #27144, #27075

As a temporary or even permanent solution we could also "inject" some of these services via the `UnitOfWork`. However, if possible, it would be good to avoid circumventing `ServiceRegistry`.

* `BuildOutputCleanupRegistry` lives in the `Gradle` scope currently (https://github.com/gradle/gradle/pull/28706/ moves it to `Build`). We might want to expose this via `MutableUnitOfWork`, as it is a project-bound service needed for mutable work, and would make sense to keep it that way.
* `OutputFilesRepository` is now in `Gradle` scope. We could also expose this via `MutableUnitOfWork` the service is only used for that.

## Services not present in "early" engine but already in the right scope

* `BuildCancellationToken` is `BuildTree` scoped
* `GradleEnterprisePluginManager` lives in the `BuildTree` scope already
* `ExecutionStateChangeDetector` in `Global` scope
* `WorkInputListeners` in `Global` scope
* `OverlappingOutputDetector` in `Global` scope

## Services already used in the "early" engine

* `BuildInvocationScopeId` in `BuiltTree` scope (essentially proto-`BuildInvocation` scope already)
* `BuildOperationExecutor` in `BuildSession` scope
* `ClassLoaderHierarchyHasher` in `UserHome` scope
* `CurrentBuildOperationRef` in `Global` scope
* `Deleter` in `Global` scope
* `FileSystemAccess` there's both a `Global` one and a `BuildSession` scoped one in `VirtualFileSystemServices`, but both engines use the `BuildSession` scoped one
* `ImmutableWorkspaceMetadataStore` in `Global` scope
* `OutputSnapshotter` is `BuildSession` scoped
* `Problems` is `BuildTree` scoped
* `TimeoutHandler` in `UserHome` scoped
* `ValidationWarningRecorder` in `Global` scope
* `VirtualFileSystem` is `UserHome` scoped

---
cc: @gradle/bt-execution

**Comment by asodja** [comment]
Fixed with https://github.com/gradle/gradle/pull/29534
