### ISSUE TITLE
Optimize service discovery

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#2725]
We could probably make service discovery faster. When adding `commons-compress:1.14` (in 3d7598e21a137d1284a6b6e606d3b983190b33ff), a JAR of 518K with 295 files in it, we've increased [cold daemon startup](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/7630441:id/report-performance-performance-tests.zip%21/report/tests/cold-daemon-on-largeMonolithicJavaProject.html) by ~15 ms. [Moving a few hundred classes to two new libraries](https://github.com/gradle/gradle/compare/956af91...b8dba54) introduced another 15 ms regression.

This is probably due to service discovery having to process those extra files here:

https://github.com/gradle/gradle/blob/61548e36b41e214d5b806bd9cb059aefcec53a02/subprojects/base-services/src/main/java/org/gradle/internal/service/DefaultServiceLocator.java#L102-L136

We could probably do a couple of things to make things faster:

- do not look in libraries we know don't need to be looked at
- cache locators more

**Comment by lptr** [comment]
If splitting JARs increases load time, we could also consider merging all Gradle JARs into a single one.

**Comment by oehme** [comment]
There also this line:

https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/service/scopes/GlobalScopeServices.java#L149

Which seems inefficient, because the plugins classloader extends from the runtime classloader, so looking in both would add some unnecessary overhead.

**Comment by melix** [comment]
If this is really the culprit, I'm afraid it's not so easy to optimize. Basically, the costly call is `ClassLoader#getResources`, which will eventually delegate to the classloader implementation to find resources on classpath. From several tests, it seems that this method is not called so often (less than 10 times), but it's often either on `AppClassLoader` or `MixinLegacyTypesClassLoader` which delegates to the former.

The call to `getResources` is the one that knows whether it's a jar, or a directory, or a remote resource, being "scanned". We have no direct access to "the classpath".

I'll continue investigating this. @lptr can you point me at a performance test that highlights the problem? How did you find out the +15ms difference?

**Comment by lptr** [comment]
@melix: take a look at the cold daemon startup test: https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/7630441:id/report-performance-performance-tests.zip%21/report/tests/cold-daemon-on-largeMonolithicJavaProject.html

**Comment by oehme** [comment]
Issue moved to [gradle/gradle-private #923](https://github.com/gradle/gradle-private/issues/923) via [**ZenHub**](https://www.zenhub.com/)
