### ISSUE TITLE
False positive warning for Android plugins where version is not needed

### ISSUE THREAD

**Issue by ArcherEmiya05** [gradle/gradle#27258]
### Current Behavior

Some plugins specified in version catalog seems no longer detected as being used but removing it will also cause build/syncing error in the project.

<img width="938" alt="image" src="https://github.com/gradle/gradle/assets/38008900/483be4ca-f56a-4a48-934f-d865ee846d39">

### Expected Behavior

Not sure when this happens, it seems after updating to Gradle 8.2 cause it.

### Context (optional)

False positive

### Steps to Reproduce

Using plugins for Android project that is using classpath or do not need version when specifying un plugin block, thus using `id()` with `get().pluginId` instead of `alias()` for Kotlin DSL.

```
plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.android.kotlin) // This should be put before any Kotlin dependent plugin
    alias(libs.plugins.ksp)
    id(libs.plugins.parcelize.get().pluginId)
}
```

```
[versions]
kotlin = "1.9.0"


[plugins]

parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }  // Mark as unused despite being used and removing this will cause build error
```

### Gradle version

8.2

### Your Environment (optional)

Android

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/newIssue?project=IDEA.
