### ISSUE TITLE
CodeNarc plugin fails w/ Java 21 bytecode

### ISSUE THREAD

**Issue by efenderbosch-atg** [gradle/gradle#27252]
### Current Behavior

Upgraded project to Java 21 from 17. CodeNarc tasks fail with:

```Execution failed for task ':codenarcTest'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CodeNarcAction
   > BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 65
```

Using CodeNarc v3.3.0. Tried Gradle 8.4 and 8.5.

### Expected Behavior

CodeNarc can run against Java 21 bytecode.

### Steps to Reproduce

Relevant parts of `build.gradle.kts`:

```
plugins {
    val kotlinVersion = "1.9.21"
    id("org.springframework.boot") version "3.1.6"
    id("io.spring.dependency-management") version "1.1.4"
    kotlin("jvm") version kotlinVersion
    kotlin("kapt") version kotlinVersion
    kotlin("plugin.spring") version kotlinVersion
    kotlin("plugin.jpa") version kotlinVersion
    id("io.gitlab.arturbosch.detekt") version "1.23.4"
    id("org.jetbrains.kotlinx.kover") version "0.7.4"
    id("org.owasp.dependencycheck") version "8.4.2"
    id("io.github.taisuke-fujimoto.env-loader") version "0.0.1"
    groovy
    codenarc
}

val javaLanguageVersion: JavaLanguageVersion = JavaLanguageVersion.of(21)
kotlin {
    jvmToolchain(javaLanguageVersion.asInt())
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict", "-Xjvm-default=all")
    }
}

java {
    toolchain {
        languageVersion = javaLanguageVersion
    }
}

dependencyManagement {
    imports {
         mavenBom("org.spockframework:spock-bom:2.4-M1-groovy-4.0")
    }
}

dependencies {
    testImplementation("org.spockframework:spock-core")
    testImplementation("org.spockframework:spock-spring")
    testImplementation("org.apache.groovy:groovy:4.0.15")
    testImplementation("org.gmetrics:GMetrics-Groovy4:2.1.0")
}

codenarc {
    toolVersion = "3.3.0"
}
```

### Gradle version

8.5

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

As mentioned in CodeNarc [issue](https://github.com/CodeNarc/CodeNarc/issues/757), Java 21 support requires Groovy 5, which is not released yet. To support this in Gradle, we need to update both the Groovy version and the minimum JDK since Groovy 5 [requires at least JDK 11 to run.](https://groovy-lang.org/releasenotes/groovy-5.0.html#Groovy5.0-requirements)

**Comment by ov7a** [comment]
@peter-thomas-mgd Thanks for the details!

***

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by efenderbosch-atg** [comment]
Just confirming it does appear to be a bug w/ the plugin and not an issue w/ CodeNarc. I was able to get a custom task running w/ Java 21.

```
dependencies {
    codenarc("org.codenarc:CodeNarc:3.3.0-groovy-4.0")
}

tasks.register<JavaExec>("codenarc2") {
    mainClass = "org.codenarc.CodeNarc"
    args(
        "-basedir=src/test/groovy",
        "-rulesetfiles=file:config/codenarc.groovy",
        "-report=html",
        "-failOnError=true"
    )
    classpath = sourceSets.main.get().runtimeClasspath + configurations["codenarc"]
}
```

**Comment by dmurat** [comment]
@ov7a Any news about the progress? Tnx

**Comment by ov7a** [comment]
@dmurat Unfortunately, no. The plugin is not in focus for now.

**Comment by big-guy** [comment]
@octylFractal do you know if this is working now?

**Comment by octylFractal** [comment]
CodeNarc depends on an older version of Groovy which doesn't support Java 21. If you want that support, you need to [add a constraint](https://docs.gradle.org/current/userguide/dependency_constraints.html#sec:adding-constraints-transitive-deps) to the `codenarc` configuration that forces a version of Groovy 3/4 that does support Java 21.

We test CodeNarc on the latest Java version that Gradle supports compiling and testing on with the Groovy upgraded like this, so it should work.

**Comment by efenderbosch-atg** [comment]
For anyone else coming here from a search, my task above is ok, but will run every build regardless if any files have changed.

Probably want something like this added to the custom task:

```groovy
    inputs.files(fileTree("src/test/groovy").include("**/*.groovy"))
    outputs.file("build/reports/codenarc/test.html")
```
Adjust for your paths as needed.
