### ISSUE TITLE
RepositoryHandler functions for Maven Central snapshots

### ISSUE THREAD

**Issue by eygraber** [gradle/gradle#27267]
### Expected Behavior

It would be nice if I was able to add maven snapshot repositories using a function like `mavenCentral` in the `pluginManagement` block in `settings.gradle(.kts)`

```kotlin
pluginManagement {
  repositories {
    mavenCentralSnapshots(s01 = false)
    mavenCentralSnapshots(s01 = true)
  }
}
```

### Current Behavior

Currently, this is how I have to declare them. I have a convention plugin that makes it easier for the `dependencyResolutionManagement` block, but in `pluginManagement` I can't use those:

```kotlin
pluginManagement {
  repositories {
    maven("https://oss.sonatype.org/content/repositories/snapshots") {
      mavenContent {
        snapshotsOnly()
      }
    }

    maven("https://s01.oss.sonatype.org/content/repositories/snapshots") {
      mavenContent {
        snapshotsOnly()
      }
    }
  }
}
```

### Context

I've never once remembered the whole definition, so I always have to go hunt for it from another project. Since this isn't something that could be provided by a plugin, having it provided as part of Gradle would be very helpful.

**Comment by eygraber** [comment]
What about simply `mavenCentralSnapshots()`? Arguably it's more correct to add both repositories and not put the onus on the user to find out what the URL is, or which of the snapshot repositories the artifact is in. 

init scripts are not much better, especially since I typically use SNAPSHOT builds in one off cases, where it's just as inconvenient to use an init script as it is to hunt down the snapshot URL. The convenience of `mavenCentral` is apparent, and considering the boilerplate involved, `mavenCentralSnapshots()` would provide even more convenience.

**Comment by ov7a** [comment]
It's a quite unusual scenario to put snapshots in your plugins repositories. And it’s not something we want to promote.

**Comment by ov7a** [comment]
Can you please provide more details about your scenario? Why are you testing snapshots of plugins?

**Comment by eygraber** [comment]
Typically if there's a bug in a plugin that was fixed, or a new feature added, but a release wasn't made yet. I want to evaluate to see if it fixes the bug for me, or if there are any issues with the new feature, so I can get that reported to the maintainer before they cut a release. 

On rarer occasions there's a bug fix in a plugin that won't get released fast enough, so I might depend on snapshots temporarily until that release is made.

**Comment by ov7a** [comment]
With the details provided, we still think this shouldn't be a part of the Gradle API.
