### ISSUE TITLE
Maven publishing retries PUT but doesn't retry metadata download

### ISSUE THREAD

**Issue by hdeadman** [gradle/gradle#27262]
### Expected Behavior

Using options like 
```
-Dorg.gradle.internal.network.retry.max.attempts=5
-Dorg.gradle.internal.network.retry.initial.backOff=5000
```
will cause maven publisher to retry PUT operations that fail with network errors that appear recoverable but if a server you are publishing to is struggling, the failure can occur while retrieving metadata and that is not retried. If it retried using the same retry logic, that would make publishing more likely to succeed.

### Context

When the Apereo CAS project publishes snapshots to the Sonatype Nexus repository there are occasional failures (e.g. a 502 failure presumably from a proxy in front of Nexus when the Nexus server is under load or possibly restarting after a crash). The retry logic in gradle was enabled but then it still failed and the failure occurred during retrieval of existing metadata from the remote maven repository.

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

***

Thanks for adding a PR for fixing that!
