### ISSUE TITLE
Plugin artifacts not deployed to plugin repository

### ISSUE THREAD

**Issue by johndevs** [gradle/gradle#2726]
The plugin artifacts show up correctly on https://plugins.gradle.org/plugin/com.devsoap.plugin.vaadin but they are not in the repository.

```
 Could not find com.devsoap.plugin:gradle-vaadin-plugin:1.2.2.
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.pom
         https://plugins.gradle.org/m2/com/devsoap/plugin/gradle-vaadin-plugin/1.2.2/gradle-vaadin-plugin-1.2.2.jar
```

### Expected Behavior
The artifacts should be in the repository

### Current Behavior
Artifacts are not in the repository.  This can be verified by accessing https://plugins-artifacts.gradle.org/com.devsoap.plugin/gradle-vaadin-plugin/1.2.2/3c98b960693f5dea7f35b23fc7e6e8a0bdb0343560634aaa6672df70ba0439fa/gradle-vaadin-plugin-1.2.2.pom manually

### Context
Currently a blocker for us since we cannot use the plugin.

### Steps to Reproduce (for bugs)
build.gradle
```
plugins {
  id "com.devsoap.plugin.vaadin" version "1.2.2"
}
```
Run **gradle dependencies**

**Comment by rhart** [comment]
@johndevs can you confirm what version of the plugin-publish plugin you are using?  You need to be using the latest version https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573

**Comment by johndevs** [comment]
@rhart I can confirm I am using an old one, 0.9.1 to be specific. So most likely the same issue. I'll update the plugin and try again.

Would it be possible to make the build break if the plugin version is no longer compatible with the plugin site it tries to upload to? It would help a lot in noticing if something needs to get updated.

**Comment by rhart** [comment]
@johndevs yes, there are some improvements being worked on.

I believe I need to delete the version you have published before you try again.  Can you confirm it's ok for me to do this?

**Comment by johndevs** [comment]
@rhart Yes, sure, go ahead, I'll rebuild/deploy them again once they are gone

**Comment by rhart** [comment]
@johndevs 1.2.2 has been removed, please re-publish when you're ready

**Comment by johndevs** [comment]
@rhart Re-published the artifacts and looks like it is working again. Thanks for your help!
