### ISSUE TITLE
Ensure classified artifacts remain distinguishable after transformations

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#2727]
When publishing to a Maven repository, library authors often use a classifier to denote different variants of their library, e.g. a production and testing variant. Currently this information is lost in the `ResolutionResult` API. Two artifacts with different classifiers will look as if they had exactly the same metadata.

This affects the new Android plugin, as it has no simple way of telling whether it has packaged an artifact into an AAR before, when two different classified variants are in the dependency graph. Using `getFile()` is not an option, as the plugin also uses dependency transformations to split artifacts into different parts (like classes and resources).

A simple first step to improve this would be to map the classifier 1:1 to a variant attribute. This is not very descriptive, but would at least allow plugin authors to make a decision how they want to handle classified artifacts. Later on we could allow this mapping to be configurable.

**Comment by Alex-Vol** [comment]
I am very excited to see this on the board. I have implemented a private plugin that makes such a feature for Ivy publishing. I intend to substitute the usage of my private implementation with this when I upgrade to version 4.3. I will try to follow the development of the 4.3 release candidates to validate this feature with our current multi module project.

**Comment by oehme** [comment]
I've adjusted the title to reflect the actual use case better. After some investigation the problem seems to be that the original classifier of an artifact is not kept during transformation. As a result, two artifacts with different classifiers can be transformed into two artifacts with the same `ComponentArtifactIdentifier`, even though their content is different.

Maintaining the classifier in the transformed artifact should fix that, as the `ComponentArtifactIdentifier` will then be different.

**Comment by oehme** [comment]
This is on `release` now.
