### ISSUE TITLE
build failing in local environment because of version locking

### ISSUE THREAD

**Issue by hlms** [gradle/gradle#27276]
### Issue type

Other

### Problem description

After the addition of [gradle version locks](https://docs.gradle.org/6.9.2/userguide/dependency_locking.html) in code repository by some other developer in my organization, now the build is failing in my machine:

```
/c/git/nextgenRepository/myProject (dev)
$ ../gradlew assemble
...
> Task :myProject:compileJava FAILED
:myProject:compileJava took 30ms
Task timings:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myProject:compileJava'.
> Could not resolve all files for configuration ':myProject:compileClasspath'.
   > Did not resolve 'com.google.guava:guava-parent:32.1.2-jre' which is part of the dependency lock state
BUILD FAILED in 1s
23 actionable tasks: 1 executed, 22 up-to-date

```

When I compared dependencies of myProject from my machine (which has issue) and that from another developer's machine (where it's working fine), found the following difference:
<img width="960" alt="comparison-of-dependencies-gradle" src="https://github.com/gradle/gradle/assets/10277817/cb2b7a90-5040-4605-9520-47aa198113ce">
 

1. working.txt is where the build (../gradlew assemble) is passing. "com.google.guava:guava:11.0.2" is fetching guava-parent.
2. issue.txt is where the build (../gradlew assemble) is failing with the aforementioned error. The same version of the library "com.google.guava:guava:11.0.2" isn't fetching guava-parent.

When we check the dependencies on maven: https://mvnrepository.com/artifact/com.google.guava/guava/32.1.2-jre : indeed, it doesn't have dependencies on "guava-parent". Details on maven site are consistent with the dependencies in my machine.
<img width="604" alt="dependencies-listed-in-maven" src="https://github.com/gradle/gradle/assets/10277817/836e7278-fe69-4af8-98b2-a61a462a5463">

Dependencies listed in https://repo1.maven.org/maven2/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.pom : 
<img width="373" alt="dependencies-listed-in-pom" src="https://github.com/gradle/gradle/assets/10277817/9998cc44-8be3-4dd0-ba70-eacbd605feeb">
 

Then how come it's different in everyone else's machine? It's working fine in everyone else's machine. Caching somewhere? How to resolve this issue in my machine?

### Context (optional)

Builds are failing in my local. As a workaround, I've disabled the version locking in my machine with the following statement in build.gradle:

`lockMode = LockMode.LENIENT`

```

$ ./gradlew --version

------------------------------------------------------------
Gradle 6.9.2
------------------------------------------------------------

Build time:   2021-12-21 20:18:38 UTC
Revision:     5d94aa68c0fdbe443838bb977080e3b9f273e889

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.16.1 (Amazon.com Inc. 11.0.16.1+9-LTS)
OS:           Windows 11 10.0 amd64
```

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

**Comment by hlms** [comment]
Alright, I've created a post on forum: https://discuss.gradle.org/t/build-failing-in-local-environment-because-of-version-locking/47173 .
