### ISSUE TITLE
Use artifact transform to perform build script compilation and instrumentation

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#27274]
Right now we have very different implementation how compilation and instrumentation works for Kotlin and Groovy build script. Kotlin uses execution engine and Groovy uses some custom implementation.

Looking at the compilation it could be expressed as an artifact transform. We have a source of a build script with dependencies, and then we change source to a .class. 

Additionally we should also separate runtime and compile classpath. With that we could the instrument the runtime classpath, while compile classpath would have original jars. That requires some more changes and it seems it's not straight forward.

A whole compile and instrument process could then be expressed as:
1. create a configuration with build script artifact with its dependencies
2. request a "compile view" of such configuration -> compilation happens
3. request a "runtime view" of such configuration -> instrumentation happens
4. use runtime view to run the build script

**Comment by lptr** [comment]
I just discussed this with @wolfs and @adammurdoch and we agreed that we probably shouldn't go as far as doing the whole process via transforms, at least not for now. We should definitely script compilation and instrumentation of the compiled code to `UnitOfWork`s, though.

**Comment by asodja** [comment]
We decided to not use artifact transform for now. Replaced by https://github.com/gradle/gradle/issues/27705.
