### ISSUE TITLE
Performance Tests lead to 404

### ISSUE THREAD

**Issue by NoPhaseNoKill** [gradle/gradle#27289]
### Issue type

Wrong or misleading information

### Problem description

When trying to access the following endpoint from your docs from gradle/performance, the page 404's

***
Report
There is a performance:report task that generates a static HTML report from the contents of the database in ~/.gradle-performance-test-data. This report allows the results over time to be visualized.

The report for the most recent test suite run against master is [here](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/.lastFinished/report-performance-performance-tests.zip%21/report/index.html?branch=master)
***

![image](https://github.com/gradle/gradle/assets/4100222/a6f641d6-3d6e-4228-bc10-0fd7b07450df)

### Context (optional)

I'm trying to see whether or not a change will impact file walking for performance. Local testing seems promising, but without access to the performance metrics, it's hard to know whether or not I'm making any headway.

### Page with the problem

https://github.com/gradle/gradle/tree/master/subprojects/performance

**Comment by ljacomet** [comment]
Resolved with:
* #27667
