### ISSUE TITLE
enforcedPlatform doesn't work with version catalog entries

### ISSUE THREAD

**Issue by staktrace** [gradle/gradle#27282]
### Current Behavior

Swapping out a string dependency (e.g. `"foo:bar:version"`) for the equivalent version catalog entry (`libs.fooBar`) causes a significant change in behaviour. In particular, if this dependency is passed to `enforcedPlatform` it does not behave as intended at all.

### Expected Behavior

Doing `enforcedPlatform(libs.fooBar)` should produce the same result as `enforcedPlatform("foo:bar:version")`, assuming `fooBar = "foo:bar:version"` is in the version catalog.

### Context (optional)

I'm in the process of converting a bunch of repos from using string-based dependency declarations to version catalogs, and the behaviour in some cases has change subtly, causing build breakages.

### Steps to Reproduce

https://github.com/staktrace/20231204-dep-resolution is a self-contained minimal reproducer. Please follow the instructions in the README to reproduce the problem. For convenience, the build scan at https://scans.gradle.com/s/2v7k4svukyxps/dependencies?configurationFilter=WyJydW50aW1lQ2xhc3NwYXRoIl0&dependencies=wire-bom&expandAll shows the dependencies - note how `version-catalog-default` resolves `wire-bom` to a different value than the other two, this is what I'm claiming is a bug.

### Gradle version

7.6.3

### Build scan URL (optional)

https://scans.gradle.com/s/2v7k4svukyxps/dependencies?configurationFilter=WyJydW50aW1lQ2xhc3NwYXRoIl0&dependencies=wire-bom&expandAll

**Comment by autonomousapps** [comment]
I tested this with Gradle 8.5, and the behavior remains the same.

**Comment by ChristianCiach** [comment]
We just got bitten by this. 

@ov7a When you say "this area of Gradle" you probably mean the version-catalog component. But I would argue that this is a broken dependency resolution, what I assume to be a core component of Gradle. Please don't sleep on this issue. It's a really nasty one.

**Comment by cobexer** [comment]
@gradle/bt-jvm sending this to you as the latest comment resonates with us and we want to have you take a look at this now.
