### ISSUE TITLE
gradle init produces settings.gradle file with wrong multi-project build documentation link

### ISSUE THREAD

**Issue by jnehlmeier** [gradle/gradle#27306]
### Issue type

Polishing

### Problem description

Using `gradle init` with
- java
- application
- multi-module
- groovy

results in a `settings.gradle` file which does contain
```
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */
```

I guess the link is wrong as it points to configuring swift projects. I assume the correct link would be https://docs.gradle.org/8.5/userguide/intro_multi_project_builds.html

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
