### ISSUE TITLE
Gradle takes to long to install

### ISSUE THREAD

**Issue by EW2010** [gradle/gradle#27337]
### Issue type

Other

### Problem description

Every time I create a new project it takes about half an hour to install gradle. That's a bit much. I only use gradle because of this if I really have to :(

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

There is no actionable information in this report.
