### ISSUE TITLE
Gradle + IBM Semeru + Windows hang on start deamon

### ISSUE THREAD

**Issue by sebastiansIT** [gradle/gradle#27348]
### Current Behavior

When using IBM Semeru 17.0.8.1 on Windows, the gradle daemon hangs. 
On MacOS the gradle daemon works fine with IBM Semeru 17.0.8.1. Also Gradle works fine on Windows with any other JRE I tried (Correto, Zulu...)

### Expected Behavior

The IBM setup should work as each other.

### Context (optional)

IBM tells me after analysing some memory dumps: 
"All the dumps uploaded shows below java and native stacks , it looks like a hang while loading a Native library."
and
"The library that is being loaded is “C:\projects\.gradle\native\e376f236ea51e6404a007f0833ffe2c6e607c4080706a723a18a27aeea778392\windows-amd64\native-platform-file-events.dll”
We don’t see any java specific issue here, could you please involve owners of this lib to investigate further on why the issue happens while loading this library?"

### Steps to Reproduce

Configure a Windows System to use Gradle 7.5.1 with the JRE 17.0.8.1 from IBM (https://developer.ibm.com/languages/java/semeru-runtimes/downloads/). Start a Gradle command (i.E. gradle build)
You get two lines on the console than nothing:

    Executing 'build'...
    Starting Gradle Daemon...

### Gradle version

7.5,1

### Your Environment (optional)

* Windows 10
* Gradle 7.5.1 (without Wrapper)
* IBM Semeru JRE 17.0.8.1

**Comment by ov7a** [comment]
We are observing multiple issues with IBM Semeru:
* https://github.com/gradle/gradle/issues/27273
* https://github.com/gradle/gradle/issues/27261
* https://github.com/gradle/gradle/issues/26224

So unless you can reproduce this with other JDK we would treat it as a IBM Semeru problem.

**Comment by bmarwell** [comment]
@ov7a I do not agree. IBM Semeru is TCK verified.

Unless you can show us WHY it is a Semeru problem (i.e. some method is ill-behaving, not according to specifications), this must be treated as Gradle bug. Closing this without any investigation does not seem to be very user friendly.

**Comment by ov7a** [comment]
Well, we see a lot of issues with Semeru and I don't feel it's worth investing for now. Can you reproduce the issue with another JDK?
