### ISSUE TITLE
Help flag should show task help when task is specified

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#27343]
### Expected behavior

The following invocation should produce help for the `init` task (or any specified task)
```
$ gradle init --help
```

This is a common pattern in almost all command line tools.

### Current behavior

The task is ignored, and general "Gradle help" is shown. Additionally, no actionable guidence is provided as to actually how to get the help for the specified task.

The "correct" way current is to use a "help" task and specify the task for which help is needed:
```
$ gradle help --task init
```

This is virtually non-discoverable, unless the user already knows about this. And even then, it is awkward, because it contradicts help-requesting practices of almost all CLI tools.

### Suggestion

We could make the global `--help` flag aware of the presense of the task selectors and automatically traslate the command into the one requesting help for the specified task.

**Comment by ov7a** [comment]
See comment from @big-guy 
* https://github.com/gradle/gradle/pull/30275#pullrequestreview-2267351342

Essentially, this means closing this issue in favor of:
* https://github.com/gradle/gradle/issues/13243
