### ISSUE TITLE
Create registry of problem categories exposed via Problems API

### ISSUE THREAD

**Issue by donat** [gradle/gradle#27355]
The documentation should have a section listing all problem categories that the tooling clients should expect.

**Comment by hegyibalint** [comment]
Remind me why we couldn't at this point make an enum for the predefined categories?
It would allow us to make a builder method, that could use this well-defined enum, and make it discoverable by our users.

**Comment by donat** [comment]
That's certainly one way to do it. I'm a bit uncertain about the precise modeling (i.e. how to change ProblemSpec) but the enum seems a good enough approach.
