### ISSUE TITLE
Changes in symlinked Java (and Kotlin as well) sources are not detected within enabled VFS

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#27373]
### Current Behavior

Changes to the symlinked sources are not detected within enabled VFS

### Expected Behavior

Changes to the symlinked sources are detected within enabled VFS

### Context (optional)

The issue was initially reported on Kotlin's YouTrack as [KT-62571](https://youtrack.jetbrains.com/issue/KT-62571). The problem arises when one configures the source set to be a symlink to another directory. Gradle fails to detect changes and marks the task as UP-TO-DATE, even if there are changes. This issue persists for both Java and Kotlin. Disabling the VFS fixes the problem.

### Steps to Reproduce

See the README at https://github.com/ALikhachev/gradle-symlinks-vfs-reproducer

### Gradle version

8.5

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by lptr** [comment]
This is a duplicate of https://github.com/gradle/gradle/issues/26201. Gradle 8.7 will ship with a fix.
