### ISSUE TITLE
Allow convention mapping to work with multi-valued lazy property types

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#27380]
In https://github.com/gradle/gradle/pull/24582 we enabled `ConventionMapping.map()` to work with properties that are of type `Property` to be assigned a convention value. We did this to enable a smoother migration to lazy properties, and towards the deprecation/removal of `ConventionMapping` in the future.

We should allow doing the same for `ListProperty`, `SetProperty` and `MapProperty`.

---
cc: @gradle/bt-execution

**Comment by bamboo** [comment]
Fixed via #27531
