### ISSUE TITLE
Make is clear that adding a dependency to the checkstyle configuration causes the default com.puppycrawl.tools:checkstyle dependency to back off

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#27397]
### Issue type

Missing information

### Problem description

The [documentation for the `checkstyle` configuration](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_dependency_management) says that it contains "the Checkstyle libraries to use". By default, it contains a dependency on `com.puppycrawl.tools:checkstyle` with a version derived from the Checkstyle extension's tool version. If another dependency is added to this configuration, the `com.puppycrawl.tools:checkstyle` dependency is lost. The documentation does not make this clear and does not explain how to add a dependency to the `checkstyle` configuration while also retaining a dependency on `com.puppycrawl.tools:checkstyle`.

### Context (optional)

I was trying to add some extensions to the classpath that's used to run Checkstyle. These extensions are an addition to rather than a replacement for `com.puppycrawl.tools:checkstyle`. 

### Page with the problem

https://docs.gradle.org/current/userguide/checkstyle_plugin.html

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

***

The more advanced solution might be to have a way to refer to the default checkstyle dependency without the need to figure out the coordinates.

**Comment by wilkinsona** [comment]
Yes, that would be nice. Even nicer if configuring the tool version continued to have an effect.
