### ISSUE TITLE
Proxy misleading .

### ISSUE THREAD

**Issue by q2333gh** [gradle/gradle#27393]
### Current Behavior

option1: i set  this in my gradle.properties.
```
 systemProp.http.proxyHost=192.168.3.22
systemProp.http.proxyPort=25526
systemProp.https.proxyHost=192.168.3.22
systemProp.https.proxyPort=25526
```

or option2: 
```bash
./gradlew -Dhttp.proxyHost=192.168.3.22 -Dhttp.proxyPort=25526 -Dhttps.proxyHost=192.168.3.22:25526 -Dhttps.proxyPort=25526 build
```

they both lead to another proxy to 192.168.235.1:25526  .

I try to ./gradlew --stacktrace . but fail to find how gradle using read  proxy file . 
[gradle_err.log](https://github.com/gradle/gradle/files/13658314/gradle_err.log)

And none of my other program in shell will using 192.168.235.1:25526 . such as curl wget  git ... 

### Expected Behavior

It should use proxy i set above .

### Steps to Reproduce

by exec `./gradlw`

### Gradle version

8.3

### Your Environment (optional)

------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------

Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.9 (Private Build 17.0.9+9-Ubuntu-122.04)
OS:           Linux 6.2.0-37-generic amd64

**Comment by q2333gh** [comment]
```bash
btwl@btwl-virtual-machine ~/.gradle> cat gradle.properties 
## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Mon Nov 27 12:01:58 CST 2023
systemProp.http.proxyHost=192.168.235.1
systemProp.http.proxyPort=25526
systemProp.https.proxyHost=192.168.235.1
systemProp.https.proxyPort=25526
btwl@btwl-virtual-machine ~/.gradle> pwd
/home/btwl/.gradle

``` 


everythings` done . wondering on the internet , took me a week to fix this .

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
