### ISSUE TITLE
Convert remaining docbook userguide docs to asciidoc

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2740]
### Context
We have several remaining docbook XML docs. Most user guide content is now in Asciidoc. Finishing this conversion is the first step toward unifying our documentation infrastructure.

**Comment by lptr** [comment]
FTR, this is already in (slow) progress.

**Comment by wolfs** [comment]
We just converted the last chapters: #2989.
@eriwen Please have a look if there is something left to do for the conversion. We can start planning out the next steps how to continue improving our documentation toolchain..

**Comment by eriwen** [comment]
Closing as complete. Thanks @lptr and @wolfs!

**Comment by bmuschko** [comment]
Nice work, @lptr and @wolfs. I think we should also convert the release notes to AsciiDoc. Do you know of any technical reason that would block the migration?

**Comment by lptr** [comment]
I believe @eriwen has some more complex plan to improve on our release notes. Might not be worth moving to Asciidoc before that. (Although we could use the line number markers when explaining new features.)

**Comment by eriwen** [comment]
I haven't quite figured out yet what exactly what we want to do with release notes. I'd only suggest a switch to asciidoc in the short term if it's easy to implement and we don't lose any functionality. 

Don't forget we still have the DSL reference in Docbook as well.
