### ISSUE TITLE
Kapt error with Gradle 8.x referring a jar in libs/ folder in android project

### ISSUE THREAD

**Issue by alberto-cappellina** [gradle/gradle#27401]
### Current Behavior

When import a JAR file built with OpenApi Generator (Maven plugin) with Android Gradle Plugin 8.x I have this errror

 Could not load module <Error module>

* What went wrong:
Execution failed for task ':app:kaptGenerateStubsMockDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

(no more details actually)

### Expected Behavior

With previous version (eg. 7.x) importing the jar in code base was not a problem

### Context (optional)

We are generating a new library with openapi generator and we should use it but at the moment we cannot even launch the application.

### Steps to Reproduce

(not sure is reproducible)
1. define an open api specification
2. use openapi generator configured for use kotlin template
3. import jar into project
4. try launch gradle assemble

### Gradle version

8.1.4

### Gradle version that used to work

7.4.2

### Build scan URL (optional)

https://scans.gradle.com/s/4d7dra33bme2o

### Your Environment (optional)

OSX Ventura 13.4
Android Studio Giraffe patch 4

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

Please open such Kotlin-related issues on the JetBrains YouTrack at https://kotl.in/issue.
