### ISSUE TITLE
Add an `org.gradle.refreshDependenciesAfterDays=N` option

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#27410]
### Expected Behavior

Add an option to "refresh" dependencies that haven't been refreshed in N days.
Maybe a property called `org.gradle.refreshDependenciesAfterDays=N`

If there is a local artifact that has not been "refreshed" (in the same way that `--refresh-dependencies` works) in the last N days, then it gets refreshed on the next build. 

This should also work with `gradle/gradle-build-action` dependency cache. 

### Current Behavior (optional)

`--refresh-dependencies` refreshes all dependencies no matter how recently they have been refreshed. 

I want to refresh dependencies only if they have not already been refreshed recently. 

### Context

This is useful if you have a maven repro proxy that might block some artifacts after some point in time. 

Maybe the artifact was available yesterday, but blocked today. (blocked for security or licensing reasons)
If the artifact is cached, the build will continue to work even if the dependency is blocked.

I want gradle to re-check the dependency every N days. If there has been a successful check in the last N days and the artifact is currently not available (4xx) then the build should fail. 

See https://github.com/gradle/gradle-build-action/issues/977

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

The only thing this offers compared to `--refresh-dependencies` is hiding a broken build up to N days. If your repository is changing, then consider marking dependencies as [changing](https://docs.gradle.org/current/userguide/dynamic_versions.html#sub:declaring_dependency_with_changing_version) and configure the refresh time.

For those reasons, this feature should not be part of Gradle.

**Comment by yogurtearl** [comment]
Ah, yeah, `changing` seems like the right concept here, but would like to be able to make every dependency "changing" by default. 

Maybe a `org.gradle.changing.by.default=true` property to make everything "changing" unless explicitly set to not changing? 

Also, in my case, "changing" is a function of the repo an artifact was loaded from, so setting a specific `repostitory` as "changing" to treat everything loaded from that repo as "changing" would be helpful.

**Comment by ov7a** [comment]
I think your use case is pretty specific. To save keystrokes, consider handling this with a plugin or a helper function.
