### ISSUE TITLE
More flexible `BuildCacheEntryWriter` APIs

### ISSUE THREAD

**Issue by joshfriend** [gradle/gradle#27432]
### Expected Behavior

It would be great to expose the internal `File` object of `BuildCacheEntryWriter` directly, or at least an `InputStream` that is more directly compatible with [the `RequestBody` API from the S3 SDK](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/sync/RequestBody.html).

### Context

The API for writing to various build cache backends is very simple and as a result is somewhat cumbersome to work with.

For example, [the androidx s3 build cache implementation](https://github.com/androidx/gcp-gradle-build-cache/blob/d2222025c0dba22c0d6f5a7aed7253c6f50083fa/s3buildcache/src/main/kotlin/androidx/build/gradle/s3buildcache/S3BuildCacheService.kt#L74-L78) has to use `writeTo()` to copy the cache contents to a `ByteArraytOutputStream` which is then passed as an array to the S3 SDK [which makes a new copy of it](https://github.com/aws/aws-sdk-java-v2/blob/9bcb8c789829768b44200b619b5e3f1735c12eda/core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java#L171). [This other implementation](https://github.com/burrunan/gradle-s3-build-cache/blob/f84cc068696139563d6cefdd08e3bd8435f89ed9/src/main/kotlin/com/github/burrunan/s3cache/internal/BuildCacheEntryWriterExtensions.kt#L6-L13) uses reflection to access the `file` property and pass that to the S3 SDK directly which avoids copying byte arrays. It has a fallback to the same method as the androidx implementation if this field is ever removed.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by joshfriend** [comment]
Would you at least consider providing an `InputStream`? I get why you wouldn't show the `File` directly, but the stream is pretty abstracted.

**Comment by joshfriend** [comment]
#36671 in 9.7 addresses this nicely, thank you :)
