### ISSUE TITLE
ComponentMetadataRule is not triggered by dependencies without a version

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27435]
### Current Behavior

ComponentMetadataRule is not triggered by dependencies without a version

### Expected Behavior

ComponentMetadataRule is ~not~ triggered by dependencies without a version

### Context (optional)

I want to use a ComponentMetadataRule to align dependencies using a virtual platform, but the ComponentMetadataRule is not triggered when the dependencies do not have a version.

### Steps to Reproduce

```kotlin
// build.gradle.kts

repositories {
  mavenCentral()
}

val dokkaPluginsClasspath: Configuration by project.configurations.creating {
  isCanBeResolved = true
  isCanBeConsumed = false
  isVisible = false
}

abstract class FooRule : ComponentMetadataRule {
  override fun execute(context: ComponentMetadataContext): Unit = with(context) {
    println("FooRule is active")
  }
}

dependencies {
  components.all<FooRule>()

  dokkaPluginsClasspath("org.jetbrains.dokka:all-modules-page-plugin")
//  dokkaPluginsClasspath("org.jetbrains.dokka:all-modules-page-plugin:1.9.10")
}

val dokkaPluginsClasspathResolverTask by tasks.registering(Sync::class) {
  group = "dokkaPlugins"
  from(dokkaPluginsClasspath.incoming.artifactView { }.artifacts.resolvedArtifacts.map { it.map { it.file } })
  into(temporaryDir)
}
```

run `./gradlew x`

Expect that the logs contain `FooRule is active`, but actually they do not.

### Workaround

Use `resolutionStrategy.eachDependency {}` to update the version to 'latest.release' if none was defined.

```kotlin
val dokkaPluginsClasspath: Configuration by project.configurations.creating {
  isCanBeResolved = true
  isCanBeConsumed = false
  isVisible = false

  resolutionStrategy.eachDependency {
    if (requested.group == "org.jetbrains.dokka" && requested.version.isNullOrBlank()) {
      useVersion("latest.release")
    }
  }
}
```

However, this means `enforcedPlatform()` is required, which might cause other problems.

### Gradle version

8.5

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Component metadata rules cannot be triggered by a dependency without a version, since they need full GAV. You need a version to decide which metadata to load. 

Your build should fail. If it's not, please provide a full and isolated reproducer for your scenario.
