### ISSUE TITLE
Tutorials should cover multiple programming languages

### ISSUE THREAD

**Issue by jiyewushen** [gradle/gradle#27447]
### Issue type

Wrong or misleading information

### Problem description

在 *Developing Custom Gradle Types* [7.0](https://docs.gradle.org/7.0/userguide/custom_gradle_types.html)、[8.0](https://docs.gradle.org/8.0/userguide/custom_gradle_types.html)
 * Gradle at (7.0,8.5] not support kotlin demo，howerver，when the managed properties was an incubating feature，it supported Java、Kotlin、Groovy demo。

### Page with the problem

https://docs.gradle.org/7.0/userguide/custom_gradle_types.html

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by lkasso** [comment]
I am actively working on re-writing the entire user manual and as I go through it, I make sure sections have both a Groovy and a Kotlin example.

**Comment by lkasso** [comment]
Over 90% of the User Manual has both Kotlin and Groovy examples as of Gradle 9. Marking this as complete.
