### ISSUE TITLE
`apt perge gradle ` will not notify user if need delete `/home/<user>/.gradle` folder 

### ISSUE THREAD

**Issue by q2333gh** [gradle/gradle#27440]
### Current Behavior

`apt perge gradle ` will not notify user if need delete `/home/<user>/.gradle` folder 
Which default behavior will not delete that. but `purge` semantics should means delete that folder.

This cause me alot problem when i try to totally clean reinstall my gradle.

### Expected Behavior

the  `purge` semantics should means delete that folder.

### Steps to Reproduce

as above

### Gradle version

8.5

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is an issue with the deb package, not Gradle itself. Please contact the author(s) of the package for this issue.

**Comment by q2333gh** [comment]
It totally not need to say sorry. I will goto deb community to tell them the bug ~  thank you for point out. Unless i wont know what cause the problem!
