### ISSUE TITLE
Scala plugin doesn't provide subproject as dependency

### ISSUE THREAD

**Issue by carymrobbins** [gradle/gradle#2746]
### Context

I'm attempting to use Gradle for a Java/Scala multi-project build. Unfortunately, it appears that when having project A depend on project B, the `scalaCompile` task for project A is not finding the compiled classes from project B.

In my `gradle.build` file below, the root project depends on `macros`.

https://github.com/carymrobbins/intellij-haskforce/blob/44ad20c9ebb221d9367bfe768a18b15ccb23fe1a/build.gradle#L99-L102

However, the `compileScala` task complains that it can't find the compiled classes from `macros` -

https://travis-ci.org/carymrobbins/intellij-haskforce#L287

### Expected Behavior

The `compileScala` task should be able to find its dependencies' compiled classes.

### Current Behavior

The `compileScala` task is not able to find its dependencies' compiled classes.

### Steps to Reproduce (for bugs)

```
% git clone https://github.com/carymrobbins/intellij-haskforce
% cd intellij-haskforce
% ./gradlew assemble
```

### Your Environment

This happens on Mac and Linux with Gradle 4.0.1.

**Comment by carymrobbins** [comment]
It seems the culprit may be that `assemble` doesn't put the compiled Scala classes into the resulting jar. I've checked the jars that are assembled and they will only contain either sources compiled in `src/main/java` or `src/main/resources`.

**Comment by carymrobbins** [comment]
Downgrading from Gradle 4.0.1 to 3.5 resolves the issue, so the problem lies with Gradle 4 compatibility.

**Comment by big-guy** [comment]
This is an issue with the `org.jetbrains.intellij` plugin.  It changes the output directories for Scala compilation when using instrumentation: https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L239

In Gradle 4.0+, there are multiple classes directories and the plugin doesn't take this into account. 
That's the source of the deprecation warning.  

You can get around this by either disabling instrumentation 
```
intellij { instrumentCode = false }
```
Or forcing a single classes directory (this sacrifices build cache support)
```
def singleClassesDir = sourceSets.main.output.classesDir 
sourceSets.main.output.classesDir = singleClassesDir
```

**Comment by carymrobbins** [comment]
@big-guy Ah makes sense, thanks for tracking down the issue!
