### ISSUE TITLE
Have an issue when adding checkerframework in gradle build

### ISSUE THREAD

**Issue by zhenqi** [gradle/gradle#2747]
Hi,

I face an issue when add checkerframework in gradle build, I follow the instructions: https://checkerframework.org/manual/#gradle, do all the steps to add these config settings into build.gradle(add all the items from instructions in certain part), and then do a build, here is the error log:

18:40:40 Download http://companyurl:9999/proximity/repository/public/org/checkerframework/checker/2.1.14/checker-2.1.14.pom
18:40:41 Download http://companyurl:9999/proximity/repository/public/org/springframework/boot/spring-boot-starter-parent/1.5.4.RELEASE/spring-boot-starter-parent-1.5.4.RELEASE.pom
18:40:44 Download http://companyurl:9999/proximity/repository/public/org/checkerframework/checker/2.1.14/checker-2.1.14.jar
18:40:44 Download http://companyurl:9999/proximity/repository/public/org/checkerframework/jdk8/2.1.14/jdk8-2.1.14.pom
18:40:45 Download http://companyurl:9999/proximity/repository/public/org/checkerframework/jdk8/2.1.14/jdk8-2.1.14.jar
18:40:45
18:40:45 FAILURE: Build failed with an exception.
18:40:45
18:40:45 * Where:
18:40:45 Build file '/var/builds/workspace/111592-v3-PR-824/BUILD_CONTAINER/oracle-jdk8-current/label/DOCKER-LOW/app_root/build.gradle' line: 185
18:40:45
18:40:45 * What went wrong:
18:40:45 A problem occurred evaluating root project 'projectname'.
18:40:45 > Cannot change strategy of configuration ':checkerFramework' after it has been resolved.
18:40:45

I am not sure where this error comes from, does someone have ideas?

Thanks,

Ace

**Comment by oehme** [comment]
The code that they recommend is broken. It resolves dependencies eagerly (by calling asPath at configuration time).

```
allprojects {
    tasks.withType(JavaCompile).all { JavaCompile compile ->
        compile.options.compilerArgs = [
                '-processor', 'org.checkerframework.checker.nullness.NullnessChecker',
                '-processorpath', "${configurations.checkerFramework.asPath}",
                '-Xmaxerrs', '10000',
                // uncomment to turn Checker Framework errors into warnings
                // '-Awarns', '-Xmaxwarns', '10000',
                "-Xbootclasspath/p:${configurations.checkerFrameworkAnnotatedJDK.asPath}"
        ]
    }
}
```

Should be more like:

```

task setupBootClasspath {
  doFirst {
    tasks.withType(JavaCompile) {
      options.bootClasspath = configurations.checkerFrameworkAnnotatedJDK.asPath
    }
  }
}

tasks.withType(JavaCompile) {
  dependsOn setupBootClasspath
  options.annotationProcessorPath = configurations.checkerFramework
  options.compilerArgs = [
    '-processor', 'org.checkerframework.checker.nullness.NullnessChecker',
    '-Xmaxerrs', '10000',
    // uncomment to turn Checker Framework errors into warnings
    // '-Awarns', '-Xmaxwarns', '10000'
  ]
}

**Comment by oehme** [comment]
I created an issue to make the `bootClasspath` declaration simpler, what I showed above is necessary at the moment, but really shouldn't be so complex.

**Comment by zhenqi** [comment]
Thanks, but I do what you showed above and get another error:

**Comment by zhenqi** [comment]
20:06:06 An exception has occurred in the compiler (1.8.0_60). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
20:06:06 com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.annotation.Annotation not found
20:06:06 :compileJava FAILED
20:06:06 
20:06:06 FAILURE: Build failed with an exception.
20:06:06 
20:06:06 * What went wrong:
20:06:06 Execution failed for task ':compileJava'.
20:06:06 > Compilation failed; see the compiler error output for details.

**Comment by oehme** [comment]
Looks like the jar you set as the boot classpath is broken, please ask for help from the checker framework team.

**Comment by zhenqi** [comment]
OK, thanks!

**Comment by big-guy** [comment]
@oehme it looks like the original (bad) code was prepending to the bootclasspath (`-Xbootclasspath/p:stuff`), while `options.bootClasspath = configurations.checkerFrameworkAnnotatedJDK.asPath` sets it to that specific list (which I think explains the error @zhenqi is seeing).  So we'd need a way to lazily set a bootclasspath and append/prepend to it.

**Comment by oehme** [comment]
Got it. In that case the workaround is to replace the assignment to bootClasspath with adding the compiler option.
