### ISSUE TITLE
Not able to import package but I have successfuly added dependencies and dependencies are showing in gradle  dependencies menu.

### ISSUE THREAD

**Issue by Krishnapro** [gradle/gradle#27518]
### Current Behavior

I'm not able to import packages from specific dependencies.

![image](https://github.com/gradle/gradle/assets/59277887/48ee1077-9dfc-49e4-bb0d-44e20f83d199)

### Expected Behavior

Dependencies have been added successfully, but when I try to import them, it gives an error.

As  we see below image dependencies added show in the Gradle menu

![image](https://github.com/gradle/gradle/assets/59277887/471002fe-74e4-447b-bdff-b3df2a8d1cca)

### Steps to Reproduce

I upgraded scale 2.11 to 2.13 and related dependencies then I got this issue. 

I have tried a lot of ways to get rid of this issue but I'm not able to do this. I already cleaned caches and built the project also cloned the new project and tried to build but the result is the same.

### Gradle version

6.1

### Your Environment (optional)

Linux Mint  20
JDK 8
Gradle 6.1
IntelliJ 2023.3.2(community edition)

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

**Comment by ljacomet** [comment]
You add that dependency to `sparkdeps` which seems to be part of `runtimeClassapth`. But for showing as an import option in the IDE, you need the dependency in `compileClasspath`.

**Comment by Krishnapro** [comment]
The issue is fixed by using dependencies with api.
