### ISSUE TITLE
Kotlin CLI script classpath wrongly set

### ISSUE THREAD

**Issue by alegomes** [gradle/gradle#27525]
### Current Behavior

The generated CLI script doesn't work out of the box.

![image](https://github.com/gradle/gradle/assets/34938/cc170af1-0291-4906-a99d-72c93fc1dca8)

### Expected Behavior

I expected the generated CLI script to run out of the box.

![image](https://github.com/gradle/gradle/assets/34938/1a802525-21a5-4472-b0cf-4fceaddcf192)

Or am I having the wrong expectation? 

### Steps to Reproduce

# 1. Create a very simple Gradle Kotlin project

![image](https://github.com/gradle/gradle/assets/34938/e7963ca2-0932-42bd-b5c9-70c6c57cb80e)

# 2. Build the project

![image](https://github.com/gradle/gradle/assets/34938/dd98a74a-aba0-4d12-8ced-8437b4197099)

# 3. Run it with ```gradle run``` ...

![image](https://github.com/gradle/gradle/assets/34938/0a9f155b-dbd3-46e6-a4a1-93c46b89eb04)

...everything works fine.

# 4. Run the generated script...

![image](https://github.com/gradle/gradle/assets/34938/23c0b2ca-569f-442f-ab31-17d4c67fd203)

# 5. The problem

It seems the CLASSPATH is not set correctly in ```app/build/scripts/app```. It uses ```lib``` instead of ```libs```.

![image](https://github.com/gradle/gradle/assets/34938/0d1713d4-a806-433f-9705-d31077c53ae2)

# 5. A solution

If I change it...

![image](https://github.com/gradle/gradle/assets/34938/b6a77c70-a7a8-4cc3-b773-c58ff0f8f5fd)

... now it works.

![image](https://github.com/gradle/gradle/assets/34938/cd12a3ad-049d-4d7d-98cc-354d1fbc22a1)

### Gradle version

8.5

### Build scan URL (optional)

https://gradle.com/s/ul7a72btoyq7y

### Your Environment (optional)

![image](https://github.com/gradle/gradle/assets/34938/1d83dbcc-f92a-44ce-87f4-8d970543d954)

**Comment by cobexer** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by cobexer** [comment]
Ah, I noticed something else here: 
You try to execute the generated startup script from it's temporary location, to test the created application distribution you need to run the `installDist` task and reference the created distribution in `./app/build/install/app/bin/app` which will work correctly. See the [application plugin documentation](https://docs.gradle.org/current/userguide/application_plugin.html#sec:the_distribution) for more details.
