### ISSUE TITLE
Broken Link to Gradle Module Metadata Specification

### ISSUE THREAD

**Issue by benlOXMT** [gradle/gradle#27524]
### Issue type

Wrong or misleading information

### Problem description

Every link to the Gradle Module Metadata specification that I've found in the docs so far has been broken. Eg on the Understanding Gradle Module Metadata [page](https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html) the link in the final sentence 
"The specification for Gradle Module Metadata can be found [here](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md)." 

If you follow that link on the "here" you'll get a File Not Found. 

### Context (optional)

As a result, I can't find a link to the actual spec, making it hard to understand Gradle Module Metadata (I'm slowly working through the Gradle docs). 

### Page with the problem

https://docs.gradle.org/current/userguide/publishing_gradle_module_metadata.html

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue.

***

This is already fixed in RC, see, for example, 
https://docs.gradle.org/release-candidate/userguide/publishing_gradle_module_metadata.html
