### ISSUE TITLE
Unresolved directive in `userguide.pdf`

### ISSUE THREAD

**Issue by shamefulCake1** [gradle/gradle#27523]
### Issue type

Missing information

### Problem description

1. `wget https://docs.gradle.org/current/userguide/userguide.pdf`
2. Open Section "GETTING STARTED"
3. Observe `Unresolved directive :leveloffset: +2`

### Page with the problem

https://docs.gradle.org/current/userguide/userguide.pdf

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
