### ISSUE TITLE
Add FileCollection overload for bootClasspath

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#2755]
Answering #2747 I realized that we have no good way to lazily resolve the bootClasspath of a compile task. This can be useful if a JDK is fetched from a repository. In general it's just odd that a classpath property would only take a `String`. 

We should add a `FileCollection` overload and possibly deprecate the `String` version.

**Comment by wolfs** [comment]
When we add the `FileCollection` version let's make sure to also fix https://github.com/gradle/gradle/issues/2619.

**Comment by lptr** [comment]
This is now merged as #3002 and will ship with Gradle 4.3.
