### ISSUE TITLE
Add 12 factor property provider support

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#27562]
### Expected Behavior

https://12factor.net
Here's a brief in how spring boot does it (they have the last wins order) https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config
```kts
providers.getProperty("foo.bar")
```
should look for this property the highest priority on my list wins

1. A command line argument `-Pfoo.bar=`
1. an environment variable `FOO_BAR`
1. a gradle property `gradle.properties` `foo.bar=`
1. a secrets directory `/run/secrets/foo/bar`

### Context

it's frustrating to have to write a lot of logic to figure out where a property might have come from in the face of security issues even. Where it should live on my local machine isn't necessarily the same as where it should live in CI, and where it should live in CI will depend on the vendor.

This is partially spring out of this

https://github.com/gradle/gradle-build-action/security/advisories/GHSA-h3qr-39j9-4r5v

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
@gradle/bt-configuration A system like this might be a good way to resolve the confusion between environment variables, system properties, gradle- and project properties.

Related:
* #26107

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before it gets implemented.
***
This is an interesting feature to consider. It seems that [build parameters plugin](https://gradlex.org/build-parameters) from GradleX already covers some aspects of these. One missing piece is the first-class secret support, though.

**Comment by oleg-nenashev** [comment]
Does this functionality really have to be a part of the Gradle core though?
I am still learning the internals, but IIUC there are many plugins like https://github.com/google/secrets-gradle-plugin implementing it as external solution

**Comment by mlopatkin** [comment]
> Does this functionality really have to be a part of the Gradle core though? I am still learning the internals, but IIUC there are many plugins like https://github.com/google/secrets-gradle-plugin implementing it as external solution

There are certain guarantees we want to provide for secrets in the Gradle core too, like avoiding accidentally spilling them to disk because of caching. We have configuration cache encryption to mitigate that to some extent now, but this feature has its costs.

**Comment by xenoterracide** [comment]
> We have configuration cache encryption to mitigate that to some extent now, but this feature has its costs.

is this something always on? is it something that is easily enabled by the github task?

> There are certain guarantees we want to provide for secrets in the Gradle core too

I would absolutely say that secrets is a required and somewhat urgent need. Even plugin creators should have a reasonable safe way to say get property as secret. So it's not added to the cache, it's far too easy to make a mistake here, the providers don't make the usage obvious. I'm not sure if `System.getProperty` will be stuck in the configuration cache either.

**Comment by mlopatkin** [comment]
> > We have configuration cache encryption to mitigate that to some extent now, but this feature has its costs.
> 
> is this something always on? is it something that is easily enabled by the github task?
> 

It is always on. By default, Gradle generates a machine-specific encryption key for CC data and stores it in `~/.gradle` (which is typically not cached as a whole or published as a build artifact on CI). Starting with Gradle 8.6 (going through RC phase ATM), it is also possible to provide the encryption key as an environment variable, mostly to allow utilizing CC on ephemeral CI. You can read more about it at [the documenation page](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:secrets). I believe, Gradle GitHub Action is going to support this soon if not already.

**Comment by xenoterracide** [comment]
I mean hopefully that resolves the issue that GitHub was complaining about... Still I think it's very unclear for plug-in providers how to do anything with secure/ secrets. I've written plugins and I was recently messing with the Maven plug in to get stuff out of the properties and I have no idea what the right way to do it is. Especially when I was trying to preserve the same name as what was already in those properties. You try to retrieve them via credentials and the credentials can't actually just be passed to the Maven plugin.

**Comment by mlopatkin** [comment]
This issue will be closed as a duplicate of

* #2885
* #29700
* #3972

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

It looks like we have all aspects of the issue covered in other epics.
