### ISSUE TITLE
Using Provider<NestedType> to replace Read-only managed nested properties 

### ISSUE THREAD

**Issue by jiyewushen** [gradle/gradle#27568]
### Issue type

Wrong or misleading information

### Problem description

Using `Provider<NestedType>` to replace `Read-only managed nested properties` rather than `Property<NestedType>` . when managed properties concept was an incubating feature, used `Property<NestedType>` to declare a read-only managed property, but now use `Provider<NestedType>` to do it.

>This pattern is useful when a custom type has a nested complex type which has the same lifecycle. If the lifecycle is different, consider using Property<NestedType> instead.

![image](https://github.com/gradle/gradle/assets/16441451/3452ecfc-7a0e-4348-8334-e196d7ebd6f0)

### Page with the problem

https://github.com/gradle/gradle/blob/master/platforms/documentation/docs/src/docs/userguide/authoring-builds/other/custom_gradle_types.adoc

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***
> If the lifecycle is different

Implies that it is not a read-only nested property but if you were to use a `Provider`, it would remain read-only in the sense that you could not update the full nested property with a reference to a different instance of it.
