### ISSUE TITLE
[security] do not cache all environment variables in configuration cache

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#27560]
### Expected Behavior

*only* explicitly requested environment variables are put in the cache. Meaning only if I do something like this would `CI`'s result be cached

```kt
providers.environmentVariable("CI")
```

### Current Behavior (optional)

from what I know all environment variables are put in the cache

### Context

I'm writing this as a result of my great annoyance with this [github vulnerability](https://github.com/gradle/gradle-build-action/security/advisories/GHSA-h3qr-39j9-4r5v), which is arguably their fault for putting secure credentials in environment variables in the first place (they always put a TOKEN in).

additionally, I think it would be good to provide a way to define a secure process.

**Comment by cobexer** [comment]
Please follow the [policy](https://github.com/gradle/gradle/security/policy) when reporting security issues.
***
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
@gradle/bt-configuration can you confirm it already works this way? That is the configuration cache would only write environment variables to the cache which are used as task inputs?
Should we consider clarifying this in the documentation?

**Comment by mlopatkin** [comment]
>gradle/bt-configuration can you confirm it already works this way? That is the configuration cache would only write environment variables to the cache which are used as task inputs?

That is indeed the case. There are plugins, though, which are not prepared for the configuration cache and grab the whole environment. The configuration cache report can help to pinpoint these plugins. There are [APIs](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:reading_sys_props_and_env_vars) that can help to reduce the number of environment variable read.

**Comment by xenoterracide** [comment]
@mlopatkin so what's going on in #27797 that's invalidating the cache based on an environment variable that's not requested by gradle?
