### ISSUE TITLE
Clarification regarding reserved alias names in version catalogs

### ISSUE THREAD

**Issue by fsladkey** [gradle/gradle#27590]
### Issue type

Wrong or misleading information

### Problem description

Hi there!

I was hoping to get some clarification on what is a valid alias name in a version catalog.

The documentation I'm referencing is https://docs.gradle.org/current/userguide/version_catalog_problems.html#reserved_alias_name

I found these docs because the inclusion of the word `class` anywhere in an alias caused a build failure.

```
* Exception is:
java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: Invalid catalog definition:
  - Problem: In version catalog libs, alias 'foo-bar-class' is not a valid alias.
    
    Reason: Alias 'foo-bar-class' is a reserved name in Gradle which prevents generation of accessors.
    
    Possible solution: Use a different alias which doesn't contain 'class'.

For more information, please refer to https://docs.gradle.org/8.4/userguide/version_catalog_problems.html#reserved_alias_name in the Gradle documentation.
```

A few things were unexpected:
* `class` isn't mentioned in the docs as a reserved alias
* `plugin` _is_ mentioned as a reserved alias, but alias names ending with plugin seem to work without issues.
* The docs imply that the issue occurs when an alias ends with a reserved keyword, but if class appears anywhere in the alias I still see the same failure (e.g. `foo-class-bar`)

### Context (optional)

The reason I want to use `class` in an alias name in the first place is because I'm interested in publishing a version catalog which includes a library with `class` in the artifact ID, and to make all aliases discoverable by users of the catalog I'd like to follow the artifact IDs exactly if possible.

So with that in mind, I'm also curious wondering:
* Is there any other way around the restrictions in reserved keywords?
* Is there a complete of reserved words?
* Is it possible to know if this list may change in the future?

Thanks in advance!

### Page with the problem

https://docs.gradle.org/current/userguide/version_catalog_problems.html#reserved_alias_name

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
***
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
