### ISSUE TITLE
Signing plugin should have an option to prevent signing derived artifacts created by other plugins

### ISSUE THREAD

**Issue by niandy** [gradle/gradle#27605]
### Expected Behavior

there should be an option to ignore derived artifacts. Probably by checking if they are `instanceof DerivedMavenArtifact`

### Current Behavior (optional)

When you're signing publication if it contains some derived artifacts that created by something else than SigningPlugin itself they will also be signed. That no always useful

### Context

signing {
    sign publishing.publications.findAll() as Publication[]
}

**Comment by vlsi** [comment]
@niandy , could you clarify why do you want to ignore derived artifacts?

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #26760

Please add your use case and 👍 to that issue.
***
We assume by derived artifact you mean an artifact produced by doing something with the publication content, then this is a valid feature request however it's a duplicate of the issue linked above.
