### ISSUE TITLE
Gradle fails if a Project uses same plugin in "main" and "buildSrc" settings script and it's invoked from buildSrc

### ISSUE THREAD

**Issue by roman-jb** [gradle/gradle#27609]
### Current Behavior

Issue only affects Kotlin DSL, Groovy DSL appears to work as intended.

Running Tasks errors out with either
```
Plugin [id: 'com.gradle.enterprise'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
```
or
```
Error resolving plugin [id: 'com.gradle.enterprise', version: '3.16.1']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.
```

For more information:
https://youtrack.jetbrains.com/issue/IDEA-342217

### Expected Behavior

Tasks should run successfully.

### Steps to Reproduce

Both `./buildSrc/settings.gradle.kts` and `./settings.gradle.kts` declare the same Plugin.
For instance:
```
plugins {
    id("com.gradle.enterprise")
}
```

### Gradle version

7.6.3

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

@roman-jb Sorry, I'm having trouble reproducing this in isolation. The setup described in [the original issue]( https://youtrack.jetbrains.com/issue/IDEA-342217) works with both Gradle 7.6.3 and 8.x and both for Groovy/Kotlin DSL used from the command line (without IntelliJ).
Can you please share more details on the investigation you conducted? Can you reproduce it without IntelliJ? If no, what do you think should be improved on the Gradle side?

**Comment by Vampire** [comment]
Let me also chime in as the original reporter. :-)
Of course you cannot reproduce from commandline, from commandline there is no problem (unless you follow the bad advice from the error).
The problem is only when you try to sync that project in IntelliJ.

**Comment by roman-jb** [comment]
Attaching two Projects one using Groovy, another uses Kotlin (issue only affects Kotlin).
Issue is reproducible outside of IDEA: using a Command Prompt navigate to the `buildSrc` folder and try running a Gradle Task from there (for instance `../gradlew :help`) - it will fail for the Kotlin-based Project, while running successfully in the Groovy-based one.
[
[IDEA-342217-KT.zip](https://github.com/gradle/gradle/files/13938420/IDEA-342217-KT.zip)
[IDEA-342217.zip](https://github.com/gradle/gradle/files/13938421/IDEA-342217.zip)
](url)

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

***

@roman-jb @Vampire Thanks for providing the details.

First of all, the issue is the same for Groovy and Kotlin DSL. There is a typo in provided groovy DSL project: `settingns.gradle` ---> `settings.gradle`.

The error is the same both for 7.6.3 and 8.x. as far as I can see.

**Comment by Vampire** [comment]
It is correct that building from within `buildSrc` fails for 7.6.3 and 8.5 alike.
But I'm not sure whether this should actually work and is not what my report was about.

My report is about opening / syncing the main project in IntelliJ.
This behaves consistent for Groovy DSL vs. Kotlin DSL,
and fails with 7.6.3 but is successful with 8.5.

**Comment by ov7a** [comment]
@Vampire I agree. Regarding 
> whether this should actually work 
At least the error should be improved to be explicit about that.

Regarding the sync - @roman-jb probably this particular part is on IntelliJ? Or something should be improved in Gradle in that regard, e.g. on the tooling API side?

**Comment by Vampire** [comment]
> at least the error should be improved to be explicit about that.

Well, the error says that no version is defined and thus the plugin cannot be found which is exactly right if you run the `buildSrc` build stand-alone.
Just if it run as included build, the version is coming from the including build and there no version is necessary.
So I'm not sure whether there is something to improve in that specific regard.

All I complained about was the sync of a valid project not working with 7.6.3 that works with 8+.
Whether this is an IntelliJ or tooling API topic I don't know. :-)

**Comment by donat** [comment]
I think you encountered https://github.com/gradle/gradle/issues/20898. I afraid the only way to resolve the problem is indeed upgrade the build to a 8.0+ version.

**Comment by Vampire** [comment]
Do you think so @donat?
There is no composite build involved and it is not complaining about things missing that would be coming from an init script.
But indeed it also works with 7.1.1 and fails with 7.2 like in the mentioned issue.

**Comment by Vampire** [comment]
Luckily, I do not have the need to use this construct anymore in the project where I had it anyway. So 🤷‍♂️ :-)

**Comment by donat** [comment]
It's not just about composites but the way the tapi queries constructed in IntelliJ, hence the difference on the command line and in the IDE for old versions.
