### ISSUE TITLE
Gradle only partly extracts zip files with extra field that is larger than 8024 bytes

### ISSUE THREAD

**Issue by coehlrich** [gradle/gradle#27604]
### Current Behavior

When using the `Copy` task to extract a zip file with an entry that has an extra field larger than 8024 bytes that entry will be the last entry extracted.

### Expected Behavior

The `Copy` task should extract the whole zip file even when an entry has an extra field larger than 8024 bytes.

### Steps to Reproduce

https://github.com/coehlrich/gradle-bug-extract-zip

Both zip files have files:
- `1.txt` with an empty extra field
- `2.txt` with an extra field where
  - in `8024.zip` is 8024 bytes in length
  - in `8025.zip` is 8025 bytes in length
- `3.txt` with an extra field that is 8024 bytes in length

Notice how when the `extract8024` task is run all 3 files are extracted while running `extract8025` only the first 2 files are extracted.

### Gradle version

8.5

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.
