### ISSUE TITLE
When viewing docs in dark-mode, 'Tips' boxes have a light-mode background

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27617]
### Issue type

Wrong or misleading information

### Problem description

The `Knowing what plugin-provided extensions are available` and `Keeping build scripts declarative` boxes are rendered with a white background, which doesn't match the rest of the theme and is more difficult to read.

<img width="891" alt="image" src="https://github.com/gradle/gradle/assets/897017/ae7676f2-9736-4cde-842e-7b808066657c">

I'd like to see something like this:

<img width="826" alt="image" src="https://github.com/gradle/gradle/assets/897017/4a76b5b2-0547-4feb-8028-a2677fb3fc55">

### Page with the problem

https://docs.gradle.org/nightly/userguide/migrating_from_groovy_to_kotlin_dsl.html

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
***
And thanks for testing nightlies!

The problem still exists in [8.6 RC2](https://docs.gradle.org/8.6-rc-2/userguide/migrating_from_groovy_to_kotlin_dsl.html#configurations-and-dependencies)

**Comment by lkasso** [comment]
Fixed in https://github.com/gradle/gradle/pull/27715
