### ISSUE TITLE
Native library cannot be loaded on Windows 10

### ISSUE THREAD

**Issue by SirTwsted** [gradle/gradle#27615]
### Current Behavior

Not working, 
typing gradle -v in terminal gives FAILURE notice.
And I don't know how to fix it as everything I tried, doesn't seem to fix the problem.

I made sure that in the environment variable panel in windows 10 the path is properly set to Gradle v8.5 folder location.
folder location is in the exact location as instructed in the installation instructions of gradle website.

### Expected Behavior

I never know what to say here except to say.
"I wish it would work"  🤷‍♀️

### Context (optional)

I am trying to get gradle to work.

### Steps to Reproduce

go to Terminal and type 
gradle -v

I get error that says FAILURE:  Build failed with an exception.
Don't know what is causing this issue.

![Screenshot_28](https://github.com/gradle/gradle/assets/15247713/0fb5d78d-617e-40c7-90f4-b3383473521e)

### Gradle version

8.5

### Your Environment (optional)

Gradle v8.5 is installed in the correct location as per instructions of your website.

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
@gradle/bt-execution at the least the error message should be improved.

**Comment by lptr** [comment]
Could you please re-run with `--stacktrace`?

**Comment by lptr** [comment]
Let's close this for now. Please let us know if you are still interested in investigating this further.

Also, in Gradle 8.8 we'll fix a problem that prevented `-Dorg.gradle.native=false` from disabling native library loading, see #28203.
