### ISSUE TITLE
war plugin bug?

### ISSUE THREAD

**Issue by N3verL4nd** [gradle/gradle#2762]
apply plugin: 'war'
<img width="733" alt="_20170821103530" src="https://user-images.githubusercontent.com/11865760/29501666-e7180278-865c-11e7-9da6-83890ae92350.png">

webapp are not automatically generated?

gradle 4.1
IntelliJ IDEA 2017.2.2

**Comment by blindpirate** [comment]
Could you please give us more context?

**Comment by N3verL4nd** [comment]
firstly,I wrote a `build.gralde` file.
```
group 'com.xiya'
version '1.0-SNAPSHOT'

apply plugin: 'idea'
apply plugin: 'war'

repositories {
    mavenCentral()
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.akhikhl.gretty:gretty:+"
    }
}

apply plugin: "org.akhikhl.gretty"

dependencies {
    compile group: 'org.springframework', name: 'spring-webmvc', version: '4.3.7.RELEASE'
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
```

secondly,I run `gradle idea` to generate a web project.But `webapp` directory isn't being generated.

<img width="240" alt="1" src="https://user-images.githubusercontent.com/11865760/29505224-8e7a908e-8677-11e7-8a6c-38712cb6027b.png">


-----------

When selected the checkbox ,there is a warning like this
<img width="801" alt="2" src="https://user-images.githubusercontent.com/11865760/29505329-3d30794a-8678-11e7-8593-04a1b23eb28c.png">

**Comment by blindpirate** [comment]
I don't have much experience in web application development, but I don't think it's a bug of Gradle. 

Actually, I guess this message is to warn you the war artifact is generated by Gradle and not by IDEA itself. Each time when you reimport the project into IDEA, IDEA would call a Gradle process to do the importing, which may be out of IDEA's control.

I think JetBrains folks may help you about the detail of this warning.

**Comment by bmuschko** [comment]
@N3verL4nd Would you mind opening an issue on Jetbrains issue tracker? I am going to close this issue for now. Feel free to comment on this issue if you need further assistance.
