### ISSUE TITLE
Console output code boxes have Java/Kotlin keywords highlighted

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27623]
### Issue type

Wrong or misleading information

### Problem description

Some code boxes with console output have Java/Kotlin keywords highlighted.

<img width="615" alt="image" src="https://github.com/gradle/gradle/assets/897017/efa68025-1ef7-4c8f-8f79-cba5caa08dea">

I'd expect to see all the text rendered without colours.

### Page with the problem

https://docs.gradle.org/nightly/userguide/part1_gradle_init.html#step_1_initializing_the_project

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

**Comment by ov7a** [comment]
This was fixed by
* https://github.com/gradle/gradle/pull/27715
