### ISSUE TITLE
Gradle distribution rotation

### ISSUE THREAD

**Issue by arturdryomov** [gradle/gradle#2763]
At this point all Gradle distributions are stored locally, no matter it was used single time or every day. It would be nice to have some rotation on hand.

* Manually. Can be done already by hand, but some task can be helpful.
* Semi-automatically. On changing Gradle wrapper version remove already downloaded wrappers in the project directory.
* Automatically. If wrapper was not used for a month, remove it. This is kind of tricky because it will require some deterministic properties to be stored.

**Comment by artem-zinnatullin** [comment]
>Semi-automatically. On changing Gradle wrapper version remove already downloaded wrappers in the project directory.

Wrappers are not stored in the project directory though, I guess you meant `~/.gradle/wrapper` :)

Rotation of wrappers is definitely a problem, my `~/.gradle/wrapper` is 7 GB (I remove old wrappers manually once in 4-6 months).

**Comment by blindpirate** [comment]
An idea which just came into my mind is to provide a task, e.g. something like `gradle cleanHistoryWrapper`. If one is bothered by the old distributions, he/she could run the command and that's all. 

@ming13 @artem-zinnatullin What do you think?

**Comment by artem-zinnatullin** [comment]
That's what @ming13 suggested or that's how I interpreted it :) 

>Manually. Can be done already by hand, but some **task** can be helpful.

I think it's a good start.

**Comment by lacasseio** [comment]
@blindpirate It would be interesting to clean based on access time, if enabled. This way we would truly clean distribution that hasn't been used in awhile.
