### ISSUE TITLE
Make CheckStyle plugin work by default for multi-project builds

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#2765]
You need boilerplate code to have one CheckStyle config file in a multi-project Gradle build.

### Expected Behavior
You add one checkstyle.xml file to the known location, apply 'checkstyle' plugin to all projects and everything works out of the box.

### Current Behavior
Running a build fails with
```
Unable to create Root Module: config {yourproject/yoursubproject/config/checkstyle/checkstyle.xml}
```

### Context
It is rare for multi-project builds to have an independent CheckStyle config file for each subproject. It feels absurd to copy-paste the same file to 20 directories (a project with 20 subprojects does not feel something exotic) and then remember to make changes in all 20 places.

Gradle should provide a safe default (`configFile = rootProject.file('config/checkstyle/checkstyle.xml')`) and allow to override this for those subprojects that really are an exception.

Currently every time I set up a multi-project build using Gradle I need to have this boilerplate code overriding `configFile` to `rootProject`.

**Comment by bmuschko** [comment]
This concern will basically be addressed by this PR: https://github.com/gradle/gradle/pull/2760. Instead of referencing a local file you'd host the file on a HTTP server and use it from each build.

**Comment by big-guy** [comment]
I think this is a bit different.  I dont think it should be necessary to have an external file to share configuration in a multiproject builds.  I think it would be a good idea to change the default to look for a config file only in the root project with multiproject builds. It would always be possible to get the old behavior by reconfiguring the tasks.

**Comment by pkubowicz** [comment]
@bmuschko I don't think so.

I don't accept having to set up a HTTP server to set up a build. It's absurd to externalise part of your build configuration (and CheckStyle configuration is a part of your build configuration) to a non-local drive. The current trend is to have source code, build configuration and CI server configuration in one repo. If I wanted a server just to check the style of my code, I would set up a Sonar server, not play with CheckStyle. What you are suggesting is against current trends.

Even if I had an HTTP server, this would mean I would still need to create a CheckStyle configuration file for each subproject - just those files would be smaller, consisting only of an import. This is worse boilerplate than I mentioned - it's better to have several lines in the root build.gradle than copy-paste files around the whole file tree.

**Comment by bmuschko** [comment]
Maybe I misunderstood your problem. What you are basically asking is to have a default value set for the `configFile` property of the Checkstyle task if you are in a multi-project build that points to the root project? In case I am still not on point could you provide a sample project that shows the use case?

> I don't accept having to set up a HTTP server to set up a build. It's absurd to externalise part of your build configuration (and CheckStyle configuration is a part of your build configuration) to a non-local drive.

That is already the case for external Gradle plugins or dependencies. Many of our users solve the problem you mention above with plugins. The functionality of a plugin can introduce those conventions.

**Comment by pkubowicz** [comment]
> Maybe I misunderstood your problem. What you are basically asking is to have a default value set for the configFile property of the Checkstyle task if you are in a multi-project build that points to the root project?

Yes, I'm asking for this.

> could you provide a sample project that shows the use case?

You can just take any multi-project build and try to use the CheckStyle plugin in it. You will end up either with copy-pasting checkstyle.xml around your file tree or applying the workaround boilerplate I mentioned.

The CheckStyle plugin is built-it in Gradle and should provide sensible defaults - ideally, it should work out-of-the box if you put files in the right place. Users should not be forced to write boilderplate code in their build.gradle. My point is that current defaults work only in single project builds. Real software does not fit into single project builds, so IMO in real world scenarios, the CheckStyle plugin does not work out of the box.

**Comment by bmuschko** [comment]
We'd be happy to receive a pull request for this. I suspect that the change would likely be a breaking change (to be proven) which would mean that we wouldn't release it before Gradle 5.0.

**Comment by pkubowicz** [comment]
I'm glad you agree on this solution. If I find some time, I will prepare a pull request.

**Comment by gortiz** [comment]
I would really appreciate to have this **very basic** feature

**Comment by lssilva** [comment]
This would be indeed nice

**Comment by pkubowicz** [comment]
Similar change should be done to CodeNarc plugin.

**Comment by bmuschko** [comment]
@pkubowicz Feel free to open another pull request specifically for plugin that should behave similarly. You can derive the changes from my pull request.

**Comment by Glusk2** [comment]
I still have a problem adding `checkstyle` plugin to a multi-project build. I've posted a SO question: https://stackoverflow.com/q/54851229 and a github issue: https://github.com/libgdx/libgdx/issues/5581 that somewhat describe my problem.

**Comment by pkubowicz** [comment]
The project you mentioned [uses Gradle 2.14.1](https://github.com/Glusk2/sprouts/blob/d891b6296def75cd363bb081f2046f69df4ebd34/gradle/wrapper/gradle-wrapper.properties). This fix appeared in Gradle 4.7.

**Comment by Glusk2** [comment]
@pkubowicz Yes that project uses gradle version `2.14.1`. But the one in the github issue ( libgdx/libgdx#5581) uses version `4.6`.
I've tried updating the project with gradle `4.6` to `4.7` and the issue persists - it compiles fine without the plugin and breaks if applied.

**Comment by Glusk2** [comment]
It wasn't a gradle issue. Resolved it: https://stackoverflow.com/a/55398135/6367213
