### ISSUE TITLE
Failed to transform gradle-8.2-src.zip(gradle:gradle:8.2) to match attributes {artifactType=src-directory, org.gradle.status=integration}

### ISSUE THREAD

**Issue by top1433** [gradle/gradle#27677]
### Current Behavior

Every time a new project is created, this file（gradle-8.2-src.zip） will be downloaded, but it eventually times out and fails. But I download very quickly in the browser, what is the reason for this！

### Expected Behavior

help me！thanks！

### Steps to Reproduce

![image](https://github.com/gradle/gradle/assets/34327580/655dfc23-31d7-4496-aecb-7602760dc7e9)
![image](https://github.com/gradle/gradle/assets/34327580/3cce44ec-498f-4693-b00c-d1523cf0559c)

### Gradle version

8.2

### Gradle version that used to work

8.5

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.
***
This looks like an environment problem on your end, 8.2 and 8.5 are hosted and handled identically on our end.

**Comment by nnoli90** [comment]
Am also facing this issue

**Comment by jriy** [comment]
可以从其他代理地址，提前将gradle src.zip好，然后 放于 .gradle/caches/modules-2/files-2.1/gradle/gradle/8.2/  目录下
运行就没问题了
