### ISSUE TITLE
sourceSets behavior when using srcDir config property different in macOs compared to windows

### ISSUE THREAD

**Issue by psvkushal** [gradle/gradle#27685]
### Current Behavior

When srcDir is used, to set the resource dir to the default value, 
In macOS : It executes without any exception
In windows: It throws an exception ```Execution failed for task ‘:app:processResources```

### Expected Behavior

The behaviour in the 2 OS should be the same

### Context (optional)

We are setting srcDir value in sourceSets in order to be explicit about from which location we are getting the resources from.

### Steps to Reproduce

Create a gradle application project,
implementation language : java
split functionality: no
build script: groovy dsl
test framework: junit jupiter

add the following lines into the build.gradle file
```
sourceSets {
    main {
    resources {
        srcDir 'src/main/resources'
    }
    }
}
jar {
    archiveName "test.jar"
}
```

### Gradle version

tested in 7.6.1 and 8.3

### Your Environment (optional)

Windows 11, MacOs ventura, Intellij Ide 2022 version and 2023 version

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
