### ISSUE TITLE
Android Studio project import memory regression in 8.6-rc1

### ISSUE THREAD

**Issue by akerimsenol** [gradle/gradle#27695]
### Current Behavior

There seems to be a memory regression in 8.6-rc1 during project configuration.

Our 2000 sub-project benchmark for Android Studio import reports significantly more memory use after project evaluation in Gradle 8.6-rc1

![image](https://github.com/gradle/gradle/assets/117925183/a3958cd5-ff49-49a4-a0d9-ae51bf61458a)

### Expected Behavior

See image above for before/after values.

### Steps to Reproduce

1. Clone the benchmark project. `git clone https://github.com/gavra0/android-extra-large-benchmark -b 2022.9`
2. Optional but recommended, set up a smaller subset (i.e. maybe 200):  https://github.com/gavra0/android-extra-large-benchmark/tree/2022.9?tab=readme-ov-file#working-with-smaller-subsets
3. Enable the [measurement plugin](https://github.com/gavra0/android-extra-large-benchmark/blob/2022.9/measurements/plugin.init.gradle.kts) for use during sync: https://github.com/gavra0/android-extra-large-benchmark/tree/2022.9?tab=readme-ov-file#working-with-smaller-subsets
4. Open Android Studio and import the project
5. Once import finishes, captured histograms will be found at `measurements` directory.

### Gradle version

8.6-rc1

### Gradle version that used to work

8.4

**Comment by mlopatkin** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by bingranl** [comment]
If I run the benchmark again with the latest gradle nightly(e.g.  8.7-20240121001303+0000, released on 21 Jan 2024), I should  be able to see the difference, right?
