### ISSUE TITLE
The 'wrapper' task removes user-defined settings in the 'gradle-wrapper.properties' file.

### ISSUE THREAD

**Issue by honourosis** [gradle/gradle#27694]
### Issue type

Other

### Problem description

How to reproduce:
1) Open any Gradle project
2) Add a custom value to the `gradle-wrapper.properties` file, for example `myProperty=test` or change any predefined value, such as `zipStorePath` or `distributionPath`
3) Run `gradle wrapper --gradle-version 8.2` (the version must be different from the current one)

As a result, the `gradle-wrapper.properties` will be updated, but all user defined data will be lost. The [WrapperGenerator implementation](https://github.com/gradle/gradle/blob/322c7dedcafea4c1302994f9ad012e9bb358bf83/platforms/software/build-init/src/main/java/org/gradle/api/tasks/wrapper/internal/WrapperGenerator.java#L89) ignores all user-defined values and simply regenerates the file content.

This behavior was not mentioned [in the current documentation](https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper).

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue.
***
The `gradle-wrapper.properties` is not supposed to be used for anything outside of the wrapper task properties.
The documentation should also clarify that modifications to the file for supported properties will not be preserved unless they are configured on the `wrapper` task of the root project.
