### ISSUE TITLE
Change in tar permission handling with 8.6-rc-1 and 8.6-rc-2

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#27709]
### Current Behavior

We have a tar task like this:

```
tasks.register("buildBZip2Tar", SymbolicLinkPreservingTar) { SymbolicLinkPreservingTar tar ->
  tar.archiveExtension = 'tar.bz2'
  tar.compression = Compression.BZIP2
  tar.preserveFileTimestamps = ${preserverTimestamp}
  from fileTree("archiveRoot")

  into('config') {
    dirMode 0750
    fileMode 0660
    from "real-folder2"
  }
}
"""
```

With 8.5 this results in permissions for 'config' folder itself to 755 but everything below 750. With gradle 8.6 it seems we now have 750 also for the config folder itself.

### Expected Behavior

the expected behaviour is that there is deterministic behaviour in gradle and this change in behaviour is not happening or at least documented and intentional. 

### Steps to Reproduce

1. git clone https://github.com/elastic/elasticsearch.git
2. ./gradlew :build-tools-internal:integTest (succeeds)
3. ./gradlew wrapper --gradle-version=8.6-rc-2 --gradle-distribution-sha256-sum 4a0d149f9edee932df9ae67f38e31878141c2aa54a93c59652beceeb46d5cfd3
4. ./gradlew :build-tools-internal:integTest (fails)

### Gradle version

8.6-rc-2

### Gradle version that used to work

8.5

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
We will make a decision before 8.6 is released.

**Comment by ov7a** [comment]
Thanks for reporting this. The changes will be reverted and reintroduced in later versions (probably 8.7). 
While the original changes improve the current state of things, this area is not covered by tests properly, so the default behavior is unclear. This should be fixed
