### ISSUE TITLE
`finalizedBy` does not work when task fails and the target task depends on origin task

### ISSUE THREAD

**Issue by nbrugger-tgm** [gradle/gradle#27707]
### Current Behavior

With this config: 
```kotlin
val cleanup = tasks.register("cleanup") {
    doLast {
        throw GradleException("cleanup should fail too!")
    }
	dependsOn("failing")
}

val failing = tasks.register("failing") {
	doFirst {
        throw GradleException("OH no! I Failed! I need cleanup!")
    }
    finalizedBy(cleanup)
}
```
executing `failing` does **not** trigger cleanup afterwards.

When the `dependsOn` is removed it works correctly

### Expected Behavior

`cleanup` is able to depend on `failing` without breaking the `finalizedBy` constraint

### Steps to Reproduce

https://github.com/nbrugger-tgm/gradle-issue-reproducer

1. `./gradlew failing`

### Gradle version

8.4, 8.5

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.
***
When a task fails, the tasks that `dependsOn` it are never run since the dependency should indicate a consumption of the tasks output which are not assumed to be produced if the task failed.

See the related issue:
* https://github.com/gradle/gradle/issues/27743

**Comment by nbrugger-tgm** [comment]
@cobexer 
> tasks output which are not assumed to be produced if the task failed

This is not true for test tasks. Test tasks do produce full output even if failing.

Is there a way to change this assumption? Lets say there is a task `convertJunitReportsToSomeFormat` what would the "gradle official" way to configure that? You cannot run  `convertJunitReportsToSomeFormat` when there are no reports so it has to depend on the test task if the convertJunitReportsToSomeFormat task is the one to be executed? But this is inconvenient since it means that you can only call the task by finalize and without creating an implicit dependency.

```kotlin
val testTask = tasks.register<Test>("test") { ... }
tasks.register<MyConversionTask>("convertTestResults") {
    unitReports = testTask //forbidden since implicit dependency
}
```

If i understand correctly that means that a task that depends on a "Test" task can never be called via the cli?

This is especially problematic if you do NOT want to execute the post-test task everytime but only when explicitlly needed `postAsGithubIssue`, `uploadToSonar` ..... only makes sense on ci. How would you suggest to configure such tasks?

In my opinion, there should be a flag `output.validOnFail` that is false by default. And produces the current behaviour but when set to true the task is assumed to have correct outputs even if failing. Or maybe a more gradle style thing such as `TaskOutputInternals#validWhen(spec: Spec<Task>)`

**Comment by cobexer** [comment]
@nbrugger-tgm please see the comment https://github.com/gradle/gradle/issues/27743#issuecomment-1899320717 in the issue we linked above
