### ISSUE TITLE
Allow injection of arbitrary classes into the buildscript classpath of test builds

### ISSUE THREAD

**Issue by robbie-demuth** [gradle/gradle#2772]
Right now, the [Java Gradle Plugin development plugin](https://docs.gradle.org/current/userguide/javaGradle_plugin.html) supports injecting the compiled classes of plugins into test builds so that the classes are accessible via the plugins DSL as described [here](https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-automatic-classpath-injection). Gradle should generalize this behavior such that any arbitrary compiled class is accessible anywhere in a test build, not just when the class is applied via the plugins DSL. This would make it possible to test custom task classes without having to package them and make them available via a plugin.

### Expected Behavior

Classes compiled by the main source set in a given module should be injected into test builds without having to package them via a plugin. This would mean that a given test build could create a task with a type has been provided by the main source set without needed to interact with the plugins DSL.

### Current Behavior

Currently, to test a custom task class via a test build, the easiest way to do so is to create a plugin (that is not published) that creates a task of the given type when applied to a project. Using automatic injection of plugin classes, test builds can then add the plugin to their classpath via the plugins DSL and configure the created task as required for testing.

### Context

During the effort to improve our build, we're removing non-incremental and non-cacheable custom tasks in favor of creating custom task classes in our build's buildSrc directory with associated tests. If I'm creating a class called `org.example.CustomTask`, I should be able to create a test build using the GradleRunner with a build file similar to the following: 

```
task customTask(type: org.example.CustomTask) {
  // Configure task properties here
}
```

Currently, the best way I know of to test custom task classes is the apply the Java Gradle Plugin Development plugin to the buildSrc project and create a plugin that creates a task of type CustomTask when applied to a project and then use automatic injection of plugin classes to test the task type in a test build. In other words, we use GradleRunner with a build file similar to the following:

```
plugins {
 id <PLUGIN_IDENTIFIER>
}

customTask {
  // Configure properties of pre-existing custom task here
}
```

### Your Environment

 * Build scan URL:

**Comment by big-guy** [comment]
This is annoying for me too.

I sort of understand why it's like this, you should try to have a "base" kind of plugin that adds capabilities (tasks, extensions, etc), but it doesn't provide any particular configuration/defaults.  And then a "conventions" kind of plugin that applies the base plugin, adds tasks and configures defaults. This can be a bit of overkill for some things.

A simple workaround I've used in the past for `buildSrc` is to have a "dummy" plugin that doesn't do anything, but exists in the same jar or has dependencies on the task-class-only-plugins you want to test.  Then you can use `plugins { id "dummy" }` to get the correct classpath. The task classes will be on the classpath at that point, so you can do what you were trying to achieve.

@bmuschko are there any other clever things we could do here?

**Comment by robbie-demuth** [comment]
In this case I'm not really trying to develop a plugin though. Instead I'm really just trying to develop custom task types for the build. I'm fairly new to Gradle in terms of plugin development, but it would seem to me that there should be a substantial market for custom task classes that aren't shipped via plugins. Imagine, for example, that Gradle didn't have a Sync task. A third party contributor could easily package a Sync class in a jar and Gradle developers could add it to their buildScripts closure. Why not support easier ways for the person developing the Sync task to test it's effectiveness in a test build?

**Comment by bmuschko** [comment]
> I sort of understand why it's like this, you should try to have a "base" kind of plugin that adds capabilities (tasks, extensions, etc), but it doesn't provide any particular configuration/defaults.

I think there's still the use case of "just" a JAR with custom tasks though I have to say it doesn't happen very often to me that I do not have to pre-configure them in _some_ way. In most cases you actually want to provide some default values which should better be set by the plugin than the custom task implementation. Either way I think it's a valid use case.

> Currently, the best way I know of to test custom task classes is the apply the Java Gradle Plugin Development plugin to the buildSrc project and create a plugin that creates a task of type CustomTask when applied to a project and then use automatic injection of plugin classes to test the task type in a test build.

The injected classpath for a plugin only takes effect if you call the method `withPluginClasspath()`. You can work around this issue by[ manually setting up the classpath](https://docs.gradle.org/current/userguide/test_kit.html#sub:test-kit-classpath-injection) and then use `buildscript` instead of `plugins` in your test. Check out this [test case](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/integTest/groovy/org/gradle/testkit/runner/enduser/GradleRunnerPluginClasspathInjectionEndUserIntegrationTest.groovy#L53) for an example.

**Comment by robbie-demuth** [comment]
> it doesn't happen very often to me that I do not have to pre-configure them in some way. In most cases you actually want to provide some default values which should better be set by the plugin than the custom task implementation

Why is it better practice to provide default values via a plugin instead of the task implementation? In our case we're trying to update a specific group tasks to be cacheable and the usages of the task are extremely limited and share common configurations, so having to create a plugin seems like overkill, even if it lives in buildSrc. 

> You can work around this issue by manually setting up the classpath and then use buildscript instead of plugins in your test. Check out this test case for an example

I hadn't thought about using the buildScript closure for this scenario, so that's a good idea and I think I'll probably take that approach. I understand the `withPluginClasspath()` functionality only modified the classpath for plugins. In general, I think it would be nice to have something along the lines of `withBuildScriptClasspath()` that could be configured from the main build. I think it would greatly improve the testing experience.

In any case, thanks for your help, @big-guy @bmuschko . For the time being, I now have a clear path forward

**Comment by bmuschko** [comment]
> Why is it better practice to provide default values via a plugin instead of the task implementation?

Mostly because of the fact that the custom task already becomes opinionated by setting default values. One has to be very mindful in picking those values. Otherwise end users might have to override those values. If you set those values from a plugin then the user can go either direction: apply the plugin and get those default values or not.

**Comment by bamboo** [comment]
I like to think of this as an application of the principle of separating mechanism (task) from policy (plugin).

**Comment by ov7a** [comment]
This is still a valid feature request

**Comment by jbartok** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

You can put something like the following into your buildscript and inject extra things into the injected plugin classpath:

```
tasks.withType<PluginUnderTestMetadata>().configureEach {
    pluginClasspath.from(...)
}
```

https://docs.gradle.org/9.5.1/javadoc/org/gradle/plugin/devel/tasks/PluginUnderTestMetadata.html#getPluginClasspath%28%29
