### ISSUE TITLE
Parallel dependency resolution for configuration cache

### ISSUE THREAD

**Issue by damianw** [gradle/gradle#27731]
### Expected Behavior

Dependencies could be resolved in parallel when using [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html).

### Current Behavior (optional)

When using [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html), dependencies which would normally be resolved at execution time are instead resolved during configuration, and aren't resolved in parallel. This means that using configuration cache could be more expensive than anticipated if resolving dependencies of affected configurations is nontrivial, and users don't get the performance benefits of parallel dependency resolution.

The underlying issue appears to be that the serialization of the configuration cache is done during task graph calculation. Ideally, resolving dependencies for the configuration cache could be done independently and in parallel.

### Context

Developers who switch branches and rebase, etc frequently are not able to make effective use of configuration cache. This is not a problem in and of itself, but not having parallel dependency resolution means that it may actually be a detriment to have configuration cache enabled at all.

**Comment by bamboo** [comment]
Depends on https://github.com/gradle/gradle/issues/29797

**Comment by abstratt** [comment]
Now that #30132 has been merged, CC and non-CC mode now work the same way wrt dependency resolution and there's no penalty for using CC anymore.
