### ISSUE TITLE
Allow test suites to reuse source sets

### ISSUE THREAD

**Issue by chaosflaws** [gradle/gradle#27758]
### Expected Behavior

Allow specifying an existing source set for a [test suite](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html).

### Current Behavior (optional)

There are no options for setting the test source set. When creating a test suite, a source set of the same name will always be generated.

### Context

When testing multi-release JARs, it is useful to be able to test identical _behaviour_ (identical test cases) on different targets.

The work-around of creating a new test suite and setting the source dirs leads to an issue with the `gradle-module-testing` plugin ([relevant issue](https://github.com/gradlex-org/java-module-dependencies/issues/80), [reproducible sample](https://github.com/chaosflaws/mrjars-test)).

One StackOverflow user basically asks for the same requirement [in this unanswered question](https://stackoverflow.com/questions/75225834/gradle-reuse-black-box-junit-test-suite-in-multiple-modules-implementing-a-shar).

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by jjohannes** [comment]
I think the use case that triggered this poposal could be solved with different concepts as I wrote here:
- https://github.com/gradlex-org/java-module-dependencies/issues/80#issuecomment-1906278394

Then it would be great to focus on the following issues instead:
- https://github.com/gradle/gradle/issues/727 | https://github.com/gradle/gradle/issues/26562
- https://github.com/gradle/gradle/issues/25808 


That is, if @chaosflaws agrees with my line of thought.

**Comment by big-guy** [comment]
Our intention here is to have one test suite to be able to compile/run on multiple Java versions, so there is no need for sharing source sets between test suites.  That's what Jendrik linked to here https://github.com/gradle/gradle/issues/25808
