### ISSUE TITLE
WinRAR archiver, a powerful tool to process RAR and ZIP files

### ISSUE THREAD

**Issue by GetStartedDOH** [gradle/gradle#27765]
"
Information about Data Protection
Controller according to General Data Protection Regulation:

win.rar GmbH
Marienstraße 12
10117 Berlin

Email: info(at)win-rar.com
Fax: +49 30 22504967

IP-Address:

We store your actual IP-address for the duration of seven days to detect attacks on and errors in our IT-systems. The legal basis for the processing is Art. 6 (1) f) General Data Protection Regulation.

Cookies:

Cookies are small text files, which can be stored on your computer. They have the purpose to store data. We need basically your consent to use cookies. In regard to cookies that are strictly necessary to provide these webpages a consent of the user is not required.

You can decide yourself whether and to what extent you want accept the use of cookies with the aid of your browser settings. At the same place you can erase cookies, which are already stored on your computer.

At Firefox you can find cookie settings in the menu Extras->Options->Data Protection.

We are using the following Cookies:
 
Webanalytics with Google Analytics:

This website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses "cookies"(see above). The information generated by the cookies about your use of the website will be transmitted to and stored by Google on servers in the United States.

Within the territory of the Member States of the European Union and other parties to the Agreement on the European Economic Area Google truncates/anonymizes the last octet of the IP address. Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA. The IP address transmitted by your browser within the frame of Google Analytics will not be associated with any other data held by Google.

We use Google Analytics to evaluate the use of our website and to improve our web services on the basis of the statistics provided by Google Analytics. The legal basis for the processing is Art. 6 (1) f) General Data Protection Regulation.

In regard to the exceptional cases in which Google transmits personal data into the USA Google is subject to the EU-US Privacy Shield, https://www.privacyshield.gov/EU-US-Framework.

Information from Google: Google Dublin, Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Ireland, Fax: +353 (1) 436 1001. Terms of Service: www.google.com/analytics/terms/gb.html, overview regarding data protection: https://support.google.com/analytics/answer/6004245?hl=en and Privacy Policy: https://policies.google.com/privacy?hl=en-GB.

You may refuse the use of cookies by selecting the appropriate settings on your browser (see above). However, please note that if you do this, you may not be able to use the full functionality of this website. Furthermore you can prevent Google’s collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available under https://tools.google.com/dlpage/gaoptout?hl=en-GB or clicking on the following link to store an opt-out-cookie, which will stop the collection and transmission of data by Google Analytics about your use of this website.

ONOFF
Activate Google Analytics now

 
Your data protection rights:

In general you have the following data protection rights in regard to win.rar GmbH:

- right of access by the data subject – Art. 15 General Data Protection Regulation
- right to rectification – Art. 16 General Data Protection Regulation
- right to erasure – Art. 17 General Data Protection Regulation
- right to restriction of processing – Art. 18 General Data Protection Regulation
- right to object – Art. 21 General Data Protection Regulation
- right to data portability – Art. 20 General Data Protection Regulation

Your option to lodge a complaint with a supervisory authority:

Supervisory Authority:

Berliner Beauftragte für Datenschutz"
 https://www.rarlab.com/cookies.htm#:~:text=Information%20about%20Data,Beauftragte%20f%C3%BCr%20Datenschutz

**Comment by cobexer** [comment]
This is noise and a waste of time, please be mindful of your open-source contributions. In case of repeated occurrences, we will take action.
