### ISSUE TITLE
Low contrast on links with code-styling in dark mode

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27763]
### Issue type

Styling or Accessibility

### Problem description

IMO the `release` text has too low contrast and is not easily legible.

* <img width="322" alt="image" src="https://github.com/gradle/gradle/assets/897017/8e697e9c-e428-4c5c-a864-8144f5ed32ba">

* <img width="317" alt="image" src="https://github.com/gradle/gradle/assets/897017/d1938bae-787f-4dfa-a4c0-17e56462b582">

I would prefer if `release` had the same colour as the rest of the highlighted link.

<img width="317" alt="image" src="https://github.com/gradle/gradle/assets/897017/8047bce3-4ca8-4555-b9ce-7f8a4ca7e5c6">

### Page with the problem

https://docs.gradle.org/nightly/userguide/cross_project_publications.html#targeting-different-platforms

**Comment by cobexer** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
