### ISSUE TITLE
Can you not set the wrapper jar SHA256 checksum in gradle-wrapper.properties?

### ISSUE THREAD

**Issue by e-ave** [gradle/gradle#27767]
### Issue type

Missing information

### Problem description

I can find documentation on
```
distributionSha256Sum=9d926787066a081739e8200858338b4a69e837c3a821a33aca9db09dd4a41026
```
But what about the other two checksums?
Complete (-all) ZIP Checksum: c16d517b50dd28b3f5838f0e844b7520b8f1eb610f2f29de7e4e04a1b7c9c79b
Wrapper JAR Checksum: d3b261c2820e9e3d8d639ed084900f11f4a86050a8f83342ade7b6bc9b0d2bdd

Will it detect if the gradle-wrapper.jar is modified? 
For maven there is `wrapperSha256Sum`
```
wrapperSha256Sum=d3b261c2820e9e3d8d639ed084900f11f4a86050a8f83342ade7b6bc9b0d2bdd
```

### Page with the problem

https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
The `distributionSha256Sum` needs to match the distribution which is referenced in the same properties file, whether it's the `-bin` or the `-all`.

For the wrapper you can use the [GitHub validation action](https://github.com/gradle/wrapper-validation-action) but having its value in the file to be validated would not provide any guarantee.
