### ISSUE TITLE
Mysterious jdk-toolchains plugin

### ISSUE THREAD

**Issue by ilya-g** [gradle/gradle#27802]
### Current Behavior

Gradle provides a built-in plugin https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.kotlin.dsl/jdk-toolchains.html that is said to be implemented by `org.gradle.api.plugins.JdkToolchainsPlugin`. However no such class can be found in the Gradle code base and applying it in a project leads to an error:
```
* What went wrong:
Error resolving plugin [id: 'org.gradle.jdk-toolchains']
> Could not find implementation class 'org.gradle.api.plugins.JdkToolchainsPlugin' for plugin 'org.gradle.jdk-toolchains' specified in jar:file:/C:/Users/...../.gradle/wrapper/dists/gradle-8.4-bin/1w5
dpkrfk8irigvoxmyhowfim/gradle-8.4/lib/plugins/gradle-plugins-8.4.jar!/META-INF/gradle-plugins/org.gradle.jdk-toolchains.properties.
```

### Expected Behavior

No errors about not found plugin implementation classes when applying built-in plugins.

### Steps to Reproduce

Gradle Kotlin DSL:
```
plugins {
    `jdk-toolchains`
}
```

### Gradle version

8.4

**Comment by cobexer** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
***
Looks like the class no longer exists and maybe the upgrade guide entry about it should also be cleaned up.
