### ISSUE TITLE
mavenContent snapshotsOnly() has no effect for repositories in pluginManagement

### ISSUE THREAD

**Issue by spand** [gradle/gradle#27813]
### Current Behavior

It seems that for repositories defined in pluginManagement mavenContent snapshotsOnly has no effect. Related question on Slack: https://www.linen.dev/s/gradle-community/t/16335756/any-particular-reason-this-allows-me-to-find-dependencies-wi#5e73bc85-9902-4b1e-bc30-39b3809a8b32

### Expected Behavior

I expect it to fail with
Plugin [id: 'com.gradle.common-custom-user-data-gradle-plugin', version: '1.12.1'] was not found in any of the following sources:

as can be seen by either using mavenLocal or the maven repo in settings.gradle.kts

### Context (optional)

I assume it is because DefaultMavenRepositoryContentDescriptor.asMutableCopy() does not copy over the private variables snapshots and releases hence the settings being forgotten.

### Steps to Reproduce

In settings.gradle.kts flip between the two repositories defined. The example plugin should not be found in either.

Reproducer here https://github.com/spand/snapshotsonlybug

### Gradle version

8.4

**Comment by cobexer** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
