### ISSUE TITLE
Re-implement replacement for null diagnosticlistener

### ISSUE THREAD

**Issue by donat** [gradle/gradle#27823]
This is sort of a feature and a regression at the same time.
As we introduced problem reporting in the [Java compile task](https://github.com/gradle/gradle/blob/f796b166368355a4c62fbbfb3157bd29c3f2a25c/platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java), we needed to [supply a value](https://github.com/gradle/gradle/blob/19b71ed5796b79d96fe209240c259259762f98d7/platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java#L79) to the diagnostic listener parameter.

This caused an effect not accounted for: _the classic error message printed to `stderr` no longer appears_.
This is a feature that we need to keep until at least 9.0, as this is a major change in how we would represent problems in the console.

We probably have two feasible solutions:
  1. Figure out what is the behavior for the JDK when the value is `null`, and figure out a way to re-enable it
  2. Reimplement the feature by ourselves.

(Personally, I'm not that hopeful of 1., but I will still attempt to discover the pieces to learn about some blockers)

**Comment by donat** [comment]
@hegyibalint ffr: I browsed the JDK sources and and found a couple of classes involved in the compiler message rendering:
- com.sun.tools.javac.util.AbstractDiagnosticFormatter (and subclasses)
- com.sun.tools.javac.util.JCDiagnostic
- com.sun.tools.javac.util.Log

**Comment by hegyibalint** [comment]
Also dropping here [`FormattedDiagnostic`](https://github.com/bazelbuild/bazel/blob/5ab21e057775909c746249078705d7e7f4cbfe0a/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/FormattedDiagnostic.java#L36) from Bazel

**Comment by hegyibalint** [comment]
The most painful part probably will be the probable adoption away from [`JavaCompile.CompileTask`](https://github.com/openjdk/jdk/blob/729ae1d78716a3830837e49376b5340eb60f9449/src/java.compiler/share/classes/javax/tools/JavaCompiler.java#L276), and use [`JavacTool`](https://github.com/openjdk/jdk/blob/729ae1d78716a3830837e49376b5340eb60f9449/src/jdk.compiler/share/classes/com/sun/tools/javac/api/JavacTool.java#L125-L131) directly[^1].

This is (probably) going to be necessary to register a logger and a diagnostic listener at the same time; as stated in the topmost comment, when using `JavaCompile.CompileTask` and supplying a non-null `diagnosticListener`, we lose the console output, as the default logging is turned off.

[^1]: the `JavacTool` class looks to me like the primary implementor of the `JavaCompile.CompileTask` interface.
