### ISSUE TITLE
The use of TestNG suites in combination with maxParallelForks causes tests to be execute multiple times

### ISSUE THREAD

**Issue by mondrejko** [gradle/gradle#2783]
I am trying to performance tune our build with Gradle 4.1. For running our Java tests, I have set
 
    maxParallelForks = project.gradle.startParameter.maxWorkerCount
    forkEvery = 1000
 
Prior to this change, the test task reports that 4,329 tests were run. After making the change, the same test task reports that 34,632 tests were run (this is exactly 8X the original count, which is what maxParallelForks is set to). And, looking at the before and after (sorted) lists of tests that were run, it appears that each test is reported 8 times. Is this a know issue? Anything that we can do about it?

**Comment by mondrejko** [comment]
Just to follow-up with a couple of additional items that I have confirmed:
1. The number of tests reported does change in proportion to the maxParallelForks value and the number of tests run is a multiple of the original (i.e., 1 fork = 4,329 tests run, 4 forks = 17,316, 8 forks = 34,
2. In each fork, all tests are run, i.e., our 4,329 tests are run for EACH and EVERY fork. Consequently, forking tests does not improve performance.

**Comment by bmuschko** [comment]
Could you please provide some additional information?

- Did you experience the behavior to become broken with a specific version of Gradle?
- Do you have TestNG [set up to use multiple threads](http://howtodoinjava.com/testng/testng-executing-parallel-tests/)? I kind of suspect that it might have something to do with that.
- Do you see the faulty behavior even when not setting `forkEvery`?
- Could you provide us with a build scan?

**Comment by mondrejko** [comment]
* Did you experience the behavior to become broken with a specific version of Gradle? 
_Did not try setting the maxParallelForks until Gradle 4.0_
* Do you have TestNG set up to use multiple threads (http://howtodoinjava.com/testng/testng-executing-parallel-tests/)? I kind of suspect that it might have something to do with that. 
_No_ 
* Do you see the faulty behavior even when not setting `forkEvery`? 
_Yes_

**Comment by mondrejko** [comment]
Is it possible to save a build-scan locally for a build to attach? Or, export from Gradle Enterprise?

**Comment by bmuschko** [comment]
So far as was not able to reproduce the issue you are seeing. For that purpose I create a test project: https://github.com/bmuschko/parallel-testng. Could you please try this out in your environment?

1. Check out project.
2. Run `./gradlew createTests`.
3. Run `./gradlew clean test`.
4. Open report under `build/reports/tests/test/index.html`. The overall test number should say 1000.

Please also have a look at the configuration in the `build.gradle` file to see if you find any difference to your setup. What version of TestNG are you using?

BTW: In Gradle 4.1 we introduced the rendering of [parallel test execution in the console](https://docs.gradle.org/current/release-notes.html#console-displays-parallel-test-execution). It seems like that is not working properly when using TestNG instead of JUnit. I logged the issue https://github.com/gradle/gradle/issues/2786 for it and will have a look.

**Comment by mondrejko** [comment]
The project isn't successful for me, which leads to another variable that may be at play. We are still compiling and running our build with JDK 7.1

**Comment by bmuschko** [comment]
> The project isn't successful for me, which leads to another variable that may be at play. We are still compiling and running our build with JDK 7.1

What error message are you seeing? The code isn't using any specific Java 8+ syntax.

> Please also have a look at the configuration in the build.gradle file to see if you find any difference to your setup. What version of TestNG are you using?

Anything you notice here?

**Comment by mondrejko** [comment]
The error message is that the library was compiled with version 52.0 and the latest supported by the JRE is 51.0.

We are currently using TestNG 6.9beta

**Comment by bmuschko** [comment]
Maybe the TestNG version used in the example was compiled with Java 8. I just changed the TestNG version in the example to use a Java 7-compatible version. It tested it out with Java 7. Can you pull from the repository and try again?

BTW: I recommend not using a beta version of an external library. Most of time these versions are not production-ready and indicate that they are still under active development. I used 6.9.13.6 which will probably work for your project as well.

**Comment by mondrejko** [comment]
Agreed on the external version library. This is just latest that was available when we last upgraded and we needed 6.9 to get a fix for another issue. Then, it just stuck for a while...

**Comment by mondrejko** [comment]
The latest sample works for me also (1000 tests executed). Will look tomorrow into our specific configuration to see what we may be doing that can cause the multiple executions (have to leave soon for the evening).

**Comment by mondrejko** [comment]
I have replicated the issue with the sample code by adding use of a suite file. In `build.gradle`:
```
useTestNG() {
  options.suites file('testng.xml')
}
```
My `testng.xml` was simply
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="module suite" verbose="1" time-out="0">
  <test name="module suite tests">
    <classes>
      <class name="MyTest1" />
    </classes>
  </test>
</suite>
```
I just included a single test class and all the tests were executed for each thread (in my case 40 tests were run, 5 tests in the class for 8 threads).

**Comment by bmuschko** [comment]
Thanks for providing the additional information. I wasn't aware of it but this has been an issue for a long time and [has been reported before](https://discuss.gradle.org/t/unit-tests-seem-to-run-multiple-times-when-using-testng-with-suites-xml-and-maxparallelforks-1/2183/4). We just didn't get around to having a deeper look yet. [This issue](https://github.com/gradle/gradle/issues/2603#issuecomment-324478454) for JUnit suites is probably related as well.

I tried it out with Gradle 3.0 and it's already behaving the way you reported it. One way to work around the issue could be to set up different source sets per "suite" that you could be run with separate `Test` tasks. That would mean not using the TestNG suite feature. Not sure if that's an option for you.

**Comment by mondrejko** [comment]
I removed use of the suites file to test and the tests are no longer executed multiple times. 

In looking at the timeline in the build scan, the test tasks still show in one pipe and the execution time seems about the same as without parallelism. Should Gradle Enterprise show the test task executing in multiple threads? How can I verify that the tests are actually running in multiple threads?

**Comment by bmuschko** [comment]
> In looking at the timeline in the build scan, the test tasks still show in one pipe and the execution time seems about the same as without parallelism.

I believe build scans do not render this information _yet_.

> How can I verify that the tests are actually running in multiple threads?

They would actually be executed in different test JVMs. You will be able to see that more clearly with Gradle 4.2 that [fixes the console display for test execution with TestNG](https://github.com/gradle/gradle/issues/2786).

**Comment by big-guy** [comment]
@mondrejko you can confirm that you're getting parallel test execution by looking at the amount of time spent executing a particular test task when compared to the amount of time spent executing tests in the Tests card:
![image](https://user-images.githubusercontent.com/5387972/29723319-260ec970-8992-11e7-9338-dc1b9832aec0.png)

Here you can see we spent 13s executing `javascript:integTest`, but we spent over 40s in "CPU time" executing the different packages.

**Comment by bmuschko** [comment]
I added test cases for this issue: https://github.com/gradle/gradle/commit/9c3d9e1e1d1d2d0f402e36d18b2229e137098c68

**Comment by samsieber** [comment]
@bmuschko I would be interested in trying to fix this. Poking around the source code for gradle, it looks like right now that the TestNGTestClassProcessor gets handed its classes to run on a per thread basis, but loads the suites from the options. So would we simply add a mechanism similar to `processTestClass` except for suites?
