### ISSUE TITLE
Add an API to access the Gradle normalized path of input files

### ISSUE THREAD

**Issue by martinbonnin** [gradle/gradle#27836]
### Expected Behavior

Allow to write task whose output depends on the Gradle normalized path of `RELATIVE` inputs like this:

```kotlin
abstract class DumpNormalizedPathsTask: DefaultTask() {
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceFiles: ConfigurableFileCollection
  
  @TaskAction
  fun taskAction() {
    val output = buildString {
      sourceFiles.withNormalizedPath().map {
        // 'it' would be something like FileWithNormalizedPath(val normalizedPath: String, val file: File)
        append(it.normalizedPath) 
        append(it.file.readText()) 
      }
    }
    
    // write output to the output file, ....
  }
}
```

### Current Behavior (optional)

I haven't found an API to do so. 

The closest solution I found is to zip/tar all input files but it's adding some uneeded I/O.

Is there another solution?

### Context

This is a follow up from https://www.linen.dev/s/gradle-community/t/16341786/if-i-have-this-get-inputfiles-get-pathsensitive-pathsensitiv#5980a277-f533-4ea5-9a67-3689e2a8a5fd

**Comment by HappyLife2** [comment]
Based on your description, it seems you want to create a Gradle task that can access the normalized path of input files. Here’s a possible solution using Java’s java.nio.file.Paths and java.nio.file.Path:

Kotlin

import java.nio.file.Paths

abstract class DumpNormalizedPathsTask: DefaultTask() {
  @get:InputFiles
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val sourceFiles: ConfigurableFileCollection
  
  @TaskAction
  fun taskAction() {
    val output = buildString {
      sourceFiles.map { file ->
        val normalizedPath = Paths.get(file.absolutePath).normalize().toString()
        append(normalizedPath)
        append(file.readText())
      }
    }
    
    // write output to the output file, ...
  }
}

In this code, Paths.get(file.absolutePath).normalize().toString() is used to get the normalized path of each file. [This should work as long as the file paths are not symbolic links](https://stackoverflow.com/questions/12690652/how-to-fix-path-manipulation-vulnerability-in-some-java-code)[1](https://stackoverflow.com/questions/12690652/how-to-fix-path-manipulation-vulnerability-in-some-java-code).

[As for zipping/tarring all input files, it’s indeed an option but it might add unnecessary I/O operations](https://stackoverflow.com/questions/19452906/how-can-i-create-a-zip-in-gradle-from-a-list-of-files)[2](https://stackoverflow.com/questions/19452906/how-can-i-create-a-zip-in-gradle-from-a-list-of-files)[3](https://docs.gradle.org/current/userguide/working_with_files.html)[4](http://sorcersoft.org/project/site/gradle/userguide/working_with_files.html)[5](https://discuss.gradle.org/t/how-do-i-create-a-tar-file-from-selected-files-from-different-directories/5512)[6](https://stackoverflow.com/questions/41136760/how-to-put-folder-into-a-tar-file-with-gradle). If the number of files is large, it could slow down the task. The solution above should be more efficient as it directly accesses the file paths without the need for additional I/O operations.

Kindly note that this solution assumes that the files are located in the local file system and that the file paths are not symbolic links. If the files are located on a remote system or if the paths are symbolic links, a different approach might be needed. If that’s the case, please provide more details so I can give a more accurate solution.

Also, please thoroughly test this solution in your environment to ensure it works as expected. If you encounter any issues, feel free to ask for further assistance.

**Comment by martinbonnin** [comment]
> val normalizedPath = Paths.get(file.absolutePath).normalize().toString()

@HappyLife2 I am confused. I'm not looking for the filesystem normalized path but for the [Gradle normalized path](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitivity.html#RELATIVE). This is the path that Gradle uses when `PathSensitivity.RELATIVE` is used to determine if tasks are up-to-date.

`Path.normalize()` is not going to help there.

**Comment by martinbonnin** [comment]
Alternatively to `ConfigurableFileCollection.withNormalizedPath()`, adding a `ConfigurableFileCollection.root()` returning the roots of the `FileTrees` could be useful. The normalization logic could be replicated in the task but also it could help outputing better diagnostics:

```kotlin
  @TaskAction
  fun taskAction() {
    if (sourceFiles.isEmpty()) {
      error("No source file found in ${sourceFiles.joinToString()}")
    }
    
    // more stuff ...
  }
```

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by lptr** [comment]
For `RELATIVE` normalization you should be able to access the relative paths of the entires by visiting the `FileCollection` as a `FileTree`.

```groovy
sourceFiles.asFileTree.visit { element ->
  println element.path // <-- this is the relative path of the entry as a String
  println element.relativePath // <-- this is the relative path of the entry as a RelativePath
}
```

See:

https://github.com/gradle/gradle/blob/20d424990144986eb315bda3941a092537c47beb/subprojects/core-api/src/main/java/org/gradle/api/file/FileTreeElement.java#L87-L100

**Comment by martinbonnin** [comment]
Works like a charm, thanks!

**Comment by martinbonnin** [comment]
Bumped into another issue. Looks like the normalized path is lost with workers? Opened a follow up issue [here](https://github.com/gradle/gradle/issues/28147).
