### ISSUE TITLE
The AsciiDoc preprocessor directives is unresolved in user guide (pdf)

### ISSUE THREAD

**Issue by foogao** [gradle/gradle#27847]
### Issue type

Wrong or misleading information

### Problem description

This happened in version 8.5, the format is pdf.
![image](https://github.com/gradle/gradle/assets/688065/914e0491-21cd-4a7b-9490-73db3202a3cc)

### Page with the problem

https://docs.gradle.org/current/userguide/getting_started_eng.html

**Comment by ljacomet** [comment]
Fixed with #27857
