### ISSUE TITLE
Missing information on how to refer to dependencies in version catalog

### ISSUE THREAD

**Issue by Herudaio** [gradle/gradle#27854]
### Issue type

Wrong or misleading information

### Problem description

The dependencies are declared with `-`, but are referred to with `.`. The page does not mention that explicitly and it's only implied from the examples. 

### Page with the problem

https://docs.gradle.org/current/userguide/dependency_management_basics.html

**Comment by Vampire** [comment]
It is described on the page where the actual version catalogs are documented: https://docs.gradle.org/current/userguide/platforms.html#sub:mapping-aliases-to-accessors

**Comment by Herudaio** [comment]
That's true. Information is out there.

It's not great form the user learning Gradle for the first time perspective though. The page I mentioned is in the promoted section for new users (getting started, core concepts, etc.) and they will find it first. From there there is no link to more advanced materials like the page you linked.

When I stumbled upon this page I had real problems understanding the code example whether some part of identifier is magically added (cause of dots), before analyzing lines one by one to find a pattern. Adding a small tip could alleviate that pain and linking to the page that you mentioned for digging deeper would also benefit learning if the user wants to dig deeper.

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue.
