### ISSUE TITLE
Gradle DSL method not found: 'jacocoTestCoverageVerification()'

### ISSUE THREAD

**Issue by Leo-Lei** [gradle/gradle#2788]
I meet the following error while using the Gradle jacoco plugin:
`Gradle DSL method not found: 'jacocoTestCoverageVerification()'`

Bellow is my environment:
Gradle: 4.1
Java: 1.8

and my build.gradle file:
```
group 'com.leibangzhu'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: "jacoco"

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
}

jacoco {
    toolVersion = "0.7.6.201602180812"
    reportsDir = file("$buildDir/customJacocoReportDir")
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.5
            }
        }

        rule {
            enabled = false
            element = 'CLASS'
            includes = ['org.gradle.*']

            limit {
                counter = 'LINE'
                value = 'TOTALCOUNT'
                maximum = 0.3
            }
        }
    }
}

```

I found there is only a jacocoTestReport task, but no jacocoTestCoverageVerification.

**Comment by Leo-Lei** [comment]
Some update, it seems that I installed the Gradle via the Homebrew, and some problem occurred, it is tricky. When I reinstall the Gradle manually, i.e. download the binary distribution, everything seems works.

**Comment by blindpirate** [comment]
That's weird. We'll look into this. Thanks for reporting.

**Comment by bmuschko** [comment]
@Leo-Lei You were probably using an older version of Gradle that didn't have the feature yet. I am closing this now as it works for you.
