### ISSUE TITLE
Distribution plugin adds assemble dependencies in wrong order

### ISSUE THREAD

**Issue by mhalver** [gradle/gradle#2789]
When using the distribution plugin, the assemble task picks up dependencies on the distZip and distTar tasks in the wrong order.

When running a simple test build (producing a main artifact and a sources artifact) using the java plugin and the distribution plugin, the assemble task executes in the following order:

- distTar
- distZip
- compileJava
- processResources
- classes
- jar
- sourcesJar
- assemble

However, the distTar and distZip task should occur last (after sourcesJar - in particular after all artifacts are built).  As it stands, if I had ran assemble and then modified my code and ran it again, my distributions folder would contain distributions with the previously built code instead of my newly changed and built code (which would, of course, be correct in my libs folder).

This means that I must run

```
gradle assemble
gradle assembleDist
```

as two commands instead of `gradle assemble` or even `gradle assemble assembleDist`.  Either the dist* tasks shouldn't be added to assemble, or they should be assured to run after jar.

Here is a simple project demonstrating this

**build.gradle**
```
buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'java'
    id 'distribution'
}

group = "com.test"

distributions {
    main {
        contents {
            from libsDir
        }
    }
}

task sourcesJar(type: Jar) {
	classifier 'sources'
	from sourceSets.main.allSource
}

artifacts {
	archives sourcesJar
}
```

**settings.gradle**
```
rootProject.name = 'Testproject'
```

**src/main/java/com/test/Test.java***
```
package com.test;

public class Test {
	public void main(String... args) {
		System.out.println("testing");
	}
}
```

I am using version 4.1 (but this is the same in 4.0) on a Windows 7 machine with Java 8.

**Comment by big-guy** [comment]
```
distributions {
    main {
        contents {
            from libsDir
        }
    }
}
```

This is telling Gradle to copy the `libsDir` into the distribution, but it doesn't setup any dependency information (because `libsDir` is just a `File`).  You can either add these dependencies manually or you can change your script to:
```
distributions {
    main {
        contents {
            from jar
            from sourceJar
        }
    }
}
```

Or you can use the application plugin (which configures the `main` distribution in a particular way).

**Comment by mhalver** [comment]
Ok, that makes sense.  I was doing it the same way as the examples that I had read, but they always run this as two separate commands (with assemble and then assembleDist), but I thought I should be able to do it together, but was seeing this behavior.  I'll make that change.

Is there a way to copy the contents of the artifacts closure over to this in order to avoid listing them twice (in artifacts and distributions)?  Something like (although this is probably not the syntax)

```
artifacts {
    archives sourcesJar
}

distributions {
    main {
        contents += artifacts.allArtifacts
   }
}
```

My real project has several more archives added to that artifacts closure.

**Comment by big-guy** [comment]
> I don't want to use the application plugin, because I am creating a library and it seems to be leaning towards standalone applications. Plus, I actually use the groovy plugin instead of the java plugin which is added by the application plugin (all my testing code is written in groovy using spock).

That's reasonable. I only suggested the application plugin if that was what you were ultimately trying to do.  The Groovy plugin applies the Java plugin too (it's built on top of it), so that wouldn't be a problem.

> Is there a way to copy the contents of the artifacts closure over to this in order to avoid listing them twice (in artifacts and distributions)?

The most straightforward way of doing this is a little awkward because both `distZip` and `distTar` are artifacts of the project too.

I think something like this works:
```
distributions {
    main {
        contents {
            def publications = configurations.archives.artifacts.matching {
                // filter out the distZip and distTar artifacts
                it.extension != 'zip' && it.extension != 'tar'
            }
            // Lazily, convert from Set<PublishArtifact> -> FileCollection and retain dependency info by hooking back into PublishArtifact
            from files({ publications*.file }).builtBy(publications)
        }
    }
}
```

**Comment by mhalver** [comment]
That does work.  Thank you.

However, I ultimately decided to go with

```
def artifactTasks = [sourcesJar, /* other artifact tasks /*]

artifacts {
    artifactTasks.each {
        archive it
    }
}

distributions {
    main {
        contents {
            (artifactTasks + jar) .each {
                from it
            }
        }
    }
}
```

Neither method is particularly pretty or declarative, but I think this serves my needs, and it is easy to add a new artifact by adding to that list.

**Comment by develeper84** [comment]
Can some one help me, how can i remove jar file from my artifacts creation.
So, i created .tar.gz file in my project but when i published .tar.gz file. it is publishing .jar file also.

distributions {
	main {
			into ("/")
			from libsDir
			fileMode = 0775
			include '*.jar'
			rename '.*.jar', "${project.name}.jar"
			from "env", "scripts"
			include '*.conf', '*.sh', '*.mf'
		}
	}
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'distribution'
