### ISSUE TITLE
Automatic dependency declaration in combination with initscript doesn't seem to work in all cases with gradle 4.X

### ISSUE THREAD

**Issue by stmlange** [gradle/gradle#2794]
Hi,
I experienced a strange issue with automatic dependency declaration in combination with initscript.
In general what I'm doing is declaring a dependency and repository inside the initscript and use it inside the build.gradle. The dependency is declared with projectsLoaded->allprojects->buildscript->dependencies

For full reference I have attached a [sample.zip](https://github.com/gradle/gradle/files/1252519/sample.zip) config where I currently can reproduce the issue. 
The file includes three files
* init-gradle-3.X.gradle -- initscript
* init-gradle-4.X.gradle -- initscript
* build.gradle -- default build script

### Expected Behavior

* `gradle --init-script init-gradle-3.X.gradle foo` works with every gradle version

### Current Behavior

* `gradle --init-script init-gradle-3.X.gradle foo` works fine up to gradle 3.X and *breaks* with gradle 4.X
* `gradle --init-script init-gradle-4.X.gradle foo` works fine up to gradle 4.X (tested gradle 2.X and gradle 3.X)

### Context

I use this to maintain automatic dependency and repository injection for multiple projects.

### Steps to Reproduce (for bugs)

Download and extract
[sample.zip](https://github.com/gradle/gradle/files/1252519/sample.zip)

Use gradle 4.X and execute
 `gradle --init-script init-gradle-3.X.gradle foo`
The
`gradle --init-script init-gradle-4.X.gradle foo`
command works fine.

### Your Environment

```
------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Linux 4.10.0-32-generic amd64
```

```
------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Linux 4.10.0-32-generic amd64
```

```
------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Linux 4.10.0-32-generic amd64
```

**Comment by blindpirate** [comment]
Thanks for reporting. I'm glad to see you have solved this 

This is due to an execution order change in Gradle 4.0. Basically, `projectsLoaded` and `allprojects` are both registering closures that won't be executed immediately, so some unexpected issues may happen when they are nested. This should be avoided. I'll close this, please feel free to reopen it if you still have questions.
