### ISSUE TITLE
Configuration Cache complains about class that is not used

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27944]
### Current Behavior

Configuration Cache complains about class that is not used

### Expected Behavior

Configuration Cache does not complain about class that is not used

### Context (optional)

https://github.com/gradle/gradle/issues/24030

### Steps to Reproduce

1. download and unpack [demo.zip](https://github.com/gradle/gradle/files/14158674/demo.zip)
2. cd into `config-cache`
3. run `./gradlew dokkaGen --configuration-cache`
4. observe error
    ```
    3 problems were found storing the configuration cache, 1 of which seems unique.
    - Task `:dokkatooGeneratePublicationGfm` of type `dev.adamko.dokkatoo.tasks.DokkatooGenerateTask`: cannot serialize object of type 'org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration', a subtype of 'org.gradle.api.artifacts.Configuration', as these are not supported with the configuration cache.

    ```
5. search in the project, and see there are no usages of `DefaultUnlockedConfiguration` 
7. Look in `DokkatooGenerateTask`, and see there are no usages of `Configuration`

### Gradle version

8.6

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Configuration cache can serialize transitive dependencies of your data that are not used directly in your code.
As you can see in the message, `DefaultUnlockedConfiguration` is an internal Gradle implementation of `org.gradle.api.artifacts.Configuration`. Probably, it was mistakenly added to the configuration cache by the complex build in your reproducer. If you feel that is a Gradle error, please, isolate the issue and verify that your build is correct.
