### ISSUE TITLE
Support for declaring transient configuration (e.g. short-lived access tokens)

### ISSUE THREAD

**Issue by bes** [gradle/gradle#2796]
When the Gradle Daemon is enabled, a plugin configuration block (e.g. the registry password for the excellent Docker Plugin https://github.com/bmuschko/gradle-docker-plugin) that configures transient credentials (An access token with a 15 minute expiry time), it's quite annoying to have to do `./gradlew --stop` just to refresh the credentials.

### Expected Behavior

The "Finding and using credentials" document https://github.com/gradle/gradle/blob/ae63d4aa1e554a16cbf5cc80bf5905870b4f10a6/design-docs/finding-and-using-credentials.md describes some different use cases for different types of credentials, but it doesn't mention temporary or transient credentials, as far as I can tell.

I would expect a way to declare that a property in a configuration block is transient, so that it may be (re-)generated as appropriate.

### Current Behavior

Currently if I have code that generates an access token, the Gradle Daemon will cache it along with the configuration and eventually the access token will time out, forcing me to kill the Gradle Daemon.

### Context

I want to be able to declare and configure transient/temporary variables (mainly access tokens) in a way that makes Gradle aware that they can expire and that they are not cacheable.

### Steps to Reproduce (for bugs)

Using the Gradle Docker Plugin as an example, with the Gradle Daemon enabled, and using Google Default Application Credentials:

```
docker {
    url = "unix:///var/run/docker.sock"

    registryCredentials {
        // https://cloud.google.com/container-registry/docs/advanced-authentication
        url = 'https://gcr.io'
        username = "oauth2accesstoken"
        password = "${-> GoogleCredential.getApplicationDefault().getAccessToken()}" // This is more complicated in my setup, I have pasted the getAccessToken() code here to make it extra clear, that's why I'm using the ${-> format
        email = "wellformed@wellformed.com"
    }
}
```

### Your Environment

* macOS Sierra
* Gradle Daemon enabled
* org.gradle.parallel=true
* org.gradle.caching=true

Thanks for a great ecosystem!

**Comment by blindpirate** [comment]
I think a better solution may be add an action to refresh token and let all necessary tasks depend on it, e.g:

```
task refreshToken {
    project.ext.lastTokenRefreshTime=0L
    doLast {
         long current=System.currentTimeMillis();
         if(current-project.ext.lastTokenRefreshTime>5*60*1000L){
              // cache time 5 min
              project.docker {
                  registryCredentials {
                      password = GoogleCredential.getApplicationDefault().getAccessToken()
                  }
              }
              project.ext.lastTokenRefreshTime=current
         }
    }
}

yourTask.dependsOn refreshToken
```

**Comment by bes** [comment]
Thank you for that answer, it is perfect!
