### ISSUE TITLE
Document how to use configuration cache with `latest.release` dependency version

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#27975]
### Issue type

Missing information

### Problem description

When the configuration cache is enabled, but you declare version dependencies upon `latest.release` you get the following:

> Calculating task graph as configuration cache cannot be reused because cached version information for [dependency group]:[dependency name]:latest.release has expired.

This is very helpful information, but there's no meaningful description on how to change the behaviour to solve this problem.

Presumably, there are two options:

1. Increase the default length that `latest.release` versions are cached. Which is currently documented as being 24 hours, but is clearly incorrect when dealing with the configuration cache: https://docs.gradle.org/current/userguide/dynamic_versions.html#:~:text=By%20default%2C%20Gradle%20caches%20dynamic%20versions%20for%2024%20hours.
2. Fix to a specific version.

### Context (optional)

Ideally, I'd like to use the configuration cache with a dynamic version like `latest.release`, with a short but sane default for the TTL on the dependency.

### Page with the problem

https://docs.gradle.org/current/userguide/configuration_cache.html

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

@gradle/bt-configuration Should the error message and docs be updated or there is something else that can be improved in the described scenario?

**Comment by mlopatkin** [comment]
>Which is currently documented as being 24 hours, but is clearly incorrect when dealing with the configuration cache:

The intended behavior of the configuration cache is to expire the entry when the resolution cache expires, so CC should be valid for 24 hours as well. The interval is configured by the `cacheDynamicVersionsFor` resolution configuration too. If that isn't happening, can you please share a reproducer?

Given that, I'm not sure what is being requested here. @JLLeitschuh do you think we need to additionally document configuration cache expiration policy? It should the same as the dependency caching policy - if not, it is a bug to fix.

**Comment by JLLeitschuh** [comment]
When I run unit tests with IJ with the configuration cache turned on, I get a warning, every time, that the CC state is invalid due to the use of `latest.release` as a version for a dependency.

Let me see if I can come up with a minimal reproducer
