### ISSUE TITLE
"For more information about parallel builds, check here" links back to itself.

### ISSUE THREAD

**Issue by sebastiancarlos** [gradle/gradle#27983]
### Issue type

Wrong or misleading information

### Problem description

The section at https://docs.gradle.org/current/userguide/performance.html#parallel_execution ends with the sentence "For more information about parallel builds, check out the [parallel builds documentation](https://docs.gradle.org/current/userguide/performance.html#parallel_execution)."

I think it should be fixed or removed.

### Page with the problem

https://docs.gradle.org/current/userguide/performance.html#parallel_execution

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue.
