### ISSUE TITLE
Typo in link at page docs.gradle.org/current/userguide/build_file_basics.html

### ISSUE THREAD

**Issue by msantondaimler** [gradle/gradle#27981]
### Issue type

Typo (please open a PR instead)

### Problem description

At the bottom of the page docs.gradle.org/current/userguide/build_file_basics.html
on the very last text line of the guide thre is a wrong text for the link to the next section.
"Consult the Writing Settings File" should be
"Consult the Writing Build Scripts"

### Page with the problem

https://docs.gradle.org/current/userguide/build_file_basics.html

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue.
