### ISSUE TITLE
Dark mode scroll bar is hard to see against the dark background

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#27996]
### Issue type

Styling or Accessibility

### Problem description

On macOS + Chrome the scrollbar is black, which is hard to see against the dark background.

Without the scrollbar being easily visible it is harder to keep track of my place in long docs pages.

Is it possible to make the scroll bar more visible in dark mode?

https://github.com/gradle/gradle/assets/897017/1551f2ca-b6a2-4d63-bf14-e073dcbb6237

### Context (optional)

On macOS + Firefox the scrollbar is visible on both white + dark mode.

https://github.com/gradle/gradle/assets/897017/2541b670-a145-4c3c-8b2c-4fd781b3eb84

### Page with the problem

https://builds.gradle.org/repository/download/Gradle_Master_Check_BuildDistributions/77650148:id/distributions/gradle-8.7-docs.zip!/gradle-8.7-20240206230028%2B0000/docs/userguide/userguide.html

**Comment by aSemy** [comment]
ping @lkasso 👋, in case you'd like to include this in https://github.com/gradle/gradle/pull/27962 :)

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritized by them.
