### ISSUE TITLE
After upgrading from 3.5 to 4.0, Java tests run twice

### ISSUE THREAD

**Issue by jyemin** [gradle/gradle#2801]
### Expected Behavior
Given test sourceSets defined like this:

        test {
            groovy.srcDirs = ['src/test/functional', 'src/test/unit']
            java.srcDirs = ['src/test/functional', 'src/test/unit']
        }

where the directories contain a mix of Groovy-based and Java-based tests, I expect the Java-based tests to run only once, as they did up until Gradle 4.0.

### Current Behavior
Groovy-based tests are run once, while Java-based tests are run twice.  Was this behavior change intentional?

### Steps to Reproduce (for bugs)
Using https://github.com/mongodb/mongo-java-driver, run this build command:

   /gradlew --info bson:clean bson:test

Build scan: https://gradle.com/s/t6p3ftwice6q4

**Comment by blindpirate** [comment]
See #2315 .

**Comment by jyemin** [comment]
No, it looks quite different.

**Comment by jyemin** [comment]
I worked around this by removing java.srcDirs entirely.  See https://github.com/mongodb/mongo-java-driver/commit/96219e615913b1038802df6bc39288537342c24e. 

Is this the recommended solution?

**Comment by blindpirate** [comment]
I've confirmed this and I'll take a look at it, thanks for reporting. Glad you have a workaround.

**Comment by blindpirate** [comment]
What you have done is exactly the right thing. In `4.0`, Gradle will generate class files in separate output directories for each language, see [here](https://docs.gradle.org/4.0/release-notes.html?utm_source=hashnode.com#multiple-class-directories-for-a-single-source-set). In your case, 
 `javac` and `groovyc` will both compile `.java` files in test directories and generate duplicate `class` files into different output directories. So they will be executed twice.

**Comment by oehme** [comment]
@jyemin What the code in your original post does is telling Gradle: Compile this code twice, once with javac, once with groovyc. 

Instead of removing the possibility for Java code completely, I recommend you follow the directory layout that Gradle uses by default. `src/test/java`, `src/test/groovy`, `src/functionalTest/java`, `src/functionalTest/groovy`.
