### ISSUE TITLE
Codenarc plugin needs the groovy plugin to be applied in order for tasks to populate

### ISSUE THREAD

**Issue by swhittaker** [gradle/gradle#2804]
### Expected Behaviour
Expected that writing: `apply plugin: 'codenarc'` would result in the codenarcMain and codenarcTest tasks becoming available.

### Current Behavior
No new tasks appear unless you also use `apply plugin: 'groovy'`

### Context
Couldn't use the plugin without discovering the groovy workaround

### Steps to Reproduce (for bugs)
Create a build.gradle file with 
```
 apply plugin: 'java'
 apply plugin: 'codenarc'
```

then try to use the codenarcMain task.

it works if you add  `apply plugin: 'groovy'`

### Your Environment
Version 4.1

**Comment by big-guy** [comment]
What would you expect the CodeNarc tasks to do if you only have Java code?

**Comment by swhittaker** [comment]
Alright looks like I was being dumb, my assumption was that codenarc was code inspection for Java - obviously it isn't!

Should the codenarc plugin perhaps warn in some way if the groovy plugin isn't applied or are there reasons for not doing that?

**Comment by big-guy** [comment]
Potentially, you could have a different plugin that builds Groovy code and the Gradle CodeNarc plugin would work with it.  There's also an ordering issue. Both of these behave the same:

```
apply plugin: 'groovy'
apply plugin: 'codenarc'
```
and:
```
apply plugin: 'codenarc'
apply plugin: 'groovy'
```

So there's not an easy point the Gradle CodeNarc plugin could say "You haven't applied the Groovy plugin".
