### ISSUE TITLE
Log configuration of the Gradle Remote cache node

### ISSUE THREAD

**Issue by sebastienmoreno** [gradle/gradle#28044]
### Issue type

Missing information

### Problem description

Information are missing concerning the log configuration of the Gradle Cache node.
I'm searching a way to change the static configuration of the log which create a "node.log" file with "INFO" level.

The current doc page only describe the location of the log files:
https://docs.gradle.com/build-cache-node/#logging

In a container context deployment, we should be able to change the log to stdout/console appender and to change log level.

Configuration by environment variable would be perfect.

> Is there a repo to contribute on this?

### Page with the problem

https://docs.gradle.com/build-cache-node/#logging

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the Develocity team. They have been informed. Response time may vary.

**Comment by rpygithub** [comment]
Hello @sebastienmoreno.

For recently released versions of the BCN it is possible to redirect all output to stdout by passing the CLI argument `--inline-logs`. Note that support for this argument is subject to change in future versions.

At what granularity are you interested in modifying the log level?

**Comment by rpygithub** [comment]
Thanks @sebastienmoreno for confirming that it works.

We'll consider the inclusion of the `--inline-logs` argument in the public documentation in an upcoming release.

Concerning modifying the log levels, this would require a change to the logging subsystem to cater to that configuration use-case. Unfortunately it's not currently something that can be done "globally" at this time, nor can we commit to supporting this feature at this time.

The default log verbosity is what it is today to assist support teams with troubleshooting BCN deployments.
