### ISSUE TITLE
Feature Request: Allow wrapper.d to check wrapper requirements

### ISSUE THREAD

**Issue by ganadist** [gradle/gradle#28060]
### Expected Behavior

```
$ git clone https://github.com/ganadist/VersionCodeDemo -b wrapper.d vcd2
$ cd vcd2
$ ./gradlew :tasks
Git lfs is not configured correctly. Please check it with.
   git lfs install --local
   git lfs fetch
   git lfs checkout

$ cat gradle/wrapper.d/02-lfs_check.sh
#!/bin/bash

# Check git-lfs is installed or not.
git-lfs > /dev/null 2>&1

if ! [ $? -eq 0 ]; then
  echo "git-lfs is not installed."
  exit 1
fi

HEADER="version https://git-lfs.github.com/spec/v1"
HEADER_LENGTH=${#HEADER}

# Compare lfs header
if echo "$HEADER" | cmp -n "$HEADER_LENGTH" - "$CLASSPATH" > /dev/null 2>&1 ; then
  echo "Git lfs is not configured correctly. Please check it with."
  echo "     git lfs install --local"
  echo "     git lfs fetch"
  echo "     git lfs checkout"
  exit 1
fi
```

### Current Behavior (optional)

```
$ git clone https://github.com/ganadist/VersionCodeDemo -b wrapper.d vcd2
$ cd vcd2
$ ./gradlew :tasks
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

$ cat gradle/wrapper/gradle-wrapper.jar
version https://git-lfs.github.com/spec/v1
oid sha256:0336f591bc0ec9aa0c9988929b93ecc916b3c1d52aed202c7381db144aa0ef15
size 63721
```

### Context

There are minimum gradle wrapper requirements such as
* `gradle/wrapper/gradle-wrapper.jar` needs Java 1.6 or higher
* `gradle/wrapper/gradle-wrapper.jar` must be checked out even if repository is using `git-lfs`.

Also, other requirements can be existed per projects.

If `gradlew` script supports `.d` style customization, it is expected that we will be able to provide clearer error messages to developers in these cases.

**Comment by ov7a** [comment]
This is a git-lfs concern and it should be solved outside of Gradle.
You still need to be aware of the exact files you want to fetch, and I see little value in changing it from one list of files to another.

In a general case, you can create a [custom Gradle distribution](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:custom_gradle_distribution) or use a custom script instead/on top of the default wrapper script.
