### ISSUE TITLE
Dark mode: Black arrows & text on a black background in a diagram

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#28066]
### Issue type

Styling or Accessibility

### Problem description

Black arrows & text on a black background in `Figure 1. Configurations use declared dependencies for specific purposes`

<img width="1009" alt="image" src="https://github.com/gradle/gradle/assets/897017/6efe69ee-2f3a-4dc0-9796-bc98ae985d80">

Also https://docs.gradle.org/nightly/userguide/variant_model.html#maven_component_model

<img width="546" alt="image" src="https://github.com/gradle/gradle/assets/897017/84136a37-1f0c-44ae-ab0a-6857b1e05ecb">

### Page with the problem

https://docs.gradle.org/nightly/userguide/declaring_dependencies.html

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue.

**Comment by lkasso** [comment]
I'm currently going section by section and updating the images to work for both dark and light mode. This will take some time.

**Comment by aSemy** [comment]
hi @lkasso 

The images on https://docs.gradle.org/current/userguide/working_with_files.html are completely invisible. 

> <img width="946" alt="image" src="https://github.com/gradle/gradle/assets/897017/00499440-2e23-4b9d-ba6b-7f5047692224">


I know you said updating the images will take time, but in the interim can you add some css?

```css
div.imageblock {
  background: white;
}
```

> <img width="941" alt="image" src="https://github.com/gradle/gradle/assets/897017/5c2c2ea0-dd4e-416d-9bd6-fcce67ae2862">
