### ISSUE TITLE
Incorrect configuration cache input when reading a file in a `BuildService` and applying a plugin from a composite build

### ISSUE THREAD

**Issue by DennisTsar** [gradle/gradle#28074]
### Current Behavior

For a multi-module project that applies a plugin which is included from a composite build, a file accessed by a `BuildService` inside `OperationCompletionListener.onFinish` is included in configuration cache inputs. As a result, configuration cache cannot be reused when this file changes, even though the file is not accessed during the configuration phase.

### Expected Behavior

Configuration cache should be reused even if the file, accessed in the execution phase, is changed.

### Context (optional)

I am developing a Gradle plugin that needs to read a file on task execution completion, which it does by implementing `OperationCompletionListener.onFinish` in a `BuildService`. I normally test this plugin by including it via composite build in another project, but this issue means that such an approach does not produce the same results as usage in a standalone project would.

### Steps to Reproduce

[Reproduction in GH action](https://github.com/DennisTsar/gradle-buildservice-issue/actions/runs/7893808738/job/21543185555#step:4:1)
- Clone https://github.com/DennisTsar/gradle-buildservice-issue
- Run `./gradlew issue:help --configuration-cache` twice & see that configuration cache is reused the second time
- Create an empty file `issue/test.txt`
- Run `./gradlew issue:help --configuration-cache` & see that configuration cache cannot be reused

While investigating, I noticed that the alphabetical ordering of the project's module names seems to affect the issue. For example, if the `z-test` module in the reproducer is replaced with the otherwise-identical module `a-test`, configuration cache is correctly reused ([action run](https://github.com/DennisTsar/gradle-buildservice-issue/actions/runs/7893808738/job/21543185555#step:6:1)). Additionally, if the problematic module also applies the plugin from the composite build, configuration cache is also correctly reused  ([action run](https://github.com/DennisTsar/gradle-buildservice-issue/actions/runs/7893808733/job/21543185537#step:5:1)).

### Gradle version

8.6

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

The fact that the configuration cache tracks the file is caused by you using it as a parameter for your BuildService. Gradle needs to know it needs to recompute the parameters for build services.

***

@gradle/bt-configuration is there a pattern that allows the user to use that file without tracking? Can we improve our documentation in that area?

**Comment by bamboo** [comment]
The reproducer is behaving is intended. The build service is registered during the configuration of the `issues` project and, that registration happens before the configuration of `z-test`, which uses the plugin from the included build. The included `gradle/plugins` build is then built on-demand to satisfy the plugin request in `z-test`. This causes the build service to be notified as tasks from the included build finish execution, still at configuration time from the main build perspective.

A [ValueSource](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ValueSource.html) can be used to hide the file access from Gradle in scenarios like this:

> A value source implementation is exempt from the automatic detection of work graph cache inputs. For example, if the [obtain()](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ValueSource.html#obtain--) method calls System.getenv("FOO") then changes to the FOO environment variable only invalidate the cache if the value returned by the obtain() method itself changes. The same applies to reading files or system properties. Starting an external process with a standard API (for example, java.lang.ProcessBuilder) is also allowed.

**Comment by mlopatkin** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

See the comment above.
