### ISSUE TITLE
--export-keys --dry-run to overwrite existing keyring

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#28082]
### Current Behavior

I'm finding with Gradle 8.5 and later that `./gradlew help --write-verification-metadata pgp,sha256 --export-keys --dry-run` generates a file at `gradle/verification-keyring.dryrun.keys`

### Expected Behavior

It would be nice if one of:
A) the command above would directly update the keyring file that Gradle uses for non-dryrun builds: `gradle/verification-keyring.keys`
B) we could specify a flag indicating which keyring file to generate

### Context (optional)

In AndroidX we have [a script](https://android.googlesource.com/platform/frameworks/support/+/12284636d8b7f0bf6d90c3d562917331f77cbe56/development/update-verification-metadata.sh) that updates the verification metadata file and the keyring because it's tricky to manually do correctly

This script moves the dryrun keyring file [here](https://android.googlesource.com/platform/frameworks/support/+/12284636d8b7f0bf6d90c3d562917331f77cbe56/development/update-verification-metadata.sh#75) like this:

```
mv gradle/verification-keyring-dryrun.keys gradle/verification-keyring.keys
```

We noticed recently that in Gradle 8.5, the name of the automatically generated dryrun keyring file has changed from
```
gradle/verification-keyring-dryrun.keys
```
to
```
gradle/verification-keyring.dryrun.keys
```
(with a `-` replaced by `.`)

### Steps to Reproduce

1. Make a project that uses signature verification. For example, we can reuse https://github.com/mathjeff/gradle-samples-2/tree/main/android-buildsrc-verification-update
2. Run `./gradlew help --write-verification-metadata pgp,sha256 --export-keys --dry-run` and see that it doesn't update `gradle/verification-keyring.keys` but instead updates `gradle/verification-keyring-dryrun.keys` with Gradle 8.4, or `gradle/verification-keyring.dryrun.keys` with Gradle 8.5
3. 
Thanks!

### Gradle version

8.6

**Comment by mathjeff** [comment]
As a workaround, we're probably going to update the path listed in our wrapper script and also stop asking our wrapper script to ignore failures to find the file (`gradle/verification-keyring.dryrun.keys`)

**Comment by ljacomet** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

* Dependency verification dry run is [explicitly documented](https://docs.gradle.org/current/userguide/dependency_verification.html#sec:verification-dry-mode) as generating new files. We have no plan to change this.
* Regarding the difficulty of updating the keys file, see [newly added documentation](https://docs.gradle.org/release-nightly/userguide/dependency_verification.html#sec:add-manual-keyring) on this topic
