### ISSUE TITLE
Gradle init no longer prompts user to input the source package name

### ISSUE THREAD

**Issue by anthony-S93** [gradle/gradle#28096]
### Current Behavior

`gradle init` no longer prompts the user to input the source package name even without the `--package` flag passed to it.  The prompt skips to java version after project name and assumes `org.example` as the package name by default.

![2024-02-16-13-28-57](https://github.com/gradle/gradle/assets/69449791/b0fa6364-7394-420a-8c46-d2b5f4171f97)

### Expected Behavior

`gradle init` will ask the user to input the source package name when the `--package` flag isn't passed to it. 

![gradle_init](https://github.com/gradle/gradle/assets/69449791/17e466bb-9c8d-4742-bdce-312ac2e9a54b)

### Steps to Reproduce

Run `gradle init`

### Gradle version

Gradle 8.6

**Comment by igorgbianchi** [comment]
I'm having the same trouble with the latest version (8.6). The 8.5 version works fine in an Ubuntu 22.04.3 machine.

**Comment by ljacomet** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

This was a change in Gradle 8.6, see [release notes](https://docs.gradle.org/current/release-notes.html#build-init-improvements).
