### ISSUE TITLE
Binary breaking change in 8.6

### ISSUE THREAD

**Issue by shanman190** [gradle/gradle#28113]
### Current Behavior

The Spring Cloud Contract plugin makes use of the `jvm-test-suite` plugin and via the `jvm-test-suite` configuration adds a dependency to the current project. In 8.5, the API used `DependencyAdder`, but this class was renamed in 8.6 to `DependencyCollector`. Now any plugin that uses the public API and was compiled on a previous version of Gradle results in a `NoSuchMethodError` as well as the inverse if you compile against 8.6, but attempt to use in 8.5.

https://github.com/spring-cloud/spring-cloud-contract/issues/2098

### Expected Behavior

No errors should occur.

### Context (optional)

I understand that this interface is marked as incubating so is subject to change, but this so also part of the public API and is now a major pain point with little to no way to work around it. In the upstream plugin code, it isn't even directly referring to the type itself so there aren't any compilation errors from switching between 8.5 and 8.6.

https://github.com/spring-cloud/spring-cloud-contract/blob/main/spring-cloud-contract-tools%2Fspring-cloud-contract-gradle-plugin%2Fsrc%2Fmain%2Fjava%2Forg%2Fspringframework%2Fcloud%2Fcontract%2Fverifier%2Fplugin%2FSpringCloudContractVerifierGradlePlugin.java#L147

### Steps to Reproduce

Steps are listed on the upstream issue.

### Gradle version

8.6

### Gradle version that used to work

8.5

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
