### ISSUE TITLE
eclipse-wtp-plugin, task eclipseWtpComponent: NullPointerException when reading org.eclipse.wst.common.component generated by Eclipse

### ISSUE THREAD

**Issue by clo-vis** [gradle/gradle#28129]
### Current Behavior

`gradle eclipseWtpComponent `

fails with

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':eclipseWtpComponent'.
> Cannot parse file '.......\.settings\org.eclipse.wst.common.component'.
         Perhaps this file was tinkered with? In that case try delete this file and then retry.
```

The failure is
```
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903)
        at org.gradle.plugins.ide.eclipse.model.WbDependentModule.<init>(WbDependentModule.java:51)
        at org.gradle.plugins.ide.eclipse.model.WbDependentModule.<init>(WbDependentModule.java:37)
```

### Expected Behavior

No failure when reading a file that Eclipse itself "tinkered with".

### Steps to Reproduce

In a gradle project (where eclipseWtp was applied) 

1. Project properties (Alt + Enter)
2. Deployment assembly/Add.../Fileset/(select a file set)/Finish
(Eclipse adds to org.eclipse.wst.common.component a child to `wb-module` called `dependent-module` **without** the attribute `archive-name`.)
3. Run `gradle eclipseWtpComponent ` to get the exception.

The constructor WbDependentModule(Node) assumes that there is always an attribute `archive-name`, it seems.

### Gradle version

8.6

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by donat** [comment]
I cannot reproduce this issue. Which type of file set should I try with? 



![Image](https://github.com/gradle/gradle/assets/419883/732d764e-6ff0-4610-a0f0-3f45ca341bab)
