### ISSUE TITLE
Regenerating IDEA project using plugin throws away 'group' attribute of module

### ISSUE THREAD

**Issue by islandsvinur** [gradle/gradle#2813]
When using `gradle idea` to regenerate/update the IDEA project files (i.e. after the project has been imported in IDEA), the `group` attribute of `module` elements in the `ProjectModuleManager` component node are lost. This leads to a broken IDEA project configuration. The `group` attribute is for grouping test and production modules under a single subproject.

https://github.com/gradle/gradle/blob/baea2d83b11eff2c003f7cbfcb85842dff3e3183/subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/Project.java#L217-L226

Only `fileurl` and `filepath` are copied to the replacement. Manually adding the `group` attributes to the entries in the .iml file repairs the broken structure (although there are still other issues).

**Comment by islandsvinur** [comment]
IntelliJ IDEA 2017.2 and Gradle 4.1 by the way.

**Comment by bmuschko** [comment]
The `idea` Gradle plugin and the built-in Intellij Gradle plugin are not necessarily meant to be fully compatible. Usually you go down the following two routes:

- Generate project files with`idea` Gradle plugin and import them into IntelliJ without activating Gradle support.
- Generate project files with`idea` Gradle plugin and import them into IntelliJ. Activating Gradle support.
- Do not generate project files with`idea` Gradle plugin and just use the import functionality of IntelliJ.

You usually don't go back and regenerate the project files. If you wanted to do that then I'd first call `cleanIdea` but that would assume that all information is provided by the build script.

**Comment by oehme** [comment]
As Ben pointed out `gradle idea` and IDEA's importer are mutually exclusive. You use either one or the other.
