### ISSUE TITLE
Plugin term is not well-defined

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#28151]
### Issue type

Missing information

### Problem description

https://docs.gradle.org/current/userguide/plugin_basics.html
https://docs.gradle.org/current/userguide/plugins.html#plugin_distribution

The documentation does not seem to provide a clear definition for the "plugin" term, and the chart with "plugins side by side with dependencies" does not explain much.

---

> https://docs.gradle.org/current/userguide/plugin_basics.html
> Most features, like the ability to compile Java code, are added by plugins

Technically speaking, "ability to compile Java code" was described in "tasks": https://docs.gradle.org/current/userguide/task_basics.html

> A task represents some independent unit of work that a build performs, such as compiling classes

In other words, one can compile Java code without `java` plugin as they could create `CompileJava` task and be done with it.

---

> https://docs.gradle.org/current/userguide/plugin_basics.html
> Applying a plugin to a project allows the plugin to extend the project’s and Gradle’s capabilities

It looks like a technical description, however, it seems to be overcomplicated. I might be missing something, but it sounds to me like "applying a key to a lock enables the key to unlock the lock". Can we somehow define what a "plugin" is, and define why do we need them?

---

In my opinion, the term "plugin" does not sound quite right. Historically, plugins were made to unlock modifying the existing software. For instance, "a png plugin" could unlock "browsing png files" in an image viewer application.
However, Gradle's case is different as users can write everything right in `build.gradle.kts`. Of course, it is not idiomatic to write everything within a single `build.gradle.kts`, however, there's nothing "Gradle plugin" unlocks.
It might be that "Gradle plugins" enable structuring, refactoring and keeping a library of build logic pieces. In that case, "library" or "build extension" might be a better terms.
Frankly speaking, as I learned Gradle, it was extremely confusing why do I need plugins.

### Context (optional)

* https://gradle-community.slack.com/archives/CAHSN3LDN/p1708010751756729
* https://github.com/autonomousapps/gradle-glossary?tab=readme-ov-file#plugin

### Page with the problem

https://docs.gradle.org/current/userguide/plugin_basics.html

**Comment by lkasso** [comment]
Closed in https://github.com/gradle/gradle/pull/28167
