### ISSUE TITLE
Unused `caches/transforms-3` directory is not removed by Gradle User Home cache cleanup

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#28178]
### Current Behavior

When a user upgrades their build to run with Gradle 8.6, the `~/.gradle/caches/transforms-4` directory is used, and the old `transforms-3` directory is not.
When cleanup runs, old unused versions of Gradle are removed from GUH, including the `caches/<gradle-version>` directory together with other directories that are no longer required (like old `caches/jars-x` and `caches/modules-2/metadata-x` directories.

However, the `transforms-*` directories are not cleaned in this way, and older versions will never be removed by cache cleanup.

### Expected Behavior

When a user runs only with Gradle 8.6, the Gradle User Home cleanup should remove the no-longer-used `caches/transforms-3` directory.

### Steps to Reproduce

- Run a build with Gradle 8.5. Note that Gradle User Home has a `caches/transforms-3` directory.
- Run the same build with Gradle 8.6. Now there is a `caches/transforms-4` directory as well.
- Wait 7 days, or artificially age the files in Gradle User Home.
- Run the same build with Gradle 8.6. Stop the daemon so that Gradle User Home cleanup runs.
- Note that the `caches/8.5` directory has been removed, but not the `caches/transforms-3` directory.

### Gradle version

8.6

**Comment by bigdaz** [comment]
@gradle/bt-execution I've been working on a fix for this, and already have a functional spike. I won't have much time to work on it in the next few weeks, but I'll assign myself and intend on taking care of getting this fixed. Expect a draft PR in a couple of weeks.

The fix involves adding an additional `CleanupAction` [here](https://github.com/gradle/gradle/blob/7859f9ad08d3a503964f31ff86cd299fabbe03e3/platforms/core-execution/execution/src/main/java/org/gradle/internal/execution/workspace/impl/CacheBasedImmutableWorkspaceProvider.java#L97-L101), using a `CompositeCleanupAction`. The main complication is that this makes construction of `CacheBasedImmutableWorkspaceProvider` even more configurable than it already was: I will likely introduce a builder for this type to make it a little less convoluted.

**Comment by liutikas** [comment]
Any updates here? We found that our non-ephemeral build over a span of a month collected 92GB worth of transforms.

**Comment by bigdaz** [comment]
> Any updates here? We found that our non-ephemeral build over a span of a month collected 92GB worth of transforms.

Yep, this is pending a fix which should be shipped in Gradle 8.8. In the meantime, it's safe to manually purge your `~/.gradle/caches/transforms-X` directories.

**Comment by liutikas** [comment]
Is there a separate effort to prune unused/stale transform entries? Right now, every time the build classpath changes, you get a new set of transforms and the old ones stick around for forever.

**Comment by asodja** [comment]
Transforms cache stored in Gradle user home should be cleaned with `created resources` time interval policy, unless cleanup is disabled, see:
https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:configure_cache_cleanup
