### ISSUE TITLE
Incorrect documentation when "gradle run" is using module-path instead of classpath

### ISSUE THREAD

**Issue by tauinger-de** [gradle/gradle#28184]
### Issue type

Wrong or misleading information

### Problem description

The docs at https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular describe when a module-path is being used on the command line instead of the regular classpath.

However, when running a modularized application the reality is different. A module-path is given to java.exe if the application-module is declaring the "mainModule" property as it is shown in one of the linked examples: https://docs.gradle.org/current/samples/sample_java_modules_multi_project.html

### Page with the problem

https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular

**Comment by ljacomet** [comment]
Unless we missed something, I believe this is an issue with using the right documentation source.

For a modular _application_, you need to look at the documentation of the [Java application plugin](https://docs.gradle.org/current/userguide/application_plugin.html#sec:application_modular).

Does that clarify the situation?

If not, please provide a more detailed explanation of what needs to change and where.

**Comment by tauinger-de** [comment]
Thanks for that - I overlooked that section. There was some other issue I had -- will get back to you tmrw
