### ISSUE TITLE
Copy Task can not copy to large destination folder

### ISSUE THREAD

**Issue by dchesterman** [gradle/gradle#2818]
Reported here earlier :
https://discuss.gradle.org/t/copy-task-extremely-slow/2544/7
https://issues.gradle.org/browse/GRADLE-2867

Running a copy task with the destination being a highly populated folder is unmanageable.  The hash calculation takes too long and is prone to failure if the folder is also being updated from other processes

If just the destination file path could be hashed that would be great, otherwise some mechanism for disabling the hash check is required.

There are still many benefits to using a CopyTask even without this state check, but in some cases this check is not feasible.

**Comment by uklance** [comment]
The `Copy` task is just a wrapper around `Project.copy(...)` with support for task inputs/outputs for up-to-date checks. If you don't want the up-to-date checks, just use `Project.copy(...)` manually 

```
task myCopy {
   doLast {
      copy {
         from 'foo' 
         into 'bar' 
      } 
   } 
} 
```

**Comment by bmuschko** [comment]
@uklance explained this appropriately. There might be good reasons why you do not want to use generate these hashes by using the `copy` method. Can we close the issue?

**Comment by oehme** [comment]
Closing as there is a simple workaround.

**Comment by Lothrazar** [comment]
So the simple walkaround is just to never use the Copy task.  ok great
