### ISSUE TITLE
build with spring boot 3.2.2 fail

### ISSUE THREAD

**Issue by cjdxhjj** [gradle/gradle#28180]
### Current Behavior

the windows work well, but the linux build by jenkins fail with the follow error
![image](https://github.com/gradle/gradle/assets/5616997/719b1ac2-00ab-40e9-b583-8a0e6eab8cf5)

### Expected Behavior

build success
this photo from windows build

![image](https://github.com/gradle/gradle/assets/5616997/9f4b6541-a90e-4a9f-bfc8-1e09fd5e90d5)

### Steps to Reproduce

build on linux

### Gradle version

8.5 8.6

**Comment by cjdxhjj** [comment]
![image](https://github.com/gradle/gradle/assets/5616997/ca1f7379-8371-402b-899d-7825ff499cb1)
the gradle attempt download deps from plugin.gradle.org

**Comment by cjdxhjj** [comment]
the plugin.gradle.org redirect the request to jcenter.bintray.com

**Comment by ljacomet** [comment]
Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

This looks like an environment issue; there is a `java.security` exception.
Before blaming Gradle, I would look at the JVM setup and its truststore.
