### ISSUE TITLE
Error `Querying the mapped value of provider(java.util.Set) before task ':subproject1:jar' has completed is not supported` when resolving files

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#28196]
### Current Behavior

Error `Querying the mapped value of provider(java.util.Set) before task ':subproject1:jar' has completed is not supported` when resolving files

### Expected Behavior

No error

### Context (optional)

subproject1 is a standard Kotlin/JVM project

```kotlin
// subproject1/build.gradle.kts

plugins {
  kotlin("jvm") version "1.9.22"
}
```

subproject2 tries to resolve the files from subproject1 using 'Variant-aware sharing of artifacts between projects'

```kotlin
// subproject2/build.gradle.kts

import org.gradle.api.attributes.Category.CATEGORY_ATTRIBUTE
import org.gradle.api.attributes.Category.LIBRARY
import org.gradle.api.attributes.LibraryElements.JAR
import org.gradle.api.attributes.LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE
import org.gradle.api.attributes.Usage.JAVA_RUNTIME
import org.gradle.api.attributes.Usage.USAGE_ATTRIBUTE
import org.gradle.api.attributes.java.TargetJvmEnvironment.STANDARD_JVM
import org.gradle.api.attributes.java.TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE

val jarFiles: Configuration by configurations.creating {
  isCanBeResolved = false
  isCanBeConsumed = false
  isCanBeDeclared = true
}

val jarFilesResolver: Configuration by configurations.creating {
  isCanBeResolved = true
  isCanBeConsumed = false
  isCanBeDeclared = false
  extendsFrom(jarFiles)
  attributes {
    attribute(USAGE_ATTRIBUTE, objects.named(JAVA_RUNTIME))
    attribute(CATEGORY_ATTRIBUTE, objects.named(LIBRARY))
    attribute(TARGET_JVM_ENVIRONMENT_ATTRIBUTE, objects.named(STANDARD_JVM))
    attribute(LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(JAR))
    //attribute(Attribute.of("org.jetbrains.kotlin.platform.type", String::class.java), "jvm")
  }
}

dependencies {
  jarFiles(project(":subproject1"))
}

val printJarFileCoords by tasks.registering {
  val fileCoords = jarFilesResolver.incoming.artifacts.resolvedArtifacts.map { artifacts ->
    artifacts.map { it.id.componentIdentifier.displayName }
  }
  doLast {
    println(fileCoords.get().joinToString())
  }
}
```

But it fails.

```
* What went wrong:
Execution failed for task ':subproject2:printJarFileCoords'.
> Querying the mapped value of provider(java.util.Set) before task ':subproject1:jar' has completed is not supported
```

### Related

* https://github.com/gradle/gradle/issues/16030
* this is a different issue to https://github.com/gradle/gradle/issues/27443 because configuration cache is not enabled
* unlike https://github.com/gradle/gradle/issues/26577 the setup is different and the workaround doesn't work

### Steps to Reproduce

[demo.zip](https://github.com/gradle/gradle/files/14380271/demo.zip)

run `./gradlew printJarFileCoords`

### Gradle version

8.6

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

`fileCoords` is not declared as an input, so it's a missing dependency between tasks.
You can use the following snippet to fix that.
```kts
abstract class Coords : DefaultTask() {
  @get:Input
  abstract val fileCoords : ListProperty<String>

  @TaskAction
  fun print() {
    println(fileCoords.get().joinToString())
  }
}

tasks.register<Coords>("printRight") {
  fileCoords = jarFilesResolver.incoming.artifacts.resolvedArtifacts.map { artifacts ->
    artifacts.map { it.id.componentIdentifier.displayName }
  }
}
```


***

In the future, please include the full stack trace in your reports.
