### ISSUE TITLE
Two gradle-user-home-cleanup runs are required to remove version-specific caches 

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#28197]
### Current Behavior

When cleanup runs, old unused versions of Gradle are removed from GUH, including the caches/<gradle-version> directory together with other directories that are no longer required (like old caches/jars-x and caches/modules-2/metadata-x directories).

However, due to ordering of cleanup actions, it takes 2 runs of cleanup to remove an unused directory like `caches/modules-2/metadata-2.100`.

1. The first cleanup run will remove `caches/<gradle-version>`
2. The subsequent cleanup run will remove directories that are no longer used by <gradle-version>.

The reason this happens is due to the order of cleanup actions:

1. Gradle determins all "active" versions of Gradle, based on the presence of a `caches/<gradle-version>`  directory. 
2. Gradle uses this "active versions" list to decide which version-specific directories to remove (like `caches/jars-8` and `caches/modules-2/metadata-2.100`)
3. Gradle then looks at which Gradle versions have been recently used, and removes the `caches/<gradle-version>` directory for stale versions.
4. This results in a modified "active versions" list, with stale versions removed.
5. Finally, Gradle removes wrapper directories based on the updated "active versions" list.

It's not until we run step 1&2 for a second time that they use the modified "active versions" list.

@ghale I'm not sure if this is known, or if you can think of an easy fix by reordering things.
If not, I don't think this behaviour is particular problematic.

### Expected Behavior

Version-specific directories like `modules-2/metadata-100` are removed in the same cache cleanup action that removes the corresponding `caches/<gradle-version>` directory.

### Steps to Reproduce

TBD.

### Gradle version

8.6

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by bigdaz** [comment]
When `Cleanup.ALWAYS` is specified, the `GradleUserHomeCleanupService` runs early, which means that the updated "active versions list" is then applied when removing unused cross-version caches.
I think this is sufficient and acceptable behaviour, and it satisfies the requirement of the `setup-gradle` GitHub Action.
Closing this issue.
