### ISSUE TITLE
Unexpected MacOS Dock icon appearing for the Gradle Daemon

### ISSUE THREAD

**Issue by ianbrandt** [gradle/gradle#28227]
### Current Behavior

Recently I started noticing a Java/Duke icon appearing in my MacOS Dock for the Gradle Daemon. I believe the daemon used to run completely in the background, but I couldn't say whether this started after a MacOS, Java, or Gradle upgrade.

![image](https://github.com/gradle/gradle/assets/709570/3a5623f6-ca27-45d4-a210-6dcd3b25aada)

### Expected Behavior

The Gradle Daemon runs completely in the background.

### Context (optional)

The Dock icon is unexpected and distracting.

### Steps to Reproduce

Reproducer: https://github.com/sdkotlin/sd-kotlin-talks/tree/682f593cf442f511da4dccc85a7e9a04714909ce

1. `./gradlew build --rerun-tasks # Appears`
2. `./gradlew --stop # Disappears`

Per https://stackoverflow.com/a/64241632/235356, I can work around the issue by adding a '~/.gradle/gradle.properties' file containing the following line:

```
systemProp.apple.awt.UIElement=true
```

I would expect Gradle to set this itself if it is indeed the correct way to address the issue.

### Gradle version

8.6

### Build scan URL (optional)

https://scans.gradle.com/s/i2jtoz53yge2a

### Your Environment (optional)

MacOS 14.3.1 (23D60)
Temurin-17.0.10+7 (build 17.0.10+7)

**Comment by ianbrandt** [comment]
I noticed that I don't get the Dock icon for Gradle Daemons launched from this similar but different project: https://github.com/sdkotlin/sd-kotlin-spring-talks/tree/1bcea44f3e2fb20b8bb631f6bc5a5128dca5f1f9.

Based on that, I seem to have isolated the issue to setting `kotlin.compiler.execution.strategy=in-process` in the original reproducer project: https://github.com/sdkotlin/sd-kotlin-talks/blob/682f593cf442f511da4dccc85a7e9a04714909ce/gradle.properties#L11.

I'm not sure where that leaves this issue. Setting `systemProp.apple.awt.UIElement=true` in combination with `kotlin.compiler.execution.strategy=in-process` is still a workaround.

**Comment by ov7a** [comment]
This is an issue with the Kotlin Gradle Plugin, which is developed by JetBrains, and cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

Please open such Kotlin-related issues on the JetBrains YouTrack at https://kotl.in/issue.

If you believe this is not a Kotlin plugin issue, please update with a reproducer that does not involve the Kotlin plugin.
