### ISSUE TITLE
Broken Linux instructions for manually verifying wrapper JAR

### ISSUE THREAD

**Issue by translatenix** [gradle/gradle#28226]
### Current Behavior

Checksum verification fails with `no properly formatted SHA256 checksum lines found`.

### Expected Behavior

Checksum verification succeeds.

### Context (optional)

is: `echo "gradle-wrapper.jar"`
sb: `echo " gradle-wrapper.jar"`

### Steps to Reproduce

Follow the Linux instructions at: https://docs.gradle.org/current/userguide/gradle_wrapper.html#manually_verifying_the_gradle_wrapper_jar

### Gradle version

8.6

### Your Environment (optional)

WSL2/Ubuntu on Windows 11

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue.
***
Indeed, it's a [typo](https://github.com/gradle/gradle/commit/35b55b5c2fb207a54cb72c776bed86b146ac0d21#diff-65ff4a5a107b2677295de834ef1aacce4a4546f2d44b361fc4c7e89d317d3ba1R396).

**Comment by lkasso** [comment]
Fixed in https://github.com/gradle/gradle/pull/28349
