### ISSUE TITLE
Allowing "apply false" to core plugin. 

### ISSUE THREAD

**Issue by iseki0** [gradle/gradle#28235]
### Expected Behavior

Allow the following code in `build.gradle.kts`:
```kotlin
plugins {
    signing apply false
}
```

### Current Behavior (optional)

```
Error resolving plugin [id: 'org.gradle.signing', apply: false]
> Plugin 'org.gradle.signing' is a core Gradle plugin, which is already on the classpath. Requesting it with the 'apply false' option is a no-op.
```

### Context

When we use Kotlin DSL, we need gradle generate stubs for script executing. In root project I have to use `allprojects{}` and `subprojects{}` block. If we don't add the plugin to `plugins{}` the stubs will not be generated. Otherwise the plugin will generate unused tasks. It's a problem, it mess up the task hierarchy.

**Comment by iseki0** [comment]
gradle/kotlin-dsl-samples#916

**Comment by ov7a** [comment]
It's hard to achieve this with a static compiled language. 

The workaround is to use convention plugins or using dynamic accessors like `project.extensions.getByName()`.

**Comment by iseki0** [comment]
And, there's a [post](https://discuss.gradle.org/t/when-will-gradle-allow-apply-false-the-core-plugin/47778/4?u=iseki0) as a reference that explain I'm in a X-Y problem and my solution doesn't work for the feature request.
