### ISSUE TITLE
Clarify how to annotate a file that a task may create or may delete

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#28231]
### Issue type

Missing information

### Problem description

Reading the documentation for `@OutputFile` and `@Destroys`, it does not anywhere help the user know how to mark a file that a task may either create or destroy.

These are the logical scenarios to consider:
1. The configuration input (such as a `ValueSource` at read configuration time) might tell the task whether to create or delete the file
2. Task input (such as an `@InputFile`) might cause the task to determine whether to create or delete the file at execution time

What do we do here?

Should we use both annotations?

```kotlin
@get:Destroys
@get:OutputFile
abstract val managedFile: RegularFileProperty
```

Or should we just use one of them? If so, which one?

The docs for both annotation types should probably mention this scenario and clarify to the user what to do.

### Page with the problem

https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Destroys.html

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by lptr** [comment]
`@OutputFile` should be usable for the case when the task decides not to create an output (or delete the file if it's already there). Would you be interested in providing a PR with the clarifications you'd like to see?

**Comment by ov7a** [comment]
@lptr @lkasso Can you please address the comment and decide if the docs can be improved even further?
