### ISSUE TITLE
gradle init with maven project results in build-logic included, but no folder generation

### ISSUE THREAD

**Issue by snowe2010** [gradle/gradle#28251]
### Current Behavior

Running `gradle init` with the incubating feature option in an existing maven project generates the following settings.gradle.kts

```kotlin
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "battery-price"
```

but it does _not_ generate the `build-logic` folder, so the build immediately fails to import. 

### Expected Behavior

to be able to run `gradle init` in a maven project and have the resulting build succeed to import

### Context (optional)

Trying to convert an existing maven project to gradle. 

### Steps to Reproduce

[gradle-init-bug.zip](https://github.com/gradle/gradle/files/14412255/gradle-init-bug.zip)

project was just generated with intellij's new project tool. kotlin, maven selected.

1. run `gradle init` with 8.7-rc-1
```
❯ gradle --version

------------------------------------------------------------
Gradle 8.7-rc-1
------------------------------------------------------------

Build time:   2024-02-22 21:39:49 UTC
Revision:     6cd7d3cf5929e1bd9f917b7dc67d03cd65d22d08

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.5 (GraalVM Community 17.0.5+8-jvmci-22.3-b08)
OS:           Mac OS X 14.2.1 aarch64
```
2. choose incubating features

Final result is this settings file

```kotlin
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "gradle-init-bug"
```

with no build-logic folder
![image](https://github.com/gradle/gradle/assets/1534535/84b4c0c0-8f00-41e0-bd5a-0e0553da2371)

### Gradle version

8.7-rc-1

### Your Environment (optional)
```
❯ gradle --version

------------------------------------------------------------
Gradle 8.7-rc-1
------------------------------------------------------------

Build time:   2024-02-22 21:39:49 UTC
Revision:     6cd7d3cf5929e1bd9f917b7dc67d03cd65d22d08

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.5 (GraalVM Community 17.0.5+8-jvmci-22.3-b08)
OS:           Mac OS X 14.2.1 aarch64
```

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
