### ISSUE TITLE
Can't reference `buildSrc` project

### ISSUE THREAD

**Issue by USSX-Hares** [gradle/gradle#28319]
### Issue type

Wrong or misleading information

### Problem description

The documentation states I can reference `buildSrc` project in my `build.gradle` scripts. However, attempting to do so results in error.

The documentation:
> The `MyCustomTask` task is used in the build script of the api and shared projects. The task is automatically available because it’s part of `buildSrc`. The `shared.build(.kts)` file is also applied:
> #### build.gradle
> ```groovy
> // Apply any other configurations specific to your project
> 
> // Use the build script defined in buildSrc
> apply from: project(':buildSrc').file('shared.gradle')
> 
> // Use the custom task defined in buildSrc
> tasks.register('myCustomTask', MyCustomTask)
> ```

Error:
```text
A problem occurred evaluating project ':api'.
> Project with path ':buildSrc' could not be found in project ':api'.
```

The only workaround I managed to find is to use the following syntax:
```groovy
apply from: rootProject.file('buildSrc/shared.gradle')
```

### Context (optional)

Gradle version: 8.6 (same as on documentation)

<details>
<summary>Gradle Info</summary>

```text

Welcome to Gradle 8.6!

Here are the highlights of this release:
 - Configurable encryption key for configuration cache
 - Build init improvements
 - Build authoring improvements

For more details see https://docs.gradle.org/8.6/release-notes.html


------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Linux 4.15.0-142-generic amd64
```

</details>

<details>
<summary>Project structure</summary>

```text
$ tree
.
├── api
│   ├── build.gradle
│   └── src
│       ├── main
│       │   ├── groovy
│       │   │   └── HelloWorlder.groovy
│       │   ├── java
│       │   └── resources
│       └── test
│           ├── groovy
│           ├── java
│           └── resources
├── buildSrc
│   ├── build
│   │   ├── classes
│   │   │   └── groovy
│   │   │       └── main
│   │   │           └── MyCustomTask.class
│   │   ├── generated
│   │   │   └── sources
│   │   │       └── annotationProcessor
│   │   │           └── groovy
│   │   │               └── main
│   │   ├── libs
│   │   │   └── buildSrc.jar
│   │   └── tmp
│   │       ├── compileGroovy
│   │       │   └── groovy-java-stubs
│   │       └── jar
│   │           └── MANIFEST.MF
│   ├── build.gradle
│   ├── shared.gradle
│   └── src
│       ├── main
│       │   ├── groovy
│       │   │   └── MyCustomTask.groovy
│       │   ├── java
│       │   └── resources
│       └── test
│           ├── groovy
│           ├── java
│           └── resources
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
└── settings.gradle
```

</details>

Full project tree in attachments:
[gh-28319.zip](https://github.com/gradle/gradle/files/14462806/gh-28319.zip)

### Page with the problem

https://docs.gradle.org/8.6/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration

**Comment by lkasso** [comment]
Fixed in https://github.com/gradle/gradle/pull/28349

**Comment by lkasso** [comment]
There are two solutions:

1. Apply it with apply from: "$project.rootDir/buildSrc/shared.gradle"
2. Update the buildSrc build script to use :

```
plugins {
    id 'groovy-gradle-plugin' // not just id 'groovy'
}
```
And the api build file can then use:
```
plugins {
    id("shared") // now you can apply shared.gradle like a plugin
}
```
See the attachment for the full working project: [gradleTestProject.zip](https://github.com/gradle/gradle/files/14553533/gradleTestProject.zip)
