### ISSUE TITLE
Are there any xaml applications (winui 3 developing) for this program?

### ISSUE THREAD

**Issue by okgamr** [gradle/gradle#28326]
### Expected Behavior

i don't really know, but it should work as the others, with the difference of the coding laguage, ig

### Current Behavior (optional)

it's just a new programming language for the program itself, as i want to use it instead of VS, so more environments woukd be good for development

### Context

Using VS as a new user is **really, really** hard, so i was looking for something similar, but easier. i've tested replit, and it's good, but i want something on the desktop, no web

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.
