### ISSUE TITLE
Compatibility matrix doesn't mention version 8.6

### ISSUE THREAD

**Issue by tudortimi** [gradle/gradle#28333]
### Issue type

Missing information

### Problem description

The [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html) doesn't mention version 8.6.

### Page with the problem

https://docs.gradle.org/current/userguide/compatibility.html

**Comment by ov7a** [comment]
Thanks for the report!

**Comment by lkasso** [comment]
Fixed in https://github.com/gradle/gradle/pull/28349
