### ISSUE TITLE
Gradle does not start on z/OS

### ISSUE THREAD

**Issue by lux01** [gradle/gradle#28348]
### Current Behavior

When attempting to perform any task on Gradle 8.8 on IBM z/OS with Java 8 or Java 11 the build fails immediately with the following error

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'temp'.
> Could not create task ':init'.
   > Could not create service of type MemoryManager using GlobalScopeServices.createMemoryManager().
      > free must be >= 0
```

The ultimate root cause of this is that `MBeanOsMemoryInfo` using the `"FreePhysicalMemorySize"` attribute from the `OperatingSystemMXBean` which is [documented to always return -1 on z/OS as it is not supported](https://eclipse.dev/openj9/docs/api/jdk11/jdk.management/com/ibm/lang/management/OperatingSystemMXBean.html).

I had originally planned to try to fix this by having the `OsMemoryStatus.getPhysicalMemory()` function return a `OsMemoryStatusAspect` instead of an `OsMemoryStatusAspect.Available` and have the physical memory be unavailable on z/OS (or more accurately whenever the `free` or `total` physical memory in `MBeanOsMemoryInfo.getOsSnapshot()` are ever negative. This turned out to have more knock on effects than I had hoped so I figured it was best to raise this defect before to get some expert opinion before committing more effort to this.

### Expected Behavior

The build should not immediately fail with an exception in `MemoryManager`.

### Context (optional)

We are trying to update the Gradle of version used by our z/OS build pipeline.

### Steps to Reproduce

1. Download Gradle to a z/OS machine
2. Export the environment the following environment variable to ensure that the inter-process between parent and child processes in Gradle work
   ```bash
   export OPENJ9_JAVA_OPTIONS="-Dconsole.encoding=ISO8859-1 -Dfile.encoding=ISO8859-1"
   ```
3. Convert the `gradle` script to EBCDIC so it can be run by `bash`:
   ```bash
   iconv -f ISO8859-1 -t IBM-1047 /path/to/gradle/bin/gradle gradle.zos
   chmod +x /path/to/gradle/bin/gradle.zos
   ```
4. Run the converted `gradle` script, piping the output through `iconv` so the output can be understood
   ```bash
   $ /path/to/gradle/bin/gradle.zos init |& iconv -f ISO8859-1 -t IBM-1047
   ```

### Gradle version

8.4 or above

### Gradle version that used to work

8.3

### Your Environment (optional)

IBM z/OS 2.4
IBM Java 8

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by lux01** [comment]
Just to update this, I have played around some more and it looks like the following is sufficient to resolve the issue enough to start the daemon and is much cleaner than trying to make the physical memory only conditionally available

```patch
$ git diff platforms/core-runtime/process-services/src/main/java/org/gradle/process/internal/health/memory/MBeanOsMemoryInfo.java
diff --git a/platforms/core-runtime/process-services/src/main/java/org/gradle/process/internal/health/memory/MBeanOsMemoryInfo.java b/platforms/core-runtime/process-services/src/main/java/org/gradle/process/internal/health/memory/MBeanOsMemoryInfo.java
index 537aaef8f2f..99d859db76d 100644
--- a/platforms/core-runtime/process-services/src/main/java/org/gradle/process/internal/health/memory/MBeanOsMemoryInfo.java
+++ b/platforms/core-runtime/process-services/src/main/java/org/gradle/process/internal/health/memory/MBeanOsMemoryInfo.java
@@ -32,6 +32,12 @@ public OsMemoryStatus getOsSnapshot() {
         String totalMemoryAttribute = Jvm.current().isIbmJvm() ? "TotalPhysicalMemory" : "TotalPhysicalMemorySize";
         long total = MBeanAttributeProvider.getMbeanAttribute("java.lang:type=OperatingSystem", totalMemoryAttribute, Long.class);
         long free = MBeanAttributeProvider.getMbeanAttribute("java.lang:type=OperatingSystem", "FreePhysicalMemorySize", Long.class);
+        if (total <= 0) {
+            throw new UnsupportedOperationException("Unable to determine total physical memory size");
+        }
+        if (free <= 0) {
+            throw new UnsupportedOperationException("Unable to determine free physical memory size");
+        }
         return new OsMemoryStatusSnapshot(total, free);
     }
 }
```

**Comment by crshnburn** [comment]
@ov7a Hi, has there been any update from team? Would a PR help as we are also affected by this and would be happy to help test any changes?

**Comment by octylFractal** [comment]
I've made a PR for this #28523

**Comment by crshnburn** [comment]
Just to confirm that I've got this working on our test z/OS system
<details><summary>Gradle output</summary>
<p>

```
/u/smithso/gradle-dev/bin:>gradle --version

Welcome to Gradle 8.8-20240321000000+0000!


------------------------------------------------------------
Gradle 8.8-20240321000000+0000
------------------------------------------------------------

Build time:   2024-03-21 00:00:00 UTC
Revision:     9f4943f3fa62d4178f2b843633db40ba4c3f717f

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_391 (IBM Corporation 2.9)
OS:           z/OS 03.01.00 s390x

/u/smithso/gradle-dev/bin:>cd ~/sample-cics-api-first/
/u/smithso/sample-cics-api-first:>ls
COBOL      COPY       CSD        LICENSE    README.md  finish     start
/u/smithso/sample-cics-api-first:>cd finish
/u/smithso/sample-cics-api-first/finish:>gradle build
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :zosConnectPreBuildTask

> Task :openApiGenerate
Unknown `format` decimal detected for type `number`. Defaulting to `number`
Unknown `format` decimal detected for type `number`. Defaulting to `number`
Unknown `format` decimal detected for type `number`. Defaulting to `number`
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project ?                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################
Successfully generated code to /u/smithso/sample-cics-api-first/finish

> Task :zosConnectApiFilter
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :war
> Task :assemble
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build

BUILD SUCCESSFUL in 26s
6 actionable tasks: 6 executed
/u/smithso/sample-cics-api-first/finish:>
```
</p>
</details>
