### ISSUE TITLE
Wrong command given in Build Scans chapter

### ISSUE THREAD

**Issue by koreQAQ** [gradle/gradle#28342]
# Issue type
Wrong information

# Problem description
Command line [ ./gradlew build --scans](https://docs.gradle.org/current/userguide/build_scans.html) went wrong .

Output:
`Unknown command-line option '--scans'.`

Use ` ./gradlew build --scan ` correct

### Page with the problem

https://docs.gradle.org/current/userguide/build_scans.html

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/28349.
