### ISSUE TITLE
Issues with Version Catalog accessors for precompiled plugin

### ISSUE THREAD

**Issue by mavek87** [gradle/gradle#28371]
### Current Behavior

Its not possible at the moment to use "alias", "id" and catalog in precompiled scripts

example 

```
plugins {
    alias(libs.plugins.gradle.ssh.plugin)
}
```

or

```
plugins {
    id(libs.plugins.gradle.ssh.plugin.get().pluginId)
}
```

It's ugly to have to specify again the plugin name because this metadata is already specified and duplicated in the catalog. Being forced to do so makes the catalog pretty useless.
```
plugins {
    id "org.hidetake.ssh"
}
```

@sgammon This is my project. It's easy to reproduce. Just Gradle init and choose always groovy. No buildSrc, nothing. Just one included subproject (named "plugin")

this is my settings gradle in the root

<b>settings.gradle</b>
```settings.gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            plugin('gradle-ssh-plugin', 'org.hidetake.ssh').version("2.11.2")
        }
    }
}

rootProject.name = 'example-gradle'
include('plugin')
```

![image](https://github.com/gradle/gradle/assets/7861356/f655cfa6-83f5-4609-a1db-5d5b2ca202c8)

In the build.gradle of the "plugin" subproject i have just 

<b>build.gradle</b>
```build.gradle
plugins {
       id 'groovy-gradle-plugin'
}
```

And in the precompiled script I have just this

<b>com.matteoveroni.plugin-name.gradle</b>
```build.gradle
plugins {
//    id "org.hidetake.ssh"
    id(libs.plugins.gradle.ssh.plugin.get().pluginId)
}
```

![image](https://github.com/gradle/gradle/assets/7861356/442463dc-4701-4956-8247-1a0a8899e23e)

If I use the string it works. 

### If I try with the id I receive an error

```
* Where:
Script '~/Documenti/workspace/java/example-gradle/plugin/src/main/groovy/com.matteoveroni.plugin-name.gradle' line: 3

* What went wrong:
Could not compile script '~/Documenti/workspace/java/example-gradle/plugin/src/main/groovy/com.matteoveroni.plugin-name.gradle'.
> startup failed:
  script '~/Documenti/workspace/java/example-gradle/plugin/src/main/groovy/com.matteoveroni.plugin-name.gradle': 3: argument list must be exactly 1 literal String or String with property replacement
  
  For more information on the plugins {} block, please refer to https://docs.gradle.org/8.6/userguide/plugins.html#sec:plugins_block in the Gradle documentation.
  
   @ line 3, column 5.
         id(libs.plugins.gradle.ssh.plugin.get().pluginId)
         ^
  
  1 error

```

### if I try with the alias this other error:

```
Could not compile script '~/Documenti/workspace/java/example-gradle/plugin/src/main/groovy/com.matteoveroni.plugin-name.gradle'.
> startup failed:
  script '~/Documenti/workspace/java/example-gradle/plugin/src/main/groovy/com.matteoveroni.plugin-name.gradle': 4: only alias(libs.plugins.someAlias) plugin identifiers where `libs` is a valid version catalog
  
  For more information on the plugins {} block, please refer to https://docs.gradle.org/8.6/userguide/plugins.html#sec:plugins_block in the Gradle documentation.
  
   @ line 4, column 5.
         alias(libs.plugins.gradle.ssh.plugin)
         ^
  
  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

### Expected Behavior

this should work in precompiled plugin scripts

```
plugins {
    id(libs.plugins.gradle.ssh.plugin.get().pluginId)
}
```

or maybe even better alias, because the plugin here don't need a version

```
plugins {
    alias(libs.plugins.gradle.ssh.plugin)
}
```

### Steps to Reproduce

It's easy to reproduce. Just Gradle init and choose always groovy. No buildSrc, nothing. Just one included subproject (named "plugin"). And finally add the files I mentioned before

### Gradle version

8.6

**Comment by sgammon** [comment]
@mavek87 Give me a few minutes, I'm trying it out now.

**Comment by mavek87** [comment]
@sgammon if you want you can clone my repository https://github.com/mavek87/example-gradle

**Comment by sgammon** [comment]
@mavek87 I got it working. You don't have to declare a version, but we also can't use `alias(...)`. It's not _that_ bad, because the plugin ID shouldn't change and you can still update your versions centrally in your version catalog.

So effectively you end up doing

In your **`libs.versions.toml`**:
```toml
[versions]
sshPlugin = "2.11.2"

[libraries]
plugin-ssh = { module = "org.hidetake:core", version.ref = "sshPlugin" }
```

It is mapped as a _library_ instead of a plugin here because we are making a plugin, so it is a direct library dependency, not a plugin being applied to the plugin project itself.

Then, you can do
```groovy
dependencies {
  implementation libs.plugin.ssh
}
```

Which allows this in your precompiled script plugin:
```groovy
plugins {
    id("org.hidetake.ssh")
}
```

Here's the sample: https://github.com/sgammon/repro-gradle-groovy-precompiled-plugin

Hope this helps 👍

**Comment by mavek87** [comment]
Yes I also have the situation you have recreated in my real plugin (not this sample), (with the dependency too). But the problem is that I have to type in the precompiled script the plugin alias

```
id("org.hidetake.ssh")
```

so I have to repeat it. Instead it should be correct to use the alias in the catalog like

```
alias(libs.x.y)
```

**Comment by sgammon** [comment]
@mavek87 There may not be any way around that, unfortunately. Allow me to explain why.

When you make a Version Catalog, Gradle parses the TOML and generates the accessors. It generates code under the hood that ends up in a JAR.

When the fix from before is applied, this one:
```kotlin
dependencies {
  implementation(files(libs.javaClass.superclass.protectionDomain.codeSource.location))
}
```

It may work to make the accessors available, but it won't work to include those accessors _transitively_ for when you actually _use_ your plugin. This plugin doesn't run on its own, right? It runs in another build, downstream. It's _that_ build where the plugin accessors would not be available.

This is why the plugin string is a better alternative: it's just the string, one time. No version. If you want, you can bend over backwards to be able to use `libs`, but is it worth it? Here's what you'd have to do:

Use a plugin like [buildconfig](https://github.com/gmazzo/gradle-buildconfig-plugin) to do the following:

```groovy
plugins {
    id "com.github.gmazzo.buildconfig" version "<current version>"
}

buildConfig {
    buildConfigField(String, "some.package.path.SomeClass.SSH_PLUGIN_ID", "\"${libs.plugins.ssh.get().pluginId}\"")
}
```

```kotlin
class SomePlugin : Plugin<Project>
  override fun apply(target: Project) {
    target.pluginManager.apply(some.package.path.SomeClass.SSH_PLUGIN_ID)
  }
}
```

Then:
```
gradlePlugins {
  // .. register `SomePlugin`, say, at `some.plugin`
}
```

Then:

```
plugins {
  id("some.plugin")
}
```

So now you have _control_ over the plugin ID, but it's still a string, after all that work.

**Comment by mavek87** [comment]
and by the way this create another problem. (Your solution is the only one working, my solution in my real project is the same) The fact that the plugin is added twice in the catalog. Once in the plugins and once in the dependencies

**Comment by sgammon** [comment]
@mavek87 I agree that is a flaw. But ultimately you don't _need_ to list it twice; just once. Probably the Gradle team would say that the _best_ way to do this is with `implementation(...plugin...)`, then use `id("your.own.convention")`, which loads the plugin and applies it.

**Comment by mavek87** [comment]
In my real code I have this in the build.gradle of the precompiled plugin like you 
```
dependencies {
    implementation libs.gradle.plugin.ssh.dep
}
```
This is documented but looks like nonsense from outside. That dependency is not a library concretely, is a plugin. And it forces me to add it in the catalog as a library. And I also need the plugin in the catalog because maybe I can apply this plugin in other projects of mine which don't use this precompiled plugin I created

**Comment by sgammon** [comment]
@mavek87 To be clear I agree with you but I don't work for Gradle. I'm just as helpless as you are to fix it.

**Comment by JavierSegoviaCordoba** [comment]
> In my real code I have this in the build.gradle of the precompiled plugin like you 
> 
> ```
> 
> dependencies {
> 
>     implementation libs.gradle.plugin.ssh.dep
> 
> }
> 
> ```
> 
> This is documented but looks like nonsense from a user perspective. That dependency is NOT a library concretely, is a plugin. And it forces me to add it in the catalog as a library. And I also need it as plugin in the catalog because maybe I can apply this plugin in other projects of mine which don't use this precompiled plugin I created (using alias where it is allowed). It's all really messy at the moment

You can transform the id of a plugin into a valid maven coordinate

id: org.foo.bar
version: 1.0.0

coordinate: org.foo.bar:org.foo.bar.gradle.plugin:1.0.0.

You can create an extension function called `artifact` for that so you can do something like:

```kotlin
implementation(libs.plugins.foo.artifact)
```

**Comment by sgammon** [comment]
Hey @JavierSegoviaCordoba. Yep, we're already doing that in the [sample](https://github.com/sgammon/repro-gradle-groovy-precompiled-plugin) if I understand your point correctly. I realize you are replying to @mavek87.

He still wants to use the version catalog even within the actual primary code of the precompiled script. In that case, I've posted a snippet above which works with `id(...)`, but a string still has to be emitted literally. It could be cleaner but it does work.

**Comment by patton73** [comment]
Honestly i think that this is an incredible mess. And this is not the only one. 
That raises some questions:

1) What's the meaning of having a Catalog if then you are forced to use the same Catalog definition inside your script because the precompiled script cannot get it from the Catalog itsself?

2) How come Gradle's teams raised this level of complexity and mess designing how a Catalog should work?

3) How come no one want at least merge some PR's that adress and solve similar issues?

4) Why Gradle's Teams basically ignore user's perspective? If people get sick of using gradle, then gradle would become useless.

**Comment by sgammon** [comment]
> What's the meaning of having a Catalog if then you are forced to use the same Catalog definition inside your script because the precompiled script cannot get it from the Catalog itsself?

Precompiled plugins can be distributed to other projects, so the complexity of bringing along the Version Catalog is not as simple as it may seem.

> Why there is no "exact" separation between libraries and plugins while using them inside a precompiled script?

Well, because, ultimately, a plugin _is a library_. It's a JAR. What makes it a "plug-in" is that it "applies" to a project; it runs, it doesn't just load. If you are depending on a plugin from a plugin, it makes a *ton of sense* for this to be a library dependency. Using the plugin downstream uses the transitive libraries, too, as traditional classpath dependencies.

> How come Gradle's teams raised this level of complexity and mess designing how a Catalog should work?

Version Catalogs are a new feature and we should give the Gradle team time to get it right. In the issue you linked, the user is trying to use dynamic versions, which aren't a good idea in general. They are trying to use them from Version Catalogs, which is an even worse idea. Gradle is right to reject that.

> How come no one wants at least merge some PRs that address and solve similar issues?

I am not sure what you are referring to specifically.

> Why Gradle's Teams basically ignore user's perspective? If people get sick of using gradle, then gradle would become useless.

While I understand Gradle can be frustrating, it isn't going anywhere. Many people understand Gradle and can get it to do what they need to do.

**Comment by mavek87** [comment]
@sgammon Dynamic version has many drawbacks but if done deliberately it's a choice. In fact dynamic version it's not forbidden by gradle. At the same way caching or not the catalog should be also a user's choice. It's ok if the default is caching. It makes sense. But why not giving the power to the user to choose what it fits better to his use case. 

Giving the possibility to choice has 0 disadvantages and 1 advantage. Be able to choose.

In fact if you want to NOT use dynamic version you can do it:

1. Leave the default cache in the catalog (Do nothing and it's the same like now)

AND/OR

2. Using dependency locking (already present in gradle).

If you want to avoid dynamic versions to be used, use dependency locking (or not).
For the cache (other totally unrelated problem) I'm forced to use it even if i don't want it.

**Comment by JojOatXGME** [comment]
@mavek87 I just created an issue about your problem.

* #28409

I did not read the comments of this issue before I have created my new issue. It also mentions a workaround at the bottom, which is similar to what @JavierSegoviaCordoba has suggested.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
I'm going to close this as a dupe of https://github.com/gradle/gradle/issues/15383. 

For now, I'd recommend that you duplicate the plugin id in the precompiled script plugin.

**Comment by mavek87** [comment]
@patton73 @sgammon Thanks to @JojOatXGME I was able to use a workaround to avoid to duplicate things in my catalog. This is the groovy code I'm using at the moment. I leave it here for other people, because I wasted days for this:

```    
def pluginDependency = (Provider<PluginDependency> pluginProvider) -> pluginProvider.map { plugin ->
        [
                "group"  : plugin.pluginId,
                "name"   : "${plugin.pluginId}.gradle.plugin",
                "version": plugin.version.requiredVersion
        ]
}
```

or using ext if you need to pass the lambda to other projects using this plugin

```
ext {
  pluginDependency = (Provider<PluginDependency> pluginProvider) -> pluginProvider.map { plugin ->
          [
                  "group"  : plugin.pluginId,
                  "name"   : "${plugin.pluginId}.gradle.plugin",
                  "version": plugin.version.requiredVersion
          ]
  }
}
```

After defining the lambda I can do something like this and so I'm able to avoid to duplicate things in the catalog.

```
dependencies {
    implementation(pluginDependency(libs.plugins.gradle.release))
    implementation(pluginDependency(libs.plugins.gradle.classpath.collision.detector))
}
```

@big-guy Sorry, but I still can't understand why we, as Gradle users, could workaround this problem with 3 lines of code after days spent trying to understand how, and the Gradle team continues to avoid addressing these kinds of behaviors. I don't want to be polemical, but I think you did a great job with the catalog. However, you should complete what you have started. 99% of the things related to the catalog work well. You should consider addressing the remaining 1% flaws like this one; otherwise, you continue to add new features without completing all the existing ones.

**Comment by nanihadesuka** [comment]
The whole combination of convention plugins and version catalogs is an incredible badly designed mess. We now have the worst of the two words. Please release a sane default, that makes the use of the two, something viable.

**Comment by Zalewa** [comment]
@mavek87 your elegant solution, which I am currently using for 9 plugins, is producing me 9 deprecation errors in Gradle 9.1.0. 

It seems it is about to die in this form:
https://docs.gradle.org/9.1.0/userguide/upgrading_version_9.html#dependency_multi_string_notation

The replacement simply composes the attributes into a single string:
```
def pluginDependency = (Provider<PluginDependency> pluginProvider) -> pluginProvider.map { plugin ->
    "${plugin.pluginId}:${plugin.pluginId}.gradle.plugin:${plugin.version.requiredVersion}"
}
```

**Comment by KemalSoysal** [comment]
I have had the same problem with Gradle 8.14.2 using the libs.versions.toml file with the plugins section
```
[plugins]
that-one-plugin = { id = "....", version.ref = "version-that-one-plugin" }
```

not being applied when used with 
```kotlin
plugins {
    alias(libs.plugins.thatOnePlugin)
}
```

The only way I could persuade gradle to apply it was:
```kotlin
plugins {
   id(libs.plugins.thatOnePlugin.get().pluginId) version "${libs.plugins.thatOnePlugin.get().version}"
}
```
Hope this is of some help
