### ISSUE TITLE
User input can be captured in plain-text from command line

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2838]
**Requirements**

- A user can access a handler for capturing input
- The handler implementation is accessible through the `Project` instance or can be injected via `javax.inject.Inject`
- The implementation allows a user to provide a prompt as String
- The answer to a prompt can be entered as free-form text and is visible on the console
- The build is paused and is awaiting user input
- The answer is accepted upon pressing the ENTER key and resumes the build
- User input can be canceled by pressing CTRL-D
- The answer is provided through as return value to the user for further processing
- Support for any non-interactive environments are out-of-scope

**Test cases**

- Functionality works with and without daemon
- Functionality works with plain and rich console
- Non-interactive console does not render prompt and returns null as answer
- User input can be captured during configuration and execution phase
- Provided prompt is rendered on console
- Prompt can span multiple lines on console
- Entering CTRL-D returns null value
- Entering any String plus ENTER captures user input and returns value to user of API
- User input is sanitized (removes blanks and special characters)
- User input is not length-restricted
- Prompt or user input renders properly in rich console

**Comment by pranayhasan** [comment]
I'm looking forward for this feature. Please let me know if you need any help in implementing this.
