### ISSUE TITLE
Gradle wrapper configurable distributionUrl hash value

### ISSUE THREAD

**Issue by dellgreen** [gradle/gradle#2844]
When gradle-bin.zip is included in repo for offline scenarios and where realtive url used because absolute one cannot be used, one ends up with lots of duplicate gradle instances in user home dir as PathAssembler.java? seems to convert relative url to absolute url resulting in unique urls and hashes for the same gradle-bin.zip version between projects.

it would be nice to not have duplicates for the same version of gradle between projects when using relative distributionUrls

**Comment by dellgreen** [comment]
looking at my self-contained projects on my sandboxed jenkins farm, on 1 slave alone i have accumulated 54GB of gradle wrappers.

~/.gradle/wrapper/dists

138M	./gradle-4.0-bin
448M	./gradle-3.5-bin
85M	./gradle-2.1-bin
144M	./gradle-3.4.1-bin
183M	./gradle-2.9-bin
52G	./gradle-2.14-bin
138M	./gradle-4.1-bin
95M	./gradle-2.10-bin
93M	./gradle-2.4-bin
87M	./gradle-2.3-bin
274M	./gradle-2.7-rc-1-bin
144M	./gradle-3.4-bin
54G	.
54G	total

**Comment by dellgreen** [comment]
a gradle-wrapper.properties key value pair for setting the hash value to override url hashing would be a simple solution as i already have a customized gradle wrapper task, so creating a hash of the zip file and using this as the dirname would be straight forward.

**Comment by dellgreen** [comment]
Think I have found the problem, looks like there is a bug in PathAssembler.java
The getDistName method is getting  path() from a URI rather than getSchemeSpecificPart() which prevents you being able to use the file:// scheme because it yields a null pointer exception.
Changing this seems to fix the problem

**Comment by dellgreen** [comment]
Or because file uris are supposed to be absolute then the prepareDistributionUri() in WrapperExecutor,java is incorrect as its converting a relative url to an absolute one

**Comment by dellgreen** [comment]
On closer inspection, this previously mentioned methods should stay as-is as they work with URIs and there are tests to explicitly test is an explicit test in WrapperExecutorTest.groovy that expects the url to not be a relative path.

So maybe its better to have an extra field in WrapperConfiguration.java i.e. distributionRaw which contains the original string that was set in the wrapper properties file before is was converted into an absolute path and uri. Then this distributionRaw value is used only for computing the hash in PathAssembler.java rootDirName() method for example:

       private String rootDirName(String distName, WrapperConfiguration configuration) {
        String urlHash = getHash(configuration.getDistributionRaw());
        return distName + "/" + urlHash;
    }

**Comment by dellgreen** [comment]
on reflection instead of the above it might be even better and more powerful to keep the existing behaviour, and then allow the user to supply an optional storage hash value in the wrapper.properties file, which would allow them to decide what hashing algorithm to use for storing the gradle zip file. This could also be added to the wrapper task so that it can be easily performed dynamically in code

**Comment by marcphilipp** [comment]
I think rather than making the hash algorithm or UID configurable as proposed in #2844 we should resolve these relative URLs into the same absolute one.

**Comment by dellgreen** [comment]
that would be awesome :+1:

**Comment by dellgreen** [comment]
I don't think so, as for every job that jenkins checks out the job file path will be different resulting in different hashes (same for the same job), but i have hundreds of jobs with different job names/numbers all using the same version of gradle, resulting in hundreds of copies of the same gradle version

**Comment by marcphilipp** [comment]
So, the distributions are indeed in different locations on the file system? Are the in the job's folder on Jenkins?

**Comment by dellgreen** [comment]
they are in the job folder that is cloned by jenkins

**Comment by marcphilipp** [comment]
Ok, so it looks like I've misunderstood your original request. We could use the distributions checksum instead which was probably not done originally because the ZIPs are quite big. I wouldn't want to change the default behavior either because it would cause duplicate distributions.

@gradle/core Thoughts?

**Comment by dellgreen** [comment]
This can probably be closed now as its a niche case and i have invested the time and effort into setting up Artifactory to better resolve my problem.

**Comment by marcphilipp** [comment]
Alright, thanks!
