### ISSUE TITLE
Generating Kotlin DSL accessors in 8.7-rc-3 use Any instead of actual types

### ISSUE THREAD

**Issue by hsz** [gradle/gradle#28458]
### Current Behavior

When running tests using `TestKit` with Gradle `8.7-rc-3` and debugging set to `true`:

```kotlin
GradleRunner.create()
    .withProjectDir(dir.toFile())
    .withGradleVersion("8.7-rc-3")
    .withPluginClasspath()
    .withDebug(true)
```

I noticed that execution fails on accessing i.e. extension properties:

```kotlin
import org.gradle.testkit.runner.GradleRunner
import java.io.File
import java.nio.file.Files.createTempDirectory
import kotlin.io.path.Path
import kotlin.io.path.appendText
import kotlin.io.path.createFile
import kotlin.io.path.exists
import kotlin.test.Test

class MyTest {

    @Test
    fun test() {
        val dir = createTempDirectory("tmp")

        dir
            .resolve("build.gradle.kts")
            .createFile()
            .appendText(
                """
                plugins {
                    id("my.plugin")
                }
                
                // (1)
                val myExtension = extensions.get("myExtension") as MyExtension
                myExtension.say.set("Hi!")
                
                // (2)
                myExtension {
                    say = "Oh!"
                }
                """.trimIndent()
            )

        GradleRunner.create()
            .withProjectDir(dir.toFile())
            .withGradleVersion("8.7-rc-3")
            .withPluginClasspath()
            .withDebug(true)
            .withTestKitDir(File("/tmp/gh"))
            .build()
    }
}
```

As accessing the `hi` property works with `(1)`, the `(2)` method fails with `Unresolved reference: say`.

After a comparison of Kotlin DSL accessors generated by `8.7-rc-3` and `8.6`, we can notice that `8.7-rc-3` uses `Any` as the `MyExtension` class is somehow not accessible.

<img width="1968" alt="image" src="https://github.com/gradle/gradle/assets/108333/ec710716-5b34-4aa5-a7fd-ce12d45430f2">

### Expected Behavior

Kotlin DSL accessors are generated with actual classes, not `Any` type.

### Steps to Reproduce

Repro repository: https://github.com/hsz/gradle87rc3-withdebug

Custom plugin class:

```kotlin
abstract class MyPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.extensions.create<MyExtension>("myExtension")
    }
}

interface MyExtension {
    val say: Property<String>
}
```

Test which access extension property:
```kotlin
class MyTest {

    @Test
    fun test() {
        val dir = createTempDirectory("tmp")

        dir
            .resolve("build.gradle.kts")
            .createFile()
            .appendText(
                """
                plugins {
                    id("my.plugin")
                }
                
                myExtension {
                    say = "Oh!"
                }
                """.trimIndent()
            )

        GradleRunner.create()
            .withProjectDir(dir.toFile())
            .withGradleVersion("8.7-rc-3")
            .withPluginClasspath()
            .withDebug(true)
            .build()
    }
}
```

### Gradle version

8.7-rc-3

### Gradle version that used to work

8.6

**Comment by hsz** [comment]
When running the same test project directly (not through TestKit), with the custom plugin attached via `includeBuild`, accessors are generated correctly with the `MyExtension` extension type imported and injected.

Groovy build scripts work in both cases: direct and TestKit way — replacing the `build.gradle.kts` to `build.gradle` in `MyTest` makes it work, as no Kotlin DSL accessors are involved.

**Comment by hsz** [comment]
FTR, `8.7-rc-3` with `withDebug(false)` generates correct accessors that rely on the `MyExtension` type.

**Comment by asodja** [comment]
Fixed with https://github.com/gradle/gradle/issues/28458
