### ISSUE TITLE
Make workers run as daemon scoped

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#28478]
### Expected Behavior

#21632 switched worker implementation to make workers session scoped instead of daemon scoped. This is a request to correct the flaws in the implementation that led to that PR being implemented in Gradle 8 and changing workers back to being daemon scoped.

### Current Behavior (optional)

Workers are session scoped.

### Context

Session scoped workers can create a large overhead when starting a new build which has many tasks that start workers and those workers are resource intensive to start.

**Comment by ov7a** [comment]
We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

This issue will be closed after 7 days unless you provide more information.

***

1. Can you please provide a detailed scenario when it affects you?
2. Can it be solved by [managing](https://docs.gradle.org/current/userguide/worker_api.html#creating_a_worker_daemon) daemons/workers (potentially by adding features to Gradle)?
3. Can it be solved by adding a flag to have a choice between session-scoped and daemon-scoped workers?
