### ISSUE TITLE
Worker API documentation incorrectly says process isolation creates daemons that persist across builds

### ISSUE THREAD

**Issue by 3flex** [gradle/gradle#28479]
### Issue type

Wrong or misleading information

### Problem description

https://docs.gradle.org/8.6/userguide/worker_api.html#creating_a_worker_daemon says

> These worker daemon processes will persist across builds and can be reused during subsequent builds.

This is not accurate since #21632 changed workers to run session scoped instead of daemon scoped.

It also talks about performance improvements when using worker daemons:

> Note that the execution time may be somewhat high. This is because Gradle has to start a new process for each worker daemon, which is expensive. However, if you run your task again, you’ll see that it runs much faster. This is because the worker daemon(s) started during the initial build have persisted and are available for use immediately during subsequent builds.

The last two sentences should be removed - there doesn't seem to be any performance benefit to using process isolation now, an in fact it will be quite slow because Gradle has to start a new process for each worker daemon for every build.

### Page with the problem

https://docs.gradle.org/8.6/userguide/worker_api.html#creating_a_worker_daemon

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by asodja** [comment]
Thanks, this is a good point. We should change wording here.

This issue is actionable and it's a good issue for someone that wants to contribute.

**Comment by andrewkolda** [comment]
should this issue be closed

**Comment by ov7a** [comment]
@andrewkolda indeed. Thanks!
