### ISSUE TITLE
Documentation contains only Kotlin code examples

### ISSUE THREAD

**Issue by gungwald** [gradle/gradle#28484]
### Issue type

Barrier

### Problem description

I don't know Kotlin. I'm a Java developer. I use Gradle to develop Java code. But now I have to somehow know Kotlin just to learn Gradle to develop Java. Groovy is a superset of Java so it makes sense. Kotlin is not a superset of Java so it does not make sense to me, especially the scripting DSL used by Gradle. You're putting the barrier very high for people to be able to learn Groovy. It seems like a poor strategic move on your part, since most people who use Gradle are Java developers.

### Context (optional)

I'm finding it hard to learn Gradle.

### Page with the problem

All of them

**Comment by SimonCJacobs** [comment]
Every time a Kotlin DSL code block example appears, you can switch it to Groovy by clicking the 'Groovy' tab on the code block. It also changes the rest of the code blocks on the same page and all other pages when you do so (presumably if you have cookies enabled). If there is one or more blocks where this isn't the case, I would share those examples.

**Comment by gungwald** [comment]
Okay I see that some pages have that. Some don't. For example https://docs.gradle.org/current/userguide/partr5_build_scripts.html

That led me to believe that all of them don't have it.

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
