### ISSUE TITLE
Integrate local build cache cleanup with global Gradle User Home cleanup config

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#28505]
### Expected Behavior

When cache-cleanup is configured via init-script for Gradle User Home, these settings should apply to `caches/build-cache-1` except where overridden by `DirectoryBuildCache.removeUnusedEntriesAfterDays`.

Specifically:
- Setting `cleanup = Cleanup.DISABLED` or `cleanup = Cleanup.ALWAYS` should prevent or force the cleanup of the local build cache
- If `DirectoryBuildCache.removeUnusedEntriesAfterDays` is not set, a value configured via `createdResources.setRemoveUnusedEntriesAfterDays` should be used instead. (The default value of 7 days would remain if neither of these is configured).

### Current Behavior (optional)

The schedule of build-cache cleanup is not influenced by the setting of `cleanup = Cleanup.ALWAYS` (or DISABLED).
The default retention period for build-cache entries is always 7 days, even when `createdResources.removeUnusedEntriesAfterDays` is configured.

### Context

Reliable and predictable cleanup of Gradle User Home is important to users attempting to manage disk usage, both locally and on CI.

**Comment by ov7a** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
