### ISSUE TITLE
Gradle Daemon doesnt work.

### ISSUE THREAD

**Issue by Macisialek** [gradle/gradle#28529]
### Current Behavior

PS C:\Users\rogue\Downloads\ReTerraForged-1.20.2> .\gradlew.bat buildNeeded
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.For more details on the daemon, please refer to https://docs.gradle.org/8.3/userguide/gradle_daemon.html in the Gradle documentation.
Process command line: C:\Program Files (x86)\Java\jre-1.8\bin\java.exe -Xmx4G -Dfile.encoding=windows-1250 -Duser.country=PL -Duser.language=pl -Duser.variant -cp C:\Users\rogue\.gradle\wrapper\dists\gradle-8.3-bin\dxjbbhstwasg8cbags9q7cvli\gradle-8.3\lib\gradle-launcher-8.3.jar -javaagent:C:\Users\rogue\.gradle\wrapper\dists\gradle-8.3-bin\dxjbbhstwasg8cbags9q7cvli\gradle-8.3\lib\agents\gradle-instrumentation-agent-8.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.3
Please read the following process output to find out more:
-----------------------
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

### Expected Behavior

Gradle should build the minecraft mod from a folder but it doesnt and i dont know why (not an expert). If you know what to do please help.

### Steps to Reproduce

You need to run .\gradlew.bat buildNeeded on reterraforged mod folder. (https://github.com/racoonman2/ReTerraForged)

### Gradle version

Gradle 7.6.4

### Your Environment (optional)

Windows 10, its powershell.exe

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.
