### ISSUE TITLE
Gradle toolchain warnings are logged on every execution

### ISSUE THREAD

**Issue by Donnerbart** [gradle/gradle#28527]
### Current Behavior

On build machines with "invalid" Common Linux Locations for Java, the paths are logged on every Gradle task execution. Depending on the task, the invalid paths are even logged multiple times.
```shell
donnerbart@firefly:~/IdeaProjects/helm-charts$ ./gradlew javaToolChain

> Configure project :hivemq-operator:hivemq-operator-plugins
Path for java installation '/usr/lib/jvm/openjdk-21' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-8' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-8' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-21' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-8' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-21' (Common Linux Locations) does not contain a java executable
```

### Expected Behavior

After https://github.com/gradle/gradle/pull/28311 I expected these paths to be logged once per daemon. The intended caching doesn't seem to work.

### Context (optional)

https://github.com/gradle/gradle/issues/22921
https://github.com/gradle/gradle/issues/26706

The support for `Common Linux Locations` should include that a lot of popular and common OS have these source-only folders for Java. I would suggest to either ignore these locations completely or add proper support in `org.gradle.jvm.toolchain.internal.InstallationLocation` for a source-only locations.

The default behavior should then be to ignore source-only locations in the toolchain on successful task executions (no log message at all, please). Only if no suitable installation location can be found, these folders should be listed as "installation location candidates", that were ignored because of the missing Java executable.

The source-only locations should also be shown when running with `--debug`, but not on `--info`.

This would reduce the _constant_ log spam on very common build machines, without taking away useful information in case of a build failure.

### Steps to Reproduce

* Have a build machine with the `Common Linux Locations` for Java, where some directories only contain the sources, e.g.:
```shell
donnerbart@firefly:/usr/lib/jvm$ ls -l
total 36
lrwxrwxrwx 1 root root   21  java-1.11.0-openjdk-amd64 -> java-11-openjdk-amd64
lrwxrwxrwx 1 root root   21  java-1.17.0-openjdk-amd64 -> java-17-openjdk-amd64
lrwxrwxrwx 1 root root   21  java-1.19.0-openjdk-amd64 -> java-19-openjdk-amd64
drwxr-xr-x 9 root root 4096  java-11-openjdk-amd64
lrwxrwxrwx 1 root root   21  java-1.21.0-openjdk-amd64 -> java-21-openjdk-amd64
drwxr-xr-x 9 root root 4096  java-17-openjdk-amd64
lrwxrwxrwx 1 root root   20  java-1.8.0-openjdk-amd64 -> java-8-openjdk-amd64
drwxr-xr-x 7 root root 4096  java-19-openjdk-amd64
drwxr-xr-x 9 root root 4096  java-21-openjdk-amd64
drwxr-xr-x 7 root root 4096  java-8-openjdk-amd64
drwxr-xr-x 3 root root 4096  openjdk-11
drwxr-xr-x 3 root root 4096  openjdk-17
drwxr-xr-x 3 root root 4096  openjdk-21
drwxr-xr-x 2 root root 4096  openjdk-8
donnerbart@firefly:/usr/lib/jvm$ ls -l openjdk-21
total 4
drwxr-xr-x 2 root root 4096  lib
lrwxrwxrwx 1 root root   11  src.zip -> lib/src.zip
```
* Checkout a Gradle project with a Java Toolchain, e.g. https://github.com/hivemq/helm-charts.
* Execute `./gradlew javaToolChain`.
* Repeat the last step.

### Gradle version

8.5

### Build scan URL (optional)

https://gradle.com/s/xaeen3c7me32e

### Your Environment (optional)

```shell
donnerbart@firefly:~/IdeaProjects/helm-charts$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

**Comment by ov7a** [comment]
@Donnerbart, please clarify.
The [PR](https://github.com/gradle/gradle/pull/28311) you mentioned has not been released yet (it will be included in 8.8, and the latest version is 8.7-RC4 currently).
You are using 8.5. It will not get an update.
 
 You are saying:
 > The intended caching doesn't seem to work.
 
 If you are referencing 8.5 here - that is expected. If you are referencing your build of master, please provide details for it.
