### ISSUE TITLE
idea: compile suites

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#28532]
### Expected Behavior

api may need tuning, but this would be a new api that culminates a replacement for current dependency management api, source set hackery, deficiencies in test fixtures and jvm test suites. It's a half baked idea for team discussion.

```kts
sources {
  java {
    toolchain {
      languageVersion.set(JavaLanguageVersion.of(21))
    }
  }
  val main by getting(JavaSource::class) {
    dependencies {
      compileOnly(libs.jspecify)
    }
    withJavadocJar()
    withSourcesJar()
  }
  val testFixtures by getting(JavaSource::class) {
    depenencies {
      compileOnly(libs.jspecify)
      implementation(main)
      implementation(projects.someOther)
    }
    withJavadocJar()
    withSourcesJar()
  }
  val test by getting(JavaSource::class) {
    dependencies {
      implementation(platform(libs.spring.bom))
      implementation(libs.junit.api)
      implementation(libs.assertj)
      implementation(libs.vavr)
      implementation(main)
      implementation(testFixtures)

      runtimeOnly(platform(libs.spring.bom))
      runtimeOnly(libs.junit.engine)
      runtimeOnly(libs.junit.launcher)
    }
  }
}

// same as now, just included for context
tasks.withType<Test>().configureEach {
  dependencyLocking { lockAllConfigurations() }
  useJUnitPlatform()
  reports {
    junitXml.required.set(false)
    html.required.set(false)
  }
  testLogging {
    lifecycle {
      showStandardStreams = true
      displayGranularity = 2
      exceptionFormat = TestExceptionFormat.FULL
      events.addAll(
        listOf(
          TestLogEvent.SKIPPED,
          TestLogEvent.FAILED,
        ),
      )
    }
  }
  inputs.dir(rootProject.file("buildSrc/src/main"))
}
```

### Current Behavior (optional)

this is real code, I didn't actually need test fixtures or other projects here, but you can see the next bug for how I'd have to hack in javadoc/source jars.
```kts
dependencies {
  compileOnly(libs.jspecify)
}

tasks.compileJava {
  options.release = 11
}

testing {
  suites {
    val test by getting(JvmTestSuite::class) {
      dependencies {
        implementation(platform(libs.spring.bom))
        implementation(libs.junit.api)
        implementation(libs.assertj)
        implementation(libs.vavr)
        implementation(project(path))

        runtimeOnly(platform(libs.spring.bom))
        runtimeOnly(libs.junit.engine)
        runtimeOnly(libs.junit.launcher)
      }
    }
  }
}

tasks.withType<Test>().configureEach {
  dependencyLocking { lockAllConfigurations() }
  useJUnitPlatform()
  reports {
    junitXml.required.set(false)
    html.required.set(false)
  }
  testLogging {
    lifecycle {
      showStandardStreams = true
      displayGranularity = 2
      exceptionFormat = TestExceptionFormat.FULL
      events.addAll(
        listOf(
          TestLogEvent.SKIPPED,
          TestLogEvent.FAILED,
        ),
      )
    }
  }
  inputs.dir(rootProject.file("buildSrc/src/main"))
}
```

### Context

I'll never understand why put context at the end, feels linguistically unnatural.

This idea is based around [this deficiency that makes test-fixtures feel unfinished](https://github.com/gradle/gradle/issues/20539) and the real mentality of what it is and needs to be fixture always has been.  the problem with test fixtures before the `test-fixtures` plugin and the workaround in that bug is it's a lot of code and hard for us mere mortals to understand. It's also based around the api for Jvm test suites. I don't know that this issue is a real action item, but more an idea for team discussion. It'd probably be a huge piece of work.

Additionally I'm using the gradlex plugin that lets me turn my test suite into a jpms module. That feels like a good idea in general, to treat these as separate modules... perhaps automagically like it does if a `module-info.java` is present it'd be considered a separate module. I think modules need to be thought about if this thought is progressed on.

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
Thanks for the suggestions.  We're working on how we can improve JVM modeling in ways similar to what you've suggested as part of the Declarative Gradle effort. You'll hear more about this as work continues.
