### ISSUE TITLE
Don't fall through to the next repository on timeouts

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#2853]
I noticed that the fixes for network connection issues to repositories, cause a repository to be disabled:

https://github.com/gradle/gradle/blob/ebab52b6e2083496308fc30d32eb94c038eab66a/subprojects/docs/src/docs/release/notes.md#timeouts-for-http-requests

That's a serious change in behavior. Dependency and build correctness often depends on the exact ordering of repositories. Internal repositories may shadow OSS artifacts in public repositories for security, compliance or legacy reasons. Local repositories might be a last-resort fallback for missing dependencies, but have development dependencies published in them. 

While we're frequently impacted by the issues caused by lack of connection timeouts (developers forgetting their VPN connection - we have init script checks w/ timeouts to catch the problems), this solution overcorrects and undermines build confidence. 

Build repeatability and determinism should _always_ come before efforts to protect the build from unreliable external resources.

### Expected Behavior
A failure to resolve a dependency in a configured repository fails the build.

### Current Behavior
The build will continue, perhaps resolving an artifact from a different repository than would usually be possible.

**Comment by oehme** [comment]
The blacklisting is inteded (to stop other requests from being made), but resolution should not fall through to the next repo, but mark that artifact as failed instead.

**Comment by bmuschko** [comment]
@oehme We should revisit this again to make sure it works as expected. 

[This test case](https://github.com/gradle/gradle/blob/release/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/DependencyResolveTimeoutIntegrationTest.groovy#L154) shows that if the metadata resolution fails with a timeout then the next repository is checked. The behavior aligns with other conditions e.g. if you receive a HTTP 500 (`moduleA.pom.expectGetBroken()`) from the metadata resolution request. In that regard it doesn't look like behavior has changed from previous versions of Gradle if I am not mistaken.

However, if the metadata can be resolved but the artifact can't (e.g. timeout or HTTP 500) then the secondary repository is not checked. You can verify that by changing the expectations as follows for the same test case.

```
moduleA.pom.expectGet()
moduleA.artifact.expectGetBlocking()
```

**Comment by adammurdoch** [comment]
The HTTP 500 case is wrong. We should not continue to the next repository unless we can answer the question "is this module present in this repository?". We cannot answer this question on a 500 response or a timeout.

**Comment by oehme** [comment]
Agreed, we should only continue if we got a clear "It's not here". If the answer is "We don't know", we need to fail that module's resolution.

**Comment by oehme** [comment]
This is on `release` now
