### ISSUE TITLE
Incorrect java warning/error location in new Problems API

### ISSUE THREAD

**Issue by Arthurm1** [gradle/gradle#28554]
### Current Behavior

Take something like...
```java
public class WarningsCreator {

  private static int idx = 0;

  private void createIndirectAccessWarning() {
    int idx = new WarningsCreator().idx;
  }
}
```

with compile settings...
```groovy
tasks.withType(JavaCompile).configureEach {
	options.compilerArgs << '-Xlint:all'
}
```

Java will throw a warning: `static variable should be qualified by type name, WarningsCreator, instead of by an expression`

The `javax.tools.Diagnostic` class will have the following position data for this warning...

```java
    int idx = new WarningsCreator().idx;
              ^                               startPosition (in file)
                                      ^       endPosition (in file)
                                   ^          position (in file)
                                   ^          columnNumber (in line)
```
This is because Java sets `startPosition` and `endPosition` to the whole `new WarningsCreator().idx` range but it sets `columnNumber`, `position` to point to the start of `.idx;`

The `offsetInFileLocation` is being reported using `startPosition` and `endPosition - startPosition` (so the length is 25).  This is correct.

But the **`lineInFileLocation`** is being reported incorrectly because the `length` is calculated using `endPosition - startPosition` (i.e. 25) when it **should be using `endPosition - position`** (i.e. 4)

### Expected Behavior

The length in `lineInFileLocation` should be correct

### Context (optional)

Trying to highlight the errors/warning correctly in an IDE

### Steps to Reproduce

Use the simple java snippet above with the `xlint` settings provided.

### Gradle version

8.8-20240323001552+0000

### Your Environment (optional)

Windows 11

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by Arthurm1** [comment]
@hegyibalint Thanks for replying - no worries on timing.

I think the whole Java `Diagnostic` class is a bit bizarre as it reports a range **and** a position in the range.

`startPosition` -> `endPosition` is highlighting...
```java
    int idx = new WarningsCreator().idx;
              ^^^^^^^^^^^^^^^^^^^^^^^^^
```

Whereas `position` is highlighting...
```java
    int idx = new WarningsCreator().idx;
                                   ^
```

Both of the above are position in the file - nothing to do with line/column numbers.

According to https://docs.oracle.com/javase/8/docs/api/javax/tools/Diagnostic.html, `position`, `lineNumber`, `columnNumber` all relate to the same position and `startPosition` <= `position` <= `endPosition`

I guess you could use `position`->`endPosition` in `offsetInFileLocation` and then the length would have to be 4 but then you could also argue for using `startPosition`->`position` and the length would have to be 21.  I think using `startPosition` and `endPosition` is correct - so length of 25.

In `lineInFileLocation` you could just miss out the `length`, but from an IDE client point of view, a highlighted range is much easier to locate on the screen using length of `endPosition - position`

It's annoying the the compiler doesn't supply `startLine`, `startColumn`, `endLine`, `endColumn` as well.

**Comment by hegyibalint** [comment]
I would need to run this on more warning examples, but when you look specifically at this warning:
> static variable should be qualified by type name

I would argue that the `.idx` part is the emphasized part, as it causes the warning. Now if this is universal (i.e. `end - position` always marks at the "interesting" part) would need some trials, but I wouldn't be surprised if not. In this case, I think a new location could be introduced: a location which would mark a "point of interest" in the range of `start..end`. 

That being said, I can also see that `columnNumber` doesn't have a per-line range (so you cannot say that in line X between column A..B there is an interesting point C)

I will think about this myself, but feel free to express what you think a consumer (i.e., a user looking at the editor) should see!

**Comment by hegyibalint** [comment]
I think I've found a solid case when the length becomes `position - start`, it's a simple unnecessary cast:

```java
public class UnusedVariableExample {
    public int calculate(int a, int b) {
        return (int)(a + b);
        //     ^  startPosition (in file)
        //                 ^  endPosition (in file)
        //     ^ position (in file)
        //     ^ columnNumber (in line)
    }
}
```

Meanwhile a bit unhappy realizing that probably we cannot pinpoint always the _exact_ location, I can see that the offset and line+column location types are harmonized, which is much better.

I think I will carry on with the current solution in the PR, which seems to do already a good enough job.
