### ISSUE TITLE
[8.7, 8.6,...] Annotation processing issue 

### ISSUE THREAD

**Issue by hrstoyanov** [gradle/gradle#28553]
### Current Behavior

I have 2 annotation processor defined in my project - one works, the other one is ignored by Gradle for no reason?

### Expected Behavior

I expected both annotation processor to work!

### Steps to Reproduce

[I have published a reproducible code](https://github.com/hrstoyanov/gradle-issue-28553), look at the README.md for complete instructions.

### Gradle version

8.7 (also 8.6 and possibly earlier)

### Your Environment (optional)

Java 21, MacOS Sonoma 14.3.1

**Comment by ov7a** [comment]
Gradle delegates annotation processing to the java compiler. Here's what it does:
```
javac -d app/build/classes/java/main -h app/build/generated/sources/headers/java/main -g -sourcepath app/src/main/java -processorpath $HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.serializer/codegen-wrapping/1.3.1/e93faa368fd9c5dd5ead491582dd5bb2e16e169f/codegen-wrapping-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.serializer/codegen-entity/1.3.1/8e720eae1673ad556be6b95baccfb1253559ab74/codegen-entity-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.serializer/base/1.3.1/ea103bbd3d57096e46f028f7794d695a83571a98/base-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/2.0.12/48f109a2a6d8f446c794f3e3fa0d86df0cdfa312/slf4j-api-2.0.12.jar -s $HOME/Downloads/gradle-issue-28553/app/build/generated/sources/annotationProcessor/java/main -XDuseUnsharedTable=true --module-path $HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.store/storage-embedded/1.3.1/713c312989ba795bcc7846c697dcfd914fbd0e4/storage-embedded-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.store/storage/1.3.1/a3d0b17cddca6219cf53305206b9274f7f9d4558/storage-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.store/afs-nio/1.3.1/e8d383bd7fd754880ba37f5876ace38efc2c3bc4/afs-nio-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.serializer/persistence-binary/1.3.1/d1d863f1f7c6c90ac0fdbcf6cf953d9d9adfbc25/persistence-binary-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.serializer/persistence/1.3.1/9e00371be8e2f59b4a1496582901f1d4ffb66a31/persistence-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.serializer/afs/1.3.1/75fe16aa5c826af6a3d3ae5d0fdea3a6d4fde3b3/afs-1.3.1.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/2.0.12/48f109a2a6d8f446c794f3e3fa0d86df0cdfa312/slf4j-api-2.0.12.jar:$HOME/.gradle/caches/modules-2/files-2.1/org.eclipse.serializer/base/1.3.1/ea103bbd3d57096e46f028f7794d695a83571a98/base-1.3.1.jar -Awrapper.types=org.eclipse.serializer.persistence.types.PersistenceStoring -Aentity.hashequalator=true -Aentity.appendable=true app/src/main/java/module-info.java app/src/main/java/issue/JulLogger.java app/src/main/java/issue/Pet.java app/src/main/java/issue/Beeing.java app/src/main/java/issue/Address.java app/src/main/java/issue/Human.java app/src/main/java/issue/EntityFactory.java app/src/main/java/issue/Named.java app/src/main/java/issue/Animal.java
```
This command produces the same output with the warning:
```
Note: Generating org.eclipse.serializer.persistence.types._wrapper.WrapperPersistenceStoring
warning: The following options were not recognized by any processor: '[entity.appendable, entity.hashequalator]'
1 warning
```
So it's either a misconfiguration or some issue with the annotation processor (it being discoverable, specifically). I don't see any obvious issues in [the source code](https://github.com/eclipse-serializer/serializer/tree/main/codegen/entity).

@hrstoyanov can you invoke the `javac` with this annotation processor?

**Comment by big-guy** [comment]
Thanks for the reproducer.

The way the annotation processor is defined is wrong:
https://github.com/eclipse-serializer/serializer/tree/main/codegen/entity/src/main/resources/META-INF.services

This is creating a file called `META-INF.services` instead of a file called `services` in the directory `META-INF`.

This is different from the way the wrapper annotation processor is defined:
https://github.com/eclipse-serializer/serializer/tree/main/codegen/wrapping/src/main/resources/META-INF/services

You can see this in the built jar too. If the codegen annotation processor moved `META-INF.services` to `META-INF/services`, I think everything would work as expected. 

The reason this works with Maven is that the EclipseStore documentation explicitly lists the class name to use as an annotation processor.

Until a new version of the codegen annotation processor is released, you can workaround this by explicitly listing the annotation processors as compiler args:
```
 '-processor', 'org.eclipse.serializer.codegen.entity.EntityProcessor,org.eclipse.serializer.codegen.wrapping.WrapperProcessor'
```
