### ISSUE TITLE
Broken link in section https://docs.gradle.org/current/userguide/writing_build_scripts.html#the_project_object

### ISSUE THREAD

**Issue by manuelcarriernunes** [gradle/gradle#28559]
### Issue type

Missing information

### Problem description

The "Gradle API" link in the first sentence of the https://docs.gradle.org/current/userguide/writing_build_scripts.html#the_project_object section is broken.

### Page with the problem

https://docs.gradle.org/current/userguide/writing_build_scripts.html#the_project_object

**Comment by lkasso** [comment]
Thank you @manuelcarriernunes. This will be fixed asap.
