### ISSUE TITLE
Plugin [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.8.0'] was not found in any of the following sources

### ISSUE THREAD

**Issue by pengzj** [gradle/gradle#28561]
### Current Behavior

Environment:

gralde: 8.6
openJDK: 21
Oracle Linux: 9.2

------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.1 (Oracle Corporation 21.0.1+12-LTS-29)
OS:           Linux 5.15.0-105.125.6.2.el9uek.x86_64 amd64

When I try to build my app in Oracle Linux:

[XXX]# gradle pfs-web-app:bootJar -x test
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Settings file '/var/log/XXXX/build/2PisFgTyL/0/XXXX/settings.gradle' line: 9

* What went wrong:
Plugin [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.8.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin:0.8.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Here is my settings.gradle

```
plugins {
    id "org.gradle.toolchains.foojay-resolver-convention" version "0.8.0"
}

rootProject.name = 'one'
include 'one-api-app'
include 'one-web-app'
include 'one-common'
```

### Expected Behavior

We should be able to find the org.gradle.toolchains.foojay-resolver-convention
and gradle can build successullly

### Steps to Reproduce

Step1: you have one Oracle Linux (9.x)

Step2:
gradle init (to create one project)

Step 3:

gradle build

And then you will get the error

### Gradle version

8.6

**Comment by ljacomet** [comment]
The plugin is for sure present on the Gradle plugin portal:
* [POM file](https://plugins.gradle.org/m2/org/gradle/toolchains/foojay-resolver-convention/org.gradle.toolchains.foojay-resolver-convention.gradle.plugin/0.8.0/)
* [Plugin reference](https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention)

So, this is most likely an environment issue. 
Can you share the [stacktrace](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_debugging) from the build error?

**Comment by rish490** [comment]
I am not exactly sure why this happens but i can list some steps which can help
first delete your node modules folder from root project directory now delete node modules using 
rm -rf node_modules then 
you might need to clear cache once
npm cache clean --force
then do
npm install --force
npm install --legacy-peer-deps
this will update your dependencies to latest version this would help

**Comment by srirambtechit** [comment]
I'm not sure what is causing this issue but was able to fix this issue.

Delete the `.gradle` directory in `$HOME` location
```
% rm -rf ~/.gradle
```

Run the app using the wrapper
```
% ./gradlew run
Downloading https://services.gradle.org/distributions/gradle-8.7-bin.zip
............10%.............20%.............30%.............40%............50%.............60%.............70%.............80%.............90%............100%

Welcome to Gradle 8.7!

Here are the highlights of this release:
 - Compiling and testing with Java 22
 - Cacheable Groovy script compilation
 - New methods in lazy collection properties

For more details see https://docs.gradle.org/8.7/release-notes.html

Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :app:run
Hello World!

BUILD SUCCESSFUL in 24s
2 actionable tasks: 1 executed, 1 up-to-date
```

**Comment by SRH603** [comment]
I'm experiencing the same problem except it‘s version 0.7.0, I've tried different Java and Gradle versions but don't work

**Comment by iEverX** [comment]
encounter same problem, resolve by setting network proxy

**Comment by mucst** [comment]
Also don't forget to stop/kill existing running daemons and java processes. Use `jps` tool for best efficiency or `gradle --stop`.

**Comment by syed-muhammad-aizaz-haider-zaidee** [comment]
If you are behind a firewall or proxy then make sure you have `gradle.properties` file at the root of the project or in `.gradle `folder

```
systemProp.http.proxyHost=???
systemProp.http.proxyPort=???
systemProp.https.proxyHost=???
systemProp.https.proxyPort=???
```
