### ISSUE TITLE
Add convenience DSL for adding repositories for GitLab's maven package repository and dependency proxy

### ISSUE THREAD

**Issue by xenomachina** [gradle/gradle#28595]
### Expected Behavior

It'd be nice if we could do something like:

``` kotlin
repositories {
    // In GitLab CI, uses the project's dependency proxy, otherwise uses mavenCentral()
    gitlabDependencyProxy { 
        fallback { mavenCentral() }
    }

    // Adds the specified GitLab group's maven package repository. Uses personal access token,
    // `pat`, if non-null, otherwise uses GitLab's CI environment variables if available,
    // otherwise fails. 
    gitlabGroupMaven("mygroup") {
        pat = findProperty("com.gitlab.pat")
    }
}
```

### Current Behavior (optional)

The equivalent of

``` kotlin
gitlabGroupMaven("mygroup") {
    pat = findProperty("com.gitlab.pat")
}
```

is

``` kotlin
maven("https://gitlab.com/api/v4/groups/mygroup/-/packages/maven") {
    name = "gitlab-maven"
    credentials(HttpHeaderCredentials::class) {
        project.findProperty("com.gitlab.pat")?.let {
            name = "Private-Token"
            value = it as String
        } ?: System.getenv("CI_JOB_TOKEN")?.let {
            name = "Job-Token"
            value = it
        } ?: throw Error(
            """
            Add "com.gitlab.pat=[TOKEN]" to ~/.gradle/gradle.properties
            """.trimIndent().trim()
        )
    }
    authentication {
        create<HttpHeaderAuthentication>("header")
    }
}
```

A similar amount of boilerplate is required to emulate the proposed `gitlabDependencyProxy`.

### Context

While both of these can currently be done with `maven()`, it requires a **lot** of boilerplate. This is especially problematic when a GitLab group has multiple GitLab projects that use Gradle and either share artifacts via GitLab's maven package repository, or use the GitLab dependency proxy (or both), because it isn't possible to completely factor out this boilerplate into a plugin, as loading the plugin itself requires using this boilerplate.

The GitLab boilerplate is also pretty finicky, and easy to get wrong. It's hard to debug, because almost everything looks like a 404. (GitLab returns 404s on authentication failures, presumably to avoid probing for private resources.)

**Comment by ov7a** [comment]
Sorry, we don't plan to support this in Gradle core. 
Convenience functionality like this should be done via a plugin.

**Comment by xenomachina** [comment]
> Convenience functionality like this should be done via a plugin.

Doesn't this run into a bootstrapping problem? Can a plugin be used to add functionality that's usable from within `buildscript`, so it can be used to load other plugins?

For example, if we have a custom `our-company` plugin that we publish to a GitLab maven repository, how can we use a `gitlab-repos` plugin to add that repository so we can then apply the `our-company` plugin?

**Comment by ov7a** [comment]
You can use an init script. See also [this discussion](https://discuss.gradle.org/t/how-to-create-custom-repository-type/7540). It's a bit old, but the principles are the same.

**Comment by xenomachina** [comment]
Doesn't an init script require access to the same file system? We have multiple repos that do not share a common file system. (eg: they are built in separate containers in CI) Common code is shared between the repos via the maven repository.

**Comment by ov7a** [comment]
I think the problem is solvable with the existing tools we have. For details, please reach out to GitLab (they might be interested in solving this in a general fashion or can have a recipe for that) and [our community](https://help.gradle.org).
