### ISSUE TITLE
Remove JVM target validation control code in Kotlin DSL

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#28614]
When https://youtrack.jetbrains.com/issue/KT-66919 is resolved, remove the code that sets the `jvmTargetValidationMode` to `WARNING`.

See comment posted by @eskatos in https://github.com/gradle/gradle/pull/28603#discussion_r1542488381.

**Comment by octylFractal** [comment]
Leaving this in triage for the Kotlin DSL folks to decide what milestone they want to track this under.

**Comment by eskatos** [comment]
[KT-66919](https://youtrack.jetbrains.com/issue/KT-66919) has been closed as _As Designed_

@octylFractal, I'm tempted to leave things as they are, what do you think we should do?

**Comment by octylFractal** [comment]
Yeah, I think that it's fine as-is.
