### ISSUE TITLE
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'com.vanniktech.maven.publish.MavenPublishBasePlugin'.

### ISSUE THREAD

**Issue by ChineseBoyLY** [gradle/gradle#28622]
### Expected Behavior

Please tell me how to put it in buildSrc for unified encapsulation and use. Thanks！

### Current Behavior (optional)

Please tell me how to put it in buildSrc for unified encapsulation and use. Thanks！

### Context

Please tell me how to put it in buildSrc for unified encapsulation and use. Thanks！

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.
