### ISSUE TITLE
IPv6 Support by default

### ISSUE THREAD

**Issue by SimonErm** [gradle/gradle#28642]
### Expected Behavior

Gradle(Wrapper) build should work normally on IPv6-only hosts.

### Current Behavior (optional)

Executing Gradle(Wrapper) on a IPv6 only host fails because it can't resolve hosts.

### Context

Currently gradle(wrapper) can't be executed on an IPv6-only host by default.
The first problem is that services.gradle.org (which supports IPv6) just redirects to the github release page which doesn't support IPv6.
Workaround: Replace distributionUrl in wrapper/gradle-wrapper.properties.
Long-Term-Fix: Use a different binary-host/Github introduces IPv6-Support

The second problem is that some plugin dependencies which are resolved over 'https://plugins.gradle.org/m2' like 'https://plugins.gradle.org/m2/org/springframework/spring-core/6.0.11/spring-core-6.0.11.pom' are redirected to jcenter.bintray.com which doesn't support IPv6.
Workaround: Add mavenCentral() to pluginManagement.repositories
Long-Term-Fix: Not sure if this is an issue because of missing migration from bintray or a real issue (because the example dependency is not that old) or not an issue related to gradle.

**Comment by ov7a** [comment]
We can reach out to those services, but we don't have a way to resolve it for them. Thus, we're closing this

We may reconsider this decision if there's a larger community impact.

Related:
* https://github.com/orgs/community/discussions/10539
* https://github.com/gradle/plugin-portal-requests/issues/165

**Comment by bsabiston** [comment]
@SimonErm do the workarounds work for you? Can you elaborate on how to implement them?  I am running into this issue...

**Comment by SimonErm** [comment]
@bsabiston  yes it worked. For the distribuitionUrl you can use https\://gh-v6.com/gradle/gradle-distributions/releases/download/v8.7.0/gradle-8.7-bin.zip for exampe.

**Comment by bsabiston** [comment]
Hm, that URL isn't accessible from our ipV6 machines.  I can access it from my ipV4 machine though.
What about your workaround for the second issue - the "Workaround: Add mavenCentral() to pluginManagement.repositories"?  is that just a file you add to?
