### ISSUE TITLE
Deprecate configure-on-demand

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#2868]
With the recent improvements in performance, configure-on-demand no longer seems to be a valuable feature. Most users misunderstand how it works and don't actually get any benefit anyway (i.e. they use `subprojects {}`, `allprojects {}`, thereby negating any laziness). At the same time, configure-on-demand creates a lot of complexity in our code base and surprises users with many corner cases.

One open question is when we remove the feature. We could leave it working until 5.0 and only deprecate the switch/API. Or we could already completely remove the feature under the hood and only leave the switch/API in place, which would then be no-ops until they are removed in 5.0

**Comment by oehme** [comment]
After discussing this on the team, we decided to only deprecate and keep the logic around until 5.0. This will give us time to see if there are any exceptional builds still out there that would require more optimizations in Gradle itself.

**Comment by ldaley** [comment]
We might be underestimating how much of an optimisation this can be.

On a, relatively small, 58 project build that is optimised for CoD, it can save .8s.

CoD on: https://e.grdev.net/s/55lctfezzmmzi/performance/build
CoD off: https://e.grdev.net/s/c2dx5qbwibaom/performance/build

This is a warmed up daemon with runs of both CoD on and off (i.e. cache is warmed with all projects).

There is practically no configuration injection in the project. Each project pulls the configuration it needs.

**Comment by ldaley** [comment]
One place where you particularly feel this is when executing individual tests in idea.

**Comment by oehme** [comment]
It would be interesting to see why this small project takes comparatiely long to configure. For reference - 1s is about what it takes to fully configure our 500-project performance test build. Did you run some experiments with JProfiler?

**Comment by ldaley** [comment]
I'm not arguing for the status quo. 

It's unreasonable to expect users to optimise for CoD now as we provide no help. Nothing about that is set in stone though.

If we can make things fast enough without CoD then all the better. FWIW I'm skeptical about this though without an alternative.

No I don't know why it takes 1s. My only thought is that it might be, ironically, that more scripts are executed due to the lack of configuration injection.

**Comment by ldaley** [comment]
> we decided to only deprecate and keep the logic around until 5.0. This will give us time to see if there are any exceptional builds still out there that would require more optimizations in Gradle itself.

Isn't this cart before horse? Shouldn't we be more confident about the situation before even deprecating, which is basically a commitment to removing?

**Comment by oehme** [comment]
So far we are not aware of a project in the wild (not maintained by Gradle) that is benefiting from CoD. The deprecation (if worded carefully) would allow us to find these projects and either improve their situation for the full configuration case enough for them to be satisfied or undo the deprecation if it turns out that CoD is the only way for them to be productive. 

I'm open to other ways we could get this insight. Twitter only reaches a small fraction of our user base, so a poll there probably wouldn't turn up those special cases. 

Improving CoD to the point where it is easy and safe to use would take significant effort. Plus, it only helps in the cases where you are only configuring some of the projects. It doesn't help with things like IDE sync or calling `gradle tasks` and anything else that requires full configuration.

**Comment by ldaley** [comment]
I don't think it would be hard to make it easy or safe if we actually tried. We'd need some new constructs and ways of preventing undeclared access, but these are doable things.

> Plus, it only helps in the cases where you are only configuring some of the projects.

Which is reasonably common. When I have my IDE execute a test through Gradle (or any concrete task) for that matter this is the case. I'm not arguing that investing in CoD should be done at the expense of making the configure-everything case faster.

Anyway, we are going around in circles. 

I don't have any alternative suggestions for determining how widely utilised CoD is, so I'll withdraw my objection (such as it is) from the plan of deprecating this.

**Comment by oehme** [comment]
> We'd need some new constructs and ways of preventing undeclared access, but these are doable things.

The bigger issue is that we'd need new constructs for cross-configuration and publishing things other than artifacts between projects.

> I don't have any alternative suggestions for determining how widely utilised CoD is

We did come up with a few ideas to tackle this (and other similar decisions), so we'll do a softer deprecation. We will:

- remove calls to action like "try out CoD" from the user/performance guide
- write a blog post/tweet explaining our intent to remove it, asking for feedback
- solicit feedback from our partners directly

If we turn up with no serious objections after this, we'll go forward with the deprecation in the next release. Does that sound good to you?

**Comment by simtel12** [comment]
As a point of data: On our 52 project Android build, checking available tasks for a single project is <1 second second with configure-on-demand and 14 seconds without.  Even using it with our most heavy-weight project is just a 5 second configuration if we use configure-on-demand vs 13s without.  In general, configuration for an actual build takes ~15-20 seconds if we don't use configure-on-demand and 1-5 seconds if we do.  This is all with a warm daemon.

We don't use configure-on-demand for general use though, as it seems to have problems with annotationProcessors in a couple of our projects and we haven't spent the time to figure out why.

**Comment by oehme** [comment]
@simtel12 neither 5s nor 15s is a normal configuration time. Can you please use the [Gradle Profiler](https://github.com/gradle/gradle-profiler) to produce a JFR recording and send it over?

50 Android projects should configure in well under 1s.

**Comment by simtel12** [comment]
I believe I misspoke - I was trying to multi-task and the thoughts about the 'annotation processor' bit bled over from my other conversations.  We had flirted with configure-on-demand about 5 months ago, so I was operating on an old cache.  After looking it up, the reason we disabled it was a ConcurrentModificationException that occurred while configuring the unit test configuration:

```
Could not determine the dependencies of task ':minerva:testReleaseUnitTest'.
> Could not resolve all dependencies for configuration ':minerva:releaseUnitTestRuntimeClasspath'.
   > java.util.ConcurrentModificationException (no error message)
```

I haven't checked if that particular problem still exists.

I'm pretty sure the majority of the performance problems we have come from the number of flavor dimensions we have (the configuration of which don't show up in --profile).  2 of the modules have 3 dimensions with between 3-8 flavors each and 4 build types - which comes out to ~380 variants, IIRC.  The other modules generally have 0-1 dimensions with 2-3 flavors at most, and the standard 2 build types.  I'm trying to convince other engineers that we should approach it differently, but... it ends up being quite a bit to configure when not using configure-on-demand.

With some creative variant ignoring, I've gotten the average configure time down to ~3 seconds - but it definitely feels like a stop-gap/hack.

I'll try to get to actually profiling it early next week.

**Comment by simtel12** [comment]
So after a few runs with gradle-profiler, [this is the breakdown of the execution:](https://imgur.com/ACJzok4) . And [this is the breakdown of configuration](https://imgur.com/zKpjU9y).

As you can see, the configuration breakdown is not exactly forthcoming about what is taking so long.  @oehme Should I send the JFR recording to your gmail, or is there a better address?

**Comment by oehme** [comment]
I'm closing this issue as we don't intend to deprecate --configure-on-demand yet based on some of the feedback we got. Our goal is to provide a new mode that enforces project isolation and thus makes it safe to configure in parallel and on demand. Once such a mode exists, `--configure-on-demand` will be deprecated in favor of it.

**Comment by oehme** [comment]
@high-stakes and @cortinico: I saw that you gave this a 😕. Would you mind sending [JFR recordings](https://github.com/gradle/gradle-profiler) as well, like @simtel12 did? We may find some low-hanging fruit in your builds as well.

`gradle-profiler --profile jfr --warmups 10 --iterations 20 help`

**Comment by AarjavP** [comment]
Is there a way to programmatically enable this feature in `settings.gradle`? Possibly through `enableFeaturePreview`?

**Comment by oehme** [comment]
No, you can either use the flag or the property. However, you are unlikely to get any benefit from it and it can give you surprising failures, which is why we wanted to deprecate it in the first place.

**Comment by GOVINDDIXIT** [comment]
@oehme  I have recently installed android studio 3.2.1 and I am unable to disable configure on demand as the checkbox is not present at  File > Settings > Build, Execution, Deployment > Compiler. Is there any way I can disable it.

**Comment by oehme** [comment]
It's off by default.

**Comment by GOVINDDIXIT** [comment]
Yes I didn't mention it in gradle.properties but still It is throwing [error](https://stackoverflow.com/questions/53154840/how-to-handle-configuration-on-demand-not-supported-error-on-android-studio-3-2)

**Comment by oehme** [comment]
Make sure you don't have it in the gradle.properties in your Gradle user home (`~/.gradle`).
