### ISSUE TITLE
Develocity capture.fileFingerprints has conflicting documentation

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#28694]
### Issue type

Wrong or misleading information

### Problem description

Develocity docs says:
>  In addition, the paths and content hashes of individual input files of each property are captured by default. -- [plugin docs](https://docs.gradle.com/enterprise/gradle-plugin/current/#capturing_file_fingerprints)

and also implies it's enabled by default because the next section is titled "When to disable".

However the JavaDoc says the opposite:
> Defaults to false. -- [BuildScanCaptureConfiguration.getFileFingerprints](https://docs.gradle.com/enterprise/gradle-plugin/api/com/gradle/develocity/agent/gradle/scan/BuildScanCaptureConfiguration.html#getFileFingerprints())

---

For reference, the Gradle Enterprise docs say:

> Since Gradle plugin 3.17, the paths and content hashes of individual task input files of each property are also captured by default. For older versions, this can be enabled on an opt-in basis. They allow identifying which individual files changed for a task when comparing two builds. -- [legacy docs](https://docs.gradle.com/enterprise/gradle-plugin/legacy/#capturing_task_input_files)

And the Javadoc says the same:
> Defaults to false. -- [BuildScanCaptureSettings.taskInputFiles](https://docs.gradle.com/enterprise/gradle-plugin/api/com/gradle/scan/plugin/BuildScanCaptureSettings.html#setTaskInputFiles(boolean)).

### Context (optional)

I understand it might be technically correct that the property's default is `false`, because the resolution of it will default to `true`. However from a DX perspective, when users are reading API docs, it feels misleading.

### Page with the problem

https://docs.gradle.com/enterprise/gradle-plugin/api/com/gradle/develocity/agent/gradle/scan/BuildScanCaptureConfiguration.html#getFileFingerprints()

**Comment by ov7a** [comment]
This is a valid documentation issue.

**Comment by wolfs** [comment]
Fixed in 3.17.2
