### ISSUE TITLE
Typo in Develocity buildScan terms code

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#28699]
### Issue type

Typo (please open a PR instead)

### Problem description

Cannot open a PR, code not found in repo.

Groovy code block at [scan setup](https://docs.gradle.com/enterprise/gradle-plugin/current/#connecting_to_scans_gradle_com) is wrong:

```patch
develocity {
    buildScan {
        termsOfUseUrl = "https://gradle.com/help/legal-terms-of-use"
-       termsOfUseUrl = "yes"
+       termsOfUseAgree = "yes"
    }
}
```

---

While you're around you probably want to change the Kotlin block's `.set()` syntax to just `=`, because that's the "[preferred way](https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:assignment:~:text=Using%20the%20%3D%20operator%20is%20the%20preferred%20way%20to%20call%20set()%20in%20the%20Kotlin%20DSL.)". Applies to most code blocks on that page.

### Page with the problem

https://docs.gradle.com/enterprise/gradle-plugin/current/#connecting_to_scans_gradle_com

**Comment by ov7a** [comment]
While the typo is fixed already, the note about `.set` is still valid.
