### ISSUE TITLE
Custom test reporting

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#28709]
### Expected Behavior

I would like to be able to report test results directly to Gradle from within a custom Gradle task.

I want the reported tests to be visible in the Gradle test report, correctly reported when the tests are launched in IntelliJ, and visible in CI tools (like GitHub actions).

### Current Behavior (optional)

There is no official way to report test results directly to Gradle. There is no workaround.

[TestResultProcessor](https://github.com/gradle/gradle/blob/v8.7.0/platforms/software/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/TestResultProcessor.java) is internal.

Because tests can't be reported to Gradle, this means that other tools that rely on Gradle's reporting can't pick up the custom tests.

* IntelliJ can't display the test results, which is normally very useful and allows for utils like 'click to show difference'.
* Custom tests can't be reported in CI tools, like GitHub.
* Custom tests are missing from reports, metrics, stats.

### Context

Here are some examples of when I want to report tests to Gradle:

1. I want to [Kotest](https://kotest.io/) to [support nested JavaScript tests](https://github.com/kotest/kotest/issues/3141). Currently this is not possible, because of limitations in the JavaScript testing frameworks (they do not support dynamically created nested tests). Because Kotest cannot directly report test results to Gradle, it looks like support might not even be possible.

1. I want to write a quick verification task. I want this to be reported to Gradle as a test.
    
    ```kotlin
    val checkReadme by tasks.registering {
        group = "verification"
    
        val readme = file("readme.md")
    
        val projectVersion = project.version.toString()
    
        doLast {
            require("Current project version is $projectVersion" in readme.readText()) {
                "Incorrect project version in readme"
            }
        }
    }
    ```

2. I want [BCV](https://github.com/Kotlin/binary-compatibility-validator/) validation results to be reported as tests.

2. Because Gradle doesn't fully support JUnit features (see footnote 1), I want to run the tests manually using the JUnit console launcher, and report the results to Gradle. [Example](https://github.com/junit-team/junit5/blob/7f04a28b136e8545206b66bf4b200271805beced/documentation/documentation.gradle.kts#L22-L35).

3. I want to use a non-JVM testing framework, like [Jasmine](https://jasmine.github.io/), [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/), [Cucumber](https://cucumber.io/).

#### Custom JUnit TestEngine

In theory, one could write a custom JUnit TestEngine to launch custom tests, but this is a prohibitive amount of work, especially for the simpler cases where I just want to report a single test case.

A custom TestEngine would also introduce a lot of extra complexity and layers, and potentially a new language for the non-JVM based tests. Even if using a custom TestEngine, Gradle doesn't fully support JUnit Platform (footnote 1), so this would be a non-starter.

Even if using a custom JUnit TestEngine, Gradle unnecessarily _requires_ that the input property `testClassesDirs` of a Test task has `.class` files, even if not testing JVM tests!

### Related

* https://github.com/gradle/gradle/issues/4773
* https://github.com/gradle/gradle/issues/22973
* https://github.com/gradle/gradle/issues/19549

----

Footnote 1: Here are the issues related to Gradle not fully supporting JUnit 

* https://github.com/junit-team/junit5/issues/2849
* https://github.com/gradle/gradle/issues/20941
* https://github.com/gradle/gradle/issues/4912
* https://github.com/gradle/gradle/issues/4773
* https://github.com/gradle/gradle/issues/4252
* https://github.com/gradle/gradle/issues/18682
* https://github.com/gradle/gradle/issues/15075
* https://github.com/gradle/gradle/issues/18682
* https://github.com/gradle/gradle/issues/19808
* https://github.com/gradle/gradle/issues/5511
* https://github.com/gradle/gradle/issues/4605

**Comment by big-guy** [comment]
This issue has a lot of good details, but I'm going to close it as a dupe for https://github.com/gradle/gradle/issues/31051

We're actively adding a new API to support generating test events from non-Test tasks. This will involve creating local HTML reports, sending events to TAPI clients and other Test-only features.
