### ISSUE TITLE
Provide the Sequence Task DSL 

### ISSUE THREAD

**Issue by XiLaiTL** [gradle/gradle#28713]
### Expected Behavior

Sequences mean the tasks will execute one by one.

I hope we can define the tasks sequence like this
```groovy
tasks.sequence("chain",["task1","task2","task3"])
```
Then I execute the "chain", the "task1" will be firstly executed. After "task1" finished, the "task2" begins. And so on.

### Current Behavior (optional)

We now can define the tasks do sequences by `dependsOn` and `finalizedBy`. However, it is so troublesome that you need to change them one by one.

I now use the custom task to construct the sequence tasks.

```groovy
import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;
import org.gradle.api.tasks.TaskContainer;

import javax.inject.Inject;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class SequenceTask extends DefaultTask {

    @Inject
    public SequenceTask( List<Object> sequence) {
        DefaultTask nextTask=null,task ;
        for(int i=sequence.size()-1;i>=0;i--){
            task = (i==0)? this : this.getProject().getTasks().create(this.getName()+"-"+i,DefaultTask.class);
            task.setDescription(sequence.get(i).toString());
            task.dependsOn(sequence.get(i));
            if(i !=sequence.size()-1)
                task.finalizedBy(nextTask);
            nextTask = task;
        }
    }

    @TaskAction
    public void start() {}
}
```
Usage of my defined task:

build.gradle
```groovy
tasks.register("gen-chain",SequenceTask,["clean-all","generateAssetsAndData","copyResources"])
tasks.register("build-chain",SequenceTask,["gen-chain"]+build_tasks)
```

### Context

Though I write the custom task, if I need to build other project, I should copy the `buildSrc` to the new one.
If it is possible to make the feature inner, I will be easy to execute my task.

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

This is probably not aligned with the vision of future Gradle versions. Ideally, there should be no `dependsOn` at all, and task dependencies should be discovered automatically via inputs and outputs.

**Comment by XiLaiTL** [comment]
I see, there will be on  `dependsOn` . My solution is just an ugly implementation in current version.
If there will be a one-by-one sequence task type, there is no `dependsOn`, too. Because we use the inner task type to construct the new task "chain" and will not affect the remain task `"clean-all","generateAssetsAndData","copyResources"`. 
The `dependsOn` will not happen in `"clean-all","generateAssetsAndData","copyResources"`.

**Comment by lptr** [comment]
As @ov7a mentioned, this is not inline with how Gradle thinks about the structure of the build. Tasks are defined in the context of their inputs and outputs, from which Gradle can work out what needs to be executed (or loaded from cache) to achieve a requested goals (=produce the output of the tasks you pass to it on the command-line) on its own. We use this "declarative," or "pull-style" specification of builds, as opposed to an "imperative" or "push-style," where you'd need to specify yourself which steps Gradle needs to take.

We also have support for lifecycle tasks like `assemble` and `build` that can be used as shorthands to produce multiple outputs (=request multiple tasks to be manifested).
