### ISSUE TITLE
JDK 22 & Gradle 8.7

### ISSUE THREAD

**Issue by mjmk3** [gradle/gradle#28710]
### Current Behavior

I just got issue with jdk 22 and gradle 8.7, I'm shocked when I saw it it's not working till now and till now it's not supported, I hope fixed this issue as soon as possible 

### Expected Behavior

fixed the issue 

### Context (optional)

I just got issue with jdk 22 and gradle 8.7, I'm shocked when I saw it it's not working till now and till now it's not supported, I hope fixed this issue as soon as possible 

### Steps to Reproduce

fixed versions

### Gradle version

8.7

### Your Environment (optional)

JDK 22 & Gradle 8.7

**Comment by 3flex** [comment]
It's planned for Gradle 8.8: #28552

**Comment by ov7a** [comment]
@mjmk3 Please, refer to [Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html#header). Gradle.
