### ISSUE TITLE
Investigate behaviour changes with Jacoco and TestKit after Gradle 8.7

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#28729]
It seems that after https://github.com/gradle/gradle/issues/27328 Jacoco report behaves differently. 
We probably broke the fix from https://github.com/gradle/gradle/pull/13731 that fixes https://github.com/gradle/gradle/issues/13614.

We should investigate if we can restore the previous behaviour.

**Comment by tomkoptel** [comment]
I've tried the update from @asodja https://services.gradle.org/distributions-snapshots/gradle-8.8-branch-asodja_fix_testkit_jacoco-20240408155641+0000-bin.zip

```
➜  jacoco-gradle-testkit git:(develop) ✗ ./gradle-8.8-20240408155641+0000/bin/gradle :jacocoTestCoverageVerification -PdisableFix=true --rerun-tasks

Welcome to Gradle 8.8-branch-asodja_fix_testkit_jacoco-20240408155641+0000!

Starting a Gradle Daemon (subsequent builds will be faster)
Calculating task graph as no cached configuration is available for tasks: :jacocoTestCoverageVerification

> Configure project :
disableFix: true

> Task :jacocoTestCoverageVerification FAILED
[ant:jacocoReport] Rule violated for bundle jacoco-gradle-testkit: instructions covered ratio is 0.0, but expected minimum is 0.8

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jacocoTestCoverageVerification'.
> Rule violated for bundle jacoco-gradle-testkit: instructions covered ratio is 0.0, but expected minimum is 0.8
```
The issue is still there.

**Comment by asodja** [comment]
@tomkoptel I tried `-PdisableFix=true` also with 8.6 and 8.5 and it seems it fails in the same way. Am I doing something wrong?

**Comment by asodja** [comment]
Fixed with https://github.com/gradle/gradle/pull/28730
