### ISSUE TITLE
Support Eclipse multi-project builds. Allow disabling .project generation

### ISSUE THREAD

**Issue by benmccann** [gradle/gradle#2873]
### Expected Behavior

There should be some way to not generate the `.project` folder for the parent project. E.g. sbteclipse has two options that can accomplish this: `skipParents` and `skipProject`

### Context

When you import a project into Eclipse it stops looking for sub-projects as soon as it finds a `.project` folder. Thus, it will only ever import the top-level project and not the sub-projects. I have to go through an extra step of running `rm -rf .project` every time before I can import the project into Eclipse

### Steps to Reproduce (for bugs)

Use a multi-project build. Run `gradle eclipse`. Run `find . -name .project`

### Current Behavior

There's always a `.project` folder generated for the parent project when I run `gradle eclipse`

### Your Environment

Gradle 3.5.0.3, JDK 1.8.0_121

### Submitter
I work at LinkedIn. I maintain sbteclipse and am a contributor to Play on Gradle

**Comment by oehme** [comment]
> When you import a project into Eclipse it stops looking for sub-projects as soon as it finds a .project folder. Thus, it will only ever import the top-level project and not the sub-projects.

There is a checkbox in the import dialog saying "Search for nested projects".

Apart from that, I recommend using Eclipse Buildship instead of using `gradle eclipse`. It'll give you much tighter integration, like a tasks view.
