### ISSUE TITLE
Plugins published to the plugin portal don't have a license

### ISSUE THREAD

**Issue by balrok** [gradle/gradle#28747]
### Current Behavior

Most (all?) gradle plugins found on the gradle plugin portal (https://plugins.gradle.org/m2) don't have a license in their pom.xml, while they have a license in the source-code and also when they are publishing to maven central.
Examples:
* [liquibase gradle-plugin](https://plugins.gradle.org/m2/org/liquibase/liquibase-gradle-plugin/2.0.2/liquibase-gradle-plugin-2.0.2.pom) vs [liquibase maven central](https://repo1.maven.org/maven2/org/liquibase/liquibase-gradle-plugin/2.0.2/liquibase-gradle-plugin-2.0.2.pom) and [on github](https://github.com/liquibase/liquibase-gradle-plugin/blob/master/build.gradle#L91)
* [publish gradle-plugin](https://plugins.gradle.org/m2/com/gradle/publish/plugin-publish-plugin/1.2.1/plugin-publish-plugin-1.2.1.pom) vs [publish maven central](https://repo1.maven.org/maven2/io/github/woody230/gradle/internal/plugin-publish-plugin/1.2.1/plugin-publish-plugin-1.2.1.pom)
* I just gave 2 examples, but so far I noticed this on all plugins that I checked

Besides that, some more meta-tags are missing too.

### Expected Behavior

I would expect that at least the license-tag is retained.

### Context (optional)

We want to make sure in our project, that we are not conflicting with any licenses.
If the pom doesn't contain the license it involves manually looking up the license-text.

### Steps to Reproduce

Visit the web-pages and you'll see

### Gradle version

8.5

**Comment by ov7a** [comment]
Unfortunately, we can't fix the old publications.

If you use the last version of the plugin publish plugin to publish your plugin, the information will be there if configured, which is mandatory for the publications that are published on Maven Central as well because it's required by Maven Central.

Note: your second comparison is for two unrelated plugins.

**Comment by balrok** [comment]
Sorry, for the second example I didn't watch out well enough.

I'm aware that existing publications won't be fixed. But I think the publish-plugin is not working correctly.
The liquibase-project uses version 1.1.0 and still there is no license. In the release-notes of the later versions of the publish-plugin I didn't find any updates regarding metadata/license.

**Comment by ov7a** [comment]
Take a look at these plugins as an example:
* https://plugins.gradle.org/m2/org/springframework/boot/spring-boot-gradle-plugin/3.2.4/spring-boot-gradle-plugin-3.2.4.pom
* https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/2.0.0-RC1/kotlin-gradle-plugin-2.0.0-RC1.pom

They have proper information about the license.

If you think you found a bug, please file an issue with a reproducer to
* https://github.com/gradle/plugin-portal-requests

Related:
* https://github.com/gradle/plugin-portal-requests/issues/212
