### ISSUE TITLE
The usage of plugins{} in settings.gradle

### ISSUE THREAD

**Issue by rdongxie** [gradle/gradle#28750]
### Issue type

Wrong or misleading information

### Problem description

> The settings file can optionally declare the [plugins](https://docs.gradle.org/current/javadoc/org/gradle/plugin/use/PluginDependenciesSpec.html) that may be applied later, which can add shared configuration among several builds / subprojects:
> 
> Plugins applied to the settings only affect the Settings object.
> 
> plugins {
>     id("org.gradle.toolchains.fake") version "0.6.0"
> }
> This is typically used to ensure that all subprojects use the same plugin version.

This is too confusing to read here. Is this plugin {} used to manage plugin versions?
Does it mean declare plugins in settings. gradle and then apply them in build. gradle?

For example: 
settings.gradle:
```
plugins{
  id 'org. springframework. boot' version '3.2.4'
}
```

build.gradle file
```
plugins{
  id 'org. springframework. boot'
}
```

 but it is incorrect

### Page with the problem

https://docs.gradle.org/current/userguide/writing_settings_files.html#2_apply_plugins

**Comment by ov7a** [comment]
This is a valid documentation issue. 

This section is wrong.

**Comment by lkasso** [comment]
Fixed in https://github.com/gradle/gradle/pull/28972
