### ISSUE TITLE
Remote caching of buildscripts causes large regression in IDE sync performance

### ISSUE THREAD

**Issue by joshfriend** [gradle/gradle#28752]
### Current Behavior

When remote build cache is enabled it is very difficult for us to sync our entire 5500+ project build. I believe that during the configuration phase, gradle is wasting large amounts of time checking remote build cache for compiled groovy script hits. we very aggressively optimize our builds with conventions plugins so our scripts are pretty simple (apply a few plugins and list dependencies) so we don't really expect much savings from remote caching these anyways. 

This negative avoidance in 8.7 shows up most acutely in IDE sync where every project in the build is being configured, instead of builds where a subset of projects are configured lazily on demand.

### Expected Behavior

I should be able to disable remote cache for buildscripts since it has large negative avoidance consequences. I believe this is hackily achievable by detecting the `idea.sync.active` system property being set by intellij as a workaround, but need to explore this more. That workaround would also disable remote build cache for other non-buildscript caching, like kotlin compilation of included builds (conventions plugins) or buildSrc stuff, which is undesirable.

### Context (optional)

This seems to mostly spike duration of syncs in the p90+ cases where little to no local cache of buildscripts are available. On average, the performance is closer to the same as 8.5 (but still higher on average, haven't dug in deeply to why this is yet). 

### Steps to Reproduce

1. Clear existing build cache
2. Begin sync on a large repo
3. Sync takes a _very_ long time (about 30+ minutes, it should be under 10 and configuration should take 2-3m)
4. Examining a flame graph of the daemon shows a LOT of time spent not really doing a whole lot, I believe it is mostly waiting on network latency from build cache calls, will send thread dump privately for examination
5. If I disable remote build cache, sync will complete in a more reasonable timeframe (configuration only takes 2-3m), flame graphs also look more reasonable

### Gradle version

8.7

### Gradle version that used to work

8.5 (and probably 8.6)

### Your Environment (optional)

macOS 14.4.1 on M3 max
Azul JDK 17

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
