### ISSUE TITLE
When will Gradle 8.8 be released?

### ISSUE THREAD

**Issue by xgbnl** [gradle/gradle#28773]
### Expected Behavior

I am developing a package based on JDK 22, and I need Gradle 8.8 to support it.

### Context

It would be nice if gradle 8.8 could be released to solve the problem that 8.7 does not support JVM 22

**Comment by mymbrooks** [comment]
use gradle 8.8 nightly
https://services.gradle.org/distributions-snapshots/
![image](https://github.com/gradle/gradle/assets/1232612/1c3ca771-dd4e-4e9b-b8d5-92e90ac062a8)

**Comment by xgbnl** [comment]
> use gradle 8.8 nightly https://services.gradle.org/distributions-snapshots/ ![image](https://private-user-images.githubusercontent.com/1232612/321474986-1c3ca771-dd4e-4e9b-b8d5-92e90ac062a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MDQ5ODgsIm5iZiI6MTcxMjgwNDY4OCwicGF0aCI6Ii8xMjMyNjEyLzMyMTQ3NDk4Ni0xYzNjYTc3MS1kZDRlLTRlOWItYjhkNS05MmU5MGFjMDYyYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDMwNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY5ZjgxMWYwMDRhNzAxYjQxNjQzNDkyMzVkNmEzNTE3YzE2YWU5NjdmMjI0NjBiMmNhNmZhN2VlM2M3NzhhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zWq_SMaRqQmfQKQvOFebJ52BZBN1pfHWpe9Veex784U)

Are you using gradle wrapper?

**Comment by mymbrooks** [comment]
Yes, I also tried wrapper, with or without wrapper works fine.
![image](https://github.com/gradle/gradle/assets/1232612/b4246b45-d890-4d61-b498-5c00515b7a26)

**Comment by xgbnl** [comment]
> Yes, I also tried wrapper, with or without wrapper works fine. ![image](https://private-user-images.githubusercontent.com/1232612/321485767-b4246b45-d890-4d61-b498-5c00515b7a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTQxMTAsIm5iZiI6MTcxMjgxMzgxMCwicGF0aCI6Ii8xMjMyNjEyLzMyMTQ4NTc2Ny1iNDI0NmI0NS1kODkwLTRkNjEtYjQ5OC01YzAwNTE1YjdhMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMDUzNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGIyNTdjODdlNzNlY2M1NDJjN2U3MzY0NTI2YTBjOWM5OGE3OGIxMGZhM2M3ZGFkNGNiNGNkYTFjNTNiZmFlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9WAVGK_f3MNrZa7xGPxE1GEksY1TlL7kY9LG3dCUqBs)

谢谢大佬，不过我的包依赖本地的gradle.我还是等它发布8.8再继续用吧

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

***

Refer to the [Compatibility Matrix](https://docs.gradle.org/current/userguide/compatibility.html#java). You can use 8.7 to build Java 22 projects by leveraging toolchains.
