### ISSUE TITLE
Gradle - Build Init Plugin - add a *.jar entry to generated .gitattributes

### ISSUE THREAD

**Issue by sdavids** [gradle/gradle#28796]
### Current Behavior

Gradle projects created by `gradle init` will contain a `.gitattributes` file with no `*.jar` entry.

### Expected Behavior

Gradle projects created by `gradle init` will contain a `.gitattributes` file with a `*.jar` entry.

### Context (optional)

It is a best practice to explicitly specify binary files in `.gitattributes`.

[.gitattributes Best Practices - Binary Files](https://rehansaeed.com/gitattributes-best-practices/#binary-files)

[Do I really need to specify all binary files in .gitattributes](https://stackoverflow.com/questions/57030698/do-i-really-need-to-specify-all-binary-files-in-gitattributes)

### Steps to Reproduce

[Gradle - Build Init Plugin - Build init types](https://docs.gradle.org/current/userguide/build_init_plugin.html#sec:build_init_types)

#### basic
```shell
$ mkdir /tmp/example-basic && cd "$_" && gradle init --type basic --dsl kotlin --incubating --quiet --project-name example-basic
$ find . -name '*.jar'
./gradle/wrapper/gradle-wrapper.jar
$ cat .gitattributes
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf
```
#### java-library
```shell
$ mkdir /tmp/example-java-library && cd "$_" && gradle init --type java-library --java-version 21 --test-framework junit-jupiter --dsl kotlin --incubating --quiet --project-name example-java-library
$ find . -name '*.jar'
./gradle/wrapper/gradle-wrapper.jar
$ cat .gitattributes
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf
```

#### cpp-library 
```shell
$ mkdir /tmp/example-cpp-library && cd "$_" && gradle init --type cpp-library --dsl kotlin --incubating --quiet --project-name example-cpp-library
$ find . -name '*.jar'
./gradle/wrapper/gradle-wrapper.jar
$ cat .gitattributes
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf
```

### Gradle version

8.7

**Comment by ov7a** [comment]
Thank you for providing a PR to fix this!
