### ISSUE TITLE
Polishing of Gradle build options

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#2880]
Addresses outstanding review comments from https://github.com/gradle/gradle/pull/2784

More specifically:

- [x] [Document "disabled" boolean options](https://github.com/gradle/gradle/pull/2784#pullrequestreview-60680831) that didn't exist before.
- [x] Mention new "disabled" boolean options in release notes.
- [x] Treat the [build scan option](https://github.com/gradle/gradle/pull/2784#discussion_r136729879) like any other boolean option.
- [x] [Unify logging command line options](https://github.com/gradle/gradle/pull/2784#discussion_r136730104) into a single build option.
- [x] [Unify stack trace command line options](https://github.com/gradle/gradle/pull/2784#discussion_r136730113) into a single build option.
- [x] Failure to apply a option should clearly [indicate if value came from Gradle property or command line option](https://github.com/gradle/gradle/pull/2784#discussion_r136729790).
- [x] Smaller [cleanup items](https://github.com/gradle/gradle/pull/2784#discussion_r136730022).

**Comment by oehme** [comment]
Can you list the outstanding work on this issue? This makes it easier to pick this story up later.

**Comment by bmuschko** [comment]
@oehme Done. I think we should probably get it done now after merging the change.

**Comment by oehme** [comment]
Yes, it's just easier for the reviewer to double-check that the follow-up PR contains everything we wanted.
