### ISSUE TITLE
Gradle provided samples broken. webApplication/customized shows contents of war file, not actual webapp.

### ISSUE THREAD

**Issue by pjr87** [gradle/gradle#2881]
I am attempting to build a web application using the samples provided by Gradle with the latest stable version. The samples I am referring to are in the "samples/webApplication" folder with gretty plugin. Quickstart sample works properly displaying the "Hello Gradle" as expected. The customized sample doesn't display this and instead displays the contents of the war file in the browser.  I have seen this issue in other projects that are not just confined to the sample provided by Gradle. 

### Expected Behavior
Should display "Hello Gradle". Instead, displays the contents of the war file.

### Context
This may only be with the latest version of Gradle but I need advisement on if this is true. It is preventing me from using Gradle at all.

### Steps to Reproduce (for bugs)
Do gradle appRunWar in the samples/webApplication/customized folder on the included samples with the Gradle download. 

This was reproduced by Stefan Wolf during the Gradle Webinar. 

### Your Environment
Windows. Newest stable Gradle version.

**Comment by blindpirate** [comment]
Looks like displaying "hello Gradle" is what `webApplication/quickstart` does, not the `webApplication/customized`. I'm not sure, @wolfs could you take a look at this? It would be quick.

**Comment by wolfs** [comment]
@pjr87 Thank you very much for reporting. After looking a bit more at the sample, it seems like http://localhost:8080/customized/hello yields `Hello Gradle`. I guess that is expected, given that the sample also shows how to include custom files in the war. I am closing this issue. Please re-open if you do not agree with my assessment.
