### ISSUE TITLE
Allow `@Input` to be used with task properties of type `Provider<T>`

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#2883]
`Provider<T>` and `PropertyState<T>` are intended to be used by plugin authors to allow a task to accept an input whose value is not known until later. However, the `@Input` annotation does not work well with task properties that have these types. For such a property, on task execution Gradle attempts to serialize the provider implementation, instead of snapshotting the current value of the provider.

This means that a task implementation cannot expose the rich query and set methods on `Provider` and `PropertyState` to its consumers, and instead must duplicate these methods on its public API. This is done inconsistently and in an ad hoc way, meaning an inconsistent and ad hoc DSL and work-arounds in the consumer.

### Expected Behavior

When a task property has `@Input` attached and is of type `Provider<T>` or one of its subtypes, Gradle should snapshot the observable value of the provider and include this snapshot in the task history.

### Current Behavior

Gradle attempts to serialize the provider implementation.

**Comment by oehme** [comment]
> This means that a task implementation cannot expose the rich query and set methods on Provider and PropertyState to its consumers, and instead must duplicate these methods on its public API. 

I don't understand this part. Why can't they expose the `Provider<T>` without marking it as `@Input`? Sure ,they have to add one more method that is marked `@Input` which calls `provider.get()`. But they don't have to duplicate everything from the provider if I understand the problem correctly.

**Comment by oehme** [comment]
@adammurdoch is this done in 4.3 or should we move this to 4.4?

**Comment by adammurdoch** [comment]
It's done and can be closed.
