### ISSUE TITLE
Scala 3 project build issue : scala compiler and scala library inconsistencies

### ISSUE THREAD

**Issue by loicdescotte** [gradle/gradle#28836]
### Current Behavior

Hello, I am trying to compile a scala 3 project with gradle .

The build is faling for my app (stackoverflow error during scala compile phase even with big stack size) but as you can see in the logs the wrong scala library version si picked.
I am using scala 3 but library 2.13.12 is picked  : 

 
```scala
unhandled exception while running posttyper on  [...] ProcessorLive.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/scala/scala3/issues/new/choose
  For non-enriched exceptions, compile with -Yno-enrich-error-messages.

     while compiling: /mnt/c/dalhy/heatws/src/main/scala/fr/edf/dtg/dalhy/services/HeatWSProcessorLive.scala
        during phase: posttyper
                mode: Mode(ImplicitsEnabled)
     library version: version 2.13.12
    compiler version: version 3.4.1
            settings: -Xunchecked-java-output-version 8 -bootclasspath /home/loic/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.12/[...]
```

The probleme seems to be with the bootclasspath parameter. I've tried some exclude and version force policies as you can see in my build.gradle file : 

```gradle
plugins {
    id 'scala'
}

version = "1.0.0"

configurations {
    runtime.exclude group: "org.scala-lang", module: "scala-library"
}

configurations {
    all {
        resolutionStrategy {
            eachDependency { details ->
                if (details.requested.group == 'org.scala-lang') {
                    detail.exclude(group: "org.scala-lang", module: "scala-library")
                }
            }
        }
    }
}
ext {
    scalaMajorVersion = '3'
    scalaVersion = "$scalaMajorVersion.4.1"
}

dependencies {
    zinc ("com.typesafe.zinc:zinc:1.9.6"){
        exclude( group: "org.scala-lang", module: "scala-library")
    }
    zinc "org.scala-lang:scala3-library_3:$scalaVersion"
    implementation "org.scala-lang:scala3-library_3:$scalaVersion"
    implementation "com.softwaremill.sttp.client3:zio-json_$scalaMajorVersion:3.9.5"
    testImplementation("dev.zio:zio-test_$scalaVersion:2.0.16")
}

repositories {
    mavenCentral()
}

tasks.withType(ScalaCompile) {
    scalaCompileOptions.additionalParameters = ["Xss256m"]
}

test {
    useJUnitPlatform()
}
```

Is there a way to fix this? Thanks !

### Expected Behavior

Build should use the 3.4.1 library for compile vers and library version because it is the scala version I have defined for my build

### Steps to Reproduce

Here is the reproduction project : 
https://github.com/loicdescotte/groovy-scala3-issue/tree/groovy-dsl

Run : 

```
./gradlew clean build --debug | grep scala-lib
```

It will output : 

```
[org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Resolve scala-library-2.13.12.jar (org.scala-lang:scala-library:2.13.12)' started
```

### Gradle version

8.x

### Your Environment (optional)

Gradle 8, WSL and Windows

**Comment by ov7a** [comment]
The message you are observing is about zinc dependencies. Zinc itself is [using 2.13](https://mvnrepository.com/artifact/org.scala-sbt/zinc).

If you change the zinc version to [2.0.0-alpha13](https://mvnrepository.com/artifact/org.scala-sbt/zinc_3/2.0.0-alpha13), the message about 2.13 you're observing will go away.

Note that in general, zinc dependencies should not affect your project dependencies. If you observe different behavior, please open a new issue with a reproducer (please make sure to change workflow [argument](https://github.com/loicdescotte/groovy-scala3-issue/blob/3cf338d10e2c1a30454a513d71ffa698127fe706/.github/workflows/run-reproducer.yml#L17) to get GH action failing).
