### ISSUE TITLE
Wrapper script for POSIX shell has invalid URL to groovy template

### ISSUE THREAD

**Issue by piotrminkina** [gradle/gradle#28846]
### Issue type

Wrong or misleading information

### Problem description

There is a problem in `gradlew` script. Given URL as bellow leads to 404. I don't know the correct URL for this template.

```sh
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
```

### Page with the problem

/gradlew

**Comment by ov7a** [comment]
It was moved here:
* https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt

The updated wrapper has the right URL.
