### ISSUE TITLE
Task property validation should validate the declared type T for properties of type `Provider<T>`

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#2884]
The `Provider` interface is intended to be used by task implementations to support properties whose values are not known until later. However, when a task property has type `Property<T>`, then validation is applied to the `Property` interface, rather than type `T`.

### Expected Behavior

Given a task property of type `Property<T>` or one of its subtypes, validate type `T` rather than the `Property` interface.

### Current Behavior

The `Property` interface is validated, which is pointless. The declared type `T` is not validated, which means problems are missed and not reported.

**Comment by bronogard** [comment]
Any timeframe when this will be worked on? Because the `@Nested `annotation on a task property of type `Property<T>` is also not working as expected.
