### ISSUE TITLE
Build cache configuration is ignored when applying a settings plugin that causes accessor generation

### ISSUE THREAD

**Issue by sorin-florea** [gradle/gradle#28855]
### Current Behavior

Generating the accessors for settings.gradle.kts will trigger the creation of the build cache controller, which snapshots the cache settings that haven't been configured yet.
Therefore, the build cache configuration in settings is ignored, and when using the Develocity build cache the build will fail on a configuration cache hit.

### Expected Behavior

Not trigger the snapshot of cache settings

### Steps to Reproduce

https://github.com/sorin-florea/gradle-reproducers/tree/main/build-cache

Essentially, have this in your `settings.gradle.kts`:
```
plugins {
    id("com.gradle.develocity") version "3.17.2"
}

buildCache {
    local {
        isEnabled = false
        isPush = false
    }
    remote(develocity.buildCache) {
        isEnabled = true
        server = "https://ge.gradle.org/"
    }
}
```

1. Run `gradle help --configuration-cache --build-cache`
2. Run `gradle help --configuration-cache --build-cache` again
The second build [fails](https://ge.gradle.org/s/jtc3sf3b2w6ea/failure#1) with
```
Could not create service of type BuildCacheController using .createBuildCacheController().
> Extension of type 'StateAccess' does not exist. Currently registered extension types: [ExtraPropertiesExtension]
```

### Gradle version

8.8+

### Build scan URL (optional)

https://ge.gradle.org/s/jtc3sf3b2w6ea

**Comment by ljacomet** [comment]
Fixed through
* #28879
