### ISSUE TITLE
Precompiled script plugin on Groovy with a package declaration

### ISSUE THREAD

**Issue by nbir94** [gradle/gradle#28851]
### Issue type

Wrong or misleading information

### Problem description

According to the [documentation for Precompiled script plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompile_script_plugin), there is an opportunity to add a package declaration for a plugin implemented either on Groovy or Kotlin:
> For example, the script `src/main/*/java-library.gradle(.kts)` has a plugin ID of `java-library` (assuming it has no package declaration). 
> Likewise, `src/main/*/my/java-library.gradle(.kts)` has a plugin ID of `my.java-library` as long as it has a package declaration of `my.`

By the way, it's impossible to create a plugin named `java-library` because it conflicts with a core plugin with the same name. But here I want to describe another problem.

When I implement a plugin with a package statement on Kotlin, it works according to the documentation. I could not succeed in doing the same on Groovy. If I add a package statement in the plugin having a `.gradle` extension like below:
```groovy
// buildSrc/src/main/groovy/com/example/my-plugin.gradle
package com.example
``` 
I see an error from Gradle:
> Execution failed for task ':buildSrc:extractPluginRequests'.
> Script '/Users/enbirr/IdeaProjects/precompiled-plugins/buildSrc/src/main/groovy/com/example/my-plugin.gradle' **should not contain a package statement.**

Without specifying the package in the plugin, I cannot use the plugin ID containing the package as suggested in the documentation - `com.example.my-plugin`. I assume that in this case, `com` and `example` are treated as directories rather than packages. Thus, I can only use `my-plugin` as the plugin identifier in the build script.

Is there a misleading in the documentation, or do I need to do something differently?

Gradle version: 8.7
Mac OS

### Context (optional)

I am implementing navigation to the plugin source from its ID in IntelliJ IDEA for statements like
```groovy
// build.gradle
plugins {
    id 'my-plugin'
}
```
I found this issue while learning the documentation to find possible approaches for plugin implementation. I am looking for conditions that would allow me to verify that a file found for navigation is a Gradle plugin and not something else.

### Page with the problem

https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompile_script_plugin

**Comment by ov7a** [comment]
> By the way, it's impossible to create a plugin named java-library because it conflicts with a core plugin with the same name. But here I want to describe another problem.

Indeed, the example should use a different name.

> Is there a misleading in the documentation, or do I need to do something differently?

The docs are misleading

The changes were made in 
* https://github.com/gradle/gradle/pull/28707
* https://github.com/gradle/gradle/pull/28167

Additional note:
It should be explicitly said that `id("kotlin-dsl")` / `id("groovy-gradle-plugin")` should be put into `buildSrc/build.gradle`

Another related docs page:
https://docs.gradle.org/current/userguide/implementing_gradle_plugins_precompiled.html#sec:the_plugin_id

**Comment by sakitA** [comment]
Hello, I have the same issue. I am using gradle 8.10 and try to write custom plugin using groovy. I follow the documentation and put all my gradle files under `myproject.plugins`. When I try to build it fail and gave 
```
Execution failed for task ':extractPluginRequests'.
> Script '<path>/buildSrc/src/main/groovy/myproject/plugins/myproject-settings.gradle' should not contain a package statement.
```

**Comment by ljacomet** [comment]
Re-opening.

We should:
* Clarify that Groovy pre-compiled script plugins _cannot have packages_
* Or make it supported

The changes done [here](https://github.com/gradle/gradle/commit/44e5f8931542c3b9472fbb3d2d39a0160e1debae) unfortunately use in-line scripts, meaning they are not tested and not guaranteed to work.

@lkasso Could you please try moving those to tested snippets and if they fail, send this back to triage?

**Comment by AngerWind** [comment]
Hello, I have the same issue. I am using gradle 8.10 and try to write custom plugin using groovy.
I created a groovy file `buildSrc/main/groovy/my/GreetingPlugin.gradle` and i also add this statement `id 'groovy-gradle-plugin'` to `buildSrc/build.gradle`

when i use this statement `id('my.GreetingPlugin')` in `${rootProject}/build.gradle` to apply this plugin, I try to build it fail and gave
> Plugin [id: 'my.GreetingPlugin'] was not found in any of the following sources

and when i add `package my` to this plugin GreetingPlugin, it gave
> Script 'C:\Users\Administrator\Desktop\demo1\buildSrc\src\main\groovy\my\GreetingPlugin.gradle' should not contain a package statement.

i can only use `id('GreetingPlugin')` to apply this plugin

**Comment by lkasso** [comment]
@AngerWind, Groovy pre-compiled script plugins cannot have packages. I am updating the documentation accordingly.

**Comment by MGaetan89** [comment]
Shouldn't this be in the 8.11 RC1 milestone, with #30591 being merged there?
