### ISSUE TITLE
Deduplicate artifacts in ArtifactCollection

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#2889]
Gradle version: 4.1

Have the following build.gradle and libs/obj-0.2.1.jar in the the project directory:
```
repositories { flatDir { dirs './libs' } }

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile (name: 'obj-0.2.1', ext: 'jar')
}
configurations.getByName('compile').getIncoming().getArtifacts().each { println it }
```

This will print obj-0.2.1.jar twice, although it refers to the same file. It would be great if the returned `ArtifactCollection` would remove the duplicates, as it already can tell there are 2 artifacts that point to the same file.

**Comment by oehme** [comment]
@gavra0 could you give us some more info how this is impacting you?

**Comment by gavra0** [comment]
This has a nasty side-effect that if your dependencies are like the ones I've described, we will dex the same jar twice, and dex merging will fail because of duplicate classes.

We use internally use `ArtifactCollection.getArtifacts()` because we need to track where the dependency is coming from (local/external jar, project dependency). Typically we would iterate over the set, and add do some processing of each `ResolvedArtifactResult`.

**Comment by oehme** [comment]
Thanks for the info. Is this blocking you or do you have a workaround?

**Comment by gavra0** [comment]
At the moment, we advise against using fileTree to specify dependencies. Plan is not to hold the stable release for this, but it would be great to have this for the plugin 3.1 :)

**Comment by oehme** [comment]
Could you keep a set of "seen" files to work around this?

**Comment by gavra0** [comment]
At this point for 3.0 it might be a bit too late for that change, and so far, there was a single bug report hitting this issue. However, we will consider doing that for 3.1 in case this does not get fixed by then.
