### ISSUE TITLE
Parallelize download of dependencies

### ISSUE THREAD

**Issue by LouisCAD** [gradle/gradle#28893]
### Expected Behavior

All dependencies are downloaded in parallel, as much as my connection can handle (possibly with a way to define a cap at maximum parallel connections for when using a constrained connection).

They are all available within a few seconds thanks to my 1GBps optic fiber connection, or in a few seconds thanks to LTE/5G, whatever.

### Current Behavior (optional)

All dependencies are downloaded sequentially, wasting developer time, and CI time.

### Context

I was updating a bunch of dependencies, and Gradle sync took more than 2 minutes, on a powerful computer, with a powerful connection.

<img width="741" alt="Screenshot 2024-04-20 at 02 21 46" src="https://github.com/gradle/gradle/assets/6975237/5ed845dd-99ac-45b5-a9cc-259ab991bf9b">

That's barely 1MB/s, or 8Mbps, when my connection could do hundreds of time more! Optic fibers and Maven repos can handle parallel connections! 469 requests is very little per today standards.

I think we can do better in 2024 :)

We have coroutines in Kotlin, we have async APIs, we have project Loom in Java, with have 10 CPU cores in many laptops, we have high bandwidth, SSDs…
Those can handle Billions of things every second if used right.

That's all I had to say.
Thank you and have a great day!
Belle journée :)

Louis CAD

**Comment by ov7a** [comment]
We have many layers of parallelism around dependency resolution. One current limitation is the configuration phase, where we resolve configurations one by one with a parallelism for downloads.
This will be addressed by [Isolated Projects](https://github.com/gradle/build-tool-roadmap/issues/43).

Can you provide a small reproducer with a build scan that showcases your scenario/build setup, please?

**Comment by jvandort** [comment]
See https://github.com/gradle/gradle/issues/27731
