### ISSUE TITLE
Users can apply script hosted on HTTP server using query parameters

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#2891]
Some HTTP server depends on the query parameter values to serve the right file.

### Expected Behavior
`apply from: 'http://localhost/some/path/file.gradle?h=some;query=value'` call to the `localhost` server with the path `some/path/file.gradle` as well as with the query parameters `h=some;query=value`.

### Current Behavior
The applying URI is model inside `ExternalResourceName` which drop the query parameters. When reconstructing the URI the query parameters aren't part of the requesting URI anymore.

### Steps to Reproduce (for bugs)
An integration test will follow soon.

**Comment by lacasseio** [comment]
Branch [dl/apply-from-with-query-string](https://github.com/gradle/gradle/tree/dl/apply-from-with-query-string) contains an integration test exposing the issue.

**Comment by lacasseio** [comment]
The integration test is now in master: https://github.com/gradle/gradle/commit/9bc33a9fd10a2d1aae16ac7b13b0b62370d51da2

**Comment by bmuschko** [comment]
I discussed this with @big-guy. He will identify whether it is a blocker for 4.2 and a implement a potential fix if it is cheap to do.

**Comment by oehme** [comment]
Fixed by fa5740022c9c2e5c4f67fbc193ad8f8c60e9c5c2

**Comment by oehme** [comment]
This has been merged
