### ISSUE TITLE
Intermittent failure to move temporary workspace to immutable location in Gradle 8.7 on Windows

### ISSUE THREAD

**Issue by tridium-gward** [gradle/gradle#28948]
### Current Behavior

When running builds with Gradle 8.7 on Windows 10, Server 2016, or Server 2019, the build intermittently fails with errors like:

```
A problem occurred configuring project ':<project>'.
> Could not move temporary workspace (C:\Users\<USER>\.gradle\caches\8.7\kotlin-dsl\scripts\0c4143977b99a09c5d42cf0d54e8e42e-50dee5f7-8c3b-40bd-93ae-4ac109ca08ba) to immutable location (C:\Users\<USER>\.gradle\caches\8.7\kotlin-dsl\scripts\0c4143977b99a09c5d42cf0d54e8e42e)
```

With a full stacktrace the ultimate error seems to be:
```
Caused by: java.nio.file.AccessDeniedException: C:\Users\<USER>\.gradle\caches\8.7\kotlin-dsl\scripts\0c4143977b99a09c5d42cf0d54e8e42e-50dee5f7-8c3b-40bd-93ae-4ac109ca08ba -> C:\Users\<USER>\.gradle\caches\8.7\kotlin-dsl\scripts\0c4143977b99a09c5d42cf0d54e8e42e
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.lambda$moveAtomically$12(DefaultFileSystemAccess.java:224)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.write(DefaultFileSystemAccess.java:212)
        at org.gradle.internal.vfs.impl.DefaultFileSystemAccess.moveAtomically(DefaultFileSystemAccess.java:223)
        at org.gradle.internal.execution.steps.AssignImmutableWorkspaceStep$WorkspaceMoveHandler.executeMoveOr(AssignImmutableWorkspaceStep.java:273)
        ... 194 more
```

I've attached the full stacktrace as [gradleerror.txt](https://github.com/gradle/gradle/files/15094074/gradleerror.txt)

### Expected Behavior

Builds should succeed.

### Context (optional)

It seems likely this is caused by antivirus scanning as per [this comment](https://github.com/gradle/gradle/issues/28475#issuecomment-2019920357) but I have no ability to exclude the Gradle directory from AV scanning (and certainly can't on our CI servers). This did not happen with Gradle 8.5 but happens occasionally with Gradle 8.7 when compiling build scripts -- sometimes it's worse than others.

### Steps to Reproduce

This is probably hard to reproduce without specific AV settings (we have Windows Defender with all knobs cranked to 11 as near as I can work out), but it's happened on CI while running a TestKit test with an empty `build.gradle.kts` and a very simple `settings.gradle.kts`:

```
import com.tridium.gradle.plugins.tridium.convention.settings.*

plugins {
  id("com.tridium.convention.settings.gradle-configuration") apply false
}

gradle.disallowSetting("org.gradle.configureondemand")
```

Where `disallowSetting` just throws if `startParameter.isConfigureOnDemand` is true.

### Gradle version

8.7

### Your Environment (optional)

Windows 10, Windows Server 2016, Windows Server 2019

**Comment by ov7a** [comment]
@tridium-gward can you provide some system and/or Windows Defender info on why the access was denied?

Can you confirm that it only occurs when the anti-virus is on? 
If that's the case, not much can be done from the Gradle side.

**Comment by tridium-gward** [comment]
I do not have the ability to turn off Defender, nor can I access its logs. 

Note that this is a regression from 8.5. I suppose we will have to stay on 8.5 for the foreseeable future if this is not something that can be fixed.

**Comment by ov7a** [comment]
Sorry, I don't think this issue is actionable without additional information.

If the security prevents Gradle from copying files, there is little we can do.

Closing this for now.
