### ISSUE TITLE
Support downloading gradle-x.x-bin.zip file via multi-thread

### ISSUE THREAD

**Issue by danielsun1106** [gradle/gradle#2895]
Downloading gradle-x.x-bin.zip is quite slow, how about improving via multi-thread?

### Expected Behavior
Downloading gradle-x.x-bin.zip file via multi-thread

### Current Behavior
Downloading gradle-x.x-bin.zip file via single-thread
```
Downloading https://services.gradle.org/distributions/gradle-4.2-rc-1-bin.zip
........................
```

### Context
download gradle-x.x-bin.zip via download tools(e.g. Thunder) by myself and place the zip file to some directory like `C:\Users\Daniel\.gradle\wrapper\dists\gradle-4.2-rc-1-bin\1ijimgwwfusqxjakf4cfx6o82`

### Steps to Reproduce (for bugs)
1. Bump the version of gradle
2. Run `gradlew clean`, which will download the new gradle

### Your Environment
Windows 10, Java 8, Gradle 4.1

**Comment by blindpirate** [comment]
Given that you're in China, I think, on Gradle side, the correct way to solve this problem is improving CDN.

**Comment by blindpirate** [comment]
@danielsun1106 We've enabled CDN in China mainland. Please try downloading without any proxy.

**Comment by ldaley** [comment]
@blindpirate it's not enabled for the default address. I will roll that out later this week.

**Comment by blindpirate** [comment]
@ldaley sorry. Looking forward to it!

**Comment by danielsun1106** [comment]
Great! I will have a try 😉
