### ISSUE TITLE
Improve markdown rendering support

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#2896]
In https://github.com/gradle/gradle/commit/73d54c86eca92ae26decccd774f49bfc2b01c314 we can see our markdown render can't process `**1.1.4-3**` correctly and we have to use `<b>1.1.4-3</b>` as a workaround. Since `pegdown` is deprecated, we should use something else instead.

**Comment by bmuschko** [comment]
I think we should fully move to AsciiDoc. We already do that for the user guide. There's no good reason to stick with Markdown for the release notes.

**Comment by blindpirate** [comment]
That would be excellent.
