### ISSUE TITLE
Ensure vanilla Java applications produced by `gradle init` work with Isolated Projects out of the box

### ISSUE THREAD

**Issue by 6hundreds** [gradle/gradle#28965]
As of Gradle 8.5 they fail with:
```
* What went wrong:
Cannot query the value of property 'buildFlowServiceProperty' because it has no value available.
```

Issue for the KGP: https://youtrack.jetbrains.com/issue/KT-63990

**Comment by 6hundreds** [comment]
@bamboo `gradle init` generates project with `kotlin-gradle-plugin = "1.9.22"`, so it fixed, just checked. 
At the same time, we could have integTests for that `configuration-cache` project - like a run `gradle init` with a set of options and run `help` with IP enabled. WDYT?

**Comment by bamboo** [comment]
@6hundreds Yes, we should have integ tests for `gradle init` compatibility with Isolated Projects but I think they should be together with the `gradle init` implementation, not with the `configuration-cache` implementation.

**Comment by 6hundreds** [comment]
@bamboo We have IP-specific tests for, say, JavaPlugin in CC project, and some other things. Placing that tests to another project will make us to expose test fixtures.

Also, doesn't this tests has to be in `smoke-ide-tests`? Since it will exercise a sync process

**Comment by 6hundreds** [comment]
Fixed via [#29254](https://github.com/gradle/gradle/pull/29254)

**Comment by 6hundreds** [comment]
Confirmed that introducing IP violation in project structure is being catched by tests in `:build-init`

**Comment by bamboo** [comment]
Great!
