### ISSUE TITLE
If dependency project has no variants, mention that there are none

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#28970]
### Current Behavior

Currently I'm finding that if I declare a dependency (with attributes) on a project that declares no variants, then the error message from Gradle says:

```
> Could not resolve all task dependencies for configuration ':subproject2:conf'.
   > Could not resolve project :subproject1.
     Required by:
         project :subproject2
      > No matching variant of project :subproject1 was found. The consumer was configured to find attribute 'attrA' with value 'value1' but:
          - None of the variants have attributes.
```

rather than saying something more like:

```
No variants were found.
```

### Expected Behavior

It would be nice if Gradle would mention that no variants were found rather than saying that every variant had no attributes

### Steps to Reproduce

See https://github.com/mathjeff/gradle-samples-2/tree/main/resolve-attributes-with-no-variants

### Gradle version

8.7

**Comment by mathjeff** [comment]
Also somewhat related to https://github.com/gradle/gradle/issues/12126

**Comment by ov7a** [comment]
Thank you for providing a PR with a fix! The responsible team will review it.
