### ISSUE TITLE
cordova build errors

### ISSUE THREAD

**Issue by mpetranech** [gradle/gradle#2897]
I'm trying to run the "cordova build" command, but it errors out on me.
Here are the errors and other info:

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/
3.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

I'm running Windows 7

Gradle Version
C:\Android\ALLApps\One\hithere>gradle -v
------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------
"""Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2
Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 201
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 7 6.1 x86
+++++++++++++++++++++++++++++++++++++++++++++++++++++
------------------------------------------------------------
C:\Android\ALLApps\One\hithere>java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode, sharing)
------------------------------------------------------------
********************************************************************
C:\Android\ALLApps\One\hithere>cordova build
ANDROID_HOME=C:\Users\Administrator\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_144
Subproject Path: CordovaLib
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/
3.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

**Comment by blindpirate** [comment]
> Could not reserve enough space for 2097152KB object heap

Looks like you set jvm args somewhere with 20GB heap memory request, that is huge! Try to decrease that with [docs here](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties).

**Comment by mpetranech** [comment]
I'll try and thanks. You are great!
Mike

**Comment by CONSTRUCTPRO** [comment]
> Looks like you set jvm args somewhere with 20GB heap memory request, that is huge! Try to decrease that with [docs here](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties).

Many thanks!!! ,This solved building my project error
