### ISSUE TITLE
Add C++20 modules support 

### ISSUE THREAD

**Issue by kelteseth** [gradle/gradle#29009]
### Expected Behavior

Modules are part of C++20 and should greatly decrease compile times, see https://en.cppreference.com/w/cpp/language/modules

### Context

Hi,
I'm not a user of gradle, but I'm tracking the progress of c++20 modules support on https://arewemodulesyet.org/tools/#build-tools and this is the issue we are linking to in our table of c++20 modules support.
Cheers 👋
Eli

**Comment by ljacomet** [comment]
Can you explain how Gralde would benefit from C++ modules?

**Comment by MikailBag** [comment]
(Disclaimer: I don't use gradle for building C++ code)

Modules are a new (well, C++20) feature which significantly changes the way C++ code is built. I don't think I can all the details in this message. As for the benefits, modules should improve build efficiency.

Before modules
```
// a.cpp
#include "lib.h" // recursively read all headers and parse declarations

// b.cpp
#include "lib.h" // one more time recursively read all headers and parse declarations
...
```

With modules
```
// a.cpp
import lib; // cheaper operation which opens binary file with all available declarations, optimized for lookup accesses

// b.cpp
import lib; // same
```

In other words, compiler no longer needs to parse header file N times (where N is count of translation units which directly or indirectly include that header). Each dependency is built only once.

Additionally, modules bring many simplifications (e.g. you can't use `using namespace ...` in header as it will "leak" into lexically next headers and user code; with modules `using` declarations are harmless).

**Comment by mikomikotaishi** [comment]
Is there still any interest/development in C++ build system support in Gradle, or is the attention primarily on JVM languages?

**Comment by angebrajuka** [comment]
Hi there, I use gradle for c++ compilation.

Another benefit of modules (the main benefit in my opinion) is that it greatly reduces and simplifies the amount of code that needs to be written. I use c++ with gradle and header + source files are just so archaic at this point. I could care less about compile times, but having to write basically all the same functions except without function bodies in a header file is just so goofy.
