### ISSUE TITLE
Android Studio project import performance regression in 8.7

### ISSUE THREAD

**Issue by akerimsenol** [gradle/gradle#29026]
### Current Behavior

There seems to be a performance regression in 8.7 in project import.

Our 2000 sub-project benchmark for Android Studio import takes significantly more time when model building with Gradle 8.7

![image](https://github.com/gradle/gradle/assets/117925183/065a4b4d-cbe7-44eb-9a3c-5a83d7e58f06)

Zip file containing jfr snapshots (Java Flight Recorder) captured with IntelliJ ultimate: [projectImport-8.6vs8.7.zip](https://github.com/gradle/gradle/files/15202002/projectImport-8.6vs8.7.zip)

My guess after inspecting the flame graphs is from the jfrs above is:
This is due to `projectObserved` callbacks, which seems to be recently introduced, see image below for a comparison
![image](https://github.com/gradle/gradle/assets/117925183/f0857267-ba80-4441-806d-11245dcca317)

### Expected Behavior

See image above for before/after values.

### Steps to Reproduce

1. Clone the benchmark project. `git clone https://github.com/gavra0/android-extra-large-benchmark -b 2022.9`
2. Optional but recommended, set up the 2000 module subset (i.e. `./apply_diff.sh app`):  https://github.com/gavra0/android-extra-large-benchmark/tree/2022.9?tab=readme-ov-file#working-with-smaller-subsets
3. Open Android Studio and import the project
4. You can observe the Gradle portion of the project import is significantly slower for  8.7 and 8.8-RC1 compared to 8.6

### Gradle version

8.7 and 8.8-RC-1

### Gradle version that used to work

8.6

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by jvandort** [comment]
How confident are you that `projectObserved` is the culprit here? This callback existed in 8.6, except with a different name (`dependencyObserved`) and called from another place. Previously, it was called by `org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.markReferencedProjectConfigurationsObserved`. Looking at your JFR traces, it seems both 8.6 and 8.7 call the function roughly the same number of times.

**Comment by akerimsenol** [comment]
I'm not confident at all  given that I'm not that familiar with the internal workings of Gradle. It's just what I saw in the relevant flame graphs. 

Although, I do see you created a commit for this already, so I guess you are a bit more confident as per your EDIT in the last comment. 

Did you confirm the commit actually improves performance? I'm willing to give it a go with my own setup if you have a build that I can try.

**Comment by akerimsenol** [comment]
I spent a bit of time profiling model building and I noticed this is mostly due to projectObserved calls waiting for locks in DefaultListenerManager, not the projectObserved call itself. 

I built a local version of Gradle with projectObserved call commented out and the dependency graph building times drastically improves from ~40s to ~25s  in our 2000 module benchmark.

**Comment by akerimsenol** [comment]
[projectObservedYourKitProfile.zip](https://github.com/user-attachments/files/16331113/projectObservedYourKitProfile.zip)
Here is a YourKit profile captured that's showing the issue. It's more detailed than the initial report and is clearly showing the issue is within DefaultListenerManager (as I wasn't able to use YourKit back then due to a bug)

**Comment by cobexer** [comment]
@akerimsenol the fix for this issue is included in the latest nightly build `8.10-20240801011711+0000` available from https://gradle.org/release-nightly/ could you give it a spin and report your findings here?

**Comment by akerimsenol** [comment]
I just tested with latest nightly 8.10-20240801011711+0000 and it seems to be good. Although to make it'd be good to merge the RC in our benchmarks and collect data from our infra with the same setup.

**Comment by joshfriend** [comment]
I also benchmarked `8.10-20240801011711` with gradle-profiler (with android studio koala feature drop beta2). I did not really notice an improvement, and in some cases it was slower:
![image](https://github.com/user-attachments/assets/2deec3a8-720b-4e32-b4c8-a6914ab81200)

**Comment by jvandort** [comment]
Are you sure your performance issue was caused by this? 

Are you able to capture flamegraphs from before and afte? Otherwise, we can't really say if this performance issue is related to yours

**Comment by joshfriend** [comment]
Captured these jfrs, the noticeable difference to me is that in 8.10 spends a chunk of time in `DefaultWorkerLeaseService.whileDisallowingProjectLockChanges` that I don't see in 8.6. I see approximately 10% regression in the Gradle portion of sync between 8.6 and 8.10 snapshots.

[sync-8.6.jfr.zip](https://github.com/user-attachments/files/16514491/sync-8.6.jfr.zip)
[sync-8.10-20240801011711+0000.jfr.zip](https://github.com/user-attachments/files/16514493/sync-8.10-20240801011711%2B0000.jfr.zip)

**Comment by akerimsenol** [comment]
I think Josh is right, I just double checked on my side and the regression doesn't seem to be gone with 8.10-RC1. 

I must have made a mistake when testing the nightly.

**Comment by akerimsenol** [comment]
One more correction, I was testing with 1000 module benchmark which is apparently relatively unaffected by this issue anyway so my last comment is also invalid. Sorry for the noise. 
Here I have a comparison between our latest runs on 8.9 and 8.10-RC1, with the 2000 module benchmark, the median values have changed as below:

Configuration:
**8.9** -> 65 seconds
**8.10-rc1** -> 68 seconds

Android model building **(which is the phase affected by this issue)**
**8.9** -> 66 seconds
**8.10-rc1** -> 49 seconds

Total daemon time during import:
**8.9** -> 156 second
**8.10-rc1** -> 143 seconds

I think then Josh is seeing a separate issue.
