### ISSUE TITLE
Path too long for default W10 backups

### ISSUE THREAD

**Issue by Visca87** [gradle/gradle#29023]
### Issue type

Polishing

### Problem description

I just installed a new Windows 10 with some tools, among them visual studio code and android studio, one of which likely installed Gradle without me noticing. 

I also activated the in-built backup system of W10 that uses the "File History" method (something granted by the usage of NTFS filesystem). This has a limit of 185 characters filenames (including the path). The backup system spewed hundreds of errors all related to Gradle due to this reason.

This is one of the hundreds of problematic files: `C:\Users\USERNAME\.gradle\caches\transforms-3\82188b1b3f1b5ffbea4c8cb0d9d036b8\transformed\unzipped-distribution\gradle-8.4\build-logic\binary-compatibility\src\main\groovy\gradlebuild\binarycompatibility\rules\SinceAnnotationMissingRuleCurrentGradleVersionSetup.java`

It's 268 characters long, out of 185.

I'm not moving or reinstalling Gradle because frankly I would provably mess with something else. If anything ever happens I'd just deal with it. I just wanted to give you the heads up that your program is likely not being able to be backup in systems without specific solutions that don't rely in "File History".

Also, hundreds of red "X" in the event viewer looks threatening (it shows 1020 errors for me). If I didn't know my installation was squeaky clean and I just manually activated the backups, I'd provably had assumed a virus corrupted everything.

**Comment by ljacomet** [comment]
Are you able to exclude elements from the backup?
As indicated early on in the path, those are `caches` and are not worth backing up.

**Comment by Visca87** [comment]
Yes, you can exclude folders.

**Comment by ljacomet** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

The names and paths of these files in Gradle will remain unchanged. Unless there is a way to mark directories to be excluded from backups, no changes will happen

Note that Gradle already does that with `CACHEDIR.TAG`:
* #20209
