### ISSUE TITLE
Allow for configuring `javac --release` in `JavaPluginExtension`

### ISSUE THREAD

**Issue by bartekpacia** [gradle/gradle#29035]
### Expected Behavior

I'd like to be able to configure `javac --release` in `JavaPluginExtension`:

```kotlin
java {
    release = JavaVersion.VERSION_21
}
```

### Current Behavior (optional)

`javac --release` can only be specified in the `JavaCompile` task:

```kotlin
tasks.named<JavaCompile>("compileJava") {
    options.release = JavaVersion.VERSION_21
}
```

### Context

I just learned about `javac --release` as a replacement for `javac -bootclasspath <...> -source <...> -target <...>`

**Comment by ljacomet** [comment]
This issue will be closed as a duplicate of

* #18530 

***

As you can see on that other issue, we decided against doing this.
