### ISSUE TITLE
Gradle module metadata spec implies non-relative URLs for files are valid, but they are not

### ISSUE THREAD

**Issue by lukebemish** [gradle/gradle#29033]
### Current Behavior

In the [gradle module metadata spec](https://github.com/gradle/gradle/blob/master/platforms/documentation/docs/src/docs/design/gradle-module-metadata-latest-specification.md), under the section for the `files` value, it states:
> `url`: The location of the file. A string. In version 1.0, this must be a path relative to the module.

Which implies that as of 1.1 non-relative URLs would work; however, gradle fails to resolve non-relative URLs for files of a variant.

### Expected Behavior

The spec should clarify what is or is not supported; perhaps the "in version 1.0" language could be dropped throughout.

### Steps to Reproduce

Create otherwise-valid gradle module metadata that specifies a non-relative URL; an example would be https://gist.github.com/lukebemish/5b2a9ad7671026d538c06296ac43719b. An attempt to depend on it results in gradle searching for the global URL as a relative path to available repositories.

### Gradle version

8.7

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

You are right, the language is confusing. For all released versions, the path must be relative.
