### ISSUE TITLE
Deprecate extending a configuration from another project

### ISSUE THREAD

**Issue by windmueller** [gradle/gradle#29040]
### Current Behavior

When creating a new configuration in a project `consumer` extending another configuration from a different project `lib` like

```
val conf: Configuration by configurations.creating {
    extendsFrom(project(":lib").configurations.implementation.get())
}
```

the resulting configuration uses only dependencies of `consumer` but none of `lib`.

### Expected Behavior

The configuration should include all dependencies of the `implementation` configuration of the specified project.

### Context (optional)

I am trying to merge runtime classpaths of multiple subprojects and Gradle should take care of resolving the "correct" versions, i.e., removing duplicates and outdated versions.

### Steps to Reproduce

A small demo project based on "gradle init": https://github.com/windmueller/gradle-configuration-issue

### Gradle version

8.7

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

I don't think Gradle supports this nor that it should. But in that case, this invocation should result in an error.

**Comment by windmueller** [comment]
> I don't think Gradle supports this nor that it should. But in that case, this invocation should result in an error.

If this is the case, what would be an acceptable approach for combining classloaders of different projects?

**Comment by big-guy** [comment]
```
val conf: Configuration by configurations.creating {
    extendsFrom(project(":lib").configurations.implementation.get())
}
```
We should make this an error.  This won't work and should not work because it's reaching across project boundaries.  We already warn/fail when a configuration is explicitly resolved across project boundaries. 

A configuration in one project should not extend a configuration in another project.

**Comment by windmueller** [comment]
> A configuration in one project should not extend a configuration in another project.

So is there another way to combine classloaders of different projects that I am not aware of?

**Comment by windmueller** [comment]
> @windmueller Have you tried using `shouldResolveConsistentlyWith`? See https://docs.gradle.org/current/userguide/resolution_strategy_tuning.html#resolution_consistency

I tried it with

```
project(":first").configurations.runtimeClasspath.get()
    .shouldResolveConsistentlyWith(project(":second").configurations.runtimeClasspath.get())
```

but when I resolve the classpath I still get different versions of the dependencies.
