### ISSUE TITLE
Cancelling a build can lead to corrupt build cache entries

### ISSUE THREAD

**Issue by dnl50** [gradle/gradle#29043]
### Current Behavior

When cancelling a Gradle Build while compiling Java sources, invalid local build cache entries can be generated. These cache entries do not contain any class files, but are still written to the local build cache. The next time the `compileJava` task is executed, the task is marked as `UP-TO-DATE` and the local build cache entry is used to build the corresponding JAR. When another project is compiled which has a project dependency on the project with the invalid local build cache entry, the Java compiler fails with `cannot find symbol` errors.

After deleting the local build cache and excuting the `clean` task, the project can be built as usual.

### Expected Behavior

Build cache entries should not be persisted after the build is canceled.

### Context (optional)

I think the problem began appearing after we upgraded our project to from Gradle 7.4.2 to Gradle 8.5. I don't recall anyone in our team mentioning this issue prior to the upgrade. Our gradle project has 378 subprojects which are built in parallel with local and remote build caching enabled.

### Steps to Reproduce

Can be reproduced in the Gradle project itself. I checked out git tag `v8.7.0` and opened the project in IntelliJ IDEA 2024.1 Ultimate Edition. After importing the project, I executed the `compileJava` task to check whether the task can be executed after the initial import, which worked just fine. I then deleted the local build cache files unter `%USERPROFILE%\.gradle\caches\build-cache-1` and executed the `clean` task.

I then executed the `compileJava` task again, but canceled the build after about 10 seconds. I reran the `compileJava` task immediately after that and `javac` printed many `cannot find symbol` errors:

```
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\impl\AbstractZipEntry.java:21: error: package org.gradle.internal.io does not exist
import org.gradle.internal.io.IoFunction;
                             ^
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\ZipEntry.java:19: error: package org.gradle.internal.io does not exist
import org.gradle.internal.io.IoFunction;
                             ^
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\ZipEntry.java:62: error: cannot find symbol
    <T> T withInputStream(IoFunction<InputStream, T> action) throws IOException;
                          ^
  symbol:   class IoFunction
  location: interface ZipEntry
C:\dev\gradle\platforms\core-runtime\files\src\main\java\org\gradle\api\internal\file\archive\impl\FileZipInput.java:23: error: package org.gradle.internal.io does not exist
import org.gradle.internal.io.IoFunction;
```

### Gradle version

8.5.0/8.7.0

### Your Environment (optional)

* I limited my gradle worker count to a maximum of 6 workers using the `org.gradle.workers.max` property in the `gradle.properties` file in my Gradle home directory
* Oracle JDK 11.0.19
* IntelliJ IDEA 2024.1 Ultimate Edition (the issue can also be reproduced using the command line though)
* Develocity 2024.1 with Develocity Gradle Plugin 3.17.1

**Comment by dnl50** [comment]
At first glance, the java compiler forking seems to be related to the issue. When enabling forking for every `JavaCompile` task, I managed to reproduce the issue with a long running annotation processor. The Gradle worker spawned for compiling is not terminated properly and keeps running in the background even after terminating the build. With a random sequence of running the `compileJava` task and termininating the build after a few seconds I managed to reproduce the issue.

**Comment by dnl50** [comment]
I managed to reproduce the issue using this simple reproducer project: https://github.com/dnl50/corrupt-build-cache. 

The `:producer` project generates 15.000 java source files, which are then compiled. The `:consumer` project has a project depencency on the `:producer` and uses the generated classes.

I executed the following steps:

1. clear the local build cache
2. stop all gradle daemons
3. start a new daemon by excuting the `clean` task ([Build Scan](https://scans.gradle.com/s/tsvg47aoc3nxw))
4. execute the `compileJava` task and stop it after the actual compilation began ([Build Scan](https://scans.gradle.com/s/22aupp3crsyu4))
5. execute the `compileJava` task immediately afterwards ([Build Scan](https://scans.gradle.com/s/4k6qybbwuvqxa))
6. wait until the CPU usage of the Gradle worker JVM goes back to idle
7. execute the `clean` task to make sure the result from the local build cache is used ([Build Scan](https://scans.gradle.com/s/tts7fd5cng64g))
8. execute the `compileJava` task again ([Build Scan](https://scans.gradle.com/s/ovurlz3bkrpcq))

**Comment by dnl50** [comment]
I managed to reproduce the behaviour with a reproducer: https://github.com/dnl50/corrupt-build-cache

Steps to reproduce:

1. clear local build cache and stop all daemons
2. start a new daemon (I used the `clean` task): [Build Scan](https://scans.gradle.com/s/cflfnfx2qzcbk)
3. run the `compileJava` task and cancel the build after 20 seconds: [Build Scan](https://scans.gradle.com/s/4p75xzmjb2tf2)
4. wait for the daemon JVM in the background to return to idle CPU load
5. rerun the `compileJava` task. This build succeeds, but no local build cache entry for the javac output is generated for some reason: [Build Scan](https://scans.gradle.com/s/abaeivs7pqdrc)
6. execute the `clean` task: [Build Scan](https://scans.gradle.com/s/64yg2tlib55sq)
7. execute the `compileJava` task again. Now the build is failing and a corrupt build cache entry for the task output of the `compileJava` task is generated without any class files: [Build Scan](https://scans.gradle.com/s/2e3lhm7kfem7q)
8. execute another `clean`: [Build Scan](https://scans.gradle.com/s/h4th3bsdfqbhg)
9. execute `compileJava` again. Now the `compileJava` task is taken from cache, but since the there are no class files in the cached result, the resulting JAR is empty and the compilation of the `:consumer` project fails: [Build Scan](https://scans.gradle.com/s/6ka4prt2rdjuy)

I also managed to get a corrupt build cache entry on step 5, but that only occured twice in about 10 tries.

**Comment by asodja** [comment]
I investigated the issue and this is a problem with persistent workers: if you interrupt the build while compile worker is running, then the result of compilation is never read from the worker. So on the next run Gradle can get the result of previous compilation. 

A fix requires an improvement to daemon<->worker protocol.

**Comment by Vampire** [comment]
Does anyone know, whether the fix for this also affects Kotlin compilation?
I had the exact same situation described here with a Kotlin project (with Kotlin 1.8.22 and Gradle 7.6.4).
But I was not able to reproduce using the reproducer provided here morphed to Kotlin.
