### ISSUE TITLE
add automatic detection for modules containing `build.gradle.kts`

### ISSUE THREAD

**Issue by elect86** [gradle/gradle#29052]
### Expected Behavior

I find myself often implement some logic to add several modules, sometimes only at top level, sometimes recursively

I'd like to have something like this

```
// settings.gradle.kts

includeByBuildScript(recursive = true)
```

Where Gradle will automatically search for all the directories containing `build.gradle.kts` and add them as modules

**Comment by ljacomet** [comment]
Possibly related:
* #15807

**Comment by mlopatkin** [comment]
>having that capability could make sense for some setups.

@ljacomet, do you think there are use cases where it cannot be implemented as a settings plugin?

**Comment by ljacomet** [comment]
That's a good point.
* If we cover including projects, there is no reason why a plugin cannot take care of it.
* If we expand to cover included builds - which is not part of the request here - the only limitations would be for build logic providing included builds.

So given the above, recommending a plugin approach seems right.

**Comment by mlopatkin** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

Given that the feature is easy to be implemented as a plugin, we do not plan to add it to the Gradle's core for now.

**Comment by elect86** [comment]
I'm planning to write a plugin for that
