### ISSUE TITLE
gradlew can't be runned on bash in windows subsystem for linux (WSL)

### ISSUE THREAD

**Issue by ylemoigne** [gradle/gradle#2906]
### Expected Behavior
When running `./gradlew tasks` in a project dir, under the ubuntu bash shell in windows subsystem for linux, I expect it to run the task.

### Current Behavior
```
ylm@wsl:~/myproject$ ./gradlew tasks
./gradlew: line 2: $'\r': command not found
./gradlew: line 8: $'\r': command not found
./gradlew: line 11: $'\r': command not found
./gradlew: line 14: $'\r': command not found
./gradlew: line 17: $'\r': command not found
./gradlew: line 18: syntax error near unexpected token `$'{\r''
'/gradlew: line 18: `warn ( ) {
ylm@wsl:~/myproject$ ./gradlew.bat tasks
./gradlew.bat: line 1: @if: command not found
./gradlew.bat: line 2: @rem: command not found
./gradlew.bat: line 3: $'@rem\r': command not found
./gradlew.bat: line 4: @rem: command not found
./gradlew.bat: line 5: $'@rem\r': command not found
./gradlew.bat: line 6: @rem: command not found
./gradlew.bat: line 7: $'\r': command not found
./gradlew.bat: line 8: @rem: command not found
./gradlew.bat: line 88: unexpected EOF while looking for matching `"'
./gradlew.bat: line 91: syntax error: unexpected end of file
ylm@wsl:~/myproject$
```

### Context
ubuntu bash shell in windows subsystem

### Steps to Reproduce (for bugs)
Install windows creator fall update through insider program
Install windows subsystem for linux
Install ubuntu bash shell through windows store.
cd in a project directory
run gradlew

**Comment by ylemoigne** [comment]
Ok, it's not you.... It's git....
When `git` checkout is configured with  `core.autocrlf=true`, it replace gradlew carriage return with CRLF.
Therefore, the script wont run.

**Comment by cybuch** [comment]
You can fix your gradlew file like: https://askubuntu.com/questions/803162/how-to-change-windows-line-ending-to-unix-version
