### ISSUE TITLE
Report JVM information for Gradle daemon

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#29101]
### Expected Behavior

It should be easy to understand which version of Java may be used to run a build.

### Context

`gradle -v` reports the _current_ JVM used.  This is often the same one used by the daemon, but this can be influenced by two different things:
- `org.gradle.java.home` can specify a completely different Java home to be used by the daemon
- Daemon JVM criteria 

Additionally, once the build is started, there is no easy way to see the actual JVM used to run the build.  This is useful for diagnosing problems caused by running a build with the wrong (or unexpected) version of Java.

Some suggestions:
- Make `gradle -v` report the value of `org.gradle.java.home` or the JVM criteria when set.
- Make `gradle buildEnvironment` or similar task report information about the build's actual JVM

**Comment by tcfurrer** [comment]
In case this helps anyone else waiting for this feature, or just stuck on older Gradle releases...
I've had this in my build.gradle for a long time: (this prints the information for every gradle task)

def level = gradle.startParameter.logLevel as String
if (level != 'QUIET') {
    def gradleVersion = project.getGradle().getGradleVersion()
    def gradleGroovyVersion = GroovySystem.getVersion()
    def gradleJavaVersion = Runtime.version().feature() + '.' + Runtime.version().interim() + '.' + Runtime.version().update()

    printf '%9s %-7s %s\n', 'Gradle', gradleVersion, "(running on JDK $gradleJavaVersion with Groovy ${gradleGroovyVersion})"
}

**Comment by octylFractal** [comment]
Spec: https://docs.google.com/document/d/1o5DkBP-hDdN5Vlmdgs6IgNZ-U2y0ffpVL6BlsTobySs/edit?usp=sharing
