### ISSUE TITLE
Support Scoop installed JDK discovery on Windows

### ISSUE THREAD

**Issue by GingerGeek** [gradle/gradle#29121]
### Expected Behavior

Gradle should detect JDKs installed by [Scoop](https://scoop.sh/) ([GitHub](https://github.com/ScoopInstaller/Scoop)).

Scoop is a popular (20k+ stars) installer on Windows for command-line, non MSI installers similar to SDKMAN!, asdf and jabba that are already installed.

Through the [Java bucket](https://github.com/ScoopInstaller/Java) scoop can manage the install of many different JVM versions and distributions

### Current Behavior (optional)

Currently Gradle does not detect the installation location of JDKs installed with scoop, unless invoked or if JAVA_HOME points to one of the installs. Builds may fail if they can't detect correctly installed required JVM versions.

### Context

Scoop installs apps in self-contained folders, generally under `%USERPROFILE%/scoop/apps`

Each combination of JVM version (8, 11, 17, etc) and distribution (Temurin, Corretto) has it's own folder e.g `temurin21-jdk`. 

With each folder there is a symlink of `current` that links to the latest installed version of that JVM within the folder. 

Also see ScoopInstaller/Java#504

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

* Should we add this support?
* Or should Gradle instead offer an SPI allowing users to add their own detection providers? (this is not a request for the attached PR to be modified to do that)

Related:
* #16645

**Comment by GingerGeek** [comment]
Thanks, 

I agree you could quite easily bloat Gradle with detection for every toolchain out there, especially as in order to "fully" support them it becomes quite complex. e.g. with scoop installation directories can be varied and to "fully" resolve the installation locations you would have to read system environment and config files with the same logic as scoop itself.

The other toolchains seem to be done on a "as-default" basis so they just check the default paths... which is the current implementation in the PR

The SPI may be a preferred method but the DX would be a challenge I feel. You wouldn't want to include logic like this in project files with this, but similarly the experience of modifying gradle user settings is not always friendly.

**Comment by big-guy** [comment]
Sorry, we don't want to add more built-in options.

I opened a new issue that describes roughly our approach: https://github.com/gradle/gradle/issues/29508

We want a mechanism so 3rd parties can add support for different package manager options and not require changes to Gradle to support them. Eventually, we would remove the existing options.
