### ISSUE TITLE
Can't enter password to system command in 4.2-RC1

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#2915]
Can't pass a password to a system command in 4.2-RC1. 

### Expected Behavior
Password can be entered. It worked in 4.1 and before.

### Current Behavior
Entered characters are ignored.

### Context
In the specific example below I'm automating adding a private key to the authentication agent using `ssh-add`.

### Steps to Reproduce (for bugs)
- Create the following build script

```
task addPrivateKey(type: Exec) {
    commandLine 'ssh-add'
    args = ['key.pem']
}
```
- Generate a key in the same directory as `build.gradle` file: `openssl genrsa -des3 -out key.pem `
- Enter a password
- Adjust permissions of the key so it can be accepted by `ssh-add`: `chmod 600 key.pem`
- Run `gradle addPrivateKey --no-daemon` (it didn't work with daemon before too)

The password prompt is displayed but the password can't be entered in 4.2-RC1.

### Your Environment
 * Build scan URL: https://e.grdev.net/s/pnxfvvepdoghe

**Comment by bmuschko** [comment]
I am going to start investigating.

**Comment by bmuschko** [comment]
Looks like [this change](https://github.com/gradle/gradle/commit/c59686a1ce8a3d3f7be6896dfba924be83ea6fc1) created the broken behavior and seems to be related to the deployment API. @big-guy is having a deeper look. I believe it's some deeper change in the API. I think the commit mentioned above is only hooking it up.
