### ISSUE TITLE
Android Studio 2.4 Preview 5 April 7, 2017 Not working with radl

### ISSUE THREAD

**Issue by MaxWeichers** [gradle/gradle#29162]
### Current Behavior

Android Studio (2.4 RC0) keeps telling me Error running android: Gradle project sync failed. Please fix your project and try again. How can I find out what the problem is? I will probably just upgrade from .

### Expected Behavior

It should work

### Steps to Reproduce

download 2.4 RCO and run gradle

### Gradle version

1

### Your Environment (optional)

android studio, ubuntu 17.01

**Comment by ljacomet** [comment]
This is an issue with the Android Gradle Plugin, which is developed by Google and cannot be addressed in the Gradle Build Tool project. We also cannot just move the issue.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/docs/setup/contribute/report-bugs#filing-a-bug

If you believe this is not an Android issue, please update with a reproducer that does not involve Android.
