### ISSUE TITLE
Auto detection of installed toolchains For vfox 

### ISSUE THREAD

**Issue by adamglin0** [gradle/gradle#29195]
### Expected Behavior

auto detection  java install dir of vfox.

### Current Behavior (optional)

from this [link of doc](https://docs.gradle.org/current/userguide/toolchains.html), auto detection not support vfox.

### Context

in my option, vfox is more powerful than asdf, so please support vfox

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Same questions and relates to:
* #29121

**Comment by big-guy** [comment]
Sorry, we don't want to add more built-in options.

I opened a new issue that describes roughly our approach: https://github.com/gradle/gradle/issues/29508

We want a mechanism so 3rd parties can add support for different package manager options and not require changes to Gradle to support them. Eventually, we would remove the existing options.
