### ISSUE TITLE
8.8 compatibility issue with JavaVersion, daemon registry and older TAPI clients

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#29209]
### Current Behavior

This was reported as a flaky test failure:
https://ge.gradle.org/s/bgojhf2n4dz7a/tests/task/:kotlin-dsl-tooling-builders:gradle6.9.4CrossVersionTest/details/org.gradle.kotlin.dsl.tooling.builders.r54.KotlinBuildScriptModelCrossVersionSpec/can%20fetch%20buildSrc%20classpath%20in%20face%20of%20buildscript%20exceptions%20TAPI%206.9.4%20-%3E%20Gradle%20current?top-execution=1

### Expected Behavior

This test should not be flaky due to 8.8 changes related to daemon registry.

### Steps to Reproduce

This needs to be reproduced

### Gradle version

8.9 nightly

### Gradle version that used to work

N/A

**Comment by ljacomet** [comment]
Fixed through #29266
