### ISSUE TITLE
Unexpected internal resolution failure with capability conflict handling

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#29208]
### Current Behavior

When resolving a particular configuration with capability conflicts, the build fails with an internal error:

> Execution failed for task ':dependencies'. |  
 > Problems reading data from Binary store in /Users/bene/.gradle/.tmp/gradle14690425166727664849.bin offset 0 exists? true |  

### Expected Behavior

No exception 

### Steps to Reproduce

Bisected to https://github.com/gradle/gradle/commit/cdb7868b553a1feea6e8a6e3edcadd5c44a15ad2 which was introduced in 8.8

### Gradle version

8.8 RC1

### Gradle version that used to work

8.7 

### Build scan URL (optional)

https://scans.gradle.com/s/sfzjpw47aqvda/tests/task/:test/details/org.gradlex.jvm.dependency.conflict.samples.SamplesTest/sample-all_build.sample?top-execution=1

**Comment by ljacomet** [comment]
We discussed this, and I will revert the fix done in #28218 because while it fixes some broken builds, it also breaks working ones.
Capability conflict handling needs a complete solution to become more reliable.
We will start working on this right now for an upcoming release.

**Comment by ljacomet** [comment]
"Fixed" with #29249
