### ISSUE TITLE
JacocoTestReport task dependent on compile not test

### ISSUE THREAD

**Issue by bendavidpaz** [gradle/gradle#2921]
The JacocoTestReport task executes as expected when test task has previously been executed. However, just running JacocoTestReport on a clean environment, executes compile but does not execute test compile and test.  The console report `JaCoCoTestReport SKIPPED`.   This behavior is a bit unclear. Please clarify in documentation at [(https://docs.gradle.org/current/userguide/jacoco_plugin.html)]

### Expected Behavior
Please change the dependency of JacocoTestReport to `dependsOn: test`  or provide explanation on the documentation page as to why not.

### Current Behavior
Execute JacocoTestReport and task is SKIPPED if tests not previously executed. What is the use case for not depending on the test task?

### Context
If I misunderstood the operation and there is a use case, then please clarify for me.

### Steps to Reproduce (for bugs)
Just setup a java app with tests including standard implementation as defined in the documentation sited above.

### Your Environment
Nothing special.

**Comment by bmuschko** [comment]
@big-guy I think we discussed this before. Do you remember the reason? I believe the report task is not incremental, same for the coverage verification task. IMHO that's not a good enough reason for not depending on the test task.

**Comment by big-guy** [comment]
It was intentional, but I don't know the reasons exactly.  It's not that the report task isn't incremental. I think it's so you could run the report on existing coverage data without rerunning the tests.

@breskeby and @adammurdoch were involved in that: https://github.com/gradle/gradle/commit/971f7815d55103aaed979c50620800b9abd911d6#diff-87d7c4e4b93105fdd221177a26e106e0

**Comment by andreas-schilling** [comment]
Stumbled upon this as well. Re-running the report without re-running the tests would be a valid reason, but then the documentation is still a bit confusing.

**Comment by tcfurrer** [comment]
Please fix this issue.  The documentation for the Jacoco Plugin still says:

"If the Java plugin is also applied to your project, a new task named jacocoTestReport is created that depends on the test task."

The argument that the task dependency isn't automatically created makes no sense to me... folks who want to regenerate the report but not re-run tests can simply apply "-x test" to the commandline.

In general, task dependencies should be added by plugins automatically.  Adding this task dependency in my build script just adds meaningless clutter.  Issues like this sort of make it feel like users have to cross Gradle's T's and dot its I's, which certainly isn't the feeling we want to generate.

**Comment by JLLeitschuh** [comment]
This behavior was fixed before 5.0 but seems to have been reverted post 5.0.

**Comment by Godin** [comment]
@andreas-schilling 

> the documentation is still a bit confusing

why not contribute - #9597 ? 😉
