### ISSUE TITLE
`sourceSets.create()` uses deperecated/superfluous API

### ISSUE THREAD

**Issue by pauliesnug** [gradle/gradle#29215]
### Issue type

Deprecation

### Problem description

When using Gradle `8.7` with the Kotlin version it ships with (outdated `1.9.22`), the `sourceSets.create` or `sourceSets.creating` functions call uses the deprecated `setCanBeResolved` api, resulting in a deprecation warning:

```
The resolvable usage is already allowed on configuration ':testARuntimeClasspath. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Remove the call to setCanBeResolved(true), it has no effect.
```

Here is a GitHub Actions reproduction for context: https://github.com/pauliesnug/gradle-plugin-publish-issue-1/actions/runs/9149209703/job/25152603811#step:4:250

**Comment by ljacomet** [comment]
This is, unfortunately, a known issue that needs to be fixed through collaboration between Gradle and JetBrains. Until it gets resolved, you will see the deprecation warning.

Related YouTrack issue:
* https://youtrack.jetbrains.com/issue/KT-66542
