### ISSUE TITLE
Unresolved reference error file of my forked repository is same than vanilla file original repository worked

### ISSUE THREAD

**Issue by MartinEesmaa** [gradle/gradle#29268]
### Current Behavior

It doesn't work and causes unknown error unresolved reference error one file is same compared to vanilla file. I don't know that I cleaned .gradle folder from my home folder on Linux and it caused an error issue.

### Expected Behavior

It will work to continue build and release apk files after all compiled codes and libraries were done of my forked repository.

### Context (optional)

The issue affected to me for building my forked repository, the all codes of all files are same of my forked repository as forked repository, but different package name of android app and little bit some codes.

My forked repository: https://github.com/MartinEesmaa/mpv-android-vvc
Original/vanilla repository: https://github.com/mpv-android/mpv-android

### Steps to Reproduce

1. Git clone of my forked repository
2. Going to my forked/buildscripts, chmod +x scripts/*.sh, ./download.sh and also targeting of arm64, x86_64 and x86.
3. Finally, run `./buildall.sh` to compile mpv-android after all dependencies folders.
4. And I get a error of unresolved reference when during build was interrupted.

Also, I tried to reset all files by copying from vanilla files to my forked repository, but skipped files and changed package name again. Doesn't work still.

### Gradle version

8.7

### Build scan URL (optional)

https://scans.gradle.com/s/5tepom7txog6k

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

See the compiler error
https://scans.gradle.com/s/5tepom7txog6k/console-log?page=1#L154
