### ISSUE TITLE
Annotate all properties that should be migrated with `@ToBeReplacedByLazyProperty`

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#29274]
We should also create a complementary annotation, maybe something like`@EagerProperty(because = "reason")`.

Additionally we should also add an archunit tests to check that we annotated all eager properties with these annotations (or we migrated them).

**Comment by sergej-koscejev** [comment]
Question from a Gradle user: what lazy property are FileCollections supposed to be replaced with? I thought they are already lazy and they have a nicer API in comparison with `SetProperty<FileSystemLocation>` or some such.

**Comment by asodja** [comment]
@sergej-koscejev Yes, they are already lazy. In that case annotation is a bit misinformative. But most of them will be replaced with `ConfigurableFileCollection`.
