### ISSUE TITLE
Error:Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-all.zip'

### ISSUE THREAD

**Issue by yuliayuliayulia** [gradle/gradle#2927]
I am a new user of Android Studio and just had it installed on WIndows 64 bit laptop, where in was never used before. When I start the Android Studio application and create a new project the following Error message appears:
Error:Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-all.zip'.

I would very much appreciate if you could give instruction on how to fix this.

**Comment by blindpirate** [comment]
Thanks for reporting. However, we need more detailed messages:

- What's your environment? OS/JDK/Android Studio version, etc.
- Could you describe the detailed steps to reproduce this issue?
- Could you give us more detailed error message (e.g. stacktrace)? You can click the error in Android Studio to get it.

**Comment by yuliayuliayulia** [comment]
Thank you for looking into it.

1. Windows 7 Professional. Android Studio version 2.3.3

2. I create a new project and the error message appears right away. If I try to import a project it still appears.

3.  log:

9/13/2017
10:10 AM	Gradle sync started

10:10 AM	Gradle sync failed: Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-all.zip'.
					Consult IDE log for more details (Help | Show Log)

10:10 AM	Gradle sync started

10:10 AM	Gradle sync failed: Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-3.3-all.zip'.
					Consult IDE log for more details (Help | Show Log)

**Comment by blindpirate** [comment]
Could you click the `Show Log` to get more details? There's little information in your description.

**Comment by yuliayuliayulia** [comment]
[idea.txt](https://github.com/gradle/gradle/files/1300172/idea.txt)

**Comment by oehme** [comment]
@yuliayuliayulia it looks like the downloaded Gradle distribution is broken. I'm not sure how your system ended up in this situation. Try deleting `~/.gradle/wrapper/dists`.

**Comment by bmuschko** [comment]
@yuliayuliayulia Did you give this another shot?

**Comment by blindpirate** [comment]
Closed due to unresponsiveness.

**Comment by Bno93** [comment]
I got the same error but in my case the URL in the error message pointing to my local gradle installation instead of 'https://services.gradle.org/distributions/gradle-3.3-all.zip'.

Is there any solution ?
