### ISSUE TITLE
Daemon logs should use explicit encoding instead of JVM default

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#29302]
### Issue type

Polishing

### Problem description

Currently, daemon logs are written and read with system default encoding, which may cause issues when e.g. TAPI client and the daemon use different defaults.

**Comment by mlopatkin** [comment]
Defined == something that both sides agree upon rather than relying on the JVM defaults. UTF-8 is a good candidate.

**Comment by lptr** [comment]
How about renaming the issue to "Daemon logs should use explicit encoding"?
