### ISSUE TITLE
Specification for prefix versions broke

### ISSUE THREAD

**Issue by tudortimi** [gradle/gradle#29316]
### Issue type

Wrong or misleading information

### Problem description

The page mentions the `+` character, but it's not listed at all in the examples. An older version of the page shows `+` used in versions: https://docs.gradle.org/7.5.1/userguide/single_versions.html

### Page with the problem

https://docs.gradle.org/8.7/userguide/single_versions.html

**Comment by ov7a** [comment]
It's already fixed by https://github.com/gradle/gradle/pull/28780
