### ISSUE TITLE
Make DependencyHandlerInternal.getDefaultArtifactAttributes() public API

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#29319]
This would be real useful for extracting the public API classes directly from the classes produced in our subprojects.

Currently this feature is used in instrumentation, but has only an internal API.

**Comment by jvandort** [comment]
The advantage of this over `getArtifactTypes` is:
1. It works for directories
2. It does not need to realize tasks to compute attributes. 

This would be our replacement for `getArtifactTypes` to deprecate that API.

**Comment by big-guy** [comment]
This might not be the only way to do this.  e.g., we may want to change the way attribute matching deals with missing attribute values or have some kind of "default" value for an attribute.  This might belong on the attribute schema.

**Comment by big-guy** [comment]
We have an internal API for this that doesn't block Provider API upgrade infrastructure work.  This can wait until after 8.x

**Comment by jvandort** [comment]
We likely do not want a solution like this. We should avoid a pattern where the consumer side "modifies" the attributes of the producer side. 

Instead, as sterling mentioned, a proper solution would be to somehow handle this at the artifact transform level, by allowing them to either declare transforming from the absence of a `from` attribute, or to somehow declare a default value for an attribute when calculating transform chains.

**Comment by jvandort** [comment]
Closed in favor of https://github.com/gradle/gradle/issues/31538
