### ISSUE TITLE
Working with Files - CopySpec - should be linked to on the Distribution Plugin doc page 

### ISSUE THREAD

**Issue by thadguidry** [gradle/gradle#29310]
### Issue type

Wrong or misleading information

### Problem description

Often folks don't know how to customize their distribution.  It often involves copying files and moving them around first, and then assembling the distribution.

We currently don't make this easy to discover from the Distribution Plugin doc page.  Specifically, we should mention it here:  https://docs.gradle.org/current/userguide/distribution_plugin.html#sec:distribution_contents

### Context (optional)

I've had many folks ping me and tell me THANKS for writing up an example.  Such as https://stackoverflow.com/questions/25951047/how-to-cherry-pick-zip-contents-with-gradle-distribution-plugin/35929148#35929148
We might also give my example within that answer additionally, and point folks to the "Working With Files" doc for further customization needs.

I'd be happy to improve the Distribution Plugin doc page with a PR, if consensus can be had on what/how we want to say the above.

My suggestion to add after current existing Example 3. :
-----------------
### Example 4. Working With Files using CopySpec

```groovy

distributions {
    main {
        baseName= 'myArchive'
        contents {
            into('bin/config') {
                from 'config'
            }
            into('lib/samples') {
                from 'samples'
            }
        }
    }
}
```

In the example above, the `bin/config` directory is created if not already existing, and the contents of `config` directory are copied into it. Similiarly for the `lib/samples` directory.

For details on using [CopySpec](https://docs.gradle.org/current/userguide/working_with_files.html#sec:copying_files) or working with files generally, please consult our userguide [Working With Files ](https://docs.gradle.org/current/userguide/working_with_files.html)

---------------------

Above Looks good?

### Page with the problem

https://docs.gradle.org/current/userguide/distribution_plugin.html#sec:distribution_contents

**Comment by ljacomet** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

***

Thanks for proposing to fix this. What you suggested sounds great to me. The team responsible for that area and our docs person will be happy to help push the PR through if you send one.

**Comment by thadguidry** [comment]
Will do!
