### ISSUE TITLE
How to customize the version sorting rules of dependency

### ISSUE THREAD

**Issue by zhaobingfeng** [gradle/gradle#2931]
Our company has a lot of internal use of the library, the version format is like "**deug1.0.2**" and "**release1.0.0**", the number is the actual version number, prefix that developed version or official version. 
When a project relies on a library of "**debug1.0.2**" and "**release1.0.0**", the last effect is "**release1.0.0**" instead of the "**debug1.0.2**" we want because the Gradle default collation is similar to the letter order. 
We did not think there was a problem when we defined the version format. Can we customize the version collation? To find the latest version that meets our requirements. Otherwise we can only let all the libraries start using the new version format.
>`ResolutionStrategy` can not meet my requirements because it requires a change in the library version to change this configuration

**Comment by oehme** [comment]
The problem you are facing is what we call "variant aware dependency resolution". We are currently implementing support for that in our native plugins (C/C++) and will later provide the same capabilities for the Java ecosystem.

"debug1.0.2" and "release1.0.2" are not different versions, but two variants of the same version. So version sorting is not the solution here. Instead you will be able to define different variants of your project (e.g. "debug" and "release") and Gradle will automatically resolve the right variant of that project's dependencies.

For now you can use `ResolutionStrategy` to implement a rule that replaces "debug" with "release" when you want "release" artifacts and vice versa.
