### ISSUE TITLE
Add an option to disable test fixtures publication

### ISSUE THREAD

**Issue by osipxd** [gradle/gradle#29328]
### Expected Behavior

It would be great to have an option to disable test fixtures from publishing.

### Current Behavior (optional)

Currently, the only way I know is to use internal Gradle APIs to skip specified components from publication:

```kotlin
plugins.withId("org.gradle.java-test-fixtures") {
    val component = JavaPluginHelper.getJavaComponent(project) as DefaultJvmSoftwareComponent
    val feature = component.features.getByName(TestFixturesSupport.TEST_FIXTURES_FEATURE_NAME)
    component.withVariantsFromConfiguration(feature.apiElementsConfiguration) { skip() }
    component.withVariantsFromConfiguration(feature.runtimeElementsConfiguration) { skip() }
}
```

### Context

I need to use test fixtures only internally between my modules, so I don't want to publish them into Maven Central. Here is the project: [osipxd/encrypted-datastore](https://github.com/osipxd/encrypted-datastore) (module encrypted-datastore contains test fixtures)

**Comment by ljacomet** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

This is documented [at the end of this section](https://docs.gradle.org/current/userguide/java_testing.html#publishing_test_fixtures) without using internal APIs.

**Comment by osipxd** [comment]
Thank you! My bad, I don't know how I missed that in docs.
