### ISSUE TITLE
Property.replace is gone from 8.8 RC2

### ISSUE THREAD

**Issue by consp1racy** [gradle/gradle#29336]
### Current Behavior

Code involving Property.replace doesn't compile.

### Expected Behavior

Code involving Property.replace compiles (and works as advertised).

### Context (optional)

See https://github.com/gradle/gradle/issues/27227. Gradle 8.8 RC2 release notes mention this as solved. It was in RC1, is *NOT* anymore.

### Steps to Reproduce

```
objects.setProperty<String>()
    .replace { setProvider ->
        setProvider.map { set ->
            set + "item"
        }
    }
```

### Gradle version

8.8 RC2

### Gradle version that used to work

8.8 RC1

**Comment by mlopatkin** [comment]
We've decided that we need to tweak `replace` behavior, so it is not ready to be released in 8.8. Sorry for the confusion.
