### ISSUE TITLE
Auto-detection of installed toolchains by mise

### ISSUE THREAD

**Issue by dkowis** [gradle/gradle#29355]
### Expected Behavior

auto detection of jvm installs by [mise](https://mise.jdx.dev/)

### Current Behavior (optional)

from this [link of doc](https://docs.gradle.org/current/userguide/toolchains.html), auto-detection picks up asdf, but not mise. Mise can use asdf plugins, just puts things in a slightly different location.

### Context

ASDF is very slow, and mise is very fast, and so I have begun using mise a whole lot more. It would be super nice to support it :D Happy to make a pull request, if I could get a bit of context for where to look. I suspect it'll be really simple.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Same questions and relates to:
* #29121

**Comment by big-guy** [comment]
Sorry, we don't want to add more built-in options.

I opened a new issue that describes roughly our approach: https://github.com/gradle/gradle/issues/29508

We want a mechanism so 3rd parties can add support for different package manager options and not require changes to Gradle to support them. Eventually, we would remove the existing options.

**Comment by bric3** [comment]
I agree with @jdx, adding this path `~/.local/share/mise` seems like a good compromise : fairly low complexity / low maintainance while delivering immediate values.

And also doesn't prevent to work on 3rd party approach.

**Comment by koppor** [comment]
Just hit this issue today, too. `mise` is a really nice and maintained cross-platform SDK manager

**Comment by bric3** [comment]
It's a bit sad because this was closed as not planned in 2024. But we didn't see the alternative #29508 being worked on (this is not critic, as I understand all things need to be scheduled), while supporting `mise` is a very low maintenance fix with immediate benefit.

Moreover it's like there no new env (JDK) manager support request regularly. In fact there are no new issue requesting adding another since that one was open.

**Comment by chadlwilson** [comment]
> It's a bit sad because this was closed as not planned in 2024. But we didn't see the alternative [#29508](https://github.com/gradle/gradle/issues/29508) being worked on (this is not critic, as I understand all things need to be scheduled), while supporting `mise` is a very low maintenance fix with immediate benefit.

It seems like even more of a cruel joke given the ASDF support has not been removed (despite ASDF's fundamental plugin security issues) and neither has Jabba - which went entirely unmaintained for a long period in the meantime, before being forked. Neither of which should be endorsed for usage IMHO.

The [symlink workaround](https://mise.jdx.dev/lang/java.html#gradle-toolchains-detection) is fine (on Linux/MacOS, haven't tried on Windows); but what a silly thing to have to do everywhere for years now.

**Comment by dkowis** [comment]
Would a merge request be accepted as a bandaid fix, given the state of the industry preferring mise? Even if it's not the ideal path, with the knowledge that it's best-effort supported? Sort of a "community thing" or is that too difficult to carve out of "gradle isn't working" properly type things?

**Comment by chadlwilson** [comment]
In the last two years, things have gone from rtx -> mise and the usage has grown immensely, so perhaps that was another factor for closing it back then (rtx was relatively new). Perhaps the easiest way to get it onto the queue is to just try again for reflection given zero progress on alternatives; and it can be considered just how big `mise` is vs all those other options - and Gradle's aims to further break into non Java areas which makes a multi-lang multi-tool version manager like mise an even better fit.

Another factor possibly in its favour now is that mise supports Windows, which it did not back then (and which SDKMAN, ASDF do not outside WSL2, IIRC) so perhaps the approach can be modified to reflect that.

**Comment by bric3** [comment]
Oh and I completely missed that jbang also added support for `mise` https://github.com/jbangdev/jbang/issues/2019
