### ISSUE TITLE
Strange "Could not get unknown property 'projectConfiguration' for DefaultProjectDependency" error in multi-project in gradle 4.1

### ISSUE THREAD

**Issue by Leo-Lei** [gradle/gradle#2936]
I have a project contains two modules, api and service.
The service depends on the api module.
`dependencies {
    compile project(':api')
}
`
But I get below warning:
`Could not get unknown property 'projectConfiguration' for DefaultProjectDependency` 
And the service module can not access the classes in api.

The Gradle version is 4.1. And I also test the Gradle 2.14.1. It works fine in Gradle 2.14.1.

**Comment by oehme** [comment]
From the provided information I can only assume you are trying to import a new Gradle project into an older version of IntelliJ IDEA. Please upgrade to the latest version.

If that doesn't fix the issue, please provide a reproducible example project and instructions how to reproduce the problem.

**Comment by Leo-Lei** [comment]
Thanks, oehme, you are right. I update the IDEA to latest version, and it works fine now. Thanks a lot.

**Comment by perry0105** [comment]
Thanks @oehme @vangoleo , I had the same problem too.

**Comment by wajiii** [comment]
I am having this problem **_right now_**! Unfortunately, my IDE does not indicate any updates currently available(I am on 2017.2.4, "Build #IU-172.4155.36, Built on September 11, 2017"), so I cannot benefit from the previously mentioned solutions (nor do I have any other known recourse)! 😞 👎

**Comment by oehme** [comment]
That's a completely different problem. Please open a bug report including a reproducible example.
