### ISSUE TITLE
Javadoc styling clashes when Gradle's dark theme is enabled

### ISSUE THREAD

**Issue by EdricChan03** [gradle/gradle#29394]
### Issue type

Styling or Accessibility

### Problem description

When the dark theme option is enabled from the Gradle documentation site, viewing any Javadoc for a Gradle API (for e.g. the newly introduced [`IsolatedProject` interface](https://docs.gradle.org/8.8/javadoc/org/gradle/api/project/IsolatedProject.html)) would result in broken styling:

![Screenshot of IsolatedProject Javadoc with dark theme enabled, where the text isn't rendered correctly](https://github.com/gradle/gradle/assets/20047125/af1ef71b-e681-4eca-8b79-0e52bebaccde)

I believe this issue applies to all of the Javadoc pages as well.

### Page with the problem

https://docs.gradle.org/8.8/javadoc/org/gradle/api/project/IsolatedProject.html

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by lkasso** [comment]
I am still seeing some issues. Re-opening to look into this week.

**Comment by oleg-nenashev** [comment]
FYI @lkasso there is a pretty nice CSS for the dark theme here: https://gist.github.com/Nzen/b415f66604e1b6562a49
