### ISSUE TITLE
Gradle 8.8 missing from Kotlin compatibility matrix

### ISSUE THREAD

**Issue by markslater** [gradle/gradle#29399]
### Issue type

Missing information

### Problem description

The [Gradle 8.8 compatibility matrix](https://docs.gradle.org/8.8/userguide/compatibility.html) doesn't specify the version of Kotlin embedded in 8.8.

### Page with the problem

https://docs.gradle.org/8.8/userguide/compatibility.html

**Comment by ov7a** [comment]
Please note that this is a **Minimum** Gradle version. That means that if there are no entry for 8.8, you can use the one for 8.7.

What we can do to improve the perception is to swap the "Minimum Gradle version" and "Embedded Kotlin version" columns.
