### ISSUE TITLE
Make Java compilation parallel by default

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#2939]
Java compilation should leverage the Worker API to become parallel by default.

### Expected Behavior
Java compilation is parallel by default, including intra-project.

### Current Behavior
Java compilation is not parallel by default, it can be parallelized using `--parallel` but not intra-project.

### Context
The existing infrastructure for Java compilation is also used in Gradle for Groovy and Scala compilation, a lot of it being shared. This effort could apply to the three compilers.

Some investigation was already done on using the Worker API. Here is a spike branch with Java/Groovy/Scala compilation parallel by default that could be reused or inspire: [pm/workers/compilation-workers-spike](https://github.com/gradle/gradle/tree/pm/workers/compilation-workers-spike)

**Comment by jaredsburrows** [comment]
This is a great idea. I believe this will benefit new users to Gradle. This will greatly help new users and projects with build speed.

**Comment by dforsl** [comment]
Hi! Are there any plans for this? Truly looking forward to intra-project parallelism for java and scala!

**Comment by ljacomet** [comment]
This is stale indeed because Gradle evolves towards the configuration which enables safe intra-project parallelism.
