### ISSUE TITLE
declarative component selection

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#29417]
### Expected Behavior

It'd be nice to have a less procedural way of defining components, perhaps even a way to do it via libs.versions.toml, or similar toml file. Maybe something like

```kts
reject("https://hibernate.atlassian.net/browse/HHH-18203", "org.hibernate.orm:hibernate-jpa-modelgen:6.5.+", expiration = "6.6.+")
// not looking up correct group, might be wrong, expecting exact group/artifact
reject("...", "com.uber:nullaway", "^0\.9\.[34]$")
```

```toml
hibernate-jpa-modelgen = { 
  module = "org.hibernate.orm:hibernate-jpa-modelgen",
  version.strictly = "6.4.+",
  reject = { reason = "...", version = "6.5.+", expiration = "6.6+" },
}
```

I haven't put a huge amount of thought into this, but it feels like a generally cleaner API could happen for simpler use cases.

### Current Behavior (optional)

```kts
configurations.configureEach {
  exclude(group = "org.slf4j", module = "slf4j-nop")
  exclude(group = "junit", module = "junit")

  resolutionStrategy {
    componentSelection {
      all {
        val nonRelease = Regex("^[\\d.]+-(M|ea|beta|alpha).*$")
        val module = Regex("^spotbugs.*")
        val group = Regex("^com.xenoterracide$")
        if (!candidate.group.matches(group) && !name.matches(module) && !candidate.module.matches(module)) {
          if (candidate.version.matches(nonRelease)) reject("no pre-release")
          if (candidate.version.endsWith("-SNAPSHOT")) reject("no snapshots")
        } else if (candidate.version.matches(nonRelease)) {
          logger.info("allowing: {}", candidate)
        }

        if (candidate.module == "hibernate-jpa-modelgen" && candidate.version.startsWith("6.5")) {
          reject("https://hibernate.atlassian.net/browse/HHH-18203")
        }

        if (candidate.module == "nullaway") {
          val reason = "https://github.com/uber/NullAway/issues/533"
          if (candidate.version.matches(Regex("^0\\.9\\.[34]$"))) reject(reason)
        }
      }
    }
  }
}
```

### Context

I personally think this code is unwieldy and ugly

related, included example of other suggested feature #29418 

current gradle: 8.7

**Comment by ljacomet** [comment]
We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

This issue will be closed after 7 days unless you provide more information.

***

How is this different from [rich versions](https://docs.gradle.org/current/userguide/rich_versions.html#header)?
Note that they are available as well for version catalogs.

And if that's the cause, is `because` the main thing missing ?
