### ISSUE TITLE
Allow to set logger for project in ProjectBuilder

### ISSUE THREAD

**Issue by augi** [gradle/gradle#2942]
It's recommended to use `ProjectBuilder` class when testing a custom Gradle plugin but there is no way how to set logger of the created Project. It seems that it uses `NoOpLogger` by default and so the developer of a Gradle plugin doesn't have any way how to see output of the project execution.

### Expected Behavior
It's possible to set logger of a new project when working with `ProjectBuilder`.

### Current Behavior
The project created by `ProjectBuilder` logs nothing.

### Context
Testing of custom Gradle plugin.

### Your Environment
IDEA as IDE, Spock as testing framework

**Comment by bmuschko** [comment]
> It's recommended to use ProjectBuilder class when testing a custom Gradle plugin.

I don't think this is a statement that we'd usually would sign off. If you want to test a plugin on a functional level then TestKit is the right tooling. I don't think we'll invest into `ProjectBuilder` anytime soon as TestKit provides all of the capabilities needed to effectively test a plugin. I am going to close this issue.
