### ISSUE TITLE
Update third party dependencies to fix potential vulnerabilities

### ISSUE THREAD

**Issue by merscwog** [gradle/gradle#2944]
When a security scan is run against Gradle 4.1 itself, there are several dependencies that have security CVEs associated with the versions used.  Most of the third party libraries have newer versions that have fixes, and below are a few examples:

- bcprov-jdkon is 1.51 and the latest version is 1.58 (many security issues addressed in later versions)
- beanshell, bsh is 2.0b4 and the latest is version 2.0.b6 which specifically addresses a vulnerability
- jackson-databind is 2.6.6 and there are multiple versions that include a critical vulnerability patch 2.6.7.1, 2.7.9.1, and 2.8.9
- xercesImpl is 2.9.1 and the latest version is 2.11.0 (miscellaneous fixes in here)

There are other less critical ones, but they probably all should be examined.

Something like the [OWASP dependency check](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/), [Sonatype App scanner](https://www.sonatype.com/appscan), or something similar could be run against newer versions of Gradle.

Companies are actually using tools like the above mentioned to determine whether products that include third party dependencies with known vulnerabilities will be allowed or rejected for internal usage.

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Thank you for bringing this up. Those all look like things that we only use internally, so as long as our tests pass, these upgrades are a good idea.

**Comment by bmuschko** [comment]
@merscwog I integrated the OWASP dependency check plugin in a [step of our CI pipeline](https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_DependenciesCheck). We'll have to improve the CVSS threshold of our libraries over time. Right now it is [set to 8](https://github.com/gradle/gradle/blob/master/gradle/dependenciesCheck.gradle#L32) which is quite high.
