### ISSUE TITLE
FileCollection.singleFile alternative to track dependency

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#2947]
### Expected Behavior

Given this:

```groovy
task mergeTask(type: Zip) {
	from "src"
	baseName "lajos"
	destinationDir file("build/archive")
}

task copyTask(type: Copy) {
	from zipTree(mergeTask.outputs.files.singleFile)
	destinationDir file("build/copy")
}

mergeTask.baseName = "tibor"
```

I would expect Gradle to discover that `copyTask` depends on `mergeTask`, and for `copyTask` to find the output created by `mergeTask`.

This could be achieved by adding an alternative to `FileCollection.singleFile` that would return a `RegularFile` built by `mergeTask`. This would fix both the too eager evaluation of `mergeTask.outputs.files.singleFile` and the discovery of the dependency between the two tasks.

Given such an alternative we should probably deprecate `FileCollection.singleFile`, too.

(We would also need to make a change for `FileResolver.zipTree()` not to resolve its input eagerly, but that can be done separately.)

### Current Behavior

Running `copyTask` fails, because `mergeTask` is never invoked. This is because `mergeTask.outputs.files.singleFile` evaluates during configuration time to a `File` object that does not track its origin, so Gradle cannot discover the dependency between `copyTask` and `mergeTask`.

Adding an explicit `copyTask.dependsOn mergeTask` fixes this problem, however the error is still not gone:

```text
* What went wrong:
Cannot expand ZIP '/Users/lptr/Workspace/gradle/bugs/task-config-order/build/archive/lajos.zip' as it does not exist.
```

This time `mergeTask` gets invoked, but `copyTask` doesn't find the created `tibor.zip`. The problem is caused by the archive base name being changed _after_ `mergeTask.outputs.files.singleFile` is already evaluated to `lajos.zip`. This can be circumvented by wrapping the value in a closure like this, so it gets evaluated later:

```groovy
from { zipTree(mergeTask.outputs.files.singleFile) }
```

**Comment by oehme** [comment]
This now exists in the form of file properties. https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:working_with_task_dependencies_in_lazy_properties
