### ISSUE TITLE
https://docs.gradle.org/8.8/javadoc/package-list is HTTP/404 but HTTP/200 with 8.7 dokka requires to download this resource

### ISSUE THREAD

**Issue by dlmiles** [gradle/gradle#29478]
### Current Behavior

https://docs.gradle.org/8.8/javadoc/package-list is HTTP/404 but HTTP/200 with 8.7 dokka requires to download this resource

https://docs.gradle.org/current/javadoc/package-list  HTTP/404

https://docs.gradle.org/8.7/javadoc/package-list  HTTP/200
https://docs.gradle.org/8.5/javadoc/package-list  HTTP/200
https://docs.gradle.org/8.0/javadoc/package-list  HTTP/200
https://docs.gradle.org/7.0/javadoc/package-list  HTTP/200
https://docs.gradle.org/6.6.1/javadoc/package-list  HTTP/200

The dokka plugin from JetBrains makes use of this data.

I notice the style changed between 8.7 and 8.8 of javadoc.

Is this removal of the file intended ?
Is a parsing provider needed in dokka now to download the larger files that are in HTML form and extract similar data ?

### Expected Behavior

A small text file served via HTTP/200 approx 7 KiB with one line per fully-qualified package name.

### Steps to Reproduce

wget https://docs.gradle.org/current/javadoc/package-list

### Gradle version

8.8

### Gradle version that used to work

8.7

**Comment by dlmiles** [comment]
When researching this by examining the plugin:

https://github.com/Kotlin/dokka/blame/09437c33bae16dd6432129db7b5706577103d3ba/dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/defaultExternalLinks.kt#L17

It looks like since JDK11 the filename became "element-list"

So the URL:
  https://docs.gradle.org/8.8/javadoc/element-list
  https://docs.gradle.org/current/javadoc/element-list
provide HTTP/200 data in the expected format

**Comment by ljacomet** [comment]
Thanks for the update, closing as invalid.
