### ISSUE TITLE
Generate warnings on dependency conflicts without failing the build.

### ISSUE THREAD

**Issue by kozayur** [gradle/gradle#2949]
### Expected Behavior

Gradle dependency management allows you to check conflicts in dependencies and fail the build when conflicts are found. It is done through `failOnVersionConflict()` in `resolutionStrategy`. I want to check the conflicts and have warning messages in the log. Although, I don't want my build to fail because of the conflicts.

### Current Behavior

If the conflicts are checked and strict strategy is used, the build will fail if the conflicts are found.

### Your Environment

 * Build scan URL:

**Comment by bigdaz** [comment]
@kozayur Sorry for the delay getting back to you. One thing we are considering is making it possible to generate a `dependencies` report with `failOnVersionConflict()` where the report would tell you about all of the version conflicts. Would that satisfy your needs?

If not, what do you need to do with this information?

**Comment by bogdandrutu** [comment]
Hi @bigdaz 

I would like to have tasks like compileJava or "check" to fail in that case and not needed to generate a dependency report. Is that possible?

**Comment by bigdaz** [comment]
@bogdandrutu yes, that's what [`ResolutionStrategy.failOnVersionConflict()`](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) will do.

**Comment by bigdaz** [comment]
When `failOnVersionConflict` is used, the `dependencies` report will now succeed and report on all conflicts that would cause resolution to fail. There is also an (internal) API for handling the failures on resolve that could be used to generate warnings as requested by @kozayur .  I'm closing this issue for now, given the available workarounds.
