### ISSUE TITLE
Wrong information about removing unintentional subprojects

### ISSUE THREAD

**Issue by esfomeado** [gradle/gradle#29499]
### Issue type

Wrong or misleading information

### Problem description

On the documentation, it mentions the following:

```
If your `settings.gradle(.kts)` looks like this:

Gradle sees a subproject with a logical project name of :subs:web:my-web-module and two, possibly unintentional, other subprojects logically named :subs and :subs:web. This can lead to phantom build directories, especially when using allprojects{} or subproject{}.

To avoid this, you can use:

include(':subs:web:my-web-module')
project(':subs:web:my-web-module').projectDir = "subs/web/my-web-module"
```

If you do this the `subs` and `web` are still included as subprojects and aren't removed as the documentation suggests.

But if you do this it works:

```
include(':my-web-module')
project(':my-web-module').projectDir = "subs/web/my-web-module"
```

The only issue is that you can't name the project `:subs:web:my-web-module`

### Page with the problem

https://docs.gradle.org/current/userguide/multi_project_builds.html#modifying_a_subproject_path

**Comment by hegyibalint** [comment]
Related:
 - https://github.com/gradle/gradle/issues/27115#issuecomment-1834406831

**Comment by hegyibalint** [comment]
This is a valid documentation issue.

**Comment by mlopatkin** [comment]
This documentation issue is confirmed.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.
