### ISSUE TITLE
Problem description copied from the CC report is noisy and ill-formatted

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#29522]
When it is not appropriate to share a complete CC report, copying the description of problems and pasting them into common places leaves a lot to be desired in terms of the formatting.

When the following piece of the CC report is copied
![image](https://github.com/gradle/gradle/assets/2759152/8d8aa8e9-224b-431a-9fca-5667d4472673)

This is how it appears when pasted to Google Docs:
![image](https://github.com/gradle/gradle/assets/2759152/4975a721-ffa0-4b98-8a8a-d83537c02c3d)

In Slack:
![image](https://github.com/gradle/gradle/assets/2759152/ce329952-6926-46e5-808d-3eafbb906a95)

In Sublime:
![image](https://github.com/gradle/gradle/assets/2759152/87cb6f01-9cf0-48b8-924d-679d46f896bf)

**Comment by ljacomet** [comment]
@alllex added the "outside Gradle" milestone.
Please correct it if the CC report is included in Gradle and was updated in another PR.

**Comment by alllex** [comment]
The updated behavior was brought in by https://github.com/gradle/gradle/pull/29440
