### ISSUE TITLE
Error:Unable to instantiate SingleSpaceSeparatorCheck

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#2953]
I am using gralde plugin `checkstyle`. Here is my script:

```gradle
apply plugin: 'checkstyle'

task checkstyle(type: Checkstyle) {
    group = 'Code Style'
    configFile = rootProject.file('checkstyle.xml')
    ignoreFailures = false
    showViolations = true
    classpath = files()
    source = 'src/main/java'
}

// check code style after project evaluation
afterEvaluate { project ->
    getTasksByName('checkstyle', false)[0].execute()
}
```
Gradle project refresh failed.

> Error:Unable to instantiate SingleSpaceSeparatorCheck

I think the error occurs because of `checkstyle.xml` with `SingleSpaceSeparator`.

```xml
<module name="SingleSpaceSeparator">
        <property name="validateComments" value="true"/>
</module>
```

**Gradle Version** : 3.3
**OS** : Max OS

**Comment by CoXier** [comment]
```gradle
checkstyle{
    toolVersion = 8.1
}
```
works for me

**Comment by big-guy** [comment]
```
// check code style after project evaluation
afterEvaluate { project ->
    getTasksByName('checkstyle', false)[0].execute()
}
```

Please do not do this.  This means if someone runs `gradle tasks`, you'll also try to execute checkstyle.  If you try to import your project into Eclipse/IntelliJ, it'll run checkstyle every time the IDE interacts with Gradle. This is almost guaranteed to break things and not do what you want.

**Comment by CoXier** [comment]
I want to apply the gradle plugin into my project in order that every one can keep code style each time when they `gradle assembleDebug` or `gradle tasks`(it's very strict, I know).

**Comment by big-guy** [comment]
If you want to always run checkstyle when someone runs `assembleDebug`, you can do something like:

`assembleDebug.dependsOn tasks.withType(Checkstyle)`

Keep in mind that this breaks the meaning of "assembleDebug" (which isn't meant to test things). 

I don't think it's helpful to run checkstyle when you run `gradle tasks` (this just lists the tasks that are available to run).

I would encourage you to open a topic on https://discuss.gradle.org/ and describe what you're trying to accomplish.  There are lots of helpful people there that are probably trying to do the same thing.
