### ISSUE TITLE
API for adding LICENSE.txt file to published JAR (and other artifacts)

### ISSUE THREAD

**Issue by omarismail94** [gradle/gradle#29536]
### Expected Behavior

FR: An API for users to set the licenseFile and where they want to store it in published packages

In AndroidX, we want to include the full LICENSE.txt file as part of the published JAR. Currently, we do:

```
tasks.withType<Jar>().configureEach { task ->
        task.from(licenseFile) { it.into("META-INF/$projectSubdir") }
    }

// other methods to add to other package types (AARs, klibs)
```

The file will be placed under META-INF/groupId/artifactId/LICENSE.txt (e.g., `META-INF/androidx/wear/protolayout/protolayout-external-protobuf/LICENSE.txt`). 

The reason for using the subdirectory structure is to minimize conflict resolution when artifacts are merged or unzipped.

If there is a method built-in method to do this as part of Gradle's Java Plugin, or publishing plugin, that would be great!

### Context

Adding LICENSE.txt files to published libs

**Comment by hegyibalint** [comment]
The snippet you shared is the right way to do this feature in your build. 

If you need to do this across your builds, make it a convention plugin.  If you need to make it configurable, provide a DSL on your plugin. If you think this is a useful feature usable by everybody, consider publishing it.

We think the tools available now are sufficient.  For example, Gradle doesn't handle AARs or klibs on itself, as they are defined by their respective plugins (AGP, KGP, etc.).

What else could Gradle provide to make this feature easier to make while being general?

**Comment by omarismail94** [comment]
Right now, we do this for all tasks of type JAR. What we're looking for is getting the right jar task that is the published library of a java project without fishing for all tasks and guessing by name

**Comment by ljacomet** [comment]
Gradle will potentially publish multiple JARs for a single project:
* The main JAR
* The sources JAR
* The javadoc JAR
* Any additional variant JAR

Having a general feature for this does not fit the flexibility of Gradle. This feature will be able to be opinionated or configurable in a plugin. This will not be added to core Gradle.
