### ISSUE TITLE
Support Kotlin v2.0.0 

### ISSUE THREAD

**Issue by 10000-ki** [gradle/gradle#29586]
### Expected Behavior

I am wondering when there are plans to support Kotlin v2.0.0

### Context

nope

**Comment by ov7a** [comment]
This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/26534
* https://github.com/gradle/build-tool-roadmap/issues/63

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

We [plan](https://github.com/gradle/build-tool-roadmap/issues/63) to add support for K2 in 9.0.

**Comment by 10000-ki** [comment]
@ov7a thank you for explaning
