### ISSUE TITLE
request more accurate information when emitting dependencies arising from gradle plugins

### ISSUE THREAD

**Issue by mcandre** [gradle/gradle#29618]
### Expected Behavior

The `dependencies` task should note the name of the plugin that pulls in transitive plugin dependencies.

### Current Behavior (optional)

Generic data files name.

### Context

When troubleshooting build systems, or when addressing supply chain security, the name of the toplevel package is essential for communicating the root cause of transitive plugin dependencies.

**Comment by ov7a** [comment]
Could you please clarify your request and provide some examples?
1. If we are talking about plugins, you probably want `buildEnvironment` that displays all buildscript dependencies declared in project with transitive dependencies.
2. What do you mean by "Generic data files names"? Both the `dependencies` and `buildEnvironment` tasks output dependency tree with maven coordinates.
