### ISSUE TITLE
buildSrc plugin cannot use more than one repository

### ISSUE THREAD

**Issue by B4ckslash** [gradle/gradle#29610]
### Current Behavior

I am currently working on transitioning a complex project from Apache Ant to Gradle. To replace a certain Ant macro I am writing what is effectively a binary plugin inside the `buildSrc` directory. This plugin depends on a company-internal library, which I have added to the `dependencies` block inside the plugin's `build.gradle.kts` file. Unfortunately, Gradle fails to resolve this dependency when I add both our internal Ivy repository and `mavenCentral()` to the `repositories` block in the same file, complaining with the following message:
```
Cannot resolve external dependency <library> because no repositories are defined.
```

This is the `repositories` specification: 
```
repositories {
    ivy {
        url = uri("https://repo-url")
        patternLayout {
            ivy("[organization]/[module]/[revision]/ivy.xml")
            artifact("[organization]/[module]/[revision]/[artifact]-[type].[ext]")
        }
    }
    mavenCentral()
}
```
Curiously, if only a single repository is specified, Gradle fails to resolve the artifacts as expected (given that neither repo holds all the transitive dependencies), as well as listing where it searched.

The file tree looks as follows:
```
(root)
|
+ -- buildSrc
|      |
|      + -- build.gradle.kts
|      + -- settings.gradle.kts
|      + -- instrument-plugin
|             |
|             + build.gradle.kts
|             + src/main/kotlin/...
+ -- build.gradle.kts
+ -- settings.gradle.kts
+ -- src/...
```
`buildSrc/build.gradle.kts`:
```
plugins {
    java
}
dependencies {
    runtimeOnly(project(":instrument-plugin"))
}
```

`buildSrc/instrument-plugin/build.gradle.kts`:
```
plugins {
    `kotlin-dsl`
}

gradlePlugin {
    plugins {
        register("instrument-plugin") {
            id = "instrument"
            implementationClass = "InstrumentPlugin"
        }
    }
}

repositories {
    ivy {
        url = uri("https://repo.url")
        patternLayout {
            ivy("[organization]/[module]/[revision]/ivy.xml")
            artifact("[organization]/[module]/[revision]/[artifact]-[type].[ext]")
        }
    }
    mavenCentral()
}

dependencies {
    implementation(<library>)
}
```

It might be worth mentioning that the library specification does have an Ivy configuration set. When I remove this configuration from the spec, Gradle complains that the dependency is looking for a `default` configuration, which is not defined. In this case, Gradle seems to at least fetch the `ivy.xml` for the artifact, otherwise it could not know that there is no `default` configuration.

### Expected Behavior

Gradle accepts multiple repositories and checks the definitions as usual.

### Context (optional)

I need to access a configuration class from the library within a task so that I can configure the execution of the mentioned instrumentor. In a previous attempt at a Gradle plugin, this was done by manually loading said config class via the class loader, using reflection to construct an instance of said class and setting the configuration fields by their name.

I would like to be able to import the class directly into my plugin code (in Kotlin) to have some semblance of proper type safety instead of manually copying member names and hoping that the names match. This obviously requires a dependency on the library containing the configuration class.

### Steps to Reproduce

A sample project can be found at https://github.com/B4ckslash/gradle-error-demo

Steps:
1. Change the repository and dependency specification in `buildSrc/plugin/build.gradle.kts` to something "real"
2. Run `./gradlew build` in the root directory
3. Observe error
4. Check if the resolution works when only a single repo is defined

### Gradle version

8.8

**Comment by ov7a** [comment]
This can be potentially caused by the ivy repository specifics. 

Can you please update your reproducer to be fully isolated by creating a local folder for the ivy repo, putting a dependency there, and using it instead of the remote repository?

**Comment by B4ckslash** [comment]
@ov7a Alright I updated the reproducer with a dummy repository with a small jar and a tiny ivy.xml and adjusted `buildSrc/plugin/build.gradle.kts` accordingly. The error still persists even there.

**Comment by B4ckslash** [comment]
Interestingly, while nailing down the details of the dummy repo and ivy.xml, I noticed that Gradle *does* resolve the repository and downloads and transforms the jar just fine (at least it gets listed as transformed in `gradle build --info`. However it still complains afterward during the execution of `:buildSrc:buildScriptClasspath`:

```
* What went wrong:
Could not resolve all artifacts for configuration ':buildSrc:buildScriptClasspath'.
> Cannot resolve external dependency test:lib:0.1 because no repositories are defined.
  Required by:
      project :buildSrc > project :buildSrc:plugin
``` 

This sounded like adding a `buildscript` block with the appropriate `repositories` configuration would help, so I added the following to `build.gradle.kts`, `buildSrc/build.gradle.kts` (which seemed the most appropriate), as well as `buildSrc/plugin/build.gradle.kts`:
```
buildscript {
  repositories {
    // Use Maven Central for resolving dependencies.
    ivy {
      url = uri("../../dummy-repo")
      patternLayout {
        ivy("[organization]/[module]/[revision]/ivy.xml")
        artifact("[organization]/[module]/[revision]/[artifact]-[type].[ext]")
      }
    }
    mavenCentral()
  }
}
```
The same error still persisted. I am honestly at a loss as to what I could even try anymore.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

This might be an issue with Ivy support and custom repository layouts.

**Comment by big-guy** [comment]
This is a quirk with the way buildSrc works.

Gradle only resolves the runtimeClasspath of the root project in buildSrc.  In your example, you have a dependency on the plugin project, but no repositories are declared in the root project.  So within the plugin project, you can resolve things, but transitively, the root project cannot.

There are a few options:
1. Define the same repositories in buildSrc's root project
2. Move the plugin into buildSrc's root project
3. Define the repositories in buildSrc's settings.gradle.  These are shared by all projects.

**Comment by big-guy** [comment]
@lkasso you might find this interesting
