### ISSUE TITLE
Built-in task to encrypt Gradle properties

### ISSUE THREAD

**Issue by daniel-shuy** [gradle/gradle#29650]
### Expected Behavior

A task, e.g. `gradle encrypt`, to encrypt sensitive info (e.g. credentials) in Gradle properties.

### Current Behavior (optional)

Gradle does not have an equivalent to Maven's [mvn --encrypt-password](https://maven.apache.org/guides/mini/guide-encryption.html).

The closest equivalent we have is the [nu.studer.credentials](https://plugins.gradle.org/plugin/nu.studer.credentials) plugin, which is [no longer maintained](https://github.com/etiennestuder/gradle-credentials-plugin/commit/96ffbc2213b02e634b6d2ff71b43033846c17f5d).

### Context

A common use case is to configure Gradle globally to use an enterprise proxy repository (e.g. Artifactory). [Usually both Gradle Plugin Portal and Maven Central are mirrored](https://plugins.gradle.org/docs/mirroring).

An [Initialization Script](https://docs.gradle.org/current/userguide/init_scripts.html) can be used to configure the `pluginManagement.repositories` and `repositories` of all Gradle projects to use the enterprise proxy repository.

However, because Gradle does not provide a built-in way to encrypt properties, either the credentials have to be stored in plaintext (which is obviously a huge security vulnerability), or we have to use a 3rd-party plugin like [nu.studer.credentials](https://plugins.gradle.org/plugin/nu.studer.credentials).

The issue with using a 3rd-party encryption plugin is that it is a Gradle plugin, which means it still has to be fetched from the Gradle Plugin Portal before the Initialization Script can run. If the company's firewall blocks direct access to the Gradle Plugin Portal to force everyone to go through the enterprise proxy repository, then its not even possible to use an Initialization Script with a 3rd-party encryption plugin. Worst of all, somehow `initscript` does not use plugins from cache, so even if you have download the plugin outside of the company's network, it will still not work when within the company's network.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Given there are issues closed as stale on the topic without a proper answer, it would be good to make a statement on core Gradle support for this.
Also, the [`Credentials` infrastructure](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:handling_credentials) still points at properties.

Related:
* #3972
