### ISSUE TITLE
DependencyConstraintHandler is missing addProvider methods

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#29651]
### Expected Behavior

`DependencyConstraintHandler` is missing `<T> void addProvider​(java.lang.String configurationName, Provider<T> constraintNotation)` and other variations of `addProvider` and `addProviderConvertible` existing on the `DependencyHandler`. 

This should allow supporting cases when the version of constraint is configured in the plugin extension provider.

### Context

Due to [this](https://docs.gradle.org/8.6/userguide/upgrading_version_8.html#dependency_mutate_dependency_collector_after_finalize) change introduced in Gradle 8.6, migration to the constraint approach requires adding workarounds when the version is provided via `Provider`.

**Comment by hegyibalint** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by big-guy** [comment]
We'll take a look and see if there's a reason we can't add these like we have in Dependencyhandler

**Comment by octylFractal** [comment]
FWIW, you can pass a `Provider` to `add`, the return value just isn't useful.
