### ISSUE TITLE
Gradle plugins docs incorrectly specify the settings.gradle

### ISSUE THREAD

**Issue by pjfanning** [gradle/gradle#29675]
### Issue type

Wrong or misleading information

### Problem description

See https://docs.gradle.org/current/userguide/plugins.html#sec:binary_plugin_locations

In settings.gradle example, we have:
```
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
    maven {
        url 'https://maven.example.com/plugins'
    }
}
```

The `maven` section should be inside the `repositories` section.

I have tested this locally and it only works by moving the `maven` section into the repositories` section.

I got an error like this when I used the format that the docs specify (as above).

```
> Could not find method maven() for arguments [settings_aidv6sabetd56ens53bti0b1p$_run_closure1$_closure3@2c12c110] on object of type org.gradle.plugin.management.internal.DefaultPluginManagementSpec.
```

### Page with the problem

https://docs.gradle.org/current/userguide/plugins.html

**Comment by hegyibalint** [comment]
This is a valid documentation issue.
