### ISSUE TITLE
Huge performance degredation with Gradle 8.8

### ISSUE THREAD

**Issue by patrickneulichedldmde** [gradle/gradle#29687]
### Current Behavior

The configuration phase takes 5 times longer since the update to 8.8.
When using the gradle-profiler with chrome-trace `gradle help` jumped from 3s to 20s.

### Expected Behavior

No regression I guess :)

### Context (optional)

We noticed the regression over the past weeks, when doing a git bisect today we saw it was the update to 8.8 which renovate merged on 01.06.
I don't know the code well enough to find out what it is that we are doing, that triggers this behavior.
I'm pretty sure this is one of the oddities we still have in our build scripts that triggers this...

### Steps to Reproduce

Thats hard on this one I think, the project is private and you won't see it with a small project I guess.
I think to have limited it to this `addMutationValidator` in `DefaultDependencyConstraintSet` which was introcuded with this [PR](https://github.com/gradle/gradle/pull/28172/files).
I can share some of the async-profiler output, when running `gradle-profiler --profile async-profiler ... help`

Gradle 8.7
![image](https://github.com/gradle/gradle/assets/169662472/c0b87f8c-7380-42d4-bed2-e7fe34f75541)

Gradle 8.8
![image](https://github.com/gradle/gradle/assets/169662472/bd772f9b-6eb1-4a41-ad7f-e0458b62fd99)

#### Edit:
Found the oddity in our scripts that causes this.
I already thought about it when I read mutation of dependency constraints.
We should be able to fix most of it.
We have some configurations with `transitive = false` we can't simply switch it out with true, but are working on it.
This was the way we found to add constraints to a configuration with transitive false, is there any better way by now?

```
configurations {
	earlib {
		transitive = false
	}
}

def allDependencyConstraints = project(":platform").configurations.api.allDependencyConstraints.toList()
configurations.getByName("earlib").dependencyConstraints.addAll(allDependencyConstraints)
```

### Gradle version

8.8

### Gradle version that used to work

8.7

### Your Environment (optional)

Running gradle Macbook pro M1

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
What's the size of `allDependencyConstraints` here? 
```
def allDependencyConstraints = project(":platform").configurations.api.allDependencyConstraints.toList()
configurations.getByName("earlib").dependencyConstraints.addAll(allDependencyConstraints)
```

In this case, is `:platform` a Gradle platform project that defines constraints? IIUC, you're trying to enforce the constraints from `:platform` on the `earlib` configuration in another project.  Does a dependency on `:platform` not work for you? e.g.:
```
dependencies {
   earlib platform(project(":platform"))
}
```
This resolves the platform from the project `:platform` and would apply the constraints from there.

**Comment by patrickneulichedldmde** [comment]
allDependencyConstraints has ~300 constraints.
:platform is a gradle platform project which only lists constraints.
No and yes since earlib is `transitive = false` adding the platform as a dependency does not add the constraints since they are "transitives" on the platform.
What works is making the configuration transitive and adding dependencies using `earlib("gav-coordinate") { transitive = false }` to it. Thats what we are migrating to right now.

**Comment by big-guy** [comment]
@patrickneulichedldmde would it be possible for you to slim this down into a reproducer or set a breakpoint in https://github.com/gradle/gradle/blob/da8bb2c4e8e73fdfa02cbf485ce1c1e5d52bc781/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dependencies/AbstractDependencyConstraint.java#L27 and tell us how large the onMutate set gets in your case?  It looks very surprising that this would be much larger than the size of allDependencyConstraints.

**Comment by patrickneulichedldmde** [comment]
I thought about creating a simple (but large) repro, but didn't find the time yet.
I'm on vacation for two weeks no, but maybe after that.

allDependencyConstraints has 293 entries.
But we had 200 projects each having ~8 configurations getting their constraints this way.
The onMutate goes up to a size of 1621 (~200 * 8) with each entry being a set with the 293 constraints.
So the `addMutationValidator` was called 200 * 8 * 293 = 569k times on a growing onMutate.

**Comment by jvandort** [comment]
I am confused by this code:
```
def allDependencyConstraints = project(":platform").configurations.api.allDependencyConstraints.toList()
configurations.getByName("earlib").dependencyConstraints.addAll(allDependencyConstraints)
```

This is not project isolation compatible, or how you're supposed to use platforms. 

Why do you not just use:
```
dependencies {
    earlib platform(project(":platform"))
}
```

**Comment by jvandort** [comment]
Excuse my last comment, I neglected to read the thread.

**Comment by big-guy** [comment]
There are a couple of things going on here:
- Sharing Dependency/DependencyConstraint instances across multiple configurations and projects
- Disabling transitive on a configuration makes platforms kind of useless (because we don't enforce their constraints)
- We added extra validation on dependency constraints that did not exist before

There are a couple of workarounds:
- Don't disable transitive on a Configuration and disable transitive on each dependency (which is what OP found)
- Or don't share Dependency/DependencyConstraint instances across projects/configurations by `.copy()` them

Long term, we might consider making Dependency/DependencyConstraints mutable after adding them to a configuration, so we don't need to track mutations.  This is a breaking change.
