### ISSUE TITLE
NettyServer.main is deprecated. Please start your Play server with the play.core.server.ProdServerStart$.main.

### ISSUE THREAD

**Issue by cescoferraro** [gradle/gradle#2969]
### Expected Behavior
Use play.core.server.ProdServerStart$.main to avoid the warning

### Current Behavior
using  play.core.server.NettyServer.main

### Context

I am not sure but I think here its the line
https://github.com/gradle/gradle/blob/714be7950eeb0356c94a1b95eeb0cdc8e9b660aa/subprojects/platform-play/src/main/java/org/gradle/play/plugins/PlayDistributionPlugin.java#L147

### Steps to Reproduce (for bugs)

	gradle clean dist 
	unzip build/distributions/playBinary.zip 
	./playBinary/bin/playBinary

project location
https://github.com/cescoferraro/play-gradle
gradle build.gradle
https://github.com/cescoferraro/play-gradle/blob/master/build.gradle

**Comment by marcospereira** [comment]
@blindpirate, @big-guy and @oehme,

This can be closed. See #3314.

**Comment by blindpirate** [comment]
@marcospereira Thanks.
