### ISSUE TITLE
Honor optional constraints in incoming POMs

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#2970]
When a Maven dependency is marked as `optional`, its version should be taken into account during version resolution if some other module adds a hard dependency on it.

**Comment by mkobit** [comment]
Nice! The JUnit 5 project just ran into this in https://github.com/junit-team/junit5/issues/1065

**Comment by oehme** [comment]
@mkobit that will be covered by #867, which depends on this one.

**Comment by oehme** [comment]
This is on `master`
