### ISSUE TITLE
Provide a new `latest-status` version to only pick latest stable release

### ISSUE THREAD

**Issue by quaff** [gradle/gradle#29714]
### Expected Behavior

Provide a new `latest-status` version like `latest.stable.release` which behaves like `latest.release` but exclude milestone and candidate releases.

### Context

Application doesn't use milestone or candidate releases in practice.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

As documented [in the Javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ComponentMetadata.html#getStatus--), we only derive two statuses from Maven metadata: `integration` or `release`.

While Gradle could do more, the main issue here is that there is no shared understanding in the JVM ecosystem of what makes a given release a non-final release. Some patterns are re-used, but it would be near impossible to cover all variations.

**Comment by big-guy** [comment]
We don't want to add more special case status handling. 

It may be possible to mimic this behavior with a ComponentSelection rule that looks at this attribute.
