### ISSUE TITLE
[Gradle 8.8] groovy and kotlin jars wrongly included in :distZip bundle 

### ISSUE THREAD

**Issue by hrstoyanov** [gradle/gradle#29730]
### Current Behavior

I have a composite build setup. When I try to produce a zip archive for my app (webapp project, using :distZip task) I see that the zip archive contains a lot of groovy and kotlin jars **I did not expect**, and they are not listed as dependencies in any of my modules - this command confirms it:
```bash
./gradlew :webapp:clean :webapp:distZip :webapp:dependencies |grep groovy
```

### Expected Behavior

I expect the zip bundle to contain only the jars I specified, no groovy/kotlin jars.

### Context (optional)

For the composite build setup, here is the **build.gradle** for my **:webapp** project:
```grrovy
plugins {
    id 'groovy-gradle-plugin'
    id 'peruncs.java-application-conventions'
    id 'peruncs.aws-conventions'
}

group = 'insbiz'

dependencies {
    implementation 'peruncs:peruncs-webassets'
    implementation 'peruncs:peruncs-utilities'
    implementation 'peruncs:peruncs-helidon'
    implementation 'peruncs:peruncs-eclipsestore'

    implementation libs.bundles.helidon.webserver
    implementation libs.bundles.helidon.webclient
    implementation libs.bundles.estore
    implementation libs.fuzzywuzzy
    implementation libs.jsoup
    runtimeOnly libs.helidon.logging.jul
//    runtimeOnly libs.slf4j.jdk14

    testImplementation libs.helidon.webserver.testing.junit5

}
```

And here is the s**ettings.gradle** for **webapp**:
```
pluginManagement {
    includeBuild('../modules//build-logic')
}

dependencyResolutionManagement {
    versionCatalogs {
        create('libs', {from(files("../modules/shared.libs.versions.toml")) })
   }
}
```
As you can see, my composite build also uses convention plugins and a shared catalog, but this plugins should not be a reason for spurious Gradle jars to be included in my zip bundles

### Steps to Reproduce

See context

### Gradle version

8.8

### Build scan URL (optional)

https://gradle.com/s/7q7c66rglxi5g

### Your Environment (optional)

Java 22.0.1, Apple M1 (arm), MacOS 14.5

**Comment by alllex** [comment]
Why do you apply the [`groovy-gradle-plugin`](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompile_script_plugin) to your web application?
This makes your webapp a Gradle plugin, which usually is not a desired goal.

Most likely, this is the reason why Gradle-related jars appear on the runtime classpath.

Also, the reproducer you provided is not self-contained, since it applies build logic that is not included such as `peruncs.java-application-conventions`, etc.
