### ISSUE TITLE
Missing link in `Implementing Binary Plugins` doc

### ISSUE THREAD

**Issue by ifeomaro** [gradle/gradle#29739]
### Issue type

Missing information

### Problem description

I was directed to the [`Developing Custom Gradle Types` page](https://docs.gradle.org/current/userguide/custom_gradle_types.html) from the [`Implementing Binary Plugins`](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_binary.html#sec:working_with_files_in_custom_tasks_and_plugins) page. But the link to the `Developing Custom Gradle Types` page is broken. Where can I find the updated link?

<img width="816" alt="page referencing broken link" src="https://github.com/gradle/gradle/assets/5240961/43bfb16a-c0bd-4df0-867a-2cde9034bad7">

<img width="543" alt="page with broken link" src="https://github.com/gradle/gradle/assets/5240961/84e61cfd-7f8a-4548-86f4-9c0df6d5483d">

### Page with the problem

https://docs.gradle.org/current/userguide/implementing_gradle_plugins_binary.html#sec:working_with_files_in_custom_tasks_and_plugins

**Comment by lkasso** [comment]
Thank you. I will fix this asap.
