### ISSUE TITLE
Gradle header dependencies is sensitive to the source ordering

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#29744]
### Current Behavior

Under some scenarios, Gradle will discover a different set of headers between builds breaking compile incremental and cache.

### Expected Behavior

Although there is a deeper issue is in the underlying header discovery process, the process itself should be deterministic between builds.

### Context (optional)

See https://github.com/nokeedev/gradle-native/issues/864.

### Steps to Reproduce

It is very hard to reproduce; see https://github.com/nokeedev/gradle-native/issues/864. The issue was only reproduced inside a client build **and** appears under particular conditions. Regardless of the reproducibility, the presence of possible non-deterministic builds cannot be understated.

### Gradle version

Every Gradle versions

**Comment by alllex** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
