### ISSUE TITLE
Gradle 8.8 with Java 22

### ISSUE THREAD

**Issue by tmetn** [gradle/gradle#29742]
### Current Behavior

Latest versions of Gradle and Java for my current settings on IntelliJ throws me the error below. Can it be fixed?
```

Unsupported Gradle JVM.

Your build is currently configured to use Java 22.0.1 and Gradle 8.8.
```

https://docs.gradle.org/current/userguide/compatibility.html

### Expected Behavior

Successful build of dependencies.

### Steps to Reproduce

Choose JDK version 22 on IntelliJ and either local or wrapper for Gradle.

### Gradle version

8.8

### Build scan URL (optional)

https://gradle.com/s/so4jhxb6iehbo

### Your Environment (optional)

Mac OS Monterey 12.6.1
JHipster 8.6.0

**Comment by tmetn** [comment]
My build fails with the same error, also for non-IntelliJ environment. Not sure if this is IntelliJ related. 

https://stackoverflow.com/questions/77140377/starting-from-which-version-does-gradle-support-java-21

**Comment by alllex** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

This is most likely an integration problem with IntelliJ as indicated in previous comments.

The provided build scan shows the build running with Gradle 8.8 and Java 22, but it **fails with an error that is unrelated** to that.

**Comment by Umair599** [comment]
Issue resolved Android Studio Koala version
