### ISSUE TITLE
Gradle SDK integration with Unity

### ISSUE THREAD

**Issue by meggie3** [gradle/gradle#2976]
Hello, at first we thought to develop Android SDK in the traditional way, however, the multdex  problem causes missing third-party library. Therefore, we have developed the SDK with Gradle but while integrating with Unity, Unity does not support the SDK which is developed with Gradle. 

Unity version: 4.7

Is there any good solution for this? 

The error log is as follows:

CommandInvokationFailure: Unable to convert classes into dex format. C:/Program Files/Java/jdk1.8.0_131\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="D:/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "D:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[

trouble writing output: Too many field references to fit in one dex file: 72403; max is 65536. You may try using multi-dex. If multi-dex is enabled then the list of classes for the main dex list is too large.

#Android SDK# #gradle# #unity# #plugin integration with unity#

**Comment by oehme** [comment]
Hey @meggie3, for Android related issues, please see the [Android Issue Tracker](https://source.android.com/source/report-bugs)

**Comment by meggie3** [comment]
Hey Oehme, but it is also related to Gradle, right? @oehme

**Comment by oehme** [comment]
You referred to a problem with dexing, which is handled by the Android plugin, not Gradle itself.
