### ISSUE TITLE
Add Provider<File>.resolve(child: XXX) extension methods for build scripts

### ISSUE THREAD

**Issue by kelemen** [gradle/gradle#29777]
### Expected Behavior

The list is not exhaustive but the following extension methods would be nice:

```kotlin
fun Provider<File>.resolve(child: String) = map { it.resolve(child) }
fun Provider<File>.resolve(childRef: Provider<String>) = zip(childRef) { dir, child -> dir.resolve(child) }
fun Provider<Directory>.resolveDir(child: String) = map { it.dir(child) }
fun Provider<Directory>.resolveDir(childRef: Provider<String>) = zip(childRef) { dir, child -> dir.dir(child) }
fun Provider<Directory>.resolveFile(child: String) = map { it.file(child) }
fun Provider<Directory>.resolveFile(childRef: Provider<String>) = zip(childRef) { dir, child -> dir.file(child) }
```

### Context

The original issue came up due to the problem of wanting to write:

```kotlin
val myFilename = "dummy"
val myFileProvider = myDirProvider.map { it.resolve(myFilename) }
```

The above code is not compatible with the configuration cache if `myFilename` is top level (due to capturing the script object). Working around this configuration cache problem can be sometimes very awkward. Though the original problem would be solved if the previously mentioned problem was fixed, it would be still nice to have these convenience methods.

**Comment by kelemen** [comment]
`DirectoryProperty` can only be used if you have a `DirectoryProperty`, but the reality is that you are likely to end up with `Provider<Directory>` or even `Provider<File>` instead. Just an example scenario:

```kotlin
val outputDir = layout.buildDirectory.dir("mydir")
val childOutputDir = outputDir.dir("childDir")
// Note that childOutputDir is a Provider<Directory> here for obvious reason
```

If I take your advice, and try to use `DirectoryProperty` instead, then I have to now write this:

```kotlin
objects.directoryProperty().value(childOutputDir).file("myfile1")
```

as opposed to:

```kotlin
childOutputDir.resolveFile("myfile1")
```

Of course, as long as we are passing a literal we can get away with `map`, but once you factor that out into a variable, then you are in for a nasty surprise of breaking the configuration cache (assuming a top level variable).

That is, `DirectoryProperty` does not scale, because just one method call, and it is no longer a `DirectoryProperty` but only a `Provider`. Of course, there are many-many cases where you just have a `Provider<File>` from an existing API.

Even worse when your starting point is a `String`:

```kotlin
providers.gradleProperty("myDirProperty")
    .map { File(it) }
    .let { objects.directoryProperty().fileProvider(it) }
```

This is how I can achieve to have a `Provider<RegularFile>`. And it has many problems:

1. It is obviously hard to read. Especially for those who are not very knowledged about Gradle (and I want the build script to look readable to them).
2. It is hard to discover by those do not already familiar with `ObjectFactory` (which is most developers).
3. There is a needless convolution here, because what I really want is a single mapping from `String` to an absolute path of type `File` or `Directory`. Instead, I create a new property and put the provider inside it.

With that I would add to the original request to have extensions creating `Provider<Directory>` or `Provider<RegularFile>` from `Provider<String>` and `Provider<File>` (if relative making them absolute using a custom directory or the project directory as a base).

Anyway, there is an alternative solution to this request: Make `DirectoryProperty.dir` and `DirectoryProperty.file` deprecated, create instead `DirectoryProperty.resolveDir` and `DirectoryProperty.resolveFile` methods, and make these new methods return `DirectoryProvider` and `RegularFileProvider` respectively. These new interfaces then can have arbitrary convenience methods (of course, the above mentioned convenience factories would still be needed). The benefit of this is that in this case everyone would benefit not just the kotlin dsl.

**Comment by kelemen** [comment]
Some remarks to my previous comment: The `Provider<String>` to `Provider<RegularFile>` can actually be done this way as well:

```kotlin
providers.gradleProperty("myDirProperty")
    .map { File(it) }
    .let { layout.file(it) }
```

though slightly better, the problem remains pretty much the same, and the fact that I even forgot about this just shows how non-obvious these solutions are. That is, Gradle would really benefit from having the recommended (or similar) utilities.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Thanks for taking the time to provide such an elaborate explanation of the challenges you face.

Regarding this issue, and the related issues below, maybe we should consider using one of them as an umbrella for tracking those improvements.
However, if any of the use cases described here actually have a solution, then this should at least become a documentation issue.

Related:
* #26211
* #23708

**Comment by mlopatkin** [comment]
We're not planning to add more extensions to instead focus on the ergonomics of the `ProjectLayout` and family, as part of #23708 and #26211.

It makes sense to package such functions as a reusable library/plugin.
