### ISSUE TITLE
jvm-test-suite gives a warning in intellij

### ISSUE THREAD

**Issue by fkhantsi** [gradle/gradle#29780]
### Current Behavior

testing->suites shows a warning
> 'suites' cannot be applied to '(groovy.lang.Closure)' 
![image](https://github.com/gradle/gradle/assets/120412673/5d853c6d-8806-46b8-8014-f7079948df19)

### Expected Behavior

The block should not show any warnings, as it is doing nothing wrong

### Context (optional)

I am trying to migrate to jvm-test-suite so I can have my component tests separately from unit tests, but this warning is making it difficult, since it hides any real issues that would arise under the suite.

### Steps to Reproduce

Open Intellij.
Create new Java project with gradle and jdk17 and Groovy DSL
Open build.gradle and set to the following

```gradle
plugins {
    id 'java'
    id 'jvm-test-suite'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

testing {
    suites {
        test {
            useJUnitJupiter()
        }

        integrationTest(JvmTestSuite) {
            dependencies {
                implementation project()
            }

            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(test)
                    }
                }
            }
        }
    }
}

tasks.named('check') {
    dependsOn(testing.suites.integrationTest)
}
```

### Gradle version

8.6

### Your Environment (optional)

Each of:
Intellij IDEA Community 2023.3
Intellij IDEA Community 2024.1
Intellij IDEA Ultimate 2023.3
Intellij IDEA Ultimate 2024.1

Windows 11/Windows 10
JDK 17

**Comment by fkhantsi** [comment]
[Same error on intellij youtrack](https://youtrack.jetbrains.com/issue/IDEA-317022/Gradle-JVM-Test-Suite-syntax-error-in-IDE)

**Comment by ov7a** [comment]
This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/newIssue?project=IDEA.

If you believe this is not an IntelliJ IDEA issue, please update with a reproducer that clarifies this.

***

FTR, test suite is an [incubating feature](https://docs.gradle.org/current/userguide/feature_lifecycle.html#sec:incubating_state). 

Please provide a reproducer if affects you outside of an IDE.

**Comment by maciejkwidzinski** [comment]
Tracked in https://youtrack.jetbrains.com/projects/IDEA/issues/IDEA-317022/Gradle-JVM-Test-Suite-syntax-error-in-IDE
