### ISSUE TITLE
Provide some form of credential management for Gradle

### ISSUE THREAD

**Issue by kelemen** [gradle/gradle#29815]
### Expected Behavior

There can be many ways to solve this, so I don't want to pick one. However a solution should:

1. Store credentials in a different location than other configuration.
2. Allow storing credentials encrypted, and even when not encrypted, they should be obfuscated to some degree (maybe with an obfuscation key stored in plain text elsewhere).
3. If there will be a Gradle command to manage credentials that must work without evaluating the build (since that is likely to crash without credentials).
4. Don't force me to add the same credentials to the store multiple times.
5. Note that there is `gradle.wrapperUser`/ `gradle.wrapperPassword`, and the wrapper jar should still remain small, so this might put some limit on what can be realistically achieved. So, maybe the wrapper credentials must be treated as an exceptional case. However, even if it is treated as an exception, it still shouldn't be stored in `gradle.properties`.
6. Provide a specialized API to set credentials from this store for whatever needs it (most notably repositories).
7. Gradle should try to prevent accidentally printing the credentials. Obviously, there can't be a protection against malice, but at least mistakenly printing them.

### Current Behavior (optional)

Gradle offers no standard way of storing credentials. So, most usually people just store them in `gradle.properties` in plain text.

### Context

We have to pass various credentials to the build. This usually happens through Gradle properties. In fact, even the [documentation](https://docs.gradle.org/current/samples/sample_publishing_credentials.html) recommends this in its example. However, this has various drawbacks:

1. You might need to set the credentials for multiple things.
2. Often the same credentials have to be set for multiple things requiring copy-pasting the credentials.
3. They are usually stored in `~/.gradle/gradle.properties` alongside with everything else. This is rather problematic, because it often happens that I want to just show my `gradle.properties` (for some other configurations), but then I have to be careful not to include credentials. And in a screen share, I have to make sure to not show my `gradle.properties` ever. In fact, I have seen people sharing their screen and then showing their credentials (populated with their credentials, and they didn't even seem to realize).

**Comment by kelemen** [comment]
Sorry for the duplicate. For those who bump into this issue, I assume #3972 is what this is marked as duplicate of.

**Comment by ov7a** [comment]
@kelemen Sorry about what. It seems like the comment from @ljacomet was lost. Indeed, we wanted to mark this as a duplicate of
* https://github.com/gradle/gradle/issues/3972

**Comment by kelemen** [comment]
@ov7a Sorry for not noticing the already open issue, which I could have, had I made more effort.
