### ISSUE TITLE
Test report aggregation plugin fails when configuration cache is enabled.

### ISSUE THREAD

**Issue by simon-spinner** [gradle/gradle#29820]
### Current Behavior

Gradle build fails with:
```
* What went wrong:
Could not load the value of field `elements` of `org.gradle.configurationcache.serialization.codecs.ResolutionBackedFileCollectionSpec` bean found in field `resultDirs` of task `:testAggregateTestReport` of type `org.gradle.api.tasks.testing.TestReport`.
> org.gradle.api.plugins.TestReportAggregationPlugin$$Lambda$2355/0x00000000cc0cd280
```

### Expected Behavior

The build succeeds with `org.gradle.configuration-cache=true`.
According to the user guide, the test report aggregation plugin supports the configuration cache.

### Steps to Reproduce

The failure is in a project I cannot share. I tried to create a minimal example with test aggregation, but I could not reproduce it there. The failure happens when calling `./gradlew --configuration-cache testAggregateTestReport`

### Gradle version

8.8

**Comment by ov7a** [comment]
Can you please share a configuration of the `TestReportAggregationPlugin` in your project?
Can you probably provide a build scan?

**Comment by simon-spinner** [comment]
I did some more experimentation. The error happens when you have file dependencies in your project such as:

**Comment by alllex** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

We are unsure whether this problem related to the general file collection-related codec, or whether it's a problem only with the test report aggregation plugin.

**Comment by mlopatkin** [comment]
The non-serializable lambda seems to be this one: https://github.com/gradle/gradle/blob/0077a27b809594555944ee18b3dc334d9aafa5d5/platforms/jvm/plugins-test-report-aggregation/src/main/java/org/gradle/api/plugins/TestReportAggregationPlugin.java#L93

The codec seems to be [overzealous in assuming](https://github.com/gradle/gradle/blob/0077a27b809594555944ee18b3dc334d9aafa5d5/platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/FileCollectionCodec.kt#L227) that `DefaultLocalFileDependencyBackedArtifactSet` cannot be reduced to its contents too, but I assume there are cases where the same type is used to represent e.g. an output of an ArtifactTransform.

I'd suggest fixing the aggregation plugin, though - it might be that some outputs will be legitimately non-reducible.

**Comment by big-guy** [comment]
We need to do the same thing as here: https://github.com/gradle/gradle/pull/27299/files#diff-9c6d344e9d82722812f9626f6cd091c66d06696a366ce8dfd77a2ebdcde001c4
