### ISSUE TITLE
The document should add reference demo

### ISSUE THREAD

**Issue by cfanlei** [gradle/gradle#29843]
### Issue type

Missing information

### Problem description

Follow the document,i got a lot of errors,and couldnot resoleve. please give the reference demo for every trait.thanks

### Context (optional)

The doc should add reference demo

### Page with the problem

all
```[tasklist]
### Tasks
```

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Sorry, I don't understand what document you are referring to. If you are talking about the tutorial, it has supporting samples. Please, be more specific.
