### ISSUE TITLE
TAPI Cross-version tests don't put `core-api` on the TAPI Client's classpath

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#29844]
### Current Behavior

If you write TAPI cross-version test like the following (specifically the import statement, which doesn't have the imported type hardcoded as a string), they will not work:

```groovy
def "supports model polymorphism"() {
        given:
        file("plugins/src/main/groovy/my/MyModelBuilder.groovy") << """
            import ${Project.name}

        // ...
      
}
```

### Expected Behavior

`core-api` (which contains the type used in the import statement) should be on the TAPI client's classpath when the test runs and should work.

### Steps to Reproduce

see above

### Gradle version

any

**Comment by donat** [comment]
This is the expected behaviour. The cross-version tests use the classpath of the currently tested tooling API version, without knowing anything about Gradle internals (including `core-api`).
