### ISSUE TITLE
`OrElseProvider` and `OrElseFixedValueProvider` sometimes prematurely evaluate artifact transforms

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#29847]
### Current Behavior

If you use `OrElseProvider` and `OrElseFixedValueProvider` in a provider chain, it sometimes prematurely evaluates artifact transforms.

### Expected Behavior

Artifact transforms should not be evaluated prematurely.

### Context (optional)

This is similar to the problems in #27372.
Those were fixed between 8.8 and 8.9-rc-2.
If you for example use the third variant in the MCVE, it fails with 8.8 but works with 8.9-rc-2.
If you use the other two, it still fails with 8.9-rc-2.

### Steps to Reproduce

settings.gradle.kts
```kotlin
include("app", "lib")
```

lib/build.gradle.kts
```kotlin
plugins { id("java-library") }
```

app/build.gradle.kts
```kotlin
plugins { id("java-library") }

abstract class IdTransform : TransformAction<TransformParameters.None> {
    @get:InputArtifact
    abstract val inputArtifact : Provider<FileSystemLocation>
    override fun transform(outputs: TransformOutputs) { outputs.file(inputArtifact) }
}
val transformed = Attribute.of("transformed", Boolean::class.javaObjectType)
configurations.runtimeClasspath { attributes.attribute(transformed, true) }
dependencies.artifactTypes.maybeCreate("jar").attributes.attribute(transformed, false)
dependencies.registerTransform(IdTransform::class) {
    from.attributes.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "jar").attribute(transformed, false)
    to.attributes.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "jar").attribute(transformed, true)
}

dependencies { implementation(project(":lib")) }

val foo by tasks.registering {
    // fails with this
    inputs.files(configurations.runtimeClasspath.flatMap { it.elements }.orElse(emptySet()))
    // fails with this
    //inputs.files(configurations.runtimeClasspath.flatMap { it.elements }.orElse(provider { emptySet() }))
    // does not fail with this, but failed in 8.8
    //inputs.files(configurations.runtimeClasspath.flatMap { it.elements })
    doLast {}
}
```

Run: `./gradlew clean foo -i -s`
=> Transform triggers for non existing `lib/build/libs/lib.jar`
=> With #29840 merged, triggers deprecation warning about premature transform execution

### Gradle version

8.9-rc-2

### Build scan URL (optional)

https://gradle.com/s/z6wx2n2qvhwxa

**Comment by alllex** [comment]
The issue is in the backlog of the relevant team, but the existence of a workaround means it might take a while before a fix is made.
