### ISSUE TITLE
Missing Groovy DSL snippets in Writing Build Scripts chapter

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#29885]
### Current Behavior

The following [snippet](https://docs.gradle.org/current/userguide/writing_build_scripts.html#5_register_and_configure_tasks) has no Groovy DSL version:

<img width="1041" alt="Screenshot 2024-07-11 at 6 31 27 PM" src="https://github.com/user-attachments/assets/4d42d800-257d-4b48-8a4f-55de5163e33f">

### Expected Behavior

All code snippets should have Kotlin and Groovy DSL versions, especially when the syntax varies.

### Steps to Reproduce

See [Writing Build Scripts chapter](https://docs.gradle.org/current/userguide/writing_build_scripts.html#5_register_and_configure_tasks).

### Gradle version

At least 8.9 documentation

**Comment by alllex** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

@lkasso, we seem to remember that tutorials were explicitly focused on a single DSL to make them simpler. Is it documented anywhere how we should handle the examples for other DSLs in this case?

**Comment by lkasso** [comment]
Hey folks,
I will go ahead and add Groovy examples to this chapter this week as part of my cleanup effort.

**Comment by MGaetan89** [comment]
Shouldn't this be in the 8.11 RC1 milestone, with #30591 being merged there?
