### ISSUE TITLE
Adaptor Interface for Managing Tests similar to dotnet

### ISSUE THREAD

**Issue by nithinbandaru1** [gradle/gradle#29902]
### Expected Behavior

In dotnet framework there is a defined interface for all different test frameworks that needs to be implemented to perform different operations regarding tests like Discovery/Listing, Parsing, Running etc.

I guess now Gradle handles this by itself checking what kind of test framework is used.

### Advantages

- If in case, there is new test framework that comes in future, then Gradle has to implement some new framework specific code to support it to perform operations like list/find, parse and run the tests.

- This will also make easier for other build tools like Mavan to not have their own custom implementation for each test framework.

- Test explorer for IntelliJ can be easily implemented irrespective of the test frameworks like we see in Visual Studio for .NET and even VS Code for every other language.

- Let's say if Gradle, Maven, IntelliJ defines 3 different interfaces. Test frameworks need to implement 3 different Adaptors for them and nothing else.

- Tests parsing/running/listing operations can be handled by test framework itself as that is the closest place for this logic to be and also better maintainable based on test framework changes.

> Note: 
> 
> Probably all this is already there in Java ecosystem, and I am not aware of it as I am new to Java world coming from dotnet world.   In this case please accept my apologies for the Noice!!

### Current Behavior (optional)

No standard interface defined for test frameworks.

### Context

I think having this interface makes things easier to maintain and also will help in building different tools around these standard interfaces as abstractions without worrying about the framework used underneath.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

There is definitely something interesting in that approach. But I am not sure it would be easy to roll that out in the JVM ecosystem.

**Comment by big-guy** [comment]
This is an interesting idea, but there aren't a lot of new testing frameworks that warrant effort in this feature. We don't plan to implement a common testing interface. 

Most new test engines are built on top of JUnit Jupiter. This is our recommended approach.

IntelliJ also delegates test execution/reporting to Gradle's Tooling API, which is generic for the underlying testing framework already.
