### ISSUE TITLE
[RESOLVED] the custom property is not getting recognized in dependency block

### ISSUE THREAD

**Issue by Outfit8TSB** [gradle/gradle#29920]
### Current Behavior

```
Could not determine the dependencies of task ':shadowJar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Could not find io.papermc.paper:paper-api:${bukkitversion}.
     Required by:
         project :
   > Could not find org.spongepowered:spongeapi:${spongeversion}.
     Required by:
         project :

```

### Expected Behavior

Build a uber jar

### Context (optional)

i wanted to build a minestom jar implementing Bukkit and Sponge

### Steps to Reproduce

i enabled + ran a ./gradlew shadowjar.

### Gradle version

Gradle Wrapper 8.7 (as a groovy build script)

### Gradle version that used to work

Gradle Wrapper 8.7 (as a kotlin build script)

### Your Environment (optional)

github actions bash

**Comment by Outfit8TSB** [comment]
wait a minute, the issue resolved. it was my fault

**Comment by Outfit8TSB** [comment]
sorry, the issue is already solved, it was my fault accidently messing up a dependency block
dependencies {
    implementation 'io.papermc.paper:paper-api:${bukkitversion}'
}
it was supposed to be 'io.papermc.paper:paper-api:' + bukkitversion

**Comment by Outfit8TSB** [comment]
how do i gotta do that? it's already solved! it's not worth making gradle version 8.9 or something. this issue reopening won't make any sense.

**Comment by Outfit8TSB** [comment]
release-notes-decision:no

**Comment by Outfit8TSB** [comment]
pause this issue right now

**Comment by Outfit8TSB** [comment]
this action is not release note-worthy, please ignore the comment

**Comment by ov7a** [comment]
@Outfit8TSB Sorry about the messages from the bot above. This is our automation to catch completed issues that are release-note-worthy. The message was [improved](https://github.com/gradle/issue-management-action/commit/f2816f4f4722b6482439f361d5b933ba98510f78#diff-f06c638959f96919b65cdc866df9c5e35ec663afedcae3ac93635a4451d492baR166-R172) to avoid similar situations in the future
