### ISSUE TITLE
Builds started failing overnight due to "org.ysb33r.gradle:grolifant:0.10" becoming unresolvable

### ISSUE THREAD

**Issue by BonusLord** [gradle/gradle#29927]
### Current Behavior

Gradle builds of our older version branches starting failing with an error about being unable to resolve the `org.ysb33r.gradle:grolifant:0.10` artifact. I'm pretty confident this started happening out of the blue within the last 48 hours.

This is the error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'mimjava'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.ysb33r.gradle:grolifant:0.10.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > gradle.plugin.org.ysb33r.gradle:packer-gradle-plugin:0.3
```

Seems like maybe this artifact got removed from the Gradle plugins repo? Adding `jcenter()` to the `repositories` in the `buildscript` block fixes the problem, but this doesn't seem like a good long-term fix since it sounds like jcenter is defunct? (And the artifact doesn't seem to be present on maven central)

### Expected Behavior

I would expect the plugin to be able to resolve its dependency from the Gradle plugins repo.

### Steps to Reproduce

This minimal `buiild.gradle` is enough to trigger the error:

```
buildscript {
	repositories {
		maven {
			url "https://plugins.gradle.org/m2/"
    		}
	}
	dependencies {

		classpath "gradle.plugin.org.ysb33r.gradle:packer-gradle-plugin:0.3"
	}
}
```

### Gradle version

6.6

### Gradle version that used to work

6.6

**Comment by ov7a** [comment]
This is an expected outcome of JCenter Shutdown. In short, plugin portal redirects to Maven Central now.

See [our blog post](https://blog.gradle.org/portal-jcenter-impact) for more details.

**Comment by BonusLord** [comment]
Ah, thank you, was not aware that switchover was happening.

For anyone else that runs into similar issues without an obvious migration / upgrade path to address them, here's what I came up with as a relatively painless workaround to get things running again:
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  
  dependencies {
    classpath fileTree(dir: 'gradle-lib/jars', includes: ['*.jar'])

    classpath("gradle.plugin.org.ysb33r.gradle:packer-gradle-plugin:0.3") {
      // When Gradle's plugin repo moved from proxying JCenter to proxying Maven Central (happened around 2024/07/16),
      // packer's transitive dependency on grolifant 0.10 became unresolvable, which broke mimjava's gradle build.
      // To resolve the problem, we checked this jar (grolifant-0.10.jar) into VCS under gradle-lib/jars which
      // gets added to the classpath via the "fileTree" statement above. We also have to explicitly exclude it
      // here to prevent gradle from trying to resolve it from a remote maven repo (since that will fail).

      exclude group: "org.ysb33r.gradle", module: "grolifant"
    }
  }
}
```
