### ISSUE TITLE
WorkQueue: Add Kotlin overload for submit

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#29925]
### Expected Behavior

```kotlin
val workQueue: WorkQueue
workQueue.submit<MyWorker> { }
```

### Current Behavior (optional)

```kotlin
val workQueue: WorkQueue
workQueue.submit(MyWorker::class.java) { }
```

### Context

There are already overloads for `named`, `withType` etc. to not use the Java Class.

**Comment by alllex** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by alllex** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by urdak** [comment]
I don't think it's possible to implement the expect behavior, because that overload would require two type parameters:
```kotlin
inline fun <reified S: WorkAction<P>, P: WorkParameters> WorkQueue.submit(noinline parameterAction: P.() -> Unit) =
    submit(S::class.java, parameterAction)
```
Which would result in:
```kotlin
workQueue.submit<MyWorker, MyParams> { }
// or infer MyParams using the underscore operator for type arguments
workQueue.submit<MyWorker, _> { }
```
Gradle already generates this extension function:
```kotlin
/**
 * Kotlin extension function taking [kotlin.reflect.KClass] for [org.gradle.workers.WorkQueue.submit].
 *
 * @see org.gradle.workers.WorkQueue.submit
 * @since 5.6
 */
inline fun <T : org.gradle.workers.WorkParameters> org.gradle.workers.WorkQueue.`submit`(`workActionClass`: kotlin.reflect.KClass<out org.gradle.workers.WorkAction<T>>, `parameterAction`: org.gradle.api.Action<in T>): Unit =
    `submit`(`workActionClass`.java, `parameterAction`)

```
So it's already possible to just use the `KClass`:
```kotlin
workQueue.submit(MyWorker::class) { }
```
This seems like a better API than using the reified type.

**Comment by hfhbd** [comment]
@urdak thank your for your answer. I wasn't aware of the KClass overload. I agree, the KClass parameter is better than two generic parameters (or the underscore).

**Comment by ov7a** [comment]
@urdak Thanks for providing the context!
