### ISSUE TITLE
github actions are opening issues when it was resolved

### ISSUE THREAD

**Issue by Outfit8TSB** [gradle/gradle#29921]
This issue looks release-note worthy, but no PR with release-notes update has been found.
Please, do one of the following:

1. Attach a PR with the release notes update to this issue.
2. Add the `has:release-notes-decision` label to the issue if it's not release-note-worthy or it was fixed in an old release.

After that, close the issue.

_Originally posted by @github-actions[bot] in https://github.com/gradle/gradle/issues/29920#issuecomment-2230374065_

**Comment by Outfit8TSB** [comment]
the issue was resolved by closing as not planned

**Comment by ov7a** [comment]
[Fixed](https://github.com/gradle/issue-management-action/commit/f2816f4f4722b6482439f361d5b933ba98510f78#diff-f06c638959f96919b65cdc866df9c5e35ec663afedcae3ac93635a4451d492baR166-R172) by improving the message.

**Comment by Outfit8TSB** [comment]
thank you
