### ISSUE TITLE
Gradle cannot use TLSv1.2 for HTTPS with IBM Java/JDK/JRE

### ISSUE THREAD

**Issue by nathan-hughes** [gradle/gradle#2993]
DefaultSslContextFactory doesn't really call the default provider, it calls the first provider of "TLS" to do SSL connections.

The problem is that the SSLContext is initialized to use "TLS". It seems like the same provider provides TLS, TLSv1.1 and TLSv1. support in Sun Java. In IBM Java, TLS in one provider, but TLSv1.2 and maybe TLSv1.1 is in another. Gradle should respect the default chosen by the java.security file and the system properties set by the user.

Originally reported on the forums:
https://discuss.gradle.org/t/gradle-cannot-use-tlsv1-2-for-https-with-ibm-java-jdk-jre/17551

The issue https://issues.gradle.org/browse/GRADLE-3451 was created but closed due to OP not replying.

We are building using gradle with IBM JDK against a nexus repository; when the repository was configured to use TLS1.2 only, our builds could no longer connect to it. We have had to switch over to the Oracle JDK for builds and the choice to use gradle is getting called into question.

The steps to reproduce from the old issue are still the same. This occurs on JDK 8 as well as on JDK 6 and 7. Tested using gradle 3.4.1. The old issue proposed replacing the current impl with a call to getDefault(), which is not ideal due to the JVM caching the SSLContext, so the gradle daemon can end up using a stale copy.

**Comment by Naveen427** [comment]
Hi, 
Same issue for IBM JDK 8 with Gradle 4.6 any suggestions ?

In our environment, we are trying to get/apply init files from GitLab, which is https enabled.
With update version of GitLab TLSv1 is not a supported version, but gradle continue to use TLSv1 and it fails.

**Comment by edoardocomar** [comment]
There is an option to make the IBM JDK behave like the Oracle JDK in terms of the "TLS" protocol string:

	`-Dcom.ibm.jsse2.overrideDefaultTLS=true`    

https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/matchsslcontext_tls.html#matchsslcontext_tls

**Comment by Naveen427** [comment]
hello edoardocomar,

Thank you so much for the suggestion, in deed it is working with the property.

I have updated this property in gradle.properties file  as
org.gradle.jvmargs=-Dcom.ibm.jsse2.overrideDefaultTLS=true

**Comment by AshfaqMemon** [comment]
Hi

I have set the above mentioned in property in my gradle.properties file but it is not taking effect. In the debug log I am not able to see the property is passing on while starting the JVM. Here is my gradle.properties content.
```
org.gradle.daemon=false
org.gradle.jvmargs=-Dcom.ibm.jsse2.overrideDefaultTLS=true -Xmx3g
systemProp.com.ibm.jsse2.overrideDefaultTLS=true
```
I have tried with both, system property and jvmargs but it is not working.

```
Here is the debug log:`
12:55:59.290 [DEBUG] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Using daemon args: [/opt/IBM/WebSphere/AppServer/java_1.8_64/bin/java, -Xmx3g, -Dfile.encoding=UTF-8, -Duser.country=IN, -Duser.language=en, -Duser.variant, -cp, /home/ashfaq/.gradle/wrapper/dists/gradle-4.1-all/bzyivzo6n839fup2jbap0tjew/gradle-4.1/lib/gradle-launcher-4.1.jar]`
```

Here is my gradle version details:

```
------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0 (IBM Corporation 2.8)
OS:           Linux 4.15.0-52-generic amd64
```

**Comment by ljacomet** [comment]
@AshfaqMemon The issue is that you explicitly disable the Gradle daemon.
Because of that, the properties passed through `org.gradle.jvmargs` are ignored, since they are dedicated to the daemon.

**Comment by AshfaqMemon** [comment]
@ljacomet I have also tried with `org.gradle.daemon=true`, but it is also not working.
