### ISSUE TITLE
Wrong JDK version in error message suggestion correction steps

### ISSUE THREAD

**Issue by chali** [gradle/gradle#29978]
### Current Behavior

I have an application with JDK 8 toolchain and I add a dependency that was build with JDK 17 and published gradle metadata. I receive an error with following suggestion:

```
Change the dependency on 'org.springframework.boot:spring-boot:3.3.2' to an earlier version that supports JVM runtime version 17.
```

### Expected Behavior

I believe the suggestion is incorrect because it should say JDK 8 instead 17 like:

```
Change the dependency on 'org.springframework.boot:spring-boot:3.3.2' to an earlier version that supports JVM runtime version 8.
```

### Steps to Reproduce

Reproducer repository https://github.com/chali/java-error

running:
```
./gradlew run
```

### Gradle version

8.8

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

I can reproduce it with 8.9 and the current master.
