### ISSUE TITLE
Ignoring specific environment varibles for caching

### ISSUE THREAD

**Issue by jensbaitingerbosch** [gradle/gradle#29971]
### Expected Behavior

Build results can be cached independent of the values of specified environments.

### Current Behavior (optional)

The whole set of environment variables are used as input for (some) build steps (especially testing). When these variable change, these tests need to be repeated. 

### Context

In the context of a CI server, there are many environment variable, that might change for every build: Build number, current Git commit id, runner id etc ([example github](https://docs.github.com/en/actions/learn-github-actions/variables)). While some tasks are only dependent on the source (e.g. compile) other tasks are dependent on the environment and their result cannot be cached. Especially test tasks cannot be cached and they need a significant amount of time. 

Especially in the case of a merged Pullrequest, where the whole project was built and tested in the PR (by merging the PR branch into the target branch) and then the merged result (which should be exactly the same then the previous test build) this feature would save quite some time in environments, where releases are high frequent.

**Comment by ov7a** [comment]
We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

This issue will be closed after 7 days unless you provide more information.

***

Can you please try using `ValueSource` to provide those environment variables, so they don't "pollute" the state of configuration cache? See this [documentation](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables:~:text=Example%202%3A%20Reading%20environment%20variables%20for%20consumption%20at%20execution%20time%3A).

If it doesn't work, can you please share a small reproducer to us for investigation?

Related:
* https://github.com/gradle/gradle/issues/20873

**Comment by viluon** [comment]
I think the requirement is pretty clear: Gradle cannot reuse the configuration cache if any environment variables have changed. Environment variables always change in CI environments. Therefore, the configuration cache is (near?) useless for CI.

I don't know whether that's still true if no tasks use the Java API for reading env vars[^1]. The documentation page @ov7a linked to no longer exists and the provider example is [gone from the 8.11 version](https://docs.gradle.org/8.11/userguide/build_environment.html). [Here's a permalink](https://docs.gradle.org/8.6/userguide/build_environment.html#sec:gradle_environment_variables) to the 8.6 page which includes the small tutorial.

By the way, neither the 8.11 docs nor [gradle/actions](https://github.com/gradle/actions) seem to warn about this. Perhaps that's worth its own issue?

[^1]: The builds I'm currently dealing with are a bit too complex to ensure that doesn't happen in any transitive task dependencies. I was looking for a smarter way to manage this and stumbled upon this issue.

**Comment by viluon** [comment]
Nevermind, after switching existing `System.getenv()`-based environment checks in tasks to use environment variable providers instead but this still fails to reuse the configuration cache:

```
Calculating task graph as configuration cache cannot be reused because environment variable 'ATUIN_HISTORY_ID' has changed.
```

Am I missing something obvious? Is invalidating the configuration cache on unrelated env var changes the expected behaviour[^1]?

[^1]: `ATUIN_HISTORY_ID` changes with every command. No tasks depend on this variable via an environment variable provider.
