### ISSUE TITLE
ConcurrentModificationException after update from 8.8 to 8.9

### ISSUE THREAD

**Issue by Keymaster65** [gradle/gradle#29986]
### Current Behavior

The build using v8.9 has a FAILURE.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':connector-api:compileJava'.
> Could not resolve all dependencies for configuration ':connector-api:compileClasspath'.
   > Could not resolve project :copper2go-api.
     Required by:
         project :connector-api
      > java.util.ConcurrentModificationException (no error message)

### Expected Behavior

Build should not fail.

### Context (optional)

I updated from v8.8 to v8.9. v8.8 work fine.

### Steps to Reproduce

Use Zulu JDK 22.0.1 or JDK 22.0.2 for Build on Branch "updateGradle_8_9"
https://github.com/Keymaster65/copper2go/tree/updateGradle_8_9

### Gradle version

8.9

### Your Environment (optional)

github pipeline:
https://github.com/Keymaster65/copper2go/blob/updateGradle_8_9/.github/workflows/build.yml

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by jvandort** [comment]
Can you please post a stack trace either by linking build scan or running with `—-stacktrace`?

**Comment by Keymaster65** [comment]
Here is the log with --stacktrace.
[log.txt](https://github.com/user-attachments/files/16332082/log.txt)

**Comment by Keymaster65** [comment]
Add here the --scan link: https://gradle.com/s/ccemr2ptsxt26

**Comment by jvandort** [comment]
Does the build reliably reproduce this failure?

are you using configuration cache?

**Comment by jvandort** [comment]
This might go away if you turn off org.gradle.parallel

**Comment by Keymaster65** [comment]
> Does the build reliably reproduce this failure?
> 
> are you using configuration cache?
It happens always. I am not aware of a special configuration cache.

**Comment by Keymaster65** [comment]
> This might go away if you turn off org.gradle.parallel

No, I still happens even without org.gradle.parallel

**Comment by Keymaster65** [comment]
1) Plugins are up to date. 
2) CC enabling shows same exception

**Comment by jvandort** [comment]
Can you post a build scan link with CC enabled?

**Comment by Keymaster65** [comment]
If I remove the plugin "info.solidsoft.pitest" the build works.

**Comment by jvandort** [comment]
It will realistically take some time for us to work through this issue unless you are able to provide a more targeted reproducer

**Comment by Keymaster65** [comment]
Ok, I will try to reduce the problem.

**Comment by Keymaster65** [comment]
The problem is reduced to the alwmost empty project
https://github.com/Keymaster65/copper2go/tree/reduceGradle_8_10

ConcurrentModificationException happens if

1. pitest ist contained
2. and test-sets ist contained
3. and two (empty) depending modules are contain

If removing 1 of these three point, no ConcurrentModificationException occurs ny more.

**Comment by jvandort** [comment]
Are you able to further reduce this to a reproducer that does not apply the plugins? I.e. by looking at the source of these plugins and seeing what they are doing?

And can you provide a build scan with the new reproducer?

**Comment by Keymaster65** [comment]
I can create a scan tomorrow. Without apply, there is no exception.

**Comment by jvandort** [comment]
Yeah something those plugins are doing are contributing to the error. Figuring out what is going on here would require figuring out what code in the plugins causes the problem

**Comment by Keymaster65** [comment]
The --scan link: https://gradle.com/s/jmscf3ycmpcly

**Comment by jvandort** [comment]
Can you run this with CC enabled?

**Comment by jvandort** [comment]
I have reason to believe the pitest plugin is the root cause here, though without the "other side" of the CME I cannot be really sure. 

This code here is doing some suspicious stuff:
https://github.com/szpak/gradle-pitest-plugin/blob/master/src/main/groovy/info/solidsoft/gradle/pitest/PitestPlugin.groovy#L252-L292

**Comment by jvandort** [comment]
If you disable the `addJUnitPlatformLauncher` functionality in pitest does the CME go away?

**Comment by Keymaster65** [comment]
With CC link: https://gradle.com/s/nlysedfnyykfw

**Comment by Keymaster65** [comment]
> If you disable the `addJUnitPlatformLauncher` functionality in pitest does the CME go away?

Congratulations!!!

This works for the reducted version:
    pitest {
        addJUnitPlatformLauncher = false
    }

**Comment by Keymaster65** [comment]
Thanx for support. I'll test it in the original project.

**Comment by Keymaster65** [comment]
Ok, I found the experimental note in
https://github.com/szpak/gradle-pitest-plugin/releases
and added
        testRuntimeOnly("org.junit.platform:junit-platform-launcher") {
            because("required for pitest")
        }

So it is still not perfect for me, but I think it is in issue in pitest now.

Thanx again for your. Support.

**Comment by Keymaster65** [comment]
Strange, that it worked fine in gradle 8.8, but I think it is proven an issue in pitest experimental feature.
