### ISSUE TITLE
gradle 4.2 - play 2.6.x - scala 2.11

### ISSUE THREAD

**Issue by vkokurin** [gradle/gradle#2999]
I have a problem starting with play 2.6, but scala 2.11 just by running gradle playRun:

> Failed to run Play
> org.gradle.internal.UncheckedException: java.lang.NoSuchMethodException: play.core.server.DevServerStart$.mainDevHttpMode(play.core.BuildLink, play.core.BuildDocHandler, int, java.lang.String)
> 

By looking into PlayRunAdapterV26X I see that it just extends PlayRunAdapterV24X which calls that mainDevHttpMode with reflections while using wrong arguments.

In change logs its written that there is a support to 2.6.x play versions, but I cannot just run the server. Maybe I am doing smthg wrong?

**Comment by bmuschko** [comment]
Could you please provide reproducible sample project?

**Comment by nberthet** [comment]
Hi @bmuschko, I confirm having the same issue.

It looks like the updated plugin works just fine with Play < 2.6, but as soon as you set the platform to 2.6 the server cannot be started. A method signature was changed, and it is not reflected in PlayRunAdapterV26X as pointed out by @vkokurin 

To reproduce, just create an empty project:
```
apply plugin: 'play'

model {
    components {
        play {
            platform play: '2.6.5'
        }
    }
}
```

Then, `gradlew runPlay` while fail and throw the exception mentioned above.

**Comment by nberthet** [comment]
For reference - https://github.com/playframework/playframework/commit/7bf7571c6997761baff79a0e89b08f9f5525b08f#diff-58bf6474fbdd7970aeb1630b24c9f7e2

**Comment by vkokurin** [comment]
@nberthet yes I have exactly same configuration.

**Comment by kknd22** [comment]
I encountered a similar issue - BTW, is there a bare bone sample project to illustration gradle 4.2 play 2.6.5(x) actually works? 

-cl

**Comment by marcospereira** [comment]
Hi, @bmuschko.

This is a reproducer: https://github.com/marcospereira/play-java-starter-example

See more info at this specific commit:

https://github.com/marcospereira/play-java-starter-example/commit/d9cb6fab92a83bc12a73463e83f65ae9b415fc10

Best.

**Comment by marcospereira** [comment]
Also, see #3018 for a (possible) fix.

**Comment by vkokurin** [comment]
Is there any workaround available guys with current gradle version? (4.2.1)

**Comment by kknd22** [comment]
I am very interested for it as well - it is kind of a showstopper for us ...

https://github.com/gradle/gradle/releases/tag/v4.2.0-RC1  

> ...Play framework support is upgraded in Gradle 4.2: **Play v2.6**, built-in Twirl template types and user-defined Twirl formats are now supported....

**Comment by vkokurin** [comment]
@kknd22 well sbt is always there

**Comment by kknd22** [comment]
yes, I am aware of it and thanks for pointing it out - however, our build/ci/cd pipeline are all in gradle and build scala are just part of whole thing - there are many other aspects (other non scala code) of the build It is impractical change to using mixing gradle/sbt because of this defect..

**Comment by lu4nm3** [comment]
Is this fix scheduled to be released anytime soon? It has become a blocker for us

**Comment by marcospereira** [comment]
@lu4nm3, you can see the progress at #3018.

**Comment by marcospereira** [comment]
@vkokurin, @nberthet, @kknd22 and @lu4nm3, 

Gradle 4.4 RC1 is out with a fix for this issue. Could you please try and report that it is working as expected?

Thank you!

**Comment by nberthet** [comment]
Hi @marcospereira, sorry for the lack of feedback, I've been using the 4.4 nightly as soon as the update has been merged, on my end everything works fine

Thank you for the update and follow up !

**Comment by lu4nm3** [comment]
@marcospereira Sorry for the late reply. Started using the RC yesterday and everything appears to be working well on my end. Thank you for all the hard work!
