### ISSUE TITLE
Can't dynamically apply a plugin

### ISSUE THREAD

**Issue by NinoDLC** [gradle/gradle#30001]
### Current Behavior

Using:
```
def foo = true

plugins {
    if (foo) {
        alias(libs.plugins.firebase.perf)
    }
    alias(libs.plugins.android.application)
}
```

throws errors `Only 'buildscript', 'pluginManagement', and 'plugins' are allowed before 'plugins'`.

Meanwhile, the previous API allowed it: 
```
def foo = true

if (foo) {
    apply plugin: 'com.google.firebase.firebase-perf'
}
apply plugin: 'com.android.application'
```

### Expected Behavior

Allow us to dynamically load plugins in the `plugins {}` block or allow us to [disable a previously loaded plugin](https://github.com/gradle/gradle/issues/19248)

### Steps to Reproduce

Write this to a build.gradle file
```
def foo = true

plugins {
    if (foo) {
        alias(libs.plugins.firebase.perf)
    }
    alias(libs.plugins.android.application)
}
```

### Gradle version

8.2

### Gradle version that used to work

1 I guess ?

**Comment by alllex** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

The `plugins` block is intentionally limited in the functionality it supports to provide further features in the build script.

If you would like to apply the plugin dynamically, consider using the [`PluginManager` API](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginManager.html#apply(java.lang.String)), which you can access on the Project instance [via `getPluginManager()`](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/PluginAware.html#getPluginManager()).
