### ISSUE TITLE
`uploadArchives` task tries to publish generated POM twice

### ISSUE THREAD

**Issue by saksmt** [gradle/gradle#3003]
`uploadArchives` task tries to publish generated POM (maybe not only POM) twice

### Expected Behavior
It should publish artifacts only once

### Current Behavior
It dies on second attempt due to 409 (Conflict)

### Context
Just trying to publish my project to corporate artifactory

#### As sample project

[Link](https://github.com/saksmt/gradle-publish-issue-3003)

#### As snippet

`publish-jars.gradle`:
```groovy
task sourcesJar(type: Jar) {
    classifier = 'sources'
    from sourceSets.main.allSource
}

build.dependsOn(sourcesJar)

artifacts {
    archives sourcesJar
}

uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: 'releases repo') {
                authentication(
                    userName: rootProject.properties.get('artifactory.username'),
                    password: rootProject.properties.get('artifactory.token')
                )
            }

            snapshotRepository(url: 'snapshots repo') {
                authentication(
                    userName: rootProject.properties.get('artifactory.username'),
                    password: rootProject.properties.get('artifactory.token')
                )
            }
        }
    }
}

def installer = install.repositories.mavenInstaller
def deployer = uploadArchives.repositories.mavenDeployer

[installer, deployer]*.pom*.whenConfigured { pom ->
    pom.project {
        packaging 'jar'
    }

    pom.withXml {
        asNode().dependencies.'*'.each {
            if (it.scope*.value != null) {
                it.scope*.value = 'compile'
            }
        }

        asNode().dependencyManagement.dependencies.'*'.each {
            if (it.scope*.value != null) {
                it.scope*.value = 'compile'
            }
        }

        def repos = asNode().appendNode('repositories')

        project.repositories.findAll { it.name != 'MavenLocal' }.each {
            def repo = repos.appendNode('repository')
            repo.appendNode('id', it.name)
            repo.appendNode('name', it.name)
            repo.appendNode('url', it.url)
        }
    }

    if (project.hasProperty('pomConfigurer')) {
        pom.withXml(pomConfigurer)
    }
}

install.dependsOn build
uploadArchives.dependsOn build

task 'publish-snapshot'() {
    dependsOn uploadArchives
}

task publish() {
    dependsOn uploadArchives
}
```

Module with POM (`parent`):
```groovy
dependencyManagement {
    generatedPomCustomization {
        enabled = true
    }
}

ext.pomConfigurer = {
    // some pom configuration
}
```

Root `build.gradle`:
```groovy
allprojects {
  apply plugin: 'maven'
  apply plugin: 'io.spring.dependency-management'
}

subprojects {
  apply from: file('publish-jars.gradle')
}
```

Output:
```
> Task :my-project:parent:uploadArchives
Could not transfer artifact groupname:parent:pom:2.1.1-rc20 from/to remote (https://releases repo): Failed to transfer file: https://releases repo/groupname/parent/2.1.1-rc20/parent-2.1.1-rc20.pom. Return code is: 409, ReasonPhrase: Conflict.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':my-project:parent:uploadArchives'.
> Could not publish configuration 'archives'
   > Failed to deploy artifacts: Could not transfer artifact groupname:parent:pom:2.1.1-rc20 from/to remote (https://releases repo): Failed to transfer file: https://releases repo/groupname/parent/2.1.1-rc20/test-parent-2.1.1-rc20.pom. Return code is: 409, ReasonPhrase: Conflict.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
```

### Your Environment
Tested on TeamCity (rhel7) and local machine with Gentoo.
Tested with gradle versions (through `gradlew`): 3.5, 4.2
Dependency management plugin (don't really think that it causes problems, but still): 1.0.1.RELEASE

**Comment by bmuschko** [comment]
Thanks for providing code snippets. Could you please provide a sample project on GitHub that can directly execute?

**Comment by saksmt** [comment]
@bmuschko, Sorry for long reply (weekend after all 😄  ). Here is sample project where this bug reproduces: [click](https://github.com/saksmt/gradle-publish-issue-3003)

**Comment by saksmt** [comment]
Any progress on this?

**Comment by marcphilipp** [comment]
@saksmt Thanks for providing the sample project! I've cloned it and can reproduce the bug locally. Can you please describe your use case? It looks like you want to publish a BOM from the `pom` subproject, correct? However, it looks like it (accidentally?) also publishes a sources JAR.

**Comment by marcphilipp** [comment]
I've looked into this a bit further. Here's what actually happens:

1. The first upload actually transfers the project's `jar` file
1. The second upload attempts to overwrite the just uploaded file with the generated POM

**Comment by marcphilipp** [comment]
The [documented way to set the packaging](https://docs.gradle.org/current/userguide/maven_plugin.html#sec:maven_pom_generation) is on the `MavenPom` object:

> Note: groupId, artifactId, version, and packaging should always be set directly on the pom object.

However, setting it to `pom` like in the following example does not work. The packaging will actually get overridden with the type (extension) of the first artifact without a classifier (usually `jar`, `war` etc.).

```gradle
[installer, deployer]*.pom {
    packaging = 'pom'
}
```

Thus, it looks like the use case of uploading a POM without any artifacts was never really considered or supported.

**Comment by saksmt** [comment]
Yeah, that's actually is my use-case - generation of parent POM/BOM, but that code is actually is in *multi*-module project which inherits common behavior of publishing jars and sources, which in my opinion should not be blocker for modifying original POM to have `pom` packaging and I could not find a way to overcome this issue...

**Comment by bigdaz** [comment]
The `maven` plugin (together with the core `uploadArchives`) are being replaced by the `maven-publish` plugin. As such, we don't plan on making changes to improve the (now legacy) `MavenInstaller` or `MavenDeployer`. Please switch your projects to use the `maven-publish` plugin, letting us know if there is something missing that prevents you from migrating.

Expect to see the legacy types deprecated in Gradle 6.x, for possible removal in Gradle 7.0.
