### ISSUE TITLE
Project dependencies can be observed outside of Configuration Cache fingerprinting

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#30043]
Running `./gradlew :docs:userguideSinglePageHtml` in the `gradle/gradle` build with Configuration Cache (already enabled) fails with the following error:

```
Caused by: java.lang.IllegalStateException: Unexpected project dependency observed outside of fingerprinting: consumer=:docs, target=:docs-asciidoctor-extensions
```

Build scan: https://ge.gradle.org/s/qxflkokqj6cn4

---

PR that introduced the related change: https://github.com/gradle/gradle/pull/29601

**Comment by lkasso** [comment]
I am getting this in 8.10RC1 when running most documentation tasks:

```
* What went wrong:
Execution failed for task ':docs:userguideMultiPage'.
> Could not resolve all dependencies for configuration ':docs:detachedConfiguration5'.
   > Unexpected project dependency observed outside of fingerprinting: consumer=:docs, target=:docs-asciidoctor-extensions

```

https://ge.gradle.org/s/clxiaenrdt5x6

**Comment by madhead** [comment]
If you absolutely need to build the docs, change the wrapper version to something older:

```
./gradlew wrapper --gradle-version 8.10-20240722004758+0000 --distribution-type bin
```

I was able to start the docs build with this. Of course do not commit that change.

**Comment by alllex** [comment]
Another workaround is to not use CC for the task before the issue is fixed
`./gradlew :docs:userguideSinglePageHtml --no-configuration-cache`

**Comment by alllex** [comment]
The error happens
- At execution time, when the Asciidoctor task's inputs are fingerprinted
- This triggers [a dependency substitution](https://github.com/gradle/gradle/blob/c49894356719acd184d87e53c638bc57911441d8/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/dependencysubstitution/DefaultDependencySubstitutions.java#L469) to resolve its target [as a project dependency](https://github.com/gradle/gradle/blob/a71bf5f2d67e294973a4bfde1d5aac9498ef123c/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/DefaultComponentSelectorConverter.java#L56)
  - the plugin uses [detached configurations](https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/34f2cf13abec169ca7e4e3c0b666a3ba46848260/jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy#L753-L758) in that bit
- which makes `:docs` project observe another `:docs-asciidoctor-extensions` project
- which fails, because CC fingerprint writer is in the `Paused` state and does not, currently, expect any dependencies to be observed

The resolution is to ignore project dependencies observed outside of configuration time, because the work graph has already been stored and/or loaded by CC.
