### ISSUE TITLE
Improve documentation for Settings.include and link this in the name deprecation

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#3008]
### Expected Behavior

settings.gradle:
```
include 'subprojects/sub1'
include 'subprojects/sub2'
include 'subprojects/sub3'

rootProject.children.each { project ->
    int slash = project.name.indexOf('/')
    String fileBaseName = project.name[(slash + 1)..-1]
    String projectDirName = project.name
    project.name = fileBaseName
    project.projectDir = new File(settingsDir, projectDirName)
    project.buildFileName = "${fileBaseName}.gradle"
}
```
There shouldn't be a deprecation warning about using a `/` in subproject names because Gradle never sees those names in practice. 

### Current Behavior

There's a deprecation warning per subproject.

### Context

We added a deprecation message for projects that used discouraged characters (#2775), but this check is applied too early.

We should also consider introducing #751

**Comment by oehme** [comment]
The deprecation is still valid here I think, `include` was never meant to be called with slashes. Users should do it the other way round: 

```
include 'sub1' 

projects.sub1.projectDir = 'subprojects/sub1'
```

We need to improve the documentation for that.

**Comment by oehme** [comment]
The missing documentation for this might be reason enough for 4.2.1.

**Comment by aalmiray** [comment]
@oehme I disagree with your conclusion, your proposal works _if_ all projects are specified by hand, but will fail when contextual information is required, such as

    ['common', 'full', 'light', 'docs'].each { name ->
        File subdir = new File(rootDir, name)
        subdir.eachDir { dir ->
            File buildFile = new File(dir, "${dir.name}.gradle")
            if (buildFile.exists()) {
                include "${name}/${dir.name}"
            }
        }
    }

    rootProject.name = 'e2e'
    rootProject.children.each { project ->
        int slash = project.name.indexOf('/')
        String fileBaseName = project.name[(slash + 1)..-1]
        String projectDirName = project.name
        project.name = fileBaseName
        project.projectDir = new File(settingsDir, projectDirName)
        project.buildFileName = "${fileBaseName}.gradle"
        assert project.projectDir.isDirectory()
        assert project.buildFile.isFile()
    }

@big-guy suggests moving the check to a later time, given that the current behavior is a deprecation warning rather than a build failure I'd think his assessment is more helpful.

**Comment by oehme** [comment]
@aalmiray instead of calling include with the wrong name and correcting it later you can call it with the name you want and set the project dir. This works in a more dynamic case like yours too:
```
["common", "etc"].each { topLevel->
  topLevel.eachDir { dir ->
    include dir.name
    projects(dir.name).projectDir = dir
  }
}

**Comment by aalmiray** [comment]
I suppose so. `settings.gradle` now looks like this https://github.com/griffon/griffon/commit/3d50bf1c95d8c3e6b0c3145e5447ce56d70c7e65

**Comment by big-guy** [comment]
@oehme I shouldn't have tried to write this before jumping on a plane :)

I think it would be OK if we produced a deprecation warning about `/` that said you should be using a different API (e.g., `void includeSubproject(File projectDir)` or something that makes it easy to use relative paths) vs the current non-actionable "your name contains deprecated characters".

**Comment by bmuschko** [comment]
> The missing documentation for this might be reason enough for 4.2.1.

@oehme At the moment I am bit on the fence whether we need a patch release just for documenting this. If everything goes well then we'll release the 4.3-RC1 in 3 weeks. I'd be happy to improve documentation with that version. My gut feeling is that the user base running into this issue is rather small. Plus it's only a deprecation - nothing should _break_ at the moment.

**Comment by jjohannes** [comment]
PR that adds hint to deprecation warnings and more documentation about `include`: #3056
