### ISSUE TITLE
Develocity retry configuration API reference link 404s

### ISSUE THREAD

**Issue by adam-enko** [gradle/gradle#30113]
### Issue type

Wrong or misleading information

### Problem description

> See the [retry configuration API reference](https://docs.gradle.com/develocity/gradle-plugin/api/com/gradle/develocity/agent/gradle/test/TestRetryConfiguration.html).

The link https://docs.gradle.com/develocity/gradle-plugin/api/com/gradle/develocity/agent/gradle/test/TestRetryConfiguration.html 404s.

### Page with the problem

https://docs.gradle.com/develocity/gradle-plugin/current/#configuration

**Comment by ov7a** [comment]
Indeed, there is a broken link, we'll fix that soon.
