### ISSUE TITLE
Could not determine java version from '9.0.0.15'

### ISSUE THREAD

**Issue by automenta** [gradle/gradle#3013]
when trying "azul zulu" jdk9:

```
openjdk version "9.0.0.15"
OpenJDK Runtime Environment (Zulu build 9.0.0.15+181)
OpenJDK 64-Bit Server VM (Zulu build 9.0.0.15+181, mixed mode)
```

> What went wrong:
> Could not determine java version from '9.0.0.15'.

if this cant be fixed maybe the error message could at least indicate **why the version string even matters** if it even does.

```
java.lang.IllegalArgumentException: Could not determine java version from '9.0.0.15'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:72)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:82)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:42)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)

```

### Your Environment

 * Build scan URL:

**Comment by blindpirate** [comment]
Duplicate with #2992 .

**Comment by AdrianWang** [comment]
same thing happened to me...

**Comment by blindpirate** [comment]
@AdrianWang You'd use Gradle 4.2.1 + on JDK 9.

**Comment by LucasMembrane** [comment]
I've got Gradle 4.4.1 and it happens to me, too:

Error Error initializing classpath: Could not determine java version from '9.0.1'. (Use --stacktrace to see the full trace)
[18:17 al ~/.../groovy_tuts/helloworld]$ gradle --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/al/.linuxbrew/Cellar/gradle/4.4.1/libexec/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          9.0.1 (Oracle Corporation 9.0.1+11)
OS:           Linux 4.14.11-200.fc26.x86_64 amd64

Any ideas???

**Comment by fragaLY** [comment]
@LucasMembrane 
Could you please update your JDK to 9.0.4 version.
Also check is your environment variable correct.

Could you please let me know if it helped you?

**Comment by LucasMembrane** [comment]
Thanks for the heads-up, but not much progress from what I could tell.  I had sort of moved on to other things,  but I updated jdk to 9.0.4 by downloading and installing the rpm, went back and installed groovy and grails, downloaded a grails example app.  Still, I got this:


[22:20 al ~/.../groovy/myapp]$ ./grailsw run-app
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/home/al/.grails/wrapper/grails-wrapper.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Resolving dependencies...................................................................................................
| Error Error initializing classpath: Could not determine java version from '9.0.4'. (Use --stacktrace to see the full trace)

**Comment by bmuschko** [comment]
@LucasMembrane I am not quite sure but Grails may ship with a specific version of Gradle (or rather the Wrapper) that does not include the relevant fix. Can you run `./gradlew version` and provide the output? At this point it may be helpful if you could provide us with a sample project that reproduces the issue. Thanks.

**Comment by emmanuj** [comment]
It appears Grails is using 3.5 wrapper.

`#Fri Nov 27 23:09:32 CET 2015
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-bin.zip`

**Comment by emmanuj** [comment]
You can follow the instructions [here](http://mrhaki.blogspot.com/2016/01/grails-goodness-changing-gradle-version.html) to change your gradle distribution for Grails if that's what you're looking for.

**Comment by cesards** [comment]
Using Gradle 4.5 fixes the problem :-) You just need to change the distribution url:

```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.5-bin.zip
```

**Comment by automenta** [comment]
`Could not determine java version from '11-ea'.`

:trophy:
