### ISSUE TITLE
Wrong command output

### ISSUE THREAD

**Issue by bibhas2** [gradle/gradle#30149]
### Issue type

Wrong or misleading information

### Problem description

The ``gradle init`` command output shown on this page has a problem. It shows ``3`` as the option for ``library`` type. 

```
Select type of project to generate:
  1: basic
  2: application
  3: library
  4: Gradle plugin
```

The actual output from the command looks like this where ``2`` is the option for ``library``.

```
Select type of build to generate:
  1: Application
  2: Library
  3: Gradle plugin
  4: Basic (build structure only)
```

### Context (optional)

Gradle version info:

```
------------------------------------------------------------
Gradle 8.8
------------------------------------------------------------

Build time:   2024-05-31 21:46:56 UTC
Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082

Kotlin:       1.9.22
Groovy:       3.0.21
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          22.0.1 (Homebrew 22.0.1)
OS:           Mac OS X 14.2.1 aarch64
```

### Page with the problem

https://docs.gradle.org/current/samples/sample_building_java_libraries.html

**Comment by ov7a** [comment]
This is a valid documentation issue. FTR, We plan to review the list of samples.
