### ISSUE TITLE
.gradle directory in version control

### ISSUE THREAD

**Issue by LaFrimousse** [gradle/gradle#30150]
### Issue type

Wrong or misleading information

### Problem description

In this [section](https://docs.gradle.org/current/userguide/gradle_directories.html#project_root), it is mentioned that the `.gradle` directory is usually checked into source control.  
I think you meant the `gradle` directory, without a dot.

### Page with the problem

https://docs.gradle.org/current/userguide/gradle_directories.html

**Comment by ov7a** [comment]
This is already addressed in 
* https://github.com/gradle/gradle/pull/30058
It's in master, but cherry-picking it to release so it's available faster:
* https://github.com/gradle/gradle/pull/30154
