### ISSUE TITLE
[8.8] new Daemon JVM feature incompatible with android; needs additional criteria

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#30153]
### Current Behavior

The only daemon jvm critieria is major version. This is sufficient for most cases, but there are a couple of issues:

- Builds are still not fully reproducible. If the gradle daemon starts from IntelliJ, the JBR distribution of java from my installed Intellij application is selected. But, if I start from terminal, a temurin distribution installed to my `Library/Java/JavaVirtualMachines` folder is selected. 
- The AGP is not compatible with the selected daemon jvm from Intellij:

```
Caused by: java.lang.IllegalArgumentException: jlink executable /Users/matthewgroth/Applications/IntelliJ IDEA Ultimate.app/Contents/jbr/Contents/Home/bin/jlink does not exist.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
	at com.android.build.gradle.internal.dependency.JdkTools$jlinkVersion$2.invoke(JdkImageTransformDelegate.kt:152)
```

### Expected Behavior

We should have additional criteria to control the selected jvm. At minimum (and this would go a very long way), allow us to specify a distribution. If I could just say "temurin", that would be enough to resolve all my issues.

### Steps to Reproduce

1. Create a project with gradle 8.8
2. Specify the daemon jvm as 21 in `gradle-daemon-jvm.properties`
3. Configure the project as an android project
4. Run `gradle --stop` to kill all daemons, then try to build an android app from IntelliJ
5. Observe the error
6. Repeat step 4, but from the command line
7. Observe no error

### Gradle version

8.8

### Your Environment (optional)

Mac OS 14.5

**Comment by rpalcolea** [comment]
This is coming as part of 8.10 :) https://github.com/gradle/gradle/pull/28931
