### ISSUE TITLE
Need to delete .gradle, otherwise terminates with main-class not found

### ISSUE THREAD

**Issue by frankbenoit** [gradle/gradle#3015]
I start gradle 4.0.1 over the wrapper.
And i get the message the main class org.gradle.wrapper.GradleWrapperMain is not found.  
But in fact the jre and classpath are perfectly ok, and the referred gradle-wrapper.jar contains this class.

When i delete the ".gradle" folder, it works for one build. Before the next call, i need again to delete this folder.

Currently i don't  know how to get more information. Can you please instruct me?
I did a build-scan, perhaps you can see something from it.

### Expected Behavior

Obviously, it shall work with the created .gradle folder.

### Current Behavior

Run only if I delete the .gradle folder

### Steps to Reproduce (for bugs)

unknown

### Your Environment

 * Build scan URL: https://gradle.com/s/33mfdmwzjdrrk

**Comment by frankbenoit** [comment]
When it is in this state, even deleting the whole content of the ".gradle" does not help.  
But if the empty directory ".gradle" is removed, then it is running again.

**Comment by frankbenoit** [comment]
Same behavior with Gradle 4.2

**Comment by bmuschko** [comment]
Is this only happening on your machine? Could you please ask one of your co-workers? I suspect some environment issue.

**Comment by frankbenoit** [comment]
yes, this is plausible. 
I have had this on another PC as well, but now it is only at one still behaving like that.
Other co-workers never saw this.

My trials are so far:

 - modify the gradlew.bat to give one explicit JRE installation.
 - limit the PATH to only windows/sys32

What else can i try?  
Can I somehow force the wrapper to give more info?

**Comment by laurelcc** [comment]
我遇到了这个同样的问题，在我反复尝试删除项目.gradle文件和本机的.gradle之后同步，仍然无法解决。才开始我怀疑idea的工程文件问题，后来我尝试修改项目gradle目录为3.1版本，再更新gradle命令指定为3.1之后，项目竟然又跑起来了。唉，害苦我了

**Comment by bmuschko** [comment]
Can you provide a reproducible example?

**Comment by bmuschko** [comment]
Given that it seems to work when deleting the Gradle user home directory did you try to set a different Gradle user home directory? Maybe try a shorter path?

**Comment by laurelcc** [comment]
之前碰到过两种情况：第一种，在idea的Run和Debug模式下，直接报“无法找到可供运行的主类”错误；第二种，在Debug模式下报“找不到org.springframework.boot”的相关引用类。环境情况是之前版本是3.1，在另外一台机子上更新到了4.2，然后这两个版本之间总有一个是有问题的，在我尝试了删除项目内的.gradle和mac上的/usr/local/bin下的.gradle都没有解决。索性将gradle环境安装回3.1又正常了

**Comment by bigdaz** [comment]
I'm closing this issue as it does not provide enough information. Please understand that we receive lots of issues and need to focus on the ones that are actionable. Here are some ways to make your issue actionable, in order of preference:

1. Provide a full reproducible example project (either as an archive or as a Github repo). This makes sure we can easily see the same issue you are experiencing.
2. If a reproducible example is infeasible, please provide detailed instructions on the environment and how to reproduce the issue. 
3. If your environment is too hard to reproduce, you can use `-Dorg.gradle.debug=true` and attach a remote debugger to dig into the Gradle code base. That way you might find the problematic code and we might be able to come up with a unit test.
