### ISSUE TITLE
Suggestion to enable composite build work without determining the included build's path

### ISSUE THREAD

**Issue by almogtavor** [gradle/gradle#30176]
I've developed a Gradle plugin that can be used to prevent a paths references problem of the current Gradle's composite build feature. Currently, composite builds work in such a way that if a team uses this for a common logic project, all of the team members need to clone the common logic project & the projects that use it in the same folder hierarchy. Auto Composite Build allows using Gradle's composite builds feature in a Git-compatible way.

### Expected Behavior

The [Auto Composite Build Plugin](https://github.com/almogtavor/auto-composite-build) features are as follows:
- **Global Module Registration**: The plugin registers shared projects (e.g., common logic libraries) in a global file located in the user's home directory.
- **Flexible Project Structure**: Developers can maintain different directory structures without worrying about breaking the composite build, as the plugin handles the inclusion paths dynamically.
- **Seamless Git Integration**: Since the paths are managed locally, project settings can be safely committed to version control, ensuring consistency across different environments.

### Current Behavior (optional)

Currently, Gradle's composite build feature requires all developers to clone shared projects into identical directory structures. This forces all of the team to structure their projects identically locally since the relative path is getting pushed to Git. The [Auto Composite Build Plugin](https://github.com/almogtavor/auto-composite-build) resolves this by registering projects in a global file on the user's machine, allowing for flexibility in project structure without breaking the composite build functionality.

### Context

An alternative could be to reference a Git URL, but this would cause each project to clone an instance of the included build project, instead of using the actual clone of the project that the user already has.

I suggest to implement this concept within the composite build feature, and if it would help, to use the actual code of Auto Composite Build.

**Comment by cobexer** [comment]
We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

This issue will be closed after 7 days unless you provide more information.

***

The primary suggested way to [share build logic](https://docs.gradle.org/current/userguide/part4_gradle_plugins.html#step_5_exploring_plugins) between separate (git) repositories is via [binary plugins](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_binary.html) published [to an internal](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#sec:publishing_your_plugin) (or external) artifact repository such as Sonatype Nexus or JFrog Artifactory among others.

Can you explain in more detail why this approach does not work for you?

**Comment by almogtavor** [comment]
Thank you for the suggestion, but Gradle plugins are typically used for tasks, whereas my use case involves sharing common application business logic, like internal libraries, that 
developers actively work on while simultaneously developing the applications that use them.
I wasn't referring to build logic, but to application logic, hence the solution regards the composite build feature.

#### The issue with the current composite build feature
The current composite build feature forces all team members to clone the shared library at a specific location relative to the application that uses it, which imposes a rigid directory structure across all team members' machines. The Auto Composite Build Plugin addresses this by enabling flexible project structures without these directory constraints, making collaboration much easier and more efficient.

**Comment by ov7a** [comment]
Sorry, we don't think it should be a core Gradle feature. There are plenty of ways to address this: git submodules. monorepo, snapshot dependencies, etc. And you have a plugin for your specific case. It's more about structuring your code and establishing the developer workflow, not about building the project.

And your case sounds too specific, so implementing it via a plugin is more appropriate.
