### ISSUE TITLE
Support for Dynamic Dependency Versioning Based on Build Environment

### ISSUE THREAD

**Issue by melihxz** [gradle/gradle#30181]
### Expected Behavior

Gradle should provide a mechanism to dynamically resolve and select dependency versions based on the build environment (e.g. development, staging, production), this feature would allow developers to define different dependency versions or configurations for each environment within a single build script or configuration block, example, `implementation("com.example:lib:1.0.0-dev")` for development and `implementation("com.example:lib:1.0.0")` for production, the selection should be automatic based on a specified environment variable or build flag

### Current Behavior (optional)

Currently developers need to manually manage dependency versions for different environments often requiring separate build scripts or complex conditional logic within the build script, this increases the maintenance burden and the potential for errors when switching between environments

### Context

in multi-environment projects, it's common to require different dependency versions or configurations based on the target environment, example, using a lightweight version of a library in development and the full version in production, currently, managing this in Gradle requires custom scripts or manually managing multiple build files, which can be cumbersome and error-prone, this feature would streamline the process, reduce the chance of errors, and improve productivity by making it easier to manage dependencies across environments, i've considered using custom tasks or external plugins, but a built-in solution would be more seamless and widely applicable.

**Comment by ov7a** [comment]
This is already can be achieved via [Modifying metadata on the component level for version selection based on status](https://docs.gradle.org/current/userguide/component_metadata_rules.html#sec:custom_status_scheme).

Another approach may be based on [variants](https://docs.gradle.org/current/userguide/variant_model.html). 

And, as you said, it can be achieved with custom build logic. Someone from the community can pack it as a community plugin. 

However, we think Gradle already has all the required capabilities to achieve what you are asking. Adding this as a core feature would complicate things.
