### ISSUE TITLE
Links in Logging docs not converted from Markdown to HTML

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#30209]
### Issue type

Wrong or misleading information

### Problem description

<img width="996" alt="image" src="https://github.com/user-attachments/assets/0fc38988-f338-49db-9678-0402ccb1edfe">

Expected:

> Gradle also integrates with the [Java Util Logging](https://docs.oracle.com/javase/8/docs/api/java/util/logging/package-summary.html),

Actual:

> Gradle also integrates with the \[Java Util Logging](https://docs.oracle.com/javase/8/docs/api/java/util/logging/package-summary.html),

<img width="884" alt="image" src="https://github.com/user-attachments/assets/47976304-a9e4-4969-9c65-8dfbb091f6f4">

Expected:

> please contact [security@gradle.com](mailto:security@gradle.com) for assistance with disclosure.

Actual:

> please contact \[[security@gradle.com](mailto:security@gradle.com)](mailto:security@gradle.com) for assistance with disclosure.

### Page with the problem

https://docs.gradle.org/current/userguide/logging.html#sec:external_tools

**Comment by ljacomet** [comment]
Thanks for the report, this exact instance was fixed through #30034 

I will leave the issue opened as we should have a build time error when such invalid links are introduced in asciidoc sources.
