### ISSUE TITLE
Force parallel project configuration before model building

### ISSUE THREAD

**Issue by 6hundreds** [gradle/gradle#30206]
During sync, IDEA [requests](https://github.com/JetBrains/intellij-community/blob/a3de4aaf59ea9cecdb3959eb946d5f273e61dafc/plugins/gradle/tooling-extension-impl/src/com/intellij/gradle/toolingExtension/impl/modelAction/GradleModelFetchAction.java#L268-L276) models sequentially per project preventing project configuration to be parallel even with Isolated Projects.

Given that all project are going to be configured at this stage anyway, it's better to have them preliminary configured in parallel a little bit in advance

**Comment by bamboo** [comment]
This will be announced as part of the IP announcement.
