### ISSUE TITLE
Logs are mistakenly outputted in INFO level

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#3021]
### Expected Behavior

Codenarc task's `console` output should be rendered as `QUITE`.

### Current Behavior

Now it's rendered as `INFO`

### Context

If we create an alone `codenarc` task and enable its console output, the output is mistakenly in `INFO` level. However, this issue doesn't occur in codenarc tasks configured by `codenarc` plugin.

### Steps to Reproduce (for bugs)

- Clone https://github.com/blindpirate/issue1481
- Run `gradle codenarcOnly`, the result doesn't appear in console.

To compare, run `gradle codenarcMain`, the result appears in console.

What's more weird, if you remove the `html` block in task `codenarcOnly` definition as follows:

```
task('codenarcOnly', type: CodeNarc) {
  group 'Test'
  source 'build.gradle'

  configFile = file('codenarc.xml')
  reports {
    /*
    html {
        enabled = true
        destination ='report.html'
    }
   */
    console {
        enabled = true
        destination ='report.xml'
    }
  }
}
```

The result appears now.

**Comment by bmuschko** [comment]
> Codenarc task's console output should be rendered as `LIFECYCLE`.

I think that it should rather use `QUIET`. `LIFECYCLE` is usually used for events that happen during the Gradle life cycle (more like progress information).

**Comment by blindpirate** [comment]
Yes, I've corrected it.

**Comment by big-guy** [comment]
> I think that it should rather use QUIET. LIFECYCLE is usually used for events that happen during the Gradle life cycle (more like progress information).

That doesn't sound right.  That means we'd print the output from Codenarc even when you run with `-q` (we usually hide everything with `-q` except errors).

This block seems suspicious:
https://github.com/gradle/gradle/blob/ee9a435d0670256ffc082155b1603d6487c34ed3/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/CodeNarcInvoker.groovy#L51-L64

Whatever `setLifecycleLogLevel` does changes depending on the order of `reports`, if the HTML report shows up first or not at all, I imagine the text report works. 

If it's simple enough, it might make sense to provide our own `ReportWriter` to CodeNarc and emit a useful console output vs trying to use the built-in text report if it requires us to do something hacky.

**Comment by blindpirate** [comment]
@big-guy Yes, you're right, that's exactly where this issue happens. Thanks for your brilliant advice.

**Comment by grv87** [comment]
> That doesn't sound right. That means we'd print the output from Codenarc even when you run with -q (we usually hide everything with `-q` except errors).

It would be good if rule violations were logged as errors.
