### ISSUE TITLE
Gradle Kotlin (Spring Boot) - languageVersion = JavaLanguageVersion.of(22) - Not working

### ISSUE THREAD

**Issue by drakgoku** [gradle/gradle#30214]
### Current Behavior

```
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(22)
	}
}
```
```
Produces:

[info] Java Home: C:\Users\.........\.vscode\extensions\redhat.java-1.33.0-win32-x64\jre\17.0.11-win32-x86_64
[info] JVM Args: --add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=ES,-Duser.language=es,-Duser.variant
[info] Gradle User Home: C:\Users\..........\.gradle
[info] Gradle Version: 8.8
[error] FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
   > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=22, vendor=any, implementation=vendor-specific} for WINDOWS on x86_64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.8/userguide/toolchains.html#sec:auto_detection.
> Learn more about toolchain repositories at https://docs.gradle.org/8.8/userguide/toolchains.html#sub:download_repositories.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 1s
[error] [gradle-server] The supplied build action failed with an exception.
[error] Error getting build for d:\.................. The supplied build action failed with an exception.
[info] Found 0 tasks
```

### Expected Behavior

```
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
```

CONFIGURE SUCCESSFUL in 1s
[info] Found 40 tasks

### Steps to Reproduce

1. Download the project at https://start.spring.io/
>1. Version project Spring Boot: 3.3.2
>2. Language: Java
>3. Java version: 22
>4. Gradle kotlin == Gradle kotlin dsl
2. From VSC you modify something or simply update and it gives an error in version 22
languageVersion = JavaLanguageVersion.of(22)

### Gradle version

https://start.spring.io/ - 3.3.2 spring boot

### Environment 

Windows

JAVA_HOME => D:\...........\Java\jdk-22.0.1

![image](https://github.com/user-attachments/assets/943e4498-ef80-41fd-82ee-583659c8f26f)

> **Note**: The Spring Boot parent project does not seem to be able to have version 22. But the Spring Boot modules/microservices/child projects can. But once the parent includes them with: include("module1, module n+1) the modules/microservices/children can no longer have version 22.
> 
> So we have:
> - SpringBoot parent: cannot have version 22 but can have version 21
> - - SpringBoot module/microservice/child: can have version 22
>
> When the parent links with include("child/microservice/child") then the child cannot have version 22 and we are left with
> - SpringBoot parent: version 21
> - - SpringBoot module/microservice/child: version 21
> 
> If you try another version it will give an error.
>

**Comment by ljacomet** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

> No locally installed toolchains match and toolchain download repositories have not been configured.

The error indicates that Gradle does not find Java 22 and [toolchain provisioning](https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning) is not configured. When the build is run, Java 17 is used - see the first line:
> [info] Java Home: C:\Users\.........\.vscode\extensions\redhat.java-1.33.0-win32-x64\jre\17.0.11-win32-x86_64

If your Java 22 installation is not in [a location detected by Gradle](https://docs.gradle.org/current/userguide/toolchains.html#sec:auto_detection), you have to configure it explicitly or enable provisioning.

You could also make a feature request to the Spring team so that their Gradle template project enables toolchain auto provisioning.

**Comment by drakgoku** [comment]
How to use gradle? I asked how to use gradle?
ljacomet asked how to make baked potatoes which apparently you didn't read the post.

Give the post a couple of turns and reopen it.
