### ISSUE TITLE
Allow included builds to define variant attribute rules that function in a composite build

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#3022]
An important feature of variant aware dependency resolution is that a plugin can define rules that describe when a particular attribute value is compatible with some other value, and how to select the best match from amongst several candidate values. When these rules do not work, dependency resolution is basically broken for these plugins.

Currently, there are some cases where these rules do not work.

### Expected Behavior

Variant attribute rules defined for a project in an included build are honored by all consumers of that project's outputs, regardless of whether they are projects in the same build or another build, and for all supported attribute value types.

Out of scope for this issue would be honoring these rules outside of the current Gradle invocation, such as via a binary repository.

### Current Behavior

Rules added by the plugin fail in various odd ways, usually a `ClassCastException` or similar, when the plugin is applied to multiple builds in the composite, and the attribute has a type defined by the plugin, such as an enum or some `Named` type.

Issue #3009 fixes the matching when attribute rules are not defined, and also when the consumer defines rules. It does not fix the case when the producer defines any rules.

**Comment by jjohannes** [comment]
I think these problems are fixed by now. If we still encounter any, we should open a separate issue for each with a reproducer.
