### ISSUE TITLE
RC Changelogs appear on Google Search instead of final releases

### ISSUE THREAD

**Issue by oleg-nenashev** [gradle/gradle#30240]
### Issue type

Missing information

### Problem description

RC Changelogs are not a part of https://docs.gradle.org/robots.txt . We post RC changelogs on social media, and they accumulate authority. So the RC link gets ranked higher, and the final release might be excluded as duplicate content on search outputs.

![image](https://github.com/user-attachments/assets/38476a4d-0812-45a0-8dee-90ad463f38bc)

### Page with the problem

All release notes

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
