### ISSUE TITLE
Cannot find a Java installation on your machine matching this tasks requirements.- Gradle 8.10

### ISSUE THREAD

**Issue by beleagaalexandra** [gradle/gradle#30241]
### Current Behavior

Hello Team,

We are currently in the process of upgrading Gradle from version 8.9 to 8.10 in our Kotlin project. During this upgrade, we encountered an issue in our CI pipeline, even though we have properly configured the JavaToolchain in our repository.

Error Encountered:

`Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=17, vendor=any vendor, implementation=vendor-specific} for LINUX on x86_64.
         > No locally installed toolchains match and toolchain download repositories have not been configured.`

Current Configuration (build.gradle.kts):
```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "17"
    }
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}
```

Workaround Implemented:
To address this issue, we found a workaround by integrating the Foojay toolchain resolver plugin in our settings.gradle.kts file:

Here’s the configuration we added:
`plugins {
  id("org.gradle.toolchains.foojay-resolver-convention") version("0.4.0")
}`

With this plugin, the CI pipeline can now successfully resolve and download the necessary Java toolchain, allowing the project to compile with the specified Java version.

Do you have any insights on why this issue is occurring? Is there an alternative solution we could apply to resolve it?

### Expected Behavior

Successful build.

### Steps to Reproduce

Upgrade to 8.10 using the configuration described above.

### Gradle version

8.10

**Comment by ljacomet** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Configuring auto-provisionning is the right solution to get JVMs to be downloaded by Gradle.

You can run `./gradlew javaToolchains` with 8.9 and 8.10 to understand the difference in detected JVMs. There have not been any changes in Gradle itself. So this might be an environment problem.

If JVMs are installed in non supported locations, you have [to configure them explicitly](https://docs.gradle.org/current/userguide/toolchains.html#sec:custom_loc).
