### ISSUE TITLE
Lazy configuration of inputs using inputs of another task creates unwanted task dependency

### ISSUE THREAD

**Issue by mboos** [gradle/gradle#30251]
### Current Behavior

When I try to lazily configure the input of a task with the input of another task (in this case, the `systemProperties` of a `Test` task), Gradle creates an unwanted test dependency on the other task. 

I'll note that the [documentation for `Provider.map`](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Provider.html#map(org.gradle.api.Transformer)) says
> When this provider represents a task or the output of a task, the new provider will be considered an output of the task and will carry dependency information that Gradle can use to automatically attach task dependencies to tasks that use the new provider for input values.

### Expected Behavior

I expect there to be no association between the two tasks when using an input to configure another input. 

### Steps to Reproduce

```kotlin
val testSuite: JvmTestSuite = ...

val newTask = project.tasks.register<MyTask>("newTask") {
  testSuite.targets.all {
    myTaskInput.convention(testTask.map { it.systemProperties })
  }
}
```
Then when I try to run only `newTask`, `test` always runs first. 
```
./gradlew newTask
...
> Task :test
> Task: :newTask
```

### Gradle version

8.10

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

The use case makes sense and it would be good to either clarify how to achieve it or why the task dependency matters, even for wiring inputs to inputs.

**Comment by mboos** [comment]
We have specialized tasks for our tests to execute our test classes on distributed nodes in CI, so we need to gather the `systemProperties` of the local `test` tasks to keep them the same. We want to do this as lazily as possible to minimize configuration time when our distributed test tasks aren't needed.

**Comment by mlopatkin** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

There are some ways to express this:
* For lazy properties the problem doesn't really exist - an idiomatic way is to do `myTaskInput.convention(testTask.flatMap { it.systemProperties })`, and `flatMap` doesn't carry dependencies. Unfortunately, `systemProperties` isn't lazy yet, so it won't help here.
* For eager properties a combination of `provider {}` and `TaskProvider.get()` can be used to break the cycle:
```
myTaskInput.convention(provider { testTask.get().systemProperties })
```

**Comment by mboos** [comment]
Thanks!
