### ISSUE TITLE
Gradle Script Kotlin and dependencyManagement

### ISSUE THREAD

**Issue by small-thanks** [gradle/gradle#30258]
### Current Behavior

I configure the plugin as follows。  https://plugins.gradle.org/plugin/io.spring.dependency-management
![image](https://github.com/user-attachments/assets/ee3b64a4-76e5-49e7-977b-60177d598f05)

### Expected Behavior

I should be able to use dependencyManagement 

### Context (optional)

My configuration is as follows
![image](https://github.com/user-attachments/assets/80ade9c2-1699-478a-859a-e841649f6208)

### Steps to Reproduce

Create a new project and configure the plugin according to the plugin official website. DependencyManagement cannot be used

### Gradle version

8.6

```[tasklist]
### Tasks
```

**Comment by ljacomet** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Kotlin accessors are only generated when plugin are applied with the `plugins` block. That block is already in your script, do not use the legacy application mechanism.

**Comment by small-thanks** [comment]
Groovy can build, but Kotlin cannot. Is this normal?
![image](https://github.com/user-attachments/assets/42246c68-39fe-4277-87df-e5e9299f655f)
![image](https://github.com/user-attachments/assets/88aeacef-715c-4ced-88fe-ecd22c7919be)
