### ISSUE TITLE
Remove `AbstractOptions`

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#3026]
Now that we do not support using `Ant` for compilation any more, we can remove [`AbstractOptions`](https://github.com/gradle/gradle/blob/8a7b8ea7bfd2c38689c8fa339c66485f610c10a9/subprojects/language-jvm/src/main/java/org/gradle/api/tasks/compile/AbstractOptions.java).
I guess we would need to deprecate the class soon to be able to remove it (or replace it with an empty class) for Gradle 5.0.

**Comment by bmuschko** [comment]
@wolfs Can you provide more context around "Now that we do not support using Ant for compilation any more"? I see that all compilation option classes for any language extends from `AbstractOptions` at the moment.

**Comment by wolfs** [comment]
@bmuschko You are right, all the `CompileOptions` are subclasses of `AbstractOptions`. Some time ago, we still supported compiling `Scala` or `Groovy` by using the `Ant` tasks. This is not the case any more. If I understand correctly, `AbstractOptions` only provide utility methods for returning the properties of the concrete `Options` subclasses in a `Map` which can be used for the `Ant` task - at least this is the only use case I figured from the code. Since this is not necessary any more we could just remove the whole class - or all of its methods.
