### ISSUE TITLE
Apple M1 chip，Some syntax errors occurred

### ISSUE THREAD

**Issue by jackxpd** [gradle/gradle#30270]
### Current Behavior

when i use Apple Mi Chip 's MAC Mini，my gradle version is 4.10.1，but i find that Some syntax errors occurred. for example, i can not get git branch information，i can not use commond order in my gradle script.
like:
 'git symbolic-ref --short -q HEAD'.execute().text.trim()  ,it returns null
 commandLine 'apksigner', 'sign', '--ks', it tells me that "A problem occurred starting process 'command 'apksigner''",but i am sure that i configured environment variables. 
those two problem ,when i use Intel Chip 's MAC Mini, it doesn't occur.

### Expected Behavior

 'git symbolic-ref --short -q HEAD'.execute().text.trim()  ,it returns null
 commandLine 'apksigner', 'sign', '--ks', it tells me that "A problem occurred starting process 'command 'apksigner''",but i am sure that i configured environment variables. 

### Steps to Reproduce

my gradle version: 4.10.1
my jdk version: jdk 11.0.24
my android Studio version :Android Studio Koala | 2024.1.1 Patch 1

### Gradle version

4.10.1

### Gradle version that used to work

4.10.1

### Your Environment (optional)

my gradle version: 4.10.1
my jdk version: jdk 11.0.24
my android Studio version :Android Studio Koala | 2024.1.1 Patch 1

**Comment by ghale** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

This question would be better directed towards the [Android community](https://source.android.com/docs/setup/community).
