### ISSUE TITLE
Deprecate `Javadoc.isVerbose/setVerbose` and prefer verbose setting on `CoreJavadocOptions`

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#30308]
These properties should belong to options. Also due to werid setters is hard to migrate them to provider API.

https://github.com/gradle/gradle/blob/678cf709a77f9f432768c6c0ee7eb48a0ddaed91/platforms/jvm/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java#L311-L327

**Comment by octylFractal** [comment]
Fixed by #30333
