### ISSUE TITLE
Gradle generates Kotlin DSL accessors for Configurations with invalid identifiers

### ISSUE THREAD

**Issue by adam-enko** [gradle/gradle#30340]
### Current Behavior

Gradle generates Kotlin DSL accessors for Configurations with invalid identifiers.

### Expected Behavior

Gradle does not generate Kotlin DSL accessors for Configurations with invalid identifiers.

### Context (optional)

A full stop, `.`, is not a valid Kotlin identifier.

If a Gradle plugin creates a task with a `.` in its name, then Gradle does not generate a Kotlin DSL accessor for it. It is filtered out by `isLegalAccessorName(it.name)`.

https://github.com/gradle/gradle/blob/6b781e8cac1aa2259e83ad97853b9b13b7f3f2e5/platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/CodeGenerator.kt#L308

However, if a Gradle plugin creates a Configuration with a `.` in its name, then the same check is not applied.

https://github.com/gradle/gradle/blob/6b781e8cac1aa2259e83ad97853b9b13b7f3f2e5/platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/accessors/Emitter.kt#L212

The result is that Gradle will generate invalid accessors for these Configurations. In projects that use included-builds for plugins, then this causes compilation failures as the accessors are compiled.

### Steps to Reproduce

[demo.zip](https://github.com/user-attachments/files/16784731/demo.zip)

### Gradle version

8.10

**Comment by ghale** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
