### ISSUE TITLE
Failure during configuration when applying a plugin causes configuration-cache report to be written to the default build directory

### ISSUE THREAD

**Issue by TimvdLippe** [gradle/gradle#30361]
### Current Behavior

The configuration cache report is written to `file:///Users/timvand/gradle-reproducer/build/reports/configuration-cache/1q1fnugvpaq1i9c96g9q7dkql/72f1ehyku0l8b3pdlxu1b3rn/configuration-cache-report.html` (Note the `build` instead of `.build` directory as expected)

### Expected Behavior

The configuration cache report is written to `file:///Users/timvand/gradle-reproducer/.build/reports/configuration-cache/1q1fnugvpaq1i9c96g9q7dkql/72f1ehyku0l8b3pdlxu1b3rn/configuration-cache-report.html`

### Context (optional)

We are seeing the configuration cache report written to a different location in a situation where we haven't turned on Isolated Projects yet. However, I was unable to figure that one out yet and I can definitely reproduce here. My hope is that the root cause of the issue is similar.

See the reproduction steps below where you can comment out the broken plugin to see the file written to the correct location as well.

### Steps to Reproduce

Project setup:

`build.gradle`
```
layout.buildDirectory = '.build'
```
`settings.gradle`
```
include(':module')
```
`gradle.properties`
```
org.gradle.configuration-cache=true
org.gradle.unsafe.isolated-projects=true
```
`module/build.gradle`
```
plugins {
    id 'java-library'
    // Comment the plugin below to fix the correct location
    id 'com.enterprise.broken-plugin'
}

tasks.register('foo') {
    dependsOn test
    doLast {
        project.projectDir
    }
}
```
`buildSrc/build.gradle`
```
plugins {
    id 'groovy-gradle-plugin'
}
```
`buildSrc/src/main/groovy/com.enterprise.broken-plugin.gradle`
```
tasks.named('test', Test) {
    // broken because it is a typo
    retry2 {
    }
}
```

To reproduce, run `./gradlew :module:foo`

### Gradle version

8.10

**Comment by bamboo** [comment]
Thanks for the report, @TimvdLippe. We'll take a look.

**Comment by abstratt** [comment]
This no longer happens in `master`, but reproduced it against 8.10 indeed.

**Comment by abstratt** [comment]
@TimvdLippe Could you please try to confirm whether a recent 8.11 nightly build addresses the issue?

**Comment by TimvdLippe** [comment]
@abstratt I have tried it out and unfortunately ran into unrelated deadlocks when running `./gradlew -Dorg.gradle.unsafe.isolated-projects=true help`. For more details, please see the Gradle Slack channel of my company. Once the deadlock is resolved, I can confirm that it is solved from our end.
