### ISSUE TITLE
S3 Encryption on PUT

### ISSUE THREAD

**Issue by sweiler** [gradle/gradle#3038]
We want to use the AWS S3 Resource subproject to put our artifacts into an S3 bucket. For this, we want to use S3's server-side encryption. This is currently not supported by the resources-s3 subproject.

### Expected Behavior
We propose to have an option to activate server-side encryption and to specify an optional key id to use. This is only relevant for the PUT action, because S3 automatically decrypts objects on GET.

The change would probably happen in the [`put`](https://github.com/gradle/gradle/blob/f0e719cff9115b85532bed2817116f5f0bede7a0/subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3Client.java#L128) method of the `S3Client` class. To enable the server-side encryption, [`withSSEAwsKeyManagementParams()`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/PutObjectRequest.html#withSSEAwsKeyManagementParams-com.amazonaws.services.s3.model.SSEAwsKeyManagementParams-) has to be called on the `PutObjectRequest` object.

### Current Behavior
It is not possible to publish artifacts encrypted into a S3 bucket. Reading encrypted artifacts is possible as it is.

### Context
Company regulations require that we store source code only encrypted. S3 allows this nearly transparently, but it has to be enabled whenever you put an object into it. We think this would be helpful for many other users, too, since regulations like this are common.

**Comment by oehme** [comment]
I think this is a good idea. Would you be interested in working on this?

**Comment by sweiler** [comment]
Yes I can work on that. But I would need some guidance on what would be the best way to make this configurable. I think it would make sense to have two optional configuration options, one to enable server side encryption at all and another one to specify the used key ID, if they don't want to use the default one.

**Comment by cgarciaarano** [comment]
Hey, it would be useful also to setup the ACL to in the `put` method. The use case is to avoid permission issues when we are publishing from an account that is not the bucket owner. 

For example, one library can publish its artifacts to an S3 bucket owned by another application and account, so it can use it in its build, keeping the permissions segregated.

I can contribute too, but as @sweiler I need some guidance to make it configurable.

**Comment by oehme** [comment]
I just realized that we don't expose any transport-specific API so far, the only S3 specific thing on the API are the AWSCredentials. There are also some system properties to control it, which is certainly not the way to go in the future. We'd probably want to provide a transport configuration DSL, similar to what we have for authentication.

I.e. something like

```
repositories {
  maven {
     url = "s3://..."
     transport(S3Transport) {
      encrypt = true
     }
  }
}
```

@bigdaz does that make sense in your opinion?

**Comment by bigdaz** [comment]
Yes, this looks like the right direction. The 'transport' is just one of the pieces that make up a repository definition. Detangling the various parts (making repositories more composable) would be good, and we'll need a DSL that can match this.

**Comment by sweiler** [comment]
Just let me add one comment.. transport doesn't sound right to me, since we are not talking about transport encryption, but server-side encryption. This is, that the artifacts are encrypted on harddisk at AWS.

**Comment by sweiler** [comment]
While the feature is still not available in Gradle, the need isn't that big anymore.
AWS has introduced a new feature that allows for an [automatic encryption on S3 buckets](http://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html). Therefore you can just simply enable this on the S3 bucket and then all artifacts pushed via Gradle are encrypted by default.

For our team this resolves the issue and we won't provide any gradle specific solution.

I'll close the issue, but feel free to re-open if it makes sense for you to have an option for this in Gradle itself.

**Comment by oehme** [comment]
Thanks for getting back to us and providing this workaround for others 👍

**Comment by opensso** [comment]
@oehme this still an issue. In some cases organization might require client-side encryption.
Would be grate if internals of configuring S3 client is exposed to gradle DSL

**Comment by oehme** [comment]
We can, though I just want to set expectations that we won't be working on this any time soon.
