### ISSUE TITLE
Gradle should not validate isolated projects when isolated projects is disabled

### ISSUE THREAD

**Issue by joshfriend** [gradle/gradle#30385]
### Current Behavior

I get [the error from this existing issue](https://github.com/gradle/gradle/issues/24981) but it happens when the build being tested has configuration cache disabled. Debugger is attached and we have `withDebug(true` in testkit. In 8.6 I am able to debug inside the tests and inside the build being tested as expected, but in 8.10 connecting the debugger results in this error from the build under test, which points at the Develocity plugin:

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to notify build listener.
> Configuration cache state could not be cached: field `$action` of `org.gradle.internal.cc.impl.services.DefaultIsolatedProjectEvaluationListenerProvider$withUserCodeApplicationContext$1$1` bean found in field `beforeProject` of `org.gradle.internal.cc.impl.services.IsolatedProjectActions` bean found in Gradle runtime: error writing value of type 'org.gradle.internal.enterprise.impl.DefaultDevelocityBuildLifecycleService$$Lambda$4455/0x000000080185fa50'
   > Unable to make field private final java.lang.Object[] java.lang.invoke.SerializedLambda.capturedArgs accessible: module java.base does not "opens java.lang.invoke" to unnamed module @3af57334
```

Working around it by adding some extra `--add-opens` to the jvmargs of the test tasks as described [here](https://github.com/gradle/gradle/issues/22765#issuecomment-1444363323) works.

### Expected Behavior

Gradle should not fail on project isolation issues unless isolated projects is actually enabled.

### Context (optional)

Here's the explanation I got from @6hundreds on slack for additional context:

Gradle 8.10 is making `DefaultDevelocityBuildLifecycleService` to use new `GradleLifecycle#beforeProject` callback for apply the logic to all projects.

`GradleLifecycle` is designed to be an Isolated Projects compatible API _even in vintage(no CC) mode_. For this purpose, Gradle runtime _isolates_ `beforeProject`/`afterProject` callbacks for each project, preventing state sharing across the projects.

_Isolation_ of the callback is being achieved by using serialization/desiarilization roundtrip _with Configuration Cache serialization protocol_.

This is explains why:
1. you getting this failure even with CC disabled
2. you see the error related to CC serilization

Perhaps, it could be cleaner to rephrase the error message in this case and not mention `Configuration cache state could not be cached`, when CC is disabled, or so.

### Steps to Reproduce

Attach debugger to a testkit test using `withDebug(true)` where the build under test applies the Devleocity plugin and is running Gradle 8.10.

### Gradle version

8.10

### Gradle version that used to work

8.6

**Comment by yogurtearl** [comment]
I hit this same error when upgrading from Develocity plugin version `3.16.2` to `3.17.6`

Removing `withDebug(true)` from the test worked around the issue. (or downgrading to Develocity plugin to `3.16.2`) 

I didn't try it, but adding `--add-opens=java.base/java.lang.invoke=ALL-UNNAMED` on the gradle daemon JVM args might work around this as well?

**Comment by joshfriend** [comment]
> I didn't try it, but adding --add-opens=java.base/java.lang.invoke=ALL-UNNAMED on the gradle daemon JVM args might work around this as well? 

I did try this as mentioned above and it does work.

Should also mention for context that we use Develocity plugin 3.18 to get the new build monitoring features.
