### ISSUE TITLE
Deadlock in parallel tasks configuration in IP mode

### ISSUE THREAD

**Issue by 6hundreds** [gradle/gradle#30402]
Running `./gradlew help` on `gradle/gradle` with IP enabled hangs at configuration of `:build-logic:java-api-extractor`.
_Note: java-api-extractor is shared between build logic and production logic_

The deadlock happens during parallel plugin resolution from included builds. That machinery isn't ready for concurrency currently. However, solely adding extra synchronization doesn't fix the problem completely. Currently cycles are allowed(historical reasons) for included builds hierarchy. That's not a problem for library(non-plugins) builds - cycle will be detected at dependency resolution time, but it's a problem for plugin builds which are being evaluated as configuration going. It's an another source of the deadlock in IP mode.

The fix should include two steps:

- [x] Forbid cycles for included plugin builds definition [#30902]
- [x] Thread safe build inclusion process [#31070 ]

**Comment by jvandort** [comment]
Do we know what’s causing this and/or do we have a thread dump?

**Comment by 6hundreds** [comment]
@jvandort Sorry, was in a rush that day. Here is a bit of additional context - the deadlock is happening during plugin resolution from included build.

**Comment by 6hundreds** [comment]
There are some  tests in :composite-builds that "proves" that included builds could have cycles in their definition:
https://github.com/gradle/gradle/blob/master/subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildIncludeCycleIntegrationTest.groovy#L22

https://github.com/gradle/gradle/blob/master/subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/plugins/PluginBuildsIntegrationTest.groovy#L576

https://github.com/gradle/gradle/blob/master/subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/plugins/PluginBuildsIntegrationTest.groovy#L353

However, these tests are testing only possibility to declare cycled structure without an error, and do not test functionality of such a build tree layout.

In the meantime, current implementation of build inclusion logic is not supporting cycles. It's early returning for cycles in [plugin builds](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildInclusionCoordinator.java#L87) and just ignores [library builds](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/internal/buildtree/BuildInclusionCoordinator.java#L108) in cycles.

We should deprecate cycles even in vintage mode
