### ISSUE TITLE
Provide a flag to disable parallel configuration for IP mode in favor of configure-on-demand

### ISSUE THREAD

**Issue by 6hundreds** [gradle/gradle#30401]
Enabling configuration parallelism in IP mode without incrementality is intentional tradeoff that been taken. It will allow to observe performance improvements been brought by parallelism during IDE project sync and tasks running from CLI.

However, for the builds of the extreme size (in terms of projects count), benefits from configure-on-demand could be more significant than benefits from parallel configuration.

**Comment by hfhbd** [comment]
Can you provide some details why parallel CC with IP and configure on demand can't be enabled simultaneously?

**Comment by 6hundreds** [comment]
> Can you provide some details why parallel CC with IP and configure on demand can't be enabled simultaneously?

As a note for the context: `parallel CC` != `parallel configuration`.  Parallel CC is mostly about parallel CC store/load(https://github.com/gradle/gradle/pull/30132), and parallel configuration is about running projects configuration in parallel. Given that, I'd rather answer on question "why parallel configuration and configure on demand can't be enabled simultaneously"

Eventually, it's definitely a goal to make configuration phase parallel AND incremental in IP mode.
Enabling parallelism in IP mode without incrementality(aka configure-on-demand) support is a step in this direction. It will allow to observe performance improvements been brought by parallelism during IDE project sync and tasks running from CLI.

However, for the builds of the extreme size (in terms of projects count), benefits from configure-on-demand could be more significant than benefits from parallel configuration. That's why the flag to control is going to be introduced.
