### ISSUE TITLE
'/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

### ISSUE THREAD

**Issue by rusefillc** [gradle/gradle#30421]
### Current Behavior

'/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

### Expected Behavior

same repo same device things are happy with 8.9

### Steps to Reproduce

clone https://github.com/rusefi/rusefi with submodules
cd firmware
make
(yes make would invoke gradle wrapper sorry about that)

### Gradle version

8.10

### Gradle version that used to work

8.9

### Your Environment (optional)

$ java --version 
openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu220.04, mixed mode, sharing)

**Comment by rusefillc** [comment]
fun fact https://www.google.com/search?q=openjdk+gradle+%22does+not+provide+the+required+capabilities%22

![image](https://github.com/user-attachments/assets/746ea4ff-5e37-41a3-9d6c-4c97196c4757)

**Comment by ljacomet** [comment]
This looks very similar to
* #30264 

which we decided to accept as a regression.

If you believe this is different, can you share a full stack trace of the error?
Could you also run `/usr/lib/jvm/java-17-openjdk-amd64/bin/java --version`? And confirm that folder has ` javac` executable.

The reproducer you shared is far from minimal and figuring out where is the problem, especially as it has a chance to be environment specific, would be quite a time sink.

Without an answer within 7 days, this issue will be closed.

**Comment by rusefillc** [comment]
@ljacomet I believe that's a different issue since we successfully use the compiler with 8.9

what would be a way to produce a more detailed stack trace?

```
> Configure project :core_io
gradle says: ABSOLUTE_BOARD_DIR=null

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `javaCompiler` of task `:logging-api:compileJava` of type `org.gradle.api.tasks.compile.JavaCompile`: error writing value of type 'org.gradle.api.internal.provider.DefaultProperty'
> Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
Configuration cache entry discarded due to serialization error.
make: *** [../java_tools/java_tools.mk:29: ../java_tools/configuration_definition_base/build/libs/config_definition_base-all.jar] Error 1
make: *** Waiting for unfinished jobs....
Calculating task graph as no cached configuration is available for tasks: :enum_to_string:shadowJar

> Configure project :core_io
gradle says: ABSOLUTE_BOARD_DIR=null

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `javaCompiler` of task `:logging-api:compileJava` of type `org.gradle.api.tasks.compile.JavaCompile`: error writing value of type 'org.gradle.api.internal.provider.DefaultProperty'
> Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
Configuration cache entry discarded due to serialization error.
make: *** [../java_tools/java_tools.mk:32: ../java_tools/enum_to_string/build/libs/enum_to_string-all.jar] Error 1
Calculating task graph as no cached configuration is available for tasks: :config_definition:shadowJar

> Configure project :core_io
gradle says: ABSOLUTE_BOARD_DIR=null

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache state could not be cached: field `javaCompiler` of task `:logging-api:compileJava` of type `org.gradle.api.tasks.compile.JavaCompile`: error writing value of type 'org.gradle.api.internal.provider.DefaultProperty'
> Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
Configuration cache entry discarded due to serialization error.
make: *** [../java_tools/java_tools.mk:26: ../java_tools/configuration_definition/build/libs/config_definition-all.jar] Error 1
```

**Comment by rusefillc** [comment]
```
/usr/lib/jvm/java-17-openjdk-amd64/bin/java --version
openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu220.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu220.04, mixed mode, sharing)
```

**Comment by ljacomet** [comment]
Producing a full stacktrace is done by passing `--stacktrace` or `-s` to the Gradle invocation, as indicated in the output.

Thanks for taking the time to look into this and confirm your setup has some issues.

Closing as an environment problem.

**Comment by mohitsatr** [comment]
@rusefillc I have the exact same issue . can you help me with how this can be resolved  ?

**Comment by Azyrod** [comment]
Hi, I have the same issue, except I have `javac` in that folder : 
```
$ /usr/lib/jvm/java-21-openjdk-amd64/bin/java --version
openjdk 21.0.9 2025-10-21
OpenJDK Runtime Environment (build 21.0.9+10-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 21.0.9+10-Ubuntu-122.04, mixed mode, sharing)
```

```
$ /usr/lib/jvm/java-21-openjdk-amd64/bin/javac --version
javac 21.0.9
```

```
$ ./gradlew decompileCFR --quiet decompileCFR

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':filament:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':filament:compileJava'.
   > Failed to calculate the value of task ':filament:compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-21-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 528ms
```

Edit: Restarting the gradle deamons fixed it, I had installed javac after a failed attempt and it looks like the deamon stuck around without realizing I had changed the installation it was using. (would be a cool feature to detect changes in the java installation and re-scan it without having to restart, cause it's quite confusing to install the missing piece but not having gradle detect it)

**Comment by StevenAWhite** [comment]
> Hi, I have the same issue, except I have `javac` in that folder :
> 
> ```
> $ /usr/lib/jvm/java-21-openjdk-amd64/bin/java --version
> openjdk 21.0.9 2025-10-21
> OpenJDK Runtime Environment (build 21.0.9+10-Ubuntu-122.04)
> OpenJDK 64-Bit Server VM (build 21.0.9+10-Ubuntu-122.04, mixed mode, sharing)
> ```
> 
> ```
> $ /usr/lib/jvm/java-21-openjdk-amd64/bin/javac --version
> javac 21.0.9
> ```
> 
> ```
> $ ./gradlew decompileCFR --quiet decompileCFR
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':filament:compileJava'.
> > Error while evaluating property 'javaCompiler' of task ':filament:compileJava'.
>    > Failed to calculate the value of task ':filament:compileJava' property 'javaCompiler'.
>       > Toolchain installation '/usr/lib/jvm/java-21-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 528ms
> ```
> 
> Edit: Restarting the gradle deamons fixed it, I had installed javac after a failed attempt and it looks like the deamon stuck around without realizing I had changed the installation it was using. (would be a cool feature to detect changes in the java installation and re-scan it without having to restart, cause it's quite confusing to install the missing piece but not having gradle detect it)

Can confirm this pushed past this issue.  

Ubuntu 24.04 

I had only installed open-jre-17-headless but after installing open-jdk-17-headless the system still refused to acknowledge the JDK until it was stopped and relaunched.  I didn't consider this until reading this response so thank you.

**Comment by Espionage724** [comment]
On openSUSE Tumbleweed I got this error with just `java-26-openjdk-headless` and `java-26-openjdk` installed; `javac` is included in `java-26-openjdk-devel`
