### ISSUE TITLE
Don't report lenient resolution failures to Problems API

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#30442]
Inform the `ResolutionFailureHandler` of when a failure is causing during lenient resolution.  Don't report these exceptions to the Problems API.  This will minimize noise on the HTML Problems report.

If this is difficult, then just don't report any failures as Problems for now and return to this later.

Ideally, we'd want to explore not using exceptions for flow control when lenient resolution fails.  This could have positive performance impacts, but seems like a much bigger refactoring.

**Comment by tresat** [comment]
@reinsch82 @big-guy

**Comment by jvandort** [comment]
We don't really know when we are doing a lenient resolution. 

Pulling on a `ResolutionResult` is lenient. All failures are represented as `UnresolvedDependencyResult`, but there is no prior "switch" to tell the dependency graph builder that the resolution is lenient -- the output is always lenient. Its a matter of the front-end types (like `ResolutionBackedFileCollection`) to take those failures during resolution and turn them into user-facing errors.

**Comment by donat** [comment]
@tresat https://github.com/gradle/gradle/pull/30506 is merged, can we close this issue?
