### ISSUE TITLE
spring boot build very slow

### ISSUE THREAD

**Issue by cjdxhjj** [gradle/gradle#30458]
### Current Behavior

![image](https://github.com/user-attachments/assets/3985cdf9-98b5-4867-8c0b-ff68c6c8ad1c)

### Expected Behavior

build quickly

### Steps to Reproduce

run bootJar

### Gradle version

8.10

### Your Environment (optional)

jdk 21

**Comment by kahamilek** [comment]
It looks related to this [issue](https://github.com/gradle/gradle/issues/30239)

**Comment by cjdxhjj** [comment]
I have upgraded to 8.10.1. The build is fast. thanks @kahamilek
