### ISSUE TITLE
Kotlin Mutliplatform build with reused daemon fails with "Cannot query the value of task ':compileKotlinWindows' property 'kotlinNativeBundleBuildService' because it has no value available."

### ISSUE THREAD

**Issue by GST1DR** [gradle/gradle#30477]
### Current Behavior

Find a small toy project attached to demonstrate the problem. (I reduced the problem to the bare minimum i could still reproduce it.)
Before (gradle 8.10) this used to build fine.
Now (gradle 8.10.1) this is a weird, partially random build bug. It seems to be related to 3 things:
1. this is a Kotlin Multiplatform Project (which do quite some gradle magic under the hood)
2. as one of the Kotlin multiplatform targets it builds a native executable (kotlin can compile to native e.g. mingw (windows), linux, mac, ios binaries.) I tested both mac (M1) and windows (mingw) - any of them or both will do.
3. It seems to be, that the bug only happens, if a gradle daemon is reused. 
3.1. build with a fresh gradle => builds fine (gradle clean build)
3.2. directly afterwards again run "gradle clean build", this will reuse the gradle daemon, which was started in the first build .
This second build fails with a strange exception (before narrrowing it down to this minimal example, the error seemed to randomly jump between different messages, here it seems to be quite stable):

> Task :compileKotlinWindows FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlinWindows'.
> Error while evaluating property 'kotlinNativeProvider$kotlin_gradle_plugin_common.kotlinNativeBundleVersion$kotlin_gradle_plugin_common' of task ':compileKotlinWindows'.
   > Cannot query the value of task ':compileKotlinWindows' property 'kotlinNativeBundleBuildService' because it has no value available.
 

### Expected Behavior

should stable build as before, no matter, if a daemon is reused or not

### Context (optional)

build my projects on the command line (windows: git bash, mac: zsh)

### Self-contained Reproducer Project

[Foo.zip](https://github.com/user-attachments/files/16946881/Foo.zip)

### Gradle version

8.10.1

### Gradle version that used to work

8.10

### Your Environment (optional)

Mac (M1) and Windows (git bash)

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Relates to:
* #30472

**Comment by ljacomet** [comment]
@6hundreds Could you make sure #30488 also fixes this issue?

**Comment by 6hundreds** [comment]
> @6hundreds Could you make sure https://github.com/gradle/gradle/pull/30488 also fixes this issue?

Actually there are two problems, that must be solved. We are working on solution that will be fix both of them, and it seems like it will be not a #30488

**Comment by ljacomet** [comment]
Hello @GST1DR and @alyssa-nash ,

Could you try version `8.10.2-milestone-1` and report the results?

`./gradlew wrapper --gradle-version 8.10.2-milestone-1`

**Comment by GST1DR** [comment]
Hello dear gradle maintainers,

i did some tests on all my gradle projects and the 8.10.2-milestone-1 seems to solve the problem. However, since the problem (from my user perspective) seemed to have some random component (did not occur always and if it occurred, the error differed), I am not 100% sure, that everything is ok (but quite sure).

What I did: build several real-world-projects with:

  *   Gradle 8.10
  *   Gradle 8.10.1
  *   Gradle 8.10.2-milestone-1

Each time I did 2 subsequent builds to simulate what I considered the cause of the problem.
Outcome:

  1.  Some projects build ok/ok/ok, i.e. they were not affected by the problem in the first place, but the new milestone did not introduce new obvious problems
  2.  Other projects build ok/error/ok, i.e. they were affected and the milestone seemed to solve the problem. (and not introduce new obvious ones)
Thanks!

Mit freundlichen Grüßen / Best regards

Dr. Steffen Guhlemann

Manufacturing Engineering (DrP/MFE)
Robert Bosch Semiconductor Manufacturing Dresden GmbH | Robert-Bosch-Ring 1 | 01109 Dresden | GERMANY
Tel. +49 351 8547-3530 | Mobil +49 152 24440214 | ***@***.******@***.***>

Sitz: Dresden, Registergericht: Amtsgericht Dresden, HRB37117
Geschäftsführung: Dr. Dirk Drescher, Dr. Patrick Leinenbach

​
Von: Louis Jacomet ***@***.***>
Gesendet: Freitag, 20. September 2024 09:37
An: gradle/gradle ***@***.***>
Cc: Guhlemann Steffen (DrP/MFE2) ***@***.***>; Mention ***@***.***>
Betreff: Re: [gradle/gradle] Kotlin Mutliplatform build with reused daemon fails with "Cannot query the value of task ':compileKotlinWindows' property 'kotlinNativeBundleBuildService' because it has no value available." (Issue #30477)


Hello @GST1DR<https://github.com/GST1DR> and @alyssa-nash<https://github.com/alyssa-nash> ,

Could you try version 8.10.2-milestone-1 and report the results?

./gradlew wrapper --gradle-version 8.10.2-milestone-1

**Comment by cocorossello** [comment]
8.10.2-milestone-1 solved the problem for us
