### ISSUE TITLE
Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

### ISSUE THREAD

**Issue by nicolaasuni-vonage** [gradle/gradle#30499]
### Current Behavior

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 8.10.1
------------------------------------------------------------

Build time:    2024-09-09 07:42:56 UTC
Revision:      8716158d3ec8c59e38f87a67f1f311f297b79576

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  17.0.12 (Debian 17.0.12+7-Debian-2deb12u1)
Daemon JVM:    /usr/lib/jvm/java-17-openjdk-amd64 (no JDK specified, using current Java home)
OS:            Linux 6.1.0-25-amd64 amd64
```

```
$ ./gradlew clean

BUILD SUCCESSFUL in 464ms
1 actionable task: 1 executed
```

```
$ ./gradlew jar

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 477ms
```

### Expected Behavior

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 8.10
------------------------------------------------------------

Build time:    2024-08-14 11:07:45 UTC
Revision:      fef2edbed8af1022cefaf44d4c0514c5f89d7b78

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  17.0.12 (Debian 17.0.12+7-Debian-2deb12u1)
Daemon JVM:    /usr/lib/jvm/java-17-openjdk-amd64 (no JDK specified, using current Java home)
OS:            Linux 6.1.0-25-amd64 amd64
```

```
$ ./gradlew clean

BUILD SUCCESSFUL in 415ms
1 actionable task: 1 up-to-date
```

```
$ ./gradlew jar

BUILD SUCCESSFUL in 469ms
2 actionable tasks: 2 executed
```

```
$ ./gradlew test

BUILD SUCCESSFUL in 1s
3 actionable tasks: 2 executed, 1 up-to-date
```

### Context (optional)

After updating gradle to the latest 8.10.1 version, the Java project fails to build as reported in the logs.
The build works with the previous gradle version 8.10.0.

### Self-contained Reproducer Project

The issue can be reproduced with this very small project:
https://github.com/Vonage/numkey/tree/main/java

`./gradlew jar`

### Gradle version

8.10.1

### Your Environment (optional)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

```
$ uname -a
Linux *** 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
```

```
$ which javac
/usr/bin/javac

$ ls -lah /usr/bin/javac
lrwxrwxrwx 1 root root 23 Jul 31 16:55 /usr/bin/javac -> /etc/alternatives/javac

$ ls -lah /etc/alternatives/javac
lrwxrwxrwx 1 root root 44 Jul 31 16:55 /etc/alternatives/javac -> /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

$ /usr/lib/jvm/java-17-openjdk-amd64/bin/javac --version
javac 17.0.12
```

```
/usr/lib/jvm/java-17-openjdk-amd64
├── bin
│   ├── jar
│   ├── jarsigner
│   ├── java
│   ├── javac
│   ├── javadoc
│   ├── javap
│   ├── jcmd
│   ├── jconsole
│   ├── jdb
│   ├── jdeprscan
│   ├── jdeps
│   ├── jfr
│   ├── jhsdb
│   ├── jimage
│   ├── jinfo
│   ├── jlink
│   ├── jmap
│   ├── jmod
│   ├── jpackage
│   ├── jps
│   ├── jrunscript
│   ├── jshell
│   ├── jstack
│   ├── jstat
│   ├── jstatd
│   ├── keytool
│   ├── rmiregistry
│   └── serialver
```

The JDK was installed via:

`sudo apt install default-jdk`

**Comment by hennyholar1** [comment]
How can I get this same issue resolved in a docker image that contains gradle.zip 8.10.2 in '/opt/gradle' directory? I built my image with Java 21 (java-21-amazon-corretto), Selenium web driver manager, chrome and edge browser and driver successfully but whenever I tried to execute my tests via .gitlab-ci.yml file script ( ./gradlew clean build), the gradle wrapper command will unzip the file successfully to the right directory, but test execution continues to fail with the above issue caption exception. 

**_Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER] #30499_**

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-17-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

Any reliable solution is highly appreciated.

**Comment by esemeniuc** [comment]
🏁 🏁 🏁 🏁 🏁 Make sure to restart gradle daemon, this was my issue. Alternatively, build with `gradle --no-daemon`

**Comment by namero999** [comment]
I'm experiencing this same issue after upgrading to 8.11.1

The machine has both jdk 17 (to run TeamCity) and jdk 21 (to build project). The default is 17. The project defines the correct toolchain

```kotlin
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}
```

and it builds correctly with Gradle 8.9. Now it will always try to use 17, as if the toolchain configuration is ignored. All the daemons were stopped.

**Comment by yannxaver** [comment]
I had the same issue on Ubuntu 24.04 and it was also solved by rebooting the computer. Notably, the computer failed to start four times after the reboot attempt. I already assumed my OS had been bricked. After the fifth hard shutdown the computer started correctly again.

```shell
javac --version
javac 21.0.5

java -version
openjdk version "21.0.5" 2024-10-15
OpenJDK Runtime Environment (build 21.0.5+11-Ubuntu-1ubuntu124.04)
OpenJDK 64-Bit Server VM (build 21.0.5+11-Ubuntu-1ubuntu124.04, mixed mode, sharing)

gradle -v
------------------------------------------------------------
Gradle 8.11.1
------------------------------------------------------------

Build time:    2024-11-20 16:56:46 UTC
Revision:      481cb05a490e0ef9f8620f7873b83bd8a72e7c39

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.5 (Ubuntu 21.0.5+11-Ubuntu-1ubuntu124.04)
Daemon JVM:    /usr/lib/jvm/java-21-openjdk-amd64 (no JDK specified, using current Java home)
OS:            Linux 6.8.0-50-generic amd64
```

**Comment by jondaley** [comment]
> Make sure to restart gradle daemon, this was my issue. Alternatively, build with `gradle --no-daemon`

Thanks - I'm new to gradle, and hadn't noticed a daemon was running.  I even erased the .gradle directory in the hopes that would change something.  But, restarting the daemon made it notice that I had installed a java compiler.

**Comment by FWDekker** [comment]
I'm experiencing the same issue, and rebooting does not resolve the issue. Downgrading to Gradle 8.7 does work, but is not preferable. I've also tried re-downloading my JDK or switching to a different JDK (I tried Coretto 21 and Temurin 21), but kept receiving the same errors.

In the end, telling Gradle which version to use, as explained in [namero999's comment](https://github.com/gradle/gradle/issues/30499#issuecomment-2490852609), was the only solution that worked for me.

**Comment by robertkraig** [comment]
LOL, this worked for me. I had to restart my damn linux computer. How on earth does that work.. Normally a simple restart of the terminal and up and running. Ran out of CLAUDE tokens trying to solve this LOL!!

**Comment by DaddyWesker** [comment]
And what if problem occurs even after restarting Ubuntu? I'm on ubuntu 25.04, gradle 9.2.0.

**Comment by Fredrik00** [comment]
Luckily stumbled upon this thread as well.
My JDK 21 installation for some reason did not include javac, after reinstalling with apt to fix this and confirming javac was now present I still got the same error. Stopping the gradle daemon with "gradlew --stop" resolved the issue for me.

**Comment by DaddyWesker** [comment]
In my case it was due to abscence of javac in the java folder. I've erased java and reinstalled it from oracle site.

**Comment by rnett** [comment]
I've just ran into this as well.  I think there's an actual issue here.  Stopping the daemon or running without it has not resolved this for me.
