### ISSUE TITLE
Unable to resolve published plugins from the gradle plugin portal

### ISSUE THREAD

**Issue by iwarapter** [gradle/gradle#3050]
### Expected Behavior
The plugin should resolve.

### Current Behavior
```
$ ./gradlew tasks

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'missing-plugin-reproducer'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find gradle.plugin.com.iadams.gradle:gradle-openshift-plugin:0.1-RC2.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/com/iadams/gradle/gradle-openshift-plugin/0.1-RC2/gradle-openshift-plugin-0.1-RC2.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/iadams/gradle/gradle-openshift-plugin/0.1-RC2/gradle-openshift-plugin-0.1-RC2.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

### Context
Unable to build without the plugin, others with the issue [also.](https://github.com/iwarapter/gradle-openshift-plugin/issues/3)

### Steps to Reproduce (for bugs)
```
$ cat build.gradle 
plugins {
  id "com.iadams.openshift-base" version "0.1-RC2"
}
```

**Comment by big-guy** [comment]
I believe you're being bitten by this: https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573

The plugin you're using to publish is using an older version of the plugin-publish plugin: 
https://github.com/iwarapter/gradle-plugin-plugin/blob/master/build.gradle#L14

**Comment by iwarapter** [comment]
Ah OK i'll update my plugins to get with the times 👍

**Comment by timyates** [comment]
Hiya!

This should fix it (I hope)

https://github.com/iwarapter/gradle-plugin-plugin/pull/2
