### ISSUE TITLE
Wrong link in 'Implementing tasks with dependency resolution result inputs Sample'

### ISSUE THREAD

**Issue by adam-enko** [gradle/gradle#30519]
### Issue type

Wrong or misleading information

### Problem description

https://docs.gradle.org/current/samples/sample_tasks_with_dependency_resolution_result_inputs.html

> For more information, see [Authoring Tasks reference chapter](https://docs.gradle.org/current/userguide/more_about_tasks.html). Additionally, see the [Incremental Build](https://docs.gradle.org/current/userguide/incremental_build.html) chapter and its [Using dependency resolution results](https://docs.gradle.org/current/userguide/incremental_build.html#sec:task_input_using_classpath_annotations) section.

'Using dependency resolution results' links to https://docs.gradle.org/current/userguide/incremental_build.html#sec:task_input_using_classpath_annotations

It should link to https://docs.gradle.org/current/userguide/incremental_build.html#sec:task_input_using_dependency_resolution_results

### Page with the problem

https://docs.gradle.org/current/samples/sample_tasks_with_dependency_resolution_result_inputs.html

**Comment by ljacomet** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

**Comment by BrianWoolfolk** [comment]
Hi, I'm looking for first good issues and wanted to ask if this Issue is already taken?

If not, I would like to fix it as a good starting point. Thanks in advance!

**Comment by Sofiyan-coder** [comment]
@adam-enko I would like to work on this issue will you assign me?

**Comment by DeepanshuYadav-code** [comment]
hey @adam-enko i would like to work on this issue

can you please assign this issue to me

**Comment by AnubhavSingh99** [comment]
\assign

**Comment by AnubhavSingh99** [comment]
\assign

**Comment by AnubhavSingh99** [comment]
hey @adam-enko i would like to work on this issue

can you please assign this issue to me

**Comment by Sofiyan-coder** [comment]
@adam-enko I would like to work on this issue will you assign me?

**Comment by adam-enko** [comment]
@Sofiyan-coder @DeepanshuYadav-code @AnubhavSingh99 Hi, I don't work at Gradle, so I can't help with assigning issues. Please stop pinging me, thanks.

**Comment by Taz03** [comment]
#29930 changed the documentation, so i believe this issue no longer relevant
