### ISSUE TITLE
Drop support for obsolete shadow plugin in 9.0

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#30516]
### Issue type

Deprecation

### Problem description

The `com.github.johnrengelman.shadow` plugin is no longer maintained, there is now a much more up-to-date fork (also endorsed by the author of the original one): `io.github.goooler.shadow`.

Since [we are dropping the old file permission API](https://github.com/gradle/gradle/pull/28436) in Gradle `9.0`, the old plugin won't any longer work with Gradle at all.

It's time to fully endorse the new fork in Gradle too. Update all tests and documentation.

### Update

**`com.gradleup.shadow`** seems to be the even more recent plugin to use.

**Comment by ciscoo** [comment]
`com.gradleup.shadow` is the ID now since it moved to an organization.
