### ISSUE TITLE
Remove inconsistency between Problems.throwing and Problems.rethrowing

### ISSUE THREAD

**Issue by donat** [gradle/gradle#30544]
> The rethrowing() method takes an exception parameter, however the throwing() method expects the action to attach an exception to the problem spec. So we have inconsistent patterns for providing a mandatory parameter. The original intent for throwing was that Gradle would create the exception, not the caller. So, we've ended up with 2 methods that do the same thing.

Tasks: 
- Problems.rethrowing() should be deleted
- If no exception specified, we should throw `ProblemAwareException`
- (If exception `cause` is specified, `problems.throwing()` should throw `ProblemAwareException(cause)`)

**Comment by M-Lazeba** [comment]
Hey @donat , the description above mentions `ProblemAwareException`, which I think is a good idea, but there is no sign of it in the commit or anywhere in the repository. As far as I see you are just throwing RuntimeException there now. Can you please elaborate why and what happened with ProblemAwareException idea?

**Comment by donat** [comment]
Ah yes, those were just my notes from a meeting.  The last sentence is invalid, we don't plan to use wrapper exceptions.
