### ISSUE TITLE
"multi-project build that contains two subproject" shows example with 3 subprojects?

### ISSUE THREAD

**Issue by louwers** [gradle/gradle#30567]
### Issue type

Wrong or misleading information

### Problem description

![image](https://github.com/user-attachments/assets/b6c3b842-a13c-490e-b8d3-3078ae9de40f)

The image shows 3 subprojects, while the text speaks of 2 subprojects.

### Page with the problem

https://docs.gradle.org/current/userguide/intro_multi_project_builds.html#sec:project_structure

**Comment by eskatos** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.
