### ISSUE TITLE
Automatic modules are not detected when MANIFEST.MF is not the 1st or 2nd entry

### ISSUE THREAD

**Issue by kelemen** [gradle/gradle#30589]
### Current Behavior

If a jar doesn't have its MANIFEST.MF as the 1st or 2nd entry, then [JavaModuleDetector](https://github.com/gradle/gradle/blob/8716158d3ec8c59e38f87a67f1f311f297b79576/subprojects/core/src/main/java/org/gradle/internal/jvm/JavaModuleDetector.java#L153) will not detect its `Automatic-Module-Name` which in turn will make Gradle believe it is a non-modular jar.

The consequence of this is that you can't use the jar in a modular context.

### Expected Behavior

Gradle should detect the `Automatic-Module-Name` even if the MANIFEST.MF is not the 1st or the 2nd entry.

I believe if the `containsAutomaticModuleName(jarStream)` would be after the loop, then it would solve this issue (though I haven't tested it).

### Self-contained Reproducer Project

See <https://github.com/kelemen/gradle-automatic-module-bug>

And run `./gradlew compileJava`

Which will fail with "error: module not found: org.jdbi.v3.core" even though the manifest entry is there in the jar.

### Gradle version

8.10.1

**Comment by eskatos** [comment]
Hi Attila,
Thank you for the report. Unfortunately, the JDK's own implementation assumes that manifest entry is first or second even though the JAR specification doesn't say anything about the manifest entry position. A quick search around the interwebs shows that lots of tools fail in the same way. We have no intention to change that behavior. You should look into getting these JARs fixed.

**Comment by kelemen** [comment]
@eskatos To be honest most things work with whatever manifest entry position. And this looks like a trivial fix to me in Gradle. You just have to put the check after the loop in `JavaModuleDetector`.

**Comment by kelemen** [comment]
In fact, if that code was changed to use `JarFile` instead of `JarInputStream` it would likely be even more efficient (not that it matters that much).

**Comment by kelemen** [comment]
Actually, I misread the code of `JarInputStream`, it indeed is limited. However, `JarFile` is not, so the technically the JDK doesn't have this limitation, and I believe that even with `JarFile` this is not a big thing to fix. I won't have time for anything for a few weeks at lease, but after that I can volunteer to fix this issue.
