### ISSUE TITLE
Configuration cache failure for lambda `DefaultScriptCompilationHandler$1`

### ISSUE THREAD

**Issue by VincentMasselis** [gradle/gradle#30606]
### Current Behavior

When running Gradle 8.9 or 8.10.+ this exception is fired:
```
Gradle runtime: cannot serialize object of type 'org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$1', a subtype of 'java.lang.ClassLoader', as these are not supported with the configuration cache.
```

When running Gradle 8.7, there is no issue and build succeed

### Expected Behavior

No exception is fired, configuration cache works as expected and the build too

### Context (optional)

I'm only facing this issue when running a C.I., on my local machine it seems to work

### Self-contained Reproducer Project

I'm work on this OSS project: https://github.com/VincentMasselis/TPMS-advanced

The code running gradle 8.10.1 which fails is accessible on this PR: https://github.com/VincentMasselis/TPMS-advanced/pull/73

A sample of failed github action is visible here: https://github.com/VincentMasselis/TPMS-advanced/actions/runs/10925145018/job/30325939804?pr=73
Build's configuration-cache report [is accessible into the artifacts section](https://github.com/VincentMasselis/TPMS-advanced/actions/runs/10925145018/artifacts/1948673155) from the action directly.

You can clone and fetch the repo by yourself, the project works immediately as long you're using Android Studio

### Gradle version

8.10.1

### Gradle version that used to work

8.7

### Build scan URL (optional)

https://gradle.com/s/ekjn4g4ea4gvs

### Your Environment (optional)

Failure seems to occur only on Github runners, my local machine works as expected

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Meanwhile, @VincentMasselis can you please try using `8.10.2-branch-bamboo_cc_release_30498_i-20240913194325+0000` nightly as described [here](https://github.com/gradle/gradle/issues/30498#issuecomment-2350065660)?

**Comment by VincentMasselisDecathlon** [comment]
@ov7a 
Unfortunately, it fails for the same reasons at the same point with the nightly build :(

GH Action job: https://github.com/VincentMasselis/TPMS-advanced/actions/runs/10942892345/job/30380989071
Scan: https://gradle.com/s/nxstdgs7acnzw
Configuration cache report: https://github.com/VincentMasselis/TPMS-advanced/actions/runs/10942892345/artifacts/1953611788

**Comment by VincentMasselis** [comment]
@ov7a 
Unfortunately, it fails for the same reason at the same point with the nightly build :(

GH Action job: https://github.com/VincentMasselis/TPMS-advanced/actions/runs/10942892345/job/30380989071
Scan: https://gradle.com/s/nxstdgs7acnzw
Configuration cache report: https://github.com/VincentMasselis/TPMS-advanced/actions/runs/10942892345/artifacts/1953611788

**Comment by mlopatkin** [comment]
Looks like we're serializing some compilation errors captured by the problems API here:
```markdown
cannot serialize object of type `org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler$1`, a subtype of `java.lang.ClassLoader`, as these are not supported with the configuration cache.
    - field `classLoader` of `org.codehaus.groovy.control.SourceUnit`
        - bean of type `org.codehaus.groovy.control.SourceUnit`
            - field `source` of `org.codehaus.groovy.control.messages.SyntaxErrorMessage`
                - bean of type `org.codehaus.groovy.control.messages.SyntaxErrorMessage`
                    - field `errors` of `org.codehaus.groovy.control.ErrorCollector`
                        - bean of type `org.codehaus.groovy.control.ErrorCollector`
                            - field `collector` of `org.codehaus.groovy.control.MultipleCompilationErrorsException`
                                - bean of type `org.codehaus.groovy.control.MultipleCompilationErrorsException`
                                    - field `cause` of `org.gradle.groovy.scripts.ScriptCompilationException`
                                        - bean of type `org.gradle.groovy.scripts.ScriptCompilationException`
                                            - bean of type `com.google.common.collect.HashMultimap`
                                                - field `delegate` of `com.google.common.collect.Synchronized$SynchronizedMultimap`
                                                    - bean of type `com.google.common.collect.Synchronized$SynchronizedMultimap`
                                                        - field `problems` of `org.gradle.internal.enterprise.impl.DefaultGradleEnterprisePluginAdapter`
                                                            - bean of type `org.gradle.internal.enterprise.impl.DefaultGradleEnterprisePluginAdapter`
                                                                - Gradle runtime
```

**Comment by mlopatkin** [comment]
@VincentMasselis, in the meantime, if you want to work around this, you should stop intercepting the compilation exception [there](https://github.com/VincentMasselis/TPMS-advanced/blob/409b64c2f1a63aae805639bac01c60bc36d69f91/build.gradle.kts#L20-L26) and use some other way to find if the secrets are usable.

**Comment by mlopatkin** [comment]
A minimized reproducer can be found here: https://github.com/mlopatkin/gradle-issue-reproducers/tree/30606-problem-api-cc-issue

**Comment by VincentMasselis** [comment]
@mlopatkin Your workaround works as expected, I replaced the file loading by a json file parsed during gradle initialization phase. I'm no longer facing any issue with configuration cache now !

**Comment by bamboo** [comment]
Hey @gradle/bt-ide-experience, do you intend to provide a fix for 8.11?

**Comment by donat** [comment]
The work that we mentioned will replace the field causing the problem is still in development. It won't happen in Gradle 8.11.

**Comment by donat** [comment]
At the same time, the offending field is not yet being used. My understanding is that removing it would resolve the issue and we'll take care of it.

**Comment by reinsch82** [comment]
We don't need to add anything to the release notes.
