### ISSUE TITLE
Improve documentation for publishing custom artifacts

### ISSUE THREAD

**Issue by cornergraf** [gradle/gradle#3064]
I am trying to publish my custom RPM artifact, but the documentation is really unclear about how this should be done.

### Current Gradle Script
This is what I have so far:

```
project(':path:to:rpm:project') {
  
    apply plugin: "java"
    apply plugin: "maven-publish"

    publishing {
        repositories {
            maven {
                credentials {
                    username 'aaa'
                    password 'sss'
                }
                url "https://url/to/repository"
            }
        }

        publications {
            pub(MavenPublication) {
                artifact 'our-software-rpm' {

                }
            }
        }
    }

    task rpmArtifact(dependsOn: 'installerMakeRpm') {
        ext.rpmfile = file("$project.buildDir/tmp/rpmbuild/RPMS/x86_64/our-software.x86_64.rpm")
    }

    artifacts {
        archives(rpmArtifact.rpmfile) {
            name 'our-software-rpm'
            type 'rpm'
            builtBy rpmArtifact
        }
    }

    assemble.dependsOn rpmArtifact
}
```

### What I need help with
I am unsure how I should reference the custom RPM artifact in the publications closure. Using the artifact name ('our-software-rpm') does not work, using the name of the task (rpmArtifact) does not work either. So what should I do?

The documentation **really** needs to be made clear how such a scenario is supposed to work.

### Your Environment
Windows 10
Gradle 3.5

**Comment by oehme** [comment]
The [JavaDoc](https://docs.gradle.org/current/javadoc/org/gradle/api/publish/maven/MavenPublication.html#artifact(java.lang.Object)) lists all the things that are accepted by a `MavenPublication`. Among them is the `PublishArtifact` that `ArtifactHandler#add()` returns. E.g. something like this should work:

```
def myRpm = artifacts.add('archives', myRpmTask.outputFile) {
 // more configuration
}

publishing {
  publications {
    pub(MavenPublication) {
      artifact myRpm
    }
  }
}
```

**Comment by oehme** [comment]
@marcphilipp This was the issue that prompted me to put "documentation for publishing artifacts" on the list to improve.

**Comment by marcphilipp** [comment]
Thanks for letting me know! I already added it to the documentation epic. 🙂
