### ISSUE TITLE
useGpgCmd stopped working in v 8.10.1

### ISSUE THREAD

**Issue by dhakehurst** [gradle/gradle#30645]
### Current Behavior

 A problem occurred starting process 'command 'gpg''

I upgraded from version 8.8 to 8.10.1 and now get this error.

### Expected Behavior

it should work!

### Self-contained Reproducer Project

https://github.com/dhakehurst/kotlin.gradle.plugin.exportPublic/tree/main/net.akehurst.kotlin.gradle.plugin

### Gradle version

8.10.1

**Comment by dhakehurst** [comment]
MacOS

 gpg --version
gpg (GnuPG/MacGPG2) 2.2.41
libgcrypt 1.8.10
Copyright (C) 2022 g10 Code GmbH

**Comment by ov7a** [comment]
Sorry, I haven't been able to reproduce your issue.
It seems that there was some kind of environment issue or a different problem with the Gradle version upgrade.

Since there are no details about the error (e.g., error message and stack trace) and we [have coverage](https://github.com/search?q=repo%3Agradle%2Fgradle+useGpgCmd%28%29+path%3Aplatforms%2Fsoftware%2Fsigning%2Fsrc%2FintegTest%2Fgroovy%2Forg%2Fgradle%2Fplugins%2Fsigning%2F*&type=code) for `useGpgCmd`, I'm closing this as reproducible.

**Comment by dhakehurst** [comment]
For Information of anyone else that arrives here.

The problem may be connected to an upgrade of gpg performed by homebrew that occurred at the same time as I upgraded gradle.

Or something changed in the required values of the signing.** properties in gradle.

I updated all of the settings in my global gradle.properties file

```
signing.gnupg.executable=/usr/local/bin/gpg
signing.gnupg.useLegacyGpg=true
signing.gnupg.homeDir=/Users/akehurst/.gnupg
signing.gnupg.keyName=...
signing.gnupg.passphrase=...
```

and it now works again.

**Comment by bubenheimer** [comment]
I had to add this in my global gradle.properties to get it to work again, thanks for the pointer, @dhakehurst 

```
signing.gnupg.executable=/usr/local/bin/gpg
```

This was not needed before. Gradle used to be able to find the executable without this, and gpg is on my PATH, so I'm guessing that's what changed in Gradle. (I'm using 8.12.1)

@ov7a time to reopen?

**Comment by ov7a** [comment]
@bubenheimer Can you craft a reproducer project, please? For now, I still think this is an environment issue. 

What does
```
which gpg
```
show in your case?

If you look at the [sources](https://github.com/gradle/gradle/blob/6b2ef170a1636ef7a638d8bb28a0c4d759e46e59/platforms/software/signing/src/main/java/org/gradle/security/internal/gnupg/GnupgSettings.java#L51), Gradle just calls `gpg` executable, relying on the standards OS mechanism to resolve the executable.

The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

**Comment by bubenheimer** [comment]
@ov7a It appears @dhakehurst already provided a reproducer.

It's `/usr/local/bin/gpg`. Don't see anything unusual there.

**Comment by ov7a** [comment]
> @ov7a It appears @dhakehurst already provided a reproducer.

But it's a regular project. As I said, I can't reproduce it. With GH action from the [reproducer template](https://github.com/gradle/gradle-issue-reproducer/blob/kotlin-dsl/.github/workflows/run-reproducer.yml), you can reproduce the environment as well.

**Comment by bubenheimer** [comment]
@ov7a what environment did you use to try the repro?

**Comment by bubenheimer** [comment]
I'm on MacOS 15.2 with gpg from GPG Suite (MacGPG 2.2.41). I've never used homebrew on this machine. I'd say it's a pretty vanilla MacOS install.

Perhaps it's related to MacOS 15.x - not sure what @dhakehurst was on. MacOS 15 has a lot of custom permissions, something may not be granted and got in the way.

**Comment by bubenheimer** [comment]
@dhakehurst may have been off by one minor release. It works for me with 8.10.1 and stops working at 8.10.2.

**Comment by Omico** [comment]
> I had to add this in my global gradle.properties to get it to work again, thanks for the pointer, [@dhakehurst](https://github.com/dhakehurst)
> 
> ```
> signing.gnupg.executable=/usr/local/bin/gpg
> ```

@bubenheimer, I think we are experiencing the same thing. I must add `signing.gnupg.executable=/usr/local/bin/gpg` into `~/.gradle/gradle.properties`.

I just bought a new Mac a few months ago. And this is my first time running the sign tasks on this Mac.

```
A problem occurred starting process 'command 'gpg''
> Could not start 'gpg'
  > Cannot run program "gpg" (in directory "/Users/omico/Git/xxxx/xxx"): error=2, No such file or directory
    > error=2, No such file or directory
```

```
gpg --version
gpg (GnuPG/MacGPG2) 2.2.41
libgcrypt 1.8.10
Copyright (C) 2022 g10 Code GmbH
```

```
which gpg    
/usr/local/bin/gpg
```

**Comment by petarov** [comment]
Explicitly setting `signing.gnupg.executable` fixed the problem on my side as well, e.g.,

```
signing.useGpgCmd=true
signing.gnupg.executable=/opt/homebrew/bin/gpg
signing.gnupg.keyName=...
signing.gnupg.passphrase=....
```
