### ISSUE TITLE
Stable directory toolchain detection

### ISSUE THREAD

**Issue by toxn** [gradle/gradle#30644]
### Expected Behavior

On Linux, toolchain detection yield a stable link to the jdk/jre installation path, eventually querying `alternatives` to retrieve it, e.g.

```
 + Red Hat, Inc. JDK 21.0.4+7
     | Location:           /usr/lib/jvm/java-21-openjdk
     | Language Version:   21
     | Vendor:             Red Hat, Inc.
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM
```

### Current Behavior (optional)

toolchain detection returns the exact directory where jre/jdk is installed, e.g. 

```
 + Red Hat, Inc. JDK 21.0.4+7
     | Location:           /usr/lib/jvm/java-21-openjdk-21.0.4.0.7-2.fc41.x86_64
     | Language Version:   21
     | Vendor:             Red Hat, Inc.
     | Architecture:       amd64
     | Is JDK:             true
     | Detected by:        Current JVM
```

### Context

Some IDE/build tools may refer to or cache the toolchain location returned by gradle. In that case, the current behavior returns a path that is almost never stable in time

**Comment by eskatos** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

If we provided the toolchain path as the major version symlink (`/usr/lib/jvm/java-21-openjdk` above) then the IDE would use it transparently across minor upgrades, it would have to figure out it changed underneath and reindex, we don't know if the IDE is currently capable of this.

Relates to
* https://github.com/gradle/gradle/issues/16628
* https://github.com/gradle/gradle/issues/22495

**Comment by jvandort** [comment]
IMO having a non-stable path allows IDEs to detect when the underlying toolchain changes without needing to deeply inspect the contents of the toolchain files. I think breaking caches when a toolchain version changes is a safer and more conservative option here.

We don't want to change this at this time.
