### ISSUE TITLE
Unformatted Markdown link in 'Working With Files'

### ISSUE THREAD

**Issue by adam-enko** [gradle/gradle#30676]
### Issue type

Styling or Accessibility

### Problem description

> To copy the contents of other JAR files into the application JAR, use the ../dsl/org.gradle.api.Project.html#org.gradle.api.Project:zipTree(java.lang.Object)[Project.zipTree(java.lang.Object)] method 

<img width="906" alt="image" src="https://github.com/user-attachments/assets/2cf745ac-583e-419b-9092-4b44b150ad19">

### Page with the problem

https://docs.gradle.org/current/userguide/working_with_files.html#using_project_ziptree_and_the_jar_task

**Comment by cobexer** [comment]
Fixed by:
* https://github.com/gradle/gradle/pull/30728
