### ISSUE TITLE
Extensions: create ExtensiblePolymorphicDomainObjectContainer - Cannot have abstract method NamedDomainObjectCollection.getAsMap()

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#30684]
### Current Behavior

```kotlin
interface MyData : org.gradle.api.Named

extensions.create<ExtensiblePolymorphicDomainObjectContainer<MyData>>("myBase")
```
```stacktrace
> Failed to apply plugin 'my-plugin'.
   > Could not create an instance of type org.gradle.api.ExtensiblePolymorphicDomainObjectContainer.
      > Could not generate a decorated class for type ExtensiblePolymorphicDomainObjectContainer.
         > Cannot have abstract method NamedDomainObjectCollection.getAsMap().
```

### Expected Behavior

No error

### Context (optional)

I as a plugin author want to create a top-level `ExtensiblePolymorphicDomainObjectContainer` extension to register different subtypes as plugin user.

If I try to use this workaround, I get another error: 
```kotlin
extensions.add("myBase", objects.polymorphicDomainObjectContainer(MyData::class))
```

```
Type mismatch: inferred type is NamedDomainObjectContainer<MyData> but ExtensiblePolymorphicDomainObjectContainer<MyData> was expected
```

### Self-contained Reproducer Project

[sample3.zip](https://github.com/user-attachments/files/17116728/sample3.zip)

### Gradle version

8.10.1

**Comment by eskatos** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

`ExtensionContainer.create(...)` is convenient to create basic objects but polymorphic containers require more.
You can create them using `ObjectFactory.domainObjectContainer(...)` or `ObjectFactory. polymorphicDomainObjectContainer(...)`.

`ObjectFactory` is the go to service for creating different types of objects that are managed by the Gradle runtime.
`ExtensionContainer` sole responsibility is to hold extension objects. We won't duplicate `ObjectFactory` capabilities in `ExtensionContainer`.

Please see the related [documentation](https://docs.gradle.org/current/userguide/collections.html#extensiblepolymorphicdomainobjectcontainer).

**Comment by hfhbd** [comment]
Okay, then I will create a new issue because the workaround using ObjectFactory also does not work because it does not expose a `ExtensiblePolymorphicDomainObjectContainer` but a  `NamedDomainObjectContainer`:

```
extensions.add("myBase", objects.polymorphicDomainObjectContainer(MyData::class))
```
