### ISSUE TITLE
Status of composite build support for native libraries

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#3068]
> Native builds are not supported. (Binary dependencies are not yet supported for native builds).
> \- [Current Limitations](https://docs.gradle.org/current/userguide/composite_builds.html#current_limitations_and_future_work)

Searching the issues this doesn't seem to be something anyone has discussed in any open or closed issues.

Is there a plan to support this in the future? Are there specific work items that need to be undertaken for this to work? What limitations cause this to not work?

**Comment by big-guy** [comment]
We're going to talk about it more soon as a follow up to the post [State and future of the Gradle Software Model](https://blog.gradle.org/state-and-future-of-the-gradle-software-model), but we've been doing some work on this (and other native related things) in master.  [A sample of composite builds working](https://github.com/gradle/native-samples/tree/master/cpp/composite-build).
