### ISSUE TITLE
Duplicate text

### ISSUE THREAD

**Issue by SesamePig** [gradle/gradle#30703]
### Issue type

Wrong or misleading information

### Problem description

https://docs.gradle.org/current/userguide/implementing_custom_tasks.html#annotating_inputs_and_outputs
![微信截图_20240926094516](https://github.com/user-attachments/assets/0c1337ed-3cc5-40e4-b516-1f0cf08128c4)

### Page with the problem

https://docs.gradle.org/current/userguide/implementing_custom_tasks.html#annotating_inputs_and_outputs

**Comment by eskatos** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

**Comment by Ahar28** [comment]
Hi @eskatos , this issue has already been resolved by #30086 .

**Comment by eskatos** [comment]
Thank you @Ahar28!
