### ISSUE TITLE
continuousBuild.adoc references JDK-8145981 as a persisting problem, but the issue is closed as fixed

### ISSUE THREAD

**Issue by ewirch** [gradle/gradle#3072]
The page says:

> On Linux, OpenJDK’s implementation of the file watch service can sometimes miss file system events (see: JDK-8145981).

However, JDK-8145981 is closed as "fixed" since 2015-12-30.

**Comment by bmuschko** [comment]
The issue might be closed for a specific version of the JDK. However, if the user runs the build with an older version than the fix version then there's still the possibility of this side effect occurring. I'd rather keep that in the documentation.
