### ISSUE TITLE
Component metadata rules

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3076]
Component metadata rules can currently only adjust the `status` and `statusScheme` of a component. Often the dependency metadata is also wrong, e.g. a version range is too strict or a hard dependency should actually be an optional one.

Today users can work around some of these use cases with dependency resolution rules. But these rules only give access to one dependency at a time and provide no context about where that dependency is coming from. Adding/removing is not possible. Also, the same rule has to be repeated on every `Configuration` that uses the dependency in question. 

This will become even more problematic with variant aware dependency resolution, as dependencies may need to be adjusted depending on the variant of the component. Repeating these adjustments on every usage site would become tedious and error prone.

Instead, allow users to correct the dependency metadata of a component once and use that corrected information when resolving any `Configuration`.

Stuff to do to complete:
- [ ] Fix rules so that `it` is not required for things like `withDependencyConstraints { it.removeAll {  it.group == 'junit' }}`

**Comment by oehme** [comment]
We should break this down further, it is currently hard to estimate.

**Comment by jjohannes** [comment]
= Analysis with Spike =

**Comment by jjohannes** [comment]
@oehme I removed my comment above, turned this one into an Epic and I am creating individual issues now.

**Comment by jjohannes** [comment]
Extended _Component Metadata Rules_ have been delivered with 6.0.

Follow ups are done as part of #3395.
