### ISSUE TITLE
Deprecate --no-rebuild

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3077]
This option was introduced very early in Gradle's life when up-to-date checking was still rather expensive. This is no longer the case. Removing this option removes a bit of complexity and avoids confusion on the user side as to when they might want to use it.

**Comment by bmuschko** [comment]
It would be interesting to know if we really optimized enough to let this option go away. Imagine you have a multi-project build with 300 subprojects but only touched 1 that you want to build. Do we know if up-to-date checking is fast enough in those scenarios. A performance test that compares both scenarios would be important to have IMHO.

Can you explain why the command line option is confusing to users?

**Comment by oehme** [comment]
> Imagine you have a multi-project build with 300 subprojects but only touched 1 that you want to build.

We have performance tests with 500 subprojects and doing a [single line change](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/8772431:id/report-performance-performance-tests.zip%21/report/tests/assemble-for-non-abi-change-on-largeJavaMultiProject.html) takes just ~1s more than [calling `help`](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/8772431:id/report-performance-performance-tests.zip%21/report/tests/configure-largeJavaMultiProject.html) on it. 

> Can you explain why the command line option is confusing to users?

Because it doesn't even work in all cases and we have no intention to fix it.

**Comment by oehme** [comment]
I've added some comments to [this commit](https://github.com/gradle/gradle/commit/614bd5896a5bbc8205519c8d37dfc69b0ad00b9c). We shouldn't create deprecation warnings in the parameter parser. We should create them when the start parameters are [validated](https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/StartParamsValidatingActionExecuter.java#L37) later. Otherwise we won't get the warning when:

- running in embedded mode
- setting options through gradle.properties
- settings options programatically

Can you please open a new issue to refactor this logic?

**Comment by blindpirate** [comment]
@oehme Sure, I think we could open an issue like "refine deprecation warning handling" to handle all these stuff.
