### ISSUE TITLE
Upgrade smoke test versions

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3080]

**Comment by oehme** [comment]
@blindpirate Why did we reopen this?

**Comment by blindpirate** [comment]
@oehme There's some failure with latest android plugin https://builds.gradle.org/viewLog.html?buildId=8663193&buildTypeId=Gradle_Check_SmokeTests&tab=buildResultsDiv

Not sure if it's environment-related and I'm investigating it now.

**Comment by oehme** [comment]
Let's open an environment issue instead.
