### ISSUE TITLE
Using Gradle 8.11 project.exec is deprecated but providers.exec is not executed

### ISSUE THREAD

**Issue by wolfseifert** [gradle/gradle#30811]
### Current Behavior

As of Gradle 8.11 project.exec is deprecated. One should use ExecOperations or ProviderFactory exec instead. But my provider.exec is never executed.

The same is true for javaexec.

Here is my small reproducer:

<pre>
tasks.register("a", Exec::class) {
  group = "my"
  executable = "echo"
  args("AAAAAAAAAAAAAA")
}

tasks.register("b") {
  group = "my"
  doLast {
    project.exec {
      executable = "echo"
      args("BBBBBBBBBBBBBBB")
    }
  }
}

tasks.register("c") {
  group = "my"
  doLast {
    providers.exec {
      executable = "echo"
      args("CCCCCCCCCCCCCCC")
    }
  }
}

open class D @Inject constructor(@Internal val execOperations: ExecOperations) : DefaultTask()

tasks.register&lt;D&gt;("d") {
  group = "my"
  doLast {
    execOperations.exec {
      executable = "echo"
      args("DDDDDDDDDDDD")
    }
  }
}
</pre>

<pre>
$ gradle a b c d

&gt; Task :a
AAAAAAAAAAAAAA

&gt; Task :b
BBBBBBBBBBBBBBB

&gt; Task :c

&gt; Task :d
DDDDDDDDDDDD
</pre>

### Expected Behavior

provider.exec should be excuted.

### Self-contained Reproducer Project

<pre>
tasks.register("a", Exec::class) {
  group = "my"
  executable = "echo"
  args("AAAAAAAAAAAAAA")
}

tasks.register("b") {
  group = "my"
  doLast {
    project.exec {
      executable = "echo"
      args("BBBBBBBBBBBBBBB")
    }
  }
}

tasks.register("c") {
  group = "my"
  doLast {
    providers.exec {
      executable = "echo"
      args("CCCCCCCCCCCCCCC")
    }
  }
}

open class D @Inject constructor(@Internal val execOperations: ExecOperations) : DefaultTask()

tasks.register&lt;D&gt;("d") {
  group = "my"
  doLast {
    execOperations.exec {
      executable = "echo"
      args("DDDDDDDDDDDD")
    }
  }
}
</pre>

### Gradle version

8.11

### Your Environment (optional)

ArchLinux

**Comment by wolfseifert** [comment]
I learned now that providers.exec input and output streams cannot be configured. Therefore its output will always be missing. But even than you still need a .result.get().

Here is the working version of the above program
<pre>
tasks.register("a", Exec::class) {
  group = "my"
  executable = "touch"
  args("A")
}

tasks.register("b") {
  group = "my"
  doLast {
    project.exec {
      executable = "touch"
      args("B")
    }
  }
}

tasks.register("c") {
  group = "my"
  doLast {
    providers.exec {
      executable = "touch"
      args("C")
    }<b>.result.get()</b>
  }
}

open class D @Inject constructor(@Internal val execOperations: ExecOperations) : DefaultTask()

tasks.register&lt;D&gt;("d") {
  group = "my"
  doLast {
    execOperations.exec {
      executable = "touch"
      args("D")
    }
  }
}
</pre>

So I am closing this issue...

**Comment by bric3** [comment]
If anyone stumble on this as well, one can access the stream via `standardOutput` or `standardError`.

E.g.


```
    val stopYarnServer by registering(Exec::class) {
        commandLine("bash", "-c", "kill ${'$'}(lsof -t -i :${port.get()})")
+       val lsof = providers.exec {
+           isIgnoreExitValue = true
+           commandLine("lsof", "-t", "-i", ":${port.get()}")
+       }

        onlyIf {
-           val output = ByteArrayOutputStream()
-           exec {
-               isIgnoreExitValue = true
-               commandLine("lsof","-t", "-i", ":${port.get()}")
-               standardOutput = output
-           }
-           return@onlyIf output.toString().isNotEmpty()
+           return@onlyIf lsof.standardOutput.asText.get().isNotEmpty()
        }
    }
```
