### ISSUE TITLE
Gradle Tutorial Wrong Code

### ISSUE THREAD

**Issue by gitubanana** [gradle/gradle#30813]
### Issue type

Wrong or misleading information

### Problem description

> First of all, Thank you for developing this amazing service and reading my issue!
> I was learning Gradle Tutorial. And I found a code which doesn't work.
> I wish I could open a PR, but sadly I couldn't find the file that contains this code... sorry for my ignorance...
> Lastly, I'm not that good at English... sorry for that too...

[In this tutorial](https://docs.gradle.org/current/userguide/part2_gradle_tasks.html#step_2_understanding_tasks), I found this code **which doesn't work**.<br>
```groovy
tasks.register(Copy, "copyTask") {
    from("source")
    into("target")
    include("*.war")
}
```

I was kind of confused. Because I thought tutorials always contain right information.
After hours of searching, I found this code **which works** [in this page](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#built_in_task_types).<br>
```groovy
tasks.register("copyTask",Copy) {
    from("source")
    into("target")
    include("*.war")
}
```

So, I think that code in the tutorial should be modified for beginners who might be confused.
After all, It's a very tiny issue.
Thank you for reading this issue. Have a nice day :)

### Page with the problem

https://docs.gradle.org/current/userguide/part2_gradle_tasks.html#step_2_understanding_tasks

**Comment by ov7a** [comment]
Thanks for report, it's already fixed in
* https://github.com/gradle/gradle/pull/30700

It's on master and will be available soon with the next Gradle release.

**Comment by gitubanana** [comment]
Silly me, I didn't know that... Sorry for my useless issue...
And thanks a lot for all your detailed information! 😀
Wishing you a great day!

**Comment by ov7a** [comment]
No problem!
