### ISSUE TITLE
Don't ask for user input on non-interactive console

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3081]
__Current behavior:__

Currently, we do not detect if the console is interactive. We simply try to request user input. If it's not supported on the low level then we return `null`.

__Desired behavior:__

- The use of `UserInputHandler` should detect if the console supports interactive mode.
- If the console is not interactive then the question is not rendered and no user input is requested.

__Implementation:__

- Console interactive detection needs to work on Unix and Windows.
- Console interactive detection needs to work daemon and no-daemon mode.
- Console interactive detection likely needs to happen on the client-side and not the daemon side.
- At this time we don't have any code in place that can detect interactive mode in console independent of OS.
- For now we could probably use `ConsoleDetector`. If the `ConsoleMetaData` is not null and standard output is available then we can assume that standard input is available. We could potentially hook that into `ConsoleConfigureAction` (which already initialized the console) and pass this information along to `UserInputHandler`.

__Test cases:__

- Existing test cases for interactive user input keep passing.
- If the console is not interactive then the question is not rendered. No user input is requested. The method `UserInputHandler.askYesNoQuestion` returns `null`. This test cases works on Unix and Windows.

**Comment by bmuschko** [comment]
@oehme While implementing a spike I detected more requirements:

- Needs to work with Gradle command line in no-daemon and daemon mode
- Needs to work with Gradle core's integration testing tooling for in-process and forked mode (and can emulate interactive mode)
- Needs to work with the Tooling API in in-process and daemon mode
- Needs to work with `GradleRunner` in embedded and daemon mode

I put together some code that passes the tests and seems to work as expected. However, it feels a bit assumptious and probably needs the slightly different approach.

- The interactive flag probably doesn't belong into `StartParameter`.
- The tooling API assumes that the console is interactive if standard input was provided.

Could you please [have a look at the code](https://github.com/gradle/gradle/compare/release...bm/detect-interactive-console) and let me know what you think before I even open a PR?

**Comment by oehme** [comment]
> The interactive flag probably doesn't belong into StartParameter.

I don't have a better place for it either. The other logging options are handled there as well.

> The tooling API assumes that the console is interactive if standard input was provided.

I think that's a relatively safe assumption.

The other assumption about the console being interactive if stdOut is available seems like a bigger issue. How does stdOut tell us that it is interactive? Don't all consoles provide stdOut (you need to write something after all)? I guess we are missing interactive detection in native platform?

I'm fine with having such a workaround for now if it works out in practice, but I think we should open a follow-up issue for 4.4 to detect this more reliably.

An implementation hint: Instead if passing the StartParameter into the DefaultUserInputHandler and adding an if-statement on every request it would be nice if we just created a `NonInteractiveUserInputHandler` and doing the if-statement once in the service registry.

**Comment by bmuschko** [comment]
> The other assumption about the console being interactive if stdOut is available seems like a bigger issue. How does stdOut tell us that it is interactive? Don't all consoles provide stdOut (you need to write something after all)? I guess we are missing interactive detection in native platform?

I instead changed the implementation to check if `System.console()` returns `null`. I think that's probably a safe approach as long as you run that code on the client-side. I also tested the changes on a run of a build on Jenkins that asks for user input.

> An implementation hint: Instead if passing the StartParameter into the DefaultUserInputHandler and adding an if-statement on every request it would be nice if we just created a NonInteractiveUserInputHandler and doing the if-statement once in the service registry.

Done in the [PR](https://github.com/gradle/gradle/pull/3106).
