### ISSUE TITLE
Configuration rules are not consulted for intra project references

### ISSUE THREAD

**Issue by mcumings** [gradle/gradle#30829]
### Current Behavior

If a `Configuration` rule is defined on a producer project then any attempt to reference a configuration handled by that rule in a consuming project will fail similar to the following:

```
 A dependency was declared on configuration 'producerConfig' of 'root project :' but no variant with that configuration name exists.
```

### Expected Behavior

Configuration rules should be consulter before failing.

### Context (optional)

We have a project which defines tasks dynamically via a `tasks.addRule` definition, where the task name is a datetime specification (e.g., `2024-10-07`).  We have other consuming projects which directly reference these tasks in order to gain access to their task outputs for consumption.

We are trying to replace this anti-pattern with proper cross-project output sharing through the use of configurations and artifacts in order to support project isolation requirements.  We noticed that `ConfigurationContainer` supports rules so we tried this approach and subsequently failed.

### Self-contained Reproducer Project

Given a root project with the following `build.gradle.kts` file:
```kotlin
tasks.register("clean", Delete::class.java) {
    delete(project.layout.buildDirectory)
}

abstract class ProducerTask : DefaultTask() {
    @get:OutputFile
    abstract val output: RegularFileProperty

    @TaskAction
    fun run() {
        logger.lifecycle("ProducerTask")
        output.asFile.get().writeText(System.currentTimeMillis().toString())
    }
}

configurations.addRule("producerRule", object : Action<String> {
    override fun execute(configurationName: String) {
        if (configurationName == "producerConfig") {
            configurations.consumable(configurationName)
            val producerTask = tasks.register("$configurationName-task", ProducerTask::class.java) {
                output.set(layout.buildDirectory.file("producer.txt"))
            }
            project.artifacts.add(configurationName, producerTask)
        }
    }
})
```

and a `:consumer` project with the following `build.gradle.kts` file:
```kotlin
abstract class ConsumerTask : DefaultTask() {
    @get:InputFiles
    abstract val input: ConfigurableFileCollection

    @TaskAction
    fun run() {
        logger.lifecycle("ConsumerTask")
        input.files.forEach { file ->
            logger.lifecycle("file = $file: ${file.readText()}")
        }
    }
}

tasks.register("clean", Delete::class.java) {
    delete(project.layout.buildDirectory)
}

val resolveConfig = configurations.create("consumerConfig") {
    isCanBeResolved = true
    isCanBeConsumed = false
    dependencies.add(project.dependencies.project(mapOf(
        "path" to ":",
        "configuration" to "producerConfig"
    )))
}

tasks.register("consumer", ConsumerTask::class.java) {
    input.setFrom(resolveConfig.incoming.files)
}
```

Run the following to reproduce the issue:
```
./gradlew clean consumer
```

NOTE: The reproducer does not define any artifact attributes.  Had this been a real project, attribute resolution would need to work as well.

### Gradle version

8.10.2

### Your Environment (optional)

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  17.0.6 (Azul Systems, Inc. 17.0.6+10-LTS)
Daemon JVM:    /Users/username/Library/Java/open-jdk-17.0.6.2-apple/zulu-17.jdk/Contents/Home (no JDK specified, using current Java home)
OS:            Mac OS X 14.6.1 aarch64

**Comment by abstratt** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mcumings** [comment]
> As an alternative, can you always name the Configurations the same thing and just optionally wire up the tasks based on the task rule?

In this case, I cannot.  The artifacts are datetime based (described more thoroughly in #30831) so the set of supported configurations would always be changing.
