### ISSUE TITLE
Unable to resolve a configuration into a single file for use as a Task input

### ISSUE THREAD

**Issue by mcumings** [gradle/gradle#30828]
### Current Behavior

There does not appear to be a workable way to resolve a configuration into a single output file for use as a Task input.  Various API was attempted to be used unsuccessfully (see reproducer).  Any attempts are resolving beyond `resolveConfig.incoming.files` (e.g., `resolveConfig.incoming.files.singleFile`) fails at `ConsumerTask` execution-time.

As a result, if the task being configured accepts a `File` or `Property<File>`, there is no way to properly configure it.

### Expected Behavior

Existing APIs should:
- Cause the configuration to resolve
- Resolution of the configuration should trigger the producer task
- Configurations with a single artifact file should be able to provide this artifact file as a task input

### Context (optional)

We are working toward project isolation but have some cross-project artifact sharing that requires feeding a task with a single input file.  The existing task definition cannot be changed to accept a `ConfigurableFileCollection`.  The result is that we are unable to define out project in a manner which is considered best practice and project isolation- ready.

### Self-contained Reproducer Project

The following can reproduce the project:

First, the producer module (`:`) with its `build.gradle.kts` file:
```kotlin
import org.gradle.api.artifacts.type.ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE

tasks.register("clean", Delete::class.java) {
    delete(project.layout.buildDirectory)
}

val producerConfig = configurations.consumable("producerConfig") {
    attributes {
        attribute(ARTIFACT_TYPE_ATTRIBUTE, "repro-producer")
    }
}

abstract class ProducerTask : DefaultTask() {
    @get:OutputFile
    abstract val output: RegularFileProperty

    @TaskAction
    fun run() {
        logger.lifecycle("ProducerTask")
        output.asFile.get().writeText(System.currentTimeMillis().toString())
    }
}

val producerTask = tasks.register("producer", ProducerTask::class.java) {
    output.set(layout.buildDirectory.file("producer.txt"))
}

project.artifacts.add(producerConfig.name, producerTask)
```

Second, the consumer module (`:consumer`) with its `build.gradle.kts` file:
```kotlin
import org.gradle.api.artifacts.type.ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE

abstract class ConsumerTask : DefaultTask() {
    @get:InputFiles
    abstract val input: ConfigurableFileCollection

    @TaskAction
    fun run() {
        logger.lifecycle("ConsumerTask")
        input.files.forEach { file ->
            logger.lifecycle("file = $file: ${file.readText()}")
        }
    }
}

tasks.register("clean", Delete::class.java) {
    delete(project.layout.buildDirectory)
}

val resolveConfig = configurations.create("consumerConfig") {
    isCanBeResolved = true
    isCanBeConsumed = false
    dependencies.add(project.dependencies.project(":"))
}

tasks.register("consumer", ConsumerTask::class.java) {
    /*
     * This works.  The `producer` task is automatically run and feeds the `consumer` task.
     */
    //input.setFrom(resolveConfig.incoming.files)

    // ..but I need to feed the (existing) task with a single file, not a file collection!

    /*
     * None of the following work.  The producer task is not run and the consumer task fails.
     *
     * Execution failed for task ':consumer:consumer'.
     *   > java.io.FileNotFoundException: /Users/username/src/ebay/repro-gradle-config/build/producer.txt (No such file or directory)
     */

    input.setFrom(resolveConfig.incoming.files.singleFile)

//    input.setFrom(provider { resolveConfig.incoming.files.singleFile })

    /*
     * This doesn't work either, failing with a different message:
     *
     * > Could not create task ':consumer:consumer'.
     *  > Collection is empty.
     */
//    input.setFrom(resolveConfig.incoming.files.asFileTree.single())
}
```

With the above in place, the following reproduces the failure:
```
./gradlew clean consumer
```

### Gradle version

8.10.2

### Your Environment (optional)

------------------------------------------------------------
Gradle 8.10.2
------------------------------------------------------------

Build time:    2024-09-23 21:28:39 UTC
Revision:      415adb9e06a516c44b391edff552fd42139443f7

Kotlin:        1.9.24
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  17.0.6 (Azul Systems, Inc. 17.0.6+10-LTS)
Daemon JVM:    /Users/username/Library/Java/open-jdk-17.0.6.2-apple/zulu-17.jdk/Contents/Home (no JDK specified, using current Java home)
OS:            Mac OS X 14.6.1 aarch64

**Comment by jvandort** [comment]
Does getElements work for you?
https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileCollection.html#getElements()

**Comment by mcumings** [comment]
Hah!  Somehow I missed that API while trying pretty much everything else.  It does indeed appear to work!

```
    input.setFrom(resolveConfig.incoming.files.elements.map { it.first().asFile })
```

Thanks!
