### ISSUE TITLE
Change the default to preserveFileTimestamps = false for all the archive tasks

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#30826]
### Expected Behavior

Creating a jar using `Jar` task in Gradle should be a deterministic. There should be no timestamps stored inside of it.

### Current Behavior (optional)

Today, the default behavior is `preserveFileTimestamps = true`, meaning the build output involving any archive is non-deterministic my default (e.g. creating jar).

### Context

For Gradle 9.0, we should change the default to not include timestamps on archives.

**Comment by jvandort** [comment]
We should change this for 9.0

**Comment by sschuberth** [comment]
I guess you are referring to [`preserveFileTimestamps`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:preserveFileTimestamps), not `archivePreserveFileTimestamps`.

In any case, AFAIK there is no way to completely omit timestamps when creating JARs. Setting `preserveFileTimestamps == false` will simply cause all timestamps to be set to the same fixed value. Which means in contrast to #30827 you have a loss of information, which could be a reason to *not* make `preserveFileTimestamps == false` the default. (Personally, I do not care too much about the atchived timestamps, but I could imagine that others do.)

**Comment by jvandort** [comment]
Renamed title/description to use correct property name

**Comment by sschuberth** [comment]
> Reproducibility in artifacts is likely a better default for a build tool

What about file permissions then? I guess they should be normalized, too, like [this plugin does](https://github.com/gradlex-org/reproducible-builds/blob/c45a7c496c2e27e032ec74acdb3b1fcec8f1f314/src/main/java/org/gradlex/reproduciblebuilds/ReproducibleBuildsPlugin.java#L37-L38)?

**Comment by jvandort** [comment]
What happens now if we don't set these defaults for permissions? I would expect file permissions to already be at least be stable across build invocations

**Comment by jjohannes** [comment]
> What happens now if we don't set these defaults for permissions? I would expect file permissions to already be at least be stable across build invocations

The problem here is that when you build on Windows, the files for which no explicit permission is configured have a different default permission that when building on Linux. So running the same build on Linux vs. Windows produces different results.
Maybe this can be improved by always setting a reasonable default/convention for all files.

I think this discussion should be a separate issue. All issues related to reproducibility are also discussed here: #28806

**Comment by lptr** [comment]
Let's do this as part of:

- https://github.com/gradle/gradle/issues/30871
