### ISSUE TITLE
Java compilation failures in problem report html are unintelligible

### ISSUE THREAD

**Issue by joshfriend** [gradle/gradle#30844]
### Current Behavior

The build console output is nicely formatted to put the relevant javac errors at the end of the build:

```
Execution failed for task ':common:flow:public:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler output below.
  /Users/jfriend/Development/android-register/common/flow/public/src/main/java/flow/Flow.java:28: error: class, interface, or enum expected
  asdfasdfasdf
  ^
  1 error
```

however, the new problem report html shows incomprehensible gibberish:

![image](https://github.com/user-attachments/assets/ccf084b9-0884-4ce1-aa19-69977ca603cf)

### Expected Behavior

The HTML problem report should have a readable error

### Self-contained Reproducer Project

Use `8.11-20240930074649+0000` and compile a java project that has a syntax error somewhere. 

### Gradle version

8.11-20240930074649+0000

**Comment by donat** [comment]
There are two problems happening here:
- the same report rendered three times,
- the compilation failure does not contain the formatted compiler error message.

The first one is already fixed on master; we should cherry-pick it to release.

The second needs some investigation. The report contains the error message, but we don't put it into the html report. We should look into how exactly it should be done.
