### ISSUE TITLE
Dependency resolution error

### ISSUE THREAD

**Issue by cjdxhjj** [gradle/gradle#30868]
## Current Behavior

My project uses jdk 21, and config with toolchain 21, but gradle always download jdk 8 and apply to project

![image](https://github.com/user-attachments/assets/bebeed22-b1c1-4e33-ae91-03c75effc9c2)

## Expected Behavior

use jdk 21

## Self-contained Reproducer Project

none

## Gradle version

8.10.2

**Comment by cjdxhjj** [comment]
Execution failed for task ':ldapa:compileKotlin'.
> Could not resolve all files for configuration ':ldapa:compileClasspath'.
   > Could not resolve org.springframework:spring-jdbc:6.1.13.
     Required by:
         project :ldapa
      > Dependency resolution is looking for a library compatible with JVM runtime version 8, but 'org.springframework:spring-jdbc:6.1.13' is only compatible with JVM runtime version 17 or newer.
   > Could not resolve org.springframework:spring-context:6.1.13.
     Required by:
         project :ldapa
      > Dependency resolution is looking for a library compatible with JVM runtime version 8, but 'org.springframework:spring-context:6.1.13' is only compatible with JVM runtime version 17 or newer.
   > Could not resolve org.springframework:spring-web:6.1.13.
     Required by:
         project :ldapa
      > Dependency resolution is looking for a library compatible with JVM runtime version 8, but 'org.springframework:spring-web:6.1.13' is only compatible with JVM runtime version 17 or newer.

* Try:
> Change the dependency on 'org.springframework:spring-jdbc:6.1.13' to an earlier version that supports JVM runtime version 8.
> Change the dependency on 'org.springframework:spring-context:6.1.13' to an earlier version that supports JVM runtime version 8.
> Change the dependency on 'org.springframework:spring-web:6.1.13' to an earlier version that supports JVM runtime version 8.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 325ms
1 actionable task: 1 executed

**Comment by cjdxhjj** [comment]
![image](https://github.com/user-attachments/assets/5239e527-b1c8-4709-8ee0-35b198ac29b5)

**Comment by cjdxhjj** [comment]
![image](https://github.com/user-attachments/assets/6e271713-1b34-4e9b-b825-552f87a2e321)

**Comment by cjdxhjj** [comment]
![image](https://github.com/user-attachments/assets/fbd7564a-d452-41d6-a292-6e5e1aa103cb)

**Comment by cjdxhjj** [comment]
when i sync or run the build command, gradle download jdk 8 and change the project language level to 8

**Comment by IgorOffline** [comment]
Hi, can you please create a self-contained reproducer project that demonstrates this issue?

**Comment by cjdxhjj** [comment]
when i create the example project, i found my sub project rewrite the jvm toolchaine to 8, when i change it to 21, it works.

**Comment by cjdxhjj** [comment]
when i create the example project, i found my sub project rewrite the jvm toolchaine to 8, when i change it to 21, it works.
