### ISSUE TITLE
Unable to access Plugin types in Kotlin script files included using apply(from = ...)

### ISSUE THREAD

**Issue by patrick-dedication** [gradle/gradle#30878]
### Expected Behavior

The migration documentation or Kotlin DSL Primer to contain a section on known limitations or workarounds when applying kotlin scripts.

### Context

I can't find out how to migrate our included groovy scripts to kotlin.
I made a repo with a minimal example, when I try to use publishing the script does no longer apply.
We also have a custom Plugin which adds a class as project extension so we can call a method on the class.
We want to convert it to a Kotlin Extension function rather than a project extension when the migration is complete, but need a way to migrate it.
Can we call the function without referencing the class type?

https://github.com/dedication-dev/gradle-apply-demo/blob/main/applied.gradle.kts

**Comment by abstratt** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Accessors are not available to included scripts applied with `apply` in Kotlin DSL. [Precompiled script plugins](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_precompiled.html) should work though. Also, please see [this comment](https://github.com/gradle/kotlin-dsl-samples/issues/1287#issuecomment-486182546).
