### ISSUE TITLE
Gradle can not resolve dependencies with multiple hypthons

### ISSUE THREAD

**Issue by taotao100** [gradle/gradle#30894]
### Current Behavior

a dependency like this could not de resolved:
implementation("io.github.digma-ai:digma-otel-agent-extension:0.8.1")

error messages in console, it ignores the prefix "digma-otel-" of the artifact :
Could not find io.github.digma-ai:extension-version:0.8.1.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/io/github/digma-ai/extension-version/0.8.1/extension-version-0.8.1.pom

### Expected Behavior

The artifact mentioned in maven central should be resolved by gradle.

### Self-contained Reproducer Project

implementation("io.github.digma-ai:digma-otel-agent-extension:0.8.1")

### Gradle version

8.10.2

**Comment by TheGoesen** [comment]
What gradle is trying to tell you is that digma-otel-agent-extension has a dependency on io.github.digma-ai:extension-version:0.8.1. However  io.github.digma-ai:extension-version:0.8.1 has not been uploaded to maven central. 
![Image](https://github.com/user-attachments/assets/589b900b-0be3-48aa-aaf9-ffa5d8ae0a06)
![Image](https://github.com/user-attachments/assets/ea0201a9-c6a3-49cf-a389-8fb4af8cac4e)

You may try to exclude said artifact or ask the developers at digma whats up with that

**Comment by taotao100** [comment]
Thanks you for your analysis, I created a ticket in digma-ai https://github.com/digma-ai/digma/issues/241. I close this issue
