### ISSUE TITLE
It's running  normally  on idea , but    build  failed  on  command line  

### ISSUE THREAD

**Issue by Super1Windcloud** [gradle/gradle#30890]
### Current Behavior

#  when I  run  "  gradle run  "  on command lint  ,  here is  result   
![image](https://github.com/user-attachments/assets/fee4107d-f23c-42c9-965b-28f457d5aadc)
![image](https://github.com/user-attachments/assets/eeccf3e9-5d92-41c6-85cb-4178d080006c)

![image](https://github.com/user-attachments/assets/6eb23e7d-cdba-4aff-ac70-3000f9bcb0a7)

### Expected Behavior

![image](https://github.com/user-attachments/assets/6e928eb7-bb3b-457c-a2c8-b78180db0a15)

### Self-contained Reproducer Project

It  is a  simple demo   

![image](https://github.com/user-attachments/assets/c5970c6a-845a-4e01-971d-0482f30f77a9)

### Gradle version

gradle  8.10.2 

### Your Environment (optional)

win11,    jDK20

**Comment by abstratt** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Comment by Super1Windcloud** [comment]
I  already solve , kotlin  need  add  Kt extension, because it's   top-level class
