### ISSUE TITLE
Scala Zinc Incremental compiler regression as of version 1.10.1

### ISSUE THREAD

**Issue by tnielens** [gradle/gradle#30898]
### Current Behavior

Test case `IncrementalScalaCompileIntegrationTest."recompiles Scala when Java changes"` passes.
If I upgrade the `DEFAULT_ZINC_VERSION` to `1.10.1+` in the gradle sources, the test case fails.

### Expected Behavior

The zinc upgrade shouldn't cause a test case failure.

### Context (optional)

I'm trying to upgrade the default version of zinc to benefit from a bug fix. The bug affects gradle multi project builds and causes over-compilation. See https://github.com/gradle/gradle/pull/30892 and https://github.com/sbt/zinc/pull/1382.

It's difficult to say if the test case failure is due to misuse of zinc by the gradle scala plugin which was uncovered by changes in zinc, or if this is a regression in zinc. I had a look at the gradle scala plugin but couldn't figure that out.

### Self-contained Reproducer Project

Set `DEFAULT_ZINC_VERSION` to `1.10.1`.

### Gradle version

17c9cfaa6ce

**Comment by ov7a** [comment]
I suspect this might be a subtle bug in zinc since I don't see anything suspicious or breaking change in 1.10.1. I'll investigate this.

**Comment by ov7a** [comment]
I filed an issue for zinc
* https://github.com/sbt/zinc/issues/1493

While it's not the root cause of this issue, I want to discover the implicit inputs to zinc before continuing.
