### ISSUE TITLE
init.d whoups again

### ISSUE THREAD

**Issue by TheGoesen** [gradle/gradle#30904]
### Issue type

Wrong or misleading information

### Problem description

# Resuructing #30610 
I didnt notice at first, but it seems to me there was an upsi in the documentation.
Point 2 was changed, but shouldn't be:
`Put a file called yourfilename.init.gradle(.kts) in the $[GRADLE_USER_HOME](https://docs.gradle.org/8.11-milestone-1/userguide/directory_layout.html#dir:gradle_user_home)/ directory.
`
in this case its really just init.gradle.kts

### Page with the problem

https://docs.gradle.org/8.11-milestone-1/userguide/init_scripts.html#sec:using_an_init_script

**Comment by abstratt** [comment]
Thanks, we will look into this.

**Comment by lkasso** [comment]
Closed with https://github.com/gradle/gradle/pull/30906
