### ISSUE TITLE
gradle failed with error Script 'node_modules\react-native\react.gradle' line: 366 Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

### ISSUE THREAD

**Issue by sumeetagarwal** [gradle/gradle#30929]
React native android app building bundle on appcenter with gradle failed with below error
Tried to upgrade gradle version but no help.

Android react native build with gradle failed with error Script 'node_modules\react-native\react.gradle' line: 366
Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

Gradle build failed with
Script 'node_modules\react-native\react.gradle' line: 366
Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

Build should run with app bundle

Gradle build scan link - https://gradle.com/s/b5gpbr4utg626

build.gradle file config

buildscript {
    ext {
        buildToolsVersion = '34.0.0'
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 34
        androidXCore = "1.0.2"
        kotlin_version = "1.8.10"
    }
    repositories {
        google()        
        mavenCentral()
        //mavenCentral{
          //  content {
            //    excludeGroup("com.facebook.react")
            //}
        //}
    }
    dependencies {
        classpath('com.android.tools.build:gradle:7.3.0')
        classpath("com.google.gms:google-services:4.4.0")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
        //implementation("org.jetbrains.kotlin.js:org.jetbrains.kotlin.js.gradle.plugin:$kotlin_version")
        //implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://dl.bintray.com/microsoftazuremobile/SDK' }
    }
}

gradle-wrapper.properties

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

settings.gradle
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.
