### ISSUE TITLE
develocity-gradle-plugin and common-custom-user-data-gradle-plugin missing licensing information

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#30938]
### Current Behavior

develocity-gradle-plugin and common-custom-user-data-gradle-plugin missing licensing information.

None of the following files has licensing information:
- https://plugins.gradle.org/m2/com/gradle/develocity-gradle-plugin/3.18/develocity-gradle-plugin-3.18.pom
- https://plugins.gradle.org/m2/com/gradle/develocity-gradle-plugin/3.18/develocity-gradle-plugin-3.18.module
- https://plugins.gradle.org/m2/com/gradle/common-custom-user-data-gradle-plugin/2.0.2/common-custom-user-data-gradle-plugin-2.0.2.pom
- https://plugins.gradle.org/m2/com/gradle/common-custom-user-data-gradle-plugin/2.0.2/common-custom-user-data-gradle-plugin-2.0.2.module

### Expected Behavior

pom files for both of these plugins ship something like

```
  <licenses>
    <license>
      <name>The Apache License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
```

like every other project.

### Context (optional)

Our project added a license checker and these two dependencies are failing as they have no license specified

### Self-contained Reproducer Project

N/A, see links above

### Gradle version

n/a

**Comment by abstratt** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by welandaz** [comment]
Hi @liutikas !
The information has been added, it will be out together with the new versions of the plugins.

Feel free to check [this PR](https://github.com/gradle/common-custom-user-data-gradle-plugin/pull/346) for `common-custom-user-data-gradle-plugin`, similar change was done for `develocity-gradle-plugin`.
