### ISSUE TITLE
Minor Things Resolving capability conflicts

### ISSUE THREAD

**Issue by TheGoesen** [gradle/gradle#30941]
### Issue type

Wrong or misleading information

### Problem description

...`withCapability("com.example.logging")` should be  ...`withCapability("com.example:logging") `
Would also suggest to change `all` to `configureEach`

### Page with the problem

https://docs.gradle.org/current/userguide/dependency_constraints_conflicts.html#resolving_capability_conflicts

**Comment by TheGoesen** [comment]
Pull Request
#30942

**Comment by abstratt** [comment]
Thanks for your contribution.
