### ISSUE TITLE
Incremental native build rebuilding all files after any failure with clang

### ISSUE THREAD

**Issue by darintay** [gradle/gradle#3094]
### Expected Behavior
Making changes to a single .cpp file should cause recompilation of only that single .o file, even after a compilation error and using clang.

### Current Behavior
When using clang as the compiler, if any file fails to compile, gradle will recompile all .o files next build

This only occurs with clang because, unlike gcc, clang will delete the output .o file if compilation fails.

Deleting the .o file causes gradle to consider all input files out-of-date and rebuild everything.
` Output property 'objectFileDirectory' file /home/dtay/src/sample-cpp/build/objs/main/mainCpp/d5jai1rac7tsmfw12u604esuq/file2.o has been removed.
All input files are considered out-of-date for incremental task ':compileMainExecutableMainCpp'.
`

### Context
This is causing gradle to unnecessarily rebuild far more of the project than necessary, and it occurs frequently during development.  It largely breaks the incremental build mechanism if you are using clang instead of gcc.

### Steps to Reproduce (for bugs)

See attached archive, which builds a simple 2-file cpp executable via clang using gradle.

[sample-cpp.tar.gz](https://github.com/gradle/gradle/files/1361036/sample-cpp.tar.gz)

Step 1: Build it (./gradlew assemble)
Step 2: Add a compilation error to one of the .cpp files
Step 3: Rebuild, which should fail due to your new error (use --info and note that it only attempts to rebuild the modified file, as expected)
Step 4: Fix your compilation error
Step 5: Rebuild again (use --info; note that both of the .cpp files are rebuilt, even though one was never touched)

You can also repeat the whole thing with gcc instead of clang to see that it does not exhibit this issue because it does not delete the output .o file on compilation failure.

### Your Environment

 * Build scan URL:

**Comment by lacasseio** [comment]
Thank you for reporting this issue. All Gradle native related development has a [new home](https://github.com/gradle/gradle-native) where this issue has been moved. We encourage you to follow that repository to stay informed about Gradle native development.
