### ISSUE TITLE
@OutputFile/@OutputDirectory don't work correctly when task doesn't write to output

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#3095]
Gradle version: 4.1

If in a build, a task does not write to the output file or output directory, subsequent incremental builds will break.

Steps to reproduce:
1. Use the build.gradle file as inlined below.
2. Run ./gradlew customTask --info -Pfile=none. Observe that the task runs and no file is output. This is expected.
3. Run ./gradlew customTask --info -Pfile=foo.txt. Observe that the task is UP-TO-DATE. This is not expected, as the file should have been written.

```
class CustomTask extends DefaultTask {             
	@OutputFile
	File outputFile	

	@TaskAction
	void doAction() {
		println "Task is running"
		if (outputFile.getPath().contains("foo")) {
			outputFile.write "Task is running"
		}
	}
}

task customTask(type: CustomTask) {
	outputFile = file(project.property('file'))
}
```

Adding `@Optional` to the property doesn't help. (And `@Optional` also has a bug as reported in https://github.com/gradle/gradle/issues/3073.)

This occurs for both `@OutputFile` and `@OutputDirectory`.

**Comment by lptr** [comment]
This works as designed. Your code makes a decision based on the location of the output, however Gradle does not consider the location of output roots to be part of the task's inputs. The current behavior is the correct one. If you want this task to do what you expect, you should make the name of the output file be an input of the task, like this:

```groovy
@Input getOutputName { outputFile.name }
```

Notice that in versions before 4.1 if you changed from `foo.txt` to `none`, you'd still be `UP-TO-DATE`. It was actually a bug in <4.1 that made the task out-of-date when `none` was changed to `foo.txt`.
