### ISSUE TITLE
HTML Problems Report feedback

### ISSUE THREAD

**Issue by Arthurm1** [gradle/gradle#30967]
### Expected Behavior

The new HTML problems report is great as it's often painful to scroll back through the terminal output to find various errors.  Here are some ways I think it could be improved...

1. It would be very handy if the stacktraces were included in the HTML regardless of whether the Gradle task was run with `--stacktrace`.  When projects have many errors/warnings, the terminal is virtually unreadable with stacktraces on, but with the HTML report they can be hidden until a specific error is drilled into.  Currently the HTML report doesn't seem to include the stacktrace even when `--stacktrace` is included.
2. Grouping seems to only be done on the first tree node.  Take the [Gradle Versions Plugin](https://github.com/ben-manes/gradle-versions-plugin) and run it on a project with many sub projects.  The same deprecation warning is shown repeatedly under the grouped section...![Image](https://github.com/user-attachments/assets/be49c7de-ea9b-4d86-aac1-d1f4c3799687)
It would be nice if these were all grouped into a single error with some count saying "x982" instead of the same warning repeated 982 times.  This may be happening here because there is no location data for these warnings.  The same thing is happening on the "Messages" page child nodes.
3. I'd like a "display as table" option with all the data in columns that are sortable (and ideally filterable by regex).  When upgrading versions (libraries, JDK, plugins, Gradle) you can often be hit with hundreds of deprecation warnings at once.  A table can make it easier to get a quick overview of which subprojects are affected and it helps make a judgement on how much work it will be to upgrade.
4. This is a bug I think: the same Java error is repeated 3 times without location. E.g.
```java
package foo;

public class Foo {
  int warning() {
    return unknownVar;  // << single error
  }
}
```
leads to 3 location errors whereas I think there should only be 1 with the exact row/column...
![Image](https://github.com/user-attachments/assets/e80e9ca1-97e9-4d15-9868-b33db5a4a68f)
Also - I find the location `5:12-10` strange to read.  I assume the `10` refers to the length but the use of the hyphen makes me think that `12-10` is a range from 12 to 10.  I think this should be changed to `5:12-22` but that's just my preference.

### Context

Trying to improve how useful the new HTML problems report is

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by reinsch82** [comment]
Thanks for the Feedback, Arthur.
I'll list our thoughts to your suggestions below.

1) stacktraces are costly performance wise, so adding it to every problem adds too much execution time to blindly add them everywhere. Specially considering that improving performance was recurringly a highly valued demand.  But we will gradually add them where we see value and can keep the performance degradation in check. see [here](https://github.com/gradle/gradle/issues/30561)
2) Deprecation is a bad example here, group tab view is a tree once the group has multiple levels e.g. java compilation
![Image](https://github.com/user-attachments/assets/b3f27f5a-978d-42fe-a374-32840bbfe71d)
We will also add summarization to avoid this massive duplication in the output.
There is currently a change in progress [here](https://github.com/gradle/gradle/pull/30841). A rudimentary specification that can be found [here](https://docs.google.com/document/d/1P8oHtfTEkRYojoCMTds5OFWj65kWRfI1qDjbsn8KBt4/edit?tab=t.0)
3) We have to look into that, it can be tricky to have a table and still be able to drill into all the details of the problem. So we need to come up with a UI solution that works reasonably well.
4) yes this is a bug an is addressed with [this PR](https://github.com/gradle/gradle/pull/30777), Gradle 8.11-rc-2 and above will not have the duplication.
