### ISSUE TITLE
Version selection is different from Maven and people's normal thinking.

### ISSUE THREAD

**Issue by huzhan0404** [gradle/gradle#30977]
### Expected Behavior

+--- org.elasticsearch.client:elasticsearch-rest-client:7.10.2 -> 7.10.2-htrunk28 

### Current Behavior (optional)

+--- org.elasticsearch.client:elasticsearch-rest-client:7.10.2-htrunk28 -> 7.10.2
A non-customized version is selected for the compiler.

### Context

I tried to correct this problem with excelude in the project, but it was identified as an active dependency.

**Comment by ljacomet** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

See [the documentation](https://docs.gradle.org/current/userguide/single_versions.html#version_ordering) and in particular:
* A version with an extra non-numeric part is considered lower than a version without: `1.1.a` < `1.1`
