### ISSUE TITLE
Potential Configuration Regression in 8.11

### ISSUE THREAD

**Issue by austinarbor** [gradle/gradle#30972]
### Current Behavior

In all versions of Gradle since version catalogs were added in 7.6, [this logic](https://github.com/austinarbor/version-catalog-generator/blob/main/plugin/src/main/kotlin/dev/aga/gradle/versioncatalogs/service/PublishedArtifactResolver.kt#L28-L63) has worked without a problem

Now, however, probably related to changes made for https://github.com/gradle/gradle/pull/30608 this logic fails with the error

```
Cannot create consumable configurations in detached resolvers
```

Based on my reading of https://github.com/gradle/gradle/issues/6881 , I'm wondering if the fix was incorrect?

My configuration:
1. Is not detached
2. Does not extend from another configuration
3. Is not consumable

The fix to get the plugin build working again on 8.11 is to actually start using a detached configuration https://github.com/austinarbor/version-catalog-generator/pull/156/files

### Expected Behavior

I see that in the ticket the goal was to fail fast instead of silently fail, but the changes introduced break a completely working build

### Self-contained Reproducer Project

1. Clone https://github.com/austinarbor/version-catalog-generator
2. `gradle wrapper --gradle-version=8.11-rc-1`
3. `./gradlew test --tests '*VersionCatalogGeneratorPluginTest' --info --stacktrace`

### Gradle version

8.11 RC1

### Gradle version that used to work

7.6 - 8.10

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by jvandort** [comment]
The change in behavior was introduced here:

https://github.com/gradle/gradle/commit/cab83c023a5c846751dd95d2529b2771d2f111ee

The change was intentional. 

Your code uses internal Gradle APIs. `DependencyResolutionServices` is an internal API and Gradle does not guarantee stable behavior with these APIs across minor versions.

**Comment by jvandort** [comment]
You are creating a configuration in a dependency resolution context known internally as a "detached resolver". 

This is an overload of the term detached. 
Detached in this context means its not attached to a project.

Users were not intended to see this failure, as it is only thrown when incorrectly using internal APIs. 

In your case, your configuration is _originally_ created as consumable. It is only later changed to `isCanBeConsumed = false`.

You would not see the error if you used the role-locked `resolvable(String)` configuration factory method, which creates the configuration in a non-consumable role upon creation.

**Comment by austinarbor** [comment]
Ah I see, thanks for the explanation
