### ISSUE TITLE
Worker based Java compile cannot deal with non serializable bootstrapClasspath

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#3098]
See: https://e.grdev.net/s/pxiecd4ksfrre/failure?openFailures=WzFd&openStackTraces=WzZd#top=0

Note that this is with a development 4.3 version. 

My guess is that `JavaCompile` needs to convert the `boostrapClasspath` to a serializable form before handing off to the worker.

**Comment by lptr** [comment]
We had the same issue with `CompileOptions`, too. I wonder how we don't have a test for this in BT. Let me look at this.

**Comment by lptr** [comment]
Okay, looks like the issue with `-bootclasspath` has already been fixed on `release`. However, `CompileOptions.sourcepath` had the same issue.

**Comment by lptr** [comment]
PR merged.
