### ISSUE TITLE
ExecOperations documented as inside internal package

### ISSUE THREAD

**Issue by adam-enko** [gradle/gradle#30982]
### Issue type

Wrong or misleading information

### Problem description

https://github.com/gradle/gradle/blob/3b75ad1567ff4f4557bb4343d346ffda7bcf4060/platforms/documentation/docs/src/docs/userguide/authoring-builds/gradle-properties/service_injection.adoc?plain=1#L229

> It is part of the `org.gradle.process.internal` package

ExecOperations is inside `org.gradle.process`, not `org.gradle.process.internal`.

The 'internal' package shouldn't be used outside of Gradle internals, and so it shouldn't be advertised.

### Page with the problem

https://github.com/gradle/gradle/blob/3b75ad1567ff4f4557bb4343d346ffda7bcf4060/platforms/documentation/docs/src/docs/userguide/authoring-builds/gradle-properties/service_injection.adoc?plain=1#L229

**Comment by adam-enko** [comment]
While I'm here, a tiny nitpick.

https://github.com/gradle/gradle/blob/3b75ad1567ff4f4557bb4343d346ffda7bcf4060/platforms/documentation/docs/src/docs/userguide/authoring-builds/gradle-properties/service_injection.adoc?plain=1#L249

The headers of the other sections are formatted as `$number.`, but 9 doesn't have a `.`.

![Image](https://github.com/user-attachments/assets/8595fcf1-4657-4bf6-bcaf-73a498424a1e)

**Comment by ov7a** [comment]
This is a valid documentation issue.

*** 

This should be fixed in 
* https://github.com/gradle/gradle/pull/30950

**Comment by mlopatkin** [comment]
Resolved in #31063
