### ISSUE TITLE
Adding additional  hint for #26672

### ISSUE THREAD

**Issue by TroutZhang** [gradle/gradle#30995]
### Issue type

Missing information

### Problem description

https://github.com/gradle/gradle/issues/26672 added some useful hints in general, but for Android Studio users, it may be easier to ask them to just upgrade the AGP, check my comments there https://github.com/gradle/gradle/issues/26672#issuecomment-2431441680

### Page with the problem

https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#changes_8.4

**Comment by abstratt** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

**Comment by Kishorecoder96** [comment]
can i contribute to this documentation ?

**Comment by TroutZhang** [comment]
Sorry for 3 weeks delay, just happened to get 1 hour wait time in Amsterdam airport.
