### ISSUE TITLE
Introduce ProjectDependency#getPath

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#30992]
https://github.com/gradle/gradle/pull/30447 deprecated `ProjectDependency#getDependencyProject`. There were a number of existing projects and plugins using this method. 

This method was used in a number of ways, including:
1. Detecting the identity of _declared_ dependencies, for reporting.
2. Introspecting the inputs of dependency resolution. This use case is better solved using `ResolutionResult`, as it accounts for dependency substitutions.
3. Performing IP unsafe operations.

With `getDependencyProject`, there is no solution for the first use case. For the same reason we expose `group`, `name`, and `version`, on a `ModuleDependency` we should expose the project's `path` on a `ProjectDependency`. This solves the first use case.

In general users should migrate away from use case 2 and 3. However, it is not the goal of the original deprecation prevent isolated-projects-unsafe code. It was intended as a refinement of the dependency resolution API surface. Dependency resolution is intended to expose _safe_ cross-project data sharing. Exposing the mutable state of target projects is does not belong on any dependency resolution API. 

However, to ease migration, the `getPath` method can be used along with the `Project#project(String)` to get access to the mutable state of other projects.

**Comment by ljacomet** [comment]
Resolved with:
* #30993
