### ISSUE TITLE
Build cache miss due to unstable sort order of the classpath property.

### ISSUE THREAD

**Issue by SheliakLyr** [gradle/gradle#31008]
### Current Behavior

I have 2 PCs that run the same build with build cache enabled. I see some unexpected differences in computed hashes for compile tasks.

I am using Scala, so the problems are visible in compileScala task. Using gradle build cache debugging I managed to track the issue to property 'classpath' from AbstractCompile (annotated with "@Classpath").

On one PC, the build outputs:
```
Appending input file fingerprints for 'classpath' to build cache key: 96d410733e26a9905b1a885b33b0a2cc - CLASSPATH{/// 89 jars }
```
On the other:
```
Appending input file fingerprints for 'classpath' to build cache key: 0ce3ff5b10f0076524d3330f5a908896 - CLASSPATH{/// 89 jars }
```

Obviously, I expect that the contents of the 'classpath' differ. However, all 89 hashes for the individual jars *are the same* between those two builds. There are only two differences:
1. Order of the "jars" is different.
2. On one PC, some jars are from .gradle cache. On the other, from .m2/repository. I have mavenLocal repository enabled.

For example:
PC1, this jar is the last on the list:
```
/home/user/.m2/repository/commons-codec/commons-codec/1.16.1/commons-codec-1.16.1.jar=IGNORED / 49a6b89d0f4398519d225ddaf43fb6a7
```
PC2, this jar is 4th from the end:
```
/home/user/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.16.1/47bd4d333fba53406f6c6c51884ddbca435c8862/commons-codec-1.16.1.jar=IGNORED / 49a6b89d0f4398519d225ddaf43fb6a7
```

After checking gradle source, I determined that order of the jars on classpath property is important (ClasspathFingerprintingStrategy.getHashingStrategy() returns KEEP_ORDER). The order should be imposed by the configuration resolver.

I suspect, that because jars are from different "sources" (.gradle cache vs local maven repository) the ordering of the jars from the resolved configuration in different between PCs.

### Expected Behavior

Task hashes are stable between machines, providing the individual jars on the classpath are the same.

### Self-contained Reproducer Project

I believe that the problem happens only when the following conditions are met:
1. Large number of jars on the classpath for compile task.
2. MavenLocal repository is used.

### Gradle version

Gradle 8.8

**Comment by SheliakLyr** [comment]
Workaround: it seems that order of the repositories matters for caching. After changing
```
mavenLocal()
maven { ... }
```
to
```
maven { ... }
mavenLocal()
```

classpath hashes are different (even though jar hashes are the same!) and seem to be stable between PCs.

**Comment by abstratt** [comment]
We would ideally need a reproducer. If that is not possible, could you please:
1. verify that the metadata files in `mavenLocal()` have the same dependency declaration order as `maven()`   
2. share the output `compileClasspath.files` from both machines
