### ISSUE TITLE
The "-b" option still makes settings.gradle to be used

### ISSUE THREAD

**Issue by acejazz** [gradle/gradle#3100]
### Expected Behavior
Based on the documentation:

> If you use -b option then settings.gradle file is not used.
(4.5. Selecting which build to execute)

Therefore if I use the `-b` option I don't want any code in the `settings.gradle` file to be executed.

### Current Behavior
Even with using the `-b` option, the code in `settings.gradle` is executed.

### Context
Going through the documentation and trying all the functionalities. (Actually not a real life application, but I want to get better with gradle and it's not possible to use it with projects I'm using at work)

#### Preconditions:
Create a project like:
```
.
├── anotherBuild.gradle
├── build.gradle
└── settings.gradle
```
With build.gradle containing:
```
task taskA{
    doLast{
        println "taskA from build.gradle"
    }
}
```
With anotherBuild.gradle containing:
```
task taskA{
    doLast{
        println "taskA from anotherBuild.gradle"
    }
}
```
and settings.gradle containing:
`println "From settings.gradle, executed during initialization phase"`

#### Steps
Run:
`gradle -q -b anotherBuild.gradle taskA`

#### Expected result
No "From settings.gradle, executed during initialization phase" must be printed.

#### Actual result
"From settings.gradle, executed during initialization phase" is printed.

### Your Environment
- Gradle 4.0
- javac 1.8.0_121
- MacOS 10.12.6

**Comment by bigdaz** [comment]
This is a documentation problem. There's no reason for `settings.gradle` to be ignored when a build file is specified. I'll remove that sentence.

**Comment by Vampire** [comment]
@bigdaz could you please add instead some text on actual expected behaviour, especially in a multi-project-build? Do you just specify the replacement for the root build script? Does this even work if the root build script is not `build.gradle`, but gets changed in `settings.gradle`? ...?
