### ISSUE TITLE
Update README for better readability

### ISSUE THREAD

**Issue by abhirajadhikary06** [gradle/gradle#31017]
**I want to update the README.md file for Gradle with some listed changes :**

- Add Gradle's participation in Hacktoberfest 2024 to Gradle's main repository.
- To add more structure for better readability
- Add relevant labels
- Update the logo of Gradle used in README as after checking the [Branding Guidelines](https://gradle.com/brand/) found that the logo used in dark mode is outdated.

**_Please assign this issue to me._**

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Our developer advocate and documentation persons should chime in on the proposed changes before this gets assigned to anyone.

**Comment by oleg-nenashev** [comment]
Hi @abhirajadhikary06 incremental contributions to improve any information in this repo are welcome

> Add Gradle's participation in Hacktoberfest 2024 to Gradle's main repository.

I am not sure it is beneficial for this landing, especially given that we do not promote this repository as good first contribution


> To add more structure for better readability

Sure, PRs are welcodme

> Add relevant labels

What do you mean?

> Update the logo of Gradle used in README as after checking the [Branding Guidelines](https://gradle.com/brand/) found that the logo used in dark mode is outdated.

Yes, a patch is welcome

**Comment by abhirajadhikary06** [comment]
> Hi [@abhirajadhikary06](https://github.com/abhirajadhikary06) incremental contributions to improve any information in this repo are welcome
> 
> > Add Gradle's participation in Hacktoberfest 2024 to Gradle's main repository.
> 
> I am not sure it is beneficial for this landing, especially given that we do not promote this repository as good first contribution
> 
> > To add more structure for better readability
> 
> Sure, PRs are welcodme
> 
> > Add relevant labels
> 
> What do you mean?
> 
> > Update the logo of Gradle used in README as after checking the [Branding Guidelines](https://gradle.com/brand/) found that the logo used in dark mode is outdated.
> 
> Yes, a patch is welcome

By labels i mean updating these ![Image](https://github.com/user-attachments/assets/a65e09d0-5c7f-4f74-b4cb-071ce021237c)
