### ISSUE TITLE
The @RELEASE_NAME@ placeholder in the verification-keyring.keys file is not substituted with the correct BCPG version anymore

### ISSUE THREAD

**Issue by maximmig** [gradle/gradle#31035]
### Current Behavior

Since Gradle 8.9 when I run the script to update dependencies `./gradlew --write-verification-metadata sha256,pgp --write-locks --export-keys` the blocks 
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v1.77.00
```
in the `verification-keyring.keys` file are replaced by 
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG v@RELEASE_NAME@
```

### Expected Behavior

The `verification-keyring.keys` file should contain the correct version of BCPG

### Self-contained Reproducer Project

The reproducer is here: https://github.com/maximmig/gradle-issue-reproducer

I run `./gradlew wrapper --gradle-version 8.9 --distribution-type bin` to update gradle to 8.9 and then run `./gradlew --write-verification-metadata sha256,pgp --write-locks --export-keys` to write the verification metadata and and export the keys.

### Gradle version

8.9

### Gradle version that used to work

8.8

### Your Environment (optional)

IntelliJ IDEA on macOS arm64

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

Reproduced on Gradle's own build. Something probably changed in bouncycastle and broke the armored key export format.

Probably introduced when we update Bouncycastle here:
* #29593

**Comment by ljacomet** [comment]
The fix was to remove that header following changes in Bouncycastle. It is not needed.
