### ISSUE TITLE
REGRESSION: `ValueSource` instances are no longer shared across projects in 8.11-rc-1

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#31039]
With the segregation of project state introduced by parallel CC storage, `ValueSource` instances are no longer shared across projects. This might lead to performance issues and, in edge cases, to correctness problems. For example:
* a Settings plugin creates a `ValueSource` then uses a `allprojects` block to share it among tasks from all projects;
* the `ValueSource` executes some external process that can yield different values when executed more than once;
* With 8.10, the `ValueSource` would be loaded and execute only once for all projects, thus sharing a single cached value;
* With 8.11-rc-1, the `ValueSource` would be loaded and executed once per project, thus potentially yielding different values to different tasks;

**Comment by ljacomet** [comment]
Resolved with:
* #31048
