### ISSUE TITLE
`ArchiveOperations` documentation is incorrect

### ISSUE THREAD

**Issue by dexman545** [gradle/gradle#31059]
### Issue type

Wrong or misleading information

### Problem description

In the [service documentation](https://docs.gradle.org/current/userguide/service_injection.html#archiveoperations), it states that `ArchvieOperations` is used for "creating archives, such as ZIP and TAR files;" however, it only contains methods for reading archives.

I believe the package is also wrong.

### Context (optional)

I was looking for a way to create zips from within a task.

### Page with the problem

https://docs.gradle.org/current/userguide/service_injection.html#archiveoperations

**Comment by ov7a** [comment]
This is a valid documentation issue.
