### ISSUE TITLE
Configuration cache is not invalidated when creating a buildSrc directory

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#31097]
### Current Behavior

When creating a buildSrc directory with contents in a project that didn't have one, yet, the next build might be a configuration cache hit.

### Expected Behavior

Creating a buildSrc directory should invalidate the configuration cache entry.

### Self-contained Reproducer Project

Start with the unmodified issue-reproducer

1. run `./gradlew help --configuration-cache` causing a configuration cache store
2. add `buildSrc/src/main/groovy/MyClass.groovy` with contents `class MyClass {}`
3. run `./gradlew help --configuration-cache` - a configuration cache hit.

### Gradle version

8.12 nightly, see the build scan

### Build scan URL (optional)

https://ge.gradle.org/s/sxc7wtf7dlpvy/performance/configuration

### Your Environment (optional)

See https://ge.gradle.org/s/sxc7wtf7dlpvy/performance/configuration

**Comment by ljacomet** [comment]
Given this happens on the main branch, adding to the future 8.12 RC1 to make sure this gets fixed.

@gradle/bt-configuration Could you check this does not happen in 8.11?

**Comment by mlopatkin** [comment]
> Could you check this does not happen in 8.11?

This never worked properly.
