### ISSUE TITLE
Download dependencies to a specific folder

### ISSUE THREAD

**Issue by hanct** [gradle/gradle#3109]
Hi,

We are trying to download dependencies for my project, but we prefer to download to specific subfolder of our project folder, rather than the machine's .gradle folder.  Internet suggest writing a simple task to do the copying from the .gradle folder to any folder we desired. 

We are wondering: Does the latest version of the gradle (v4.X.X) able to do this, with simple configuration, rather than having to write a task for such simple action?

**Comment by bigdaz** [comment]
I think you're referring to where the Gradle cache is located, which is where Gradle will download and cache files. This will always be located in the Gradle user home directory, which is configurable via the `--gradle-user-home` command line option.
