### ISSUE TITLE
Task eclipseClasspath: Add dependencies > api libraries to Eclipse project exported libraries

### ISSUE THREAD

**Issue by haba713** [gradle/gradle#3110]
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
> Dependencies appearing in the api configurations will be transitively exposed to consumers
> of the library, and as such will appear on the compile classpath of consumers.

Gradle task `eclipseClasspath` should add the `dependencies > api` libraries with their dependents to Eclipse project exported libraries.

### Expected Behavior
The file `.classpath` should have this kind of lines for `dependencies > api` libraries and their dependents.
```xml
<classpathentry exported="true" kind="lib" path="[homedir]/.gradle/caches/..." />
```

### Current Behavior
No `dependencies > api` libraries are added to Eclipse project exported libraries.

### Context
If you have Gradle Java library project A in Eclipse with dependent libraries and want to use it in different Eclipse project B,  you must take care of adding project A dependencies manually to Eclipse project B.

### Steps to Reproduce (for bugs)
1. Create a new Gradle project.
2. Add `apply plugin: 'eclipse'` to `build.gradle`.
3. Add `api 'net.sourceforge.nekohtml:nekohtml:1.9.22'` to dependencies.
4. Run `./gradlew eclipse`
5. Import project to Eclilpse.
6. See Project > Properties > Java Build Path > Order and Export.
7. The libraries `nekohtml`, `xercesImpl` and `xml-apis` should be selected but they aren't.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/jgkx37wafcino

**Comment by oehme** [comment]
This is working as expected. 

Eclipse reexports are brittle, downstream projects can't opt out of them, e.g. to use a different version. Instead each Gradle project defines its own classpath fully. This ensures that resolution rules etc. are taken into account. 

If project B is part of a different Gradle build, have a look at composite builds to work on A and B together. 

If B is not a Gradle project, and you are okay with the downsides of reexports, you can adjust the eclipse model of A with `eclipse.classpath.whenMerged {}`.
