### ISSUE TITLE
allow Provider::orElse to take a `Callable`

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31104]
### Expected Behavior

this seems silly
```
someProperty.orElse(() -> providerFactory.getProvider(() -> ...) )...
```

instead allow, which just makes the other provider under the hood.

```
someProvider.orElse(() -> ...)
```

### Context

I just want to write less and sometimes more functional code. The reality in my use case even having a fully fledge provider seems silly (but maybe isn't). I just want it to orElse call that function at the end.

**Comment by ljacomet** [comment]
This issue will be closed as a duplicate of

* #29358

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.
