### ISSUE TITLE
make provider.MissingValueException part of the published api

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31110]
### Expected Behavior

Make `org.gradle.api.internal.provider.MissingValueException` part of the published API. 

### Context

in order to test a `ValueSource` correctly I might also need to know when it's returning `null`

```java
  @Test
  void obtainWithHeadBranchSetNoRemotes() {
    var hbvsp = project
      .getProviders()
      .of(HeadBranchValueSource.class, c -> {
        c.getParameters().getHeadBranch().set("other");
        c.getParameters().getProjectDir().set(project.getProjectDir());
      });

    assertThatExceptionOfType(MissingValueException.class).isThrownBy(() -> hbvsp.get());
  }
```

current version 8.10.2

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

@gradle/bt-configuration What should be the flow on the user side? Do we expect users to catch those exceptions or not?

**Comment by mlopatkin** [comment]
We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

This issue will be closed after 7 days unless you provide more information.

***

The proposed use case seem to be served by `Provider.isPresent` or `.getOrNull`, and the exception type is already specified as `IllegalStateException`. Maybe there is another use case where a more precise type is required?

**Comment by xenoterracide** [comment]
My doing, wanting this might have been due to one of the many other things that has surprised me that doesn't work. I'm not certain what the state of my code was when I created this that I thought this was a good idea. 

I *might* have been trying to inject another value source and expecting it to throw this as I didn't set the state. If I return `null` in the `ValueSource` and I want that value returned and cached from a `ValueSource` or if a `Property` is set to `null`. I guess `Provider` is just a lazier `Optional` (dear java, why isn't `Optional` lazier like `Stream`, also why couldn't it have been my 3 states).

I'm not certain I've ever really agreed with `Optional` throwing an error on `get()`. it's generally a good practice to catch the most specific exception possible if you need to.

Btw, did anyone realize the name `Provider` conflicts with a class in "javax.inject".

I'm closing since I don't recall, unfortunately. It might also have been my brain "oh this throws... let's catch it in our test".

**Comment by mlopatkin** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

So far I don't see a compelling use case to catch the exception coming from an unset provider specifically. Just like with arrays or `Optional`, the consumer is expected to check for the presence of the value before obtaining it, or use fallback-taking variants, like `getOrElse`.
