### ISSUE TITLE
[ QUESTION ] Gradle reloading failed multiple times with all of tricks I know

### ISSUE THREAD

**Issue by Xelbayria** [gradle/gradle#31130]
### Current Behavior

I keep getting the error: `The process cannot access the file because it is being used by another process` and there are only one process that is accessing the file (it's Java 21). There are no other application that are preventing the file from being accessed. 

The IDE is Intellij IDEA community edition, latest version to date. 

I've tried all of the trick I know to get it finish with the gradle reloading. I keep running into the error with random file. 

<details><summary>Additional Info</summary>

I've tried: 
- invalidate & Restart the file (IDEA's feature)
- `gradle --refresh-dependencies`
	- via IDEA's gradle
	- via powershell
- deleted the cache folder via `~/.gradle/cache/...` 
- deleted the .gradle folder in the project `~/.gradle/...` 
- tried `reload all Gradle Project` via IDEA's gradle

</details> 

this is quite frustrating because i've been trying to get `gradle reload` to be finished all day without succession. I've run out of ideas and am helpless. My computer is 13 years old

---

**OTHERS**
I apologize for creating the issue that is not really a bug. More of need help with dealing with the issue I'm helpless with. 

FYI, I do not want to sign up for 2 different website: stackoverflow or slack just to get help. you could create a server on discord for anyone who need help with gradle. It's just a suggestion. 

### Expected Behavior

I expected that I do not have to run into the error. Not even once. 

### Self-contained Reproducer Project

[WoodGood](https://github.com/MehVahdJukaar/WoodGood). The library & dependencies are over 50 of libraries in the project and it's for Minecraft 1.21.1 with Neoforge & Fabric. 

I sometimes have run into the error in 1.18.2 to 1.20.1 but i used some tricks to finish the `gradle reloading` without any problem. BUT 1.21, as you can see the issue above. 

if You want to do some testing to check how gradle behave with the build.gradle via the link. You could just simply let gradle do its job by importing the dependencies. I'm sure you won't have any problem on your computer. It should be just "me" where it's just a problem on my side.

### Gradle version

8.10.2

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***
You can use process explorer or similar software to find the process using the file.

Another thing that could work is to restart your machine.
