### ISSUE TITLE
build service documentation/pattern encourages finalizer security vulnerability add lazy initialization and static factories

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31146]
### Expected Behavior

https://docs.gradle.org/current/userguide/build_services.html The example shows starting the web service and accessing properties in the constructor. Both of which could throw exceptions.

To mitigate this I suggest that gradle should add support for some form of `@PostConstruct` to initialize `BuildService`. I would also suggest changing this documentation to not include a vulnerability. I'm currently using my services to implement the `Supplier` interface, of course if there's no value you need... that'd just be invoking a `void start` or soemthing.

It might also be good to provide a way to annotate a static factory as a constructor instead.

this is the attack I'm referring to https://self-learning-java-tutorial.blogspot.com/2020/03/finalizer-attack-in-java.html

p.s. I have no reason to believe/know if gradle itself is vulnerable in any way. I perceive this to be a problem with construction for my objects.

### Context

There isn't a great way to initialize build service objects in a way that their constructors won't throw exceptions, and using a lazy call in the consumer to do the work feels like it's against gradle's intent.

**Comment by reinsch82** [comment]
We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

This issue will be closed after 7 days unless you provide more information.

***

Gradle is a runtime and has a programming model. We understand you have other habits from other runtimes.
Yet we don't see how this is an effective problem.
Please share a more complete example of a problem that can not be expressed with a current gradle version.

**Comment by xenoterracide** [comment]
> Gradle is a runtime 

The JVM is a runtime and gradle is subject to any security issues it has unintentionally allowed, even ones it has deprecated and may be removing.

> Please share a more complete example of a problem that can not be expressed with a current gradle version.

I think you didn't mean *not*?

I am relying on you to read provided links to understand the nature of this attack and how it works. Smarter people than me have explained this attack vector in great detail.

I want at minimum *Documentation* that doesn't suggest writing code vulnerable to a finalizer attack. Unless since as you say gradle is its own runtime you plan on providing a version of gradle that only runs on a jvm that doesn't execute finalizers which AFAIK still doesn't exist (this deprecation was completed, but AFAIK it hasn't been removed) https://openjdk.org/jeps/421

Do I need to provide an example of crafting some malicious code that has gotten into a jar that's not signed and not validated that can execute and grab credentials? This is a plugin API so all we'd need is one plugin to add a malicious jar. Honestly, I'd bet if someone was using the vulnerable version of log4j I might be able to craft this out of that. The only real protection is that it's probably not super easy to get a vulnerable class into someones environment... except gradle supports those init scripts that execute without approval, so they exist and you might not know it. So the only real thing you need to do is slip one of those into place, and it can execute a finalizer, of course at that point you can probably do any naughty things you want even with finalizers disabled.

your example is starting a web server

```java
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.services.BuildService;
import org.gradle.api.services.BuildServiceParameters;

import java.net.URI;
import java.net.URISyntaxException;

public abstract class WebServer implements BuildService<WebServer.Params>, AutoCloseable {

    // Some parameters for the web server
    interface Params extends BuildServiceParameters {
        Property<Integer> getPort();

        DirectoryProperty getResources();
    }

    private final URI uri;

    public WebServer() throws URISyntaxException {
        // Use the parameters
        int port = getParameters().getPort().get();
        uri = new URI(String.format("https://localhost:%d/", port));

        // Start the server ...

        System.out.println(String.format("Server is running at %s", uri));
    }

    // A public method for tasks to use
    public URI getUri() {
        return uri;
    }

    @Override
    public void close() {
        // Stop the server ...
    }
}
```

this code is vulnerable to a finalizer attack simply because these lines throw an exception in the constructor, to the point you've had to put the exception on the constructor.

```java
        int port = getParameters().getPort().get();
        uri = new URI(String.format("https://localhost:%d/", port));
```

I think that the only way to do this securely right now is to not to call the web server in the constructor. SO what I do is this

```java
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.services.BuildService;
import org.gradle.api.services.BuildServiceParameters;

import java.net.URI;
import java.net.URISyntaxException;

public abstract class WebServer implements BuildService<WebServer.Params>, AutoCloseable {

    // Some parameters for the web server
    interface Params extends BuildServiceParameters {
        Property<Integer> getPort();

        DirectoryProperty getResources();
    }

    // A public method for tasks to use
    public URI getUri() {
       // Use the parameters
        int port = getParameters().getPort().get();
        try {
           var uri = new URI(String.format("https://localhost:%d/", port));

           // Start the server ... needs a nullable variable to track the server state

           System.out.println(String.format("Server is running at %s", uri));
           return uri;
        }
        catch ( URISyntaxException e ) {
           throw new RuntimeException( e );
        }
    }

    @Override
    public void close() {
        // Stop the server ...
    }
}
```

doing it like this avoids any chance of a finalizer attack when someone calls `getUri`. I don't believe that gradle intends for the server to be started this late in the build. In order to avoid the vulnerability you'd need to either allow a static factory so that the exceptions are done in the static factory constructor.


```java
    @Inject
    @Creator // or whatever, name shamelessly derived from Jackson
    public static WebServer start( Params params) throws URISyntaxException {
       // Use the parameters
       int port = params.getPort().get();
       var uri = new URI(String.format("https://localhost:%d/", port));

       // Start the server ...

       System.out.println(String.format("Server is running at %s", uri));
       return uri;
    }
```

or you could provide this

```java
    @PostConstruct
    public setup() throws URISyntaxException {
        // Use the parameters
        int port = getParameters().getPort().get();
        uri = new URI(String.format("https://localhost:%d/", port));

        // Start the server ...

        System.out.println(String.format("Server is running at %s", uri));
    }
```
which would be called lazily sometime after the build service had `new` called in a way that didn't throw exceptions.

Obviously you can't prevent, or ask people to change their code from throwing exceptions in the constructor. You can however stop suggesting it, and provide alternatives if my suspicion on expecting a web server to be started before the `uri` is requested. Without some method to do so though, that's the only secure way to do it.

is this clearer?

**Comment by ljacomet** [comment]
A few points to clarify:

* Gradle is responsible for instantiating services and makes sure this happens when the service is first needed. It has no opinion on when the service state is created (constructor, or lazily on demand). So feel free to do it lazily in your plugins.
* In either case, throwing an exception will fail the build
* Regarding the security aspect: as you stated, by running plugin code, there are [risks](https://blog.gradle.org/project-integrity). This is why we said Gradle is a runtime.
* That finalizer attack blog post is not very relevant in our opinion. Other Java features can be used to abuse code: reflection, serialization. The finalizer trick is no different.


So regarding the 3 points at the end:
1. We do not think complicating the example would provide value. Initialization in constructor is something that makes sense for an instance that will be lifecycled by Gradle.
2. Motivating those features as a protection against the finalizer attack would not be a good enough reason to update Gradle's programming model. Gradle will run user code - in plugins and in tests. The security considerations are quite different from the closed environment of an application
3. Void by the above two points.
