### ISSUE TITLE
New newline in unixStartScript.txt breaks existing functionality

### ISSUE THREAD

**Issue by martinda** [gradle/gradle#31152]
### Current Behavior

The [platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt](https://github.com/gradle/gradle/commit/021931895700b326803fa93d1b35615d82f6b0a1#diff-6de71ffa3194baebf530a113d1c2181d6552731ebcc4ce52d796a8ba14800b81) file introduces a new `\n` character in commit 021931895700b326803fa93d1b35615d82f6b0a1

The result is that since Gradle 8.9, we're seeing the line being split in the start script:
```bash
APP_HOME=$( cd -P "${APP_HOME:-./}.." > /dev/null && printf '%s
' "$PWD" ) || exit
```

Now it would not be so bad, but we're actually using `APP_HOME` as a key to insert some custom code to setup the `JAVA_HOME`, so our startup scripts are truly standalone applications. However, because of the newly introduced `\n`, it breaks:
```bash
APP_HOME=$( cd -P "${APP_HOME:-./}.." > /dev/null && printf '%s
# We inject JAVA_HOME on the line after APP_HOME
JAVA_HOME=/path/to/java
' "$PWD" ) || exit
```

### Expected Behavior

We were not expecting the newline to be introduced, the behavior of Gradle 8.8 was good. The code then was:

```bash
APP_HOME=\$( cd "\${APP_HOME:-./}${appHomeRelativePath}" > /dev/null && pwd -P ) || exit
# We inject JAVA_HOME on the line after APP_HOME
JAVA_HOME=/path/to/java
```

### Context (optional)

It broke all our startup scripts since Gradle 8.9.

### Self-contained Reproducer Project

The intent was to change from `cd` to `cd -P`, but adding the `\n` was not necessary. Perhaps it should have been escaped with `\\n`?

### Gradle version

8.9

### Gradle version that used to work

8.8

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

While we understand this is not an ideal situation, note that we do not consider the content of those generated scripts to be part of an API that would follow [the feature lifecycle](https://docs.gradle.org/current/userguide/feature_lifecycle.html#sec:states).

We will fix this instance as it definitely looks like a mistake and not a wanted change.
