### ISSUE TITLE
Broken link in samples page note

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#31258]
On samples pages, [like this one](https://docs.gradle.org/current/samples/sample_sharing_convention_plugins_with_build_logic.html), the link in the note at the top of the page is broken.

The link currently points to: 
https://docs.gradle.org/current/samples/gradle_ides.html#gradle_ides

It should point to:
https://docs.gradle.org/current/userguide/gradle_ides.html#gradle_ides

**Comment by oleg-nenashev** [comment]
We discussed it on the community Slack. To confirm, it is a valid issue
