### ISSUE TITLE
Powershell build output is not user friendly (garbage)

### ISSUE THREAD

**Issue by lukef** [gradle/gradle#3128]
### Using
Windows 10
Powershell
Gradle 4.2

### Issue

While trying to build the `JetBrains/kotlin-native` repository using Powershell the gradle build process produces unreadable output like the example below:

```
1m 35s]?[m?[38D?[1B?[1m> :backend.native:genLlvmInteropStubs?[m?[37D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 66% EXECUTING [1m 35s]
?[m?[38D?[1B?[1m> :backend.native:genLlvmInteropStubs?[m?[37D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 66% EXECUTING [1m 35s]?[m?[38
D?[1B?[1m> :backend.native:genLlvmInteropStubs?[m?[37D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 66% EXECUTING [1m 35s]?[m?[38D?[1B?[
1m> :backend.native:genLlvmInteropStubs?[m?[37D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 35s]?[m?[38D?[1B?[1m> :ba
ckend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 35s]?[m?[38D?[1B?[1m>
:backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 35s]?[m?[38D?[1B?[1
m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 35s]?[m?[38D?[1B
?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 35s]?[m?[38D?
[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 36s]?[m?[3
8D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 36s]?[m
?[38D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 36s]
?[m?[38D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1m 3
6s]?[m?[38D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING [1
m 36s]?[m?[38D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUTING
 [1m 36s]?[m?[38D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXECUT
ING [1m 36s]?[m?[38D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67% EXE
CUTING [1m 36s]?[m?[38D?[1B?[1m> :backend.native:compileLlvmInteropStubsKotlin?[m?[47D?[4B?[5A?[1m<?[0;32;1m========?[0;39;1m-----> 67%
```

I'm positive its because powershell doesn't understand all the formatting codes, CRLF, etc that's being passed in for formatting the output.

**Comment by blindpirate** [comment]
I would say it's not garbage, it's [ANSI control sequence](https://en.wikipedia.org/wiki/ANSI_escape_code). Actually, powershell should support this and I can build `JetBrains/kotlin-native` with powershell 4. Is there any possibility that your powershell is misconfigured?

![screen](https://user-images.githubusercontent.com/12689835/31599366-bc47ce66-b217-11e7-9016-083314d4eab3.gif)

**Comment by eriwen** [comment]
@lukef one workaround is to set `--console=plain`. If you use Gradle 4.3+, you can make this a persistent Gradle property `org.gradle.console=plain`. Hopefully you're able to configure ANSI support with your environment though. Finally, it might be useful for us to understand if the behavior is better with Gradle 3.4 and lower if you feel compelled to test it.

**Comment by lukef** [comment]
Let me look into it. I haven't done anything crazy to my Powershell set up (newbie to windows here). My powershell version information is as follows (if it helps):

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  19
```

Running using `--console=plain` works for now but i'll post back if I figure out why my setup is different.

**Comment by lukef** [comment]
As a follow-up. Using gradle 4.3 and an out of the box setup of powershell (5) will always render incorrectly. The workaround works, but its not ideal. Pretty sure nothing is misconfigured powershell-wise.

**Comment by blindpirate** [comment]
I'll close it for now. Please feel free to reopen.
