### ISSUE TITLE
Unable to run Gradle task in 8.10 due to bytecode interception

### ISSUE THREAD

**Issue by ChrisTrenkamp** [gradle/gradle#31310]
I cannot upgrade my application to Gradle 8.10 due to bytecode interception breaking a task.  It works in 8.9.  

I get this error message:

> Inconsistent constant pool data in classfile for class org/lwjgl/system/Configuration$StateInit. Method 'java.lang.String gradle$intercept$$java$lang$System$$getProperty$0(java.lang.String)' at index 86 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef

I suspect this has to do with the new Configuration Cache.  Is there a way to work around this issue for now?

**Comment by mlopatkin** [comment]
Oh, that's unfortunate. What version of lwjgl is being used?

>Is there a way to work around this issue for now?

Not really, except not using lwjgl as part of the build script classpath.

**Comment by mlopatkin** [comment]
Actually, I'm able to reproduce the issue with a simple class on the build class path:

```java
package org.example;

import java.util.function.*;

public interface Foo {


  static Function<String, String> getFunc() {
    return System::getProperty;
  }  
}
```

We're generating
```
  #19 = Methodref          #2.#18         // org/example/Foo.gradle$intercept$$java$lang$System$$getProperty$0:(Ljava/lang/String;)Ljava/lang/String;
  #20 = MethodHandle       6:#19          // REF_invokeStatic org/example/Foo.gradle$intercept$$java$lang$System$$getProperty$0:(Ljava/lang/String;)Ljava/lang/String;
```
instead of a proper method reference to an interface static method that looks like (method name different):
```
#19 = InterfaceMethodref #2.#18         // org/example/Foo.id:(Ljava/lang/String;)Ljava/lang/String;
#20 = MethodHandle       6:#19          // REF_invokeStatic org/example/Foo.id:(Ljava/lang/String;)Ljava/lang/String;
```

**Comment by mlopatkin** [comment]
Release notes in #31300.
