### ISSUE TITLE
Java installation no longer found

### ISSUE THREAD

**Issue by msteur** [gradle/gradle#31326]
### Current Behavior

Running `./gradlew clean build ` fails with the message `Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=21, vendor=any vendor, implementation=vendor-specific} for LINUX on x86_64.`

### Expected Behavior

Running `./gradlew clean build ` should result in a successful build.

### Self-contained Reproducer Project

[gradle-regression.zip](https://github.com/user-attachments/files/17790815/gradle-regression.zip)

### Gradle version

8.10 /8.11

### Gradle version that used to work

8.9

### Your Environment (optional)

OpenSUSE Tumbleweed

This install jvms in /usr/lib64 instead of /usr/lib

**Comment by reinsch82** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

I can confirm the regression from 8.9 to 8.10 using an opensuse container.

**Comment by big-guy** [comment]
Could you run `gradle javaToolchains` on Gradle 8.9 and latest and provide the output here?

**Comment by big-guy** [comment]
Were you actually compiling anything?  Maybe we're being more strict about having a JDK installed even if you're not compiling Java source files.

**Comment by msteur** [comment]
The attached zip file contains a java source file that got compiled. So it remains a bit of a mystery to me.
But at least thanks for the pointers!
