### ISSUE TITLE
Annotation processor support for Java 23

### ISSUE THREAD

**Issue by shalabi** [gradle/gradle#31323]
### Expected Behavior

When compiling with annotations seeing this error:

warning: Supported source version 'RELEASE_22' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor' less than -source '23'

### Context

We are interested in upgrading to Java 23

**Comment by TheGoesen** [comment]
Gradles error messages in this area have a tendency to be misleading. 
Its most likely that one ore more annotation processors that you are using is annotated with 
`@SupportedSourceVersion(SourceVersion.RELEASE_22)`

However gradle does not print the name of the annotation processor and instead prints `org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor` which is an umbrella for 'could be any processor'

**Comment by shalabi** [comment]
resolve... we found it
