### ISSUE TITLE
Cross-module resource sharing limitation significantly impacts test execution performance

### ISSUE THREAD

**Issue by nick2525** [gradle/gradle#31332]
### Expected Behavior

Gradle should provide a mechanism to share heavyweight resources (like UI testing libraries initialization) across module test executions while maintaining module isolation for build integrity. This could be achieved through shared memory spaces or resource pooling.

### Current Behavior (optional)

Each module must initialize its own test environment in separate processes, preventing resource sharing. For UI testing tools like Paparazzi, this means:

~20 seconds initialization per module
No way to share initialized resources
Multiplied overhead across modules
Increased CI/CD times and infrastructure costs

### Context

Gradle Version: 8.9
Environment: Multi-module Android projects
Testing Framework: Paparazzi 1.3.4
Issue reproducible across different CI environments
Impact increases with number of modules
Example case: Android UI testing libraries requiring Layoutlib initialization

Link to connected issue from paparazzi testing https://github.com/cashapp/paparazzi/issues/1662

**Comment by reinsch82** [comment]
If what you need is an external service, you have a [build service](https://docs.gradle.org/current/userguide/build_services.html) that manages these services. Gradle manages the lifetime of these.

However for something that seems to run in the JVMs memory how do you imagine this could be shared across different test processes?
