### ISSUE TITLE
Version Catalogs plugins condition

### ISSUE THREAD

**Issue by myfaverate** [gradle/gradle#31342]
### Expected Behavior

# Can you support this
```kotlin
val isModule: String by project
if(isModule.toBoolean()){
    plugins {
        alias(libs.plugins.android.application)
        alias(libs.plugins.kotlin.android)
    }
}else{
    plugins {
        alias(libs.plugins.android.dynamic.feature)
        alias(libs.plugins.kotlin.android)
    }
}
```

### Context

In Android project, Select the plug-in based on gradle.properties.

**Comment by reinsch82** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

There are reasons why the plugins block has limited flexibility and it has to be the first one in the file.
You should leverage [convention plugins](https://docs.gradle.org/current/userguide/writing_plugins.html#convention_plugins) for achieving the same.

**Comment by myfaverate** [comment]
Thank you very much!
