### ISSUE TITLE
Improve output for ambiguous task names

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#3134]
As a user I can (and frequently do) use camel case on the command line to select a task I want to execute. This works well also in multi projects by using a path like `:c:s-s:m:bui` (or something like that).

When the tasks names are derived from other inputs that task name can become quite long it can be difficult to pick it out and visually execute it without just copying and pasting it, especially if generated by a plugin's `NamedDomainObjectContainer` or other objects.

### Expected Behavior

I can think of a few possible improvements, I'm sure there are others.

* Visually distinguish camel case characters with markup
* Output each ambiguous task choice on another line
* Prompt for input again based on the filtered tasks
* Use something like https://github.com/gradle/gradle-completion (which I'm planning on doing anyways)

### Current Behavior

For example, a current Gradle project I am looking it uses the `java-gradle-plugin` for development. It produces two plugins with similar names. Here is the output when running `./gradlew genP` to see what one of the generated POMs would be.

> * What went wrong:
>
> Task 'genP' is ambiguous in root project 'qms-tools'. Candidates are: 'generatePomFileForPluginMavenPublication', 'generatePomFileForQmsProjectPluginMarkerMavenPublication', 'generatePomFileForQmsSubprojectPluginMarkerMavenPublication'.

Looking at a terminal at going from `genP` to `genPFFQP`, `genPFFS`, or `gPFFM` are all difficult to see and figure out without having to type most of the task.

### Context

See above example

### Your Environment

Gradle 4.2.1

**Comment by oehme** [comment]
I think using Gradle completion is probably the best way to go here. Would that be a satisfactory answer for you?

**Comment by mkobit** [comment]
@oehme I think that is a better solution, closing this.
