### ISSUE TITLE
Disk I/O overhead on mac silicon machine as compared to ubuntu/linux distro

### ISSUE THREAD

**Issue by ritesh-singh** [gradle/gradle#31348]
### Current Behavior

👋  I was benchmarking some of our task-groups using gradle-profiler on mac-machine vs the linux-ubuntu distro with local and remote cache enabled.

Notice, disk i/o overhead when unpacking artifacts on mac-runner as compared to the ubuntu-distro.

**Linux distro (16 core)**

Pack | 15 | 19.896s | 273.1 MiB 
Unpack | 13334 | 28m 19.254s | 6.9 GiB

JDK - Java_Temurin-Hotspot_jdk/21.0.3-9.0.LTS

**Mac studio 20 core M1 Ultra**

Pack | 15 | 57.588s | 273.1 MiB
Unpack | 13334 | 2h 42m 42.171s | 6.9 GiB

JDK - Java_Temurin-Hotspot_jdk/21.0.3-9.0.LTS/arm64

Not sure, if it's relevant to gradle or if something can be done at gradle end to optimise the disk i/o for cache artifacts or if the mac-OS (arm machines) in general has disk i/o overhead as compared to linux (amd).

### Expected Behavior

Unpacking of cache artifacts should be same or outperform on mac ssd disk.

### Self-contained Reproducer Project

- Take any project like https://github.com/android/nowinandroid
- Enable local cache
- Run benchmark or one single build taking advantage of local cache on mac machine and linux machine.

### Gradle version

8.10.2

**Comment by ljacomet** [comment]
Could you share a few more datapoints:

* Explain what the shared numbers are? Some have units but could still be misunderstood.
* How did you obtain those numbers? Your reproduction steps are very limited.
* What are the disks on both machines? Technology, capacity, brand and free space

Without that information, reproducing those results will be a challenge. And having that information might help us match the performance testing we do internally.
