### ISSUE TITLE
Rename configurable `Provider` subtypes to make the role of each type clearer and the names consistent

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#3136]
Several different naming schemes have emerged for the configurable `Provider` subtypes. Rename these types before they are widely used to make the names clearer.

Specifically:

- `PropertyState` -> `Property`. This thing represents a configurable property. Let's get rid of the 'state' as it doesn't add any value.
- `DirectoryVar` -> `DirectoryProperty`. Use 'property' instead of 'var' for all configurable properties.
- `RegularFileVar` -> `RegularFileProperty`. As above.
- `ListProperty` -> stays the same.

**Comment by bmuschko** [comment]
As follow up work items we'll also have to update the use of those classes in guides and guide samples. I created the following issues:

- https://github.com/gradle-guides/gradle-site-plugin/issues/1
- https://github.com/gradle-guides/implementing-gradle-plugins/issues/13

**Comment by eriwen** [comment]
@adammurdoch Does "Regular" in `RegularFileProperty` add value? I presume this distinguishes this from a link?

**Comment by adammurdoch** [comment]
@eriwen A "regular file" is-a kind of file, but there are other kinds of files such as, as you point out, symlinks, but also directories, named pipes, devices, and so on. I don't want to use "FileProperty" as the name for this because I want to make it clear that the value of this property is always a "regular file" and not any other kind of file.

Generally, what a task is after when it uses a "regular file" is something with binary content (so not a directory) that is bounded in size (so not a 'stream' like a named pipe or device).

**Comment by eriwen** [comment]
Thanks for the explanation, Adam. `FileProperty` definitely wouldn't be descriptive enough as you say. I tried to think of a better word than "Regular" and couldn't.

**Comment by melix** [comment]
It would be nice if the error message said:

```
The property(Class) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getObjects().property(Class) method instead.
```
instead of:
```
The property(Class) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the ObjectFactory.property(Class) method instead.
```

otherwise one has to find where to get a handle on this object factory.

**Comment by adammurdoch** [comment]
The message should suggest `getObjects()` as a replacement when the `ProviderFactory` was accessed via `getProviders()`. If it was accessed by injection (ie using `ProviderFactory` as the injected type), it should suggest `ObjectFactory` as the replacement.

**Comment by ldaley** [comment]
Death to all `PropertyState` specializations.
