### ISSUE TITLE
NPE when "basicProblemDetails" is null

### ISSUE THREAD

**Issue by hegyibalint** [gradle/gradle#31371]
CI brought up this problem: https://builds.gradle.org/repository/download/Gradle_Master_Check_PerformanceTestSlowLinuxbucket18/91856447:id/results/performance/build/test-results-largeAndroidBuildPerformanceTest.zip!/performance-tests/report/index.html

Probably caused by the implementation in #31043

**Comment by hegyibalint** [comment]
@alllex had a great insight into this:

> This one seems to be straight-forward: we use a regular HashMap with computeIfAbsent, but given the exception, the access to the map itself is not synchronized
[https://github.com/gradle/gradle/blob/e653eceb310d16f026e9db766c216ea3bbab6af8/pla[…]gradle/problems/internal/services/DefaultProblemSummarizer.java](https://github.com/gradle/gradle/blob/e653eceb310d16f026e9db766c216ea3bbab6af8/platforms/ide/problems/src/main/java/org/gradle/problems/internal/services/DefaultProblemSummarizer.java#L103)

**Comment by alllex** [comment]
@hegyibalint, I am not sure that this is connected. The suggestion I provided was to mitigate the `ConcurrentModificiationException` happening when the `seenProblemsWithCounts` is mutated without synchronization. I don't know if one might be the cause of the other , or whether they are separate problems.
