### ISSUE TITLE
Deprecate nested builds without a settings.gradle

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#3137]
As stated in https://github.com/gradle/gradle-private/issues/708, we're going to deprecate and remove support for upward-searching `settings.gradle`.

With this change, this part of https://docs.gradle.org/4.2.1/userguide/build_lifecycle.html#sec:initialization would be changed to:

- If a settings.gradle file is found, Gradle checks if the current project is part of the multiproject hierarchy defined in the found settings.gradle file. If not, AN EXCEPTION WILL BE THROWN. Otherwise a multiproject build is executed.

However, given that this is a considerable behavior change, I'd like to break this thing into two steps:

- [x] Deprecate the suport in 4.4
- [ ] Remove the support in 5.0

The deprecation thing includes:

- Deprecation warning when user's build doesn't contains a `settings.gradle` and is not part of a multiproject.

**Comment by oehme** [comment]
> If a settings.gradle file isn't found in current project, the build is executed as a single project build.

This is not the intended behavior.

The linked ticket is about the following scenario: You have a build with a settings.gradle file. Nested in a directory under that build is another build without a settings.gradle file. When you try to run that nested build, Gradle will search upwards to find the settings.gradle file, load that file and determine that the project you were trying to start is actually not part of that higher-level build. It will then roll back a bunch of services and start again, treating it as a single-project build instead.

```
foo
  settings.gradle // does not include bar
  build.gradle
  bar // user starts a build here
    build.gradle
```

This is complex and should be deprecated/removed.

In the future, Gradle would throw an error when it finds a settings.gradle file further up, but that settings.gradle file doesn't actually include the project you were trying to run. To fix that, the user should add a settings.gradle file to the nested build.


```
foo
  settings.gradle
  build.gradle
  bar
    settings.gradle //this fixes the problem, it is now clear that this is a different build
    build.gradle
```
