### ISSUE TITLE
Gradle not picking up build configuration changes

### ISSUE THREAD

**Issue by hallatech** [gradle/gradle#3138]
I'm testing upgrading from 2.14.1 to 4.2.1
I've updated the wrapper: gradle wrapper --no-daemon
I've started a new 4.x build: gradle clean build
When editing build files to remove warnings and rerunning the changes are not always (i.e. mostly not) being picked up.

### Expected Behavior
Every time a build file is changed it should be picked up on the next execution. This always happens correctly under 2.14.1

### Current Behavior

There are various build files that produce warnings such as this:

`> Configure project :Development:Versioned
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_2cuf8gs9p9rwikw8xfh2fdikw.run(/home/vagrant/workspace/myproject/Development/Versioned/build.gradle:51)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)`

I change the equivalent of `taskX << {` to `taskX.doLast {`.  The build file is saved in Eclipse, and is available on the FS in the VM.
I rerun: `gradle clean build` (Note the daemon is running as default - no overrides)
Sometimes the warning is gone and the next one in the same or next file comes up.
Sometimes the same warning appears and goes away after I run the command a second time.
Sometimes the same warning comes up and does not go away after multiple invocations. To remedy this I need to run:
`gradle --stop; gradle clean build`
There seems inconsistency in the way the daemon is picking up changes to the build files.

### Context
Its not affecting me directly longer term, i.e. I'm just walking through converting the build configuration , but this is not expected behaviour as it never did this under 2.x. Any change was always picked up correctly by the daemon on the next build request

### Steps to Reproduce (for bugs)
Its not really a build error but a behavioural issue with the daemon not picking up some changes.

### Your Environment
Vagrant headless Linux VM on Mac OS Sierra host.
Running gradle builds in the VM with Eclipse on the host.
Synced folders between host and guest VM
Exact same environment running and working on 2.14.1 but this problem only arises when running on 4.2.1.
In 2.14.1, the daemon was always on by virtue of configuration in gradle.properties

 * Build scan URL: N/A

**Comment by hallatech** [comment]
I've been experiencing this a lot just now even on fresh plugin build projects. Even more frustrating I'm getting frequent hangs where it just says IDLE and does nothing. A Ctrl-C and the second run normally picks it up. It hangs in IntelliJ, it hangs on the CLI on the Mac and in my Linux VM. Really frustrating as there is no way I can know whether a build change has guaranteed to actually been picked up unless I stop and restart the daemon. This never happened under 2.14. :(

**Comment by hallatech** [comment]
The IDLE issue might be misleading and un-related. I noticed when I happened to catch the IDLE problem with debug that there were multiple daemons running, 1 in the VM and 1 on the host against a shared ~/.gradle dir. Sometimes there were also 2 daemons running on the host, 1 from the CLI and 1 spawned by IJ. The IDLE-stuck daemon eventually timed out with an error

**Comment by oehme** [comment]
Many of the issues you are describing sound like you are trying to share a Gradle user home between the host and VM. This is not supported. It would be okay if you only synced your gradle.properties, but sharing the caches will lead to problems.

**Comment by oehme** [comment]
Closing as there was no further response to the advice above. Feel free to reopen with more details.

**Comment by hallatech** [comment]
Thanks, I had to step away from this for quite awhile. 
Yes we are sharing the gradle cache between the host and the VM, but mostly to allow us to share the cache over time between many VMs to reduce the time to redownload all dependencies and gradle itself. This has actually worked fine for years and still works in a Docker environment using the host's gradel cache as a shared volume in 1 or more containers (albeit mostly 1 so in the same sense as a VM sharing the hosts cache).

**Comment by hallatech** [comment]
I'll review this when getting back to the upgrade task. Thanks again.
