### ISSUE TITLE
"Writing Build Scripts": provider is not explained

### ISSUE THREAD

**Issue by louwers** [gradle/gradle#31399]
### Issue type

Missing information

### Problem description

The [extra properties](https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:extra_properties) sections shows a code snippet which uses `provider`. This is not explained, nor is it explained in any of the documentation that is linked to. So this is quite confusing when reading a "Learning the Basics" guide.

If possible, the `provider` syntax / function should be explained. If not in scope for an introductory guide, it should not be used.

### Page with the problem

https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:extra_properties

**Comment by ov7a** [comment]
This is a valid documentation issue.

***

Learning the basics should cover the Providers API, which is a key item of the configuration API.

**Comment by lkasso** [comment]
@louwers, I added a link to the entire section called [Understanding Gradle Types](https://docs.gradle.org/current/userguide/properties_providers.html) as a temporary fix. 
Check out the attached PR.

I will update this more conclusively when I rewrite this tutorial next year, but it is out of scope right now.
