### ISSUE TITLE
Missing snippet Javadoc task

### ISSUE THREAD

**Issue by louwers** [gradle/gradle#31397]
### Issue type

Wrong or misleading information

### Problem description

There is a snippet missing here:

![Image](https://github.com/user-attachments/assets/57ffd8e0-6c1f-433d-ae79-eb0cee251522)

### Page with the problem

https://docs.gradle.org/current/userguide/writing_build_scripts.html#5_register_and_configure_tasks

**Comment by ov7a** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

**Comment by bodhili** [comment]
> This is a valid documentation issue.
> 
> We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

Hi ov7a @ov7a , Is this example right for issue #31397 (Gradle 8.11.1)?   thanks!

```kotlin
  // build.gradle.kts

  tasks.named<Javadoc>("javadoc").configure {
    exclude("app/Internal*.java")
    exclude("app/internal/*")
  }
```

```grvooy
// build.gradle
tasks.named("javadoc", Javadoc) {
    exclude 'app/Internal*.java'
    exclude 'app/internal/*'
}
```

**Comment by bodhili** [comment]
> [@bodhili](https://github.com/bodhili) Yes. The docs for that will be fixed in
> 
> * [Missing snippet Javadoc task #31397](https://github.com/gradle/gradle/issues/31397)

OK
