### ISSUE TITLE
Code sample "Apply plugins to the build" is wrong

### ISSUE THREAD

**Issue by louwers** [gradle/gradle#31396]
### Issue type

Wrong or misleading information

### Problem description

On this page: https://docs.gradle.org/current/userguide/writing_build_scripts.html#writing_build_scripts

It reads:

> The Kotlin gradle plugin, version 1.9.0, has also been applied.

However, the this is not true for the corresponding code sample.

### Page with the problem

https://docs.gradle.org/current/userguide/writing_build_scripts.html#writing_build_scripts

**Comment by ov7a** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

**Comment by lkasso** [comment]
Thank you for finding this outdated paragraph. I have removed it.
