### ISSUE TITLE
Pre-compiled script plugin contains wrong example code

### ISSUE THREAD

**Issue by louwers** [gradle/gradle#31400]
### Issue type

Wrong or misleading information

### Problem description

This snippet refers to a 'MyCreateFileBinaryPlugin'.

```kt
gradlePlugin {
    plugins {
        create("my-binary-plugin") {
            id = "com.example.my-binary-plugin"
            implementationClass = "MyCreateFileBinaryPlugin"
        }
    }
}
```

However, the preceding snippet shows a snippet of code from a completely different section! This is not even a plugin.

![Image](https://github.com/user-attachments/assets/6c866123-e4d4-4685-90eb-2674e0da0c7d)

### Page with the problem

https://docs.gradle.org/current/userguide/writing_plugins.html#pre_compiled_script_plugin

**Comment by ov7a** [comment]
This is a valid documentation issue.

***

Indeed, this page brings confusion. Please refer to the [full docs](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_precompiled.html) until it's fixed.

**Comment by louwers** [comment]
I think there are some recent regressions, older versions of the documentation show the correct code snippet.
