### ISSUE TITLE
Lost important documentation parts in 8.11

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#31414]
### Issue type

Missing information

### Problem description

The docs of 8.11 lost very important parts of the documentation.
For example the whole "Sharing outputs between projects" section is gone and only redirects to `dependency_resolution_basics.html#dependency-resolution-basics` which does not provide *any* relevant information.

### Page with the problem

https://docs.gradle.org/current/userguide/cross_project_publications.html

**Comment by lkasso** [comment]
@Vampire, I'm currently adding a How To Guide section for "Sharing outputs between projects" in Gradle 8.12. 
Is there anything else you want me to "put back"?

**Comment by Vampire** [comment]
I did not check what else was removed, I just searched for that specific section to share it with another user and was not able to find it, and then recognized the commit that deleted it together with some other things, so intentionally wrote the report a bit blurry, sorry. :-)

**Comment by lkasso** [comment]
No problem, if there is anything else you find missing, feel free to add it to this thread or ping me and I will take care of it.

**Comment by Vampire** [comment]
#31920 it seems, on Slack that section was also just missed

**Comment by lkasso** [comment]
> [#31920](https://github.com/gradle/gradle/issues/31920) it seems, on Slack that section was also just missed

I'm currently working on this. The information is there but it is hard to find.
