### ISSUE TITLE
Revert Eclipse classpath separation

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3142]
As discussed on Slack, this feature needs some rework before it goes in, so let's revert for 4.3 and do it in 4.4 instead.

**Comment by oehme** [comment]
Done by https://github.com/gradle/gradle/commit/0f7ac32fbfd8cf7181e0e47ee059496bb77aa4cb

**Comment by donat** [comment]
This issue is listed in the release notes as fixed. Maybe we want to remove it from there. Should we just remove the milestone tag?

**Comment by oehme** [comment]
We probably shouldn't list "chores" in general. The milestone is useful to know when we are ready to release (no more stories with that milestone).
