### ISSUE TITLE
Kotlin Assignment Plugin doesn't recognize annotations used by Gradle for set methods in buildSrc Gradle plugins

### ISSUE THREAD

**Issue by dmitry-stakhov** [gradle/gradle#31421]
### Current Behavior

This is a follow up issue for the Kotlin issue: https://youtrack.jetbrains.com/issue/KT-73396/Kotlin-Assignment-Plugin-Missing-error-message-for-error-from-assign-plugin

Steps to reproduce:
Create a custom Gradle plugin in buildSrc folder, for example like this:
```kotlin
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

class MyPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.configure(KotlinMultiplatformExtension::class.java) {
            compilerOptions {
                optIn = listOf<String>()
            }
        }
    }
}
```
It seems that the assignment compiler plugin is applied, but Gradle doesn't add `import org.gradle.kotlin.dsl.assign` and the code fails to build.

According to [this comment](https://youtrack.jetbrains.com/issue/KT-73396/Kotlin-Assignment-Plugin-Missing-error-message-for-error-from-assign-plugin#focus=Comments-27-11114797.0-0) the issue is on Gradle side, so reporting it here.

### Expected Behavior

The mentioned import should be added and the code should be built successfully.

### Self-contained Reproducer Project

[ForgottenReproducer.zip](https://github.com/user-attachments/files/17921662/ForgottenReproducer.zip)

### Gradle version

8.10.2

**Comment by asodja** [comment]
In `.kt` files you have to manually import `assign` overload methods. There is no way to automatically add imports as in `.kts` scripts. T
If that has changed let us know.

IntelliJ will help you adding import with quick actions for `=` as for other operator overload methods: 
![Image](https://github.com/user-attachments/assets/e1a1bcc5-5b2a-429d-9c21-0d6b2d563ca2)

**Comment by ov7a** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

*** 

The assignment feature is not intended to work in binary plugins, it's a DSL feature.
