### ISSUE TITLE
Duplicate documentation

### ISSUE THREAD

**Issue by tg-freigmbh** [gradle/gradle#31477]
### Issue type

Wrong or misleading information

### Problem description

There are 2 pages in the documentation describing project Properties
https://docs.gradle.org/current/userguide/build_environment.html#sec:project_specific_properties
https://docs.gradle.org/current/userguide/project_properties.html

It seems to me like the second link is older and probably should just be deleted as it doesnt have much/any additional information.

### Page with the problem

https://docs.gradle.org/current/userguide/build_environment.html#sec:project_specific_properties

**Comment by jbartok** [comment]
This is a valid documentation issue.

**Comment by lkasso** [comment]
[project_properties.html](https://docs.gradle.org/current/userguide/project_properties.html) is an outdated page and is due to be removed in Gradle 8.12's documentation.
