### ISSUE TITLE
Gradle 9.0: Evaluate which dependency management types need to be migrated to lazy

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#31492]
This is an issue to double check what would be good to be lazy for Gradle 9.0 that is related to dependency management.

I've added PublishArtifact, ConfigurablePublishArtifact and ConfigurationVariant to [the board ](https://github.com/orgs/gradle/projects/124/views/1).

From Slack discussion https://gradle.slack.com/archives/C02V8UKCXPT/p1733151935466709

> Justin
ConfigurationVariant is related defining artifacts. Its getDescription which is incubating should really be a Property
ArtifactCollection#getFailures does not have a lazy counterpart -- making it difficult to consume failures lazily
ArtifactView.ViewConfiguration is an interesting class. I'm not sure if this should be lazy or not (mostly the lenient flag, but withVariantReselection too)
There is also everything on ResolutionStrategy which is not lazy atm. There are definitely some legacy things around here though so I'm not sure if making all of this lazy is really necessary.
Finally there is the Configuration type, with several fields that could
be migrated to provider API. Not sure what the discussion behind migrating that type was.isTransitive may be good to migrate. get/setDescription maybe? Also shouldResolveConsistentlyWith/disableConsistentResolution is an interesting field

**Comment by jvandort** [comment]
I think we should go with what we originally talked about:
- ConfigurationVariant#getDescription should be migrated from an Optional to a (mutable) Property
- PublishArtifact + ConfigurablePublishArtifact
- Configuration:
    - set/isTransitive
    - set/getDescription
- ResolutionStrategy:
    - activateDependencyLocking/deactivateDependencyLocking
    - disableDependencyVerification/enableDependencyVerification

**Comment by jvandort** [comment]
@asodja Please close when you ack

**Comment by asodja** [comment]
Thanks!
