### ISSUE TITLE
Model auto-applied plugin requests better

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3149]
Right now we shoehorn them into the existing `DefaultPluginRequest` with scriptDisplayName = "auto applied" and lineNumber=null. We should find a better model for this.

**Comment by oehme** [comment]
Also consider addressing this comment: https://github.com/gradle/gradle/pull/3148#discussion_r144208618

**Comment by oehme** [comment]
I've updated the title and description to not prescribe an implementation, but describe the problem instead. It's still open what we actually do about it.
