### ISSUE TITLE
setJvmArgs in JavaExecHandleBuilder with an empty-string argument causes java-exec to fail

### ISSUE THREAD

**Issue by parasgithub** [gradle/gradle#3154]
The setJvmArgs method of the JavaExecHandleBuilder class (which takes an iterable as a parameter) causes java-exec to fail when one of the jvm arguments is an empty string.

### Expected Behavior

Java execution should not fail.

### Current Behavior

Java execution fails.

### Context

I was trying to customize a java-exec task to invoke compilation for https://github.com/gosu-lang/gosu-lang. I was making use of environmental variables to specify the jvm-args that are passed to the java-exec task, and one of the environmental variables had value "" (empty string). 

### Steps to Reproduce (for bugs)

[https://github.com/parasgithub/gradle-bug]
compare output of compileFile and compileFileFixed tasks.
[](url)
### Your Environment

 * Build scan URL: https://scans.gradle.com/s/fitwjelnfmcda

**Comment by bmuschko** [comment]
Thanks for reporting. I believe the error message could be better here. It should be very straight forward to filter out empty String in the build script before passing them as arguments. This is so minor that I do not believe we'll prioritize anytime soon. If you feel strongly about having better handling for this then I'd propose you submit a pull request and we'll be happy to review it.
