### ISSUE TITLE
User Guide: 27.5.2. Applying plugins: should be "apply plugin: <<plugin id>>" instead of "apply plugin: <<plugin version>>"

### ISSUE THREAD

**Issue by ewirch** [gradle/gradle#3155]
Chapter 27.5.2, section "Applying plugins to subprojects", contains this sentence:

> But, you can use the apply false syntax to tell Gradle not to apply the plugin to the current project and then use `apply plugin: «plugin version»` in the subprojects block

It should be `apply plugin: «plugin id»` instead.

**Comment by oehme** [comment]
Thanks for the pointer!
