### ISSUE TITLE
Java Debugger Options should imply --no-daemon

### ISSUE THREAD

**Issue by stovocor** [gradle/gradle#3156]
Starting a build using the Gradle wrapper, existing daemon instances do not stop at breakpoints.

### Expected Behavior
When specifying debugger options with GRADLE_OPTS like

`GRADLE_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"`

a build with the Gradle wrapper should stop at breakpoints specified in the IDE.

### Current Behavior
Starting the Gradle wrapper build with

`GRADLE_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"`

suspends the startup until a debugger client has connected. So it looks like the debugger is correctly setup, but the execution does not stop at any breakpoint. Using the option '--no-daemon' works as expected.

### Steps to Reproduce (for bugs)
1. Start a build using the Gradle wrapper
2. Set `GRADLE_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"`
3. In your IDE, specify a breakpoint in the Gradle code that should be triggered
4. Start another build using the Gradle wrapper
5. Connect your IDE. The breakpoint will not be triggered.

**Comment by oehme** [comment]
When you want to connect to the daemon instead of the client, please use `org.gradle.jvmargs` in your `gradle.properties`. `GRADLE_OPTS` is only for the client VM that connects to the daemon (or that runs the build when using no daemon).
