### ISSUE TITLE
The Gradle build should use component metadata rules to adjust dependencies of external modules

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3161]
At the moment the build uses the _Client Module_ concept to override dependencies of external modules in [dependencies.gradle](https://github.com/gradle/gradle/blob/master/gradle/dependencies.gradle). Once #3157 is implemented, that new mechanism should be used instead and the client modules should be deprecated.

**Comment by jjohannes** [comment]
Started to try out some new things: https://github.com/gradle/gradle/tree/jjohannes/dependency-management/gradle-build-with-metadata-rules

**Comment by bigdaz** [comment]
@jjohannes what's left to call this complete?

**Comment by jjohannes** [comment]
I think this is complete. The Gradle build now uses component metadata rules instead of _client modules_ and `@jar` dependencies in `dependencies.gradle`.

https://github.com/gradle/gradle/commit/f4d7dde27b74f734e124d72bfaf5ca5ca995b799

We will continue to dogfood further improvements as part of separate issues.
