### ISSUE TITLE
Deprecate ClientModule

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3163]
Once #3157 is implemented as replacement and the Gradle build is adjusted #3161.

**Comment by jjohannes** [comment]
With #3360 integrated, Client Modules will stop working for maven dependencies. Because we ignore them for variant-aware dependencies here, which is by design:
 https://github.com/gradle/gradle/blob/7eddd3e185e3bd6e7067587819c5b0856eeb007c/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/clientmodule/ClientModuleResolver.java#L150

We need to make sure to deprecate asap and remove the feature in 5.0.

**Comment by bmuschko** [comment]
FYI: I already removed documentation on this with my [latest changes to the dependency management chapter](https://github.com/gradle/gradle/commit/fc24d15a25e51534ef7af384f0b66f9f78d1b2ae).

**Comment by jjohannes** [comment]
After discussing with @bigdaz, I fixed the issue mentioned above in #3960. This decouples the need to deprecate the client modules feature from the advanced pom support which should become the default in 5.0.

We will still do this (deprecate client module) but we have to make sure that component metadata rules are ready, as a better replacement, first.

**Comment by jjohannes** [comment]
We should do this deprecation now (6.x). Component metadata rules now offer the same expressiveness (and more). The deprecation message should point users to component metadata rules as a replacement.

**Comment by ljacomet** [comment]
Currently `ClientModule` can add metadata to a local library. Which is something a `ComponentMetadataRule` cannot model.

**Comment by jjohannes** [comment]
In the end, there are no plans to deprecate this.
