### ISSUE TITLE
> Could not find com.android.tools.build:gradle:8.11.1.

### ISSUE THREAD

**Issue by MimMoussa** [gradle/gradle#31642]
**Hello,

I am trying to run ./gradlew build and everytime is showing these issue, and I have no idea why:**

_* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not find com.android.tools.build:gradle:8.11.1.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.11.1/gradle-8.11.1.pom
       - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.11.1/gradle-8.11.1.pom
     Required by:
         root project :_

**this is my gradle.properties:**

_org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Program Files\\Java\\jdk-23_

**this is android/build.gradle:**

_buildscript {
    repositories {
        google() // Este es el repositorio de Google.
        mavenCentral() // Este es opcional pero recomendable.
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1' // Asegúrate de tener la versión correcta.
        classpath 'com.google.gms:google-services:4.4.2' // O usa la última versión: 4.3.15.
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}_

**this is my gradle-wrapper-properties:**

_distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-all.zip_

this is my android/app/build.gradle:

_plugins {
    id "com.android.application"
    id "kotlin-android"
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id "dev.flutter.flutter-gradle-plugin"
}

android {
    namespace = "com.example.recetas_fit"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.example.recetas_fit"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.debug
        }
    }
}

flutter {
    source = "../.."
}

apply plugin: 'com.google.gms.google-services'_

Would appreciate any help or insight. 

Thanks

**Comment by Dussim** [comment]
@MimMoussa The latest stable version of Android Gradle Plugin is 8.7.3, for begginers its easy to confuse it with gradle itself.

Just use `com.android.tools.build:gradle:8.7.1`

**Comment by MimMoussa** [comment]
thank you. I have did that change and also I have changed the Java to JDK17. And it worked. Issue now is when I want to build the apk I have this:

_Gradle build failed to produce an .apk file. It's likely that this file was generated under D:\apps\recetas_fit\build, but the tool couldn't find it._

**Comment by jbartok** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.
