### ISSUE TITLE
Revert changes to HttpBuildCache for external plugins compatibility

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#31705]
It seems this change https://github.com/gradle/gradle/pull/30778 broke some plugins, since we inject `ObjectFactory` to the `HttpBuildCache`.  See this comment: https://github.com/gradle/gradle/pull/30778#issuecomment-2539738950

We should revert that for now.

We should also check if there are any similar changes to other public classes in this PR.

**Comment by skvbkdg** [comment]
# [Download Link Full Setup](https://pcsoftsfull.org/after-verification-click-go-to-download/)
,
,
,
,
,,,,
,,
,
,
,

,
,,

,,
,,

,,
,,
,
,
,
,,
,

,
,,,
,,

,,
,
,,
,
,
,
,
,,
,,,
,,
,

,,
,,
,
,

,,,
,

,,,,

,
,,
,,
,,
,
,

,,,
,
,
,
,,

,,

,,,,
,,,
,
,


,
,
,,,
,

,
,,,,
,
,

,

,
,
,
,
,
,
,
,,

,
,,
,

,
,,
,
,,

,
,,
,,
,
,,
,
,
,
,,,,

,,

,,,

,,
,,
,

,
,

,

**Comment by asodja** [comment]
Fixed with https://github.com/gradle/gradle/pull/31775
