### ISSUE TITLE
Expose a build method on GradleRunner that doesn't assert the build execution result

### ISSUE THREAD

**Issue by radarsh** [gradle/gradle#3173]
Gradle TestKit currently has two public methods that return a `BuildResult`. However, both these methods assert the build execution status and throw either `UnexpectedBuildFailure` or `UnexpectedBuildSuccess` exceptions.

It would be good if there was an additional build method that simply returned the build execution result rather than throwing an exception. In some cases, our tests would want to be in charge of this assertion. This is especially the case if we have a test helper method that abstracts the `GradleRunner` from the tests. For example,

```groovy
private BuildResult run(String project, String args) {
    GradleRunner.create()
        .withGradleVersion('4.2')
        .withProjectDir(new File(project))
        .withPluginClasspath()
        .withDebug(true)
        .withArguments(args.split(' '))
        .forwardOutput()
        .build()
}
```

Then if we had a generic test such as the following, it would still work

```groovy
@Unroll
def "test that build on #project is #result"() {
    when:
        def result = run(project, 'clean build')
    then:
        result.task(':build').outcome == result
    where:
        project        | result
        'good-project' | SUCCESS
        'bad-project'  | FAILURE
}
```

Currently however, as our `run` helper calls `GradleRunner.build` internally, it expects the build to only pass and will throw `UnexpectedBuildFailure` if it didn't, leaving me unable to have a clean and readable test.

**Comment by bmuschko** [comment]
I'll like to avoid making the API more complex than it is right now. Your use case could easily be solved by splitting the test case or introducing the following change:

```
private BuildResult run(String project, String args, boolean successfulOutcome) {
    def gradleRunner = GradleRunner.create()
        .withGradleVersion('4.2')
        .withProjectDir(new File(project))
        .withPluginClasspath()
        .withDebug(true)
        .withArguments(args.split(' '))
        .forwardOutput()

     successfulOutcome ?  gradleRunner.build() : gradleRunner.buildAndFail()
}
```

**Comment by radarsh** [comment]
@bmuschko thanks. I have handled it currently as follows:

```groovy
private BuildResult runProject(File projectDir, String args) {
    try {
        GradleRunner.create()
            .withGradleVersion('4.3')
            .withProjectDir(projectDir)
            .withPluginClasspath()
            .withDebug(true)
            .withArguments(args.split(' '))
            .forwardOutput()
            .build()
    } catch (UnexpectedBuildFailure e) {
        e.buildResult
    }
}
```

You may close this issue.
