### ISSUE TITLE
Continuous build fails with "User limit of inotify watches reached" on large project

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#3174]
### Expected Behavior

Gradle should not fail or should degrade gracefully (e.g., emit a warning that there's a problem with the build/OS/whatever).

### Current Behavior

When running a Play application with hot reload (IOW `gradle runPlayBinary`), when Gradle drops into "continuous build"-like behavior, it fails while trying to watch all of the build's input files.

### Context

I can provide more context privately.

### Steps to Reproduce (for bugs)

1. `gradle runPlayBinary`
2. Interact with Play application.

### Your Environment

This is occurring with Gradle 4.2.

**Comment by bigdaz** [comment]
Can you see if the same issue occurs if you run a simple task (not `PlayRun`) with continuous build? Something like `gradle -t assemble`.

This would give us an idea if this problem is specific to running Play applications or a problem with continuous build in general.

**Comment by blindpirate** [comment]
@bigdaz Yes, the same issue does occur with `gradle -t assemble`. It's due to linux's inotify limit.

Step to reproduce:

- On Linux.
- `echo 1 | sudo tee /proc/sys/fs/inotify/max_user_watches` to change the limit to 1
- Run `gradle -t assemble` in any project.

**Comment by oehme** [comment]
This also affects earlier versions. The workaround is to raise the max_user_watches value.
