### ISSUE TITLE
Gradle 4.x hangs when using composite builds and a plugin project

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#3175]
Gradle hangs indefinitely when the included build is substituted in the classpath of the buildscript.

### Expected Behavior

Gradle does not hang.

### Current Behavior

Gradle hangs while resolving the compile classpath.  This happens reliably with a given project.

### Context

It appears to be related to the number of direct dependencies in the build script, the number of workers and the order the substituted project appears.

e.g., The build that hangs looks something like this (but I haven't been able to reproduce it):

```
buildscript {
   dependencies {
     classpath 'org:pluginA:1.0'
     classpath 'org:pluginB:1.0'
     classpath 'org:pluginC:1.0'
     classpath 'org:pluginD:1.0'
     classpath 'org:pluginE:1.0'
  }
}
```

With `--max-workers=4`, running `gradle tasks --include-build=../path/to/pluginE` will cause a hang.

Reordering the dependencies fixes the problem.  The substituted plugin just needs to be within the first 'max workers' number of dependencies.  I can provide more context privately with information about the complexity of the given plugin projects.  

### Your Environment

This was reproducible with 4.0-4.2.

**Comment by adecker89** [comment]
I believe that I've run into this issue as well on gradle 4.5. It's a particularly nasty failure case as it gives very little indication as to what is causing the hang and can be impossible to reproduce locally since environmental factors such as cpu count are at involved.

**Comment by adammurdoch** [comment]
Is this still an issue? There have been a bunch of deadlock fixes since 4.2 (and some new ones added, no doubt).

**Comment by fcurts** [comment]
@adammurdoch I just ran into this issue with 5.1.1, or at least I believe it's the same issue.

Downstream build uses a plugin of an included build.

When executing `gradlew idea` for the downstream build, it is forever stuck in:
```
> :xxx:ideaModule > Resolve dependencies of :xxx:compileClasspath
> :yyy:ideaModule > Resolve dependencies of :yyy:compileClasspath
```

Debug output is an endless loop of:
```
02:48:49.775 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
02:48:49.776 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:48:49.776 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:48:49.776 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:48:49.777 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:48:49.777 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:48:49.777 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:48:50.909 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(11)-127.0.0.1: (port 53133) connection closed
02:48:50.909 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(11)-127.0.0.1: close connection
02:48:52.378 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 34359738368, Free: 18163306496}
02:48:52.378 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 34359738368, Free: 18163306496}
02:48:52.378 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 514850816, Committed: 479199232}
02:48:55.424 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(12)-127.0.0.1: (port 53133) connection closed
02:48:55.424 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(12)-127.0.0.1: close connection
02:48:57.375 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 34359738368, Free: 18166566912}
02:48:57.375 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 34359738368, Free: 18166566912}
02:48:57.376 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 514850816, Committed: 479199232}
02:48:59.775 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
```

Setting `org.gradle.parallel=true` for the downstream build immediately solves the issue.

The issue appeared out of nowhere; I still don't know what triggered it and desperately tried to fix it for hours until I found this issue.

**Comment by ibejoeb** [comment]
> When executing `gradlew idea` for the downstream build, it is forever stuck in:
 
> Setting `org.gradle.parallel=true` for the downstream build immediately solves the issue.

Exactly the same experience with the `idea` plugin on gradle 5.5.1. Parallel workaround works, e.g., `gradle --parallel idea`.

**Comment by jjohannes** [comment]
Instead of using `gradlew idea`, the import features of the latest IDEA version should be used directly. If there is still an issue as the one described here with Gradle 6.7+, please open a new issue with a reproducer.
