### ISSUE TITLE
Missing `cache.properties` file causes Gradle to fail to start

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#3176]
Sporadically, starting with Gradle 4.2, the file `.gradle/buildOutputCleanup/cache.properties` is removed or fails to be created when starting the Gradle daemon.  This causes the build to fail very early (while creating `TaskExecutionServices`) and is unrecoverable without deleting the `.gradle` directory or creating the missing file by hand.  Stopping and restarting the daemon doesn't recreate the file.

This doesn't appear to happen on every build and I believe the build sometimes works and then fails later (with another new daemon).

### Expected Behavior

Gradle would not fail to start.

### Current Behavior

Gradle fails with a cryptic message:
```
Could not create service of type TaskOutputFilesRepository using TaskExecutionServices.createTaskOutputFilesRepository(). 
> java.io.FileNotFoundException: /path/to/project/.gradle/buildOutputCleanup/cache.properties (No such file or directory)
```

### Context

I can provide more context privately.

### Steps to Reproduce (for bugs)

This happens sporadically.

### Your Environment

The build is running inside a Linux Docker container. 

This occurs on Gradle 4.2.  Previously, the project was using 4.0.2 and didn't see this problem.

**Comment by blindpirate** [comment]
The failure occurs [here](https://github.com/gradle/gradle/blob/4faebce1380d6778a4d4de8c06bcf11540629b95/subprojects/core/src/main/java/org/gradle/cache/internal/DefaultPersistentDirectoryCache.java#L83), where Gradle tries to load `cache.properties`. It's easy to reproduce, just remove `.gradle/buildOutputCleanup/cache.properties` and rerun any gradle task. However, I tried both `4.2.1` and `4.0.2` and they both see this issue. So the question is: when and where is it removed? I couldn't find out any clues in code, @big-guy please give me more context privately.

**Comment by npappassl** [comment]
Removing the cache.properties.lock file did the trick for me

**Comment by FauricioValencia** [comment]
las rutas??

**Comment by esipavicius** [comment]
With ubuntu I start react-native run-android with sudo. So its gets permissions to download .gradle. Maybe its works when chmod .gradle folder.

**Comment by backdoorcodr** [comment]
or by removing the `workerMain.lock`  !
