### ISSUE TITLE
Support mapping command line options to user input

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3180]
**Requirements**

- Non-interactive consoles do not allow for capturing input via the command line
- The API exposes a way to map command line options and their values to a requested user input
- Works with the Tooling API and from the IDE

**Test cases**

- If command line option is mapped and value is provided then the return value of the user input is the mapped value.
- If command line option is mapped and value is not provided then the return value of the user input is null.
- If the command line option is not mapped then the return value is still null.
- User cannot enter answer if mapped command line option is mapped.

**Comment by adammurdoch** [comment]
This feels back to front to me. I would consider reusing the build option concept to model the logical input (which is exactly what a build option represents) and then add support for prompting the user for the value of a build option when none is provided in some other way.
