### ISSUE TITLE
There is a difference in behavior between running Gradle tests in IDEA and running them from the command line.

### ISSUE THREAD

**Issue by gongxuanzhang** [gradle/gradle#31810]
### Current Behavior

When I run the tests in IDEA using the green arrow, I notice that the print statements in the test functions appear in the testClasses task, rather than the expected test task.

This causes my custom listener to not be triggered at the expected time.
<img width="764" alt="Image" src="https://github.com/user-attachments/assets/ece81b29-4fc8-45a5-a527-b179c924e137" />

### Expected Behavior

It should be triggered within the test task, and the listener and test cases should execute according to the lifecycle.

### Self-contained Reproducer Project

you can reproduce in https://github.com/gongxuanzhang/idea_gradle_test_issue_demo

The specific operation can be referred to in the README.

### Gradle version

8.8

## Env

- MacOs 15.0.1
- IntelliJ IDEA 2024.3.1 (Ultimate Edition)
- Gradle 8.8
- JDK 17

**Comment by jbartok** [comment]
This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project. We cannot just move the issue.

Please open such IntelliJ-related issues on the JetBrains Issue Tracker at https://youtrack.jetbrains.com/newIssue?project=IDEA.

If you believe this is not an IntelliJ IDEA issue, please update with a reproducer project that clarifies this.

***

Printing to the standard output happens from multiple threads and/or JVMs in this case, preserving order might not be possible in this case.
