### ISSUE TITLE
Dependency locking

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3181]
### Expected Behavior

A user can create a dependency lock file which contains the resolved versions of all `Configurations` when the lock was created. If a lock is present, Gradle will use these versions instead of resolving version ranges dynamically. Dependency lock files are intended to be checked into the version control repository together with the project source code.

### Current Behavior

Dynamic dependencies are resolved to whatever version matches them at the time the build is executed. This means that using dynamic dependencies makes builds inherently non-reproducible. The alternative is using explicit version numbers, which increases the maintenance overhead of the project.

### Context

Teams like to stay on the cutting edge for external libraries in a build by declaring dependencies with a dynamic version. However, a new version might still break the build, often unintended by the library author. The teams would therefor like to lock their dependencies until they explicitly decide to upgrade them within the bounds specified by their version ranges.

**Comment by dsilvasc** [comment]
@ljacomet @haoming-ahoy For consistent resolution results across configurations and subprojects, see this forum thread:
https://discuss.gradle.org/t/how-to-cross-compile-and-publish-project-for-different-versions-of-scala/3044

**Comment by izeye** [comment]
This looks resolved as the feature has already been released.

See https://docs.gradle.org/current/release-notes.html

**Comment by ljacomet** [comment]
This was delivered in [Gradle 4.8](https://docs.gradle.org/4.8/release-notes.html).
