### ISSUE TITLE
Updating to Spring Boot Kotlin DSL version 3.4.0 - Gradle wrong update

### ISSUE THREAD

**Issue by drakgoku** [gradle/gradle#31823]
### Current Behavior

There is an issue with Kotline Gradle DSL in Spring Boot, when Gradle is updated. For some reason, the "gradle-wrapper.jar" file is not updated and always points to the previous version no matter how many times you update it via commands and even if you put later versions they do not compile because the .jar is pointing to an old version. I don't know if it has to do with the minor version.

The RedHat plugin tells us the confusion (what the hell is this doing here?)

When you go from version 3.3.5 (in my case) to version 3.4.0 for some reason the gradle gets lost in the previous version 3.3.5 (and this is not able to update correctly) and this messes up the RedHat plugin.

In the end, the solution I found is to remove the "gradle-wrapper.jar" and download the "gradle-wrapper.jar" from the website or from a new spring boot project.

Can you take a look at the post?
https://github.com/redhat-developer/vscode-java/issues/3895
At first I thought it was a problem with the RedHat plugin, but it's more of a gradle issue. I mention it in the solution right there. Take your time, it's a bit strange.

### Expected Behavior

The behavior I expect is that instead of doing it manually, when you use the command ./gradlew wrapper --gradle-version x.x.x the .jar is automatically modified correctly.

The solution, as I mentioned, gives me this soft warning:
```
[Incubating] Problems report is available at: file:///E:/Projects/Project%..../..../build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.11.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
```

### Self-contained Reproducer Project

An example cannot be provided as this is a private project.

### Gradle version

3.3.5 -> 3.4.0

**Comment by jbartok** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

As stated in https://github.com/redhat-developer/vscode-java/issues/3895, we also belive that your environment is broken somehow.

There seems to be an issue with some init scripts Gradle has no control over:

> Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.11.1-bin.zip'.The specified initialization script 'C:\Users\...\AppData\Roaming\Code\User\globalStorage\redhat.java\1.36.0\config_win\org.eclipse.osgi\58\0\.cp\gradle\init\init.gradle' does not exist.Java(0)

**Comment by drakgoku** [comment]
> Your issue appears to be a question about how to use Gradle. "

Hahahahaha. Give this guy a raise. He made my day haha. Very good.
