### ISSUE TITLE
A user should be able to derive locks for a build and write to new file

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3182]
**Use case**

As a user I want to generate a file that contains the a snapshot of resolved dependency at a given time. 

**Implementation**

- A boolean build option is introduced for indicating that dependencies should be locked. The build option is only available as command line option.
- The build locks dependencies on demand independent of the executed task by determining the resolved concrete versions for requested dependencies in the build for all configurations in single and multi-project builds. 
- Gradle writes a new, build-specific file to disk, a so-called lock file, that maps the coordinates of a dynamic dependency version to a concrete version per configuration. Gradle writes the local file in a human-readable, structured format (JSON) with a comment to signal that it is auto-generated. The lock file is not intended to be edited by a user directly to avoid conflicts with other, locked versions of transitive dependencies.
- Gradle writes a SHA1 hash file alongside the JSON file so it can be used for later change comparisons.
- The user manually checks in the lock file into version control.

**Out of scope**

- This use case does not actually use the rules in an existing lock file yet. This will be addressed with a later story.
- Locking dependencies declared for `classpath` configuration in `buildscript` block.

**Test cases**

- Can (de-) activate lock file generation via build option.
- Does not write a lock file if no dependencies could be resolved.
- Can derive concrete dependency version for `.+` notation e.g. `org.gradle:gradle-core:14.+`.
- Can derive concrete dependency version for `latest.release` and `latest.snapshot` notation e.g. `org.gradle:gradle-core:latest.release`.
- Can write lock for concrete version.
- Takes into account dependency resolve rules when determining concrete dependency version.
- Uses default TTL for dynamic versions or the one defined in init or build script.
- Can write a new lock file for all resolved configurations in build.
- Only creates a single lock file in a multi-project build scenario.
- Gradle can execute subsequent builds with the dependency lock build option. Newly added or removed dependencies will be reflect in the lock file.

**Comment by eljobe** [comment]
I recommend a plain-text format so that users can easily experiment with manually overriding just one dependency in the lock file and run tests or otherwise verify that the manually-specified version behaves as they desire.

**Comment by oehme** [comment]
I'm closing this story for now, as we should first write a high-level design spec in a Google doc and agree on the behavior before breaking things down into concrete stories.

**Comment by oehme** [comment]
@bmuschko Why offer a Gradle property? I don't see how rewriting the lock on every build would be useful.

@eljobe The lock file is not meant to be edited. If the user wants to try out a new dependency, they can update it in their build file and update the lock just for that module (a follow-up story to this one). That will usually result in a lock update for many configurations, as they inherit dependencies from others. Tinkering with the locked dependencies directly would be error prone. We will make it user-readable though, so you can see differences in a commit more easily.

**Comment by bmuschko** [comment]
@oehme Was thinking about this a bit more and you are right. At the moment I cannot think of a use case we'd need this for. I'll remove it from the description.

**Comment by eljobe** [comment]
As long as a single dependency can be updated in the lock-file via Gradle commands, the user shouldn't need to edit the lock file. I had assumed, incorrectly, that the only option would be something like, "Update Dependencies" which would move all of the dependencies in the lock file to whatever the latest matching version was for their dynamic range.  If, as you are suggesting, Gradle will be able to do something like, "Update this one library to a newer version," that should be fine.
