### ISSUE TITLE
Project can consume lock file and use concrete, locked version for dependencies

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3183]
**Requirements**

- Reads lock file in dedicated project directory upon build execution
- Uses concrete version found in lock file for a "mappable" dynamic version of a dependency
- Only applies to first-level dependencies
- Applies to all configurations
- Reads locks and applies them to root project and subprojects of a build
- Dependency report indicates that a version was used from lock file
- Dependency insight report renders a descriptive reason for dependencies that use locked version

**Test Cases**

- Only reads lock file if found with specific name and in dedicated location
- Builds data structure in memory from read lock file information
- Lock for `group` and `name` uses read version instead of going through normal dependency version selection process if found in first-level dependencies of build
- Behavior works for all configurations in root project and all subprojects
- Lock for `group` and `name` that cannot be found in any project(s) is omitted
- A lock only applies to the configuration that was read from lock file
- Dependency resolution fails if locked version cannot be resolved from any of the declared repositories
- Dependency insight report renders descriptive reason indicating that locked version was selected

**Comment by eljobe** [comment]
If the lock file is only read in a task which runs during the execution phase of the build, wouldn't it be too late to influence the resolution of dependencies which are used by things like Init plugins or Gradle plugins? Maybe it would make more sense to read the lock file whenever dependency resolution happens instead of during a task.

**Comment by bmuschko** [comment]
> If the lock file is only read in a task...

I am not actually mentioning a task in this spec. I guess you are referring to the task that generates the lock file. That task would only be run upon request. The consumption side of things happens with every execution of the build (without invoking a specific task).

**Comment by oehme** [comment]
I'm closing this story for now, as we should first write a high-level design spec in a Google doc and agree on the behavior before breaking things down into concrete stories.
