### ISSUE TITLE
Add a check that build classpath is identical through the project

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#31846]
### Expected Behavior

`org.gradle.strictbuildclasspath=true` exists that enforces that no additional plugins are added in subprojects. This will ensure that everything is done through `plugins { id("foo") apply = false }` in the root project.

### Current Behavior (optional)

There is currently no way to ensure this is the case.

### Context

Not following this leads to super confusing behaviors like BuildServices crashing with bizarre error messages https://github.com/gradle/gradle/issues/17559

**Comment by ljacomet** [comment]
This issue will be closed as a duplicate of

* #1370

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.

**Comment by liutikas** [comment]
This is a request for a smaller much narrower feature than the issues was duped against.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

That's a good point, sending it for team triage.

**Comment by alllex** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
***

While this is not a comprehensive solution to the problem, we recognize this as a valid feature that can be useful to teams who want to or are required to get the most performance out of Gradle and not lose it accidentally by unsuspecting build logic changes.

Having said that, there are no plans to migrate all Gradle users to such a constraint. This means the proposed mode of operation will have to stay an opt-in feature. This comes at a cost of raising the implementation complexity of Gradle further still.

We are adding the issue to the team backlog. However, at this point, we can't promise any timeline.

**Comment by martinbonnin** [comment]
> there are no plans to migrate all Gradle users to such a constraint

@alllex can you ellaborate a bit? Is the plan to keep multiple classloaders in the long run? 

Reading #1370, I was under the impression that central classpath management was overall a desired goal, even if a very distant one. 

Have things changed? Are there valid use cases for multiple build script classpath?

**Comment by alllex** [comment]
> Reading https://github.com/gradle/gradle/issues/1370, I was under the impression that central classpath management was overall a desired goal, even if a very distant one.

Alignment of the team on the topic is still a work in progress. But even if there was an alignment, we aren't ready to commit to the central classpath management as a long-term goal. It is too far away and things can change before we get there.

Given that, we should treat the proposed flag/mode as something that might stay an opt-in forever or for a very long time, and design accordingly.

**Comment by martinbonnin** [comment]
Gotcha 👍 
I must say it's not really the answer I was looking forward to but thanks a lot for taking the time to answer and explain the situation 🙏

**Comment by liutikas** [comment]
Gradle decision can happen later, adding this feature is still valuable to many users that would like this single classpath behavior to be enforced.

**Comment by hfhbd** [comment]
AFAIK DCL does not support multiple classpaths but requires a single classpath via settings (ecosystem) plugins, so migrating to DCL could be a valid option in the future.
