### ISSUE TITLE
Copy task expand() escape newlines into `\n`

### ISSUE THREAD

**Issue by qyl27** [gradle/gradle#31850]
### Expected Behavior

Similar to #10458.  
Now we have a property to transform from `escapeBackslash` to `\n` to newline.  
I want an option in `SimpleTemplateEngine` that controls newlines (maybe more special characters) escaping behavior.  

### Context

I want to expand a multi-line text string into my template resources during the `processResource` task.  
The templates have TOML and JSON formats. Expanding to TOML, everything works well, but in JSON, I must write some extra code to escape newlines, quotes, etc.

**Comment by ljacomet** [comment]
Gradle already exposes all of the options of `SimpleTemplateEngine` which is a Groovy-provided type.
There is no option on that engine to handle what you are asking for.

Also, since you shared that you have to write extra code, could you share exactly what you are doing?

**Comment by qyl27** [comment]
oh, ok.  
I am using gradle to injecting some description and comments into some configuration files. These texts are each in a text file for designers. 
 
The files to expand have both TOML and JSON formats, so I must write 2 `processResources` to sperate replace `CR LF` or not.

**Comment by ov7a** [comment]
@qyl27 Given your answer, I assume there is nothing to be done on the Gradle side. Note that today's copy task API is pretty cluttered and it's unlikely that the requested feature would be added to it, especially since there is a workaround. However, I hope it will be redesigned in the future.
