### ISSUE TITLE
Component metadata rules should allow updating dependencies

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3186]
Follow up to #3157. 
- **The version of a dependency can be changed**
- We should keep in mind that we also want to change other properties of the dependencies in the future as well

**Comment by mkobit** [comment]
I don't know if it is entirely related, but the `extension` would also be really helpful as the current dependency management APIs don't really handle that case very well (https://discuss.gradle.org/t/configuration-and-transitive-dependency-management-by-extension/23824 for context).

**Comment by jjohannes** [comment]
@mkobit there is more follow up work planned on this topic. Eventually you will be able to adjust the artifacts of a component (which you could use to change the extension(s) only) - #3159.
