### ISSUE TITLE
PlayRun task should make working dir configurable

### ISSUE THREAD

**Issue by ymwang1984** [gradle/gradle#3188]
### Expected Behavior

[PlayRun task](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/tasks/PlayRun.java) is the task type to launch the play server for local development and hot reload. Currently this task support changing HTTP port, etc., but it does not support changing the working directory of the server process. The working directory is hard coded to be the project directory.

### Current Behavior

However, sometimes users may want the server process to run in rootDir instead of projectDir if there is a nested structure.

Furthermore, the Play server testing task, namely "testPlayBinary", actually allows users to configure the working directory. This makes many Play users confused since there is an asymmetry between local dev and testing functions provided.

In addition, for SBT (the native build tool for Play), the working directory is configurable. So Gradle should have this feature parity.

### Context

Play users in my company often have to use workarounds to bridge this working directory gap by adding symlinks, changing Play configurations, etc. But it will be much more straightforward if the working directory can be configured directly.

### Steps to Reproduce (for bugs)

N/A. We've discussed this issue with Gradle Inc offline @big-guy @bigdaz 

### Your Environment

 * Build scan URL: 

Both Mac and Linux have this issue.

**Comment by ymwang1984** [comment]
@big-guy @bigdaz 

I think it is hard-coded here:

https://github.com/gradle/gradle/blob/f5a2a8a861a1803c662bd7632d1f94689dc46968/subprojects/platform-play/src/main/java/org/gradle/play/tasks/PlayRun.java#L89

"getProject().getProjectDir()" is the hard-coded path.

**Comment by ymwang1984** [comment]
@big-guy @bigdaz 

Please let me know if the pull request makes sense. Locally it fixes the issue on some of the play projects we work on. Thanks!

**Comment by bigdaz** [comment]
Merged, thanks @ymwang1984 !

**Comment by ymwang1984** [comment]
Thanks @bigdaz
