### ISSUE TITLE
Test task does not run JUnit test with @Category and @RunWith annotations

### ISSUE THREAD

**Issue by isobretatel** [gradle/gradle#3189]
### Expected Behavior
Test task runs JUnit test with Category and RunWith annotations.

### Current Behavior
Test task does not run JUnit test with Category and RunWith annotations.

### Context
I need to filter JUnit tests by Category.
The JUnit test uses PowerMock.

### Steps to Reproduce (for bugs)
Self-contained example project:
https://github.com/isobretatel/GradleTestCaseJunitWithAnnotations

1. Run test task.
2. MyTest JUnit test is not executed.

Workaround: Add annotation PowerMockIgnore({ "org.junit.experimental.categories.Category", "FastTest" }) to JUnit class.

### Your Environment
Build scan URL:  https://gradle.com/s/faumwb7enlf7i

**Comment by mkendle** [comment]
Also ran into the same issue today. The workaround is fixing it for me for now.

**Comment by syedihuda** [comment]
Any updates here?  

I'm running into the same issue, the workaround isn't working either.  Although, I have a different setup - using Java Play Framework (2.x) and SBT for builds
