### ISSUE TITLE
Unable to use kotlin jre8 named regex groups in build script

### ISSUE THREAD

**Issue by knolleCC** [gradle/gradle#3194]
When I try to use named groups via kotlin.text.Regex in my build.gradle, I get the following exception:
"Retrieving groups by name is not supported on this platform."

Example Code:

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath("org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.3")
        }
    }

    import kotlin.text.Regex
    import kotlin.text.MatchNamedGroupCollection

    def regex = new Regex("(?<bla>.*)")
    MatchNamedGroupCollection groups = regex.matchEntire("abc").groups
    println groups.get("bla").value

It seems gradle has its own kotlin-stdlib on the classpath and this is not aware of the stdlib-jre8 from the script dependencies.

Whats worse, the same happens when I use an imported class that uses kotlin named regex groups, for example:

    buildscript {
        repositories {
            // some local repo...
        }
        dependencies {
            classpath("my.domain:kotlin-regex-test:+")
            // depends on kotlin-stblib-jre8 and thus can use named regex!
        }
    }

    my.domain.RegexTester.test()

Ah, and of course I use a JDK 8 and when I do this in an ordinary Kotlin file it works just fine.

### Expected Behavior

Named regex groups in build script and dependencies should work when kotlin-stblib-jre8 is on the classpath.

I see that gradle still wants to support java 7, so you cannot add kotlin-stblib-jre8 to the default classpath, but there should be a way to enable this.

**Comment by oehme** [comment]
@bamboo please correct me if I'm wrong, but I don't think we can fix this, as kotlin-stdlib is part of Gradle's runtime and needs to be the same for all plugins and build scripts in order to work. So this will only be fixed when we drop Java 7 support in Gradle 5.0

**Comment by bamboo** [comment]
@oehme It seems it should be possible to ship `kotlin-stdlib-jre8` alongside `kotlin-stdlib-jre7` and `kotlin-stdlib`:

> There are now separate versions of the standard library supporting the new JDK APIs added in Java 7 and 8. If you need access to the new APIs, use kotlin-stdlib-jre7 and kotlin-stdlib-jre8 maven artifacts instead of the standard kotlin-stdlib. These artifacts are tiny extensions on top of kotlin-stdlib and they bring it to your project as a transitive dependency.
https://kotlinlang.org/docs/reference/whatsnew11.html#java-8-standard-library-support 

My understanding is that as long as no code from `kotlin-stdlib-jre8` is executed, everything should work as expected under Java 7, meaning, community plugins that rely on `kotlin-stdlib` or `kotlin-stdlib-jre7` should continue to work.

I've created a corresponding issue in `kotlin-dsl`: gradle/kotlin-dsl#558

**Comment by oehme** [comment]
Interesting, thanks a lot Rodrigo! 

Closing this since this is now tracked on the Kotlin DSL repo.
