### ISSUE TITLE
plugin-publish-plugin incompatible with JDK 9

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#3195]
### Expected Behavior
plugin publishing should have Java 9 runtime support

### Current Behavior
plugin-publish-plugin fails on Java9 with javax/xml/bind/DatatypeConverter error

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
JAXB is not considered to be part of Java SE, so it is not included on the default module path since Java 9. I think we should stop using it. @gradle/cloud-services can one of you take a look at this?

**Comment by timyates** [comment]
In progress 👍

**Comment by timyates** [comment]
Fixed in version 0.9.9 of the `plugin-publish` plugin

https://plugins.gradle.org/plugin/com.gradle.plugin-publish/0.9.9
