### ISSUE TITLE
s3 maven repository always requires credentials/authentication

### ISSUE THREAD

**Issue by ernestas2k** [gradle/gradle#3198]
### Context
I have S3 bucket that's accessible via specific network (whose ip address is whitelisted in bucket policy).  The bucket is accessible via curl/browser. I couldn't find a way to access (read from) the bucket w/o authentication. 

### Current Behavior
Credentials/Authentication is required when specifying s3 backed maven repository.

```
    maven {
        name 'maven repository'
        url 's3://bucket-name.s3.amazonaws.com/'
    }
```

Results in: 

```
S3 resource should either specify AwsIamAutentication or provide some AwsCredentials.
```

### Expected Behavior
A way to access s3 bucket w/o authentication. To this moment I only have two suggestions:

1. Accessing w/o authentication when no credentials/authentication is specified:
```
    maven {
        name 'maven repository'
        url 's3://bucket-name.s3.amazonaws.com/'
    }
```

2. Accessing with new authentication type, let's call it 'None':
```
        maven {
            name 'maven repository'
            url 's3://bucket-name.s3.amazonaws.com/'
            authentication(None)
        }
```

PS: any simple workaround (that requires no extra dependencies) would help me.

**Comment by mark-vieira** [comment]
> The bucket is accessible via curl/browser.

Then you should be using `http` as the protocol. If you've enabled static web hosting (or something similar) to allow anonymous access to the bucket then it should not be accessed via the AWS API but rather as a regular HTTP repository.

**Comment by ernestas2k** [comment]
I haven't enabled static content serving, also responses are BucketList xml. It's early morning, and I may be missing something, but switching to http:// instantly solved the issue.

Thanks, Mark!

**Comment by mark-vieira** [comment]
Closing this issue since this is just a configuration issue. There is effectively no such thing as anonymous access via the `s3` protocol. Talking to the S3 API (or any AWS API for that matter) requires credentials of some sort. It wouldn't make sense for us to not require a credentials provider here, although there are likely other credentials providers we don't currently support.

**Comment by venkatesh028** [comment]
@mark-vieira Do we need credentials for accessing the  bucket which have public read
