### ISSUE TITLE
JUnitTest won't run if you add an ant property

### ISSUE THREAD

**Issue by MrKuip** [gradle/gradle#3201]
If I add 1 antproperty it will another antproperty with the name 'size' and it's value is an Integer

### Expected Behavior
I expect one antproperty to be added.

### Current Behavior
I get an extra antproperty with the name 'size' that has a Integer value.

### Context
We are converting our ant build system to gradle. 
In our current build.xml we run junit tests.
When running the test I got an Exception: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
I spend a couple of hours debugging and found out that JUnitTask copies the ant properties (ObservableMap) into an object of class java.util.Properties.
It then tries to write those Properties to disk and then I get the exception.
It turns out to be that when writing to disk you can ONLY have values that are Strings.
In this case the extra property 'size' is an Integer. And there is the ClassCastException.

### Steps to Reproduce (for bugs)
```
task bug {
  doLast {
    int sizeBefore;
    int sizeAfter;

    sizeBefore = ant.properties.size();
    println 'The property \'size\' before adding a TEST property is: ' + ant.properties['size'];

    ant.properties['TEST'] = 'test';

    println 'The property \'size\' after adding a TEST property is: ' + ant.properties['size'];
    sizeAfter = ant.properties.size();

    println 'The expected size of properties after adding 1 property is ' + sizeBefore;
    println 'But the size is now ' + sizeAfter;
  }
}
```

**Comment by bmuschko** [comment]
Could you please provide a minimalistic sample project that reproduces the issue?

**Comment by MrKuip** [comment]
The minimalistic sample project is the code that I already provided.
Isn't that enough?
It prints out what is wrong if you run the task

**Comment by bmuschko** [comment]
> In our current build.xml we run junit tests.
When running the test I got an Exception: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

I am asking for a sample project because you explicitly mentioned JUnit tests and that the issue surfaces if the tests are run. Is this relevant? If it isn't then I think we can remove that from the description.

**Comment by MrKuip** [comment]
JUnit test is relevant. I just debugged and analyzed it already and it boils down to the problem described in the example.

But I will create a sample project.
I do not have much time now. I will take some time

**Comment by MrKuip** [comment]
[SampleProject3201.zip](https://github.com/gradle/gradle/files/1501362/SampleProject3201.zip)

I've attached the minimalistic sample project. 

If you run "gradle runTest" you get the following exception:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

If you run "ant runTest" you do not get the Exception but the expected output (1 test will fail)

The cause of the ClassCastException is the following line in build.gradle:
  ant.properties['TEST'] = 'test';
If you comment this line out the 'gradle runTest' will also have the expected output.

The problem is that that line will add another property with the name "size" that is an Integer.

**Comment by MrKuip** [comment]
I'm stuck here. I cannot find a workaround for this issue.

I debugged a little bit further and the problem is in ./api/internal/project/DefaultAntBuilder.java.
I found this code:

    public Map<String, Object> getProperties() {
        ObservableMap map = new ObservableMap(getProject().getProperties());
        map.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent event) {
                doSetProperty(event.getPropertyName(), event.getNewValue());
            }
        });

The problem is that the event is fired when an item is ADDED, REMOVED, UPDATED,CLEARED,MULTI...
But also when the bound property SIZE is changed.
This is not a property IN the map but a property OF the map. So that property doesn't belong in 
the ant.properties.

A propertychange of the SIZE is a PropertyChangeEvent. The othere events are of the class PropertyEvent.
So a simple instancecheck will resolve my problems. But a good solution must filter out the
unwanted PropertyChangeEvents.

**Comment by MrKuip** [comment]
If anyone experiences this problem also:
I found a workaround. It is very simple. ;-)

Just clear the size property after setting an ant property. like this:

      ant.properties['TEST'] = 'test';
      ant.properties['size'] = ""

**Comment by MrKuip** [comment]
The same construction is used in getReferences() and should also be fixed!

    public Map<String, Object> getReferences() {
        ObservableMap map = new ObservableMap(getProject().getReferences());
        map.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent event) {
                getProject().addReference(event.getPropertyName(), event.getNewValue());
            }
        });
