### ISSUE TITLE
Test class execution events fired for TestNG tests should include correct summary of the results of the test class

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#3207]
Gradle's `Test` task fires events at the completion of the tests for a test class that summarize the result for the test class. This summary is represented by the `TestResult` and includes details such as a result (success, failure, skipped), the number of tests, the failures and so on.

For JUnit tests, this summary includes the expected values. However, for TestNG tests, this summary is always empty, with a result of 'success', 0 tests, no failures, and so on.

These events are fired through public API, either to a build logic-supplied `TestExecutionListener` or closures passed to the various methods on `Test` such as `afterSuite()`.

### Expected Behavior

The test class summary includes the correct details for all tests.

### Current Behavior

The test class summary includes the correct details for JUnit, and no details for TestNG.

**Comment by blindpirate** [comment]
Recently I noticed this issue, which seems not to happen. I tested with `samples/testing/testng/java-passing` and `build.gradle`:

```
test {
   afterSuite { descriptor, result ->
       println descriptor
       println "${result.testCount}, ${result.failedTestCount}, ${result.skippedTestCount}"
   }
}
```

And the result is:

```
Test suite 'Gradle test'
4, 0, 0
Test suite 'Gradle suite'
4, 0, 0
Gradle Test Executor 5
4, 0, 0
Gradle Test Run :test
4, 0, 0
```

I didn't observe this issue with `4.2` and `4.5` so I'll close it. Please feel free to reopen if this issue still exist.
