### ISSUE TITLE
Lack of non-serialisable transport for parallel task work

### ISSUE THREAD

**Issue by JaciBrunning** [gradle/gradle#3226]
### Expected Behavior
There should be some method, Workers or otherwise, that allows passing of non-serialisable data (i.e. any object) without isolation, allowing tasks to run in parallel while still being able to pass other data and objects.

### Current Behavior
As far as I'm aware, only Workers are the current method to allow tasks to execute in parallel until depended on. This is great, but only works for serialisable data. In cases where non-serialisable objects should be transferred, it isn't possible to have the task run in parallel to tasks that do not depend on it.

### Context
In my use case, I have a deployment plugin that uses SSH/SFTP (through Jsch) to transfer files to a remote target after being built with the gradle native platform. The goal is to have a 'discovery' task attempt multiple hostnames to find the target, whilst simultaneously building the native binaries until a connection is achieved. 

In order for this to be done, the discovery task must implement Workers. However, I cannot 'reuse' the open SSH session in the task with other, dependent tasks, as all data passed to Workers must be serialisable. A method I've used to overcome this is to store objects in a map and pass the map key to the Worker in Isolation Mode "none", but this is far from safe or practical.

I understand the purpose of Workers is to _allow_ this method of isolation, and reduce the problems associated with accessing data from multiple threads, however I think there should be a companion system in place to allow parallelizable tasks without sacrificing the ability to work with any old java object, forgoing the isolation, and leaving the race conditions and access rights to the plugin author.

### Steps to Reproduce (for bugs)

See above.

### Your Environment
N/A (feature request)

**Comment by oehme** [comment]
We shouldn't forgo isolation, since that is the whole point of the worker API and it would be way too easy for users to shoot themselves in the foot. I think the use case you mentioned could be solved in a different way: 

The discovery task has an output where it stores the host that did work and the other tasks take that as an input and connect to it. Right now this would have to be modeled as a file, as there is now way to model non-file outputs.
