### ISSUE TITLE
Clarify `-b`/`-c`/`-p` usage

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#3227]
Currently, there're three command line options whose behavior are confusing:

- `-b` specify the build file
- `-c` specify the settings file
- `-p` specify the project directory

For example, in the [documentation](https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:selecting_build):

> You can use the `-b` option to select another build file. If you use `-b` option then settings.gradle file is not used. 

What's more, the [implementation](https://github.com/gradle/gradle/blob/9aaba9b430a2f7abb5e64c949346a665153b6811/subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoader.java#L46) is also confusing/buggy.

We should clarify what's gonna happen if these options are applied (combinedly). Or, if they're useless, deprecate/remove them.

**Comment by oehme** [comment]
I think fixing them to match their current documentation would be a good first step, e.g. fixing #3100

**Comment by bmuschko** [comment]
@blindpirate The documentation has been changed recently for those option: https://docs.gradle.org/current/userguide/command_line_interface.html#_environment_options. Does this improve the situation or is additional work needed?

**Comment by oehme** [comment]
The goal of this ticket is to evaluate:

- which of these options we want to keep at all
- what their exact contract should be (e.g. the current behavior of `-b` is highly confusing and not mentioned in the new documentation)
- create issues to change Gradle to be in line with those decisions
