### ISSUE TITLE
Polish up deprecation message mechanism

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#3228]
Currently, our deprecation message mechanism is not perfect:

- The warning is only outputted in console, we'll not get the warning when:
  - running in embedded mode
  - setting options through gradle.properties
  - settings options programatically
- There're several duplicates of deprecation message, e.g [here](https://github.com/gradle/gradle/blob/614bd5896a5bbc8205519c8d37dfc69b0ad00b9c/subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java#L93) and [here](https://github.com/gradle/gradle/blob/614bd5896a5bbc8205519c8d37dfc69b0ad00b9c/subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java#L171). Since they're similar wording, we should collect and unify them to make it more easy to maintain.
- There's lots of hardcoded `removed in Gradle 5.0`, which could be refined.

@bmuschko @oehme Anything complementary? 

Previously, when running `gradle --help`, a user would see:

```
...
-q, --quiet               Log errors only.
--recompile-scripts       Force build script recompiling. [deprecated - Support for --recompile-scripts was deprecated and is scheduled to be removed in Gradle 5.0.]
--refresh-dependencies    Refresh the state of dependencies.
...
```
And when running `gradle <task> --recompile-scripts`, a user would see:

```
$ ./gradlew help --recompile-scripts
The --recompile-scripts option is deprecated - Support for --recompile-scripts was deprecated and is scheduled to be removed in Gradle 5.0.
...
```

After this change, when running `gradle --help`, a user would see:

```
-q, --quiet               Log errors only.
--recompile-scripts       Force build script recompiling. [deprecated - has been deprecated and is scheduled to be removed in Gradle 5.0. ]
--refresh-dependencies    Refresh the state of dependencies.
```

when running `gradle <task> --recompile-scripts`:

```
$ subprojects/build-option/build/integ\ test/bin/gradle --recompile-scripts help
--recompile-scripts has been deprecated and is scheduled to be removed in Gradle 5.0.
```

**Comment by oehme** [comment]
I'd recommend splitting out the logic that constructs messages from the deprecation logger into its own class. It seems like having a `DeprecationWarning` class would be a good move. Right now we have a bunch of hardcoded "Gradle 5.0" messages, when really the version number should be automatically inferred from the current major release.

**Comment by bmuschko** [comment]
Can we first define how this change would surface to the user? It's not fully clear to me based on the description.

For example I am not necessarily a fan of making `gradle -?` harder to read by adding information on when the option will be removed. What I'd like to see here is: When I as user do x then I see the following.

**Comment by blindpirate** [comment]
@bmuschko Sure, added above. Actually there's no big change.

**Comment by bmuschko** [comment]
Thanks for clarifying. Instead of adding a deprecation message that indicates the version we want to remove the feature I'd rather want to know why it has been deprecated or what the replacement for it should be. For that reason I am advocating for not adding it to the output of `gradle -?`.

I also think this reads a bit weird: 

`deprecated - has been deprecated and is scheduled to be removed in Gradle 5.0`

This should be good enough:

 `deprecated - scheduled to be removed in Gradle 5.0`
