### ISSUE TITLE
Eclipse plugin ignores force on dependency with relocation

### ISSUE THREAD

**Issue by gradlifier** [gradle/gradle#3229]
### Expected Behavior
In our build.gradle we reference a compile dependency, which has a relocation in its pom.xml file (e.g. see http://central.maven.org/maven2/com/lowagie/itext/4.2.0/itext-4.2.0.pom). Because of licensing issues we have to use this exact version of the itext dependency and we do not want to follow the relocation. 
For this reason we added the following block to our build.gradle file: 

`configurations.all {`
`	resolutionStrategy {`
`		force group: 'com.lowagie', name: 'itext', version: '4.2.0'`
`		all*.exclude group: 'com.itextpdf', module: 'itextpdf'`
`	}`
`}`

The expected output of `gradle dependencies` is now: 

> compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
\--- com.lowagie:itext:4.2.0

> compileClasspath - Compile classpath for source set 'main'.
\--- com.lowagie:itext:4.2.0
[...]

This works fine with all Gradle versions. The task `gradle eclipse` generates the .classpath file for Eclipse. The result for Gradle versions 2.14, 3.5 and 4.1 is (expected and correct): 

`<classpathentry path="C:/Daten-lokal/Benutzer/ml79/gradle/caches/modules-2/files-2.1/com.lowagie/itext/4.2.0/77e08389e3fa7b0212b67702ba6e4dbbbff68ae5/itext-4.2.0.jar" kind="lib" sourcepath="C:/Daten-lokal/Benutzer/ml79/gradle/caches/modules-2/files-2.1/com.lowagie/itext/4.2.0/e975b1e422df52672e57ca3da650ea27038c266/itext-4.2.0-sources.jar"/>`

With Gradle versions 4.2 and 4.2.1 the itext dependency is missing completely in the .classpath file, what is wrong. I found no way to get itext 4.2.0 into the .classpath file, neither with dependency substitution, nor with any force and excude combinations.  

We are not able to use versions 4.2 and 4.2.1 because of this issue. It makes us too much effort to manipulate the .classpath file for round about one hundred projects manually. 

Our build.gradle file: 

apply plugin: 'java'
apply plugin: 'eclipse'

allprojects {
	repositories {
		mavenCentral()
	}
}

dependencies {
	compile group: 'com.lowagie', name: 'itext', version: '4.2.0'
}

configurations.all {
	resolutionStrategy {
		force group: 'com.lowagie', name: 'itext', version: '4.2.0'
		all*.exclude group: 'com.itextpdf', module: 'itextpdf'
	}
}

We are using Gradle Wrapper for execution.

**Comment by oehme** [comment]
Can you please attach a reproducible project as a zip?

**Comment by gradlifier** [comment]
Eclipse project to reproduce the issue.
[lib-test.zip](https://github.com/gradle/gradle/files/1393937/lib-test.zip)

**Comment by blindpirate** [comment]
Potentially related to #2166 . I'll take a look.

**Comment by blindpirate** [comment]
@gradlifier Here's what's happening.

In Maven, an artifact can be relocated via `relocation` tags in `pom.xml` (see [here](https://maven.apache.org/guides/mini/guide-relocation.html)). Before Gradle 4.2, if `A` is relocated to `B`, `A.jar` and `B.jar` will both be downloaded, which causes potential issues (e.g. #1789 ), so we changed this behaviour in `4.2` and avoid downloading `A.jar` in this situation. 

In most cases it's correct, but your case looks slightly different. In my understanding, if `A` is relocated to `B`, they're basically the same artifact (e.g [org.apache.commons:commons-io:1.3.2](http://repo1.maven.org/maven2/org/apache/commons/commons-io/1.3.2/commons-io-1.3.2.jar) and [commons-io:commons-io:1.3.2](http://repo1.maven.org/maven2/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar)). However, your `com.lowagie:itext:4.2.0` is relocated to `com.itextpdf:itextpdf:5.5.6`, but they're totally different. Could you explain a bit why is it?

IMHO, `relocation` element shouldn't be used here and what Gradle 4.2 does is the right thing. @bigdaz , WDYT?

```
$ tree -d itext-4.2.0
itext-4.2.0
├── META-INF
│   └── maven
│       └── com.lowagie
│           └── itext
└── com
    └── lowagie
        ├── rups
        │   ├── controller
        │   ├── io
        │   │   └── filters
        │   ├── model
        │   └── view
        │       ├── icons
        │       ├── itext
        │       │   └── treenodes
        │       └── models
        ├── text
        │   ├── error_messages
        │   ├── exceptions
        │   ├── factories
        │   ├── html
        │   │   └── simpleparser
        │   ├── pdf
        │   │   ├── codec
        │   │   │   └── wmf
        │   │   ├── collection
        │   │   ├── crypto
        │   │   ├── draw
        │   │   ├── events
        │   │   ├── fonts
        │   │   │   └── cmaps
        │   │   ├── hyphenation
        │   │   ├── interfaces
        │   │   ├── internal
        │   │   └── parser
        │   ├── rtf
        │   │   ├── direct
        │   │   ├── document
        │   │   │   └── output
        │   │   ├── field
        │   │   ├── graphic
        │   │   ├── headerfooter
        │   │   ├── list
        │   │   ├── parser
        │   │   │   ├── ctrlwords
        │   │   │   ├── destinations
        │   │   │   ├── enumerations
        │   │   │   ├── exceptions
        │   │   │   └── properties
        │   │   ├── style
        │   │   ├── table
        │   │   └── text
        │   └── xml
        │       ├── simpleparser
        │       └── xmp
        ├── toolbox
        │   ├── arguments
        │   │   └── filters
        │   ├── plugins
        │   └── swing
        └── tools
$ tree -d itextpdf-5.5.6
itextpdf-5.5.6
├── META-INF
│   └── maven
│       └── com.itextpdf
│           └── itextpdf
└── com
    └── itextpdf
        ├── awt
        │   └── geom
        │       ├── gl
        │       └── misc
        ├── testutils
        ├── text
        │   ├── api
        │   ├── error_messages
        │   ├── exceptions
        │   ├── factories
        │   ├── html
        │   │   └── simpleparser
        │   ├── io
        │   ├── l10n
        │   │   └── error
        │   ├── log
        │   ├── pdf
        │   │   ├── codec
        │   │   │   └── wmf
        │   │   ├── collection
        │   │   ├── crypto
        │   │   ├── draw
        │   │   ├── events
        │   │   ├── fonts
        │   │   │   ├── cmaps
        │   │   │   └── otf
        │   │   ├── hyphenation
        │   │   │   └── hyph
        │   │   ├── interfaces
        │   │   ├── internal
        │   │   ├── languages
        │   │   ├── parser
        │   │   │   └── clipper
        │   │   ├── qrcode
        │   │   └── security
        │   └── xml
        │       ├── simpleparser
        │       │   └── handler
        │       └── xmp
        └── xmp
            ├── impl
            │   └── xpath
            ├── options
            └── properties
```

**Comment by bigdaz** [comment]
@blindpirate I agree that we should only be including the artifacts and dependencies for the target of the relocation. There's no way to tell Gradle (or Maven I think) to ignore the relocation, and the issue has nothing to do with the use of `force` in the build.

As far as I'm concerned `com.itext:itext:4.2.0` doesn't exist as a real module: you'll see that the POM file has no dependencies in it, and I have no idea why there is a `itext-4.2.0.jar` file present in the repository.

Including both `itext-4.2.0.jar` and `itext-pdf-5.5.6.jar` in the resolution was a bug in earlier versions of Gradle. Now we (correctly) only include `itext-pdf-5.5.6.jar`, and the user is explicitly excluding this jar.

Our handling of relocation is pretty broken in general. Instead of adding a dependency on the relocated module and then ignoring artifacts of the original module, we should probably treat a relocation like a _dependency substitution_, replacing the original dependency with the relocated one.

So instead of:
```
+--- com.lowagie:itext:4.2.0
|    +--- com.itextpdf:itextpdf:5.5.6
```

we should have:
```
+--- com.lowagie:itext:4.2.0 -> com.itextpdf:itextpdf:5.5.6 (POM relocation)
```

**Comment by bigdaz** [comment]
It _might_ be possible to use a dependency like `com.lowagie:itext:4.2.0@jar` to get the artifact from the original location.

**Comment by gradlifier** [comment]
Hi together, many thanks for your help an the workaround with `com.lowagie:itext:4.2.0@jar`. That seems to work well for us now! 
And yes, the version 4.2.0 of this artifact seems not to be an official one as stated in   https://stackoverflow.com/questions/37740725/how-to-migrate-com-lowagie-itext-form-2-1-7-to-4-2-0
So in a longer term we will switch to a newer version or a fork of iText. 

Regarding the relocation you may be right. It does not make sense to "suppress" relocation, so I am closing the issue now.
