### ISSUE TITLE
Investigate improvements for handling metadata and its modification in AbstractMutableModuleComponentResolveMetadata and friends

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3241]
For #3076 and related stories, we need to make more metadata mutable in some form. [`AbstractMutableModuleComponentResolveMetadata`](https://github.com/gradle/gradle/blob/95022e5492537fbdf632ebaca0358edd1408769b/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/AbstractMutableModuleComponentResolveMetadata.java#L46), together with Mvn and Ivy specific subclasses, is the place where metadata is currently stored and manipulated. The current approach for storing metadata in these classes is:

- **Store the data in the _original_ format.** Which means there is no unified format but different implementations store data differently. For example, the Ivy metadata stores a list of `Artifact`s with a links to there configurations (`Artifacts.getConfigurations()`) while the Mvn implementation constructs this information on the fly (since it is less flexible for Mvn).
When the resolution engine requires the data in a unified format, the data is translated into a unified view based on configurations in `populateConfigurationsFromDescriptor()`.

Issues with this approach are:
- Most important, in the context of #3076, is that making metadata mutable is hard. Either we need specific solution for different metadata sources (Ivy, Mvn, Gradle's own format) - we do not want this. Or we need to do specific data translation for each format we use to store metadata.
- Always when we add some new metadata, individual handling of the data needs to be implemented in different places. For example the recently added `variants` can currently only be added to Mvn metadata and later needs to be integrated wit other metadata as done [here](https://github.com/gradle/gradle/blob/d8672835bf3acdac65830230f894381df29fdc9c/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/DefaultMavenModuleResolveMetadata.java#L132-L141) for the dependencies.

This issue is about turning this around by **storing the data in a unified format** the moment a `MutableModuleComponentResolveMetadata` is created. The format would be oriented at what the resolution engine needs (_(Configurations ->) Variant -> Dependencies+Artifacts+X_). (we might drop configurations later to represent everything through variants).

Based on this, we can then allow more metadata to be manipulated in a unified way. And build public metadata rule APIs on top of that.

**Comment by jjohannes** [comment]
@adammurdoch what are your thoughts on this? Do you already have similar or different ideas about how to proceed here?

**Comment by oehme** [comment]
Let's postpone this, based on our discussion last week.
