### ISSUE TITLE
Retry on failed gradle wrapper download

### ISSUE THREAD

**Issue by cdancy** [gradle/gradle#3243]
### Expected Behavior
With the correct properties/config/whatever in place downloading the gradle wrapper would be retried up to some configurable amount of times.

### Current Behavior
Download of gradle wrapper fails should the network become overly congested.

### Context
In cases where there is lots of network load/congestion the gradle wrapper fails to download correctly in our CI environment. We'd like to have some configurable options in place to retry X number of times, preferably with waits in between, to make this process more resilient.

Also commented [here](https://discuss.gradle.org/t/making-the-wrapper-more-resilient-to-corrupted-downloads/22066/11) though not sure how active that thread/forum is anymore so cross posting here.

### Steps to Reproduce (for bugs)
It's not entirely reproducible per se just fails to download due to load and/or network congestion.

### Your Environment
cloudbees jenkins but has happened from various developers desktops as well when the local network is under heavy load.

### Possibly Related
https://github.com/gradle/gradle/issues/2598

**Comment by bmuschko** [comment]
I think this feature request should apply to dependency downloads in general not just the Wrapper. For the Wrapper the issue might be more pronounced as the download size is larger than other library dependencies.

**Comment by cdancy** [comment]
@bmuschko I was thinking as much. Is this work a dev like myself should even attempt to take on or something better suited for gradle engineers?

**Comment by bmuschko** [comment]
@cdancy I don't think we'll tackle the topic anytime soon. There's nothing speaking against this feature being picked up by the community. If you are planning to do so, then I'd suggest that you start by writing down the use cases, an implementation approach and test cases in this issue. We can discuss from there.

**Comment by bmuschko** [comment]
@cdancy Were you planning to work on this? If you don't then I suggest we close the issue for now.

**Comment by cdancy** [comment]
@bmuschko lets close this as I believe the new internal http properties should solve the issue for us at least for now.

**Comment by cdancy** [comment]
@yole take a look at [THIS](https://github.com/gradle/gradle/pull/3371/files) pull request to get a better understanding of how this works which is, IMO, just a band aid of sorts. [THIS](https://github.com/gradle/gradle/issues/4629) thread goes over things in more detail.
