### ISSUE TITLE
Task executed within nested builds do not add to "actionable tasks" total

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#3244]
### Expected Behavior

Build summary summarizes all builds that run from a single Gradle invocation.

### Current Behavior

Build summary only shows a summary of tasks that executed in the outermost build.

### Context

We currently disable collecting task statistics from nested builds:
https://github.com/gradle/gradle/blob/2f705c71ab53f8b1d225a63c10882ae571bf7cc1/subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/statistics/TaskExecutionStatisticsEventAdapter.java#L38-L41

### Steps to Reproduce (for bugs)

Using https://github.com/gradle/native-samples/tree/master/cpp/composite-build

Run `./gradlew --console=plain build`.  You'll see:
> :dependDebugCpp
> :transitive-dependencies:greeting:dependDebugCpp
> :math:dependDebugCpp
> :transitive-dependencies:hello:dependDebugCpp
> :math:compileDebugCpp
> :transitive-dependencies:greeting:compileDebugCpp
> :compileDebugCpp
> :transitive-dependencies:hello:compileDebugCpp
> :math:linkDebug
> :check UP-TO-DATE
> :transitive-dependencies:greeting:linkDebug
> :transitive-dependencies:hello:linkDebug
> :linkDebug
> :installDebug
> :assemble
> :build
> 
> BUILD SUCCESSFUL in 9s
> 4 actionable tasks: 4 executed

We've obviously tried to run more than 4 actionable tasks, but the build summary doesn't show that.

### Your Environment

This happens in all environments.

**Comment by ldaley** [comment]
This is now an issue for build scans, so I would like to us to reconsider priority. Build scans provide similar types of task statistics, that do consider included builds _and buildSrc_. 

We should change this end of build summary to consider _all_ tasks that were run.
