### ISSUE TITLE
`withDependency` mutations should be available to downstream consumers

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3247]
When the `DependencySet` is mutated via `Configuration.withDependency`, these modifications should be visible to all consumers of that dependency set. This includes:

- When the configuration is consumed as project dependency
- When the configuration is consumed as a substituted project dependency in a composite build
- When the dependencies are published to an `ivy.xml` file with the `ivy-publish` plugin
- When the dependencies are published to a `pom` file using the `maven-publish` plugin

This story is closely related to #812 and #3238

This story should include documentation and release notes for `withDependencies`.

**Comment by bigdaz** [comment]
Test coverage added

**Comment by pioterj** [comment]
@bigdaz What about this part?

> This story should include documentation and release notes for `withDependencies`?
