### ISSUE TITLE
Expose fewer internal services from the testing tasks

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#3258]
Part of the native work for supporting XCTest was to reuse the JVM testing infrastructure. Most of the common logic was extracted to `AbstractTestTask`. It requires test framework integration to extends `AbstractTestTask` and implement `createTestExecutionSpec` and `createTestExecuter`.

### Expected Behavior
By extracting the logic into a service, we can simplify the requirement for test framework integration and remove internal type leaked through protected method. The base class `AbstractTestTask` should only provide generic APIs commons between test frameworks.

### Current Behavior
New test framework integration relies on extending the base class as opposed to composing.

**Comment by adammurdoch** [comment]
I think a better title for this issue would be something like 'expose fewer internal services from the testing tasks'. Using a service would be a way to solve this.
