### ISSUE TITLE
The use of Project.property(Class) or ProviderFactory.property(Class) should not render a deprecation warning

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3262]
### Expected Behavior

The deprecation warning will be removed from `Project.property(Class)` and `ProviderFactory.property(Class)` to ease the main for plugin developers and consumers of the plugin.

### Current Behavior

Plugins that create a `Provider` instance through `Project.property(Class)` or `ProviderFactory.property(Class)` automatically render a deprecation warning when used by builds with Gradle 4.3. The build script user cannot really fix the issue. The plugin would have to be changed to use the replacement API `ObjectFactory.property(Class)`. Switching to the new API would make the plugin incompatible to Gradle version < 4.3 as the returned type of the method call is different (`PropertyType` vs. `Property`).

### Context

[An incubating API was deprecated](https://github.com/gradle/gradle/commit/9ab5b27736026316cf1a84932dc227cab25ac611) early on in a major release cycle. The returned type of the replacement method is incompatible making it impossible for plugin developers to release a version that supports running on a all minor versions of Gradle for a major release.

**Comment by adammurdoch** [comment]
This shouldn't be closed until the release branch that contains this change has been merged into master, and the changes ignored.

The warning should not be removed from master, but it will be easy for someone to unintentionally remove the warning by merging the release branch into master.

**Comment by bmuschko** [comment]
@adammurdoch Good point. Done!
