### ISSUE TITLE
Processing of the patch file after calling Gradle from the patch file is not executed

### ISSUE THREAD

**Issue by starmineouji** [gradle/gradle#3266]
I am Japanese. Because I am using google translation, there may be strange places, but please forgive me

### Expected Behavior
echo Build start
gradle build
echo Build finished
If there is processing called, all commands are normally read

### Current Behavior
<img width="960" alt="default" src="https://user-images.githubusercontent.com/28946729/31846784-5b24a022-b64b-11e7-93cb-00e4654e1314.PNG">
However, when "gradle build" is executed, subsequent "echo Build finished" will not be executed
But in ShellScript(.sh) this bug does not occur.

### Context
I'm trying to build a program using Gradle as a tool for creating additional elements of a certain game now.
But due to this bug we have to use "Git-bash" which allows you to build ShellScript in Windows environment
However, in that case, the execution log can not be seen in Java, and the disadvantage is too much, such as the Git window getting in the way.

### Steps to Reproduce (for bugs)
Code written in the Expected Behavior or https://github.com/starmineouji/SpigotIDE/blob/master/SpigotIDE-for_IDE/build.bat (the code I wanted to execute)

### Your Environment
Gradle 4.2.1 Windows 10

 * Build scan URL:

**Comment by blindpirate** [comment]
Try `call gradle build`. When you're running `gradle` in bat files, you're actually calling `<gradle distribution>/bin/gradle.bat`, which needs a `call` command.

See https://stackoverflow.com/questions/14731877/a-bat-file-call-or-not-to-call-that-is-the for more details.
