### ISSUE TITLE
buildNeeded/buildDependents does not work with Java Library plugin

### ISSUE THREAD

**Issue by jonathan-yan** [gradle/gradle#3269]
### Expected Behavior

Running the `buildNeeded`/`buildDependents` on a project in a multi-project build should run tests for all projects that it depends on/depends on it.

### Current Behavior

Only tests for the current project are run.

### Context

I am trying to start using the Java Library plugin in a multi-project build.

### Steps to Reproduce (for bugs)

* Example project: [example-buildneeded-issue.zip](https://github.com/gradle/gradle/files/1407106/example-buildneeded-issue.zip)
* Run `./gradlew --console=plain clean :applications:application-1:buildNeeded` (expected it to fail as there is a deliberately failing test in the `library-1` project but it passes as the tests for the latter are not run)

### Your Environment

* macOS High Sierra 10.13
* Oracle JDK 8u152

**Comment by jonathan-yan** [comment]
Note that if the Java Library plugin is to be adopted, this is quite a serious bug as users will most likely not realise that the `buildNeeded`/`buildDependents` task is not exercising the tests of dependencies/dependants as it should do.

**Comment by oehme** [comment]
This was a simple oversight and is fixed by https://github.com/gradle/gradle/pull/4964
