### ISSUE TITLE
Plugins repo returns 302's on non-existing artifacts

### ISSUE THREAD

**Issue by cjhkramer** [gradle/gradle#3276]
### Expected Behavior
curl -v https://plugins.gradle.org/m2/org/mockito/mockito-all/maven-metadata.xml
Should return a 404

### Current Behavior
curl -v https://plugins.gradle.org/m2/org/mockito/mockito-all/maven-metadata.xml
Returns a 302, redirects to a directory.

> HTTP/1.1 302 Found
> Date: Tue, 24 Oct 2017 13:20:55 GMT
> Transfer-Encoding: chunked
> Connection: keep-alive
> Location: https://plugins.gradle.org/m2/org/mockito/mockito-all/maven-metadata.xml/
> Via: 1.1 vegur
> Server: cloudflare-nginx

### Context
We mirror this repo in our Artifactory. If it returns a 302 like this, Artifactory thinks this is a directory, hence our builds fail.

### Steps to Reproduce (for bugs)
See the curl command.

### Your Environment
Running Artifactory Pro, that has a vrepo that we use for all our remote dependencies. The vrepo connects through a proxy through the internet.

**Comment by islandsvinur** [comment]
I'm observing the same problem when using dynamic versions for plugins:

```
> Could not resolve all dependencies for configuration ':compile'.
   > A problem occurred configuring project ':xxx'.
      > Could not resolve all files for configuration ':xxx:classpath'.
         > Could not find any matches for org.ajoberstar:grgit:[2.0.0,) as no versions of org.ajoberstar:grgit are available.
           Searched in the following locations:
               https://plugins.gradle.org/m2/org/ajoberstar/grgit/maven-metadata.xml
           Required by:
               project :xxx > org.ajoberstar:gradle-git-publish:0.3.1
```

**Comment by bamboo** [comment]
Thanks for the report, we'll look into it.

**Comment by JLLeitschuh** [comment]
Our company is hitting this too:
```bash
curl -v https://plugins.gradle.org/m2/org/glassfish/javax.el/maven-metadata.xml
```
Response:
```
*   Trying 104.16.174.166...
* TCP_NODELAY set
* Connected to plugins.gradle.org (104.16.174.166) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: ssl473435.cloudflaressl.com
* Server certificate: COMODO ECC Domain Validation Secure Server CA 2
* Server certificate: COMODO ECC Certification Authority
> GET /m2/org/glassfish/javax.el/maven-metadata.xml HTTP/1.1
> Host: plugins.gradle.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Tue, 24 Oct 2017 15:04:45 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d9102484f45ccae7f11edcae47696e9581508857485; expires=Wed, 24-Oct-18 15:04:45 GMT; path=/; domain=.gradle.org; HttpOnly
< Location: https://plugins.gradle.org/m2/org/glassfish/javax.el/maven-metadata.xml/
< Via: 1.1 vegur
< Server: cloudflare-nginx
< CF-RAY: 3b2dd4924f6f5a3e-BOS
< 
* Connection #0 to host plugins.gradle.org left intact
```

Note the trailing slash which seems incorrect to me:
```
< Location: https://plugins.gradle.org/m2/org/glassfish/javax.el/maven-metadata.xml/
```

**Comment by bamboo** [comment]
Thanks for the reports. We identified the defect and have a fix currently going through review.

**Comment by pvdissel** [comment]
@bamboo How's the review going?

**Comment by bamboo** [comment]
Hi @pvdissel, we are still testing the changes internally, in the meantime Portal behavior was restored to the previous version (Bintray redirect):
```
$ curl -v https://plugins.gradle.org/m2/org/mockito/mockito-all/maven-metadata.xml
...
< HTTP/1.1 303 See Other
< Date: Thu, 26 Oct 2017 12:14:43 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d9f77fa15904619ad53ffb17bff35f3541509020082; expires=Fri, 26-Oct-18 12:14:42 GMT; path=/; domain=.gradle.org; HttpOnly
< Location: https://jcenter.bintray.com/org/mockito/mockito-all/maven-metadata.xml
< Via: 1.1 vegur
< Server: cloudflare-nginx
< CF-RAY: 3b3d563abe111d12-EZE
<
```

**Comment by pvdissel** [comment]
ah, thanks for the update

**Comment by timyates** [comment]
The changes are live now.

As before, the Plugin Portal mirrors jcenter (with a 303) if it cannot find a resource locally as before.

Thanks @bamboo, and everyone for reporting this to us.
