### ISSUE TITLE
When reloading a Play! application, if the classloader has not changed, do not reload the application.

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#3295]
When changing a file that is only served as "assets" (and is not part of the classloader), Gradle still reloads the Play application. This is unnecessary.

SBT had a related problem: https://github.com/playframework/playframework/issues/2905

### Expected Behavior

When changing an asset file or a file that does not affect the classloader of the Play application, the Play application does not reload.  The Gradle build may still need to run (e.g., to copy assets/generate other assets).

### Current Behavior

Play application reloads on any change.

### Steps to Reproduce (for bugs)

1. Using the "basic" Play application sample, run the Play application (`gradle runPlay`)
2. Change a file in `public/`.  Observe the Play application stops/starts.  This is unnecessary when the file is not a part of the classloader.

**Comment by 2020saurav** [comment]
@big-guy, Just checking if there is any action planned for this issue?

**Comment by manufacturedba** [comment]
Also interested in seeing this fixed

**Comment by ymwang1984** [comment]
@big-guy @bigdaz Just checking, any upadte on this issue?

**Comment by ymwang1984** [comment]
@blindpirate  Thanks a lot for the fix! 

Is there a Gradle nightly version that we could try out? Thanks!

**Comment by blindpirate** [comment]
@ymwang1984 Tomorrow I guess, I'll let you know. :-)

**Comment by oehme** [comment]
@ymwang1984 please let us know if this fixes the issue for you

**Comment by ymwang1984** [comment]
@oehme 

We are still verifying. Initial feedback is good as a few front-end devs said the re-deploy is much faster with asset change only. Please give us one more week to thoroughly test it. Thanks a lot!
