### ISSUE TITLE
tar.gz artifact not resolved from Nexus maven repository with Gradle 4.2.x

### ISSUE THREAD

**Issue by Bluesboy** [gradle/gradle#3303]
### Expected Behavior
I'm trying to pack application bundle with Gradle, for this purpose I'm using **dependencies**. Gradle 4.2.x throws an error, but previous versions are works fine.

### Current Behavior
Gradle 4.2.x throws this error:
```
FAILURE: Build failed with an exception.

* Where:
Script '/home/bluesboy/work/project/gradle/repack.gradle' line: 71

* What went wrong:
Execution failed for task ':unpackWildfly'.
> Could not resolve all files for configuration ':wildfly'.
   > Could not find wildfly.tar.gz (com.redhat:wildfly:10.1.0.Final).
     Searched in the following locations:
         http://nexus.ps.lcl:8081/repository/maven-releases/com/redhat/wildfly/10.1.0.Final/wildfly-10.1.0.Final.tar.gz
```
What's confusing is that if I **curl** this link it downloads fine, and previous versions of Gradle (3.5.0 - 4.1.x) works as expected 
### Context
I can download this artifact with **download** plugin, but that way Gradle do not use cache, and redownloads large file on every build

### Steps to Reproduce (for bugs)
Upload wildfly-10.1.0.Final.tar.gz as an maven artifact in Nexus repository, then run this task:

```
configurations {
  wildfly
}
dependencies {
  wildfly 'com.redhatt:wildfly:10.1.0.Final@tar.gz'
}
task unpackWildfly {
  doLast {
    copy {
      from tarTree(configurations.wildfly.singleFile)
      into "${buildDir}/unpack/"
    }
  }
}
```

### Your Environment
Nexus 3.5.2
Gradle 4.2.x

**Comment by bmuschko** [comment]
Is there any chance you can reproduce the issue with Maven Central? At the moment your issue is hard to diagnose as I can't have a look at your repository or try out your build.

**Comment by Bluesboy** [comment]
@bmuschko Now I can't reproduce it myself, even with my local Nexus repo. Maybe it was something related with user session or environment. I guess you can close this issue. Anyway thank you for response.

**Comment by bmuschko** [comment]
@Bluesboy Thanks for checking.
