### ISSUE TITLE
Urgent : Baseline file for "Lint" is not created for app module when it has any other module dependency

### ISSUE THREAD

**Issue by krishnaChaitanyaAripaka** [gradle/gradle#3304]
Hi,
I have an "app" module and "library" module in my project
**App Gradle :**
android {
    
    flavorDimensions "lintMain"
    productFlavors {
        higherVersion {
            minSdkVersion 20
        }
        mainapp {
            minSdkVersion 19
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        lintConfig file("$project.rootDir/lint_check/mylint.xml")
        baseline file("$project.rootDir/lint_check/baseline-demo-app.xml")
        abortOnError true
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':mylibrary')
}

**Library Gradle :**

android {
    flavorDimensions "lintLib"
    productFlavors {
        mainapp {
            minSdkVersion 19
        }
    }

    lintOptions {
        lintConfig file("$project.rootDir/lint_check/mylint.xml")
        baseline file("$project.rootDir/lint_check/baseline-demo-lib.xml")
        abortOnError true
    }
}

**Description :**
When I don't link the app module with library then 2 baseline files (one for app and other for library module) are created. 
But when I link app with library like this **"compile project(':mylibrary')"** then 
1. First time I run this "./gradlew lintMainappRelease", it creates baseline file only for library module but not for app.
2. Second time I run the same command "./gradlew lintMainappRelease" then it creates baseline for app.

Cab I get some help how to fix this.

**Comment by bmuschko** [comment]
Please open Android-related issues on the [Android issue tracker](https://source.android.com/source/report-bugs) as suggested in the issue instructions.
