### ISSUE TITLE
Show `strict` and `prefer` version constraints in the dependency reports

### ISSUE THREAD

**Issue by melix** [gradle/gradle#3307]
If the dependency graph contains dependencies declared with `strictly` or `prefers` constraints, they should be visible as such when running `gradle dependencies` and `gradle dependencyInsight` reports.

### Expected Behavior

The dependencies report should allow different version constraints to be correctly identified.

### Current Behavior

Strict and prefer constraints are shown as regular dependencies. There's no way to know from the report that a dependency has a strict or prefer constraint.

**Comment by etiennestuder** [comment]
Probably also something for build scans.

**Comment by bigdaz** [comment]
One option to implement this is to provide a well formatted description for a version constraint, that is available in the `ResolutionResult` API and can be used in the `dependencies` report and build scans.
