### ISSUE TITLE
How to get notified on Gradle releases?

### ISSUE THREAD

**Issue by pvdissel** [gradle/gradle#3319]
I've been following the gradle-dev mailinglist for ages, and I know the usage of that mailing list was stopping slowly. But now it seems the gradle release updates have also been stopped being published on the gradle-dev mailinglist.

So, what's the new way to get notified on Gradle releases?

**Comment by blindpirate** [comment]
@eriwen could you please let us know the answer?

**Comment by TheSnoozer** [comment]
I'm currently using github's integrated features for this. Subscribe to the releases as RSS via:

https://github.com/gradle/gradle/releases.atom

**Comment by eriwen** [comment]
That's an excellent question @pvdissel! Most folks get release announcements through [our Twitter channel](https://twitter.com/gradle), however, we are considering better way to proactively allow users to be notified — stay tuned!

**Comment by bmuschko** [comment]
I guess another option would be to subscribe to https://discuss.gradle.org/c/news. We usually post release announcements there.

**Comment by bmuschko** [comment]
Given these option I think you we can close this issue.

**Comment by pvdissel** [comment]
:+1: thanks, it's a good start :)

**Comment by adamdougal** [comment]
Is there any way to only get the released versions and not the release candidates?

**Comment by eriwen** [comment]
I have meant to move this to the blog so one could easily get what you want @adamdougal. For now, if you really want minimal notifications and don't want to subscribe to GitHub releases or forum news, you could subscribe to [Gradle releases in the Youtube Channel ](https://www.youtube.com/playlist?list=PLLQbIfXVLZqEC80VWVU5DFgPBO7HMsXX9) even though that seems a bit unorthodox.
