### ISSUE TITLE
Tips on using gradle in a z/OS environment (without the daemon)

### ISSUE THREAD

**Issue by daveyc** [gradle/gradle#3320]
This issue is documentation not a bug.

I've just started to use gradle on a z/OS system. 

The first hurdle was the requirement for `-Dfile.encoding=UTF8`, a common issue when reading jar files on a EBCDIC system. 

The second hurdle was the daemon! I didn't dig too deep but it seems the daemon reads from stdout which is in EBCDIC. I tried `-Dconsole.encoding=UTF8`  which broke everything :smile:.  I don't think we need the daemon when using the IBM JVM. The `-Xshareclasses` option uses AOT (ahead-of-time compilation) which caches compiled Java code into a UNIX shared memory segment to be reused. This was 50% faster than `--no-daemon`.

` DEFAULT_JVM_OPTS="-Dfile.encoding=ISO8859-1 -Xshareclasses -Dorg.gradle.daemon=false"`

**Comment by bmuschko** [comment]
Are you suggesting to add these settings to the Gradle documentation? To be honest I am not quite sure how that will fit in with other information. It simply seems to be very specific.

**Comment by jlczuk** [comment]
Assuming the original poster's thought about the need for the file.encoding setting, as well as the shareclasses and setting false for the gradle daemon is still ture, it seems to me that the "Installing Gradle" section of the docs would be appropriate.  Step 3. Configure your system environment has specific instructions for both Linux & Mac Users and for Windows Users.

I am investigating using Gradle and I would need for it to run on z/OS.  I will try to document my findings here in terms of what would be required or helpful configuration settings.

My current build uses Ant, but I want to revise that to take advantage of Gradle so incorporate dependency checking for dependent jars and eventually a perhaps cleaner build task structure.
