### ISSUE TITLE
Upgrade ant to 1.9.9

### ISSUE THREAD

**Issue by george-moberly** [gradle/gradle#3322]
A user reports that they are using Ant attributes that were new in Ant v1.9.7, and they are forced to repackage Gradle as we are still on 1.9.6.

The version packaged with Gradle is almost 2.5 years old at this point:
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015

The latest stable version has been out for 9 months now
$ ant -version
Apache Ant(TM) version 1.10.1 compiled on February 2 2017

**Comment by big-guy** [comment]
We can only update to Ant 1.9.9 because Ant 1.10.1 requires Java 8. http://ant.apache.org/

**Comment by george-moberly** [comment]
changing headline to request 1.9.9
