### ISSUE TITLE
Compress verbose console output

### ISSUE THREAD

**Issue by kenzierocks** [gradle/gradle#3325]
### Expected Behavior

Using verbose console output should print the task names, but should still be reasonably dense information-wise.

### Current Behavior

Verbose console outputs two newlines for every task, which makes the output sparse and not as easy to read.

### Context

I really liked the old style output, and I was happy to see verbose console mode added. However, I don't think the extra newlines add any clarity and might reduce it due to the extra separation. (This is just my opinion, but I think that others who wanted the old output might agree.)

### Steps to Reproduce (for bugs)

Run a build using verbose console output.

**Comment by ilya-g** [comment]
I've also noticed that verbose console tends to repeat task names without any output during parallel builds. Here is excerpt from the output when it happens: https://pastebin.com/8rGarXF5

I expect that task name should be printed only when a task outputs something or when it completes.

**Comment by bmuschko** [comment]
@kenzierocks Do I understand it correctly? This is just about the extra new lines?

@ilya-g The issue you report might have a different root cause. Could you please open a separate issue for it including a reproducible example?

**Comment by kenzierocks** [comment]
Yes, @bmuschko, this is just about new lines. You can see it in the pastebin that was linked however.

**Comment by bmuschko** [comment]
@kenzierocks Thanks, would you be interested in providing a pull request for this?

**Comment by kenzierocks** [comment]
Sure!

**Comment by ilya-g** [comment]
@bmuschko Opened #3456

**Comment by kenzierocks** [comment]
#3491 has been created.
