### ISSUE TITLE
Remove usage of --no-search-upwards in tests/samples

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3333]
They should use a settings file instead.

**Comment by bmuschko** [comment]
@oehme Checking in on the scope here. Am I correct to assume that we'll want to remove "magic" behavior from our integration test infrastructure as well? For example `AbstractGradleExecuter` [sets `--no-search-upwards` automatically](https://github.com/gradle/gradle/blob/master/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/AbstractGradleExecuter.java#L852-L854) if no setting file can be found. I removed that to see the impact and it results in thousands of failed test cases. I guess we'd have two options here:

1. Touch up all failing test classes manually by creating an empty settings file if no other settings behavior should be tested. There are actually some test classes that explicitly do not require the initial creation of a settings file (e.g. init plugin).
2. Automatically create an empty settings file in the `setup` method in `AbstractIntegrationTest` with an option to deactivate the behavior.

Do you have any thoughts on this?

**Comment by oehme** [comment]
I think we can start with an internal system property that's only used by our test executor. TestKit can use the internal API on `GradleConnector`. I.e. we keep the behavior in place for testing purposes, but we deprecate/remove the CLI option.
