### ISSUE TITLE
Deprecate --no-search-upwards

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3334]
Users should create a settings file instead of using this option.

**Comment by bmuschko** [comment]
This will likely introduce an automatic breaking change. TestKit [sets no search upwards](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/ToolingApiGradleExecutor.java#L184) for every test execution. If we'd deprecate the option then plugin authors would see the deprecation message for every test. Instead we should probably remove the default behavior which might break tests or make it configurable through the `GradleRunner` API.

**Comment by adammurdoch** [comment]
We can continue to honor this when requested through the TAPI. We want to remove all public ways to request 'no search upwards' behaviour but we can also give TestKit a way to ask for this when running tests, possibly by having it just use `--settings-file` to point to a placeholder when there is none in the test project directory.
