### ISSUE TITLE
gradle doesn't find local repository if it's a symlink

### ISSUE THREAD

**Issue by plecesne** [gradle/gradle#3336]
### Context

For reasons beyond my control, the local repository I'm compiling against is behind symlinks.

gradle resolves the symlink of the project directory, but it does so *before* evaluating the file paths (i.e. it assumes that all the files under the project directory have the same directory structure and same file names). That is an issue if the files actually have a different path, e.g.

```
buildscript {
  repositories {
    maven {
      url rootProject.file("maven/repository/local/")
    }
  }
}
```
with the following symlinks:

`my_project/ --> /tmp/`
`my_project/maven/repository/local/com/google/guava/guava/22.0/guava-22.0.pom --> /tmp/165a4bd984f`

and passing `-p my_project` to gradle would lead to the exception:

```
Could not find com.google.guava:guava:22.0.
     Searched in the following locations:
         file:/tmp/maven/repository/local/com/google/guava/guava/22.0/guava-22.0.pom
```

### Expected Behavior
Gradle should resolve the symlinks only when looking at files, not directories, thus search for the repository at `my_project/maven/repository/local/...` instead of `/tmp/maven/repository/local/...`

### Current Behavior
Gradle should only resolve symlinks when reading files, not resolve symlinks of directories (in particular of the project directory), so that symlinks become truly transparent to the build system as they should be.

The resolution of the symlink for the project directory seems to be done [here](https://github.com/gradle/gradle/blob/b7a7fca42497c8fd2a31f0296b826e6c70bb9078/subprojects/core/src/main/java/org/gradle/initialization/BuildLayoutParametersBuildOptions.java#L71).

### Steps to Reproduce (for bugs)
Use a local maven repository by adding an init script of type:

```
rootProject {
  buildscript {
    repositories {
      maven {
        url rootProject.file("path/to/local/maven/repository")
      }
    }
  }
}

allprojects {
  repositories {
    maven {
      url rootProject.file("path/to/local/maven/repository")
    }
  }
}
```

Have all files from "path/to/local/maven/repository" be a symlink to files in a different directory, e.g. /tmp/1, /tmp/2, etc.

### Your Environment
Ubuntu, Gradle 4.0.1

**Comment by ov7a** [comment]
Sorry for the late reply. 

This is still reproducible in Gradle 9.5.1

Related:
- https://github.com/gradle/gradle/issues/35379
