### ISSUE TITLE
A build option should be declarable for internal use only

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3339]
### Expected Behavior

Build options (command line and Gradle property) can be declared to be "internal". Internal build options cannot be discovered by the end user. 

The [API for configuring a command line option](https://github.com/gradle/gradle/blob/master/subprojects/build-option/src/main/java/org/gradle/internal/buildoption/CommandLineOptionConfiguration.java) could look this way:

```
public class CommandLineOptionConfiguration {
    private boolean internal;

    public CommandLineOptionConfiguration internal() {
        internal = true;
        return this;
    }

    public boolean isInternal() {
        return internal;
    }
}
```

Gradle properties are currently not discoverable by the end user. A convention should be established that marks a Gradle property as internal e.g. start with the prefix `org.gradle.internal`.

### Current Behavior

As soon as a build option is declared in Gradle core and that change has been released, the user will be able to discover it e.g. by executing `gradle -?`.

### Context

Features enabled/disabled by build options might not be ready or intended for external consumption at the time of releasing a new version of Gradle. Those build option should be hidden from the user. 

This feature is needed for longer-running features like dependency locking that likely won't expose user-facing value in one Gradle release. Nevertheless, integrating the code early on has a lot of benefits for developing the feature.

**Comment by oehme** [comment]
I don't think we need an internal build option, we can use an internal system property and then add a build option when we actually want to expose the feature to users.

**Comment by bmuschko** [comment]
> then add a build option when we actually want to expose the feature to users.

I was thinking along the lines of having the code in the code base plus the relevant tests that use the build option from the command line without actually making it available to the end user.

**Comment by oehme** [comment]
What's the use case though? Why is it important to have a build option when the feature is not meant for users? For tests we can hide the details of how to activate the feature in a setup method. Then when we introduce the user-facing option we only change a single place.

**Comment by bmuschko** [comment]
> For tests we can hide the details of how to activate the feature in a setup method.

Let's say you want to expose a user-facing feature that will expose a command line option. The tests use that user-facing feature. However, to make it useable for the end user an additional feature needs to be added which is not ready for release yet. In those cases you have three options:

1. Rip out the whole feature from the code base.
2. Integrate the code but do not expose it the end user. Deactivate it with a feature flag.
3. Integrate the code but test it with internal ways to activate feature. The test code will still have to be changed when the feature becomes ready for the end user to cover the user-facing command line options.

I am talking about point 2. here which is generally not an uncommon thing to do.
