### ISSUE TITLE
Auto-applied build scan plugin should not render warning when other plugins are applied with plugin DSL

### ISSUE THREAD

**Issue by grv87** [gradle/gradle#3341]
### Expected Behavior
According to [4.3 release notes](https://docs.gradle.org/4.3/release-notes.html#convenient-use-of-build-scan-plugin):
> This version of Gradle makes it even easier to gain deep insights into your build. By using the command line option `--scan`, the latest build scan plugin is applied automatically.

### Current Behavior
* There is build scan 1.10.1 already, but Gradle uses 1.9.1
* There is a warning that plugin was applied after other plugins
```
$ gradle build --scan
Download https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/1.9.1/build-scan-plugin-1.9.1.pom
Download https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/1.9.1/build-scan-plugin-1.9.1.jar

BUILD SUCCESSFUL in 10s
6 actionable tasks: 4 executed, 2 from cache

WARNING: The build scan plugin was applied after other plugins.
The captured data is more comprehensive when the build scan plugin is applied first.

Please see https://gradle.com/scans/help/plugin-late-apply for how to resolve this problem.
```

### Steps to Reproduce (for bugs)
`gradle build --scan`

**Comment by bmuschko** [comment]
The wording for the auto-applied build scan plugin is incorrect in the release notes and misleading. A specific build scan version is bound to a specific Gradle version. It's basically hard-coded. Gradle does not try to use the latest version of the build scan plugin as it has to be compatible with it. Newer versions of the build scan plugin might use an API from Gradle core that does not exist with earlier versions.

Regarding the warning: Do you apply the build scan plugin in your build script as well? It sounds like you do but not as the first plugin in the list. Please provide a reproducible and minimalistic example. I cannot reproduce it with a simple build script executed by Gradle 4.3.

**Comment by grv87** [comment]
My bad. I got a problem with version and made far-reaching conclusion that the feature in the the whole was not production-ready.

The problem is in `nebula.dependency-lock` plugin. Without that warning disappears. I'll redirect the issue to them.

I suppose that release notes could not be changed, so I'm closing this.

**Comment by oehme** [comment]
@grv87 Can you please attach a reproducible example project? The warning you see should not happen, no matter what other plugins you apply.

**Comment by grv87** [comment]
build.gradle:
```
plugins {
  id 'nebula.dependency-lock' version '4.9.5'
  id 'lifecycle-base'
}
```
Run:
```
$ gradlew build --scan

BUILD SUCCESSFUL in 4s

WARNING: The build scan plugin was applied after other plugins.
The captured data is more comprehensive when the build scan plugin is applied first.

Please see https://gradle.com/scans/help/plugin-late-apply for how to resolve this problem.

Do you accept the Gradle Cloud Services license agreement (https://gradle.com/terms-of-service)? [yes, no]
yes
Gradle Cloud Services license agreement accepted.

Publishing build scan...
https://gradle.com/s/xxxxxxxx


```

**Comment by bmuschko** [comment]
@grv87 Thanks for providing the example. I can reproduce the warning message. It looks to me that the auto-applied is added later in the list than any external plugin applied by the plugin DSL. We'll look into a fix. Please be aware that the actual functionality is working as-is.

**Comment by oehme** [comment]
Let's fix this in 4.3.1 by adding the auto-applied plugin first.

**Comment by bmuschko** [comment]
@grv87 This has been fixed. Could you try out your project with a snapshot of the 4.3.1 release? https://downloads.gradle.org/distributions-snapshots/gradle-4.3.1-20171107130851+0000-bin.zip

**Comment by grv87** [comment]
Confirm the fix of this issue. Thank you!

However, I can't confirm that change of load order doesn't introduce new problems with other plugins.


I wrongfully blamed `nebula.dependency-lock` plugin. I believed the problem was in that *magic* that it does with dependencies.
