### ISSUE TITLE
Specifying httpTimeout only for build cache

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#3345]
In my company we have a (in my opinion) typical setup of our internal network.
"Everything" is only accessable inside this network.
For me, as a remote worker, I need a VPN.

Now, we wanted to introduce gradles build cache. Using [this](https://www.jfrog.com/blog/speed-up-your-gradle-builds-with-jfrog-artifactory/) tutorial to setup the cache on our internal artifactory.
The problem is now, that we have **always** be connected to our VPN. Even if its not needed. E.g. just building a Android App. gradle look always if there is a cache and wait - if its not reachable...

In 4.3 you introduced a httpTimeout. Unfortunately it is defined for **all** network connections. It is not specific for the build cache.
In my opinion we should have two different timeouts. One for "general" network connections. And one specific for the build cache.
Why?
Because the "open internet" (or speciaclly jcenter where most of our dependencies live) is something different than a build-cache which may hold classes which should never be live in the "open internet".

> **Note:** I've removed your template because it doesn't fit very well in this issue (IMO). Sry for that 😅

**Comment by bmuschko** [comment]
I can see the need for wanting to declare different timeouts for different repositories and/or the remote build cache. Is the default of 30 seconds (as defined in Gradle 4.3.1) not a good enough middle ground to fulfill both use cases?

**Comment by StefMa** [comment]
Unfortunately no.
Given that one developer has not connected to the VPN and runs
```
./gradlew clean random-module:build --console=rich
```
this will stock for 30 secs at the first time the remote cache got asked about it.
Which will increase the build time a lot (assume that the `random-module` will build from scratch (without any caching or so) just 30 secs).

Another question:
I don't know how the timeout works...
Will it used "one time" or "for each request"?
Given we set the timeout to 5 sec. 
Will each task request and wait for 5 sec **or **will the first task request, wait and say to all other task "it is not available"/"we got a timeout, don't try it again"? 🤔 
And what happen if the first task wait 5 seconds, got a response after 3 seconds and the next task request again? Will the second task wait only 2 seconds more or will they wait for 5 sec again? 🤔

**Comment by wolfs** [comment]
@StefMa When a task runs into a timeout when pulling from or pushing to the build cache the build cache will be disabled for the rest of the build. The next build we will try again. The timeout is per request, so each request would need to be below the timeout. In your example the second task would also wait for 5 sec for a response from the build cache.

**Comment by lptr** [comment]
I don't think setting timeouts is the way to handle this. A better way would be to enable the remote cache only if the VPN is available.

**Comment by StefMa** [comment]
@lptr and how can I archive that? ☺

**Comment by lptr** [comment]
If you know a way to determine if the VPN is up (maybe you have an environment variable? some command-line utility you can call?), then you can do something like this in your `settings.gradle`:

```gradle
buildCache {
    remote {
        enabled = // ... <-- here comes the code that determines if the VPN is up
    }
}
```

**Comment by wolfs** [comment]
@StefMa Has your problem been addressed? Please re-open this issue if you think there is still something to do on our side.

**Comment by StefMa** [comment]
@wolfs yeah, thank you for you help
I will give it a try 👍

**Comment by StefMa** [comment]
I just tried it with 
```groovy
        enabled = {
            if (InetAddress.getByName("http://google.de").isReachable(3000)) {
                println 'Found VPN connection'
                return true
            } else {
                println 'VPN connection not found, defaulting to offline build'
                return false
            }
        }()
```

Unfortunately I got a `https://google.de: unknown error` on terminal and this in intellij:
```
Unknown host 'https://google.de: nodename nor servname provided, or not known'. You may need to adjust the proxy settings in Gradle. Learn about configuring HTTP proxies in Gradle
```

But I don't want to set up a proxy, right? 🤔

**Comment by wolfs** [comment]
@StefMa I guess you want to catch the `UnknownHost` exception and set enabled to false.

**Comment by StefMa** [comment]
Just for tracking.
This works:
```groovy
        enabled = {
            try {
                Socket socket = new Socket()
                socket.connect(new InetSocketAddress("google.de", 80), 100)
                println "Found VPN connection. Enable remote build cache"
                socket.close()
                return true
            } catch (IOException exe) {
                println "VPN connection not found (Reason: '${exe.message}'). Disable remote build cache."
                return false
            }
        }()
```

I use Socket because with that you can specify the port.
Our internal artifactory was blocked with `InetAddress`...
