### ISSUE TITLE
Provide a better API for making POM modifications

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#3348]
Gradle Maven plugin does not expose enough of public APIs to properly configure pom files from Java.

### Expected Behavior
We would like to have an API similar to the following:
```
pom.getProject().setName("Bananas");
pom.getProject().setDescription("Bananas is a great library");
pom.getProject().setUrl("http://www.bananas.com");
pom.getProject().setInceptionYear("2017");
pom.getProject().setDevelopers(new Developers((new Developer()).setName("Expert Inc")));
...
```

### Current Behavior
Currently, we can only do something similar to this in Groovy:
```
pom.project {
  name 'Bananas'
  description 'Bananas is a great library'
  url 'http://www.bananas.com'
  inceptionYear '2017'
  licenses {
    license {
      name 'The Apache Software License, Version 2.0'
      url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
      distribution 'repo'
    }
  }
  developers {
    developer {
      name 'Expert Inc'
    }
  }
}
```

### Context
[Maven plugin docs](https://docs.gradle.org/current/userguide/maven_plugin.html) gives an example of configuring Maven pom "Example 33.6. Builder style customization of pom". It seems to be using 
[org.gradle.api.artifacts.maven.MavenPom](https://github.com/gradle/gradle/blob/063c320418f56a8a37273ed5312fdcab8d9ac0b9/subprojects/maven/src/main/java/org/gradle/api/artifacts/maven/MavenPom.java) object behind the scenes. We are trying to write a java Gradle plugin that allows us to automate pom configuration. Sadly, we have to use groovy instead of java since most of the methods are not public (and groovy just reflects into everything).

### Your Environment
Using Gradle 4.3 and maven plugin

Our exact class that does this [here](https://android.googlesource.com/platform/frameworks/support/+/master/buildSrc/src/main/groovy/android/support/SupportLibraryMavenUploader.groovy)

**Comment by eskatos** [comment]
Hi @liutikas,
Thanks for the report!
We have no immediate plan to provide a Java api for this.

Doing it in Groovy is the most convenient way at the moment.
In Java you could use [`MavenPom::getModel()`](https://github.com/gradle/gradle/blob/063c320418f56a8a37273ed5312fdcab8d9ac0b9/subprojects/maven/src/main/java/org/gradle/api/artifacts/maven/MavenPom.java#L159-L167) that returns the underlying native Maven `org.apache.maven.model.Model` object.

**Comment by eskatos** [comment]
@liutikas, thinking a bit more about this, my advice ☝️ on using `MavenPom::getModel()` isn't good. The underlying implementation is shaded and cannot be loaded.

So, Groovy it is for now.

**Comment by oehme** [comment]
We should also provide a better API in the maven-publish plugin.

**Comment by marcphilipp** [comment]
Minimum requirements for publishing to Central:
http://central.sonatype.org/pages/requirements.html#sufficient-metadata

Complete reference:
https://maven.apache.org/pom.html

**Comment by liutikas** [comment]
Here is exactly the snippet of groovy I would love to replace:
https://android.googlesource.com/platform/frameworks/support/+/refs/heads/support-library-27.1.1/buildSrc/src/main/kotlin/android/support/MavenUploadHelper.kt#62

Ideally, we do provide a way to set licenses and developers. That way I can remove all of the groovy code. If we use MavenPom it should be proper object types that we can then set onto pom without using private methods.

**Comment by martinbonnin** [comment]
For the record, this can be done in Kotlin with something like this:

```kotlin
            setProperty("inceptionYear", "2016")

            invokeMethod("licenses", delegateClosureOf<groovy.lang.GroovyObject> {
              invokeMethod("license", delegateClosureOf<groovy.lang.GroovyObject> {
                setProperty("name", "The Apache Software License, Version 2.0")
                setProperty("url", "http://www.apache.org/licenses/LICENSE-2.0.txt")
                setProperty("distribution", "repo")
              })
            })
```

It's not pretty but it works and I guess there's a way to construct those Groovy closures in Java too.
