### ISSUE TITLE
Simple Java Scanner Input Gives NoSuchElementException

### ISSUE THREAD

**Issue by securitygate** [gradle/gradle#3350]
When I attempt to compile a simple input file, using, "gradle clean", "gradle build" and "gradle run", I end up receiving the following error:

### Expected Behavior

I expect the machine to initially output "Text Input: ", then allowing the user to input text, which will then be output afterwards.  

### Current Behavior

I receive the following errors, depending on whether I use "nextInt()".

> Exception in thread "main" java.util.NoSuchElementException
>         at java.util.Scanner.throwFor(Scanner.java:862)
>         at java.util.Scanner.next(Scanner.java:1485)
>         at java.util.Scanner.nextInt(Scanner.java:2117)
>         at java.util.Scanner.nextInt(Scanner.java:2076)
>         at main.main(main.java:9)

The following error is for "nextLine()":

> Text Input: Exception in thread "main" java.util.NoSuchElementException: No line found
>         at java.util.Scanner.nextLine(Scanner.java:1540)
>         at Main.main(Main.java:9)

### Context

With this error, I am unable to obtain any user input from the command line.  

### Steps to Reproduce (for bugs)

```
import java.util.Scanner;

public class Main{

   public static void main(String args[]){
   Scanner scan= new Scanner(System.in);

   System.out.print("Text Input: ");
   String text= scan.nextLine();
   System.out.println(text);

   }
}
```

### Your Environment

 * Build scan URL: 

Running Java 1.8_121, on a windows 7 environment, using Gradle 4.3 through PowerShell.

**Comment by blindpirate** [comment]
@bmuschko I think you're best person to answer this.

**Comment by oehme** [comment]
You probably didn't set an [input stream](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:standardInput) on your `run` task, so no input can be obtained.

**Comment by G-Drake** [comment]
This question is exactly the same error that I am getting, and I cant find the answer.

**Comment by G-Drake** [comment]
This question is exactly the same error that I am getting, and I cant find the answer.

**Comment by hajame** [comment]
You can add this to the end of your `build.gradle` to define standardInput.

```
run {
    standardInput = System.in
}
```

**Comment by titan369** [comment]
> You can add this to the end of your `build.gradle` to define standardInput.
> 
> ```
> run {
>     standardInput = System.in
> }
> ```

I tried including this in build.gradle in the project but it still doesn't recognised Scanner. The same error message is generated. Any other remedy apart from the above?

**Comment by Pawananjani1A** [comment]
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextLong(Scanner.java:2222)
	at java.util.Scanner.nextLong(Scanner.java:2182)
	at Codechef.main(Main.java:25)
I am also having similar problem while solving a codechef problem.

**Comment by ninoshainidze** [comment]
but I run code in intel j and it worked. and I want to run my code in sololearn and then I have this situation. how can I fix it there?

**Comment by david-slalom** [comment]
> You can add this to the end of your build.gradle to define standardInput.
> run {
>     standardInput = System.in
> }

This worked for me

**Comment by PriyankaPawar7910** [comment]
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextInt(Scanner.java:2117)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at Source.main(Source.java:157)
I am getting this error. This is my code.

   public static void main(String[] args) {
		//CODE HERE
		Scanner sc = new Scanner(System.in);
	    List<Doctor> DocData = new ArrayList<Doctor>();
		String docList[] = doctorsData.split(";");
		int i;
		int length = docList.length;
		for(i=0;i<length;i++){
		    String send[] = docList[i].split("-");
		    DocData.add(new Doctor(send[0],send[1],Integer.parseInt(send[2])));
		}
		DoctorService DrServ = new DoctorService(DocData);
	    int choice = sc.nextInt();
		switch(choice){
	        case 1:
		        int years=sc.nextInt();
		        System.out.println(DrServ.getExperienceDoctors(years));
		        break;
	        case 2:
	            String dept = sc.nextLine().trim();
	            System.out.println(DrServ.getSpecialityDoctors(dept));
	            break;
	        default:
	            System.out.println("Invalid Choice");
		    
		}
	}

I am unable to use hasNextInt and hasNextLine function at same time. Please hepl

**Comment by ninoshainidze** [comment]
> Exception in thread "main" java.util.NoSuchElementException
> at java.util.Scanner.throwFor(Scanner.java:862)
> at java.util.Scanner.next(Scanner.java:1485)
> at java.util.Scanner.nextInt(Scanner.java:2117)
> at java.util.Scanner.nextInt(Scanner.java:2076)
> at Source.main(Source.java:157)
> I am getting this error. This is my code.
> 
> public static void main(String[] args) {
> //CODE HERE
> Scanner sc = new Scanner(System.in);
> List DocData = new ArrayList();
> String docList[] = doctorsData.split(";");
> int i;
> int length = docList.length;
> for(i=0;i<length;i++){
> String send[] = docList[i].split("-");
> DocData.add(new Doctor(send[0],send[1],Integer.parseInt(send[2])));
> }
> DoctorService DrServ = new DoctorService(DocData);
> int choice = sc.nextInt();
> switch(choice){
> case 1:
> int years=sc.nextInt();
> System.out.println(DrServ.getExperienceDoctors(years));
> break;
> case 2:
> String dept = sc.nextLine().trim();
> System.out.println(DrServ.getSpecialityDoctors(dept));
> break;
> default:
> System.out.println("Invalid Choice");
> 
> ```
> 	}
> }
> ```
> 
> I am unable to use hasNextInt and hasNextLine function at same time. Please hepl

can u tell me what was your task?
