### ISSUE TITLE
UnsupportedJavaRuntimeException.javaDeprecationWarning() should fail gracefully

### ISSUE THREAD

**Issue by donat** [gradle/gradle#3355]
The `UnsupportedJavaRuntimeException.javaDeprecationWarning()` method calls `JavaVersion.current()` which throws a runtime exception in previous Gradle versions when executed on Java 9. This is the root cause why the Tooling API lost backward compatibility on that platform (#3317). 

### Expected Behavior
Instead of throwing an exception, the method should log the parse error when an unknown Java version is found.

### Current Behavior
The current state is fine but not future-proof. If a new version scheme is introduced by Java then #3317 will happen again.

**Comment by donat** [comment]
We can either fix this particular problem or adjust `JavaVersion` such that it returns an `UnknownVersion` if the version string parsing fails.

**Comment by blindpirate** [comment]
Oops, this is closed automatically by comments in my commits.
