### ISSUE TITLE
Gradle metadata should support dependency constraints

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3356]
In the metadata we want to support dependency constraints. A constraint narrows down what versions of a module are considered compatible with the one I’m building. Its notation is almost identical to a dependency:

```
dependencies {
  constraints {
    implementation  "com.google.guava:guava:[15, 18]"
  }
}
```

Constraints can be used to model maven's _optional_. To implement this, we roughly need to:
- Replace the optional property in [GradleDependencyMetadata](https://github.com/gradle/gradle/blob/be828ab474aeeaaefeebfef81dfde9e4a3b840c9/subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/GradleDependencyMetadata.java#L116) and the other DependencyMetadata implementations with constraints. In the other implementations, optional needs to be mapped to constraints.
- Support constraints in [ModuleMetadataParser](https://github.com/gradle/gradle/blob/2eedc2890b54bfbb80c6dcbe04b63bf5e072a658/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/ModuleMetadataParser.java#L156)
   - This could be done in a separate step
- Adjust and extend test coverage for _optional_

**Comment by oehme** [comment]
I don't think we want `optional` in our metadata file. We want to have constraints instead and refactor internally to map Maven's "optional" concept to these constraints.

**Comment by jjohannes** [comment]
This is a duplicate of issues in #3549.
