### ISSUE TITLE
Gradle indefinitely hangs when internet connection is suddenly changed to airplane mode 

### ISSUE THREAD

**Issue by shashidhar502** [gradle/gradle#3361]
Environment Android Studio
Gradle version 3.3. 4.1 4.3 all tested

Steps to reproduce

Create a gradle project which needs to download the dependencies from the server
in the middle of download switch the internet connection to airplane mode

Gradle will struck at the same place even after 10 minutes

### Expected Behavior
It has to stop or fail the build

### Current Behavior
it hangs indefinitely 

### Steps to Reproduce (for bugs)

Steps to reproduce

Create a gradle project which needs to download the dependencies from the server
in the middle of download switch the internet connection to airplane mode

Gradle will struck at the same place even after 10 minutes

### Your Environment

 * Build scan URL: 

Android Studio

**Comment by oehme** [comment]
Gradle 4.3 should time out connections after 30s. Can you verify this is still happening with 4.3?

**Comment by shashidhar502** [comment]
Yeah I verified
I thought there will be timeout so i have waited for 10 minutes but still it is in IDLE condition

**Comment by bmuschko** [comment]
@shashidhar502 Can you please run this with debug logs turned on (`-d`) ? I want to see what happens under the covers.

**Comment by bmuschko** [comment]
@shashidhar502 Do you have any more feedback here?

**Comment by bmuschko** [comment]
I am going to close this issue for now as we haven't gotten any additional feedback. Please provide the requested information if you'd like to continue the discussion.
