### ISSUE TITLE
Increase http timeout

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3370]
This has already been done for 4.4, but we should backport it to 4.3.1. The timeout should be 30s, not 10s by default.

Also, the timeout property should be prefixed with `org.gradle.internal`. It is only there for testing and not meant to be user-editable.

**Comment by cbeams** [comment]
As I mentioned in #4629, I've found that the new 30s timeouts are not enough when resolving built-on-the-fly dependencies from JitPack. I'd like to have an option to increase this to any value I need to. This is unfortunately a pretty serious degradation from the Maven builds I just ported to Gradle, where I never experienced these timeouts while doing the same JitPack-based builds.

**Comment by liucc52** [comment]
how to increase http timeout, because the artifact download often failed when use jcenter

**Comment by marcphilipp** [comment]
As the issue description states, there are properties (`org.gradle.internal.http.connectionTimeout` and `org.gradle.internal.http.socketTimeout`) so set the timeouts but they are currently only intended to be used internally for tests.

**Comment by liucc52** [comment]
what do you mean by only intended to be used internally for tests.
how to make org.gradle.internal.http.connectionTimeout and org.gradle.internal.http.socketTimeout in effect ,put them in gradle.properties right?

**Comment by liucc52** [comment]
it is still failing on downloading artifacts from jcenter or plugins.gradle.org/m2 sometimes, 
* What went wrong:
A problem occurred configuring root project 'job_80751537-9239-4754-a92e-52b642f83b6e_1532690884891'.
&gt; Could not resolve all files for configuration ':classpath'.
   &gt; Could not download nekohtml.jar (net.sourceforge.nekohtml:nekohtml:1.9.16)
      &gt; Could not get resource 'https://plugins.gradle.org/m2/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar'.
         &gt; Tag mismatch!


each time, it fails on different artifacts

**Comment by Xerus2000** [comment]
Have the properties changed? I set them in the `gradle.properties` file in a single-module project, but it didn't change anything.

**Comment by Xerus2000** [comment]
Did something about these properties change? I tried increasing them using a gradle.properties file on a simple project, but it still timed out after 30 seconds.
