### ISSUE TITLE
Solution for Task.execute() usage in tests with ProjectBuilder

### ISSUE THREAD

**Issue by dchesterman** [gradle/gradle#3372]
With task.execute being deprecated, I think it is more critical to come up with a solution for executing a task in a test while using ProjectBuilder.  This is the only use case we have for it.

I know some time ago there was talk that being able to do something like that was a known issue, but right now task.execute is the only way.

There is the buildscript/GradleRunner pattern but that is not straightforward (or even possible?)  to replicate classpath and gradle init script state that comes with the ProjectBuilder test pattern.

Is there any proposal for being able to trigger a tasks action in this type of test?

**Comment by big-guy** [comment]
You should use [Gradle TestKit](https://guides.gradle.org/testing-gradle-plugins/) to test task actions. `ProjectBuilder` can't do enough to properly test a task's actions.

I'm not sure what you mean by 
> There is the buildscript/GradleRunner pattern but that is not straightforward (or even possible?) to replicate classpath and gradle init script state that comes with the ProjectBuilder test pattern.

The GradleRunner is much, much closer to what your task will actually see classpath-wise when executing.  Is there something specific you had in mind for replicating the classpath?
