### ISSUE TITLE
Gradle dependency resolution fails if any repositories give a 400 error

### ISSUE THREAD

**Issue by magneticflux-** [gradle/gradle#3379]
### Expected Behavior

The dependency resolution step ignores the failed repository as the required dependencies are not present and checks the next repository.

### Current Behavior

The dependency resolution step throws an `org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException` exception which is never caught, failing the build.

### Context

After I updated from `4.2.1` to `4.3` in my Android project, I was unable to build the project. I depend on 4 Maven urls, one of which is custom.

### Steps to Reproduce (for bugs)

Project: https://github.com/magneticflux-/Gradle43DependencyBug

Change the wrapper from 4.3 to 4.2.1 and it builds correctly.

### Your Environment

Stacktrace: https://gist.github.com/magneticflux-/337cd873ddae8f842e5f4b54cff23f10

**Comment by magneticflux-** [comment]
Duplicate of #3335

**Comment by oehme** [comment]
Closing since this is a duplicate. A fix is on the way.
