### ISSUE TITLE
Build operations with "null" as description in IntelliJ

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#3386]
Some build operations show up as `null` in the console view.

![image 8](https://user-images.githubusercontent.com/495366/32449469-f0165bee-c311-11e7-8ff7-348b33c32b0a.png)

**Comment by bmuschko** [comment]
Is there an easy way to reproduce the issue? Do you have a sample build or did you just use the Gradle core build?

**Comment by lptr** [comment]
I was trying to run tests with this one: https://github.com/gradle/android-cache-fix-gradle-plugin
