### ISSUE TITLE
Provide a DSL to opt-out of Gradle metadata publishing

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3391]
When we enable Gradle metadata publishing by default, this would allow a user to opt-out for cases where we are unable to produce a valid Gradle metadata file for the publication.

Testing:
- Module metadata isn't produced with 'opt-out'
- 'opt-out' can be used to avoid failure for an 'un-publishable' component (eg see DefaultMavenPublication. checkThatArtifactIsPublishedUnmodified())

**Comment by bigdaz** [comment]
To fix the 'unpublishable component' problem, I think we should instead implement #3761. However there may still be a valid reason for a user to prevent the publishing of the Gradle metadata file.

**Comment by ljacomet** [comment]
Already possible through disabling the Gradle Module Metadata generation task, which are named `generateMetadataFileFor<PublicationName>Publication`.
