### ISSUE TITLE
Produce Gradle module metadata when publishing java component using `ivy-publish`

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3393]
Similar to #3331.

**Comment by jjohannes** [comment]
Also: provide an internal opt-in for publishing the metadata (both maven and ivy) in the publishing extension. See: https://github.com/gradle/gradle/pull/3349#discussion_r149314718

**Comment by bigdaz** [comment]
Note: map the 'status' value to an attribute in the published metadata

**Comment by bigdaz** [comment]
@melix Is this complete?

**Comment by melix** [comment]
Sir yes, Sir!

**Comment by bigdaz** [comment]
@melix You know there's a 'close' button on these issues, right?
