### ISSUE TITLE
Add sufficient test coverage for dependency resolution using Gradle module metadata

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3394]
This will likely involve converting all/most of the existing resolution tests to use the new metadata format. Testing of Ivy and Maven repository metadata should be secondary to testing Gradle metadata.

**Comment by jjohannes** [comment]
For this issue: Provide sufficient coverage for the initial version of using Gradle metadata in dependency resolution.

Create a **follow up issue** to improve the structure of all gradle/maven/ivy metadata tests. The follow up should be addressed before we make the new metadata the default (probably Gradle 5.0). That might include for example:
- Get rid of duplication
- Provide a test runner that tests all three different metadata implementations for test cases that should be covered by all three.

**Comment by bigdaz** [comment]
@melix Note that this includes resolution from both Ivy and Maven repositories. So you might want to do #3462 first, since the scope is a little smaller.

**Comment by jjohannes** [comment]
Check which tests are left to convert.

**Comment by bigdaz** [comment]
@jjohannes I think it's also worth considering what combinations of published metadata + experimental features we want to test. Then we have the new ability for the client to choose which metadata sources to use.

In our current coverage, I think we are checking the most important use cases:
1) Ivy descriptor and no Gradle descriptor + experimentFeatures off
2) Pom file and no Gradle descriptor + experimentFeatures off
3) Gradle metadata + Ivy file + experimentalFeatures on
4) Gradle metadata + Pom file + experimentalFeatures on

However there are important cases that should have at least _some_ coverage:
5) Pom file only or Ivy file only + experimentFeatures on: to verify that we can resolve from a Gradle 4.x repository with Gradle 5.x
6) Pom file only + experimentalFeatures on: to test optional dependency handling and BOM import
7) Mixed repository setups, like a POM file that declares a dependency on something that's found in a `.module` file. This is important since we treat dependencies declared in a POM file differently from a dependency declared in a build script. I think our coverage here is a little thin.

**Comment by jjohannes** [comment]
> 1. Pom file only or Ivy file only + experimentFeatures on: to verify that we can resolve from a Gradle 4.x repository with Gradle 5.x
> 2. Pom file only + experimentalFeatures on: to test optional dependency handling and BOM import

These will be added with #3697 (https://github.com/gradle/gradle/pull/3697/commits/ebbb18b38ad5df5ce1a734c6ccfb18821b89d597). I think we can accept the overhead of these additional test runs for _every_ test. To keep it simple and to stay prepared for 5.0. In 5.0 all the variations with _experimentFeatures off_ will go away and test runtime will go down again.

> 3. Mixed repository setups, ...

We have exactly one test for metadata rules, which produce metadata (e.g. newly added dependencies) _as if_ they originate from a `.module` file.
I think we should add more test coverage (maybe one test class with a couple of cases) explicitly for testing repository combinations.

**Comment by jjohannes** [comment]
I added a test for mixed repository setup: https://github.com/gradle/gradle/commit/a9a3c94b571bd55cf734f54d8c7e2840e01b3aee
Which is extended with more scenarios for the experimental case in #3360.

**Comment by jjohannes** [comment]
I think the coverage for _Gradle module metadata_ is sufficient for now.

I think we can and should still check existing tests and convert more to use the new fixtures if it makes sense. If only for the sake to make the tests more maintainable. I would however suggest to do this:
(1) By improving tests as we go. Always when we work on features, check/improve the related tests
(2) Go through our exiting coverage again later (before 5.0) - #3853
