### ISSUE TITLE
Gradle Module Metadata

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3395]
The existing Ivy and Maven metadata formats are insufficient to describe the variants and rich dependency information that is part of the Gradle software component model. A new, Gradle-specific metadata format will be used to allow the full model to be published, and to allow new dependency management features to be fully reflected int he publishing metadata.

Module metadata will be published alongside existing Ivy or Maven metadata files. Published `.pom` and `ivy.xml` files will contain a lossy mapping of the Gradle metadata model, and will be designed for consumers that cannot handle the new metadata format (eg Ivy, Maven, old versions of Gradle). 

Existing repository layouts will be used. There is no requirement for a new Gradle-only repository layout.

**Comment by ljacomet** [comment]
Closing as this was delivered and improved over the Gradle 6.x line
