### ISSUE TITLE
Possible improvements to 'strict versions' DSL

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3400]
I'm concerned that the DSL as it stands might be a bit too loose, allowing users to get confused. I'm not sure, but I want to have a conversation.

In the current DSL, the following is perfectly valid:
```
dependencies {
   compile("org:foo:3.3") {
        version {
           strictly "1.1"
           prefer "2.2"
        }
    }
}
```
In effect, the last setting overrides the previous 2. I wonder if it might be better to fail any attempt to override a previous version preference.

Also, there seems to be little test coverage of this behaviour. I think some more unit test coverage of the Dependencies DSL would be good. Possibly adding to `DefaultDependencyHandlerTest`, or direct test coverage for `MutableVersionConstraint`.

**Comment by melix** [comment]
I agree that better validation would be a good idea, but in practice I'm not sure how to implement that properly. In your example, we _could_ detect that both `strictly` and `prefer` are called within the same `version` block. This would imply wrapping the version constraint to capture the calls, it's doable.

But how to make the difference between the 2 cases:

- version is written in the dependency declaration, and overridden in a `version` block (case above)
- version constraint comes from a module definition, and is overridden in the DSL (to be clear this use case is not possible now, but will happen with metadata rules)

In both cases the dependency is represented the same way.

**Comment by bamboo** [comment]
> in practice I'm not sure how to implement that properly

Excuse my naiveté but would it be possible to just gather the data during `strictly` and `prefer` and then validate the accumulated data at once upon leaving `version`?

**Comment by melix** [comment]
It is, but how does it prevent from writing:

```
compile("org:foo:3.3") {
        version {
            prefer '3.4' // this is redundant with 3.3 above, it overrides the version
        }
}
```

or:
```
compile("org:foo") {
        version {
            prefer '3.3'
        }
        version {
            prefer '3.4'
        }
}
```
in general we don't handle such cases.

**Comment by bamboo** [comment]
Right. That would require pushing the validation up one layer.

**Comment by bigdaz** [comment]
I would rather not focus on how it would be implemented, but rather on the optimal behaviour. At this stage, I don't think we have a good use case for any of the above DSL examples. I would like to consider making it a failure to attempt to overwrite the version of an existing `Dependency`. We could allow the conversion of `prefer` to `strictly` for the same version, to permit:
```
compile("org:foo:3.3") {
        version {
            strictly '3.3'
        }
}
```
but prohibit:
```
compile("org:foo:3.3") {
        version {
            strictly '3.4'
        }
}
```

That will leave the question of how to deal with modifying the version constraint in the new `Configuration.withDependencies` method. I don't really like that we expose raw `Dependency` instances here, and so I'd propose that we switch to an API more like the one for modifying component metadata: https://github.com/gradle/gradle/blob/899f60db7e9dae03b4e2e4b430bc14be75b80e58/subprojects/core-api/src/main/java/org/gradle/api/artifacts/VariantMetadata.java#L36-L36. (Note that this API does not _yet_ support modifying the entire version constraint)

**Comment by bigdaz** [comment]
> But how to make the difference between the 2 cases:
> 
> - version is written in the dependency declaration, and overridden in a version block (case above)
> - version constraint comes from a module definition, and is overridden in the DSL (to be clear this use case is not possible now, but will happen with metadata rules)
> 
> In both cases the dependency is represented the same way.

The last statement is not correct. We have different representations of a dependency in the DSL and in a metadata rule.

**Comment by melix** [comment]
Alright so it we **do** have a separate thing, then validation can happen. Is this what you meant by "Unit test coverage for more dependency declarations, including various permutations of version= and version {}" ?

**Comment by melix** [comment]
Ok with my spike, the following doesn't work anymore:

```
configurations.compile.withDependencies { deps ->
    def bar = deps.find { it.name == 'bar' }
    assert bar.version == null
    bar.version { prefer '1.0' }
}
```
(found in https://github.com/melix/gradle/blob/0c909ded454e99e7766f032e1fecfa23832a5fb6/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/ConfigurationMutationIntegrationTest.groovy#L135)

It fails with:

> Can't set preferred version to 'null' because it's already set to '2.2'

So if we validate this, it means that we can't have a rule that would override versions set in different configurations, for example. Let's discuss.

**Comment by ljacomet** [comment]
This has been fixed and multiple version constraints can be expressed on a single dependency declaration.
