### ISSUE TITLE
Configuration.firstLevelDependencies may be wrong with version-range merging

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3401]
`Configuration.resolvedConfiguration.firstLevelDependencies` is not returning the correct values when a selected first-level dependency is removed due to version-range merging. See [here](https://github.com/gradle/gradle/pull/3305/files#r148766105) for a way to reproduce this issue.

There are 2 distinct problems I observed:

1. `ResolvedConfiguration.getFirstLevelModuleDependencies() != ResolvedConfiguration.getFirstLevelModuleDependencies({true})`: the former uses a different implementation to get the resolved dependencies.
2. Neither of these 2 return the expected result in the case of conflict resolution in the face of version range merging.

It appears that getFirstLevelDependencies() is omitting the conflict-resolved node altogether, and getFirstLevelDependencies({true}) is including the node, but with the wrong version.

**Comment by melix** [comment]
Closing as delivered
