### ISSUE TITLE
Delete empty package from build/classes in the incremental build if there are no class files left

### ISSUE THREAD

**Issue by udalov** [gradle/gradle#3405]
I have the simplest `build.gradle`:
```
apply plugin: "java"
```

With the single Java source file at `src/main/java/test/Test.java`:
```
package test;

public class Test {}
```

The project compiles successfully and the build produces the class file at `build/classes/java/main/test/Test.class`.

Now if I move this Java source file to `src/main/java/test2/` and update the package statement accordingly, the project also compiles successfully and there's a class file in the new package, but the old directory `build/classes/java/main/test` is not deleted, although it's now empty.

### Expected Behavior
I would expect that the package in the built classes is deleted as soon as all class files are deleted from it by the incremental build.

### Current Behavior
The package is not deleted. The empty directory is also present in the .jar generated by the jar task. (`gradle clean` fixes the problem, of course.)

### Context
In my case, I have a task that collects jars from several other projects and runs some post-processing to pack contents of those jars into a new jar with a custom code using `ZipOutputStream`. Now if I'm trying to move packages around between those projects and I'm using incremental build, the problem arises where I'm writing several entries with the same name into the `ZipOutputStream` (one is the directory with the actual classes in one project, and the other is the empty leftover directory from another project), which leads to an exception from `ZipOutputStream`.

(I understand that this is a minor issue and there are easy workarounds such as avoiding writing empty directories to the jar in my custom code.)

### Your Environment

Gradle 4.2.1, macOS 10.12.6

**Comment by wolfs** [comment]
@udalov Thank you for reporting this. I imagine that this issue is annoying. This is currently not on our high priority list to fix. I think it requires changes in incremental compilation and non-incremental compilation. I guess `SimpleStaleClassCleaner` would need to be updated.
Would you be willing to contribute a PR?
