### ISSUE TITLE
Resolve runtime variant of published java library where consuming configuration defines no attributes

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3407]
When `components.java` is published with Gradle module metadata, 2 variants are defined: 'api' and 'runtime'. This works fine when the library is consumed by configurations defined by the `java` plugin, since the appropriate attributes are set on the consumer. However in many cases a user will want to resolve those libraries as part of an arbitrary, custom configuration.

There are a few ways we could solve this:
1. Force consuming configurations to declare the appropriate "usage" attribute
2. Allow a published module to declare a 'default' variant.
3. Allow a published module to declare a 'default' value for an attribute.
4. Add a built-in compatibility rule to Gradle that chooses the 'runtime' variant over the 'api' variant.
5. When a variant can't be automatically selected from the module metadata, fall back to resolving via the published POM/Ivy file.

The problem with 1) is that it will likely be a serious impediment to adopting the new module metadata format as the default. Many/most builds out there will likely resolve an arbitrary configuration, as do many 3rd party plugins (as do our built-in plugins, but we can fix those).  

The problem with 2) & 3) is that they bind the published metadata to the notion of a default, when it's not really the producers responsibility to define this. For instance, which of "Linux" and "Windows" would be the default? Which of 'api', 'link', 'runtime', 'debug'. By choosing 'runtime' over 'api', the producer would be making a fairly arbitrary decision.

Option 5) seems pretty crappy to me: I left it in there for completeness

That leaves 4), or some variation thereof. Ideally the consuming build would apply a plugin to provide the java-style Usage compatibility rules, but to start with we could automatically apply that plugin on every build (or perhaps as part of the 'base' or even 'java-base' plugin).

**Comment by oehme** [comment]
> Add a built-in compatibility rule to Gradle that chooses the 'runtime' variant over the 'api' variant.

I think that's the way to go. It's a disambiguation rule though. It's already part of [java-base](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaBasePlugin.java#L520) and is just missing some catch-all when everything matches.

**Comment by bigdaz** [comment]
Thanks. The existing disambiguation rules from `java-base` aren't firing because we aren't creating strongly-typed `Usage` attributes when parsing `.module` files. Easy fix.

To start with, I think we could consider enabling module metadata consumption by default only when the `java-base` plugin is applied. This would be similar to what's happening in the [`CppBasePlugin`](https://github.com/gradle/gradle/blob/3239141271c4791ee21c6ccbbf8374b23f318d4a/subprojects/language-native/src/main/java/org/gradle/language/cpp/plugins/CppBasePlugin.java#L79-L85).

This would ensure that no-attribute configurations can resolve from maven repositories with and without the `java-base` plugin, and defer the question of what to do for consumers that aren't 'component-aware'.

**Comment by bigdaz** [comment]
And here's a quick spike of how a producer-side disambiguation rule could easily solve this: https://github.com/gradle/gradle/commit/f83051b208e6e586de973e7063d32aa5c6b54fdd

**Comment by oehme** [comment]
Sweet 👍
