### ISSUE TITLE
[4.3] - flatDir with Android AARs no longer work

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#3409]
## Description:
Bringing in local AAR file fails in `4.3`. Gradle treats it as a normal dependency and fails to resolve.

AGP: `2.3.3`
Gradle: `4.1/4.2`

## Repro:
```
repositories {
    flatDir { dirs("libs") }
}

dependencies {
    compile(name: "<dependency>", ext: "aar")
}
```

## Error:
```
$ gradlew
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve :<dependency>:.
     Required by:
         project :app
      > Could not resolve :<dependency>:.
         > Could not get resource <url>/<dependency>-.pom'.
            > Could not GET '<url>/<dependency>-.pom'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by bmuschko** [comment]
Hi Jared,

You are probably running into this situation: https://docs.gradle.org/current/release-notes.html#avoid-checking-other-repositories-when-dependency-resolution-in-one-repository-fails

We are working on a patch release (4.3.1) to be less aggressive. Could you try out your project with a snapshot of the 4.3.1 release? https://downloads.gradle.org/distributions-snapshots/gradle-4.3.1-20171107130851+0000-bin.zip

**Comment by jaredsburrows** [comment]
@bmuschko Thanks for your incredibly fast response. I will try that now.

**Comment by jaredsburrows** [comment]
@bmuschko `4.3.1` seems to fix this issue! Thanks!

**Comment by bmuschko** [comment]
Sweet, thanks for confirming!
