### ISSUE TITLE
Nested afterEvaluate() calls should not be silently ignored

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#3411]
### Current Behavior

Consider this code:

```gradle
afterEvaluate {
    println "Outer"
    afterEvaluate {
        println "Inner"
    }
}
```

This now prints:

```text
Outer
```

And the `Inner` part is silently ignored.

### Expected Behavior

There should be a clear warning saying that an `afterEvaluate {}` hook was added from another `afterEvaluate {}` hook, and that it has been ignored.

### Context

The `afterEvaluate {}` hook is used in a lot of ways to work around ordering problems, and it's easy to end up nesting two of them. Debugging such issues can be pretty hard.

**Comment by bamboo** [comment]
I wouldn't expect the hook to be ignored at all.

My mental model of `afterEvaluate` is that all requests will be satisfied asynchronously at some point just as the evaluation phase ends before the next phase beings.

I understand this might pose some implementation challenges but let's not settle for a warning without first evaluating the cost of honoring all the requests.

**Comment by lptr** [comment]
Good point, @bamboo. I remember bringing this question up a while back, and IIRC the answer back then was that there's a legitimate reason for not executing nested calls. That said, just executing them would also be a way to solve this issue.

**Comment by eskatos** [comment]
Just faced this while fighting with ordering problems.
Silently ignoring blocks of build logic is both surprising and nonsensical.
Gradle should either honor what the build author writes, or fail if it can't.

**Comment by bamboo** [comment]
Superseded by #5200.
