### ISSUE TITLE
Illegal character in opaque part being thrown using gradle version 4.3

### ISSUE THREAD

**Issue by HugGa** [gradle/gradle#3413]
So, essentially, I am running into this bug where I am unable to compile using the newest version of gradle, and only the versions past 4.2 seem to have this bug as far as I have tested.
### Expected Behavior
What should happen is that I should have a build that passes this point and will allow me to use the exported dependencies

### Current Behavior
My current behavior seems to be getting a "Java.net.URISyntaxException: Illegal character in opaque part at index 6: value: ..."
### Context
I cannot attempt to build using gradle version 4.3 the project that you will see in the steps to reproduce
### Steps to Reproduce (for bugs)
As far as I have tested, the steps I took to reproduce has been the following:
download allwpilib (from: https://github.com/wpilibsuite/allwpilib/)
Set gradle wrapper to version 4.3 (or latest)
Do ./gradlew tasks

### My Environment
 * Build scan URL: https://scans.gradle.com/s/nwox54e4jbdbm (yes, I recognise that the scan was applied after, but I do not think that it matters much here, as it still captured the relevant information)

Thank you for your time

**Comment by oehme** [comment]
@lacasseio Since this seems to be a native regression in 4.3, could you take a look at this?

**Comment by big-guy** [comment]
@HugGa I think you're running into a change introduced in 4.3: https://docs.gradle.org/current/release-notes.html#changes-to-incubating-native-compile-and-link-tasks

I opened an issue in the plugin's project: https://github.com/wpilibsuite/native-utils/issues/4

**Comment by HugGa** [comment]
I have no idea where this change comes from, but it does seem to me that that might be a cause, shall I close this issue?

**Comment by big-guy** [comment]
Based on the reply: https://github.com/wpilibsuite/native-utils/issues/4#issuecomment-343370344,  they plan to keep the plugin compatible with Gradle 4.1, so you won't be able to use Gradle 4.3 with it.

**Comment by jeanse7en** [comment]
Actually, it's big problem where you put your server. 
I already faced this problem before, I used Geronimo with the space in my direction D:\Common DevTool\Geronimo.
Have 2 ways to resolve
1.  change to D:\Tool\Geronimo, it ran well.
Your directory is not correct, C:/Program Files, You should move your server to another place without space in name. 
2. Upgrade the jsf version.
Hope that my answer can help you
