### ISSUE TITLE
unable to create a parent section of the pom, with maven plugin

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#3414]
this is about generating a pom, not importing one.

### Expected Behavior

the generated pom should also contain this
```
  <parent>
    <groupId>io.spring.platform</groupId>
    <artifactId>platform-bom</artifactId>
    <version>Brussels-SR5</version>
  </parent>
```

### Current Behavior

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.xenoterracide</groupId>
  <artifactId>bom</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <properties>
    <jcabi-matchers.version>1.3</jcabi-matchers.version>
    <s3mock.version>0.2.2</s3mock.version>
    <mbassador.version>1.3.1</mbassador.version>
    <tika.version>1.15</tika.version>
    <aws.version>1.11.207</aws.version>
    <immutables.version>2.5.5</immutables.version>
    <assertj.version>3.8.0</assertj.version>
    <slf4j-test.version>1.1.0</slf4j-test.version>
    <equalsverifier.version>2.3.3</equalsverifier.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>nl.jqno.equalsverifier</groupId>
        <artifactId>equalsverifier</artifactId>
        <version>${equalsverifier.version}</version>
      </dependency>
      <dependency>
        <groupId>net.engio</groupId>
        <artifactId>mbassador</artifactId>
        <version>${mbassador.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.tika</groupId>
        <artifactId>tika-core</artifactId>
        <version>${tika.version}</version>
      </dependency>
      <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>builder</artifactId>
        <version>${immutables.version}</version>
      </dependency>
      <dependency>
        <groupId>org.immutables</groupId>
        <artifactId>value</artifactId>
        <version>${immutables.version}</version>
      </dependency>
      <dependency>
        <groupId>io.findify</groupId>
        <artifactId>s3mock_2.12</artifactId>
        <version>${s3mock.version}</version>
      </dependency>
      <dependency>
        <groupId>com.jcabi</groupId>
        <artifactId>jcabi-matchers</artifactId>
        <version>${jcabi-matchers.version}</version>
      </dependency>
      <dependency>
        <groupId>uk.org.lidalia</groupId>
        <artifactId>slf4j-test</artifactId>
        <version>${slf4j-test.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

### Context

I'm trying to programatically generate a pom for dependency management. As far as I know, gradle without a BOM support has no similar concept, and obviously I'm using the Spring BOM for a parent here. One of the problems I encountered with the Spring Gradle plugin was if I didn't use my parent to extend it my properties didn't affect it. So assertj.version was not overridden.

### Steps to Reproduce (for bugs)

here's the basic code, [forum post](https://discuss.gradle.org/t/generating-a-bom-with-gradle/24679), and the [full source](https://bitbucket.org/xenworks/bom/commits/4e8a2c5c2f27d7d88decc862b046c3788cfda561) which doesn't include the parent section, because it doesn't work (doesn't fail either, just doesn't include the section).

```
group 'com.xenoterracide'
version '0.1.0-SNAPSHOT'

repositories {
    maven {
        url System.getenv('JAR_REPOSITORY_URI')
    }
    jcenter()
}

apply plugin: 'maven-publish'
apply plugin: 'maven'


publishing {
    repositories {
        maven {
            url System.getenv('JRS_S3_URI')
            credentials(AwsCredentials) {
                accessKey System.getenv('JRS_ACCESSKEYID')
                secretKey System.getenv('JRS_SECRETACCESSKEY')
            }
        }
    }
    publications {
        maven(MavenPublication) {
            pom.withXml {
                def sb = asString()
                sb.setLength 0
                sb.append  file( "$buildDir/bom.pom" ).text
                println( sb.toString() )
            }
        }
    }
}

build.doFirst {
    pom {
        project {
            parent {
                groupId 'io.spring.platform'
                artifactId 'platform-bom'
                version 'Brussels-SR5'
            }
            packaging 'pom'
            properties {
                equalsverifier   version: "2.3.3"
                mbassador        version: "1.3.1"
                tika             version: "1.15"
                immutables       version: "2.5.5"
                assertj          version: "3.8.0"
                s3mock           version: "0.2.2"
                aws              version: "1.11.207"
                "slf4j-test"     version: "1.1.0"
                "jcabi-matchers" version: "1.3"
            }
            dependencyManagement {
                dependencies {
                    dependency 'nl.jqno.equalsverifier:equalsverifier:${equalsverifier.version}'
                    dependency 'net.engio:mbassador:${mbassador.version}'
                    dependency 'org.apache.tika:tika-core:${tika.version}'
                    dependency 'org.immutables:builder:${immutables.version}'
                    dependency 'org.immutables:value:${immutables.version}'
                    dependency 'io.findify:s3mock_2.12:${s3mock.version}'
                    dependency 'com.jcabi:jcabi-matchers:${jcabi-matchers.version}'
                    dependency 'uk.org.lidalia:slf4j-test:${slf4j-test.version}'
                }
            }
            licenses {
                license {
                    name 'The Apache Software License, Version 2.0'
                    url 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    distribution 'repo'
                }
            }

        }
    }.writeTo("$buildDir/bom.pom")
}
```
### Your Environment
consistent on windows, with intellij, and gradlew 4.3, and wercker (docker container)

**Comment by jjohannes** [comment]
@xenoterracide I tried out your example. I can not reproduce the issue with Gradle 4.3. The `<parent>` section is included for me.
Might there be something else in your actual project causing this? Is there maybe something else named `parent` in you build script that could cause the unexpected behavior?

**Comment by oehme** [comment]
The script above has several problems, for instance:

- don't mix `maven` and `maven-publish`
- don't use `build.doLast {}` if you want to modify a POM, `build` is just one task of many and not always executed. Instead add this logic where you actually need it, in the `pom.withXml {}` hook.

I think asking for help on the forum on how to do this using the current APIs is best.

In general, I think we should have a strongly typed POM API in the `maven-publish` plugin to make this easier. This is already tracked by https://github.com/gradle/gradle/issues/3348. I'm closing this as a duplicate.

**Comment by xenoterracide** [comment]
>  I tried out your example. I can not reproduce the issue with Gradle 4.3. The <parent> section is included for me.

hmm... I'm going to have to look further, maybe something is cached somewhere locally? I edited my source and it seems to be working on wercker now, strange. Guess I'll chalk it up to me being an idiot or something weird in my local windows environment (can't check that atm)

> I think asking for help on the forum on how to do this using the current APIs is best.

I did, and Stackoverflow 24 hours before that

> here's the basic code, forum post, and the full source which doesn't include the parent section,

> don't mix maven and maven-publish

didn't find another way to publish to s3 than with maven-publish

>don't use build.doLast {} if you want to modify a POM, build is just one task of many and not always executed. Instead add this logic where you actually need it, in the pom.withXml {} hook.

seems that publish only runs if build has run, and since this is a BOM that I'm building, and the artifact type is "pom" this seemed the only way to get it to build something that could be published. I could be wrong about this, am a n00b when it comes to gradle. though from what you've said what I'm trying to do is currently not possible with only 1 plugin ( mean it is, if I craft the xml manually).
