### ISSUE TITLE
Deprecate `Convention` concept

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#3425]
### Expected Behavior

The `Convention` concept should be deprecated for removal. A deprecation message is rendered when accessing the `Convention` through the `Project` API. 

There's a usability issue here. Builds that use plugins configuring Gradle core plugins through `Convention` would always render the deprecation warning. Users and plugin authors cannot fix this by switching to a different API. Potentially this situation could be mitigated by implementing https://github.com/gradle/gradle/issues/3332. Alternatively, we should probably not render a deprecation warning at all.

### Current Behavior

Conventions are used by Gradle core plugins. Users (more specifically plugin authors) have to use a cumbersome API to access convention values. For example:

```
JavaPluginConvention javaConvention = project.getConvention().getPlugin(JavaPluginConvention.class);
SourceSet main = javaConvention.getSourceSets().getByName(SourceSet.MAIN_SOURCE_SET_NAME);
```

### Context

`Convention` is a legacy concept and has been effectively been replaced by extensions. Some Gradle core plugins still use this concept and should be migrated to extensions in the long run. `Convention` should be deprecated.

**Comment by bmuschko** [comment]
@oehme Any idea on how to tackle the deprecation message issue described above? I don't actually expect a lot of users to create their own `Convention`. Maybe we can just not add a deprecation warning via the logger but instead just add a deprecation annotation to `Project.getConvention()`.

**Comment by adammurdoch** [comment]
We shouldn't do something ad hoc here for deprecation warnings. We should do whatever we do everywhere else (and make that "whatever" better).

**Comment by oehme** [comment]
We shouldn't be deprecating as long as they are the only way to do certain things, like defining custom source set types. Once that is done, we deprecate like everything else.

**Comment by JLLeitschuh** [comment]
The Kotlin plugin defines a custom `Configuration` as well.

**Comment by grv87** [comment]
I use `Convention` in my internal plugin, it provides nice DSL like
```
publicReleases = false
license = 'Apache-2.0'
tags = ['super', 'cool', 'project']
```
Replacing convention with extension I would have to use extra block in each build script, which is not nice.
I could use Groovy's `metaClass` as a replacement, but it would complicate setting up this new DSL.
So, if this is open for discussion, I would vote against removing `Convention`.

**Comment by oehme** [comment]
The point is exactly to have an extra block to reduce the clutter on the Project API. It makes it much clearer what you are configuring. Please never use Groovy metaclass, as that makes your plugin unusable from Kotlin.

**Comment by eskatos** [comment]
I think we still want to do that

**Comment by big-guy** [comment]
@eskatos is this something that would be helpful with configuration caching?

**Comment by eskatos** [comment]
@big-guy Not really. It is mostly helpful because extensions are a better replacement and for good Kotlin DSL support.

**Comment by donat** [comment]
We have the following conventions in the codebase:
- ApplicationPluginConvention
- JavaPluginConvention
- BasePluginConvention
- DefaultGroovySourceSet 
- ProjectReportsPluginConvention
- WarPluginConvention
- AntlrSourceVirtualDirectory
- ScalaSourceSet

Before we can deprecate the concept of conventions we need to make sure that properties stored in a convention are also available as an extension.

**Comment by ljacomet** [comment]
🎉 This is in for Gradle 7.1!
