### ISSUE TITLE
Continuous build responsiveness is too slow on mac

### ISSUE THREAD

**Issue by nedtwigg** [gradle/gradle#3427]
### Expected Behavior

Using `gulp` in watch mode, it takes milliseconds for a change in a sass file to be compiled to css and displayed in the browser using livereload.

### Current Behavior

This same workflow in Gradle has a delay of multiple seconds on a mac.  Most of it is outside of Gradle's control, thanks to [JDK-7133447](https://bugs.openjdk.java.net/browse/JDK-7133447), but it appears that a [little of it](https://github.com/gradle/gradle/commit/41b5087c596244bdf41f37b204665f5f81383331) might be self-induced.

### Context

Thanks to the fantastic [gradle-node-plugin](https://github.com/srs/gradle-node-plugin) by @srs, all of the great web frontend tooling is easily accessible to gradle.  Unfortunately, because Gradle's latency is so much longer than gulp's it is noticably worse for design tasks.

[jpathwatch](https://bitbucket.org/atlassian/atlassian-jpathwatch) provides a workaround for mac, and [sfmf4j](http://sworisbreathing.github.io/sfmf4j/implementation-features.html) provides a facade over `WatchService` and `jpathwatch`.

### Your Environment

The problem is most severe on mac, which happens to be the most popular OS for hipster web devs.

**Comment by wolfs** [comment]
The responsiveness will also be fixed when using the file watching provided by `native-platform`, as suggested by https://github.com/gradle/gradle/issues/11834.

**Comment by graemerocher** [comment]
Any news?

**Comment by wolfs** [comment]
@graemerocher This will be in Gradle 7.5.

**Comment by graemerocher** [comment]
Awesome news. Thanks!
