### ISSUE TITLE
Execution failed for task ':clean' after gradle upgraded from 3.5.1 to 4.3.1

### ISSUE THREAD

**Issue by danielsun1106** [gradle/gradle#3437]
### Expected Behavior

Execute task ':clean' successfully.

### Current Behavior

Execution failed for task ':clean'  because of the error `Caused by: org.gradle.api.file.UnableToDeleteFileException: Unable to delete file: D:\_APPS\git_apps\groovy\target\libs\groovy-3.0.0-SNAPSHOT.jar`  ( BTW, sometimes the file failed to delete is `D:\_APPS\git_apps\groovy\target\bootstrap\groovy-3.0.0-SNAPSHOT-bootstrap.jar` )

### Context

We fail to continue run `gradlew clean dist`, no workaround found yet...

### Steps to Reproduce (for bugs)

1. clone https://github.com/apache/groovy.git
2. run `gradlew clean dist`  (BTW, `gradlew dist` fails as well)
3. get the error `FAILURE: Build failed with an exception.`, i.e. `org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':clean'`

### Your Environment

Win10, Java 8, Gradle 4.3.1
 * Build scan URL:  https://gradle.com/s/dx7bxzoe5tpmg

**Comment by bmuschko** [comment]
Is there a reason why you even need to run the `clean` task? Usually you don't need to do so. Gradle will figure out necessary changes for you.

**Comment by danielsun1106** [comment]
Even if we do not run clean task,  dist task fails with same reason because clean task will run automatically.

**Comment by bmuschko** [comment]
@danielsun1106 I am bit confused. What exactly makes the `clean` task run? Does one of your tasks depend on the `clean` task?

**Comment by danielsun1106** [comment]
@bmuschko As you see, dist task(https://github.com/apache/groovy/blob/master/gradle/assemble.gradle#L644) does not depend on the `clean` task. 

P.S. even if I search all gradle script files, only one `clean` task found: https://github.com/apache/groovy/blob/master/subprojects/performance/build.gradle#L45

**Comment by bmuschko** [comment]
I'd try to remove the line https://github.com/apache/groovy/blob/master/subprojects/performance/build.gradle#L45. I see no reason why you should run `clean` here.

@melix Do you have any background information on this?

**Comment by danielsun1106** [comment]
@bmuschko @melix  `gradlew clean dist` runs well on CentOS 7, but fails on Win10

**Comment by danielsun1106** [comment]
4.4-rc-2 has the same issue:
```
java.io.IOException: Unable to delete file: D:\_APPS\git_apps\groovy\target\bootstrap\groovy-3.0.0-SNAPSHOT-bootstrap.jar
> Unable to delete file: D:\_APPS\git_apps\groovy\target\bootstrap\groovy-3.0.0-SNAPSHOT-bootstrap.jar
```

**Comment by danielsun1106** [comment]
After @melix improved the build of Groovy, the issue is gone :-)
