### ISSUE TITLE
Make `ResolutionStrategy.preferProjectModules()` the default

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3449]
When you include a project component in the graph, make it win over all module components. Not sure if we'd need a way to disable this.

**Comment by jjohannes** [comment]
Related: https://github.com/gradle/gradle/issues/1629 (could be a use case for `doNotUseProjectModules()`)

**Comment by bigdaz** [comment]
We won't be making this change for 5.0. Might want to consider again for 6.0.
We'll need to address #5076 before making this the default.

**Comment by jjohannes** [comment]
There is no clear use case for making this (breaking) change.
