### ISSUE TITLE
After every incremental build, spring-boot-gradle-plugin modifies Spring Boot executable jarfile, even with no input (code) changes.

### ISSUE THREAD

**Issue by derekmahar** [gradle/gradle#3452]
### Expected Behavior

After first Gradle build and given no input changes or any other project changes, `spring-boot-gradle-plugin` should **not** modify the Spring Boot executable jarfile.

### Current Behavior

After every incremental build, [`spring-boot-gradle-plugin`](https://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-gradle-plugin.html) `1.5.8.RELEASE` modifies the Spring Boot executable jarfile, even with no changes to the source code or other build dependencies.
An incremental build should not touch any build artefact when there are no project changes.

### Context

- Increases build time due to unnecessary re-generation of build artefacts.
- Increases deployment to run time environment because deployment script unnecessarily transmits build artefacts that are functionally identical to existing artefacts.

### Steps to Reproduce (for bugs)

1. Build a project that uses the spring-boot-gradle-plugin.  Note the time stamp of the Spring Boot executable jarfile and time stamps of Spring Boot artefacts inside the jarfile.
2.  Without making any changes to the project, build the project again and note that the executable jarfile time stamp has changed as well as the time stamps of Spring Boot artefacts inside the jarfile:

```
derek@derek-lubuntu:~/Projects/fire$ diff accounts-backend.jar.1.txt accounts-backend.jar.2.txt 
1,4c1,4
<      0 Fri Nov 10 12:30:36 EST 2017 META-INF/
<    268 Fri Nov 10 12:30:36 EST 2017 META-INF/MANIFEST.MF
<      0 Fri Nov 10 12:30:36 EST 2017 BOOT-INF/
<      0 Fri Nov 10 12:30:36 EST 2017 BOOT-INF/classes/
---
>      0 Fri Nov 10 12:47:38 EST 2017 META-INF/
>    268 Fri Nov 10 12:47:38 EST 2017 META-INF/MANIFEST.MF
>      0 Fri Nov 10 12:47:38 EST 2017 BOOT-INF/
>      0 Fri Nov 10 12:47:38 EST 2017 BOOT-INF/classes/
46c46
<      0 Fri Nov 10 12:30:36 EST 2017 BOOT-INF/lib/
---
>      0 Fri Nov 10 12:47:38 EST 2017 BOOT-INF/lib/
180,183c180,183
<      0 Fri Nov 10 12:30:36 EST 2017 org/
<      0 Fri Nov 10 12:30:36 EST 2017 org/springframework/
<      0 Fri Nov 10 12:30:36 EST 2017 org/springframework/boot/
<      0 Fri Nov 10 12:30:36 EST 2017 org/springframework/boot/loader/
---
>      0 Fri Nov 10 12:47:38 EST 2017 org/
>      0 Fri Nov 10 12:47:38 EST 2017 org/springframework/
>      0 Fri Nov 10 12:47:38 EST 2017 org/springframework/boot/
>      0 Fri Nov 10 12:47:38 EST 2017 org/springframework/boot/loader/
189c189
<      0 Fri Nov 10 12:30:36 EST 2017 org/springframework/boot/loader/jar/
---
>      0 Fri Nov 10 12:47:38 EST 2017 org/springframework/boot/loader/jar/
212c212
<      0 Fri Nov 10 12:30:36 EST 2017 org/springframework/boot/loader/data/
---
>      0 Fri Nov 10 12:47:38 EST 2017 org/springframework/boot/loader/data/
225c225
<      0 Fri Nov 10 12:30:36 EST 2017 org/springframework/boot/loader/archive/
---
>      0 Fri Nov 10 12:47:38 EST 2017 org/springframework/boot/loader/archive/
238c238
<      0 Fri Nov 10 12:30:36 EST 2017 org/springframework/boot/loader/util/
---
>      0 Fri Nov 10 12:47:38 EST 2017 org/springframework/boot/loader/util/
```

### Your Environment

 * Build scan URL: https://gradle.com/s/2lyisnjrx3jmo

```
derek@derek-lubuntu:~/Projects/fire/accounts/backend$ gradle --version

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.4.0-97-generic amd64
```

**Comment by mkobit** [comment]
What happens if you specify a classifier and run the build multiple times? This might be the same issue from https://github.com/spring-projects/spring-boot/issues/1113

```groovy
bootRepackage  {
    classifier = 'exec'
}
```

**Comment by derekmahar** [comment]
@mkobit, yes, adding a `classifier` to the `bootRepackage` block does prevent `spring-boot-gradle-plugin` from touching the Spring Boot jarfile:

```
derek@derek-lubuntu:~/Projects/fire/accounts/backend$ ls -la build/libs/backend.jar
-rw-rw-r-- 1 derek derek 52381 Nov 13 10:26 build/libs/backend.jar
derek@derek-lubuntu:~/Projects/fire/accounts/backend$ gradle build -x test

> Task :accounts:backend:bootRepackage UP-TO-DATE
Using TaskInputs.file() with something that doesn't resolve to a File object has been deprecated and is scheduled to be removed in Gradle 5.0. Use TaskInputs.files() instead.


BUILD SUCCESSFUL in 2s
11 actionable tasks: 1 executed, 10 up-to-date
derek@derek-lubuntu:~/Projects/fire/accounts/backend$ ls -la build/libs/backend.jar
-rw-rw-r-- 1 derek derek 52381 Nov 13 10:26 build/libs/backend.jar
```

Note that the time stamp and size of `backend.jar` are the same before and after repeating the Gradle build.

**Comment by oehme** [comment]
This is a bug in the Spring boot plugin, which I think will be fixed in the upcoming 2.0 version of that plugin.

**Comment by derekmahar** [comment]
@oehme, does `spring-boot-gradle-plugin` have a separate Github project where I may find a report for this bug or report it to their team?

**Comment by derekmahar** [comment]
I found [`spring-boot-gradle-plugin`](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin).
