### ISSUE TITLE
Problem setting up Gradle for Eclipse.

### ISSUE THREAD

**Issue by wcdeich4** [gradle/gradle#3453]
I setup Eclipse Oxygen on Windos 7, and followed the Gradle install instructions, created the environment variables & added the Buildship Gradle Integration 2.0 plugin to Eclipse.  But when I try to create a new Gradle Project & click "Finish" nothing happens - even the dialog box does not close until I click "Cancel".  Any idea what I am doing wrong?

**Comment by bmuschko** [comment]
How does your build script look like? What Gradle tasks are you running?

**Comment by bmuschko** [comment]
@donat Do you have an idea what might be happening here?

**Comment by wcdeich4** [comment]
I downloaded the Eclipse Oxygen zip package.  I thought I had to install Gradle on the laptop separately & c reeate JAVA_HOME & GRADLE_Home environment variables.  I also installed Spring Tool Suite & reinstalled Buildship Gradle Integration 2.0 thru the Eclipse Marketplace.  
 

![gradlefailure](https://user-images.githubusercontent.com/12387531/32693403-9ff77d7e-c6f8-11e7-9838-461d086c2313.PNG)  

When I click the "Finish" button the dialog box does not close.  The dialog box never closes until I click "Cancel"

**Comment by donat** [comment]
@wcdeich4 The root cause might be that your Eclipse is running on Java 9, which is not supported by the latest release. We fixed the problem in the latest 2.2 [milestone](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md) and we'll soon publish the release.

In any case, you should be able to find a stack trace in the Gradle console: 
<img width="584" alt="screen shot 2017-11-06 at 22 51 16" src="https://user-images.githubusercontent.com/419883/32446897-5fe6cd9a-c345-11e7-8c66-04b944afc996.png">

**Comment by wcdeich4** [comment]
Thank you.  After reinstalling Eclipse with the executable installer like @bmbaisch & downgrading to java 1.8 like @donat said, and re setting up the JAVA_HOME & GRADLE_HOME windows environment variables & manually overriding the settings in Eclipse... I was finally able to create a new Gradle Project in Eclipse inside a Windows 7 virtual machine.

BTW, I used to be a .NET developer until business needs pushed me into Java.  I have to say, it is hard to get used to such a heterogeneous environment where you depend on 3rd parties for really basic things, like dependency injection & things can suddenly stop working b/c Oracle did something to Java that broke the Gradle's.  I'm not saying it's your fault, I'm just saying, after using .NET where most everything you need is build in by Microsoft & if you chose to use 3rd party dependencies, the core system never depends on them - it's quite a shock dealing with Java.  Sorry;  just had to get that off my chest.
