### ISSUE TITLE
Provide an opt-in for Maven optional dependencies support for Gradle 4.x

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3458]

**Comment by Vampire** [comment]
Was this done or rejected?

**Comment by jjohannes** [comment]
@Vampire consuming optional dependencies is in 4.6 as opt-in. See for example: https://github.com/gradle/gradle/issues/1253#issuecomment-365625205. You can give it a try with 4.6 RC2.

**Comment by Vampire** [comment]
Ah, ok, thanks, maybe you should change the milestone then though.
This issue is in milestone `4.4 RC1` which made me think it is included already.

**Comment by jjohannes** [comment]
Thanks I missed that. This should not have had any milestone when it was closed.
