### ISSUE TITLE
Maven repo URL is outdated

### ISSUE THREAD

**Issue by kbarrette** [gradle/gradle#3463]
The Maven plugin uses an outdated repo URL. This has started causing problems as the SSL cert for the outdated URL is incorrect.

The recommended URL for the Maven repository is https://repo.maven.apache.org/maven2/ - see 
https://maven.apache.org/repository/

**Comment by bmuschko** [comment]
Thanks for reporting. Sonatype is working on a fix right now: https://issues.sonatype.org/browse/MVNCENTRAL-2870. Nevertheless, Gradle should use the URL for Maven Central that's recommended by Sonatype.

**Comment by jvasallo** [comment]
Working on MR now! 👍  First PR to Gradle so would need some review.

**Comment by bmuschko** [comment]
@kbarrette Could you point me to the piece of Maven documentation that states the canonical repo URL? I do not see it in the link you provided.

**Comment by kbarrette** [comment]
@bmuschko terribly, it's in the image map - "central CDN" in the central block.

**Comment by bmuschko** [comment]
@kbarrette Thanks, I would have never found it. ;-)

**Comment by kbarrette** [comment]
No problem - I would have submitted a PR, but for a one-line change like this, filling out the licensing release, etc seemed a bit heavy-weight :)

**Comment by JLLeitschuh** [comment]
Should this fix get backported to previous major release numbers as well?

**Comment by bmuschko** [comment]
@JLLeitschuh I don't think we'll backport this change. `repo1.maven.org` is back in commission and should work as before. Any build stuck on an older version of Gradle can still use the canonical Maven repo URL by spelling it out via `maven { url 'https://repo.maven.apache.org/maven2/' }` instead of using the `mavenCentral()` shortcut if needed.

**Comment by twogee** [comment]
This is what Sonatype says at http://central.sonatype.org/pages/consumers.html

The canonical URLs for accessing Central are
    HTTP: http://repo1.maven.org/maven2
    HTTPS: https://repo1.maven.org/maven2

**Comment by bmuschko** [comment]
@twogee This is what the official Maven documentation says:

https://maven.apache.org/guides/mini/guide-mirror-settings.html

> Note: The official Maven 2 repository is at `http://repo.maven.apache.org/maven2` hosted in the US, or `http://uk.maven.org/maven2` hosted in the UK.

The Sonatype docs might be outdated.

**Comment by twogee** [comment]
Just picking the nit: Sonatype docs say "canonical", Maven docs say "official" 😄
