### ISSUE TITLE
Normalize version selectors when publishing to module metadata

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3466]
Currently, Gradle allows a wide range of version strings to be declared, published and consumed. There are a number of issues with version selector strings as they now stand:

- They are largely opaque to Gradle: only the `VersionSelectorScheme` really knows how to interpret them. This means that it's hard to perform simple operations on these version strings.
- They are published and consumed unmodified, which means that we publish invalid version strings to Maven POM files, like `1.+`.
- The version strings depend on an implicit version ordering, and this ordering is not particularly well defined or documented: #1872, #2017, #1218
- Many formats have vague and not-very-useful definitions:
    - `1.2+` performs basic string matching on the version, and has no semantic knowledge of version parts
    - `[1.0, 2.0)` will include `2.0-beta-1` in the range, so it's not an exact equivalent to `1.+`
    - `latest.<status>` encodes the status selector with the version selector, but otherwise is the equivalent to `+`.
    - No other range selectors permit a status selector.

In the lead up to Gradle 5.0 it would be good to address some of these limitations. We could force users not to use certain syntax (like `1+`) if they want to publish to Gradle metadata. Or we could allow the publishing of an opaque (deprecated) version string, but prevent the use of new features like `strictly` and `reject` with these version strings. Either of these mechanisms could be used to migrate users toward a more consistent, more well-defined version selector syntax.

With Gradle 5.0 it might be worth introducing some minor breaking changes, like ensuring that exclusive version ranges behave as expected when pre-release versions are involved.

See also : https://github.com/gradle/gradle/pull/3440#discussion_r150645469

**Comment by grv87** [comment]
Issue on documentation: #5603

**Comment by ljacomet** [comment]
This is obsolete and some of the intended feature are offered via [publication of resolved versions](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies)
