### ISSUE TITLE
Verify that artifacts are not re-downloaded after change to Maven central URL

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3467]

**Comment by bmuschko** [comment]
Here's how I verified that artifacts are **not** re-downloaded:

1. Build a new distribution of Gradle on my local machine that uses `https://repo.maven.apache.org/maven2/`.
2. Set up a new build script with the following content:

```
apply plugin: 'base'

configurations {
    myConf
}

repositories {
    mavenCentral()
}

dependencies {
    myConf 'commons-lang:commons-lang:2.5'
}

task copyLibs(type: Copy) {
    from configurations.myConf
    into "$buildDir/libs"
}
```

3. Delete `~/.m2` and `~/.gradle` to ensure a fresh Gradle user home and no potential references to existing artifacts in Maven Local.
4. Execute the build in 2. with Gradle 4.3.1 via `gradle cleanCopyLibs copyLibs -i`. Gradle downloads the artifacts:

```
:copyLibs (Thread[Daemon worker,5,main]) started.
Download https://repo1.maven.org/maven2/commons-lang/commons-lang/2.5/commons-lang-2.5.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/12/commons-parent-12.pom
Download https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
Download https://repo1.maven.org/maven2/commons-lang/commons-lang/2.5/commons-lang-2.5.jar
```

5. Execute the build in 2. with the local Gradle distribution via `gradle cleanCopyLibs copyLibs -i`. Gradle finds the already downloaded artifacts in the cache:

```
Found locally available resource with matching checksum: [https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.5/commons-lang-2.5.pom, /Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/4fca8db5890f26627b09ab48d8888256ccb38dbb/commons-lang-2.5.pom]
Found locally available resource with matching checksum: [https://repo.maven.apache.org/maven2/org/apache/commons/commons-parent/12/commons-parent-12.pom, /Users/bmuschko/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-parent/12/cc649b3f6671ff0e0ad57304441e0a5d2610db73/commons-parent-12.pom]
Found locally available resource with matching checksum: [https://repo.maven.apache.org/maven2/org/apache/apache/4/apache-4.pom, /Users/bmuschko/.gradle/caches/modules-2/files-2.1/org.apache/apache/4/602b647986c1d24301bc3d70e5923696bc7f1401/apache-4.pom]
Creating new cache for metadata-2.36/module-artifact, path /Users/bmuschko/.gradle/caches/modules-2/metadata-2.36/module-artifact.bin, access org.gradle.cache.internal.DefaultCacheAccess@4e01c85a
Found locally available resource with matching checksum: [https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.5/commons-lang-2.5.jar, /Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/b0236b252e86419eef20c31a44579d2aee2f0a69/commons-lang-2.5.jar]
```

**Comment by oehme** [comment]
There should be an integration test for this if we don't have one already.

**Comment by bigdaz** [comment]
There is both [integration test coverage](https://github.com/gradle/gradle/tree/2019777707cdf8d100cdf0fe6f78c67db372f740/subprojects/dependency-management/src/crossVersionTest/groovy/org/gradle/integtests/resolve/artifactreuse) and [documentation](https://docs.gradle.org/current/userguide/dependency_management.html#sub:cache_artifact_reuse) of this feature. But for some reason it's not trusted or understood, and we continue to get unconfirmed reports like this from @melix:
> I think we have something supposed to reuse artifacts, but I've seen it failing multiple times in practice
