### ISSUE TITLE
Running ./gradlew wrapper overwrites the distribution URL from all.zip  to bin.zip

### ISSUE THREAD

**Issue by mvysny** [gradle/gradle#3470]
Running `./gradlew wrapper --gradle-version 4.3.1` on any project (you can quickly try https://github.com/mvysny/karibu-dsl ) will always change `gradle/wrapper/gradle-wrapper.properties` `distributionUrl` from `gradle-x.y.z-all.zip` to `gradle-4.3.1-bin.zip` (changes `all` to `bin`).

### Expected Behavior
The wrapper plugin should recognize that I'm using gradle distro with sources and should preserve the `all` classifier.

### Current Behavior
The wrapper plugin overwrites entire `.properties` file and always changes the URL classifier from `all` to `bin`

### Steps to Reproduce (for bugs)
```bash
git clone https://github.com/mvysny/karibu-dsl
cd karibu-dsl
./gradlew wrapper --gradle-version 4.2.1
```

### Your Environment
Should be reproducible in any environment.

**Comment by blindpirate** [comment]
Thanks for reporting. You can use `--distribution-type` to specify the distribution type. See https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:wrapper_generation for more details.

**Comment by bamboo** [comment]
@blindpirate Even though `--distribution-type` is available I think there's still merit to the idea of making the wrapper task smarter and preserve the distribution type when only `--gradle-version` is given.

**Comment by blindpirate** [comment]
@bamboo OK, let's keep it open.

**Comment by big-guy** [comment]
It's not quite the same, but you can set the distribution type in the build script, so the wrapper task will always use the `all` distribution:
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html#org.gradle.api.tasks.wrapper.Wrapper:distributionType

```
wrapper {
   distributionType = "all"
}
```

**Comment by oehme** [comment]
Closing, as @big-guy's answer is the recommended way to ensure a distribution type in your project.
