### ISSUE TITLE
the library's library's api can't be used after I update gradle to 4.1

### ISSUE THREAD

**Issue by Mao-x-w** [gradle/gradle#3471]
After I update Android Studio to 3.0,at sametime,I update gradle to 4.1。But,the library's library's api can't be used. Such as  app module dependent app1 module,then,app1 module dependent app2 module,I can't use app2's api in app。But，before gradle 4.1,it works。

**Comment by oehme** [comment]
I'm closing this issue as it does not provide enough information. Pleasep rovide a full reproducible example project (either as an archive or as a Github repo). This makes sure we can easily see the same issue you are experiencing.

**Comment by Mao-x-w** [comment]
OK,I solve it.It because that I change my compile to "compile project(path:':app',configuration: 'default')" in order to fix another bug. After I update gradle to 4.3.1,that bug was fixed,then I delete the "configuration: 'default'" ,this bug fix too. Thank you
