### ISSUE TITLE
Document new dependency management features

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#3472]
WIP documentation here: https://docs.google.com/document/d/1Cfh3CeepC3cZuRBCXVnxfR1vyCu7wFmFBYneXedcaIE/edit#heading=h.uo6da3819lzn

Features include:
- strict dependencies
- dependency constraints
- new module metadata
- BOM import
- Optional dependencies
- `Configuration.withDependencies`

Once ready, cover in:

- Release notes
- User guide

**Comment by jjohannes** [comment]
The document linked above has been deleted and the content was moved. 

For 4.6 we covered:
- dependency constraints
- BOM import
- Optional dependencies

Follow up issues for remaining topics:
- strict dependencies: part of #3977 
- new module metadata: #4049
- Configuration.withDependencies: #4377
