### ISSUE TITLE
Remove `project.property` deprecation for 4.4

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3474]
Since the advanced deprecation handling is not ready, let's do the same as we did for 4.3 - remove this warning as it is confusing the users of a major community plugin with no good workaround.

**Comment by lacasseio** [comment]
I'm a bit confused, is this a typo? `project.property` is deprecated, not `project.provider`. Or I'm missing something?

**Comment by oehme** [comment]
@lacasseio my bad, fixed.

**Comment by bmuschko** [comment]
This has been merged into `release` and reverted on `master` so we keep the deprecation message. The plan for 4.5 is to have deprecation message suppression in place for end users that originate from a plugin.
