### ISSUE TITLE
Failure of example code in: Appendix B.1. Groovy script variables

### ISSUE THREAD

**Issue by mottati** [gradle/gradle#3489]
Attempting to run the code in [Appendix B.1. Groovy script variables](https://docs.gradle.org/current/userguide/potential_traps.html#sec:groovy_script_variables
), I encounter the following error:

```
gradle -b scope.gradle 

FAILURE: Build failed with an exception.

* Where:
Build file '/data/volumes/scope.gradle' line: 3

* What went wrong:
A problem occurred evaluating root project 'volumes'.
> Could not set unknown property 'scriptScope' for root project 'volumes' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```
### Expected Behavior

The expectation was that example code would behave as documented. 

### Current Behavior
Creation of the scriptScope variable causes Gradle to fail.

### Context

I am trying to write a build script with a mixture of tasks and defs. There are a number of global properties set and checked at the beginning. In my particular case, this value comes from the environment. 

I was doing something roughly equivilant to: 

```
String _callbackHost = System.getenv("CALLBACK_HOSTNAME")
if (_callbackHost == null) {
    throw new GradleException("Please provide a value for CALLBACK_HOSTNAME")
}

def method(String port ) {
    println "${_callbackHost} ${port}"
}

task install {
    doLast{
        method("1234")
    }
}
```

    

### Steps to Reproduce (for bugs)
Run the example code provided in the link posted in the description above. 

### Your Environment

```
gradle --version 

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

```

 * Build scan URL: https://gradle.com/s/hdy6guns3grzw

**Comment by big-guy** [comment]
This is a typo in the docs.

This is intended to be a Groovy example, so you would run `groovy scope.groovy`, not Gradle.  The doc generator hardcodes the description of the output as "Output from **gradle**" (this should be "Output from **groovy**" at least).

**Comment by bmuschko** [comment]
@mottati Would you be interested in providing a better description for this via a pull request?

**Comment by mottati** [comment]
As you have noted, this should be treated as a documentation issue. The "output from **gradle**" message misdirected me into thinking I could do something that is not possible. 

The capability I need, value accessable within a def or a task, can be obtained by storing values in project.properties. I don't think it needs a PR.

**Comment by bmuschko** [comment]
The sample has been fixed. Thanks again for reporting.
