### ISSUE TITLE
Provide better ways to express whether I intend to use the contents of the artifacts of a configuration or just use their locations

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#3492]
Sometimes I want to know where the files of a configuration will end up, so that I can calculate some configuration value or generate some file that includes the file names or locations. Far more commonly, however, I want the files to have been produced so that I can use their content.

The current contract on `Configuration` is essentially the first one, and it's up to you, the caller, to make sure you query the files from some context where the configuration has been declared as a task input so that their content will be up-to-date. However, it is easy to mess this up and accidentally query from a context where this isn't the case, leading to all kinds of confusing behaviour.

We should replace these contracts with more explicit "I want the locations" and "I want the locations and the contents" query APIs of some kind. This will allow us, for example, to provide validation, failing early when I ask for the contents of something that I haven't declared as an input/dependency.

### Expected Behavior

Gradle helps me out when I ask for the contents of the files of a configuration from somewhere where Gradle cannot guarantee that the contents are available, so that when I'm expecting the files to exist and be up-to-date, they either always are or the build always fails in a nice way that explains the problem and how to fix it.

### Current Behavior

Gradle makes me confused. Probably should split that into several issues ...

**Comment by oehme** [comment]
We should also fail when you ask for the locations too early, i.e. during configuration time. See https://github.com/gradle/gradle/issues/2298
