### ISSUE TITLE
Maven2Gradle conversion support targeting Kotlin DSL

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#3493]
I had a short chat with @bamboo about this idea at Kotlin Conf.

Currently the `init` task which invokes the [Maven2Gradle](https://github.com/gradle/gradle/blob/master/subprojects/build-init/src/main/groovy/org/gradle/buildinit/plugins/internal/maven/Maven2Gradle.groovy) converter only supports generating groovy based DSL.

### Expected Behavior
Ability to convert a maven project to the Gradle Kotlin DSL OR Gradle Groovy DSL.

### Current Behavior
Currently, only Groovy is supported.

### Context
This would help increase adoption of the Gradle Kotlin DSL for users that are migrating their builds from maven.

### Questions
- Does this converter make sense to live in the Gradle repository or the Kotlin DSL repository?
- If the converter should live in the Gradle repository, can the logic that already exists in the `Maven2Gradle` class be shared with the Kotlin converter? Does it make sense to share logic between the two converters or try and write a new one for Kotlin?
- The `MavenProjectsCreatorSpec` doesn't seem to actually compile the generated build file. Is there a different place where that does happen?

Does anyone know how often this converter gets used? I know that I ran it when I was first attempting my conversion of my companies build from Maven to Gradle and found it an incredibly useful starting point. Is it worth spending the time to implement the converter for Kotlin?

**Comment by bmuschko** [comment]
Overall a good idea. We'd definitely welcome a pull request if you are interested in working on it.

> Does this converter make sense to live in the Gradle repository or the Kotlin DSL repository?

For now I think we'll want to keep the code in the Gradle repository. The `init` task is part of Gradle core.

> Does it make sense to share logic between the two converters or try and write a new one for Kotlin?

The converter should share the general infrastructure for both target DSLs as much as possible. I'd think that the actual derived information from the Maven build is the same. The only difference is how it would be interpreted in the target language.

> The `MavenProjectsCreatorSpec` doesn't seem to actually compile the generated build file. Is there a different place where that does happen?

I think what you are looking for is `MavenConversionIntegrationTest`.

> Does anyone know how often this converter gets used?

I have been using it before to convert larger Maven multi-project builds to get a starting point. Other than that I do not have any numbers on the usage.

> Is it worth spending the time to implement the converter for Kotlin?

I personally think it would be great to have the functionality. More and more users will migrate to Kotlin directly. Over time we'll have to ensure that the produces output will still be correct with the Kotlin DSL (which isn't final yet).

**Comment by eskatos** [comment]
PR https://github.com/gradle/gradle/pull/3556

**Comment by bmuschko** [comment]
@eskatos The PR has been merged. Can you please close the issue?

**Comment by eskatos** [comment]
The PR linked above (#3556) has been closed, not merged.
Let me re-triage this issue, sorry for the confusion.

**Comment by JLLeitschuh** [comment]
Can you clarify what happened?

**Comment by eskatos** [comment]
@JLLeitschuh we decided to add Kotlin DSL support to all build init build types except for the Maven to Gradle conversion in #3788. The main reason was to not add more complexity to `Maven2Gradle` without making it better. The `Maven2Gradle` converter needs some more love before this can happen. This issue is solely about the Maven to Gradle conversion and will be tackled on its own.

**Comment by adammurdoch** [comment]
The changes in https://github.com/gradle/gradle/pull/6489 mean that it would now be much simpler to implement Kotlin DSL support for Maven conversion. This would make a good contribution from the community, if someone is interested.

**Comment by bjliu** [comment]
Working on this now

**Comment by jjohannes** [comment]
This will be in 6.7
