### ISSUE TITLE
Create a dependency management samples repository

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3495]
To demonstrate new features in dependency management, we want to have a place to collect examples: https://github.com/gradle/dependency-management-samples

Initially add example we already have for:
- optional dependencies
- BOM import
- New _component metadata rules_ feature
- `Configuration.withDependencies()`

**Comment by pioterj** [comment]
Have we considered simply [gradle/subprojects/docs/src/samples/](https://github.com/gradle/gradle/tree/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/docs/src/samples)?

**Comment by jjohannes** [comment]
This repository is meant for sharing examples of features that are under development to gather early feedback. Once they are final, we can move stable examples into the documentation.

**Comment by jjohannes** [comment]
Repo was created and an initial set of samples was added.
