### ISSUE TITLE
missing custom Gradle Plugin com.github.ramonwirsch.FopRenderer 

### ISSUE THREAD

**Issue by ramonwirsch** [gradle/gradle#3499]
For a few versions, when i publish a new version of my own plugin, it is listed in Gradles Plugin portal and the HTTP-accessible maven lists the artifacts correctly (https://plugins.gradle.org/m2/gradle/plugin/com/github/ramonwirsch/FopRenderer/fopRenderer/0.1.14/), but the artifacts themselves are missing (e.g. https://plugins.gradle.org/m2/gradle/plugin/com/github/ramonwirsch/FopRenderer/fopRenderer/0.1.14/fopRenderer-0.1.14.pom)

After a few weeks it usually starts working again.
I believe it broke the first time right around when the Maven coordinates assigned by gradle changed (0.1.10 - 0.1.11).

The publishing plugin does not show any errors.
It is not a problem of gradle not resolving the plugin id correctly, but a problem in the plugin repository as the link gradle fails to find is the correct one and it fails even from a browser.

What can I do to have my plugin published correctly?

**Comment by oehme** [comment]
@rhart is this something you could look into?

**Comment by rhart** [comment]
@ramonwirsch can you confirm which version of the publish plugin you are using? 

If it is < 0.9.7 then you are likely suffering from this bug https://discuss.gradle.org/t/plugin-authors-please-use-the-latest-plugin-publish-plugin-others-may-result-in-a-broken-upload/23573

Upgrading to the latest version of the plugin-publish-plugin will fix this, but will require pushing a new version of your plugin.

**Comment by ramonwirsch** [comment]
Yep, like an idiot is was using 0.9.5 and did not think to upgrade.

Thanks very much, problem resolved!
