### ISSUE TITLE
Dependencies with api not working as compile.

### ISSUE THREAD

**Issue by YunlongYang** [gradle/gradle#3509]
When I publish my android library project to gitpack.io, i want to add Glide to my dependencies and user no need to add it again.
At first, i use implementation, it do not work, after reading doc, i change to api.
But it did not work either,at last, i change to compile, it works well.
i know compile is deprecated now, but i have to use it here.

**Comment by oehme** [comment]
Please open an issue at jitpack, since they are probably still using the old configurations.
