### ISSUE TITLE
TeamCity Build Status on Pull Requests

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#3515]
TeamCity pass/fail results should be displayed as statuses on PR's and on commits.
This will help contributors see if things have failed TeamCity checks and that they need to update their PR's.

The configuration seems to be pretty easy to setup:
https://blog.jetbrains.com/teamcity/2016/10/teamcity-10-github-related-improvements/

**Comment by big-guy** [comment]
We do (see "Show all checks" and the checks/crosses on some commits):
https://github.com/gradle/gradle/pull/3505 

Builds aren't automatically triggered because we require someone with access to OK the build first.

**Comment by JLLeitschuh** [comment]
Sorry. Mean to target this at the Gradle Kotlin DSL project. My mistake.
