### ISSUE TITLE
Gradle PMD plugin does not function with Java 9

### ISSUE THREAD

**Issue by BillAtPros** [gradle/gradle#3519]
[A project with a README.md](https://github.com/BillAtPros/pmdTest) has been created for this issue. This include environment details and debug output.

After running *./gradlew check* the pmd output shows that pmd encountered an error while processing the single .java file in the project.

```
Error while processing me/pmdTest/src/main/java/foo/HelloWorld.java
```

Debug output seems to indicate an issue with asm:
```
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.getImportedClasses(PMDASMClassLoader.java:107)
```
Again [please see the project created to illustrate this issue](https://github.com/BillAtPros/pmdTest) for complete details.

**Comment by blindpirate** [comment]
Thanks for reporting. AFAIK, that's a known limitation of PMD. Looks like this should be fixed in the future release [6.0.0](https://github.com/pmd/pmd/issues/584), so there's nothing we can do on Gradle side.

I'll close it now, please feel free to reopen.

**Comment by BillAtPros** [comment]
@blindpirate 
[Actually, 6.0.0 is released](https://mvnrepository.com/artifact/org.ow2.asm/asm/6.0). The PMD plugin needs to be updated to use 6.0.0 as dependency in order to support 1.9 bytecode. 

Is the PMD plugin managed/supported by Gradle? If so, I respectfully submit that the ball is  now no longer in ASM's court, but firmly in Gradle's

**Comment by blindpirate** [comment]
We manage the PMD plugin (a very thin layer to invoke PMD core via [Ant](https://github.com/gradle/gradle/blob/2622baaf86d959685f94c947302b5fb1b26f4ac5/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy#L60)), but the PMD core is maintained by PMD team.

Sorry if I didn't make myself clear. I mean [pmd 6.0.0](https://github.com/pmd/pmd/issues/584), not ASM 6.0.0. I'm not sure if latest [5.8.1](https://github.com/pmd/pmd/releases) is compatible with ASM 6, but you can sure try it:

```
dependencies {
    pmd 'net.sourceforge.pmd:pmd-java:5.8.1'
    pmd 'org.ow2.asm:asm:6.0'
}
```
