### ISSUE TITLE
Setting Java Security Manager will make junittests run in Gradle hang

### ISSUE THREAD

**Issue by elvaro** [gradle/gradle#3526]
I have a junit test that sets a security manager for the jvm. When the unit test is run in IntelliJ it completes normally. However when the test is run through Gradle it hangs after a new security manager has been set.
### Expected Behavior
The test case should finish in expected manner whether run through Gradle or IntelliJ

### Current Behavior
The test case hangs when run through Gradle but completes successfully when run in IntelliJ

### Context

I have a java command line tool that sets the security manager during the initialization phase. I have Junit test cases that check certain behaviour in the code to make sure the code is valid.

I will also include links to older issue in the old Jira issue tracker. These issues seem to cover the same issue that I am having but for some reason they were not exported over to the Github tracker. Therefore those issues were never solved.
https://issues.gradle.org/browse/GRADLE-2170
https://issues.gradle.org/browse/GRADLE-903

### Steps to Reproduce (for bugs)

A project that reproduces this problem can be found here:
https://github.com/elvaro/gradle-securityManager-bug
This project contains a single java junit test class that has two different test cases. One of them sets a new security manager and uses the supplied policy file. That one fails when run in gradle but will complete successfully in IntelliJ.
Then there is a second test case that set a new security manager where the checkPermission methods are overridden to not to throw any exceptions on errors. This ensures that gradle can finish the tests as well as IntelliJ.

### Your Environment

 * Build scan URL: 
https://scans.gradle.com/s/x64ckcsudvuto/
In this scan I had to comment out the test that was not working since otherwise the gradle build would hang and not create the scan url.

**Comment by blindpirate** [comment]
Thanks for reporting, it's definitely Gradle's bug and has nothing to do with `SecurityManager`, `SecurityManager` is just a trigger. I'll investigate it.

**Comment by bmuschko** [comment]
@blindpirate This is lined up in the backlog. Were you planning to work on this soon?

**Comment by blindpirate** [comment]
@elvaro This is due to heavy usage of reflection/process communication in Gradle internal implementation. Setting up `SecurityManager` will disrupt Gradle's work (use reflection/read data from socket, etc.). I'd admit this is incorrect, at least Gradle shouldn't hang there, but currently this is hard to solve this problem thoroughly.

@bmuschko Since there's no easy fix for this issue, we could discuss it on the meeting.

**Comment by oehme** [comment]
We should find out why Gradle hangs in this scenario and throw a descriptive exception instead. We can't simply make this work, as our test infrastructure depends on reflection and socket communication. So we need to instruct users to allow `org.gradle.*` to do anything.

**Comment by blindpirate** [comment]
When running tests, Gradle will fork several worker processes to run the test, which send test results to main process via socket and reflection. Once a security manager is set in a worker process, all messages will be "sealed" in that process, which results in main process waiting infinitely. BTW, IDEA runs the tests and catches the result via stdout, so it wouldn't be affected.

A possible solution for hanging is to monitor worker process standard output, because all messages that are "sealed" in the JVM will eventually fall back to standard out. When we find worker process stdout say, "hey buddy, I can't send you any message because I'm sealed", we can mark this worker process as "dead" or something like this, telling user, "sorry, you'd allow Gradle's internal work in your security manager".

**Comment by salvianreynaldi** [comment]
I'm still experiencing hanging tests in 4.7 + security manager and policies applied. Moreover, setting tests security policy to only allow connection to "[0:0:0:0:0:0:0:1]" while the environment's ipv6 is disabled will result in this kind of errors
```
java.lang.RuntimeException: Could not connect to server [50b34dd4-a0e8-4358-b068-7e249aac341b port:40967, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
Caused by: java.security.AccessControlException: access denied ("java.net.SocketPermission" "127.0.0.1:40967" "connect,resolve")
Process 'Gradle Test Executor 7' finished with non-zero exit value 1
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 7' finished with non-zero exit value 1
```
how can we run tests successfully while still restricting them not to make any network connection at all?

**Comment by blindpirate** [comment]
@salvianreynaldi You'd better adjust your security manager and policies to allow Gradle package/code base to access socket, use reflection, etc. Or, simply allow Gradle to do anything.

**Comment by salvianreynaldi** [comment]
thanks @blindpirate , but how exactly do I allow gradle in the policy file? what `codeBase` / `signedBy` that I should grant access to?

**Comment by blindpirate** [comment]
I think something like 

```
grant codeBase "file:<GRADLE_USER_HOME>/-" {
    permission java.security.AllPermission;
};
```

would help. The format is from https://docs.oracle.com/javase/7/docs/technotes/guides/security/PolicyFiles.html

I'm not sure if Gradle's jar is signed, I think they're not so `signedBy` isn't necessary.

**Comment by salvianreynaldi** [comment]
@blindpirate I've tried this
```
grant codeBase "file:${gradle.user.home}/-" {
    permission java.security.AllPermission;
};
```
while setting `systemProperty "gradle.user.home", project.gradle.gradleUserHomeDir`

but doesn't this gives all libraries in `<gradle.user.home>/.caches/modules-2/files-2.1/` access to the internet? Is it possible to only give the permissions to gradle (and its dependencies)? I tried `codebase file:${gradle.home}/-` (e.g. `/home/salvian/.gradle/wrapper/dists/gradle-4.7-bin/73xux3q4721jgr4pjvqf9o30/gradle-4.7/-`) but this results in the same `java.security.AccessControlException` errors

**Comment by blindpirate** [comment]
The workaround is listed in this thread, by granting proper permission to gradle jars.

**Comment by siyopao** [comment]
Ah, sorry about that. I read that but I thought it applied to a different problem. I'll give it a shot. Cheers.

**Comment by johnrengelman** [comment]
Has anyone gotten this to work? Would love to seen an example policy config that actually works.
I've done:
```
grant codeBase "file:/Users/john/.gradle/-" {
    permission java.security.AllPermission;
};
```
which from my understanding should grant all JARs and classes under that path the all permission. But it still doesn't work. Tests just hang.

If I add: 
```
grant {
  permission java.security.AllPermission;
};
```
then the tests run fine.
