### ISSUE TITLE
support cross-compilation of a Scala project to target numerous versions of Scala, i.e. 2.10/2.11/2.12

### ISSUE THREAD

**Issue by yairogen** [gradle/gradle#3530]
### Expected Behavior
Support cross compilation like sbt  - one build produces multiple artifacts per scala version

### Current Behavior
Not Supported

### Context
This is the major reasons why people stick with sbt

**Comment by oehme** [comment]
It's absolutely supported, there's just not a single-line convenience for it. But you can create multiple Scala compile tasks and multiple Jar tasks and even vary dependencies and source files depending on scala version if you want. This would be an ideal topic for a community plugin.

**Comment by igreenfield** [comment]
@oehme could you supply sample how to achieve what you describe?

**Comment by nathanalderson** [comment]
I created [a plugin](https://github.com/ADTRAN/gradle-scala-multiversion-plugin) a while ago to help achieve this, but it's pretty hacky. I suspect there is a much better way to do it, but don't think I'm familiar enough with the core pieces to achieve it properly. I'd love to see something more official.

**Comment by sschuberth** [comment]
For reference, LinkedIn seems to have created some plugin for this, albeit it's only avialble as `buildSrc` sources:

https://github.com/linkedin/scanns/tree/master/buildSrc/src/main/groovy/com/linkedin/nn/build/plugins 

And also:

https://github.com/linkedin/photon-ml/tree/master/buildSrc/src/main/groovy/com/linkedin/photon/build/plugins

**Comment by oehme** [comment]
I was thinking more along the lines of just creating one compile and jar task for each version, not creating synthetic projects.

**Comment by sschuberth** [comment]
That's probably indeed the better approach as otherwise with separate synthetic projects you seem to be running into issues like https://github.com/linkedin/scanns/issues/2.

**Comment by asm0dey** [comment]
I would like to reopen this

**Comment by chenjianjx** [comment]
It will be great if this feature is implemented.  Cross building is a basic requirement if you want to build a Scala library to be used by projects with different Scala versions.

**Comment by ljacomet** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.
***

There is one complicating factor with this: cross project resolution and publication have issues when there is more than one publication, which would be the case for Maven compatibility of such a setup.

Related:
* https://github.com/gradle/gradle/issues/12324
* https://github.com/gradle/gradle/issues/998
