### ISSUE TITLE
Ear exclude deploy jars/wars from earlib configuration

### ISSUE THREAD

**Issue by jutoft** [gradle/gradle#3535]
When adding a module to an ear from maven, one have to add the module to "deploy" configuration before it is added as a module.
But to get it's dependencies added it have to be added to "earlib" as well.

### Expected Behavior

Have all "jars/wars" in deploy configuration be excluded from the earlib configuration when creating the ear file.

### Current Behavior

The dependency is placed both in the root and in the lib directory.

### Context

Trying to add existing jars from maven artifacts into a ear.

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
I think simply doing a `minus()` when assembling the EAR should work. It's still a bit cumbersome though, as the user has to add the same dependency to two `Configurations`. I also wonder if it really makes sense to add all of them, since some of the dependencies are usually bundled inside the WAR. I don't think projects published with Maven properly separate that.

Could you provide a little example project to illustrate the expected behavior? We could then use that as a test case.

**Comment by jutoft** [comment]
The issue is that we have a bean that have several dependencies, but to get the dependencies the jar have to be in the earlib configuration.

I would suggest that using earLib.minus(deploy) would resolve that so in less lines the dependencies can be resolved into earlib and the deployments into the deploy location.

I added a test on https://github.com/jutoft/gradle/tree/ear_no_default_dependencies to show how i expect it to work.

**Comment by oehme** [comment]
@jutoft I don't see a test yet, did you push it? Also there are unrelated changes to the `Configuration`s and artifacts. We should not do those, they are breaking changes and shouldn't be necessary for fixing the issue.

**Comment by jutoft** [comment]
Oh, i just thought it was a defect that the ear declares transitive dependencies when it would never be used… but I guess I can just use the archives configuration to resolve the ear file without getting the dependencies. 

The war plugin have providedCompile and providedRuntime. Those files do not get added to the war file. But they are declared as dependencies, though the rest of dependencies are as well I guess. 
We would have to add war.providedCompile.minus(javacompile.minus(providedCompile)). To only get the dependencies not in the war file. Same for runtime of cause.

**Comment by jutoft** [comment]
I will push tomorrow… I must have forgotten to do so.

**Comment by oehme** [comment]
I think changing the Configurations to model WARs/EARs better is another issue. This is possible with variant-aware dependency management now, we just haven't gotten to it yet. But let's first start with the issue you described.

**Comment by jutoft** [comment]
I have updated the branch now.
https://github.com/jutoft/gradle/tree/ear_no_default_dependencies

**Comment by jutoft** [comment]
Do you see any way to get the same result without modifying either Ear or EarPlugin.

**Comment by jutoft** [comment]
An alternative is to create a "provided" configuration, that could then be removed from earlib.
The user would have to set it transitive:false to get the result though.

**Comment by oehme** [comment]
I think what you have on your branch now is a good step forward. Would you mind opening a new PR?

**Comment by jutoft** [comment]
Done.

**Comment by jutoft** [comment]
I will push tomorrow… I must have forgotten to do so.
