### ISSUE TITLE
Gradle Nexus 401 Password Issue

### ISSUE THREAD

**Issue by jomach** [gradle/gradle#3536]
I’m getting 401 on my gradle.build

maven {
url "https://nexus/repository/maven-public"
credentials {
username nexusUser
password nexusPassword
}
}

If I run gradlew clean build and I put nexusUser and nexusPassword on gradle.properties it will fail with 401 but the properties are there because if I do println(nexusUser) I get a response. If I hard code the credentials it does work. Gradle 4.3.1
### Expected Behavior
This should work. 

### Current Behavior
it does 401 back. If I hardcode the password String then it works. Is the new gradle version doing something the the password ? like hashing or so ?
### Context
Nexus, gradle

### Your Environment

 * Build scan URL:

**Comment by jomach** [comment]
I found out that gradle does not escape spaces on gradle.properties which is bad...

**Comment by bmuschko** [comment]
You'll have to escape the spaces yourself in the properties file. Java doesn't do that out of the box either.
