### ISSUE TITLE
Fails creating a POM when having local dependencies

### ISSUE THREAD

**Issue by saantiaguilera** [gradle/gradle#3543]
When using `implementation project(':local_module')`, the pom file generated breaks (creating zero ([]) generatedDependencies) thus having an empty pom

If instead is used `compile project(':local_module')`, then the following error happens:
```
Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'default' not found.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.createNotFoundException(DefaultConfigurationContainer.java:127)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:229)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:117)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.getByName(DefaultConfigurationContainer.java:49)
        at org.gradle.api.publication.maven.internal.pom.DefaultPomDependenciesConverter.getTargetConfiguration(DefaultPomDependenciesConverter.java:122)
        at org.gradle.api.publication.maven.internal.pom.DefaultPomDependenciesConverter.addMavenDependencies(DefaultPomDependenciesConverter.java:134)
        at org.gradle.api.publication.maven.internal.pom.DefaultPomDependenciesConverter.addFromDependencyDescriptor(DefaultPomDependenciesConverter.java:113)
        at org.gradle.api.publication.maven.internal.pom.DefaultPomDependenciesConverter.convert(DefaultPomDependenciesConverter.java:55)
        at org.gradle.api.publication.maven.internal.pom.DefaultMavenPom.getGeneratedDependencies(DefaultMavenPom.java:170)
        -> Where I do the pom.writeTo(path) <-
```

If the local dependency is removed, everything works as expected

### Expected Behavior
This doesnt happen in 3.+ gradle versions, the expected behaviour should be a pom with all my `generatedDependencies`, and that can be written

### Current Behavior
Fails to handle all the dependencies, creating an empty array of generatedDependencies
Currently my dependency scope is:
```
dependencies {
    implementation project(path: ':loquacious')

    implementation dependency.implementation.kotlin
    implementation dependency.implementation.support.annotations
    implementation dependency.implementation.gson

    testImplementation dependency.test.junit
    testImplementation dependency.test.robolectric
    testImplementation dependency.test.mockito
}
```

Throws the above stacktrace, if the dependency scope is:
```
dependencies {
    compile project(path: ':loquacious')

    implementation dependency.implementation.kotlin
    implementation dependency.implementation.support.annotations
    implementation dependency.implementation.gson

    testImplementation dependency.test.junit
    testImplementation dependency.test.robolectric
    testImplementation dependency.test.mockito
}
```

* Works if you dont have a local dependency.
* Using `api` bears no meaning
* Works fine in gradle 3.X
* Tried using gradle 4.3.1 and 4.1.0
* Im generating the pom like this:

```groovy
            DefaultMavenPom createdPom = null
            project.install {
                repositories.mavenInstaller {
                    createdPom = pom {
                        project {
                            groupId project.group
                            artifactId project.name
                            version project.version

                            packaging 'aar'

                            if (configHelper.websiteUrl) {
                                url configHelper.websiteUrl
                            }

                            if (configHelper.licenseName && configHelper.licenseUrl) {
                                licenses {
                                    license {
                                        name configHelper.licenseName
                                        url configHelper.licenseUrl
                                    }
                                }
                            }
                        }
                    }
                }
            }

            createdPom.writeTo("${project.buildDir}/" +
                    "publications/" +
                    "${TASK_NAME_PREFIX}${variant.name.capitalize()}/" +
                    "pom-default.xml")
```

### Context
Trying to release a library. 

### Steps to Reproduce (for bugs)
1. Clone it. (https://github.com/saantiaguilera/android-api-loquacious)
2. Set some user and apikey of bintray, or run the generatePom... task, or copy paste my above pom generation
3. If you are going for the bintray way, run `./gradlew publishModule` since thats the task that runs it
4. See results.

The module `locale` is the one that has local dependencies, thus breaking its own pom.

I've for now downgraded my gradle version to 3.5.1, which runs correctly. I provide here both sha commits if you wish to check something:
**Sha for gradle 4.3.1** (fails): 2b019262630e5b26c6958860fb0d15a542ddd517
**Sha for gradle 3.5.1** (ok)   : 7407ed03653a97083e6f4483af4c7e3a9eab109c

### Your Environment
MacOS Sierra

Gradle 4.3.1

Android Studio 3.0 (although I believe this issue is from the gradle Maven plugin, and not from android)

**Comment by jjohannes** [comment]
@saantiaguilera I can not reproduce this problem (anymore?). Did you fix this in your publishing plugin?

**Comment by saantiaguilera** [comment]
Nope, I just downgraded it to gradle 3.5. Did you try it in the 4.1 sha? (2b019262630e5b26c6958860fb0d15a542ddd517)

**Comment by bbowman** [comment]
I'm seeing this as well.

**Comment by bigdaz** [comment]
Unfortunately, we are unable to reproduce this problem.

The `maven` plugin (together with the `repositories.mavenInstaller`) are being replaced by the `maven-publish` plugin. As such, we don't plan on making changes to improve this (now legacy) mechanism for generating POM files. Expect to see this type deprecated in Gradle 6.0, for possible removal in Gradle 7.0.

Please update your build to use the `maven-publish` plugin, letting us know if there are issues that prevent this migration.
