### ISSUE TITLE
Dependency constraints

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3549]
Gradle should provide a mechanism to express constraints over transitive dependencies. These dependencies should be used for the build and should be published: Without information loss in the new Gradle metadata format and with a (possibly lossy) mapping in Maven BOMs or as maven optional dependencies (for consumption by Maven).

**Comment by ljacomet** [comment]
This has been completed in Gradle 5.2 with the documentation of rich version declaration.

Constraints:
* can be declared
* are only about the module they target, they do not add a path to transitive dependencies
* can have attributes and capabilities
* form the basis of a platform definition in `java-platform` plugin
* have a visual indicator in `dependencies` and `dependencyInsight` reports
