### ISSUE TITLE
Show dependency constraints in the dependencies report

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3554]
When a dependency constraint influences the resolution result, it already shows up as a dependency in the `ResolutionResult` API and the `dependencies` and `dependencyInsight` reports.

- add test coverage for existing behaviour (if required)
- ~Show more details about version constraints~ 
- Show edges from dependency constraints differently to edges from strong dependencies
All of these are likely useful.

**Comment by melix** [comment]
I have spiked a cheap way to do this, leveraging the new `ComponentSelectionReason` API. I added a new type of cause, `constraint`, which is used whenever a component is selected by a constraint.

Then the dependency insight report can use that information to show that a component was constrained:

```
> Task :dependencyInsight 
com.google.guava:guava:23.6-jre (via constraint)
\--- nebula.example:bom:1.0.0
     \--- testRuntimeClasspath
```

Note, however, that the addition of a cause breaks the build scan plugin.
