### ISSUE TITLE
Support definition of dependency constrains for a group of modules 

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3559]
A common pattern for "platforms" that consist of multiple modules, is to have all modules in the same group and have their versions synced. 
This feature allows to make sure the versions of all modules that belong to such a "platform" align,  by defining a dependency constraint for the whole platform (i.e. the whole group).

For example:
```
dependencies {
  constraints {
    implementation group: "org.glassfish.jersey.core", version "2.6"
  }
}
```

We may consider to support hierarchical groups or something similar that takes _group of parent_ into account. Such that this is also supported:

```
dependencies {
  constraints {
    implementation group: "org.glassfish.jersey", version "2.6"
  }
}
```

**Comment by lslonina** [comment]
This could be done same way as in [Spring Dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin).
I think that it should be possible to list artifacts to have same group with different versions/artifacts
```
dependencies{
     constraints{
          implementation (group:'org.slf4j', version: '1.7.7') {
               artifact 'slf4j-api'
               artifact'slf4j-simple'
          }
     }
}
```

**Comment by melix** [comment]
We're probably going to model this as a first class concept (module set).

**Comment by ljacomet** [comment]
This feature has been delivered as part of Gradle 5.0 under the name [dependency alignment](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:version_alignment).
