### ISSUE TITLE
Support dependency injector in the ObjectFactory

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#3562]
### Expected Behavior
When we instantiate an object using the `project.objects.newInstance()` API, it would be useful to support partial arguments list (from the left) and try to resolve the remaining arguments using dependency injection.

### Current Behavior
Gradle throws "no suitable constructor found" exception.

### Context
In this case I am trying to instantiate objects in a domain object container and have it come out of the factory initialized with default values and `Property` holders.

### Steps to Reproduce (for bugs)
https://discuss.gradle.org/t/how-to-use-the-instantiator-to-create-a-named-domain-object/24855

@oehme

**Comment by adammurdoch** [comment]
This was added in Gradle 4.2.
