### ISSUE TITLE
Consider changing resolution from a Maven repository to not look for a pom when a Gradle metadata file is present

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#3568]
When the dependency resolution experimental features are enabled, Gradle looks for and downloads both the Maven POM and the Gradle module metadata file to resolve from a module in a Maven repository. However, when the module metadata file is present, the contents of the POM are ignored, except in some rare cases.

Downloading the POM means another network request, and potentially several network requests on dependency refresh/Gradle version upgrade, and these requests can be expensive. There is also more work in juggling the extra, unused, data in caches in heap and on the file system (but this can be addressed separately).

We should consider not bothering downloading the POM when the Gradle module metadata file is present. A potential downside is that we give up some validation that the module is well formed, and we would also need to deal with those cases where the POM is actually required (when a dependency declaration points to a specific configuration we resolve this to a matching scope in the POM).

### Expected Behavior

Gradle does fewer network requests by not downloading POMs that it won't use.

### Current Behavior

Gradle performs network requests to download POMs that it won't use, meaning wasted work.

**Comment by melix** [comment]
FTR this is now also true with Ivy files, now that we support publishing Gradle metadata on Ivy repositories. However there are probably much more edge cases with Ivy than there are with Maven.

**Comment by bigdaz** [comment]
We no longer download the POM/Ivy file if a Gradle metadata file is found. However the code has not yet been refactored internally to separate the Ivy/Maven model from the Gradle metadata. I've opened #3816 for this.
