### ISSUE TITLE
Support version variables in Plugins section

### ISSUE THREAD

**Issue by eximius313** [gradle/gradle#3593]
### Expected Behavior
Gradle should support versions taken from `ext` in `plugins` section

### Current Behavior
`«plugin version» and «plugin id» must be constant`

### Context
DRY is considered a good practice in programming. 
Unfortunately if I want to use a plugin, I must declare its version in two places:
```
buildscript {
    ext {
        myPluginVersion = "0.3"
    }
    dependencies {
        classpath "my:app:${myPluginVersion}"
    }
}
plugins {
    id 'my.app' version '0.3' apply false
}
```
there should be an option to do:
```
plugins {
    id 'my.app' version myPluginVersion apply false
}
```

**Comment by eximius313** [comment]
How about SpringBoot where plugin must be the same version as library?

**Comment by drasolka** [comment]
The Spring Framework version is managed by the Spring Boot plugin.
E.g. the spring boot plugin version 1.5.8 provides the spring framework version [4.3.12](https://docs.spring.io/spring-boot/docs/1.5.8.RELEASE/reference/htmlsingle/#getting-started-system-requirements).
The spring boot plugin version 2.0.0.M6 provides the spring framework version [5.0.1](https://docs.spring.io/spring-boot/docs/2.0.0.M6/reference/htmlsingle/#getting-started-system-requirements).

### Plugins DSL
The Spring Boot sample configuration with **plugins dsl** provided in [documentation](https://docs.spring.io/spring-boot/docs/1.5.8.RELEASE/reference/htmlsingle/#getting-started-gradle-installation).
```
plugins {
    id 'org.springframework.boot' version '1.5.8.RELEASE' //plugin version
    id 'java'
}

jar {
    baseName = 'myproject'
    version =  '0.0.1-SNAPSHOT'
}

repositories {
    jcenter()
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web") //no dependency version, it is managed by plugin
    testCompile("org.springframework.boot:spring-boot-starter-test")
}
```
Note that there is no version specified for dependencies because spring boot plugin works as Maven BOM and provides versions to spring dependencies.

### Buildscript
The Spring Boot sample configuration with **buildscript** can be found [here](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-gradle-installation).
```
buildscript {
    repositories {
        jcenter()
        maven { url 'http://repo.spring.io/snapshot' }
        maven { url 'http://repo.spring.io/milestone' }
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:2.0.0.BUILD-SNAPSHOT' //plugin version
    }
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot' //apply plugin, no version required
apply plugin: 'io.spring.dependency-management'

jar {
    baseName = 'myproject'
    version =  '0.0.1-SNAPSHOT'
}

repositories {
    jcenter()
    maven { url "http://repo.spring.io/snapshot" }
    maven { url "http://repo.spring.io/milestone" }
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web") //no dependency version, it is managed by plugin
    testCompile("org.springframework.boot:spring-boot-starter-test")
}
```

**Comment by bmuschko** [comment]
There might a valid use case where you would want to externalize the version for a plugin. In your specific example you are mixing up the `buildscript` and `plugins` declaration so I think it's a non-issue for you. We can continue the discussion if you feel like you still want to continue to talk about it.

@drasolka Thanks for your answers!

Closing the issue for now.

**Comment by eximius313** [comment]
That was exactly my case

**Comment by jmewes** [comment]
For Spring Boot you can work around this issue like this:

```
plugins {
    id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

ext {
    springBootVersion = '2.0.4.RELEASE'
}

    repositories {
        mavenCentral()
        maven { url 'http://repo.maven.apache.org/maven2' }
    }

    dependencies {
        compile 'org.springframework.boot:spring-boot-starter'
    }

    dependencyManagement {
        imports { mavenBom("org.springframework.boot:spring-boot-dependencies:${springBootVersion}") }
    }
```

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    }
}

apply plugin: "org.springframework.boot"
```

See https://plugins.gradle.org/plugin/org.springframework.boot

**Comment by reitzig** [comment]
Not sure if this is a shortcoming in the Kotlin plugin, but here I need redundant versions (Gradle 5.3.1):

```groovy
plugins {
    id 'org.springframework.boot' version "2.1.4.RELEASE"
    id "org.jetbrains.kotlin.jvm" version "1.3.31"
    id "org.jetbrains.kotlin.plugin.spring" version "1.3.31"
    id "org.jetbrains.kotlin.plugin.allopen" version "1.3.31"
}
```

The only way I found for this setup to state the version only once was to not use `plugins` but the `buildscript/dependencies` + `apply` style.

**Comment by perlun** [comment]
@reitzig Don't think it's Kotlin-related. It's the same when using the Groovy DSL as well.

**Comment by lukasbradley** [comment]
I have the same issue using Java.  Please re-open, it's the 21st century.  We should have this.

**Comment by kdabir** [comment]
I think this is closest to what we can get to externalize the plugin version (as of gradle 5.6.1)

settings.gradle
```
pluginManagement {
  plugins {
        id 'org.gradle.sample.hello' version "${helloPluginVersion}"
    }
}
```
build.gradle
```
plugins {
    id 'org.gradle.sample.hello'
}
```
gradle.properties
```
helloPluginVersion=1.0.0
```

Reference:
https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_version_management
