### ISSUE TITLE
Modifying a dependency in resolutionStrategy does not affect generated POMs

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#3594]
When a `resolutionStrategy` is set up for a project that modifies the dependencies by using, e.g. `useVersion`, the resulting version is not reflected in `pom.xml` that is generated for publishing the project. Instead. Instead, if there was no version in the build script, there is no version in the POM either.

### Expected Behavior
A dependency that is provided a version with the `resolutionStrategy` mechanism, should have that same version in the `pom.xml` generated during publishing.

### Current Behavior
The version that is set with `resolutionStrategy` is not reflected in the POM (in particular, when there's no version in the build script, there is no version in the POM either).

### Context
In the `kotlin-gradle-plugin`, we tried to set up the resolution strategy for a user's convenience, allowing them to specify the Kotlin version only once in the `plugins { ... }` block and omit the explicit versions in the other Kotlin artifacts dependency declarations (such as `org.jetbrains.kotlin:kotlin-stdlib`, `org.jetbrains.kotlin:kotlin-reflect`).

### Steps to Reproduce (for bugs)
1. Clone the repository: https://github.com/h0tk3y/gradle-resolution-strategy-problem
2. `./gradlew install`
3. `cat build/poms/pom-default.xml`
4. Note that the dependency has no version:

        <dependency>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-stdlib</artifactId>
          <scope>compile</scope>
        </dependency>
    

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/75qaccuwwnrhy

**Comment by oehme** [comment]
The resolution strategy affects resolution, so it is expected that it does not affect the declared dependencies. Have a look at the new `Configuration.withDependencies {}` API in Gradle 4.4 RC1 for a way to provide default versions. This will be respected in the generated POM.
