### ISSUE TITLE
Setting a dependency version via `Configuration.withDependencies` fails

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#3598]
The `Configuration.withDependencies` API does not allow modifying a dependency version. The example from [the JavaDoc](https://docs.gradle.org/4.4-rc-1/javadoc/org/gradle/api/artifacts/Configuration.html#withDependencies(org.gradle.api.Action)) fails with an exception.

### Expected Behavior
`withDependencies` should allow modifying the dependencies of a configuration, in particular, replace the versions of the dependencies.

### Current Behavior
The attempt to modify a version fails with an exception:
```
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Cannot set the value of read-only property 'version' for DefaultExternalModuleDependency{group='junit', name='junit', version='null', configuration='default'} of type org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency.
```

### Context
The API was the recommended way to modify the dependency versions so that the change affects publications as well, in place of resolution strategy. https://github.com/gradle/gradle/issues/3594

### Steps to Reproduce (for bugs)
1. Clone the repository https://github.com/h0tk3y/gradle-with-dependencies-issue
2. `./gradlew build`
3. See the log

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/4mojo27d5km3i

**Comment by jjohannes** [comment]
The example seems to be wrong. Can you try

`dependency.version { prefer '1.1.60' }` (instead of `dependency.version = '1.1.60'`)

**Comment by h0tk3y** [comment]
Tried it, and It works. Thanks!

**Comment by lptr** [comment]
I think we should still fix the Javadoc example.

**Comment by jjohannes** [comment]
Example updated.
