### ISSUE TITLE
Remove wrapper zip after unzipping

### ISSUE THREAD

**Issue by brillenheini** [gradle/gradle#3605]
### Expected Behavior

To save space, it would be nice, if the wrapper would remove the downloaded zip file after it has been unzipped.

### Current Behavior

Unused zip files are consuming disk space in ~/.gradle/wrapper/dists, e.g.:

    gradle-4.1/
    gradle-4.1-bin.zip
    gradle-4.1-bin.zip.lck
    gradle-4.1-bin.zip.ok

**Comment by SUPERCILEX** [comment]
Still a great feature request.

**Comment by vlsi** [comment]
It would be nice if the zips were removed, especially for CI agents where users don't know `zip` is never really re-used.

**Comment by consp1racy** [comment]
I've been caching the zip file in CI:
* it's quicker to cache than the exploded archive
* I don't have to download it from Gradle
Not a fan of this change.
