### ISSUE TITLE
Question: project and task dependencies

### ISSUE THREAD

**Issue by nerro** [gradle/gradle#3608]
Hey,

I written a Gradle task to preload all dependencies on my CI server (saw it on https://github.com/gradle/gradle/issues/1049). All project dependencies were resolved except of dependencies from my custom task on `buildSrc` project.

My custom task extends `DefaultTask` and adds a custom configuration `wsimport` to generate some JAXB from WSDL file. Can you point me in right direction :smile: ?

Thanks.

**Comment by bmuschko** [comment]
This is rather a question for the [Gradle forum](https://discuss.gradle.org/). Would you mind transferring the discussion over there? Please also provide more information e.g. the code you are using.
