### ISSUE TITLE
[Modular Gradle] Support building Gradle plugins as Java modules

### ISSUE THREAD

**Issue by code2358** [gradle/gradle#3617]
This is a feature request to support Gradle plugins packaged as Jigsaw modules.

### Suggested Behavior
```
buildscript {
   ....
    dependencies {
        modulepath 'some:jigsaw_module:1.0.0' // goes to --modules 
    }
}
```
### Context
I want to write a Gradle plugin which depends on the java.smartcardio module of Java 9. As result of this dependency I am forced to compile the Gradle plugin as Jigsaw module. However, Gradle just supports classpath dependencies in the buildscript section.

**Comment by jjohannes** [comment]
It is unlikely that we can restructure Gradle and its plugin system to run modular.

As far as I know, if you just develop your plugin "the normal way" such that everything is on the classpath (aka unnamed module), ` javax.smartcardio` is available and accessible.
