### ISSUE TITLE
No such property: `junitXml` for class: `org.gradle.api.reporting.ReportContainer`

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#3627]
In Gradle 4.4, common testing infrastructure was extracted to `AbstractTestTask` class. 

### Expected Behavior
Given a class annotated with `@CompileStatic` and referencing `junitXml` property like `test.reports.junitXml`, it should compile without errors.

### Current Behavior
The compilation gives the following error:
`/buildSrc/src/main/groovy/Plugin.groovy: 579: [Static type checking] - No such property: junitXml for class: org.gradle.api.reporting.ReportContainer`

**Comment by jochenberger** [comment]
Yes, RC4 fixed the issue I reported on the forums, thanks.
