### ISSUE TITLE
init.gradle set gradle version don't support version with source?

### ISSUE THREAD

**Issue by zssng** [gradle/gradle#3631]
### Current Behavior

Error:'4.3.1-all' is not a valid Gradle version string (examples: '1.0', '1.0-rc-1')
### Context

    task wrapper(type: Wrapper) {
        gradleVersion = '4.3.1-all'
    }
### Your Environment

 * Build scan URL:

**Comment by bmuschko** [comment]
The Wrapper task provides a different property for setting the distribution type. You should declare it like this:

```
wrapper {
    gradleVersion = '4.3.1'
    distributionType = Wrapper.DistributionType.ALL
}
```

**Comment by zssng** [comment]
@bmuschko Thank you,it works.That's all i need. i should read the document more carefully.
