### ISSUE TITLE
PT_NOTE segments make UPX packed failed..

### ISSUE THREAD

**Issue by joelihn** [gradle/gradle#3634]
hi, i`m using upx under android armv8:

libA.so which packed with upx(with paramemetr --android-shlib),called by libB.so;
libB.so is a jni so, no matter use dynamic call or static call libA.so(packed with upx),the test.apk crashed

main-->libB.so -->libA-upx.so:

Debug with upx developer for many times,, at last we found there are two PT_NOTE segments make upx cannot work:

```
de-compress
$ upx -d -o libA-orig.so Test/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libtest.so

$ readelf --headers --notes libA-orig.so
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000062138 0x0000000000062138  R E    10000
  LOAD           0x0000000000062d98 0x0000000000072d98 0x0000000000072d98
                 0x0000000000000270 0x0000000000000270  RW     10000
  NOTE           0x0000000000000200 0x0000000000000200 0x0000000000000200
                 0x0000000000000024 0x0000000000000024  R      4
  NOTE           0x00000000000620a0 0x00000000000620a0 0x00000000000620a0
                 0x0000000000000098 0x0000000000000098  R      4

Displaying notes found at file offset 0x00000200 with length 0x00000024:
  Owner                 Data size       Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 3463ee29b3e940f525c95d491f3639d01fd81129

Displaying notes found at file offset 0x000620a0 with length 0x00000098:
  Owner                 Data size       Description
  Android              0x00000084       NT_VERSION (version)
```

The second PT_NOTE has a 0x15 and "r16-beta1" embedded in it, followed by about 0x74 bytes of zeroes ($ od -Ax -tx4c -j 0x000620a0 libA-orig.so | sed 10q) So that looks like a "post-processor" appended it after the static binder /bin/ld finished. It would be much more convenient if that note appeared together as part of only one PT_NOTE segment, and towards the low end of the first PT_LOAD rather the high end. What is the purpose of that note? Can it be omitted or deleted?

I don't know how to do it, and he suggested I go here to ask:"second PT_NOTE at the high-address end of PT_LOAD[0] causes problems. The ideal change would be to put all the PT_NOTEs together starting near the low-address end (at offset 0x200 in this case.)"

### Expected Behavior

> libA.so output is:
....
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 1.
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 1.
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: Source file name: /mnt/sdcard///*.
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: fopen
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: Not a typewriter
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: fopen
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 131694
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 21.
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 22.
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 23.
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 3.
09-29 13:58:55.594 14201 14201 D KEYSTORETESTJNI: 31.
09-29 13:58:55.596 14201 14201 D KEYSTORETESTJNI: 32.
09-29 13:58:55.596 14201 14201 D KEYSTORETESTJNI: Not a typewriter
09-29 13:58:55.596 14201 14201 D KEYSTORETESTJNI: 3.
09-29 13:58:55.596 14201 14201 D KEYSTORETESTJNI: 4.
...

### Current Behavior

> libA-upx.so output is:
...
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: 1.
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: 1.
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: Source file name: /mnt/sdcard///*.
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: fopen
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: Not a typewriter
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: fopen
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: 131694
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: 21.
09-29 13:48:46.427 13554 13554 D KEYSTORETESTJNI: 22.
09-29 13:48:46.428 13554 13554 D KEYSTORETESTJNI: 23.
09-29 13:48:46.428 13554 13554 D KEYSTORETESTJNI: 3.
09-29 13:48:46.428 13554 13554 D KEYSTORETESTJNI: 31.
09-29 13:48:46.437 13554 13554 F libc : Fatal signal 4 (SIGILL), code 1, fault addr 0x7f6f739d64 in tid 13554 (le.keystoretest)
09-29 13:48:46.445 462 462 W : debuggerd: handling request: pid=13554 uid=10242 gid=10242 tid=13554
09-29 13:48:46.530 13577 13577 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-29 13:48:46.531 13577 13577 F DEBUG : Build fingerprint: 'Xiaomi/gemini/gemini:7.0/NRD90M/V8.5.3.0.NAACNED:user/release-keys'
09-29 13:48:46.531 13577 13577 F DEBUG : Revision: '0'
09-29 13:48:46.531 13577 13577 F DEBUG : ABI: 'arm64'
09-29 13:48:46.531 13577 13577 F DEBUG : pid: 13554, tid: 13554, name: le.keystoretest >>> com.example.keystoretest <<<
09-29 13:48:46.531 13577 13577 F DEBUG : signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0x7f6f739d64
09-29 13:48:46.531 13577 13577 F DEBUG : x0 0000007f6f7d81f0 x1 0000007f8e92b452 x2 0000007f6f7cbb38 x3 0000000000000005
09-29 13:48:46.531 13577 13577 F DEBUG : x4 0000000000000000 x5 0000000000000000 x6 0000007f6f738000 x7 0000007f6f71767a
09-29 13:48:46.531 13577 13577 F DEBUG : x8 0000000000000000 x9 0000000000000001 x10 0000000000000001 x11 0000000000000006
09-29 13:48:46.531 13577 13577 F DEBUG : x12 ffffffffffffffff x13 0000007f8e3ac000 x14 0000007f8e3ad000 x15 0000007f8958e000
09-29 13:48:46.531 13577 13577 F DEBUG : x16 0000007ffcfd8850 x17 0000007ffcfd871f x18 00000000ffffffff x19 0000007f6f7d81f0
09-29 13:48:46.531 13577 13577 F DEBUG : x20 0000007f6f7cbb38 x21 0000007f8e92adb9 x22 0000000000000001 x23 0000000000000005
09-29 13:48:46.531 13577 13577 F DEBUG : x24 0000000000000000 x25 0000007f894ff1b9 x26 0000007f6f739d4c x27 0000007f8e94f000
09-29 13:48:46.532 13577 13577 F DEBUG : x28 0000000000000000 x29 0000007ffcfd8a20 x30 0000007f8e8ae3b8
09-29 13:48:46.532 13577 13577 F DEBUG : sp 0000007ffcfd8a10 pc 0000007f6f739d64 pstate 0000000080000000
09-29 13:48:46.541 13577 13577 F DEBUG :
09-29 13:48:46.541 13577 13577 F DEBUG : backtrace:
09-29 13:48:46.541 13577 13577 F DEBUG : #00 pc 0000000000001d64 anonymous:0000007f6f738000
09-29 13:48:46.541 13577 13577 F DEBUG : #1 pc 000000000000c3b4 /system/bin/linker64 (__dl__ZN6soinfo10call_arrayEPKcPPFvvEmb+360)
09-29 13:48:46.542 13577 13577 F DEBUG : #2 pc 000000000000c3b4 /system/bin/linker64 (__dl__ZN6soinfo10call_arrayEPKcPPFvvEmb+360)
09-29 13:48:46.542 13577 13577 F DEBUG : #3 pc 000000000000a3cc /system/bin/linker64 (__dl__Z9do_dlopenPKciPK17android_dlextinfoPv+540)
09-29 13:48:46.542 13577 13577 F DEBUG : #4 pc 0000000000007378 /system/bin/linker64 (__dl_dlopen+56)
09-29 13:48:46.542 13577 13577 F DEBUG : #5 pc 0000000000020980 /data/app/com.example.keystoretest-1/lib/arm64/libKeyStoreTest.so (Java_com_example_keystoretest_MainActivity_KeyStoreTest+3264)
09-29 13:48:46.542 13577 13577 F DEBUG : #6 pc 00000000000daf90 /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
09-29 13:48:46.542 13577 13577 F DEBUG : #7 pc 00000000000d19b4 /system/lib64/libart.so (art_quick_invoke_stub+580)
09-29 13:48:46.542 13577 13577 F DEBUG : #8 pc 00000000000de680 /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+204)
09-29 13:48:46.542 13577 13577 F DEBUG : #9 pc 000000000028c758 /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+312)
09-29 13:48:46.542 13577 13577 F DEBUG : #10 pc 0000000000285734 /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
09-29 13:48:46.542 13577 13577 F DEBUG : #11 pc 0000000000550d48 /system/lib64/libart.so (MterpInvokeVirtual+608)
09-29 13:48:46.543 13577 13577 F DEBUG : #12 pc 00000000000c4394 /system/lib64/libart.so (ExecuteMterpImpl+14228)
...

### Steps to Reproduce (for bugs)

I've a test project.

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Please open Android specific issues on the Android isse tracker.
