### ISSUE TITLE
Failed to publish publication 'AndroidDebug' to repository 'mavenLocal'

### ISSUE THREAD

**Issue by striboldt** [gradle/gradle#3635]
After upgrading to Gradle wrapper version 4.3.1 + gradle plugin 3.0.1 we are no longer able to publish to maven local in a one liner: ./gradlew clean assemble publishToMavenLocal

Expected Behavior:
.aar is build and published to local maven repo.

Current Behavior:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':AndroidProject:publishAndroidDebugPublicationToMavenLocal'.
> Failed to publish publication 'AndroidDebug' to repository 'mavenLocal'
   > Invalid publication 'AndroidDebug': artifact file does not exist: '/Users/mstr/Github/AndroidProject/build/outputs/aar/AndroidProject-debug.aar'

I can confirm that the .aar has not been generated.

It's possible to break up the execution into two independent  commands, which solves the problem:
./gradlew clean assemble
./gradlew publishToMavenLocal

This is of course not as convenient as a one liner.

Regards,
Morten

**Comment by marcin-onegini** [comment]
I have the same issue. It looks like the 'publishToMavenLocal' is executed before 'clean' and 'assemble'

**Comment by blindpirate** [comment]
@striboldt @marcin-onegini Thank you very much for reporting. Could you please provide a simple sample to reproduce it? It would greatly help us to find out the reason.

**Comment by striboldt** [comment]
I have created a Gist with some sample files (hope this will be sufficient):
https://gist.github.com/striboldt/f4963ed89b12773c0cd08f00ed9b275f

**Comment by ycuicui** [comment]
I confirm the issue.
As a workaround, i delete the build folders before launching the command! (my command is not exactly the same: "gradlew clean build publishToMavenLocal")
Sometime it works, sometime not!

**Comment by ycuicui** [comment]
I don't know if this may help, but i notice that when it fail, the Lint reports are not generated too.

**Comment by oehme** [comment]
You have to tell Gradle which task builds that artifact, otherwise it can't know that the task is not ready yet. There is a missing `builtBy "packageDebug"` there.

**Comment by bigdaz** [comment]
To clarify what @oehme said:
- Gradle executes things in parallel where possible. In this case Gradle doesn't know that you need to build `AndroidProject-debug.aar` before publishing. So we publish in parallel with building.
- The reason Gradle doesn't know this is because this information wasn't included when configuring the `MavenPublication` in the `maven-publish` plugin. This would probably happen if you called `MavenPublication.artifact(File)`. Gradle doesn't know where the file came from, or what tasks produce it.
- You can fix this by changing your build like something like this:

```
maven(MavenPublication) {
    artifact <taskThatProducesFile>
}
```

or

```
maven(MavenPublication) {
    artifact(<artifactFile>) {
          builtBy <taskThatProducesFile>
    }
}
```

**Comment by striboldt** [comment]
Thanks for the clarification. Now I'm able to publish again.

**Comment by vanlooverenkoen** [comment]
Method could not be found. This is the error:

> Exception thrown while executing model rule: PublishingPlugin.Rules#publishing(ExtensionContainer)

   > Could not find method buildyBy() for arguments [assembleRelease] on DefaultMavenArtifact_Decorated aar:null of type org.gradle.api.publish.maven.internal.artifact.DefaultMavenArtifact.

and this is my publish.gradle file that is applied in my build.gradle

```
apply plugin: 'maven-publish'

ext { LOCAL_VERSION_NUMBER = 1 }
apply from: 'dev.properties'

def publishPath = rootProject.hasProperty("localMavenPath") ? localMavenPath : "file://$rootProject.buildscript.sourceFile/../../maven/"
def artifactVersion = CORE_ARTIFACT_VERSION.replace('\"', '') + (ext.uploadLocal ? '.' + LOCAL_VERSION_NUMBER : '')

task androidSourcesJar(type: Jar) {
    classifier = 'sources'
    from android.sourceSets.main.java.sourceFiles
}

artifacts {
    archives androidSourcesJar
}

publishing {
    repositories {
        maven {
            url publishPath
        }
    }

    publications {
        maven(MavenPublication) {
            groupId CORE_ARTIFACT_PACKAGE.replace('\"', '')
            version artifactVersion
            artifactId CORE_ARTIFACT_NAME.replace('\"', '')
            artifact("$buildDir/outputs/aar/core-release.aar") {
                builtBy "assembleRelease"
            }

            artifact androidSourcesJar

            pom.withXml {
                def dependenciesNode = asNode().appendNode('dependencies')

                //Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
                configurations.compile.allDependencies.each {
                    if (it instanceof ExternalModuleDependency) {
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        dependencyNode.appendNode('groupId', it.group)
                        dependencyNode.appendNode('artifactId', it.name)
                        dependencyNode.appendNode('version', it.version)
                    }
                }
            }
        }
    }
}

```

**Comment by vanlooverenkoen** [comment]
But this does work well

            artifact ("$buildDir/outputs/aar/core-release.aar") {
                builtBy tasks.getByPath("assembleRelease")
            }

Why is that?

**Comment by oehme** [comment]
You need to update your Gradle version, 4.1 didn't have this method.

**Comment by vanlooverenkoen** [comment]
To what version?

**Comment by oehme** [comment]
I'm sorry I was mistaken - A String won't work here (something we should probably fix). You should be able to simply use a reference to that task:

```
artifact ("$buildDir/outputs/aar/core-release.aar") {
  builtBy assembleRelease
}
```

**Comment by ControlTheBit** [comment]
When I try this, I get the following error:
`Could not get unknown property 'assembleRelease' for DefaultMavenArtifact_Decorated aar:null of type org.gradle.api.publish.maven.internal.artifact.DefaultMavenArtifact.`

I can't seem to find the mistake. Ideas?

My config:

```
publishing {
    publications {
        aar(MavenPublication) {
            groupId 'this.is.my.package'
            // version property will be provided by the build environment
            artifactId project.getName()

            // Tell maven to prepare the generated "*.aar" file for publishing
            artifact("$buildDir/outputs/aar/${project.getName()}-release.aar") {
                builtBy assembleRelease
            }
        }
    }
}
```

Versions:
`"org.jfrog.buildinfo:build-info-extractor-gradle:4.7.5"`
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip`

**Comment by marcphilipp** [comment]
@ControlTheBit Sounds like the `assembleRelease` task is not defined yet when you reference it. Could you post a sample project to reproduce the issue?

@oehme Why doesn't passing the task name as a `String` work?

**Comment by ControlTheBit** [comment]
@marcphilipp I solved the issue for now by changing our build script on CI from 
```
- ./gradlew clean assembleRelease artifactoryPublish -PredactedArtifactoryUsername=${REPO_USERNAME} -PredactedArtifactoryPassword=${REPO_PASSWORD} -Pversion=${BITBUCKET_BRANCH}-SNAPSHOT
```

to

```
- ./gradlew clean
- ./gradlew assembleRelease
- ./gradlew artifactoryPublish -PredactedArtifactoryUsername=${REPO_USERNAME} -PredactedArtifactoryPassword=${REPO_PASSWORD} -Pversion=${BITBUCKET_BRANCH}-SNAPSHOT
```

So we can build the library at least. I don't have the time to create a project to reproduce this now, but I simply created a new android project with the default "app" module and added a second module of type library to it. Then I added the code from my first post into the build.gradle of the library module. That's pretty much it. Thanks for maintaining this library! 👍

**Comment by ChanSek** [comment]
Looks like, I have a similar problem. Can anybody please help me out.

https://stackoverflow.com/questions/56983000/cannot-convert-assemblerelease-to-a-task

**Comment by iZooto-sdk** [comment]
ERROR: Failed to resolve: android-sdk

**Comment by nateridderman-lilly** [comment]
For an android library project, I had to use `builtBy assemble` even though I can run the assembeRelease task from the command line.

**Comment by iZooto-sdk** [comment]
Assemble

**Comment by GuilhE** [comment]
> artifact("$buildDir/outputs/aar/${project.getName()}-release.aar") {
>                 builtBy assembleRelease
>             }

How does it translate to `.kts`?
Thanks.

**Comment by androideveloper** [comment]
> For an android library project, I had to use builtBy assemble even though I can run the assembleRelease task from the command line.

Thanks for the tip! I also couldn't use `bundleReleaseAar` although it is available in task list
