### ISSUE TITLE
Produce a `JavaLibraryPlatform` and consume it in a multi-project build

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3639]
For this to work properly, consuming a `JavaLibraryPlatform` should be consistent whether consumed via project dependency, composite build or external repository. This would either require a separate project plugin so the producing project doesn't have any artifact, or have the consumer wired into the the actual `JavaLibraryPlatform` component when resolving a project dependency.

**Comment by ljacomet** [comment]
Work being done in #7945
