### ISSUE TITLE
Add rejectAll() to version constraints to express incompatibility

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3643]
```
constraints {
    compile 'org:Y' {
        version { rejectAll() }
    }
}
```

Can be implemented by using the exists reject mechanism in version constraints.

Test cases:
- defining
- publishing
- consuming

**Comment by bigdaz** [comment]
We should have some test coverage for this in `RichVersionConstraintsResolveIntegrationTest`, as well as in tests for publishing to ivy/maven. Currently, we only test that this works for `rejectAll()` in the build script, not for a published module that has a `reject '+'` constraint.

**Comment by bigdaz** [comment]
So I fixed a bug that meant `rejectAll()` was broken when publishing and resolving: https://github.com/gradle/gradle/commit/ec0669028229a97a2f6fe66a99c10e9e765d54ae.

Added some test coverage for this specific case: https://github.com/gradle/gradle/commit/03a16916f211d643f4f6a2fe8d553851d9b5f4ed

Not sure if we think this is sufficient coverage. I was surprised that we had no coverage for published constraints that included any `reject` version constraints. (In fact our test fixtures were broken when trying to produce a `.module` file like this).

**Comment by melix** [comment]
Thanks, eagle eye @bigdaz !

**Comment by melix** [comment]
Can this be closed now?

**Comment by bigdaz** [comment]
Up to you @melix. Do you consider that we have sufficient integration test coverage for publishing and resolving `reject()` and `rejectAll()` constraints?
