### ISSUE TITLE
[Build Cache] support 'compilePlayBinaryScala' as Cacheable Task

### ISSUE THREAD

**Issue by devishree90** [gradle/gradle#3648]
Hi Gradle Team,

I'm working on play project which uses gradle as build system. I'm trying to use build caching for better performance. From build scan, i observe 'compilePlayBinaryScala' is not cacheable and most of the other tasks are dependent on 'compilePlayBinaryScala'. Enabling caching for 'compilePlayBinaryScala' will really scale up the build.

I would like to know if there are plans to make this task cacheable. If not, i would like to request to enable caching for 'compilePlayBinaryScala' task.

**Comment by devishree90** [comment]
@blindpirate - I have submitted pull request for this issue. I'm not quite sure what tests need to be updated. Could you suggest recommended tests for this change?

**Comment by blindpirate** [comment]
@devishree90 Thank you very much for this! I'd recommend to take a look at [BuildCacheFixture](https://github.com/gradle/gradle/blob/2534889d68c8b22592a194ace59a8c084095c633/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/BuildCacheFixture.groovy#L24) and its subclasses, which are all about build cache test.

We look forward to your contribution!

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/3804.
