### ISSUE TITLE
ivy-publish does not use the correct configurations from project dependencies

### ISSUE THREAD

**Issue by m-raab** [gradle/gradle#3650]
I created a java project with some compile and runtime dependencies.
```
plugins {
    id 'java'
    id 'ivy-publish'
}
...
dependencies {
    compile 'org.apache.logging.log4j:log4j-core:2.2'
    compile 'commons-io:commons-io:2.1'
    runtime 'commons-codec:commons-codec:1.4'
}
```
The generated ivy.xml contains the runtime configuration, but all dependencies are assigned to the compile configuration.

```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
  <info organisation="com.testcase" module="testcase" revision="1.0.0" status="integration" publication="20171128214217"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="runtime" visibility="public"/>
  </configurations>
  <publications>
    <artifact name="testcase" type="jar" ext="jar" conf="compile"/>
  </publications>
  <dependencies>
    <dependency org="commons-codec" name="commons-codec" rev="1.4" conf="compile-&gt;default"/>
    <dependency org="org.apache.logging.log4j" name="log4j-core" rev="2.2" conf="compile-&gt;default"/>
    <dependency org="commons-io" name="commons-io" rev="2.1" conf="compile-&gt;default"/>
  </dependencies>
</ivy-module>
```
In Gradle 3.x it was working correct.
### Expected Behavior

The dependencies should be assigned to the correct configuration from the project dependencies configuration:
```
<dependency org="commons-codec" name="commons-codec" rev="1.4" conf="runtime-&gt;default"/>
```

### Current Behavior

All dependencies are assigned to the compile configuration:
```
 <dependency org="commons-codec" name="commons-codec" rev="1.4" conf="compile-&gt;default"/>
```

### Context

Ivy publishing is used in our projects and we expect that the ivy generation is correct.

### Steps to Reproduce (for bugs)

Create a simple java project with following configuration:

build.gradle
```
plugins {
    id 'java'
    id 'ivy-publish'
}

group 'com.testcase'
version '1.0.0'

sourceCompatibility = 1.8

publishing {
    publications {
        ivyJava(IvyPublication) {
            from components.java
        }
    }
    repositories {
        ivy {
            // change to point to your repo, e.g. http://my.org/repo
            url "${project.buildDir}/repo"
            layout('pattern') {
                ivy '[organisation]/[module]/[revision]/[type]s/ivy-[revision].xml'
                artifact '[organisation]/[module]/[revision]/[ext]s/[artifact]-[type](-[classifier])-[revision].[ext]'
            }
        }
    }
}

repositories {
    jcenter()
}

dependencies {
    compile 'org.apache.logging.log4j:log4j-core:2.2'
    compile 'commons-io:commons-io:2.1'
    runtime 'commons-codec:commons-codec:1.4'
}
```

Run
```
gradlew publish
```

### Your Environment

```
------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Mac OS X 10.13.1 x86_64
```

**Comment by bigdaz** [comment]
Thanks for your detailed report. For historic reasons, the `compile` configuration in Gradle doesn't really represent exactly what's needed to compile your code. You can read more about this in Cedric's [excellent blog post](https://blog.gradle.org/incremental-compiler-avoidance). We didn't want to replicate this bug into the `maven-publish` and `ivy-publish` plugins. 

Instead, we introduced the concept of `api` in Gradle, which maps exactly to what is required to compile against the library. Any dependencies declared for the `api` in Gradle will be placed into the `compile` Ivy configuration when using the `ivy-publish` plugin.

If you are creating a Java library and want to use `ivy-publish` for publishing, then I suggest you switch to use the [`java-library` plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html) for your project. This provides strict separation of API and implementation, which aids with compile avoidance, and produces the 'correct' Ivy XML for your intended use.
