### ISSUE TITLE
Documentation for Gradle command line exit codes

### ISSUE THREAD

**Issue by ghost** [gradle/gradle#3652]
I have a script which calls `gradle` command line. It handles multiple tasks, in each task it calls `gradle`. If Gradle returns exit code other than `0`, it prints out a log and continues to handle next tasks. Most of the times, the exit code is `1`.

Now when the script is calling Gradle, I run `gradle --stop`. My script gets `1` exit code and continues the next tasks.

### Expected Behavior

Could you change the exit code when Gradle stops when receiving stop commands from itself? And, it would be great if you have documentation about all exit codes on your website. Currently I cannot find one.

### Current Behavior

- When build fails internally, Gradle command line returns `1` exit code most of the times.
- Calling `gradle --stop` also make it returns `1` exit code.

### Context

It would be great if `gradle --stop` returns another exit code, other than `1`.

Thank you,

**Comment by ov7a** [comment]
Sorry for the late reply.

This is a valid documentation issue

Related:
* https://github.com/gradle/gradle/issues/12374
