### ISSUE TITLE
gradle bootRun returns an error that the commandline is too long

### ISSUE THREAD

**Issue by frederichenry** [gradle/gradle#3653]
when running gradle bootRun I ran into an error java.io.IOException: CreateProcess error=206, The filename or extension is too long because of a really long classpath dependencies.

I know that there is a workaround : http://tuhrig.de/gradles-bootrun-and-windows-command-length-limit/.

Note: this happens only on windows.

When asked on spring boot I received this as response (https://github.com/spring-projects/spring-boot/issues/11197):

The BootRun task is a subclass of Gradle's JavaExec. If the functionality were added to JavaExec, all JavaExec-based tasks would benefit.

Could this be implemented?

**Comment by oehme** [comment]
Yes, we have considered this, though it is not currently a priority. See https://github.com/gradle/gradle/issues/1989
