### ISSUE TITLE
Improved Error Messaging

### ISSUE THREAD

**Issue by jsiddharth** [gradle/gradle#3661]
Gradle Exceptions are too cryptic to understand. It will greatly help to know where the error/exception is coming from. 

As an Example, I am pasting a exception that I got. The below exception is very helpful to the gradle developer, but completely useless to a user.

For example, 
1) _The supplied build action failed with an exception._ : Obviously, not useful.
2) _Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :coregeneral._ : Which _Project_ If I knew the name of the project / file that this exception is referring to, I could better debug my issue. If a file expected was missing, where was the file expected ? In which path are you trying to find a file that is missing ? I have no clue
3) _Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :coregeneral._ : I have a "compile project('coregeneral') in my current file, but I am wondering what the "Default" is ? where are you expecting the "Default".

Good error messages help hack into issues quickly. Please improve on the error handling and provide more information.

**Context :** The context of the issue is mentioned above, I am not looking for help on the below issue. This issue has been raised to "request for a improvement on the error handling and messaging in gradle".
```
**Please do not just close this issue, its a serious requirement. I have taken a lot of time and pain to log this, if you need more information ask for it. I am happy to provide it.**

org.gradle.tooling.BuildActionFailureException: The supplied build action failed with an exception.
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerConnection$CancellableActionRunner.run(CancellableConsumerConnection.java:104)
	at 
...
...
...

Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':compileClasspath'.
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:97)
	at )
...
...
...
Caused by: org.gradle.internal.component.model.ConfigurationNotFoundException: Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :coregeneral.
	at org.gradle.internal.component.model.LocalComponentDependencyMetadata.selectConfigurations(LocalComponentDependencyMetadata.java:124)
	at 
...
..
...
```

### Steps to Reproduce (for bugs)
**Main Project settings.gradle snippet**
```
rootProject.name = 'mnoxwebserviceendpoints'

def projectRootDir = new File("./", "../../checkout")
def mnoxbackendDir = new File(projectRootDir, "mnoxbackendv2")
def mnoxwebservicesDir = new File(projectRootDir, "mnoxwebservicesv2")

include ':coregeneral'
project (':coregeneral').projectDir = new File (mnoxbackendDir, 'coregeneral')
```
 
**Main Project build.gradle snippet**
apply plugin: 'java'
apply plugin: 'war'
repositories {
    jcenter()
}
dependencies {
    compile 'org.slf4j:slf4j-api:1.7.21'
// Many more dependencies
	compile project('coregeneral')
     //many more projects
	compile files('build/classes/main') ;
    testCompile 'junit:junit:4.12'
}

war {
webXml = file('WebContent/WEB-INF/web.xml') // cocompies a file to WEB-INF/web.xml
}
task appProperties(type: Copy) {
  from 'src/app.properties'
  into 'build/app.properties'
  expand([
    buildType: '$buildType'
  ])
}
sourceSets {
    main {
        java {
            srcDir 'src'
        }
    }
}
jar {
    baseName='mnoxwebserviceendpoints'
    from ('build.classes.main')
}
task deploy (dependsOn: war){
    copy {
        from "build/libs"
        into "gradle_properties_tomcat_webapps_folder"
        include "*.war"
    }
}

**CoreGeneral Settings.gradle**
`rootProject.name = ':coregeneral'`

**CoreGeneral build.gradle**
apply plugin: 'java'
repositories {
    jcenter()
}

dependencies {
    compile 'org.slf4j:slf4j-api:1.7.21'
//many more dependencies 
    testCompile 'junit:junit:4.12'
}
jar {
    baseName='coregeneral'
    from ('build/classes/main')
}
sourceSets {
    main {
        java {
            srcDir 'src'
        }
    }
}
allprojects {
    apply plugin: 'java'
    sourceCompatibility = 1.7
    targetCompatibility = 1.7
}

**Gradle Properties**
```
org.gradle.jvmargs=-Xmx2120M -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
```

### Your Environment

 * Build scan URL:

**Comment by jsiddharth** [comment]
Note : One more link on the web that hints at need for improved debug information during error and exceptions 

https://discuss.gradle.org/t/configuration-compile-declares-a-dependency-on-configuration-default-which-is-not-declared-in-the-module-descriptor/11431

**Comment by jsiddharth** [comment]
To clarify my expectation better. I need the following style of error messages for Exceptions too.

FAILURE: Build failed with an exception.

```
* Where:
Settings file '/Users/jsiddharth/Desktop/v2/checkout/mnoxwebservicesv2/mnoxwebserviceendpoints/settings.gradle' line: 7

* What went wrong:
A problem occurred evaluating settings 'mnoxwebserviceendpoints'.
> Project with path ':coregeneral' could not be found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED
```

**Comment by eriwen** [comment]
This is really an Epic, because there are a bunch of ways to improve this. I agree that there's a lot of opportunity to make this much better.
