### ISSUE TITLE
Produce valid Ivy/Maven metadata files when publishing dependency without version

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3667]
Gradle will happily publish and resolve a dependency with an empty version to an Ivy descriptor file, or a Maven POM file. However, these published metadata files may not be valid for consuming by Ivy/Maven.

Possible solutions, not mutually exclusive:
- Publish dependency constraints into `<dependencyManagement>` (POM)
- Publish dependency on a constraints platform with `<scope>import</scope>` (POM)
- Combine all constraints to determine the version to publish. (Ivy/POM)
- Publish _resolved_ version for dependency (Ivy/POM)

See #3655

**Comment by bigdaz** [comment]
Or we should consider separating the _declared_ versions in a build script from the _published_ versions: there are good arguments for publishing the _resolved_ version rather than the declared version, since that's the one you actually built and tested with.

I think this publishing is something we should include in any discussions about "best practices for version management".

**Comment by ljacomet** [comment]
For Gradle 5.0 it has been discussed that, in addition to the already available changes, Gradle would warn when it detects that a created `pom.xml` will be invalid when consumed by a Maven project, and similarly for `ivy.xml` and Ivy.

Note that the following items:
> * Publish dependency constraints into <dependencyManagement> (POM)
> * Publish dependency on a constraints platform with <scope>import</scope> (POM)

have been added to the publication logic for `maven-publish` plugin already.

**Comment by ljacomet** [comment]
The changes around logging for potential compatibility issues missed Gradle 5.0 but will be in 5.2.
Since there is now a way to publish resolved versions (#7926), closing this issue.
