### ISSUE TITLE
Ear plugin validates application.xml file if DTD is set at configuration phase

### ISSUE THREAD

**Issue by petehayes** [gradle/gradle#3677]
### Expected Behavior
The gradle ear plugin should not read a specified DTD in a custom application.xml descriptor at gradle configuration time.

### Current Behavior
At gradle configuration time, if a DTD is specified in a custom application.xml descriptor, the DTD is read, and possibly downloaded if external.  If the external site is not available, gradle stops with an error.

### Context
We specify a DTD and gradle hits this site everytime it is configuring our project and sporadically failing when not available.

### Steps to Reproduce (for bugs)
See this project here: https://github.com/petehayes/ear-xml-validation

Clone and run `./gradlew tasks`

It will fail with a no such host exception as I intentionally gave the DTD reference a bad host name

### Your Environment
Ubuntu 16.04 machine

**Comment by cdancy** [comment]
@bmuschko or any other gradle dev would it be possible to take a look at this and/or provide a work around? This breaks running our build with `--offline` mode.

**Comment by cdancy** [comment]
Any updates here? Our CI infrastructure was crippled due to the oracle endpoint that serves this going up and down throughout the day today.

**Comment by marcphilipp** [comment]
I checked the code: We cannot turn off downloading the DTD because the XML parser has `XMLConstants.FEATURE_SECURE_PROCESSING` enabled which requires access to external DTDs.

However, you should be able to workaround the connectivity issues by specifying the `javax.xml.catalog.files` system property and adding a catalog file that "redirects" the URI to a local copy of the DTD. See https://docs.oracle.com/javase/9/docs/api/javax/xml/catalog/CatalogFeatures.html for details.

**Comment by cdancy** [comment]
Thanks @marcphilipp we'll look into this and get back.

**Comment by vadakr** [comment]
Just wanted to post my experience with creating a local catalog to work around this problem. Note that I was **NOT** successful in getting it to work, so decide if you want to read further.

I have an 'application.xml' file defined with -

`<!DOCTYPE application PUBLIC "-//Sun Microsystems, Inc.//DTD J2EE Application 1.3//EN" "http://java.sun.com/dtd/application_1_3.dtd">`

I get this error when the Gradle ear task runs -

```
> Failed to apply plugin [id 'org.gradle.ear']
   > java.io.IOException: Server returned HTTP response code: 403 for URL: http://java.sun.com/dtd/application_1_3.dtd
```

I am using OpenJDK 12.

I created a catalog file called 'catalog.xml' and saved it to the folder 'c:\xml'. Here are its contents -

```
<?xml version="1.0" encoding="UTF-8"?>
<catalog  xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <public 
       publicId="-//Sun Microsystems, Inc.//DTD J2EE Application 1.3//EN"
       uri="file:///c:/xml/application_1_3.dtd"/>
</catalog>
```
[Source](https://docs.oracle.com/javase/9/core/xml-catalog-api1.htm)

I manually downloaded http://java.sun.com/dtd/application_1_3.dtd and saved it to 'c:\xml\application_1_3.dtd'. Note how the catalog file above "redirects" the publicId to a local URI.

I then created a file called 'jaxp.properties' and saved it to 'JAVA_HOME/lib' ([source](https://docs.oracle.com/javase/tutorial/jaxp/properties/usingProps.html)). Note that the source states that this file should go into the JRE/lib folder under JAVA_HOME. But there's no JRE folder under OpenJDK 12, so I put it into 'lib'. Here are the contents of 'jaxp.properties' -

`javax.xml.catalog.files=file:///c:/xml/catalog.xml`

This basic setup would not work around the issue. So I tried a few flavors of the above -

1. I tried saving 'jaxp.properties' to 'JAVA_HOME/conf' ([source](https://docs.oracle.com/javase/9/docs/api/javax/xml/catalog/CatalogFeatures.html))
2. I tried making the URI in the catalog file relative ([source](https://docs.oracle.com/javase/9/core/xml-catalog-api1.htm))
3. There is an interesting property called '[javax.xml.accessExternalDTD](https://docs.oracle.com/javase/tutorial/jaxp/properties/properties.html)' which lets you control whether external DTDs should be accessed. I set this in 'jaxp.properties' as -

`javax.xml.accessExternalDTD=""`

I could not get any of these to work. I was curious as to why option 3 above didn't work, but looking at the [createParser()](https://github.com/gradle/gradle/blob/master/subprojects/ear/src/main/java/org/gradle/plugins/ear/descriptor/internal/DefaultDeploymentDescriptor.java) method, I at least understand why. The statement -

`parser.setProperty(ACCESS_EXTERNAL_DTD, ALLOW_ANY_EXTERNAL_DTD)`

overrides my system property with "all". What is interesting though is that there's a comment above that line that says -

> // If not set for >= JAXP 1.5 / Java8 won't allow referencing DTDs, e.g.
> // using http URLs, because Groovy's XmlParser requests FEATURE_SECURE_PROCESSING

But the Javadoc for ACCESS_EXTERNAL_DTD suggests that FEATURE_SECURE_PROCESSING should be restricting external access, not allowing it. ([source](https://docs.oracle.com/javase/7/docs/api/javax/xml/XMLConstants.html#ACCESS_EXTERNAL_DTD))

> When FEATURE_SECURE_PROCESSING is enabled, it is recommended that implementations restrict external connections by default, though this may cause problems for applications that process XML/XSD/XSL with external references.

I may have misunderstood that comment in the code, but wanted to point it out anyway.

After spending about 4 hours trying this and that, I reluctantly removed the DOCTYPE from my application.xml to get past the problem.
