### ISSUE TITLE
CompositeBuildDependencySubstitutions:80 is too verbose

### ISSUE THREAD

**Issue by calvertdw** [gradle/gradle#3686]
### Expected Behavior
Run large composite builds with `--info` without large portions of the log being filled by
"Found no composite build substitute for module 'some.group:some-artifact."

### Current Behavior
Half of the gradle log when run with --info is filled with something like this:

Found no composite build substitute for module 'org.apache.maven:maven-settings'.
Found no composite build substitute for module 'org.apache.maven:maven-profile'.
Found no composite build substitute for module 'org.apache.maven:maven-artifact-manager'.
Found no composite build substitute for module 'org.codehaus.plexus:plexus-utils'.
Found no composite build substitute for module 'org.codehaus.plexus:plexus-container-default'.
Found no composite build substitute for module 'org.apache.httpcomponents:httpcore'.
Found no composite build substitute for module 'org.apache.httpcomponents:httpcore-nio'.
Found no composite build substitute for module 'org.apache.httpcomponents:httpclient'.
Found no composite build substitute for module 'commons-logging:commons-logging'.
Found no composite build substitute for module 'org.ejml:core'.
Found no composite build substitute for module 'commons-beanutils:commons-beanutils'.
... goes on ...

### Context
This output is not relevant to the user. Logs become overwhelmed by this message and it is difficult to debug other problems.

### Steps to Reproduce (for bugs)
Run any project with composite builds with --info.

### Your Environment
Gradle 4.3.1

**Comment by big-guy** [comment]
I've switched this to use debug-level logging in master and it'll be in 4.5.

Thanks!
