### ISSUE TITLE
Module metadata is not correctly written to/from the dependency cache

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3712]
Adam reported this issue: https://github.com/gradle/gradle-native/issues/329, which is due to the `Usage` attribute not being correctly written to the cache. We have special handling for this attribute in the `ModuleMetadataParser`, but not in the `ModuleMetadataSerializer`.

Inspection shows that we have a similar problem with "dependencyConstraints": these are parsed correctly from module metadata, but not written to/from the cache.

Both of these cases mean that we'll be able to see different behaviour simply by running the same build twice: the second time around component attributes won't be set and the dependency constraints won't be applied. (And likely some other things we've missed).

We need to solve this problem in a systematic way that stops us making these problems in the future. Some options:
- Update our test fixtures so that we always resolve twice, the second time from the cache
- Change our production code so that instead of using the values parsed directly from the repository, we first write to the cache and then read the module metadata back out of it immediately.
- Write the JSON file as-is to the cache, rather than a binary representation of it.

I prefer something that enforces this in the production code, rather than something relying on test infrastructure, but I'd be happy with any solution.

**Comment by bigdaz** [comment]
Note that test coverage _must_ involve a remote repository, since we bypass the cache for local (file) repositories.

**Comment by bigdaz** [comment]
Note that test coverage _must_ involve a remote (HTTP) repository. Caching is bypassed for local repositories.
That's how I didn't pick up gradle/gradle-native#329: the coverage involved resolving from a file repository, and I did the same in my manual testing. As soon as I changed `AbstractIvyPublishIntegTest` to _resolve_ via an HTTP server, the test blows up on the `assert` here: https://github.com/gradle/gradle/blob/d9fb41dfff9b1dfe9b38cd92b348585269d6438e/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/ModuleMetadataSerializer.java#L146-L159

**Comment by melix** [comment]
That's clearly not the first time we're beaten by this, and it's too easy to forget. One possible approach would be to add a test for module metadata serializer that simulates what happens in a lightweight manner:

- have a list of sample pom/ivy/Gradle metadata files
- parse them
- use `ModuleMetadataSerializer` to serialize them
- read back using `ModuleMetadataSerializer`
- assert that the read version == the written version
