### ISSUE TITLE
Gradle startup script should attempt to use ./gradlew if present

### ISSUE THREAD

**Issue by carymrobbins** [gradle/gradle#3713]
I usually have a shell `alias gr=gradle`; however, I have recently updated to be -

```bash
alias gr='$(if [ -f ./gradlew ]; then echo ./gradlew; else echo gradle; fi)'
```

It may be valuable for the gradle startup script to do this check for you for convenience.
For what it's worth, I'm currently using the ArchLinux community package -

```
% pacman -Q gradle
gradle 4.3.1-1
```

**Comment by blindpirate** [comment]
> It may be valuable for the gradle startup script to do this check

Do you mean we add this check into `<gradle-distribution>/bin/gradle` script? It would be a bit tricky if users want to try different gradle version on a project which has `gradlew`. What should they do? Run `gradle --no-gradlew`?

**Comment by jochenberger** [comment]
For a multi-project build, you'd also have to check if there is a `gradlew` in the *root* project.
