### ISSUE TITLE
Reference chocolatey in installation doc

### ISSUE THREAD

**Issue by rocklass** [gradle/gradle#3717]
Can you please reference chocolatey as a package manager in installation doc (https://gradle.org/install/#with-a-package-manager)?

The command line to install it is: choco install gradle

I'm maintaining this version very regularly.

You can check it here: https://chocolatey.org/packages/gradle

Thanks

**Comment by bmuschko** [comment]
We used to list Chocolatey but took it out as the [latest version was always lagging behind](https://github.com/gradle/gradle/issues/1631). How are you planning to ensure that the package is always updated within a reasonable time frame going forward?

**Comment by rocklass** [comment]
I receive notifications when a new release of Gradle is available, so I can update the package very quickly, as you can see in [version history](https://chocolatey.org/packages/gradle).

I'm maintaining this package since october and I have published all versions of Gradle since that date in a very short time.

**Comment by bmuschko** [comment]
@eriwen Do you think the times between publishing Gradle and having it available on Choco are acceptable and make it worthwhile to list it again?

**Comment by rocklass** [comment]
For example, I have already submitted version 4.4 ([link](https://chocolatey.org/packages/gradle/4.4.0))

**Comment by eriwen** [comment]
Wow, 35k downloads just from chocolatey already. That's definitely legit enough to add back, and I'll trust if you @rocklass if you say you're on top of new releases. 

This is now back at https://gradle.org/install/

**Comment by axias41** [comment]
> 
> 
> Wow, 35k downloads just from chocolatey already. That's definitely legit enough to add back, and I'll trust if you @rocklass if you say you're on top of new releases.
> 
> This is now back at https://gradle.org/install/

As 2019-05-22, I can't see it

**Comment by lacasseio** [comment]
There was some legit security concerned against packages that we don't have ownership over. Our fix until we can discuss this further internally is to remove it from our documentation. It's nothing against Chocolatey or the maintainer. It's simply around security concern about the packaging process. The Linux package is a heavily modified Gradle, all in good faith, but cause failures that are introduced by those modifications. We can see that someone with ill intent could cause more than build failures.
