### ISSUE TITLE
Add more test coverage for metadata sources

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3718]
@melix I've "merged" your PR with a bunch of rework and refactoring. The big difference is that the link between the DSL `metadataSources` and the instances used in `ExternalResourceResolver` is much simpler and a lot more hard-coded. We translate the user config to a set of booleans to decide which metadata sources to use, and instantiate them directly if required. This is sufficient for what we need.

I brought over your `LegacyArtifactLookupResolveIntegrationTest` but I think we need a bit more test coverage for different combinations of `metadataSources`. Luckily the `FlatDirectoryArtifactRepository` is just an ivy repository with only the `artifact()` metadata source configured, but we probably want to test things like:
- Opt-out of `gradleMetadata()` and see that the `.module` file isn't requested
- Opt-in to `artifact()` with experimentalFeatures and see that we check for a `jar` file
- Some other combinations of metadata sources, including just `mavenPom()` or just `ivyDescriptor()` or just `gradleMetadata()`
  - We might want to update `AbstractModuleDependencyResolveTest` so that in most cases we just test a single metadata source, and then have some separate tests that verify they work in combination.

Also, add samples and documentation

**Comment by bigdaz** [comment]
Some test coverage: https://github.com/gradle/gradle/commit/c22adbfefd9282c795287e2946f29d1f3733c7e7
