### ISSUE TITLE
Throw deprecation warnings as exceptions in TestKit

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#3727]
## Context

As a part of deprecation warnings improvement #3728 , we're going to suppress warnings from 3rd-party plugins by default. However, this would make plugin developers not aware of their usage of deprecated API. We should throw exceptions when deprecated API is used in TestKit, until disabled by developers explicitly.

**Comment by big-guy** [comment]
Now that we have `--warning-mode=fail`, I think plugin developers can accomplish this on their own by running with that option.
