### ISSUE TITLE
Rethink Dependency(Constraint)Metadata interfaces and adapter structure

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3732]
Follow up to #3697, https://github.com/gradle/gradle/pull/3783#discussion_r157642695.

There are a couple of things here to reconsider:
- Rename internal interfaces `DependenyMetadata` and `VariantMetadata ` to avoid name duplication with public interfaces
- Do we really need separate interfaces for `DirectDependencyMetadata` and `DependencyConstraintMetadata`. Can we get rid of the term _direct dependency_ here? Can we simplify the hierarchy of adapters which all share the same implementation (at the moment)?
- Use a different name for `DependenciesMetadata` (the collection). It's confusing as it is too similar to `DependencyMetadata`.

**Comment by oehme** [comment]
Is this atill planned for 4.8?

**Comment by ljacomet** [comment]
No, removed the milestone reference.

**Comment by jjohannes** [comment]
The current structure has been accepted and the interfaces have been de-incubated for 6.0
