### ISSUE TITLE
Gradle 4.4: Included build 'buildSrc' cannot have included builds.

### ISSUE THREAD

**Issue by VenelinPetkov** [gradle/gradle#3736]
Cannot set includedBuild in Gradle 4.4 in buildSrc.

### Expected Behavior
In Gradle 4.3.1 buildSrc settings were allowed to have includedBuilds

### Current Behavior
In Gradle 4.4 the build sync is throwing an error:
Included build 'buildSrc' cannot have included builds.

### Context
composite build

**Comment by oehme** [comment]
@bigdaz I assume this is intended behavior, as nested composites are not allowed in general. Can you verify that's the intention?

**Comment by bigdaz** [comment]
Yep, if this was working in 4.3.1, that was by coincidence.

**Comment by oehme** [comment]
Thanks Daz, closing as expected behavior.
