### ISSUE TITLE
Document log format in userguide

### ISSUE THREAD

**Issue by dmolesUC3** [gradle/gradle#3741]
The [Logging chapter](https://docs.gradle.org/current/userguide/logging.html) of the userguide doesn't document the log format -- I tried `String.format()` style (`%s`) and `MessageFormat` style (`{0}`) before drilling down into what proved to be the SLF4J source code to find `{}`.

I understand this is just the way SLF4J does things, but for those of us that aren't familiar with SLF4J it would be nice if the Gradle docs provided at least one format-string example.

**Comment by blindpirate** [comment]
Thanks for your suggestion. That would be good if we have these examples in `Example 24.2` of https://docs.gradle.org/current/userguide/logging.html 

Would you like to provide a PR? It would be simple, just add a few lines after https://github.com/gradle/gradle/blob/838310ce1a3e6bd4799884b3f0938e1f1ea49472/subprojects/docs/src/samples/userguide/tutorial/logging/build.gradle#L8

**Comment by bmuschko** [comment]
I opened a pull request for this: https://github.com/gradle/gradle/pull/3915
