### ISSUE TITLE
NPE when dependency artifact name is not specified

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#3742]
When an artifact is attached to a dependency declaration and no value is provided for the artifact `name` property, the build fails with a NPE.

For example:

```
apply plugin: 'java'

dependencies {
    compile('my.lib:1.2') {
        artifact {
            classifier = 'test'
        }
    }
}
```

### Expected Behavior

Either provide a default value for the `name` property or deal with a `null` value or fail with a better error message when the value is `null`.

### Current Behavior

Using a `null` value for an artifact `name` (however this happens) results in a NPE when the artifact is added to the dependency declaration.

**Comment by oehme** [comment]
@jjohannes may I assign this to you?

**Comment by jjohannes** [comment]
@oehme sure. I will check this.
