### ISSUE TITLE
Bypassing Zinc for non-incremental Scala compilation

### ISSUE THREAD

**Issue by dsilvasc** [gradle/gradle#3748]
Zinc is helpful in speeding up incremental builds of Scala code, but it comes with a startup cost ( https://github.com/gradle/gradle/issues/3725 ) and a complexity/maintenance cost ( https://github.com/gradle/gradle/issues/2605 ).

When you run Gradle mostly during full builds in Jenkins or CircleCI, and when you let your IDE handle incremental builds, you don't really reap any benefits from Zinc-based Scala builds in Gradle.

### Expected Behavior

For use cases that only need full (non-incremental) builds, it would be nice to bypass zinc and run `scalac` directly -- similarly to how gradle runs `javac`.

Is this doable through configuration in the gradle scala plugin today?  If not, what would it take to make that possible?

### Current Behavior

All scala builds seem to go through zinc before `scalac`.

### Context

Longer build times and concurrency bugs when using zinc.

### Your Environment

 * Build scan URL:

**Comment by dsilvasc** [comment]
How about something like this?  A gradle buildscript to override compileScala and compileTestScala tasks with replacements that call the Scala compiler directly (without zinc and without a new jvm process).

It doesn't handle compiler flags, other xxScala tasks, and probably a lot of other functionality from the tasks provided by the scala plugin.

```gradle
apply plugin: 'scala'

dependencies {
  compile "org.scala-lang:scala-library:2.11.12"
}

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "org.scala-lang:scala-library:2.11.12"
    classpath "org.scala-lang:scala-compiler:2.11.12"
    classpath "org.scala-lang:scala-reflect:2.11.12"
  }
}

import scala.tools.nsc.*
import scala.collection.JavaConversions

def doCompile(sourceSet, depSourceSets, configuration) {
  Settings settings = new Settings()

  // https://stackoverflow.com/questions/27934282/object-scala-in-compiler-mirror-not-found-running-scala-compiler-programatical
  // http://www.scala-lang.org/old/node/7949
  // https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  def deps = depSourceSets.collect { it.outputDir.toString() }.join(':')
  settings.classpath().value_$eq(configuration.asPath + ":$deps")

  sourceSet.scala.outputDir.mkdirs()
  settings.d().value_$eq(sourceSet.scala.outputDir.toString())

  for (srcDir in sourceSet.scala.srcDirs) {
    settings.sourcepath().append(srcDir.toString())
  }

  Global global = new Global(settings)

  // https://stackoverflow.com/questions/27980332/how-do-i-construct-a-non-static-java-inner-class-from-groovy
  Global.Run run = new Global.Run(global)

  def fileNames = sourceSet.allScala.collect { it.toString() }
  run.compile(JavaConversions.asScalaBuffer(fileNames).toList())

  if (global.reporter().hasErrors()) {
    throw new GradleException("Failed to compile.")
  }
}

task compileScalaDirect {
  dependsOn compileJava
  inputs.files(compileScala.inputs.files)
  outputs.dir(project.sourceSets.main.scala.outputDir)
  doFirst {
    doCompile(project.sourceSets.main, [project.sourceSets.main.java], configurations.compile)
  }
}

task compileTestScalaDirect {
  dependsOn compileJava
  dependsOn compileScala
  dependsOn compileTestJava
  inputs.files(compileTestScala.inputs.files)
  outputs.dir(project.sourceSets.test.scala.outputDir)
  doFirst {
    doCompile(
      project.sourceSets.test,
      [project.sourceSets.main.java, project.sourceSets.main.scala, project.sourceSets.test.java],
      configurations.testCompile)
  }
}

compileScala {
  dependsOn compileScalaDirect
  onlyIf { false }
}

compileTestScala {
  dependsOn compileTestScalaDirect
  onlyIf { false }
}
```

**Comment by ghale** [comment]
I think in general, we would prefer improving our integration with Zinc (see #2158) over adding support for another compiler.  I'm closing this for now.
