### ISSUE TITLE
Gradle testkit documentation: BuildLogicFunctionalTest junit assertion uses actual result as expected and vica versa

### ISSUE THREAD

**Issue by futu** [gradle/gradle#3764]
https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/docs/src/samples/testKit/gradleRunner/junitQuickstart/src/test/java/org/gradle/sample/BuildLogicFunctionalTest.java#L62

Gradle *-all distribution contains sample: 
gradle-4.4/samples/testKit/gradleRunner/junitQuickstart/src/test/java/org/gradle/sample/BuildLogicFunctionalTest.java

BuildLogicFunctionalTest junit assertion uses constant (SUCCESS) as actual result and tasks output as expected (result.task(":helloWorld").getOutcome()).

junit Assert has static method with folowing signature:
` assertEquals(Object expected, Object actual)`

assertion in code:
`assertEquals(result.task(":helloWorld").getOutcome(), SUCCESS);`

### Expected Behavior

expected result is SUCCESS
actual result is result.task(":helloWorld").getOutcome(), SUCCESS

### Current Behavior

actual result is SUCCESS
expected result is result.task(":helloWorld").getOutcome(), SUCCESS

### Context

It doesn't break anything, but provides sample with incorrect assertion logic
### Your Environment

 * Build scan URL:

**Comment by blindpirate** [comment]
Thanks for your careful reading. Would you like to provide us a pull request? It would be simple. No pressure on you.

**Comment by futu** [comment]
Sure, should I create design doc at first?

**Comment by blindpirate** [comment]
Just like the normal GitHub contribution process. Fork `gradle`, clone to your local, change the line you just discovered, and create a pull request. 

If you're not familiar, I'd like you to see https://github.com/processing/processing/wiki/Contributing-to-Processing-with-Pull-Requests first.

**Comment by eriwen** [comment]
@futu contributing this is now very easy, I hope you'll give this a shot.

1) Go to the [TestKit docs page](https://docs.gradle.org/current/userguide/test_kit.html)
2) Click "Edit this page"
3) Make changes on GitHub
4) [Sign off your commit](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md#signing-off-commits-after-submitting-a-pull-request) so we can accept your PR.

**Comment by blindpirate** [comment]
Aha, good to know this magic!

**Comment by bmuschko** [comment]
@futu Can you explain what the problem is with the code we have? We are comparing two objects, (in this case of type `TaskOutcome`) via `org.junit.Assert.assertEquals`. It is not clear from your description what else you'd expect here or why you consider this "incorrect assertion logic".

**Comment by eriwen** [comment]
@bmuschko I think what @futu reported is that we just switched the expected and actual values in the test assertions. Tests are valid, just would report failures a little oddly.

**Comment by bmuschko** [comment]
@eriwen I see. Thanks for clarifying.

**Comment by futu** [comment]
@eriwen It seems to me that I can't edit sample java files via "Edit this page". There is no code in editor, just link to file that I need to change.

**Comment by eriwen** [comment]
@futu I'm sorry, you're right. Editing samples is a bit tougher, but luckily not too much :) 

The path noted in the docs goes to [this sample](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/samples/testKit/gradleRunner/testKitFunctionalTestSpockBuildCache/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy). You can also edit that on GitHub or in your editor of choice to submit a PR. 

Not quite as easy as I claimed, but would still appreciate if you gave that a go. Thanks!

**Comment by bmuschko** [comment]
I just went ahead and fixed the issue: https://github.com/gradle/gradle/commit/1ba314ed1e454765f1b4d8655bf8047bc1ec752f.
