### ISSUE TITLE
Deprecate dependency management features for removal

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3771]
There are many legacy features supported in dependency management that add little or no value, but we retain for backward compatibility purposes. Some of these we've already decided to change in Gradle 5.0, and some would permit simplification and refactoring if we removed them.

We need a deprecation cycle to remove / change things, and we should consider those for the next release, or it could be too late to change for 5.0.

Candidates:
- Any behaviours that will are enabled by `experimentalFeatures.enable()` and will change by default in Gradle 5.0
    - Maven `optional` dependencies
    - `<dependencyManagement>` in Maven BOM as dependency
    - Searching for module artifact if metadata is not found
- Magic "optional" configuration that includes all Maven 'optional' dependencies
- Shorthand notation for declaring dependency artifacts: `org.foo:bar:1.0:<classifier>@<extension>`
- Searching for a `jar` file for a POM file with `packaging = 'pom'`: https://github.com/gradle/gradle/blob/5f12fa6c215dc5970e86a92cd42cc6b0fc66e785/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java#L240-L242
- Different behaviour for different POM `packaging` values, depending on whether we are looking [in the cache](https://github.com/gradle/gradle/blob/5f12fa6c215dc5970e86a92cd42cc6b0fc66e785/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java#L218-L220), or [in a remote repository](https://github.com/gradle/gradle/blob/5f12fa6c215dc5970e86a92cd42cc6b0fc66e785/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java#L243-L250) (this looks like it could be a bug)
- Performing a directory listing for a Maven repository when no `maven-metadata.xml` is found
- Resolving non-unique Maven SNAPSHOTs : need to confirm if Maven3+ is able to resolve these legacy publications
- Dependency resolution at configuration-time
- HTML `dependencies` report: build scans already provide a much better report, and we don't want to maintain a separate rich HTML report

**Comment by 3ll3d00d** [comment]
> Shorthand notation for declaring dependency artifacts: org.foo:bar:1.0:<classifier>@<extension>
is there a document that describes what replaces this and/or what the related features are in 5.0 that lead to such features being removed?

**Comment by bigdaz** [comment]
The motivation for removing the shorthand notation is that it's the cause of confusion. It's not clear from the syntax that this is a way to target a particular artifact from the specified module, and to ignore the module metadata.

We think that the equivalent full syntax provides a clearer indication of this:
```
dependencies {
    compile('org.foo:bar:1.0') {
        artifact {
            classifier 'classy'
            extension 'jar'
        }
    }
}
```

The HTML dependency report hasn't been kept up-to-date with recent developments in dependency management, and we are reluctant to invest too much into it where that effort will duplicate the much better job that will be done by free, public build scans. We understand there are cases where an organization cannot use public build scans, and no decision has been made at this time to remove the HTML dependency report. 

The motivation for this GH issue is to find things that can reduce our maintenance burden at little cost to users. Deprecation is one way to find out how widely used certain features are, and we can use any feedback in order to make an educated decision.

**Comment by adammurdoch** [comment]
> Dependency resolution at configuration-time

I'm not sure about this one, I think there are legit use cases for querying things in order to configure other things. We can certainly address the issues that are symptoms of resolution at configuration time though (performance and confusing ordering related failures), possibly by helping people make these things lazy and maybe other kinds of validation.

**Comment by adammurdoch** [comment]
Some more candidates (if they're not already on the list):

- `group`, `name` and `version` on `Dependency`. These properties don't make sense for all dependency declarations. Might instead expose the component selector or push these properties further down or both.
- `force` on `ExternalDependency`. Should use strictness, or resolution strategy instead.
- `changing` on `ExternalModuleDependency`. This belongs on the component's metadata, can use a metadata rule instead.
- `SelfResolvingDependency`, or at least `ProjectDependency extends SelfResolvingDependency`. It doesn't really make sense to query the files that match a project dependency, except in the context of a graph resolution. Use `ArtifactCollection` and other result APIs.
- Client modules. Should use component metadata rules instead.

**Comment by bigdaz** [comment]
We are too late for to deprecate any of these for removal in 5.0. Let's look into deprecating stuff early in 5.x for removal in 6.0.
