### ISSUE TITLE
Wrong test execution time for parallel test execution

### ISSUE THREAD

**Issue by rosolko** [gradle/gradle#3774]
### Expected Behavior

I wood like to see real tests execution time.

### Current Behavior

Gradle test report show me just sum of all test execution times.

### Steps to Reproduce (for bugs)

For example I create two class with two test for each class in one `sample` package.
Each test contains `5` second sleep, so in test execution each class takes me `10` second for execute.
First:
```
public class TestClassOne {
    @Test
    public void testOne() throws InterruptedException {
        Thread.sleep(5000);
    }

    @Test
    public void testTwo() throws InterruptedException {
        Thread.sleep(5000);
    }
}
```
Second:
```
public class TestClassTwo {
    @Test
    public void testOne() throws InterruptedException {
        Thread.sleep(5000);
    }

    @Test
    public void testTwo() throws InterruptedException {
        Thread.sleep(5000);
    }
}
```
I set `maxParallelForks` property in `test` task equals to `2`:
```
test {
    maxParallelForks = 2
}
```
After all setup I run `test` task in console.
`./gradlew clean test --tests \*sample\* `
And test executed in parallel.
At the end I open report and it says me that I spend `20` second to test but actually only `10`.

<img width="970" alt="image 2017-12-11 at 15 52 16" src="https://user-images.githubusercontent.com/11458319/33832043-7ca77ee6-de8b-11e7-8df2-5886a33437cc.png">

### Your Environment

```
------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Mac OS X 10.13.2 x86_64
```

**Comment by eriwen** [comment]
@rosolko To be very clear, the "duration" at the top of the report "20s" is wrong. The duration for each test class "10s" is correct. Do you agree?

**Comment by rosolko** [comment]
@eriwen Yes, correct. Just overall duration time is wrong.

**Comment by ubergrohman** [comment]
Same issue for gradle 7.2 and parallel test execution with junit5.

**Comment by ov7a** [comment]
This is still reproducible with 9.5.1
