### ISSUE TITLE
gradle-api-x.y.jar contains too many properties which may break tests

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#3780]
### Expected Behavior

Generated gradle-api-x.y.jar should be at the end of test classpath when forking test worker process.

### Current Behavior

Now it's at the beginning of the test classpath, which might cause weird test failures.

### Context

Recently I found a build of mine is broken after upgrading to `4.4`. The failure looks unrelated to the upgrade, but it does exist. I extract a minimum sample here: https://github.com/blindpirate/gradle44-breaking-change

In short, some 3rd dependencies might be leaked into test classpath. If I run test with dependency `gradleApi()`, the [simple test](https://github.com/blindpirate/gradle44-breaking-change/blob/master/src/test/groovy/GitCloneTest.groovy) would succeed with `4.3.1`, but fail with `4.4`. However, running in IDEA always succeed and `gradle dependencies` with `4.3.1` and `4.4` are identical:

```
# zhb @ bs-MacBook-Pro in ~/Projects/tmp/gradle44-breaking-change on git:master o [9:03:44] 
$ gradle431 test

BUILD SUCCESSFUL in 3s
2 actionable tasks: 2 executed

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/gradle44-breaking-change on git:master o [9:11:44] 
$ gradle44 test

> Task :test FAILED

GitCloneTest > gitCloneTest FAILED
    org.apache.commons.exec.ExecuteException at GitCloneTest.groovy:65

1 test completed, 1 failed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/zhb/Projects/tmp/gradle44-breaking-change/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
2 actionable tasks: 2 executed

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/gradle44-breaking-change on git:master o [9:11:53] C:1
$ gradle431 dependencies > 431 && md5 431
MD5 (431) = 6f72e1993a16a4cd69aec326835561fd

# zhb @ bs-MacBook-Pro in ~/Projects/tmp/gradle44-breaking-change on git:master x [9:12:14] 
$ gradle44 dependencies > 44 && md5 44
MD5 (44) = 6f72e1993a16a4cd69aec326835561fd

```

After some investigation, finally I found the reason is the huge `gradle-api-x.y.jar` which is generated by Gradle when it encounters `gradleApi` dependency declaration.

Previously, `gradle-api-4.3.1.jar` didn't contain any JGit dependencies so it works fine. In `4.4`, JGit was introduced into `version-control` subproject, so its resources are shaded into `gradle-api-4.4.jar`. In this case, `org/eclipse/jgit/internal/JGitText.properties` from [org.eclipse.jgit:org.eclipse.jgit:4.5.3.201708160445-r](https://github.com/gradle/gradle/blob/c6902f790ca6ac7fbfeb08074bdc2500cd4cdc75/gradle/dependencies.gradle#L82) are loaded from `gradle-api-4.4.jar` instead of the correct JGit jar. We can see the debug log at [this line](https://github.com/gradle/gradle/blob/5742f4ec60540d36e3197315d2fa02c8fbf3a686/subprojects/core/src/main/java/org/gradle/process/internal/worker/DefaultWorkerProcessBuilder.java#L188), the test classpath order is:

```
Using application classpath [..., /Users/zhb/.gradle/caches/4.4/generated-gradle-jars/gradle-api-4.4.jar, ... , /Users/zhb/.gradle/caches/modules-2/files-2.1/org.eclipse.jgit/org.eclipse.jgit.http.server/4.9.1.201712030800-r/6ecb5bd14f45fe07995074613c9255a3447623b2/org.eclipse.jgit.http.server-4.9.1.201712030800-r.jar ]
```
Looks like there're no work arounds. 

### Steps to Reproduce (for bugs)

https://github.com/blindpirate/gradle44-breaking-change

**Comment by blindpirate** [comment]
It turns out to be [org.eclipse.jgit:org.eclipse.jgit:4.5.3.201708160445-r](https://github.com/gradle/gradle/blob/c6902f790ca6ac7fbfeb08074bdc2500cd4cdc75/gradle/dependencies.gradle#L82) leaked into test class path. JGit runtime needs to load `JGitText.properties`, but what it reads is Gradle's JGit dependency, not the correct JGit in test classpath.

**Comment by oehme** [comment]
For 4.4.1 we should exclude the JGit .properties files from the API jar. They are always looked up using the qualified name, so we don't need to keep the copy with the original name. Long term we need to come up with a better solution for our API jar, since these leakages keep biting us.

@big-guy Since the native team introduced this dependency, would you mind taking over this issue?

**Comment by big-guy** [comment]
This has been fixed in release
