### ISSUE TITLE
Plugin artifacts are re-downloaded from plugin portal when Gradle is upgraded

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3799]
Gradle tries to avoid re-downloading artifacts when it is upgraded, even if the format of the artifact cache has changed. It does this by comparing checksums of previously downloaded artifacts against the checksums declared by the repository server.

This is not working for artifacts downloaded from the plugin portal, due to the fact that the portal does not expose the necessary checksums.

### Expected Behavior

When I update to Gradle 4.x and run a build, no previously downloaded artifacts should be downloaded.

### Current Behavior

When I update to Gradle 4.5 nightly, POM files and Jar files for plugins and dependencies are re-downloaded.

### Context

This behaviour gives a poor impression of Gradle, leading users to think that everything will be re-downloaded for every Gradle version update. This may also make users more reluctant to try out new Gradle versions.

### Steps to Reproduce (for bugs)

- Define a build that uses a plugin from the plugin portal
- Run that build with Gradle 4.4
- Run that build again with a Gradle 4.5 nightly

**Comment by eskatos** [comment]
This happens since #3347.

The proprietary plugin portal client did cache plugin resolution metadata on its own. Since #3347, the regular dependency resolution engine is used to lookup plugin metadata from the plugin portal, considering it as a regular maven repository.

This combined makes surface the fact that the plugin portal doesn't serve artifacts checksums nor proper http caching headers, preventing dependency resolution to short circuit and reuse previously downloaded artifacts.

**Comment by acourtneybrown** [comment]
https://github.com/gradle/gradlecom/pull/462 contains changes to the plugin portal to generate & serve hash checksum files (`.md5` & `.sha1`) for artifacts that are _known_ to the plugin portal, but not artifacts that are being proxied from Bintray.

**Comment by acourtneybrown** [comment]
@oehme gradle/gradlecom#462 (plus another minor fix from running in dev) got deployed to plugins.gradle.org on 16 Mar @ 2:45p MST.  @eriwen & I did some manual validation that the checksum files were allowing Gradle to avoid downloading plugins between versions.  Using this simple `build.gradle`:

```
plugins {
  id 'com.eriwen.gradle.css' version '2.14.0'
}
```

Here are the build scans for running Gradle 4.5, 4.5.1 & 4.6:

4.5:  https://e.grdev.net/s/ihu76et3f76rs/performance/networkActivity
4.5.1: https://e.grdev.net/s/piguxwjaq2zz2/performance/networkActivity
4.6:  https://e.grdev.net/s/f3wrkb56k5eus/performance/networkActivity

The 4.5 build was the first & the plugin needed to be downloaded.  With both the 4.5.1 & 4.6, the updated plugin portal served up the `.sha1` checksum file & Gradle didn't need to download the (unchanged) plugin jar.

We'll continue to monitor the plugin portal for some time this afternoon (MST) to make sure there aren't any unforeseen performance & error problems.

**Comment by oehme** [comment]
Awesome, thanks Adam!
