### ISSUE TITLE
Downgrade dependency with constraint + component-metadata-rule is cumbersome

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3803]
One of the motivations to dependency constraints is to make it easy for a local component to control the transitive versions of dependencies (and to have these constraints available to consumers of that component). At times, a strict constraint may result in a build failure due to the need to downgrade some of the transitive dependency versions.

Using the `nebula.dependency-recommender` plugin this is trivial. This can also be achieved using a constraint + a component metadata rule, but the end result is a bit ugly: https://github.com/bigdaz/example-project/blob/dependency-downgrade/override_project_example/build.gradle

Note that the alternative syntax using dependency resolve rules is much simpler.  I would suggest a syntax like:
```
dependencies.components {
     withModule('overridestrategy:a') {
          withDependency('overridestrategy:transitivedeb') {
               version { prefer '1.0.0' }
          }
    }
}
```

In addition to cumbersome syntax, the reporting is not as good when a component-metadata-rule is used for constraint compliance.
With component-metadata-rule:
```
> Task :dependencyInsight 
overridestrategy:transitivedeb:1.0.0
\--- compile

overridestrategy:transitivedeb:1.0.0
\--- overridestrategy:a:1.0.0
     \--- compile
```

With dependency-resolve-rule:
```
> Task :dependencyInsight 
overridestrategy:transitivedeb:1.0.0 (selected by rule)
\--- compile

overridestrategy:transitivedeb:1.0.1 -> 1.0.0
\--- overridestrategy:a:1.0.0
     \--- compile
```

**Comment by ljacomet** [comment]
This is now resolved in Gradle 6.0 with the `strictly` semantics - see #10512
