### ISSUE TITLE
FAILURE: Build failed with an exception. Could not compile build file 'C:\myapp\platforms\android\build.gradle'.

### ISSUE THREAD

**Issue by oTTa** [gradle/gradle#3806]
when i run "**ionic cordova build android --release --stacktrace --info android**"

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\myapp\platforms\android\build.gradle' line: 328

* What went wrong:
Could not compile build file 'C:\myapp\platforms\android\build.gradle'.
> startup failed:
  build file 'C:\myapp\platforms\android\build.gradle': 328: unexpected token: } @ line 328, column 1.
     }
     ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\myapp\platforms\android\build.gradle' line: 328

* What went wrong:
Could not compile build file 'C:\myapp\platforms\android\build.gradle'.
> startup failed:
  build file 'C:\myapp\platforms\android\build.gradle': 328: unexpected token: } @ line 328, column 1.
     }
     ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova build android --release (exit code 1).

**Comment by oehme** [comment]
Looks like your build script has a syntax error. If you think your build script is correct and you still get an error, please provide an example project.

**Comment by admirableghost** [comment]
I am facing the same issue. Were you able to solve it ? @oTTa .
It is an auto generated file while building for android using ionic cordova

ionic info
`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.10.0
    npm  : 2.15.12 
    OS   : macOS High Sierra

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
`

**Comment by oTTa** [comment]
@admirableghost 
first you need to set ANDROID_HOME and later you set distributionUrl for grandle like this

var distributionUrl = process.env['CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL'] || 'https\\://services.gradle.org/distributions/gradle-4.1-all.zip';
