### ISSUE TITLE
Support custom attributes in publications

### ISSUE THREAD

**Issue by melix** [gradle/gradle#3809]
In https://github.com/gradle/gradle/issues/3159 we added support for adding or updating attributes found in a module. However, there's no possibility to actually publish a module with custom attributes.

## Context

It possible to mutate component level attributes, as well as variant level attributes. However, there's a missing piece in the puzzle: while I have tests proving that we serialize attributes properly, and consume them properly, there's actually no way to declare attributes on published components or variant.

So it means it is possible to replace, say, attribute `quality` from `canary` to `qa` if it's found in module metadata. But there's no way to actually create a metadata file that has such a custom attribute.

**Comment by octylFractal** [comment]
This appears to no longer apply, because you can just add attributes to apiElements/runtimeElements.
