### ISSUE TITLE
Provider and Property APIs implicit task dependency inference does not work when creating instance with injected ProjectLayout

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#3811]
Task inference should work with any provider that is linked from a task (from https://docs.gradle.org/nightly/userguide/lazy_configuration.html#sec:lazy_configuration_roadmap)

I can't share the full code right now, but I can provide a contrived example below. If a "more real" example is needed, I can do that as well.

### Expected Behavior

The APIs should be symmetric. It is expected that wiring a `Provider<>` from one task into the next produces an implicit task dependency. Any task or plugin that wires `Provider<>` and `Property<>` types (not just filesystem output types) to other tasks should also get implicit task `dependsOn`.

### Current Behavior

Tasks do not have implicit dependency depending on how the object was created. `dependsOn` is explicitly required.

### Context

In my case, I am writing a plugin that is:

* Creating an extension object with `DirectoryProperty` and `RegularFileProperty` fields tmhat are created from `project.layout.buildDirectory.dir` and `project.layout.directoryProperty`
* Tasks are creating with `@Inject` with constructor arguments `ObjectFactory`, `ProviderFactory`, and `ProjectLayout`. The properties (like `Property<String>` and `DirectoryProperty`) are created from these injected types
* The task `Property<>` types are wired into inputs of tasks by way of `myTask.inputDir.set(extension.destinationDir)`

### Steps to Reproduce (for bugs)

This is a basic example without a plugin setting up the inputs and outputs. I can provide a more full one if needed.

* `build.gradle`

    ```groovy
    import javax.inject.Inject
    wrapper.gradleVersion = '4.4'
    
    // https://docs.gradle.org/nightly/userguide/lazy_configuration.html#sec:lazy_configuration_roadmap example
    class ProducerNewOutputFile extends DefaultTask {
      @OutputFile
      final RegularFileProperty outputFile = newOutputFile()
    
      @TaskAction
      void produce() {
        String message = 'Hello, World!'
        def output = outputFile.get().asFile
        output.text = message
        logger.lifecycle("Wrote '${message}' to ${output}")
      }
    }
    
    class ConsumerNewInputFile extends DefaultTask {
    
      @InputFile
      final RegularFileProperty inputFile = newInputFile()
    
      @TaskAction
      void consume() {
        def input = inputFile.get().asFile
        def message = input.text
        logger.lifecycle("Read '${message}' from ${input}")
      }
    }
    
    task producerNOF(type: ProducerNewOutputFile)
    task consumerNOF(type: ConsumerNewInputFile)
    
    consumerNOF.inputFile = producerNOF.outputFile
    producerNOF.outputFile = layout.buildDirectory.file('producerNOF.txt')
    
    // Injection example
    class ProducerInjectLayout extends DefaultTask {
    
      @Inject
      ProducerInjectLayout(ProjectLayout layout) {
        outputFile = layout.fileProperty()
      }
    
      @OutputFile
      final RegularFileProperty outputFile
    
      @TaskAction
      void produce() {
        String message = 'Hello, World!'
        def output = outputFile.get().asFile
        output.text = message
        logger.lifecycle("Wrote '${message}' to ${output}")
      }
    }
    
    class ConsumerInjectLayout extends DefaultTask {
    
      @Inject
      ConsumerInjectLayout(ProjectLayout layout) {
        inputFile = layout.fileProperty()
      }
    
      @InputFile
      final RegularFileProperty inputFile
    
      @TaskAction
      void consume() {
        def input = inputFile.get().asFile
        def message = input.text
        logger.lifecycle("Read '${message}' from ${input}")
      }
    }
    
    task producerInject(type: ProducerInjectLayout)
    task consumerInject(type: ConsumerInjectLayout)
    
    consumerInject.inputFile = producerInject.outputFile
    producerInject.outputFile = layout.buildDirectory.file('producerInject.txt')
    ```

* Run `./gradlew consumerNOF` - see success and task ordering as described in linked documentation
* Run `./gradlew consumerInject` - `specified for property 'inputFile' does not exist` and no task dependency inference

### Your Environment

* Gradle 4.4

**Comment by wolfs** [comment]
I guess this is the same behavior as I show in the integration tests in a PR I just opened: https://github.com/gradle/gradle/pull/3813, right?

**Comment by mkobit** [comment]
Another use case I have for this is to expose `Provider<>` on an extension that a user can arbitrarily use, and then the tasks that build that `Provider<>` are automatically executed without them having to know what type and what name the underlying tasks are.

**Comment by mkobit** [comment]
Would really like to see all of the `Provider` types have complete support and implicit task dependency calculations wherever they are used from.

Is this something scheduled or something that needs to be picked up by the community?

**Comment by mkobit** [comment]
I don't know if `Provider` are supposed to be allowed as task dependencies, as well but adding `consumerInject.dependsOn(producerInject.outputFile)` does not get the task dependencies correct, either.

**Comment by big-guy** [comment]
To get the task dependency, the output property needs to be connected to the task somehow.

So in your `@Inject` example:
```
outputFile = layout.fileProperty()
```
This creates a `RegularFileProperty` that has no task information built in. So later on, when you do:
```
consumerInject.inputFile = producerInject.outputFile
```
This doesn't connect the consumer to the producer because outputFile carries no dependency information.

We could do better at calling out this particular behavior in the user guide chapter:
https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:working_with_task_dependencies_in_lazy_properties

We do say that you need to use `newOutputFile`, but we don't warn you about if you don't explicitly. 

Here's your example adapted a bit to use an extension to connect the producer and consumer.
```
import javax.inject.Inject

class ProducerConsumerExtension {
    final RegularFileProperty connector

    ProducerConsumerExtension(ProjectLayout layout) {
        connector = layout.fileProperty()
    }
}
// https://docs.gradle.org/nightly/userguide/lazy_configuration.html#sec:lazy_configuration_roadmap example
class ProducerNewOutputFile extends DefaultTask {
  @OutputFile
  final RegularFileProperty outputFile = newOutputFile()

  @TaskAction
  void produce() {
    String message = 'Hello, World!'
    def output = outputFile.get().asFile
    output.text = message
    logger.lifecycle("Wrote '${message}' to ${output}")
  }
}

class ConsumerNewInputFile extends DefaultTask {

  @InputFile
  final RegularFileProperty inputFile = newInputFile()

  @TaskAction
  void consume() {
    def input = inputFile.get().asFile
    def message = input.text
    logger.lifecycle("Read '${message}' from ${input}")
  }
}

def extension = extensions.create("myExt", ProducerConsumerExtension, layout)

task producerNOF(type: ProducerNewOutputFile) {
    outputFile = layout.buildDirectory.file('producerNOF.txt')
}

task consumerNOF(type: ConsumerNewInputFile) {
    inputFile = extension.connector
}

extension.connector = producerNOF.outputFile
```

**Comment by mkobit** [comment]
Thanks @big-guy , your explanation of how things currently work makes sense. 

Although, IMO having multiple ways to do this where the behavior differs is confusing as a plugin and build script writer. Even though all task implementation in Gradle basically inherit from `DefaultTask`, I still try to avoid inheritance where I can and make use of dependency injection where possible.

Would an improvement here be for the "injector" to inject a task-aware `ProjectLayout`/`ObjectFactory`/ other objects so that "things" created from that object are task-aware? Or possibly, allow `@Inject` to create the `DirectoryProperty`, `RegularFileProperty`, and `Provider`/`Property` types? To me, it seems like Gradle is in control of instantiating these objects so it should be able to wire up the dependencies together. WDYT?

**Comment by wolfs** [comment]
@mkobit #4665 fixes your problems when using `layout.{file,directory}Property()` for inputs - so there is no need to use `newInput{File,Directory}()` any more as long as the property has the correct annotations.

It does not yet fix that, when a property is annotated with `@Output*`, the task dependency is added - so `newOutput{File,Directory}()` is still required.

Is that already sufficient for you?

**Comment by mkobit** [comment]
@wolfs I think that is a huge improvement, but if `Provider<>` and `Property<>` types are expected to be the "correct" types used for representing inputs and outputs going forward then I think the leftover `newOutput*` behavior will be confusing. From my perspective, the `Provider` and `Property` types are something I've been wanting to see in Gradle for a long time - functional inputs and outputs, implicit task dependencies, lazy values, (possibly non-file system outputs eventually) - and I'd really love for them to be fully supported and modeled throughout the whole Gradle platform while keeping them simple and obvious. Right now, they still have a few limitations. For example, if I want to just make a `Provider<RegularFileDirectory>` an `artifact {}` from the build, it has to carry task information/buildable information with it, even if I just want to include a directory from a subproject without reaching directly into it.

I think that object creation and dependency injection is still lacking alignment across Gradle's APIs. It would be nice to not see the same issue impact the `Property` and `Provider` APIs if they don't have to. A few examples being `WorkerExecutor` JSR-330 style injection, `ExtensionContainer.create` with providing constructor arguments, creating a `new` instrane and `ExtensionContainer.add`, [`@Inject` on getters](https://github.com/gradle/gradle/blob/fae15bc929dc60d57c168a1904c9088f66b4549d/subprojects/core/src/main/java/org/gradle/api/tasks/AbstractExecTask.java#L49-L52), the new [`ObjectFactory` APIs](https://docs.gradle.org/current/javadoc/org/gradle/api/model/ObjectFactory.html), inheritance creation now with `new{Input,Output}{File,Directory}()`, and certainly others. Having multiple ways of creating `Property` types and having dependency inference "work one way, but not the other" when the same types are used, I think, will be confusing to both plugin and build script authors. 

Now there is:

* [`Project.getLayout().{file,directory}Property()`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#getLayout--)
* Inject the `ProjectLayout` and create `{RegularFile,Directory}Property` - a little bit strange to model files or directories outside of the project or build directory, but still works fine. Injection is also mostly straightforward.
* `DefaultTask.new{Input,Output}{File,Directory}()` - non-final protected methods
* `Project.getProviders().provider(Callable<? extends T> value)`
* `Project.provider(Callable<T> value)` - duplicate of other method I'm guessing for more concise build scripts

I don't know if others are running into similar issues yet as these APIs are still new. I just wanted to get some of my thoughts down on here while these APIs are still fresh and beginning to be dogfooded (is that a word?) inside of the Gradle project itself. Being able to refer to Gradle's source code as the canonical source for _"what are the best practices for implementing custom tasks?"_ will be useful while you guys work out the kinks and maybe run into the same issues that consumers are running into. I would hate to see the lazy configuration APIs run into an early death like the software model, but also avoid the complexities and confusion of all of the `Convention`-style APIs.

**Comment by lacasseio** [comment]
Thanks @mkobit for these suggestions and thoughts on the Provider API. We are also experiencing some of the pain you are describing here internally and we will be working on fixing those soon. Some of the duplicated API you mentioned were created as gab bridging. Although the Provider API is incubating, some partners are already using it and as it evolved we want to avoid breaking developers for no reason. We will clean those, we just don't have a concrete stories moving forward with the clean up.

We appreciate the effort you are making in using those APIs and those exact comments help us prioritize the next work around those APIs.

We will soon start dogfooding the API more widely in Gradle as well as establish a migration path.

**Comment by mkobit** [comment]
Thanks @big-guy , @wolfs , and @lacasseio for the taking the time to respond on this. Looking forward to seeing these APIs evolve.

**Comment by adammurdoch** [comment]
Thanks for the feedback, there are some very good points you raise. We plan to simplify the APIs so that there's a consistent pattern for creating property instances, regardless of whether implementing a task or some other model object such as a plugin extension. And so that whatever that ends up being, it maintains the task dependency information when it should (and fail when it shouldn't rather than silently ignoring this).

I'm leaning towards using the dependency injection approach, as this will be easier to use in situations other than implementing a task.

**Comment by adammurdoch** [comment]
The task dependency inference issue is now fixed, via https://github.com/gradle/gradle/pull/6603. Property instances created using the factory methods on `DefaultTask` and using the factory method on `ProjectLayout` now work consistently.

There are still some edge cases to fix and some API simplification yet to do, but I'm going to close this issue as the basic problem is now fixed. Please raise new issues for any further changes you think we should make or issues you run into.
