### ISSUE TITLE
Project will not compile without transitive dependency exclusion when I believe it should.

### ISSUE THREAD

**Issue by andrewparmet** [gradle/gradle#3817]
I have a project in which I have a dependency on a recent version of Guava, but the presence of other dependencies that have a dependency on an older version of Guava seem to override my version with theirs.

### Expected Behavior

The project should compile - `./gradlew compileJava` should succeed.

### Current Behavior

Without an explicit transitive dependency exclusion the task fails. The task succeeds when I add `exclude group: 'com.google.guava'` for the module with an older dependency. Here's the failure output: 
```
$ ./gradlew compileJava

> Task :compileJava FAILED
<...>/test-gradle-transitive-dependencies/src/main/java/Main.java:6: error: cannot find symbol
        Throwables.throwIfInstanceOf(new Exception(), RuntimeException.class);
                  ^
  symbol:   method throwIfInstanceOf(Exception,Class<RuntimeException>)
  location: class Throwables
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

### Context

I'm trying to use a new version of Guava in a project that has dependencies that require other versions of Guava.

### Steps to Reproduce (for bugs)

I have a minimal working example of a single Java file and build.gradle:
```java
import com.google.common.base.Throwables;

public class Main {
    public static void main(String... args) {
        Throwables.throwIfInstanceOf(new Exception(), RuntimeException.class);
    }
}
```

```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.google.guava:guava:23.5-jre'
    compileOnly('com.google.errorprone:error_prone_core:2.0.5') {
        exclude group: 'com.google.guava'
    }
}
```

The project can be found here: https://github.com/andrewparmet/test-gradle-transitive-dependencies

If I comment out the `exclude group` line compilation fails. I also tried to use a resolution strategy to force versions of the Guava module to version 23.5-jre but this also failed. I include the `build.gradle` file I used with this attempt as `build.gradle.alt`. It seems to be related to the error-prone module, as other modules do not cause this problem. I appreciate any insight into why this is going wrong.

### Your Environment

 * Build scan URL: 
https://gradle.com/s/3mnzxioz4ffcg

This problem did not occur on Gradle 3.5 or 3.5.1, and first occurs in version 4.0.

**Comment by big-guy** [comment]
The problem is in the version of error-prone you're using.  Before 2.0.16, the error-prone-core jar also contained a copy of Guava.  See related https://github.com/google/error-prone/issues/501

The reason exclude seemed to fix the problem is that it changed the ordering of the classpath.  The exclusion would put the newer Guava jar ahead of the error-prone-core jar.  When the error-prone-core jar is ahead of the Guava jar, you get an old copy of `Throwables`.

Can you switch to use a newer version of error-prone?

**Comment by andrewparmet** [comment]
Sure, I can use a newer version. I'm not quite sure what you mean when you say it contained a copy of Guava - the dependency tree shows that its version of Guava should be forced up to my required version. I didn't realize this has something to do with the classpath ordering?

**Comment by big-guy** [comment]
If you look at the contents of the [error prone core jar for 2.0.5](http://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.0.5/), you'll see Guava classes inside of it. It doesn't matter which version of Guava is chosen if the Guava jar appears after the error prone core jar in the classpath.

**Comment by andrewparmet** [comment]
Ah, I was looking through various POMs and must have missed some configuration somewhere that includes the Guava source. Thanks!
