### ISSUE TITLE
Allow module replacement rules to provide descriptive reason and make available in resolution result

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3822]
Currently, module replacement rules are not visible in the `ResolutionResult` API or the `dependencyInsight` report. The [Nebula `replace` rule allows a custom description to be provided](https://github.com/nebula-plugins/gradle-resolution-rules-plugin/blob/86c24b6fd8b9ec161a91f7501d0e37126865d149/src/main/kotlin/nebula/plugin/resolutionrules/rules.kt#L78-L82) for these, and the `NebulaDependencyInsightReportTask` displays those reasons.

We should consider if we want to do this, or if we will simply deprecate `ComponentModuleMetadata` in place of a new 'substitutes' dependency constraint.

**Comment by melix** [comment]
This is implemented as part of #3830
