### ISSUE TITLE
Gradle 4.4 Eclipse plugin ignores classpath.defaultOutputDir

### ISSUE THREAD

**Issue by jereh16** [gradle/gradle#3825]
With Gradle 4.4 the eclipse plugin seperates the output for each source folder. The current default is to write all compiled classes to ${project}/bin/main or ${project}/bin/test. 

### Expected Behavior
The custom value of classpath.defaultOutputDir should be used for the output of each source folder.

### Current Behavior
build.gradle:
```
eclipse {
    classpath.defaultOutputDir = file('build-eclipse')
}
```

Eclipse .classpath
```
        <classpathentry path="build-eclipse" kind="output"/>

	<classpathentry output="bin/main" kind="src" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry output="bin/main" kind="src" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry output="bin/test" kind="src" path="src/test/java">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
	<classpathentry output="bin/test" kind="src" path="src/test/resources">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
```

### Expected Behavior
Eclipse .classpath
```
        <classpathentry path="**build-eclipse**" kind="output"/>

	<classpathentry output="**build-eclipse**/main" kind="src" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test,integrationTest"/>
		</attributes>
	</classpathentry>
	<classpathentry output="**build-eclipse**/test" kind="src" path="src/test/resources">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>

**Comment by Prodentity** [comment]
I came across this as well.  The difference between 4.3 and 4.4 is that the output portion of the entry was not included, thus the default was enough.  So I now have the following in my build:
```
    classpath {
        defaultOutputDir = file('build/classes/java/main')
        file.whenMerged {
            entries.each {
                source ->
                    // This seems kludgy.  If the second test is omitted, it fails processing a 'Project Dependency' entry
                    if (source.kind == 'src' && source.toString().contains('output')) {
                        source.output = 'build/classes/java/main'
                    }
            }
        }
    }
```
The kludge is because, although you would expect that the kind = src is sufficient, it returns far more and without the test, it crashes.

**Comment by oehme** [comment]
The default output dir is just what the name says: The default for source folders that specify no output. Gradle now specifies an output for each source folder automatically, so the default output dir is rarely ever used anymore. This is intentional. You can remove the output directory decalaration if you really want to put things into the same folder.

**Comment by jereh16** [comment]
I would like to have a configuration where i could define where the build artefacts are generated. The current implementation in gradle 4.4 always uses /bin/main or /bin/test. I would like to change that to /build/eclipse/main and build/eclipse/test. In versions before 4.4 this was possible by setting the default output dir :-(

**Comment by oehme** [comment]
You can change these defaults using `classpath.file.whenMerged {}`, as @Prodentity pointed out.

**Comment by jereh16** [comment]
Yes sure, but it looks more like a workaround than a solution. Seems I have to live with that.

**Comment by oehme** [comment]
So what you're looking for is something like an `outputBaseDir`?

**Comment by jereh16** [comment]
Yes, i would like to configure the base dir for all eclipse outputs.

**Comment by PaoloFinamore** [comment]
There would be another workaround to 

> 
> 
> I came across this as well. The difference between 4.3 and 4.4 is that the output portion of the entry was not included, thus the default was enough. So I now have the following in my build:
> 
> ```
>     classpath {
>         defaultOutputDir = file('build/classes/java/main')
>         file.whenMerged {
>             entries.each {
>                 source ->
>                     // This seems kludgy.  If the second test is omitted, it fails processing a 'Project Dependency' entry
>                     if (source.kind == 'src' && source.toString().contains('output')) {
>                         source.output = 'build/classes/java/main'
>                     }
>             }
>         }
>     }
> ```
> 
> The kludge is because, although you would expect that the kind = src is sufficient, it returns far more and without the test, it crashes.

'source.toString().contains('output')' can be replaced with 'source.hasProperty('output')'
