### ISSUE TITLE
[Help] Apply Plugin only for release or disable plugin for variants 

### ISSUE THREAD

**Issue by biaomingzhong** [gradle/gradle#3836]
I am using a android library name `com.growingio.android:vds-android-agent:1.1.1@aar` . It needs to use a plugin to transform my code in artifact state . The library name is  `com.growingio.android` where buildscipt dependencies is `classpath 'com.growingio.android:vds-gradle-plugin:1.1.1'`

But It took really long time to transform my code after every `installDebug`, while I only want to use this plugin in release variant. 

I have use variants to split my code to `debug` and `release` variant. Only in `release` variant, my project use `releaseImplementation` to include their aar. My `debug` variant didn't import or use their code in any ways to speed up my build in `installDebug`. But their plugin just scan and try to transform my code no matter what.

Please know that in my profile report for `installDebug`, their plugin's transform task is most time-consuming.

😃  Can someone help me out here?

**Comment by biaomingzhong** [comment]
I have post this question in [discuss.gradle.org](https://discuss.gradle.org/t/apply-plugin-only-for-release-or-disable-plugin-for-variants/25141). But no one reply anything in 4 days.

**Comment by oehme** [comment]
Please get in touch with that plugins author. The plugin should let you choose which variants you want to transform. Or maybe it should just notice that the variant isn't using their library and automatically disable the task for that variant.
