### ISSUE TITLE
Provide eclipse.classpath.outputBaseDir

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3839]
Gradle uses separate output folders for each source folder since 4.4. They are all located under the `bin` directory by default. Changing that base dir is rather cumbersome:

```
classpath {
   file.whenMerged {
       entries.each { entry ->
            if (entry instanceof org.gradle.plugins.ide.eclipse.model.Output) {
               entry.path = entry.path.replace('bin', 'build/eclipse')
            }
       }
   }
}
```

It would be great if there was an `outputBaseDir` instead that users can change:

```
classpath {
   outputBaseDir = 'build/eclipse'
}
```

This is a follow-up to #3825

**Comment by oehme** [comment]
@jereh16 this would be a good candidate for a pull request

**Comment by rubin55** [comment]
Your example in the description:

```
classpath {
   file.whenMerged {
       entries.each { entry ->
            if (entry instanceof org.gradle.plugins.ide.eclipse.model.Output) {
               entry.output = entry.output.replace('bin', 'build/eclipse')
            }
       }
   }
}
```

Gives the following error: 

```
<backtrace lines here>
Caused by: groovy.lang.MissingPropertyException: No such property: output for class: org.gradle.plugins.ide.eclipse.model.Output
```

When I look at Output.java, I see a get/set Path but no output field; what am I missing?

**Comment by oehme** [comment]
I meant path, changed the example above.

**Comment by vlotarev** [comment]
BTW it would be nice to have a way to restore 4.3. behavior, i.e. to have a possibility to put all the compiled classes to the single output folder.

**Comment by oehme** [comment]
You can use the code I showed above and adjust it to remove the output folder attribute instead.

**Comment by mhldtna** [comment]
I tried this, and it didn't work.  Specifically, I put this in build.gradle for one project in a multi-project build:
`
  eclipse {
	classpath {
	   file.whenMerged {
	       entries.each { entry ->
	            if (entry instanceof org.gradle.plugins.ide.eclipse.model.Output) {
	               entry.path = entry.path.replace('bin', 'build/classes/')
    			}
		 	}
		}
	}
  }`

After refreshing the project, I found that the default output directory has been updated as expected, but the output folders for each source file have not been updated. For example:
`<classpath>
	<classpathentry kind="output" path="build/classes//default"/>
	<classpathentry output="bin/main" kind="src" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry output="bin/main" kind="src" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>`

Also, I tried this in the root project, like this:
`subprojects {
  eclipse {
	classpath {
	   file.whenMerged {
	       entries.each { entry ->
	            if (entry instanceof org.gradle.plugins.ide.eclipse.model.Output) {
	               entry.path = entry.path.replace('bin', 'build/classes/')
    			}
		 	}
		}
	}
  }
}`

... and I got this error on the "file.whenMerged" line:
`Cannot invoke method whenMerged() on null object`

**Comment by wordlessly** [comment]
What the EclipsePlugin is doing:

1. defying intuitive Eclipse standard by using: DEFAULT_PROJECT_OUTPUT_PATH = "bin/default";
2. defying intuitive Eclipse standard by specifying an output dir per source folder: 	`<classpathentry kind="src" output="bin/main" path="src">`
3. adding clutter like to .classpath: `<attribute name="gradle_scope" value="main"/>			<attribute name="gradle_used_by_scope" value="main,test"/>`
4. making it straight up cumbersome, ugly and error-prone to fix this insanity

I played through ever interpretation of how this absolutely unexpected behavior of EclipsePlugin could have come to live. Even the most positive reading (incompetence and a complete lack of understanding of what Eclipse users expect) doesn't seem plausible. It all doesn't make sense.

Help me out here. What's the plan? Do you want to drive people to Intellij IDEA by making Gradle just ugly and annoying for Eclipse users?

**Comment by dgeissl** [comment]
The thing is, one can already customize the defaultOutputPath and I expected it to be the baseDir for all other output paths, but it is not:
```groovy
eclipse {
    classpath {
        defaultOutputDir = file('build') // this should be enough
        file {
            whenMerged { // but we still need to adjust the outputs for src paths
                cp -> cp.getEntries().forEach{
                    cpEntry -> if(cpEntry.kind=='src') {
                        cpEntry.output = cpEntry.output.replace('bin/', 'build/')
                    }
                }
            }
        }
    }
}
```
and even this defaultOutputDir is not set to 'build' but 'build-default'.

**Comment by wordlessly** [comment]
All Gradle-Eclipse-Defaults should be identical to Eclipse-Defaults when you create a project. Since ALL (src, per source-folder outputdir, default output dir, etc.) the Eclipse-Defaults are ignored by the Gradle-Eclipse plugin one wonders if this is deliberate? The IDEA plugin respects all of IDEA's defaults. Does this all make sense now?

**Comment by stanio** [comment]
It is sad and unfortunate one has to clutter the build scripts with explicit `eclipse` plugin customizations.  It could just use the default Eclipse output-dir as `baseOutputDir` instead of hard-coding it to `bin/`.
