### ISSUE TITLE
Getting system headers for gcc does not consider the executable set in the target platform.

### ISSUE THREAD

**Issue by PGaus** [gradle/gradle#3857]
### Expected Behavior
The GccMetadataProvider has to consider the corresponding executable (not always "/usr/bin/gcc") set in the target platform.
```gradle
model {
    toolChains {
        gcc(Gcc) {
            target("foobar"){
                cppCompiler.setExecutable "/opt/foobar/g++"
            }
         }
    }
}
```
### Current Behavior
The GccMetadataProvider calls compilerArgs() with "/usr/bin/gcc" which leads to wrong system includes for different compilers. This leads to a wrong options.txt file for gcc

### Steps to Reproduce (for bugs)
Compile with multiple gcc compilers on same system

### Your Environment
Ubuntu 14.04 LTS with GCC 4.8.5 under /usr/bin/gcc + arm-linux-gnueabihf-g++ and aarch64-poky-linux-g++ under /opt/... in tollchains

**Comment by wolfs** [comment]
@PGaus Thank you for your report. I guess you are using Gradle 4.4?
The problem you are describing should be already fixed on `master`. Could you try a [nightly](https://gradle.org/nightly/) and see if that fixes your problem?
The issue would be the same as https://github.com/gradle/gradle-native/issues/281 I suppose.

**Comment by PGaus** [comment]
@wolfs Thanks for the fast response. Yes I used 4.4.
Yeah, this is the same issue than gradle/gradle-native#281.
I tried nightly 4.5-20180102235856+0000 with which the problem is solved, but I still have one remark. Because in my opinion these paths should **not** be included in the options.txt files.

**Comment by wolfs** [comment]
Closing as duplicate as https://github.com/gradle/gradle-native/issues/281.
