### ISSUE TITLE
Update to HttpClient 4.5.5

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#3859]
We upgraded several dependencies in 4.4 (https://github.com/gradle/gradle/pull/3253).  But when we updated to HttpClient 4.5.3, but we had to revert back to 4.4.1 due to #3663.

HttpClient 4.5.4 was released December 4 and contains a fix for #3663, so we should be able to try an update again.

**Comment by bmuschko** [comment]
I tried upgrading to HttpClient 4.5.4 in a branch to see if it passes CI. Unfortunately, that version has another regression we ran into with our build: [HTTPCLIENT-1888](https://issues.apache.org/jira/browse/HTTPCLIENT-1888). We'll have to wait until 4.5.5 is released.

**Comment by bmuschko** [comment]
4.5.5 is still not available. Left a [comment](https://issues.apache.org/jira/browse/HTTPCLIENT-1888?focusedCommentId=16316863&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16316863).
