### ISSUE TITLE
Apply DSL-defined dependency constraints when experimentalFeatures is disabled

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3870]
Currently, we are not applying any dependency constraints in resolution, unless `experimentalFeatures` is enabled. It doesn't make any sense to me to have a DSL construct `dependencies { constraints {}}` and have it make no difference without `experimentalFeatures`.

In my mind, it's much simpler to say that `dependencyConstraints` work in 4.5, but they will never be present in a resolved external module.

Change things so that we use `experimentalFeatures`:
1. When converting Maven metadata into a `ConfigurationMetadata`
2. When deciding whether to publish or resolve Gradle metadata files

**Comment by bigdaz** [comment]
I reverted the fix due to a performance regression. Will try again.

**Comment by jjohannes** [comment]
I think a fix to get to roughly the same performance as before would be to do this in `DefaultPendingDependenciesHandler`:

- Not always create `PendingDependenciesState`
- Do this to lazily create the state (or not) in the beginning of `maybeAddAsPendingDependency()`
```
            if (DefaultPendingDependenciesHandler.this.pendingDependencies == null && !dependencyState.getDependencyMetadata().isPending()) {
                return false;
            }
            if (pendingDependencies == null) {
                pendingDependencies = new PendingDependenciesState();
            }
```

This way the expensive code never runs when we do not have pending dependencies at all in the graph. 
Another general optimisation, which is to run the substitution rules less, can then be done in a separate step.

**Comment by bigdaz** [comment]
@jjohannes that  _might_ work, but we'll still be running the dependency substitution rules multiple times. This happens in `ModuleIdentifier key = lookupModuleIdentifier(dependencyState);`. 

Trying it out and measuring will be the only way to know for sure.

**Comment by jjohannes** [comment]
That's what I mean. With what I suggested, `lookupModuleIdentifier()` is never called as long as `!dependencyState.getDependencyMetadata().isPending()` is always true (i.e. we never hit a pending dependency).
I am not saying that that is the final and ideal solution. But it _could_ be a fist step to get this change in for now and restore the performance we had when we used the "NoOpPendingDependenciesHandler".

But if we can do a better solution right away that's fine of course. Just wanted to mention this.

**Comment by bigdaz** [comment]
Hmm. That means that we won't be calling `DefaultPendingDependenciesHandler.this.pendingDependencies.notPending(key)` for those dependencies, but I guess we won't need to. Thanks for the idea: I'll try it out.

**Comment by bigdaz** [comment]
@jjohannes It looks like our pending dependencies support requires us to track all non-pending dependencies, just in case a pending dependency is seen later. This allows us to know whether we should convert the pending dependencies into hard dependencies.

**Comment by melix** [comment]
That's correct. That's because of replacements, which are (currently) handled by the conflict resolution handler. So if you see a dependency A that is _optional_, it _may_ be replaced with a dependency _B_ which is **not**. If you only take the optionality of _A_ into consideration, then you wouldn't upgrade to _B_ properly.
