### ISSUE TITLE
BuildOperationTrace is broken for composite builds 

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#3873]
When running a composite build with `-Dorg.gradle.internal.operations.trace`, the trace is broken due to 
`ApplyScriptPluginBuildOperationType.Details#getBuildPath()` always throwing an `IllegalStateException` for `settings.gradle` scripts of included builds resulting in a trace file that doesn't contain the buildPath for applied settings scripts of non root builds.

**Comment by breskeby** [comment]
Added PR exposing the problem at https://github.com/gradle/gradle/pull/3874

**Comment by ldaley** [comment]
This aspect has effectively been fixed by #4227. I have raised #4241 to cover the fundamental root cause.
