### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hhxx1994** [gradle/gradle#3896]
Error:Could not set unknown property 'configDir' for object of type org.gradle.api.plugins.quality.CheckstyleExtension.

when I build the version 4.4 source

**Comment by hhxx1994** [comment]
can not find the jquery.min.xml

**Comment by bmuschko** [comment]
I am going to close the issue. Your problem description doesn't show a reproducible example and seems to describe two different issues. Please provide more information based on the issue template.
