### ISSUE TITLE
Gradle should check subsequent repositories when a POM without artifacts is found

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3897]
### Current Behaviour

When a POM file is present in a repository _without any matching artifacts_, Gradle will use that repository to resolve the module, often resulting in failure when resolving the artifacts.

### Expected Behaviour
Instead, Gradle should ignore the 'incomplete' module, and continue to search other repositories for the module.

Split out from #3666

**Comment by ljacomet** [comment]
Given the risks involved in anything that relates to metadata and the state in which they exist out there, I believe such corner cases should not be handled by Gradle.

And especially since Gradle 5.1 and the support for #1369, there is a relatively easy workaround.

**Comment by ljacomet** [comment]
Confirmed that this will not be done.
