### ISSUE TITLE
Gradle import com.fasterxml.jackson.datatype cannot be resolved

### ISSUE THREAD

**Issue by Premiumlab** [gradle/gradle#3899]
<img width="547" alt="screen shot 2017-12-23 at 8 01 49 pm" src="https://user-images.githubusercontent.com/24338630/34323862-917674b4-e820-11e7-8023-900e66f5059f.png">

As the screen shot shows, import com.fasterxml.jackson.datatype cannot be resolved.

Here's what I add into the  build.gradle

<img width="696" alt="screen shot 2017-12-23 at 8 37 17 pm" src="https://user-images.githubusercontent.com/24338630/34323874-1d92fe36-e821-11e7-813e-91c05143fdb3.png">

The last a few lines are from the Maven Repo: https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.9.3

To solve this problem, I tried to add more dependencies in build.gradle, as this post suggests

Jackson cannot access com.fasterxml.jackson.core.ObjectCodec

https://stackoverflow.com/questions/31356952/jackson-cannot-access-com-fasterxml-jackson-core-objectcodec

<img width="696" alt="screen shot 2017-12-23 at 8 38 59 pm" src="https://user-images.githubusercontent.com/24338630/34323879-58efc46e-e821-11e7-943c-28431c43d59d.png">

But it is still not imported.

The IDE I am using is Spring Tool Suite, and it is a web application.

Thanks!

@cowtowncoder 

 
EDIT1:

I understand that jackson-datatype-jsr310 is DEPRECATED and has become part of Jackson Java 8 Modules as of Jackson 2.8.5.

However, I add this to the end of build.gradle,

`    // https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jdk8
compile group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jdk8', version: '2.9.3'`

And import this

`import com.fasterxml.jackson.datatype.jdk8;`

It still shows import com.fasterxml.jackson.datatype cannot be resolved.

<img width="499" alt="screen shot 2017-12-23 at 11 45 20 pm" src="https://user-images.githubusercontent.com/24338630/34324524-c775269e-e83b-11e7-8e5a-e29f0fafd5b2.png">

EDIT2:

Both Eclipse and STS are the latest version.

<img width="514" alt="screen shot 2017-12-25 at 11 09 37 pm" src="https://user-images.githubusercontent.com/24338630/34347510-9421bb1a-e9c9-11e7-8684-b079acea9a13.png">

<img width="985" alt="screen shot 2017-12-25 at 11 10 11 pm" src="https://user-images.githubusercontent.com/24338630/34347515-9bae696e-e9c9-11e7-85bf-d7c4a04d7a3a.png">

<img width="1167" alt="screen shot 2017-12-25 at 11 10 33 pm" src="https://user-images.githubusercontent.com/24338630/34347516-a0800416-e9c9-11e7-987a-69b793003cf3.png">

**Comment by bmuschko** [comment]
Pivotal's STS support for Gradle has been deprecated and will be removed sooner or later. Please use [Buildship](https://projects.eclipse.org/projects/tools.buildship) instead. Please report back if that doesn't solve your problem.

**Comment by bmuschko** [comment]
I am going to close this issue for now. Please add another comment if you'd like to follow up. There should be no general issue with resolving Jackson from Maven Central as demonstrated by this example:

```
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.3'
}
```

**Comment by nenadbulatovic** [comment]
@bmuschko
`compile 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.3'`
that is not working, juts tried it.

**Comment by beezerbt** [comment]
@bmuschko 
i did the same and it is not working either.

**Comment by beezerbt** [comment]
It was the GODDAMN gradle.properties.
I had it set so that it had proxy information for my corporate network.
And it was buggering intellij up...but there is absolutely jack error message wise!
I simply removed ALL the proxy information from the properties and the following worked:
plugins {
    id 'java'
}

group 'herd'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile "org.mockito:mockito-core:2.+"
    compileOnly 'org.projectlombok:lombok:1.18.2'
    compile 'com.google.guava:guava:27.0-jre'
    compile 'com.fasterxml.jackson.core:jackson-core:2.4.1'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.4.1'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.4.1'
}
