### ISSUE TITLE
`PomReader` parse active pom profiles is error!

### ISSUE THREAD

**Issue by warningrc** [gradle/gradle#3905]
at `PomReader.isActivationPropertyActivated ` method as follow:

https://github.com/gradle/gradle/blob/022de6f9e371785a31a5001df84138b45650f516/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/PomReader.java#L684-L687

https://github.com/gradle/gradle/blob/022de6f9e371785a31a5001df84138b45650f516/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/PomReader.java#L646-L652

Maven to activate this profile if  the property customProperty is start with "!".
But [Maven documentation](http://books.sonatype.com/mvnref-book/reference/profiles-sect-activation.html#profiles-sect-activation-config)  say:
>The property element tells Maven to activate this profile if the property customProperty is set to the value xxx

**Comment by bmuschko** [comment]
Please be aware that the current implementation in Gradle was a deliberate decision. You can find more information on activating profiles by system property in the blog post ["Gradle's Support for Maven POM Profiles"](https://blog.gradle.org/maven-pom-profiles). Activating profile by system property makes a build potentially unreproducible depending on the user's setup.
