### ISSUE TITLE
Resolving an unrelated configuration causes code-quality plugins `toolVersion` to be ignored

### ISSUE THREAD

**Issue by eslafgh** [gradle/gradle#3908]
I noticed with a github project I follow that when using gradle 4.4.1 (rather than 4.3.1) the tool version of pmd used when running the pmdMain task was reverting to the default rather than using the version requested by the build files.

### Expected Behavior

pmdMain task should use the tool version set by the build file.

### Current Behavior

With certain build file setups (see below) the default pmd tool version is used rather than the one set in the build file.

### Context

With gradle 4.3.1 the pmd tool version set by the build file was being used correctly.

A bisect revealed the problem started with commit 67ff46b9da551e9df2ba4529e36ce9327a462901 which according to the comment was a fix for issue #812.

### Steps to Reproduce (for bugs)

The following gradle.build can be used to demonstrate when the problem occurs.

```
plugins {
  id 'java'
  id 'pmd'
}
repositories { mavenCentral() }

// Need a non empty configuration.
dependencies { testCompile group: 'junit', name: 'junit', version:'4.12' }

if(hasProperty('triggerProblem')) {
  configurations.testCompile.each { } // With this line pmd version 5.6.1 (the default) is used.
}

// Tool version change after line that triggers problem, otherwise there is no problem.
pmd { toolVersion = "5.8.1" }

```

Need a source file so pmdMain has something to do.

```
$ mkdir -p src/main/java 
$ echo "class X {}" > src/main/java/X.java
```

Run without trigger line, no problem pmd 5.8.1 used.

```
$ gradle-4.4.1 -q clean pmdMain
$ grep "<pmd" build/reports/pmd/main.xml 
<pmd version="5.8.1" timestamp="2017-12-26T16:47:56.273"
```

Run with trigger line, then pmd 5.6.1 (the default) is used.

```
$ gradle-4.4.1 -q -PtriggerProblem=1 clean pmdMain
$ grep "<pmd" build/reports/pmd/main.xml 
<pmd version="5.6.1" timestamp="2017-12-26T16:48:52.547">
```

No problem with gradle 4.3.1

```
$ gradle-4.3.1 -q -PtriggerProblem=1 clean pmdMain
$ grep "<pmd" build/reports/pmd/main.xml 
<pmd version="5.8.1" timestamp="2017-12-26T16:49:34.372">
```

### Your Environment

```
$ gradle-4.4.1 -v

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Linux 4.4.106-gentoo amd64
```

**Comment by bmuschko** [comment]
Could you please provide information on why you iterate over the dependencies of the `testCompile` configuration at configuration time? I will likely want to do that during execution time in a task's action. I can reproduce the issue but my question still stands. 

@bigdaz Could you have a look at this? Seems like iterating over a configuration during Gradle's configuration phase before the PMD tool version is set has a set effect on the default configuration functionality.

**Comment by eslafgh** [comment]
The original build file that I observed the problem with was https://github.com/PCGen/pcgen/blob/master/build.gradle which iterates over the runtime configuration to generate a classpath for a jar file i.e. it contains the following:
```
ext {
    classpath = ""
    configurations.runtime.each { lib -> classpath += " libs/${lib.name} "}
}
```
while I was playing with my demo build file I changed from runtime to testCompile and to see if that made any difference (which it did not).

**Comment by blindpirate** [comment]
Thanks @eslafgh for raising this issue. A workaround is moving `pmd{ }` block in front of the iteration:

```
plugins {
  id 'java'
  id 'pmd'
}
repositories { mavenCentral() }

// Need a non empty configuration.
dependencies { testCompile group: 'junit', name: 'junit', version:'4.12' }

// Tool version change after line that triggers problem, otherwise there is no problem.
pmd { toolVersion = "5.8.1" }

if(hasProperty('triggerProblem')) {
  configurations.testCompile.each { } // With this line pmd version 5.6.1 (the default) is used.
}
```

@bigdaz looks like `configuration.each` triggers [`default dependency action`](https://github.com/gradle/gradle/blob/2622baaf86d959685f94c947302b5fb1b26f4ac5/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java#L98) prematurely via [`DefaultConfigurationComponentMetaDataBuilder.addConfiguration`](https://github.com/gradle/gradle/blob/ececd24d0258ec1350c7d64e9431b9d70690c2ca/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/DefaultConfigurationComponentMetaDataBuilder.java#L48).

**Comment by bigdaz** [comment]
This bug is due to the fact that we are now executing the `defaultDependencies` action for _every_ configuration whenever _any_ configuration is resolved. Instead we should only execute the `defaultDependencies` action for a configuration when it is resolved, or participates in dependency resolution.
