### ISSUE TITLE
Cannot resolve recursive copy of configuration with cyclic project dependencies.

### ISSUE THREAD

**Issue by funvin** [gradle/gradle#3913]
Here's all the context you need - 
https://discuss.gradle.org/t/cannot-resolve-recursive-copy-of-configuration-with-cyclic-dependencies-within-beforeresolve/8726
https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/46

**Comment by bmuschko** [comment]
@bigdaz @melix @jjohannes Could you please comment on this?

**Comment by bigdaz** [comment]
Closing as duplicate of #1638
