### ISSUE TITLE
Error:Cannot find snapshot for id: -4123461672748341163

### ISSUE THREAD

**Issue by Pryansh** [gradle/gradle#3919]
### Your Environment

 * Build scan URL:

**Comment by Pryansh** [comment]
![screenshot 8](https://user-images.githubusercontent.com/34795123/34404529-1f050136-ebd4-11e7-9d35-4688e166332f.png)

**Comment by wolfs** [comment]
@Pryansh Could you please provide a little bit more detail for the problem you are encountering?

It seems like you are hitting https://github.com/gradle/gradle/issues/2827#issuecomment-327121069, that should be fixed as of Gradle 4.3.
Which Gradle version are you using?

**Comment by wolfs** [comment]
I am closing this issue. Please re-open/comment on #2827 if you continue to have this problem in 4.3+.
