### ISSUE TITLE
Build failed due to error in Retrolambda because of Java 9

### ISSUE THREAD

**Issue by Nighty42** [gradle/gradle#3921]
### Expected Behavior

The Gradle build should be executed successfully with no error while executing the task "applyRetrolambda".

### Current Behavior

The Gradle build failed when the task "applyRetrolambda" is executed do to an issue in Retrolambda itself til version 2.5.1 due to an incompability issue with Java 9. For details see this issue at Retrolambda: 
[Retrolambda - Issue 137](https://github.com/orfjackal/retrolambda/issues/137?_pjax=%23js-repo-pjax-container).

The developers of Retrolambda already applied a fix in version 2.5.2 which was published at 28.12.2017. It would be nice if you could update your version of Retrolambda with the next release.

### Context

I tried to create a build of a JavaFX application with Gradle for Android.

### Steps to Reproduce (for bugs)

Install the newest Java 9 JDK (9.0.1) with Android SDK 27 and try to build an existing JavaFX application with "gradle build android".

### Your Environment

 * Build scan URL: 
Windows 10 x64, Android SDK 27, Java JDK 9.0.1, Gradle 4.4.1 (incl. Retrolambda 2.5.1)

**Comment by bmuschko** [comment]
Retrolambda is not part of the Gradle core distribution. The dependency either comes from the Android plugin or another plugin (maybe https://github.com/evant/gradle-retrolambda?). I am going to close this issue. Please open an issue for the plugin that declares the dependency.
