### ISSUE TITLE
Lockable `Property` concept should be part of the public API

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#3925]
Gradle native heavily use the `Provider`/`Property` concept. To enforce some restriction, some `Property` can be locked to prevent any modification in the future.

### Expected Behavior
Lockable `Property` concept should be available to plugin author to be used in 3rd party plugins.

### Current Behavior
`AbstractLockableProperty`, `LockableProperty`, `LockableListProperty` and `LockableSetProperty` are all internal types, hence, plugin author must rely on internal API if they want to use them.

### Context
`Provider`/`Property` concept is a new and improved way to defer work later in Gradle's build execution. Some values need to attain a final (locked) state in order to move forward with the configuration of a build. Once locked, we want to notify the build author of any mistake when modifying the property.

**Comment by ldaley** [comment]
Is this another dimension of API explosion? What if I want a lockable `DirectoryProperty`? What about `SetProperty`?

**Comment by lacasseio** [comment]
Excellent point @ldaley. We should have a broader discussion about this as it's not the first time this is raised. Let's discuss the implication in the this issue: https://github.com/gradle/gradle/issues/4019

**Comment by adammurdoch** [comment]
This is added via https://github.com/gradle/gradle/pull/7371
