### ISSUE TITLE
CheckstylePlugin seems to modify dependency configurations

### ISSUE THREAD

**Issue by esz** [gradle/gradle#3927]
### Expected Behavior

Applying the checkstyle plugin to the build should not make any differences (in terms of visible classes during the build) when building a project that includes sources generated into a separate source set by the hibernate annotation processor.

### Current Behavior

My build fails reproducibly after applying the checkstyle plugin (`javax.persistence.metamodel.SingularAttribute` and other classes are not visible any more within the generated source set `annotationProcessing`)

### Steps to Reproduce (for bugs)

* clone https://github.com/esz/checkstyle_classpath
* enable this line in build.gradle: `// apply plugin: 'checkstyle'`
* `gradlew clean build` and observe compilation failure due to missing classes
* uncomment `apply plugin: 'checkstyle'` again
*  `gradlew clean build` and observe that the build works now

### Your Environment

I am able to reproduce this behavior on different environments.
My current environment is:
- Windows 10x64
- gradle 4.4
- JDK 8

**Comment by blindpirate** [comment]
I'm afraid you've misunderstood the usage of source set here. You should put java source code into `src/annotationProcessing/java/` and simplify your `build.gradle` to:

```
sourceSets {
        annotationProcessing
}

dependencies {
        annotationProcessingCompile group: 'org.hibernate', name: 'hibernate-core', version: '5.2.11.Final'
        annotationProcessingCompile group: 'org.hibernate', name: 'hibernate-jpamodelgen', version: '5.2.11.Final'
}
```

Please see https://docs.gradle.org/current/userguide/java_plugin.html for more details.

**Comment by esz** [comment]
@blindpirate, thank you for your reply.

I modified my example (https://github.com/esz/checkstyle_classpath) according to your suggestion. The problem, however, still persists.

The project contains the following two source sets:

**src/main/java**
-  projectname.model.MyEntity (a hibernate entity)

**src/annotationProcessing/java**
- projectname.model.MyEntity_ (I generated this class manually with the hibernate annotation processor - `hibernate-jpamodelgen`)

Building this project with checkstyle enabled or disabled, by in- or excluding this one-liner:
```
apply plugin: 'checkstyle'
```
should definitively not make any difference in the project's build path visible to the compiler.

However with **checkstyle enabled**, I get: https://github.com/esz/checkstyle_classpath/blob/master/build_with_checkstyle.txt

...and with **checkstyle disabled**, I get: https://github.com/esz/checkstyle_classpath/blob/master/dependencies_without_checkstyle.txt

Would you please reopen this issue?

**Comment by blindpirate** [comment]
Yes, it makes a difference with `checkstyle` plugin applied or not.

`checkstyle` plugin will create extra [configuration](https://docs.gradle.org/current/userguide/dependency_management.html#sub:configurations) so the dependencies outputs are different.

When it comes to the build, without `checkstyle` plugin, your `annotationProcessing` source set doesn't get compiled and checked, you can observe there's no `compileAnnotationProcessingJava` in https://github.com/esz/checkstyle_classpath/blob/master/build_without_checkstyle.txt . With `checkstyle` plugin enabled, all source sets will be compiled, thus trigger the error.

If you want to use separate source sets, you'd write:

```
sourceSets {
        annotationProcessing {
            compileClasspath += sourceSets.main.output
        }
}
dependencies {
        compile group: 'org.hibernate', name: 'hibernate-core', version: '5.2.11.Final'
        compile group: 'org.hibernate', name: 'hibernate-jpamodelgen', version: '5.2.11.Final'
        annotationProcessingCompile group: 'org.hibernate', name: 'hibernate-core', version: '5.2.11.Final'
        annotationProcessingCompile group: 'org.hibernate', name: 'hibernate-jpamodelgen', version: '5.2.11.Final'
}
```

And I highly recommend you to read  https://docs.gradle.org/current/userguide/java_plugin.html first.
