### ISSUE TITLE
libgcc support x86_64 architecture 

### ISSUE THREAD

**Issue by modularity** [gradle/gradle#3929]
### Expected Behavior
libgcc should support x86_64 architecture 

### Current Behavior
only libgcc.i686 is supported

### Context
Tried to build Android project with new dependencies via 'react-native run-android' 

### Steps to Reproduce (for bugs)
Successfully created React Native project, installed 'amazon-cognito-identity-js' and ran 'react-native link' on this dependency.
After running 'react-native run-android' the build failed with the following error:
```
Android/Sdk/build-tools/23.0.1/aapt: error while loading shared libraries: libgcc_s.so.1: 
cannot open shared object file: No such file or directory

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':amazon-cognito-identity-js:processReleaseResources'.
com.android.ide.common.process.ProcessException: Failed to execute aapt 
```

I verified that libgcc was installed
```
$ yum list installed | grep libgcc
libgcc.x86_64                              7.2.1-2.fc27                @fedora
 ```

Following this [StackOverflow](https://stackoverflow.com/questions/43498186/fedora-25-libgcc-s-so-1-not-found) post, I ran
``` 
sudo dnf install libgcc.i686 
```
This resolved the error and the build successfully compiled.

### Your Environment
Fedora 27
gradle 2.2.3
React Native 51.0

**Comment by bmuschko** [comment]
Please open Android-related issues on the Android Issue Tracker at `https://source.android.com/source/report-bugs`.
