### ISSUE TITLE
Provide summary of experimental features and breaking changes

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3933]
https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/preview-features.adoc

**Comment by bigdaz** [comment]
https://github.com/gradle/gradle/commit/5fad35f3430c758e8fc2499ff0193045d6cff120

**Comment by jjohannes** [comment]
I will adjust the doc as part of #3945 and structure it according to what's done there. If possible, we can document some features, which are not opt-in, directly in the docs and then link to them. I'll create separate issues for those:
- #3961 (metadata sources)

**Comment by jjohannes** [comment]
Lets continue work on this in the issues linked above ☝️.
