### ISSUE TITLE
Gradle fails to resolve dependencies with no group on Ivy repository

### ISSUE THREAD

**Issue by max-ag** [gradle/gradle#3938]
With Gradle 4.2, resolving a dependency that doesn't have any group set works.
With Gradle 4.5-20171220235901+0000, resolving the same dependency fails.

### Expected Behavior

I'm expecting the dependency to be resolved properly, as with Gradle 4.2.

### Current Behavior

Can't resolve the dependency.

### Steps to Reproduce (for bugs)

```
repositories {
    ivy {
        name = "myIvyRepo"
        url = <url_to_repo>
        layout 'pattern', {
            ivy "[organisation]/[module]/ivy-[revision].xml"
            artifact "[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]"
        }
        credentials {
            username = <user>
            password = <password>
        }
    }
}

configurations {
    bob
}

dependencies {
    bob ":DEPENDENCY:1.0.0@zip"
}

task installBob(type: Copy) {
    from(zipTree(configurations.bob[0]))
    into file("${buildDir}/install")
}
```

Then just run 'gradle tasks'

**Comment by oehme** [comment]
Your pattern marks `organisation` as mandatory, so this is expected. Please use `([organisation])` instead to mark it as optional.
