### ISSUE TITLE
Expose maven repository constructor via GroovyMavenDeployer

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#3944]
This issue is a request to expose maven repository constructor via GroovyMavenDeployer.

Example of configuring in [maven plugin manual](https://docs.gradle.org/current/userguide/maven_plugin.html) shows to set local repository using:
```
uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "file://localhost/tmp/myRepo/")
        }
    }
}
```

### Expected Behavior
[GroovyMavenDeployer](https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/maven/src/main/java/org/gradle/api/artifacts/maven/GroovyMavenDeployer.java) show have `public RemoteRepository repository(Map properties) {` method.

Alternatively, GroovyMavenDeployer chould also have a `public RemoteRepository repositoryFromUrl(File file) {` method.

### Current Behavior
As of Gradle 4.4.1, this API is actually private so calling it from Java or Kotlin is impossible (without reflection or using internal classes). The desire method only exists in [DefaultGroovyMavenDeployer](https://github.com/gradle/gradle/blob/master/subprojects/maven/src/main/java/org/gradle/api/publication/maven/internal/deployer/DefaultGroovyMavenDeployer.java) which is in an internal package.

**Comment by bigdaz** [comment]
The `maven` plugin (together with the `repositories.mavenDeployer`) are being replaced by the `maven-publish` plugin. As such, we don't plan on making changes to improve this (now legacy) mechanism for publishing. Expect to see these types deprecated in Gradle 6.x, for possible removal in Gradle 7.0 (or later).

I'm closing this issue to reflect the fact that we don't plan on fixing this. In the meantime, feel free to continue using the internal `MavenRemoteRepository` and `DefaultMavenGroovyDeployer` types: we won't be changing them anytime soon.

**Comment by liutikas** [comment]
There is still no support for maven publishing aars using `maven-publish`. Given that a huge Gradle user comes from Android builds, it seems that we should not be able to deprecate/remove `maven` plugin until the support for Android Gradle Plugin artifacts is added.

**Comment by bigdaz** [comment]
> There is still no support for maven publishing aars using `maven-publish`.

@liutikas Can you please give a little more detail on this? Is this a matter of the Android plugin not supporting `maven-publish`, or something more fundamental? My understanding is that `maven-publish` should have all of the features required for publishing aars: if not, then we'll need to address any limitations before the "old" publishing mechanism can be deprecated.
