### ISSUE TITLE
Gradle Tooling API with Gradle Daemon contains memory leak

### ISSUE THREAD

**Issue by Crazyjavahacking** [gradle/gradle#3946]
On our huge multi-module Gradle project, the 2nd run of IntelliJ's "Refresh all Gradle projects" runs always OOM.

### Expected Behavior
The 2nd refresh of Intellij's "Refresh all Gradle projects" will be faster as the Gradle Daemon is already running and some of the data is already cached in the memory.

### Current Behavior
2nd refresh of all Gradle projects is much slower (48s vs. 6m) and eventually gets OOM. The GC is spending ~12% of CPU time.

From the jvisualvm view it is obvious that there is memory leakage:
1st run executes in ~48s, GC activity max ~ 1% of CPU, consumed memory ~500MB.
2nd run dies after ~ 6M, GC activity ~ 12% of CPU, consumed memory ~800MB.

### Context
This is not allowing us to refresh the IntelliJ's Gradle project for the 2nd time and Gradle daemon always has to be stopped.

### Steps to Reproduce (for bugs)
IntelliJ version: 2018.3.2
Gradle version: 4.5-20180102235856+0000
Gradle JVM: 1.8.0_144 (Oracle Corporation 25.144-b01)

See attached

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Please provide an hprof dump for the build, otherwise we can't investigate what the problem is. Also please make sure that the leak is not in your build or a community plugin. It is highly unlikely that there is a leak in Gradle itself, given how many large projects are successfully using it.

**Comment by oehme** [comment]
A service like dropbox should do the trick for larger files.

**Comment by oehme** [comment]
Another important questions is whether this occurs only with IDEA or whether you see the OOM on the command line too?

**Comment by Crazyjavahacking** [comment]
You are right, this is not caused by Gradle itself. If I comment out all non-standard Gradle plugins, the memory leak does not occur.

Closing this issue.

**Comment by oehme** [comment]
Thank you for following up! I'd love to know which plugin was causing the problem and how. Maybe something we can detect and warn about automatically.

**Comment by Crazyjavahacking** [comment]
Excelsior JET Gradle plugin: https://github.com/excelsior-oss/excelsior-jet-gradle-plugin.

I am currently investigating it and will let you know.

**Comment by Crazyjavahacking** [comment]
I created appropriate issue: https://github.com/excelsior-oss/excelsior-jet-gradle-plugin/issues/39.

It looks like there is some problem with convention mapping.

**Comment by Crazyjavahacking** [comment]
We were unable to investigate why the memory leak is happening. It just does not make much sense.

My assumption is that some code is storing strong reference to Excelsior JET Gradle plugin which stores reference to `gradle.api.Project` which stores references to spring objects.

Can you please help us with the investigation?

Links:
1. [Heap dump](https://drive.google.com/file/d/1FPMMCXFbucyTzHaK578AFBAwM-e2pJyY/view)
2. [Excelsior JET Github issue](https://github.com/excelsior-oss/excelsior-jet-gradle-plugin/issues/39)

**Comment by blindpirate** [comment]
@Crazyjavahacking I've downloaded your heap dump, thanks for reporting. After some check, I think it's normal for such a big project (seems 560+ subprojects) to cost 800MB memory. I didn't see anything particularly abnormal. Have you tried to set a larger `Xmx` in your `gradle.properties`? Or maybe you could provide us with more details of your project in case there's anything I missed.

**Comment by Crazyjavahacking** [comment]
It's normal, indeed. However without applying plugins once I perform resync in IntelliJ most of the objects are freed (as of JVisualVM graphs).

And Excelsior JET Gradle plugin is not really doing anything special in terms of memory, so it should not block objects to be freed by GC.

What kind of information would be helpful for you?

**Comment by oehme** [comment]
The problem is in the JET plugin, which uses [instance-level metaclasses](https://github.com/excelsior-oss/excelsior-jet-gradle-plugin/blob/f10b5ed7ecd6d8abe9434c314a1cac69949afb4d/src/main/groovy/com/excelsiorjet/gradle/plugin/ExcelsiorJetExtension.groovy#L408). These are held in memory by Groovy even after the instance is no longer used. They are only released after several minutes (soft references). This is a bug in Groovy of course, but I'm pointing out the JET plugin, because plugins shouldn't use metaclass magic at all. They should use plain old Java objects and Gradle's `Extension` mechanism, so that the DSL also works in Kotlin.
