### ISSUE TITLE
[Transform API] Is Proguard Transform guaranteed to be executed after custom transform?

### ISSUE THREAD

**Issue by jchensc** [gradle/gradle#3954]
I am writing a custom transform (Name: "DoSomething") using [Transform API](http://tools.android.com/tech-docs/new-build-system/transform-api). After adding the custom gradle transform plugin into project, I got this task list if I run `./gradlew assembleRelease -m`

```
// prev tasks
:app:transformClassesWithDoSomethingForRelease SKIPPED
:app:processReleaseJavaRes SKIPPED
:app:transformResourcesWithMergeJavaResForRelease SKIPPED
:app:transformClassesAndResourcesWithProguardForRelease SKIPPED
// other tasks
```

From the output we can see that DoSomething transform happens before Proguard transform. This is exactly what I want. However, according to the [Transform API Site](http://tools.android.com/tech-docs/new-build-system/transform-api), it says "There's no way to control ordering of the transforms."

Therefore, I'm wondering whether Proguard Transform is guaranteed to be executed after my custom transform? 

I'm asking here since there's no other sites/doc for an official answer. Thanks ahead!

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
I'm afraid you won't get a good answer here, since this is an Android-specific question. The Android plugin is not developed by the Gradle team. There is an issue tracker for the [Android plugin](https://source.android.com/source/report-bugs) and they often answer questions on stackoverflow.
