### ISSUE TITLE
Add documentation about metadataSources

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3961]
Document it in [repositoryTypes.adoc](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/repositoryTypes.adoc) and add something to the release notes. Describe `jcenter() {  mavenPom() }` as opt-out of the _looking for jars_ behaviour.

This is only about documenting the feature which you can use right now to opt-out of the old behaviour. It is not about changing the default in 5.0. This is covered in #3933.

**Comment by bmuschko** [comment]
Documentation should be part of your actual API changes. Is there a reason why you are not documenting it yet?

**Comment by jjohannes** [comment]
Add this to the "Repository types"  section of the [restructured documentation](https://docs.google.com/document/d/1op4_f_TC3ESJO7xvtvu0mrLpucTMJD8uVINqZMHVfdI).
