### ISSUE TITLE
Play plugin should make it easy to use the standard maven layout

### ISSUE THREAD

**Issue by gmethvin** [gradle/gradle#3970]
The Play sbt plugin has the [PlayLayoutPlugin](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/main/scala/play/sbt/PlayLayoutPlugin.scala) to enable the custom Play layout. Many people prefer not to use this plugin and use the standard layout, especially if they are developing a microservice and mixing both Play and non-Play services, or using tooling that expects the standard maven layout.

I actually like the way the maven plugin does it, since there you can see how everything is configured and easily remove things: https://play2-maven-plugin.github.io/play2-maven-plugin/1.0.0-rc1/usage-play26.html. Not saying it has to be done this way, but there should at least be a setting to enable/disable it.

**Comment by ptagr** [comment]
+1

**Comment by sentenza** [comment]
I'm testing [this g8 seed](https://github.com/muya/play-sbt-scala-seed.g8) and so far it seems the best way to enable the standard SBT layout for a Play! project.
