### ISSUE TITLE
allow pluginManagement block to appear at any place in settings.gradle

### ISSUE THREAD

**Issue by marmax** [gradle/gradle#3974]
### Expected Behavior
as a gradle user, I would like to be able to specify pluginManagement {} block at any place in settings.gradle, so I can set a condition prior it's use in pluginManagement block (while I expect such a condition to be used also in some other blocks)

As an example:
```
def isCI = System.getenv().containsKey("CI")
def forcePublic = System.getenv().containsKey("USE_PUBLIC")
def useLocal = isCI && !forcePublic

pluginManagement {
    repositories {
        maven {
            if (useLocal){
                url 'https://192.168.x.x/nexus/content/repositories/gradle-plugins/'
            } else {
                url 'https://nexus.example.org/nexus/content/repositories/gradle-plugins/'
            }
        }
    }
}

// another
if (isCI){
}

```

### Current Behavior
The pluginManagement {} block must appear before any other statements in the script (as documented), which gives no flexibility as shown above.

I can still achieve desired functionality, but using duplicated variables, e.g.:

```
pluginManagement {
    def isCI = System.getenv().containsKey("CI") // <-- first occurence
    def forcePublic = System.getenv().containsKey("USE_PUBLIC")
    def useLocal = isCI && !forcePublic

    repositories {
        maven {
            if (useLocal){
                url 'https://192.168.x.x/nexus/content/repositories/gradle-plugins/'
            } else {
                url 'https://nexus.example.org/nexus/content/repositories/gradle-plugins/'
            }
        }
    }
}

// another block
def isCI = System.getenv().containsKey("CI") // <-- here I have to duplicate the variable
if (isCI){
}

```

### Context
My use case is to hack on network setup not under my control (no dns, NAT etc.)

**Comment by oehme** [comment]
The pluginManagement block needs to be compiled and executed before the script can be compiled. Thus it cannot be preceeded by other statements. The same is true for the buildscript and plugins block.
