### ISSUE TITLE
Document version constraints

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3977]
This includes documenting use cases for: _prefer_, strictly, _reject_, _rejectAll_ (strict, incompatibility, ...). Since they are all version constraints, it might make sense to document these in one go.

As a base we can take docs and examples from https://github.com/gradle/dependency-management-samples - move them to `docs` and refine them.

Add something to the release notes.

**Comment by jjohannes** [comment]
Add this to the "Managing transitive dependencies"  section of the [restructured documentation](https://docs.google.com/document/d/1op4_f_TC3ESJO7xvtvu0mrLpucTMJD8uVINqZMHVfdI).

Consider replacing the "Enforcing specific dependency versions" section (about `force`) and change the existing use case  to address it with `strictly`.

**Comment by ljacomet** [comment]
In addition of the version documentation, more details should be added to #7926 documentation in order to explain _what_ gets replaced when using resolved version for publishing.

**Comment by ljacomet** [comment]
Rich version definition has been documented for Gradle 5.2. Keeping this open a bit longer to double check all the suggested changes have been taken into account.

**Comment by ljacomet** [comment]
Given all the upcoming documentation work around Gradle metadata and a potential rework of dependency management related content, closing this one.
