### ISSUE TITLE
Ignore outdated versions of module metadata <1.0

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3979]
For module metadata version <1.0 we do not give any compatibility guarantees. So if we increase the version number, older versions should just be discarded. In the case of java libraries, the pom/ivy metadata should then be used instead.

For example, if we would increase the version now from `0.3` to `0.4`, version `0.3` (and lower) should just be discarded instead of failing [here](https://github.com/gradle/gradle/blob/5125ca11ee4f507f5db310f42b413d7858ba28a1/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/ModuleMetadataParser.java#L80).

**Comment by ljacomet** [comment]
This behavior has changed, Gradle will always try to parse the Gradle Module Metadata and check the version only if it fails to do so. This was done to improve support for compatibility.
