### ISSUE TITLE
Intellij shows warnings on tasks.withType(JavaCompile)

### ISSUE THREAD

**Issue by Eng-Fouad** [gradle/gradle#3992]
IntelliJ shows the following warnings when using `tasks.withType(JavaCompile)`:

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

> 'withType' in 'org.gradle.api.DomainObjectCollection<T>' cannot be applied to '(java.lang.Class<org.gradle.api.tasks.compile.JavaCompile>, groovy.lang.Closure<java.lang.String>)' less... (Ctrl+F1) 
This inspection reports assignments with incompatible types

![Warning](https://i.imgur.com/vgWl1cc.png)

I am using Gradle 4.4.

**Comment by oehme** [comment]
This is an issue in IntelliJ and can't be fixed on our side. IntelliJ should properly handle the fact that any method that accepts an Action in Gradle will also accept a Closure.
