### ISSUE TITLE
Weird behavior of exclude patterns (simply don't exclude)

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#3994]
### Expected Behavior
`exclude` should work on the absolute path, or at least include the part of the relative path that was specified as source, or maybe relative to project root?
**See also code block `println`s, that explains it more.**

### Current Behavior
`exclude` on path that's part of the tree doesn't work.

### Context
I'm configuring `checkstyle` plugin for Android variants, and the variants contain a set of folders which I have no control over (src/main/java, src/debug/java, etc. + generated code paths as absolute paths). Dropping it in `SourceTask.source` and `include/exclude` on it should work to filter out some generated code, or so I thought.
**Important**: `files(...).asFileTree` and `src.matching(patternSet)` is part of `SourceTask.getSource()` which I cannot change, the only API I have is `source`/`include`/`exclude`.

### Steps to Reproduce (for bugs)
Drop this in a `build.gradle` and `gradle` (no need for params). I used Groovy IIFE `({ -> ...}.call())` to make the local variables scoped and the blocks look similar.

```gradle
create(file('src/main/java/com/example/Foo.java'))
create(file('src/main/java/com/example/more/Bar.java'))
create(file('src/gen/java/com/example/R.java'))
create(file('src/gen/java/com/example/more/R.java'))
create(file('src/main/java/com/example/keep/R.java'))

def create(file) {
	file.parentFile.mkdirs()
	file << file.absolutePath
}

({ ->
	println "works as expected"
	PatternSet patternSet = new PatternSet();
	FileTree src = files('src').asFileTree;
	patternSet.exclude("**/gen/**/R.java");
	println src.matching(patternSet).files.join('\n');
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\Foo.java
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\keep\R.java
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\more\Bar.java
}.call())
println ""
({ ->
	println "same exclude different sources doesn't work; neither do variants of it"
	PatternSet patternSet = new PatternSet();
	FileTree src = files('src/main', 'src/gen').asFileTree;
	patternSet.exclude("**/gen/**/R.java");
	patternSet.exclude("/gen/**/R.java");
	patternSet.exclude("gen/**/R.java");
	println src.matching(patternSet).files.join('\n');
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\Foo.java
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\keep\R.java
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\more\Bar.java
//!extra P:\projects\bugs\gradle-pattern\src\gen\java\com\example\more\R.java
//!extra P:\projects\bugs\gradle-pattern\src\gen\java\com\example\R.java
}.call());
println ""
({ ->
	println "this obviusly works, but it also excludes **/keep/R.java"
	PatternSet patternSet = new PatternSet();
	FileTree src = files('src/main', 'src/gen').asFileTree;
	patternSet.exclude("**/R.java");
	println src.matching(patternSet).files.join('\n');
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\Foo.java
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\more\Bar.java
//!missing P:\projects\bugs\gradle-pattern\src\main\java\com\example\keep\R.java
}.call());
```
### Your Environment
```
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64
```

**Comment by TWiStErRob** [comment]
Note: I found no documentation yet about this behavior, neither seen an exception/warning message. An RTFM response to this issue is acceptable to me, if I can achieve what I'm doing within reason.

**Comment by blindpirate** [comment]
Well, I think that's kind of expected behavior: all patterns are matching relative path. Let's take a look at your second case: `src/main` and `src/gen` excluding `**/gen/**/R.java`: `**/gen/**/R.java` matches all files whose **relative path** to `src/gen` contains `gen`, which means, `src/gen/java/com/example/R.java`'s relative path (to `src/gen`) is `java/com/example/R.java` thus doesn't match `**/gen/**/R.java`.

**Comment by TWiStErRob** [comment]
@blindpirate Kind of expected, now I see, but at the same time how would one achieve what I was intending to do? Remember I have no control over the input directories' format, only the source/include/exclude.

After some thought and making assumptions about the directory structure (no external source folders!) I can do this:

```groovy
//inputs: Checkstyle task, Android variant

def buildPath = task.project.buildDir.toPath()
def projectPath = task.project.projectDir.toPath()
def relativeBuildPath = projectPath.relativize(buildPath)
// start with the whole project
task.source projectPath
// include whatever needs to be included
task.include variant.getSourceFolders(SourceKind.JAVA).collect {
	projectPath.relativize(it.dir.toPath()).toString() + File.separator
}
task.exclude "${relativeBuildPath}/${FD_GENERATED}/source/*/${variant.name}/**/*.java"
```

The problem I see with this is performance, for example if there's a folder that is not in the includes list, it still needs to be processed, this may be particularly bad if, for example a Gradle subproject has a lot of subprojects, in that case each subproject's sources will be included in `task.source projectPath` and only then later filtered. If I run the above code for each subproject I get N^2 runtime (even assuming file scan is a linear operation). This is just speculation, didn't test it yet.

Also "no external source folders", that is a big one to make. I guess I could detect that via `.startsWith("..")` and `task.source` those folders as well, but you can see how it's getting out of hand compared to the original simple code:
```groovy
def relativeBuildPath = task.project.projectDir.toPath().relativize(task.project.buildDir.toPath())
task.source variant.getSourceFolders(SourceKind.JAVA)
task.exclude "${relativeBuildPath}/${FD_GENERATED}/source/*/${variant.name}/**/*.java"
```

What do you think? Is there something that would make it simpler? Or some way to do matches on absolute paths in `exclude`?

**Comment by blindpirate** [comment]
Honestly I don't know what's your intention, sorry. If I understand you correctly, you want two sets of source:

- all source under `src/main`
- all source under `src/gen` excluding all `R.java` files.

You can have two `FileTree`s and add them to `SourceTask.setSource()` instead of `SourceTask.source()` (in other words, NO `PatternSet` at all):

```
FileTree genSrc = fileTree('src/gen').matching { exclude '**/R.java' }
yourTask.setSource(mainSrc+genSrc)
```

Here's my test script:

```

create(file('src/main/java/com/example/Foo.java'))
create(file('src/main/java/com/example/more/Bar.java'))
create(file('src/gen/java/com/example/R.java'))
create(file('src/gen/java/com/example/more/R.java'))
create(file('src/main/java/com/example/keep/R.java'))

def create(file) {
        file.parentFile.mkdirs()
        file << file.absolutePath
}

({ ->
        FileTree genSrc = fileTree('src/gen').matching { exclude '**/R.java' }
        FileTree mainSrc = fileTree('src/main')
        FileTree result = genSrc + mainSrc
        result.each { println(it) }
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\Foo.java
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\keep\R.java
//P:\projects\bugs\gradle-pattern\src\main\java\com\example\more\Bar.java
}.call());
```

**Comment by blindpirate** [comment]
BTW you might want to see https://docs.gradle.org/current/userguide/working_with_files.html

**Comment by TWiStErRob** [comment]
I don't have control over what's coming to me so I can't split the excludes per folder like you did. The problem is that my input is [`src/gen', 'src/main'] without any knowledge of order or contents, it could be `['src/gen/a', 'src/gen/b', 'src/main']` for all I know.

I guess I'll try to pre-filter the folders; also give that doc a read, I skimmed it a few times, but never actually fully read it (usually these docs cover the very basics, but not advanced cases).

Thank you for your time!

**Comment by blindpirate** [comment]
I'm a bit confused, can you run `new File('src').listFiles()` if you can't control the contents? 

After all, you could use

```
yourTask.source { 
// a closure to implement whatever you want
}
```

**Comment by TWiStErRob** [comment]
`variant.getSourceFolders(SourceKind.JAVA)` gives me that array, but what it returns depends on how the Gradle Android project is set up (e.g. multiple source folders per source set).

`.source {}` could be a good one, thanks.
