### ISSUE TITLE
Discuss the implication of modeling specific `Property` and `Provider` types

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#4019]
With the `Provider`/`Property` API, we modeled some specialized types: `ListProperty`, `SetProperty`, `RegularFileProperty` and `DirectoryProperty`. We also have internal API that should be public at some point: `LockableProperty`, `LockableListProperty` and `LockableSetProperty`. The question regarding if we are creating too many dimensions that we will have to support in the future. This issue is to discuss the design on how we can find a middle ground between modeling and maintainability.

### Expected Behavior
Identify a way forward that doesn't compromise modeling and maintainability around `Provider`/`Property` APIs.

### Current Behavior
We are moving toward, what could be, a modeling explosion with specialized types that may cause trouble in the near feature.

**Comment by ldaley** [comment]
I think a good goal would be to not complect the value and mechanics such as `DirectoryProperty` does. `Property` would provide purely the mechanics and be effectively monadic. At the very least, this will come at the cost of syntactic sugar (i.e. you need to unpeel the provider layer to get value for anything). It would solve the explosion problem though.

It's also worth considering that Kotlin can extend parameterized type specialisations. For example, methods can be added to `Property<Directory>` via extension. This would restore some of the sugar for Kotlin users. FWIW, I'm not sure that's the right thing to do though.

**Comment by eskatos** [comment]
👍 to what Luke said about segregating responsibilities.

We should also keep in mind that Kotlin can't override the assignment operator. The syntactic sugar required to unpeel the provider will remain necessary, just like it is with the current api.

**Comment by ldaley** [comment]
@eskatos given this on Directory:

```
Directory dir(String var1);
```

Would it not be possible to extend `Property<Directory>` with …

```
Provider<Directory> dir(String var1);
```

?

**Comment by eskatos** [comment]
@ldaley yes, that should be possible

```kotlin
fun Provider<Directory>.dir(path: String): Provider<Directory> { get().dir(path) }
```

So that when you have some `Property<Directory>` say named `outputDir`, which is set, you could write something like:

```kotlin
val anotherDirProvider = outputDir.dir("some/path")
```

What I meant above is that we can't overload the `=` operator to make simple assignments look nice.

For example with the current api you must write:

```kotlin
outputDir = file("some/path")
```

instead of:

```kotlin
outputDir.set(file("some/path"))
```

Which brings another issue. For simple assignments, we'd want extensions like:

```kotlin
fun Property<Directory>.set(file: File): Unit { ... }
```

to mimic the actual `DirectoryProperty#set(File)` function.

But what would be the body of such a `Property<Directory>` extension?
It can't invoke `Property#get()` with its current contract which is to throw if unset.
It could invoke `Property#set(Directory)` instead, but then it needs to create an instance of `Directory`, how?

**Comment by ldaley** [comment]
We are never going to be able to really support simple assignments. We have already given up on that elsewhere.

I don’t think mixing Property with factories is a good idea either. But if we had to solve that, our only option that I can see would accessing the factory from thread global state.

**Comment by eskatos** [comment]
Right, factories are the third player: `Provider/Property`, the actual "property type" and its factories.

We do already have some decoration in the Groovy DSL that allows simple assignments. But yes, we given up on that for the Kotlin DSL, for now.

**Comment by eskatos** [comment]
As a general comment and at the risk of stating the obvious, I think that the solution we end up choosing must be usable 100% with the Java API, even if it requires ceremony, meaning we can create DSL syntaxes in both Groovy with e.g. decorations and Kotlin with e.g. extensions.

We should also keep in mind that with Gradle 5 requiring Java 8, we'll be able to use default methods on interfaces in the Java API. They could prove to be handy.

From a quick look at our existing property types, I think simple Kotlin extensions can be used for all functions they have including on the multi-valued ones, currently `ListProperty` and `SetProperty`, with extensions functions for all methods of `HasMultipleValues` on `Property<MutableList<T>>` & its set counterpart.

```kotlin
// Extensions for single valued property
fun Provider<Directory>.dir(path: String): Provider<Directory> = map { it.dir(path) }
val Provider<Directory>.asFile get() = get().asFile

// Usage sample
val someDir = project.layout.buildDirectory.dir("foo") // Property<Directory>
project.layout.buildDirectory.set(file("other-build"))

require(someDir.asFile.absolutePath.endsWith("other-build/foo"))
```

```kotlin
// Extensions for multi valued property
fun <T> Property<MutableList<T>>.set(iterable: Iterable<T>) { set(iterable.toMutableList()) }
fun <T> Property<MutableList<T>>.add(element: T) { get().add(element) }

// Usage example
val someList = project.objects.listProperty<String>() // Property<MutableList<String>>
someList.set(listOf("foo", "bar"))
someList.add("bazar")

require(someList == listOf("foo", "bar", "bazar"))
```

I assume that the Groovy DSL can provide similar syntax via decoration.

**Comment by bamboo** [comment]
These Kotlin extensions could be nice as well:

```kotlin
val <T> Provider<T>.value: T
    get() = get()

var <T> Property<T>.value: T
    get() = get()
    set(value) = set(value)
```
