### ISSUE TITLE
dependency resolution fails for .aar on repository requiring authentication

### ISSUE THREAD

**Issue by time4tea** [gradle/gradle#4028]
This is related to building an android project but i don't believe the problem is android specific.

For a .aar file getMetaData() issues a Head request rather than usual Get. 

When challenged with 401 Authenticate, it should retry the request sending relevant credentials, however it does not, so the dependency resolution fails.

Other .jar files on the same repository are successfully retrieved, as the request is correctly retried with credentials.

The above was determined using charles proxy as MiTM.

### Your Environment

Android project building in environment disconnected from the internet, using nexus repository that requires http basic authentication, over https.

Thanks!

**Comment by time4tea** [comment]
Sorry forgot version.. all recent versions, including 4.4.1.

**Comment by jjohannes** [comment]
@time4tea thanks for reporting. Can you be more specific on _all recent versions_? Could you check if this works for you with older versions of Gradle? It would be very helpful to know if this a regression and, if it is, in which version it was introduced.

**Comment by time4tea** [comment]
I didn't check every single version but i looked as far back as 2.12.

Cheers! James




On 15 Jan 2018 08:13, "Jendrik Johannes" <notifications@github.com> wrote:

@time4tea <https://github.com/time4tea> thanks for reporting. Can you be
more specific on *all recent versions*? Could you check if this works for
you with older versions of Gradle? It would be very helpful to know if this
a regression and, if it is, in which version it was introduced.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gradle/gradle/issues/4028#issuecomment-357609978>, or mute
the thread

**Comment by bmuschko** [comment]
Would you mind putting together a little sample project that demonstrates the issue?

**Comment by jjohannes** [comment]
Closing this until we have a reproducible example.
