### ISSUE TITLE
Getting error (don't exactly know what it means)

### ISSUE THREAD

**Issue by MTMasterGaming** [gradle/gradle#4032]
### Expected Behavior

So I am new to gradle and I am just trying to compile something, but I have had so many issues, and I just don't know what any of this means, even after I have tried googling it. Basically I am expecting this to work, and setup and download everything, but I am getting an error when I do gradlew setupDecompWorkspace, or any gradlew command in fact.
### Current Behavior

This is the message I get: 
`Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)`
### Context

As I said, I was trying to compile something, specifically [this](https://github.com/PeregrineZ/youtube-chat-for-minecraft), but I get this error. Don't think it has anything to do with what I am trying to compile because even when doing gradlew --version I still get the same error.
### Steps to Reproduce (for bugs)

Again, any gradlew command produces this error for me. I just updated to version 4.4.1 and JDK 9.0.1, so I am on the latest of everything I can think of. 
### Your Environment

 * Build scan URL: https://gradle.com/s/s2mgtbojxmxz4
So I am not sure if this has anything to do with the gradlew messages I am getting, but here it is. Again, I really don't know much about this, I am just following instructions. Please let me know if you can find out what is wrong.

**Comment by blindpirate** [comment]
According to the error log:

> C:\Users\MTMaster\.gradle\caches\minecraft\net\minecraftforge\forge\1.8.9-11.15.1.2318-1.8.9\userdev\dev.json could not be parsed

I think this issue is related to the project (and perhaps MDK?) you're trying to compile and there's nothing we can do on Gradle's side. I suggest you to ask in the repository you're referring to.

P.S I can run `./gradlew --version` and `./gradlew build` with the repository without any error. (JDK8).
