### ISSUE TITLE
Document Gradle module metadata

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#4049]
- valid values for public attributes - org.gradle.usage and org.gradle.status
- ...

**Comment by trevjonez** [comment]
should this task also include documentation about the conversion from the software components / usage types through to the generation of a .module file? Or is it intended to be only the specifics about the formatting/semantics of the .module file and properties? [(such as this document)](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-specification.md)

**Comment by jjohannes** [comment]
We should consider adding a description of Java ecosystem attributes from #9675 to the spec.

**Comment by jjohannes** [comment]
Attribute values are already documented in the spec (#10230): https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md#standard-attributes
