### ISSUE TITLE
DomainObjectCollection#withType type parameter should be less restrictive

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#4050]
### Current Behavior

[DomainObjectCollection.java](https://github.com/gradle/gradle/blob/b0032a8a355379e5868b22d660f8be5cf857168e/subprojects/core-api/src/main/java/org/gradle/api/DomainObjectCollection.java#L34)
```java
public interface DomainObjectCollection<T> extends Collection<T> {
  <S extends T> DomainObjectCollection<S> withType(Class<S> type);
  <S extends T> DomainObjectCollection<S> withType(Class<S> type, Action<? super S> configureAction);
  <S extends T> DomainObjectCollection<S> withType(Class<S> type, Closure configureClosure);
}
```

`<S extends T>` prevents from querying the collection by a type shared by actual elements of the collection that is out of the type hierarchy of `T`.

For example, using the `tasks` container, one could want to configure all tasks of type `VerificationTask` (the following also applies to e.g. `JavaForkOptions` or `ProcessForkOptions` from the Gradle API). 

In Groovy the IDE shows a warning but this just works:

```groovy
tasks.withType(VerificationTask) {
   ignoreFailures = true
}
```

Given the above method signatures, trying to do the same in Java is not possible:
```java
getProject().getTasks().withType(VerificationTask.class, new Action<VerificationTask>() {
    @Override
    public void execute(VerificationTask task) {
        task.setIgnoreFailures(true);
    }
});

// error: no suitable method found for withType(Class<VerificationTask>,<anonymous Action<VerificationTask>>)
```

nor with the Kotlin DSL:
```kotlin
tasks.withType<VerificationTask> {
    isIgnoreFailures = true
}

// Type argument is not within its bounds: should be subtype of 'Task!'
```

### Expected Behavior

The last two `java` and `kotlin` snippets above work.

### Context

Reported against the Kotlin DSL in https://github.com/gradle/kotlin-dsl/issues/575

### Workaround

Casting

```kotlin
// in kotlin
tasks.all {
    if (this is VerificationTask) { // smart cast
        ignoreFailures = true
    }
}
```

```java
// in java
getProject().getTasks().all(new Action<Task>() {
    @Override
    public void execute(Task task) {
        if (task instanceof VerificationTask) {
            ((VerificationTask) task).setIgnoreFailures(true);
        }
    }
});
```

**Comment by JLLeitschuh** [comment]
Trying to take a crack at this problem, this seems like this would require quite a few changes to public interfaces that are public. This might be an unsolvable problem without having it be an API breaking change.

**Comment by JLLeitschuh** [comment]
There is far too much filtering code that assumes that `<S extends T>`. Breaking that fundamental assumption creates compiler errors everywhere.

**Comment by JLLeitschuh** [comment]
Digging into this problem a bit, I think that the easier solution might just be adding an additional set of API's to the `DomainObjectCollection`.

Unfortunately, I can't put multiple type bounds on the `withTypeWeak` methods.

Something like:
```java
interface DomainObjectCollection<T> extends Collection<T> {
    <S extends T> DomainObjectCollection<S> withType(Class<S> type);
    <S extends T> DomainObjectCollection<S> withType(Class<S> type, Action<? super S> configureAction);

    /**
     * Filters out the elements of the {@link DomainObjectCollection} that match type `S`.
     */
    <S> DomainObjectCollection<T> filterType(Class<S> type);

    <S> DomainObjectCollection<S> withTypeWeak(Class<S> type);
    <S> DomainObjectCollection<S> withTypeWeak(Class<S> type, Action<? super S> configureAction);
}
```
