### ISSUE TITLE
Project dependencies failing to resolve correctly in v4+ works in 3.5

### ISSUE THREAD

**Issue by domcc** [gradle/gradle#4053]
### Expected Behavior
We have a multi project gradle build setup. We can add additional projects into the multi project setup by cloning a repo into the multi project setup.
mymultiproject
--- submultiproject
----- subProj1 
----- subProj2 (Has compile project reference to ":submultiproject:subProj1")
----- subProj3 (Has compile project reference to ":submultiproject:subProj1" and ":submultiproject:subProj2")

We could then clone Project1 into mymultiproject to get
mymultiproject
---project1 (Has compile project reference to ":submultiproject:subProj1") and ":submultiproject:subProj2") and ":submultiproject:subProj3")
--- submultiproject
----- subProj1
----- subProj2
----- subProj3

When we do this gradle can no longer resolve the project references that subProj2 and subProj3 have to subProj1 and subProj2 and the build fails. Actually to be more precise gradle does appear to resolve the reference however it is looking for submultiproject/subProj1/builds/libs/subProj1.jar. Not such jar exists because the actual jar has a version subProj1-1.2.3.jar
This works in gradle 3.5 and fails in gradle 4.0 onwards.
As it stands this means we can not use gradle 4+

### Steps to Reproduce (for bugs)
I have been unable to reproduce this with a cut down project. However by running the build with --debug i have observed the following:
1. I see 
`17:29:01.757 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 1.8 -target 1.8 -d C:\Temp\mymultiproject\submultiproject\subProj2\build\classes\java\main -encoding UTF-8 -g -sourcepath  -processorpath  -XDuseUnsharedTable=true -classpath ;C:\Temp\mymultiproject\submultiproject\subProj1\build\libs\subProj1.jar -processorpath  ...`
You can see that it is attempting to resolve subProj1.jar. When i run the same build using gradle 3.5 i see the following:
`17:19:22.558 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 1.8 -target 1.8 -d C:\Temp\mymultiproject\submultiproject\subProj2\build\classes\main -encoding UTF-8 -g -sourcepath  -processorpath  -XDuseUnsharedTable=true -classpath C:\Temp\mymultiproject\submultiproject\subProj1\build\libs\subProj1-1.2.3.jar -processorpath  ...`
You can see that it is correctly using the subProj1 jar with the version information (which exists)

### Other observations
When i import the above project into Intellij using gradle 4+ i see the following in the gradle side bar:
->:submultiproject:subProj2
--->Source Sets
------>main
--------v Dependencies
---------->subProj1:main(Compile)
                 submultiproject/subProj1/builds/libs/subProj1.jav (Compile)

When i import into Intellij using gradle 3.5 i see the following:
->:submultiproject:subProj2
--->Source Sets
------>main
--------v Dependencies
---------->subProj1:main(Compile)

Notice that with 3.5 the node "                 submultiproject/subProj1/builds/libs/subProj1.jav (Compile)" is not present when it is using gradle 4+.

I have tried this with 4.5-RC1 and i have the same problem.

### Your Environment
Build scan url is returning not found https://gradle.com/scans/get-started
This is running on Windows 7 x64 using JDK1.8.0_151
Just to repeat this works in gradle 3.5 and lower but does not work in gradle 4+

**Comment by big-guy** [comment]
@domcc Thanks for noticing the broken link.  I've fixed it.  Could you try creating a build scan with Gradle 3.5 and Gradle 4.5-rc-1 and sharing it?

Could you share any of your configuration for subProj1 and subProj2?

**Comment by domcc** [comment]
I have managed to reproduce the problem in a cut down project. I will post the demo application as soon as i can. I now know the cause so will try and cut it down further.
Basically in the example i posted above. It project1 has defined a task like shown below then it causes the failure i have reported:
```
def myLocation = file("test/resources/something")
task doSomethingWierd(type: Copy) {
        from configurations.testCompile.filter { it.name.startsWith('something-data') }.collect { zipTree(it) }
        into myLocation
        include "test/resources/*.csv"
        include "test/resources/samples/*.csv"
}
```
It looks like this causes the project1/build.gradle file to be run at which point it does not have valid version information. This can be corrected by changing the task above to
```
def myLocation = file("test/resources/something")
task doSomethingWierd(type: Copy) {
    doLast {
        from configurations.testCompile.filter { it.name.startsWith('something-data') }.collect { zipTree(it) }
        into myLocation
        include "test/resources/*.csv"
        include "test/resources/samples/*.csv"
    }
}
```
Still it will be interesting to know why this worked in 3.5 and not 4+

**Comment by bmuschko** [comment]
You are iterating over the configuration `testCompile` during Gradle's configuration phase. That in turn means that the configuration needs to be resolved. I am a bit unsure why it would cause an exception. I'd try to evaluate the filtered list dependencies to a later time by passing a `Closure` to the `from` method.

```
task doSomethingWierd(type: Copy) {
    from { configurations.testCompile.filter { it.name.startsWith('something-data') }.collect { zipTree(it) } }
    ...
}
```

**Comment by domcc** [comment]
@bmuschko should the entire task be put in a doLast {} block or would that be incorrect?

**Comment by bmuschko** [comment]
@domcc None of the method calls should need to go into an action. You are effectively deferring the execution with the `Closure` if you are using it to call the `from` method.

**Comment by domcc** [comment]
I have uploaded same project showing the problem between gradle 3.5 and gradle. 4.0. 
[multiprojproblem.zip](https://github.com/gradle/gradle/files/1641435/multiprojproblem.zip)

I have resolved the issue as suggested above so its more a curiosity as to why it works in 3.5 vs 4+.

**Comment by oehme** [comment]
Remember to specify `testCompile` as an input to your task, Gradle doesn't know you're using it in the closure.

```
task doSomethingWierd(type: Copy) {
    inputs.files configurations.testCompile
    from { configurations.testCompile.filter { it.name.startsWith('something-data') }.collect { zipTree(it) } }
    ...
}
```

What you had before might have worked by accident before, but was definitely not supported.

**Comment by domcc** [comment]
Thanks for your help. @oshme What would be the inmpact of not adding the line
`inputs.files configurations.testCompile` ?
Would it just result in the task running for other configurations?

**Comment by oehme** [comment]
No, it would mean your task doesn't notice changes to the configuration, so it wouldn't run at all.
