### ISSUE TITLE
How to access cache key for any gradle task?

### ISSUE THREAD

**Issue by devishree90** [gradle/gradle#4056]
I'm working on gradle based play project and really interested in building something for metrics around cache misses/hits over any specific gradle task.

Does gradle provide any api to access cache key for Task objects?

**Context**
Currently, I can't establish association of cache keys & tasks. I'm trying to build something for metrics around cache misses/hits for any specific gradle task

**Comment by blindpirate** [comment]
I'm afraid there's no explicit API to fulfill your demand. However, you can get some of these information from the log, e.g. `UP-TO-DATE`/`NO-SOURCE`. If you run Gradle with `--info`/`--debug` you can get even more information about cache miss/hit and why they're missed (which property of the task is out-of-date). Please let me know if I didn't make myself clear.

**Comment by big-guy** [comment]
It's not directly the same thing, but you can [export data](https://docs.gradle.com/enterprise/export-api/) out of build scans and visualize it the way you want.  This is what Sam talks about in this Gradle Summit talk:
https://www.youtube.com/watch?v=jXJvX0F5hTs
