### ISSUE TITLE
How to access cache keys of gradle tasks?

### ISSUE THREAD

**Issue by devishree90** [gradle/gradle#4061]
I'm working on gradle based play project and really interested in building something for metrics around cache misses/hits over any specific gradle task.

Does gradle provide any api to access cache key for Task objects?

**Comment by bmuschko** [comment]
There's not a public API to retrieve that information. I am assuming you mean the build cache? You might want to look into [Gradle Enterprise](https://gradle.com/build-cache) that supports metrics in that regard.

I am going to close this issue. It's better suited as a question on the [Gradle forum](https://discuss.gradle.org/).

**Comment by rhart** [comment]
@devishree90 this information is available per build in both [Community](https://scans.gradle.com/get-started) and [Gradle Enterprise](https://gradle.com/build-scans) build scans.  See https://scans.gradle.com/s/h2ily574bqb4g/performance/buildCache and https://gradle.com/enterprise/releases/2017.5#analyze-and-optimize-build-cache-performance

If you want metrics across all builds, then Gradle Enterprise has an Export API function that would allow you to do this https://docs.gradle.com/enterprise/export-api/

**Comment by devishree90** [comment]
Thank you @rhart & @bmuschko
