### ISSUE TITLE
project.delete deletes in symlinkd directories on Windows 10

### ISSUE THREAD

**Issue by mjoberg** [gradle/gradle#4065]
If using Cygwin with the environment variable CYGWIN set to “winsymlinks:nativestrict”, symlinks start to work like on Linux. A guess is that this started to work without being priviliged in the version “Creator’s Update”, arriving in September 2017.

Now, deleting a directory with project.delete (where followSymlinks is false by default) on Windows Version 10.0.16299.125, may not work correctly.

- if the directory to be deleted contains a symlink to a directory, the directory’s contents (but not the directory) are wiped out prior deleting the symlink itself (SYMLINKD).

project.delete treats symlinks differently comparing Ubuntu to Windows 10 Fall Edition.

### Expected Behavior

If the directory to be deleted contains a **symlink to a file**, the action is correct. The symlink is deleted but the file linked to is kept (SYMLINK). The behaviour is correct.

If the directory to be deleted contains a **symlink to a directory**, the symlinkd only should be deleted. Works on Ubuntu.

### Current Behavior

If the directory to be deleted contains a symlink to a directory, the directory’s contents (but not the directory) are wiped out prior deleting the symlink itself (SYMLINKD). Applies to Gradle versions 3.1 and 4.4.1, at least.
### Context

Files that weren't expected to be deleted get deleted. We're trying to delete a part of a project tree that has symlinks to directories and files.

### Steps to Reproduce (for bugs)

See [https://discuss.gradle.org/t/project-delete-and-windows-10-fall-edition/25251](url)
### Your Environment

 * Build scan URL: https://gradle.com/s/7ub2jipzw2v6e

**Comment by lacasseio** [comment]
This should be fixed in 5.3, RC will be coming out soon. Reopen if the RC doesn't fix the issue.
