### ISSUE TITLE
Restore the vertical whitespace before each task header in the rich console

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#4071]
The vertical whitespacing makes it easy to scan the output and quickly comprehend the output as several useful chunks. Removing the vertical whitespace leaves behind an un-parsable wall of text with some undifferentiatable bold chunks embedded in it.

### Expected Behavior

The rich console should make very clear to the user which task or operation a logging output belongs to. One effective way to achieve this is to use vertical whitespace between the output of each task.

### Current Behavior

It's a mess. The text is way too dense to parse effectively, and the bold embedded in the text is distracting.

**Comment by oehme** [comment]
I think this is an unintended side-effect of this well-meaning PR https://github.com/gradle/gradle/issues/3325.

We should probably back this out for 4.5

**Comment by adammurdoch** [comment]
It was pretty clear from the change to the functional test in that PR that this would happen. We shouldn't just change functional tests that happen to break without understanding the intent of the test and the impact of the change.

**Comment by eriwen** [comment]
This is addressed by 5bfa724 which, and I hope you'll agree, is a good compromise.
