### ISSUE TITLE
There should not be any difference in behavior when addressing tasks by type or name

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#4073]
Difference in behavior between:

```groovy
tasks.withType(SomeTask) {
  enabled = false
}
```

and

```groovy
someTaskName.enabled = false
```

### Expected Behavior
Addressing a task by type or name and setting the `enabled` flag has the same behavior.

### Current Behavior
Addressing a task by type and setting the `enabled` flag doesn't work.
Addressing a task by name and setting the `enabled` flag works.

### Context
This was reported against `gradle/kotlin-dsl` first but it applies to both Groovy and Kotlin DSL.
https://github.com/gradle/kotlin-dsl/issues/488

According to the report this started with Gradle 4.2-rc-1

The reproducer projects all use the Spring Boot plugin.

### Steps to Reproduce (for bugs)
Here is a reproducer that is smaller than the one provided in the original report: https://github.com/eskatos/gradle-issue-4073

- by type: https://scans.gradle.com/s/x4grdmp7d4toq/timeline?task=d3uk6pp6xfn76
- by name: https://scans.gradle.com/s/3rueolqjiom6w/timeline?task=d3uk6pp6xfn76

**Comment by oehme** [comment]
`BootJar` extends `Jar`, so the second `withType` statement reactivates it. This is just expected behavior.

**Comment by eskatos** [comment]
Right! Thanks Stefan!
