### ISSUE TITLE
Consider removing Groovy methods from the Gradle Java API

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#4075]
In particular `Closure` taking methods. They should use type safe signatures instead like `Action<T>`, `Spec<T>` etc..

The benefit to users is less information overload when asking for code completion, reading the docs, etc.. And make the Gradle API an example of what should be done in community plugins.

This will require a deprecation cycle.

**Comment by mkobit** [comment]
In the same vein, please consider (at some point) removing the `Object` accepting methods. To me it has proven to be a non-stop source of confusion for myself and others I have worked with:

 - [`project.file`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#file-java.lang.Object-) can take 8 different types
 - [`project.files`](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#files-java.lang.Object...-) can take 12 types
 - [`task.dependsOn` and task ordering](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#dependsOn-java.lang.Object...-) can take 9 types
 - [`CopyTask.from` (and similar types)](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/AbstractCopyTask.html#from-java.lang.Object...-)

With the introduction of `Provider` types as well for connecting inputs and outputs (and especially in multiproject builds), there is a very large API surface to learn in both usage and plugin development.

**Comment by wolfs** [comment]
@eskatos We already tried to deprecate `Closure` accepting methods: https://github.com/gradle/gradle/pull/677
This didn't turn out so well :(

Note that the methods accepting `Closure`s are re-added at runtime. This means that Groovy build script would get deprecation warnings whenever using one of the deprecated `Closure` taking methods on the public API, even though everything is perfectly fine.

**Comment by eskatos** [comment]
Right, the deprecation cycle should:
- allow Java API consumers (Java, Groovy, Kotlin binary plugins, Kotlin DSL scripts) to use the deprecated methods, getting deprecation warnings ;
- allow Groovy DSL consumers to use Groovy types, without deprecation warnings.

In other words, the Groovy DSL decorations should be changed/added to not delegate to the deprecated Java API methods but to their strongly/plain-java typed equivalents.

**Comment by wolfs** [comment]
@eskatos Yeah. We currently don't do any compile time decoration for Groovy, so the `Closure` taking methods just don't exist statically if they are not added to the Java API. We probably should provide static extensions for Groovy, too.
