### ISSUE TITLE
Properties are no longer (4.3+) evaluated in with ivy publications block post.

### ISSUE THREAD

**Issue by moserp** [gradle/gradle#4076]
### Expected Behavior
Properties used within fields/attributes in a publication block for Ivy publishing should be evaluated to their value 

### Current Behavior
From 4.3 onwards a property is not evaluated, you get the value "null".  In versions 4.2.1 and before you would get the value of the property as set in gradle.properties or the ext {} block

### Steps to Reproduce (for bugs)

```
apply plugin: "java"
apply plugin: 'ivy-publish'

ext {
    // or set in project gradle.properties file
    component = "foo"
}

repositories {
    ivy {
        name "snapshots"
        // repo details here...
    }
}

publishing {
    repositories {
        add project.repositories.snapshots
    }
    publications {
        ivy(IvyPublication) {
            organisation 'com.example'
            module "mymodule-${component}"
            revision "1.0"
            artifact name: "myartifact-${component}", source: "${component}.tar.gz", type: 'tar.gz', extension: 'tar.gz'
        }
    }
}
```

Before v4.3 Gradle would have evaluated module, artifact and source to mymodule-foo, myartifact-foo and foo.tar.gz, respectively from v4.3 they become mymodule-null, myarticat-null and null.tar.gz

I would rather not hardcode the module, artifact and source name in the build file so I can have 1 common build file across several projects and vary the values by having a different gradle.properties file per project.

### Your Environment
Ubuntu 16.04
java version "1.8.0_162"
Gradle versions tried: Expected behavior: 4.0, 4.1, 4.2.1. Current behavior: 4.3, 4.4.1, 4.5-rc-1

**Comment by blindpirate** [comment]
Could you use `${project.component}` as a workaround?

**Comment by blindpirate** [comment]
@moserp After some investigation, I found this is a coincidence. After `4.3` we introduced some internal property named `component` and it's searched before the outermost property `component` you defined: https://github.com/gradle/gradle/blob/f2e115c9dd1aecb51f3142ace786a1555cbcd0cc/subprojects/publish/src/main/java/org/gradle/api/publish/internal/PublicationInternal.java#L27

Sorry for the inconvenience, but you can rename that property to something else, e.g. `componentName`.

**Comment by moserp** [comment]
Using a different property name, eg componentName as suggested, resolves the issue for me.  Thanks.
