### ISSUE TITLE
Internal types should not leak through core plugins extensions

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#4079]
### Expected Behavior
No internal types are leaked through core plugins extensions.

### Current Behavior
Two extensions in Gradle built-in plugins expose internal Gradle types:

- `defaultArtifacts` has a public type of `org.gradle.api.internal.plugins.DefaultArtifactPublicationSet`
- `toolChains` has a public type of `org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal`

These internal types leak through the public `ExtensionContainer.getSchema()` method.

### Context
This was reported against `gradle/kotlin-dsl` in https://github.com/gradle/kotlin-dsl/issues/361.
In the context of the Kotlin DSL, the impact is that accessors available in build scripts then include `defaultArtifacts` and `toolChains`.
API documentation then references these Gradle internals that are explicitly excluded resulting in `<ERROR CLASS>` in the output.

See:
- the [defaultArtifacts](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin/org.gradle.api.-project/default-artifacts.html) accessor
- the [toolChains](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin/org.gradle.api.-project/tool-chains.html) accessor

**Comment by big-guy** [comment]
opened https://github.com/gradle/gradle-native/issues/499 for the native part of this.
