### ISSUE TITLE
Is there a way to apply a plugin directly from a sub-project or module without publishing?

### ISSUE THREAD

**Issue by shehabic-work** [gradle/gradle#4087]
### Expected Behavior

I would like to know if something like:
`classpath project(":project-or-module-name")` would be possible just like normal dependencies when referenced the same way.

### Current Behavior

Currently if you're developing a plugin, and assuming that you'll be applying the plugin in another module/project, you have to first comment out the code that applies the plugin, or point to an older version that's already published, then publish the new one then refer to it back.

### Context

I have a project with multiple modules/subprojects, I want one of the modules/subprojects to be a gradle-plugin and would like to apply this plugin in other modules/subprojects

### Your Environment

 * Build scan URL: 
I don't think it's relevant to this question/request but this is y env:
```
------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Mac OS X 10.13.2 x86_64
```

**Comment by bmuschko** [comment]
No, that's currently not possible. You'd put your plugin into `buildSrc` instead. You can find more information [here](https://docs.gradle.org/current/userguide/custom_plugins.html).

**Comment by big-guy** [comment]
You could also use [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) for this.  There's a sample using a composite build for plugin development: https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/compositeBuilds/plugin-dev

The idea is that the plugin is a separate build that's just included into the other build. You don't have to go through a local publish step or put everything into buildSrc.
