### ISSUE TITLE
Expose isFromCache() method in TaskState API

### ISSUE THREAD

**Issue by devishree90** [gradle/gradle#4093]
Currently, there is no way for user to identify programmatically if task used cache object or not. Gradle provides this information in logs but there is no public API. This PR exposes isFromCache() method as part of TaskState API making this info available to users.

**Use-case:**
I'm trying to build plugin,  which will provide information like what is impact on build time(broken down by tasks )when i use build-cache. I would like to know how individual task execution time is improved/impacted if i use build-cache. I would like to have this information available via API which i can use programmatically.

I'm able to get info about Task Execution(Task start time, Task end time) by implementing TaskExecutionListener. I'm not able to determine if task output was from cache or not programmatically. (Gradle logs have this info. Parsing logs is not possible option here).  

It will be really helpful to expose isFromCache() as part of TaskState API

**Comment by bmuschko** [comment]
I am trying to understand your use case. As outlines by this [blog post](https://blog.gradle.org/introducing-gradle-build-cache) task execution times will be significantly faster if you use the correct annotations. Most of the Gradle core built-in task are already equipped to support the build cache. Why don't you just give the build cache a shot?

Be aware that a build scan already provides you with the [performance information](https://guides.gradle.org/using-build-cache/#build_cache_performance). I don't think we'll want to expose the method as a public API at this time.

**Comment by devishree90** [comment]
@bmuschko - Thanks for the info. Build scans provides info on task performance for individual builds. 

 My use case is to build plugin, which will provide information like what is impact on build time(broken down by tasks )when i use build-cache. I want to collect information about individual builds and  build dashboard which will give me aggregate of build/task improvement over period of time(i.e Day,week, month,year) with build-cache.

**Comment by mockitoguy** [comment]
Hey @bmuschko! Thanks for considering! What's the problem with exposing the property?

We absolutely want to use Gradle Enterprise for many reasons, including much better understanding what's cacheable or not.

Our use case is that we don't want to depend on Gradle Enterprise (3rd party) as a middle man between builds and our big data infrastructure. All builds at LinkedIn send Kafka events with build information, we store them in big data to track trends. We would love to show a trend of how cache-ability impacts build times across all LinkedIn, over time. Currently we use the private API but we would rather not to. Please expose it :)

Thoughts?

**Comment by ldaley** [comment]
Hi @mockitoguy, 

The problem with exposing it is the compatibility burden. We want to improve and enrich the task feedback in ways that may go beyond the current model. Exposing the concept of "from cache" in public API restricts our ability to move here. Gradle Enterprise is irrelevant in this consideration.

I acknowledge that we have already exposed some aspects of the outcome via TaskState, and this is something that we regret and will work to change. We don't want to exacerbate the problem.

The best outcome for us would be for you to use `skipMessage`, or the private API.

**Comment by bmuschko** [comment]
I am going to close the issue and pull request for now. Please let us know if you have additional concerns.

**Comment by mockitoguy** [comment]
Thank you guys for considering! We respect the decision.
