### ISSUE TITLE
 Unable to resolve dependency for ':appname@qaDebug/compileClasspath': Failed to transform file 'design-26.0.2.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform Failed to transform file 'design-26.0.2.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

### ISSUE THREAD

**Issue by raazvengala** [gradle/gradle#4095]
Not able to build the project after update of gradle. 
Unable to resolve dependency for ':beats@qaDebug/compileClasspath': Failed to transform file 'design-26.0.2.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

Failed to transform file 'design-26.0.2.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
 > java.io.FileNotFoundException: C:\Users\username\.gradle\caches\transforms-1\files-1.1\design-26.0.2.aar\f5496a20bb7d2392cac2bf37b5ffd28c\res\drawable-xxhdpi-v4\design_ic_visibility_off.png (Access is denied)
    > C:\Users\username\.gradle\caches\transforms-1\files-1.1\design-26.0.2.aar\f5496a20bb7d2392cac2bf37b5ffd28c\res\drawable-xxhdpi-v4\design_ic_visibility_off.png (Access is denied)

Unable to resolve dependency for ':beats@qaDebug/compileClasspath': Failed to transform file 'android-image-cropper-2.5.0.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform

Failed to transform file 'android-image-cropper-2.5.0.aar' to match attributes {artifactType=android-exploded-aar} using transform ExtractAarTransform
 > java.io.FileNotFoundException: C:\Users\username\.gradle\caches\transforms-1\files-1.1\android-image-cropper-2.5.0.aar\a420fe7bd1a2c2349fc7c4dc91955b27\res\drawable-hdpi-v4\crop_image_menu_flip.png (Access is denied)
    > C:\Users\username\.gradle\caches\transforms-1\files-1.1\android-image-cropper-2.5.0.aar\a420fe7bd1a2c2349fc7c4dc91955b27\res\drawable-hdpi-v4\crop_image_menu_flip.png (Access is denied)
### Steps to Reproduce (for bugs)

Download the latest Android Studio
Import any project or create a new project.
Build the project and you will get issues in messages.

### Your Environment
Android Studio 3.0.1
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
classpath 'com.android.tools.build:gradle:3.0.1'
compilesdkversion 26
targetsdkversion 26

 * Build scan URL:

**Comment by blindpirate** [comment]
Thanks for reporting, could you retry with higher permission (e.g. Run as administrator)? Looks like there're some permission issues:

> Access is denied

**Comment by raazvengala** [comment]
I've installed as an administrator only. I think files are missing in c:/users/username/.gradle/transform/ ***.aar/somefilename***.**.  Please kindly check why the files are not creating in caches. This issue is coming from past 1 day due to some updation

**Comment by blindpirate** [comment]
Sorry, but could you give us more information? This issue looks like environment-specific:

- Your OS
- After which update this issue occurred? Android update or Gradle update? What's the previous version ( the version without this issue) ?
- Could you run with `--stacktrace` to get the whole stacktrace?

**Comment by raazvengala** [comment]
OS: window 7 -  64bit 
Build tools version '27.0.3'
Gradle plugin version 3.0.1
Android studio : 3.0.1
Java : Version 8 Update 161

**Comment by oehme** [comment]
The error message says that the Android plugin cannot extract an aar into the cache directory. Make sure it is not write protected. You can try using a different Gradle user home directory to be sure (using the `-g` command line option).

**Comment by bmuschko** [comment]
I am going to close this issue as we proposed a solution but haven't heard back. Feel free to reopen if you need further assistance.
