### ISSUE TITLE
project.configurations.getByName('compile') doesnot work

### ISSUE THREAD

**Issue by prathibhap-google** [gradle/gradle#4100]
I use project.configurations.getByName('compile') to list all dependencies in my android project. After Upgrading to gradle 4.1 and Android Plugin 3.0.1 project.configurations.getByName('compile') does not list all dependencies.

I understand that compile is deprecated and the alternative is api/implementation. But project.configurations.getByName('api') and project.configurations.getByName('implementation') does not work. I am not sure what is the best way to find all the dependencies that are declared in build.gradle file

**Comment by blindpirate** [comment]
Could you give us more information? A sample `build.gradle` would be good.

- From which version do you upgrade from?
- How do you use the `project.configurations.getByName('compile')`?

**Comment by oehme** [comment]
For general usage questions please use the Gradle forum. 

The correct configurations to resolve are either compileClasspath or runtimeClasspath, depending on what you are trying to do.
