### ISSUE TITLE
Multi-project gradle setup does not allow module's to configure different repository sources, leading to coupled projects.

### ISSUE THREAD

**Issue by atreat** [gradle/gradle#4106]
```
------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.12.6 x86_64
```

Steps to Reproduce:
1. Take two modules, 'app' and 'lib'
2. Have lib setup with 'google' repository and dependency of 'com.google.android.gms:play-services-location:11.4.2' in module's build.gradle
3. Attempt to build app with `gradle app:assembleDebug` without defining 'google' repository inside the app's build.gradle (or using an `allprojects` block in the root build.gradle)

This doesn't matter which repository you are defining or which dependency. Above I'm using a concrete example. There is nothing specific about the values used. I'm not using Android Studio when running this build. I'm using the gradle CLI and running the commands manually.No behavior changes if I'm using a gradle wrapper or not.

```
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.google.android.gms:play-services-location:11.4.2.
  Searched in the following locations:
      file:/Users/me/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-location/11.4.2/play-services-location-11.4.2.pom
      file:/Users/me/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-location/11.4.2/play-services-location-11.4.2.jar
      file:/Users/me/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.4.2/play-services-location-11.4.2.pom
      file:/Users/me/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.4.2/play-services-location-11.4.2.jar
      file:/Users/me/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.4.2/play-services-location-11.4.2.pom
      file:/Users/me/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.4.2/play-services-location-11.4.2.jar
  Required by:
      project :app > project :lib
```

I've attached a sample project that contains build files only. There is no source but there are defined AndroidManifest.xml files in each module as the android plugin requires this. I believe this is the smallest example I could build that still displays the issue.
[test-gradle.zip](https://github.com/gradle/gradle/files/1652305/test-gradle.zip)

I would expect that the lib module would be able to define repositories to pull its dependencies from. When the app is compiled using the lib project as a dependency, it should not need to redefine repositories used by transitive dependencies it gets from the lib module.

I have already opened an issue in [Google's Issue Tracker](https://issuetracker.google.com/issues/70815519) it was deemed 'Infeasible' as an issue with Gradle's handling of repositories.

**Comment by oehme** [comment]
This is working as intended. Projects should not leak repositories into other projects. If you have a repository that most/all of your projects need, defining it with an `allprojects {}` block is the way to go.

**Comment by oehme** [comment]
It's the opposite of a leak. A is in full control where its transitive dependencies come from. For instance, it could use a more trusted repository even if B gets some of its dependencies (maybe test dependencies) from the internet.

> I would expect B to be built using its repositories, then its packaged binary linked to A when A is built.

Not sure what you mean by that. A needs B's API dependencies to compile against B and it needs B's runtime dependencies in order to run. Where else is A going to get them than by asking some repository?

**Comment by atreat** [comment]
Ah I guess I didn't know A would need B's API dependencies to compile against B. I thought it would only need to know the APIs it talks to in B, but if B exposes any of its dependencies APIs I can see that it would cause problems.

Thanks for the info

**Comment by sschuberth** [comment]
> > Thats a shame. I'd consider the need to use an `allprojects` block an explicit act of leaking repository sources into other projects.

> It's the opposite of a leak. A is in full control where its transitive dependencies come from.

While it's indeed not a leak, it creates tight coupling that's by now [discouraged](https://docs.gradle.org/current/userguide/sharing_build_logic_between_subprojects.html#sec:convention_plugins_vs_cross_configuration). Instead, you should share build logic / configuraion via `buildSrc` or convention plugins.

In any case, to me it's a recurring source of confusion that custom repositories need to be re-declared in all consumers 😞
