### ISSUE TITLE
Resolution fails for packaging type "pom" if the maven repository responds with 403 for non-existing jar file

### ISSUE THREAD

**Issue by andrena-eike-kohnert** [gradle/gradle#4107]
### Expected Behavior

Given a maven repository which answers with HTTP 403 for non existing files.

When resolving a maven dependency with packaging type "pom" the resolving process should not fail.

### Current Behavior

Gradle fails the build with following output:

```
Cached resource https://[myArtifactoryServer]/artifactory/maven2-all/org/apache/jena/apache-jena-libs/3.6.0/apache-jena-libs-3.6.0.pom is up-to-date (lastModified: Mon Jan 22 09:04:25 CET 2018).
[...]
Failed to get resource: HEAD. [HTTP HTTP/1.1 403 Forbidden: https://[myArtifactoryServer]/artifactory/maven2-all/org/apache/jena/apache-jena-libs/3.6.0/apache-jena-libs-3.6.0.jar]
[...]
:myProject:compileJava FAILED
:myProject:compileJava (Thread[main,5,main]) completed. Took 1.982 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':jenaOrm:compileClasspath'.
> Could not determine artifacts for org.apache.jena:apache-jena-libs:3.6.0
   > Could not get resource 'https://[myArtifactoryServer]/artifactory/maven2-all/org/apache/jena/apache-jena-libs/3.6.0/apache-jena-libs-3.6.0.jar'.
      > Could not HEAD 'https://[myArtifactoryServer]/artifactory/maven2-all/org/apache/jena/apache-jena-libs/3.6.0/apache-jena-libs-3.6.0.jar'. Received status code 403 from server: Forbidden
```

### Context

The maven repository which I am using is a company internal artifactory server. It is configured to answer with http code 403 for non existing urls. When using a server which responds with http 404(as most servers) the problem does not occur. Gradle silently ignores this.

Mavens packaging type "pom" usually means, that there is no jar file. E.g. the apache-jena-libs coordinate from the example project points to such a pom project, which does not have its own jar file. The pom of that project looks like this:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>apache-jena-libs</artifactId>
  <packaging>pom</packaging>
  <name>Apache Jena - Libraries POM</name>
  <version>3.6.0</version>
  <parent>
    <groupId>org.apache.jena</groupId>
    <artifactId>jena</artifactId>
    <version>3.6.0</version>
    <relativePath>..</relativePath>
  </parent>
    ...

  <dependencies>
    ...
  </dependencies>

</project>

```

I do not know if there is a valid use case in which the jar file would be present. Currently I cannot imagine such a use case. If there is no such use case the cleanest solution would be probabbly to remove the request to that non existing jar file.

### Steps to Reproduce

As I do not know a public maven repository which answers 403 instead of 404 I cannot easily share a "ready to run" reproducer. When such a server is available, reproducing is quite simple using the following build.gradle:

```
apply plugin: 'java'

repositories {
	maven {
		url "https://[myArtifactoryServer]/artifactory/maven2-all"
		credentials {
			username artifactory_user
			password artifactory_password
		}
		authentication {
			basic(BasicAuthentication)
		}
	}
}

dependencies {
	compile 'org.apache.jena:apache-jena-libs:3.6.0'
}

```

### Your Environment

* Gradle 4.4.1
* Java Project
* Company internal artifactory server with maven repositories

**Comment by bigdaz** [comment]
Thanks for the report @andrena-eike-kohnert.  We've seen similar issues before with handling HTTP 401/403 (#3335 and #1880), except that instead of checking for existence of the entire module, we are checking for the optional _jar_ artifact for a Maven module with packaging == 'pom'.

The solution is likely for us to treat more status codes as meaning "probably missing" for a repository, in addition to 404 which means "missing". For an optional artifact like this, we'd consider "probably missing" enough to ignore and move on.

I'm not sure when we'll get to addressing this, but I'll add it to the list.

**Comment by andrena-eike-kohnert** [comment]
Thanks for your reply.

Maybe some day the described behaviour will also be changed on artifactory side. Artifactory has two issues related to this:

https://www.jfrog.com/jira/browse/RTFACT-13797
https://www.jfrog.com/jira/browse/RTFACT-8765

**Comment by citistefanos** [comment]
Having the same issue when publishing in-house Gradle plugins and using the plugins DSL to resolve them, after our (in-house) Artifactory team fiddled with permissions. There's a similar issue reported in #5606 and I would argue 403 should be treated as a missing artifact (though perhaps logged at WARN level?)

Going on #5606 this looks like a one-line fix. Should I do a PR?

**Comment by eekboom** [comment]
Can anybody explain to me why gradle even tries to access the *JAR* file at all?
Why doesn't it load the pom first, detects that it is using "pom" packaging and then skips the jar?

**Comment by bigdaz** [comment]
You can read the explanation in this (and following) comments: https://github.com/gradle/gradle/issues/6155#issuecomment-409582055

In a nutshell: Maven does this (or used to), and when we tried to stop doing it, people were reporting their builds failing.

If we have evidence that Maven no longer supports a module with `packaging = 'pom'` and a jar artifact, then it would be easy to justify us dropping this as well.

**Comment by eekboom** [comment]
Thanks a lot for the quick answer!
That seems to make sense.
How about a new gradle property that makes this behavior configurable?

**Comment by treyturner** [comment]
I'm [affected by this](https://github.com/erdi/webdriver-binaries-gradle-plugin/issues/19), as I rely on a [pom-only Gradle plugin](https://plugins.gradle.org/plugin/com.github.erdi.webdriver-binaries) that I'm attempting to source from an Artifactory virtual repository.

**Comment by DrMoriarty** [comment]
Hi All!
I know what public repository gets 403 on inexisted file: `maven { url 'https://s3.amazonaws.com/moat-sdk-builds' }`
I tried to integrade MoPub android SDK and when I added this repo now my building process crashes on facebook sdk!
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':lintVitalRelease'.
> Could not resolve all artifacts for configuration ':debugCompileClasspath'.
   > Could not resolve com.facebook.android:facebook-applinks:[4,5).
     Required by:
         project :
      > Failed to list versions for com.facebook.android:facebook-applinks.
         > Unable to load Maven meta-data from https://s3.amazonaws.com/moat-sdk-builds/com/facebook/android/facebook-applinks/maven-metadata.xml.
            > Could not get resource 'https://s3.amazonaws.com/moat-sdk-builds/com/facebook/android/facebook-applinks/maven-metadata.xml'.
               > Could not GET 'https://s3.amazonaws.com/moat-sdk-builds/com/facebook/android/facebook-applinks/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

How can I instruct gradle not to fail when it get 403 for some file?

**Comment by holuond** [comment]
I'm experiencing the same problem when publishing a new snapshot Maven artifact to Artifactory through Gradle's maven-publish, although in my case it fails on trying to locate maven-metadata.xml (in the new snapshot version, which doesn't yet exist) which returns the 403 response code and that fails the deployment. Spent some hours today trying to work around this in some clean fashion, didn't succeed. :/

**Comment by altavir** [comment]
We observe a complex problem based on this. Basically projects fails to resolve buildSrc `kotlin-dsl` from specific IPs. The error is following:
```
   > Could not resolve org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.4.
     Required by:
         project :buildSrc > org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.4
      > Could not resolve org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.4.
         > Could not get resource 'https://plugins.gradle.org/m2/org/gradle/kotlin/gradle-kotlin-dsl-plugins/2.1.4/gradle-kotlin-dsl-plugins-2.1.4.module'.
            > Could not GET 'https://jcenter.bintray.com/org/gradle/kotlin/gradle-kotlin-dsl-plugins/2.1.4/gradle-kotlin-dsl-plugins-2.1.4.module'. Received status code 403 from server: Forbidden
```

After a lot of diffing, we found out that for some reason, kotlin-dsl-plugin resolver uses a redirect that leads from gradlePluginPortal to now dead bintray. For some reason, bintray returns 403 instead of 404 for some requesting IPs and we get that error. It seems that we have some weird combination of gradle portal bug and this problem and I am not sure which is easier to fix.

**Comment by ljacomet** [comment]
There is no plan to change Gradle's behaviour with regards to interpreting a 403.
