### ISSUE TITLE
Changed case in class name should lead to full compile on case-insensitive FS

### ISSUE THREAD

**Issue by swhittaker** [gradle/gradle#4111]
### Expected Behavior
Changing the case of a package should result in a rebuild / rename of the folder
e.g. com.foo.testMe -> com.foo.testme

### Current Behavior
When the case changes the old package name is preserved in the build\classes\java folder structure.

### Context
When an app is run in this situation, the classes in that package cannot be found. This results in a ClassNotFoundException and application may crash.

### Steps to Reproduce (for bugs)
Build an application.
For a class that is used in the application, change the case of it's package (the folder not the declaration in the class - although that may change too)
Rebuild and run the application, exercising the targeted class.
Application should crash with class not found for the class in the new package name, as the old folder was preserved instead.

**Comment by oehme** [comment]
The case of the output folder is based on the package declaration in the class, not which source folder it came from. If you change the package declaration in the class, does it work correctly?

**Comment by swhittaker** [comment]
No - the class is recompiled (into build\classes\java\main\com\foo\testMe). It has the correct 'testme' package compiled in, but the parent folder is still 'testMe'.

Can easily see this behaviour by changing the case of build\classes\java\main\com\foo\testMe manually and running jar task.

**Comment by blindpirate** [comment]
I guess there's nothing we can do on Gradle's side, https://stackoverflow.com/questions/10890805/case-sensitivity-of-java-class-names

**Comment by oehme** [comment]
We can do something - When we detect a case change on a case-insensitive system, we need to do a full compile.
