### ISSUE TITLE
Shorten very long conflict resolution error reports

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#4119]
Somewhat related to bug https://github.com/gradle/gradle/issues/4118.

Reports can get very long showing all the different path to the module declaring the dependency/constraint in conflict. Maybe it can be shortened by just showing one path. I am attaching a long report example from the gradle build showing all possible paths to `com.google.collections:google`.

[https://app.zenhub.com/files/302322/cc25c4cc-62d1-429c-8351-058eddd4796b/download](https://app.zenhub.com/files/302322/cc25c4cc-62d1-429c-8351-058eddd4796b/download)

**Comment by bigdaz** [comment]
This is also proving a problem for build scans: https://gradle.slack.com/archives/C03A0MT6S/p1516729203000601

**Comment by jjohannes** [comment]
To reproduce this, you can build Gradle on the _dogfooding_ branch: https://github.com/gradle/gradle/tree/jjohannes/dependency-management/dogfood

Removing one of the _downgrading_ rules in `dependencies.gradle` should trigger the issue.

I think the solution is to remove duplications in a similar way we do it for the `dependencies` report. That probably also fixes  #4118.

**Comment by jjohannes** [comment]
It would also be nice if you can see the custom reasons (`because ...`) in the error report. If that's easy to do.
