### ISSUE TITLE
Stabilize ExcludeRuleMergingPerformanceTest

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#4121]
This test has too much noise that may hide real regressions, and makes them hard to track down when introduced. Spend some time trying things that might stabilize this test, and rebaseline if required.

**Comment by jjohannes** [comment]
We now have a new more specific test and will ad another one in #4281. Also some general performance test stability improvements are coming (bare metal agents).
I am closing this issue. We can reopen if we encounter issues again.
