### ISSUE TITLE
GradleBuild.startParameter.includedBuilds does not work

### ISSUE THREAD

**Issue by AlexMAS** [gradle/gradle#4153]
Hello!

I try to create a build task in my `build.gradle` like this:

```groovy
task buildDebug(type: GradleBuild) {

    startParameter.includedBuilds = [
        new File('../component1'),
        new File('../component2')
    ]

    tasks = [ 'build' ]
}
```

And when I run `gradle buildDebug` I get an error `Could not resolve all files for configuration...` i.e. some dependencies from `component1` and `component2` weren't resolved. But if I do the same using command line:

```bash
$ gradle --include-build ../component1 --include-build ../component2 build
```

It works fine.

What should I do to fix this problem?

### Expected Behavior

Value of `startParameter.includedBuilds` are used during execution the specified tasks.

### Current Behavior

It seams that value of `startParameter.includedBuilds` are ignored.

### Context

Composite build.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/m5q2mcrggxbza/

**Comment by oehme** [comment]
This is not meant to be mutated (and we should make it read-only). Please use `includeBuild` in `settings.gradle`.

**Comment by AlexMAS** [comment]
I've tried to find some workaround and now I have a little solution but it is not exactly what I want...

In my `settings.gradle` file I put some logic which defines how to build the project - as a composite project or not. For that I defined my own project parameter `composite`.

*settings.gradle*
```groovy
if (startParameter.projectProperties.composite != null) {
    includeBuild '../component1'
    includeBuild '../component2'
}
```

So when I run:

```bash
$ gradle build
```

I have the normal build and dependencies are resolved from defined repositories.

When I run:

```bash
$ gradle build -Pcomposite=true
```

I have the composite build and it works fine.

I do not like to pass parameters because it is unclear and inconvenient, so next step I decided to create an appropriate task:

```bash
task buildDebug(type: GradleBuild) {
    tasks = [ 'build' ]
    startParameter.setProjectProperties([ 'composite': 'true' ])
}
```

But when I execute it:

```bash
$ gradle buildDebug
```

I get the exception which says `Included build 'X' cannot have included builds`.

I suppose that running nested task in the way like above is cause of the exception but I do not know how to escape this restriction.

**Context**

Maybe I reinvent the wheel so I need your help. I have several independent components each of them is in its own repository. Sometimes I would like to work with project by using composite build especially in cases when I make changes in several related components. It would allow me not to publish inconsistent versions of the components. But normally I work only with one component (repository) and would like to use stable dependencies hence do not use composite build. If I declare included builds in my `settings.gradle` without any conditions I will be forced to use composite build by default always as I run `gradle build`. But it is not necessary in my case. In addition, repositories of included components can have inappropriate state and developers can get unexpected errors during the build.

**Comment by oehme** [comment]
I'm sorry, I misread your initial code snippet. Nested composites aren't supported at the moment and a `GradleBuild` task is treated very much like a composite itself. I don't think I have a better solution for your use case than using a property.

**Comment by AlexMAS** [comment]
Thank you for replying! Yes, I understand now why it happens. I think the solution with a property will be enough.

**Comment by rjbell4** [comment]
FWIW, nested composites work now in Gradle v4.10 ... except with the GradleBuild task :disappointed:
