### ISSUE TITLE
Deprecation message for use of classes in `org.gradle.util` package is almost never shown to the user

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#4160]
The deprecation message for usage of classes such as `org.gradle.util.GradleVersion` is emitted only when the build script is compiled, rather than each time the build is run. What this means is the user sees something like this:

```
# initial build
> ./gradlew build

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
...

BUILD SUCCESSFUL in 3s
> ./gradlew build --warning-mode=all

BUILD SUCCESSFUL in 3s
# me: oh well, it's gone now, all is good
```

Unless the user knows that the deprecation warning happens to come from script compilation and how to provoke a recompile, this warning is basically never shown. Even when the user is running the build with `--warning-mode`, they only see the warning once and then it goes away.

### Expected Behavior

A deprecation warning message for a feature should be emitted on _every_ build.

### Current Behavior

The deprecation warning message disappears and is quickly forgotten.

**Comment by totorovan** [comment]
May I take this one?

**Comment by totorovan** [comment]
May I take this one?

**Comment by hhumas** [comment]
any solution for this >.. my app was using gradle 2.0 which do not support instant run so i updated the gradle . now when i try to make release i get error

**Comment by adammurdoch** [comment]
Closing, as the deprecation message is long gone.
