### ISSUE TITLE
The Gradle distribution ships outdated Gradle icons

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#4161]
### Expected Behavior
Either ship up-to-date media files or remove them from the distribution.

### Current Behavior
The Gradle distribution ships outdated icon files in the `./media` subdirectory.

### Context
I was showing the layout of the Gradle distribution to a colleague and going through each directory. When we reached the media directory, he saw the icons and reacted as "wasn't the Gradle logo some kind of elephant?"

Overall, my view is that branding files don't need to be part of the distributions, but if they are, they should be up to date and accompanied by usage guidelines.

**Comment by blindpirate** [comment]
Thanks @ddimtirov for your kind reminder. @eriwen could you take a look at this?
