### ISSUE TITLE
Upgrade to AWS SDK 2.0

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4162]
Follow-up to #4029

**Comment by oehme** [comment]
The dependency management team should take care of this, since this is used for publishing and resolving dependencies. I'm not sure what you mean by "what's expected here". We use the AWS SDK in an outdated version and need to update it. That's all :)

**Comment by TarodBOFH** [comment]
aws SDK 2 is still in preview as per this writing: 

_NOTE 2.0 version still a preview and is not recommended for production use yet._

**Comment by oehme** [comment]
At the very least we should upgrade to an AWS version that is Java 11 compatible. The current one relies on java.xml.bind, which is no longer part of the JDK.

**Comment by ljacomet** [comment]
Already done as part of #6215 and #6626

**Comment by marcphilipp** [comment]
Well, I updated the SDK in #6215 but it's still not compatible with Java 11 at the moment because JAXB is missing from the JDK.

@ljacomet Since AWS SDK 2.0 is not GA, yet, I think we should reopen this issue and assign it to 6.0 for now.

**Comment by ljacomet** [comment]
Right, makes sense.

**Comment by Bwvolleyball** [comment]
Hello, I'm not sure if this changes the plans, but it seems that the aws sdk 2.x is now GA:

https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-x-released/

There do seem to be a few things still missing from 2.x which could be a deal breaker at the moment though.

**Comment by marcphilipp** [comment]
Thanks for letting us know! Sounds like we should wait for it to become feature-complete, in particular where S3 features are concerned, before upgrading.

**Comment by Bwvolleyball** [comment]
Just to post a quick update, it looks like the latest version of the aws-sdk for java is now up to `2.5.2` [maven central listing](https://search.maven.org/artifact/software.amazon.awssdk/aws-sdk-java/2.5.2/jar). I tried really hard to see if the S3 features are available yet, but couldn't confirm or deny their presence.

**Comment by abrooksv** [comment]
@Bwvolleyball S3's client is out, the high level library TransferManager has not been created for V2 though.

The S3 migration guide can be found here: https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#41-s3-changes

**Comment by ljacomet** [comment]
Given the description on https://aws.amazon.com/sdk-for-java/ where it states:
> The 2.0 version of the SDK is a major rewrite of the 1.11 code base.

and
> Although we’re excited about the AWS SDK for Java 2.0, we also want to reassure customers that we will continue to update the 1.11 SDK with new service APIs, new services, bug fixes and security fixes.

Also given the scope of the [migration guide](https://docs.aws.amazon.com/sdk-for-java/v2/migration-guide/whats-different.html), I do not see this as a small task.

So proposal would be to remove any target milestone here and see when it can be properly planned.
And that does not prevent Gradle from staying up-to-date with the `1.11.x` releases.

**Comment by ljacomet** [comment]
Closing as this is currently not planned.

**Comment by alienisty** [comment]
@ljacomet you may want to reopen this one, what you quoted in your last comment

> Although we’re excited about the AWS SDK for Java 2.0, we also want to reassure customers that we will continue to update the 1.11 SDK with new service APIs, new services, bug fixes and security fixes.

is no longer true, [support for the 1.11 SDK ends December 31, 2025](https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/)
