### ISSUE TITLE
Tasks with type war are not working properly

### ISSUE THREAD

**Issue by kpramesh2212** [gradle/gradle#4169]
My Gradle Version:
=====================
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Linux 4.13.0-31-generic amd64

Issue 1: War task is not honoring the includes pattern
======================
Consider the build file
```
apply plugin: 'war'               
task earSoapApiWar(type: War) {
	group 'ITNCM War'
	description "Creates ear-SOAP-API.war file"
	webXml = file("xml/war/soap_war.xml")
	includeEmptyDirs = false
	archiveName = "ear-SOAP-API.war"
	
	includes = [
				 "com/intelliden/icos/soap/**",
				 "com/intelliden/icos/util/soap/**",
				 "com/intelliden/icos/iweb/servlet/*Stream*",
				 "com/intelliden/icos/iweb/servlet/*Servlet*",
				 "com/intelliden/icos/iweb/servlet/*JNLP*",
				 "com/intelliden/servlet/**",
				 "com/intelliden/icos/iweb/servlet/NetworkResourceConfigGMDServlet.class",
				 "com/intelliden/icos/iweb/servlet/ServletBase.class",
				 "com/intelliden/icos/iweb/servlet/Constants.class",
				 "com/intelliden/icos/iweb/servlet/IntelliDENSession.class",
				 "com/intelliden/icos/iweb/StateMap.class",
				 "com/intelliden/icos/iweb/PropertyMap.class",
				 "com/intelliden/common/soap/CDATAEncoder.class"
   				]


	metaInf {
	   from "properties/axis-config/META-INF"
	   include "services/org.apache.axis.components.encoding.XMLEncoder"
	}
    
   
    classpath configurations.wsdlAxis.filter {
    			(it.name.startsWith("axis") || it.name.startsWith('wsdl4j')) && !it.name.startsWith("axis-ant")
    			}
}
```
**Problematic Output =   The produced war file contains all the classes.**  
**Expected Output = The war file should only contain the classes included in the includes pattern.**

Issue 2: inputs.files not working for WAR tasks
===============
 Consider the following build file
```
apply plugin : 'java'
task earSoapApiWar(type: War) {
	group 'ITNCM War'
	description "Creates ear-SOAP-API.war file"
	webXml = file("xml/war/soap_war.xml")
	includeEmptyDirs = false
	archiveName = "ear-SOAP-API.war"
        inputs.files fileTree(dir: sourceSet.main.java.outputDir)
		
	metaInf {
	   from "properties/axis-config/META-INF"
	   include "services/org.apache.axis.components.encoding.XMLEncoder"
	}
    
   
    classpath configurations.wsdlAxis.filter {
    			(it.name.startsWith("axis") || it.name.startsWith('wsdl4j')) && !it.name.startsWith("axis-ant")
			  }


                             
                             
}
```
**Problematic output:  The produced war file doesn't have any classes**
**Expected output: The produced war file should have all the classes in the sourceSet.main.java.outputDir**

Issue 3: tasks with type WAR by default assumes the inputs.files is sourceSets.main.java.outputDir
=====
Consider the following build file

```
apply plugin: 'war'

task myWar(type: War) {
   archiveName = "mywar.war"
   webXml = "properties/web.xml"
}
```
Consider the following build file
```
apply plugin: 'jar'

task myJar(type: Jar) {
  archiveName = "myjar.jar"
}
```
Run  the above task myJar produces myjar.jar

The contents of the myjar.jar file is empty which is good (Since i havent specified any inputs for myJar task)

However running the task myWar produces mywar.war
**Expected output: Then contents of the mywar.war should be only containing the web.xml file and it should not contain any class files since i haven't told my custom war task where to find the class files from**
**Actual output: Contains the class files from sourceset.main.java.outputDir**

Please let me know if any more details are required.

**Comment by blindpirate** [comment]
Thanks for reporting, can you provide us with a sample project? That would be great.

**Comment by kpramesh2212** [comment]
@blindpirate 

Thanks for taking this ticket into consideration and thanks for your time.

issue2: I am not able to remember how to reproduce this but I will update you on it

However for issue1 and issue3, I have attached a sample project
[issues.zip](https://github.com/gradle/gradle/files/1681530/issues.zip)

**Comment by blindpirate** [comment]
Thanks. 

You'd use 

```
war {
    rootSpec.include("**/Include.class")
    rootSpec.exclude("**/Exclude.class")
}
```

It's a bit complex, though. See [here](https://discuss.gradle.org/t/how-can-i-exlude-files-from-war-when-using-war-plugin-against-default-or-webappdirname-location/7366/10) for a reference.

As for issue3, I think that is just something conventional. `jar` is just a normal file container and you can put anything in it, which means a empty jar is of course ok. However, most servlet containers assume `war` contains all necessary web application files so that they can load and start web application automatically.
