### ISSUE TITLE
Importing generated eclipse projects results in build path errors

### ISSUE THREAD

**Issue by epeee** [gradle/gradle#4172]
### Expected Behavior
Running `./gradlew eclipse` and importing the generated projects should not end up in build path errors.

### Current Behavior
Running `./gradlew eclipse` and importing the generated projects ends up in:
 _"Cannot nest 'projA/src/main/java' inside 'projA'. To enable the nesting exclude 'src/' from 'projA''"_ Build Path Problem.

### Context
It looks like this one was introduced in Gradle 4.5. Using Gradle 4.4.1 the generated project can be imported to Eclipse without any errors. 
This one is a minor one which can be fixed easily in the build.gradle file, but it might break some builds which are out there.

### Steps to Reproduce
This can be reproduced by having a *settings.gradle* like

```
include 'projA'
include 'projB'
```
and a *build.gradle* like 
```
subprojects {
    apply plugin: 'java'
    apply plugin: 'eclipse'

    dependencies {
        testCompile project(':projA')
    }
}
```

In order to use Gradle 4.5 we are adding the `testCompile project(':projA')` dependency only if the subproject is not 'projA'.

self-contained example: https://github.com/epeee/gradle-4172.

**Comment by bmuschko** [comment]
@donat Could you please look into this?

**Comment by donat** [comment]
This is probably related to the recent changes in the dependency resolution engine.

**Comment by oehme** [comment]
@donat Could you fix the [EclipseDependencyCreator](https://github.com/gradle/gradle/blob/master/subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/EclipseDependenciesCreator.java#L97)? I forgot the self-dependency check like in the [IDEA plugin](https://github.com/gradle/gradle/blob/master/subprojects/ide/src/main/java/org/gradle/plugins/ide/idea/model/internal/IdeaDependenciesProvider.java#L164). This means we are missing test coverage. You might want to double-check other implementations of `IdeDependencyVisitor`.

**Comment by epeee** [comment]
@oehme thx for the hint! I can confirm that the generated project can be imported without errors again after applying your fix (building gradle locally using fixes from https://github.com/epeee/gradle/tree/gradle-4172).
I have not checked other implementations of `IdeDependencyVisitor` though.

**Comment by oehme** [comment]
@donat Since we're doing a patch release anyway, we should fix this there as well. The release is on Monday, so could you look into this today? If not I'll try to free up some time.
