### ISSUE TITLE
Could not find method on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

### ISSUE THREAD

**Issue by dengzhao7053** [gradle/gradle#4173]
when i build apks, there was an error.
Error:Could not find method ileja_testDebugCompile() for arguments [DefaultProjectDependency{dependencyProject='project ':carrobotCommons'', configuration='ileja_testDebug'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### Your Environment
Android studio 
buildToolsVersion "25.0.3"
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

**Comment by oehme** [comment]
Please use the Android issue tracker for Android related questions. My best bet is that you updated to Android 3.0 and need to adjust your build according to the [migration guide](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html)
