### ISSUE TITLE
Passing project parameters to an included build

### ISSUE THREAD

**Issue by AlexMAS** [gradle/gradle#4178]
Hello!

I defined the dependency on tasks from included builds:

*build.gradle*
```groovy
task someCompositeTask {
    dependsOn gradle.includedBuilds*.task(':someIncludedTask')
}
```

Is there a way to run `someCompositeTask` with parameters:

```bash
$ gradle someCompositeTask -Pparam1=123
```

And get these parameters during processing `someIncludedTask`?

### Expected Behavior

Included tasks receive parameters from composite task.

### Current Behavior

Included tasks do not receive parameters from composite task.

**Comment by NightXlt** [comment]
This problem is really a pain point in our daily work. Does the fix in your schedule table?  Thank you for your time.

**Comment by blindpirate** [comment]
For people googled this:

![image](https://user-images.githubusercontent.com/12689835/183783906-f4da7d3c-8ff4-4c35-a421-fd62266974e0.png)

```
tasks.register("includedHello") {
    doLast {
        println("includedHello: ${gradle.startParameter.projectProperties} ${gradle.parent!!.startParameter.projectProperties}")
    }
}

```
