### ISSUE TITLE
Add a getter for the 'version constraints' property on `ExternalDependency`

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#4182]
In general, we should provide getters for all data structures in the model. The version constraints structure of a dependency declaration is such a structure, however there is no getter for it.

### Expected Behavior

A getter is present for this structure.

### Current Behavior

No getter is present.

**Comment by adammurdoch** [comment]
The getter on `DependencyConstraint` should return a mutable version constraint structure as well.

**Comment by melix** [comment]
To be clear, the getter is defined in `ModuleVersionSelector`, that `ExternalDependency` extends. So it's more about overloading the return type to `MutableVersionConstraint`.

**Comment by bigdaz** [comment]
This has been added
