### ISSUE TITLE
DependencyConstraint should not extend from Dependency

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#4184]
A dependency declaration, represented using `Dependency` represents some capability that must be present for the consumer to function. A dependency constraint applies some additional criteria to things that are otherwise present or not in the dependency graph. Or, another way to view this is that a dependency adds edges to the graph, and a dependency constraint affects which versions these edges can point to but does not add edges.

These aren't the same things and should not share `Dependency` as a common API.

### Expected Behavior

Dependency declarations and dependency constraints are modelled as different things.

### Current Behavior

Dependency declarations and dependency constraints are modelled as the same things.

**Comment by jjohannes** [comment]
After gaining some experiences with using constraints and discussing this wit Adam, I think we should give it another try to remove this coupling of `Dependency` and `DependencyConstraint` from the APIs.
