### ISSUE TITLE
Allow the dependency constraints associated with a configuration to be queried

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#4185]
In general, it should be possible to query the data structures associated with the model. The dependency constraints associated with a configuration are part of the model and should be queryable, in a similar way that the dependency declarations for a configuration can be queried.

### Expected Behavior

There is a way to query dependency constraints associated with a configuration that is consistent with the way that dependency declarations are queried (which can be different to whatever that happens to be now).

### Current Behavior

Dependency constraints are write-only.

**Comment by jjohannes** [comment]
Actually, dependency constraints are part of the dependency set at the moment (because they also extend Dependency) and can be accessed through that. This will change with #4184. So these two issues are best addressed together.

**Comment by jjohannes** [comment]
Added as part of #4255:

https://github.com/gradle/gradle/pull/4255/files#diff-123dd87518f4d90f42e82145375e901a
