### ISSUE TITLE
Move preview-features.adoc content to user guide

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#4189]
Makes this (or parts of it) part of the user guide:
https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/preview-features.adoc

The documentation about how POMs/BOMs are supported by Gradle should be part os the user guide and linked in the corresponding 4.6 release notes sections.

**Comment by bmuschko** [comment]
It might work well in this section: https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html
