### ISSUE TITLE
Multi-project build. Can't import packages

### ISSUE THREAD

**Issue by soberich** [gradle/gradle#4200]
### Expected Behavior
one subproject can import packages from another

### Current Behavior
there is a root project (just a wrapper with no code) and several subprojects (I cleaned it up to just two projects to resolve this issue). When I work in IDEA everything inported as usual. I have a module (subproject) with db entities, and the other module (second subproject) and, of course, I put 
the line in build.gradle in user-service module (the one which depends on the user-service-api)
`implementation(project(":user-service-api"))`
but when I run (clean) build I got 
```
> Task :user-service:compileJava FAILED
Compiling with JDK Java compiler API.
C:\Users\..\IdeaProjects\poliglot\user-service\src\main\java\de\psg\domain\user\impl\UserRepository.java:3: error: package de.psg.domain.user.model does not exist
import de.psg.domain.user.model.User;
                               ^
C:\Users\..\IdeaProjects\poliglot\user-service\src\main\java\de\psg\domain\user\impl\UserRepository.java:11: error: cannot find symbol
public interface UserRepository extends JpaRepository<User, Long> {
                                                      ^
  symbol: class User
C:\Users\..\IdeaProjects\..\user-service\src\main\java\de\psg\domain\user\impl\UserRepository.java:12: error: cannot find symbol
    Stream<User> getAll();
           ^
  symbol:   class User
  location: interface UserRepository
C:\Users\..\IdeaProjects\..\user-service\src\main\java\de\psg\domain\user\impl\UserRepository.java:13: error: cannot find symbol
    Stream<User> getByName(String name);
           ^
  symbol:   class User
  location: interface UserRepository
```

### Context
multimodule project where api jars separated from impl.

ALSO, as a notу I have the same package struckture in both modules
it is `de.psg.domain.user.*` for all packages across modules
so in API module it is `de.psg.domain.user.model` etc.
and in impl module `de.psg.domain.user.impl`  and `de.psg.domain.user.utils` etc. maybe this confuses build process ?
```
C:.
├───user-service
│   ├───build
│   │   ├───classes
│   │   │   └───java
│   │   │       └───main
│   │   └───tmp
│   │       └───compileJava
│   └───src
│       └───main
│           ├───java
│           │   └───de
│           │       └───psg
│           │           └───domain
│           │               └───user
│           │                   └───impl
│           ├───resources
│           │   └───META-INF
│           └───webapp
│               ├───resources
│               └───WEB-INF
└───user-service-api
    └───src
        └───main
            ├───java
            │   └───de
            │       └───psg
            │           └───domain
            │               └───user
            │                   ├───api
            │                   └───model
            └───resources
```
### Steps to Reproduce (for bugs)
gradlew clean build

### Your Environment
------------------------------------------------------------
Gradle 4.5
------------------------------------------------------------

Build time:   2018-01-24 17:04:52 UTC
Revision:     77d0ec90636f43669dc794ca17ef80dd65457bec

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 7 6.1 amd64

**Comment by oehme** [comment]
Please provide a reproducible example project, either as an archive or as a Github project.

**Comment by soberich** [comment]
My bad. 
I spend one day with thу issue, but it turn out the bnd plugin were doing its thing.
The project's which I depend on `.bnd` file contained `-wab:` directive, so its classpath terned into web-project alike. So the dependent project could not reslove it.
Unforntunatevly, those kind of tools like `bnd` does not provide a lot of the debug/loging capabilities, so It is always hard to say what is happening underneath.
Thank you very much.
