### ISSUE TITLE
In Gradle 4.5 the javadoc of SetProperty interface contains link to wrong factory method org.gradle.api.model.ObjectFactory#listProperty(Class)

### ISSUE THREAD

**Issue by bronogard** [gradle/gradle#4203]
### Expected Behavior
When I open the javadoc of the [SetProperty](https://github.com/gradle/gradle/blob/521d1c279d81fddd42cbeab21754aaf08065e1cd/subprojects/core-api/src/main/java/org/gradle/api/provider/SetProperty.java#L26) interface I want to see a javadoc link to [ObjectFactory#setProperty](https://github.com/gradle/gradle/blob/521d1c279d81fddd42cbeab21754aaf08065e1cd/subprojects/core-api/src/main/java/org/gradle/api/model/ObjectFactory.java#L114).

### Current Behavior
When I open the javadoc of the [SetProperty](https://github.com/gradle/gradle/blob/521d1c279d81fddd42cbeab21754aaf08065e1cd/subprojects/core-api/src/main/java/org/gradle/api/provider/SetProperty.java#L26) interface I see a javadoc link to [ObjectFactory#listProperty](https://github.com/gradle/gradle/blob/521d1c279d81fddd42cbeab21754aaf08065e1cd/subprojects/core-api/src/main/java/org/gradle/api/model/ObjectFactory.java#L102).

### Context
No big impact at all.

### Steps to Reproduce (for bugs)
A click on the link to [SetProperty](https://github.com/gradle/gradle/blob/521d1c279d81fddd42cbeab21754aaf08065e1cd/subprojects/core-api/src/main/java/org/gradle/api/provider/SetProperty.java#L26) interface will suffice to see what I described above.

### Your Environment
Gradle 4.5
Windows 10 Pro (1703 15063.850)
IntelliJ IDEA 2017.3.3 (Community Edition)

**Comment by big-guy** [comment]
Thanks @bronogard -- I've fixed the link in https://github.com/gradle/gradle/commit/04deb22ee0004e97c38977551723e1936abe23c8
