### ISSUE TITLE
Trying to run gradle wrapper from Windows' Bash, the SDK directory is being interpreted as a concatenation of Windows/Linux PATH

### ISSUE THREAD

**Issue by code-n-roll** [gradle/gradle#4207]
### Expected Behavior

When running "./gradlew task" in a android project dir, under bash shell in windows subsystem for linux, I expect it to run the task.

### Current Behavior

 What went wrong:
A problem occurred configuring project ':app'.
 The SDK directory '/mnt/d/android/projects/projectname/D:\android\sdk' does not exist.

### Context

bash shell in windows subsystem for linux

### Steps to Reproduce (for bugs)

Install windows subsystem for linux
Open terminal
Type "bash" in terminal
Move to project directory
Run ./gradlew task

**Comment by oehme** [comment]
Please open Android-related issues on the [Android Issue Tracker](https://source.android.com/source/report-bugs)
