### ISSUE TITLE
Configurable distribution repository URL for Gradle wrapper download

### ISSUE THREAD

**Issue by reegnz** [gradle/gradle#4210]
### Expected Behavior
I want to override the repository url for the gradle wrapper task with my custom repository URL, so that the wrapper config generated uses my mirror instead of the official distribution point.
```
wrapper {
  repositoryUrl = "https://my-private.mirror.org/gradle-distributions" 
}
```
If I want to update gradle wrapper to a new version, I want the following command to use the repo I have specified above.
```
./gradlew wrapper --gradle-version 4.5
```

### Current Behavior
I can only override the entire distributionUrl:
```
wrapper {
  distributionUrl = 'https://my-private.mirror.org/gradle-distributions/gradle-4.4.1-bin.zip'
}
```
This means I cannot upgrade my gradle wrapper config pointing to my custom site with the following command:
```
./gradlew wrapper --gradle-version 4.5
```

### Context

I want to mirror gradle distributions in-house at our company to reduce outbound network traffic, but also make upgrading gradle wrapper as simple as if I were using services.gradle.org.

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Can you try using:

```
  distributionUrl = "https://my-private.mirror.org/gradle-distributions/gradle-${gradleVersion}-bin.zip"
```

**Comment by reegnz** [comment]
I opened this ticket after finding this in the gradle source code:
https://github.com/gradle/gradle/blob/34750856b4ea704208f1b4872e96d13f29329718/subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java#L342

So I assume it's not as simple as that.  :(

Didn't try it out though, so I'll also verify your suggestion.

**Comment by reegnz** [comment]
@oehme Ok, I've tried various configurations:
```
wrapper {
distributionUrl = "https://my-private.mirror.org/gradle-distributions/gradle-${gradleVersion}-bin.zip"
}
```
Cannot use --gradle-version from CLI to upgrade version, always takes current gradle version.

Another alternative I've tried (the current one I'm using):
```
wrapper {
  gradleVersion = '4.4.1'
  distributionUrl = "https://my-private.mirror.org/gradle-distributions/gradle-${gradleVersion}-bin.zip"
}
```
--gradle-version from CLI doesn't override version in build.gradle
If it were to work it would still fall back to the configured one instead of the current version (like in the previous one).

**Comment by oehme** [comment]
This could be fixed by using the new `Provider` infrastructure here instead of a plain `String`. Would you be interested in providing a pull request?

Otherwise you can always do something like this to modify the url last minute, when the version is known (pretty hacky):

```
wrapper {
  doFirst {
     distributionUrl = "https://my-private.mirror.org/gradle-distributions/gradle-${gradleVersion}-bin.zip"
  }
}
```

**Comment by reegnz** [comment]
I am not that familiar with the provider infrastructure yet.
I'll have a look.

**Comment by big-guy** [comment]
`Provider` is the right answer here, but the most reliable workaround for now would be:

```
task configureWrapper {
  doLast { 
    wrapper.distributionUrl = "https://my-private.mirror.org/gradle-distributions/gradle-${wrapper.gradleVersion}-bin.zip"
  } 
}   

wrapper.dependsOn configureWrapper
```

Using `doFirst` to modify inputs is going to fail in the future and would behave incorrectly if you needed to change the URL at some point.

**Comment by bodiam** [comment]
I have the same issue. I'm in an enterprise setting, and I have to download Gradle from an internal repository, but after every wrapper upgrade, I have to fix the URLs. Would be nice if this could be fixed.

**Comment by soloturn** [comment]
"gradle init" also destroys an existing url and enters an unreachable default URL in an enterprise setting.

**Comment by martinda** [comment]
Is there an example of the `Provider` infrastructure that would teach me how to add a system property such as `gradle.wrapperRepository` which, when set, would replace the hard code string value in `DistributionLocator.java`?

**Comment by mjadczak** [comment]
It looks like this was added in version 8.2: https://github.com/gradle/gradle/commit/a6313ff9592aed71bb34694a9f03e9d37dcdc777#diff-9b13417b3301e94644ac049b22a8a6b0056a6597d10167e756580c5ee5934c7e

You can now set this in your `gradle.properties` file in order to set the base url:

```
systemProp.org.gradle.internal.services.base.url=https\://my-artifactory-server.local/services-gradle-remote 
```

The configured URL should proxy/mirror `https://services.gradle.org`. I'm sure the fact that the property is on an `internal` package means that it's not officially stable, but I'm happy to take it. It would be nice to stabilise this as a documented property!
