### ISSUE TITLE
Relative path sensitivity isn't accounted for in task inputs

### ISSUE THREAD

**Issue by robbie-demuth** [gradle/gradle#4213]
### Expected Behavior

Changes to relative paths of files that are used as task inputs annotated with `@PathSensitive(PathSensitivity.RELATIVE)` should cause the cache key of the task to change, thus making the task out-of-date.

### Current Behavior

Suppose I have the following task class:

```
@CacheableTask
public class CustomTask extends DefaultTask {

  Project project = getProject();

  public Object inputDir;
  public Object outputFile;

  @Internal
  public File getInputDir() {
    return project.file(inputDir);
  }

  public void setInputDir(Object inputDir) {
    this.inputDir = inputDir;
  }

  @OutputFile
  public File getOutputFile() {
    return project.file(outputFile);
  }

  public void setOutputFile(Object outputFile) {
    this.outputFile = outputFile;
  }

  @InputFiles
  @PathSensitive(PathSensitivity.RELATIVE)
  public Iterable<File> getInputFiles() {
    return project.fileTree(ImmutableMap.of("dir", getInputDir(), "includes", ImmutableList.of("**/*"))).getFiles();
  }

  @TaskAction
  public void taskAction() {
    project.delete(outputFile);
    CharSink charSink = Files.asCharSink(getOutputFile(), Charsets.UTF_8, FileWriteMode.APPEND);
    for (File file : getInputFiles()) {
      try {
        charSink.write(project.getProjectDir().toPath().relativize(file.toPath()) + System.getProperty("line.separator"));
      } catch (IOException e) {
        throw new GradleException("Could not write to " + outputFile);
      }
    }
  }

}
```

And suppose I have the following directory structure:

```
input/
  _a/
  a/
    a.txt
```

And suppose I have the following build script:

```
task customTask(type: CustomTask) {
  inputDir = 'input'
  outputFile = 'output.txt'
}
```

I run `gradle customTask` once to populate the task's history. As expected, `output.txt` contains the following: `input\a\a.txt` (I'm on Windows). Now, I move `a.txt` from `a/` to `_a/`, so my directory structure looks like the following:

```
input/
  _a/
    a.txt
  a/
```

When I run `gradle customTask` again, Gradle marks the task as `UP-TO-DATE`. 

### Context

While I created just enough code here to get a working sample, our organization recently ran into this issue on a more complex task class when a developer tried moving a file from one directory to another. While Gradle should have detected that the cache key of the task had changed, it did not and the developer ended up getting a cache hit against our remote cache.

### Steps to Reproduce (for bugs)

Unzip [bug.zip](https://github.com/gradle/gradle/files/1679570/bug.zip) and follow the instructions above.

### Your Environment

 * Build scan URL: N/A

**Comment by wolfs** [comment]
@robbie-demuth Thank you for reporting!

By calling `getFiles` on the file tree, you loose the hierarchy information which is essential for relative path sensitivity. So Gradle treats each file as root file relative to itself. This is why the change is not detected.

Try using this instead:
```
@InputFiles
@PathSensitive(PathSensitivity.RELATIVE)
public FileTree getInputFiles() {
    return project.fileTree(ImmutableMap.of("dir", getInputDir(), "includes", ImmutableList.of("**/*")));
}
```

Does this fix your problem?

**Comment by wolfs** [comment]
Even easier, why don't you annotate `getInputDir()` with `@InputDirectory @PathSensitive(PathSensitivity.RELATIVE)` and `getInputFiles()` with `@Internal`?

**Comment by robbie-demuth** [comment]
Thanks for the quick reply, @wolfs

With respect to calling `getFiles()` on the tree, that was something I had to implement to navigate around another issue I created regarding FileTrees matching empty directories (see https://github.com/gradle/gradle/issues/3444). Do you have any insight into that issue? Based on what you said above, it sounds like what I’m encountering is intended behavior. In that case, I think the documentation around relative path sensitivity might need some clarification since I spent a good chuck of time today reading through it and couldn’t figure out why the task was still `UP-TO-DATE`

Regarding your second suggestion, I simplified the example quite a bit, but in practice, the task class wraps some legacy code that expects directories as inputs, but only cares about files with certain extensions when creating files in the output directory. Given that behavior, I thought it made most sense to expose the directories via an internal property to the tasks in the build script while calculating the actual task inputs using those directories internally. If you can think of a better design pattern for this use case, I’d be happy to hear about it

**Comment by wolfs** [comment]
Hi @robbie-demuth.

I agree that our documentation about path sensitivity could be better. If you have a suggestion how to improve please provide an issue or a PR.

In your example then includes where `**/*`, this is why I suggested adding the input directory directly as an input. What you are saying makes sense and your solution should work.

**Comment by robbie-demuth** [comment]
@wolfs - Do you have any insight into the other issue I linked (https://github.com/gradle/gradle/issues/3444)? Also, based on what you said above, is it correct to state that relative path sensitivity only has an effect when the annotation is placed on a FileTree? It sounds like placing it on anything else would only catching renaming a file in which case, it functions like `PathSensitivity.NAME_ONLY`

**Comment by wolfs** [comment]
@robbie-demuth relative path sensitivity has an effect when the annotation is placed on a `FileTree` or a `FileCollection`. It even works on a single `File` or an `Iterable<File>`, if the files are directories. As soon as you add every file in a directory to the collection which is annotated and the collection is not a `FileTree`, then relative path sensitivity will not have the desired effect.

**Comment by wolfs** [comment]
Closing since this is working as expected. Please re-open if you see something which has not been addressed.
