### ISSUE TITLE
The tooling API should provide a way to get the dependencies of the project

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#4215]
The tooling API doesn't provide a way to get the dependencies of the project.

### Expected Behavior
The tooling API would provide a way to get the dependencies of the project.

### Current Behavior
The tooling API doesn't provide a way to get the dependencies of the project.

### Context
I'm trying to build a tool to track the dependencies between multiple projects.

### Steps to Reproduce (for bugs)
N/A

### Your Environment
JDK 8

**Comment by bmuschko** [comment]
You can query the information via the `IdeaProject` or the `EclipseProject`. Please refer to the following two resources:

- https://discuss.gradle.org/t/getting-dependencies-using-gradle-tooling/17793
- https://issues.gradle.org/browse/GRADLE-2055

Let us know if you have additional questions.

**Comment by asarkar** [comment]
@bmuschko that’s not the same thing. The IDEA/Eclipse modules require respective project files to be present. A Gradle project is a Gradle project regardless of an IDE; it doesn’t make sense to depend on an IDE for getting basic project information. The `GradleProject` module should expose the dependencies.

**Comment by asarkar** [comment]
I stand corrected. I was trying to get the `IdeaModel` that failed without the project files, but `IdeaProject` seems to work. I'll look into it and report back if I face any problems. Thanks.

That said, it is extremely confusing to get project info from the IDE projects.

**Comment by oehme** [comment]
The Tooling API models are crafted to the specific needs of the tool they are used for. A generic "dependency model" would not be useful in that regard, as every tool needs different information. It would just end up being hugely complex and leaking all kinds of internal information, making it a bad candidate for the forward and backward compatibility we guarantee for tooling models. It would also be incredibly expensive to resolve every configuration in every project (which such a generic model would have to do, as it doesn't know what the user wants). In short: Generic models are bad :)

The Tooling API is [extensible](https://docs.gradle.org/current/javadoc/org/gradle/tooling/provider/model/ToolingModelBuilderRegistry.html), you can write your own model builders and query them to get exactly what your tool needs. You can inject your custom model builder with an init script, so you can request it from any existing project without changing that project.
