### ISSUE TITLE
Remove malformed jar deprecation

### ISSUE THREAD

**Issue by melix** [gradle/gradle#4218]
Currently, if a jar on classpath is malformed, we issue a warning explaining that this is not going to supported as of Gradle 5.0.

However, there are multiple cases where this could be wrong:

- for newer Java releases, for which Gradle is not ready, any unrecognized class format will trigger the problem. That's why we had to reintroduce a `Java10ClassReader`
- for some use cases, putting a malformed jar on classpath is valid. See [this tweet](https://twitter.com/CedricChampeau/status/943149158805966849) for example.
- Gradle may have a bug (but admittedly if there's such a bug we need to fix it).

**Comment by oehme** [comment]
> for some use cases, putting a malformed jar on classpath is valid

Only on the runtime classpath though. On the compile classpath it would fail anyway when trying to compile.
