### ISSUE TITLE
codenarcMain and codenarcTest tasks fails in JAVA 9

### ISSUE THREAD

**Issue by modestukasai** [gradle/gradle#4219]
Hi,
I get bellow error. Please see [git repository](https://github.com/modestukasai/groovy-codenarc-java-9)

I am executing `.gradlew codenarcMain` or `.gradlew codenarcTest` with java 9 compiler.

`Execution failed for task ':codenarcMain'.`
`java.lang.NoClassDefFoundError: Unable to load class groovy.xml.jaxb.JaxbGroovyMethods due to missing dependency javax/xml/bind/JAXBContext`

**Comment by blindpirate** [comment]
You can `--add-modules` according to [this post](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j), or use following workaround:

```
dependencies {
    compile 'org.springframework.boot:spring-boot-starter'
    compile 'org.codehaus.groovy:groovy'

    testCompile "org.spockframework:spock-core:$spockVersion"
    testCompile "org.spockframework:spock-spring:$spockVersion"
    testCompile 'org.springframework.boot:spring-boot-starter-test'

    codenarc 'javax.xml.bind:jaxb-api:2.3.0', 'org.codenarc:CodeNarc:1.1' <- add this line
}
```
