### ISSUE TITLE
Default includes for cross-compiling native iOS project cause compilation failures

### ISSUE THREAD

**Issue by djinni-developer** [gradle/gradle#4234]
When using plugin "cpp", system includes are added to clang's compiler options, which results in failures if I try to build a native C++ library for iOS. It also fails to compile for macOS, but only if I also include the appropriate -isysroot as compiler.args.

### Expected Behavior
Since I am specifying -isysroot, I expect that it is used to figure out what the default system includes should be added.
OR
Since I am specifying -isysroot, I expect that gradle won't attempt to add default system includes to my compiler arguments.

### Current Behavior
I see the following compiler options, most of which are based on my configuration of the toolchain.
```
-x
c++
-c
-std=c++14
-O0
-g
-arch
arm64
-miphoneos-version-min=11.0
-isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk
-stdlib=libc++
-fPIC
-Wall
-Wextra
-I
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
-I
/usr/local/include
-I
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include
-I
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
-I
/usr/include
```
However, the additions to the include path are automatically added by gradle, and result in numerous errors. As an example:
```
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:629:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/typeinfo:61:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/exception:82:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cstdlib:86:
In file included from /usr/include/stdlib.h:63:
In file included from /usr/include/_types.h:27:
In file included from /usr/include/sys/_types.h:32:
/usr/include/sys/cdefs.h:761:2: error: Unsupported architecture
#error Unsupported architecture
```

### Context
I can no longer compile iOS projects using gradle native if I upgrade to latest gradle. 
Also, this problem occurs for macOS if I specify -isysroot for macOS, so although I can compile for macOS, I suspect I'm not getting the correct behaviour (as determined by sys root).

### Steps to Reproduce (for bugs)
The attached gradle project has a very simple C++ file (basically just includes memory header). It can be built using gradle 4.3, but it will fail on gradle 4.5.
[Archive.zip](https://github.com/gradle/gradle/files/1686431/Archive.zip)

### Your Environment
This problem is in 4.5, and is in nightly builds (last checked January 31, 2018).
The problem is not present in 4.4-20171031235950+0000 (but I am not sure which build breaks the behaviour).
Compiling on macOS Sierra with Xcode 9.2.

**Comment by djinni-developer** [comment]
Seems like Issue #3900 describes the same issue.

**Comment by lacasseio** [comment]
This issue is a duplication of https://github.com/gradle/gradle-native/issues/493. Thanks @djinni-developer for reporting this issue.
