### ISSUE TITLE
Build path for non root builds cannot be queried until part way through the build's lifecycle

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#4241]
Our data model has effectively evolved into a build invocation building a _tree_ (ish) of builds. There is a root build (i.e. the starting point for the build definition and our traditional understanding of a build), and included builds (composite build feature) and source dependencies are the child builds of the root. Each build in the tree has an identity, known as a build path, represented as a conventional Gradle path (e.g. `:foo`). The root build always has a path of `:`, while the child builds use the name of their root project to form their build path. This is problematic because this root project name is not known until after the project structure is finalised (i.e. settings script evaluated). By this time, plenty of interesting things have happened for this build that need to be attributed to it (i.e. as build operations). This is particularly problematic for build scans.

For example, we need to observe the evaluation of the settings script and its identity is fundamentally tied to the build. That is, the operation started notification for this operation effectively needs to communicate the build path.

Happily, we coincidentally sidestepped this problem with the current build scan approach. This _is_ going to break when we add support for composite includes as script plugins and support for source dependencies. Separately, it is impacting our (internal) build operation trace feature that we use for testing and reasoning about build operations at development time (we have a kludge workaround with [this](https://github.com/gradle/gradle/pull/4227)).

We will need to fix this properly soonish.

I can think of two potential solutions:

1. Use an identifier that we can calculate immediately, before needing to do anything interesting with the build
2. Use a temporary identifier until we can determine the “proper” one

(1) is much more appealing WRT implementation. It is far simpler. For example, we can base it on the name of the directory of the included build or identity of the source dependency. A potential downside is that this does not match user expectations.

(2) Would allow us to effectively keep the same user facing behaviour at the cost of significant complexity.

**Comment by adammurdoch** [comment]
This is very slowly making progress, through refactors to fix other issues.

**Comment by ldaley** [comment]
@adammurdoch can you please indicate what you are actually working towards.
