### ISSUE TITLE
StaticVersionComparator unsafe in TreeMap/TreeSet

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#4253]
We use this code internally in a project, and noticed that the last `return` causes versions that have the same parts, but different separators to be considered equal:

https://github.com/gradle/gradle/blob/d0247e9f637d7974381473168c91f3cbdfc40520/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/strategy/StaticVersionComparator.java#L84

That means that {{1.1.1}} and {{1.1-1}} are the same, and one would be missing from a sorted set w/ comparator. Unsure if this affects you use of version comparisons in core, but wanted to give you guys a heads up.

**Comment by bigdaz** [comment]
Thanks for reporting @DanielThomas : this doesn't affect the way we use `StaticVersionComparator`, but I've documented the limitation for now. That code looks quite suspect and I'd like to get it rewritten some day...
