### ISSUE TITLE
Gradle 3.5 Pick's up dependency version number rather then project version

### ISSUE THREAD

**Issue by pratikpparikh** [gradle/gradle#4257]
I have the project.version which is usually used when I do the build  and it generates the artifact appended by the project.verion something like "hibernate-validator-${project.version}.jar".  With the latest version, it is picking up version specified in plugin configuration.

**Comment by oehme** [comment]
Please attach a reproducible example project, including expected and actual behavior.

**Comment by ghale** [comment]
Closing this for now.  We can reopen if we have a reproducible example.
