### ISSUE TITLE
v4.5 Can not compile Sass: Failed to apply plugin [id 'com.github.robfletcher.compass']

### ISSUE THREAD

**Issue by hmortensen** [gradle/gradle#4259]
Upgraded from gradle 4.4 to 4.5 

### Expected Behavior
Command: gradlew tasks (or any other task)
Build succeeds with SASS compilation working.
Reversion to 4.4 and the problem goes away.

### Current Behavior
Command: gradlew tasks (or any other task)
Operation halts with following error message appears
* What went wrong:
A problem occurred evaluating project ':webapp'.
> Failed to apply plugin [id 'com.github.robfletcher.compass']
   > Could not create task of type 'CompassFork'.

### Context
Spring MVC Java project.
I can not do a build with 4.5 because the build halts at the error.

### Steps to Reproduce (for bugs)

apply plugin: 'com.github.robfletcher.compass'
buildscript {
    repositories {
        mavenCentral()
        // Sass plugin
        jcenter()
        maven { url 'http://dl.bintray.com/robfletcher/gradle-plugins' }
    }

    dependencies {
        classpath "com.github.robfletcher:compass-gradle-plugin:2.0.6"
    }
}

war {
    dependsOn compassCompile
    // etc
}

compass {
    sassDir = file('resources/scss')
    cssDir = file('src/main/webapp/resources/styles')
}

### Your Environment
Ubuntu 16.04
Linux 4.13.0-32-generic

**Comment by hmortensen** [comment]
Gradle  Info   : 
------------------------------------------------------------
Gradle 4.5
------------------------------------------------------------

Build time:   2018-01-24 17:04:52 UTC
Revision:     77d0ec90636f43669dc794ca17ef80dd65457bec

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Linux 4.13.0-32-generic amd64

**Comment by hmortensen** [comment]
[compass.dump.gz](https://github.com/gradle/gradle/files/1693052/compass.dump.gz)

**Comment by oehme** [comment]
The https://github.com/johnrengelman/gradle-processes plugin is using internal APIs. There is already a bug report for the plugin [here](https://github.com/johnrengelman/gradle-processes/issues/9). Please let the plugin author know that you are affected by this.
