### ISSUE TITLE
cannot clone from https://chromium.googlesource.com/external/github.com/gradle/gradle.git

### ISSUE THREAD

**Issue by leeshd** [gradle/gradle#4275]
### Steps to Reproduce (for bugs)

git  clone https://chromium.googlesource.com/external/github.com/gradle/gradle.git
Cloning into 'gradle'...
POST git-upload-pack (gzip 24751 to 11631 bytes)
fatal: git fetch_pack: expected ACK/NAK, got 'ERR want 91f691f5fe99c70dd3d757e8edbcfe75027f879c not valid'
fatal: The remote end hung up unexpectedly
### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Closing as this is a server error on the Chromium project and unrelated to Gradle.
