### ISSUE TITLE
Fix performance of attribute matching

### ISSUE THREAD

**Issue by melix** [gradle/gradle#4283]
### Context

This is a follow up of a discussion with @oehme about the performance attribute matching, that we had after [investigating the consequences of enabling improved POM support](https://github.com/gradle/gradle/issues/3723).

It turns out a significant part of the performance regression is related to variant selection (because we map Maven scopes to variants), rather than BOM support (aka, adding more pending dependencies).

The problem can be seen in this flame graph:

![selection_135](https://user-images.githubusercontent.com/316357/35874173-24b3464e-0b6c-11e8-91e0-122679644196.png)

It turns out that most of the selection time is spent in disambiguation. This happens because there are no requested attributes, so we end up with 2 Maven "variants", one for runtime and one for compile, and we try to select between them.

In practice, in most of the cases, the attribute sets are always the same, and the result of disambiguation is always the same too, which is why I implemented a [dirty hack](https://github.com/gradle/gradle/commit/99fd4e625da70cb1fc89b597b2181e1d6313eaea) to measure the impact of having a cache there. As expected, reducing the time spent in attribute matching dramatically reduces the impact of enabling the flag, from 12.5% overhead to just about 4%.

Before caching, there are however some things that we can do:

1. there's an [optimization in the attribute matcher](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/MultipleCandidateMatcher.java#L80), that avoids recomputing the coerced requested attributes, but no such optimization exists for the "extra" attributes
2. even if we do cache those values, they would still be recomputed for every component selection, which is very inefficient knowing that in most cases they will in practice be identical.

However, caching is not easy because:

a. the attribute matcher is at a global scope, so caching would introduce memory leaks if not done right
b. it has to be schema aware, which is not possible at the moment, because the `AttributeSelectionSchema` is unique for each selection, and is a merged schema of the producer and the consumer.

The second point can be mitigated by introducing some kind of "hash" of the schema, so that we avoid comparing the schemas themselves. @oehme suggested something like `getSchemaHash` or `addTo(Hasher)` on `AttributeSelectionSchema`, that could be used in the cache key.

The rationale is that in most cases the producer and the consumer will share the same schema.

**Comment by melix** [comment]
@bigdaz I assigned this to you, for discussion. This is going to have an impact on your work for attributes on dependencies.

**Comment by oehme** [comment]
Using a global cache that hashes the schema would lead to the most cache hits, but could also lead to expensive hash keys. I'd recommend trying out another approach as well:

You could put a cache into each schema instance (which a new cache per project for each build) and then cache the results at this lower level (the key would be expected and actual values and it would return a match or a disambiguation result). This has a much simpler lifecycle and cheaper cache keys. It would change the cost from O(number of dependencies) to O(number of projects), which might already be enough.

**Comment by ljacomet** [comment]
Work has happened in this area and performance has been improved.
