### ISSUE TITLE
Can't use `super` keyword in task constructor in build file

### ISSUE THREAD

**Issue by gerhard6** [gradle/gradle#4289]
see title
when removing the "super." prefix in the class definition, it works as expected
also, I removed the mentioned caches/4.5 directory manually, and the error occured again.

### Expected Behavior
bug report should not happen

### Current Behavior
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'bug'.
> Could not open proj remapped class cache for epqv1jockzcuc8qrfasdg5hmd (C:\Users\Gerhard.Langs\.gradle\caches\4.5\scripts-remapped\build_2bs22puqkh95asrhk0i917u7s\epqv1jockzcuc8qrfasdg5hmd\proje4eedbb0676df3aa4f2dfc4f6a234fd6).
   > Could not open proj generic class cache for build file 'C:\dev\jo-gradle\bug\build.gradle' (C:\Users\Gerhard.Langs\.gradle\caches\4.5\scripts\epqv1jockzcuc8qrfasdg5hmd\proj\proje4eedbb0676df3aa4f2dfc4f6a234fd6).
      > BUG! exception in phase 'class generation' in source unit '_BuildScript_' Unexpected super property set for:super.group

### Steps to Reproduce (for bugs)
just run gradle 4.5 without any parameters. with a build.gradle with this content:

class BaseAsTask extends DefaultTask {
    BaseAsTask()
    {
        super.group = "Appserver Management Tasks"
    }
}

### Your Environment

$ gw --version
Using gradle at '/cygdrive/c/dev/jo-gradle/bug/gradlew' to run buildfile '/cygdrive/c/dev/jo-gradle/bug/build.gradle':

------------------------------------------------------------
Gradle 4.5
------------------------------------------------------------

Build time:   2018-01-24 17:04:52 UTC
Revision:     77d0ec90636f43669dc794ca17ef80dd65457bec

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64

**Comment by blindpirate** [comment]
You can use `group="Appserver Management Tasks"` or `super.setGroup("Appserver Management Tasks")` as a workaround. This is a Groovy bug and you can track the process there: https://issues.apache.org/jira/browse/GROOVY-8474
