### ISSUE TITLE
Cannot download dependencies from http://bits.netbeans.org/nexus/content/groups/netbeans

### ISSUE THREAD

**Issue by kelemen** [gradle/gradle#4297]
Gradle since version 4.1 fails to download (some) dependencies from http://bits.netbeans.org/nexus/content/groups/netbeans

I'm not behind any proxy and Gradle 4.0.2 has no problem downloading the dependencies. Also, I can download the failing artifacts myself by any other tools I have tried.

### Expected Behavior

Successful dependency resolution.

### Current Behavior

Fails with:

> Could not resolve org.netbeans.api:org-netbeans-api-templates:RELEASE81.
>   Could not get resource 'http://bits.netbeans.org/nexus/content/groups/netbeans/org/netbeans/api/org-netbeans-api-templates/RELEASE81/org-netbeans-api-templates-RELEASE81.pom'.
>      Could not HEAD 'http://bits.netbeans.org/nexus/content/groups/netbeans/org/netbeans/api/org-netbeans-api-templates/RELEASE81/org-netbeans-api-templates-RELEASE81.pom'.
>         Connection reset

### Steps to Reproduce (for bugs)

My project: https://github.com/kelemen/netbeans-gradle-project can be used to reproduce the issue but the version of gradle in *gradle-wrapper.properties* should be changed.

Or you can just add the repository "http://bits.netbeans.org/nexus/content/groups/netbeans" and try resolve "org.netbeans.api:org-netbeans-api-templates:RELEASE81".

**Comment by blindpirate** [comment]
Could you provide more details about reproduce sample? Which command can trigger this issue? I tried `gradle build` with `4.2` and didn't encounter any problems at all. Also, it would be good to run with `--stacktrace` to see the entire stacktrace, not only a few lines saying `Connection reset`.

**Comment by kelemen** [comment]
The `build` task should trigger the issue (it triggers it for me) for the *master* branch (does not for the *nb9* branch). I'm using JDK 1.8.0_92 and I'm trying it by replacing the URL in */gradle/wrapper/gradle-wrapper.properties*, then use the Gradle wrapper. I have tried it again and building still fails to me. Anyway, any task triggering dependency resolution should run into the issue (so, I guess gradlew :netbeans-gradle-plugin:compileJava` is the minimum you can do). I have tried this using both the *gradlew* script and running tasks from the Tooling API (fails the same way).

**Comment by big-guy** [comment]
Please try upgrading to 5.x and reopen this issue if you're still seeing it. Thanks!
