### ISSUE TITLE
Wrong newline handling on simple terminals (compiler output is stuck at the end of previous line)

### ISSUE THREAD

**Issue by Alexander--** [gradle/gradle#4306]
This issue applies only to fallback console output mode, used for unrecognized terminal models. Rich mode with interactive animated progress bars does not suffer from this issue.

Expected behavior: Gradle should emit newlines at the end of line whenever it prints to console.

Observed behavior: newlines are emitted *at the beginning* of each logged line, which causes output from external sources to stick onto the same line:

<pre>
:app:generateDebugSources
:compiler:compileJava<strong>warning: [options] bootstrap class path not set in conjunction with -source 1.7</strong>

:compiler:processResources NO-SOURCE
:compiler:classes
:compiler:jar
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac<strong>Note:</strong>
Note: APT plugin says: Started new scan at 2018-02-09
Note: APT Linker says: Finished scan after 1929ms
Note: APT Linker says: Empty working set!
</pre>

Note the bolded text, — it clearly should not be there.

### Context
This issue is reproducible in IntelliJ Idea terminal, Travis CI logs and probably dozen of other places. It obfuscates Gradle output, making it harder to read, and ultimately harder to debug.

### Steps to Reproduce (for bugs)
Try to compile *any* java project, that produces warnings.

### Your Environment
Gradle 4.5.1
Groovy 2.4.12
Arch Linux

**Comment by chrislong** [comment]
I ran into this, too. For now, this works around it for me:

```
compileJava {
    doFirst {
        logger.lifecycle('')
    }
}
```

And there's probably a way to apply it to all compile tasks.

**Comment by Alexander--** [comment]
@chrislong This is a nice attempt, but it does not really solve the underlying problem.

I suspect, that the reason, why this odd behavior was introduced is desire to guarantee a line break before each Gradle's line, while avoiding excessive line breaks. Putting a line break at the end of line can lead to ugly output when output from multiple parallel sources interleaves.

Here is my take: replace entire stdout of Gradle process with pipe and have a Thread process the other side of pipe to strip excessive line breaks. This way Gradle should be able emit line breaks on both sides of line without worrying about wasting screen space.

**Comment by ghale** [comment]
Starting with Gradle 4.7, the "plain" console also groups task output with the task that produces it, rather than interleaving it.  I'm pretty sure that fixes this issue.  We can reopen if there is some scenario where this still occurs.
