### ISSUE TITLE
Disable boolean `@Option`s from the command line

### ISSUE THREAD

**Issue by acourtneybrown** [gradle/gradle#4311]
### Expected Behavior

Boolean-valued command line flags for tasks should allow the option to be disabled.

### Current Behavior

The `@Option(option=<name>)` annotation on a boolean field or method allows the value to be set to `true` by including `--<name>` on the command line.  Boolean-valued flags are explicitly not able to provide a value, eg: `--<name>=true` or `--<name>=false` fails with a message like:

```
FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :test from command line.
> Command-line option '--<name>' does not take an argument.
```

If the option is configurable from both the build file and the command line, it is not directly possible to enable a flag in the build file, but disable it per build from the command line.

**Comment by kheerthi** [comment]
Currently if a boolean variable is declared as false plugin, it can be enabled by passing --variable. However, since the variable needs to be true in most case and needs to be disabled on demand. How can this operation be performed from a consuming project?

**Comment by szpak** [comment]
I ran into that trying to override a boolean property set to `true` in `build.gradle` via `@Option`.

**Comment by szpak** [comment]
I think, there is still no way to achieve that in Gradle 6.6
