### ISSUE TITLE
Never triggered  buildStarted in custom BuildListener (BuildAdapter)

### ISSUE THREAD

**Issue by PascalKern** [gradle/gradle#4315]
I tried all I know and I found on the net to get the `buildStarted()` method called in my custom BuildListener. The behaviour of the BuildListener is of course different depending where the listener is added to gradle (ie. in build.gradle or in a gradle init script). But nether way I get the method called.
All other methods in the BuildListener where called as expected in the expected point in execution time.

For my tests I used the bellow class with a different "message" prefix to separate them. I added the class in ether a build script _and_ a init script (selects by the `--init-script` switch):
#### Content of `listeners.gradle` (and added to `listeners.initd.gradle` too):
```groovy
class MyBuildListener extends org.gradle.BuildAdapter {
    
    def buildListener = [:]
    
    void buildFinished(BuildResult result) {
        buildListener.buildFinished = "INIT.D +++ Finished with action $result.action"
        displayExecuteBuildListeners()
    }
    
    def displayExecuteBuildListeners() {
        println buildListener.collect { method, message ->  "\t${method.padRight(24)} => $message" }.join("\n")
        println "\t${'-'*64}"
    }

    void buildStarted(Gradle gradle) { buildListener.buildStarted = "INIT.D +++ Build started..." }    

    void projectsEvaluated(Gradle gradle) { buildListener.projectsEvaluated = "INIT.D +++ Projects evaluated..." }

    void projectsLoaded(Gradle gradle) { buildListener.projectsLoaded = "INIT.D +++ Projects loaded..." }
    
    void settingsEvaluated(Settings settings) { buildListener.settingsEvaluated = "INIT.D +++ Settings evaluated from $settings.rootDir" }
}

gradle.addBuildListener(new MyBuildListener())
```

On the other side I cloned the Gradle repository. Checked out tag v4.2.1 and run the `DefaultGradleSpec` test within IntelliJ and all tests pass (as expected). So what do I wrong?

### Expected Behavior

I would expect that the final output does contain the line: `buildStarted             => INIT.D +++ Build started...`.

```
$ gradle --init-script listeners.initd.gradle -S clean build

BUILD SUCCESSFUL in 19s
12 actionable tasks: 10 executed, 2 up-to-date
        settingsEvaluated        => INIT.D +++ Settings evaluated from /Users/pkern/Google Drive/GradleBuildListenerExample
        buildStarted             => INIT.D +++ Build started...
        projectsLoaded           => INIT.D +++ Projects loaded...
        projectsEvaluated        => INIT.D +++ Projects evaluated...
        buildFinished            => INIT.D +++ Finished with action Build
        ----------------------------------------------------------------
        projectsEvaluated        => BUILD  +++ Projects evaluated...
        buildFinished            => BUILD  +++ Finished with action Build
        ----------------------------------------------------------------
```

### Current Behavior

All went as almost expected except that there is no output line dedicating that the `buildStarted` method was called!

```
$ gradle --init-script listeners.initd.gradle -S clean build

BUILD SUCCESSFUL in 19s
12 actionable tasks: 10 executed, 2 up-to-date
        settingsEvaluated        => INIT.D +++ Settings evaluated from /Users/pkern/Google Drive/GradleBuildListenerExample
        projectsLoaded           => INIT.D +++ Projects loaded...
        projectsEvaluated        => INIT.D +++ Projects evaluated...
        buildFinished            => INIT.D +++ Finished with action Build
        ----------------------------------------------------------------
        projectsEvaluated        => BUILD  +++ Projects evaluated...
        buildFinished            => BUILD  +++ Finished with action Build
        ----------------------------------------------------------------
```

### Context

There are different things I try to do with the `buildStarted` listener. One of it is to trigger the execution of a second tool as soon as the build starts to do some work. 
For example:
- Update or init some subprojects kept in a GIT submodule which may contain further build scripts.
- "Decorate" the `org.gradle.api.internal.project.DefaultProject` ie. the `findProperty()` method to also search the System for requested property. Or add some more _global_ methods to the class with Groovy metaclass feature.
Of course this is just for convenient and I know there are other ways like usage of the extension on Project or to decorate use the `ProjectEvaluationListener` and decorate on the instance itself than on the class.

_But I'm almost more curious what I missed or what I'm doing wrong to access this listener._ :-)

### Steps to Reproduce (for bugs)

I attached a little example project (reduction of a sample project from the Gradle docs' repo). Just extract the content an run it with:
`gradle --init-script listeners.initd.gradle -S clean build`

Hoppe this is what you need to reproduce my issue. If you need more just drop my a message.

[GradleBuildListenerExample.zip](https://github.com/gradle/gradle/files/1713424/GradleBuildListenerExample.zip)

### Your Environment

```
$ gradle -v
------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1114

$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by oehme** [comment]
There is no way for users to hook in before the build starts, this method is mostly used by internal listeners in Gradle. The build starts before any scripts are evaluated. 

What kind of tool are you trying to call, what's the use case? "As soon as Gradle does some work" is a bit vague. The real work only starts during task execution.

**Comment by PascalKern** [comment]
Thanks for the reply.
It does in deed already answer my main question about the usage meaning of this API method. 

I'm still a bit curious why such a method exist and doesn't contain any comment about the meaning of almost only internal usage for this method on the BuildListener. I understand of course that the method is called very, very early in the build as I would expect by it's name. :-)

About the a bit vague use case see my edits above. But as I denoted in this comment my main question about the usage of this method is already answered.
If you could tell me if a plugin implementation would have access to this method or if there are any other potential ways to get a custom closure executed somehow with this method this question (issue) can be closed.

Many thanks anyway for your time.

**Comment by oehme** [comment]
I don't think there is any way for non-Gradle code to hook into buildStarted. For your use case above I think `settingsEvaluated` should work as well. Or you could just do the work right in your init script (i.e. without waiting for a callback), since that is a s close as you'll get to the start of the build.

**Comment by oehme** [comment]
If it belongs to a specific project, then I'd just run the code right at the start of your settings.gradle script. I had assumed you were trying to do this for multiple different projects.

**Comment by PascalKern** [comment]
You assumed right. Finally my code must work for single as well as for multiproject build. But so far I can see to place the code in the `settings.gradle` will work for both and therefor I'm quiet happy.

Hope I'll find soon time to verify this all (it's mostly used for a build at my company) and report back if something doesn't work. But I'm quiet sure I have now enough ways to work around.

Again. Many thanks for all your time.
