### ISSUE TITLE
Local `file` repository resolve is slow due to re-parsing unchanged descriptor files

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#4322]
When a repository is configured with a local `file` URL, then Gradle bypasses the usual module descriptor cache in order to always provide an up-to-date view of the files in the repository. This makes it easy for users to make changes to their local file repository and have those immediately available to Gradle.

Since local filesystem access is generally much faster than remote repository access, caching was considered unnecessary for local file repositories. However, performance tests reveal that resolving from a local file repository takes twice the time of resolving from a local HTTP repository: one culprit is the fact that we re-parse the Ivy/POM descriptor files on every resolve, even when they have not changed. Reading parsed metadata from the cache is much faster than re-parsing the original metadata files.

### Expected Behavior

When using a local file repository, the performance will not be slower than a local HTTP repository.

### Current Behavior

Resolving from a local file repository for a sample project takes _more than twice the time_ as resolving the same project from a local HTTP repository.

### Steps to Reproduce (for bugs)

Compare the time take for the same resolve from an [HTTP repository](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/10923127:id/report-performance-performance-tests.zip%21/report/tests/resolve-large-dependency-graph-%28advanced-pom-support-%3D-false%2C-parallel-%3D-false%29.html) and a [local file repository](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/10923127:id/report-performance-performance-tests.zip%21/report/tests/resolve-large-dependency-graph-from-file-repo.html).

**Comment by oehme** [comment]
See this issue for how severe the result can be: https://github.com/gradle/gradle/issues/6171
