### ISSUE TITLE
User Guide still says "Rule based model configuration is the future of Gradle." despite it being deprecated

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle#4327]
### Expected Behavior

In https://blog.gradle.org/state-and-future-of-the-gradle-software-model it is said that
> The rule engine that was part of the Software Model will be deprecated.
and that, basically, the "software model" will not be continued and rather its features will be backported into the existing plugins.

I'd expect documentation (User Guide) to match, at least for versions released after this statement.

### Current Behavior

https://docs.gradle.org/4.5.1/userguide/java_software.html says:
> The Java software plugins are intended to replace the Java plugin, and leverage the Gradle software model […]

https://docs.gradle.org/4.5.1/userguide/software_model.html#sec:limitations_and_future_direction says:
> Rule based model configuration is the future of Gradle.

### Context

This came up in a discussion about the future of GWT, and prototyping a Gradle plugin for GWT 3, where one of the contributors brought the idea that rule-based model configuration was the future of Gradle, and we could leverage it, yada yada, and he had already started work using it (afaik, mostly around variant-aware dependency resolution which, iiuc, will come to Gradle "standard plugins" later this year).

This rang a bell as I had read the blog post about it being deprecated; and he pointed me to the documentation still saying it is, literally, "the future of Gradle".

He's now reverting the work he had started. :man_shrugging:

**Comment by oehme** [comment]
@bmuschko @eriwen This should be very high on our change list :)
