### ISSUE TITLE
Play's runPlayBinary task Java 9 issues 

### ISSUE THREAD

**Issue by dforsl** [gradle/gradle#4339]
### Expected Behavior
The Play plugin provides the task *runPlayBinary* to run the app whilst developing. Although it's a little unclear what Play's support for Java 9 currently is, it does at least function to some extent and will hopefully be fully supported not too far ahead. Hence, it would be great if *runPlayBinary* worked also with Java 9 as it's a great tool during development.

### Current Behavior
When using Java 9 with a database which requires *java.sql.Connection* and *javax/sql/DataSource* to be available, errors such as *NoClassDefFoundError: java/sql/Connection* are being thrown. However, everything compiled just fine and a corresponding distribution of the app runs without problem.

### Steps to Reproduce (for bugs)
1. Create a Play-project which makes use of a database; the default H2-db is sufficient.
Play model config:
`
model {
    components {
        play {
            platform play: '2.6.10', scala: '2.12', java: '1.9'
            injectedRoutesGenerator = true
        }
    }
}`

2. run *runPlayBinary*

### Your Environment
Java 9.0.4+11
Scala 2.12.4

> ------------------------------------------------------------
>Gradle 4.5
>------------------------------------------------------------
>
>Build time:   2018-01-24 17:04:52 UTC
>Revision:     77d0ec90636f43669dc794ca17ef80dd65457bec
>
>Groovy:       2.4.12
>Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
>JVM:          9.0.4 (Oracle Corporation 9.0.4+11)
>OS:           Linux 4.13.0-31-generic amd64

**Comment by dforsl** [comment]
Not sure if this is relevant, but I've seen a few examples where this type of issue with scala was supposedly worked around with JAVA_OPTIONS and the add-modules flag.

**Comment by dforsl** [comment]
I also attempted to configure the fork options, with the hopes that it would be passed to to dev-server, but without success.

`tasks.withType(PlayRun) {
    forkOptions.jvmArgs = ['--add-modules', 'java.sql']
}`

**Comment by tmackenzie** [comment]
I'm interested in getting Play `2.6.20` configured with JDK 9. If I coded it would this feature be welcome?
