### ISSUE TITLE
Load aws credentials stored in `~/.aws/` using my own profile name

### ISSUE THREAD

**Issue by Gujarats** [gradle/gradle#4341]
### Expected Behavior
I'm trying to load `aws credentials` from default config file `~/.aws/`. using this code snippet : 
``` gradle
    repositories {
        maven {
            url "${internal_s3_url}"
            authentication {
                awsIm(AwsImAuthentication)
            }
        }
    }
```
And here is my `credential` looks like : 
```
[test-gujarat]
aws_access_key_id =~~
aws_secret_access_key =~~
[gujarat.santana]
aws_access_key_id =~~
aws_secret_access_key = ~~
```
I know if I changed the profile `gujarat.santana` to `default` it will load the access_key and secret_key. Now Is it possible not to use `default` profile and using my own name profile? if Possible, how do I do that ?  

### Current Behavior
Currently I got this error  `Unable to load AWS credentials from any provider in the chain` after running `gradle build`.

### Context
I need to use another profile name instead of using `default` profile since I have many access_key and secret_key in my local. The reason why I don't want to use `default` is because I would like to make my `default` profile for my admin user in my aws account and use another profile to for another access and permission.

### Steps to Reproduce (for bugs)
If you have your S3 bucket in aws and IAM user in aws which has access_key and secret_key then put it in your `~/.aws/credentials`. and load the profile name with your own name not `default` profile. 

### Your Environment
```
------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.4.0-109-generic amd64
```

**Comment by blindpirate** [comment]
Well, AFAIK the aws configuration file is read by [AWS-SDK](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default) and there's no special setting on Gradle's side to specify a "user". Currently a workaround could be Environment variables/Java system properties (see [here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default)) or even parse the `~/.aws/credentials` youself.

**Comment by Gujarats** [comment]
Okay I see now, thanks for the info. I would to see this new feature can be easily called like for example 
```gradle
repositories {
        maven {
            url "${internal_s3_url}"
            authentication {
                awsIm(YOUR_PROFILE_NAME)
            }
        }
    }
```
Or maybe you have another suggestion since I don't really like to see the previous one like `awsIm(AwsImAuthentication)` because I don't see it really matter to call the `AwsImAuthentication` inside `awsIm()`. But still it is a suggestion from me.
