### ISSUE TITLE
Allow opting out of plugin dependency substitution in a composite

### ISSUE THREAD

**Issue by adrian-baker** [gradle/gradle#4343]
In a composite build, if I include a build with the same group/name coordinates as a dependency of a 
plugin (eg a common open source library), it seems gradle attempts to substitute this include not only when resolving build dependencies for a Java project, but also when resolving dependencies of 3rd party gradle plugins.

The build at https://github.com/adrian-baker/gradle-scratchpad/tree/master/bug-composite-include-pollutes-plugin is a simple example showing the problem we hit in our build. We have a local fork of an Apache project (org.apache.jackrabbit:jackrabbit-spi2dav) which gets compiled and built into our application. It also happens to be an indirect dependency of an unrelated plugin (com.cognifide.gradle:aem-plugin).

The sample build fails because the included empty project doesn't match what the plugin expects, whereas I would expect the plugin to be completely unaffected:

```
A problem occurred configuring root project 'bug-composite-include-pollutes-plugin'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.apache.jackrabbit:jackrabbit-spi2dav:2.9.0.
     Required by:
         project : > com.cognifide.gradle:aem-plugin:2.0.15 > org.apache.jackrabbit.vault:vault-cli:3.1.24 > org.apache.jackrabbit.vault:vault-davex:3.1.24
      > Org.apache.jackrabbit.vault:vault-davex:3.1.24 declares a dependency from configuration 'runtime' to configuration 'runtime' which is not declared in the descriptor for project :jackrabbit-spi2dav.
```

If this is a deliberate design choice rather than just a bug, I believe it's quite a problematic one, as it essentially precludes ever safely using anything other than privately namespaced group/name includes, to prevent any chance of accidentally overlapping with the plugin dependency tree, or vice versa, which is normally otherwise entirely separate. The fork of jackrabbit in our case was absolutely not intended to affect any plugins, until this issue occurred, I was happily ignorant it was even used indirectly as a plugin dependency.

If this is required for supporting including custom plugins via composite builds (a good feature), then perhaps includes for the purpose of the plugin dependencies should be declared differently, to separate them - just as the buildscript dependencies block cannot interfere with the project dependencies in a Java project.

Incidentially, this was noticed by us when we attempted to upgrade to https://plugins.gradle.org/plugin/com.gradle.build-scan/1.12, which initially confused me with this error - confusing, because we didn't think we were including any plugins with composite builds:

> Build scans are not supported for this build due to a build plugin composite substitution.

**Comment by oehme** [comment]
This works as designed, but I understand your use case. I've rephrased it as a feature request to opt in (or out) of plugin classpath substitution.

**Comment by 4n00p** [comment]
@adrian-baker Forgive me if I’m making a mistake, but I believe I encountered the same problem as you. Have you tried changing your dependencies block as described here:    
https://stackoverflow.com/questions/33853881/gradle-could-not-resolve-all-dependencies-for-configuration-compile

**Comment by JojOatXGME** [comment]
I had the same problem with an in-house plugin and library today. Is there a workaround? Can I somehow prevent the substitution or is it just not possible for now?
