### ISSUE TITLE
gradle init > is too old under 4.5.1

### ISSUE THREAD

**Issue by MartinX3** [gradle/gradle#4345]
`gradle init` is nice to init a gradle project or import a maven project.

But it generates a build.gradle with old things.

- Java is set to 1.5, instead of 1.8
- apply plugin is used, instead of plugins {}
- the plugin "applications" should be included into a java project
- a "jar" task should be included

As a newbie, I would think that the latest gradle version wouldn't give me a build.gradle with deprecated stuff.

**Comment by oehme** [comment]
> Java is set to 1.5, instead of 1.8

That's bad indeed.

> apply plugin is used, instead of plugins {}

Good point

> the plugin "applications" should be included into a java project

Only if you use `--type java-application`

> a "jar" task should be included

That's part of the java plugin already. 

Would you be interested in providing a pull request for the first two issues?

**Comment by MartinX3** [comment]
Thank you very much for the fast response and yes, of course, I will try to create one PR. :-)

>>    a "jar" task should be included
> 
> That's part of the java plugin already.

Oh, sorry, I meaned a prefilled task, like
```gradle
jar {
    manifest {
        attributes(
                'Class-Path': configurations.compile.collect { it.getName() }.join(' '),
                'Main-Class': 'hello.world'
        )
    }
}
```

**Comment by oehme** [comment]
I don't think we should include this in the template, as executable JARs not very common. And if you really want one, there are plugins out there that build one for you. Also the code above contains a common anti-pattern: It resolves dependencies at configuration time, leading to performance issues and ordering bugs.

**Comment by MartinX3** [comment]
Aye aye Sir! :-)

**Comment by oehme** [comment]
I can warmly recommend the [Shadow](https://github.com/johnrengelman/shadow) plugin.

**Comment by MartinX3** [comment]
Thank you very much.
It works like a charm, I don't need to configure it and don't need this inefficient part code anymore! :-)
