### ISSUE TITLE
De-incubate continuous build

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#4355]
The continuous build API hasn't really changed in years.

I vote that we "promote" it in Gradle 5.0, along with a bunch of other obviously stable-but-not-perfect stuff.

### Expected Behavior
Continuous build should no longer be marked incubating in docs or in Gradle CLI.

**Comment by marcphilipp** [comment]
I'm moving this to 5.1.

@eriwen Is that ok with you?

**Comment by eriwen** [comment]
Yeah, we can even take off the milestone... just a travesty this hasn't been promoted yet.

**Comment by oehme** [comment]
@wolfs Did you de-incubate this already?

**Comment by wolfs** [comment]
@oehme Yes, I did. Closing.
