### ISSUE TITLE
Gradle JUnit 5 can't recognize Vintage descriptor in some cases

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#4358]
Let's say we have the spock tests:

```
abstract class Base extends Specification {
    def ok() {
        expect: "success"
    }
}

class Sub extends Base {
    def ok() {
        expect: "success"
    }
}
```

JUnit Vintage engine will create following test descriptors:

- `ok(Sub)[0]`
- `ok(Sub)[1]`

But these descriptors can't be recognized by [JUnitTestEventAdapter](https://github.com/gradle/gradle/blob/214617efc7636c1221af2d5d0cce620b5c975e76/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestEventAdapter.java#L32). This results in incorrect class name/method name and test hangs.

**Comment by sbrannen** [comment]
Are you saying that two test methods execute when using JUnit Vintage, but only one test executes when using JUnit 4.12 stand-alone?

If so, then that would be a bug in Vintage.

**Comment by blindpirate** [comment]
@sbrannen Thanks for your attention.

No, 2 tests are executed when using JUnit 4.12 as well as Vintage. The problem is, for the example above, JUnit 4.12 will generate 2 descriptors with same name (`ok(Sub)`), but Vintage will generate 2 descriptors with different name (`ok(Sub)[0]`/`ok(Sub)[1]`). I think it's reasonable for Vintage to emit 2 descriptors with different name.

**Comment by sbrannen** [comment]
OK.

Thanks for the explanation.

I still think it's a bit odd that an overridden test method is executed, since that is not how JUnit 4, JUnit Jupiter, TestNG, etc. work, but... I suppose this behavior is a Spock thing.

**Comment by blindpirate** [comment]
Yes, I was a bit surprised at first sight as well. Actually this is not an "overriding", which means compiler will complain if you mark it with `@Override`: https://stackoverflow.com/questions/47492773/override-test-in-spock

**Comment by sbrannen** [comment]
Thanks, I came to the same conclusion after having found this: https://stackoverflow.com/a/22970970/388980

Spock _magic_... 😉
