### ISSUE TITLE
Groovy lib dependency doesn't allow the -grooid classifier

### ISSUE THREAD

**Issue by Shockah** [gradle/gradle#4360]
Basically it's this issue:
https://discuss.gradle.org/t/groovy-plugin-dependency-with-classifier-seems-to-break-resolution/13519
https://issues.gradle.org/browse/GRADLE-3377

### Expected Behavior
Specifying a dependency like `compile "org.codehaus.groovy:groovy:2.4.13:grooid"` should properly resolve.

### Current Behavior
Right now the `:grooid` classifier part gets treated as part of the version.

### Context
I hit this issue when trying to include Groovy in an iOS (via RoboVM) project.

### Steps to Reproduce (for bugs)
An example buildscript from the first link:
```
apply plugin: 'java'
apply plugin: 'groovy'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy:2.4.4:grooid'
}
```

**Comment by jjohannes** [comment]
@Shockah this is specific to the 'groovy' plugin. Your PR does not fully fix the problem. I will add some comments there if you want to follow up. Otherwise, have you tried using the https://github.com/groovy/groovy-android-gradle-plugin instead or does that not work in the RoboVM context?
