### ISSUE TITLE
Gradle 4.5 C++ rebuild with no changes performs worse than Gradle 4.3 on a "larger" project

### ISSUE THREAD

**Issue by javaJake** [gradle/gradle#4369]
I understand Gradle is trying to make a Java-based solution, but as of 4.5, my C++ build times have gotten significantly worse. I have ccache wired in so it handles caching C++ builds for me, and it's very quick and transparent. Gradle 4.5 now apparently hashes every single file every single build, causing a rebuild of an already built project to take minutes. Before, it was roughly 30 seconds.

I think there are potentially two issues here:

1. The hashing is not done in parallel, so my 7 other cores are idling while Java spins on 1 core.
2. The hashing is done every run. It should only need to hash when it suspects the file has changed.

Unfortunately, if I turn off build caching, it turns it off Gradle-wide, which means I lose the caching benefits for Java.

I personally think it'd be smarter to adopt the methods that ccache and clcache use to check for changed code. Those use the preprocessor and hash the output to check for rebuilds (or even older cached builds).

### Expected Behavior
Gradle 4.5 should decrease, not increase, build times. Gradle should use all my cores to hash. Gradle should only hash when it suspects file changes.

### Current Behavior
Gradle 4.5 increased my build time by minutes. Gradle uses one core to hash. Gradle hashes every file every build.

### Context
I'm building a C/C++ project with around a dozen modules, into debug binaries that end up around 600MB. I suspect Gradle has only ever been tested with smaller C/C++ projects.

### Your Environment
Gradle 4.5 on either CentOS 6, or Windows 7, all 64-bit, running with gcc 4.9.4 or VS 2013.

**Comment by javaJake** [comment]
It appears I jumped to conclusions. I turned the build cache off and still see minutes of time going to reading header files that haven't changed. I wonder if this has to do with the newer header processing code.

**Comment by lptr** [comment]
Thanks for reporting this. Can you please change the title of the issue to reflect your latest findings?

**Comment by javaJake** [comment]
I made the title describe the symptom instead of suggesting the problem this time.

**Comment by oehme** [comment]
@lacasseio this is likely the same regression you are currently investigating.

**Comment by lacasseio** [comment]
It looks like it's related to a regression we are hunting down in Gradle Native with regards to build analysis. Based on our initial analysis it seems to be related to projects with lots of headers that contains macro includes (i.e. `#include SOME_MACRO`), typically exposed through dependencies on Boost and the like. We are working on a fix for Gradle 4.7.

**Comment by big-guy** [comment]
Issue moved to [gradle/gradle-native #502](https://github.com/gradle/gradle-native/issues/502) via [**ZenHub**](https://www.zenhub.com/)

**Comment by interviewQ** [comment]
Has this issue been fixed in Gradle 4.7 ? I am seeing this issue in gradle 4.6 and deciding if upgrading to 4.7 will help.

**Comment by adammurdoch** [comment]
There are a bunch of C++ compile performance improvements in 4.8-rc-1. These may or may not improve your build, but we are seeing builds that are now much faster with 4.8-rc-1 than they were with 4.2 or any other release).

There aren't any major improvements between 4.6 and 4.7, however, so I'd suggest giving 4.8 a try instead of 4.7.
