### ISSUE TITLE
Composite build failures are reported incorrectly for dependency on different subprojects of an included build

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#4370]
When a multiproject included build provides multiple artifact dependencies in a composite build, then a failure to build _one_ of the subprojects of the included build can be reported multiple times.  This is because the tasks to build the different subprojects are run in a single execution of the included build, and any build failure is attributed to each of the tasks requested.

### Expected Behavior

If an included build provides multiple artifacts via multiple subprojects, a failure in one subproject will not prevent other subprojects from building, and will not be reported multiple times.

One possible solution would be to execute the included build with `--continue`, and collect failures on a per-task basis.

### Current Behavior

A failure in one subproject of an included build may be attributed to other subprojects in the same build, and reported multiple times.

Test case marked as `@ToBeImplemented`: 
https://github.com/gradle/gradle/blob/d6de054a8786940a89992dc1bab256c5eefe70e5/subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/CompositeBuildDependencyArtifactsIntegrationTest.groovy#L644-L677

### Steps to Reproduce (for bugs)

Execute `gradle build` with this repo: https://github.com/bigdaz/gradle-4370

 * Build scan URL: 
https://scans.gradle.com/s/irvllppsclvko/console-log#L14

Note the duplicate exception in the console output.

**Comment by adammurdoch** [comment]
This is fixed via #5474 and #5418 (and #5503).
