### ISSUE TITLE
Project.getProperties() fails when the project directory does not exist

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#4376]
For some kinds of project layouts, the concept of a project directory doesn't really make sense. For example, when I have a build that produces several different libraries and uses the Swift Package Manager convention, the pieces of each library are distributed across a bunch of different top level directories. It is not unreasonable to model this as a multi-project Gradle build, with each project producing a separate library and the project directory of each project (other than the root project) pointing to some directory that doesn't exist.

In this case, calls to `Project.getProperties()` fail, indirectly because `getAnt()` fails because the project directory does not exist.

This leads to confusion as sometimes the project directory may exist and sometimes not. For example when I'm using a Git repository an empty project directory is not visible to someone that clones the repo, so my build logic may accidentally work in my clone but fail everywhere else. Or some tasks may implicitly create the project directory (say by creating the build directory) so that the build works by accident when I have already run those task locally but may fail elsewhere.

### Expected Behavior

Gradle should either always succeed or always fail when the project directory does not exist.

These methods should either:
- not fail when the project directory does not exist
- or we should not support a missing project directory and fail earlier in configuration when the project directory does not exist
- or we should create the project directory if missing.

### Current Behavior

The user sometimes receives a confusing error message when the project directory does not exist, and sometimes does not receive any error message.

**Comment by oehme** [comment]
I think `Project#getProperties()` is confusing and we should remove it or change it's behavior. Who would actually expect it to contain the `AntBuilder` and all other services that have a getter?

After talking to some users with similar problems (#3959), it usually turns out they only wanted the extra properties.
