### ISSUE TITLE
Show actionable message for deprecation warnings summary

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#4379]
When a build uses deprecated features, we print the following message at the end:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings
```

I think most people either want to take no action on the warning or see all of the warnings.
In order to find out that one should use `--warning-mode all` to see the warnings one would need to go the the webpage (maybe difficult in restricted environments), read through quite some text and then find out what the command line option is. This seems pretty heavy-weight

### Expected Behavior
The deprecation summary reads like this:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use `--warning-mode all` to see the deprecation warnings.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings
```
We could even drop the link to the docs altogether.

### Current Behavior
`--warning-mode all` is not mentioned in the summary message.

### Further suggestions
Maybe we should print the summary line when `--warning-mode all` is enabled, too. This would allow as to add information like:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
If you have a use case for one of the deprecated features please open an issue on https://github.com/gradle/gradle.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by wolfs** [comment]
@eriwen @oehme @blindpirate What is your take on this?

**Comment by eriwen** [comment]
Hm, I don't think we can cover all the options on the CLI (therefore I think the URL should stay, among other reasons), but I do like the convenience of having a common option displayed. 

My only concern with this is verbosity, though a weak concern.

**Comment by big-guy** [comment]
We did this a long time ago
