### ISSUE TITLE
Display the end time of the build

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/gradle#4382]
### Expected Behavior
Display the current time once the build has finished

### Current Behavior
At the moment we only get a duration displayed. Sometimes it is useful to know when the build finished.

### Context
Often you will kick off a build and come back to it some time later. When that happens you may be unsure if you have changed the code or not since the build finished. Having a time stamp displayed at the end of the build will help with that.

**Comment by oehme** [comment]
You can do this with a [build listener](https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html#org.gradle.api.invocation.Gradle:buildFinished(org.gradle.api.Action)) and put that into an init script so it applies to all builds on your machine.
