### ISSUE TITLE
Remove aborted attempt at `CacheControl` DSL from public API

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#4390]
Many years ago I started working on an API to allow fine-grained control over caching in our dependency cache: [org.gradle.api.artifacts.cache.ResolutionRules](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/cache/ResolutionRules.java#L26-L26). This is a public `@Incubating` API, but can only be accessed via `ResolutionStrategyInternal.getResolutionRules()`.

In theory, this API would permit per-module configuration of cache-expiry.

There are a number of issues with this API:
- It is imperative rather than declarative, so it's harder for Gradle to make smart choices
- It makes it difficult to refactor and simplify our caching infrastructure
- It has no documentation
- It is likely over-engineered for the problem that it attempts to solve

It's unlikely this API is widely used.  I have seen no mention of it since it was developed in 2012. I recommend we simply remove the interface from the public API in a release <= 5.0.

**Comment by blindpirate** [comment]
Are we still going to make it in `4.7RC1`? If not, please remove the milestone.
