### ISSUE TITLE
Gradle Ivy Maven ... Oh My !

### ISSUE THREAD

**Issue by supertick** [gradle/gradle#4395]
Hello,
First thank you for providing and maintaining this excellent build framework !
This is a question not an "issue" - so I hope to be able to tag it in the appropriate category.

A little background:

Gradle previously used Ivy to do dependency management, now I have "heard" since 2011 it relies on its own dependency manager.  From my experimentation, it appears gradle's current dependency management strategy more closely resembles Ivy than Maven.   (My experiment was comparing the results of **gradle vs maven vs ivy** results of dependent and transitive libraries downloaded for some equivalent (compile) build definition.

I am looking for a very modular runtime dependency manager.  Apache Ivy exceeds this "concept" except for a critical failure of not returning multiple artifacts which have different classifiers in maven repos.

**An easy validation test is to pull the dependencies of** 
**_'net.java.jinput', name: 'jinput', version: '2.0.7'_** with all 3 dependency managers

**gradle downloads the correct  3 artifacts which have classifiers** 
jinput-platform-2.0.7-natives-linux.jar
jinput-platform-2.0.7-natives-windows.jar
jinput-platform-2.0.7-natives-osx.jar

**maven downloads the correct 3 artifacts which have classifiers**

**ivy downloads only 1**
jinput-platform-2.0.7-natives-osx.jar (only the 'last' one)

My first question is, "Is gradle's current dependency manager in a distinct and modular form - similar to ivy ?" - specifically if I only wanted the dependency management system is it or could it be bundled in a single jar with a command line interface similar to Ivy ?

Second question is, If gradle's current dependency management was a fork of ivy, were any "fixes" sent back to ivy ?  And if its a fork - is there a possibility someone could direct me to it so I might pull it ?

Your time and effort are much appreciated.

Hugs,
Greg

**Comment by oehme** [comment]
Hey Greg,

for future questions please use the [Gradle forum](discuss.gradle.org).

Gradle's dependency management engine is not a standalone tool and it is pretty different from Ivy, so nothing was contributed back. Hope that answers your question :)
