### ISSUE TITLE
FR: When consuming Maven dependencies allow the version strings on transitive deps to be strictly enforced.

### ISSUE THREAD

**Issue by PaulRashidi** [gradle/gradle#4404]
Our team maintains a set of libraries which we are moving to semantic versioning (semver.org). We plan to release libraries in subsets and we optimize them together in those subsets such that we know that major version changes for each library aren't compatible. Concretely, LibA requires LibB@2. If an app tried to add LibC which uses LibB@3 then we don't want Gradle to uplift** and use LibB3.

One way we've looked at this is that we'd like to switch to declaring the version ranges in our POM files and then have Gradle strictly enforce those. I.E., in libraries in one subset we declare transitive deps to libraries in other subsets at specific major version ranges, "[1.0,2)"  (<- maven, not ivy).  We're not sure requiring our devs to enable strict version checking across their whole Gradle build is a fair solution, so this might require a way to flag GroupIds/Artifacts that should have the version string interpreted strictly during dependency resolution.

At the same time, we'd like to try to preserve hermetic builds, when possible. When we push a new lib we'd prefer that our use of ranges not cause new versions to be picked up in Gradle builds without a corresponding dep change. We can minimize the chance of this happening as a result of our lib's deps (not eliminate) by accompanying strict range interpretation with ordered version string processing such that we can declare the transitive dep ranges like this: "1.2,[1.0,2)". It would be interpreted as prefer 1.2, but if something else asks for something in the 1. range then allow it, but don't actively query for the highest versions of libraries.

I've been looking through all the issues related to this
https://github.com/gradle/gradle/issues?page=1&q=is%3Aissue+maven+version+string&utf8=%E2%9C%93

and it seems you might have been working on much of the plumbing for this by supporting preferred and rejection ranges natively in Gradle.
https://github.com/gradle/gradle/pull/3440#discussion_r150645469

Is there another way to achieve our goals and/or is this something that makes sense to support in the Gradle dep resolution strategies without custom plugins?

**We're only concerned with the dependency consumption side of things as we have a non-Gradle build system that we use to compile and publish to Maven.

**Comment by oehme** [comment]
You can use a [component metadata rule](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/DependencyHandler.html#components-org.gradle.api.Action-) to change the version to be strict based on the coordinates of the dependency.

**Comment by PaulRashidi** [comment]
Hi,
  I investigated this a bit awhile back. IIRC, when I ended up creating rejection rules that resulted in no possible libraries being selected the error message said that the artifact couldn't be found. This would be rather rough for our library users to debug. Would it be possible to pass through a rejection reason and adjust the error message to indicate that versions existed, but were rejected and then provide the plugin reasons?

**Comment by ljacomet** [comment]
As of Gradle 6.0, Gradle Module Metadata would be the best answer.
For existing components, combining component metadata rules and `strictly` version declaration should give you what you want.

Could you please try the above and confirm it covers your use case?

**Comment by PaulRashidi** [comment]
Thanks for following up. I've switched teams, but I will let the team responsible for the plugin know.

For reference, the plugin we developed to help users deal with the SDK's rather tricky transitive dependency resolution problem was this one.
https://github.com/google/play-services-plugins/tree/master/strict-version-matcher-plugin

**Comment by ljacomet** [comment]
Closing as this should be possible with rich version constraints.
