### ISSUE TITLE
`Tar` task shouldn't ignore work to be done when misconfigured

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#4406]
Given a single `Tar` task configuration without applying the `base` plugin:
```
task someTask(type: Tar) {
    from 'some/dir'
}
```

### Expected Behavior
Executing `someTask` should fail the build by complaining that some property wasn't properly configured.

### Current Behavior
The task is up-to-date even if `some/dir` contains files.

### Steps to Reproduce (for bugs)
- Copy the task configuration in an empty build script
- Execute `./gradlew someTask`

**Comment by lacasseio** [comment]
Note, this issue is most likely affecting other `AbstractArchiveTask` tasks.

**Comment by big-guy** [comment]
This appears to have been fixed
