### ISSUE TITLE
Composite builds cause "Dependencies were resolved during project configuration" warnings

### ISSUE THREAD

**Issue by adrian-baker** [gradle/gradle#4420]
Including a build seems to cause build scans to report all dependencies within the included build to be reported as being resolved during the configuration phase, under the "Settings and suggestions" section. This is even if the dependencies aren't actually referenced in the main build.

I'm not sure whether this is a genuine performance issue or a false positive.

See https://github.com/adrian-baker/gradle-scratchpad/tree/master/bug-composite-build-resolve-during-config for a very simple example, and compare the build scans with and without including the second build.

https://scans.gradle.com/s/cdx4x6wfhmfhw/performance/suggestions?open=WyJyZXNvbHV0aW9uRHVyaW5nQ29uZmlndXJhdGlvbiIsIm5vbkNhY2hlYWJsZVRhc2tPdXRwdXQiXQ

**Comment by ldaley** [comment]
Hi @adrian-baker,

It does potentially represent a problem, but it will be in Gradle itself. We are looking into it and will provide an update soon.

**Comment by adammurdoch** [comment]
This is fixed in Gradle Enterprise 2018.2 and also the public scans.gradle.org instance.
