### ISSUE TITLE
Preserve hierarchy information in test logging

### ISSUE THREAD

**Issue by sormuras** [gradle/gradle#4438]
Gradle 4.6 introduced support for executing "JUnit Platform"-based test engines.  At the moment, all hierarchy information created by an engine is flattened to a depth of `1`: `class` + `name` -- one may achieve another level of nesting by evaluating "suite" call-backs as well.

The [`TestDescriptor`](https://github.com/gradle/gradle/blob/master/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestDescriptor.java) has a parent property, but it only links to "internal" Gradle data types. The logical test container is not preserved.

So you can't re-build the real underlying test plan tree anymore. The following tree view was printed by the [JUnit Platform Console Launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher). It would be nice to achieve a similiar tree with the built-in Gradle test logging features.

### Expected Behavior
```
╷
├─ JUnit Jupiter ✔
│  ├─ AssertionsDemo ✔
│  │  ├─ exceptionTesting() ✔
│  │  ├─ groupedAssertions() ✔
[...]
│  ├─ ParameterizedTestDemo ✔
│  │  ├─ testWithEnumSourceInclude(TimeUnit) ✔
│  │  │  ├─ [1] HOURS ✔
│  │  │  └─ [2] DAYS ✔
│  │  ├─ testWithRegularParameterResolver(String, TestReporter) ✔
│  │  │  └─ [1] foo ✔
│  │  │        2018-02-19T10:47:03.894712 argument = `foo`
│  │  ├─ testWithCsvSource(String, int) ✔
│  │  │  ├─ [1] foo, 1 ✔
[...]
```
See full log at https://travis-ci.org/junit-team/junit5/jobs/343306357#L603

### Current Behavior
Using the built-in callbacks for test (and suite) reports via...
```
test {
  useJUnitPlatform {
    excludeTags 'exclude'
  }
  testLogging {
    afterTest { TestDescriptor td, TestResult tr ->
      out << td.className + ' ' + td.name + ' ' + tr.resultType.name()
[...]
```
...you may render flattend reports like:
```
[...]
example.AssertionsDemo > exceptionTesting() PASSED
example.AssertionsDemo > groupedAssertions() PASSED
[...]
example.ParameterizedTestDemo > [1] HOURS PASSED
example.ParameterizedTestDemo > [2] DAYS PASSED
example.ParameterizedTestDemo > [1] foo PASSED
example.ParameterizedTestDemo > [1] foo, 1 PASSED
[...]
```
See full log at https://travis-ci.org/junit-team/junit5/jobs/342475343#L603

### Your Environment
 * Build scan URL with the tree: https://gradle.com/s/2lfxujikyltqi
 * Build scan URL w/o the tree: https://gradle.com/s/k67wqgup4l4u2

**Comment by sormuras** [comment]
Additional information - this is the call-back interface the JUnit Platform Launcher provides:  [TestExecutionListener](https://junit.org/junit5/docs/current/api/org/junit/platform/launcher/TestExecutionListener.html)
The tree view is rendered by the [TreePrintingListener](https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/tasks/TreePrintingListener.java) implementation.

**Comment by sormuras** [comment]
The test report presented by "Build scan" ([JUnit 5 Build scan](https://scans.gradle.com/s/5jrpg3rlq7poc/tests)) could offer a tree view as well.

**Comment by jbduncan** [comment]
This issue sounds valuable to me.

**Comment by marcphilipp** [comment]
@gradle/bt-support I think the behavior has changed in the meantime in the sense that events for all intermediate nodes are also reported, correct?

**Comment by Gawen-pjr** [comment]
I can confirm that the hierarchical tests are well reported under IntelliJ IDEA at least

**Comment by marcphilipp** [comment]
Thanks for the confirmation!
