### ISSUE TITLE
Update Jansi to support xterm-256color and 24 bit rgb terminals

### ISSUE THREAD

**Issue by thetric** [gradle/gradle#4440]
Gradle should support colored console output under Linux if the `TERM` environment variable is set to `xterm-256color` or `xterm-24`. Currently Gradle simply crashes on startup.

### Expected Behavior
Gradle should work under (Linux) terminals if `TERM` is set to `xterm-256color` or `xterm-24`.

### Current Behavior
Fails with `xterm-256color`:
```console
$ TERM=xterm-256color gradle -v --debug --stacktrace
20:28:34.772 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /home/broj/.gradle/native

FAILURE: Build failed with an exception.

* What went wrong:
Could not open terminal for stdout: could not get termcap entry

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Works with `xterm`:
```console
$ TERM=xterm gradle -v
------------------------------------------------------------
Gradle 4.5.1
------------------------------------------------------------

Build time:   2018-02-05 13:22:49 UTC
Revision:     37007e1c012001ff09973e0bd095139239ecd3b3

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Linux 4.15.3-2-ARCH amd64
```

### Context
This issue occurs when executing any Gradle task.

This should be fixed by updating Jansi from 1.14 to at least 1.15 (see the [1.15 release notes](https://github.com/fusesource/jansi/blob/master/changelog.md#jansi-115-released-2017-03-17), latest version is [1.17](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.fusesource.jansi%22%20AND%20a%3A%22jansi%22)). 

A workaround for this is to set `org.gradle.console=plain` or the corresponding CLI flag but I want colored output :disappointed: 

### Steps to Reproduce (for bugs)

Execute the following command under some Linux terminal emulator (not in the TTY), e.g. xfce4-terminal, termite, XTerm, UXTerm, ...

```console
$ TERM=xterm-256color gradle -v
```

### Your Environment
* Gradle 4.5.1
* Oracle JDK 1.8u162
* OS: Arch amd64
* terminal: termite
* environment vars:
  * `TERM=xterm-256color`
  * `LANG=en_US.UTF-8`
  * `LC_CTYPE=en_US.UTF-8`
  * `LC_TYPE` isn't set
* the corresponding terminfo file under `/usr/share/terminfo/x/xterm-256color` exists
* latest `ncurses` and `ncurses5-compat-libs` are installed

**Comment by thetric** [comment]
Hm, manually replacing the Jansi jar in the Gradle distribution with the latest version didn't bring any improvements.

**Comment by thetric** [comment]
not reproducible on a similar machine

**Comment by big-guy** [comment]
@thetric Replacing the jar in the distribution may not be enough if you've run `gradle` once for that distribution.  Gradle extracts the native .so into a cache in GRADLE_USER_HOME that's specific for the version of Gradle used.  If the file is already extracted, I don't think we'll extract it again.

**Comment by thetric** [comment]
I've deleted `~./gradle` and rerun `TERM=xterm-256color ./gradle -v` without success. It's strange that Gradle doesn't print more helpful logs with  `--debug` or `--stacktrace`. 

I have also noticed that Gradle fails to execute under tmux with the same error. tmux sets `TERM` to `screen-256color`.

**Comment by RedTailBullet** [comment]
I am still experiencing this problem with 4.7... Any fix for it?

**Comment by casimiro** [comment]
It seems to be quite easy to reproduce the bug:
`TERM=xterm-256color gradle` will do it.

While the fix is not released, it's possible to workaround this problem with an alias:
`alias good-gradle="TERM=xterm gradle"` or just
`alias gradle="TERM=xterm gradle"`

**Comment by MJJoker** [comment]
I too can reproduce this problem.
I am using XFCE4 as an desktop environment and the xfce4-terminal

**Comment by alexanderankin** [comment]
bug is still an issue
