### ISSUE TITLE
Checksums on plugins.gradle.org are not always accurate

### ISSUE THREAD

**Issue by balefrost** [gradle/gradle#4442]
### Expected Behavior

The checksum file [kotlin-gradle-plugin.pom.sha1 (plugins.gradle.org)](https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom.sha1) should match the file content for [kotlin-gradle-plugin.pom (plugins.gradle.org)]( https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom)

### Current Behavior

The checksum file [kotlin-gradle-plugin.pom.sha1 (plugins.gradle.org)](https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom.sha1) is identical to the checksum file [kotlin-gradle-plugin.pom.sha1 (jcenter)](https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom.sha1). However, the POM files themselves differ. jcenter is consistent with itself, whereas plugins.gradle.org is not self-consistent. jcenter and maven-central also agree with each other. 

Also worth noting is that [kotlin-gradle-plugin.pom.sha1 (plugins.gradle.org)](https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom.sha1) actually redirects to [kotlin-gradle-plugin.pom.sha1 (jcenter)](https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom.sha1). So jcenter is internally consistent, but plugins.gradle.org is not.

I can't tell which piece is wrong: is the problem that the POM file doesn't agree with the other repositories or is the problem that the checksum isn't consistent with the file?

### Context

I'm trying to mirror gradle plugins for use in an environment with no internet access. I'm using Artifactory with the default checksum policy of "generate if absent". [Here's the documented behavior of that option](https://www.jfrog.com/confluence/display/RTF/Remote+Repositories#RemoteRepositories-ChecksumPolicy). I'd rather not turn off checksum verification, since it's generally good. 

### Steps to Reproduce (for bugs)

1. Download [kotlin-gradle-plugin.pom (plugins.gradle.org)](https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom)
2. Compute a SHA-1 sum of that file
3. Compare to the content of [kotlin-gradle-plugin.pom.sha1 (plugins.gradle.org)](https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.21/kotlin-gradle-plugin-1.2.21.pom.sha1)

For me, the computed SHA-1 is `b8a482a948be42a18547b5fcc6f75411e30608b2`, whereas the advertised SHA-1 in `2f497fbce005e703e500f7e769cb3a939a7194ca`.

### Your Environment

Nothing relevant.

**Comment by oehme** [comment]
The problem is that the plugin portal does not provide checksums at the moment, but it falls back to jcenter for artifacts it can't find. This means it'll also fall back for checksums if jcenter has them. We are currently fixing the missing checksums, see #3799

**Comment by eriwen** [comment]
The plugin portal now provides checksums properly. #3799 has been fixed. Please let me know if you see any further issues.
