### ISSUE TITLE
Play plugin: script generated by dist does not accept command line arguments

### ISSUE THREAD

**Issue by kiran002** [gradle/gradle#4471]
It seems to me that the command, gradle dist , does not produce the same output as ./sbt dist . The archive that the gradle produces contains a shell script that does not accept any command line arguments. Where as, the same works with sbt.

### Expected Behavior

the dist command produces an archive, with a shell script that should accept command line arguments like, 

`$ my-first-app-1.0/bin/my-first-app -Dconfig.file=/full/path/to/conf/application-prod.conf`

more information can be found here (https://www.playframework.com/documentation/2.6.x/Deploying#using-the-dist-task)

### Current Behavior

When the above command is executed i get the following error,

`Bad root server path: /home/ec2-user/test/play-scala-starter-example/build/distributions/-Dplay.http.secret.key=abcccc`

### Context
I am trying to deploy an application to production, once the distribution package has been created.

### Steps to Reproduce (for bugs)

`git clone https://github.com/playframework/play-scala-starter-example.git`
`cd play-scala-starter-example/`
`./gradlew dist`
`cd buid/distributions`
`unzip playBinary.zip`
`playBinary/bin/playBinary  -Dplay.http.secret.key='abcccc'`

### Your Environment

Running a centos machine on aws, but the issue also persists on my local ubuntu vm.

**Comment by kavinkumarks** [comment]
If you lookup the startup script, there would be an environment variable like <APP_OPTS>, set it to the command line arguments that you want to send and start the application.

**Comment by pdtran3k6** [comment]
Any follow ups on this issue?

**Comment by pdtran3k6** [comment]
So I have found a workaround:
Right now the shell script that is generated from `gradle dist` doesn't take in arguments. Thus, any arguments must be put in `$root/conf/application.conf`. Something like this:
```
# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile
play.http.secret.key="test"
```
Then, just proceed to run the script **without any arguments**:
```
./$root/build/distributions/playBinary/bin/playBinary (your path may be different)
```

**Comment by pdtran3k6** [comment]
Or you can write your own version of `playBinary` and copy it to `bin` folder in `build.gradle`:
```
model {
  ...
  distributions {
    playBinary {
      contents {
        from("yourScriptName") {
          into "bin"
        }
      }
    }
  }
}
```

Then, instead of running `bin/playBinary`, just run `bin/yourScriptName` and feed it arguments as usual.

**Comment by bmuskalla** [comment]
The plugins are superseded by https://gradle.github.io/playframework/ and will be [removed in one of the next major releases](https://github.com/gradle/gradle/issues/9434).
