### ISSUE TITLE
Build init plugin should offer JUnit 5 test framework selection

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#4485]
### Expected Behavior

The command line option `--test-framework` should offer an option for JUnit 5 tests.

### Current Behavior

JUnit 5-based tests are not supported at the moment for the project type `java-application` or `java-library`.

### Context

The build init plugin should support JUnit 5 natively now that the test framework has become a core functionality.

**Comment by karanveersp** [comment]
Until Gradle updates this, I've created a python script that others may find helpful. It generates a JUnit5 Gradle Java project.
https://github.com/karanveersp/junit5-project-initializer

**Comment by adammurdoch** [comment]
This is a duplicate of #8826 (which has been fixed).
