### ISSUE TITLE
Can we delete customM2Check.gradle?

### ISSUE THREAD

**Issue by hansd** [gradle/gradle#4487]
This task is configured to never execute: https://github.com/gradle/gradle/blob/6f51f19a37990d1260a81cbbf14f95bdb959a0bf/gradle/customM2Check.gradle#L18

Do we still need this script?

**Comment by hansd** [comment]
Many thanks, Bo!

**Comment by blindpirate** [comment]
@hansd done in https://github.com/gradle/gradle/pull/4493
