### ISSUE TITLE
Can we delete buildTagging.gradle?

### ISSUE THREAD

**Issue by hansd** [gradle/gradle#4489]
It looks like that this script is not used in our build: https://github.com/gradle/gradle/blob/6f51f19a37990d1260a81cbbf14f95bdb959a0bf/gradle/buildTagging.gradle#L23

It is probably used on our internal CI infrastructure. If that is the case we should move it out of the public repository.

**Comment by blindpirate** [comment]
Yes, at the end of every build on CI there's a stage `TAG_BUILD`.

**Comment by eskatos** [comment]
There are may aspects of our build that relate to CI infrastructure. I don't think they should be moved out of `gradle/gradle`. They should be easily distinguishable though.

Closing as we won't *delete* this logic.

**Comment by hansd** [comment]
@eskatos I know that we have a lot of special treatment for CI in our build logic. But this is a script not used at all in the build logic. It is applied nowhere. So I don't necessarily agree. It is not about deleting it, but moving it somewhere else.

**Comment by jjohannes** [comment]
This is completely separate build. I think the easiest improvement is to move the script to a different location in the repository. Then, this new location has to be used here: https://github.com/gradle/gradle/blob/teamcity-versioned-settings/.teamcity/Gradle_Check/configurations/GradleBuildConfigurationDefaults.kt#L157

I think it would also be better to call the file "build.gradle" and place it into a separate directory. And then set this directory as the working directory in the team city build step. It would clarify that this is a separate build.

**Comment by hansd** [comment]
@jjohannes Thanks for pointing this out. 

If this script above is the only consumer of `buildTagging.gradle` the latter should not live in the public repo.

**Comment by wolfs** [comment]
Why should it not live in the public repo? The above also lives in the same public repo (only a different branch).
I think moving the `buildTagging.gradle` to a `build.gradle` in a different directory within `gradle/gradle` would be a good start.

**Comment by wolfs** [comment]
We ended up applying the plugin to the root build: #7346
