### ISSUE TITLE
Include annotation processor output as source folder in IDEs

### ISSUE THREAD

**Issue by SergejIsbrecht** [gradle/gradle#4499]
Currently when using annotationProcessor configuration in 4.6-RC2 all files will be generated to /build/classes/java/main/[...]. This behavior is expected, but I also would expect, that the path to java files would be included to sources in the IDE with Idea/ Eclipse plugin. The APT-Plugin ( https://github.com/tbroyer/gradle-apt-plugin ) has an idea plugin extension, that includes the folder containing the generated java files in the IDE (Idea).

It would be great, when the IDEA/ Eclipse plugins would be updated, that the folders with generated java files would be included as source folders.

Tested with IDE 2018.1 EAP Community

**Comment by oehme** [comment]
This is not expected to work yet. See #2300 for the overall progress of the story.
