### ISSUE TITLE
WorkerExecutor should limit the number of active work items

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#4502]
Currently `DefaultWorkerExecutor` creates an `ExecutorService` with an unbound thread pool to handle work requests.  This works fine for most scenarios, but if the number of work items is extremely large, this can consume a lot of resources (and potentially exhaust them).  We should move this to a queue-based approach similar to `DefaultBuildOperationQueue` where the number of active threads is limited.  We should take care to deal with contention between worker leases and avoid a scenario where the active thread pool is full of requests that can't get a worker lease.

### Expected Behavior
`WorkerExecutor` limits the number of active threads when processing work items.

### Current Behavior
`WorkerExecutor` creates as many threads as outstanding work items 

### Context
When submitting extremely large numbers of work items, lots of resources can be consumed (or exhausted)

### Steps to Reproduce (for bugs)
Submit a _lot_ of items to the `WorkerExecutorService`

**Comment by blindpirate** [comment]
Are we still going to make it in `4.7RC1`? If not, please remove the milestone.

**Comment by big-guy** [comment]
Yes, I'm trying to finish this today

**Comment by eriwen** [comment]
@big-guy Is the intent to do this today? Please let the team know if we'll need to delay the RC for it.

**Comment by ghale** [comment]
Sorry, I commented on the PR, but didn't realize this issue also had a milestone set.  No, we cut the release branch before we could get the PR reviewed and put away.  This will have to go into 4.8.

**Comment by oehme** [comment]
This has been fixed.
