### ISSUE TITLE
Update JUnit Platform dependencies in sample projects and user guide

### ISSUE THREAD

**Issue by BlueIce** [gradle/gradle#4509]
There are three sample projects for the JUnit Platform:

- docs/src/samples/testing/junitplatform/engine
- docs/src/samples/testing/junitplatform/jupiter
- docs/src/samples/testing/junitplatform/tagging

Currently this projects have dependencies on the JUnit Platform release 5.0.3. A few days ago a new stable release was published: https://github.com/junit-team/junit5/releases/tag/r5.1.0. Please consider updating to the new version.

If I understood correctly any changes to the dependencies sections of the sample projects will also show up in the user guide of the java plugin automatically.

**Comment by blindpirate** [comment]
Closed by #4516 , thanks @BlueIce !

**Comment by BlueIce** [comment]
It's even included in the 4.6 release, nice. :smile:
