### ISSUE TITLE
dependsOn should not fail if a task is not defined

### ISSUE THREAD

**Issue by novaterata** [gradle/gradle#4522]
I have a multi-project gradle build where not all of the subprojects  have the same plugin, but I would like to define tasks in the root  build.gradle file like this: 

    subprojects {
        task continuousBuild(dependsOn: ["clean", "check", "jacocoTestReport", "integrationTests"] )
    }

This fails because not all projects have a "jacocoTestReport" or "integrationTests" task.

I can workaround this by doing this:

    task continuousBuild(dependsOn: ['clean', 'check']) {
        def uncommonTasks = ['jacocoTestReport', 'integrationTests']
        dependsOn += tasks
                .findAll { uncommonTasks.contains(name) }
   }

But I don't think I should have to do that. If a task isn't defined, just ignore it.

**Comment by big-guy** [comment]
I don't think we would want that behavior in general.  It would be bad for the more common case of fat fingering a task name (it would be silently ignored) or cause weird problems if tasks change name.

You can do this already in a couple of different ways:
```
subprojects {
    task continuousBuild {
       // if the types of tasks is known
       dependsOn tasks.withType(Delete), tasks.withType(JacocoReport), tasks.withType(Test)
       // -or- if the list of task names is short
       dependsOn tasks.matching { it.name in [ 'jacocoTestReport', 'integrationTests' ] }
    }
}
```
You can also combine the two approaches.  `matching` isn't the same as your `findAll` solution as you'll run into ordering problems with `findAll`.  If the task hasn't been created when you run `findAll`, you won't find it.

I would also say that running `clean` as part of continuous build is really strange.  Gradle should be able to work without running clean, so if you're running into problems with that, we would really like to know.

Another way of looking at this is to consider defining a task that every project will have, but is configured differently depending on which plugins are applied.  e.g.:
```
subprojects {
    task devBuild
    pluginManager.withPlugin("java") {
        devBuild.dependsOn "check"
    }
    pluginManager.withPlugin("jacoco") {
        devBuild.dependsOn "jacocoTestReport"
    }
    pluginManager.withPlugin("pluginThatAddsIntegrationTests") {
        devBuild.dependsOn "integrationTests"
    }
}
```
HTH

**Comment by novaterata** [comment]
Yeah, I actually removed clean so it's optional, but I tend to run it out of paranoid habit I guess
