### ISSUE TITLE
JUnit 5 docs should include examples for package/class filtering

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#4523]
The [docs on test filtering](https://docs.gradle.org/4.6-rc-2/userguide/java_plugin.html#test_filtering) includes a JUnit 4 example for package/class filtering, but we do not do the same for JUnit platform.

It would be good to add these examples, and further link to them from the [Using JUnit 5](https://docs.gradle.org/4.6-rc-2/userguide/java_plugin.html#using_junit5) subsection.

**Comment by JLLeitschuh** [comment]
You should be able to configure (and possibly have examples for) these things:
https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-selectors

An example similar to this one for the existing plugin would be useful:
```gradle
junitPlatform {
    // ...
    filters {
        engines {
            include 'junit-jupiter'
            // exclude 'junit-vintage'
        }
        tags {
            include 'fast', 'smoke & feature-a'
            // exclude 'slow', 'ci'
        }
        packages {
            include 'com.sample.included1', 'com.sample.included2'
            // exclude 'com.sample.excluded1', 'com.sample.excluded2'
        }
        includeClassNamePattern '.*Spec'
        includeClassNamePatterns '.*Test', '.*Tests'
    }
    // ...
}
```

**Comment by oehme** [comment]
@eriwen the docs you linked to are independent of which test framework is used. Filtering by class name works for all of them. That's why it's not nested inside the framework element, but directly under the test task itself.

**Comment by JLLeitschuh** [comment]
I think I see what you're saying @oehme.

I guess the goal is to make sure that all of the knobs that the Junit5 gradle plugin offers are also offered through the Gradle API.

**Comment by blindpirate** [comment]
Thanks @eriwen @JLLeitschuh . Just as @oehme said, filtering by name is unified in the documentation whichever test frame work is used. 

```
junitPlatform {
    // ...
    filters {
        engines {
            include 'junit-jupiter'
            // exclude 'junit-vintage'
        }
        tags {
            include 'fast', 'smoke & feature-a'
            // exclude 'slow', 'ci'
        }
        packages {
            include 'com.sample.included1', 'com.sample.included2'
            // exclude 'com.sample.excluded1', 'com.sample.excluded2'
        }
        includeClassNamePattern '.*Spec'
        includeClassNamePatterns '.*Test', '.*Tests'
    }
    // ...
}
```

This can be translated to Gradle scripts:

```
test {
    filter {
        includeTestsMatching 'com.sample.included1.*', '*Test'
    }
    useJUnitPlatform {
        includeEngines 'junit-jupiter'
        includeTags 'fast', 'smoke & feature-a'
    }
}
```

And I added the missing `includeEngines` parts to the documentation in #4598
