### ISSUE TITLE
Cannot "echo yes" to turn on build scans via command line

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#4526]
## This works:
```
$ gradlew assemble --scan

8 actionable tasks: 8 up-to-date

Publishing a build scan to scans.gradle.com requires accepting the Terms of Service defined at https://scans.gradle.com/terms-of-service. Do you accept these terms? [yes, no]
yes
Gradle Cloud Services license agreement accepted.

Publishing build scan...
https://gradle.com/s/b2btrjyay6exu
```

## This does not work:
```
$ echo yes | gradlew assemble --scan

8 actionable tasks: 8 up-to-date


The build scan was not published due to a configuration problem.

The Gradle Cloud Services license agreement has not been agreed to.

To agree to the license, include the following in your root project's configuration:
buildScan { licenseAgreementUrl = 'https://gradle.com/terms-of-service'; licenseAgree = 'yes' }

For more information, please see https://gradle.com/scans/help/plugin-license.

Alternatively, if you are using Gradle Enterprise, specify the server location.
For more information, please see https://gradle.com/scans/help/plugin-enterprise-config.

BUILD SUCCESSFUL in 0s
```

**Comment by jaredsburrows** [comment]
This way users do not have to add this to their code base: 
```
buildScan {
  licenseAgreementUrl = "https://gradle.com/terms-of-service"
  licenseAgree = "yes"
}

```

**Comment by big-guy** [comment]
I think we're not likely to solve this particular problem in this way soon.

You can also add an init script to your Gradle user home:
https://docs.gradle.com/build-scan-plugin/#for_all_your_builds

Inside it, you can do the:
```
buildScan {
  licenseAgreementUrl = "https://gradle.com/terms-of-service"
  licenseAgree = "yes"
}
```

You wouldn't need to accept the license on each project individually.

**Comment by oehme** [comment]
I'm curious why this doesn't work - do we not read from stdin @eriwen?

**Comment by Ram-Lakhan** [comment]
- Check below link:
https://guides.gradle.org/creating-build-scans/#auto_apply_the_build_scan_plugin

**Comment by msgilligan** [comment]
> You can also add an init script to your Gradle user home: https://docs.gradle.com/build-scan-plugin/#for_all_your_builds
> 
> Inside it, you can do the:
> 
> ```
> buildScan {
>   licenseAgreementUrl = "https://gradle.com/terms-of-service"
>   licenseAgree = "yes"
> }
> ```
> 
> You wouldn't need to accept the license on each project individually.

I tried this and get the error:

```
$ gradle build --scan

FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/sean/.gradle/init.d/build-scan-agree.gradle' line: 1

* What went wrong:
A problem occurred evaluating initialization script.
> Could not find method buildScan() for arguments [build_scan_agree_bjec7e8o82f6v8auo952om7on$_run_closure1@1a169943] on build of type org.gradle.invocation.DefaultGradle.

```

I want to run a build scan by providing the `--scan` argument which will automatically apply the plugin. But if I do this in a CI environment, I get the above error. How can I agree to the license without manually installing the plugin?

Note that the **Gradle Enterprise Gradle Plugin User Manual** says:

> Be careful not to commit agreement to the terms of service into a project that may be built by others.

So having a way to agree without putting it in `build.gradle`, etc. seems like something that should be supported.

**Comment by msgilligan** [comment]
Since this issue is closed I opened a new issue for my request: https://github.com/gradle/gradle/issues/26316
