### ISSUE TITLE
WrapperExecutor.readDistroUrl should support square brackets

### ISSUE THREAD

**Issue by mercer** [gradle/gradle#4529]
### Expected Behavior
- usage of square bracket `[` or `]` in `distributeionUrl` is accepted

### Current Behavior
- WrapperExecutor throws a RuntimeException `Exception in thread "main" java.lang.RuntimeException: Could not load wrapper properties from '/home/project/gradle/wrapper/gradle-wrapper.properties'.`
- see [output.log](https://github.com/gradle/gradle/files/1761719/output.log)

### Context
- I hoped I can point the gradle distribution url to an internal jfrog link that gives the latest (internal) release

### Steps to Reproduce (for bugs)
- given distributionUrl=https\://artifacts/maven/com/artifact/[RELEASE]/name-[RELEASE].zip
 in gradle-wrapper.properties
- it should be accepted as a valid url
- because square brackets are valid in a url
- and because jfrog offers an api https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-RetrieveLatestArtifact

### Your Environment
- gradle 5.1 through gradle wrapper
- ubuntu 17.04

**Comment by oehme** [comment]
Square brackets are not valid in URLs, see http://www.ietf.org/rfc/rfc3986.txt

> A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").  This is the only place where
   square bracket characters are allowed in the URI syntax.

Have you tried encoding them?

**Comment by mercer** [comment]
@oehme I was aware these are not valid characters in URLs, but this doesn't stop Artifactory from using them. And I'd say Artifactory's decision is relevant in our context here.

Indeed, encoding works, so I used `distributionUrl=https://artifacts/maven/com/artifact/%5BRELEASE%5D/name-%5BRELEASE%5D.zip` instead of `distributionUrl=https://artifacts/maven/com/artifact/[RELEASE]/name-[RELEASE].zip`, thanks for the suggestion.
