### ISSUE TITLE
Javadoc fails to generate resourcedoc.xml for Jersey 1.19

### ISSUE THREAD

**Issue by pavel-kolesov** [gradle/gradle#4530]
I'm using following configuration of Javadoc to generate resourcedoc.xml for Jersey 1.19 (the pattern taken from https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html).
The task fails with "javadoc: error - invalid flag: -d":

-d flag value is generated from destinationDir property, which can't be omitted.
Is there a way to workaround this?

Java version: 1.8.0_144

```
def jerseyVersion = "1.19"
configurations {
    wadlDoclet
}
dependencies {
    wadlDoclet "com.sun.jersey.contribs:wadl-resourcedoc-doclet:${jerseyVersion}"
}
task generateWadl(type: Javadoc) {
    source = sourceSets.main.allJava
    destinationDir = file('./')
    options.docletpath = configurations.wadlDoclet.files.asType(List)
    options.doclet = "com.sun.jersey.wadl.resourcedoc.ResourceDoclet"
    options.addStringOption("output", "resourcedoc.xml")
}
war {
    dependsOn generateWadl
}
```

**Comment by blindpirate** [comment]
Please see here: https://bugs.openjdk.java.net/browse/JDK-4935349

This is not a Gradle issue.

**Comment by pavel-kolesov** [comment]
Disagree: the problem is not in javadoc, but in a javadoc gradle plugin, which supplies incorrect set of parameters to javadoc.

**Comment by blindpirate** [comment]
You're right. Sorry.

**Comment by pavel-kolesov** [comment]
A workaround is to use ant.javadoc plugin - destdir is not required, if custom doclet is used.

See https://ant.apache.org/manual/Tasks/javadoc.html
