### ISSUE TITLE
Provide a convenient way of producing a `Provider<Directory>` from a `File`

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#4532]
To bridge between tasks that do not use the Provider API/Property types and expose a `File`, we already supply a `ProjectLayout.file()` API to convert from a `File` to a `Provider<RegularFile>`.  We should provide a similar API for creating a `Provider<Directory>`.  Currently, you need to go the long way around:

```
someDirectory.set(layout.projectDirectory.dir(provider { taskWithoutProvider.outputDir.absolutePath }))
```

Just using `someDirectory.set(taskWithoutProvider.outputDir)` isn't enough because `outputDir` may be set much later.

### Expected Behavior

Easy to bridge old and new APIs.

### Current Behavior

Not that convenient.

**Comment by mkobit** [comment]
In a similar fashion,, being able to take `Configuration` -> `Provider<RegularFile>`/`Provider<File>` (similar to [`Configuration.getSingleFile()`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/FileCollection.html#getSingleFile--)

**Comment by Vampire** [comment]
Yeah, a `myConfiguration.getSingleFileProvider()` or similar would also be nice, currently you have to do `layout.file(provider { myConfiguration.singleFile })`.

**Comment by Vampire** [comment]
I'd say the main description of this ticket is fulfilled with https://github.com/gradle/gradle/commit/2c943ff55c8156889b9b74d55f1efae309922bcd#diff-a23fe71c2c0969c7522615def294e0422080dfbf8bc0d4598baf88bda76ffe1d since 6.0.
But it would still be nice to have `Configuration.getSingleFileProvider()`.

**Comment by wolfs** [comment]
I created https://github.com/gradle/gradle/issues/20155 for the single file from a collection case. Let's close this issue.
