### ISSUE TITLE
Some included builds have to be resolvable from a maven repository for the build to proceed

### ISSUE THREAD

**Issue by calvertdw** [gradle/gradle#4535]
In composite builds, sometimes I get the "resource missing" error (described in #2521) and the only thing I do to fix the problem is `publishToMavenLocal` on the "missing" project.

This works by allowing the build to proceed by (gathering the POM?) from mavenLocal, even though the build is included properly in the end.

The published version of the included build artifact doesn't have to match the including dependency version. So it's not actually resolving it. Appears to just be "looking for it".

If I delete the artifact from mavenLocal the error comes back.

in:composite-builds

**Comment by oehme** [comment]
Can you please provide a reproducible example?

**Comment by ghale** [comment]
I'm closing this for now.  We can reopen if we have a way to reproduce the behavior.
