### ISSUE TITLE
Gradle checkstyle plugin doesn't generate any tasks

### ISSUE THREAD

**Issue by psukys** [gradle/gradle#4540]
### Expected Behavior

Adding into `build.gradle`:
```gradle
apply plugin: 'checkstyle'

checkstyle {
    configFile = rootProject.file('config/checkstyle/checkstyle.xml')
}
```
and checkstyle's configuration in aforementioned path.

Running `./gradlew tasks` expect to see the following tasks, as [defined in documentation](https://docs.gradle.org/current/userguide/checkstyle_plugin.html):
 - `checkstyleMain`
 - `checkstyleTest`
 - `checkstyleSourceSet`

### Current Behavior
Tasks are not visible, no additional information is provided

### Your Environment
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Linux 4.15.4-300.fc27.x86_64 amd64
```

**Comment by blindpirate** [comment]
Well, have you applied `java` or `groovy` plugin? If yes, could you provide a reproducible sample?

**Comment by psukys** [comment]
@blindpirate no, neither. Are there any dependent plugins neededfor `checkstyle` plugin?

**Comment by blindpirate** [comment]
AFAIK, `checkstyle` plugin creates one task for each [`sourceSet`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html). If there's no source set, no wonder `checkstyle` plugin doesn't create any task.

P.S `java` plugin will create two source set `main` and `test` by default: https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_source_sets

**Comment by psukys** [comment]
@blindpirate by running `./gradlew sourceSets` it seems that both `main` and `test source sets are present (actual output from [reference build.gradle](https://github.com/TCA-Team/TumCampusApp/blob/master/app/build.gradle) file: https://pastebin.com/raw/rfrZQGa5)

**Comment by oehme** [comment]
You are using the Android plugin, which doesn't interoperate with the Checkstyle plugin. You might want to add a feature request on their [issue tracker](https://issuetracker.google.com/issues/new?component=192709&template=842921).

**Comment by lidudutju** [comment]
@oehme I want to add checkstyle plugin to my Android project. But it didn't work. Is Android plugin still incompatible with checkstyle plugin?

**Comment by oehme** [comment]
Nothing has changed there, please open a feature request on their issue tracker.
