### ISSUE TITLE
multi-project task from projectsEvaluated not found in subproject dependsOn

### ISSUE THREAD

**Issue by novaterata** [gradle/gradle#4550]
I didn't have this problem with 4.4.x, but after I upgraded to 4.6 I started having this problem

I have a multi-project project
In the root build.gradle I have a 

```
   gradle.projectsEvaluated {
            configure(subprojects.findAll { it.plugins.hasPlugin 'java' }) {
                task signJar(type: Exec, dependsOn: jar) {
                   // ...
                }
                task verifyJar(type: Exec, dependsOn: signJar) {
                   // ...
                }
   }
```

In a subproject that does use the 'java' plugin

I have a task that dependsOn 'verifyJar' and ':another-java-sub-project:verifyJar', but the build fails saying that no task with that path exists

Again, this only changed after upgrading to 4.6

**Comment by big-guy** [comment]
A reproducible example would be helpful. This seems like some sort of regression, but you can do this in a simpler way.

```
subprojects {
    pluginManager.withPlugin('java') {
        task signJar(type: Exec, dependsOn: jar) {
           // ...
        }
        task verifyJar(type: Exec, dependsOn: signJar) {
           // ...
        }
    }    
}
```

**Comment by novaterata** [comment]
If I have the time I'll try to create one, I'll try your alternative method. It is very hard to find the recommended way to do anything like this with gradle. All the documentation seems to assume all the projects use the same language

**Comment by novaterata** [comment]
@big-guy pluginManager worked and I definitely like it better, wish I'd known about it earlier. I tried to create a simple repro project, but the regression must be more esoteric than I thought. Maybe needs some of my other plugins thrown into the mix. I'll close for now and reopen if I can create a repro project
