### ISSUE TITLE
--fail-fast argument not works with command line

### ISSUE THREAD

**Issue by Alexuy** [gradle/gradle#4562]
### Expected Behavior
If i set --fail-fast argument in command line, test task parameter failFast value must be set to 'true'

### Current Behavior

Now, when i try to run grade tasks:

```groovy
gradle clean build --fail-fast -i
```

i have error:

``` bash
FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :build from command line.
> Unknown command-line option '--fail-fast'.
```

If i set in build.gradle test parameter:
```groovy
test {
    failFast = true
}
````

all works fine

**Comment by oehme** [comment]
Duplicate of https://github.com/gradle/gradle/issues/2032

You'll have to list the test task explicitly if you want to give it options, e.g: `gradle build test --fail-fast`

**Comment by henrik242** [comment]
You can also specify a custom property `doFailFast`, like this:
```
gradle clean build -PdoFailFast -i
```
Then you just read that in build.gradle:
```
test {
    failFast = rootProject.hasProperty("myFailFast")
}
```
