### ISSUE TITLE
Build hangs when test task fails due to an invalid JVM argument

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#4564]
### Expected Behavior

The build fails when the test task is configured with an invalid JVM argument.

### Current Behavior

The build hangs when the test task is configured with an invalid JVM argument.

### Context

I originally encountered this problem when accidentally attempting to build a project that requires Java 9 with Java 8. The test task was configured with the `add-module` JVM argument which Java 8 rejects. The test task failed but the build then hung.

### Steps to Reproduce (for bugs)

Unzip the [attached project](https://github.com/gradle/gradle/files/1775225/test-hang.zip) and run `./gradlew build`.

### Your Environment

I don't believe this issue is specific to any particular environment. I experienced the problem with Gradle 4.6. Some further experimentation suggests that earlier versions are also affected.

**Comment by oehme** [comment]
Thanks Andy! This is a known issue. The problem is that the daemon will wait indefinitely for the first message from the test executor instead of timing out at some point.

**Comment by wilkinsona** [comment]
I don't think it's specific to when the daemon's being used. The following exhibits the same behaviour:

```
./gradlew --no-daemon build
```

**Comment by oehme** [comment]
We tend to use the word daemon interchangeably with "main build vm", which is what I meant here.

**Comment by wilkinsona** [comment]
Ah, I see. Thanks for the clarification.
