### ISSUE TITLE
Missing convenience method for domain object creation

### ISSUE THREAD

**Issue by hansd** [gradle/gradle#4570]
This works fine: `tasks.create<CleanUpCaches>("cleanUpCaches")`

This does not work:
```
tasks {
   create<CleanUpCaches>("cleanUpCaches")    
}
```

The latter would be really nice to have as this is my idiomatic way now to create domain objects that I don't need to access after creating via a variable.

**Comment by bamboo** [comment]
Relates to gradle/kotlin-dsl#605

**Comment by eskatos** [comment]
Superseded by https://github.com/gradle/kotlin-dsl/issues/804
