### ISSUE TITLE
Using kotlin build scripts instead of groovy build scripts does not work on linux ppcle and aix ppc

### ISSUE THREAD

**Issue by epeee** [gradle/gradle#4603]
### Expected Behavior

The build does not fail if I use kotlin scripts instead of groovy scripts.

### Current Behavior

The build fails if I use kotlin scripts instead of groovy scripts (on aix ppc and linux ppcle). It works on linux x86 and windows.

### Context

I tried to execute a gradle build which is already migrated to kotlin scripts on aix ppc and linux ppcle. While trying to get more details about the problem I realized that it is not related to my build. I tried using an empty settings.gradle.kts file which did result in:

> ./gradlew help
> e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
>     class org.gradle.api.plugins.PluginAware, unresolved supertypes: Object
>     class org.gradle.api.Action, unresolved supertypes: Object
>     class groovy.lang.GroovyObjectSupport, unresolved supertypes: Object
>     class groovy.lang.GroovyObject, unresolved supertypes: Object
>     class java.lang.Runnable, unresolved supertypes: Object
>     class java.util.concurrent.Callable, unresolved supertypes: Object
>     class java.io.Serializable, unresolved supertypes: Object
>     class java.io.File, unresolved supertypes: Object
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Settings file '/home/ep/gradle-kotlin/settings.gradle.kts'
> 
> * What went wrong:
> Script compilation error:
> 
>   Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
>       class org.gradle.api.plugins.PluginAware, unresolved supertypes: Object
>       class org.gradle.api.Action, unresolved supertypes: Object
>       class groovy.lang.GroovyObjectSupport, unresolved supertypes: Object
>       class groovy.lang.GroovyObject, unresolved supertypes: Object
>       class java.lang.Runnable, unresolved supertypes: Object
>       class java.util.concurrent.Callable, unresolved supertypes: Object
>       class java.io.Serializable, unresolved supertypes: Object
>       class java.io.File, unresolved supertypes: Object
>   
> 
> 1 error
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 

using a settings.gradle file instead of the settings.gradle.kts results in:

> ./gradlew help
> :help
> 
> Welcome to Gradle 4.6.
> 
> To run a build, run gradlew <task> ...
> 
> To see a list of available tasks, run gradlew tasks
> 
> To see a list of command-line options, run gradlew --help
> 
> To see more detail about a task, run gradlew help --task <task>
> 
> For troubleshooting, visit https://help.gradle.org
> 
> BUILD SUCCESSFUL in 1s
> 1 actionable task: 1 executed
> 
> 

### Steps to Reproduce (for bugs)

Create 2 empty files (build.gradle, settings.gradle). Running gradlew help will succeed. 
Let's rename settings.gradle to settings.gradle.kts now and gradlew help will fail with the message mentioned above.

It looks like it is not related to ibm jvm usage (because using an ibm one does work on linux x86). Furthermore, it seems to be related to running on ppc/ppcle. 

### Your Environment

> ------------------------------------------------------------
> Gradle 4.6
> ------------------------------------------------------------
> 
> Build time:   2018-02-28 13:36:36 UTC
> Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c
> 
> Groovy:       2.4.12
> Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
> JVM:          1.8.0 (IBM Corporation 2.8)
> OS:           AIX 7.2 ppc64
>

**Comment by eriwen** [comment]
Is this something your team should investigate @eskatos?

**Comment by eskatos** [comment]
@epeee this is an issue with the Kotlin compiler, maybe around locating the rt.jar
Superseded by https://youtrack.jetbrains.com/issue/KT-25504
