### ISSUE TITLE
UploadArchives eagerly publishes all artifacts

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#4612]
The way `BasePlugin` works, it eagerly adds all artifacts from all configurations to the `archives` configuration: 

https://github.com/gradle/gradle/blob/0f1507b4a3cefc048c24ab78251e33b526699489/subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePlugin.java#L164-L172

This then causes all artifacts to be published when invoking `uploadArtifacts`.  The problem is that sometimes I may be creating a configuration with artifacts that are not intended for publication (for instance, they are only used in between projects of a multi-project build) and may not be suitable for publication (e.g. a directory instead of a file).  At best, I may publish artifacts I don't intend to.  At worst, publishing may fail.

### Expected Behavior
There should be a simple and obvious way to prevent `uploadArchives` from publishing artifacts that are not intended for publication.  

### Current Behavior
Currently, the only obvious way to prevent this is to explicitly remove the artifacts from the `archives` configuration which seems less than optimal.

### Context
A configuration ("foo") is being used to expose a directory artifact to other projects in a multi-project build.  This project also publishes a jar artifact.  We want the jar artifact to be published when `uploadArchives` is called, but not the directory artifact from the "foo" configuration.

### Steps to Reproduce (for bugs)
```
apply plugin: "base"

configurations {
    foo 
    bar
}

task mkdir {
    ext.outputDir = file("${buildDir}/foo")
    doLast {
        outputDir.mkdirs()
    }
}

task jar(type: Jar) {
    from "build.gradle"
}

artifacts {
    bar jar
    foo file: mkdir.outputDir, builtBy: mkdir
}

uploadArchives {
    repositories {
        ivy { url file("${buildDir}/repo") }
    }
}
```

**Comment by oehme** [comment]
The workaround is to set a different Configuration on the task instead of the archives configuration.

**Comment by ghale** [comment]
I still think we need to be better here.  Although changing the configuration of `uploadArchives` would work, it doesn't seem like a great solution to have `uploadArchives` upload something other than `archives`.  Especially since this task is created via a task rule whose express purpose is to allow you to upload the configuration with the given name.  

Certainly the user could create another configuration (say "foo") and then call `uploadFoo`, but this becomes really awkward if you have a large multi-project build and some projects have this requirement while others don't.

What I am questioning here is not whether the archives configuration should contain all artifacts, but whether all artifacts of a configuration should be published externally any time that configuration is published.  I think there is a valid use case where a configuration can have artifacts that are only used internally and should not be published externally.  We should support this without awkward contortions on the user's part.

**Comment by oehme** [comment]
I don't think we need to make this better, given that we want to deprecate and remove the whole old publishing infrastructure once we finish the maven-publish/ivy-publish plugins (which we intend to do till the middle of the year). 

We could do a simple fix for not trying to publish directories, but I wouldn't do any more than that, if even.

**Comment by bigdaz** [comment]
The `maven` plugin and the core `uploadArchives` task are being replaced by the `maven-publish` and `ivy-publish` plugins. As such, we don't plan on making changes to improve the (now legacy) behaviour. Expect to see `uploadArchives` deprecated in Gradle 6.x, for possible removal in Gradle 7.0.
