### ISSUE TITLE
gradle init fails to migrate exiting maven projects

### ISSUE THREAD

**Issue by jagraj** [gradle/gradle#4615]
We have exiting maven projects and we tried to migrate them using gradle init. It migrated projects but when i try to import in the tools and those projects fail to import due to the error generated from gradle init.

One of the child EJB project has dependency on JPA project and here is the entry in pom.xml
  	<dependency>
	  	<groupId>com.ibm.ws.svt.gs.garagesale-ee7</groupId>
  		<artifactId>CreditCardDBJPA</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  		<scope>provided</scope>
  	</dependency>

After gradle init the following entry is generated in build.gradle file and this is failed to import in tools.

description = ''
dependencies {
    compileOnly group: 'javax.ejb', name: 'javax.ejb-api', version:'3.2'
    compileOnly group: 'org.eclipse.persistence', name: 'javax.persistence', version:'2.1.1'
  providedCompile project(':CreditCardDBJPA')
}

In the above build file, the gradle init should have generated with "compileOnly" rather "providedCompile" 

### Expected Behavior
In the above build file, the gradle init should have generated with "compileOnly" rather "providedCompile" 

### Current Behavior

In the above build file, the gradle init generated with  "providedCompile" .

Error
 Could not find method providedCompile() for arguments [project ':CreditCardDBJPA'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### Context
We got into this problem when migrating existing maven projects into Gradle projects.

### Steps to Reproduce (for bugs)
Here are the projects generated from gradle init.
[TestProjects.zip](https://github.com/gradle/gradle/files/1786260/TestProjects.zip)

### Your Environment
------------------------------------------------------------
Gradle 4.5.1
------------------------------------------------------------

Build time:   2018-02-05 13:22:49 UTC
Revision:     37007e1c012001ff09973e0bd095139239ecd3b3

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (IBM Corporation 2.9)
OS:           Windows 10 10.0 amd64

**Comment by berkesokhan** [comment]
Bump! This is an important issue...
