### ISSUE TITLE
Application plugin "installDist" task fails on Linux in certain cases

### ISSUE THREAD

**Issue by FredDeschenes** [gradle/gradle#4627]
### Expected Behavior

The `installDist` task from the application plugin should work the same on all platforms.

### Current Behavior

On Linux, the plugin will sometimes tell you it failed the `installDist` task even though every thing seems to have worked anyway. This seems to be happening because of the `into "/my-java-service"` in my `build.gradle` file.
```shell
$ ./gradlew clean installDist distZip
:clean
:compileJava
:processResources NO-SOURCE
:classes
:jar
:startScripts
:installDist FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installDist'.
> /home/fdeschenes/gradle-installdist-broken/build/install/gradle-installdist-broken/bin does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
5 actionable tasks: 5 executed
```

Running `tree build/` will produce the same output in both Linux and Windows : 
```shell
$ tree build/
build
├── classes
│   └── java
│       └── main
│           └── Main.class
├── distributions
│   └── gradle-installdist-broken.zip
├── install
│   └── gradle-installdist-broken
│       ├── Dockerrun.aws.json
│       ├── my-java-service
│       │   ├── bin
│       │   │   ├── gradle-installdist-broken
│       │   │   └── gradle-installdist-broken.bat
│       │   └── lib
│       │       └── gradle-installdist-broken.jar
│       └── varnish
│           └── varnish.vcl
├── libs
│   └── gradle-installdist-broken.jar
├── scripts
│   ├── gradle-installdist-broken
│   └── gradle-installdist-broken.bat
└── tmp
    ├── compileJava
    └── jar
        └── MANIFEST.MF
```
Unzipping the output of `distributions/gradle-installdist-broken.zip` will produce the same content as the `install/` directory as expected.

### Context

Not a huge deal for me as in my case I know it works anyway, but I guess this might cause issues to other people. Workaround : use `distZip` or `distTar` and unzip/tar the archive.

This might also be broken on OSX, but I don't have a Mac available to test.

### Steps to Reproduce (for bugs)

- Clone this repo : https://github.com/FredDeschenes/gradle-installdist-broken
- Execute `./gradlew[.bat] installDist`

### Your Environment

 * Build scan URL (Arch Linux): https://scans.gradle.com/s/yilddgenhcyt2
 * Build scan URL (Windows 8.1): https://scans.gradle.com/s/l477j3ctqd2aq

**Comment by FredDeschenes** [comment]
I did a little more digging on this and figured out that the exception is being thrown by Ant's "chmod" task, called from `ApplicationPlugin::configureInstallTask`. Windows builds obviously skip this part, but on Linux (and I guess OSX) we end up in Ant's `AbstractFileSet::getDirectoryScanner(Project)`, which validates that the parent directory exists and throws if it doesn't (which always happens since the wrong path is sent to the `chmod` task by the application plugin).

I now wonder if that chmod is even necessary : I've commented it out, which fixed my build, and the start scripts (both the shell script and `.bat` file) have the executable bit set properly. The start scripts generated in `build/scripts` already have the bit set anyway, and the sync should keep the same permissions when syncing a file, so is there even a point of having this extra `chmod` done post-syncing?

**Comment by blindpirate** [comment]
Well, thanks for reporting, after looking into this, I think you're probably right. This looks unnecessary and might bring a little performance improvement. I'll try to remove this part when I have time. Or maybe you'd like to provide a PR :-)

**Comment by FredDeschenes** [comment]
Alright, I'll send a PR sometime today, thanks!
