### ISSUE TITLE
Track up-to-date state of closures in @Nested beans

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#4637]
When we have `@Nested` beans with closure objects, we currently only partly track their up-to-date-ness.  There have been some attempts to introduce some better tracking, but there are still some gaps (see https://github.com/gradle/gradle/pull/4531/files#r173014240).  We should find a way forward with this, potentially by just making `@Nested` objects with nested closures always out-of-date.

### Expected Behavior
We accurately capture changes to nested closures during up-to-date checks.

### Current Behavior
We detect a certain class of changes, but there are a number of gaps where we could incorrectly conclude that an object is up-to-date when it may not actually be (for instance when the delegate changes).

**Comment by lptr** [comment]
Does this apply to only closures in `@Nested` beans, or also to top-level properties?

**Comment by wolfs** [comment]
The current tracking should be fine for most use cases, and for other use-cases the inputs of the closure should be added separately.
