### ISSUE TITLE
Convert and move gradle/buildTagging.gradle to gradle/ci/build.gradle.kts

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#4641]
Conversion to Kotlin for dogfooding's sake.
Move to a separate directory to clearly state it's only used by CI.

**Comment by wolfs** [comment]
I think the file should be named `build.gradle.kts` and have a corresponding `settings.gradle.kts` right next to it. It should be invoked as a completely separate build.

**Comment by wolfs** [comment]
We ended up moving the file to the root build: #7346
