### ISSUE TITLE
Convert subproject build scripts to Kotlin

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#4649]
This issue is an umbrella issue to help us keep track of what remains to be done without creating a hundred issues upfront.

Project | 🤺 |  🏷 
--------|------|-----
~`:announce`~ | @eskatos |  #4110 
~`:antlr`~ | @hansd |  #4332
~`:base-services`~ | @hansd | #4332
~`:base-services-groovy`~ | @hansd | 32054e9c05d8a5b7624c848e20add6a2d4105b31
~`:build-cache`~ | @hansd | 74d4b94874a70e176d815f3f604b4b24108a51f5
`:build-cache-http` |
~`:build-comparison`~ | @hansd | #4565
`:build-init` |
~`:build-options`~ | @eskatos | #4668
`:build-scan-performance` |
`:cli` |
`:code-quality` |
~`:composite-builds`~ | @eskatos | #4668
`:core-api` |
`:core` |
~`:dependency-management`~ | @jjohannes | #4498
`:diagnostics` |
`:distributions` |
~`:distributions-dependencies`~ | @jjohannes | #4465 
`:docs` |
`:ear` |
`:ide-native` |
`:ide-play` |
`:ide` |
~`:installation-beacon`~ | @eskatos | #4110 
`:integ-test` |
~`:internal-android-performance-testing`~ | @eskatos | #4668
~`:internal-integ-testing`~ | @eskatos | #4668
~`:internal-performance-testing`~ | @eskatos | #4668
~`:internal-testing`~ | @eskatos | #4668
~`:ivy`~ | @jjohannes | #4498
`:jacoco` |
`:javascript` |
~`:jvm-services`~ | @eskatos | #4668
`:language-groovy` |
`:language-java` |
`:language-jvm` |
`:language-native` |
`:language-scala` |
`:launcher` |
`:logging` |
~`:maven`~ | @jjohannes | #4498
~`:messaging`~ | @eskatos | #4668
`:model-core` |
`:model-groovy` |
`:native` |
`:osgi` |
`:performance` |
`:persistent-cache` |
`:platform-base` |
`:platform-jvm` |
`:platform-native` |
`:platform-play` |
~`:plugin-development`~ |@eskatos |  #4110 
`:plugin-use` |
`:plugins` |
`:process-services` |
`:publish` |
`:reporting` |
`:resources-gcs` |
`:resources-http` |
`:resources-s3` |
`:resources-sftp` |
`:resources` |
~`:runtime-api-info`~ | @eskatos | #4110
`:scala` |
`:signing` |
`:smoke-test` |
`:soak` |
`:test-kit` |
`:testing-base` |
`:testing-junit-platform` |
`:testing-jvm` |
`:testing-native` |
~`:tooling-api-builders`~ | @eskatos | #4668
~`:tooling-api`~ | @wolfs | #4763
`:version-control` |
`:wrapper` |
~`:workers`~ | @eskatos | #4668

Please add your github handle to the table above when you consider doing some conversion and link your PRs to this issue.

**Comment by jjohannes** [comment]
All scripts have been converted except for `docs.gradle`. We have a separate follow up issue that covers converting `docs.gradle` to Kotlin DSL: https://github.com/gradle/gradle-private/issues/3135
