### ISSUE TITLE
Clearly document the behavior of multiple finalizer tasks

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#4650]
When a task has multiple finalizers, as `finalizedBy(t2, t1)`, there are various unknowns. The current implementation seems to be sorting the tasks alphabetically, so `t1` would run before `t2`. However, it's not clear if they are fired parallely, or if `t2` runs even if `t1` fails.

**Comment by jlstrater** [comment]
when updating this section of the documentation, please also add clarification around the text 

```
On the other hand, finalizer tasks are not executed if the finalized task didn’t do any work, for example if it is considered up to date or if a dependent task fails.
```
The confusion happens when the task it finalizes is not up to date. One proposal was to change the text to 'if they are up-to-date themselves'
