### ISSUE TITLE
Checksum Summary Files for gradle-checksum

### ISSUE THREAD

**Issue by edziegle** [gradle/gradle#4654]
### Expected Behavior

Per what I mentioned in this [issue](https://github.com/gradle/gradle-checksum/issues/2) on the [gradle-checksum](https://github.com/gradle/gradle-checksum) plugin, I am hoping to add the ability to produce xml and csv checksum summary files similar to how the [checksum-maven-plugin](https://checksum-maven-plugin.nicoulaj.net/examples/generating-checksum-summary-files.html) works. Essentially the user could define the `files` property for the plugin to generate checksums for, and then generate an xml or csv file containing all of those checksums.

Following the maven plugins example, the user could specify whether they want a csv or xml file (or both) and then provide the desired output paths. If the user provides no details about this, the plugin will not produce them and instead use its normal behavior (described below under 'Current Behavior'). When the user _does_ specify creating a summary file, the individual file creation should be disabled.

##### Test Cases
Ideally the report generation feature will use the checksum generating code that already exists, so I won't cover the test cases around that (eg, does the algo actually work, etc)
- When no summary file config is provided, it should not produce summary files
- When summary file config is provided, it should not produce individual checksum files
- Output dir can be specified
- Output file base name can be specified
- Removes previous report files before writing new ones
- Produced CSV file is a valid CSV file
- Produced XML file is a valid XML file
- It should gracefully fail on file permissions errors, eg can't create parent directory, or the summary file

One detail which may need more discussion is the actual output format: it could be similar to the maven plugin by producing a list of fileName:checksum for the csv, and xml output being:
```
<files>
    <file name='file name'>
        <hashcode algo='md5'>64724f0a5fe4f12148432a8f02aa4a40</hashcode>
    </file>
   ...
</files>
```

### Current Behavior

The plugin takes in a `FileCollection` and will generate an individual `.$algorithm` file (eg, .md5, .sha1, etc) for each file in the `FileCollection`. These checksum files are output to `$buildDir/checksums` by default, but the output dir can be specified.

### Context

I don't want to bore you with the precise details, but I am on a project that has these checksum summary files/reports as a part of our process (government certifications are involved); checksums for `.java`, `.class` and `.js` are included in the report. In the past we've used the checksum-maven-plugin to accomplish this step, but we'd like to move away from maven and have a holistic Gradle build, without having to reimplement this process in our code or an in-house tool. Having this as a part of Gradle is good for controllability/predictability of the process.

I got in touch with Mr. Lebeck-Jobe who seemed to be the original maintainer of the plugin for feedback on the idea, and he suggested that I bring the issue up here on the main issue board. I hope I am not being disruptive by duplicating this issue, I was just concerned that the plugin isn't being actively maintained/watched anymore. Reviewing the contribution guide, the language seems to suggest I should have brought this issue to the main board in the first place, so I apologize for placing it on the plugin board first.

**Comment by oehme** [comment]
No need to duplicate this issue here, since it's not about Gradle, but about that specific plugin. Let's talk there.
