### ISSUE TITLE
Gradle 4.6 JUnit 5 test can not found resources either in "src/main/resources" or "src/test/resources".

### ISSUE THREAD

**Issue by jaggerwang** [gradle/gradle#4662]
### Expected Behavior
When execute "./gradlew test" command, "application.properties" file under "src/main/resources" should be loaded, so the properties can get by using "System.getProperty".

### Current Behavior
Resources not loaded, even with coping to "src/test/resources".

### Context

**build.gradle**
```
apply plugin : 'application'

mainClassName = 'com.bicisims.qt.recvservice.Main'

dependencies {
    compile 'io.netty:netty-all:4.1.21.Final'
    compile 'org.apache.logging.log4j:log4j-api:2.10.0'
    compile 'org.apache.logging.log4j:log4j-core:2.10.0'
    compile 'org.mongodb:mongodb-driver:3.6.3'
    compile 'com.aliyun:hitsdb-client:0.0.5'
    compile 'org.apache.kafka:kafka-clients:0.10.0.0'
    compile 'org.apache.kafka:connect-json:0.10.0.0'
    compile 'com.aliyun.openservices:ons-sasl-client:0.1'
    compile 'com.fasterxml.jackson.core:jackson-core:2.9.4'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.9.4'
    compile 'com.fasterxml.jackson.module:jackson-module-parameter-names:2.9.4'
    compile 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.9.4'
    compile 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.9.4'
    compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    compile 'commons-codec:commons-codec:1.10'

    compileOnly 'org.projectlombok:lombok:1.16.18'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.1.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.1.0'
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}
```

**project structure**
![image](https://user-images.githubusercontent.com/1255011/37193296-1c328b9c-23a4-11e8-8c3b-00949081d1e2.png)

### Steps to Reproduce (for bugs)
Execute `./gradlew test`, test failed.

### Your Environment
 * Build scan URL: https://gradle.com/s/sitsqz6kmcl62

**Comment by oehme** [comment]
Why would these properties be available with `System.properties`? It's just some property file, so your code (or some framework you use) needs to load that file itself. Does this test work with JUnit 4 or in the IDE?

**Comment by jaggerwang** [comment]
Got it, Thanks!
