### ISSUE TITLE
Setting executableDir might make the start script unusable

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4675]
### Expected Behavior
If you set `executableDir` to `''` or to `'i/love/subdirectories/bin'`, the start scripts should still work as expected and if not feasible at least a validation of the value should be done and the build fail, but having it working would be more expected and wanted.

### Current Behavior
The calculateion of `APP_HOME` in the start scripts assume that the start script is exactly one directory layer below the distribution directory and thus fails to work properly if there are more or less layers.

### Your Environment
Gradle 4.6

**Comment by blindpirate** [comment]
Sorry for the late response, but I don't think so. According to https://github.com/gradle/gradle/blob/ecd4e22675a2d79adc02cafea1975508fd12cbf4/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt#L23 and https://github.com/gradle/gradle/blob/a41ab5a643bef06bd01fec04f770023c7316324f/subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/StartScriptTemplateBindingFactory.java#L178

We do render the start script with correct relative path. And I tried with `i/love/subdirectories/bin`, then run `installDist` and the generated script, all works well. Could you please provide a sample and detailed steps?

**Comment by Vampire** [comment]
I'm sorry, I was wrong about `'i/love/subdirectories/bin'`, that works fine.
But `''` does not work. In that case there is one `..` too much.

**Comment by blindpirate** [comment]
I see. Thanks for reporting and sorry for missing that.

**Comment by tomas-pluskal** [comment]
It seems setting ```executableDir``` to ```''``` still does not work with Gradle 5.4.1. 
Is there any workaround for that?

**Comment by tomas-pluskal** [comment]
FYI, I opened a new issue for this problem (#9351) and I submitted a pull request with the fix.

**Comment by Vampire** [comment]
Opening a PR is great @tomas-pluskal, but why did you open the exact same issue again as duplicate when you already know it is reported in this issue here? o_O

Besides that, the workaround is to either use a custom start script template or to post-process the existing one.

With Kotlin you can do it for example like

```kotlin
application {
    executableDir = ""
    mainClassName = "my.main.Class"
}

tasks.startScripts {
    doLast {
        unixScript.writeText(unixScript.readText()
                .replace("cd \"`dirname \\\"\$PRG\\\"`/..\" >/dev/null", "cd \"`dirname \\\"\$PRG\\\"`\" >/dev/null")
        )
        windowsScript.writeText(windowsScript.readText()
                .replace("set APP_HOME=%DIRNAME%..", "set APP_HOME=%DIRNAME%")
        )
    }
}
```
or accordingly with Gradle.

**Comment by tomas-pluskal** [comment]
Strange question, considering that nobody touched this issue for more than a year.. o_O

How about the PR? I would prefer to fix the issue rather than use workarounds.

**Comment by Vampire** [comment]
As I said, PR is great (per-se, didn't review).
Just wait some time, usually the Gradle guys are relatively fast in accepting PRs, or at least looking at them.

**Comment by tomas-pluskal** [comment]
It seems the commit that was supposed to fix this issue only fixed the unix start script, but not the Windows start script. This issue still remains on Windows. See #10387
