### ISSUE TITLE
Support capturing logs from JavaCompile tasks

### ISSUE THREAD

**Issue by davidburstromspotify** [gradle/gradle#4678]
### Expected Behavior
Much like it is possible to capture process output from JavaExec tasks, it should be possible to capture output from JavaCompile. The means of specifying the output sink with the DSL is up to Gradle to decide upon.

### Current Behavior
Using the logging configuration for JavaCompile tasks to add output listeners does not work the way users expect. During parallel execution of JavaCompile tasks, each output listener added to each task will see the output of the other tasks.
It is also not possible to use the "-Xstdout" flag in javac, as it is not supported by the supplied compiler in Gradle.

### Context
To provide the most value from a CI build, it is useful to specify "--continue". The problem is that compilation issues for a given task is difficult to find in a lengthy build log, and because of parallel execution, it can even be difficult to correlate the output with the correct task. In a CI setting, we would like to export the output from each failed task into individual files and report them at developer convenience.

**Comment by stephanenicolas** [comment]
Thx so much for opening this issue. On our side we are trying to filter the deprecation warnings and store them in a file. But there is no way to prevent a JavaCompile task from.logging. 

It is probably due to the daemonesque nature of compilation, but it would really nice to have this working or -Xstdout being supported.

**Comment by stephanenicolas** [comment]
I checked the source code and the issue with `-Xstdout` comes from javac itself. The only solution would be to redirect the output stream of the compiler, which seems possible. It could be added to the JavaCompileSpec and passed to `org.gradle.api.internal.tasks.compile.JdkJavaCompiler#createCompileTask`. The first argument is a writer that receives the errors.

**Comment by stephanenicolas** [comment]
I checked the source code and the issue with `-Xstdout` comes from javac itself. The only solution would be to redirect the output stream of the compiler, which seems possible. It could be added to the JavaCompileSpec and passed to `org.gradle.api.internal.tasks.compile.JdkJavaCompiler#createCompileTask`. The first argument is a writer that receives the errors.

**Comment by stephanenicolas** [comment]
Great to see this getting prioritized ! @ghale

**Comment by trejkaz** [comment]
Ah, is there absolutely no way to do this right now? I am looking for a workaround for there being no obvious way to capture and count warnings. :(

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue will be closed as a duplicate of

* https://github.com/gradle/gradle/issues/2408

Please add your use case and 👍 to that issue.

If you think our analysis is wrong, please provide us with more detailed information explaining why.
