### ISSUE TITLE
Allow javac Argument Files passing to compilerArgs in JavaCompile task

### ISSUE THREAD

**Issue by soberich** [gradle/gradle#4679]
### Expected Behavior

`compilerArgs.add("@javacArgs")`
or
`compilerArgs.add("@\"C:/path/to/file/javacArgs\"")`
or
`compilerArgs.add("@\"${rootProject.projectDir.path}/javacArgs\"")`

or any other suitable variant (with quotes or not, etc.) which DOES work with direct java invocation
works in gradle

### Current Behavior
```
execution failed for task ':compileJava'.
> invalid flag: @"C:\path\to\file\javacArgs"
```

### Your Environment
WITH or WITHOUT IDE does not matter. Still does not work

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          **9.0.4 (Oracle Corporation 9.0.4+11)** OR **1.8 (Oracle Corporation 1.8+162)**
OS:           Windows 10 10.0 amd64

IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.4096.5, built on March 6, 2018
IntelliJ IDEA EAP User
Expiration date: April 5, 2018
JRE: 1.8.0_152-release-1136-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Windows 10 10.0

**Comment by oehme** [comment]
What would be the benefit of this feature? Why not use the DSL to define arguments?

**Comment by soberich** [comment]
I use java8Args separately from java9Args for example.
I understand that could be done in many ways which are workarounds.
This is a matter of choice and preferences. Maybe some one, like me, prefer to separate "concerns" in different configuration files as much as possible e.g. javac args in @javacArg file
Arg files are very native Java feature. I consider so much native and quite simple feature could be supported by any jvm tool like build tool.
So, the answer is - separation and maintenance of different environments (instead adding more code in build logic, like `if (..isJava9Compatible) else if (..isJava8Compatible)`)

**Comment by wrotte** [comment]
Such files would be more compact and easier to write and maintain.  compilerArgs.addAll(['putting', 'some'] ) compilerArgs << "delimiters" << "between" << "arguments" make s them tedious to write and change. 

Moreover, it currently appears that the JavaCompile task does sanity checking on arguments before passing them to javac - I am for example trying to change the garbage collector used by javac using the option '-XX:+UseConcMarkSweepGC', which results in an error diagnostic that it is an invalid flag. 

This mechanism could be used as a way to say 'just trust me' when using nonstandard options.

**Comment by oehme** [comment]
We can't "just trust" such a file, we'd read it and handle the arguments inside it just as if you had added them through the DSL. Otherwise we would potentially miss important flags that influence the tasks's output and thus break up-to-date checking and caching. The `-XX` flag should not be a problem. If that doesn't work, please open a separate issue.

**Comment by soberich** [comment]
@oehme 
Kotlin 1.2.50 is also adding support for arg files
https://youtrack.jetbrains.com/issue/KT-24472

**Comment by soberich** [comment]
1.3 is out and here is a link to issue tracker to track progress
https://youtrack.jetbrains.com/issue/KT-24613
This will really clean up the code since now it is like 
```kotlin
        freeCompilerArgs += arrayOf(
            "-Xuse-experimental=kotlin.ExperimentalUnsignedTypes",
            "-XXLanguage:+InlineClasses",
            "-Xjsr305=strict",
            "-java-parameters",
            "-Xenable-jvm-default"
        )
```
and 
```kotlin
tasks {
        withType<JavaCompile> {
            options.apply {
                encoding = UTF_8.name()
                isIncremental = true
                // compiler deamon JVM options
//                isFork = true // FIXME: Reported a bug https://github.com/rzwitserloot/lombok/issues/1603
//                forkOptions.jvmArgs = project.extra["org.gradle.jvmargs"].toString().split(" ")
                // javac tasks args file, but does not work
                // tried replace special characters - no luck
                // turn out Gradle does not support this, see https://github.com/gradle/gradle/issues/4679
//                compilerArgs.add("@" + project.rootDir.absolutePath.replace(Regex("(?<=[(,])([^(),]* [^(),]*)(?=[),])"), " \"\$1\"").replace('\\', '/') + "/javac" + current().majorVersion + "Args")
                // Could be like this, but this is not lesser ugly
//                file(rootDir.path + "/javac" + current().majorVersion + "Args").useLines { it.forEach { compilerArgs.add(it) } }
                compilerArgs.addAll(arrayOf(
                    "-Xlint",
                    "-Xlint:-processing",
                    "-Xdiags:verbose",
                    "-Adebug=false",
                    "-AaddGenerationDate=true",
                    "-parameters",
                    "-Amapstruct.defaultComponentModel=$componentModel"
                ))
            }
        }
    }
```
