### ISSUE TITLE
Replace CommandLineArgumentProvider with ListProperty

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4685]
In Gradle 4.6 we introduced a `List< CommandLineArgumentProvider>` on the compile and exec tasks. This could be replaced with the more generic `ListProperty<String>`, which would cover all cases:

- adding simple String arguments (thereby also superseding `getJvmArgs`) 
- adding a single lazy String
- adding a lazy set of Strings

**Comment by lptr** [comment]
I'm not sure what you mean. Do you mean using `ListProperty<String>` (this we have), or are you suggesting introducing `ListProvider<String>` as a new thing? Should users extend either `ListProperty` or this new `ListProvider` somehow? How would that type be instantiated?

Notice that a single `CommandLineArgumentProvider` can produce 0 or more `String` arguments, so I guess you'd need `List<ListProvider<String>>` to replace `List<CommandLineArgumentProvider>`.

We could have that, I guess, but I think `CommandLineArgumentProvider` has a very specific purpose, and it's better to capture it as a thing itself: we are not just producing `String`s here, but `String`s to be passed on the command-line that need to have their own annotated inputs and outputs. If we had a thing like `ListProvider<String>`, `CommandLineArgumentProvider` could extend that interface, but I would keep `CommandLineArgumentProvider` even then.

**Comment by oehme** [comment]
Sorry I meant `ListProperty`. You can add a `Provider<List<String>>` to that ListProperty if you want to compute multiple arguments at once. Providers are instantiated using `project.objects.provider`. 

I don't see a need for a special-purpose type, it just makes the DSL less streamlined in my opinion. //cc @big-guy since you wanted to push Providers into more of our plugins.

**Comment by lptr** [comment]
I'm still not sure how this would work. A good exercise would be to show how `JacocoAgent` would be implemented with such a setup.

**Comment by oehme** [comment]
Okay so the problem is that you want it to be a `@Nested` object with annotated input properties which are used for up-to-date checking instead of the computed value. This is indeed not possible with Providers right now as far as I can see. I think it should be though, otherwise I fear we'll reinvent this pattern several times. I.e. command line arguments are not the only thing that should be computed from more structured data. Jar manifest entries come to mind as a different example.

**Comment by lptr** [comment]
Yes, this is exactly what `CLAP` was designed to be. I think it's alright to have these types, too. What would we gain if we had this thing as a `ListProvider<String>`?

**Comment by oehme** [comment]
Consistency. Why have two properties `List<String> jvmArgs` + `List<CLAP> jvmArgProviders` when we could have one `ListProperty<String> jvmArgs`?

I mean do we really want to create the equivalent of `CLAP` for every property that needs to be turned into a list if Strings and could be derived from richer data? Clearly for the Jar manifest case the name "CommandLineArgumentProvider" doesn't make sense. Wouldn't it be much better to have one type for this that we can use everywhere? I think that's exactly what `ListProperty` should be.

**Comment by lptr** [comment]
The `jvmArgs` property was left in place solely for backwards compatibility. We would have done the same if we introduced it as `List<ListProperty<String>>`. (Again, a single level `ListProperty<>` wouldn't work, as you want to be able to have multiple providers that each can provide lists of arguments.)

I think it's okay to create the equivalent for `CLAP` for some concepts. Command-line arguments is one of those things, as they have multiple uses and capture a real-world concept. We already use them in multiple places (`Exec` task parameters, `jvmArgs`, options for the Java compiler), and expect to use it in other command-line tool invoking tasks, e.g. native compilers, linkers etc.

I just saw that we have `ListProperty<String> compilerArgs` in `AbstractNativeCompileTask` – we'll need to change that somehow to be able to pass rich command-line arguments to native compilers.

Can you elaborate on how this collides with your expectations about Jar manifest handling?

**Comment by wolfs** [comment]
@oehme I think one important piece is still missing from the discussion: We expect plugin authors to implement `CommandLineArgumentProvider`s, while the `Provider`/`Property` interfaces should never be implemented by them.

The whole point of the interface is that a plugin author can implement it. The lazyness is not important.

We could have added a `ListProperty<CommandLineArgumentProvider>`, but we decided against it, since the whole task does not use providers at all and we were not sure how ready `ListProperty` is for prime time.

I guess the `Provider` in `CommandLineArgumentProvider` is misleading - a `CommandLineArgumentProvider` is not a `Provider`. Maybe we should come up with a better name. How about `CommandLineArguments`?

There also was some discussion on the [design doc](https://docs.google.com/document/d/13mqMnJkeyR6Y9QpaaGXrZ3ycWoPRB8xFsaZsVLQk318/edit#heading=h.vjt0d6rxoebr).

**Comment by oehme** [comment]
> We would have done the same if we introduced it as List<ListProperty<String>>. (Again, a single level ListProperty<> wouldn't work, as you want to be able to have multiple providers that each can provide lists of arguments.)

I think you misunderstand how ListProperty works. You can totally add a Provider to it that computes multiple arguments at once. As I mentioned earlier, ListProperty supports adding `T`, `Provider<T>` and `Provider<List<T>>`

> I just saw that we have ListProperty<String> compilerArgs in AbstractNativeCompileTask – we'll need to change that somehow to be able to pass rich command-line arguments to native compilers.

That's why I'm saying we should improve ListProperty and Provider so that users can treat them as `@Nested`. 

> Can you elaborate on how this collides with your expectations about Jar manifest handling?

Well according to your argument we would have to introduce `ManifestEntryProvider` similar to `CommandLineArgumentProvider`. My point is that both are just lazy lists of Strings and we should use `ListProperty<String>` for such lists.

> The whole point of the interface is that a plugin author can implement it. 

I don't see a good reason why we wouldn't allow some way to create a provider with nested fields. You currently pass a `Callable` to `project.objects.provider`, that `Callable` could have annotated fields.

I'd really like to hear @big-guy or @adammurdoch take on this.

**Comment by lptr** [comment]
I don't see why it would be a problem if we introduced a `ManifestEntryProvider`. If the use case is to produce manifest entries, I think you'd actually want a different API, something like:

```java
interface ManifestEntryProvider {
    Map<String, String> asManifestEntries();
}
```

I'm still curious how you imagine something like `JacocoAgent` or a manifest entry provider to be implemented by a plugin developer or a build author with `Provider`s only.

**Comment by oehme** [comment]
```
JacocoAgent implements Callable<String> {
  @InputFiles
  FileCollection jacocoPath
  
  String call() {
    //compute agent path here
  }
}
```

```
Test {
  //This isn't supported yet, but should in my opinion. Instead of snapshotting the return value of the providers it would snapshot the input properties of each provider added to this list.
  @Nested 
  ListProperty<String> getJvmArguments()
}
```

```
test.jvmArguments.add(objects.provider(new JacocoAgent(configurations.jacoco))
```

**Comment by ldaley** [comment]
I raised this generally in the preliminary discussion about `CommandLineArgumentProvider`. I thought we should look to reuse providers, but I now think that's wrong. However, I still think that a myriad of orthogonal bespoke types for every case (in reality, the ones we consider important enough to do this extra work for) is the wrong direction.

I think we should aim to simplify things to three concepts:

1. Providers - only provide execution integration machinery (e.g. lazy computation, task dependencies)
2. Value types - RegularFile, Directory etc.
3. Type representations/transformations/coercions (i.e. what `CommandLineArgumentsProvider` is) - needs a catchy name

We have, mistakenly in my opinion, complected (1) and (2) with things like `ListProvider` and `RegularFileProvider`. Where's my `LockableListProvider`? Where does this stop? I think provider should be always be absolutely value agnostic and be _only_ concerned with execution mechanics. But that's another issue.

`CommandLineArgumentsProvider` should be replaced by something like `Value<T>` or  `As<T>`. This would have a single no arg method that returns the logical thing as `T`. So `CommandLineArgumentsProvider` becomes `As<List<String>>`. We would provide various out of the box type coercions, either via `objects` or via the value types themselves, e.g.

```
objects.asAbsolutePath(regularFile) // returns `As<String>`, but implementation has appropriate `@InputFile` etc annotations.

// or on regularFile

regularFile.asAbsolutePath() // like above
 
```

`Provider` would not implement `As`. They are different concerns. But you could have a `Provider<As<List<String>>>`. 

 This highlights a hurdle to this generic approach, in that many will find it not aesthetically pleasing to have so many `<>` flying around. Moreover, declaration site covariance and contravariance exacerbates this problem with `Provider<As<? extends List<String>>>` being required in a few places. 

However, if we and users can accept this, I think we get a lot. The benefit of a simple, universal and _composable_ programming model would go a long way. With the proliferation of `Provider` implementations and types like `CommandLineArgumentsProvider` I think we are headed in the opposite direction of further complecting the programming model by introducing too many bespoke concepts.

**Comment by lptr** [comment]
I like this separation of concerns, and is in-line with making `CommandLineArgumentProvider` more generic iteratively. In 4.5 we had `CompilerArgumentProvider` that has been extended to the more general `CommandLineArgumentProvider` in 4.6. I can see us taking it to this new place eventually. My only concern is not to end up with a deep type system that we try to model with Java's generics.

**Comment by ldaley** [comment]
> My only concern is not to end up with a deep type system that we try to model with Java's generics.

I am concerned about this too, but I would like to really explore the benefits before writing it off. My intuition is that we could come up with something very, small, simple and powerful with this approach and it might in the end outweigh the emotional barrier of nested parameterised types.

**Comment by oehme** [comment]
We should also think about what this would look like in Kotlin. Maybe some of its features would make what Luke is proposing look more pleasing.
