### ISSUE TITLE
Can not load docker image compressed with Tar task

### ISSUE THREAD

**Issue by Tooa** [gradle/gradle#4688]
* I receive an error when loading (`docker load`) an exported docker image (`docker save`) gzipped with `gzipImageWithTarTask` (see also `doesNotWork.sh`). 
* Whereas loading an exported docker image gzipped with `gzipImageWithExecTask` is loaded fine (see also `works.sh`).

Minimal example ([minimal_example.tar.gz](https://github.com/gradle/gradle/files/1804258/minimal_example.tar.gz)) attached.

***build.gradle***
```gradle
plugins {  id 'java-library' }

dependencies { }

repositories {
    jcenter()
}

task gzipImageWithTarTask(type: Tar) {
    from buildDir
    include 'alpine'
    destinationDir buildDir
    archiveName = 'alpine.gz'
    compression = Compression.GZIP
}

task gzipImageWithExecTask(type: Exec) {
    workingDir buildDir
    commandLine "gzip", "-k", "alpine"
}
```

### Expected Behavior

I am able to load the gzipped image (created with the `gzipImageWithTarTask` task) via `docker load -i alpine.gz` i.e.

```
~/Desktop/gradle-tar-test/build $ docker load -i alpine.gz 
Loaded image: alpine:latest
```

### Current Behavior

Loading the gzipped image returns the following error:

```bash
~/Desktop/gradle-tar-test/build $ docker load -i alpine.gz 
open /var/lib/docker/tmp/docker-import-507029262/repositories: no such file or directory
```

### File size differs between the two provided versions

* File `alpine.gz.gradle` is generated with the `Tar` task.
* File `alpine.gz.gzipShell` is generated with the `Exec` task.

```
~/Desktop/gradle-tar-test/build $ ls -al
total 8248
drwxr-xr-x 2 user user    4096 Mär 12 20:01 .
drwxr-xr-x 6 user user    4096 Mär 12 19:59 ..
-rw------- 1 user user 4412416 Mär 12 20:00 alpine
-rw-r--r-- 1 user user 2005813 Mär 12 20:00 alpine.gz.gradle
-rw------- 1 user user 2009247 Mär 12 20:00 alpine.gz.gzipShell
```

### Steps to Reproduce (for bugs)

* Execute `doesNotWork.sh` to see the error case.
* Execute `works.sh` to see the expected behavior.

### Your Environment

* Gradle 4.6 using the Gradle Wrapper

**Comment by lacasseio** [comment]
The `Tar` task does more than just compression, it also, as the name implies, create a tar archive. In other words, the `Tar` task would produce a `.tar.gz` file. It would be recommended to use the `Exec` task if compression is the only thing that is required.
