### ISSUE TITLE
Could not create SecurityManager: worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager

### ISSUE THREAD

**Issue by gregmeraz** [gradle/gradle#4689]
We have been getting the following stack trace when the :test task gets executed:

```
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager: worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager
	at sun.misc.Launcher.<init>(Launcher.java:106)
	at sun.misc.Launcher.<clinit>(Launcher.java:57)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1448)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1433)

Could not write standard input to Gradle Test Executor 2.
java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:66)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:51)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
:test FAILED

FAILURE: Build failed with an exception
```

### Expected Behavior
Test suite should be initialized without issues and build should go fine. On local enviroments it is working as expected

### Current Behavior
Getting exception each time the test task gets executed, the only way the test task passes is if we comment out all the test classes. Even a dummy test class with assert true will break the build.
we have tried with spock, junit and testNG and all give the same exception even with dummy test classes.

### Context
We have tried already by deleting the .gradle/caches folder and still no luck.
We also tried by overriding the SecurityManager and it still gave the same exception.
Our theory is that the gradle-worker.jar generated by :compileGroovy task is not working as expected.

As a note, if we skip the tests and build the app, it works fine and as expected, its only the test task which seems to be failing.

### Your Environment
The build is being done with Jenkins in a LINUX slave server with Java 8, grails 3 and groovy.
Gradle being used is 4.6 but we had tried also with 3.5 and is the same error.

**Comment by blindpirate** [comment]
Thanks for reporting. I suggest you to do as follows:

- Run your tasks/params with extra `--info`, e.g. `gradle test --info`
- You'll find the line `Starting process 'Gradle Test Executor X'. Working directory: XXX Command: XXX`

In my machine it looks like this: 

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Djunit.version=4.12 -Dorg.gradle.native=false -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /Users/zhb/.gradle/caches/4.5/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 3'
```

Note the `-cp /Users/zhb/.gradle/caches/4.5/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain` part.

Check if the `<HOME>/.gradle/caches/4.5/workerMain/gradle-worker.jar` exists. If not, try to delete the whole `<HOME>/.gradle/caches/4.5` as a [workaround](https://discuss.gradle.org/t/java-lang-internalerror-could-not-create-securitymanager-jarjar-org-gradle-process-internal-child-bootstrapsecuritymanager/2478/14).

The detail of this bug is still not clear, if you could provide us with a minimum reproducible sample that would be great.

**Comment by gregmeraz** [comment]
hi @blindpirate 
I added the --info argument to the build and this is what we get:

```
Task ':test' is not up-to-date because:
  Task has failed previously.
Starting process 'Gradle Test Executor 2'. Working directory: /srv/jenkins_linux_workspace/workspace/projectName Command: /usr/local/java/versions/jdk1.8.0_65/bin/java -Dgrails.env=test -Dgrails.full.stacktrace -Dinfo.app.grailsVersion=3.3.0 -Dinfo.app.name=LDAPIServices -Dinfo.app.version=0.1 -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 "-XX:-UseSplitVerifier -Xverify:none" -XX:-UseSplitVerifier -Xverify:none -Xms512m -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /home/pebuild/.gradle/caches/4.6/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 2'
Successfully started process 'Gradle Test Executor 2'
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager: worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager
	at sun.misc.Launcher.<init>(Launcher.java:106)
	at sun.misc.Launcher.<clinit>(Launcher.java:57)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1448)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1433)

Could not write standard input to Gradle Test Executor 2.
java.io.IOException: Broken pipe
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:66)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:51)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
:test FAILED
:test (Thread[Task worker for ':',5,main]) completed. Took 1.416 secs.
```

maybe the jenkins user does not have permissons to copy inside the build server?

I did verify tath the gradle-worker.jar exists and it it, i even deleted and it gets automatically created again during :compileGroovy task.

we have trying by deleting the caches folder but not the whole path for .gradle

**Comment by gregmeraz** [comment]
we have not been able to replicate the issue on our locals :(

**Comment by tsgautier** [comment]
I'm seeing this error intermittently on my local machine which is Mac OS X High Sierra.

Happens with both Gradle 4.6 and Gradle 4.7.  

I see it most frequently *after* I remove the ~/.gradle/caches directory to refresh all libraries and then run gradle test, something like:

$ rm -rf ~/.gradle/caches; ./gradlew test

Running gradle test immediately after getting this error results in success.

**Comment by tsgautier** [comment]
More details:

This happens almost every time I refresh the cache.  

I am using Gradle 4.7 with the Junit 5 Jupiter engine tests enabled via:

test {
  useJunitPlatform()
}

**Comment by blindpirate** [comment]
@tsgautier Thanks for the information, I've already reproduced it. I'll investigate it.

**Comment by geoHeil** [comment]
I think you need to kill the daemon after clearing the caches - then everything works fine again.

**Comment by gregmeraz** [comment]
I had forgotten to updated this issue...

So, basically, after a month of debugging, the issue was that on the jenkins job of the build there were some parameters being passed to the vm that were making the gradle tests to crash.

GRAILS_OPTS="-XX:-UseSplitVerifier -Xverify:none"

we removed that

**Comment by KaleRoberts** [comment]
I suggest running ./gradlew --stop (if you're running gradle wrapper from your local project) or gradle --stop
That will stop the running daemon and should allow you to run the commands you need

**Comment by bandhammanikanta** [comment]
> We have been getting the following stack trace when the :test task gets executed:
> 
> ```
> Error occurred during initialization of VM
> java.lang.InternalError: Could not create SecurityManager: worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager
> 	at sun.misc.Launcher.<init>(Launcher.java:106)
> 	at sun.misc.Launcher.<clinit>(Launcher.java:57)
> 	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1448)
> 	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1433)
> 
> Could not write standard input to Gradle Test Executor 2.
> java.io.IOException: Broken pipe
> 	at java.io.FileOutputStream.writeBytes(Native Method)
> 	at java.io.FileOutputStream.write(FileOutputStream.java:326)
> 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
> 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
> 	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:66)
> 	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:51)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
> 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
> 	at java.lang.Thread.run(Thread.java:745)
> :test FAILED
> 
> FAILURE: Build failed with an exception
> ```
> ### Expected Behavior
> Test suite should be initialized without issues and build should go fine. On local enviroments it is working as expected
> 
> ### Current Behavior
> Getting exception each time the test task gets executed, the only way the test task passes is if we comment out all the test classes. Even a dummy test class with assert true will break the build.
> we have tried with spock, junit and testNG and all give the same exception even with dummy test classes.
> 
> ### Context
> We have tried already by deleting the .gradle/caches folder and still no luck.
> We also tried by overriding the SecurityManager and it still gave the same exception.
> Our theory is that the gradle-worker.jar generated by :compileGroovy task is not working as expected.
> 
> As a note, if we skip the tests and build the app, it works fine and as expected, its only the test task which seems to be failing.
> 
> ### Your Environment
> The build is being done with Jenkins in a LINUX slave server with Java 8, grails 3 and groovy.
> Gradle being used is 4.6 but we had tried also with 3.5 and is the same error.

remove the environment property for gradle and delete .gradle folder from your home directory.
If you are not able to delete .gradle folder. then, remove environment property and restart your machine and then delete. now hit "gradle -v" in cmd. it will reconfigure your gradle. (we reconfigured this to get "gradle-worker.jar" which will be downloaded on reconfiguring.)

**Comment by bandhammanikanta** [comment]
Remove the environment property for gradle and delete .gradle folder from your home directory.
If you are not able to delete .gradle folder. then, remove environment property and restart your machine and then delete. now hit "gradle -v" in cmd. it will reconfigure your gradle. (we reconfigured this to get "gradle-worker.jar" which will be downloaded on reconfiguring.)

**Comment by bandhammanikanta** [comment]
> Thanks for reporting. I suggest you to do as follows:
> 
> * Run your tasks/params with extra `--info`, e.g. `gradle test --info`
> * You'll find the line `Starting process 'Gradle Test Executor X'. Working directory: XXX Command: XXX` in log
> 
> In my machine it looks like this:
> 
> ```
> /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Djunit.version=4.12 -Dorg.gradle.native=false -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /Users/zhb/.gradle/caches/4.5/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 3'
> ```
> Note the `-cp /Users/zhb/.gradle/caches/4.5/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain` part.
> 
> Check if the `<HOME>/.gradle/caches/4.5/workerMain/gradle-worker.jar` exists. If not, try to delete the whole `<HOME>/.gradle/caches/4.5` as a [workaround](https://discuss.gradle.org/t/java-lang-internalerror-could-not-create-securitymanager-jarjar-org-gradle-process-internal-child-bootstrapsecuritymanager/2478/14).
> 
> The detail of this bug is still not clear, if you could provide us with a minimum reproducible sample that would be great.

Here, to get "gradle-worker.jar",

Remove the environment property for gradle and delete .gradle folder from your home directory.
If you are not able to delete .gradle folder. then, remove environment property and restart your machine and then delete. now hit "gradle -v" in cmd. it will reconfigure your gradle. (we reconfigured this to get "gradle-worker.jar" which will be downloaded on reconfiguring.)

**Comment by ripla** [comment]
@oehme how does that advice relate to e.g. the recommended config for a Travis build, which has `rm -fr $HOME/.gradle/caches/*/plugin-resolution/`? Or is this bug about deleting the *whole* `caches` directory?

**Comment by h2hjastermereel** [comment]
> I suggest running ./gradlew --stop (if you're running gradle wrapper from your local project) or gradle --stop
> That will stop the running daemon and should allow you to run the commands you need

This was the answer for me. I started always running my builds such as:

gradlew --stop && gradlew clean build

**Comment by big-guy** [comment]
Please reopen this issue if someone finds a way to reproduce a problem with worker processes failing to start.

@h2hjastermereel Neither of those things should be necessary (running `--stop` and running clean all the time).  You're effectively running without the daemon, which means you'll pay the start-up cost penalty for the daemon without ever re-using it.  If you're running into issues, please open an issue.  Thanks!

**Comment by christopherbryanboyd** [comment]
@big-guy Hi, we are seeing this issue on our jenkins server, when jenkins is running gradle (wrapper, tried both 4.10.2 and 5.2.1).
We don't see it when manually invoking gradle from the CLI.
It's a Windows Server running Java 8_202.
At this point we're not sure how to solve the issue, it just started happening one day about 2 weeks ago. I disabled all of the junit tests, but the error still occurs when jenkins invokes the `test` task.
The daemon is completely disabled, we run `gradlew --stop` first, and include the `--no-daemon` flag when running the tests, and another `gradlew --stop` when done.
The error happens every time, when gradlew is invoked by jenkins.

**Comment by big-guy** [comment]
@christopherbryanboyd It sounds like you may be running into a different problem with a similar symptom.   Could you open a new issue with some of the things you've tried? Thanks!

**Comment by christopherbryanboyd** [comment]
@big-guy will do, thank you

**Comment by rafaelCarinha** [comment]
Old thread, but this happened to me also, when I deleted the gradle caches folder.
I have 2 jdks configurations (openjdk and oracle jdk). 
Changing the jdk solved my problem.

**Comment by smallwenzi** [comment]
after I delete gradle cache folder (gradle_user_home folder) ,I compiled success .

**Comment by alienwings** [comment]
If you have deleted caches directory and you don't want to delete the whole gradle_user_home folder, you can delete daemon directory only. I have verified the case.

**Comment by orubel** [comment]
The solution to this is easier than you know:

`./gradlew --stop;./gradlew clean;./gradlew build`

**Comment by jabrwoky** [comment]
In my case it wasn't a leading space in GRAILS_OPTS,  it was _two consecutive_ spaces. Once I correct that, things returned to normal.

**Comment by felixchaureed** [comment]
> In my case it wasn't a leading space in GRAILS_OPTS, it was _two consecutive_ spaces. Once I correct that, things returned to normal.

You saved my life. Wasted countless hours on it.....

**Comment by wukangxin** [comment]
The scenario I encountered is that the `<HOME>/.gradle/caches/6.7.1/workerMain/gradle-worker.jar` does not exist. During compilation, it is found that four threads are executed concurrently. Considering that multi-thread conflicts may exist, the four threads are modified to single-thread compilation to solve this problem.
Actions performed:
delete caches folder : ` «HOME> / .gradle/caches`
Add  `org.gradle.workers.max=1 `to the gradle.properties file.
Execute compile cmd :  `./gradlew clean build -x test --stacktrace --info` 

The gradle.properties file is modified due to other problems. The final configuration is as follows:


```
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Duser.timezone=UTC -Dfile.encoding=UTF-8
toolchain.compiler.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Duser.timezone=UTC -Dfile.encoding=UTF-8
toolchain.javadoc.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Duser.timezone=UTC -Dfile.encoding=UTF-8
toolchain.launcher.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Duser.language=en -Duser.country=US -Duser.timezone=UTC -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
systemProp.gradle.ssl.disabled=true
systemProp.socks.proxyHost=${your proxy host}
systemProp.socks.proxyPort=${your proxy port}
systemProp.socks.proxyUser=${your proxy user}
systemProp.socks.proxyPassword=${your proxy password}
systemProp.http.proxyHost=${your proxy host}
systemProp.http.proxyPort=${your proxy port}
systemProp.http.proxyUser=${your proxy user}
systemProp.http.proxyPassword=${your proxy password}
systemProp.https.proxyHost=${your proxy host}
systemProp.https.proxyPort=${your proxy port}
systemProp.https.proxyUser=${your proxy user}
systemProp.https.proxyPassword=${your proxy password}
systemProp.http.nonProxyHosts=${your not proxy host}
systemProp.https.nonProxyHosts=${your not proxy host}
org.gradle.workers.max=1

```

> Thanks for reporting. I suggest you to do as follows:
> 
> * Run your tasks/params with extra `--info`, e.g. `gradle test --info`
> * You'll find the line `Starting process 'Gradle Test Executor X'. Working directory: XXX Command: XXX` in log
> 
> In my machine it looks like this:
> 
> ```
> /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Djunit.version=4.12 -Dorg.gradle.native=false -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /Users/zhb/.gradle/caches/4.5/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 3'
> ```
> 
> Note the `-cp /Users/zhb/.gradle/caches/4.5/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain` part.
> 
> Check if the `<HOME>/.gradle/caches/4.5/workerMain/gradle-worker.jar` exists. If not, try to delete the whole `<HOME>/.gradle/caches/4.5` as a [workaround](https://discuss.gradle.org/t/java-lang-internalerror-could-not-create-securitymanager-jarjar-org-gradle-process-internal-child-bootstrapsecuritymanager/2478/14).
> 
> The detail of this bug is still not clear, if you could provide us with a minimum reproducible sample that would be great.
