### ISSUE TITLE
Can we make JavaVersion APIs public?

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#4692]
File: https://github.com/gradle/gradle/blob/27127bed9b655e41857aee3528275c4b8a3dc3da/subprojects/base-services/src/main/java/org/gradle/api/JavaVersion.java#L119

`isJava8`, `isJava9`, and `isJava10` should be public. Would you accept a PR for this?

**Comment by melix** [comment]
-1 on making it public, this one because it's terribly weak. We are currently thinking about changing this API, to not rely on an enum.

However, strong +1 on having a public API to deal with the "Gradle runtime environment".

**Comment by jaredsburrows** [comment]
So, -1 + 1 = 0? What?

**Comment by melix** [comment]
Sorry I thought my comment was clear:

- -1 on making `JavaVersion` public
- +1 on creating a new public API for "Gradle runtime environment" which exposes methods to know about the Java runtime

**Comment by jaredsburrows** [comment]
What are you thinking about changing this API to? For now, the methods should be public. I do not know why they are private in the first place.

**Comment by melix** [comment]
I think we can proceed in 2 steps:

1. change the visibility of `isJava8` and friends to `public`, because the current API is public
2. provide a new API that is forward-compatible and doesn't rely on an enum and us updating everytime a new JDK is out

**Comment by jaredsburrows** [comment]
We can do both. I can make a PR for 1. Then when you decide on 2, I can make a PR for that.

**Comment by blindpirate** [comment]
Closed by #4759 . Still much thanks @jaredsburrows !

**Comment by jaredsburrows** [comment]
Nice.
