### ISSUE TITLE
Changed task definition should cause up-to-date check to fail?

### ISSUE THREAD

**Issue by gustafg** [gradle/gradle#4729]
I was experimenting with the Sync task as I wanted to port an old Ant script that copies files from a set of directories to another set of directories using the copy task having the flatten attribute set to true (which means all source files end up in the same directory even if they come from different source directories).

Since the Sync task do not have the equivallent of the flatten attribute I had to invent this myself using an eachFile closure. This worked well. However when I mis-spelled the target directory and corrected this error the task didn't run again because it was up-to-date.

I think I understand why it's up-to-date, but I don't understand why a task definition change do not cause the task up-to-date status to change. Isn't it reasonable that a task definition change also changes the up-to-date flag?

This behaviour can be simulated using Gradle 4.6 (also tried on 4.5.1) using something like this:

```groovy
task syncMyFiles(type: Sync) {
  setIncludeEmptyDirs false
  into 'destdir'
  from('sourcedir') {
    include '*/copyme/*.txt'
    eachFile { it.path = 'copymes/' + it.name }
  }
}
```

The sourcedir has the following structure:

```text
sourcedir/a/copyme/file1.txt
sourcedir/b/copyme/file2.txt
```

Expected sync result is:

```text
destdir/copymes/file1.txt
destdir/copymes/file2.txt
```

**Comment by lptr** [comment]
Closed because it duplicates #1191.

**Comment by gustafg** [comment]
Thanks, I will track #1191. In the event someone else has a similar "need" in the future, I came up with a work around that is good enough for me. If I specify part of the closure using a task input property I get desired function. Ie like this:
```
task syncMyFiles(type: Sync) {
  setIncludeEmptyDirs false
  into 'destdir'
  inputs.property('copyme_dest_path', 'copymes/')
  from('sourcedir') {
    include '*/copyme/*.txt'
    eachFile { it.path = inputs.getProperties()['copyme_dest_path'] + it.name }
  }
}
```

**Comment by gustafg** [comment]
Noticed now that you already described this approach in #1191 aswell. Thanks again!
