### ISSUE TITLE
Generated gradle api jar is different on different OSes

### ISSUE THREAD

**Issue by kageiit** [gradle/gradle#4732]
The generated gradle api jar in `$GRADLE_USER_HOME/.gradle/caches/4.6/generated-gradle-jars/gradle-api-4.6.jar` is not byte indentical across OSes

### Expected Behavior
Generated gradle api jars are identical

### Current Behavior

The generated gradle api jars are not identical

### Context

This causes build cache misses for projects that depend on the gradle api like so

```
dependencies {
  implementation gradleApi()
}
```

### Steps to Reproduce (for bugs)
Run `sha1sum ~/.gradle/caches/4.6/generated-gradle-jars/gradle-api-4.6.jar` on

Mac Osx (Darwin 17.4.0 x86_64) :
`3a6dee25a18ec394fdb5682a61bb72d6d7ab2bda  /Users/kage/.gradle/caches/4.6/generated-gradle-jars/gradle-api-4.6.jar`

Linux (Linux 4.4.82 x86_64) :
`74d0048611e72ee86ffdc01c0b9f607bf1d1f388  /home/gkorlam/.gradle/caches/4.6/generated-gradle-jars/gradle-api-4.6.jar`

**Comment by kageiit** [comment]
I have verified the unzipped contents are identical. This seems to be just a mismatch of zip metadata

**Comment by blindpirate** [comment]
Well, given that their contents are identical, could you tell me why the sha1num difference matters?

**Comment by kageiit** [comment]
Because the digest of the jar is what goes into computing the cache keys for a remote cache. The jars have to be exactly identical otherwise a remote cache becomes ineffective

**Comment by blindpirate** [comment]
Nice point! Thanks for pointing out. @lptr WDYT?

**Comment by big-guy** [comment]
@kageiit could you provide copies of the jars?

When you say the contents are identical, are you saying that the checksums of each of the individual files are identical?

We don't calculate the cache key from the bytes of the jar.  We look at the individual files inside the jar, so I wouldn't expect the checksum of the jar to matter.

**Comment by kageiit** [comment]
@big-guy Github does not allow me to upload large files. I put them in the gradle slack and cc'ed @oehme

**Comment by kageiit** [comment]
@big-guy do you calculate the cache key from individual files inside the jar for all tasks? If there are custom tasks that just consume this jar as a task input file, I am not sure that would hold true and it would still invalidate such custom tasks incorrectly

**Comment by big-guy** [comment]
There are two different things.

The cache key is made up of task inputs + output properties + task implementation.  The task implementation is derived from a hash of the classloader of any actions and the classloader of the implementation class of the task.  The classloader's hash is based on the individual files in the jar and not the jar file directly.

If the `gradleApi()` jar is used as an input to a task, the way this contributes to the cache key depends on the type of input.  
- With `@InputFile`/`@InputFiles`, the cache key would be based on the bytes of the jar.  
- With `@Classpath`, the cache key would be based on the individual files in the jar (like the classloader above). This was the first specialized annotation and it would be better named `@RuntimeClasspath`.
- With `@CompileClasspath`, the cache key would be based on the public API of the classes in the jar file. This is only used for Java compilation. 

I looked at the two jars and they are identical content wise.  So if you had a task with the `gradleApi()` jar as an input, you likely want it to be used as a `@Classpath` and not a `@InputXXX` -- but it depends on what you're doing with it.

**Comment by kageiit** [comment]
yes. I was referring to the case when the jar were to be used with `@InputXXX`, that would break cache assumptions. Have you checked if the jar metadata are different (since content is the same)?

**Comment by wolfs** [comment]
The Gradle API jar should be byte by byte reproducible (same metadata). We even have a test for this: https://github.com/gradle/gradle/blob/29dcd9a47981b4ffc1b21353063be3c4fdcb38ef/subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/runtimeshaded/RuntimeShadedJarCreatorTest.groovy#L106-L164

**Comment by wolfs** [comment]
I compared the `jar`s you provided. It seems like the metadata is completely identical.
The unzipped files are identical, too.

That points to `ZipOutputStream` creating different zipped files for the same `.class` files. Did you maybe use two different Java versions to create the API jars?

For your custom task, why don't you add the Gradle API jar as a classpath by annotating the input property with `@Classpath`? This should solve your issue I guess.

**Comment by kageiit** [comment]
on mac
```
java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

on linux
```
java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by wolfs** [comment]
That means Oracle vs OpenJDK + a change in the minor version?

Does adding `@Classpath` to the inputs of your custom task solve your problem?

**Comment by kageiit** [comment]
The issue here is not about using `@Classpath`. If there is an issue with `ZipOutputStream` that is going to cause a lot of problems for any tasks that run in gradle using it and running across platforms. The custom task is hypothetical and a bit tangential to the real issue

**Comment by wolfs** [comment]
Regarding the reason why the jars are not byte by byte equivalent, I don't have a better explanation than blaming the Zip implementation in the JDK. Since the extracted files are the same and the metadata is the same this is all what is left IMO.

What I fail to see is how this would cause a lot of problems for any tasks that run in Gradle. Zips/Jars are not shared via the build cache between machines, so they are all local to one machine and the whole different OS problems do not apply.

Moreover, for all jars on classpaths (i.e. for java compilation and execution), we don't require byte-for-byte identical archives but only that the contents are the same. And the contents are the same for the gradle-api jar. We could even remove the code to generate the same metadata for the gradle-api.jar and that would not have any negative effects on build.

What kind of problems do you see when Gradle creates a gradle-api.jar which is not byte-by-byte the same but only contains exactly the same files?

**Comment by ghale** [comment]
@kageiit Does this continue to be a problem for you?  

If so, can you provide some more information about how this is affecting you?  For instance, if this is about gradle-api.jar specifically, how are you using it such that `@InputFiles` is more appropriate than `@Classpath`?  If this is about some other jar that is being generated by a task in the build, what are the scenarios where this is causing a cache miss?
