### ISSUE TITLE
buildSrc leaks dependencies into the main project's build script classpath

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#4741]
### Expected Behavior
buildSrc should not leak dependencies into the main project's build script classpath

### Current Behavior
buildSrc leaks dependencies into the main project's build script classpath

### Context
Build fails at configuration time due to Gradle loading the wrong version of Guava. Example bugs in Android Studio: https://issuetracker.google.com/70970475, https://issuetracker.google.com/71441014, https://issuetracker.google.com/71536362, https://issuetracker.google.com/72880673

### Steps to Reproduce
I've also attached a project: 
[buildSrcLeakedDependency.zip](https://github.com/gradle/gradle/files/1816614/buildSrcLeakedDependency.zip)

 1. Create a new empty Gradle project
 2. Create buildSrc/build.gradle and add a dependency on guava 18:
```
repositories {
    jcenter()
}
dependencies {
    implementation 'com.google.guava:guava:18.0'
}
```

 3. In the root project's build.gradle, add a dependency on guava 22, and call a method that exists in guava 22 but not in guava 18:
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.google.guava:guava:22.0'
    }
}
println com.google.common.collect.ImmutableSet.toImmutableSet() 
```

 4. Run ./gradlew help to trigger the call to guava.
 5. Observe that the build fails, saying that the method does not exist.
 6. Remove the dependency on guava 18 in buildSrc/build.gradle, rerun ./gradlew help, and observe that the build succeeds.

### Your Environment
Gradle version: 4.5

### Notes
This issue is mentioned at "Central plugin classpath management" (https://github.com/gradle/gradle/issues/1370), but because that proposal aims to solve multiple issues at the same time, I wanted to create this bug for users who are coping specifically with this issue.

In particular, I'd like to learn Gradle's thoughts on the way forward with this issue and workarounds for the moment.

The current workarounds seem to include:
 - Declare all plugin dependencies in buildSrc (if using buildSrc), or
 - Upgrade the versions of the problematic dependency to a common version. In the example, that would mean adding the following to buildSrc/build.gradle

```
dependencies {
    implementation 'com.google.guava:guava:22.0'
}
```

**Comment by oehme** [comment]
It is fully intended for buildSrc to expose its dependencies to all projects. What's problematic is that there is no conflict resolution, because the `buildSrc` classloader is a parent to all others. This could be changed in the long run, as part of the central classpath management you referred to. It's complicated in terms of backward compatibility though. There is no plan to tackle this until at least the middle of this year.

> Declare all plugin dependencies in buildSrc (if using buildSrc)

I think that's the best way to do it right now.

**Comment by hungvietnguyen** [comment]
Thanks a lot for your info!

**Comment by lptr** [comment]
@oehme should we close this yet?

**Comment by oehme** [comment]
I think so, since we won't change the behavior of buildSrc for backwards compatibility reasons. Instead we'll probably recommend composites in the future.

**Comment by martinbonnin** [comment]
> I think so, since we won't change the behavior of buildSrc for backwards compatibility reasons. Instead we'll probably recommend composites in the future.

How would that look ? Instead of putting the shared build logic in `buildSrc`, put it in an included build and make that included build produce a proper plugin ?
