### ISSUE TITLE
Antlr task should not add timestamps to the generated sources

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#4745]
The default template for Antlr3 java code generation adds timestamps to the generated Java sources. This is bad for using the build cache, since the `javaCompile` task depends on antlr's output and would therefore not have [stable task inputs](https://guides.gradle.org/using-build-cache/#stable_task_inputs).

### Expected Behavior
Generated Java sources do not contain a timestamp

### Current Behavior
Generated Java sources contain a timestamp.

### Steps to Reproduce (for bugs)
See the [Gradle Summit 2017 talk](https://youtu.be/gXXTJrLKoNs?t=1271) and the corresponding sample project: https://github.com/wolfs/summit-2017-examples/tree/broken/codegen.

### Your Environment
Gradle 4.6, Mac OS.

**Comment by lptr** [comment]
Since this doesn't have a large impact, and it only affects ANTLR3 anyway, I'm closing this.
