### ISSUE TITLE
Dependency locks and composite builds

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#4749]
Once dependency locking is introduced, it needs to interact well with other Gradle features.

One integration point is with composite builds.

What happens when you have binary dependencies being replaced by project dependencies through a composite and you were applying dependency locks?
* Should the build fail because the binary dependency is now a project dependency?
* Should the build fail because the project dependency has a different version than the locked binary dependency?
* If you generate a lock file from a composite build, what does it contain? Only dependencies that remained binary?
* Does it lock project dependencies that reference projects from a different part of the composite?

All these questions need to have a clear answer so that users mixing composite builds and dependency locking know what to expect and how to resolve potential build failures.

**Comment by s4nk** [comment]
Is there currently any workaround to mix composite builds with dependency locking? Even some way to ignore checking binary dependencies replaced by project dependencies

**Comment by NielsDoucet** [comment]
This incompatibility is an annoying hindrance, which might reduce adoption of either of these awesome features.

**Comment by ljacomet** [comment]
Locking ignores projects, as it assumes that in a multi project build, the control over project state is provided by the underlying source control system.

The proposal for composite integration is to apply the composite substitution rules to lock entries and to ignore lock entries that are substituted by a project.

So to answer the questions asked initially:

*  Should the build fail because the binary dependency is now a project dependency?
   * No
* Should the build fail because the project dependency has a different version than the locked binary dependency?
   * No
* If you generate a lock file from a composite build, what does it contain? Only dependencies that remained binary?
   * It contains only binary dependencies, omitting the composite projects. There is no translation back from composite to binary.
* Does it lock project dependencies that reference projects from a different part of the composite?
   * No

In addition, there is no attempt to relax constraints on versions of binary dependencies brought in by the composite.
That is, if my project locked `org:foo:1.1` and `org:bar:1.1` and then `foo` becomes a project reference which brings `org:bar:1.2` this will be considered a lock violation.

Scenarios where that answer is not sufficient might benefit from making the locking conditional, disabling it when the build is part of a composite.

**Comment by xenoterracide** [comment]
> It contains only binary dependencies, omitting the composite projects. There is no translation back from composite to binary.

this is potentially problematic for me (if I understand you correctly), as for composite modules I have created a tree structure, each, including root, being able to build by itself, but also as a tree.

root/.git
|--->modules/a/.git
|--->modules/b/.git

for me, in CI each .git stands alone, the existence of the composite is to ease development in the IDE. composite was chose over multi-module for the ability of the modules to stand alone.

**Comment by NielsDoucet** [comment]
The answer to question 3 (what does a lockfile for composite build contain?) was giving me doubts at first. But the commit message  talking about the `live lock state` made me believe this is the right path.
As long as you don't generate new lockfiles while running a composite build, the persisted lock state will remain stable. This seems like a very good solution to me.

**Comment by ljacomet** [comment]
No further work planned here, see #9907 for potential follow up
