### ISSUE TITLE
Dependency locking and source dependencies

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#4750]
Once dependency locking is introduced, it needs to interact well with other Gradle features.

One integration point is with source dependencies.

Source dependencies end up pulled in as projects in a composite build. However, there is a version resolution that kicks in before the right branch / tag / commit is picked to be included.
It would be good to have dependency locking influence that resolution and the validation of the lock be able to check that a project dependency was initially a source dependency and that the resolved version does match the locked one.

While this shares similarities with #4749 because of the use of composite builds, there is a difference in expectations, as the composite here is implicit and in a way an implementation detail.

**Comment by rgoldberg** [comment]
See: https://github.com/gradle/gradle/issues/9907#issuecomment-526078277
