### ISSUE TITLE
Need a way to run tests against obfuscated code

### ISSUE THREAD

**Issue by javaone199** [gradle/gradle#4755]
Need a way to run tests against obfuscated jar. For example,

    src/main/java
    src/test/java
    
    gradle test

It will run tests against the main source set output, not jar.

Suppose:

    the main.jar is obfuscated to main-obfuscated.jar.

Need to run tests against the obfuscated jar, not the main output classes.

**Comment by oehme** [comment]
You can create a new task of type `Test` (maybe call it `obfuscatedTest`) that tests the obfuscated classes.

**Comment by javaone199** [comment]
Sorry. I do not understand it. It would be great if you could show me an example. Basically I need to remove main output from test runtime classpath,  and add the obfuscated jar in the test runtime classpath.

**Comment by oehme** [comment]
For general Q&A, please use the [Gradle Forum](https://discuss.gradle.org/new). The community there can help you build an example.
