### ISSUE TITLE
Unable to get debug log messages in test-kit 

### ISSUE THREAD

**Issue by jansauer** [gradle/gradle#4757]
When writing gradle plugins gradle runner output is missing debug log messages when run with ` .withDebug(true)`.

### Expected Behavior
Logged debug messages should be in the `GradleRunner` output.

### Current Behavior
Logged debug messages are missing

### Steps to Reproduce (for bugs)
Run this test case:
```
  def "log a debug message"() {
    given:
    buildFile << """
            task helloWorld {
                doLast {
                    logger.debug 'Hello world!'
                }
            }
        """

    when:
    def result = GradleRunner.create()
        .withProjectDir(testProjectDir.root)
        .withArguments('helloWorld')
        .withDebug(true)
        .withPluginClasspath()
        .forwardOutput()
        .build()

    then:
    result.output.contains('Hello world!')
    result.task(":helloWorld").outcome == SUCCESS
  }
```

### Spark

Maybe [ToolingApiGradleExecutor.java#L177](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/ToolingApiGradleExecutor.java#L177) should also call [setVerboseLogging](https://github.com/gradle/gradle/blob/master/subprojects/tooling-api/src/main/java/org/gradle/tooling/internal/consumer/DefaultGradleConnector.java#L124) with the debug parameter from the runner.

### Your Environment
Gradle 4.6
com.gradle.plugin-publish 0.9.10

**Comment by big-guy** [comment]
This is working as intended.

`withDebug` refers to whether or not the build under test can be connected to with a debugger:
https://github.com/gradle/gradle/blob/7c09b6dc6a8d3b703df3fbf46d2122956da9b12f/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/GradleRunner.java#L274-L288

If you would like to see debug-level logging, you can pass `--debug` to the build under test:
```
    def result = GradleRunner.create()
        .withProjectDir(testProjectDir.root)
        .withArguments('helloWorld', '--debug')
        .withDebug(true)
        .withPluginClasspath()
        .forwardOutput()
        .build()
```
