### ISSUE TITLE
ivy-publish and maven-publish without gradle metadata fail with NPE when resolving publishableFiles

### ISSUE THREAD

**Issue by sbgertp** [gradle/gradle#4760]
The default behaviour of not including gradle metadata in ivy publishing will include a null entry in FileCollection returned by DefaultIvyPublication.getPublishableFiles, which upon resolve will result in an exception

### Expected Behavior

No error

### Current Behavior

```
* What went wrong:
Execution failed for task ':tasks'.
> Exception thrown while executing model rule: copyToTaskContainer
   > Cannot convert path to File. path='null'
```

### Steps to Reproduce (for bugs)

```
plugins {
  id("java")
  id("ivy-publish")
}

publishing {
  repositories {
    ivy {
      name = "ivy"
      url = file("ivy-repo")
    }
  }
  publications {
    ivy(IvyPublication) {
      from(components.java)
    }
  }
}

tasks.withType(PublishToIvyRepository) {
  println("$name publishable files: ${publication.publishableFiles.files}")
}
```
### Your Environment

Gradle 4.6

**Comment by jjohannes** [comment]
Thanks for reporting @sbgertp. This is a regression introduced with 4.5 already.

The problem existis with `maven-publish` as well.

Responsible code (should check if gradle metadata is null):

In `DefaultIvyPublication`
https://github.com/gradle/gradle/blob/11f21cfc298246eb08de7a13c7a864772c9e70ea/subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java#L274

In `DefaultMavenPublication`
https://github.com/gradle/gradle/blob/11f21cfc298246eb08de7a13c7a864772c9e70ea/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java#L295

**Comment by blindpirate** [comment]
Also seen in #4753

**Comment by sbgertp** [comment]
As a temporary workaround we were able to use:
```
     ivy(IvyPublication) {
       from(components.java)
+      gradleModuleDescriptorFile = project.files(".nonexistent_file")
     }
```
Empty FileCollection would not work because of these constraints:
https://github.com/gradle/gradle/blob/11f21cfc298246eb08de7a13c7a864772c9e70ea/subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publication/DefaultIvyPublication.java#L294
https://github.com/gradle/gradle/blob/11f21cfc298246eb08de7a13c7a864772c9e70ea/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java#L336
And a dummy non-existent file works because of these:
https://github.com/gradle/gradle/blob/11f21cfc298246eb08de7a13c7a864772c9e70ea/subprojects/ivy/src/main/java/org/gradle/api/publish/ivy/internal/publisher/DependencyResolverIvyPublisher.java#L47
https://github.com/gradle/gradle/blob/11f21cfc298246eb08de7a13c7a864772c9e70ea/subprojects/maven/src/main/java/org/gradle/api/publication/maven/internal/action/AbstractMavenPublishAction.java#L74
