### ISSUE TITLE
Let Gradle create the Gradle Report even in a failed test scenario

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#4788]
### Expected Behavior

If the test classes fail, `Gradle` should create anyway the `Gradle Reports` with all the report error data.

It had worked when I used to work with `JUnit` 4, but not anymore with 5. I am assuming the new plugin in Gradle would be the cause.

### Current Behavior

If the test classes fail, `Gradle` does _not_ the `Gradle Reports` with all the report error data.
Thus the `build/reports` directory is empty. 

`Gradle Reports` is only created when all the test classes pass, in other module (among others) It creates always the `build/reports/tests/test` containing:

* classes
* css
* index.html
* js
* packages

### Context

Without this `Gradle Report`, is hard find the reason of the failure and check the error stack trace.

### Steps to Reproduce (for bugs)

Just create any Test classes and it must fail.

### Your Environment

* Gradle 4.6
* JUnit 5.1.0

It works (I already did do a confirmation) for JUnit 4.12 and either Gradle 4.3.1 or 4.5.1. It about for other older projects

**Comment by blindpirate** [comment]
This is not true. We do have reports in test failure scenario and we have a lot of integration tests to guarantee this behavior. Could you please provide a reproducible sample instead of just saying `creating any Test classes which fail`?

**Comment by manueljordan** [comment]
Ok, I am going to do this tomorrow with a single module.

About `create any Test classes which fail` is when some _assertion_ fails. 
By the moment my unique way to see the error stack trace is through `Jenkins`.

**Comment by blindpirate** [comment]
> I am going to do this tomorrow with a single module.

Thanks a lot!

> when some assertion fails

We have tests for this scenario, so I very much want to see a sample.

**Comment by manueljordan** [comment]
Hello Zhang

I have created a project from the scratch with one nested module, it avalilable here: [gradle-junit5](https://github.com/manueljordan/gradle-junit5)

The unique two `@Test` methods are simple and pass, the weird now is when even both pass, the 
`build/reports/tests/test` directory is not created. But I can confirm that `build/test-results/junit-platform/TEST-junit-jupiter.xml` is created

I am totally confused because the other big project with many modules always create that path directory only when all `@Test` methods pass, but in this new project does not happen.

Seems the problem is about configuration, _but practically the settings used in both projects are the same_

If I use either:

* gradle :gradle-junit5-domain:test --parallel
* gradle :gradle-junit5-domain:junitPlatformTest --parallel
* Jenkins with either of above

I have the situation reported for this new project `gradle-junit5`.

Just in case:

```
gradle --version

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.11.3 x86_64
```

I must assume it is not a bug, but because the settings are the same in both projects and works in one (the most complex) and not the other (the simple). Thus I want assume it is a wrong or missing configuration, thus perhaps it would be nice to take in advantage to enhance the documentation, it for either `JUnit` or `Gradle`.

Thanks for your time

**Comment by blindpirate** [comment]
You're using `org.junit.platform.gradle.plugin` plugin - that is already deprecated because now Gradle supports JUnit Platform natively. You should try 

```
test {
     useJUnitPlatform()
}
```

instead of `apply plugin: 'org.junit.platform.gradle.plugin'`

Opened a PR in your repository.

**Comment by manueljordan** [comment]
Thanks for your time, I appreciate your support. I was not aware about this new change.

**Comment by manueljordan** [comment]
BTW If I remove:

```
//This location is mandatory
buildscript {

	repositories {
		mavenCentral()
	}
		
	dependencies {		
		classpath "org.junit.platform:junit-platform-gradle-plugin:1.1.0"
	}
	
}
```

It works fine, I mean seems above is not necessary any longer too.
