### ISSUE TITLE
Gradle DSL does not catch pojos in NamedDomainObjectContainer correctly

### ISSUE THREAD

**Issue by hamidelmaazouz** [gradle/gradle#4795]
When there's a pojo as property of a NamedDomainObjectContainer's content type, build fails with:
`groovy.lang.MissingPropertyException`

### Expected Behavior
A configuration example in Gradle DSL looks like:
`units {
  unit1 {
    locationHash = 'aS223SDfcs22300gopWWA'
    students {
      student1 {
        efficiencyRate = 0.76
        tutor {
          firstName = "James"
          lastName = "Bond"
          flags = [
              '03-01-2008': "Interview report",
              '03-01-2009': "First drill report"
          ]
        }
      }
      student2 {
        efficiencyRate = 0.54
      }
    }
  }
  // other units
}`

- `units` is a container of `Unit` objects (NamedDomainObjectContainer<Unit>)
- `students` is a container of `Student` objects inside `Unit`. Each student object has a `Tutor` object.
- To catch configuration of `Tutor` objects, this method is used inside `Student`:
`  void tutor(Action<Tutor> configureAction) {
    configureAction.execute(tutor)
  }`

This configuration is supposed to be mapped to the corresponding groovy structure (described above). But build fails to do so with `groovy.lang.MissingPropertyException: Could not set unknown property 'firstName' for Student ... of type Student
        at org.gradle.internal.metaobject.AbstractDynamicObject.setMissingProperty(AbstractDynamicObject.java:115)
        at org.gradle.internal.metaobject.ConfigureDelegate.setProperty(ConfigureDelegate.java:107)
`.
It is as if the build thinks properties of `Tutor` are under `Student` which is not correct.
Adding the supposedly unknown properties (`Tutor` properties) under `Student` hides the issue, but that's not what I want.

### Current Behavior
 `groovy.lang.MissingPropertyException: Could not set unknown property 'firstName' for Student ... of type Student`.
It is as if the build thinks properties of `Tutor` are under `Student` which is not correct.
Adding the supposedly unknown properties (`Tutor` properties) under `Student` hides the issue, but that's not what I want.

### Context
Trying to catch Gradle DSL configuration into Groovy pojos:
- `units` is a container of `Unit` objects (`NamedDomainObjectContainer<Unit>`)
- `students` is a container of `Student` objects inside `Unit`. Each student object has a `Tutor` object.
- To catch configuration of `Tutor` objects, this method is used inside `Student`:
`  void tutor(Action<Tutor> configureAction) {
    configureAction.execute(tutor)
  }`

### Your Environment
Gradle version 4.3.1
Groovy version 2.4.12

**Comment by blindpirate** [comment]
Instead of explaining your DSL and types, I think it's much more easy to understand if you can provide a minimum  reproducible sample.

**Comment by hamidelmaazouz** [comment]
Thanks blindpirate for your reply. Check this: https://github.com/hamidelmaazouz/gradledslbugreprod

**Comment by blindpirate** [comment]
Thanks for the sample. Actually this issue is out of Gradle scope, but I'll give you some hints:

```
  def tutor(Action<Tutor> configureAction) {
    configureAction.execute(tutor)
  }
```

is equivalent to 

```
  def tutor(Closure c){
    c.call(tutor)
  }
```

This is done automatically by [ASM](https://github.com/gradle/gradle/blob/9eddf5ea37ab4171e8c163511854133d2016f2b0/subprojects/core/src/main/java/org/gradle/api/internal/AbstractClassGenerator.java#L63). So your issue is actually "why `closure.call(tutor)` not work?".

when some property is set in a [closure](http://groovy-lang.org/closures.html), the default search order(delegation strategy) is 1. owner 2. delegate. You need to set `tutor` as your closure's delegate:

```
  def tutor(Closure c){
    c.delegate = tutor
    c.call(tutor)
  }
```

BTW, your `tutor` field isn't initialized yet.

See [Delegation strategy chapter](http://groovy-lang.org/closures.html#_delegation_strategy) for more details.

**Comment by hamidelmaazouz** [comment]
Workaround is working. Thanks a lot blindpirate for your help.
