### ISSUE TITLE
Feature request: Ability to query a configuration for 'provided' scope dependencies from Maven dependencies

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#4806]
Question originally posted at https://discuss.gradle.org/t/how-to-query-for-provided-scoped-dependencies-of-a-configuration/26131

For a given dependency

### Expected Behavior

Should be able to query for dependencies that have `provided` scope.

### Current Behavior

It seems like you are unable to get dependencies of the `provided` scope from a `resolvedConfiguration`

### Context

See https://discuss.gradle.org/t/how-to-query-for-provided-scoped-dependencies-of-a-configuration/26131

I wanted to map some provided scope dependencies into a different configuration, but was unable to 

### Steps to Reproduce (for bugs)

```
wrapper.gradleVersion = '4.6'

repositories {
  maven {
    url = 'https://repo.jenkins-ci.org/public/'
  }
}

configurations {
  myConfig
}

dependencies {
  myConfig(group: 'org.jenkins-ci.main', name: 'jenkins-core', version: '2.112')
}

tasks.create('demo') {
  doFirst {
    configurations.myConfig.resolvedConfiguration.resolvedArtifacts.findAll {
      it.moduleVersion.id.name == "javax.servlet-api"
    }.forEach {
      println(it)
    }
  }
}
```

Run `./gradlew demo` and see no output

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/u4vynffjlquz6

**Comment by blindpirate** [comment]
Thanks fore reporting, but AFAIK there's no way to achieve this. `org.jenkins-ci.main:jenkins-core`'s `provided` transitive dependency is totally unused for your build, so Gradle discards it during dependency resolution phase.
