### ISSUE TITLE
How can I run particular test for a test suite?

### ISSUE THREAD

**Issue by tshasc** [gradle/gradle#4816]
I want to run particular tests for a test suite. How can I define the rule in gradle file?
 I found below code which can count/create index for each test. but how can I make sure it will skip the test meet the criteria
In another word, how can I just run test as “AAATest” but not run test as “BBBTest”
any solutions?

def numTests = 0
test {
beforeTest { descriptor ->
System.out.println(“Running test " + numTests + " : " + descriptor)
numTests++
}
}
test << {
System.out.println(”\nnumTests executed: " + numTests);
}

**Comment by blindpirate** [comment]
Sorry I don't quite understand what you mean. Are you saying you only want `AAATest` to be run? You can use [test filtering](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestFilter.html) or [--tests](https://docs.gradle.org/current/userguide/java_plugin.html#test_filtering)

**Comment by tshasc** [comment]
1) I want to do this by gradle instead of command line

2) I want to choose which test to run in runtime.
   for example, if index of current test is 5 or 10 or 15... I will run current test,otherwise do nothing

If that possible to implement this by updating build.gradle, thanks?

**Comment by blindpirate** [comment]
Sounds like a sampling of test. AFAIK there's no way to control test execution like this. What you're trying to use is a [`TestListener`](https://github.com/gradle/gradle/blob/6e4745113c85697e0ac315540899e4703ca92e3f/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestListener.java#L28), which can only LISTEN but can't MODIFY a test. The test execution is controlled by test frameworks (e.g. JUnit/TestNG), Gradle can only control which classes are included in test execution.

You can traverse the test class directory and only include some of them by [`include()`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/Test.html#include-java.lang.Iterable-). Note this is class-level, not testcase-level.

Or you can write some custom [`Runner`](https://github.com/junit-team/junit4/wiki/test-runners).

**Comment by tshasc** [comment]
What I want to do if divide tests into different groups.
Yes, my final solution is just use include /exclude as below to generate 3 test groups
if(index==1) { include 'ABC/a*/**' }
else if (index==2) { include 'ABC/b*/**' }
else { exclude 'ABC/a*/**' exlucde 'ABC/b*/**' }

**Comment by blindpirate** [comment]
`include/exclude` is a configuration phrase action and can't be done at test execution runtime. What's more, it's kind of random - the test descriptor/event order is not guaranteed so your intended group might be unstable. What about [test grouping](https://docs.gradle.org/current/userguide/java_plugin.html#test_grouping)? It's more stable than what you intended to do.
