### ISSUE TITLE
How to make a ssl connection to database in gradle? 

### ISSUE THREAD

**Issue by SpamhaterAlex** [gradle/gradle#4819]
Hi community, 

I have a truststore-file, which is need to make a connection to my database, which is in cloud. 
For this, I need to set up my system propertys: 

`-Djavax.net.ssl.trustStore=pathToMyTrustStore -Djavax.net.ssl.trustStorePassword=Password`

In my build.gradle I have a "jdbc" connection to my database. But it fails, because, I have to set up this System propertys in gradle. 

Does anybody have a hint for me, how to set this in gradle? Before the project will be build? (my application) 

Thanks a lot

**Comment by oehme** [comment]
Please use the Gradle forum for Q&A. 

Make sure to provide an example project there, otherwise people won't know what you are trying to do.
