### ISSUE TITLE
Project dependency with configuration incorrectly published in pom

### ISSUE THREAD

**Issue by emmanuelguerin** [gradle/gradle#4827]
### Context
I'm attempting to publish a jar with maven-publish that contains a project dependency to another project, with an alternate configuration.
The resulting pom.xml doesn't contain the classifier, even though it is specified in the artifacts.

### Steps to Reproduce
See repo: https://github.com/emmanuelguerin/gradle-conf-issue
Starting from the following sample in the documentation:
https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:project_jar_dependencies
I'm adding the maven-publish plugin and a classifier to the spiJar task:
```gradle
subprojects {
    apply plugin: 'maven-publish'
    apply plugin: 'java'
    group = 'org.gradle.sample'
    version = '1.0'
    publishing {
        publications {
            maven(MavenPublication) {
                from components.java
            }
        }
    }
}

project(':api') {
    configurations {
        spi
    }
    dependencies {
        compile project(':shared')
    }
    task spiJar(type: Jar) {
        baseName = 'api-spi'
        from sourceSets.main.output
        include('org/gradle/sample/api/**')
        classifier = 'spi'
    }
    artifacts {
        spi spiJar
    }

    publishing.publications.maven.artifact(spiJar)
}

project(':services:personService') {

    dependencies {
        compile project(':shared')
        compile project(path: ':api', configuration: 'spi')
        testCompile "junit:junit:4.12", project(':api')
    }
}
```
Then call:
```
gradle :services:personService:generatePomFileForMavenPublication
```

### Expected Behavior
The content of `services/personService/build/publications/maven/pom-default.xml` should be:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.gradle.sample</groupId>
  <artifactId>personService</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>org.gradle.sample</groupId>
      <artifactId>shared</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.gradle.sample</groupId>
      <artifactId>api</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
      <classifier>spi</classifier>
    </dependency>
  </dependencies>
</project>
```

### Current Behavior
The current implementation doesn't include the `classifier` for the `org.gradle.sample:api` dependency.

### Your Environment
gradle 4.6

### Comments
Looking at the code, it seems this feature is not implemented at the moment. When a project dependency is added to the MavenPublication, its configuration is completely ignored.
Only a `ModuleVersionIdentifier` is returned by the `ProjectDependencyPublicationResolver`, when an `ArtifactIdentifier` would probably be required to contain the necessary information.

**Comment by blindpirate** [comment]
Thanks for reporting. Seems like this is not implemented yet.

**Comment by Marquis-August-Pagnin** [comment]
Is there a workaround?  Can you give ETA?  If you give me some pointers, I can give fixing this bug a try.

**Comment by emmanuelguerin** [comment]
I submitted this bug a long time ago. Given what has been done in dependency management in the interval. I think the usecase should be updated to make sense in the new paradigm.

**Comment by Marquis-August-Pagnin** [comment]
@emmanuelguerin What needs to be updated in the usecase itself?  I am not getting the expected behavior you mentioned using Gradle 6.1 and I strongly suspect the issue I am facing is due to this issue

The only part of your post I think that may need updating is the 'Comments' section where you provide your analysis.
