### ISSUE TITLE
Gradle 4.6 with useJUnitPlatform() does not execute @Test methods declared in static nested classes

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#4831]
### Expected Behavior

Working with `Gradle` version **4.6** with `useJUnitPlatform()` execute the test classes and expect all the `@Test` methods declared through a simple class and _static nested class_ are executed (it does not matters if pass or fail)

### Current Behavior

Possible bug or missing configuration:

Working with `Gradle` version **4.6** with `useJUnitPlatform()` the `@Test` methods declared through  _static nested class_ are ignored. Only are executed the `@Test` methods declared in a simple class.

### Context

I am not able to know if a `@Test` pass or fail from a _static nested class_, it because through `useJUnitPlatform()` they are _now_ ignored.

### Steps to Reproduce (for bugs)

All available in [gradle-junit5](https://github.com/manueljordan/gradle-junit5), be sure to read the `readme` file for detailed information.

### Your Environment

```
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.11.3 x86_64
```

And `JUnit` version `5.1.0`

**Comment by blindpirate** [comment]
AFAIK this has already been resolved in #4492 , would you mind trying with latest snapshot version http://services.gradle.org/distributions-snapshots/ ?
