### ISSUE TITLE
Generic JavaDoc task options are not considered task inputs

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4834]
I had

```groovy
    tasks.withType(Javadoc) {
        options {
            locale 'en'
            encoding 'UTF-8'
            links 'https://docs.oracle.com/javase/8/docs/api/'
            delegate.use()
            version()
            author()
            splitIndex()
        }
    }
```
And changed it to (added the `html5` option)
```groovy
    tasks.withType(Javadoc) {
        options {
            locale 'en'
            encoding 'UTF-8'
            links 'https://docs.oracle.com/javase/8/docs/api/'
            delegate.use()
            version()
            author()
            splitIndex()
            addBooleanOption 'html5', true
        }
    }
```
This did **not** trigger a rebuild of the docs.
As in this case the value is static it is not that problematic, but if the value is dynamic and not added as property task input manually, it would not work properly. I'd have expected this to work properly.

**Comment by blindpirate** [comment]
Thanks for reporting, I believe this is because `-html5` is a Java 9 new option and isn't included in snapshot calculation.

**Comment by blindpirate** [comment]
Yes. This should be definitely improved. Opened #4841 .

**Comment by ghale** [comment]
Closing this as it will be handled with #4841.
