### ISSUE TITLE
Cannot set the value of read-only property 'classpath' 

### ISSUE THREAD

**Issue by pedegie** [gradle/gradle#4835]
Hello when I trying add this code to my build.gradle:
```
bootRun {
    dependsOn pathingJar
    doFirst {
        classpath = files("$buildDir/classes/main", "$buildDir/resources/main", pathingJar.archivePath)
    }
}
```
I got this error: 
Cannot set the value of read-only property 'classpath' for task ':modules:view:bootRun' of type org.springframework.boot.gradle.tasks.run.BootRun.

Does someone know cause of it?  I'm using gradle-4.4.1 version

**Comment by oehme** [comment]
This question is better suited for the [Spring Boot issue tracker](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin)
