### ISSUE TITLE
Order of group options in Javadoc task is not considered for up-to-date checks

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4843]
### Expected Behavior
If you change the order of `group` options for a `Javadoc` type task, the task should be rerun as the result will be different.

### Current Behavior
The task is considered up-to-date or taken from the build cache.

### Your Environment
Gradle 4.6

**Comment by blindpirate** [comment]
Thanks for raising this, can you give an example that different order matters?

**Comment by Vampire** [comment]
Any example.
The order of the group arguments defines the order in the produced page.
If you have
```groovy
javadoc.options.group 'Public API', '*'
javadoc.options.group 'Internal Helpers', 'com.example.internal.*'
```
and look at `overview-summary.html`, you get first `Public API`, then `Internal Helpers`.
If you swap around to 
```groovy
javadoc.options.group 'Internal Helpers', 'com.example.internal.*'
javadoc.options.group 'Public API', '*'
```
and look at `overview-summary.html`, you get first `Internal Helpers`, then `Public API`.

**Comment by blindpirate** [comment]
Okay, that makes sense.

**Comment by Vampire** [comment]
In 5.0 it still reproduces, in 6.0 it is fixed, so some 5.x version fixed this already.
