### ISSUE TITLE
Running java main class from WorkerExecutor to create daemon process

### ISSUE THREAD

**Issue by shshankar1** [gradle/gradle#4844]
I am trying to run a java main from WorkerExecutor to create daemon process but gradle build is failing with reason:
Execution failed for task ':client-stp-grid-publisher-acceptance:startClientStpGridPublisherAsync'.
> A failure occurred while executing startClientStpGridPublisher
   > Could not serialize parameters
      > org.gradle.api.internal.project.DefaultProject_Decorated

build.gradle:
```
import org.gradle.workers.WorkerExecutor
import javax.inject.Inject
import org.gradle.workers.WorkerConfiguration
import org.gradle.workers.IsolationMode

class startClientStpGridPublisher implements Runnable{
    final Project project

    @Inject
    public startClientStpGridPublisher(Project project){
        this.project = project
    }
    @Override
    public void run(){
        println("hello, startClientStpGridPublisher.run")
        project.javaexec {
            classpath = sourceSets.main.runtimeClasspath
            main = "com.markets.efx.client.stp.acceptance.StartClientStpGridPublisherCore"
        }
    }
}

class RunAsyncTask extends DefaultTask{
    final WorkerExecutor workerExecutor

    @Inject
    public RunAsyncTask(WorkerExecutor workerExecutor) {
        this.workerExecutor = workerExecutor
    }

    @TaskAction
    public run(){
        workerExecutor.submit(startClientStpGridPublisher.class){WorkerConfiguration config ->
            println("hello, workerExecutor.submit")
            config.isolationMode = IsolationMode.PROCESS
            config.forkOptions { JavaForkOptions options ->
                options.maxHeapSize = "512m"
                options.systemProperty "org.gradle.sample.showFileSize", "true"
            }
            config.params project
        }
    }
}

task startClientStpGridPublisherAsync(type: RunAsyncTask)

task preIntegrationTest(dependsOn: ['startClientStpGridPublisherAsync','deleteChronicleQueue', 'createChronicleQueue'])

```
Can you please help me figure out the reason? I understand that it is not correct forum to ask questions but I am unable to get answers from other forums e.g. https://stackoverflow.com/questions/49485845/running-gradle-task-as-daemon-thread-java-9-with-gradle-4-4-1

**Comment by blindpirate** [comment]
`config.params project` will send param to worker process via serialization/deserialization. Obviously, `Project` implementation can't be serialized. You need to use serializable parameters.

**Comment by shshankar1** [comment]
@blindpirate any suggestion on how can I achieve requirement to run java class main as deamon process?

**Comment by ghale** [comment]
One way to implement this would be to pass the arguments to `main()` in the configuration, and then in your `Runnable`, simply execute `com.markets.efx.client.stp.acceptance.StartClientStpGridPublisherCore.main()` with those arguments.  You'll need to worry about any sort of static state that gets carried over between invocations, but otherwise, that's a workable approach.

Another approach would be to figure out what `main()` is doing and reimplement that in your `Runnable` class.
