### ISSUE TITLE
Eclipse4.4.2 + gradle4.6+springboot1.5.6.RELEASE+mybatisGenerator1.3.5

### ISSUE THREAD

**Issue by shaeEdison** [gradle/gradle#4858]
When using the "mybatisGenerate" command, the prompt "configfile src/main/resources/generatorConfig.xml does not exist"

**Comment by blindpirate** [comment]
Thanks for reporting, but this seems a configuration issue. I think this is out of Gradle scope, please attach a reproducible sample (or at least stacktrace/build.gradle) rather than two-line description. Feel free to reopen it.

**Comment by shaeEdison** [comment]
`task mybatisGenerate << {
    def properties = getDbProperties()
    ant.properties['targetProject'] = projectDir.path
    ant.properties['src_main_java'] = sourceSets.main.java.srcDirs[0].path
    ant.properties['src_main_resources'] = sourceSets.main.resources.srcDirs[0].path
    ant.properties['modelPackage'] = properties.getProperty("modelPackage")
    ant.properties['mapperPackage'] = properties.getProperty("mapperPackage")
    ant.properties['sqlMapperPackage'] = properties.getProperty("sqlMapperPackage")
    ant.taskdef(
            name: 'mbgenerator',
            classname: 'org.mybatis.generator.ant.GeneratorAntTask',
            classpath: configurations.mybatisGenerator.asPath
    )
    ant.mbgenerator(overwrite: true,
            configfile: 'src/main/resources/generatorConfig.xml', verbose: true) {
        propertyset {
            propertyref(name: 'targetProject')
            propertyref(name: 'src_main_java')
            propertyref(name: 'src_main_resources')
            propertyref(name: 'modelPackage')
            propertyref(name: 'mapperPackage')
            propertyref(name: 'sqlMapperPackage')
        }
    }
}`
