### ISSUE TITLE
gradle fails due to dependency on Unsafe::defineClass which is removed in JDK 11

### ISSUE THREAD

**Issue by kevinrushforth** [gradle/gradle#4860]
gradle fails to run on the latest development build of Java due to a dependency on sun.misc.Unsafe::defineClass, which was recently removed from the mainline jdk code base. See [JDK-8193033](https://bugs.openjdk.java.net/browse/JDK-8193033). This fix will show up in JDK 11-ea+6.

### Expected Behavior
gradle should work with the latest JDK.

### Current Behavior
gradle fails to run with the latest JDK

### Context
We are trying to build / test JavaFX with the latest JDK bits.

### Steps to Reproduce (for bugs)

1. Download an OpenJDK 11 EA build (openjdk-11-ea+6 or later) from: http://jdk.java.net/11/

Note that as of the time of this bug report, jdk-11+5 is the latest version available. I expect build 6 to be posted shortly. Alternatively, you can build OpenJDK from source by cloning: http://hg.openjdk.java.net/jdk/jdk but it is probably easier to just wait a day or two to download jdk-11+6 from the download site.

2. Set JAVA_HOME and PATH to point to the jdk-11 build in step 1 and run the following from an empty directory:

$ gradle --info --stacktrace tasks
FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().
...
Caused by: java.lang.NoSuchMethodError: sun.misc.Unsafe.defineClass(Ljava/lang/String;[BIILjava/lang/ClassLoader;Ljava/security/ProtectionDomain;)Ljava/lang/Class;
	at org.gradle.internal.classloader.ClassLoaderUtils.define(ClassLoaderUtils.java:104)

I have attached the complete log here:
[err.log](https://github.com/gradle/gradle/files/1852869/err.log)

### Your Environment
Ubuntu 16.04, but this is not platform-specific.

**Comment by kevinrushforth** [comment]
I was able to reproduce this bug with the gradle-4.7 nightly from today, and also with earlier versions of gradle (e.g., 4.3 and 4.6). Prior to 4.7 nightly, I had to modify my local build of the JDK to change the version string back to "10" so as to avoid issue #4515 ...

**Comment by blindpirate** [comment]
Thanks @kevinrushforth for reporting this. We're kind of aware of this issue - lots of projects are affected by this removal actually.. :-)

**Comment by AlanBateman** [comment]
sun.misc.Unsafe.defineClass has been terminally deprecated (forRemoval=true) for a few releases so removing it should not be a surprise. Lots of effort in 2017 to contact projects using it, I don't know if the Gradle usage was identified. From an initial glance, the Gradle usage seems like  candidate to move to MethodHandles.Lookup defineClass (Lookup::defineClass is the only supported API for injecting classes into an existing loader/package).

**Comment by kevinrushforth** [comment]
I note that jdk-11+6 is now on the http://jdk.java.net/11/ download site.

**Comment by oehme** [comment]
The immediate failure is fixed, but there is some follow-up work to do: https://github.com/gradle/gradle/issues/5079
