### ISSUE TITLE
NotSerializableException: DefaultProjectLayout$(FixedDirectory|FixedFile) when attempting to use @Input for path-type inputs

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#4861]
Trying to use a `DirectoryProperty` or `FileProperty` with `@Input` for path-type (not content) task inputs.

### Expected Behavior

Similar to what happens with `@Input` with a `File`.

>  When used on a File object that refers to a file or directory, the up-to-date check is only dependent on the path and not the contents of the file or directory. To make it depend on the contents, use InputFile or InputDirectory respectively.

### Current Behavior

Serialization exceptions on task inputs

>java.io.NotSerializableException: org.gradle.api.internal.file.DefaultProjectLayout$FixedFile

(I think) the workaround is to make the desired property `@Internal` and map it to a different internal output like:

```groovy
@Internal
final DirectoryProperty myDir = ...

@Input
final Provider<File> myDirAsFileProvider = myDir.asFile
```

### Context

Desire to use the strongly modeled types to represent "paths" in a similar way to how `@Input` works.

### Steps to Reproduce (for bugs)

```groovy
import static java.util.Objects.requireNonNull
import javax.inject.Inject

class DirTask extends DefaultTask {
  @Input
  final DirectoryProperty exampleInputDir
  @Input
  final RegularFileProperty exampleInputFile

  @OutputDirectory
  final DirectoryProperty exampleOutputDir

  @Inject
  DirTask(ProjectLayout projectLayout) {
    this.exampleInputDir = projectLayout.directoryProperty()
    this.exampleInputFile = projectLayout.fileProperty()
    this.exampleOutputDir = projectLayout.directoryProperty()
  }

  @TaskAction
  void doThing() {}
}
tasks.create('myTask', DirTask) {
  exampleInputDir.set(layout.projectDirectory.dir('myDir'))
  exampleOutputDir.set(layout.buildDirectory.dir('outDir'))
  exampleInputFile.set(layout.projectDirectory.file('build.gradle'))
}

tasks.wrapper.gradleVersion = '4.6'
```

`./gradlew myTask`

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/46zmqosqhxt5a

**Comment by blindpirate** [comment]
Thanks for reporting. It seems like a missing `implements Serializable` there.

**Comment by wolfs** [comment]
@mkobit Could you describe your use-case for adding the file/directory path as an input to the task as opposed to the contents? For cacheable tasks, we actually [print a warning](https://github.com/gradle/gradle/blob/f00f44afd41ff4452e488c694e32c0f0cbd67eac/subprojects/core/src/test/groovy/org/gradle/api/internal/tasks/properties/PropertyValidationAccessTest.groovy#L51-L60) when this happens.

**Comment by mkobit** [comment]
@wolfs good point about the the cacheable tasks.

The use case here is, I don't think, not a general one. I have a personal project where I use Gradle as more of a "personal environment/workflow management" tool rather than a build tool. It is basically a place for me to experiment with some Gradle features and get a feel for some of the new things coming down the pipeline.

What I was trying to accomplish was "take an input file or directory, and symlink it to the destination" while seeing how up-to-date checking and modeling with the `Property` and lazy configuration types. So, the output would be a symlink file/directory somewhere and the input would be a path to some file or directory.

My expectation coming in was that it would be treated in a similar way as:

```groovy
@Input
File dirOrFilePath
```

which I believe just cares about the path of the input.

I was seeing if I could still strongly model the input as either a `Directory` or `RegularFile` (could actually probably use `FileSystemLocation`) instead of a `Provider<File>` (or something like that) and how up-to-date checking would work when I ran into this.

Looking through this a little more and thinking through it, my expectations may be wrong and this may be invalid. I do notice that the `:buildSrc:validateTaskProperties` does not show any warnings or errors, so maybe that is the only improvement here?

**Comment by wolfs** [comment]
Well, if the generated symlink is the output, then Gradle would actually snapshot the contents of it. So everytime something in the symlinked file changes, Gradle would re-execute the task.

I think that the built-in up-to-date checking won't help much for the task under question. The task would be up-to-date when the input path would be a symlink pointing to the right target. The output is the actual symlink.

So you would need to add the path of the symlink you want to create and the path which will be the target of the symlink as an input (currently as `String`s) and for the outputs you need to declare `outputs.upToDateWhen { }`, adding the condition that the file at the path of the symlink is a symlink pointing to the target.

**Comment by mkobit** [comment]
Awesome, that makes sense @wolfs . I think that everything here works as should be expected, so unless you think there is any follow up I think this can be closed.
