### ISSUE TITLE
Feature request: Consider adding flatMap to org.gradle.api.provider.Provider

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#4875]
Combining multiple `Provider` values together is cumbersome. It also isn't clear if this loses the provenance of the `Provider` for task dependency inference to work correctly.

### Expected Behavior

Would like to be able to arbitrarily combine `Provider` types together while also getting task dependency inference.

Proposal is to add something like `flatMap(Transformer<? extends S,Provider<T>> transformer)` so that the following would work:

```kotlin
val prov1: Provider<String> = target.provider { "hello" }
val prov2: Provider<String> = target.provider { "world" }

val result: Provider<String> = prov1.flatMap { h ->
  prov2.map { w ->
    "$h $w"
  }
}
```

### Current Behavior

Need to either call `get()` on one of the providers inside of a `map` function or flatten out `provider`s with `map` calls. 

Here is an example:

```kotlin
val prov1: Provider<String> = target.provider { "hello" }
val prov2: Provider<String> = target.provider { "world" }

val example1: Provider<String> = prov1.map { h ->
  // calling .get() on other provider
  "$h ${prov2.get()}"
}

val example2: Provider<String> = prov1.map { h ->
  prov2.map {w ->
    "$h $w"
  }
}.map {
  // have Provider<Provider<String>> here
  it.get()
}
```
### Context

Writing a plugin attempting to use the `Property`/`Provider` lazy APIs and wanted to map multiple extension properties to a single `Provider<>`. The hope was also that the task dependencies are also inferred  through the use of `Provider`/`Property` chaining.

### Your Environment

Gradle 4.6

**Comment by mkobit** [comment]
IMO I think this is more important with the direction of the lazy configuration APIs (I don't know if that is the right way to describe the feature). Having a `TaskProvider<>` that has an `@Output[File|Directory]` property of type `[RegularFile|Directory]Proprety` and trying to wire that into another task is not straightforward and is IMO a bit uglier. Do I call:
```kotlin
newTask.configure { inputFile.set(myTask.get().outputFile) }
```
or 
```kotlin
newTask.configure { inputFile.set(myTask.map{ it.outputFile }.get()) }
````
I think a `flatMap` like 

```kotlin
newTask.configure { inputFile.set(myTask.flatMap { it.outputFile  }) }
```

is more streamlined and better fits expectations of treating the `Provider`/`Property` types as more "functional".

If/when Kotlin adds support for multiple setters for a property it might look like

```kotlin
newTask.configure { 
  inputFile = myTask.flatMap { it.outputFile  }
}
```

Which I think looks pretty slick and displays the intent and dependencies well!

**Comment by JLLeitschuh** [comment]
@mkobit  Very much in agreement with you. The confusion between which pattern should be used is one of the problems that I faced.

**Comment by adammurdoch** [comment]
PR https://github.com/gradle/gradle/pull/6775 adds a `flatMap()` method. The implementation takes care of tracking the producer task, to automatically add task dependencies to the consuming tasks.
