### ISSUE TITLE
--dry-run does not show tasks from composite builds

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4894]
### Expected Behavior
If you execute a build with `--dry-run` it should show all tasks to be executed.

### Current Behavior
Only own tasks are shown, not the tasks from included builds.

### Your Environment
Gradle 4.6

**Comment by Vampire** [comment]
It seems this got worse.
With 6.5.1 now the included build actually got executed.

**Comment by jjohannes** [comment]
Closing this as duplicate of https://github.com/gradle/gradle/issues/2517.

Pleas subsribe to that issue @Vampire.
