### ISSUE TITLE
Included build failure does not break the build

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4895]
I just changed a line in an included build (composite build feature) and did `./gradlew run` in the main build with Gradle 4.6 both.
I then wondered why the change did not have the intended effect.
When I scrolled up I found that the `compileJava` task of the included project failed with error which did not disturb the main build from continuing.

**Comment by GFriedrich** [comment]
Just stumbled into the same problem.
I guess this is a known limitation right now for composite builds, but I'm wondering why there is no notice on the documentation page about this.
Is there any known workaround?

**Comment by Vampire** [comment]
@blindpirate why is this labeled feature? Doesn't this imply the current behavior is expected and wanted and I request a change of that? 
I cannot believe it is expected and wanted that a failed included build is silently ignored.

**Comment by GFriedrich** [comment]
Also this issue is missing the "in:composite-builds" label.

**Comment by adammurdoch** [comment]
It's definitely not great to have failures go missing, and not the intended behaviour at all. We'll get this fixed soon.

**Comment by adammurdoch** [comment]
This is fixed now. The fix will be in 4.9.
