### ISSUE TITLE
Dependency artifact download logging does not get grouped

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#4898]
The "Download ..." output rendered by dependency resolution does not get grouped with the task it is associated with.  This output comes from the underlying Apache HttpClient classes and does not travel through our output rendering chain that does the task grouping.  We should see if there is a way we can capture this output and run it through our grouping console chain.

For instance, the following "Download" messages are associated with the `linkTest` task, but are rendered before the task header:

```
> Task :compileTestCpp
Download https://repo.gradle.org/gradle/libs-snapshots-local/org/gradle/cpp-samples/googletest_debug_linux_x86-64_4.5/1.9.0-SNAPSHOT/maven-metadata.xml
Download https://repo.gradle.org/gradle/libs-snapshots-local/org/gradle/cpp-samples/googletest_debug_linux_x86-64_4.5/1.9.0-SNAPSHOT/googletest_debug_linux_x86-64_4.5-1.9.0-SNAPSHOT.module
Download https://repo.gradle.org/gradle/libs-snapshots-local/org/gradle/cpp-samples/googletest_debug_linux_x86-64_4.5/1.9.0-SNAPSHOT/googletest_debug_linux_x86-64_4.5-1.9.0-SNAPSHOT.so
> Task :linkTest
```

### Expected Behavior
The "Download" output should be grouped with the task that is associated with the artifact download.

### Current Behavior
This logging does not pass through our grouping output rendering chain, so task grouping is not applied to these messages.

### Context
This is not a new problem, and has been visible with the rich console since it was introduced.  However the problem is a little more visible now that the plain console also uses task grouping.

**Comment by oehme** [comment]
These verbose messages were removed in 4.10. They were abusing the loggingHeader mechanism.
