### ISSUE TITLE
Global "pluginManagement" configuration for internal Artifactory proxy repo

### ISSUE THREAD

**Issue by apottere** [gradle/gradle#4920]
At our company, we use an internal Artifactory instance for proxying dependencies from public repositories on developer laptops and CI builds.  This increases resolution speed and insulates us from potential downtime in the upstream repositories.  It also allows us to seamlessly resolve proprietary dependencies alongside public dependencies.

With dependencies and "old-style" gradle plugins, we've used `~/.gradle/init.gradle` to add our internal repository and enforce that all requests go through it (on developer laptops and CI servers alike):
```
allprojects {
    buildscript {
        repositories {
            // Add/Remove plugin repos here...
        }
    }
    repositories {
        // Add/Remove dependency repos here...
    }
}
```

With the new `plugins {}` syntax, it appears that the only way to manage plugin repositories is with a `pluginManagement` section in `settings.gradle`, which is a project file.  With `~/.init.gradle`, we can control the repositories for all projects (like maven's `settings.xml`) without including repository information in every gradle project we have, but there doesn't seem to be a way to configure `pluginManagement` globally.

Is that a correct assessment, and can `pluginManagement` only be configured in individual projects? If so:
1. Is there a workaround that would let us change the plugin repositories in a global build script?
2. Can support for a global `pluginManagement` block (in `~/.gradle`) be added?

**Comment by oehme** [comment]
You can use `settingsEvaluated {}` from your init script to configure the plugin management section.

**Comment by apottere** [comment]
Awesome, thanks!  It would probably be a good idea to document this alongside the plugins documentation, I exhausted about 40-50 links before I resorted to asking here.

**Comment by oehme** [comment]
Good idea, would you mind sending a PR with the change in documentation that would have helped you?

**Comment by apottere** [comment]
https://github.com/gradle/gradle/pull/4999
