### ISSUE TITLE
Changing test framework-specific properties should mark test task out-of-date

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#4924]
### Expected Behavior

Changing any test framework-specific property, e.g. `includeTags` for JUnit Platform, should mark  `Test` tasks out-of-date.

### Current Behavior

Currently, only framework-agnostic properties are taken into account when checking whether a `Test` task is up-to-date.

### Context

This behavior is very surprising because all other options, such as `filter`, mark  `Test` tasks out-of-date.

https://github.com/gradle/gradle/blob/c2067eaa129af4c9c29ad08da39d1c853eec4c59/subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/Test.java#L833-L843

### Steps to Reproduce (for bugs)

For example, let's assume we have the following configuration

```gradle
test {
	useJUnitPlatform {
		includeTags "foo"
	}
	filter {
		includeTestsMatching "com.example.project.*"
	}
	testLogging {
		events "passed", "skipped", "failed"
	}
}
```

Running the test task yields the following output:

```
$ ./gradlew --console plain test 
:compileJava
:processResources NO-SOURCE
:classes
:compileTestJava
:processTestResources NO-SOURCE
:testClasses
:test

com.example.project.CalculatorTests > foo() PASSED

BUILD SUCCESSFUL in 1s
3 actionable tasks: 3 executed
```

Replacing `includeTags` with `excludeTags` in the build script and running the test again should run the `Test` task again because its config has fundamentally changed. However, it is considered up-to-date.

```
./gradlew --console plain test
:compileJava UP-TO-DATE
:processResources NO-SOURCE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test UP-TO-DATE

BUILD SUCCESSFUL in 0s
3 actionable tasks: 3 up-to-date
```

**Comment by wolfs** [comment]
Looks like the [getters in `JUnitPlatformOptions`](https://github.com/gradle/gradle/blob/38ac47d8bb5d7f3aeb10290ee47035e34e9cc038/subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/junitplatform/JUnitPlatformOptions.java#L82-L114) are missing the corresponding input annotations.

**Comment by marcphilipp** [comment]
Yep, same for `JUnitOptions` and `TestNGOptions`.
