### ISSUE TITLE
Unix start script defines to run with Bourne Shell but is not compatible

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4926]
If you try to run the unix start script from the `application` plugin (and thus also `gradlew` I guess) with a real Bourne Shell (`sh`) and not one that is symlinked to a `bash` or `dash`, which is what the script declares it is compatible with in its Shebang line, it fails with a syntax error.

The last thing executed successfully is the false darwin-check in line 108 and then it fails on line 113 because of a syntax error in line 141 which is the line containing `i=$((i+1))` and the error literally is `syntax error at line 141: 'i=$' unexpected`.

The system at our customer where this happened was a Sun Solaris SPARC 2.10 system where obviously an original Bourne Shell is installed and not a symlink to one of the more mighty shells that know the arithmetic syntax.

You should either make the start script Bourne Shell compatible as declared, or change the Shebang to require some other shell like `bash`, while the former would be preferable I think.

**Comment by lacasseio** [comment]
@Vampire We did some change around this story in 6.0. Could you confirm if this issue is still valid?

**Comment by Vampire** [comment]
I don't remember how I tested it here, but comparing the files I changed in my PR for this issue with the current master state seems to imply the issues are fixed now.
