### ISSUE TITLE
dependent projects are not working in 4.4 and 4.6

### ISSUE THREAD

**Issue by jsiddharth** [gradle/gradle#4927]
I have 2 gradle projects A and B

In project A I have

    dependencies {
        ext {
            support_library_version = '26.1.0'
        }
        implementation "com.payu.india:payu-sdk:4.4.1"
        implementation "com.payu.magicretry:magicretry:1.0.4"
        implementation "com.payu.custombrowser:payu-custom-browser:6.1.1"
        implementation "com.android.support:appcompat-v7:${support_library_version}"
        implementation "com.android.support:support-v4:${support_library_version}"
    }

In project B I have

    implementation project(':A')

For some reason project B reports unable to find symbol for all `com.payu.*` imports.

After I upgraded I had to copy all the needed `implementation` from project A to project B. What am I missing ?

**Comment by oehme** [comment]
As the name says, `implementation` dependencies are implementation details and are not available for downstream projects to compile against. If a dependency should be part of your api, you should use the `api` configuration
