### ISSUE TITLE
Clarify how to make annotation processor incremental

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#4930]
1. https://docs.gradle.org/4.7-rc-1/userguide/java_plugin.html#sec:incremental_annotation_processing does not describe whether `incremental.annotation.processors` file contains simple class name of the processor or fully qualified class name
2. When I run `gradle classes` my annotation processor does not work incrementally; logs with `--info` don't give me any idea why Gradle has decided not to treat my processor as incremental - is the syntax of `incremental.annotation.processors` invalid, is my processor not found in that file? When I run with `--debug` I am overwhelmed by logs; I cannot find the class name of my processor there. I also cannot find words 'incremental' and 'annotation.processors', so I suppose Gradle does not have any useful logging for this new feature.

**Comment by oehme** [comment]
1. It's the qualified name. I'll change the sample to make that clearer.
2. The info log definitely says which processors aren't incremental. Did you enable incremental compile?

**Comment by oehme** [comment]
Awesome! So there's only some documentation to clarify.

**Comment by oehme** [comment]
Documentation update is in https://github.com/gradle/gradle/pull/4959

**Comment by pkubowicz** [comment]
Thank you.
