### ISSUE TITLE
Provide a Gradle command to display task dependency tree/hierarchy

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#4932]
As a user, I want to know all the tasks that are available, but instead of a flat list, I want to know how they depend on one another. Even better: tell me why.

### Expected Behavior
I propose perhaps a flag for the `gradle tasks` command like `--tree` or `--dependencies` that prints the report suggested above. I strongly feel that this ought to be baked in.

### Current Behavior
There are a couple plugins that do this:
* https://github.com/jakeouellette/inspector/
* https://github.com/dorongold/gradle-task-tree

However, the former is only compatible with Gradle 2.x and the latter isn't really actively maintained. 

### Context
This a very popular plugin https://github.com/dorongold/gradle-task-tree, and we've gotten a lot of feedback from folks that suggest this should be built-in

**Comment by bmuschko** [comment]
This issue is a duplicate of https://github.com/gradle/gradle/issues/980.

**Comment by lptr** [comment]
Instead of a task hierarchy, what I usually find asking is "why did task X get triggered when I asked for task Y". In a project where there are lots of tasks, it might be more useful to address this use case.

**Comment by eriwen** [comment]
Alright, closing as duplicate of #980
