### ISSUE TITLE
Tampered file in local Gradle cache

### ISSUE THREAD

**Issue by mockitoguy** [gradle/gradle#4934]
What is the desired behavior of Gradle when local dependency cache is tampered?

Specific example: a jar file in dependency cache is modified (some files are removed from the archive) but the file keeps the same name and the absolute path. We observe that Gradle uses tampered file and does not detect that its checksum is different than when the file was put in dependency cache. Running with "--refresh-dependencies" does not help, either (more info - [forum ticket](https://discuss.gradle.org/t/refresh-dependencies-option-doesnt-refresh-gradle-cache/26285))

Is the current behavior considered a bug or a design choice?

I'd like to propose to consider the current behavior as a bug. I would like to reliably reuse Gradle cache on CI hosts for different builds, so that I can maximize build speed and productivity of our teams. If the jar files in dependency cache can be tampered with and it remains unnoticed it can lead to issues.

Consider this scenario: a Java library is tested, built and released from CI host A. The library depends on 3rd party dependency "util". Later, this library is packaged into a Java service, a war file. However, the war is built on CI host B, which has tampered "util" jar in the local dependency cache. In result, I have a deployable war packaged with a library and tampered "util" jar. The library was not tested and built with tampered "util" so there is no guarantee it will work. Hence, my Java service may not work.

I'd like to use this ticket to identify the desired behavior of Gradle for this use case. Once this is done, let's think how to solve it. Our team at LinkedIn can help and prepare a design spec / pull request.

Thanks in advance for considering!

**Comment by Deepak-D** [comment]
Hello @oehme, I find this issue as related to my requirement. I created a new topic related to this in Gradle forum ([click here](https://discuss.gradle.org/t/how-to-protect-war-file-from-tampering/32290) to know more). I'm looking to protect my WAR file from tampering post build of my gradle project.

Could you please, confirm if we already have a working solution? If Yes, please advise me how to do this else I would strongly recommend to include this in future release for security purpose. If there are any plans to implement this in the future, could you tell in which version it would likely to be released?

Thanks in advance!

**Comment by paplorinc** [comment]
cc: @melix

**Comment by Deepak-D** [comment]
Hello again @oehme / @paplorinc / @melix, Do we have any workaround solutions to protect WAR file from tampering for the time being?

**Comment by melix** [comment]
This behavior is not a bug. The local dependency cache is not supposed to be altered by anyone, and is designed to be _fast_. Of course we can't prevent anyone from:

1. intentionally change a file in the cache, for "legitimate" reasons (there are none, really)
2. maliciously change a file, in which case there are probably easier ways to compromise a build

Adding a validation step here would require checking the hashs of the files _everytime_, which has a serious performance impact. There are strategies to mitigate this cost, but they would reduce the security.

So currently there's no plan to work on this _for the local cache_.

However, we _do_ have a plan for adding checksum (and signature) verification for remote dependencies, but this is a slightly different problem.

@Deepak-D on a side note, we receive _lots_ of reports, it's not nice to ping twice on the same day for the same topic.
