### ISSUE TITLE
Set up Java 11 test stage

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4938]
For now this can be weekly or on demand, since 11 is not very stable yet.

**Comment by blindpirate** [comment]
Now the stage is set but Java 11 is pretty unstable (actually I even found and reported a bug in Java 11) so I think we'd wait for it being a bit more stable.

**Comment by oehme** [comment]
Is there a follow-up epic for all things related to Java 11 support? If not, we should create one and assign it to 4.9 RC1

**Comment by blindpirate** [comment]
Writing :-)
