### ISSUE TITLE
Mark maven-publish and ivy-publish as stable

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4939]
Once other issues in #1165  are ironed out, these should be promoted as the definitive plugins for publishing.

This should include:

- remove `@Incubating`
- update documentation to clearly mark them as the default way to publish (e.g. a link in the old maven/ivy plugins)
- update the "publishing artifacts" documentation
- ensure that all samples for publishing use these plugins
- add a mention in the release notes

**Comment by marcphilipp** [comment]
I just stumbled upon this:
https://docs.gradle.org/current/userguide/publishing_ivy.html#publishing_ivy:future

> Convenient customization of module attributes (`module`, `organisation` etc.)

`module` is already customizable, `organisation` and a few others could be added similar to #3348.

> Convenient customization of dependencies reported in `module descriptor`.

Do we even want this?

> Multiple discrete publications per project

Not sure what that means. Multiple publications already work.

@oehme Thoughts?

**Comment by oehme** [comment]
The first two are indeed the Ivy equivalent of #3348. Not sure about dependencies either. We certainly want to be able to influence what is published, but probably in a Maven/Ivy-independent way instead of messing with the descriptor files.

Multiple publications don't really work, because you can't depend on a project with multiple publications. (#1061)

**Comment by marcphilipp** [comment]
As part of this issue, I want to make sure that our documentation on publishing is clearly structured and sends the message that the new Maven/Ivy Publish Plugins are the preferred way to publish artifacts.

Here's what we currently have in the User Guide sidebar:

<img width="236" alt="screen shot 2018-05-03 at 12 21 26" src="https://user-images.githubusercontent.com/214207/39571664-8f0a9198-4ecc-11e8-8bf4-a3f53b20f3e3.png">

- Distribution Plugin (Old? both?)
  - Currently documents how to publish using the Maven Plugin and `uploadArchives`
  - Not clear if it can be used with the new publishing plugins
- Maven Plugin (Old)
  - Belongs to the old infrastructure, not needed anymore, will eventually become obsolete
- Maven Publish Plugin (New)
  - features as "new" in the page title
- Ivy Publish Plugin (New)
  - features as "new" in the page title
- Publishing Artifacts Overview (Old)
  - documents the old publishing mechanism
  - is referenced from the Maven and Ivy Publish Plugins (in a note in "Publications" section)
- Signing Plugin
  - part of the old and new publishing mechanism

I think we should have a new Publishing Artifacts Overview that explains that briefly there are two mechanisms and links to the relevant chapters. But I'm not sure what to do about the sidebar. We could add "(Old)" and "(New)" to all items but that would look silly.

@pledbrook @eriwen @oehme I'd be happy to hear your ideas how to structure these chapters.

**Comment by oehme** [comment]
I think we should change the distribution plugin to use `maven-publish`. I'm not sure why that plugin is listed under `publishing artifacts` specifically, as it is about building distributions. Sure, distributions are usually published, but it's not a perfect fit.

The "publishing artifacts overview" should be split. Artifacts are still a thing, they are attached to a `Configuration`. A `Configuration`s artifacts are used by

- dependency management inside a project
- publishing with the old `Upload` task
- publishing with the new publishing plugins (where you usually just specify a SoftwareComponent, which then knows which Configurations need to be published with it)

The chapter currently explains artifacts only in the context of the `Upload` task, which is causing a lot of confusion for our users. I think such a general treatise of artifacts belongs in the dependency management chapter.

I'd name the remaining chapters 

- Maven Publish Plugin
- Ivy Publish Plugin
- Old Maven Plugin
- Old Ivy Plugin
- Signing Plugin

**Comment by pledbrook** [comment]
One of my goals is to move plugin reference chapters out of the side nav and make them accessible/searchable from a Plugin Reference page. That would include the chapters:

 * Maven Plugin
 * Maven Publish Plugin
 * Ivy Publish Plugin
 * Signing Plugin

For now, I would leave them in that section of the navigation. I'm fine with the rename suggested by @oehme, although I'm not sure there is an old Ivy plugin. I would put the Maven Plugin or Old Maven Plugin last.

I absolutely agree with @marcphilipp that we need a general page for publishing. I wouldn't even call it an overview. It's something I'd be willing to work on, but that would depend on what the deadline is for these improvements. Its focus should be on the "new" publishing mechanisms, with links to other pages that detail the old upload approach.

One last thing: I would really like clarity throughout the user manual on the use of "artifact", "archive" and "component". And any other word that is close in meaning in Gradle terminology. Sometimes I see "archive" when I expect to see "artifact" and I don't really know what "component" is about. On top of that we have "module" in the area of dependency management. It's important we're consistent and explain the terms in a way that clearly differentiates them.

**Comment by eriwen** [comment]
@pledbrook we want to improve publishing documentation for Gradle 4.8 within the next week, but then further refine it for Gradle 5.0 I imagine as we work on finishing the maven-publish plugin. 

We have the Dependency Management Terminology page that may be helpful for defining these terms. I personally don't care for the fact that we restrict that to dependency management. I would prefer exactly 1 glossary that's linked to from everywhere.

**Comment by oehme** [comment]
- component: A Gradle term for a thing that you can depend on, potentially providing different variants
- module: A term inherited from Ivy. A module is the combination of organisation + name (or groupId+artifactId), without the version. I.e. it identifies a body of code over its lifetime, e.g. `com.google.guava:guava`
- module component: A component provided by a module. You get this by selecting a specific version of a module, e.g. `com.google.guava:guava:21`
- project component: A component provided by a project in a multi-project or composite build
- variant: a combination of metadata (like its dependencies and attributes) and artifacts
- artifact: the file that the user actually cares about in the end, e.g. a JAR
- archive: just a special kind of artifact

**Comment by pledbrook** [comment]
@oehme This demonstrates the problem :smile: Your definition of "component" seems to match the definition of "module" in [the dependency management terminology](https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub:terminology_module) chapter. Your definition of "module" sounds like a dependency coordinate to me, simply without the version.

Reading all of them together, I think I can see the distinctions, but I still find "component", "module", and "project" too fuzzy as labels and I think we'll struggle to ensure consistency in the user manual with their usage. Not sure what we can do about it though!

@eriwen Agreed. A single glossary makes sense to me.
