### ISSUE TITLE
Deprecate Upload-based publishing infrastructure

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4940]
Once `maven-publish` and `ivy-publish` are marked stable (#4939) and all crucial bugs (e.g. #1061) have been fixed, deprecate the old publishing infrastructure, including:

- the `maven` plugin
- the `Upload` task
- the `archives` configuration

The documentation needs to changed in a few places, including `buildingJavaProjects.adoc`.

**Comment by oehme** [comment]
That's right, I don't expect a removal before Gradle 6.0

**Comment by ljacomet** [comment]
* Gradle 6.0 will deprecate the `maven` plugin, the usage of `uploadArchives`.
* General deprecation of the `Upload` task will happen slightly later.
* As for the `archives` configuration, this needs a bit more attention as it is currently used for linking production of JARs by the `java` plugins to the `assemble` lifecycle task.

**Comment by ljacomet** [comment]
Created #10796 and #10797 as follow ups.

Closing this as the deprecation is already on `master`.

**Comment by opluscustom** [comment]
> 
So please help me how to resolve problem as https://github.com/gradle/gradle/issues/1061
I see u have close the issue，but I can not find the right Solution.
Thanks very much！
