### ISSUE TITLE
Better task failure diagnostics

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#4947]
When a task fails, it can provide diagnostic information in several ways:

1. By printing diagnostic information to stdout
1. By printing diagnostic information to stderr
1. By printing diagnostic information to both stdout and stderr
1. By providing diagnostic information in the exception it throws

4 can easily be accessed with a `TaskExecutionListener` and is printed to stderr at the end of the build.  Starting with 4.7, 1, 2, and 3 are now grouped together on stdout with the task that produced the information, and obviously this is information that build scans (https://scans.gradle.com) provide, but it would be nice if there was some way for the user to capture this additional task diagnostic information themselves and implement their own handling of task failures (by writing to a "failure" log or some other handling mechanism).

For instance, one way would be to provide a way to capture the stderr/stdout messages that a task produces.  You can currently register a stdout and stderr listener while a task is running, but this gets _all_ output produced while the task is running.  If multiple tasks are running in parallel, you could receive output produced by other tasks.  On the other hand, if there were a way to capture _only_ the output associated with the task where the listener is registered, the user could implement their own custom handling of that information.

We should explore the options for providing better mechanisms to access this diagnostic information.

### Expected Behavior
The user can easily access _all_ diagnostic information produced by a task when it fails.

### Current Behavior
Some of this information is only printed on stdout.

### Context
Users who want to implement custom handling of task failures do not have good mechanisms for doing so.

**Comment by ldaley** [comment]
@ghale I have a bit to add to this. I will organise to sync with you soon.
