### ISSUE TITLE
Provide a default config file for checkstyle plugin

### ISSUE THREAD

**Issue by javintx** [gradle/gradle#4952]
Hi,

I think that could be a good improve if we can set a default checkstyle.xml file without need to have that file. (like  #420)

### Expected Behavior
Something like:

```
apply plugin: 'checkstyle'
checkstyle {
  toolVersion = "8.9"
  config {
    sun.enabled = true
    // Or
    //google.enabled = true
    // Or
    //custom.enabled = true
    // file = new File("custom.xml")
  }
}
```

### Current Behavior
Always it is necessary to have the configuration xml file.

### Context
We simplify the process of project configuration if we don't have to copy the sun or the google xml config files in all projects. Many projects uses sun or google configuration.

Thanks!

**Comment by seamlik** [comment]
This would be great. Checkstyle itself already supports using a config from within its JAR, and the official release already bundles the Google and Sun configs. Unfortunately we can't use them in Gradle, and I'm not sure if we can even apply custom commandline flags to Checkstyle.

The workaround is usually like downloading them from GitHub, which wastes time and traffic.

**Comment by javintx** [comment]
> This would be great. Checkstyle itself already supports using a config from within its JAR, and the official release already bundles the Google and Sun configs. Unfortunately we can't use them in Gradle, and I'm not sure if we can even apply custom commandline flags to Checkstyle.
> 
> The workaround is usually like downloading them from GitHub, which wastes time and traffic.

If it is not possible to implement it as you say, it could use a configuration (Google or Sun) by the default. 

The major idea is to make it as easy to use as possible, so you don't need to configure an specific checkstyle configuration to have it. May be it would not be the best option, but it is commonly used in many projects.

**Comment by swankjesse** [comment]
I got close to this by following examples from [Caffeine](https://github.com/ben-manes/caffeine/). [Here’s a PR](https://github.com/square/okhttp/pull/5720/files) if you’d like to copy-paste. But it‘s 9 lines of awkward configuration when I think this could be a 1-liner.

**Comment by anshupitlia** [comment]
Are we looking towards fixing it?

**Comment by anshupitlia** [comment]
> I got close to this by following examples from [Caffeine](https://github.com/ben-manes/caffeine/). [Here’s a PR](https://github.com/square/okhttp/pull/5720/files) if you’d like to copy-paste. But it‘s 9 lines of awkward configuration when I think this could be a 1-liner.

This config works like a charm.
