### ISSUE TITLE
tarTree silently excludes .git files

### ISSUE THREAD

**Issue by jmkk** [gradle/gradle#4955]
### Expected Behavior
When using tarTree within a Copy task to unarchive a tar file, all files contained within the archive should get extracted, unless Copy task is configured to filter/exclude explicitly.

### Current Behavior
tarTree silently skips extracting certain files, namely `.git` and `.gitignore`

### Context
Using gradle Copy tasks to extract archives containing git repos is broken.

### Steps to Reproduce (for bugs)
1. Create a tgz archive containing `.git` and/or `.gitignore` files among other files, for example:
```
tar --gzip --list --file=xxx.tgz
xxx/
xxx/.gitoooooo
xxx/.gi
xxx/.gitignore
xxx/file1
xxx/.git
xxx/.file2
```

2. Create a task to extract the tgz
```groovy
task unzip(type: Copy) {
    def tarFile = file('xxx.tgz')
    def outputDir = file("${buildDir}/unpacked")
    from tarTree(tarFile)
    into outputDir
}
```

3. Run the task `gradle unzip`

4. Observe the extracted files: `ls -1aR build/unpacked/xxx`
```
.file2
.gi
.gitoooooo
file1
```

5. Note missing `.git` and `.gitignore` files.

### Your Environment
Gradle 4.6
Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.13.4 x86_64

**Comment by mkobit** [comment]
Sounds similar to what I ran into in https://github.com/gradle/gradle/issues/1348 which resulted in https://github.com/gradle/gradle/issues/2986

**Comment by jmkk** [comment]
Closing this, as it's a dupe of https://github.com/gradle/gradle/issues/2986
