### ISSUE TITLE
Change the default location for annotation processor generated sources to a source directory

### ISSUE THREAD

**Issue by nniesen** [gradle/gradle#4956]
The annotation processors default behavior is to write the generated sources to the `/build/classes/java/<sourceSet>/` folder. This pollutes the compiled classes directory and implementation JAR with source code. Also, the sources are not available in the sources JAR file and are not included as source folders in the IDEs (https://github.com/gradle/gradle/issues/4499).

### Expected Behavior
* The `options.annotationProcessorGeneratedSourcesDirectory` should default to a source directory. For example: `build/generated/src/<sourceSet>/java`
* Gradle should automatically create and clean the generated source directories.
* The generated source directories should be included as source folders in sources in the IDEs (https://github.com/gradle/gradle/issues/4499).
* The generated sources should be included in the `*-sources.jar`

### Current Workaround
Example to configure a different output directory for the main source set in `samples/java/incrementalAnnotationProcessing/user/build.gradle`:
```
compileJava {
    String relativePath = "build/generated/src/main/java"
    sourceSets.main.java { srcDir relativePath }
    File generatedSourceDir = project.file("build/generated/src/main/java")
    println "Creating and configuring generated source directory $generatedSourceDir"
    project.mkdir(generatedSourceDir)
    options.annotationProcessorGeneratedSourcesDirectory = generatedSourceDir
    outputs.dir(generatedSourceDir)
    
    doFirst {
        // force a clean of generatedSourceDir to prevent java.lang.IllegalStateException: endPosTable already set. This shouldn't be need if using Gradle 4.8+ or Java 9+.
        project.delete(generatedSourceDir)
        project.mkdir(generatedSourceDir)
    }
}
```

Related: https://github.com/gradle/gradle/issues/2300

**Comment by xenoterracide** [comment]
converting from the apt plugin and got bitten by this with error prone, because I had, had the sources output to generated so they weren't scanned, then surprise! they are again.
