### ISSUE TITLE
Cannot provide a project-based dependancy with a classifier

### ISSUE THREAD

**Issue by LDVSOFT** [gradle/gradle#4967]
### Expected Behavior
I want to be able to depend on classified library version created in another submodule, something alike:
```
dependencies {
    testCompile project(path: ':foo', classifier: 'test')
}
```

### Current Behavior
There may be something to do this today, but I cannot find any reference of that, should be documented then.
If there is no way to do this, then... should be one implemented?

### Context
I am trying to depend on submodule JAR with a classifier, that can easily done in Maven.
In Gradle, the only workaround is via configurations, that looks hacky:
```
// Module foo
configurations { testJar }

task packageTests(type: Jar) {
    classifier = 'test'
    from sourceSets.test.output
}

artifacts {
    testJar packageTests
}
// Module Bar
dependencies {
    testCompile project(path: ':foo', configuration: 'testJar')
}
```
Trying to use `test` instead of `testJar` fails.

### Your Environment
I am using Gradle 4.4

**Comment by oehme** [comment]
There's nothing hacky about using the Configuration, your second snippet is correct.
