### ISSUE TITLE
SLF4J ClassCastException when putting slf4j on the module path

### ISSUE THREAD

**Issue by christopher-johnson** [gradle/gradle#4974]
See [this repository](https://github.com/christopher-johnson/gradle-junit5-jpms) for a minimal example.

The issue is described in https://github.com/trellis-ldp/trellis/issues/96 and also possibly related to https://github.com/gradle/gradle/issues/2657

**Comment by oehme** [comment]
This is the same problem as #2657, caused by putting slf4j on the module path.

**Comment by oehme** [comment]
Duplicate of #2657
