### ISSUE TITLE
The Sign task should have the signature files as output

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4980]
### Expected Behavior
Task of type `Sign` is not up-to-date when its output file is manipulated or deleted

### Current Behavior
Task of type `Sign` is up-to-date when its output file is manipulated or deleted

### Steps to Reproduce (for bugs)
- run a task of type `Sign`
- modify or delete the generated signature
- rerun the task of type `Sign`

### Your Environment
Gradle 4.6

**Comment by marcphilipp** [comment]
@Vampire Thanks for reporting! Looks indeed like a bug. I'm looking into it right now.
