### ISSUE TITLE
Automatically add a META-INF/IDE/encoding file in source jars

### ISSUE THREAD

**Issue by fbricon** [gradle/gradle#4989]
I'd like to see build tools standardize on storing source encoding information in the generated source jars, so that IDEs would be able to automatically determine which encoding to apply when opening source jars, like in [m2e](https://bugs.eclipse.org/bugs/show_bug.cgi?id=533398). But the goal of this approach is really to be IDE agnostic.

There's a [work in progress on the Maven side](https://issues.apache.org/jira/browse/MSOURCES-113) where we settled on adding a META-INF/IDE/encoding file by default (more details might emerge later when the implementation is finalized).

I'm not too familiar with Gradle, but I'm sure anyone could hack their own build.gradle file to achieve the desired result. But I open this ticket hoping a similar approach can be added as a *default* behaviour (as in convention over configuration), for anyone publishing their project sources to a repository manager.

**Comment by marcphilipp** [comment]
An extra manifest entry would be very simple to add. An extra file would also be easy to implement as a plugin.
