### ISSUE TITLE
Please support optional transitive dependencies in Ivy dependencies like they are supported in POMs now

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#4994]
Having
```groovy
runtimeOnly 'org.apache.logging.log4j:log4j-core:2.11.0'
runtimeOnly('org.fusesource.jansi:jansi') {
    because 'log4j needs it for proper ANSI colors on Windows'
}
```
works if you depend on a Maven repository where the `log4j-core` POM has
```xml
<dependency>
    <groupId>org.fusesource.jansi</groupId>
    <artifactId>jansi</artifactId>
    <optional>true</optional>
</dependency>
```
in it.

If you have an Ivy repository, the respective part of the `ivy.xml` is
```xml
<dependency
    org="org.fusesource.jansi"
    name="jansi"
    rev="1.17"
    force="true"
    conf="optional->compile(*),master(*)"/>
```
This is the one generated by the Ivy `install` task from the Maven Central POM, that we use to build and maintain a corporate Ivy repository.

But using this, results in
```
* What went wrong:
Could not determine the dependencies of task ':application:distZip'.
> Could not resolve all task dependencies for configuration ':application:runtimeClasspath'.
   > Could not find org.fusesource.jansi:jansi:.
     Required by:
         project :application
```

The work-around of course is to explicitly specify the version, but it would be nice if optional dependencies in Ivy files would be supported as they are in Maven files now. (or will be when the feature preview gets promoted)

**Comment by ljacomet** [comment]
As an FYI and as indicated in #5434 when `IMPROVED_POM_SUPPORT` becomes the default in Gradle 5.0, Maven `optional` dependencies will not be parsed and used.

**Comment by Vampire** [comment]
Thanks for the note, this is really sad. :-(
Yet the issue mentions it will probably be reintroduced and then it would still be nice if Ivy metadata is handled the same as Maven metadata.

**Comment by Vampire** [comment]
Closing for now as optional dependencies are not yet reintroduced for poms
