### ISSUE TITLE
Create publishing tasks without model rules

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4998]
Instead of using the software model, use idioms like `DomainObjectContainer.all {}` to lazily create the tasks for each publication and each repository. This removes the need for the software model and makes the tasks easier to configure from build scripts.

The publishing extension still needs to be made available to the software model, since it was available there for a long time.

**Comment by ldaley** [comment]
How will the “lazily” bit work?

**Comment by oehme** [comment]
Lazily as in "when publications/repositories are added". 

```
publications.all {
  repositories.all {
     //create publishing task
  }
}
```

**Comment by ldaley** [comment]
That's quite a stretch of the meaning of “lazy” :)

**Comment by oehme** [comment]
On-demand? ;)
