### ISSUE TITLE
Prevent changing ordering constraints or task dependencies too late

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#5012]
I wanted to make all `BaseStagingTask`s of the `io.codearte.gradle.nexus:gradle-nexus-staging-plugin:0.11.0` plugin be run after any `PublishToMavenRepository` tasks if both are to be executed, so I naturally wanted to add some `mustRunAfter` constraints.

As the task names are generically generated from buildscript configuration I wanted to prevent hard-coding, so that not anyone changes another part of the buildscript and forgets to change this one, so I tried this:

```groovy
tasks.withType(BaseStagingTask) { stagingTask ->
    allprojects {
        tasks.withType(PublishToMavenRepository) {
            stagingTask.mustRunAfter it
        }
    }
}
```

When called with `./gradlew closeRepository publish --dry-run` this worked without error and also was called and so on, it just had no effect whatsoever on the task ordering, `closeRepository` was executed first.

Through some debugging I found out that the problem is, that the following happened:

- `DefaultTaskExecutionPlan#addToTaskGraph` was called for `closeRepository` at which point the task dependencies and ordering constraints are evaluated
- After that `DefaultTaskExecutionPlan#addToTaskGraph` was called for `publish`. `publish` had a `String` task dependency on the actual `PublishToMavenRepository` tasks that were not yet realized at that point.
- When this dependency was resolved, the actual `PublishToMavenRepository` tasks are realized and the closure that should add the `mustRunAfter` constraint gets called
- This is too late, as the `mustRunAfter` was already evaluated

Gradle should follow its typical pattern to prevent user idiocracy and fail the build execution when task dependencies or ordering constraints are tried to be modified when they are practically effectless.

**Comment by oehme** [comment]
This should fail indeed.

It should be fixable by replacing the innermost closure with `stagingTask.mustRunAfter(tasks.withType(PublishToMavenRepository))`

**Comment by Vampire** [comment]
Ah great, you are right.
I didn't think about delayed resolving actually.
A Closure as constraint itself also works.
So either of the following two is working as expected:

---
```groovy
tasks.withType(BaseStagingTask) { stagingTask ->
    allprojects {
        stagingTask.mustRunAfter tasks.withType(PublishToMavenRepository)
    }
}
```
---
```groovy
tasks.withType(BaseStagingTask) {
    it.mustRunAfter {
        allprojects.tasks*.withType PublishToMavenRepository
    }
}
```
---
So then only the error message is missing when you try to modify the constraints or dependencies (didn't actually try the latter, just assuming it also does not do the check) too late.

**Comment by Vampire** [comment]
Here a proper reproducer without any plugins that misbehaves with 4.10.3 but properly fails with an error in 6.5.1:
```kt
open class A : DefaultTask()
open class B : DefaultTask()
open class C : DefaultTask()

tasks.register<A>("a")
tasks.register<B>("b") {
    dependsOn("c")
}
tasks.register<C>("c")

tasks.withType<A>().configureEach a@{
    allprojects {
        tasks.withType<C>().configureEach c@{
            this@a.mustRunAfter(this@c)
        }
    }
}
```
