### ISSUE TITLE
Changing private API in Kotlin causes Java to rebuild, but changing method body is not

### ISSUE THREAD

**Issue by alexey-tsvetkov** [gradle/gradle#5013]
Consider the following project: https://github.com/alexey-tsvetkov/gradle-change-in-kotlin-private-api-causes-java-rebuild
Two subprojects ':app' and ':lib' (':app' depends on ':lib'), both use Kotlin and Java.
Changing a method body in Kotlin in ':lib' does not cause Java (in both subprojects) to rebuild.
But adding/removing a private function (1efe0b233efb82c4bacfbde5b1b8eed7f4a95a8e) in Kotlin class causes Java to rebuild.
I'm guessing it happens because all Kotlin classes are annotated with `@kotlin.Metadata`,
which stores serialized Kotlin metadata as an argument (information about functions nullability, etc. including signatures of private functions).
Is it true that Gradle considers class annotations a part of ABI for Java consumers?

**Comment by oehme** [comment]
It does, because those annotations can be accessed by annotation processors and thus influence the compilation result.
