### ISSUE TITLE
Gradle resolution error

### ISSUE THREAD

**Issue by digital-nomad17** [gradle/gradle#5023]
**Summary**:

Gradle is having issues resolving google map packages in android project.

**Steps to reproduce**:

Unknown

**Expected behavior**:

Google packages to resolve correctly

**Observed behavior**:

Gradle build is getting this error:

`Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath: class com.google.android.gms.maps.model.LatLng, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza class com.google.android.gms.maps.model.PolylineOptions, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza class com.google.android.gms.maps.model.MarkerOptions, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza class com.google.android.gms.maps.model.CameraPosition, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza class com.google.android.gms.location.LocationRequest, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza class com.google.android.gms.location.LocationSettingsRequest, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza class com.google.android.gms.location.LocationSettingsResult, unresolved supertypes: com.google.android.gms.common.internal.safeparcel.zza`

Device and Android version:
minSdkVersion 16
targetSdkVersion 27
android studio version 3.1.1
gradle version 4.1

Screenshots:

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by oehme** [comment]
Please open Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs
