### ISSUE TITLE
Gradle 4.6 Native  Build Failure With Windows 10 and MSVS 2017 SDK

### ISSUE THREAD

**Issue by gblikas** [gradle/gradle#5038]
### Expected Behavior

A successful execution of `C:/Gradle/gradle-4.6/samples/native-binaries/cpp` on Windows 10 with Visual Studio 2017, and the Desktop Development With C++ properly installed. With desktop development default installed, the "Windows SDK 10.0.16299.0 for Desktop C++" is installed. 

### Current Behavior

Windows SDK fails to be found for native build specifications. 

### Context

This issue halts the ability to run and build NativeBuildSpec oriented libraries with the VisualCpp toolchain parameters. Seems like after the Windows 10 SDK for C++ development was properly installed, execution of `vswhere.exe -all -format json` showed a valid SDK directory, however, Gradle was not detecting it. Likewise, the call to  `vswhere.exe -all -legacy -format json` showed no additional fields under "properties", which I believe is what Gradle is parsing. 

### Steps to Reproduce (for bugs)

Hypothetically, a fresh installation of Visual Studio 2017 Community Edition, select the "Desktop Development With C++" and manually install Gradle, according to their [installation page](https://gradle.org/install/). Afterward, navigate to the sample cpp directory for native plugin building (`C:/Gradle/gradle-4.6/samples/native-binaries/cpp`), and try any Gradle command associated with building the NativeBuildSpec-- e.g. `gradle components`. 

### Your Environment

 * Windows 10 x64 
 * Visual Studio 2017 Community 
 * Desktop Development with C++ installed-- default "un-modified". 
 * Universal Windows Platform Development 
 * .Net Desktop Development

### Purposed Solution: 
After installing, the following additional components for C++ development, and re-booting, Gradle was able to build NativeBuildSpec(s): 
- C++/CLI Support
- Windows 10 SDK (10.0.15063) for Desktop C++
- VC++ 2015.3 v140 toolset for desktop
After doing so, a call to `vswhere.exe -all -legacy -format json` shows fields inside of the "properties" key, which points (obviously) to the VC++ 2015.3 v140 toolset, I just installed. Then, I was able to successfully build the NativeBuildSpec target in the sample project(s).

**Comment by lacasseio** [comment]
Issue moved to [gradle/gradle-native #618](https://github.com/gradle/gradle-native/issues/618) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lacasseio** [comment]
Thanks, @gblikas for reporting this issue. I moved the issue to the native issue board so we can prioritize it.
