### ISSUE TITLE
Build option handling with -D instead of -P is confusing

### ISSUE THREAD

**Issue by sic-bre** [gradle/gradle#5040]
example:
```
➜  build-cache-sample gradle clean build --build-cache
BUILD SUCCESSFUL in 1s
5 actionable tasks: 5 executed

➜  build-cache-sample gradle clean build --build-cache
BUILD SUCCESSFUL in 0s
5 actionable tasks: 2 executed, 3 from cache

➜  build-cache-sample gradle clean build -Porg.gradle.caching=true
BUILD SUCCESSFUL in 0s
5 actionable tasks: 5 executed
```

### Expected Behavior
We expect that org.gradle.caching would be recognized when applied as a property on the command line or in a init.gradle script.  Note we first discovered this in our companies init.gradle script when we programatically added the property and found that it was ignored.  We also expect that --no-build-cache will take priority over the property if both are set on the command line.

### Current Behavior
-Porg.gradle.caching=true is ignored if set on the command line or the propery is set on StartParameters in an init.gradle script.

### Context
We are trying to set the default for all builds in or corporation to use caching (the opposite of what the current default is.)  We want the developer to still be able to use the --no-build-cache or -Porg.gradle.caching=false to override the corporate default locally for testing and development purposes.

### Steps to Reproduce (for bugs)
Sample project is provided here: https://github.com/sic-bre/build-cache-sample.git

### Your Environment
Gradle 4.6 and Gradle 4.7-rc-2 run on Mac and Windows inside and outside our firewall.

**Comment by oehme** [comment]
Since caching is a build option, not a project property, it should be `-Dorg.gradle.caching=true`, not `-Porg.gradle.caching=true`.

**Comment by sic-bre** [comment]
This is inconsistent, caching works with
1) Command line argument --build-cache
2) Command line argument -Dorg.gradle.caching=true (a system property set on the command line)
3) gradle.properites value org.gradle.caching=true (a Gradle project property set in build.gradle) 

But not with:

4) gradle.properites vaule systemProp.org.gradle.caching=true (a system property set in build.gradle)
5) Commadn line argument -Porg.gradle.caching=true (a Gradle project property set on the command line)

So it works with Gradle project properties set in the gradle.properties file but not on the command line.
And it works with system properties set on the command line but not the gradle.properties file.

Note it is documented to work with a Gradle project properties in but not system properties https://docs.gradle.org/current/userguide/build_cache.html

**Comment by oehme** [comment]
Yes, this inconsistency exists for all build options.

**Comment by sic-bre** [comment]
I believe there are some bugs that can be fixed by enabling all the ways to set the option.  This should probably be done for all the build options that have this behavior:

* If a command line system property -Dsomepropery then the build.gradle value  systemProp.someproperty should have the same effect.  That is not true in this case.

* If a Gradle project property works in the build.gradle file it should also work on the command line -P.    That is not true in this case.

* Finally if a property is set both by systemProperty and Gradle project property.  The precedence between the two in controlling the behavior should be well documented in https://docs.gradle.org/current/userguide/build_cache.html, https://docs.gradle.org/current/userguide/command_line_interface.html, and https://guides.gradle.org/using-build-cache/

Given the legacy behavior the fix that would not break existing builds would be:

* Fix so that both -Dorg.gradle.caching=(true|false) and -Porg.gradle.caching=(true|false) work on the command line.

* Fix so that both systemProp.org.gradle.caching=(true|false) and org.gradle.caching=(true|false) work in the gradle.properties

* Verify and document that the precedence in setting caching is:

1) --no-build-cache / --build-cache enables last entry on the command line wins
2) -Porg.gradle.caching=(true|false)
3) org.gradle.caching=(true|false) in gradle.properties
4)  -Dorg.gradle.caching=(true|false)
5) systemProp.org.gradle.caching=(true|false) in gradle.properties
