### ISSUE TITLE
When running a build scan with the --quiet flag, the publishing output is still sent to standard output

### ISSUE THREAD

**Issue by sic-bre** [gradle/gradle#5043]
When running a build scan with the --quiet flag, the publishing output is still sent to standard output.

example:

```
build-scan-sample% gradle clean build --quiet --scan 2>/dev/null

Publishing build scan...

https://gradle.com/s/m5h66xqaco6di 
```

### Expected Behavior
Only user defined output and fatal error messages should be output (and that only on stderr) when using --quiet.  Standard Gradle plugins should including the build scan plugin should not output data in quiet mode.

### Current Behavior
See example above

### Context
Some of our automated build steps in Jenkins pipelines read the standard output of gradle --quiet and parse the the stdout stream returned.  The only plugin that produces output with the --quiet flag is the build scan plugin.  We have had to introduce a HACK to filter out this output from our parser as a temporary work around. 

### Steps to Reproduce (for bugs)
Example is in https://github.com/sic-bre/build-scan-sample.git

### Your Environment
Gradle 4.6 and Gradle 4.7-rc-2 all environments with build-scan plugin version 1.12 & 1.13.1.
https://gradle.com/s/m5h66xqaco6di

**Comment by ldaley** [comment]
Hi @sic-bre. This is a bug that we will fix for the next version. In the meantime, you can use a hidden internal feature to get the behaviour you want. You can add `-Dscan.quiet` to the command line arguments to Gradle.

Please note that this feature is not public and may change at any time. However, it works as of the latest release and in the next release the build scan plugin will honour `--quiet`, so should be safe for you.

**Comment by bmuschko** [comment]
@ldaley Do you have a rough ETA on when a new version of the build scan plugin is going to be released including a fix for this issue?

**Comment by ldaley** [comment]
@bmuschko no I don't. Do you have a burning need?

**Comment by sic-bre** [comment]
@ldaley Not a burning need just trying to plan on when I can remove and validate the work around from our flow to accommodate this issue.

**Comment by etiennestuder** [comment]
@bmuschko We will most likely implement and release sometimes next week. I cannot be more precise than that at this time.

**Comment by guylabs** [comment]
@sic-bre we released `1.13.2` of the build scan plugin which fixes that issue. Please upgrade to this version.

Thanks for reporting this bug.

**Comment by sic-bre** [comment]
Thanks.  This is now adopted by our init.gradle script and functionality is verified.

**Comment by mwos-sl** [comment]
Actually I need the opposite feature :D To get build scan url somehow, while we're using `--quiet` mode. Is there a flag for this?
Or maybe there is a separate gradle tasks that prints last build scan url?

**Comment by lukeramsden** [comment]
Bump on this - can I get a build scan URL without removing usage of --quiet?

**Comment by guylabs** [comment]
@lukeramsden You can register [this callback](https://docs.gradle.com/enterprise/gradle-plugin/#capturing_the_build_scan_id_or_address) and print the Build Scan URL by yourself as this will be printed as mentioned [here](https://docs.gradle.org/current/userguide/logging.html#sec:sending_your_own_log_messages).

**Comment by erichaagdev** [comment]
Here's an example of doing the opposite (printing the Build Scan URL on `--quiet`) that is configuration cache compliant. You can use this in `settings.gradle.kts`:

```kotlin
abstract class IsQuietValueSource : ValueSource<Boolean, ValueSourceParameters.None> {
  override fun obtain(): Boolean {
    val logger = Logging.getLogger(IsQuietValueSource::class.java)
    // If --quiet is used, everything above QUIET will be disabled (so, WARN and above)
    return !logger.isWarnEnabled && logger.isQuietEnabled
  }
}

develocity {
  buildScan {
    val isQuiet = providers.of(IsQuietValueSource::class.java) { }
    buildScanPublished {
      if (isQuiet.get()) {
        println("\nPublishing build scan...\n$buildScanUri\n")
      }
    }
  }
}
```
