### ISSUE TITLE
Gradle Plugin Development Plugin should allow customization of Ivy descriptor of plugin marker

### ISSUE THREAD

**Issue by jwclark** [gradle/gradle#5044]
### Expected Behavior
GradleJavaPlugin's IvyPublication for the plugin marker should allow ivy.xml customization, specifically the ability to change 'status' from 'integration' to 'milestone' or 'release'.

### Current Behavior
There is no clear method for setting the generated plugin marker IvyPublication status attribute to something other than 'integration'.

### Context
We are trying to publish gradle plugins to our internal ivy repository. We are currently manually creating the marker ivy publication so that we can correctly set the status attribute.

### Steps to Reproduce (for bugs)
1. apply java-gradle-plugin and ivy-publish plugins to build.
2. configure plugin using gradlePlugin extension
3. configure ivy repository using publishing extension
4. Run 'gradle publish'

### Your Environment
Gradle 4.6

**Comment by jjohannes** [comment]
This is a duplicate of: #6925
