### ISSUE TITLE
Add task to run installed native executable

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#5047]
I want to run a native executable installed by the install task. Prior to 4.7, I could create another exec task that depended on the installed task whose commandLine was set to the runScript property of the install task. However I realize that that method was internal, and in 4.7 that was removed. It looks like runScriptFile could work, but I can't figure out how to actually get the property out of what that returns in a groovy scripts. Plus, it seems like I shouldn't need internal methods to create a run task. Either one should be there already, or there should be a public way to get the created run script.

**Comment by lacasseio** [comment]
Issue moved to [gradle/gradle-native #629](https://github.com/gradle/gradle-native/issues/629) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lacasseio** [comment]
Thanks @ThadHouse for this feature request. Because this issue is related to Gradle native, I moved it to the [`gradle/gradle-native` repository](https://github.com/gradle/gradle-native).
