### ISSUE TITLE
The new gradle requires removing & re-adding dependencies (again and again)

### ISSUE THREAD

**Issue by johan974** [gradle/gradle#5055]
### Expected Behavior
My Android app uses gradle for many years. After migrating to the new gradle version, the build should complete successfully. 

### Current Behavior
After upgrading to the newest gradle version, I get errors because dependencies cannot be found. 
The cure is, over and over again, to comment out the specific dependencies, perform a "sync now" for gradle, then un-comment them back again. Then everything works fine.  No code change is needed. 

### Context
Using Android Studio (newest), after upgrading I have to rebuild the project a number of times after supposed errors. 

### Steps to Reproduce (for bugs)
See above, comment the dependences yielding the error and then uncommenting the lines solves the error. For example with Fabric.io. 

   compile('com.crashlytics.sdk.android:crashlytics:2.7.0@aar') {
        transitive = true;
    }

Another was the osmdroid packages. 

### Your Environment
Android Studio newest. Build tools 27.0.0.

**Comment by oehme** [comment]
Please report Android problems on the [Android issue tracker](https://source.android.com/source/report-bugs).
