### ISSUE TITLE
Example in JavaDoc for AuthenticationSupported should be updated to follow idiomatic gradle

### ISSUE THREAD

**Issue by robin-a-meade** [gradle/gradle#5057]
The [example](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/repositories/AuthenticationSupported.java#L59)

```
repositories {
    maven {
        url "${url}"
        credentials {
            username = 'joe'
            password = 'secret'
        }  
    }  
}
```

should be updated to remove the assignments because:

"No assignment is required during configuration as Gradle decorates the properties to allow for a more declarative DSL." [1]

[1] https://guides.gradle.org/writing-gradle-tasks/#make_the_message_configurable

In addition, this will make the example consistent with the AwsCredentials example below it, which _does_ use assignment-less idiomatic gradle.

**Comment by marcphilipp** [comment]
Closing with rationale from https://github.com/gradle/gradle/pull/5058#issuecomment-394606785.
