### ISSUE TITLE
JavaCompile::getDependsOn changed between 4.3 and 4.5 (returns empty set now)

### ISSUE THREAD

**Issue by osklyar** [gradle/gradle#5062]
The behaviour of `JavaCompile::getDependsOn` (and thus, possibly, of `AbstractCompile::getDependsOn` has changed somewhere between the releases 4.3 and 4.5 (still the same in 4.7-rc-2).

In 4.3. the method was returning (when printed) `[task 'compileJava' input files]`, which included all the dependencies required for to compile the sources. This permitted creating other `compile` like tasks to be executed _before_ Java compilation by copying all the dependencies of the `compileJava` task. For example, plugins providing `AspectJ` compilation, such as http://github.com/teris-io/nox, used this technique to inject the `compileAspect` task before compiling Java _and_ to have all the project dependencies respected correctly. As of at least 4.5 `JavaCompile::getDependsOn` returns an empty set, making copying of dependencies impossible leading to random build errors due to missing dependent jars. This also does not reflect the actual state of the dependencies graph as the documentation explicitly says that `compileJava` depends on all the jars on the dependency list.

### Expected Behavior
`JavaCompile::getDependsOn` to return an actual set of dependencies that can be reapplied elsewhere.

### Current Behavior
`JavaCompile::getDependsOn` returns an empty set in 4.5->4.7-RC2. Worked correctly in 4.3.

### Context
Provide a compilation task that has exactly same set of dependencies as `compileJava`

### Steps to Reproduce (for bugs)
println(compileJava.getDependsOn())

### Your Environment
OSX

**Comment by marcphilipp** [comment]
`JavaCompile::getDependsOn` eagerly returns a snapshot of the current (mutable) dependencies. 

@osklyar Have you tried using `JavaCompile::getTaskDependencies` instead?

**Comment by osklyar** [comment]
`compileJava.getTaskDependencies().getDependencies(compileJava)` returns a full and correct set of dependencies for the compile task. So even though it is a change of behaviour, probably, my original reliance on `getDependsOn` was wrong.

What I am still puzzled about is the following: `setDependsOn` accepts `TaskDependency` among others, however, it is not clear how is it going to extract the dependencies to set if `TaskDependency` has only one method, `getDependencies(task)` needing a reference to a task and `setDependsOn` does not actually have a reference to a task we want to copy from. So, which of the two should I use to copy dependencies of a task:

- `compileAspect.setDependsOn(compileJava.getTaskDependencies().getDependencies(compileJava))`
-  `compileAspect.setDependsOn(compileJava.getTaskDependencies())`

**Comment by marcphilipp** [comment]
The `task` parameter of `TaskDependency.getDependencies(task)` is nullable and rarely used. So, in your case, I would use `compileAspect.setDependsOn(compileJava.getTaskDependencies())` instead of eagerly computing the dependencies by calling `getDependencies()`.

**Comment by osklyar** [comment]
@marcphilipp The above has shifted the problem into a different area, for which I have a workaround, but I would be grateful for an idea for a clean solution if you have any:

I am copying dependencies from `compileJava` to `compileAspect` in `Plugin::apply`, that is when `nox.AspectJ` plugin is applied, it applies the `JavaCompile` plugin _and_ copies the dependencies via `this.setDependsOn(compileJava.getTaskDependencies().getDependencies(compileJava))`. The problem is that, normally, plugins are applied at the top of the build script, before `dependencies` declaration, so no actual dependencies are copied if that order is preserved. Moving `plugins.apply(nox.AspectJ)` below the `dependencies` declaration provides a workaround, but in essence I would rather prefer a mechanism to register a callback on `setDependencies` where I could copy all the newly added dependencies to the `compileAspect` task. Else I am forcing the user into maintaining a fix order between plugin application and dependency declaration. 

Possible?

**Comment by marcphilipp** [comment]
Does this also happen when you use `this.setDependsOn(compileJava.getTaskDependencies())`?

**Comment by osklyar** [comment]
That way my Kotlin-based plugin won't compile in https://github.com/teris-io/nox/blob/b13a8beea57c01f6ee5811e5e5fa27194423311f/src/main/kotlin/nox/AspectJ.kt#L60: `ajc.setDependsOn(javaTask.taskDependencies)` results in `Type mismatch: Required (Mutable)Iterable<*>! Found: TaskDependency!`. Unfortunately, I cannot try it directly in the build script, because there the `compileJava` is already set to depend on `compileAspect` resulting in circular dependencies.

**Comment by wolfs** [comment]
Why don't you use `this.dependsOn(compileJava.getTaskDependencies())`? Is it important that you override the current dependencies for the task you are configuring?

**Comment by marcphilipp** [comment]
Thanks, @wolfs! That's actually what I meant to write.

**Comment by osklyar** [comment]
@wolfs Yes, that one compiles. Will give it a try now.

**Comment by marcphilipp** [comment]
You should be able to let the `classes` task depend on `compileAspect` and, if necessary, tell the `compileJava` task that it `mustRunAfter(compileAspect)`.

**Comment by osklyar** [comment]
@marcphilipp This has done the job. Thanks a lot for your help.

**Comment by marcphilipp** [comment]
You're welcome, glad it worked out! 🙂
