### ISSUE TITLE
Use `Lookup.defineClass` instead of `ClassLoader.defineClass`

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#5079]
### Context

This is follow-up of #4976 .

Some history:

- Previously, we use reflection to invoke `protected ClassLoader.defineClass` to inject `byte[]` into a `ClassLoader`. 
- After Java9, reflection is forbidden in this case, so we change to `Unsafe.defineClass`.
- Java11 removed the API `Unsafe`, so we change to `Lookup` to invoke `protected ClassLoader.defineClass`.

However as pointed out [here](https://github.com/gradle/gradle/pull/4976#discussion_r180748688):

> Using the legacy or new reflection APIs to call the protected ClassLoader.defineClass methods from the wrong context will break once --illegal-access=deny is the default. Better to work out how to use `Lookup.defineClass`.

The reason why we didn't use `Lookup.defineClass` is, `Lookup.defineClass` can only inject class bytes into same package and same class loader of `Lookup` object. This is a huge limitation for us because in Gradle code base we need to inject class bytes into any class loader without limitation.

**Comment by oehme** [comment]
Fixed by https://github.com/gradle/gradle/pull/5811

**Comment by mlchung** [comment]
The comment states that `Lookup.defineClass` injecting a class in the same runtime package as the lookup class is a huge limitation to Gradle.  What classes is Gradle spinning and what package are they intended to place in?
