### ISSUE TITLE
Maven publish should resolve the Gradle cache

### ISSUE THREAD

**Issue by mjaggard** [gradle/gradle#5086]
### Expected Behavior
When I publish a snapshot of Project A, them run a build of Project B which depends on the same snapshot version of Project A on a single computer, the result should be the to use the latest.

### Current Behavior
The Gradle cache is kept at the old version so I need to refresh dependencies or have snapshots checked frequently to see the new version.

### Context
This will make developers working on multiple projects more productive because they don't need to reconfigure where dependencies come from or refresh manually or have frequent checks for new versions from potentially slow remote systems.

### Your Environment
Behaviour is identical on all platforms. Possible issue between versions of Gradle because they don't share a cache?

**Comment by mjaggard** [comment]
Related to #1165 and #4939

**Comment by oehme** [comment]
The cache is just a cache, not a repository. Gradle will not publish to the cache and will not use cache entries unless they came from the repository the build is using. This is important for reproducible builds.

You can either use composite builds (preferred) or publish/consume from a local repository like mavenLocal().

**Comment by mjaggard** [comment]
I'm not asking to write to the cache, I'm asking to invalidate an entry in the cache that Gradle *knows* is out of date.

**Comment by mjaggard** [comment]
Thanks for the pointer about composite builds - I hadn't seen that before.
Yes, I am publishing to a remote repository.

My thought was that when Gradle builds a project and pushes a version of an artifact to a remote location, it knows that the artifact with the identical group, name and version is now out-of-date in the cache. Therefore it should invalidate that cache entry in order that the next build of some other project will download the new version.

**Comment by oehme** [comment]
Thanks, I had misunderstood your question to be about publishing to a local repository, which is better solved by composite builds.

Updating the cache when publishing to the remote is an interesting idea. However, there are things that could go wrong and the remote might end up not actually serving what you just published (e.g. maybe the things got put into a staging area where they might still be rejected). So I'm not sure we can just make that assumption and update the cache entry.

**Comment by mjaggard** [comment]
Is there an option to mark the cache entry as needing updating, such that a subsequent build with `--offline` specified would still work but the dependency would be checked in other cases?

**Comment by oehme** [comment]
Good point, that would work indeed.

**Comment by mjaggard** [comment]
I haven't hit this problem recently because I don't use my local cache much in my new company but I still think this is relevant
