### ISSUE TITLE
Gradle Wrapper Ignores Logging Flags If After Task(s)

### ISSUE THREAD

**Issue by adamdougal** [gradle/gradle#5098]
### Expected Behavior

When running `./gradlew printSomething -q` without the relevant Gradle version downloaded, I would expect that the only output would be from the `printSomething` task.

### Current Behavior

When running `./gradlew printSomething -q` without the relevant Gradle version downloaded, I still see the download logs:
```
Downloading https://services.gradle.org/distributions/gradle-3.5-bin.zip .........................
```

If instead I run `./gradlew -q printSomething` with the `-q` flag first, it works as expected.

### Context

We have Gradle tasks to print out the version of our app to deploy by looking up the latest version in a repository e.g:

```
VERSION_TO_DEPLOY=`../gradlew getLatestReleaseCandidate -q
../gradlew deployToStage -PdeployVersion=$VERSION_TO_DEPLOY
```
With this bug the download logs are also assigned to `VERSION_TO_DEPLOY` which then breaks the `deploy` task.

### Steps to Reproduce (for bugs)

https://github.com/adamdougal/gradle-wrapper-logging-issue

You can run the `run.sh` to reproduce.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/2i4vzfmgd4dsm

This example uses Gradle version `4.7` but I've also seen this happen with many other versions including: `2.9`, `3.5`, `4.1` and`4.6`.

**Comment by adamdougal** [comment]
Heya, I don't suppose you have any update on this? We are frequently finding teams running into this issue. Happy to raise a PR if you can point me in the right direction.

**Comment by big-guy** [comment]
I don't believe anyone's looked at this.

You can start here:
https://github.com/gradle/gradle/blob/982d3999a0fbb9aa1a236a517e50c3e95631f925/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleWrapperMain.java#L43-L60

This looks eerily similar to https://github.com/gradle/gradle/issues/1895, so my suspicion is that we stop parsing the command-line on the first unrecognized option or we're ignoring options after the first unrecognized option as if they're parameters to that unrecognized option. 

I'm happy to look at a PR.  I would try reproducing the problem in `WrapperLoggingIntegrationTest`

**Comment by pawelprazak** [comment]
Still happening in 7.4:
```
./gradlew run --console=plain --quiet
Downloading https://services.gradle.org/distributions/gradle-7.3.1-bin.zip
    ...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%
...
```

**Comment by ov7a** [comment]
This is still reproducible with 9.5.1

**Comment by jbartok** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
