### ISSUE TITLE
Gradle 4.7 resourceDirs not working

### ISSUE THREAD

**Issue by topjung3** [gradle/gradle#5100]
### Expected Behavior
When I add idea.module resourceDirs = file('src/main/resources/static/js') in build.gradle, I would expect Gradle add resource path 'src/main/resources/static/js' into IntelliJ project structure resource folders.

### Current Behavior
It doesn't add new resource path in IntelliJ configuration.

### Context
I checked resourceDirs, there is a proper path array in, but not working...

### Steps to Reproduce (for bugs)
Make a new Gradle(4.7) Java project in IntelliJ. 
Add directories which are named resource2 and src2 at /src/main/

Add idea plugin and resourceDir in build.gradle.

apply plugin: 'idea'

...

idea {
    module {
        resourceDirs += file('src/main/resources2')
        sourceDirs += file('src/main/src2')
    }
}

And import changes then Gradle add a new source folder in project structure but resource folder doesn't ...

### Your Environment
MacOS 10.13
IntelliJ IDEA ULTIMATE 2017.3.3 - build 173.4301.25
Gradle 4.7
JDK 1.8

**Comment by topjung3** [comment]
Thanks @donat !

**Comment by marcphilipp** [comment]
@donat Shall we close this issue or keep it open until IDEA supports it?

**Comment by donat** [comment]
I think we should keep it open. This issue does not strictly belong to Gradle, however, we (I, specifically) should track JetBrains' progress and the results. Having said that, I'll move the issue to the icebox for the time being.

**Comment by vladsoroka** [comment]
The support has been [added recently](https://youtrack.jetbrains.com/issue/IDEA-195798) for the next IDEA release (2018.3 builds)

**Comment by oehme** [comment]
Thanks! I'm going to close this issue now. @topjung3 please give the 2018.3 builds of IDEA a try.
