### ISSUE TITLE
Can't setupDecomworkspace even in the fine network

### ISSUE THREAD

**Issue by DogSeeker666** [gradle/gradle#5118]
It actually every Gradle build but I only show Minecraft log

Executing gradle command: build Microsoft Windows [Version 6.1.7601] Copyright (c) 2009 Microsoft Corporation.  All rights reserved. F:\Mcreator>cd forge F:\Mcreator\forge>SET "JAVA_HOME=F:\Mcreator\jdk32\" F:\Mcreator\forge>SET JAVA_EXE=%JAVA_HOME%\bin\java.exe F:\Mcreator\forge>SET PATH=%JAVA_HOME%\bin\;%PATH% F:\Mcreator\forge>gradlew -Dorg.gradle.jvmargs="-Xms512m -Xmx1024m" build To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.0/userguide/gradle_daemon.html. FAILURE: Build failed with an exception. * What went wrong: A problem occurred configuring root project 'forge'. > Could not resolve all dependencies for configuration ':classpath'. > Could not resolve net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT.      Required by: BUILD FAILED          :forge:unspecified > Could not GET 'http://repo1.maven.org/maven2/net/minecraftforge/gradle/ForgeGradle/1.2-SNAPSHOT/ForgeGradle-1.2-SNAPSHOT.pom'. > Connection reset > Could not GET 'http://files.minecraftforge.net/maven/net/minecraftforge/gradle/ForgeGradle/1.2-SNAPSHOT/ForgeGradle-1.2-20150805.153118-302.pom'. Total time: 23.795 * Try: secs > Connection reset Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. F:\Mcreator\forge> Task completed with return code 0 in 24736 milliseconds

I tried all my computers inside my house. they got the same result but when I used the computer from outside. It worked, even their internet is far slower than me so I'm sure it is my network system problem
But I can't find any solution

**Comment by oehme** [comment]
Closing since this is a problem in your network, not Gradle.
