### ISSUE TITLE
Gradle and Eclipse plugin on WSL generate configuration with Linux native directories

### ISSUE THREAD

**Issue by lucasvc** [gradle/gradle#5123]
I’m switching from Cygwin to [Windows Subsystem for Linux](https://docs.microsoft.com/es-es/windows/wsl/about) (aka WSL) as development environment.

So I try to generate Eclipse configuration for my projects from a WSL command line using the `eclipse` plugin and its task. But what I got are Linux native directories.

Is this the expected behaviour? I mean, if the Cygwin case is treated as special, should WSL also treated as special, even is an almost trully Linux OS?

I’ve created the repository https://github.com/lucasvc/gradle-eclipse-wsl as an example. I’ve pushed the two `.classpath`'s created by WSL and Cygwin environments.

**Comment by lamba92** [comment]
If you use the Gradle wrapper just call from command line `wsl ./gradlew <task name>` and everything will work just fine. Right now I'm working on few SDKs that need linux for licensing and I've always worked on Windows with JetBrains tools and from the embedded terminal I can call `wsl ./gradlew run` (usng the Java `application` plugins) with no problems so far. On WebStorm (and RubyMine as well if I am not mistaken) is available an extension to use NodeJS installed inside WSL trasparently, i guess something similar can be achieved as well with a plugin.

**Comment by sgijsenot** [comment]
A reliable way of detecting WSL may be reading /proc/version. Example output:

`Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #648-Microsoft Tue Mar 05 18:57:00 PST 2019`

It may be easier and more flexible to make this a setting within the plugin instead though. In the future (or certain situations) you may want to run Eclipse from within WSL, while in other cases you would want to run Eclipse within Windows directly. For my use case, running everything but Eclipse from within WSL would be ideal, but that cannot (yet) easily be accomplished right now. Having a setting for this, developers could configure this from within their own build scripts or from .gradle/gradle.properties in their home directory.
