### ISSUE TITLE
plugin 'application'  task 'startScripts'  create a shell script with  a  wrong path of runnable jar   

### ISSUE THREAD

**Issue by RobinLJB** [gradle/gradle#5125]
I am a rookie about using gradle
and  I try to use "`application`" plugin to build a runnable jar

in  this plugins ,there is a task named '`startScripts`'  , which is to create a shell script to run the jar

but i find that the path of the jar is wrong    

### Expected Behavior
the true file path  of my  runnable jar is under   `/build/libs/`

and the shell script should locate my  jar in this postion

### Current Behavior

actually shell script  locate my  jar under the folder `/build/lib/` which lost an `s`

### Your Environment
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Mac OS X 10.13.4 x86_64

**Comment by RobinLJB** [comment]
in the class `org.gradle.jvm.application.tasks.CreateStartScripts`
its method `getRelativeClasspath()`
```
     @Input
    protected Iterable<String> getRelativeClasspath() {

        return Lists.newArrayList(Iterables.transform(getClasspath().getFiles(), new Function<File, String>() {
            @Override
            public String apply(File input) {
                return "lib/" + input.getName();
            }
        }));
    }
```
it hardcodes the path which is under ` lib` folder

**Comment by marcphilipp** [comment]
The `application` plugin does not create a runnable JAR. It creates a distribution TAR and/or ZIP including an operating system specific start scripts. There's a section in the documentation about [customizing start script generation](https://docs.gradle.org/current/userguide/application_plugin.html#sec:customizing_start_script_generation).

@RobinLJB Does that help?

**Comment by marcphilipp** [comment]
Closing this issue for now. Please reopen/comment should the issue persist.

**Comment by eean** [comment]
the issue here is that startScripts generates a bash file that doesn't work out of the build directory. It would be nice if there was one.

**Comment by lacasseio** [comment]
@eean Could you write the exact steps you are following? The scripts gets generated in some location but only the `installDist` task will copy everything in the right location and should work inside the build directory. If you aren't executing this task and simply trying to execute the script that are generated inside the build directory intermediate location then it is not expected to work.
