### ISSUE TITLE
Memoized Provider variant to avoid expensive operations

### ISSUE THREAD

**Issue by ajoberstar** [gradle/gradle#5126]
When using the Property/Provider API, they provide you laziness benefit by allowing evaluation to be deferred until the Property's value is needed. However, every time you run `get()` on the Provider it evaluates all over again. If it's an expensive evaluation, you have to handle caching the result yourself.

The existing behavior is certainly beneficial in many cases (or at least not detrimental), so I'm not proposing changing it. Just introducing a new method to create a Provider that won't re-evaluate.

### Expected Behavior

A variant of provider should be available that memoizes the computation it's given. This is a contrived example, see context for better ones.

```
def prop = project.objects.property(String)
prop.set(project.providerMemoized { new Date().toString() })
def oldV = prop.get()
Thread.sleep(5000)
def newV = prop.get()

assert oldV == newV
```

### Current Behavior

The existing providers will re-evaluate each time.

```
def prop = project.objects.property(String)
prop.set(project.provider { new Date().toString() })
def oldV = prop.get()
Thread.sleep(5000)
def newV = prop.get()

assert oldV == newV // will fail
```

### Context

A couple plugins I write have use cases like this that I'd like to put in Property/Provider-land:

- Checking for an existing git repo, if it doesn't exist clone it, and return an open Grgit instance to interact with it. This is passed to multiple tasks, so re-opening for each is wasteful.
- Calculating a version number from your Git repo's history.

### Steps to Reproduce (for bugs)

See expected and current.

### Your Environment

Gradle 4.6

**Comment by adammurdoch** [comment]
This is now possible for `Property` by using `finalizeValueOnRead()` added in https://github.com/gradle/gradle/pull/11661. There is not a way to do this for `Provider` yet.

**Comment by adrian-skybaker** [comment]
This would still be useful, I have a provider which generates a timestamp which I want to evaluate at-most once.

**Comment by cloudshiftchris** [comment]
Doable via Kotlin extension function: 

```
public fun <T> Provider<T>.memoize(): Provider<T> {
    val originalProvider = lazy { get() }
    return map { originalProvider.value }
}
```

**Comment by PantherDD** [comment]
I needed this functionality too, and I ended up (mis?)using a `Property` like so:
```java
Provider<String> provider = project.provider(() -> "This is really expensive to calculate");
Property<String> property = project.getObjects().property(String.class);
property.set(provider);
property.disallowChanges();
property.finalizeValueOnRead();
```

**Comment by consp1racy** [comment]
Sadly, `Property` factory isn't available in [`Settings`](https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/Settings.html) script.

**Comment by ljacomet** [comment]
Sorry for the late reply

Given that we have an existing open issue, keeping this one as duplicate
