### ISSUE TITLE
[Gradle 4.7]`java.security.AccessControlException: access denied ("java.util.PropertyPermission" "line.separator" "read")`

### ISSUE THREAD

**Issue by danielsun1106** [gradle/gradle#5131]
### Expected Behavior
The following exception should not occur after gradle bumped to 4.7
`java.security.AccessControlException: access denied ("java.util.PropertyPermission" "line.separator" "read")`

### Current Behavior
The following exception occurs after gradle bumped to 4.7
`java.security.AccessControlException: access denied ("java.util.PropertyPermission" "line.separator" "read")`

### Context
The build on TeamCity CI fails. We have to downgraded gradle to 4.6 for the time being.
* 4.7 fails:
http://ci.groovy-lang.org/viewLog.html?buildId=49104&tab=buildResultsDiv&buildTypeId=Groovy_Jdk8Build_PlusSnapshotDeploy&guest=1

* 4.6 succeeds:
http://ci.groovy-lang.org/viewLog.html?buildId=49158&tab=buildResultsDiv&buildTypeId=Groovy_Jdk8Build_PlusSnapshotDeploy&guest=1

### Steps to Reproduce (for bugs)
1. Clone https://github.com/apache/groovy
2. Bump gradle to 4.7
https://github.com/apache/groovy/commit/2850721b23ffe8f4d985343d4ff70c2a69ca05d5

### Your Environment

* jdk1.8.0
* gradle 4.7
* TeamCity Enterprise 10.0.2 (build 42234), Open Source License
* Linux Ubuntu-1310-saucy-64-minimal 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
 * Build scan URL:  https://gradle.com/s/vsy6mkc4ml3sk

**Comment by marcphilipp** [comment]
@danielsun1106 I believe there's nothing Gradle can do here: Your test suite install a custom security policy that disallows reading the `line.separator` property which Gradle needs to print a line triggered by running the script. I see two options: Remove `println` statements from the code under test or redirect `System.out` for the duration of the test.

**Comment by danielsun1106** [comment]
Thanks for your looking into the issue. I will try according to your suggestion.

**Comment by marcphilipp** [comment]
Sure, you're welcome! Closing this issue for now, please let us know if the problem persists.
