### ISSUE TITLE
Could not find tools.jar in system classpath

### ISSUE THREAD

**Issue by fuyutsuki** [gradle/gradle#5132]
### Current Behavior

I attempted to build jar with `Java 10.0.1` + `Kotlin 1.2.40` + `Gradle 4.7`, but it will not work.

### Your Environment

 * Build scan URL:  https://scans.gradle.com/s/i6rmjselqlm2a/

**Comment by marcphilipp** [comment]
From the stacktrace in the build scan it looks like a problem with the official kotlin-gradle-plugin. Please open an issue on [JetBrains' issue tracker](https://youtrack.jetbrains.com/issues/KT).

**Comment by fuyutsuki** [comment]
Ok, I'm sorry for troubling you.

**Comment by marcphilipp** [comment]
No worries! 🙂
