### ISSUE TITLE
Core or Standard Plugins?!

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#5137]
### Current Behavior
Currently the gradle tools says:
```
* What went wrong:
Plugin [id: 'com.android.library', version: '3.1.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
```
(Gradle Core Plugins)

But the documentation says something about Standard Plugins -> https://docs.gradle.org/current/userguide/standard_plugins.html

### Expected Behavior
I expect the same "naming" for Core/Standard Plugins everywhere

### Context
It is just naming :D
But I write a Blogpost about "it" and don't know how I call such plugins. Either Standard or Core.

**Comment by oehme** [comment]
Core :)

**Comment by StefMa** [comment]
Thanks for the response 🙃
Should we keep the issue open to change the documentation then? Otherwise feel free to close 🔒

**Comment by oehme** [comment]
We'll leave it open, just wanted to give you a quick answer :)

**Comment by StefMa** [comment]
The old standard_plugins doc redirects to https://docs.gradle.org/current/userguide/plugin_reference.html which doesn't mention 'standard' anymore.
Can be closed ✅
