### ISSUE TITLE
unable to suppress/change gradle default output with 4.7

### ISSUE THREAD

**Issue by diacone** [gradle/gradle#5138]
### Expected Behavior
given this build script:
```
import org.gradle.api.Task;
import org.gradle.api.tasks.TaskState;
import org.gradle.api.execution.TaskExecutionListener;

gradle.useLogger(new TaskExecutionListener() {
    void beforeExecute(Task t) {}
    void afterExecute(Task t, TaskState s) {}
})

task first {
    doFirst { println "Hello!" }
}

task second {
    doFirst { println "Hello 2!" }
}
```
I expect to see the following output:
```
./gradlew --console=plain first second
Hello!
Hello 2!
```

### Current Behavior
```
./gradlew --console=plain first second

> Task :first
Hello!

> Task :second
Hello 2!

```

### Context
We need to be able to suppress the default logging output in order to use custom formatting.

### Steps to Reproduce (for bugs)
Just run the above tasks with 4.6 nd 4.7

**Comment by oehme** [comment]
@ghale Might be related to the recent logging changes, can you take a look please?

**Comment by ghale** [comment]
@diacone This has actually been broken for some time with the rich console, but the plain console simply caught up with those changes in 4.7.  I think ultimately we may want to move away from this pattern, but obviously we don't want to prevent you from solving your problems.  It would be good to understand what your use case is - what is the motivation for setting the logger here?  Are you just trying to inhibit the task header or are you looking to decorate it with additional information?  Or something else?

**Comment by diacone** [comment]
@ghale The task header (if you meant \n + the whole line) is something I don't want to be part of the output. Ideally I don't want to see anything except for task outputs.

But the ultimate goal is to be able create a structured log from the build (including stdout/stderr). So, I wouldn't have to deal with that if there is a listener/event emitor wich would provide ALL events from the build or at least a data structure (again complete structured log with all outputs) at the end of the build.

**Comment by aartiPl** [comment]
Additional use cases:
1. When using buildSrc you get a lot of irrelevant logs at the beginning of Gradle builds. I would like to print simple signature with common information at the beginning, but now it will be in the middle of the Gradle log.
2. I have task for updating password in gradle.properties. I can not disable logs for that task and Gradle keeps flooding console with unnecessary logs.

It was quite useful feature - please restore it.
