### ISSUE TITLE
Update publishing section of the new building Java projects user guide chapter in regards to signing capability

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#5164]
Support for signing publications created with the maven-publish/ivy-publish plugin is coming in 4.8: https://github.com/gradle/gradle/issues/4943.

Let's update "Packaging and publishing" of new the new building Java projects user guide chapter 
https://docs.gradle.org/nightly/userguide/building_java_projects.html#sec:java_packaging

It currently says:
> The latter two "Publish" plugins are the preferred options unless you need to sign POMs, for example when publishing to Maven Central. In that case, you need to use the original mechanism with the Maven Plugin.

**Comment by marcphilipp** [comment]
Good catch! I will update it accordingly.
