### ISSUE TITLE
gradle 4.7 Plugin with id 'org.springframework.boot' not found.Plugin with id 'io.spring.dependency-management' not found.

### ISSUE THREAD

**Issue by godpit** [gradle/gradle#5175]
gradle 4.7 Plugin with id 'org.springframework.boot' not found.Plugin with id 'io.spring.dependency-management' not found. springboot1.5.10.RELEASE,spring-boot-gradle-plugin:1.5.10.RELEASE

**Comment by oehme** [comment]
Please provide a reproducible example project.

**Comment by blindpirate** [comment]
Close due to unresponsiveness. Please feel free to reopen it.
