### ISSUE TITLE
gradle cannot update the newest SNAPSHOT jar with the same version

### ISSUE THREAD

**Issue by victorqian** [gradle/gradle#5177]
gradle version:4.6
![image](https://user-images.githubusercontent.com/10111872/39296277-0cd97d00-4973-11e8-9e25-9c2b75da8ecd.png)
Using 'cacheChangingModulesFor' to get the newest SNAPSHOT JAR, but it doesn't work.

**Comment by marcphilipp** [comment]
@victorqian Can you please provide an executable sample project that reproduces the issue?

**Comment by ghale** [comment]
Closing this for now.  We can reopen if we have a way to reproduce the behavior.
