### ISSUE TITLE
Unable to reset `user.dir` system property in Java 11

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#5187]
### Context

Our daemon will reset `user.dir` system property in switching build environment. However, this is implicitly forbidden in Java 11.

https://github.com/gradle/gradle/blob/561b7ec949184b6bc41605b1818d15161fd5209e/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/processenvironment/AbstractProcessEnvironment.java#L92

```
    public void setProcessDir(File processDir) throws NativeIntegrationException {
        setNativeProcessDir(processDir);
        System.setProperty("user.dir", processDir.getAbsolutePath());
    }
```

JDK team's reply https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8202127 is :

> This is not a bug. The "user.dir" property should never be changed in a running VM.

We need to find another solution for this.

**Comment by oehme** [comment]
Relying on user.dir is always wrong in Gradle. It breaks down whenever you invoke your build from a different directory, e.g.

- a subproject directory
- as part of a composite build
- using the `-p` switch.

Users should always use `Project.file` or construct files relative to some existing thing like `project.buildDir`.

The question here is really just: How do we catch code that constructs relative paths from scratch and fail eagerly?

**Comment by oehme** [comment]
@blindpirate Can you point me at any test that was failing because of this?

**Comment by blindpirate** [comment]
@oehme https://builds.gradle.org/viewLog.html?buildId=14474480&tab=buildResultsDiv&buildTypeId=Gradle_Check_Platform_Java11_Oracle_Linux_ide

**Comment by oehme** [comment]
Thanks!

**Comment by oehme** [comment]
I've fixed the tests to be ignored on Java 11+ and made our recommendation against relying on `user.dir` stronger. See https://github.com/gradle/gradle/pull/6139
