### ISSUE TITLE
excludeCategories starts a jvm when "forkEvery 1", causing slow performance

### ISSUE THREAD

**Issue by 4n00p** [gradle/gradle#5191]
### Expected Behavior
excludeCategories allows the test task to skip the test and does not start a new jvm  when "forkEvery" is specified.

### Current Behavior
 A new jvm should not be started to determine if a test class with a JUnit Category should be excluded from the task.

### Context
This is causing slow performance for builds with a large number of tests.

### Steps to Reproduce (for bugs)
I have a simple example here:
https://github.com/4n00p/mastering-gradle/tree/master/Chapter6/Test_Junit_Categories
in the build.gradle, I specify the debug jvmArgs in order to get the message:
"Listening for transport dt_socket at address:"
This lets me know if a jvm has been started ("suspend=n" so I just get a message from the jvm).

There are two tests in my example, in two separate JUnit categories (FastTest and SlowTest).
One test is included and the other is excluded, yet two jvms are started ("Listening transport...").

### Your Environment
This has been demonstrated on gradle 4.7 & 4.3.1
This issue might be related to: 
"--tests seems to initialize every test causing slow performance "
https://github.com/gradle/gradle/issues/3851

**Comment by marcphilipp** [comment]
Gradle can only set a filter for JUnit to include/exclude classes, it cannot determine whether a class contains any included tests on its own. Thus, when you set `forkEvery` to 1, this behavior is to be expected.
