### ISSUE TITLE
Provide an API/DSL to customize the information published in the Ivy module descriptor of an IvyPublication

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5193]
Add a typesafe DSL to specify the following elements/attributes:

* [info](https://ant.apache.org/ivy/history/2.0.0/ivyfile/info.html)
	* [license](https://ant.apache.org/ivy/history/2.0.0/ivyfile/license.html) (0..n)
	* [ivyauthor](https://ant.apache.org/ivy/history/2.0.0/ivyfile/ivyauthor.html) (0..n)
	* [description](https://ant.apache.org/ivy/history/2.0.0/ivyfile/description.html) (0..1)

## Proposed DSL

```gradle
publishing {
  publications {
    myPublicationName(IvyPublication) {
      descriptor {
        license {
          name = "The Apache License, Version 2.0"
          url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
        }
        author {
          name = "John Doe"
          url = "http://example.com/users/john.doe"
        }
        description {
          text = "Some description"
          homepage = "http://example.com/projects/foo"
        }
      }
    }
  }
}
```

**Comment by lavcraft** [comment]
It's useful for MavenPublication too i guess

**Comment by marcphilipp** [comment]
@lavcraft Customizing the POM is already in the works in #5183.
