### ISSUE TITLE
FileTree skips files which names start with dot

### ISSUE THREAD

**Issue by guai** [gradle/gradle#5195]
gradle 3.3
it affects `delete` task and so these files never being deleted
Maybe it makes some sense on unix, where they have a convention that this files kinda hidden
But definitely not on windows

**Comment by oehme** [comment]
These are the default excludes we took over from Ant, you can overwrite them, e.g. specify an empty set of exludes.

**Comment by guai** [comment]
Nevermind, I got it

**Comment by guai** [comment]
No, I actually could not make it work. Pls help

**Comment by oehme** [comment]
Please see the [user guide](https://docs.gradle.org/current/userguide/working_with_files.html#sec:file_trees) in file trees.
