### ISSUE TITLE
Only display welcome message on interactive builds

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#5201]
The new welcome message feature is great, but we see it on CI and other places where Gradle is non-interactive.

**Comment by blindpirate** [comment]
@eriwen I think this is reasonable. WDYT?

**Comment by vpavic** [comment]
Could this be reopened?

I'm aware of #12550 being still open, but IMO even with some kind of welcome message opt-out being supported, Gradle as a tool should be smart enough to figure out it runs in an environment where welcome message quite likely isn't of value.

For example, I believe that the presence of one of the following environment variables could be considered a strong enough indicator that welcome message can be disabled:

- `CI=true`
- `TERM=dumb`
