### ISSUE TITLE
New test exception format that uses `Throwable.printStackTrace()`

### ISSUE THREAD

**Issue by ghost** [gradle/gradle#5203]
Hi,

I have custom exception classes that override `Throwable.printStackTrace()` to provide additional domain specific information in the stack trace, this works nicely in Maven and IDEs, when the tests fail, I can see the additional info, but the current Gradle exception formats (via test.testLogging.exceptionFormat, short/full) appear to not use `Throwable.printStackTrace()`, so it would be nice to have this addition for testing reports.

Thanks.

**Comment by marcphilipp** [comment]
The reason Gradle doesn't use `printStackTrace()` is probably because of filtering. While we could probably introduce a new format (e.g. unfiltered) I'm not convinced overriding `printStackTrace()` is the way to go to report additional information.

**Comment by laec** [comment]
One thing I'm working on is to add source code snippets to the stack trace for test failures: https://gitlab.com/lae/java-stack-source

```java
org.junit.ComparisonFailure: expected:<H[ello]!> but was:<H[i]!>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at example.HelloTest.hello(HelloTest.java:16)

       14      @Test
       15      public void hello() {
    -> 16          assertEquals("Hello!", greet());
       17      }

    ...

```

I couldn't find a better way than overriding `Throwable.printStackTrace` that would work across IDEs, build tools, and testing libraries.
