### ISSUE TITLE
Android Studio Gradle (Ubuntu)

### ISSUE THREAD

**Issue by sherbaev** [gradle/gradle#5204]
I am using Android Studio on Ubuntu .  Every time , after Gradle finish its work , the gradle process is not removing itself . As a consequetly , laptop's memory  (RAM) is being fulled with gradle processes .
![screenshot from 2018-04-28 09-45-31](https://user-images.githubusercontent.com/31945873/39392182-f598fa4a-4aca-11e8-80f6-df5170e6d1cd.png)
  How it can be fixed ?

**Comment by marcphilipp** [comment]
That's probably the Gradle daemon but there should not be more than one, or are you working with different Gradle/Java versions, e.g. in different projects, at the same time?

**Comment by sherbaev** [comment]
I am using Java 9 and Gradle version 4.4

**Comment by marcphilipp** [comment]
Have verified that all of these are indeed Gradle processes?

**Comment by sherbaev** [comment]
I do not know .  How it can be verified ?

**Comment by marcphilipp** [comment]
Can you access the full command for each process through your UI? Otherwise, try `ps aux` from a terminal.

**Comment by Axrorxoja** [comment]
@marcphilipp ,I also have the same problem, every time the gradle creates new daemon but it does not die and it stays on ram because of this for a day 3-4 times my ram is overflowing
I tested 4.4.4.5.4.6.4.6 gradle versions but ... :(

android studio: 3.2.1
gradle: 4.4
ubuntu: 16.04 x64
ram: 16

**Comment by oehme** [comment]
As Marc said, we'll need the full command line of those processes to see how they differ. Gradle definitely shouldn't start a new daemon unless your java home or important jvm args change.

**Comment by marcphilipp** [comment]
@sherbaev @Axrorxoja Does #5253 help?

**Comment by sherbaev** [comment]
@marcphilipp Nope ,It does not work for me .  It is still creating another daemon .

**Comment by eriwen** [comment]
Use of `gradle --status` can tell us more about Daemon processes, and `--info` logging may be helpful here as it often logs why a Daemon could not be reused.

**Comment by LiuJQ** [comment]
help, I'm suffering the same problem.
```script
./gradlew clean :app:assembleDebug
```
Once I run this command in terminal, Java process will increase huge memory, even 4g per one sometimes. 
> System: Ubuntu 18.04 LTS
Java: 1.8.0_191
Gradle: 5.0-milestone-1
