### ISSUE TITLE
Why do javadoc tasks of depending projects depend on each other?

### ISSUE THREAD

**Issue by larsgrefer** [gradle/gradle#5207]
Given this simple java multi-module project: https://github.com/larsgrefer/gradle-javadoc-example

When executing `./gradlew b:javadoc --console=plain` I can see that the task `a:javadoc` is executed, too. Why is this so?

`b:javadoc` seems to have no inputs which are generated by `a:javadoc`

**Comment by oesolutions** [comment]
Unfortunately I've been unable to work out why this is needed, but in case it helps you or someone else;

The dependency is created between the two tasks [here](https://github.com/gradle/gradle/blob/834632674ca29b6fd190857947338b2b54a9bb62/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L298). The javadoc tasks are configured to depend on the javadoc tasks of any project dependencies.

**Comment by oehme** [comment]
This seems to have been there since the beginning of time. I don't see why it's necessary either. You could look into the git history or just remove it and see if any tests break. A PR would be welcome.

**Comment by larsgrefer** [comment]
I've had a look at the git history, but that didn't help.

I'll provide a PR which removes this.

**Comment by larsgrefer** [comment]
@oehme Seems like all tests are running fine
