### ISSUE TITLE
Add SHA256 link to download pages

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#5211]
It would be very helpful to have a link to the SHA256 for each download. This will make it easier to add that value to the gradle/wrapper/gradle-wrapper.properties file.

**Comment by marcphilipp** [comment]
Which page are you referring to? https://gradle.org/next-steps/?version=4.7&format=bin has a SHA256 download link.

**Comment by baron1405** [comment]
* https://gradle.org/install/ manual install section
* https://gradle.org/releases/
