### ISSUE TITLE
Publishing to S3 Maven: Give bucket owner full control over published files 

### ISSUE THREAD

**Issue by klesniewski** [gradle/gradle#5233]
### Expected Behavior
When publishing artifacts to S3-backed Maven repository, I expect bucket owner (account that owns the bucket) to have full control over the published files, so that the bucket owner can grant read access to the files.

### Current Behavior
The behavior is as expected only if the IAM user/role used to publish artifact belongs to the same account, that owns the bucket. However, if the publishing IAM user/role belongs to another account, the bucket owner by default will not have permissions to read the files. In order for bucket owner to grant read access to the files, the publishing IAM user/role has to grant bucket owner permissions to the published files. For more details, see [Bucket Owner Granting Its Users Permissions to Objects It Does Not Own](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example3.html).

### Proposed change
When uploading artifacts To S3-backed Maven repository, owner of the bucket should always be granted full access. Since the [MavenArtifactRepository](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.repositories.MavenArtifactRepository.html) does not seem to provide any way to configure the behavior or does not provide any point, where the configuration could be easily introduced, I propose to change the behavior without option for configuration.

In terms of functionality this should not be a breaking change, as with that modification more principals (bucket owner and object owner) have access to the objects. In terms of security this could be a breaking change, but I have hard time to imagine a use case where the S3 Maven bucket owner should have less permissions then the object owner.

The change can be implemented by adding:

    putObjectRequest.setCannedAcl(CannedAccessControlList.BucketOwnerFullControl)

as line 140 to [S3Client](https://github.com/gradle/gradle/blob/7283def6e4c9773ed92340e57ae5c2033b783c05/subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3Client.java#L142).

### Context
To separate our environments we are using multiple AWS accounts. We also have a root account, where IAM users for employees are defined, so that we can manage users in a single place. The users can access other accounts by assuming roles. The S3 bucket is provisioned on other account than IAM users.

in one account (and can assume roles to control other accounts), while S3 bucket hosting Maven repository is owned by another account. The only other alternative solution I can think of is to migrate the S3 bucket to be owned by the same account where the IAM users are defined.

**Comment by eriwen** [comment]
@klesniewski Thanks for reporting and probably tracking down how to fix. Would you be willing to contribute this in the form of a pull request?

**Comment by klesniewski** [comment]
Sure, I will try to make some time during the weekend.

**Comment by marcphilipp** [comment]
Resolved by #5329.
