### ISSUE TITLE
Adding the new entry of <classpathentry kind="output" path="bin/default"/> to the .classpath file causes Tomcat Server not able to start in Eclipse

### ISSUE THREAD

**Issue by faiyat** [gradle/gradle#5237]
### Expected Behavior
We have recently upgraded from Gradle 4.2 to 4.51.  Before the upgrade, we were able to import Eclipse projects to Eclipse or Gradle project using Buildship, and start tomcat service in Eclipse without issue. 

### Current Behavior
Currently importing of both types of projects still works, but Tomcat service cannot be started any more with error of "org.eclipse.core.runtime.CoreException: The archive: /<abc>/bin/default which is referenced by the classpath, does not exist.", where <abc> is one of the projects' name.  And indeed we only see /<abc>/bin folder but not /<abc>/bin/default in the workspace.  To workaround this problem, we have to delete this new entry in .classpath of every projects that required to be built to be able to start Tomcat.

### Context
We need to start Tomcat server in Eclipse as part of our development process.  With the new entry in the .classpath file, '<classpathentry kind="output" path="bin/default"/>', which was introduced in Gradle 4.4, generated by Gradle eclipse task, we cannot start Tomcat without removing 'default' from this entry in every projects.

### Steps to Reproduce (for bugs)
1. Make sure Gradle version is 4.4+ (We are using 4.5.1)
2. Run ./gradlew cleanEclipse eclipse to generate .classpath file.  Verify an entry of "<classpathentry kind="output" path="bin/default"/>" is presented in the file.
3. Go to Eclipse and import Gradle/Eclipse projects.  Start Tomcat from Eclipse.  You will see "org.eclipse.core.runtime.CoreException: The archive: /<abc>/bin/default which is referenced by the classpath, does not exist." in the error.log, and tomcat is not able to start.

### Your Environment
Gradle 4.5.1
Eclipse Oxygen
Eclipse Tomcat plugin 9.1.2
Apache-Tomcat 7.0.45

**Comment by oehme** [comment]
This is the default output folder, which is only used for sources that have no more specific output (e.g. `bin/main` for main code, `bin/test` for test code). So it is normal that this folder might be empty/non-existent. I'd consider it a bug in the tomcat plugin that it can't deal with that. Could you please open a bug there?

As a workaround you could tell Gradle to create the folder for you
```
eclipseClasspath.doLast {
  file("bin/default").mkdirs()
}
```

**Comment by oehme** [comment]
Every .classpath file has a default output directory. This directory may sometimes not exist. This has nothing to do with Gradle.

**Comment by faiyat** [comment]
This default folder is 'bin', but not bin/default.  As you suggested, the workaround solve the problem for now.  So we are not blocked.  But this bin/default is introduced by Gradle.

**Comment by oehme** [comment]
It can't be /bin if you also have /bin/main etc. But Eclipse requires you to always have a default even if it is unused, so there's nothing we can do about that. Plugins need to deal with that default entry.
