### ISSUE TITLE
rootProject.name in settings.gradle is ignored when using command line option --build-file

### ISSUE THREAD

**Issue by janjoerke** [gradle/gradle#5240]
### Expected Behavior

It should be possible to set the rootProject name, even if using a different buildscript.

### Current Behavior

When using the command line option --build-file to spcify an alternative buildscript the settings.gradle file is used, but setting the rootproject name with
`rootProject.name = 'Test'`
within settings.gradle is ignored.

### Steps to Reproduce (for bugs)

[rootProjectNameBug.zip](https://github.com/gradle/gradle/files/1970197/rootProjectNameBug.zip)
Unpack zip and call 
`gradlew projects -b test.gradle`

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/a2g36fuxieezc/

**Comment by oehme** [comment]
This is expected, the `-b` option ignores the settings file and treats it as a single-project build. 

See https://github.com/gradle/gradle/issues/3227 - we are considering to remove `-b` and `-c`
