### ISSUE TITLE
Fix gradle init when there is a pom and the --dsl kotlin is set

### ISSUE THREAD

**Issue by alexandrenavarro** [gradle/gradle#5241]
Fix gradle init when there is a pom and the --dsl kotlin is set

### Expected Behavior
When you do a gradle init --dsl kotlin on a project where there is a pom.xml, it should generate a gradle.build.kts with gradle-dsl instead of gradle.build with groovy dsl.

**Comment by eriwen** [comment]
@eskatos is this easy or really difficult to implement? I suspect the latter, in which case I assume we should tackle this post Kotlin DSL 1.0. Do you have any info here?

**Comment by eskatos** [comment]
It's definitely more involved than the regular init templates but nothing impossible. It's not lined up for Kotlin DSL 1.0 though. A PR from the community would be very welcome.

But, what is also reported above is that the `--dsl` option is silently ignored. We should fail saying that generating Kotlin DSL scripts from a Maven build isn't supported instead.

**Comment by eskatos** [comment]
https://github.com/gradle/gradle/issues/3493 is the original issue about supporting conversion of Maven builds to Gradle Kotlin DSL.

I just opened https://github.com/gradle/gradle/pull/5331 to at least fail with a reasonable error message until this is implemented.

Closing this one as duplicate.
