### ISSUE TITLE
dependency substitution in composite builds resolves to build/classes folder instead of jar

### ISSUE THREAD

**Issue by tjanu** [gradle/gradle#5247]
### Expected Behavior

When substituting a dependency in a composite build, the dependency should be satisfied with the built jar file at all times so e.g. also resources from the dependency can be loaded during, for example, code generation steps.

### Current Behavior

When using a code generation plugin (here: org.unbroken-dome.xjc) in two projects, one depending on the other, and using dependency substitution in a composite build the resources of the dependency cannot be resolves as the dependency resolves to $dependency/build/classes directory instead of the jar file.

I could not reproduce this without using a code generation plugin (i.e. simply doing a getClass().getClassLoader().getResource("path/to/resource/in/dependency") in a class of the dependent plugin works when doing ./gradlew run).

### Context

I'm trying to use the org.unbroken-dome.xjc plugin for XML Schema to Java code generation in multiple dependent projects (to allow for schema and code sharing). With this, it is impossible to use a composite build for this.

### Steps to Reproduce (for bugs)

Github project with a minimal example at: [https://github.com/tjanu/gradle-jaxb-composite-example](https://github.com/tjanu/gradle-jaxb-composite-example)
Some notes:
This set of instructions works:
git clone...
(cd dependency; ./gradlew build)
(cd dependent; ./gradlew build)

This set of instructions does not work:
git clone...
(cd composite; ./gradlew build)

The "dependent" project includes it's own checkout of the current version of the xjc plugin where I just added more logging to see where the dependency resolves to (see with e.g. (cd composite; ./gradlew build -d | grep -A 15 "Resolving URI").

I would have expected both ways to work equally.

Note that having an uploadArchives or publishing configuration in dependency does not change anything regarding this behaviour (as hinted at by the docs that "projects declaring uploadArchives should work out of the box in a composite build").

### Your Environment

Tried on Ubuntu 17.10 with gradle 4.7 (wrapper included in example) and current openjdk8

**Comment by oehme** [comment]
Your task is using the `compileClasspath` which is only meant for compilation. Compilation does not need resources. You can use the `runtimeClasspath` instead or even better define your own configuration specific to JAXB.
