### ISSUE TITLE
Print daemon's JAVA_HOME and JVM_ARGS  in `gradle --status` output.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gradle/gradle#5253]
There is a common issue when you use Gradle from Android Studio and Terminal and end up using two Gradle daemons, one is spawned by `gradlew` from Terminal and another one is spawned by IDE.

This happens because Android Studio by default uses embedded JDK instead of system one thus Gradle can't reuse daemons:

(`File` → `Project Structure` → `SDK Location` → `JDK Location`)

<img width="406" alt="screen shot 2018-05-03 at 5 19 11 pm" src="https://user-images.githubusercontent.com/967132/39608549-1d87feea-4ef7-11e8-8fad-b0af7f8be061.png">

(IntelliJ doesn't seem to do that btw, I might need to create an issue in Android Studio bug tracker)

It obviously creates all sorts of performance problems, but unfortunately Gradle doesn't make it easy to diagnose and fix.

When Gradle spawns an additional daemon it outputs following message:

```console
Starting a Gradle Daemon, x incompatible Daemons could not be reused, 
use --status for details
```

But `gradle --status` output is not actionable:

```console
$ ./gradlew --status
  PID STATUS   INFO
69136 IDLE     4.6
69147 IDLE     4.6
```

I had to dig into Gradle sources to figure why it might spawn an additional daemon when there is already one running IDLE daemon of the same Gradle version, in my case JVM_ARGS were same, but Android Studio was using own `JAVA_HOME`.

I think it's reasonable to print each daemon's `JAVA_HOME` and `JVM_ARGS` to make output actionable and easier to fix.

I have some code for that, but as suggested in [`CONTRIBUTING.md`](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md) I'm opening an issue first :)

What do you think about it?

It's somewhat related to #2660.

**Comment by oehme** [comment]
I think that's a great idea, a PR would be very welcome.

**Comment by nateridderman** [comment]
This seems like a small change that would be very helpful for Android developers.
