### ISSUE TITLE
How to get buildType/flavorDimensions on another gradle file. 

### ISSUE THREAD

**Issue by AnkitSinhal** [gradle/gradle#5260]
Below are the codes which I am trying to get the **buildType** of AndroidStudio project.
 
`project.hasProperty('buildType')`
or 
`project.getProperties().get('buildType')`

Both of above lines return null values. So how can I get the project **buildType** in another gradle file (like sonar.gradle or jacoco.gradle).

Also from AndroidStudio 3.0 and above supports "**flavorDimensions**" property so how can I get the **buildVarient** in another gradle file?

**Comment by oehme** [comment]
The extension is called `android.buildTypes`, not `buildType`.
