### ISSUE TITLE
Gradle Plugin for Cloud Foundry?

### ISSUE THREAD

**Issue by SpamhaterAlex** [gradle/gradle#5265]
Hi community, 

I want to ask, if somebody can recommend a gradle plugin for cloud foundry? 
It shall be able to do this command: 
`cf push APP_NAME --docker-image [REGISTRY_HOST:PORT/]IMAGE[:TAG] [--docker-username USERNAME]`

I would be happy, if you can give me some hints. 

Thank you in advance

**Comment by oehme** [comment]
Please use the [Gradle forum](https://discuss.gradle.org/) for questions. The issue tracker is only for bugs and feature requests for Gradle core.
