### ISSUE TITLE
Help popular annotation processors adopt incremental processing

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#5277]
Please submit PRs to update the list of annotation processors that support incremental annotation processing:

https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/java_plugin.adoc#state-of-support-in-popular-annotation-processors

**Comment by dimsuz** [comment]
Toothpick: [Open issue](https://github.com/stephanenicolas/toothpick/issues/290)

**Comment by Javernaut** [comment]
Realm: [Open issue](https://github.com/realm/realm-java/issues/5906)

**Comment by TWiStErRob** [comment]
https://github.com/johncarl81/parceler
https://github.com/Raizlabs/DBFlow

**Comment by technoir3** [comment]
Glide: [Open issue](https://github.com/bumptech/glide/issues/3072)

**Comment by simtel12** [comment]
In addition to Room's compiler, mentioned by @TWiStErRob, Lifecycle has a compiler too
https://developer.android.com/topic/libraries/architecture/lifecycle (android.arch.lifecycle:compiler)

LoganSquare: https://github.com/bluelinelabs/LoganSquare
AutoValue extensions: rharter/auto-value-gson#179, rharter/auto-value-parcel#131

**Comment by masc3d** [comment]
Requery: [Open issue](https://github.com/requery/requery/issues/773)
Parceler: [Open issue](https://github.com/johncarl81/parceler/issues/343)

**Comment by cckroets** [comment]
GreenRobot's EventBus: [Open issue](https://github.com/greenrobot/EventBus/issues/528)

**Comment by pjakubczyk** [comment]
@oehme  Re Glide:
Linked ticked is Closed
please use https://github.com/bumptech/glide/issues/2983

**Comment by ngattusohw** [comment]
@oehme Hi -- I am currently having this issue where I want to enabling compile avoidance for my project, but I am using the gradle hibernate ORM plugin with annotations, and it recompiles my entire project everytime (takes 15+ minutes to build) .. wondering if anyone could help me out. I am unsure if the hibernate ORM plugin supports compile avoidance or not, as I couldn't find it in their documentation 
 found here ... http://docs.jboss.org/hibernate/orm/5.1/userguide/html_single/Hibernate_User_Guide.html#BytecodeEnhancement-enhancement-gradle

Thanks!

**Comment by jjlueck-tock** [comment]
I am also interested in where Hibernate is with moving over to an annotation processor jar that will inform the gradle incremental compilation process. I haven't found them on any list of projects that are in the works for patching. 

Think they'll accept a community-driven PR over at https://github.com/hibernate/hibernate-orm/pulls
?

**Comment by oehme** [comment]
@jjlueck-tock @ngattusohw As far as I can see, Hibernate doesn't do annotation processing, but post-processes the classes after compilation. I don't know why that would cause compilation to rerun. A reproducible example project would probably help them. How about you open an issue for them and ask them to improve the situation?

**Comment by tprochazka** [comment]
I asked Google team about DataBinding support
https://issuetracker.google.com/issues/110061530
Sadly it is planned for 3.3

**Comment by masc3d** [comment]
@tprochazka it can be mitigated by using instant run, except if you `<include>` more than one databinding layout, then it's triggering https://issuetracker.google.com/issues/79362720

**Comment by ngattusohw** [comment]
I just noticed this in my build.gradle output... "All input files are considered out-of-date for incremental task ':Web:compileJava'." .. where my build.gradle compileJava looks like this
compileJava {
	doFirst {
		apply plugin: 'org.hibernate.orm'

		hibernate {
			enhance {
				enableLazyInitialization= true
				enableDirtyTracking = true
				enableAssociationManagement = true
			}
		}
	}
}

@oehme Any direction appreciated, thanks

**Comment by oehme** [comment]
As mentioned before, this is not annotation processing related. Hibernate uses bytecode enhancement. Please file a bug for their plugin.

**Comment by ngattusohw** [comment]
@oehme okay thank you. Sorry for bothering and thank you for your responsiveness!

**Comment by jnehlmeier** [comment]
EclipseLink: [Open Issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=535985)

**Comment by johncarl81** [comment]
Parceler: [Supported since 1.1.11](https://github.com/johncarl81/parceler/releases/tag/parceler-project-1.1.11)

**Comment by khaidinh** [comment]
Immutables: https://immutables.github.io

**Comment by farrault** [comment]
Hi @oehme,
FYI : Lombok 1.16.22 and 1.8.0 fail with Gradle 4.8 in incremental mode : see https://github.com/rzwitserloot/lombok/issues/1716

It seems to be corrected but not released yet.

**Comment by oehme** [comment]
I see, they were a little too closely coupled to the Filer class hierarchy. The change looks good, much more robust. I pinged them for a release.

**Comment by oehme** [comment]
@khaidinh Can you please open an issue for immutables that I can reference here?

**Comment by betorcs** [comment]
PermissionsDispatcher: [Open issue](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/473)

**Comment by khaidinh** [comment]
@oehme 

https://github.com/immutables/immutables/issues/804

Thanks!

**Comment by bingranl** [comment]
Should we add Android Room Persistence Library here?

**Comment by simtel12** [comment]
Does kapt support annotation processors that are incremental, or would adding an incremental processor via kapt still result in a full compile?

**Comment by tinsukE** [comment]
@simtel12 I don't think KAPT supports it yet, check out this issue, which has been upvoted by the likes of Jake Wharton (or some user with his name):
https://youtrack.jetbrains.com/issue/KT-23880

**Comment by autonomousapps** [comment]
@matejdro that seems correct, but they haven't had a release since August 7. Maybe we can encourage them to release sooner than later? cc @oehme

**Comment by matejdro** [comment]
What is going on with the Room? I know it says that it is unlikely to get incremental, but unlike every single other item on the list, it does not have an issue open on their issue tracker. Instead it just links to the Room docs page.

**Comment by basmastr** [comment]
Created an issue for [querydsl ](https://github.com/querydsl/querydsl/issues/2380)

**Comment by davidburstromspotify** [comment]
com.google.auto.factory.processor.AutoFactoryProcessor in com.google.auto.factory:auto-factory:1.0-beta6 also seems to be non-incremental.

**Comment by davidburstromspotify** [comment]
Opened https://github.com/google/auto/issues/679 on AutoFactory

**Comment by gunnarmorling** [comment]
Regarding Hibernate, there are two annotation processors:

* The Hibernate ORM AP for generating type-safe meta-models (this is unrelated to entity enhancement as dicussed above, but creates literal types for referencing entity properties in a safe way when using the Criteria API)
* The Hibernate Validator API for checking correct placement of Bean Validation constraints (filed [HV-1665](https://hibernate.atlassian.net/browse/HV-1665) for this)

**Comment by hotchemi** [comment]
As for PermissionsDispatcher PR is already merged and we're gonna release next week(thank you so much for listing!):D
https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/473

**Comment by stephanenicolas** [comment]
@oehme can you please add:
* Dart and Henson: [since version 3.1.0](https://github.com/f2prateek/dart/releases/tag/3.1.0)

we just released it and we are very proud to have added incremental annotation support. Thx for all your work on this.

**Comment by WonderCsabo** [comment]
@oehme i opened a ticket in AndroidAnnotations.

https://github.com/androidannotations/androidannotations/issues/2193

Can you add it to the list?

**Comment by oehme** [comment]
Kapt is in progress, I know because I'm getting plenty of questions about it. Please stay tuned.

**Comment by stephanenicolas** [comment]
Thx @oehme for the answer and the change to Dart and Henson. 

I got another question for you: 
The release of android gradle plugin 3.3.0 states that incremental annotation processing is not compatible with gradle 5.1 and higher: 
https://developer.android.com/studio/releases/gradle-plugin#new_features
(The first note with a blue star)

What does it mean ? That the support for incremental annotation processing is discontinued from gradle after gradle 5.1 ? Or that the android plugin has to catchup because things changed or that the support will be restored from Gradle. This sentence is a bit scary..

**Comment by TWiStErRob** [comment]
@stephanenicolas they fixed it, if you open #8194, my reading is this:
 * 5.0 incremental
 * 5.1 non-incremental (#8194)
 * 5.1.1 incremental

**Comment by stephanenicolas** [comment]
Hopefully someone from Google can make the note more clear.

Thx !

**Comment by yanzhenjie** [comment]
AndServer: [Open issue](https://github.com/yanzhenjie/AndServer/issues/152)

**Comment by harliedharma** [comment]
Litho: [Open issue](https://github.com/facebook/litho/issues/482)

**Comment by IvanShafran** [comment]
Moxy: [Open issue](https://github.com/Arello-Mobile/Moxy/issues/240)

**Comment by stephanenicolas** [comment]
@oehme we're glad to announce that ToothPick 2 is released with incap support !
https://github.com/stephanenicolas/toothpick/pull/320

**Comment by stephanenicolas** [comment]
@oehme the butterknife PR will probably never get merged. The main author is not very supportive of the idea. So, we had to fork it to enable incremental annotation processing.

We're happy to release butterfork : https://github.com/stephanenicolas/butterknife
Hopefully we can maintain the fork working as new versions of butterknife are released.

**Comment by hungvietnguyen** [comment]
@oehme Could you add Auto Service to the list of supported incremental APs (https://github.com/google/auto/pull/667)? And update the status of Data Binding also (https://issuetracker.google.com/110061530#comment28)? :) Thanks!

**Comment by hungvietnguyen** [comment]
@oehme Looks like Glide has just become incremental too: https://github.com/bumptech/glide/issues/2983

**Comment by oehme** [comment]
Let me know when there is a release, so I can link that above :)

**Comment by tprochazka** [comment]
Databinding has already a version with experimental support of the incremental compilation
https://issuetracker.google.com/issues/110061530#comment28

**Comment by oehme** [comment]
Databinding is already checked off above.

**Comment by tprochazka** [comment]
Do you have anybody some new information about Room incremental support? It is still valid this ' Unlikely to be incremental in its default mode, as it generates files using java.io'? And it is an explanation from somebody from google team? There is no public issue for it?

**Comment by technoir42** [comment]
Glide 4.9.0 was released with support for incremental AP https://github.com/bumptech/glide/releases/tag/v4.9.0

**Comment by autonomousapps** [comment]
Kotlin 1.3.30 will support incremental annotation processing with kapt! https://youtrack.jetbrains.com/issue/KT-23880

It requires opting in with `kapt.incremental.apt=true` in `gradle.properties`.

**Comment by kakai248** [comment]
Epoxy: [Open issue](https://github.com/airbnb/epoxy/issues/423)

**Comment by hungvietnguyen** [comment]
@oehme, @big-guy: We are working on making Room and Lifecycle incremental. Could you please update the list above and the user guide with links to track this work:

- Room: https://issuetracker.google.com/issues/129112888
- Lifecycle: https://issuetracker.google.com/issues/129115778

**Comment by isker** [comment]
@big-guy some of the links in that table 404.  For example: https://developer.android.com/topic/libraries/architecture/room)

**Comment by big-guy** [comment]
Thanks @isker - I've fixed it for the next nightly build

**Comment by markchristopherng** [comment]
@oehme 

Hi Stephen, the engineers at airBnb don't use gradle and they have mentioned this is not a priority for them however they have 2 very popular android frameworks that don't support incremental annotation processing. Judging by the comment in epoxy issue its sounds like epoxy could involve a bit of work to support incremental annotation processing however on the other hand the airbnb engineer also mentions that deeplinkDispatch framework might not need any code changes at all. Are you are able to look at the deeplinkDispatch framework and possibly do a PR if it is a very easy fix.

airbnb deeplinkDispatch - https://github.com/airbnb/DeepLinkDispatch/issues/247
airbnb epoxy - https://github.com/airbnb/epoxy/issues/423

**Comment by oehme** [comment]
Sorry, I won't have time to look into that. Maybe someone else following this thread would be interested in doing so.

**Comment by graemerocher** [comment]
@oehme I have started a PR for Micronaut with some changes to support this https://github.com/micronaut-projects/micronaut-core/pull/2071

However I could do with some help to verify the correctness of this change and how it relates to what Micronaut does.

**Comment by simtel12** [comment]
@oehme Just FYI, it looks like Room has added support in version 2.2.0 - hidden behind a flag.  The [issuetracker ticket](https://issuetracker.google.com/issues/112110217) has more info.

```Room 2.2.0 will be an incremental annotation processing when enabled via the option 'room.incremental = true'```

**Comment by ColtonIdle** [comment]
> Please submit PRs to update the list of annotation processors that support incremental annotation processing:
> 
> https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/java_plugin.adoc#state-of-support-in-popular-annotation-processors

Updated url: https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing
