### ISSUE TITLE
Document how to publish a Maven BOM using the Maven Publish Plugin

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5292]
Publishing a BOM is an important use case for libraries that publish multiple artifacts and want to ease dependency management for their users and help them to avoid using incompatible versions.

This is a follow-up on #4941.

**Comment by melix** [comment]
Let's defer this a bit: while there are ways to publish a BOM today, this is not the way we want to model it. In particular we want to have a "platform plugin" which responsibility would be to publish a BOM when targetting Maven repositories.

**Comment by marcphilipp** [comment]
Is the "platform plugin" on the roadmap? I was wondering whether we should document the `javaLibraryPlatform` component now and mark it "experimental".

**Comment by melix** [comment]
It is on the roadmap, and I don't think we should release 5.0 without it. A "BOM" doesn't represent a `javaLibrary`, so `javaLibraryPlatform` is already too confusing to me.

**Comment by marcphilipp** [comment]
Ok, if you don't mind and I find the time, I might just create a short sample and add it to this issue's description for our most courageous users. 😉

**Comment by ljacomet** [comment]
Superseded by #7945

**Comment by ljacomet** [comment]
And for completeness, here is a [working example](https://github.com/gradle/gradle/issues/7909#issuecomment-444070805) with Gradle 5.0
