### ISSUE TITLE
Document how to publish a dynamic set of artifacts using the Ivy/Maven Publish Plugins

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5293]
Document how to publish a [dynamic set of artifacts](https://discuss.gradle.org/t/maven-publication-closure-is-evaluated-too-early/19911/6) in the User Guide.

This is a follow-up on #4941.

**Comment by jjohannes** [comment]
It is now possible and recommended to add artifacts through components. That is you add them to `configuration.outgoing` or to a variant of it `configuration.outgoing.variants` - https://docs.gradle.org/release-nightly/userguide/publishing_customization.html
