### ISSUE TITLE
Cygwin gradlew: arguments cannot have double quotes

### ISSUE THREAD

**Issue by gerhardol** [gradle/gradle#5300]
The correction for #865 is insufficient for Cygwin. The arguments are trashed in the Cygwin specific loop.
Patch gradlew to go into the Cygwin argument cleanup, comment out the 'cygpath' commands.

### Expected Behavior

For a description and testcase, see #865 but run it in Cygwin

### Current Behavior

See #865 

### Context

This makes it difficult to pass arguments with double quotes to gradlew

### Steps to Reproduce (for bugs)

See #865 

### Your Environment

 Gradle Version: 4.7
Last worked correctly in: unknown
Operating System: Win7, CYGWIN_NT-6.1 pc 2.8.2(0.313/5/3) 2017-07-12 10:58 x86_64 Cygwin
JVM version: Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

**Comment by ov7a** [comment]
Fixed in 6.9 (no longer reproducible in later versions)
