### ISSUE TITLE
Introduce Publishing chapter in User Guide

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5311]
As discussed and proposed in https://github.com/gradle/gradle/issues/4939#issuecomment-386595121, the User Guide should feature a chapter on Publishing that briefly introduces the new publishing plugins and mentions the original, soon to be deprecated mechanism with links to the plugin reference chapters (Ivy Publish, Maven Publish, Signing, Old Maven).

**Comment by marcphilipp** [comment]
@pledbrook I've assigned this to you and the 4.9 RC 1 milestone for now. Please figure out how to prioritize this with all the other things you have on your plate and update it as you see fit. Thanks!

**Comment by oehme** [comment]
This has been merged.
