### ISSUE TITLE
Dependencies task output for a composite build doesn't show expected project name

### ISSUE THREAD

**Issue by chali** [gradle/gradle#5343]
I have a project `consumer` which is including another project `included` as a composite. Project `included` is in a directory named `included` but in `settings.gradle` I have `rootProject.name='included-project'`. `included` project has two modules `a` and `b`. `b` depends on `a`. My `consumer` project depends on `b`.

When I include project `included` in settings.gradle of `consumer` and run following task `./gradlew dependencies --configuration compile` I see different results for Gradle 4.7 and Gradle 4.8 Nightly.

### Expected Behavior
With Gradle 4.7 I see this output which is what I expect.

    compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
    \--- example:b:1.0.0 -> project :included-project:b
         \--- project :included-project:a

### Current Behavior
With Gradle 4.8. Project `a` is reported differently.

    compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
    \--- example:b:1.0.0 -> project :included-project:b
         \--- project :included:a

### Context
From the output, it looks like the transitive project dependency is reported with directory name instead of `rootProject.name`.

### Steps to Reproduce (for bugs)
Here an example project showing the described situation https://github.com/chali/compositeBuildIssue

**Comment by bigdaz** [comment]
Thanks for reporting. I've confirmed that this is a regression from 4.7.

**Comment by bigdaz** [comment]
@adammurdoch I suspect that this is related to the work you did to improve handling of `BuildIdentifier` in a composite build. Can you please take a look?

**Comment by adammurdoch** [comment]
This is fixed now. The fix will be in 4.8.
