### ISSUE TITLE
classpath used by "gradle run" is different from "gradle idea"

### ISSUE THREAD

**Issue by xaka** [gradle/gradle#5345]
I've got 2 plugins applied: "idea" and "application". 

For long time I've been running and debugging the code via IntelliJ IDEA and had no issues. Recently I decided to give it a shot and run outside of IDE. First step was to leverage gradle's "application" plugin that comes with "run" and other useful tasks.

When I use "run", the code crashes eventually for different reasons caused by ordering of classpath entries. I was expecting both plugins to use the same classpath resolution logic, but it seems it's different and mostly affected by transient dependencies (not explicitly stated in "build.gradle").

Adding those transient dependencies by hand and explicitly placing them in right order helps with this issue, but I don't think it's expected to work this way as it kills developer's experience. 

What happens in theory is (the dependency graph):
```
A
 A.1 (transient)
B
```

leads to (classpath ordering):
```
A -> B -> A.1
```

instead of:
```
A -> A.1 -> B
```

I also tried "distTar" and "distZip" tasks of "application" plugin. Both come out with the same issue.

**Comment by oehme** [comment]
Your application should never depend on classpath ordering. Gradle only guarantees that the ordering is stable across minor releases, but does not guarantee any particular order.

Also, `gradle idea` and `gradle run` use the same resolution engine. But in IDEA you have the additional complexity of different scopes, while on the command line there is one unambiguous classpath. This may explain the differences in execution you are seeing.

**Comment by errodrigues** [comment]
I've many time faces this exact same issue and then amount of hacking needed to solve this is horrible.
Even though I certainly agree with the concept that classpath order shouldn't matter, I am very much convinced that this is wishful thinking. In many real world scenarios, especially when there's legacy stuff in the mix, it is very common to stumble upon weird modules that include fat jars including older versions of libraries that are also being formally imported as a declared dependency.

I find this particularly annoying when building REST applications with Jersey, which has heavy dependencies on HK2 for example. HK2 makes heavy use of reflective resource location and class loading and is very sensitive to classpath. If any other set of HK2 classes from a wrong version is found in the classpath before the actually declared HK2 module, it doesn't work.

Yes, I know there shouldn't be another crazy fat jar file in the classpath competing with HK2, but again... in the real world, s@&#t always happens and they are not always fixable.

Honestly, this is so basic I'm very surprised Gradle claims to be a build tool for Java but doesn't guarantee a topological sort of the dependency graph when generating classpath.

**Comment by oehme** [comment]
No matter which order we choose, some case would always have a problem.

The solution to competing jars is excluding the bad one, not relying on ordering.
