### ISSUE TITLE
on Mac android studio: It is currently in use by another Gradle instance.

### ISSUE THREAD

**Issue by mnnyang** [gradle/gradle#5349]
I tried various methods but could not solve it。
-------
Timeout waiting to lock file hash cache (/project-path/.gradle/4.4/fileHashes). It is currently in use by another Gradle instance.
Owner PID: unknown
Our PID: 1679
Owner Operation: unknown
Our operation: 
Lock file: /project-path/.gradle/4.4/fileHashes/fileHashes.lock
------

**Comment by oehme** [comment]
Please provide the full debug log (by running `gradlew assemble --debug`), otherwise we can't help you diagnose this issue.

**Comment by wuhongsheng** [comment]
Hi, i let you here the same (Or similar) error, how can i solve it?

**Comment by ghale** [comment]
I'm closing this as there is not enough information to follow up.  If you feel there is still an issue to be addressed, please open a new issue.
