### ISSUE TITLE
Gradle Path type is NOT compatible with Java Path interface

### ISSUE THREAD

**Issue by aplatypus** [gradle/gradle#5362]
### Expected Behavior

- Gradle script should respect values that are _`instanceof`_**` java.nio.file.Path`**
- Specifically the type: **`org.gradle.model.Path`** shall be an _`instanceof`_**` java.nio.file.Path`**
- The Gradle `Path` type is hiding the standard Java NIO library _Path_ interface.
   - This kind of name class should be avoided.
   -  If the Gradle path type must be different, I recommend naming it specifically, e.g.: _GradlePath_, to distinguish it from the standard type.

### Current Behavior

-  Java and Groovy variables of type and functions  returning **` java.nio.file.Path`** cause an **`GroovyCastException`** exception in Gradle script
- This prevents perfectly _legitimate_ instructions from working in the build file

```
FAILURE: Build failed with an exception.

* Where:
Build file '...\foundation\build.gradle' line: 105

* What went wrong:
A problem occurred evaluating root project 'foundation'.
> isNotMakeLink...  Failed with exception: GroovyCastException
   > Cannot cast object ...\foundation\common-files' 
        with class 'sun.nio.fs.WindowsPath' 
        to class 'org.gradle.model.Path'
```

### Context

- The original code that raised this error is perfectly acceptable Groovy (or Java) code.
- This creates a symbolic link on to common resoruces

```
    boolean  isMakeLink( 
    {
         :
        try
        {
            Path newLink;
           newLink = java.nio.file.Files.createSymbolicLink( linkPath.toPath(), existingFolder.toPath(), new FileAttribute<?>[0]  );

            rslt = true;
        }
        catch(  Exception ex )
        {
            throw new ProjectConfigurationException( "isMakeLink...  Failed with exception: "+ ex.getClass().getSimpleName(),  ex  );
        return rslt;
    }
```

-  The code actually works once the newLink `Path` is explicitly typed as the correct Java type:
    - use:  **`java.nio.file.Path`**
   - as a workaround
```
         :
            java.nio.file.Path newLink;
           newLink = java.nio.file.Files.createSymbolicLink( linkPath.toPath(), existingFolder.toPath(), new FileAttribute<?>[0]  );
         :
```

### Steps to Reproduce (for bugs)

-  Enter statements shown above

### Your Environment

- Window and Linux command line
- Gradle v4.6

**Comment by oehme** [comment]
Gradle's Path has nothing to do with the file system and can't be changed for a long time to come for backwards compatibility. It will eventually disappear, but until then you'll have to use an explicit import.

I recommend writing imperative login in buildSrc where this problem doesn't exist. Build scripts are for declarative logic.
