### ISSUE TITLE
Allow integration tests from gradle/gradle to be run from the IDE when the build under test performs Java compilation

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#5363]
Given:

1. The Java compile task now outputs a deprecation warning when it discovers annotation processors on the compile classpath that will be implicitly used.
2. The Kotlin embedded compiler happens to include such an annotation processor.
3. When running an integration test from the IDE pretty much every Gradle runtime dependency is visible.
4. Unexpected deprecation messages fail a build when run via the gradle/gradle test fixtures.

Then: whenever an integration test happens to run a build under test that performs Java compilation is run from the IDE, the test fails due to an unexpected deprecation message.

### Expected Behavior

It should be possible to run any integration test from the IDE.

### Current Behavior

Running an integration test that performs Java compilation fails when run from the IDE. Instead, I have to run these tests from the command-line, which is a lot slower.

I haven't looked into why these tests pass from the command-line. I'm assuming that by coincidence the kotlin compiler isn't visible in these cases.

**Comment by oehme** [comment]
Sounds like `gradleApi` exposes too much in embedded mode.

**Comment by adammurdoch** [comment]
This has disappeared for me. Unfortunately I don't know why. I _think_ it happened when I recreated my IDEA project, for an unrelated issue.

**Comment by oehme** [comment]
I also don't see this anymore.
