### ISSUE TITLE
Migrate Gradle core plugins Conventions to Extensions

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#5377]
Groovy and Kotlin DSL handle Conventions differently.
In Groovy scripts, conventions are not namespaced.
In Kotlin scripts, they are and only appear on `project`.

Extensions on the other hand are treated uniformly. They are namespaces on both DSLs and can appear at any level.

Given that the Groovy and Kotlin DSLs will be maintained side by side in the long run and Conventions are going away, all Gradle core plugins should be refactored to move from Conventions to Extensions.

Goals
- simplification effort
- for build authors and plugin authors
   - more predictable DSL
   - reducing cognitive overhead
      - two extension mechanisms
      - two ways to model a DSL

> The fewer conceptual differences there are between the two DSLs, the better
> @adammurdoch 

The most important conventions are `BasePluginConvention`, `JavaPluginConvention`, `ApplicationPluginConvention` and source sets conventions.

**Comment by JLLeitschuh** [comment]
You'll probably also want to help the Jetbrains team migrate the Kotlin plugin as well.
https://github.com/JetBrains/kotlin/blob/ce18c2bf26f5579f47771609c35115903451e71b/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt#L637

**Comment by adammurdoch** [comment]
We'll split this into a few steps. The first will be to migrate the plugins to add project level conventions while leaving the extensions in place for backwards compatibility (https://github.com/gradle/gradle-native/issues/681)

Later, we can:

- migrate the source set level conventions
- update the documentation and guides
- deprecate the extensions and related types
- deprecate the extension mechanism
- and finally remove the deprecated things (no earlier than Gradle 6.0).

**Comment by eskatos** [comment]
I think we still want to do that

**Comment by tudortimi** [comment]
When you're going to migrate the source set level conventions to extensions , will this mean that the DSLs will change? Concretely, will the following still be possible, for example, for the Groovy plugin?

```
sourceSets {
    main {
        groovy {
            // configure Groovy source
        }
    }
}
```

I'm asking because I'm developing some plugins that are conceptually similarly structured like the JVM plugins (core plugin that adds the source set and plugins that extend this source set). I looked at the Groovy plugin code for inspiration on how to implement this, but that uses conventions. I have no idea how to approach this task using extensions.

**Comment by tudortimi** [comment]
Don't we still want this?

**Comment by donat** [comment]
All core plugins are using extensions by default. The convention objects are still kept for backward compatibility reasons. The cleanup work is tracked in https://github.com/gradle/gradle/issues/22050.
