### ISSUE TITLE
Broken link in docs despite looking correct in adoc

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#5379]
### Expected Behavior

Opens https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

### Current Behavior

Opens https://docs.gradle.org/current/userguide/java_plugin.html

### Context

I was just reading the docs, and got confused when navigation took me to the same page having no info on the topic that was promised.

### Steps to Reproduce (for bugs)

Go to https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations
Click link in "please consult the Java Library Plugin"

### Your Environment

I wanted to fix the broken link, but it seems everything is in order:

`[[sec:java_library_separation]]` section was there for 9 months
https://github.com/gradle/gradle/blame/1df3977e78ffdab836dbf043972fa1e0fcd5758b/subprojects/docs/src/docs/userguide/javaLibraryPlugin.adoc#L33

`<<java_library_separation, Java Library Plugin>>` link was added a month ago
https://github.com/gradle/gradle/blame/1df3977e78ffdab836dbf043972fa1e0fcd5758b/subprojects/docs/src/docs/userguide/javaPlugin.adoc#L256

My suspicion is that something may go wrong during adoc to html conversion.

**Comment by eriwen** [comment]
Should be fixed by https://github.com/gradle/gradle/commit/2ba5213ca342f208b82bff957a0d4ca17513d20e

**Comment by eriwen** [comment]
Thank you for reporting @TWiStErRob.

**Comment by TWiStErRob** [comment]
Ah, makes sense :) Thanks.

**Comment by eriwen** [comment]
Yep, I just verified in the nightly docs.
