### ISSUE TITLE
Feature: Add dependency GAV aliases

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#5404]
possible this is already being worked on, but I'd like in my plugins, to be able to write something like

```
        deps.constraints( dch -> {
            dch.create( "com.google.code.findbugs:jsr305" + LATEST ).withAlias("jsr305");
            dch.create( "org.junit.jupiter:junit-jupiter-api:5.+" ).withAlias("junit5");
            dch.create( "org.junit.jupiter:junit-jupiter-engine:5.+" ).withAlias("jupiter");
            dch.create( "org.assertj:assertj-core:3.8+" ).withAlias("assertj");
        } );
```
then in any project which imports my plugin I could write

```
plugins { id("myplugin").version(...) }

dependencies {
    compileOnly( "jsr305" );
    testImplementation("junit5")
    testRuntime("jupiter")
    testImplementation("assertj")
}
```

this would pull in the latest version of jsr305,  junit 5.2.x (both api and runtime), and assertj 3.9.1 (but not 4, or 3.7)

**Comment by melix** [comment]
There are different things bundled in this feature request:

1. being able to recommend dependency versions, which can now be expressed through [dependency constraints](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:dependency_constraints)
2. A short-hand notation to include dependencies

I think 2. shouldn't be implemented, as it belongs to the "old world", where dependencies drive everything. Instead, we should think in terms of modeling software. What you probably want here is to say "I'm building a Spring Boot application", so there should be a Spring Boot plugin which has an extension to configure the application, and applies sensible defaults. This one should add the dependencies transparently. There's no reason why a user should be faced with a low-level concept (dependencies) when it can be modeled through a higher concept (a Spring Boot application).

**Comment by xenoterracide** [comment]
I don't fully agree with you because I'm of the opinion we should know *exactly* what our module depends on an exports. In fact it's one of the reasons I switched to gradle is I felt it was doing that better. However let me try to give a better example than a "Spring Boot Appliction". Also I don't build "Applications" I build libraries and modules and compose them into applications.

I use this module to verify that my equals contracts are implemented correctly

```
    testImplementation("com.jayway.jsonpath:json-path:2.+")
    testImplementation("org.mockito:mockito-core")
    testImplementation("com.google.code.gson:gson")
    testImplementation("org.hamcrest:hamcrest-library")
    testImplementation("com.jcabi:jcabi-matchers:1.+")
    testImplementation("nl.jqno.equalsverifier:equalsverifier:2.+")
```

I'll be honest, I can never remember the group for equalsverifier, or json-path, or jcbabi. Every time I have to add them as a dependency I have to look them up, and then copy and paste. I'd rather be able to write my specific project code in a way my brain can remember.

```
testImplementation("json-path")
testImplementation("equalsverifier")
testImplementation("gson")
testImplementation("jcabi")
```

On to the constraints part, yes, you're right, but so far I haven't seen a way that I could do this for a library, such that my library only expresses minimal dependencies, and shared through say my personal plugin, so that I can share those constraints more easily amongst my libraries. Also I've actually started to avoid Spring Boot Starters, because, for example the other day my tests weren't running in gradle but were in Idea;  I thought, but I configured everything for junit 5 right in my plugin? yes? and I made sure it also enabled junit platform? 'cause that was the problem earlier. I removed junit 4 too, I made sure of that... ... wth... hour later... notice 
https://bitbucket.org/xenoterracide/gradle-plugin-bundle/src/master/src/main/java/com/xenoterracide/gradle/plugin/configurations/JavaLib.java

turned out spring-boot-starter-test (head desk) was used ,that pulls in junit4, and my tests are still configured with junit4... surprise!! you have dependencies on your compile path that you didn't think you had. From what I've seen of the constraints API how would it help me with this problem? I'd then have to copy and paste constraints to exclude junit4 into every library that uses `spring-boot-starter-test`. even more concerning is the other transient dependencies that pulls in, will I know when I get a new transient dependency and then use it? Also what about on non test classpath? maybe things are pulled in I don't need... what if a library is pulled in that's never used, I have to go check that that happens and exclude it? what happens when another one is added in an upgrade, and what if I'm using a `-starter-*:2.+` syntax. Now every release I'd have to go in, and ensure no new accidental unused deps were pulled in, unless of course gradle plans on adding some sort of auto dependency filter to only have the end maven publish result contain deps I actually used, and at the scope I actually need them.

My "authorbundle" plugin is an attempt to deduplicate my code that was copy and pasted around.... this ticket is arguably a continuation of that. I simply don't currently see a way that I can use constraints to write in my plugin, if dep used, then use this version. For further info on how I'm using the plugin, you can check out the following repository, which is a composite root, and will point you to 2 other repositories.

https://bitbucket.org/xenworks/entities/src/master/

**Comment by xenoterracide** [comment]
I'd like to add, not just a memory improvement to give a GAV an alias, but code maintenance improvement. For example over the lifecycle of work project, the GA(V) for javax.persistence will have changed at least 3 times, if not 4.

**Comment by xenoterracide** [comment]
updated ticket to remove discussion of constraints, they *might* partially fit, I'm uncertain. I still want aliases though.

**Comment by xenoterracide** [comment]
last comment, you hyper-focussed on what boot provides, but that only works for a subset of code that boot manages.

**Comment by melix** [comment]
This is covered by https://github.com/gradle/gradle/issues/15352
