### ISSUE TITLE
Plugin Site reports false usage information about Plugin DSL

### ISSUE THREAD

**Issue by madorb** [gradle/gradle#5410]
Every plugin on https://plugins.gradle.org/ contains an "about the new plugin mechanism" footer which states:

> Cannot be used in conjunction with subprojects {}, allprojects {} etc.
> 
> It is not possible to use the familiar pattern of applying a plugin to multiple projects at once using subprojects {} etc. at the moment. There is currently no mechanism for applying a plugin to multiple projects at once. At the moment, each project that requires a plugin must declare so in the plugins {} block in its buildscript.
> 
> Future versions of Gradle will remove this restriction.
> 
> If the current limitations of the new plugin mechanism are problematic for your build, the recommended approach is to use the “traditional” mechanism for the time being.

I've assumed that this was in fact correct for as long as it's been there, but just today I found out that it is not as per: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl

Unless I'm missing something the plugins site documentation has been incorrect since at least gradle 3.0? is it possible to update this text to report more accurate information?

**Comment by big-guy** [comment]
We've deployed a change to the plugin portal to link to the updated documentation so we can keep this in sync with the latest changes in Gradle.
