### ISSUE TITLE
Dependency locking does not work with unique SNAPSHOT modules

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#5413]
When a module is published with unique SNAPSHOT versions, then the dependency lock is written with the timestamped version. However, this lock is not applied correctly to constrain the version when resolving. This means that when a new unique SNAPSHOT is published, resolution with the lock file will fail.

### Expected Behavior
Given a dependency on a SNAPSHOT module published with unique (timestamped) versions, dependency locking should ensure that the same timestamped version is used, irrespective of the setting of `cacheChangingModulesFor`.

### Current Behavior
Dependency locking causes a build failure when a SNAPSHOT module is locked and then a newer version is published.

```
* What went wrong:
Could not resolve all dependencies for configuration ':lockedConf'.
> Dependency lock state for configuration 'lockedConf' is out of date:
    - Did not resolve 'org:unique:1.0-SNAPSHOT:20100101.120001-1' which is part of the lock state
    - Resolved 'org:unique:1.0-SNAPSHOT:20100101.120002-2' which is not part of the lock state
```

### Steps to Reproduce (for bugs)
Ignored test case here:
https://github.com/gradle/gradle/commit/ff08b2b58d0b52f3ce18d5097507e1fc5921f6de

**Comment by ljacomet** [comment]
Given that for Gradle, snapshots are considered as changing versions and not dynamic ones so far, I will do the following changes:
* For SNAPSHOT, lock the -SNAPSHOT version, without timestamp.
* Emit a warning when locking is used and _changing_ dependencies are part of the graph.

**Comment by ljacomet** [comment]
AFAICT locking a unique SNAPSHOT would force us to treat them as dynamic versions and no longer changing ones. While this is indeed a requested change, I believe it is beyond the scope (and timing) of this issue.

**Comment by bigdaz** [comment]
Gradle already supports a dependency on a timestamped version of a SNAPSHOT, and will perform conflict resolution when a dependency on both `1.0-SNAPSHOT` and `1.0-<timestamp>` are present in the graph. So I _think_ we could lock snapshots by adding a constraint on `1.0-<timestamp>`.

**Comment by ljacomet** [comment]
Ok, let me try this then.

**Comment by ljacomet** [comment]
After giving it more thought, supporting of locking unique snapshot version will not be done.

Snapshots are allowed to disappear from repositories. Frequently a repository will only server a limited number of them. And that means that pushing new snapshots could make older ones (potentially locked) disappear.

Since the main goal of dependency locking is reproducible builds this does not seem a good solution anyway.

**Comment by barriosnahuel** [comment]
Hi, I'm facing this problem against a Google official dependency from one build to the next one, do you know something about this particularly dependency?

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':Mercadolibre:debugCompileClasspath'.
> Dependency lock state for configuration 'debugCompileClasspath' is out of date:
    - Did not resolve 'com.google.android.gms:play-services-iid:10.2.6' which is part of the lock state
    - Did not resolve 'com.google.android.gms:play-services-gcm:10.2.6' which is part of the lock state
```

Regards!

**Comment by TWiStErRob** [comment]
> After giving it more thought, supporting of locking unique snapshot version will not be done.

That's unfortunate @ljacomet. I have a feeling that the choice should be given to the users. If they use a repo where the snapshots are preserved for a very long time (e.g. the [public Sonatype SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/main-SNAPSHOT/)), this would be a useful feature, however based on a potential assumption about (some) repositories, you shortcut this decision, making "stable" consumption of SNAPSHOT dependencies [almost impossible](https://github.com/detekt/detekt/issues/5066#issuecomment-1180900461).

**Comment by acecilia** [comment]
Agree, is quiet unfortunate that, when developing a locking mechanism for reproducible builds, it misses the chance of locking the snapshot resolved timestamp - resulting in a non-reproducible build due to the incomplete version information in the lockfile
