### ISSUE TITLE
Gradle 4.8-rc-1 does not allow abbreviations of model rule based tasks

### ISSUE THREAD

**Issue by timyates** [gradle/gradle#5424]
I believe there has been a regression in 4.8-rc-1 WRT using abbreviations of task names from the command line when tasks are added via model rules.

If we take the [basicRuleSourcePlugin documentation sample](https://github.com/gradle/gradle/tree/c2fb47745a7a6daaff9f29fe84dedd425f53467d/subprojects/docs/src/samples/modelRules/basicRuleSourcePlugin), and [update the task name](https://github.com/gradle/gradle/blob/c2fb47745a7a6daaff9f29fe84dedd425f53467d/subprojects/docs/src/samples/modelRules/basicRuleSourcePlugin/build.gradle#L82) so that it can be abbreviated, ie:

```
    tasks.create("sayHelloToUser") {
      doLast {
        println "Hello $p.firstName $p.lastName!"
      }
    }
```

With Gradle 4.7, you can run the abbreviated task name, ie:

```
$ gradle sHTU

> Task :sayHelloToUser
Hello John Smith!

BUILD SUCCESSFUL in 1s
```

With Gradle 4.8-rc-1, this fails

```
$ gradle sHTU

FAILURE: Build failed with an exception.

* What went wrong:
Task 'sHTU' not found in root project 'basic-rule-source-plugin'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by marcphilipp** [comment]
@oehme Could this be related to the model bridging performance improvements in #5185?

**Comment by oehme** [comment]
Most probably yes, I'll take a look.

**Comment by oehme** [comment]
It was caused by a refactoring in the context of lazy task configuration, since we had no coverage for this scenario. PR is here: https://github.com/gradle/gradle/pull/5428
