### ISSUE TITLE
Improved pom support gives unexpected importance to versions of optional dependencies

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#5434]
### Expected Behavior

```groovy
dependencies {
	implementation "org.springframework:spring-beans:5.0.6.RELEASE"
	implementation 'org.yaml:snakeyaml:1.19'
}
```

The optional dependency in `spring-beans` on `snakeyaml` has no effect on the version of `org.yaml:snakeyaml` that is resolved.

### Current Behavior

With improved pom support enabled, the optional dependency in `spring-beans` on `snakeyaml` causes 1.20 of `snakeyaml` to be resolved.

### Context

The current behaviour of improved pom support is problematic from a library publisher's perspective as it can lead to an unintended upgrade of a dependency. Spring Framework provides a concrete example with its SnakeYAML dependency.

Spring Framework supports a range of SnakeYAML versions but compiles and tests against the latest. In 5.0.5, it upgraded from 1.19 to 1.20. When building with Maven or with Gradle without improved pom support enabled, this upgrade has no effect on the dependencies of a consuming project. When using Gradle with improved pom support enabled, this change in Spring Framework 5.0.x (a maintenance or bug fix release) causes the consuming project to start using a new minor version of SnakeYAML.

It's undesirable for an upgrade to a new maintenance release of a library to trigger an upgrade to a new minor release of another dependency. Library publishers make changes such as the one described above with the assumption that their project's Maven metadata will be processed as Maven intends (and as Gradle does without improved pom support enabled). Improved pom support invalidates this assumption which leaves library developers rather stuck. They either have to avoid upgrading the version of optional dependencies in maintenance releases or they have to run the risk of triggering unwanted dependency updates for their users that use Gradle.

### Steps to Reproduce (for bugs)

The problem can be reproduced by resolving the following dependencies with improved pom support enable:

```groovy
dependencies {
	implementation "org.springframework:spring-beans:5.0.5.RELEASE"
	implementation 'org.yaml:snakeyaml:1.19'
}
```

`snakeyaml` 1.20 will be resolved. By contrast if `spring-beans` 5.0.4.RELEASE is used, `snakeyaml` 1.19 will be resolved.

### Your Environment

N/A

**Comment by eriwen** [comment]
@ljacomet Is this a bug or intentional behavior? Achieving the desired behavior here seems to be quite important to the Spring Boot team, so I'd like to advocate that we address this.

**Comment by bigdaz** [comment]
I think this is yet another example of the difference between Maven's "nearest wins" conflict resolution, and the way Gradle considers all incoming edges and tries to find the optimal match.

If my understanding is correct, this behaviour is the same as if the `spring-beans -> snaeyaml` dependency was _not_ optional: Gradle would choose `1.20`, whereas Maven would choose `1.19`.

**Comment by wilkinsona** [comment]
> If my understanding is correct, this behaviour is the same as if the `spring-beans -> snaeyaml` dependency was _not_ optional: Gradle would choose `1.20`, whereas Maven would choose `1.19`.

That's my understanding too.

The problem is that improved pom support adds to the differences between Maven's dependency resolution and Gradle. As I tried to explain above, that's going to make things difficult for teams maintaining widely adopted libraries, particularly those like the various Spring projects with many optional dependencies.

**Comment by eriwen** [comment]
If we're not willing to change the default behavior, it is my sincerest request that we provide a flag or Gradle property for cases like this to help ease adoption. I think if we have something like that in place we have a path to evolve from there.

**Comment by bigdaz** [comment]
@eriwen There are multiple issues here, some of which stem from fairly intractable differences between the way Maven and Gradle do dependency resolution (and can't be easily solved with a simple flag). 

As to the specific issue of `optional` dependencies, we are discussing internally a way to turn these into 'weaker' constraints so that they don't influence resolution in unexpected ways.

As to the broader issues, one of our goals leading up to Gradle 5.0 is to make the "improved POM support" and "BOM import" functionality work in a way that supports the specific needs of the Spring Boot team. I don't think we'll be able to make everything work "just like Maven", but I hope we'll be able to come up with something satisfactory. I expect we'll be reaching out to @wilkinsona in the near future to discuss.

**Comment by eriwen** [comment]
Awesome, thanks @bigdaz. I'm sure there are many, many Spring Boot Gradle users who'll appreciate it.

**Comment by bigdaz** [comment]
Related Nebula integration issue: https://github.com/nebula-plugins/gradle-nebula-integration/issues/12

**Comment by bigdaz** [comment]
FYI We've decided to roll back the current support for Maven `optional` dependencies in Gradle 5.0. We won't automatically create a constraint when we see an optional dependency in a POM file.

We'll likely re-introduce this as an opt-in at a later date, as part of broader support for optional features in Gradle.

**Comment by Vampire** [comment]
Just to add my 2ct.
I feel very sad that `optional` dependencies will not be supported anymore by default (or at all) in 5.0.
Regarding the conflict resolution, the current behavior is exactly like I would have expected it to work.

If a library depends on some version of another library, there might be backwards incompatible changes in that version.
It is far more likely that you get backward compatible changes in newer versions than that you have changes in a newer version that also work in the older version.

Consider that spring-boot declares that it optionally depends on snakeyaml 5 while your build script depends on snakeyaml 3.
It is far more likely that things that worked in 3 still work in 5, than that things in 5 already were available in 3.
Of course they could be totally incompatible.

That's always the problem you have with transitive dependencies and version conflicts.

But in the sense of how Gradle does conflict resolution by default, choosing the newest version if no `force` is done and no custom resolve rules are setup, the current behaviour is exactly what I would expect when supporting optional dependencies.
