### ISSUE TITLE
BOM import cannot provide version recommendations for non-transitive configurations

### ISSUE THREAD

**Issue by jotel** [gradle/gradle#5467]
### Expected Behavior
For the following settings 
```groovy
configurations {
  foo {
    transitive = false
  }
}

dependencies {
    foo 'org.springframework.boot:spring-boot-dependencies:1.5.8.RELEASE'

    foo 'com.google.code.gson:gson'
    foo 'dom4j:dom4j'
}
```

I'd expect that the `com.google.code.gson:gson:2.8.2 and 'dom4j:dom4j:1.6.1` will be resolved in the `foo` configuration.

### Current Behavior
Configuration can't be resolved, Gradle fails with an error `Could not resolve all files for configuration ':foo'.`

### Context
It's not posisble to use recommendations using improved pom support on non-transitive configurations

### Steps to Reproduce (for bugs)

Github repo: https://github.com/jotel/g96
Just run `./gradlew showFooFiles` to excercise current behaviour. The task simply iterates troug files from configuration 
```groovy
task showFooFiles {
  doLast {
    configurations.foo.each {
      println "==> $it.name"
    }
  }
}
```

### Your Environment
N/A

**Comment by melix** [comment]
It's an interesting case, and it actually doesn't surprise me. `foo` is not transitive, and we add a dependency on `org.springframework.boot:spring-boot-dependencies:1.5.8.RELEASE`. Because we're not transitive, we don't get the dependencies of `spring-boot-dependencies`, so we cannot suggest versions for `com.google.code.gson:gson`.

This is _kind of_ related to #4422 (we don't _inline_ dependencies), but it's not exactly the same issue.

**Comment by ljacomet** [comment]
@melix Now that we have a nearly final plan for BOM support in Gradle 5.0, might be interesting to revisit this and comment on the expected outcome. Would the `platform` keyword take care of this for example? As one could argue that a non transitive platform makes little sense.

**Comment by melix** [comment]
There's no change on this: a `platform` dependency is still a dependency involving one level already. We don't inline dependencies, so the problem would be the same.

**Comment by ljacomet** [comment]
@jotel Can you describe why you mark a configuration as `transitive = false`?
This is a feature that the Gradle team is considering for removal in the future and is interested to understand why it gets used.

**Comment by ljacomet** [comment]
Closing as no change is planned from the Gradle side.
