### ISSUE TITLE
Provide public cancellation API

### ISSUE THREAD

**Issue by denisk20** [gradle/gradle#5468]
This [issue](https://github.com/gradle/gradle/issues/2128) meant to fix the situation when the gradle daemon is killed by executing `CTRL+C` command in the terminal along with the underlying process itself. The fix has been merged into `4.8 rc1` however the issue still appears when running a server using gradle, for example, an instance of local google app engine.

An example project:
https://github.com/denisk20/appengine-test

1. Run `./gradlew appengineRun`
2. Wait for `INFO: Dev App Server is now running` line to appear
3. Click `CTRL+C`
4. Wait a 4-5 seconds for the "Java" task to disappear
5. Run ./gradlew appengineRun again. Notice Starting Daemon line briefly appearing -- that means that the daemon has just been killed with `CTRL+C`.

**Comment by oehme** [comment]
The problem here is that the appEngine task doesn't use `exec`/`javeExec` (which supports cancellation), but runs some custom thread that Gradle doesn't know about and can't control. To fix this we'll probably need a public cancellation API for plugin authors.

**Comment by denisk20** [comment]
For the case of Google App Engine the problem can be mitigated if one uses `./gradlew appengineStop` to stop the dev server. This way the next `./gradlew appengineRun` usually leverages the daemon.

**Comment by mkobit** [comment]
I think that is the route that most plugins have gone down for application startup and teardown. I've seen a few different ways that applications or plugins handle it:

* Gradle `--continuous` mode support built-in for deployment reloading that "cancel" on signal/Ctrl + C
    * [Ratpack supports this](https://ratpack.io/manual/current/gradle.html#development_time_reloading)
    * Gradle's built-in [Play Support](https://docs.gradle.org/current/userguide/play_plugin.html#play_continuous_build)
* separate tasks for lifecycle start and stop with the "background" task running separate from Gradle. 
    * AppEngine example above
    * [Gretty](https://akhikhl.github.io/gretty-doc/Gretty-tasks)
* application is aware of changes itself and hot reloads on change detection
    * [vert.x CLI option that watching filesystem and runs `./gradlew classes` on each change] (https://github.com/vert-x3/vertx-examples/tree/master/gradle-redeploy)
    * [ktor reloads of classfiles, for example by running `./gradlew classes -t` alongside the application itself](http://ktor.io/servers/autoreload.html#recompiling-automatically-on-source-changes)

**Comment by mkobit** [comment]
Also, this sounds similar to https://github.com/gradle/gradle/issues/1128

**Comment by oehme** [comment]
In Gradle 6.0, task threads will be interrupted when the build is cancelled, allowing tasks to react to that signal and wrapping up quickly.

**Comment by LouisCAD** [comment]
Perfect to work with coroutines since `runBlocking` will cancel the coroutine if the blocked thread is interrupted!
https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html
