### ISSUE TITLE
Internal task ':languageNative:integTest' fails when platform GCC lacks Objective-C support

### ISSUE THREAD

**Issue by Aaron1011** [gradle/gradle#5469]
When GCC lacks support for compiling Objective-C code (the `cc1obj ` binary is not installed), the Objective-C related tests error with a `NullPointerException`. A stacktrace can be seen [here](https://pastebin.com/raw/pZA2HwD1)

### Expected Behavior
The `:languageNative:integTest` task should print an informative error message explaining that Objective-C support is missing from GCC, or should simply skip any Objective-C related tests.

### Current Behavior
A large number of Objective-C related tests fail with a `NullPointerException` Without attaching a debugger, it's impossible to determine that the missing Objective-C support is the root cause.

### Context
I'm attempting to contribute to Gradle. When running `./gradlew check` locally, I came across these test failures.

### Steps to Reproduce (for bugs)
1. Remove Objective-C support from your platform GCC. On Arch Linux, this can be done by uninstalling the `gcc-objc` package. I haven't tested any other platforms, but I believe that removing the `gobjc` package on Ubuntu will have the same effect.
2. Clone the `gradle` repository, and run `./gradlew :languageNative:integTest`.
3. Observe the large number of Objective-C test errors.

### Your Environment
I'm running Gradle on Arch Linux. However, this issue should be reproducible on any Linux distribution that packages Objective-C support for GCC separately.

 * Build scan URL: https://scans.gradle.com/s/petu3mblz5rc6/

**Comment by lacasseio** [comment]
Issue moved to [gradle/gradle-native #689](https://github.com/gradle/gradle-native/issues/689) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lacasseio** [comment]
Thanks @Aaron1011 for reporting this issue. We will consider this use case when improving the tool chain support.
