### ISSUE TITLE
Public API for adding to SourceSetOutput.classesDirs

### ISSUE THREAD

**Issue by ajoberstar** [gradle/gradle#5471]
### Expected Behavior

JVM language plugins need to be able to modify SourceSets similar to core Gradle plugins. Currently, there is no way to add a classesDir to the SourceSetOutput.

### Current Behavior

Currently, you need to use internals:

Either:

```java
SourceSetUtil.configureOutputDirectoryForSourceSet(sourceSet, clojurescriptSourceSet.getClojureScript(), compile, project);
```

But the signature is [changing in 4.8](https://github.com/gradle/gradle/commit/25f870d43d48265f30d770302f7ff3191002d6a7).

Or you have to cast to `DefaultSourceSetOutput` to access `addClassesDirs`.

### Context

Third-party JVM language plugins have nearly identical requirements to the core ones, and need stable public APIs for core features like adding and configuring SourceSets.

Similar issues #727, #3191, #831.

As a side note here, the deprecated model-space approach for this was on a much better path. I just had to declare I wanted a ClojureSourceSet and register it as a language. Gradle dealt with providing default directories for everything for me. Ultimately, there's no reason that I (as a language plugin author) need to care what directory you put those classes in or where the sources are (as long as it's unique and consistent with other plugins).

It would be great to cut down the boilerplate for language plugins (particularly JVM ones).

### Your Environment

 * Build scan URL:

**Comment by JLLeitschuh** [comment]
@ajoberstar Stutter is awesome. Considering using it on some of my plugins. Good catch on this one.
