### ISSUE TITLE
Add the ability to configure a delay in continuous mode

### ISSUE THREAD

**Issue by bric3** [gradle/gradle#5481]
Following a discussion on twitter @eriwen, I wondered if it was possible to make gradle delay it's execution in continuous mode.

I have an IDE that _aggressively_ auto save my content on disc, this content may be a coherent compile unit or more likely not, even for non compilation tasks I see gradle zealously running tasks as soon as it sees a file modified. I'd like to alter this behaviour to delay or debounce those events, like waiting 10 or 30 seconds of inactivity to actually starts something.

The twitter thread : https://twitter.com/BriceDutheil/status/997523010281144321

**Comment by ov7a** [comment]
Fixed in 7.5 by
* https://github.com/gradle/gradle/pull/20027
