### ISSUE TITLE
JUnit with RunWith(Suite.class) runs inner tests twice

### ISSUE THREAD

**Issue by jkff** [gradle/gradle#5484]
`FooTest.java`:

```
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({
    FooTest.InnerTest.class
})
public class FooTest {
  @RunWith(JUnit4.class)
  public static class InnerTest {
    @Test
    public void testInner() {
      throw new RuntimeException();
    }
  }
}
```

`build.gradle`:

```
apply plugin: 'java'
repositories {
    mavenCentral()
}
dependencies {
    testCompile 'junit:junit:4.12'
}
```

### Expected Behavior
When I do `./gradlew build`, the `testInner()` method should be run once.

### Current Behavior
The method is run twice.

### Context
Running tests multiple times is wasteful.

### Steps to Reproduce (for bugs)
[gradle-test.tar.gz](https://github.com/gradle/gradle/files/2023903/gradle-test.tar.gz)

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/3bp3uc4dty7jk

**Comment by marcphilipp** [comment]
Please use `@RunWith(Enclosed.class)` instead of `@RunWith(Suite.class)` for this use case.
