### ISSUE TITLE
Set gradle version as property at runtime

### ISSUE THREAD

**Issue by sksamuel** [gradle/gradle#5489]
In the JVM it would be very useful (at least to me!) to be able to detect which version of gradle is being used for a build. This would allow me to add a workaround for a gradle issue that only affects 4.7/4.8 for example. There are gradle properties for the worker (org.gradle.test.worker) and native mode. So org.gradle.version could be added too.

**Comment by oehme** [comment]
There's already Gradle.getGradleVersion, so I'm not sure what's missing.

**Comment by sksamuel** [comment]
What I'm referring to is detecting the version of gradle inside your the code being built, and not inside the gradle build file itself.

**Comment by oehme** [comment]
Why would the code being built depend on the Gradle version?

**Comment by sksamuel** [comment]
There's a bug in 4.7 (and probably 4.8) whereby gradle doesn't support nested tests in junit properly. There is an issue already open, and it's getting fixed. However in the meantime it would have been helpful if I could add a workaround in my project (https://github.com/kotlintest/kotlintest/issues/336). Ideally I'd only want the workaround to appear when it's in a version of gradle that has the issue (and also, for example, not when running tests via intellij) because it reduces functionality so I don't want to to apply when it's a version of gradle that seems to work.

That's one example, and I'm sure this kind of functionality might appear in the future.

**Comment by oehme** [comment]
Okay, so it's just to work around a bug. Here's how you can do that workaround in your build until the bug is fixed:

```
tasks.withType(Test) {
  systemProperty "gradle.version"  gradle.gradleVersion
}
```

**Comment by sksamuel** [comment]
Ok, but now I have to tell every user of KotlinTest to do this. Which means people will open up issues saying KotlinTest is broken when they try to run it with latest gradle.

It's not the _end of the world_ but I think setting the gradle version during a build would be useful regardless.

**Comment by oehme** [comment]
Let's get the bug fixed instead of adding another feature. The timeline would be the same - Gradle 4.9
