### ISSUE TITLE
Gradle 4.7 with Java 9/10 cannot run load FXML files

### ISSUE THREAD

**Issue by Kool-Koder** [gradle/gradle#5506]
Hi,

I have tried multiple combinations. Apparently, Gradle 4.7 with Java 1.8 can load the FXML files and display it.

However, with Gradle 4.7 (Java 9/10), it is not possible to load the FXML files as the "package does not exists". Is there a bug or some limitation with Java 9/10? Thanks! :)

Attached with error message below.

![gradle](https://user-images.githubusercontent.com/39305371/40435737-e8f0860a-5ee3-11e8-82c3-7d88ca3b2dc7.PNG)

**Comment by marcphilipp** [comment]
Are you using OpenJDK or Oracle JDK?

**Comment by marcphilipp** [comment]
I'm closing this issue as it most probably a JDK issue (JavaFX is not available on OpenJDK 9/10) and nothing Gradle can do anything about. If you think otherwise, please open another issue and provide a sample project.
