### ISSUE TITLE
4.8-rc1 introduced new illegal reflective access operation 

### ISSUE THREAD

**Issue by sormuras** [gradle/gradle#5529]
Also present in `4.8-rc-2`:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.gradle.internal.reflect.JavaMethod (file:/C:/Users/Sor/.gradle/wrapper/dists/gradle-4.8-rc-2-bin/dkhalqo78s9dbz4hnfu2wbwtr/gradle-4.8-rc-2/lib/gradle-base-services-4.8.jar) to class java.lang.ClassLoader
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Is this a known ... temporary Lookup?

**Comment by marcphilipp** [comment]
Indeed, this was changed for #4860 to work on JDK 11 but uses reflection to compile on Java 7.

@blindpirate @oehme Do you think it would be feasible to move `LookupClassDefiner` and other related code to a separate Java 9-based subproject, e.g. `base-services-java9`, to avoid using reflection?

**Comment by blindpirate** [comment]
It is feasible but need a bit more work. I picked this solution out of several choices: https://github.com/gradle/gradle/pull/4976#issuecomment-379660504

If we decide to remove this warning, I'd like to do it. :-)

**Comment by marcphilipp** [comment]
Maybe we can address this in conjunction with #5079?

**Comment by oehme** [comment]
Fixed by https://github.com/gradle/gradle/commit/3db6e256987053171178aa96a0ef46caedc8d1a4

**Comment by sormuras** [comment]
Same, same. But different. Using 4.9-rc1.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by worker.org.gradle.internal.reflect.JavaMethod (file:/C:/Users/Sor/.gradle/caches/4.9-rc-1/workerMain/gradle-worker.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of worker.org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by oehme** [comment]
@blindpirate Can you please take a look at the above?

**Comment by sormuras** [comment]
Find the warning emitted here: https://travis-ci.org/junit-team/junit5/jobs/399631088

**Comment by blindpirate** [comment]
Thanks @oehme @sormuras We had fixed this in https://github.com/gradle/gradle/commit/3db6e256987053171178aa96a0ef46caedc8d1a4, but this broken IDEA import so we have to revert it. Now it's in https://github.com/gradle/gradle/pull/5811 but it seems too late to be in `4.9`. @oehme Do you think we should cherry-pick it into `4.9`?

**Comment by oehme** [comment]
I'm fine with pushing this out to 4.10, we should just mark it accordingly.

**Comment by oehme** [comment]
Btw does your change also fix https://github.com/gradle/gradle/issues/5079?

**Comment by oehme** [comment]
Nothing we can do about those until Groovy fixes them. Any way to get stacktraces for those warnings?
