### ISSUE TITLE
Gradle fails config if a publication repo has colon in the name

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#5533]
### Expected Behavior
Gradle should not fail or fail with helpful message.

### Current Behavior

Gradle fails with unhelpful error message.

### Context
I am setting up an enterprise build and we are managing repo managers centrally, allowing each project to configure repository by a pair of `managerId` and `repoId`. 

Later in the configuration, we look for the best-matching credentials in hierarchical manner that allows to specify different credentials for release/integration, as well as for each project or each manager. Ideally, we would have had `ext` properties on the repo, but right now we tunnel this information with structured names. The initial separator was colon, which lead to the discovery of this bug.

Fixing Gradle to strip the colon when it creates the task, or not allow colons in the repo names are both acceptable solutions. The current error is confusing to build users.

### Steps to Reproduce (for bugs)

If we configure a project as follows:

````
apply plugin: 'java-library-distribution'
apply plugin: 'maven-publish'
publishing.repositories.maven {
            name = "bro:ken"
            url "$buildDir/repo"
}
````

The build would fail with:

````
Could not determine the dependencies of task ':publish'.
> Task with path 'publishMavenJavaPublicationToBro:kenRepository' not found in root project 'foobar'.
````

That is, Gradle would search for project `publishMavenJavaPublicationToBro` and task `kenRepository`

### Your Environment
Gradle 4.7

**Comment by marcphilipp** [comment]
Thanks for reporting this issue! I think not allowing colons with a good error message is the way to go. Publication names are probably affected as well.
