### ISSUE TITLE
Reduce memory used in FileUtils#calculateRoots

### ISSUE THREAD

**Issue by tjni** [gradle/gradle#5541]
### Current Behavior
The `calculateRoots` method in `FileUtils` is called many times in my build, and profiling reveals a large amount of string memory allocation:

<img width="1139" alt="screen shot 2018-05-25 at 8 51 51 am" src="https://user-images.githubusercontent.com/3806110/40560135-eb5ba7aa-600d-11e8-8dc3-b68365304d6b.png">

This is avoidable if we rewrite the code with that in mind.

### Context
The build I work with is large, and I am investigating if memory pressure is one of the bottlenecks of its performance. I'll submit a PR linking back to this issue.

**Comment by tjni** [comment]
It's hard to compare exactly, but here is what our heap looks like in comparable parts of the build:

Before:

<img width="1130" alt="screen shot 2018-05-25 at 12 01 23 pm" src="https://user-images.githubusercontent.com/3806110/40561829-84ae45ca-6013-11e8-88fc-d1a1f030df24.png">

After:

<img width="1120" alt="screen shot 2018-05-25 at 12 01 39 pm" src="https://user-images.githubusercontent.com/3806110/40561833-8acbab46-6013-11e8-8f55-8385716b5f29.png">

**Comment by oehme** [comment]
Thank you for the PR, makes perfect sense. 

I'd like to work a bit more with you regarding build performance if you're interested. Maybe we can find other areas for improvement based on your build. You can drop me a line at stefan@gradle.com

**Comment by oehme** [comment]
PR merged. Feel free to reach out to me for further optimizations as mentioned above.
