### ISSUE TITLE
IDEA Plugin generates unexpected directory structure given sub-project deeper than 1 level

### ISSUE THREAD

**Issue by guspower** [gradle/gradle#5548]
### Expected Behavior
Given a project with a subproject more than one level deep, `./gradlew idea` should generate a correct `subproject.iml` in the subproject folder. 

### Current Behavior
Instead this file is generated and placed in subfolder corresponding to the project's parent folder.

### Context
Setting up a new multi-level project

### Steps to Reproduce (for bugs)
1. Create `build.gradle`
```
allprojects {
  apply plugin:'idea'
}
```
2. Create nested subproject directory
```
mkdir -p subdir/subproject
```
3. Add subproject to `settings.gradle`
```
include 'subdir/subproject'
```
4. Run IDEA plugin
```
gradle idea
```
5. Observe output
```
> find .

.
./build.gradle
./subdir
./subdir/subproject
./subdir/subproject/subdir
./subdir/subproject/subdir/subproject.iml
./settings.gradle

```
(Expected `./subdir/subproject/subproject.iml` but got `./subdir/subproject/subdir/subproject.iml`)

### Your Environment
```
$ gradle -version

------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Linux 4.16.7-gentoo amd64
```

**Comment by oehme** [comment]
Please check the log, you should have gotten a deprecation warning about the slash in the project name. Logical project paths (as used by the include method) are separated by a colon.

```
include `subdir:subproject`
```

**Comment by guspower** [comment]
Yes indeed:
```
$gradle idea -Dorg.gradle.warning.mode=all

The project name 'subdir/subproject' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/4.7/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
```
Sure enough I changed the `settings.gradle` to `subdir:subproject` and all is well. Thanks for your help and quick reply.
