### ISSUE TITLE
Source set dependencies all in Provided mode in Intellij 2018.1.4

### ISSUE THREAD

**Issue by dcoraboeuf** [gradle/gradle#5551]
### Expected Behavior

Using Gradle 4.6, I've declared an extra source set:

```groovy
sourceSets {
    acceptance {
        java.srcDir file('src/acceptance/kotlin')
        resources.srcDir file('src/acceptance/resources')
        compileClasspath = configurations.acceptanceCompileOnly
    }
}
```

I've added several dependencies into the associated configuration:

```groovy
    acceptanceCompileOnly "net.serenity-bdd:serenity-cucumber:1.9.7"
    acceptanceCompileOnly "org.influxdb:influxdb-java:2.10"
```

When I import the Gradle project into Intellij 2018.1.4, I expect the dependencies of the "acceptance" source set to have all dependencies in the Compile scope.

### Current Behavior

All dependencies do appear as Provided, making the code not runnable from Intellij. They should appear as Compile.

Note that this issue has already been reported in the past - see #1276

### Context

I'm trying to define a distinct source set, isolated from the `main` and `test` ones, with its own configuration and set of dependencies.

### Steps to Reproduce (for bugs)

See above.

When trying to apply the workaround described at #1276 (not using the modules per sourceset), the code does not compile any longer.

### Your Environment

* Mac OS
* Intellij 2018.1.4
* Gradle 4.6
* JDK 1.8 / Kotlin 1.2.41

**Comment by oehme** [comment]
You marked them as `compileOnly`, which by definition means "not available at runtime".

**Comment by oehme** [comment]
Also, this line is unnecessary: `compileClasspath = configurations.acceptanceCompileOnly`. This property already has a proper default.
