### ISSUE TITLE
Don't create .gradle folder if gradle is run outside of a gradle project

### ISSUE THREAD

**Issue by Xerus2000** [gradle/gradle#5554]
Sometimes I accidentally run gradle in the wrong directory, which failes and creates a .gradle directory where it simply does not belong.

### Expected Behavior
Either it does not create a .gradle directory until the location is confirmed to be a gradle project, or it removes the .gradle directory after failing. The directory only contains hashes at that point anyways.

### Current Behavior
A .gradle folder is always created when running gradle in a directory, unless there is a settings.gradle in one of the parent directories.

### Steps to Reproduce
Run gradle in a directory that is neither a gradle project nor a folder in a gradle project.

**Comment by oehme** [comment]
Any folder (even empty) is a valid Gradle project, so there is no way for us to tell whether this call was intended or not.

That being said, I just made some changes that move some of the hashes into the user home, so the latest 4.9 nightly should no longer create any hashes in the project dir (since the project is empty, so there is nothing project-specific to hash).

**Comment by rosti-il** [comment]
Hi @oehme
Could you explain more about "any folder (even empty) is a valid Gradle project"? What is the rationality of creating the `.gradle` directory in such folders that don't contain any other Gradle file?

Also, running `gradle --warning-mode all` with Gradle 6.0.1 in a folder without any Gradle file prints the following warning:
_Executing Gradle tasks as part of an undefined build has been deprecated. This will fail with an error in Gradle 7.0._

Running the same command in the root of some Gradle project doesn't print this warning. And finally running that command inside any sub-folder of that Gradle project fails with the following error message:
```
C:\develop\test\aaaaa>gradle --warning-mode all

FAILURE: Build failed with an exception.

* What went wrong:
Project directory 'C:\develop\test\aaaaa' is not part of the build defined by settings file 'C:\develop\test\settings.gradle'. If this is an unrelated build, it must have its own settings file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```
So Gradle already can distinguish between an empty folder that is a sub-folder and not a sub-folder of a Gradle project with the `settings.gradle` mandatory file.

Will Gradle 7.0 not create the `.gradle` everywhere but in the root of a Gradle project with mandatory Gradle file(s) in it?

**Comment by nmoreaud** [comment]
I agree with this report
