### ISSUE TITLE
excluding lib folder from jar

### ISSUE THREAD

**Issue by MonicaNegi** [gradle/gradle#5562]
Hi, 
I am creating a jar from gradle project using following task-
task fatJar(type: Jar) {
     exclude('lib')     
	baseName = project.name
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
I want to exclude lib folder from the generated jar. 
Providing exclude('lib') doesn't excludes lib folder from the jar.
Please let me know, how can i achieve this.

**Comment by marcphilipp** [comment]
Have you tried `exclude('lib/**')`?

**Comment by MonicaNegi** [comment]
Thanks, it worked with exclude('lib/**')

**Comment by marcphilipp** [comment]
Glad to hear it! 🙂
