### ISSUE TITLE
Make AbstractCodeQualityPlugin part of the public API

### ISSUE THREAD

**Issue by Mauin** [gradle/gradle#5575]
The code quality plugins that are shipping with Gradle (PMD, Findbugs, Checkstyle, etc.) all extend the internal `AbstractCodeQualityPlugin`. Other, external code quality plugins that want to offer a very similar API to these plugins are either forced to extend the internal API and handle unexpected changes down the line, or emulate the behavior by re-implementing it.

Is it possible to make `AbstractCodeQualityPlugin` part of the public API? Alternatively: What are the alternatives for external code quality plugins to support the same API as the Gradle-internal code quality plugins?

### Expected Behavior
Support `AbstractCodeQualityPlugin` as part of the public API

### Current Behavior
`AbstractCodeQualityPlugin` is an internal API and subject to breaking changes at any time.

### Context
As part of a refactor in Detekt, a static analysis tool for Kotlin, we are implementing `AbstractCodeQualityPlugin` to give Detekt the same API and features that other code quality plugins also use: https://github.com/arturbosch/detekt/pull/771

This brought up the discussion if we want to extend this internal API and live with potential breaking changes down the line.

### Steps to Reproduce (for bugs)
/

### Your Environment
/

**Comment by marcphilipp** [comment]
Related issue:
https://github.com/spotbugs/spotbugs-gradle-plugin/issues/22

I took a quick look at `AbstractCodeQualityPlugin`. It basically uses a template method approach for configuration but does not seem to be using any internal APIs. Thus, I think third-party code quality plugins such as Detekt and Spotbugs might be better off not extending `AbstractCodeQualityPlugin`.

@Mauin Am I missing something?

**Comment by marcphilipp** [comment]
FWIW Spotbugs is planning to make the move away from `AbstractCodeQualityPlugin`:
https://github.com/spotbugs/spotbugs-gradle-plugin/issues/29.

**Comment by Mauin** [comment]
I see. I've also noticed the breaking API change in 4.8, which is fine. 
But overall wouldn't it be better for the entire ecosystem if code quality plugins could all share the same basic API for configuring the different tools? With external code quality plugins implementing their own plugins every plugin will end up with a different API and configuration. If all plugins extend the same base `AbstractCodeQualityPlugin` at least some parts of the API would be the same across all tools.

**Comment by marcphilipp** [comment]
The only shared configuration API I could find is `CodeQualityExtension` which is public and can be reused by other plugins.

Could you try to implement your plugin without using `AbstractCodeQualityPlugin` so we can see how much of it ends up being duplicated? If it's a substantial amount, we can and will certainly reconsider.

**Comment by big-guy** [comment]
+1 Marc said. I reckon the better approach is to have an extendable model vs "here's a base plugin you extend".
