### ISSUE TITLE
Use ComponentMetadataRule in buildSrc

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#5589]
We use `org.gradle.api.artifacts.dsl.ComponentMetadataHandler.withModule()` methods in buildSrc.  We get CI failures now that we've deprecated these methods.  For now, I've suppressed these deprecations until we can convert buildSrc to use ComponentMetadataRules.

Revert this commit
https://github.com/gradle/gradle/commit/c46db10ea151af2777e8deef69666aa92f5a8b46

**Comment by ljacomet** [comment]
Fixed by #5607
