### ISSUE TITLE
Constraint Doc Improvement Request (and maybe feature)

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#5591]
Reading this https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html

```
   constraints {
        implementation('org.apache.httpcomponents:httpclient:4.5.3') {
            because 'previous versions have a bug impacting this application'
        }
        implementation('commons-codec:commons-codec:1.11') {
            because 'version 1.9 pulled from httpclient has bugs affecting this application'
        }
    }
```

ok, so do constraint versions fix the actual version, if 4.5.4 of httpclient is out will it still get pulled? how about 4.6? 5?  if not can I write `4.+`? what if I want version 4 or later including 5? does 4+ do that?

https://docs.gradle.org/current/userguide/dependency_management_for_java_projects.html according this I'm pretty sure I can't do 4+ even if it were accurate

I actually have a specific problem in regards to this I'm trying to understand the right way to resolve. Some of my test code relies specifically on assertj 3.8+ (including 3.9), I'd like to define my dep accurately as 3.8+ as 3.+ in theory will match a number of versions that wouldn't even compile, I also don't want to restrict to 3.8.+ because I have no reason to.

**Comment by bigdaz** [comment]
Thanks for your comment. There are two things that are not clear from our documentation that should make this clearer:

1. Dependency `constraints` support dynamic versions (version ranges) just like regular dependencies. So you can use `4.+` if you like.
2. Gradle support both Ivy-style (`4.+`) and Maven-style (`[4.0, 5.0)`) version ranges. 

I've raised #5603 to specifically deal with the second point. In the meantime, here are some hints:
- `4.+` does string matching on the version number, so will match any version that begins with `4.`. (Don't use `4+`, it never makes sense to match `4.0`, `42.3` and `400.3` but not `5.0`!)
- For your `assertj` case, try using `[3.8, 4.0)` to include all versions >= 3.8 and < 4.0.

**Comment by xenoterracide** [comment]
maybe... but this worked when the version was was on the dependency and there were no constraints.

```
       static final String LATEST = ":latest.release";
        project.getPluginManager().apply( "org.gradle.java-library" );
        DependencyHandler deps = project.getDependencies();
        deps.add( COMPILE, "com.google.code.findbugs:jsr305" );
        deps.add( TEST_IMPL, "org.junit.jupiter:junit-jupiter-api" );
        deps.add( TEST_IMPL, "org.assertj:assertj-core" );
        deps.add( TEST_RUN, "org.junit.jupiter:junit-jupiter-engine" );

        deps.constraints( dch -> {
            dch.create( "com.google.code.findbugs:jsr305" + LATEST );
            dch.create( "org.junit.jupiter:junit-jupiter-api:5.+" );
            dch.create( "org.junit.jupiter:junit-jupiter-engine:5.+" );
            dch.create( "org.assertj:assertj-core:[3.8,4)" );
        } );
```

now

```
$ ./gradlew clean compileJava
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.google.code.findbugs:jsr305:.
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by bigdaz** [comment]
Just like your using `dependencies.add()` you need to use [`dependencies.constraints.add`](https://docs.gradle.org/4.8-rc-3/javadoc/org/gradle/api/artifacts/dsl/DependencyConstraintHandler.html#add-java.lang.String-java.lang.Object-). The `create` method creates a 'detached' constraint, not bound to any configuration.
