### ISSUE TITLE
Feature: add constraint "groups"

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#5592]
related to #5404 it would be nice to write a plugin as 

        deps.constraints( dch -> {
            dch.create( "testCompile", "org.junit.jupiter:junit-jupiter-api:5.+" ).withAlias("junit");
            dch.create( "testRuntime", "org.junit.jupiter:junit-jupiter-engine:5.+" ).withAlias("jupiter");
            dch.create(  "testImplementation", "org.assertj:assertj-core:3.8+" ).withAlias("assertj");
            dch.create( "testImplementation", "org.mockito:mockito-core:3.+").withAlias("mockito")
            dch.group("junit5").of( "jupiter", "junit" );
            dch.group("test").of( "assertj" ).with("junit5");
            dch.group( "mock-test").of("mockito").with("test");
        } );

then use it like

     dependencies {
         use("test")
     }

or 

     dependencies {
         use("mock-test")
     }

which would import -api as a test compile dep, and engine as a test runtime, this is similar spring-boot-starter modules.

**Comment by xenoterracide** [comment]
one thought is being able to write a `Plugin<DependencyConstraintHandler>` however the problem I have with this, is really 2 things 1. Plugins can't use dynamic versions... 2. I don't see it as a plugin so I'd prefer it not be in that block.

**Comment by ljacomet** [comment]
Thanks for the idea.

Work is still ongoing around constraints and concepts to group them together. Your idea seems similar to what Maven BOMs are used for and we have plans for supporting and defining similar things in Gradle.

As such, closing this issue. Please watch out for announcements around this in the future.
