### ISSUE TITLE
Publishing extension behavior change in 4.8-rc-3

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#5605]
When we upgrade to 4.8-rc-3, previously working publishing configurations break with:

> org.gradle.api.InvalidUserDataException: Cannot configure the 'publishing' extension after it has been accessed.

### Expected Behavior
The publishing extension should be configurable.

### Current Behavior
The publishing extension is being accessed unexpectedly before the build is able to configure it.

### Context
It breaks our publishing verification feature.

### Steps to Reproduce (for bugs)
Run the `PublishVerificationPluginIntegrationSpec` tests in https://github.com/nebula-plugins/nebula-publishing-plugin

### Your Environment
Gradle 4.8-rc-3

**Comment by oehme** [comment]
RC3 just restored the deferred configurable behavior by default, which was erroneously removed in RC1/2. The changes to your plugin assume that the `STABLE_PUBLISHING` feature is always on. To make it compatible with both approaches, the `afterEvaluate` block should be inside the `publishing` block, not around it.

**Comment by DanielThomas** [comment]
Thanks @oehme! @chali heads up.

**Comment by oehme** [comment]
To be more precise, it only needs to be around the if-condition that decides which component to use.

**Comment by chali** [comment]
I went with:

```
    project.publishing {
            publications {
                nebulaIvy(IvyPublication) {
                    project.afterEvaluate { p ->
                        if (p.ext.get(IVY_WAR)) {
                            from p.components.web
                        } else if (p.ext.get(IVY_JAR)) {
                            from p.components.java
                        }
                    }
                }
            }
        }
```

But now it is not publishing jar at all. Using Gradle 4.8-rc-3 without the STABLE_PUBLISHING  feature flag. Am I overlooking something?

**Comment by oehme** [comment]
Without stable publishing ,the project already is evaluated. You need to check the project's state. 

I've tried finding out who is dereferencing the publication too early. How do I make your tests run against a local install of Gradle?

**Comment by chali** [comment]
I had an impression that I could make it work with or without STABLE_PUBLISHING with one configuration based on this comment "To make it compatible with both approaches, the afterEvaluate block should be inside the publishing block, not around it." But based on the last comment I have to have some branching in the code to handle each case differently. Right? I was looking at `ProjectState` but it has only executed flag which doesn't seem helpful.

**Comment by chali** [comment]
So far I'm using this as a condition `project.getServices().get(FeaturePreviews).isFeatureEnabled("STABLE_PUBLISHING")` Everything is internal :(

**Comment by oehme** [comment]
Just use the executed flag, that's exactly what I meant.

**Comment by chali** [comment]
Aaah. I thought that it will be true when the whole graph is executed. I used it and it works! Thanks, @oehme for your help
