### ISSUE TITLE
Add a flag to treat 403 as a missing resource

### ISSUE THREAD

**Issue by helfper** [gradle/gradle#5606]
Artifactory, that is very popular software to serve Maven artifacts, in some configurations returns 403 instead of 404 when the artifact is missing (https://www.jfrog.com/jira/browse/RTFACT-13797).

Would it be possible add a flag (either to the command line or a field in repositories > maven) to treat the 403 Forbidden as missing ressource? This would make some Gradle tasks run much faster.

I think the most relevant part in the code for that issue is:

https://github.com/gradle/gradle/blob/757eadb00ccdd9ea7040a6482258149bf46bc83e/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/HttpClientHelper.java#L151-L162

**Comment by helfper** [comment]
Sorry, I got it the way around. I meant treat 403 as missing. I have updated the title and description.
When the dependency is missing, Gradle will not try to download again, but it will when it gets a 403 Forbidden.
This makes a huge difference when we refresh the Gradle project in IntelliJ and some dependencies don't have sources for example. I means taking dozens of minutes versus just a few seconds.

**Comment by oehme** [comment]
Got it, thanks for the explanation!

**Comment by helfper** [comment]
FWIW Someone at my company created a patched version of Gradle internally, basically replacing the first `if` above with something like `if (wasMissing(response) || wasForbidden(response))`, and it works just great for us. I only suggested it begging a flag as I'm not fully aware about the possible consequences of always treating Forbidden in the same way as missing and it might break someone else's workflow. Otherwise, doing it always would be just fine with me.

**Comment by oehme** [comment]
I think it would make sense to configure things like this on the repository level. Basically give Gradle more information about each specific repository instead of a global flag.

**Comment by citistefanos** [comment]
Is there a good reason why treating 403 as missing shouldn't be default behaviour? Returning 403 for missing artifacts is actually good security practice in many situations (to avoid someone without access from implying the presence of something).

This is particularly insidious issue in my case because it hits our gradle plugins. The plugin resolver will look for the plugin descriptor, then for a pom (which it finds) then for a JAR (which it won't find), then look at the pom to find the actual JAR. Now that the JAR lookup returns 403 instead of 404 (our admins disabled global read access), this makes it impossible to resolve any plugin.

Basically, if plugin and dependency resolution treat missing artifacts as a recoverable error and it's reasonable for repositories to return 403 instead of 404 for missing artifacts, then they should be treated the same.

**Comment by marcphilipp** [comment]
> Is there a good reason why treating 403 as missing shouldn't be default behaviour? Returning 403 for missing artifacts is actually good security practice in many situations (to avoid someone without access from implying the presence of something).

Isn't that usually done the other way around? Returning 403 can be considered information disclosure whereas 404 does not expose that vulnerability (cf. https://lockmedown.com/when-should-you-return-404-instead-of-403-http-status-code/). IMHO this is a bug in Artifactory and should be fixed there.

**Comment by citistefanos** [comment]
> Isn't that usually done the other way around?

Seems like it is. I suppose any case where some resources return 404 and others 403 can be used to test for their existence, but I digress: Given that gradle often looks at multiple repositories, and often for expected-to-be-missing resources (e.g. plugin jars next to the plugin poms) would it not make sense to treat 403s as recoverable just as it does 404?

> IMHO this is a bug in Artifactory and should be fixed there.

For sure, but I think treating 403s as missing resources is still the right behaviour.

**Comment by citistefanos** [comment]
I can't argue with that. Even a feature toggle would be a hack in that case. Maybe close this issue as won't fix?

**Comment by ljacomet** [comment]
There are no plans on changing this behavior in Gradle.

Please re-open with added use cases if you believe it really is a missing configuration.
