### ISSUE TITLE
Support test fixtures as a first class concept

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#5615]
Sharing test fixtures for a library is a common use case that Gradle should support out of the box:

- test fixtures are code that makes it easier to test a library
- test fixtures depend on the main code of the library
- the library's tests depend on its test fixtures
- downstream project's tests should automatically depend on the test fixtures if they depend on the library
- test fixtures can be published alongside the library, including proper dependency declarations

Alternatively, we could provide the infrastructure for users to define their own components and their relationships and leave test fixtures to a community plugin. But I think they are important enough to be a core concept.

**Comment by sebersole** [comment]
@oehme To follow up on our discussion from #1061, how would a sub-project define a dependency on this "test fixture" artifact?

Specifically asking about your statement "So as long as there is exactly one publication with a component (your main library), that one's coordinates will be put in dependency declarations of downstream projects."  

I guess it depends on what you mean by "downstream projects".  As far as normal "external dependency" notation, the test fixture would have a different name/artifactId (`hibernate-testing` versus `hibernate-core`), so I am not overly worried out that.  However, I am worried about sub-projects.  Assuming that the project `hibernate-core` defines this configuration/publication/artifact, how would another Hibernate ORM sub-project reference that as a dependency?

Thanks, as always, for your help :)

**Comment by oehme** [comment]
As of now, you'll have to put it into a Configuration and reference that Configuration. E.g.

```
configurations {
  testFixtures
}

artifacts {
  testFixtures testFixturesJar
}
```

```
dependencies {
  testImplementation project(path :'foo', configuration: 'testFixtures')
}
```

**Comment by sebersole** [comment]
Ah sweet, that's perfect.  Did not realize that project-dependencies could specify `configuration`.  And this solution (^^) is available already in 4.8/4.9?

**Comment by oehme** [comment]
Oh, that's been around since 1.0 :)

**Comment by sebersole** [comment]
That's what I get for starting at .7 ;)

**Comment by oehme** [comment]
Might have been there too, I didn't check. I was late to the party compared to you :)

**Comment by pioterj** [comment]
Addressed by https://github.com/gradle/gradle/pull/9632

**Comment by ljacomet** [comment]
Documentation has been added as well #9724
