### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by jenlindadsouza** [gradle/gradle#5616]
### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Please follow our issue template.

**Comment by jenlindadsouza** [comment]
Sorry about that. I didn't realize it submitted. I had second thoughts on submitting the issue as I realized it might be a better fit in the IntelliJ IDEA community. The issue is the following:


I was looking for advice on the ideal way to resolve the Project Build Failure issue using Gradle within the IntelliJ environment. The error message I get is:

    Cause: startup failed:
    initialization script 'C:\Users\JenniferD'Souza\AppData\Local\Temp\ijinit.gradle': 5: unexpected char: '\' @ line 5, column 45.
    le('C:\\Users\\JenniferD'Souza\\AppData\
                              ^

    1 error

I understand the single-quote (apostrophe) character in the directory name is breaking the build file path. Is there a way to just keep the apostrophe and try to make the build work correctly which could involve escaping the apostrophe with a backslash character in any paths?

Relevant to the issue, please find the error screenshot attached 
![error](https://user-images.githubusercontent.com/15185300/40835778-538b491a-658c-11e8-94a7-b59630c0eb0b.png)

Many thanks for any suggestions for resolving this.

**Comment by oehme** [comment]
Thanks for the follow-up :) This will have to be fixed on the IntelliJ side. IntelliJ generates an init script that refers to its own installation path and it'll need to quote the single-quote character so it becomes a valid String literal.

**Comment by amanijoseph87** [comment]
Is there a fix for this

**Comment by v1ra1** [comment]
I am also running into this issue cause my user is a money sign. $
![image](https://user-images.githubusercontent.com/8594476/141602641-a41f7135-0d95-44b8-aea9-374401a06e60.png)
