### ISSUE TITLE
Gradle should pass empty -sourcepath to javadoc (like it does for javac)

### ISSUE THREAD

**Issue by tbroyer** [gradle/gradle#5630]
### Expected Behavior
Javadoc shouldn't fail (or even warn) on source files that are not in the project (i.e. in third-party dependencies)

### Current Behavior
Javadoc warns, and in some times even fails (I believe in this case it's a bug in javadoc, but still), about source files that are actually packaged in third-party dependencies (i.e. present in the classpath); specifically here `com.google.gwt:gwt-user:2.8.2`.

<details>

```
./gradlew :compat:javadoc

> Task :compat:javadoc FAILED
/…/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.2/a2b9be2c996a658c4e009ba652a9c6a81c88a797/gwt-user-2.8.2.jar(com/google/gwt/event/shared/EventBus.java):24: error: cannot access EventBus
public abstract class EventBus extends com.google.web.bindery.event.shared.EventBus implements
                                                                          ^
  bad source file: /…/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.2/a2b9be2c996a658c4e009ba652a9c6a81c88a797/gwt-user-2.8.2.jar(com/google/web/bindery/event/shared/EventBus.java)
    file does not contain class com.google.web.bindery.event.shared.EventBus
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compat:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/…/gwt-events/compat/build/tmp/javadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
4 actionable tasks: 3 executed, 1 up-to-date
```

</details>

### Context

GWT libraries bundle their source files, these interfere with javadoc, the way it's currently configured.

This is actually similar to #414.

A workaround is to `addStringOption("sourcepath", "")` in the javadoc task.

### Steps to Reproduce (for bugs)

It happened to me at some point when working on https://github.com/gwtproject/gwt-events; but it can be reproduced at gwtproject/gwt-events@b2b3704f.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/a6n37nyfmakpa

**Comment by Glusk2** [comment]
This work-around does not work with:
https://github.com/nebula-plugins/gradle-aggregate-javadocs-plugin

**Comment by tbroyer** [comment]
Just tested, and yes it does: you need to apply the workaround to all Javadoc tasks in all projects and subprojects (the `aggregateJavadoc` task created by the plugin in the root project, and the `javadoc` tasks in all subprojects, as the plugin triggers their execution)
