### ISSUE TITLE
Unable to apply pluginManagement block from script plugin

### ISSUE THREAD

**Issue by edeesis** [gradle/gradle#5636]
If you have the pluginManagement block in a script plugin for Settings scripts, you're unable to apply it due to the following error:

Cause: startup failed:
script '<script loc>': 1: Only Settings scripts can contain a pluginManagement {} block.

See https://docs.gradle.org/4.7/userguide/plugins.html#sec:plugin_management for information on the pluginManagement {} block

 @ line 1, column 1.
   pluginManagement {
   ^

1 error

### Expected Behavior
I understand why it doesn't make sense for the pluginManagement block to be unavailable in a binary plugin, because you need that before you can resolve any dependencies, but a script plugin resolved from either the local filesystem or over HTTP does not use the repositories block or resolutionStrategy.

I propose that either it's allowed for script plugins to have the pluginManageent block, or create a new way to apply a similar methodology before the settings script is finished compiling.

### Current Behavior
Gradle can't process script plugins because only the raw settings.gradle file can have the pluginManagement block.

### Context
We have written a gradle plugin that is currently hosted in a private S3 bucket. 

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        mavenLocal()
        maven {
            url "s3://$s3_bucket"
            authentication {
                awsIm(AwsImAuthentication)
            }
        }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.namespace.startsWith('com.group')) {
                useVersion "1.0"
            }
        }
    }
}
```

Since we don't want to host our plugins on the Gradle Plugin Portal, we had to add the URL/authentication to every repository that uses our plugin.

We also have to specify which version of the plugin we're using in every single repo as well.
This requires us to copy and paste that block in every settings.gradle file.

### Steps to Reproduce (for bugs)
Create a script plugin that contains the pluginManagement block.
Attempt to apply that script plugin using `apply from:`

### Your Environment
Mac OSX
Gradle 4.7

**Comment by johndevs** [comment]
Any update on this? Any workaround other than manually merging the settings scripts?

**Comment by kasabov** [comment]
I believe you need to prefix the code in your external settings script with "settings.". This works for me:

_plugin-management.gradle_
```
settings.pluginManagement {
    repositories {
        String mavenLocalFolder = System.getProperty('maven.repo.local') ?: project.findProperty('maven.repo.local')
        if (mavenLocalFolder) {
            maven { url mavenLocalFolder }
        }
        maven { url 'https://my-company/artifactory/plugins-snapshot' }
    }
    plugins {
        id 'my-plugin' version "$myPluginVersion"
    }
}
```

_settings.gradle_
```
apply from: '/some/url/local/or/remote/plugin-management.gradle'
rootProject.name = 'my-project'
plugins {
    id 'my-plugin'
}
```

Note that _$myPluginVersion_ is still local to the project (defined in _gradle.properties_) and thus can be overridden at project's build time.

**Comment by renatoathaydes** [comment]
@kasabov that saved me big time, thanks mate.
