### ISSUE TITLE
Creating a task inside configureEach causes CME

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#5646]
```
tasks.configureEach {
  tasks.register("foo")
}
```

This is problematic when converting to use register() etc. as it's a standard pattern to dynamically derive tasks from other tasks, using things like `tasks.withType()`.

Fails with 4.9-20180605235937+0000.

**Comment by lacasseio** [comment]
It looks like this issue is a duplicate of https://github.com/gradle/gradle/issues/5708 (or the other way around). Regardless, it's already fixed in the release branch. Closing this issue as fixed.
