### ISSUE TITLE
TestKit not working with Kotlin Spring plugin

### ISSUE THREAD

**Issue by FWiesner** [gradle/gradle#5648]
### Expected Behavior
(opening this issue here as the Spring Kotlin plugin works nicely from regular builds, but causes issues with TestKit and I have no idea whether this is something to fix in Kotlin team's sub-plugin or in TestKit)
TestKit should be able to load the Kotlin sub-plugins like the compiler plugin for Spring Boot.

### Current Behavior
Please see this bug: https://github.com/gradle/kotlin-dsl/issues/913 that I originally had created against the Kotlin DSL, but then it turned out that also TestKit with Groovy DSL input is affected.

### Context
My current workaround is to manually open all my test-relevant Spring classes and not apply the Kotlin Spring plugin (which works nicely when not called from TestKit, but a regular build)

### Steps to Reproduce (for bugs)
add the Kotlin and Kotlin Spring plugins to a TestKit input

### Your Environment
Java 10
Gradle 4.7/4.8

**Comment by oehme** [comment]
The Kotlin subplugin mechanism should be replaced. It makes assumptions about the classloader hierarchy that don't hold under many circumstances. Instead Kotlin should use Gradle's normal plugin mechanism for extension.

**Comment by oehme** [comment]
Actually, there already is an open issue and I've commented on it: https://youtrack.jetbrains.net/issue/KT-24327
