### ISSUE TITLE
A compelling Gradle usability enhancement request

### ISSUE THREAD

**Issue by zxcware** [gradle/gradle#5652]
Hi team,

At the moment, given the following block, it's extremely difficult to reason what object are those 2 fields belong to, in other words, it's extremely difficult to reason the delegation object for a block, especially when the block is imported from an external plugin, even with the help of code completion feature in IDE.
```
blockName {
  field1 = value1
  field2 = value2
}
```

The pattern violates the predominant top-down(forward) reasoning pattern, which, in this case, given delegation object, think about its fields to use. It would be simplified a lot if the above block can be:
```
blockName(DelegationType delegationObject) {
  delegationObject.field1 = value1
  delegationObject.field2 = value2
}
```
In this way, the syntax of Gradle would be accepted much more quickly, for users can click the `DelegationType` to read the type document and explore fields by typing `delegationObject.`. Instead of, users are guessing if `field1` belongs to the `project` or the `delegationObject` every time.

I think forward reasoning is much simpler than backward reasoning, which is the current model adopted by Gradle. No matter how powerful it is, I saw many engineers reluctantly work on it because they don't want to be trapped in this guess-and-try game.

Best,
Zhixiong

**Comment by oehme** [comment]
I'm not sure how this would improve things, it just adds more noise. You can click on the blockName method to see it's delegate type. You can also click on every property to see what type it comes from.

That being said, if you absolutely want to write the type down again, you can.

```
blockName { DelegateType delegate ->

}
```
