### ISSUE TITLE
includeBuild has unexpected side effects on the "main" build

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#5669]
@cloviss commented on [Fri Jun 08 2018](https://github.com/gradle/gradle-native/issues/731)

_includeBuild_ changes the build behavior of the composite build, even if the included build has nothing be be built.

### Expected Behavior
"Each included build is configured and executed in isolation", as documented.

### Current Behavior
Using _includeBuild_ changes the build behavior of the "main" build (and eventually this build might fail).

### Steps to Reproduce (for bugs)
Unpack the attached file [foo.zip](https://github.com/gradle/gradle-native/files/2083790/foo.zip) and, in the directory _foo_, type _gradle compileJava_ . The build will fail.

Remove _includeBuild '../includedProject'_  from _foo\settings.gradle_. The build succeeds.

### Your Environment
gradle 4.7 and 4.8

    .
    ├───foo
    │   │   settings.gradle
    │   │
    │   └───app
    │           build.gradle
    │
    └───includedProject

_foo\settings.gradle_ contains only

    include 'app'
    includeBuild '../includedProject'

_foo\app\build.gradle_ downloads a file from github to use it as dependency

    apply plugin: 'java'
    ext.jgraphxVersion = '3.9.3'
    
    repositories {
        ivy {
            url 'https://github.com/'
            layout 'pattern', {
                artifact '/[organisation]/[module]/archive/v[revision].[ext]'
            }
        }
    
        flatDir {
            dirs "${buildDir}/unpacked/dist/jgraphx-${jgraphxVersion}/lib"
        }
    }
    
    configurations { jgraphx }
    
    dependencies {
        jgraphx "jgraph:jgraphx:${jgraphxVersion}@zip"
    
        implementation ":jgraphx:"
    }
    
    task unzipJgraphx(type: Copy) {
        from zipTree(file(project.configurations.jgraphx.asPath))
        into file("${buildDir}/unpacked/dist/")
    }

    tasks.compileJava.dependsOn unzipJgraphx

**Comment by oehme** [comment]
This build resolves dependencies at configuration time which is an error. Composite builds just highlight that problem more clearly, but it's always wrong.
