### ISSUE TITLE
Remove `TaskCollection.getAt()` from public API

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#5673]
This is a Groovy specific method that's leaked into the public API.  `getByName`, `named` and other APIs are a better choice.  

https://github.com/gradle/gradle/pull/5665/files#r193922399

**Comment by lacasseio** [comment]
To avoid broking anyone, would you suggest annotating with `@deprecated` the `TaskCollection.getAt()` and add leaving it on `DefaultTaskCollection`? Or are you suggesting we should also add deprecation warning when using `TaskCollection.getAt()` as well?

**Comment by big-guy** [comment]
We'd mark it deprecated on `TaskCollection`, eventually remove it, but leave it implemented in the underlying implementation classes.  When/if we ever remove `getByName(..)` then I would consider deprecating `getAt(..)` and/or returning a provider then.
