### ISSUE TITLE
Javadoc for Task should mention TaskProvider as a dependency type

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#5676]
The Javadoc of the `Task` interface is missing the mention of `TaskProvider` as a potential parameter to `dependsOn()`. `mustRunAfter()` and `shouldRunAfter()`. There's a list of the options both on the interface's Javadoc and also at the Javadoc of `dependsOn()` itself (we could perhaps have one list instead, too).

**Comment by lacasseio** [comment]
@lptr Do you want to code review this PR: https://github.com/gradle/gradle/pull/5863
