### ISSUE TITLE
gradle test --tests com.testname isn't passed to JUnit Platform

### ISSUE THREAD

**Issue by sksamuel** [gradle/gradle#5678]
### Expected Behavior
When gradle is launched with --tests the parameter should be sent to junit platform in the form of a `org.junit.platform.engine.DiscoveryFilter` so that test engine implementations can use it.

### Current Behavior
Instead --tests seems to activate the junit 4 test scan.

**Comment by oehme** [comment]
It does use a [Junit Platform filter](https://github.com/gradle/gradle/blob/master/subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestClassProcessor.java#L144).

**Comment by oehme** [comment]
Feel free to leave this open then, if it could be improved on our side to support engines better.

**Comment by sksamuel** [comment]
I'm in two minds now, because the discovery filters only allow you to filter by class and package. The post filters allow you to filter by test name. So in the case of richer test frameworks that allow nested tests, you'd have to use the post filters. I think maybe it should just be documented better from JUnits side.

**Comment by oehme** [comment]
Let's just add this to #4912.
