### ISSUE TITLE
Task 'asciidoctor' not found in project ':docs'.

### ISSUE THREAD

**Issue by daggerok** [gradle/gradle#5680]
for some reasons gradle asciidoctor (asciidoctor depending tasks) from docs subproject cannot be found on CI: you can check [Travis CI build (for example line 753) here](https://travis-ci.org/daggerok/findbugs-example/jobs/390220891#L753), as well as [GitLab CI build here](https://gitlab.com/daggerok/findbugs-example/-/jobs/73837294)

while locally on my mac os x from console everything is working as expected (any of these tasks executions):

```bash
./gradlew asci
./gradlew asciidoc
./gradlew asciidoctor
./gradlew documentation
./gradlew :docs:ascii
./gradlew :docs:asciidoc
./gradlew :docs:asciidoctor
./gradlew :docs:documentation
# ...
```

### Expected Behavior

tasks should execute successfully

### Current Behavior

any asciidoctor-related tasks couldn't be found on ci (tested on travis or gitlab, see links above)

### Context

I'm using same gradle build structure a lot, and this is start happening about 1-2 months ago...

### Steps to Reproduce (for bugs)

- clone repo and verify that locally build will be successful
   ```bash
   git clone https://github.com/gaggerok/findbugs-example
   ./gradlew documentation
   ```

- checkout provided ci builds outputs or push to travis/gitlab as own repo with same command you used locally and see failed build result with message `Task 'asciidoctor' not found in project ':docs'.`

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/keiwfipw7f5sk

actual repositories:
- [github](https://github.com/daggerok/findbugs-example)
- [absolutely same repo, but on gitlab](https://gitlab.com/daggerok/findbugs-example)

---
Regards,
Maksim

**Comment by daggerok** [comment]
I also previously opened issue on travis-ci project [here](https://github.com/travis-ci/travis-ci/issues/9641)

**Comment by daggerok** [comment]
Also opened issue for gitlab: https://gitlab.com/gitlab-org/gitlab-ce/issues/47655

**Comment by oehme** [comment]
Your build file is not called `build.gradle`, but `buIld.gradle` (upper case i). That's why it works on a case-insensitive system, but not on a case-sensitive one.

**Comment by daggerok** [comment]
Oh... I don't know how it's could happens...
@oehme, thanks for your attention!

---
Regards,
Maksim
