### ISSUE TITLE
Project.getProperties() forces configuration of all deferred configurables

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#5682]
### Expected Behavior
`Project.getProperties()` should return the properties without forcing premature configuration. This means, either return the deferred configurables in unresolved state, or do not return them at all.

### Current Behavior
As soon as any plugin calls `Project.getProperties()`, any deferred configurables are resolved and fail later when we attempt to configure them.

### Context
Trying to use the `gradle-credentials` plugin together with `maven-publish` (see also https://github.com/etiennestuder/gradle-credentials-plugin/issues/22)

### Steps to Reproduce (for bugs)

```gradle
plugins { id 'maven-publish' }
if (hasProperty("fail")) getProperties()
publishing { }
```
Run as `gradlew help` - passes; run as `gradlew help -Pfail=please` - fails

### Your Environment
Tested Gradle 4.7 and 4.8 - the behavior is consistent.

**Comment by oehme** [comment]
DeferredConfigurable is deprecated as of 4.8.

**Comment by ddimtirov** [comment]
If anybody has the same problem, it can be resolved by adding `enableFeaturePreview('STABLE_PUBLISHING')` to `settings.gradle`
