### ISSUE TITLE
Gradle wrapper gets confused when there are two distributions of the same Gradle version

### ISSUE THREAD

**Issue by ddimtirov** [gradle/gradle#5683]
### Expected Behavior
The [Gradle.gradleHomeDir](https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html#org.gradle.api.invocation.Gradle:gradleHomeDir) should return a directory storing the distribution specified in the `gradle-wrapper.properties`.

### Current Behavior
We are repackaging Gradle, adding an init script, and a few property files in the `init.d` directory.
Then the init script looks up the correct property file relative to `Gradle.gradleHomeDir` and applies it as project defaults (among other things).

As of Gradle 4.8 I noticed that if there is a Gradle 4.8 daemon running using the Gradle Inc. distribution and then I run a different built with wrapper pointing to the customized distribution, it downloads the custom distribution correctly, but decides to run on the daemon from the stock distribution, just picking up our init files.

We wouldn't care about this (as we are not patching Gradle), but the `Gradle.gradleHomeDir` returns the location cached dist of the Gradle Inc.'s distribution and then our property defaulting fails.

### Context
I replaced a nice API with classloader hackery - I shouldn't need to do it.
Bundling resources with init scripts should be supported scenario.

### Steps to Reproduce (for bugs)
1. Create 2 distributions of the same Gradle version. 
2. Create 2 gradle builds, pointing to different distributions and printing `gradle.gradleHomeDir` from the build
3. Run the builds - should print different directories, right now they print the same

### Your Environment
Gradle 4.8

**Comment by ddimtirov** [comment]
Actually I found a workaround - turns out that `gradle.startParameter.gradleHomeDir` returns a good value, so I can use that.

Still the behavior is confusing. If it is intentional, the difference should be made clear in the documentation.

**Comment by oehme** [comment]
This is intentional, you should not depend on the installation path. If your script wants to read a resource, use a path relative to initscript.sourceFile.

startParameter.gradleHomeDir is not public api.

**Comment by ddimtirov** [comment]
Understood, but `gradle.gradleHomeDir` - what is it supposed to be returning?

**Comment by oehme** [comment]
It's supposed to return the home that the daemon was started with, as it does.

See ScriptHandler for documentation.
