### ISSUE TITLE
If --tests matches no tests, none should be executed

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#5688]
### Expected Behavior

Running `./gradlew test --tests com.pany.TestClass` where `com.pany.TestClass` does not actually match an existing class in the project should fail the build process.

### Current Behavior

Running the `test` task for a non-existing test class silently runs all tests.

### Context

To better prevent against typos in the class name passed to the `--tests` parameter it would make more sense to fail the build rather than silently running all tests.

### Steps to Reproduce (for bugs)

You can use the Gradle project itself to reproduce:

    cd subprojects/wrapper
    ../../gradlew test --tests foo.bar
    [...]
    46 tests completed, 11 failed

Note that the fact I see failing tests here is irrelevant. What's relevant is that test do get executed at all despite `foo.bar` not matching any class.

### Your Environment

Tested with Gradle 4.6, 4.7, 4.8 and 4.9-20180607113442+0000 on Windows 10 64-bit.

**Comment by blindpirate** [comment]
This is not the expected behavior. Could you please provide a reproducible sample?

**Comment by sschuberth** [comment]
Isn't the example mentioned under "Steps to Reproduce (for bugs)" above good enough?

**Comment by blindpirate** [comment]
Can't reproduce with that steps. I tried Mac and Win 7:

```
# zhb @ bs-MacBook-Pro in ~/Projects/gradle/subprojects/wrapper on git:master o [16:21:00] 
$ ../../gradlew test --tests foo.bar
Parallel execution is an incubating feature.
> Task :wrapper:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wrapper:test'.
> No tests found for given includes: [foo.bar](--tests filter)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
282 actionable tasks: 6 executed, 276 up-to-date
```

![image](https://user-images.githubusercontent.com/12689835/41652619-2e631026-74b6-11e8-8780-1ea67f464919.png)

**Comment by sschuberth** [comment]
Interesting, I can still reproduce my issue with d56fd83963280067dfe5f14a22d8bd734a1da949 (the commit I had check out) and 370bb8675bbf93a74308db07a3023e74d218e507 (current master) in Git Bash (from Git for Windows). I also tried with `cmd.exe`, and I can reproduce it. Some more info:

```
------------------------------------------------------------
Gradle 4.9-20180607113442+0000
------------------------------------------------------------

Build time:   2018-06-07 11:34:42 UTC
Revision:     5fb5640bc78767aa40c940ced5a0bd12c43d0947

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 10 10.0 amd64
```

**Comment by rsivan** [comment]
I was about to file a similar bug, it happens here consistently (gradle 4.6, macos).

**Comment by blindpirate** [comment]
@rsivan Can you please share your steps to reproduce?

**Comment by rsivan** [comment]
just ran gradlew :Src:Tests:UITest:cleanTest :Src:Tests:UITest:test --tests "*PropertyTableFieldTest", with all variations of the wildcard before, after, both and none, in all cases all tests are run.
Note that the build.gradle filefor this module has a filter { includeTestsMatching('*Test') }, which I suspect overrides the command line flag (I was hoping it didn't)

**Comment by blindpirate** [comment]
@rsivan I'm sorry, run `:Src:Tests:UITest:cleanTest :Src:Tests:UITest:test --tests "*PropertyTableFieldTest"` on which project? If you mean your own project, I'm afraid I can't reproduce on my side.

**Comment by rsivan** [comment]
It should probably happen on any project where there is a filter such as  { includeTestsMatching('*Test') }, which covers, say, 5 test classes, but you want to just run one class with --tests while debugging a specific case.

**Comment by big-guy** [comment]
@sschuberth can you see if you're still seeing this problem and reopen this issue? On the tip of master (5.3-nightly), I don't see this behavior.

**Comment by sschuberth** [comment]
I cannot reproduce the issue anymore with Gradle 5.2.1. As expected I'm now getting "No tests found for given includes".
