### ISSUE TITLE
JavaFileManager is not closed after usage

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#5690]
JavaFileManager is not closed by org.gradle.api.internal.tasks.compile.JdkJavaCompiler after compilation is done. This seems to be an issue with JDK8, I am not sure if JDK9+ has the same problem.

Typically, not closing the `JavaFileManager` has no consequences, because javac will close all jars from the classpath it opens. However, if an empty jar is in the classpath, it will use `ZipFile` to load the entries, and it will not close the file after usage.

To verify the issue, run the following on Windows (this is roughly what JdkJavaCompiler is doing):
```
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.jar.JarOutputStream;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;

public class Main {
  public static void main(String[] args) throws IOException {
    Path dir = Files.createTempDirectory("repro");
    Path emptyLib = dir.resolve("lib.jar");
    try (JarOutputStream jos = new JarOutputStream(Files.newOutputStream(emptyLib))) { }

    List<String> options = new ArrayList<>();
    options.add("-cp");
    options.add(emptyLib.toString());

    Path src = Files.write(dir.resolve("Main.java"), "public class Main {}".getBytes());
    JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
    StandardJavaFileManager fc = compiler.getStandardFileManager(null, null, null);
    Iterable<? extends JavaFileObject> fileObjects = fc.getJavaFileObjects(src.toFile());

    compiler.getTask(null, fc, null, options, null, fileObjects).call();
    Files.delete(emptyLib);
  }
}
```

**Comment by oehme** [comment]
This is already fixed on master. Btw java will keep all jars open by default, I also had to add a hack to clear out the zip file index cache.

**Comment by oehme** [comment]
See https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/ResourceCleaningCompilationTask.java

**Comment by gavra0** [comment]
Looks great, thanks!
