### ISSUE TITLE
Gradle 4.8 no longer considers versions equal when using dependencySubstitution and failOnVersionConflict

### ISSUE THREAD

**Issue by atorok** [gradle/gradle#5692]
### Expected Behavior
Depending on both a sub-project  and something which is substituted to the same sub-project triggers a failure when the configuration is configured with `failOnVersionConflict`. This only happens with Gradle 4.8.

### Current Behavior
The dependency resolutions should succeed just like in 4.7

### Context
The [elastic/elasticsearch] build uses `failOnVersionConflict` and substitutions to be able to build some sub-projects (also) stand-alone.  We encountered this issue trough a chain of transitive dependencies, much less obvious than the example below. 

### Steps to Reproduce (for bugs)
```
git clone git@github.com:atorok/gradle4.8_dependencySubstitution_failOnVersionConflict_reproduce.git
./gradlew assemble 
```
this fails with:
```
* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > A conflict was found between the following modules:
      - gradle_test:sub1:0.0.1
      - gradle_test:sub1:0.0.1
```

### Your Environment
 - https://gradle.com/s/n2eopjnp2bx5a fails with 4.8
 - https://gradle.com/s/rkmntk62zdyow works with 4.7

**Comment by ljacomet** [comment]
Thanks for the report and reproducible test case.
Looks like some refactoring around dependency management made a shortcut disappear which was handling modules having the exact same version.
