### ISSUE TITLE
Project dependencies work in Eclipse but not commandline gradle build

### ISSUE THREAD

**Issue by fil512** [gradle/gradle#5693]
### Expected Behavior
si-dao project compiles because classes from si-core are on the classpath at compilation time

### Current Behavior
both projects compile without errors in Eclipse.  .classpath is being generated by the Eclipse gradle plugin and when I check the Build Path in Eclipse, I see the project dependency there.

When I build commandline with gradle build, the compilation of si-dao produces a long string of errors of missing classes (classes that are in si-core)

### Your Environment
Eclipse Oxygen
Buildship 2.2.1 (Gradle plugin)
Gradle 4.7

build.gradle file:

```
buildscript {
       ext {
             springBootVersion = '2.0.2.RELEASE'
       }
       repositories {
             mavenCentral()
       }
       dependencies {
              classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
       }
	}

subprojects {
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'jdepend'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'
	
    group = 'com.kenstevens.stratinit'
    version = '1.2.0-SNAPSHOT'
    sourceCompatibility = 1.8
    
    repositories {
    	mavenLocal()
        mavenCentral()
    }
    
    dependencies {
       compile 'org.springframework.boot:spring-boot-starter'
       compile 'org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final'
       compile 'dijkstra-java:rollerjm-graphs:1.0'
       compile 'com.google.guava:guava:25.1-jre'
       testCompile 'org.springframework.boot:spring-boot-starter-test'
    }
}

project(':si-core') {
}

project(':si-dao') {
    dependencies {
        compile project(':si-core')
    }
}
```

**Comment by fil512** [comment]
Here is my settings.gradle:

```
rootProject.name = 'si-master'

include 'si-core', 'si-dao'
```

**Comment by fil512** [comment]
I was able to resolve this by changing:
 apply plugin: 'java'
to 
 apply plugin: 'java-library'

I would love to understand why dependencies work for java-library but not java...

**Comment by oehme** [comment]
There should be no difference. Can you please provide a reproducible sample project?

**Comment by ghale** [comment]
I'm closing this for now.  If you feel there is still an issue that needs to be addressed, please provide a sample that reproduces the problem.
