### ISSUE TITLE
Can no longer configure GenerateMavenPom tasks in 4.8, works in 4.7

### ISSUE THREAD

**Issue by atorok** [gradle/gradle#5696]
### Expected Behavior
Changing the destination of the generated pom should work as documented:
```
generaatePomFileForMavenJavaPublication {
    destination = file("$buildDir/test.pom")
}
```
or 
```
tasks.withType(GenerateMavenPom.class) {
    destination = file("$buildDir/test.pom")
}
```
https://docs.gradle.org/4.8/userguide/publishing_maven.html

### Current Behavior
The documented version doesn't work in neither 4.7 nor 4.8. 
`withType` no longer works in 4.8.

### Context
Our build always generates the pom files, and sometimes bundles them to jars, or hands them over to be published ( publishing to the repo is  not done with Gradle ). 

### Steps to Reproduce (for bugs)
See https://github.com/atorok/gradle4.8_publishing_generate_pom_only_reproduce

``` 
git clone git@github.com:atorok/gradle4.8_publishing_generate_pom_only_reproduce.git
cd gradle4.8_publishing_generate_pom_only_reproduce
./gradlew clean generatePomFileForMavenJavaPublication
```

Proof that it works with 4.7:
```
[:~/work/elastic/gradle4.8_publishing_generate_pom_only_reproduce] % sed  -i 's/4\.[0-9]/4.7/'  gradle/wrapper/gradle-wrapper.properties
[:~/work/elastic/gradle4.8_publishing_generate_pom_only_reproduce] % ./gradlew clean generatePomFileForMavenJavaPublication
> Task :clean
> Task :generatePomFileForMavenJavaPublication

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
[:~/work/elastic/gradle4.8_publishing_generate_pom_only_reproduce] % find -name *.pom -o -name *.xml
./build/test.pom
[:~/work/elastic/gradle4.8_publishing_generate_pom_only_reproduce] % sed  -i 's/4\.[0-9]/4.8/'  gradle/wrapper/gradle-wrapper.properties
[:~/work/elastic/gradle4.8_publishing_generate_pom_only_reproduce] % ./gradlew clean generatePomFileForMavenJavaPublication
> Task :clean
> Task :generatePomFileForMavenJavaPublication

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
[:~/work/elastic/gradle4.8_publishing_generate_pom_only_reproduce] % find -name *.pom -o -name *.xml
./build/publications/mavenJava/pom-default.xml
```

### Your Environment
 * Build scan URL 4.8: https://gradle.com/s/sii2itr3j6a7o 
 * Build scan URL 4.7: https://gradle.com/s/2xpwdr3ssyon2

Seems like @oehme  made some changes in the plugin that could be relevant.

**Comment by atorok** [comment]
Can be worked around with:
```
project.getGradle().getTaskGraph().whenReady {
    tasks.withType(GenerateMavenPom.class) {
        destination = file("$buildDir/test.pom")
    }
}
```

**Comment by oehme** [comment]
We'll remove this example from the docs. Why do you want to change the location? I can't imagine a good use case for that, but maybe you can help.

Your first example will work btw if you activate the stable publishing feature (which a deprecation warning in 4.8 should be telling you to do). The second example doesn't work because your `withType` hook runs before our logic that sets the defaults, so your value is overwritten. This is a general problem with setting defaults that we'll fix in a cross-cutting way soon.

**Comment by atorok** [comment]
We want the build to produce the  `.pom` files right besides the `.jar`. 
Can you reference a ticket for this please:

>  This is a general problem with setting defaults that we'll fix in a cross-cutting way soon.

**Comment by oehme** [comment]
I created https://github.com/gradle/gradle/issues/5704

**Comment by atorok** [comment]
I just tested with `enableFeaturePreview('STABLE_PUBLISHING')` but  I did not see it make any  difference.

**Comment by oehme** [comment]
As I said, the first example (getting by name) will work, not the second. You have a type in there btw, make sure that's not in your real code.

**Comment by atorok** [comment]
Indeed it was the typo, thanks @oehme !
