### ISSUE TITLE
Plugin Publishing Plugin not publishing multiple plugins

### ISSUE THREAD

**Issue by Sanne** [gradle/gradle#5697]
### Expected Behavior
The DSL for the `Plugin Publishing Plugin` has a `plugins` section which suggests I can declared multiple plugins.

Executing:

     ./gradlew publishPlugins

Should result in all declared plugins to be published.

### Current Behavior
Executing:

     ./gradlew publishPlugins

Results in only one of the plugins to be published on the plugins portal.

### Context
I'm developing a *couple* of OSS plugin to build custom WildFly servers.
I've structured it as two plugins yet they share a lot of code - I expect people to often use both but not necessarily.
 - https://github.com/wildfly/wildfly-gradle-tools

It can be found on the portal as both:
 - https://plugins.gradle.org/plugin/org.wildfly.build.provision
 - https://plugins.gradle.org/plugin/org.wildfly.build.featurepack

### Steps to Reproduce (for bugs)
Please see this section of my build:
 - https://github.com/wildfly/wildfly-gradle-tools/blob/master/build.gradle#L61-L79

### Your Environment
 * Build scan URL: https://gradle.com/s/jg2aj6vjnn3uq

_Thanks very much for the plugin portal, other than this minor issue it's a real pleasure to use!_

**Comment by oehme** [comment]
You used the [same name](https://github.com/wildfly/wildfly-gradle-tools/blob/master/build.gradle#L68) twice.

**Comment by Sanne** [comment]
awesome, thanks @oehme !
