### ISSUE TITLE
Dependency won't pass to next repository on failure

### ISSUE THREAD

**Issue by scphantm** [gradle/gradle#5702]
We just upgraded several of our projects to 4.7 and things have been blowing up all over the place, to the point where many of our projects were forced to downgrade back to 4.2.  I just read that you changed the behavior in 4.3 so that if a dependency repository returns an error, it fails the build instead of falling thru to the next repository in the stack.  

https://docs.gradle.org/4.3/release-notes.html?_ga=2.219243034.208527151.1528888504-1998248491.1525192646#avoid-checking-other-repositories-when-dependency-resolution-in-one-repository-fails

I need a way to renable the old logic.  Our problem is that due to our firewall and internal security scanning systems, our artifactory server's connection to the internet is, shall we say, unstable.  It constantly gets false hits on our on the wire bug and virus scanner.  When it does get a  hit, the scanner nukes the network connection, giving artifactory a timeout error.  This in turn gets to the client as a failed connection, and now gradle fails the build.

Now, with 4.2, this was no problem because gradle would just move on to the next repository and try downloading the file from another remote repo in artifactory, usually succeeding.  But, now with this change, builds are blowing up all over the place

### Expected Behavior
I get how people would want it fail, i really can see that argument.  But at the same time this has damn near crippled us.  I need some kind of setting that i can put in the build file to say, if there's an error, move to the next repo.  Even a code snippet that i can plug into our enterprise level plugins to override the error handling would be fine.  I need something to kick this thing hard enough to move to the next repo on a failure.  The way our systems work, its very common for the first repo to fail, very rare for all 20 or so to fail.

### Current Behavior
as per the link above, this logic was changed in 4.3 to fail the build on connection failure pulling down dependencies

### Context
We have so many security scanners listening over the wire and various other tooling managing internet connections, that we constantly get dropped connections.  Its a way of life here.  Most systems we run handle the connection drops in stride, this one did, until we upgraded to 4.7

### Your Environment
happens on all environments we run, win7, win10, mac.

**Comment by oehme** [comment]
That would mean non-reproducible builds, giving you potentially different/untrusted artifacts depending on the environment. See #4629 for a solution that I think would be more appropriate. Would that be a good solution for you?

**Comment by scphantm** [comment]
It may help some cases.  but unfortunately if our system gray flags a site because of a hack, or ddos, or their coffee is at 154 degrees instead of 157, its gray flagged for hours/days/weeks.  retrys won't help, it has to fall thru to the next repo in the chain to try from a different site.

im limited on how i can fix it with artifactory, and changing the order of the repos in my init.gradle is out of the question because i would need a FTE who's whole job is updating and redistributing the file that holds that info, day in and day out.

Is there a way where i can inject my own error handler into that method?  nothing about my network and associated security systems is typical so i imagine the number of people with this problem is limited.  but if i had a way to inject my own error handler via my corp JVM plugin we use across the board, that would solve my problem.

**Comment by oehme** [comment]
I'm not sure I understand the situation - Why can't you shield your build from external outages using your internal Artifactory instance? I.e. your build has exactly one repo (your artifactory mirror) and Artifactory takes care of holding everything you need inside your organization instead of Gradle trying to get things from the internet. 

No, there is no way to change this error handling at the moment.

**Comment by scphantm** [comment]
because due to issues outside my control, i don't have one repo, i have close to 20.  gotta be pushing close to 70 if you count the remotes individually, and i believe around 18 local repos.  We tried one repo to rule them all in the very early days of the implement, but things went bad within minutes for a variety of reasons.  I have to keep things separate and in specific orders.

like i said, im limited on how i can fix it with artifactory

**Comment by oehme** [comment]
Alright so you have plenty of repos in Artifactory. Still that should shield you from outside failures by mirroring. So why does that not work out?

**Comment by ljacomet** [comment]
The change is to improve reproducibility and will stay.

Alternatives are to hide this with a proxy repository, or have conditional repository declarations depending on the network / work environment.
