### ISSUE TITLE
CopySpec with absolute "from" resolves differently on windows and linux

### ISSUE THREAD

**Issue by cfraenkel** [gradle/gradle#5703]
Copy and Distribution tasks behave differently on linux and windows if the `from` statement (incorrectly) contains an absolute path (beginning with "/"). On windows this is resolved against `$projectDir` while on linux this is resolved against `/`

### Expected Behavior

Gradle on windows should resolve absolute paths against the root of the current drive.

### Current Behavior

Gradle on windows currently resolves absolute paths against the project directory.

### Context

Builds produce different results when run on windows and linux.

### Steps to Reproduce (for bugs)

The issue can be reproduced with the following build file
```
task copyTask(type: Copy) {
   from '/'
   include 'build.gradle'
   destinationDir = file("$buildDir")
   doLast {
      println outputs.files.files
   }
}
defaultTasks 'copyTask'
```
### Your Environment

 * Build scan URL: 
[Linux](https://scans.gradle.com/s/gojg6sgdwfhbe)
[Windows](https://scans.gradle.com/s/5iqz24fs5arhk)

**Comment by oehme** [comment]
`/` is not an absolute path on Windows.

**Comment by cfraenkel** [comment]
Is there maybe a way to warn the user / developer that they are writing non-portable build scripts when they begin their from with "/"?
