### ISSUE TITLE
Property.map {} types do not carry task dependencies when used as inputs to another task

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#5706]
Related issue: https://github.com/gradle/gradle/issues/3811

Since file system outputs are the best way to propagate information forward in a build, it would be very useful to allow them to be passed in as inputs to other task types that make use of https://docs.gradle.org/current/userguide/lazy_configuration.html .

### Expected Behavior

Task dependencies that built the output should be carried with it and provide implicit dependencies.

### Current Behavior

`dependsOn` is still required, and outputs cannot be wired into other tasks with whatever type they have.

### Context

Trying to make use of lazy task APIs and be able to wire mapped outputs as inputs to another task. For now, these are all tasks defined outside of Gradle itself until https://github.com/gradle/gradle/issues/4224 is resolved.

### Steps to Reproduce (for bugs)

```kotlin
tasks {
  "wrapper"(Wrapper::class) {
    gradleVersion = "4.8"
  }
}

open class Producer : DefaultTask() {
  @get:Input
  var text: String = "hello"

  @get:OutputFile
  val outputFile: RegularFileProperty = newOutputFile()

  @TaskAction
  fun writeFile() {
    outputFile.get().asFile.writeText(text)
  }
}

open class ShowThing : DefaultTask() {
  @get:Input
  val inputText: Property<String> = project.objects.property()

  @TaskAction
  fun showText() {
    println("Printing text: ${inputText.get()}")
  }
}

tasks {
  val prod by creating(Producer::class) {
    outputFile.set(layout.buildDirectory.file("myfile.txt"))
  }
  val show by creating(ShowThing::class) {
    inputText.set(prod.outputFile.map { it.asFile }.map { it.readText() })
  }
}
```

Run `./gradlew show` and see only the `show` is executed, not both `prod` and `show`.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/m7mdvcmqjz7n2

**Comment by JLLeitschuh** [comment]
#6363 has several examples that expand upon what @mkobit has above.

**Comment by adammurdoch** [comment]
Some support for this added via #6722. The support handles only file type properties, as these are the only kinds of buildable things that Gradle currently understands. I think we should close this issue as done, and add new issues that cover support for other kinds of properties.

**Comment by JLLeitschuh** [comment]
Are all of the use cases I covered in #6363 handled now?

**Comment by adammurdoch** [comment]
I think they already were, just not necessarily with the pattern you wanted to use. This hasn't changed, there's no `flatMap()` method yet.

**Comment by adammurdoch** [comment]
More fixes and a `flatMap()` method added via https://github.com/gradle/gradle/pull/6775.

I'm going to close this issue. Please open new issues for any further changes/improvements/fixes we should make.
