### ISSUE TITLE
Project fails to build, but then succeeds after a clean

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#5707]
I was encouraged to come here via Twitter: https://twitter.com/AutonomousApps/status/1002228362780164097

### Expected Behavior
Project should not require a clean to successfully build.

### Current Behavior
Project fails, but then succeeds when the gradle command is re-run with the addition of the word "clean".

### Context
It's been a huge productivity suck, cumulatively, being forced to clean all the time.

### Steps to Reproduce (for bugs)
Here's an example of a build that failed, but succeeded after a clean:

Failed: https://gradle.com/s/aqui4ld3g6msq
Succeeded after clean: https://gradle.com/s/avzm75glmwatk

Unfortunately, my project is proprietary, so I cannot easily share source code.

### Your Environment
Ubuntu 16.04, System76 Oryx Pro. Android Studio 3.1.2, Gradle 4.8.

**Comment by oehme** [comment]
Looks like a bug in the Kotlin plugin. But without a reproducible example it'll be hard to do anything about it.

**Comment by autonomousapps** [comment]
I hear you about reproducibility. I was hoping that the build scans would be useful. If there's anything I can do to help, let me know.

A pretty old version? I just double-checked, and the scan indicates I'm on 1.2.50. Isn't that the latest? I just updated it yesterday.

**Comment by oehme** [comment]
Sorry, I misread. Yes 1.2.50 is the latest.

**Comment by oehme** [comment]
@yanex @h0tk3y I've heard the same complaint from several people at DroidCon. Kapt doesn't seem to be safe incrementally. Could you please look into this?

**Comment by big-guy** [comment]
Please reopen if this is really a Gradle bug, but for now I'll assume it's a Kotlin/kapt problem.
