### ISSUE TITLE
Using project.tasks.withType sometimes leads to Concurrent Modification Exception.

### ISSUE THREAD

**Issue by rajnx** [gradle/gradle#5708]
### Expected Behavior
When using project.tasks.withType() { } in gradle plugin build should run successfully without any exception.

### Current Behavior
When using project.tasks.withType() { } in gradle plugin build is throwing Concurrent Modification Exception. Seems fix for this is already done in 4.9RC1.

https://github.com/gradle/gradle/pull/5587

Can we get this fix imported in 4.8.1 as well?

**Comment by oehme** [comment]
@big-guy Can you backport the fix to 4.8.1?

**Comment by lacasseio** [comment]
We will backport the fix from [this PR](https://github.com/gradle/gradle/pull/5587).

**Comment by lacasseio** [comment]
My bad, I forgot to close this issue.
