### ISSUE TITLE
Changing deprecated 'task wrapper(type: Wrapper)' to `wrapper` skips subprojects

### ISSUE THREAD

**Issue by bmalinowsky** [gradle/gradle#5717]
Gradle 4.8 issues the following warning: "Creating a custom task named 'wrapper' has been deprecated and is scheduled to be removed in Gradle 5.0. You can configure the existing task using the 'wrapper { }' syntax [...]" 

Therefore, I changed `task wrapper(type: Wrapper)` to `wrapper` in build.gradle inside a `allprojects` block.

### Expected Behavior

Calling `./gradlew wrapper` should update all subprojects referenced in `settings.gradle` to the correct version specified by `gradleVersion`.

### Current Behavior

Calling the `wrapper` task only updates the root project, subprojects stay with the old version. Specifically, 
* gradle-wrapper.properties of root is updated to 4.8
* gradle-wrapper.properties of subprojects stay at 4.7

### Context

The wrapper is used to keep the root project and all subprojects in sync to use the gradle version as specified by `gradleVersion`. This worked until now using `task wrapper(type: Wrapper)`, it does not work any longer when addressing the deprecation warning and using `wrapper`.

### Steps to Reproduce (for bugs)

Change `task wrapper(type: Wrapper)` to `wrapper` in an allprojects block.

### Your Environment

------------------------------------------------------------
Gradle 4.8
------------------------------------------------------------

Build time:   2018-06-04 10:39:58 UTC
Revision:     9e1261240e412cbf61a5e3a5ab734f232b2f887d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          9 (Oracle Corporation 9+181)
OS:           Mac OS X 10.13.5 x86_64

My build.gradle file: https://github.com/calimero-project/calimero.parent/blob/master/build.gradle

**Comment by oehme** [comment]
Subprojects shouldn't have wrapper properties. Subprojects are not supposed to be run by themselves.
