### ISSUE TITLE
gradle build --scan error-reporting URL is invalid

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#5718]
If Gradle 4.8 encounters an exception when trying to publish a build scan, it display an error-reporting URL, but that URL is invalid:

    Please report this problem via https://gradle.com/scans/help/plugin and include the following via copy/paste:

**Comment by etiennestuder** [comment]
You are correctly redirected to https://gradle.com/help with further directions how to report your issue (forum or email).
