### ISSUE TITLE
Native build not honoring platform operating system setting

### ISSUE THREAD

**Issue by djdominguez** [gradle/gradle#5720]
I have a native build configured for with multiple platforms (Linux and Windows).  On Linux it does the right thing by only building Linux binaries.  But on Windows it will attempt to build Linux binaries as well and fail because it cannot find the compiler.

This is a regression that started in gradle 4.6.  I've confirmed that the behavior behavior is working as expected with gradle 4.5.1. 

### Expected Behavior

The build should succeed on Windows.

### Current Behavior

The build fails for gradle 4.6+

### Context

I'm unable to upgrade beyond gradle 4.5.1

### Steps to Reproduce (for bugs)

Run `gradle build` on attached project.  There is also a console.log file with my output.
[gradle-test.zip](https://github.com/gradle/gradle/files/2107391/gradle-test.zip)

### Your Environment

```------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 10 10.0 amd64

```
Also, this build is configured for a TDM-GCC compiler, but I don't think the actual compiler matters.  You can change it to point to any C++ compiler.

**Comment by lacasseio** [comment]
Issue moved to [gradle/gradle-native #735](https://github.com/gradle/gradle-native/issues/735) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lacasseio** [comment]
Thanks for reporting this. All native work has now his [dedicated repository found](https://github.com/gradle/gradle-native), any native issues should be open on that repository.

We don't expect a regression after 4.6, we will look at this specific case and comment on the other issue.

**Comment by djdominguez** [comment]
Sounds good.  Thank you.  I'll be sure to use the dedicated repository in the future if necessary.
