### ISSUE TITLE
I get an exception when I use java 10.0.1 to execute the command.

### ISSUE THREAD

**Issue by chsungyesuzuki** [gradle/gradle#5723]
### Expected Behavior
Expected Behavior:
I am using Minecraft Forge Mdk. Under normal conditions, the command prompt interface should show Build successful and I can decompile my Minecraft. Then I can develop a Mod for Mincraft.

### Current Behavior
Current Behavior:
I got an Exception, suggesting that I could not determine java version from '10.0.1'.

### Context
Context:Now that I can't build decompilation environments, I can't decompile my Minecraft, let alone develop a Minecraft mod.

### Steps to Reproduce (for bugs)
I follow the steps on this site:
https://fmltutor.ustc-zzzz.net/1.1-%E9%85%8D%E7%BD%AE%E4%BD%A0%E7%9A%84%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83.html

### Your Environment
The Minecraft Forge Mdk use gradle 1.7. I use Java 10.0.1.
 * Build scan URL:

**Comment by oehme** [comment]
Gradle 1.7 is way too old. The latest is 4.8.
