### ISSUE TITLE
war plugin does change behaviour of Copy task

### ISSUE THREAD

**Issue by Werzi2001** [gradle/gradle#5732]
### Expected Behavior

- `Copy` task working the same no matter if `war` plugin is applied or not
- `Copy` task should only copy files from target into destination without removing already existing from destination

### Current Behavior

- `Copy` task working differently (in an incorrect way) if `war` plugin is loaded
- `Copy` task removes already existing files from destination (only on first run and only if `war` plugin is applied)

### Context

- The `Copy` task is used as part of a bigger build but doesn't create the correct result
- Therefore the whole build fails on a business level although Gradle says "success"

### Steps to Reproduce (for bugs)

- Use this build: [abc.tar.gz](https://github.com/gradle/gradle/files/2115100/abc.tar.gz)
- Be sure to use a clean extract of the archive for each test as the error only seems to occur as long as the `.gradle` directory doesn't exist (so usually only on first run)
- The build contains the simple `abc` task which basically just copies files from a `from` directory into the `dest` directory within the build directory. The `dest` directory already contains files/subdirectories that are created by other tasks in the real build.
- Run the task using `./gradlew abc` and the `dest` directory only contains the files from `from`. The already existing files in `dest` are removed. Basically the `Copy` does replace the `dest` directory by the `from` directory.
- If you remove the `war` plugin before running the `abc` task it works as expected (files are copied to `dest` and existing content of `dest` remains)

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/umed7axdh3xha

**Comment by Werzi2001** [comment]
I did some further debugging and could track it down until the `lifecycle-base` plugin. So when using `lifecycle-base` instead of `war` plugin it happens also. I had a look at the code of `lifecycle-base` plugin but could not find anything that should cause something like that.

**Comment by Werzi2001** [comment]
Sorry should not have been closed.

**Comment by wolfs** [comment]
@Werzi2001 Thank you for the report. Gradle will clean up files in the destination directory if it doesn't know how they have been produced. So the copy task determines that the `dest` directory already exists, and there are files in there which have not been produced by Gradle (not declared as outputs of other tasks). Therefore, it cleans up the directory first before executing the copy task.

This also only happens with a clean `.gradle` directory, since on the first run of the `Copy` task Gradle determines that it produced the directory `dest`, so the next time it runs it won't try to clean it up.

If the contents of the `dest` directory are produced by other tasks in your build, then those tasks need to declare the files as there outputs. Even better, have the files produced in a different location and then use the `Copy` task to copy them all to the `dest` dir.

**Comment by Werzi2001** [comment]
@wolfs Thanks very much for your response. Clearing the destination of unknown output makes sense but I didn't manage to get the outputs declaration to work (yes the files are generated by other tasks). This is such a task:
```
// task that copies all plugins to plugins directory based on plugin configuration
task extractPugins(dependsOn: [configurations.plugin]) {
	doLast {
		// process all files from plugin configuration
		for (def file : configurations.plugin.files) {
			// extract file
			copy {
				from zipTree(file)
				into "$buildDir/plugins"
				exclude '**/META-INF/**'
			}
		}
	}
}
```

I tried adding
```
outputs.dir("$buildDir/plugins")
```
to the task that that didn't work (directory still gets wiped).

Could you give me a hint on how to do it properly? I don't think I can work with a Copy-Task here, can I?

**Comment by Werzi2001** [comment]
@wolfs Could you please give me further feedback? Otherwise I'll have to create a new bug as it doesn't seem to work.

**Comment by wolfs** [comment]
How did you declare the outputs? Outside or inside of the `doLast` block? They should be declared outside.

A copy task should also work, you can do something like:

```groovy
task extractPugins(type: Copy, dependsOn: [configurations.plugin]) {
    from {
        configurations.plugin.files.collect { fileTree(it) }
    }
    into "$buildDir/plugins"
    exclude '**/META-INF/**'
}

**Comment by Werzi2001** [comment]
@wolfs 
I had it within the `doLast` block. Outside of it it seems to work fine. Thanks a lot.
