### ISSUE TITLE
Gradle blocks and freezes in EndPointQueue.take and never finishes when running tests

### ISSUE THREAD

**Issue by mvysny** [gradle/gradle#5737]
Having a specially crafted project with a reusable module with tester classes, running JUnit5 tests on such project will (dead)lock/block Gradle in
```
epollWait:-1, EPollArrayWrapper (sun.nio.ch)
poll:265, EPollArrayWrapper (sun.nio.ch)
doSelect:92, EPollSelectorImpl (sun.nio.ch)
lockAndDoSelect:89, SelectorImpl (sun.nio.ch)
select:100, SelectorImpl (sun.nio.ch)
select:104, SelectorImpl (sun.nio.ch)
read:178, SocketConnection$SocketInputStream (org.gradle.internal.remote.internal.inet)
fill:139, Input (com.esotericsoftware.kryo.io)
require:159, Input (com.esotericsoftware.kryo.io)
readByte:255, Input (com.esotericsoftware.kryo.io)
readByte:80, KryoBackedDecoder (org.gradle.internal.serialize.kryo)
read:63, InterHubMessageSerializer$MessageReader (org.gradle.internal.remote.internal.hub)
read:52, InterHubMessageSerializer$MessageReader (org.gradle.internal.remote.internal.hub)
receive:79, SocketConnection (org.gradle.internal.remote.internal.inet)
run:263, MessageHub$ConnectionReceive (org.gradle.internal.remote.internal.hub)
onExecute:63, ExecutorPolicy$CatchAndRecordFailures (org.gradle.internal.concurrent)
run:46, ManagedExecutorImpl$1 (org.gradle.internal.concurrent)
runWorker:1135, ThreadPoolExecutor (java.util.concurrent)
run:635, ThreadPoolExecutor$Worker (java.util.concurrent)
run:55, ThreadFactoryImpl$ManagedThreadRunnable (org.gradle.internal.concurrent)
run:844, Thread (java.lang)
```

When I debug the tests in Intellij (debug `./gradlew umn-sync-tester:test` and place a breakpoint into `GlobalLogClientTestBattery.kt` file line 25 `client.close()`), it can be seen that the tests were run, but Gradle deadlocks afterwards.

### Expected Behavior
Gradle should run the tests and finish successfully.

### Current Behavior
Gradle blocks in some internal code and never finishes.

### Context
I'm trying to declare a suite of test classes for a Client interface, which then can be applied to various client class implentations.

### Steps to Reproduce (for bugs)
1. `git clone https://gitlab.com/mvysny/umn`
2. `cd umn`
3. `git checkout gradle_deadlock_bug`
4. `./gradlew`

The build will freeze when running tests from `umn-sync-tester`.

### Your Environment
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)

Ubuntu 18.04 x86-64

gradle wrapper 4.8

Also reproducible on openjdk-8

**Comment by mvysny** [comment]
Bump? You can reproduce the issue very simply on the attached project, simply
[umn.zip](https://github.com/gradle/gradle/files/2481963/umn.zip)
 by running `./gradlew umn-sync-server:test`. Note that the test doesn't freeze when run from Intellij.

**Comment by mvysny** [comment]
[test_executor_1.stack.txt](https://github.com/gradle/gradle/files/2482036/test_executor_1.stack.txt)
It can be seen that the Gradle worker is hung on `executor.shutDown()` which is blocked in Gradle `EndPointQueue.take`.

**Comment by mvysny** [comment]
[stdout.txt](https://github.com/gradle/gradle/files/2482051/stdout.txt)

**Comment by marcphilipp** [comment]
You mean `./gradlew umn-sync-tester:test`, right?

**Comment by mvysny** [comment]
@marcphilipp that too as well; I've made the `umn-sync-server:test` to be as simple as possible so it may be easier to debug that one. ps: Thank you so much for looking into this issue!

**Comment by marcphilipp** [comment]
Is this there anything special about `com.gitlab.mvysny.umn.sync.tester.MVStoreGlobalLogTest`?

**Comment by marcphilipp** [comment]
```
$ ./gradlew :umn-sync-server:test
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Project 'umn-sync-server' not found in root project 'umn'. Some candidates are: 'umn-sync-tester'.
```

**Comment by mvysny** [comment]
> Is this there anything special about `com.gitlab.mvysny.umn.sync.tester.MVStoreGlobalLogTest`?

Not really, it uses a very quick on-disk database. In fact replacing that suite with just one blank test will still make Gradle freeze:

```kotlin
package com.gitlab.mvysny.umn.sync.tester
import com.github.mvysny.dynatest.DynaTest
class MVStoreGlobalLogTest : DynaTest({
    test("Empty") {}
})
```
Deleting `MVStoreGlobalLogTest` will actually make Gradle freeze in `InMemoryGlobalLogTest`.
Now the interesting thing is that when you comment out the `globalLogClientTestBattery { log.newClient() }` call in `InMemoryGlobalLogTest`, the suite passes. So the issue seems to be with the `globalLogClientTestBattery()` extension method. However, if you replace that extension method simply with a single test:
```kotlin
fun DynaNodeGroup.globalLogClientTestBattery(clientProducer: ()-> GlobalLogClient) {
    test("foo") {}
}
```
Then the test still freezes. It looks to me as if the pure act of calling the `globalLogClientTestBattery()` extension method freezes Gradle, however that sounds quite ridiculous to me...

> Project 'umn-sync-server' not found

I'm very sorry, it's called umn-proxy-server, please try `./gradlew umn-proxy-server:test`

**Comment by marcphilipp** [comment]
Hmm, what does the `TestDescriptor` for the `test` defined in the extension function use as a `TestSource`, specifically, which class? There's a bug that currently only a single test class may execute at a time.

**Comment by mvysny** [comment]
Thank you, that is very interesting piece of info!

The algorithm is here: https://github.com/mvysny/dynatest/blob/master/dynatest-engine/src/main/kotlin/com/github/mvysny/dynatest/engine/DynaTestEngine.kt#L233
In short, it will try to guess `FileSource` from whoever called the `test` method, falling back to `ClassSource`.

In case of the `globalLogClientTestBattery`  extension method, that resolves to the `GlobalLogClientTestBattery.kt` file (or `GlobalLogClientTestBatteryKt` class), which is different than the class currently being tested (`MVStoreGlobalLogTest`) which may trigger the bug and confuse Gradle.

Please let me verify this assumption by temporarily disabling this code, always returning `null` or something similar.

**Comment by mvysny** [comment]
Thank you @marcphilipp , indeed returning `null` as a `TestSource` helped! It seems that if there is a `TestDescriptor` with `FileSource` with a child `TestDescriptor` with a `ClassSource` then that will make Gradle freeze.

**Comment by marcphilipp** [comment]
Yes, Gradle currently makes to many assumptions about these kinds of things. I'm closing this issue in favor of the more general #4252.
