### ISSUE TITLE
Proper JaCoCo support when testing plugin with GradleRunner

### ISSUE THREAD

**Issue by vanniktech** [gradle/gradle#5738]
The `GradleRunner` testing infrastructure is really nice. The only downside I'm currently having is that it won't work out of the box with code coverage tools such as JaCoCo. 

My motivation is that I'd like to see which lines I've got covered and which I haven't. 

I don't know whether this can actually be achieved on Gradle side only since as far as I know the plugin is bundled as a jar and will be run that way - which JaCoCo might not recognize.

**Comment by mkobit** [comment]
Similar to https://github.com/gradle/gradle/issues/1465

**Comment by vanniktech** [comment]
I'll close this in favor of #1465
