### ISSUE TITLE
Gradle and Java 7: unable to download from Maven Central

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#5740]
Due to the changes to Maven Central setup on June 18th 2018, effectively banning `TLSv1` and `TLSv1.1`, when using Java 7 Gradle versions that encode the Maven Central `HTTPS` url can no longer download artifacts.

See https://central.sonatype.org/articles/2018/May/04/discontinue-support-for-tlsv11-and-below/ for etails.

Note that this issue will affect JCenter as of June 24th 2018 - see https://jfrog.com/knowledge-base/why-am-i-failing-to-work-with-jfrog-saas-service-with-tls-1-0-1-1/

Status of Gradle versions:
* Older than Gradle `2.1`, unaffected.
* Gradle versions `2.1`-`2.14.1` and using Java 6, affected
  * Use a http URL for maven central and not `mavenCentral()`
* Gradle versions `3.0`-`4.8` and using Java 7 
  * Use Java newer than `1.7.0_131-b31` or if not possible
  * Use a http URL for maven central and not `mavenCentral()`
* Gradle versions `3.0`-`4.8` and using Java 8+, unaffected.

**Comment by ljacomet** [comment]
Proposed solution:
* Gradle `4.8.1` and later will automatically set the TLS protocols to `["TLSv1", "TLSv1.1", "TLSv1.2"]` for Java 7.
* In addition, if the property `https.protocols` is set, it will be used.

**Comment by rickla** [comment]
I am still having issues even thought it seemed to work for me a few days ago.  

Error resolving plugin [id: 'com.bmuschko.tomcat', version: '2.2.5']
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not determine artifacts for com.bmuschko.tomcat:com.bmuschko.tomcat.gradle.plugin:2.2.5
      > Could not get resource 'https://plugins.gradle.org/m2/com/bmuschko/tomcat/com.bmuschko.tomcat.gradle.plugin/2.2.5/com.bmuschko.tomcat.gradle.plugin-2.2.5.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/com/bmuschko/tomcat/com.bmuschko.tomcat.gradle.plugin/2.2.5/com.bmuschko.tomcat.gradle.plugin-2.2.5.jar'.
            > Received fatal alert: handshake_failure

**Comment by marcphilipp** [comment]
@rickla Are you using 4.8.1?

**Comment by ljacomet** [comment]
That's because of #5777, where JCenter has a different twist on the story.
