### ISSUE TITLE
Provide a convenient way to link to updates instruction when generating deprecation warnings

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#5755]
### Current Behavior
An example of a deprecation warning:

```
The property(Class) method has been deprecated and is scheduled to be removed in Gradle 5.0. 
Please use the ObjectFactory.property(Class) method instead.
```

### Expected Behavior
This is better: 

```
The property(Class) method has been deprecated and is scheduled to be removed in Gradle 5.0. 
Please use the ObjectFactory.property(Class) method instead. 
See https://docs.gradle.org/current/updating-gradle-4.html#object-factory-property
```

### Context
Oftentimes, it's not a trivial change to update from a deprecated API to a new one. Users would especially appreciate more detailed instructions. 

Currently the deprecation warning conveniences don't provide a way to use the DocumentationRegistry, which would help in linking to the docs from the logs.

We are working on a Gradle 4.x-5 migration guide (and older versions eventually). It seems especially appropriate that we would link every deprecation warning to instructions on how to resolve it. (This could be applied for other types of warnings of course)

**Comment by bmuskalla** [comment]
@rieske Can this be called done given your recent improvements?

**Comment by rieske** [comment]
Yes, this was handled with https://github.com/gradle/gradle/issues/11828
