### ISSUE TITLE
Different behaviour regarding JUnit 5 @Nested classes between Gradle 4.6 and 4.7-4.8

### ISSUE THREAD

**Issue by kassiar** [gradle/gradle#5763]
When trying to run a single test from the `@Nested` class in JUnit 5, the outcome is different between Gradle versions, with 4.6 finding and executing the test successfully, and 4.7 and 4.8 being unable to find the test at all.

### Expected Behavior
The specified test methods in the nested class should be executed.

### Current Behavior
The specified methods are not being found.

### Context
The issue originally arose while I was trying to migrate some tests from JUnit 4 to JUnit 5, replacing the `@RunWith(Enclosed.class)` approach to nested tests we've used before with the new `@Nested` classes in JUnit 5. When I tried to launch these new tests from Intellij IDEA (using those little green triangles on the side), I got a failure like this one (please check the `Steps to Reproduce` section for the test setup explanation)

    Executing tasks ':cleanTest :test --tests "EnclosingClass$NestedClass.nestedTest"'...
    > Task :cleanTest
    > Task :compileJava UP-TO-DATE
    > Task :processResources NO-SOURCE
    > Task :classes UP-TO-DATE
    > Task :compileTestJava UP-TO-DATE
    > Task :processTestResources NO-SOURCE
    > Task :testClasses UP-TO-DATE
    > Task :test FAILED
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':test'.
    > No tests found for given includes: [EnclosingClass$NestedClass.nestedTest] filter.includeTestsMatching)
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    * Get more help at https://help.gradle.org
    BUILD FAILED in 0s
    4 actionable tasks: 2 executed, 2 up-to-date
    No tests found for given includes: [EnclosingClass$NestedClass.nestedTest] (filter.includeTestsMatching)
    Tasks execution finished ':cleanTest :test --tests "com.example.EnclosingClass$NestedClass.nestedTest"'.

 Note that I used the Gradle Test Runner, which basically executes a Gradle command. When using the native IDEA JUnit execution support, the test is executed normally. This fact made me curious, so I've  tried to launch the tests directly from the command line:

    gradlew cleanTest test --tests EnclosingClass$NestedClass.nestedTest

As expected, the execution failed in a similar manner - though the error message was slightly different: 
`No tests found for given includes: [EnclosingClass$NestedClass.nestedTest] (--tests filter)`

And here's the interesting part:
- when using Gradle 4.6 instead of 4.7 (or 4.8 for that matter) the nested test is executed properly
```
gradlew :cleanTest :test --tests "EnclosingClass$NestedClass.nestedTest"

> Task :test
EnclosingClass > EnclosingClass$NestedClass.nestedTest() STARTED
EnclosingClass > EnclosingClass$NestedClass.nestedTest() PASSED
BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed
```
- If a wildcard is added in front of the filter, then the test gets successfully found and executed too:
`gradlew cleanTest test --tests "*com.example.EnclosingClass$NestedClass.nestedTest"`

I suspect that this issue can be related to the changes in https://github.com/gradle/gradle/pull/4597, though it's mostly because of the leading wildcard changing the behaviour.

### Steps to Reproduce (for bugs)
Here's a very simple setup the demonstrates this behaviour:
- First, do a `gradle init --type java-library`
- Replace the contents of build.gradle with the following:
```
plugins {
    id 'java'
}

dependencies {
    testCompile 'org.junit.jupiter:junit-jupiter-api:5.2.0'
    testCompile 'org.junit.jupiter:junit-jupiter-params:5.2.0'
    testRuntime 'org.junit.jupiter:junit-jupiter-engine:5.2.0'
}

repositories {
    jcenter()
}

test {
    useJUnitPlatform()
    testLogging {
        events "STARTED", "PASSED", "FAILED", "SKIPPED"
    }
}
```
- Create a new source file `src/java/test/EnclosingClass.java` with the following contents:
```
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Nested;
import static org.junit.jupiter.api.Assertions.assertEquals;

class EnclosingClass {
    @Nested
    class NestedClass {
        @Test
        void nestedTest() {
            assertEquals(2, 1 + 1);
        }
    }
}
```
- Make sure that we're using Gradle 4.6 in `gradle/wrapper/gradle-wrapper.properties`
- Execute the following command line and note that the test is found and executed:
 `gradlew cleanTest test --tests EnclosingClass$NestedClass.nestedTest`
- Change Gradle version to 4.7 and execute the same command. Note that the test is not found.

### Your Environment
Build scan, Gradle 4.7, test detection failed: https://scans.gradle.com/s/i3licwrkey3pa
The same for 4.6, test detection successful: https://gradle.com/s/nzbs6as64cb6a

**Comment by marcphilipp** [comment]
@kassiar Thanks for the detailed bug report!

@blindpirate Could you please take a look at this one and decide if this behavior is expected after the changes in #4597?

**Comment by blindpirate** [comment]
Thanks @marcphilipp @kassiar I've confirmed this is a bug. For now, please use `--tests EnclosingClass*.nestedTest` as a workaround.

**Comment by eximius313** [comment]
@blindpirate When do you plan to fix it?

**Comment by zcmgyu** [comment]
In `gradle-7.1`

> gradlew test --tests EnclosingClass$NestedClass.nestedTest

You will get this message when executing this command line:

> No tests found for given includes: [EnclosingClass.nestedTest](--tests filter)

But, the below command worked

> gradlew test --tests EnclosingClass*.nestedTest
