### ISSUE TITLE
Make it clearer which interfaces are intended to be implemented by users

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#5779]
It appears that starting with Gradle 4.8, custom implementations of TaskDependency no longer work. Using them in a publishing block now throws a ClassCastException. Apparently, TaskDependency implementations are being cast to a TaskDependencyInternal interface. One could argue that this is not a bug since the TaskDependency interface is not meant to be implemented by plugin developers, but that is not clear from the documentation. This is another example of how Gradle makes it challenging to integrate into the framework without using internal interfaces and classes. Another example is integrating into the report generation infrastructure. At a minimum, please consider adding "Not to be implemented by plugin developers" to the documentation for the corresponding interfaces.

**Comment by ldaley** [comment]
@baron1405 you're right, in that this is a breaking API change. FWIW, the source `@HasInternalProtocol` annotation is supposed to signal exactly what you are asking for, but it was missed in this case _and_ it is not visible in the Javadoc.

@oehme we should really do something about this. I think we should move `@HasInternalProtocol` (or a replacement) to the public API and include it in the API documentation. Furthermore, we need to treat the introduction of an internal protocol to a public type as a breaking change.

**Comment by baron1405** [comment]
Thanks @ldaley for the quick and constructive response!

**Comment by oehme** [comment]
Actually pretty much no interface in Gradle is there for user implementation, not just the ones annotated with HasInternalProtocol. I think we should flip it around and annotate the hand full of interfaces user are actually allowed to implement.

**Comment by oehme** [comment]
To the issue at hand: Why are you implementing TaskDependency?

**Comment by ldaley** [comment]
>  I think we should flip it around and annotate the hand full of interfaces users are actually allowed to implement.

Sounds reasonable. How would we communicate this to users?

**Comment by oehme** [comment]
We could add this to the validation that the plugin development plugin does. That would probably be the most visible. We could also be explicit and document the opposite as well and add some automation that forces us to actively decide for each interface.

**Comment by baron1405** [comment]
@oehme thanks for the update. I implement TaskDependency because it is required when implementing PublishArtifact. I implement PublishArtifact so that a task I have written can provide a convenience method for obtaining the artifacts produced by that task. This method is for use by consumers of the task so that they can add the artifacts to their publish blocks. The reason I chose PublishArtifact is that it provides the builtBy functionality. This makes it very easy for consumers of my task to not only publish the artifacts but have the task run to generate the artifact.

I will reiterate my concern that restricting the integration points into the Gradle framework (i.e implementable interfaces), increases the tendency of developers to use internal APIs in their plugins.

**Comment by baron1405** [comment]
Thanks for the tip on using ArtifactHandler!

Yes, more flexibility in publishing inputs would be very helpful and would make this very clean.

**Comment by oehme** [comment]
Yes, that would be the rough order we would proceed in. I've changed the title of this issue to reflect this.

**Comment by baron1405** [comment]
Has there been any progress on this documentation issue?
