### ISSUE TITLE
Feature: negative or regex constraints

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#5780]
here's the issue in code

https://bitbucket.org/xenoterracide/gradle-plugin-bundle/src/19a675b7daec9b989f2d0d3f9cca05a7af59a251/build.gradle.kts?at=master

https://bitbucket.org/xenoterracide/gradle-plugin-bundle/addon/pipelines/home#!/results/53

more specifically the problem in this case is that junit is doing pre-release releases as releases. However, there are also cases of regressions where you may want to clarify not this version.

I'd like to be able to write something like

```
      project.getDependencies().constraints( dch -> {
            dch.add( COMPILE, "org.immutables:value:!2.1.+" ); 
            dch.add( COMPILE, "org.immutables:value:2.+" );
```

in junit's case I'd really like to be able to match 5.2.0 or 5.3.0 (stable) but not 5.3.0.M+

**Comment by marcphilipp** [comment]
Regarding the JUnit milestone issue, here's a way to solve it on your end:

```gradle
dependencies {
    testImplementation("org.junit:junit-bom:latest.release")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
	// ...
    components {
        all { ComponentMetadataDetails details ->
            if (details.id.version.contains("-M")) {
                details.status = "milestone"
            }
        }
    }
}
```

**Comment by ljacomet** [comment]
Dependencies declaration can now have a `reject` clause, which takes ranges.

This should allow this problem to be solved.
