### ISSUE TITLE
Plugins repository shows wrong latest version

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#5788]
If I upload `2.0.0-foo` first and then `2.0.0`, the `-foo` version will still be shown as the latest version. Shouldn't it just use a timestamp based sorting mechanism?

**Comment by marcphilipp** [comment]
@eriwen Could you please take a look?

**Comment by eriwen** [comment]
Yes, version ranking has been one of the frustrating parts of the plugin portal infrastructure I'd like to change. Simple timestamp-based sorting doesn't cover the case where, say, 2.0.0 is released and then 1.2.4, but I agree this needs to be a lot better.

I must admit that this won't be at the top of my list for a bit. I see you've already deleted the problematic versions @SUPERCILEX. I'll update this issue when we propose a solution here.

**Comment by SUPERCILEX** [comment]
Ok, SGTM 👍
