### ISSUE TITLE
Task validation contradicts documentation

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [gradle/gradle#5789]
Documentation on [`@Input`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Input.html) says:
```
When used on a File object that refers to a file or directory, the up-to-date check is only dependent on the path and not the contents of the file or directory.
```
Documentation on [`@InputDirectory`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/InputDirectory.html) says:
```
To make the task dependent on the directory location but not the contents, use an Input annotation instead.
```

So from the docs it seems that `@Input` on a file property is a valid use-case.

However `validateTaskProperties` from `java-gradle-plugin` warns in that case:
```
property 'X' has @Input annotation used on property of type java.io.File
```

When using `validateTaskProperties.failOnWarning = true`, it is impossible to ignore the warning.

Either the docs should be fixed or the warning should be ignored (I prefer the latter).

**Comment by marcphilipp** [comment]
@wolfs Could you please take a look?

**Comment by wolfs** [comment]
@alexey-tsvetkov Using `@Input` on a file property in most cases is an error. There are use-cases for this though, as the Javadoc states (tracking only the absolute path).

What is your concrete use-case? I think it would be much better to annotate the `File` property with `@Internal` and add a separate property `String` property annotated with `@Input` which returns the absolute path of the file.

**Comment by alexey-tsvetkov** [comment]
In my case the input was actually redundant. But I still think there are perfectly valid use cases for having `@Input` on a file. 
I was puzzled when `validateTaskProperties` warned me about something I did intentionally after reading the docs explicitly saying that I should do that if I wanted to depend on a directory's location.
Maybe there should be a way to express "I can read the docs and I know what I'm doing", or maybe annotating a file property with `@Input` should be deprecated (and the docs should clearly say it).

**Comment by wolfs** [comment]
@alexey-tsvetkov We adjusted the documentation: https://docs.gradle.org/nightly/javadoc/. So we don't suggest annotating a `File` object with `@Input` anymore.

**Comment by twwwt** [comment]
Since I ran into the same error yesterday and have found this issue today, let me add that this issue is still not entirely resolved. As of Gradle 6.6.1, the Javadoc of `@Input` still [states](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Input.html):

> [...] When used on a File object that refers to a file or directory, the up-to-date check is only dependent on the path and not the contents of the file or directory. [...]

@wolfs 
Is this what you mean with:
> We adjusted the documentation: https://docs.gradle.org/nightly/javadoc/. So we don't suggest annotating a `File` object with `@Input` anymore.

To me, that sentence in the Javadoc of `@Input` tells me that I may very well annotate a `File` with `@Input`. As a result, precisely the same thought of @altsvetkov occurred to me:
> I was puzzled when validateTaskProperties warned me about something I did intentionally after reading the docs explicitly saying that I should do that if I wanted to depend on a directory's location.

Note that also the current JavaDoc of [`@InputDiretory`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/InputDirectory.html) is imprecise about the use of `@Input` on paths or files and should be clarified, imho.

**Comment by scott-pollom** [comment]
+1 to twwwt's comment. I just hit this issue after reading the [Input documentation](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Input.html):

> [...] When used on a File object that refers to a file or directory, the up-to-date check is only dependent on the path and not the contents of the file or directory. [...]
