### ISSUE TITLE
Allow using Java 7/8 features in the Gradle Build itself

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#5798]
Currently, we cannot use Java 7 (or 8) features in the Gradle build itself. This is due to different reasons:
- We cannot set a different source code level per module in IDEA, since we have cyclic dependencies there when using the `gradle idea`. This makes it hard to use Java 7/8 features on the (few) subprojects which allow it.
- We want to print a nice error message on Java 5 when we try to start Gradle on Java less than 7 and when we start a worker on Java less than 6. All the dependencies of the code that needs to run on Java 5 also needs to be compiled for Java 5. Currently, this is most of Gradle, including `core`.
- We want to be able to run tests on Java 6. This requires most of Gradle to run on Java 6, given that we use quite some classloading machinery on the Daemon itself.
- The worker daemon machinery also support running on Java 6, so that code and all the dependencies need to be able to run on Java 6.

We should use this Epic to track work which brings us closer to using Java 7/8 in the Gradle code base in more places.

**Comment by wolfs** [comment]
One way to solve the issues with cyclic dependencies in idea is to use the native import with the one module per source set option.

**Comment by ijuma** [comment]
> We want to print a nice error message on Java 5

Is this still important? I haven't seen a Java 5 user in a long time. It's not even listed in Oracle's support page (http://www.oracle.com/technetwork/java/javase/eol-135779.html). Even for Java 6, extended support expired at the end of this year.

**Comment by ljacomet** [comment]
@wolfs I believe this is no longer an issue and can be closed. Agreed?

**Comment by wolfs** [comment]
Yeah, that is now more or less fixed.
