### ISSUE TITLE
Remove shared dependency caches for unused versions of Gradle

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5807]
## Context

It's a convention to version shared caches so later changes to the format won't affect earlier versions. Instead the version that introduces the breaking change increments the version number and starts with an empty cache.

For example, a typical cache directory looks like this:

```
~/.gradle/caches
├── 2.12
⋮
├── 4.9-20180627091721+0000
├── build-cache-1
├── jars-1
├── jars-2
├── jars-3
├── journal-1
├── modules-2
└── transforms-1
```

In this case, there are three versions of the `jars` cache.

## Goals

Now that [version-specific caches are cleaned up periodically](https://github.com/gradle/gradle/issues/5742), we should remove all versions of shared caches that concern unused Gradle versions. We know which Gradle versions are unused by inspecting the version-specific cache directories.

## Deliverables

- [ ] Research which Gradle version uses which version of `jars` and `modules`
- [ ] Convert this information into a mapping available in source code
- [ ] Ensure there's a test that fails if a future Gradle version increments the cache version but does not adjust the mapping
- [ ] Extract functionality for listing used Gradle versions from `VersionSpecificCacheAndWrapperDistributionCleanupService` to make it reusable
- [ ] Delete unused versions of the `jars` cache
- [ ] Delete unused versions of the `modules` cache

**Comment by marcphilipp** [comment]
@ljacomet Are we also considering deleting unused `modules-2/metadata-*`?

**Comment by ljacomet** [comment]
Yes, I think we should even though they are nowhere as big as the `files-x` one.

As for the versions to delete: is it really the unused ones? Or rather the unused over the last X days ones?

**Comment by marcphilipp** [comment]
Resolved in https://github.com/gradle/gradle/pull/5843.
