### ISSUE TITLE
Unify plugin-publish plugin with java-gradle-plugin

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#5808]
From the [Design Spec](https://docs.google.com/document/d/1-OgChwWtigDZTUAkc9MHVaXgZac14LcttcKR1Rq2cUA/edit?usp=sharing):

## Context

Publishing Gradle plugins currently requires different plugins depending on whether one wants to publish to the Plugin Portal or a custom, e.g. company-internal, repository. For the former purpose, there’s the Plugin Publishing Plugin (`com.gradle.plugin-publish`); for the latter, there’s the Gradle Plugin Development Plugin (`java-gradle-plugin`).

When a project wants to publish Gradle plugins to both the Plugin Portal and a custom Maven repository or simply use the Gradle Plugin Development Plugin to generate the plugin descriptors, its build script currently requires some duplication:

- the plugin IDs have to be duplicated in the plugins blocks of `gradlePlugin` and `pluginBundle`
- the maven coordinates have to customized twice (in mavenCoordinates of `pluginBundle` and in the `pluginMaven` publication).

Moreover, the Plugin Publishing Plugin generates a separate POM file and does not take into account any customizations made to the POM of the main publication added by the Gradle Plugin Development Plugin.

## Goal

Simplify publishing to the Plugin Portal and a custom repository to avoid duplication and enable reuse of POM customization.

**Comment by marcphilipp** [comment]
I wrote a [design spec](https://docs.google.com/document/d/1-OgChwWtigDZTUAkc9MHVaXgZac14LcttcKR1Rq2cUA/edit?usp=sharing) and update the issue description with its main points. Comments on the design spec are welcome!

**Comment by marcphilipp** [comment]
plugin-publish 0.10.0 has been released, the changes to the `java-gradle-plugin` plugin will be in 4.10.

**Comment by jmini** [comment]
If anyone is interested, @marcphilipp wrote this little example to demonstrate how to use this feature with the Groovy DSL:
https://github.com/marcphilipp/gradle-sandbox/blob/85e934d13b413df2fccd752591f631128e7e7734/plugin-maven-publish/build.gradle#L23-L44
