### ISSUE TITLE
Wrapper method in subproject results in error since version 4

### ISSUE THREAD

**Issue by amaloy** [gradle/gradle#5816]
### Expected Behavior
When Gradle is invoked in the parent project, a subproject that has a `wrapper` method shouldn't cause a failure.

### Current Behavior
When Gradle is invoked in the parent project, a subproject that has a `wrapper` method causes a failure:
```
$ ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/amaloy/boog/g4/subproject/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating project ':subproject'.
> Could not find method wrapper() for arguments [build_3hahijwjmgwyw035at2gjxwy3$_run_closure1@74204f25] on project ':subproject' of type org.gradle.api.Project.
```

### Context
In this particular case, the subproject is a project that can be independently build and otherwise worked with, so it's useful for it to have its own wrapper (and having the wrapper method (previously in Gradle 3 it was a task) is desirable). The subproject is a git submodule in the parent project repository, which I bring up to show that, again, the subproject is a separate project/repository and can be worked with on its own.

I'm in the process of upgrading from Gradle 3 to 4.

I did come across this comment: https://github.com/gradle/gradle/issues/5042#issuecomment-384182328
But from my experience (see below) this feels like a regression.

### Steps to Reproduce (for bugs)
Working example with Gradle 3:
```
$ cat build.gradle 
task wrapper(type: Wrapper) {
    gradleVersion = '3.5.1'
}
$ cat subproject/build.gradle 
task wrapper(type: Wrapper) {
    gradleVersion = '3.5.1'
}
$ cat settings.gradle 
rootProject.name = 'g3'
include ':subproject'
$ ./gradlew tasks
:tasks

------------------------------------------------------------
All tasks runnable from root project
<...snip...>
BUILD SUCCESSFUL

Total time: 0.985 secs
```

Failing example with Gradle 4 (the wrapper section is modified as recommended by warnings):
```
$ cat build.gradle 
wrapper {
    gradleVersion = '4.8.1'
}
$ cat subproject/build.gradle 
wrapper {
    gradleVersion = '4.8.1'
}
$ cat settings.gradle 
rootProject.name = 'g4'
include ':subproject'
$ ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/amaloy/boog/g4/subproject/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':subproject'.
> Could not find method wrapper() for arguments [build_3hahijwjmgwyw035at2gjxwy3$_run_closure1@42a233d6] on project ':subproject' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

### Your Environment
```
$ ./gradlew -v

------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_65 (Oracle Corporation 25.65-b01)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by marcphilipp** [comment]
Since subprojects are not supposed to be run by themselves, they should not redefine the `wrapper` task. Please remove it from `subproject/build.gradle`.

**Comment by FerusGrim** [comment]
I'm going to comment on this, since it's the newer of the two issues that I could find (the other being [#5042 (comment)](https://github.com/gradle/gradle/issues/5042#issuecomment-384182328)).

This really seems like a regression, to me. Subprojects which are also stand-alone projects is extremely common. I can think of 3 projects off the top of my head which I use, as well as a few by myself which use them this way.

However, until this can be (hopefully) addressed, I've come up with a workaround that should suffice for myself and @amaloy.

```groovy
// Only supply the wrapper method if being called from the rootProject.
if (rootProject == project) {
    wrapper {
        distributionUrl = "https://services.gradle.org/distributions/gradle-$gradleVersion-all.zip"
    }
}
```

It's unfortunate that this is a necessary (and dirty) fix, but it'll get the job down, for now.

**Comment by jsm174** [comment]
I agree with @FerusGrim where subprojects could be stand-alone - ex. building a jhipster based application with several microservice projects.. 

If you try to import all projects into eclipse, you'll encounter this error. It is frustrating to have to import each project one by one.

**Comment by jsm174** [comment]
@big-guy Thanks! includeBuild works like a charm!
