### ISSUE TITLE
Gradle 4.8.1 resolved dependencies differently than gradle 4.6

### ISSUE THREAD

**Issue by mikewertheim** [gradle/gradle#5818]
I'm using JDK 1.8.0_161 on Windows 10.

The dependencies section of my build.gradle file contains this line:
	compile 'org.apache.pdfbox:pdfbox:2.+'

When I build using gradle 4.6, I get this output (which is the expected behavior):
Download https://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox/2.0.11/pdfbox-2.0.11.pom
Download https://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox/2.0.11/pdfbox-2.0.11.jar

When I build using gradle 4.8.1, I get this output (which seems incorrect):
Download https://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox/2.0.0/pdfbox-2.0.0.pom
Download https://repo.maven.apache.org/maven2/org/apache/pdfbox/pdfbox/2.0.0/pdfbox-2.0.0.jar

The issue is that gradle 4.8.1 is not getting the most recent version of pdfbox. Why?

**Comment by mikewertheim** [comment]
Here is the entire build.gradle file:

buildscript {
	repositories {
		maven {
			url "https://plugins.gradle.org/m2/"
		}
	}
	dependencies {
		classpath 'net.ltgt.gradle:gradle-errorprone-plugin:0.+'
		classpath 'org.owasp:dependency-check-gradle:3.+'
	}
}

apply plugin: 'java'
apply plugin: 'net.ltgt.errorprone'
apply plugin: 'org.owasp.dependencycheck'
tasks.withType(JavaCompile){
	options.warnings = true
	options.compilerArgs += '-Xlint:deprecation'
	options.compilerArgs += '-Xlint:unchecked'
}

apply plugin: 'war'
apply plugin: 'checkstyle'
check.dependsOn dependencyCheckAnalyze

repositories {
	mavenCentral()
}
configurations.errorprone {
	resolutionStrategy.force 'com.google.errorprone:error_prone_core:2.+'
}

dependencies {
	compileOnly(
		[group: 'servletapi', name: 'servletapi', version: '2.+', transitive: true]
	)

	compile 'com.github.dhorions:boxable:1.+'
	compile 'com.google.code.gson:gson:2.+'
	compile 'com.google.guava:guava:25.+'
	compile 'com.sendgrid:sendgrid-java:4.+'
	compile 'commons-codec:commons-codec:1.+'
	compile 'commons-io:commons-io:2.+'
	compile 'mysql:mysql-connector-java:8.+'
	compile 'org.apache.commons:commons-csv:1.+'
	compile 'org.apache.commons:commons-math3:3.+'
	compile 'org.apache.httpcomponents:httpclient:4.+'
	compile 'org.apache.pdfbox:pdfbox:2.+'
	compile 'org.apache.tomcat:tomcat-jdbc:9.+'
	compile 'org.tuckey:urlrewritefilter:4.+'
}

sourceCompatibility = 1.8
version = '1.0'

task createProperties {
	doLast {
		new File("$projectDir/src/main/webapp/WEB-INF/classes/version.properties").withWriter { w ->
		Properties p = new Properties()
		p.store w, null}
	}
}

classes {
	dependsOn createProperties
}

**Comment by mikewertheim** [comment]
Here are the two dependency trees.

gradle 4.6:
```
compileClasspath - Compile classpath for source set 'main'.
+--- com.github.dhorions:boxable:1.+ -> 1.5
|    +--- org.apache.pdfbox:pdfbox:2.0.0 -> 2.0.11
|    |    +--- org.apache.pdfbox:fontbox:2.0.11
|    |    |    \--- commons-logging:commons-logging:1.2
|    |    \--- commons-logging:commons-logging:1.2
|    +--- org.slf4j:slf4j-api:1.7.10
|    +--- com.google.guava:guava:18.0 -> 25.1-jre
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- org.checkerframework:checker-qual:2.0.0
|    |    +--- com.google.errorprone:error_prone_annotations:2.1.3
|    |    +--- com.google.j2objc:j2objc-annotations:1.1
|    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
|    +--- org.apache.commons:commons-csv:1.2 -> 1.5
|    \--- org.jsoup:jsoup:1.9.2
+--- com.google.code.gson:gson:2.+ -> 2.8.5
+--- com.google.guava:guava:25.+ -> 25.1-jre (*)
+--- com.sendgrid:sendgrid-java:4.+ -> 4.2.1
|    +--- com.sendgrid:java-http-client:4.1.0
|    |    +--- org.apache.httpcomponents:httpcore:4.4.4 -> 4.4.9
|    |    +--- org.mockito:mockito-core:1.10.19
|    |    |    +--- org.hamcrest:hamcrest-core:1.1
|    |    |    \--- org.objenesis:objenesis:2.1
|    |    \--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.5
|    |         +--- org.apache.httpcomponents:httpcore:4.4.9
|    |         +--- commons-logging:commons-logging:1.2
|    |         \--- commons-codec:commons-codec:1.10 -> 1.11
|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.5
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0 -> 2.9.5
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.5
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.5
|    \--- com.fasterxml.jackson.core:jackson-core:2.9.5
+--- commons-codec:commons-codec:1.+ -> 1.11
+--- commons-io:commons-io:2.+ -> 2.6
+--- mysql:mysql-connector-java:8.+ -> 8.0.11
|    \--- com.google.protobuf:protobuf-java:2.6.0
+--- org.apache.commons:commons-csv:1.+ -> 1.5
+--- org.apache.commons:commons-math3:3.+ -> 3.6.1
+--- org.apache.httpcomponents:httpclient:4.+ -> 4.5.5 (*)
+--- org.apache.pdfbox:pdfbox:2.+ -> 2.0.11 (*)
+--- org.apache.tomcat:tomcat-jdbc:9.+ -> 9.0.10
|    \--- org.apache.tomcat:tomcat-juli:9.0.10
+--- org.tuckey:urlrewritefilter:4.+ -> 4.0.4
\--- servletapi:servletapi:2.+ -> 2.4-20040521
     \--- javax.servlet:servlet-api:2.4-20040521
```

gradle 4.8.1:
```
compileClasspath - Compile classpath for source set 'main'.
+--- com.github.dhorions:boxable:1.+ -> 1.5
|    +--- org.apache.pdfbox:pdfbox:2.0.0
|    |    +--- org.apache.pdfbox:fontbox:2.0.0
|    |    |    \--- commons-logging:commons-logging:1.2
|    |    \--- commons-logging:commons-logging:1.2
|    +--- org.slf4j:slf4j-api:1.7.10
|    +--- com.google.guava:guava:18.0 -> 25.1-jre
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- org.checkerframework:checker-qual:2.0.0
|    |    +--- com.google.errorprone:error_prone_annotations:2.1.3
|    |    +--- com.google.j2objc:j2objc-annotations:1.1
|    |    \--- org.codehaus.mojo:animal-sniffer-annotations:1.14
|    +--- org.apache.commons:commons-csv:1.2
|    \--- org.jsoup:jsoup:1.9.2
+--- com.google.code.gson:gson:2.+ -> 2.8.5
+--- com.google.guava:guava:25.+ -> 25.1-jre (*)
+--- com.sendgrid:sendgrid-java:4.+ -> 4.2.1
|    +--- com.sendgrid:java-http-client:4.1.0
|    |    +--- org.apache.httpcomponents:httpcore:4.4.4 -> 4.4.9
|    |    +--- org.mockito:mockito-core:1.10.19
|    |    |    +--- org.hamcrest:hamcrest-core:1.1
|    |    |    \--- org.objenesis:objenesis:2.1
|    |    \--- org.apache.httpcomponents:httpclient:4.5.2
|    |         +--- org.apache.httpcomponents:httpcore:4.4.4 -> 4.4.9
|    |         +--- commons-logging:commons-logging:1.2
|    |         \--- commons-codec:commons-codec:1.9 -> 1.10
|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.5
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0 -> 2.9.5
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.5
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.5
|    \--- com.fasterxml.jackson.core:jackson-core:2.9.5
+--- commons-codec:commons-codec:1.+ -> 1.10
+--- commons-io:commons-io:2.+ -> 2.6
+--- mysql:mysql-connector-java:8.+ -> 8.0.11
|    \--- com.google.protobuf:protobuf-java:2.6.0
+--- org.apache.commons:commons-csv:1.+ -> 1.2
+--- org.apache.commons:commons-math3:3.+ -> 3.6.1
+--- org.apache.httpcomponents:httpclient:4.+ -> 4.5.2 (*)
+--- org.apache.pdfbox:pdfbox:2.+ -> 2.0.0 (*)
+--- org.apache.tomcat:tomcat-jdbc:9.+ -> 9.0.10
|    \--- org.apache.tomcat:tomcat-juli:9.0.10
+--- org.tuckey:urlrewritefilter:4.+ -> 4.0.4
\--- servletapi:servletapi:2.+ -> 2.4-20040521
     \--- javax.servlet:servlet-api:2.4-20040521


```

**Comment by ljacomet** [comment]
So it looks like the `pdfbox` version taken is the one picked by `com.github.dhorions:boxable:1.5` which has a dependency on `org.apache.pdfbox:pdfbox:2.0.0` and the change in resolution happened in Gradle 4.7.

I'll try to dig up what caused this.

**Comment by sonicsnes** [comment]
Isn't 2.0.0 the expected conflict resolution due to the change in 4.3? https://docs.gradle.org/4.3/release-notes.html#version-ranges-are-now-handled-properly

**Comment by bigdaz** [comment]
@sonicsnes is correct. Given a concrete version and a version range, Gradle will now choose the concrete version if that version lies within the range.

**Comment by drabe8** [comment]
I'm seeing something similar... but the behavior change is definitely between 4.6 and 4.7. I specify "3.+" of my library as a direct dependency, and then a transitive dependency specifies "3.0.46". I want to take the latest 3.x version, which in my case is 3.0.57. That's what I get using gradle 4.6, but using 4.7 I get version 3.0.46. How can I force it to take the newest version?

**Comment by bigdaz** [comment]
@drabe8 If `3.0.57` is the newest version available, then you can get the behaviour you desire using `latest.integration` instead of `3.+`.

**Comment by drabe8** [comment]
@bigdaz Thanks for the suggestion. Today that would be fine... but if tomorrow, latest.integration points to 4.0, then I'd be unintentionally upgrading to a new major version. We use semantic versioning in our organization, so I really *do* mean "latest 3.x version available."

**Comment by jotel** [comment]
It looks like a regression in Gradle.. a very simple build.gradle shows the problem:
```
repositories {
  jcenter()
}

configurations {
  a {}
  b {}
}

dependencies {
  a 'org.hamcrest:hamcrest-core:1.+'
  a 'junit:junit:4.10'

  b 'org.hamcrest:hamcrest-core:1.+'
}
```
The Gradle doc says

> If the dependency is declared as a dynamic version (like 1.+), Gradle will resolve this to the highest available concrete version (like 1.2) in the repository. For Maven repositories, this is done using the maven-metadata.xml file, while for Ivy repositories this is done by directory listing.

but getting the dependency tree in Gradle version >= 4.7  for `a` and `b` configuration you'd get different versions of `hamcrest-core` library:

`╰─➤  ./gradlew dep --configuration a`
```
a
+--- org.hamcrest:hamcrest-core:1.+ -> 1.1
\--- junit:junit:4.10
     \--- org.hamcrest:hamcrest-core:1.1
```
 and 

`╰─➤  ./gradlew dep --configuration b`
```
b
\--- org.hamcrest:hamcrest-core:1.+ -> 1.4-atlassian-1
```
So it seems like now dynamic versions get the highest available from transitive dependencies .

For gradle *4.6* you get this for configuration `a`
```
a
+--- org.hamcrest:hamcrest-core:1.+ -> 1.4-atlassian-1
\--- junit:junit:4.10
     \--- org.hamcrest:hamcrest-core:1.1 -> 1.4-atlassian-1
```

**Comment by bigdaz** [comment]
@drabe8 Another workaround that would be less brittle. As of today use `[3.0.57, 4)` as your version range. Then you won't get the older versions that are currently brought in, and you won't get anything from the `4.x` stream either.

**Comment by bigdaz** [comment]
Thanks @jotel for your comment. This is a change in the way Gradle resolves version conflicts in the presence of multiple dependencies on the same module. This was an intentional change, as described in the original issue: #2869.

However, it's clear that this had unintended side effects:
- While #2869 is expressed in terms of version ranges with a definite upper bound (e.g. `[3.0, 3.5]`) we implemented the same solution for version ranges with a undefined upper bound (e.g. `[3.0, 4.0)`).
- We also interpreted `3.+` as a version range, meaning it would "accept" any version matching `3.*`.

I've raised #6102 to clarify this issue and open the discussion for potential solutions.

**Comment by dchesterman** [comment]
@bigdaz the commit you are pointing to is in 4.3 but the change in functionality above is between 4.6 and 4.7

Any indication on what commit in 4.7 changed this?

**Comment by bigdaz** [comment]
@dchesterman Yes, in Gradle 4.3 we changed the way we interpreted a version range like `[1.0, 2.0)`. Later (in Gradle 4.7) we made a similar change for version ranges like `1.+`. https://github.com/gradle/gradle/commit/26da3b84b581a22c7c825495ec1ba4ec45e1febf

Note that the second change has been reverted for 4.10. You can read more details in #6102.
