### ISSUE TITLE
Exponential slow-down when using Gradle workers on Appveyor

### ISSUE THREAD

**Issue by ysb33r** [gradle/gradle#5828]
After about 1.5 weeks of experimentation and investigation I think I'm ready to lay an isue at Gradle's door: Tests for implementations using Gradle workers (either `CLASSLOADER` or `PROCESS`) slows down far a alrge degree (even close to expoenential in some cases) when running on Appveyor). When using `javaexec` instead instead of Gradle workers tests complete in the expected time.

### Expected Behavior

If the tests with `javaexec` can complete in 9min I would expect Gradle workers to complete in a similar if not faster, time.

### Current Behavior

Tests involving Gradle workers take over 1h to run, after which Appveyor will kill the build. 

### Context

So far I have only seen this issue happen when running the build for on Appveyor (Windows). testing on a local Windows machine has not exhibited the behaviour to the extent thayt I have seen on Appveyor.

There are five important factors at play here:
- Gradle workers
- Gradle detached configurations
- AsciidoctorJ
- JRuby
- Closures are dehydrated / rehydrated across classloader boundaries (There is one test that deals with this).

Integration tests involve running Testkit which invokes the new Asciidoctor tasks which in turn will use Gradle workers to run AsciidoctorJ & JRuby in isolated environments. Some of the tests use to Spock's `@Unroll` to combine various releases of AsciidoctorJ & JRuby. initially I thought the invalid combination of AsciidoctorJ 1.5.7 & JRuby 9.2.00 was contributing to the problem, but after removing them form the test matrix the problem persisted.  

it is possible that using AsciidoctorJ 1.5.x in one execution and then using AciidoctorJ  1.6.x in a subsequent execution amplifies the problem, although that is not absolute. I have run tests where 1.5 was completely eliminated and the again where only 1.5 was used and I still saw the problem, although it just took longer to arrive.

### Steps to Reproduce (for bugs)

I have created a special branch to experiment with this issue -> https://github.com/ysb33r/asciidoctor-gradle-plugin/tree/debug-appveyor

`appveyor.yml` is already set up to run the exact command, but if you want to run locally use

```
gradlew.bat  :asciidoctor-gradle-jvm:intTest
```

I have already modified the `intTest` to exclude any other integration tests except those in `AsciidoctorTaskFunctionalSpec` and `ExtensionsFunctionalSpec` as those two together produce the problem, but running them solo does not. I'm have also set up the tests to run with `maxParallelForks=1` as I wanted to eliminate concurrency of tests from the equation.

For the purposes of saving time I have annotated both test suites with Spock's `@Stepwise` to save some time in the test run. Experience with this issue has shown that once the first test fail, all subsequent tests will also fail.

*IMPORTANT*: I have hardcoded it to run all of the mentioned integration tests as in-process with an isolated classloader. So irrespective of what the tests says in what it mode it is running, it will actually run with this hard-coded mode. If you need to change it to another mode change the `IN_PROCESS` to `OUT_OF_PROCESS` or `JAVA_EXEC` at the following line.

https://github.com/ysb33r/asciidoctor-gradle-plugin/blob/5cab9db2d4e3da7ba491f1874266040d99bb5be4/asciidoctor-gradle-jvm/src/main/groovy/org/asciidoctor/gradle/jvm/AbstractAsciidoctorTask.groovy#L694

(The above tests are not affected by #3698, so they can be run with Gradle workers)

### Your Environment

As mentioned before, this seems to mostly occur on Appveyor. `appveyor.yml` should provide reasonable information of the environment.

(I have hardly seen this behaviour on Travis CI or locally on Linux, Mac or Windows).

## Mentions

Two other people that have to be mentioned with related to this issue (as per conversation on Twitter):
- @headius: If this turns out to be an issue related to JRuby on WIndows
- @robertpanzer In case AsciidoctorJ is having memory leaks (or interplays badly with JRuby on Windows).

**Comment by ysb33r** [comment]
*UPDATE*: I have managed to reproduce this on a Mac laptop with 8GB where only about 2GB are available to the JVM It ssems to be related to the Gradle daemon keeping a lot in memory and causing to much swap be used. This slows down the task execution.

**Comment by oehme** [comment]
Have you checked the Xmx value you give to the workers? By default we set no value, which means the JVM will take 1/4th of you RAM, which is probably excessive for your use case. In case of JavaExec the JVM dies right after the work is done, but worker processes stick around to be reused later.

**Comment by ysb33r** [comment]
I'll do a test by which I'll restrict the memory via JavaForkOptions 0 will try to get around to it by the next weekend.

**Comment by ysb33r** [comment]
This has become a non-issue for us as the asciidoctor-gradle build now uses GH Actions inetad for Windows builds
