### ISSUE TITLE
Remove javax.annotation package & sub-packages from gradle-api-<version>.jar

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#5835]
Remove `javax.annotation` package & sub-packages from `gradle-api-<version>.jar`.

They cause duplicate package problems with the module path.

Would be preferable to have transitive dependencies on an artifact like `com.google.code.findbugs:jsr305`.

Maybe some additional packages should also be removed from that jar, like `javax.inject` & `javax.xml*`.

**Comment by rgoldberg** [comment]
A Gradle plug-in with which I used the module path. I’m switching all my code over to module path. Currently, I just excluded the FindBugs JSR 305 jar from my transitive dependencies fit guava.

Dependencies would be more flexible if you decompose the gradle-api jar so people can choose what to exclude, or so the transitive dependencies of gradle-api will just be the same artifacts that others depend on, so nothing will need to be excluded.

**Comment by marcphilipp** [comment]
As long as Gradle doesn't use the module path at runtime, I don't see much benefit in using it during development of a plugin. Am I missing something?

**Comment by rgoldberg** [comment]
I don’t know all the benefits of the module path in all circumstances, but I’m trying to keep all my code consistent, and I’m switching all my code to module path.

Even without the module path, it’s generally nicer to have transitive dependencies instead of monolithic jars since it allows more flexibility in terms of upgrading / modifying individual artifacts to fix bugs, reduces duplicate classes on the class path (which could prevent version bugs), provides more flexibility for excludes, lets devs better understand the dependencies of their code when looking at dependency reports, etc.

**Comment by marcphilipp** [comment]
Agreed.
