### ISSUE TITLE
Make TestKit always search-upwards like all Gradle builds do

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#5838]
### Current Behavior
TestKit [disables searching upwards for settings.gradle files](https://github.com/gradle/gradle/blob/master/subprojects/test-kit/src/main/java/org/gradle/testkit/runner/internal/ToolingApiGradleExecutor.java#L184), diverging from the default behavior of Gradle. 

### Expected Behavior
~I understand that we have good reasons for this default that diverges from normal Gradle behavior. As a user, I want an API that allows me to enable this while knowing what the implications are.~

Prevent TestKit from disabling search-upwards (following discussion in comments). This will be a breaking change, so will have to go in a major release.

### Context
Some Gradle samples tests have unnecessarily specify where the settings.gradle file is `--settings-file=../settings.gradle` because Gradle is not searching as it would normally. 

This means that the command to display in our documentation does not match the one that a user would actually run (though they could).

**Comment by oehme** [comment]
Yes I think we should

**Comment by eriwen** [comment]
Okay @oehme I have changed the description and marked this for Gradle 5.0.
