### ISSUE TITLE
[Feature request] Allow split/multiple property files

### ISSUE THREAD

**Issue by hrstoyanov** [gradle/gradle#5839]
Please allow for multiple property files to be supplied on the command line, for example:

```
gradlew -Ppublic-file.properties -Pprivate-file.properties ...
```
The current mechanism of individual properties on the command line(-Pkey=val), a single __gradle.properties__  file or environment variables is not flexible enough!  This is a particularly acute issue when the developer need to separate a set of the properties to be public (such as library versions) and perhaps stored in Git repo, from the properties that need to be private/are sensitive (access keys, passwords, etc), perhaps not coming the Git repo.

**Comment by marcphilipp** [comment]
I usually put those properties in my `~/.gradle/gradle.properties` file. Is that an option for you?

**Comment by hrstoyanov** [comment]
@marcphilipp yes, this can work to some exent, but in a Ci/CD pipeline you want to mix more than 2 sources of properties, unrelated to anyone's home directory?

**Comment by oehme** [comment]
How exactly is the current approach not flexible enough? Please provide a concrete example that doesn't work.

**Comment by oehme** [comment]
There are many ways in which you can already do this. You could

- use a custom user home for each project on CI and automatically sync the credentials there
- create automation that passes the sensitive properties as environment variables for the build
- write some simple logic that reads a custom property file, whose location is specified through a `-P` property and read the sensitive information from there - This shouldn't be more than 5 lines of code
- use the [Gradle credentials plugin](https://github.com/etiennestuder/gradle-credentials-plugin)

Given all these options I don't see the need for another feature in Gradle itself.

**Comment by hrstoyanov** [comment]
You are basically repeating the options that I __already__ mentioned (along with their problems) and none of them is as straightforward and flexible as having something like command line I proposed, IMO.

**Comment by oehme** [comment]
See my option 3, which is exactly what you are asking for and can be built with just a few lines of code.
