### ISSUE TITLE
Support for dependency locking in the build script

### ISSUE THREAD

**Issue by rpau** [gradle/gradle#5845]
According to https://docs.gradle.org/current/userguide/dependency_locking.html#locking_limitations , it is not possible to take benefit of the dependency locking of classpath dependencies in the script plugin. 

Is it possible to fix this? Are you planning to work on this feature? I have searched among your opened and closed issues but I haven't found anything related.

**Comment by ljacomet** [comment]
Work on adding this support has started.
So far, it will work for `buildscript` sections of project `build.gradle`. It will not work for the script `classpath` of `settings.gradle` or init scripts.

Will this match your expectations?
If not, can you describe your use case in detail?
