### ISSUE TITLE
Java 7 deprecation message is not shown when using a Java 7 client with a daemon that uses a later version of Java

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#5889]
It is possible to use a Java 7 client to talk to a daemon running on some later Java version, for example by configuring a Java home property in `gradle.properties`. This scenario is deprecated as we don't want to support Java 7 in the client any more that we do in the daemon and other places. However, a deprecation warning is not shown in this case.

### Expected Behavior

I should receive a warning that using a Java 7 client is deprecated and will no longer work from Gradle 5.0 onwards.

### Current Behavior

I do not receive a warning.

**Comment by big-guy** [comment]
I guess the horse has already left this barn.
