### ISSUE TITLE
LinkageError when compiling Groovy code using custom BytecodeExpression in AST Transformation

### ISSUE THREAD

**Issue by leonard84** [gradle/gradle#5908]
## Summary

When using this custom `BytecodeExpression` 
```java
import groovyjarjarasm.asm.*;
import org.codehaus.groovy.ast.ClassHelper;
import org.codehaus.groovy.classgen.BytecodeExpression;

class ClosureReferenceExpression extends BytecodeExpression {

  ClosureReferenceExpression() {super(ClassHelper.CLOSURE_TYPE);}

  @Override
  public void visit(MethodVisitor methodVisitor) {
    methodVisitor.visitVarInsn(Opcodes.ALOAD,0);
  }
}
```
in an AST transformation, the compilation fails with `java.lang.LinkageError: loader constraint violation: loader (instance of groovy/lang/GroovyClassLoader) previously initiated loading for a different type with name "groovyjarjarasm/asm/MethodVisitor"`. I checked with the `dependencies` task that only a single groovy version is present.

### Expected Behavior

It should compile without issue.

Using IntelliJ to compile and run the tests works without issue.

### Current Behavior

Can be seen here https://travis-ci.org/spockframework/spock/builds/401275894

### Context

Currently Spock uses a hacky workaround to get a reference to the current closure. This `BytecodeExpression` is the clean way to get it.

See also http://groovy.329449.n5.nabble.com/Get-reference-to-enclosing-closure-td5744668.html

### Steps to Reproduce (for bugs)

Checkout https://github.com/spockframework/spock/commit/e78bd761b92c7ab82588a1166611fc6ce692ac01 and run `./gradlew build`

### Your Environment

 * Build scan URL: 
    * https://gradle.com/s/hkcz2bqu2wiyo 
    * https://gradle.com/s/xvlzrvggytga2 
    * https://gradle.com/s/tkis2ojpbzq5m 
    * https://gradle.com/s/d4cnkpxxhsyvs

**Comment by marcphilipp** [comment]
Looks like a Groovy issue after looking at it briefly.

@melix Do you have time to take a look?

**Comment by melix** [comment]
There are chances that it's a problem in classloading isolation of the Groovy runtime in Gradle. We have some magic to hide the groovy classes, but I'm not sure they hide things starting with `groovyjarajar`

**Comment by leonard84** [comment]
@melix so no easy fix then?

**Comment by melix** [comment]
Not without deeper investigation.

**Comment by leonard84** [comment]
This seems to have been fixed by the PR, thx.
