### ISSUE TITLE
feature: dependency lock workflows

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#5912]
Started looking at the dependency locking and thinking about how I want to use it... what occurs to me is that I'm looking at it for solving 2 problems, but I need it to stay out of the way as number 3 & 4.

1. repeatable release builds
1. documenting versions at time of build
1. detect backwards upstream incompatibilities ASAP
1. ensure that the defined required range of deps does in fact work throughout (e.g. 1.+ means, 1.0, 1.1, 1.0.9, 1.2.3 all have to work, currently I don't see any nice way to do this currently.

This list, I believe satifsies my "Acceptance Criteria", and is indeed important for libraries

I think this can mainly be achieved by running `gradle --write-locks build` every time gradle is run... though the problem I see is remembering it. This makes me wonder if it's possible to tell gradle to always do this instead of simply having it be an option... Though then comes the problem of how does one get CI to commit back... which is another issue... problems with this are fairly simple.

I question though, whether with 3, simply doing `--write-locks` is the right answer, vs say doing an `--unlock` or `--ignore-locks`, I originally thought of just committing new deps with the release, and then immediately blowing them away.

with 4,  you would need a "random in range" dependency version resolver, to allow fuzz testing what gradle considers to be a valid version (this is another feature I'd like to see added and can open an issue), however the only way I could see this working is with an `--ignore-locks` feature, where if toggled the locks will not be taken into account during that run, and normal resolution would apply.

**Comment by ljacomet** [comment]
Regarding 3, the idea of having a way to ignore dependency lock state has been discussed but no work happened yet. Right now, it feels like we are missing solid use cases for it.
In this specific example, and because I assume that detection would happen on CI, something like `--update-locks *:*` should do the trick.

**Comment by xenoterracide** [comment]
still would like to see this
