### ISSUE TITLE
Gradle installation not working

### ISSUE THREAD

**Issue by Zaderos** [gradle/gradle#5913]
I attempted to follow all the steps in the installation tutorial and in the last step (the one in which you test your gradle by typing " gradle -v ") the cmd doesn't recognize the command as it should.

I'm trying to code using eclipse, and I have to use the command " gradlew setupDecompWorkspace" in a folder.

I did everything the way the tutorial told me and have checked too many times to be able to count them.

I am using Windows 7, and the tutorials I found for it do the exact same thing I did.

Thanks in advance for any and all help

**Comment by Zaderos** [comment]
pressed the close issue button by accident :man_facepalming:

**Comment by eriwen** [comment]
I suspect that `gradle` may not be on your `PATH`. Please consider following the [troubleshooting guide here](https://docs.gradle.org/current/userguide/troubleshooting.html), and let us know if that doesn't fix things up.
