### ISSUE TITLE
Received complete event for an unknown operation in 4.8-RC1

### ISSUE THREAD

**Issue by aj-jaswanth** [gradle/gradle#5914]
After upgrading from `4.7` to `4.8.1` gradle throws `Received complete event for an unknown operation` error and stops.
### Expected Behavior

Gradle build should succeed in running all tasks.

### Current Behavior

The error is thrown irrespective of parallel builds or running the daemon.

### Context

I have a reproducible sample at https://gist.github.com/aj-jaswanth/de1f847da7a36ead9d58106a6a3c6ff3. Run using `gradle -b blah.gradle runThis`.
This doesn't happen almost always, please try running multiple times.

The issue is not present in version `4.7` but is present in `4.8-RC1`. After doing a bisect I found that the above error started at the commit `https://github.com/gradle/gradle/commit/f18da336e9aae1a68594b7f56e32da6cccbb0eb9`.
### Your Environment

I am using macOS 10.13.5, java 1.8.0_162.

**Comment by wolfs** [comment]
@aj-jaswanth Thank you for reporting. The problem is caused by the commit you posted and your build script using `TaskInternal.execute` (even nested). Started with Gradle 4.8, we events with `Task.execute` as if Gradle would have executed the task.

Can you move away from using `TaskInternal.execute`? Looking at your code, you could use `Project.exec` directly and replace the tasks with functions. Then you wouldn't need to use `TaskInternal.execute()`. Alternatively, you can use `dependsOn` to model the relationship between the tasks. Would that work for you?

Note that `TaskInternal.execute` will be removed with Gradle 5.0.

**Comment by wolfs** [comment]
It seems like running Gradle with `--console=plain` makes the build work. Does that fix your problem?
You can set add [this](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) to your `gradle.properties` file to use `plain` console logging as default:
```
org.gradle.console=plain
```

**Comment by aj-jaswanth** [comment]
@wolfs Yes, plain console solves it. We'll move away from `TaskInternal.execute()`. 
Thanks for the help.

**Comment by wolfs** [comment]
I'll close this issue since there is a workaround and it is caused by using a deprecated API.

**Comment by aj-jaswanth** [comment]
Sure. I'll close it.

**Comment by marcellodesales** [comment]
@wolfs I'm getting this on `Gradle 4.10.1` release... :(

**Comment by wolfs** [comment]
@marcellodesales Does it work if you use `--console=plain` (i.e. the workaround described above)? Can you describe your use-case for using `Task.execute()`? Note that this method will be removed in Gradle 5.0, so you need to migrate away from it anyway.

**Comment by XeZZoR** [comment]
I think I get this error cause of:
assemble.doLast({ copyConf.execute() })

Where copyConf:

  task copyConf(type: Copy) {
    from 'config'
    into 'build/libs/config'
    doLast {
      def props = new File("$buildDir/libs/config/application-default.properties")
      props.createNewFile()
      props.write "build.version=$version\n"
      props << other_build_stuff
    }
  }

Got a multi module project. Some projects have their own configs and those call that copyConf Task after assemble. Is there a more elegant way?

**Comment by wolfs** [comment]
@XeZZoR Yes, there is. Use `project.copy` directly. For questions/discussions please head over to the [forum](https://discuss.gradle.org/).
