### ISSUE TITLE
plugin-dev plugin is not build cache friendly

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#5928]
### Expected Behavior

Caching should work when using this plugin.

### Current Behavior

The `PluginUnderTestMetadata` task writes a file detailing the plugin to be tested (used by TestKit), that contains absolute paths and platform specific line endings.

We patched around this in our own build #3891.

**Comment by wolfs** [comment]
That has already been fixed: https://github.com/gradle/gradle/pull/4398
Are you still experiencing the problem?

**Comment by wolfs** [comment]
Closing as it is already fixed.
