### ISSUE TITLE
Reuse plugin IDs declared in java-gradle-plugin's plugins block for plugin publishing

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5929]
If the Gradle Plugin Development Plugin is applied to a project, the Plugin Publishing Plugin should match plugins by name and use the plugin IDs defined in the former’s `plugins` block (`PluginDeclaration`) unless overridden in the latter’s `plugins` block (`PluginConfig`) to allow users to avoid this duplication. This should work regardless of the order of the respective `plugins` blocks.

**Comment by marcphilipp** [comment]
I'm wondering whether we should add a `displayName` to `PluginDeclaration` because then you could get away without repeating the plugin name. Then, you'd only have to do that if you want to configure custom `tags`, `description` or `version` for oone of the plugins.

@oehme Thoughts?

**Comment by oehme** [comment]
`description` makes sense for Maven publishing (or any kind of publishing really) so +1 on that
