### ISSUE TITLE
Gradle 4.8.1 not generating XML Junit5 test report

### ISSUE THREAD

**Issue by oneiros-de** [gradle/gradle#5934]
### Expected Behavior

XML reports of my tests should be generated.

### Current Behavior

I can switch on and off the html reports but no xml reports are generated.

### Context

I want an XML report of my tests for Jenkins; the project uses JUnit5 and JUnit.

### Steps to Reproduce (for bugs)

I have this snippet in my code:
```
test {
    useJUnitPlatform()
    reports {
        junitXml.enabled = true
        html.enabled = false
    }
}
```
but `gradle test` generates no XML file (if I enable the html report, it is generated, though).
### Your Environment

 * Build scan URL: https://scans.gradle.com/s/vjgy6erjfeju2/

See also https://stackoverflow.com/q/51282064/821436

**Comment by oehme** [comment]
@wolfs The output came from the cache, so I assume this is a nonintended cache hit. Could it be that report.enabled is not part of the cache key?

**Comment by wolfs** [comment]
@oehme Enabled reports are tracked for any report container: https://github.com/gradle/gradle/blob/bfefc3e5ee3e0148e8d724039ecce2278f0865bf/subprojects/reporting/src/main/java/org/gradle/api/reporting/ReportContainer.java#L91-L98

I also tried it out and got the following when changing `junitXml.enabled`: 
![image](https://user-images.githubusercontent.com/423186/42583415-2f32a986-8531-11e8-97b4-c75784973db0.png)
See the [build scan](https://e.grdev.net/s/x7ouhbaqwk2xm/timeline?task=si6uhuz4tdufw).

So we even track the fact that a report is enabled twice. Once via `ReportContainer.getEnabledReports` and once via `TestTaskReports.get...`: https://github.com/gradle/gradle/blob/dfecfafa52ca7db2cfdfd4f5e848943dc4384ae9/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestTaskReports.java#L29-L43.

**Comment by wolfs** [comment]
@oneiros-de Note that the xml report can be found under `build/test-results/<test-task-name>` and not under `build/reports`.

**Comment by oneiros-de** [comment]
@wolfs o.k., that was the problem - the report is generated but I did not find it (didn't look there).

Why are the locations different for xml (`build/test-results/test/`) and html (`build/reports/tests/test/`)? If this is not documented yet (and I think it isn't), it should be.

**Comment by oehme** [comment]
The locations are different because the reports directory is for human-readable content.

**Comment by BelooS** [comment]
Guys, please stop changing the directory per couple of gradle versions
