### ISSUE TITLE
assembleDist generates scripts with wrong classpath

### ISSUE THREAD

**Issue by ilyaukin** [gradle/gradle#5945]
### Expected Behavior

Scripts in build/scripts/ use correct class path to generated jar.

### Current Behavior

Scripts use incorrect classpath to generated jar.
The jar is in libs/ directory, classpath in scripts contains lib/

### Steps to Reproduce (for bugs)

https://github.com/ilyaukin/tucan

### Your Environment

 * Build scan URL: 
https://scans.gradle.com/s/6teiglychzspk

**Comment by joamuran** [comment]
I have the same problem in a simple Hello World Project from an Ubuntu Bionic, both in 3.4.1 version (default version in ubuntu) and in 4.10. 
Just doing a simple "gradle build", the structure generated into build folder contains jars into "libs" folder:

```bash
.
├── build
│   ├── classes
│   │   └── java
│   │       └── main
│   │           └── ...
│   ├── distributions
│   │   ├── HelloGradle.tar
│   │   └── HelloGradle.zip
│   ├── libs
│   │   └── HelloGradle.jar
│   ├── scripts
│   │   ├── HelloGradle
│   │   └── HelloGradle.bat
│   └── tmp
│       ├── compileJava
│       └── jar
│           └── MANIFEST.MF
...
```
When we launch build/scripts/HelloGradle, we got:

```shell
$ ./build/scripts/HelloGradle 
Error: Could not find or load main class com....
Caused by: java.lang.ClassNotFoundException: com...
```
If we look at HelloGradle script, we see that it sets classpath to:

```shell
CLASSPATH=$APP_HOME/lib/HelloGradle.jar
```
As we can see, lib folder stablished in classpath is not libs folder wich contains jar files.

If we change classpath to $APP_HOME/libs/HelloGradle.jar or we rename libs folder to lib (obviously, only one of these two options), it works:

 ```shell
$ ./build/scripts/HelloGradle 
Hello Gradle!!
```

**Comment by thc202** [comment]
Those scripts are not expected to be executed directly from the build directory, they should be executed from the distributions (i.e. unpack `HelloGradle.zip`/`HelloGradle.tar`).
