### ISSUE TITLE
Performance issues on Java 10 (and higher) on Windows

### ISSUE THREAD

**Issue by cliffred** [gradle/gradle#5951]
After we upgraded to Java 10 we noticed the duration of the configuration phase of our build increased dramatically. 

### Expected Behavior
No significant changes in build time after upgrading to Java 10.

### Current Behavior and context
We have a large multi-project build with 197 sub projects. Benchmarking with the [gradle-profiler ](https://github.com/gradle/gradle-profiler) showed that executing `gradle help` took 6.4 seconds on average on Java 9 and 47.4 seconds on Java 10. We measured `gradle help` to focus on the configuration phase.

Profiling with JProfiler revealed this increase was due to an increased average time of the `File.listRoots()` method, which gets called from [org.gradle.api.internal.file.FileOrUriNotationConverter.convert(Object,NotationConvertResult)](https://github.com/gradle/gradle/blob/8c61b05f79ac58fac3f41f3245a97275ad3b5837/subprojects/core/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java#L101). The average time of `File.listRoots()`  went from 4μs on Java 9, to 6,065μs on Java 10. In our build this method gets called 6220 times, resulting in the dramatic increase.

The performance decrease of `File.listRoots()` in Java 10 is probably due to this change in `java.io.WinNTFileSystem`: http://hg.openjdk.java.net/jdk10/jdk10/jdk/rev/9065d9d6c3e0

As [org.gradle.api.internal.file.FileOrUriNotationConverter.convert(Object,NotationConvertResult)](https://github.com/gradle/gradle/blob/8c61b05f79ac58fac3f41f3245a97275ad3b5837/subprojects/core/src/main/java/org/gradle/api/internal/file/FileOrUriNotationConverter.java#L101) gets called (relatively) often in Gradle builds, it might be a good idea to cache the result of `File.listRoots()` .

As a workaround we prefixed a lot of file references with `file:` and replaced `file('path')` with `new File('path')`, preventing calls to `File.listRoots()`. This improved the build time significantly (17.3 seconds on average), but still a lot slower than with Java 9, because this method also gets called a lot with arguments that are not in our control, like 'gradle/dependency-locks', 'build', 'src/main/java', and 'src/test/java'.

### Steps to Reproduce
Install JDK 10 and set JAVA_HOME to the JDK 10 location and run your build. Especially noticeable with large projects with many file references in the build files.

### Your Environment
Gradle 4.8
Windows 10
Core i7-4790
32GB RAM

**Comment by oehme** [comment]
I had fixed this 2 months ago, but somehow must have forgotten to push it. PR is here: https://github.com/gradle/gradle/pull/5952

**Comment by oehme** [comment]
Note that even 6s configuration time is not good. Can you send me the JFR file for Java 9 without your workarounds?

Also note that `new File("path")` is not correct in Gradle, as it will resolve against the directory the daemon was started in, not the project directory of the project you are configuring.

**Comment by cliffred** [comment]
Thank you for the quick reply. I've just emailed you the JFR file.
