### ISSUE TITLE
Error from `lenientConfiguration.getArtifacts()` when dependency does not explicitly define default configuration

### ISSUE THREAD

**Issue by jeremylong** [gradle/gradle#5953]
This issue might be related to the android sdk - but I believe it is in core gradle so I am starting here.

I am writing a gradle task that collections information from the `ResolvedArtifacts`. On a multi-project android build (such as [sample-dependency-check-app](https://github.com/jeremylong/sample-dependency-check-app])), when calling `lenientConfiguration.getArtifacts()` the following errors are produced. When calling `lenientConfiguration.getAllModuleDependencies()` no errors are produced and a sample task works (however, I need the actual ResolvedArtifact not the ResolvedDependency).

```
Execution failed for task ':app:resolveArtifacts'.
> Could not resolve all dependencies for configuration ':app:debugAndroidTestCompileClasspath'.
   > More than one variant of project :mylibrary matches the consumer attributes:
       - Configuration ':mylibrary:debugApiElements' variant android-aidl:
           - Found artifactType 'android-aidl' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
...
```

The quick fix is to have my end users explicitly set the default configuration when referencing a library in their multi-project build. In the sample-dependency-check-app/app/gradle.build they have a dependency defined as:

```groovy
implementation project(':mylibrary')
```

If they update the dependency declaration to the following - `lenientConfiguration.getArtifacts()` works successfully in my task:

```groovy
implementation project(path: ':mylibrary', configuration: 'default')
```

### Expected Behavior
`lenientConfiguration.getArtifacts()` should not error when configuration: 'default' is missing (it is the default right?). If `lenientConfiguration.getAllModuleDependencies()` succeeds without the explicit default configuration - I am not sure why getArtifacts would error.

### Context
I am maintaining the [OWASP dependency-check-gradle](https://github.com/jeremylong/dependency-check-gradle) plugin. This is a FOSS Software Composition Analysis tool that reports when a project is using known vulnerable libraries. Dependency-check requires analyzing the actual dependency file (i.e. JAR file in the case of Java).

### Steps to Reproduce (for bugs)
source code: https://github.com/jeremylong/dependency-check-gradle
sample project: https://github.com/gmetal/sample-dependency-check-app

```shell
git clone https://github.com/gmetal/sample-dependency-check-app
cd sample-dependency-check-app
./gradlew dependencyCheckAggregate
```

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/vqlwitt3l65wk

**Comment by oehme** [comment]
There is a difference between asking for the components you depend on and asking for its artifacts. That's why the former succeeds while the latter fails.

There is no single list of artifacts for an Android project. Each project provides an AARs, a JAR, a classes folder, a resources folder etc). The Android team decided not to have a default fallback to prevent silent failures. If you just want the external dependencies (for which there is only one artifact), you can use an ArtifactResolutionQuery to only ask for those, based on what you find in `configuration.incoming.resolutionResult`.

Please don't use `resolvedConfiguration`. That API is old, slow and soon to be deprecated. Use `configuration.incoming` instead.

**Comment by oehme** [comment]
Ah yes I forgot that you can't ask for the acutal jar, my bad. 

What you can do is use the `incoming.artifacts {}` API with the right attribute. Probably `artifactType "jar"` for your purpose. You might want to check with the Android team for details on which attributes they use and what values there are. Maybe they even have a convenience method that gives you the artifact collection you need.

There basically is no single artifact model anymore. The Android team could decide to ditch AARs in favor of publishing 3 separate files and the plugin would keep working. So as a consumer you need to be explicit what you are interested in. Do you want classes, resources, manifests, whole AAR files etc.

**Comment by oehme** [comment]
No, there is a second overload that allows you to modify the attributes you are looking for.

**Comment by jeremylong** [comment]
@oehme truly appreciate your assistance with this! I could not find an overload for `getArtifacts()` - but I did find `artifactView` which works:

```groovy
def artifactType = Attribute.of('artifactType', String)
def types = ['jar', 'aar']
types.each { type ->
    configuration.incoming.artifactView {
        attributes {
            it.attribute(artifactType, type)
        }
    }.artifacts.each {
        println "artifact file: ${it.file}"
    }
}
```

Last question - is there a way to get a list of the `artifactType` that are contained within the incoming artifacts?

**Comment by oehme** [comment]
We need to rename that method for clarity :)

There is currently no API to iterate over all the possible variants.  The error message should show you the different ones it tried to pick from though.
