### ISSUE TITLE
Suggested improvements to cache cleanup

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#5960]
1. *Limited documentation*: Currently, the release notes provide more detailed documentation than the user guide. We should aim for the opposite: provide a highlight of the feature in the release notes, and detailed description in the user guide.

2. *Force cleanup*: An explicit way to force cache cleanup (without any timeout) would be very useful, particularly as users (like me) experiment with this feature. Even if "cleanup on stop" is useful in maintenance mode, users will be initially happier if they can "run cleanup" and see the effect immediately.

3. *Partial cleanup of `modules-2/metadata-X`*: We should not be removing individual files from within `modules-2/metadata-X`. The `metadata` directory should be treated as a atomic binary store. While it _may_ currently be resilient to partial cleanup, I don't think we want to guarantee this.
    - The `modules-2/files*` and `modules-2/resources*` are fine to cleanup in this way.
    - Should be removing the entire `modules-2/metadata-X` directory when all Gradle versions that use that metadata directory have been removed.

4. *Not handling aborted downloads*: Daemon log contains a lot of exceptions like this: https://gist.github.com/bigdaz/9c1f9d3da2d4dd6842664128e232657a
The distribution directory suggests that maybe these were aborted downloads. It would be nice to clean those up.
```
➜  dists  ls /Users/daz/.gradle/wrapper/dists/gradle-3.5-20170226000042+0000-bin/ptn855b85a0cc1ta5jpde0bl
gradle-3.5-20170226000042+0000-bin.zip.lck  gradle-3.5-20170226000042+0000-bin.zip.part
➜  dists  ls /Users/daz/.gradle/wrapper/dists/gradle-2.14-20160412222818+0000-bin/22ngetywytgpfn4xrx9i96zb2
gradle-2.14-20160412222818+0000-bin.zip.lck  gradle-2.14-20160412222818+0000-bin.zip.part
```

5. *Empty directories remain for 4.0-4.2*: After cleanup, a bunch of directories like `caches/4.0-20170515213009+0000` remain. They contain only an empty `plugin-resolution` directory. It would be nice if these were deleted as well.

6. *Clean `wrapper/dists` for older versions*: It might be fine if we don't automatically remove directories from `caches` for  Gradle versions `< 4.0`. However, it would be great if I manually delete the `caches/3.3-X` directory then the corresponding `wrapper/dists` would be deleted, along with shared caches that are no longer in use. It looks like we are using the removal of `caches/foo` to trigger the removal of `wrapper/dists/foo`: any reason we can't rely on the "used Gradle versions" instead?

7. *Not removing really old `artifacts-X`*: This directory precedes `modules-X`, and was in use with Gradle 1.0 - 1.8 (or so). It would be nice to clean it up, but probably not worth the effort.

**Comment by oehme** [comment]
+1 for an explicit option. I had 120GB of old stuff in my caches and waiting for that to be deleted at daemon stops would have taken a very long time.

**Comment by bigdaz** [comment]
@marcphilipp I think the explanation that you've added to the release notes is suitable for inclusion in the user guide. I think users will appreciate an explanation of exactly what we do and do not clean up. Certainly, I would have appreciated it, and only looked in the user guide for an explanation!

If it's not something we want in the user guide, then we probably shouldn't be including it in the release notes either.

**Comment by marcphilipp** [comment]
Closing this issue as resolved since all subtasks have been addressed.
