### ISSUE TITLE
Core plugins should not implement Plugin<ProjectInternal> leaking an internal type

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#5964]
Core plugins that `implements Plugin<ProjectInternal>` do leak the internal `ProjectInternal` type into the Gradle public API. They should not.

The problem is exacerbated with Kotlin where type safety matters and the api expect `Plugin<Project>`.

### Expected Behavior
```kotlin
project.apply<JacocoPlugin>()
```
Should work.

### Current Behavior
Compiler complains with...
![image](https://user-images.githubusercontent.com/132773/42677490-343983fe-867c-11e8-9286-182e579b39b9.png)

### Context
First reported as https://github.com/gradle/kotlin-dsl/issues/964, including a workaround.

At the time of writing, I found 20 core plugins in the public api that leak `ProjectInternal`:
- HelpTasksPlugin
- JacocoPlugin
- CppApplicationPlugin
- CppBasePlugin
- CppLibraryPlugin
- NativeBasePlugin
- SwiftApplicationPlugin
- SwiftBasePlugin
- MavenPlugin
- LifecycleBasePlugin
- NativeComponentModelPlugin
- NativeComponentPlugin
- DistributionPlugin
- JavaBasePlugin
- JavaLibraryDistributionPlugin
- JavaPlugin
- ReportingBasePlugin
- CppUnitTestPlugin
- NativeTestingBasePlugin
- XCTestConventionPlugin

They should `implements Plugin<Project>` and cast internally if required.

**Comment by oehme** [comment]
More generally, plugin types should disappear from the public API. We should use the plugin IDs and their extensions instead.

**Comment by eskatos** [comment]
@oehme agreed, but until then it would be good to fix the internal types leak

**Comment by JLLeitschuh** [comment]
What is the point of having `Plugin` be generic to begin with?
I understand that it will be an API breaking change to remove the generic, but is it really necessary?

**Comment by oehme** [comment]
There are `Settings` and `Gradle` plugins.

**Comment by grv87** [comment]
If plugins would disappear from public API, please, move constants to somewhere else available. `JavaPlugin` now exposes a bunch of constants like `API_CONFIGURATION_NAME`. They are very useful in custom plugins.
