### ISSUE TITLE
Dependencies report should prioritize hard dependencies over dependency constraints

### ISSUE THREAD

**Issue by NHendricks** [gradle/gradle#5969]
The gradle documentation says: "The dependency report always contains declared and transitive dependencies." (see https://docs.gradle.org/current/userguide/inspecting_dependencies.html#sec:listing_dependencies). When using the feature preview IMPROVED_POM_SUPPORT (which will be the default behaviour in gradle 5) the dependency graph shows the dependency constraints imported from the dependencyManagement section of a pom instead of the transitive dependencies. From my point of view this is not correct and it makes it very hard to get an overview of the projects transitive dependencies (i might have to call dependencyInsight for every single dependency or have to build scan).
My example is a simple project with 2 compile dependencies: org.springframework.boot:spring-boot-dependencies (pom with dependencyManagement) and org.springframework.amqp:spring-rabbit (pom with dependencies).
### Expected Behavior
The transitive dependencies of the declared dependency org.springframework.amqp:spring-rabbit should be displayed. The dependency to org.springframework.boot:spring-boot-dependencies should be displayed without children.
### Current Behavior
The transitive dependencies of org.springframework.amqp:spring-rabbit are not displayed. All of them occur as children of the dependency to org.springframework.boot:spring-boot-dependencies.
### Context
I want to have an overview of my projects dependencies. As far as possible i want to see which dependency brought other dependencies into the tree.

### Steps to Reproduce (for bugs)
build.gradle:
apply plugin: 'java'

repositories {
	jcenter()
}

dependencies {
	compile 'org.springframework.boot:spring-boot-dependencies:2.0.3.RELEASE'
	compile 'org.springframework.amqp:spring-rabbit'
}

call "gradle dependencies"

### Your Environment
 * Build scan URL: 
https://gradle.com/s/rmejk2adtyqho

**Comment by ljacomet** [comment]
In preparation of Gradle 5.0 a number of changes have happened around Maven BOM support. See [this comment](https://github.com/gradle/gradle/issues/4422#issuecomment-418152063) on how to use BOMs with the latest 5.0 nightly.
Also, constraints no longer have transitive dependencies.

Because of all these changes, a `dependencies` report will only show constraints that effectively match a real dependency in the build.

With these changes in mind, could test again and let us know if that resolves this issue?
