### ISSUE TITLE
compileJava task fails to generate native headers

### ISSUE THREAD

**Issue by weiqigao** [gradle/gradle#5973]
### Expected Behavior
I work on a Windows 7 PC in a Cygwin 64 enviroment, using Gradle 4.8.1 and OpenJDK 10.0.1.
With the following `build.gradle` file:

```
plugins {
    id 'java'
}

compileJava {
    options.compilerArgs += ["-h", "src/main/headers"]
    options.verbose = true
}
```

and a single Java file in `src/main/java/foo/Foo.java` whose content is:

```
package foo;

public class Foo {
    public native void doIt();
}
```

When I run `gradle build` I expect the JNI header file to be created at `src/main/headers/foo_Foo.h`

### Current Behavior
The header file is not created.

### Context
I'm trying use Gradle for a Java application that needs JNI support.

### Steps to Reproduce (for bugs)
In a fresh directory, create the above `build.gradle` and `src/main/java/foo/Foo.java` files.  Run the `gradle build` command.

If I add a `options.verbose = true` option to `compileJava`, the verbose output contains the lines:

```
[wrote DirectoryFileObject[src\main\headers:foo_Foo.h]]
[wrote DirectoryFileObject[C:\cygwin64\home\90019249\temp\src\java\jni\jni-bug\build\classes\java\main:foo/Foo.class]]
```
However the header file cannot be found in `src/main/headers/foo_Foo.h`.

If I change the `"src/main/headers"` to an absolute directory with the drive letter, like `"C:/cygwin64/home/90019249/temp/src/java/jni/jni-bug/src/main/headers"`, then the file will be generated in the expected location.

### Your Environment
Again, I'm working in a Cygwin 64 environment on a Windows 7 64-bit machine.  I tried the above from a Windows command prompt (without Cygwin) and observed the same behavior.

 * Build scan URL: https://gradle.com/s/6et4h7ywsp5zu

**Comment by oehme** [comment]
Please use the `file()` method. Relative paths won't work when passed as compiler args because the working dir is not the project directory (that would prevent us from reusing the compiler).

**Comment by asadqazi** [comment]
for java this works. but how to do it for kotlin?
```
compileJava {
    options.compilerArgs += ["-h", file("src/main/include")]
}
```
