### ISSUE TITLE
Cross-project dependencies don't include compiled sources

### ISSUE THREAD

**Issue by JacobAMason** [gradle/gradle#5980]
I'm attempting what should be a simple two project dependency chain. Project A depends on project B by the recommended lines in `settings.gradle`:
```
include ':ProjectB'
project(':ProjectB').projectDir = new File(settingsDir, '../ProjectB')
```
and then the following in project A's `dependencies`
```
dependencies {
    compile project(path: ':ProjectB')
}
```
My output from `./gradlew dependencies` is the following:
```
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.31
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.31
|    |    \--- org.jetbrains:annotations:13.0
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.31
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.31 (*)
\--- project :ProjectB
     +--- io.grpc:grpc-netty:1.13.1
     |    +--- io.grpc:grpc-core:[1.13.1] -> 1.13.1
     |    |    +--- io.grpc:grpc-context:1.13.1
     |    |    +--- com.google.code.gson:gson:2.7
     |    |    +--- com.google.guava:guava:20.0
     |    |    +--- com.google.errorprone:error_prone_annotations:2.1.2
     |    |    +--- com.google.code.findbugs:jsr305:3.0.0
     |    |    +--- io.opencensus:opencensus-api:0.12.3
     |    |    \--- io.opencensus:opencensus-contrib-grpc-metrics:0.12.3
     |    |         \--- io.opencensus:opencensus-api:0.12.3
     |    +--- io.netty:netty-codec-http2:[4.1.25.Final] -> 4.1.25.Final
     |    |    +--- io.netty:netty-codec-http:4.1.25.Final
     |    |    |    \--- io.netty:netty-codec:4.1.25.Final
     |    |    |         \--- io.netty:netty-transport:4.1.25.Final
     |    |    |              +--- io.netty:netty-buffer:4.1.25.Final
     |    |    |              |    \--- io.netty:netty-common:4.1.25.Final
     |    |    |              \--- io.netty:netty-resolver:4.1.25.Final
     |    |    |                   \--- io.netty:netty-common:4.1.25.Final
     |    |    \--- io.netty:netty-handler:4.1.25.Final
     |    |         +--- io.netty:netty-buffer:4.1.25.Final (*)
     |    |         +--- io.netty:netty-transport:4.1.25.Final (*)
     |    |         \--- io.netty:netty-codec:4.1.25.Final (*)
     |    \--- io.netty:netty-handler-proxy:4.1.25.Final
     |         +--- io.netty:netty-transport:4.1.25.Final (*)
     |         +--- io.netty:netty-codec-socks:4.1.25.Final
     |         |    \--- io.netty:netty-codec:4.1.25.Final (*)
     |         \--- io.netty:netty-codec-http:4.1.25.Final (*)
     +--- io.grpc:grpc-protobuf:1.13.1
     |    +--- io.grpc:grpc-core:1.13.1 (*)
     |    +--- com.google.protobuf:protobuf-java:3.5.1
     |    +--- com.google.guava:guava:20.0
     |    +--- com.google.api.grpc:proto-google-common-protos:1.0.0
     |    \--- io.grpc:grpc-protobuf-lite:1.13.1
     |         +--- io.grpc:grpc-core:1.13.1 (*)
     |         \--- com.google.guava:guava:20.0
     \--- io.grpc:grpc-stub:1.13.1
          \--- io.grpc:grpc-core:1.13.1 (*)
```
As you can see, Project B only included it's transitive dependencies. While this means I've at least pointed my project to the right place on my filesystem, I don't know how to get the compiled output from Project B into Project A. I thought the `jar` task for Project B might not have been running at all, but that didn't seem to be the case.
```
10:47:29 PM: Executing task 'build'...

...

:ProjectB:compileJava
:ProjectB:processResources UP-TO-DATE
:ProjectB:classes
:ProjectB:jar
:compileKotlin

... Import errors ...

:compileJava FAILED
```
I have executed the `clean` task on project B and have also confirmed that project A's `build` task does indeed compile the jar on project B.

### Expected Behavior

I expected the `compile project()` line to include the jar generated by project B as a library dependency. The documentation I've read  https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:project_jar_dependencies has lead me to believe that this is what should happen. Specifially, the following excerpt

> A “lib” dependency is a special form of an execution dependency. It causes the other project to be built first and adds the jar with the classes of the other project to the classpath. It also adds the dependencies of the other project to the classpath.

I appear to be getting the latter "dependencies of the other project to the classpath", but not the former "jar with the classes of the other project to the classpath".

### Context

Project B is a grpc model which creates generated source from a proto file. The generated source is in the jar made from the `jar` task in this model.

### Steps to Reproduce (for bugs)

Since I was attempting to make a grpc project with grpc java, you're welcome to do the same, but I imagine that any cross-project dependencies will behave in the same way.

### Your Environment

------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Linux 4.17.3-1-ARCH amd64

**Comment by JacobAMason** [comment]
Pushed here: https://github.com/JacobAMason/gRPC-Example

The HelloWorld file in the default package of ProjectA can reference the Greeter in the default package of ProjectB, but the generated source in ProjectB is not reference-able in ProjectA.

**Comment by JacobAMason** [comment]
Of course I'd find a solution after posting this issue, even though I've been on this for hours:
If I include the generated output in the `sourceSets` in ProjectB, everything is happy.
```
sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}
```

This could be a weird generated sources quirk.

**Comment by oehme** [comment]
That project builds just fine without the snippet above.

**Comment by JacobAMason** [comment]
It shouldn't, at least not after the imports are fixed like I did in the last commit to that example.

**Comment by oehme** [comment]
Well if the imports are wrong then that's the issue, nothing in Gradle.

**Comment by JacobAMason** [comment]
I mean, the imports being wrong wasn't really the problem. I just mistyped a letter in my example, but the problem was still there until that `sourceSets` block was added to the project that created the generated code.

**Comment by oehme** [comment]
As I said above, it builds just fine without that `sourceSet` snippet.
