### ISSUE TITLE
Gradle 4.9 + Lombok 1.18.0 fails

### ISSUE THREAD

**Issue by tmszdmsk** [gradle/gradle#5983]
### Expected Behavior
build should pass as in previous `4.8.x` version

### Current Behavior
Build process fails with following message:
```
/path/to/buildSrc/file.java:24: warning: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.ClassCastException: org.gradle.api.internal.tasks.compile.processing.IncrementalFiler cannot be cast to com.sun.tools.javac.processing.JavacFiler
...
error: cannot find symbol
  @Setter(onMethod = @__(@JsonProperty("notify")))
```

### Context
Build worked properly with the previous version of Gradle

### Steps to Reproduce (for bugs)
`gw compileTestJava`

### Your Environment
lombok `1.18.0`
gradle `4.9.0`
java `java version "1.8.0_152" Java(TM) SE Runtime Environment (build 1.8.0_152-b16) Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)`

**Comment by oehme** [comment]
This was already fixed on the Lombok side. https://github.com/rzwitserloot/lombok/pull/1718

Note that this already happened with 4.8, 4.9 didn't change anything in that area.
