### ISSUE TITLE
Update plugin-publishing documentation

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#5987]
Document recommended usage of `plugin-publish` along with `java-gradle-plugin` on Plugin Portal, link to it from the User Guide, and add an entry to the Release Notes.

**Comment by marcphilipp** [comment]
I'm going to update https://plugins.gradle.org/docs/publish-plugin and https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/ and add a short note and reference to the guide on https://docs.gradle.org/4.8/userguide/java_gradle_plugin.html.

@eriwen Do we publish release notes for the plugin-publish plugin? If so, where? In the forum?

**Comment by eriwen** [comment]
@marcphilipp We typically post this news in the forum. I would like to encourage us to use the blog for new releases like this, but I won't mandate it in this case.

**Comment by eriwen** [comment]
Here's an example of a forum post: https://discuss.gradle.org/t/plugin-authors-v0-9-10-of-the-plugin-publish-plugin-released-with-kotlin-dsl-support/25763

**Comment by marcphilipp** [comment]
Related issue: https://github.com/gradle/guides/issues/187
