### ISSUE TITLE
Bundled `testng` and `jcommander` versions are old and buggy

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#5990]
Gradle ships with version `6.3.1` of TestNG, which was released in 2011. It also ships with `com.beust:jcommander:1.47`, which has known performance issues: https://github.com/cbeust/jcommander/pull/265.

I'm not sure of the significance of the bundled versions of these libraries, since it does not seem possible to use TestNG without providing a version in the `testCompile` configuration.

We should avoid shipping with such an outdated version of TestNG if possible.

**Comment by DPUkyle** [comment]
Thanks for logging this, Daz!

**Comment by ljacomet** [comment]
JCommander is updated to version 1.72 for Gradle 5.0
Upgrading TestNG would require more investigation as the Gradle build contains the following reason: `later versions break test cross-version test filtering`
