### ISSUE TITLE
Let TAPI clients discover forked processes more easily

### ISSUE THREAD

**Issue by tcfurrer** [gradle/gradle#6001]
The netbeans gradle plugin could benefit from a Gradle API that exposes the PID of the JVM process(es) that are spawned when running application, tests, etc.  This would allow for more convenient/automated connections to run profiler on those processes.  Currently the only option is to manually point the profiler to the processes, but it would be nicer if any tool calling Gradle could automate that.

This API would make most sense for cases where the gradle tasks being executed only result in a single application/test JVM being spawned.  In cases where multiple JVMs are spawned (for example when running tests in parallel), the API could return the whole list of PIDs, but the usefulness in that case is less clear.

Related issues:
https://github.com/kelemen/netbeans-gradle-project/issues/106
https://github.com/kelemen/netbeans-gradle-project/issues/394

**Comment by kelemen** [comment]
There is no need for a list, if a task was capable to call back to the client of the Tooling API (if there is any) with a somewhat custom message (e.g., a map mapping strings to strings and boxed primitives).

**Comment by oehme** [comment]
I think this could be modelled as a progress event (similar to what we already have for tasks and tests in the Tooling API). This event could be fired whenever we fork a new process and provide that processes PID. We could fire another one when the process is killed.

**Comment by kelemen** [comment]
Yes, I think that would be good, if the progress event is well defined. So that I can be confident that my code won't break in a subsequent Gradle version.
