### ISSUE TITLE
Transitive dependencies in Maven repositories are resolved without consideration of dependency attributes

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#6020]
When a module is resolved from a `maven` repository, and that module declares dependencies that are also resolved from a `maven` repository, then the transitive dependency is resolved without consideration of any consumer attributes, whether declared on the resolving configuration, or on the transitive dependency itself (via a component metadata rule).

This is due to the legacy component selection that is used when resolving transitive Maven modules.

This issue is resolved by using `enableFeaturePreview('IMPROVED_POM_SUPPORT')`.

### Expected Behavior
Consumer attributes should be considered when resolving transitive Maven modules.

### Current Behavior
Consumer attributes (declared on either `Configuration` or `DependencyMetadataDetails`) are ignored when resolving transitive Maven modules.

### Context
This issue is resolved by using `enableFeaturePreview('IMPROVED_POM_SUPPORT')`, and will be fixed when we make that option the default. This issue is just an explanation of the current behaviour.

### Steps to Reproduce (for bugs)
This build will successfully resolve the `compileClasspath` configuration.

```
apply plugin: 'java'

dependencies {
    implementation('org.junit:junit4-engine:5.0.0-SNAPSHOT')

    components.all {
        allVariants {
            withDependencies {
                it.each {
                    it.attributes {
                        it.attribute(org.gradle.api.internal.project.ProjectInternal.STATUS_ATTRIBUTE, 'XXXX' )
                    }
                }
            }
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url = 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}
```

Output of `gradle dependencyInsight --configuration compileClasspath --dependency junit-engine-api` gives:
```
> Task :dependencyInsight
org.junit:junit-engine-api:5.0.0-SNAPSHOT:20160616.110047-927
   variant "runtime" [
      org.gradle.status = integration (compatible with: XXXX)

      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]
```

Note the line `org.gradle.status = integration (compatible with: XXXX)`, which is incorrect.

**Comment by ljacomet** [comment]
Closing as `IMPROVED_POM_SUPPORT` will become the default in Gradle 5.0
