### ISSUE TITLE
Task 'assembleRelease' not found in root project 'android'  

### ISSUE THREAD

**Issue by hadjloo** [gradle/gradle#6026]
I'm trying to execute Signed APK with **gradlew assembleRelease** but the task is not available

I'm using vsCode - react-native and gradle

### Expected Behavior

I need gradlew assembleRelease to build a Signed APK for me
### Current Behavior

The gradlew cannot find assembleRelease task, so it doesn't work

### Steps to Reproduce (for bugs)

I'm using **Reactnative 0.54.0** and **react-native-cli 2.0.1** along side **gradle 4.8.1**

I have created a react-native project using **create-react-native-app myProjectName**

When I created the project, it doesn't include android and ios folders, so I added them manually.

I also installed gradle using **choco** and then created a wrapper for it using **gradle wrapper --gradle-version 4.8.1 --distribution-type all**

so I am developing react-native using microsoft **vsCode** and then see my application in action using **Genymotion** emulator, everything is fine

now, I want to generate the final **Signed APK** for play store, I'm using this guide provided by react-native 

[https://facebook.github.io/react-native/docs/signed-apk-android.html][1]

  [1]: https://facebook.github.io/react-native/docs/signed-apk-android.html

When I want to run **gradlew assembleRelease** I get this error

    C:\myApp\android>gradlew assembleRelease

    FAILURE: Build failed with an exception.

    * What went wrong:
    Task 'assembleRelease' not found in root project 'android'.

    * Try:
    Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    BUILD FAILED in 4s

what's wrong with assembleRelease? what should I do?

to add more info, I have to say that when I want to build this project in VSTS (TFS Online) I get this error

    2018-07-17T16:20:14.9268702Z ##[error]Error: Not found wrapperScript: D:\a\1\s\gradlew

this is available gradlew tasks

    C:\myApp\Android>gradlew tasks

    > Task :tasks

    ------------------------------------------------------------
    All tasks runnable from root project
    ------------------------------------------------------------
    
    Build Setup tasks
    -----------------
    init - Initializes a new Gradle build.
    wrapper - Generates Gradle wrapper files.
    
    Help tasks
    ----------
    buildEnvironment - Displays all buildscript dependencies declared in root project 'android'.
    components - Displays the components produced by root project 'android'. [incubating]
    dependencies - Displays all dependencies declared in root project 'android'.
    dependencyInsight - Displays the insight into a specific dependency in root project 'android'.
    dependentComponents - Displays the dependent components of components in root project 'android'. [incubating]
    help - Displays a help message.
    model - Displays the configuration model of root project 'android'. [incubating]
    projects - Displays the sub-projects of root project 'android'.
    properties - Displays the properties of root project 'android'.
    tasks - Displays the tasks runnable from root project 'android'.
    
    To see all tasks and more detail, run gradlew tasks --all
    
    To see more detail about a task, run gradlew help --task <task>
    
    BUILD SUCCESSFUL in 1s
    1 actionable task: 1 executed

and this is myApp\android\**build.gradle**

    project.ext.react = [
        bundleInStaging: true 
    ]
    task wrapper(type: Wrapper) {
        gradleVersion = '4.8.1'
    }
    android {
        defaultConfig {
            applicationId "com.sunkime.client"
        }
        signingConfigs {
            staging {
                keyAlias = "staging"
                storeFile = file("my-release-key.keystore")
                keyPassword = "qwert%$#@!"
                storePassword = "qwert%$#@!"
            }
            release {
                if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                    storeFile file(MYAPP_RELEASE_STORE_FILE)
                    storePassword qwert%$#@!
                    keyAlias qwert%$#@!
                    keyPassword qwert%$#@!
                }
            }
        }
        buildTypes {
            debug {
                applicationIdSuffix ".debug"
            }
            staging {
                applicationIdSuffix ".staging"
                signingConfig signingConfigs.staging
                minifyEnabled true
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            }
     
            release {
                applicationIdSuffix ".release"
                signingConfig signingConfigs.release
                minifyEnabled true
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            }
        }
    }

I also used **gradlew clean** and no difference

### Your Environment

 * Build scan URL: 

I also asked the same question in stackoverflow, : [here](https://stackoverflow.com/questions/51397363/task-assemblerelease-not-found-in-root-project-android)

**Comment by oehme** [comment]
Please provide a reproducible example project. You probably didn't include your Android subproject in settings.gradle.

**Comment by hadjloo** [comment]
should I add my entire app? or just the **android** folder?

**Comment by oehme** [comment]
I'm not asking for your app, just for a small example that reproduces the problem you are seeing.

**Comment by hadjloo** [comment]
@oehme I've uploaded a simple sample of my app here

http://sunki.me/WebApi/Client.rar

you can download it and test it.
Sorry for its large size (90MB) I wanted you see what I am using

I'm looking forward to hearing from you

**Comment by oehme** [comment]
You are calling Gradle in your root folder, which is not a Gradle project. Either call Gradle in the Android project folder or put the `settings.gradle` in your root project and include the Android project from there.

**Comment by hadjloo** [comment]
I couldn't fix the problem, could you really build it? can you tell me how did you released this project?

I tried in android folder and in root, nothing changed, I can't get your point, 
can you please try to build this sample project and tell me what should I do to get it work?

**Comment by okergaye** [comment]
Elaborate. That link did not help me figure out what to do.

**Comment by brysonandrew** [comment]
I had this issue when trying to release my Android app with React Native.

Basically I hadn't set up gradle correctly.

At the time I hadn't run `react-native eject` or in my case `expo eject` so I made my own android folder (not a good idea) and tried setting everything up from there.

I fixed it by running `expo eject` and then following the instructions here https://facebook.github.io/react-native/docs/signed-apk-android.

**Comment by tucson-tom** [comment]
I just ran into this issue with a normal Java app.  Turned out to be that the SDK for the compileSdkVersion/targetSdkVersion was not installed on the target system.  `assembleRelease` worked fine after installing the correct Android SDK.  The error message that gradle emits is quite useless since it doesn't provide any comprehensible context.  Only by launching Android Studio on the system did the real error finally show up.

**Comment by dorklord23** [comment]
In my case, the solution is to use `cd android` first before running `./gradlew assembleRelease`

**Comment by frackinfrell** [comment]
I had the same issue on a native Android build on VSTS and tried most of the items here.  Finally found out that the username for VSTS had changed and that caused the SDK location in `ANDROID_HOME` to be incorrect.

**Comment by alexcroox** [comment]
@dorklord23 I'm having the same issue, the list of tasks is different depending on the folder you execute gradlew from. I've opened the question here: https://stackoverflow.com/questions/58826949/gradlew-tasks-returns-different-results-depending-on-calling-directory

Weirdly it works fine from my local machine, but not on my CI (CircleCi)

**Comment by Waguynho** [comment]
For me works setting the ANDROID_HOME and delete file local.properties with "sdk.dir=C\:\\Users\\Me\\AppData\\Local\\Android\\Sdk". When gradle does not find the local properties It search in ANDROID_HOME

**Comment by kmanishk1** [comment]
Open the android folder in Android Studio and then run the command concerning `assembleRelease`. Works just fine.

**Comment by CallmeKingsley** [comment]
if you are using Fastlane, the issue is located in your Fastlane lane under grandle 

eg gradle(task: "clean assembleRelease")

**Comment by bulgarian-beast** [comment]
I have finally solve this error:

You have to check, one by one each versions of your dependencies in your pubspec.yaml.
During one week I got stuck bcs my version of path_provider package wasn't the latest.

**Comment by khoihuynhInfo** [comment]
You  can try remove platfrom 
using command: rm -rf platform
This work with me 👍

**Comment by fanshanhong** [comment]
> I just ran into this issue with a normal Java app. Turned out to be that the SDK for the compileSdkVersion/targetSdkVersion was not installed on the target system. `assembleRelease` worked fine after installing the correct Android SDK. The error message that gradle emits is quite useless since it doesn't provide any comprehensible context. Only by launching Android Studio on the system did the real error finally show up.
> 
> Edit: Never mind. This still does not work. But running Android Studio causes the build to succeed and further `assembleRelease` builds work fine, but pulling a fresh copy of the repo from git goes right back to the error message. So Android Studio is doing something to the project that makes CLI gradle work. Frustrating.
> 
> 2nd edit: `local.properties` was missing and triggered the error. Running Android Studio creates it during a sync but the file itself specifically says to NOT include it in version control. It contains the path to the Android SDK in my project and that's it. The gradle error message and logging options do not indicate that this missing file could be the issue. Since gradle underpins most Android development, I consider this to be a bug in gradle.

Yes!  You are right.   I according to the 2nd edit, add a  local.properties file to root project and add sdk.dir=xxx.  After that ,   the command  gradlew assembleRelease works fine.

Thank you!

**Comment by hanimhanna** [comment]
> > I just ran into this issue with a normal Java app. Turned out to be that the SDK for the compileSdkVersion/targetSdkVersion was not installed on the target system. `assembleRelease` worked fine after installing the correct Android SDK. The error message that gradle emits is quite useless since it doesn't provide any comprehensible context. Only by launching Android Studio on the system did the real error finally show up.
> > Edit: Never mind. This still does not work. But running Android Studio causes the build to succeed and further `assembleRelease` builds work fine, but pulling a fresh copy of the repo from git goes right back to the error message. So Android Studio is doing something to the project that makes CLI gradle work. Frustrating.
> > 2nd edit: `local.properties` was missing and triggered the error. Running Android Studio creates it during a sync but the file itself specifically says to NOT include it in version control. It contains the path to the Android SDK in my project and that's it. The gradle error message and logging options do not indicate that this missing file could be the issue. Since gradle underpins most Android development, I consider this to be a bug in gradle.
> 
> Yes! You are right. I according to the 2nd edit, add a local.properties file to root project and add sdk.dir=xxx. After that , the command gradlew assembleRelease works fine.
> 
> Thank you!

how should i add it can you explian?! plz

**Comment by adilexperience** [comment]
For those who are still struggling. try this, my issue is resolved.

https://stackoverflow.com/a/76994264/10601559
