### ISSUE TITLE
Mapped `Provider` should correctly delegate `Task` dependencies

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#6036]
The use case for this issue is pretty tricky. Under certain scenario mapped `Provider` should expose the original `Task` dependencies. Other time, it should expose the returned type `Task` dependencies. Finally, on some other time, it should not expose any `Task` dependencies and it may even be an error having a dependency on that `Provider`.

### Expected Behavior

Let's explore what we expect under every scenario to lock down the behavior.

### Current Behavior

Task dependencies are lost everytime a `Provider` is mapped.

### Context

See https://github.com/gradle/gradle/pull/5504
See https://gradle.slack.com/archives/C5DTC5KGC/p1532004795000074

### Your Environment

 * Build scan URL:

**Comment by lacasseio** [comment]
User this scenario:
```
class Producer extends DefaultTask {
    @OutputFile
    final RegularFileProperty outputFile = newOutputFile()
    
    @TaskAction
    void produce() {
        outputFile.asFile.get().text = "Produced by $name"
    }
}
class Consumer extends DefaultTask {
    @InputFile
    final RegularFileProperty inputFile = newInputFile()
    
    @TaskAction
    void consume() {
        println "Consumed from $name: '${inputFile.asFile.get().text}'"
    }
}
task producer(type: Producer) {
    outputFile = layout.buildDirectory.file("out.txt")
}
task consumer(type: Consumer) {
    inputFile = producer.outputFile
}
tasks.register("foo", Consumer) {
    inputFile = tasks.withType(Consumer).named("consumer").map { task.inputFile }
}
```
The executed task should only be `foo` and `producer`.

**Comment by lacasseio** [comment]
Given the same scenario as above, if the task `foo` depends only on the location of the file, then it shouldn't have any task dependency on `producer` and only `foo` should be executed. However, in this scenario, if both task `provider` and `consumer` were lazy, they would need to be realized.

To solve this scenario, it would be valid to introduce something more rich to express you are depending on a property of the file that doesn't require the task execution.

**Comment by wolfs** [comment]
I think we discussed having two kinds of `map` - one that leaves the input comprehension (including task dependency information) intact and only maps the values and another one which works like it does now - loose all the extra information of the current provider.

We probably should be introducing that new `map` method now to solve this use case. WDYT?

**Comment by lacasseio** [comment]
I would be careful with adding another `map` method simply because it can confuse users and have them use the more expensive and less correct one because it seems to work in all the case they care without asking questions. I think it would be better to model more strongly what it means to depend on a smart value (with task dependencies) vs dumb value (without task dependencies). Given that it's possible.

**Comment by lacasseio** [comment]
We have to be careful not to become too crazy about modeling too. Still, could you explain what you have in mind with another `map` method so it's documented and we have a better understanding.

**Comment by mkobit** [comment]
Related to https://github.com/gradle/gradle/issues/5706

**Comment by adammurdoch** [comment]
Initial support for this added via https://github.com/gradle/gradle/pull/6722.

These kinds of providers now carry information about the producer task:

- A `TaskProvider` created using one of the methods of `TaskContainer`.
- A task's `@OutputFile RegularFileProperty` and `@OutputDirectory DirectoryProperty` property.
- When mapping a provider on this list (including this item).

There's some validation missing, and handles (intentionally) only file type values. I think we should close this issue as done and add new issues for any later changes we want to make.

**Comment by adammurdoch** [comment]
More fixes in https://github.com/gradle/gradle/pull/6775
