### ISSUE TITLE
Gradle should not keep invoking File.listRoots but should consider cache the info.

### ISSUE THREAD

**Issue by FuminZhou** [gradle/gradle#6042]
### Expected Behavior
In java 10 for Windows system, the File.listRoots method's performance has degraded significantly compare to previous versions.  Some systems more significant than others.  The time could increase from sub ms, to sub seconds depends on the System.

Gradle as of 4.9, observed in 4.6, 4.7, 4.8, 4.8.1, invokes this method extensively depending on projects configuration, but foresee-able, multi-complex-projects gradle build could be impacted much more significantly by this.

Though the issue could be said as a Java issue, Oracle did indicate that Application could choose to use some cache mechanism regarding to File system rather than expecting java to do the caching.

Since the root files is not expected to change regularly - or at least not in between a build process, it would make sense to establish a cache of this, instead of invoking listRoots all the time.  For common systems, this info is not expected to be big either, thus impact on memory should be nominal making it a good candidate for caching.

### Current Behavior
Particularly, org.gradle.api.internal.file.FileOrUriNotationConverter, about line 101:
            for (File file : File.listRoots()) {
would invoke the listRoots every time the convert method is invoked.

Changing to:
            if (staticFileRootCache == null) {        // have to declare this as a static variable.
                  synchronized (staticLock) {           // have to declare this as a static variable.
                        if (staticFileRootCache == null) {
                              staticFileRootCache = File.listRoots();
                        }
                  }
            }
 
            for (File file : staticFileRootCache) {

should be able to avoid the multiple calls to File.listRoots()

a quick search in gradle 4.8.0 source code shows there are a couple of groovy files (some seems to be tests related) also uses the File.listRoots.  Not quite certain those should also be changed.

### Context
For one of multi-project build, after we switch over from java 8/9 to java 10, gradle build time jumped from 8 minutes to >6 hours!

### Your Environment
 * Build scan URL:

**Comment by oehme** [comment]
Please try put the lates nightly, this was already fixed.

**Comment by FuminZhou** [comment]
??? oehme, Why do you say this is fixed? I see that previous change moved the File.listRoots to be within the URI_SCHEME.matcher.  OK, so maybe it would be invoked left often... but still, when it does get passed that, every time it would call the File.listRoots directly - which so far in 11-ea is still a slow operation.  - And I propose the code should cache the result of the File.listRoots.

**Comment by FuminZhou** [comment]
I mean "less often" by the "left often"...  So it probably is an improvement, but...

**Comment by oehme** [comment]
Please measure with the latest nightly. If there is still a problem, we can improve it further.

**Comment by FuminZhou** [comment]
Just use notationString that matches the URI_SCHEME, you can try it out.  Especially if that is used hundreds of times.

**Comment by oehme** [comment]
I'm not doubting that you can construct a problematic case. My question is: When does that happen in your build?

**Comment by FuminZhou** [comment]
Sigh... you probably would call it bad practice..., but in our org, we have some common stuff shared in a network drive "S:"  - and it looks some engineers assumed everybody would put thing in their "C:"... we have a todo item to clean those up..., and a lot more others... that is how we bumped this issue - to be fair, we do not know exact which ones are causing the issue - just the profiling is telling us this listRoots is invoked thousands of times... - we do have many subprojects..  well, also to be fair, some of our machines the listRoots was not that costly, but some are.
