### ISSUE TITLE
Run tests with randomized HashSet order

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#6048]
Reproducibility is a major issue for Gradle: a lot of our logic and optimizations depend on things happening in the same order. Yet from time to time we bump into [issues with reproducibility](https://github.com/gradle/gradle/issues/5920), and often the fix is to replace a `HashSet` with a `LinkedHashSet`, or some similar change to enforce consistent ordering.

Consistent ordering is guaranteed by:
- linked structures like `LinkedHashMap` and `LinkedHashMultimap`
- sorted structures like `TreeMap`
- `HashSet` and `HashMap` with entries/keys having consistent `hashCode()` implementations (most typically a `String`)

A naïve solution would be to ditch using data structures that don't retain consistent order of elements completely, but it would have performance implications. In some cases it is irrelevant to keep track of element order, and then a `HashMap` or a `HashSet` could outperform a linked or sorted variant by a significant margin.

So the question becomes: how do we ensure that we use the right collection/map type? This issue is about avoiding using a container that doesn't guarantee consistent ordering where we should. We do not aim to avoid unnecessarily retaining consistent ordering.

Here's a two-step approach (original idea by @melix) to significantly decrease the changes of a similar problem occurring in the future:

- Make sure the intention is clear when we create the data structure: instead of writing `new HashSet<>()`, we could use something like `Sets.createUnordered()` vs `Sets.createOrderRetaining()` to get a `LinkedHashSet`. Doing this would ensure that a developer can't accidentally choose the wrong type, and the resulting code would also clearly document their original intent. We could even introduce a Checkstyle rule to forbid using direct constructor calls (and calls to Guava's `Sets.new*()` as well).
- When running tests, for `Sets.createUnordered()` we could return a different implementation that intentionally mixes up the order of elements every time it's iterated to shake out code that depends on consistent ordering without using a data structure to guarantee it. We could run unit tests and embedded integration tests in this mode, while forked integration tests, performance tests etc. could run normally to avoid performance impacts. Unit tests and embedded integration tests would provide more than sufficient coverage.

**Comment by tcfurrer** [comment]
Great idea, but doesn't seem like it's really Gradle's responsibility?  The JDK itself missed the boat to provide the ability to optionally control the ordering of unordered collections.  Wish they could somehow add that feature back in retroactively while maintaining backward compatibility, yet without any performance tax, etc.  And this idea isn't really unique to test runs.  You could just as well want to fiddle with unordered collections iteration while debugging code running in production.

**Comment by lptr** [comment]
To be clear, this issue proposes to run Gradle's own tests with this randomization to ensure that we don't accidentally introduce reproducibility issues in sensitive areas of the Gradle product itself. It is not about a feature we would provide for users.

**Comment by tcfurrer** [comment]
Oops, thanks for clarifying.  Sounds like you guys are in the same boat as the rest of us Java coders... wishing the JDK had provided a convenient debug option to control the order of all its un-ordered collections in various ways, just to make debugging easier sometimes.
