### ISSUE TITLE
Docs are unclear on how JavaExec parses --args / argsString

### ISSUE THREAD

**Issue by kenzierocks** [gradle/gradle#6056]
The documentation of [`setArgsString(String)`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/JavaExec.html#setArgsString-java.lang.String-) states that `args` "will be parsed to [an] argument list." However, it doesn't describe exactly what syntax is acceptable for parsing. I'm mostly wondering if quoting is supported, and if both `'` and `"` are acceptable quote delimiters.

### Expected Behavior
The documentation should inform me what to expect from argument parsing.

### Current Behavior
I need to manually test argument parsing to determine how it works.

### Context
Manually testing how a particular function works in Gradle is difficult, and requires a whole project setup just to determine the effect of one function. It'd be much faster if I could just read the docs and know if I need to handle something myself.

Manual testing also won't tell me if there's special symbols I need to avoid, and since the current documentation does say that it parses the input, there could be unexpected special symbols, such as `$` or `` ` ``.

### Your Environment
Gradle 4.9

**Comment by marcphilipp** [comment]
I agree that we should provide more details and a few examples in the Javadoc. IIRC it supports single and double quotes and space as a separator.

@blindpirate Do you have time to improve the documentation?

**Comment by blindpirate** [comment]
Thanks for the advice @kenzierocks . Internally we use Ant's `CommandLine.translateCommandLine` to process this string. If you want to know what's the behavior of parsing quote, take a look at [the test](https://ant.apache.org/manual/api/org/apache/tools/ant/types/Commandline.html#translateCommandline-java.lang.String-).

I'm wondering which kind of clarification you expect. Would you like to provide a PR with the clarification which satisfies you most?

**Comment by kenzierocks** [comment]
Sure, I can do that.

**Comment by kenzierocks** [comment]
Pull request created. #6081.

**Comment by blindpirate** [comment]
Thanks @kenzierocks !
