### ISSUE TITLE
As a build author, I would like to know where a given task is coming from

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#6058]
### Expected Behavior
Given a task name, I would like to know which plugin or project or script the task creates it. 

I am willing to query this myself through the CLI or Tooling API, or have this written in some other task's report.

### Current Behavior
I do not have a "current" model way of determining provenance for a task. The best alternative I have is to guess by applying plugins and using the task report or a Tooling API query.

### Context
I think we've known this to be a user need for some time, and tried to address this in different ways. I could not find an issue already for this, however.

I believe a significant percentage of users would benefit from this functionality, so even if we have a way to achieve incremental improvement, I imagine users would appreciate it.

**Comment by big-guy** [comment]
This information is now in build scans
