### ISSUE TITLE
The application plugin's run task should not change the working directory

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#6074]
Gradle 4.9 added support for [passing arguments to JavaExec tasks](https://docs.gradle.org/4.9/release-notes.html#command-line-args-supported-by-javaexec). By default, JavaExec tasks [change the working directory to the project directory](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html#org.gradle.api.tasks.Exec:workingDir). However, this default behavior is confusing when using the application plugin's `run` task (which is a JavaExec task) and passing relative file paths as part of the arguments.

### Expected Behavior

Assume a multi-project and a directory structure like

    + $HOME
      |
      + development (contains root build.gradle file and input-file.txt file)
         |
         + app (contains app build.gradle file)
         |
         + lib (contains lib build.gradle file)

When running an application like

    cd ~/development
    ./gradlew app:run --args="--input input-file.txt"

I would expect the application to look for `input-file.txt` at `~/development/input-file.txt`.

### Current Behavior

The application looks for `input-file.txt` at `~/development/app/input-file.txt`.

### Context

Now that arguments can be passed to JavaExec tasks, it's convenient to use that feature as a drop-in replacement for calling the start scripts that can be generated by the application plugin. However, currently relative file paths need to be adjusted to take the implicit change of the working directory into account.

### Steps to Reproduce (for bugs)

I wouldn't necessarily consider this to be a bug, but rather an ask for a change in behavior to increase convenience.

### Your Environment

```
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Windows 10 10.0 amd64
```

**Comment by ljacomet** [comment]
Sorry for the late reply

There is no way to fix this because what you pass on the CLI is passed as-is to your application. And it is that application's working directory that comes into play.
There would be no reason to run this based on the root project of the build instead of the app project's directory.

**Comment by sschuberth** [comment]
> There would be no reason to run this based on the root project of the build instead of the app project's directory.

Well, I tend to disagree. From the user's perspective who's running the Gradle wrapper, the current working directory is `~/development` in my example. It's nontransparent that Gradle seems to internally change the CWD when running the application so that it becomes the app project's directory instead of leaving it unmodified.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by big-guy** [comment]
We don't think we want to change this default. Relative file resolution within a project are almost entirely resolved relative to the project.  There are at least four reasonable working directories:

- The current working directory that ran Gradle
- The root of the project
- The project directory
- The installation directory

The project directory seems like the least bad option. 

A couple of workarounds:
Install and run the app directly:
```
./gradlew install && ./app/build/install/app/bin/app --input input-file.txt
```

Set the working directory for the run task to the rootDir:
```
run {
   workingDir = rootDir
}
```
