### ISSUE TITLE
Gradle 4.8.1 ~ 4.9: Using implementation with local dependency included in settings.gradle but not in build.gradle gives cryptic compiler error

### ISSUE THREAD

**Issue by filpano** [gradle/gradle#6077]
### Expected Behavior
I have a project that includes several local projects as follows:
> --- appA/settings.gradle
> include ': libA'
> project(':libA')
> include ': libB'
> project(':libB')
> ...
> --- appA/build.gradle
> implementation project(':libA')
> ... // libB not included here

Some package and symbol from `libB` is then used in `appA`, despite not being listed as a compile dependency. When I perform `./gradlew clean build`, Gradle should, as with using `compile` with previous versions, simply give out compiler errors indicating the some imported symbol could not be found including line numbers.

### Current Behavior
Often (not always, seems to be project dependent), instead of the expected behaviour mentioned above, 
the `compileJava` task for the given project will fail as follows:

   > Note: Some input files use or override a deprecated API.
   > Note: Recompile with -Xlint:deprecation for details.
   > 1 warning
   >
   > \> Task :compileJava FAILED
   > 2 errors
   >
   > FAILURE: Build failed with an exception.
   >
   > \* What went wrong:
   > Execution failed for task ':compileJava'.
   > \> Compilation failed; see the compiler error output for details.
   >
   > \* Try:
   > Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Note that this is the only error being given. There is no compiler output - using `--info`, `--stacktrace`, `--debug` does not yield anything more than the above. In IntelliJ 2017.1.4, there is additionally (under "Messages") an error message that reads:

   > Error: java: Compilation failed: internal java compiler error

Basically, gradle does not seem to be redirecting the compiler output to stderr in these cases (as I am assumming there *has* to be some, seeing how opening the classes in the IDE shows the error).

### Context
This issue has caused me quite a bit of headaches in the last two days while trying to switch from `compile` to `api`/`implementation` to prevent unwanted transitive dependencies in our projects. It was not immediately clear what is going on, and only after opening the relevant class was it shown that dependencies that were previously transitively imported were now (rightfully) to blame.

### Steps to Reproduce (for bugs)
As far as I can tell, the above settings/build.gradle setups above triggered the issue. The issue seems to also be present in Gradle 4.9, using the same steps.

### Your Environment
Unfortunately I am not at liberty to provide a build scan at this time. Some potentially useful information:

   > $ java -version
   openjdk version "1.8.0_171"
   OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
   OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

   > $ ./gradlew --version
   Gradle 4.8.1   
   Build time:   2018-06-21 07:53:06 UTC
   Revision:     0abdea078047b12df42e7750ccba34d69b516a22
   Groovy:       2.4.12
   Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
   JVM:          1.8.0_171 (Oracle Corporation 25.171-b11)
   OS:           Linux 3.16.0-4-amd64 amd64
   
   > $ lsb_release -a
   Distributor ID: Debian
   Description:    Debian GNU/Linux 8.11 (jessie)
   Release:        8.11
   Codename:       jessie

**Comment by oehme** [comment]
Please provide a reproducible example project. Otherwise it's nearly impossible to tell what the problem may be.

**Comment by filpano** [comment]
Hi - I'll attempt to do some later this evening and try to make it available for testing. Thanks for the response!

**Comment by ghale** [comment]
I'm going to close this for now.  If you feel there is still an issue that needs to be addressed, please provide an example that we can use to reproduce.
