### ISSUE TITLE
Perform cache cleanup at end of build session

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#6084]
In order to let users deactivate cache cleanup using the existing option mechanisms and to make it more consistent, cleanup (of Gradle user home) should be performed at the end of the build session instead of when the daemon is shut down.

## Deliverables

- [ ] Move cleanup of Gradle user home to end of build session
- [ ] Introduce property to disable cache cleanup and use it for the project directory and the Gradle user home

**Comment by lukeu** [comment]
>  Introduce property to disable cache cleanup and use it for the project directory and the Gradle user home

Did a7257ab / #6371 resolve this?

**Comment by marcphilipp** [comment]
Only partially, namely for the Grade user home. Setting it in `<project-dir>/gradle.properties` currently has no effect.

**Comment by NoahAndrews** [comment]
This would definitely still be useful, so that we can configure cache cleanup per-project.

**Comment by TWiStErRob** [comment]
I found this in code (7.4.2):
``// TODO Will be implemented without hard-coded access to `$GRADLE_USER_HOME/gradle.properties` for 5.1 in #6084``

**Comment by bigdaz** [comment]
Gradle User Home cleanup can now be configured via an init-script, which satisfies the requirements of this issue.
Docs here: https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:cache_cleanup
