### ISSUE TITLE
Gradle should make it easy to use the highest available version matching some base version

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#6102]
In earlier versions of Gradle, it was easy for a build to depend on the highest `3.x` version of a dependency, using the `3.+` dependency syntax.

As part of fixing #2869 and #4180, we chose to interpret the `3.+` version as: "accept any version in the '3.+' range". This is the same way as we interpret the range `[3, )`.

Given 2 different dependencies on the same module, Gradle will attempt to find a non-conflicting match. So given the versions `3.3` and `3.+`, Gradle would choose `3.3` as the best match.

Unfortunately, this change means it is now difficult for a build to depend specifically on the _highest_ version in the `3.x` version series. 

### Expected Behavior
One of the following: 
- Reinstate the old behaviour where `3.+` means exclusively "the highest version starting with '3'".
- Consider all ranges with no inclusive upper bound to mean exclusively "the highest version in the range". This would include `3.+` and `[3, 4)`, but not `[3, 3.5]`
- Provide a simple alternative syntax that specifies "the highest version with a major version `3`".

### Current Behavior
- `3.+` means  "any version starting with '3'". Gradle will choose the highest _in the absence of other constraints_.
- `[3.0, 4)` means "any version >= 3.0 and < 4". Gradle will choose the highest _in the absence of other constraints_.
- There is no alternative syntax, except `latest.integration`, which does not permit restriction based on a major version prefix.

### Context

Refer to the following issues: #5818, #2869, #4180

**Comment by bigdaz** [comment]
To clarify, we changed the behaviour of version range resolution in 2 steps:
- In Gradle `4.3` we changed it so that when resolving `[1.0, 2.0)` and `1.1` we'd pick `1.1`
- In Gradle `4.7` we changed it so that when resolving `1.+` and `1.1` we'd pick `1.1`

We have received no issue reports for the former change, but the latter change has prompted numerous issues.

**Comment by ljacomet** [comment]
After some internal discussion, it has been agreed to revert to the old behavior for resolving `1.+` and `1.1` to be the currently highest `1.x`, that is restore the behavior of Gradle 4.6 and before.

**Comment by ljacomet** [comment]
This has been fixed, commit had wrong issue number
