### ISSUE TITLE
Slow mergeDebugAssets step with gradle 4.8

### ISSUE THREAD

**Issue by darind** [gradle/gradle#6110]
### Context

I have a simple Android application with a blank activity containing lots of static files in the `app/src/main/assets` folder. I have added around 8500 javascript files that will be used by the app (think of the `node_modules/@angular` NPM package added to the `assets` folder).

In gradle < 4.8 this application builds in less than 1 minute (`:app:assembleDebug` step).

In gradle >= 4.8 the application takes forever (more than 30 minutes) freezing at the `:app:mergeDebugAssets` step. 

I noticed that there is a [**change in gradle 4.8**](https://github.com/gradle/gradle/issues/4502) in which the number of workers has been reduced to the number of available CPU cores.

If I hardcode the `org.gradle.workers.max` property to a sufficiently large number (for example 1000), the app builds much faster but on machines with less resources it will fail with OOM errors (this wasn't the case with gradle < 4.8 even though the build was consuming lots of resources).

### Steps to reproduce

1. Use Android Studio to create a new application with a blank activity
2. `npm i @angular` in some separate folder and then copy `node_modules` to the `app/src/main/assets` of the newly created Android application
3. Make sure you use at least gradle 4.8 (`gradle/wrapper/gradle-wrapper.properties`):

```
#Fri Jul 27 10:29:51 EEST 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.8-all.zip
```
4. Invoke the `:app:assembleDebug` step

**Comment by oehme** [comment]
This is already fixed for 4.10. Please try out the latest nightly.

**Comment by condesales** [comment]
@oehme did try out 4.10-rc-1 and I get the following error message
```
Could not find org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.2.60.
Searched in the following locations: file:/Users/felipe/.gradle/caches/4.10-rc-1/embedded-kotlin-repo-1.2.60-2/repo/org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable/1.2.60/kotlin-scripting-compiler-embeddable-1.2.60.jar
Required by:
    project :buildSrc
```

**Comment by oehme** [comment]
@bamboo Any ideas?

**Comment by tagantroy** [comment]
@condesales same problem
`> Could not resolve all files for configuration ':buildSrc:kotlinCompilerPluginClasspath'.
   > Could not find org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.2.60.
     Searched in the following locations: file:/Users/ivan.balaksha/.gradle/caches/4.10-20180810170449+0000/embedded-kotlin-repo-1.2.60-2/repo/org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable/1.2.60/kotlin-scripting-compiler-embeddable-1.2.60.jar
     Required by:
         project :buildSrc
   > Could not find org.jetbrains.kotlin:kotlin-sam-with-receiver:1.2.60.
     Required by:
         project :buildSrc
`

**Comment by tagantroy** [comment]
@oehme should i create issue in this repo or kotlin-dsl?

**Comment by oehme** [comment]
In the Kotlin DSL repo please
