### ISSUE TITLE
wtp-eclipse: wrong facet version with sourceCompatibility 9 or 10

### ISSUE THREAD

**Issue by clo-vis** [gradle/gradle#6133]
The generated **org.eclipse.wst.common.project.facet.core.xml** contains the wrong version for the facet _jst.java_ if _sourceCompatibility_ is 9 or 10. 

### Expected Behavior
with sourceCompatibility = 9
`<installed facet="jst.java" version="9"/>`

with sourceCompatibility = 10
`<installed facet="jst.java" version="10"/>`

### Current Behavior
with sourceCompatibility = 9
`<installed facet="jst.java" version="1.9"/>`

with sourceCompatibility = 10
`<installed facet="jst.java" version="1.10"/>`

Because of this, the generated project always has the error "Java compiler level does not match the version of the installed Java project facet".

### Context
Any war project imported in Eclipse

### Steps to Reproduce (for bugs)
Import a project in Eclipse with 
```
plugins {
    id 'war'
    id 'eclipse-wtp'
}
sourceCompatibility = 10
```

### Workaround
```
eclipse {
    wtp {
        facet {
            facets = []
            facet name: 'jst.web', version: '2.4'
            facet name: 'jst.java', version: '10'
        }
    } 
}
```

**Comment by ecdragon** [comment]
I have the same issue, using recommended snippet in build.gradle:

```
sourceCompatibility = JavaVersion.VERSION_1_10
targetCompatibility = JavaVersion.VERSION_1_10
```

clo-vis workaround by hard-wiring facet name in eclipse task works. Also can manually edit Eclipse facet in the project after importing.
