### ISSUE TITLE
When the argument to `--args` starts with a `-` then it is sent to gradle instead of the run task

### ISSUE THREAD

**Issue by nik9000** [gradle/gradle#6140]
I'd like  `./gradlew run --args '-h'` to pass the `-h` to the run task. Instead `-h` is sent to gradle and I get a usage message.

### Steps to Reproduce

Sorry for not making a minimal reproduction but the shallow clone should make this pretty quick and I'm fairly sure this isn't an issue with our build files. This is what I'd like:

```
$ git clone --depth 1 https://github.com/nik9000/elasticsearch.git -b de_shadow_benchmarks
$ cd elasticsearch
$ ./gradlew -p benchmarks/ run --args '-h'
...

Usage: java -jar ... [regexp*] [options]
 [opt] means optional argument.
 <opt> means required argument.
```

But this is what happens:

```
$ git clone --depth 1 https://github.com/nik9000/elasticsearch.git -b de_shadow_benchmarks
$ cd elasticsearch
$ ./gradlew -p benchmarks/ run --args '-h'
USAGE: gradlew [option...] [task...]

-?, -h, --help            Shows this help message.
```

You can work around this by adding a leading space to the `--args` parameter like this:
```
$ ./gradlew -p benchmarks/ run --args ' -h'
```

But this is confusing and easy to forget.

**Comment by nik9000** [comment]
What about forcing `--args` to have a parameter?

**Comment by oehme** [comment]
`--args` is not known to the command line parser. It is only discovered later when your build is configured, as it is an option on the `run` task. Command line parsing happens long before any configuration of your build is known.

**Comment by nik9000** [comment]
I see.
