### ISSUE TITLE
improve maven -> gradle generation for kotlin

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#6146]
so... I did a `gradle init` on a maven module earlier, converting it. I wanted to use kotlin though. Groovy and Kotlin have a lot of syntax overlap, however the way the groovy code is currently generated, using single `'`s, no parenthesis on methods, and long form deps.

basically it's obnoxious to have to convert

```
    compile group: "com.vaadin", name: "vaadin-compatibility-themes", version:"8.1.3"
```
to
```
    compile( "com.vaadin:vaadin-compatibility-themes:8.1.3" )
```
when the latter is valid syntax in both language, and that's all I really want, is simply to generate the most cross compatible syntax. I don't need an option for kotlin generation, oh and it would  be nice if it started generating with `java-library/implementation` instead of `java/compile`

**Comment by adammurdoch** [comment]
This is improved somewhat in https://github.com/gradle/gradle/pull/6489, so that the conversion now uses the string notation. It should also now be much simpler to implement proper Kotlin DSL support for the Maven conversion. Would you be interested in contributing a fix?

**Comment by xenoterracide** [comment]
sorry for taking so long to get back to this... tbh, this is obviously not important enough to me to contribute a fix. Sorry, lame on my part.
