### ISSUE TITLE
Running gradle test in windows fails with java.lang.ClassNotFoundException: Corporation (misparsing of -Djava.vm.vendor="Oracle Corporation" option)

### ISSUE THREAD

**Issue by nicops** [gradle/gradle#6164]
### Expected Behavior
Should be able to run a test with gradle in Windows 10 with jvm 10.0.1.

### Current Behavior
gradle test fails when creating the Gradle Test Executor with `java.lang.ClassNotFoundException: Corporation`. The problem is that java.exe is instatiated with wrong arguments, more specifically, the problem is how the java class ProcessBuilder that is going to invoke java.exe is instantiated. So the `-Djava.vm.vendor="Oracle Corporation"` arguments gets misparsed.

### Context
When I first saw this problem, I thought immediately it was a problem with how java.exe was called because there was this Corporation option and there was no Corporation main class.

I've confirmed this is the problem by starting the gradle daemon, debugging it, setting a breakpoint inside DefaultExecHandle#start(), and removing the offending argument from the "arguments" field, then doing continue. The offending argument is `-Djava.vm.vendor="Oracle Corporation"` and the problem is the double quotes.

The root cause is that the ProcessBuilder class (java sdk code) doesn't behave properly when double quotes are included inside an Windows. And gradle doesn't take this into account. 

A small example of how ProcessBuilder behaves:

```
class ProcessBuilderBugMain {
    public static void main(String[] args) throws Exception {
        Process p = new ProcessBuilder(
                "java.exe",
                "-Djava.vm.vendor=\"Oracle Corporation\"",
                "-Djava.vm.version=10.0.1+10",
                "-cp",
                "./build/classes/java/main",
                "HelloWorldMain"
                ).inheritIO()
                .start();

        System.out.println("exit value was" + p.waitFor());

        Process r = new ProcessBuilder(
                "java.exe",
                "-Djava.vm.vendor=Oracle Corporation",
                "-Djava.vm.version=10.0.1+10",
                "-cp",
                "./build/classes/java/main",
                "HelloWorldMain"
        ).inheritIO()
                .start();

        System.out.println("exit value was" + r.waitFor());

        Process q = new ProcessBuilder(
                "java.exe",
                "-Djava.vm.vendor=\\\"Oracle Corporation\\\"",
                "-Djava.vm.version=10.0.1+10",
                "-cp",
                "./build/classes/java/main",
                "HelloWorldMain"
        ).inheritIO()
                .start();

        System.out.println("exit value was" + q.waitFor());
    }
}
```

The output is

```
Error: no se ha encontrado o cargado la clase principal Corporation
Causado por: java.lang.ClassNotFoundException: Corporation
exit value was1
Hello, World
exit value was0
Hello, World
exit value was0
```
I have a spanish operating system, but the first line basically means the Corporation main class hasn't been found. This is a small scale reproduction of the issue the gradle code is having.

At first I thought this behaviour was a bug in Java 10, but it is actually intended behaviour, as you can see here https://bugs.openjdk.java.net/browse/JDK-8131908

Not sure how to fix or workaround. Maybe the problem is in either `JvmOptions` or `ProcessBuilderFactory`, either the first one should generate it without quotes in the `formatSystemProperties` method, or the latter should escape them when instantiating the ProcessBuilder object. I didn't quite understood the actual source of the jvm options within the gradle code.

### Steps to Reproduce
Not 100% sure how to reproduce, but I guess installing jdk 10.0.1 in windows and the latest gradle version and running gradle test on any project should suffice.

**Comment by marcphilipp** [comment]
Sounds related to #6072.

**Comment by marcphilipp** [comment]
@nicops I could not reproduce the issue with a regular tests task on Windows 10 with JDK 10.0.2. Do you use a special configuration for your `test` task, i.e. sth. like the following?

```gradle
test {
    systemProperties System.properties
}
```

**Comment by nicops** [comment]
Yes. And the workaround mentioned on https://github.com/gradle/gradle/issues/6072 did the trick.

Closing this one as duplicate.

**Comment by marcphilipp** [comment]
@nicops Thanks!
