### ISSUE TITLE
Javadoc and Groovydoc tasks don't clean their output directories

### ISSUE THREAD

**Issue by grv87** [gradle/gradle#6168]
### Expected Behavior
`Groovydoc` tasks clean their destination directories before running. At least, `groovydoc` task provided by default by `groovy` plugin.

### Current Behavior
Destination directory isn't cleaned. If a class was removed from source, its documentation is still there. It can erroneously leak to website or release.

### Steps to Reproduce (for bugs)
1. Apply `groovy` plugin
2. Add some classes to `src/main/groovy` directory
3. Run `groovydoc`
4. Make sure that `build/docs/groovydoc/<package>/<class>.html` exists
5. Remove one class from `src/main/groovy`
6. Rerun `groovydoc`
7. See that `build/docs/groovydoc/<package>/<class>.html` still exists

**Comment by wolfs** [comment]
Has `Javadoc` the same problems?

**Comment by grv87** [comment]
I've tested `Javadoc`, it has the same problem

**Comment by grv87** [comment]
@lptr, you think this is a problem with `OutputDirectory` in general?

**Comment by grv87** [comment]
Tested with 4.3.1 and 3.0 too. The same problem, so, this is not a regression.

**Comment by wolfs** [comment]
This will be fixed in Gradle 5.0.
