### ISSUE TITLE
Support tag-specific junit5 tasks 

### ISSUE THREAD

**Issue by jcornaz** [gradle/gradle#6172]
Since gradle provide native support of the Junit5 platform, the JUnit team dropped support of their plugin. So the feature request [Support tag-specific Gradle tasks](https://github.com/junit-team/junit5/issues/579) will not be implemented by the Junit team.

### Expected Behavior
User should be able to create tag-specific tasks. Here is an example:
```groovy
task uiTest(type: Junit5Test) {
  includeTags = ['ui']
  excludeTags = ['integration']
}
```

### Current Behavior
Currently, user has to write a filter in the Juni5 configuration, using condition based on properties. Here is an example (comming from [this StackOverflow question](https://stackoverflow.com/questions/40891867/junit5-tag-specific-gradle-task/40912322#40912322)):
```
junitPlatform {
    filters {
        tags {
            exclude project.hasProperty('runIntegrationTests') ? '' : 'integration-test'
        }
    }
}
```

### Context
In my gradle build to be able to provide the following tasks:
* `test` run only unit tests
* `integrationTest` run integration tests
* `uiTest` run the UI test
* `check` (used by the build system)  run all tests

And I would like to be easy and safe to modify/add such tasks

### Your Environment
Gradle 4.9
Junit 5.2.0
Java 8+
Kotlin 1.2+

**Comment by oehme** [comment]
This is already possible, the `junitPlatform` extension is per `Test` task, so just create an additional `Test` task.

**Comment by jcornaz** [comment]
Ok thanks @oehme. Is that written somewhere in the documentation? I lost many hours looking for this feature.

**Comment by oehme** [comment]
It's in the [testing chapter](https://docs.gradle.org/current/userguide/java_testing.html#using_junit5)

**Comment by TWiStErRob** [comment]
For posterity: the syntax for this in Gradle 4.6+ is:
```gradle
task uiTest(type: Test) {
    useJUnitPlatform {
        includeTags 'ui'
        excludeTags 'integration'
    }
}
```

See https://stackoverflow.com/a/52245028/253468 for more.
