### ISSUE TITLE
Updating dependencies updates all, even those that are not selected

### ISSUE THREAD

**Issue by martofeld** [gradle/gradle#6174]
While using the gradle native dependencies lock I tried to update said file with a specific dependency yet multiple are updated.

### Expected Behavior
The expected behavior should be to update only the dependencies that are specified to be updated

### Current Behavior
Multiple dependencies are updated, even when not specified

### Context
I am trying to migrate from nebula-plugin to native gradle locks. The issue occurs after creating the lock files when attempting to update a certain library. Using Gradle plugin 4.9

My build.gradle is:
```
---
dependencies {
    def supportLibraryVersion = "27.0.1"
    def gsonVersion = "2.8.2"

    api("com.android.support:appcompat-v7:$supportLibraryVersion")
    api("com.android.support:recyclerview-v7:$supportLibraryVersion")

    api("com.google.code.gson:gson:$gsonVersion")
}
---
```

### Steps to Reproduce (for bugs)
1. Run `./gradlew dependencies --write-locks`. This generates the lock file as follows:
```
android.arch.core:common:1.0.0
android.arch.lifecycle:common:1.0.3
android.arch.lifecycle:runtime:1.0.3
com.android.support:animated-vector-drawable:27.0.2
com.android.support:appcompat-v7:27.0.2
com.android.support:recyclerview-v7:27.0.2
com.android.support:support-annotations:27.0.2
com.android.support:support-compat:27.0.2
com.android.support:support-core-ui:27.0.2
com.android.support:support-core-utils:27.0.2
com.android.support:support-fragment:27.0.2
com.android.support:support-vector-drawable:27.0.2
com.google.code.gson:gson:2.8.2
```
2. Auming we have a hotfix on a lib, change the variables to `supportLibraryVersion=27.0.2` and `gsonVersion=2.8.4`
3. Run `./gradlew dependencies --update-locks com.android.support:recyclerview-v7`. The lockfile remains as follows
```
android.arch.core:common:1.1.0
android.arch.core:runtime:1.1.0
android.arch.lifecycle:common:1.1.0
android.arch.lifecycle:livedata-core:1.1.0
android.arch.lifecycle:runtime:1.1.0
android.arch.lifecycle:viewmodel:1.1.0
com.android.support:animated-vector-drawable:27.1.1
com.android.support:appcompat-v7:27.1.1
com.android.support:recyclerview-v7:27.1.1 **<-Shouldn't this be the only updated?**
com.android.support:support-annotations:27.1.1
com.android.support:support-compat:27.1.1
com.android.support:support-core-ui:27.1.1
com.android.support:support-core-utils:27.1.1
com.android.support:support-fragment:27.1.1
com.android.support:support-vector-drawable:27.1.1
com.google.code.gson:gson:2.8.4 **<-This should not be updated**
```

### Your Environment
Gradle 4.9 and 4.8
Android Studio 3.2 Canary 16
Android Gradle Plugin 3.1.0

**Comment by ljacomet** [comment]
What you observe is the expected behavior.
Dependency locking can only lock a valid resolution result - that is something that would be resolved even without locking present.
When you upgrade `supportLibraryVersion` and `gsonVersion`, you tell Gradle to update _multiple_ libraries. And so when you resolve with relaxed locking, to allow for upgrades, all these libraries are indeed upgraded.

Also since you use only fixed versions, locking will only be useful in your case if these libraries themselves have dynamic versions declared.

Does this clarify the expected outcome?

**Comment by martofeld** [comment]
@ljacomet I understand what you say. But I still have a question. Lets say I have 2 modules with dynamic version, I publish version 1.2.0 and 2.2.0 respectively and then consume them as so
```
api ("com.package:module1:1.+")
api ("com.other.package:module2:2.+")
```

I lock my dependencies and the lockfile should look something like this
```
com.package:module1:1.2.0
com.other.package:module2:2.2.0
```

I then realize that module1 has an issue and publish a patch therefore having a version 1.2.1 and since time has passed, module2 now has a version 2.3.0 that I don't want to use.

So, to update the lock I run `./gradlew dependencies --update-locks com.package:module1` would this update module2 as well? 

If so, what the idea of specifying which modules I want to update? 
And if not, why does it update both in the case I have static versions? I only want to update those I told gradle to via the command

**Comment by ljacomet** [comment]
In that case the command will behave as you expect: only `com.package:module1` will get a newer version.

To be complete: if `com.package:module1:1.2.1` had itself a dependency on `com.other.package:module2` in a version higher than `2.2.0` then it would be updated as well.

**Comment by martofeld** [comment]
@ljacomet I have testes this and you are right. I just have one more question then, lets say I have locked with version 1.2.0 for module1, I proceed to publish versions 1.2.1 and 1.3.0 and the update the locks (always using 1.+ as the version). What version will the lock take?

**Comment by martofeld** [comment]
Thanks for you help, I will proceed to close the issue
