### ISSUE TITLE
Nebula recommender plugin 6.+ fails BomSupportPlugin smoke test

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#6177]
It appears to be a failure in our resolve fixture and not the plugin itself.

### Steps to Reproduce (for bugs)
Change `5.1.0` to `6.1.1` in 
https://github.com/gradle/gradle/blob/fb5374b105eaf8ecf700d80b5a8889db91b516de/subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/AbstractSmokeTest.groovy#L38

### Your Environment

 * Build scan URL: https://e.grdev.net/s/q2qcpd4i6ndli/tests/iptsm6im6po76-f62n4dgfn3rik?openStackTraces=WzBd

**Comment by ljacomet** [comment]
There is indeed a failure in the resolve fixture: we did not account for dependency reasons having new line characters (`\n`) and thus having entries span multiple lines.
However once that is changed, assertions need to be updated as it looks like the Nebula plugin now uses reasons on dependencies / constraints
