### ISSUE TITLE
OSGi plugin causes unnecessary build cache misses

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#6187]
I'm having an issue I think similar to https://issues.gradle.org/browse/GRADLE-1227.
Incremental task execution seems to work properly, but the task caching does not work properly.

- I have subprojects `api` and `core`
- `core` depends on `api`
- both have the `osgi` plugin applied

When I execute the build two times in a row, every actionable task is properly UP-TO-DATE.
But when I do `clean build` with build cache enabled, then only 9 of the 11 cacheable tasks are taken from cache.
`core:test` is reexecuted (and due to that or due to the same reason `core:jacocoTestReport`).
The reason is, that the `api` JAR has s different hash when calculating the cache key.
The only difference inside the `api` JARs is the `Bnd-LastModified` header in the manifest.

To validate it is the reason for the cache miss, I tried to exclude the header, but I also wasn't successfull in trying to do so.

I tried
```groovy
jar { manifest { instruction '-removeheaders', 'Bnd-LastModified' } }
```
this did not remove the header but only moved it down to be the last one while before it was near the top.

I tried
```groovy
jar { manifest { instruction 'Bnd-LastModified', '0' } }
```
this had no effect whats-o-ever.

I tried
```groovy
jar { manifest { instruction '-noextraheaders', 'true' } }
```
this removed the `Created-By` header and the `Tool` header and moved the `Bnd-LastModified` header down to the bottom of the manifest again.

Is the inability to remove the `Bnd-LastModified` header a separate issue I should report separately, or is this expected?
Should Gradle for improvement of binary build reproducability always suppress this header like it made the `WriteProperties` task that does not output a timestamp to generated properties files?

To validate my assumption I then resorted back to not apply the `osgi` plugin and then the JARs were identical and the cache was used properly for all 11 cacheable tasks.

If you want to have an example at hand, you can use the `v_3` branch of https://github.com/Javacord/Javacord where I struggle with this issue.

**Comment by lptr** [comment]
The caching issue is clearly caused by the `Bnd-LastModified` attribute being added. I tried to remove it in the past, but gave up after similar results. Are you sure the code that adds it is on the Gradle side?

**Comment by Vampire** [comment]
Well, either Gradle or something Gradle uses like the bnd tool.
I found a post on the bnd list by Luke from 2012 or so where he asked whether you can remove that attribute safely to get binary reproducible builds.
He didn't mention Gradle explicitly, but sounded like he talks about Gradle.
It was also at some point "fixed" that incremental build is ignoring that property as you can see in the linked issue.
Also if you Google for it, you find the recommendation to use the `-removeheaders` instruction to remove the header which seemed to partly work as it was not where the bnd tool usually had put it, but in the end of the attributes list, just as when I used the `-noextraheaders` instruction which made the other bnd-specific headers vanish and have the last modified header in the end again and the `Bnd-LastModified` instruction which should set it to a fixed value (you even do this in one of your tests) had no effect at all.

**Comment by wolfs** [comment]
The OSGi plugin has been deprecated and will be removed in 6.0: #9433 
Does the external plugin already solve your issues?

**Comment by Vampire** [comment]
I don't know, I didn't use the external plugin in that project yet.
But as you said, as the bundled `osgi` plugin is deprecated, let's just close this issue here.
