### ISSUE TITLE
Build scan email should provide alt text

### ISSUE THREAD

**Issue by nlwillia** [gradle/gradle#6192]
The html part of the email you receive to access a build scan wraps the link around an image without an alt tag.

```
<a href="https://scans.gradle.com/s/.../activate/...">
<img src="https://assets.gradle.com/img/email-build-scan-activate-cta.png" width="220px">
</a>
```

So if your email client is configured to block images, you don't see anything to click.  An alt tag or text link would fix that.

**Comment by big-guy** [comment]
@gradle/cloud-services ☝️

**Comment by eriwen** [comment]
@etiennestuder FYI

**Comment by etiennestuder** [comment]
We have fixed this and it will be live once we upgrade scans.gradle.com in production next time.
