### ISSUE TITLE
Support Eclipse in Play Plugin

### ISSUE THREAD

**Issue by eximius313** [gradle/gradle#6205]
[Documentation for Play plugin](https://docs.gradle.org/current/userguide/play_plugin.html#play_ide) states that `Gradle supports generating IDE metadata for IDEA only for Play projects at this time.` 

[sbteclipse](https://github.com/sbt/sbteclipse) supports Eclipse for SBT so it should be possible for Gradle to do it.

Could you please support Eclipse as well?

**Comment by oehme** [comment]
We have no plan to work on this, but you're welcome to provide a pull request.
