### ISSUE TITLE
Reduce default memory settings for daemon and workers

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6216]
We've improved Gradle's memory footprint a lot. The major version boundary would be a good opportunity to revisit the default heap size for a daemon and a worker. Currently they are

- 1GB for the command line client
- 1GB for the daemon
- 1/4th of physical memory for a worker (because we set no value)

I think more reasonable defaults would be:

- 64MB for the client
- 512MB for the daemon
- 256MB for a worker

**Comment by oehme** [comment]
We should also set some reasonable defaults for permspace/metaspace to lock down classloader leaks more quickly.

**Comment by jcbritobr** [comment]
Gradle 4 take too much memory for a simple development machine. Up to 2 Gb ram. Insane. I go out of resource in few times using intellij and gradle together. Hope you guys can fix this performance issue.

**Comment by oehme** [comment]
@jcbritobr You know that you can change the defaults, right? Also make sure it's actually Gradle slowing down your machine, not IntelliJ or some other program.

**Comment by jcbritobr** [comment]
![image](https://user-images.githubusercontent.com/6579862/43996920-0fb9c0a4-9da4-11e8-9b10-2be3ae9bd609.png)
I did. This daemon disrupts more than helps. There is no effective way to control heap sizing in java+ 8. It always get growing. The result is so many process hitting your memory.

**Comment by oehme** [comment]
> There is no effective way to control heap sizing in java+ 8. It always get growing

That's not true. Heap size is limited to what you specify with `-Xmx`.

**Comment by eriwen** [comment]
Oh my gosh friggin' yessss. We really wanted to do this before Gradle 3.0 but couldn't for a few reasons. I only regret that I have but 1 vote to give to this.
