### ISSUE TITLE
Gradle task log grouping breaks with multithreading

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6220]
Example:
```kt
project.tasks.register("foobar").configure {
    doLast {
        val pool = Executors.newSingleThreadExecutor()
        val pendingOutput = pool.submit { println("Foo") }

        pendingOutput.get()
        pool.shutdownNow()
        println("Bar")
    }
}
```

Outputs:
```
Foo

> Task :foobar
Bar

```

**Comment by oehme** [comment]
Please don't use your own executers. Use the [worker API](https://guides.gradle.org/using-the-worker-api/) instead.

**Comment by SUPERCILEX** [comment]
@oehme is there a way to get it without constructor injection? That forces clients to upgrade to 4.7 I believe.

**Comment by oehme** [comment]
I'm not sure what you mean - constructor injection in tasks has been there since Gradle 1.0

**Comment by SUPERCILEX** [comment]
Ohhhhhhhhh, my B. It's custom property injection that was added: https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskContainer.html#create-java.lang.String-java.lang.Class-java.lang.Object...-
