### ISSUE TITLE
Provide default value for JavaCompile header output

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6226]
On Java 8+ we should provide a conventional header output directory so that users don't have to configure this manually when they have `native` methods in their code.

This is a potentially breaking change as some users may have a custom workflow where they generate the headers separately and don't actually want header generation as part of JavaCompile.

**Comment by adammurdoch** [comment]
This was fixed in https://github.com/gradle/gradle/pull/12234. I think I forgot to add this to the release notes and mention it as a potential breaking change.

**Comment by adammurdoch** [comment]
Added to the release notes for 6.3: https://github.com/gradle/gradle/pull/12470
