### ISSUE TITLE
Support annotationProcessor in IDEA

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6227]
With the deprecation of annotation processors on the compile classpath, it is important that the `annotationProcessor` configuration works as expected with IDEA. There are different solutions to this

1. Put them into idea's PROVIDED scope so they are picked up automatically as before
2. Configure idea's processor path explicitly (@vladsoroka does IDEA have an explicit option for that?)

**Comment by melix** [comment]
@graemerocher the next release is going to be 5.0. There will not be any additional 4.x.

**Comment by graemerocher** [comment]
That is unfortunate then. Looks like 4.x users will have to live with warnings.

**Comment by oehme** [comment]
> Looks like 4.x users will have to live with warnings.

They don't have to, simply do this:

```
idea.module.scopes.PROVIDED.plus += configurations.annotationProcessor
```

**Comment by graemerocher** [comment]
That requires applying the `idea` plugin, which is not necessarily desirable

**Comment by oehme** [comment]
What do you mean by not desirable? It doesn't do any harm and solves the problem.

**Comment by graemerocher** [comment]
It is yet another plugin to configure and manage and adds IDE specifics to build templates. When you are trying to create something generic for users to consume that may or may not be using IDEA it is not desirable to apply a plugin that it is not going to be used.

I get that a workaround exists, it just isn't a great workaround IMO.

**Comment by graemerocher** [comment]
So doing:

```
idea.module.scopes.PROVIDED.plus += configurations.annotationProcessor
```

In Gradle 4.10.2 result ins 

```
Caused by: java.lang.ClassCastException: java.io.File cannot be cast to org.gradle.api.artifacts.Configuration
        at org.gradle.plugins.ide.internal.resolver.IdeDependencySet$IdeDependencyResult.resolvePlusConfigurations(IdeDependencySet.java:96)
        at org.gradle.plugins.ide.internal.resolver.IdeDependencySet$IdeDependencyResult.visit(IdeDependencySet.java:88)
   
```

So it seems the workaround is not really a viable workaround.

**Comment by oehme** [comment]
It's `idea.module.scopes.PROVIDED.plus += [configurations.annotationProcessor]`
