### ISSUE TITLE
Report information about task dependencies in scan plugin

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6230]
The `--scan` option currently only has information about cache invalidation to explain why a task was run. I'd want to know which task dependencies caused it to run. This is useful to know why a task that shouldn't be running was executed.

See https://github.com/gradle/gradle/issues/6211#issuecomment-410935258 for context.

**Comment by ldaley** [comment]
Hi @SUPERCILEX,

This is something we are working on. I cannot give an ETA at this time.

**Comment by SUPERCILEX** [comment]
Awesome!
