### ISSUE TITLE
Share build cache with you guys?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6253]
Just want to make sure I'm not missing out on perf improvements: can 3P contributors access your build cache for this repo?

**Comment by oehme** [comment]
They can't, it's a password-protected instance. We don't want everyone to use it as a free cache for all their own projects :)

**Comment by wolfs** [comment]
To put @oehme's comment a little bit differently: Currently we don't enable anonymous read access on our cache instance, given that we also use it for private projects, too. We may use a separate cache node for the `gradle/gradle` project alone and maybe allow anonymous read access to it in the future.

So currently, 3P contributors cannot access our build cache.

**Comment by SUPERCILEX** [comment]
Alright, thanks for the info and glad to know you're aware of it.
