### ISSUE TITLE
Issue with Minecraft Forge

### ISSUE THREAD

**Issue by Blu3FireEdeN** [gradle/gradle#6255]
Hello, i have a problem with the Minecraft Forge installation.

Here's my error :
https://scans.gradle.com/s/dxaajaft54bus/

JavaSE Version : 10.1
Gradle Version : 4.9
Minecraft Forge Version : 14.23.4.2746

Followed tutorial : http://mcforge.readthedocs.io/en/latest/gettingstarted/

Thanks.

**Comment by big-guy** [comment]
Hi @Blu3FireEdeN 

This might be better raised at https://github.com/MinecraftForge/ForgeGradle/issues I think that's the repository for the plugin causing the problem (`net.minecraftforge.gradle.forge`).

I think their plugin is looking for `java.ext.dirs` to be set to something and it blows up with a NPE when that system property isn't set:
https://github.com/MinecraftForge/ForgeGradle/blob/FG_2.3/src/main/java/net/minecraftforge/gradle/user/TaskRecompileMc.java#L105

You could try working around this by passing `-Djava.ext.dirs=""`, but you should let the plugin authors know.

HTH

**Comment by Blu3FireEdeN** [comment]
Thank you so much !
