### ISSUE TITLE
BuildProfile not initialised as expected

### ISSUE THREAD

**Issue by tomdcc** [gradle/gradle#6259]
On the [latest nightly](https://builds.gradle.org/viewLog.html?buildId=14884476&tab=buildResultsDiv&buildTypeId=bt39),  the `BuildProfile` on the [`ProfileEventAdapter`](https://github.com/gradle/gradle/blob/3976bed8c9e1a2db19cf911531ba892cc2c498f4/subprojects/core/src/main/java/org/gradle/profile/ProfileEventAdapter.java#L48) is null. This profile was used by Build Scan plugins up to 1.12.x, and having it not initialised results in missing critical information from scans produced by those plugin versions.

A similar change was made in Gradle 2.9 to only populate that object when `--profile` was passed. I'm not sure if a similar change has been made again or if there's some other change that has caused this to occur.

Current nightlies are labelled 4.11-x. If the next version is going to be 4.11 rather than 5.0, we should revert this change and wait for 5.0 to make it.

Regardless, when it's broken in 5.0, we should also update [`BuildScanPluginCompatibility`](https://github.com/gradle/gradle/blob/62f0788e95f0621b75edc124cecb0f863007b426/subprojects/core/src/main/java/org/gradle/internal/scan/config/BuildScanPluginCompatibility.java#L23) to require plugin version 1.13 or later.

### Expected Behavior
`ProfileEventAdapter.buildProfile` is populated for all builds.

### Current Behavior
Field is null.

### Context
Breaks build scan plugins < 1.13

### Steps to Reproduce (for bugs)
Run any build with current Gradle nightly and an older scan plugin version, view scan (will cause an internal server error in scan server).

**Comment by lptr** [comment]
Yeah, this is on me, and it's indeed the same we did apparently for 2.9. I wish we had some more comments on 6221a81fde7b1c54c12e5ef314291d2d448b1794... :/

**Comment by lptr** [comment]
OK, so IIUC, we can deprecate the old versions of the scan plugin that expect this thing to be always present. I think we should do this, since `4.11` = `5.0`. Who should do that? Can the CS team take this on?

**Comment by tomdcc** [comment]
We (the GE team) need to make a decision about which plugin versions to require for 5.0, but that decision won't be made for a couple of weeks when we've hit an internal milestone. We'll pick it up then.

**Comment by tomdcc** [comment]
In the meantime I've raised https://github.com/gradle/gradle/pull/6477 to update the minimum version requirement, but the general question of compatibility for 5.0 remains for now.

**Comment by lptr** [comment]
I've reassinged this to @tomdcc.

**Comment by lptr** [comment]
@tomdcc I'm assuming this can be closed. Can you please re-open if that's not correct?

**Comment by tomdcc** [comment]
With 5.x only supporting plugin 2.0+ we're good.
