### ISSUE TITLE
Console logging causes print dialog to appear

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#6261]
Yeah, it sounds weird. I think what happens is that we have some concurrency issue writing to the console that results in some mixed up special characters being processed by the terminal that end up being interpreted as <kbd>Cmd+P</kbd>.

![image](https://user-images.githubusercontent.com/495366/43886911-774d0372-9bbd-11e8-93fa-3f9f75686a2e.png)

Notice that the font has changed from bold to non-bold around the middle of the screen, too—probably another garbled special character.

**Comment by big-guy** [comment]
@lptr has this happened lately to you?  we've touched some of the console code lately, so I wonder if this has been magically fixed.

**Comment by lptr** [comment]
I was not experimenting with anything in this area. Let's close it and reopen if it happens to someone again.
