### ISSUE TITLE
Remove the ability to add non-directory-based file trees as declared outputs

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6267]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java#L422

**Comment by wolfs** [comment]
That is not deprecated anymore. We now do it differently and can continue to support that strange use case. // cc @pledbrook.

**Comment by lptr** [comment]
Do we need to say something about the un-deprecation, or is the use case sufficiently obscure that it’s not needed?

**Comment by wolfs** [comment]
I would say the use case is sufficiently obscure that saying something would confuse users even more.
