### ISSUE TITLE
Remove BroadcastingCollectionEventRegister#getAddAction

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6268]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/core/src/main/java/org/gradle/api/internal/collections/BroadcastingCollectionEventRegister.java#L60

**Comment by adammurdoch** [comment]
Done in https://github.com/gradle/gradle/pull/6493
