### ISSUE TITLE
Remove UnionFileCollection/UnionFileTree#add

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6273]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/core/src/main/java/org/gradle/api/internal/file/UnionFileCollection.java#L48

https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/core/src/main/java/org/gradle/api/internal/file/UnionFileTree.java#L58

**Comment by wolfs** [comment]
Fixed by https://github.com/gradle/gradle/pull/6365.
