### ISSUE TITLE
Forbid removing a task when a Provider for that task is also in the dependencies

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6278]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskDependency.java#L245

**Comment by lacasseio** [comment]
Because we are [widening the deprecation warning](https://github.com/gradle/gradle-native/issues/790) in the next version of Gradle and the next version is 5.0, we changed the scheduled for removal to 6.0. I will close this issue and we can revisit this during Gradle 6.0 release.
