### ISSUE TITLE
Feature request: Provide managed dependencies for referencing projects

### ISSUE THREAD

**Issue by NHendricks** [gradle/gradle#6284]
In issue https://github.com/gradle/gradle/issues/4979 there was already a longer discussion about the feature preview improved_pom_support and differences between maven and gradle.
Without mavens nearest first and exclude concept i dont see a gradle way to provide managed dependencies (versions and excludes) to referencing projects. 
Instead of solving this ourselves like in https://github.com/melix/bubble-bom (here are no excludes covered, imho it only works for versions) i would highly appreciate an official gradle way solve this.

**Comment by melix** [comment]
[Enforced platforms](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import) should do what you need.
