### ISSUE TITLE
Remove support for nested build without a settings file

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6287]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/core/src/main/java/org/gradle/initialization/DefaultSettingsLoader.java#L89

**Comment by bigdaz** [comment]
I can take a look at this, but it's not really anything to do with composite builds or what we normally refer to as 'nested' builds. We already prohibit adding included builds without a settings file.

See https://github.com/gradle/gradle/issues/3137

**Comment by oehme** [comment]
Sorry, after 50 or so deprecations I guess my brain was fried :) Reassigning.
