### ISSUE TITLE
Forbid creating convention objects

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6289]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/diagnostics/src/main/java/org/gradle/api/plugins/ProjectReportsPluginConvention.java#L41

https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/ear/src/main/java/org/gradle/plugins/ear/EarPluginConvention.java#L63

https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/plugins/src/main/java/org/gradle/api/plugins/ApplicationPluginConvention.java#L45

https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePluginConvention.java#L50

https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPluginConvention.java#L64

https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/plugins/src/main/java/org/gradle/api/plugins/WarPluginConvention.java#L38

https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/osgi/src/main/java/org/gradle/api/plugins/osgi/OsgiPluginConvention.java#L47

**Comment by pledbrook** [comment]
This is already mentioned in the [Gradle 4.10 release notes](https://docs.gradle.org/current/release-notes.html#deprecations) as something you can't do.

**Comment by oehme** [comment]
It's mentioned as a deprecation, this issue is about removing it entirely.

**Comment by adammurdoch** [comment]
Done via https://github.com/gradle/gradle/pull/6708
