### ISSUE TITLE
Remove deprecated JavaLibrary constructor

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6291]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/plugins/src/main/java/org/gradle/api/internal/java/JavaLibrary.java#L90

**Comment by jameskleeh** [comment]
@bigdaz Is there any documentation anywhere on how to migrate to the new constructor?

**Comment by bigdaz** [comment]
@jameskleeh No, this is an internal type and is not intended for direct instantiation. Please vote for #1842 to push for a supported way to construct a `SoftwareComponent`.
