### ISSUE TITLE
Forbid using --source-path in raw compiler args

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6294]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java#L231

Or consider automatically remapping such arguments to the correct input property.

**Comment by pledbrook** [comment]
Whoever implements this, please verify the Gradle upgrade chapter of the user manual. I'm writing it on the assumption that this approach will be forbidden, but if the alternative approach is taken, the chapter will need updating.
