### ISSUE TITLE
Forbid specifying -processorpath in the raw compiler args

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6295]
https://github.com/gradle/gradle/blob/54e42e81171fd5e4b738b0401829cd839dae74f9/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/processing/AnnotationProcessorPathFactory.java#L118

Or redirect such calls to the correct property automatically.

**Comment by pledbrook** [comment]
As with `-source-path`, please ensure that the Gradle upgrade chapter of the user manual matches the approach taken to resolve this issue.

**Comment by marcphilipp** [comment]
@oehme Which option would you prefer?

**Comment by marcphilipp** [comment]
@bigdaz There's another task to remove support for detecting annotation processors on the classpath with an open PR that will likely conflict with this one: see https://github.com/gradle/gradle/pull/6921#discussion_r220994292.

**Comment by oehme** [comment]
I think we should go for the "forbid" path. The other way would be a major refactoring and I don't really see the use case.

**Comment by bigdaz** [comment]
@marcphilipp Yep, I saw that other PR which is why I unassigned myself from this issue. I'll leave it to you.
Note that PR #6931 adds a validation step that prohibits `-sourcepath` in the compiler args. It would be trivial to add `-processorpath` to the validation, which means most of the work for this issue will be  about cleaning up the infrastructure that dealt with it being present.

**Comment by marcphilipp** [comment]
@oehme Should we also prohibit using `-proc:none|only` and `-processor` or simply pass them along to the compiler?

**Comment by oehme** [comment]
No, those are orthogonal to the processor path and should remain. We have no replacement for them.

**Comment by marcphilipp** [comment]
One more thing: `CompileOptions.setAnnotationProcessorPath(null)` is documented to use the compile classpath instead. Do we remove that, too?

**Comment by marcphilipp** [comment]
I changed the Javadoc in 0285f2120e9 as part of #6921.

**Comment by oehme** [comment]
Yes we do. We always use the processorPath now.
