### ISSUE TITLE
Review Upgrade from Gradle 4.x chapter for dependency management topics

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#6307]
Coming with Gradle 5.x there will be a dedicated chapter to 4.x upgrade.
We must review it before the release to make sure all changes are properly captured, including further changes added between now and 5.0.

**Comment by pledbrook** [comment]
See #6165 for the working pull request.

**Comment by bigdaz** [comment]
Done: https://github.com/gradle/gradle/pull/7677
