### ISSUE TITLE
Update behavior of IdeaModel#sourceDirs

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6312]
To fix https://github.com/gradle/gradle/blob/ae0af9283f6e0627e65ed192a2abdbc52067c922/subprojects/ide/src/crossVersionTest/groovy/org/gradle/plugins/ide/tooling/r50/ToolingApiIdeaModelCrossVersionSpec.groovy#L36

**Comment by oehme** [comment]
Make sure to check back with @vladsoroka to make sure that IDEA handles the new methods already.

**Comment by donat** [comment]
I've contacted him. I'll close this issue when I get his confirmation.

**Comment by donat** [comment]
I've notified @nskvortsov and he is looking into the change; closing the issue.
