### ISSUE TITLE
project.afterEvaluate can't be called from plugin.apply

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6319]
In [this plugin](https://github.com/Triple-T/gradle-play-publisher/blob/97397c683876f2ae895dbe8c754ea4a5f8387b86/plugin/src/main/kotlin/com/github/triplet/gradle/play/PlayPublisherPlugin.kt#L195) for example, it crashes. I don't see why that should be disallowed. The 4.10 release notes only mention calling `afterEvaluate` from `tasks.register`.

Project: https://github.com/SUPERCILEX/Robot-Scouter/tree/3986943126d1e8f661b6e3c2f986dc02e7848c9c
Setup: `./gradlew setup`

Test: `./gradlew wrapper --gradle-version 4.10-rc-1 -PdevBuild -s`. (You'll have to comment out `configureGeneral()` in my main build script.)

**Comment by big-guy** [comment]
Thanks @SUPERCILEX, this should still work.  We'll get a fix and another RC going.

There are a few things I found while tracking this down:

### `getTasksByName`
Every call to `project.getTasksByName("task name", true)` defeats configure-on-demand and causes all projects to be fully evaluated. 

You could replace
https://github.com/SUPERCILEX/Robot-Scouter/blob/master/buildSrc/src/main/kotlin/com/supercilex/robotscouter/build/RobotScouterBuildPlugin.kt#L44

with either searching through the task graph for tasks with the name `processReleaseMetadata` and disabling them or configuring the tasks with `onlyIf` (something like this):
```
tasks.withType(type of processReleaseMetadata).named("processReleaseMetadata").configure {
    onlyIf { 
        project.secrets.single({ it.name.contains("publish") }).exists()
    }
}
```

### `whenTaskAdded`
[`tasks.whenTaskAdded {}`](https://github.com/SUPERCILEX/Robot-Scouter/blob/master/build.gradle.kts#L82-L84) causes all tasks to be created even if they're declared with `register(...)`.

**Comment by SUPERCILEX** [comment]
@big-guy Thanks for all the tips! Shouldn't that be documented somewhere? 😄

#### `getTasksByName`

Is there an easy way to recursively access `named` across all projects? And is there an optional version of `named` that doesn't throw? Here's what I came up with, pretty sure it isn't forcing on-demand tasks to be created:
```kt
project.gradle.taskGraph.whenReady {
    val hasCreds by lazy { project.secrets.single { it.name.contains("publish") }.exists() }
    allTasks.filter { it.name == "processReleaseMetadata" }.forEach {
        if (!hasCreds) it.enabled = false
    }
}
```

#### `whenTaskAdded`

Is there an alternative? I mean, I could do the `taskGraph` trick again, but that's kinda ugly. Personally, I think Gradle 5.0 should change the method signature to accept an `Action<TaskProvider<T>>` so it can be used efficiently.

**Comment by SUPERCILEX** [comment]
**_WHAT!!!???_** OMG, you just saved me 10 ENTIRE SECONDS off of every build. Like, that'll be enough for me to have sub-minute incremental builds, thank you so much!!! ❤️ (And I kept complaining to everyone about how long configuration took 🤦‍♂️.)

### Old 💩

![image](https://user-images.githubusercontent.com/9490724/43930957-f776a05c-9bf0-11e8-9d6c-073fcfe97803.png)

### New ✨

![image](https://user-images.githubusercontent.com/9490724/43930978-084f9726-9bf1-11e8-8660-54ab270e8ed2.png)

**Comment by SUPERCILEX** [comment]
Regarding `whenTaskAdded`, here's how I replaced it:
```kt
gradle.taskGraph.whenReady {
    allTasks.filter { name.contains("Test") }.forEach { it.enabled = false }
}
```

**Comment by oehme** [comment]
2s is still slow, unless you have hundreds of subprojects. You can use the Gradle profiler to find out what code exactly is slowing your build down. If making those tasks lazy made 10s difference it also means you have some very expensive code in those configure closures.

**Comment by SUPERCILEX** [comment]
@oehme Nah, Google's just being naughty. I've complained about it here: https://issuetracker.google.com/issues/112219401 and I'll keep trying to get them to reduce configuration time as we make progress.

Data: this [build scan](https://scans.gradle.com/s/jocwdv2vw7vdy/performance/configuration?openScriptsAndPlugins=WzBd#afterEvaluate) shows that creating the `com.android.application` plugin tasks is hella expensive.

**Comment by oehme** [comment]
That's not really what the build scan shows. It just shows that the `afterEvaluate` hook is slow. That hook contains everything related to variants, including any 3rd party plugins and code in your own build related to variants. Given you only have 500 tasks in total, this should not take 2s. Have a look with the profiler and you'll see where the time is going.

**Comment by ldaley** [comment]
> Eventually build scans will be more fine grained about this and pinpoint which plugin is contributing exactly. 

FYI, this is coming very soon. ~2 weeks away.

**Comment by oehme** [comment]
@ldaley Even for `DomainObjectContainer.all {}`? Because that's where the missing clarity for Android builds is - plugins doing expensive things as the Android plugin adds the variants.

**Comment by ldaley** [comment]
No, not to that level. The next release just has attribution of the lifecycle callbacks. 

With a closer look, I guess that's not actually going to reveal anything in this case because it's almost certainly the android plugin incurring the time.

**Comment by oehme** [comment]
I don't think it's the Android plugin per se, but callbacks like `variants.all {}`.

**Comment by ldaley** [comment]
Right, but that's going to show with the attribution as just Android plugin time.

**Comment by big-guy** [comment]
This is fixed and will be included in 4.10-rc-2.

**Comment by SUPERCILEX** [comment]
@oehme @ldaley Oh, it's the Jetifier transforms. Should they be doing this at configuration time or should I report a bug?
![image](https://user-images.githubusercontent.com/9490724/43976570-eae0758e-9c95-11e8-99d3-a9778ae47f8e.png)

**Comment by oehme** [comment]
Please use the jfr profiler so we see the actual stacktrace. Resolving dependencies at configuration time is always a bug. We just need to find out who does it.

**Comment by SUPERCILEX** [comment]
@oehme I'm not sure how to figure who's starting the transforms, but I've filed #6348
