### ISSUE TITLE
My server doesn't start up to 1000 s ec

### ISSUE THREAD

**Issue by Purushottam10** [gradle/gradle#6320]
### Your Environment

 * Build scan URL:

**Comment by big-guy** [comment]
Hi @Purushottam10 

I'm not sure what you mean.  Could you provide some more information and reopen this issue?

Thanks!

**Comment by Purushottam10** [comment]
package webamber;
public class Services {
private int id ;
private String serviceName ;
private double cost;
private String about;
/**
* @return the id
*/
public int getId() {
return id;
}
/**
* @param id the id to set
*/
public void setId(int id) {
this.id = id;
}
/**
* @return the serviceName
*/
public String getServiceName() {
return serviceName;
}
/**
* @param serviceName the serviceName to set
*/
public void setServiceName(String serviceName) {
this.serviceName = serviceName;
}
/**
* @return the cost
*/
public double getCost() {
return cost;
}
/**
* @param cost the cost to set
*/
public void setCost(double cost) {
this.cost = cost;
}
/**
* @return the about
*/
public String getAbout() {
return about;
}
/**
* @param about the about to set
*/
public void setAbout(String about) {
this.about = about;
}
public static void main(String[] args) {
}


}
this is jsp code

**Comment by marcphilipp** [comment]
@Purushottam10 This does not look like it's even using Gradle at all or am I missing something?
