### ISSUE TITLE
Reduce configuration time overhead of finding Java installations in our build

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#6322]
This is costing .3s every build: https://e.grdev.net/s/fyeu2prbbgcou/performance/configuration?openScriptsAndPlugins=WzBd#gradlebuild.available-java-installations

A quick fix might be to cache the result. Another way might be to have a task to generate a data file in GRADLE_USER_HOME which users can run once (or when things change), and use that if present.

**Comment by oehme** [comment]
I don't think we need the (expensive) `JavaInstallationProbe` here, as we're not interested in detailed information like the vendor etc. There is a cheaper alternative with `JvmVersionDetector`.

**Comment by wolfs** [comment]
We need the vendor for validation. We could move the validation to somewhere later in the build, tough. Can we execute the validation in parallel during configuration phase maybe?

**Comment by oehme** [comment]
Why during the configuration phase at all? I always encourage plugin authors to have validation tasks and hook them in where needed. For our case that would be as a dependency of `compileJava` I guess.

**Comment by wolfs** [comment]
That sounds good, too.

**Comment by wolfs** [comment]
I just saw that the vendor is also an input to the compilation tasks...

**Comment by wolfs** [comment]
PR for fixing the configuration time cost: https://github.com/gradle/gradle/pull/6335
After: https://e.grdev.net/s/2pllg3ipx3f2i/performance/configuration

**Comment by wolfs** [comment]
Fixed by https://github.com/gradle/gradle/pull/6335.
