### ISSUE TITLE
Interaction between environment variables and gradle daemon changed with java 9

### ISSUE THREAD

**Issue by ksaua** [gradle/gradle#6330]
Create the following build.gradle
```
System.getenv().each { key, value ->
    println key + "=" + value
}
```

Run the following - ensuring you use Java 8 jre:
```
export ENV_TEST=initial; ./gradlew tasks | grep ENV_TEST
export ENV_TEST=changed; ./gradlew tasks | grep ENV_TEST
```

This will output
```
ENV_TEST=initial
ENV_TEST=changed
```

When running the same with java 9 it will output:
```
ENV_TEST=initial
ENV_TEST=initial
```

### Expected Behavior
Environment variables are inherited from the gradlew.bat/shell file, and not the gradle daemon's environment variables. For Java 8 the environment variables are fetched from the gradlew.bat environment, while if running in Java 9 the environment variables are fetched from the gradle daemon.

### Context
We use environment variables when running gradle in Jenkins, to get better performance we use the daemon. To fix this we will have to use the --no-daemon flag.

### Steps to Reproduce (for bugs)
As above ^

**Comment by marcphilipp** [comment]
This has been fixed in https://github.com/gradle/gradle/pull/6170 for Gradle 4.10.
