### ISSUE TITLE
buildSrc is recompiled when changing top level build.gradle.kts from Intellij

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#6332]
I have the `gradle/gradle` project imported into Intellij and am editing the root `build.gradle.kts` file, e.g. adding a `println` statement here: https://github.com/gradle/gradle/blob/85efa7e2863fd5edf3e2272c8879000de4da6361/build.gradle.kts#L303-L306

When running `./gradlew help` from the command line, stale output cleanup kicks in and deletes all the output in `buildSrc`: https://e.grdev.net/s/e76jh7hvk3dks/timeline?task=suyolbmpu62oy

Running `./gradlew help` again yields everything up-to-date as expected: https://e.grdev.net/s/pilnvh56b53io/timeline

Editing `build.gradle.kts` from the command line doesn't cause anything being re-built/stale output cleanup: https://e.grdev.net/s/7a45onymq7eze/timeline

When I focus on Intellij after having changed the file from the command line, stale output cleanup kicks in again and everything is rebuilt: https://e.grdev.net/s/lfjiaouo3bcx6/timeline

**Comment by oehme** [comment]
Maybe the Kotlin DSL running a task (to generate the project schema) with a different JVM. Do you have org.gradle.javahome set in your user home? If not it may differ between IntelliJ and command line.

Do you get the same effect when running a task from idea and then from the command line again?

**Comment by wolfs** [comment]
My guess would be that something causes `buildSrc/.gradle/buildOutputCleanup/` or `.gradle/buildOutputCleanup/` to be invalidated.

Looking at the debug log, that indeed seems to be the issue:
```
 18:30:33.949 [DEBUG] [org.gradle.cache.internal.DefaultPersistentDirectoryCache] Invalidating Build Output Cleanup Cache (/Users/wolfs/projects/gradle/build-tool-release/buildSrc/.gradle/buildOutputCleanup) as cache property gradle.version has changed from 4.11-20180810065304+0000 to 4.10-rc-1.
```

Looks like I was using a local Gradle distribution from Intellij instead of the wrapper...

Selecting `Use default gradle wrapper` fixes the problem.
