### ISSUE TITLE
4.10 rc1 still outputs quite a bit of transform logs

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6334]
They should all all be suppressed at the standard log level and only show up for `info` or maybe even `debug`.

Sample project: https://github.com/SUPERCILEX/Robot-Scouter/tree/3b3f70665f919d50eba749ca2b2f114b1ed47342

Running: `./gradlew setup assembleDebug -PdevBuild --console plain`

See https://github.com/gradle/gradle/issues/6092#issuecomment-412152716 for context.

**Comment by oehme** [comment]
I think what's tripping users up here is that we are treating transforms like tasks now. However, in a small-medium Android project there are many more transforms than tasks. Also transforms are usually even less meaningful to the end user than most tasks are. As a result this logging is perceived as "clutter".

**Comment by eygraber** [comment]
Seeing this in the 4.10 release as well.

**Comment by technoir42** [comment]
Any updates? Since 4.9 it has become harder to find useful information in logs. Something like an option to change log level for transform logs would be great.

**Comment by wolfs** [comment]
The current plan is to remove the individual console logging from the plain console and only show the progress information with the rich console. This probably won't make it into 5.0.

**Comment by wolfs** [comment]
We don't log artifact transforms any more in 5.1. You can try out a recent nightly to see the effect.

**Comment by xbournerx** [comment]
@wolfs why was this closed? It is still not fixed.
I just tried out 5.1.1 and there are still a lot of Transform Logs. :(

**Comment by wolfs** [comment]
@xbournerx What console are you using? Can you maybe point me to an example what the logs look like?

The behaviour in 5.1 should be that an artifact transform does not show up in the console log if it doesn't log anything.

**Comment by SUPERCILEX** [comment]
It works for me. Though the transforms do show up in Gradle scan, not sure if that's intentional

**Comment by wolfs** [comment]
It is intentional for the transforms showing up in the build scan, so there is at least some trace in there. As soon as transforms are captured in the timeline, they should not show up in the console log in build scans any more.

**Comment by SUPERCILEX** [comment]
Cool 👍

**Comment by doniwinata0309** [comment]
Gradle 5x and 6x generating transforming logs in the console log in build scans, is this expected  ?
Sample project:
https://scans.gradle.com/s/ioy3beo7tkbla/console-log#L2
