### ISSUE TITLE
Simplify specifying single file has been built by some task

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6336]
Related to #2947

`ConfigurableFileCollection` exposes methods for conveying that a file collection is built by some task, but no parallel exists for conveying that a single file is built by some task.

The `RegularFile` is great for passing around task output information lazily, but it would be really awesome if the `RegularFile` (or some inheriting type) could also convey what tasks need to be executed to build it. (For example, by implementing `org.gradle.api.BuildableComponentSpec`).

This would simplify writing plugins extensions by not requiring a user to specify both the `RegularFile` and the task that built it.

Currently, the Gradle API provides no mechanism for constructing a `BuildableComponentSpec` implementation meaning you end up having to implement the `BuildableComponentSpec` sub-interface of methods you want, manually.

An example of a usecase:
```kotlin
val generateSwaggerSchema =
    tasks.register("generateSwaggerSchema", GenerateSwaggerSchema::class.java) {
        // ...
    }

artifactory {
    servers { // `this` is of type `NamedDomainObjectContainer`
        "companyArtifactory" {
            url = "https://company.artifactory.com"
            credentials {
                username = "user"
                password = "password"
            }

            upload { // `this` is of type `NamedDomainObjectContainer<UploadDescriptor>`
                all {
                    repository = "api-docs-local"
                    destinationDirectory = "project/$version"
                }
                "openapi" {
                    file.set(schemaDirectoryOut.map { it.file("openapi.json") })
                    builtBy(generateSwaggerSchema)
                }
                "swagger" {
                    file.set(schemaDirectoryOut.map { it.file("swagger.json") })
                    builtBy(generateSwaggerSchema)
                }
            }
        }
    }
}
```

For reference, this is what `UploadDescriptor` looks like:
```kotlin
data class UploadDescriptor(
    val name: String,
    /**
     * The Artifactory repository the file should be uploaded to.
     */
    var repository: String? = null,
    /**
     * The destination on the Artifactory server that this file should be uploaded to.
     */
    var destinationDirectory: String? = null,
    /**
     * The file to be uploaded to the [destinationDirectory].
     */
    val file: RegularFileProperty,
    /**
     * Specifies that this [file] has been built by a set of tasks.
     * @see Task.dependsOn
     */
    var builtBy: Iterable<Any> = emptyList()
) {
    /**
     * Specifies that this [file] has been built by a set of tasks
     * @see Task.dependsOn
     */
    fun builtBy(vararg tasks: Any) {
        builtBy += listOf(*tasks)
    }
}
```

Another option is to expose an implementation of `BuildableComponentSpec` that plugin developers can actually use in their code.
Currently `BuildableComponentSpec` is too complex to reasonably implement, plus `ComponentSpec` is annotated as `@HasInternalProtocol`.

**Comment by oehme** [comment]
See [RegularFileProperty](https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:working_with_task_dependencies_in_lazy_properties).

**Comment by JLLeitschuh** [comment]
@oehme How do I configure what task a `RegularFileProperty`'s origin? There doesn't seem to be an API for specifying `builtBy`?

**Comment by oehme** [comment]
The task that created the property object, as shown in the docs.

**Comment by JLLeitschuh** [comment]
`RegularFileProperty` doesn't mention anywhere about being associated with the task that created it.
Nor does `DirectoryProperty`. At least, not in the sources currently on `master`.

You can't get access to that object created by the `DefaultTask::newOutputDirectory` call without forcing the configuration of the task though.

Take for example, this API:
```kotlin
@CacheableTask
open class GenerateSwaggerSchema : JavaExec() {
    @Suppress("LeakingThis")
    @get:OutputDirectory
    val schemaDirectory: DirectoryProperty = newOutputDirectory()
}

val schemaDirectoryOut = layout.buildDirectory.dir("schema" )

val generateSwaggerSchema =
    tasks.register("generateSwaggerSchema", GenerateSwaggerSchema::class.java) {
        // Other configuration removed for brevity....
        // Does link the `schemaDirectoryOut` variable as having been created by this task?
        schemaDirectory.set(schemaDirectoryOut)
    }

artifactory {
    servers {
        "plexxiArtifactory" {
            upload {
                "openapi" {
                    // Does this linking carry over?
                    file.set(schemaDirectoryOut.map { it.file("openapi.json") })
                }
            }
        }
    }
}
```

There's no way to adapt this example to also not force the configuration of the `GenerateSwaggerSchema` task and also ties the output of one task to another without an explicit `dependsOn`.

For example:
```kotlin
val generateSwaggerSchema =
    tasks.register("generateSwaggerSchema", GenerateSwaggerSchema::class.java) {
        // Other configuration removed for brevity....
        // Does link the `schemaDirectoryOut` variable as having been created by this task?
        schemaDirectory.set(layout.buildDirectory.dir("schema" ))
    }

artifactory {
    servers {
        "plexxiArtifactory" {
            upload {
                "openapi" {
                    file.set(
                        generateSwaggerSchema
                            .map { it.schemaDirectory }
                            .map { it.file("openapi.json") }
                            .get() // This collapses the configuration for `generateSwaggerSchema` 😢
                    )
                   // This also doesn't work to tie the `schemaDirectory` which was created using
                   // `newOutputDirectory` as an input to the other task.
                }
            }
        }
    }
}
```
 
The above example has two problems:
1. Setting the output of the `GenerateSwaggerSchema::schemaDirectory` causes the deferred configuration of the `GenerateSwaggerSchema` task to be resolved. Thus totally negating the benefits of using the `register` API.
2. Calling `file` on a `BuildableDirectoryVar` and assigning it as the input to another task doesn't seem to link them together as dependencies of one another.


### Simpler Example

This is more easily represented with this simple test:
```kotlin
@CacheableTask
open class GenerateSwaggerSchema : JavaExec() {
    @Suppress("LeakingThis")
    @get:OutputDirectory
    val schemaDirectory: DirectoryProperty = newOutputDirectory()
}

val generateSwaggerSchema =
    tasks.register("generateSwaggerSchema", GenerateSwaggerSchema::class.java) {
        schemaDirectory.set(layout.buildDirectory.dir("schema"))
    }

open class OutputTest : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @Suppress("LeakingThis")
    val outputFile = newInputFile()
}

val someDefault =
    tasks.register("someTask", OutputTest::class.java) {
        outputFile.set(
            generateSwaggerSchema
                .map { it.schemaDirectory }
                .map { it.file("openapi.json") }
                .get()
        )
    }
```

```
./gradlew :someTask --dry-run

Parallel execution is an incubating feature.
:someTask SKIPPED
```

Notice that `generateSwaggerSchema` wasn't listed in the task execution list.

**Comment by JLLeitschuh** [comment]
`it.file("openapi.json")` returns `Provider<RegularFile>`, `map` returns `Provider<T>`.
So `map { it.file("openapi.json") }` returns `Provider<Provider<RegularFile>>`.

What I really need on `Provider` is a `flatMap` method but none currently exists.

**Comment by JLLeitschuh** [comment]
@oehme Regardless of the outcome of #6361 and #6363 I still think that there should be a way to tie a `DirectoryProperty` or a `RegularFileProperty` to the task that built it.

**Comment by JLLeitschuh** [comment]
@oehme What about needing to retrofit existing tasks that don't expose any sort of `RegularFileProperty` for example, the `Jar` task (which extends `AbstractArchiveTask`) doesn't provide a mechanism to create a `RegularFileProperty` that is tied to the `Jar` task.
If I want the output of the `Jar` task, to be used as the input to a task that takes a `RegularFileProperty` how do I create this relationship?

**Comment by oehme** [comment]
You can get the `TaskProvider` for the Jar task and use `map` to map it to its output dir. This will preserve the dependency on the Jar task.

**Comment by JLLeitschuh** [comment]
That's quite a roundabout mechanism, is this only supported in Gradle 5.0 or in 4.10.2 as well?

**Comment by oehme** [comment]
That'll be 5.0 I believe.
