### ISSUE TITLE
Webapp dependencies' jars are not deployed to an Eclipse managed Tomcat instance

### ISSUE THREAD

**Issue by niqueco** [gradle/gradle#6341]
I'm working in a web application in Eclipse using the wtp-eclipse plugin (from buildship). Everything is fine except that when the project is deployed to the Eclipse managed Tomcat instance the jars from the project dependencies are not copied.

### Expected Behavior
When executing the webapp inside Eclipse all the jars needed for it (as per build.gradle "implementation" sentences) should be copied to the libs folder in the deployed instance.

### Current Behavior
Only things already in WEB-INF/libs are there. The project fails with "class not found" exceptions.

### Your Environment
Using Gradle 4.9 and Eclipse 4.8

**Comment by niqueco** [comment]
I guess this is reported here: https://github.com/eclipse/buildship/issues/496

The workaround there worked fine.

I don't know whose fault this is (buildship or the gradle plugin) though.

**Comment by marcphilipp** [comment]
@donat Can we close this issue?

**Comment by oehme** [comment]
We can't, this is a Gradle issue, not a Buildship one - We need to switch `eclipse-wtp` from `runtime` to `runtimeClasspath`. This got lost during the introduction of these new configurations.

**Comment by big-guy** [comment]
@oehme just this? https://github.com/gradle/gradle/commit/852dcb0a8d0e856ee2b2e70621a4c95c23bb11bb

**Comment by oehme** [comment]
Yep, thanks for that :)

**Comment by ams-tschoening** [comment]
#496 contained multiple issue, external dependencies AND [included builds](https://github.com/eclipse/buildship/issues/496#issuecomment-408840748):

> (but projects included with includeBuild are still ignored)

Which of both problems is addressed by this issues? Because I'm using Gradle 6.2.1 and dependencies for the included builds are still not published to embedded Tomcat. Should this be reopened or an additional issue created or ...?
