### ISSUE TITLE
Dynamic range should be supported by the plugin block

### ISSUE THREAD

**Issue by mat013** [gradle/gradle#6346]
The issue Snapshot plugin versions are not supported #3902 has been solved, however this only solves the issue with snapshot versions. 

It would be valuable to have the possibility to support version ranges. 

For my case it would be nice if the labels latest.integration and latest.release in particular is supported, as when our modules are being developed they should run with the latest version of the plugin rather than a fixed version. Mainly because our project consists of many projects, and would be nice to avoid to bump the version for every project whenever a bugs or inadequacies have been found in our plugins. 

### Expected Behavior

The dynamic range should work as it does in the case of normal dependency resolution. 

### Current Behavior

Gradle throws an error that dynamic ranges are not supported

### Context

With 100s of modules and all the project relies on some plugin for some common behaviour, and a bug has been resolved in a plugin all projects dependent on the plugin should then have the version bumped. 

In addition for our case projects when releasing the plugin should be fixed to the latest released version of the plugin, and again it would be nice to avoid bumping all the projects manually.

### Steps to Reproduce (for bugs)

plugins {
    id("com.companya.gradle.release").version("latest.integration")
}

### Your Environment

All versions

**Comment by ljacomet** [comment]
Sorry for the late reply

This was fixed in Gradle 7.0:
* #14704
