### ISSUE TITLE
Transforms are run during configuration time

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6348]
This might be Google's fault, I'm not sure. Here's the [profiling](https://github.com/gradle/gradle/files/2281305/profile.zip). See https://github.com/gradle/gradle/issues/6319#issuecomment-412198186 for context.

Project: https://github.com/SUPERCILEX/Robot-Scouter/tree/dadc63f2137e1bdfe9993268e3b031728ddfaa03
Setup: `./gradlew setup`

**Comment by oehme** [comment]
It's the Kotlin plugin, please file an issue for them.

<img width="1088" alt="screen shot 2018-08-12 at 17 46 01" src="https://user-images.githubusercontent.com/1191797/44008358-a56c4082-9e57-11e8-8e50-14548a3ad283.png">
