### ISSUE TITLE
build-dashboard relies on instanceof checks to locate reports due to type hierarchy of Reporting interface

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#6350]
When looking for any tasks that implement `Reporting`, the build-dashboard plugin traverses all projects and all tasks looking for any task that is an `instanceof Reporting`.  This means that we need to realize all possible tasks when a build uses the build-dashboard plugin and executes the buildDashboard task.

The buildDashboard task is _also_ a finalizer for any `Reporting` task, so executing any `Reporting` task with the build-dashboard plugin applied causes a chain reaction:

Reporting task realized -> Reporting task finalized by buildDashboard -> buildDashboard realized -> all tasks in all projects are realized.

### Expected Behavior

It seems like we may have intended `Reporting` to be implemented by things other than a task, but we only use it with tasks.  If `Reporting` extended `Task`, we could search for tasks without realizing all possible tasks.

### Current Behavior

`tasks.withType(Reporting)` is invalid since `Reporting` is unrelated to `Task`.  The workaround is to use `.all` or `.configureEach` and look for any task that is `instanceof Reporting`.

**Comment by JLLeitschuh** [comment]
@big-guy This is very much related to this issue: #4050
