### ISSUE TITLE
Cache cleanup deletes entries currently being created by another process

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#6354]
Recent CI builds (e.g. https://builds.gradle.org/viewLog.html?buildId=14941151&buildTypeId=Gradle_Check_Parallel_Java7_Ibm_Linux_toolingApi) have shown that there's a race condition between cache cleanup and the `transforms` cache (potentially also the `jars` cache). Cache cleanup scans the cache directory for files to deleted and decides whether to delete a file based on information in the file access time journal. When another build currently creates an entry in the cache, e.g. an artifact transform, the entry's directory is created first and files are written into afterwards. The file access time journal is updated when the entry has been written completely. Thus, there's a race condition when the cleanup has already listed files in the directory and decides on whether to delete the new entry which has not yet been written to the file access time journal.

In order to prevent this from happening, we should only delete files for which we can be sure that they have been written to the journal. For files unknown to the journal we currently use the inception time of the journal as a fallback in order to deal with files written by previous Gradle versions. In addition, we should check the file modification timestamp prior to deleting it and only delete those older than a certain amount of hours, e.g. 24 hours to be on the safe side.

**Comment by marcphilipp** [comment]
On second thought, I think 24 hours is too much. That would mean cleanup is executed every 24 hours but only deletes files older than that. 1 hour should be enough.

**Comment by wolfs** [comment]
Fixed via #6356.
