### ISSUE TITLE
How to generate a repo URL from android project on github

### ISSUE THREAD

**Issue by nusktec** [gradle/gradle#6360]
I have a working project forked from a friend of mine, but i want the gradle url to be from my own forked one

**Comment by marcphilipp** [comment]
Sorry, I‘m not sure what you mean. Do you want to host an artifact repository on GitHub pages?

**Comment by nusktec** [comment]
For instance, i have this library forked 'com.facebook.shimmer:shimmer:0.3.0'
i want it to be as 'com.nusktec.shimmer:shimmer:0.3.0'

**Comment by marcphilipp** [comment]
Please refer to the user guide chapter on [publishing artifacts](https://docs.gradle.org/current/userguide/publishing_overview.html).
