### ISSUE TITLE
Jar task fails when osgi plugin enabled with resource files only (no source files)

### ISSUE THREAD

**Issue by benfortuna** [gradle/gradle#6370]
### Expected Behavior

When osgi plugin is enabled the `osgi-classes` output directory should be maintained in the build directory.

### Current Behavior

Since gradle 4.2.1 the clean stale outputs feature will remove the `osgi-classes` directory. 

This causes the Jar task to fail as it cannot copy Manifest.MF from `osgi-classes`

### Context

Unable to build osgi JAR files (appears to be a problem when there are no compiled classes)

Example output (on Windows, result is same on MacOS):

![image](https://user-images.githubusercontent.com/984966/44072120-5a75b6ce-9fd0-11e8-9d1b-dac2b656d10e.png)

build.gradle:

```
apply plugin: 'java'
apply plugin: 'osgi'
```

```
C:\Users\xxxxxx\Development\gradle-osgi-test>.\gradlew jar
> Task :jar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':jar' property 'rootSpec$2$1' during up-to-date check.
> Could not copy MANIFEST.MF to 'C:\Users\xxxxxx\Development\gradle-osgi-test\build\tmp\jar\MANIFEST.MF'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 2 executed
```

### Steps to Reproduce (for bugs)

Include osgi plugin in build.gradle. Don't provide any source files (resources only).

Note the above test works if I remove osgi plugin or add at least one source file (Java).

### Your Environment

 * Build scan URL: 
 * Gradle 4.9
 * Java 1.8

**Comment by benfortuna** [comment]
I found similar issues in old JIRA but it's unclear if it was resolved (status is `wontfix`):

* https://issues.gradle.org/browse/GRADLE-1288
* https://issues.gradle.org/browse/GRADLE-982
* https://issues.gradle.org/browse/GRADLE-2391

**Comment by wszeboreq** [comment]
Is there any workaround?

**Comment by benfortuna** [comment]
You can try adding a task to create the osgi-classes dir and attach as a dependency of processResources. I found this worked for a while but stopped working around gradle 4.9 release.

I've just changed to using the bnd plugin, which has it's flaws (documentation, etc.), but no choice really because OSGi plugin is effectively abandoned.

**Comment by wszeboreq** [comment]
@benfortuna thank you for the hints. I'm falling into this problem with Gradle 4.10.3. Info log confirm 'osgi-classes' is removed as stale output.

As a workaround, I ended up with the following:

```
// workaround for https://github.com/gradle/gradle/issues/6370:
task createOsgiClassesDir {
    doLast {
       file("${buildDir}/osgi-classes").mkdirs()
    }
}

osgiClasses {
    dependsOn createOsgiClassesDir
    enabled false
}
```

It seems it's doing the trick, but I'm not sure and currently have no time to analyze if it has some negative side effects. I think for osgi plugins with no source it is OK.

**Comment by jjohannes** [comment]
The OSGI plugin is removed from the Gradle distribution in Gradle 6.0.

Please migrate to an OSGI plugin available from the [Gradle Plugin Portal](https://plugins.gradle.org).
