### ISSUE TITLE
Improve dependency locking and IDE import interactions

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#6383]
When enabling dependency locking and automatic import in an IDE, changing a dependency can result in the IDE import failing because Gradle will fail the build saying that the lock file is out of date.

The most likely solution is to make dependency locking lenient during IDE import.

A more general solution could be to have locking transparently apply local build file modifications to its lock state.

**Comment by oehme** [comment]
I think a lenient configuration shouldn't fail, but instead provide a list of errors. We already do that for unresolvable dependencies.
