### ISSUE TITLE
Implement specialized `DirectoryProvider` for easy chaining directory provider

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#6390]
### Expected Behavior

The specialized type `DirectoryProvider` is used instead of `Provider<Directory>` for easy chaining relative directory and file.

### Current Behavior

Beyond `DirectoryProperty#dir/file`, it's not obvious how to keep chaining additional layer of relative directory and file as the return type is `Provider<Directory>` which only offer `map`.

### Context

We should consider the concern here: https://github.com/gradle/gradle/issues/4019
See forum discussion: https://discuss.gradle.org/t/chaining-together-file-directory-providers/27980

### Your Environment

 * Build scan URL:

**Comment by Lanchon** [comment]
i second this, was about to request it myself.

the specialization damage for files and directories is already done, so you should finish the job and close the gaps.

```
// if i can do this:
void f(Directory rootDir) {
    def someDir = rootDir.dir('some-dir')
    def otherDir = someDir.dir('other-dir')
    def theFile = otherDir.file('the-file')
}

// the i should be able to do this:
void f(DirectoryProperty/DirectoryProvider rootDir) {
    def someDir = rootDir.dir('some-dir')
    def otherDir = someDir.dir('other-dir')
    def theFile = otherDir.file('the-file')
}
```

and note that you can use `File` instances in addition to strings in `Directory.dir()/file()`, so you should too in `DirectoryProperty/DirectoryProvider`

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by alllex** [comment]
Sorry for the late response

This is a valid request, and we agree that the ergonomics around Property/Provider types should be improved.

We are reopening the issue to track this. However, we aren't necessarily agreeing with the proposed API surface.

This relates to the [Provider API migration](https://github.com/gradle/build-tool-roadmap/issues/28). We likely won't have the capacity to address this before the migration is done.
