### ISSUE TITLE
uploadArchives task of maven plugin is UP-TO-DATE when dependencies have changed

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#6400]
### Your Environment
Gradle 4.9

### Steps to Reproduce
Sample project: [MavenPluginBug.zip](https://github.com/gradle/gradle/files/2295473/MavenPluginBug.zip)

Set up a simple Java library project as follows:
```
plugins {
    id 'java-library'
    id 'maven'
}

repositories {
    jcenter()
    google()
}

dependencies {
    implementation "com.android.tools.build.jetifier:jetifier-core:1.0.0-alpha07"
}


uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "file://" + projectDir.path + "/localRepo")
        }
    }
}

// The uploadArchives task does not specify an output, so we need to 
// specify it manually, otherwise the task will always be out-of-date.
tasks.getByName("uploadArchives").outputs.dir("localRepo")
```

Run `./gradlew uploadArchives --info` the first time.

Change the dependency `1.0.0-alpha07` to `1.0.0-alpha08`.

Run `./gradlew uploadArchives --info` the second time.

Observe the following output:
```
> Task :compileJava UP-TO-DATE
Skipping task ':compileJava' as it is up-to-date.
:compileJava (Thread[Task worker for ':',5,main]) completed. Took 0.014 secs.
:processResources (Thread[Task worker for ':',5,main]) started.
...
> Task :uploadArchives UP-TO-DATE
Skipping task ':uploadArchives' as it is up-to-date.
:uploadArchives (Thread[Task worker for ':' Thread 27,5,main]) completed. Took 0.0 secs.
```

As discussed at https://github.com/gradle/gradle/issues/6398, the fact that `compileJava` is `UP-TO-DATE` is expected because the change from Jetifier `1.0.0-alpha07` to `1.0.0-alpha08` is a non-ABI change. However, `uploadArchives` should *not* be `UP-TO-DATE` as the output pom file needs to be updated.

**Comment by big-guy** [comment]
This is doing it:
```
tasks.getByName("uploadArchives").outputs.dir("localRepo")
```

`Upload` is written under the assumption that it'll always run.  When you add outputs to it, the regular up-to-date checking kicks in.  This task doesn't declare its inputs, so changes to its configuration will not make it out of date. 

What are you trying to do?
