### ISSUE TITLE
failOnVersionConflict() broken in gradle 4.10-rc-1/2

### ISSUE THREAD

**Issue by mkmaier** [gradle/gradle#6403]
After upgrading to 4.10-rc-1 or rc-2, my build fails when `failOnVersionConflict()` is in effect, even though it is fine in 4.9. The error message it gives is confusing, mentioning only a *single* conflicting dependency (with itself?!).

### Expected Behavior
* Dependencies should continue to resolve cleanly, like in gradle 4.9.
* If there is indeed a conflict now, the error message should mention all involved clashing packages, not just a single one.

### Current Behavior
Build fails and dependencyInsight output is not helpful:

	$ gradlew  :fetch:bar:dependencyInsight --configuration pc_protocols --dependency com.acme.foo:protocols.global

	> Task :fetch:bar:dependencyInsight
	Dependency resolution failed because of conflicts between the following modules:
	   - com.acme.foo:protocols.global:6.24.9.20180716-161435

	com.acme.foo:protocols.global:6.24.9.20180716-161435
	   variant "default+runtime" [
		  org.gradle.status = release (not requested)
	   ]
	   Selection reasons:
		  - Was requested : didn't match versions 6.36.1.20180813-143748, 6.36.0.20180813-084056, 6.36.0.20180810-101221, 6.35.0.20180809-135903, 6.34.0.20180809-105201, 6.33.0.20180808-164958, 6.32.6.20180808-132345, 6.32.5.20180807-154913, 6.32.4.20180807-142403, 6.32.3.20180803-093406, 6.32.2.20180802-165920, 6.32.1.20180802-150209, 6.32.0.20180802-123412, 6.31.3.20180801-155049, 6.31.2.20180801-124350, 6.31.1.20180801-115002, 6.31.0.20180801-085420, 6.30.5.20180731-143119, 6.30.4.20180731-121223, 6.30.3.20180731-063146, 6.30.2.20180730-133221, 6.30.1.20180730-124846, 6.30.1.20180730-091833, 6.30.0.20180730-082414, 6.29.0.20180727-103458, 6.28.0.20180726-162229, 6.27.2.20180726-152910, 6.27.1.20180726-074550, 6.27.0.20180725-111351, 6.26.2.20180724-102155, 6.26.1.20180723-143901, 6.26.0.20180720-150059, 6.25.0.20180719-161156, 6.24.17.20180719-102600, 6.24.16.20180718-164418, 6.24.15.20180718-094254, 6.24.14.20180717-165840, 6.24.13.20180717-163015, 6.24.12.20180717-152451, 6.24.11.20180717-140800, 6.24.10.20180717-135339
		  - Forced
		  - By conflict resolution : between versions 6.24.9.20180716-161435 and 6.24.9.20180716-161435

	com.acme.foo:protocols.global:6.24.9.20180716-161435
	\--- com.acme.foo:protocols.messages:6.24.9.20180716-161435
		 \--- pc_protocols

	com.acme.foo:protocols.global:6.24.9.+ -> 6.24.9.20180716-161435
	\--- pc_protocols

### Context
 I'm forcing the dependency version in question, as part of an effort to achieve consistent versions across all modules of a multi-module build: `force com.acme.foo:protocols.global:6.24.9.+`, which is also the reason for using `failOnVersionConflict()`  in the first place.

### Steps to Reproduce (for bugs)
I'll be happy to provide additional information, but I don't see where to even begin to create a minimal project exhibiting this bug.

**Comment by big-guy** [comment]
@gradle/dependency-management ☝️ can you see if this is requires another RC?

**Comment by melix** [comment]
I'm looking into this, but fail to reproduce so far.

**Comment by mkmaier** [comment]
@melix you beat me by a minute, my reproducer is here: https://github.com/mkmaier/gradle-6403 Same general idea, only slightly more convoluted. `gradlew copy` will show the problem.
