### ISSUE TITLE
Deprecate withArguments() and withJvmArguments() in LongRunningOperation

### ISSUE THREAD

**Issue by donat** [gradle/gradle#6405]
The `LongRunningOperation` interface has multiple methods doing the same thing:
- withArguments() is the same as setArguments()
- withJvmArguments() is the same setJvmArguments()

Let's deprecate `withArguments()` and `withJvmArguments()` as the `setXX()` name describes the functionality better.

**Comment by big-guy** [comment]
@donat I think we're not going to do this for 5.2?  Can we unassign it from that milestone?

**Comment by donat** [comment]
Done. Thanks for the reminder!
