### ISSUE TITLE
Build scans should report percentages on top of raw numbers

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6426]
When looking at overall build metrics or task execution times, knowing the relative importance of a metric can sometimes be more helpful than just the raw number.

Example: it would be super useful to see that init and config take 10% of the build time instead of just 14 seconds.

![image](https://user-images.githubusercontent.com/9490724/44302953-aa6a3680-a2e8-11e8-9fad-ae6201b215c6.png)

**Comment by etiennestuder** [comment]
Thanks for the feedback @SUPERCILEX. We will add this to our queue of things to consider.

**Comment by SUPERCILEX** [comment]
Still think this would be helpful.

**Comment by bmuskalla** [comment]
Agreed. But given this is about build scans, the gradle issue backlog is the wrong place for this. @etiennestuder What would be a good place to put GE feature requests like this?

**Comment by etiennestuder** [comment]
Thanks for the proposal. We currently have no concrete plans on our roadmap to add percentages to these metrics. Thus, I'm going to close this issue.
