### ISSUE TITLE
Copy task zeros out pre-existing files

### ISSUE THREAD

**Issue by blakemcbride** [gradle/gradle#6435]
I have a copy task:
```
    task copyToLibs(type: Copy) {
	    into "libs"
	    from configurations.runtime
    }
```
jar files that existed in the libs directory prior to running the above task get truncated to zero bytes when the other files get copied.  These jar files are not present in configuration.runtime

### Expected Behavior

It should copy the dependencies and leave whatever is there before alone.

### Current Behavior

The pre-existing jar files are truncated to zero bytes.

### Context

I provide custom jar files with my app.  When the developer uses the app, I want to copy the dependencies to the libs directory.  The copy works fine but my custom jar files are getting zeroed out.

### Steps to Reproduce (for bugs)

I just do:  gradle copyToLibs

### Your Environment

Gradle 4.9.  64 bit LinuxMint OS.

**Comment by big-guy** [comment]
I don't see this behavior. 

Could you try adding this to your `copyToLibs` task?
```
   eachFile { fcd ->
     println fcd.file.absolutePath + " -> " + fcd.relativePath
   }
``` 

I suspect that those files are a part of the runtime configuration.

**Comment by blakemcbride** [comment]
When I add your println I see that it's trying to copy the file on to itself.  This is no doubt zeroing it out.  So, it seems my copy command is wrong.  How can I modify it to only copy the files cached by gradle and not the ones already in the libs directory?  Thanks!

**Comment by blakemcbride** [comment]
IMO, logic should be added to gradle to prevent it from attempting to copy a file onto itself.  This would eliminate problems even when the logic is not perfect.

**Comment by oehme** [comment]
Generally having a file be both an input *and* an output of the same task is not possible. You can either filter the inputs, e.g. using `configurations.runtime.filter {}` or by copying to a different directory, so that you don't end up trying to copy `lib` to a place where it already is.
