### ISSUE TITLE
`tasks.getByName("wrapper")` succeeds but `tasks.named("wrapper")` fails

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#6436]
### Expected Behavior
Build script should be able to configure the `wrapper` task using the lazy API.

```kotlin
val w1 = tasks.named("wrapper").get()
val w2 = tasks.getByName("wrapper")
require(w1 === w2)
```

### Current Behavior
`tasks.named("wrapper")` causes the build to fail with:

```
Task with name 'wrapper' not found in root project 'gradle-kotlin-dsl'.
```

Curiously, if the script executes `getByName("wrapper")` before executing `named("wrapper")` then it succeeds:

```kotlin
val w2 = tasks.getByName("wrapper")
val w1 = tasks.named("wrapper").get()
require(w1 === w2)
```

**Comment by big-guy** [comment]
Hmm, this isn't right.  It's probably because tasks like `wrapper`, `dependencies`, `help`, etc are registered via a different mechanism (aka "placeholders").  

I think this may go away in 5.0, since we'll be removing placeholders: https://github.com/gradle/gradle/issues/6277

**Comment by zustse** [comment]
This happens in 4.10-rc-3 too.

**Comment by lacasseio** [comment]
@bamboo The placeholder API is kind of like the lazy API meaning it gets created the first time it is accessed and is then available via the lazy APIs. Because of its internal nature, we didn't wire it properly with the lazy API.

**Comment by zustse** [comment]
@lacasseio Do I understand you right that I cannot configure the wrapper task with the above syntax anymore? Do I really have to use the `getByName` method in 4.10 or what is your recommended way to configure the wrapper task in 4.10?

BTW
```kotlin
tasks {
    named<Wrapper>("wrapper") {
        ...
    }
}
```
does not work either.

**Comment by oehme** [comment]
It'll work again in 5.0, unless @bamboo and @eskatos consider this serious enough to have another RC.

**Comment by zustse** [comment]
Ok, thanks for the info.

**Comment by big-guy** [comment]
We no longer have placeholder tasks, so this is no longer an issue.  The wrapper task is like any other.
