### ISSUE TITLE
Gradle uploadArchives removes api dependencies from generated Maven pom file

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#6438]
@fabiocarvalho777 commented on [Mon Aug 20 2018](https://github.com/gradle/gradle-native/issues/829)

### Expected Behavior
Gradle `uploadArchives` is supposed to upload properly the generated Maven artifact to the configured Maven repository.

### Current Behavior
Gradle `uploadArchives` is removing `api` dependencies from generated Maven `pom.xml` file (all `compile` dependencies are missing).

### Context
Because of this issue, the clients of my library are facing compilation issues, since API transitive dependencies are missing.

I have also opened [this StackOverflow question](https://stackoverflow.com/questions/51903077/how-to-prevent-gradle-uploadarchives-from-removing-compile-maven-dependency) for this issue, hoping I could be doing something wrong and that somebody could point it out for me, but unfortunately it didn't get any answer.

**Important:** I noticed that when working on my development environment, in which I don't need to use `uploadArchives`, but just `install`, I get the Maven pom file generated correctly and installed to my laptop local Maven repository. Of course it misses items configured as part of `uploadArchives`, such as developers and licenses meta-data, but all the dependencies, including the `api`/`compile` ones, are there, which makes me think `uploadArchives` seems to be removing `api`/`compile` dependencies when editing the `pom.xml` file to add meta-data.

### Steps to Reproduce (for bugs)
1. Have a Gradle based project, using `maven` and `java-library` plugins, making use of `api` and `implementation` dependencies.
2. Configure the Maven repository details and credentials, have a Maven pom file generated automatically by Gradle, and uploaded to the Maven repository.
3. You will notice that the `api` dependencies, which are supposed to be `compile` dependencies in the Maven pom file, are missing.

##### Real example of the issue below

- [Gradle project with an API dependency](https://github.com/paypal/butterfly/blob/butterfly_3/butterfly-extensions-api/build.gradle#L4)
- [Gradle configuration for generating and uploading Maven artifact](https://github.com/paypal/butterfly/blob/butterfly_3/build.gradle#L93-L146)
- [Generated and uploaded pom file](https://oss.sonatype.org/content/repositories/snapshots/com/paypal/butterfly/butterfly-extensions-api/3.0.0-SNAPSHOT/butterfly-extensions-api-3.0.0-20180820.190944-16.pom) (notice the API dependency (`org.slf4j:slf4j-api:1.7.21`) is missing)
- [Sample build](https://travis-ci.org/paypal/butterfly/builds/418373345)

### Your Environment

 * Build scan URL: https://gradle.com/s/a45h7sk36l7ts

**Comment by oehme** [comment]
This is an ordering problem. As soon as you call `mavenDeployer.pom`, the mappings are copied and new mappings are ignored. However, you are calling this from the parent project and later in the child project you apply the `java-library` plugin. I tried to fix this, but it's tough to do without breaking backwards compatibility. Therefor I suggest wrapping the `pom` block in `afterEvaluate`. This is also necessary to make the line `description = project.description` work. Right now you are executing this before the subproject has been configured, so its description will always be empty.
