### ISSUE TITLE
Junit 5 parallel test execution via Gradle fails with "Received a completed event for test with unknown id".

### ISSUE THREAD

**Issue by bersercker111** [gradle/gradle#6453]
### Expected Behavior
All tests are executed normally. Like they do when running them with idea runner.

### Current Behavior
One or several tests are ignored or fail. The cause seems to be "Received a completed event for test with unknown id".

Stacktrace: 
`Caused by: java.lang.IllegalArgumentException: Received a completed event for test with unknown id '27.78'. Registered test ids: '[27.82, 27.1, 27.81, :test]'Close stacktrace
at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:133)
at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:34)
at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:73)
at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)`

### Context
We decided to parallelize our test to improve test execution performance and build times using the new Junit 5 parallel test execution feature. 

### Steps to Reproduce

I've made an example project that somewhat resembles the tests that we have in the project i'm working on. An abstract class with method for some initialization to be done before running each test and a number of test classes extending it. Not sure this inheritance is relevant, but the bug doesn't reproduce if i'm just running the same test 100000 times with RepeatedTest annotation.

Github project: https://github.com/bersercker111/gradle_4_9_junit_5_3_RC1_parallel_test_bug

Commands to reproduce: 
```
git clone https://github.com/bersercker111/gradle_4_9_junit_5_3_RC1_parallel_test_bug
cd gradle_4_9_junit_5_3_RC1_parallel_test_bug
./gradlew test
```

The bug occurs almost every time on my environment if i'm running all test with gradle test task.

### Your Environment

Operating system	Linux 4.8.0-53-generic
CPU cores	4 cores
Max Gradle workers	4 workers
Java runtime	Oracle Java(TM) SE Runtime Environment 1.8.0_144-b01
Java VM	Oracle Java HotSpot(TM) 64-Bit Server VM 25.144-b01 (mixed mode)
Max JVM memory heap size	954 MB

Gradle version: 4.9.0
Junit version: 5.3.0_RC1

Build scan URL: https://scans.gradle.com/s/3gl3valcquzfo

**Comment by moleksyuk** [comment]
![screen shot 2018-08-21 at 15 31 30](https://user-images.githubusercontent.com/793472/44401459-65980700-a557-11e8-94d1-5cd8e188ed6f.png)

Time to time fails for me as well.

**Your Environment**

- System Version: macOS 10.13.6 (17G65)
- Kernel Version: Darwin 17.7.0
- java version "1.8.0_172"
- Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
- Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

**Comment by mdolinin** [comment]
Have same issue. After some debugging find out that issue is in `JUnitPlatformTestExecutionListener`
https://github.com/gradle/gradle/blob/2b3811843a0b371f018d7c828927bb725f1564cd/subprojects/testing-junit-platform/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestExecutionListener.java#L48
It doesn't expect to have multiple running classes simultaneously.
Temporary fix is to configure gradle test task to run classes in different forks
```
test {
      maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
}
```

**Comment by mdolinin** [comment]
Just one more update right configuration for workaround is 
```
test {
      systemProperties['junit.jupiter.execution.parallel.enabled'] = true
      maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
      forkEvery = 1
}
```

**Comment by cocorossello** [comment]
Same error here with gradle 4.10

**Comment by sdavids** [comment]
Another workaround:

build.gradle
```
test {
      maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
      forkEvery = 1
}
```

src/test/resources/junit-platform.properties
```
junit.jupiter.execution.parallel.enabled=true
```

Without the `forkEvery = 1` you sometimes get errors like this one:

```
Received a completed event for test with unknown id '5.18'. Registered test ids: '[2.2, 2.3, 2.1, 5.1, 2.6, 2.7, 2.4, 2.5, 2.8, 2.9, :test]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '5.18'. Registered test ids: '[2.2, 2.3, 2.1, 5.1, 2.6, 2.7, 2.4, 2.5, 2.8, 2.9, :test]'
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:29)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:133)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:34)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:73)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by cocorossello** [comment]
The workarounds do work, but forking the jvm for each test is not possible for a medium/big size project

**Comment by sdavids** [comment]
@marcphilipp Assuming we use Gradle > 5.1:

To get JUnit 5 parallel execution we need:

A)

build.gradle
```
test {
      maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1
}
```

src/test/resources/junit-platform.properties
```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
```

B)

src/test/resources/junit-platform.properties
```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
```

How does [maxParallelForks](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks) interact with JUnit 5 [junit.jupiter.execution.parallel.config.fixed.parallelism](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-config)?

**Comment by marcphilipp** [comment]
[maxParallelForks](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks) will use multiple VMs and JUnit will parallelize test execution according to the configured parallelism _in each of them_.

For example with [maxParallelForks](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks) = 2 and [junit.jupiter.execution.parallel.config.fixed.parallelism](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-config) = 4, Gradle will fork two VMs and distribute the found test classes evenly among them. In each VM, JUnit will execute the tests in 4 concurrent threads.

**Comment by marcphilipp** [comment]
Personally, I would just use JUnit's parallelism because it should have less overhead. Thus B) is sufficient IMHO.

**Comment by dlapunas** [comment]
> How does [maxParallelForks](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxParallelForks) interact with JUnit 5 [junit.jupiter.execution.parallel.config.fixed.parallelism](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-config)?

To extend @marcphilipp explanation, gradle distributes **classes** among processes, while junit distrubutes **classes and methods**. So after gradle spawns a VM, junit is responsible for parallelizing the classes (1-n) it received.

**Comment by sdavids** [comment]
Maybe add a section to the Gradle documentation?

**Comment by calvertdw** [comment]
Documentation still missing on this. Shouldn't there be a section here? https://docs.gradle.org/current/userguide/java_testing.html#using_junit5

**Comment by marcphilipp** [comment]
@calvertdw This is a JUnit feature, not a Gradle one and is documented in the [JUnit User Guide](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution).

**Comment by vlsi** [comment]
> Marc: I would just use JUnit's parallelism because it should have less overhead

a) Gradle-based parallelism should better control resource utilization for multi-module builds. Gradle-based VMs account the number of parallel workers, while JUnit parallelism does not know if there is concurrent execution of tests from another module.

b) Gradle-based parallelism could cache test outcomes. In other words, if a batch fails, then Gradle could retry just a subset of tests. Of course, source-code change would probably trigger re-execution of all the tests.

c) Gradle tracks execution history, so it knows past response times for the test, so it can better schedule test execution order

d) Gradle-based parallelism allows concurrent execution of tests which can't really work in the same JVM. For instance, if tests play with `System.properties`, `TimeZone.setDefault`, classloaders, then the tests are hard to parallelize in a single JVM.

**Comment by leonard84** [comment]
> d) Gradle-based parallelism allows concurrent execution of tests which can't really work in the same JVM. For instance, if tests play with `System.properties`, `TimeZone.setDefault`, classloaders, then the tests are hard to parallelize in a single JVM.

JUnit5 Jupiter has support for managing access to shared resources via [@ResourceLocks ](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-synchronization) the same goes for [Spock 2.0](https://spockframework.org/spock/docs/2.0/all_in_one.html#_resource_locks).

**Comment by vlsi** [comment]
@leonard84 , concurrent means simultaneous. ResourseLock makes the test executed in a single thread, however, the concurrent execution is not possible

**Comment by leonard84** [comment]
Yes, that is true, but in a most cases not every test modifies the shared resource, and resource locks only enforce single threaded execution, if you are acquiring a `READ_WRITE` lock, all test that use just a `READ` lock, can execute concurrently. Gradle runs a single test class also sequentially, so you don't have full concurrency either.

So YMMV depending on you test suite. For example, if you have a single data driven tests that makes a remote call to 100+ systems, Gradle class based forking method can't run those concurrently.

Also don't forget the memory overhead of multiple jvms, especially on free-tier ci-systems you are quite limited.

**Comment by sanity** [comment]
cc: @marcphilipp

Would it be possible to reopen? 

This prevents [our project](https://kweb.io/) from upgrading to Gradle 7. We've documented our experience [here](https://github.com/kwebio/kweb-core/issues/304). Our users have reported similar problems in their projects.

**Comment by marcphilipp** [comment]
@sanity Could you please create a new issue??
