### ISSUE TITLE
HTTP connections created by Gradle should use TCP keep-alive

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#6461]
### Expected Behavior

HTTP Build cache client should work for long builds where the build cache is behind a proxy that terminates idle connections.

### Current Behavior

In between usages of the HTTP connections, they may be terminated by a MITM or the server. The client doesn't see this until it goes to use the connection, upon which the request fails and the build cache is then disabled for the rest of the build.

### Context

Raised here: https://github.com/gradle/gradle/issues/6018#issuecomment-414687655

Note: this won't completely eliminate failures due to dead connections, but should significantly reduce them by the keep alive mechanism keeping the connection alive (i.e. preventing idle) and probing the connection regularly to test whether it is still alive.

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/6564.

@ldaley Can you confirm this works now?

**Comment by josecoll** [comment]
@wolfs is there any chance of back-porting this fix to 4.X ? 
I can confirm the fix works on a local custom gradle build of 4.9.

**Comment by wolfs** [comment]
@josecoll We probably won't be back-porting this feature to the 4.x series. We only do bugfix releases.

Is there something in particular which would block you from upgrading to 5.0 (i.e. do you have some deprecation messages in your build)?
