### ISSUE TITLE
Build-init-plugin should allow user-provided types.

### ISSUE THREAD

**Issue by jgsuess** [gradle/gradle#6474]
Build-init-plugin should take user-provided extensions and allow user-provided types.

### Expected Behavior
on calling the build init plugin, the user can pass a provider Jar that implements more init types and call one of them using `-p "MyProjectType"`.

### Current Behavior
The choice of project types is fixed.

### Context
We are developing a toolset for a cross-language analysis tool. We need to create target project layouts and would like to extend existing infrastructure and use existing conventions. `build-init` seems to be the conventional approach, but cannot be used in this way.

**Comment by trevjonez** [comment]
https://github.com/gradle/gradle/issues/1686

**Comment by oehme** [comment]
Closing as duplicate of #1686
