### ISSUE TITLE
Delete task always follows symlinks on Windows

### ISSUE THREAD

**Issue by kanigget** [gradle/gradle#6478]
When using a 'delete' task, Gradle does not delete the target of symlinks (by default), it just deletes the symlink itself.  This is great, except on Windows where it always follows symlinks (even when followsymlinks = false).

In the WindowsJdk7Symlink class, it appears to completely disable symlink support in the constructor on the basis that they are not necessarily accessible by normal (non-administrator?) users.  However the platform does actually support symlinks, and this flag prevents it from detecting symlinks at all.

### Expected Behavior

Delete steps should not (by default) follow symlinks on any platform.

### Current Behavior

Delete steps delete the target of a symlink on Windows.

### Context

Our build process involves symlinking some dependent NodeJS modules, but the 'clean' tasks are actually deleting the dependent module instead of just the symlinks themselves.

### Steps to Reproduce (for bugs)

[build.zip](https://github.com/gradle/gradle/files/2313266/build.zip)

'gradle create' will create a directory called 'target' and a symlink called 'symlinkedDir' that points at it.  'gradle clean' will remove both 'symlinkedDir' and the contents of 'target'.  It should only remove 'symlinkedDir'

### Your Environment

Gradle 4.9, Windows 7 64bit SP1.

**Comment by lacasseio** [comment]
This should be fixed in 5.3, RC will be coming out soon. Reopen if the RC doesn't fix the issue.
