### ISSUE TITLE
Provide insights about incremental compilation to build scans

### ISSUE THREAD

**Issue by melix** [gradle/gradle#6481]
### Context

For incremental compilation, we track a lot of different things, and sometimes we decide to recompile everything. We know why (constant X has changed, analysis is missing, ...) but it's not exposed to the user, and not in debugging either. It would be nice to capture this in a way that build scans could use.

**Comment by ldaley** [comment]
This sounds very useful for debugging the incremental compiler. It's not clear to me what users are going to do with this though.

**Comment by melix** [comment]
Not necessarily for debugging the incremental compiler. Sometimes you will just not understand why a full recompile happened and blame the tool. By showing the reason, we can actually explain why (just like cache misses), or, if the incremental compiler was wrong, it could be used to create an issue.

**Comment by ldaley** [comment]
Cache misses are potentially user actionable. For example, users can refine their inputs configuration or stabilise the inputs. I can't see the same thing here. 

I'm, indirectly, asking for us to define the problem we are solving first instead of jumping to the solution of this information in build scans.

**Comment by oehme** [comment]
There are several user-actionable things we could provide:

- how many classes were recompiled based on a certain change? - A high number indicates a highly tangled code base. Decoupling through interfaces could make your builds faster
- why did we do a full recompile? Overuse of constants can defeat the incremental compiler. Using static methods is more advisable in most cases (also according to the Java language spec, which states that "constants should only be used for things that are constant in the mathematical sense, i.e. things that never change"
- what annotation processor is preventing incremental compilation? You might want to get rid of it or contact the author

**Comment by ldaley** [comment]
> how many classes were recompiled based on a certain change?

I think for this to be useful it would have to be over time. It seems unlikely to me that it would be very useful to do this on a per case basis, as analysing a single instance in isolation doesn't buy much (i.e. how common is this kind of change? Is it worth optimising?). Such a feature would probably build on the same kind of data we have in mind for this issue, but it would also need more.

> Overuse of constants can defeat the incremental compiler.

I think we might be better off acknowledging the reality of how constants are used in practice and accommodating, if possible. 

> What annotation processor is preventing incremental compilation? You might want to get rid of it or contact the author

I think this would be better suited for a more general “warning” mechanism for any task, which is also under consideration.

**Comment by tjni** [comment]
I think this can be most valuable if build scans capture whether compilation was incremental or not along with a way to reproduce the behavior. That's enough for me to begin an investigation.

Is it possible for build cache enabled CI builds and hot reload (after the first change) to also leverage incremental compilation? If so, the value of being able to improve incremental compilation increases.
