### ISSUE TITLE
Expand --tests capabilities

### ISSUE THREAD

**Issue by MartyIX** [gradle/gradle#6505]
Hi,

`gradle test --tests <smt>` [specifies](https://docs.gradle.org/current/userguide/java_testing.html#simple_name_pattern) which tests should be run. 

It would be great to be able to specify which tests **must not** run. The desired behavior would allow for example to skip integration tests with a command along these lines:

```
gradle test --tests-not-to-run '*IntegTest'   # just illustration
```

Environment: Gradle 4.9 (all versions)

Best regards,
Martin

PS: @mkobit wrote on Slack: I think it would be cool (at least for junit 5) to be able to pass in the selectors/filters into `--tests` like `--tests "tagFilter=(fast && local)"` or `--tests "selectPackage="com.mkobit.stuff"`

**Comment by oehme** [comment]
Integration tests should really be in their own task. The `test` task is meant for unit tests. 

Overall I'm not convinced that "which tests not to run" is a common enough use case to deserve its own command line option.

**Comment by MartyIX** [comment]
To clarify: What I'm really after is a way to express negation in `--tests`. I don't really care if there is a new option or some other syntax.

**Comment by honzasterba** [comment]
It would be nice to have the same feature as maven does:

`mvn test -Dtest=!LegacyTest`

**Comment by oehme** [comment]
What is the use case here? What day-to-day problem would negation solve? `--tests` solves the problem of "I changed a certain area of the code and want to test that area only". I don't see a similar use case for negation at the moment.

**Comment by MartyIX** [comment]
https://blog.jdriven.com/2017/10/run-one-or-exclude-one-test-with-maven/ seems to summarize it nicely:

> Excluding tests from the build cycle by the command line usually occurs when the following scenarios meet:
> 
> *    A test requires significant amount of resources (time, memory, disk space, etc.)
> *    The run needs to be independent from the IDE (reenact the Continuous Integration / Continuous Delivery pipeline) as some IDEs load test-dependencies on the compile-time class-path.
> *    You have no or limited ability to change the code-base

**Comment by MartyIX** [comment]
I have resolved my issue by introducing `integrationTest` as documented in Gradle docs. 

This issue may be closed, if you don't like the proposed new functionality.

**Comment by mkobit** [comment]
@MartyIX I wouldn't close this yet, as there are a handful of others (including me) who :+1: it. I agree that introducing more CLI options like `--tests-not-to-run` would be confusing, but there may be other approaches for what I think the feature is, which is _improve built-in support for filtering through command-line execution_. 

For my use case, I'd like to be able to use the various options supported by [`JUnitPlatformOptions`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/junitplatform/JUnitPlatformOptions.html) to be apply to supply additional filtering with the Gradle CLI. The example I provided was to be able to supply those filters through the existing `--tests` option through use of things like `--tests includeEngine=jupiter && excludeTag=integration`, but there may be other ways to do something like this. 

I think my current option is to have my build script wrap all of my desired configuration options in a kind of project property like `-PmyTests=...` and do the parsing/configuration in the build script. I think this type of parameterized configuration could be done by a plugin with some clever use of project properties to configure the `junitPlatformOptions` without even needing build-in support, but worth thinking about it.

**Comment by sschuberth** [comment]
> What is the use case here? What day-to-day problem would negation solve?

For us, it would help to run all but some (functional) tests that require a special environment. Those excluded test would be run later inside a Docker container with required tools installed. As that set of tests is quite large and spread across different subprojects (that share a common package prefix), using e.g. test tags is less convenient here than simply being able to exclude tests by package name wildcard. So 👍🏻 for being able to say something like `./gradlew funTest --tests='!org.ossreviewtoolkit.plugins.packagemanagers.*'`.

**Comment by sschuberth** [comment]
I'm now working around this limitation with

    tasks.withType<Test>().configureEach {
        properties["exclude.tests"]?.also { excludes ->
            filter {
                excludes.toString().split(',').map { excludeTestsMatching(it) }
            }
        }
    }

**Comment by sschuberth** [comment]
> What is the use case here? What day-to-day problem would negation solve?

Moreover, you could have asked the same before introducing [TestFilter.excludeTestsMatching​()](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestFilter.html#excludeTestsMatching-java.lang.String-). But now that `excludeTestsMatching​()` is there, it seems inconsistent that `includeTestsMatching​` as a matching `--tests` CLI option, but `excludeTestsMatching​()` has no matching CLI option.

**Comment by sschuberth** [comment]
@wolfs @jjohannes If I would be planning to work on this, would the preferred way to introduce a new CLI option, like `--tests-exclude`, or to extend the syntax of the existing `---tests` option (e.g. by a `!` prefix)?

**Comment by ljacomet** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.

***

Having more ability to control which tests run from the CLI does make sense. The exact implementation would be the result of a design spec.
