### ISSUE TITLE
Rethink --fail-fast option

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6513]
Instead of having a special flag on the Test task, I think its behavior should be to fail fast by default and only continue with other tests if the `--continue` build option was used.

**Comment by lptr** [comment]
Can you explain the rationale for this change? It's not obvious to me why this would be better than the current behavior.

**Comment by oehme** [comment]
Everything else in Gradle fails fast by default and --continue is the way to make it continue. The Test task is inconsistent in this regard.

**Comment by oehme** [comment]
The question should be: What use case does the separate flag solve? As I said we introduced it for backwards compatibility reasons, which is no longer a concern in 5.0.

In other words: Why would we make this configurable on a per task level instead of using the --continue flag.

**Comment by abishek3876** [comment]
1. How will this work for other test tasks (like Android instrumentation tests)? If those are not going to stop after the first failure, then I think that inconsistency is a bit more confusing than the fail-late behavior of only the test task.
2. For our builds which run in the CI environment, we would like to have all the tests executed even if one of the tests fail, the report in the CI system should show all the failures. I am not really sure what the "--continue" flag does exactly, but if it's going to publish the builds even after a test failure then that would be wrong for most of the people.

I believe the fail-fast option for tests is only useful in developer machines, but most developers would be using an IDE which should give them more control over which tests to run in the first place.

**Comment by oehme** [comment]
1. Not all kinds of tests support stopping, but I don't think that is an inconsistency in Gradle. Gradle will always do a best effort of stopping test execution.
2. The usual way to do this is to have two Gradle invocations `gradle check --continue` and then `gradle publish`. Almost all projects I've seen use `--continue` on CI already, because they want to get all failures from all test tasks, not just the first one that failed.

**Comment by CristianGM** [comment]
To me 3 makes a lot of sense, while 1 makes me think some projects would have to change their CI scripts or they'll publish even when the tests are broken.
I don't want to fail fast because I want all the tests reports, so I'll need to add a --continue and then split the command so the next task doesn't run if the tests failed.

**Comment by oehme** [comment]
Dependent tasks don't run when a dependency failed. If the tasks don't have a relationship then there would be no guarantee of ordering to begin with. So you want to make your publish task depend on check in any case. 

Using `--continue` is the normal thing to do on CI, otherwise you don't get all test reports but only the first test task that fails.

**Comment by oehme** [comment]
I've thought about this some more and I think --fail-fast and --continue look redundant because the former is binary for no good reason. If we had --max-failures on the Test task instead, it would allow users to make much better trade-offs between fast feedback and information gained. Seeing only a single failure is often not enough, but waiting for all failures can be costly for end-to-end tests.

I also noticed that --fail-fast is not incubating, so we can't just pull it out in 5.0 anyway without violating our deprecation policy.

So instead of removing the option, maybe we should introduce `--max-failures` as a more general replacement?

**Comment by ldaley** [comment]
Just on naming alone, “max” isn’t quite right, though it is succinct. Something like —stop—after—failure—count  would be more “correct”

**Comment by ldaley** [comment]
Also, is time more important here? Or is it the count?

**Comment by oehme** [comment]
Something like "continue another minute after the first failure" could also work, yes.

**Comment by guai** [comment]
Hi
I'm using gradle 7.6. is `--fail-fast` still a thing?

**Comment by ljacomet** [comment]
Sorry for the late reply

`--fail-fast` stayed. This remains closed as obsolete.
