### ISSUE TITLE
org.gradle.api.tasks.testing.Test::useTestNG does not have correct type signature

### ISSUE THREAD

**Issue by jnizet** [gradle/gradle#6519]
This has already been filed for both `useJUnit()` and `useTestNG()`, but was fixed only for `useJUnit()`: see #2675.

### Expected Behavior
When using the Kotlin DSL, I should be able to configure TestNG options without casting `this` to TestNGOptions. 

### Current Behavior
I'm forced to cast, because the method takes an `Action<? super TestFrameworkOptions> testFrameworkConfigure` as argument instead of an `Action<? super TestNGOptions> testFrameworkConfigure`.

### Context
I'm trying to use the Kotlin DSL to configure TestNG.

### Steps to Reproduce (for bugs)
```
plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    testCompile("org.testng:testng:6.3.1")
}

tasks.getByName<Test>("test") {
    useTestNG {
        excludeGroups("integrationTests")
        includeGroups("unitTests")
    }
}
```

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/6520
