### ISSUE TITLE
TaskProvider.configure should return itself

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#6524]
Currently I write a bunch of new Gradle scripts and use the following syntax for that:
```kotlin
val donwloadStrings = tasks.register("updateStrings").apply {
    configure {
        // A bunch of config 
    }
}
 tasks.register("updateStrings").configure {
    dependsOn(downloadStrings)
    // Some other config 
}
```

### Expected Behavior
`TaskProvider.configure` should return itself. We can than omit the `apply{}` or `with{}`.

### Current Behavior
`TaskProvider.configure` don't return itself but `void`. 

### Context
I want to `configure` a lazy task directly and use the returned `TaskProvider` in another task (as dependency).
First register all the task and **later** call configure on them feels wrong somehow:
```
val donwloadStrings = tasks.register("updateStrings")
val updateStrings = tasks.register("updateStrings")

downloadStrings.configure {
   // Configure
}
updateStrings.configure {
  dependsOn(donwloadString)
}
```

### Your Environment
Gradle 4.10-rc-3
IntelliJ IDEA 2018.2.2 (Community Edition)
Build #IC-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by lacasseio** [comment]
Although I see this could be valuable, I fail to see how it's valuable in this specific use case. You can pass a configuration closure/lambda/action during the registration like:

```
val downloadStrings = tasks.register("downloadStrings") {
   // Configure
}
val updateStrings = tasks.register("updateStrings") {
    dependsOn(downloadStrings)
}
```

The question would be why did you feel you needed to register all the task and later configure them? That would be a failure to properly communicate on our part.

**Comment by StefMa** [comment]
Hey @lacasseio 
that is true. I missed that fact the we can configure it directly in the `register()` method 🙃 
I just replace "everything" to that code. Works fine 👌 

The only thing where it's missed is the overload where you can add **arguments** to the task.
![bildschirmfoto 2018-08-27 um 13 52 14](https://user-images.githubusercontent.com/10229883/44658255-6ec61f80-aa00-11e8-84c0-eada346bf829.png)
At lest for this it would be valuable.

> The question would be why did you feel you needed to register all the task and later configure them? 

Maybe i described it wrong. I don't want to do that 🙃 But that is a "workaround" to don't add `apply` or `with`.
So everything is good here 👍 

Feel free to close this issue if you don't want to return the `TaskProvider` on `configure`. I'm fine with the current API :)

**Comment by StefMa** [comment]
That would be a good solution, yes 👍 😀

**Comment by tbroyer** [comment]
BTW, if you go that way, I'd suggest providing a Kotlin extension using `vararg`:
```kotlin
fun <T: Task> TaskContainer.register(name: String, type: KClass<T>, vararg constructorArgs: String, configuration: T.() -> Unit): TaskProvider<T> =
    register(name, type.java, constructorArgs).apply { configure(configuration) }
```
that could be called as:
```kotlin
tasks.register("someTask", CustomTask::class, 42, 52.0) { /* … */ }
```

(note that as expressed above, it doesn't even use the proposed new API, so could be added to kotlin-dsl right now; otherwise it could use the proposed new API by wrapping the vararg into a list; you would probably want to add the corresponding `registering` delegate, and maybe a reified variant)

**Comment by lacasseio** [comment]
I opened issue https://github.com/gradle/gradle-native/issues/835 to track the proposed work for a `register` overload.

**Comment by StefMa** [comment]
I'm confused. Why have you moved that to the `native` repo? 🤔 
Isn't that a "Gradle core" thing and needs to implemented in *this* repo?
