### ISSUE TITLE
Accessing DefaultTask methods leads to issues in build script

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#6530]
I noticed that my build script failed if I have the following task:
```kotlin
open class ATask : DefaultTask() {

    @TaskAction
    fun xx() {
        println(buildDir)
    }
}

// It does not care if we use `create` or `register`
tasks.create("crash", ATask::class.java)
```

Gradle reports with this example:
> The constructor for class [] should be annotated with @Inject

If I add a `@Inject` constructor it failed with a `ArrayIndexOutOfBoundsException`.

The reason is that we try to access the `buildDir` inside a `(Default)Task`. 
The `getBuildDir()` method is part of `Project` **not** of a `DefaultTask`. It seems that the IDE can't resolve it correctly but Gradle fails at runtime.

According to @eskatos it is maybe related to the way Gradle instantiate tasks.
He posted a example in Slack which works:
```
println(Foo())
class Foo { init { println(buildDir) } }
```
[See Slack](https://gradle-community.slack.com/archives/CA7UM03V3/p1535375382000100?thread_ts=1535360843.000100&cid=CA7UM03V3)

### Expected Behavior
The best behavior I expect is that the IDE reports me that I can't access top-level members inside a "closed" class. 
**Or** it should work and Gradle does not fail 🙃 

### Current Behavior
It failed :/

### Your Environment
Gradle 4.10-rc-3 (but effects also 4.9)
IntelliJ IDEA 2018.2.2 (Community Edition)
Build #IC-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by eskatos** [comment]
Issue moved to [gradle/kotlin-dsl #1068](https://github.com/gradle/kotlin-dsl/issues/1068) via [**ZenHub**](https://www.zenhub.com/)
