### ISSUE TITLE
PluginDependenciesSpec: Unable to keep versions in sync across plugins and other dependencies

### ISSUE THREAD

**Issue by jeremy-w** [gradle/gradle#6541]
### Expected Behavior
- Given I have a dependency that should use the same version as an accompanying plugin, like:

  - Implementation dependency: `implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$KOTLIN_PLUGIN_VERSION"`
  - Plugin dependency: `id 'org.jetbrains.kotlin.kapt'`
- When I change the version for the plugin dependency
- Then the version of the implementation dependency should automatically change as well

As a further, trickier scenario:

- Given I have two plugins vended by the same module
- I'd like to be able to easily say, "use `ModuleVersion`" in one place.
- And share that across plugin dependencies as well as other dependencies.

### Current Behavior
- Can't share a single, global version definition:
  - Previously, my project coordinated versions between plugin and implementation dependency by using a project property that got interpolated into the classpath needed to resolve the plugin and into the implementation dependency spec (as above)
  - But a `PluginDependenciesSpec` requires a literal string as the version, so both dependencies can no longer share the same definition.

- Can't read the plugin version to use for the implementation version:
  - I expected to be able to fish out the version using `pluginManager.findPlugin("plugin id").version`, and use that to sync the implementation dependency version with the plugin's.
  - But the `AppliedPlugin` returned by `findPlugin` doesn't have a `version` property, just the ID (which is what I used to find it in the first place, so it isn't telling me much new!).

In the case where there are multiple plugins provided by the same module, this gets even messier, since you now need to update them all manually, due again to the literal string requirement of `PluginDependenciesSpec`.

### Context
- I am attempting to use the modern plugins DSL, as described in ["Using Gradle Plugins"](https://docs.gradle.org/current/userguide/plugins.html).
- But manually syncing versions by dropping in comment tokens to help me regex-replace is pretty gross.
- I'm not hugely conversant in Gradle, so it's possible I'm missing some elegant solution, like just specifying the version with one of those, and letting that drive the selection of the module version for all others. (Plugins really didn't seem to like leaving the version `null`, though.)

### Steps to Reproduce (for bugs)
N/A

### Your Environment
Building an Android app + library using Gradle and Android Studio.

**Comment by eskatos** [comment]
Hi @jeremy-w,

The Gradle Forums available at https://discuss.gradle.org/ are be a better place for usage questions.

You can centrally declare your plugin versions in the `pluginManagement {}` block of your `settings.gradle` file using [Plugin Resolution Rules](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_resolution_rules). It doesn't have the limitations of the `plugins {}` block that can be found in project scripts.

As for regular dependencies you might be after [customizing the dependency resolution behavior](https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html).

HTH

Please post in the forum if you face some difficulties.

**Comment by jeremy-w** [comment]
Thanks @eskatos. As the `PluginManager.findPlugin` API is still incubating, I thought that noting the absence of `AppliedPlugin.version` would be useful feedback for the Gradle DSL itself, vs a specific usage question.

## What's the preferred way to provide feedback on Incubating features?
I reviewed the docs on the [Feature Lifecycle](https://docs.gradle.org/current/userguide/feature_lifecycle.html), and while it pointed out that features incubate in order to get feedback, it didn't actually give me any hints as to _how_ the Gradle team would prefer to receive that feedback! Is the answer to that also "see the forums"? If not, what's the preferred way to provide feedback on Incubating features? (I see some topics on the forums for feedback on early 3.0 releases, but nothing for more recent.)
