### ISSUE TITLE
Checkstyle/FindBugs HTML report stylesheet does not support type-safe configuration

### ISSUE THREAD

**Issue by jjustinic** [gradle/gradle#6543]
### Expected Behavior
Using the Kotlin DSL, the HTML report stylesheet should allow configuration as follows:
```
tasks.withType<Checkstyle>() {
    reports {
        xml.isEnabled = false
        html.isEnabled = true
        html.stylesheet = resources.text.fromFile("config/xsl/checkstyle-custom.xsl")
    }
}
```
### Current Behavior
The html report is only configurable as a `SingleFileReport`, requiring a cast to `CustomizableHtmlReport`:
```
 tasks.withType<Checkstyle>() {
    reports {
        xml.isEnabled = false
        html.isEnabled = true
        (html as CustomizableHtmlReport).apply {
            stylesheet = resources.text.fromFile("config/xsl/checkstyle-custom.xsl")
        }
    }
}
```

### Context

This issue was encountered while working on PR #6510 Include Kotlin DSL samples for code quality plugin chapters for epic #6442 Include Kotlin DSL samples in all user manual chapters.

**Comment by eskatos** [comment]
Closing as delivered in #6551, thanks again James!
