### ISSUE TITLE
[4.10] - org.gradle.api.tasks.compile.CompileOptions:incremental - default is false?

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#6544]
## Description:
Do the docs need to be updated? `CompileOptions:incremental` default returns false according to the docs.

## Docs:
 - https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:incremental

## Release Notes:
 - https://github.com/gradle/gradle/releases/tag/v4.10.0
 - https://docs.gradle.org/4.10/release-notes.html#incremental-java-compilation-by-default

**Comment by oehme** [comment]
Indeed, thanks for the pointer.

**Comment by jaredsburrows** [comment]
How often do you update the site?

**Comment by oehme** [comment]
The docs are static and built together with the release. We generally don't touch them after the fact. So the correction would be in the docs of the next release.

@eriwen how involving would an ad hoc correction to the published docs be?

**Comment by eriwen** [comment]
@oehme much more involved than I'd like. Luckily we have a chance to fix with 4.10.1. Should we cherry pick a fix here?
