### ISSUE TITLE
More performance from smaller <max-workers> ?

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#6545]
I made the interesting observation on my computer (having 56 cores) that a clean build of AndroidX using `--max-workers=16` runs much faster than a clean build without any specification of `--max-workers`.

I've also discovered that according to `pstree -p ${gradlePid} | wc -l`, Gradle has 8000-10000 child processes in existence at a time.

I've also found that even with only "--max-workers=16", according to `htop`, Gradle generally uses more than 99% of all of the CPUs

My guess is that what's going on is that Gradle (specifically, probably one or more Gradle plugins) is spawning many more processes than is needed, and that that's resulting in excess context switching.

I'm not sure whether this is something that Gradle can reasonably be expected to dynamically detect and compensate for, but if it is then that would be handy.

I'm still hoping to dig deeper into the details eventually to figure out more specifically why so many processes are spawning.

I enabled build scans for two representative builds, which can be found at:
Build scan from max-workers 16         : https://scans.gradle.com/s/fknlr375evb4o
Build scan from max-workers unspecified: https://scans.gradle.com/s/mmkeof2zrjxcy

To reproduce this behavior:
1. download the androidx-master-dev branch of AndroidX via `repo` as described in https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/README.md
2. run `cd frameworks/support && rm -rf ../../out && GRADLE_USER_HOME../../out ./gradlew buildOnServer`

Some additional build durations for other values of --max-workers :

--max-workers=8 buildOnServer
9.37user 11.74system 12:42.06elapsed 2%CPU (0avgtext+0avgdata 383932maxresident)k
32inputs+319152outputs (0major+98306minor)pagefaults 0swaps

--max-workers=16 buildOnServer
9.02user 10.86system 11:22.92elapsed 2%CPU (0avgtext+0avgdata 409428maxresident)k
0inputs+319088outputs (0major+103593minor)pagefaults 0swaps

--max-workers=24 buildOnServer
9.28user 11.56system 12:06.81elapsed 2%CPU (0avgtext+0avgdata 499748maxresident)k
0inputs+319192outputs (0major+128482minor)pagefaults 0swaps

--max-workers=32 buildOnServer
11.05user 12.31system 13:57.19elapsed 2%CPU (0avgtext+0avgdata 579620maxresident)k
0inputs+319256outputs (0major+152748minor)pagefaults 0swaps

--max-workers=40 buildOnServer
12.42user 12.18system 15:00.71elapsed 2%CPU (0avgtext+0avgdata 576896maxresident)k
0inputs+319280outputs (0major+150236minor)pagefaults 0swaps

--max-workers=48 buildOnServer
11.77user 11.93system 17:40.43elapsed 2%CPU (0avgtext+0avgdata 616720maxresident)k
0inputs+319408outputs (0major+157018minor)pagefaults 0swaps

--max-workers=56 buildOnServer
12.91user 12.34system 23:53.76elapsed 1%CPU (0avgtext+0avgdata 631672maxresident)k
0inputs+319552outputs (0major+160298minor)pagefaults 0swaps

--max-workers=64 buildOnServer
14.16user 13.41system 26:04.43elapsed 1%CPU (0avgtext+0avgdata 653612maxresident)k
0inputs+319776outputs (0major+165561minor)pagefaults 0swaps

Anyway, I'm not necessarily expecting a specific solution from Gradle ; mostly just trying to raise awareness

Thanks

**Comment by oehme** [comment]
Having thousands of child processes is definitely not normal. Gradle itself will only allow `--max-workers` "things" to run at any given time. Have you checked what some of these processes are doing? Maybe we can narrow down the culprit that way.

**Comment by mathjeff** [comment]
Slight clarification/correction to my previous statement, it turns out that the >8000 number that I computed from `pstree -p ${gradlePid} | wc -l` was actually threads, not processes.

Now it turns out that based on `jstack -l ${gradlePid} | grep 'ForkJoinPool-' | wc -l`, it looks like there are 5445 ForkJoinPool workers. Most of the blocks of output from jstack look like:

"ForkJoinPool-10488-worker-56" #20122 daemon prio=5 os_prio=0 tid=0x00007f351c055000 nid=0x15718 waiting on condition [0x00007f2d22dec000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006d0a73b50> (a java.util.concurrent.ForkJoinPool)
        at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

   Locked ownable synchronizers:
        - None


I don't see very many instances of the text "ForkJoinPool" in the source code of Gradle but I do see a bunch of instances in the source code of the Android Gradle Plugin so I guess that's probably where I'll look next

**Comment by oehme** [comment]
Make sure you're using the latest Gradle version. There was a Thread leak that we fixed in 4.10.

**Comment by oehme** [comment]
@ghale can you take a look at this one? Not sure if this is a bug in the worker API or a bug in AAPT.

**Comment by ghale** [comment]
I took a quick look at this, and I don't see any evidence of worker API misbehavior with this build on 4.10.  With max-workers=16, I see the worker executor thread pool grow to about the size of max-workers at one point and then dropped off almost immediately.  What I do see is several hundred threads getting started from a `ForkJoinPool` which appear to be related to dexing (and maybe other things, too, but not core Gradle stuff).  However, I did not see the thread count growing to the sorts of numbers we're talking about (thousands).  With 16 workers, it appeared to max out around 500 total threads on my machine.  It's also possible that we're looking at different measurements of thread count, too.

It's conceivable that the pre-4.10 thread leak could cause thousands of `WorkerExecutor` threads to be left lying around, but I'm not seeing it with 4.10.  Going from 8 to 16 max workers, the number of `ForkJoinPool` threads definitely goes up - at least double, if not more - it's likely that this is either causing memory pressure or I/O pressure leading to the slower performance at higher concurrency levels.

**Comment by mathjeff** [comment]
Another update on the progress of this:

We ended up finding that having the Android Gradle Plugin's DexMergerTransform ( https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/transforms/DexMergerTransform.java#240 ) call shutdown() on its ForkJoinPool when finished resulted in faster builds and decreased the number of threads (`reported by pstree -l -a $gradlePid`) to less than 8000 from more than 1300.

We also found that (without applying the above DexMergerTransform fix,) increasing the memory in gradle.properties from `org.gradle.jvmargs=-Xmx4g` to `org.gradle.jvmargs=-Xmx8g` resulted in faster builds too (but of course didn't seem to change the max thread count) ; we're still investigating exactly how much of an impact it makes, but preliminary tests indicate that it makes the build take 33% as long (3x throughput) on the build servers, and 88% as long on my development computer.

Not exactly looking for a solution from Gradle for this, although it occurs to me though that if Gradle were to have some sort of clever memory usage report then that could potentially help with debugging (does this already exist and I just don't know about it? )

Thanks!

**Comment by oehme** [comment]
Would you mind sharing these insights on the Android issue tracker instead? I'm going to close this, since the problem turned out not to be on the Gradle side.

[Build scans](https://scans.gradle.com) will show you how much time your build spends in garbage collection, which can give you a good hint when to increase memory. If you want to dig deeper into where the memory usage originates from, you can use the [gradle-profiler](https://github.com/gradle/gradle-profiler) to get JFR recordings.

**Comment by mathjeff** [comment]
Sounds good to me; thanks.

It looks like this thread leak was independently fixed in the Android Gradle Plugin but only after 3.2.

At your suggestion, now when I specifically look into the Performance tab in one of my earlier build scans ( https://scans.gradle.com/s/mmkeof2zrjxcy ), I see two lines that say:

"Total build time	24m 2.308s"
"Total garbage collection time 18m 50.025s"

Thanks
