### ISSUE TITLE
Changing configuration attributes is not allowed even though the configuration has not been resolved

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#6549]
### Environment
Gradle 4.9

### Steps to Reproduce
Given the following build file:
```
repositories {
    jcenter()
}

configurations {
    foo
}

dependencies {
    foo 'junit:junit:4.12'
}

configurations {
    kapt
}

configurations.foo.files

configurations.all { configuration ->
    if (configuration.name.contains("kapt")) {
        configuration.attributes.attribute(Attribute.of("artifactType", String.class), "processed-jar")
    }
}
```

`./gradlew help` produces this error:
```
Cannot change attributes of configuration ':kapt' after it has been resolved
```

However, configuration `:kapt` was never resolved, so the error should not have been thrown.

(If it turns out that changing configuration attributes is not allowed after *any* of the configurations is resolved, then the error message should indicate that too.)

### Context
This bug was originally reported on Android Studio issue tracker: http://issuetracker.google.com/111990719. The users are using projects that have some configurations (not `kapt`) resolved at configuration time, but their builds fail with a message saying that `kapt` was resolved too early.

**Comment by melix** [comment]
This is not a bug, to mutate the attributes you need to use the

```
attributes { attribute(...) }
```

notation. There's a technical reason for this that we're trying to remove (making sure mutation happens at the right time), see https://github.com/gradle/gradle/issues/5400

**Comment by hungvietnguyen** [comment]
If I change
```
configurations.all { configuration ->
    if (configuration.name.contains("kapt")) {
        configuration.attributes.attribute(Attribute.of("artifactType", String.class), "processed-jar")
    }
}
```

into
```
configurations.all { configuration ->
    if (configuration.name.contains("kapt")) {
        configuration.attributes {
            attribute(Attribute.of("artifactType", String.class), "processed-jar")
        }
    }
}
```

I still get the same error. Am I missing something?
