### ISSUE TITLE
OsgiManifest needs to be casted in the Kotlin-DSL

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#6552]
As part of the Kotlin-DSL documentation update I updated the [OSGI Plugin doc here](https://github.com/gradle/gradle/pull/6539).
The Groovy documentation there said already this:
> // the manifest of the default jar is of type OsgiManifest

for this line of code:
```
jar {
    manifest {
    }
}
```
So this `manifest` is not a [`org.gradle.api.java.archives.Manifest`](https://docs.gradle.org/4.10/javadoc/org/gradle/api/java/archives/Manifest.html) but a [`org.gradle.api.plugins.osgi.OsgiManifest`](https://docs.gradle.org/4.10/javadoc/org/gradle/api/plugins/osgi/OsgiManifest.html).

This leads to the fact that we have to **cast** the `Manifest` to the `OsgiManifest`. Otherwise we can't access the properties like [`instructions`](https://docs.gradle.org/4.10/javadoc/org/gradle/api/plugins/osgi/OsgiManifest.html#instruction-java.lang.String-java.lang.String...-).

### Expected Behavior
The best thing is to change the behavior of the OSGIPlugin that you can change the `Manifest` not within the `jar` Task somehow but directly... Like
```
osgiManifest {
  // setup here
  putIntoJarTask()
}
```
(Just a proposal. I don't know what the best solution would be 🙃 )

### Current Behavior
The `Manifest` needs to be casted to the `OsgiManifest`:
```
tasks.withType<Jar> {
    manifest {
        (manifest as? OsgiManifest)?.apply {
             // setup
    }
}
```

### Context
See for more context this PR https://github.com/gradle/gradle/pull/6539

**Comment by big-guy** [comment]
Since we've deprecated the built-in osgi plugin in favor of the community one, we probably won't fix this. As an alternative that avoids the casting, you can also go through the convention:

```
osgi.osgiManifest {
   // configure it
}
```
