### ISSUE TITLE
Move gradle wrapper scripts to gradle directory

### ISSUE THREAD

**Issue by vpriscan** [gradle/gradle#6561]
I am proposing that you change the default location of Gradle Wrapper scripts (`gradlew` and `gradlew.bat`) generated by `gradle wrapper` task. Currently the default location is the working directory, which is usually the project root. Unfortunately that makes project root directory cluttered with gradle files.

Out of 8 files/folders in this example project root directory, 5 of them are Gradle specific:
![image](https://user-images.githubusercontent.com/26350152/44790824-83411e00-aba0-11e8-9437-1752c1c92ee8.png)
I have too often seen people having disdain towards Gradle exactly because of this, especially newcomers, it gives them the impression Gradle suffers from "configuration hell" or something.

Wouldn't it be better to put those wrapper scripts in the `gradle` directory instead?
Executing Gradle tasks using the wrapper would now look like 
eg. `gradle/gradlew clean` or eg.`gradle/w clean`, instead of `./gradlew clean` (assuming working dir is project root dir). 
In this example that would reduce the number of Gradle specific files in project root directory to 3.

**Comment by big-guy** [comment]
This is a nice idea, but I don't believe we're likely to do this. I'm closing this for now.

We're more likely to make it easier to install a "Gradle wrapper" globally that looks at the gradle-wrapper.properties and selects the right version of Gradle instead.  That could potentially get rid of the scripts entirely.

**Comment by wietlol** [comment]
Is there already a way to move the root directory gradle-related files to a different place?
Either by global or local settings/installations.
