### ISSUE TITLE
`Manifest.from(mergePath, closure)` is missing an Action<T> taking overload

### ISSUE THREAD

**Issue by jnizet** [gradle/gradle#6574]
`Manifest.from(mergePath, closure)` is missing an `Action<ManifestMergeSpec>` taking overload for type safety.

### Context
The lack of an overload forces the usage of `Closure` in a plugin written in Java or Kotlin ; or of `closureOf()` in a Kotlin DSL script or plugin.

**Comment by eskatos** [comment]
Closing as delivered in #6587
