### ISSUE TITLE
jogl-all and gluegen-rt doesn't run with gradle. 

### ISSUE THREAD

**Issue by chuidiang** [gradle/gradle#6594]
Hi:

I have the same issue https://issues.gradle.org/browse/GRADLE-2553

With dependencies like this

```
compile "org.jogamp.gluegen:gluegen-rt:2.1.5"
runtime "org.jogamp.gluegen:gluegen-rt:2.1.5:natives-android-armv6"
runtime "org.jogamp.gluegen:gluegen-rt:2.1.5:natives-linux-amd64"
...
```

gluegen-rt searchs for jars with native libraries (i.e gluegen-rt-2.1.5-natives-linux-amd64.jar ) in the same directory where gluegen-rt-2.1.5.jar is located, but gradle puts these files in the gradle cache in different directories. This makes impossible for an IDE to run the imported gradle project.

Same issue with jogl-all 

```
compile "org.jogamp.jogl:jogl-all:2.1.5"
runtime "org.jogamp.jogl:jogl-all:2.1.5:natives-android-armv6"
runtime "org.jogamp.jogl:jogl-all:2.1.5:natives-linux-amd64"
...
```

When a dependency has a "classifier" (like natives-linux-amd64), maybe gradle could place them into the same directory than the jar without the classifier.

Thanks.

**Comment by big-guy** [comment]
Sorry, we're not likely to make that sort of change.  It seems to me that gluegen-rt/jogl shouldn't rely on particular directory layouts to work and use the classpath instead.  It looks like gluegen might have a newer release that does that based on this commit: https://github.com/sgothel/gluegen/commit/f5c48efcf546ba4e08e197ccced6df83b57e1755#diff-b3a10f0077c20961d43b6c24675fb17e

I would look to see if those libraries/tools have newer versions available.

As a workaround, you could do something like the [application plugin](https://docs.gradle.org/current/userguide/application_plugin.html) and copy your application + dependencies into a particular layout and run from there.
