### ISSUE TITLE
Gradle does not compile source files generated in the last round of annotation processing

### ISSUE THREAD

**Issue by lukoerfer** [gradle/gradle#6595]
It may be possible that this issue was already discussed a long time ago, however I could not find enough information on this topic (especially regarding Gradle).

Annotation processing works in different rounds, because every generated source code might again contain annotations that need to be processed. Now there are different interpretations of what is allowed (and possible) during the last round (and what is not).

### Expected Behavior
**Strong (maybe wrong) statement**: When an annotation processor generates a source file in the last round of annotation processing (when `roundEnv.processingOver()` evaluates to `true`), the file should still be compiled, because ...

### Current Behavior
... the compiler (and even Gradle) does not fail or even warns me saying something different. It just says:

> warning: File for type 'package.to.File' created in the last round will not be subject to annotation processing.

This should be clear, because since the source file is created in the last round, there will be no more round to process possible annotations. But there is no warning (or error) about the source file not being compiled, the compilation will just fail when another file references the generated file (it does even print the error *before* the mentioned warning).

As a side note, there was [a discussion on the same topic](https://bugs.eclipse.org/bugs/show_bug.cgi?id=329156) regarding the Eclipse compiler and it seems like they decided to support compiling source files generated in the last round.

### Context
I'm currently working on an annotation processor that collects all types annotated with a specific annotation (similar like [ClassIndex](https://github.com/atteo/classindex)). Of course I want to process all classes, even those that might be generated during various rounds of other annotation processing.

There are other frameworks where this topic was discussed, e.g. [Toothpick](https://github.com/stephanenicolas/toothpick/issues/85), where they first changed their processor to just collect the annotation from the first round (see [issue](https://github.com/stephanenicolas/toothpick/issues/158)), but now encounter issues when using Toothpick with another annotation processor like Google AutoFactory (see [issue](https://github.com/stephanenicolas/toothpick/issues/187)).

I found a [similar issue for Hibernate](https://hibernate.atlassian.net/browse/METAGEN-45), where they even explicitly stated Gradle being (one part of) the problem:

> The problem also exists when using gradle.

### Steps to reproduce
For now, I only created this issue to get more insight on how Gradle wants to handle this topic. If you consider this a bug, I'll add a minimal example project to reproduce.

Just to make sure, I do not say this is a bug for sure. I just think that the behaviour of Gradle should be clearly defined and, if last round compilation should not be supported, Gradle and/or the compiler should state it clearly.

**Comment by oehme** [comment]
Have you tried your processor with plain javac? Gradle just uses the Java compiler API. It should behave no different from compiling with plain javac.

**Comment by big-guy** [comment]
@lukoerfer were you able to try your annotation processor out with plain javac like Stefan suggested above?  A sample project would be appreciated if you see a difference in behavior between plain javac and Gradle.

I'll close this until we hear back. Thanks!

**Comment by nbrugger-tgm** [comment]
This is a OpenJDK problem etc `javac` https://bugs.openjdk.java.net/browse/JDK-8256826
