### ISSUE TITLE
Function getDisplayName() of ComponentIdentifier class does not work as expected for snapshot artefacts stored in timestamps

### ISSUE THREAD

**Issue by efarhat** [gradle/gradle#6605]
It looks like the getDisplayName() function of ComponentIdentifier class does not works as expected if the object instance is a snapshot artefact stored in timestamps in a Maven repository.

Here is an extract of my build.gradle file:

```
project.dependencies {
    myConf "com.simu:myTool:1.0.0-SNAPSHOT"
}

project.configurations.getByName('myConf').resolvedConfiguration.resolvedArtifacts.each { artifact ->
    if (artifact.getName().contains('myTool'))
        println artifact.getId().getComponentIdentifier().getDisplayName()
}
```

Here is the maven-metadata.xml of 'com.simu:myTool:1.0.0-SNAPSHOT' :

```
<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>com.simu</groupId>
  <artifactId>myTool</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <versioning>
    <snapshot>
      <timestamp>20180710.150114</timestamp>
      <buildNumber>6</buildNumber>
    </snapshot>
    <lastUpdated>20180710150117</lastUpdated>
    <snapshotVersions>
      <snapshotVersion>
        <extension>jar</extension>
        <value>1.0.0-20180710.150114-6</value>
        <updated>20180710150114</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>pom</extension>
        <value>1.0.0-20180710.150114-6</value>
        <updated>20180710150114</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
</metadata>
```

What I get in the configuration phase:

```
> Configure project :
com.simu:myTool:1.0.0-SNAPSHOT:20180710.150114-6
```

Thus, the timestamp value is added to the returned value

What we should obtain is:
`com.simu:myTool:1.0.0-SNAPSHOT`

I am using Gradle 4.7

**Comment by ljacomet** [comment]
This has been like that for a long time and is by design.

What issue does that cause you?

**Comment by efarhat** [comment]
Hi ljacomet  and thank you for your answer.
I am using this function to add a dependency to a configuration of my project that is originally stored in my classpath configuration.

**Comment by ljacomet** [comment]
Then you definitely should not be using a method called `getDisplayName` for that, as the name implies this is a variant to be used in user facing output.

Depending on the code you are writing and where you do this addition, there might be a way without going back to parsing a `String` notation.

Given your answer, I am also closing this issue.
