### ISSUE TITLE
Avoid unnecessary resolution of version ranges when combined with fixed version constraints

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#6611]
When a resolution has multiple different dependencies on a module, Gradle attempts to find the best version that matches all of the version constraints from those dependencies. When one dependency contains a version range and another dependency/constraint specifies a particular version within this range, then Gradle will choose the fixed version as the "best" match.

In this case, Gradle should not need to resolve the version range at all. Gradle should detect that the fixed version lies within the range, and omit any resolution of the range.

This is particularly important for dependency locking, where a version constraint is used to lock to a particular version within a range. Avoiding the resolution of dynamic versions would improve performance in this case, particularly when `cacheDynamicVersionsFor 0, 'seconds'` is used.

### Expected Behavior

Gradle will not resolve the highest value in a version range, when this value will be replaced by a fixed version within the range.

### Current Behavior

Gradle resolves a version range to it's highest value, even when this value will not be used.

### Context

Avoiding the resolution of dynamic versions could have a significant impact on performance. This will be particularly evident when version ranges are combined with dependency locking.

See https://github.com/gradle/gradle/blob/ee0ba0c3880c50daa1dc0e480d28ce5f14910fc4/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/locking/LockingInteractionsIntegrationTest.groovy#L318-L352

**Comment by ljacomet** [comment]
Was resolved by #9252
