### ISSUE TITLE
Upgrade default tool version of PMD

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#6625]
Update `toolVersion` to latest available version which is compatible with Java 8: 6.7.0.

PMD 6.0 has deprecated the default rule set the plugin has been using: `java-basic`. It can still be used, but will print a big block of deprecation warnings such as:

```
> Task :pmdMain
Use Rule name category/java/errorprone.xml/AvoidBranchingStatementAsLastInLoop instead of the deprecated Rule name rulesets/java/basic.xml/AvoidBranchingStatementAsLastInLoop. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/AvoidDecimalLiteralsInBigDecimalConstructor instead of the deprecated Rule name rulesets/java/basic.xml/AvoidDecimalLiteralsInBigDecimalConstructor. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/AvoidMultipleUnaryOperators instead of the deprecated Rule name rulesets/java/basic.xml/AvoidMultipleUnaryOperators. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/AvoidUsingOctalValues instead of the deprecated Rule name rulesets/java/basic.xml/AvoidUsingOctalValues. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/BrokenNullCheck instead of the deprecated Rule name rulesets/java/basic.xml/BrokenNullCheck. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/CheckSkipResult instead of the deprecated Rule name rulesets/java/basic.xml/CheckSkipResult. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/ClassCastExceptionWithToArray instead of the deprecated Rule name rulesets/java/basic.xml/ClassCastExceptionWithToArray. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/DontUseFloatTypeForLoopIndices instead of the deprecated Rule name rulesets/java/basic.xml/DontUseFloatTypeForLoopIndices. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/JumbledIncrementer instead of the deprecated Rule name rulesets/java/basic.xml/JumbledIncrementer. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/MisplacedNullCheck instead of the deprecated Rule name rulesets/java/basic.xml/MisplacedNullCheck. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/OverrideBothEqualsAndHashcode instead of the deprecated Rule name rulesets/java/basic.xml/OverrideBothEqualsAndHashcode. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/ReturnFromFinallyBlock instead of the deprecated Rule name rulesets/java/basic.xml/ReturnFromFinallyBlock. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/errorprone.xml/UnconditionalIfStatement instead of the deprecated Rule name rulesets/java/basic.xml/UnconditionalIfStatement. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/multithreading.xml/AvoidThreadGroup instead of the deprecated Rule name rulesets/java/basic.xml/AvoidThreadGroup. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/multithreading.xml/DontCallThreadRun instead of the deprecated Rule name rulesets/java/basic.xml/DontCallThreadRun. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/multithreading.xml/DoubleCheckedLocking instead of the deprecated Rule name rulesets/java/basic.xml/DoubleCheckedLocking. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/bestpractices.xml/AvoidUsingHardCodedIP instead of the deprecated Rule name rulesets/java/basic.xml/AvoidUsingHardCodedIP. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/bestpractices.xml/CheckResultSet instead of the deprecated Rule name rulesets/java/basic.xml/CheckResultSet. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/codestyle.xml/ExtendsObject instead of the deprecated Rule name rulesets/java/basic.xml/ExtendsObject. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/codestyle.xml/ForLoopShouldBeWhileLoop instead of the deprecated Rule name rulesets/java/basic.xml/ForLoopShouldBeWhileLoop. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/performance.xml/BigIntegerInstantiation instead of the deprecated Rule name rulesets/java/basic.xml/BigIntegerInstantiation. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/performance.xml/BooleanInstantiation instead of the deprecated Rule name rulesets/java/basic.xml/BooleanInstantiation. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/design.xml/CollapsibleIfStatements instead of the deprecated Rule name rulesets/java/basic.xml/CollapsibleIfStatements. PMD 7.0.0 will remove support for this deprecated Rule name usage.
Use Rule name category/java/design.xml/SimplifiedTernary instead of the deprecated Rule name rulesets/java/basic.xml/SimplifiedTernary. PMD 7.0.0 will remove support for this deprecated Rule name usage.
```

Thus, in order to avoid printing these warnings when a user uses the plugin's default configuration, we have to pick one of the [newly introduced categories](https://pmd.github.io/pmd-6.0.0/pmd_rules_java.html):

- Best Practices
- Code Style
- Design
- Documentation
- Error Prone
- Multithreading
- Performance

There is no category that contains all rules from `java-basic`. 13 of the 24 rules are contained in "Error Prone", though.

**Comment by marcphilipp** [comment]
@adangel @oowekyala @jsotuyod As PMD maintainers, do you have any advice for us here?

**Comment by jsotuyod** [comment]
@marcphilipp that's right. The best practice is for developers to write their own rulesets and [tailor which rules are right for them.](https://pmd.github.io/pmd-6.7.0/pmd_userdocs_best_practices.html#choose-the-rules-that-are-right-for-you)

We are [in the process of defining some *quickstart* rulesets for different kind of projects](https://github.com/pmd/pmd/pull/1260), that developers can use as starting points for their own rulesets, but they are still unshipped.

In the meantime, if you want something that works out of the box you have 2 alternatives:
1. bundle a custom ruleset with Gradle (which may include the rules from the old `java-basic` ruleset if you want) and reference that by default
2. default to a category that is broad enough / basic enough to not be polemic.. possible [`bestpractrices`](https://pmd.github.io/pmd-6.7.0/pmd_rules_java.html#best-practices) or [`errorprone`](https://pmd.github.io/pmd-6.7.0/pmd_rules_java_errorprone.html) are the best fit.

If you can, please contact me by email (my email is public) so we can discuss this in detail / better collaborate to get the Gradle integration up to speed with all the PMD features not currently supported:

1. CPD
2. Support for Java 9, 10 and 11
3. Support for other languages Gradle supports. ie: PMD can also apply rules to xml files, and CPD is supported not only forJava, but among languages Gradle supports it can also work on:
  - Groovy
  - Scala
  - C
  - C++
  - Objective-C
4. Incremental analysis

**Comment by marcphilipp** [comment]
@jsotuyod Thanks for the feedback!

The quickstart rule sets sound exactly like what we would need. Any idea when those will be shipped?

I don't think we should be bundling our own ruleset, because it needs to work across all supported versions of PMD (4.x - 6.x). The approach I'd take is to use a category by default (e.g. `errorprone`), and fall back to `java-basic` for PMD 5.x and `basic` for 4.x.

Regarding adding missing features to the Gradle integration, I'm afraid we don't have a lot of time to work on it at the moment. Would you or someone else from the PMD team/community be willing to take on that work? If so, there are two possible ways: (1) contribute to Gradle by submitting PRs, (2) fork/create a new community plugin and eventually deprecate the plugin in Gradle core.

> Support for Java 9, 10 and 11

The update to PMD 6.7.0 should be sufficient for that, right?

**Comment by jsotuyod** [comment]
@marcphilipp ok, that sounds good.

Yes, we are willing to contribute to Gradle, as we have done in the past. However, the last time I tried to bump PMD and support the analysis cache, the PRs got stalled for months and then reverted before release. So I'd really appreciate being able to talk to someone from Gradle and coordinate the work to avoid wasting efforts.

As for Java 9, 10 and 11... Yes, PMD 6.7.0 supports those, but you will also need to update Gradle's [`TargetJdk`](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/TargetJdk.java#L24-L30)

**Comment by marcphilipp** [comment]
The `TargetJdk` is currently only used for PMD < 5.x:

https://github.com/gradle/gradle/blob/2622baaf86d959685f94c947302b5fb1b26f4ac5/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy#L46-L49

Do we have to specify `language`/`version` for PMD 6.x to work with Java 9/10/11 or will it detect that on its own?

**Comment by JLLeitschuh** [comment]
It would be totally awesome if there were CPD support built into Gradle. I do want to make sure it supports language plugins. For example, for Kotlin. I'm planning on publishing this plugin when I get a chance: https://github.com/JLLeitschuh/pmd-kotlin

**Comment by jsotuyod** [comment]
PMD will always default to the latest supported Java version, which may not be actually the version used by the Gradle project. This may result in having rules enabled / disabled which shouldn't be for the project.

That `targetJdk` attribute was removed back in PMD 5, as PMD moved from a Java-only tool to a multilanguage tool. The way to do that properly is using a child node in the task:

```xml
<sourceLanguage name="java" version="1.8"/>
```

Supported versions are:

```java
        addVersion("1.3", new JavaLanguageHandler(3), false);
        addVersion("1.4", new JavaLanguageHandler(4), false);
        addVersion("1.5", new JavaLanguageHandler(5), false);
        addVersion("1.6", new JavaLanguageHandler(6), false);
        addVersion("1.7", new JavaLanguageHandler(7), false);
        addVersion("1.8", new JavaLanguageHandler(8), false);
        addVersion("9", new JavaLanguageHandler(9), false);
        addVersion("10", new JavaLanguageHandler(10), false);
        addVersion("11", new JavaLanguageHandler(11), true);
```

https://github.com/pmd/pmd/blob/e3018c3892bb34805efff9d9a2e4c6acde682887/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java#L20-L28

**Comment by sudharmohan** [comment]
I have a initialized a default value for the variable to avoid NPE and overriding the value on certain if condition.  But pmd check throws a warning " 'DD'-anomaly for variable 'x' (lines '16'-'18') ". 

Ex:  
```
List<String> x = new ArrayList<>();
if(  condition ) {
  x = <some value retrieved from different object>;
}
```

This is more similar to original problem. 

I can remove the "DD anomaly" warning by following code:

```
List<String> x;
if(condition) {
  x = <some value from object>;
} else {
 x = new ArrayList<>();
}
```
I simply initialized the default value ahead instead of defining in else part.  

Should I open different ticket or can it be reopened?

Most of the DataFlow anomaly are reporting false warning.

**Comment by JLLeitschuh** [comment]
@sudharmohan This isn't the place to report issues/questions about PMD. Please refer to the README for the PMD project to ask question:

https://github.com/pmd/pmd
