### ISSUE TITLE
Checkstyle plugin with Task Configuration Avoidance problem

### ISSUE THREAD

**Issue by sdavids** [gradle/gradle#6629]
I am trying to use [Task Configuration Avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) with the _Checkstyle_ plugin.

Original _build.gradle_:

```
plugins {
  id 'java'
  id 'checkstyle'
}

repositories {
  jcenter()
}

dependencies {
  checkstyle 'com.puppycrawl.tools:checkstyle:8.12'
}

checkstyle {
  configDir = project.file('gradle/conf/')
}
```

Try 1:

```
tasks.named('checkstyle').configure {
  configDir = project.file('gradle/conf/')
}
```

Error:

```
> Task with name 'checkstyle' not found in root project 'checkstyle-test'.
```

Try 2:

```
tasks.withType(Checkstyle).configureEach {
  configDir = project.file('gradle/conf/')
}
```

Error: 
```
> Cannot cast object '/Users/dev/checkstyle-test/gradle/conf' with class 'java.io.File' to class 'org.gradle.api.provider.Provider'
```

I am not sure if it is a bug or if I have to configure it differently ...

**Comment by lacasseio** [comment]
I can understand the confusion and we hope in the future to make everything more discoverable.

To start with, it's the extension that is named `checkstyle`, so you will not find any tasks with that name. The tasks name are [derived on the source set name](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/AbstractCodeQualityPlugin.java#L172). The [`Checkstyle#setConfigDir` take a `Provider<File>`](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java#L268-L271) and `project.file` returns a `File`.

You can either change to use [`Checkstyle#setConfigFile` using `configFile`](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java#L81-L83) if that was the original intent or use [`ProjectLayout` methods](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/file/ProjectLayout.java) to get a `Provider<File>` to pass to `Checkstyle#setConfigDir`.

I hope this answer your question. The provider API is still under review in term of improvement before making it stable, if you have a suggestion for improvement, please search for issue on this repositories or open a new one. Keep in mind this repository is for feature and bug request, all questions should be directed to the [user forum](https://discuss.gradle.org/).

**Comment by sdavids** [comment]
A working version using the _ProjectLayout_ methods looks just awful :

```
tasks.withType(Checkstyle).configureEach {
  configFile = project.file('gradle/conf/checkstyle.xml')
  configDir = project.layout.directoryProperty(project.provider({ project.layout.projectDirectory }))
                .dir('gradle/conf/')
                .map({ it.getAsFile() } as Transformer<Directory, File>)
}
```

This one works too:

```
tasks.withType(Checkstyle).configureEach {
  configFile = project.file('gradle/conf/checkstyle.xml')
  configDir = project.provider({ project.file('gradle/conf/') })
}
```

The _gradle/conf_ directory contains a _checkstyle-suppressions.xml_ and _checkstyle.xml_ contains the following snippet:

```
  <module name="SuppressionFilter">
    <property name="file" value="${config_loc}/checkstyle-suppressions.xml"/>
  </module>
```
