### ISSUE TITLE
Gradle Build for Application Backend Failing. Cannot resolve all artifacts for Config "Classpath". Anyone have a fix for this ? 

### ISSUE THREAD

**Issue by Barry007H** [gradle/gradle#6630]
I have a application backend that uses gradle, however i have recieved the same error everytime i attempt to start up the backend, which is that the classpath config cannot resolve all the artifacts.

The Context is that i have a spring boot application acting as the backend for a front end application, the backend when attempting to start up will not resolve classpath and fails everytime. I have provided the error log below.

----- ERROR LOG -----

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'bfapps-shopfloor-1man-multiple-svc'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download httpclient.jar (org.apache.httpcomponents:httpclient:4.2.5)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download commons-lang.jar (commons-lang:commons-lang:2.4)
      > Could not get resource 'https://jcenter.bintray.com/commons-lang/commons-lang/2.4/commons-lang-2.4.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/commons-lang/commons-lang/2.4/commons-lang-2.4.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download sonar-scanner-api.jar (org.sonarsource.scanner.api:sonar-scanner-api:2.9.0.887)
      > Could not get resource 'https://jcenter.bintray.com/org/sonarsource/scanner/api/sonar-scanner-api/2.9.0.887/sonar-scanner-api-2.9.0.887.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/sonarsource/scanner/api/sonar-scanner-api/2.9.0.887/sonar-scanner-api-2.9.0.887.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download xstream.jar (com.thoughtworks.xstream:xstream:1.3.1)
      > Could not get resource 'https://jcenter.bintray.com/com/thoughtworks/xstream/xstream/1.3.1/xstream-1.3.1.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/com/thoughtworks/xstream/xstream/1.3.1/xstream-1.3.1.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download commons-codec.jar (commons-codec:commons-codec:1.8)
      > Could not get resource 'https://jcenter.bintray.com/commons-codec/commons-codec/1.8/commons-codec-1.8.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/commons-codec/commons-codec/1.8/commons-codec-1.8.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download jackson-mapper-asl.jar (org.codehaus.jackson:jackson-mapper-asl:1.9.12)
      > Could not get resource 'https://jcenter.bintray.com/org/codehaus/jackson/jackson-mapper-asl/1.9.12/jackson-mapper-asl-1.9.12.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/codehaus/jackson/jackson-mapper-asl/1.9.12/jackson-mapper-asl-1.9.12.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download jackson-core-asl.jar (org.codehaus.jackson:jackson-core-asl:1.9.12)
      > Could not get resource 'https://jcenter.bintray.com/org/codehaus/jackson/jackson-core-asl/1.9.12/jackson-core-asl-1.9.12.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/codehaus/jackson/jackson-core-asl/1.9.12/jackson-core-asl-1.9.12.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download httpcore.jar (org.apache.httpcomponents:httpcore:4.2.4)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar'.
         > Could not HEAD 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Environment:
Spring Tool Suite for development 
Command line for local hosting

can anyone help me with this as i cannot find a solution

**Comment by marcphilipp** [comment]
Looks like an issue with your JDK's trust store. Do the suggestions in [this SO post](https://stackoverflow.com/questions/9210514/unable-to-find-valid-certification-path-to-requested-target-error-even-after-c) help?

**Comment by ljacomet** [comment]
This could also be https://blog.gradle.org/unable-to-download-maven-central-bintray but in any case, pretty unlikely to be a bug.
