### ISSUE TITLE
./gradlew build produces nonfunctional build/classes/java/main/main/java structure

### ISSUE THREAD

**Issue by rhmoult** [gradle/gradle#6651]
After running ./gradlew build, I cannot run java -jar build/libs/*jar due to inability to find the main class.  Further inspection suggests this is because of the strange directory structure produced like build/classes/java/main/main/java/com/example/greet 
### Expected Behavior

I expected ./gradlew build to produce a structure like build/classes/main/com/example/greet

### Current Behavior

Instead of ./gradlew build producing build/classes/java/main/main/java/com/example/greet, I expected it to produce build/classes/main/com/example/greet

### Context

This issue has affected me such that I cannot run the jar provided in build/libs because the main class cannot be found.
### Steps to Reproduce (for bugs)

git clone https://github.com/rhmoult/gradlebug.git
cd gradlebug
./gradlew clean
./gradlew build
java -jar build/libs/*jar
ls -R build/classes

### Your Environment

 * Build scan URL: 
https://gradle.com/s/ghpekm7uuzx2u

**Comment by jnizet** [comment]
Well, your source files have

    package main.java.com.example.greet

instead of

    package com.example.greet;

**Comment by marcphilipp** [comment]
Indeed, the package declaration looks wrong.
