### ISSUE TITLE
double deprecation message when using publishing plugin

### ISSUE THREAD

**Issue by jnizet** [gradle/gradle#6653]
### Expected Behavior
When using the publishing plugin without enabling the feature "STABLE_PUBLISHING", I should get a correct deprecation message.

### Current Behavior
I get a message with two deprecation warnings:

> [...] is now deprecated. has been deprecated.

This is caused by `org.gradle.util.SingleMessageLogger#nagUserWithDeprecatedBuildInvocationFeature()` appending " has been deprecated." to the summary, which itself already contains the deprecation warning.

### Context
Not a big issue of course. I noticed it while translating a sample to Kotlin. 

### Steps to Reproduce (for bugs)
Use the publishing pugin without enabling the STABLE_PUBLISHING feature

I would be happy to file a PR, but I'm not sure if the correct fix would be to print the prefix as is, without appending "has been deprecated.", or if the specific summary used in PublishingPlugin.java should be reworded (i.e. if its " is now deprecated." ending should be removed)

**Comment by marcphilipp** [comment]
Good catch! Looks like this was broken in a1006da3fa8a8457b4d4011e9581cd506662c8de. 

I think removing the `" is now deprecated."` ending should be fine.

**Comment by jnizet** [comment]
I'll file a PR tonight (French time)

**Comment by marcphilipp** [comment]
Please file it against the `release` branch so we can include the fix in 4.10.1.
