### ISSUE TITLE
Access to another modules test classes with idea-Plugin in multi-module build

### ISSUE THREAD

**Issue by acetous** [gradle/gradle#6674]
We generate our IntellJ project configuration using the idea Plugin in our multi-module build. The example for the following description is provided at https://github.com/acetous/gradle-idea-plugin-multi-module-example.

We're having two modules *api* and *shared* where *api* has a compile dependency on *shared*.

### Expected Behavior
Using IntelliJ testclasses in *api* can see the production classes from *shared* but have no access to the test classes in *shared*.

### Current Behavior
Using IntelliJ testclasses in *api* can see the production **and test classes** from *shared*.

### Context
The example provided is very generic. `PersonTest` imports `HelperTest` which should not be possible. In our large project with ~150 modules and a lot of dependencies in between the modules there are always situations in which someone uses a class from the test sources of another dependent project. IntelliJ can compile the project and run the tests. Gradle cannot compile the project because the dependency between those projects does not include classes from test sources.
Apart from that, when trying to write tests with Spring, IntelliJ suddenly finds other configuration classes and imports them thus failing the tests.

### Steps to Reproduce (for bugs)
* Clone https://github.com/acetous/gradle-idea-plugin-multi-module-example
* Run `gradlew check`
* The build fails with `PersonTest.java:8: error: cannot find symbol HelperTest` ◀️ That is correct!
* Run `gradlew idea`
* Open the project in IntelliJ
* Press *Build project* ◀️ This should fail but doesn't.
* Run `PersonTest` in IntelliJ. The test passes. ◀️ The test should fail.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/gf5tm3lol6tss
* IntelliJ IDEA 2018.2 (Ultimate Edition) Build #IU-182.3684.101, built on July 24, 2018

**Comment by oehme** [comment]
Please use Idea's own importer instead of running `gradle idea`. Select the "Module per SourceSet" option. This will give you the separation you want.
