### ISSUE TITLE
Difference between console mode 'plain' and 'verbose'

### ISSUE THREAD

**Issue by nerro** [gradle/gradle#6677]
Before the new console modes (rich, plain and verbose) were introduced, the standard mode was `plain` (or most similar). Now the difference between `plain` and `verbose` is coloring of statuses (up-to-date, no-source etc.)

![gradle_console-plain](https://user-images.githubusercontent.com/5961772/45224042-44564b00-b2b9-11e8-86a2-8c45c3c57278.png)
![gradle_console-verbose](https://user-images.githubusercontent.com/5961772/45224043-44564b00-b2b9-11e8-9341-c051bd3c65d1.png)

### Proposal
Do you think that removing `> Task ` prefix for plain mode is a good idea? If so, I would sent a PR.

### Your Environment
```
------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Windows 7 6.1 amd64
```

**Comment by oehme** [comment]
The difference is not just coloring. The verbose console has the interactive work-in-progress display. The plain console doesn't do that, to be compatible with more environments.

I don't think we should introduce artificial differences between them like removing `> Task`.

**Comment by nerro** [comment]
thanks for explanation, in my opinion just a lot of noise and repetition of the same prefix`> Task `
=> **closed**.

**Comment by oehme** [comment]
Tasks are not the only thing that can get run, just the most common.
