### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6681]
I found a few broken links:

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.tasks.bundling.Tar.html
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.tasks.bundling.Zip.html

They are linked from this location:
https://docs.gradle.org/current/userguide/application_plugin.html#sec:application_tasks

@eriwen

**Comment by eriwen** [comment]
Fixed those and a couple more with https://github.com/gradle/gradle/commit/174707adf876fe06c1c394785ae4e26aa792f7ee — thanks @JLLeitschuh!
