### ISSUE TITLE
Release "Remove deprecated Class.newInstance()" fix in the 4.10.1 milestone

### ISSUE THREAD

**Issue by lamagicsword** [gradle/gradle#6683]
Currently, I am trying to build the Gradle source project using Java 9. However, certain plugins are still using the deprecated Class.newInstance() from Java 8. This will cause the build to fail. Currently, this issue was fixed by commit fad5133. However, it is not included latest 4.10.1 milestone. I wish to add this fix in the 4.10.1 release in order to resolve this issue for developers.

**Comment by oehme** [comment]
If you want to build 4.10 from source, use Java 8.

**Comment by lamagicsword** [comment]
I have tried to build 4.10.1 using Java 8. However, it will cause some plugins to fail as this issue suggested https://github.com/gradle/gradle/issues/6393 and the solution is now Gradle requires JDK 9 or 10 to build. I wish to know if there is a work around for these two problems. Thank you!

**Comment by wolfs** [comment]
The `release` branch now works when building with Java 9. That will be the base for 4.10.1.
You can also run the build on Java 8 and set the `java9Home` system property or project property to the path of a JDK 9 home directory.

We removed all that complexity from the `master` branch.

**Comment by TellH** [comment]
> The `release` branch now works when building with Java 9. That will be the base for 4.10.1.
> You can also run the build on Java 8 and set the `java9Home` system property or project property to the path of a JDK 9 home directory.
> 
> We removed all that complexity from the `master` branch.

But JDK 9 is not available to download in Oracle official website now.  So is there any other way to build 4.10.1 using Java 8?  Please help me out of this dilemma. Any useful advice would be appreciated.

**Comment by blindpirate** [comment]
@TellH You can set `java9Home` to a JDK11 java home. `java9Home` is just a name for "JDK 9+".
