### ISSUE TITLE
Allow third party developers to take advantage of the Gradle Build Cache

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6690]
This issue stems from these two comments:

#6253
https://github.com/gradle/kotlin-dsl/pull/1095/files#r216131039

As an open source developer, I'd love to be able to take advantage of the awesome performance benefits of the Gradle build cache for projects like Gradle & the Gradle Kotlin DSL but in a safe, read only, mode.

This would allow external contributors to gain the benefits of the Gradle build cache while working on projects like Gradle.

### Context

Running the `./gradlew check` task against this repository can take an incredibly long time.
It would be awesome if I could take advantage of the Build cache to speed up this process as a third party developer.

### Proposed Solution

1. Allow support for a read only user of the Gradle Build Cache.
2. For the Gradle and Gradle Kotlin DSL project, make this user the default if no override is specified.
3. Profit(?)

**Comment by wolfs** [comment]
You can do that now by using https://eu-build-cache.gradle.org/cache/ as cache node. Actually, you shouldn't need to configure anything on your machine, the `gradle/gradle` build should use this cache node out of the box.
