### ISSUE TITLE
TestSuiteExecutionException: Could not execute test class 'MyApp$delayedInit$body'.

### ISSUE THREAD

**Issue by maxhillaert** [gradle/gradle#6693]
Objects extending scala.App that happen to hang around in a test source set seem to get discovered when doing "gradle test"  and then delayedInit of scala.App causes the exception.

```

org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not execute test class 'MyApp$delayedInit$body'.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

...

Caused by: java.lang.IncompatibleClassChangeError: MyApp and MyApp$delayedInit$body disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at java.lang.Class.getEnclosingClass(Class.java:1277)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.isInnerClass(JUnitPlatformTestClassProcessor.java:97)
```

### Expected Behavior
scala.App objects should be discovered and excluded

### Current Behavior
They are discovered.

### Context
Have to work around it by rewriting those objects to not use scala.App.    Behaviour is surprising.

### Steps to Reproduce (for bugs)
Just add following class to your test source set next to a unit test fixture and do gradle test.
```
object MyApp extends App {

  println("Initialize")
}

```

### Your Environment
gradle 4.7
junit 5.2

**Comment by marcphilipp** [comment]
As a workaround, have you tried using [test filtering](https://docs.gradle.org/current/userguide/java_testing.html#test_filtering)?

**Comment by maxhillaert** [comment]
I’ve worked around it by going through all scala.App extensions in the test
source sets , removing the use of the trait and implementing def main(args)
manually.
I could do filtering I suppose but either way require manual updating when
someone on the team adds a scala.app not knowing this issue exists.

I think gradle should probably not try and drill into objects that extend
Scala.App.

**Comment by maxhillaert** [comment]
By the way, this issue didn’t exist before I upgraded the codebase using
junit 5 native support in gradle. Works fine with junit 4.2.

**Comment by alexbezhan** [comment]
I got this issue on Gradle Kotlin project. I've created a minimal project that reproduces this issue https://github.com/alexbezhan/kotlin-junitplatform-incompatible-inner-class-error

**Comment by alexbezhan** [comment]
@marcphilipp Hi, may I ask you to reopen this issue please, since now we have a reproducible code

**Comment by marcphilipp** [comment]
@alexbezhan I would have but it looks like you were faster! 🙂

**Comment by osama-raddad** [comment]
I am straggling  with this issue for the last two days do you have any work around at-least?
