### ISSUE TITLE
ApplicationPluginConvention should support environment variables in applicationDefaultJvmArgs

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6702]
The `ApplicationPluginConvention::applicationDefaultJvmArgs` variable doesn't support environment variables being passed.

This behaviour, according to @multi-io the author of the feature is completely intentional as he describes in this SO response:
https://stackoverflow.com/a/29464373/3708426

His recommended workaround is to do something like this:
```groovy
startScripts {
    doLast {
        unixScript.text = unixScript.text.replace('\\$MY_VAR', '$MY_VAR') 
        windowsScript.text = windowsScript.text.replace('\\$MY_VAR', '%MY_VAR%')
    }
}
```

However, there is no way to do this in a strongly typed language like kotlin.

Instead of a hacky solution, it would be nice if there was a more conventional solution for supporting having environment variables be supported in 

### Context

We were trying to achieve something like this without success.
```kotlin
application {
    mainClassName = "a.random.name.Main"
    applicationDefaultJvmArgs = listOf("-XX:HeapDumpPath=${'$'}{HEAP_DUMP_LOCATION:-/var/debug/application}")
}
```

Doing the above results in something like being produced:
```bash
# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_TESTING_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-XX:HeapDumpPath=\${HEAP_DUMP_LOCATION:-/var/debug/application}"'
```

### User Story

As a user of the application plugin, I'd like an API that allows me to pass environment variables in my `applicationDefaultJvmArgs` (or equivalent new API) in a way that  is platform independent.

### Your Environment
```
------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by JLLeitschuh** [comment]
Ah, fair enough.

Would it be good to document in the documentation for the Application plugin that this is the suggested way of getting around this problem?

Also, out of curiosity, won't modifying the `unixScript` and `windowsScript` in a `doLast` break the cacheability of the task?

**Comment by eskatos** [comment]
More documentation sounds good.

Depends on what are the inputs to what you use to write to those files.
Outputs are snapshotted after task execution, so after `doLast` actions.

**Comment by AndrewTasso** [comment]
I also wanted to toss another user scenario into the mix that increases the scope of the issue a bit. All of the solutions have been focused on the `startScripts` task. However, All `JavaExec` tasks that are setup with the `Application` plugin (e.g. `run`) are also impacted by this. 

So, in order for `run` to pull from the environment at runtime, the `systemProperties` for that `ExecTask` need to be explicitly set in addition to modifying the start scripts.

Here's how we handle ensuring that our Oracle JDBC connector can find our TNS Admin folder (via the `$TNS_ADMIN` env variable) using both the `run` task and/or via the generated start scripts.

```groovy
//Use a token (that doesn't contain characters that needs to be escape) to be replaced with system specific env format
applicationDefaultJvmArgs = ["-Doracle.net.tns_admin=@TNS_ADMIN@"]

run.systemProperties.put("oracle.net.tns_admin", System.getenv("TNS_ADMIN"))

//Ensure that the proper system environment variable format is used
startScripts {
	doLast {
		unixScript.text = unixScript.text.replace('@TNS_ADMIN@', '$TNS_ADMIN')
		windowsScript.text = windowsScript.text.replace('@TNS_ADMIN@', '%TNS_ADMIN%')
	}
}
```

Supporting the inclusion (and runtime expansion) of an environment variable via  `applicationDefaultJvmArgs` would aid in ensuring the same configuration is used for both the `ExecTasks` and generate start scripts.

**Comment by carlosalberto** [comment]
IMHO adding a `startScripts` sounds like a quick hack, but it doesn't really scale well (I can imagine a few scenarios where things would easily break).
