### ISSUE TITLE
Add --group option to filter tasks

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#6723]
Proposed API: `./gradlew tasks --group publishing`

**Comment by jlstrater** [comment]
@jmfayard would this feature help with your custom group filter?

**Comment by jlstrater** [comment]
@SUPERCILEX This seems like it would be helpful for several people I've chatted with and it could be implemented pretty easily by using the same pattern as the `-all` flag. Would you be interested in submitting a PR for this?

**Comment by jmfayard** [comment]
@jbaranski Yes!

Let me write down my use case for reference.

On Android, we have sometimes hundreds of Gradle tasks. The bulk of them is technical tasks but a dozen or so are very important tasks that my co-workers need to know about. I want those VIP tasks to be easy to discover, and also I want an easy way to update the README. 

Something like `$ ./gradlew tasks --group important` would solve both of those problems. 

My co-workers could use it interactively and I could copy-paste its output in the README. 

It woud be handy to add a bit of documentation on how to modify the group of the tasks I care about. In pseudo-code, something like this:

```
// build.gradle
for (task in listOf(":clean", ":check", ":app:somethingImportant")) {
     tasks.named(task).group = "important"
}
```

**Comment by SUPERCILEX** [comment]
@jlstrater yeah, sounds like fun. I'll see what I can do over the weekend.

**Comment by SUPERCILEX** [comment]
No, I haven't had the time to poke at it unfortunately. 😢

**Comment by SUPERCILEX** [comment]
@jlstrater Had some time to get this done! #7788
