### ISSUE TITLE
pluginUnderTestMetadata.pluginClasspath can no longer be customized

### ISSUE THREAD

**Issue by edeandrea** [gradle/gradle#6730]
Prior to Gradle 4.10 I was doing this to customize the plugin classpath when running our integration tests. Essentially we don't want the integration tests reading the compiled classes. We want them to use the actual artifact produced by the build (i.e. output from `jar` task).

```groovy
pluginUnderTestMetadata {
  // This tells the integration tests to use the actual artifact jar file rather than the classes on the filesystem
  pluginClasspath = files(jar.archivePath) + pluginUnderTestMetadata.pluginClasspath - files(gradlePlugin.pluginSourceSet.output.classesDirs, gradlePlugin.pluginSourceSet.output.resourcesDir)
}
```

### Expected Behavior
Prior to Gradle 4.10 this worked as expected

### Current Behavior
With Gradle 4.10 this is now broken because the `setPluginClasspath` method on `org.gradle.plugin.devel.tasks.PluginUnderTestMetadata` has been removed.

### Context
We've lost the ability to configure the plugin classpath when authoring Gradle plugins.

Is there a workaround for this?

**Comment by ghale** [comment]
@edeandrea The setter was removed, but `pluginClasspath` is an instance of `ConfigurableFileCollection`.  Does the following work?

```
pluginUnderTestMetadata {
  pluginClasspath.from = files(jar.archivePath) + pluginUnderTestMetadata.pluginClasspath - files(gradlePlugin.pluginSourceSet.output.classesDirs, gradlePlugin.pluginSourceSet.output.resourcesDir)
}
```

**Comment by shomeo** [comment]
> 
> ...
>  Does the following work?
> 
> ```
> pluginUnderTestMetadata {
>   pluginClasspath.from = files(jar.archivePath) + pluginUnderTestMetadata.pluginClasspath - files(gradlePlugin.pluginSourceSet.output.classesDirs, gradlePlugin.pluginSourceSet.output.resourcesDir)
> }
> ```

@ghale Yes it does work, thank you. While navigating my org's Gradle 2.5 -> 6+ upgrade, I ran into this exact issue when finalizing the milestone release of our custom plugins on Gradle 4.10.3, and your comment unblocked me.
