### ISSUE TITLE
Collect & log thread dump of the timed-out task/process

### ISSUE THREAD

**Issue by sambsnyd** [gradle/gradle#6739]
Followup to #1096 / #6643 which first implements a timing out hanging or otherwise errant long running tasks.

### Desired Behavior
When a task is timed out it would be desirable to collect stacktraces/thread dumps from the timed-out task and any workers or sub-processes it spawned.
Ideally, there would be a best-effort basis to collect the *relevant* stack traces, not just the one from the thread the hanging task was orchestrated from. A hanging JavaExec, worker API, Test task worker should have the relevant thread state captured.

### Context
Preventing the very frustrating  failure mode of an indefinite hang in CI and on local developer machines is highly desirable. But if the timeout mechanism itself complicates or impedes root-cause analysis it comes at a steep cost.

In practice, most of the hangs we've experienced have been related to test execution. A minority of hangs have been from other programs called via JavaExec. I recall no hangs in Gradle itself or any Gradle plugins we have used. 

### Your Environment
(mostly) Java multi-project build. Several forms of code generation. Light but increasing usage of composite build. Several different test frameworks, mocking frameworks, and a homegrown bytecode transformation or two.

**Comment by marcphilipp** [comment]
@oehme Can we postpone this one to 5.2?

**Comment by ldaley** [comment]
We actually did this for 6.8: https://github.com/gradle/gradle/issues/14960

It doesn't trace into forked processes, only what's going on in the build VM.

**Comment by tylerbenson** [comment]
@ldaley that is certainly an improvement, but I don't think it is capturing a thread dump as suggested in this issue, which I think is a very useful indicator of why a task might be stuck. I suggest you consider reopening this issue.

**Comment by ldaley** [comment]
It reports a stack trace of the thread that is effectively preventing the task from stopping. I'm not convinced that showing the state of all threads would be an improvement and it's unlikely that we will add that unless someone makes a good case for it.

**Comment by tylerbenson** [comment]
ah, I see... I missed that it prints the stacktrace.  Thanks for doing this.
