### ISSUE TITLE
Option to disable filtering in Copy type tasks

### ISSUE THREAD

**Issue by Frontrider** [gradle/gradle#6744]
The copy task (and everything based on it) modifies the files when used. (most relevant is the replacement of the line endings). It can corrupt some of out files, rendering them to be useless. An option to make gradle copy as-is would be useful.

Workarounds accepted, (antbuilder is our current workaround) but having an option to NOT to do that would be better.

### Expected Behavior
I expected the files to copy as is.

### Current Behavior
The file is edited, sometimes becomes corrupted

### Context
We're migration an old program to gradle, and some parts require the zipping of a single class file, but this class file becomes corrupted when we do this. (old framework, this change will bring us one step closer to not to need to do this)
We would also use it to package shell scripts, that are also becoming corrupted.

### Steps to Reproduce (for bugs)
Add shell scripts or class files to the "from" tag of a zip, or a copy task.

### Your Environment
Gradle 4.9
OS: Windows, Linux.

**Comment by jnizet** [comment]
You should provide a reproduction test case. If you don't activate filtering somehow, files are copied as is. So, without a concrete reproduction test case, it's hard to figure out why you get the behavior you describe.

Note that all jar files produced by gradle for basically every Java build are produced by the Jar task which extends the Zip task. If it corrupted every class file in the jar, that woul be a serious problem. So something is most probaby wrong on your side.

**Comment by Frontrider** [comment]
Thank you, we can start going from there.
