### ISSUE TITLE
Launching Gradle repo integTest tests in IntelliJ runs wrong task

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6753]
Example: Attempt to launch the `org.gradle.api.SettingsDslIntegrationSpec` test in IntelliJ.

### Expected Behavior

IntelliJ will attempt to launch the task `:core:cleanTest :core:integTest` with the arguments `--tests org.gradle.api.SettingsDslIntegrationSpec`.

### Current Behavior

IntelliJ will attempt to launch the task `:core:cleanTest :core:test` with the arguments `--tests org.gradle.api.SettingsDslIntegrationSpec`.

This fails without being able to find any tests because the `SettingsDslIntegrationSpec` doesn't exist under the `test` source set.

### Context

You have to know to go change your Gradle launch arguments for the test to launch the `:integTest` task instead of the `:test` task.

Gradle/IntelliJ should automatically figure out what task to try to launch the test with.

### Your Environment

The current status of the Gradle `master` branch.

**Comment by wolfs** [comment]
@JLLeitschuh You are hitting https://youtrack.jetbrains.com/issue/IDEA-169795. It should work when not delegating test execution/building to Gradle.

Note that we just made it possible that the projects works when imported into Intellij, and it only works with 2018.3 EAP. The current way to work with the `gradle/gradle` project is to run the `idea` task and then open the generated `.ipr` file from Intellij as described in https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#intellij.

Closing this now as there is nothing to do from our side to fix it.
