### ISSUE TITLE
Inherited configuration exclusions are not published to the POM

### ISSUE THREAD

**Issue by rocketraman** [gradle/gradle#6766]
### Expected Behavior

I declare a `java-library` project. In this project, I declare a module exclusion to the `api` configuration. When doing `publish`, this exclusion should be published to the POM as a global exclusion.

### Current Behavior

Currently, the exclusion is not published to the POM at all. Downstream consumers of the library therefore transitively include the excluded dependency.

### Context

A consumer of a java-library published by Gradle can have more dependencies than intended, if setup in this way.

### Steps to Reproduce (for bugs)

Clone repo https://github.com/rocketraman/test-gradle-library-global-exclusions and run:

```
gradle generatePomFileForMavenPublication
```

The output in `build/publications/maven/pom-default.xml` does not contain the appropriate exclusion.

Note that if configuration `api` is changed to `apiElements` in the build, then the exclusion is correctly output to the POM.

### Your Environment

 * Build scan URL: 
https://gradle.com/s/qft6giuc2kdws

**Comment by marcphilipp** [comment]
Thanks for the bug report! I think we should in fact consider the full configuration hierarchy when determining the global excludes here:

https://github.com/gradle/gradle/blob/df2a05123c06691db1a59cf06f1c496d916141d9/subprojects/plugins/src/main/java/org/gradle/api/internal/java/JavaLibrary.java#L166-L172

@oehme Would you consider this a breaking change?
