### ISSUE TITLE
Unincubate all pre-4.x APIs

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6771]
As a first step towards making `@Incubating` more meaningful again, let's remove it from all APIs that haven been there since 4.0, i.e. for over a year. We are not going to change those APIs without deprecation, so they are in fact not incubating anymore. We should then gradually make this stricter.

**Comment by JLLeitschuh** [comment]
Related:
https://github.com/JetBrains/intellij-community/pull/872

**Comment by mkobit** [comment]
Any consideration towards using something like https://github.com/apiguardian-team/apiguardian compared to a single `@Inclubating` marker?

**Comment by oehme** [comment]
No, I don't see the benefit. There already is an annotation for deprecation in the jdk. And stable is our default, so it doesn't need an extra annotation.

**Comment by oehme** [comment]
Yes it should.

**Comment by wolfs** [comment]
Fixed via #7229, #7332 and #7349.
