### ISSUE TITLE
Error handling for 3rd party plugin tasks

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#6772]
Hi, is there a recommended way (if) to intercept/catch errors/exceptions for applied plugins to massage the error messages (for example)?

I saw that `Task` is able to retrieve `LoggingManager` via `getLogging()` which could have an error listener via `addStandardErrorListener`. However it is marked as an internal API. So I'm looking for something public if available

### Expected Behavior
Perhaps make `getLogging` public or provide a public API to intercept exceptions thrown by plugins so messages or action could be taken?

### Current Behavior
Currently this is not possible.

### Context
My current use case is to intercept exceptions or errors from bintray plugin and do some message massaging. For example:

```
 java.io.IOException: Failed to deploy file. Status code: 403 Response message: Artifactory returned the following errors: 
[09:49:07] Not enough permissions to overwrite artifact
```

While the error is clear, we have internal requirements to provide more friendly messaging around this.

**Comment by marcphilipp** [comment]
You should be able to use `Project.getLogging`. I'm closing this issue for now but feel free to report back if this doesn't work for your use case.
