### ISSUE TITLE
Help popular Gradle plugins provide Kotlin DSL usage samples

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#6790]
We want the Kotlin DSL to be a viable alternative for a large number of projects. Now that the vast majority of Gradle documentation (in the [nightly docs](https://docs.gradle.org/nightly/)) includes Kotlin DSL examples alongside Groovy DSL ones, we want to get Kotlin DSL examples for popular plugins as well.

Some of these will be promoted in our Gradle Kotlin DSL 1.0 guides and docs. Please feel free to suggest others we should get in touch with or link to your own plugin examples.

**Plugin authors** can verify your samples using the same library that Gradle does: [Exemplar](https://github.com/gradle/exemplar). You are welcome to reach out directly to eric@gradle.com for help with Kotlin DSL samples or Exemplar.

In case you missed it, here's the [Migrating Build Scripts from Groovy to Kotlin](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/) guide.

| Plugin | Status | Issue/PR |
| --- | --- | --- |
| Android | 🔴 | - |
| [Crashlytics](https://docs.fabric.io/android/crashlytics/build-tools.html#) | 🔴 | - |
| [Firebase](https://firebase.google.com/docs/android/setup?authuser=0) | 🔴 | - |
| [Android Check 2](https://github.com/stoyicker/android-check-2) | 💚 | https://github.com/stoyicker/android-check-2/issues/119 |
| [Spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle) | 🔴 | https://github.com/diffplug/spotless/issues/310 |
| [Kotlinter](https://github.com/jeremymailen/kotlinter-gradle) | 💚 | https://github.com/jeremymailen/kotlinter-gradle/issues/78 |
| [Dex Count](https://github.com/KeepSafe/dexcount-gradle-plugin) | 💚 | https://github.com/KeepSafe/dexcount-gradle-plugin/issues/258 |
| [android-junit5](https://github.com/mannodermaus/android-junit5) | 💚 | https://github.com/mannodermaus/android-junit5/issues/119 |
| [APT](https://github.com/tbroyer/gradle-apt-plugin) | 💚 | https://github.com/tbroyer/gradle-apt-plugin/issues/92 |
| [Android Play Publisher](https://github.com/Triple-T/gradle-play-publisher) | 💚 | https://github.com/Triple-T/gradle-play-publisher/issues/445 |
| [Kotlin](https://github.com/JetBrains/kotlin/tree/master/libraries/tools/kotlin-gradle-plugin) and Kotlin Docs | 💚 | - |
| [Detekt](https://github.com/arturbosch/detekt/tree/master/detekt-gradle-plugin) | 💚 | - |
| [Spring Dependency Management](https://github.com/spring-gradle-plugins/dependency-management-plugin) | 💚 | https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/232 |
| [Spring Boot](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin) | 💚 | https://github.com/spring-projects/spring-boot/pull/14585 |
| [Versions](https://github.com/ben-manes/gradle-versions-plugin) | 💚 | https://github.com/ben-manes/gradle-versions-plugin/issues/267 |
| [Shadow](https://github.com/johnrengelman/shadow) | 🔴 | https://github.com/johnrengelman/shadow/issues/417 |
| [Bintray](https://github.com/bintray/gradle-bintray-plugin) | 🔴 | https://github.com/bintray/gradle-bintray-plugin/issues/265 |
| [Docker](https://github.com/bmuschko/gradle-docker-plugin) | 💚 | - |
| [Git Publish](https://github.com/ajoberstar/gradle-git-publish) | 🔴 | https://github.com/ajoberstar/gradle-git-publish/issues/61 |
| [Build Scan](https://docs.gradle.com/build-scan-plugin/) | 💚 | - |
| [Dependency Graph Generator](https://github.com/vanniktech/gradle-dependency-graph-generator-plugin) | 🔴 | https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/issues/79 |

**Comment by gildor** [comment]
Link on Kotlin plugin is broken.
Probably should be https://github.com/JetBrains/kotlin/tree/master/libraries/tools/kotlin-gradle-plugin

Also Kotlin docs should be changed on this page of official reference:
https://kotlinlang.org/docs/reference/using-gradle.html

**Comment by StefMa** [comment]
Kotlins [Dokka plugin](https://github.com/Kotlin/dokka) should show the Kotlin DSL usage.

**Comment by eriwen** [comment]
Thanks @gildor. Fixed.

Thank you for filing an issue @StefMa. Is Dokka widely used do you think?

**Comment by StefMa** [comment]
As kotlin get more and more popular I think Dokka will be - if it's not
still - get popular too.

I mean we need a alternative for the javadoc, right? 😉

**Comment by deeprim** [comment]
Hi @eriwen,

I believe [Detekt](https://github.com/arturbosch/detekt#gradleplugin), should be on the list,
Thanks

**Comment by jnizet** [comment]
I'll open an issue on the Spring Boot project and offer my help for its translation.

**Comment by mkobit** [comment]
For https://github.com/ben-manes/gradle-versions-plugin, an example and test was added in https://github.com/ben-manes/gradle-versions-plugin/pull/237 and should be available in v0.18.0+

**Comment by mkobit** [comment]
Nebula Lint plugin is currently blocked and fails immediately if attempted to use on the `kotlin-dsl` (https://github.com/nebula-plugins/gradle-lint-plugin/issues/166)

**Comment by JLLeitschuh** [comment]
@nedtwigg Spotless is on this list.

**Comment by bmuschko** [comment]
@eriwen An [initial implementation](https://github.com/bmuschko/gradle-docker-plugin/pull/677) has been added to the Docker plugin and will be released soon.

**Comment by eriwen** [comment]
Thanks for the update @bmuschko.

**Comment by jmfayard** [comment]
@eriwen 
I would suggest to convert your list of plugins with a markdown table with links to the relevant issues if they exist

```
| project               | status                                 |
|---------------------------|-----------------------------------------|
| dexcount-gradle-plugin |  [OK, see #256](https://github.com/KeepSafe//issues/256)  |
| ...   | ...
```

**Comment by aalmiray** [comment]
The guide for https://github.com/aalmiray/kordamp-gradle-plugins version `0.7.0` now displays Groovy & Kotlin examples. See https://github.com/aalmiray/kordamp-gradle-plugins/issues/25

**Comment by eriwen** [comment]
Thanks @aalmiray!

**Comment by mannodermaus** [comment]
As mentioned in https://github.com/mannodermaus/android-junit5/issues/119, android-junit5 now shows Kotlin examples in its README, and there are dedicated sections on the project's wiki.

**Comment by jmfayard** [comment]
@eriwen  https://github.com/ben-manes/gradle-versions-plugin/issues/267 is now resolved, you can update the status of the Versions plugin!

**Comment by eriwen** [comment]
Done with pleasure @jmfayard. Thank you!

**Comment by jmfayard** [comment]
@eriwen more plugins now provide Kotlin DSL samples
- dexcount: https://github.com/KeepSafe/dexcount-gradle-plugin
- Kotlin: https://kotlinlang.org/docs/reference/using-gradle.html
- Android Junit5 https://github.com/mannodermaus/android-junit5
- https://github.com/spring-gradle-plugins/dependency-management-plugin

**Comment by eriwen** [comment]
Look at all of that green. I hope Android is coming soon 🤞

**Comment by jmfayard** [comment]
@eriwen 
Would be nice if that happen.

Meanwhile, I have found a nice work around the lack of documentation from the Android team:

1. Extract the `android { ... }` block to a separate file `app/android.gradle`
2. Convert the rest of app/build.gradle to `app/build.gradle.kts`
3. Add in `app/build.gradle.kts`: `apply(from = "android.gradle")`

https://github.com/jmfayard/update-legacy-android-project/commit/a22c3c4cad4f8db7d562bf7313e23f21b7f7c0d4

**Comment by jjohannes** [comment]
There is no more concrete work planned here and the description has not been updated anymore -> closing.
