### ISSUE TITLE
Extensible disambiguation rules

### ISSUE THREAD

**Issue by melix** [gradle/gradle#6800]
### Context

We knew the problem existed, but it has been highlighted by a fix for the Scala compiler by @big-guy . Whenever the Java plugin is applied, it adds a disambiguation rule, which role is to help selecting the right variant of a Java component, whenever multiple candidates are available.

The problem arises when a plugin wants to enrich the existing model. This is what the Scala plugin does. In addition to the `JAVA_API` and `JAVA_RUNTIME` usages, it adds a new one, an "incremental analysis" usage, that the Scala compiler deals with. It's worth noting that the Scala plugin builds _on top of_ the Java plugin.

The problem, now, is that the default Java disambiguation rule is not capable of dealing with this new additional possible value for the `Usage` attribute. Therefore, the only option is that the Scala plugin adds another disambiguation rule which replicates what the Java disambiguation rule provides, but knowing that there's an additional possible value in the mix.

Note that we discussed using a _separate_ attribute for this (other than `Usage`) since this seems orthogonal to the `Usage`, but it doesn't really solve the problem: while we have disambiguation rules for individual attributes, there's no such thing as a "global" disambiguation rule, which is able to select between multiple candidate variants, on _different_ attributes.

See #6754

**Comment by big-guy** [comment]
We're suffering from this in the gradle/gradle build ourselves:
```
> Could not resolve all files for configuration ':core:integTestRuntime'.
   > Could not resolve project :docs.
     Required by:
         project :core > project :internalIntegTesting > project :launcher
         project :core
      > Cannot choose between the following variants of project :docs:
          - apiElements
          - cssElements
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'apiElements':
              - Found minified 'true' but wasn't required.
              - Found org.gradle.usage 'java-api' but wasn't required.
          - Variant 'cssElements':
              - Found minified 'true' but wasn't required.
              - Found org.gradle.usage 'css-resources' but wasn't required.
          - Variant 'runtimeElements':
              - Found minified 'true' but wasn't required.
              - Found org.gradle.usage 'java-runtime-jars' but wasn't required.
```

This makes `gradle dependencies` on our subprojects report failed dependencies on some configurations. In the `docs` project, we have a "css-resources" usage for exposing the css files elsewhere.

This is going to get worse if we convert our test fixtures to use this same mechanism.
