### ISSUE TITLE
IvyArtifactRepository layout pattern doesn't support orgPath

### ISSUE THREAD

**Issue by rmtmckenzie** [gradle/gradle#6805]
I am trying to use the custom ivy path defining mechanism to download an artifact that doesn't conform to the normal standard for naming.

I'm able to get it to work, but only by providing a non-standard path definition.

### Expected Behavior

Using 'orgPath' in the layout pattern of an ivy repository should not result in an error, and should result in an attempt to download the artifact at the path with `.` replaced by `/` in the organisation.

### Current Behavior
It throws an exception.

### Context

This is the path I'm trying to download an artifact from:
`https://jitpack.io/com/github/mitreid-connect/json-web-key-generator/json-web-key-generator-0.3/json-web-key-generator-json-web-key-generator-0.3-jar-with-dependencies.jar`

This is the pattern I'm trying to use:
```groovy
    ivy {
        url 'https://jitpack.io'
        layout 'pattern', {
            artifact '/[organization]/[module]/[revision]/[module]-[revision]-[ext]'
        }
    }
```
And this is the dependency definition I've ended up using:
    `testImplementation 'com/github/mitreid-connect:json-web-key-generator:json-web-key-generator-0.3@jar-with-dependencies.jar'`

Note that instead of using `com.github.mitreid-connect` as is standard, I'm using slashes because `orgPath` doesn't work.

According to the [gradle docs](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.repositories.IvyArtifactRepository.html#N2567B) for the ivy artifact pattern:

> The available pattern tokens are listed as part of [Ivy's Main Concepts documentation](http://ant.apache.org/ivy/history/master/concept.html#patterns).

That includes `orgPath` which is:

>the organisation name where '.' has been replaced by '/'. This can be used to configure Maven 2-like repositories.

Note that downloading that artifact in that way is a workaround already; I should really repackage it up in a more sensible way myself. However, having a way to download a dependency directly from an URL would another better solution...

### Your Environment
Not relevant to this particular bug, other than that I'm using gradle 4.10.

**Comment by bigdaz** [comment]
You can get the behaviour you want by setting `m2compatible` for the layout: https://docs.gradle.org/current/userguide/repository_types.html#example_ivy_repository_with_maven_compatible_layout

**Comment by rmtmckenzie** [comment]
Ah, missed that. Thanks!
