### ISSUE TITLE
Document a warning against static state in Gradle plugins

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#6818]
Gradle attempts to reuse classloaders between build invocations to keep classes "hot" (since Gradle 2.4).  This has implications for how Gradle plugins (and their dependencies) are written.  Specifically, Gradle plugins, tasks, extensions, etc should in general not keep static state because it can cause problems like resource leaks and make it seem like configuration changes are being ignored.

This leads to other bad advice like:
- Don't use the daemon at all
- Delete your GRADLE_USER_HOME
- Stop/restart the daemon when changing configuration

This would be appropriate in our Gradle guides on plugin development and/or the user manual.

### Context

Given a plugin like this:
```
class MyPlugin implements Plugin<Project> {
    static String prop = System.getProperty("myproperty", "default")
    void apply(Project project) {
       project.logger.lifecycle("myproperty is " + prop)
    }
}

apply plugin: MyPlugin
```

When you run `gradle help`, this produces the message "myproperty is default".
When you run `gradle help -Dmyproperty=somethingelse`, this produces the message "myproperty is default". (surprising!)
When you then stop the daemon and run `gradle help -Dmyproperty=somethingelse`, this produces the message "myproperty is somethingelse". This is the message you'll get until you stop the daemon/use another daemon.

**Comment by mkobit** [comment]
I've seen this a lot with people also expecting environment variable changes to take effect through some tasks that eventually `exec` with inheritance from `System.getenv()`.

```
SOME_VAR=new_var ./gradlew doThing
```

I know something got changed in 4.10 to fix this, but if there is a similar recommendation for that, it would also be useful.
