### ISSUE TITLE
TaskInputs.getProperties() result mutation should be disallowed/documented

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#6821]
Mutating the result from calling [`TaskInputs.getProperties()` ](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskInputs.html) could be expected by a user to mutate the inputs used in up-to-date checks for the ad-hoc task.

### Expected Behavior

Mutating the output map from [`TaskInputs.getProperties()` ](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskInputs.html) should result in an error, or something else to tell the user not to do that. The Javadoc should also clarify the intended use of the method as well as the return value.

### Current Behavior

No errors, feedback to user, and task does not make use of returned properties.

### Context

I recently came across this with a coworker in a build script using ad-hoc task inputs registration.

### Steps to Reproduce (for bugs)

1. `build.gradle.kts`

    ```kotlin
    tasks {
      create("wrapper", Wrapper::class) {
        gradleVersion = "4.10.1"
      }
      create("myAdHocTask") {
        println("Inputs: ${inputs.properties}")
        inputs.property("registered", "value")
        println("Inputs: ${inputs.properties}")
        val content = "hello " + (project.findProperty("myInput") as String? ?: "there")
        // below is line in question
        inputs.properties["content"] = content
        println("Inputs: ${inputs.properties}")
    
        val outputFile = file("output.txt")
        outputs.files(outputFile)
    
        doFirst {
          outputFile.writeText(content)
        }
      }
    }
    ```

1. Run `./gradlew myAdHocTask --console=plain`

    ```
    > Configure project :
    Inputs: {}
    Inputs: {registered=value}
    Inputs: {registered=value}
    
    > Task :myAdHocTask
    ```

1. `cat output.txt`

    ```
    hello there
    ```

1. `./gradlew myAdHocTask -P myInput="gradle" --console=plain`

    ```
    > Configure project :
    Inputs: {}
    Inputs: {registered=value}
    Inputs: {registered=value}
    
    > Task :myAdHocTask UP-TO-DATE
    ```

1. `cat output.txt`

    ```
    hello there
    ```

Expectation from the script author here might be that mutating the returned properties map is allowed and the task would be reexecuted with the new input. It actually does not have impact on the up-to-date checking and is surprising behavior to build script and plugin authors.

### Your Environment

* Gradle 4.10.1

**Comment by lptr** [comment]
Making the result of `TaskInputs.getProperties()` immutable would make the behavior obvious. This is a breaking change we can do in 6.0.
