### ISSUE TITLE
System properties in gradle.properties are non read from init script when using intellij project import

### ISSUE THREAD

**Issue by chali** [gradle/gradle#6825]
I have a project which sets a system property in gradle.properties. I have an init script reading that property. When I run my project through CLI I see the expected value. When I import the project through IntelliJ I see a default value.

### Expected Behavior
I would like to see the same value read in both cases. In my case the boolean value `true`

### Current Behavior
In CLI, my value is correct `true` but when IntelliJ import the project it is `false`

### Context
I use this to enable experimental features in my plugin which affect what configurations appear in my project. I read system properties later in my plugin too. In the plugin, I see the right value which is not consistent with the value what init script got. This is causing different inconsistent configuration leading to failure with dependency locking.

### Steps to Reproduce (for bugs)
Example project: https://github.com/chali/system-properties-not-honored
* Assuming that you are in project directory cp init.gradle ~/.gradle/init.d/
* Run `./gradlew help` You will see this as part of the output `Example property is: true`
* Run `idea .` and as part of Build: Sync you will see `Example property is: false`

### Your Environment
Gradle 4.10.2
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018

JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by oehme** [comment]
`systemProp` values are only parsed right before the `settings.gradle` file is evaluated. At that point init scripts have already run. So this can neither work on the CLI nor in IDEA. I've tried your example and it prints `false` no matter what.

Using `org.gradle.jvmargs=-Dexample.property=true` on the other hand works both on the command line and in IDEA.

So the real issue here is the discrepancy between those two approaches of setting system properties.

**Comment by oehme** [comment]
The reason is that this handling lives in the [`wrapper`](https://github.com/gradle/gradle/blob/09bb4f056b0dcfd1d2ef16c59b234d0ad4575537/subprojects/wrapper/src/main/java/org/gradle/wrapper/SystemPropertiesHandler.java#L25) instead of the Gradle client where it belongs.

**Comment by sschuberth** [comment]
Is there a known workaround to make a programmatic task execution via the tooling API (that injects a custom `init.gradle`) respect proxy settings from `~/.gradle/gradle.properties`?

**Comment by oehme** [comment]
I'm afraid there is no workaround for this at the moment.

**Comment by sschuberth** [comment]
That's unfortunate to hear, @oehme. When you say:

> The naked Gradle executable and the Tooling API only handle these properties later, when the settings.gradle file is loaded, which explains why you can't access it in your init script.

Does that mean that `settings.gradle` is loaded *after* `init.gradle` is evaluated?

Also, isn't there even a "hacky" work-around possible like calling the same code from within the `init.gradle` that the Gradle wrapper would call to apply the proxy settings?

**Comment by oehme** [comment]
> Does that mean that settings.gradle is loaded after init.gradle is evaluated?

Yes.

> Also, isn't there even a "hacky" work-around possible like calling the same code from within the init.gradle that the Gradle wrapper would call to apply the proxy settings?

Well, you could read gradle.properties yourself and set them as system properties. I don't see a reason why that wouldn't work.

**Comment by sschuberth** [comment]
> Well, you could read gradle.properties yourself and set them as system properties. I don't see a reason why that wouldn't work.

That should basically be what I tried via hard-coding above, or:

> And neither does it seem to work to do `System.setProperty('https.proxyHost', 'proxy.host.com')` etc. at the beginning of `init.gradle`.

Or should the system properties be set in the code calling the tooling API instead?

**Comment by oehme** [comment]
What are you trying to affect by setting it in `init.gradle`?

**Comment by sschuberth** [comment]
> What are you trying to affect by setting it in `init.gradle`?

The retrieval of the Gradle wrapper. I'm currently getting "Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-4.10.1-all.zip'" as proxy settings do not seem to be taken into account.

**Comment by oehme** [comment]
The retrieval of the Gradle distribution is based on the system properties of the application that's using the Tooling API. After all, Gradle isn't even started at that point.

**Comment by sschuberth** [comment]
Nevermind, I indeed got it working by setting the proxy-related system properties manually from parsing `~/.gradle/gradle.properties` in the code that calls the tooling API. In my initial attempt I simply forgot to remove the `systemProp.` prefix from the names. (Doh!)

Here's my preliminary Kotlin code to do so:

            val proxyRegex = Regex("^systemProp\\.https?\\.proxy.+$")
            val proxyProperties = getUserHomeDirectory().resolve(".gradle/gradle.properties").inputStream().use {
                Properties().apply { load(it) }.filter { (key, _) ->
                    (key as String).matches(proxyRegex)
                }
            }

            proxyProperties.forEach { (key, value) ->
                System.setProperty((key as String).removePrefix("systemProp."), value as String)
            }

**Comment by sschuberth** [comment]
Now the next problem is that indeed resolution of Gradle plugins fails.

> If you're trying to affect buildscript dependency resolution, make sure that you put it inside the `buildscript {}` block.

What is "it" in the sentence above? The call to `System.setProperty()`?

**Comment by oehme** [comment]
Exactly.

**Comment by big-guy** [comment]
@donat can you see if this can be closed with an explanation of 6.x's behavior now?

**Comment by donat** [comment]
No, this issue is still valid. In https://github.com/gradle/gradle/issues/11173 we did not check the behavior of `init.d`/init scripts. I think the difference comes from the fact that the main class reads and sets those system properties from `gradle.properties` _before_ launching Gradle. @sterling Should that be the expected behavior for all invocation methods?

**Comment by sschuberth** [comment]
Ok, so as quick recap, I'm able to make a build that I trigger via the Tooling API and to which I pass an `init.gradle` script to properly download its needed Gradle distribution behind a proxy by settings the according proxy system properties in the application that calls the Tooling API. However, the programmatically triggered build still cannot download its compile dependencies (I'm not talking about build plugin dependencies here). And that is although I'm *also* setting the proxy system properties inside the `init.gradle`. Any more hints on how to resolve this, @oehme?

**Comment by oehme** [comment]
We could mimic the behavior of GradleWrapperMain in the TAPI by changing [this line](https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/DaemonBuildActionExecuter.java#L45). Instead of just passing the Daemon system properties here, we could pass all system properties. That would result in them being set before init scripts are evaluated. We might then be able to remove the other system-property related code in the SettingsEvaluator.

**Comment by oehme** [comment]
This was also causing problems when using dependency verification together with init scripts.

**Comment by eskatos** [comment]
Fixed in https://github.com/gradle/gradle/pull/16757
This will be in Gradle 7.1
