### ISSUE TITLE
Missing rules in selection reasons in dependencyInsight

### ISSUE THREAD

**Issue by chali** [gradle/gradle#6826]
### Expected Behavior
When I'm running `dependencyInsight` task I would like to see all rules affecting inspected dependency under selections reason.

### Current Behavior
* `resolutionStrategy.eachDependency { DependencyResolveDetails details -> details.useVersion = 'XXX'}` Is shown only when `because` is provided
* `resolutionStrategy.dependencySubstitution` is shown only when `because` is provided and it must be the first rule taking effect. When substituting a version set through the previous point it is not shown too.

### Context
In real life, we have projects with many more dependencies and tenths of rules applied by plugins so we are not necessarily aware of all possible sources of rules. Dependency insight is a tool on which we heavily rely on to get the complete picture. 

Here is my build file:
```
apply plugin: 'java'

repositories {
    mavenCentral()
}

configurations.all {
    resolutionStrategy.eachDependency {DependencyResolveDetails details ->
        if (details.requested.group == 'net.spy') {
            details.useVersion '2.11.7'
            //details.because '2.11.7 is a good one'
        }
    }
    resolutionStrategy.dependencySubstitution {
       substitute(module('net.spy:spymemcached:2.11.7'))
         //.because('not really 2.11.6 is a good one')
         .with(module('net.spy:spymemcached:2.11.6'))
           
    }
}

dependencies {
    compile 'net.spy:spymemcached:2.11.5'
}
```

### Steps to Reproduce (for bugs)
`./gradlew dependencyInsight --dependency spymemcached --configuration compile` produces this output:
```
> Task :dependencyInsight
net.spy:spymemcached:2.11.7 (selected by rule)
   variant "default" [
      org.gradle.status = release (not requested)
   ]

net.spy:spymemcached:2.11.5 -> 2.11.7
\--- compile
```

### Your Environment
Gradle: 4.10.2

**Comment by bigdaz** [comment]
I can see a few related issues here:
1) If multiple rules are applied for the same module, only the last rule applied will be reported in the dependency insight report.
2) If the last rule applied has no reason provided, then the report shows `(selected by rule)` in the header rather than the more comprehensive `Selection reasons:` block. I don't think this shortcut is all that helpful, and the inconsistency is confusing.

**Comment by OdysseusLives** [comment]
That's awesome that there are additional selection reasons, as in [this example with multiple rules acting on a module](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons-with-subst/details-with-reason-subst-without/output.txt#L16-L17) that show a line for "Selected by rule" even when a reason is not provided.

I will add that the trail of selection reasons is also very interesting!

--------

A simple case is [with two selection rules, 1 with a reason](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons-with-subst/details-with-reason-subst-without/input/build.gradle) with the following [output](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons-with-subst/details-with-reason-subst-without/output.txt#L16-L17):

(I'm using Gradle 5.1-20181127213941+0000 for all these examples)

```
> Task :dependencyInsight
net.spy:spymemcached:2.11.6
   variant "compile" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-api
      org.gradle.component.category = library (not requested)
   ]
   Selection reasons:
      - Selected by rule : 2.11.7 is a good one
      - Selected by rule

net.spy:spymemcached:2.11.5 -> 2.11.6
\--- compileClasspath
```

Without looking at the build file, it's not clear when or how `2.11.6` was introduced to the project. 

------------

This simple case can become much more complicated, as well, as in:

**[complex example: has reasons shown](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons/complex-have-reasons-here/input/build.gradle) with [output](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons/complex-have-reasons-here/output.txt)**
```
> Task :dependencyInsight
org.mockito:mockito-core:1.8.3
   variant "compile" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-api
      org.gradle.component.category = library (not requested)
   ]
   Selection reasons:
      - Forced
      - Selected by rule : RULE 1
      - Selected by rule : RULE 2
      - Selected by rule : SUBSTITUTION 1
      - Selected by rule : SUBSTITUTION 2
      - Selected by rule : SUBSTITUTION 3

org.mockito:mockito-all:1.8.0 -> org.mockito:mockito-core:1.8.3
\--- compileClasspath
```

**[complex example: would love reasons shown](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons/complex-would-love-reasons-here/input/build.gradle) with [output](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons/complex-would-love-reasons-here/output.txt)**
```
> Task :dependencyInsight
org.mockito:mockito-core:1.8.3
   variant "compile" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-api
      org.gradle.component.category = library (not requested)
   ]
   Selection reasons:
      - Forced
      - Selected by rule
      - Selected by rule

org.mockito:mockito-all:1.8.0 -> org.mockito:mockito-core:1.8.3
\--- compileClasspath
```
----------

Ideally, when a selection criteria does not have a reason attached, information from the code that introduced it is still provided.

**Suggestion: a snippet of the introductory line**
```
   Selection reasons:
      - Selected by rule : 2.11.7 is a good one
      - Selected by rule : useVersion '2.11.7'
```

**Suggestion: snippet with line number from local project**
```
   Selection reasons:
      - Selected by rule : 2.11.7 is a good one
      - Selected by rule : useVersion '2.11.7' from build.gradle#L12
```

**Suggestion: snippet with line number from an external dependency**
```
   Selection reasons:
      - Selected by rule : 2.11.7 is a good one
      - Selected by rule : useVersion 'foo' from org.springframework.boot:spring-boot-gradle-plugin:1.4.7.RELEASE
```
As would be applicable in [an example with the Spring Boot 1.x plugin](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/misc/spring-boot-dependencies-v1.x.x/input/build.gradle) with [output](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/misc/spring-boot-dependencies-v1.x.x/output.txt#L5) which looks at a dependency managed by the Spring Boot 1.x plugin, that it described as "(selected by rule)" in the header.

-------

Finally, the shortcut `(selected by rule)` in the header is less preferable, as noted in the comment above. I might wonder what are my selection reasons, and miss this shortcut on top.

It's still used, as in [this example with a single selection rule with no provided reason](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/dependency-insight/docs/missing-reasons/use-version-without-a-reason/output.txt)
