### ISSUE TITLE
Can not download jar from private maven depository

### ISSUE THREAD

**Issue by shenhejia** [gradle/gradle#6829]
maven {
            url "http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/"
        }
implementation 'com.alibaba:fastjson:1.2.9'
    implementation 'com.ali.auth.sdk:alibabauth_core:1.4.3@jar'
    implementation 'com.ali.auth.sdk:alibabauth_ui:1.4.3@aar'
    implementation 'com.ali.auth.sdk:alibabauth_ext:1.4.3@jar'

### Current Behavior
Resource missing. [HTTP GET: http://maven.aliyun.com/nexus/content/groups/public/com/ali/auth/sdk/alibabauth_ui/1.4.3/alibabauth_ui-1.4.3.pom]
Resource missing. [HTTP HEAD: http://maven.aliyun.com/nexus/content/groups/public/com/ali/auth/sdk/alibabauth_ui/1.4.3/alibabauth_ui-1.4.3.aar]
ould not find com.ali.auth.sdk:alibabauth_core:1.4.3.
  Searched in the following locations:
      file:/Users/apple/Documents/soft/android-sdk-macosx/extras/m2repository/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      file:/Users/apple/Documents/soft/android-sdk-macosx/extras/m2repository/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      file:/Users/apple/Documents/soft/android-sdk-macosx/extras/google/m2repository/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      file:/Users/apple/Documents/soft/android-sdk-macosx/extras/google/m2repository/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      file:/Users/apple/Documents/soft/android-sdk-macosx/extras/android/m2repository/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      file:/Users/apple/Documents/soft/android-sdk-macosx/extras/android/m2repository/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      https://repo.maven.apache.org/maven2/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      https://repo.maven.apache.org/maven2/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      https://jcenter.bintray.com/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      https://jcenter.bintray.com/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      https://www.jitpack.io/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      https://www.jitpack.io/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      http://maven.wtvdev.com:8090/nexus/content/repositories/tvclient/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      http://maven.wtvdev.com:8090/nexus/content/repositories/tvclient/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      http://maven.wtvdev.com:8090/nexus/content/repositories/tvclient-snapshots/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      http://maven.wtvdev.com:8090/nexus/content/repositories/tvclient-snapshots/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      http://maven.aliyun.com/nexus/content/groups/public/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      http://maven.aliyun.com/nexus/content/groups/public/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar
      file:/Users/apple/Documents/wasutv4.0/libs/alibabauth_core-1.4.3.jar
      file:/Users/apple/Documents/wasutv4.0/libs/alibabauth_core.jar
      https://maven.google.com/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.pom
      https://maven.google.com/com/ali/auth/sdk/alibabauth_core/1.4.3/alibabauth_core-1.4.3.jar

but I can download Jar by Safari 
### Your Environment
macos 10.12.6
android studio 3.1.2
gradle 4.4
jdk 1.8.0_91

 * Build scan URL:

**Comment by marcphilipp** [comment]
Could you please enabled `--debug` and share the output?

**Comment by shenhejia** [comment]
> Could you please enabled `--debug` and share the output?

thank you for your reply. The problem has been solved, i set no proxy in AS, but forget set the file gradle.properties ;
by the way , why i set proxy in AS, the gradle.properties will also seted , but i set no proxy in AS, the file gradle.properties is still ...
