### ISSUE TITLE
Allow / document uploading to plugin portal without plugin-publish

### ISSUE THREAD

**Issue by kamalmarhubi** [gradle/gradle#6842]
### Expected Behavior
As a plugin author, I can publish my plugin to the [Gradle Plugin Portal](http://plugins.gradle.org/) without requiring the [plugin-publish](https://plugins.gradle.org/docs/publish-plugin) plugin. This could be as simple as a web form allowing me to upload artifacts, but something easier to automate would be better.

### Current Behavior
I cannot publish my plugin to the portal, increasing friction for my users who have to add maven repos in their buildscript.

### Context
Our plugin's build is done in bazel for uniformity with the rest of our related projects. Part of the build generates files in a maven layout, including required metadata and hashes, so we have that part covered. I'm looking for a way to get the plugin DSL benefits for our users without having to rework our entire build.

A cursory look the plugin's jar indicates that it's covered under Apache License 2.0, but the source of doesn't seem to be available, which makes it more annoying to adapt.

### Steps to Reproduce (for bugs)
1. use a non-Gradle build system to build a Gradle plugin
2. attempt to follow the directions to include it in the plugin portal
3. :crying_cat_face:

**Comment by marcphilipp** [comment]
The HTTP API to publish to the Plugin Portal is considered internal for now and we have no plans to publish it at this point.

However, the `plugins` DSL supports any Maven repo you configure using `buildscript`. Would that be an option?
