### ISSUE TITLE
Feature? dependency lock missing skippedDependencies Property

### ISSUE THREAD

**Issue by chunling-ren** [gradle/gradle#6846]
### Expected Behavior

The ‘Locking of dynamic dependencies’ could provide the options to exclude/skip some specific dependencies. 
Just like the property 'skippedDependencies  = [<group>:<artifact>]' used in gradle plugin 'nebula.dependency-lock'
### Current Behavior
I don't find such property to exclude/skip some specific dependencies in gradle's ‘Locking of dynamic dependencies’ feature's usage.
### Context
We use gradle plugin 'nebula.dependency-lock' in our projects now, and try to migrate it to gradle's built in dependency lock.
There is one property 'skippedDependencies  = [<group>:<artifact>]' used in 'nebula.dependency-lock', that I can use to skip some specific dependencies from locking. But I couldn't find the corresponding configure in gradle's dependency lock.
Is that in your plan in future, or I missed something?
### Your Environment
From gradle 4.8.0.

**Comment by ljacomet** [comment]
Can you elaborate on the use case? Why would want _some_ dependencies to remain unlocked? What's the benefit for the build authors / developers working with the code?
