### ISSUE TITLE
Support GStrings in publishing pom-dsl

### ISSUE THREAD

**Issue by sdavids** [gradle/gradle#6858]
```
  publishing {
    publications {
      mavenJava(MavenPublication) {
        from components.java
        pom {
          name = "${project.name}"
        }
      }
    }
  }
```

==>

> Cannot set the value of a property of type java.lang.String using an instance of type org.codehaus.groovy.runtime.GStringImpl.

**Comment by big-guy** [comment]
Thanks @sdavids, this was already fixed in https://github.com/gradle/gradle/pull/6536 and will be in the next release (5.0).
