### ISSUE TITLE
Kotlin plugins don't export kotlin

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#6859]
https://github.com/tbroyer/gradle-errorprone-plugin/issues/6#issuecomment-421489539

it seems that if you write a plugin with kotlin, that you can get kotlin for free from the dsl, but then the plugin doesn't export that, and so if you're consuming that plugin with java in another plugin, the APIs can be missing. I doubt this is an actual problem with the DSL itself... though maybe... see aforementioned external ticket for where this is happening.

My thought is that if gradle can provide the kotlin std lib, it should export it, the way it does groovy stuff.

**Comment by marcphilipp** [comment]
@gradle/kotlin-dsl Does this ring a bell?

**Comment by tbroyer** [comment]
Fwiw, plugins don't "export" Groovy or the Gradle API either. But when using the `java-gradle-plugin` you get the `gradleApi()` compile dependency, which transitively brings `localGroovy()` (IIUC), but not the embedded Kotlin. AIUI, this creates a discrepancy between dependencies that "transitively depend" on Kotlin (such as plugins using `kotlin-dsl`, or anything using `embeddedKotlin("…")`), and virtually all others.

**Comment by tmack8001** [comment]
this is a very annoying issue when combining plain java projects and gradle plugins that are built with kotlin, adding explicit dependencies in my project to kotlin dsl just seems dirty...
