### ISSUE TITLE
builsSrc project can't resolve symbol, show unused variables

### ISSUE THREAD

**Issue by mtrakal** [gradle/gradle#6867]
Sample project: https://github.com/mtrakal/buildSrcIssue

### Expected Behavior
Resolve import file, didn't show all used variables start with `Config.XXX` as not recognized and in `buildSrc -> Confit.kt` file don't show all as unused.

### Current Behavior
app/build.gradle have `import cz.bs.Config` which is in `\buildSrc\src\main\kotlin\cz\bs\Config.kt`
but it didn't recognize it. It recognize it in root `build.gradle` in this sample project, but not in my real project, maybe same issue as why it didn't resolve in `/app/build.gradle`

### Steps to Reproduce (for bugs)
just sync proejct in Intellj Idea, look at `\app\build.gradle` file and you will see `import` as red and not recognized.

### Your Environment

 * Build scan URL: 
https://gradle.com/s/5shrwwihi5hwa

IntelliJ IDEA 2018.3 EAP (Community Edition)
Build #IC-183.2635.13, built on September 19, 2018
JRE: 1.8.0_152-release-1293-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

<img width="960" alt="2018-09-24" src="https://user-images.githubusercontent.com/1458891/45943181-a0bda800-bfe5-11e8-8a3a-9af23563a648.png">

**Comment by big-guy** [comment]
This appears to be working for me (IDEA 2018.3, Gradle 5.3). 

We don't have much control over making `build.gradle` auto-complete better than it is.  If you want better IDE support, [there's Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:ide_support).
