### ISSUE TITLE
Feature request: integrate with native scala compiler

### ISSUE THREAD

**Issue by dsilvasc** [gradle/gradle#6905]
The graal team at Oracle has put together instructions for how to compile the scala compiler to a native image:

https://github.com/graalvm/graalvm-demos/tree/master/scala-days-2018/scalac-native
https://www.youtube.com/watch?v=lQNXwb66eQ8

It would be nice to have an option in Gradle to use this instead of the JVM-hosted compiler.

This would reduce the time currently taken by JVM + GradleWorkerMain startup in compileScala and compileTestScala tasks.

### Expected Behavior

`org.gradle.api.tasks.scala.ScalaCompile` could have an option to use the native scalac image and use that instead of starting another JVM for the compiler.

It could start with no incremental compilation support (zinc).

### Current Behavior

ScalaCompile runs zinc/scalac as a java program in a gradle worker jvm, which incurs a startup cost.

### Context

Trying to reduce the time spent in compileScala, compileTestScala, compileScoverageScala, and compileTestScoverageScala tasks -- especially in a multi-project build with lots of small subprojects (invoking the compiler lots of times).

**Comment by oehme** [comment]
The compiler worker is reused across compile tasks, so a native image won't save you much. At some point we'll even reuse them across builds, making a native image even less useful. So it's really not worth the extra complexity I think.
