### ISSUE TITLE
Generating POM files is slower than required because output upToDateWhen always failing

### ISSUE THREAD

**Issue by martinrosstmc** [gradle/gradle#6925]
We have hundreds of subprojects in our project.  These are published out to mavenLocal repo.  According to build scan we are spending a significant amount of time in :generatePomFileForCoreJavaPublication tasks.  This is because 
GenerateMavenPom  constructor has the following code

    public GenerateMavenPom() {
        // Never up to date; we don't understand the data structures.
        getOutputs().upToDateWhen(Specs.satisfyNone());
    }

There is no way to add a hook to control this since if ANY of the upToDateWhen calls fail the method will be rerun.

### Expected Behavior

GenerateMavenPom should either have proper up-to-date check OR should allow the user to plug in their own check.

I am happy to contribute a patch if given a bit of guidance on what to check.

### Your Environment

 * Build scan URL:

**Comment by JamesXNelson** [comment]
This would be really nice, in cases when one might want to put that pom in a resource like a jar; the constant invalidation would really be a pain.

If DefaultMavenPublication had an onPopulated listener, it could be configured to wait until the full set of `MavenDependency`s are known, and then use those to populate a sane up-to-date check.

**Comment by trejkaz** [comment]
I have a reasonable workaround:

    tasks.withType(GenerateMavenPom) {
        onlyIf {
            if (!destination.exists()) {
                return true
            }

            def pomGenerator = new MavenPomFileGenerator(pom.projectIdentity, versionRangeMapper)
            pomGenerator.configureFrom(pom)
            pom.apiDependencyManagement.each { dependency ->
                pomGenerator.addApiDependencyManagement(dependency)
            }
            pom.runtimeDependencyManagement.each { dependency ->
                pomGenerator.addRuntimeDependencyManagement(dependency)
            }
            pom.importDependencyManagement.each { dependency ->
                pomGenerator.addImportDependencyManagement(dependency)
            }
            pom.apiDependencies.each { dependency ->
                pomGenerator.addApiDependency(dependency)
            }
            pom.runtimeDependencies.each { dependency ->
                pomGenerator.addRuntimeDependency(dependency)
            }
            pomGenerator.withXml(pom.xmlAction)
            def tempFile = file("${destination}.tmp")
            pomGenerator.writeTo(tempFile)

            return destination.getText('UTF-8') != tempFile.getText('UTF-8')
        }
    }

This at least stops it writing the file again, so downstream tasks like jar and test don't have to run again, but I'd at least prefer not to have to duplicate the logic of `GenerateMavenPom`. Still, this might demonstrate what the task itself _could_ do to avoid it.
