### ISSUE TITLE
Intellij problems with native import of `gradle/gradle`

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#6941]
This issue collects problems we have/had when using the native Gradle import in Intellij for `gradle/gradle`.

There is also a [Google Doc](https://docs.google.com/document/d/1iCv02TqT0nB-BIKnVnKrztGOj_CAHol6NIaTU_81DuA/edit#) collecting some problems and solutions.

**Comment by wolfs** [comment]
We are affected by https://youtrack.jetbrains.com/issue/IDEA-194910, which caused us to implement this workaround: https://github.com/gradle/gradle/blob/d430dcbe8aff0bbe94781314c4557468c5b41de4/subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/IntegrationTestBuildContext.java#L118-L123

**Comment by wolfs** [comment]
Intellij is reporting some Javadoc errors in `coreApi` when referring to classes in the same directory: https://youtrack.jetbrains.com/issue/IDEA-199670

**Comment by wolfs** [comment]
We are hit by a problem when some part of the source code is not compiled: https://youtrack.jetbrains.com/issue/IDEA-200656

That requires the developer to manually build part of the projects.

**Comment by wolfs** [comment]
Maybe the IDEA13 workaround is related to some of the problems: https://github.com/gradle/gradle-private/issues/195

**Comment by jjohannes** [comment]
To avoid duplicated tracking and to make sure we do not get confused, I am closing this issue. Lets use separate issues for things we need to fix on the Gradle side and the Google Doc for everything else we need to track.I just updated the document and made sure it covers everything mentioned in this issue.

I am linking the document in #6809. #6809 is also the place where we also collect all the GH issue regarding this topic.
