### ISSUE TITLE
Too many workers when running in docker containers?

### ISSUE THREAD

**Issue by iamdanfox** [gradle/gradle#6942]
_On large projects that use `--parallel` and build in CircleCI docker images, I've observed gradle spinning up way more workers than vCPUs available. My workaround is to explicitly set `--max-workers` but ideally I'd like Gradle to detect this automatically. My motivation here is to stop builds failing with `exit 137`._

### Expected Behavior

Running `./gradlew build --parallel` inside a docker container should spawn no more workers than vCPUs available to the container. They should also pick sensible heap sizes to avoid OOMs (already tracked in https://github.com/gradle/gradle/issues/5102 I think).

### Current Behavior

- All CI builds for [palantir/conjure-java-runtime](https://github.com/palantir/conjure-java-runtime) run inside `circleci/openjdk:8u181-jdk` docker images (on [CircleCI 2](https://circleci.com/)).
- Running `./gradlew build --parallel --scan` shows 13 workers, when CircleCI claims they only allocate 3 vCPUs (the build scan shows gradle has detected 32 cores)
- (Interestingly it always seems to pick 13 workers, even if you dial up the CircleCI resource_class to xlarge which allocates 8 vCPUs)

<img width="1205" alt="screen shot 2018-09-28 at 16 30 06" src="https://user-images.githubusercontent.com/3473798/46219141-7732b280-c33e-11e8-892a-e0727977b691.png">

### Context

I'm trying to reduce the rate of CircleCI build failures due to `exit 137` errors.

### Steps to Reproduce (for bugs)

 * Build scan URL: https://gradle.com/s/r44w2hsonaqo6
 * Relevant branch: https://github.com/palantir/conjure-java-runtime/pull/832

**Comment by iamdanfox** [comment]
Trying to find a proposal for how to fix this, it seems that on older JVMs, [`Runtime.getRuntime().availableProcessors()`](https://github.com/gradle/gradle/blob/master/subprojects/base-services/src/main/java/org/gradle/internal/concurrent/DefaultParallelismConfiguration.java#L33) will always return the number of physical CPUs. 

Apparently OpenJDK are tracking this (https://bugs.openjdk.java.net/browse/JDK-8146115) and the `UseContainerSupport` flag was backported to 8u192 (scheduled for [Oct 2018](http://openjdk.java.net/projects/jdk8u/releases/8u192.html) release).  

Perhaps it's not actually worth the effort to try to make this work on older JVMs - any kind of more precise detection seems to be a very platform-specific thing, which I assume gradle tries to avoid?

**Comment by oehme** [comment]
If there is a fix in the JVM then indeed I think we should avoid working around it ourselves. We could document that users should use that flag or even add it ourselves if that makes sense.

**Comment by oehme** [comment]
Closing since this is fixed in the JDK. Documentation tracked in #6988

**Comment by iamdanfox** [comment]
Thanks, I think an authoritative guide on how to make Gradle behave in docker would be awesome.
