### ISSUE TITLE
Feature Request: Property based implementation PasswordCredentials

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6943]
### Context

This idea originated from this discussion with @bmuschko on his Gradle Plugin:
https://github.com/bmuschko/gradle-docker-plugin/pull/655#issuecomment-424041169
This spawned from his work on the docker plugin to convert the whole API to using the new lazy API.
https://github.com/bmuschko/gradle-docker-plugin/pull/659

Currently, the `org.gradle.api.credentials.PasswordCredentials` is a javabean style API.
This means that the username/password can't be lazily configured.

I propose adding an additional interface, similar to the `PasswordCredentials` but calling it `PropertyBackedPasswordCredentials`.

This is the proposed structure for such an interface:

```java
interface PropertyBackedPasswordCredentials extends Credentials {
    Property<String> getUsername();
    Property<String> getPassword();

    /**
     * Exposes a delegate to this interface as a {@link PasswordCredentials}.
     */
    default PasswordCredentials asPasswordCredentials() {
        return new PasswordCredentials() {
            @Nullable
            @Override
            public String getUsername() {
                return PropertyBackedPasswordCredentials.this.getUsername().getOrNull();
            }

            @Override
            public void setUsername(@Nullable String userName) {
                PropertyBackedPasswordCredentials.this.getUsername().set(userName);
            }

            @Nullable
            @Override
            public String getPassword() {
                return PropertyBackedPasswordCredentials.this.getPassword().getOrNull();
            }

            @Override
            public void setPassword(@Nullable String password) {
                PropertyBackedPasswordCredentials.this.getPassword().set(password);
            }
        };
    }
}
```

This would allow plugin authors to have a common interface for implementing `Property` backed extensions where authentication is needed.

This is good for build writers because we are able to have a common interface to configure all authentication against.

**Comment by JLLeitschuh** [comment]
@rieske Did you do something in this area recently? Has this issue been resolved?

**Comment by rieske** [comment]
Yes, I believe so - have a look at this sample: https://docs.gradle.org/current/samples/sample_publishing_credentials.html

**Comment by SimonCJacobs** [comment]
That link does not show passing credentials to a repository in a using a lazy `Provider`/`Property` approach. It's all about using project properties, like those in a `gradle.properties` file
