### ISSUE TITLE
JacocoCoverageVerification  Task is not annotated with @CacheableTask

### ISSUE THREAD

**Issue by decoded4620** [gradle/gradle#6951]
The JacocoCoverageVerification Task is not @Cacheable

**Comment by decoded4620** [comment]
https://github.com/gradle/gradle/blob/b4855c745a218094fe21c83cd5fe5042f0f1c987/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoCoverageVerification.java

**Comment by wolfs** [comment]
@decoded4620 The `JacocoCoverageVerification` is not annotated with `@Cacheable` since it has no output files (at least currently) and therefore cannot be cached. How long is this task running for you, it should be fast given that it only needs to parse the execution data, right?
