### ISSUE TITLE
create reliable CI version by sane default

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#6962]
gradle should make an effort to generate a default version of an artifact built. current java builds leave the version setting to developers. especially when packaging ears or wars or other types of applications which include binary dependencies this is a problem when using snapshot versions or version ranges.

gradle could generate a safe version as it knows a lot about the build. it could use, just to name a few, the source code management git hash, a hash of binary file dependencies, a timestamp. important is to get the same version if nothing in the dependent sources or binaries changed. otherwise it would cause a new version with the same contents trickle down all dependencies.

i am aware that gradle enterprise offers a feature which helps to find an issue with creating new version without necessity so developers can manually create a sane version. but - that sounds like a second class workaround which can (and should) be solved by the tool.

**Comment by oehme** [comment]
> i am aware that gradle enterprise offers a feature which helps to find an issue with creating new version without necessity so developers can manually create a sane version. but - that sounds like a second class workaround which can (and should) be solved by the tool.

I don't know what you mean by this. Gradle enterprise doesn't manage your project's versions.

There are plenty of plugins that define versioning strategies, including versioning from the git hash (e.g. https://github.com/ajoberstar/gradle-git). Gradle core is not opinionated on this.
