### ISSUE TITLE
For dependencies with resolutionStrategy, the dependency version is not written to the POM

### ISSUE THREAD

**Issue by BorzdeG** [gradle/gradle#6963]
### Expected Behavior
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>demo</groupId>
  <artifactId>gradle-pom-versions</artifactId>
  <version>1</version>
  <dependencies>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>1.2.61</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.7.25</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

### Current Behavior
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>demo</groupId>
  <artifactId>gradle-pom-versions</artifactId>
  <version>1</version>
  <dependencies>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>1.2.61</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

### Context

build.gradle.kts:
```gradle
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformCommonPlugin

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath(embeddedKotlin("gradle-plugin"))
  }
}

group = "demo"
version = "1"

apply {
  plugin<MavenPublishPlugin>()
  plugin<KotlinPlatformCommonPlugin>()
}

repositories {
  jcenter()
}
dependencies {
  "compile"(kotlin("stdlib"))
  "compile"("org.slf4j:slf4j-api")
}

configurations.all {
  resolutionStrategy {
    eachDependency {
      if (requested.group == "org.slf4j") {
        useVersion("1.7.25")
      }
    }
  }
}

configure<PublishingExtension> {
  publications {
    this.create("demo", MavenPublication::class.java) {
      from(project.components["java"])
    }
  }
}
```

### Steps to Reproduce (for bugs)

`gradle generatePomFileForDemoPublication`

### Your Environment

 * Build scan URL: https://gradle.com/s/spxvqh7t4n5oo

**Comment by ljacomet** [comment]
Right now publication is based on _declared_ dependency versions. Though we are considering adding a feature to publish _resolved_ version, that is not yet the case.

Could you elaborate on the exact issue you have? I assume this reproducer is a simplified version of the original issue.
It seems weird to define a first level dependency without a version at all and rely on a substitution rule for setting it.
Have you considered [_dependency constraints_](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#example_define_dependency_constraints)? They will be properly published to `dependencyManagement`

**Comment by BorzdeG** [comment]
@ljacomet Yes, this is a simplified model of a multi-modular configuration that reproduces the problem.

A complete example is [here](https://github.com/itbasis/kotlin-utils/) - now in each module you have to explicitly indicate the version of the dependency so that it is written into the POM-file

Instead of just writing `com.github.lewik.klogging:klogging.jvm`, you have to write `com.github.lewik.klogging:klogging.jvm:$kloggingVersion`: https://github.com/itbasis/kotlin-utils/blob/master/kotlin-utils-jvm/build.gradle.kts#L12

**Comment by ljacomet** [comment]
It is on the roadmap of the Gradle dependency management team to come up with recommendations on declaring dependencies and managing versions in build scripts.
Reducing such repetition is one of the aspects we would consider.

As there will be no specific handling of substitution, force or other dynamic manipulation of dependencies declaration in the current publication setup, I am closing this.

**Comment by awasthi1312** [comment]
we use maven. I am able to exclude the child-jar but unable to find the way to include at the same time as mentioned in resolutionStrategy. Could you please share a way to achieve below in maven-pom?
configurations.all {
  resolutionStrategy {
    eachDependency {
      if (requested.group == "org.slf4j") {
        useVersion("1.7.25")
      }
    }
  }
}

**Comment by ljacomet** [comment]
See [publication of _resolved_ versions](https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies).
