### ISSUE TITLE
Use configured system proxy settings for HTTP

### ISSUE THREAD

**Issue by ghost** [gradle/gradle#6966]
I work behind corporate proxy and have to provide proxy settings flags for gradle to download dependencies. The problem is I have to store my password in a plain text file gradle.properties.
There is the `useSystemProxies` Java flag that allows to use system proxy settings instead of specifying username and password etc. Is there a similar flag for gradle? It's very insecure to store username and password.

### Expected Behavior
I expect that flag `useSystemProxies` works i.e. uses configured Windows' proxy as it does Google Chrome for instance.

### Current Behavior
I'd like to gradle learn to use system's proxy settings without necessity to provide username and password in a plain text file.

I've set the `useSystemProxies` to true in gradle.properties like `org.gradle.jvmargs=-Djava.net.useSystemProxies=true`. JVM recognizes proxy but gradle assemble fails with timeout error.

> C:\Users\admin\projects\Android>gradle assemble
> Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
>
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> A problem occurred configuring root project 'Android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.3.
     Required by:
         project :
      > Skipped due to earlier error
      > Could not resolve com.android.tools.build:gradle:3.1.3.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.3/gradle-3.1.3.pom'.
               > Connect to corpproxy.local:8080 [corpproxy.local/192.168.0.17, corpproxy.local/192.168.0.11] failed: Connect timed out
   > Could not resolve io.fabric.tools:gradle:1.+.
     Required by:
         project :
      > Failed to list versions for io.fabric.tools:gradle.
         > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/io/fabric/tools/gradle/maven-metadata.xml.
            > Could not get resource 'https://dl.google.com/dl/android/maven2/io/fabric/tools/gradle/maven-metadata.xml'.
               > Could not GET 'https://dl.google.com/dl/android/maven2/io/fabric/tools/gradle/maven-metadata.xml'.
                  > Connect to corpproxy.local:8080 [corpproxy.local/192.168.0.17, corpproxy.local/192.168.0.11] failed: Connect timed out
>
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log > output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
>
> BUILD FAILED in 2m 6s

**Comment by ehmkah** [comment]
@radikpsb - as workaround you could use a local installed proxy like cntlm. This proxy stores your password encrypted and then there is no need to give it in plaintext to any app.
