### ISSUE TITLE
Rich console is not detected with ConEmu on Windows 10

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#6969]
When running with [ConEmu version 180626 64bit](https://github.com/Maximus5/ConEmu/releases) (TERM=xterm-256color), Gradle starts up with a non-rich console. When forcing it with `--console=rich` the rich console works fine.

(Issue broken out of #6874).

**Comment by adammurdoch** [comment]
This should be fixed with https://github.com/gradle/gradle/pull/8189. Can you try it out?

**Comment by lptr** [comment]
Looks like it works well with the latest nightly:

![image](https://user-images.githubusercontent.com/495366/50915085-51867080-1438-11e9-8c4d-de3a8b2d0a0a.png)

**Comment by adammurdoch** [comment]
I'll close this as fixed. We can add new issues for any remaining problems.
