### ISSUE TITLE
Rich console is not detected with MinTTY on Windows 10

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#6970]
When running with MinTTY version 2.9.0 used by Git Bash and WSL console (`TERM=xterm`), Gradle starts up with a non-rich console. When forcing it with `--console=rich` the rich console works fine.

(Issue broken out of #6874).

**Comment by adammurdoch** [comment]
This should be fixed with https://github.com/gradle/gradle/pull/8189. Can you try this out?

**Comment by lptr** [comment]
Seems to work fine with latest nightly:

![image](https://user-images.githubusercontent.com/495366/50915568-61eb1b00-1439-11e9-80d4-02eebf3270fd.png)

**Comment by adammurdoch** [comment]
Thanks for checking. I'll close this as fixed.
