### ISSUE TITLE
gradle should retrieve a table of contents

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#6973]
long established repository formats especially in linux like debian apt, redhat yum, arch pacman use a table of contents to speed up calculation of new versions on the client without doing server roundtrips.

e.g. debian has:
* https://wiki.debian.org/RepositoryFormat#A.22Contents.22_indices
* https://wiki.debian.org/RepositoryFormat#indices_difference_files_.28diffs.29

gradle is not as bad as maven when using version ranges. but it would be of benefit that maven binary repositories and maven clients support a similar table of content which can be retrieved in one go to resolve e.g. "the current version", or know without server roundtrip that a particular repository does not have this artifact.

**Comment by oehme** [comment]
That's exactly what maven-metadata.xml does and Gradle already uses that.
