### ISSUE TITLE
HI, i am trying to run gradle in one of my laptop and i am facing issue while building the project. Its happening in only certain few systems and i am not sure its because of fire wall or other stuff

### ISSUE THREAD

**Issue by Mithunj44** [gradle/gradle#6982]
HI, i am trying to run gradle in one of my laptop and i am facing issue while building the project. Its happening in only certain few systems and i am not sure its because of fire wall or other stuff.
I tried removing .gradle folder and tried with jdk 7 and also tried with various versions of gradle but still i got the same issue.Please check the logs and let me know if its because of fire wall or system issue.
[daemon-14444.out.log](https://github.com/gradle/gradle/files/2435180/daemon-14444.out.log)

### Context

i am trying to setup work space for gradle related projects.

### Steps to Reproduce (for bugs)

if i execute the below command i got the issue and the logs is attached in this defect.
gradle init  --type java-application

### Your Environment

 * Build scan URL: 
windows 10
Gradle version : 4.10.2
JDK version : 8

**Comment by lacasseio** [comment]
Please use the [user forum](https://discuss.gradle.org/) for those kinds of questions.
