### ISSUE TITLE
gradle is using proxy will i am not using proxy in android studio or on system

### ISSUE THREAD

**Issue by Bilalazam3142** [gradle/gradle#6992]
### Your Environment

 * Build scan URL:

**Comment by Bilalazam3142** [comment]
i need help plz solve this issue

**Comment by Bilalazam3142** [comment]
![screenshot from 2018-10-02 17-29-03](https://user-images.githubusercontent.com/43064011/46348528-b592df00-c668-11e8-9c6d-c3165df2bfc9.png)

**Comment by oehme** [comment]
Gradle doesn't magically decide to use a proxy :) Make sure you didn't configure it in `gradle.properties` or in IDEA.

**Comment by Bilalazam3142** [comment]
I removed proxy from every where even from OS setting and in
gradle.properties there is nothing about proxy
and i deleted the gradle folder and android studio re-downloaded it and now
its fixed
