### ISSUE TITLE
Intellij / Gradle / Java 10 - error in the generated iml file when root project and module LANGUAGE_LEVEL don't match

### ISSUE THREAD

**Issue by dcabasson** [gradle/gradle#6995]
### Expected Behavior
When a root project has a language level of 9 and a module has a language level of 10, the generated module iml file is leading to a crash of Intellij.
This is because the module has 
```<component name="NewModuleRootManager" inherit-compiler-output="true" LANGUAGE_LEVEL="JDK_1_10">```

When Intellij expects JDK_10 according to :
https://github.com/JetBrains/intellij-community/blame/master/jps/model-api/src/org/jetbrains/jps/model/java/LanguageLevel.java

### Current Behavior
Intellij crashes when trying to build the project :
<img width="1146" alt="screen shot 2018-10-02 at 17 41 00" src="https://user-images.githubusercontent.com/1946465/46378669-60f06380-c66a-11e8-8d40-7bfc62d5ba86.png">

### Context
Our project is running into that issue while trying to use Java 9 at the root project and 10 in some submodules.

### Steps to Reproduce (for bugs)
See attached sample project. Generate idea descriptors from root using
```gradlew cleanIdea idea```
open the project in IntellijIDEA and hit the build button. The build crashes with the issue as in the sccreenshot above.

### Your Environment
Gradle 4.10.2
Intellij IDEA 2018.3 EAP

**Comment by dcabasson** [comment]
Sample project reproducing the issue:
[gradle-6995.zip](https://github.com/gradle/gradle/files/2439841/gradle-6995.zip)

**Comment by marcphilipp** [comment]
Thanks for the bug report! Does IDEA's native import work for you? In any case, would you be interested in providing a fix via a PR?

**Comment by jjohannes** [comment]
Using the native import in IDEA is now the recommended way. The `cleanIdea` and `idea` tasks should not be used directly anymore.

Please open a new issue if there is still a problem.
