### ISSUE TITLE
Gradle 5.0-milestone-1 can't resolve some plugin portal plugins

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#6997]
### Expected Behavior
```
plugins {
  id "org.ysb33r.vfs" version "1.0.1"
}
```
to work

### Current Behavior
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/paul/src/local/gradle/gradle5bug/build.gradle' line: 2

* What went wrong:
Plugin [id: 'org.ysb33r.vfs', version: '1.0.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin module from found marker 'org.ysb33r.vfs:org.ysb33r.vfs.gradle.plugin:1.0.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

### Your Environment
Gradle 5.0-milestone-1
Can't produce build scan, build fails too early.

**Comment by marcphilipp** [comment]
Does that work in 4.10.2?

**Comment by eskatos** [comment]
Yes. It is caused by this change https://github.com/gradle/gradle/pull/6774 🤦‍♂️

**Comment by eriwen** [comment]
Good thing we didn't rush this into 4.10.2 eh?

**Comment by oehme** [comment]
The portal mirrors jcenter, so why does adding jcenter to the repo list fix this issue?

**Comment by eskatos** [comment]
> The portal mirrors jcenter, so why does adding jcenter to the repo list fix this issue?

Good question. I don't know exactly how the portal "mirrors" jcenter. The new code from #6774 only look at metadata, maybe the "mirroring" only supports jars or something.

**Comment by oehme** [comment]
@eskatos Can you please take care of this one before RC1?

**Comment by marcphilipp** [comment]
FWIW I just submitted a PR to fix this issue on the Plugin Portal.

**Comment by eskatos** [comment]
This might be a false alarm. I can reproduce the issue with this plugin on 4.10 back to 3.5.

I wonder how it passed for me before. I was migrating some logic from Groovy to Kotlin so I suppose I've seen it work using the `buildscript {}` block and direct plugin artifact dependency.

**Comment by eskatos** [comment]
Closing this issue as invalid as understood in above https://github.com/gradle/gradle/issues/6997#issuecomment-428545254
