### ISSUE TITLE
resolvedConfiguration.resolvedArtifacts doesn't include FileCollectionDependency

### ISSUE THREAD

**Issue by pyrocks** [gradle/gradle#6998]
As the title suggests - I wonder why `resolvedConfiguration.resolvedArtifacts` does not include dependencies of type `FileCollectionDependency`.

### Expected Behavior

I would expect `resolvedArtifacts` to include dependencies of type `FileCollectionDependency`

### Current Behavior

 `resolvedConfiguration.resolvedArtifacts` only includes project and external module dependencies

### Context

I'm writing a plugin which translates every transitive dependency of a given configuration to a task. This should include ALL dependency types.
Since `resolvedArtifacts `does not include `FileCollectionDependency` dependencies I have to manually recurse through the subproject's configuration and collect all such dependencies on my own.
Actual use-case: for code generation purposes I create a Sync task per dependency to extract certain types of files from the jar to a given folder, then the code generation task depends on these tasks.

### Steps to Reproduce (for bugs)

```
plugins {
    id 'java'
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.5' //external module
    compile project(':module1') //project
    compile files('../lib/local.jar') //local file
}


afterEvaluate {
    println "resolved artifacts:"
    configurations.compile.resolvedConfiguration.resolvedArtifacts.each { ra ->
        println "ra=$ra"
        println "ra.class=${ra.class.simpleName}"
        println "ra.file=${ra.getFile()}"
    }

    println "FileCollectionDependency:"
    configurations.compile.dependencies.withType(FileCollectionDependency).each { fd ->
        println "fd=$fd"
        println "fd.class=${fd.class.simpleName}"
        println "fd.files.files=${fd.files.files}"

    }
}
```

prints:
```
...
> Configure project :module2
resolved artifacts:
ra=gson.jar (com.google.code.gson:gson:2.8.5)
ra.class=DefaultResolvedArtifact
ra.file=some-omitted-path\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.5\f645ed69d595b24d4cf8b3fbb64cc505bede8829\gson-2.8.5.jar
ra=module1.jar (project :module1)
ra.class=DefaultResolvedArtifact
ra.file=some-omitted-path\myartifact\module1\build\libs\module1.jar
FileCollectionDependency:
fd=org.gradle.api.internal.artifacts.dependencies.DefaultSelfResolvingDependency_Decorated@433edba9
fd.class=DefaultSelfResolvingDependency_Decorated
fd.files.files=[some-omitted-path\myartifact\lib\local.jar]
...
```

### Your Environment

gradle version 4.10

If this is the _expected behaviour_ I would like to understand why...

**Comment by oehme** [comment]
Don't use resolvedConfiguration, it's outdated and slow. Use incoming.artifacts.

**Comment by pyrocks** [comment]
Thanks for the prompt reply!
I just tried incoming.artifacts and it does include FileCollectionDependency - this is great.

One thing though: I did not see in the documentation (i.e Configuration javadoc) not to use resolvedConfiguration or to favor incoming over it - can you point me to the right page? maybe this method should be `@deprecated` ?

**Comment by oehme** [comment]
Yes, this deprecation is already planned (cc @bigdaz)

**Comment by pyrocks** [comment]
It would be worth mentioning it also in the user guides and plain documentation. 
At least a usage example of incoming.artifacts.
I have been working with gradle for almost a year and had no clue about incoming vs resolvedConfiguration. Moreover-  a lot of stackoverflow and forum answers suggest using resolvedConfiguration.

**Comment by bigdaz** [comment]
@pyrocks Thanks for the feedback. We are indeed planning to de-`@Incubate` the `ResolutionResult` API (`.incoming`) and then later deprecate `ResolvedConfiguration`. We should have done that a couple of releases ago.

**Comment by pyrocks** [comment]
Is it de-incubated enough to use it in production in 4.10?

**Comment by bigdaz** [comment]
> Is it de-incubated enough to use it in production in 4.10?

Yes, the `ArtifactCollection` API is stable enough to use in production. It's been around since v3.4 and is used by the Google Android plugin, so it's not going to be changed without a deprecation cycle.

**Comment by oehme** [comment]
Consider it not incubating.
