### ISSUE TITLE
Changing the resources output directory to classes directory produces a JAR with duplicate entries

### ISSUE THREAD

**Issue by jeankst** [gradle/gradle#7006]
Reopening https://issues.gradle.org/browse/GRADLE-2213 here:

### Expected Behavior
Both classes and resources under build/classes/java/main
JAR produced correctly

### Current Behavior
Both classes and resources are under build/classes/java/main
But produced JAR contains duplicated entries that cannot be opened/extracted by some tools

### Context
Gradle 4.10.2
I run tests that expect resources along with classes

### Steps to Reproduce (for bugs)
  sourceSets {
    main {
      ...
      output.resourcesDir = "build/classes/java/main"
    }
  }

### Workaround
jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

**Comment by marcphilipp** [comment]
What's the reason for changing `resourcesDir` to point to the classes dir?

**Comment by marcphilipp** [comment]
Unless there's a different underlying issue (if so, please comment or open another issue), this works as expected.

**Comment by jeankst** [comment]
- IDEs and Maven copy resources along with classes
- some of our (integration) tests expect resources along with classes
- https://stackoverflow.com/questions/42552581/how-to-copy-resource-files-in-classes-folder-with-gradle

So the following produces a JAR with duplicate entries:
```
apply plugin: "java"

sourceSets {
  main {
    output.resourcesDir = "${buildDir}/classes/java/main"
  }
}

```
Am I doing this wrong? is output.resourcesDir = "${buildDir}/classes/java/main" forbidden with Gradle?

**Comment by GrafDiffusore** [comment]
Hit the same thing.

In my case, resources are Spring context files which to be packaged into result jar. Loading code uses Spring ClassPathContext, so beans loading should work (and works), but having jar twice the size it needs to be doesn't look nice.

**Comment by dpecet** [comment]
Hi, having the same issue, did anybody solved this? 
Using gradle runner, it doesn't put resources to build/classes, after putting 

```
sourceSets {
  main {
    output.resourcesDir = "${buildDir}/classes/java/main"
  }
}
```

having double files in jar

**Comment by Adrodoc** [comment]
Same issue here. Having resources and classes reside in the same output folder is important for unit tests that make use of JPA or WELD. JPA expects the persistence.xml in the same classpath entry as classes and WELD expects beans.xml in the same classpath entry as classes. It would be really nice if Gradle would check for the case where the output dir for resources and classes are equal.
