### ISSUE TITLE
Issue with using `configurations.<configName>.asPath` in `subprojects` block

### ISSUE THREAD

**Issue by micro-focus** [gradle/gradle#7008]
### Expected Behavior
Running `gradlew build` should succeed.

### Current Behavior
Running `gradlew build` results in the following error:

`Cannot change strategy of configuration ':sub1:lightbendFortifyPlugin' after it has been resolved.`

### Context
We're trying to build a Scala project with multiple subprojects. We've configured the root `build.gradle` file to pass a .jar library to the Scala compiler `-Xplugin:` option in the `subprojects` block. However, it seems the property `configurations.lightbendFortifyPlugin.asPath` (which is the absolute path to the .jar file) causes the build to fail with the above error. (The .jar library is the Lightbend Scala translator for Fortify SCA. The ultimate goal here is to scan the Scala project for security vulnerabilities using Fortify SCA. An intermediate step is required to translate the Scala source files into SCA's abstract syntax tree model.)

### Steps to Reproduce (for bugs)
To reproduce the issue, we have a simple project that contains a root `build.gradle` file and a subproject named `sub1` that also contains its own `build.gradle` file. Here is the root `build.gradle` file:

```groovy
apply plugin: 'scala'

ext {
    scalaBinaryVersion = '2.12'
    scalaVersion = '2.12.6'
    fortifyPluginVersion = '1.0.11'
}

allprojects {
    task hello {
        doLast { task ->
            println "I'm $task.project.name"
        }
    }
}

subprojects { subproject ->
    apply plugin: 'scala'

    repositories {
        mavenCentral()
        maven {
            credentials {
                username lightbendUser
                password lightbendPassword
            }
            url = 'https://repo.lightbend.com/commercial-releases/'
        }
    }

    configurations {
        lightbendFortifyPlugin
    }

    dependencies {
        compile("org.scala-lang:scala-library:$scalaVersion") // specify Scala version
        lightbendFortifyPlugin group: 'com.lightbend', name: "scala-fortify_$scalaVersion", version: fortifyPluginVersion, classifier: "assembly"
    }

    tasks.withType(ScalaCompile) {
        scalaCompileOptions.additionalParameters = [
            "-Xplugin:" + configurations.lightbendFortifyPlugin.asPath,
            "-Xplugin-require:fortify",
            "-P:fortify:build=top"
        ]
    }
}
```
Here is the `build.gradle` file for the `sub1` subproject:

```groovy {.line-numbers}
configurations.all { conf ->
    resolutionStrategy {
        // Reduced this from the default of 24 hours, so that dependencies
        // will be refreshed at the start of each developer's working day
        cacheDynamicVersionsFor 12, 'hours'
    }
}
```
The issue is due to the property **`configurations.lightbendFortifyPlugin.asPath`** in the root `build.gradle` file. If this property is replaced with its actual string value (i.e., the absolute path to the .jar file), then the build succeeds.

### Your Environment
I've only tested this on Linux so far.

**Comment by big-guy** [comment]
This is happening because `configurations.lightbendFortifyPlugin.asPath` requires dependencies added to that configuration to be resolved early.  This has a [performance](https://guides.gradle.org/performance/#don_t_resolve_dependencies_at_configuration_time) impact and should be avoided.

It would be nice if we had something built into the `ScalaCompile` task for plugins, but short of that, you can do something like this:
```
    task configureScalaCompile {
        dependsOn configurations.lightbendFortifyPlugin
        doLast {
            tasks.withType(ScalaCompile) {
                scalaCompileOptions.additionalParameters = [
                    "-Xplugin:" + configurations.lightbendFortifyPlugin.asPath,
                    "-Xplugin-require:fortify",
                    "-P:fortify:build=top"
                ]
            }
        }
    }
    tasks.withType(ScalaCompile) {
        dependsOn configureScalaCompile
    }
```

This will delay the resolution of the dependencies until execution time.
