### ISSUE TITLE
Introduce BuildCacheService#init/start

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#7026]
The `BuildCacheService` has a `#close` method which will be triggered at the end of the Gradle build to close possible opened resources.

What I is missing a `BuildCacheService#init/start` method, which will be called only once. When the BuildCache is used for the first time.

### Expected Behavior
There should be a `BuildCacheService#init or start` method which will be triggered by the first artifact which can be stored.

### Current Behavior
There is no `init/start` method.

### Context
Assume that I build my own remote `BuildCacheService`.
For whatever reasons my `BuildCacheService#store` took some time (maybe because my server needs a authentication **all the time** (for each stored artifact)).

I could imagine that I create a "session" ID in the `init/start` method which allows the `BuildCacheService#store` method to call a URL with that session ID.
Which means my build cache server does not to authenticate the user again and again - which leads to faster storing...

### Steps to Reproduce (for bugs)
- 

### Your Environment
-

**Comment by lptr** [comment]
You can use `close()` do clean up, and you can do initialization in your `BuildCacheServiceFactory` implementation.

**Comment by wolfs** [comment]
It should be enough to implement the logic in your `BuildCacheServiceFactory`, right? We have no plans to add an `init/start` method for now.

**Comment by StefMa** [comment]
Thanks guys.
But this leads to another question.

Will the Factory created each time when I do a build (e.g. also when I
execute the help task)?
Or only if Gradle detects that a task from the build may be cached?

**Comment by lptr** [comment]
The factory is called for every build right now, so yes, even when you execute `help`.
