### ISSUE TITLE
Java plugin: shouldn't javadoc task depend on 'compileJava' instead of 'classes'?

### ISSUE THREAD

**Issue by tcfurrer** [gradle/gradle#7027]
Currently the Java Plugin adds a 'javadoc' task which depends on the 'classes' task.  The 'classes' task in turn depends on 'compileJava' and 'processResources'.  But the javadoc tool only needs the .java and .class files, and not other resource files.  

We have a very large project with many gigabytes of resource files.  So processResources is a lot slower than compileJava.  In fact, whenever incremental build can't save the day, processResources runtime dominates.  It seems silly to wait for processResources to complete when all I want to do is build javadocs.

I tried to workaround this using:
    javadoc.dependsOn.remove('classes')
    javadoc.dependsOn compileJava

But for some reason processResources still runs.  It seems if the "remove" doesn't work, or happens too early.

I observed this while using Gradle 4.8 on Linux with Java 8.

The goal here is just to minimize the task dependencies of the javadoc task, for the sake of generating javadocs with minimum runtime (when starting from a clean state).

**Comment by marcphilipp** [comment]
It doesn't depend on any specific task but on all tasks that contribute to the output of the main source set:

https://github.com/gradle/gradle/blob/3126964f14d430a7fdae602572bf41c6a323f474/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L286

As a workaround, you should be able to set

```gradle
javadoc {
    classpath = sourceSets.main.output.classesDirs + sourceSets.main.compileClasspath
}
```

I think multiple gigabytes of resource files is not a typical use case so I'm inclined to leave the default classpath as-is.
