### ISSUE TITLE
Why is the FindBugs plugin still built into Gradle?

### ISSUE THREAD

**Issue by tcfurrer** [gradle/gradle#7028]
The FindBugs tool hasn't been developed since 2015, and there is a newer tool SpotBugs which replaced it.  FindBugs doesn't support any Java version after Java 8.  Now that Java 11 is out, FindBugs is starting to look pretty antiquated.

It seems like Gradle should stop including the FindBugs plugin, and maybe consider to start including the SpotBugs plugin instead.  By including FindBugs in both the releases and the documentation, Gradle is spotlighting a tool that really no new project should even be considering.  Any new project starting up on Gradle could easily be led astray, assuming that because mighty Gradle builds in support for FindBugs that FindBugs must be a good tool to invest in (in 2018 and beyond)... wrong!  Why not give props to SpotBugs, or at least some other code inspection tool that is still being actively developed, and will have support for newer Java versions?

**Comment by big-guy** [comment]
Its deprecated in the next release and recommends Spotbigs https://docs.gradle.org/nightly/userguide/findbugs_plugin.html

We can't rip it out immediately, so it'll be included until 6.0.

**Comment by thc202** [comment]
Related to #6652.
