### ISSUE TITLE
gradle application plugin startScripts: add custom directory to classpath is almost impossible

### ISSUE THREAD

**Issue by samodadela** [gradle/gradle#7033]
My application has a directory structure like this:
```
app
   bin
   conf
   lib
```

What I want to achieve is to have conf/ added to the classpath in the startup script(s). However - whatever I do gradle always adds lib/conf to the classpath:
CLASSPATH=$APP_HOME/lib/conf

I started with this one (no solution unless I put conf in lib/conf - which I don't want):
https://stackoverflow.com/questions/35545405/gradle-add-directory-to-classpath?rq=1
... which directs you to this gradle issue (it's a 'won't fix' and it also doesn't work):
https://issues.gradle.org/browse/GRADLE-2991
... and finally to more creative answers like patching the generated install scripts after they are generated:
https://stackoverflow.com/questions/10518603/adding-classpath-entries-using-gradles-application-plugin

I tried both using startScripts and createStartScripts... It always adds lib/ before conf.
Would it be possible to get a forceClassPath or something so that I don't have to patch the install scripts?

I'm using the latest gradle version 4.10.2 on macosx.

**Comment by lacasseio** [comment]
Unfortunately, we will not provide any classpath feature unless there is a wider pattern around this. You can use a custom template to fulfill the use case. [The Javadocs provide an example.](https://docs.gradle.org/current/javadoc/org/gradle/jvm/application/tasks/CreateStartScripts.html)

If you have a clearer pattern/use case that we can look at with regards to why the `conf` can't be in `lib` and that it's a widespread usage. We can look at modelling this inside the `application` plugin.

**Comment by neworld** [comment]
> You can use a custom template to fulfill the use case. [The Javadocs provide an example.](https://docs.gradle.org/current/javadoc/org/gradle/jvm/application/tasks/CreateStartScripts.html)

I did not try, but by looking at the template the `lib` in the classpath is hardcoded. Is there any particular reason for forcing `lib` directory? For example, I prefer having a flat structure for my very small application (script + jar)

**Comment by xerus2000** [comment]
Agree with @neworld here. Hardcoding with no option to change doesn't seem reasonable.

**Comment by xerus2000** [comment]
I have a slightly different issue that also relates to missing configuration options: I don't want to hide my start-scripts in a "bin" directory but rather have them in the toplevel. Modifying the template for that is quite a hassle.

**Comment by Stingray42** [comment]
Why is this closed?

**Comment by Stingray42** [comment]
Why is this closed?

**Comment by Blacklands** [comment]
I'm also wondering why this is closed. This issue still persists.
There's now a way to change the executable directory (default `bin`), so why is `lib` still being hardcoded?
