### ISSUE TITLE
Windows OSError: Can not read file in context: .gradle\4.10.2\fileHashes\fileHashes.lock

### ISSUE THREAD

**Issue by daggerok** [gradle/gradle#7043]
### Expected Behavior

Should just works, because with same project config on linux CI systems no similar problem and I have never faced with them previously also on my mac

### Current Behavior
Don't know why, but this error happening on my wondows 10 system:

```bash
OSError: Can not read file in context: D:\gitlab-runner\.gradle\4.10.2\fileHashes\fileHashes.lock
```

### Context

Some issues with lock files on windows system are available.
I'm facing with this kind of issues not first time on windows system and locks in project local folder `.gradle`

### Steps to Reproduce (for bugs)

using gradle docker compose plugin `plugins { id 'com.avast.gradle.docker-compose' version '0.7.1' }`, during execution composeUp task next error is happening:

```bash
> Task :assemble UP-TO-DATE

> Task :composeUp FAILED
Building crew-buddies-guides
[9244] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 97, in create_archive
  File "tarfile.py", line 1978, in addfile
  File "tarfile.py", line 255, in copyfileobj
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 282, in build
  File "compose\project.py", line 378, in build
  File "compose\service.py", line 1067, in build
  File "site-packages\docker\api\build.py", line 154, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: D:\gitlab-runner\.gradle\4.10.2\fileHashes\fileHashes.lock

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeUp'.
> Process 'command 'docker-compose'' finished with non-zero exit value -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed
```

### Your Environment
windows 10
gradle 4.10.2
I'm using gradle wrapper

```bash
./gradlew -version                                                                                                                                                                                            /cygdrive/d/gitlab-runner

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Windows 10 10.0 amd64
```

 * Build scan URL: 
https://gradle.com/s/eqopywvldcude

**NOTE 1**
It's not related to cygwin, in cmd shell same error is happening even if I'm removing .gradle folder before `gradlew composeUp` command

**NOTE 2**
I also can suspicious gradle daemon. Even if I have in my local project `gradle.properties` file next property key=value: `org.gradle.daemon=false` I can see, that after gradlew assembe task execution, daemon was here:

```bash
{ gitlab-runner } master » ./gradlew clean                                                                                                                                                                                               /cygdrive/d/gitlab-runner
> Task :clean UP-TO-DATE
> Task :docs:clean UP-TO-DATE

BUILD SUCCESSFUL in 6s
2 actionable tasks: 2 up-to-date
{ gitlab-runner } master » ./gradlew ass                                                                                                                                                                                                 /cygdrive/d/gitlab-runner
> Task :assemble UP-TO-DATE
> Task :docs:assemble UP-TO-DATE

BUILD SUCCESSFUL in 5s
{ gitlab-runner } master » ./gradlew --stop                                                                                                                                                                                              /cygdrive/d/gitlab-runner
Stopping Daemon(s)
1 Daemon stopped
```

**Comment by oehme** [comment]
Please include a reproducible example project.

**Comment by daggerok** [comment]
Hello, @oehme 

Unfortunately, after few days, I had tried run same project with no changes again and it's working fine these 2 days. I cannot reproduce that issue at th moment, so I don't know if there are really any reasons to send you an example repo, but I will do that for future cases if they will happens again: https://github.com/daggerok/gradle-windows-issue

---
Regards,
Maksim

**Comment by oehme** [comment]
The problem is probably that your docker container tries to read files in the gradle cache directory (`.gradle`), which it shouldn't try to access. It's only supposed to serve the generated documentation, right? 

The lock files in the cache are locked by the Gradle daemon. That is intentional and part of Gradle's cross-process safety protocol.

**Comment by daggerok** [comment]
well, you absolutely right about `.dockerignore` and `.gradle`. It must be ignored and it was already there...

**Comment by oehme** [comment]
Then I don't understand why Docker still tries to read it.

**Comment by daggerok** [comment]
Hello, just decide drop here few lines about an issue: after few reboots and cleaning a repo described errors  wasn't appear anymore. Seems like it was some local / windows issue
