### ISSUE TITLE
Prefer declaration is inconsistent for usage vs publishing

### ISSUE THREAD

**Issue by OdysseusLives** [gradle/gradle#7046]
When using `prefer` for a dependency, a local build will resolve to the preferred version when defined as:

**Declared together**
```
dependencies {
    api('tree:acacia') {
        version {
            require '[1.2, 2.0)'
            prefer '1.5'
        }
    }
}
```
or  as

**Declared separately**
```
dependencies {
    api('tree:acacia') {
        version {
            require '[1.2, 2.0)'
        }
    }
    api('tree:acacia') {
        version {
            prefer '1.5'
        }
    }
}
```

However, when publishing with the `ivy-publish` and `maven-publish` plugins, the dependency must be declared separately, or only the version range is published.

### Expected Behavior
It is expected that if the dependency definition works sufficiently to resolve to the preferred version when `dependencyInsight` is used, then this dependency preference is also published. 

It is unexpected for both configurations to resolve in `dependencyInsight`, but only the declared separately configuration to propagate the preferred dependency version. 

### Steps to Reproduce (for bugs)
See the following projects:
**Defined in the same block**
[Sample project here](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/require-prefer/docs/publishing/maven-publishing-when-in-same-block-contains-only-range/input/build.gradle)
with
```
> Task :dependencyInsight
tree:acacia:1.5
   variant "compile" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-api
      org.gradle.component.category = library (not requested)
   ]

tree:acacia:[1.2, 2.0) -> 1.5
\--- compileClasspath
```

with published pom file from `./gradle publish`:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>tree</groupId>
  <artifactId>blue-palo-verde</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>tree</groupId>
      <artifactId>acacia</artifactId>
      <version>[1.2, 2.0)</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Defined in different blocks**
[Sample project here](https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/require-prefer/docs/publishing/maven-publishing-when-in-different-blocks-contains-prefer-and-range/input/build.gradle)
with
```
> Task :dependencyInsight
tree:acacia:1.5
   variant "compile" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-api
      org.gradle.component.category = library (not requested)
   ]

tree:acacia:1.5
\--- compileClasspath

tree:acacia:[1.2, 2.0) -> 1.5
\--- compileClasspath
```

with published pom file from `./gradle publish`:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>tree</groupId>
  <artifactId>blue-palo-verde</artifactId>
  <version>1.0</version>
  <dependencies>
    <dependency>
      <groupId>tree</groupId>
      <artifactId>acacia</artifactId>
      <version>1.5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>tree</groupId>
      <artifactId>acacia</artifactId>
      <version>[1.2, 2.0)</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

### Context
It looks like this is related to #6610, but also involves publishing.

### Your Environment
Using nightly Gradle v5.0-20181004235847+0000

**Comment by ljacomet** [comment]
Closing as won't fix / obsolete:
* Mapping of rich version to Maven or Ivy will never be complete.
* Publication of _resolved_ versions is now an option.
