### ISSUE TITLE
Conflict resolution can be bypassed, resulting in arbitrary version chosen

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#7050]
I've found a situation in which conflict resolution is bypassed, even though there are two versions that should be considered.

Consider a repository with the following dependency structure:

```
org:one:1.0
\--- org:control:1.0
     \--- org:dep:2.5
org:two:1.0
+--- org:control-1.2-bringer:1.0
|    \--- org:control:1.2
|         \--- org:dep:2.5
\--- org:dep-2.0-bringer:1.0
     \--- org:dep:2.0
```

### Expected Behavior

Depending on `org:one:1.0` and `org:two:1.0` should resolve to a dependency on `org:dep:2.5` via conflict resolution between `2.5` and `2.0`.

### Current Behavior

If the dependencies are arranged just as described above (the order of the two `org:two:1.0` dependencies matter!), then `org:dep:2.0` will be selected and no conflict resolution will even take place (as verified with a debugger).

Debugging this, this is what is roughly happening:

1. `DependencyGraphBuilder#traverseGraph` is called
1. Edge from `org:control:1.0 -> org:dep:2.5` is visited, selector for `org:dep:2.5` created is resolved. `ModuleResolveState` for `org:dep` has one selector and that version is selected.
1. Later, when the `org:control-1.2-bringer` node is being resolved, the `-> org:control:1.2` dependency is visited
1. The `org:control:1.0` selector is `release()`d because the dependency has been superseded by `1.2`. This removes the `org:dep:2.5` selector from `org:dep`'s `ModuleResolveState`.
1. `org:dep:2.0` is visited (from `org:dep-2.0-bringer:1.0`) and this adds the `org:dep:2.0` selector to the `org:dep` `ModuleResolveState`. That version is then 'selected' in the `ModuleResolveState`, as there's only one selector available. So far so good.
1. The `org:control:1.2 -> org:dep:2.5` dependency is finally visited in the end. When creating the `EdgeState`, the *old* `org:dep:2.5` selector (created in step 2) is retrieved from the `ResolveState`.
1. When it gets to `performSelectionSerially`, the selector for `org:control:1.2 -> org:dep:2.5` is *never visited* because `selector.isResolved()` (having been resolved earlier in step 2). Thus, `2.0` remains the selected version in `org:dep`'s `ModuleResolveState`!

### Context

We've hit this on a number of projects where we tried to use the `latest` resolution strategy, as opposed to `strict` (aka `failOnVersionConflict()`) + `nebula.dependency-recommender` + `dependencyRecommendations { strategy OverrideTransitives }`.

### Steps to Reproduce (for bugs)

I'm providing an actual failing test: https://github.com/gradle/gradle/pull/7049

### Your Environment

 * Build scan URL: n/a

**Comment by ljacomet** [comment]
Thanks for the report and the reproducible test case. I will be adding a fix to your PR so that it can be merged.
