### ISSUE TITLE
Gradle 5.x release candidates not available on SDKMAN

### ISSUE THREAD

**Issue by marc0der** [gradle/gradle#7051]
For some time Gradle has been publishing their releases (and release candidates) to SDKMAN. One of our users recently noticed that the `5.0-milestone-1` release was not available on SDKMAN. On further examination, it turns out that _no_ 5.0* releases have been published to SDKMAN at all.

Is this intentional? If not, would it be possible to set this right? Of course, as always I'm more than happy to help getting this resolved.

**Comment by big-guy** [comment]
It's intentional. There hasn't been a release candidate for 5.0.  `5.0-milestone-1` is just a named nightly that we could point people to. It's not a stable release or release candidate. We've only done this for major bumps as a sort of preview.

**Comment by marc0der** [comment]
No probs then. Thanks for clarifying.
