### ISSUE TITLE
UrlRepositoryDescriptor throws NPE in case of null URL 

### ISSUE THREAD

**Issue by facewindu** [gradle/gradle#7057]
We received a [user bug report](https://groups.google.com/a/gradle.com/forum/#!topic/gradle-enterprise-team/aNIk5uMZdlM) about a NPE when using `--scan`.
Analysis shows that this comes from the URL of an plugin-added ivy repository being null, which is valid.

### Expected Behavior
No NPE thrown when a repository contains an null URL.

### Current Behavior
When using the build scan plugin, and requesting the RepositoryDescriptor of such a repo, a NPE is thrown by the ImmutableMap.Builder (that does not allow null values)

### Steps to Reproduce (for bugs)
Checkout https://github.com/square/sqldelight
Run `./gradlew tasks --scan`
=> NPE when publishing the build scan plugin.

**Comment by facewindu** [comment]
It is possible to define a maven/ivy repo with no URL; and even no artifactUrls (maven) or artifact/ivy patterns (ivy)
Ivy repos will get the default artifact / ivy patterns.
Maven repos will have empty artifact urls.
See https://github.com/gradle/gradle/commit/454f7f26a3511e15df06e3ad2cfea28e3445ef8a

I'm questioning the usefulness of that. To me, those repos are useless then, and I was expecting Gradle to fail.

@melix @bigdaz, what's your opinion on this?

**Comment by facewindu** [comment]
https://github.com/gradle/gradle/blob/fd5b31325073b385f42a7339f81096a47ded0f63/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultMavenArtifactRepository.java#L210
https://github.com/gradle/gradle/blob/79442a97f098374ec65ea6d4b37d72ea3f2df6b2/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/DefaultIvyArtifactRepository.java#L204 (edited)

I see what happens
in real life, when creating a resolver from a repo
things blow if there is not a properly built url to resolve things
but the build scan plugin capture what was set as the properties of the repo, no matter if it makes sense or not
The validation happens ‘later’ when Gradle actually needs the repo.

@melix @bigdaz Can we move the validation earlier ? (when calling `createDescriptor`)
cc @ldaley

**Comment by facewindu** [comment]
I tried validating things earlier. [This seems to work well](https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_Stage_ReadyforMerge_Trigger&branch_Gradle_Check=fg%2Frepository-descriptor-url-check&tab=buildTypeStatusDiv)

**Comment by bigdaz** [comment]
I'd be fine with moving validation _earlier_ but I'm not sure that `createDescriptor()` is the right place. This is only called when constructing the build operation descriptor: it would feel wrong for [`ResolutionAwareRepository`](https://github.com/gradle/gradle/blob/d34a03c6a28be37e7ee9dd2556c471a38eb3ba94/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/ResolutionAwareRepository.java#L22-L33) to _not_ validate when `createResolver()` is called.

So at some point when the repository is no longer mutable, we'd need to do validation. This could be as simple as validating for the first of `createResolver()` and `getDescriptor()`.

**Comment by facewindu** [comment]
That's what I did

**Comment by ldaley** [comment]
> So at some point when the repository is no longer mutable

IIUC it's always mutable, so we need to validate each time it is “used”.  Currently, this is twice (one for resolver, one for descriptor). We could relatively easily change things around so that `ResolutionAwareRepository` returns an object that _holds_ a resolve and knows how to create a descriptor and we perform validation _once_ when creating this.

Potentially later we can look at caching this object and reusing when the repository hasn't changed which is 99.999% of the time.

**Comment by facewindu** [comment]
closing as merged
