### ISSUE TITLE
 Gradle should always respect the extra attributes when selecting artifacts transforms chains

### ISSUE THREAD

**Issue by noproxy** [gradle/gradle#7061]
### Expected Behavior

When selecting artifacts transforms chains, Gradle should always respect the extra attributes.

### Current Behavior

Only when there is one-step transform matched,  Gradle will respect the extra attributes. But when searching for chains transforms, Gradle ignores the extra attributes requirement of the transform.

### Context

Given these three transforms:

```
Transform1: artifactType=xbundle,  buildType=default ->  artifactType=aar, buildType=debug
Transform2: artifactType=xbundle,  buildType=default ->  artifactType=aar, buildType=release
Transform3: artifactType= aar -> artifactType=classes
```

Providing a maven dependency in the 'implementation' configuration, likes this:

```
MavenDependency {artifactType=xbundle,  buildType=default}
```

Then, we try to get the artifacts with attributes ```artifactType=aar, buildType=release```.

```java
final Configuration implementation = project.getConfigurations().getByName("implementation");
final Configuration test = project.getConfigurations().create("test");
test.setCanBeResolved(true);
test.extendsFrom(implementation);

test.incoming.artifactView(config -> {
                        config.attributes(container -> container.attribute(ARTIFACT_TYPE, "aar"));
                        config.attributes(container -> container.attribute(BUILD_TYPE, "release"));
                    }).getArtifacts();
```

Gradle should search a chain to transform from ```{artifactType=xbundle,  buildType=default}``` to ```{artifactType=aar,  buildType=release}```,
And the ```Transform2``` with one depth just works! So gradle just select it, and no conflict occurs! Up to now, artifacts transforms work fine.

### Steps to Reproduce (for bugs)

But then, if we try to get the artifacts with attributes ```artifactType=classes, buildType=release```.

There is no one-step transform works, and Gradle will find some candidates can produce 'artifactType=aar'. That's

```
Transform3: artifactType= aar -> artifactType=classes
```

Then, Gradle searches for transforms to produce ```artifactType=aar``` **(Note: gradle will ignore the buildType attribute limit)** to create chains. And there are two:

```
1. artifactType=xbundle,  buildType=default ->  artifactType=aar, buildType=debug
2. artifactType=xbundle,  buildType=default ->  artifactType=aar, buildType=release
```

So, gradle find two chains to get artifacts like ```artifactType=classes, buildType=release```:

```
1. artifactType=xbundle,  buildType=default ->  artifactType=aar, buildType=debug
    - artifactType= aar -> artifactType=classes
2. artifactType=xbundle,  buildType=default ->  artifactType=aar, buildType=release
    - artifactType= aar -> artifactType=classes
```

And, gradle will throw ```AmbiguousTransformException``` exception because gradle unable to choose one chains from two path with the same depths.

But I think only the 2nd chains can produce the requested artifacts. Gradle ignore the extra attribute requirement of the transformer when search for chains transforms. 

### Your Environment

Gradle 4.10.2

**Comment by melix** [comment]
Indeed it should fail, and doing this on a project using `java-library` properly fails, so I _think_ the error is likely in the Android plugin.

**Comment by oehme** [comment]
@ducrohet You might want to make "buckets" like `implementation` non-resolvable so users don't run into errors like the one above.

**Comment by noproxy** [comment]
Sorry for confusion.

My code is using the ```test``` configuration created by myself. I wrote ```implementation``` wrongly.

**Comment by noproxy** [comment]
@oehme Can reopen this issue? The ```implementation cannot be resolved``` is not the crux of the problem. I have fixed the issue details.

**Comment by noproxy** [comment]
I created a demo project to produce the issue. https://github.com/noproxy/gradle-issue-7061

**Comment by oehme** [comment]
Thanks for the clarification. The problem here is that we only consider the end result of the transform chain for matching. Since you have a transform from `aar->classes` that doesn't preserve `buildType`, the resulting variants both just have the `classes` attribute and are thus ambiguous.

I think this is a general limitation of the transformation infrastructure - it's not a partial transformation of the attributes, but a total replacement. @melix this seems to be an extensibility problem, since plugin authors can't be expected to know about all other attributes in existence.
