### ISSUE TITLE
Surface tooling API model requests in IDE 

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#7071]
Late in the 4.x line, we added a "Realize task <task path>" build operation.  Because of the way build operations are turned into progress events, the IDE sees these build operations too:

![image](https://user-images.githubusercontent.com/5387972/46618203-ef426a80-caec-11e8-95d3-01f53863aa01.png)

For some model imports, we end up realizing all tasks.  e.g., to get a `GradleProject`, we need realized tasks to get group and description.  Since this happens after we've configured the build, all of the "realize task" messages appear to be top-level events that aren't very interesting. 

Short of hiding these events, it would be better to group them inside their model requests instead.  As a side effect, this would make it possible to see which model requests are expensive.

### Expected Behavior

Model requests are a separate top level event like "Load build" or "Configure build"

### Current Behavior

Activity related to model requests is not visible.

### Steps to Reproduce (for bugs)

Import gradle/gradle into IntelliJ.  Look at the "Build" tab.

### Your Environment

This happens everywhere.

**Comment by ldaley** [comment]
I had been wondering why these showed up at the top level.
