### ISSUE TITLE
Project dependency in custom configuration of Gradle Plugin doesn't invoke assemble tasks

### ISSUE THREAD

**Issue by Mauin** [gradle/gradle#7075]
In our repository we're developing a static analysis tool plus its companion Gradle Plugin. The Gradle Plugin is defined as a composite build to be able to develop it easier in our setup. 
In addition the Gradle Plugin exposes a custom configuration that can be used to override its default dependencies. We use this in development to exchange modules with the local version instead of versions from remote to be able to use local changes in the dependencies directly.

When defining this overriding dependency as a `project` dependency the project dependency is not running the assemble tasks before actually calling the tasks defined by the Gradle Plugin which results in the tasks failing due to missing dependencies at runtime. 

### Expected Behavior
Defining a project dependency in a custom configuration of a composite build adds its assemble tasks as task dependencies.
`detekt(project(":detekt-cli"))`

### Current Behavior
The tasks seem to be not added as task dependencies and task execution fails at runtime due to missing dependencies.
However in the custom task classpath the JAR of the project dependency is defined, but seems to be nonexistant.

```
> Task :detekt-api:detekt FAILED
Classpath:
/dev/detekt/detekt-cli/build/libs/detekt-cli.jar // does not exist at this point
[....]

Error: Could not find or load main class io.gitlab.arturbosch.detekt.cli.Main
```

### Context
This is currently requiring us to manually add the required project assemble tasks as task dependencies (https://github.com/arturbosch/detekt/pull/1207)

_Removing the composite build from the build setup results in the build succeeding without any changes to the dependency setup._

### Steps to Reproduce (for bugs)
Check out: https://github.com/mauin/detekt/tree/gradle_project_dependency_issue_composite_build
Run: ./gradlew clean detekt
--> Build fails due to missing dependencies

See: https://github.com/Mauin/detekt/tree/gradle_project_dependency_issue_no_composite_build for a version without the composite build which succeeds with the same tasks.

### Your Environment
Gradle v4.10.2
 * Build scan URL: Build scans are not supported for this build due to a build plugin composite substitution.

**Comment by ghilainm** [comment]
I have the same kind of issues.

I have composite build with two projects. One is building a jar using the java-library plugin and the other one define custom configuration and dynamically create tasks based on the configuration resolution to unpack jar produced by the first project.

The JAR of the first projects are not yet build when the tasks to unpack it is triggered by the composite build.
