### ISSUE TITLE
Print file:// URL on CLI when HTML dependency report task has finished

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#712]
### Expected Behavior

When generating the HTML dependency report it would make sense to directly print the url of the generated html file on the build output as a user usually directly wants to see the report afterwards.
### Current Behavior

`apply plugin: 'project-report'` in `build.gradle` then run `dependencyReport`
This just prints `BUILD SUCCESSFUL` without any URL to the actual report.
### Context

I want to be able to quickly view the report after I run the `dependencyReport` task and I should not have to guess where it is under the `$buildDir`

**Comment by johnmartel** [comment]
All 4 project reports do not display a link to the generated file. I guess this change could be done for all of them:
- `taskReport`
- `propertyReport`
- `dependencyReport`
- `htmlDependencyReport`

**Comment by eriwen** [comment]
👍 @johnmartel you want in on this?

**Comment by johnmartel** [comment]
Yes, I already forked the repo and currently working on the solution.

It's pretty simple, although I have yet to find how to test for interactions with the project logger for my unit tests.

**Comment by eriwen** [comment]
@johnmartel If you provide a partial PR and explain the test you want to write, I think we can be of some assistance.

**Comment by johnmartel** [comment]
See https://github.com/gradle/gradle/pull/762

**Comment by johnmartel** [comment]
I completed the changes. I also added a fix (see b1ea13d) to what I noticed was a bug in the Javadoc for `org.gradle.api.reporting.dependencies.HtmlDependencyReportTask`.
