### ISSUE TITLE
Public API to retrieve build start time 

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#7138]
### Expected Behavior
a public API that allows me to retrieve build start time information for metrics purposes

### Current Behavior
non existent

### Context
`ProfileListener` and the whole of org.gradle.profile is not public API, and as such Gradle makes no promise to keep these APIs or their behavior stable. There were changes for Gradle 5 that prevented us for using it in https://github.com/nebula-plugins/gradle-metrics-plugin and one suggestion was to implement our own listeners (https://github.com/nebula-plugins/gradle-nebula-integration/issues/31#issuecomment-422319185)

We did this and it works somehow as expected. However, we are missing the important piece of the time when the build started. Currently we are only able to track it based on when our plugin is getting applied (https://github.com/nebula-plugins/gradle-metrics-plugin/pull/29/files#diff-b9e461c3579c046658f8b39cd3059fdbR75).

It would be nice if we could get a public API to retrieve at least the timing information so our metrics become more accurate.

**Comment by bigdaz** [comment]
In lieu of a public API for this, you could use `org.gradle.internal.scan.time.BuildScanBuildStartedTime`: this internal API is used by the Gradle build scan plugin and so is likely to be stable over time.

You should be able to get an instance via `project.services.get(BuildScanBuildStartedTime)`, or via constructor injection.

**Comment by rpalcolea** [comment]
Hi @bigdaz! yeah we will do that for now. Hopefully we can get a public API to prevent potential breaking changes in case build scans change in the future. 

Thanks again for the input!
