### ISSUE TITLE
[Modular Gradle] Start Gradle with the necessary Java modules

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#722]
For some features the Jigsaw module `java.xml.bind` is required. This is not exposed imported by default, see https://bugs.openjdk.java.net/browse/JDK-8157670 . Currently we do not know if more modules are required.

We need to add the modules to the JVM running Gradle/doing testing via the JVM option `-addmods`.

**Comment by plotters** [comment]
Are there plans to implement something like this?

`./gradlew` build --add-modules=java.activation`

This would be great in cases migration to java 9 modules is not yet feasible to make the project compile

**Comment by tbroyer** [comment]
Similarly, continuous build could use `com.sun.nio.file.SensitivityWatchEventModifier` and `com.sun.nio.file.ExtendedWatchEventModifier` on Java 9 by using the `jdk-unsupported` module, to remove the current caveats (https://docs.gradle.org/4.2/userguide/continuous_build.html#sec:continuous_build_limitations_jdk9)

See https://stackoverflow.com/q/46590600/116472 and https://github.com/gradle/gradle/commit/0e96ab66a46ee1c201cf63980da4be8d27268ff5

**Comment by jjohannes** [comment]
Gradle 7.0 runs on JDK16 and has support to work with (compile, test, run) Java Modules. I think there is nothing left to do here. Please open a new issue for what concrete is missing in Gradle 7+ if any.
