### ISSUE TITLE
Fix annotation processing integration tests on Java 9

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#725]
InProcessGroovyCompilerIntegrationTest and InProcessJavaCompilerIntegrationTest which fail for Annotation Processing with java.lang.RuntimeException: Annotation Processor Classpath is contaminated by Gradle ClassLoader at `com.test.SimpleAnnotationProcessor.process(SimpleAnnotationProcessor.java:22)`

Current state of analysis:
When compiling Java classes on Java 9 with an embedded Java compiler (non-forking) then the Gradle classes are accessible from the Annotation Processor. This is because `javac` is always loaded by `jdk.internal.loader.ClassLoaders$AppClassLoader` since we only load `javax.tools.ToolProvider` via the `isolatedClassloader` which then loads the `JavaCompiler` via `jdk.internal.loader.ClassLoaders$AppClassLoader`. I did try to load the implemenation of `JavaCompiler` via `isolatedClassloader` but it seems to that for this to work `FilteringClassloader` needs to be able to provide Java 9 modules via `getServicesCatalog` which I do not know how to implement.
All this happens in `JdkTools`.

**Comment by oehme** [comment]
This has been fixed https://github.com/gradle/gradle/pull/5563/commits/375ad7314ac4fb4713d38c21daf532920c34dc52
