### ISSUE TITLE
Allow user code to submit progress logs through BuildOperations API

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#730]
### Context
[Forum Post](https://discuss.gradle.org/t/can-gradle-team-add-progresslogger-and-progressloggerfactory-to-public-api/18176)

Many users would like to send their own messages to the progress logger. Also see elastic/elasticsearch#18935

**Comment by eriwen** [comment]
Possibly related: https://github.com/gradle/gradle/commits/pm-build-operations-event-bus

**Comment by ajoberstar** [comment]
👍

**Comment by eriwen** [comment]
This is sort of done, but plugins cannot submit progress logs yet. This issue should be broken up and the goal stated in the description address for v4.1

**Comment by eriwen** [comment]
This is already available using the new Worker API, which is being documented for Gradle 4.1. Closing as duplicate

**Comment by rjernst** [comment]
@eriwen This is really not solved by the worker api. That assumes all tasks can/should be converted to use the worker api. But, for example, wrapping an existing ant task which forks multiple processes, and wanting to update the gradle status for those processes is not covered. It also does not cover running a complex testing script through a vagrant virtual machine with exec. As a custom task designer, I can capture and understand the output from these external processes, but I need a way to pass the status to gradle for output in the status line.
