### ISSUE TITLE
Updating gradle from 3.0.1 to 3.2.0, ''failed to run Gradle Findbugs Worker'' when building gradle.

### ISSUE THREAD

**Issue by ZiranLi** [gradle/gradle#7309]
I justed updated Gradle to 3.2.0 from 3.0.1. When I tried to build the project again, I got the exception: 
''Execution failed for task ':app:findbugs'.
> Failed to run Gradle FindBugs Worker
   > Process 'Gradle FindBugs Worker 10' finished with non-zero exit value 1''

When I degrade the gradle to 3.0.1, I can successfully build the gradle. 

### Expected Behavior

I think that might be something with my Findbugs plugin? The classed file location might changed after upgrading gradle.
### Your Environment

 * Build scan URL: 
Android Studio: 3.1.4
Gradle:3.0.1 to 3.2.0

**Comment by oehme** [comment]
I assume you mean "Android Gradle plugin" 3.2. Please open Android issues on the Android issue tracker.
