### ISSUE TITLE
Provide method to get relative file path from InputFileDetails

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#731]
Plugin authors like myself need incremental tasks that preserves source directory structure in the output.

For example:

Input

```
style.css
vendor/bootstrap.css
```

Output

```
$buildDir/style.min.css
$buildDir/vendor/bootstrap.min.css
```

I would like [this test](https://github.com/eriwen/gradle-digest-plugin/blob/master/src/test/groovy/com/eriwen/gradle/DigestPluginFunctionalTest.groovy#L59) to pass using `IncrementalTaskInputs`. See [here](https://github.com/eriwen/gradle-digest-plugin/blob/master/src/main/java/com/eriwen/gradle/Digest.java#L63) also.

**Comment by adammurdoch** [comment]
I would add methods to ask for filtered `FileCollection` and `FileTree` instances, that contain the changed/added/removed input files. This way, I can use the same APIs to iterate over the input for both incremental and non-incremental execution.

I would avoid just adding more stuff to `InputFileDetails`.
