### ISSUE TITLE
Gradle does not honor testng verbose setting

### ISSUE THREAD

**Issue by tpott519** [gradle/gradle#7310]
When the testng XML file specifies the verbose level it is honored when running via Eclipse (the reports contain the logging) but when run via gradle it is not honored (the reports do not contain the logging).

### Expected Behavior
The verbose level should be honored when logging.

### Current Behavior
If the testng Reporter.log(String logMessage) method is called this is honored when the tests are run via gradle (they show up in the emailed report html file). If testng.Reporter.log(String logMessage, int reportingLevel) is called with any level and the verbose setting is 10 or any value for that matter, the logging using that method does not show up in the log.

### Context
Missing logging in our testng when running via gradle (which is how we want to run our tests).

### Steps to Reproduce (for bugs)
Using eclipse right click on the testng.xml file and run as testng. Then open the emailable-report.html via the file system (it will be in the root folder under test-output) - Notice there are two log entries - one using each method of logging stated above. Now go to the command line and run ./gradlew build. Look in the build/reports/testng/emailiable-report.html and notice only the one log entry is present (the log entry not containing the log level). Open build/reports/testng/index.html using an editor and search for "verbose" - verbose has a value of zero. Open test-output/index.html and search for "verbose" and notice verbose has the value set in testng.xml. 

### Your Environment
Windows 10
Git-bash that came with git version 2.18.0.windows.1
Eclipse 4.8
gradle 4.9
Java 1.8.181
testng 6.14.3

[Files.zip](https://github.com/gradle/gradle/files/2462867/Files.zip)

**Comment by sky137586** [comment]
I'm facing the same issue. Any update will be appreciated.
