### ISSUE TITLE
Cause: lateinit property output has not been initialized

### ISSUE THREAD

**Issue by cuijianzhi** [gradle/gradle#7314]
It worked well with gradle 4.10.2 on android studio ,but found this error when i upgrade to 5.0 at sync .On android java language，not kotlin.

**Comment by big-guy** [comment]
Hi @cuijianzhi, 

We'll need a little more information about what you're talking about.  A reproducible example is always best, but a description of what you're doing, code snippets, what you're seeing or stacktraces also help.

I'm closing this until we get more information.

**Comment by cuijianzhi** [comment]
> Hi @cuijianzhi,
> 
> We'll need a little more information about what you're talking about. A reproducible example is always best, but a description of what you're doing, code snippets, what you're seeing or stacktraces also help.
> 
> I'm closing this until we get more information.

here is some logs:
[bug.txt](https://github.com/gradle/gradle/files/2541288/bug.txt)

**Comment by cuijianzhi** [comment]
> Hi @cuijianzhi,
> 
> We'll need a little more information about what you're talking about. A reproducible example is always best, but a description of what you're doing, code snippets, what you're seeing or stacktraces also help.
> 
> I'm closing this until we get more information.

It's disappear when new version AS release( Android Studio 3.4 Canary 3
Build #AI-183.3975.18.34.5112304, built on November 6, 2018)and i upgrade it.
