### ISSUE TITLE
Replace module replacement rules with capabilities and substitution rules

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7325]
The functionality provided by "Module Replacement Rules" is a subset of that provided by "Capabilities". We should consider:
a) Changing the implementation of module replacement rules to define capabilities and dependency substitution rules under the hood. This would allow us to simplify our conflict resolution code.
b) Deprecate module replacement rules, documenting the recommended replacement.

**Comment by melix** [comment]
Did you have a chat with @ljacomet ? We discussed precisely this today :D

**Comment by bigdaz** [comment]
I saw the conversation on Slack. I still can't see a good reason not to do both of the changes I suggested above:
>a) Change the implementation of module replacement rules to define capabilities and dependency substitution rules under the hood. This would allow us to simplify our conflict resolution code.
>b) Deprecate module replacement rules, documenting the recommended replacement.

I think proliferation of different mechanisms to control dependency resolution behaviour is going to lead to confusion, and making it simpler should be a priority for us.

**Comment by ljacomet** [comment]
I thought the same initially, but sadly the _applies only in case of conflict_ is the hardest thing to model.
Especially when the to be replaced module appears first in the graph and then the conflicting one appears. We have then to restart pretty much all incoming edges to that node. And that's definitely not an easy task with our resolution algorithm as it stands.

**Comment by bigdaz** [comment]
OK, so using capabilities + substitution doesn't give  the exact behaviour of module replacement, since the capabilities will produce a conflict which must then be explicitly fixed with a substitution rule. In that case, we can't replace the implementation of module replacement rules, but we could simply deprecate them and recommend a mechanism using capabilities.

I doubt very many users are actively using module replacement rules, since they are so restricted in scope. And I think the benefits of simplification outweigh the pains of migration.
