### ISSUE TITLE
Gradle no longer support proper location of artifacts when multiple repositories is provided

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#7336]
@faiyat commented on [Wed Oct 10 2018](https://github.com/gradle/gradle-native/issues/889)

Gradle allow to specify multiple repositories for dependency resolution.  However, it always tries to look for all dependencies in the first repository.  If fail the build immediately if it couldn't find it there, instead of searching through all the repositories.

### Expected Behavior
It should continue to search all repositories if it couldn't find in the first one, then second, etc.  The build should only fail after all repositories have been searched and not find in any of them.

### Current Behavior
The artifact exists in the 2nd repository.  But the build failed immediately after it fail to find it in the 1st one.

### Context
We use nexus to store our internally created artifacts.  We also proxy'd all public repositories in nexus as well, such as maven central, cloudera, etc.  In the repositories closure of gradle, we provided multiple urls to each of these repositories, internal or proxy'd.   And we expect Gradle to search in all of them before declare an artifact is not found.  

Following is a snippet from our build script.  turn, turn_test are internal repositories that store artifacts created in house; while central, cloudera are proxies to public repositories.  Snapshots is our internal snapshot repositories.

    repositories {
    	        maven {
    		      url 'http://maven.turn.com/service/local/repositories/turn/content/'
    	        }
                maven {
                      url 'http://maven.turn.com/service/local/repositories/central/content/'
                }        		
		maven {
			url 'http://maven.turn.com/service/local/repositories/snapshots/content/'
		}
		maven {
			url 'http://maven.turn.com/service/local/repositories/turn_test/content/'
		}		
		maven {
			url 'http://maven.turn.com/service/local/repositories/cloudera/content/'
		}	
    }

### Steps to Reproduce (for bugs)
In our dependencies closure, one of the dependencies is:
compile "org.codehaus.groovy:groovy-all:$groovyVersion.+"

When build executed, we are getting the following error:

00:02:07.554 > Could not resolve org.codehaus.groovy:groovy-all:2.3.+.
00:02:07.554   Required by:
00:02:07.554       project :modules:kvstore
00:02:07.554    > Failed to list versions for org.codehaus.groovy:groovy-all.
00:02:07.554       > Unable to load Maven meta-data from http://maven.turn.com/service/local/repositories/turn/content/org/codehaus/groovy/groovy-all/maven-metadata.xml.
00:02:07.554          > Could not get resource 'http://maven.turn.com/service/local/repositories/turn/content/org/codehaus/groovy/groovy-all/maven-metadata.xml'.
00:02:07.555             > Could not GET 'http://maven.turn.com/service/local/repositories/turn/content/org/codehaus/groovy/groovy-all/maven-metadata.xml'.
00:02:07.555                > Read timed out

where the groovy-all artifact is available in maven central.  But it exited after failed to find it in turn repository.

### Your Environment
We have Gradle 4.5.1.  Java 1.80.  We are using nexus to store our artifacts.

**Comment by big-guy** [comment]
@faiyat I believe this is intentional because Gradle is unable to determine which artifacts are available when it can't reach a repository.  This doesn't happen when the repository returns a 404/no artifacts.

@melix @oehme is there any change in this behavior since 4.5.1?

**Comment by oehme** [comment]
This is intentional, if the repository times out we don't just fall through to the next, because that would lead to non-reproducible builds. Timeouts were introduced in 4.3

**Comment by faiyat** [comment]
Thanks for looking into this.  Does it mean Gradle no longer support
multiple repositories?  What if not all artifacts can be found in one
repository?

Thanks,

Vivian Zhang

**Comment by oehme** [comment]
I can't tell you why you are getting a timeout, you'll have to analyze your network. Make sure you're not being blocked by a firewall or similar. Try opening the url in a browser. Do you get a fast response?

**Comment by faiyat** [comment]
There is no firewall issues.  Clearly the component that failed does not
exist in the first repo in the list.  But Gradle still stuck there and
timeout eventually.  Wouldn't it move on if the path to the component is
not found?  It should return not found instead of timeout.  Is multiple
repo stil supported by Gradle?


Thanks,

Vivian Zhang

**Comment by faiyat** [comment]
From the build log, it looks like the time between the compile task start
and fail is 30s.  Assuming it's all spend with the network.  How do I
increase the timeout in Gradle script so that it won't exit so fast?

Thanks,

Vivian Zhang

**Comment by oehme** [comment]
You said this happens on every build - It's not normal to get timeouts every time. Try opening the URL in your browser - Do you get a fast 404 response there?

**Comment by faiyat** [comment]
It does not happen on every build, but on most of our failed builds.  The
issue is not with the timeout, but with the wrong url it is looking at.  No
matter how long the time out we give, if the artifact is not there, then it
will fail eventually.  This is the part I'm puzzled about.  If Gradle
couldn't find the artifact in one of the repositories, then it should move
on immediately to the next repo until it searches all repo and couldn't
find, it can then report that it cannot be resolved.  The issue I have
reported is that it stuck at the first repo it encounter, which does not
have the artifact it is looking for.  If it is network related as you said,
then how do I increase the time out for it to confirm the path does not
exist there and move on?  I have already added
org.gradle.internal.http.socketTimeout=300000 to gradle.property file,
which does not seem to help.

Thanks,

Vivian Zhang

**Comment by oehme** [comment]
Our default timeout is half a minute which should be more than enough. You should really get in touch with your network admin if your internal repository does not respond in less than half a minute. Increasing the timeout would just mask a serious network issue instead of fixing it.
