### ISSUE TITLE
Task implementors/users get often-surprising caching behaviour when file inputs have no explicit normalisation/path-sensitivity

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#7338]
It is currently possible to “cache enable” most tasks by adding `@Cacheable` or using the corresponding runtime API. When doing only this, users sometimes get behaviour that appears to be correct, but is actually often not fully correct.

The problem arises from file inputs by default not being considered portable. That is, we effectively default to `PathSensitivity.ABSOLUTE`, which is often not what is actually wanted. Indications are that users are not _intentionally_ using this default. Instead, they are either unaware of the concept of input portability or have forgotten about the property. This has the result of effectively masking the problem. 

Our proposed increment for improving this situation is to consider a caching ineligible for caching if any file input property does not have an _explicit_ normalisation/path-sensitivity declared. This ineligibility would be expressed using the existing mechanism that we use for other configuration problems (e.g. overlapping outputs, lambda inputs etc.) and would be observable in the same way. Future work may increase the visibility of this and other related problems.

The net effect of this change is that tasks that declare themselves to be cacheable, but have any file input property declared without a normalisation would no longer be considered cacheable.

**Comment by autonomousapps** [comment]
Would we emit a warning to the console if a task is `@Cacheable` but we decline to cache it for the reasons stated? That would be an improvement over a silent failure.

**Comment by wolfs** [comment]
@autonomousapps The feature will not be silent - we will report that caching is disabled via the caching disabled reason. This currently shows up on the info log and is prominent in build scans.

**Comment by lptr** [comment]
@autonomousapps commented on Oct 12, 2018:

> Well, I have confirmation from Google that at least one plugin author is intentionally relying on absolute path-sensitivity. It's nice to be proven wrong so decisively. Here's what Ivan Gavrilovic just said to me by email:
> 
> > When it comes to path sensitivity, we cannot use relative path sensitivity because of our transforms (com.android.build.api.transform.Transform). Relative path sensitivity breaks the incremental build correctness for them (that is one of the reasons why we have our Android Build cache for dexing). Good news is that we are moving away from those, and migrating to Gradle ArtifactTransforms, which are cacheable.
> 
> I admit I don't understand why relative path-sensitivity would break incremental build correctness for those tasks, but maybe I can find someone to explain that to me.

@ldaley commented on Oct 12, 2018:

> This change would mean that that task would stop being cacheable until they explicitly add the absolute path sensitivity declaration.

@wolfs commented on Oct 23, 2018:

> This issue should probably be solved by doing #833 and then https://github.com/gradle/build-cache/issues/600.

**Comment by lptr** [comment]
We now disable caching for tasks failing validation.
