### ISSUE TITLE
Gradle Sync issue on Android Studio

### ISSUE THREAD

**Issue by shabbirsphinx** [gradle/gradle#7340]
Using classpath 'com.android.tools.build:gradle:3.2.0' in top build.gradle file

NEGOTIATE authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)

> Could not resolve com.android.tools.build:gradle:3.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom'. Received status code 500 from server: Internal Server Error

**Comment by shabbirsphinx** [comment]
I am getting this error and could not sync grade properly.
./gradlew clean gives me this error.

**Comment by trevjonez** [comment]
error message here is pretty clear that the google maven server is having issues.

**Comment by oehme** [comment]
Closing, as this is not a Gradle issue. The error message shows that there is a server error on Google's side.
