### ISSUE TITLE
Fail fast if source folders are prefixes of each other

### ISSUE THREAD

**Issue by quentinflahaut** [gradle/gradle#7341]
gradle version: v4.10.2

Create a anonym class implementing an interface.
Compile one time.
Change a method name in the interface.
Build again

The incremental build will fail, asking for the delete method.

This is a regression from gradle v4.10

With gradle v4.9 is working very well

**Comment by oehme** [comment]
Please provide a reproducible sample project.

**Comment by quentinflahaut** [comment]
I cannot reproduce the problem on a simple project.
The bug appear only on my project which is quite complexe.

The project which contains the modified interface does not update the .class in the build/classes folder.

however i got this message:
> Task :java:index6:compileJava UP-TO-DATE
file or directory 'C:\ng\src\svn\platform\apollo\index6\src\main\java', not found
Build cache key for task ':java:index6:compileJava' is 4db1a98a9d3506238fbcac22b75e543d
Task ':java:index6:compileJava' is not up-to-date because:
  Input property 'source' file C:\ng\src\svn\platform\apollo\index6\index\src\com\exalead\index\compact\IndexCompactService.java has changed.
  Input property 'source' file C:\ng\src\svn\platform\apollo\index6\index\src\com\exalead\index\resources\IndexResourcesManager.java has changed.
Created classpath snapshot for incremental compilation in 0.154 secs. 937 duplicate classes found in classpath (see all with --debug).
Class dependency analysis for incremental compilation took 0.151 secs.
file or directory 'C:\ng\src\svn\platform\apollo\index6\src\main\java', not found
None of the classes needs to be compiled! Analysis took 0.328 secs.
:java:index6:compileJava (Thread[main,5,main]) completed. Took 1.159 secs.
:java:index6:classes (Thread[main,5,main]) started.

**Comment by oehme** [comment]
Looks like you have defined both `src` and `src/main/java` as a source folder, which can't work, because on is a prefix of the other. If you want your source folder to be `src`, then you have to overwrite the default `src/main`java` instead of just adding it.

We should fail much earlier in such scenarios.

**Comment by quentinflahaut** [comment]
You point something interesting, when I created very small java gradle project, I tested 3 sourSets definition:
1)
sourceSets {
    main.java.srcDirs = ['src']
}

2)
sourceSets {
	main {
	    java {
	        srcDirs = ['src']
	    }
    }
}

3)
sourceSets {
	main {
	    java {
	        srcDir 'src'
	    }
    }
}

But on the last one (and only on the last one, I get this message: 
> Task :p2:compileJava UP-TO-DATE
file or directory 'C:\Users\qft1\Desktop\gradleTest\p2\src\main\java', not found
Skipping task ':p2:compileJava' as it is up-to-date.
:p2:compileJava (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 0.101 secs.

I my project I only used the last syntax on every projects

**Comment by quentinflahaut** [comment]
I'll try on my project to change the sourceset as you mention and give you the result

**Comment by oehme** [comment]
The only thing that matters is the `srcDirs = ['src']` part. Everything else is just variations of one another.

**Comment by quentinflahaut** [comment]
Ok, I understand the problem now.
Every variation are not equals.
With the following variation:
`sourceSets { main { java { srcDir 'src' } } }`
The sourcet is well added, but the default src/main/java is still used. Therefor, I get the message 
`'C:\Users\qft1\Desktop\gradleTest\p2\src\main\java', not found`
Additionally, on this variation, the cache system is still looking on the missing path, and doesn't rebuild the current project. And so the incremental compilation was broken.

**Comment by quentinflahaut** [comment]
In my project, the broken variation is the most important because I want to specify a pattern of inclusion or exclusion to every single folder that I specify. (The structure of the project is quite complicated, we are still migrating from a very old build system)

**Comment by oehme** [comment]
So with `srcDirs = ['src']`, incremental compile works?

**Comment by quentinflahaut** [comment]
yes with srcDirs it's working

**Comment by oehme** [comment]
Interesting - it shouldn't fail because of that, but we don't have test coverage for overlapping source folders, so it slipped through.
