### ISSUE TITLE
Remove deprecated Jetty plugin

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#735]
The Jetty plugin has been deprecated with Gradle 3.0. The plugin including all its tests needs to be removed from the Gradle code base. Any testing coding code that relies on the Jetty plugin needs to be changed to use a different solution.
### Expected Behavior

Delete the plugin code under [`jetty` subproject](https://github.com/gradle/gradle/tree/master/subprojects/jetty) and anything in the Gradle core infrastructure that uses it.
### Current Behavior

Users will have to use the external Gretty plugin.
### Context

The Jetty plugin in its current form does not provide a good user experience. It uses a very old version which is not configurable. Users expect more functionality of the plugin.
### Your Environment

All environments.

**Comment by big-guy** [comment]
I think we have things that use jetty, but not the jetty plugin.  Do you think we would need to update things that _use_ jetty (e.g., all of our HTTP/repo mocking infrastructure)?

**Comment by bmuschko** [comment]
We can continue to use Jetty for testing infrastructure. That's totally fine. This work really is only about the fact that were are going to remove the Jetty plugin and therefore need to change everything that depends on it.

**Comment by bmuschko** [comment]
@eriwen Why did you remove the milestone for this issue? The deprecation message and our documentation says that the plugin will be removed with 4.0.

**Comment by eriwen** [comment]
@bmuschko Mistake on my part. We aren't doing any new deprecations in 4.0, but since this is already deprecated I'll put it back on the 4.0 milestone

**Comment by pioterj** [comment]
Remember to remove it from the user manual too.

- Obviously https://docs.gradle.org/current/userguide/jetty_plugin.html
- Also https://docs.gradle.org/current/userguide/web_project_tutorial.html

**Comment by pioterj** [comment]
And from https://docs.gradle.org/current/userguide/standard_plugins.html

**Comment by eriwen** [comment]
Closing as complete
