### ISSUE TITLE
Consuming preferred dependencies is unexpected across Gradle, Maven, and Ivy metadata

### ISSUE THREAD

**Issue by OdysseusLives** [gradle/gradle#7351]
### Purpose
This is related to #7046 as it relates to publishing a preferred dependency & using Maven & Ivy formats that do not support `preferred` dependencies like richer Gradle metadata does. 

This discussion could lead to part of documentation on `prefer` or to other outcomes, and I wanted to raise this user flow as noteworthy:

1. User defines preferred dependency version in a project
2. User publishes with Maven or Ivy or Gradle metadata format 
3. User consumes dependency in another project
4. User expects to resolve to the preferred transitive dependency version

However, this is not what happens when publishing with a Maven pom.

### Expected Behavior

When publishing a preferred dependency with a range in different blocks:
```
dependencies {
    api ('tree:acacia') {
        version {
            prefer '1.5'
        }
    }
    api ('tree:acacia') {
        version {
            require '[1.2, 2.0)'
        }
    }
}
```

Then the published pom contains two `required` dependencies:
```
<dependencies>
    <dependency>
      <groupId>tree</groupId>
      <artifactId>acacia</artifactId>
      <version>1.5</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>tree</groupId>
      <artifactId>acacia</artifactId>
      <version>[1.2, 2.0)</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

When this is consumed, I expect that the preferred version (as defined in the build file) then becomes the selected version (winning over the version range). 

### Current Behavior
Currently, I see that the selected version is the highest in the version range, rather than the preferred dependency that is listed statically. 

The following is from `dependencyInsight`:

```
> Task :dependencyInsight
tree:acacia:1.9
   variant "compile" [
      org.gradle.status             = release (not requested)
      org.gradle.usage              = java-api
      org.gradle.component.category = library (not requested)
   ]

tree:acacia:[1.2, 2.0) -> 1.9
\--- tree:blue-palo-verde:1.0
     \--- compileClasspath
```

While it makes sense that the highest version wins, this behavior is not the same as what happens in the same user flow when publishing a preferred version of a dependency, then reading in this publication using Ivy metadata or Gradle metadata. 

### Context
This is different behavior than is happening with Ivy files or Gradle metadata. 

With the same build dependencies, the following Ivy is produced with two `required` dependencies:
```
  <dependencies>
    <dependency org="tree" name="acacia" rev="1.5" conf="compile-&gt;default"/>
    <dependency org="tree" name="acacia" rev="[1.2, 2.0)" conf="compile-&gt;default"/>
  </dependencies>
```

Which yields the following in `dependencyInsight`:
```
> Task :dependencyInsight
tree:acacia:1.5
   variant "default" [
      org.gradle.status = integration (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]

tree:acacia:1.5
\--- tree:blue-palo-verde:1.0
     \--- compileClasspath

tree:acacia:[1.2, 2.0) -> 1.5
\--- tree:blue-palo-verde:1.0
     \--- compileClasspath
```

Similarly, when using the Gradle metadata format via `enableFeaturePreview('GRADLE_METADATA')`, the following metadata is produced with the full information on `prefer` and `require`:
```
      "dependencies": [
        {
          "group": "tree",
          "module": "acacia",
          "version": {
            "prefers": "1.5"
          }
        },
        {
          "group": "tree",
          "module": "acacia",
          "version": {
            "requires": "[1.2, 2.0)"
          }
        }
      ]
```

Which yields the following in `dependencyInsight` when the build is configured to use `metadataSources { gradleMetadata() }`:
```
> Task :dependencyInsight
tree:acacia:1.5
   variant "api" [
      org.gradle.usage  = java-api
      org.gradle.status = release (not requested)
   ]

tree:acacia:1.5
\--- tree:blue-palo-verde:1.0
     \--- compileClasspath

tree:acacia:[1.2, 2.0) -> 1.5
\--- tree:blue-palo-verde:1.0
     \--- compileClasspath
```

### Steps to Reproduce (for bugs)
This issue is reproducible in the following project:
- [publishing with `maven-publish` using mavenPom metadata](https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/require-prefer/docs/consuming/consuming-published-dependencies-from-maven-with-mavenPom-metadata-using-different-block/input)

This expected behavior is reproducible in the following projects:
- [publishing with `ivy-publish` using ivyDescriptor metadata](https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/require-prefer/docs/consuming/consuming-published-dependencies-from-ivy-with-ivyDescriptor-metadata-using-different-block/input)
- [publishing with `maven-publish` using Gradle metadata](https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/require-prefer/docs/consuming/consuming-published-dependencies-from-maven-with-gradleMetadata-metadata-using-different-block/input)
- [publishing with `ivy-publish` using Gradle metadata](https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/require-prefer/docs/consuming/consuming-published-dependencies-from-ivy-with-gradleMetadata-metadata-using-different-block/input)

### Your Environment

Using Gradle v5.0-20181010235832+0000

**Comment by ljacomet** [comment]
Perfect mapping of rich versions to Maven or Ivy is impossible.
A possible fix is to rely on publishing _resolved_ versions.

Note that Gradle also produces some warnings when concepts cannot be mapped in the target metadata format.

No further improvements planned here.
