### ISSUE TITLE
Prevent changes to a configuration after it has been resolved that would affect the resolved graph

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#7358]
### Expected Behavior

Once a configuration has been resolved, any change to that configuration that would affect the resolved graph should be disallowed.

### Current Behavior

Some changes (only adding/removing dependencies) from a configuration after it has been resolved fail with the message:
> Cannot change dependencies of configuration ':implementation' after it has been resolved.

But there are many other ways to impact which dependencies may be selected. 

### Context

The current behavior prevents a mistake like this from going unnoticed:
```
dependencies {
   implementation("org:dependency:1.0")
}
println configurations.implementation.files
dependencies {
   implementation("org:other:1.0")
}
// where's the "other" dependency?
println configurations.implementation.files
```

This isn't a new problem.

### Steps to Reproduce (for bugs)
```
apply plugin: 'base'

repositories {
    jcenter()
}

configurations {
    implementation
}

dependencies {
    implementation("log4j:log4j") {
        version {
            prefer "1.2.17"
        }
    }
}

task resolve {
    dependsOn configurations.implementation
    doLast {
        println configurations.implementation.files
        // Fails with "Cannot change dependencies of configuration ':implementation' after it has been resolved."
        // project.dependencies.add("implementation", "com.google.guava:guava:17.0")
        
        // This does not fail, though it would change the versions in the graph:
        configurations.implementation {
            dependencies.all {
                version {
                    prefer "1.2.16"
                }
            }
        }
        println configurations.implementation.files
    }
}
```

Run with `gradle resolve`.  Notice if you move the configuration outside of the task action, it does change the resolved graph.

### Your Environment

This always happens.

**Comment by JLLeitschuh** [comment]
@big-guy What happens if you do this:
```
dependencies {
   implementation("org:dependency:1.0")
}
println configurations.implementation.files
dependencies {
   implementation("org:other:1.0")
}
// where's the "other" dependency?
println configurations.implementation.resolvedConfiguration.files
```
Does the above issue still happen?

**Comment by big-guy** [comment]
@JLLeitschuh Yes, the build still fails as it should.
