### ISSUE TITLE
On macOS Sierra, it takes several seconds to resolve the local hostname

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#736]
Other Java tools are experiencing a problem with looking up the local hostname on macOS Sierra (10.12).  Here's a longer description of the problem: https://thoeni.io/post/macos-sierra-java/
### Expected Behavior

Local host look-up should be speedy, or if not, cached.
### Current Behavior

I suspect this causing a problem here: 
https://discuss.gradle.org/t/gradle-always-execute-creating-new-in-memory-cache-for-repo-maven-when-i-build-project-i-configurated-org-gralde-daemon-true-in-gradle-properties-the-command-line-properties-like-org-gradle-daemon-true-are-ignored/20080
### Context

We have an uncached hostname look-up here: 
https://github.com/gradle/gradle/blob/master/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/ntlm/NTLMCredentials.java#L64

We have a cache in InetAddressFactory for this look-up that we could re-use.  This has a large impact on builds with many repositories.
### Steps to Reproduce (for bugs)

This happens always.
### Your Environment

macOS Sierra

**Comment by twoseat** [comment]
Of possible relevance: https://thoeni.io/post/macos-sierra-java/

**Comment by oehme** [comment]
It seems to be an issue in the JDK actually, calling an inefficient native method: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8170910

I guess we could work around this by implementing our own logic in `native-platform`.
