### ISSUE TITLE
Incremental compiler should handle top-level package-private classes correctly

### ISSUE THREAD

**Issue by Pokechu22** [gradle/gradle#7363]
Incremental building doesn't work correctly when there are classes that aren't named the same as the file they are in.  This can be done with a package-access class.

### Expected Behavior
Files that were changed and the files that referenced them to be rebuilt.

### Current Behavior
Some of the files aren't rebuilt, causing various odd behaviors (see steps to reproduce).

### Context
I have a somewhat hacky setup that I use for building some code against several configurations where most of the code is the same across the configurations with only a few files changed.  The code that has multiple versions is put into a file such as `Foo_ConfA.java` and `Foo_ConfB.java`, both of which contain a (non-public) `class Foo`.  This code is then referenced from other classes in the same package, _or_ extended by a separate public class (to get around the restriction of it being package access) which is then extended by other code.  I then `exclude` all but one of the versions within my buildscript, so that only the one I want is used.  This is definitely very hacky, but it's the use-case I ran into this with.

Note that this use case is _not_ required to reproduce this bug, though; simply having a class whose name doesn't match the filename will trigger it.

### Steps to Reproduce

There are two variations that give different errors.  Both of them start with the same project, incremental.zip, but require editing it in different ways.  This project has a class named `StringUtil` declared in `Util.java`, and also two other classes: `Main` which references both other classes, and `Constants` which contains a method to get a string constant used in both classes.

#### Case A

0. Extract the project ZIP.
1. Run a build without changing anything.  The build should complete normally.
2. Delete the `StringUtil.twice` method.
3. Build again.  Despite `Main` referencing the deleted method, the build will be successful.
4. Attempting to run `Main` will cause a NoSuchMethodError to be thrown.

<details><summary><code>compileJava</code> segment from a debug build:</summary>
<pre>
14:10:01.090 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :compileJava (Thread[Daemon worker Thread 23,5,main]) started.
14:10:01.092 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for resourceHashesCache, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\fileHashes\resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@6b55edea
14:10:01.093 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for taskHistory, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@5ea531c1
14:10:01.095 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for task history cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory)
14:10:01.100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on task history cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory).
14:10:01.100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on task history cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory).
14:10:01.102 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for outputFiles, path C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup\outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@63093ab8
14:10:01.105 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for Build Output Cleanup Cache (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup)
14:10:01.106 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on Build Output Cleanup Cache (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup).
14:10:01.107 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on Build Output Cleanup Cache (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup).
14:10:01.132 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache fileHashes.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\fileHashes\fileHashes.bin)
14:10:01.153 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache classAnalysis.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\classAnalysis.bin)
14:10:01.486 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache taskHistory.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\taskHistory.bin)
14:10:01.489 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache taskHistory.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory\taskHistory.bin)
14:10:01.489 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache outputFiles.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup\outputFiles.bin)
14:10:01.108 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
14:10:01.108 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :compileJava
14:10:01.108 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :compileJava' started
14:10:01.108 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':compileJava'
14:10:01.109 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':compileJava' into context took 0.001 secs.
14:10:01.110 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Realize task :clean' started
14:10:01.110 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Realize task :clean'
14:10:01.111 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Realize task :clean' completed
14:10:01.116 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':compileJava' is up-to-date
14:10:01.118 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Implementation for task ':compileJava': org.gradle.api.tasks.compile.JavaCompile_Decorated@82f9eb64cac75b78d32d56b7273d1766
14:10:01.118 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Action implementations for task ':compileJava': [org.gradle.api.tasks.compile.JavaCompile_Decorated@82f9eb64cac75b78d32d56b7273d1766]
14:10:01.124 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property classpath (CompileClasspath) for task ':compileJava'
14:10:01.125 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :compileClasspath' started
14:10:01.126 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve dependencies of :compileClasspath'
14:10:01.126 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :compileClasspath' completed
14:10:01.126 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property effectiveAnnotationProcessorPath (Classpath) for task ':compileJava'
14:10:01.127 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :annotationProcessor' started
14:10:01.127 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve dependencies of :annotationProcessor'
14:10:01.127 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :annotationProcessor' completed
14:10:01.127 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property options.bootstrapClasspath (CompileClasspath) for task ':compileJava'
14:10:01.127 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property options.sourcepath (RelativePathInput) for task ':compileJava'
14:10:01.127 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property source (NameOnlyInput) for task ':compileJava'
14:10:01.130 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property destinationDir (Output) for task ':compileJava'
14:10:01.134 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Task ':compileJava' is not up-to-date because:
  Input property 'source' file C:\Pokechu22\GradleTests\Incremental\src\main\java\Util.java has changed.
14:10:01.134 [DEBUG] [org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter] Ensuring directory exists for property destinationDir (Output) at C:\Pokechu22\GradleTests\Incremental\build\classes\java\main
14:10:01.134 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':compileJava'.
14:10:01.134 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute compile for :compileJava' started
14:10:01.140 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for classAnalysis, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\classAnalysis.bin, access org.gradle.cache.internal.DefaultCacheAccess@7fd7bd3a
14:10:01.142 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for Java compile cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile)
14:10:01.143 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on Java compile cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile).
14:10:01.144 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on Java compile cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile).
14:10:01.145 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for jarAnalysis, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\jarAnalysis.bin, access org.gradle.cache.internal.DefaultCacheAccess@7fd7bd3a
14:10:01.145 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for taskHistory, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@7fd7bd3a
14:10:01.148 [INFO] [org.gradle.api.internal.tasks.compile.incremental.classpath.ClasspathSnapshotMaker] Created classpath snapshot for incremental compilation in 0.0 secs.
14:10:01.148 [DEBUG] [org.gradle.api.internal.tasks.compile.incremental.classpath.ClasspathSnapshotMaker] While calculating classpath snapshot 0 duplicate classes were found: [].
14:10:01.204 [INFO] [org.gradle.api.internal.tasks.compile.incremental.recomp.PreviousCompilationOutputAnalyzer] Class dependency analysis for incremental compilation took 0.051 secs.
14:10:01.215 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 1.8 -target 1.8 -d C:\Pokechu22\GradleTests\Incremental\build\classes\java\main -g -sourcepath  -proc:none -XDuseUnsharedTable=true -classpath C:\Pokechu22\GradleTests\Incremental\build\classes\java\main C:\Pokechu22\GradleTests\Incremental\src\main\java\Util.java
14:10:01.216 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
14:10:01.486 [INFO] [org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler] Incremental compilation of 1 classes completed in 0.337 secs.
14:10:01.486 [DEBUG] [org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler] Recompiled classes [Util]
14:10:01.486 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute compile for :compileJava'
14:10:01.486 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute compile for :compileJava' completed
14:10:01.486 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property destinationDir (Output) for task ':compileJava'
14:10:01.489 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
14:10:01.489 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':compileJava'
14:10:01.490 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :compileJava'
14:10:01.491 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :compileJava' completed
14:10:01.491 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :compileJava (Thread[Daemon worker Thread 23,5,main]) completed. Took 0.401 secs.
</pre>
</details>
<br>
Note that it states "Recompiled classes [Util]", and not "StringUtil".

#### Case B

0. Extract the project ZIP.
1. Run a build without changing anything.  The build should complete normally.
2. Change the return value of `Constants.getIndent` to something else (e.g. 2 spaces).
3. Build again.  Compilation will fail, claiming `StringUtil.twice` does not exist, despite it existing.

<details><summary><code>compileJava</code> segment from a debug build:</summary>
<pre>
14:19:48.649 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :compileJava (Thread[Daemon worker Thread 25,5,main]) started.
14:19:48.652 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for resourceHashesCache, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\fileHashes\resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@51c8959b
14:19:48.652 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for taskHistory, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@20157e68
14:19:48.653 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for task history cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory)
14:19:48.656 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on task history cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory).
14:19:48.656 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on task history cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory).
14:19:48.658 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for outputFiles, path C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup\outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@678fcb0e
14:19:48.659 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for Build Output Cleanup Cache (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup)
14:19:48.661 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on Build Output Cleanup Cache (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup).
14:19:48.662 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on Build Output Cleanup Cache (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup).
14:19:48.675 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache fileHashes.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\fileHashes\fileHashes.bin)
14:19:48.864 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache taskHistory.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\taskHistory\taskHistory.bin)
14:19:48.864 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Opening cache outputFiles.bin (C:\Pokechu22\GradleTests\Incremental\.gradle\buildOutputCleanup\outputFiles.bin)
14:19:48.663 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
14:19:48.663 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :compileJava FAILED
14:19:48.663 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :compileJava' started
14:19:48.663 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':compileJava'
14:19:48.664 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Putting task artifact state for task ':compileJava' into context took 0.0 secs.
14:19:48.664 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Realize task :clean' started
14:19:48.665 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Realize task :clean'
14:19:48.665 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Realize task :clean' completed
14:19:48.669 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':compileJava' is up-to-date
14:19:48.669 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Implementation for task ':compileJava': org.gradle.api.tasks.compile.JavaCompile_Decorated@82f9eb64cac75b78d32d56b7273d1766
14:19:48.669 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Action implementations for task ':compileJava': [org.gradle.api.tasks.compile.JavaCompile_Decorated@82f9eb64cac75b78d32d56b7273d1766]
14:19:48.670 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property classpath (CompileClasspath) for task ':compileJava'
14:19:48.670 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :compileClasspath' started
14:19:48.671 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve dependencies of :compileClasspath'
14:19:48.671 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :compileClasspath' completed
14:19:48.671 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property effectiveAnnotationProcessorPath (Classpath) for task ':compileJava'
14:19:48.671 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :annotationProcessor' started
14:19:48.672 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Resolve dependencies of :annotationProcessor'
14:19:48.672 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Resolve dependencies of :annotationProcessor' completed
14:19:48.672 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property options.bootstrapClasspath (CompileClasspath) for task ':compileJava'
14:19:48.672 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property options.sourcepath (RelativePathInput) for task ':compileJava'
14:19:48.672 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property source (NameOnlyInput) for task ':compileJava'
14:19:48.676 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property destinationDir (Output) for task ':compileJava'
14:19:48.679 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Task ':compileJava' is not up-to-date because:
  Input property 'source' file C:\Pokechu22\GradleTests\Incremental\src\main\java\Constants.java has changed.
14:19:48.679 [DEBUG] [org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter] Ensuring directory exists for property destinationDir (Output) at C:\Pokechu22\GradleTests\Incremental\build\classes\java\main
14:19:48.679 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':compileJava'.
14:19:48.680 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute compile for :compileJava' started
14:19:48.684 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for classAnalysis, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\classAnalysis.bin, access org.gradle.cache.internal.DefaultCacheAccess@43623a9b
14:19:48.685 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Acquiring file lock for Java compile cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile)
14:19:48.688 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on Java compile cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile).
14:19:48.688 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on Java compile cache (C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile).
14:19:48.689 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for jarAnalysis, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\jarAnalysis.bin, access org.gradle.cache.internal.DefaultCacheAccess@43623a9b
14:19:48.689 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for taskHistory, path C:\Pokechu22\GradleTests\Incremental\.gradle\4.10.2\javaCompile\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@43623a9b
14:19:48.690 [INFO] [org.gradle.api.internal.tasks.compile.incremental.classpath.ClasspathSnapshotMaker] Created classpath snapshot for incremental compilation in 0.0 secs.
14:19:48.692 [DEBUG] [org.gradle.api.internal.tasks.compile.incremental.classpath.ClasspathSnapshotMaker] While calculating classpath snapshot 0 duplicate classes were found: [].
14:19:48.698 [INFO] [org.gradle.api.internal.tasks.compile.incremental.recomp.PreviousCompilationOutputAnalyzer] Class dependency analysis for incremental compilation took 0.002 secs.
14:19:48.711 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 1.8 -target 1.8 -d C:\Pokechu22\GradleTests\Incremental\build\classes\java\main -g -sourcepath  -proc:none -XDuseUnsharedTable=true -classpath C:\Pokechu22\GradleTests\Incremental\build\classes\java\main C:\Pokechu22\GradleTests\Incremental\src\main\java\Constants.java C:\Pokechu22\GradleTests\Incremental\src\main\java\Main.java
14:19:48.711 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
14:19:48.849 [ERROR] [system.err] C:\Pokechu22\GradleTests\Incremental\src\main\java\Main.java:7: error: cannot find symbol
14:19:48.849 [ERROR] [system.err]               System.out.println(StringUtil.twice(text));
14:19:48.849 [ERROR] [system.err]                                  ^
14:19:48.850 [ERROR] [system.err]   symbol:   variable StringUtil
14:19:48.850 [ERROR] [system.err]   location: class Main
14:19:48.855 [ERROR] [system.err] 1 error
14:19:48.856 [INFO] [org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler] Incremental compilation of 3 classes completed in 0.165 secs.
14:19:48.856 [DEBUG] [org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler] Recompiled classes [Constants, StringUtil, Main]
14:19:48.856 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute compile for :compileJava'
14:19:48.856 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute compile for :compileJava' completed
14:19:48.857 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Fingerprinting property destinationDir (Output) for task ':compileJava'
14:19:48.865 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
14:19:48.865 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':compileJava'
14:19:48.866 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :compileJava'
14:19:48.866 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :compileJava' completed
14:19:48.866 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :compileJava (Thread[Daemon worker Thread 25,5,main]) completed. Took 0.216 secs.
</pre>
</details>
<br>
Note that `javac` is only given "Constants.java" and "Main.java", but it states "Recompiled classes [Constants, StringUtil, Main]".

Additionally, note that this doesn't seem to happen if `Constants` contains a direct String constant instead of a method; in that case, everything builds fine (but this seems to be because it triggers a full recompilation).

### Your Environment
 * Java version: Oracle Java(TM) SE Runtime Environment 1.8.0_131-b11
 * Windows 10 build 17763 (insider preview)
 * Gradle 4.10.2, with the daemon
 * Cygwin, using the `gradlew` script (not `gradlew.bat`)

**Comment by oehme** [comment]
This is because we always assume we can get the class name from the Java file name. The workaround is to stick with this (in my opinion reasonable) guideline.

The only ways to fix this completely would either be

- parsing the source code to find out what types changed (very expensive)
- recompiling all classes inside the same package (less expensive, but still not great)

**Comment by Pokechu22** [comment]
Makes sense; however, for my hacky solution I can't think of a clean way to what I need without this.

Would it be possible to use the sourcefile attribute to determine the proper file?  The issue I can think of with that would be that it's not present when debug info is disabled, but it still is one other possible method.

I'm also curious how using the file name to get the class name works with regards to inner classes - if I recall correctly they're compiled into separate files with distinct internal class names, so I'm not sure how it would know to check the outer class' file?  (I haven't tested this behavior, though)

**Comment by oehme** [comment]
This problem is about determining the class name from a source file, not from a class file. The latter is easy.

**Comment by Pokechu22** [comment]
Right, but since the initial step involves compiling all the files, wouldn't it be possible to record the source file associated with each compiled class at that point?

**Comment by oehme** [comment]
That doesn't help when you add types to a source file.

**Comment by Pokechu22** [comment]
Hm, or if a type is moved from one source file to another (which could happen without the file being deleted since you can have one public class and several package-private classes in the same file)... yeah, that's a bit more complicated.

I feel like it could still work based on scanning for any newly generated class files after compilation (and also class files that _weren't_ generated when it was expected that they would be), and also checking for changes in the source file from that... but it definitely gets complicated, and I suspect that in some cases it might end up requiring 1 compilation attempt that if it fails, everything in the package gets recompiled.

**Comment by Pokechu22** [comment]
I'm curious about how something else works, actually.  [The documentation on incremental compilation states](https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_compile):

> * Since constants can be inlined, any change to a constant will result in Gradle recompiling all source files. For that reason, you should try to minimize the use of constants in your source code and replace them with static methods where possible.
> * Since source-retention annotations are not visible in bytecode, changes to a source-retention annotation will result in full recompilation.

How are both of these detected?  It seems like both of these would also require either parsing the file before compiling, or multiple compile steps.

**Comment by oehme** [comment]
If an affected file contains either of these, we do a full recompile.

**Comment by Pokechu22** [comment]
I think I found a separate edge-case relating to that.  It seems like inner classes also cause issues there; if the constant or annotation is in an inner class it doesn't force a full recompile.  For constants, interestingly, this causes no issues and behaves better than would be expected; it looks like there is actually still a generated reference to the class in the [`InnerClasses` attribute](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.6), even though there's no field reference.  So only the files actually referencing that class are recompiled.

However, for annotations, no `InnerClasses` attribute is generated.  So given these two files:

<details><summary><code>Main.java</code></summary>
<pre lang="java">
public class Main {
	@Test.Foo("test")
	public void foo() { }
}
</pre>
</details><details><summary><code>Test.java</code></summary>
<pre lang="java">
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
public class Test {
	@Retention(RetentionPolicy.SOURCE)
	public static @interface Foo {
		public String value();
	}
}
</pre>
</details><br/>

... if built once, and then `value()` is deleted, that change is not detected and the build succeeds (until `Main` is changed).  However, since this is a source-level annotation, nothing happens at runtime.

> We could of course do the same for files containing types with a name that doesn't match the file name.

I think that probably would be the best solution; this situation involving package-private classes is rare enough that it shouldn't affect many people and it's something that doesn't need to be optimized for.

**Comment by rgeorge-at-mentor** [comment]
@oehme 

Just came a across a very closely resembling issue in our efforts to migrate to Gradle.  We have cases in our code where multiple classes are declared the same .java file.  Some of them do have a public class which matches the file name and some don't.

When a change is made to a class used by one of these package private classes, incremental compilation lands up deleting the .class file corresponding to the package private class.

Attached is a sample demonstrating this issue.  
[class-getting-deleted.zip](https://github.com/gradle/gradle/files/2835566/class-getting-deleted.zip)

The zip file contains 2 .java classes:

1. `MyTopLevelClass.java`: This contains a public class called `MyTopLevelClass` & one package private class called `MyVanishingClass`

2. `SomeUsefulClass.java:` This is a public class `SomeUsefulClass` which is referenced by `MyVanishingClass`

**Steps:**
* Do an initial build - `gradle jar`
* List classes in `build/classes/java/main/com/mycompany/gradle`
* You should see three .class files corresponding to the 3 clasess
* Make an edit to SomeUsefulClass
* Do a rebuild - `gradle jar`
* List classes in `build/classes/java/main/com/mycompany/gradle`
* You should notice that the class `MyVanishingClass.class` is deleted

This is feels like quite a significant bug - please do let us know if we should raise a new bug or the above scenario is covered by this one.

**Following is my environment:**
```
$ gradle --version
Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987
Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Windows 7 6.1 amd64
```
Thanks!

**Comment by oehme** [comment]
That's the same issue. The workaround is to put every class into its own class file or deactivate incremental compilation.
