### ISSUE TITLE
Gradle ignores "write only" properties in up-to-date checks

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#737]
@big-guy commented on [Fri Aug 19 2016](https://github.com/gradle/task-output-cache/issues/51)

I found this in `PlayRun`, but there may be other tasks that have this problem.

`runtimeClasspath` is annotated as an `@InputFiles`:
https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/tasks/PlayRun.java#L67-L67

It has a setter, but no getter, so we don't see this as an actual input because we look for getters. This means we don't get an error message when it's null.

I don't know if it makes sense to change the way we search for annotations or just add a validation to the `java-gradle-plugin` validator that looks for this scenario.

**Comment by adammurdoch** [comment]
If we end up not supporting this pattern, then we should add the validation to the inspection we do at runtime (which every task instance goes through), rather than checking in the plugin plugin at build time (which not every task goes through). Or, even better, check in both places.

**Comment by wolfs** [comment]
The validation is already in place: https://github.com/gradle/gradle/blob/8fbc841e1d1304471064a3fe04328b4ead9cb89a/subprojects/plugin-development/src/integTest/groovy/org/gradle/plugin/devel/tasks/AbstractPluginValidationIntegrationSpec.groovy#L666-L718
