### ISSUE TITLE
Settings Plugins need a delayed evaluation mechanism like afterEvaluate

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#7370]
### Expected Behavior
A user should be able to apply a `Settings` plugin and that plugin should be able to declare logic that should be evaluated after the user's `settings.gradle.kts` or `settings.gradle` file is evaluated.

### Current Behavior

Currently, neither the `Settings` interface, nor the `DefaultSettings` class support an `afterEvaluate` mechanism.

### Context
This plugin: https://github.com/GradleWeaver/better-build-file-names
I'm authoring probably one of the very few plugins for `Settings`.
This plugin recursively iterates over all of the `ProjectDescriptor`'s that have been created by the user calling `include` and changes the `ProjectDescriptor::buildFileName` to be `[project-name].gradle` or `[project-name].gradle.kts`.

This was originally inspired by the logic in Gradle's own build:
https://github.com/gradle/gradle/blob/b752deb35c485d521c0b5d9c10848f716242fd1f/settings.gradle.kts#L147-L163

The problem in this case is that if you apply my plugin first, none of the `ProjectDescriptor` have been added to the `Settings::rootProject` so the build isn't changed.

The current workaround is to tell users to do this:
```kotlin
buildscript {
  repositories {
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  dependencies {
    classpath("gradle.plugin.org.gradleweaver.plugins:better-build-file-names:0.0.1")
  }
}

include(":a")
include(":b")
include(":c")
include(":d")
include(":e")

// This line must be last!
apply(plugin = "org.gradleweaver.plugins.better-build-file-names")
```

### Your Environment
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.1 ("Oracle Corporation" 10.0.1+10)
OS:           Mac OS X 10.14 x86_64

```

**Comment by big-guy** [comment]
I don't think we want an "afterEvaluate" mechanism for settings scripts.

Like we have for other collection of things (tasks, configurations, publications, etc), we want a container for projects like a `NamedDomainObjectContainer`.

e.g., settings.gradle
```
include ":sub1"
include ":sub2"

badNameForContainerOfThings.all { ProjectDescriptor pd ->
    // set conventions for projects
}

include ":sub3" // still works as expected
```

`ProjectDescriptor` is probably not quite right for this. It has a mutable name (which `NamedDomainObjectContainer` doesn't allow) and all of its properties should be migrated to a `Provider`/`Property`.

**Comment by eskatos** [comment]
@JLLeitschuh can't you use `gradle.settingsEvaluated {}` in the meantime?

**Comment by JLLeitschuh** [comment]
I didn't know that that API even existed. I'll give it a shot. Thanks @eskatos!

**Comment by JLLeitschuh** [comment]
@eskatos Worked like a charm. Thanks!
