### ISSUE TITLE
Javadoc does not show method names

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#7378]
The Javadoc for the latest nightly doesn't show method names any more:
https://docs.gradle.org/nightly/javadoc/org/gradle/api/initialization/definition/InjectedPluginDependencies.html
![image](https://user-images.githubusercontent.com/423186/46940725-b57fdf80-d069-11e8-9ace-9d31a71d3ab9.png)

The Javadoc for 4.10 still seems to work: https://docs.gradle.org/4.10/javadoc/org/gradle/api/initialization/definition/InjectedPluginDependencies.html
![image](https://user-images.githubusercontent.com/423186/46940767-cc263680-d069-11e8-8798-f827ac4b9f46.png)

**Comment by liach** [comment]
Would this get a fix for major version 4 of gradle or is this not backward compatible? This still happens to gradle 4.10.3 (as seen in the method summary of https://docs.gradle.org/4.10.3/javadoc/org/gradle/api/Task.html)

**Comment by big-guy** [comment]
@eriwen is https://github.com/gradle/gradle/pull/7436 something that should have been cherry-picked back to 4.10.3?

**Comment by Vampire** [comment]
@eriwen in case you actually did work-around it, the work-around is gone again.
The 4.10.3 JavaDocs are still very hard to read without method names.
