### ISSUE TITLE
Limit Metaspace used by Gradle

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#7385]
We used to limit PermGenSpace for Java 7 and below, but not Metaspace for Java 8 and above. When I tried putting a limit in place as part of https://github.com/gradle/gradle/pull/7343, I got lots of OutOfMemoryErrors. This suggests that we introduced a leak since we stopped testing on Java 7.

This is a blocker for 5.0

**Comment by oehme** [comment]
The leak is in the Kotlin compiler - It uses Gradle-provided objects like Project and Logger over [Java RMI](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/compilerRunner/GradleIncrementalCompilerServicesFacadeImpl.kt#L15). RMI keeps a strong reference to those objects around, resulting in giant classloader leaks.  I'm not familiar with RMI, so maybe it's just a simple matter of closing some connection to fix this. Otherwise I'd strongly suggest not passing any Gradle objects over RMI, but having your own protocol.

cc @eskatos @bamboo

**Comment by eskatos** [comment]
Leak mitigation in https://github.com/gradle/kotlin-dsl/pull/1188

**Comment by oehme** [comment]
@eskatos Let me know when the fix is in gradle/gradle
