### ISSUE TITLE
Support Java library variants identified by classifiers

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7393]
- Some java library variants are published as a single module, with only the artifacts varying. The different variant artifacts are identified with different classifiers. eg:
- net.sf.json-lib:json-lib:2.4 has json-lib-2.4.jar, json-lib-2.4-jdk13.jar  and json-lib-2.4-jdk15.jar  
- In order to leverage the results of M4.1, access to the classifier will be required. Depending on the solution for M4.1, the classifier will be exposed where needed.

**Comment by ljacomet** [comment]
Closing as obsolete, different solutions are available in Gradle 6.0: more complete component metadata rules allowing to create variants on the fly, or proper publication with Gradle Module Metadata
