### ISSUE TITLE
Document use of variants for libraries using conventions in module name or version

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7394]
Module (artifact identifier) and version based variants are supported through a combination of attributes and capabilities. (e.g. `guava:26.0-jre` & `guava:26.0-android`) Document how to get conflict detection for these use cases, using popular libraries as examples.

**Comment by JamesXNelson** [comment]
Hate to be a bother, but if there's any progress here, it would be really nice to get an idea of the sorts of things a person should (or shouldn't) do w.r.t. variants; it's possible to piece together an idea grepping through sources and tests and issues, but it would be great to see any document, no matter how rough of a draft, describing the intentions / usage of variants, capabilities, usages and the like.

i.e. how does one "properly" go about publishing and consuming multiple artifacts produced by a single project?  There's obviously a lot of nuance there, but I'll save you the wall of text that comes to mind. ^_^

Thanks for building excellent tools!

**Comment by ljacomet** [comment]
This information is part of the reworked Dependency Management documentation for Gradle 6.0.
Have a look at the section "Fixing Metadata"
