### ISSUE TITLE
Version consistency when resolving a configuration hierarchy 

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7395]
Often it is desired to express consistency in the resolution results of configurations that extend each other. For example, any module that is present in `runtimeClasspath` should have the same version when `testRuntimeClasspath` is resolved. (i.e the resolution result of `testRuntimeClasspath` should be a superset of `runtimeClasspath`.) 

Currently, `testRuntimeClasspath` may increase the versions of modules that were already selected in `runtimeClasspath`. 

One way to solve this would be to add a configuration option to `Configuration` declaring that it must be resolved consistently with a parent configuration, or another arbitrary configuration. Gradle would then consider the result of the other configuration resolution as a strict constraint for the configuration in question and use that information during dependency resolution. This will either lead to a consistent resolution result or fail the build with an appropriate error.

**Comment by ljacomet** [comment]
Note that this consistent result could be extended cross projects.

**Comment by aaronabf** [comment]
This would be an amazing feature! 🙏

**Comment by melix** [comment]
This is now on `master`. See https://docs.gradle.org/nightly/userguide/resolution_strategy_tuning.html#resolution_consistency
