### ISSUE TITLE
Dependency Locking

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7397]
Dependency locking is important new functionality in Gradle. We should continue to improve and polish it based on user feedback.

Some ideas:
* ~Support locking of build `classpath` configuration~ Complete: see gradle/gradle#5845
* Flag to fail build if locked configurations that are resolved do not have a lock state
* Flag to ignore lock state
* Introduce a task based way to generate locks, makes it easier to perform the generation from IDE
* When a lock file is out of date, it prints only the configuration name, we should add the full project path to simplify search in multi project setups.

**Comment by rgoldberg** [comment]
Isn't the following implemented by `gradle dependencies --write-locks`?

> Introduce a task based way to generate locks, makes it easier to perform the generation from IDE

**Comment by jjohannes** [comment]
Open items and extension to dependency locking are now tracked through the [in:dependency-locking](https://github.com/gradle/gradle/labels/in%3Adependency-locking) label
