### ISSUE TITLE
Groovy plugin is not compatible with `java-library` plugin

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7398]
The `groovy` plugin does not expose the correct variants for consumption by the `java-library` plugin. When a `java-library` plugin project has a project dependency on a `groovy` project, it results in "unable to resolve class" errors when trying to compile the `java-library` project.

This is a [documented "known issue" with the `java-library` plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_known_issues_compat), which should be fixed.

A similar issue exists with the (Jetbrains provided) `kotlin` plugin, so any solution should be promoted for use by external plugin authors as well.

**Comment by oehme** [comment]
The Kotlin plugin does not have this problem, it [registers the needed variant](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt#L199).

**Comment by xSAVIKx** [comment]
@JamesXNelson thank you for your work on the problem! Maybe there is any news about when your PR could be merged and released?

**Comment by big-guy** [comment]
The 5.2 ship has sailed, but I've put it on the list for 5.3.

**Comment by JamesXNelson** [comment]
Cool.  Updated documentation regarding the workaround, so anyone 5.2 or earlier will know whether they still need it or not.  I've not experienced any issues with having both the fix and the workaround applied at once, though I also deleted the workaround pretty quickly after testing the fix.

**Comment by emmanuelguerin** [comment]
Hi. In fact this problem is also present for the scala plugin. The workaround works in a similar way. I'm not sure there is an issue for it?

**Comment by JamesXNelson** [comment]
doubtful.  

Up to you if you'd like to add on to the open PR, or make a new one with a ticket of its own.
If you want to add on, just send a PR to the branch, and I can merge... or open a second PR to gradle.

The testing I did might be a little overkill, but should be fairly trivial to duplicate / reuse most of it.

**Comment by dsilvasc** [comment]
@emmanuelguerin Filed an issue for the scala plugin: https://github.com/gradle/gradle/issues/8788

**Comment by ljacomet** [comment]
Was merged in time for 5.3 RC2
