### ISSUE TITLE
Better support for diverse network environments

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7399]
Gradle needs to work in all sorts of corporate network environments, with a wide variety of proxies, mirrors, authentication schemes. In addition, repository servers can be flaky, misconfigured, or slow.

This Epic covers work to improve support for different networking environments, different server configuration, etc.

**Comment by oehme** [comment]
Often times users aren't even aware of the misconfiguration, just getting timeouts and thinking that something is wrong with Gradle, e.g. https://github.com/gradle/gradle/issues/7336

**Comment by jjohannes** [comment]
We don't use this to track work anymore.
