### ISSUE TITLE
Support optional PublicationArtifact

### ISSUE THREAD

**Issue by noproxy** [gradle/gradle#7415]
We have more than one archives to publish, and they are distinguished with different classifiers. Some of these can be optional( such as java-doc, java-src and other our custom artfacts).

The task to build optional artifacts will not be executed because NO-SOURCE. But publishing will fail because the files of the artifacts don't exist. We have to check whether the task inputs is empty  by ourselves and then skip registering the PublishArtifacts.

### Expected Behavior

Some publish artifacts can be marked as optional. 

```java
project.getArtifacts().add(configuration.getName(), archivesOptionalArtifactsTask, artifact -> {
    artifact.setOptional(true);
});
```

When publishing, the optional artifacts will be ignored if the file doesn't exist and won't cause the publishing failing. But publishing will still fail if there is no non-optional artifacts and no optional artifacts is present.

### Current Behavior

Publishing will fail when any artifacts' file do not exists. This will throw

```
Caused by: org.gradle.api.artifacts.PublishException: Cannot publish artifact 'library-verifredLib.jar' (/path/to/library-verifredLib.jar) as it does not exist.
```
### Your Environment

gradle 5.0-milestone-1

**Comment by marcphilipp** [comment]
Is using the new publishing mechanism an option? IIRC it currently has the same limitation but I wouldn't object to adding an `optional` property.

**Comment by noproxy** [comment]
I sort out some to work with this feature.

The new publish plugin provides the ``org.gradle.api.publish.internal.PublicationInternal.addDerivedArtifact`` to register artifacts
 which will be ignored if the file doesn't exist. But it's internally and only used by the built-in Sign plugin.

1. We may simply add new public api to register derived artifact to implement optional artifacts just in maven-publish and ivy-publish plugin. The public api look likes:
```
publishing {
    publications {
        maven(MavenPublication) {
            artifact file('should_exist.jar')
            optionalArtifact file('may_be_exist.jar')
        }
    }
}
```

2. Or we can add an optional property to `org.gradle.api.publish.PublicationArtifact`(and the `org.gradle.api.artifacts.PublishArtifact` which will be deprecated),
and remove the special `derivedArtifacts`. The api may look likes:
```gradle
publishing {
    publications {
        maven(MavenPublication) {
            artifact file('should_exist.jar')
            artifact(file('may_be_exist.jar')) {
                optional = true
            }
        }
    }
}
```

Which one is better? Any advice? @marcphilipp

**Comment by marcphilipp** [comment]
@gradle/dependency-management Could one of you take a look, please?

**Comment by noproxy** [comment]
I finally find that the `org.gradle.api.publish.internal.PublicationInternal.addDerivedArtifact`` can only be used by `Sign Plugin` because it will append an addition extension.

**Comment by xiaoyu-yang-gh** [comment]
any update on this feature?

**Comment by ljacomet** [comment]
Sorry for the late reply

Publishing (or not) artifacts based on other task having outputs or not feels like a very strange publication model.
Unless a clearer set of use cases can be presented, there is no plan to implement such a feature.

If you have those use cases, create a new feature request, possibly linking to this one.
