### ISSUE TITLE
Strange cache between executions

### ISSUE THREAD

**Issue by ethankhall** [gradle/gradle#742]
It looks like Gradle is not executing/recompiling the `Dependency.metaClass.environmentMarkers = bla` in the below sections.

If you were to execution this build script:

```
Dependency.metaClass.environmentMarkers = { String... markerStrings ->
  println delegate
}

configurations {
  compile
  }
repositories {
  mavenCentral()
}
dependencies {
  compile('junit:junit:4.11') { environmentMarkers('sss') }
}
```

Then add a println in the closure, with the daemon running it would not print the second line. If you stop the daemon it will pick up the update on the first run, but then cache the closure again.

**Comment by szczepiq** [comment]
Woah!!! Nice investigation.

metaClass & classloader cache in the daemon

How about this to avoid using metaClass?

```java
dependencies {
  compile('junit:junit:4.11') { ext.environmentMarkers = 'sss' }
}
```

**Comment by ethankhall** [comment]
It was an attempt to access the Artifact, so the environmentMarkers would call `delegate.getName()` to access the dependency name.

**Comment by melix** [comment]
So I tried different variations of the problem, including putting the closure code into a variable, using method closures, resetting the metaclass explicitly, ... and it seems that the only case where this happens is when the closure is used as a meta-method. 

A possibility is that for this specific case it's getting the old class of the closure because Groovy keeps a reference to it somewhere. However even that is strange, because if I introduce an additional closure before the definition of the metaclass, the internal class name of the closure used in the bytecode should change, so it should pickup the new one... Really puzzling.

**Comment by melix** [comment]
Another finding: writing

```
def mc = Dependency.metaClass
println mc.methods.findAll { it.name.startsWith('envir') }*.closure*.call()
```
before and after the assignment shows that the new closure is assigned, and that when we call it, it is the new code being executed.

**Comment by melix** [comment]
Also try this:

```
void bar() {
   println 'Original bar'
}

Dependency.metaClass.environmentMarkers = { String... markerStrings ->
  bar()
}

configurations {
  compile
  }
repositories {
  mavenCentral()
}
dependencies {
  compile('junit:junit:4.11') { environmentMarkers('sss') }
}

task foo {
  doLast {
    bar()
  }
}
```

then call `./gradlew foo`. It's going to print:

```
Original bar
:foo
Original bar
```

Now edit the file and change the `bar` method to:

```
void bar() {
   println 'New bar'
}
```
and execute the build again. This time it's going to print:
```
Original bar
:foo
New bar
```

Which means that when the closure assigned to the metaclass is called, we're calling the old code, but not when running the task action. So it means that we keep the old project class in memory too, which implies a memory leak.

@adammurdoch any idea what could be causing this?

**Comment by melix** [comment]
So here is the explanation: when you write:

```
Dependency.metaClass.environmentMarkers = ...
```

you are changing the metaclass of the `Dependency` class, which is an interface type. Then the method `environmentMarkers` is called on the container, which will perform an [explicit lookup for the metaclass](https://github.com/gradle/gradle/blob/f98789aedee8a532d245aa31fcc32053fc74166d/subprojects/core/src/main/java/org/gradle/internal/metaobject/BeanDynamicObject.java#L136-L139). This has the side effect of settting the metaclass of the _concrete_ type, which is `org.gradle.api.internal.artifacts.dependencies.DefaultExternalModuleDependency_Decorated`.

Then when the second execution of the script with a changed metaclass is done, when `getMetaClass` is found, we're using the same type (`DefaultExternalModuleDependency_Decorated`) which has its metaclass already set. So it will *not* look for the `Dependency` metaclass but instead use the old one.

I tried the same code with a file collection dependency:

```
FileCollection.metaClass.environmentMarkers = ...
...
compile files('foo.jar') { environmentMarkers('sss') }
```

and the behavior is the same, but this time the concrete type is not a decorated type but `org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection`. This means that for `FileCollection` you can workaround by setting the metaclass directly on the `DefaultConfigurableFileCollection` type. The problem with `DefaultExternalModuleDependency` is that you get a decorated type, for which the metaclass is also _per instance_.

A generic workaround for this behavior is to reset the metaclass when the method is called. It comes with a price (for each invocation), but I can't think of anything better now:

```
Dependency.metaClass.environmentMarkers = { String... markerStrings ->
  bar()
  delegate.class.metaClass = null
}
```

Interestingly this is something I cannot reproduce (yet) outside of Gradle.

**Comment by eriwen** [comment]
@melix Is this an actionable task? Do we have enough information and motivation to fix this?

**Comment by zvezdan** [comment]
@eriwen It's a bug in Gradle daemon cache compared to what Groovy as a language specifies.
I had to backtrack on a feature for {py}gradle and use a less appealing syntax for the users of the extension because of this. The simpler syntax worked fine, if not for the caching bug. It was unexpected, based on the language spec, and it was not easy to investigate and debug. It can surprise someone else in the future. I think that should be enough of a motivation to fix the bug.
