### ISSUE TITLE
Test method is not closed after test passed.

### ISSUE THREAD

**Issue by MirekSh** [gradle/gradle#7420]
> 13:12:21.850` [DEBUG] [TestEventLogger] Gradle suite > Gradle test > api.provider.registration.RegistrationTest PASSED
> 13:12:26.120 [LIFECYCLE] [org.gradle.process.internal.health.memory.MemoryManager]
> 13:12:26.120 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17179869184, Free: 5480427520}
> 13:12:26.120 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17179869184, Free: 5480427520}
> 13:12:26.120 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1073741824, Committed: 268435456}
> 13:12:27.212 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
> 13:12:27.213 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 13:12:27.213 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
> 13:12:27.214 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> 13:12:27.214 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
> 13:12:27.214 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
> 13:12:27.215 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
> 13:12:31.120 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 17179869184, Free: 5460381696}
> 13:12:31.120 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 17179869184, Free: 5460381696}
> 13:12:31.120 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1073741824, Committed: 268435456}

### Expected Behavior
Test method should be closed.

### Current Behavior
Test method is not closed after test passed.

### Context
I'm trying to build test suite for rest-assured testing. When I'm running it with IntelliJ IDEA it works like charm.

### Steps to Reproduce (for bugs)
gradlew clean test --tests *RegistrationTest --debug

### Your Environment
Gradle: 4.9
TestNg:  6.14.3
Rest-Assured: 3.1.1
Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.2 ("Oracle Corporation" 10.0.2+13)
OS:           Mac OS X 10.13.6 x86_64

**Comment by marcphilipp** [comment]
Please provide more details what "test method should be closed" means. Does executing the `test` task hang? Can you provide a build scan and/or a sample project?

**Comment by MirekSh** [comment]
@marcphilipp Issue can be closed, when preparing sample project I've started to run:
`gradlew test --tests 'RegistrationTest' --debug`
and it's working fine. Sorry for takim time.
