### ISSUE TITLE
<activity-alias> not working after gradle update

### ISSUE THREAD

**Issue by Liestambeur** [gradle/gradle#7423]
### Expected Behavior
We have one target that uses a different activity then the others. We managed this by adding the following lines in the manifest of that target:
```
        <activity-alias
            android:name="com.twipemobile.twpublishing.ui.to.HomeScreenActivity"
            android:targetActivity="com.twipemobile.client.activity.ClientHomeScreenActivity" />
```
When we launch that tartget the activity ClientHomeScreenActivity should be used instead of HomeScreenActivity.

### Current Behavior
When we use gradle 2.10 it works correctly.
When we upgrade to gradle 4.1 it does not work anymore and the standard HomeScreenActivity is used.

### Context
We are trying to migrate our platform to a newer gradle version. Most features stay the same but the <activity-alias> suddenly get's ignored.

**Comment by oehme** [comment]
For Android issues, please use the [Android issue tracker](https://source.android.com/setup/contribute/report-bugs).
