### ISSUE TITLE
Checkstyle plugin does not include modules from buildSrc

### ISSUE THREAD

**Issue by barnabycourt** [gradle/gradle#7425]
### Expected Behavior
When using the checkstyle plugin I would expect that modules from buildSrc are available when checkstyle is executed. Because they are not included any custom checkstyle modules that are compiled via buildSrc are not on the classpath when the checkstyle module executes. This causes the checkstyle module to fail on initialization of the custom module. I would expect that any custom modules from buildSrc are available on the classpath so that they can be referenced via a custom checkstyle configuration. 

### Current Behavior
The checkstyle module does not include classpath entries for buildSrc jar file.

### Context
I am trying to use a custom checkstyle module that is part of my project without including it in the output of the project. I could do this by using a sub project or putting the custom module in the main path but then I would have to manually filter the custom classes out of the generated artifacts. This becomes even more cumbersome in a multi-project build.  

### Steps to Reproduce (for bugs)

1. Check out https://github.com/barnabycourt/gradle_checkstyle
1. Run `./gradlew check`
1. Observe that the check run failed initializing the custom module & buildSrc is not included on the classpath that checkstyle is using. 

### Your Environment
 * Fedora 28
 * Java 8
* Reproducer Project: https://github.com/barnabycourt/gradle_checkstyle
 * Build scan URL: https://scans.gradle.com/s/bmqm2rt3lcxcy/

**Comment by oehme** [comment]
This is working as intended, checkstyle is run in an isolated classloader with only the rules that were specified on its own classpath - You can create a subproject for your custom checkstyle rules and add that to the [checkstyle classpath](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_dependency_management).

**Comment by barnabycourt** [comment]
@oehme If checkstyle is intended to be running with an isolated classloader why are the build/classes/java/main & build/resources/main directories included by default? Should that be opened as a bug?

**Comment by oehme** [comment]
Because Checkstyle needs them to run some of its checks on your code. It's not entirely source code based.

If it also looks for rules in there then that would be an odd implementation detail of Checkstyle, but not much we can do about. Checkstyle extensions are supposed to go into the `checkstyle` Configuration, as shown in the documentation.

**Comment by barnabycourt** [comment]
@oehme Thanks for the background, I appreciate you taking the time.
