### ISSUE TITLE
Shortcut for install/update the last available version with Gradle Wrapper

### ISSUE THREAD

**Issue by FilipJirsak** [gradle/gradle#7449]
It would be nice if I could tell Gradle to use the last available stable version with `gradle wrapper` task. For example with
```
gradle wrapper --gradle-version=last
```
Now I have to look at the web and copy the version number to the command line.

**Comment by marcphilipp** [comment]
Thanks for the proposal. To be honest, I'm not sure such an option would see much usage.

@gradle/developer-experience WDYT?

**Comment by big-guy** [comment]
@marcphilipp as a data point, in nearly every repo we have we have added extra wrapper tasks to update to a nightly/RC/GA.  I think the only contentious point is whether or not we want to treat the services.gradle.org JSON endpoint as a public API. I'll grant you that we upgrade Gradle more than most people would.

**Comment by eriwen** [comment]
I think this is such a good idea that I wrote [a spec](https://github.com/gradle/gradle/blob/v3.5.0/design-docs/automatic-upgrades.md) for this roughly 2 years ago :) 

I'm going to give my 👍 here but admit that this isn't the first issue I would personally pick up. I would be happy for us to entertain PRs here.
