### ISSUE TITLE
Introduce an easy fail if no tests config option

### ISSUE THREAD

**Issue by OlgaMaciaszek** [gradle/gradle#7452]
There should be an easy config option to mark that the build should fail if no tests were executed. In Maven, it's very easy to achieve by setting the surefire plugin option like so: `<failIfNoTests>true</failIfNoTests>`. There should be an easy option to set it up in gradle.

### Expected Behavior
It would be good to have an easily available config option, like:

```[groovy]
test {
	failIfNoTests()
}
```

### Current Behavior
Right now, the following workaround is possible:
```[groovy]
test {
	afterSuite { desc, result ->
		if (!desc.parent) {
			if (result.testCount == 0) {
				throw new IllegalStateException("No tests were found. Failing the build")
			}
		}
	}
}
```

**Comment by marcphilipp** [comment]
Just to be sure we're on the same page: The use case for this feature is that no tests is likely due to a configuration error or is there another scenario where this might be useful?

**Comment by OlgaMaciaszek** [comment]
The scenario would be that no tests were executed - either the config is wrong (I've just recently had this happen when I used a deprecated gradle jupiter plugin, I guess there are a lot of ways that a bad config can mess up test execution) or, as well, if the developers have not added any/ have removed all the tests from the module. So, in essence, the `test` task has been run, but no tests were executed, for whichever reason.

**Comment by szpak** [comment]
I recently ran into that issue after a migration of all my tests to JUnit 5. I forgot to add `useJUnitPlatform()` and all the tests were executed from Idea, but none of them from Gradle. Having that option available would help me to spot it on the first local or Travis build (I noticed that quite fast only thanks to the weekly sanity builds on Jenkins which started to complain about missing reports).

**Comment by Comnir** [comment]
I think the flag [setFailOnNoMatchingTests ](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestFilter.html#setFailOnNoMatchingTests-boolean-) can be set in a filter block to achieve this behavior. I found this suggestion [here](https://discuss.gradle.org/t/multi-module-build-fails-with-tests-filter/25835).

BTW, I'd the opposite issue, i.e., no tests ran, but the Gradle run failed. I ran a test task with a package filter:
> gradle  --tests com.my.package.*

This failed in my case, because one of the project modules didn't have this package.

**Comment by szpak** [comment]
I have found the limitation of that approach. Starting with 6.4, Gradle is able to detect some internal errors of the JUnitPlatform (or the test engines running the platform) and report it as an artificial failing test itself:
![image](https://user-images.githubusercontent.com/148013/85689580-0c5d0980-b6d3-11ea-93e2-f29ef8577c73.png)

However, if an exception about "no tests found" is thrown, then the original error is completely hidden (visible only with `--debug`) - see https://github.com/szpak/spock-global-unroll/issues/7 .

@marcphilipp Do you see any good way (better than detecting `Gradle Test Executor` in the test class name) in Gradle 6.4+ to both detect "no tests found" (and fail) and do not hide internal JUnit Platform errors (as in https://github.com/szpak/spock-global-unroll/issues/7)?

**Comment by marcphilipp** [comment]
@szpak I've fixed that for 6.7 in #13879.

**Comment by xenoterracide** [comment]
curious, does this first need to be an issue fixed in junit? an API for gradle to consume?

**Comment by xenoterracide** [comment]
also, I would argue that this should be the default, and there should be a `passWithNoTests()` option, as this is most likely to happen early in a project due to configuration error.

**Comment by marcphilipp** [comment]
I don't think this requires any changes in JUnit. Making it fail on no tests by default would break existing projects and be annoying when starting a new Gradle project from scratch, though, wouldn't it?

**Comment by xenoterracide** [comment]
> break existing projects 

presumably only if they had a test block and no tests were running, which if that's true is important in CI

> Annoying when starting a new Gradle project from scratch

no, it wouldn't be for me, and like my description on the other ticket, this is even the default for things like jest. no tests is a failure to test in and of itself, imho. besides, it'd be easy to disable right when you're adding the test block in the first place.

**Comment by xenoterracide** [comment]
are patches welcome?

**Comment by xenoterracide** [comment]
I have a new reason to want this, `jacoco` doesn't generate a report or fail if there are no tests. At least not if you use it the way the documentation suggests using it.

**Comment by xenoterracide** [comment]
Actually, I have a new reason, turns out jacoco doesn't generate a report if there are no tests, at least not in the way the documentation says to do it. Which means you won't fail code coverage, either.

**Comment by xenoterracide** [comment]
just as an FYI, Implemented the above workaround in kotlin, but have also asked for a nicer API to avoid the closure.

```kts
  afterSuite(
    KotlinClosure2<TestDescriptor, TestResult, Unit>(
      { descriptor, result ->
        if (descriptor.parent == null) {
          logger.lifecycle("Tests run: ${result.testCount}, Failures: ${result.failedTestCount}, Skipped: ${result.skippedTestCount}")
          if ( result.testCount == 0L ) {
            throw IllegalStateException("You cannot have 0 tests");
          }
        }
        Unit
      })
  )
  ```

**Comment by xenoterracide** [comment]
furtherly I have ^ that, but I realized there's still a problem, that doesn't execute if the suite isn't... which means this functionality also has to validate that there is actually a source set or something to run for tests.

```
> Task :util:test:test NO-SOURCE
file or directory '/home/xeno/IdeaProjects/pm/backend/module/util/test/build/classes/java/test', not found
Skipping task ':util:test:test' as it has no source files and no previous output files.
:util:test:test (Thread[Execution worker for ':' Thread 7,5,main]) completed. Took 0.0 secs.
:util:test:jacocoTestReport (Thread[Execution worker for ':' Thread 7,5,main]) started.
```

**Comment by xenoterracide** [comment]
I have encountered further issues along the way, if tests source does not exist, tests may not be run, and so it will not fail. If something in buildSrc is changed that may not be run, and so tests will still not fail. I believe these 2 hacks will fix that.

Can we please get a simple option for this?

```kts
val available = tasks.register("tests available") {
  sourceSets.getByName("test") {
    if (java.isEmpty) throw FileNotFoundException("no tests found")
  }
}

tasks.test.configure {
  inputs.dir(buildSrcSourceRootsFilePath)
  finalizedBy(available)

  afterSuite(
    KotlinClosure2<TestDescriptor, TestResult, Unit>(
      { descriptor, result ->
        if (descriptor.parent == null) {
          logger.lifecycle("Tests run: ${result.testCount}, Failures: ${result.failedTestCount}, Skipped: ${result.skippedTestCount}")
          if ( result.testCount == 0L ) {
            throw IllegalStateException("You cannot have 0 tests");
          }
        }
        Unit
      })
  )
}
```

**Comment by FrauBoes** [comment]
Successfully running the test task with no test to execute is to be deprecated. This means the behaviour requested here will eventually become the default. 

In the meantime, to have the test task fail in this scenario, you can use `test.getFilter().setFailOnNoMatchingTests(false)`. If `isFailOnNoMatchingTests == true`, the test task will fail, if `isFailOnNoMatchingTests == false`, test will run without a deprecation warning.
