### ISSUE TITLE
[Epic] In-Memory Plugin Repositories

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#746]
The idea for solving this is for us to provide an API that one can use to build a plugin repository implementation, which is effectively just a mapping table. The user is responsible for sourcing whatever data they need and building the definition. There are several possible variants on this; e.g. a callback/factory style API instead of specify everything up front.

This plugin repository would participate in resolution just like other plugin repositories.

**Comment by oehme** [comment]
Closing, as this has been solved by the `pluginManagement {}` DSL
