### ISSUE TITLE
Add Kotlin snippets to Plugin Guide

### ISSUE THREAD

**Issue by NikkyAI** [gradle/gradle#7467]
### Expected Behavior
For someone interestedi n writing gradle plugins with Kotlin there should be a official Guide available

### Current Behavior
https://guides.gradle.org/writing-gradle-plugins/ contain only java sources

adding a Kotlin tab to the code blocks would be fine, since the structure of gradle plugins does not change between groovy, java and kotlin

**Comment by jmfayard** [comment]
I will provide the kotlin version of those java snippets

**Comment by eriwen** [comment]
Thanks for the report and info folks! 

We'll consider this, but we must also add to such a guide tips to ensure Groovy-friendly configuration (such as "use `Action`").
