### ISSUE TITLE
Add way to run wrapper task without configuring entire project

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#7475]
I have some plugins that I have switched major versions, and have switched them to use the new Task Provider APIs added in 4.9. I have gotten a decent amount of complaints from my users where they upgrade my plugin, and then their project fails to configure because they are still on an old version of gradle. An easy solution would be to just have documentation to have my users run `./gradlew wrapper --gradle-version=4.9`, and then have that upgrade the wrapper in their project. However, this fails as the entire project is required to be configured before running the wrapper task. There should be a way to shortcut this task when ran from the command line, so the entire project doesn't have to be configured.

**Comment by davidburstrom** [comment]
I'd suggest you'd run `./gradlew :wrapper --gradle-version=x` instead (note the leading colon). If you have configuration on demand enabled, this will configure only the root project.

**Comment by ThadHouse** [comment]
This is still an issue for us, so commenting to reopen the issue.

**Comment by davidburstrom** [comment]
@ThadHouse Did you see [this comment](https://github.com/gradle/gradle/issues/7475#issuecomment-582790374)? Or are you asking that no configuration should take place at all?
