### ISSUE TITLE
Gradle 3.1 change: "replaced" change type breaks compatibility with existing plugin

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#748]
The change adds a new ChangeType value `REPLACED` (reference: https://github.com/gradle/gradle/commit/0a4a3bbb16425acfcce84f02001b87c4faede233). This leads to two issues:

`FileChange` has not been updated to provide a `isReplaced()` method so plugins cannot query for this kind of file change. Because `OrderSensitiveTaskFilePropertyCompareStrategy` has been changed to exclusively use the new status instead of `MODIFIED` some file changes cannot be detected by new task implementations.

However a bigger problems is that existing plugins that go through `IncrementalTaskInputs.outofDate` looking at `isModified()` will also always miss the files that use the new status. The only fix is to release a new version of the plugin (after the new API is fixed with a new `isReplaced()` method).

In order to be compatible, I believe Gradle should make these replaced files return `true` for both `isModified()` and `isReplaced()`. This require some more refactoring as `FileChange` only support a single `ChangeType`.

The Gradle plugin for Android is failing some of its tests on 3.1 because of this.
- JIRA issue: [GRADLE-3577](https://issues.gradle.org/browse/GRADLE-3577)
- Internal review: [REVIEW-6345](https://code-review.gradle.org/cru/REVIEW-6345)

**Comment by lptr** [comment]
FTR: the task output cache team is tracking this issue as ☝️.

**Comment by wolfs** [comment]
LGTM. I think we should open a JIRA issue (this affect 3.1, right)? Should we also add something to the release notes apart from the JIRA issue which will be automatically added? I think the issue should be enough.

**Comment by lptr** [comment]
Added JIRA issue. I also think it should be enough for the release notes.

**Comment by eriwen** [comment]
Closing as delivered in Gradle 3.2
