### ISSUE TITLE
GRADLE_OPTS documentation in build environment is misleading

### ISSUE THREAD

**Issue by Starch** [gradle/gradle#7491]
I found the documentation of GRADLE_OPTS to be misleading. For instance [here in the current documentation](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables):

    GRADLE_OPTS
        Specifies command-line arguments to use when starting the Gradle client. This can be useful for setting the properties to use when running Gradle.

It made me think that I could have used ``GRADLE_OPTS=-Poption=value`` or ``GRADLE_OPTS=--no-daemon`` as the doc talks about gradle command-line arguments, with a link to [cli interface](https://docs.gradle.org/current/userguide/command_line_interface.html#command_line_interface).

### Expected Behavior
* *gradle* command-line arguments should be accepted in GRADLE_OPTS, or
* the documentation should be changed to state that GRADLE_OPTS can only be provided with *JVM* arguments, such as ``-Doption=value`` for setting a system property (very as same as JAVA_OPTS).

### Current Behavior

```shell
$ GRADLE_OPTS=--no-daemon ./gradlew clean
Unrecognized option: --no-daemon
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Context
I wanted to give command lines arguments to gradle via GRADLE_OPTS envvar, such as the ``--no-daemon`` option in my CI environment.

### Your Environment
* gradle 4.10.2
* openjdk 11+28

**Comment by oehme** [comment]
Done in https://github.com/gradle/gradle/commit/c0593bfa8a5da9135593ea6325c9356129c17536

**Comment by IanVS** [comment]
>Unrelated advice: Don't use --no-daemon, it will make your builds slow.

What about in CI?  I've seen it recommended to use this setting when running CI because it leads to more repeatable results.  Is that not the case?
