### ISSUE TITLE
Unable to import the specified dependencies

### ISSUE THREAD

**Issue by xiaoxing598** [gradle/gradle#7495]
### Expected Behavior

I managed to rely on the cradle in the IDE. When adding a `org.springframework.cloud:spring-cloud-gateway:2.0.1.RELEASE` dependency, I found that it could not be imported automatically, and reloading would not work. Because it didn't give me an error, I don't know what happened.

### Current Behavior

The dependencies I added were not introduced and there were no errors.

### Context

I want IDE (IntelliJ IDEA) to be able to introduce specified dependencies

### Steps to Reproduce (for bugs)

![97cfaf92-1c6a-4b5b-a43b-feb29885009b](https://user-images.githubusercontent.com/5615719/47354096-5ddc1680-d6f0-11e8-9c8c-dba1309a690d.jpg)

### Your Environment

idea:2018.2.5
gradle:4.10.2
window7

**Comment by oehme** [comment]
Please provide a reproducible example project.

**Comment by xiaoxing598** [comment]
@oehme  `https://github.com/xiaoxing598/demo.git` Please take a look, thank you!

**Comment by ghale** [comment]
The above url is not valid (or at least is no longer valid).  Closing this for now - if you can provide something reproducible, we can take another look.
