### ISSUE TITLE
Please back port 7059 fix to 4.10.3

### ISSUE THREAD

**Issue by daschneider** [gradle/gradle#7500]
### Expected Behavior

./gradlew build should run the junit cases.

### Current Behavior

~~~
Execution failed for task ':test'.
> failed to read class file xxx
~~~

### Context
Prevents upgrading to Java 11 (unless we skip running unit tests).  We need to upgrade to Java 11 but can not wait for Gradle 5.0 upgrade.

### Steps to Reproduce (for bugs)
See issue #7059

### Your Environment
See issue #7059

**Comment by daschneider** [comment]
Thanks for including this fix in 4.10.3.  Is there an estimated release date for 4.10.3?

**Comment by malejpavouk** [comment]
Is there any way how to force Gradle (4.10.2) to use the new asm in the meantime, till 4.10.3 is released? 

This causes us troubles as it makes impossible to compile tests, which contain nested class.

**Comment by marcphilipp** [comment]
I'm afraid, there is no way to force 4.10.x to use a newer ASM version.

**Comment by big-guy** [comment]
We can't fully support JDK11 in 4.10.3, but we backported a fix that may allow some builds to work with JDK11.
