### ISSUE TITLE
Play 2.4 route compilation errors were silently ignored

### ISSUE THREAD

**Issue by garylin** [gradle/gradle#7502]
When compiling play routes with gradle's play plugin, errors were silently being ignored.  

### Expected Behavior
Route compilation error should cause the build to failed with the corresponding compilation error message displayed to the the user.

### Current Behavior
If routes file contains errors, in several cases, the build will still be completed with no default route generated.  As the results, all requests sent to the play application will return 404.

### Context
The issue lies with Gradle’s Routes Compiler, where it assumes the return type of the route compile method is Boolean (This is true in Play 2.2, but not Play 2.4 or later):
https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/internal/routes/RoutesCompiler.java#L74 

In Play 2.4 adapter, it is compiling the route using play.routes.compiler.RoutesCompiler.compile() method:
https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/internal/routes/RoutesCompilerAdapterV24X.java#L60 

However, as you can see, the compile method returns an Either instead of a Boolean:
https://github.com/playframework/playframework/blob/2.4.x/framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala#L80 
When there is a route failure (when compile method returning an Either object with route compilation errors), the logic in the RoutesCompiler will simply treat it as successful. 

Maybe we need to have RoutesCompilerAdapter to also handle the route compilation return value, normalizing it before returning it back to RoutesCompiler.

### Steps to Reproduce (for bugs)
Found in: Gradle 4.8
Play: 2.4 (the issue is likely applicable to later version)

Create a play route that will results in compilation failure.  For example, create a controller:

```
package com.foobar;
import play.mvc.Controller;
import play.mvc.Result;


public class HelloController extends Controller {
  public Result index() {
    return ok("Hello");
  }

  public Result index(String path) {
    return ok("Hello");
  }
}
```

And then use the routes file below:

```
# This will cause route compilation failure since overload is not supported.
GET        /        com.foobar.HelloController.index()
GET        /*path   com.foobar.HelloController.index(path)

```
When build with gradle (gradle compilePlayBinaryPlayRoutes), the build completes successfully without any compilation failures.

### Your Environment
Found in: Gradle 4.8
Play: 2.4 (the issue is likely applicable to later version)

**Comment by big-guy** [comment]
Thanks for the really thorough bug report @garylin 

I took a stab at adapting the result from a 2.4+ compiler.  Could you give `5.1-20181027042452+0000` a try?
