### ISSUE TITLE
AbstractMavenPublisher results in lost System.out

### ISSUE THREAD

**Issue by AmlingPalantir** [gradle/gradle#7506]
### Expected Behavior
During the build lines printed to System.out reach gradle stdout.

### Current Behavior
Observed only during our longest and terriblest builds, System.out will sometimes "flicker" (alternating between making it to gradle stdout and not) and ultimately stop coming through.

### Context
Nope.

### Steps to Reproduce (for bugs)
I tried to reproduce this with simpler cases but I just could not get the timing.  The data I can give based on debugging and print instrumenting our long and terrible builds that reproduce this:

*) Multiple instances of StartableLoggingSystem exist, all pointed at the same DefaultStdOutLoggingSystem.
*) Each start() saves the previous log level and sets it to some specified value, and each stop() resets it to the saved value.
*) start/stop are called on these in a manner that is "consistent" per StartableLoggingSystem instance, but not for the shared DefaultStdOutLoggingSystem as a whole (e.g.  you can have start1, start2, stop1, stop2).
*) Almost all of these set log level QUIET so it sort of doesn't matter, all saved values are QUIET.
*) But!  AbstractMavenPublisher.execute produces one at INFO.
*) An interleave happens like:  start1 INFO, start2 QUIET (saves INFO), stop1 INFO (restores original), stop2 QUIET (restores INFO!)
*) System.out events from then on get level INFO which means they're dropped later (some later piece of logging infrastructure has threshold LIFECYCLE which passes QUIET and drops INFO).

### Your Environment
This is all as of gradle 4.10.2.  It's unfortunately a long way off to upgrade our long and terrible builds to newer gradle and as mentioned, I failed to engineer a free-standing repro so I can't really test newer gradle.

**Comment by AmlingPalantir** [comment]
[trace.txt](https://github.com/gradle/gradle/files/2507792/trace.txt)

This is the logging I got from StartableLoggingSystem during the relevant part with commentary added on the important lines.

**Comment by big-guy** [comment]
@AmlingPalantir could you try the latest nightly? I think this may be fixed.

You can upgrade with `gradlew wrapper --gradle-version=5.1-20181126000019+0000`

**Comment by AmlingPalantir** [comment]
Unfortunately our build is on the complex side and is unlikely to just work with a newer version of gradle.  I'll look into it, but in the mean time, was there a specific change you thought might have fixed it?

**Comment by AmlingPalantir** [comment]
Oh, obviously 7bc44d5b1ec0.  Nm.  Upgrade still ... in progress.

**Comment by big-guy** [comment]
There was some logger juggling that was starting/stopping the logger system while publishing that looked unnecessary.

**Comment by AmlingPalantir** [comment]
Well, that was an adventure.  I'm not sure we'll be able to upgrade our actual build right away, but I was able to get enough of it running and use the same process to both reproduce the issue on 5.0-20181121000205+0000 and not reproduce the issue on 5.1-20181126000019+0000.

**Comment by ghale** [comment]
Based on the comment above, I'm going to close this as fixed.  If you feel like there's still something that needs to be addressed here, we can always re-open it.
