### ISSUE TITLE
Invalid module name for jboss.jaxb.api.2.3.spec

### ISSUE THREAD

**Issue by nlisker** [gradle/gradle#7516]
Trying to run a project with a dependency 

    compile "org.jboss.resteasy:resteasy-client:3.6.1.Final"

will result in an error:

```
> Task :run FAILED
--
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for C:\Users\Nir\.gradle\caches\modules-2\files-2.1\org.jboss.spec.javax.xml.bind\jboss-jaxb-api_2.3_spec\1.0.0.Final\fd03ab1e2b25dcf20af049d34ef4b8d2d97b73f\jboss-jaxb-api_2.3_spec-1.0.0.Final.jar
Caused by: java.lang.IllegalArgumentException: jboss.jaxb.api.2.3.spec: Invalid module name: '2' is not a Java identifier
```
I have [reported](https://issues.jboss.org/browse/RESTEASY-2039) it to the RESTEasy devs and they suggest it's a problem in Gradle.

I am using Buildship, and looking at the dependency configuration, the dependency is on the classpath. The automatic module naming process is attempting to use the jar name and fails.

### Expected Behavior
No error when running.

### Current Behavior
The above error while running.

### Context
Cannot run any project which depends on the RESTEasy client.

### Steps to Reproduce (for bugs)
Create a project with:

```
apply plugin: 'java'

repositories {
    jcenter()
}

sourceCompatibility = 11
targetCompatibility = 11

dependencies {
    compile "org.jboss.resteasy:resteasy-client:3.6.1.Final"
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.10.2'
}
```
and execute `run`.

### Your Environment
* OpenJDK 11
* Gradle 4.10.2
* Buildship 3.0.0
* Eclipse 2018-09 (4.9) (patched for Java 11)
* Win10

**Comment by oehme** [comment]
I don't see how this would be a problem in Gradle. They put a digit into their artifact id and jigsaw forbids numbers in module identifiers. So automatic module conversion will fail. They need to give it an explicit module name.
