### ISSUE TITLE
Make project.sync() a public API

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#752]
I thought we had already done this at some point.

We already have `project.copy`, we should provide the Sync-equivalent.

**Comment by eriwen** [comment]
@big-guy We're booked for 3.3, so I think this should go in the next release after that unless it's very easy. Any thoughts? Is this easy enough we could ask for outside contribution?

**Comment by big-guy** [comment]
It's pretty easy.

We need to add the `sync` method with the signature `WorkResult sync(Action<? super CopySpec> action);` and documentation to `subprojects/core/src/main/java/org/gradle/api/Project.java` 

We need to add the method to the DSL here: `subprojects/docs/src/docs/dsl/org.gradle.api.Project.xml`

Make sure we have decent test coverage, something like we do in `CopyTaskIntegrationSpec` and `CopySpecIntegrationSpec` in `SyncTaskIntegrationTest` or a new class.

**Comment by big-guy** [comment]
Note that we do not want a Closure version of this method.

**Comment by ajoberstar** [comment]
👍

**Comment by oconnelc** [comment]
I maybe able to take a look at it this weekend.

**Comment by hotchemi** [comment]
Can I grab the issue?

**Comment by big-guy** [comment]
Sure, please make sure you take a look at our [contributing guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md).

**Comment by hotchemi** [comment]
Addressed on https://github.com/gradle/gradle/pull/1137!
Btw, I found two `NotYetImplemented` annotations in integtests file. Would they be another story to enhance?

- https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy#L173
- https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/SyncTaskIntegrationTest.groovy#L200

**Comment by big-guy** [comment]
Thanks @hotchemi.  I'll take a look.

Yes, those are both areas that we need to improve. You can leave those alone for this story.  We have a general problem with the `Copy`-like tasks having under specified inputs like that.

**Comment by hotchemi** [comment]
@big-guy Thank you for your response. Okay, so let me try to fix them when I can get a time to look into if it's okay.

**Comment by henryptung** [comment]
@big-guy Why no closure version?
