### ISSUE TITLE
Gradle plugins 3.2.1 found "\r" pack to apk become r in string

### ISSUE THREAD

**Issue by ZhangHowie** [gradle/gradle#7521]
### Expected Behavior
I change the gradle plugins from 2.3.3 to 3.2.1, in the string.xml "\r" pack to apk ,then I found the app will translate the "\r" to "r" , in the previous of Gradle 2.3.3 version doesn't exit this problem.

### Current Behavior
Android "\r" in the string.xml pack to apk then you will find the "\r" to "r"

### Steps to Reproduce (for bugs)
Android in string.xml, add one word append "\r", then "r" will be append
### Your Environment
Android Studio 3.2.1
Gradle 3.2.1
Gradle wrapper 4.6-all
 * Build scan URL:

**Comment by lptr** [comment]
This sounds like an Android plugin issue, please report on the Android issue tracker: https://issuetracker.google.com/issues/new?component=192709&template=842921
