### ISSUE TITLE
Gradle's built in Logger should use `getDisplayName` when logging Describables

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#7530]
Many things in Gradle's code base implement `Describable`. The `displayName` is expected to be a human readable description. This description should be used when logging things automatically.

So let's say your code does the following:
```
Logger logger = LoggerFactory.getLogger(MyClass.class);
Describable myDescribable;
logger.info("This should log the display name of {}", myDescribable);
```

### Expected Behavior
The display name of `myDescribable` is logged when the info log is enabled

### Current Behavior
The result of `toString()` of `myDescribable is logged.

### Context
Currently, if you want to log the display name and not evaluate the display name if logging is disabled since it may be expensive you need to do something like
```
if (logger.isInfoEnabled()) {
    logger.log("My info is {}.", describable.getDisplayName());
}
```

That is annoying and error prone.

**Comment by lptr** [comment]
This is a great idea. Whoever implements this should check all the places where we wrap logger calls with `if (LOGGER.isXxxEnabled()) { ... }` only because of a describable, and unwrap the call there.
