### ISSUE TITLE
BuildScans should accept license agreement command line option

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#7534]
Currently there are two ways of using build scans plugin:

* `--scan` command line option
* install de plugin

The second one allows to configure in your buildscript the license agreement acceptance 

```
buildScan {
    termsOfServiceUrl = 'https://gradle.com/terms-of-service'
    termsOfServiceAgree = 'yes'
}
```

with the command line option, this is not possible.

### Expected Behavior
A command line option for `--scan` to also accept the license terms

### Current Behavior
You need to install the plugin and add the closure to your build script

### Context
Nebula plugins used to provide build scan plugin as part of it for all other nebula plugins, this way it would be possible for us to publish build scans without applying the plugin and reducing the boilerplate across repositories.

However, with Gradle 5.x+, engineers would have to use build scans 2.x which does not work on gradle 4.10 or older. More info here -> https://github.com/nebula-plugins/nebula-plugin-plugin/pull/49. This is a breaking change for our consumers.

**Comment by ldaley** [comment]
@rpalcolea thanks for the report. I'll look into it. It will be simple enough to do, but we need to verify it meets the legal requirements.

**Comment by allco** [comment]
It's kinda sad that it is not fixed and just closed without any explanation.
