### ISSUE TITLE
pom artifacts force hard coded compile dependency reference version number : hard coded works vs. variable fails

### ISSUE THREAD

**Issue by txpokey** [gradle/gradle#7538]
### Expected Behavior

expect both to work: 
`      compile group: 'org.codehaus.groovy', name: 'groovy-all', version: '2.5.2', ext: 'pom' 
`
`     compile group: 'org.codehaus.groovy', name: 'groovy-all', version: "${groovyVersion}", ext: 'pom'
`
but the hard coded version number is the one that works. 
But ideally I should be able just to say: 
`compile("org.codehaus.groovy:groovy-all")`
which is what I can do when the artifact is NOT a pom. 
### Current Behavior

this bug pops up when the artifact is a pom; when its a pom artifact, the hard coded version number is required. And then using the ${groovyVersion} substitution, I get the following error: 
`Could not resolve all files for configuration ':projectCertifyJava:compileClasspath'.
> Could not find org.codehaus.groovy:groovy-all:'2.5.2'.
  Required by:
      project : ...`
### Context

I'm trying to keep version numbers in my gradle.properties. But in fact, I should be able to use the following line but for the fact that this artifact is now set up as a pom on mavenCentral. 
`compile("org.codehaus.groovy:groovy-all")
`. when the revision is NOT a pom, leaving out the version number works just fine. 
### Steps to Reproduce (for bugs)

I committed the failing code on SHA = bb08cb7 on the master branch of the following : [github project](https://github.com/txpokey/projectCertify)
### Your Environment

 * Build scan URL: [build scan](https://scans.gradle.com/s/g4u3mnjd6yitg)

**Comment by ljacomet** [comment]
The issue comes from [this line](https://github.com/txpokey/projectCertify/commit/bb08cb7a83b1535fcd9d04be655c6d4fede20dae#diff-503f218d646c10f484fdc9d6315bf2e3R1).

As you can see in the error message you posted:
> Could not find org.codehaus.groovy:groovy-all:'2.5.2'.
> Required by:
> project : ...`

the problem comes from the extra quotes you copied over in the properties file.

Removing them will fix your problem.

**Comment by txpokey** [comment]
awesome catch. solved two problems i had.
