### ISSUE TITLE
Add ability to specify "name" for task.onlyIf actions (and possibly others like upToDateWhen)

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#7541]
`doFirst` and `doLast` offer the ability to specify a description/name for the action. It would be 

### Expected Behavior

```
Skipping task ':MyTask' as task onlyIf "only when executing in CI environment" is false.
```

### Current Behavior

```
Skipping task ':MyTask' as task onlyIf is false.
```

### Context

It is difficult to understand an `onlyIf`, especially if it is a composed `onlyIf` of multiple actions. It would be useful if the logs and other pieces told you why it was not executed.

**Comment by wolfs** [comment]
This is still something we should do.
