### ISSUE TITLE
Problems utilizing client certs from Windows-MY or KeychainStore

### ISSUE THREAD

**Issue by tiguchi** [gradle/gradle#7546]
# Problem
I want to use client certificates for authorizing a development workstation to access a private Maven repository that requires client certificates for access.

For that I want to utilize the default key store of the development platform (Mac OS X or Windows).

The Mac OS X keychain store or the Windows certificate store can be used by setting up the following system properties:

```
javax.net.ssl.keyStoreType=(Windows-MY|KeychainStore)
```

However the following line of code which is responsible for setting up the SSL context for Gradle requires that also an existing keystore file must be specified in order to utilize the Keychain or Windows certificate store:

https://github.com/gradle/gradle/blob/08a7cd33880b7b816e791d95d2fe68dc237a6afa/subprojects/resources-http/src/main/java/org/gradle/internal/resource/transport/http/DefaultSslContextFactory.java#L147

## Expected Behavior

The keystore file should not be a requirement for setting up the key store.

## Workaround

Create empty file and also set it via

```
javax.net.ssl.keyStore=/path/to/dummy-file
```

This convinces Gradle's SSL context init routine to pick up the platform's key store.

**Comment by rieske** [comment]
Fixed by https://github.com/gradle/gradle/pull/7661
