### ISSUE TITLE
ExtensionAware should be exposed on Gradle API types that can be extended

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#7547]
Gradle API types that can be extended, ie. public extension points, should expose the `ExtensionAware` type to allow access and configuration of extensions in statically typed languages. 

In the Gradle API, `Settings`, `Project`, `DependencyHandler`, `Task` and `SourceSet` already do. `Gradle` and `RepositoryHandler` are good candidates, the latter is extended by the `javascript-base` plugin and the latter has community interest (#7414). There's also `JavaScriptExtension` that is itself extended by each of the javascript plugins.

There're also types extended in community plugins. One good example is the [org.jetbrains.gradle.plugin.idea-ext](https://github.com/JetBrains/gradle-idea-ext-plugin) plugin that currently has to cast [Gradle API objects](https://github.com/JetBrains/gradle-idea-ext-plugin/blob/423e75ff40e209f963eb84d24f942bfe1f47faca/src/main/groovy/org/jetbrains/gradle/ext/IdeaExtPlugin.groovy#L30) and [own objects instantiated by Gradle](https://github.com/JetBrains/gradle-idea-ext-plugin/blob/423e75ff40e209f963eb84d24f942bfe1f47faca/src/main/groovy/org/jetbrains/gradle/ext/IdeaExtPlugin.groovy#L32) to `ExtensionAware` to register its extensions. Builds using that plugin also have to cast in order to configure its extensions.

- [ ] list public extension points
- [ ] let all public extension points implement `ExtensionAware`

Blocked by #7548

**Comment by oehme** [comment]
Why do we want to statically expose this if we only have a handful of use cases? Note that every single DSL object in Gradle is extensible, so this list would be very long. The few plugins that actually extend anything except the project could cast to ExtensionAware.

Accessing extensions shouldn't need casts, the Kotlin DSL should generate accessors.

**Comment by eskatos** [comment]
Not all model elements are extensible, only the ones that are instantiated and decorated by Gradle. For example, the API allows to add extensions instantiated by user code, undecorated. We do this in several places, community plugins too. Because of that, casting to `ExtensionAware` won't work uniformly. In that regard, having a way to tell if something is extensible makes sense to me.

Accessing extensions from statically typed languages currently requires casting in all cases but using the Kotlin DSL with available accessors.

**Comment by adammurdoch** [comment]
> the API allows to add extensions instantiated by user code, undecorated

This will be deprecated at some point. All extensions will need to be well formed model objects (whatever that happens to mean at the time, at the very least it will mean that Gradle owns the instantiation).

**Comment by JLLeitschuh** [comment]
> This will be deprecated at some point. All extensions will need to be well formed model objects (whatever that happens to mean at the time, at the very least it will mean that Gradle owns the instantiation).

For the Kotlin based plugins if Gradle must instantiate all extension objects, this will prevent being able to add arbitrary function to the `ExtensionContainer`. For example like this:

```kotlin
val somethingUsefulImpl = fun() {
    println("Hello world project ${project.name}!")
}
project
    .extensions
    .add(
        typeOf<() -> Unit>(),
        "doSomethingUseful",
        somethingUsefulImpl
   )
```

This is also being discussed here:
#7427

In the above example, `somethingUsefulImpl` is a final subtype of `kotlin.jvm.functions. Function0`. Currently, Gradle can't decorate final types.

The above is a contrived example, but there are practical applications that allow plugin authors to expose the API they want on various types dynamically.

## Aside
I proposed a more general solution to this "multiple inheritance" problem here:
https://github.com/gradle/gradle/issues/7548#issuecomment-434837341

**Comment by eskatos** [comment]
A use case that was risen by a build author for `Gradle : ExtensionAware` is accessing extra properties.

In a kotlin build script you can't do 
```kotlin
val foo: String? by gradle.extra
```
nor access the extra properties using the API
because `Gradle` doesn't implement `ExtensionAware`.

One need to cast as a workaround:
```kotlin
val foo: String? by (gradle as ExtensionAware).extra
```
