### ISSUE TITLE
About update gradle from 2.3 to 3.2 not find Task.getProviders()

### ISSUE THREAD

**Issue by weatherfish** [gradle/gradle#7549]
Hello

I Update my gradle from 2.3 to 3.2.

and the gradle2.3 has API Task.getProviders . but the newer do not have the API . 

the error msg is : 

 ``` 
Could not find method getProviders() for arguments [] on task ':phantom-sample:plugin-component:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.
```

**Comment by oehme** [comment]
You only updated the Android plugin, not Gradle. You need to upgrade Gradle too.

**Comment by weatherfish** [comment]
> You only updated the Android plugin, not Gradle. You need to upgrade Gradle too.

I update my  Android plugin 2.3 . and Gradle 4.6
I write a test gradle plugin and used getProviders()
