### ISSUE TITLE
Update java-library plugin documentation to describe the performance benefits over java plugin.

### ISSUE THREAD

**Issue by jlstrater** [gradle/gradle#7558]
A user expressed confusion regarding the difference between 'java' and the 'java-library' plugin implementation. He said:

I read the docs multiple times and I don't quite get the difference between `java` and `java-library`.
Both plugins provide `implementation` configuration, which seems to be working as expected within the project (`implementation` dependency is not exposed to consumers). `java-library` plugin provides `api` configuration, whereas `java` provides `compile` configuration.
But `compile` and `api` dependencies are exposed to consumers, so I wonder what are the benefits of using `java-library`

I struggle with this too and think the documentation could be clearer.

The suggested responses were:
 * There are differences, as shown in the table in the section https://docs.gradle.org/4.10.2/userguide/java_library_plugin.html#sec:java_library_configurations_graph
Though understanding these differences is mainly for plugin authors

 * The primary benefit of using `java-library` is that Gradle defines an additional “classes-dir” variant. This variant is not published, but when the java-library project is consumed as a project dependency, we don’t need to build the library jar just in order to compile the consumer.

Anyone who is willing to add something to the docs to clear up this confusion is welcome to pick up this ticket.

**Comment by oehme** [comment]
> whereas java provides compile configuration.

`compile` is deprecated. Only `implementation` will remain in the `java` plugin. Think of the `java` plugin as some lower-level infrastructure. End users should choose between `java-library` and `application`.

> The primary benefit of using java-library is that Gradle defines an additional “classes-dir” variant. This variant is not published, but when the java-library project is consumed as a project dependency, we don’t need to build the library jar just in order to compile the consumer.

It's not about jar vs classes folder (actually JAR is more efficient on Windows and we should probably use that), but about the fact that we don't need resources for compilation, so we can start the downstream compile task before the upstream processResources is done.

**Comment by oehme** [comment]
Wrong is a strong word, it used to be the way to go and we don't want to scare everyone who uses it right now :) But yes at some point we'll start nagging against usage of `compile` etc. So whenever you create new projects or touch existing ones, think "is this a library or an application?" and make the appropriate change.

**Comment by oehme** [comment]
@jlstrater I think we should reframe this issue. It's about the correct modeling of your project (is it a library or an app? what is its api, if any?). Some additional performance is a nice side effect of that, but I wouldn't dig into that in the user guide. Most of the information can stay in the `java` plugin, because libraries and applications have most things in common. But there should be a pointer for the end user saying that they are really looking for either the `java-library` or `application` plugins.

Also, there is an [outstanding issue](https://github.com/gradle/gradle/issues/7398) with the `java-library` plugin that we should fix before recommending it to everyone.
