### ISSUE TITLE
CONSTANT_TIME_FOR_TAR_ENTRIES = 0 causes issues with Java applications

### ISSUE THREAD

**Issue by blop** [gradle/gradle#7564]
Hello,

I'm using the Gradle TAR task with the "preserveFileTimestamps = false" option (version 4.10.2).
This is part of the creation of Docker images and that flag helps deduplicating similar layers.

As stated in https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarCopyAction.java#L120 the last modified date is set to 0.

Unfortunately, this has some side effects for Java applications, as the popular java.io.File#lastModified method returns a primitive long value and uses 0 when the last modified date cannot be read or if the file is invalid.

I have the same symptoms as presented here https://github.com/spotify/docker-maven-plugin/issues/58#issuecomment-91189781

Could you please change the CONSTANT_TIME_FOR_TAR_ENTRIES for anything but 0, or make it configurable ? Maybe make it the same as the CONSTANT_TIME_FOR_ZIP_ENTRIES to be homogeneous ?
See https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipCopyAction.java#L57

Thanks!
Ping @big-guy ;-)

**Comment by wolfs** [comment]
@blop Thank you for the report.

Do you have a failure when reading directly from the zip file or when using the unpacked files?
Can you disable restoring the file modified time stamps when un-tarring?
What code does fail on your end? I guess that code is not coming from Gradle?

**Comment by wolfs** [comment]
@blop I would expect that when untarring modification timestamps are not restored. So my question is what tool do you use for untaring and can that tool be configured to not restore the timestamps but use the current time instead.

What workaround in the `ZipCopyAction` do you refer to? The strange date we use as modification timestamp [here](https://github.com/gradle/gradle/blob/07ca2ebe27a8f41d5588d6432a793adc1ca1dd0c/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipCopyAction.java#L57)? That is not related  to the modified timestamp no the unpacked files but to how Java stores timestamps in the zip entries.

**Comment by blop** [comment]
I'm not untarring it myself, I pass the tar to the Dockerfile ADD instruction https://docs.docker.com/engine/reference/builder/#add.

The timestamps I get afterwards are the ones set by Gradle here : 
https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/TarCopyAction.java#L109

Then later, when the Java app starts it has issues with the files with lastModifiedDate=0 which is the value chosen by Gradle when "not preserving timestamps".

**Comment by blop** [comment]
It'd be nice to have another default constant (like 1), or provide a way to set my own constant timestamp on every file get goes inside the tar (either through a Tar task option, or through the eachFile(FileCopyDetails) which allows setMode() but nothing related to the file timestamps yet).

I can't use the "current timestamp" at any point or preserveFileTimestamps=true because the whole point is that the resulting tar needs to be the same upon multiple builds if nothing else changes.

**Comment by big-guy** [comment]
@wolfs it seems like there's no harm/difference for us to use `1` or the same timestamp as Zip entries. 

The issue linked to in the OP looks buggy IMHO, but if it saves some frustration, we should just do it.

@blop would you be willing to submit a PR changing this to `1` and fixing any integration tests (something like `gradlew core:check --continue`)?

**Comment by wolfs** [comment]
@big-guy Yeah, that sounds like a good idea. We can't use the same constant as for zip files, since the millis would depend on the time zone. Is there some minimal resolution in milliseconds for tar entries?

**Comment by big-guy** [comment]
Ah, yeah, it's 1-second resolution.  Looks like it needs to be set to `1000` (for 1 second) or otherwise it's rounded down to 0.

**Comment by blop** [comment]
Looks like 1000 is better indeed.

More more information about symptoms and same workaround used here :
https://github.com/GoogleContainerTools/jib/pull/1133 for
https://github.com/GoogleContainerTools/jib/issues/1079

I'll prepare a PR.
