### ISSUE TITLE
Gradle java / kotlin multi-project with java+lombok dependant modules in use

### ISSUE THREAD

**Issue by daggerok** [gradle/gradle#7569]
Hello, seems like my team is missed time when our builds starts failing - after GRADLE_USER_HOME was updated, all our build start failing with same message:

```bash
> Task :modules:xyz-data:common:xyz:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:xyz-data:common:xyz:compileJava'.
> Could not instantiate annotation processor 'lombok.launch.AnnotationProcessorHider$AnnotationProcessor'
```

JDK 8
kotlin 1.2.71
lombok 1.18.2
gradle 4.8.1, 4.9, 4.10.2 - doesn't matter

NOTE: I cannot share build scan because of customer NDA, and if it's needed I can try re-create similar one with dummies modules

PS: If someone has similar worked build configuration (gradle multi-project build with java, kotlin, spring-boot and lombok) can you please share it?

**Comment by oehme** [comment]
Yes, please create a small reproducer project.

**Comment by daggerok** [comment]
okay, I found a problem and it was mainly in gitlab runner user home directory synchronisation by using nfs: each time when parallel job start build same module, currently running same job on another node but with same user already created lock file in ~/.gradle
main misunderstanding was in that `Could not instantiate annotation processor 'lombok.launch.AnnotationProcessorHider$AnnotationProcessor'` message, seems like it wasn't able to do so because of parallel execution lock.

can be fixed with workaround like so:

```bash
GRADLE_USER_HOME=.gradle/$(date +%y-%m-%d-%H-%M) clean build
``` 

closing with issue
