### ISSUE TITLE
Up-to-date checks for ArtifactTransforms

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#7570]
Motivation: https://issuetracker.google.com/117893217
Version: 5.1-20181029034539+0000

Artifact transforms might be interrupted while processing inputs, leaving the output in inconsistent state. Subsequent runs will be not re-run the transform, and it is very hard for the users to figure out what is going on.

In https://issuetracker.google.com/117893217, ExtractAarTransform was force-stopped on the CI, which resulted in missing classes.jar in the artifact transform output.

It would be great to have task-like up-to-date checks with artifact transforms.

**Comment by wolfs** [comment]
Thank you for the report @gavra0. I am currently in the process of implementing up-to-date checks for artifact transformations.

With the current code, we consider an artifact transformation to be up-to-date if the result files (`List<File>` returned by the transform method) of the last execution exists. We seem to store the list of output files only after the whole output has been generated. So I don't see how force-killing the build could leave behind an inconsistent state. The bug report shows that it is possible somehow.

With actual up-to-date checks, we would store not only the `List<File>` which was generated by the artifact transformation, but a snapshot of the whole output directory. So the artifact transformation would need to re-run whenever the state there changes - exactly as up-to-date checks work now for tasks.

Would that solve the problem you reported?

**Comment by gavra0** [comment]
Yes, that approach looks good. Thank you for working on this!

**Comment by wolfs** [comment]
Fixed via #7572.
