### ISSUE TITLE
5.0 rc1 regression against milestone1 for missing plugin pom

### ISSUE THREAD

**Issue by yschimke** [gradle/gradle#7584]
The POM is missing https://jcenter.bintray.com/net/swiftzer/semver/semver/1.1.0/

```
$ ./gradlew test

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'rsocket-cli'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find net.swiftzer.semver:semver:1.1.0.
     Searched in the following locations:
       - file:/Users/yuri/.gradle/caches/5.0-rc-1/embedded-kotlin-repo-1.3.0-2/repo/net/swiftzer/semver/semver/1.1.0/semver-1.1.0.jar
       - https://plugins.gradle.org/m2/net/swiftzer/semver/semver/1.1.0/semver-1.1.0.pom
     Required by:
         project : > org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:6.2.1 > gradle.plugin.org.jlleitschuh.gradle:ktlint-gradle:6.2.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
```

**Comment by oehme** [comment]
This is intentional. Plugins without a POM are invalid. How was this plugin even published, did someone manually upload a jar?

**Comment by oehme** [comment]
@eskatos is this mentioned in the release notes? Maybe we should provide an explanation of the workaround?

Don't we use ktlint too? Why didn't we see this problem?

**Comment by JLLeitschuh** [comment]
Yea, I didn't realize the implications of this decision. We need to come up with a solution.

See https://github.com/JLLeitschuh/ktlint-gradle/issues/162

I'm guessing Gradle has maven central declared as a repository in the `buildscript` block or gradle is using a mirror that is backed both by maven central and the plugin portal.

**Comment by oehme** [comment]
The portal forwards requests for unknown things to JCenter, which mirrors mavenCentral. But that doesn't answer the question why the SemVer library has no POM.

**Comment by eskatos** [comment]
@oehme added to the upgrading doc in https://github.com/gradle/gradle/pull/7738

The version of `ktlint-gradle` we use (5.x) doesn't depend on the offending version of `semver`, that's why we didn't experience that issue.

**Comment by oehme** [comment]
Got it, thanks!
