### ISSUE TITLE
Annotation Processor API: Filer finds non-existing resources

### ISSUE THREAD

**Issue by jnehlmeier** [gradle/gradle#7588]
### Expected Behavior
Annotation processor API allows to load resources from any `StandardLocation`. Given there is no `StandardLocation` for resources one have to search for resources in multiple `StandardLocation` in order to be compatible to all kinds of project configurations and build tools.

To figure out what strategy is best when using Gradle I created a simple project with an annotation processor that scans all `StandardLocation` for a specific resource and prints out the result. Using that annotation processor I could play around with  different `build.gradle` configurations and check what the annotation processor can see. 
Turns out that using `compileJava.options.sourcepath = files('src/main/resources')` is probably the best way in Gradle to make resources accessible to annotation processors (**something that you might want to add to your documentation**)

Using the above I would expect my annotation processor to find the resource file **in exactly one** location: `StandardLocation.SOURCE_PATH`

### Current Behavior
The annotation processor discovered the resource file in **three** `StandardLocation`:

1. ✅ `SOURCE_PATH`: `file:///<project-dir>/src/main/resources/test.xml`
2. 🛑 `SOURCE_OUTPUT`: `file:///<project-dir>/build/classes/java/main/test.xml`
3. 🛑 `CLASS_OUTPUT`: `file:///<project-dir>/build/classes/java/main/test.xml`

In all three cases the annotation processor API returns a non-null `FileObject` when calling [processingEnv.getFilter().getResource(...)](https://docs.oracle.com/javase/10/docs/api/javax/annotation/processing/Filer.html#getResource(javax.tools.JavaFileManager.Location,java.lang.CharSequence,java.lang.CharSequence)), however you can only successfully read it in the first case because for the other cases the file it points to is non-existent. **This seems to a be a bug** because the `Filer` should not return such an object but instead throw an `IOException`.

### Context
I want to write an annotation processor that processes resource files and generates source based on these resource files (e.g. source file from a xml template)

### Steps to Reproduce (for bugs)
- Download [gradle-apt-resources-issue.zip](https://github.com/gradle/gradle/files/2457713/gradle-apt-resources-issue.zip)
- run `./gradlew clean build`

### Your Environment
Mac OS 10.13.6, Oracle Java 10.0.2, Grade 4.10.2

**Comment by oehme** [comment]
Have you tried this with plain javac? We call the Java compiler API and use the standard java file manager implementation.

**Comment by jnehlmeier** [comment]
Hmm, seems like a real Java issue. Tried javac with version 1.8, 9, 10 (Oracle JDK) and 11 (OpenJDK) and in all cases the annotation processor claims to find the file in `SOURCE_OUTPUT´ and `CLASS_OUTPUT` even though it does not exist in these locations.

**Comment by oehme** [comment]
Closing as a JDK issue then. You might want to open a bug on the JDK issue tracker. Thanks for checking!
