### ISSUE TITLE
Buildscript had three repositories,first repo doesn't contain the plugin,but second repo does. Except could download it from second repo,but failure.

### ISSUE THREAD

**Issue by pokercc** [gradle/gradle#7593]
### Expected Behavior

Buildscript had three repositories,first repo doesn't contain the plugin,but second repo does. Except could download it from second repo.
### Current Behavior

Buildscript had three repositories,first repo doesn't contain the plugin,but second repo does. Except could download it from second repo,but failure.
There is build.gradle config:
```groovy
buildscript {
    ext.kotlin_version = '1.3.0'
    repositories {
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        google()
        jcenter()
    }
}
```
There is error:
```
Parallel execution is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'AndroidPInstallApkDemo'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).
     Searched in the following locations:
         https://maven.aliyun.com/repository/gradle-plugin/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 17s
Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).
Searched in the following locations:
    https://maven.aliyun.com/repository/gradle-plugin/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar

```

### Context

In china, download gradle plugin is very slow. So I add aliyun mirror to spped up download that.
### Steps to Reproduce (for bugs)

At first use android studio 3.2.1 ,new android project within kotlin support.
Then add `  maven { url "https://maven.aliyun.com/repository/gradle-plugin" }` to your build.gradle buildScript.repositories first line.
Next ,exec command "./gradlew build",the error will occur;
### Your Environment

 * Build scan URL: 
android studio 3.2.1
gradle wrapper 4.6

**Comment by oehme** [comment]
Please provide a reproducible example project. The error above looks like you only defined one repository.

**Comment by pokercc** [comment]
Thanks for your answer. 
I defined three repositories in buildScript.repositories.
```
 repositories {
        //aliyun repo
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        //google repo
        google()
        //jcenter repo
        jcenter()
    }
```
Here is a reproducible example project. https://github.com/pokercc/GradleIssues7593Reproduct

**Comment by oehme** [comment]
The `aliyun` is broken - It contains the POM, but not the JAR for AAPT. You may want to get in touch with them, they may need to resynchronise with Google.

**Comment by pokercc** [comment]
Thanks a lot ,I will feedback to aliyun repo.

**Comment by bigdaz** [comment]
FYI this was an issue with `jcenter` containing a broken version of `com.android.tools.build:aapt2-proto:0.3.1`. This was published wrongly without knowledge of the Android team, and has now been removed.

You can find a number of reported issues related to this:
- https://github.com/flutter/flutter/issues/23404
- https://stackoverflow.com/questions/52944351/android-ci-build-could-not-find-aapt2-proto-jar
- https://issuetracker.unity3d.com/issues/gradle-build-fails-when-downloading-files-from-jcenter

My guess is that the `aliyun` mirror managed to get the same broken module. It will need to be removed if it hasn't yet been.
