### ISSUE TITLE
Empty version lists from a repository are cached forever

### ISSUE THREAD

**Issue by sonicsnes** [gradle/gradle#7601]
### Expected Behavior

If your project uses two dependency repositories, and depends on a dependency using a version range, if newer versions are published to the second repository, they should be resolved automatically (after an appropriate amount of time to expire the version list cache).

### Current Behavior

If the dependency previously did not exist in the second dependency repository, it will never be picked up by gradle, even if it is the highest version in the version range.

### Context

We are migrating modules from one internal repository (ivy) to another (maven). Gradle builds with warm caches never pick up these newer migrated modules, since they have cached an empty version list on the maven repo.

The current work-around is to `--refresh-dependencies` every time a build seems to not be picking up module versions that are newly migrated to maven, but this is a pain to enforce across the entire org.

### Steps to Reproduce (for bugs)

* Say your project uses two dependency repositories, maven-central and jcenter.
* Dependency `a:b:1.0` has been published to maven central.
* Your project contains a dependency on `a:b:[1,2)`. It properly resolves 1.0 from maven central, and caches that the version list on jcenter is empty.
* Dependency `a:b:1.1` gets published to jcenter.
* Your project will never resolve 1.1, as the empty jcenter version list is cached forever.

This appears to be a bug or oversight in `DefaultCachePolicy.mustRefreshVersionList`. If no dependencies are found in a repository, the cache policies will be checked against an empty `Set<ModuleVersionIdentifier>`. `cacheDynamicVersionsFor` only applies to resolution results which are not empty, and there is no other mechanism to prevent these resolutions from caching forever.

Either `cacheDynamicVersionsFor` should also apply to empty results, or there should be an additional separate cache function to adjust cache time for empty version list results from a repo.

### Your Environment

Gradle 4.10.2

**Comment by ljacomet** [comment]
Thanks for the report and I understand the frustration while doing that migration.

However what you asking is the opposite of what other users want with such empty version caching. If they have more than one repository, they do not want Gradle to go look over all repositories every time the cache of dynamic dependency version expires.

As such any solution that would result in a performance impact on this scenario is not an option.

Linked to the fact that there is a workaround and the other priorities in Gradle at the moment, I do not see any work on this being prioritized in the medium term.

**Comment by ljacomet** [comment]
Closing as there is still no work planned on this.

**Comment by tyates-indeed** [comment]
Why not provide a flag to allow users adjust this behavior as they see fit? We're fine with taking the performance hit but I recognize not everyone else is. Would y'all be open to us sending you a merge request to add this flag @ljacomet ?
