### ISSUE TITLE
JUnit 5 Disabled annotation doesn't work on a method

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#7604]
### Expected Behavior
[@Disabled](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Disabled.html) annotation on a method should exclude the method from execution.

### Current Behavior
The method is executed even though annotated with `@Disabled`. If the class is annotated instead, then the tests in the class are not executed as expected.

### Context
Ignoring a test.

### Steps to Reproduce (for bugs)
The project is [here](https://github.com/asarkar/java/tree/master/jpms-learning), the test class in question is [here](https://github.com/asarkar/java/blob/master/jpms-learning/com.greetings/src/test/java/com/greetings/ModularityTest.java). 

### Your Environment
* openjdk version "11.0.1"
* Gradle wrapper 4.10.2

**Comment by marcphilipp** [comment]
When I move `@Disabled` to the method and run the test, I get the following exception:

```
java.lang.reflect.InaccessibleObjectException: Unable to make public com.greetings.ModularityTest() accessible: module com.greetings does not "exports com.greetings" to module org.junit.platform.commons
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:189)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:182)
	at org.junit.platform.commons@1.3.1/org.junit.platform.commons.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:1340)
	at org.junit.platform.commons@1.3.1/org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:431)
```

So, JUnit is trying to instantiate your test class but can't access the constructor of the test class.

Please refer to https://sormuras.github.io/blog/2018-09-11-testing-in-the-modular-world.html for options on testing using the module path.

**Comment by asarkar** [comment]
@marcphilipp I didn’t see that exception and the test was executed. Of course, if the class couldn’t be instantiated, there’d be no way to execute the test, right?
Also, how do you explain the annotation working on the class?

Are you running JDK 11 and using the Gradle wrapper that comes with the project?

**Comment by marcphilipp** [comment]
Did the test pass for you?

> Are you running JDK 11 and using the Gradle wrapper that comes with the project?

Yes.

**Comment by asarkar** [comment]
@marcphilipp
I made an interesting observation. Your initial assessment was right for commit [51d2b76b](https://github.com/asarkar/java/tree/51d2b76bf798612d6a2acd358a535928dfbc8bcd/jpms-learning); it was my bad to have removed the `--add-exports` JVM argument from the `build.gradle`. Afterting [adding it back](https://github.com/asarkar/java/blob/master/jpms-learning/build.gradle#L50), the test indeed gets ignored if `@Disabled` is applied at the method level, **as long as** the test class is `public`. If the visibility is changed to package-default, the annotation no longer works and the test is executed.
AFAIK, test classes don't need to be `public` with JUnit5, right? If that's the case, then this ticket stands as a bug.

**Comment by marcphilipp** [comment]
No, test classes don't have to be public in JUnit 5, it will try to make them accessible. Could you please share a build scan so I can see what you're seeing?

**Comment by marcphilipp** [comment]
If yo [look at the build scan](https://scans.gradle.com/s/5mexfnqc2hxwu/console-log#L18-L19), you see that it fails with an `InaccessibleObjectException`. If the `@Disabled` annotation is present on the test class, JUnit does not attempt to instantiate it. If it's on the test method, it tries to instantiate the test class and pass it to registered `ConditionalExecution` extensions. Since that fails, it reports the test method as failed. The root cause is still the missing `--add-opens` so this is neither a bug in Gradle nor in JUnit.

**Comment by asarkar** [comment]
@marcphilipp makes sense, thank you for looking into it. Can the error message be improved to report the actual problem instead of showing a test failure, which is obviously misleading. The test wasn't executed, so it couldn't have failed.

**Comment by marcphilipp** [comment]
It does report the actual problem, i.e. exception. Test execution does not only consist of executing the test method but includes the preparations for doing so, e.g. creating the test instance. There's no other way for JUnit to report such failures except for failing the corresponding element in the test tree. In any case, since this is not a Gradle but a JUnit issue, please open an issue for the JUnit project if you have an idea how to improve the messaging.

**Comment by djangofan** [comment]
Just FYI.  If you annotate a JUnit5 test as **@Disabled(value="Here is the reason.")** ,  then the explanatory message does not display on the Gradle HTML report.

**Comment by marcphilipp** [comment]
@djangofan That's #5511.
