### ISSUE TITLE
[Oct 31] Publish v3.2 RC2

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#761]
Expected fixes: https://github.com/gradle/gradle/issues/748 and https://github.com/gradle/gradle/pull/710
- [x] Update release notes
- [x] Get verification from submitters

**Comment by eriwen** [comment]
@bmuschko any reason we wouldn't close this now?

**Comment by bmuschko** [comment]
@eriwen Had left it "under review" as I was still waiting to get feedback from reporters. I think we can close now.
