### ISSUE TITLE
Deprecate BuildListener.buildStarted

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#7613]
### Expected Behavior
`org.gradle.BuildListener.buildStarted(Gradle gradle)` should be triggered when a listener is implemented and also this should happen before other listeners such as `ProjectEvaluationListener`

### Current Behavior
`buildStarted` is not triggered at all.
 
### Context
This is started to happen in ` 5.0-20181024213332+0000`

It affects because we depend on `buildStarted` to initialize some custom build metrics that we have in https://github.com/nebula-plugins/gradle-metrics-plugin. We applied a workaround but we don't feel confident that it will be enough and also wondering if other methods are triggered in the proper order.

### Steps to Reproduce (for bugs)
https://github.com/nebula-plugins/gradle-nebula-integration/tree/master/build-started-listener-issue

Given this listener https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/build-started-listener-issue/src/main/groovy/nebula/plugin/test/MyBuildListener.groovy and adding it to the project via https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/build-started-listener-issue/src/main/groovy/nebula/plugin/test/MyPlugin.groovy

I should expect this test to pass: https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/build-started-listener-issue/src/test/groovy/nebula/plugin/test/MyPluginSpec.groovy#L8

However, `buildStarted` is never triggered and the build will fail.

As a note, `project.gradle.addListener(myListener)` or `project.gradle.addBuildListener(myListener)` have the same behavior

**Comment by adammurdoch** [comment]
The `buildStarted` method is left over from a very old API from the Gradle 0.x days that was used to embed Gradle and that is no longer used.

It doesn't make sense to call this method from a listener registered within a build, as the build has already started. We should remove this method instead. If there's some code that feels like it should belong in a `buildStarted` method, it would be better to put this code somewhere else and call it just before you register the listener.

**Comment by rpalcolea** [comment]
Thanks for the clarification @adammurdoch. It would be nice if this could be marked as deprecated and put a not that is not even triggered anymore.. it seems like a breaking change without nottice

**Comment by asarkar** [comment]
Since Gradle now requires Java 8 minimum, it'd have been better to make the methods in `BuildListener` `default`, because an implementation is forced to override them anyway, and the error message shows up in the build logs continuously.

I think the error message should suggest that [BuildAdapter](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/BuildAdapter.java) is used instead.
