### ISSUE TITLE
[Epic] Support distributed build clusters

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#7614]
Gradle is extremely well suited for this sort of feature—I'm really surprised it's not being actively worked on.

### Machinery

- A Gradle account would be used to register available machines
- Machines are allowed to sleep, but are kept alive should jobs need to be run
- Gradle detects mouse and keyboard input at the OS level to switch into low priority mode when the machine is being used
- Tasks (and potentially WorkerExecutors) are sharded
- Inputs are sent to remote machines and outputs are retrieved to be used on the machine requesting a build
- Outputs are first sent to the machine requesting the build, then to the remote cache to minimize latency for the requested build
- The Gradle account computes a latency graph on a recurring basis to determine the smallest latency machines available from any potential machine requesting a build
- When a Gradle daemon is busy on the local machine, the entire build is sent to a remote machine instead of creating a new daemon (unless all machines are saturated in which cases multiple daemons may be started)
- Tasks are intelligently distributed to generate the longest consecutive sequence possible, thus minimizing data transfer

### Customer value

- Build speed
- Minimizing costs since dedicated build machines aren't necessarily required anymore

### Gradle value

The most enticing Gradle Enterprise offering to date

PS: how is this not a thing? I'm sure hoards of developers would love to work on such an exciting project (myself included).

**Comment by lptr** [comment]
:) Without promising anything let me assure you that this is being worked on.

**Comment by big-guy** [comment]
This is a good idea, but we don't have anything to announce at this time.

**Comment by lagergren** [comment]
Can you tell us what's going on in this space? I had a use case that would seriously benefit from this today, and I remember that I had read something a couple of years ago that it was work in progress. 

Is there an issue number or can I get status updates anywhere?

Regards,
M

**Comment by uyilmaz** [comment]
Just a "remote" daemon running on the local machine that can be connected over tcp would be super nice. For CI jobs running in containers. They could share the daemon instead of starting it and killing it everytime.
