### ISSUE TITLE
 What went wrong: Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'. > More than one file was found with OS independent path 'androidsupportmultidexversion.txt'

### ISSUE THREAD

**Issue by kyodgorbek** [gradle/gradle#7618]
I am getting this issue on from gradle android studio below my app:gradle from android studio

apply plugin: 'com.android.application'
apply plugin: 'realm-android'
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "activity.drawer.navigation.com.kitabsawtitest"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        preDexLibraries true
    }
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.aurelhubert:ahbottomnavigation:2.1.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.mikhaellopez:circularimageview:3.2.0'
    implementation 'com.ncornette.cache:okcache-control:1.1.1'
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    implementation 'android.arch.lifecycle:runtime:1.1.1'
    implementation 'com.android.support:multidex:1.0.3'
    implementation "android.arch.core:common:1.1.1"
}

**Comment by marcphilipp** [comment]
That's definitely not an issue in Gradle core but probably related to the Android plugin. You're more likely to get a helpful answer on StackOverflow or the Gradle forums.
