### ISSUE TITLE
Support JUnit platform configuration parameters

### ISSUE THREAD

**Issue by jlink** [gradle/gradle#7622]
It should be possible to set junit 5 platform configuration parameters in test task.

### Expected Behavior

```
test {
    useJUnitPlatform {
        includeEngines "junit-jupiter", "jqwik"
        configurationParameters["junit.jupiter.testinstance.lifecycle.default"] = "PER_CLASS"
        configurationParameters["junit.jupiter.execution.parallel.enabled"] = true
        configurationParameters["jqwik.tries.default"] = 100        
    }
}
```

Those parameters should then be available for a test engine through
`ExecutionRequest.getConfigurationParameters()`.

### Current Behavior

Not supported. Some configuration parameters might also be accessible through system properties.

### Context
This would allow to configure e.g. paralle execution, default lifecyle or options from
other test enginges through gradle.

**Comment by marcphilipp** [comment]
Thanks for the feature requests. While this feature isn't available, yet, you can use `junit-platform.properties` or use system properties which the JUnit platform automatically converts into configuration parameters:

```gradle
test {
    useJUnitPlatform {
        includeEngines "junit-jupiter", "jqwik"
    }
    systemProperties = [
        "junit.jupiter.testinstance.lifecycle.default": "PER_CLASS",
        "junit.jupiter.execution.parallel.enabled": true,
        "jqwik.tries.default": 100
    ]
}
```

**Comment by jlink** [comment]
cool. I'll try it, thanks

**Comment by jlink** [comment]
I tried

```
	systemProperties = [
		"jqwik.tries.default": 100
	]
```

together with

```
@Override
public void execute(ExecutionRequest request) {
	System.out.println(request.getConfigurationParameters());
          ...
}
```

`gradle clean test --info` had the following result:

```
Gradle Test Executor 8 STANDARD_OUT
    CONFIG: LauncherConfigurationParameters []
```

Gradle version: 10.2
Platfrom version: 1.3.1

Am I doing something wrong?

**Comment by jlink** [comment]
Unexpected, but yes, now it works :-) Cheers.

BTW, can system properties also be set through command line options of `gradle` command?

**Comment by jlink** [comment]
Well, I think it’s a pity that a crucial part of system builds, testing, gets only half-hearted support from Gradle - this is not the only unsupported JUnit platform feature.
