### ISSUE TITLE
Buildscript classpath resolution doesn't take dependencies already present in the parent classpath into account

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#7628]
### Expected Behavior
Versions of dependencies in parent scopes (parent projects or `buildSrc`) should be honored when resolving the classpath of buildscripts.

For a concrete example, if `buildSrc/build.gradle.kts` declares a dependency on version `3.2.0` of the Android build tools:

```
dependencies {
    implementation("com.android.tools.build:gradle:3.2.0")
}
```  

And a subproject uses a plugin that depends on version, say, `2.3.3` of the Android build tools. The version resolved and used for the buildscript should be `3.2.0` and not `2.3.3`.

### Current Behavior

The buildscript classpath resolution doesn't take dependencies already in the classpath into account.

### Notes

#1370 provides a solution.

**Comment by oehme** [comment]
This is intended behavior. There is no point in honoring the versions in the subproject, because the classes will be loaded from the parent's classloader anyway.

The correct solution is not to use `buildscript {}` in subprojects. See also #7456
