### ISSUE TITLE
Idea configuration generated for Java 10 is invalid

### ISSUE THREAD

**Issue by dcabasson** [gradle/gradle#7631]
When generating the idea configuration with cleanIdea idea for a Java 10 project, using the current version of Intellij (2018.2.5) the generated configuration is invalid and Intellij tries to build using language level 11 which doesn't work that well against JDK 10.

See attached project.

Step to reproduce :
* gradlew cleanIdea idea
* open the resulting project in Intellij
* Choose Build > Build Project
* Build fails with the error :
![image](https://user-images.githubusercontent.com/1946465/48011768-8ac7fa80-e0ee-11e8-9b9c-95042543771d.png)

**Comment by dcabasson** [comment]
[gradle-7631.zip](https://github.com/gradle/gradle/files/2549639/gradle-7631.zip)

**Comment by dcabasson** [comment]
Thanks for looking into that @oehme - can you share the generated ipr file, before you open Intellij? Which version of Intellij are you using? Are you set up to use Java 10? Did you check the language level in Intellij?

**Comment by oehme** [comment]
The ipr file had bytecode level `1.10` in it. I'm using the latest IntelliJ EAP. Yes I am sure I'm set up for Java 10.

**Comment by dcabasson** [comment]
So, 1.10 is invalid according to Intellij :
https://github.com/JetBrains/intellij-community/blob/master/jps/model-api/src/org/jetbrains/jps/model/java/LanguageLevel.java

It should be JDK_10

I am using community version 2018.2.5 - is that the one you also have?

**Comment by oehme** [comment]
I'm using the latest [EAP](https://www.jetbrains.com/idea/nextversion/) as mentioned above. It works just fine and detects JDK 10 as expected.

**Comment by dcabasson** [comment]
@oehme - are you opening the file by opening the generated ipr file?

**Comment by oehme** [comment]
Yes.

**Comment by big-guy** [comment]
@dcabasson I'm closing this for now, but please leave a comment if you're still seeing this with the latest IntelliJ/Gradle. Thanks!
