### ISSUE TITLE
Java Scanner Yields NoSuchElementException

### ISSUE THREAD

**Issue by slothsalad** [gradle/gradle#7638]
I am working on a project to calculate fractions, however this program is just meant to read user input and return part of it but instead results in the following: 
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at fracCalc.fracCalcCheckUno.produceAnswer(fracCalcCheckUno.java:21)
	at fracCalc.fracCalcCheckUno.main(fracCalcCheckUno.java:14)

### Expected Behavior
The code should read the user input and then return the second part of it, which I have called "operand2"

### Current Behavior
Code results in the error: Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at fracCalc.fracCalcCheckUno.produceAnswer(fracCalcCheckUno.java:21)
	at fracCalc.fracCalcCheckUno.main(fracCalcCheckUno.java:14)

### Context
With this error I am unable to receive any user input.

### Steps to Reproduce (for bugs)

package fracCalc;
import java.util.Scanner;
public class fracCalcCheckUno{
    public static void main(String[] args) {
    Scanner a = new Scanner(System.in);
         System.out.print("Input fraction expression: ");
         String phrase = a.next();
         String b = produceAnswer(phrase);
         System.out.println(b);

    }    
    public static String produceAnswer(String phrase) {
        Scanner console = new Scanner(phrase);
          String operand1 = console.next();
          String operator = console.next();
          String operand2 = console.next();
         String answer = produceAnswer(phrase);
         System.out.println(answer);

        return operand2;
    }
}

### Your Environment
Build scan URL

**Comment by big-guy** [comment]
Hi @slothsalad,

It seems like you might be asking about a problem with Java in general.  This issue tracker is for problems with Gradle specifically.

You can try getting help on our [forums](https://discuss.gradle.org/), but your question might be better answered on [Stackoverflow](https://stackoverflow.com/).

HTH
