### ISSUE TITLE
Build fails with ClassCastException org.gradle.api.DefaultTask_Decorated to org.gradle.api.tasks.compile.JavaCompile

### ISSUE THREAD

**Issue by industrious** [gradle/gradle#7639]
### Expected Behavior
The build should be successful and the result should be a list of available tasks.

### Current Behavior
```
$ ./gradlew tasks --scan
...

* What went wrong:
Execution failed for task ':tasks'.
> Cannot cast org.gradle.api.DefaultTask_Decorated to org.gradle.api.tasks.compile.JavaCompile
```

### Context
This build is working for Java 8 + Gradle 3.3. Now we need to upgrade to Java 11 and Gradle 4.10.2 but the build fails with this error. I narrowed it down in the debug mode to the following build script.

### Steps to Reproduce (for bugs)
```
apply plugin: 'java'

buildScan { termsOfServiceUrl = 'https://gradle.com/terms-of-service'; termsOfServiceAgree = 'yes' }

sourceSets {
    rmi
}


task compileRmiJava(overwrite: true) {
    dependsOn compileJava
}
```

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/tiwk5xjojfqhm/

[gradle-test.zip](https://github.com/gradle/gradle/files/2552610/gradle-test.zip)

**Comment by industrious** [comment]
I'd be really grateful if someone could provide a workaround. Perhaps, it's possible to rewrite the build script to avoid this exception.

**Comment by oehme** [comment]
```task compileRmiJava(overwrite: true)```

You are overwriting the compile task with a different one. Why are you doing this?

**Comment by industrious** [comment]
I did not write it in the beginning, I guess it generates RMI stubs from classes in the main sourceSet. Here is a snippet from the original build.gradle:
```
task compileRmiJava(overwrite: true) {
    dependsOn compileJava
    def classes = [
        ...
    ]   
    outputs.dir sourceSets.rmi.output.classesDir
    doLast {
        file(sourceSets.rmi.output.classesDir).mkdirs()
        exec {
            executable org.gradle.internal.jvm.Jvm.current().getExecutable('rmic')
            args '-d', sourceSets.rmi.output.classesDir
            args '-classpath', sourceSets.main.output.classesDir
            classes.each { args it } 
        }
    }
}
```
I have now come up with a workaround consisting of a separate processRmiJava task that just is included in the jar explicitly but what would be a proper way of achieving this?

**Comment by oehme** [comment]
Since you're generating classes directly, your solution sounds reasonable. I.e. there is no need for a "compile" task.
