### ISSUE TITLE
Cannot start Java 9+ daemon if client has java.endorsed.dirs

### ISSUE THREAD

**Issue by vladsoroka** [gradle/gradle#7642]
All  JVM system properties of a tooling client are passed to the daemon process for a `BuildAction` execution, see [DaemonParameters.java#L153](https://github.com/gradle/gradle/blob/v4.10.2/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/configuration/DaemonParameters.java#L153), [DaemonBuildActionExecuter.java#L57](https://github.com/gradle/gradle/blob/v4.10.2/subprojects/launcher/src/main/java/org/gradle/tooling/internal/provider/DaemonBuildActionExecuter.java#L57)

This can cause issues if the daemon JVM will receive incompatible system property (e.g. when daemon JVM version is not the same as tooling client JVM version).

The original user issue description can be found at https://youtrack.jetbrains.com/issue/IDEA-193219

**Comment by oehme** [comment]
The Tooling API doesn't pass any system properties by default. I.e. the code you linked contains a null value by default. Please make sure you aren't passing them yourself.

The use case in the linked issue is a bad idea in general (passing all system properties to another tool). The user should pick the properties they actually need.

**Comment by oehme** [comment]
I guess there is the potential issue of not even being able to start the daemon if IDEA was started on Java 8 with some endorsed libs. We could remove that one explicitly.
