### ISSUE TITLE
Gradle 5.0 RC1 doesn't build my composite build anymore.

### ISSUE THREAD

**Issue by ams-tschoening** [gradle/gradle#7650]
Two projects `A` and `B`, `A` is providing plugins to `B` and `B` includes `A` using `includeBuild` in `settings.gradle`. `B` is a `java-library` and with Gradle 4.10 builds properly, but after upgrading to Gradle 5.0 RC1 it doesn't anymore. It seems to stop after executing the task `processResources`, but without any error. The only thing of interest logged is the following warning:

> Ignoring listeners of task graph ready event, as this build (:A) has already executed work.

### Expected Behavior

Project `B` should continue to build properly, resulting in the creation of a JAR file.

### Current Behavior

No JAR file is created, the build stops after  `build\resources\main\META-INF\gradle-plugins\[...]` has been created.

### Context

Project `A` is providing helper plugins to multiple other projects, project `B` is consuming those plugins and at the same time provides one on its own to one specific other project `C`. In the end, project `A` and `B` are simply a variant of `buildSrc` for individual projects, only externalized into their own repos/projects and therefore included by their consumers.

Gradle 5.0 RC1 needs to be used because [it fixes another issue](https://discuss.gradle.org/t/illegalstateexception-without-any-further-details-in-included-build/29331) for me.

During debugging I was able to work around that problem not only by switching versions of Gradle, but as well by reducing my `build.gradle` of project `B` to either not apply my plugin from project `A` anymore or keep applying that plugin and instead not using the plugins of `A` which project `B` provides to project `C`. The main difference in both cases is the classpath for `buildscript` vs. `implementation`. that might or might not have to do with it... What I couldn't find was what actually triggers the execution the warning mentions, I don't have the feeling that that depends on my own code. And it works with 4.10 unchanged as well, so shouldn't be that wrong.

### Steps to Reproduce (for bugs)

cd de.am_soft.docbeam.raw.server.build
gradlew wrapper --gradle-version=4.10
gradlew clean build
gradlew wrapper --gradle-version=5.0-rc-1
gradlew clean build

### Your Environment

 * Build scan URL: 
* Windows 10 1803 x86-64
* java version "1.8.0_181"

[gradle_4_10.txt](https://github.com/gradle/gradle/files/2554349/gradle_4_10.txt)
[gradle_5_0_rc1.txt](https://github.com/gradle/gradle/files/2554352/gradle_5_0_rc1.txt)
[GitHub.zip](https://github.com/gradle/gradle/files/2554362/GitHub.zip)

**Comment by eskatos** [comment]
I can reproduce

![image](https://user-images.githubusercontent.com/132773/48124532-d90b0400-e27c-11e8-8f13-b20a13a103a3.png)

**Comment by adammurdoch** [comment]
A work around, until there's a fix, is to use the `java` plugin instead of the `java-library` plugin in the plugin build.
