### ISSUE TITLE
Eclipse resourceFilters cannot be modified in beforeMerged and whenMerged 

### ISSUE THREAD

**Issue by cfraenkel** [gradle/gradle#7657]
The resourceFilter list in the beforeMerged and whenMerged hooks of `eclipse.project.file` does not reflect the loaded .project data and changes to that list are not persisted to `.project`.

This issue could be related to the problem mentioned in https://github.com/gradle/gradle/issues/1974#issuecomment-300115022. Since that Issue deals with a different matter I've opened this new issue.

### Expected Behavior
* When I list the current resourceFilters in beforeMerged I expect to see the resourceFilters loaded from the file.
* When I modify the resourceFilters set in beforeMerged / whenMerged I expect my changes to be persisted to the `.project` file and / or used by buildship

### Current Behavior
The  Project passed to the `beforeMerged` and `whenMerged` Actions (and closures) always contains an empty `resourceFilter` list (unless modified in beforeMerged).
Changes to the List in beforeMerged / whenMerged are not persisted to disk.

### Context
I want to add resource filters that exclude subprojects from searches and launcher discovery.

### Cause
I've looked at the source and the cause is most likely `org.gradle.plugins.ide.eclipse.model.NonRenamableProject `. This class is used by the calls to whenMerged and beforeMerged in `org.gradle.plugins.ide.eclipse.model.EclipseProject.mergeXmlProject(...)` and is missing overrides that delegate the call to `getResourceFilters()` and `setResourceFilters(...)` to the underlying project object.

### Steps to Reproduce (for bugs)
`.project` file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>groovy</name>
	<comment></comment>
	<projects/>
	<natures/>
	<buildSpec/>
	<linkedResources/>
	<filteredResources>
		<filter>
			<id>1</id>
			<type>30</type>
			<name/>
			<matcher>
				<id>org.eclipse.ui.ide.multiFilter</id>
				<arguments>1.0-name-matches-false-false-input</arguments>
			</matcher>
		</filter>
	</filteredResources>
</projectDescription>
```

build.gradle:
```groovy
import org.gradle.plugins.ide.eclipse.model.ResourceFilterAppliesTo
import org.gradle.plugins.ide.eclipse.model.ResourceFilterType
import org.gradle.plugins.ide.eclipse.model.internal.DefaultResourceFilter
import org.gradle.plugins.ide.eclipse.model.internal.DefaultResourceFilterMatcher

plugins {
   id 'eclipse'
}
eclipse {
   project {
      file {
         beforeMerged { prj ->
            // this should print existing entries in the .project file, but prints the empty list
            println prj.resourceFilters
         }
         whenMerged { prj ->
            // this should add a new resourceFilter, but does not.
            prj.resourceFilters += new DefaultResourceFilter(ResourceFilterAppliesTo.FILES_AND_FOLDERS, ResourceFilterType.EXCLUDE_ALL, true,
                    new DefaultResourceFilterMatcher("org.eclipse.ui.ide.multiFilter", "1.0-name-matches-false-false-testDir", [] as Set))
         }
      }
   }
}
```

run the eclipseProject task or import into eclipse using buildship

### Your Environment

I'm encountering this Issue using gradle 4.10.2

**Comment by Vampire** [comment]
May I ask in what regard you think this is different from what I wrote in https://github.com/gradle/gradle/issues/1974#issuecomment-300115022?
Or did you just think you make a separate issue for it with better description, as my issue is mainly about the name for the resource filters?

**Comment by cfraenkel** [comment]
I think this issue deals with the problem you described in your comment. Its as you said, I wanted to track this as a separate issue as I felt it might get lost as a comment in a ticket dealing with a different issue. I also did some digging looking for a cause for this issue and I thought that it would be wrong to post all of this in a ticked dealing with the name of the resource filters.

**Comment by agavrilov** [comment]
I encountered the same issue on Gradle 5.6.2. Is there any ETA for fixing it?

**Comment by cfraenkel** [comment]
This issue still exists and requires workarounds and hacks.
