### ISSUE TITLE
allow --version to be non terminal

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#7659]
```yaml
      - gradle --version
      - gradle -Dorg.gradle.daemon=false --stacktrace --info build
```
instead of running these 2 command in ci I'd rather
```yaml
      - gradle --version -Dorg.gradle.daemon=false --stacktrace --info build
```

and have it printed at the top

**Comment by oehme** [comment]
This doesn't sound worth the change, especially since --version is designed to complete quickly without configuring a build etc.

**Comment by big-guy** [comment]
To add my 2 bits, you can get this information in other ways:
- Create a [build scan](https://scans.gradle.com/) - this records the version of Gradle, plugins, dependencies, etc that were used for the build.
- Add your own message to the build to log the version of Gradle
- Run with `--profile`, the version of Gradle is reported in the generated file

If you're using the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html), the commit that is being built already has the information about which version of Gradle was used.

**Comment by xenoterracide** [comment]
1. I don't want to create a build scan every CI run
1. This sounds more complicated than running the gradle command twice
1. and I'm supposed to get the profile file off my cloud hosted CI system? or concat it? seems again more complicated than running the command twice
1. I don't use wrapper in some cases because I'd prefer to know when gradle breaks somehow ASAP, I also allow java to update as well, and --version reports that info, I have CI jobs specifically to say, "did anything break with new deps"?

**Comment by xenoterracide** [comment]
by the way I'm not suggesting that --version configure build, simply that it prints its information and doesn't force gradle to immediately exit if I told gradle to do something else

**Comment by xenoterracide** [comment]
I feel like you just pointed out a significant design flaw... in how this works... I'd have to dig into argument/option parsing. I've certainly used programs that are capable of this.

**Comment by Vampire** [comment]
Just adding my 2ct, I also usually do the same, running Gradle twice once with `--version` to log the used Gradle, Java etc. version without putting this in each build file.

And I would also welcome if this would be considered.

Regarding default task it is easy.
- If no `--version` is given and no explicit tasks, run the default tasks
- If no `--version` is given and explicit tasks, run the explicit tasks
- If `--version` is given and no explicit tasks, just print the version and exit prematurely
- If `--version` is given and explicit tasks, print the version and run the explicit tasks

If one wants to print the version and also run the default tasks, he then has to specify the default tasks explicitly, but that is acceptable imho.

**Comment by xenoterracide** [comment]
^ I like that plan

**Comment by xenoterracide** [comment]
another option for me, a `version` task, then I could run `gradle version build`

**Comment by xenoterracide** [comment]
oh, looks like I already suggested a version task,  :'(
