### ISSUE TITLE
Classpath conflict with Gradle plugin written in Kotlin

### ISSUE THREAD

**Issue by chrisr3** [gradle/gradle#7666]
I wrote a Gradle plugin using Kotlin 1.2.71 for use with Gradle 4.10.2. When I tested my plugin with the latest Kotlin 1.3, I received this error at runtime:
```
Caused by: java.lang.NoSuchMethodError: kotlin.io.ByteStreamsKt.readBytes(Ljava/io/InputStream;)[B
	at org.testing.example.ExampleTask.doIt(ExampleTask.kt:10)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        ...
```
When I raised this issue with the Kotlin developers [KT-27867](https://youtrack.jetbrains.com/issue/KT-27867), I was told that this is because Gradle is forcing my plugin to use Gradle's own internal Kotlin library at runtime (i.e. `kotlin-stdlib-1.2.61`) rather than the `kotlin-stdlib-1.3.0` one I was expecting. The missing method is one that has been introduced in Kotlin 1.3, of course.

My example project is here: [kotlin-example.tar.gz](https://github.com/gradle/gradle/files/2561069/kotlin-example.tar.gz)

Note that it does _not_ use Gradle's Kotlin DSL.

So the problem here is two-fold. Either:
- Gradle needs proper classpath isolation for its plugins so that plugins can be written in versions of Kotlin independent of the version bundled with Gradle, or
- Gradle needs to provide a way for plugin developers to manage Kotlin version compatibility.

Cheers,
Chris

**Comment by oehme** [comment]
What you are asking for is not possible. Both the Kotlin and Groovy standard libs are part of Gradle's common API, which must be the same for everyone so that build scripts and plugins can talk to each other (using the same types). You are bound to the version that ships with Gradle. 

The fact that your example doesn't use the Kotlin DSL doesn't matter. Some of your users *will* use the Kotlin DSL and expect it to work.

**Comment by chrisr3** [comment]
@oehme Then we are left with the second part of the problem, namely:

**Which version of Kotlin _should_ plugin developers be using to write their Gradle plugins?**

Groovy developers can use `localGroovy()`, but there's no equivalent for Kotlin developers. So how do you _expect_ us all to "bind to the version that ships with Gradle"? Because the only "solution" I can see at the moment is digging into the digging into the Gradle installation, reading the version from the jars and then updating my `build.gradle` files to match _by hand_!

**Comment by bamboo** [comment]
@chrisr3 We hear you, documentation in this area is lacking. Here are a few ways of using the version of Kotlin shipped with a particular version of Gradle:

### The `kotlin-dsl` plugin
The [`kotlin-dsl` plugin](https://docs.gradle.org/5.0-rc-2/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin) applies the correct version of the Kotlin JVM plugin to your project:

```kotlin
plugins {
    `kotlin-dsl`
}
```

`kotlin-dsl` also fiddles with the Kotlin compiler configuration which might be something you don't want, in that case we recommend using the lower level `embedded-kotlin` plugin.

### The `embedded-kotlin` plugin
```kotlin
plugins {
    `embedded-kotlin`
}
```
 
### `embeddedKotlinVersion`
Alternatively, the version of Kotlin embedded in Gradle is exposed via the Kotlin DSL property [`embeddedKotlinVersion`](https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.kotlin.dsl/embedded-kotlin-version.html`) which allows a solution like:

```kotlin
plugins {
    kotlin("jvm") version embeddedKotlinVersion
}
```

I hope that helps.

**Comment by chrisr3** [comment]
Thanks, but as I've already pointed out, while my project is building a Gradle plugin in Kotlin, it is currently using the _Groovy_ DSL and I _**really**_ don't want to have to rewrite the entire project to use the Kotlin DSL instead. Especially since it's been made abundantly clear that the Groovy DSL is every bit as dependent on Gradle's embedded Kotlin version as the Kotlin DSL is!

I do not think it unreasonable to use Gradle's Groovy DSL to write Gradle plugins in Kotlin. It hasn't been deprecated, has it?

So is there an equivalent of the `embeddedKotlinVersion` property for the Groovy DSL please? Because I am going to need such a property for blocks like this:
```gradle
dependencies {
    proguard "org.jetbrains.kotlin:kotlin-compiler-embeddable:$kotlin_version"
    proguard "org.jetbrains.kotlin:kotlin-annotations-jvm:$kotlin_version"
    proguard "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    runtimeClasspath "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}
```
The `kotlin-gradle-plugin` only sets the version number for `compile` and `testCompile` configurations, of course. It ignore any configurations developers have declared themselves.

**Comment by chrisr3** [comment]
@bamboo BTW, I have just tried adding the following to my root project's `build.gradle`:
```gradle
plugins {
    id 'org.gradle.kotlin.embedded-kotlin' version '1.0.2'
}
```
and have been rewarded with this thoroughly delightful warning:
> WARNING: Unsupported Kotlin plugin version.
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.2.61` that might work differently than in the requested version `1.3.0`.

I have _no idea_ how a plugin whose _very purpose_ is to use the version of Kotlin embedded into Gradle itself could be requesting Kotlin 1.3.0, but no matter. I have removed the plugin again, of course.

**Comment by bamboo** [comment]
> is there an equivalent of the embeddedKotlinVersion property for the Groovy DSL please?

The property can be imported in a Groovy script:

```Groovy
import static org.gradle.kotlin.dsl.KotlinDependencyExtensionsKt.embeddedKotlinVersion
```

Alternatively, a Kotlin script can be applied from a Groovy script to capture the property under a different name:

```Groovy
// build.gradle

apply from: 'gradle-kotlin-version.gradle.kts'

println(kotlin_version)
```

```Kotlin
// gradle-kotlin.version.gradle.kts
extra["kotlin_version"] = embeddedKotlinVersion
```

> I have no idea how a plugin whose very purpose is to use the version of Kotlin embedded into Gradle itself could be requesting Kotlin 1.3.0

The `1.0.2` version of plugin goes with Gradle 5.0, that's why it's using Kotlin 1.3.0. The plugin is meant to be used from the Kotlin DSL via the provided plugin aliases which use the correct version.
