### ISSUE TITLE
Exception in task execution graph ready listener does not fail build

### ISSUE THREAD

**Issue by pun-ky** [gradle/gradle#7679]
Trying to implement check that will prevent dangerous task execution without explicitly set parameter, let's say `-Pforce`. However when throwing an exception in task execution graph listener / when graph ready, the exception is not causing a build failure.

### Expected Behavior

Exception is thrown and build ends with failure.

### Current Behavior

Exception is thrown, however build ends with success.

### Context

The task is configured lazily using new API `task.register`. Regardless that the task could be unintentionally eagerly loaded in plugin user buildscript by using `tasks.getByName()` instead `tasks.named()` , I need to hook to the moment just after configuration phase to perform such check. During task execution is too late, because my build could be running for some time (even few minutes) then failing at last task requiring that `-Pforce` set could be very annoying. And that's the reason I tried with:

![image](https://user-images.githubusercontent.com/10673561/48249850-996b2600-e3fc-11e8-8fe9-381ece8c8ba3.png)

### Steps to Reproduce (for bugs)

[gradle-should-fail.zip](https://github.com/gradle/gradle/files/2565033/gradle-should-fail.zip)

### Your Environment

 ```
$ sh gradlew --version

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_121 (Oracle Corporation 25.121-b13)
OS:           Windows 10 10.0 amd64
```

**Comment by pun-ky** [comment]
heh, upgraded to 5.0 and seems that you have fixed that in the meantime :) I am curious, what was the root cause?

**Comment by big-guy** [comment]
I suspect it's related to #7329 if this worked in 4.9.

Since this is a really common pattern, we really should have something like:
```
<T extends Task> void whenTaskInGraph(TaskProvider<T> task, Action<T> action);
```
in `TaskExecutionGraph` that does something similar to what you're doing with `whenReady`.

That way, you could just do:
```
val a = tasks.register("a", A::class.java)
project.gradle.taskGraph.whenTaskInGraph(a) {
     this.willBeExecuted()
}
```

Is this something you'd be interested in contributing?

**Comment by pun-ky** [comment]
Hard to say if it is common pattern. Sure, I will consider contributing after completing my plugin development. Thanks for your response.
