### ISSUE TITLE
Finalizer tasks order may not be honored in all cases with parallel enabled

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#768]
### Expected Behavior

The task order should be correctly honnored when multiple finalizer tasks points to the same task event when parallel execution is enabled
### Current Behavior

According to [this build log](https://builds.gradle.org/viewLog.html?buildId=1600741&buildTypeId=Gradle_Master_CoveragePhase_LinuxCoverage_LinuxJava17ParallelIntegrationTests_5L) from TeamCity, the order is not respected:
- Test `honours task ordering with finalizers on finalizers` found [here](https://github.com/gradle/gradle/blob/ad1a7fbed7e6088a88845c7da4a4e396e6826f29/subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskExecutionIntegrationTest.groovy#L517-L574): The task `h` is executed before task `e` is executed.
- Test `multiple finalizer tasks point to the same task` found [here](https://github.com/gradle/gradle/blob/ad1a7fbed7e6088a88845c7da4a4e396e6826f29/subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/TaskExecutionIntegrationTest.groovy#L479-L514): task `e` is executed twice and task `h` is executed before task `e`. 
### Context

Parallel execution may report invalid tasks ordering in presence of several level of finalizer tasks.
### Steps to Reproduce (for bugs)

Execute test in parallel: `-Dorg.gradle.parallel.intra=true` and `-Porg.gradle.parallel=true`

**Comment by eriwen** [comment]
Given that `--parallel` shall be deprecated in favor of the Worker API, I vote we close this as `wont-fix`. Agreed?

**Comment by ldaley** [comment]
Why is `--parallel` being deprecated? My understanding was that it would become default.

Perhaps you mean `-Dorg.gradle.parallel.intra`.

**Comment by eriwen** [comment]
@ldaley My understanding is that we will enable it by default using the Worker API. `--parallel` as it stands today is considered "unsafe" and once we have sufficient Worker API coverage we won't need `--parallel` anymore. The equivalent of `--no-parallel` will be `--max-workers=1`. 

I don't think we'll have a warning message for use of `--parallel` for awhile, though, and it'll certainly be around until at least 6.0
