### ISSUE TITLE
Question: How to import a module from a parent folder to another module?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [gradle/gradle#7685]
Simple question:

If we have a structure like this:

```
/a
/b
/x/y/z
```

How can we import the module `a` from `z`?

I tried some varations like

```
implementation project(:a)
implementation project(:../../:a)
```

But I haven't had success yet.

If I try `implementation project(:a)` from `b` it works ok.

**Comment by big-guy** [comment]
`project(":a")` should work if both projects are in the same [multi-project build](https://docs.gradle.org/current/userguide/multi_project_builds.html).

This sort of thing is better asked on our [forums](https://discuss.gradle.org/).
