### ISSUE TITLE
Gradle - JavaCompilationError / Build Error

### ISSUE THREAD

**Issue by christianquirante** [gradle/gradle#7687]
**### Expected Behavior**
When I changed my Gradle from distributionUrl=https://services.gradle.org/distributions/gradle-4.4-all.zip to 4.6-all.zip, no errors are showing up, but since the

```
    dependencies {
    classpath 'com.android.tools.build:gradle:3.1.3'
}
```
is not a stable version, I have to changed it to the latest available tools.build

```
  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
}
```
after that I got the JavaCompilationError, but when I stay at 3.1.3 the error doesn't occur. What do I need to configure first, before upgrading from 3.1.3 to 3.2.1?

**### Current Behavior**
These are the errors that showed which I think is, particularly about AndroidManifest.xml (since it couldn't find the object class which are in the AndroidManifest.xml) after doing the gradle upgrade.

1) Cannot Find Symbol Classes anymore

2) Couldn't find the AndroidManifest.xml file anymore

3) java.lang.RuntimeException: java.lang.IllegalArgumentException: couldn't make a guess in a particular databinding anymore

**### Context**
Currently I couldn't build my project in java because of the error I got from upgrading my gradle.

**### Steps to Reproduce (for bugs)**
To reproduce this, I think you need to have this:

1) Target SDK 28
2) Tools.Build.grade.3.2.1
3) Android Studio 3.2

**Comment by marcphilipp** [comment]
The Android plugin is not a core Gradle plugin. Please consult the [release notes of the Android plugin](https://developer.android.com/studio/releases/gradle-plugin).
