### ISSUE TITLE
addAllSuccessorsRecursively throws StackOverflowException in presence of a long dependsOn chain on a finalizer task

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#769]
### Expected Behavior
No `StackOverflowException` should be thrown. Although the JVM could run out of memory and/or performance may suffer if the depends on chain is abnormally long.

### Current Behavior
A `StackOverflowException` can be thrown from [`addAllSuccessorsRecursively`](https://github.com/gradle/gradle/blob/ad1a7fbed7e6088a88845c7da4a4e396e6826f29/subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionPlan.java#L398-L414).

### Context
The case never present itself, but it's something that could be improved (memory wise).

### Steps to Reproduce (for bugs)
Around a 9000 depends on chain will cause an `StackOverflowException`.

**Comment by lacasseio** [comment]
CR for addAllSuccessorRecursively: https://code-review.gradle.org/cru/REVIEW-6354

**Comment by eriwen** [comment]
@lacasseio Who is responsible for pushing this forward? Who is reviewing?

**Comment by lacasseio** [comment]
I was just about to ping back on this, @bmuschko was the one who did the first review.

**Comment by bmuschko** [comment]
This card can only be finished if the other corresponding card is going to be implemented as well. I suggest we roll back the changes to production code to avoid introducing a regression but keeping the tests. Alternatively, we can implement both cards. Your call, @lacasseio.

**Comment by lacasseio** [comment]
Last code review fix was done here: https://github.com/gradle/gradle/commit/4d15c4edb296b0226ac4a17143172152d17c5888

**Comment by lacasseio** [comment]
I decided to push forward as the change for gradle/gradle#841 was quite trivial and additional change was done to the code for this issue (made reverting less trivial). The code for the other issue is also in code review.
