### ISSUE TITLE
Gradle native binary generated by Graalvm

### ISSUE THREAD

**Issue by luistrigueiros** [gradle/gradle#7690]
This is an idea/sugestion proposal:

Now with @graalvm would it be possible to ship native binary version of  Gradle that would be fast to lunch and maybe does not share some of the problems of the deamon mode.

Thank you.
Luis Oscar

**Comment by marcphilipp** [comment]
Thanks for the proposal. Howevver, AFAIK Graal doesn't fully support reflection which is a showstopper for us at this point.

**Comment by mkotsbak** [comment]
Reflection is partly supported with some effort needed: https://www.graalvm.org/reference-manual/native-image/Reflection/
Probably applies to all plugins in use too...
