### ISSUE TITLE
Cannot access a prior verison of the artifact produced by a project

### ISSUE THREAD

**Issue by bjhargrave** [gradle/gradle#7706]
### Expected Behavior

I have a task which needs to access the prior version of the artifact built by a project to use as a baseline for the currently building version of the artifact. The prior versions of the artifact are in a configured repository.

Doing the obvious:

    configurations {
      prior
      prior.transitive = false
    }

    dependencies {
      prior "${group}:${project.name}:(,${project.version}["
    }

I would expect the configuration to hold the prior version of the project's artifact from the configured repository.

### Current Behavior

The configuration holds the project's output (the currently built artifact) and not a prior version.

    $ gradle dependencies --configuration prior prior

    > Task :dependencies

    ------------------------------------------------------------
    Root project
    ------------------------------------------------------------

    prior
    \--- test:baselinetask1:(,1.1.0[ -> project : (*)

    (*) - dependencies omitted (listed previously)

    A web-based, searchable dependency report is available by adding the --scan option.

    > Task :prior
    prior: /Users/hargrave/tmp/gradle-dep/prior/build/libs/baselinetask1-1.1.0.jar

    BUILD SUCCESSFUL in 0s
    2 actionable tasks: 2 executed

If I delete the dependencies section and add a `defaultDependencies` closure:

    configurations {
      prior
      prior.transitive = false
      prior.defaultDependencies { deps ->
        println "prior: defaultDependencies ${group}:${project.name}:(,${project.version}["
        Dependency priorDep = dependencies.create('group': group, 'name': project.name, 'version': "(,${project.version}[") {
          force = true
          transitive = false
        }
        println "priorDep: ${priorDep}"
        deps.add(priorDep)
      }
    }

    task prior {
      doFirst {
        println "prior: ${configurations.prior.asPath}"
      }
    }

Then it works as desired _on versions of Gradle prior to 4.8_:

    $ gradle dependencies --configuration prior prior

    > Task :dependencies

    ------------------------------------------------------------
    Root project
    ------------------------------------------------------------

    prior
    prior: defaultDependencies test:baselinetask1:(,1.1.0[
    priorDep: DefaultExternalModuleDependency{group='test', name='baselinetask1', version='(,1.1.0[', configuration='default'}
    \--- test:baselinetask1:(,1.1.0[ -> 1.0.0

    A web-based, searchable dependency report is available by adding the --scan option.

    > Task :prior
    prior: /Users/hargrave/tmp/gradle-dep/prior/repodir/test/baselinetask1/1.0.0/baselinetask1-1.0.0.jar

    BUILD SUCCESSFUL in 0s
    2 actionable tasks: 2 executed

But on Gradle 4.8 or later, the `defaultDependencies` section results in the project's artifact instead of the prior version as desired.

    $ gradle dependencies --configuration prior prior

    > Task :dependencies

    ------------------------------------------------------------
    Root project
    ------------------------------------------------------------

    prior
    prior: defaultDependencies test:baselinetask1:(,1.1.0[
    priorDep: DefaultExternalModuleDependency{group='test', name='baselinetask1', version='(,1.1.0[', configuration='default'}
    \--- test:baselinetask1:(,1.1.0[ -> project : (*)

    (*) - dependencies omitted (listed previously)

    A web-based, searchable dependency report is available by adding the --scan option.

    > Task :prior
    prior: /Users/hargrave/tmp/gradle-dep/prior/build/libs/baselinetask1-1.1.0.jar

    BUILD SUCCESSFUL in 0s
    2 actionable tasks: 2 executed

### Context

I need to access the prior version of the artifact built by a project to use as a baseline for the currently building version of the artifact. I was able to do this via `defaultDependencies` prior to Gradle 4.8. Now I cannot get access to a prior version of a project's built artifact.

### Steps to Reproduce (for bugs)

See https://github.com/bjhargrave/gradle-issue-prior for the example gradle project referenced above.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/tbwrj6kvhmpec

**Comment by mnlipp** [comment]
Searching around for this topic in the last few days, it is incredible that I didn't come across this issue and created a [duplicate](https://github.com/gradle/gradle/issues/8717#issuecomment-470918016).

I have, however, found a [work-around](https://discuss.gradle.org/t/is-the-default-configuration-leaking-into-independent-configurations/2088/6) while searching, which boils down to:
```
def oldGroup = project.group
try {
    project.group = 'dummy_group_for_baselining'
    configurations.baseline.files
} finally {
    project.group = oldGroup
}
```
I have successfully tested this hack with bnd gradle plugin 4.1.0 and gradle 4.10.3 and 5.2.1.

**Comment by ljacomet** [comment]
relates to #1629
