### ISSUE TITLE
Gradle lists files in all build output directories before executing the first task action

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#7707]
Before executing a task, Gradle does several other checks:
- Does the task have any sources? If yes, execute the task. If no, does it have any outputs? If yes, delete the outputs. If no, mark the task as NO-SOURCE.
- Does the task have any _stale_ outputs? If yes, delete them.  If no, execute the task.

The process for determining what is safe to delete currently lists all build directories (maybe some multiple times?). Depending on the OS, the filesystem, size of the project and number of files, this may not be immediately noticeable as a problem. 

On some systems, this can cause the first task to take ~seconds before executing anything.  Since these checks happen as part of up-to-date checks, even completely up-to-date tasks can take ~seconds.

### Expected Behavior
Gradle does not need to spend time looking at every output directory before executing a task.

### Current Behavior
Gradle looks at every output directory before executing a task.

### Context
https://discuss.gradle.org/t/gradle-scan-shows-first-task-taken-up-by-worker-takes-a-long-time/29394/6

**Comment by wolfs** [comment]
@big-guy What do you mean by "walks all build directories"? I don't see the implementation doing any file walks. As long as you do not register a file tree as a target for the `clean` task, no file walking should take place.

The paths are resolved, and that seems to be very slow on Windows.

Looking at the stack trace, it seems like we end up resolving a `MinimalFileTree` after all. Any ideas how that can happen?

**Comment by big-guy** [comment]
"walks" isn't the right way to describe it.  We look at each "output" directory and list its contents:
https://github.com/gradle/gradle/blob/3b15ec768759e3ec9b238bef7becb46e6e3ea39a/subprojects/core/src/main/java/org/gradle/internal/cleanup/DefaultBuildOutputCleanupRegistry.java#L68-L73

`outputs` here is a collection of all the delete targets for all `clean` tasks, buildDir and all class output directories.

**Comment by big-guy** [comment]
I would expect listing the contents of `build` directory to be relatively fast (we're going to have ~10s of directories, usually).  It's unlikely that there are a lot of other directories/paths added to a `clean` task to the point that it would be a problem.

Could a bulk of the time go to listing the contents of the source set output? Registered here:
https://github.com/gradle/gradle/blob/3126964f14d430a7fdae602572bf41c6a323f474/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L273

**Comment by wolfs** [comment]
@big-guy Why do you think we list the contents of the `build` directory? The build directory is registered as a file collection containing one element, so iterating this file collection will exactly yield this on directory. The same is true for `DefaultSourceSetOutput`.

Am I missing something?

**Comment by wolfs** [comment]
I logged all the paths in the gradle build itself. We `1028` output paths registered. We end up with 3-4 for each source set: `build/classes/{java,groovy}/<sourceSetName>`, `build/{,generated}resources/<sourceSetName>`. We have 3-5 source sets per sub-project: `main`, `test`, `integTest`, `testFixtures`, and `crossVersionTest`.
There is also the `build` directory for each subproject.

**Comment by wolfs** [comment]
@big-guy There was some change for 5.1 which may have made the whole NO_SOURCE handling a little bit faster. Can you maybe try again and see if the problem persists?

**Comment by wolfs** [comment]
Let's close this. Please re-open if it is still an issue.
