### ISSUE TITLE
5.0-rc-2: Tooling API cannot open buildSrc

### ISSUE THREAD

**Issue by kelemen** [gradle/gradle#7708]
Since "-u" was removed from 5.0, I have removed passing that when loading projects. However, I can no longer open *buildSrc* this way. As it now complains that *buildSrc* is not part of the build referenced in the *settings.gradle* file (which is technically true of course). What is the preferred way to load *buildSrc* now (and some projects without *settings.gradle* in the subdirectory of a Gradle project)?

**Comment by eskatos** [comment]
ftr, removal was done in https://github.com/gradle/gradle/pull/6929

**Comment by oehme** [comment]
Add a settings.gradle file to buildSrc if you want to open it separately.

**Comment by oehme** [comment]
After reading the corresponding forum post, I realise you are asking for a tool that has to deal with all kinds of builds. I think we can ease that transition.

**Comment by kelemen** [comment]
Yes, it is actually for the NetBeans integration. To be honest, I didn't even know that *buildSrc* can have its own *settings.gradle* because it does not seem obvious what will be put on the classpath of the scripts.

Anyway, what will be the resolution of this issue? What should I do to cooperate with Gradle. I'm guessing that there are lots of projects with a *buildSrc* and no *settings.gradle*. What can I do with that? If I remove the "-u" then all those projects become unloadable. If I keep it, I won't be able to load 5.0+ projects and I can't tell the Gradle version before providing this argument.

**Comment by marcphilipp** [comment]
With the change in #7719, Gradle 5.0 will automatically not search upward if the project dir is called `buildSrc`. Thus, you should be able to import `buildSrc` projects without `-u` in Gradle 5.0.

**Comment by kelemen** [comment]
Thanks, though I still have a problem because I can't always decide what Gradle version will be used before loading a project. So, I don't know if I should pass "-u" or not.

**Comment by oehme** [comment]
You can, the `BuildEnvironment` tooling model will tell you without needing to load the project. It's a purely client-side model.

**Comment by kelemen** [comment]
Thanks, I'm actually using that, but I'm passing the same arguments (say "-c") as the subsequent model loading or task execution. Is it safe, to omit the "-u" for that?

**Comment by oehme** [comment]
You shouldn't need to ask that question for `buildSrc`, because it should use the same distribution/Gradle version as the main build.

**Comment by kelemen** [comment]
The user can open *buildSrc* without opening the actual project. This might even be important if there is an issue with *buildSrc* (which would prevent the loading of the owner project).

**Comment by kelemen** [comment]
Also, I might be mistaken but it seems to me that if there is a *settings.gradle* for *buildSrc*, Gradle ignores the *gradle-wrapper.properties* (I'm guessing that it does not try to load the approriate from the root project). Altough, I guess this was probably the case with "-u" as well. So if it is so, this is not really a regression.

**Comment by oehme** [comment]
buildSrc is not really designed well to be opened on itself. You'd need wrapper.properties and gradle.properties in it and they would have to exactly match the main project's configuration.

The long term goal here is to make buildSrc behave more like included builds in a composite, so IDEs don't need to do anything special, it would just be imported like any other included build. Until then we're left with workarounds like the ones explained above.

**Comment by kelemen** [comment]
Yes but I might still wish to open the *buildSrc* when it fails to build for some reason and fix the issue. Also, it is rather awkward to handle this in the NB API given all the automatisms. By the way, is it possible to fix this in a way that *buildSrc* not needing *settings.gradle* is detected on the client side? I believe this would work for me fine because then I just had to update the Tooling API to 5.0.

**Comment by kelemen** [comment]
Thank you, then I'll probably be able to work with it without problem.
