### ISSUE TITLE
buildSrc bizarrely doesn't compile one dependency when upgrading to Gradle 5

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#7710]
My `buildSrc` used to compile fine before Gradle 5.0, but upgrading breaks `Grgit` for whatever reason. It's _only_ that one dependency. Not sure what's going on. 🤷‍♂️

Project: https://github.com/SUPERCILEX/Robot-Scouter/tree/8a5dfc0ade1e31386fd8c261a8aa708a9808b3a1
Setup: `./gradlew setup`

Run `./gradlew wrapper --gradle-version 5.0-rc-2` twice. The second time will show compilation errors relating to `Grgit`.

**Comment by oehme** [comment]
Can you please include the error you are seeing?

**Comment by SUPERCILEX** [comment]
It's symbol not found errors (could not find `Grgit`). As if I didn't have the dependency at all.

**Comment by oehme** [comment]
`grgit-gradle` only has a runtime dependency on `grgit-core`, which is why Gradle 5.0 (correctly) doesn't have it on the compile classpath. It was probably published with an outdated version of the plugin-publish plugin @ajoberstar .

**Comment by SUPERCILEX** [comment]
Gotya, thanks! Just curious, why did this work before?

**Comment by oehme** [comment]
It worked before because Gradle <5.0 would not separate compile/runtime for Maven dependencies.
