### ISSUE TITLE
Upgrade to Groovy 2.5.4

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#7711]
Groovy 2.5.4 was just released and we should upgrade to the latest version to benefit from bug fixes.

**Comment by lptr** [comment]
I won't have the time to do the upgrade, but published `groovy-all-1.0-2.5.4` so anyone ready to babysit the build can bump the version number.

**Comment by marcphilipp** [comment]
FYI https://discuss.gradle.org/t/gradle-5-0-rc-2-is-now-available-for-testing/29447/8

**Comment by embee1981** [comment]
Hi guys, looks like there was a critical bug fixed for groovy 2.5.4 - https://issues.apache.org/jira/browse/GROOVY-8871. I stumbled across this as one of my home brewed plugins stopped working due to the same exception

**Comment by eskatos** [comment]
Done in https://github.com/gradle/gradle/commit/16d1b2af48ac6b45bbe96ad83a97cd07caf7b4ed
