### ISSUE TITLE
Gradle VCS cache for source dependencies fills up

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#7713]
### Expected Behavior
Gradle VCS cache for source dependencies does not fill up

### Current Behavior
Gradle VCS cache for source dependencies fills up

### Context
I needed that latest commit for a Gradle plugin as it adds important new functionality.
I decided to try the new source dependencies for this and depended on branch `master` of the plugin.
It works great so far, but within the last two days I already have 3 complete clones now in the VCS cache.
For this plugin it is not that bad as it is small, but if you have source dependencies on larger projects this can become a serious problem very fast.

Every time a new commit is seen when I build, a complete new clone is made.
I'd like to suggest to
- just update the existing clone if depending on a branch
- if multiple worktrees are needed due to dependency on different versions from different projects for example, use `git-worktree` to at least only duplicate the worktree and not the full repository
- have some cleanup when the dependency is not needed anymore, at least if it is bigger than some threshold

### Your Environment
Gradle 4.10.2

**Comment by big-guy** [comment]
Have you seen a problem with clean-up or did you just notice the directory growing?

> just update the existing clone if depending on a branch
We need to keep separate working directories for each resolved version, but we could do something different here. Originally, we were going to keep a central clone in a global cache and use dedicated work trees. 

> if multiple worktrees are needed due to dependency on different versions from different projects for example, use git-worktree to at least only duplicate the worktree and not the full repository
This is a good idea too, but JGit doesn't support this yet AFAIK.

> have some cleanup when the dependency is not needed anymore, at least if it is bigger than some threshold
There is a clean-up for this cache.  It's time-based at 7 days.

**Comment by Vampire** [comment]
> Have you seen a problem with clean-up or did you just notice the directory growing?

I didn't see any clean-up happening and the source dependencies not mentioned in the cleanup part of the release notes.

>> just update the existing clone if depending on a branch

> We need to keep separate working directories for each resolved version, but we could do something different here. 

May I ask why?
I understand that for different resolved versions you need different worktrees, as one part of the build could need one version and another one a different version.
But if the dependency is on "branch XXX", all could use the same worktree, couldn't they?

>> if multiple worktrees are needed due to dependency on different versions from different projects for example, use git-worktree to at least only duplicate the worktree and not the full repository

> This is a good idea too, but JGit doesn't support this yet AFAIK.

Yeah, to my knowledge they unfortunately _still_ don't support worktrees, I wasn't aware you use JGit for this.

So one option could be to use a natively available Git if there is one present with detecting it and also being able to configure the path to it via some property.

Another option could be to make a bare clone that is not cleaned as long as there are non-bare clones and then make non-bare clones specifying the bare clone with `--reference`, so that the object files are reused at least if JGit supports that at least.

Another option could maybebe to reuse the same Git-dir, specifying different worktrees for each command if JGit supports that, like using the `--git-dir` or `--work-tree` parameters to command-line Git.

>> have some cleanup when the dependency is not needed anymore, at least if it is bigger than some threshold

> There is a clean-up for this cache. It's time-based at 7 days.

Ah, ok, nice, then I just didn't notice it yet. :-)
But still, if you often recompile and the projet you are using is also pretty active, you could still end up with maaaany clones in there if not reusing the cache dir for branch-dependencies.
An old branch dependency cache dir is never needed again, is it?
Once the branch advanced always the new cache dir is used, thus my idea to update the existing clone instead of making new clones for each change when depending on a branch.

**Comment by lacasseio** [comment]
Everything related to source dependencies should stay open, it's an unfinished and unpolished but important feature.

**Comment by ljacomet** [comment]
Source dependencies is not an area of focus for now.
