### ISSUE TITLE
Gradle plugins cannot determine which version of Kotlin they need to use.

### ISSUE THREAD

**Issue by chrisr3** [gradle/gradle#7714]
According to #7666:

> Both the Kotlin and Groovy standard libs are part of Gradle's common API, which must be the same for everyone so that build scripts and plugins can talk to each other (using the same types). You are bound to the version that ships with Gradle.

However, Gradle doesn't provide any way for developers to know _which_ version of Kotlin they need to bind their plugins to, c.f. Groovy's `localGroovy()` mechanism.

With the release of Kotlin 1.3.0, IntelliJ is now aggressively pushing a new Kotlin plugin, which means that _at the very least_ Gradle plugin projects now need to include something like:
```gradle
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        apiVersion = "1.2"
        languageVersion = "1.2"
    }
}
```
However, this could also reasonably be expected to change in future, when Gradle upgrades its bundled Kotlin from 1.2.61 and (some) plugin developers choose to use the new Kotlin features.

Ref: [KT-27867](https://youtrack.jetbrains.com/issue/KT-27867).

**Comment by oehme** [comment]
See https://github.com/gradle/gradle/issues/7666#issuecomment-438280667
