### ISSUE TITLE
Fix deprecation warning when exposing dependencies to artifact transforms

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#7729]
This is related to PR #7672 where we had to accept some deprecation warnings in tests, see here: https://github.com/gradle/gradle/blob/ed0fa898c25fb57ec1d6ce9e3850d6a773ae222e/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformWithDependenciesIntegrationTest.groovy#L25-L26

**Comment by ljacomet** [comment]
Fixed by #7962
