### ISSUE TITLE
Error when setting "dimension" in Android 

### ISSUE THREAD

**Issue by dovahkiin98** [gradle/gradle#7730]
I'm using **gradle-5.0-milestone-1** and **3.4.0-alpha03** on **Android Studio 3.4 Canary 3**, and **Kotlin 1.3.10**.
In Kotlin Scripts for build.gradle in the app version, 
```kotlin
productFlavors {
    create("deploy") {
        dimension = "demo"
    }
    create("development") {   
        dimension = "demo"
        minSdkVersion(24)
        resConfigs("en", "xxhdpi")
    }
}
```
The line **dimension =X** is underlined as an error saying **Val cannot be assigned**. But build, sync, and everything else works fine.

**Comment by eskatos** [comment]
`ProductFlavor.getDimension()` return type is nullable but the parameter to `ProductFlavor.setDimension(dim)` isn't.

You can use the setter directly:
```kotlin
productFlavors {
    create("deploy") {
        setDimension("demo")
    }
}
```
