### ISSUE TITLE
Tooling API: Allow to explicitly retrieve information about unresolved dependencies

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#7733]
Original issue was posted here: https://issues.gradle.org/browse/GRADLE-1995

The Tooling API doesn't allow to get information about unresolved third-party dependencies.

### Expected Behavior
 There is some API to determine if the dependency is resolved (e.g. `IdeaSingleEntryLibraryDependency.isResolved()`)

### Current Behavior
 Unresolved dependencies are indistinguishable from resolved ones.

### Context
 As a workaround, Gradle Idea import has to rely on names of files produced by `UnresolvedIdeDependencyHandler` for this. It is very fragile approach, e.g. broken in 5.0-rc-2 with Idea 2018.2

### Steps to Reproduce (for bugs)

1. Go to $GRADLE_HOME/samples/java/quickstart;
2. Define, say, version '10.2' for 'commons-collections' dependency at 'build.gradle' there;
3. Start the program below:

```java
package org.jetbrains.plugins.gradle;

import org.gradle.tooling.GradleConnector;
import org.gradle.tooling.ModelBuilder;
import org.gradle.tooling.ProjectConnection;
import org.gradle.tooling.model.idea.*;

import java.io.File;


public class GradleStartClass {

  private static final String GRADLE_PROJECT_PATH = "/home/denis/dev/gradle/gradle-1.0-milestone-6/samples/java/quickstart";

  public static void main(String[] args) {
    test("/home/denis/dev/gradle/gradle-1.0-milestone-6"); // Don't expect exception here
  }

  private static void test(String gradleHome) {
    GradleConnector connector = GradleConnector.newConnector();
    connector.useInstallation(new File(gradleHome));
    connector.forProjectDirectory(new File(GRADLE_PROJECT_PATH));
    ProjectConnection connection = connector.connect();
    ModelBuilder<? extends IdeaProject> modelBuilder = connection.model(IdeaProject.class);
    IdeaProject project = modelBuilder.get();
    for (IdeaModule module : project.getModules()) {
      for (IdeaDependency dependency : module.getDependencies()) {
        if (dependency instanceof IdeaModuleDependency) {
          continue;
        }
        System.out.printf("Dependency: %s%n", ((IdeaSingleEntryLibraryDependency)dependency).getFile());
      }
    }
  }
}
```

**Comment by leonardobsjr** [comment]
Hello. I would like to have a try at fixing this issue. I've sent a PR to the eclipse/buildship using the file names produced, but, as @nskvortsov  said, it's really fragile. Can you guys send me pointers about how i should approach this?

I've taken a look at the code and, at a first approach, i've added the resolved flag to AbstractLibrary and changed EclipseDependenciesCreator to have another collection with the unresolvedDependencies separated from the files collection.
