### ISSUE TITLE
Gradle 5.0 > Improved support for test filtering for multi projects and composite build from the command line using --tests option

### ISSUE THREAD

**Issue by ghilainm** [gradle/gradle#7748]
### Expected Behavior
It should be possible to do test filtering using command line option using --test option in composite builds and in multi project builds.

### Current Behavior
It fails with the following error.

```
(develop)$ gradle test --tests *IT

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :test from command line.
> Unknown command-line option '--tests'.

* Try:
Run gradle help --task :test to get task usage details. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings
```

### Context
Gradle 5
Launched command `gradle test --tests *IT` from root project of multi project build.

*Update*: it works if defined using the allprojects block but not the subprojects block. I would expect it to work in both situation. It definitely does not work for composite builds.

**Comment by lethidiemmy961996** [comment]
Hello, Any news?
I have a same error too. I tried with gradle 4.6, 4.10.1, 5.5.1. But it does not works.
