### ISSUE TITLE
Build scan privacy

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#7749]
I'm not able to find any information on what seems to be a very important part of build scan, privacy. I'd like to know how long Gradle keeps the scan, where are the scan kept (e.g. Gradle private datacenter, Amazon AWS), and who has access to the scans. Also, once a scan is created on scans.gradle.com, how do I get it deleted?

**Comment by big-guy** [comment]
The terms of services and privacy policies are available [here](https://gradle.com/legal/terms-of-service/).  Builds need to opt into these terms as [described in our docs](https://docs.gradle.com/build-scan-plugin/#accept_the_scans_gradle_com_terms_of_service).

You can [delete build scans or request build scans to be deleted](https://discuss.gradle.org/t/removing-published-build-scans-from-scans-gradle-com/26309).
