### ISSUE TITLE
How to get the full name of a task executing (without abbreviations)

### ISSUE THREAD

**Issue by athkalia** [gradle/gradle#7756]
Hello,

This is more of a question rather than an issue.
I am trying to get the name of a task using `getGradle().getStartParameter().getTaskNames()`
The thing is that this does not take into account task name abbreviations. So if I am running the task `aD` (which is an abbreviation for `assembleDebug`), the command `getGradle().getStartParameter().getTaskNames()` will only return `aD`. Is there a way for me to get the whole task name, `assembleDebug` in this case?

Thanks in advance.

**Comment by big-guy** [comment]
Our [forums](https://discuss.gradle.org) or [community Slack](https://github.com/gradle/gradle/issues/3518#issuecomment-384358716) is a better place to ask this.

If you want to selectively do something if a particular task is being run, you should check if that [task is in the task graph](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#configure-by-dag).

**Comment by cylee0909** [comment]
> Our [forums](https://discuss.gradle.org) or [community Slack](https://github.com/gradle/gradle/issues/3518#issuecomment-384358716) is a better place to ask this.
> 
> If you want to selectively do something if a particular task is being run, you should check if that [task is in the task graph](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#configure-by-dag).

sadly, when findtask use  abbreviation name we always get null

**Comment by cylee0909** [comment]
meet the same issue, does any one has some solutions? thanks alot!

**Comment by victorchoy** [comment]
I think  many people meet the question.  Is there any solution? It's quite possible to check task name to prepare something before task execution
