### ISSUE TITLE
Check Caffeine to replace Guava caches

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#7757]
@ben-manes on [the dev list](https://groups.google.com/d/msgid/gradle-dev/689dae24-5fcf-4399-be6b-594cc91e8d17%40googlegroups.com):

> Since Gradle 5.0 is Java 8-based, the usages of Guava's cache can be replaced with Caffeine. There seem to be [25 files](https://github.com/gradle/gradle/search?p=2&q=%22com.google.common.cache.CacheBuilder%22&type=&utf8=%E2%9C%93) importing it - are any of these performance critical like in your original testing Luke / Lari? If so, you can switch over without much complexity. You may want to set to Caffeine.executor(Runnable::run) if callbacks (like RemovalListener) need to run on a known thread (vs ForkJoinPool). I'd also advise reviewing your ample usage of soft/weak references, since soft is fairly a poor approach in most cases.

We should see how this works as a replacement. The benchmarks look promising: https://github.com/ben-manes/caffeine/wiki/Benchmarks

![image](https://user-images.githubusercontent.com/495366/48699353-8d941680-ebe9-11e8-99b3-7a4814b56a60.png)

**Comment by LifeIsStrange** [comment]
@lptr I feel like this has fell under the radar? Cache performance probably is important to overall gradle performance so this is worth exploring

**Comment by lptr** [comment]
You're right, it did. I wonder if the results still hold, though. We are planning to upgrade to Guava 30 with Gradle 7.0. Maybe it'll be worth taking a look at this then.

**Comment by ben-manes** [comment]
Guava’s cache stopped active development 8-10 years ago, so the benchmarks still holds true. That is with 64 concurrency level, whereas the default is 4, so Guava is performing worse in your usages. How much of a gain, if any, depends on if those caches are performance sensitive.

**Comment by lptr** [comment]
We have a few caches that are performance sensitive I think.

Would be lovely if someone could create a PR. I'd be happy to run our performance suite on it. Doing so would increase the chance of getting this implemented by a lot.

**Comment by ben-manes** [comment]
@lptr done, please see #15354

**Comment by lptr** [comment]
As shown by https://github.com/gradle/gradle/pull/15354 there is no noticeable performance improvement by doing the switch, yet there is a significant amount of added complexity if we do it. Let's not do it then.
