### ISSUE TITLE
Clarification of a dependency resolution API

### ISSUE THREAD

**Issue by Myllyenko** [gradle/gradle#7758]
I think that documentation of a dependency resolution API (namely its `ResolvedConfiguration` and `ResolutionResult` parts) is currently quite vague.

### Context
I write a set of tasks that:

1. classifies dependencies considering their coordinates and POM content;
2. creates project distribution considering dependency classification results;
3. converts Gradle dependency version notation to the custom format.

So, first, I need to analyse a dependency graph. Looks like I have two options: [`ResolvedConfiguration`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolvedConfiguration.html) and [`ResolutionResult`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/result/ResolutionResult.html). Their descriptions themselves are not deep (I think they lack use cases) but considering their methods I concluded that the two main differences between them are:

1. `ResolvedConfiguration` actually downloads resolved dependencies;
2. `ResolutionResult` contains information about "source dependencies" (like requested version ranges).

So I decided that I should go with `ResolutionResult` for dependency analysis.

But I've faced the following obstacles:
1. I'm unable to find information about dependency classifiers (strangely, in `ResolvedConfiguration` it is easily accessible).
2. There is a maze of dependency identifiers which looks all the same for me as a user: for example, `ModuleVersionIdentifier` and `ModuleComponentIdentifier`. It would be great if documentation of these classes contained their use cases and information about mapping between a dependency as it is declared by a user and its ID (or IDs). Something like "if a user declares `compile group: 'com.google.guava', name: 'guava', version: '27.0-jre'`, it is converted to `SomeIdentifier` with the following property values..."
3. I can't find API that represents Gradle dependency ranges (something like Maven's [`VersionRange`](https://maven.apache.org/ref/3.5.0/maven-artifact/apidocs/org/apache/maven/artifact/versioning/VersionRange.html)) or other means that allow one to parse/convert Gradle dependency version notation.

**Comment by melix** [comment]
Thanks @Myllyenko . Basically the `ResolutionResult` API is replacing the `ResolvedConfiguration` one. It's main advantage is being _lazy_. However as you noticed there are a few issues, not everything is available using this API, which prevents us from removing the `ResolvedConfiguration` API. We're aware of this and want to fix it as part of cleaning up the dependency management APIs.

**Comment by Myllyenko** [comment]
@melix 
Thank you for the information. As I am interested in this functionality, I am ready to create a pull request with corresponding changes. But it will require some guidance from the Gradle team on implementation details.

The goals of this PR:

* expose dependency classifiers;
* make it easy to download either `ResolvedComponentResult` as is or with some modifications (namely I'm interested in changing a classifier);
* allow dependency version range inspection.
