### ISSUE TITLE
Add baseName to NativeBinarySpec

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#777]
Following a recent question from the forum and based on personal experience, it should be easy to modify the output file name for each binary. 

### Expected Behavior
The proposed fix would be to add a baseName or similar behavior to change the name of the binary. This solution should also be back port to JVM model by adding such feature at the BinarySpec level.

### Current Behavior
Current solution is to modify the output file path (which differ per binary type). Several problem exists with this solution such as dealing with extension (executable on Linux doesn't have one) and the different naming for getter/setter of the output file property.

### Context
This is a common pattern done in the native.

**Comment by zosrothko** [comment]
Just a remark: Why baseName (or a surrogate)  is not part of
BinaryNamingScheme since this interface concentrate most of Binary path
and naming?

**Comment by lacasseio** [comment]
My bad for not responding earlier. We will consider this when we tackle this issue.

**Comment by zosrothko** [comment]
@lacasseio Hi, is there any news on this issue?

**Comment by lacasseio** [comment]
Unfortunately, we don't have much news on this issue, @zosrothko. We are currently ramping up a native continuous native effort in Gradle and this issue will be visited once we get to the binary configurability.

**Comment by big-guy** [comment]
Issue moved to [gradle/gradle-native #500](https://github.com/gradle/gradle-native/issues/500) via [**ZenHub**](https://www.zenhub.com/)
