### ISSUE TITLE
Java System Properties should be propagated to test execution

### ISSUE THREAD

**Issue by Kerooker** [gradle/gradle#7773]
Bringing [Jira's issue 1185 (test - default to include the system properties)](https://issues.gradle.org/browse/GRADLE-1185) to Github.

### Expected Behavior

When executing a test via `./gradlew -Dx=y test`, the `x` property should be propagated to gradle's JVM children, as I'm trying to configure a property to the whole test suite.

### Current Behavior
Currently, -D properties are not found inside test execution, and a workaround must be made: One must add this to build.gradle:

```
test {
    systemProperties = System.properties
}
```
For system properties to correctly work inside tests.

### Context

With https://github.com/kotlintest/kotlintest/issues/474, I went digging for the issue, and found out that Gradle doesn't add its JVM properties to the test execution, leading to a misconfiguration when nothing is added to the build.gradle file.

As the original Jira issue, this seems to be a behavior that won't cause any issues, and will make project configuration easier.

Is there any other way to add system properties without configuring the test this way?

### Steps to Reproduce (for bugs)
Create a simple test that checks for a System property, such as
```
@Test
public void testProperty() {
assertEquals(System.getProperty("foo"), "bar");
}
```

And execute it trying to pass a system property:
```
./gradlew -Dfoo="bar" test
```

**Comment by oehme** [comment]
This is intentionally not the case - Your tests should be specific about what their environment is. If there is a property that you specifically would like to propagate, you can do so by configuring the Test task.
