### ISSUE TITLE
Should be able to transform a property to a new value using the original property

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#7774]
This code will cause a `StackOverflow`.
```kotlin
val nameProp = objects.property(String::class.java)
// Imagine this is a default set by a plugin
nameProp.set("a")
// Imagine the user wants to use the default value but with their own data apended
nameProp.set(nameProp.map { "$it-my-better-name"})

// StackOverflow here
val value = nameProp.get()
// Never reached
println(value) // Should print "a-my-better-name"
```

### Expected Behavior
The above code should print `"a-my-better-name"`.

### Current Behavior
Calling `nameProp.get()` causes a `StackOverflow` because of the cyclic mapping.

### Context

A use case would be a plugin specifies some sort of default value for a property which the user wants to use as a basis for the value they actually use.
For example, if some task is dynamically generated based upon the elements in a `NamedDomainObjectCollection` and the user wants to tweak the generated task to have a property that's content is dynamically generated, be slightly different.

### Related Issues
#7636

### Your Environment
```
------------------------------------------------------------
Gradle 4.10.1
------------------------------------------------------------

Build time:   2018-09-12 11:33:27 UTC
Revision:     76c9179ea9bddc32810f9125ad97c3315c544919

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by Resistance** [comment]
Instead of saying "the value of this property depends on the value of itself", update the property of the owning object instead:

```
// in SomeTask constructor inside a plugin
this.nameProp = objects.property(String::class.java)
this.nameProp.set("a")

// in your build configuration
someTask.nameProp = someTask.nameProp.map { "$it-my-better-name"}
```

The evaluation of properties could be improved by detecting such cyclic dependencies

**Comment by big-guy** [comment]
@Resistance Did you mean something like:

```
someTask.nameProp = someExtension.nameProp.map { "$it-my-better-name"}
```

`nameProp` needs to be final in `SomeTask`, so you can't overwrite the property.  Doing so will break the Property/Provider and make the value order of assignment dependent.

Imagine:
```
class SomeTask extends DefaultTask {
    public Provider<String> nameProp

    SomeTask() {
       this.nameProp = objects.property(String::class.java)
       this.nameProp.set("a")
    }
}

// in your build configuration
anotherTask.derivedProp = someTask.nameProp.map { "$it-derived" }
someTask.nameProp = someTask.nameProp.map { "$it-my-better-name"}
yetAnotherTask.derivedProp = someTask.nameProp.map { "$it-derived" }

// later on
someTask.nameProp.get() == "a-my-better-name" // expected
anotherTask.derivedProp.get() == "a-derived" // unexpected (!)
yetAnotherTask.derivedProp.get() == "a-my-better-name-derived" // expected
```

**Comment by adammurdoch** [comment]
We'll probably do something like option 2, to add a method that allows a transform of some kind to be applied to the property's value. The method would run the transform on every call to `get()`, passing the transform the current value (if present) and then using whatever it returns as the result.

**Comment by grv87** [comment]
What about lazy configuration of objects?
If I have a `Property<SomeObject> someProperty`, I would like to configure it lazily with `someProperty.configure { ... }`.
Lazy task configuration is awesome, it would be good if it worked for other objects.
Is it covered by this issue, or should I open another one?

**Comment by big-guy** [comment]
@grv87 I don't think there's a particular issue for configuration of a mutable object. Please open an issue
