### ISSUE TITLE
3.2-rc-* Build Fails With Crashed Daemon

### ISSUE THREAD

**Issue by jpe42** [gradle/gradle#778]
The build for my project [freegeoip-java-client](https://github.com/jamespedwards42/freegeoip-java-client) started failing as of the 3.2 release candidates.

### Expected Behavior
`./gradlew build` should continue to work as with Gradle version 3.1.  Here is a [working build scan using 3.1](https://scans.gradle.com/s/2fnh6cgfkpl3u), from `./gradlew build -Dscan`.

### Current Behavior
The build for the subproject `freegeoip-java-dslplatform-data` fails with a crashed Gradle daemon and JVM.  The only upstream local subproject `freegeoip-java-api` is still working.  The major difference to me is that the compileOnly dependency 'com.dslplatform:dsl-json-processor:+' for the failing subproject requires the [Mono JIT compiler](http://www.mono-project.com/).

Debug Logs on Pastebin:
[./gradlew :freegeoip-java-dslplatform-data:build --debug --stacktrace](http://pastebin.com/crEHESgH)

JRE 8.0_112-b15 crash logs:
[hs_err_pid29.log](http://pastebin.com/Uz4NzxKf)

JRE 9-ea+142 crash logs:
[hs_err_pid24254.log](http://pastebin.com/dgEQGm2Z)

### Context
I'm just being pro-active with this issue, I can continue to use 3.1 with no issues.

### Steps to Reproduce

1. Clone the Github project [github.com/jamespedwards42/freegeoip-java-client](https://github.com/jamespedwards42/freegeoip-java-client) 

2. Run `./gradlew :freegeoip-java-dslplatform-data:build` with any 3.2 release candidate.  Or, if you don't want to have to install Mono, I have provided an Alpine Docker image that can provide a proper build environment:

```sh
user ~/git/freegeoip-java-client > docker run --rm -it \
  -v $GRADLE_USER_HOME:/root/.gradle \
  -v $(pwd):/usr/local/src/freegeoip/ \
  jamespedwards42/alpine-jdk-mono:latest sh
root /usr/local/src > cd freegeoip/
root /usr/local/src/freegeoip > ./gradlew :freegeoip-java-dslplatform-data:build
Starting a Gradle Daemon
...
```

##### Env 1:
* MacOS Sierra 
* JDK 9-ea build 142
* Mono JIT compiler version 4.6.1
* Gradle 3.2-rc-(1|2)

##### Env 2:
* Docker Alpine Linux 
* JDK 8 update 112 build 15
* Mono JIT compiler version 4.6.1.5-r0
* Gradle 3.2-rc-(1|2)

**Comment by bmuschko** [comment]
@jamespedwards42 Thanks for reporting. I am currently looking into the issue and let you know.

**Comment by bmuschko** [comment]
I can reproduce the issue. It has been captured via [GRADLE-3578](https://issues.gradle.org/browse/GRADLE-3578).

**Comment by bmuschko** [comment]
@jamespedwards42 A workaround for this issue is to fork the Java compilation process like so:

```compileJava {
    options.fork = true
}```

Would that be a viable option for you while we are looking for a more stable, long-term solution?

**Comment by jamespedwards42** [comment]
@bmuschko Yes, that will work, thank you!...  I'm trying to stay up with the latest so that I will be ready for jigsaw module support.  Thanks again for the support, huge Gradle fan here.

**Comment by bmuschko** [comment]
@jamespedwards42 Thanks for the great feedback! I also [reported the issue to the Jansi project](https://github.com/fusesource/jansi/issues/66).

**Comment by eriwen** [comment]
@bmuschko What is the follow up action for us here? We may consider another card for such follow-up, as this is no longer blocking 3.2.

**Comment by bmuschko** [comment]
@eriwen Let's reword the issue and line it up for 3.3. I'd just keep the original card.

**Comment by eriwen** [comment]
@bmuschko Can you follow up on this and provide an update, please?

**Comment by eriwen** [comment]
Thanks for the update. I think you can unassign this from yourself

**Comment by Hubbitus** [comment]
I'm also have reproducible java crash on my project on gradle >= 2.14.

It is use Sencha for build and it import ant tasks which bundle `jansi` version 1.9
Java top crash stack is:
```
Stack: [0x00007f5e5d63c000,0x00007f5e5d73d000],  sp=0x00007f5e5d737190,  free space=1004k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x68523f]
C  [libjansi.so+0xf38]  Java_org_fusesource_jansi_internal_CLibrary_init+0x108
j  org.fusesource.jansi.internal.CLibrary.<clinit>()V+21
```

Details you may found in RedHat bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1408857 where I report it first.

But really it looks like gradle issue instead of java itself.

Gradle bundles jansi-native which seams the root cause:
```
$ ls -l /home/pasha/.gradle/native/jansi/1.14/linux64
-rwxr-xr-x 1 pasha pasha 48340 Mar  1 16:17 libjansi-64-1.9.so
-rw-rw-r-- 1 pasha pasha 54754 Mar  1 16:19 libjansi.so
```
It will be downloaded automatically, so I can't just make it not writable, gradle complain:
`Could not create Jansi native library '/home/pasha/.gradle/native/jansi/1.14/linux64/libjansi.so'`, ok, but for experiment I just delete it after download:
```
watch -n0.1 rm -v /home/pasha/.gradle/native/jansi/1.14/linux64/libjansi*.so
```
It prevent usage it.
And build now fine!!

Continue experimenting I found nicer workaround - just include and force class load of newer `jansi` version in build script:
```gradle
buildscript {
    dependencies {
        classpath group: 'org.fusesource.jansi', name: 'jansi', version: '1.14'
    }
}
org.fusesource.jansi.AnsiConsole.out.print('init workaround') // Just import org.fusesource.jansi.AnsiConsole; is not enough!
```
End it seams work without deleting anything…

It seams as versions incompatibility gradle native so with possible other jansi versions!

I have test it on `gradle` version 4.3. If you wishes I could open separate bug.

**Comment by oehme** [comment]
@bmuschko is this issue still relevant?

**Comment by bmuschko** [comment]
@oehme I am pretty sure this is still an issue. It's originating from Jansi though (see issue above).

**Comment by Hubbitus** [comment]
Does someone will deal with that crash in `gradle`?

**Comment by Hubbitus** [comment]
With `gradle` 5.2.1 situation became even more worse - daemon crashed each time on start. And workaround stop working! It looks like `jansi` updated to version 1.17.

Additionally to it it looks like I need do also:
`ln -sb /dev/null /home/pasha/.gradle/native/jansi/1.17.1/linux64/libjansi.so` to get minimum working gradle on Linux box!

**Comment by Hubbitus** [comment]
Is it possible disable `jansi native` use in `gradle`?

**Comment by Hubbitus** [comment]
It looks like it works by `_JAVA_OPTIONS='-Dorg.gradle.native=false' ./gradlew --no-daemon <task>` or `./gradlew -Dorg.gradle.native=false <task>` but placing `org.gradle.native=false` into `gradle.properties` does not help.

**Comment by alexvas** [comment]
Just in case anyone else encounter the problem (as me with Gradle 7.3.3):
using strict version of Jansi library (1.18 -- same as in Gradle in my case), here is the fix:
```
        api("org.fusesource.jansi:jansi") {
            // old version here otherwise there will be a core dump
            version {
                strictly("1.18")
            }
        }
```
