### ISSUE TITLE
Gradle 5.0-rc-4 exponential backoff makes IDE import very slow

### ISSUE THREAD

**Issue by btilbrook-nextfaze** [gradle/gradle#7787]
### Expected Behavior

Gradle `5.0-rc-4` should successfully sync in Android Studio `3.2.1`.

### Current Behavior

Gradle sync hangs at the following stage:

```
Build model 'org.jetbrains.plugins.gradle.model.BuildScriptClasspathModel' for root project 'my-android-project'
```

### Context

This project is using dependency locking.

### Steps to Reproduce (for bugs)

1. Open the attached project in Android Studio `3.2.1`
1. Gradle sync
1. Cancel with the cross button and repeat if necessary

Sample project:
[Gradle Hang.zip](https://github.com/gradle/gradle/files/2601900/Gradle.Hang.zip)

### Your Environment

Android Gradle Plugin `3.2.1`
Android Studio `3.2.1`
Build `#AI-181.5540.7.32.5056338`, built on October 9, 2018
JRE: `1.8.0_152-release-1136-b06` `x86_64`
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS `10.13.6`
Kotlin `1.3.10`

 Build scan URL: https://scans.gradle.com/s/sxwbk763vyulg

Daemon thread dump: 
[gradle.threaddump.txt](https://github.com/gradle/gradle/files/2605978/gradle.threaddump.txt)

**Comment by oehme** [comment]
Please provide a thread dump (using `jstack`) of the Gradle daemon when the hang occurs.

**Comment by jjohannes** [comment]
I can confirm that this is very slow with the 5.0 RCs. I don't think it's hanging but it is very slow (~10 minutes). It looks as if there is some (unexpected?) slow network access going on.

Works fine with `4.10.2`.

**Comment by big-guy** [comment]
@btilbrook-nextfaze can you confirm that this happens with every sync or just the first one?  The "Build model ..." message is a new message in 5.0, but what's happening under the covers is not.  Previously, this time would have been rolled up in the overall sync time and wouldn't be attributed to any particular action.

**Comment by eskatos** [comment]
I can reproduce the issue with Studio 3.2. It's not hanging but loosing time on retrying jcenter with a backoff.

![image](https://user-images.githubusercontent.com/132773/48861581-34cca580-edc4-11e8-8693-91544b56c064.png)


What is troubling though is that the build declares the `google()` repo first, then `jcenter()`, but it seems the sync process is trying to lookup things from `jcenter()` that are present in `google()`.

Also see https://discuss.gradle.org/t/gradle-5-0-rc1-problem-with-artifact-resolution-in-intellij-import/29445 for an internal workaround.

FWIW, Studio 3.3 or 3.4 don't have the issue and the attached project syncs in a snap.

**Comment by marcphilipp** [comment]
If it works with Studio 3.3 and 3.4 I wouldn't consider it a blocker for 5.0.

@eskatos @oehme WDYT?

**Comment by ljacomet** [comment]
So the root cause of the slowness is an internal exception triggering the HTTP retries:
```
Caused by: java.lang.AbstractMethodError
    at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultCachePolicy.mustRefreshModule(DefaultCachePolicy.java:205)
    at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultCachePolicy.mustRefreshModule(DefaultCachePolicy.java:192)
```
We are investigating the effect of no longer retrying when seeing that error. However a possible outcome might be we have to declared Android Studio 3.2.1 incompatible with Gradle 5.0.

**Comment by ljacomet** [comment]
And that error is caused by an added method on `ModuleComponentIdentifier`, which was already present in Gradle 4.10. So it really the combination of both causing the problem.

**Comment by jjohannes** [comment]
The error is caused by an incompatibility between Android Studio 3.2 and Gradle 5.0. 

You have to upgrade to Android Studio 3.3 to work with Gradle 5.0.

The change we are doing for RC5 is #7813. Then the error is no longer hidden. Which means that the Sync in AS 3.2 will no longer "hang", but fail.

Thanks for reporting this @btilbrook-nextfaze!

**Comment by btilbrook-nextfaze** [comment]
Thanks for resolving it. I suspected this might ultimately be the outcome.

**Comment by gi-utkarsh** [comment]
I had the same problem. Was Looking for some forum on this issue It take 10 minutes when i create a new activity or a fragment. Can someone please elaborate on what causes this issue.

**Comment by diego-lipinski-de-castro** [comment]
There is no AndroidStudio 3.3 (for mac atleast) and Gradle 5.0 is not building, throws this error

**Comment by jjohannes** [comment]
@diego-lipinski-de-castro Android Studio 3.3 is currently in RC phase. You can get it here: https://developer.android.com/studio/preview/
