### ISSUE TITLE
How to config avoid fetch sources.jar and javadoc.jar?

### ISSUE THREAD

**Issue by gunC** [gradle/gradle#7789]
How to config avoid fetch sources.jar and javadoc.jar?
I try the following config , but not work in AndroidStudio/Idea

```
idea {
        module {
            downloadJavadoc = false
            downloadSources = false
        }
    }
```

**Comment by oehme** [comment]
If IDEA/Studio ignore these settings, please report that on the JetBrains/Google issue trackers.
