### ISSUE TITLE
Generated scripts in Gradle 3.2 spawn child processes

### ISSUE THREAD

**Issue by mark-vieira** [gradle/gradle#779]
It looks like we have a regression with regards to the following change: https://github.com/gradle/gradle/pull/621

Specifically, the change to using `eval` instead of `exec` in these scripts. These two have very different behavior, specifically, `eval` creates a child process whereas `exec` does not. This ends up breaking folks that use distributions created by 'application' plugin as an entrypoint in a Docker container. Since the entrypoint process and the `java` process have unique PIDs, Docker ends up sending stop/kill signals to the shell script PID instead of the `java` process. The end result is that the java process does not get the SIGTERM signal when calling `docker stop` which would allow the application to gracefully shutdown.

This is a breaking change and we should either revert, or refactor the script to use `exec` again in some kind of /bin/sh compatible way.

**Comment by jjohannes** [comment]
I have pushed a fix for this. 

 `eval` was actually used before, but only to interpret (de-escape) the JVM args which the script is reading from environment variables. With the PR, the eval was "pulled down" to do everything. The fix now restores the original behaviour of using `exec` to actually call `java`.

https://github.com/gradle/gradle/commit/2a2a575922efef04fb6fbad178272b3073e8c84d and https://github.com/gradle/gradle/commit/8adf7d4367b67dca822e3f3e2dbe6e87129ab815

Compared to what we had in 3.1, we change the way how all the arguments for `java` are assembled.


In 3.1 we did:
```
  # Split up the JVM_OPTS And GRADLE_OPTS values into an array, following the shell quoting and substitution rules
  function splitJvmOpts() {
      JVM_OPTS=("$@")
  }
  eval splitJvmOpts $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS
  JVM_OPTS[${#JVM_OPTS[*]}]="-Dorg.gradle.appname=$APP_BASE_NAME"

  exec "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
```
Now we do:
```
  # Escape application args
  for s in "${@}" ; do
      s=\"$s\"
      APP_ARGS=$APP_ARGS" "$s
  done

  # Collect all arguments for the java command, following the shell quoting and substitution rules
  eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

  exec "$JAVACMD" "$@"
```

This avoids the usage of a second array (JVM_OPTS) which is not supported by minimal `sh` implementations like dash. Instead, we bring the application args on the same level as the three JVM option variables (a single String which contains all options escaped - APP_ARGS). Then we use `eval` to de-escape it into the $@ array. And then call Java with the arguments from the array.

**Comment by jjohannes** [comment]
I added an integration test that reproduces this issue: https://github.com/gradle/gradle/commit/81ffaa4d81d3dfbb5e84dabf496f8293fd9cdbe9

**Comment by jjohannes** [comment]
@mark-vieira would you mind reviewing this as you seem to have most insights into the problem?

Review: https://code-review.gradle.org/cru/REVIEW-6359

**Comment by mark-vieira** [comment]
LGTM 👍

**Comment by jjohannes** [comment]
For inclusion in changelog: https://issues.gradle.org/browse/GRADLE-3579

**Comment by eriwen** [comment]
Closing as delivered
