### ISSUE TITLE
Unable to remove annotation processor warnings from integration tests sourceset

### ISSUE THREAD

**Issue by Mayday90** [gradle/gradle#7791]
I am using lombok in my gradle project. I have simplified the problem into a very simple project example attached. By following official docs, I am creating a separate source set for integration tests. I am including into integration tests the classpath of common tests, in order to be able to reuse their utils (com.company.utils.Utils in the attached project). I am getting the warning about annotation processors due to this integration tests sourceset, and I am scared I won't be able to move to gradle 5.0 in the future

### Expected Behavior
> gradlew clean build --warning-mode all

> BUILD SUCCESSFUL in 2s
> 7 actionable tasks: 7 executed

### Current Behavior
> gradlew clean build --warning-mode all

> Task :compileIntegTestJava
> The following annotation processors were detected on the compile classpath: 'lombok.launch.AnnotationProcessorHider$AnnotationProcessor' and 'lombok.launch.AnnotationProcessorHider$ClaimingProcessor'. Detecting annotation processors on the compile classpath is deprecated and Gradle 5.0 will ignore them. Please add them to the annotation processor path instead. If you did not intend to use annotation processors, you can use the '-proc:none' compiler argument to ignore them.
> BUILD SUCCESSFUL in 2s

### Context

I think this is the relevant part:

```
 sourceSets {
    integTest {
        java.srcDir file('src/integTest/java')
        resources.srcDir file('src/integTest/resources')
        compileClasspath += sourceSets.main.output + sourceSets.test.output+ configurations.compileClasspath + configurations.testRuntimeClasspath
        runtimeClasspath += output + compileClasspath
    }
}
```
I am scared I can not migrate in the future to new gradle 5.0

### Steps to Reproduce (for bugs)
> gradlew clean build --warning-mode all

### Your Environment
* gradlewrapper 4.8
* jdk 10.0.2

Download: [integration-tests.zip](https://github.com/gradle/gradle/files/2603511/integration-tests.zip)

**Comment by oehme** [comment]
If you want to use annotation processors, put them into the processor path of your sourceSet, i.e. `integTestAnnotationProcessor`

**Comment by Mayday90** [comment]
@oehme Would you mind specifying in what closure should I write that exactly, and where should it target? I'm unable to make it work

I mean, I understand the compileClasspath += sourceSets.main.output... etc, but

integTestAnnotationProcessor += <?>

**Comment by Mayday90** [comment]
I am using lombok annotations (for example `@SLF4J`) for my source code. I do also want to use those annotations in tests, so I do intend to use those annotation processing, but taking it from source code.

Considering your suggestion, this worked for me, is it correct?

`annotationProcessorPath += sourceSets.main.annotationProcessorPath`

**Comment by oehme** [comment]
That works.
