### ISSUE TITLE
Consider making builds generated by :init use same versions as embedded for Groovy and Kotlin dependencies

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#7797]
for consistency.

### Expected Behavior

```
gradle init --type=groovy-application
```
would generate a build that depends on Groovy using the same version as the embedded Groovy version.

In the same way, 
```
gradle init --type=kotlin-application
```
would generate a build that depends on Kotlin using the same version as the embedded Kotlin version.

### Current Behavior

The Groovy and Kotlin versions used by `:init` are set to "latest available on release branching according to a range" configured in

https://github.com/gradle/gradle/blob/0fa0d95ff7b8510349669c4ecc94572ed16bce32/subprojects/build-init/build-init.gradle.kts#L62-L72

which might be different than the embedded versions.

### Context
#7793, #7795 and #7796

**Comment by wolfs** [comment]
What is the reason that we want to use the embedded versions as default for building an application with Groovy/Kotlin? I don't see why someone should bind the version of Groovy/Kotlin in their project to whatever Gradle uses currently.

**Comment by bamboo** [comment]
In the Kotlin case, the currently embedded version happens to be the latest stable Kotlin version so it makes sense.

**Comment by eskatos** [comment]
@wolfs the version we use in `:init` generated builds isn't the single supported version. One can change the version in their build according to any compatibility issues. This issue isn't suggesting to change that but to change what particular version `:init` uses when generating the builds and use the same version as embedded Groovy/Kotlin, for consistency and least astonishment. I think it would also makes things simpler for us and prevent situations like #7793.

**Comment by adammurdoch** [comment]
I don't think we should recommend people use this pattern for anything that isn't intended to run on Gradle itself (plugins and build logic libraries). If the software is not intended to run on Gradle, then by using the local Kotlin or Groovy version people are unnecessarily coupling the version of the language they use in production with the version of the build tool that they use. This is not a good situation for people to be in.

I'm going to close this.
