### ISSUE TITLE
Error in generation of Intellij modules when using shared code and resources directory

### ISSUE THREAD

**Issue by smarklund** [gradle/gradle#7799]
When generating Idea modules with the **idea** task as of Gradle 4.7 and onwards
the generation is incorrect when the source and resource folders share directory.

We have a lot of older repositories where the source layout is like:
  * java - containing production code and resources
  * test - containing test code and resources

To set this up source sets are configured like:

```
project.sourceSets.main.java.srcDir 'java'
project.sourceSets.main.resources.srcDir 'java'

project.sourceSets.test.java.srcDir 'test'
project.sourceSets.test.resources.srcDir 'test'
```

As of Gradle 4.7 and onwards Gradle is no longer generating working Idea modules when code share folder with resources.

### Expected Behavior
If the source and resources share folder the generated sources folder should be flagged as a source folder. If test code is sharing test resources it should be flagged like test sources.

### Current Behavior

* As of Gradle 4.7 and up to 4.10.2 the shared folder is flagged as a resources folder causing the code to be handled like resources and copied rather than compiled.
* Gradle 5.0 completely skips generating folders in the iml file.

### Steps to Reproduce

I have made a test repository so you easily can replicate the issue with different Gradle versions.

    https://github.com/smarklund/gradle-idea-issue.git

Have the project opened in Intellij and see the different properties or lack thereof on the java and test folders.

### Conclusion

Generated iml files are not working with Gradle 4.7 and onwards if source directory share directory with resources directory.

It would be great to know whether you consider this an issue. I can manipulate the iml files to get correct sourceFolders in the iml files but it does look like an issue to me and I wager we are not the only ones out there with above organization of code.

Thanks!
Stefan

**Comment by smarklund** [comment]
Hello,

As of build "5.1-20181126000019+0000" this issue remains. If source and resource directory share directory no folder at all gets written in generated idea files.

```
./gradlew wrapper --gradle-version="5.1-20181126000019+0000"
./gradlew cleanIdea idea

cat gradle-idea-issue.iml
<?xml version="1.0" encoding="UTF-8"?>
<module relativePaths="true" type="JAVA_MODULE" version="4">
  <component name="NewModuleRootManager" inherit-compiler-output="true">
    <exclude-output/>
    <orderEntry type="inheritedJdk"/>
    <content url="file://$MODULE_DIR$/">
      <excludeFolder url="file://$MODULE_DIR$/.gradle"/>
      <excludeFolder url="file://$MODULE_DIR$/build"/>
    </content>
    <orderEntry type="sourceFolder" forTests="false"/>
  </component>
  <component name="ModuleRootManager"/>
</module>
```

No 'java' or 'test' directory in the generated Idea module xml. It is not usable.

Do you need any more information? I feel like I have done a pretty through job reporting the issue including adding a repository for easy issue reproduction.

Would you agree this is an issue?

Thank you,
Stefan

**Comment by jjohannes** [comment]
Using the native import in IDEA is now the recommended way. The `cleanIdea` / `idea` tasks should not be used directly anymore.

Please open a new issue if there is still a problem.
