### ISSUE TITLE
org.gradle.project.foo in gradle.properties does not work the way as the document says

### ISSUE THREAD

**Issue by dapengzhang0** [gradle/gradle#7805]
### Expected Behavior

Following the [official document](https://docs.gradle.org/4.9/userguide/build_environment.html#sec:project_properties): **Example: Setting a project property via gradle.properties**

`project.properties['foo']` should be `'bar'`

### Current Behavior

`project.properties['foo']` is `null`; however, `project.properties['org.gradle.project.foo']` is `bar`.

### Context

Either the [official document](https://docs.gradle.org/4.9/userguide/build_environment.html#sec:project_properties) **Example: Setting a project property via gradle.properties**
 is wrong or there is a bug.

### Steps to Reproduce (for bugs)

**gradle.properties**
```
org.gradle.project.foo=bar
```

**build.gradle**
```gradle
println project.properties['foo']
if (project.hasProperty('foo')) {
    println 'Has property foo'
    println project.foo
} else {
    println 'Does not have property foo'
}

println project.properties['org.gradle.project.foo']
if (project.hasProperty('org.gradle.project.foo')) {
    println 'Has property org.gradle.project.foo'
    println project.'org.gradle.project.foo'
}
```

output of gradle build:
```
null
Does not have property foo
bar
Has property org.gradle.project.foo
bar

```

**Comment by marcphilipp** [comment]
That's a bug in the documentation, I'm afraid. The `org.gradle.project.` prefix is used to set a project property using a system property. To set a project property from `gradle.properties`, you can simply write `foo=bar`.

The documentation is already fixed and will be in 5.0:
https://docs.gradle.org/release-candidate/userguide/build_environment.html#sec:project_properties
