### ISSUE TITLE
Add note to upgrade guide to not try upgrading to 5.0 and switching to the Kotlin DSL at the same time.

### ISSUE THREAD

**Issue by jlstrater** [gradle/gradle#7815]
### Context

Several users have reported issues with trying to upgrade to Gradle 5.0 and switching to the Kotlin DSL at the same time. Doing both at the same time, makes it difficult to determine which step is causing the problem.

Therefore, we should remind users in the [4.x to 5.0 upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_4.html) that they should upgrade their Groovy builds to 5.0 before trying to switch to the Kotlin DSL.

**Comment by pvliss** [comment]
Hello @jlstrater. I would like to help with this one if you don't mind

**Comment by jlstrater** [comment]
That would be wonderful @pvliss ! Do you have an idea for where you think the note should go?

**Comment by pvliss** [comment]
Well I initially thought to use a warning at the top but then show that there is already a heading `Before yous start migrating` at the doc [file](https://github.com/gradle-guides/migrating-build-logic-from-groovy-to-kotlin/edit/master/contents/index.adoc) and the very first item reads: `Using the latest versions of Gradle, applied plugins, and your IDE should be your first move.`

So I was thinking of simply appending the following: `Avoid upgrading Gradle and migrating to Koltin at the same time to ease troubleshooting in case of potential issues.` and possibly making it stronger to make it harder to miss.

What do you think?

**Comment by jlstrater** [comment]
I'm glad I asked. This issue is actually about modifiying the [4.X to 5.0 upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_4.html). On github, you'll find it [here](https://github.com/gradle/gradle/edit/master/subprojects/docs/src/docs/userguide/upgrading_version_4.adoc).

**Comment by jlstrater** [comment]
Hmm. I'm not sure it's quite the same level as the breaking Android change. It's more of a recommendation. Perhaps it would work at the end of point 1 in the For All Users section? 

👍on the text though. Remember to use the phrase `Kotlin DSL` to avoid confusion with other Kotlin usages and add a transition between sentences. Go ahead and submit a PR when you're ready and someone will review it when they get a chance.

**Comment by pvliss** [comment]
Thanks @jlstrater for all the feedback. I have now submitted a PR following your recommendations. I guess we could also add it as a separate second point within the `For All Users` section but lets see what the reviewer will have to say as well.

**Comment by pvliss** [comment]
@jlstrater I think this can be closed as it has already been merged and part of the 5.2 release.

**Comment by jlstrater** [comment]
Oh yes! Thank you for the reminder. I'm used to tagging my PRs so they close the issue automatically. ☺️
