### ISSUE TITLE
Can not get the information added with configure closure in  whenObjectAdded's callback

### ISSUE THREAD

**Issue by fairysword** [gradle/gradle#7818]
### Expected Behavior

I have some productFlavors setting
```
productFlavors {
    free {
        dimension "mode"
    }
    paid {
        dimension "mode"
    }
}
```
when I call `whenObjectAdded`  with my custom action before productFlavors called , such as
```
productFlavors.whenObjectAdded { flavor ->
    // I want to get the information added with this flavor's configure closure ,  such as the dimension
}
```
### Current Behavior

I can not get the dimension value, because when my custom action called, the closure 
```
{
    dimension "mode"
}
```
with the flavor is not called.
The reason is in the source code of `AbstractNamedDomainObjectContainer`
```
public T create(String name, Action<? super T> configureAction) throws InvalidUserDataException {
    assertCanAdd(name);
    T object = doCreate(name);
    add(object);
    configureAction.execute(object);
    return object;
}
```
### Context

I want to get some information added with the flavor's configure closure,  then do something else
### Your Environment

gradle version: 4.4
os: macOS 10.14

**Comment by fairysword** [comment]
@marcphilipp AfterEvaluate is to late for me, can you add another method for this?

**Comment by fairysword** [comment]
I use MOP to replace the productFlavors method body, which can solve my problem
```
def androidExtension = project.extensions.findByName('android')
def methodProductFlavors = androidExtension.metaClass.getMetaMethod('productFlavors', Closure.class)
androidExtension.metaClass.productFlavors = { Closure action ->
    methodProductFlavors.invoke(delegate, action)
    // get information of flavors
}
```

**Comment by marcphilipp** [comment]
I'm sure this has been discussed before.

@oehme Do you have any pointers?

**Comment by oehme** [comment]
This is what the lazy configuration API (Provider/Property) is supposed to help with - Making deferred computations based on other values. The Android plugin hasn't adopted it yet as far as I know (just like most Gradle core plugins haven't yet). Until that changes, there is no good way to solve this issue. An `afterDefaultsConfigured` method on our domain object container could help, but it would introduce the new concept of the initial closure being the "defaults". Right now the initial closure has no meaning at all, it's just one of many configure closures :) It would probably match people's intuition, the downside being "yet another way of doing things".
