### ISSUE TITLE
Always re-run tests when executed from IDE

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#7822]
When delegation to Gradle is enabled in IntelliJ, Gradle will not re-execute successful tests without a change to the source code. This is because Gradle will recognize the results to be up-to-date. However, the user's goal in running tests from an IDE is not to produce the XML report, but to see the code run once again. This could be even more counter-intuitive to the user when after a code change Gradle decides that the code is exactly as it was before, and just loads a cached result instead of re-executing the tests.

It should be possible for the IDE to force the re-execution of the tests it has asked to execute instead. One option is to introduce a `--rerun-tests` option for the `Test` task that could be automatically added by IDEs.

**Comment by alexey-tsvetkov** [comment]
BTW currently Intellij executes `:subproject:cleanTest :subproject:test`, which re-runs tests when the build cache is not enabled.
