### ISSUE TITLE
Add the 'org.gradle.usage' attribute to the buildscript's classpath configuration

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#7826]
### Expected Behavior
A `buildscript { dependencies { classpath '...' } }` dependency is resolved in a variant-aware way with a usage value appropriate for Java (`org.gradle.usage='java-runtime'`).

### Current Behavior
The attributes of the buildscript's classpath configuration are empty.

### Context
This prevents the buildscript classpath from resolving a dependency on a module with multiple variants where only one is suitable for JVM, like in Kotlin multiplatform projects.

### Steps to Reproduce (for bugs)
Checkout `https://github.com/JetBrains/rd` commit `85eeca2fe`, go to `rd-benchmark` where the root project is included as a composite build, resolve the buildscript's classpath configuration that depends on two modules with JVM and non-JVM variants alike. It resolves to non-JVM artifacts (according to the disambiguation rules for the case when no specific usage is requested) since it has no proper `org.gradle.Usage` attribute. 

Those artifacts are 
`rd-core-metadata-SNAPSHOT.jar` and `rd-framework-metadata-SNAPSHOT.jar `. 

Instead, the buildscript should get the JVM artifacts, `rd-core-jvm-SNAPSHOT.jar` and `rd-framework-jvm-SNAPSHOT.jar`.

The workaround is to manually set the usage attribute as follows:
```
buildscript {
    configurations.classpath.attributes.attribute(
        Usage.USAGE_ATTRIBUTE, 
        objects.named(Usage, 'java-runtime')
    )
    // ...
}
```

**Comment by ljacomet** [comment]
Thanks for the report, work has started on this and should make it in Gradle 5.2
