### ISSUE TITLE
Make it easier to understand how service scopes are accessible from each other

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#7833]
When working with services, one often has to answer one of these questions, that can be hard to do so:

* what scope(s) is a service type `X` available in?
* what services are visible from scope `A`?
* what is the relationship of scope `A` and `B`?
* what service scopes are there?

Here's a bunch of ideas to make things easier to manage:

* make sure every `ServiceRegistry` has a relevant `displayName` to help debugging
* make service discovery declarative somehow
    * maybe instead of using imperative code, we could discover services via some sort of SPI  (we already do this for plugin projects)?
    * we should check if we could use `@javax.inject.Scope`
    * use the type system to somehow model the hierarchy of scopes
        * having a type per scope would allow scopes to be easily documented (note that we already some have documentation for some scopes on the `PluginServiceRegistry` methods)
* generate an HTML report during the build listing each service and its scopes—such a report file could be published as part of Gradle releases for internal documentation
* replace `create...()` and `decorate...()` method name convention with explicit `@Provides` annotations (a'la Guice)
    * this lets us ignore "unused" warnings in IntelliJ

**Comment by lptr** [comment]
This is explicitly not about replacing `ServiceRegistry` with something like Guice, though we could explore that option as well as a separate endeavor.

**Comment by big-guy** [comment]
+1 on something that would show us the current state of things (e.g., a HTML report)

`PluginServiceRegistry` is sort of the only documentation on the order/hierarchy of the services.  It provides some information about what the different levels mean, but we could also do with some sort of documentation on any other design decisions that need to be considered for a service at each of the levels.

e.g., it would be surprising for a global scope that share expects everything to be keyed for a single project (or build).  

It would be wasteful/counter productive to have a cache that's only project scoped for something that's reused across a build or build tree or multiple builds.

**Comment by lptr** [comment]
I think this would be worth keeping open. /cc @adammurdoch
