### ISSUE TITLE
Project buildscript ClassLoader should load classes from buildscript classpath first and only then from gradle libs dir

### ISSUE THREAD

**Issue by remal** [gradle/gradle#7837]
There are a lot of libraries bundled with Gradle. For example: asm, guava, kotlin-reflect, etc...

We don't have a possibility to override versions of such libs, as project ClassLoader loads classes from parent first and only then from classpath of buildscript block.

It prevents from using a specific version of Kotlin runtime. Or from using a fixed version of a lib without upgrading Gradle.

And the worst thing is that this behavior isn't obvious. If I develop a plugin, the plugin compiles correctly, it can pass all the tests... But when a user tries to apply plugin with another Gradle version, it will fail with some classpath error that's very hard to debug.

For now I can see only one solution: to shade all plugin dependencies to avoid any classpath conflicts with bundled libraries. But iа I use a library with a bug, nobody can't change it's version just by using a direct classpath dependency...

**Comment by oehme** [comment]
Only the Gradle API is part of the buildscript classpath. ASM, Guava etc. are internals and are not leaked into plugins.

The Kotlin version is part of the API and is thus fixed. This is not something we can change, as it needs to be the same for all plugins, so they can communicate correctly with each other and with the Kotlin DSL.
