### ISSUE TITLE
Gradle 5 build failed

### ISSUE THREAD

**Issue by RexProg** [gradle/gradle#7839]
when i want to upgrade gradle from 5-rc5 to 5 project didn't sync

more detail about error :
![image](https://user-images.githubusercontent.com/23130739/49085156-9a0e1400-f266-11e8-8fb7-2e41873a49bd.png)
https://gist.github.com/RexProg/28c93af163540129302ad89099249e1b

**Comment by melix** [comment]
As stated in the [upgrade guide linked to the release notes](https://docs.gradle.org/current/userguide/upgrading_version_4.html), Gradle 5 is only compatible with Android Studio 3.4+. The error you are seeing was already present in 5-rc5, but unfortunately silently ignored (and causing slow syncs). Gradle 5.0 final makes it clear it's not compatible.
