### ISSUE TITLE
Different "dependencies" task output in Gradle 5.0

### ISSUE THREAD

**Issue by GFriedrich** [gradle/gradle#7845]
When using the "dependencies" task optional transitive dependencies are not listed anylonger as it was in Gradle 4.X

### Expected Behavior
I would expect the optional transitive dependencies to be listed if they are resolved by other dependencies.
As a bonus point I would expect they are marked in some way so it's clear that those are optional dependencies.

### Current Behavior
The optional transitive dependencies are not listed below their parent dependencies even though they are resolved.

### Context
It makes it hard to understand which dependencies are used by other dependencies.

### Steps to Reproduce (for bugs)
Include dependencies with the following dependencies block ("spring-aop" is an optional transitive dependency of "spring-tx"):
```
dependencies {
  implementation("org.springframework", "spring-tx", "4.3.20.RELEASE")
  implementation("org.springframework", "spring-aop", "4.3.20.RELEASE")
}
```
For versions before 5.0 the dependency tree of the compileClasspath configuration looks like this:
```
+--- org.springframework:spring-tx:4.3.20.RELEASE
|    +--- org.springframework:spring-aop:4.3.20.RELEASE
|    |    +--- org.springframework:spring-beans:4.3.20.RELEASE
|    |    |    \--- org.springframework:spring-core:4.3.20.RELEASE
|    |    |         \--- commons-logging:commons-logging:1.2
|    |    \--- org.springframework:spring-core:4.3.20.RELEASE (*)
|    +--- org.springframework:spring-beans:4.3.20.RELEASE (*)
|    \--- org.springframework:spring-core:4.3.20.RELEASE (*)
\--- org.springframework:spring-aop:4.3.20.RELEASE (*)
```
From Gradle 5.0 on the tree looks like this:
```
+--- org.springframework:spring-tx:4.3.20.RELEASE
|    +--- org.springframework:spring-beans:4.3.20.RELEASE
|    |    \--- org.springframework:spring-core:4.3.20.RELEASE
|    |         \--- commons-logging:commons-logging:1.2
|    \--- org.springframework:spring-core:4.3.20.RELEASE (*)
\--- org.springframework:spring-aop:4.3.20.RELEASE
     +--- org.springframework:spring-beans:4.3.20.RELEASE (*)
     \--- org.springframework:spring-core:4.3.20.RELEASE (*)
```

Thanks for looking into it.

**Comment by MartinX3** [comment]
I got the same problem.

Level 2 dependencies doesn't get loaded.
I use
`compile group: 'org.springframework.boot', name: 'spring-boot-starter-mail', version: '2.1.1.RELEASE'`
which should load
`compile group: 'org.springframework.boot', name: 'spring-boot-starter-thymeleaf', version: '2.1.1.RELEASE'`
and its dependencies.
But only
`compile group: 'org.springframework.boot', name: 'spring-boot-starter-thymeleaf', version: '2.1.1.RELEASE'`
gets loaded and its dependencies are getting ignored.

Downgrading to gradle 4.10.2 fixed this problem.

**Comment by yidongnan** [comment]
I got the same problem.Level 2 optional dependencies doesn't get loaded.

**Comment by big-guy** [comment]
@gradle/dependency-management Could you chime in here?  This seems related to Daz's comment here: https://github.com/gradle/gradle/issues/5434#issuecomment-416666751

Is there something in the migration guide or user guide that explains this behavior?

**Comment by GFriedrich** [comment]
@big-guy thx for the reference of the connected issue. Now it makes sense to me why it behaves this way, even though I've used "IMPROVED_BOM_SUPPORT" in 4.10.2.
It should definitely mentioned somewhere that the optional dependency support was removed again with Gradle 5.0.
From my point of view this issue can be closed now, but I leave this up to you.

**Comment by ljacomet** [comment]
Hello,

Thanks for the report and sorry for the surprise there. We purposely did not call out some of the more arcane changes done around features of `IMPROVED_POM_SUPPORT` and its enabling in 5.0.
We have a [high level comment](https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:dependency_constraints) in the migration guide instead.
Note that `optional` dependencies were only pulled in as `constraints` and so the change _should not_ impact what's in the graph, while it may have an impact on the resolved version.

@MartinX3 If the above does not apply to your issue, please file another one with more details, for example including the `dependencies` input for the affected configuration.
