### ISSUE TITLE
[Nov 7] Publish 3.2 RC 3

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#785]
#778 #779 #783

**Comment by bmuschko** [comment]
Let's specifically point out the [known Jansi issue](https://github.com/gradle/gradle/blob/release/subprojects/docs/src/docs/release/notes.md#usage-of-jansi-library-embedded-with-java-annotation-processor) in the release notes.

**Comment by eriwen** [comment]
Closed as delivered!
