### ISSUE TITLE
Specifying classifier breaks maven-publish functionality

### ISSUE THREAD

**Issue by anadendla-zscaler** [gradle/gradle#7857]
Maven allows classifiers as part of the jar filename and as part of the jar task.

Using a classifier on a library and publishing using maven-publish causes the jar file name to come with a classifier `myLib-1.1-jdk18.jar` and the pom file to be named `myLib-1.1.pom`.

Because of the mismatch above, downstream users are not able to refer to the library successfully.

### Expected Behavior
Allow specifying a classifier in the `maven(MavenPublication)` task so the jar file and the pom file name match.
### Current Behavior
the jar and pom file name have a mismatch and we are not able to refer to the jar file in other projects.
### Context
I have a project for which i use the current git branch as one of the classifiers. This allows me to distinguish between builds(feature/bugfix etc). If i use a classifier on the jar file name, there is currently no way to publish the jar file using the plugin.

### Steps to Reproduce (for bugs)
In the below example, if "myLib" has a classifier as part of the jar file, the build fails for the "app"(downstream consumer of library).
If the classifier is commented out...everything works.
see https://github.com/anadendla-zscaler/gradle-maven-local
### Your Environment
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.14.1 x86_64

**Comment by marcphilipp** [comment]
That's how Maven classifiers are supposed to work.

From the official [POM reference](https://maven.apache.org/pom.html):

> The classifier distinguishes artifacts that were built from the same POM but differ in content. It is some optional and arbitrary string that - if present - is appended to the artifact name just after the version number.

You'll need to change your dependency declaration to `compile 'com.example:myLib:1.1:jdk18'` to make it work.
