### ISSUE TITLE
Make download events visible in 'info' log level

### ISSUE THREAD

**Issue by wszeboreq** [gradle/gradle#7862]
### Expected Behavior

As described in https://github.com/gradle/gradle/issues/6098 download events should now be visible in 'info' log level.

Also, ideally I would like to have a possibility to revert download events visibility in the default log level (just in the console).

### Current Behavior

Currently (Gradle 5.0-rc-5) download events are visible in 'debug' log level, but not in 'info' - this was confirmed to be done by mistake in https://github.com/gradle/gradle/issues/6098#issuecomment-425970674 - examples:

```
13:44:33.659 [DEBUG] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Downloading http://xxx.xxx.xxx.xx:8081/repository/xxx/com/xxx/xxx/xxx/xxx/maven-metadata.xml to D:\tmp\gradle_download6264871921616986023bin
```
```
13:44:33.793 [DEBUG] [org.gradle.internal.resource.transfer.DefaultCacheAwareExternalResourceAccessor] Downloading http://xxx.xxx.xxx.xx:8081/repository/xxxx/xxx/xxx/xxx/xxx/xxx.xxx.xxx.xxx/xxx/xxx.xxxx.xxx-xxxxxxx-resources.zip to D:\tmp\gradle_download5266068623856984472bin
```

### Context

Visibility of download event in 'info' log level e.g. allows me to easily notice/check if build triggered a download of a remote artifacts or not. Debug log is too detailed for this purpose. The previous old behavior (abandoned with https://github.com/gradle/gradle/issues/6098) of displaying download events in the console was even more useful for us.

### Your Environment

```
------------------------------------------------------------
Gradle 5.0-rc-5
------------------------------------------------------------

Build time:   2018-11-22 19:58:45 UTC
Revision:     42e59c2484a49702234030881640aa8d8bfa6d43

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Windows 10 10.0 amd64
```

**Comment by dlandis** [comment]
Would love to see this changed as I found the `Downloading...` messages very useful at times but the `debug` level is way too overloaded.

**Comment by big-guy** [comment]
I bumped the logging to INFO in https://github.com/gradle/gradle/commit/a33907db68bba084be09f85316eecad7d9618f87

**Comment by dlandis** [comment]
thanks
