### ISSUE TITLE
Don't attempt to fetch virtual platform

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#7865]
With the change that made the test in https://github.com/gradle/gradle/pull/7782 pass, you can now add a constraint on a virtual platform, and its components will align with that constraint.
However, it seems that gradle is still attempting to fetch the platform itself in the process, as if it were a published platform.

cc @melix

### Expected Behavior

Gradle should not attempt to resolve a virtual platform against any of the repositories.

There should be a way to tell gradle that a coordinate is definitely a virtual platform, so it won't even _attempt_ to download it.

### Current Behavior

Gradle tries to resolve the virtual platform's pom and jar against all the defined repos, and fails.
After it can't find it, it does manage to align its components to the expected version, but it made unnecessary requests that are wasteful and slow down the build.

### Context

I'm trying to ensure a group of components matching a pattern all get the same version, or fail the build otherwise.
The way I'm going about it is by assigning the matching components to a virtual platform, and adding a single constraint on the platform itself.
I know this could be achieved by adding a constraint on one of the matching components as well, but I'm not a fan of that solution because I might not know the coordinate to any of them at the point where I define my constraints.

### Steps to Reproduce (for bugs)

A short build definition:

```gradle
repositories {
    jcenter()
}

configurations {
  foo
}

dependencies {
    components.all { ComponentMetadataDetails details ->
        if (details.id.group.startsWith("com.fasterxml.jackson.")) {
            println "Got component: $details"
            details.belongsTo "com.fasterxml.jackson:platform:${details.id.version}"
        }
    }
}

dependencies {
  constraints {
      foo platform("com.fasterxml.jackson:platform:2.9.5")
  }

  foo 'com.fasterxml.jackson.core:jackson-databind:2.9.3'
  foo 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.0'
}
```

Trying to get the dependencies of `foo` shows that gradle attempts to look up the platform externally:

```
...
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/platform/2.9.5/platform-2.9.5.pom]
Resource missing. [HTTP HEAD: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/platform/2.9.5/platform-2.9.5.jar]
Resource missing. [HTTP GET: https://repo.jfrog.org/artifactory/libs-release-bintray/com/fasterxml/jackson/platform/2.9.5/platform-2.9.5.pom?referrer]
Resource missing. [HTTP HEAD: https://repo.jfrog.org/artifactory/libs-release-bintray/com/fasterxml/jackson/platform/2.9.5/platform-2.9.5.jar?referrer]
...
```

### Your Environment

 * Build scan URL: https://gradle.com/s/5npyqhuhjnixk
 * Repo: https://github.com/dansanduleac/gradle-test/tree/issue-7865

**Comment by melix** [comment]
This is expected as we have no way to know from the declaration if the platform is virtual or not. It's only as soon as we have a rule which applies that we know it, which is too late already.

**Comment by dansanduleac** [comment]
I suspected as much!
That's why I said:
> There should be a way to tell gradle that a coordinate is definitely a virtual platform

In our use case, we are planning to replace nebula-style forces (like `com.fasterxml.jackson:* = 2.9.5`) with virtual platform constraints. It would be unfortunate if there were no way to tell gradle that this is a self-defined virtual platform and it would try to look it up unsuccessfully for every single platform every time.

**Comment by melix** [comment]
Yup, I agree it would be nice to explain this a virtual platform to avoid lookups in this case. Are the network calls actually causing you troubles?

**Comment by dansanduleac** [comment]
Just realised something - while network calls are a problem, a larger issue is that platforms are deemed virtual per project (as far as I can tell) and that means that I can't just apply a platform constraint to multiple projects (e.g. allprojects)
if I try to do that, but there exists a project among those which does not have even a single dependency matching the platform (i.e. `belongsTo` is not called), then gradle will just treat the platform as a published platform and fail resolution.

Happy to file a separate issue for that in particular if you'd like me to.

**Comment by melix** [comment]
Note that depending on the order of resolution, you _may_ or may not have network calls. As for this:

> if I try to do that, but there exists a project among those which does not have even a single dependency matching the platform (i.e. belongsTo is not called), then gradle will just treat the platform as a published platform and fail resolution.

No it won't if you use a `constraint`: if you don't have any `belongsTo`, then the platform will never be referenced, and the constraint never applied. So you will never have a network request and the build won't fail.

**Comment by dansanduleac** [comment]
It seems you're right, my bad!

I _am_ hitting an issue where a virtual platform ends up as an `UnresolvedDependencyResult` in the `ResolutionResult`, and as far as I can see, all I'm doing is adding a constraint on it (to pretty much all configurations), but this is part of a larger plugin and I've not been able to find a repro for it yet.
I'll come back once I have it (or maybe I just made a very silly mistake somewhere)

**Comment by dansanduleac** [comment]
@melix Ok I found the repro!
Turns out, if you depend on a module without transitive dependencies, then the virtual platform will fail to resolve. Updating description with repro and build scan.

**Comment by ljacomet** [comment]
I believe this has been fixed since `belongsTo` now implies _virtual_ platforms and you need to use an overload to tell it your platform is real.

Re-open if that's not the case.
