### ISSUE TITLE
Continuous Build: Changes under --project-cache-dir should not trigger rebuild

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#787]
Running a continuous build does not work as expected when `sourceSets {}` includes the root directory of the project. 

### Expected Behavior
Changes in `--project-cache-dir` should not trigger continuous builds.

### Current Behavior
Changes that occur in the `.gradle/` directory end up triggering additional builds, and in some cases can result in an infinite loop of builds.

### Context
This prevents the use of `--continuous` build in use cases where the `rootDir` is added to `sourceSets{}`. 

### Suggested Fix
From Adam:

> The actual problem here is that the source set definition happens to include these directories, even though this is not the intention. This will affect all kinds of things: the mapping to the IDE, incremental build, output caching, construction of a source jar, and so on, as the source set is input to many things (every thing in fact), not just continuous build. So, we should fix this by improving the definition of the source set so that it does not unintentionally include these directories. We _could_ consider changing the source set definitions to exclude the project cache dir by default.

**Comment by oehme** [comment]
How does the project root directory as a source folder even make sense? Maybe we should just detect and forbid that instead?
