### ISSUE TITLE
"Connection refused" integTest failures

### ISSUE THREAD

**Issue by huxi** [gradle/gradle#788]
I have failing integration tests because the exception message of `org.apache.http.conn.HttpHostConnectException` has changed for some reason. I don't know whether that reason is Java 8u112, macOS 10.12.1 or apache.http.

The output in question now looks like this
`org.gradle.api.UncheckedIOException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:54268 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1, localhost/fe80:0:0:0:0:0:0:1%1] failed: Connection refused (Connection refused)`
instead of either
`org.gradle.api.UncheckedIOException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:54268 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1, localhost/fe80:0:0:0:0:0:0:1%1] failed: Connection refused`
or
`org.gradle.api.UncheckedIOException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:54268 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1, localhost/fe80:0:0:0:0:0:0:1%1] failed: Connection refused: connect`
which the current regex could handle.

### Expected Behavior

The integration tests should not fail.

### Current Behavior

The following integration tests fail:
- `org.gradle.api.publish.ivy.IvyPublishHttpIntegTest`
   - `"reports failure publishing to HTTP repository"`
- `org.gradle.integtests.publish.ivy.IvyHttpPublishIntegrationTest`
   - `reportsFailedPublishToHttpRepository`
- `org.gradle.plugin.use.resolve.service.PluginResolutionServiceCommsIntegrationTest`
   - `"non contactable resolution service produces error"`
   - `"non contactable dependency repository produces error"`

The regex used to check the message should be altered. It currently contains the following string:
`Connection refused(: connect)?`

This should be changed to either
`Connection refused.*` (relaxing the checking)
or
`Connection refused(: connect|\\ \\(Connection refused\\))?` (adding my current output to the set of valid outputs).

### Context

I'm currently trying to ensure that #699 won't break your integration tests. That PR extends `GradleExecuter` in such a way that you either have to declare incubation warnings or say that you aren't interested in them - similar to the way deprecation warnings are currently handled already. This is guaranteed to break all integration tests of incubating features and I want to include the proper fix for those broken tests in my PR - because otherwise you probably won't like my PR very much.

To achieve this, I need working integration tests to begin with.

### Steps to Reproduce (for bugs)

Execute `./gradlew check` in the root of the `gradle` repository with my environment.

### Your Environment
```
------------------------------------------------------------
Gradle 3.3-20161025000042+0000
------------------------------------------------------------

Build time:   2016-10-25 00:00:42 UTC
Revision:     2b77833dc5c3eb654e051913e78967cfcace8345

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_112 (Oracle Corporation 25.112-b16)
OS:           Mac OS X 10.12.1 x86_64
```

**Comment by huxi** [comment]
Should I close this issue or will you do it once this has been in a release?

**Comment by eriwen** [comment]
Cards are closed when users get the benefit, so I think this can be closed
immediately. Thanks!
