### ISSUE TITLE
Better handle a missing file name or url in Gradle module metadata

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#7889]
### Expected Behavior

Either fail with a useful error message when the `name` or `url` property is missing. Alternatively, provide some useful default, for example use the name as the default URL.

### Current Behavior

Currently, the `name` and `url` properties are required for a file that is referenced by the Gradle metadata file. When one of these is missing, the build fails with no-very-useful error messages that does not indicate what the problem is. For example, a missing `name` property leads to a NPE.

**Comment by jjohannes** [comment]
Fixed with #9336.
