### ISSUE TITLE
Provider#map cannot shed its value.

### ISSUE THREAD

**Issue by tjni** [gradle/gradle#7902]
Whether an optional `Property` on a task is missing can depend on another `Provider`. In that case, it's necessary to produce from that `Provider` another value-less `Provider`.

### Expected Behavior
It would be convenient to be able to shed the value during a transformation:
```
provider.map { condition ? value : null }
```

### Current Behavior
This violates the documented contract of `map` and throws an exception with message:
```
Transformer for this provider returned a null value.
```
It's possible to work around this using `flatMap`:
```
provider.flatMap { condition
    ? project.providers.provider({ -> value })
    : project.providers.provider({ -> null })
}
```
However, this is very awkward.

### Steps to Reproduce (for bugs)
```
class ExamplePlugin implements Plugin<Project> {
    void apply(Project project) {
        project.task('example', type: ExampleTask) {
            message = project.providers.provider({ -> "Forbidden message." }).map {
                it != "Forbidden message." ? it : null
            }
        }
    }
}

class ExampleTask extends DefaultTask {
    @Optional @Console
    final Property<String> message = project.objects.property(String)

    @TaskAction
    void runTask() {
        println(message.getOrNull() ?: 'Hello, world!')
    }
}

apply plugin: ExamplePlugin
```
Run
```
./gradlew example
```

### Your Environment
 * https://scans.gradle.com/s/42kzufeiwhncc

**Comment by adammurdoch** [comment]
Thanks for reporting the issue. Do you have a more concrete example of what you'd like to use this for?

**Comment by tjni** [comment]
Thanks for responding! Yes, I can give an example.

I'm working on refactoring an existing task which accepts as inputs two different sets of credentials for two different staging environments. These are captured in two JSON files, which are parsed and set as two different input properties to my task. At execution time, a command line option is read to choose which credential to use.

Some users of this task might only have one of the two credential files available, and so they can only run the task with one value for the command line option, but I would like that to succeed.

I'm not convinced that the UX we're providing is the best possible, but I don't want to change it without giving an appropriate amount of heads up. This means, for example, I can't change the task right now to use a single multi-tenant credential file or switch to using a system property and choose which file to wire at configuration time.

**Comment by adammurdoch** [comment]
Thanks for the example. Do you want to be able to do something like this?

```
val jsonFileContent = providers.provider { ... parse some file ... }
myTask.credentials = jsonFile.map { s -> if (commandLineOption)  s else null }
```

**Comment by tjni** [comment]
Yes, something exactly like that or equivalent would solve my issue.

**Comment by adammurdoch** [comment]
Fixed via https://github.com/gradle/gradle/pull/12025
