### ISSUE TITLE
Kotlin DSL plugin documentation doesn’t have Groovy snippets

### ISSUE THREAD

**Issue by gildor** [gradle/gradle#7904]
Kotlin DSL plugin documentation doesn’t have Groovy snippets
https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

I think it can be useful for people who want to migrate Groovy/Java plugin to Kotlin, but don’t want to start from migration to `build.gradle.kts` from `build.gradle`

Also kotlin-dsl plugin cannot be applied without explicit version from Groovy, like `id 'kotlin-dsl'` or at least `id 'org.gradle.kotlin.kotlin-dsl'`. not sure, should this point be reported to a separate issue

**Comment by eskatos** [comment]
Issue moved to [gradle/kotlin-dsl #1270](https://github.com/gradle/kotlin-dsl/issues/1270) via [**ZenHub**](https://www.zenhub.com/)
