### ISSUE TITLE
Allow file or project dependencies to be used as platforms

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#7909]
### Expected Behavior

I'd like to be able to use a file or the contents of a project dependency as a platform or enforced platform. It would be great if something like this was possible in the file case:

```groovy
dependencies {
    implementation platform(file('pom.xml'))
}
```

Or something like this in the case of a project dependency, where the `bom` configuration contains the pom file with the dependency management metadata:

```groovy
dependencies {
    implementation platform(project(path: ":bom", configuration: "bom"))
}
```

### Current Behavior

I understand from @ljacomet that no metadata processing is performed on file-based dependencies. It appears the same is true of project-based dependencies as well. The end result is that the configuration of the platform has no effect, i.e. it seems to fail silently.

### Context

My goal is to be able to write Maven dependency management metadata in a pom.xml file, publish this for use by Maven users and also consume it in the same multi-project Gradle build as a platform or enforced platform.

### Steps to Reproduce (for bugs)

N/A

### Your Environment

Gradle 5.0

**Comment by melix** [comment]
> My goal is to be able to write Maven dependency management metadata in a pom.xml file, publish this for use by Maven users and also consume it in the same multi-project Gradle build as a platform or enforced platform.

So your build is a Gradle build? If so, this is going to be superceded by the support for defining platforms in Gradle directly. So basically your `file(...)` or `project(...)` dependency would become a project dependency on a platform module.

**Comment by wilkinsona** [comment]
Yes, that's right. Defining a platform in Gradle directly sounds exactly like what I'd like to do, particularly if it's possible for the platform to be published as a Maven pom with `<dependencyManagement>`.

**Comment by melix** [comment]
For completeness, there *is* already a way to publish a BOM. It's not what we will eventually implement, in particular in the context of Gradle metadata, but it should already solve your use case. The idea is to use the "Java library" plugin to publish a BOM file. So you would say you build a Java Library, when in practice it's just a BOM file. Here's an example:

```kotlin
plugins {
    `java-library`
    `maven-publish`
}

group = "org.example"
version = "1.0"

repositories {
    jcenter()
}

dependencies {
    constraints {
       api("org.apache.commons:commons-math3:3.6.1")
    }
}

publishing {
    publications {
        create<MavenPublication>("myBom") {
            from(components["javaLibraryPlatform"])
        }
    }

    repositories {
        maven {
            name = "myRepo"
            url = uri("file://${buildDir}/repo")
        }
    }
}
```

then calling `publishMyBomPublicationToMyRepoRepository`, you'd end up with a `pom.xml` file which is effectively a BOM:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>bom</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-math3</artifactId>
        <version>3.6.1</version>
        <scope>compile</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

There are 2 "tricks" to make this work:

1. use `constraints` in dependencies
2. use `javaLibraryPlatform` as the component source for publishing

**Comment by wilkinsona** [comment]
Thank you, @melix. Is it possible to use a third-party platform as a constraint? I'm aiming for the equivalent of a Maven bom that uses `<scope>import</scope>` and `<type>pom</type>` to include another pom in its own dependency management. I've tried something like the following but it didn't appear to work:

```
dependencies {
    constraints {
       api("org.apache.commons:commons-math3:3.6.1")
       api platform("org.springframework:spring-framework-bom:5.1.3.RELEASE")
    }
}
```

The symptom was that an `org.springframework:spring-core` dependency in a project that depends on the bom project could not be resolved due to the lack of a version. Directly defined constraints, such as the one above for `commons-math3`, are working nicely.

**Comment by melix** [comment]
Constraints will only apply if Gradle sees another "hard" dependency on the same thing. So, what you could do is to add a real dependency on the platform instead:

```
dependencies {
    constraints {
       api("org.apache.commons:commons-math3:3.6.1")
    }
    api platform("org.springframework:spring-framework-bom:5.1.3.RELEASE")
}
```

however, those dependencies are not _inlined_ and wouldn't get published as part of a BOM, typically.

**Comment by ljacomet** [comment]
However, when publishing to Maven, the platform declaration would appear as a `<scope>import</scope><type>pom</type>` in the `pom.xml`

**Comment by wilkinsona** [comment]
Thanks, both. That is working nicely.

**Comment by ljacomet** [comment]
Since there is a relatively easy workaround and Gradle 5.2 will support native platform definition, closing this.
