### ISSUE TITLE
Javadoc anchors no longer work in Gradle 5.0

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#7917]
### Expected Behavior
Links like this should go directly to the anchor specified in the URL: https://docs.gradle.org/5.0/javadoc/org/gradle/api/artifacts/dsl/DependencyHandler.html#artifactTypes-org.gradle.api.Action-

### Current Behavior
After a short delay, the page scrolls (jumps) back to the top.

### Context
I traced this to https://docs.gradle.org/5.0/javadoc/search.js line 98:

`$("#search").focus();` 

This seems to be caused by the new autocomplete included with Javadocs generated by Java 9. Why it is necessary to focus the search box I don't know but this line and the next line should be eliminated.

This `search.js` is coming from the JDK so we'll have to see if this is either fixed in a newer version of Java or if we'll have to do some transform. 

### Steps to Reproduce (for bugs)
Visit https://docs.gradle.org/5.0/javadoc/org/gradle/api/artifacts/dsl/DependencyHandler.html#artifactTypes-org.gradle.api.Action-

### Your Environment
This occurs on Chrome, Firefox, and Safari on macOS at least.

**Comment by big-guy** [comment]
According to the docs, `-noindex` should disable the search box, but I'm not sure what else it may disable.  Do you want to give it a go for 5.1?

**Comment by eriwen** [comment]
The search box seems like a nice feature it'd be a shame to lose it because of this. 

I imagine we can figure something else out, even running JS after the search init to jump the page back down (ugh)

**Comment by lacasseio** [comment]
The javadoc seems to be opinionated that the top navigation is always present (aka using frames), so the page can jump to the right anchor as well as focus on the search box. See https://docs.oracle.com/javase/9/docs/api/java/io/File.html#exists--

**Comment by lacasseio** [comment]
It seems our stylesheet is a bit out of date compared to the latest version, notably missing the `.fixedNav` css. I will see if I can take the latest generated CSS from javadoc and copy our change to it without much change to the style.

**Comment by lacasseio** [comment]
PR: https://github.com/gradle/gradle/pull/8891

**Comment by lacasseio** [comment]
This issue affects the Javadoc for Gradle 5.0 to 5.3.1 and all GA and RC versions in between. Do we plan on rolling backward to fix all those versions? It may be possible to simply replace the old CSS with the new one to fix the issue for each version.

**Comment by lacasseio** [comment]
@big-guy Do we care about the affected released documentation?

**Comment by big-guy** [comment]
I was going to see if this worked on the deployed site with a nightly.  I think it would be nice to fix the existing docs if we can

**Comment by lacasseio** [comment]
The topmost header is broken as it doesn't stay in place. See https://github.com/gradle/gradle-private/issues/2037
