### ISSUE TITLE
[Gradle 5.0] maven publishing is broken

### ISSUE THREAD

**Issue by hrstoyanov** [gradle/gradle#7922]
When I upgrade to Gradle 5.0, publishing my snapshots to Maven central bombs:
See [this for more details](https://issues.sonatype.org/browse/OSSRH-44610)

Downgrading to Gradle 4.10.2 fixes the issue. I suspect this piece of code:

```
publishing {
        repositories {
            maven {
                url = version.endsWith('SNAPSHOT') ?
                        "https://oss.sonatype.org/content/repositories/snapshots/"
                        : "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
                credentials {
                    username sonatypeUsername
                    password sonatypePassword
                }
            }
        }
    }
```

gets confused and picks the wrong URL (https://oss.sonatype.org/service/local/staging/deploy/maven2/) to publish to when I set my artifact version to  0.0.1-SNAPSHOT in Gradle 5.0.

Again, the issue does not exist in 4.10.2!

**Comment by marcphilipp** [comment]
That's most likely because the `publishing` block is now evaluated eagerly (there probably was a deprecation warning about this behavior being deprecated in your 4.10.x build). When do you set the project version? After the `publishing` block?

**Comment by marcphilipp** [comment]
https://github.com/peruncs/gwt is the project in question, right?

Since the version is set by subprojects, you'll need to wrap the assignment of `url` in an `afterEvaluate` block.
