### ISSUE TITLE
Task action implementation is not tracked when added via Task.doLast(String, Action)

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#7923]
@wolfs commented on [Tue Dec 04 2018](https://github.com/gradle/build-cache/issues/1364)

See https://github.com/gradle/kotlin-dsl/issues/1271

The underlying issue is that we don't unpack `ConfigureUtil.WrappedConfigureAction` which is created by the `Closure` accepting method created by our runtime task decoration.

**Comment by wolfs** [comment]
@jjohannes Can you maybe look into fixing this, given that you introduced the method(s)? I can give some guidance.

**Comment by lptr** [comment]
I'm guessing this is not true anymore?

**Comment by wolfs** [comment]
I am pretty sure it still is. At least I don't remember fixing anything in that area.

**Comment by lptr** [comment]
IIRC, we did track _unnamed_ additional actions properly, it was only an issue with the (then) newly added _named_ actions. If you look at the code we are now calling through from unnamed to named, so either we don't have the problem or we have the problem with unnamed actions, too.

I'd be pretty surprised if we had a problem with tracking the implementation of unnamed actions, as we have tests for that case.

**Comment by lptr** [comment]
Ah, is this not about the "new" methods adding the `String` parameter, but the methods taking `Closure`?

> The underlying issue is that we don't unpack `ConfigureUtil.WrappedConfigureAction` which is created by the `Closure` accepting method created by our runtime task decoration.

Those methods are gone now. Does that change the situation?

We do unwrap `WrappedConfigurationAction` here, but it's not related:

https://github.com/gradle/gradle/blob/d9f98fecd1dfb9cd6184346299aa265a6552230b/subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/bean/NestedRuntimeBeanNode.java#L63-L67

**Comment by wolfs** [comment]
We should fix this.

**Comment by lptr** [comment]
Woo-hoo! 🎉
