### ISSUE TITLE
Deprecation Warning when using IvyArtifactRepository.layout says "This is scheduled to be removed in Gradle 5.0" when building with gradle 5.1-milestone-1

### ISSUE THREAD

**Issue by ManfredSchenkIOSB** [gradle/gradle#7934]
When using gradle 5.1-milestone-1 with a gradle build that uses the IvyArtifactRepository.layout(..) method a Deprecation Warning is issued with the text "This is scheduled to be removed in Gradle 5.0".

Since the new method patternLayout is new in gradle 5.0 I assume that the Warning should read "..be removed in Gradle 6.0"

### Expected Behavior

The build should issue a Warning "This is scheduled to be removed in Gradle 6.0" (or some othe future version)

### Current Behavior

The build issues a Warning "This is scheduled to be removed in Gradle 5.0" which seems to be a bit strange in a post-5.0 version.

### Steps to Reproduce (for bugs)

Define an IvyArtifactRepository using the IvyArtifactRepository.layout(..)  method and build with gradle gradle 5.1-milestone-1. 

### Your Environment

gradle 5.1-milestone-1, latest Oracle JDK 8, Windows 10

 * Build scan URL:

**Comment by ljacomet** [comment]
Hello,

Thanks for the report.

The version that appears in the message is computed and there was a bug, see #7908. `5.1 RC1` will report this deprecation and removal for Gradle `6.0`
