### ISSUE TITLE
Application plugin documentation does not document convention properties

### ISSUE THREAD

**Issue by isker** [gradle/gradle#7939]
https://docs.gradle.org/current/userguide/application_plugin.html#sec:application_convention_properties mentions that the plugin uses convention properties but does not provide any details.  To find them, I have to find the convention docs https://docs.gradle.org/current/dsl/org.gradle.api.plugins.ApplicationPluginConvention.html, which are not linked from that article.

**Comment by marcphilipp** [comment]
While you should prefer the `application` extension to configure it, I agree that this could improved. Would you be interested in submitting a PR?

**Comment by isker** [comment]
Well, the extension is likewise undocumented in that article. There are
usage examples but nothing that covers all of the extension properties.
Sounds like both should be explained?

I can try to throw something together pending your judgment of what should
be added.

**Comment by marcphilipp** [comment]
I think linking to the extension and the convention in the DSL docs would make sense.

**Comment by isker** [comment]
OK, I will try to produce a PR for this.

**Comment by isker** [comment]
@marcphilipp looking into it, I can't find any Javadocs or DSL docs for https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaApplication.java.  There is nothing in https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/package-summary.html.  Do you know why that is?  There is nothing for me to link to for the extension.
