### ISSUE TITLE
Gradle 5 does not pick annotation processor from project dependency

### ISSUE THREAD

**Issue by ishaigor** [gradle/gradle#7941]
My project has subprojects that are generating different artifacts. Among those, the subproject of interest are
* model - contains annotations that will be used in other sub-projects
* model-processor - contains annotation processor that generates sources for any class found with the annotations from model subproject
* consumer - contains classes annotated with annotations from model subproject that should be accompanied by sources generated by annotation processor from model-processor subproject.

The build.gradle for consumer sub-project looks like
```
description = ''
dependencies {
    annotationProcessor project(':model-processor')

    compile project(':model')
}
```
### Expected Behavior

I expect to find the generated sources under ﻿consumer/build/generated/source/apt/main
### Current Behavior

I am not getting the files generated under consumer/build/generated/source/apt/main with the Gradle 5.0. I do get the annotation processor to work with the same build script and Gradle 4.10.2.
### Context

I am trying to switch to Gradle 5 from Gradle 4.10.2 where the generation works. If I cannot get the annotation processor to work, I cannot migrate.

### Steps to Reproduce (for bugs)

Clone https://github.com/ishaigor/annotation-processor-sample
Follow the steps in README

### Your Environment

 * Build scan URL: 
  * https://gradle.com/s/sremu47v5j5kk - non working 5.0
  * https://gradle.com/s/5pa5eu7fsrnic - working 4.10.2

**Comment by ishaigor** [comment]
@big-guy, @oehme, @marcphilipp, I updated the description with the link to the sample that demonstrates the issue. Is there anything else needed in addition to the sample and the build scans?

**Comment by ishaigor** [comment]
Thank you for looking into the issue, one annotation processor was not declared: com.google.auto.service. Pushed correction out.

**Comment by radzio** [comment]
@ishaigor can tell more how you fixed your issue? I have the same and upgrading auto-service didn't help.

**Comment by ishaigor** [comment]
Take a look at https://github.com/ishaigor/annotation-processor-sample/commit/d7645914b9f53a5f350c7098973f3554c48e75d8#diff-366f42343748f0d02147a45a53a2cf62 @radzio

**Comment by swathistudyblue** [comment]
I have multiple annotations in my project from lombok, slf4j, spring etc. And I created a new annotation and a processor for it. When I register this processor, all the other annotations start throwing compile errors. Is there anything specific I have to do to add to the existing list of processors.

**Comment by marcphilipp** [comment]
@swathistudyblue You need to add the other processors as dependencies to the `annotationProcessor` configuration as well.

**Comment by oradkovsky** [comment]
Upgrading auto-service didn't help for me as well. Fighting build system instead of doing useful work :(

**Comment by Yukooo** [comment]
Have the same issue, @oradkovsky  have you managed to fix it. PS. All files are generated and placed in the `$buildDir/generated/sources/annotationProcessor/java/main` even the Intelijia Idea see those generated java files, but still, when I try to extend my class with a generated one, gradle can not find it.
