### ISSUE TITLE
Publication of platform component

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#7945]
With the addition of [BOM support](https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import) and [dependency alignment](https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:version_alignment), Gradle needs the ability to publish a platform.

Such a platform publication needs to be supported in the Gradle metadata format and, with possibly some lossy conversion, be able to produce a valid Maven BOM.

**Comment by marcphilipp** [comment]
Is a platform component a BOM, i.e. using `dependencyManagement` in the generated POM, or like `javaLibraryPlatform` a "aggregator" that uses packaging `pom` and `dependencies` in the generated POM?

**Comment by melix** [comment]
`javaLibraryPlatform` is using `<dependencyManagement>`. But the idea is to have a real "platform" component.

**Comment by marcphilipp** [comment]
It's only using `<dependencyManagement>` for constraints, though, isn't it? Regular dependencies would end up in `<dependencies>`, wouldn't they?

**Comment by melix** [comment]
I think so, but if you are writing a platform, you should _not_ have dependencies, only constraints.

**Comment by melix** [comment]
FTR work on a real "Java platform" plugin happens on this PR: https://github.com/gradle/gradle/pull/7967/commits

**Comment by ljacomet** [comment]
Feature and documentation have been merged, closing
