### ISSUE TITLE
`artifact(..)` from `MavenPublication` does not support the lazy configuration API

### ISSUE THREAD

**Issue by madhead** [gradle/gradle#7958]
The result of calling `tasks.registering()` is not supported by `MavenPublication.artifact()`.

### Expected Behavior

The build should succeed.

### Current Behavior

The build fails:

    * What went wrong:
    Cannot convert the provided notation to an object of type MavenArtifact: task ':experiments:sourcesJar'.
    The following types/formats are supported:
      - Instances of MavenArtifact.
      - Instances of AbstractArchiveTask, for example jar.
      - Instances of PublishArtifact
      - Maps containing a 'source' entry, for example [source: '/path/to/file', extension: 'zip'].
      - Anything that can be converted to a file, as per Project.file()

### Steps to Reproduce (for bugs)

Configure Maven publishing in a multi-module Gradle project like:

    subprojects {
        apply<JavaLibraryPlugin>()
        apply<MavenPublishPlugin>()

        configure<PublishingExtension> {
            publications {
                create<MavenPublication>("main") {
                    from(components["java"])

                    val sourcesJar by tasks.registering(Jar::class) {
                        val sourceSets: SourceSetContainer by project

                        from(sourceSets["main"].allJava)
                        classifier = "sources"
                    }

                    artifact(sourcesJar)
                }
            }
        }
    }

The build fails with the stacktrace above, because `artifact()` does not support the provided object.

### Context

Related SO question: https://stackoverflow.com/a/53654651/750510

In order to overcome the issue one needs to add a `.get()` call to the result of registering a task:

    subprojects {
        apply<JavaLibraryPlugin>()
        apply<MavenPublishPlugin>()

        configure<PublishingExtension> {
            publications {
                create<MavenPublication>("main") {
                    from(components["java"])

                    val sourcesJar by tasks.registering(Jar::class) {
                        val sourceSets: SourceSetContainer by project

                        from(sourceSets["main"].allJava)
                        classifier = "sources"
                    }

                    artifact(sourcesJar.get())
                }
            }
        }
    }

### Your Environment
    ------------------------------------------------------------
    Gradle 5.0
    ------------------------------------------------------------

    Build time:   2018-11-26 11:48:43 UTC
    Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

    Kotlin DSL:   1.0.4
    Kotlin:       1.3.10
    Groovy:       2.5.4
    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
    JVM:          1.8.0_192 (Oracle Corporation 25.192-b26)
    OS:           Linux 4.17.19-1-MANJARO amd64

**Comment by marcphilipp** [comment]
I fully agree that this would be very useful! 👍

**Comment by trejkaz** [comment]
This appears to now be responsible for the majority of eager task creation in my project. :)

The bit I don't fully understand is that I've registered the publication itself in a lazy fashion, yet I can see the tasks mentioned in there are definitely being created, so the publication itself must be getting created and configured. :(

**Comment by svermeulen** [comment]
This is also a blocker for making my scripts lazy.  Currently I have to calculate all the properties for every publication every time gradle is run even when it's not used

**Comment by jjohannes** [comment]
With Gradle 6, it is recommended to add additional variants (configurations) and add artifacts through them. Would that be sufficient to address the issues listed here?

Documentation: https://docs.gradle.org/release-nightly/userguide/publishing_customization.html

**Comment by technoir42** [comment]
@jjohannes adding artifacts to a configuration requires much deeper knowledge of Gradle to do properly (e.g. knowing what attributes are and that their combination must be unique). I'm saying that as someone who just spent a day learning that stuff.
For casual users being able to just write `artifact taskProvider` and still benefit from the lazy configuration would be really handy.

**Comment by pun-ky** [comment]
yep, totally agree with @technoir42 

for me, as a plugin author, it makes things a lot more complicated. As I cannot pass task provider to `artifact()` or it is eagerly resolved, it effectively is disabling laziness of my configuration. In the end, also causes some other integration issues for which I need to implement workarounds.

**I'd like to highlight that probably this issue needs to be more prioritized.**

 I have spent a lot of time in case of making my plugin and build lazy, but in the end, API offered by Gradle seems to be not complete in case of full development workflow, I mean artifact publication here. If I could do some workaround with passing artifact as a component, I will try, but it seems that it will be much harder workaround for sth looking very simple.

**Comment by pun-ky** [comment]
tried with introducing software component successfully

software component definition inside Java Plugin is using LazyPublishArtifact, which effectively is a clue in case of laziness which we want to achieve here.

which means, to resolve origin issue, @madhead you could simply write:

```kotlin
import org.gradle.api.internal.artifacts.dsl.LazyPublishArtifact

publications {
    create<MavenPublication>("main") {
        artifact(LazyPublishArtifact(sourcesJar))
    }
}
```

**Comment by NielsDoucet** [comment]
Seeing as there is an internal api available, what are the chances this can be made part of the public api?

**Comment by melix** [comment]
`LazyPublishArtifact` won't be made public, but we're working on APIs which should make this less relevant: https://github.com/gradle/gradle/pull/13395

**Comment by melix** [comment]
Btw, unless I'm missing something, if you use the software component factory, and _not_ the legacy `artifact` notation on Maven publications, you shouldn't have this problem at all, since artifacts attached to outgoing configurations are wrapped into lazy publish artifacts automatically.

**Comment by NielsDoucet** [comment]
My artifact is just a zipfile, created by a simple Zip task.
According to [the documentation](https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components), I can only get access to the software component factory from a plugin, which seems unnecessary in this case.

reduced build configuration:
```
val distributionZip by tasks.registering(Zip::class) {
    from(some fileset)
}

val myZipConfiguration by configurations.creating

artifacts {
    add(myZipConfiguration.name, distributionZip)
}

publishing {
    publications {
        register<MavenPublication>("myPublication") {
            artifact(LazyPublishArtifact(distributionZip))
        }
    }
}
```
This is a fairly straightforward setup in my opinion. I don't believe this use case is covered by the spike you linked, nor does it warrant building a plugin.

**Comment by melix** [comment]
For clarity I think it makes sense to move this code in a `buildSrc` plugin where you'd get access to the factory. There are options to get access to the service from the build script but I wouldn't recommend that.

The problem with using the API like you are is that it makes things difficult to consume from other projects, because there's no associated metadata.

We can consider adding something to this legacy `artifact` method but I'm not convinced we should encourage its use.

**Comment by NielsDoucet** [comment]
We have multiple binary distributions that get generated by a gradle build and published to a repository. None of these require any metadata to be consumed. 

As an example, the reduced build above is for creating a custom gradle distribution, which is downloaded directly from the repository by the gradle wrapper.

**Comment by melix** [comment]
Right. You say you don't need metadata... until you need it ;) We really have several options there. One of them is just to automatically wrap in a lazy artifact, the other is to offer an API to make such lightweight publications easier to create (and then published with proper metadata), ...
