### ISSUE TITLE
Update optional section in Maven migration guide

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#7984]
The Maven migration guide section on [optional dependencies](https://guides.gradle.org/migrating-from-maven/#provided_scope_and_optional_dependencies) still indicates that Gradle will transform optional dependencies into constraints.

This change, which was present behind the `IMPROVED_POM_SUPPORT` flag did not make it in 5.0 because it caused more issues than good. See conversations in #5434.

The documentation should be updated to reflect this.

**Comment by pledbrook** [comment]
How are optional dependencies treated then? I'm thinking about editing that section to make it a bit clearer. The current language is quite awkward and doesn't do a good job of distinguishing between consuming and publishing optional dependencies. I could fix this issue at the same time.

**Comment by ljacomet** [comment]
Optional dependencies are simply ignored for dependency management purposes. They have only a documentation meaning, the same as in Maven.

The Gradle feature that relates to them is [feature variants](https://docs.gradle.org/5.3/userguide/feature_variants.html#header).

**Comment by pledbrook** [comment]
@ljacomet Can you confirm whether this is fixed already, please? It appears to be and it just looks like this issue was overlooked and should have been closed with [this commit](https://github.com/gradle/gradle/commit/d09c2e354576ac41078c322815cc6db2b66d976e#diff-31aae0725493681984897ace4b8badd6R312).

**Comment by ljacomet** [comment]
Indeed!

Closing as done
