### ISSUE TITLE
Update test coverage to cover Scala 2.12.0

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#799]
Scala 2.12.0 was just released.

http://www.scala-lang.org/news/2.12.0

We currently only test Gradle against 2.10.4 and 2.11.1. We should consider updating these versions too.

Scala 2.12 only works with JDK8+, so we'll need to split our coverage accordingly.

**Comment by otrosien** [comment]
What would be the desired outcome? 

Update all existing scala references to latest of 2.10, 2.11 and add 2.12 to the ScalaCrossCompilationIntegrationTest? What should be the default scala version for the integration tests?

**Comment by big-guy** [comment]
This has been done
