### ISSUE TITLE
Consider a deprecation warning detail report

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#7996]
### Expected Behavior
A deprecation warnings report, either as part of the build output or separate command where we could get warnings associated with code in current project and warnings coming from 3rd party dependencies.

### Current Behavior
Deprecation warning message such as:

`The DefaultSourceDirectorySet constructor has been deprecated. This is scheduled to be removed in Gradle 5.0. Please use the ObjectFactory service to create instances of SourceDirectorySet instead.`

Show in the build, but this is coming from gradle-kotlin-plugin owned by Jetbrains on this case

### Context
We fail our builds when our plugins use deprecated APIs. However, this also includes 3rd party dependencies that we pull. For example: https://github.com/nebula-plugins/nebula-kotlin-plugin/blob/master/build.gradle#L43

Most of times, these dependencies are not fixed right away because it isn't a top priority for maintainers. 

It would be ideal if we could know warnings generated by us separated from the ones from 3rd party code.

**Comment by marcphilipp** [comment]
Build scans show details on where the warnings originate from, e.g. https://scans.gradle.com/s/jjyglf3euwwbq/deprecations. Is that an option for you?

**Comment by rpalcolea** [comment]
Hi @marcphilipp , this is related to https://github.com/gradle/gradle/issues/7991

Ideally, we would like to fail our builds when we have deprecations warnings. However, we found that sometimes there are warnings out of our control, for example: https://youtrack.jetbrains.net/issue/KT-26808

The information in the build scan is great, however we would like to have a easy way to fail a build when these are present from 3rd party.

**Comment by marcphilipp** [comment]
@rpalcolea So, can we close this issue in favor of #7991 then since the reporting part is covered by build scans?

**Comment by rpalcolea** [comment]
well, in our case we don't use build-scans for internal projects. It would be great to get it in the console output but if there are not plans to add that, I guess it is fine to close this
