### ISSUE TITLE
User Manual toc difficult to access on narrow screens

### ISSUE THREAD

**Issue by tnielens** [gradle/gradle#8000]
The user manual table of content is hard to reach (impossible?) on narrow screens. 
It makes it difficult to navigate the documentation and understand its structure.

Reproduction: narrow your browser on desktop env or open the manual on a phone.

**Comment by big-guy** [comment]
@gradle/developer-experience is this something fixable with the way the docs hide the navigation section?

**Comment by eriwen** [comment]
@big-guy this is fixable by allowing narrower content and keeping navigation there, by showing the sidebar on hover/click of some element, or by expanding the "hamburger menu" on the top to include navigation. 

Here's 2 lines of relevant code here: [hiding by default](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/css/manual.css#L1608-L1609) and [showing nav at a certain width](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/css/manual.css#L1843) — hope that gets someone started.

**Comment by quat1024** [comment]
This also makes it impossible to access the Gradle documentation from a phone >.>
