### ISSUE TITLE
Provide a way to stop daemon via tooling api.

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#8010]
When shutting down Android Studio, we also want to shutdown daemon and right new rely on some private (semi hacky way to do so). 

https://android.googlesource.com/platform/tools/idea/+/mirror-goog-studio-master-dev/plugins/gradle/src/org/jetbrains/plugins/gradle/internal/daemon/DaemonStopAction.java

Also when running tests on Windows, in order to avoid file locks, it would be much easier if we could have an orderly shutdown of the daemon.

**Comment by big-guy** [comment]
Dupe of #8219
