### ISSUE TITLE
Settings#PluginManagment not working on Android Projects

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#8017]
I created a new project and try to move away from the top-level `build.gradle` `buildscript` block.
For this I've moved the "where can Gradle find the AGP" into the `pluginManagment` block in the settings as the following:
```
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("com.android")) {
                useModule("com.android.tools.build:gradle:3.2.1")
            }
            if (requested.id.id.startsWith("org.jetbrains.kotlin")) {
                useVersion("1.3.11")
            }
        }
    }
}
```
This works - as long as you have only an application - as expected. You can use the `plugins` block in the `build.gradle[.kts]` file and everything is fine.
But this will be problematic when I create a new (library-) module and my application-module depends on them.
This is my library `build.gradle[.kts]`
```
plugins {
    id("com.android.library")
}

android {
    compileSdkVersion(27)
    defaultConfig {
        minSdkVersion(15)
        targetSdkVersion(27)
        versionCode = 1
        versionName = "1.0"
    }
}
```
and my application depends on them:
```
dependencies {
    implementation(project(":library"))
}
```

Now, when I run the `assemble` task the build fails with:
![bildschirmfoto 2018-12-12 um 12 13 43](https://user-images.githubusercontent.com/10229883/49866201-63f49680-fe07-11e8-90d3-361e0a59b6d1.png)

I have a full "working" sample here: 
https://github.com/StefMa/kotlin-dsl/tree/pluginmanagment_issue/samples/hello-android
(or if you just want to checkout the diff https://github.com/gradle/kotlin-dsl/compare/master...StefMa:pluginmanagment_issue)

The "funny" part of the issue is:
When I move back to the `buildscript` block (and remove the `settings#pluginManagment` everything works as expected.

TBH I'm not quite sure if this an issue with Gradle or the Android Gradle Plugin.
But because you write "somewhere" in you documentation (I can't find it currently - but I know I have read that in the past) that the "plugins{}" block behave "exactly" like the "apply plugin" I think it is more an Gradle issue. Because - well - it does not behave identical.
When I'm wrong and this is an AGP issue please give me an hint. I'll open an AOSP ticket for them 👍 

### Expected Behavior
When I use the `pluginManagment` block it behaves identical with the `buildscript` block.

### Current Behavior
The `lintVitalRelease` task failed.

### Context
See above 👆 

### Steps to Reproduce (for bugs)
You can checkout this project:
https://github.com/StefMa/kotlin-dsl/
Checkout the branch `pluginmanagment_issue`
Navigate into `samples/hello-android``
and run
```
./gradlew lintVitalRelease
```

### Your Environment
Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

Android Gradle Plugin 3.2.1

Gradle 4.10.3 (in the new project)
But Gradle 5.0 in the kotlin-dsl sample..

Scan: https://scans.gradle.com/s/jnnufyicb455y

**Comment by ljacomet** [comment]
There is something wrong in what you are doing.
The following:
```
if (requested.id.id.startsWith("com.android")) {
    useModule("com.android.tools.build:gradle:3.2.1")
}
```
will replace all android plugins with the module referenced. Which means the library and application plugins are not applied in the end AFAICT.

What are you trying to do with this?
Why did you replace the `classpath` entry with this substitution?

**Comment by StefMa** [comment]
My goal is that I use the `pluginManagment` block inside the `settings.gradle` file instead of the old/depreated `buildscript` block.
As I understand the documentation [here](https://docs.gradle.org/5.1/userguide/plugins.html#sec:plugin_resolution_rules) correctly that is the way to go, no?

I know that the code you mention is *not* responsible for *applying* the plugin - but it will all "map" all `com.android[xx]` plugins to the given module.
The plugins will be applied in each module (project(?)) build.gradle file.
See https://github.com/gradle/kotlin-dsl/compare/master...StefMa:pluginmanagment_issue#diff-73abc3e1564d593001e5f3e58116fd5eR2
and 
https://github.com/StefMa/kotlin-dsl/blob/pluginmanagment_issue/samples/hello-android/app/build.gradle.kts#L5

**Comment by ljacomet** [comment]
I was wrong in my first analysis. I tried your code and I have to admit I am puzzled as to why it does not work. The plugins are properly applied AFAICT.

So I went back over your changes and if I revert the versions upgrade _and_ the inclusion of `implementation(project(":library"))` in the app project, then `./gradlew assemble` passes fine.
So I think the issue is really around the sum of modifications, while just the changes about using `pluginManagement` are fine.

**Comment by StefMa** [comment]
> So I went back over your changes and if I revert the versions upgrade and the inclusion of `implementation(project(":library"))` in the app project ...

Have you tried to use the older versions with the `library` project as dependency?
I think the issue is the same...

How do we proceed here now? 🤔 
I that an issue?
And if yes, where?
I mean the `plugins` block together with the `pluginMangament` block **should be** a direct replacement for the `buildscript` block, right?
So I assume that it should work what ever solution you use. But it does not work. So I think something is broken with this "replacement"...

**Comment by ljacomet** [comment]
Indeed, if I test the project with the added library but without the changes around `pluginManagement`, it builds fine. And if I then use `pluginManagment` instead of `buildScript` the error reported above is shown.
Given that excluding the `app:lintVitalRelease` task from the build allows it to pass, I would say the issue is not in plugin application but rather in the way linting is wired and thus an Android problem.

@gradle/kotlin-dsl Are you aware of issues around `pluginManagement` vs `buildScript` declaration?

**Comment by StefMa** [comment]
I just created an issue on the [Android tracker](https://issuetracker.google.com/issues/122698934).
Maybe it's an issue in that task 🤷‍♂️ 

I also tried to find the code of this task in [googlesource](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/build-system/gradle-core/) but man... why they are not using github? 😂

**Comment by StefMa** [comment]
Old issue, but I just wanted to report that this issue doesn't happen with the "latest" versions of all dependencies anymore.
See also https://github.com/gradle/kotlin-dsl-samples/compare/master...StefMa:kotlin-dsl:pluginmanagment_issue-2024

Also reported to the Android issue tracker: https://issuetracker.google.com/issues/122698934#comment4
