### ISSUE TITLE
Task is not rerun though last execution failed if previous output is reproduced before the exception

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#8018]
With the following build script in an otherwise empty project you can reproduce the behavior:

```gradle
plugins {
    id 'java'
}

jar {
    doLast {
        if (project.findProperty('baz')) throw new RuntimeException('baz')
        archivePath.delete()
        archivePath.text = 'bar\n'
        if (project.findProperty('bam')) throw new RuntimeException('bam')
    }
}
```

I tested it with Gradle 2, 3, 4 and 5 and the output is similar, just the detail messages improved slightly.
But the behavior seems pretty inconsistent and unlogical and @oehme confirmed that this behavior is not like intended. The point is, that the last call should not be up-to-date as the previous run was failing.

2.14.1
======

* `rm -rf build .gradle`
* `./gradlew -i jar`
  * Executing task ':jar' due to: No history is available.
  * :jar completed.
* `./gradlew -i jar`
  * :jar UP-TO-DATE
  * :jar completed.
* `rm -f build/libs/*.jar`
* `./gradlew -i jar -P baz=true`
  * Executing task ':jar' due to: Output file ...\build\libs\foo.jar has changed. Output file ...\build\libs\foo.jar has been removed.
  * :jar FAILED
* `./gradlew -i jar -P baz=true`
  * Executing task ':jar' due to: Output file ...\build\libs\foo.jar has changed.
  * :jar FAILED
* `./gradlew -i jar`
  * Executing task ':jar' due to: Output file ...\build\libs\foo.jar has changed.
  * :jar completed.
* `rm -f build/libs/*.jar`
* `./gradlew -i jar -P bam=true`
  * Executing task ':jar' due to: Output file ...\build\libs\foo.jar has changed. Output file ...\build\libs\foo.jar has been removed.
  * :jar FAILED
* `./gradlew -i jar -P bam=true`
  * :jar UP-TO-DATE
  * :jar completed.

3.5
===

* `rm -rf build .gradle`
* `./gradlew -i jar`
  * Executing task ':jar' due to: No history is available.
  * :jar completed.
* `./gradlew -i jar`
  * :jar UP-TO-DATE
  * :jar completed.
* `rm -f build/libs/*.jar`
* `./gradlew -i jar -P baz=true`
  * Executing task ':jar' due to: Output property 'archivePath' file ...\build\libs\foo.jar has changed.
  * :jar FAILED
* `./gradlew -i jar -P baz=true`
  * Executing task ':jar' due to: Output property 'archivePath' file ...\build\libs\foo.jar has changed.
  * :jar FAILED
* `./gradlew -i jar`
  * Executing task ':jar' due to: Output property 'archivePath' file ...\build\libs\foo.jar has changed.
  * :jar completed.
* `rm -f build/libs/*.jar`
* `./gradlew -i jar -P bam=true`
  * Executing task ':jar' due to: Output property 'archivePath' file ...\build\libs\foo.jar has changed.
  * :jar FAILED
* `./gradlew -i jar -P bam=true`
  * :jar UP-TO-DATE
  * :jar completed.

4.10.2 & 5.0
===========

* `rm -rf build .gradle`
* `./gradlew -i jar`
  * Task ':jar' is not up-to-date because: No history is available.
  * :jar completed.
* `./gradlew -i jar`
  * :jar UP-TO-DATE
  * :jar completed.
* `rm -f build/libs/*.jar`
* `./gradlew -i jar -P baz=true`
  * Task ':jar' is not up-to-date because: Output property 'archivePath' file ...\build\libs\foo.jar has been removed.
  * :jar FAILED
* `./gradlew -i jar -P baz=true`
  * Task ':jar' is not up-to-date because: Task has failed previously.
  * :jar FAILED
* `./gradlew -i jar`
  * Task ':jar' is not up-to-date because: Task has failed previously.
  * :jar completed.
* `rm -f build/libs/*.jar`
* `./gradlew -i jar -P bam=true`
  * Task ':jar' is not up-to-date because: Output property 'archivePath' file ...\build\libs\foo.jar has been removed.
  * :jar FAILED
* `./gradlew -i jar -P bam=true`
  * :jar UP-TO-DATE
  * :jar completed.

**Comment by Vampire** [comment]
> IIUC, with Gradle 5.0, it is working as expected for you, except for the last gradlew -i jar -P bam=true?

Actually in all tested versions, yes.

> So our current logic does the following: If the task fails, save the fact that the task failed in the task history if the task changed any of the outputs.

Well, the task did change the outputs.
I guess you compare to the outputs after the last successful task execution, but if the intended logic is what you said, not what the code does, then maybe outputs before current execution should be compared against. In this case behavior of my test case would have been like expected.

> If there is no difference between the outputs from the last task execution and after the failed execution, then we don't change the task history and pretend it never tried to execute.

Ah, yes, my guess was correct. :-D
But I think it would be more intuitive to at least compare outputs before current execution against after failed, as in my showcase the task did some work and just happened to stop with the same result as the last successful execution.

> If the flag influences the outputs, it needs to be declared as an input.

Definitely, in this case there is no flag [making the Jedi gesture], the flags are only there to emulate failure conditions without changing the buildscript which would per-se be a change in inputs and cause the task to rerun.

> After having the explanations above, does the current behaviour break any use case you have? The behaviour seems to be correct, given the up-to-date logic Gradle uses (i.e. same inputs +same outputs -> task is up-to-date).

Not a concrete one, I just tried to verify what I told trejkaz in #1339 and stumbled upon this behavior while playing around. You and the code are maybe right in how it is done currently despite what I said above. I was just confused that the task failed and yet didn't re-run on re-execution like I was used to.

I guess usually a task will not produce the same result as the last successful run and then error out, especially if the failing action works on the actual outputs.
One situation I could imagine is, if the failing action does something additional that does not influence the output files like calling some remote api or whatever and it might be "wrong" if the task is not rerun in this case. But I guess in this case even comparing the output before and after the task could show equalness while the task is expected to be re-run. So in this case I guess it would be necessary to either have a separate `finalizedBy` task (are those run if the task that is being finalized is up-to-date?) or adding a "fake" output file that is written if the mandatory task was successful. For this it would probably be better if Gradle would support output properties, then no fake output file would be necessary.

> One thing we could consider is that we check if the failed task changed any of the output files while it executed (in your case it created foo.jar) and save the failed state if it did some changes, even if the final result of the failed task is the same as from the previous execution.

I'm now not sure anymore whether this makes more sense or whether the current logic is appropriate. :-/

**Comment by wolfs** [comment]
Let's close this issue since the behaviour is as expected.
