### ISSUE TITLE
Documentation should give guidance on using composite builds to simplify plugin development

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#8027]
Composite builds can simplify plugin development, however this is not obvious to people reading the documentation to learn how to implement a plugin.

### Expected Behavior

It is easier for plugin authors to discover the goodness of composite builds and how this feature can help with plugin development.

### Current Behavior

There's a sample that shows a basic scenario, but this is difficult to discover.

**Comment by bmuschko** [comment]
I [added this](https://guides.gradle.org/testing-gradle-plugins/#manual-tests) a while ago but maybe it should be cross-referenced in other places of the documentation.
