### ISSUE TITLE
Composite builds should fail when the same build is included multiple times

### ISSUE THREAD

**Issue by donat** [gradle/gradle#8031]
### Expected Behavior

Gradle should fail with an invalid configuration message when the same build included multiple times in the composite.

### Current Behavior

The following project layout builds successfully:

_A/settings.gradle_
```
includeBuild('../B')
includeBuild('../C')
```
_B/settings.gradle_
```
includeBuild('../C')
```
_C/settings.gradle_
```
rootProject.name = 'C'
```

### Context
The `EclipseProject` tooling model for a project similar as above [causes problems in Buildship](https://github.com/eclipse/buildship/issues/822). The model builder basically creates two `EclipseProject` instance for project `C`.

**Comment by adammurdoch** [comment]
This is a use case we want to support, to allow multiple builds to reference another shared build. We should fix this in buildship (and/or the tooling API), not remove support for this from the build tool.

**Comment by donat** [comment]
I agree. We should go with a fix on the IDE side. Let's follow-up on issue https://github.com/eclipse/buildship/issues/908.
