### ISSUE TITLE
Misplaced apostrophe in AbstractProjectSpec.java (English grammar correction)

### ISSUE THREAD

**Issue by karlrwjohnson** [gradle/gradle#8041]
*(Apologies in advance if I filled this out incorrectly. I'm doing my best, but this form is designed for bugs, not spelling changes, so it's a bit overkill in this case.)*

### Expected Behavior

When I receive a hint about unrelated builds, the phrase `If this is an unrelated build, it must have it's own settings file` should use "its" instead of "it's".

The word is being used in the possessive sense, whereas "it's" is reserved for contractions.

### Current Behavior

`Project directory (snipped) is not part of the build defined by settings file (snipped). If this is an unrelated build, it must have it's own settings file`

### Context

My multi-project build has mysteriously decided that the buildSrc directory is not part of the build for some reason, but I sense that's more information than necessary to reproduce.

### Steps to Reproduce (for bugs)

This is just a text issue; it shouldn't require a complex setup to reproduce. I received this error message because something was wrong in my environment, but I'm not yet sure what caused it. If I knew how to reproduce the issue, I wouldn't be seeing it.

**Comment by karlrwjohnson** [comment]
The change is a one-liner:
```
diff --git a/subprojects/core/src/main/java/org/gradle/initialization/AbstractProjectSpec.java b/subprojects/core/src/main/java/org/gradle/initialization/AbstractProjectSpec.java
index 5ba9d73b242..010f97d743e 100644
--- a/subprojects/core/src/main/java/org/gradle/initialization/AbstractProjectSpec.java
+++ b/subprojects/core/src/main/java/org/gradle/initialization/AbstractProjectSpec.java
@@ -23,7 +23,7 @@ import java.util.ArrayList;
 import java.util.List;
 
 public abstract class AbstractProjectSpec implements ProjectSpec {
-    private static final String UNRELATED_BUILD_HINT = " If this is an unrelated build, it must have it's own settings file.";
+    private static final String UNRELATED_BUILD_HINT = " If this is an unrelated build, it must have its own settings file.";
     public boolean containsProject(ProjectRegistry<? extends ProjectIdentifier> registry) {
         checkPreconditions(registry);
         List<ProjectIdentifier> matches = new ArrayList<ProjectIdentifier>();
```

**Comment by big-guy** [comment]
Thanks, feel free to [submit a PR](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for typos like this in the future.

You're getting this message because we require all builds to have a `settings.gradle`.  `buildSrc` is considered a separate build that provides plugins/configuration to the "main" build.
