### ISSUE TITLE
Allow missing `@Inject` on constructors when it is unambiguous which constructor to use

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#8044]
Currently we use JSR-330 semantics for constructor injection, which requires a `@Inject` annotation on a constructor that accepts parameters. For many Gradle types this seems to be pointless ceremony. This is particularly true for types implemented in Kotlin, where the convenient syntax for declaring constructors currently cannot be used.

### Expected Behavior

Either:

- When there is only one constructor on the type, use it.
- When there is only one constructor on the type that matches the given parameters, use it.

For other cases, still allow an `@Inject` annotation to be used to disambiguate between constructors.

### Current Behavior

Gradle is overly restrictive and prevents Kotlin conveniences being used.

**Comment by lacasseio** [comment]
I believe this is important and can be a source of confusion as `project.extensions.create` is able to create objects without the inject annotation on the constructor and not `objects.newInstance`.
