### ISSUE TITLE
Multi project build doesn't compile with Gradle 5.x

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#8045]
One of our multi project builds is currently failing to compile. 

### Expected Behavior

`./gradlew assemble` should compile as it does in Gradle 4.x

### Current Behavior

Fails compilation with:

```
> Task :views-json-testing-support:compileGroovy FAILED
startup failed:
/Users/graemerocher/dev/grails/views/json-testing-support/src/main/groovy/grails/views/json/test/JsonViewUnitTest.groovy: 6: unable to resolve class grails.plugin.json.view.test.TestRequestConfigurer
 @ line 6, column 1.
   import grails.plugin.json.view.test.TestRequestConfigurer
   ^

/Users/graemerocher/dev/grails/views/json-testing-support/src/main/groovy/grails/views/json/test/JsonViewUnitTest.groovy: 5: unable to resolve class grails.plugin.json.view.test.JsonRenderResult
 @ line 5, column 1.
   import grails.plugin.json.view.test.JsonRenderResult
   ^
```

### Context

This issue is blocking us trying to create the first milestone on Grails 4.x

### Steps to Reproduce (for bugs)

1. `git clone git@github.com:grails/grails-views.git`
2. `git checkout gradle-5`
3. `./gradlew assemble`

### Your Environment

* Gradle 5.0 and 5.1 rc1

**Comment by ljacomet** [comment]
Could you please make sure this is not a consequence of Gradle now separating `compile` and `runtime` scopes of artifacts with Maven metadata?
See this [breaking change note](https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:pom_compile_runtime_separation) for reference.
An easy way to figure that out would be to compare the output of `./gradlew dependencies --configuration compileClasspath` between the current Gradle version used by the project and 5.0

**Comment by graemerocher** [comment]
yes I already reviewed that. As far as I can see the `views-json-testing-support` module has a direct compile dependency on the `views-json` module:

```groovy
compile project(":views-json")
```

The classes that it cannot find during compilation are found in that module. In additional it is possible to compile only the `views-json-testing-support` if you compile only that project,  the compilation error occurs only if you run `./gradlew assemble` from the root project.

**Comment by oehme** [comment]
@ljacomet It's a project dependency, so this does not apply.

@graemerocher Have a look at the jar that is generated for your views-json project. It's a Spring Boot fat jar, not the normal project jar and thus it cannot be used to be compiled against. Seems like you are replacing the normal jar with the spring boot jar.

**Comment by graemerocher** [comment]
Wow, this must be a change in the boot plugin, sorry for the hassle.
