### ISSUE TITLE
Memory settings not done properly?

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#8046]
I've seen in the 5.0 release notes and user guide, that there should be max heap limits set automatically.
But if I run a build with no `org.gradle.jvmargs`, no `JAVA_OPTS` and no `GRADLE_OPTS` this seems to not work properly.
If I run with `--no-daemon` and in the build script `println(Runtime.getRuntime().maxMemory() / 1024 / 1024 / 1024)`, it displays on CircleCI that approx. 17 GiB max heap are used while the docker container is restricted to 4 GiB.
If I run without `--no-daemon` it displays the proper 0.5 GiB.
Or is it expected that the memory settings are not done in this case?
I didn't find a mention of that in the docs, just that the client VM is used if sufficient and otherwise a one-time daemon is spun up.
I run with `--no-daemon` as the build is run within an ad-hoc docker container, so there is absolutely no added value in building with the daemon as far as I understood.

**Comment by oehme** [comment]
Make sure you regenerated the wrapper script after upgrading, otherwise you still have the old one which didn't limit memory for the client VM.

**Comment by Vampire** [comment]
Ah, right, I just changed the properties file and didn't think about the wrapper for this quick test, will try it, thanks.
