### ISSUE TITLE
Dependencies defined in mixed (java/scala) module not available in dependent projects

### ISSUE THREAD

**Issue by h-ngo** [gradle/gradle#8048]
We defined some dependencies in a Java/Scala mixed module. However, these dependencies are not available in the dependent projects. We have to pull them in specifically in the dependent project. If we convert it to either Java or Scala only project, then all these dependencies will be visible in the dependent projects. 
Due to some business reasons, we have to keep the module as a mixed module. Any help would be greatly appreciated. 

Below is the snippet of the project setup. We created a simple projects to replicate the issue:

_Project B_
   |
   --- build.gradle:

       def javaScalaProjectNamePattern = /java-scala/

       subprojects { sub ->
          version = rootProject.version

         if (sub.name ==~ /$javaScalaProjectNamePattern/) 
         {
             apply plugin: "scala"
             dependencies {
                compile scala_library
                compile scala_reflect
                compile slf4j
                compile logback_classic
            
                testCompile junit
                testCompile mockito
                testCompile scalatest
          }
         }  
       } 
       else  {
        println "project $sub.name is not included correctly"
        throw new StopActionException("project ${sub.name} is not included correctly")
      }
     }

   _--- java-scala_
        |
      - - build.gradle:

           sourceSets.main.scala.srcDir 'src/main/java'
           sourceSets.main.java.srcDirs = []
           
           publishing {
             publications {
               maven(MavenPublication) {
                groupId project.group
                version project.version
                artifact jar
                artifact scalaSourcesJar
               }
             }
           }

          dependencies {
            compile "org.apache.camel:camel-kafka:2.23.0"
          }
           
_Project A_
 |
 --- build.gradle

 dependencies {
    compile('com.testB:java-scala:1.0.0-SNAPSHOT')
 }

_**org.apache.camel:camel-kafka:2.23.0 is missing in Project A. Have to specifically pull it in using compile "org.apache.camel:camel-kafka:2.23.0".**_

OS: Centos 6
IDE: Intellij
Gradle version: 4.4.
Build Scan: we are not using this feature.

**Comment by marcphilipp** [comment]
Where does Project A get the dependency from? A Maven repo? What does the POM look like?

**Comment by h-ngo** [comment]
All dependencies are pulled from MavenLocal.

The POM does indeed look wrong:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.testB</groupId>
<artifactId>java-scala</artifactId>
<version>1.0.0-SNAPSHOT</version>
</project>
```

Project B also has a Java-only module. And, the POM looks correct:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.testB</groupId>
<artifactId>java-only</artifactId>
<version>1.0.0-SNAPSHOT</version>
<dependencies>
<dependency>
<groupId>org.scala-lang</groupId>
<artifactId>scala-library</artifactId>
<version>2.12.6</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.scala-lang</groupId>
<artifactId>scala-reflect</artifactId>
<version>2.12.6</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-api</artifactId>
<version>1.7.12</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>ch.qos.logback</groupId>
<artifactId>logback-classic</artifactId>
<version>1.2.3</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>javax.transaction</groupId>
<artifactId>jta</artifactId>
<version>1.1</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.apache.camel</groupId>
<artifactId>camel-kafka</artifactId>
<version>2.23.0</version>
<scope>compile</scope>
</dependency>
</dependencies>
</project>
```

Any suggestion? Thanks

**Comment by ljacomet** [comment]
Looks like in your `java-scala` project, you do not select a `component` to be published.

Only if `MavenPublication.from(SoftwareComponent)` is called, will you have dependencies added from the project. Because the `scala` plugin builds on top of the `java` plugin, the component is simply named `java` and thus you need to `from(components.java)` in your publication.

**Comment by ljacomet** [comment]
Closing this as an answer was provided. Reopen if the issue still persists.
