### ISSUE TITLE
Application plugin adds in 'ant' and 'junit' to distribution for no apparent reason

### ISSUE THREAD

**Issue by bimargulies-google** [gradle/gradle#8052]
https://scans.gradle.com/s/3yaxo7o76i356/

### Expected Behavior

distribution built by application plugin will contain only my dependencies, not other jar files.

### Current Behavior

ant and junit are included in my distribution.

Git clone 

https://github.com/bimargulies-google/oltpbench/tree/kill-pom

and run gradle build.

Then examine the resulting build script to see what I see.

**Comment by big-guy** [comment]
There's a transitive dependency on ant and junit.

You can see this in the build scan:
https://scans.gradle.com/s/3yaxo7o76i356/dependencies?dependencies=ant&expandAll&focusedDependency=WzAsMSw2MCxbMCwwLFswXV1d&focusedDependencyView=dependents

ant is coming in through openjpa and junit is coming in through serp (which comes from openjpa).

You can also see this on the command-line with [dependencyInsight](https://docs.gradle.org/current/userguide/inspecting_dependencies.html#sec:identifying_reason_dependency_selection).

There are different ways to deal with this, but we have some docs for [managing transitive dependencies](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html).  You can exclude those particular dependencies, disable all transitive dependencies for openjpa, or something in-between.
