### ISSUE TITLE
buildscript can't be configure

### ISSUE THREAD

**Issue by Jonatha1983** [gradle/gradle#8053]
When using the buildScript block in a build.gradle file it behave differently  from other dsl elements

Expected Behavior
To be able to pass to  the buildScript an external Closure without having to pass the buildscript itself:

While this work fine:
```
buildscript {
       repositories{
             ....
        }
        dependencies{
            ....
        }
}
```
This does not work
```
def aClosure = {
       repositories{
             ....
        }
        dependencies{
            ....
        }
}

buildscript aClosure
```

### Current behavior
When using other DSL element such as project.afterEvaluated {} we are able to pass a closure defined externally  ( project.afterEvaluated aClosure ) but with buildScript no. 

### Context
It all started with problems we faced when we tried to use some groovy Classes among a large multiproject (500+ projects and lots of script plugins).  We saw that when we defined a Singelton we get multiple instyances,  because of different classLoader.
So we are now trying to align all using the buildscript and we want to do it in one place. 

We defined a clouser on the gradle.ext and we trying to configure the buildscript with it - but without passing the buildscript itself it aint working.

### Steps to Reproduce (for bugs)
build.gradle 
```
apply from aSecondBuildFile.gradle
```

aSecondbuildFiles.gradle
```
def bs = {
   //define repositories and dependencies
}

buildscript bs

// Erro cannot find bs property 
```

### Your Environment
Gradle 4.10.2
Java 1.8

**Comment by big-guy** [comment]
This is because `buildscript` needs to be treated specially and extracted from the build script file before we evaluate the file.

> We saw that when we define a Singelton obejct we get a duplication cause of different classLoaders, so we trying to allign a buildScript for all and we want to do it in one place. 

You should be able to do this by adding all of the build script dependencies to the root project.  The subprojects will inherit from that classloader.

**Comment by boaznahum** [comment]
subprojects but not external scripts (apply from:)
Seems this was closed too quickly
