### ISSUE TITLE
aspectj.gradle error

### ISSUE THREAD

**Issue by uooka** [gradle/gradle#8063]
Hi folks,

When trying to apply the aspectj.gradle plugin I am faced with the following error message.

* What went wrong:
A problem occurred evaluating root project 'test-bed'.
> Failed to apply plugin [id 'aspectj.gradle']
   > Could not create task ':compileAspect'.
      > Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

Gradle version 5.0
AspectJ version 1.9.1
aspectj.gradle plugin version 0.1.6

Anyone got any idea-ios?

**Comment by big-guy** [comment]
This was a property that was removed in Gradle 5.0 after being deprecated for Gradle 4.x.  There are several other AspectJ plugins you could try on the [plugin portal](https://plugins.gradle.org/search?term=aspectj).

related: https://github.com/gradle/gradle/issues/7861

**Comment by uooka** [comment]
Noice! 

I'm using the following [plugin](https://plugins.gradle.org/plugin/io.freefair.aspectj.post-compile-weaving).

**Comment by Amrkamel1** [comment]
@uooka 

Can you please provide ur build.gradle 
Im facing an issue with new plugin as well : 

 Could not find any public constructor for class io.freefair.gradle.plugins.AspectJExtension_Decorated which accepts parameters [].

"buildscript {

    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "io.freefair.gradle:aspectj-plugin:3.5.1"
    }
}

plugins {
    id 'java'
    id 'ru.vyarus.quality' version '2.2.0'
    id "io.qameta.allure" version "2.7.0"
//    id("aspectj.gradle") version "0.1.6" apply false
    id "io.freefair.aspectj.post-compile-weaving" version "3.5.1" apply false



}
ext {
    aspectjVersion = '1.9.2'
}


apply plugin: 'java'
apply plugin: 'idea'
apply plugin: "io.qameta.allure"
apply plugin: "io.freefair.aspectj.post-compile-weaving" 

"

**Comment by raghavpn** [comment]
@Amrkamel1  Please can you share your build.gradle if its fixed?

**Comment by wangmingliang-ms** [comment]
same here
```
A problem occurred evaluating root project '****'.
> Failed to apply plugin [class 'io.freefair.gradle.plugins.aspectj.AspectJBasePlugin']
   > Could not create an instance of type io.freefair.gradle.plugins.aspectj.AspectJExtension_Decorated.
      > Could not find any public constructor for class io.freefair.gradle.plugins.aspectj.AspectJExtension_Decorated which accepts parameters [].
```
