### ISSUE TITLE
sporadic NumberFormatException in MemInfoOsMemoryInfo.parseMeminfoBytes

### ISSUE THREAD

**Issue by Temennigru** [gradle/gradle#8068]
Our testing system has been reporting sporadic NumberFormatException: null errors on our routine gradle tests, coming from internal gradle code. The only information we have is the stack trace, as reproducing the bug has been problematic.

> Caused by: org.gradle.internal.service.ServiceCreationException: Could not create service of type WorkerDaemonClientsManager using GradleUserHomeServices.createWorkerDaemonClientsManager().
> 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:823)
> 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:774)
> 	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:568)
> 	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:625)
> 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:787)
> 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:773)
> 	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:568)
> 	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:625)
> 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.assembleParameters(DefaultServiceRegistry.java:787)
> 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:773)
> 	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectServiceProvider.getInstance(DefaultServiceRegistry.java:568)
> 	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:625)
> 	at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:292)
> 	at org.gradle.api.internal.DependencyInjectingInstantiator.convertParameters(DependencyInjectingInstantiator.java:118)
> 	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:63)
> 	at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:72)
> 	... 52 more
> Caused by: java.lang.NumberFormatException: null
> 	at java.lang.Long.parseLong(Long.java:552)
> 	at java.lang.Long.parseLong(Long.java:631)
> 	at org.gradle.process.internal.health.memory.MemInfoOsMemoryInfo.parseMeminfoBytes(MemInfoOsMemoryInfo.java:94)
> 	at org.gradle.process.internal.health.memory.MemInfoOsMemoryInfo.getOsSnapshotFromMemInfo(MemInfoOsMemoryInfo.java:78)
> 	at org.gradle.process.internal.health.memory.MemInfoOsMemoryInfo.getOsSnapshot(MemInfoOsMemoryInfo.java:49)
> 	at org.gradle.process.internal.health.memory.DefaultOsMemoryInfo.getOsSnapshot(DefaultOsMemoryInfo.java:37)
> 	at org.gradle.workers.internal.WorkerDaemonClientsManager.getTotalPhysicalMemory(WorkerDaemonClientsManager.java:136)
> 	at org.gradle.workers.internal.WorkerDaemonClientsManager.<init>(WorkerDaemonClientsManager.java:75)
> 	at org.gradle.workers.internal.WorkersServices$GradleUserHomeServices.createWorkerDaemonClientsManager(WorkersServices.java:87)
> 	at sun.reflect.GeneratedMethodAccessor218.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
> 	at org.gradle.internal.service.ReflectionBasedServiceMethod.invoke(ReflectionBasedServiceMethod.java:35)
> 	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:821)
> 	... 67 more

**Comment by big-guy** [comment]
@Temennigru which OS are you seeing this on?

What does `/proc/meminfo` look like for you?

**Comment by Temennigru** [comment]
Hey @big-guy, we are running glinux, a variant of debian, and I don't have access to the machines running the tests.

**Comment by big-guy** [comment]
Does the build that fails use included builds/composite build?

Is the failure happening at the start of a build or just sometime during it?

**Comment by Temennigru** [comment]
I don't think this specific test uses composite build, as it is a very basic test.

And it seems to be failing when creating a task, not when building:

when calling Project.getTasks().create()

TaskCreationException: Could not create task ':test'.
Caused by: org.gradle.api.tasks.TaskInstantiationException: Could not create task of type 'Example'.

**Comment by big-guy** [comment]
OK.  Does the build use `GradleBuild` tasks?

Does the `Example` task have any constructor arguments or injected services (annotated with `@Inject`)?

**Comment by Temennigru** [comment]
Hey @big-guy, sorry for the delay.

What exactly do you mean by a GradleBuild task?

Example does have @Inject, and it receives a WorkerExecutor object.

Here is the test in question:

https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/gradle-core/src/test/java/com/android/build/gradle/tasks/MergeResourcesTest.java

@line 73

**Comment by big-guy** [comment]
OK, I think I found something.  We were sharing the Matcher instance across threads.  This will be included in 5.2 and should show up in a nightly in ~a day.
