### ISSUE TITLE
A Provider that implements HasMultipleValues should allow removing elements

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#8071]
### Expected Behavior

The `HasMultipleValues` API should provide a way to remove one, many or all elements.

```
void remove(T element);
void removeAll(Collection<T> elements);
void clear();
```

### Current Behavior

A user can only add new elements to a `HasMultipleValues` but not remove any of them.

### Context

Convention plugins may populate default values for fields of type `SetProperty` or `ListProperty`. Sometimes users may want to manipulate those values e.g. remove specific ones or replace them with other ones.

**Comment by rkrisztian** [comment]
I am missing this one too, currently it is quite cumbersome to remove values:

```
def newList = new ArrayList<String>(myListProperty.get())
newList.remove 'myElement'
myListProperty.set newList
```

**Comment by rkrisztian** [comment]
I don't feel like letting this one go. The reason in the Context does not feel like bad practice to me.
