### ISSUE TITLE
Update DSL reference to show `defaultTasks()` method

### ISSUE THREAD

**Issue by pledbrook** [gradle/gradle#8072]
At some point, it seems that `defaultTasks()` was added as a concrete method to `Project`. The [API Javadocs](https://docs.gradle.org/release-nightly/javadoc/org/gradle/api/Project.html#defaultTasks(java.lang.String...)) reflect this, but the DSL reference does not.

**Edit** I was wrong about the "magic method" reference in the class Javadoc. That seems to have been updated.

**Comment by big-guy** [comment]
Done in https://github.com/gradle/gradle/commit/b6fe036e7fc6bd966a6ced0b887d6f963bfcce13
