### ISSUE TITLE
Gradle 5.1 incompatible change in behaviour of task inputs.files.asFileTree.matching -it doesn't filter

### ISSUE THREAD

**Issue by boaznahum** [gradle/gradle#8077]
Gradle 5.1rc2 , there is a change in behaviour of task inputs.files.asFileTree.matching -it doesn't filter

### The code below demonstrates it:

```
// create some input files
tasks.register("gen-dir") { t->

    def dir = file("inputs").toPath()
    t.outputs.dir dir

    doLast {
        delete dir
        Files.createDirectories(dir.resolve("l\\schema\\resources")).resolve("a.xsd").toFile().text = "x"

        Files.createDirectories(dir.resolve("l\\bad\\place")).resolve("b.xsd").toFile().text = "x"
    }
}
tasks.register("code-gen") { t->

    t.group "code-gen"

    t.dependsOn "gen-dir"

    t.inputs.files tasks.named("gen-dir")

    // this file is not filtered in gradle 5.1rc 
    t.inputs.file buildscript.sourceFile

    doLast {

        def inputFiles = t.inputs.files.asFileTree

        logger.quiet "original=\n${inputFiles.asFileTree.join("\n")}";

        PatternSet sourceFilter = new PatternSet().include('**/schema/resources/*.xsd')

        def filtered= inputFiles.asFileTree.matching(sourceFilter);

        logger.quiet "filtered=\n${filtered.join("\n")}";

    }
}
```
### Context
We take the task input files and filtering them, doing some processing(code generation) on the results

### Expected Behavior
In gradle 4.10.2 the output is:
```
original=
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\inputs\l\bad\place\b.xsd
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\inputs\l\schema\resources\a.xsd
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\build.gradle
filtered=
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\inputs\l\schema\resources\a.xsd
```
Indeed we get the right results, only files that match the filter '**/schema/resources/*.xsd' are included.

### Current Behavior
In gradle 5.1rc2 , , the single file that is added to the inputs is not filtred:
```
original=
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\inputs\l\bad\place\b.xsd
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\inputs\l\schema\resources\a.xsd
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\build.gradle
filtered=
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\inputs\l\schema\resources\a.xsd
F:\views\gradle-issues\gradle5.issue.taskinputs.matching\build.gradle
```

### Steps to Reproduce (for bugs)
Simply run the attached 
[code.zip](https://github.com/gradle/gradle/files/2690586/code.zip)

code above(task cod-gen)

### Your Environment
------------------------------------------------------------
Gradle 5.1-rc-2
------------------------------------------------------------

Build time:   2018-12-17 22:42:01 UTC
Revision:     4f93941ff2f23ed981b9416a66af36ab0a8ef4de

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Windows 10 10.0 amd64

 * Build scan URL:  https://gradle.com/s/izwhcrkahafum

**Comment by boaznahum** [comment]
@wolfs thanks
This is only synthetic example. In 'real' life the 'files' added are provided by some other plugin, The developer is not aware of the internal implementation, it can be combination of some root directories and some single files, this bring me to more important point:
  FileTree#matching(PatternFilterable)
should be behave as documented, but I see you already open a bug so we are aligned :)

I'm adding some script as input because  the task invoke a closure defined in this file:
```
//In root project (we apply once for better performance):
def codeFile = "${viewRoot}/QBuildSystemCore/gradle/scripts/code_generation/xsdCodeGen.gradle"
apply from: codeFile

// In specific project & task 
    inputs.file codeFile 
    doLast {
      // execute some closure defined in the above applied file
      rootProject.ext.xsdCodeGen(...)
   }
```

Is there a better way to express this dependency ? (I know converting to plugin is more elegant ...)

Thanks
Boaz

**Comment by wolfs** [comment]
The problem should be fixed via https://github.com/gradle/gradle/pull/8083, i.e. `matching` will now also work on the root regular files.

**Comment by big-guy** [comment]
@boaznahum could you try `5.1-20181219204953+0000`?  You can upgrade with `gradle wrapper --gradle-version= 5.1-20181219204953+0000`
