### ISSUE TITLE
wrapper task fails when the version 5.1 is specified.

### ISSUE THREAD

**Issue by ahamana** [gradle/gradle#8078]
### Current Behavior

wrapper task fail when the version 5.1(5.1-rc-1/5.1-rc-2) is specified.
\* When the version 5.0 is specified, an error does not occur.

```
.\gradlew.bat wrapper --gradle-version=5.1-rc-2
> Task :wrapper FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wrapper'.
> Failed to write wrapper JAR to C:\Users\xxx\gradle\wrapper\gradle-wrapper.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
```

### Your Environment
WIndows 10

**Comment by wolfs** [comment]
@ahamana Thank you for reporting. Could you provide a stack trace of the failure or maybe a build scan? What version of Gradle are you using to run the build with the `:wrapper` task?

**Comment by ahamana** [comment]
@wolfs I use the version 5.0 to run the build with the wrapper task.

The stack trace is here.
\* The Japanese message "プロセスはファイルにアクセスできません。別のプロセスが使用中です。" in the stack trace means that "The process can not access the file. Another process is in use.".
[stacktrace.zip](https://github.com/gradle/gradle/files/2690676/stacktrace.zip)

**Comment by ahamana** [comment]
@wolfs The below cases work differently with the same command.

This case is success.
```
.\gradlew.bat wrapper --gradle-version=5.1-rc-2
Downloading https://services.gradle.org/distributions/gradle-5.0-bin.zip
.................................................................................
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

BUILD SUCCESSFUL in 44s
```

This case is failure.
```
.\gradlew.bat wrapper --gradle-version=5.1-rc-2
Downloading https://services.gradle.org/distributions/gradle-5.1-rc-2-bin.zip
.................................................................................
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
> Task :wrapper FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wrapper'.
> Failed to write wrapper JAR to C:\Users\xxx\gradle\wrapper\gradle-wrapper.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
1 actionable task: 1 executed
```

**Comment by ahamana** [comment]
@marcphilipp Many thanks for checking quickly.

**Comment by big-guy** [comment]
@ahamana could you try `5.1-20181219204953+0000`?  You can upgrade with `gradle wrapper --gradle-version= 5.1-20181219204953+0000`

**Comment by ahamana** [comment]
@big-guy The wrapper task works fine. Thanks for fixing the issue quickly.
