### ISSUE TITLE
Generated pom for a project with a project dependency on a Java Platform is invalid

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#8085]
### Expected Behavior

When a [Java Platform](https://docs.gradle.org/nightly/userguide/java_platform_plugin.html) is consumed via a `project` dependency, the pom that's generated by a `MavenPublication` will import the Platform's bom into its `<dependencyManagement>`.

### Current Behavior

The dependency for the Platform is a regular dependency which cannot be resolved. Other regular dependencies are declared without a version so they also cannot be resolved.

### Context

I'm trying to define a Java Platform in a multi-project build, consume that Platform elsewhere in the same build, and then publish working Maven metadata for all the build's projects.

### Steps to Reproduce (for bugs)

The problem can be reproduced using the sample project in [this repository](https://github.com/wilkinsona/enforced-platform-problem).

### Your Environment
 * Build scan URL: https://gradle.com/s/4ycr2n4dmz2qq

**Comment by ljacomet** [comment]
Thanks for the bug report, this is indeed a forgotten aspect of the support added for #7945
