### ISSUE TITLE
Depend on individual Groovy libraries instead of groovy-all

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#8087]
Gradle used to depend on `groovy-all.jar` that contained everything from Groovy, including all its shaded third-party dependencies. Gradle used to expose this JAR as part of its API, too.

Since version 2.5, Groovy does not publish such a JAR anymore, and instead provides only a POM that declares a dependent on most (but not all) Groovy JARs.

For Gradle 5.0 we tried to switch to the new approach, i.e. to make Gradle depend on individual Groovy JARs (see https://github.com/gradle/gradle/pull/6324). However, this has proven difficult.

Ultimately, we chose to go with a workaround, and reproduce a `groovy-all.jar` of sorts: with some more code from Groovy than the official `groovy-all.pom` would declare, and without any of the third-party dependencies. (See https://github.com/gradle/gradle-groovy-all.) This is a hack that got us onto Groovy 2.5, but we should do better.

This issue is about cleaning up this mess, and getting us to depend on actual Groovy libs and their dependencies.

Some of the problems encountered in https://github.com/gradle/gradle/pull/6324:

- [ ] with many new libraries on the classpath we had issues with forking workers on Windows because of command-line length reaching 32 KB

**Comment by lptr** [comment]
This is a pre-requisite to upgrading to Gradle 3.0, so let's keep this open.

**Comment by jjohannes** [comment]
This has been solved for Gradle 7.0 by #16193.

**Comment by lptr** [comment]
Yay! \o/
