### ISSUE TITLE
gradle 5.0 have a problem with Android Studio 3.2.1

### ISSUE THREAD

**Issue by stanislavdimov** [gradle/gradle#8088]
### Expected Behavior

Expected -> Build project

### Current Behavior

Curent -> Not Build! Generate ERROR

### Context

Caused by: java.lang.AbstractMethodError: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

### Steps to Reproduce (for bugs)

Android studio 3.2.1. with Gradle ver 5.0
I go back to Gradle ver 4.10.3 and I do not have any problem!

### Your Environment

PC , OS Windows 10 x64, Intel core i5-8600k, Coffe Lake, Java 11.0

 * Build scan URL:

**Comment by stanislavdimov** [comment]
Caused by: java.lang.AbstractMethodError: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;
Android studio 3.2.1. with Gradle ver 5.0
I go back to Gradle ver 4.10.3 and I do not have any problem!
PC , OS Windows 10 x64, Intel core i5-8600k, Coffe Lake, Java 11.0

**Comment by ljacomet** [comment]
Gradle 5.0 _is not_ compatible with Android 3.2.

This is indicated in the [upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_4.html).

Note that combine effort from the Gradle and Android team may end up making Android 3.3 compatible, so you may not have to wait until 3.4 is out.

**Comment by MaxEgg** [comment]
Same problem with intelliJ

**Comment by stanislavdimov** [comment]
I am migrate to ver android studio 3.3R and to this moment I do not have problem with gradle 5.0q but I recomende you to build you project with gradle ver 4.10.
How m-r Jacomet write Gradle NOT compatible with Android Studio 3.2.
To IntelleJ IDEq I see that they have a big problem with visual component preview, must write every time for new name on Theme listing (Base) or change name  AppCompat...to alpha1

**Comment by stanislavdimov** [comment]
some help..only for this picture do not understand where is problem
do you see log file for errors?

**Comment by SkyFlyTang** [comment]
remove .gradle

**Comment by kvbutler** [comment]
Yeah rollback to Gradle 4.8 works okay
