### ISSUE TITLE
Native builds don't log warnings unless the build fails.

### ISSUE THREAD

**Issue by donalmacc** [gradle/gradle#810]
### Expected Behavior
If the compiler detects a warning, the user should be notified in the build, even if the build is succesful

### Current Behavior
If a warning is generated, it is suppressed unless the build fails. This has been discussed before [on the forums](https://discuss.gradle.org/t/native-how-can-i-get-compile-warnings-printed-in-the-console-window/11484/4)

### Steps to Reproduce (for bugs)
If running on windows, 
```#include <iostream>

int main()
{
	return 0;
}
```
and `build.gradle`
```apply plugin: 'cpp'

model {

    components {
        Main(NativeExecutableSpec) {
            sources {
                cpp{
                    source{
                        srcDirs "src"
                        include "**/*.cpp"
                    }
                }
            }
        }
    }

}
```
generates a warning by default with MSVC 2013: 
`warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc`
If the compile is successful, the warning is suppressed. remove the semicolon from `return 0` and the build fails, but also logs the warning.

### Your Environment
Gradle 3.1 
Windows 10 pro x64
MSVC 2013 and 2015. 

Can repro on debian jessie using gradle 3.1, with gcc 4.9 using a more complex example.

**Comment by lacasseio** [comment]
Thanks @donalmacc for the report. To comment further on this issue, this can be seen as a regression when `BuildOperationLogger` was introduced but that modification was a necessity to fix interleaving logs from the parallel compilation. The current workaround would be to use `/WX` flag which "treats all warning as errors" for both the [compiler](https://msdn.microsoft.com/en-us/library/thxezb7y.aspx) and the [linker](https://msdn.microsoft.com/en-us/library/ms235592.aspx).

**Comment by big-guy** [comment]
To provide a little bit of history, this was something we did intentionally (to hide all output from the underlying tool) until we could find something better. The output was pretty useless when it was all jumbled together.

**Comment by lacasseio** [comment]
We could probably print an excerpt of the output (just like when there is an error) all the time. This way we could at least see some warning. Better modeling could be done to grab and display the warning message in a more IDE friendly output. However, there is also the possibility to improve the integration of Gradle with Visual Studio. @donalmacc, could you comment on the use case for log warning? Are they needed in the context of the CLI or the IDE?

**Comment by donalmacc** [comment]
Hi Daniel
Apologies for the delay getting back to you. I would argue that a jumbled/interleaved output is better than no output whatsoever. If I put a print statement in a closure and its executed in parallel, It's logged, albeit not in order. I'm actually quite shocked that the solution to this was to suppress the output of the tools.

@lacasseio Ideally we would have it working in both IDE and CLI builds. We have developers using the IDE for builds, and we have CI machines using CLI builds. If the developers and CI builds are receiving different information, that's not good.

**Comment by lacasseio** [comment]
Good point @donalmacc. The discussion we had internally was to show compiler output on the console, but not interleave the output of parallel compilations. Gradle should collect the output for a compiler invocation as it does now, and write it to the console atomically once the compiler invocation has completed.

**Comment by donalmacc** [comment]
Ideally it would output in-progress, (of course), but having it all flushed after the compile has completed would do perfectly.

**Comment by big-guy** [comment]
Issue moved to [gradle/gradle-native #495](https://github.com/gradle/gradle-native/issues/495) via [**ZenHub**](https://www.zenhub.com/)
