### ISSUE TITLE
BOM support seems incomplete in gradle maven plugin

### ISSUE THREAD

**Issue by cdietrich** [gradle/gradle#8105]
Gradle since version 5.0 support maven boms. but the poms generated by the gradle maven plugin dont reflect that

### Expected Behavior

if dependencies of a gradle module are resolved agains a bom then the generated pom file by the gradle maven plugin should reflect them.

### Current Behavior

the generated poms dont have a dependency management

```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>something</groupId>
  <artifactId>gradle-broken-bom-maven-dependencymanagement</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-dependencies</artifactId>
      <version>1.5.8.RELEASE</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>dom4j</groupId>
      <artifactId>dom4j</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>
```

### Steps to Reproduce (for bugs)

here is a sample project
https://github.com/cdietrich/gradle-broken-bom-maven-dependencymanagement

### Your Environment

 * Build scan URL: https://gradle.com/s/vx4s5nmwmjeya

any os. happens with latest gralde nightly too

**Comment by melix** [comment]
The `maven` plugin is deprecated and BOM support is not implemented with this plugin. Please use `maven-publish` instead.
