### ISSUE TITLE
Failed to load native library 'libnative-platform.so' for Linux amd64.

### ISSUE THREAD

**Issue by Beau-1983** [gradle/gradle#8107]
beau@BeauPC:/opt$ sudo su -
[sudo] beau 的密码： 
root@BeauPC:~# gradle -v

------------------------------------------------------------
Gradle 5.1-rc-2
------------------------------------------------------------

Build time:   2018-12-17 22:42:01 UTC
Revision:     4f93941ff2f23ed981b9416a66af36ab0a8ef4de

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.15.0-43-generic amd64

root@BeauPC:~# 
root@BeauPC:~# exit 
注销
beau@BeauPC:/opt$ gradle -v

FAILURE: Build failed with an exception.

* What went wrong:
Failed to load native library 'libnative-platform.so' for Linux amd64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
beau@BeauPC:/opt$

**Comment by Beau-1983** [comment]
when i use a normal  user (not root ) to run gradle -v ,it outprint "Failed to load native library 'libnative-platform.so' for Linux amd64.", is anyone who can help me to resolve this problem? thanks!

please send me a email to 462620105@qq.com, thats very kind of u!
this is my first time to learn gradle by myself.

**Comment by Beau-1983** [comment]
by the way ,my  system is ubuntu 18.04

**Comment by big-guy** [comment]
@Beau-1983 My best guess is that there's some kind of permissions issue.  Can you try running with `-g gradle-user-home` and see if it works? If so, that means your `~/.gradle` directory may have the wrong permissions.

Does running with `-s` give you a longer stacktrace you can share?

**Comment by ghale** [comment]
Closing this as there was no response from the poster.

**Comment by GabrielBB** [comment]
@big-guy Adding `-g gradle-user-home` worked for me on dockerized Jenkins:

`/var/jenkins_home/tools/hudson.plugins.gradle.GradleInstallation/gradle_4/bin/gradle bootJar -g gradle-user-home`

**Comment by manueljordan** [comment]
For Ubuntu 

I have installed Gradle 7.2 and the `repository` directory in `/opt/gradle/` to be shared for some users:

Therefore:

```
/opt/gradle/
      7.2        rwxr-xr-x root root
      repository rwxr-xr-x root root
```
Where each directory has ` rwxr-xr-x root root`, when I execute `gradle --version` appears

```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Could not initialize native services.
   > Failed to load native library 'libnative-platform.so' for Linux amd64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

If I use: `gradle --version -g ~/.gradle` it works fine - therefore it is an access permission problem/situation for each _non-root_ user/group, but even when I created a common group (`developer`) for the users and added `+w` to the common group for both - I mean

```
/opt/gradle/
      7.2        rwxrwxr-x root developer
      repository rwxrwxr-x root developer

```
appears the same error - the goal is share among the users the same repository access.

What is missing to accomplish this goal?

**Comment by npivaut** [comment]
sudo chmod 777 /tmp/gradle_cache 
sudo chmod 777 /tmp/gradle_dist

**Comment by Qian-MoBai** [comment]
I also encountered the above issue. After investigation, the problem occurred because I used a variable when setting GRADLE_USER_HOME. My original setting was `$ENV/Repository/GradleRepo`. After changing it to an absolute path, it worked.
