### ISSUE TITLE
Add ability to configure the application plugin with an arbitrary source set

### ISSUE THREAD

**Issue by sedovalx** [gradle/gradle#8113]
Right now the name of the `main` source set of the java plugin is hardcoded into the `ApplicationPlugin`. Ideally, it should be possible to provide the classpath for the `run` task via the plugin configuration. 

### Expected Behavior
The configuration of the application plugin should have a property to specify the source set for the classpath of the `run` task.

### Current Behavior
The `main` source set is hardcoded in the `ApplicationPlugin`, so the classpath for the `run` task can't be changed.

### Context
The problem that I'm trying to solve is to run the JVM artefacts of the `kotlin-multiplatform` plugin with the `application` plugin. The source set of the artefacts has `jvmMain` name.
Also, there is a [SO ticket](https://stackoverflow.com/questions/47888015/gradle-application-plugin-with-main-class-in-non-main-source-set) with a similar request.

### Steps to Reproduce (for bugs)
- Apply the [kotlin-multiplatform](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html) plugin
- Configure the plugin with the jvm target, the `jvmMain` source set is auto-created
- Create `src/jvmMain/kotlin/sample/App.kt` file with the `main` method
- Apply the `application` plugin
- Configure the application plugin to use the `sample.AppKt` main class
- Try to run the `run` task

### Your Environment
Gradle 5.0
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Kotlin 1.3.10

**Comment by ljacomet** [comment]
Note that you can update the configuration of the `run` task added by the plugin, to update its classpath property:
```
tasks.named('run', JavaExec) {
    classpath = <wanted classpath>
}
```
The above will work as long as it happens after `Application` plugin is applied.

Note that there is another hard coded information: the configuration to be used to source the `lib` content of the application distribution, which defaults to `runtimeClasspath`.

**Comment by Xerus2000** [comment]
I have the exact same problem as @sedovalx and wanted to use the workaround from @ljacomet, but I have no clue how to get the classpath of a kotlin sourceSet.
I have tried something like this, but it doesn't find the executable:
```kotlin
tasks {
    run.configure {
        classpath = kotlin.sourceSets.getByName("jvmMain").kotlin
    }
}
```

**Comment by tom-power** [comment]
Hi `sourceSets.test.runtimeClasspath` works for me

**Comment by yschimke** [comment]
I'm getting errors trying to use application plugin with a kotlin multiplatform project, and I suspect it is because the sourceset to use is jvmMain instead of main.
