### ISSUE TITLE
@InputFiles and @InputDirectories with order preserved

### ISSUE THREAD

**Issue by grv87** [gradle/gradle#8132]
### Expected Behavior
* `@InputFiles` or `@InputDirectories` could be configured to preserve order of items.
For example, with another annotation accepting `FileNormalizer` class
* There is built-in `FileNormalizer` that preserves order, or it is obvious for users how to implement custom `FileNormalizer`

### Current Behavior
* `FileNormalizer` could be specified with `TaskInputFilePropertyBuilder` instance only. There is no way to add `FileNormalizer` to property annotated with `@InputFiles` or `@InputDirectories`
* There is no built-in order-preserving `FileNormalizer` (at least, not in public API)
* `FileNormalizer` interface has no methods, and it is not obvious for users how to implement custom normalizer
* It is not obvious that the order is not preserved when `List` (vs `Set`) is used

### Context
I'm writing a plugin wrapping another tool. The plugin parses that tool's configuration files to Java/Groovy classes, and Gradle annotations mark properties that are actual inputs and outputs.
The problematic property is a list of scripts that should be executed, in specified order.

**Comment by lptr** [comment]
This is a sort of duplicate of #8491.

**Comment by grv87** [comment]
@lptr, agree. I'm closing this as duplicate.
