### ISSUE TITLE
Custom Attribute types lead to memory leak

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#8142]
See https://github.com/gradle/gradle/blob/master/subprojects/model-core/src/main/java/org/gradle/api/internal/model/NamedObjectInstantiator.java#L57

This means that the Android plugin classes can never be garbage collected (e.g. on buildSrc changes). leading to metaspace leaks. Even on simple projects this can break the daemon after only a few buildSrc changes.

I don't see why we use strong references here, as we already have a classloader cache that keeps them alive across builds until they are no longer needed. The cache above could thus safely use weak references.

**Comment by big-guy** [comment]
Is this serious enough for a 5.1.1, if we can get 5.2 out by February?

How quickly does this manifest itself as a failure?

**Comment by adammurdoch** [comment]
@melix Thanks for fixing this. I was going to look at it this morning and it's fixed already.

I think in general we should avoid ad hoc, one-off solutions to these caching problems and try to make sure we solve the problem in the same way each place that the problem existing, by reusing the same code. For example, we have 3 different solutions to the problem of holding state for generated classes, one for each place we do this. Nothing we should change for the release, but I might look at cleaning this up in master.

**Comment by JLLeitschuh** [comment]
> Is this serious enough for a 5.1.1, if we can get 5.2 out by February?

For someone who's actively developing a build, it basically makes the build slower & slower every run. It's really noticeable after very few re-runs and then you start getting the `Expiring Daemon because JVM Tenured space is exhausted` at which point you're better killing your current build than waiting for it because it will be so slow from that point forward.

**Comment by melix** [comment]
@adammurdoch It seems the smoke test is still failing under some (unclear) circumstances, so the fix is not perfect. Would you mind taking this over since you had ideas how to do it properly?

**Comment by melix** [comment]
Damn, I was looking at https://builds.gradle.org/viewLog.html?buildId=18883231&buildTypeId=Gradle_Check_Soak_Java11_Openjdk_Linux_0

**Comment by adammurdoch** [comment]
My plan was only to take the fix and use it elsewhere, not to change how it works. The only thing I would change is how we handle unrecognised class loaders (which could be just to deprecate support for them).

**Comment by oehme** [comment]
Closing since the tests are passing.
