### ISSUE TITLE
Dtest.debug seems ignored

### ISSUE THREAD

**Issue by EmteeW** [gradle/gradle#8156]
I couldn't find documentation stating this to be deprecated, rather, I found 5.0 documentation claiming both should work, so....

C:\GRADLE\gradle-5.0\bin\gradle :cleanTest :test --tests com.me.MyClass* -Dtest.debug
(above does not wait, runs test successfully, exits without attachment)

C:\GRADLE\gradle-5.0\bin\gradle :cleanTest :test --tests com.me.MyClass* --debug-jvm
(waits for debugger attachment, can be successfully attached)

Windows 10, JDK 1.8_181

Can repro?

**Comment by GFriedrich** [comment]
Looks like you didn't search hard enough: There is a deprecation info at https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#potential_breaking_changes
> The -Dtest.debug command-line option has been removed — use the --debug-jvm option instead.

> I found 5.0 documentation claiming both should work, so....
Maybe you can tell where you found the "-Dtest.debug" option - that would be a documention error then.

**Comment by EmteeW** [comment]
https://docs.gradle.org/current/userguide/java_testing.html#sec:debugging_java_tests

At end:
"You can either set the Test.getDebug() property to true or use the --debug-jvm command line option"

I guess now in hindsight I just assumed that meant the property was still "public" and could be set via command line.  It must have melded in my head with all the other (more stale) information out there recommending  it (think Stackoverflow and similar).

At any rate, I was trying to figure out where I needed to submit a ticket.  I wasn't sure this was a bug, and had posted it to forums first, but got no traction.  I need to submit the issue to: https://github.com/kelemen/netbeans-gradle-project

...because that is how it is attempting to run debug-test.  There is a workaround to configure the plugin to make the process "attach" to the debugger, and those cmdline args/options still work fine.

Thanks for quick response!  Gradle is Great.  I'll see if I can get that IDE plugin back on track, and keep the House of Gradle clean ;)
