### ISSUE TITLE
Provide a build aborted/cancelled listener/hook

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#8159]
### Expected Behavior
Have a method in `BuildListener` or somewhere else that allows to hook into the build lifecycle when a build is cancelled or aborted, for example CTLR + C.

### Current Behavior
There isn't a public API for this. I believe the suggested solution would be:

```
 Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Clean shutdown");
        }));
```

However, this is getting executed every time the JVM is shutdown (successful builds included). 

### Context
We have the need to execute some logic when a build is cancelled, for example via a Jenkins job that got aborted. This way, we could cleanup some resources or interact with 3rd party services that we use for our gradle plugins.

**Comment by rpalcolea** [comment]
Related to https://github.com/gradle/gradle/issues/1128

**Comment by coder82** [comment]
This is an annoying issue when working with servers, the shutdowns hooks do not work and I don't want to build without daemon support. It's very much needed to exec some custom code upon build termination.

**Comment by oehme** [comment]
Does `BuildListener#buildFinished` not work? It should provide you a `BuildCancelledException` as the `failure`.

**Comment by coder82** [comment]
gradle.buildFinished { buildResult ->
    println "BUILD FINISHED"
    println "build failure - " + buildResult.failure
}

This doesn't print anything on CTRL+C @oehme
