### ISSUE TITLE
Visual Studio debugging command is different to what gradle executes 

### ISSUE THREAD

**Issue by donalmacc** [gradle/gradle#816]
Visual studio has a field in its property pages for the command to execute while debugging
![screenshot 28](https://cloud.githubusercontent.com/assets/861243/20052567/6f876946-a4cc-11e6-82f2-50adebe7da72.png)
By default, this is $(TargetPath) which is the output executable that gradle generates. This exe isn't the output of the install task, so if the executable has any dependencies (e.g. DLLs being present), this won't work.

### Expected Behavior
A NativeExecutableComponent generated visual studio project named MyExecutable, should have ``gradlew runMyExecutable$(Configuration)`` set as the `Debugging` command in visual studio.

### Current Behavior
See Opening paragraph; Debugging command is $(TargetPath)

### Context
If an executable has a runtime dependency, or depends on having run the install task to run, it will not function correctly. Secondly, one of the major advantages of using gradle is that the builds I run from my IDE are the same as the builds I run from the command line. This breaks this expectation, as from the commandline, the `runXXXX` command is used, whereas the executable is launched without context.

### Steps to Reproduce
Use the [visualStudio sample](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/native-binaries/visual-studio) to generate a visual studio project, and observe the Debugging command in the project properties.

### Your Environment
gradle 3.1
Verified on VS 2013, VS2015.

**Comment by donalmacc** [comment]
Having explored solutions to this ourselves, I'm actually not sure that making the `runXXXX` command the debugging command is the "correct" solution. Referring back to my other improvement suggestion: [822](https://github.com/gradle/gradle/issues/822), setting the NMake build command to be the `install` task instead of the assemble task should be performed, but as a result of this, changing the NMakeOutput to reference the output of the install task, (ie `build\install\path\to\exe` rather than `build\exe\path\to\exe`) should be sufficient.

**Comment by lacasseio** [comment]
Those are great suggestions, thanks @donalmacc.

**Comment by donalmacc** [comment]
Turns out this already in place, and the issue for us is that we're using the Google test plugin. The google test plugin generates `NativeTestSuiteBinarySpec` tasks, while normal executables generate `NativeExecutableBinarySpec` tasks. Unfortunately the logic for choosing whether to use the install task or the build task depends on the binary being a `NativeExecutableBinarySpec`

**Comment by donalmacc** [comment]
I'm going to close this, and open a new issue [here](https://github.com/gradle/gradle/issues/844) as this is misleading.
