### ISSUE TITLE
Tasks provided by thirdparty plugin are not up-to-date after running build with “–scan”

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#8161]
Raised in the forum at https://discuss.gradle.org/t/class-path-has-changed-after-adding-scan/30038 

Example project demonstrating the problem + instructions is available at https://github.com/MyDogTom/build-scan-classpath

### Expected Behavior
kotlin compile tasks are considered up-to-date when running same `build` task with `--scan` enabled for the first time.
 
### Current Behavior
kotlin compile tasks are not up-to-date. As reason build scans states `Class path of task ‘taskName’ has changed from XYZ to ZYX.`

when --scan is used without the scan plugin applied already in the build, the scan plugin is dynamically applied to the build which results in a changed classpath that leads to non up-to-date tasks provided by third party plugins
 
### Context
This is partially related to https://github.com/gradle/gradle/issues/6045

### Steps to Reproduce (for bugs)
See instructions at https://github.com/MyDogTom/build-scan-classpath#build-scan-classpath

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/luruyeebt7s26/timeline?task=ta44irykic3pc

**Comment by MyDogTom** [comment]
I [updated example project](https://github.com/MyDogTom/build-scan-classpath/commit/689fd22f7615cae494e1c640572b80e2e9411808) to Gradle 6.5rc5 and Kotlin 1.3.72. Unfortunately the issue is still present :(

**Comment by benhyland** [comment]
Thanks for describing this issue, it was very confusing for someone not knowing much about kotlin or gradle, good to have an explanation. The mentioned workaround should be OK for us too.

**Comment by sorin-florea** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.
