### ISSUE TITLE
Java compilation fails with cryptic message when compilerArgs has "-J" flags instead of forkOptions.jvmArgs

### ISSUE THREAD

**Issue by isker** [gradle/gradle#8163]
### Expected Behavior
[CompileOptions.compilerArgs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:compilerArgs) correctly handles `-J` flags.  (These are the flags that are passed to the JVM that javac launches.)

### Current Behavior
CompileOptions.compilerArgs places `-J` flags into java-compiler-args.txt.  Placing these flags into command line argument files is explicitly disallowed by javac.  At some point an assertion with a particularly useless error message was added into javac validating this:

```
An exception has occurred in the compiler (1.8.0_141). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: the -J flag should be caught by the launcher.
        at com.sun.tools.javac.main.Option$20.process(Option.java:331)
        at com.sun.tools.javac.main.Main.processArgs(Main.java:260)
        at com.sun.tools.javac.main.Main.compile(Main.java:414)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.sun.tools.javac.main.Main.compile(Main.java:361)
        at com.sun.tools.javac.Main.compile(Main.java:56)
        at com.sun.tools.javac.Main.main(Main.java:42)
```

From [javac 10 documentation](https://docs.oracle.com/javase/10/tools/javac.htm#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9__BHCJEIBB) on `-J` flags in the command line arguments files:

> The -J options aren’t supported because they’re passed to the launcher, which doesn’t support argument files.

There is similar language going back to at least the [javac 6 documentation](https://docs.oracle.com/javase/6/docs/technotes/tools/windows/javac.html#commandlineargfile).

Javac memory flags, which I believe are being sourced from gradle configuration, look to be correctly placed directly on the command line.  Here's the full javac invocation gotten from an `--info` invocation of gradle:
```
Starting process 'command '/usr/jdk1.8/bin/javac''. Working directory: [REDACTED] Command: /usr/jdk1.8/bin/javac -J-Xms1024m -J-Xmx4g -J-Xss4096k @/[REDACTED]/build/tmp/compileJava/java-compiler-args.txt
```

### Context

I am trying to debug an annotation processor.  These run inside of javac.  I want to only debug javac for one of the many JavaCompiles that are being run as a part of my build, so this seemed like the most direct way to do that.

### Steps to Reproduce (for bugs)

You can add this line (or any other one adding a JVM flag) to the buildscript of any java project:
```groovy
compileJava.options.compilerArgs += '-J-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005'
```

### Your Environment
I can provide more details if you need, but I don't think any more is necessary.

**Comment by big-guy** [comment]
This is sort of the same question: https://github.com/gradle/gradle/issues/8097

You can run the Gradle daemon in debug mode with `-Dorg.gradle.debug=true`: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

That'll probably be easier to debug than catching the external javac process.

**Comment by isker** [comment]
@big-guy that'd handle my case, but for arbitrary JVM flags it looks like the solution in https://github.com/gradle/gradle/issues/8097#issuecomment-449424639 is correct.

If compilerArgs not handling -J flags isn't on the table, can this issue at least track providing a better error message?  Fail fast if any compileArgs start with `-J`?

**Comment by big-guy** [comment]
That's a good idea.  Would you be willing to submit a PR? 

I think we can add validation in:
https://github.com/gradle/gradle/blob/2ba8246ede3e02cc7675a68115fb66f7cace2d8e/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java#L93

A note about what `compilerArgs` means here (basically, that these are not command-line options for the launcher):
https://github.com/gradle/gradle/blob/ad284fbdf6bae705e24964a3717b2fc86c74fb05/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/CompileOptions.java#L299-L310

**Comment by isker** [comment]
Sure.  I will add test coverage here: https://github.com/gradle/gradle/blob/2ba8246ede3e02cc7675a68115fb66f7cace2d8e/subprojects/language-java/src/test/groovy/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilderTest.groovy#L341-L360

Let me know if you have additional expectations.
