### ISSUE TITLE
Default xmx changed before and after 5.0 for test executor?

### ISSUE THREAD

**Issue by wisechengyi** [gradle/gradle#8166]
When upgrading gradle from 4.10.2 to 5.1 (only variable, no other plugin changes), we observed some tests failing due to OOM in 5.1 which passed in 4.10.2 without any issue.

With further investigation, this is the command line 

#### From 4.10.2

`388229 worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 2' -Djava.awt.headless=true -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -Drobolectric-deps.properties=/home/yic/t2/build/global/robolectric-deps.txt -Drobolectric.offline=true -Drobolectric.test.config=/home/yic/t2/build/projects/lib/twitter/features/onboarding/intermediates/unit_test_config_directory/debugUnitTest/generateDebugUnitTestConfig/out/com/android/tools/test_config.properties -Xverify:none -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea`

#### From 5.1
`394911 worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1' -Djava.awt.headless=true -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -Drobolectric-deps.properties=/home/yic/t2/build/global/robolectric-deps.txt -Drobolectric.offline=true -Drobolectric.test.config=/home/yic/t2/build/projects/lib/twitter/features/onboarding/intermediates/unit_test_config_directory/debugUnitTest/generateDebugUnitTestConfig/out/com/android/tools/test_config.properties -Xverify:none -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea`

Hence the difference is 5.1 has `-Xmx512m`, and 4.10.2 does not which probably defaults to 1G.

Questions:
1. Has it been changes lately to explicitly set the test executor's default Xmx to be 512m if [`maxHeapSize`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxHeapSize) isn't supplied by user?
2. If so, that means we'd probably need to manually specify it?

**Comment by GFriedrich** [comment]
@wisechengyi: Yes this has been changed in Gradle 5 - please see https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:default_memory_settings
Basically before it was "not limited" - which means it took 1/4 of your memory by Java default. Now it's limited to 512 MB and you need to set the worker heap to your needs if you need more than that.

**Comment by wisechengyi** [comment]
Great, thanks for the clarification and pointer!
