### ISSUE TITLE
[Documentation] Link code examples to github

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#8180]
Some of the documentations have nice "highlighting" "badges" like the following:
![bildschirmfoto 2019-01-08 um 11 52 01](https://user-images.githubusercontent.com/10229883/50826517-1c94f380-133c-11e9-9feb-66bc174b6fb7.png)

When I want to take a look into the example i do the following:
* I open a new tab in my browser
* google for the path (here `samples/compositeBuilds/basic`)
* click/open the first google result which is most of the time the source code at github (here https://github.com/gradle/gradle/tree/8f9a01ff37e304340f11db890c3db9eaac46cd2b/subprojects/docs/src/samples/compositeBuilds/basic)

I think it would be great when there is already a link to the source code at github.
The branch should reflect the current Gradle version from the doc.
So meaning `current` goes to to the master branch while a specific documentation (e.g. `4.9`) should point to the git-tag ([like this](https://github.com/gradle/gradle/tree/v4.9.0/subprojects/docs/src/samples/compositeBuilds/basic))

### Expected Behavior
There is an link to the example/source code in the documentation when its mentioned..

### Current Behavior
There is no link to the example/source code :(

**Comment by clemp6r** [comment]
Also the following pages refer to samples in the `-all` distribution but samples are not included in this distribution anymore.

https://docs.gradle.org/current/userguide/gradle_wrapper.html#customizing_wrapper

> You can also find various samples for configuring the Wrapper in the Gradle distribution.

https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests

> A sample of mixed tests can be found at samples/testing/junitplatform/mix in the '-all' distribution of Gradle.

> A test engine filtering sample can be found at samples/testing/junitplatform/engine in the '-all' distribution of Gradle.
