### ISSUE TITLE
Provide tasks `sourcesJar`, `javadocJar` with gradle

### ISSUE THREAD

**Issue by zenglian** [gradle/gradle#8192]
I think it will be good to provide tasks `sourcesJar`, `javadocJar` OOTB  with gradle.

Not sure if there is such a plugin today, but the suggested solutions in below link are a bit tricky, and not standardized:

https://stackoverflow.com/questions/11474729/how-to-build-sources-jar-with-gradle

**Comment by jjohannes** [comment]
This is available in Gradle 6+

```
java {
    withJavadocJar()
    withSourcesJar()
}
```
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example
