### ISSUE TITLE
Gradle attempts to acquire exclusive lock on $PWD/.gradle and $GRADLE_USER_HOME/.gradle

### ISSUE THREAD

**Issue by stmlange** [gradle/gradle#8202]
I was under the impression that gradle only tries to acquire exclusive locks on `$GRADLE_USER_HOME`. However one of our builds failed (randomly), since it seems that gradle also tries to acquire an exclusive lock on `$PWD/.gradle`. When two jobs run in parallel, it seems obvious that not both might be able to get the exclusive lock.

### Expected Behavior

Gradle only acquire exclusive locks on `$GRADLE_USER_HOME`. 

### Current Behavior

Gradle attempts to acquire exclusive lock on `$PWD/.gradle` and `$GRADLE_USER_HOME/.gradle`

### Context

Build failed, since one of the gradle instances could not acquire an exclusive lock on `$PWD/.gradle`

### Steps to Reproduce (for bugs)

gradle.properties
```
org.gradle.daemon=false
org.gradle.workers.max=5
```

build.gradle (see also https://docs.gradle.org/current/userguide/tutorial_java_projects.html#sec:summary)
```
plugins {
    id 'java'
    id 'eclipse'
}
version = '1.0'
jar {
    manifest {
        attributes 'Implementation-Title': 'Gradle Quickstart',
                   'Implementation-Version': version
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'commons-collections', name: 'commons-collections', version: '3.2.2'
    testImplementation group: 'junit', name: 'junit', version: '4.+'
}

test {
    systemProperties 'property': 'value'
}

uploadArchives {
    repositories {
       flatDir {
           dirs 'repos'
       }
    }
}
// end:complete-example[]
```

Run:
```
mkdir -p /tmp/gradle_tmp_home

export GRADLE_USER_HOME="/tmp/gradle_tmp_home"

./gradlew clean build --dry-run --debug --console=plain | grep "Waiting to acquire exclusive lock on file hash cache"
15:04:40.071 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on file hash cache (/tmp/gradle_tmp_home/caches/5.1/fileHashes).
15:04:40.739 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on file hash cache (/example/.gradle/5.1/fileHashes).
```

### Your Environment

```
$ gradle --version

------------------------------------------------------------
Gradle 5.1
------------------------------------------------------------

Build time:   2019-01-02 18:57:47 UTC
Revision:     d09c2e354576ac41078c322815cc6db2b66d976e

Kotlin DSL:   1.1.0
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.15.0-39-generic amd64
```

**Comment by oehme** [comment]
Gradle needs to control cache access, so the locking is expected. However the lock is released when another build needs it. 

Can you attach a project that reliably fails? Or is it sporadic/environment specific?

**Comment by stmlange** [comment]
Sorry for the delay here. So far I could experience the issue with a single build reliably. However boiling it down to something reproducible did not trigger that issue (so far). I'd like to try some other options and I guess when I can't get it reproduced I'll just close this issue...
