### ISSUE TITLE
Incremental Java compile is disabled when empty source folders are added

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#8203]
### Environment
Gradle 5.1-rc-2 (in Gradle 5.1-rc-3 and above, the issue is masked by a different issue: https://github.com/gradle/gradle/issues/8194)

### Steps to Reproduce
Use this sample Android project: [MyApplication.tar.gz](https://github.com/gradle/gradle/files/2742456/MyApplication.tar.gz)

1. Run the first build: `./gradlew :app:compileDebugJavaWithJavac`, it should succeed.
2. In `app/src/main/java`, add package `com.example.foo` without any classes.
3. Run the second build: `./gradlew :app:compileDebugJavaWithJavac --info`, observe that Gradle performs full recompilation:
```Full recompilation is required because A resource changed. Analysis took 0.053 secs.```

### Expected Behavior
Gradle should perform incremental compile in the second build.

### Context
I saw this issue a while ago but can only manage to reproduce it now while debugging https://github.com/gradle/gradle/issues/8194 and https://github.com/gradle/gradle/issues/8197. It doesn't happen on a HelloWorld project, but it does on this particular project. (I haven't examined how this project exposes the issue yet.)

**Comment by hungvietnguyen** [comment]
### Additional Request

The error message `Full recompilation is required because A resource changed` may be more helpful if it also points out exactly what resource has changed.

**Comment by wolfs** [comment]
@oehme It looks like changes to directories (i.e. adding directories in source folders) are processed as resource changes: https://github.com/gradle/gradle/blob/8ce7ea59c0b47e2dc6f090c923b9c893979095f0/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/InputChangeAction.java#L45-L53

Is this intentional? I guess it would be fine to only process actual files. WDYT?

**Comment by oehme** [comment]
Yes, good catch!

**Comment by ljacomet** [comment]
@bigdaz Ended up taking a look at it and opened #8211 - feel free to take over after my day if that solution is not satisfactory
