### ISSUE TITLE
Feature Request: Allow multiple channels in the gradle wrappers

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#8207]
**Use case:** 

Sometimes you need to be able to switch between gradle versions because of compatibility issues. 
E.g. Android Gradle plugin 3.4 alpha doesn't work with Gradle 4.10, but Android Studio 3.2 won't sync when using Gradle 5.1. 

It would be nice to allow users of the build to choose from multiple pre-selected gradle versions, without having to modify any files in the project itself (i.e. the gradle-wrapper.properties) which causes 
difficulties when switching branches. 

**Possible solution:** 

Maybe you could have multiple URLs like this in `gradle-wrapper.properties`:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-milestone-1-all.zip
distributionUrl_foo=https\://services.gradle.org/distributions/gradle-5.1-all.zip
distributionUrl_bar=https\://services.gradle.org/distributions/gradle-4.10-all.zip
```
(where `foo` and `bar` could be arbitrary version names that users select.)

And select them like this in `$HOME/.gradle/gradle.properties`:
```
wrapper.version=foo
```
which would select version `5.1`. 

If `wrapper.version` didn't exist, it would default to the plain `distributionUrl` (i.e. `5.0-milestone-1`)

Is this something you would consider?

**Comment by big-guy** [comment]
No, I don't think this is something we'd want to do.

The example you gave could be handled in a couple of other ways:
1. Use [sdkman](https://sdkman.io/) to switch between different versions of Gradle without modifying the build.
1. Explicitly configure the IDE to sync with a different version of Gradle (than what the build says).

I think it's important that the build itself declares which version needs to be used, so it would be unnecessary for a build to specify multiple versions of Gradle _and_ for the user to select which version they want to use.

**Comment by eygraber** [comment]
I've been running into this issue for a while. I'm a team lead for Android at my company, and I routinely check out preview versions of Gradle and the Android Gradle Plugin to make sure that we'll be compatible with them in the future. The rest of my team needs to stay on the stable version, so I can't commit `distributionUrl` to our VCS.

Is there any way to achieve the functionality @yogurtearl asked for by allowing `distributionUrl` to be parameterized, so I can set an environment variable that determines what version will be used (or something along those lines)?
