### ISSUE TITLE
When using Java Gradle Plugin flag tasks that are Cacheable but do not define PathSensitive

### ISSUE THREAD

**Issue by vanniktech** [gradle/gradle#8214]
A lot of Gradle Plugin authors assume that just slamming `@CacheableTask` on their task will make it cachable. While this might work for local builds it might not for remote builds since the paths of each file have to be considered too.

Just like the Java Gradle Plugin warns you when you have parameters in your custom Task that are not annotated with `@Input` or any other incremental build related annotation, it would also be nice if the Java Gradle Plugin warns you when you have a task that is marked as `@CacheableTask` but does not specify the `@PathSensitive` for each of it's inputs and outputs.

**Comment by big-guy** [comment]
In [5.1 and newer](https://docs.gradle.org/current/release-notes.html#improvements-for-plugin-authors), it does.
