### ISSUE TITLE
Document deprecated APIs replaced by Property / Provider

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#8217]
As indicated in [this forum post](https://discuss.gradle.org/t/publishing-jars-with-classifiers-after-v5-0/30144), Gradle users are surprised by the deprecation of some task fields and the missing updates to documentation and release notes referencing these deprecations.

Impacted types:
* `AbstractArchiveTask`

We should definitely update documentation to reflect these changes and consider adding a release note whenever such a change happens in the future.

Also it seems these deprecations are not coupled with a deprecation warning and thus are only visible through IDE highlighting and DSL documentation.

**Comment by ljacomet** [comment]
@big-guy Could you add other types, if any, that should be properly updated across documentation?

**Comment by ljacomet** [comment]
Working on the PR for `AbstractArchiveTask`

**Comment by big-guy** [comment]
@ljacomet can we close this one?

**Comment by ljacomet** [comment]
If there are no other types impacted, then sure it can be closed.
