### ISSUE TITLE
Improvement suggestions to Visual Studio plugin

### ISSUE THREAD

**Issue by donalmacc** [gradle/gradle#822]
We've been using the Visual studio integration for a few weeks now, and I've got some suggestions for improvements based on our day to day usage. This is coming more from a C++ developer than a build engineer, so feel free to correct me/ask for clarification. 

### Current Behavior
>  This task will generate a Visual Studio Solution file for the named component. This solution will include a Visual Studio Project for that component, as well as linking to project files for each depended-on binary. 

From the user guide. 

In a single project build with multiple components, the IDE tasks are populated with two tasks per component; one to build the VS solution, and one to clean it. These tasks figure out what other components the current component depends on, and adds those projects to the solution.

In a multi project build, the behaviour is the same. 

### Suggested Behavior
Rather than generating one Visual studio solution per Component, generate one per Project. In a single project build, this will mean there are two IDE tasks - one to generate the solution and one to clean the solution. The visual studio solution should include a visual studio project for all of the native components in the gradle project, regardless of whether they are in the dependency graph. The visual studio solution name should be the same as the gradle project.

In a multi project build, there will be two tasks per project. One to generate that projects solution, and one to clean the project's solution. As before, all of the components that are part of the current gradle project should have their visual studio project added to the solution. If the gradle project has child projects, all of the components of the child projects should have their visual studio projects added to the solution. These projects would be grouped in filters in the solution, with the filter name set as the projects name.

In the case there are dependencies on other projects, the components may/may not have their visual studio projects added to the solution. Possibly, this could be a property of the solution task.

### Your Environment
gradle 3.1, gradle 3.2
Visual Studio 2013, Visual Studio 2015
Windows 10 Pro x64

**Comment by donalmacc** [comment]
Regarding the `Debugging` Command, I've been investigating this and I am not convinced that generating the `.vcxproj.user` command is the right way of doing this. [I've bugged this in 816](https://github.com/gradle/gradle/issues/816), and noted that if the NMake build command is set to the `install` task, the NMakeOutput file should be set to the output of the install task, not the output of the build task.

**Comment by lacasseio** [comment]
Thanks for the awesome suggestions @donalmacc. The current support for Visual Studio is quite limited. As you can see, we use NMake project to provide the integration with Gradle. All the solutions you brought are very good and valid.

We are looking to make a better deep integration with Visual Studio by improving the NMake approach and coming up with a modeling for those other features. Different solution path exists at the present moment such as using the Gradle Tooling API, custom MSBuild integration or expanding current NMake solution.

We are not abandoning the NMake solution. Instead, we want to make to integration better and more useful for native development. We welcome any improvement you can contribute in improving the Visual Studio integration.

**Comment by donalmacc** [comment]
It is, yes. It doesn't appear to have had much development activity since it was implemented first.

I'm happy to try and be involved in the development of this, and I thought that getting my ideas open for discussion was the first step towards doing so. I would hope to use this issue, and 816 as a jumping off point.

**Comment by lacasseio** [comment]
I'm glad to hear this. Let us know of about anything we can help with your contribution.

**Comment by jrmash** [comment]
I work on a project that is currently evaluating the use of Gradle for our C++ builds and I ran across this ticket while researching options for better Visual Studio integration.  To that end, there are a couple very specific features that I would like to get some feedback from you guys:

- Generate Visual Studio Project files that use the MSVC build toolchain and project settings.  This feature is useful for developers that are debugging with the Visual Studio IDE and want to locally toggle a project property or update a runtime parameter without having to dig around to figure out what the corresponding command line flag is so they can add it to the Gradle build file.  This is, so far, the number one requested feature so far by the developers helping me evaluate.
- Provide a means to allow SourceSets defined in the Gradle build file to be used as filters in the Visual Studio project file filters.  This is something that I would imagine most small projects do not need, so could be an optional feature that defaults to off to maintain current compatibility, but it is nearly critical for any sort of large-scale project.

Assuming that you guys provide a little guidance on the preferred implementation and we do the work, would these features be something that would be pulled back into the official Visual Studio plugin?

**Comment by big-guy** [comment]
We incorporated some of these changes into 4.6: https://docs.gradle.org/4.6-rc-1/release-notes.html#improved-visual-studio-ide-support-for-multi-project-builds

**Comment by adammurdoch** [comment]
There will also be some further improvements in 4.7 (e.g. generated VS files use a more modern format, the platform toolset matches the version of VS, the debugger uses the output of the install task). These will only apply to the new C++ plugins, however.
