### ISSUE TITLE
Concurrently use worker process when work is thread safe

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [gradle/gradle#8220]
### Expected Behavior

A single worker process is used for a thread-safe work. 

### Current Behavior

A worker process is created for each concurrent work.
Since not all workloads are thread-safe, the feature would require some kind of opt-in mechanism, such as an annotation on a `Runnable` class or new isolation mode (`IsolationMode.SHARED_PROCESS`). 

### Context

In the worst case Gradle can create `number_of_cpu_threads` number of  processes for each a work even when the work is thread-safe.
To put it in perspective, for a common setup of 4 core/8 threads 16Gb RAM, 8 * 512Mb is 4Gb or 25% of RAM just for one type of work. And 512Mb might be not enough for some heavy workloads, such as code compilation. Also since each process is doing only a part of work's executions, JIT warm up might take more builds.
These issues prevent us from using Gradle worker processes for the Kotlin compiler, instead we use our own implementation of the compiler daemon. However implementing daemon can be non-trivial for a plugin developers (we still have a number of daemon related issues). Also it might be hard to reuse a custom implementation in different plugins. We actually have this problem, when because of implementation details and structure of our repositories, the Kotlin compiler daemon is not used in dokka (Kotlin documentation generator) and Kotlin/Native.

### Steps to Reproduce (for bugs)
N/A

### Your Environment
N/A

**Comment by alllex** [comment]
Sorry for the late reply.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

---

While the feature request makes sense, there are potential challenges in addressing it due to the complications with how the worker classpath and reuse are handled. We'd need a confirmation from the responsible team on how to proceed.

**Comment by alllex** [comment]
On behalf of the responsible team, we are not reopening the issue for now.

While the proposed direction might be viable, it's unclear whether it's the best course without diving deeper into the use case. The improvements in the areas of Workers are also not in the immediate focus of the team.

When the time comes to focus on the larger problem of memory consumption by the build, we'll consider this as one of the strategies.
