### ISSUE TITLE
Checkstyle method exclude(excludeSpec) is failed when closure return false

### ISSUE THREAD

**Issue by DmitryevichD** [gradle/gradle#8225]
I want use an exclude(excludeSpec) method for filtering my files. 
When my closure returns false, I have the error: "Cannot add include/exclude specs to Ant node. Only include/exclude patterns are currently supported".
But when closure returns true, checkstyle does correct filtering all  files.

**Comment by big-guy** [comment]
@DmitryevichD Could you provide an example of what you've tried and what you're trying to do?

Thanks!
