### ISSUE TITLE
Warn the user if local build cache is put on a network share

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#8228]
As that would make it slow and you might as well use the remote cache instead. Many organisations put their user homes on network shares and the default local cache location is in the user home.

**Comment by lptr** [comment]
Aren't there problems with locking, too?

**Comment by oehme** [comment]
Yes. They could be solved, but it would still be awfully slow.

**Comment by ljacomet** [comment]
Valid and related:
* #33903
