### ISSUE TITLE
Native: Gradle attempts to configure PrebuiltLibraries for targetPlatforms not used in the current project

### ISSUE THREAD

**Issue by philmcardle** [gradle/gradle#823]
When configuring PrebuiltLibraries, Gradle tries to configure the library binaries for every platform defined in the project, and what seems to be every default platform that it supports.

### Expected Behavior
When platforms are explicitly defined, Gradle should only configure PrebuiltLibraries for those platforms.

I have no strong feelings on what should happen when no platforms are defined.

### Current Behavior
Gradle will configure the PrebuiltLibrary binaries for the defined platforms in the project, and then all of the following:

	platform 'windows_x86'
	platform 'windows_x86-64'
	platform 'windows_arm-v7'
	platform 'windows_ia-64'
	platform 'freebsd_x86'
	platform 'freebsd_x86-64'
	platform 'freebsd_arm-v7'
	platform 'freebsd_armv8'
	platform 'freebsd_ppc'
	platform 'freebsd_ppc64'
	platform 'unix_x86'
	platform 'unix_x86-64'
	platform 'unix_arm-v7'
	platform 'unix_armv8'
	platform 'unix_ppc'
	platform 'unix_ppc64'
	platform 'linux_x86-64'
	platform 'linux_x86'
	platform 'linux_arm-v7'
	platform 'linux_armv8'
	platform 'osx_x86'
	platform 'osx_x86-64'
	platform 'solaris_x86-64'
	platform 'solaris_x86'
	platform 'solaris_sparc-v8'
	platform 'solaris_sparc-v9'

### Context
I've been following the suggested approach in [71.16.2](https://docs.gradle.org/current/userguide/native_software.html#native_binaries:platform) in the User Guide and extending the targetPlatform with support for defining the tool chain, as we need to be able to target multiple tool chains per existing combinations of architecture + operating system, and especially to link against prebuilt libraries built with different compilers, and I found that when accessing an extra property on the targetPlatform object in PrebuiltLibraries' binaries, that Gradle was configuring for more platforms than I expected, and for which my extra property didn't exist.

More specifically, I have defined ext.toolChain in each of the platforms I support, and I depend on this property to build the path to the staticLibraryFile when configuring PrebuiltLibraries.

I'm working around this by using `targetPlatform.hasProperty` prior to calling code that depends on it.

### Steps to Reproduce (for bugs)
Using the [cunit](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/native-binaries/cunit) sample, add code similar to `println targetPlatform` inside

    binaries.withType(StaticLibraryBinary) {
        println targetPlatform
        staticLibraryFile =
            file("libs/cunit/2.1-2/lib/" +
                 findCUnitLibForPlatform(targetPlatform))
    }

See that it attempts to configure the defined x86 platform and all of the platforms listed above when running gradle tasks / build.

### Your Environment
Windows 10 1607, Gradle 3.1, MSVC 2013

**Comment by big-guy** [comment]
Based on the [direction](https://blog.gradle.org/state-and-future-of-the-gradle-software-model) we're heading in, we're going to leave this as it is.  The kind of dependency management for the [new work](https://blog.gradle.org/introducing-the-new-cpp-plugins) we're doing is already better than what we had before and we have some [samples](https://github.com/gradle/native-samples#application-with-prebuilt-library-dependencies-prebuilt-binaries) for what this looks like currently.  We're working on making this better and plan to tackle "prebuilt binaries" in a couple of different ways.  

- As binaries available from a remote repository
- As binaries that can be built from source where Gradle does the building or delegates to another build system
- As target runtimes (this is mostly for choosing an appropriate stdlib)
- As "system libraries" from well known locations (like Homebrew, pkgconfig, etc).

If you feel like we've missed something, please feel free to [open an issue](https://github.com/gradle/gradle-native) on gradle-native.
