### ISSUE TITLE
Support returning a value from worker

### ISSUE THREAD

**Issue by AlexeyTsvetkov** [gradle/gradle#8233]
It would be nice to be able to return a serializable value from worker back to a Gradle plugin (so a value processing code would have an access to the Gradle model).

### Expected Behavior
I would like to be able to write something like:
```
workerExecutor.submit(MyCallable.class, { config -> /* ... */ }, { returnValue -> /* ... */ })
```

I feel that a callback should be executed as a part of task execution (so it is executed before following tasks and before output snapshot is created), but I don't have any strong supporting use-cases.

### Current Behavior
Currently it is possible to "return" a value by serializing it to a file, but it is less performant and less convenient. 

### Context
N/A

### Steps to Reproduce (for bugs)
N/A

### Your Environment
N/A

**Comment by adammurdoch** [comment]
Do you have some examples of what you'd like to use this for?

**Comment by alexey-tsvetkov** [comment]
I would like to use it for performance reports/logs from the Kotlin compiler

**Comment by uklance** [comment]
I just threw together a wrapper for the worker executor API which allows you to specify jobs as `Callable` and under the hood it does all the serializing / deserializing to files.

See [CallableWorkerExecutor.java](https://github.com/uklance/gradle-callable-worker/blob/master/buildSrc/src/main/java/CallableWorkerExecutor.java) and [SampleTask.java](https://github.com/uklance/gradle-callable-worker/blob/master/buildSrc/src/main/java/SampleTask.java).
