### ISSUE TITLE
Enforce or drop HasInternalProtocol annotation

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#8236]
We used to use `@HasInternalProtocol` to signal that a public type has an accompanying internal type to go with it. The annotation is used inconsistently, sometimes not appearing on types that do have an accompanying type, while sometimes appearing on types that don't (or not anymore). The practical value of having this annotation present in a consistent way is not obvious either.

One option is to decide that this annotation is useful, and then enforce its use. One way to do that is by annotating the accompanying internal type with a reference to its public type (`@AccompanyingInternalTypeOf(PublicType.class)`), and make sure that for every `@HasInternalProtocol`-annotated type we have at least one such reference at all times, and vice versa.

The other option is to remove `@HasInternalProtocol`. If we do so, we should consider capturing a different quality of public types, which is their extensibility by user code. We should probably annotate all public types (there should be few) that are supposed to be extended/implemented by user code with something like `@Extensible`.

**Comment by adammurdoch** [comment]
I would remove it, and replace it with something like an `@Extensible` annotation.

**Comment by ldaley** [comment]
I suggest also having an inverse annotation and verifying that all applicable types are annotated.

The reason being is that the primary purpose is/was to communicate to users. Relying on the omission of annotations to communicate “you should not extend/implement this” seems risky to me. I don't think enough users would internalise “only extend `@Extensible`” for it to be effective. Sure, some people will miss `@NonExtensible`, but it should reduce the number.

**Comment by ldaley** [comment]
> The reason being is that the primary purpose is/was to communicate to users.

I am aware it did not do this well.

**Comment by lptr** [comment]
We could have static validation to see if a plugin extended something not-extendable, regardless of how it is marked (and perhqps require an explicit opt-in to allow it).

This is a somewhat different topic, but we should find a way to enforce validations, as currently we don’t have a good way to say that “if you are developing code for Gradle, you should adhere to these rules”. One way could be to allow adding the `gradleApi()` dependency only by applying a plugin. This plugin could enable all the validations we want.

**Comment by ldaley** [comment]
I think we should prioritise consistent and correct usage on our side before the user side.
