### ISSUE TITLE
Platform dependency + version constraint not deduped in POM

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#8238]
### Expected Behavior

```gradle
dependencies {
  compile platform("org.apache.spark:spark-dist_2.11-hadoop-palantir-bom")
  constraints {
    compile "org.apache.spark:spark-dist_2.11-hadoop-palantir-bom:2.5.0-palantir.7"
  }
}
```

When I depend on a published platform without a version, and inject the version separately through a vanilla constraint, I expect the resulting POM to contain a single entry in the `<dependencyManagement>` section.

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-dist_2.11-hadoop-palantir-bom</artifactId>
        <version>2.5.0-palantir.7</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

### Current Behavior

I get two entries for the same dependency (same `groupId` and `artifactId`), one of which doesn't have a version. This is not a correct POM.

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-dist_2.11-hadoop-palantir-bom</artifactId>
        <version>2.5.0-palantir.7</version>
        <scope>compile</scope>
      </dependency>
      <dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-dist_2.11-hadoop-palantir-bom</artifactId>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

Note that gradle imports the correct BOM, it's just the published POM that ends up being incorrect.

### Context

I'm trying to declare a BOM dependency as described [here](https://docs.gradle.org/5.1/userguide/managing_transitive_dependencies.html#sec:bom_import), but have the version injected from somewhere else, which is why it ends up as a constraint.

### Steps to Reproduce (for bugs)

Please see linked repo.

### Your Environment

 * Build scan URL: https://gradle.com/s/ilk7ycapy6w5u
 * Repo: https://github.com/dansanduleac/gradle-test/tree/ds/constrained-platform-double-entry

**Comment by melix** [comment]
The problem here is similar to #7351 and, to some extent #8020. Basically without resolving, we cannot know what to do. Even if we do, we still need to be smart about deduplication and how to do it.

**Comment by dansanduleac** [comment]
Don't we resolve prior to writing the pom file though?
I agree that merging these is a bit weird since in gradle the platform has a configuration, but in maven we can't use the scope as it needs to be `import`.
However, imagining that platform imports are just read out of the `default` configuration, then could we not use the resolved `default` to figure out the correct version?

**Comment by melix** [comment]
> Don't we resolve prior to writing the pom file though?

No we don't. We only do this when you have configured a version mapping strategy, which is fairly recent addition to Gradle.

> However, imagining that platform imports are just read out of the default configuration, then could we not use the resolved default to figure out the correct version?

First, I don't really understand what you mean. Beside that, there's no "platform imports are read of out a configuration". We parse the POM files, build a model, and use the model consistency. There shouldn't be anything using the `default` configuration, which even doesn't exist at all for Maven.
