### ISSUE TITLE
JaCoCo plugin should provide a way to verify that given code metrics are met

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#824]
Users need a way to check that code coverage meets a given standard. 

### Expected Behavior
A provided task or task configuration such that one can choose to fail the build if a certain level is not achieved with the current build.

### Current Behavior
No coverage verification built-in.

### Context
This is a very [highly voted feature request](https://issues.gradle.org/browse/GRADLE-2783). 

The implementation shouldn't be too hard - the underlying Ant tasks provide a way to pass appropriate values and fail the build if metrics are not met.

There is also an [incomplete attempt](https://github.com/gradle/gradle/pull/460) at this that can be learned from.

**Comment by jiakuan** [comment]
In-built support should be very helpful. I've been using a workaround with some custom code for this purpose. Sample Jacoco configuration can be found here: https://github.com/jiakuan/apuava/blob/master/gradle/jacoco.gradle

**Comment by bmuschko** [comment]
Spec: https://github.com/gradle/gradle/blob/master/design-docs/code-coverage.md

**Comment by bmuschko** [comment]
PR: https://github.com/gradle/gradle/pull/983

**Comment by bmuschko** [comment]
The pull request has been merged and will be release with the next version of Gradle. Enjoy!
