### ISSUE TITLE
Provide public OSS API to export Build Scans results

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#8241]
### Expected Behavior
Provide a public API to export Build Scans results without the need of Gradle Enterprise

### Current Behavior
Exporting build scan results requires Gradle Enterprise which isn't suitable for every company/project.

### Context
We have internal systems for statistics/metrics that combine several datasources and not only build/gradle ones. Having an extra layer such as gradle enterprise doesn't play very well in our infrastructure. 

It would be ideal if we could have access to a public API to export our build scans results without the need for pushing to a Gradle Enterprise instance.

**Comment by ldaley** [comment]
Hi @rpalcolea, 

We do not intend to provide open access to the data that is collected by Gradle Enterprise, without Gradle Enterprise.

If there's data of particular interest that you are looking to observe, please indicate what it is and what your motivation for observing it is. There may be other ways to achieve your goal, depending on what it is.
