### ISSUE TITLE
GradleBuild task does not work with Composite Builds. 

### ISSUE THREAD

**Issue by tasomaniac** [gradle/gradle#8246]
### Expected Behavior

GradleBuild task should work when composite builds are used too. Can you provide a timeline when this will be supported?

### Current Behavior

GradleBuild tasks fail on configuration time and it says that they are not supported yet with no more information.

**Comment by big-guy** [comment]
I don't think we intend to make this work any time soon.

Could you describe what you're trying to do? Composite builds largely replaces the need for `GradleBuild` tasks.

**Comment by tasomaniac** [comment]
On CI, I use GradleBuild to create a very simple task that runs collection of tasks after doing some little configuration. This also allowed us to put plugins behind a flag during development. Applying those plugins would break Android Plugin's task configuration avoidance setup and cause thousands of tasks to be configured. 

```
project.tasks.create("ciCheck", GradleBuild) {
            startParameter = gradle.startParameter.newBuild() // copy from the real build. Needs to come first

            tasks = [ 'evaluateViolations', 'test', `jacocoTestReport`]

            startParameter.projectProperties['checkVariant'] = variant.name
        }
}
```

Not only I put only a single task to run at CI, but also I can put this special task as a shared run configuration into the IDE. 

That means by default all static analysis tools, Jacoco setup we have all gets configured and run when this special task runs. 

I achieve many things with only couple of lines and O love it 😊 Composite Builds replaces this task but then I would need to create a real project.

**Comment by tasomaniac** [comment]
People use dependsOn for this but not only it is fragile but also does not do the same thing. For example, adding test would automatically run all test taska from all subprojects. So, simple. Otherwise, I would need to dyanmically find tests tasks on all subprojects myself and depend on them.

**Comment by Vampire** [comment]
Can this issue be reopened please?
This is still a serious issue.
I just wanted to release a project using the gradle-release plugin which uses the `GradleBuild` task twice to isolate things and build with un-snapshotted version reliably.
But as this project is using an included build, it now blew up and the release does not work. :-(

**Comment by caeus** [comment]
I've been using composite builds for a while now. I'm trying now to register a GradleBuild task and I get the error `Cannot include build '***' in build '****. This is not supported yet.`

This is the error this issue refers to?

**Comment by chris-hatton** [comment]
Also run into this:  We wanted to define a higher-order Gradle project to orchestrate build across several others, decoupled from their complexities via `GradleBuild` invocation.  It was a blow to discover this doesn't work due to the child projects' use of Composite as the recommended `buildSrc` equivalent.

**Comment by Vampire** [comment]
You can use the tooling API instead. As that is also what IDE integrations use, it should always be up to date and working. I even got the release plugin to work by clearing the task actions and replacing them by a respective tooling API call.

**Comment by chris-hatton** [comment]
Thanks @Vampire .  Can you say if the [Tooling API](https://docs.gradle.org/current/userguide/third_party_integration.html#embedding) offer any efficiency over shell command, for the simple case of invoking a build?  i.e. ability to benefit from parallelism within the same Gradle daemon?

**Comment by Vampire** [comment]
> Can you say if the [Tooling API](https://docs.gradle.org/current/userguide/third_party_integration.html#embedding) offer any efficiency over shell command, for the simple case of invoking a build? i.e. ability to benefit from parallelism within the same Gradle daemon?

I do not think that when using the Tooling API the executed build will run in the same daemon either, as the daemon is still occupied with the build that invokes the other build, so iirc it will run in a separate daemon either way. I just think it is more clean to use the tooling API than to use a plain `exec` and you could also handle build results or streams more properly than when using a plain `exec`.

Btw. you do not need to include the tooling API like mentioned on the docs page you linked to, as the tooling API is already included in the Gradle distribution. So you can just simply use it from within a Gradle build.

> would you agree that if users are compelled to use the Tooling API to achieve builds; doesn't this indicate a shortcoming with the user API?

I would not object, which is also why I thumbs-uped this issue.
I think the `GradleBuild` task should be able to run composite builds.
But as long as this is not possible, using the tooling API is an alternative that works perfectly fine.
It just is not as declaratively as using a `GradleBuild` task, but more imperatively.
This is for example what I do to replace the `GradleBuild` actions of the release plugin using the tooling API:
```kts
configure(listOf(tasks.release, tasks.runBuildTasks)) {
    configure {
        actions.clear()
        doLast {
            GradleConnector
                .newConnector()
                .forProjectDirectory(layout.projectDirectory.asFile)
                .connect()
                .use { projectConnection ->
                    val buildLauncher = projectConnection
                        .newBuild()
                        .forTasks(*tasks.toTypedArray())
                        .setStandardInput(System.`in`)
                        .setStandardOutput(System.out)
                        .setStandardError(System.err)
                    gradle.startParameter.excludedTaskNames.forEach {
                        buildLauncher.addArguments("-x", it)
                    }
                    buildLauncher.run()
                }
        }
    }
}
```

**Comment by chris-hatton** [comment]
I was looking to make improvements to our setup where 'Gradle executes Gradle via shell' setup; and very excitedly stumbled upon the `GradleBuild` task.   Finding this page; I discovered that I did the exact same thing a year ago.
Same time again next year I guess?
I really think this should be re-opened.  Composite Builds are one of Gradle's most powerful features and I use them a lot, but their limitations are frustrating.

**Comment by Vampire** [comment]
What do you mean? The issue **is** open. And you can still use the tooling API in an ad-hoc task.

**Comment by tasomaniac** [comment]
Sorry for being the one, I just realized that I was the one opening this and decided it is best to close.

GradleBuild task itself is more than unideal. The console output becomes weird and it confuses a lot of people. Error handling is also not ideal. I think Gradle can deprecate this feature as they also do not maintain it.

Since there is an alternative now, it is best to close this.

**Comment by Vampire** [comment]
But why?

There always was that alternative.
That doesn't make the task less useful once it is fixed, probably by using the tooling API itself.

Also, that the task is currently not worked on, does not mean it is particularly unmainained.
It is just not within the focus of a team that is pretty constrained on resources and works on other topics.
But even then, a contributor could send a pull request that fixes this.

And it was already closed in the past, but reopened by Gradle staff.

As long as the task indeed is not officially deprecated, this issue is perfectly valid and stay open.
So please reopen it again so that we do not have to open a reanimation issue and make all voters and watchers switch over.

**Comment by piotrminkina** [comment]
A particularly good case where this can come in handy is the `initscript {}` block in initialization scripts. This is where Composite Builds don't work, and it would be useful to have something to make the work of implementing initialization plugins easier, especially in conjunction with building own Gradle distribution.

```groovy
initscript {
    // run `publishToMavenLocal` first in example project, because Gradle doesn't support Composite Builds here

    repositories {
        mavenLocal()
        gradlePluginPortal()
    }

    dependencies {
        classpath('com.example:init-plugin:latest.release') { emd ->
            emd.changing = true
        }
    }
}
```
