### ISSUE TITLE
Support OS distributions with ncurses 6.x 

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#825]
Since upgrade to Fedora 24 running Gradle in a GNOME Terminal (the standard terminal app) has undergone a few noticeable changes that are certainly undesirable and I'd argue are regressions:

* Gradle output is no longer colored. Everything output from Gradle is black text
* Ctrl+C no longer stops the Gradle process
* Gradle used to output progress through tasks like test (e.e. - Executing test 39 of 4049, 12 skipped.) That no longer occurs.

### Expected Behavior
Terminal behavior should be consistent among major OS distributions

### Context 
From the forums: https://discuss.gradle.org/t/terminal-problems/20319

### Your Environment
I think this affects Linux and Windows Cygwin environments (I haven't tried Cygwin personally).

### Suggested Fix
This is really a problem in the `native-platform` library we bundle with Gradle.  I've raised a separate issue there: https://github.com/adammurdoch/native-platform/issues/18

As a half-measure, we could fail more gracefully and explain to the user what may be broken.

**Comment by adammurdoch** [comment]
I've updated to a new version of `native-platform` with the fix. This also fixes a similar problem on newer versions of FreeBSD (different versions of the standard c++ library).

**Comment by adammurdoch** [comment]
Tried this out on a few different machines, seems to be working ok.

**Comment by big-guy** [comment]
Thanks @adammurdoch
