### ISSUE TITLE
Use `$Dsl` for generated decorated classes

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#8254]
Changing the suffix of the generated task classes from `_Decorated` to `$Dsl` broke the IDEA import (https://github.com/gradle/gradle/issues/8244). We reverted the change to keep the import working (#8247).

Jetbrains will fix the issues on there side and maybe Gradle will provide some public API to query the original class name for generated classes (#8252).

For Gradle 6.0, we should probably change the suffix again to `$Dsl` (or something else).

**Comment by melix** [comment]
I'm pretty sure I used the `_Decorated` trick in the past in a plugin, so I think this issue is more widespread than just the IDEA import. We should be very careful.

**Comment by wolfs** [comment]
@melix You are not the only one.

We should provide a public API (#8252) and then announce the API and have people use it. Gradle 6.0 for changing the name might be too aggressive, though I think we should at least consider the change for that release.

I can't think of a way to deprecate relying on the class name of the generated classes to see how many plugins are affected...
