### ISSUE TITLE
ClassLoaderCache less effective for composite builds in IntelliJ IDEA 

### ISSUE THREAD

**Issue by GFriedrich** [gradle/gradle#8256]
When using IntelliJ IDEA for a composite build, the ClassLoaderCache doesn't work as expected.

### Expected Behavior
When working in the same project, I would expect that the ClassLoaderCache keeps all ClassLoader instances that are created by the Daemon that gets started by IntelliJ IDEA when opening a build.gradle(.kts) file of an included build.

### Current Behavior
When opening the build.gradle file of an included build, IntelliJ IDEA will first configure the outer root project and afterwards a new session in the same Daemon is started to configure just the project of the included build.

### Context
To me it looks like this makes the ClassLoaderCache for IntelliJ IDEA less effective.

### Steps to Reproduce (for bugs)
Have 3 project (A, B, C). Project A includes the project B and C via ```includedBuild```.
Opening the build.gradle(.kts) of B or C results in the configuration of the root project A first, which creates ClassLoaders for A, B and C and afterwards another configuration takes place resulting in the drop of the ClassLoaders for A and B/C (depending on which build.gradle(.kts) you've opened. (Of course this gets worse if you have a much bigger composite build project.)

### Your Environment
Gradle 5.1.1 + IntelliJ IDEA 2018.3.3

I'm not very familiar will all of the internals of Gradle and I'm not even sure whether this ticket should be created here or in the bugtracker of JetBrains, but I would be happy if you could take care of this (and in case this is the wrong place, create a ticket for IntelliJ IDEA and communicate a solution to them).
Thanks in advance.

**Comment by GFriedrich** [comment]
When using the Kotlin DSL I came across an additional problem connected to this issue here (I could image it's the same problem for Groovy):
I took a deeper dive into the sources of Gradle and found that the compiled Kotlin scripts are cached via CrossBuildInMemoryCache and resolved via a key containing the classloader. Unfortunately the classloaders are recreated (as mentioned before) which results in at least a reloading of the compiled scripts (or even a recompilation - it's hard to tell as this is deep down in the Gradle rabbit hole and I didn't want to debug all this, so this conclusion is just from reading the code - no guarantee or whatsoever).
I'm wondering whether it would be possible to hold the classloaders in the ClassLoaderCache in the same way as the CrossBuildInMemoryCache holds its classes via a SoftReference if the class was loaded several builds ago (again I don't have a clue which additional strings are connected to this - I'm sure you know far better than I do).

**Comment by GFriedrich** [comment]
I'm still interested in this, but didn't have the time yet to check the issue for one of the latest versions of Gradle and/or IntelliJ IDEA.
In case I've time for this, I will post an update.

**Comment by ljacomet** [comment]
Please consider adding a reproducer, that would help someone else look into this, including the Gradle team

**Comment by ljacomet** [comment]
The way this works has changed in recent Gradle and IntelliJ IDEA versions, so this issue is obsolete.
