### ISSUE TITLE
Follow the Freedesktop XDG base directory standard (in Linux)

### ISSUE THREAD

**Issue by x80486** [gradle/gradle#8262]
On Linux, Gradle currently creates a `$HOME/.gradle/` (or `$HOME/.gradle-kotlin-dsl/`) folder in the user's home directory. Most applications/programs don't create a folder in the user's home directory anymore, but instead use the `Freedesktop XDG` standard – found here: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html.

Using this standard:
- `$XDG_CACHE_HOME` says "temporal/non-essential" files go to `$HOME/.cache/`
- `$XDG_CONFIG_HOME` says "configuration files" go to `$HOME/.config/`
- `$XDG_DATA_HOME` says "data files" go to `$HOME/.local/share/`

This is just a request to consider using this standard. It makes a lot of sense; it is easy for the user to understand, makes it easier to backup / locate / restore / manage / clear user's data, and creates less clutter in the user's home directory.

Thanks in advance...and thanks so much for everyone's hard work on this – it's amazing!

**Comment by big-guy** [comment]
As much as I would like something like this, I don't think we're going to do this for a few reasons:

- We need to provide a familiar experience across all major platforms (Linux, macOS, Windows).  ~/.gradle (GRADLE_USER_HOME) does that for the most part.  If we were to adopt the XDG standard for Linux, I think we would want to do the proper thing for every platform (e.g., using %AppData% on Windows) and that would make things more different for better or worse.
- We have backwards compatibility concerns.  People rely on configuration files in GRADLE_USER_HOME to keep their builds working, so we would need to support both locations for awhile.  Similarly, some people expect to be able to copy GRADLE_USER_HOME and reuse it.
- We have cross-version concerns.  Some of the directories under GRADLE_USER_HOME are shared by multiple versions of Gradle.  We can't update the already released versions of Gradle, so we would have to either live with two copies of some things or support both locations.
- I think there's also an issue with people using an old wrapper jar to install newer version of Gradle. This would stop working or use the old location.

If there's a lot of interest in this, maybe there are some smaller steps we could take to make this better.

**Comment by piegamesde** [comment]
> If we were to adopt the XDG standard for Linux, I think we would want to do the proper thing for every platform

The XDG standard is platform-agnostic and not limited to Linux.

> We have backwards compatibility concerns.

Are there backwards compatibility issues that cannot be solved with symlinking folders? Also, major version bumps are not expected to be backwards-compatible.

> We have cross-version concerns.

This is a temporary issue. Nobody will use the old versions forever, and as time goes by, fewer and fewer installations will use the old directory.

**Comment by lhanson** [comment]
Agreed, I've seen all of these concerns addressed pretty neatly in a number of projects making the transition. Please reconsider.

**Comment by Xerus2000** [comment]
I am also highly in support of this, our home directory deserves to be free!

**Comment by carl-mastrangelo** [comment]
I too would like to raise support for this issue.  My use case:   I periodically back up my $HOME directory using rsync.  I pass `--exclude=~/.cache/` to rsync to avoid backing up cache-able files.  While waiting for the backup to complete today, I noticed it was taking a pretty long time.   Looking at the logs, it was spent mirroring many gigs of `~/.gradle/caches`.  

If Gradle had followed the pattern of putting its caches in a consistent folder, it would have saved me the time of having to look into this, and adding more special cases to my backup scripts.

**Comment by xerus2000** [comment]
Although actually, almost everything in the folder is some sort of cache. This would be the structure as I see it:
- put the gradle.properties into `${XDG_CONFIG_HOME:-~/.config}/gradle`
- everything else goes into `${XDG_CACHE_HOME:-~/.cache}/gradle`

So the change wouldn't have to be big.

That can't currently be replicated because the `gradle.properties` is only searched for in `GRADLE_USER_HOME`. A first step could be to simply search the above config location additionally. Then we could set `GRADLE_USER_HOME` to .cache/gradle and it should work rudimentarily.

**Comment by serebit** [comment]
+1 for this. I can set Gradle to use the proper dirs, but it should really use them by default. Please reconsider.

**Comment by cwrau** [comment]
As for the `GRADLE_USER_HOME` concern, lots of projects use the XDG standard and still have their own flags / env vars to specifically use another location.

You could do the same; if `GRADLE_USER_HOME` is set, only use that directory (maybe with an info message?), otherwise use the XDG folders

**Comment by dragetd** [comment]
Please follow the XDG directory standard. Gradle could check for ~/.gradle and default to the old bahaviour but allow (and default to) the XDG standard.

**Comment by soloturn** [comment]
@big-guy the suggestion of @dragetd seems to be a very neat one, don't you think, for two years or so? the current behaviour is very cumbersome in windows corporate environments as all the distributed file caches follow the windows %appdir% structure. you want me to create ticket for this, or change the title here to make it a platform independent problem?

**Comment by timkrueger** [comment]
Please help to clean __my__ home directory and follow the XDG Base Directory Specification [1]. 

Thanks for doing Gradle! I use it since a few days and enjoy it.

[1]  https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by dragetd** [comment]
Hm, this is unfortunate.

For those stumbling over this in the future, I use a script that helps me here:

```
#!/bin/sh

FAKE_HOME="${XDG_CONFIG_HOME:-$HOME}/.config/noXDG"

# Get the real path of this script
SCRIPT=$(readlink -f "$0")

# And the called command
CMD="$(basename $0)"

# Exec
which -a "$CMD" | {
  while read -r EXEPATH; do
    if [ "$(readlink -f $EXEPATH)" != "$SCRIPT" ]; then
      exec "$EXEPATH" "$@"
    fi
  done
  echo "fake-home could not find executable shadowed by $CMD" >&2
  exit 1
}
```

This is in my .local/bin directory and has symlinks for any app onto fake-home to fix this bug.


As for gradle, maybe the developers are willing to at least discuss it again if it was contributed as an external contribution? One that respects backward-compatibility and is configurable?

**Comment by serebit** [comment]
Yeah, given the support for this feature it seems a little odd that it was closed without any clarifying comments as to why.

**Comment by soloturn** [comment]
@big-guy, @donat  here from apple where they expect files: https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFileSystem/Articles/WhereToPutFiles.html. user home is a nogo there. they have a cache directory as well.

for the reasons above, there seems to be a solution for all of them:

- operating system specific locations are the rule, not the exception, gradle is sticking out. gradle sticking out breaks the backup experience as well, as it does not backup essential user data but a huge gradle cache,  if one does not exclude it.
- for backward compatibility one can check if .gradle exists for a couple of time.
- running multiple versions of gradle is not an issue, 2 copies wil stay, or a user will link the directories if bothering too much.
- if the old wrapper jar is used, also not problem. whoever has a problem will with pleasure upgrade.

**Comment by sdavids** [comment]
Please consider reopening ...

**Comment by mattfbacon** [comment]
This feature is still missing and especially for such a widely used tool I find it surprising that this is not being prioritised.

**Comment by soloturn** [comment]
@big-guy if you ask for smaller steps, can you imagine that you put created files which can be lost in xdg_cache_dir ? this would already solve the backup problem. default is easy for all operating systems:
* linux: ~/.cache/gradle/
* windows: %LOCALAPPDATA%
* macos: ~/Library/Caches/gradle/

**Comment by martinda** [comment]
Same here. In corporate land we have NFS and hosts everywhere. The `/home` is NFS mounted to all the hosts we can access, so `/home` is the worst for caching anything because of quotas and performance. My hack is to have the user properties in `~/.gradle/gradle.properties`, and `GRADLE_USER_HOME` on a local disk as `GRADLE_USER_HOME=/localdisk/.gradle`, and lastly have a symbolic link pointing back to `/home`:
```bash
$ ls $GRADLE_USER_HOME/gradle.properties
lrwxrwxrwx  1 user group 39 May 31  2021 gradle.properties -> /home/user/.gradle/gradle.properties
```

But I also discovered data in `~/.cache/gradle`, and I am not sure where that comes from. In there I see a list of hostnames. It looks like this snippet:

```
$ tree .cache/gradle
├── host001
│   ├── caches
│   │   ├── 8.5
│   │   ├── CACHEDIR.TAG
│   │   ├── jars-9
│   │   ├── journal-1
│   │   ├── modules-2
│   │   └── transforms-3
│   ├── daemon
│   │   ├── 8.5
│   │   └── CACHEDIR.TAG
│   ├── gradle.properties -> /home/user/.gradle/gradle.properties
│   ├── native
│   │   ├── 38dada09dfb8b06ba9b0570ebf7e218e3eb74d4ef43ca46872605cf95ebc2f47
│   │   ├── c067742578af261105cb4f569cf0c3c89f3d7b1fecec35dd04571415982c5e48
│   │   └── jansi
│   └── notifications
│       └── 8.5

```
