### ISSUE TITLE
Suggestion: Add a simplified way to link javadoc to relevant JDK javadoc

### ISSUE THREAD

**Issue by simonbasle** [gradle/gradle#8267]
### Expected Behavior
It should be easy to link to the JDK javadocs in a java project's javadoc.

In order to avoid the ceremony of detecting the build's JDK version and correct URL to use (see below), it could come in the form of a `linkToJdk()` method in Javadoc task's `options`.

This method would append the correct URL for the `JavaVersion.current()` to the external links, the same way `links(...)` appends (but taking the URL from an hardcoded `Map` keeping the correct one relative to each `JavaVersion.majorVersion`).

### Current Behavior
All links must be manually provided by the user, but in the case of the JDK javadocs there is both some overhead and an issue with differing URL templates between javadocs for Java 8-10 and Java 11+.

### Context
There are two problems since JDK11:
  - If the build's JDK is JDK11 or above, it will fail to link to JDK docs from an earlier version, with the `javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/9/docs/api/ are in the unnamed module` message.
  - The JDK javadoc URL cannot simply be inferred from `JavaVersion.current().majorVersion`, as since JDK11 the template has changed:
    - `https://docs.oracle.com/javase/8/docs/api/`
    - `https://docs.oracle.com/javase/9/docs/api/`
    - `https://docs.oracle.com/javase/10/docs/api/`
    - `https://docs.oracle.com/`**en/java/**`javase/11/docs/api/`

### Steps to Reproduce (for information)
Building a java project with a javadoc link to https://docs.oracle.com/javase/8/docs/api/ with JDK11 should display the first issue. Replacing `8` with `11` will also fail.

**Comment by douira** [comment]
too bad this was closed, this would be a useful feature.

**Comment by ljacomet** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.
