### ISSUE TITLE
Extending another project's configuration uses current project's configuration instead

### ISSUE THREAD

**Issue by labkey-susanh** [gradle/gradle#8275]
Creating a configuration for moduleB that extends a configuration from moduleA uses the dependencies from moduleB's configuration instead of moduleA's.

### Expected Behavior

The dependencies for moduleB's configuration should be those of the extended configuration in moduleA.

### Current Behavior

The dependencies for moduleB's configuration are the ones declared in moduleB, not the ones from moduleA (even if moduleB does not have a configuration by the same name).

### Context

We use a multi-project build and many projects depend on a central API project that includes many external dependencies.  We produce separate, semi-portable jar files for each project and each of these jar files includes the external jars that it depends on.  However, we want to eliminate the jar files that are already included in the API project to reduce the size of the jar files we build.

We had been doing this by referencing the API project and then getting the appropriate configuration to do the deduplication (e.g., project.project(":api").configurations.external).  Since upgrading to Gradle 5.0, we are seeing warning messages like so

`The configuration :server:api:external was resolved without accessing the project in a safe manner. This may happen when a configuration is resolved from a thread not managed by Gradle or from a different project. See https://docs.gradle.org/5.0/userguide/troubleshooting_dependency_resolution.html#configuration_resolution_constraints for more details. This behaviour has been deprecated and is scheduled to be removed in Gradle 6.0.`

The referenced documentation provides a good suggestion for how to resolve it:

> In most cases, the deprecation warning can be fixed by defining a configuration in the project where the resolution is occurring and setting it to extend from the configuration in the other project.

This does not work, unfortunately unless I'm misunderstanding what is being suggested.

### Steps to Reproduce (for bugs)

The attached example is a simple two-project build with a single task "showDedupes" that illustrates the problem.  

[gradleCrossConfig.zip](https://github.com/gradle/gradle/files/2775144/gradleCrossConfig.zip)

### Your Environment

* Gradle 5.1.1
* Java 11

**Comment by labkey-susanh** [comment]
Is there any chance this problem will get addressed for Gradle 6.0?  (I've just tried with my simple example project provided here and Gradle 5.6.2 but the problem persists.) We will likely need to switch to 6.0 soon after it is released in order to get Java 13 support, so I'm trying to understand if I need to find an approach other than the one suggested in the docs to be able to do our dependency subtraction.

If you have suggestions for a different approach, that would also be appreciated.

**Comment by melix** [comment]
This is not going to be fixed in 6.0 because extending another project configuration is unsafe. Instead, we have updated the documentation to reflect this: https://docs.gradle.org/release-nightly/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors

**Comment by melix** [comment]
Note that you can easily share dependencies using, for example, the Java Platform plugin, which is safer.

**Comment by ljacomet** [comment]
Closing as documentation has been updated and there is no plan to allow extending configurations across project boundaries.
