### ISSUE TITLE
NullPointerException in wrapper when `lib` directory doesn't exist on disk yet

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#8289]
Gradle version: 5.0-milestone-1

Got this error, but not reproducible:
``` 
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

Seems there might be a race condition that rarely happens between unzipping the downloaded gradle dist and loading the launcher jar from the `lib` directory.

In `org.gradle.wrapper.Install#unzip`, I think each file/directory needs to be sync'd before you try to read back from it. `close()`ing the Stream does not guarantee that it will be written to the underlying disk. So it is it possible that `lib` doesn't yet exist on disk when you call `new File(gradleHome, "lib").listFiles()` in `BootstrapMainStarter.findLauncherJar`, resulting in a NPE.

I think we need to call `.getFD().sync()` on the `FileOutputStream` in `Install#unzip`.

Would you accept a PR to address this?

**Comment by big-guy** [comment]
Hmm, that doesn't sound right to me.  I would find it very surprising if writing to a file, closing it and then re-reading the same file could sometimes appear as a missing file.  I think `sync()` is only going to guarantee that the _contents_ of the file are written persistently, but this failure is about entirely missing files.

I think a reasonable PR would be to change `BootstrapMainStarter` to look at the return value of `listFiles()` and produce a better error message.  `listFiles()` returns null when `gradleHome/lib` is not a directory and when an I/O error occurs.  We could check for null and fail with more information.

Is it possible that the directory the distribution was extracted to was on a shared mount or were there multiple Gradle builds trying to extract the same distribution?

When this happened, did the next build succeed?

**Comment by big-guy** [comment]
Closing until we have more information/reproducible case.

**Comment by cobexer** [comment]
gradle does not recover from this error and all following builds fail with the same error!

**Comment by JmeterChen** [comment]
when i build  a gradle project  got the errors,how to solve it???
![image](https://user-images.githubusercontent.com/34080816/87763947-29a37480-c848-11ea-86e5-68430488f963.png)
