### ISSUE TITLE
Yall broke the gradle daemon

### ISSUE THREAD

**Issue by mcandre** [gradle/gradle#8291]
### Expected Behavior

`gradle <task>` can be run hundreds of times in succession without issue.

### Current Behavior

* The Gradle daemon runs out of metaspace after just a handful of builds of Hello World.
* The Gradle daemon crashes, corrupting the file hash cache.
* Not even `gradle clean` can run when the file hash cache is corrupt.
* Gradle offers no built-in task to clear the file hash cache (have to find all `*.lock` files in `$HOME/.gradle` recursively and delete them).
* Configuring `org.gradle.daemon=false` in `$HOME/.gradle/gradle.properties` triggers an annoying banner:

> To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.1.1/userguide/gradle_daemon.html.
> Daemon will be stopped at the end of the build stopping after processing

### Your Environment

macOS Mojave, OpenJDK 11, Gradle 5.1.1

**Comment by big-guy** [comment]
> The Gradle daemon runs out of metaspace after just a handful of builds of Hello World.

Do you have an example build you can share? 

> Configuring org.gradle.daemon=false in $HOME/.gradle/gradle.properties triggers an annoying banner:
>> To honour the JVM settings for this build a new JVM will be forked.

Are you also setting `org.gradle.jvmargs`?
