### ISSUE TITLE
Generating HTML test report takes > 30 minutes with over 100,000 unit tests

### ISSUE THREAD

**Issue by ymwang1984** [gradle/gradle#8294]
### Expected Behavior

The time spent to generate test report should scale well with number of tests run.
### Current Behavior

Generating test report probably takes O(N*N) with number of tests as N.

In our company, some applications have over 300,000 unit tests, and developers are surprised to discover that running their unit tests takes: only 5 minutes to actually run the tests and **> 30 minutes** to generate the HTML report. The larger the application, the longer it becomes to generate test reports. In the end, our developers have to disable HTML test reports.

### Context

People have to disable HTML test reports, especially for large scale applications. But developers do like the HTML report format.

After some analysis, we have a pretty good idea about what the issue comes from, most likely it is from this file: ClassPageRenderer.java

https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/testing-base/src/main/java/org/gradle/api/internal/tasks/testing/report/ClassPageRenderer.java

In this file
(1) at Line 54, we start to iterate through all our tests. Goes to Line 55 and onto Line 78 `renderTableRow` method.
(2) at Line 80, in each iteration we have to determine the table row. Goes to Line 80 and onto Line 60 `determineTableRow` method.
(3) at Line 61, we call a method `methodNameColumnExists()` which is Line 86 and we start to iterate through all tests again!

So in the end, the complexity is about O(N*N). At least that's about the scalability that we see in real applications.

Potentially, it can be fixed by simply caching the table rows since it is the same for every test, such as the below diff:

[renderer.txt](https://github.com/gradle/gradle/files/2780955/renderer.txt)

### Steps to Reproduce (for bugs)

[groovy.zip](https://github.com/gradle/gradle/files/2780964/groovy.zip)

Can use the above zip to demonstrate the problem, it is a simple Java project with a single test file that has 50,000 tests.

`./gradlew clean build` takes at least 3 minutes, and over 2 minutes are spent generating the HTML report.

In build.gradle, if we toggle `reports.html.enabled = true` to `false`, the build time will be drastically reduced. That proves that the most time are spent generating reports.

### Your Environment

 * Build scan URL:

**Comment by ymwang1984** [comment]
@blindpirate  Thank you for the quick response!

**Comment by blindpirate** [comment]
I guess this is only a noticeable issue when a single test class contains 100,000 test cases, right?

**Comment by ymwang1984** [comment]
Yes I think so. It does not show up when the number of tests is not that big.

In my company, some large applications recently started to use a new pattern called "branch permutation tests" so their number of tests suddenly explodes. And then developers started to notice this build performance problem.

Will it be worthwhile to backport this change to some Gradle 4 version?

**Comment by blindpirate** [comment]
I think it's definitely worthwhile for your scenario, but unfortunately, we currently don't have any plan to maintain 4.x...

**Comment by blindpirate** [comment]
This would be fixed in 5.2RC1. 

> I do wonder: why report on successful tests at all? Is there a compelling case for them?

I think I would like to see a big picture of my tests - how many tests succeed, how many tests fail, and I also want to see how long the successful tests take. This discussion seems to be out of this issue scope - but anyway, thank you again for reporting!

**Comment by ymwang1984** [comment]
We've verified that 5.2-rc-1 fixes the issue. Thanks @blindpirate 

cc @jasongilanfarr
