### ISSUE TITLE
Enhancement: Soft assert on check tasks

### ISSUE THREAD

**Issue by mcandre** [gradle/gradle#8296]
### Expected Behavior

`gradle check` continues processing all configured linters (e.g. Checkstyle, PMD, Spotbugs), regardless of whether one or more of them fail. The final exit code reflects whether any of these checks failed.

### Current Behavior

Gradle terminates early on the first failing check, which unfortunately makes it difficult to get a full report of all the linter warnings at once.

### Context

This behavior makes it difficult to assess how many total linter warnings exist for a large codebase, and therefore how much time would be required to resolve them.

### Your Environment

macOS Mojave

**Comment by big-guy** [comment]
You can run with `--continue`, which will give you what you want, I believe.
