### ISSUE TITLE
Maven [16.0.6] "range" should be interpreted as strictly

### ISSUE THREAD

**Issue by melix** [gradle/gradle#8297]
### Context

Currently, Gradle parses `[16.0.6]` as a dynamic selector. However, the specs for Maven says that this is a "hard" requirement on `16.0.6`. So instead, we should parse it as `strictly 16.0.6`.

**Comment by oehme** [comment]
Nothing in Maven is a hard requirement though. It just uses the first version it sees. Only the enforcer plugin will complain and a lot of people don't use that. I suspect you might break more builds than you would hope if you make this strict in Gradle.

**Comment by jjohannes** [comment]
Following the comment above, we will not change the behavior of interpreting [16.0.6] to be as compatible as possible with Maven's behavior.

Strict versions can be published in Gradle Module Metadata.

We can however parse this as a _single required_ version which would be performance optimization: #11185
