### ISSUE TITLE
Two copy tasks with the same outputDir remove contents when --rerun-tasks is used

### ISSUE THREAD

**Issue by martin-linha** [gradle/gradle#8299]
### Expected Behavior

I have two tasks of type `Copy` - **firstCopy** and **secondCopy**. Both tasks have the same output directory (_build/destination_), specified via `into` statement. The **secondCopy** task depends on **firstCopy**.

After execution of `gradle secondCopy --rerun-tasks`, I expect to have all the input files from both tasks in the _build/destination_ folder.

### Current Behavior

Currently, after executing `gradle secondCopy --rerun-tasks`, I get only input files from secondCopy task, although the firstCopy task is executed properly as well.

It happens if and only if there is no local cache (no .gradle directory in my project) and the gradle command is exectuted with `--rerun-tasks`.

- If `--rerun-tasks` is missing, everything works as expected. 
- If I first execute `gradle secondCopy`, which creates the local Gradle cache and afterwards `gradle secondCopy --rerun-tasks` it suddenly works.

Note, if I downgrade to Gradle 4.6, everything works as expected.

### Context
I am trying to copy some files to the same output directory by using two tasks of type Copy. However, it seems the second one removes the contents of in the output directory first.

#### 1.
Use the following simple build.gradle

```
apply plugin: 'java'

task firstCopy(type: Copy) {
    from 'first.file'
    into 'build/destination'
}


task secondCopy(type: Copy) {
    from 'second.file'
    into 'build/destination'
}

secondCopy.dependsOn firstCopy

```

#### 2.

create two empty files - first.file and second.file in the root of the project

#### 3.

ensure, there is no .gradle folder in the project and execute

`gradle secondCopy --rerun-tasks`

#### 4.

check build/destination folder - it contains only second.file and missing first.file (which was somehow removed by the secondCopy task)

#### 5.

in case the cache exists, it will work fine, do:

1.  remove .gradle folder
2.  run `gradle secondCopy`
3. see that first.file and second.file are present
4. remove build folder, but keep the .gradle folder
5. execute `gradle secondCopy --rerun-tasks`
6. **see that first.file and second.file are suddenly present**

### Your Environment
Gradle 5.1.1 (with 4.6 works perfectly)

**Comment by wolfs** [comment]
@martin-linha Thank you for your bug report! Even though your instructions are very specific, I fail to reproduce the bug with Gradle 5.1.1.
This is what I did:
- Start with an empty project `.gradle` folder and the setup described in step 1 & 2
- Run `gradle secondCopy --rerun-tasks`

Then `build/destination/first.file` and `build/destination/second.file` exist.

Can you please check your reproduction steps?

**Comment by martin-linha** [comment]
Hi @wolfs,

yes, the steps are correct and I have reproduced it multiple times. Forgot to mention I use Gradle wrapper, assume it does not change much though.

![gradleissue](https://user-images.githubusercontent.com/8123842/51548620-feb1ad80-1e68-11e9-849d-31800d548adb.gif)

**Comment by wolfs** [comment]
@martin-linha I can reproduce the problem, it seems to happen on Windows only...

**Comment by martin-linha** [comment]
@wolfs, I do not reckon so - I have tested it on centOS and the same story.

**Comment by wolfs** [comment]
I'll close this issue. Please re-open if you can still reproduce it with the nightly version above.
