### ISSUE TITLE
Remove old JAR when version changes when using 'java' plugin

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#830]
When changing the `project.version` on a project using the `'java'` plugin, the JAR that was built with the older version is not removed.

```
$ ./gradlew jar
$ ls build/libs/
myapp-0.1.0.jar
## Change version in build.gradle from '0.1.0' to '0.2.0'
$ ./gradlew jar
$ ls build/libs/
myapp-0.1.0.jar myapp-0.2.0.jar
```

### Expected Behavior

I would like the out-of-date JAR output to be removed when the inputs change, so that only the currently declared JAR is output after a `./gradlew build`.

### Current Behavior

Multiple JARs are kept in the `build/libs` directory when input properties/convention mappings are changed

### Context

This issues comes up for us when trying to coordinate Docker builds with something like the Spring Boot plugin that repackages an entire application into an uber JAR. We want to take the output artifact from Gradle and shove it into an image without having to move between the different applications. It would be ideal if a user doesn't have to run `./gradlew clean` when they change the `project.version`

*Example Dockerfile*
```docker
FROM java/openjdk-8-jre

ARG APP_HOME=/app/springboot

WORKDIR $APP_HOME
EXPOSE 8080
COPY build/libs/*.jar $APP_HOME/application.jar

CMD ["java", "-jar", "application.jar"]
```

#### Workarounds

I believe a workaround we could do would be to add a commands like `ARG` and provide the location of the JAR at build time. We are mostly running newer versions of Docker so 

```docker
FROM java/openjdk-8-jre

ARG SPRINGBOOT=build/libs/myapp.jar
ARG APP_HOME=/app/springboot

WORKDIR $APP_HOME
EXPOSE 8080
COPY $SPRINGBOOT $APP_HOME/application.jar

CMD ["java", "-jar", "application.jar"]
```

Another option for us could could also be to build the JAR without the version in it even when it is defined in the `build.gradle`.

### Steps to Reproduce (for bugs)

1. Set `version = '0.1.0'`
1. Apply the `'java'` plugin
1. Run `./gradlew jar`
1. set `version = '0.2.0'`
1. Run `./gradlew jar`

### Your Environment

* Gradle 3.1
* Docker 1.12

```groovy
plugins {
  id 'org.springframework.boot' version '1.4.2.RELEASE'
}
```

**Comment by eriwen** [comment]
@mkobit Thank you for the well-written issue.

Another workaround is that you can [customize the `archiveName`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html) to exclude the version

```
jar {
    archiveName = "${baseName}-${appendix}-${classifier}.${extension}"
}
```

**Comment by bmuschko** [comment]
I don't think we want to clean out the output from a previous execution per-se just because an input changed. There might be other viable use cases that would require it to still be there.

Another option you have here is to generate the Dockerfile at build time and populate it with the information you have available. You can either write a task yourself or use the `Dockerfile` task type from the [Gradle Docker plugin](https://github.com/bmuschko/gradle-docker-plugin).

Can we close the issue given that you can generate the JAR file without the version number and the other options I proposed?

**Comment by mkobit** [comment]
@bmuschko I think the different options above provide enough flexibility to solve this in other ways that don't make a huge change in how the `Jar` task currently works.

Closing.
