### ISSUE TITLE
Scala (v2.11.11) classes missing from fat JARs

### ISSUE THREAD

**Issue by mcandre** [gradle/gradle#8307]
### Expected Behavior

All classes needed by a Scala source appear in the JAR artifact created by `gradle shadowJar`, with the com.github.johnrengelman.shadow v4.0.4 plugin. (This fat JAR plugin integrates fairly well with plain vanilla Java, Kotlin, Clojure, and Groovy. Just not the latest Scala builtin plugin.)

### Current Behavior

When I try to run my fat JAR, I get an error about some critical Scala classes missing from the JAR:

```console
$ java -jar build/libs/args.jar a b c
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function1
	at us.yellosoft.args.Args.main(Args.scala)
Caused by: java.lang.ClassNotFoundException: scala.Function1
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

For what it's worth, this used to work back in the day with Gradle v2, Java v8, Scala library v2.11.1. Not sure what broke.

### Workaround

Update Scala library to v2.12.4.

### Steps to Reproduce (for bugs)

1. Write a Scala application targeting dependency `compile 'org.scala-lang:scala-library:2.11.12'`.
2. Add `id 'com.github.johnrengelman.shadow' version '4.0.4'` plugin.
3. Run `gradle shadowJar`.
4. Run `java -jar build/libs/<project>.jar [<arguments>]`

### Your Environment

```console
$ gradle --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by big-guy** [comment]
I don't see this behavior. The fat jar has Scala inside it.  Is it possible you ran `gradlew jar` which overwrote the shadow jar?  Please reopen with a repository with a reproducible case or a zip of a reproducible example.
