### ISSUE TITLE
Scala classes violate Spotbugs

### ISSUE THREAD

**Issue by mcandre** [gradle/gradle#8308]
### Expected Behavior

Class files generated by Gradle for Scala source (e.g. with Scala library v2.12.4) pass default Spotbugs, assuming no user Scala code violates Spotbugs.

### Current Behavior

The class files generated from Scala sources trigger Spotbugs rule violations such as `MS_PKGPROTECT`. I'm not sure whether this is an issue with Gradle or perhaps with Scala itself. Could someone chime in?

### Steps to Reproduce (for bugs)

Add Spotbugs to `build.gradle`:

```gradle
plugins {
    id 'com.github.spotbugs' version '1.6.9'
}

apply plugin: 'com.github.spotbugs'

spotbugs {
    sourceSets = [sourceSets.main]
}
```

Then write some *.scala code:

```scala
package us.yellosoft.args

object Args {
    def main(args : Array[String]) : Unit = args.foreach(println)
}
```

Then run `gradle check`.

Then open the Spotbugs results in `build/reports/spotbugs/main.html`.

### Workaround

For now, I am disabling this rule for Scala sources, with a Spotbugs `excludes.xml` file:

```xml
<FindBugsFilter>
    <Match>
        <Source name="~.*\.scala" />
        <Bug pattern="MS_PKGPROTECT" />
    </Match>
</FindBugsFilter>
```

### Your Environment

```console
$ gradle --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.2 x86_64
```

**Comment by big-guy** [comment]
Just based on FindBugs exclude files I see around, this is something that needs to be fixed on the SpotBugs/FindBugs side (with a different set of defaults for Scala files) or in your project, by excluding this particular bug check from Scala sources.
