### ISSUE TITLE
Improve implementation of available-at in Gradle metadata

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#8315]
Currently the implementation of the `available-at` feature of Gradle metadata relies on adding a dependency.
This scheme breaks if `transitive = false` is used at the dependency or configuration level.

Ideally variants `available-at` should behave as if they were declared in-place.

See [these lines](https://github.com/gradle/gradle/blob/e5f027d0602ace69fa8ce61de282b6324a3181c2/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/ModuleMetadataParser.java#L155-L158) in the implementation.

**Comment by jjohannes** [comment]
Another problem is that you cannot distinguish these "artificial" dependencies from "real" dependencies in a resolution result.

This is a problem for the Kotlin multiplatform plugin, so it has to rely on some heuristics to make the distinction.

**Comment by ljacomet** [comment]
Will be fixed in 6.8
