### ISSUE TITLE
CoffeeScriptCompile task failure: cannot find dependency

### ISSUE THREAD

**Issue by w-kaluza** [gradle/gradle#832]
### Expected Behavior

I would like to be able to compile CoffeeScript to JavaScript using the built-in CoffeeScriptCompile task type.

### Current Behavior

Running a gradle task of type CoffeeScriptCompile produces an error:
	
    Could not find org.coffeescript:coffee-script-js:1.3.3.

The dependency name and version is specified in CoffeeScriptExtension.java

### Context

I require a build task which

* accepts as input a set of *.coffee files from one or more directories,
* outputs *.js files to a specified directory. If the source dirs contained subdirectories, their structure should be preserved in the output.
	
Additional documentation/tutorials on using SourceTask and its extensions is also desirable.

### Steps to Reproduce (for bugs)

The build.gradle file used:

    import org.gradle.plugins.javascript.coffeescript.CoffeeScriptCompile

    apply plugin: 'coffeescript-base'

    repositories {
        jcenter()
        mavenCentral()
    }

    task compileCoffee(type: CoffeeScriptCompile) {
        source file('cs')
        destinationDir file('js')
    }

Output:

    $ gradle compileCoffee
    :compileCoffee FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Could not resolve all dependencies for configuration ':coffeeScriptBasePluginJs'.
    > Could not find org.coffeescript:coffee-script-js:1.3.3.
      Searched in the following locations:
          https://jcenter.bintray.com/org/coffeescript/coffee-script-js/1.3.3/coffee-script-js-1.3.3.pom
          https://jcenter.bintray.com/org/coffeescript/coffee-script-js/1.3.3/coffee-script-js-1.3.3.js
          https://repo1.maven.org/maven2/org/coffeescript/coffee-script-js/1.3.3/coffee-script-js-1.3.3.pom
          https://repo1.maven.org/maven2/org/coffeescript/coffee-script-js/1.3.3/coffee-script-js-1.3.3.js
      Required by:
          project :

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 31.06 secs

### Your Environment

Output of gradle --version:

    ------------------------------------------------------------
    Gradle 3.2-rc-3
    ------------------------------------------------------------

    Build time:   2016-11-07 15:32:33 UTC
    Revision:     5d11ba7bc3d79aa2fbe7c30a022766f4532bbe0f

    Groovy:       2.4.7
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
    OS:           Windows 10 10.0 amd64

**Comment by eriwen** [comment]
Looks like the coffeescript module has been removed from JCenter and/or Maven Central. This fix would be to find where it moved to or provide an alternative.

**Comment by bmuschko** [comment]
I believe the CoffeeScript plugin has never been in a state ready for public consumption. It was part of the Gradle code base but we never announced it as a feature. 

Maven Central doesn't allow for removing published artifacts so I doubt the CoffeeScript JS was every available there. I'd suggest publishing a CoffeeScript artifact to JCenter or an internal binary repository and consuming it from there.

**Comment by bmuschko** [comment]
Closing this issue for the following reasons:

1. A working repository containing the CoffeeScript JS has been provided.
2. The feature isn't ready for public consumption yet and therefore can change at any time.

**Comment by bigdaz** [comment]
@bmuschko is correct. Our [integration tests](org.gradle.plugins.javascript.coffeescript.CoffeeScriptBasePluginIntegrationTest) resolve the coffee-script JS from https://repo.gradle.org/gradle/javascript-public.
