### ISSUE TITLE
List tasks by group

### ISSUE THREAD

**Issue by sannidhi01** [gradle/gradle#8323]
CONTEXT:
Tasks listing option.  Presently(at least v 5.1.1), there are two options to display tasks: default(gradle tasks) and all(gradle tasks --all). 

PROBLEM:
To view a custom tasks, if all option is used,

1. There's an unnecessary display of default tasks and other groups of tasks which the user might not be interested in.
2. If there are many custom tasks(could be under different groups), finding specific task is inconvenient as it may involve scrolling window.

PROPOSAL:
1. An option to list tasks by group, something like: gradle tasks <--groupName>. This should display tasks under the specified group.
2. Another option to list untitled/uncategorized group, something like: gradle tasks --other. This should display tasks under untitled/uncategorized group.

**Comment by big-guy** [comment]
This is already possible, it was [just added in 5.1](https://docs.gradle.org/current/release-notes.html#filter-tasks-with---group).

You do `gradle tasks --group somegroup` to see only those tasks. 

You can check this with `gradle help --task tasks` and you'll see something like:
```
> Task :help
Detailed task information for tasks

Path
     :tasks

Type
     TaskReportTask (org.gradle.api.tasks.diagnostics.TaskReportTask)

Options
     --all     Show additional tasks and detail.

     --group     Show tasks for a specific group.

Description
     Displays the tasks runnable from root project 'build-init-example'.

Group
     help
```
