### ISSUE TITLE
Groovy list.push pushes to front in Gradle 5.1.1

### ISSUE THREAD

**Issue by realdadfish** [gradle/gradle#8325]
### Expected Behavior
def args = ["a", "b", "c"]
args.push("d")
println(args) // prints [a, b, c, d] correctly in 4.10.2 

### Current Behavior
def args = ["a", "b", "c"]
args.push("d")
println(args) // prints [d, a, b, c] wrongly in 5.1.1

### Your Environment

./gradlew --version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Mac OS X 10.14.1 x86_64

**Comment by realdadfish** [comment]
Ok, seems to be rooted to the [Groovy update to 2.5.x](http://groovy.329449.n5.nabble.com/Groovy-2-5-1-array-issue-td5752734.html), however, I fail to see a note about potential breaking changes here in the [Gradle release notes](https://docs.gradle.org/5.0/release-notes.html)

**Comment by melix** [comment]
This is a side effect of upgrading to Groovy 2.5. Groovy 2.4.10 shows the old behavior, Groovy 2.5 doesn't. As for not being listed in the potential breaking changes, the Groovy upgrade is mentioned here:

https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#rel5.0:library_upgrades

**Comment by realdadfish** [comment]
@melix Yes, I see that the Groovy update was mentioned there, but _not_ that it is a potential breaking change. Given the fact that Groovy was a minor update from 2.4 to 2.5 I guess nobody would have expected a breaking change, but the Groovy people do not seem to adhere to semantic versioning.
Even when explicitly looking at the [Groovy Changelog](http://groovy-lang.org/releasenotes/groovy-2.5.html), it's kind of buried in the breaking changes section:

    same linkedlist code different behavior between groovy and java ([GROOVY-6396](https://issues.apache.org/jira/browse/GROOVY-6396))

which is non-saying :(
