### ISSUE TITLE
Wrong output files naming in 5.1

### ISSUE THREAD

**Issue by anri-vin** [gradle/gradle#8328]
I have Android library project with single module named **library**. After I updated gradle from 5.0 to 5.1 I noticed following behavior changes:

### Expected Behavior
./gradlew assemble**Release** should produce file library-**release**.aar and ./gradlew assemble**Debug** should 
produce file library-**debug**.aar. This is current behavior for all previous gradle versions including 5.0.

### Current Behavior
For any build type output file name is library.aar without any build-type classifier on gradle 5.1 and 5.1.1. If I add following code to build.gradle:
```
afterEvaluate {
    android.libraryVariants.all { libraryVariant ->
        libraryVariant.outputs.all { output ->
            println output.outputFile.name
        }
    }
}
```
It is still printing correct values on any version:
```
library-debug.aar
library-release.aar
```

### Context
I need to get separate android library files for debug build type and for release build type.

### Steps to Reproduce (for bugs)
Sample project is in attachment. You can change gradle version in gradle-wrapper.properties to 5.0 and see the difference.
[sample.tar.gz](https://github.com/gradle/gradle/files/2791846/sample.tar.gz)

### Your Environment
 * Build scan URL: 
https://scans.gradle.com/s/xw6k2paslzzta

**Comment by big-guy** [comment]
@autonomousapps does this ring any bells?

**Comment by lepicekmichal** [comment]
Same problem here

**Comment by autonomousapps** [comment]
@big-guy never heard of this, but it is reproducible for me. If I take the sample and run `./gradlew assemble`, it only produces a single file, `library/build/outputs/aar/library.aar`, but I expect it to produce both `library-debug.aar` and `library-release.aar`. After setting the Gradle version to Gradle 5.0, running `./gradlew assemble` produces both variants as expected. We should figure out what's going on here, because at present it looks like Gradle 5.1 is causing trouble for Android library authors.

@anri-vin FYI, I had to remove your `local.properties` file to run this sample, since they both pointed to directories on your system :)

**Comment by big-guy** [comment]
Ultimately, this is fallout from #8401, which broke the Android plugin. There's a fix in the Android Gradle plugin 3.4 and hopefully it'll be backported to a 3.3.x

**Comment by autonomousapps** [comment]
As a workaround for those who can't wait on AGP 3.4 or a hypothetical 3.3.2, try this:

```groovy
// in library/library.gradle
afterEvaluate {
    def debugFile = file("$buildDir/outputs/aar/library.aar")
    tasks.named("assembleDebug").configure {
        doLast {
            debugFile.renameTo("$buildDir/outputs/aar/library-debug.aar")
        }
    }
    tasks.named("assembleRelease").configure {
        doLast {
            debugFile.renameTo("$buildDir/outputs/aar/library-release.aar")
        }
    }
}
```
Evidence it works:
![screenshot from 2019-02-21 10-44-56](https://user-images.githubusercontent.com/5402301/53196386-d5518200-35cc-11e9-86f5-39b374aeb803.png)

**Comment by DanielNovak** [comment]
So was this fixed or not? I haven't found a PR/commit linked to this. We still see the issue in AGP 3.4.

**Comment by autonomousapps** [comment]
Daniel, which version of Gradle are you using?

**Comment by DanielNovak** [comment]
@autonomousapps 5.3.1, I can try 5.4.1 later today.

**Comment by igorbzin** [comment]
I am getting the same issue on 5.4.1 with gradle plugin 3.4.1 ..

**Comment by drostowsky-tmobile** [comment]
Also seeing the same issue on 5.4.1 with gradle plugin 3.4.1. We had to downgrade to Gradle 4.10.2 and 3.3.2 plugin to get it to work again.

**Comment by autonomousapps** [comment]
I will try to verify this against the latest combination of AGP/Gradle, but I wonder why [this workaround](https://github.com/gradle/gradle/issues/8328#issuecomment-466136196) isn't good enough? If you have a lot of flavors, I'm sure the script could be updated to use Android's variants to get reference to each in a loop.

**Comment by autonomousapps** [comment]
I just updated the reproducer (see https://github.com/gradle/gradle/issues/8328#issuecomment-459050485) to Gradle 5.4.1 and AGP 3.4.1 and ran `./gradlew assemble` and it has the correct behavior. That is: 
```
find . -type f -name *.aar
./library/build/outputs/aar/library-debug.aar
./library/build/outputs/aar/library-release.aar
```
If anyone finds this not to be the case, a reproducing sample will be very helpful.

**Comment by drostowsky-tmobile** [comment]
In the interest of sharing, here's the build.gradle code that stopped working for us when we updated to Gradle 5.1 (and up). Our main use case is trying to add the version name to the .aar filename. If there's an alternative to what we were doing, happy to learn that technique. Thx!

`
    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                outputFileName = "mylibrary-${variant.name}-${android.defaultConfig.versionName}.aar"
            }
        }
    }
`

**Comment by Gryzor** [comment]
@drostowsky-tmobile Did you find an alternative to that?

**Comment by drostowsky-tmobile** [comment]
> @drostowsky-tmobile Did you find an alternative to that?

Unfortunately, not in Gradle files. It's still an issue. Our build system around it had to do the renaming of the .aar. More specifically, our Jenkinsfile that uploads the .aar to Artifactory did the renaming of the .aar before it puts it into Artifactory for everyone to consume. My stance at the time was to work with whatever flawed names produced by Gradle and we'll rename it post build.

**Comment by will-quast** [comment]
For those who still have this issue, using Gradle 6.1.1 and AGP 4.0.1, another workaround is:
```
afterEvaluate {
    android.libraryVariants.all { variant ->
        variant.variantData.outputFactory.apkDataList.each { apkData ->
            if (apkData.outputFileName.endsWith('.aar')) {
                apkData.outputFileName = "${project.name}-${buildType.name}-anything-you-want.aar"
            }
        }
    }
}
```
