### ISSUE TITLE
Improved performance of tasks report

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#833]
Large multi-project builds with a lot of tasks suffer from poor performance when executing the tasks task. It's not unusual to see a task execution time of multiple minutes for enterprise projects which renders the report unusable. The goal of this story is to improve the performance of the tasks report by optimizing its internal workings and the information rendered for the user.

### Expected Behavior

Significantly reduced time to execute the `tasks` report.

### Current Behavior

Medium to large multi-project builds suffer from a slow execution time for the `tasks`. Sometimes executing a specific task takes less time than discovering tasks.

### Context

In larger projects the `tasks` report becomes unusable.

**Comment by bmuschko** [comment]
[This spec](https://github.com/gradle/gradle/blob/master/design-docs/task-reporting.md#story-improved-performance-of-tasks-report) describes the problem and implementation approach.

**Comment by bmuschko** [comment]
I submitted the change as [pull request](https://github.com/gradle/gradle/pull/854).

**Comment by bmuschko** [comment]
If the implementation is correct, then we could improve the performance quite a bit. For the Gradle core build, the numbers are as follows when running `gradle tasks`.

**Before**: 45-55 secs
**After**: 4-5 secs

Most of the performance gain came from not walking the task dependencies in `DefaultTaskContainer.realize()`: ~ 30 sec.

**Comment by eskatos** [comment]
I tried with a bunch of other builds, with a warm daemon and everything in cache:

**gradle/perf-native-large** - did not make a difference, fast in any case
- `3.2`: <2 secs
- `bm-performant-tasks`: <2 secs

**gradle/perf-enterprise-large** - now this is interesting!
- `3.2`:  ~9 minutes 🐌 🐌 🐌 
- `bm-performant-tasks`: ~6 secs 🏇 🏇 🏇 

**apache/zest-java** - wow, much faster!
- `3.2`: 30/40 secs 🐌 
- `bm-performant-tasks`: <2 secs 🐎 

`perf-native-large` must not suffer from what makes `tasks` slow

For these builds I did not see any missing tasks with the new impl.

**Comment by hansd** [comment]
Can't wait to have that released. Is it fair to say that gradle tasks performance is now roughly equivalent to the configuration time (for the current model)?

**Comment by bmuschko** [comment]
The change has been merged to `master` and will go out with 3.3. The tasks report performance is likely pretty close to the overall configuration time. We basically just have to build the task graph and then walk the tasks for rendering purposes.

**Comment by bmuschko** [comment]
The training material is going to be updated via issue #602.
