### ISSUE TITLE
Search is broken in Gradle Javadoc

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#8334]
* In a browser go to the Gradle Javadoc for the 5.1.1 release
* Enter "Project" in the search field
* Select the offered org.gradle.api.Project
* You end up following a broken link to:
https://docs.gradle.org/current/javadoc/undefined/org/gradle/api/Project.html
* You should have been taken to:
https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html

Notice that the broken link contains `undefined` in the path whereas the correct link does not.

Fails on Chrome 71 on both Mac (Mojave) and Linux (RHEL 7).

**Comment by eriwen** [comment]
This was fixed by https://github.com/gradle/gradle/commit/a8fe3ccf87074cfd47ae1c5ea48097c1d8fb8e7e for Gradle 5.2. 

Thanks for the clear reproducing steps.
