### ISSUE TITLE
Online docs: Build Lifecycle page build error

### ISSUE THREAD

**Issue by gebart** [gradle/gradle#8338]
The example output from `gradle test testBoth` on the documentation page https://docs.gradle.org/5.1.1/userguide/build_lifecycle.html#sec:settings_file shows an error message instead of the correct output.

### Expected Behavior

The 4.10 docs show this:
```
> gradle test testBoth
This is executed during the initialization phase.

> Configure project :
This is executed during the configuration phase.
This is also executed during the configuration phase.
This is executed during the configuration phase as well.

> Task :test
This is executed during the execution phase.

> Task :testBoth
This is executed first during the execution phase.
This is executed last during the execution phase.

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
```

### Current Behavior

5.1.1 docs current content:
```
> gradle test testBoth
Unresolved directive in build_lifecycle.adoc - include::../../samples/userguide/buildlifecycle/basic/buildlifecycle.out[]
```

### Steps to Reproduce (for bugs)
go to https://docs.gradle.org/5.1.1/userguide/build_lifecycle.html#sec:settings_file
look under "Output of `gradle test testBoth`"

### Your Environment

 * Build scan URL:

**Comment by big-guy** [comment]
Thanks, this is fixed in the 5.2 RC
