### ISSUE TITLE
Sync task should not skip at all when it has no input files

### ISSUE THREAD

**Issue by jochenberger** [gradle/gradle#834]
See https://discuss.gradle.org/t/sync-task-should-delete-target-files-if-it-has-no-inputs/14084/4
A `Sync` task that has no input files should not be skipped, because there might be files in the target directory than need to be deleted.
cc @wolfs

**Comment by wolfs** [comment]
This is only useful if we sync a directory where we put files from outside of the task itself. This could be another task in the same build (which would be a bad practice since we generally want to avoid overlapping output directories) or an external program running somewhere.

What would be the concrete use case for this feature?

**Comment by jochenberger** [comment]
I thought that it might be an issue if the task has run before and then the task implementation changes and the source files are deleted.
However, it is definitely an issue if the task *name* changes. (create file in `srcDir`, run Sync task, delete file in `srcDir` *and* rename sync task, run it again, the target file stays in place).

**Comment by entonio** [comment]
I have a task to sync some files changed by an external program. If the external program deletes them all from the source, I want the sync task to delete all in the target. It's what's expected by the semantics of the word 'sync' - cf how `rsync --delete` works.

**Comment by mitm001** [comment]
> This is only useful if we sync a directory where we put files from outside of the task itself.

Use case. 
The "from" directory is used as a cache of sorts where things get added to or removed from.
The "from" directory is outside any/all projects the sync task runs in. 
This "from" directory is used by many projects which expect to grab files from it "except" things they don't want. 
The projects rely on this "from" directory to populate "into" a directory inside the project so it can use these files.
Sometimes the cache gets emptied but when other projects call sync they will not update and have garbage still lying around.

Simple test. 
One file in one "from" external directory. 
One sync task in a project with a "into" directory. 
Call sync task to populate the "into" directory. 
Remove that one file in the "from" directory. 
Call sync task from project.

```
> Task :syncDependencies NO-SOURCE
```
So no updated project...
