### ISSUE TITLE
Provide a way to adapt a Configuration so that it can be used in tasks that use RegularFileProperty

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#8355]
Having a dependency that includes a single file is difficult to wire into a task that was a `RegularFileProperty`. For example, in a multi-project setup where an executable or single output file is produced by one project and needs to be consumed by another, it can be annoying and difficult to wire it into tasks that make use of `RegularFileProperty`.

### Expected Behavior

Ability to adapt a `Configuration` instance into a `RegularFile`  or as a type that can be provided to one of the setters to `RegularFileProperty` so task inference can be deduced.

### Current Behavior

Need to explicitly add a `dependsOn`/`input.files` to the configuration in the task, use `Configuration.getSingleFile()`, and/or perform some other workaround to make sure task inference can be deduced without having to explicitly add it to the task configuration.

### Context

In a multi-project build you may download or create an executable or a single consumable file that you want to use in another project. This works alright with JVM JARs since `JavaExec` makes use of `classpath` and `mainClassName`, but doesn't work as well when you want to invoke that executable or make use of that file directly.

A contrived example:

`settings.gradle.kts
```kotlin
rootProject.name = "kotlin-dsl-lab"
include("a")
include("b")
```

`a/build.gradle.kts`
```kotlin
plugins {
  base
}

val outputFile = file("$buildDir/file.txt")

val myTask by tasks.creating {
  outputs.file(outputFile)
  doFirst("write file") {
    outputFile.writeText("hello world")
  }
}

val myConfig by configurations.creating {
  outgoing.artifact(outputFile) {
    builtBy(myTask)
  }
}
```

`b/build.gradle.kts`
```kotlin
val consumerConfig by configurations.creating

dependencies {
  consumerConfig(project(path = ":a", configuration = "myConfig"))
}

open class RFPConsumer : DefaultTask() {
  @get:InputFile
  val inputFile: RegularFileProperty = project.objects.fileProperty()

  @TaskAction
  fun readFile() {
    println("Content: ${inputFile.asFile.get().readText()}")
  }
}

// fails
val singleFile by tasks.registering(RFPConsumer::class) {
  inputFile.set(consumerConfig.singleFile)
}

// succeeds
val inputWithFiles  by tasks.registering(RFPConsumer::class) {
  inputs.files(consumerConfig)
  inputFile.set(consumerConfig.singleFile)
}

// configuration failure
val inputWithFile by tasks.registering(RFPConsumer::class) {
  inputs.file(consumerConfig)
  inputFile.set(consumerConfig.singleFile)
}

// succeeds
val usingDependsOn by tasks.registering(RFPConsumer::class) {
  dependsOn(consumerConfig)
  inputFile.set(consumerConfig.singleFile)
}

// fails
val adaptWithProvider by tasks.registering(RFPConsumer::class) {
  inputFile.set(layout.file(provider { consumerConfig.singleFile }))
}
```

### Steps to Reproduce (for bugs)

N/A

### Your Environment

* Gradle 5.1.1

**Comment by adammurdoch** [comment]
You should be able to use `Configuration.elements` and `Project.layout` to do this now, albeit not in a very convenient way.
