### ISSUE TITLE
Official documentation on testing a plugin with functional tests is incorrect

### ISSUE THREAD

**Issue by eyalroth** [gradle/gradle#8358]
The official documentation on [testing gradle plugin with functional tests](https://guides.gradle.org/testing-gradle-plugins/#functional-tests) states that the following configuration should be added to the build file:
```groovy
gradlePlugin {
    testSourceSets sourceSets.functionalTest
}
```

However, this will suddenly cause the test-kit (`org.gradle.testkit`) to be unavailable in the `test` source-set. To fix this I've used:

```groovy
gradlePlugin {
    testSourceSets sourceSets.test, sourceSets.functionalTest
}
```

I'm not sure if this is intended or not; this behavior should either be fixed or better documented.

**Comment by big-guy** [comment]
This is intentional, but I agree it's unclear.

The assumption was that if you have a separate set of functionalTests that use TestKit, then the test source set is only unit tests and does not need TestKit. 

I reworded that section to make that clearer (should be live soon-ish).
