### ISSUE TITLE
POM file is parsed multiple times when imported into different modules

### ISSUE THREAD

**Issue by moley** [gradle/gradle#8360]
I have a project which contains a huge dependency tree, importing boms with spring-dependency plugin. 

`dependencies {
    classpath "org.springframework.boot:spring-boot-gradle-plugin:2.1.0.M3"
    classpath "io.spring.gradle:dependency-management-plugin:1.0.7.BUILD-SNAPSHOT"
  }

  dependencyManagement {
    imports {
      mavenBom 'mypackage:integration-bom:1.8.4.1-SNAPSHOT-1901142023'
    }
  }
`
The SNAPSHOT is not a real maven snapshot, but is only a special version tag. 
On the last stage resolving dependencies needs **at least 5GB memory and 50 minutes**. JProfiler told me, that e.g. PomReader#replaceProps is called 2.623.108 times. So I debugged dependency resolution and set a breakpoint in PomReader constructor. I suspect the PomReader doesn't contain any kind of caching, because the debugger gets to this breakpoint multiple times with the same resource (e.g. jboss-eap-parent-7.0.3.GA-redhat-2.pom). Can you please give me a hint how to solve this problem and fix this including a cache? 

My stack was: 
<init>:135, PomReader (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:229, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:117, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:231, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseImportedDependencyMgts:194, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
overrideDependencyMgtsWithImported:173, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:146, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:231, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseImportedDependencyMgts:194, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
overrideDependencyMgtsWithImported:173, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:146, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:231, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseImportedDependencyMgts:194, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
overrideDependencyMgtsWithImported:173, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:146, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:231, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseImportedDependencyMgts:194, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
overrideDependencyMgtsWithImported:173, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:146, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:231, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseImportedDependencyMgts:194, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
overrideDependencyMgtsWithImported:173, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:146, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:231, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseImportedDependencyMgts:194, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
overrideDependencyMgtsWithImported:173, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:146, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomResource:231, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parsePomForSelector:221, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseImportedDependencyMgts:194, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
overrideDependencyMgtsWithImported:173, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParsePom:146, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParseDescriptor:94, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
doParseDescriptor:59, GradlePomModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseDescriptor:48, AbstractModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseMetaData:43, AbstractModuleDescriptorParser (org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser)
parseMetaDataFromResource:53, DefaultMavenPomMetadataSource (org.gradle.api.internal.artifacts.repositories.metadata)
parseMetaDataFromResource:38, DefaultMavenPomMetadataSource (org.gradle.api.internal.artifacts.repositories.metadata)
parseMetaDataFromArtifact:72, AbstractRepositoryMetadataSource (org.gradle.api.internal.artifacts.repositories.metadata)
create:59, AbstractRepositoryMetadataSource (org.gradle.api.internal.artifacts.repositories.metadata)
resolveStaticDependency:244, ExternalResourceResolver (org.gradle.api.internal.artifacts.repositories.resolver)
doResolveComponentMetaData:125, MavenResolver (org.gradle.api.internal.artifacts.repositories.resolver)
resolveComponentMetaData:445, ExternalResourceResolver$RemoteRepositoryAccess (org.gradle.api.internal.artifacts.repositories.resolver)
resolveComponentMetaData:378, CachingModuleComponentRepository$ResolveAndCacheRepositoryAccess (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
resolveComponentMetaData:138, ErrorHandlingModuleComponentRepository$ErrorHandlingModuleComponentRepositoryAccess (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
process:67, ComponentMetaDataResolveState (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
resolve:59, ComponentMetaDataResolveState (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
findBestMatch:138, RepositoryChainComponentMetaDataResolver (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
findBestMatch:119, RepositoryChainComponentMetaDataResolver (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
resolveModule:92, RepositoryChainComponentMetaDataResolver (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
resolve:63, RepositoryChainComponentMetaDataResolver (org.gradle.api.internal.artifacts.ivyservice.ivyresolve)
resolve:94, ComponentResolversChain$ComponentMetaDataResolverChain (org.gradle.api.internal.artifacts.ivyservice.resolveengine)
resolve:62, ClientModuleResolver (org.gradle.api.internal.artifacts.ivyservice.clientmodule)
resolve:188, ComponentState (org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder)
getMetadata:141, ComponentState (org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder)
calculateTargetConfigurations:156, EdgeState (org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder)
attachToTargetConfigurations:112, EdgeState (org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder)
attachToTargetRevisionsSerially:306, DependencyGraphBuilder (org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder)
resolveEdges:193, DependencyGraphBuilder (org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder)
traverseGraph:146, DependencyGraphBuilder (org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder)
resolve:117, DependencyGraphBuilder .......

**Comment by melix** [comment]
First thing to try is to replace the Spring dependency management with Gradle's native BOM import. Please take a look at https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import

and report back if you still have a memory issue.

**Comment by bigdaz** [comment]
@moley Can you share a build scan? If not, can you confirm if the dependencies resolved are coming from a local file repository? Things like `mavenLocal()`, `maven { url "file..." }` are local file repositories.

For remote repositories, Gradle parses the downloaded POM and caches it in an optimized format. For local repositories, Gradle does not cache the metadata, resulting in repeated re-parsing of POM files.

See #4322 for more details.

**Comment by moley** [comment]
@bigdaz No, we have eliminated all kind of local repos due to we got in some performance drawbacks with this. The stacktrace, which I pasted into the issue was taken with a resource from a http url. Maybe this is an behaviour that is only available when working with spring-dependencies-plugin. We are not using gradle enterprise, so I think that providing build scans is not possible - isn't it? 

@melix The problem is, that we currently are using gradle 4.x, where bom import is not yet implemented. Switching to gradle 5 is planned in the future, but currently we are not able to do.

**Comment by melix** [comment]
That's unfortunate, any chance you can give it a try on a limited version of your build? This plugin is known to be particularly expensive in large projects.

**Comment by melix** [comment]
Can you give more details? Is it faster (less than 50 minutes)? Does it use less than 5GB? Can you send us a CPU and memory snapshot?

Thanks

**Comment by moley** [comment]
@melix 
I don't know exactly why - but I could not reproduce this 55 minutes and 5 GB anymore. But I have no started my example multiple times with both spring/gradle4 and plain gradle5, here are the results: 

gradle4/spring-dependencies plugin needs 8m in the middle and runs without memory logout with 1,5G
gradle5 plain needs 11m in the middle and runs only with more memory (Tried with 2,5G).

As I already mentioned.... The PomReader is used multiple times with the same resources, so I think a cache would solve this issue. PomDomParser#getFirstChildEvent is implemented well I think, it's the amount of 100 mio invocations, that kills the performance. So I'd like to beta test any kind of solution in this case. 

Some snapshots: 

<img width="1466" alt="bildschirmfoto 2019-01-31 um 12 48 13" src="https://user-images.githubusercontent.com/3918367/52053175-f63c2f80-2558-11e9-9e6d-a8d3f92c1516.png">
<img width="1478" alt="bildschirmfoto 2019-01-31 um 12 50 14" src="https://user-images.githubusercontent.com/3918367/52053177-f63c2f80-2558-11e9-90dc-0cf375280fc3.png">
<img width="1466" alt="bildschirmfoto 2019-01-31 um 12 52 29" src="https://user-images.githubusercontent.com/3918367/52053178-f63c2f80-2558-11e9-8195-0fe82f1db55f.png">
<img width="1481" alt="bildschirmfoto 2019-01-31 um 13 03 44" src="https://user-images.githubusercontent.com/3918367/52053179-f63c2f80-2558-11e9-99d2-46ca41c09137.png">
![bildschirmfoto](https://user-images.githubusercontent.com/3918367/52053180-f63c2f80-2558-11e9-8891-50356f4a71d9.png)

**Comment by melix** [comment]
My best bet is that you are using a file repository, like `mavenLocal()`, which is bad for performance (see #4322)

**Comment by moley** [comment]
No I println all the repos, and I don't have any mavenLocal() in place. I only have remote repos in my configuration and also I can observe when debugging that PomReader is called with remote url's (multiple times with exactly the same one).

**Comment by bigdaz** [comment]
@moley This is very odd. For one, Gradle should never be parsing POMs directly from remote URLs: these files are always downloaded and parsed locally. The confirm, you'll need to inspect the `LocallyAvailableExternalResource` [here](https://github.com/gradle/gradle/blob/b44dd3c9fde3ac69206bb604c13e4212eeaa9faf/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorParser.java#L91) and see what `getFile()` returns.

Gradle definitely does cache the output of parsing these downloaded POM files, in a binary format in the module metadata cache (`~/.gradle/caches/modules-2/metadata-2.XX`). In addition, we keep the entire module metadata in memory for the life of the build invocation, so we should _never_ load the same module twice in a single build invocation. We need to get to the bottom of why this isn't working for you.

A few things you could to do diagnose this:
- If possible, try with an older Gradle version (like 4.0) to see if the same behaviour is present.
- Simplify your project to the bare minimum needed to exhibit this behaviour, by systematically removing additional dependencies/plugins/etc.
- In your stack trace, it's pretty clear there is a recursive call to [`parsePomForResource`](https://github.com/gradle/gradle/blob/b44dd3c9fde3ac69206bb604c13e4212eeaa9faf/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/parser/GradlePomModuleDescriptorParser.java#L224). It would be interesting to know what resources are in that recursive call.

Thanks for taking the time to report. We definitely would like to get to the bottom of this.

**Comment by moley** [comment]
@bigdaz 
I have created a small testproject, were you can reproduce: https://github.com/moley/exampleGradleDepsPerformance
Details you can see in https://github.com/moley/exampleGradleDepsPerformance/blob/master/README.md. 
If you have problems with it or any further questions, feel free to ask.

**Comment by bigdaz** [comment]
Thanks for the taking the time to create a reproducer @moley 

However, I don't think there's anything fundamental going on here. You are resolving quite a large dependency graph, and adding in the `spring-dependency-management` plugin adds significant overhead to the resolution. But it doesn't appear pathological.

Here's what I see (starting with `gradleHome` as an empty directory):
- Run with a clean gradle home (no cache, no daemon): 46s https://scans.gradle.com/s/o64wfma5ifvuu/ 
- Run again (modules in cache, no daemon): 5s https://scans.gradle.com/s/sb7oy5rw2q46a
- Run with warm daemon (modules in cache, daemon): 1.6s https://scans.gradle.com/s/2a6un2ff5ubz6

Under "Performance > Network Activity" you'll see far fewer network requests when modules are in the gradle cache. 

To be sure, I added some logging whenever we parsed a POM file, and yes, you can see lots of duplicates here: https://scans.gradle.com/s/3nhtneakiwepe/console-log
But none of this parsing happened on a subsequent build: https://scans.gradle.com/s/mlcaiked5x3pu/console-log

To be sure, a lot of this duplicate parsing is related to imported and parent POMs: https://scans.gradle.com/s/fbg7mxb5pouzs/console-log

This makes sense, since we only cache the result of parsing a top-level POM into a Gradle module. We don't do any caching of the _parsed result_ of POM files  are inputs to this process (parent or import).

In the end, the title of this issue is probably correct, but only on the first resolve of a module. I would suspect that HTTP downloads are going to dominate in this case, and that additional caching would not have a significant impact.

**Comment by moley** [comment]
@bigdaz 
Yes, I can confirm your results. As soon as the cache is built up, it is much faster. Sorry for the misleading header.... 
But in my opinion it is still an issue (not a blocking one, but still....), because for any project, which is big enough, this leads to huge memory and time consumption. I could even reproduce without spring-dependencies plugin and the built in gradle bom mechanism of gradle 5. 
In our scenario this issue hits the integration project, which is used to bundle installation artifacts for different scenarios, so we cannot provide a fast installation process at all, because from version to version - we always have a kind of clean state, because most dependencies change meanwhile. 
I don't think HTTP traffic dominates in this case taking a look at the profiler result, but perhaps you can easily add a measurement to your "Parsing ....BOM" console output to have a feeling how many time is needed in sum for all parsing?

**Comment by moley** [comment]
@bigdaz 
Hi Daz, 
do you have an idea when this issue can be fixed? This is currently a show stopper for us. Would be nice to get additional infos.... 
Thanks in advance

**Comment by bigdaz** [comment]
@moley This issue is not prioritized at present. I'm now working on a different project, so I'll leave it to @gradle/dependency-management to respond.

To summarize:
- We never cache the result of parsed POM files directly: we cache the single module metadata that results from parsing a number of POM files (module POM, parent POMs, imported POMs)
- A lot of parent/imported POM files are shared among different modules: we parse these multiple times. In some cases the same POM file is parsed multiple times just to resolve a single module.
- With BOM support, the graph of POM files that are input to a module metadata is increased, making this more problematic.
- This issue impacts _every resolve_ for a file-backed repository, and the _initial resolve_ for a cached HTTP repository.

IMHO we should first address the issue with file repositories not having any caching, and the look for a solution where POM parsing is reduced when the module metadata is not cached.

**Comment by moley** [comment]
@gradle/dependency-management Hi, any changes to this issue? We are currently working with a gradle version, which is patched on our own, which improves this situation from "I cannot work with it" to , "it is still very slow" - which is by far not the solution. So we would highly appreciate if this error is getting fixed officially... 
Can you give us a hint, if anything was happening so far or when you plan to improve the performance at this point? I always thought that performance is one of the main advantage of gradle - would be nice to get an answer...
Cheers
Markus

**Comment by melix** [comment]
There is no plan to improve this short term. This issue is explained by a combination of 2 factors:

- having a deep "parent" POM file hierarchy or having a lot of dependencies with parent POMs (note, Gradle _never_ produces files with parent POMs)
- using a clean state, which busts all the caches, in particular the binary caches which are a huge performance gain in Gradle
- _or_ having a lot of changing dependencies, in which case we need to re-parse everything
- _or_ using _file repositories_ in which case the binary caches are _not used_

This makes it very unlikely, you're basically the only one reporting this issue, so we can't do anything compared to other highly voted issues. We have plans to add a binary cache for file repositories too (which would be a first step), but it wouldn't solve your problem. Adding a cache for _parent parsing_ is significantly more work, and we can accept PRs if you want to make progress on this.

Thanks for your patience,
