### ISSUE TITLE
Missing setArchiveBaseName-Method in class AbstractArchiveTask

### ISSUE THREAD

**Issue by sielenk-yara** [gradle/gradle#8371]
### Expected Behavior

Setting the Zip-Archive base name can be done with the same property as getting it.

### Current Behavior

Assigning to `baseName` in a Zip task is shown as deprecated. The documentation on the `org.gradle.api.tasks.bundling.AbstractArchiveTask.setBaseName`-method refers to `getArchiveBaseName` (which is a documentation bug). The expected `setArchiveBaseName` does not exist.
Groovy accepts assigning to `archiveBaseName`, though.

### Context / Steps to Reproduce

The Task
```
task sdkZip(type: Zip) {
    baseName = "Suffix-${globals.versionText}-Postfix"

    from(buildInstaller)
}
```
produces the expected result but causes a deprecation warning while
```
task sdkZip(type: Zip) {
    archiveBaseName = "Suffix-${globals.versionText}-Postfix"

    from(buildInstaller)
}
```
does not result in the expected archive file but shows no warnings.

No, this is not a compete example but the fix - I hope - is obvious to anyone around in that area of the code so I did not clone and create a pull request. I hope you are OK with that.

### Your Environment

Gradle 5.1.1 used from IntelliJ-IDEA 2018.3.4 (Ultimate Edition) with
```
wrapper {
    distributionType = Wrapper.DistributionType.ALL
    gradleVersion = "5.1.1"
}
```
in the top level `build.gradle` file and the IDE instructed to actually use that.

**Comment by ljacomet** [comment]
The reason behind this is that `archiveBaseName` is now of type `Property<String>` which carries its own method to set its value.
The groovy DSL also provides a convenience method that allows `archiveBaseName = 'foo'` to be valid while in the Kotlin DSL you have to do `archiveBaseName.set('foo')`.
So in that sense the documentation is right as you now have to go through that richer type and you cannot change the instance of `Property<String>` that is tied to `archiveBaseName`.

**Comment by sielenk-yara** [comment]
You are absolutely right, I just saw that moments ago. Sorry, my bad and thanks for the quick reply!
But setting it still did not work as expected here. So I will have to investigate further.

**Comment by kristianperkins** [comment]
Googling this error brought me here. It would be nice if the gradle error message stated that adding an equals sign fixes this, or if the baseName deprecation warning was more precise as just replacing baseName with archiveBaseName in the script does not work.
