### ISSUE TITLE
How to exclude resolved plugin in Gradle 5.x with a custom one?

### ISSUE THREAD

**Issue by ashiishsharma** [gradle/gradle#8373]
For Gradle 5.x,

Can a plugin that is resolved in a transitive dependency of a plugin be excluded (same way 'exclude' works in gradle for dependennt code libraries) and a custom plugin be supplied in place of that ?

I am able to supply my own custom plugin via following code :

        buildscript {
        dependencies {
            classpath files('/home/developer/Workspace/custom-gradle-plugin-0.3.6.jar')
        }
       }
    
    apply plugin: com.custom.gradle.plugins.CustomSupportPlugin

But this is not able to override the plugin that is being resolved via transitive plugin resolution.

**Comment by big-guy** [comment]
There are a couple of different things you could do.

If you're developing a new version of the plugin, you could use composite builds:
https://github.com/gradle/gradle/tree/master/subprojects/docs/src/samples/compositeBuilds/plugin-dev

If you're just replacing it, you can use plugin resolution strategy to substitute a plugin for another:
https://discuss.gradle.org/t/resolution-strategy-for-classpath-configuration/24519 (this is an example for specifying a version, but I think you can do the same with a different group/name/version).

Please ask these sorts of questions on the forums or our community Slack.  Thanks!
