### ISSUE TITLE
testAnnotationProcessor does not work with play plugin

### ISSUE THREAD

**Issue by jasongilanfarr** [gradle/gradle#8378]
annotationProcessor(...lombok...) works for play projects for compilePlayBinaryScala; however, testAnnotationProcessor(...lombok...) does not seem to enable annotation processing in compilePlayBinaryTests. 

As far as I can tell, there is no play/playTestAnnotationProcessor

**Comment by big-guy** [comment]
There's not a separation between the annotationProcessor classpath and the regular classpath in the Play plugin.

As a workaround, could you try:
```
model {
    tasks.compilePlayBinaryTests { 
      annotationProcessorPath = classpath
    }
}
```
and use the `playTest` configuration to add the annotation processor.

**Comment by ymwang1984** [comment]
Verified that the workaround works.
