### ISSUE TITLE
Composite builds, Sharing multiple ouput directories for the dependent module, instead of just $buildDir/classes/java/main

### ISSUE THREAD

**Issue by scicompth** [gradle/gradle#8385]
Consider the following setup :

```
configurations {
    codeGen
}

sourceSets {
    codeGen {
        java {
            srcDirs = [ "codeGen"]
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs = ["src"]
        }
    }
}
```

As we understand, with above setup, compileJava and compileCodeGenJava will have its own output directories as below.

```
compileJava        ----> $buildDir/classes/java/main
compileCodeGenJava ----> $buildDir/classes/java/codeGen
```

Also, It is **not** possible for us to club the two compilation steps into one. With that assumption, Is it possible to share both output directories (main and codeGen) for the modules dependent on this module ? By default, only $buildDir/classes/java/main will be used for the dependency substitution.

### Expected Behavior
There should be a way to share multiple output directories for the dependent modules.

### Current Behavior
Not able to do so or rather don't know how to do it.

### Context
Composite builds

### Your Environment
Gradle: Version 5.0
Windows 7 SP1 , 64-bit

**Comment by scicompth** [comment]
Team, please help us here. We are really struggling with this issue. I have much simplified our use case here, but if we can get the possible options for above mentioned scenario, we will be more than happy. We tried giving the same destinationDir for both the JavaCompile tasks but it leads us to unexpected problems during rebuild (as in build on already built code with some minor code changes). Also, but doing so, we are not able to leverage from the build cache and incremental build like features.

**Comment by tadfisher** [comment]
Composite builds are currently limited to the `default` configuration artifact only. The Java plugin sets a default to what you expect, which is the archive produced by the `jar` task. You can override this default with an `artifacts` configuration like:

```groovy
def combinedJar = tasks.register("combinedJar", Jar) {
    from sourceSets.main.output
    from sourceSets.codegen.output
}

artifacts {
    archives combinedJar
}
```

Or something to that effect. Anything added to `archives` will override the default artifact, I believe.
