### ISSUE TITLE
Silent change in behavior for tasks that extend `AbstractArchiveTask` 

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#8401]
Tasks that extend `AbstractArchiveTask` in 5.1 or later may no longer work as expected.

### Expected Behavior

Behavior should be maintained or should fail loudly.

### Current Behavior

Depending on how the task is implemented, we may now silently ignore what the custom task does.

### Context

Before 5.1, none of the built-in `AbstractArchiveTask`-based tasks (`Zip`, `Tar`, `Jar`, `Ear`, `War`) used the Provider API for their major properties (file name, classifier, extension, etc).

In 5.1, we added Provider API based equivalents and deprecated the old methods/properties. The old methods are implemented on top of the new Provider API methods and internally we use the new methods.

In Android and other plugins, we've seen a couple of problems fall out of that:
- https://github.com/gradle/gradle/issues/8328 - This was fixed upstream in Android
- https://gradle-community.slack.com/archives/CA7UM03V3/p1549056159397100 - refers to the nebula-ospackage plugins.

The issue is caused by two different patterns:
- The Android `AarBundle` task overrides `AbstractArchiveTask.getArchiveName` so that the archive name can be calculated dynamically/on-demand.  Since the `AbstractArchiveTask` no longer looks at `archiveName` when determining the output file name changes to `AarBundle.archiveName` are ignored. 
- The nebula-ospackage plugin uses [Convention mapping to override `AbstractArchiveTask.getArchiveName`](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy#L107-L109), among other things. In a similar way to `AarBundle`, the convention mapping is ignored.

The "fix" so far has been for the affected plugins to change their code to use the Provider API where possible.  Since this impact wasn't considered when we added the Provider APIs, we could...
1) Roll everything back
2) Use the old methods internally to keep convention mapping/overrides in the loop.
3) Detect this situation and fail 

I think 2 is possible, but we may be giving up some simplicity.

**Comment by JamesXNelson** [comment]
I believe the shadow plugin was also affected by the convention mapping.

**Comment by pun-ky** [comment]
My plugin has also few tasks extending `Zip` task and I also observed it.

https://github.com/Cognifide/gradle-aem-plugin/blob/master/src/main/kotlin/com/cognifide/gradle/aem/pkg/tasks/Compose.kt#L163

I am setting corrected `baseName` within task construction phase (task is being registered / not created) but Gradle's Base Plugin is overriding it on line https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePlugin.java#L113

As an effect, my corrected base name default is gone after upgrading Gradle, because configureEach from Base Plugin is of course called later. Now I am confused, how can I set my corrected base name default value which will be still overriddable via build script.

Any thoughts on that?

**Comment by pun-ky** [comment]
Any ETA?

**Comment by big-guy** [comment]
@pun-ky that may have been added around the same time as `convention` and it was overlooked. I think that should be `convention` and not `set`.  Would you be interested in submitting a PR?

**Comment by pun-ky** [comment]
Yep, I will try to create my first PR here, but I am wondering if still 3rd party plugins like mine will need to be updated after changing `set` to `convention` in mentioned place. If there will be `convention` custom plugins will be able to override that default convention as I am understanding this new API. But still the change introduced forces plugin devs to align, right? So that more than this 2 lines need to be changed in my potential PR, because we are considering eliminating this silent regression at all? In other words, if there is more work to do, I am not sure if I will find a fix in my limited time.

**Comment by JamesXNelson** [comment]
Looks like it's just changing `set` to `convention`.

I wonder if it shouldn't actually be done in AbstractArchiveTask itself, to set the convention as soon as possible, in case plugin wants to override convention...

**Comment by Lanchon** [comment]
my plugin is also affected. i had to use this ugly workaround for lack of laziness, and you adding laziness this way broke my code. i actually haven't tested my plugin in 5.1+, but i was investigating the longevity of my current hack and found this issue.

take a look:

```
/*
 * DexPatcher - Copyright 2015-2019 Lanchon
 * (GNU General Public License version 3 or later)
 *
 * DexPatcher is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 */

package lanchon.dexpatcher.gradle.tasks

import groovy.transform.CompileStatic

import lanchon.dexpatcher.gradle.Utils

import org.gradle.api.file.RegularFile
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.bundling.Zip

// FIXME: This apparently does not work on Gradle 5.1 or later.
// (See: https://github.com/gradle/gradle/issues/8401)

@CompileStatic
class LazyZipTask extends Zip {

    @OutputFile final RegularFileProperty archiveFile

    LazyZipTask() {
        archiveFile = project.layout.fileProperty()
        archiveFile.set project.<RegularFile>provider {
            Utils.getRegularFile(project, super.getArchivePath())
        }
    }

    @Internal
    public File getArchivePath() {
        return archiveFile.get().asFile;
    }

}
```

there is:
- a name clash over `archiveFile`.
- `getArchivePath()` being ignored (i guess, haven't tried).

i want to support both Gradle 4 and 5:
- one way is to add properties and a doFirst action that reads them and sets the old style fields. this is hacky and probably incorrect.
- a cleaner way is to keep the current code (add properties, override getArchivePath) but also reflect the existence of the new style properties. and if they are there, set them to mirror the value of the added properties. this is correct but needs reflection.

any other way to support laziness on Gradle 4 and 5?

**Comment by JLLeitschuh** [comment]
@Lanchon The `Zip` task now supports lazy configuration in 5.1+ so your "hack" as you call it shouldn't be necessary anymore.

**Comment by Lanchon** [comment]
@JLLeitschuh, thanks but that's irrelevant. as i stated:

> i want to support both Gradle 4 and 5

**Comment by Lanchon** [comment]
Here is a workaround to support archive laziness in Gradle 4 and 5.1+. It is supposed to compile under both Gradle 4 and 5.1+. **Note that this code has not yet been tested under Gradle 5.1, but is expected to work.**

```
/*
 * DexPatcher - Copyright 2015-2019 Lanchon
 * (GNU General Public License version 3 or later)
 *
 * DexPatcher is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 */

package lanchon.dexpatcher.gradle.tasks

import groovy.transform.CompileDynamic
import groovy.transform.CompileStatic

import lanchon.dexpatcher.gradle.Utils

import org.gradle.api.file.Directory
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.bundling.Zip
import org.gradle.util.GradleVersion

@CompileStatic
class LazyZipTask extends Zip {

    // Conditionally enable workaround for Gradle 5.1 bug (https://github.com/gradle/gradle/issues/8401).
    private static final boolean GRADLE_5_1 = (GradleVersion.current() >= GradleVersion.version('5.1'))

    // Enable workaround for Gradle < 5.1 unexpected behavior seemingly related to convention implementation.
    private static final boolean DESTINATION_DIR_WORKAROUND = true

    // Client must configure the output archive only using these properties:
    @Internal final Property<String> lazyArchiveFileName
    @Internal final DirectoryProperty lazyDestinationDirectory

    LazyZipTask() {
        if (GRADLE_5_1) {
            // On Gradle >= 5.1 simply alias existing properties.
            lazyArchiveFileName = gradle_5_1_getArchiveFileName()
            lazyDestinationDirectory = gradle_5_1_getDestinationDirectory()
        } else {
            // On Gradle < 5.1 create new properties and override existing getters.
            lazyArchiveFileName = project.objects.property(String)
            lazyArchiveFileName.set project.<String> provider {
                super.getArchiveName()
            }
            lazyDestinationDirectory = project.layout.directoryProperty()
            if (!DESTINATION_DIR_WORKAROUND) {
                lazyDestinationDirectory.set project.<Directory> provider {
                    Utils.getDirectory(project, super.getDestinationDir())
                }
            }
        }
    }

    @CompileDynamic
    private Property<String> gradle_5_1_getArchiveFileName() {
        return this.getArchiveFileName()
    }

    @CompileDynamic
    private DirectoryProperty gradle_5_1_getDestinationDirectory() {
        return this.getDestinationDirectory()
    }

    @Override @Internal public String getArchiveName() {
        if (GRADLE_5_1) {
            return super.getArchiveName()
        } else {
            return lazyArchiveFileName.get()
        }
    }

    @Override @Internal public File getDestinationDir() {
        if (GRADLE_5_1) {
            return super.getDestinationDir()
        } else {
            if (!DESTINATION_DIR_WORKAROUND) {
                return lazyDestinationDirectory.get().asFile
            } else {
                super.destinationDir = lazyDestinationDirectory.get().asFile
                return super.getDestinationDir()
            }
        }
    }

}
```

**Comment by Lanchon** [comment]
UPDATE: although my plugins developed against 4.10.1 do not trigger deprecation warnings there, they have multiple issues with Gradle 5.1, including some that superficially look like this bug but involving other non-archive tasks. Gradle 5.1 is not my top priority so i'll postpone testing of the above code.

**Comment by pun-ky** [comment]
affects also 5.4, 

I tried with setting 

```kotlin
open class MyTask : Zip() {
    init {
        archiveBaseName.convention(project.provider { "${project.rootProject.name}-${Formats.dateFileName()}" })
    }

    // ...
}
```

but I need to use `set` here instead of `convention`, because my convention is still being overridden by https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePlugin.java#L113

as I understand this, I need to assign convention separately as it is Gradle Base plugin doing, not in `MyTask` `init` block / construction phase (most probably it will work)

```kotlin
   project.tasks.register("myTask", MyTask::class.java)
   project.tasks.withType(MyTask.class).configureEach {
                 archiveBaseName.convention(project.provider { "${project.rootProject.name}-${Formats.dateFileName()}" })
   }
```

this looks confusing for me, because I cannot have all task specific stuff defined inside task class / need to think about conventions / lazy API which can affect my task code from outside.

**Comment by Lanchon** [comment]
## workaround:

this [LazyZipTask](https://github.com/DexPatcher/dexpatcher-gradle/blob/c2b69789dfb365ba5d27a207d6df9739f562d37a/src/main/groovy/lanchon/dexpatcher/gradle/tasks/LazyZipTask.groovy) is tested to work on Gradle versions earlier than and later than 5.1.
