### ISSUE TITLE
--args not working in some cases

### ISSUE THREAD

**Issue by Dkhusainov** [gradle/gradle#8405]
I have an project with an application plugin and I'm trying to run it with command line arguments:

`gradlew run --args "-P:key1=value1 -P:key2=value2"`

### Expected Behavior

It just works.

### Current Behavior

I get this error: `No argument was provided for command-line option '--args'.`

### Context

If I remove the -P: prefix it works as expected. But nowhere in the application plugin documentation does it says that this option behaves differently if the prefix is present at the start of args.

### Steps to Reproduce (for bugs)

See above.

### Your Environment

 * Build scan URL:

**Comment by Dkhusainov** [comment]
It does work if I add a dummy value as the first argument

**Comment by a01fe** [comment]
It appears that the error happens whenever the first character is a `-`.
Adding whitespace is enough to get it to work, e.g., `./gradlew run --args "-d foo"` fails but `./gradlew run --args " -d foo"` works.
