### ISSUE TITLE
Warn against subclasses that may interfere with replaced properties

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#8414]
When a property has been replaced with a Provider API-based one, subclasses that extend the old API may break in strange ways.

Given:
```
class Base {
    String oldProperty
    String getOldProperty() { return oldProperty }
    void setOldProperty(String oldProperty) { this.oldProperty = oldProperty }
    // somewhere
    conventionMapping.map("oldProperty") {
        "convention"
    }
}
```
If this is replaced by:
```
class Base {
    String getOldProperty() { return newProperty.get() }
    void setOldProperty(String oldProperty) { this.newProperty.set(oldProperty) }

    Property<String> newProperty = project.objects.property(String)
    String getNewProperty() { return newProperty }

    // somewhere else
    getNewProperty().convention("convention")
}
```

Subclasses of `Base` could extend `getOldProperty` or `setOldProperty` and break the migration.

**Comment by jjohannes** [comment]
Since we did not do anything on this since more than 2 years the problem doesn't seem too severe. We can get back to it when we do port more things to the provider API though. But we need to reconsider what is useful and necessary.
