### ISSUE TITLE
Automatically wire convention mapping to replacement properties when known

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#8415]
Similar to how subclasses may break migration: https://github.com/gradle/gradle/issues/8414

Plugins that rely on the internal convention mapping APIs may subtly break when migrating to a Provider API-based property.

Since we control the wiring for convention mapping and #8412 would give us more clues about the relationship between properties, we could automatically wire convention mapping to the new property vs using the old property.

**Comment by jbartok** [comment]
@big-guy are you ok with us closing this?
