### ISSUE TITLE
o.j.r.nRunListener.testRunFinished event not triggered when executing in JUnit tests

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#842]
Migrated from JIRA: https://issues.gradle.org/browse/GRADLE-3411

Arquillian relies on JUnit listeners to launch some internal events. One of the last events that are thrown inside Arquillian is AfterSuite event. This Arquillian event might be responsible to clean up some elements that could be created during the test phase (for example a Docker container). This event is called when testRunFinished method from JUnit RunListener is called (https://github.com/junit-team/junit/blob/3e43555e1f4df95b0a239f453af6d3226a8fef6e/src/main/java/org/junit/runner/notification/SynchronizedRunListener.java#L42)

### Expected Behavior
AfterSuite event should be sent

### Current Behavior
AfterSuite event is not sent

### Context

`fireTestRunFinished` is documented as "do not call this, as it might be moved in the future". IntellijJ, Eclipse and Maven are all calling it. Maybe @sbrannen can shed some light on this?

**Comment by sbrannen** [comment]
Maybe @marcphilipp can shed some light on this? 😉

**Comment by marcphilipp** [comment]
What version of JUnit is this happening with? Is it a regression? How are you calling JUnit? Through JUnitCore?

**Comment by oehme** [comment]
@marcphilipp it's not a regression. We use `RunNotifier` in our code base here: 

https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestClassExecuter.java#L112

The Maven/Eclipse/IntelliJ codebases [call](https://github.com/apache/maven-surefire/blob/b9a926d7b80d455da9003c0e1e122b0208eb8277/surefire-providers/surefire-junit4/src/main/java/org/apache/maven/surefire/junit4/JUnit4Provider.java#L164) the `fireTestRunFinished()` method, whose JavaDoc says "DO NOT CALL". We don't call it, resulting in missing events.

**Comment by marcphilipp** [comment]
While this happened before I was involved, I'm quite certain that the Javadoc "Do not call" is targeted at implementors of `Runner`. Having said that, I think it would be ok for you to call it. However, I don't see why you have to use RunNotifier directly. Can't you use `JUnitCore`?

```java
JUnitCore core = new JUnitCore();
core.addListener(listener);
core.run(request);
```

This way, it's `JUnitCore`'s responsibility to call `testRunStarted`/`testRunFinished`.

**Comment by thaddeusdiamond-smartercloud** [comment]
+1 for this feature.  Galen (http://galenframework.com/) has HTML report generators that are invoked in this manner.  It would be convenient not to have to create a Runner wrapper that invokes it directly.

**Comment by gigaga** [comment]
+1. I have the same problem...

**Comment by rmarone** [comment]
+1

**Comment by frejhaka** [comment]
+1

**Comment by dstucki** [comment]
Any updates/follow-ups on this issue?

**Comment by sbabcoc** [comment]
I posted a potential solution in the Help/Discuss forum that could help JUnit 4 users who need to attach RunListener providers to their test suites.
https://discuss.gradle.org/t/how-to-attach-a-runlistener-to-your-junit-4-tests-in-gradle/30788
The post describes how to configure a Gradle project to use the JUnit Foundation library to attach RunListener classes to JUnit 4 test suites. Listeners are specified in a ServiceLoader provider configuration file, and the library automatically attaches them.

**Comment by mleegwt** [comment]
A workaround: Use the vintage JUnit 5 runner. The reporting works there.
