### ISSUE TITLE
Warn if a class used in injection is not static

### ISSUE THREAD

**Issue by melix** [gradle/gradle#8423]
### Context

Whenever Gradle cannot find a constructor to use, the error we get is extremely misleading. For example, given the following rule:

```
dependencies {
   components.all(FixOksocialOutput::class.java)
}

open class FixOksocialOutput: ComponentMetadataRule {
   override fun execute(context: ComponentMetadataContext) = context.details.run {
      if (id.group == "com.baulsupp" && id.name == "oksocial-output") {
          allVariants {
             withDependencies {
                removeAll { name == "jackson-bom" }
             }
          }
      }
   }
}
```

Gradle fails with a spurious:

```
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > There was an error while evaluating a component metadata rule for io.netty:netty-bom:4.1.33.Final.
      > Could not create an instance of type Build_gradle$FixOksocialOutput.
         > The constructor for class Build_gradle$FixOksocialOutput should be annotated with @Inject.
```

So first thing you try then is to add an `@Inject` constructor:

```
open class FixOksocialOutput @javax.inject.Inject constructor(): ComponentMetadataRule { ... }
```

but then you're welcomed with a terrible error message:

```
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > There was an error while evaluating a component metadata rule for io.netty:netty-bom:4.1.33.Final.
      > Could not create an instance of type Build_gradle$FixOksocialOutput.
         > Index 0 out of bounds for length 0
```

when it turns out the problem has _nothing_ to do with `@Inject`. The problem is that the rule _captured a variable from the outer scope_. In this example, the rule should have been:

```
    removeAll { it.name }
```

(note the `it.`). Forgetting it means that the class is an inner class instead, and that it's _not static_. Therefore Gradle should capture this error properly and explain that either the class is not declared static, or that it probably captures a variable from the outer scope.

**Comment by adammurdoch** [comment]
This is something specific to Kotlin. For Java and Groovy implementations, Gradle will tell you that you're trying to create an instance of a non-static inner class.

**Comment by melix** [comment]
do not close

**Comment by eskatos** [comment]
This was fixed in Gradle 8.0 RC1. Here's what you get now:

```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.baulsupp:oksocial-output:4.19.0.
     Required by:
         project :
      > Could not resolve com.baulsupp:oksocial-output:4.19.0.
         > There was an error while evaluating a component metadata rule for com.baulsupp:oksocial-output:4.19.0.
            > Could not create an instance of type Build_gradle$FixOksocialOutput.
               > Class Build_gradle.FixOksocialOutput is a non-static inner class.
```

Test coverage added in
* https://github.com/gradle/gradle/pull/23498

**Comment by bric3** [comment]
In my opinion this message `Class Build_gradle.XXX is a non-static inner class.` is not that helpful in the context of kotlin.

Instead I believe this message should states this as well : `current task probably captures a variable from the outer scope.`
Describing remediation would be even nicer. E.g. suggest the developer to rewrite `abstract class XXX @Inject constructor(project: Project) { ... }`.

I believe this could fit nice in the new Problems / Reporting goals ?
* https://github.com/gradle/build-tool-roadmap/issues/49

What do you think ?

**Comment by eskatos** [comment]
Hi Brice,
That makes sense.
Care to open a separate feature request to suggest a remediation?

**Comment by bric3** [comment]
@eskatos Done #25494
