### ISSUE TITLE
Java/JUnit: includeCategories does not include parameterized category test method  

### ISSUE THREAD

**Issue by adude3141** [gradle/gradle#8424]
If we try to implement parameterised test method in nested classes and tag them with some category, those tests will not get executed with gradle.

The very same tests executed with e.g. IntelliJ platform test runner executes the test as expected.

```
package com.other;

import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.ArrayList;

import static org.junit.Assert.fail;

//@RunWith(Enclosed.class)
public class Categories {
    @Category(SomeCategory.class)
    @RunWith(Parameterized.class)
    public static class TagOnClass {
        @Parameterized.Parameter
        public String param = null;

        @Parameterized.Parameters
        public static Iterable<Object[]> getParameters() {
            ArrayList<Object[]> parameters = new ArrayList<>();
            parameters.add(new Object[] { "tag on class" });
            return parameters;
        }

        @Test
        public void run() {
            System.err.println("executed " + param);
        }
    }

    @RunWith(Parameterized.class)
    public static class TagOnMethod {
        @Parameterized.Parameter
        public String param = null;

        @Parameterized.Parameters
        public static Iterable<Object[]> getParameters() {
            ArrayList<Object[]> parameters = new ArrayList<>();
            parameters.add(new Object[] { "tag on method" });
            return parameters;
        }

        @Test
        @Category(SomeCategory.class)
        public void run() {
            System.err.println("executed " + param);
        }
    }

    public static class TagOnMethodNoParam {
        public String param = "none";

        @Test
        @Category(SomeCategory.class)
        public void run() {
            System.err.println("executed " + param);
        }
    }

    @RunWith(Parameterized.class)
    public static class Untagged {
        @Parameterized.Parameter
        public String param = null;

        @Parameterized.Parameters
        public static Iterable<Object[]> getParameters() {
            ArrayList<Object[]> parameters = new ArrayList<>();
            parameters.add(new Object[] { "untagged" });
            return parameters;
        }

        @Test
        public void run() {
            System.err.println("executed " + param);
        }
    }
}
```
with build file
```
plugins {
    id 'java'
}

repositories {
    jcenter()
}

dependencies {
    testCompile "junit:junit:4.13-beta-2"
//    testCompile "junit:junit:4.12" // this also fails on TagOnClass, see. https://github.com/gradle/gradle/issues/1153
}

task catTest(type: Test, dependsOn: tasks.testClasses) {
    testLogging {
        events "PASSED", "STARTED", "FAILED", "SKIPPED"
        showStandardStreams = true
    }

    reports.html.destination = file("$buildDir/reports/catTests")

    useJUnit {
        includeCategories 'com.other.SomeCategory'
    }
}
```

### Expected Behavior
Gradle should execute the same tests as plain unit

### Current Behavior
In the given example gradle does not execute *TagOnMethod.run*

### Steps to Reproduce (for bugs)
Compare the output running above test with 
`./gradlew clean catTest`
does not execute *TagOnMethod.run* whereas executing without gradle does.

gradle executes only `TagOnMethodNoParam.run` and `TagOnClass .run` whereas junit additionally executes `TagOnMethod .run`

### Your Environment
gradle 5.2
junit 4.13-beta-2

**Comment by marcphilipp** [comment]
@adude3141 Does this work with JUnit 4.12?

**Comment by adude3141** [comment]
There seems to be no difference between junit 4.12 and 4.13-beta-2 if executed *without* gradle.

If executed *with* gradle, junit 4.12 also misses `TagOnClass`.

**Comment by marcphilipp** [comment]
@adude3141 How exactly did you run the tests without Gradle?

**Comment by adude3141** [comment]
@marcphilipp 
It probably does not matter how to execute the junit test. I did use IntelliJ junit run config, i.e. not binding to delegate tests to gradle, but using intellijs platform runner.

I do expect junit runners. whether plain java, maven, ant or gradle to behave the same.

**Comment by marcphilipp** [comment]
That's a reasonable explanation. I was just wondering how you configured the category to be run.

**Comment by adude3141** [comment]
In Intellij:

Edit Configurations...
  add  new JUnit Configuration
 -> Set Test Kind to Category

**Comment by marcphilipp** [comment]
@adude3141 A fix will be released as part of 5.3 RC2. It would be great if you could give that a try when it's released.

**Comment by marcphilipp** [comment]
Resolved by #8731.

**Comment by adude3141** [comment]
Sure, @marcphilipp.

Thanks for fixing!

**Comment by adude3141** [comment]
Testet with 5.3-rc-3

Glad to confirm, that now this is working es expected.

@marcphilipp Thanks again for fixing!

**Comment by marcphilipp** [comment]
@adude3141 Thanks for testing! 👍
