### ISSUE TITLE
ComponentSelectionReason#isExpected gives different results between Gradle 5.0 and 5.1

### ISSUE THREAD

**Issue by chali** [gradle/gradle#8435]
We are using org.gradle.api.artifacts.result.ComponentSelectionReason#isExpected API however we noticed that it gives different results when moving from Gradle 5.0 to 5.1.1

### Expected Behavior
I would expect consistent behavior in both versions for the same situation.

### Current Behavior
It returns `false` in Gradle 5.0 it returns `true` in Gradle 5.1.1

### Context
We have this debugger view comparison which shows that in version 5.1.1 there is an additional description `requested` at the end of the descriptions list. The logic of `isExpected` is driven by that last entry. However, other reasons show that we applied rules which caused an upgrade of the version of my library.

#### Gradle 5.0
![image](https://user-images.githubusercontent.com/600335/52381782-ad3c1d80-2a27-11e9-9594-8b9048d4fed3.png)

#### Gradle 5.1.1
![image](https://user-images.githubusercontent.com/600335/52381799-b9c07600-2a27-11e9-94a9-9b3d8ea6e215.png)

**Comment by ljacomet** [comment]
So looking into this, I am failing to reproduce that 5.1.1 state showed in the report.
I can make the `isExpected` code more resilient to ordering in these descriptions but I wonder if there is not another issue hiding here.

Any chance you can provide a reproducer ?
