### ISSUE TITLE
Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy()

### ISSUE THREAD

**Issue by mounaim-dev** [gradle/gradle#8436]
I'm trying to run react-native project by typing `react-native run-android` and it appear that error

```
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at runOnAllDevices (/home/moun3im/Downloads/AwesomeProject/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/home/moun3im/Downloads/AwesomeProject/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/home/moun3im/Downloads/AwesomeProject/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
So what does it mean this error?
`Command failed: ./gradlew installDebug`

`Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy()`

**Comment by thuypt** [comment]
Check this question https://stackoverflow.com/questions/30840526/gradle-could-not-create-service-of-type-initscripthandler-using-buildscopeservic

**Comment by praween05** [comment]
Go to your project build.gradle file and change the gradle claaspath to 

`classpath` 'com.android.tools.build:gradle:3.3.1'`

because gradle wrapper 4.10 uses gradle 3.3.1 and also change the buildToolVersion to

` buildToolsVersion = "28.0.3"`

When I did that and build app from terminal the error go away

**Comment by mounaim-dev** [comment]
I fixed the problem, the problem was in my java 11. when I downgraded it to 8 it work fine, thank you

**Comment by big-guy** [comment]
There could be a lot of different things that cause this. 
- File permissions of ~/.gradle
- File permissions of the directory Gradle's running in

If you have a sample project, please reopen this issue and we can take a look. Thanks!

**Comment by fasihkhan320** [comment]
Same error I got but not resolved by downgraded

**Comment by kamithL** [comment]
Install Homebrew and Check It  its Work For me .

**Comment by fasihkhan320** [comment]
Resolved gridle version dependencies are there.
My android sdk platform version is 28.0.3 and Jdk version is 11 so I Downgraded to Jdk 8 after runing react-native run-android  multiply time for gridle download purpose now sucessfully run .

**Comment by radistao** [comment]
In my case the problem was when the project directory is mounted directly to docker container: 

`-v ${PWD}:/home/gradle/project -w /home/gradle/project`

in this case the owners are different and docker container user (either _gradle_ or _root_) can't override/delete `./buildSrc/build` or `./build/`. 

One of the fixes - copy the sources inside the container to temporary directory and build there.

**Comment by nitindutta5** [comment]
> I fixed the problem, the problem was in my java 11. when I downgraded it to 8 it work fine, thank you

How did you downgrade your java
?

**Comment by radistao** [comment]
> How did you downgrade your java

https://www.google.com/search?q=debian+update+alternatives+java

BUT, this should not be a solution:  i built it in Java 11 successfully.

**Comment by fsalazarsch** [comment]
> There could be a lot of different things that cause this.
> 
> * File permissions of ~/.gradle
> * File permissions of the directory Gradle's running in

First usable answer, searched in a lot of forums

**Comment by sambit15k** [comment]
I was in a similar situation , All i had to do is chmod 777 .gradle/ on the project directory & my jenkins started building the project .

**Comment by fat-tire** [comment]
I'm just gonna throw this out there too in case anyone's googling for this error-- make sure that you're logged in as the user you THINK you're logged in as-- if you forgot you're User A but in User B's directory trying to build and getting this error..  try logging in as the user you meant to be cuz you probably don't have access to write in ~/.gradle :)

**Comment by graylancome** [comment]
> I was in a similar situation , All i had to do is **chmod 777 .gradle/** on the project directory & my jenkins started building the project .

This solved my issue running Gradle in docker

**Comment by lahiruk** [comment]
> There could be a lot of different things that cause this.
> 
>     * File permissions of ~/.gradle
> 
>     * File permissions of the directory Gradle's running in
> 
> 
> If you have a sample project, please reopen this issue and we can take a look. Thanks!

I changed `docker run --rm -u gradle` to `docker run --rm -u root`

**Comment by NashieArtz** [comment]
Hi, I have the same problem here, but I am literally new to all of this, I tried to understand but welp, can't really. I don't know how to do all what is said on the above about giving permissions about --stacktrace or chmod777, etc. My JDK is 8u261. If anyone has the patience to guide me step by step and with details, I appreciate it. If you want a private conversation so that it's more fluid, I have discord: Nashie_3.30am#6513.

Thanks.

**Comment by mdaniyalaslam** [comment]
fix by running `sudo chmod -R 777 ./` in your project root directory

**Comment by sragha45** [comment]
> fix by running `sudo chmod -R 777 ./` in your project root directory

Thanks, you saved my day

**Comment by utkukutlu** [comment]
run this  **find ./ -name "*.lock" -type f -delete** in your project root directory

**Comment by aftabaminzoobiapps** [comment]
fixed.  
check this 
[https://stackoverflow.com/questions/53272230/could-not-create-service-of-type-scriptpluginfactory-using-buildscopeservices-cr/65932283#65932283](url)

**Comment by saed13272** [comment]
It was solved for me like this:
In the Windows 10 antivirus section, there was a message stating that Action gradle was blocked by antivirus and administrator, and I set the access permission to allow, and the problem was resolved.
![1](https://user-images.githubusercontent.com/84316430/118474573-76820100-b720-11eb-9f9f-8936039e18d1.jpg)

**Comment by MenachemICTBIT** [comment]
> It was solved for me like this:
> In the Windows 10 antivirus section, there was a message stating that Action gradle was blocked by antivirus and administrator, and I set the access permission to allow, and the problem was resolved.
> ![1](https://user-images.githubusercontent.com/84316430/118474573-76820100-b720-11eb-9f9f-8936039e18d1.jpg)

Gosh darn it, Microsoft! This has caused me so many weird developer bugs... Thank you for pointing this out.

**Comment by shilpi-A** [comment]
Hi All i am facing same error could pls help: 
* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

**Comment by said8811** [comment]
> 

u can download java version and put it in directory which your current java staying at
