### ISSUE TITLE
Generated Visual Studio files for NativeTestSuiteBinarySpec components execute the wrong build command

### ISSUE THREAD

**Issue by donalmacc** [gradle/gradle#844]
Following on from [816](https://github.com/gradle/gradle/issues/816), the `VisualStudioProjectRegistry` only generates install tasks for `NativeExecutableBinarySpec`(seen [here](https://github.com/gradle/gradle/blob/f001402c8b7f404c923d972f1bc524b2de7b3fcd/subprojects/ide-native/src/main/groovy/org/gradle/ide/visualstudio/internal/VisualStudioProjectRegistry.java).)

I have attempted a fix for the bug, however I am not sure if the solution is good enough. Should `NativeTestSuiteBinarySpec` inherit from `NativeExecutableBinarySpec`, instead of `NativeTestSuite`, or should the `ExecutableVisualStudioProject` be generated for `NativeTestSuiteBinarySpec`

### Expected Behavior
The NMake build command of a NativeTestSuiteBinarySpec should be the install command, and the NMake output file should be the output of the install task.

### Current Behavior
The NMake build command of a NativeTestSuiteBinarySpec is the `assemble` or `build` task, and the NMake Output file is the output of this task instead.

### Context
Trying to debug executables generated with the Google test plugin fails. I initially believed that this was all executables, however on further inspection I was wrong.

### Steps to Reproduce (for bugs)
add `apply plugin: 'visual-studio'` to the google test sample, and generate a visual studio project for the executable.

### Your Environment
gradle 3.1/3.2, Windows 10 x64.

**Comment by big-guy** [comment]
Visual studio support for NativeTestSuiteBinarySpecs will be improved where it overlaps with other improvements we're making to support the new C++ plugins. 

I've opened https://github.com/gradle/gradle-native/issues/503 to capture that we need to support test components in the new C++ plugins.
