### ISSUE TITLE
Task Configuration Avoidance is missing a report API

### ISSUE THREAD

**Issue by stephanenicolas** [gradle/gradle#8444]
It would be very interesting to get some reporting on task config avoidance as a gradle API. Using the build scan plugin is not always possible (disclosure issue for instance) and it cannot be automated too. 

We would love to be able to:
* print the number of tasks created lazily, eagerly
* their names, their location
* who created them
* build tools to verify that all new plugins doesn't trigger the early creation of tasks that were previously avoided.

**Comment by lacasseio** [comment]
Could you explain what you mean by "not always possible" with the build scan plugin? It could be a missing feature for that plugin to collect the right information.

As to how to actually solve this, there are 2 ways to do it:
 - If you are lucky enough to still use a Gradle version that supports the [internal flag `org.gradle.internal.tasks.stats`](https://docs.gradle.org/5.0/userguide/task_configuration_avoidance.html#sec:how_do_i_know_its_working), you can use it to receive some statistic after the build. Note this will be removed in the future without notice.
 - The "official way" would be to roll your own logic that attaches a `configureEach` to every task container of every project to collect the information you need. The earlier you can attach this configuration the better. Probably something in a init or settings script but could get around with something in the root project. You should be able to get the number of tasks in the container after the build finishes versus the number of tasks you have seen being resolved. Each configuration action being called would allow you to get the name, path and, with some stack trace analysis, who created them.

Given all this, it would be better if you could provide some missing use case for the scan plugin to handle given it already have access to all that information. I will close this issue but feel free to post your use case here.
