### ISSUE TITLE
android.enableSeparateAnnotationProcessing=true

### ISSUE THREAD

**Issue by Yousha** [gradle/gradle#8445]
### Expected Behavior
Using `android.enableSeparateAnnotationProcessing=true` without any warning.

### Current Behavior
Got the following warnings from the compiler/builder:
With `android.enableSeparateAnnotationProcessing=true`

> The option setting `android.enableSeparateAnnotationProcessing=true` is experimental and unsupported.
> The current default is 'false'.

With `android.enableSeparateAnnotationProcessing=false`

> Gradle may disable incremental compilation as the following annotation processors are not incremental: compiler-1.1.1.jar (android.arch.persistence.room:compiler:1.1.1), compiler-4.8.0.jar (com.github.bumptech.glide:compiler:4.8.0), butterknife-compiler-8.6.0.jar (com.jakewharton:butterknife-compiler:8.6.0). Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.

### Context
I added this new option in my **gradle.properties** file:
`android.enableSeparateAnnotationProcessing=true`

### Your Environment
Windows 10 64bit
JRE 1.8.0_152-release-1136-b06 amd64
JVM OpenJDK 64-Bit Server VM by JetBrains s.r.o
Android Studio 3.2.1 Build #AI-181.5540.7.32.5056338
Gradle 4.10.3
Android Gradle plugin: 3.3.1

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-v13:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:support-vector-drawable:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    annotationProcessor 'android.arch.persistence.room:compiler:1.1.1'
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
    implementation 'android.arch.persistence.room:runtime:1.1.1'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.github.satyan:sugar:1.5'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation('com.squareup.retrofit2:converter-simplexml:2.3.0') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
    implementation 'com.squareup.okhttp3:logging-interceptor:3.8.0'
    implementation 'com.jakewharton:butterknife:8.6.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.6.0'
    implementation 'com.wealdtech.hawk:hawk-core:1.2.2'
    implementation 'com.github.tosslife:pullloadview:1.1.0'
    implementation 'com.github.faruktoptas:FancyShowCaseView:1.0.1'
}
```

 * Build scan URL: 
https://gradle.com/s/ryyiuya2kc53q

**Comment by big-guy** [comment]
This is a feature of the Android plugin and not Gradle itself.  There's not much we can do to stop them from emitting a warning about an experimental option.
