### ISSUE TITLE
gradlew fails when run in a directory with semicolons

### ISSUE THREAD

**Issue by dhaugh** [gradle/gradle#845]
### Expected Behavior

Expect to compile cleanly
### Current Behavior

currently, gradlew returns the output `Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`
Prevents compilation

### Steps to Reproduce (for bugs)

create a directory with the following structure
<directory with semicolons in it>
| - gradlew
| - gradle/
&nbsp; &nbsp;| - wrapper
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| - gradle-wrapper.jar
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| - gradle-wrapper.properties

./gradlew assembleDebug returns 
`Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain`
### Your Environment

 * Build scan URL:

**Comment by big-guy** [comment]
Which version of Gradle are you using?

Which OS are you on?

What's the output of `unzip -p gradle/wrapper/gradle-wrapper.jar build-receipt.properties`?

**Comment by eriwen** [comment]
This issue has been `not-actionable` for over a week. Closing for now, please reopen if you have additional information, an example, or a build scan.
