### ISSUE TITLE
Gradle -console plain output not showing dependency download status

### ISSUE THREAD

**Issue by plasm0r** [gradle/gradle#8451]
### Expected Behavior
When a project has 3rd party dependencies that require downloading from a repository and '-console plain' is enabled, progress for each download should be shown so the user is aware of what Gradle is doing.

### Current Behavior
When Gradle is invoked with the '-console plain' option, Gradle pauses while downloading any 3rd party dependencies to the cache with no feedback to the console/user until all dependencies have been downloaded.

### Context
We need to run Gradle in '-console plain' mode because we are invoking it via another script and prefer to use the plain console output. For large projects that require the download of a large number of dependencies, Gradle doesn't show any messages about the status of the dependency downloads leaving the user confused as to what Gradle is doing as it pauses for a long period of time before continuing after the downloads are completed..

### Steps to Reproduce (for bugs)
Add some 3rd party dependencies to your project that require download from a repository to the local cache. Then build your project with the '-console plain' option. Observe that no download status messages are shown for each dependency that is being downloaded.

### Your Environment
Windows 10, OpenJdk 11.0.2, Gradle 5.2

**Comment by oehme** [comment]
Whoever looks into this, please note that this was intentionally removed, because the verbose download messages were annoying other users.

**Comment by waiting0729** [comment]
I also encountered the same problem. I also want to know dependency download status in High version gradle. Is there a configuration?

**Comment by howardpang** [comment]
I also encountered the same problem, then download info is useful for me ,i think it can't add a option to gradle properties to control the output
