### ISSUE TITLE
False circular dependency: incoming.artifacts bring dependency from non related configuration 

### ISSUE THREAD

**Issue by Jonatha1983** [gradle/gradle#8464]
When working in a multi project environment - having one project with a compile (or implementation) dependency on another Project, we end up with unexpected dependencies: 
Using the compile.incoming.artifacts of the first we are getting runtime dependencies of the second(transitively) as well. 
 
### Expected Behavior
When using configurations.XXX.incoming.artifacts.artifacts we expect to get XXX dependency only.

### Current Behavior
For example: configurations.compile.incoming.artifacts.artifacts  bring runtimeOnly dependency also. 

### Context
Stopper - since we get a circular false positive dependency. 

### Steps to Reproduce (for bugs)
Create a multiiproject environment: 
settings.gradle
```
rootProject.name = "IssueX"
include` "a","b","c","d"
```
//a folder
build.gradle
```
plugins{ id "java" }
dependencies {
    compile project(':b')
}
tasks.register("printMyCompileArtifacts") {
    doLast {
        configurations.compile.incoming.artifacts.artifacts.each { println "File: ${it.getFile()}"}
    }
}
````
//b folder 
build.gradle 
```
plugins{ id "java" }
dependencies{
    runtimeOnly project(':c')
}
```
//c folder
build.gradle 
```
plugins{ id "java"}
dependencies{
    runtimeOnly project(':d')
}
```
//d folder
build.gradle
`plugins{ id "java"}`

When running printMyCompileArtifacts we get: 
> Task :a:printMyCompileArtifacts
File: F:\views\g\IssueX\b\build\libs\b.jar
File: F:\views\g\IssueX\c\build\libs\c.jar
File: F:\views\g\IssueX\d\build\libs\d.jar

While expecting only b. 

### Your Environment
Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_101 (Oracle Corporation 25.101-b13)
OS:           Windows 7 6.1 amd64

 * Build scan URL: 
https://scans.gradle.com/s/mrcavfpwu45ec

**Comment by oehme** [comment]
Please use `compileClasspath`, not `compile`. `compile` is not meant to be resolved and only allowed to be for backwards compatibility.

**Comment by Jonatha1983** [comment]
Is there any rules regarding which configuration can be resolved and which cannot ? Any document that explain this  ?

Also it happen also with implementation configuration - if one use a new configuration that extends implementation and later he try to resolve it in the same way specified above - he end up with  the same result ( both implementation and runtimeOnly )

**Comment by melix** [comment]
For backwards compatibility reasons, every configuration is _by default_ created with `canBeResolved=true`, which is not super nice, but unfortunately necessary. This explains why `compile` is `canBeResolved=true`. 

The reason is will not work either when you extend implementation is that you don't give enough information to the engine to select the appropriate variants (aka the right attributes).

You can find details about how it works in the docs: https://docs.gradle.org/current/userguide/dependency_management_attribute_based_matching.html

**Comment by Jonatha1983** [comment]
Thanks i will read it - I hope to find an answer there to why i am getting other configuration deps ( e.g. runtimeOnly)  when i am resolving another resolvable configuration. 

Thanks again.
