### ISSUE TITLE
Issues with guides.gradle.org

### ISSUE THREAD

**Issue by CodingKoopa** [gradle/gradle#8465]
The [Gradle homepage](https://gradle.org/) links to [this page](https://gradle.org/guides/#getting-started) for getting started. However, the [Getting Started](https://docs.gradle.org/current/userguide/getting_started.html) page of the User Manual not only does a much better job of starting from nothing, but is better updated.

As an example, the [C++ tutorial of the User Manual](https://docs.gradle.org/current/userguide/cpp_plugins.html) is properly updated for the new `cpp` plugin. The [other guide](https://guides.gradle.org/building-cpp-libraries/), however, uses the old method of using C++, and includes no mention of it being outdated.

Additionally, the two sites are confusingly similar, resulting in navigation being made difficult:
![image](https://user-images.githubusercontent.com/13039555/52529423-74b67100-2cbf-11e9-874c-b40f67bf8cb2.png)

For these reasons, I feel that something should be done to reduce confusion, for example:
- Retire `guides.gradle.org`, and use `docs.gradle.org` as the "one" Gradle tutorial. I feel that the latter is comprehensive enough that this is possible, and makes things easier to follow.
- Add notices to `guides.gradle.org` about when an update is needed. Finding the outdated guide only to find the newer one later was, frankly, very frustrating for me.

**Comment by blindpirate** [comment]
@CodingKoopa Thanks for the suggestion! 

@gradle/developer-experience I think the out-of-date doc is worse than nothing. WDYT?

**Comment by eriwen** [comment]
Until Gradle 5.2 these guides were not outdated, and there was no docs.gradle.org content for the new C++ plugins. 

@big-guy @lacasseio you are responsible for making sure users are successful in your domain. I suggest you hide the guide or update it when you have a chance. I trust your judgement.

**Comment by big-guy** [comment]
There were PRs waiting for 5.2 to be released to merge, so the guides have been updated.

**Comment by CodingKoopa** [comment]
Thanks! That pretty much addresses the issue.
