### ISSUE TITLE
Allow distributionUrl be set from an environment variable

### ISSUE THREAD

**Issue by yeralin** [gradle/gradle#8477]
In generated `gradle-wrapper.properties`, I'd like to have an ability to use environment variables for `distributionUrl` property. 
For example, my current `gradle-wrapper.properties` is
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```
It is confusing that we can use `GRADLE_USER_HOME` for `distributionBase` or `zipStoreBase`, but if we try to set an env variable for `distributionUrl`, as for example `distributionUrl=GRADLE_DIST_PATH` that I pre-defined as something like `GRADLE_DIST_PATH=file:/<path>/gradle-<version>-bin.zip`, the variable will not resolve.

### Expected Behavior
You set `distributionUrl` to an environment variable that will get resolved by gradle at runtime.

### Current Behavior
It does not resolve set env variable (only works with either HTTP(S) links or hardcoded file paths like `https\://services.gradle.org/distributions/gradle-4.4-all.zip` or `file:/<path>/gradle-<version>-bin.zip`)

### Context
In my environments, I don't have access to `https://services.gradle.org`, and I'm running multiple builds with gradle binaries located at different (non-static) paths. So, I'd like  to be able to set `distributionUrl` to some env variable that I can define later in my pipeline.

### Steps to Reproduce
Export an environment variable (in the same fashion as `GRADLE_USER_HOME`), set `distributionUrl` to that variable, and run a gradle task.

### Your Environment
Does not apply

### Comment
I understand that I can intercept `wrapper` gradle task and regenerate `gradle-wrapper.properties` with the values I want. But I'd rather avoid that. It just creates a confusion that we can use `GRADLE_USER_HOME` variable for `distributionBase` or `zipStoreBase` in `gradle-wrapper.properties`, but we can't do the same for `distributionUrl`.

Something similar was already raised here: 
https://discuss.gradle.org/t/gradle-wrapper-in-environments-that-require-controlled-builds/11848
https://stackoverflow.com/questions/22896569/how-to-use-gradle-zip-in-local-system-without-downloading-when-using-gradle-wrap

**Comment by big-guy** [comment]
I don't think we want to do this.  `GRADLE_USER_HOME` isn't an environment variable in this context, it's just a value we recognize that has a special meaning (the other one is `PROJECT`).  It's important for the builds to declare which version of Gradle they require, so providing a URL from the environment defeats that. 

> In my environments, I don't have access to `https://services.gradle.org`, and I'm running multiple builds with gradle binaries located at different (non-static) paths.

Are you completely cut off from the internet or could you mirror `https://services.gradle.org/distributions` via Artifactory (or another artifact repository)?  That would let you use an internal-only URL that points to a particular version of Gradle without relying on services.gradle.org.

I'm not sure I understand the importance of why you have multiple Gradle binaries with different paths.  Are you saying that you might have three different Gradle 5.0 URLs that may need to be used/switched out dynamically?

**Comment by yeralin** [comment]
In my case, I have multiple environments where gradle could be placed at different paths. But it's okay, I think I found a workaround.

**Comment by faruktoptas** [comment]
@yeralin I've got the same problem can you explain your workaround?

**Comment by yeralin** [comment]
@faruktoptas I ended up packaging gradle within my workspace, and then accessing it locally using `distributionUrl=file://`

**Comment by mrburrito** [comment]
@big-guy found this issue when searching for a way to do exactly this. We are in a scenario where we need to build a project in multiple locations, each with their own URL for gradle distributions and without having a common endpoint they can hit. It would be really nice to have the ability to use environment variables to define all or part of the `distributionUrl`.

Example:

```
distributionUrl=${GRADLE_DISTRIBUTION_URL}/gradle-6.3-all.zip
```

The workarounds we've come up with all require assumption of having tools like `envsubst`, `sed`, or another pattern substitution command available and a more portable solution would be preferred.

**Comment by viqbgrg** [comment]
inin.gradle
```groovy
afterProject{
    allprojects{
        tasks.named('wrapper') {
            distributionUrl = "https://mirrors.cloud.tencent.com/distributions/gradle-" + gradleVersion + "-" + (distributionType.name().toLowerCase(Locale.ENGLISH)).toString() + ".zip"
        }
    }
}
```

**Comment by penguin-cloud** [comment]
Downloading every build is stupid waste of bandwidth.  It does not change that often and makes builds slow on enterprise systems.  This was not thought out and only works inside tech firms that have no rules.

we ABSOLUTELY should have the power to allow variables in the URL.

**Comment by PayBas** [comment]
Why is this closed? This still remains a major p.i.t.a. for anyone inside a fenced-off corporate network.

**Comment by blipper** [comment]
This is pretty important for us too.

**Comment by samrocketman** [comment]
I proposed this discussion and patch in 2018.  The patch for this is simple (only 7 lines) but unfortunately was rejected.

https://github.com/gradle/gradle/pull/6349

https://discuss.gradle.org/t/support-for-gradle-wrapper-distribution-mirror/26838

This is pretty critical in any environment but for reasons unknown to me there’s no desire to support it.
