### ISSUE TITLE
IDEA shows incorrect number of buildSrc dependencies

### ISSUE THREAD

**Issue by Dibro89** [gradle/gradle#8478]
### Expected Behavior
IDEA's Gradle view should show correct number of `buildSrc` default dependencies.

### Current Behavior
Shows every default dependency twice (or even thrice in `test` Source Set).

### Context
The issue is cosmetic and doesn't really bother me.
Also custom dependencies declared in `buildSrc/build.gradle(.kts)` are not affected.

### Steps to Reproduce (for bugs)
Create a Gradle project with `buildSrc` dir.
Create a `buildSrc/build.gradle(.kts)` file, it may be empty.
Open Gradle view in IDEA.

### Your Environment
Ubuntu 18.10, OpenJDK 8, Gradle 5.2.1, IntelliJ IDEA 2018.3.4 (snap).

![screenshot_20190211_190542](https://user-images.githubusercontent.com/16293890/52580214-91be8180-2e30-11e9-96e3-c0a6f7a3acd9.png)

**Comment by big-guy** [comment]
@wolfs @blindpirate is this something you guys have noticed before?

**Comment by blindpirate** [comment]
I can confirm this issue with my IDEA 2018.3.1 + Gradle 5.0. Will investigate it.

**Comment by blindpirate** [comment]
This is an IDEA issue. Opened issue there: https://youtrack.jetbrains.com/issue/IDEA-207207

It was also reported by other people: https://youtrack.jetbrains.com/issue/IDEA-181666
