### ISSUE TITLE
Allow multiple headers in http authencation

### ISSUE THREAD

**Issue by tobad357** [gradle/gradle#8481]
### Expected Behavior

Currently it isn't possible to include multiple custom headers using HttpHeaderCredentials/HttpHeaderAuthentication (or at least I can't find a way)
This means that it isn't possible to use [Cloudflare Access](https://blog.cloudflare.com/give-your-automated-services-credentials-with-access-service-tokens/) in front of a repository and/or gradle cache.

Cloudflare Access needs two headers sent at once and then normally the underlying site would also need an access token sent which in turn means three headers in total

Cloudflare Headers needed
```
CF-Access-Client-ID:
CF-Access-Client-Secret:
```

### Current Behavior

Not possible to send two or more HttpHeaderCredentials in one authentication

Allow something like this to send multiple custom headers

```
repositories {
	maven {
		url "https://mvn.site.com/repository/maven-central"
        credentials(HttpHeaderCredentials) {
            name = "CF-Access-Client-Id"
            value = "yyyyy"
        }
        credentials(HttpHeaderCredentials) {
            name = "CF-Access-Client-Secret"
            value = "xxxx"
        }		                
        authentication {
            header(HttpHeaderAuthentication)
            header(HttpHeaderAuthentication)
        }        
    }	
}
```
### Context

We are trying to add Cloudflare Access in front of our domains so we can access repositories etc without VPN while at the same time not exposing them to the world.

### Your Environment

 * Build scan URL:

**Comment by ld0614** [comment]
We also have a requirement to send 2 named headers to access a maven repository.  This is so we can use Azure AD Application Proxy to provide secure external access into an environment.

**Comment by mchave** [comment]
This is currently a blocking issue for us.

**Comment by Alexmatiron** [comment]
That would be awesome feature to have . Can't wait to have it

**Comment by liamsill** [comment]
Please fix. This is a big issue for us.

**Comment by jeantil** [comment]
has anyone ever found a solution for this ?

**Comment by qwpto** [comment]
Not yet, and we still need it.

**Comment by qoomon** [comment]
We still need this. Our scenario is as follows.

`GithubActions` -> `Private OIDC-Gateway` -> `Private Nexus`

* for Authentication against `OIDC-Gateway` an `Proxy-Authentication: Bearer ...` header is needed
* for Authentication against  `Private Nexus` an `Authentication: Basic ...` header is needed

**Comment by kyhule** [comment]
Has anyone found a workaround for this? Currently running into the same problem as we are migrating our code to Github Enterprise Cloud and Github Actions but need to get to our internal artifactory through a proxy.

**Comment by ljacomet** [comment]
Keeping it closed as a duplicate of the other issue, even if more recent.
