### ISSUE TITLE
new rich console output not working with gradle 5.2.x and mintty, zsh, tmux

### ISSUE THREAD

**Issue by mrt181** [gradle/gradle#8484]
### Expected Behavior
task status updates not repeated but sticking to one line
colored output

### Current Behavior
![capture](https://user-images.githubusercontent.com/161961/52632687-8320aa80-2ec2-11e9-834e-f9d4a2ecaaf6.png)

### Context
trying out new 5.2.x feature
probably related to #8189  #5735 #2845 #6970 #8204

### Your Environment
Windows 7 x64
Cygwin 2.895 x64
mintty 2.9.6-0
zsh 5.5.1-1
tmux 2.6-1

**Comment by mrt181** [comment]
still broken with `v5.4.1`

**Comment by moneytoo** [comment]
Still an issue as of ``v6.2.1``. The interactive progress is messing the output for me in latest Cygwin (bash) but also in log of Jenkins (2.223 on top of CentOS 7). As a workaround, I have to use ``--console=plain``.

**Comment by mcooper7290** [comment]
I'm seeing the same problem.  Gradle 6.2.1 with Cygwin 3.1 bash window.
