### ISSUE TITLE
Debug messages are lost when using slf4j in worker api process isolation mode

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#8487]
If you submit an item of work using process isolation mode and that item of work grabs an SLF4J logger and logs a message in debug mode, the message never makes it to the logging subsystem, even if the Gradle logger log level is set to debug.

### Expected Behavior
Logging in a worker daemon should work the same as logging in the build process and capture SLF4J log events if the Gradle log level is set appropriately.

### Current Behavior
We currently capture warn and above from slf4j, but info and debug messages don't seem to get captured with process isolation mode.

**Comment by big-guy** [comment]
This appears to be fixed in 5.5 already.
