### ISSUE TITLE
Task output files should be able to change during task execution

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#8493]
When wrapping tools that, given a configuration file, it will output a set of files that aren't known ahead of time but won't change for the same input.

### Expected Behavior

A task should be able to change the output file collection. The change should be considered during the snapshot after execution.

### Current Behavior

Gradle saves the output file collection result before execution (most likely during output overlapping calculation) and snapshot this saved file collection after execution. It effectively makes the task out-of-date at least once after an execution.

### Context

A concrete example is `yarn install`. Assuming the `package.json` resolve to fixed dependency version, all the files present in `node_modules` after a clean `yarn install` are the output of the task in question. Any change to this baseline of files will require a new install. However, any new files (because of in directory build/file generation) won't require a new install and the task should be considered up-to-date. The output files can be tracked via a snapshot file generated at the end of the task execution that lists all the files present after a fresh install. The snapshot file is not of interest but the content of the files listed in that snapshot file is.

### Steps to Reproduce (for bugs)

Here is a [patch of an integration test](https://github.com/gradle/gradle/files/2858242/patch.txt) showing this behaviour:
```
diff --git a/subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/UpToDateIntegTest.groovy b/subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/UpToDateIntegTest.groovy
index a700fc19ec1..20db0cecfcb 100644
--- a/subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/UpToDateIntegTest.groovy
+++ b/subprojects/core/src/integTest/groovy/org/gradle/api/internal/changedetection/state/UpToDateIntegTest.groovy
@@ -16,6 +16,7 @@
 
 package org.gradle.api.internal.changedetection.state
 
+
 import org.gradle.integtests.fixtures.AbstractIntegrationSpec
 import spock.lang.Issue
 
@@ -123,4 +124,102 @@ public class CreateEmptyDirectory extends DefaultTask {
         skipped customTask
         result.output =~ /Skipping task '${customTask}' as it is up-to-date\./
     }
+
+    def "can modify the output files listing during execution"() {
+        buildFile << '''
+            task customTask(type: CustomTask) {
+                dependencies.put("foo", "foo")
+                dependencies.put("bar", "bar")
+            }
+
+            class CustomTask extends DefaultTask {
+                @OutputFiles
+                FileCollection outputFiles = project.files(project.provider {
+                    if (!project.file("$temporaryDir/snapshot.txt").exists()) {
+                        return []
+                    }
+                    return project.file("$temporaryDir/snapshot.txt").readLines().collect {
+                        new File(it)
+                    }
+                });
+
+                @Input
+                Map<String, String> dependencies = [:]
+
+                @TaskAction
+                void doStuff() {
+                    def s = project.file("$temporaryDir/snapshot.txt")
+                    s.delete()
+                    project.file("$temporaryDir/node_modules").delete()
+
+                    dependencies.entrySet().each { e ->
+                        project.file("$temporaryDir/node_modules/${e.key}.txt").with {
+                            it.parentFile.mkdirs()
+                            it.text = e.value
+                            s << it.absolutePath + "\\n"
+                        }
+                    }
+                }
+            }
+        '''
+        def customTask = ":customTask"
+
+        // TEST 1
+        when:
+        println("TEST #1: Clean execution")
+        run customTask, "--info"
+        then:
+        executedAndNotSkipped(customTask)
+
+        when:
+        // HACK: Needs to run the task another time to make it up-to-date
+//        run customTask, "-i"
+        println("ENSURE UP-TO-DATE")
+        run customTask, "-i"
+        then:
+        skipped(customTask)
+
+        when:
+        println("TEST #2: Mess around with known outputs")
+        file("build/tmp/customTask/node_modules/foo.txt").delete()
+        run customTask, "-i"
+        then:
+        executedAndNotSkipped(customTask)
+
+        when:
+        println("ENSURE UP-TO-DATE")
+        run customTask, "-i"
+        then:
+        skipped(customTask)
+
+        when:
+        println("TEST #3: Change input which cause more output")
+        buildFile << '''customTask.dependencies.put("g", "g")\n'''
+        run customTask, "-i"
+        then:
+        executedAndNotSkipped(customTask)
+
+        when:
+        // HACK: Needs to run the task another time to make it up-to-date
+//        run customTask, "-i"
+        println("ENSURE UP-TO-DATE")
+        run customTask, "-i"
+        then:
+        skipped(customTask)
+
+        when:
+        println("TEST #4: Change input which cause less output")
+        buildFile << '''customTask.dependencies.remove("foo")\n'''
+        run customTask, "-i"
+        then:
+        executedAndNotSkipped(customTask)
+
+        when:
+        // HACK: Needs to run the task another time to make it up-to-date
+//        run customTask, "-i"
+        println("ENSURE UP-TO-DATE")
+        run customTask, "-i"
+        then:
+        skipped(customTask)
+    }
 }
```

### Your Environment

 * Build scan URL:

**Comment by wolfs** [comment]
@lacasseio Gradle assumes that the location of the output files is fixed when the task starts to execute. The location of the output files is the configuration of the task. So these locations should not change during task execution and Gradle fixes the locations when it takes a snapshot of the outputs before execution.

Regarding your use-case of taking a snapshot of a directory and then considering only the new/changed files as outputs of the task: This is already done automatically by Gradle, so there is no need to add some custom code. More precisely, before the task starts executing its actions, Gradle takes a snapshot of the output directories/files. Then, after the task finished executing, it takes another snapshot and compares the snapshot before task execution to the snapshot after task execution. Only the files which changed between the two snapshots (or which are already considered an output of the task) will be considered a part of the task's output and considered for up-to-date checks. That is exactly the behaviour you want to model, right?

**Comment by lacasseio** [comment]
I can confirm this is working as expected. My bad for the noise.
