### ISSUE TITLE
task.inputs.files allows registering invalid input that task.inputs.file disallows

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#8495]
If you register an input file with `task.inputs.file 'nowhere.ext'` that does not exist, Gradle barfs and errors out.
If you register the same file with `task.inputs.files 'nowhere.ext'`, no error happens.
Maybe this is intended, but shouldn't it error out the same way?
If you want to have optional input files, you can always do it with `task.inputs.files filetree('nowhere.ext')`.

**Comment by wolfs** [comment]
That is currently expected, as Gradle does not have more information about things in the file collection.
