### ISSUE TITLE
Gradle DSL method not found: 'destination()' after update to Gradle 5.2.1

### ISSUE THREAD

**Issue by userdimi** [gradle/gradle#8498]
After updating to Gradle 5.2.1 my build is failing with this error: 

`Gradle DSL method not found: 'destination()'`

I figured out that this error has something todo with my `analysis.gradle`

My `analysis.gradle` looks like that

    apply plugin: 'checkstyle'
    apply plugin: 'pmd'
    apply plugin: 'jacoco'

    jacoco {
    toolVersion = "0.7.7.201606060606"
    }

    check.dependsOn 'checkstyle', 'pmd', 'lint'

    task checkstyle(type: Checkstyle) {
    println "----- checkstyle -----"
    configFile file(projectDir.getAbsolutePath() + '/analysis/checkstyle-ruleset.xml')

    source 'src'
    source '../domain/src'
    source '../util/src'
    include '**/*.java'
    exclude '**/gen/**'
    exclude '**/java-gen/**'
    exclude '**/androidTest/**'
    exclude '**/test/**'

    ignoreFailures = true

    classpath = files()

    reports {
        xml {
            destination buildDir.absolutePath + "/outputs/reports/checkstyle_report.xml"
        }
    }
}
 
I think I have to replace the `destination` flag but I have no idea how to replace it.

**Comment by big-guy** [comment]
@userdimi which version of Gradle were you coming from?

Does this fix it?
```
reports {
    xml {
        destination = new File(buildDir, "outputs/reports/checkstyle_report.xml")
    }
}
```

**Comment by userdimi** [comment]
@big-guy Unfortunately, no. By building I've getting this error: 

`Unable to create Root Module: config {/Users/fooUser/Projects/barProject/analysis/checkstyle-ruleset.xml}, classpath {null}.`

I've checked the path and there is nothing wrong with it. /../barProject/analysis/checkstyle-ruleset.xml

Maybe is something wrong with my checkstyle-ruleset.xml?

**Comment by userdimi** [comment]
I've moved my rulesets for checkstyle and pmd from analysis folder to config folder. Now everything is fine. Thank you a lot

**Comment by miPlodder** [comment]
@userdimi It worked, but the filename is `quality.gradle`.

**Comment by savitasoni** [comment]
in quality.gradle file too it won't work for me

**Comment by savitasoni** [comment]
how to resolve  ERROR: Gradle DSL method not found: 'destination()'
