### ISSUE TITLE
Overload ambiguity for put(T, value) and put(T, provider { value }` when using MapPropery<T, Any>.put(T, any)

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#8500]
We have been using a `MapProperty` that should accept the `Any` type for values that later get converted and massaged to be passed into a CLI application. The values that get converted can be files, strings, etc, so the choice was made to use `MapProperty` that accepts `RegularFile`, `Directory`, and any other type that would be converted during execution time.

### Expected Behavior

Possibly a clearer path to follow the pattern described above. It could also just be the way things are and this is a minor wart to deal with if you use `MapProperty<K, Any>`.

### Current Behavior

```kotlin
import org.gradle.api.Project
import org.gradle.api.file.Directory
import org.gradle.api.file.RegularFile
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Provider

fun overloadAmbiguity(project: Project, mapProperty: MapProperty<String, Any>) {
  mapProperty.put("keyProviderPut", project.provider { "keyProviderPutValue" })
  mapProperty.putAll(mapOf("keyPutAll" to "keyPutAllValue"))
  mapProperty.putAll(project.provider { mapOf("keyProviderPutAll" to "keyProviderPutAllValue") })
  mapProperty.put("absoluteFileGetsRelativized", project.file("some/relative/file").absoluteFile)
  mapProperty.put("absoluteFileGetsRelativizedProvider", project.provider { project.file("some/relative/file/provider").absoluteFile })

  val regularFile: RegularFile = project.layout.projectDirectory.file("regularFile")
  val directory: Directory = project.layout.projectDirectory.dir("directory")
  val regularFileProvider: Provider<RegularFile> = project.layout.buildDirectory.file("regularFileProvider")
  val directoryProvider: Provider<Directory> = project.layout.buildDirectory.dir("directoryProvider")
  mapProperty.put("regularFile", regularFile)
  mapProperty.put("directory", directory)
  mapProperty.put("regularFileProvider", regularFileProvider)
  mapProperty.put("directoryProvider", directoryProvider)
  mapProperty.put("anyProvider", project.provider { Any() })
}
```

(Picture for line numbers)

![Compiler errors and line numbers show in IntelliJ](https://user-images.githubusercontent.com/1447148/52720102-a2741200-2f6c-11e9-9a61-e72997bce472.png)

Compiler errors:

```
e: /home/mkobit/Workspace/code-lab/gradle-lab/src/main/kotlin/deleteme.kt: (8, 15): Overload resolution ambiguity:
public abstract fun put(p0: String, p1: Any): Unit defined in org.gradle.api.provider.MapProperty
public abstract fun put(p0: String, p1: Provider<out Any!>): Unit defined in org.gradle.api.provider.MapProperty
e: /home/mkobit/Workspace/code-lab/gradle-lab/src/main/kotlin/deleteme.kt: (12, 15): Overload resolution ambiguity:
public abstract fun put(p0: String, p1: Any): Unit defined in org.gradle.api.provider.MapProperty
public abstract fun put(p0: String, p1: Provider<out Any!>): Unit defined in org.gradle.api.provider.MapProperty
e: /home/mkobit/Workspace/code-lab/gradle-lab/src/main/kotlin/deleteme.kt: (20, 15): Overload resolution ambiguity:
public abstract fun put(p0: String, p1: Any): Unit defined in org.gradle.api.provider.MapProperty
public abstract fun put(p0: String, p1: Provider<out Any!>): Unit defined in org.gradle.api.provider.MapProperty
e: /home/mkobit/Workspace/code-lab/gradle-lab/src/main/kotlin/deleteme.kt: (21, 15): Overload resolution ambiguity:
public abstract fun put(p0: String, p1: Any): Unit defined in org.gradle.api.provider.MapProperty
public abstract fun put(p0: String, p1: Provider<out Any!>): Unit defined in org.gradle.api.provider.MapProperty
e: /home/mkobit/Workspace/code-lab/gradle-lab/src/main/kotlin/deleteme.kt: (22, 15): Overload resolution ambiguity:
public abstract fun put(p0: String, p1: Any): Unit defined in org.gradle.api.provider.MapProperty
public abstract fun put(p0: String, p1: Provider<out Any!>): Unit defined in org.gradle.api.provider.MapProperty
```

The workaround is to use one of the `putAll` methods instead.

### Context

See summary at top of issue.

### Your Environment

 * Build scan URL:

**Comment by adammurdoch** [comment]
I think for this pattern (I have a configurable map of file system locations, some of which may be calculated) we should aim for the type parameters to describe what the property represents (what it produces) rather than what the property uses as input. That is, the property should be a `MapProperty<String, RegularFile>` or `MapProperty<String, File>` or whatever, rather than `MapProperty<String, Any>`. So, we might add some extension methods or a specialized subtype that adds methods to allow clients to directly add entries to the map using values of any type that can later be resolved to a file location.

**Comment by mkobit** [comment]
Sorry, @adammurdoch , I don't think I was clear enough in my description. My hope when using `MapProperty<String, Any>` is to support `File`, `RegularFile`, `Directory`, and also any other type like `String`, `Int`, etc. Then, at runtime those inputs get converted into CLI arguments that we pass to the tool.

In this example case, we are explicitly wrapping the `docker image build` CLI command and the `MapProperty` is being used for the `--build-arg` option.

**Comment by tkrullmann** [comment]
I've been working around this problem by defining a custom extension function on `MapProperty` with a different name:

```kotlin
fun <K : Any, V : Any> MapProperty<K, V>.putFrom(
        key: K, providerOfValue: Provider<out V>
) = put(key, providerOfValue)
```

Java has a strict set of rules for overload resolution (with `Object` always losing vs a more specific type, like `Provider<? extends Object>` in this instance), but the Kotlin compiler will just give up when facing any ambiguity. Probably the creators of Kotlin thought this would be a good thing, to help avoid any bugs, but it has been a frequent source of incompatibility with existing Java libraries :-(

It would probably a good idea to add this `putFrom` method to Gradle for better Kotlin support.

**Comment by krystian-panek-wttech** [comment]
still valid and workaround as mentioned here https://github.com/gradle/gradle/issues/8500#issuecomment-640561873 is required
