### ISSUE TITLE
Gradle does not reuse Workers with functionally equivalent classpaths

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#8504]
When starting a worker, we copy worker jars into a cache to prevent other processes from overwriting them while it's running.  The path to the cache for these jars are based on the byte-for-byte hash of the jar file.  Two jar files that differ only by the timestamps in the jar are treated as different files and put into separate cache locations. This makes the classpath for the worker appear different, even though they are functionally equivalent.

### Expected Behavior

Gradle workers should be reusable if the classpath has not really changed (similar to the way `@Classpath` is handled for tasks).

### Current Behavior

Gradle workers are considered reusable only when the _absolute paths_ to the classpath are the same.

(Technically, we check if the running worker's classpath is a _superset_ of the requested classpath, but it's still based on file path).

### Context

I noticed that a build was accumulating many workers when buildSrc was rebuilt without any changes.

### Steps to Reproduce (for bugs)

This can be reproduced on the gradle/gradle build by building buildSrc, running compileAll, cleaning buildSrc and running compileAll again.  Even though buildSrc didn't change, new workers will be started.

**Comment by adammurdoch** [comment]
Good idea. This will also be helpful for other things that use the jar cache, eg the buildSrc classloader, script compilation, etc.

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.
