### ISSUE TITLE
Publication of large files to artifactory is very slow in Gradle.

### ISSUE THREAD

**Issue by IronLung7** [gradle/gradle#8508]
Publication of large files to remote cache is very slow in Gradle.
We have two files (3.8GB, 4.6GB) defined in @output.
In our build, we also have logic to calculate checksum (md5 and sha1) and to publish the artifacts to Artifactory (implemented with bash calling curl).
 
It costs about 15 mins to publish these two files to the remote cache, 10 mins to calculate md5 and sha1 for these two files, and 5 minutes to upload them to Artifactory.

### Expected Behavior
Pushing to remote cache should be fast.

### Current Behavior
Pushing to remote cache cost a lot of time. And we don't have any options to optimize the remote cache pushing performance.

### Context
This makes our CI build took longer than building without Gradle

**Comment by lptr** [comment]
It's unclear to me if this is about publishing to a something like a Maven repo in Artifactory, or you are trying to store the output of a task in the remote build cache (which you've implemented Artifactory).

In either case we'd need more information about what your expectation is. It seems there's a pre-Gradle build that handled this in some form, so I'm guessing it is the Maven publication use case. What were the timings you saw with that implementation?

**Comment by IronLung7** [comment]
@lptr Pushing to remote cache costs 15 mins, and publishing files using curl command costs 5 mins.  What I want to say is that the publishing to remote cache is very slow.
