### ISSUE TITLE
Improve Gradle error messaging when incorrectly referencing variables in an outer scope in build scripts

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#8521]
### Expected Behavior
Given [this faulty custom task declaration](https://github.com/gradle/build-analysis-demo/blob/ew/custom-inline-task/build-event-indexerator/build.gradle.kts#L22-L52) in Kotlin, Gradle error messaging should have been clearer what the actual problem is.

### Current Behavior
The above code snippet has a bunch of problems, but Gradle had a confusing error message:

```
Could not create task ':build-event-indexerator:indexTaskEvents'.
> Could not create task of type 'DataflowExec'.
  > The constructor for class Build_gradle$DataflowExec should be annotated with @Inject.
```

### Context
Related to https://github.com/gradle/gradle/issues/7644

This came up as I was trying to create a custom task inside `<root_project>/build.gradle.kts`. 

I expect this is rarely encountered due to how horribly I'd messed up the class declaration, but it was really confusing at the time.

### Steps to Reproduce (for bugs)

 1) Define a crazy inline custom task class like [this one](https://github.com/gradle/build-analysis-demo/blob/ew/custom-inline-task/build-event-indexerator/build.gradle.kts#L22-L52).
 2) Execute any Gradle task such as `help`

### Your Environment

 * Build scan URL: https://e.grdev.net/s/7fchmwrm7ascy

**Comment by SUPERCILEX** [comment]
This would be really nice (spent like 30 mins digging through source code and google to get here).

**Comment by cbpr** [comment]
I'm running in the same issue when I `exec {}` inside an `open class Foo: DefaultTask() {...}` in a buildSrc kts file.
I have no idea yet, how I could provide such a call-exec-functionality centrally in buildSrc. I do not want to inherit `Exec` task, but call it from a DefaultTask and care about the resulting command line output.
