### ISSUE TITLE
Gradle Docs 5.2.1 doesn't explain "virtual platforms"

### ISSUE THREAD

**Issue by merhalak** [gradle/gradle#8527]
Gradle Docs (5.2.1) contains dead link to subsection "Virtual platforms" in section "Dependency Management Terminology" subsection "Platform".

### Context

[Reference to Dependency Management Terminology -> Platform](https://docs.gradle.org/current/userguide/dependency_management_terminology.html#sub::terminology_platform)

**Comment by melix** [comment]
Indeed the link is broken. Should link to https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:virtual_platform
