### ISSUE TITLE
Creating multiple Checkstyle tasks overwrite each others configProperties

### ISSUE THREAD

**Issue by WonderCsabo** [gradle/gradle#8532]
### Expected Behavior
When we create multiple Checkstyle tasks in a project, we expect all the properties of those task to be set for each task individually, and not in a global fashion.

### Current Behavior
It seems the `configProperties` are somehow overwriting each other. In the example project, we define the `checkstyleCacheFile` config property, which is different for the two Checkstyle tasks. However when running the first task, the second task's property is used, because we can observe the cache file created is using the name from the last (second) task.

### Context
The real context is creating separate Checkstyle tasks for Android variants, which would use separate output files, as for reports and for cache files. Reports work well, but it seems the config properties overwrite each other, and only the last task's property is used for all tasks. This can be reproduced in a simple Java project.

### Steps to Reproduce (for bugs)
Clone https://github.com/WonderCsabo/checkstylegradleparallelbug
Run ` ./gradlew clean checkstyleFirst`
Observe that `build/cacheFileSecond` is created, however `build/cacheFileFirst` config property was defined for the `checkstyleFirst` task.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/vvnrk77mb5dmm

**Comment by natgaertner** [comment]
This seems to be an issue with the conventional values that are provided to the task for parameters like configProperties. Specifically, if the value fetched from the task is null-ish, the hard-coded conventional value is used. This includes being empty for Collection and Map types: https://github.com/gradle/gradle/blob/master/subprojects/model-core/src/main/java/org/gradle/internal/extensibility/ConventionAwareHelper.java#L100

But of course the value that a Checkstyle task has if you haven't set it yet is an empty map:
https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java#L62

When you create entries in configProperties by specifying keys as in the steps to reproduce:
```
configProperties.key = value
```
there's an implicit getConfigProperties call that winds up resolving back to the "conventional" value. That value remains the same object even as its entries are added to by both the checkstyle tasks defined in the build file. Thus the second checkstyle task overwrites the entry set in the first one.

If you explicity set configProperties to be a map independently in each task, like so:
```
configProperties = [key: value]
```
this issue does not occur.
Demonstrated here: https://github.com/natgaertner/checkstylegradleparallelbug

I'm not sure what the best fix would be. Some kind of copy on write would be the most sophisticated thing I could imagine, but I'm at a loss about how that would happen neatly.
