### ISSUE TITLE
Parallel configuration phase

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#8538]
### Expected Behavior
Do some of the "configuring build" part in parallel. For example almost sure compiling the Gradle files for each separate module doesn't have cross-dependencies. The fact that I can read "compiling :foo" means that it's slow enough to get a win from parallelization. Resolving configuration dependencies are also a good candidate.

Other parts could also be parallelized, I guess, but that may be a much harder problem.

### Current Behavior
Configuration phase looks very serial on a single thread.

### Context
I have a ton of cores in the my PC, but it's buzzing on a single thread to compile the Gradle files. Even on a dual-core machine this would cut the time in "half". Anything is a win that changes
```
<============-> 97% CONFIGURING [1m 12s]
> IDLE
> IDLE
> IDLE
> project > :foo
> IDLE
> IDLE
> IDLE
> IDLE
```
to do some things in parallel.

### Steps to Reproduce (for bugs)
Project with lot of subprojects each having a `build.gradle` file.

### Your Environment
any; local, CI

**Comment by d1ss0nanz** [comment]
It's common to have subprojects that depend on each other via the `project(':subprojectA')` annotation.
This should still work.

**Comment by ZakTaccardi** [comment]
Some good reading on this issue

https://artemzin.com/blog/fundamental-design-issues-of-gradle-build-system/#designissueconfigurationisserial

**Comment by PaulWoitaschek** [comment]
Can we unstale this? It's a really good idea and would really speed things up on multi module projects.

**Comment by TWiStErRob** [comment]
Ah, I think this will as closed during the great purge. Odd that there was nor reply from maintainers.

**Comment by Tapchicoma** [comment]
I think [project-isolation](https://gradle.github.io/configuration-cache/#project_isolation) goes into this direction

**Comment by adammurdoch** [comment]
It does indeed. Parallel configuration and build script compilation are likely to be one of the performance improvements that project isolation will enabled.

**Comment by NikolayMetchev** [comment]
Is project isolation different to gradle configuration cache? If I enable project isolation will it compile in parallel?

**Comment by bamboo** [comment]
FTR, from a recent discussion: Task graph building can be smarter when the task selector is constrained (e.g. absolute), this is good because IDEs already invoke Gradle with absolute task paths. In that case, a parallel / on-demand configuration strategy can be employed: configure projects "backwards" through the task graph by following task dependencies (starting from the absolute paths given).

**Comment by LouisCAD** [comment]
Is compiling in parallel under consideration for an upcoming Gradle version?

Computers keep having more cores, it'd be really good to have the state of the art build system to leverage those for what is currently quite a drag when a project needs its build scripts compiled and we are all waiting for it.

**Comment by bamboo** [comment]
> Is compiling in parallel under consideration for an upcoming Gradle version?

Yes. The current thinking is that parallel script compilation will be a natural byproduct of parallel configuration and that's where we're focusing our efforts.

**Comment by NikolayMetchev** [comment]
> > Is compiling in parallel under consideration for an upcoming Gradle version?
> 
> Yes. The current thinking is that parallel script compilation will be a natural byproduct of parallel configuration and that's where we're focusing our efforts.

That would be fantastic. Are there any timelines as to when that would be available?

**Comment by franckrasolo** [comment]
For anyone still willing to read the blog post titled **"Fundamental Design Issues of Gradle Build System"** suggested by @ZakTaccardi over 4 years ago, it can now be found at the [Internet Archive](https://web.archive.org/web/20220824194513/https://artemzin.com/blog/fundamental-design-issues-of-gradle-build-system/).

**Comment by rsicarelli** [comment]
Any update on this issue?

**Comment by alllex** [comment]
Sorry for the late reply

This will be addressed as a part of the overall Isolated Projects initiative:
* https://github.com/gradle/build-tool-roadmap/issues/76

We will close this issue in favor of the roadmap item
