### ISSUE TITLE
Write structured error output details at the end of the log stream

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#8543]
Currently Gradle users have to hunt for the following important pieces of information in the log stream when there is a failure:

 * What task failed
 * The causal error message(s)
 * Where the test/error reports are
 * The command that was run

(Honestly this is sometimes so long that some of this is lost out of the CLI buffer.)

### Expected Behavior
A structured error report at the end of build, even if a limited one, would be a huge experience improvement. Here are some examples:

#### Test failure
```
Errors (1)

> Task :foo:integTest [org.gradle.api.tasks.Test] FAILED
Description: There were failing tests.
Report:      file:///Users/you/src/yourproject/build/reports/integTest/index.html
Command:     ./gradlew :foo:integTest
Build Scan:  https://scans.gradle.com/s/somekey
```

Here's what is better than the current behavior:

 * This is much more easily parseable by humans and computers
 * It is grouped at the end, so that `--continue` doesn't make the output very scattered
 * It contains the command to re-run. This is optional, but would be cool
 * It contains the type of task that failed
 * The build scan URL is included as a peer to the test report, as it should be. 

### Current Behavior
As of Gradle 5.2, we write:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/eric/src/eriwen/gradle-digest-plugin/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
13 actionable tasks: 1 executed, 12 up-to-date

Publishing build scan...
https://scans.gradle.com/s/occff3ygnj5bs
```

### Context
I consider this my greatest failure so far in Gradle user experience. This is an issue that affects everyone who uses the build tool, including possibly those that use IDEs. This is because IDEs don't yet surface build failure details like this in their UI. Perhaps a structured log output would be helpful. Regardless, doing this for CLI and continuous integration is enough. 

This could be implemented within the logging chain or perhaps as something that subscribes log events more on the outside and maps certain messages to each failure.

**Comment by cesar1000** [comment]
Thanks, Eric!

Ideally, I'd like to see Gradle formalize errors in the API, collecting an `Error` from each failed task - delegating to the tasks to describe their own errors, and falling back to a default error definition. For example, the unit test or checkstyle tasks would register their own instances of `Error`, describing each failed test or checkstyle violation, and including links to the relevant reports.

It would be ideal if, as part of this effort, Gradle made it easier to inspect the task output (either standard or error) to collect extra information about the error, as described in https://github.com/gradle/gradle/issues/6068.

Build scans could use the information collected through errors to offer the extra detail about build failures, instead of just presenting a callstack and error output (and requiring several clicks). On the client side, error handling can be delegated to plugins, which may dump a description of the errors to the console (as described above), or present to the user through other means (like sending to a CR system, which we've been doing for a few months to remove the need for users to interact with Jenkins entirely).

**Comment by alekseyp555** [comment]
In the summary gradle report *Where title missed why? Only this. How configure this output ?
gradlew test -Ptarget=local cleanTest test 1>all.log 2>error.log
2 tests completed, 2 failed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':testSpravochniki'.
> There were failing tests. See the report at: 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 47s

**Comment by Nirvanchik** [comment]
In our project we have "merge" branches where we are merging diverging code of different creators and we get a lot of errors in those branches. **And we apply computer processing of compilation errors**: parse them, find broken code lines, blame the owners of that code, get urls to the source code with those lines, put all this information into nice html with a table which is sortable and filterable (by owner, by error type, etc.).
Also, we use `--continue` flag to get as much as possible errors at once (and our project enables org.gradle.parallel flag).

Currently, Gradle is not very friendly to our use case.

Gradle allows to get tasks list that have failed (using org.gradle.api.execution.TaskExecutionListener), and exception stack trace of Gradle itself (using org.gradle.BuildAdapter) which is nice but not enouph for our happyness.

We need Gradle to give us error output of every failed task separately (using task.logging.addStandardErrorListener does not work : https://github.com/gradle/gradle/issues/6068) or may be some kind of api that @cesar1000 proposed or may be some json report where we could read it. It is not comfortable to parse stderr with all of those different failed tasks output with either many parsers either one dreadful parser.

**Comment by ov7a** [comment]
For follow-up on this issue, see
* https://github.com/gradle/build-tool-roadmap/issues/120

in out public roadmap.

Since it's a quite old issue and has a broad scope, keeping it closed. Please open specific issues for related bugs/feature requests (there are already some).
