### ISSUE TITLE
Checkstyle classpath is set incorrectly for multi-project builds

### ISSUE THREAD

**Issue by punya** [gradle/gradle#855]
### Expected Behavior
If project A depends on project B, then the javadoc for a function defined in A should be able to reference an exception defined in B.

### Current Behavior
* If a function's javadoc has more than one `@throws` tag, one of which references an exception in a different project, then the Gradle Checkstyle task shows an error:
```
[ant:checkstyle] [ERROR] .../checkstyle-bug/client/src/main/java/csbug/BarInterface.java:10:22: Unable to get class information for @throws tag 'FooException'. [JavadocMethod]
```
* This doesn't happen if there's only a single `@throws` tag
* This only happens for Checkstyle newer than 6.11.2 (including the most recent release 7.2)
* This happens for Gradle 2.12 - 3.1
* This can be fixed by manually adding dependencies to the Checkstyle classpath:
```
tasks.checkstyleMain.classpath += configurations.compileClasspath
```

### Context
It's reasonable to have a project that contains API classes (interfaces, data formats, exception types) and dependent projects that reference API classes. Functions that throw (and document) multiple exception types are common as well.

### Steps to Reproduce (for bugs)
https://github.com/punya/checkstyle-bug minimally demonstrates the problem. [Uncomment these two lines](https://github.com/punya/checkstyle-bug/blob/bf22270d/build.gradle#L23-L24) to fix the problem manually.

### Your Environment
 * Build scan URL: https://scans.gradle.com/s/umlviaz4noymq

**Comment by eriwen** [comment]
@punya Thank you for the excellent bug report.

**Comment by punya** [comment]
@eriwen I'm thinking of submitting a PR to fix this, which amounts to

```diff
-        task.setClasspath(sourceSet.getOutput());
+        task.setClasspath(sourceSet.getOutput().plus(sourceSet.getCompileClasspath()));
```

in CheckstylePlugin.java. Before diving in to write integration tests, etc, I wanted to check if further discussion (on the mailing list) or a design doc would be necessary for this change.

**Comment by eriwen** [comment]
@punya Thanks for asking. I don't think that a design doc is necessary given the scope of this bug. If we have sufficient test coverage, I'm 100% good with that.

**Comment by eriwen** [comment]
Moving to Ready To Deliver with changes in #863
