### ISSUE TITLE
java-platform plugin breaks when mixed with other plugins

### ISSUE THREAD

**Issue by nicholas-s-perkins** [gradle/gradle#8553]
### Behavior
I've been attempting to publish a BOM using the java-platform plugin, but I'm noticing some strange behavior that is not documented as far as I can tell, so perhaps it's a bug?

In order to produce a BOM that imports another BOM, I have to additionally include the java plugin as far as I can tell, like so:
```groovy
plugins {
    id 'java-platform'
    id 'java'
}

repositories {
    mavenCentral()
}

javaPlatform {
    allowDependencies()
}

dependencies {
    api(platform("com.amazonaws:aws-java-sdk-bom:1.11.498"))
    constraints {
        api group: "org.glassfish.corba", name: "glassfish-corba-orb", version: "4.2.0"
    }
}
```
This seems to work, however, switching the order of the plugin import to this:
```groovy
plugins {
    id 'java'
    id 'java-platform'
}
```
Causes any task to break with this error:
```
An exception occurred applying plugin request [id: 'org.gradle.java-platform']
> Failed to apply plugin [id 'org.gradle.java-platform']
   > Cannot add a configuration with name 'apiElements' as a configuration with that name already exists.

```
This seems unexpected?

Additionally, adding the kotlin plugin causes everything to stop working all together, no matter the order:
```
plugins {
    id 'java-platform'
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.3.21'
}
```
with this error:

```
An exception occurred applying plugin request [id: 'java-platform']
> Failed to apply plugin [id 'org.gradle.java-platform']
   > Cannot add a configuration with name 'api' as a configuration with that name already exists.
```

### Your Environment
gradle wrapper 5.2.1, macOS 10.14.3

**Comment by melix** [comment]
You should not apply the `java` plugin in addition to the `java-platform` plugin. A platform should be in its own project. Out of curiosity: why did you _also_ apply the `java` plugin?

**Comment by nicholas-s-perkins** [comment]
@melix So is `java-platform` intended to not be mixed with other plugins?

Now that you question it and that I've tinkered with it a bit more, it does seem like I was maybe doing something strange in the first place, and in trying to convert what I've previously done it turned out to be surprising that it worked in the first place?
 
So I had been organically converting an older style project into one that that used java-platform and newer conventions.   This project was for the purpose of publishing a jar and a BOM.  I included things like kotlin/java plugins because (perhaps not in a good style) I personally found it useful to organize all of the dependency and plugins in the root project build.gradle.

so the project looks something like
```
/project/
    build.gradle
        /my-bom/
            build.gradle
        /my-jar/
            build.gradle
```

And here's a simplified middle version of the main build.gradle that appears to function:

```groovy
buildscript {
    ext{
        kotlin_version = "1.3.21"
    }
    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlin_version}"
    }
}

allprojects{
    apply plugin: 'java-platform'
    apply plugin: 'java-library'
    apply plugin: 'kotlin'

    group = 'com.foo'
    version = '1.0.0'

    javaPlatform {
        allowDependencies()
    }

    repositories {
        mavenCentral()
    }
}

project(":my-bom"){
    dependencies {
        api platform(group: 'com.amazonaws', name: 'aws-java-sdk-bom', version: '1.11.498')

        constraints {
            api group: "${group}", name: 'my-jar', version: "${version}"
            api group: 'org.glassfish.corba', name: 'glassfish-corba-orb', version: '4.2.0'
            api group: "org.jetbrains.kotlin", name: 'kotlin-stdlib-jdk8', version: "$kotlin_version"
        }
    }
}

project(":my-jar"){
    dependencies{
        implementation platform(project(':my-bom'))
        api group: "org.jetbrains.kotlin", name: 'kotlin-stdlib-jdk8'
        api group: 'com.amazonaws', name: 'aws-java-sdk-core'
    }
}
```
In trying to use the newer style `plugins` block, it went from functioning to breaking because somehow in the old style way of applying plugins it functioned.  
I can restructure it, but I felt I would at least inquire to see if that was intended behavior since I somehow got it to work using different conventions.

**Comment by melix** [comment]
> @melix So is `java-platform` intended to not be mixed with other plugins?

It doesn't make sense to "mix in" Java platform with other plugins. When you apply the plugin, you are saying "this project is a Java platform". Similarly if you apply the `java-library` plugin, you are saying "this project is a Java library". A project _cannot_ be both a platform and a library at the same time: it doesn't make sense. Think of plugins as "what am I building here". So **only** your "BOM" project should be applying the `java-platform` plugin. The libraries should **only** apply the `java-library` plugin.

**Comment by ljacomet** [comment]
Since applying the `java-platform` plugin after `java` or `java-library` already throws, we will just improve the error message in that case.
In order to not break existing builds, applying `java` or `java-library` after `java-platform` will cause a deprecation warning in 5.3+ and will break in 6+
