### ISSUE TITLE
PluginAwareExtensions.kt does not contain a extension functions for applying a plugin class

### ISSUE THREAD

**Issue by MatFl** [gradle/gradle#8557]
This problem occurred when I stumbled upon #1262 while migrating groovy scripts to kotlin DSL.

The workaround from #1262 is to apply the plugin class directly.
(`apply plugin: org.owasp.dependencycheck.gradle.DependencyCheckPlugin`)

However the apply function from PluginAwareExtensions only allows Strings.

There should be a extension function like this:
```
fun PluginAware.apply(pluginClass: Class<out Plugin<*>>) {
    apply {
        plugin(pluginClass)
    }
}
```

so when using kotlin DSL one can use:
`apply(pluginClass = org.owasp.dependencycheck.gradle.DependencyCheckPlugin::class.java)`

**Comment by eskatos** [comment]
What about the following?
```kotlin
import org.owasp.dependencycheck.gradle.DependencyCheckPlugin

apply<DependencyCheckPlugin>()
```

**Comment by MatFl** [comment]
Yes, this also works. I didn't know how to interpret the syntax of the method. Kotlin is still quite new to me :)
