### ISSUE TITLE
ExtractSymbols task does not work on windows.

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#8562]
The ExtractSymbols task does not work on windows. Nowhere on the documentation is this said, I only found this out by checking the unit tests.

On windows, support for dumpbin would need to be added, and then the command to call would be `/NOLOGO /EXPORTS /OUT:outfilehere infile`

There is also a typo `extracter` instead of `extractor` in the error message.

Scan is https://scans.gradle.com/s/2vnh7esmthvky

### Expected Behavior
ExtractSymbols should give me the dumbpin output of symbols for windows binaries.

### Current Behavior
ExtractSymbols fails with an error stating the symbol extractor is not available.

### Context
I need this to build a task that checks the built shared libraries for specific symbols (Mainly some JNI symbols for a JNI plugin).

**Comment by ThadHouse** [comment]
I actually just realized ExtractSymbols doesn't do what I was thinking. I was thinking it would extract all the symbols and write them to a text file. I didn't realize it just extracted the actual debug symbols to another file to be missed with stripping. Sorry, closing.

**Comment by lacasseio** [comment]
Thanks for the typo, I fixed it here: https://github.com/gradle/gradle/commit/f305a27fdff1737ffc996209f71b4c7f55d7358b
