### ISSUE TITLE
Gradle 5.X won't resolve deps with underscores in package name

### ISSUE THREAD

**Issue by lxdraw** [gradle/gradle#8576]
### Expected Behavior
When a dependency has a class in a package with an underscore in its name Gradle should resolve the class successfully

### Current Behavior
When package names contain underscores I get the following error and the build fails:
```e: /Users/x/IdeaProjects/scratch/src/test/kotlin/com/company/scratch/ScratchApplicationTests.kt: (3, 12): Unresolved reference: nhaarman
e: /Users/x/IdeaProjects/scratch/src/test/kotlin/com/company/scratch/ScratchApplicationTests.kt: (4, 12): Unresolved reference: nhaarman
e: /Users/x/IdeaProjects/scratch/src/test/kotlin/com/company/scratch/ScratchApplicationTests.kt: (5, 12): Unresolved reference: junit
e: /Users/x/IdeaProjects/scratch/src/test/kotlin/com/company/scratch/ScratchApplicationTests.kt: (8, 36): Unresolved reference: mock
e: /Users/x/IdeaProjects/scratch/src/test/kotlin/com/company/scratch/ScratchApplicationTests.kt: (11, 6): Unresolved reference: Test
e: /Users/x/IdeaProjects/scratch/src/test/kotlin/com/company/scratch/ScratchApplicationTests.kt: (14, 9): Unresolved reference: verify
> Task :compileTestKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 39s
5 actionable tasks: 4 executed, 1 up-to-date
```

### Context
I am using [Kluent](https://markusamshove.github.io/Kluent/) for assertions and mocking in my unit tests for a Kotlin app. The mocking portions are shadowed under the `com.nhaarman.mockito_kotlin` package. On Gradle versions 5.X when the `com.nhaarman.mockito_kotlin` package is imported in a class the task `compileTestKotlin` fails. Pull in the same class from a package without an underscore, e.g. `org.mockito.Mockito`, and Gradle runs the tests successfully.

### Steps to Reproduce (for bugs)
[scratch.zip](https://github.com/gradle/gradle/files/2890432/scratch.zip)

### Your Environment
Reproduced on macOS High Sierra, macOS Mojave, Windows 10.

**Comment by melix** [comment]
This error is from the Kotlin compiler. What makes you think Gradle 5 is responsible here? Does it work _without_ Gradle?

**Comment by lxdraw** [comment]
Tried compiling the test with `kotlinc` and it seems to be having the same trouble that Gradle 5 is having. I don't understand why Gradle 4 works but Gradle 5 does, but I agree this likely a problem with the Kotlin compiler. I am going to close this.
