### ISSUE TITLE
Use M2_REPO instead of absolute paths in eclipse .classpath

### ISSUE THREAD

**Issue by kno10** [gradle/gradle#858]
The eclipse plugin generates `.classpath` with absolute path names.

The folliowing setting will instead use the `M2_REPO` variable:
```
eclipse.pathVariables 'M2_REPO': new File(repositories.MavenLocal.url)
```
This produces more portable class paths for eclipse.

**Comment by eriwen** [comment]
@kno10 Can you please give some context about why "more portable classpaths for Eclipse" are impactful? In general, I can't prioritize a change unless we know why we should make it instead of all of the other work we have. It would greatly improve the chances of prioritization and time-to-fix if you provided a small reproducible example which demonstrates the impact of this bug. Thanks.

**Comment by kno10** [comment]
It may make it easier to share projects if the classpath does not depend on the user setup. Right now, the path names would usually look like `/home/username/.m2/repository/org/gradle/.../.jar`; with that change they will be simply `M2_REPO/org/gradle/.../.jar`, and eclipse knows how to expand `M2_REPO`.
The Eclipse Maven integration m2e uses this to set up classpaths, so it would be more consistent.

While many people hate checking in settings files into version control, others do like it. Sometimes there could be decent reasons to do so, maybe for portability from one computer, operating system, or one user to another. It would also allow you to move your `.m2` folder, and - assuming eclipse picked up this change - this will not require reconfiguration.

Of course the idea of the eclipse plugin is to not have to check in such files, but rather generated them with gradle. But as `pathVariables` exists already for exactly this purpose, we may as well use it.

**Comment by oehme** [comment]
I'd recommend using [Eclipse Buildship](https://github.com/eclipse/buildship), which puts dependencies in a classpath container, thus making the .classpath file portable.

We can't just use a path variable, as those need to be actively defined in the IDE by the user. If we switched Gradle to inserting path variables by default, then `gradle eclipse` would be broken for pretty much everyone.
