### ISSUE TITLE
Modifying a dependency in eachDependency() disables improved pom support

### ISSUE THREAD

**Issue by sonicsnes** [gradle/gradle#8586]
IMPROVED_POM_SUPPORT, which should be active for everyone now on gradle 5, is actually deactivated if a dependency is modified within eachDependency.

### Expected Behavior
Improved pom support should always be active for maven poms.

### Current Behavior
Improved pom support is disabled if a dependency is modified with eachDependency, even simply via .because(). Legacy maven configuration selection is used instead.

### Context
I noticed this because some of our maven poms were pulling in `default` of their dependencies, while (seemingly randomly), others were pulling in `runtime`.

This is because `alwaysUseAttributeMatching()` is always called for maven modules in https://github.com/gradle/gradle/blob/5e65884e365e643c270f98a606bd36f744dbab82/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/maven/RealisedMavenModuleResolveMetadata.java#L148, but then that flag is lost when the metadata is cloned on https://github.com/gradle/gradle/blob/6be5f69a972a128cdc1a5ebc45765223590530b2/subprojects/dependency-management/src/main/java/org/gradle/internal/component/external/model/ConfigurationBoundExternalDependencyMetadata.java#L137 (and the two methods following)

### Your Environment
Gradle 5.2.1

**Comment by ljacomet** [comment]
Thanks for the report and taking time to pinpoint the bug.
