### ISSUE TITLE
Two subprojects cannot use two extensions with the same name but different class

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#8592]
### Expected Behavior
When:
* Subproject `projA` loads extension of class `ExtA` with name `myExt` (as provided by plugin of class `PluginA`).
* Subproject `projB` loads extension of class `ExtB` with name `myExt` (as provided by plugin of class `PluginB`).

Then:
* I expect that both subprojects will work just fine.

### Current Behavior
```
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':projB'.
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'pluginB']
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'ExtA_Decorated@657cef10' with class 'ExtA_Decorated' to class 'ExtB'
```

### Context
I've got two Gradle plugins that work similarly so they share base classes (this also applies to the extensions). They are used in a Gradle project that builds multiple apps. To simplify their configuration, I decided to use the same extension name for both subprojects. Sadly, the extensions seem to be loaded in a common registry that doesn't scope the extensions on subproject level, so they conflict.

### Steps to Reproduce (for bugs)
You should have all info already.

### Your Environment
```
------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------

Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Linux 3.10.0-957.1.3.el7.x86_64 amd64
```

**Comment by big-guy** [comment]
Could you provide an example?  I don't see this behavior.  I suspect you have either applied both `pluginA` and `pluginB` to projB or `pluginB` is reaching into projA and looking for the extension by name. 

I tried:
```
class ExtA {}
class ExtB {}

project(":a") {
   extensions.create("myExt", ExtA)
}

project(":b") {
   extensions.create("myExt", ExtB)
}

subprojects {
	println "extension is " + extensions.myExt
}
```

And this prints out different types for the same extension name.

**Comment by rkrisztian** [comment]
Sorry, assumed that reproducibility was easier. I will work on that example you requested.

**Comment by rkrisztian** [comment]
Re-reported as #8608.
