### ISSUE TITLE
Two subprojects cannot use two extensions with the same name but different class

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#8608]
When using the Gradle Daemon, project extensions sharing a base class applied into the same Gradle project break the root project with a class cast exception.

### Expected Behavior
When:

* Gradle Daemon is enabled.
* `ExtensionA` and `ExtensionB` both extend `ExtensionBase`.
* Subproject `projectA` loads extension of class `ExtensionA` with name `extensionBase` (as provided by plugin of class `PluginA`).
* Subproject `projectB` loads extension of class `ExtensionB` with name `extensionBase` (as provided by plugin of class `PluginB`).

Then:

* Command `gw tasks && gw tasks` on root level should return the task list twice.

### Current Behavior
```none
A problem occurred evaluating project ':projectA'.
> Failed to apply plugin [class 'PluginA']
   > Cannot cast object 'ExtensionB_Decorated@7eb9d6e6' with class 'ExtensionB_Decorated' to class 'ExtensionA'
```

### Context
I've got two Gradle plugins that work similarly so they share base classes (this also applies to the extensions). They are used in a Gradle project that builds multiple apps. To simplify their configuration, I decided to use the same extension name for both subprojects. Sadly, the extensions seem to be loaded in a common registry that doesn't scope the extensions on subproject level, so they conflict.

### Steps to Reproduce (for bugs)
See attached example project:
[test.zip](https://github.com/gradle/gradle/files/2900146/test.zip)

### Your Environment
```
------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 3.10.0-957.1.3.el7.x86_64 amd64
```

PS.: Originally reported the problem in #8592, but it was closed due to not enough reproducibility information.

**Comment by rkrisztian** [comment]
It seems to me that the problem is caused by some kind of caching of static non-final field `extensionTypeClass`. If I don't use it, the problem disappears.

**Comment by big-guy** [comment]
I don't think there's any reason for `extensionTypeClass` to be static.  What you're seeing is how static variables work.  Here's a [similar example outside of Gradle](https://stackoverflow.com/questions/9898097/what-are-the-rules-dictating-the-inheritance-of-static-variables-in-java) that shows the same behavior.

**Comment by rkrisztian** [comment]
Right, I should have known that, thanks.
