### ISSUE TITLE
Pre-compiled scripts are discovered in a specified location without buildSrc

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#8615]
This allows pre-compiled scripts to be located anywhere in the project.  Pre-compiled scripts would be enabled through a Settings plugin.  This plugin would:

- Provide an extension for defining the pre-compiled script location
- Create an included build for the script plugins
- Apply the pre-compiled script Project plugin to the included build project
- Add the pre-compiled script location to the GradlePluginDevelopmentExtension.pluginSourceSet in the included build project

This should be able to also enable pre-compiled kotlin script plugins, too.

**Comment by oehme** [comment]
I'm curious, why do we want to support a different location than buildSrc?
