### ISSUE TITLE
Gradle download certificate broken

### ISSUE THREAD

**Issue by guenhter** [gradle/gradle#8623]
### Expected Behavior
Gradle can be downloaded

### Current Behavior
Certificate error when downloading gradle via Browser or via `./gradlew`

### Steps to Reproduce (for bugs)
Go to the browser and hit
https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip

This error then appears

```
downloads.gradle-dn.com uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. Error code: SEC_ERROR_UNKNOWN_ISSUER
```

**Comment by blindpirate** [comment]
@guenhter Thanks for reporting, we've noticed this issue and working on this. 
Can you please tell us what's your location? And when do you observe this failure?

**Comment by guenhter** [comment]
Sure. my Location is Austria (Europe). If you need it more precise, just say a word.
We noticed the problem since today (it's 9am here). Yesterday, everything worked fine.

**Comment by blindpirate** [comment]
OK, thank you. We thought this issue was fixed at 8am today European time, so if you still see it, can you please try to run `wget https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip` and paste the output here? That would help.

**Comment by guenhter** [comment]
```
> date
Tue 26 Feb 09:22:26 CET 2019


> wget https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip
--2019-02-26 09:22:30--  https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip
Resolving downloads.gradle-dn.com (downloads.gradle-dn.com)... 146.112.61.110, ::ffff:146.112.61.110
Connecting to downloads.gradle-dn.com (downloads.gradle-dn.com)|146.112.61.110|:443... connected.
ERROR: The certificate of ‘downloads.gradle-dn.com’ is not trusted.
ERROR: The certificate of ‘downloads.gradle-dn.com’ hasn't got a known issuer.
```

**Comment by sempr** [comment]
I meet the same issue, the output is

$ wget -v  https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip
--2019-02-26 17:52:22--  https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip
Resolving downloads.gradle-dn.com (downloads.gradle-dn.com)... 58.211.137.192
Connecting to downloads.gradle-dn.com (downloads.gradle-dn.com)|58.211.137.192|:443... connected.
OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Unable to establish SSL connection.

**Comment by big-guy** [comment]
@sempr we rolled back some changes here. Are you working again?

**Comment by guenhter** [comment]
```
> date && wget https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip

Tue 26 Feb 14:40:09 CET 2019
--2019-02-26 14:40:09--  https://downloads.gradle-dn.com/distributions/gradle-5.2.1-bin.zip
Resolving downloads.gradle-dn.com (downloads.gradle-dn.com)... ::ffff:146.112.61.110, 146.112.61.110
Connecting to downloads.gradle-dn.com (downloads.gradle-dn.com)|::ffff:146.112.61.110|:443... connected.
ERROR: The certificate of ‘downloads.gradle-dn.com’ is not trusted.
ERROR: The certificate of ‘downloads.gradle-dn.com’ hasn't got a known issuer.
```

**Comment by blindpirate** [comment]
@guenhter Please don't try `gradle-dn`, this is the redirected domain. Can you please try the original domain `http://services.gradle.org/distributions/gradle-5.2.1-bin.zip`?

**Comment by big-guy** [comment]
Can you try with gradlew again?  We switched back to not using gradle-dn.com at the moment.

**Comment by guenhter** [comment]
Thx for the fast support.
Works again.

**Comment by blindpirate** [comment]
@guenhter We've switched to `gradle-dn.com` as CDN domain again, so please let us know if you see any issues. Thank you very much.

**Comment by guenhter** [comment]
Still works. Thx.

**Comment by sempr** [comment]
It works now, thx.

**Comment by blindpirate** [comment]
@guenhter Thank you very much.
@sempr The downloading speed should be much improved in China now.

**Comment by wusatosi** [comment]
> @guenhter Thank you very much.
> @sempr Thank you very much. The downloading speed should be much improved in China now.

Gradle-dn.com is not used in China though :(, gradlew still downloads jar file from `services.gradle.org`
