### ISSUE TITLE
Process isolation mode doesn't expose resources to Thread.currentThread().getContextClassLoader().getResource()

### ISSUE THREAD

**Issue by jfbibeau** [gradle/gradle#8628]
We're attempting to spin up a Worker with a custom classpath. A class on that custom classpath is part of our product code, and uses `Thread.currentThread().getContextClassLoader().getResource()` to attempt to read a properties file located on the classpath.

### Expected Behavior
We should be able to use `Thread.currentThread().getContextClassLoader().getResource()` to pull a file from the classpath, when using Isolation mode of classloader or process.

### Current Behavior
Neither classloader nor process isolation modes give us access to the resource. The only thing that works is changing it to the class' classloader (`SerializerWorker.class.getClassLoader()`).

I even confirmed that when starting the worker with isolation mode of `PROCESS`, Gradle passes the correct JAR via `-cp` to the worker, and confirmed the JAR had the resource in it, but still can't find it. Odd.

### Context
We have to put in a 'workaround' in our production class to workaround this issue in Gradle.

### Steps to Reproduce (for bugs)
Download self-contained attached project and follow README :)
[gradle-task-resource-bug-master.zip](https://github.com/gradle/gradle/files/2906216/gradle-task-resource-bug-master.zip)

### Your Environment
macOS 10.14.2
OpenJDK 11.0.2

**Comment by imoverclocked** [comment]
I found a work-around that can be placed in the proxy class of the plugin:

```
        Thread.currentThread().setContextClassLoader(
                new URLClassLoader(
                        ((URLClassLoader) Thread.currentThread().getContextClassLoader()).getURLs(),
                        this.getClass().getClassLoader()
                )
        )
```

**Comment by ghale** [comment]
We've done quite a bit of refactoring of the classloader structure of workers with Gradle 5.5.  I'm pretty sure this should just work now.  Can you give the latest 5.5 RC a try and see if it resolves your issue  (https://gradle.org/release-candidate/)?

**Comment by imoverclocked** [comment]
For some reason, I still have to pass a classloader from the proxy class. The form of this hack has changed a little:

```
ObjectFactory.forName(klass, true, getClass().getClassLoader()).newInstance(...)
```

Just using the standard `forName(String name)` results in a `ClassNotFoundException`:

```
ObjectFactory.forName(klass).newInstance(...)
```
