### ISSUE TITLE
UnrecoverableUnpackingException is hidden by DefaultBuildCacheController

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#8629]
We have a special exception for when we fail to clean up the outputs after a failed unpack operation. This exception is supposed to signal a build failure to the `CacheStep`. However, it is [caught and wrapped](https://github.com/gradle/gradle/blob/b76473aa28015e53680f21b16fcba1067621153c/subprojects/build-cache/src/main/java/org/gradle/caching/internal/controller/DefaultBuildCacheController.java#L117) in a `GradleException` by the `DefaultBuildCacheController`, so it is never actually handled correctly.

**Comment by lptr** [comment]
It appears that the recovery from a failed unpack is botched in multiple places.

Here in [`ResolveIncrementalChangesTaskExecuter`](https://github.com/gradle/gradle/blob/da80e7e6df5d6463ed167f45d42b64b7f6de3f22/subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/ResolveIncrementalChangesTaskExecuter.java#L62) we call `context.isOutputRemovedBeforeExecution()` But that field in the context is only set much later, in [`CacheStep`](https://github.com/gradle/gradle/blob/a6c3d65b152aaf33e877609e0ded076af912add0/subprojects/execution/src/main/java/org/gradle/internal/execution/impl/steps/CacheStep.java#L111), when we are actually trying and failing to load something from cache.

This essentially means that we don't disable incremental execution after a failed unpack.

**Comment by lptr** [comment]
#8783 removes `UnrecoverableUnpackingException`—problems with cleaning up after a failed load from cache are not handled in a special way anymore. Instead, they simply bubble up to top and make the build fail as any other unexpected error would.

**Comment by oehme** [comment]
I didn't look deeper, but doesn't that mean that any local build cache issue fails the build? Wouldn't it be nicer if we continued until a certain number of errors when we can?
