### ISSUE TITLE
Too many Gradle Test Executors created for JUnit 5 tag inclusion with forkEvery

### ISSUE THREAD

**Issue by calvertdw** [gradle/gradle#8632]
For the test configuration:

```kotlin
tasks.test {
    useJUnitPlatform {
        includeTags("slow")
    }
   forkEvery = 1
   maxParallelForks = 1
}
```

### Expected Behavior

Each test class runs in a forked JVM.

### Current Behavior

Each test class runs in a forked JVM, but an additional empty JVM that doesn't run any tests is forked for each test class in my project. In my case, this is about 150 classes, where only 2 or so have the tag `@Tag("slow")`. This causes the build time to be mostly consumed by pointlessly spawning JVMs:

```
build	26-Feb-2019 11:16:21	Gradle Test Executor 1 started executing tests.
build	26-Feb-2019 11:16:21	Gradle Test Executor 1 finished executing tests.

...

build	26-Feb-2019 11:33:12	Gradle Test Executor 149 started executing tests.
build	26-Feb-2019 11:33:13	Gradle Test Executor 149 finished executing tests.
```

Only 4 tests were run in that build with a total test runtime of 3 minutes, in spite of the test phase taking 17 minutes.

### Context

We parallelize our tests over jobs in Atlassian Bamboo, to get nice visualization and "re-run" ability of each job, so each of our test builds should only run 1 test at a time, but they leak memory so we want each test to run in it's own JVM.

### Your Environment
Gradle 5.2
Oracle JDK 1.8.0_201
Linux 4.4.0-142-generic amd64 (Ubuntu 16.04 Server 64-bit)

**Comment by calvertdw** [comment]
Running the same build with `forkEvery = 3` and JUnit still measuring the test runtime at 3 minutes, the build takes 8 minutes (5 minutes of overhead spawning useless JVMs). It seems to prove that this is an important issue and a bug in Gradle.

**Comment by big-guy** [comment]
It's not exactly a bug -- it's a consequence of `forkEvery`.  The test filtering has to be done by the testing framework, which runs in a separate process. 

@marcphilipp do you have any ideas here?

**Comment by oehme** [comment]
We should only throw the executer away after it has really run a test, not when it skips one. This would require a significant redesign of the test execution infrastructure though.

**Comment by calvertdw** [comment]
It seems like Gradle must have a list of discovered tests it's secretly passing around to the executors. Shouldn't that be pre-filtered?

**Comment by oehme** [comment]
There is no prediscovered list, it's the executers job to disocover tests.
