### ISSUE TITLE
Task graph is different between Gradle 4.4 and Gradle 4.5

### ISSUE THREAD

**Issue by pedrovaldevino** [gradle/gradle#8641]
Hello. I'm migrating to Gradle 5x from v4.4, but my build breaks as soon as I update to a version >= 4.5.

Some issues are related to the fact that some tasks are now being added to the task graph, when they weren't before (and in my case, I don't want them there). I was able to produce a tiny example to illustrate this:

```
plugins {
  id 'java'
}

allprojects {
  apply plugin: 'java'
}

project(':foo') {
  dependencies {
    compile project(':bar')
  }

  task someTask(dependsOn: [project.configurations.compile]) {
    // this should call :bar:jar
  }
}

project(':bar') {
  jar {
    setDependsOn([]) // don't call other tasks
  }
}

```

If I execute ```foo:someTask -m``` with Gradle 4.4, I get this:

```
2:39:09 PM: Executing task 'foo:someTask --dry-run'...

:bar:jar SKIPPED
:foo:someTask SKIPPED

BUILD SUCCESSFUL in 0s
2:39:09 PM: Task execution finished 'foo:someTask --dry-run'.
```

While with Gradle 4.5 I get this instead:

```
2:39:36 PM: Executing task 'foo:someTask --dry-run'...

Build cache is an incubating feature.
:bar:compileJava SKIPPED
:bar:processResources SKIPPED
:bar:classes SKIPPED
:bar:jar SKIPPED
:foo:someTask SKIPPED

BUILD SUCCESSFUL in 0s
2:39:36 PM: Task execution finished 'foo:someTask --dry-run'.
```

I had a look at the release notes for v4.5 and I could not find a reason for this. What am I missing/doing wrong? If this is something that no longer works, how can I achieve the same with an updated version? Many thanks.

**Comment by lacasseio** [comment]
This is [an expected change](https://github.com/gradle/gradle/commit/8e4f53010070cd3f5a759534f12744ba3738ab91). The question is what's your use case for doing something like this? Gradle is moving toward correct-by-default behaviour. If we detect inputs is been produced by another task, then we will add task dependencies in order to ensure the input gets generated.
