### ISSUE TITLE
Daemon memory leak soak tests are very brittle

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#8655]
Our memory leak tests attempt to force the daemon into low-memory situations. The way it does this is highly dependent on how exactly the GC and GC monitor interact.  

We really want a couple of kinds of tests:
- Integration level tests that detect a given low memory situation. This can be fed in artificially
- Integration level tests that react to a detected situation. This can be fed in artificially
- Soak level tests that do something similar to the existing tests, but can be a little more relaxed in exactly what we're testing for.

**Comment by ghale** [comment]
PR https://github.com/gradle/gradle/pull/8720
