### ISSUE TITLE
Gradle fails to start on Java 9 Jigsaw snapshots due to failure in dynamic class generation

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#866]
`AsmBackedClassGenerator` and `AbstractProxyClassGenerator` both use protected methods reflectively to inject dynamically generated classes into various ClassLoaders. This fails on Java 9 Jigsaw because these methods are no longer accessible, and so Gradle fails to start.

There is no strong reason why we need to use this approach, so can change it to avoid requiring the use of protected methods.

A quick hack to fix this is available in this branch: https://github.com/gradle/gradle/tree/am-jigsaw-hacks

**Comment by melix** [comment]
This should be fixed by #2175

**Comment by jjohannes** [comment]
Gradle obviously now works with Java versions 9+.
