### ISSUE TITLE
Build scans are not supported for this build due to a build plugin composite substitution.

### ISSUE THREAD

**Issue by tazzledazzle** [gradle/gradle#8660]
Build scans are not supported for this build due to a build plugin composite substitution.

This is troublesome for me because I have a couple plugins in `buildSrc` that depend on a project in my build that will be moving directories and now my classpath is having issues.

### Expected Behavior
I have build scans published after a build with composite build substitutions.

### Current Behavior
Build scans are disabled because they are not supported currently.

**Comment by 3flex** [comment]
This is becoming more of an issue now that build scans are the only supported method to test task configuration avoidance. Gradle 5.0 docs said to either use build scan or run `gradle -Dorg.gradle.internal.tasks.stats help` when testing changes related to task configuration avoidance. The command still works as of Gradle 5.4 but it's clear it shouldn't be relied upon and could be removed at any time.

Build scans would be very useful in general anyway but this is a specific case that needs a supported solution.

**Comment by 3flex** [comment]
I think this can be closed now - from [Build Scan plugin release history](https://docs.gradle.com/build-scan-plugin/#plugin_release_history):

> 2.3 - 3rd May 2019
Added support for plugin composite builds
Added support for continuous builds
Added support for capturing the details of annotation processors used during Java compilation

**Comment by ldaley** [comment]
Thanks for following up @tazzledazzle
