### ISSUE TITLE
Add way to lazily create dependent tasks of all of a type of task

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#8662]
I have a plugin where I want to add a task per instance of a single task type. In my use case, I need a task added per instance of the `CompileJava` task. I want this new task to be lazily created, and it needs to include the name of the `CompileJava` task in its name. With the lazy API's, I cannot find a way to do this. Doing this currently seems to require force configuring all `CompileJava` tasks, which we shouldn't have to do.

As an idea, if there was a way from `TaskContainer` to get a list or an on registered callback of `Name, TaskProvider<T>` pairs for a specific type of task, that would solve this, and many other cases of lazy creation I can think of. It seems like all the information needed to make an API like this should be already known by gradle.

**Comment by ThadHouse** [comment]
Digging more through the API, it looks like `TaskProvider` already has a `getName()` on it. This means if there as a `whenRegistered(Action<TaskProvider>)` api added to `TaskContainer`, this would be easily solved.

**Comment by lacasseio** [comment]
This issue use-case is duplicate in several places such as https://github.com/gradle/gradle-native/issues/772. I will close this issue in favour of the other one.
