### ISSUE TITLE
[Gradle 5.2.1] zip task does not support setting archiveName/destinationDir at doFirst 

### ISSUE THREAD

**Issue by CharmsStyler** [gradle/gradle#8668]
```
task myZip(type: Zip) {
    from('actors') {
        include('src/main/**')
        include('buildfiles/petiole/**')
    }

    doFirst {
        /**
        here the archiveName is generated at execution time by plugin. for the simplicity of the example this is staticly defined.
        **/
        archiveName 'Reports123.zip' // <= 
        destinationDir(file('.'))
    }

    doLast {                
        println "zip file= ${destinationDir}/${archiveName}"            
    }
}
```

### Expected Behavior

It honor the parameters defined at the doFirst setup and generate at ./Reports123.zip
(This works as expected in Gradle 4.10.2 )

### Current Behavior

Gradle 5.2.1 does not honor the parameters defined at doFirst it populates at   [org.gradle.internal.execution.impl.steps.CreateOutputsStep] Ensuring parent directory exists for property archiveFile at project/build/distributions/project-0.0.1.SNAPSHOT.zip

### Steps to Reproduce (for bugs)

1. Add the following file to build.gradle file
2. run  gradle -q myzip --debug

### Your Environment

 * Build scan URL:

**Comment by big-guy** [comment]
This is intentional.  You shouldn't change the configuration of a task once it has started executing.

If you're using 5.1+, you can try:
```
task myZip(type: Zip) {
    from('actors') {
        include('src/main/**')
        include('buildfiles/petiole/**')
    }

    archiveFileName = provider {
        // calculate name
    }

    destinationDirectory = file('.')
}
```

**Comment by CharmsStyler** [comment]
@big-guy is there way we could apply same for destinationDir = project.provider{  ?

```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'provider(?)' with class 'org.gradle.api.internal.provider.DefaultProvider' to class 'java.io.File'
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:375)
        at org.gradle.internal.metaobject.BeanDynamicObject.trySetProperty(BeanDynamicObject.java:176)
        at org.gradle.internal.metaobject.CompositeDynamicObject.trySetProperty(CompositeDynamicObject.java:66)
        at org.gradle.internal.metaobject.ConfigureDelegate.setProperty(ConfigureDelegate.java:94)
```

**Comment by lacasseio** [comment]
Use `destinationDirectory` instead of `destinationDir`.

**Comment by CharmsStyler** [comment]
@lacasseio Fails with 
```
Caused by: org.gradle.api.InvalidUserDataException: No value has been specified for property 'archiveFile'.
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.report(ValidatingTaskExecuter.java:64)
        ... 34 more
```
Full code..
```
task myZip(type: Zip) {
   from('actors') {
       include('src/main/**')
       include('buildfiles/petiole/**')
   }
 archiveFileName.set( project.provider { somePlugin.fileName } )
 destinationDirectory.set ( project.objects.directoryProperty().dir(somePlugin.dirname) )
 
}
```

**Comment by lacasseio** [comment]
`project.objects.directoryProperty()` builds a `DirectoryProperty` and `DirectoryProperty#dir` creates a `Provider<Directory>` where his value depends on the `DirectoryProperty` that was just created. The error you are receiving comes from the fact that the `DirectoryProperty` doesn't have any value set. You should only use `project.objects.directoryProperty()` when creating properties, not when setting values. The setter for `DirectoryProperty` can take a `File` instance that you can create using `Project#file` or a `Directory`/`Provider<Directory>` which can be built using either `project.layout.projectDirectory.dir` (same as `Project#file`) or `project.layout.buildDirectory.dir` (same as `Project#file("$buildDir/...")` but the `buildDir` resolution is differed in case the value is changed later. I hope this helps answer your question.

**Comment by smac89** [comment]
This is why I am grateful that Kotlin is now here for gradle. Can't keep track of these types!

**Comment by khumbuche** [comment]
I am using Gradle 5.5.1 Kotlin script to produce .ear file as document describes (https://docs.gradle.org/current/dsl/org.gradle.plugins.ear.Ear.html#org.gradle.plugins.ear.Ear:archiveName) in the code below, but it results in error - any reason, why? 

Just for kicks & giggle - I have also tried archiveFile but with no avail. 
Thanks.
Sunit.

```
plugins {
	`ear`
}

ear {
	archiveFileName = "test_servce.ear"
	deploymentDescriptor {
		displayName = "Test Web Services"
	}
	dependencies {
		deploy(project(path = ":war_project", configuration="archives"))
	}
}
```

Results in error:

```
  Line 6:       archiveFileName = "test_servce.ear"
           ^ Unresolved reference: archiveFileName
```

**Comment by paplorinc** [comment]
The [ear](https://github.com/gradle/gradle/blob/master/subprojects/ear/src/main/java/org/gradle/plugins/ear/Ear.java#L53) plugin seems to have setters for `archiveName`, `baseName` and `libDirName`.
Could you please retry your script with 
```kotlin
ear {
    archiveName = "test_servce.ear"
    // ...
}
```

**Comment by khumbuche** [comment]
@paplorinc,
I tried your solution again but resulted in following error. 

Thanks,
Sunit
````
  Line 6:       archiveName = "test_servce.ear"
           ^ Unresolved reference: archiveName

1 error
````

**Comment by paplorinc** [comment]
Hey, just tried it out locally, it's working for me with
```gradle
ear {
    archiveBaseName = 'test_servce'
}
```
see: https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/tasks/bundling/AbstractArchiveTask.java#L51

**Comment by khumbuche** [comment]
That still didn't work for me in Kotlin.  It resulted in same error for archiveBaseName.

**Comment by paplorinc** [comment]
@eskatos, @bamboo, can you guys help out?

**Comment by bamboo** [comment]
The `ear` plugin registers an `ear` task. The Kotlin DSL requires tasks to be accessed through the `tasks` container, the following should work:
```kotlin
plugins {
    ear
}

tasks.ear {
    archiveName = "test_servce.ear"
    // ...
}
```

**Comment by khumbuche** [comment]
@bamboo, The solution provided fixed the issue.
Thank you, all!

**Comment by khumbuche** [comment]
@bamboo,
The build pipeline is working like a charm with above fix.  However, when I run `gradlew eclipse` task, I get 

* What went wrong:
Could not create task ':test_ear:ear'.
\> Cannot change dependencies of configuration ':test_ear:deploy' after it has been resolved.


So, I added dependency to GenerateEclipseClasspath task as shown below.  It fixed the problem running `gradlew eclipse`, but did not fix the problem when project is imported thru `Eclipse -> Import -> Gradle -> Existing Gradle Project` on Eclipse v4.12.  Any suggestions?


```
plugins {
	'java'
	'ear'
	'eclipse'
}

tasks.ear {
	// The ear plugin registers an ear task. The Kotlin DSL requires 
	// tasks to be accessed through the tasks container, details on
	// https://github.com/gradle/gradle/issues/8668

	archiveName = "test_services.ear"
	deploymentDescriptor {
		displayName = "Test Services"
	}
	dependencies {
		deploy(project(path = ":war_project", configuration = "archives"))
	}
}

tasks {
	// Added dependency so 'Eclipse' can reference the project
	withType<GenerateEclipseClasspath> {
		dependsOn("ear")
	}
}
```

Thanks.
Regards.
