### ISSUE TITLE
gradle/native-samples : binary-dependencies project does not work on macos 

### ISSUE THREAD

**Issue by eltonkent** [gradle/gradle#8670]
Checkout the native-samples project. https://github.com/gradle/native-samples
 https://github.com/gradle/native-samples/tree/master/cpp/binary-dependencies.

### Expected Behavior
The binary dependencies project should work just fine.

### Current Behavior
```
> Task :compileDebugCpp FAILED
In file included from /Users/.../cpp/binary-dependencies/src/main/cpp/split.cpp:2:
/Users/.../cpp/binary-dependencies/src/main/headers/string_utils.h:9:10: fatal error: 'linked_list.h' file not found
#include "linked_list.h"
         ^~~~~~~~~~~~~~~
1 error generated.
```
The binary dependencies have been built and uploaded to 1. .m2 2. ../repo
### Environment
Gradle 5.2.1
------------------------------------------------------------
Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.14.3 x86_64

**Comment by lacasseio** [comment]
Issue moved to [gradle/gradle-native #995](https://github.com/gradle/gradle-native/issues/995) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lacasseio** [comment]
Thanks for reporting this issue, I moved the issue to the `gradle-native` repository where all native issues are handled.
