### ISSUE TITLE
"Ignoring listeners of task graph ready event" logged, yet listener fired

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#8672]
I registered a listener (from a plugin apply method) via:

    project.getGradle().getTaskGraph().whenReady(Action<TaskExecutionGraph>)

When using the plugin in Gradle 5.2.1, I saw the following warning:

> Ignoring listeners of task graph ready event, as this build (:<build-name>) has already executed work.

The listener still fired.

This logging presumably occurs at:

https://github.com/gradle/gradle/blob/c2e97cd6229cfa1f8e48eadb6189acd2d6bcf99a/subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskExecutionGraph.java#L174

### Expected Behavior
I want the listener to fire, but it's disconcerting to see this warning.

Either the warning shouldn't be logged in this case, or the listener shouldn't fire.

### Current Behavior
Warning output, and listener fires, despite warning saying it will be ignored.

### Steps to Reproduce (for bugs)
Write project plugin that uses the aforementioned task graph listener registration method.

### Your Environment
Will supply as needed.

**Comment by big-guy** [comment]
@rgoldberg do you have a complete example you can provide? Are you using configure-on-demand or composite builds?

**Comment by rgoldberg** [comment]
Unfortunately, I won’t have time to look into this for at least a few weeks, if not months. I’ll try to get to it, but it might be a while.

**Comment by big-guy** [comment]
All right.  My simple attempts to reproduce didn't turn up anything, so please reopen the issue or leave a comment here if you have more information. Thanks!

**Comment by rgoldberg** [comment]
How do I reopen?

Had time to get a fairly small example, which is attached.

[task-graph-listeners.zip](https://github.com/gradle/gradle/files/2991196/task-graph-listeners.zip)

**Comment by rgoldberg** [comment]
This is still happening in Gradle 5.4.

Any idea what causes this?

**Comment by rgoldberg** [comment]
This is still happening in Gradle 5.4.1.

Any idea what causes this?

**Comment by rgoldberg** [comment]
I think I ran into an actual issue that is caused by the underlying mechanism that outputs this warning.

A simplified setup has a composite build (C) that includes a plugin build (P). P is applied to another included build (B).

It seems that if the overall task graph includes a task from both P & B (e.g., :P:javadoc & :B:javadoc), a task graph ready event will fire for the tasks in P necessary to create the binary P plugin for use by B (i.e., :P:jar & all its task dependencies).  A task graph ready event will also fire for :B:javadoc (& its dependencies), but no task graph ready event will fire for :P:javadoc (& its dependencies) because P has already done work.  If setup for :P:javadoc is performed in a task graph ready event for P, then :P:javadoc won't be properly setup because that code won't ever run.

Is the above intelligible?

If not, what clarification do you need?

If so, should this remain part of this issue, or should I create a new issue?  Is there any reason why either a second task graph ready event can't be fired for :P:javadoc (& its dependencies), or why those tasks can't be included in the original task graph ready event for P (that was only for :P:jar & its dependencies)?
