### ISSUE TITLE
Gradle generates broken generated-gradle-jars/gradle-api-5.2.1.jar when run in a Docker container using adoptopenjdk/openjdk11:alpine-slim as base image

### ISSUE THREAD

**Issue by ewirch** [gradle/gradle#8675]
Using Gradle 5.2.1 with wrapper script. See attached project:
[gradle-fail.zip](https://github.com/gradle/gradle/files/2926296/gradle-fail.zip)

Create Docker image:
```
docker build --tag gradle-fail .
```

Run created image:
```
docker run -ti gradle-fail
```

Once inside the container, run Gradle:
```
./gradlew test --no-daemon
```

Gradle will fail:
```
  Line 1: rootProject.name = "cloud-configuration"
          ^ Unresolved reference: rootProject
```

Reading debug output will tell me that Gradle cannot read files from generated `gradle-api-5.2.1.jar`. Quick check:
```
> jar -xf /root/.gradle/caches/5.2.1/generated-gradle-jars/gradle-api-5.2.1.jar

Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
java.util.zip.ZipException: invalid distance too far back
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:195)
	at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:141)
	at jdk.jartool/sun.tools.jar.Main.extractFile(Main.java:1452)
	at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1359)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:409)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1676)
```

The jar is broken. No wonder Gradle cannot read the contents.

Note: just tested with openjdk:11-jdk-slim as base image. Works as expected. So its probably a Gradle / adoptopenjdk issue.

**Comment by blindpirate** [comment]
See https://github.com/AdoptOpenJDK/openjdk-docker/issues/87

**Comment by blindpirate** [comment]
Thanks for reporting. I'm afraid this is an JDK issue when running in alpine-slim docker container. See the issue above for reproducible sample with pure Java code. It has nothing to do with Gradle.

**Comment by blindpirate** [comment]
BTW I was even trying to find out the root cause via debugging, but it turned out to be a native JDK code generating the corrupted byte stream so I gave up.
