### ISSUE TITLE
Distribution plugin should allow line endings customization

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#8688]
### Expected Behavior

Distribution should allow to create distributions with custom-provided line endings.
In other words, publish `readme.txt` as CRLF (in *.zip) and as LF (in *.tar)

### Current Behavior

Both created archives have the same contents. It is kind of bad since Windows would expect CRLF, and Linux would expect LF.

### Context

I'm trying to create binary and source code distribution for Apache JMeter, and the convention there is to have `*.zip` with CRLF, and `*.tgz` with LF.

### Steps to Reproduce (for bugs)

```
plugins {
    distribution
}

distributions {
    main {
        contents {
            from(file("build.gradle.kts"))
        }
    }
}
```

`./gradlew assembleDist` produces `dist.zip` and `dist.tar` with exactly the same contents (current contents of `build.gradle.kts` which is not user-friendly, and which depends on the build environment)

**Comment by big-guy** [comment]
I *think* you can do this via `filter(FixCrLfFilter)` in the tasks that generate the zip and tar.

**Comment by vlsi** [comment]
Of course I can.

However it would be really nice if Gradle could automatically infer line endings and executable bits.

Here's a small DSL I ended up with:

```kotlin
fun commonFiles(textEol: LineEndings) = copySpec {
...
     into("examples") { // <-- Gradle's 'into'
        from("$rootDir/bin/examples", textEol) { // <-- my own extension function
            text("**/*.jmx", "**/*.jsp", "**/*.csv") // <-- my own extension function
            binary("**/*.png") // <-- my own extension function
        }
    }
    into("extras") {
        from("$rootDir/extras", textEol) {
            shell("proxycert", "schematic") // <-- my own extension function
            text("*.json", "*.jmx", "*.txt", "*.xml", "*.bsh", "*.xsl")
            binary("*.jar", "*.png")
        }
    }
}

val distTar by tasks.registering(Tar::class) {
    ...
    with(commonFiles(LineEndings.LF))
}

val distZip by tasks.registering(Zip::class) {
    ...
    with(commonFiles(LineEndings.CRLF))
}

```

The idea is
1) I create a function that returns `CopySpec` with that adjusts text files appropriately.
In theory it should allow to produce the same archives no matter which OS developer uses.
2) The sad thing Gradle does not allow to specify `text`/`binary`/`shell`. It basically requires to duplicate `from` items like the following (which is what my `from(String, LineEndings, ..)` function does behind the scenes (e.g. https://github.com/apache/jmeter/pull/448/commits/0d3f858fa27ddfc6290b996ef8d4bbb810672cab#diff-4d9d83e51a27ac8f096d75f6af4f09aeR69 ):

```kotlin
        from("$rootDir/bin/examples") {
            include("**/*.jmx")
            filter(text)
        }
        from("$rootDir/bin/examples") {
            include("**/*.png")
            filter(binary)
        }
        from("$rootDir/bin/examples") {
            include("proxycert.sh")
            filter(LineEndings.LF) // LineEndings is not present in Gradle :(
            fileMode = "755".toInt(8)
        }
        from("$rootDir/bin/examples") {
            include("proxycert.cmd")
            filter(LineEndings.CRLF) // LineEndings is not present in Gradle :(
        }
```

Well, I can add my extension functions and be happy, however it is really sad default Gradle behaviour does not enable to have cross-platform consistent builds.

**Comment by vlsi** [comment]
This is kind of related: https://github.com/gradle/gradle/issues/1588

**Comment by vlsi** [comment]
This is still relevant

**Comment by vlsi** [comment]
I believe this is still relevant
