### ISSUE TITLE
Console.readline() prompt text is overwritten by status line

### ISSUE THREAD

**Issue by benmccann** [gradle/gradle#869]
Migrated from https://issues.gradle.org/browse/GRADLE-3446

https://discuss.gradle.org/t/console-readline-does-not-print-text-if-run-from-dolast-with-gradle-2-13/17371
I have a script that ask for user input using `System.console().readline('label')`. The label is printed on console and the user can type something.

### Your Environment
I upgraded from gradle 2.12 to 2.13 and now the first label I use in the task disappears.

### Steps to Reproduce (for bugs)
This issue can be reproduced with the following code:

```gradle
def console = System.console()
def firstname
def lastname

task run {
    doLast {
        firstname = console.readLine('> What is your first name?: ')
        lastname = console.readLine('> What is your last name?: ')
    }
}
```

### Expected Behavior
With Gradle 2.12:

```
"gradle-2.12/bin/gradle" run
> Building 0% > :run> What is your first name?: John
> What is your last name?: Doe
:run
```

### Current Behavior
With Gradle 2.13:

```
> "gradle-2.13/bin/gradle" run
> Building 0%> What is your > Building 0% > :runJohn
> What is your last name?: Doe
:run
```

The first label (> What is your first name?) is not showing.

### Context
We are trying to prompt the user to enter their password. The password prompt is disappearing

**Comment by eriwen** [comment]
@benmccann Thanks very much for the well-written issue. I have confirmed this continues to affect Gradle 3.2.

**Comment by fbrubbo** [comment]
@eriwen is there any plan to fix this? we are waiting this fix for a long time now.

**Comment by eriwen** [comment]
@fbrubbo Fixing this issue is currently unscheduled; however, if you use [Zenhub](zenhub.io) it is in our Backlog which means it is much more likely to be picked up in the next couple releases. 

We welcome contributions to our free, open-source project if you are passionate about this issue.

**Comment by dant3** [comment]
I can confirm this issue still exists in Gradle 4.0

**Comment by samsieber** [comment]
As a work around, you can use 
``` --conosle plain ```
as cli args to gradle and it won't happen... but that's just one more thing to ask users to do :(

**Comment by eriwen** [comment]
One can also set environment TERM=dumb @samsieber

**Comment by ov7a** [comment]
This issue is not planned to be fixed because it will be superceeded by this issue:
* https://github.com/gradle/gradle/issues/1251
