### ISSUE TITLE
[TestKit] Could not create service of type FileHasher

### ISSUE THREAD

**Issue by pablisco** [gradle/gradle#8695]
When upgrading our [plugin](https://github.com/novoda/gradle-static-analysis-plugin/) to Gradle 5, one of the issues that we found was that the build was complaining about timing out because of `fileHashes` being locked:

```
* What went wrong:
    Could not create service of type FileHasher using GradleUserHomeScopeServices.createCachingFileHasher().
    > Timeout waiting to lock file hash cache (/tmp/.gradle-test-kit-jenkins/caches/5.2.1/fileHashes). It is currently in use by another Gradle instance.
      Owner PID: 22085
      Our PID: 10210
      Owner Operation: 
      Our operation: 
      Lock file: /tmp/.gradle-test-kit-jenkins/caches/5.2.1/fileHashes/fileHashes.lock
```

We managed to fix this by moving the `testKit` directory locally to the test using `.withTestKitDir()` however, this has incremented our build time from 16 minutes to almost an hour and a half. Our guess is that it could be because of having to set up `testKit` for each tests (although could be wrong)

### Expected Behavior
No lock/timeout when using shared TestKit directory and potentially not taking so long to run the build.

### Current Behavior
Build time is inflated by a factor of 6x

### Context
This is related to gradle plugin tests in https://github.com/novoda/gradle-static-analysis-plugin/

### Steps to Reproduce (for bugs)
https://github.com/novoda/gradle-static-analysis-plugin/pull/171

### Your Environment
This happens on local and on our CI environment.

**Comment by Kailash23** [comment]
Check this
https://stackoverflow.com/a/46094804/7727818

**Comment by jjohannes** [comment]
Please leave a comment here or open a new issue if this is still a problem with Gradle 7.
