### ISSUE TITLE
Play application testPlayBinary cannot be configured in model block

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#870]
### Expected Behavior

I expect to be able to configure the `testPlayBinary` task in the `model` block.

### Current Behavior

Configuring the task fails with:

```
Cannot add rule testPlayBinary { ... } @ build.gradle line 151, column 7 for model element 'tasks.testPlayBinary' at state DefaultsApplied as this element is already at state Initialized.
```

### Context

I was attempting to provide some additional properties by configuring `testPlayBinary` task.

### Steps to Reproduce (for bugs)

1. Clone https://github.com/simonharrer/play-java-gradle-example
1. Add a `testPlayBinary` configuration rule (in my case I added to line 151)

    ```groovy
    model {
      tasks {
        testPlayBinary {
          systemProperty 'propname', 'value'
        }
      }
    }
    ```

1. Run `./gradlew build

### Your Environment

Tested on Gradle 3.1 and 3.2

 * Build scan URL: https://scans.gradle.com/s/pydnoyurpgi5o

**Comment by lacasseio** [comment]
Thanks Mike for this well-formed bug request. My preliminary debugging downsized the reproducible sample to the following build script:
```
plugins {
    id 'play'
}

repositories {
    jcenter()
}

model {
    tasks {
        testPlayBinary {
          systemProperty 'propname', 'value'
        }
    }
}
```
