### ISSUE TITLE
Message formatting is incorrect when artifacts cannot be resolved

### ISSUE THREAD

**Issue by srmurguia** [gradle/gradle#8708]
### Expected Behavior
When artifacts cannot be resolved a message saying what failed should be shown in the output

### Current Behavior
A message is shown, but its formatting seems to be wrong, for example:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'My Application'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.5.0-alpha07.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0-alpha07/gradle-3.5.0-alpha07.pom
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0-alpha07/gradle-3.5.0-alpha07.jar
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0-alpha07/gradle-3.5.0-alpha07.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.5.0-alpha07/gradle-3.5.0-alpha07.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

In particular this part seems to be missing something (or have extra " :"")
     Required by:
         project :

### Context
Message can be confusing.

### Steps to Reproduce (for bugs)
Add a dependency to an artifact that does not exist and run a task. I reproduced it by adding a Android Gradle plugin version that is not available to an Android Studio project and then running this in a terminal:
./gradlew :app:generateDebugSources

### Your Environment
Using gradle-5.2.1-bin on a linux machine.

**Comment by ljacomet** [comment]
When failing to resolve dependencies, the impacted project is listed. The notation for the root project happens to be simply `:`.

So while the output is indeed correct, improvements could be made for things to be clearer.

**Comment by ljacomet** [comment]
After internal discussions, this notation is used in a lot of places and there is no reason to change it. It is part of the Gradle learning curve.
