### ISSUE TITLE
ResolutionStrategy not honored for transitive dependencies of project dependency

### ISSUE THREAD

**Issue by eric-isakson** [gradle/gradle#872]
### Expected Behavior
In a multi-project build where I depend on a project that has a resolution strategy, I expect the resolution strategy to be applied to the transitive dependencies I get when I depend on that project.

### Current Behavior
The resolution strategy is not applied to the transitive dependency

### Context
I'm working with multiproject builds and I don't want to have to repeat myself if I create a project dependency.

### Steps to Reproduce (for bugs)
https://github.com/eric-isakson/gradle-multi-project-transitive-dependency-problem
Clone and run:
`./gradlew :bob:dependencies :joe:dependencies`

You will see that bob resolves fine while joe that depends on bob fails to resolve.

**Comment by eric-isakson** [comment]
I know that it is possible to fix this by applying the same resolution strategy to both joe and bob, but my actual use case is more complex where I am dynamically adding subprojects when they are present in my local workspace and using a dependency substitution rule to switch from module dependencies to project dependencies.

This is with 2.14.1

master/settings.gradle:```
rootProject.name = 'master'

if (rootDir.name == 'master') {
    // Include all peer projects that are themselves Gradle builds
    rootDir.parentFile.listFiles(new FileFilter() {
        @Override
        boolean accept(File subdir) {
            return new File(subdir, 'build.gradle').exists() && subdir.name != 'master'
        }
    }).each {
        includeFlat it.name
    }
}
```

master/build.gradle:```
// ...
def modulesToSubprojects = subprojects.collectEntries { subproject ->
    def subprojectId = ":${subproject.name}"
    // this makes rootProject.afterEvaluate go after all subprojects have been evaluated
    rootProject.evaluationDependsOn(subprojectId)
    ["${subproject.group}:${subproject.name}" : subprojectId]
}
afterEvaluate {
    subprojects.each { subproject ->
        subproject.configurations.all {
            modulesToSubprojects.each { moduleId, subprojectId ->
                resolutionStrategy.dependencySubstitution {
                    substitute module(moduleId) with project(subprojectId)
                }
            }
        }
    }
}
//...
```

I use git submodules and have some users that pull all of the subprojects and some that only pull in one or two. My subprojects are required to not themselves use subprojects and express there interdependencies using module dependencies in their individual build.gradle files.

I'm about to try out the composite builds introduced in Gradle 3 and I'm hoping they support this concept but my organization is currently on 2.14.1

**Comment by eric-isakson** [comment]
I notice this is labeled as a feature but isn't this a bug even if it is a long standing one that wasn't noted before? Thank you for the follow up!

The doc here:

https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:project_jar_dependencies

states:

> A “lib” dependency is a special form of an execution dependency. It causes the other project to be built first and adds the jar with the classes of the other project to the classpath. **It also adds the dependencies of the other project to the classpath**. So you can enter the “api” directory and trigger a “gradle compile”. First the “shared” project is built and then the “api” project is built. Project dependencies enable partial multi-project builds.

**Comment by bigdaz** [comment]
This is how the `ResolutionStrategy` works: it provides additional context that is used when _resolving_ a configuration. It does not have any effect on _consumers_ of that configuration, whether that's via a project dependency or via a published module.

We don't have any plans to directly change this: `ResolutionStrategy` will remain just that, a way to influence the resolution of a Configuration. However, we are introducing the concept of transitive "dependency constraints" that will affect direct resolution of a Configuration, resolution of a child Configuration, consumption via a project dependency, consumption in a composite build and publishing to a repository.

In the meantime, you might want to check out the [Spring dependency-management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin), or the [Nebula dependency-recommender plugin](https://github.com/nebula-plugins/nebula-dependency-recommender-plugin) which perform magic to allow some sorts of rules to be applied transitively in this way.

**Comment by flyskywhy** [comment]
honored by e.g.

    allprojects {
        repositories {
            exclusiveContent {
                filter {
                    includeGroup "com.facebook.react"
                }
                forRepository {
                    maven {
                        url "$rootDir/../node_modules/react-native/android"
                    }
                }
            }
        }
        ...
    }

ref to https://github.com/flyskywhy/PixelShapeRN/commit/a4fcde5
