### ISSUE TITLE
can't use plugin in flat dir

### ISSUE THREAD

**Issue by brainchild0** [gradle/gradle#8726]
### Overview

Whereas it was possible using the old-style `apply()` semantics to find a plugin definition from a local "flat" directory, as best I can determine, this  case is not possible when the plugin is declared using the new-style `plugin {}` blocks.  

### Expected Behavior

If the below block appears in the `settings.gradle` file for a project, then Gradle should search the `lib` subdirectory for plugins.

~~~groovy
pluginManagement {
    repositories {
        gradlePluginPortal()
        jcenter()
        flatDir {
            dirs 'lib'
        }
    }
}
~~~

The plugin should be discovered as long as the ID appears in the plugin block in `build.gradle`.

~~~groovy
plugins {
    id 'plugin-id'
}
~~~

### Current Behavior

Gradle produces the error:

~~~text
 What went wrong:
Plugin [id: 'plugin-id'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)
~~~

The situation improves slightly if a version number is added to plugin declaration in the build file and the JAR file is renamed appropriately.

~~~text
Plugin [id: 'plugin-id', version: '1.0.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'plugin-id:plugin-id.gradle.plugin:1.0.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    BintrayJCenter
    flatDir(/absolute/path/to/lib)
~~~

It is strange that adding the version number to *what is being searched for* affects the *list of places being searched*.

The main issue, however, is that Gradle does not find the plugin in either case.

### Context

I am unable to use new-style plugin semantics to use a plugin in a local directory under the project directory that is not a repository.

### Steps to Reproduce

1.  Create a plugin definition,   and place the JAR file in the a local directory within the project.
2.  Add the `pluginManagement{}` block as above to `settings.gradle` and the `plugin` declaration using the plugin ID and version number in `build.gradle` as above.
3. Invoke Gradle on any build task.

*I will attempt to provide an example if other details are insufficient to explain the issue.  However, doing so is complicated by needing to  build separately a plugin that is not available in any standard repositories.*

###   Environment

OS: Linux Mint 19.1

~~~text
$ java --version
openjdk 11.0.1 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1, mixed mode, sharing)
~~~

~~~
$ gradle --version

------------------------------------------------------------
Gradle 5.2
------------------------------------------------------------

Build time:   2019-02-04 11:16:48 UTC
Revision:     840644a429c8b8b9ae399867eb1660e3109bc7a3

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.1 (Oracle Corporation 11.0.1+13-Ubuntu-3ubuntu118.04ppa1)
OS:           Linux 4.18.0-16-generic amd64
~~~

### Further information

*May* be duplicate of #5425.

**Comment by big-guy** [comment]
I think you have to actually publish to the directory (so other marker artifacts are included, not just the jar).  

Have you thought about/tried using [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) instead?  This would avoid having to put the jar in a special place and use flat dir.

**Comment by big-guy** [comment]
I think you're right this is a dupe of #5425

**Comment by brainchild0** [comment]
> I think you have to actually publish to the directory (so other marker artifacts are included, not just the jar).

I don't know what this means, and I haven't found clarification in the documentation.  Would you please explain, as well as indicate any relevant user documentation?
 
> Have you thought about/tried using [composite builds](https://docs.gradle.org/current/userguide/composite_builds.html) instead?

No, I was not aware of it.  I will have to learn about it to determine how well it meets my requirements.


> I think you're right this is a dupe of #5425

Before leaving this issue, please note, that my intention was to suggest that the behavior I described *may* derive from the same problem in the codebase as the behavior the other user described.  Certainly, key differences separate the two cases in terms of use, requirements, and behavior.  If you can confirm, based on the design of the software, that the two issues are to be merged, such determination is yours to make.  I am uncomfortable that this issue has already been closed, because I am yet unclear whether the report I submitted relates to 1) a bug, 2) a design flaw,  3) lack of documentation about how to organize a build for the particular requirements, or 4) personal confusion that could be remedied by being pointed to existing documentation.  If nothing else, I would ask for some clarify on this distinction.

**Comment by brainchild0** [comment]
I now feel quite frustrated.

I carefully filed a report, with a full description of the issue and and a complete set of details required to reproduce.

The issue was closed.  A minimal response was given.

I requested clarification 11 days ago.  Yet, I have no further elucidation on any of the following questions:
1.  Is the observed behavior intended, or   a bug?
1.  How do I achieve the desired effect?  Invoke a more appropriate feature?  Use the same feature differently?  Apply a work around until some bug is resolved?  
1.   Are improvements or fixes planned to address the problem, if it is a bug or a design issue?
1.   Are documentation changes planned, or are articles currently available, to clarify any possible misunderstanding or  mistake?



I had explained this issue on a common Q&A site.  The community had no insight on the topic.  Then, I posted to the issue tracker, and still received no useful information, or full acknowledgment of a properly identified issue.  Given these observations, the best case about this question is that the community currently suffers from a very serious poverty of information and understanding on this topic.  Even if the scope of the problem is limited to this optimistic case, I would hope that at least some productive exchange of information can begin.

**Comment by jjohannes** [comment]
@brainchild0 A flat dir repository won't work out of the box with the plugins block. In order to find a plugin, a so called [plugin marker](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) needs to be published as well. Which is a pom.xml file with metadata. A flat dir repo, by design, only contains files and no metadata.

I would advice to publish the plugin with metadata to the local folder and then use a `maven {}` repository pointing at the local folder. Please see documentation here: 
https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#custom-plugin-repositories

**Comment by brainchild0** [comment]
It has been quite some time since I have looked at this topic, but I seem to recall that much of the confusion resulted from documented claims about the equivalence of two sets of semantics, one deprecated, the other more recent. Since the plugin marker appears outside the build files, requiring its inclusion in the flat directory represents a  more comprehensive  change than simply the semantics in the build file.

**Comment by jjohannes** [comment]
I am not sure what your use case is, but if you have a local plugin the recommended way would be to define it in an included build or buildSrc [as shown in this sample](https://docs.gradle.org/current/samples/sample_convention_plugins.html). Then you don't even need a local repository and don't need to worry about plugin marker artifacts.

**Comment by brainchild0** [comment]
I suppose integrating the source of the target plugin, rather than the distribution,  into the source tree of the outer project would be generally a preferred approach.

The core of this issue, I believe, is that the combination of the documentation and the design have not been optimally friendly to users such as myself, who had had a working tree until trying to migrate away from deprecated patterns. It seems I was led to believe that I could keep the same behavior, and still avoid deprecated semantics, simply by changing the project file, and not other parts of the tree.

If semantics become deprecated, then new semantics should clearly support the same features. If a feature itself becomes deprecated, then the documentation should express the fact and reason for the deprecation, and suggest a preferred usage pattern.

I think the sample you referenced may have value in this scenario, but a major issue is that there was no clear path to finding it from the earlier sequence of experienced in creating my project.
