### ISSUE TITLE
Support for MSVC 17 (Visual Studio "15") - Feature request?

### ISSUE THREAD

**Issue by donalmacc** [gradle/gradle#873]
Visual Studio 2017 was released as a release candidate earlier today. 
Running `gradle build` from "Developer command prompt for VS2017"  fails, currently. 

### Current Behavior
Using the cpp-exe sample, executing `gradle build` fails with the following:
```
C:\Work\cpp-exe>gradle build
:compileMainExecutableMainCpp
Ignoring value 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24629\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24629\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt;' set for environment variable 'INCLUDE'.
Ignoring value 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24629\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24629\lib\x86;C:\Program Files (x86)\Windows Kits\10\UnionMetadata;C:\Program Files (x86)\Windows Kits\10\References;C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;' set for environment variable 'LIBPATH'.
Ignoring value 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24629\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24629\lib\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x86;' set for environment variable 'LIB'.
hello.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory

:compileMainExecutableMainCpp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileMainExecutableMainCpp'.
> A build operation failed.
      C++ compiler failed while compiling hello.cpp.
  See the complete log at: file:///C:/Work/cpp-exe/build/tmp/compileMainExecutableMainCpp/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.266 secs
```

Notably, it's not picking up the VS2017 install. As [posted in the forums](https://discuss.gradle.org/t/automatic-detection-of-visual-studio-community-2015-rc-not-working-properly/10309/4), the directory structure has changed: [Link to blog post](https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/)
### Your Environment
Gradle 3.1, gradle 3.2, MSVC 2017 RC, Windows 10 x64

**Comment by lacasseio** [comment]
Thanks @donalmacc for this feature request. We looked into VS2017 support and it would require more code change to support this version mainly because of the on-disk layout change. We would like to get ahead of the curve with this support. However, this is not a high priority for us as changes to VS2017 could still be coming. We can start the discussion if you want to help out with this support.

**Comment by zxtwonder** [comment]
Since VS2017 is officially released now, is there any possible date for the VisualCpp tool chain to support it?

**Comment by lacasseio** [comment]
Unfortunately @zxtwonder we don't have an ETA on VS2017 support at the present moment.

**Comment by janjoerke** [comment]
Are there any updates on the eta you can share with us. We need Visual Studio 2017 support by the end of this year. I would rather not try to hack a solution by myself, but if you say VS 2017 support is not expected to arrive before 2018 i may have no choice.

**Comment by ghale** [comment]
@janjoerke I'm actually starting on the work for VS2017 support now.  It's too late for 4.3, but I would expect it to be in 4.4 (which should be out before the end of the year).

**Comment by big-guy** [comment]
We're also in the process of migrating native-specific features/bugs onto our [gradle-native](https://github.com/gradle/gradle-native) board.

This issue is being tracked under:
https://github.com/gradle/gradle-native/issues/123
