### ISSUE TITLE
Gradle cannot resolve configurations which include dependencies which contain "task" in the name

### ISSUE THREAD

**Issue by schoeppi5** [gradle/gradle#8733]
### Expected Behavior
If I include a dependency
```gradle
dependencies {
  myConfiguration group: 'com.mycompany', name: 'tasks-task', version: '1.0.0', classifier: 'some-classifier'
}
```

And then try to resolve a configuration like this:
```groovy
configurations.myConfiguration.each {
  println it
}
```
it should work.

### Current Behavior
BUT:
I get an error:

```
* What went wrong:
A problem occurred configuring root project 'tasks-task'.
> Could not resolve all files for configuration ':myConfiguration'.
   > Could not find tasks-task-some-classifier.jar (project :).
```

### Context
This is a huge blocker for me and my colleagues as we currently migrate a domain called "tasks-task" from maven to gradle and can't do so due to this issue.

### Steps to Reproduce (for bugs)
Just implement a dependency which contains "task" in its name and try to resolve a configuration that includes this dependency and run any task.

### Your Environment
I am using Gradle 5.2.1 on Windows 10 and Java 8 (also tried with Java 11). Due to the fact we are developing proprietary software I am not able to provide you any more detailed information.

Thanks in advance for any help on this issue

**Comment by ljacomet** [comment]
As you state in your report, providing a reproducer should be fairly easy.
So could you provide one?

To my knowledge, there is no reason that the name of a dependency would have an impact on its resolution, aside from invalid characters or encoding issues, which is not the case here.

**Comment by schoeppi5** [comment]
Ok so that is weird! Although the original problem is defenetly caused by the *task* in the name, I am currently not abel to reproduce the error as mentioned above. I'm guessing some other factor I don't see yet plays a part here. So I guess this issue, although it still isn't resolved, can be considered closed since I can't tell you guys how to reproduce it.
