### ISSUE TITLE
java.io.IOException in multi-project on Windows 10 - linux works fine

### ISSUE THREAD

**Issue by apj68** [gradle/gradle#8740]
This `settings.gradle` file works in Linux but not in Windows:

    includeFlat "foo:foo", "foo:proja", "foo:projb"

### Expected Behavior

`includeFlat foo:foo` should resolve a directory located adjacent to the master directory, e.g.:

    master/
    foo/
     |-- foo

It does resolve correctly on Linux platform but not Windows 10.

### Current Behavior

Using my current `gradle` installation (v2.2.1), the error comes from `GfFileUtils.java`:

    Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at org.gradle.util.GFileUtils.canonicalise(GFileUtils.java:222)

This also fails with v5.2.1 from a different location:

    > The project name 'foo:foo' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/5.2.1/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).

    * Try:
    Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    * Exception is:
    org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':foo:foo'.
    <snip>
    Caused by: org.gradle.api.InvalidUserDataException: The project name 'foo:foo' must not contain any of the following characters: [/, \, :, <, >, ", ?, *, |]. Set the 'rootProject.name' or adjust the 'include' statement (see https://docs.gradle.org/5.2.1/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
            at org.gradle.util.NameValidator.newInvalidUserDataException(NameValidator.java:45)

### Context

I am trying to specify multiple projects in `settings.gradle`.  From [Settings](https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/Settings.html#includeFlat-java.lang.String...-) documentation for `includeFlat`:

> The supplied name is converted to a project directory relative to the parent directory of the root project directory.

It seems in this case the supplied name is not being converted correctly.

### Steps to Reproduce (for bugs)

To reproduce:

1. Unzip gradle_test.zip
2. cd gradle_test\master
3. Run projects:
    `gradle -i projects`

### Your Environment

This works on linux (`RHEL 6 - 2.6.32-504.8.1.el6.x86_64`) but fails on Windows 10 (`OS Name: Microsoft Windows 10 Enterprise OS Version: 10.0.17134 N/A Build 17134`).

[gradle_test.zip](https://github.com/gradle/gradle/files/2953828/gradle_test.zip)

**Comment by blindpirate** [comment]
Can you please explain which version of Gradle are you using? IIRC, the version you're using on RHEL (which works) is an old version and the version you're using on Windows is a relatively newer version. This behavior was changed in some early 2018 releases.

**Comment by apj68** [comment]
Sorry, you're right, I had some mixed versions.  Here's what I find:

Gradle Version|Windows 10   | RHEL 6
--------------|---------- | -------------
2.13  | Fails               | Works
2.2.1 | Fails               | Works
5.2.1 | Fails               | Fails

Let me know if there's any other info I could provide to help with this.  Thanks!

**Comment by apj68** [comment]
This appears to be a workaround:

    include ':foo:foo', ':foo:proja', ':foo:projb'
    project(":foo:foo").projectDir=file("../foo/foo")
    project(":foo:proja").projectDir=file("../foo/proja")
    project(":foo:projb").projectDir=file("../foo/projb")

As well as this:

    includeFlat ':foo', ':foo:foo', ':foo:proja', ':foo:projb'

Apparently `includeFlat` does not work like `include` with respect to using the last element of the provided argument as the *project name*.  From the `include` documentation:

>The last element of the supplied path is used as the project name. The supplied path is converted to a project directory relative to the root project directory. The project directory can be altered by changing the 'projectDir' property after the project has been included (see ProjectDescriptor.setProjectDir(File))

>As an example, the <span style="background-color: #FFFF00">path `a:b` adds a project with path `:a:b`, name ``b and project directory $rootDir/a/b</span>. It also adds the a project with path \:a, name a and project directory $rootDir/a, if it does not exist already.

So in this case, if I "declare" my intermediate/parent projects first (such as `foo`) then I don't get the path problem.  I don't know if this is as designed or not.  Possibly as a matter of clarity this could be added to `includeFlat` documentation:

 > `includeFlat` will not build intermediate projects.  For example, use `includeFlat :foo, :foo:bar` not `includeFlat :foo:bar`.

Of course, this isn't 100% accurate since it *does* work on Linux, just not Windows.

In any case, I have a workaround so will leave it to the powers-that-be to determine if anything further ought to be done on the Gradle side.
