### ISSUE TITLE
Android Plugin for Gradle 2.2.2 and Gradle version 2.14.1 together failed to download android support v4

### ISSUE THREAD

**Issue by indeeware** [gradle/gradle#875]
Android application build fails with Android Plugin for Gradle 2.2.2 and Gradle version 2.14.1. 
**But build successful with Android Plugin for Gradle 1.2.3 and Gradle version 2.3**

### Expected Behavior
Android application should successfully build in command line with  Android Plugin for Gradle 2.2.2 and Gradle version 2.14.1

### Current Behavior
Android application build fails with Android Plugin for Gradle 2.2.2 and Gradle version 2.14.1. Because it fails to find a symbol in the com.android.support:support-v4:23.2.1. 
Also build fails in the Android Studio with the same reason.

### Context
I had to updated the Android Studio to 2.2.2(Latest) and this must use at least  Android Plugin for Gradle 2.2.2. Therefore I had to update gradle as well. (Tried both gradle 2.14.1 and gradle 3.2) But build fails with the same reason.

### Steps to Reproduce (for bugs)
Have the following settings in the application gradle.build file

```gradle
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
    }
```

Also

```gradle
dependencies {
    compile 'com.android.support:support-v4:23.2.1'
}
```
Android SDK is uptodate
![image](https://cloud.githubusercontent.com/assets/23511041/20370321/3b3a5fca-acb2-11e6-8d19-c81d2a8a02a0.png)

![image](https://cloud.githubusercontent.com/assets/23511041/20370331/4b3bde3a-acb2-11e6-8d16-c068975f2fa0.png)

And run the gradle build.
Build fails and out put's following errors
 error: cannot find symbol
import android.support.v4.app.DialogFragment;
         ^
error: cannot find symbol
import android.support.v4.app.FragmentActivity;

**Comment by eriwen** [comment]
@indeeware Thank you for the thorough description to your problem. Given that this is an import error, I think the likely cause is either a missing declared dependency or possibly a bug in the Android Plugin for Gradle. Have you raised this on the [Android Developers group](https://groups.google.com/forum/#!forum/android-developers) or [StackOverflow](http://stackoverflow.com/)?

If you're certain this is a bug in Gradle, please say what makes you certain of this.

**Comment by indeeware** [comment]
@eriwen Thanks for the response. I don't think it's a missing declare dependency. Because without no any changes to the files build successful with Android Plugin for Gradle 1.2.3 and Gradle version 2.3. Probably a bug in the Android Plugin for Gradle. No I haven't raised anything on the Android Developer group or StackOverflow. I will do that.

**Comment by eriwen** [comment]
@indeeware Were you able to get this solved elsewhere?

**Comment by indeeware** [comment]
@eriwen Nope. I logged this issue in both [Android](https://code.google.com/p/android/issues/detail?can=2&q=227953&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&id=227953) and [StackOverflow](http://stackoverflow.com/questions/40668887/android-plugin-for-gradle-2-2-2-and-gradle-version-2-14-1-together-failed-to-dow), but didn't get an answer.

**Comment by oehme** [comment]
Closing, as this is an Android-specific issue which is better answered on the Android bug tracker.
