### ISSUE TITLE
[Docs] Unclear semantics of @InputFile(s)/Directory annotations

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#8759]
from the docs [here](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/package-summary.html):

- `@InputFile`: will cause the task to be considered out-of-date when the file path or contents have changed.
  **issue 1:** does not specify what happens if the path is a directory. throws exception?
- `@InputDirectory`: will cause the task to be considered out-of-date when the directory location or contents have changed.
  **issue 2:** does not specify what happens if the path is a file. throws exception?
- `@InputFiles`: will cause the task to be considered out-of-date when the file paths or contents have changed.
  **issue 3:** does not specify what happens if some paths are directories. throws exception? i think it doesn't. what then? hashes the path only but not the contents? works as `@InputFile` or `@InputDirectory` for each path depending on the type of item found?

besides improving the docs sometime, could you please clarify here?
almost nothing is specified, so i'm unable to code.

**Comment by wolfs** [comment]
@Lanchon Thank you for reporting. Regarding input file annotations, we have some more documentation in the [user manual](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_annotations) and, for a more concrete example, we also have a [guide](https://guides.gradle.org/implementing-gradle-plugins/#benefiting_from_incremental_tasks).

If you want to suggest a concrete improvement to the doc, we are happy about a pull request.

To answer your questions:
- `@InputFile`: requires the annotated parameter to be a regular file, everything else will throw an exception.
- `@InputDirectory`: requires the annotated parameter to be a directory, everything else throws an exception. The directory and the files in the directory will be checked for changes to the path and the contents.
- `@InputFiles`: works on collection of files or a single file as if all the regular files in the collection are annotated with `@InputFile` and all directories annotated with `@InputDirectory`.

For general questions and discussions how to author build files and write custom plugins, please use the [forum](https://discuss.gradle.org).

**Comment by Lanchon** [comment]
IMHO the API should be de definitive reference, not guides or manuals or tracker issues.

your very complete answer is much appreciated, thank you.
