### ISSUE TITLE
./gradle attempts to execute arbitrary code w/3.2

### ISSUE THREAD

**Issue by techwhizbang** [gradle/gradle#876]
As of the latest Gradle 3.2 release if someone passes along a series of system properties or variables wrapped in single ticks the ./gradle invocation attempts to execute the code. I believe this is due to the introduction of the "eval set" in the gradle script. 

For example:

```sh
~/Downloads/gradle-3.1/bin
 [7] → ./gradle '-DghprbPullTitle="<http://ticket/123456> Upgrade project to gradle 3.2"' clean
Starting a Gradle Daemon (subsequent builds will be faster)

~/Downloads/gradle-3.2/bin
 [12] → ./gradle '-DghprbPullTitle="<http://ticket/123456> Upgrade project to gradle 3.2"' clean
./gradle: line 164: http://ticket/123456: No such file or directory
```

**Comment by wolfs** [comment]
That should be a duplicate of #865. Can you confirm

**Comment by techwhizbang** [comment]
Yes it is a duplicate

**Comment by eriwen** [comment]
Closing as `was:duplicate` of #865
