### ISSUE TITLE
Failed startup of context o.a.g.JettyWebAppContex: about guide(Building Java Web Applications)

### ISSUE THREAD

**Issue by isdux** [gradle/gradle#8761]
### Expected Behavior
when i studing use gradle to build java-web project, i got a problem.
when i excute gradle appRun by gretty, i get a problem "Failed startup of context o.a.g.JettyWebAppContex"

### Your Environment
jdk 11

### Result
i found ,if jdk11,we need gretty 2.3.1 instead of gretty 2.2.0, and special jetty version "9.4.14.v20181114"
and sometime, gretty 's default port is 8080, we need to eddit.

gretty {
    // default 8080
    // serlvetContainer  jetty7/8/9，tomcat7/8
    // contextPath default project name
    httpPort = 9090
    servletContainer = 'jetty9.4'
    jetty94Version = "9.4.14.v20181114"  // hetty94version
    contextPath = 'webdemo'
}

in my opionion, this should appear in gradle guide.thanks.

**Comment by isdux** [comment]
ERROR: Mockito cannot mock this class
you can update the mockito version
testCompile 'org.mockito:mockito-core:2.21.0' instead of 2.7.19.

**Comment by blindpirate** [comment]
This seems nothing to do with Gradle. `gretty` seems to be provided by a 3rd-party plugin so please open an issue in their issue-tracker.

If you think this is something wrong with Gradle, please provide a reproducible sample and steps.
