### ISSUE TITLE
playRun project dependency does not configure task dependency

### ISSUE THREAD

**Issue by tnielens** [gradle/gradle#8764]
In a multi-project setup, the `playRun` dependency configuration does not work for project dependencies.
In my case I have a main play project with some plugin interfaces. Those interfaces are implemented in side projects. I discover plugin implementations by reflection. In my main play project, when I want run it with a specific plugin implementation, I declare a dependency with a `playRun`  project configuration like `dependency { playRun project('pluginImpl')}`, and not plain `play` configuration to avoid circular deps. The task graph is not correctly configured as, when I `runPlayBinary`, the side project jar is not built. I worked around this issue by declaring the task dependency explicitly with `runPlayBinary.dependsOn project.tasks.getByPath(":pluginImpl:jar")`

My gradle version
```------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Linux 4.15.0-46-generic amd64```

**Comment by big-guy** [comment]
Do you have an example you can put into a repo to share?
