### ISSUE TITLE
Newlines in JAVA_OPTS breaks application plugin shell script in Gradle 3.2

### ISSUE THREAD

**Issue by hovenko** [gradle/gradle#877]
When using environment variables with newlines, for instance JAVA_OPTS, then the eval command in the generated application script fails.

### Expected Behavior
I would expect Java application to start when executing the script.

### Current Behavior
The application script fails at eval with:
```
build/install/myapp/application/bin/myapp: eval: line 2: -Xms400m: not found
build/install/myapp/application/bin/myapp: eval: line 3: -Xmx400m: not found
build/install/myapp/application/bin/myapp: eval: line 4: -classpath: not found
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
[...]
```

Fails with exit code 1

### Steps to Reproduce (for bugs)

```bash
$ ./gradlew installDist
$ export JAVA_OPTS="
        -Xms400m
        -Xmx400m
   "
$ ./build/install/myapp/application/bin/myapp
```

### Your Environment
```bash
$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

```bash
$ ./gradlew -v

------------------------------------------------------------
Gradle 3.2
------------------------------------------------------------

Build time:   2016-11-14 12:32:59 UTC
Revision:     5d11ba7bc3d79aa2fbe7c30a022766f4532bbe0f

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Linux 3.16.0-4-amd64 amd64
```

Worked correctly in Gradle 3.1

**Comment by wolfs** [comment]
Should be fixed by #865 - could you try out the workaround (editing the wrapper script by hand) there?

**Comment by hovenko** [comment]
Tried to apply the patch from https://github.com/gradle/gradle/commit/a171b72b0973ace7b1f9c17551654c0de1ca49e2, but it still fails with the same result.

It's not the APP_ARGS that fails in my case.

It looks to be the eval line below the patch:
```bash
eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$MYAPP_OPTS" -classpath "\"$CLASSPATH\"" myapp.Main "$APP_ARGS"
```

**Comment by eriwen** [comment]
@hovenko Thank you for the well-written issue. 

@jjohannes Can you please confirm this is still an issue or let me know if you need my team to address it?

**Comment by jjohannes** [comment]
Yes it is an issue with JVM options defined in one of the environment variables - `"$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$MYAPP_OPTS"` - using newlines.


Defining the arguments without newlines. E.g.:
```
export JAVA_OPTS="-Xms400m  -Xmx400m"
```

or

```
export JAVA_OPTS="'-Xms400m'  '-Xmx400m'"
```

would work.

I am looking into this now.

**Comment by jjohannes** [comment]
The fix is on `master`: https://github.com/gradle/gradle/commit/b0fb42928c9d95a389962e2252e8efb0fe0b9fde

**Comment by jjohannes** [comment]
@hovenko can you check if the following change (removing quotes in the line you pointed out above) fixes your issue.

```
eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$MYAPP_OPTS" -classpath "\"$CLASSPATH\"" myapp.Main "$APP_ARGS"
```
replace with
```
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $MYAPP_OPTS -classpath "\"$CLASSPATH\"" myapp.Main "$APP_ARGS"
```

**Comment by hovenko** [comment]
@jjohannes Thanks, works perfectly! :)
