### ISSUE TITLE
Parallel build doesn't respect task order (extra configuration)

### ISSUE THREAD

**Issue by andilem** [gradle/gradle#8771]
We have a relatively large multi-project (~100 subprojects) where project :c has an implementation dependency on project :s (and :s has an api dependency on project :b and :b has api dependencies on many other projects, but this probably doesn't matter).
Project :c has an additional configuration ("fatjar") and a task fatJar(type: jar) which produces that jar and also includes the normal jar content ("with jar").

When running the gradle build with --no-parallel, everything works as expected and the tasks are executed in the correct order, but when running the build with --parallel, it may happen that the tasks are executed in the wrong order and the build fails. This is not really reproducable, but it my fail on the CI server 10 times in a row (or it might work for weeks).
Here is a log extract which shows that the tasks are not executed in the correct order:
```
> Task :b:jar
> Task :b:assemble
> Task :b:compileTestJava
> Task :b:processTestResources NO-SOURCE
> Task :b:testClasses
> Task :s:compileJava
> Task :c:compileJava   // first problem - why is c started when s:jar is not yet available?
> Task :c:processResources NO-SOURCE
> Task :c:classes
> Task :c:fatJar FAILED   // fails because s.jar is not yet available
> Task :c:jar
> Task :c:compileTestJava NO-SOURCE
> Task :c:processTestResources NO-SOURCE
> Task :c:testClasses UP-TO-DATE
> Task :s:processResources NO-SOURCE
> Task :s:classes
> Task :s:jar   // only after this task is s.jar available
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':c:fatJar'.
> Cannot expand ZIP '/(censored)/s/build/libs/s.jar' as it does not exist.
```
From my observations, it happens only when having an additional configuration which extends the implementation and/or api configuration, but I'm not sure about this.

**Comment by big-guy** [comment]
How are you adding s.jar's contents to the fatjar?  Could you distill your build down into an example project?

**Comment by andilem** [comment]
My :c build.gradle looks something like this:
```
configurations {
    fatjar {
        extendsFrom implementation
        exclude group: 'org.osgi'
        // more excludes
    }
}

dependencies {
    implementation project(':s')
   // more implementation deps (external jars)
}

task fatJar(type: Jar) {
    archiveName = "c_fat.jar"
    manifest {
        attributes 'Main-Class': 'xxx'
    }
    from { configurations.fatjar.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
assemble.dependsOn fatJar
```
I will try to create an example project, but as said, that is a little bit complicated because the issue is not really reproducible.

**Comment by big-guy** [comment]
This is the bit that's breaking it:
```
...
    from { configurations.fatjar.collect { it.isDirectory() ? it : zipTree(it) } }
...
```

This collect turns the configuration (with dependency information) into a collection of files (no dependency information).  This is a common gotcha.

Try adding inside `fatJar`: `dependsOn configurations.fatjar`

**Comment by andilem** [comment]
Thank you, that was the reason... I should have read the javadoc which says that accessing a configuration as FileCollection does not resolve it.
