### ISSUE TITLE
Weird/buggy null handling in implementation of DirectoryProperty 

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#8774]
### Expected Behavior
`DirectoryProperty` implementations should be settable to null because they are `Property<Directory>`s and properties can be set to null according to the `Property` contract.

### Current Behavior
Weird inconsistent behavior depending on which setter is invoked:
```
dir = project.layout.directoryProperty()
dir.set ((Directory) null)   // correctly sets dir to null
dir.set ((File) null)        // WTF... throws NPE!
```

### Context
I can't use `DirectoryProperty` in my plugin. I expected it to be nullable given that it is a `Property<T>`; I'll have to rewrite my plugin to use `Property<Directory>` instead or provide a wrapper for `DirectoryProperty`.

`RegularFileProperty` might be affected by the same issue.

### Your Environment
Tested on Gradle 4.3 through 4.10.3

**Comment by adammurdoch** [comment]
Thanks for reporting. These methods should work the same way WRT `null` and it's a bug that they don't.

**Comment by Lanchon** [comment]
On top of that, i hope nulls are intended to be accepted, because i am depending on that.

**Comment by adammurdoch** [comment]
Do you have some examples of what you'd like to use nulls for? This will help with evolving the APIs.

**Comment by big-guy** [comment]
@adammurdoch the buggy behavior is fixed in https://github.com/gradle/gradle/commit/796504edffe1d4b8c085cbb37edbbc848d2c9a73

**Comment by Lanchon** [comment]
sure. i've got
- tasks for various tools you can instantiate if they are in the build path,
- a base plugin with extensions that brings in the tasks and configure them with defaults from the extensions when you instantiate them,
- and several opinionated plugins that include the base plugin and establish and further configure task chains for specific purposes.

the opinionated plugins configure themselves some task properties that are necessary for the chain to work, while leaving others connected to the defaults in the extensions.

all is good for now. but there are some chain task properties that must be empty (null) for some chains to work. leaving those properties connected to the defaults in the extensions is brittle. for even if the default value for the extension defaults is null, as soon as those defaults are changed in the extensions the affected chains would cease to work.

the correct way is for the opinionated plugins to break the connection imposed by the base plugin for those task properties that it crucially needs to be empty. hence the need to set some task properties to empty (null) when their previous values were references to mirrors default properties in plugin extension objects.

hope this is clear enough.
