### ISSUE TITLE
Dependencies disappear from lockfiles when updating Gradle from 4.10.1 to 5.0

### ISSUE THREAD

**Issue by beatrizz** [gradle/gradle#8779]
We're using dependency locking in an Android project. We're trying to update Gradle from 4.10.1 to 5.0 and we've seen that the lockfiles that store the locked configuration changed when we updated Gradle: some transitive dependencies of the Fresco library disappeared from the lockfiles.

Note: We were initially trying to update to the latest version of Gradle, but we've narrowed the problem down to the 4.10.1 --> 5.0 update.

This is reproducible in the sample project attached.

### Expected Behavior
The lockfiles don't change when updating Gradle.

### Current Behavior
The lockfiles change when updating Gradle.

Before the update, the Fresco-related dependencies are:
```
com.facebook.fresco:animated-base:1.13.0
com.facebook.fresco:animated-drawable:1.13.0
com.facebook.fresco:animated-gif:1.13.0
com.facebook.fresco:drawee:1.13.0
com.facebook.fresco:fbcore:1.13.0
com.facebook.fresco:fresco:1.13.0
com.facebook.fresco:imagepipeline-base:1.13.0
com.facebook.fresco:imagepipeline:1.13.0
com.facebook.fresco:nativeimagefilters:1.13.0
com.facebook.fresco:nativeimagetranscoder:1.13.0
com.facebook.soloader:soloader:0.6.0
com.parse.bolts:bolts-tasks:1.4.0
```

After changing the version in `gradle-wrapper.properties` and updating the locks, they are:
```
com.facebook.fresco:animated-gif:1.13.0
com.facebook.fresco:drawee:1.13.0
com.facebook.fresco:fbcore:1.13.0
com.facebook.fresco:fresco:1.13.0
com.facebook.fresco:imagepipeline-base:1.13.0
com.facebook.fresco:imagepipeline:1.13.0
com.facebook.fresco:nativeimagefilters:1.13.0
com.facebook.fresco:nativeimagetranscoder:1.13.0
```

The first two and the last two dependencies have disappeared.

However, they're correctly listed when running `./gradlew app::dependencies`, before and after the update:
```
+--- com.facebook.fresco:fresco:1.13.0
|    +--- com.facebook.fresco:fbcore:1.13.0
|    +--- com.facebook.fresco:drawee:1.13.0
|    |    +--- com.facebook.fresco:fbcore:1.13.0
|    |    \--- com.facebook.fresco:imagepipeline:1.13.0
|    |         +--- com.facebook.fresco:imagepipeline-base:1.13.0
|    |         |    +--- com.facebook.soloader:soloader:0.6.0
|    |         |    +--- com.parse.bolts:bolts-tasks:1.4.0
|    |         |    \--- com.facebook.fresco:fbcore:1.13.0
|    |         +--- com.facebook.soloader:soloader:0.6.0
|    |         +--- com.parse.bolts:bolts-tasks:1.4.0
|    |         \--- com.facebook.fresco:fbcore:1.13.0
```

### Context
We're using dependency locking because we want to make sure we don't accidentally update libraries. If some dependencies are missing from the locked configurations, we may accidentally upgrade or downgrade them without testing the change.

We've checked this by forcing the SoLoader version to be 0.5.0 (Fresco uses 0.6.0). Before the Gradle update, there was an error because the version we were forcing didn't match the locked version. After the Gradle update, we were able to use SoLoader 0.5.0 without any errors.

### Steps to Reproduce (for bugs)
In the attached project (or any project that uses `com.facebook.fresco:fresco` and `com.facebook.fresco:animated-gif`), update the Gradle version in `gradle-wrapper.properties`. The project can't be built until the locks are updated and 4 dependencies disappear when you do so.

You can force SoLoader to be 0.5.0 by adding this to `app/build.gradle`:
```
project.configurations.all { configuration ->
    resolutionStrategy {
        force 'com.facebook.soloader:soloader:0.5.0'
    }
}
```

With Gradle 4.10.1, you won't be able to build the project if you force the SoLoader version to be 0.5.0 because the version you're forcing and the locked version mismatch. However, with Gradle 5.0, you can build the project if you force the SoLoader version to be 0.5.0 because there's no locked version.

### Your Environment
 * Build scan URL before the update: https://gradle.com/s/ceaqvgd5qgnxe
 * Build scan URL after the update: https://gradle.com/s/5piv5ksebgn6s

Hopefully you can get all the details from the attached sample project. Here are some:
* Gradle: 4.10.1 (without bug) and 5.0 (with bug)
* Android Gradle Plugin: 3.3.2
* Fresco: 1.13.0

[FrescoSample.zip](https://github.com/gradle/gradle/files/2967817/FrescoSample.zip)

**Comment by melix** [comment]
My first guess is that you are just facing [this](https://twitter.com/gradle/status/1106176824504209408). Would you mind checking?

**Comment by ljacomet** [comment]
That's exactly the problem as can be seen in [the POM](https://repo.maven.apache.org/maven2/com/facebook/fresco/fresco/1.13.0/fresco-1.13.0.pom) for `fresco:1.13.0`.

And because `soloader` is a `runtime` dependency, the locking does not complain about the force since that dependency does not even enter the graph and so it does not have a version.

Closing as this is an expected step of the 5.0 migration.

**Comment by beatrizz** [comment]
Thank you both for the explanation! That was the issue. We're now locking the runtime dependencies and the lockfiles include all we expected.

**Comment by ljacomet** [comment]
Just to make sure you are locking the right configuration, you should be locking `runtimeClasspath` as this is what reflects best the whole set of dependencies, irrelevant of the configuration bucket one is added.
See [this documentation](https://docs.gradle.org/5.2.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) for details.

**Comment by beatrizz** [comment]
Thanks! We were locking compileClasspath and we've changed it to runtimeClasspath.
Apologies for opening an issue when we just hadn't understood what was different after the update. You've saved us a lot of time :)
