### ISSUE TITLE
Document or facilitate "subdirectory" definition with directory providers

### ISSUE THREAD

**Issue by melix** [gradle/gradle#8781]
### Context

My use case was to be able to create two providers for subdirectories of a directory provider. For example, my task wants to create 2 different directories under `build`. I intuitively expected something like this to be possible:

```
val topLevel = project.layout.buildDirectory.dir("top")
val sub1 = topLevel.dir("sub1")
val sub2 = topLevel.dir("sub2")
```

However, `topLevel` is of type `Provider<Directory>`, not `DirectoryProvider`, so you can't use this pattern. The solution suggested by @big-guy was to do this:

```
val topLevel = project.objects.directoryProperty().convention(project.layout.buildDirectory.dir("top"))
val sub1 = topLevel.dir("sub1")
val sub2 = topLevel.dir("sub2")
```

which isn't super obvious (a bit verbose, and you have to "look" at 2 different places: `project.objects` and `project.layout`).

Minimally, this should be documented.

**Comment by lacasseio** [comment]
I think you could also use the `Provider#map` method to transform with `Directory#dir`.
