### ISSUE TITLE
disable boolean in plugin

### ISSUE THREAD

**Issue by kheerthi** [gradle/gradle#8782]
When using @option to accept values from user for a plugin, currently if a boolean variable is declared as false plugin, it can be enabled by passing --variable. However, since the variable needs to be true in most case and needs to be disabled on demand. How can this operation be performed from a consuming project?

**Comment by big-guy** [comment]
My suggestion would be to invert the boolean so that it's false by default. You can have the option name be "no-variable", so someone would pass `--no-variable` on the command-line.
