### ISSUE TITLE
Scala plugin is not compatible with `java-library` plugin

### ISSUE THREAD

**Issue by dsilvasc** [gradle/gradle#8788]
The `scala` plugin does not expose the correct variants for consumption by the `java-library` plugin. When a `java-library` plugin project has a project dependency on a `scala` project, it results in "unable to resolve class" errors when trying to compile the `java-library` project.

This is a [documented "known issue" with the java-library plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_known_issues_compat), which should be fixed.

This issue is a copy of https://github.com/gradle/gradle/issues/7398 but for Scala instead of Groovy.

**Comment by dsilvasc** [comment]
Here's the fix for the groovy plugin: https://github.com/gradle/gradle/pull/8229

**Comment by ljacomet** [comment]
Should be addressed by #9872
