### ISSUE TITLE
`<fileInstance> as Directory` breaks groovy's type system

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#8793]
### Expected Behavior
`<fileInstance> as Directory` should fail to compile or produce an appropriate `Directory` object.

### Current Behavior
`<fileInstance> as Directory` produces a runtime object on which `instanceof Directory` evaluates to `true` but still none of the `Directory` methods can be invoked on it.

### Context
i just spent over a day debugging a module that uses a Provider<Directory> created by another module. the provided object seemed to be a `Directory` at runtime, so i rewrote and tried all sorts of language workarounds on my using module, which was not to blame for the issue.

this is probably a Groovy bug. but it is very tempting to attempt to create a `Directory` by trying `<fileInstance> as Directory` and seeing if it compiles instead of going through the docs. so maybe you should explicitly disallow such conversions somehow (ideally at compile time; otherwise throwing at the conversion point).

### Steps to Reproduce (for bugs)
```
@CompileStatic
File test() {
    Directory wtf = (new File("/xxx")) as Directory
    System.println "instanceof Directory: " + (wtf instanceof Directory)
    return wtf.getAsFile()
}
```

invoking test() produces:
```
instanceof Directory: true
groovy.lang.MissingMethodException: No signature of method: java.io.File.getAsFile() is applicable for argument types: () values: []
Possible solutions: isFile(), eachFile(groovy.lang.Closure), eachFile(groovy.io.FileType, groovy.lang.Closure), getName()
```

### Your Environment
Gradle 4.10.3
Groovy bundled in Gradle

**Comment by big-guy** [comment]
Groovy's trying to be helpful and generating a dynamic object that implements `Directory` and tries to delegate through to the underlying `File` as if `File` implemented `Directory`.  I don't think that this would have ever worked, so I'm not sure if it's important to explicitly prevent it.  It's a common pattern that you do not need to create instances of Gradle types (which is what `as` would have to do). 

I'm a little unclear what you're trying to do.   What did you finally get to work?

**Comment by Lanchon** [comment]
> I'm a little unclear what you're trying to do. What did you finally get to work?

i'm writing a big plugin. yes i got it to work. the problem is all the time i lost diagnosing the issue. better diagnosis would have helped me a lot instead of weird behavior.

> It's a common pattern that you do not need to create instances of Gradle types

yes. i should ve reasoned that there was no context available (eg: project) in File for it to auto convert to Directory via some Gradle provided code. but i didn´t think, so i was bitten by this.

**Comment by Lanchon** [comment]
i'm new to Groovy and although it's an interesting thing, it is very much spoiled by its failure to abide by the "what you don't know won't hurt you" principle. i guess most people will try to use Groovy as "a better Java", but will get hurt by stuff like x == null vs x.is(null), ((Integer) 0) ?: 42 returning 42, meta objects, and a million others.

**Comment by big-guy** [comment]
I'm going to close this since I don't think we're going to do anything special here to prevent this in particular.
