### ISSUE TITLE
JacocoMerge/JacocoReport: avoid eager task realization when executionData(TaskCollection tasks) is used

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#8794]
### Expected Behavior

```Kotlin
// Register a task, every other task would add relevant configurations later
val jacocoMerge by tasks.registering(JacocoMerge::class);

val jacocoReport by tasks.registering(JacocoReport::class) {
    group = "Coverage reports"
    description = "Generates an aggregate report from all subprojects"
    executionData(jacocoMerge)
}

// ^^^ the above works

// vvv below fails
...
allprojects {
  plugins.withType<JacocoPlugin> {
    jacocoMerge {
      executionData(tasks.withType<Test>()) // <-- this line fails
    }
  }
}
```

### Current Behavior

```
> Could not create task ':jacocoMerge'.
   > DefaultTaskCollection#all(Action) on task set cannot be executed in the current context
```

In other words, `executionData(TaskCollection)` invokes `tasks.all` which is forbidden in task configure method.

### Context

I'm trying to create an aggregate jacoco report that supports "configuration avoidance"

### Workaround

```
    jacocoMerge {
      val testTasks = tasks.withType<Test>()
      // Note: this assumes exec are always Jacoco output files. Optional testTasks.matching could be used to filter tasks
      // Note: this creates a lazy collection
      // Some of the projects might fail to create a file (e.g. no tests or no coverage),
      // So we check for file existence. Otherwise JacocoMerge would fail
      val execFiles = files(testTasks).filter { it.name.endsWith(".exec") }
      executionData(execFiles)
    }
```

**Comment by vlsi** [comment]
The same issue happens when JacocoReport is used alone.

### Expected Behavior

```kotlin
val jacocoReport by tasks.registering(JacocoReport::class) {
    group = "Coverage reports"
    description = "Generates an aggregate report from all subprojects"
}

allprojects {
    plugins.withType<JacocoPlugin> {
        jacocoReport {
            executionData(tasks.withType<Test>())
        }
```

### Workaround

```kotlin
...
    plugins.withType<JacocoPlugin> {
        jacocoReport {
            // Note: this creates a lazy collection
            // Some of the projects might fail to create a file (e.g. no tests or no coverage),
            // So we check for file existence. Otherwise JacocoMerge would fail
            val execFiles = files(testTasks).filter { it.exists() && it.name.endsWith(".exec") }
            executionData(execFiles)
        }
```

**Comment by NielsDoucet** [comment]
Ran into this issue today as well. Any plans to fix this?

**Comment by pantherdd** [comment]
How is the [`JacocoReportBase#executionData(org.gradle.api.tasks.TaskCollection)`](https://docs.gradle.org/current/javadoc/org/gradle/testing/jacoco/tasks/JacocoReportBase.html#executionData-org.gradle.api.tasks.TaskCollection-) method supposed to be used then?

I ran into this by simply calling it like this:
```kts
tasks.jacocoTestReport {
    executionData(tasks.withType<Test>())
}
```

**Comment by pantherdd** [comment]
What's wrong with [`JacocoReportBase#executionData(Task...)`](https://docs.gradle.org/current/javadoc/org/gradle/testing/jacoco/tasks/JacocoReportBase.html#executionData-org.gradle.api.Task...-)? Please don't deprecate it, that's the only one I can use now, like so:
```kts
tasks.jacocoTestReport {
    tasks.withType<Test>().forEach { executionData(it) }
}
```
Though of course this isn't great, because I need to realize all the `Test` tasks for it to work, but at least it's possible.

What we would need instead of deprecating the existing methods is:
* A new `JacocoReportBase#executionData(Provider<Task>...)` overload that would save the provider and only query it when necessary
* Improve `JacocoReportBase#executionData(TaskCollection)` to save the collection itself instead of calling `#all(Action)` on it, and resolve it to individual tasks as late as possible

**Comment by rkrisztian** [comment]
I can confirm the workaround works in the root project too:

```groovy
plugins {
	id 'jacoco'
}

allprojects {
	repositories {
		// ... (This block is needed so `org.jacoco:org.jacoco.ant:0.8.7` can be resolved.)
	}
}

tasks.register('jacocoMergedReport', JacocoReport) {
	subprojects {
		pluginManager.withPlugin('jacoco') {
			sourceSets sourceSets.main
			classDirectories.from sourceSets.main.output
                        // `executionData tasks.withType(Test)` should work but it doesn't...
			executionData files(tasks.withType(Test)).filter { it.name.endsWith('.exec') && it.exists() }
			dependsOn tasks.withType(Test)
		}
	}

	reports {
		xml {
			enabled = true
			outputLocation = file "$buildDir/reports/jacoco/report.xml"
		}
		html {
			enabled = true
			outputLocation = file "$buildDir/reports/jacoco/html"
		}
	}
}
```

=> Now I see why the root project should define a repository. Without the jacoco plugin loaded, there is no JacocoAnt, so the Jacoco task would miss it on the classpath:

```none
  - Type 'org.gradle.testing.jacoco.tasks.JacocoReport' property 'jacocoClasspath' doesn't have a configured value.
```

Knowing this, I will soon try again with the aggregation plugin.

**Comment by rkrisztian** [comment]
`executionData tasks.withType(Test)` works for me in Gradle 8.1.1.
