### ISSUE TITLE
Links in v3.5 user guide jumps to current version instead

### ISSUE THREAD

**Issue by jjkavalam** [gradle/gradle#8798]
### Expected Behavior

Links in https://docs.gradle.org/3.5/userguide/userguide.html should link to documentation about v3.5

### Current Behavior

Certain links (perhaps the majority of them) in the  https://docs.gradle.org/3.5/userguide/userguide.html point to documentation about the "current" version (which at the time of reporting this issue is v5.x)

### Context

I am trying to get some information about Gradle 3.5 and due to this issue cannot find a way to get to that. I end up with documentation about a different version.

### Steps to Reproduce (for bugs)

1. Open https://docs.gradle.org/3.5/userguide/userguide.html  in the browser
2. Click on the link : "Using the Gradle Command-Line" 

Browser navigates to https://docs.gradle.org/current/userguide/command_line_interface.html (this page is about v5.x) !

### Your Environment

Chrome 65

**Comment by big-guy** [comment]
I think this has something to do with some redirects and/or renamed chapters we've had over time.

As a workaround, I can suggest using https://docs.gradle.org/3.5/userguide/userguide_single.html
