### ISSUE TITLE
[RFE] Add `ProviderFactory.singletonListProvider` and/or `HasMultipleValues.setSingleton`

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#8804]
### RFE

Add convenience method to `ProviderFactory` (with default implementation):
```
<T> Provider<List<T>> singletonListProvider​(Callable<? extends T> value)
```

And/or add to `HasMultipleValues<T>` (with default implementation):
```
void setSingleton(T value)
void setSingleton(Provider<? extends T> provider)
```

Both are useful, favor second form for usability, first form for generality.

And while we are on topic, maybe also consider adding these two:

`ProviderFactory`:
```
<T> Provider<List<T>> emptyListProvider​()
```

`HasMultipleValues<T>`:
```
void setEmpty()
```

### Context
this is handy to connect tasks, say a `ListProperty<RegularFile>` input to a `RegularFileProperty` output. this should be common enough to warrant convenience.

**Comment by big-guy** [comment]
Can you provide a bit more detail on how you think you'd use this?  Do you have any examples you can share?

**Comment by Lanchon** [comment]
see the 'context' section above. i've made many tasks with ’ListProperty<RegularFile>’ inputs. i think it's more idiomatic than ’Property<FileCollection>’. am i being a heretic of some sort?

**Comment by Lanchon** [comment]
(eg: a tool that takes several dalvik executables as input. each might be a .dex file. but because of the multi-dex nightmare, each might also be a .jar, or an .apk, or even a directory containing 'classes<n>.dex' files. so each item is actually a `FileSystemLocation`.)

**Comment by big-guy** [comment]
In that specific example, I wouldn't use `ListProperty<FileSystemLocation>`. I would use a `ConfigurableFileCollection`.  `Property<FileCollection>` would be a bit like `Property<Provider<thing>>` and would add an unnecessary "lazy" layer. 

But even if you were using `ListProperty<FileSystemLocation>`, I'm not sure why you need a `singletonListProvider` or `emptyListProvider`.

I think you could do something like this without any new API:
```
class Consumer extends DefaultTask {
    ListProperty<FileSystemLocation> inputs
    ...
}

class Producer extends DefaultTask {
    RegularFileProperty output
    ...
}

task producer1(type: Producer)
task producer2(type: Producer)
task producer3(type: Producer)

task consumer(type: Consumer) {
    inputs.add(producer1.output)
    inputs.add(producer2.output)
    inputs.add(producer3.output)
}
```
which I think should just be:
```
class Consumer extends DefaultTask {
    ConfigurableFileCollection inputs
    ...
}

class Producer extends DefaultTask {
    RegularFileProperty output
    ...
}

task producer1(type: Producer)
task producer2(type: Producer)
task producer3(type: Producer)

task consumer(type: Consumer) {
    inputs.from(producer1.output)
    inputs.from(producer2.output)
    inputs.from(producer3.output)
}
```

In the case where a Producer is producing several outputs, they could expose a `FileCollection` output that would work in a similar way.

**Comment by Lanchon** [comment]
thanks so much!!

> `Property<FileCollection>` [...] would add an unnecessary "lazy" layer.

point taken.

so among `FileCollection` and `ListProperty<? extends FileSystemLocation>` you recommend the former. i thought `FileCollection` was sort of deprecated the same way `File` is: because contents are not strongly modeled, and also because items there could potentially be relative to an unspecified root (or could they?).

but i get it, the Gradle way is `? extends FileCollection` so i suppose i'll migrate to that form.

thanks again!

**Comment by big-guy** [comment]
> so among FileCollection and ListProperty<? extends FileSystemLocation> you recommend the former. i thought FileCollection was sort of deprecated the same way File is: because contents are not strongly modeled, and also because items there could potentially be relative to an unspecified root (or could they?).

Not deprecated, the modeling is just around a "collection of file-like things", so you can have a mixture of `File`, `RegularFile`, `Provider`s of the same, etc.

You can create a `ConfigurableFileCollection` from `ObjectFactory.fileCollection()` (5.3+) or `Project.files()`.

**Comment by Lanchon** [comment]
FYI,

```
RegularFileProperty output
ListProperty<FileSystemLocation> inputs

inputs.set output.<List<RegularFileProperty>>map { [ it ] }
```

that fails at runtime when gradle wants to persist the properties for later up-to-date checks. don't have the time to investigate, but first though was that the `[ ... ]` literal is not serializable, which seems like too conspicuous an omission on Groovy's part; i hardly believe it. but if true, someone should report it.

**Comment by big-guy** [comment]
I think that's overcomplicating it.  You probably just want:
```
inputs.add(output)
```
which adds to the list or if you really only want to have the single element:
```
inputs.empty().add(output)
```

If you unravel `inputs.set output.<List<RegularFileProperty>>map { [ it ] }`, you'll get
```
Provider<List<RegularFileProperty>> mapped = output.<List<RegularFileProperty>>map { [ it ] }
inputs.set(mapped)
```
There are a few strange things here:
- `inputs.set` would accept something like `Provider<List<RegularFile>>`, not the type of mapped, which is a bit like a `Provider<List<Provider>>`.
- the `it` is a RegularFile, so you're actually returning a `List<RegularFile>` from the `map` and that turns into a `Provider<List<RegularFile>>`.
- You're using a list for a single element (List would make `add` seem more appropriate).

**Comment by Lanchon** [comment]
sorry, i meant `output.<List<RegularFile>>map`, that was a typo. i was just letting you know about the non-serializability of the obvious map solution to singletons.

for the rest of your info: i got it the first time, yes, i'll use `? extends FileCollection` for multi-valued inputs/outputs.

thanks again!

**Comment by Lanchon** [comment]
btw, your info on the recommended way of doing 'new style'  multivalued properties is much appreciated. i think it should be part of the lazy initialization guide.

but...

i think i might stick to `ListProperty<FileSystemLocation>` inputs in some cases after all.

why?

i made a [dex bytecode patcher](https://dexpatcher.github.io/) [tool](https://github.com/DexPatcher/dexpatcher-tool/releases) that can apply arbitrary patch files to a dex executable. reading and writing dex takes a lot of time (say 95% of total tool run time), so the tool can actually apply several patches one after the other in one go, avoiding the work of writing and reading back intermediate files.

now, two observations regarding the patch list input to the tool's task:
1) each patch is also a dex executable. it can be expressed as `some-patch.dex`, or due to multi-dex `some-patch.jar` or `some-patch/classes<n>.dex`. `FileSystemLocation` expresses this file/dir reality nicely.
2) patches are not commutative: if there are multiple patches to apply, they have to be applied in a specified order. `(Configurable)FileCollection` does not immediately conveys the idea that ordering exists at all. even though the implementation may conserve ordering (does it?), the API docs -i think- do not specify it, which is bad for me.

with a strong emphasis on "2." above, i'm leaning towards keep using `ListProperty<FileSystemLocation>` for patch list inputs. what do you think?

**Comment by Lanchon** [comment]
>  I think should just be:
```
class Consumer extends DefaultTask {
    ConfigurableFileCollection inputs
    ...
}

class Producer extends DefaultTask {
    RegularFileProperty output
    ...
}

task producer1(type: Producer)
task producer2(type: Producer)
task producer3(type: Producer)

task consumer(type: Consumer) {
    inputs.from(producer1.output)
    inputs.from(producer2.output)
    inputs.from(producer3.output)
}
```

1. ok, but i'll make my `ConfigurableFileCollection` and `RegularFileProperty` fields **final**. seems like property content should change, not the property implementation itself. please advise if you think this is bad practice for `ConfigurableFileCollection`.
2. does `consumer` get an implicit `dependsOn [ producer1, producer2, producer3 ]` via ts `ConfigurableFileCollection`, similarly to what it would get from a `Property<>`?

**Comment by big-guy** [comment]
> ok, but i'll make my ConfigurableFileCollection and RegularFileProperty fields FINAL. seems like property content should change, not the property implementation itself. please advise if you think this is bad practice for ConfigurableFileCollection.

Yes, these should be final.  I left it off for brevity. 

> does consumer get an implicit dependsOn [ producer1, producer2, producer3 ] via its ConfigurableFileCollection, similarly to what it would get from a Property<>?

Yes, if they're marked as `@InputFiles`.

**Comment by Lanchon** [comment]
> Yes, if they're marked as @InputFiles.

thanks! they are.

FYI,
so in the end i converted most tasks to `ConfigurableFileCollection` inputs except for the patcher task that depends on input file ordering. for that task i defined redundant properties of which only one can be set or the task will fail:

```
    @Optional @InputFiles final Property<FileSystemLocation> patch
    @Optional @InputFiles final ListProperty<FileSystemLocation> patches
```

the convenience `patch` property gets used 99% of the time, with `patches` available for special cases.

thanks again!

**Comment by lacasseio** [comment]
If I'm not mistaken, the `ConfigurableFileCollection` should be deterministic which means the input file ordering should as expected.
