### ISSUE TITLE
Fail build on Checkstyle Warning Violation

### ISSUE THREAD

**Issue by jsotuyod** [gradle/gradle#881]
This was https://issues.gradle.org/browse/GRADLE-2888, reported against Gradle 1.7, and still present in 3.2

### Expected Behavior
When only violations of severity warning are found, Checkstyle will not ignore them.

At the very least, the message `Checkstyle rule violations were found. See the report at: file://....` will be shown as part of the output.

If configured to `ignoreFailures = false` it will fail the build too. Bonus points for being able to configure Checkstyle's `maxErrors` and `maxWarnings` thresholds for failure.

### Current Behavior
The message is only shown if there is at least 1 violation of severity error.

Builds will only fail when `ignoreFailures = false` if there is at least 1 violation of severity error.

### Context
The very idea of configuring Checkstyle is to ensure code quality rules. Having them silenced makes it effectively useless.

Having separate severities makes sense, and it's true we may not want all violations to break the build, but still the "violations found" message would be appreciated. Checkstyle understands this, and exposes 2 config values `maxErrors` and `maxWarnings` to define the threasholds for each violation type.

Recently, https://github.com/gradle/gradle/pull/780 added support for `maxErrors`, though `maxWarnings` is still missing, and the current implementation would still mean that if there are not at least `maxErrors` violations of severity error, the "violations found" message would not be logged at all.

### Your Environment
Linux, MacOS

**Comment by eriwen** [comment]
Thank you for moving it @jsotuyod. It had 8 votes on JIRA.

**Comment by joffrey-bion** [comment]
Adding here the current workaround mentioned by David Byron for this issue:

    tasks.withType(Checkstyle).each { checkstyleTask ->
        checkstyleTask.doLast {
            reports.all { report ->
                def outputFile = report.destination
                if (outputFile.exists() && outputFile.text.contains("<error ")) {
                    outputs.upToDateWhen { false }
                    throw new GradleException("There were checkstyle warnings! For more info check $outputFile")
                }
            }
        }
    }

**Comment by dbyron0** [comment]
Thanks.  That's me.  Turns out I commented out the `outputs.upToDateWhen { false }` line since it caused trouble:

```
Execution failed for task ':checkstyleMain'.
> Cannot call TaskOutputs.upToDateWhen(Closure) on task ':checkstyleMain' after task has started execution.
```

**Comment by joffrey-bion** [comment]
Thanks @dbyron0 for the reply, I edited to avoid confusing readers. In fact I had removed that line in my project too.

**Comment by alex-arana** [comment]
I've updated #780 to include support for maxWarnings.

**Comment by eriwen** [comment]
This has been fixed with #780.

**Comment by jsotuyod** [comment]
@eriwen actually it's not. #780 does an important part in exposing `maxErrors` and `maxWarnings`,  but the message indicating violations were found is only displayed if `maxErrors` or `maxWarnings` violations of the proper severity have been found.

The message should be printed always a violation of any severity has been found even if the build is not failed.

**Comment by eriwen** [comment]
@jsotuyod To rephrase what's still missing: You want a warning log message if there were any warnings or errors detected. I'll reopen this and think about it. Pull requests welcome, too ;)

**Comment by jsotuyod** [comment]
@eriwen exactly!

**Comment by echerepanova** [comment]
WHEN????!!!111oneoneadinadin!!

**Comment by javabrett** [comment]
@jsotuyod @eriwen In finding this issue open and when using Gradle 4.2.1, with a project with a single warning-level Checkstyle violation, starting with empty `checkstyle {}` configuration, I found:

`./gradlew clean checkstyleMain`

```
> Task checkstyleMain
[ant:checkstyle] [WARN] /<redacted>.java:12:34: ',' is not followed by whitespace. [WhitespaceAfter]
```
Warning-level violation is printed to the console, build-succeeds.

`./gradlew checkstyleMain`

Nothing reported because `checkstyleMain` is `UP-TO-DATE`.

Added `maxWarnings = 0`.

```
> Task checkstyleMain
[ant:checkstyle] [WARN] <redacted>.java:12:34: ',' is not followed by whitespace. [WhitespaceAfter]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task 'checkstyleMain'.
> Checkstyle rule violations were found. See the report at: file:///<redacted>/build/reports/checkstyle/main.html

```

 `checkstyleMain` is no-longer up-to-date and runs, build fails correctly as `maxWarnings` threshold has been exceeded, warning is still printed to console, along with reference to the failure report.

Added `showViolations = false`.

Build fails with the report-mention, but the actual individual violation is suppressed.

This all seems pretty complete to me - maybe there were more fixes since this was last discussed.  Am I missing some feature-request outstanding, or should this be closed?

**Comment by jsotuyod** [comment]
@javabrett your description of the current behavior is correct, but is not what I would expect.

The message:
```
> Checkstyle rule violations were found. See the report at: file:///<redacted>/build/reports/checkstyle/main.html
```

Should be shown every time a violation is found (which is what the message expresses!), regardless of the values set to `maxWarnings` and `maxErrors`; and therefore, on wether the build succeded or failed. Otherwise, a developer may simply assume no violations exist.

The only way to currently do this is to make the build fail with 0 tolerance for either warnings or errors and have the build fail upon any of these, which is a little too hardcore.

**Comment by javabrett** [comment]
I see, it's the link to `build/reports/checkstyle/main.html` that you'd like reported.  That seems reasonable to me, although it is currently in the style/context of links to reports for build-failure.

Based on https://github.com/gradle/gradle/issues/881#issuecomment-266926129 and the following comments, I figured the reporting of the violations themselves on the console provided not suppressed by `showViolations = false`.

**Comment by javabrett** [comment]
@jsotuyod does PR #3901 work for you?

**Comment by jsotuyod** [comment]
@javabrett yes, that seems to do exactly what I would expect! Thanks!
