### ISSUE TITLE
failOnVersionConflict only for certain dependencies

### ISSUE THREAD

**Issue by h-ngo** [gradle/gradle#8813]
We want to fail the build if certain dependencies have multiple versions. Is it possible to apply failOnVersionConflict only for certain dependencies?

Quick search on Gradle forum. Same question was posted back in Nov 2018: https://discuss.gradle.org/t/failonversionconflict-only-for-certain-dependencies/29375
, but not yet has a response.

**Comment by ljacomet** [comment]
There is no built-in support for that, but with an `afterResolve` hook on a configuration, it is possible to achieve it in a custom way:

```
plugins {
    `java-library`
}

repositories {
    jcenter()
}

dependencies {
    // Creating conflct on animal-sniffer
    implementation("com.google.guava:guava:27.0.1-jre")
    implementation("org.codehaus.mojo:animal-sniffer-annotations:1.16")
    // Creating conflict on hamcrest
    testImplementation("org.hamcrest:hamcrest-core:1.2")
    testImplementation("junit:junit:4.12")
}

configurations {
    testCompileClasspath.get().incoming.afterResolve {
        resolutionResult.allComponents {
            if (selectionReason.isConflictResolution && moduleVersion != null) {
                if (moduleVersion!!.name.contains("hamcrest")) {
                    throw AssertionError("Cannot have a conflict on hamcrest")
                }
            }
        }
    }
}
```

**Comment by ljacomet** [comment]
Closing as there is no plan to have this built-in and a solution was posted.

**Comment by h-ngo** [comment]
@ljacomet 
Thanks for posting the solution. It works for Gradle 5. Unfortunately, we are using Gradle 4.4, but can't yet upgrade due to business restrictions. `afterResolve` doesn't return ResolutionResult but DefaultConfiguration instead. Hence, we keep getting 

"Could not find method allComponents() for arguments .... on configuration ':abc:resolutionResult' of type org.gradle.api.internal.artifacts.configurations.DefaultConfiguration"

Any suggestions?

**Comment by ljacomet** [comment]
The code was written using the Kotlin DSL not the Groovy one. The types returned by these methods have not changed in quite some time so it should work as well.

Try removing the `.get()` which is not needed in Groovy and adding `it.` in front of `resolutionResult`.
