### ISSUE TITLE
Spotty authorization problems with build cache

### ISSUE THREAD

**Issue by nedtwigg** [gradle/gradle#8818]
I'm getting spotty authorization problems with the docker image `gradle/build-cache-node:7.0`.  Often, these are fixed just by rerunning the build.  The authorization problems show up like [this](https://travis-ci.org/diffplug/spotless/builds/508790652#L474)

> Could not load entry 3d051d9314a361db3fc251c66e52a5d4 for task ':lib:compileJava' from remote build cache: Loading entry from 'https://buildcache.diffplug.com/3d051d9314a361db3fc251c66e52a5d4' response status 401: Unauthorized`

The cache node is setup like this:
<img width="402" alt="Screen Shot 2019-03-20 at 3 18 44 PM" src="https://user-images.githubusercontent.com/2924992/54723051-880cf580-4b23-11e9-9eaa-982c7991dd49.png">

Side bug: this dashboard always says "The cache is empty." even though I know that it is not...

### Expected Behavior

Either my authorization should be correct or not.  Rerunning a build with the same user/pass shouldn't work one time and not another.

### Current Behavior

I'm getting intermittent authorization failures with gradle build cache.

### Context

It makes it harder to get a project's CI pipeline humming with buildcache.  I'm still not sure if anonymous access requires `username='anonymous'`, but it seems to reduce auth failures so I [put it in](https://github.com/diffplug/spotless/blob/647b553a1b3ad984e2ebcab1ad7aa7b6f7db549a/settings.gradle#L16-L26).

### Steps to Reproduce (for bugs)

- start `gradle/build-cache-node:7.0` from dockerhub
- setup with anonymous read and authorized write
- use it in a build
- I get misc failures on my local machine and in CI, using anonymous or authorized access

### Your Environment

Here's the scan that matches the travis build linked above:

 * Build scan URL: https://scans.gradle.com/s/uoysmfufflbmw/switches

**Comment by nedtwigg** [comment]
I've just encountered this in CI:

```
> Task :buildSrc:compileJava FROM-CACHE
   ...
> Task :client:gulp_permanent
Could not load entry 41470a8fe662a8c35d00b91de7055e12 for task ':client:gulp_permanent' from remote build cache: Loading entry from 'https://buildcache.diffplug.com/41470a8fe662a8c35d00b91de7055e12' response status 401: Unauthorized
   ...
> Task :client:gulp_revProd FROM-CACHE
```

Seems like the cache is coming and going within a single build...

**Comment by ldaley** [comment]
@nedtwigg could you share the log file file with me? (see in the cache data dir). You can email it to me via luke at gradle dot com.

**Comment by ldaley** [comment]
@nedtwigg the problem is that you have the wrong cache address.

You have:

https://buildcache.diffplug.com/

It should be:

https://buildcache.diffplug.com/cache

**Comment by nedtwigg** [comment]
Thanks!  I have changed the URL as suggested, and it does seem to have improved.  But it definitely worked intermittently with the old URL.  It seems the buildcache makes some attempt to redirect that sorta works?  Would be better to fail hard than work intermittently with the wrong URL.

**Comment by ldaley** [comment]
> It seems the buildcache makes some attempt to redirect that sorta works? 

There's nothing there like that. There's no reason that it should have worked intermittently. If you still see this after changing the config, please reopen.

**Comment by eygraber** [comment]
I can't reopen this, but I have always had `/cache/` at the end of the address and I have this problem.
