### ISSUE TITLE
Invisible groovy packages in groovy-all-1.0-2.5.4.jar shipped with Gradle 5

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#8821]
### Context

During the investigation of [this failure](https://builds.gradle.org/viewLog.html?buildId=21075875&buildTypeId=Hygiene_CiHealthReRunBuildTagging&tab=buildResultsDiv&branch_Hygiene=refs%2Fheads%2Fblindpirare%2Frevert-change): 

```
Caused by: java.lang.NoClassDefFoundError: org/apache/groovy/dateutil/extensions/DateUtilExtensionsClose stacktrace
at org.gradle.ci.tagging.TeamCityFailedBuildTagger.happenRecently(TeamCityFailedBuildTagger.groovy:303)
at org.gradle.ci.tagging.TeamCityFailedBuildTagger$_flakinessOccursFrequently_closure2.doCall(TeamCityFailedBuildTagger.groovy:298)
```

`org/apache/groovy` package seems to be introduced since groovy 2.5, and Gradle 5 didn't export it in [`DefaultGradleApiSpecProvider`](https://github.com/gradle/gradle/blob/b34cbd3b29b717ac885b692ef7e09be834c717b1/subprojects/core/src/main/java/org/gradle/initialization/DefaultGradleApiSpecProvider.java#L36)

Adding it to exportedPackages may solve this issue, but questions would be: are there any other similar new, unexported packages in Groovy 5?

cc @lptr @melix

**Comment by lptr** [comment]
The idea is that you shouldn't be using those date-related functions at all. If you want to, add a dependency on `groovy-dateutil`.

**Comment by blindpirate** [comment]
@lptr thanks...but the date-related packages are packed into `groovy-all-1.0-2.5.4.jar`...

**Comment by blindpirate** [comment]
@lptr Actually the code was `new Date() - anotherDate < 7`, which implicitly invokes groovy date functions. This seems like a breaking change when user upgrade to Gradle 5 and suddenly the code start breaking. If you think this is expected behavior, please close it.
