### ISSUE TITLE
Build Init plugin should allow configuring JUnit 5 for Java project types

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#8826]
### Expected Behavior

The parameters `--test-framework` should allow the value `junit4` and `junit5`. Not providing the `--test-framework` parameter should default to JUnit 5. The generated code should include something like the following:

```
test {
    useJUnitPlatform()
}

dependencies {
    def junitJupiterVersion = '5.4.1'
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion"
}
```

### Current Behavior

A user can only generate a Java-based project with JUnit 4 as the default. JUnit 5 will likely become the standard version for most projects in the near future.

### Context

Support JUnit 5 in the build init plugin.

### Steps to Reproduce (for bugs)

The command `gradle init --type java-library` only generates JUnit 4 code.

**Comment by adammurdoch** [comment]
This is done via #9118 plus some follow up in #9191
