### ISSUE TITLE
Use `Deleter` for cleaning up leftover files from failed unpack

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#8829]
We are cleaning up the output directories of a task after a failed attempt to load from the cache. Currently, we are using `FileUtils` to do the cleanup. It may be better to use [Deleter](https://github.com/gradle/gradle/blob/21925d22551636a6578cc343118a41e91bc9bb75/subprojects/core/src/main/java/org/gradle/api/internal/file/delete/Deleter.java), so the error messages when failing to delete the unpacked files would be better.

See https://github.com/gradle/gradle/pull/8783#discussion_r266046836

**Comment by lptr** [comment]
We should not try to recover from a failed unpack at all. We'll change this in 6.0.
