### ISSUE TITLE
archiveBaseName values set in custom ArchiveTask constructors, are overwritten with project.archivesBaseName values when BasePlugin is applied

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#8831]
### Expected Behavior
When I extend an archive task class (e.g: Jar) and specify an archiveBaseName value in the constructor, I expect that value I specified to be applied rather than seeing the default value from the project.archivesBaseName being used.

### Current Behavior
The archiveBaseName value I set in the constructor is overwritten with the project.archivesBaseName value by the BasePlugin in a project.getTasks().withType(AbstractArchiveTask.class).configureEach() block.

### Context
Gradle used to behave this way, and this regression silently broke part of our build.

### Steps to Reproduce (for bugs)
define a custom archive task class that extends the Jar task, and set a uniquely identifiable archiveBaseName in its constructor.

add an instance of this Task to a project which applies the BasePlugin, and execute the task.

note that the default archiveBaseName was used rather than the archiveBaseName you've set in the constructor.

### Your Environment
using gradle 5.2.1

**Comment by big-guy** [comment]
This was a mistake (`.convention` was added about the same time that `archiveBaseName` was) and will be fixed in 5.4.  You should be able to try a nightly in ~a day.

**Comment by steffenyount** [comment]
oh great! thank you for the quick turnaround!
