### ISSUE TITLE
Gradle leaks private information to log files, other users on the same system

### ISSUE THREAD

**Issue by schildbach** [gradle/gradle#8833]
As followup to #8832:

[Bitcoinj](https://github.com/bitcoinj/bitcoinj) has a [tool](https://github.com/bitcoinj/bitcoinj/blob/master/tools/src/main/java/org/bitcoinj/tools/WalletTool.java) to work with Bitcoin wallets. It can (amongst many other things) print the private seed and private keys.

Because gradle managed the dependecies, [we're using gradle](https://github.com/bitcoinj/bitcoinj/blob/a67f54cd0c1a1c6ac8b71cfdcafad990e0d8cac4/tools/build.gradle#L17) to start the tool as a convenience. Finally, a [wrapper](https://github.com/bitcoinj/bitcoinj/blob/master/tools/wallet-tool) is supplied for the right Gradle parameters.

(Note that the solution is still written for Gradle 3.4.1, as that's the version that is in Ubuntu Bionic. We will be upgrading to Gradle 4.4.1 soon.)

We recently discovered that the private keys (and everything else printed to the console) leaks into logfiles written by Gradle at `~/.gradle/daemon`, and we didn't find a way to switch logging off for a session or at least suppress logging of standard output. Log files are world readable, so any user on the same system can steal private keys.

Of course we could go without gradle in this case but honestly managing (transitive) dependencies by hand is not really an option these days.

At the very least, users should be warned everything is being logged. Honestly I had no idea these logs exist.

**Comment by big-guy** [comment]
Thanks @schildbach 

> (Note that the solution is still written for Gradle 3.4.1, as that's the version that is in Ubuntu Bionic. We will be upgrading to Gradle 4.4.1 soon.)

FYI, this isn't really the Gradle 3.4.1 or 4.4.1 that we've released. 

> Log files are world readable, so any user on the same system can steal private keys.

I think we can restrict this.

> Of course we could go without gradle in this case but honestly managing (transitive) dependencies by hand is not really an option these days.

There's another option here that gets what you want, I think:
- Use the [application plugin](https://docs.gradle.org/current/userguide/application_plugin.html#header)
- This will add an `installDist` task that generates a script to run your tool
- In your wrapper script, run `gradle installDist` and then run the generated script.

**Comment by schildbach** [comment]
@big-guy I may be wrong, but I think I cannot use the application plugin in this case, because it allows only one of such applications per module. Our tools module contains many tools, and each of them of course has a different main class. Of course I could split it up into one module per tool, but that would be a lot of overhead.
