### ISSUE TITLE
Source dependencies feature branch versioning doesn't work when there is a tag

### ISSUE THREAD

**Issue by FlavioF** [gradle/gradle#8843]
I am using Gradle **4.10.3** and trying to use source dependencies described here:
https://blog.gradle.org/introducing-source-dependencies
It works pretty well except when we try to use versioning based on branch name when a tag is present on the repo.

settings.gradle
```
sourceControl {
    gitRepository("ssh://git@bitbucket.org/some/repo.git") {
        producesModule("some:repo")
    }
}
```

build.gradle
```
dependencies {
    implementation("some:repo") {
        version {
            branch = 'feature/some_branch'
        }
    }
....
    }
```

### Expected Behavior

Use the branch version always.

### Current Behavior

If there is at least one tag in the repo, last tag will be used instead of branch.
### Context

To manage versions I would like to choose between branch (for development releases) and tag (for production releases). Right now that's not possible.

### Steps to Reproduce (for bugs)

1. Create one Gradle Git Repo (A)
2. Create another Gradle Git Repo (B)
3. Use B as dependency of A with a branch (master for instance)
4. Confirm that everything is working as expected
5. Create a tag on Repo B
6. Apparently everything is still working as expected
7. Add a new class in a different branch on Repo B (test for instance)
7. Change version branch on repo A (from master to test)
8. Confirm that new class is not present on repo A

### Your Environment

 * Build scan URL: 
Java8, Gradle 4.10.3

**Comment by ddimtirov** [comment]
Linking to #10559
