### ISSUE TITLE
Can not copy xml before processTestResources in Gradle 3.2

### ISSUE THREAD

**Issue by Hawods** [gradle/gradle#885]
Here is my configurations:
```
task copyTestConfig(type: Sync) {
        def configHome = "${rootDir}/config"
        from(configHome) {
            include '**/*.properties'
            include '**/*.xml'
        }
        into "${buildDir}/resources/test"
    }
processTestResources.dependsOn copyTestConfig
```

After run task processTestResources all properties and xml in "${rootDir}/config" should be copy into "${buildDir}/resources/test". But no xml copied when I use Gradle 3.2, and same configuration work fine in Gradle 3.1. 

Besides, when I replace processTestResources by processResources like this:
```
task copyTestConfig(type: Sync) {
        def configHome = "${rootDir}/config"
        from(configHome) {
            include '**/*.properties'
            include '**/*.xml'
        }
        into "${buildDir}/resources/test"
    }
processResources.dependsOn copyTestConfig
```
Every thing work fine even in Gradle 3.2. So weird...

**Comment by lacasseio** [comment]
Thanks for opening an issue @Hawods. I wasn't able to reproduce the behavior explained here. Could you provide us with a more detailed example of your configuration work as expected?

**Comment by Hawods** [comment]
@lacasseio Thanks for your response. I have just tested again, can not reproduce too. I'm sorry to trouble you.
