### ISSUE TITLE
Category attribute in ResolvedComponentResult has type String not Category

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#8854]
I'm trying to determine if a resolved component is a platform or not.

I have a `ResolvedComponentResult` and am getting the attributes of the selected variant via `((ResolvedComponentResult) rcr).getVariant().getAttributes()`.

Printing this out for a particular component, I can see it includes a category of "platform":
```
{org.gradle.category=platform,...}
```

### Expected Behavior

I expect `attributes.getAttribute(Category.CATEGORY_ATTRIBUTE)` to return a non-null `Category` value, whose name is equal to `Category.REGULAR_PLATFORM`.

### Current Behavior

When I do `attributes.getAttribute(Category.CATEGORY_ATTRIBUTE)`, this returns null.

To get it to work, I had to redefine the category attribute as being of type String:
```gradle
def attr = Attribute.of("org.gradle.category", String)
attributes.getAttribute(attr) == Category.REGULAR_PLATFORM
```

### Steps to Reproduce 

This is a problem in both gradle 5.3 and latest nightly.

1. Define a platform dependency on a configuration
2. Get the ResolutionResult for that configuration, and attempt to get the `Category.CATEGORY_ATTRIBUTE` for each component as described above

### Your Environment

Build scan URL:

**Comment by melix** [comment]
This may look curious but this is actually expected. When looking at the `ResolutionResult`, attributes are _desugared_: their type is very likely to be `String` (there are a few exceptions). The reason is that when you have a published component, the published metadata only tells the attribute name and value, and it's _coerced_ to a typed attribute.

So the right way to look for this attribute is actually to find by name.

**Comment by dansanduleac** [comment]
When you say find by name, is there a specific method you suggest?

Right now I've had to declare my own duplicate category attribute, with the implicit assumption that the type is String:
https://github.com/palantir/gradle-consistent-versions/pull/70/files#diff-08f32d35d43128c708e9977c0f96ea65R30

Is there a better way to do it, ideally one that's available in the gradle API? I'm really uncomfortable with defining my own attribute and basically guessing the type, with the prospect of this silently breaking in a future version of gradle.

**Comment by dansanduleac** [comment]
Also, why can't we coerce the string value back to the type that's expected in the API, given that it's a Named type that the ObjectFactory can create?

**Comment by melix** [comment]
Just iterate over the attributes and get them by name. The API of the `AttributeContainer` is _strict_, it doesn't do any coercion, so when you ask it for an attribute of a specific type, it does its job and tries to find one with the exact type. So here, you need to iterate over the attributes, find the one that has the expected name and compare its value. That's something we could improve in the future, but for now there's no better way.

**Comment by dansanduleac** [comment]
Even comparing its value is non-trivial, since iterating gives me a bunch of `Attribute<?>` and now I have to switch on the runtime type.
I'd need some sort of `attr instanceof Named ? ((Named) attr).getName() : attr.toString()`, or possibly even throw if it's neither Named nor String...

**Comment by melix** [comment]
I understand but there's currently no better way to do this.

**Comment by dansanduleac** [comment]
Yep, not complaining, just making sure I wasn't missing something obvious.

**Comment by ljacomet** [comment]
Closing as no changes are planned in this area
