### ISSUE TITLE
Vulnerabilities in Gradle 5.1.1

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#8857]
@gakhrejah commented on [Tue Mar 26 2019](https://github.com/gradle/gradle-native/issues/1003)

Hi Team,

I am using Gradle 5.1.1 version to compile my spring boot applications in a docker container.
I am using JFROG as an artifactory to store all the artifact . It runs a JFROG artifact scan which is causing the issue .
Gradle 5.1.1 comes with a common-collection-3.2.2.jar in lib folder and bcprov-jdk15on-1.60.jar in lib/plugin folder  . These JAR is causing the JFROG XRAY issue 
These are vulnerabilities which is causing my build to fail

### Expected Behavior
XRAY scan should pass

### Current Behavior
XRAY scan is failing with the vulnerabilities attached

### Context
Can you please let me know 
1) Is there any we can upgrade these 2 jar in gradle-5.1.1.
2) I have tried directly replacing the jar with the upgraded version but then it is not able to compile my code.

Please let me know , as this issue is blocker.
Please let me know if you require any other info

[XRAY-SCAN-LOGS.txt](https://github.com/gradle/gradle/files/3007104/XRAY-SCAN-LOGS.txt)
 for us 

---

@gakhrejah commented on [Tue Mar 26 2019](https://github.com/gradle/gradle-native/issues/1003#issuecomment-476517254)

JARS in which vulnerabilities are fixed 

bcprov-jdk15on-1.61.jar
commons-collections4-4.2.jar

Can you please let us know how can we update the pre existing jar in gradle package i.e.  gradle-5.1.1-all.zip

NOTE: I want the jar to be updated in gradle package inside lib folder .

Please let me know if you need any other info

**Comment by gakhrejah** [comment]
hi team,
Can you please have a look here

**Comment by lacasseio** [comment]
I'm unsure what is the action you want the Gradle development team to take. We are aware some jar may be vulnerable in theory but we aren't using any of the vulnerable features within Gradle. Given those jars aren't part of your project, what is the issue here? Once your application is built, Gradle shouldn't be part of your release hence shouldn't trigger any scan. Could you clarify what is the intention of using the jar inside the Gradle package directory?

**Comment by big-guy** [comment]
@gakhrejah Gradle 5.4 will no longer include commons-collections and the bouncy castle vulnerability is more of a warning if you're using a BKS-V1 keystore (Gradle does not).  But like Daniel said, I don't think these are warnings are something that affect your application.
