### ISSUE TITLE
Given organization in generated POM is evaluated to org.apache.maven.model.Organization.toString()

### ISSUE THREAD

**Issue by huxi** [gradle/gradle#886]
This issue mirrors [GRADLE-1200](https://issues.gradle.org/browse/GRADLE-1200).

Executing `gradle install` on the following `build.gradle` causes a malformed `organization` to be generated in `build/poms/pom-default.xml`.
```groovy
apply plugin: 'java'
apply plugin: 'maven'

install.repositories.mavenInstaller.pom.project {
		developers {
			developer {
				id 'jdoe'
				email 'jdoe@acmeinc.com'
				name 'John Doe'
				organization 'ACME Incorporated'
			}
		}
	}
```

### Expected Behavior

`build/poms/pom-default.xml` should look like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId></groupId>
  <artifactId>install-pom-bug</artifactId>
  <version>unspecified</version>
  <developers>
    <developer>
      <id>jdoe</id>
      <name>John Doe</name>
      <email>jdoe@acmeinc.com</email>
      <organization>ACME Incorporated</organization>
    </developer>
  </developers>
</project>
```

### Current Behavior
`build/poms/pom-default.xml` looks like this instead:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId></groupId>
  <artifactId>install-pom-bug</artifactId>
  <version>unspecified</version>
  <developers>
    <developer>
      <id>jdoe</id>
      <name>John Doe</name>
      <email>jdoe@acmeinc.com</email>
      <organization>org.apache.maven.model.Organization@29c6e3c</organization>
    </developer>
  </developers>
</project>
```

### Context

This is a minor issue because an easy workaround exists. One simply needs to replace `organization 'ACME Incorporated'` with `organization = 'ACME Incorporated'`.

It's a bug nevertheless and you need to know about this workaround. The need to use `=` in this context isn't exactly obvious, either.

Generation of the POM is currently handled by `org.sonatype.maven.polyglot.groovy.builder.ModelBuilder` of [`org.sonatype.pmaven:pmaven-groovy:0.8-20100325`](http://jcenter.bintray.com/org/sonatype/pmaven/pmaven-groovy/0.8-20100325/) which is only available on jcenter.

The latest version of this dependency appears to be [`io.takari.polyglot:polyglot-groovy:0.1.19`](http://repo1.maven.org/maven2/io/takari/polyglot/polyglot-groovy/0.1.19/) from [polyglot-maven](https://github.com/takari/polyglot-maven/) but I didn't evaluate whether upgrading would fix this issue or not.

### Steps to Reproduce (for bugs)

Execute `gradle install` with the `build.gradle` above.

**Comment by bmuschko** [comment]
@huxi Any chance you are interested in providing a pull request for the issue?

**Comment by huxi** [comment]
@bmuschko Maybe. No promises about an ETA, though.

**Comment by huxi** [comment]
Simply changing the following in `maven.gradle` wasn't enough:
```groovy
    //compile "org.sonatype.pmaven:pmaven-common:0.8-20100325@jar"
    compile "io.takari.polyglot:polyglot-common:0.1.19"
    //compile "org.sonatype.pmaven:pmaven-groovy:0.8-20100325@jar"
    compile "io.takari.polyglot:polyglot-groovy:0.1.19"
```

meaning that the following test I added to `org.gradle.integtests.publish.maven.MavenJavaProjectPublishIntegrationTest` would still fail:
```groovy
    @Issue('886')
    def "organization is generated as expected"() {
        given:
        buildFile << """
apply plugin: 'java'
apply plugin: 'maven'

install.repositories.mavenInstaller.pom.project {
    developers {
        developer {
            id 'jdoe'
            email 'jdoe@acmeinc.com'
            name 'John Doe'
            organization 'ACME Incorporated'
        }
    }
}
"""
        when:
        run "install"

        and:
        def pomContent = file('build/poms/pom-default.xml').text

        then:
        pomContent.contains('<organization>ACME Incorporated</organization>')
    }
```

Next step was trying to update the Maven and - as a consequence - aether versions in `dependencies.gradle`:

```groovy
// versions.maven = "3.0.4"
versions.maven = "3.3.9"

// [...]

    //aether:
    //dependency "org.sonatype.aether:aether-api:1.13.1@jar"
    //dependency "org.sonatype.aether:aether-impl:1.13.1@jar"
    //dependency "org.sonatype.aether:aether-spi:1.13.1@jar"
    //dependency "org.sonatype.aether:aether-util:1.13.1@jar"
    //dependency 'org.sonatype.aether:aether-connector-wagon:1.13.1@jar'

    dependency "org.eclipse.aether:aether-api:1.1.0@jar"
    dependency "org.eclipse.aether:aether-impl:1.1.0@jar"
    dependency "org.eclipse.aether:aether-spi:1.1.0@jar"
    dependency "org.eclipse.aether:aether-util:1.1.0@jar"
    dependency 'org.eclipse.aether:aether-transport-wagon:1.1.0@jar'
// [...]
```

That change turned out to be non-trivial since `org.gradle.api.publication.maven.internal.action.AbstractMavenPublishAction` is using internal Maven/Aether APIs that aren't available anymore, e.g. `MavenRepositorySystemSession`, `SimpleLocalRepositoryManager` (construction now requires the use of `SimpleLocalRepositoryManagerFactory` because it was changed to package-private) etc.

I'll leave it at that for now for the following reasons:
- I'm unaware about the reasons those internal APIs have been used in the first place
- I can't be sure if those changes would fix this issue at all
- I didn't check whether the above upgrades would require a higher Java version than Gradle allows. The plan was to find a fix and then downgrade until the required Java version was met.
- this is a pretty critical part of Gradle that I'd rather not break for a minor issue like this

I hope this stab at a solution helps anyway even if it's just "there's a maintenance problem lurking in the Maven integration" and "no, a simple upgrade won't fix the issue".

**Comment by bigdaz** [comment]
The `maven` plugin (together with the core `Upload` task) are being replaced by the `maven-publish` plugin. As such, we don't plan on making changes to improve the (now legacy) `MavenInstaller`. Expect to see this type deprecated in Gradle 6.x, for possible removal in Gradle 7.0.
