### ISSUE TITLE
plugin applied in subprojects block of a subproject not applied to children

### ISSUE THREAD

**Issue by kunickiaj** [gradle/gradle#8865]
### Expected Behavior
Given: 
```groovy
subprojects {
  apply plugin: 'java'
}
```
Expected javaplugin to be applied in all subprojects.

### Current Behavior
java plugin is applied to current project and not subprojects.

### Context
Given:

rootProject --> intermediateProject --> leafProject1
rootProject --> intermediateProject --> leafProject2

intermediateProject/build.gradle contains the above subprojects block, however `gradle :intermediateProject:leafProject1:compileJava fails due to missing 'java' plugin.

Invoking top level `gradle compileJava` or `gradle :intermediateProject:compileJava` builds the leafProjects correctly.

Same behavior was exhibited regardless of which plugin was specified. Tried java-library and maven-publish plugins as well.

### Steps to Reproduce 
```
git clone https://github.com/kunickiaj/gradle-repro.git
gradle :intermediate:leafProject1:compileJava
```

results in:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/adam/workspace/kunickiaj/gradle-repro/intermediateProject/leafProject1/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':intermediateProject:leafProject1'.
> Could not find method api() for arguments [com.google.guava:guava:20.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

### Your Environment
macOS 10.14.4 Java 11 and Gradle 5.3
Build scan URL: https://gradle.com/s/ej37rnnietzgy

**Comment by lacasseio** [comment]
The root of the issue is with `configure-on-demand` as the [warning state, it's an incubating feature](https://scans.gradle.com/s/ej37rnnietzgy/console-log#L1) and is only useful for a shrinking amount of use cases. Turn it off and everything will be working as expected. This feature is not meant to be used in builds and will soon be removed.

**Comment by lacasseio** [comment]
By the way, thanks for sharing a build scan. It was really useful to reproduce the issue.

**Comment by kunickiaj** [comment]
Thanks for the quick response. Just to clarify, are you saying configure on demand is going to be removed, or some other feature?

**Comment by lacasseio** [comment]
Configure on demand was and is still an incubating feature. Most of what it's doing has been enabled by default using the worker API. There is no timeline but it's been more and more broken and we aren't really fixing any issue given the incubating nature of it.
