### ISSUE TITLE
Installing Android SDK packages must flow successfully, ignoring copyrastic idiotia manifestations

### ISSUE THREAD

**Issue by powerbroker** [gradle/gradle#8867]
On importing Android project into Eclipse

```
org.gradle.tooling.BuildException: Could not fetch model of type 'GradleBuild' using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.1-all.zip'.......
...............
Caused by: com.android.builder.errors.EvalIssueException: Failed to install the following Android SDK packages as some licences have not been accepted.
   platforms;android-27 Android SDK Platform 27
   build-tools;28.0.3 Android SDK Build-Tools 28.0.3
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

Using Android SDK: d:\Infrastructure\Java\android-sdk-windows
	at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:194)
	at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.java:876)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:722)
...............
```

WTF?!!!!!!!!!!!!!!!!

Copyrastic idiotia manifestations must never fail development process. All this stuff is meant for bullshitting end-users and never for making troubles for developers. Since we know what the truth is. Speaking honestly, almost nobody of us was even interested in copyrastic toilet paper (so called 'license') meaning to read it.

SDK packages installation must focus on installation success, totally avoiding(and ignoring, if any) finger-sucked copyrastic obstacles.

**Comment by oehme** [comment]
Please follow our code of conduct. Offensive language is not welcome here.

Apart from that, this is not a Gradle issue, but an Android issue. Android requires you to accept their license and this is very unlikely to change.
