### ISSUE TITLE
Gradle strips /META-INF/gradle/incremental.annotation.processors file when downloading annotation processor dependencies

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#8869]
### Environment
Gradle 5.3

### Current Behavior
To make Room an incremental annotation processor, we've added the following file to the jar that we publish:

> /META-INF/gradle/incremental.annotation.processors

I've confirmed that the file exists in the published jar.

When Gradle downloads this jar to the `~/.gradle/caches` directory, for some reason the jar no longer contains the `META-INF/gradle` directory.

We've narrowed down the issue to this nightly release:

`gradle-5.3-20190122101802+0000` => BUGGY
`gradle-5.3-20190122000039+0000` => WORKING

### Expected Behavior
Gradle doesn't modify the jars' contents when downloading.

**Comment by wolfs** [comment]
Where in the local caches does the downloaded file exist? Gradle should not modify downloaded jars, so I am very surprised that what you described occured.

For me, the most probably cause is that the version of the dependency in the remote repository has been overwritten, and that Gradle uses the old version in the dependency cache. Can you try out with a new Gradle user home?

Another option would be that it chooses a different repository to download the dependency from in the newer nightly.

**Comment by hungvietnguyen** [comment]
Ah yes, the version of the dependency that I'm testing with locally just got pushed to the remote repository. I should have used a "dev" version that never exists remotely. (And you're right, the seemingly Gradle regression is just that Gradle chooses a different repository in the new nightly.)

Sorry for the false alarm!
