### ISSUE TITLE
Drop the LicenceNotAcceptedException handling in com.android.build.gradle.internal.SdkHandler.initTarget() method

### ISSUE THREAD

**Issue by powerbroker** [gradle/gradle#8871]
On importing Android project into Eclipse, when guuugel copyrastic checks fail, build fails with inappropriate error message and invalid stack trace:

```
org.gradle.tooling.BuildException: Could not fetch model of type 'GradleBuild' using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.10.1-all.zip'.......
...............
Caused by: com.android.builder.errors.EvalIssueException: Failed to install the following Android SDK packages as some licences have not been accepted.
   platforms;android-27 Android SDK Platform 27
   build-tools;28.0.3 Android SDK Build-Tools 28.0.3
To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
	at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:194)
	at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.java:876)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:722)
...............
```

The error message states "actually there are no errors, we just want you to do some monkey dance". The stack trace points into Gradle code, hiding the actual entity, responsible for this error - goooogle.

The gooogle responsibility for this error should be obvious. No efforts should be spent on attempts to handle goooglic errors in case they cannot be made invisible for user. The com.android.builder.sdk.LicenceNotAcceptedException, if unchecked, should never ever be mentioned in Gradle code. If checked, should be re-thrown inside a RuntimeException in a manner "we have no idea what it is and cannot care about bugs in third-party code". A short message stating "build failed because somewhat went wrong IN GOOGLE CODE" may be provided.
Yes, people will complain to goooogle and fill their bug trackers with bug reports. Yes, let gooogle carry their own responsibility for their bugs.

**Comment by oehme** [comment]
Again, com.android.builder is not part of Gradle, but part of the Android pluign. Gradle does nothing special here, it just presents the exception like any other.
