### ISSUE TITLE
Moving Java files breaks incremental builds

### ISSUE THREAD

**Issue by GFriedrich** [gradle/gradle#8874]
When moving a "java" file from package A to package B, the incremental build results in both classes to exists in the build/classes folder.
Even worse: When deleting the build folder and doing a recompile, the class files pop up again in both packages due to being fetched from the compile cache of Gradle (of course only if caching is enabled).

### Expected Behavior
The class file from package A should go away and only package B should contain a class file.

### Current Behavior
Both packages contain a class file.

### Context
This is basically the worst case scenario when using incremental builds. Especially when using frameworks that automatically detect Java classes.

### Steps to Reproduce 
Have an existing project that was compiled previously.
Move some class to a different package.
Run the Gradle build again.

### Your Environment
Gradle 5.3
Java 8

**Comment by GFriedrich** [comment]
Additional info: If I disable the incremental build for the java compile task, the behavior goes back to normal.
Looks to me that the "incremental" build is not really production ready. (Even though it should when being enabled as default.)

**Comment by oehme** [comment]
Can you please attach a small example project showing the problem?

**Comment by GFriedrich** [comment]
Sure, will do - give me a moment.
Also some more info: I've tested some older Gradle versions and also 4.10.x and upwards seems to be affected.
And I've also tested a Kotlin plugin, but things are working properly over there, so it must be some kind of Java plugin issue.
And finally I tested on a different machine but got the same bad result.

**Comment by GFriedrich** [comment]
Steps for reproduction:
* Run the "build" task
* Check that there is a class in "build/classes/java/main/packagea"
* Move the class to the currently empty "packageb" (remember to change the package name inside the Java file)
* Rerun the "build" task
* Now there are two files within the "build/classes" folder, even though there should be only one.
[gradle-bug.zip](https://github.com/gradle/gradle/files/3015093/gradle-bug.zip)

As said: The situation gets more confusing if you enable the caching of the tasks and have systems like a CI, where suddenly classes pop up in folders you don't expect them to be in.

**Comment by wolfs** [comment]
I saw the same today. I moved `FilePathUtils.java` in the hierarchy: https://e.grdev.net/c/r4buqpimc3g2k/gkoexqzeptusu/task-inputs?toggled=WzIsNV0&toggledFileChanges=WyJtemN0ZWE0ajRhcGFtLWZpbGUtaW5wdXQtMCIsIm16Y3RlYTRqNGFwYW0tMC0wIiwibWVsenM3ZXFnYnQ2Mi1maWxlLWlucHV0LTAiLCJtZWx6czdlcWdidDYyLTAtMCJd#change-melzs7eqgbt62-0-0-0

My guess is that, since we use `NAME_ONLY` as the path sensitivity for source files, the change is reported only once as modified. Therefore, we only mark the new file as updated and don't remove the old file, since the incremental changes don't report the old location in any way.

A simple fix is to use `RELATIVE` path sensitivity for the sources - though that comes with a performance impact...

**Comment by GFriedrich** [comment]
Wondering why this never popped up earlier, because this is basically broken since more than half of a year now and using frameworks like Spring that scan classes from your classpath are quite common these days.

**Comment by oehme** [comment]
I didn't know we used name only notmalization, that won't work of course. The package matters for Java. We'll have to bite whatever performance penalty that means. @wolfs can you make the change?

**Comment by wolfs** [comment]
I can make the change. I think it is the best way forward.

Note that from a Java compiler perspective the package matters, the location of the source file does not. The package is encoded in the file not as part of the path. That is why we went with `NAME_ONLY` in the first place back in 3.x.

**Comment by GFriedrich** [comment]
Are you planning to put this to 5.3.1?
Would be awesome, because currently I need to disable incremental builds in general due to this issue.

**Comment by wolfs** [comment]
This is no planned for `5.3.1`. By disabling incremental builds you mean incremental Java Compilation? Incremental builds should be fine, you only need to disable incremental Java compilation.

**Comment by GFriedrich** [comment]
Yes thats what I meant.
For me this is a serious issue. People that do not know about this and have incremental Java compilation enabled by default and do some refactoring will end up with wrong application Jars and the problems will only arise during runtime.
Would be great to see this in a bugfix version and not wait additional weeks for 5.4

**Comment by oehme** [comment]
5.4 RC1 is due next week, not "in weeks" :)

**Comment by GFriedrich** [comment]
But I won't use 5.4 RCx for a productive development system and normally it takes at least one additional week to have the 5.4 rolled out the door. So basically: Yes it is "weeks". ;)

**Comment by GFriedrich** [comment]
FYI: I've decided to use a patched version of Gradle 5.3.1 including the fixes from the PR.
The results look good to me and therefore I'm not in the need anylonger to have bugfixed version rather soonish.

**Comment by doniwinata0309** [comment]
I am having similar issue, but it is on annotation processor. When moving class to another module, the generated class from annotation processor is still generated on old module (causing compilation failed).

**Comment by wolfs** [comment]
@doniwinata0309 What do you mean by "moving class to another module"? Are you moving the class to another package?

**Comment by doniwinata0309** [comment]
@wolfs  yes, I am moving the class to another package. It is android project with gradle 5.2.1.

**Comment by wolfs** [comment]
@doniwinata0309 Can you try if your problem is fixed in `5.4-20190329080509+0000`?

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/8880.

**Comment by doniwinata0309** [comment]
thanks @wolfs , will let you know if still having the issue.
