### ISSUE TITLE
produced POM for gradle plugin portal doesn't use resolved dependencies when configured

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#8879]
Hi folks, we detected an issue with our plugins getting published to plugin portal without the resolved dependency version for each one of them. We were expecting to configure the `MavenPublication` once with our plugin but things didn't work. This is here -> https://github.com/nebula-plugins/nebula-publishing-plugin/blob/master/src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy

With that said, we tried to reproduce this without Nebula and just vanilla Gradle as follows: https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/gradle-plugin-pom-resolved-dependencies/build.gradle 

We configure the publication to use resolved dependencies: 

```
publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            group 'nebula.test.plugin'
            version '1.0.0'
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
}
```

When we publish this plugin to maven local, we get the following POM:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>nebula.test.plugin</groupId>
  <artifactId>gradle-plugin-test</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>27.1-jre</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

However, when trying to push this repo to the plugin portal, this is the output:

```
> Task :publishPlugins
Publishing plugin nebula.test-nothing-plugin version 1.0.0
Thank you. Your new plugin nebula.test-nothing-plugin has been submitted for approval by Gradle engineers. The request should be processed within the next 24 hours, at which point you will be contacted via email.
Publishing artifact build/libs/gradle-plugin-test-1.0.0.jar
Publishing artifact build/libs/gradle-plugin-test-1.0.0-sources.jar
Publishing artifact build/libs/gradle-plugin-test-1.0.0-javadoc.jar
Publishing artifact build/libs/gradle-plugin-test-1.0.0-groovydoc.jar
Publishing artifact build/publish-generated-resources/pom.xml
Activating plugin nebula.test-nothing-plugin version 1.0.0
```

And the generated `pom.xml` is:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>gradle.plugin.nebula.test.plugin</groupId>
  <artifactId>gradle-plugin-test</artifactId>
  <version>1.0.0</version>
  <dependencies>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>latest.release</version>
      <scope>compile</scope>
      <type>jar</type>
      <optional>false</optional>
    </dependency>
  </dependencies>
</project>
```

It appears that any change to the `MavenPublication` is not honored by the plugin-publish-plugin.

This is using Gradle 5.3

**Comment by ljacomet** [comment]
@marcphilipp Any chance this rings a bell directly?

**Comment by marcphilipp** [comment]
The plugin-publish plugin reuses the POM of the `pluginMaven` publication that is created by the `java-gradle-plugin` (if `gradlePlugin.automatedPublishing` is not set to `false`). Thus, you need to change the configuration of that publication instead of creating a new `MavenPublication`.

Instead of 

```gradle
publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            group 'nebula.test.plugin'
            version '1.0.0'
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
}
```

use this:

```gradle
publishing {
    afterEvaluate {
        publications.getByName("pluginMaven") {
            group 'nebula.test.plugin'
            version '1.0.0'
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
}
```

However, in your build output it looks like you've disabled automated publishing in which case the plugin-publish plugin generates its own POM:

```
Publishing artifact build/publish-generated-resources/pom.xml
```

should be 

```
Publishing artifact build/publications/pluginMaven/pom-default.xml
```

For me the sample project produces the latter line.

@rpalcolea Did you have that disabled?

**Comment by ljacomet** [comment]
I confirm that Marc's suggestion works as expected and the right pom file gets updated for me.

**Comment by rpalcolea** [comment]
Thanks for the prompt response folks, this is interesting and makes complete sense... I was able to get things working on my sample project.

I found that using our plugin through `plugin-plugin` doesn't work, for example: 

```
plugins {
    id "nebula.plugin-plugin" version "9.3.0"
}

repositories {
    jcenter()
}

dependencies {
    compile 'com.google.guava:guava:latest.release'
}

group = 'nebula.test.plugin'
version = '1.0.13'


task('final') {
    doLast {
        println "hello"
    }
}
pluginBundle {
    website = 'https://nebula-plugins.github.io/'
    vcsUrl = 'https://nebula-plugins.github.io/'
    tags = ['testing', 'integrationTesting', 'compatibility']
    plugins {
        testNothingPlugin {
            id = 'nebula.test-nothing-plugin'
            displayName = 'nebula-test-nothing-plugin'
            description = 'nebula-test-nothing-plugin'
            tags = ['nebula', 'plugin']

        }
    }
}```

This results in  `Publishing artifact build/publish-generated-resources/pom.xml`

```
   <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>latest.release</version>
      <scope>compile</scope>
      <type>jar</type>
      <optional>false</optional>
    </dependency>
```

`plugin-plugin` applies `nebula.maven-publish` via https://github.com/nebula-plugins/nebula-plugin-plugin/blob/master/src/main/groovy/nebula/plugin/plugin/NebulaPluginPlugin.groovy#L57

The interesting bit is that if I consume `nebula.maven-publish` directly on my test project things work:

```
plugins {
    id 'groovy'
    id 'com.gradle.plugin-publish' version '0.10.1'
    id 'java-gradle-plugin'
    id "nebula.maven-publish" version "9.5.0"
}

repositories {
    jcenter()
}

dependencies {
    compile 'com.google.guava:guava:latest.release'
}
```

`Publishing artifact build/publications/pluginMaven/pom-default.xml`

```
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>27.1-jre</version>
      <scope>compile</scope>
    </dependency
```

is it possible that applying the plugin applies happens in a way that this gets executed either too early or too late https://github.com/nebula-plugins/nebula-publishing-plugin/blob/v9.5.0/src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy#L35 ?

**Comment by rpalcolea** [comment]
I’m starting to think this is happening because Plugin-plugin doesn’t apply java-gradle-plugin so there is no re-use. However I would expect the nebula maven plugin to apply to any mavenpublication

Thoughts on this @marcphilipp?

**Comment by rpalcolea** [comment]
Hi @ljacomet @marcphilipp ,

I found that this block is the culprit on my use case -> https://github.com/nebula-plugins/nebula-plugin-plugin/blob/master/src/main/groovy/nebula/plugin/plugin/NebulaPluginPlugin.groovy#L118

It appears that configuring the `pluginBundle` there generates the `pom.xml` instead of the `pom-default.xml` 

So I guess doing this disables `automatedPublishing` ?

**Comment by rpalcolea** [comment]
actually, the problem is specific to setting the `mavenCoordinates`. Removing that fixes the issue

```
 mavenCoordinates {
                        groupId = project.group
                        artifactId = project.name
                    }
```

**Comment by marcphilipp** [comment]
Right, because then `plugin-publish` "has to" generate its own POM.

**Comment by marcphilipp** [comment]
@rpalcolea Can we close this issue?

**Comment by rpalcolea** [comment]
yeah, sorry for the noise and thanks for the explanation!

**Comment by marcphilipp** [comment]
No worries! I believe @ljacomet has created an issue to improve the documentation on the integration of the three plugins.
