### ISSUE TITLE
Signing plugin doesn't work with GPG 2.1

### ISSUE THREAD

**Issue by bryant1410** [gradle/gradle#888]
### Expected Behavior
If using the 'signing' plugin in a system that has GPG version 2.1, it should work.

### Current Behavior
It isn't working.

### Context
[GPG 2.1 doesn't use `secring.gpg` file](https://www.gnupg.org/faq/whats-new-in-2.1.html). According to the changelog, this plugin should use the *gpg-agent*.

Also, it should support long key id format, besides this isn't a problem.

### Steps to Reproduce (for bugs)
Apply this plugin and try to use it in a system with GPG 2.1.

### Your Environment
A system with GPG 2.1 version installed.

**Comment by huxi** [comment]
Gradle is currently using `org.bouncycastle:bcpg-jdk15on:1.51`.

The latest version is `org.bouncycastle:bcpg-jdk15on:1.55`.

The (confusingly structured) [Bouncy Castle release notes](http://bouncycastle.org/releasenotes.html) contain the following line for `1.55`:

> Additional search methods have been added to PGP public and secret key rings.

This may or may not be related in some way. A little more info than "It isn't working." might be useful.

**Comment by bryant1410** [comment]
Okay, the thing is it doesn't find the key, because it isn't there:

```
did not find secret key for id 'ABCDEF12' in key source 'file: /home/bryant1410/.gnupg/secring.gpg'
```

And trying with pubring.gpg (which in fact it shouldn't work), it isn't able to parse it:

```
Caused by: org.gradle.api.InvalidUserDataException: Unable to read secret key from file: /home/bryant1410/.gnupg/pubring.gpg (it may not be a PGP secret key ring)
```

**Comment by bryant1410** [comment]
Maybe upgrading this library to that version will work

**Comment by jbgi** [comment]
Any news one this?

**Comment by huxi** [comment]
`brew update` just forced me to upgrade to GnuPG 2.1. Surprisingly, everything was still working.

This is the case because upgrading GnuPG leaves the existing `~/.gnupg/secring.gpg` file alone and is simply importing its content during initial startup.

If you started out with GnuPG 2.1 instead of upgrading from earlier versions, creating a `secring.gpg` file manually appears to be the proper workaround:
```
gpg --export-secret-keys >~/.gnupg/secring.gpg
```
I tested this by replacing my original `secring.gpg` file with a freshly exported one. Signing still worked afterwards.

Keep in mind that you need to repeat this export every time you add a new private key to GnuPG 2.1.

See [What’s new in GnuPG 2.1 - Removal of the secret keyring](https://gnupg.org/faq/whats-new-in-2.1.html#nosecring).

Hope this helps.

**Comment by jbgi** [comment]
@huxi That is also the workaround I found. I forgot to report it here. Thanks for doing it.

**Comment by emlun** [comment]
With a slightly [patched][pull] Gradle you can also use the (currently in alpha) [gpg-signing][gpg-signing] plugin.

[pull]: https://github.com/gradle/gradle/pull/2724
[gpg-signing]: https://github.com/Yubico/gradle-gpg-signing-plugin

**Comment by jkinkead** [comment]
This is quite frustrating, especially when generating new keys (finding the 4-byte ID from gpg is non-obvious). Any chance [the docs](https://docs.gradle.org/current/userguide/signing_plugin.html) could be updated to note the incompatibility?

**Comment by BrainStone** [comment]
And add the simple fix that @huxi provided.

**Comment by jmuia** [comment]
To find the 4-byte ID: `gpg  --list-keys --keyid-format 0xSHORT`

**Comment by benjamin-bader** [comment]
10+ times over the past four years, I've found myself pulling out hair and eventually re-discovering this issue.

This is important, first-party Gradle functionality.  Are there plans to support contemporary versions of GPG?  If not, are there significant blockers, e.g. BouncyCastle is incompatible?  Or is it simply that it hasn't made the cut, and help would be appreciated?

**Comment by emlun** [comment]
Since [Gradle 4.5.1](https://docs.gradle.org/4.5.1/release-notes.html#signing-artifacts-with-gpg-agent) you can use the [`useGpgCmd()` option of the signing plugin](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:using_gpg_agent) to use gpg-agent as the backend instead of Gradle's Java backend. This works fine for me in GPG 2.2.23, and also supports using smartcard keys.

**Comment by xinpengfei520** [comment]
Thank you very much, it solved my problem.

**Comment by benjamin-bader** [comment]
This is very much _not_ a stale issue.  The default signing plugin continues to not work with the default versions of GPG, and it continues to be a nuisance requiring delving into github issues (!) to learn how to properly sign things.

**Comment by szpak** [comment]
@benjamin-bader To be honest, the official documentation clearly says that `useGpgCmd()` should be used for gpg2:
https://docs.gradle.org/7.4.2/userguide/signing_plugin.html#sec:using_gpg_agent

and it seems to work (at least it worked when I last check it 2 or 3 years ago).

Maybe you could propose a PR with the documentation changes to make it more "findable"?

**Comment by Slion** [comment]
Landed here after trying and failing to use the signing plugin with `secring.gpg` generated from GnuPG 2.4.5.
I'm on Windows building from Android Studio. It worked after enabling `useGpgCmd()` and it prompted me for my password.
To avoid the password prompt you can provide it from your `gradle.properties` like so:
```
signing.gnupg.keyName=24875D73
signing.gnupg.passphrase=gradle
```

See [above post](https://github.com/gradle/gradle/issues/888#issuecomment-1142579889). Thanks @szpak.

**Comment by mendhak** [comment]
I've been able to follow that for Github Actions, I set the passphrase as a Github Secret, then access the secret like so:   

    run: ./gradlew assembleRelease -Psigning.gnupg.passphrase=${{ secrets.GPG_SIGNING_PASSWORD }} -Psigning.gnupg.executable=gpg

**Comment by ov7a** [comment]
Sorry for the late reply.

The documentation was updated a couple of times since the issue was requalified as a documentation issue. This issue will be closed as obsolete.

If you have suggestions on how to improve the docs, please open a new issue.
