### ISSUE TITLE
Create default task to get and set project version

### ISSUE THREAD

**Issue by feanor777** [gradle/gradle#8883]
Add the possibility to get and set project version using the default Gradle task.
For example, like in Versions Maven Plugin (https://www.mojohaus.org/versions-maven-plugin/index.html)
Right now to get project version in Gradle need to write some terrible thing, like this:
`./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'
`
And to set project from the command line - just impossible.
For example, during integration with different Jenkins plugins, they need the project version and it works ok with maven, but with Gradle need to use different hacks.

**Comment by big-guy** [comment]
I don't think we're going to add something like this built-in, at least, nothing specifically for version.

If you need to print the version number of your project, you can add:
```
task printVersion {
   doLast { 
       logger.lifecycle(project.version)
   }
}
```
And run it `gradle printVersion`.  

If you want to derive your project's version from the command-line, you can do that too:
```
version = findProperty("cliVersion") ?: "1.0.0" // default to 1.0.0 if unspecified
```

There are release plugins that try to handle some of these things for you: https://github.com/researchgate/gradle-release

**Comment by borys-zora** [comment]
in this case you can not automate gradle project and maven wins generic automation ;)
I am trying to get version number of project to create release tag then using https://github.com/JavatarPro/declarative-pipeline
with maven I can do the job easily, but with gradle you should force to create some kind of method to work with it
maven:
https://github.com/JavatarPro/declarative-pipeline/blob/master/src/pro/javatar/pipeline/service/impl/MavenBuildService.groovy
gradle (in progress):
https://github.com/JavatarPro/declarative-pipeline/blob/CD-16-add-gradle-and-nomad-support/src/pro/javatar/pipeline/service/impl/GradleBuildService.groovy
I rely on that who will use declarative pipeline must use plain **version** property

**Comment by lacasseio** [comment]
Issues like this have a think-outside-the-box-solution. Gradle manages automatic version update by [using a text file](https://github.com/gradle/gradle/blob/master/version.txt) that you can update using `file('version.txt').txt = "new.version.number"`. There is a ton of ways to manage project version and upgrade them for releases. Gradle is flexible enough for every type of automation without being opinionated on a specific release pipeline.

**Comment by borys-zora** [comment]
So you even your project is released in strange way. Instead of providing out-of-the-box solution you force to think-out-of-the-box each project. Issues are in that everybody will invent their own way. I guess you are using standard WIFI  protocol and standard HTTP protocol, on your logic, everybody could send different messages why we should bothers with these RFCs, JSRs, language apis and libraries, everybody can write same library in their own way ...
I understand that you will not provide standard way, thanks that you give me one of the thousands ways how it could be done with very flexible gradle
