### ISSUE TITLE
Unauthorized message for repo.gradle.org

### ISSUE THREAD

**Issue by Neumsy** [gradle/gradle#8893]
When we perform a build of our applications, we receive the following error when attempting to resolve dependencies.
   > Could not resolve all files for configuration ':detachedConfiguration1'.
      > Could not resolve org.eclipse.platform:org.eclipse.text:[3.8.0,4.0.0).
        Required by:
            project : > com.diffplug.spotless:spotless-eclipse-groovy:2.9.2 > org.eclipse.platform:org.eclipse.jface.text:3.15.100
         > Failed to list versions for org.eclipse.platform:org.eclipse.text.
            > Unable to load Maven meta-data from <our artifactory server>/gradle-transitive-plugin-repo/org/eclipse/platform/org.eclipse.text/maven-metadata.xml.
               > Could not HEAD '<our artifactory server>/gradle-transitive-plugin-repo/org/eclipse/platform/org.eclipse.text/maven-metadata.xml'.
                  > Read timed out

We are using our Artifactory server as a proxy to the outside world.  We started seeing this issue on 3/25/2019.  The error we are seeing in Artifactory is:
2019-03-29 07:37:18,885 [https-jsse-nio-157.154.59.30-8443-exec-2847] [INFO ] (o.a.r.RemoteRepoBase:1024) - Error listing remote resources https://repo.gradle.org/gradle/libs-releases-local/org/eclipse/platform/org.eclipse.text/3.8.100: Unable to retrieve https://repo.gradle.org/gradle/libs-releases-local/org/eclipse/platform/org.eclipse.text/3.8.100/: 401: Unauthorized (remote response: 401: Unauthorized)

### Expected Behavior
The dependency for the eclipse modules should not time out and be resolved.

### Current Behavior
Build fails and timeout message is received.  401 error is received by artifactory

### Context
This prevents our users from performing successful builds as the dependency tree can not be updated.

### Steps to Reproduce 
Include a dependency to com.diffplug.spotless:spotless-eclipse-groovy:2.9.2 as an anonymous user

**Comment by ljacomet** [comment]
Did you start using a new plugin?
Plugin dependencies should be served from their source repository, not `repo.gradle.org`.

For example, `org.eclipse.platform:org.eclipse.text` can be found in Maven Central.

So adding `mavenCentral()` to your buildscript repository would solve the issue.

Also when hitting these URLs, I get a 404 not a 401, so something else is happening with your Artifactory instance.

**Comment by Neumsy** [comment]
We did not change anything on our end.  Our Artifactory server just serves as a relay to maven central and other repositories external to our company.  This is so developers only have to hit our repository and Artifactory pulls in what is required from the outside world.  

Our transitive repositories in Artifactory do hit against Maven Central as part of the resolve path.  Due to the 401/404 error, I believe it is then timing out without trying to other repositories which are in the resolution path.

**Comment by ljacomet** [comment]
Unless you provide more information that help pinpoint the issue to be on the Gradle side, there is nothing more that can be done.

No one else has reported suddenly seeing `401` instead of expected `404` for these URLs.

**Comment by ljacomet** [comment]
Please re-open if you can add more information pinpointing the issue to Gradle infrastructure.
