### ISSUE TITLE
Improve provider error message when no value has been specified

### ISSUE THREAD

**Issue by melix** [gradle/gradle#8904]
### Context

Whenever a `Provider<T>` value is not set, the build fails with a generic error message:

```
> No value has been specified for this provider.
```

It does _not_ indicate which provider it is. To understand what is going on, the user needs to run with `--stacktrace` and look at source code, which is not particularly easy.

**Comment by vlsi** [comment]
+1

What if `Provider.name(String): Provider` method was added to enable adding the clarification?
Or even `Provider.description(String): Provider`

**Comment by lacasseio** [comment]
I think there's a lot we can improve without needing a new method on the Provider API. For starter, we can capture where it was created and where the value was configure (if explicitly set to null).

**Comment by vlsi** [comment]
I'm afraid capturing stacktraces would impact performance (especially for Java 8).

However, it might be a very good idea to print some frames from the actual stacktrace.

**Comment by adammurdoch** [comment]
@vlsi regarding the behaviour of `convention()`, this has been improved in Gradle 5.6 (https://github.com/gradle/gradle/issues/8635).

**Comment by vlsi** [comment]
>adammurdoch: regarding the behaviour of convention(), this has been improved in Gradle 5.6 

Thanks, that is nice. In the mean time I'm using `.value(nullable)` which produces the behavior I want.

>lacasseio: I think there's a lot we can improve without needing a new method on the Provider API

Here's a sample:

`rc` property specified "release candidate index". It is taken from the command line (e.g. `-Prc=4`)
Then `rc` property is used in a template for `release candidate tag`.


Then there's a `validateParams` task that validates if `release candidate tag` is already present.
It uses `val rcTagName = rcTag.get()` to get the actual tag name.
That line fails in case `-Prc` was not provided. The failure itself is expected, however the message is somewhat obscure.

Unfortunately, the failure message does not trace back to `rc`.
Of course I might group my validations so that `rc` validation is the first, and dependent validations (e.g. tags) are performed only in case `rc` succeeds, however it would be nice if `rcTag.get()` could produce a meaningful error message.

```
open class ReleaseExtension @Inject constructor(
    private val project: Project,
    objects: ObjectFactory
) {

    val rc = objects.property<Int>()
        .value(
            project.stringProperty("rc")?.toInt()
        )

    val releaseTag = objects.property<String>()
        .convention(project.provider { "v${project.version}" })

    val rcTag = objects.property<String>()
        .convention(releaseTag.map { "$it-rc" + rc.get() })
```

Relevant stacktrace (`ReleaseExtension.kt:86` is the line that calls `rcTag.get()`): 

```
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:154)
        at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:49)
        at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:49)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:154)
        at com.github.vlsi.gradle.release.ReleaseExtension$$special$$inlined$apply$lambda$4.run(ReleaseExtension.kt:86)
        at com.github.vlsi.gradle.release.StageVoteReleasePlugin$configureRoot$validateParams$1$1.execute(StageVoteReleasePlugin.kt:83)
        at com.github.vlsi.gradle.release.StageVoteReleasePlugin$configureRoot$validateParams$1$1.execute(StageVoteReleasePlugin.kt:38)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
```

**Comment by adammurdoch** [comment]
Some improvements were made in https://github.com/gradle/gradle/pull/10371.

Now, the error message will (in most cases) include the task or extension and property names. This doesn't work in all cases yet, however, I think this enough to consider this issue as "done" and we can open new issues for further improvements.

**Comment by paulsUsername** [comment]
<img width="986" alt="Screenshot 2019-12-18 at 13 17 51" src="https://user-images.githubusercontent.com/32492218/71089458-cf024700-2198-11ea-8175-0cb685d15ece.png">
Its hard to emphasies how demented this is driving me! I can't get past 5.3.1 becasue of it.

**Comment by adammurdoch** [comment]
@paulsUsername Are you using the most recent version of Gradle? The improvements only happened in Gradle 6.0. However, there may be some edge cases that don't work, so if you are using Gradle 6.0 and still seeing this vague error message could you please open a new issue with some more details. For example, a stack trace or build scan would be very useful. This will help us improve this error message.
