### ISSUE TITLE
ConfigurationContainer.register action should run first

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#8906]
### Expected Behavior

When declaring `ConfigurationContainer.register` with that action, I expect that the action will be executed before any other hooks added by `ConfigurationContainer.configureEach`, regardless of when they were added.

### Current Behavior

The register configurationAction is actually executed after any `configureEach` that have already been added to the `ConfigurationContainer`.

### Context

It's hard to write code such as:

```gradle
configurations.configureEach {
    if (!it.isCanBeConsumed()) {
        return
    }
    // logic
}
```

Because this might or might not catch java's `compileClasspath` configuration for instance, if the above code is run before the java plugin is applied.

### Steps to Reproduce 

1. Declare a configureEach action that prints the configuration name
2. register a configuration via `configurations.register`, and print something from its register action
3. realize the configuration (e.g. by getting them)
4. the configureEach action is shown to run first

### Your Environment

https://github.com/dansanduleac/gradle-test/tree/ds/register-configure-each

Build scan URL: https://scans.gradle.com/s/kin5v52slvpmc

**Comment by ljacomet** [comment]
This looks like a more general issue between the contract of `DomainObjectCollection.configureEach` and `NamedDomainObjectContainer.register(java.lang.String, org.gradle.api.Action<? super T>)`.

As reported, it would make sense that a newly registered instance sees its `configurationAction` applied first before any external one.

@gradle/core Any one cares to have a look?

**Comment by big-guy** [comment]
This was intentionally chosen to do what it does to make it consistent with the existing APIs and less surprising (order is the order of application like everywhere else). We considered making the configuration action passed via register (and maybe create) special and run first, but I don't think it helps here.

How would an early configuration action help in this particular example? The way the Java plugin adds the `compileClasspath` Configuration doesn't rely on the configuration action to `register()` or `create()`.  We create the Configuration and then configure the instance directly. canBeResolved and canBeConsumed are both very obvious "this should never change" properties, but that's not as clear with everything else.  I think we want more of a lifecycle of a domain object than an implicit rule that you can read values if the "first" configuration action has happened.  It just becomes a race to be "first" at that point.

I think `configureEach` is the wrong tool to try to iterate through a container and do something else, like create more tasks or other domain objects. It relies on configurations being realized to do any work. I see a couple of options:

- Use `configurations.filter {}` to select the Configurations you need to look at later (e.g., as part of a task action). Do this if you're using `configurations.configureEach` to build a list.
- Keep using `configurations.all` + afterEvaluate.  Configurations aren't lazy right now, so it doesn't make sense to try until other work is done.

We're missing a few pieces of the API to make "derive the configuration of this from the configuration of that" work lazily. You highlighted another good thing that's unfinished here https://github.com/gradle/gradle/issues/8943.

If what you ultimately wanted was something like "for each configuration, have a task that resolves it" (for whatever reason), it would be nice if you could do (this is made up):
```
tasks.from(configurations.map { confs ->
    // all configurations have been configured completely and finalized.
    return confs.filter(it.canBeResolved).collect { conf ->
        tasks.create(conf.name + "Resolve", ConfResolver) {
            resolve = conf
        }
    }
})
```

I don't think we need/want to change the ordering here.  _Maybe_ there's an opt-in "early configuration" we would want, but I don't have a good example that couldn't be solved with an existing pattern and doesn't make things more complicated.  Do you have a fuller example of what you were trying to accomplish?

**Comment by dansanduleac** [comment]
> "for each configuration, have a task that resolves it"

I think you hit the nail on the head there @big-guy!
I agree it is a bit risky to special case lazy actions in order to ensure they happen before other lazy actions, but if the API were more explicit in distinguishing lazy producers ("configurators", let's say) from lazy consumers, then this would be solved while getting rid of all the ordering ambiguity.

In terms of what I planned to use this with, I was trying to copy all consumable configurations, in order to resolve them as part of writing a lock file. I'm doing this in order to prevent involving existing configurations in resolution, because as soon as I write the lock file, I then add the locked versions as constraints onto the original configurations involved.
(as part of https://github.com/palantir/gradle-consistent-versions)

You are right that `afterEvaluate` + `all` works in this particular case, though. I think I was just eagerly trying to be lazy since I noticed the new lazy configuration constructors, but since this is not fully fleshed out, there's no point in doing that yet.

**Comment by noproxy** [comment]
The same issue troubles iterating TaskContainer, too.

In my opinion, action registered against specific task should be evaluated in the order they are added.

1. **Without lazy initialization**, the below code will be evaluated as: action1 -> action2 -> action3.

```
tasks.create("exampleTask") { (action 1)
     ...
}

tasks["exampleTask"].configure { (action 2)
    ...
}

tasks.all { (action 3)
    ...
}
```

2. When it's coming to **lazy initialization**, the order should honor the order that the lazy action is registered.

```
tasks.register("exampleTask") { (action 1)
     ...
}

tasks["exampleTask"].registerConfiguringAction { (action 2)
    ...
}

tasks.all {
    registerConfiguringAction { (action 3)
        ...
    }
}
```
The actions should also be executed in oder as:  action1 -> action2 -> action3.

I think the problem is that there is no such method like 'registerConfiguringAction'. 

We have:
- tasks.create: expected to be executed **at once**
- task.configure: expected to be executed **at once**
- tasks.register: expected to be executed **lazily**
- task.???: expected to be executed **lazily**

Anyway, I can now use `afterEvaluate` + `all` as a workaround. But if the `all` action should always be used combined with `afterEvaluate`, it seems the reactiveness of the `all`, `matching` of the DomainObjectCollection becomes less meaningful.

**Comment by lacasseio** [comment]
What you are searching here is:
 - `task['exampleTask'].configure {}` lazy equivalent is [`tasks.named('exampleTask') {}`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskCollection.html#named-java.lang.String-org.gradle.api.Action-) or [`TaskProvider#configure(Action)`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskProvider.html#configure-org.gradle.api.Action-).
 - `tasks.all {}` lazy equivalent is [`tasks.configureEach {}`](https://docs.gradle.org/current/javadoc/org/gradle/api/DomainObjectCollection.html#configureEach-org.gradle.api.Action-)

All of these equivalents are covered in the [Task Configuration Avoidance chapter](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview).

**Comment by noproxy** [comment]
@lacasseio Thanks for guidance.

I had tried ``configureEach`` but it didn't work yet which really confused me. I finally find my problem is that I added the configure action before task registering.

**Comment by lacasseio** [comment]
Yes, unfortunately, actions are executed in the order they are added. The confusion is the action added by `create` or `register` aren't executed first but instead added to the list of action to execute when the `Task` is realized. The action execution order is the same for `create` vs `register` so the migration between both APIs is seamless.
