### ISSUE TITLE
Improve feature variant API

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#8907]
The current feature variant API is ungainly, verbose & error-prone.

### Current Behavior
```
java {
    registerFeature("mysqlSupport") {
        usingSourceSet(sourceSets["main"])
        capability("org.gradle.demo", "producer-db-support", "1.0")
        capability("org.gradle.demo", "producer-mysql-support", "1.0")
    }
    registerFeature("postgresSupport") {
        usingSourceSet(sourceSets["main"])
        capability("org.gradle.demo", "producer-db-support", "1.0")
        capability("org.gradle.demo", "producer-postgres-support", "1.0")
    }
    registerFeature("mongoSupport") {
        usingSourceSet(sourceSets["main"])
        capability("org.gradle.demo", "producer-db-support", "1.0")
        capability("org.gradle.demo", "producer-mongo-support", "1.0")
    }
}

dependencies {
    "mysqlSupportImplementation"("mysql:mysql-connector-java:8.0.14")
    "postgresSupportImplementation"("org.postgresql:postgresql:42.2.5")
    "mongoSupportImplementation"("org.mongodb:mongodb-driver-sync:3.9.1")
}
```

### Expected Behavior
Should be something like:

```
java {
    registerServiceFeature("dbSupport") {
        registerServiceProvider("mysqlSupport", "postgresSupport", "mongoSupport") {
            usingSourceSet(sourceSets["main"])
        }
    }
}

dependencies {
    "mysqlSupportImplementation"("mysql:mysql-connector-java:8.0.14")
    "postgresSupportImplementation"("org.postgresql:postgresql:42.2.5")
    "mongoSupportImplementation"("org.mongodb:mongodb-driver-sync:3.9.1")
}
```

Or something like:

```
java {
    registerServiceFeature("dbSupport") {
        usingSourceSet(sourceSets["main"]) // this will apply before start of Action in all subsequent calls to registerServiceProvider(…)
        registerServiceProvider("mysqlSupport") {
            dependencies {
                implementation("mysql:mysql-connector-java:8.0.14")
            }
        }
        registerServiceProvider("postgresSupport") {
            dependencies {
                implementation("org.postgresql:postgresql:42.2.5")
            }
        }
        registerServiceProvider("mongoSupport") {
            dependencies {
                implementation("org.mongodb:mongodb-driver-sync:3.9.1")
            }
        }
    }
}
```

**Comment by ljacomet** [comment]
Both of your proposals make the `capability` aspect disappear. It is however key to that example. So there needs to be a way to express that these features are exclusive _and_ still allow them to be selected by the consumer.

**Comment by rgoldberg** [comment]
I don’t see how the `capability` aspects are no longer available in my proposals. The revamped code would make a default capability for each provider based on its name, and that default could be overridden, just like the current code, by putting each provider in its own call to `registerServiceProvider(…)`, and calling `capability(…)` from the call’s `Action`.

The proposals would also add to each provider  the `capability`s of its enclosing service, which would also have an overridable default based on its name, analogous to the existing code.

Does that address your concerns?

**Comment by rgoldberg** [comment]
This doesn’t have to be limited to two levels of hierarchy; this could support arbitrary depth by using one method instead of two differently named methods. Any call nested in the `Action` of an outer call would inherit the settings of all of its enclosing hierarchy in a cascading manner, like CSS. I just thought that the different method names for service & provider made the relationship more understandable; those two methods could still exist as wrappers around a core method that doesn’t imply only two levels, so that users who need more hierarchy can use it, while the normal two-level case will still have the more descriptive method names.

From what I know, can only have either on/off features (already handled nicely by existing API), and service / provider feature

**Comment by rgoldberg** [comment]
From what I know, can only have either on/off features (already handled nicely by existing API), and service / provider feature

**Comment by rgoldberg** [comment]
From what I know, there are five types of features:

1. Independent optional features (e.g., enables logging in predetermined manner when selected)
2. Mutually exclusive optional features (e.g., will log if single logging provider selected)
3. Mutually exclusive mandatory features (e.g., must select a single logging provider)
4. Non-mutually exclusive optional features (e.g., will log to all selected logging providers)
5. Non-mutually exclusive mandatory features (e.g., must select one or more logging providers)

Types 2 - 5 could be generalized to just a minimum & maximum number of providers that can be selected for a service at one time:

2. 0/1
3. 1/1
4. 0/infinity
5. 1/infinity

These types should be supported by the API.

The hierarchical modification would also be useful for many type 1s, if, e.g., you have 20 type 1s that all apply to the “main” source set, use a container action that doesn’t create a service / provider grouping, but that allows you to call

```
usingSourceSet(sourceSets["main"])
```

once in the group action, which then applies it to the 20 enclosed type 1s, thus saving many lines of code.
