### ISSUE TITLE
Javadoc gradle task deletes files in destination directory

### ISSUE THREAD

**Issue by jwgish** [gradle/gradle#8910]
Upgrading from 4.10 to 5.3 I found that the Javadoc task has introduced new, undocumented behavior.  At the start of the task it cleans the directory.  This breaks existing builds which depended on the old behavior which did not clean the directory.  This is inconsistent with other tasks such as Javac which is non-destructive such that multiple Javac tasks can create classes in the same destination directory,

**Comment by thc202** [comment]
Background #6168.

**Comment by oehme** [comment]
That's intended. Also, you should not let multiple tasks write to the same directory, as that will make them non-cacheable.
