### ISSUE TITLE
Implement autofinalizable org.gradle.api.provider.Property

### ISSUE THREAD

**Issue by Myllyenko** [gradle/gradle#8923]
### Expected Behavior
`Property` implementation should be able to automatically finalize itself on a first call to `get()`.

### Current Behavior
Any `Property` can be freely modified until explicit call to `finalizeValue()`.

### Context
My Gradle plugin exposes properties that are used across multiple parts of a build. If such property is modified between the moments different tasks read it, their results will become inconsistent. To prevent it, I currently use `get()` preceded by `finalizeValue()` which is simple yet quite cumbersome. Having autofinalizable properties will allow to get rid of this boilerplate code.

**Comment by adammurdoch** [comment]
Added via https://github.com/gradle/gradle/pull/11661
