### ISSUE TITLE
Java project with different compilation targets fails after upgrading on Gradle 5.3

### ISSUE THREAD

**Issue by SimY4** [gradle/gradle#8930]
### Expected Behavior

My main and test source sets have different compile targets (java6 for main and java8 for tests). And there's a common module shared between my submodules used only in tests with Java8 compile target.

```
    sourceCompatibility = JavaVersion.VERSION_1_6

    compileTestJava {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    dependencies {
        testImplementation project(':module-with-compile-target-1_8')
    }
```

This should setup compiled fine in gradle 5.2 as it should.

### Current Behavior

After upgrading to gradle 5.3 I'm now getting this error on build:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':my_module:test'.
> Could not resolve all task dependencies for configuration ':my_module:testRuntimeClasspath'.
   > Could not resolve project :module-with-compile-target-1_8.
     Required by:
         project :my_module
      > Unable to find a matching variant of project :module-with-compile-target-1_8:
          - Variant 'apiElements' capability com.example:module-with-compile-target-1_8:1.0.0-SNAPSHOT:
              - Found org.gradle.category 'library' but wasn't required.
              - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
              - Required org.gradle.jvm.version '6' and found incompatible value '8'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api-jars'.
          - Variant 'runtimeElements' capability com.example:module-with-compile-target-1_8:1.0.0-SNAPSHOT:
              - Found org.gradle.category 'library' but wasn't required.
              - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
              - Required org.gradle.jvm.version '6' and found incompatible value '8'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime-jars'.
```

### Context

It stopped working after bumping the gradle version to 5.3. It's still not working in gradle 5.3.1
I would say that this check should take into account that main and test compile targets may be different.

### Steps to Reproduce 
Sample project can be found here:
https://github.com/SimY4/xpath-to-xml/tree/java6
`Java6` is the name of a branch is which main sourceSet is configured with java 6 compile target and test source set is configured with java 8 compile target.

### Your Environment
-

**Comment by melix** [comment]
Thanks for reporting. This is _kind of_ expected since the default is to use the Java extension target compatibility level as the requirement `java { targetCompatibility = ... }`. If it's not the case, you can override the default explicitly:

```
configurations {
   testCompileClasspath {
        attributes {
            attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 8)
        }
   }
}
```

**Comment by SimY4** [comment]
@melix Thank you to such a quick response.

I didn't quite get what is expected and what's the suggested solution. Can you elaborate a little on what you're proposing?

I've set the source and target for the main sourceSet to Java6 and I've set source and target for test sourceSet to Java8. I guess the feature here is that java8 targeting modules can't be matched with java6 targeting modules. But tests source set is targeting java8 so it should be fine to match them.

**Comment by melix** [comment]
What is happening is explained https://docs.gradle.org/current/userguide/upgrading_version_5.html#automatic_target_jvm_version[here]. In a nutshell, Gradle checks that your configuration is consistent. If you have a Java 6 module that depends on Java 8 modules, it cannot work, so it will ask you to fix it.

Here, you have a more complex setup, where the tests actually use a different target level. That's fine, but Gradle doesn't "discover" it automatically. The reason is that you set the target level on a _task_, and multiple tasks may contribute to a single source set output. We could try to infer from all the tasks that contribute, but we don't do this. The only place we look at is the Java plugin convention target level. So in special cases like yours, you need to override the default setting, and tell that for the test compile classpath, you expect dependencies with level 8.

**Comment by SimY4** [comment]
@melix Thank you for the detailed explanation. Now I get what's going on.

I added the proposed configuration change to my build and it's still failing with the same error. I applied it for all submodules, I hope that's the right place for it.

**Comment by melix** [comment]
Did you apply the fix to the `testRuntimeClasspath` too?

**Comment by SimY4** [comment]
@melix Nope. It worked after I applied it for testRuntimeClasspath, thanks.
