### ISSUE TITLE
Copy task does not copy empty dirs when no files are present

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle#894]
### Steps to Reproduce
Follow the ["Steps to Reproduce"](https://github.com/eljobe/copies/blob/master/README.md#steps-to-reproduce) in the `README.md` on the reproduction project.
https://github.com/eljobe/copies

### Expected Behavior
See the ["Expected Outcome"](https://github.com/eljobe/copies/blob/master/README.md#expected-outcome) section of the `README.md` on the reproduction project.

### Current Behavior
See the ["Observed Outcome"](https://github.com/eljobe/copies/blob/master/README.md#observed-outcome) section of the `README.md` on the reproduction project.

### Context
Most of the reasoning behind why this bug is important is captured in the JRIA issue from which this bug is copied: https://issues.gradle.org/browse/GRADLE-1643

### Your Environment
 * Build scan URL: https://gradle.com/s/ff4omynwblo6a

**Comment by eriwen** [comment]
Thanks for the excellent example project Pepper!

**Comment by eljobe** [comment]
This is very similar to the problem described in #895
