### ISSUE TITLE
IvyPublication - support for versionMapping

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#8948]
Similar to [`MavenPublication`](https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html), it would be nice if `IvyPublication` supports `versionMapping`.

Example:

```
publishing {
  publications {
    ivy(IvyPublication) {
      from components.java
      versionMapping {
        usage('java-runtime'){
          fromResolutionResult()
        }
      }
    }
  }
}
``` 

Currently this is not supported.

Background: We have ivy and maven repositories and we would like to start using gradle module metadata files. While we already have mechanisms to hook into the ivy descriptor to modify the versions from resolution result, it would be nice if we can apply that as mentioned above so it also happens for gradle module metadata.

Our use case are libraries that always point to `latest.release` and we would like to write the resolved version to gradle metadata file.

**Comment by ljacomet** [comment]
PR has been merged, thanks for the report and the contribution.
