### ISSUE TITLE
Allow to upload artifacts in parallel with `maven-publish`

### ISSUE THREAD

**Issue by e5l** [gradle/gradle#8950]
Our libraries team faced a performance issue with publishing the Ktor framework to Bintray. They had been using the Bintray Gradle plugin for that until they changed to `maven-publish`. The change led to severe publishing time degradation (more than 10x). They suspect that the `maven-publish` plugin does not run artifact upload in parallel, with only one worker doing actual upload and the others waiting.

### Expected Behavior

Parallel artifacts uploading.

### Current Behavior

Sequential uploading: https://github.com/gradle/gradle/blob/7bc44d5b1ec024b1d53c6afb434ffe907de158f7/subprojects/maven/src/main/java/org/gradle/api/publish/maven/tasks/PublishToMavenRepository.java#L81

### Steps to Reproduce 

1. Clone https://github.com/ktorio/ktor/
2. Change publication credentials and repo
3. `./gradlew publish --parallel`

### Your Environment

Build scan URL:
Using the Bintray Gradle plugin: https://scans.gradle.com/s/g5aq6eimp4ii4
Using the `maven-publish` plugin with parallel build *enabled*: https://scans.gradle.com/s/otit6zl5ja2xa
Using `maven-publish`, with parallel build *disabled*: https://scans.gradle.com/s/frzuvwm6wmk54/

**Comment by bigdaz** [comment]
Thanks for the detailed report @e5l. We added that global lock to avoid bugs that were caused by a lack of thread-safety in the Maven libraries we use to publish.

After a little investigation I'm pretty sure we can remove the need for the global lock, which will permit artifact uploads in parallel. Stay tuned!
