### ISSUE TITLE
WindowsStartScriptGenerator uses the wrong classpath

### ISSUE THREAD

**Issue by Octogonapus** [gradle/gradle#8963]
Sorry for deleting the issue template, but this is not so much a bug report as a code issue I noticed when trying to use a custom Windows start script template. `WindowsStartScriptGenerator` accesses a resource using `UnixStartScriptGenerator.class` instead of `WindowsStartScriptGenerator.class` here:
https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/plugins/src/main/java/org/gradle/api/internal/plugins/WindowsStartScriptGenerator.java#L26

If the Gradle team agrees this is an issue, I'd be happy to PR the fix.

**Comment by lacasseio** [comment]
The class is used for loading locating the text file. It's strange to use the `UnixStartScriptGenerator` but doesn't have any effect.
