### ISSUE TITLE
correct documentation for maven-publish

### ISSUE THREAD

**Issue by rburgst** [gradle/gradle#8968]
The current maven-publish  [documentation](https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPublication.html) refers to an example that no longer works with gradle 5.
As of gradle 5 `artifacts` need to be nested in an `afterEvaluate` block.

### Expected Behavior
Documentation for maven-publish should contain correct sample sources.

### Current Behavior
Current documentation shows a sample script that doesnt work with Gradle 5 producing the following error message: 
```
 Could not get unknown property 'sourcesJar' for object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.
```

### Context
See pull request #8966

### Steps to Reproduce 
try out the sample from `subprojects/docs/src/samples/signing/maven-publish/groovy/build.gradle`

**Comment by ljacomet** [comment]
Can you please be more specific?

These samples are run as part of CI and trying `gradle publish` with Gradle 5.3.1, no problems are reported.

**Comment by rburgst** [comment]
ok, I found out the reason, it seems that the `java` plugin generates the sourceJar task itself at a later stage of the configuration phase. Therefore, it doesnt exist at the time when the `publishing` block is evaluated. 

Manually adding the `sourceJar` task as its done in the sample fixes the problem.

**Comment by ljacomet** [comment]
The `java` plugin _does not define_ a `sourceJar` task nor a `javadocJar` task. It only defines a `javadoc` task for generating the Javadoc.

So it is expected that you define `sourceJar` and `javadocJar` yourself if you intend to publish them.

Thanks for following up, closing as there it nothing to act upon.

**Comment by alexandre-thauvin** [comment]
> ok, I found out the reason, it seems that the `java` plugin generates the sourceJar task itself at a later stage of the configuration phase. Therefore, it doesnt exist at the time when the `publishing` block is evaluated.
> 
> Manually adding the `sourceJar` task as its done in the sample fixes the problem.

Hello can you give a snippet of manually adding the sourceJar and javadocJar ? Indeed I have this problem and when I try to add it I have an error related to the Javadoc...

**Comment by rburgst** [comment]
here is a sample for the source jar task

```
apply plugin: "java"
apply plugin: "idea"

apply plugin: "maven-publish"

sourceCompatibility = 11
targetCompatibility = 11

task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    classifier "sources"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
        }
    }

    repositories {
        maven {
            url "..."
            credentials {
                ...
            }
        }
    }
}


dependencies {

...
}
```

**Comment by ljacomet** [comment]
Note that with Gradle 6+, it is recommended to use the provided `withSourcesJar()` and `withJavadocJar()` from [the java extension](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java-extension).
