### ISSUE TITLE
When vm_stat fails when starting a daemon, the entire build fails

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#897]
This causes a `RuntimeException` to be thrown:
https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/health/memory/VmstatAvailableMemory.java#L63-L63

Which, I think was supposed to be guarded against here:
https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/MasterExpirationStrategy.java#L76-L76

But since the `RuntimeException` is not handled, it bubbles up the call stack. `addLowMemoryDaemonExpirationStrategyWhenSupported` is called by `MasterExpirationStrategy`'s constructor.  And `MasterExpirationStrategy` is created in `DaemonServices`.  Any exception occurring during service registry initialization just causes the entire daemon to shutdown.

### Expected Behavior

The build should be able to continue working even if we cannot run vm_stat.

### Current Behavior

The daemon randomly fails to start.  This occurs deep in the service registry/initialization code.

### Context

As reported on the forums: 
https://discuss.gradle.org/t/build-stops-with-message-gradle-build-daemon-has-been-stopped-service-stop/20517/4

### Steps to Reproduce (for bugs)

This happens randomly due to /usr/bin/vm_stat failing.  I don't know of a reliable way to make it fail.

### Your Environment

This affects macOS only.

### Implementation comments

There are a few oddities for me with the current implementation of `MemoryInfo` and the various `AvailableMemory` types and how it interacts with the expiration strategies.  I would expect `DefaultExecActionFactory` to be injected from somewhere.  I would also expect `AvailableMemory` instances to be reused due to the comment in `VmstatAvailableMemory`, but maybe this is intentional to prevent state from bleeding between health checks.

To fix the service injection, I think you could pull `MemoryInfo` up to `DaemonServices`, inject the appropriate `AvailableMemory` and determine the type of `AvailableMemory` in the service registry (instead of in `MemoryInfo`).  That way you don't have to carry the dependencies for all the different types of `AvailableMemory`s around in `MemoryInfo`.

I think we should also change the way the `LowMemoryDaemonExpirationStrategy` is added to `MasterExpirationStrategy` so that we don't rely on exception handling from `checkExpiration` telling us if we should use `LowMemoryDaemonExpirationStrategy`.  I think it makes sense to just always add it and handle the failure elsewhere.  Maybe this can just be a `AvailableMemory` that returns `-1` (or MAX_INT) if the underlying implementation fails once.

**Comment by big-guy** [comment]
And as a separate thing, we should consider adding whatever functionality we need to do this natively into `native-platform` instead of forking a process and scraping its output.

**Comment by adammurdoch** [comment]
I plan to add some way to query memory to `native-platform` at some point.

**Comment by eskatos** [comment]
Thanks @big-guy for the detailed report and your insights.

Detangling memory health-checks and expirations strategies will be handled out of this issue which really is about a bug that can be fixed right away in isolation.

**Comment by big-guy** [comment]
LGTM @eskatos
