### ISSUE TITLE
Dependency locking does not properly fail build with incompatible "force" resolution strategy

### ISSUE THREAD

**Issue by seanabraham** [gradle/gradle#8971]
When using dependency locking, a "force" rule on a resolution strategy can subvert a locked version and the build does not fail.

### Expected Behavior
As explained in the repro, the build should fail if the final resolution differs from what is specified in the lock state.

### Current Behavior
The build succeeds despite resolution differences

### Context
This issue prevents the usage of dependency locking in my project since using a resolution strategy can violate what is expected behavior with dependency lock state present.

### Steps to Reproduce 
https://github.com/seanabraham/resolution-force-gradle-repro

### Your Environment
Build scan URL: https://scans.gradle.com/s/le6jaoot65smi
This is the build scan where the build succeeded when I would expect it to fail.

**Comment by ljacomet** [comment]
Thanks for the report, locking should indeed detect that scenario and fail accordingly.

Note that otherwise, it is by design that the `force` feature can overwrite / ignore a `strictly` constraint.

**Comment by seanabraham** [comment]
I see. Thanks for the context re: `force` vs `strictly`, that's good for me to keep in mind.
