### ISSUE TITLE
Can't Reference nested Kotlin objects in buildSrc

### ISSUE THREAD

**Issue by AndrewReitz** [gradle/gradle#8977]
If I have a nested objects in kotlin in buildSrc with no package, I get a build failure saying that I can't reference the nested object. If I add a package the issue goes away, and I wasn't able to reproduce if the build script is in kotlin. 

Example of Issue Here:
https://github.com/AndrewReitz/gradle-kotlin-buildSrc-issue

**Comment by big-guy** [comment]
@melix I think this might be related to how we look up "nested" classes in a Groovy build script?  Does this look familiar?

**Comment by big-guy** [comment]
I don't think this is a Kotlin problem, but maybe you've seen this before @bamboo @eskatos ?

**Comment by G00fY2** [comment]
@AndrewReitz not sure if you are still looking for a solution.

What I ended up doing was moving the objects into a file and defined a package. For example:
```
package Libs

object Dagger {
    const val core = "something:something:dagger${Versions.something}"
}
```

This gives you the same Syntax and works with Groovy. :)
