### ISSUE TITLE
Regression: Kotlin classes from project dependency of multi module project not included in compile classpath. Worked in Gradle 5.2, stopped working in Gradle 5.3.

### ISSUE THREAD

**Issue by viktornordling** [gradle/gradle#8980]
A multi module project with Kotlin source code, which used to work, stops working after upgrading to Gradle 5.3, because the Kotlin classes from the `compile project('other-module')` dependency are not found.

### Expected Behavior
The Kotlin classes in the `compile project('other-module')` dependency should be found.

### Current Behavior
The Kotlin classes in the `compile project('other-module')` dependency are not found:

```
e: /Volumes/git/projects/gradle/multi/greeter/src/main/kotlin/use/some/kkk/User.kt: (3, 8): Unresolved reference: some
e: /Volumes/git/projects/gradle/multi/greeter/src/main/kotlin/use/some/kkk/User.kt: (7, 9): Unresolved reference: Thang
```

### Context
- Works in Gradle 5.2.
- Doesn't work in Gradle 5.3

### Steps to Reproduce 
See https://github.com/viktornordling/gradle-multimodule-kotlin-bug

**Comment by ljacomet** [comment]
Your sample uses `org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0`. If I replace this dependency versions `1.3.0` with any more recent version, like `1.3.10` or above, the problem disappears.

So while I understand it is not great to having such breaking changes, there is a workaround.

**Comment by viktornordling** [comment]
Thanks @ljacomet . I'm happy to close this issue then, hopefully someone else who gets caught on this can find this issue and spend less time than I did.. 😊

**Comment by houshuai0816** [comment]
I also encountered this problem, but using your way of change, still did not succeed.

**Comment by houshuai0816** [comment]
Bug Project addr is https://github.com/houshuai0816/gradle-multimodule-kotlin-bug

**Comment by houshuai0816** [comment]
@viktornordling @ljacomet

**Comment by viktornordling** [comment]
@houshuai0816 , in my case I can clearly show this worked with Gradle 5.2 but not with Gradle 5.3. Can you show that this once worked (with some version of Gradle)? 

If not, it's probably not a regression and probably not related to this issue in any way.
