### ISSUE TITLE
Maven publish should retry publication on transient remote errors

### ISSUE THREAD

**Issue by srivettepalantir** [gradle/gradle#8992]
Expected Behavior:

I would expect it to be easily possible to configure maven-publish to retry the PUT requests to remote services like artifactory that suffer from network and service level transient flakes.

Current behavior:

 A single transient publication 503 from remote artifactory in a >300 project build causes the entire build to fail.  There is no externally configurable way to enable retries to add resilience to transient network and artifactory flakes.

Context:

 I have a publication job that runs many, many times a day in a complex project that publishes hundreds of artifacts to a remote artifactory server.  The artifactory server has a small error rate where it flickers and throws the occasional 503.  This causes the whole build to fail and is quite painful.  I would expect gradle’s maven-publish plugin to offer configuration for retries against remote publication.  This seems related to https://github.com/gradle/gradle/issues/4629 but in regards to publication rather than resolution.

**Comment by srivettepalantir** [comment]
I'm currently working a PR to achieve this.

**Comment by ljacomet** [comment]
Reflection about another issue that could come out as a result of these retries:

The repository received the upload but did not communicate that back to the build. Upon retry, it fails saying that the file exists already.

I do not think that should be handled in any automated fashion as there would most likely be no way to differentiate between this build having done the upload and a previous (potentially different) one having done so and thus we should certainly not be optimistic about these errors.

**Comment by ljacomet** [comment]
The PR adding this support has been merged, closing.
