### ISSUE TITLE
Checkstyle tasks unnecessarily depend on compiled output

### ISSUE THREAD

**Issue by ldaley** [gradle/gradle#8995]
Checkstyle is a source file processor, we are currently forcing it to be run after we compile the source which doesn't make sense. 

https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CheckstylePlugin.java#L164

**Comment by adammurdoch** [comment]
There are some checks that use the bytecode. Potentially we can figure out whether those checks are being used (or have some way to declare this) and wire in the dependencies accordingly. Or perhaps split the checks into separate tasks.
