### ISSUE TITLE
Exception with hidden cause during annotation processing

### ISSUE THREAD

**Issue by mleveill** [gradle/gradle#8996]
### Expected Behavior
When an exception is thrown during annotation processing, it should include the underlying cause (the original exception) so that the developer can fix the issue.

### Current Behavior
An exception is caught in AnnotationProcessingCompileTask.instantiateProcessor and the code then throws an IllegalArgumentException without including the original caught exception as the cause. This makes it impossible to identify the cause of the exception.

The AnnotationProcessingCompileTask.loadProcessor method does the same thing.

### Context
I had not included all dependencies needed by the annotation processor on the annotation processor classpath. The underlying cause was a ClassNotFoundException, however I couldn't see that until I edited the source for AnnotationProcessingCompileTask.

So the ClassNotFoundException was caught in AnnotationProcessingCompileTask.instantiateProcessor and not included as the cause of the IllegalArgumentException thrown from this method.

### Proposed changes
Simply pass the original exception as the 2nd parameter to the new IllegalArgumentException throw in both AnnotationProcessingCompileTask's instantiateProcessor and loadProcessor methods. I've confirmed this fixes the issue and I don't imagine this will have any side-effects.

### Stack trace
The stack trace should've looked like this but was missing all the "Caused by" lines.

Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileGenerateJava'.
Caused by: java.lang.IllegalArgumentException: Could not instantiate annotation processor 'com.example.SomeAnnotationProcessor'
	at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.instantiateProcessor(AnnotationProcessingCompileTask.java:150)
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoClassDefFoundError: com/example/ExampleAnnotation
Caused by: java.lang.ClassNotFoundException: com.example.ExampleAnnotation

**Comment by big-guy** [comment]
@mleveill Do you have an example project you could share?

**Comment by mleveill** [comment]
Sure, here's a minimal example: https://github.com/mleveill/gradle-annotation-processing-8996

**Comment by bmuskalla** [comment]
Thanks again @mleveill

**Comment by Bennett-Lynch** [comment]
@bmuskalla I stumbled upon something similar recently. A build failure simply gave the output:

```
* What went wrong:
Execution failed for task ':compileJava'.
> com/google/common/collect/ImmutableSet
```

Including `--stacktrace` does give the more helpful message:

```
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableSet
```

But it would be nice if the full `Throwable#toString()` was included in the basic failure message, rather than just `Throwable#getMessage()`.

**Comment by mleveill** [comment]
@Bennett-Lynch Looks like your issue only happens in some circumstances.

`Throwable.getMessage` is used when the annotation processor has a static field referencing a missing class (or if the class of the static field itself has a static field referencing a missing class, and so on recursively). It's also used when a static initializer throws a `NoClassDefFoundError`.

Whereas `Throwable.toString` is used when an annotation processor's constructor or methods run. It's also used when a static initializer throws a `RuntimeException`, unfortunately it's called on the `ExceptionInInitializerError` instead of the `RuntimeException` causing it.

I think these should be our goals for these error messages:
1. Indicate which annotation processor is faulty or misconfigured.
2. Give enough detail so the user can take action.
3. Don't necessitate a re-run with `--stacktrace` for this info.

My proposed changes are in AnnotationProcessingCompileTask `loadProcessor` and `instantiateProcessor`:
```
// loadProcessor:
} catch (LinkageError | ClassNotFoundException ex) {
    String msg = "Annotation processor '" + declaredProcessor.getClassName()
               + "' not found/loaded because: " + unwrapMessage(ex);
    throw new RuntimeException(msg, ex);
}

// instantiateProcessor (slightly different because loadProcessor won't throw a RuntimeException nor InvocationTargetException):
} catch (LinkageError | RuntimeException origEx) {
    Exception unwrapped = unwrapCause(origEx);
    String msg = "Could not instantiate annotation processor '"
               + processorClass.getName() + "' because: " + unwrapMessage(unwrapped);
    throw new RuntimeException(msg, unwrapped);
}

private String unwrapMessage(Throwable throwable) {
    if (throwable instanceof ExceptionInInitializerError) {
        return throwable.getCause().toString();
    }
    return throwable.toString();
}
```
This will produce errors like:
- `Could not instantiate annotation processor XXX because: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableSet`
- `Could not instantiate annotation processor XXX because: java.lang.ArrayIndexOutOfBoundsException: ...`


No `--stacktrace` re-run required to figure out which processor is problematic, nor to get the exact details.

For comparison, here are errors currently emitted:
- `com/google/common/collect/ImmutableSet`
- `java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableSet`
- `java.lang.ExceptionInInitializerError`
- `java.lang.ArrayIndexOutOfBoundsException: ...`
- `Could not instantiate annotation processor XXX`

I've made a branch to reproduce @Bennett-Lynch's error message here: https://github.com/mleveill/gradle-annotation-processing-8996/tree/NoClassDefFoundError

This file has the static field causing the error message: https://github.com/mleveill/gradle-annotation-processing-8996/blob/NoClassDefFoundError/src/processors/java/com/example/gradle/i8996/FaultyProcessor.java
