### ISSUE TITLE
Embedded compiler does not find `-path` warnings

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#900]
In the Gradle build we [changed](https://github.com/gradle/gradle/blob/1a416789f178c869dd31e64acfae2a8aa137bc77/gradle/compile.gradle#L22-L22) running Java compilation from embedded to forked.
After using forked Java compilation the build started to fail.
It seems like the `path` warnings caused by the [Manifest of the launcher jar](https://github.com/gradle/gradle/blob/f823b80e34130d63047232cd86e303e6f91d8b59/subprojects/launcher/launcher.gradle#L47-L47) referencing `core.jar` and `base-services.jar` via `Class-Path` where either not created or not captured when using embedded compilation.

### Expected Behavior
Embedded compilation fails when referencing paths in the Manifest of a jar on the classpath which do not exist.

### Current Behavior
Embedded Java compilation succeeds.

### Context
See above.

### Steps to Reproduce (for bugs)
Remove `'-Xlint:-path'` from [compile.gradle](https://github.com/gradle/gradle/blob/1a416789f178c869dd31e64acfae2a8aa137bc77/gradle/compile.gradle#L36-L36) and run `:idePlay:compileJava` in the Gradle build.

**Comment by eriwen** [comment]
@wolfs I'm not sure how to classify this. Is this a bug in the Gradle distribution or just our own build?

**Comment by wolfs** [comment]
That's a bug in the Gradle distribution - embedded compilation and forked compilation should yield the same compiler warnings.

**Comment by wolfs** [comment]
This didn't come up for me again, so I'll close this issue for now.
