### ISSUE TITLE
Change the TestReport task to aggregate from XML results, not binary results

### ISSUE THREAD

**Issue by Arthurm1** [gradle/gradle#9006]
### Issue
Currently the TestReport task uses the JUnit test result files from the binary directories of subprojects to produce an aggregated output in HTML.  This binary file format is internal to Gradle.  I was hoping this task could be changed to aggregate from the XML files instead.  This would mean that projects that use non-JUnit tests but still produce JUnit XML output would be included in the aggregated report.

### Expected Behavior
The task could (I hope) use the JUnit XML format test results as sources.

### Current Behavior
The task uses the Gradle binary format test results as sources as seen roughly here...
https://github.com/gradle/gradle/blob/00dd03f4d8dc6f6949cf9ecf4aed903366c74da6/subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/TestReport.java#L153

### Context
I'm using the `com.github.maiflai.scalatest` plugin to run ScalaTest tests as well as Java JUnit tests in a mixed Scala and Java environment.  The TestReport task aggregates only the Java JUnit results because the Scala tests only output in XML/HTML so the Scala results are silently ignored.

My current workaround is to use the Jenkins JUnit plugin to aggregate the test results as this uses XML sources but I'm trying to move away from Jenkins.

**Comment by big-guy** [comment]
I don't think we'll get to this any time soon, but as another option, you could switch to using the JUnit runner for ScalaTest:
http://www.scalatest.org/user_guide/using_junit_runner

And this would let you run without `com.github.maiflai.scalatest` and everything should "just work".

**Comment by Arthurm1** [comment]
@big-guy Thanks for the info - and for Gradle :-) - but I don't think the JUnit runners work (yet) with JUnit 5.  At least I can't find any info on how to migrate scalatests with runners from JUnit 4.  My own fault for upgrading.  Jenkins works fine in my workflow so no urgency.

**Comment by big-guy** [comment]
You could use JUnit4 with Gradle too.  Maybe there's some way to do this with JUnit5, @marcphilipp ?

**Comment by marcphilipp** [comment]
You can use runners on JUnit 5 (the JUnit Platform to be precise) via the Vintage engine. Alternatively, ScalaTest could provide a `TestEngine` to run on JUnit Platform directly.

**Comment by Arthurm1** [comment]
@marcphilipp Thanks - I didn't realise that `RunWith` was still supplied by the Vintage engine.
