### ISSUE TITLE
Fast way to declare dependencies in `buildSrc` for autocompletion without a full rebuild

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#9008]
I like to declare dependencies in `buildSrc` for autocompletion in gradle scripts.

```kotlin
// in buildSrc
object Versions {
  kotlin = "1.3.21"
}
object Libs {
  object Kotlin {
    stdLib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
  }
}
```
In my groovy gradle scripts, I do the following.

```kotlin
dependencies { implementation Libs.Kotlin.stdLib }
```

This poses a build speed problem - updating the `buildSrc` file to ` kotlin = "1.3.30"` requires a full rebuild. My request is to support autocomplete for dependencies in `buildSrc`, but not requiring a full rebuild of it for a simple version bump.

Some more discussion about this https://www.reddit.com/r/androiddev/comments/b3tiuh/improving_build_speed_in_android_studio/ej3ba3h?utm_source=share&utm_medium=web2x

**Comment by mkobit** [comment]
Related to https://github.com/gradle/gradle/issues/6045 ?

**Comment by LouisCAD** [comment]
For that specific use case, there's this Gradle plugin: https://github.com/jmfayard/refreshVersions
(Full disclosure: I worked on it, for several reasons, one being to avoid the full rebuild on dependencies upgrade, the other one being discovering these available updates).

**Comment by ljacomet** [comment]
This is a topic currently worked on, closing as duplicate.
