### ISSUE TITLE
File renames on matching files not working properly

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9012]
Maybe I'm just using it wrongly, but it more seems to be a bug.

I have this in my Kotlin build script with all three referenced files present:
```kotlin
distributions {
    main {
        contents {
            from("src/main/resources/") {
                include("log4j2.xml")
                include("config-default.properties")
                include("secrets-default.properties")
                into("config")
                filesMatching("*-default*") {
                    println(this)
                    rename("$", ".foo")
                }
            }
        }
    }
}
```
On running `installDist` the output I get is like expected
```
file 'path\to\project\src\main\resources\config-default.properties'
file 'path\to\project\src\main\resources\secrets-default.properties'
```
But the result looks not really like expectd
```
$ ls -1 build/install/project/config/
config-default.properties
log4j2.xml.foo
secrets-default.properties.foo
```
I would have expected config and secrets to have the foo suffix and log4j2.xml to be unmodified.
It looks to me like the rename action is attached to the wrong file or something like that.

**Comment by big-guy** [comment]
[`filesMatching`](https://docs.gradle.org/5.4-rc-1/javadoc/org/gradle/api/file/CopySpec.html#filesMatching-java.lang.Iterable-org.gradle.api.Action-) isn't doing what you think it's doing.

`filesMatching`'s closure is called for each matching file and passed a FileCopyDetails.  This is a common-ish footgun I've seen (`eachFile` does the same).  We should probably add a `rename(...)` method to `FileCopyDetails` that does the obvious thing.  I don't think anyone ever intends to use rename like it works now (from inside a `filesMatching` or `eachFile`).

You could do something like this:
```
distributions {
    main {
        contents {
            from("src/main/resources/") {
                include("log4j2.xml")
                include("config-default.properties")
                include("secrets-default.properties")
                into("config")
                filesMatching("*-default*") {
                    name = name + ".foo"
                }
            }
        }
    }
}
```

**Comment by Vampire** [comment]
Oh, sorry, I thought rename is on the file copy details, not on the copy spec. Actually I think this is not the first time I made this error. :-(

One thing though, why do not all files get the foo suffix but only two of them?

**Comment by big-guy** [comment]
`filesMatching` only runs after the first matching file, which then configures the next file to be copied to be renamed.  If no files matched the pattern, the rename() would never be called.

**Comment by Vampire** [comment]
But nonetheless, if one matched, the `rename` is called on the copy spec and thus should affect all files, shouldn't it?

Oh wait, is the `filesMatching` executed at execution time and the rename for the matching file happened before already? 

Oh, yeah, of course, has to be like that, at configuration time the set of files might not yet be clear.

So how about either adding `rename` (and maybe others) methods to `FileCopyDetails` so that it works as expected, or at least disallow to call the methods of the outer scope. Wasn't there some DSL annotation to prevent this? Or maybe it should be disallowed to change the configuration at execution time generally from within the task.

**Comment by big-guy** [comment]
> So how about either adding rename (and maybe others) methods to FileCopyDetails so that it works as expected, or at least disallow to call the methods of the outer scope. Wasn't there some DSL annotation to prevent this? Or maybe it should be disallowed to change the configuration at execution time generally from within the task.

It should probably be both of these things.

1. Provide API to FileCopyDetails to rename
2. Prevent changes to CopySpec when executing

**Comment by Vampire** [comment]
So do we reopen this issue, is there an issue for this I can vote and watch or will you make a new one?
