### ISSUE TITLE
pluginManagement{} config from init scripts is not given priority over the "settings.gradle" one

### ISSUE THREAD

**Issue by ndifolco** [gradle/gradle#9016]
### Expected Behavior
When adding a pluginManagement{} configuration in an initialization script, it should be given priority over the pluginManagement{} configuration from the "settings.gradle" file.

In instance Gradle should look in the plugin repositories from the initialization script before the plugin repositories from the "settings.gradle" file.

### Current Behavior
When adding a pluginManagement{} configuration in an initialization script, it is not given priority over the pluginManagement{} configuration from the "settings.gradle" one.

In instance Gradle looks in the plugin repositories from the "settings.gradle" file before the plugin repositories from the initialization script.

### Context
Same context than #4920:
At our company, we use an internal Artifactory instance for proxying dependencies from public repositories on developer laptops and CI builds. This increases resolution speed and insulates us from potential downtime in the upstream repositories. It also allows us to seamlessly resolve proprietary dependencies alongside public dependencies.

So it is important that our internal repositories have priority over the public ones.

### Steps to Reproduce 
```
// settings.gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

include ':app'
```

```
// init.gradle
settingsEvaluated { settings ->
    settings.pluginManagement {
        repositories {
            maven {
                url "http://<my artifactory url>/artifactory/maven"
            }
        }
    }
}
```

### Your Environment
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip

**Comment by tbroyer** [comment]
`RepositoryHandler` is a `NamedDomainObjectCollection`, so I suppose you could remove all existing repositories, add yours, then re-add the repositories you initially removed.
We actually do something similar in our init script where we remove all the Maven repositories and add our Sonatype Nexus proxy (we don't re-add repositories afterwards though); and we also warn if there exist other, non-Maven, repositories that we won't be able to proxy through our Nexus.

**Comment by big-guy** [comment]
I think something like @tbroyer suggested is the right thing here.  `settingsEvaluated` means it runs after the settings script is evaluated. 

1. Clear the existing repositories.
2. Add your repositories.
3. Optionally, restore the repositories from step 1.

**Comment by ndifolco** [comment]
Thank you @tbroyer and @big-guy for your support.

Following your suggestions, I did the following modifications to my Gradle initialization script:
```
// init.gradle
settingsEvaluated { settings ->
    settings.pluginManagement {
        // Print repositories collection
        println "Repositories names: " + repositories.getNames()
        // Clear repositories collection
        repositories.clear()
        // Add my Artifactory mirror
        repositories {
            maven {
                url "http://<my artifactory url>/artifactory/maven"
            }
        }
        // Print repositories collection
        println "Repositories names: " + repositories.getNames()
    }
}
```
So now, the pluginManagement{} config from my initialization scripts is overwriting the "settings.gradle" one.
