### ISSUE TITLE
Support @Nested properties on an artifact transform parameters object

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#9029]
When adding an immutable nested property to a transform parameters object, the managed type should be created automatically.
E.g. something like this should just work:
```groovy

interface NestedType {
    @InputFiles
    ConfigurableFileCollection getInputFiles()
}

interface Parameters extends TransformParameters {
    @Nested
    NestedType getNested()
}
```

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/9461.
