### ISSUE TITLE
Rename ValidateTaskProperties to ValidateParameters

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9031]
It's not only about task properties now as we are checking transform action properties and parameters, too.

Also rename `ValidateTaskPropertiesIntegrationTest`.

**Comment by 3flex** [comment]
6.0 milestone?

**Comment by lptr** [comment]
@3flex I'm not sure I understand your comment. Would you like us to schedule this to be done for 6.0?

**Comment by 3flex** [comment]
Just wondering if it will be done in 6.0 or later. I don't have a preference. I realise now that my comment wasn't helpful at all, sorry about that!
