### ISSUE TITLE
Use snapshots instead of fingerprints for work outputs

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9034]
For task outputs (and outputs in general), it makes no sense to use fingerprints, since we actually use the snapshot of the outputs in various places - for caching, for determining what is part of the output and what not, etc. Actually, using the fingerprints currently feels kind of odd in some places, e.g. for the output cleanup we don't know the root files of the outputs from the last execution anymore, since we only have the fingerprint available.

We always use absolute path sensitivity and have no content normalization for the outputs, so we can use the snapshot as is for change detection.

When we don't need to generate the fingerprint from the output snapshot, the whole snapshotting and comparing should also be faster. Being able to store the output snapshot in the execution history is also a first step towards incremental loading from cache. Checking if we have the same outputs as last time can also be made faster, since we can use the Merkle-tree structure of the outputs and don't need to compare all the files.

**Comment by paplorinc** [comment]
See: https://github.com/gradle/gradle/issues/9034#discussion_r299052840
