### ISSUE TITLE
Minimal version of gradle_wrapper

### ISSUE THREAD

**Issue by javyxx** [gradle/gradle#9037]
I download many projects and use gradle wrapper. It would be nice to be able to specify a minimal version. For example this project can be executed with any version 5.x

### Expected Behavior
Use version 5.x that you have already downloaded but download the latest 5.x

### Current Behavior
Download the fixed version placed in the configuration file

**Comment by big-guy** [comment]
This could be a good idea in some ways, but it's important that a build is repeatable. Your build may work with 5.0-5.3, but fail with 5.4 and work again with 5.5. 

The wrapper is intended to bootstrap the build into a good state, so I don't think we're likely to add something like this soon.
