### ISSUE TITLE
Provide a way to specify latest version in plugins block

### ISSUE THREAD

**Issue by johnscancella** [gradle/gradle#904]
There is no warning or way to specify the latest version of a applied plugin in the plugin block

### Expected Behavior

 Some Options to solve this:
- Warn if a applied plugin is out of date with latest version on https://plugins.gradle.org/
  - `warning: plugin org.owasp.dependencycheck:1.4.4 is out of date - latest version is 1.4.4.1. Update your plugin to suppress this warning.`
- Change syntax of of the plugins block to allow use of `latest.integration` like in the dependencies block
  - `plugins { id "org.owasp.dependencycheck" version "latest.integration"}`
- Change syntax to be just like built in plugins and make version optional
  - i.e. `plugins {id "org.owasp.dependencycheck"}` would be valid

My personal favorite would be to change the syntax to make version optional and if not specified always grab the latest.

### Your Environment
mac OS El Capitan
Java 1.8.0_112
gradle 3.2 (revision 5d11ba7bc3d79aa2fbe7c30a022766f4532bbe0f)

**Comment by ljacomet** [comment]
Sorry for the late reply

This was fixed in Gradle 7.0:
* #14704
