### ISSUE TITLE
Explore forbidding overlapping outputs entirely

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9041]
Currently we accommodate overlapping outputs in our task infrastructure. This adds a bunch of complexity, as we need alternative ways to handle things. Some examples:

- we disable caching for a task if we detect overlapping outputs to it, because we can't reliably tell which files belong to which task (they might belong to both)
- we have to do some clever detection of outputs when it comes to tasks with overlapping outputs to see whose output each file is that adds complexity
- we can't clean up stale output directories for a task that lost its sources when it has overlapping outputs
- we can't delete the outputs of an incremental task executed in non-incremental mode like we would, because again we don't know which of those outputs belong to the task

From the user's perspective things get even more complicated as overlapping outputs might not happen when executing one set of tasks, but happen when executing others.

There are still some cases where overlapping outputs are used in today's builds. For example, multiple `Copy` tasks might copy stuff from different sources to the same output directory in preparing a distribution.

We should enumerate all the use cases still calling for overlapping outputs and come up with solutions to replace them with that don't require overlaps. If this is possible, we should start being more forceful about disallowing overlaps: deprecate them, and after a period of time fail the build if we detect any.

**Comment by gerhardol** [comment]
If overlapping outputs are forbidden, I really would like to see a task configuration to "execute the task without checking outputs and consider the outputs created by this task". This will simplify some situations where the the outputs are up-to-date but the task should run to update the cache only.
(The workaround is to stash the outputs, then restore as a special task 'variant'.)

Slightly related is a way to simpler clean the outputs prior to running the task to simplify situations where gradle is not in control of the outputs.
https://discuss.gradle.org/t/run-cleantaskname-without-adding-depencies/34733

**Comment by mathjeff** [comment]
Another advantage of having Gradle forbid multiple tasks from declaring the same output file would be reducing the risk of two plugins writing the same output file, causing consumers of that file to getting seemingly random results when trying to read it: https://github.com/gradle/gradle/issues/12173

**Comment by leonard84** [comment]
I think it is a good idea, as the way gradle behaves in this case is not really obvious to the user. As a first step, we could display a warning when overlapping outputs are defined.

**Comment by dgeissl** [comment]
As I have some issues with output files I've been guided to this discussion, so I'd like to ask one question.
How do you define overlapping output? I guess obvious are the following situations:
- 2 Tasks that declare the same `@OutputDirectory(ies)`
- 2 Tasks that declare the same `@OutputFile(s)`
- 1 Task declaring a `@OutputDirectory` where another Task write it's `@OutputFile` to
What about:
- 2 Tasks declaring a `@OutputFile` that end up in the same directory but with different names
is that also a overlapping output?

**Comment by chylek-qr** [comment]
> > 2 Tasks declaring a @OutputFile that end up in the same directory but with different names
> 
> This is not an overlapping output.
> 
> A potentially overlapping output is if one Gradle task could potentially overwrite output files from another Gradle task. An overlapping output is when something in the output directory or file changed or has been added since the previous time the task executed.

Does that mean that a `classes`/`testClasses` tasks' `doLast` action, which runs an executable that transforms the classes after compilation but before they're used by other tasks, will count as "output directory changing", or do I need to look elsewhere?

We're running into "Gradle does not know how file was created", which is breaking caching between different daemons and massively increasing compile times. Gradle isn't telling me why, and a script that sounds like it would find the cause was removed in #9067 with no mention of an alternative, so this is my only suspicion.

**Comment by lptr** [comment]
The thing we are trying to look out for is the outputs of a task being changed by another task (or some other external process) during or between builds. The `doFirst()` and `doLast()` actions are considered to be part of the task's execution, and thus can safely make changes to the outputs of the task.

**Comment by iseki0** [comment]
@lptr 
> The doFirst() and doLast() actions are considered to be part of the task's execution, and thus can safely make changes to the outputs of the task.

But it's not enough, since sometimes we need process cross-reference across multiple compilation task during an instrumentation. Such as, if we use both of Kotlin and Java, these tasks only generate output of itself language.

**Comment by iseki0** [comment]
At that case(#2137) I'm guessing the `SourceSet` will be useless. Because we have to copy the output to another path and the SourceSet.classesDirs doesn't means anything but for the first post-process task.

**Comment by lptr** [comment]
> If overlapping outputs are forbidden, I really would like to see a task configuration to "execute the task without checking outputs and consider the outputs created by this task". This will simplify some situations where the the outputs are up-to-date but the task should run to update the cache only. (The workaround is to stash the outputs, then restore as a special task 'variant'.)

@gerhardol as a late reply to this, since 7.3 Gradle supports `@UntrackedTask`s.

**Comment by lptr** [comment]
Let's conclude this investigation, and continue the discussion on the issue about deprecating overlapping outputs in Gradle: https://github.com/gradle/gradle/issues/28394

**Comment by gerhardol** [comment]
> > If overlapping outputs are forbidden, I really would like to see a task configuration to "execute the task without checking outputs and consider the outputs created by this task". This will simplify some situations where the the outputs are up-to-date but the task should run to update the cache only. (The workaround is to stash the outputs, then restore as a special task 'variant'.)
> 
> @gerhardol as a late reply to this, since 7.3 Gradle supports `@UntrackedTask`s.

@UntrackedTasks does not help as the cache is not updated, which was the reason to run the task.
