### ISSUE TITLE
Deprecate `IncrementalTaskInputs`

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9048]
Everybody should use `InputChanges`.

**Comment by lptr** [comment]
We need to do #9052 before we can deprecate `IncrementalTaskInputs`.

**Comment by wolfs** [comment]
Let's deprecate it for 6.0 and start nagging in 7.0.

**Comment by wolfs** [comment]
The non-nagging deprecation has been done as part of https://github.com/gradle/gradle/pull/10490.

**Comment by melix** [comment]
I'm removing the 7.1 milestone because #17115 showed that we first need a release of the Kotlin plugin which doesn't use the old API.

**Comment by wolfs** [comment]
Kotlin 1.6 seems to have moved to InputChanges: https://github.com/JetBrains/kotlin/commit/7b6dddf012db149a204b964c628f8ee5b7f1c408

So we can do this as still as Gradle moves to Kotlin 1.6.x
