### ISSUE TITLE
Remove custom change detection code from incremental Java compile

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9052]
With https://github.com/gradle/gradle/pull/8499, the custom alignment code for incremental Java compilation should not be necessary any more and the normal incremental information can be used.

Maybe we should dogfood after we also support better incremental task inputs.

**Comment by wolfs** [comment]
The Android Gradle Plugin currently [extends `JavaCompile`](https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/AndroidJavaCompile.kt#107) with quite some logic which means that moving to `InputChanges` would be a breaking change for them.

**Comment by lptr** [comment]
FTR, it also has its own way to specify additional sources, so our workarounds for `getSource()` could be problematic, too.

**Comment by lptr** [comment]
@wolfs created an issue on the Android issue tracker: https://issuetracker.google.com/issues/133354240

**Comment by lptr** [comment]
\o/ https://issuetracker.google.com/issues/133354240#comment9:

> This should be released in 3.6.0-alpha05.
> 
> Fixed with ag/I1a1a636546a07e38d5a220fdcb2b09b0c376bd2d.

**Comment by lptr** [comment]
I think this means we can break `JavaCompile` for extension in 6.0.

**Comment by wolfs** [comment]
I we break JavaCompile in 6.0, then AGP 3.5 will not work anymore with Gradle 6.0. So no stable version of AGP would work with Gradle 6.0 when it comes out, right? I don't think we can do this...

**Comment by lptr** [comment]
6.0 GA is planned for end of August now. When is AGP 3.6 planned?

**Comment by lptr** [comment]
Kotlin extends `AbstractCompile` only:

https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/Tasks.kt#L267-L272

And it doesn't mess with `getSource()`:

https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/Tasks.kt#L83-L85

**Comment by wolfs** [comment]
Using `InputChanges` in `JavaCompile` is now tracked as part of #9817 and is a requirement for removing the custom change detection code.
