### ISSUE TITLE
Native: buildDir is only partially applied when set within the binaries block

### ISSUE THREAD

**Issue by philmcardle** [gradle/gradle#906]
### Expected Behavior
Gradle should update the build dir for all outputs when set within the binaries block.

### Current Behavior
Given the following code, Gradle will change the build dir for objs and tmp, but not libs (see tree, next).

    apply plugin: 'cpp'

    model {
      
        toolChains  {

            vs2013(VisualCpp) {
                installDir = 'C:/Program Files (x86)/Microsoft Visual Studio 12.0'
            }

        }

        components {

            TestProject(NativeLibrarySpec) {
                targetPlatform 'windows_x86-64'

                binaries {
                    all {
                        buildDir = "${projectDir}\\build\\${targetPlatform.name}"
                    }
                }
            }
        }

    }

Tree output for example code above:

    build
    ├───libs
    │   └───testProject
    │       ├───shared
    │       └───static
    └───windows_x86-64
        ├───objs
        │   └───testProject
        │       ├───shared
        │       │   └───TestProjectCpp
        │       │       └───c6j6y5w4zqfxu2hrtsy45883i
        │       └───static
        │           └───TestProjectCpp
        │               └───c6j6y5w4zqfxu2hrtsy45883i
        └───tmp
            ├───compileTestProjectSharedLibraryTestProjectCpp
            ├───compileTestProjectStaticLibraryTestProjectCpp
            ├───createTestProjectStaticLibrary
            └───linkTestProjectSharedLibrary

Whereas the following code:

    apply plugin: 'cpp'

    buildDir = "${projectDir}\\build\\windows_x86-64"

    model {
      
        toolChains  {

            vs2013(VisualCpp) {
                installDir = 'C:/Program Files (x86)/Microsoft Visual Studio 12.0'
            }

        }

        components {

            TestProject(NativeLibrarySpec) {
                targetPlatform 'windows_x86-64'
            }
        }

    }

Produces the following tree:

    build
    └───windows_x86-64
        ├───libs
        │   └───testProject
        │       ├───shared
        │       └───static
        ├───objs
        │   └───testProject
        │       ├───shared
        │       │   └───TestProjectCpp
        │       │       └───c6j6y5w4zqfxu2hrtsy45883i
        │       └───static
        │           └───TestProjectCpp
        │               └───c6j6y5w4zqfxu2hrtsy45883i
        └───tmp
            ├───compileTestProjectSharedLibraryTestProjectCpp
            ├───compileTestProjectStaticLibraryTestProjectCpp
            ├───createTestProjectStaticLibrary
            └───linkTestProjectSharedLibrary

### Context
I'm working through my workaround described in [GH 859](https://github.com/gradle/gradle/issues/859), where I am able to target, for example, windows_x64_vs2013 and windows_x64_vs2015 in separate executions of Gradle by only configuring one platform and toolchain at a time, and I need the output paths for at minimum the final outputs and ideally all the intermediates to be different for each platform/toolchain combination.

I've read https://discuss.gradle.org/t/add-suffix-relative-to-buildtypes-or-platforms-for-native-builds/19999/4 and linked questions.

In the first example above, I can still set the output paths for the libs using setStaticLibraryFile / setSharedLibraryFile / setSharedLibraryLinkFile on StaticLibraryBinarySpec and SharedLibraryBinarySpec respectively, but then NativeExecutableBinarySpec and GoogleTestTestSuiteBinarySpec have no equivalent methods, so I'm faced with modifying the paths on the link / install / create tasks separately instead, and I'm very quickly writing a lot of code.

It would be ideal if buildDir worked as expected in this scenario although I suspect there's more to it (relatedly, I also submitted feature request [GH 907](https://github.com/gradle/gradle/issues/907) regarding the impact of variants on the output paths).

### Steps to Reproduce (for bugs)
See current behavior.

Source code: [buildDir-example.zip](https://github.com/gradle/gradle/files/606398/buildDir-example.zip)

### Your Environment
Windows 10 x64, Gradle 3.2, MSVC 2013

**Comment by lacasseio** [comment]
Thanks @philmcardle for the detailed issue.

I see there is some confusion about the [Groovy closure delegate](http://groovy-lang.org/closures.html). In a nutshell, for every Groovy closure, Gradle configure the delegate object to the _configuring object_ in question. When a symbol is not found in the `Closure` scope, Groovy will look for the symbol as a property on the delegate. Failing to find the missing property on the delegate, Groovy will move to the parent scope and repeat the process.

In your first example, where you invoke `buildDir` from within the component's binaries container, it will first start looking in the `all` scope for the symbol named `buildDir`. Then it will look at the current configuring binary (delegate) for the `all` closure - either `SharedLibraryBinarySpec` or `StaticLibraryBinarySpec`. Then it will look at the configuring closure for the component followed by its delegate (`NativeLibrarySpec`). Finally, it will look at your `build.gradle` scope followed by the its delegate (`Project`) where it will finally find `buildDir`. You are basically configuring `Project.buildDir` from the `all` configuring closure of a component's binaries container.

I can see configuring `buildDir` for a specific component could be beneficial. Could you give us some concrete use case for configuring the `buildDir` per component? That would help us with our planning.

**Comment by philmcardle** [comment]
Thanks Daniel.

There is unquestionably confusion about the scope of the closure delegate. Thanks for clarifying that. It's actually normally so confusing that I tend to just name the parameter explicitly so that I know what I'm accessing.

However, in this instance, I really did want to change the project's `buildDir`. It's unquestionably an awful hack, but it's just because the binaries are the only thing that have an awareness of what platform Gradle has configured them for (again, this is my VS2013/VS2015 issue).

I still found it odd however that in the case where I was using it (or misusing it), it only applied to the intermediates and the logs, but not the final results, hence the report.

In truth, without [GH 907](https://github.com/gradle/gradle/issues/907), and without something equivalent to this [this comment](https://github.com/gradle/gradle/issues/859#issuecomment-262241529) on 859 (or any equivalent suggestion) working, I'm probably going to resort to a less awful hack and just propagate the configured platform (again, [859](https://github.com/gradle/gradle/issues/859), I've forced Gradle to only configure one platform at a time 🙁) across the entire multi-project build, since I've already backed myself into that corner with my requirements.

**Comment by philmcardle** [comment]
In hindsight, I really shouldn't be trying to modify the project's `buildDir` at this time, so I'm going to close this unless you feel differently - it's perhaps not unreasonable to have undefined behaviour in that scenario.

I'll report a separate issue if I have a use case for per-component `buildDir`.

Thanks.

**Comment by lacasseio** [comment]
Sounds reasonable. Groovy scope can sometimes be difficult to follow due to the lack of code completion. Kotlin script support will help a lot with intellisense when version 1.0 comes out.
