### ISSUE TITLE
Use output snapshot for determining output names in cache key calulation

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9071]
Instead of using `taskProperties.getOutputFileProperties()`. See https://github.com/gradle/gradle/pull/8038#discussion_r241741459.

**Comment by paplorinc** [comment]
Is this issue still relevant?
It seems to me the related files have already changed a lot.

**Comment by wolfs** [comment]
Well spotted! We are using the output names from the fingerprints already: https://github.com/gradle/gradle/blob/45b63d909b314b65c344c9cb63f7c42de997d59c/subprojects/execution/src/main/java/org/gradle/internal/execution/steps/ResolveCachingStateStep.java#L165
