### ISSUE TITLE
Normalize line endings or provide better advice for line endings as they relate to the remote build cache

### ISSUE THREAD

**Issue by autonomousapps** [gradle/gradle#9072]
As [discussed in Slack](https://gradle.slack.com/archives/C0WTFHWT1/p1541458054045300), we [provide advice](https://guides.gradle.org/using-build-cache/#line_endings) for how to handle line endings for users in projects that have heterogeneous build environments (e.g., Windows + Nix). The problem is that this advice is incorrect. When followed, it defeats the remote cache -- meaning that outputs produced on a Linux system will have a different hash than those that a Windows system might produce, and vice-versa.

For example:
![win-nix-line-endings](https://user-images.githubusercontent.com/5402301/48231325-915ea800-e362-11e8-857b-21958ad5b1ba.png)
(this build scans that produced this diff have been obliterated from ge-experiment, but could be recreated if that would be helpful)

Those source files are identical. The only difference is that, on one system they have CRLF line endings, and on the other, LF line endings.

Through experimentation, I have discovered that 
1. Nuking the local clone of a project
1. Running these commands:
```
git config --global core.autocrlf false
git config --global core.eol lf
```
3. Re-cloning the project

resolves this issue. But I make no warranties about the impact of this on the Windows system beyond the fact that task outputs cached from a Linux system are now usable.

**Observed behavior:**
The remote build cache cannot be shared across the Windows/Nix boundary, due to native line endings being different, and our own advice on the matter merely cements this status quo.

**Expected behavior:**
The remote build cache is usable out of the box in a heterogeneous build environment, or at the very least, we provide correct advice on the matter.

**Comment by lptr** [comment]
This has come up again when I tried to build Gradle on my Windows toybox and 40% of the tasks just didn't load from remote cache.

It seems that @JLLeitschuh's changes (see https://github.com/gradle/gradle/pull/9505) have made Git check out all text files with `LF` line endings, but it didn't work for an existing checkout, i.e. line endings were only fixed for files changed after this PR was merged.

Anyway, a fresh checkout solved the problem, however, it seems that JMH generates code with line endings that fit the current OS. So while we can force people to use one line-ending for checked-in code as a workaround, generated code might still be a problem.

Once we add source code/line ending normalization though this shouldn't pose a problem anymore.

**Comment by lptr** [comment]
Looking at this talk I was wondering... https://www.youtube.com/watch?v=Jr_pD3_wBbk

...shouldn't we capture the fingerprint of the AST instead of simply normalizing line endings? We should definitely look into how much work that would be, and how much additional time it would take.

**Comment by bamboo** [comment]
Fingerprinting the AST is an interesting idea and  could make the fingerprint much more resilient to formatting changes. It sounds a little complex though and likely to add significant overhead.

Fingerprinting the token stream produced by the lexer should provide most of the benefits with less overhead and for a smaller investment.

**Comment by lptr** [comment]
I like that idea a lot. We should definitely measure this.

Also note that we should be able to cache the results based on the hash of the raw file contents if the overhead becomes large.

**Comment by autonomousapps** [comment]
Is this really stale?

**Comment by lptr** [comment]
No, we should address this still.

**Comment by ghale** [comment]
There is now a `@NormalizeLineEndings` annotation (and a corresponding `normalizeLineEndings()` method on the runtime API) that allow a task author to specify that an input is not sensitive to line endings and that we should normalize them when hashing text files.  This capability will be in Gradle 7.2.
