### ISSUE TITLE
Remove unnecessary JDK 7 directory walker check

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9075]
The test check that JDK7 walker gets picked with Unicode encoding as default can be removed now, given that we don't support running on Java 7 any more.

**Comment by lptr** [comment]
It might be worth looking at #9084 as well in the same go, or as a separate task.

**Comment by paplorinc** [comment]
I've provided a PR that addresses both: https://github.com/gradle/gradle/issues/9084
By removing the usage, I would have left dangling classes behind, seemed more consistent to clean those up in the same PR (just saw the other PR after this one was already finished).
If you would like me to split it into multiple ones, let's discuss how to do that without half-finished refactorings.
