### ISSUE TITLE
Test real symlink handling on Windows

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9077]
Looks like Windows has "always" (since Vista) been able to create symlinks on NTFS, but only since Windows 10 creators update did it become possible to create symlinks without administrator privileges. Git 2.13.1 adds support for symlinks: https://github.com/git-for-windows/git/pull/1188

We should add some integration tests using `mklink` to see if we do the right thing on Windows. Might need installing Windows 10 agents.

**Comment by lptr** [comment]
@paplorinc please take a look at how this functionality works in native Windows 10. Can we or can't we create symlinks? Is it feasible for Gradle to support this eventually?

**Comment by paplorinc** [comment]
After removing the [Gradle's native Windows symlink creation guard](https://github.com/gradle/gradle/blob/master/subprojects/native/src/main/java/org/gradle/internal/nativeintegration/filesystem/jdk7/WindowsJdk7Symlink.java#L40) and the [test's symlink requirement](https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy#L25), without admin rights we're getting:
<img src="https://user-images.githubusercontent.com/1841944/59762188-fc784180-9296-11e9-9973-223749a1b7c5.png">
Starting Idea with Admin rights will make many related tests pass:
<img src="https://user-images.githubusercontent.com/1841944/59762189-fd10d800-9296-11e9-9f8b-a3d88b934bb2.png">

WIth the latest Windows 10 (after March 2017) an alternative is to enable `Developer mode`:
<img width="406" alt="Screen Shot 2019-06-19 at 13 46 20" src="https://user-images.githubusercontent.com/1841944/59762942-aa382000-9298-11e9-95f9-9d08afda88e3.png">
Before this is enabled:
<img width="626" alt="Screen Shot 2019-06-19 at 13 47 46" src="https://user-images.githubusercontent.com/1841944/59763109-2599d180-9299-11e9-82fb-720512dda306.png">
After:
<img width="425" alt="Screen Shot 2019-06-19 at 13 48 56" src="https://user-images.githubusercontent.com/1841944/59763111-2599d180-9299-11e9-9e1c-6be25016e5b1.png">

**Comment by lptr** [comment]
Looks like this is possible but definitely not something we can expect a significant portion of our users doing on a daily basis with their source code. Let's revisit this later.

Note that it seems that we'll be getting Windows 10 on CI soon.

**Comment by lptr** [comment]
If I read this correctly, JDK 13 is the first that lets one create a "developer mode" symlink on Windows: https://bugs.openjdk.java.net/browse/JDK-8218418. That means before JDK 13 there's no chance of doing this without native magick.

Let's take a look at this again around 7.0, maybe things have changed by then. Specifically: Windows might have adopted developer mode as default, or JDK 13 might be in widespread use among our target audience.

**Comment by lptr** [comment]
We now have Windows 10 installed across the board with developer mode enabled:

![image](https://user-images.githubusercontent.com/495366/80807106-9483ce80-8bbc-11ea-81ea-d1a51e0e6da1.png)

I can create symlinks using `MKLINK` from `cmd.exe` (doesn't work from PowerShell :/), and it seems `java.nio.file.Files.createSymbolicLink()` can create symlinks without special permissions on regular NTFS volumes, too. \o/

**Comment by wolfs** [comment]
Let's not do this right now.
