### ISSUE TITLE
Gradle daemon caches Ant task configuration

### ISSUE THREAD

**Issue by vitjouda** [gradle/gradle#908]
### Expected Behavior
```
ext {
    genSources = "${projectDir}/${buildDir.name}/generated-sources"
}
task jaxbTask {
    ext {
        resourceDirRelative = "src/main/resources"
    }
    mkdir(genSources)
    doLast {
        ant.taskdef(name: 'xjc', classname: 'com.sun.tools.xjc.XJC2Task',
                classpath: configurations.jaxb.asPath)
        ant.xjc(destdir: genSources, extension: true, catalog: "D:/catalog.cat") {
            schema(dir: resourceDirRelative, includes: "*.xsd")
            binding(dir: resourceDirRelative, includes: "bindings.xml")
            arg(value: "-Xnamespace-prefix")
        }
    }
}
```
When I change the `catalog `property to different file, old file is no longer used during this Ant task execution.

### Current Behavior
When this task is invoked for the first time, Gradle somehow caches `catalog` property. When I now change path to catalog (different, non existing file or even an empty string) and re-run this task, build is successful despite it should fail. When i change it to different existing catalog, old one is still used. I have to stop gradle daemon to apply any changes. This is very inconvenient.

### Context
Creating buildscripts for new JAXB based projects using XJC with catalog option.

### Your Environment
Windows 7 x64, Java 1.8

**Comment by bmuschko** [comment]
Could you please provide a test project on GitHub that demonstrates the issue?

BTW: I strongly suggest you define inputs/outputs for your task so Gradle know _if_ you made changes to the task configuration. Any reason you don't use one of the [existing JAXB plugins](https://plugins.gradle.org/search?term=jaxb)?
