### ISSUE TITLE
javac will not create the source output directory for annotation processors

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#909]
@big-guy commented on [Fri Nov 18 2016](https://github.com/gradle/task-output-cache/issues/306)

Builds that use annotation processors (like Lombok) and configure the generated source output directory will likely use a `doFirst` to create the source output directory before running javac.  The [Gradle Apt plugin](https://github.com/tbroyer/gradle-apt-plugin) does this.

Since we want to discourage the use of `doFirst` or `doLast` with the built-in tasks from build scripts, we could consider adding something to `CompileOptions` to represent the `-s` command-line option to javac.  

For correctness, builds should also add their source output directory as an output when using the cache.  We could do that automatically with something in `CompileOptions`.

Command-line options for annotation processing: http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javac.html#processing

We came across this in a build and switched it to using a configure task instead of `doFirst` to create the directory.

---

@big-guy commented on [Mon Nov 21 2016](https://github.com/gradle/task-output-cache/issues/306#issuecomment-261979450)

Another way of getting around this is to make `outputs.dir` and `outputs.file` behave like `@OutputDirectory` and `@OutputFile`.  The annotations create output directories if they do not exist, but the DSL methods do not.

**Comment by oehme** [comment]
The generated source directory is now configurable on `CompileOptions`
