### ISSUE TITLE
Use shards in the local build cache

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9093]
We should create directories in the local build cache for the first two letters of the md5 hash. This allows to have much more files in the local cache which is necessary if you use the cache on CI or when we have finer grained cache entries when using Merkle trees.

**Comment by Tapchicoma** [comment]
@lptr imho still valid issue?

**Comment by lptr** [comment]
It could be. I wonder if users are actually struggling with this. There is an assumption here that the local cache might collect too many entries over time, but I'm not sure if this is the case actually. We've never measured the impact of a growing local cache. I guess we should.

Note that on CI we recommend you turn the local cache off.
