### ISSUE TITLE
Disable caching and up-to-date checks completely for task

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9095]
See https://github.com/gradle/gradle/issues/2818

This is probably a good reason to make it possible for a task to disable any kind of input/output snapshotting, thus disabling up-to-date checks completely.

Currently a task can declare `outputs.upToDateWhen { false }`, effectively making up-to-date checks to always result in re-running the task. But because we don't have any knowledge about what the closure does, we still snapshot the task: maybe the closure will return `true` the next time we execute it.

We could use a different API to disable any kind of caching for the task, including up-to-date checks. This would keep the `Copy` task mentioned in https://github.com/gradle/gradle/issues/2818 perform properly.

**Comment by lptr** [comment]
We still want this.

**Comment by reinhapa** [comment]
Is there a way to disable snapshotting in a existing task jet? As we have immensely long running times when copy data to a windows remote share as part of our distribution task, where the snapshotting takes more then 80% of the execution time..

**Comment by lptr** [comment]
There is no way to switch off snapshotting yet, but thanks for the use case, this is a pretty good reason to implement the feature.

**Comment by ohumbel** [comment]
For me `immensely long` means dozens of minutes up to hours. So any speed improvement would greatly be appreciated.

**Comment by lptr** [comment]
Hi @reinhapa! Thanks for reaching out. What would be the most useful for us at this stage is if you could explain the use cases you'd like to handle via this feature.

**Comment by reinhapa** [comment]
@lptr In my use case it would be most useful to some how signal on a `@OutputDirectory` (or any output) to be not being cached. In my case I know that certain mounted folders under Linux or drives in Windows do point to network shares, that are not suitable for caching. In those cases I would like to disable all caching.

**Comment by reinhapa** [comment]
@lptr is there anything I can do to push this issue forward? We got massive build times when copy data to big shares as they take up to an hour to complete when a raw copy just would take seconds.

**Comment by lptr** [comment]
@reinhapa IIUC, for your tasks it takes hours to snapshot the output locations, and the tasks would only copy files?

One escape hatch that might work right now would be to not declare the outputs for a task that does only the copying using `FileOperations.copy()`. If you declare no outputs, Gradle doesn't have anything to snapshot. It's not nice, because in general we are trying to guide people towards declaring all of their inputs and outputs correctly, but since this is about _not_ caching, I think it could work.

We are planning a rework of the whole input/output declaration APIs that will include solving this problem, too, but I can't yet say when that will land. We would like to do some preparation beforehand, so that the transition to the new APIs can be smoother than our usual _introduce new -> deprecate old -> remove old_ cycle.

**Comment by reinhapa** [comment]
@lptr so just that I understand it correctly, as an intermediate solution I will replace the existing `@OutputDirectory` with `@Internal` and revisit as soon there is a better solution of marking an output that should not be cached?

**Comment by lptr** [comment]
@reinhapa yes, that is what I'm suggesting essentially. If this task is always used to copy things outside the project directory where you don't want to check for outputs etc., then I believe this should work.

Please add a TODO comment to revisit, though. :)
