### ISSUE TITLE
Fine grained file system mirror invalidation

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9096]
Currently, all of the file system mirror is invalidated whenever a task executes. Since different tasks may re-use the same inputs or read from the same directory, this causes work to be done twice or even more often during a build.

It would be much better to invalidate only the parts of the file system mirror that the task would touch – i.e. the declared outputs of the task.

As a safety net we could invalidate only part of the file system mirror if the task validation for the task which is about to execute succeeded.

**Comment by wolfs** [comment]
I did some measurements, the first with fine grained invalidation - i.e. the task only invalidates the outputs in the files system mirror.

## nonAbiChange:

| | fine grained invalidation | latest nightly |
|----|----|----|
| total time | 1551 | 2128 |
| config time | 290 | 339 |
| execution time | 1261 | 1789 |
| before execution snapshotting | 979 | 1566 |

So pure execution time goes down by 500ms, which is about 30%.

**Comment by wolfs** [comment]
For a fully up-to-date build, with fine grained invalidation and no invalidation between builds, I have the following result:

## upToDate


|  | no invalidation between builds | latest nightly
| -- | -- | --
total time | 540 | 941
config time | 253 | 282
execution time | 287 | 659
before execution snapshotting | 378 | 1035

That means that the execution time was reduced by 372ms, that is about 55%. Cumulative snapshotting time before task execution was even reduced by more than 60%.

The raw results can be found here: https://docs.google.com/spreadsheets/d/1Q3vZ6GKyEmEsDwIvQfOBN3Bnz33GU77yTi7oKibQKEc/edit#gid=0

**Comment by lptr** [comment]
Old writeup @wolfs found: https://docs.google.com/document/d/1YN1lNZ9_8KjwY8e2vQJ5Ae1BDrCkZ2yE3ZWRvy1GAdc

**Comment by wolfs** [comment]
Fine grained invalidation can now be turned on via a system property. See this PR for also allowing the file system state to survive between builds: https://github.com/gradle/gradle/pull/11360
