### ISSUE TITLE
Track JVM version more precisely

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9102]
Currently we track `1.8`, i.e. major and minor version for `JavaCompile`.

We should also track

- [ ] full version number including build number
- [ ] vendor
- [ ] Make sure we track it for `GroovyCompile` here: https://github.com/gradle/gradle/blob/678fc228149384426768462d047c8659fa5d2cef/subprojects/language-groovy/src/main/java/org/gradle/api/tasks/compile/GroovyCompile.java#L132
- [ ] Remove vendors as inputs added here gradle/gradle@06c5da7

**Comment by DPUkyle** [comment]
Thanks for sharing; @big-guy and I discussed this in some detail in a private forum. I'll be watching to see how this evolves!

**Comment by pioterj** [comment]
For the record, the workaround for tracking the vendor is described at https://guides.gradle.org/using-build-cache/#java_version_tracking.

**Comment by bmuskalla** [comment]
We now take the following into account as [inputs](https://github.com/gradle/gradle/commit/f056aa385ff83f712836f4bbd07a0bf680471542):
If no toolchain is configured:
* Java language version (major version)

If toolchains are configured:
* Java language version (major version)
* Vendor, if specified as toolchain requirement (starting with 6.8)
* JVM implementation (e.g. J9), if specified as toolchain requirement (starting with 6.8)

As an example, using the following setup
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
        vendor = JvmVendorSpec.ADOPTOPENJDK
    }
}
```

Compile and test tasks (and any custom tasks using toolchains) take 11 and the vendor into account. Wit this, we're closing this issue for now until there is a good reason to take more nuanced version information into account that is not possible to workaround as described above.
