### ISSUE TITLE
Composite build fails when included build dependency is resolved with `fileTree` or a `flatDir` repository

### ISSUE THREAD

**Issue by altavir** [gradle/gradle#911]
Dependecies like `compile fileTree(dir: 'libs', include: ['*.jar'])` or declared in local repository
```
repositories {
    flatDir {
        dirs 'libs'
    }
}
```
can't be reached via composite build.

### Expected Behavior
I expect to work with local jars just as I work with maven dependencies.

### Current Behavior
Can't reach local dependency inside included build

### Steps to Reproduce (for bugs)
1. Create a local jar dependency in build1.
2. Create build2 which includes build1.
3. Add dependency on project including jar in build2.

### Your Environment
gradle 3.2
Idea 2016.3
windows 10 x64

**Comment by eriwen** [comment]
@altavir Thank you for your contribution. It would help us greatly if you could provide an example project or test case for this. 

Additionally, can you specify why this is _important_ to fix? What is this preventing you from achieving?

**Comment by altavir** [comment]
The project I am working on is quite large (~30 subprojects in two repositories), but I can reproduce important parts.
1. I have a link to local snapshot copy of [JFreeChart](http://www.jfree.org/jfreechart/) library in [one of my projects](https://bitbucket.org/Altavir/dataforge/src/1e1ddc152f3507f3e3023c7ee8fa62d3b9ecdff2/dataforge-plots/plots-jfc/build.gradle?at=dev&fileviewer=file-view-default#build.gradle-6). JFreeChart has a maven artifact, but it does not have JavaFX support.
2. Then I am adding dependency on this module in [another module of this build](https://bitbucket.org/Altavir/dataforge/src/1e1ddc152f3507f3e3023c7ee8fa62d3b9ecdff2/dataforge-grind/build.gradle?at=dev&fileviewer=file-view-default#build.gradle-21)
3. Finally I am including this build inside another one via [composite build](https://bitbucket.org/Altavir/numass/src/f813a4ac6241467403e45448887c74c70010a254/settings.gradle?at=composite2&fileviewer=file-view-default#settings.gradle-3).

The build works, but classed from local jar a missing in the runtime.

The reason why I need this is obvious. I have some third party jar that is not in maven central and I need to use it. It works perfectly from the same project but fails in composite build which is a bit frustrating because I waited for composite build feature with great anticipation.

**Comment by adammurdoch** [comment]
@sheldonneuberger there are two problems in the description, not being able to use a `flatDir` repository and not being able to use a `fileTree` dependency. Which one of these are you running into?

**Comment by sheldonneuberger** [comment]
@adammurdoch fileTree.

**Comment by adammurdoch** [comment]
I've split out https://github.com/gradle/gradle/issues/5473 to cover the fix for using `FileTree`.

**Comment by adammurdoch** [comment]
The `FileTree` case is fixed now. The fix will be in 4.9. I'll leave this issue open as the `flatDir` case is not yet addressed.

**Comment by sheldonneuberger** [comment]
I tested gradle-4.9-20180530235941+0000 and it fixes my issue. Thanks!
