### ISSUE TITLE
Java custom task doFirst() action not called

### ISSUE THREAD

**Issue by an-cwi** [gradle/gradle#9142]
### Expected Behavior
When creating a custom task which extends another task, I expect an action registered in the constructor via `doFirst(final Action<? super Task> action)` to be called before the task's `@TaskAction` is executed.

```java
public class AnotherTask extends DefaultTask {

    @TaskAction
    void doWork() {
        System.out.println("doing work of AnotherTask...");
    }
}

public class MyCustomTask extends AnotherTask {

   public MyCustomTask() {
      doFirst(this::setup);
   }

   private void setup(final Task task) {
      System.out.println("setting up MyCustomTask...");
   }
}
```

Running a task of the above type should call `setup()` prior to calling the `@TaskAction` of `AnotherTask`.

Expected output of running `myCustomTask`:
```
setting up MyCustomTask...
doing work of AnotherTask...
```

### Current Behavior
Currently the action registered with `doFirst()` is called after the `@TaskAction` of `AnotherTask`.

Output of running `myCustomTask`:
```
doing work of AnotherTask...
setting up MyCustomTask...
```

### Context

Previous mentions of the issue:
https://issues.gradle.org/browse/GRADLE-2064?_ga=2.88567000.2120670124.1555328555-2074863166.1517433528
https://discuss.gradle.org/t/dofirst-does-not-execute-first-but-only-after-task-execution/28129

### Steps to Reproduce 

[bug-example.zip](https://github.com/gradle/gradle/files/3085148/bug-example.zip)

### Your Environment
Gradle 5.3.1

**Comment by big-guy** [comment]
The implementation is something like this:
- Analyze classfile for methods annotated with `@TaskAction`
- Create an instance of the task
- Add methods discovered above as actions with something like `doFirst`

In this case, the constructor runs first and adds the setup action, then the methods annotated with `@TaskAction` get added before that one.  

It's been like this for a long time, so we're unlikely to change it. I think there used to be other actions that were added this way that required the task action to be added "first", but I don't think those exist anymore. If we switched Gradle's behavior to use doLast, it would break builds that rely on the task action happening first.

Ultimately, I think you shouldn't use doFirst/doLast to change the action of a task from the constructor. This doesn't really compose well and it'll be surprising to see a task with multiple actions. 

I would either do:

```
public class MyCustomTask extends AnotherTask {
   @TaskAction
   @Override
   void doWork() {
      // setup    
      System.out.println("setting up MyCustomTask...");
      // delegate work to super's method now
      super.doWork();
   }
}
```

Or I would use an entirely different task for the "setup" steps (depending on what needed to be done).  You could also move the call to `doFirst(setup)` into the plugin, but I think this is strange too.

**Comment by an-cwi** [comment]
I see. Thanks for following up.

First of all, a few clarifications:
1. The `setup()` method is setting values on the inherited task, in particular ones that are required at the point when the main `@TaskAction` is executed. So it's not something that can be extracted out into a separate task that is run beforehand.
1. Unfortunately the task I'm trying to override marks it's `doWork()` function as final, so I can't override it. That is what I've done in other cases, though.

Also, I'm not sure what you mean by "move the call to `doFirst(setup)` into the plugin".

Secondly, maybe it's the semantics of `doFirst()` and `doLast()` that are a bit confusing. It sounds like the implementation is that these methods just add actions to the beginning or end of a single list, to which the main `@TaskAction` is also added (using `doFirst()`). My interpretation/assumption was that these methods add actions that are done "first", before the main action, and then "last", after the main action. Maybe such methods would be called `doBefore()` and `doAfter()`, I suppose. Is that something that's ever been considered?

Finally, I'm only running into this issue when implementing the overriding task in Java. If I use groovy and call `doFirst()` or `doLast()` in the configuration closure, it works as expected:
```groovy
task myCustomTask(type: AnotherTask) {
   doFirst {
      println "setting up MyCustomTask..."
   }
}
```
However, I haven't been able to find a way to replicate this in Java. I see the `configure(Closure)` method, but I'm not sure if there's a way to effectively create a closure from Java. Any suggestions to that end?

It's possible I don't fully understand the `task` model and the intended usage, so I appreciate your patience and time on this. Thanks again.

**Comment by big-guy** [comment]
> The setup() method is setting values on the inherited task, in particular ones that are required at the point when the main @TaskAction is executed.

I don't know your example completely, but this sounds like you are trying to change the configuration of the task while it's executing, which will cause problems where your task will be up-to-date when it shouldn't be.

> Also, I'm not sure what you mean by "move the call to doFirst(setup) into the plugin".

I just mean that in your plugin, you'd do:
```
anotherTask {
  doFirst {
     println "setting up MyCustomTask..."
  }
}
```
This may be your best option, but keep in mind that this action is executed during the execution phase and _should not_ change the configuration of the task.

> Secondly, maybe it's the semantics of doFirst() and doLast() that are a bit confusing. It sounds like the implementation is that these methods just add actions to the beginning or end of a single list

Yep, that's basically what it is.  

> Finally, I'm only running into this issue when implementing the overriding task in Java. If I use groovy and call doFirst() or doLast() in the configuration closure, it works as expected:

This is doing something very different.  In the OP, `MyCustomTask` was adding the action in the constructor of the task (this would be the same in Java/Groovy/Kotlin/etc).  In this example, the task is constructed, the TaskAction is added and then your configuration block runs. 

> However, I haven't been able to find a way to replicate this in Java. I see the configure(Closure) method, but I'm not sure if there's a way to effectively create a closure from Java. Any suggestions to that end?

If you have a task instance, you can just call `doFirst` or `doLast` directly to add an Action.
