### ISSUE TITLE
OutOfMemoryError in gradlew process

### ISSUE THREAD

**Issue by emmanuelguerin** [gradle/gradle#9144]
### Expected Behavior
gradlew should work fine

### Current Behavior
While running a build generating a lot of logs (around 50MB in a single task when the build succeeds).
gradlew generates:

`java.lang.OutOfMemoryError: GC overhead limit exceeded`

It is the gradlew process (the one run from the gradlew script and that has by default a 64MB max heap size) that generates the error. It is NOT the gradle daemon itself.

Increasing the heap size using GRADLE_OPTS solves the issue, but how can we set a reasonable size?

gradlew is called with the --no-daemon option.

### Your Environment
Here is a heap dump from the gradlew process when the error occurs:
https://gist.github.com/emmanuelguerin/374d04e91b3c0bbb870a5878e5df6189/raw/efc12c1880c7497a63551c4643a1a69b0c1c1f41/java_pid30749.hprof

**Comment by big-guy** [comment]
I can't quite tell from the heap dump.. Which version of Gradle is this?

**Comment by emmanuelguerin** [comment]
I tried with gradle 5.1.1 and 5.3.1, they both seem to have the issue. The dump is from gradle 5.1.1.

**Comment by emmanuelguerin** [comment]
Another thing that may not show in the logs is that --parallel is also set, and other tasks are running when the client crashes.

**Comment by emmanuelguerin** [comment]
We haven't see that particular issue for quite a while. I'll close this.
