### ISSUE TITLE
Provide deeper modeling of Java libraries provided by the JDK

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#9146]
Some versions of the JDK come with pre-packaged libraries (like JavaFX) beyond the regular core Java runtime (anything in the old school rt.jar). The location (or inclusion) of these libraries can vary by Java vendor and Java version. e.g., JavaFX is included in Java 8, but not in Java 12. 

Builds that need to use these libraries need to go through some hackery to get them added properly.  Usually, these extra libraries are added as an absolute path to a directory or jar. This means that Gradle can provide very little help when the library is missing, the library is different between machines or the library should be selected in a different way.

### Expected Behavior

Gradle should have an API to manually configure JDK provided libraries or automatically discover them so that we get them into the Gradle dependency management engine as normal looking dependencies.

This is a similar problem that needs to be solved for native "prebuilt libraries" and is similar to what we already try to do for libraries provided by the Visual C++/Windows SDK. 

### Current Behavior

Users must use plain Files as dependencies.

### Context

As a pseudo-code example of what we could do:
```
plugins {
    id 'java'
}

java {
    // Need a 1.8 JDK (or compatible)
    targetCompatibility = 1.8
}

dependencies {
    // compiles against JavaFX, but does not expose it in API
    implementation library("javafx")
}
```
- When we find a compatible Oracle JDK8, Gradle should add the javafx.jar to the compile classpath with metadata about where it came from, version, etc. 
- When we find a compatible Oracle JDK12 that can build down to 1.8, Gradle should fail with an error that we can't find a "javafx" library in the JDK.
- When we find a compatible non-Oracle JDK8 or JDK12, Gradle should fail with an error that we can't find a "javafx" library in the JDK because these do not include javafx.
- Maybe there's an API for manually registering other JDK libraries or providing a mapping to GAV if they're now published separately.
- Downstream consumers should see the javafx library as a "regular" dependency.  It's a bit TBD what we would need to include in the metadata (maybe Gradle Metadata only?). 
- Build-scans and dependency reports should see this as a regular dependency.

**Comment by DPUkyle** [comment]
`tools.jar` is another example of a platform-specific dependency that some people need at both compile and runtime, though that problem has largely gone away with Java 9+.

**Comment by bmuskalla** [comment]
Closing in favor of #14802
