### ISSUE TITLE
`cleanTest` does not rerun tests

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#9153]
### Expected Behavior
When running a test like so `./gradlew cleanTest test` I would expect the test itself to re-run.

### Current Behavior
The test task results are pulled from the local build cache and not re-run.

Maybe I have a misunderstanding of what `cleanTest` should do. Is it expected that the results of the test are pulled from the build cache instead of being re-run?

Here is a sample repro case:
https://github.com/runningcode/test-cache

When `org.gradle.caching=true`, running `./gradlew cleanTest test` twice in a row does not cause the test to be re-run.

**Comment by wolfs** [comment]
Yes, that is expected. The same if you run `./gradlew cleanCompileJava compileJava`, then the result of compilation will also be pulled from the cache.

The task `cleanTest` is a finer grained `clean` which only removes the outputs of the test task.

**Comment by wolfs** [comment]
I think you use `clean` in order to re-run the tests and only the test task. For this use-case we have the `rerun-tasks` command line option. I would probably be better if it was possible to select a single task which should be rerun instead of re-running all of the tasks with `--rerun-tasks`.

I'll close this issue since `clean` is not meant to be used for re-running a task.

**Comment by lptr** [comment]
I've added an issue about rerunning single tasks: https://github.com/gradle/gradle/issues/9166.

**Comment by hmijail** [comment]
`./gradlew cleanTest test` is actually the method proposed by the Gradle docs under "Forcing tests to run" ( https://docs.gradle.org/current/userguide/java_testing.html#sec:forcing_java_tests_to_run ). Would be great if that got fixed.

**Comment by ocean927** [comment]
This behaviour is confusing. Add to that SO replies suggesting clean, cleanTest none of which help rerun the test. By default, tests should rerun every single time, not using cached results. Why can't Gradle expose "cache results y/n" option, pick reasonably defaults and let users override per task if necessary.

**Comment by Sottti** [comment]
I'm running  `./gradlew cleanTest test --no-build-cache` and apparently works, in case anyone looking for this.

**Comment by vladimirf7** [comment]
Is there a way to rerun the tests without recompiling them?

**Comment by guai** [comment]
`gradle check --rerun --build-cache` still doesn't rerun tests
