### ISSUE TITLE
Nested platform constraint does not resolve versions

### ISSUE THREAD

**Issue by greyskyy** [gradle/gradle#9159]
### Expected Behavior
Specifying a platform (maven-bom) in the dependency constraints of a `java-platform` build, should cause projects importing the outer platform to automatically import the constraints of the inner platform.

### Current Behavior
The inner platform is not imported, preventing versions from being resolved.

### Context
I am creating a `java-platform` project which will consolidate many of dependencies across multiple projects in my organization.  This platform will publish both a maven pom and the gradle metadata that can be consumed, simplifying version management across multiple projects.  In my specific example, my dependency constraints include `api platform('com.fasterxml.jackson:jackson-bom:2.9.8')`.  My expectation is that this will behave just like including an artifact with `<type>pom><scope>import</scope>` in the dependencyManagement section of a maven pom.

### Steps to Reproduce 
Using the uploaded projects in [nested-bom.zip](https://github.com/gradle/gradle/files/3090955/nested-bom.zip), run the following:

```bash
unzip nested-bom.zip
cd project1
./gradlew publishToMavenLocal

cd ../project2
./gradlew build #<-- note this fails to resolve dependency versions for jackson
```

This is reproducible regardless of whether the module metadata is published or not.

Hand-editing the resulting project1 pom.xml, to include specify `<scope>import</scope><type>pom</type>` resolves the issue, but this should not be necessary.

### Your Environment
```bash
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

$ ./gradlew --version
------------------------------------------------------------
Gradle 5.4
------------------------------------------------------------

Build time:   2019-04-16 02:44:16 UTC
Revision:     a4f3f91a30d4e36d82cc7592c4a0726df52aba0d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Windows 10 10.0 amd64
```

**Comment by greyskyy** [comment]
updating the `pom.xml` can resolve the issue, but that seems incorrect, long-term.  Especially considering in gradle 6.0 the module metadata will always be published, thus eliminating this work-around.

updates the the `project1/build.gradle` can work around this issue:
```groovy
configurations {
    importScope
}
// ...
publishing {
    publications {
        bom(MavenPublication) {
            from components.javaPlatform

            // remove all scope entries from the dependency management section
            asNode().dependencyManagement.dependencies[0].dependency.each {
                if (it?.scope != null) {
                    it.remove(it?.scope[0])
                }
            }

            // add scope=import,type=pom to the boms
           configurations.importScope?.dependencies.each { dep ->
               def n = asNode().dependencyManagement.dependencies[0].dependency.find {
                   it.artifactId[0].text() == dep.name &&
                   it.groupId[0].text() == dep.group
               }

               n?.appendNode('scope', 'import')
               n?.appendNode('type', 'pom')
            }
        }
    }
}
```

**Comment by ljacomet** [comment]
You are defining the BOM as a `constraint`, but that is most likely not what you want to do. A constraint on a platform will just say that if that dependency enters the graph _elsewhere_ it should use the `platform` part of it and the version recommendation from the constraint.

If you expect that constraints of that BOM to be visible to the consumers of your platform, then you need to add the BOM as a `platform` `dependency` by doing something like:

```
javaPlatform {
    allowDependencies()
}
dependencies {
    api platform('com.fasterxml.jackson:jackson-bom:2.9.8')
}
```

Then this will be properly published as an inlined BOM in Maven.

This is not the first time this question pops-up. Keeping the issue open to track documenting that pattern.

**Comment by greyskyy** [comment]
Thanks @ljacomet 

That works with the module metadata publication.  However the bom is still published with `<scope>compile</scope>` in the `pom.xml`.

This fixes the problem for gradle users, but it appears to still be an issue when publishing the maven bom itself.

**Comment by greyskyy** [comment]
thanks @ljacomet

**Comment by koppor** [comment]
This still appears on the first page of google hits.

The fix from https://github.com/gradle/gradle/commit/937d6ce25f72ed114767405fb1ac33179dfb2b9f seems to be gone from https://docs.gradle.org/current/userguide/platforms.html.

I think, it is not possible with gradle 8.14.2?


I started to try with Kotlin:

```
publishing {
    publications {
        create<MavenPublication>("bom") {
            from(components["javaPlatform"])
```

I get 

    SoftwareComponent with name 'javaPlatform' not found.
