### ISSUE TITLE
Missing import statement for VersionNumber in init.gradle

### ISSUE THREAD

**Issue by wangyw** [gradle/gradle#9162]
1. brew install gradle (Mac Sierra)
2. run gradle

### Expected Behavior
gradle should run

### Current Behavior
When I run gradle, it failed because "Could not get unknown property 'VersionNumber'" at '/Users/ywang2/.gradle/init.gradle' line: 155

I added "import org.gradle.util.VersionNumber" to ~/.gradle/init.gradle, then it worked.

`TAG-32368:cc-indexer ywang2$ gradle

FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/ywang2/.gradle/init.gradle' line: 155

* What went wrong:
A problem occurred evaluating initialization script.
> Could not get unknown property 'VersionNumber' for build of type org.gradle.invocation.DefaultGradle.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
`

### Steps to Reproduce 
$ gradle

FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/ywang2/.gradle/init.gradle' line: 155

* What went wrong:
A problem occurred evaluating initialization script.
> Could not get unknown property 'VersionNumber' for build of type org.gradle.invocation.DefaultGradle.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

### Your Environment

Build scan URL:

**Comment by big-guy** [comment]
This was an intentional change.

`org.gradle.util` was not part of Gradle's public API but used to be part of the default imports in build scripts.  This was removed in 5.0. Types in `org.gradle.util` may be removed or changed at any time as we treat it as an internal API.
