### ISSUE TITLE
Add FileCopyDetails.setLastModified() - to set the destination lastModified value for a copied file

### ISSUE THREAD

**Issue by steffenyount** [gradle/gradle#9164]
Add ability to easily set reproducible lastModified values on Copy tasks' output files.

### Expected Behavior
The FileCopyDetails object passed to Actions registered using CopySpec.eachFile() should allow the implementer to specify a lastModified value for the destination file, and when specified that value should be set on the destination file. E.g:
```
void setLastModified(long time);
```

### Current Behavior
While the `FileCopyDetails` already includes first class support for setting destination file attributes like `setMode​(int mode)` and the archive tasks have first class support for reproducible lastModified values with the `preserveFileTimestamps​` option, there is currently no mechanism providing first class support to easily set reproducible lastModified values on Copy tasks' output files.

And yes, as pointed out in #1252, with trouble one can hack a solution together that assigns lastModified values to the outputs, but it would be so much better if the Gradle DSL provided simple first class support for doing this simple thing.

### Context
To increase our build's total build avoidance, I've been trying to make our tasks' inputs and outputs more reproducible, to thus get more up-to-date avoidance and cache hit based avoidance.

In this process I've run into a couple of compiler/code generator tool limitations whereby:
1. all the input files need to be colocated in a single source directory
2. the input files' lastModified dates are recorded in the output files

We've been using a copy task to assemble the single source directory for the compiler, but this has introduced the unfortunate side effect that the relocated input files' lastModified dates reflect the time of the copy and as a consequence the output files differ depending on when that (uncached) copy was performed. This unnecessary difference then cascades down the task dependency chain preventing cache hits and the related build avoidance.

**Comment by aalmiray** [comment]
I'm interested in this feature. Stale bot stay away for one more year.

**Comment by ov7a** [comment]
Sorry for the late reply.

While it might be tempting to have an API for setting lastModified time, it's unlikely that there is a scenario when a custom timestamp should be set. It should be either the actual time or the preserved original modification time. That covered already in
* https://github.com/gradle/gradle/issues/1252

Introducing an extra API to change the modification time would add an extra method with little value. And Copy task is already bloated with all kinds of stuff. So, I'm closing this. Further work of redesign of the Copy task related to this issue should be done in #1252.
