### ISSUE TITLE
Ability to re-run selected tasks

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9166]
We have the `--rerun-tasks` command-line option that re-executes every task in the task graph even if there are no detected changes. While this can be useful, there's another use case that is not supported this way, which is to only re-run a single task. This is typically useful when trying to re-run tests from an IDE while debugging, or when trying to diagnose flaky tests from the command-line.

Without the build-cache, a workaround can be to run `cleanTest test`. However, with the build-cache enabled, this just results in the previously stored outputs to be reloaded without the tests being re-executed.

Of course, using `--rerun-tasks` achieves the goal of re-running the tests, however, it will also re-run all the dependent tasks, too, adding a potentially prohibitively large overhead.

We should instead allow the user to specify in some way the subset of tasks they want to re-run.

Probably the most straightforward way to do this is to only re-run tasks that are requested. E.g. something like:

```bash
$ ./gradlew --rerun test
```

...would only re-run the `test` tasks in the project.

We could also rename `--rerun-tasks` to `--rerun-all` perhaps.

**Comment by lptr** [comment]
Using `--rerun-tasks` currently also means disabling incremental execution for every task. I guess we'd want to keep this for `--rerun` as well. Moreover, we should remove all outputs before execution for any task that is "re-ran". (We already do this for tasks using the new `IncrementalInputs` API, but in case of `--rerun` we can be more aggressive.)

**Comment by wolfs** [comment]
Instead of adding a global command line option to select which tasks to rerun, it would be simpler (and better IMO) to add a command line option to each task (i.e. to `DefaultTask`).

That way, you could do
```
gradle test --rerun
gradle compileJava --rerun test
```
and similar things.

The implementation would only be a few lines of code, see for example here: https://github.com/gradle/gradle/pull/9502/commits/630fa3ecca0cb3f2c403e1364090156f2d7e71e3

**Comment by paplorinc** [comment]
Hey team, is this still on the roadmap? :)

In the case of failing test suites that have an expensive setup, this could save quite a lot of time (cc: @almilo.

**Comment by oldergod** [comment]
I like this idea.

**Comment by dboreham** [comment]
> I recently needed something like this and went with an init script.

Apologies for the dumb question, but this seems to be the only viable solution to a missing (intentionally) feature in gradle: 

Can you give some tips on using this code for non-gradle-experts? I've tried pasting it into `~/.gradle/init.gradle` but doesn't seem to work (tests task still skipped). Thanks!

**Comment by abstratt** [comment]
We still want to make a few additional changes for this:

- implement validation for custom task options so that we produce a warning for those clashing with built-in task options
- clean-up DistributionTest
- update the nightly Gradle builds run under to last night's

New PR coming down the pike.

**Comment by hmijail** [comment]
The [Gradle docs](https://docs.gradle.org/current/userguide/java_testing.html#sec:forcing_java_tests_to_run) have been wrong for [years](https://github.com/gradle/gradle/issues/9153#issuecomment-577663226), stating that `gradle cleanTest test` should be used to force the rerun of tests. Would be a good moment to fix.
