### ISSUE TITLE
Updating from Gradle version 4.10.1 to 5.1.1 causes `Unresolved reference` errors

### ISSUE THREAD

**Issue by Klyner007** [gradle/gradle#9169]
The problem I have has to do with ROS libraries; ROS Java bootstrap's "message_generation" library to be specific. This library has the same relative path as the rosjava library(when you import it); namely "org.ros.*". I am not sure if this has anything to do with the issue.

### Expected Behavior
All is OK. The libraries are found and can be navigated to. No compiler errors are present.

### Current Behavior
The import `org.ros.message.MessageListener` from library `message_generation` from rosjava_bootstrap is colored red partly. `Unresolved reference: message` is shown in the tooltip. Same applies to the definitions of this library.

When I try to build the project this gives the error `Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath: class sensor_msgs.CompressedImage, unresolved supertypes: org.ros.internal.message.Message`.

org.ros.internal.message.Message originates from the same library(`message_generation`).

### Context
Nothing changed in the file or import structure. The `message_generation` is just imported with a jar file. The working library is imported using an `implementation` definition in Gradle. I'd like to be able to use the newest Gradle version without having the current issue.

### Your Environment
build.gradle (app)

    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "fsrt.service"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    dependencies {
       implementation fileTree(include: ['*.jar'], dir: 'libs')
       implementation 'com.android.support:recyclerview-v7:28.0.0'
       androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
           exclude group: 'com.android.support', module: 'support-annotations'
       })
       // Service messages
       //implementation 'fsrt.service:shared:0.1'
       // ROS
       implementation 'org.ros.rosjava_core:rosjava:0.3.5'
       implementation 'org.ros.rosjava_messages:sensor_msgs:1.12.5'
       // JSON converter
       implementation 'com.google.code.gson:gson:2.8.2'
       // Websockets
      implementation 'org.java-websocket:Java-WebSocket:1.3.7'
       // Android Room
       implementation 'android.arch.persistence.room:runtime:1.1.1'
       annotationProcessor "android.arch.persistence.room:compiler:1.1.1"
       implementation 'android.arch.lifecycle:extensions:1.1.1'
       // Android support libraries
       implementation "com.android.support:appcompat-v7:${supportLibraryVersion}"
       implementation "com.android.support:design:${supportLibraryVersion}"
       implementation "com.android.support:cardview-v7:${supportLibraryVersion}"
       implementation 'com.android.support.constraint:constraint-layout:1.1.3'
       testImplementation 'junit:junit:4.12'
       implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
     }

**Comment by big-guy** [comment]
I think you're running into this: https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:pom_compile_runtime_separation

This was a change from 4.x to 5.x.  

If [this is the right metadata](https://github.com/rosjava/rosjava_mvn_repo/blob/master/org/ros/rosjava_messages/sensor_msgs/1.12.5/sensor_msgs-1.12.5.pom), I think ROS is publishing the wrong thing. This says that you only need the jar that contains `org.ros.internal.message.Message` when running your application and not when you're compiling it, which doesn't seem to be the case.  To fix this, you'll need to add the extra dependencies that ROS isn't including for compilation. 

If you run `gradle dependencies` with your build with 4.10.1 and then again with 5.1.1, you'll be able to find the other dependencies that are missing.
