### ISSUE TITLE
Kotlin script gradle proeprties

### ISSUE THREAD

**Issue by igorwojda** [gradle/gradle#9170]
We are defining a few properties in `gradle.properties` that latter may be overridden by CI. We defining these properties here to get more clarity (on what cmd parameters can be used by CI).
```
foo=""
bar="ABC"
```

### Expected Behavior
I want to have an easy way to determine if the property has an empty string value:
```
foo: ""
foo.isNotBlank(): false
foo.isNotEmpty(): false
foo == "": true

bar: "ABC"
bar.isNotBlank(): true
bar.isNotEmpty(): true
bar == "": false
```

### Current Behavior
property comparistion seems to be broken. `isNotBlank`, `isNotEmpty` and direct comparistion seems not to have any efect
```
val foo: String by project
foo: ""
foo.isNotBlank(): true
foo.isNotEmpty(): true
foo == "": false

val bar: String by project
bar: "ABC"
bar.isNotBlank(): true
bar.isNotEmpty(): true
bar == "": false
```

### Context
Gradle 5.4
Using Kotlin gradle script to access property in Android project
```
val foo: String by project
val bar: String by project
```

**Comment by eskatos** [comment]
@igorwojda, the `gradle.properties` files are JVM `.properties` files. There's no support for quotes in those files, meaning you get `""` for the `foo` property as expected, not an empty string. Same for your `bar` property for which you get the `"ABC"` string, not just `ABC`.

Closing as working as expected.
