### ISSUE TITLE
ArtifactTransform on non-project artifacts is running both sequentially and not early

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#9173]
If a task triggers transformations of downloaded artifacts (as opposed to project-generated artifacts), these are run just before the task and run sequentially rather than in parallel.

This is problematic for the android plugin. Our main usage of this right now is pre-dexing the jars from dependencies (both external and project-generated, though this is handled by 2 different tasks).

One could think that this only need to run once, be cached and will not need to run again. However there are several cases that can trigger a re-run of the transforms:

- Change to `buildSrc`. A pattern popular with our users is to put dependency versions in a class in `buildSrc`. This allow nice code completion is the IDE. However every time this gets edited, a full build happens. We are hearing complaints about this more and more from developers.
- Our dexing process include desugaring of Java 8 features. In order to do this we need to know the `minSdkVersion` of the app. If this changes, this will trigger a recomputation. One thing to know is that when deploying from Studio to a device we inject the `minSdkVersion` of the target device into the build to override the app's own `minSdkVersion`. So this number can change more often than expected. Sure the computation is still cached, but that means that if you test across several API level, you will redex your dependencies for all API levels every time you change your dependencies.

I'm trying to get actual numbers using the gradle profilers but ran into https://github.com/gradle/gradle-profiler/issues/122 . I will run numbers manually and post some numbers using the large test project.

**Comment by wolfs** [comment]
Fixed via #9352.
