### ISSUE TITLE
TestKitFunctionalTestSpockBuildCache Sample Never Hits The Cache If The Output Is A Directory

### ISSUE THREAD

**Issue by lingocoder** [gradle/gradle#9181]
Specific build commands run in a specific sequence in a command line build results in cache hits for a custom task as and when expected. Yet those exact same build commands run in the exact same sequence programmatically in [*a Spock/TestKit functional test*](https://github.com/lingocoder/jarexec.plugin/blob/master/src/test-functional/groovy/com/lingocoder/plugin/jarexec/JarExecPluginCacheabilityFunctionalTest.groovy), fail to produce build cache hits for the exact same task code that successfully produces cache hits from the command line. 

This issue has led me to suspect that there could be *some kind* of defect either in TestKit or [*the User Guide's sample code*](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/samples/testKit/gradleRunner/testKitFunctionalTestSpockBuildCache/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy).

### Expected Behavior

`FROM_CACHE` outcome

### Current Behavior

`UP_TO_DATE` outcome

### Context

I'm working on a custom [`@CacheableTask`](https://github.com/lingocoder/jarexec.plugin/blob/master/src/main/java/com/lingocoder/plugin/jarexec/ExecJar.java) for a custom plugin.

I am trying to accomplish the automation of functional testing for that `@CacheableTask`.

The task has `@Inputs` and `@Outputs`, etc. More specifically, it has a directory that is annotated as an `@OutputFile`. In normal operation I can build the project directly from the command line and get cache hits under the expected conditions. For example, I can do:

1. `gradle build` and get an `UP_TO_DATE` outcome. 

2. `rm -fr` to delete the output directory or just do a `gradle clean build` and I get the expected `FROM_CACHE` outcomes whenever I want.

### Steps to Reproduce 

[*Here is a self-contained custom plugin project with a cacheable task*](https://github.com/lingocoder/jarexec.plugin). It contains [*a Spock/TestKit functional test*](https://github.com/lingocoder/jarexec.plugin/blob/master/src/test-functional/groovy/com/lingocoder/plugin/jarexec/JarExecPluginCacheabilityFunctionalTest.groovy) in which the reported issue occurs.

The steps that led me to the issue are:

1. I copied [*the sample Groovy code*](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/samples/testKit/gradleRunner/testKitFunctionalTestSpockBuildCache/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy) to a file within my existing project.

2. I copied the plugin DSL block, the dependency block, the task configuration, etc., from [*my project's `build.gradle`*](https://github.com/lingocoder/jarexec.plugin/blob/master/build.gradle)

3. I pasted that into [*the User Guide sample test's `buildFile`*](https://github.com/lingocoder/jarexec.plugin/blob/master/src/test-functional/groovy/com/lingocoder/plugin/jarexec/JarExecPluginCacheabilityFunctionalTest.groovy)

4. I followed [*the User Guide's instructions to the letter*](https://docs.gradle.org/current/userguide/test_kit.html?_ga=2.6802610.1624497841.1555478375-568002704.1555478375#sub:test-kit-build-cache)

### Your Environment

`Java 11`
`Gradle version 5.3.1`
`Linux`

Due to Privacy concerns, I'd rather not publicize the information build scans reveal.

**Comment by wolfs** [comment]
@lingocoder Thank you for reporting. I did run the test locally, and for the first run I saw this in the info log:
```
Caching disabled for task ':execjar' because:
  Gradle does not know how file 'jaxrs.out' was created (output property 'watchOutDir'). Task output caching requires exclusive access to output paths to guarantee correctness.
```

So caching was disabled since something else placed the `jaxrs.out` file in the output directory. The task itself didn't work on my machine with this message:
```
Task ':execjar' is not up-to-date because:
  No history is available.
Cannot run program "java": error=2, No such file or directory
java.io.IOException: Cannot run program "java": error=2, No such file or directory
```

The task does not fail though... It probably also doesn't create any output, that's why it is up-to-date on the second run.

All in all, this doesn't seem to be a problem with testkit.

**Comment by lingocoder** [comment]
Hey Thanks @wolfs for investigating that. And thanks for keeping me in the loop.

> ...*The task itself didn't work on my machine*...

Thanks. When did you clone/download it by the way? There have been a lot of changes since I first reported this a few months ago. But I'll investigate and see if I can make it fail the way it did on your machine.

Do you remember what you did to make it fail?
