### ISSUE TITLE
Add beforeTask/afterTask callbacks

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#9182]
while hooking 3rd party build systems (eg: Android's) i usually need to write the same silly helpers:

```
    static void beforeTask(Task task, Closure closure) {
        task.project.gradle.taskGraph.beforeTask {
            if (it.is(task)) closure()
        }
    }

    static void afterTask(Task task, Closure closure) {
        task.project.gradle.taskGraph.afterTask {
            if (it.is(task)) closure()
        }
    }
```

and more recently, also the equivalent `TaskProvider` versions. would you consider adding them to the API? thanks!

**Comment by lacasseio** [comment]
Could you expand on the use case these hooks solve? The issue with such hooks is the inability to cache or compute the up-to-date check.

**Comment by Lanchon** [comment]
in my case it's a common use case for `TaskGraph.before/afterTask`.  not if you are developing an independent plugin, but if you are hooking into somebody else's work; i've encountered the need a couple of times.

instead of describing a use case, i'll link you to it as soon as i commit. but in a couple of days, i'm at the beach now.

**Comment by Lanchon** [comment]
here is the use case:

https://github.com/DexPatcher/dexpatcher-gradle/blob/03e1144691918c275ebdbfc8c2295599e5f00478/src/main/groovy/lanchon/dexpatcher/gradle/plugins/PatchedAppPlugin.groovy#L116-L119

i need to intercept the dex files fed to the packageApplication task, process them, and feed the resulting dex files to packageApplication.

when using Android Gradle plugin v3.2.x (or v3.3.x with `android.enableDexingArtifactTransform=false`), the packageApplication task inputs are set during the execution phase, so project.afterEvaluate is too early for reading the input properties and setting the new values. packageApplication.doFirst is too late as up-to-date determinations have already executed. doLast in a task dependency may be skipped if the task is skipped, eg due to it being cached or up-to-date. so i'm using afterTask on the dependency.

**Comment by lacasseio** [comment]
I see the point, however, the use case can be achieved without `beforeTask`/`afterTask` by using a custom configuration task that is running before the `packageApplication` task to configure it. It used to be a common pattern before the Provider API and it should go away as time moves forward. In this case, notifying the Android team of such use case would be the first step as the issue is not within Gradle. As for a cleaner solution, something like this would probably solve the issue:
```
def configureTask = tasks.register("configurePackageApplication") {
    doLast {
        ((ConfigurableFileCollection) packageApplication.get().dexFolders).setFrom patchDex
    }
}
packageApplication.configure { dependsOn(configureTask) }
```

Casting the `dexFolders` into its implementation type `ConfigurableFileCollection` is also something to be concerned about and should be raised to the Android team as it may break in future versions.

If there are additional use cases to consider, please comment them here and we can see if it's worth implementing those methods, however, the use case presented here isn't enough.

**Comment by Lanchon** [comment]
thanks for the help. i think the hacks i'm doing here go well beyond what the android team is willing to support though stable API. hacks such as the casting of dexFoldes are plenty around the codebase and are unfortunately necessary to achieve my goals. in particular, i have to dig into the internal state of the Android plugin, state that they very clearly do not want to expose. so i have to accept the portability issues going forward.

regarding your `configurePackageApplication` solution above, is there any advantage to introducing a task when a graph hook suffices? the hook seems much more lightweight. (the API i proposed would make it more efficient than a task, but the way it's implemented now, who knows...)

**Comment by lacasseio** [comment]
The goal here is to avoid adding APIs that are too specific when other APIs can be used. Each API we add is something we have to test, document and maintain in a future release. It doesn't look much but it's a big investment for a project the size of Gradle. The task graph APIs are useful but not for this type of work.

**Comment by Lanchon** [comment]
i understand, thanks.

come to think about it, a reason to prefer the task solution is that using the proposed hooks one has to rather arbitrarily choose between beforeTask(androidTask) and afterTask(myAddedTask), while a task just cleanly expresses something to be done in between.

beforeTask(A) is useful for when one is hooking A but can't fully determine A's dependencies. (not my case.)

afterTask(A) {...} is useful to avoid this kind of pretty ugly construct:
`B.doLast {...}; B.dependsOn(A); A.dependsOn(X); X.finalizedBy(B);`

btw, sorry for the rant on the other issue. and you are right, it was incubating API after all.

thanks.
