### ISSUE TITLE
TaskProvider does not provide enough info to be useful

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#9183]
`TaskProvider.getName` is meaningless without a companion `getProject` or equivalent. it is as if an API wanted to identify a file by its bare filename without its directory.

### use case

check out this code: https://github.com/gradle/gradle/issues/9182#issue-435477436

now imagine you wanted to add lazy versions with signatures like:
`afterTask(TaskProvider task, Closure closure)`

you'll have to force task instantiation as soon as the first task executes because `TaskProvider` does not provide enough info about its task to identify it.

in this case there is a workaround:

```
    static void afterTask(Task task, Action<? super Task> action) {
        task.project.gradle.taskGraph.afterTask {
            if (it.is(task)) {
                action.execute task
            }
        }
    }

    static void afterTask(TaskProvider task, Action<? super Task> action) {
        task.configure { Task it ->
            afterTask it, action
        }
    }
```

but this doesn't redeem `TaskProvider`. a defaulted `getProject` could be added, but yes, the default would be kinda nasty (`this.get().getProject()`).

**Comment by lacasseio** [comment]
`TaskProvider#getProject()` is not something we are likely to add. The provided use case is not clear enough on why this information is require. `TaskProvider#getName()` were added for convenience only during migration and will be reconsider in the future. Provider are simply a lazy value, some convince method exists foe some type of Provider but those are kept explicitly lean.

**Comment by Lanchon** [comment]
for whatever reason getName was added, it's completely useless without getProject. it's a design bug whether you want to fix it or not.

the use case is very clear: we want to know if a Task reference we have (provided to the call back) is the same task that is hiding behind a TaskProvider. this can be done by checking provider.name and provider.project to match the task values, or by invoking provider.get which instantiates the task needlessly (especially if the task wasn't part of the executing task graph).

as you can see, provider.name alone is completely useless. in general TaskProvider should help out by providing all info possible that can be obtained without instantiating the task:
- name
- project
- task path
- task class

**Comment by lacasseio** [comment]
There should already be a project instance in the methods calling `afterTask`/`beforeTask`. The `Project` instance can be drilled down into the helper methods. At a higher level, referencing task by name should be considered a bad practiced, especially when dealing with variants of a component like in the Android plugin. This is the reason why `TaskProvider#getName()` is controversial. However, this is not something we will be addressing soon. Knowing what the `taskGraph.afterTask` and `taskGraph.beforeTask` is used (use case), we can better advise on what action should be taken on either side.

**Comment by Lanchon** [comment]
i'll expand on the usage of afterTask on the other issue when i commit soon.

> At a higher level, referencing task by name should be considered a bad practice

comparing the pair (task.project, task name) to identify if the task provider would provide a certain task is ugly but always safe. this caveat does not apply.

using myTask.project.tasks.named(myTask.name) that you suggested in another issue is even uglier (table lookup) but also safe.

but i agree that TaskProvider.getProject is in the end an indirect way to know if a task is instantiated.

the workaround i supply in the first post here (calling configure to have code executed only if the task exists) is also an indirect way to know if a task is instantiated.

so it looks like whats needed is TaskProvider.isTaskInstanciated() or some better wording.

unfortunately a default would be needed, and it would have to be `{ get(); return true; }` so i think a better name is needed, such as isBeingLazy.

**Comment by Lanchon** [comment]
see usage of afterTask here:
https://github.com/gradle/gradle/issues/9182#issuecomment-485650075
