### ISSUE TITLE
Hook when Gradle execution finishes

### ISSUE THREAD

**Issue by augi** [gradle/gradle#9185]
As part of work done by [this Gradle plugin](https://github.com/avast/gradle-docker-compose-plugin), we execute background threads (`setDaemon(true)`). If the Gradle is executed without Gradle daemon, then threads are correctly shutdown when the Gradle execution finishes (because also JVM finishes). But this is not true if Gradle daemon is enabled - then threads keep running.

So I need a hook/callback that I could bind, and kill the background threads manually there.

### Expected Behavior
There is an Gradle API that allows to kill background threads when Gradle execution finishes (at least when Gradle daemon is enabled).

### Current Behavior
Now, background threads are still running even if Gradle execution finished. This is because JVM is reused.

### Context
I'm not aware of any hook/callback that I could use to solve this issue :(

The issue in my plugin has been reported [here](https://github.com/avast/gradle-docker-compose-plugin/issues/188)

**Comment by lacasseio** [comment]
What you most likely searching for is [Gradle#buildFinished] (https://docs.gradle.org/current/javadoc/org/gradle/api/invocation/Gradle.html#buildFinished-org.gradle.api.Action-). The bigger question is why you need to execute unmanaged thread in your build. You should consider the worker API. There isn't a need for any specific features.
