### ISSUE TITLE
Compare the binary form of local cache property for up-to-date check

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#919]
### Expected Behavior
Avoid `ClassNotFoundException` on subsequent build execution once a task property was captured as input.

### Current Behavior
Depending on the `ClassLoader` context a `Serializable` type was used as task input property, a `ClassNotFoundException` will be raised due to how Gradle handle local cache entries. The is lots of different edge case where [`CacheBackedTaskHistoryRepository.loadPreviousExecutions`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CacheBackedTaskHistoryRepository.java#L125) won't choose the right `ClassLoader` for the `serializer`. Choosing the right `ClassLoader` is [not a trivial task](https://github.com/gradle/gradle/issues/784).

### Context
Issue gradle/gradle#784 started the discussion regarding a more permanent fix. In a nutshell, before commit 77c3d80ea27997ddc2fbc597f41c6efeec44d145 we would grab the classloader for the current task class which happens to be the build script classloader where the serialized type is declared only if the task class was declared in the build script. The change in Gradle 3.2 fixed the scenario where the task class was a Gradle core type and the serialized type was declared in `buildSrc`. In this case, we would be getting the core classloader (through the task class) that have no knowledge of the `buildSrc` and build script declared types. The solution was to use the project level class loader. However, this classloader doesn't have any knowledge of the build script declared types.

We explored using a `MultiParentClassLoader` and capturing the compiled build script instance in order to get the build script classloader at a later time. Both solutions are not enough. In the first solution, we are simply hacking a fix without addressing the real problem. It is also vulnerable to more issues in the case of class collision between multiple classloaders. In the second solution, we need to consider how is affect Kotlin support. Groovy and Kotlin are both affected by this issue. Furthermore, there are extra edge cases that cause the same failure.

The solution to explore is to converge toward how the build cache is handling cache entries. This solution involves a one-way serialization by comparing the serialized binary instead of trying to deserialize the task input from the local cache. This would deprecate property values with custom `equals()` method.

### Steps to Reproduce (for bugs)
[This test case](b2e8fd941ec3483dcee693fe0b454a0b68fd60fa) exposes one way to reproduce the problem.

An additional test case can be derived by removing/changing the `enum` type between build invocation.

**Comment by lacasseio** [comment]
A partial solution was developed for this issue in [this branch](https://github.com/gradle/gradle/tree/dl-issue-919).

**Comment by eriwen** [comment]
Related to #784

**Comment by lacasseio** [comment]
The code review for this issue is here: https://github.com/gradle/gradle/pull/962

**Comment by lacasseio** [comment]
[GRADLE-2771](https://issues.gradle.org/browse/GRADLE-2771) is likely to get fixed by the work on this issue.

**Comment by eriwen** [comment]
@lacasseio Is this still in progress? Should we move this back to backlog?

**Comment by lacasseio** [comment]
@adammurdoch It seems your work around `ValueSnapshot` (https://github.com/gradle/gradle/commit/ee61d0038ab42ea1f838e66e25578c96389f73b0) in Gradle 3.4 could enable us to close this issue. Can you confirm so we can close this issue?

**Comment by lacasseio** [comment]
I will close this issue as it seems to be fixed since Gradle 3.4.
