### ISSUE TITLE
Use worker API for built-in code quality tasks

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#9196]
Dogfood worker API for more built-in plugins.

Code quality plugins:
- Checkstyle
- PMD
- CodeNarc
- FindBugs (deprecated)
- JDepend (deprecated)

Checkstyle and CodeNarc are both used by the gradle/gradle build, so we should be able to see some improvement here since we run multiple checkstyle/codenarc tasks on each subproject.  These need to run sequentially right now.

**Comment by bigdaz** [comment]
We are now planning on deferring this, pending the outcome of the "instant execution" work.

**Comment by ldaley** [comment]
@bigdaz I discussed this today with @adammurdoch. I'm not sure that waiting is the right strategy. He and @big-guy are going to discuss next week.

**Comment by shevek** [comment]
oh god this is SUCH A BAD IDEA PLEASE DONT DO IT IT WILL BREAK EVERYTHING

See https://github.com/spotbugs/spotbugs-gradle-plugin/issues/149

**Comment by gengjiawen** [comment]
@bigdaz @ldaley Anything to push this forward ?

**Comment by big-guy** [comment]
@jvandort can this be closed now?

**Comment by jvandort** [comment]
Checkstyle, PMD, and CodeNarc are all now implemented via the worker API.
