### ISSUE TITLE
Problems with using gradle-5.4 in unity

### ISSUE THREAD

**Issue by lichenyigit** [gradle/gradle#9198]
When I use the gradle-5.4 in unity , it happend a problem after building apk.
Information with unity console:

![gradle problem](https://user-images.githubusercontent.com/28697006/56604388-63310400-6634-11e9-9182-448336e06844.png)
When I use the 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom' to try to access it, the result is 404.
When I can think of is that I ask question here, so I throw it here.

**Comment by big-guy** [comment]
Did this fail with 5.3 or older? I think you should be able to resolve this from Google's repository (index page is here https://dl.google.com/dl/android/maven2/index.html).

I don't believe this is an error with Gradle.  You can try asking for more help on our [forums](https://discuss.gradle.org/).
