### ISSUE TITLE
[WARNING: RANT] initial value of properties of boxed primitive types

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#9203]
why the hell did you haphazardly change the initial value of properties in this commit???
https://github.com/gradle/gradle/commit/dbb85f50bb184cc128949d4eec039b9ed30fc170

why the hell you break my code programmed against gradle 4.10 in the **very first** release after that???

why didn't you respect you own mandates and added a new method `.emptyProperty(Class)` and deprecated the one you had instead of needlessly changing the damn semantics of the API? why was my code was intentionally broken on gradle 5.0 when it should have been good though at least gradle 6.0?

why didn't you even document this brain-dead breaking change in the 4.10 -> 5.0 migration guide here:
https://docs.gradle.org/current/userguide/upgrading_version_4.html#changes_5.0
and could you please at least document it now???

i can't believe you guys, this is completely irresponsible. and don't tell me you needed to do this to support property conventions, you didn't. what a waste of time.

**Comment by lacasseio** [comment]
I understand you are unhappy with the change in commit https://github.com/gradle/gradle/commit/dbb85f50bb184cc128949d4eec039b9ed30fc170. The change is part of the stabilizing process that every [Incubating API](https://docs.gradle.org/current/userguide/feature_lifecycle.html#sec:incubating_state) goes through. The summary of the contract is when an API is tagged as incubating, the users should be expecting breaking change without notice. You are welcome to submit a PR for this breaking change.

On another note, it would be preferable for your next issue to follow the issue template as well as reading over the [Code of Conduct](https://gradle.org/conduct/).
