### ISSUE TITLE
Compile dependency on koltin-gradle-plugin:1.3.30 in buildSrc breaks android builds

### ISSUE THREAD

**Issue by sedovalx** [gradle/gradle#9209]
I have a Gradle multi-module project with the buildSrc module. Everything is written in Kotlin except build scripts. One of the project modules is an Android module (with android plugins applied). Then, I had to write a piece of build logic (in buildSrc) that is related to types in the `kotlin-gradle-plugin` plugin, so I added the plugin into dependencies of the buildSrc module.

### Expected Behavior
The build of the Android module shouldn't fail.

### Current Behavior
The Android module fails to build after the change with an error below.

### Context
I want to be able to write build logic that uses types from the `kotlin-gradle-plugin` Gradle plugin. Here is the related issue in the Kotlin project https://youtrack.jetbrains.com/issue/KT-31178.

### Steps to Reproduce 
- take a minimalistic MPP Gradle project with an android build [kotlin-nmpp-playground-2.zip](https://github.com/gradle/gradle/files/3112602/kotlin-nmpp-playground-2.zip)

- update the version of the Gradle wrapper to 5.1.1
```
./gradlew wrapper --gradle-version 5.1.1 --distribution-type all
```
- set `sdk.dir` property in the `local.properties` file 
- check that Gradle is able to configure the project with no errors
```
./gradlew clean tasks
```
- add `buildSrc/build.gradle` script with the following content
```
plugins {
    id("org.gradle.kotlin.kotlin-dsl") version "1.1.1"
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    compile("org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.30")
}
```
- run `./gradlew clean tasks` again and check that project configuration fails with the next output
```
> Configure project :m-r-a
Kotlin Multiplatform Projects are an experimental feature.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/alexander.sedov/Documents/work/sandbox/kotlin-nmpp-playground/m-apps/m-app-android/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':m-apps:m-app-android'.
> com/android/build/gradle/BaseExtension

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':m-apps:m-app-android'.
> compileSdkVersion is not specified.
```
- comment out the line in `buildSrc/build.gradle` where the dependency is added
- run `./gradlew clean tasks` one more time and see that the configuration succeeds

**Comment by spencerwhyte** [comment]
I am also experiencing this issue. As soon as I add `compile("org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.30")`, everything breaks in exactly the way you described.

**Comment by krzysiek-zgondek** [comment]
I don't know if this is still relevant but i did have the same issue and changing from
`implementation(kotlin("gradle-plugin"))`
to
`compileOnly(kotlin("gradle-plugin"))`
in build.gradle.kts of buildSrc submodule did the trick for me

**Comment by chris-hatton** [comment]
I'm also experiencing this issue (eee [Slack thread](https://kotlinlang.slack.com/archives/C19FD9681/p1640237894004100).
As this is the first time I've tried to reference a plugin from `buildSrc`, I'm not sure whether I'm abusing Gradle or whether there's something peculiar about the `multiplatform` plugin that's making it misbehave in this scenario.

**Comment by kvothe321** [comment]
Hi, I am also experiencing the same issue with Gradle 8.7.0. Any updates?
