### ISSUE TITLE
Public contract for Annotation Types broken in stubbed API classes

### ISSUE THREAD

**Issue by ThiporKong** [gradle/gradle#921]
Default values for Annotation Type Elements are missing in stubbed API classes.

I have verified that the library's runtime jar contains the complete Annotation Type. The default values are missing only in the stubbed API jar/classes.

As a quick mitigation please advise how I can force the use of the runtime jar instead of the broken stubbed API jar in my dependencies.

### Expected Behavior
Annotation default values should be included in stubbed API classes, because they are part of the public Annotation contract.

If I have a Java library that defines Annotations Types with default values, then I want to be able to compile against the library's stubbed API jar.

### Context

I suppose the problem is somewhere in the [org.gradle.jvm.tasks.api.internal](https://github.com/gradle/gradle/tree/master/subprojects/platform-jvm/src/main/java/org/gradle/jvm/tasks/api/internal) package.

### Steps to Reproduce (for bugs)
Execute the `build` task:
```gradle
import java.nio.file.Files

plugins {
    id 'jvm-component'
    id 'java-lang'
}

model {
    components {
        def aSrc = Files.createTempDirectory("a-src").toFile()
        new File(aSrc, "Annotation.java").text = """
import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Documented
@Inherited
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface Annotation {
    String value() default "Hello, I'm the default!";
}
"""

        def bSrc = Files.createTempDirectory("b-src").toFile()
        new File(bSrc, "AnnotationUser.java").text = """
public class AnnotationUser {
    @Annotation
    public void test() {}
}
"""

        a(JvmLibrarySpec) {
            sources.java.source.srcDir aSrc
        }
        b(JvmLibrarySpec) {
            sources.java.source.srcDir bSrc
            dependencies.library 'a'
        }
    }
}
```
The outcome will be

    AnnotationUser.java:3: error: annotation @Annotation is missing a default value for the element 'value'

### Your Environment
gradle-3.2.1, JDK 1.8.0

**Comment by ThiporKong** [comment]
Found a workaround by patching the ApiJar task to copy over the runtime JAR:
```gradle
import org.gradle.jvm.tasks.api.ApiJar

import java.nio.file.Files
import java.nio.file.StandardCopyOption

tasks.withType(ApiJar.class) { ApiJar apiJarTask ->
    if (apiJarTask.name == 'aApiJar') {
        AbstractArchiveTask runtimeJarTask = (AbstractArchiveTask)tasks.getByName("createAJar")
        apiJarTask.dependsOn(runtimeJarTask)
        apiJarTask.doLast {
            Files.copy(runtimeJarTask.archivePath.toPath(), apiJarTask.outputFile.toPath(), StandardCopyOption.REPLACE_EXISTING)
        }
    }
}
```

**Comment by bmuschko** [comment]
@ThiporKong Why did you reopen issue after closing it?

**Comment by ThiporKong** [comment]
Because I closed it accidentially. A workaround is not yet a resolution, right?
