### ISSUE TITLE
`Exec` tasks do not execute in parallel in the same project

### ISSUE THREAD

**Issue by ericparton** [gradle/gradle#9215]
I've come across a situation where two simple exec tasks will only run serially even when the parallel flag is set and workers are available. Neither of the tasks depend on each other.

### Expected Behavior

Tasks will run in parallel when all task dependencies have been executed, when workers are available and the parallel flag is set.

### Current Behavior
In this particular case, these two tasks always running serially, even when the parallel flag is set.

### Context

I just upgraded to gradle 5.4, so I thought it might be a regression of some kind, but I can also reproduce it with gradle 4.8. This is all happening within the context of a larger multiproject build, where many other tasks are running in parallel as expected.

### Steps to Reproduce 

Here's a buildscript that can reproduce the issue:
```
plugins {
    id 'base'
}

group 'com.example'
version '1.0-SNAPSHOT'

task task1 ( type: Exec ) {
    workingDir projectDir
    commandLine 'sleep', 10
}

task task2 ( type: Exec ) {
    workingDir projectDir
    commandLine 'sleep', 10
}

check.dependsOn task1, task2
```
with this command:
`gradle build --parallel`

### Your Environment

Build scan URL: https://scans.gradle.com/s/ncsiol47asufc/

**Comment by big-guy** [comment]
This is to be expected, at the moment.  Tasks need to opt into intra-project parallelism by using the worker API.  The `Exec` task doesn't do that yet.

**Comment by ericparton** [comment]
That's good to know, thanks. Do you think I should close the issue or leave it as a feature request?

**Comment by big-guy** [comment]
I renamed it a bit and put it in our bucket of possible improvements for the worker API.  We want to have all built-in tasks to allow parallel execution (even inside the same project) eventually.

**Comment by tonytvo** [comment]
this is probably the most look forward feature for me, do you have a roughly an idea when you guys would start to work on it?
