### ISSUE TITLE
Source dependencies: Issues when trying to replace a JVM library

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#9217]
Motivation for me is to use a slightly modified JVM library that has not merged in an open MR/released version/whatever to replace the version I am currently using. 

### Expected Behavior

* Documentation
Some documentation or guidance as to what to do with a source dependency

### Current Behavior

Here is what I have tried:

`build.gradle.kts`

```kotlin
plugins {
  `java-library`
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

repositories {
  jcenter()
}

dependencies {
    //    implementation("io.github.config4k:config4k:0.4.1")
    //    implementation("io.github.config4k:config4k:0f5914b6279b8415e9c30807b4e7c338216db501")
    //    implementation("io.github.config4k:config4k:master")
     implementation("io.github.config4k:config4k") {
        version {
            branch = "master"
        }
    }
}

```

`settings.gradle.kts`

```kotlin
rootProject.name = "kotlin-dsl-lab"

sourceControl {
//    vcsMappings {
//        withModule("io.github.config4k:config4k") {
//            from(GitVersionControlSpec::class) {
//                url = uri("https://github.com/mkobit/config4k.git")
//            }
//        }
//    }
    gitRepository(uri("https://github.com/mkobit/config4k.git")) {
        producesModule("io.github.config4k:config4k")
//        plugins {
//            id("maven-publish")
//        }
    }
}
```

I've tried different variations of the above with no success in resolving the dependency using `./gradlew build` with a single empty Java source file. It looks like commit references would be supported with https://github.com/gradle/gradle/issues/7770 , but I can't even get that far.

### Context

I was trying to try and use the source dependency feature mentioned on https://blog.gradle.org/introducing-source-dependencies , but I'm doing everything wrong apparently.

**Gradle**: 5.4

**Comment by mkobit** [comment]
The original example I provided was off so I have edited it to a much more reasonable example.

Unfortunately, the first thing I ran into when trying to use it after was:

```
> Could not resolve all task dependencies for configuration ':compileClasspath'.                                       
   > Git repository at https://github.com/mkobit/config4k.git did not contain a project publishing the specified dependency.                                                                                                                  
     Required by:                                          
         project : 
```

Then, trying to just apply `maven-publish`

```
    gitRepository(uri("https://github.com/mkobit/config4k.git")) {
        producesModule("io.github.config4k:config4k")
        plugins {
            id("maven-publish")
        }
    }
```
(which seems right?) results in:

```
* Where:
Injected plugin

* What went wrong:
An exception occurred applying plugin request [id: 'maven-publish']
> Failed to apply plugin [id 'org.gradle.maven-publish']
   > org.gradle.initialization.DefaultSettings_Decorated cannot be cast to org.gradle.api.Project
```

**Comment by davis-th** [comment]
I got the same error and can not find any information for help.
Can anyone tell us how to handle it?

**Comment by vladistan** [comment]
Same here...

**Comment by ddimtirov** [comment]
Linking to #10559

**Comment by julienledem** [comment]
Same error:
```
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all task dependencies for configuration ':compileClasspath'.
   > Git repository at https://github.com/MarquezProject/marquez.git did not contain a project publishing the specified dependency.
     Required by:
         project :
```
Is it not working at all for java or is some metadata missing?

**Comment by xing16** [comment]
Same error:
`
include ':app'
rootProject.name = "ApplicationModule"
sourceControl {
    gitRepository("https://gitee.com/xing16/module_test.git") {
        producesModule("com.fc.moduletest:home")
        rootDir = "home"
    }
}


`


`
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Git repository at https://gitee.com/xing16/module_test.git did not contain a project publishing the specified dependency.
     Required by:
         project :app

`

**Comment by malenalbc** [comment]
Any news about this? After [solving the auth problem](https://github.com/gradle/gradle/issues/8245) I got stuck in this step, where my gradle dependency is downloaded but `:app:compile<Flavor>DebugJavaWithJavac'` fails with this error.
