### ISSUE TITLE
[SDKMAN] [minor] 'gradle.bat' marked as executable on linux

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#9219]
when installing gradle on linux via:
```
sdk install gradle 5.4
```

the `gradle.bat` file is needlessly placed in the PATH and marked as executable.
this pollutes the shell tab autocomplete.

**Comment by lacasseio** [comment]
Sounds like an easy enough thing to contribute as a PR. It seems to be coming from https://github.com/gradle/gradle/blob/master/subprojects/distributions/distributions.gradle#L94-L97. Changing this would also require to align https://github.com/gradle/gradle/blob/master/buildSrc/subprojects/integration-testing/src/main/kotlin/org/gradle/gradlebuild/test/fixtures/IntTestImagePlugin.kt#L170-L173. Finally the change for the distribution would need to add an [integration test in `DistributionIntegrationSpec`](https://github.com/gradle/gradle/blob/master/subprojects/distributions/src/integTest/groovy/org/gradle/DistributionIntegrationSpec.groovy).
