### ISSUE TITLE
The JacocoReportBase.setClassDirectories(FileCollection) method has been deprecated

### ISSUE THREAD

**Issue by sainath199** [gradle/gradle#9222]
I'm trying to use jacoco plugin for build but I'm facing following error

### Current Behavior
gradle jacocoTestReport --warning-mode=all

> Configure project :
The JacocoReportBase.setClassDirectories(FileCollection) method has been deprecated. This is scheduled to be removed in Gradle 6.0. Use getClassDirectories().from(...)
	at build_cyv4aqw024szpuohg9tt2g7bq$_run_closure10$_closure15.doCall(/builds/OCGBU_OCSS/ossbrkr/cloud-broker/build.gradle:127)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)

**Comment by bmuskalla** [comment]
Thanks for raising this. This was a regular deprecation warning to use a new instead of an old API. Please reopen if we misunderstood the issue.
