### ISSUE TITLE
Compilation avoidance for Kotlin DSL scripts

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#9224]
Kotlin DSL should recognize ABI (Application Binary Interface) breaking changes, and trigger recompilation of scripts only in that case.

This wouldn't change the feedback loop duration for API changes in `buildSrc`, but for a non-API change it would short-circuit all build scripts compilation, shortening the feedback loop. On builds with lots of scripts the effect would be dramatic.

**Comment by ZacSweers** [comment]
Commenting because this is actually important

**Comment by eskatos** [comment]
See https://github.com/gradle/gradle/pull/14735
