### ISSUE TITLE
For a multi module project, let the developer establish circular reference between modules.

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#923]
### Expected Behavior

What I need is the option or feature that a Java project based in multi module be able to support circular dependencies between modules. 

Of course is normal that each module should contains all the classes related to a specific role or specification or logic, such as: domain, service api, service impl, validation, etc. But for some scenarios circular references arise.

For example:

In the `module-domain` module exists the `Person` class defined how:

```
@Entity
@Table(name="person")
@DateDeath(groups={PersonDeathCheck.class})
public class Person implements Serializable {
```

See that `Person` class uses or depends on `@DateDeath`

Now, in the `module-validation` module exists the `@DateDeath`  **and** `DateDeathValidator` class. Both defined how:

```
@Target({TYPE})
@Retention(RUNTIME)
@Constraint(validatedBy=DateDeathValidator.class)
public @interface DateDeath {
```

Until here: See that `@DateDeath` uses or depends on `DateDeathValidator`, where:

```
public class DateDeathValidator implements ConstraintValidator<DateDeath, Person>{
```

Until here: See that `DateDeathValidator` depends on:

* `@DateDeath` and it is located in the **same** module: `module-validation`
* `Person` class and it is located in a **different** module: `module-domain`

Therefore:  because `Person` class uses `@DateDeath` and it uses `DateDeathValidator` and it _refers_ again the `Person` class, therefore we have circular reference between these modules.

```
project(':web-27-domain') {
	description 'domain'
        dependencies {
 	   compile project(':web-27-validation')
	}
}

project(':web-27-validation') {
	description 'Validation'
        dependencies {
 	   compile project(':web-27-domain')
	}
}
```

### Current Behavior

The error message about the **circular references**  appears. Yes I know, it is the expected.

### Context

Currently my unique to way to avoid the error message about the **circular references** is merge the code from `web-27-validation` into `web-27-domain`. But I don't like have the own validation control directly within the `domain` module. 

Yes I know has sense have an `Entity` depending directly with other annotations for `Jackson`, `JPA` and _Validation_ such as `JSR-349` (`@NotNull`, etc), but the own validation logic should remain located in a different module. I want keep the coupling as low how possible between modules. 

**Suggestion ( possible solution)**: let the developer define a special attribute within the `project(':web-27-name'){...}` block, specially within `dependencies {...}`, where be able to accept the circular reference.

### Your Environment

*  `Gradle 3.1`
* `Mac 10.11.3`
* `Spring Framework 4.3.x`

**Comment by oehme** [comment]
Circular references are forbidden for good reasons: You couldn't compile the `domain` module without having compiled the `validation`, but you also can't compile the `validation` module without the `domain` module. This just means that the architecture is broken. Either the two need to be merged or they need better isolation, like a service loader mechanism.

**Comment by manueljordan** [comment]
I see your point, and I am agree, but consider the scenario about the `javadoc` working around the `@link` to refer classes or methods for any component around other modules, thus possibly among modules, and perhaps arising the circular dependences
