### ISSUE TITLE
Classifiers and Artifact-only not supported for Java software model dependencies

### ISSUE THREAD

**Issue by ThiporKong** [gradle/gradle#924]
Use of [classifiers and artifact-only notations](https://docs.gradle.org/current/userguide/dependency_management.html#ssub:artifact_dependencies) on [Java software model dependencies](https://docs.gradle.org/current/userguide/java_software.html#sec:declaring_dependencies) yields an IllegalDependencyNotation exception thrown by [DefaultModuleDependencySpec](https://github.com/gradle/gradle/blob/master/subprojects/platform-base/src/main/java/org/gradle/platform/base/internal/DefaultModuleDependencySpec.java#L96).

### Expected Behavior
I expect to be able to use classifiers and artifact-only notations on Java software model dependencies in the same way as described in the chapter [Dependency Management](https://docs.gradle.org/current/userguide/dependency_management.html) in the user guide.

Please advise about work-arounds.

### Steps to Reproduce (for bugs)
```gradle
plugins {
    id 'jvm-component'
    id 'java-lang'
}

model {
    components {
        def zSrc = Files.createTempDirectory("z-src").toFile()
        new File(zSrc, "Z.java").text = ''

        z(JvmLibrarySpec) {
            sources.java.source.srcDir zSrc
            dependencies.module 'org.apache.qpid:qpid-bdbstore:6.1.0:tests'
        }
    }
}
```
yields

    Error:'org.apache.qpid:qpid-bdbstore:6.1.0:tests' is not a valid module dependency notation. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core'.

### Your Environment
Gradle 3.2.1, Java 1.8

**Comment by jjohannes** [comment]
The "Java software model"-plugins are discontinued. Please use the _java-library_ and _java_ plugins instead.
