### ISSUE TITLE
When using the -bin distribution from a Kotlin DSL script sometimes IntelliJ Navigate to source goes to the decompiled source instead of the source

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#9250]
### Expected Behavior

_Navigate to Source_ should always navigate to the source documentation_

### Current Behavior

![peek 2018-09-14 11-43](https://user-images.githubusercontent.com/1447148/45563562-5da84b80-b813-11e8-8eaf-7b717df37618.gif)

At the end of the gif, navigating to `register` does not go to the source code.

### Context

_Navigate to Source_ expected to jump to source but sometimes does not seem to.

### Steps to Reproduce (for bugs)

Was using _Navigate to Source_ in IntelliJ on a bunch of places and noticed some of them didn't always go to the source transformed

### Your Environment

* Gradle 4.10 `bin` distribution
* Kotlin plugin: Version: 1.2.70-release-IJ2018.2-1

**Comment by ov7a** [comment]
Sorry for the late reply.

It was definitely an issue in the past, but I don't think this applies to the latest version of Gradle. The most recent related issue is  
* https://github.com/gradle/gradle/issues/37819

I'm leaving this issue closed as obsolete. If anybody stumbles across a similar problem, please open a new issue.
