### ISSUE TITLE
Consider adding `kotlinx()` to the DependencyHandler in Kotlin DSL

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#9259]
The `KotlinDependecyExtensions` provides some great helper methods to call.
Like `kotlin("stdlib")`.
There exist also the `embeddedKotlin()` function.

I would recommend that you add `kotlinx()` to that as well.
Then coroutines leads from
```
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.0")
```
to
```
implementation(kotlinx("coroutines-core:1.1.0")
```

**Comment by StefMa** [comment]
@eskatos would you merge this if I would create a PR for it?

**Comment by eskatos** [comment]
A better home for that would be the Kotlin Gradle Plugin

**Comment by StefMa** [comment]
I am not aware of the current state / code of the Kotlin DSL stuff.
But wouldn't it make sense to have both extensions (`kotlin()` and
`kotlinx()`) at the same place? 🤔

Anyways. I see two plugins. The Kotlin DSL base and "just" kotlin DSL
plugin. In which of them would you add it?

**Comment by eskatos** [comment]
Both `kotlin()` and `kotlinx()` extensions would be better in the Kotlin Gradle Plugin at https://github.com/JetBrains/kotlin.

**Comment by StefMa** [comment]
Ah sorry 😅 that is what you mean.
Yeah, I agree. Will close this.
