### ISSUE TITLE
Add deprecation warnings to "deprecated" generated Kotlin DSL accessors for improved IDE and script compilation experience

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#9269]
It might be useful for the IDE to be able to mark certain generated accessors as deprecated. For example, the `compile` and `runtime` configurations are not recommended in favor of using the `api`, `runtimeOnly`, and `implementation` configurations instead.

Other cases might be when a particular extension/convention is deprecated.

### Expected Behavior

* IDE warnings in build script that uses them
* Toggle the warnings on/off during script compilation time

### Current Behavior

No differentiation between the different generated accessor methods.

### Context

In process of migrating projects that use the "legacy" configurations.

**Comment by jjohannes** [comment]
This is done in #10312 and will be in Gradle 6+.
