### ISSUE TITLE
Consider generating Kotlin DSL static accessors for subprojects

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#9281]
All of the names of all of the subprojects are known at compile time of the `build.gradle.kts` file.
I propose that static fields be generated for subproject's.

For example, if I have the following `settings.gradle` file:
```groovy
include ":algorithms:dijkstra"
include ":algorithms:depth-first"
include ":application"
```

The Gradle Kotlin DSL could generate the following in the `accessors.kt` file:

```kotlin
class `algorithms project`(project: Project) : Project by project {
    class `dijkstra project`(project: Project) : Project by project {
    }
    val `dijkstra` = `dijkstra project`(project.project(":algorithms:dijkstra"))

    class `depth-first project`(project: Project) : Project by project {
    }
    val `depth-first` = `depth-first project`(project.project(":algorithms:depth-first"))
}

class `application project`(project: Project) : Project by project {
}

val Project.`algorithms` = `algorithms project`(rootProject.project(":algorithms"))
val Project.`algorithms` = `application project`(rootProject.project(":application"))
```

The result would be that you could do something like this in your `build.gradle.kts` file:
```kotlin
`algorithms`.`dijkstra` {
    // Some configuration here
}

`algorithms`.`depth-first` {
    // Some configuration here
}

// You could also do something like this:
`algorithms` {
    `depth-first` {
        // Some config here
    }
    `dijkstra` {
        // Some config here
    }
}

// This wouldn't compile (which is good!)
`application`.`dijkstra`
```

**Comment by LouisCAD** [comment]
For reference, there's already a plugin from the community doing exactly that, without even having to call all these `include`s by @pablisco https://github.com/pablisco/auto-module.

This plugin relies on updating the content of `buildSrc`, which means whole build invalidation on every little change, no incremental compilation and no build cache, not good for build performance. It'd be great that Gradle either does what this plugin does without invalidating the whole build because of a new module, a removed one or a rename, or that Gradle allows this plugin to work without invalidating the whole build.

**Comment by pablisco** [comment]
@louisCAD it's still work in progress. There is cache now. I'm currently looking at ways to not require the buildSrc. However, yeah it would be nice if the dsl plugin would generate these 👍

**Comment by Tapchicoma** [comment]
Imho would be still nice to have.

**Comment by JLLeitschuh** [comment]
@melix If I remember correctly, something like this ended up included in the central declaration of dependencies feature?

**Comment by LouisCAD** [comment]
Yep, I think it's part of Gradle 7 already, I need to try using it.

**Comment by ephemient** [comment]
https://docs.gradle.org/7.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors

**Comment by JLLeitschuh** [comment]
I think this is likely the closes to my vision that we're going to get on this feature. I think for most things, we're going to suggest using precompiled script plugins over using the `subprojects` and `allprojects` block in the future.

**Comment by ljacomet** [comment]
This will not be done this way and is indeed superseded by type safe project accessors.

Closing
