### ISSUE TITLE
Performance regression for input snapshotting between Gradle 5.4 and Gradle 5.3.1

### ISSUE THREAD

**Issue by dcabasson** [gradle/gradle#9287]
Working on a large gradle build, we see some performance regression in input snapshotting times between Gradle 5.4 and Gradle 5.3.1

With the same code, the only difference being the version of Gradle and running
`gradlew clean assemble && gradlew assemble` the time spent on input snapshotting in the assemble after a clean assemble has increased by about 25%.

### Gradle 5.3.1 
(as reported by Gradle Entreprise)
Snapshotting task inputs	1699	2m 15.687s
from build id vamgc5az42l4g

### Gradle 5.4
(as reported by Gradle Entreprise)
Snapshotting task inputs	1699	2m 50.139s
from build id p7qcw6k32wavm

**Comment by lptr** [comment]
We are waiting for more data on this from @dcabasson.

**Comment by dcabasson** [comment]
After further testing, it looks like 5.4.1 is actually faster than 5.3.1

Sorry about the noise.
