### ISSUE TITLE
WindowsSdkLocator doesn't detect Windows SDK 10

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#929]
### Expected Behavior
Gradle should detect and use the Windows SDK 10 if installed or directly pass as a candidate.

### Current Behavior
Gradle doesn't detect and use Windows SDK 10. On a clean machine (possibly only Windows 10) with a fresh install of Visual Studio 2015, Gradle fail to build any application that requires access to the Windows SDK (for example `kernel32`).

### Context
This is a bit tricky to solve as with Windows SDK 10, Microsoft started versioning the `include` and `lib` in relation to move toward the Universal C Runtime.

### Steps to Reproduce (for bugs)
On a fresh Windows 10 machine with only Visual Studio 2015 install try to build CUnit sample.

**Comment by lacasseio** [comment]
The current workaround is to either:
1. Install older version of the Windows SDK (for example 8.1)
2. Enter the include path and library path manually as compiler and linker `args`

Option 1 may have side effect and undefined behavior regarding breaking changes made the Windows API between 8.1 and 10 or missing feature as you will be targeting Windows 8.1 feature set.

**Comment by zosrothko** [comment]
This could be fixed by making WindowsSdkLocator  working in the same way as DefaultUrctLocator and abstracting both to a common WindowsLocator.

**Comment by pedrolamarao** [comment]
I've just hit the same bug.
This is what I get when running gradle with --debug:

13:23:37.595 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultWindowsSdkLocator] Ignoring candidate Windows SDK directory C:\Program Files (x86)\Windows Kits\10 as it does not look like a Windows SDK installation.
13:23:37.596 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultWindowsSdkLocator] Could not find Windows resource compiler in system path.
13:23:37.596 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultUcrtLocator] Found ucrt 10.0.10240.0 at C:\Program Files (x86)\Windows Kits\10
13:23:37.597 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultUcrtLocator] Found ucrt 10.0.10240.0 at C:\Program Files (x86)\Windows Kits\10

**Comment by eriwen** [comment]
@lacasseio @eljobe can this be moved to gradle-native?

**Comment by prb28** [comment]
This may help someone (workaround 1 from @lacasseio) :
with gradle 4.5.1, installing **VC++ 2015.3 v140 toolset (x86,x64)** did work.
![vctools](https://user-images.githubusercontent.com/10462286/36262414-a6e7fe32-1267-11e8-8dcb-0884f7227463.png)
_(Image borrowed from https://stackoverflow.com/questions/44046355/visual-studio-2015-not-detecting-v141-2017-build-tools)_

**Comment by adammurdoch** [comment]
This is fixed in https://github.com/gradle/gradle/pull/4414. I'm going to close this issue. Please open a _new_ issue if you run into any further problems with Visual Studio or Windows SDK discovery.
