### ISSUE TITLE
Composite builds don't work with Maven BOM support

### ISSUE THREAD

**Issue by rschmitt** [gradle/gradle#9294]
### Expected Behavior

When using a Maven BOM to manage dependencies within a platform, composite build task dependency resolution should work correctly.

### Current Behavior

Attempts at using a composite build result in a circular task dependency being reported, apparently because each project references the BOM and the BOM references each project. (This works fine outside of composite builds.)

### Context

I have a number of projects (over a hundred) that use a legacy build system. I'm trying to enable them to build on Gradle, while also continuing to build on the legacy build system, which means I have to maintain their legacy structure (separate projects). The projects depend on each other, and I want to use a Maven BOM file to specify what the latest version of each project is, and to manage inter-project dependencies. At the same time, I want to use composite builds, because they enable me to check out arbitrary subsets of these packages and build them all together in parallel.

### Steps to Reproduce 
Repro here:
[repro.tar.gz](https://github.com/gradle/gradle/files/3118950/repro.tar.gz)

Repro output:

```
+ cd bom
+ mvn install
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------------< repro:bom >------------------------------
[INFO] Building bom 1.0.0
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ bom ---
[INFO] Installing /Users/ryansch/ws-gradle/repro/bom/pom.xml to /Users/ryansch/.m2/repository/repro/bom/1.0.0/bom-1.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.338 s
[INFO] Finished at: 2019-04-25T14:42:05-07:00
[INFO] ------------------------------------------------------------------------
+ cd ../composite
+ gradle assemble

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:a:compileJava
\--- :a:compileJava (*)

(*) - details omitted (listed previously)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

### Your Environment

I am using Gradle 5.4, Maven 3.6.1, and OpenJDK 11.

**Comment by tronku** [comment]
@wolfs are we planning to include this anytime soon?

**Comment by ov7a** [comment]
@tronku This area of Gradle is currently not a focus one, so it might take a while before this issue would be considered.
