### ISSUE TITLE
Let the Kotlin DSL IDE script editor resolver support non-jvm IJ projects

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#9299]
This is about supporting the rich Kotlin DSL script editor in IntelliJ projects that are not JVM based, e.g. python, javascript, native ...

### Expected Behavior

Editing a `.gradle.kts` script in IntelliJ IDEs in a Gradle project that is not JVM based, iow where the _Project SDK_ isn't a JVM, should work in the same way as with JVM based projects.

### Current Behavior

Non JVM based IntelliJ IDEs don't support the rich Kotlin DSL script editor for `.gradle.kts` files when the _Project SDK_ is not a JVM.

### Implementation notes

This will require coordinated changes to both the Kotlin IntelliJ Plugin and Gradle.

First, https://youtrack.jetbrains.com/issue/KT-31152 need to be fixed in a released Kotlin version.

Then our `KotlinBuildScriptDependenciesResolver` need to relay the `javaHome` environment in the returned script dependencies.

For more details, see the original report https://github.com/gradle/kotlin-dsl/issues/1354.

A previous attempt was made in Gradle 5.4 https://github.com/gradle/gradle/pull/8756 but it made that Kotlin issue linked above very visible, hence reverted in Gradle 5.4.1 https://github.com/gradle/gradle/issues/9195

**Comment by eskatos** [comment]
`KT-31152` is marked as fixed for Kotlin 1.3.50

**Comment by NataliaUkhorskaya** [comment]
@eskatos Yes, the fix was chipped with 1.3.50. So is it possible to revert the fix in some next version of Gradle?

**Comment by eskatos** [comment]
Fixed in #10350, will ship in 6.0
