### ISSUE TITLE
"apply from" makes task disable

### ISSUE THREAD

**Issue by VeiZhang** [gradle/gradle#9308]
When using "apply from" in Android Studio gradle file, I see some custom tasks is gone and disable. if remove "apply from", it will be normal.

* normal
![normal](https://user-images.githubusercontent.com/19425616/56857456-6e6f9100-69a0-11e9-9fe9-9c4a76c8f380.png "normal")

* unnormal
![unnormal](https://user-images.githubusercontent.com/19425616/56857457-6e6f9100-69a0-11e9-9e62-ff7eda30faab.png "unnormal")

**Comment by lacasseio** [comment]
We can't help if no sample project reproducing the failure is provided. We also need more information regarding which version of Gradle are you using. If these information can be provided, reopen the issue.

**Comment by VeiZhang** [comment]
@lacasseio Thanks a lot. I found the reason.
