### ISSUE TITLE
Gradle does not run simple OpenJDK 12, JavaFX 12 project out of the box

### ISSUE THREAD

**Issue by pelamfi** [gradle/gradle#9309]
A very simple Java 12 / OpenJDK 12 project with a JavaFX 12 dependency does not run using gradle 5.4.1

./gradlew run produces these errors:
module not found: javafx.controls
module not found: javafx.graphics

Here is a simple GitHub hello world project. (The master in that same repo works due to several hacks, that should probably not be necessary.)

https://github.com/pelamfi/gradle-javafx-hello-world-app/tree/gradle-javafx-run-not-working

### Expected Behavior
"./gradlew run" should open a window

### Current Behavior
```
$ ./gradlew run

> Task :compileJava FAILED
/Users/pete/lattana_workspace/gradle-javafx-hello-world-app/src/main/java/module-info.java:2: error: module not found: javafx.controls
    requires javafx.controls;
                   ^
/Users/pete/lattana_workspace/gradle-javafx-hello-world-app/src/main/java/module-info.java:3: error: module not found: javafx.graphics
    requires javafx.graphics;
                   ^
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```
### Context
I'm trying to help people (and my self) on StackOverflow. Starting with a simple
JavaFX project is needlessly hard. I'm not absolutely sure whose problem this should
really be and it could be I'm just not reading documentation right and missing something
simple.

It is important to note, that the plugin `org.openjfx.javafxplugin` works 
as demonstrated in the [master branch of my example project](https://github.com/pelamfi/gradle-javafx-hello-world-app).

However,  I feel that for a simple project a plugin should not be necessary
as all that is really needed is to add some dependencies and configure the
Java `--module-path` and the `--add-modules` settings as shown in
[a hacky way this branch](https://github.com/pelamfi/gradle-javafx-hello-world-app/tree/gradle-javafx-run-working-without-plugin-and-with-hacks).

Anyway, here is my answer to the question "Building a JavaFX application using Gradle":
https://stackoverflow.com/a/55889428/1148030

### Steps to Reproduce 
Clone the branch [gradle-javafx-run-not-working](https://github.com/pelamfi/gradle-javafx-hello-world-app/tree/gradle-javafx-run-working-without-plugin-and-with-hacks) of
[my example repository](https://github.com/pelamfi/gradle-javafx-hello-world-app)

```
git clone --single-branch --branch gradle-javafx-run-not-working git@github.com:pelamfi/gradle-javafx-hello-world-app.git

cd gradle-javafx-hello-world-app

./gradlew run 
```

### Your Environment
```
$ sdk current

Using:

gradle: 5.4.1
java: 12.0.1-open
sbt: 1.1.4
scala: 2.12.8
```

MacOS mojave 10.14.4 (18E226)

Build scan URL: https://scans.gradle.com/s/rcynl52nopika

**Comment by SupinePandora43** [comment]
same issue with Gradle 5.2.1, AdoptOpenJDK 12.0.1 x86, Windows 7 x86

**Comment by pelamfi** [comment]
This issue is now fixed! (Closing this)

Tested with Gradle 6.6.1 and now it works with some simple Gradle configuration.

See my example at:
[https://github.com/pelamfi/gradle-javafx-hello-world-app/tree/gradle-javafax-run-without-javafx-plugin](https://github.com/pelamfi/gradle-javafx-hello-world-app/tree/gradle-javafax-run-without-javafx-plugin)

The relevant parts of Gradle documentation are here:

Gradle documentation for the Application plugin which shows how
to inform the plugin about the module that contains the main:
https://docs.gradle.org/current/userguide/application_plugin.html

Gradle documentation showing how to enable the module support (inferModulePath)
https://docs.gradle.org/current/samples/sample_java_modules_multi_project.html
https://guides.gradle.org/building-java-9-modules/ (Previous referred from here)

Gradle documentation showing how to set up a Java module:
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular
