### ISSUE TITLE
Let configure pluginRespository in Gradle Wrapper

### ISSUE THREAD

**Issue by daniilguit** [gradle/gradle#932]
I have lots of separated projects with our custom plugins stored in Artifactory Maven repo. I want to use `plugins { id '' version ''}` syntax for them, so I need to configure [plugin repository](https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories).
I want to configure this in custom gradle distribution that is used by Gradle Wrapper instead of configuring it for each project. Currently it needs to be configured in settings.gradle which is parsed before all init.d scripts so I guess it is not possible to do it from there.

### Expected Behavior
It should be somehow possible to configure plugin repository inside gradle distribution (like it is possible to do for build scripts & and common dependencies inside init.d scripts)

### Current Behavior
Currently, this plugin repository is defined in settings.gradle and hence can not be set 'globally'.

**Comment by oehme** [comment]
This will be possible once we remove the special handling for `pluginRepositories` and make them a normal method on `Settings` (see #1343). Then you can use the [settingsEvaluated()](https://docs.gradle.org/current/javadoc/org/gradle/BuildListener.html#settingsEvaluated(org.gradle.api.initialization.Settings)) hook in init scripts to add plugin repositories from a custom distribution.

**Comment by oehme** [comment]
Thanks for pointing this out, this was indeed fixed in 3.5
