### ISSUE TITLE
Rename "property type" to "property role" when dealing with property annotations

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9327]
When we have a parameter declared like this:

```groovy
class MyTask extends DefaultTask {
    final @InputFiles ConfigurableFileCollection sources

    // ...
}
```

We currently have some code that talks about "property type" of the `sources` property when observing the `@InputFiles` annotation. This is a big ambiguous, as `ConfigurableFileCollection` is also the "type" of that property.

We could perhaps call the type determined by the `@InputFiles` annotation the "role" of the property.

**Comment by paplorinc** [comment]
See:
* org.gradle.model.internal.manage.schema.extract.StructSchemaExtractionStrategySupport#determinePropertyType

which gets the return value of the property
vs
* org.gradle.api.internal.tasks.properties.DefaultTypeMetadataStore.DefaultPropertyMetadata#getPropertyType

which gets the annotation of the property
