### ISSUE TITLE
Cannot execute `buildSrc` tests in IDEA when using kotlin-dsl precompiled scripts in `buildSrc`

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#9328]
Running code in `buildSrc` should work when using precompiled script plugins.

### Expected Behavior

Should be able to execute and run tests, `main()`, and other code in `buildSrc` like normal Kotlin modules.

### Current Behavior

IDEA fails with Kotlin compiler errors.

### Context

Trying to make conventional plugins and test them in `buildSrc`. Team uses IntelliJ to quickly run and debug the tests for bits of logic or plugins we have introduced in `buildSrc`. Not being able to use IDEA breaks the workflow, so we are currently unable to use precompiled script plugins.

### Steps to Reproduce 

![kotlin-dsl-run-something-in-test-module](https://user-images.githubusercontent.com/1447148/56981510-aadbf200-6b44-11e9-9576-04e63608aa71.gif)

* Create `buildSrc`
* Use `kotlin-dsl` plugin
* create a precompiled plugin file, like `dumbplugin.gradle.kts`
* use some `kotlin-dsl` APIs in it, like `val b by tasks.registering`
* create a another type somewhere with a `fun main() {` or something normally excecutable from IntelliJ
* Try and run code

```
Information:Kotlin: kotlinc-jvm 1.3.31 (JRE 1.8.0_201-b09)
Information:Module "kotlin-dsl-lab_buildSrc_main" was fully rebuilt due to project configuration/dependencies changes
Information:4/30/19 12:34 PM - Build completed with 3 errors and 1 warning in 3 s 5 ms
Warning:Kotlin: ATTENTION!
This build uses unsafe internal compiler arguments:
-XXLanguage:+NewInference
-XXLanguage:+SamConversionForKotlinFunctions
-XXLanguage:+NewInference
-XXLanguage:+SamConversionForKotlinFunctions
This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!
/home/mkobit/Workspace/code_lab/kotlin-dsl-lab/buildSrc/src/main/kotlin/my/new/dumbplugin.gradle.kts
Error:(3, 1) Kotlin: No script runtime was found in the classpath: class 'kotlin.script.templates.standard.ScriptTemplateWithArgs' not found. Please add kotlin-script-runtime.jar to the module dependencies.
Error:(3, 10) Kotlin: Unresolved reference: tasks
Error:(4, 3) Kotlin: Unresolved reference: doFirst
```
### Your Environment

* Gradle 5.4.1

IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Licensed to ...
Subscription is active until ...
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-47-generic

**Comment by JLLeitschuh** [comment]
This exact same issue is impacting my co-workers. @oehme saw the same thing the other day too.

This impacts more than just executing tests in the `buildSrc` project, it also impacts trying to execute tests with IJ (ie not using the delegate to Gradle functionality) against normal source sets as well.

Chatting with @bamboo about this, he thinks that this is probably a bug in IJ, not in the Kotlin DSL or the Tooling API.

**Comment by eskatos** [comment]
Thanks for the report @mkobit!
I can confirm it can be reproduced when not delegating IDE actions to Gradle.

It's an IDE integration issue, could you please open an issue for JetBrains on https://youtrack.jetbrains.com/issues/KT?

**Comment by mkobit** [comment]
Created https://youtrack.jetbrains.com/issue/KT-31659 with the same content as the original description

**Comment by narit-teacher** [comment]
Error:(1, 1) Kotlin: No script runtime was found in the classpath: class 'kotlin.script.templates.standard.ScriptTemplateWithArgs' not found. Please add kotlin-script-runtime.jar to the module dependencies.

**Comment by JorgeCastilloPrz** [comment]
Got a similar problem but for tests not a main function. You don't seem to be able to use the IDE to run it at all, it ignores you when clicking on play icon.
