### ISSUE TITLE
How can I update memory setting for "Gradle Test Executor"

### ISSUE THREAD

**Issue by tshasc** [gradle/gradle#9329]
I can see that by default, its memory setting is "Xmx:2048m MaxHeapSize=512m"
How can I update it if I feel it is not enough?

**Comment by big-guy** [comment]
I don't believe that's the default, but you can set the max heap size or JVM arguments with the `Test` task: https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:maxHeapSize
