### ISSUE TITLE
Flavor dimensions aren't resolved for downstream dependencies

### ISSUE THREAD

**Issue by DSteve595** [gradle/gradle#9330]
Using the Android Gradle Plugin.

I've run into an issue regarding dependency management that seems like it'll make it hard to scale things up in a project with one or more modules that use flavor dimensions.
Below is the bug report I initially filed with Android, though I've since learned the behavior I'm seeing isn't strictly tied to AGP, but relates to how Gradle resolves transitive dependencies.

>I have a library module `libA`, another library module `libB`, and an app module `app`.
`libA` depends on `libB`. app depends on `libA`.
`libB` has a flavor dimension `myDimen`.
`libA` and `app` do not have flavor dimensions.
When I include `libB` as a dependency in `libA`, it makes sense that i have to supply a `missingDimensionStrategy` for `myDimen`. After doing that, `libA` builds fine, but `app` has an issue. It can’t resolve which variant to use, even though it only has `libA` as a dependency, and `libA` includes `libB` as an `implementation` dependency. I have to add the same `missingDimensionStrategy` to `app` in order for it to build.
Shouldn’t this dimension issue be taken care of by `libA`, so that `app` doesn’t have to know about `libB`’s dimensions?

I've attached a project demonstrating the issue.
[FlavorDimensionsIssue.zip](https://github.com/gradle/gradle/files/3133827/FlavorDimensionsIssue.zip)

From what I've gathered, this is actually working as intended. But this definitely presents an issue for projects that want to use flavor dimensions.
I'm not intimately familiar with how Gradle's dependency resolution works, but I think a potential solution would be to allow library modules to specify "default" flavors for their dimensions, which could then be used by consumers, or overridden via the existing `missingDimensionStrategy` option.

**Comment by d4rken** [comment]
I don't think this is stale.

**Comment by kalayda** [comment]
Still actual. Please don't ignore.

**Comment by ov7a** [comment]
Sorry for the late reply.

Given the age of the issue, we would not invest time into ressurecting it. If you stumble across a similar problem, please open a new issue with a fresh reproducer project attached.
