### ISSUE TITLE
Add public API to get information about if caching enabled for the task

### ISSUE THREAD

**Issue by lukaville** [gradle/gradle#9333]
### Expected Behavior
It would be great to have an API to get information about is caching enabled for the task and if not we should be able to get the reasons why it's not cacheable.

### Current Behavior
Currently, we don't have such a public API. There are only some internal classes that are used by build scan plugin.

### Context
We used this internal API to get information about is task output cacheable: from `TaskExecutionListener` we receive `TaskExecution` object and then we access output caching state using `(TaskExecution.state as TaskStateInternal).taskOutputCaching.isEnabled` but now this API is removed.

We need this API to report build cache miss metric to our internal analytics system.

**Comment by eugene-krivobokov** [comment]
In the last versions of Gradle there is no `(TaskExecution.state as TaskStateInternal).taskOutputCaching`. We also can't find any info about cacheability of tasks for our internal analytics system.

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.
***

This is somewhat in line with [ADR-0011](https://github.com/gradle/gradle/blob/master/architecture/standards/0011-api-observability.md). We may also need to revisit/introduce some of the functionality as part of implementing CC-compatible version of `afterTask`.
