### ISSUE TITLE
Moving a project causes Java incremental compilation to fail

### ISSUE THREAD

**Issue by patkovskyi** [gradle/gradle#9337]
Java incremental compilation feature is not portable, meaning: it does not work when you move your project together with buildDir (aka "build/" folder). Gradle remembers absolute buildDir location of the last successful build and looks for .class files there, fails to find them, triggers full recompilation. 

The same happens for all UP-TO-DATE checks (they all fail when you move the project). But this can be mitigated to some degree by using "--build-cache" (UP-TO-DATE checks will fail but cacheable tasks will be restored FROM-CACHE). However, incremental Java compilation will fail (triggering full recompilation) regardless of "--build-cache" flag.

### Expected Behavior
Gradle should look for .class files for incremental Java compilation in the current buildDir.

### Current Behavior
Gradle looks for .class files for incremental Java compilation in the buildDir used for the last successful build. This path is stored as an absolute path somewhere in $GRADLE_USER_HOME.

### Context
I'm trying to make incremental builds work in CI environment. To achieve that, I cache $GRADLE_USER_HOME and buildDir ("build/") directories between CI runners using distributed cache (they download and unpack cache before the build, build, then pack and upload cache). With current Gradle behavior, incremental Java compilation works only if a subsequent build happens on the same runner.

### Steps to Reproduce
1. `git clone git@github.com:patkovskyi/gradlehello.git && cd gradlehello`
2. `./gradlew compileJava --build-cache`
3. modify Main.java in some way (e.g. edit comment)
4. `./gradlew compileJava --build-cache --info` (notice "Incremental compilation of 1 classes")
5. `cd .. && mv gradlehello hellogradle && cd hellogradle`
6. modify Main.java again
7. `./gradlew compileJava --build-cache --info` (notice "Output property 'destinationDir' file <path to gradlehello/build> has been removed" and "Full recompilation is required because no incremental change information is available.")

The results are the same if you remove `--build-cache` flags, but I decided to add them to show that using build-cache does not help.

### Your Environment
Gradle version 5.4.1
https://github.com/patkovskyi/gradlehello
Result of step 7 with added --scan flag: https://scans.gradle.com/s/j4icd4ls5xv2s

**Comment by DevSrSouza** [comment]
I could reproduce it on Gradle 7
