### ISSUE TITLE
gradle asciidoctor plugin not rendering inline macro extension

### ISSUE THREAD

**Issue by efeig** [gradle/gradle#934]
### Expected Behavior
I use the extensions configuration method of the asciidoctor gradle plugin to add an inline macro, that transforms the following markup 'issue:PRJ-100[]' into a link that points to the web page for issue PRJ-100 (see build file below). Until gradle version 2.14 the result was as expected: In the generated html file all occurences were replaced by a proper link. 

### Current Behavior
In gradle version 3.1 and 3.2.1 the inline macro is not rendered correctly any more. After switching to a new gradle version the link is created correctly only once. In following builds the pattern ' issue:PRJ-100[]' is not transformed into a link any more. I realized that the problem only occurs when I include the line
```
     classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11'
```
without generating a pdf file (i.e. using pdf as backend). Leaving the line as it is and using pdf as backend or commenting the line out leads to the expected result.

### Context
In principle it makes no sense to include
```
     classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11'
```
wihtout generating pdf files from AsciiDoc files. However, should this line affect the correct rendering of inline macros in html files?

### Steps to Reproduce (for bugs)
My build file looks like that
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11'
    }
}

apply plugin: 'org.asciidoctor.convert'

asciidoctor {
    backends=['html5']
//    backends=['html5', 'pdf']
    extensions {
         inlinemacro(name: "jira") {
            parent, target, attributes ->
              options = [
                "type": ":link",
                "target": "https://my.issue.server/${target}".toString()
            ]
            createInline(parent, "anchor", target, attributes, options).render()
        }
      }    
}
```
Putting a test.adoc file in the default sources dir `src/docs/asciidoc` with following content
```
jira:PRJ-1058[] 
```
and executing the `asciidoctor` task, should reproduce the problem.

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/hb2x6qnjapvfg/infrastructure

**Comment by bmuschko** [comment]
@efeig This is likely an issue with the Asciidoctor Gradle plugin. Would you mind raising the issue there first?

**Comment by efeig** [comment]
sure, done, thank you
https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/203

**Comment by bmuschko** [comment]
Thanks, I am going to close this issue for now. In case it is an issue in Gradle core then we can re-open.
