### ISSUE TITLE
Passing multiple arguments to gradlew

### ISSUE THREAD

**Issue by hanct** [gradle/gradle#9340]
Gradle: v5.3.1

Hi all,

I try passing multiple arguments to the gradle task (called bootRun) via gradlew with the below command where **--data.server=remoteHost:999** and **--spring.main.banner-mode=off** are two different arguments

   **bootRun --args=--data.server=remoteHost:999,--spring.main.banner-mode=off**
 
When my application print out the value of **data.server**, the value print out is **remoteHost:999,--spring.main.banner-mode=off.**

In other word, gradle seems to treat all the text from "remoteHost" onward as the value of data.server.

Placing comma between multiple arguments is something i learn from online research, but seem that it is not working. Is that a bug? but is this the correct syntax to use to pass multiple arguments?

**Comment by oehme** [comment]
You shouldn't put a comma, you should put a space and put quotes around the whole argument.
