### ISSUE TITLE
Disallow write-only task properties

### ISSUE THREAD

**Issue by paplorinc** [gradle/gradle#9341]
E.g.
```
// no field, just setter
public void setMutablePropertyWithoutGetter() {} 
```
(see `ValidateTaskPropertiesIntegrationTest#report setters for property with mutable type #type`)

It should warn about a write-only property, i.e. unpaired get/set.
See: https://github.com/gradle/gradle/pull/9324/files#r280388131

**Comment by lptr** [comment]
I think we want to do this eventually.

**Comment by lptr** [comment]
Another good validation to add for 7.0.

**Comment by lptr** [comment]
I tried to implement this, but it doesn't make much sense in the end. We also have tasks that have setters without getters, and in general there should be nothing wrong with having differently setters for properties if the different names add useful context.
