### ISSUE TITLE
enable Idea plugin to create "new" directory-based  configuration structure rather than file-based  configuration 

### ISSUE THREAD

**Issue by sdwarwick** [gradle/gradle#9345]
The Intellij Idea plugin is used to set parameters and potentially generate configuration files for the intellij IDE.  Right now, it generates older-style files that are in the  project root directory.  

Jetbrains moved to a newer style where configuration was in a .idea directory with xml files.   A preferred approach would be for the idea plugin to support the generation of these files instead of the older approach.

**Comment by oehme** [comment]
Please use Idea's importer and don't run `gradle idea`. The importer is better in every way.

**Comment by sdwarwick** [comment]
sounds like it should be depreciated then?   it shows up as a first class feature of the idea plugin
