### ISSUE TITLE
Feature: Allow setting Gradle log level to WARNING via CLI

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#935]
As requested on [the forums](https://discuss.gradle.org/t/cant-pick-warning-log-level-and-higher-from-the-command-line/18574):

> The gradle docs on log levels list all the various log levels and the section right below it shows how to make gradle output messages with a certain log level and higher. But there's no way to specify WARNING and higher.
>
>There should be a way to specify WARNING and above, making gradle only output actionable output.

### Expected Behavior
CLI option allows WARNING, QUIET, and ERROR logs output.

### Current Behavior
`-q` will output ERROR and QUIET, but will drop WARNING.
default will output ERROR, QUIET, WARNING and LIFECYCLE level, which users may find too noisy.

### Context
Multiple people have requested this, so it's likely to help a non-trivial number of users.

This seems like it should be straightforward to implement in `LoggingCommandLineConverter`

**Comment by Valloric** [comment]
I'm the original reporter on the gradle forum. I'd _love_ to see this feature implemented!

**Comment by Valloric** [comment]
Talking to folks, there seems to be _another_ bug contributing to this: gradle doesn't redirect stdout and stderr for sub-processes it starts. So even when I pass `-q` to gradle, I get info output from sub-processes.

Gradle should collect stdout and put it on LIFECYCLE and collect stderr and put it on ERROR.

**Comment by Valloric** [comment]
To summarize what I'm asking for:

1. Redirect sub-process output to gradle loggers. `stdout` should go to `LIFECYCLE`, `stderr` should go to `ERROR` (or possibly `WARNING`)
2. Add a flag similar to `-q` **but** that includes WARNING log level; let's call it `--foobar` for the sake of discussion.

These two changes together should result in `gradle build --foobar` only showing errors and warnings and not any informational output.

**Comment by eriwen** [comment]
@Valloric Could you please file a separate issue for sub-process logging with full context and examples?

**Comment by deep00maj** [comment]
Is it available in 3.3 or earlier?

**Comment by lacasseio** [comment]
Code review done and merged in master.
