### ISSUE TITLE
Randomly, Gradles clang system header detection breaks

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#9359]
It seems like gradle's system header detection is not correct. Every few months, our gradle builds break, and I was finally able to trace it down to gradles system header includes. It usually happens after xcode updates. What happens is that it picks headers that can't compile with the stock arguments. It's difficult to reproduce, as it doesn't happen every update, and every time it does we reinstall our build servers. But, it is now continously happening on azures systems, which gave me a chance to do more debugging.

Here is my build. Nothing special at all, just a stock objective c project
https://github.com/ThadHouse/XCodeAzureTest

Here is the gradle --debug --info log and a copy of what options.txt is.
[gradlemac.zip](https://github.com/gradle/gradle/files/3148809/gradlemac.zip)

**Comment by lacasseio** [comment]
Closing this issue in favour of https://github.com/gradle/gradle-native/issues/1014.
