### ISSUE TITLE
test suites are ignored in doLast, but works in doFirst

### ISSUE THREAD

**Issue by sidrom** [gradle/gradle#936]
I have a task called "test", using TestNG and have 'suites' in doLast.
I use this code:

```
test {
    print '\ntest'

    doLast {
        useTestNG() {
            print '\nhohoho\n'
            suites 'src/test/java/test.xml'
            print '\nhahaha\n'
        }
    }
}
```
and console output looks like:
```
$ gradle test


Configuring > 0/1 projects > root project > Resolving dependencies 'classpath'
 test
:compileJava
:processResources
:classes
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test

hohoho


hahaha

BUILD SUCCESSFUL

Total time: 10.813 secs
```
and no info about suites, no browser.

**Expected Behavior**
As the result I want to see this test suite running in browser using Selenium. Suites should be run. Info should be present in console output

**Current Behavior**
No browser, no tests. Suite is ignored. No info in console output

**Context**
If I use code without 'doLast' or change 'doLast' on 'doFirst' - works as expected
```
test {
    print '\ntest'

    doFirst {
        useTestNG() {
            print '\nhohoho\n'
            suites 'src/test/java/test.xml'
            print '\nhahaha\n'
        }
    }
}
```

I wrote a message here, but no answer
https://discuss.gradle.org/t/is-it-possible-to-run-test-suite-in-dolast/20612

**Comment by lptr** [comment]
Hi @sidrom, I answered in detail on your forum post. **tl;dr:** using `doFirst()` and `doLast()` to change task configuration causes problems with up-to-date checks, and should not be used. Using `doLast()` currently has no effect as it is executed _after_ the main task action (in this case test execution). In later Gradle versions we'll warn and even later forbid using this pattern.
