### ISSUE TITLE
Gradle tooling API freezes if checksum verification fails

### ISSUE THREAD

**Issue by chyingo** [gradle/gradle#9361]
### Expected Behavior
Gradle should throw RuntimeException indicating "Verification of Gradle distribution failed".

### Current Behavior
The tooling API never return. Had to manually kill the process to continue. 

### Context
Sometimes user forgets to update the checksum value after changing the versions of Gradle distribution. Tooling API should fail gracefully in that case.

### Steps to Reproduce 
Add this line to gradle-wrapper.properties,
"distributionsha256sum=[Some Invalid SHA]"
Query any builder model using ModelBuilder#get(), and notice it hangs.

**Comment by Yky** [comment]
Any updates on this issue? Android Studio 3.5 now requires removing the distributionsha256sum in order to sync successfully and throws an error otherwise.

**Comment by mpp-doric** [comment]
Interested to hear more about what the thought process behind forcing removal of the checksum here. The useful fix would seem to be throwing a descriptive error when the checksum is invalid. How can we ensure integrity of the wrapper without this checksum?

**Comment by carstenhag** [comment]
https://gitlab.com/fdroid/rfp/issues/1098

On f-droid, there is a bot checking for this value to be present. If not, it shows that a security vulnerability is missing. But now Gradle does not want me to include this property. What do I do now?

**Comment by eighthave** [comment]
@carstenhag if you get the hash value right, then it should work.  See the gradle.org checksums page and instructions that it links to: https://gradle.org/release-checksums/

**Comment by carstenhag** [comment]
@eighthave Hey, Android Studio/Gradle completely refuse to build when `distributionsha256sum` is set for me. I thought I had the right hash, but I have to verify that at home.

**Comment by mpp-doric** [comment]
@carstenhag relevant https://issuetracker.google.com/issues/129261435#comment6

**Comment by chyingo** [comment]
> Any updates on this issue? Android Studio 3.5 now requires removing the distributionsha256sum in order to sync successfully and throws an error otherwise.

Studio 3.5.1 and Studio 3.6 will allow distributionsha256sum, after an extra screening to ensure that you're aware of possible crash if the checksum values don't match.

**Comment by carstenhag** [comment]
Thanks @chyingo. That works :)

**Comment by inazaruk** [comment]
>Studio 3.5.1 and Studio 3.6 will allow distributionsha256sum, after an extra screening to ensure that you're aware of possible crash if the checksum values don't match.

I assume the above statement is referring to the warning that Android Studio is now showing.

![Screen Shot 2020-02-25 at 3](https://user-images.githubusercontent.com/813213/75395350-11d25080-58a7-11ea-9c28-cdf7d9315e92.png)

This warning is pretty confusing to developers when they see it for the first time. 

It would be great to either implement proper Android Studio support for distributionsha256sum instead of showing the warning (not sure if this is possible). Or at least provide a way to opt-out of the warning through some config file. Like an option in gradle-wrapper.properties so that it could be shared with all developers in the repo and avoid these warnings.

**Comment by big-guy** [comment]
The underlying problem is actually fixed in 6.3, but the IDEs need to integrate the 6.3 tooling API client library once it's released.

**Comment by ebrahemabdeen** [comment]
![بدون عنوان](https://user-images.githubusercontent.com/76885459/103466719-fbf7ac80-4d4f-11eb-9175-9a679d7fff05.png)

**Comment by ebrahemabdeen** [comment]
how do i fix this error

**Comment by ebrahemabdeen** [comment]
![بدون عنوان](https://user-images.githubusercontent.com/76885459/103480302-3b6bda80-4ddc-11eb-9ac0-e07668508094.png)

**Comment by assemmahgoob** [comment]
thanks body for this fixed
[whatsapp gold](https://www.abu3rab.com)

**Comment by nzdeveloper009** [comment]
> ![بدون عنوان](https://user-images.githubusercontent.com/76885459/103466719-fbf7ac80-4d4f-11eb-9175-9a679d7fff05.png)
> how do i fix this error ?

same error any body who resolve it?

**Comment by assemmahgoob** [comment]
[واتساب الذهبي](https://watsabplusgold.com/whatsapp-gold-apk) WhatsApp Gold

**Comment by assemmahgoob** [comment]
تحميل وتنزيل [واتساب الازرق](https://whatsplus.teiel.com/2020/01/whatsapp-plus-v825.html) تحديث جديد 2021 ضد الحظر WhatsApp Plus v9.10

**Comment by assemmahgoob** [comment]
صُممت لعبة [PUBG MOBILE](https://xapkpure.app/pubg-mobile) ببجي موبايل PLAYERUNKNOWN’S BATTLEGROUNDS الرسمية حصريًا لأجهزة الموبايل. بالتالي يمكنك اللعب مجانًا في أي مكان وزمان. وتُقدم PUBG MOBILE أكثر الألعاب متعددة اللاعبين حدة مجانًا على الموبايل. ادخل بالمظلة وتجّهز للمنافسة والتحميل من موقع [XapkPure](https://xapkpure.app/)

**Comment by whatsomar** [comment]
**[تحميل واتساب عمر](https://savetovideo.com/)** تم تحديث برنامج ob whatsapp الإصدار V30 لواتساب عمر وتعد نسخة حديثة ويمكن تنزيل واتساب عمر الأصلي من متجر Google Play ويشتمل برنامج ob4whatsapp.

تنزيل **[واتس اب عمر](https://savetovideo.com/%d9%88%d8%a7%d8%aa%d8%b3-%d8%b9%d9%85%d8%b1)**

**Comment by alexbudarov** [comment]
related IntelliJ IDEA ticket:
https://youtrack.jetbrains.com/issue/IDEA-266355

**Comment by whatsomarr** [comment]
تحميل وتنزيل **[واتساب عمر العنابي](https://www.whatsomar.app/2020/10/obwhatsapp.html)** تحديث جديد 2021 ضد الحظر WhatsApp Plus v33

**Comment by whatsomarr** [comment]
تنزيل وتحميل **[واتساب عمر الازرق](https://www.whatsomar.app/2020/10/ob3whatsapp-apk.html)** اخر إصدار وضد الحظر

**[واتساب عمر](https://www.apkplus.app/)**

**[واتساب عمر العنابي](https://www.ahlamcom.com/android/واتساب-عمر-العنابي/)**

**Comment by aoxrb** [comment]
اقترح عليك تنزيل [كيبورد ابراهيم](https://www.al3bqri.com/2021/09/keyboard-ebrahim.html) وكذلك [بريستات لايت روم](https://www.al3bqri.com/2021/07/new-presets-lightroom.html) من موقع [العبقري](https://www.al3bqri.com)

**Comment by codewith-fun** [comment]
It is not fully supported to define distributionSha256Sum in gradle\wrapper\gradle-wrapper.properties.
Using an incorrect value may freeze or crash Android Studio.
Please manually verify or remove this property from all of included projects if applicable.
For more details, see https://github.com/gradle/gradle/issues/9361.
Use "cd5c2958a..." as checksum for https://services.gradle.org/distributions/gradle-7.4-all.zip and sync project
Remove distributionSha256Sum and sync project
Open Gradle wrapper properties

**Comment by suqapp4** [comment]
<a href="https://www.suqapp.com/2021/11/fake-numbers-app.html">افضل برنامج ارقام وهمية</a> 
<a href="https://www.suqapp.com/2022/03/yemen-numbers-detector.html">تحميل كاشف الارقام اليمنية</a>
<a href="https://www.suqapp.com">سوق تحميل تطبيقات</a>
<a href="https://www.alnajm-tech.com/2021/01/El%20Prince-Keyboard-Fahudi.html">كيبورد البرنس فهودي</a>
<a href="https://www.apps-star.com/2021/10/whatsapp-ios.html">واتساب ايفون للاندرويد</a>
<a href="https://www.apps-star.com/2021/08/old-whatsapp.html">واتساب القديم</a>

**Comment by alnajmalyamani** [comment]
هذا <a href="https://www.apps-star.com/2021/10/whatsapp-ios.html">واتساب ايفون للاندرويد</a> شكراً لك

**Comment by kbmods** [comment]
<p dir="auto">تحميل وتنزيل <strong><a href="https://kbmods.blogspot.com/p/whatsapp-alkaser-3copys.html" rel="nofollow">واتساب الكاسر الازرق</a></strong> تحديث جديد 2023 ضد الحظر KBWhatsApp v21</p>

**Comment by kbmods** [comment]
<p dir="auto">تنزيل وتحميل <strong><a href="https://kbmods.blogspot.com/p/kb-wahtsapp-adsbygoogle-window.html" rel="nofollow">KBWhatsApp</a></strong> اخر إصدار وضد الحظر</p>
<p dir="auto"><strong><a href="https://kbmods.blogspot.com/2019/12/kbwhatsapp.html" rel="nofollow">واتس الكاسر الازرق</a></strong></p>
<p dir="auto"><strong><a href="https://kbmods.blogspot.com/2019/12/kb2whatsapp.html" rel="nofollow">واتساب الكاسر الاسود</a></strong></p>
<p dir="auto"><strong><a href="https://kbmods.blogspot.com/2019/12/kb3whatsapp.html" rel="nofollow">واتساب الكاسر الاحمر</a></strong></p>

**Comment by kbmods** [comment]
<p dir="auto">تحميل وتحديث <strong><a href="https://www.abu3rabwhats.com/2021/05/kbwhatsapp.html" rel="nofollow">واتساب الكاسر</a></strong> أخر إصدار ضد الحظر</p>
<p dir="auto">تحميل وتنزيل <strong><a href="https://kbmods.blogspot.com/2019/12/whatsapp-alkaser-plus-2020.html" rel="nofollow">واتساب الكاسر الذهبي</a></strong> اخر إصدار الجديد</p>
<p dir="auto"><strong><a href="https://www.kimods.co/2020/02/whatsapp-alkaser2020.html" rel="nofollow">الواتس الكاسر</a></strong></p>
<p dir="auto"><strong><a href="https://www.abu3rabwhats.com/2021/06/kbwhatsapp.html" rel="nofollow">واتس الكاسر</a></strong></p>
