### ISSUE TITLE
Code not covered for mockito test cases even though code is executed, JaCoCo

### ISSUE THREAD

**Issue by bvishweshwar** [gradle/gradle#9365]
### Steps to reproduce
gradle build - used to build

Attached is build.gradle file.
[build.txt](https://github.com/gradle/gradle/files/3156775/build.txt)
build.txt

### Tools
Codebase: groovy
JaCoCo version: 0.8.1.201803210924
Operating system: Windows
Tool integration: gradle 4.7

### Expected behaviour
Test cases written in mockito should cover code.

### Actual behaviour
Code is not covered for test cases written in mockito.

**Comment by bmuskalla** [comment]
Thanks for the report. If you still see this issue in a recent version of Gradle/Mockito, please reopen this with a small reproduced. Thanks!
