### ISSUE TITLE
Why the number of "Gradle Test Executor" is much more testTask.maxParallelForks

### ISSUE THREAD

**Issue by tshasc** [gradle/gradle#9368]
I defined below in gradle file.
but when I use "ps ax | grep Gradle" the number of "Gradle Test Executor" is much more that
the env variable what I set for MAX_PARALLEL_FORKS. why?

BTW, looks like by default, gradle should just use N/2+1 CPU for parallel thread
But the number of "Gradle Test Executor" is bigger than N/2+1
and most of the time, I can see almost all N CPU are 100% used when running gradle tests
why?
when will gradle launch a new "Gradle Test Executor"? 
when will a "Gradle Test Executor" exit?

if (System.getenv('MAX_PARALLEL_FORKS')) {
            testTask.maxParallelForks = System.getenv('MAX_PARALLEL_FORKS').toInteger()
        } else {
            testTask.maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1

**Comment by tshasc** [comment]
when will gradle launch a new "Gradle Test Executor"?

**Comment by big-guy** [comment]
Do you know which version of Gradle you're using?

If you're running more than one Gradle build at a time, Gradle can start up to maxParallelForks per build.

If you're only running a single build, I would only expect maxParallelForks.  If you can provide an example build that shows more than maxParallelForks running at once, we'll be happy to take a look.

**Comment by tshasc** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

just run 

./gradlew -Dorg.gradle.jvmargs="-XX:MaxHeapSize=16g -Xmx16g -Dfile.encoding=UTF-8" -Dfile.encoding=UTF-8 -Dorg.gradle.parallel=true -Dorg.gradle.configureondemand=false --no-daemon --stacktrace
