### ISSUE TITLE
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

### ISSUE THREAD

**Issue by sindhujabd** [gradle/gradle#9371]
Gradle daemon is getting disappeared for random builds, not for all.
 Expected Behavior
Gradle build should get completed without any daemon crash issues

### Current Behaviour 
The message received from the daemon indicates that the daemon has disappeared.
12:45:25 Build request sent: Build{id=ae0f76e9-1246-4b40-9b79-319b3331ef97, currentDir=/var/lib/jenkins/workspace/gradle_build}
12:45:25 Attempting to read last messages from the daemon log...
12:45:25 Daemon pid: 16423
12:45:25   log file: /var/lib/jenkins/.gradle/daemon/4.10.1/daemon-16423.out.log
12:45:25 ----- Last  20 lines from daemon log file - daemon-16423.out.log -----
12:45:25 12:44:51.272 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 135: Received non-IO message from client: Build{id=ae0f76e9-1246-4b40-9b79-319b3331ef97, currentDir=/var/lib/jenkins/workspace/gradle_build}
12:45:25 12:44:51.272 [INFO] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received command: Build{id=ae0f76e9-1246-4b40-9b79-319b3331ef97, currentDir=/var/lib/jenkins/workspace/gradle_build}.
12:45:25 12:44:51.272 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Starting executing command: Build{id=ae0f76e9-1246-4b40-9b79-319b3331ef97, currentDir=/var/lib/jenkins/workspace/gradle_build} with connection: socket connection from /0:0:0:0:0:0:0:1:40106 to /0:0:0:0:0:0:0:1:35178.
12:45:25 12:44:51.273 [ERROR] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=ae0f76e9-1246-4b40-9b79-319b3331ef97, currentDir=/var/lib/jenkins/workspace/gradle_build}, connection = DefaultDaemonConnection: socket connection from /0:0:0:0:0:0:0:1:40106 to /0:0:0:0:0:0:0:1:35178] after 0.0 minutes of idle
12:45:25 12:44:51.273 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Marking the daemon as busy, address: [2200ca13-f674-4128-a545-659eeac6683f port:40106, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]]
12:45:25 12:44:51.273 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [2200ca13-f674-4128-a545-659eeac6683f port:40106, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]]
12:45:25 12:44:51.273 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
12:45:25 12:44:51.273 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
12:45:25 12:44:51.274 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
12:45:25 12:44:51.274 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
12:45:25 12:44:51.274 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
12:45:25 12:44:51.274 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=ae0f76e9-1246-4b40-9b79-319b3331ef97, currentDir=/var/lib/jenkins/workspace/gradle_build}. Dispatching build started information...
12:45:25 12:44:51.274 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 17: dispatching class org.gradle.launcher.daemon.protocol.BuildStarted
12:45:25 12:44:51.275 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: {PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin, INC_BUILD_PROPERTIES=/data/incremental_build/CI-CDScriptCloning_Incremental/inc_build.properties, XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop, RUN_DISPLAY_URL=https://www.ci-cd.com/job/gradle_build/146/display/redirect, HUDSON_HOME=/var/lib/jenkins, RUN_CHANGES_DISPLAY_URL=https://www.ci-cd.com/job/gradle_build/146/display/redirect?page=changes, JOB_URL=https://ci-cd.com/job/gradle_build/, HUDSON_COOKIE=fd831548-7051-42bf-b323-f79316031732, ANDROID_HOME=/data/usefull_dir/Sdk, MAIL=/var/mail/jenkins, AOSP=aosp, JENKINS_SERVER_COOKIE=401dcd0c63115d3c, LOGNAME=jenkins, PWD=/var/lib/jenkins/workspace/gradle_build, JENKINS_URL=https://ci-cd.com/, USER=john, SHELL=/bin/bash, BUILD_TAG=jenkins-gradle_build-146, ROOT_BUILD_CAUSE=TIMERTRIGGER, BUILD_CAUSE_TIMERTRIGGER=true, OLDPWD=/var/lib/jenkins/workspace/gradle_build, JENKINS_HOME=/var/lib/jenkins, NODE_NAME=master, BUILD_DISPLAY_NAME=#146,  SHAREDSPACE_SCM_URL=NONE, JOB_DISPLAY_URL=https://www.ci-cd.com/job/gradle_build/display/redirect, GIT_BRANCH=origin/develop, CLEAN_BUILD_PROPERTIES=/data/clean_build/CI-CDScriptCloning_Clean/clean_build.properties, SHLVL=1,  BUILD_ID=146, LANG=en_US.UTF-8, XDG_SESSION_ID=c1, JOB_NAME=gradle_build, BUILD_CAUSE=TIMERTRIGGER, GIT_PREVIOUS_SUCCESSFUL_COMMIT=da182f3efe57d1ffc0e208e2907f685a8c2dc92d, NODE_LABELS=master, HUDSON_URL=https://ci-cd.com/, JFROG_APK=jfrogapk,  WORKSPACE=/var/lib/jenkins/workspace/gradle_build, ROOT_BUILD_CAUSE_TIMERTRIGGER=true, GIT_LOCAL_BRANCH=develop, _=/usr/bin/daemon, GIT_COMMIT=da182f3efe57d1ffc0e208e2907f685a8c2dc92d, EXECUTOR_NUMBER=0, HUDSON_SERVER_COOKIE=401dcd0c63115d3c, JOB_BASE_NAME=gradle_build, USER=jenkins, GEM_PATH=file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/stapler-jruby-1.209.jar!/gem/, BUILD_NUMBER=146, BUILD_URL=https://www.ci-cd.com/job/gradle_build/146/, BUILD_TIMESTAMP=2019-05-09_12:44:0_IST, GIT_URL=https://bitbucket.com/scm/repo_name.git, MAJOR_NUMBER=0, XDG_RUNTIME_DIR=/run/user/112, HOME=/var/lib/jenkins}
12:45:25 12:44:51.276 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
12:45:25 12:44:51.276 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 16423). The daemon log file: /var/lib/jenkins/.gradle/daemon/4.10.1/daemon-16423.out.log
12:45:25 12:44:51.278 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting 3rd build in daemon [uptime: 43.7 secs, performance: 96%]
12:45:25 12:44:51.280 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
12:45:25 12:44:51.280 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=5f1cae86-95e4-412d-98aa-14bd1b717caa,javaHome=/usr/lib/jvm/java-8-openjdk-amd64,daemonRegistryDir=/var/lib/jenkins/.gradle/daemon,pid=16423,idleTimeout=10800000,daemonOpts=-Xmx1536m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
12:45:25 Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
12:45:25 ----- End of the daemon log -----
12:45:25 
12:45:25 
12:45:25 FAILURE: Build failed with an exception.
12:45:25 
12:45:25 * What went wrong:
12:45:25 Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
12:45:25 
12:45:25 * Try:
12:45:25 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
12:45:25 
12:45:25 * Get more help at https://help.gradle.org

### Steps to Reproduce 
./gradlew clean 
./gradlew test 
./gradlew assembleRelease

### Your Environment
Running on JENKINS server
Gradle version: 3.3.2

**Comment by big-guy** [comment]
This can sometimes be caused by the Linux OOM killer which kills "large" processes that consume a lot of memory. 

You might find more information in the daemon logs (/var/lib/jenkins/.gradle/daemon/4.10.1/daemon-16423.out.log) and the system logs.
