### ISSUE TITLE
Unable to run build action when using String name variable for my custom type task

### ISSUE THREAD

**Issue by RotBolt** [gradle/gradle#9372]
### Current Behavior

This is the custom type task. I was trying to accomplish. I just used variable `name`. but it thrown exception
```
class HelloNameTask extends DefaultTask {
    String name

    @TaskAction
    void doAction() {
        println "Hello, $name"
    }
}

task helloName(type: HelloNameTask) {
    name = 'Rohan'
}
```
**Exception**
```
Could not run build action using Gradle installation '/opt/gradle/gradle-5.4.1'.
Build file '/home/thelimitbreaker/GradleStorm/ud867/1.16-Exercise-CreateATaskType/build.gradle' line: 27
A problem occurred evaluating root project '1.16-Exercise-CreateATaskType'.
Could not create task ':helloName'.Java(0)
```
But when i change the variable name to `firstname or something else`. It works fine

### Expected Behavior
There should not be exception merely because of variable name.

### Context

Creating custom type task. I just used variable `name (String type)` And it caused exception

### Steps to Reproduce 

- Create a custom task
- create varaible with name `name of String type`
- run gradle taskname
- see the exception

### Your Environment

Build scan URL: https://gradle.com/s/bjgyzp76c5k4s

**Comment by lacasseio** [comment]
It sounds to me the _name_ variable is considered as a Groovy property which generates a getter and setter. The getter overrides the `DefaultTask` getter `getName()` used to identify the name of the task. Which creates unexpected name change from within the container. In this case, you will have to use something different than `name`. Probably `fullName` or, as you said, `firstname`.

@adammurdoch I feel the `getName()` field should be declared as `final` on types being created by the container to avoid such issue.
