### ISSUE TITLE
dependencies --write-locks behavior in multi-project inconsistent with documentation

### ISSUE THREAD

**Issue by weiminyu** [gradle/gradle#9373]
In a multi-project, when running the command 'gradlew **dependencies** --write-locks' from the root directory, only buildscript-classpath.lockfiles are generated for root and subprojects.

### Expected Behavior
We expect lockfiles be generated for all enabled configurations, like what happens with
'gradlew **build** --write-locks'.

Alternatively, the online documentation for dependency locking at https://docs.gradle.org/current/userguide/dependency_locking.html
should be updated.

**Comment by kreiger** [comment]
This seems to be fixed, the page now says
   
>  Run `gradle dependencies --write-locks`. This will effectively lock all resolvable configurations that have locking enabled. Note that in a multi project setup, `dependencies` only is executed on _one_ project, the root one in this case.

**Comment by jkylekelly** [comment]
Are there any plans to enable --write-locks support for multi-project repositories?  Something that works similarly to `gradle projects` as in it works across all projects?

Or is there a better alternative?  I've written a blog post detailing my strategy but this feels like a horrible way to do something fairly simple: https://www.cramhacks.com/p/gradle-multi-project-lockfiles

**Comment by ellisdc** [comment]
This is how I write locks for all subprojects from the parent project. I create a new task called allDependencies like this:

`allprojects { currProject ->
    task allDependencies {
        dependsOn 'dependencies'
    }
}`

Then this to write locks:

`./gradlew allDependencies --write-locks --init-script=myLockConfigs.gradle`

where myLockConfigs.gradle would have your desired lock configurations [per the gradle docs](https://docs.gradle.org/current/userguide/dependency_locking.html).

**Comment by toddbaert** [comment]
This is strange and inconsistent behavior. Why would "build" update sub projects but "dependencies" not?

**Comment by anessi** [comment]
I also ended up here because wanted to generate a single lockfile for all runtime dependencies of a multi-module project that I can use as input for trivy. Here's the task I came up with: https://github.com/aquasecurity/trivy/discussions/4660#discussioncomment-10447482
Maybe this helps someone else.
