### ISSUE TITLE
Rich console output breaks in IntelliJ terminal on Windows

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9374]
I'm on Windows and am using IntelliJ 2019.1 with Gradle 5.4. If I use the Git Bash, the rich console output works pretty well, but it'll freeze when in the IntelliJ terminal. This is related to #9374.

Project: https://github.com/SUPERCILEX/Robot-Scouter/tree/641cd57e741a900adbeb1a0a948d4e35dd912381
Setup: ./gradlew setup
Run: ./gradlew aRel inside the IntelliJ 2019.1 terminal

It'll take forever and will freeze at some point (the build still works, but the live updating part of the console is frozen).

**Comment by SUPERCILEX** [comment]
Whoops, didn't mean to submit that. Just a sec.

**Comment by lptr** [comment]
I see this as well with latest Gradle nightly on `master` with the `gradle/gradle` build itself:

![gradle  C__Users_Lorant Pinter_Workspace_gradle_gradle  -  _settings gradle kts - IntelliJ IDEA 2019  08  02  14_17_02](https://user-images.githubusercontent.com/495366/62369605-66d7ff00-b530-11e9-9f3c-e50bba562b95.png)

The build progresses, but the console stops updating after some of the `buildSrc` tasks have finished. I'm not even sure if the build would ever finish either

**Comment by SUPERCILEX** [comment]
The build does finish, but you can't monitor its progress. Thanks for finally acknowledging this!!!

**Comment by SUPERCILEX** [comment]
Closing in favor of #5735
