### ISSUE TITLE
Warning about capability when building POM for publishing

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9378]
I build a library project that optionally supports different other libraries depending on what is available at runtime.
I found that Gradle now supports these via registered features.
So I did it like
```kotlin
java {
    val main by sourceSets
    registerFeature("lib1Support") { usingSourceSet(main) }
    registerFeature("lib2Support") { usingSourceSet(main) }
}
dependencies {
    "lib1SupportImplementation"("lib:one:1.0.0")
    "lib2SupportImplementation"("lib:two:2.0.0")
}
```

All seems to work as expected, it compiles and in the generated POM from `generatePomFileForMyPublication`, the dependencies are listed with `optional` set to `true`.

Now the "issue" is, that the `generatePomFileForMyPublication` task generates a warning like:
```
> Task :generatePomFileForMyPublication
Maven publication 'my' contains dependencies that cannot be represented in a published pom file.
  - Declares capability net.kautler:my-project-lib1-support:0.1.0-SNAPSHOT
  - Declares capability net.kautler:my-project-lib2-support:0.1.0-SNAPSHOT
```

Is this expected?
Isn't this actually supported by having the dependencies with `optional` set to `true`?
Or did I miss something essential on this topic?

**Comment by ljacomet** [comment]
The complete idea behind feature variants is also to allow consumers to use them. That relies on `capabilities`, which are generated by default using kebab case from the feature name, or can be set by using `capability(String, String, String)` in `registerFeature`.

When mapping the dependencies to Maven, the warning indicates that the capability aspect will be lost and thus consumption may not be as rich as with the Gradle Module Metadata format.

Now, in this context, and because the dependencies are marked as optional, maybe the warning is superfluous since it is quite clear that there is loss when mapping dependencies to `optional`.

Let me have a look about dropping the warning in that case.

**Comment by ljacomet** [comment]
Had a deeper look, the warning makes sense, especially if you encode exclusivity between feature variants. 

What's not ideal is the header of these warnings: the capability aspect is not about dependencies, but really about the extra artifacts, which only carry information in their classifier for Maven.

**Comment by Vampire** [comment]
Maybe it could at least be degraded to `info` level to not pollute lifecycle logs?

**Comment by dawi** [comment]
I am also getting this warnings in Gradle 5.6 since I started using test-fixtures.

```
Maven publication 'mavenJava' contains dependencies that cannot be represented in a published pom file.
  - Declares capability xxx:xxx-test-fixtures:4.2-SNAPSHOT
Maven publication 'mavenJava' contains dependencies that cannot be represented in a published pom file.
  - Declares capability xxx:yyy-test-fixtures:4.2-SNAPSHOT
Maven publication 'mavenJava' contains dependencies that cannot be represented in a published pom file.
  - Declares capability xxx:zzz-test-fixtures:4.2-SNAPSHOT
```

**Comment by ljacomet** [comment]
@dawi That's strange because publication only looks at dependencies that end up in the `compile` or `runtime` maven scopes. How come your test fixture usage appears there?

**Comment by ljacomet** [comment]
Note that we are considering adding DSL methods to silence these publication warnings.

The current idea would be to silence them per Gradle variant, so that if you expand you project by adding more variants, you are warned if you introduce new potential issues.

**Comment by ljacomet** [comment]
Gradle 6.0 will come with an improved message and a possibility to turn the warnings off.

**Comment by TWiStErRob** [comment]
@ljacomet is there a way to ignore this in a more specific manner? Right now `test-fixtures` is the offender, but what if I add more capabilities that would trigger this?
