### ISSUE TITLE
encoding problem with precompiled kotlin script plugins

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9383]
I just spent hours to find out why my build suddenly throws strange errors. :-(

I'm working on the build for a library and was about to add maven publishing.
All worked well, until I suddenly got this error:
```
> Task :buildSrc:compileKotlin FAILED
e: ...\buildSrc\src\main\kotlin\net\kautler\publishing.gradle.kts: (4, 1): Expression 'publishing' cannot be invoked as a function. The function 'invoke()' is not found
e: ...\buildSrc\src\main\kotlin\net\kautler\publishing.gradle.kts: (4, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
internal val OrgGradlePluginGroup.publishing: PluginDependencySpec defined in gradle.kotlin.dsl.plugins._0f7525d1a3945796e226e609a50f6d81 in file PluginSpecBuilders.kt
public val PluginDependenciesSpec.publishing: PluginDependencySpec defined in org.gradle.kotlin.dsl
```
Which made absolutely no sense to me as I just added some comments.
I thought some cache is corrupt or whatever and tried all from completely cleaning everything including 15 GiB Gradle caches and so on, but the error persisted.

Finally after long trial & error and guessing, I boiled it down to this causing the issue:

```kotlin
package net.kautler

plugins { `maven-publish` }
publishing { }
// Björn
```

It is the `ö` in the comment which produces this strange error.
I tried to save the file as UTF-8, UTF-16, ISO-8859-1, all produced the same error.
The main problem is, I need this `ö` actually in the real code, not only in a comment, so just leaving it out is not an option.

So besides that maybe there could be some more meaningful option shown if possible and it should probably work properly, is there any way to work around this properly?

**Comment by Vampire** [comment]
One workaround, once you discovered you have an encoding problem of course is to use unicode escapes instead of the problematic characters, so e. g. `"Bj\u00f6rn"` instead of `Björn`.

**Comment by eskatos** [comment]
Thanks for the report @Vampire 
Could you please tell us what Gradle version are you using? maybe more details on the host system and locale settings could also help down the road. A build scan would also help.
The thing is I can't reproduce the issue locally. A reproducer build would be great

**Comment by Vampire** [comment]
5.4.1, Windows 10, de_DE.ISO-8859-1

I hopefully soon release this project to the OSS wild, then you can use it as reproducer by simply replacing the unicode escape back to an `ö`.

When kicking off the main build a build scan will not pre produced it seems as the  `buildSrc` `compileKotlin` is failing. I kicked off the `buildScan` build directly.
Buildscan with `ö` failing: https://scans.gradle.com/s/wekme65j2rpqm
Same build with the unicode escape: https://scans.gradle.com/s/q22cnd4tf7kc2

**Comment by Vampire** [comment]
Grml I fell the same trap again.
I now added license headers to the files that of course also contain my name, and boom, all static accessors are unavailable while only the `:buildSrc:compileKotlin` step fails, the `:buildSrc:generatePrecompiledScriptPluginAccessors` step had no visual problem.

**Comment by Vampire** [comment]
I would investigate it if you can't reproduce, but I have no real idea where to look at.

**Comment by Vampire** [comment]
Something between 5.6.4 and 6.0 seems to have fixed this.
Leaving this open in case you want to investigate what caused this or want to add some test, but at least it works properly with Gradle 6 now.

**Comment by Vampire** [comment]
Closing as I guess you don't want to investigate or test further
