### ISSUE TITLE
Kotlin examples 500 and 513 should use an until range

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9384]
The Kotlin examples 500 and 513 in the userguide have the following line:
```kotlin
.let { children -> (0..children.length).map { children.item(it) } }
```
This accidentally works as the next line is `.filterIsInstance<Element>()` which throws away the extra `null` element that is generated.
But if someone uses this as inspiration to do something similar and copies it, it might go wrong like for me when I created an extension function `fun NodeList.asList() = (0..length).map { item(it) }`.

Instead the line should actually read
```kotlin
.let { children -> (0 until children.length).map { children.item(it) } }
```
or for my extension function `fun NodeList.asList() = (0 until length).map { item(it) }`.

Actually you could even use the probably nicer
```kotlin
.run { (0 until length).map(::item) }
```

**Comment by bamboo** [comment]
Hi @Vampire. Thanks for the report. Maybe you would like submitting an accompanying PR to fix it?

**Comment by Vampire** [comment]
Maybe. (#9457)
