### ISSUE TITLE
Cannot set archiveClassifier: Unknown property

### ISSUE THREAD

**Issue by burdoto** [gradle/gradle#9394]
When trying to set the archive classifier from a custom Jar task, I get the following error:
`Could not get unknown property 'archiveClassifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.`
I define the Jar tasks like the following: 
```groovy
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier.set("sources")
}

task javadocJar(type: Jar) {
    //javadoc
    from javadoc.destinationDir
    archiveClassifier.set("javadoc")
}
```

### Expected Behavior
The classifier should be set for each Jar task.

### Current Behavior
When syncing the project, I get the following error:
```
Could not get unknown property 'archiveClassifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.
```

### Context
I am trying to define custom Jar tasks to be used as artifacts in a publication task.
The publication:
```groovy
    publications {
        mavenJava(MavenPublication) {
            artifactId = artifactName
            from components.java

            artifact sourcesJar
            artifact javadocJar

            pom {
// ...
```

### Steps to Reproduce 
The exact gradle setup that is failing can be found  in this commit: 
https://github.com/burdoto/javacord-utilities/tree/c5ea17f67a0aadb662cf3176145cba9e4eb3eb30

### Your Environment
IDE: IntelliJ Ultimate 2019.1.1
Gradle Version: 5.2
Build scan URL: [impossible to obtain, gradle won't sync with the ide]

**Comment by noproxy** [comment]
Are you sure the gradle version is 5.2 ?

This works for Gradle >= 5.1.
```
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier.set("sources")
}
```

This works for all version before Gradle 6.0. But ``setClassifier`` is deprecated since 5.1.
```
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    classifier "sources"
}
```

**Comment by burdoto** [comment]
Yes, I am sure I am using Gradle 5.2;
```groovy
wrapper {
  gradleVersion = '5.2'
  distributionUrl = "https://services.gradle.org/distributions/gradle-$gradleVersion-all.zip"
}
```
![grafik](https://user-images.githubusercontent.com/42473485/57605479-ff309a00-7566-11e9-81c7-3701598f08bf.png)

**Comment by noproxy** [comment]
I think you should view the version  in `gradle/wrapper/gradle-wrapper.properties`.

**Comment by burdoto** [comment]
That is actually set to 4.10.2, and it won't change with the wrapper task. 
```yml
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by noproxy** [comment]
> That is actually set to 4.10.2, and it won't change with the wrapper task.
> 
> ```yaml
> distributionBase=GRADLE_USER_HOME
> distributionPath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> ```

Obviously，you need to upgrade to 5.1 before use 'archiveClassifier'
