### ISSUE TITLE
IntelliJ - Unable to execute test in generated sources (Spring Cloud Contract)

### ISSUE THREAD

**Issue by michalborek** [gradle/gradle#9399]
### Expected Behavior
When using Spring Cloud Contract, tests are being generated and put in build/ dir. When opening generated test and running it, only one test should be run.

### Current Behavior
IntelliJ says "No tasks". Tests are being run only when using full run (./gradlew test)

### Context
Trying to run single test that is generated by Spring Cloud Contract.

### Steps to Reproduce 
Create Spring Cloud Contract contract and run tests. Then select generated test (from build file) and try to run it as single test.

I believe that no tests that are generated in build dir are being executed separately (using IntelliJ single test run). I believe that it is gradle problem since it work properly when downgrading gradle to 5.3.

### Your Environment
MacOS: 10.14.3
Intellij: 2019.1
Gradle 5.4.1
Using gradle wrapper.
Gradle set as default runner for tests.

It works fine for the same configuration but with Gradle 5.3.

**Comment by noproxy** [comment]
Do you check the **Delegate IDE build/run actions to Gradle** option?

It is in **File | Settings | Build, Execution, Deployment |Build Tools |Gradle | Runner**.
![](https://1.bp.blogspot.com/-0QqM4j4vVDI/WDVdxV42aYI/AAAAAAAALsY/MZGnO4TUKjo_ON9Wtrp7nJQYwk-UJ5wWgCLcB/s1600/idea-gradle-delegate.png)
]

**Comment by michalborek** [comment]
Yes, the delegation is set.

**Comment by noproxy** [comment]
Could you attach a sample project to try reproducing?
