### ISSUE TITLE
Incremental Java compile does not clean up annotation processors' custom output directories

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#9401]
### Version

Gradle 5.4.1

### Context

When an annotation processor writes some resources to a custom location, it needs to declare the resource location as an `@Output` to Gradle. One way to do this is by using [`JavaCompile.compileOptions.compilerArgumentProviders`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:compilerArgumentProviders).

Take this example from this [sample project](https://github.com/gradle/gradle/files/3177092/GradleBug.zip):

```
class SchemaLocationArgumentProvider implements CommandLineArgumentProvider {

    @OutputDirectory
    File schemaLocationDir

    SchemaLocationArgumentProvider(File schemaLocationDir) {
        this.schemaLocationDir = schemaLocationDir
    }

    @Override
    Iterable<String> asArguments() {
        ["-AschemaLocation=${schemaLocationDir.path}"]
    }
}

def compileJavaTask = tasks.getByPath("compileJava")
def schemaLocation = new File('schemaLocation')

compileJavaTask.options.compilerArgumentProviders.add(new SchemaLocationArgumentProvider(schemaLocation))
compileJavaTask.doLast {
    // Simulate what an annotation processor could do
    new File(schemaLocation, "schema.txt") << "Sample content"
}
```

### Problem
When we delete all the Java source files, we expect Gradle to delete the resource outputs in addition to the class file outputs, but it currently deletes only the class files. (In the above example, `schemaLocation/schema.txt` will not be deleted.)

**Comment by noproxy** [comment]
`@OutputDirectory` should be used in a Task and on the java getter method. Not work here.

I think you should `javax.annotation.processing.Filer` to write files, because it is hard to track output files created by trick.

**Comment by hungvietnguyen** [comment]
The challenge is that `javax.annotation.processing.Filer` allows writing to only a few predefined locations, whereas some annotation processors like Room want to write to a user-defined location.

The current approach with `compilerArgumentProvider` seems to be the only way for annotation processors to declare output directories to Gradle, unless Gradle provides an alternative/better approach such as the one in https://github.com/gradle/gradle/issues/6440 (which is still pending).

**Comment by oehme** [comment]
Note that even if we fix this for the special case where the last source file is deleted, it would still be wrong for any other incremental case. That's because we wouldn't know which resource is generated by which source file. That's why the documentation says that incremental processors must use the Filer for writing.

**Comment by gavra0** [comment]
If APs that write to these directories declare themselves as `AGGREGATING`, all generated files can be removed, as aggregating processors always run.

I agree that having support for this in the JDK would be the best option, but it will take time (probably 1-2 years) before that happens. Maybe that is something we can pursue in parallel with the short-term solution?

**Comment by oehme** [comment]
Let me see if I understand your suggestions: Gradle would always delete any custom output directories on incremental builds and processors would have to mark themselves as aggregating, so that they can recreate their files regardless of what has changed? That would work as a short term solution, yes.

**Comment by gavra0** [comment]
Yes, that's what I had in mind to address both non-incremental and incremental APs how need additional outputs.
