### ISSUE TITLE
PMD Plugin java.lang.NoSuchMethodError: org.apache.commons.lang3.mutable.MutableInt.getAndIncrement()I

### ISSUE THREAD

**Issue by Omenien** [gradle/gradle#9403]
I am experiencing an issue where the PMD plugin's pmd-java dependency is pulling in a version of `org.apache.commons:commons-lang3` (3.4) which is missing the `org.apache.commons.lang3.mutable.MutableInt.getAndIncrement()I` method.  

### Expected Behavior
pmd-java's dependency on `org.apache.commons:commons-lang3:3.8.1` should result in a version of `org.apache.commons:commons-lang3` which has the required method(s) being on the classpath.

### Current Behavior
pmd-java's dependency on `org.apache.commons:commons-lang3:3.8.1` is satisfied by `org.apache.commons:commons-lang3:3.4` which  is missing the `org.apache.commons.lang3.mutable.MutableInt.getAndIncrement()I` method.

```
pmd - The PMD libraries to be used for this project.
\--- net.sourceforge.pmd:pmd-java:6.14.0
     +--- net.java.dev.javacc:javacc:5.0
     +--- net.sourceforge.pmd:pmd-core:6.14.0
     |    +--- org.antlr:antlr4-runtime:4.7
     |    +--- com.beust:jcommander:1.72
     |    +--- commons-io:commons-io:2.6 -> 2.5
     |    +--- net.java.dev.javacc:javacc:5.0
     |    +--- net.sourceforge.saxon:saxon:9.1.0.8
     |    +--- org.apache.commons:commons-lang3:3.8.1 -> 3.4
     |    +--- org.ow2.asm:asm:7.1
     |    \--- com.google.code.gson:gson:2.8.5
     +--- net.sourceforge.saxon:saxon:9.1.0.8
     +--- org.ow2.asm:asm:7.1
     +--- commons-io:commons-io:2.6 -> 2.5
     \--- org.apache.commons:commons-lang3:3.8.1 -> 3.4
```

### Context
This error started occurring after I attempted to update my PMD `toolVersion` from 5.8.1 to 6.14.0. Any 6.x release I tried exhibited this error. 

### Steps to Reproduce 
I'm not actually sure how to reproduce this. I can't find a single reference to `org.apache.commons:commons-lang3:3.4` anywhere in `$ gradle dependencies`. I've created multiple dummy projects that attempt to draw it out and have not been able to do so. If there's a Gradle command that I could run that would help isolate why the dependency is being satisfied this way I'd be happy to do so.

I'm able to workaround this issue by adding the following block:
```groovy 
afterEvaluate {
    dependencies.add('pmd', "net.sourceforge.pmd:pmd-java:6.14.0")
    dependencies.add('pmd', 'org.apache.commons:commons-lang3:3.8.1')
}
```
which results in the following `pmd` dependency configuration:
```
pmd - The PMD libraries to be used for this project.
+--- net.sourceforge.pmd:pmd-java:6.14.0
|    +--- net.java.dev.javacc:javacc:5.0
|    +--- net.sourceforge.pmd:pmd-core:6.14.0
|    |    +--- org.antlr:antlr4-runtime:4.7
|    |    +--- com.beust:jcommander:1.72
|    |    +--- commons-io:commons-io:2.6 -> 2.5
|    |    +--- net.java.dev.javacc:javacc:5.0
|    |    +--- net.sourceforge.saxon:saxon:9.1.0.8
|    |    +--- org.apache.commons:commons-lang3:3.8.1
|    |    +--- org.ow2.asm:asm:7.1
|    |    \--- com.google.code.gson:gson:2.8.5
|    +--- net.sourceforge.saxon:saxon:9.1.0.8
|    +--- org.ow2.asm:asm:7.1
|    +--- commons-io:commons-io:2.6 -> 2.5
|    \--- org.apache.commons:commons-lang3:3.8.1
\--- org.apache.commons:commons-lang3:3.8.1
```

It's highly possible that I just don't understand Gradle's dependency resolution strategy well enough and this is working as expected.

### Your Environment
Unfortunately, I'm not able to provide much information here. The Gradle version in use is https://services.gradle.org/distributions/gradle-5.4.1-all.zip.

**Comment by big-guy** [comment]
@Omenien 

If you can, you could share a [build scan](https://scans.gradle.com/) with the failing build.

Otherwise, you could try running [`dependencyInsight`](https://docs.gradle.org/current/userguide/inspecting_dependencies.html#example_using_the_dependency_insight_report_for_a_given_dependency).  It would be something like: `gradle dependencyInsight --configuration pmd --dependency commons-lang3`.

**Comment by ljacomet** [comment]
The relevant part in the `pmd` dependencies output is:
`org.apache.commons:commons-lang3:3.8.1 -> 3.4`

This indicates that something is forcing the version of `commons-lang3` to `3.4`.
The command suggested by @big-guy should give you information as to where this can come from.

**Comment by ljacomet** [comment]
Closing as this is most likely not a Gradle bug
