### ISSUE TITLE
Provide ability to exclude some artifacts produced by artifacts transformation

### ISSUE THREAD

**Issue by noproxy** [gradle/gradle#9410]
In some case, we need to exculde just some artifacts generated by artifact transformation.

For example, an android application depends on an android library "com.example:library:1.0".
The resolved artifact is a file  ``library-1.0.aar`` whose format is android archive bundle.

The content of the bundle is:
```
classes.jar
res/
R.txt
public.txt
proguard.txt
annotations.zip
AndroidManifest.xml
```
As we know, android plugin registers `ArtifactTransform` to decompress them from the bundle ( and many other transforms to alter the attributes) and consumes each in different tasks finally.

If some libraries contains one **evil** artifact in the bundle(e.g., the `proguard.txt`), we want to exclude the `proguard.txt` but all the remain artifacts should be kept.

### Expected Behavior

We can exclude just some artifacts produced in ArtifactTransforms.

### Current Behavior

We can only exclude the whole dependency.

### Context

After android gives the android library ability to carry some consumer ProGuard rules, there are always some bad ProGuard rules introduced by some libraries in poor quality. They may keep almost everything to make ProGuard useless or mess up the debug info of source code by `-renamesourcefileattribute`.

Maybe, it's more easy to provide these APIs to exclude some ProGuard rules just in Android Plugin, if the ProGuard rules is the only situation.

**Comment by noproxy** [comment]
We can find out the evils by this task:

```
// print all proguard rules to search the evils
tasks.create("printAllProGuards") {
    doLast {
        configurations["releaseRuntimeClasspath"].incoming.artifactView {
            attributes {
                attribute(Attribute.of("artifactType", String.class), "android-consumer-proguard-rules")
            }
        }.files.files.forEach { file ->
            if (file.exists()) {
                println "------------------------------${file}------------------------------"
                println(file.text)
            }
        }
    }
}
```

But I don't find a way to remove some of them if the library is closed source.

**Comment by lptr** [comment]
> Maybe, it's more easy to provide these APIs to exclude some ProGuard rules just in Android Plugin, if the ProGuard rules is the only situation.

This indeed sounds like something to do on the Android plugin side. We don't plan to introduce generic filtering for transforms, but AGP could easily add some filtering specifically for extraction. Or maybe it could target ProGuard files even more specifically.

If you want to push this, the best step is to open an issue on Android's issue tracker at https://issuetracker.google.com/issues/new?component=192709&template=842921.

**Comment by noproxy** [comment]
Thx，I post it at https://issuetracker.google.com/issues/132755145
