### ISSUE TITLE
Deprecate play plugins

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#9412]
The plugins are superseded by https://gradle.github.io/playframework.

**Comment by bigdaz** [comment]
We should investigate if the migration is feature-complete. In particular, I didn't see support for CoffeeScript in the new plugin, and it's not clear to me if the remaining plugin in Gradle core will continue to work with the new Play support.

**Comment by lptr** [comment]
Does this include retiring our own JavaScript plugins as well?

**Comment by bigdaz** [comment]
I suggest we add separate issues for deprecating and removing the plugins in the `javascript` module. As far as I'm aware we haven't extracted all these into external plugins.

**Comment by big-guy** [comment]
We should deprecate without replacement the Coffeescript plugin.  We intentionally decided _not_ to migrate that to the new Play plugin because it was only created as an example of how to integrate something into the Play plugins/software model.

+1 for treating the javascript plugins separately.
