### ISSUE TITLE
Kotlin DSL IntelliJ script resolution miss configured environment variables

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#9422]
Kotlin DSL IntelliJ script dependencies resolution fail if the build fails to configure depending on the state of an environment variable configured in IntelliJ.

### Expected Behavior

An environment variable configured in IntelliJ for Gradle is available in the build on Kotlin DSL IntelliJ script dependencies resolution.

### Current Behavior

Environment variables configured in IntelliJ for Gradle aren't passed to the build for Kotlin DSL script dependencies resolution.

As a result, If the build fails to configure when a custom environment variable isn't set

![image](https://user-images.githubusercontent.com/132773/57705486-4fd9ed00-7664-11e9-8341-a6463d7f4668.png)

### Context

Original report https://youtrack.jetbrains.com/issue/KT-30974

A fix in Kotlin is required before a fix in Gradle can be made.

### Steps to Reproduce 

* create build that fails to configure when a custom environment variable isn't set
* import in IntelliJ
* add the environment variable to the IntelliJ configuration
* open a `.gradle.kts` script
* observe an error message and inability to autocomplete in the editor as shown above

### Your Environment

Gradle 5.4.1
IJ 2019.x with Kotlin 1.3.31

**Comment by NataliaUkhorskaya** [comment]
@eskatos The fix on the IDEA side will be shipped with Kotlin 1.3.40 (name of the environment key is `gradleEnvironmentVariables`)

**Comment by eskatos** [comment]
Fixed in #10351, will ship in 6.0
