### ISSUE TITLE
Move non-core plugins out of Gradle distribution

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#9428]
The Gradle distribution contains some plugins which are not actively developed anymore. For some of them, better replacements are already available in the portal.

In this Epic we track the state of these plugins with the goal to eventually remove them from the distribution in one of the upcoming major releases.

For each of these plugins, there should be:
- A deprecation issues with the probable target milestone attached
- A removal issue with the proper milestone attached

**Comment by big-guy** [comment]
@jjohannes I took a look at the list of plugins in the distribution, I think there may be a couple of other chunks of plugins.

I think we should consider a few more plugins for deprecation in 6.0--basically, all of the other software model based plugins.  @lacasseio and the core team can decide on the native plugins, but we someone else should speak up if we think we shouldn't go ahead and deprecate the JVM software model plugins.

I think we should also come up with some kind of "adoption guide" and advertise a couple of plugins as up for adoption (ANTLR and JaCoCo).  Maybe PMD too.

<summary>
Here are my notes:
<details>

Consider deprecation in 6.0:
- subprojects/language-java/src/main/resources/META-INF/gradle-plugins/org.gradle.java-lang.properties
- subprojects/language-jvm/src/main/resources/META-INF/gradle-plugins/org.gradle.jvm-resources.properties
- subprojects/testing-jvm/src/main/resources/META-INF/gradle-plugins/org.gradle.junit-test-suite.properties
- subprojects/language-scala/src/main/resources/META-INF/gradle-plugins/org.gradle.scala-lang.properties
- subprojects/platform-jvm/src/main/resources/META-INF/gradle-plugins/org.gradle.jvm-component.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.assembler-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.assembler.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.c-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.c.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cpp-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cpp.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-c-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-c.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-cpp-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-cpp.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.windows-resource-script.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.windows-resources.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.binary-base.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.component-base.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.component-model-base.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.language-base.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.clang-compiler.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.gcc-compiler.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.microsoft-visual-cpp-compiler.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.native-component-model.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.native-component.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.standard-tool-chains.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cunit-test-suite.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cunit.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.google-test-test-suite.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.google-test.properties

Adoption:
- subprojects/antlr/src/main/resources/META-INF/gradle-plugins/org.gradle.antlr.properties
- subprojects/jacoco/src/main/resources/META-INF/gradle-plugins/org.gradle.jacoco.properties

Deprecated (in 5.5 or before), will be removed in 6.0:
- subprojects/announce/src/main/resources/META-INF/gradle-plugins/org.gradle.announce.properties
- subprojects/announce/src/main/resources/META-INF/gradle-plugins/org.gradle.build-announcements.properties
- subprojects/build-comparison/src/main/resources/META-INF/gradle-plugins/org.gradle.compare-gradle-builds.properties
- subprojects/code-quality/src/main/resources/META-INF/gradle-plugins/org.gradle.findbugs.properties
- subprojects/code-quality/src/main/resources/META-INF/gradle-plugins/org.gradle.jdepend.properties
- subprojects/ide-play/src/main/resources/META-INF/gradle-plugins/org.gradle.play-ide.properties
- subprojects/osgi/src/main/resources/META-INF/gradle-plugins/org.gradle.osgi.properties
- subprojects/platform-play/src/main/resources/META-INF/gradle-plugins/org.gradle.play-application.properties
- subprojects/platform-play/src/main/resources/META-INF/gradle-plugins/org.gradle.play-coffeescript.properties
- subprojects/platform-play/src/main/resources/META-INF/gradle-plugins/org.gradle.play-javascript.properties
- subprojects/platform-play/src/main/resources/META-INF/gradle-plugins/org.gradle.play.properties

To be deprecated in 6.0:
- subprojects/javascript/src/main/resources/META-INF/gradle-plugins/org.gradle.coffeescript-base.properties
- subprojects/javascript/src/main/resources/META-INF/gradle-plugins/org.gradle.envjs.properties
- subprojects/javascript/src/main/resources/META-INF/gradle-plugins/org.gradle.javascript-base.properties
- subprojects/javascript/src/main/resources/META-INF/gradle-plugins/org.gradle.jshint.properties
- subprojects/javascript/src/main/resources/META-INF/gradle-plugins/org.gradle.rhino.properties
- subprojects/maven/src/main/resources/META-INF/gradle-plugins/org.gradle.maven.properties

Leave as-is:
- subprojects/build-init/src/main/resources/META-INF/gradle-plugins/org.gradle.build-init.properties
- subprojects/build-init/src/main/resources/META-INF/gradle-plugins/org.gradle.wrapper.properties
- subprojects/code-quality/src/main/resources/META-INF/gradle-plugins/org.gradle.checkstyle.properties
- subprojects/code-quality/src/main/resources/META-INF/gradle-plugins/org.gradle.codenarc.properties
- subprojects/code-quality/src/main/resources/META-INF/gradle-plugins/org.gradle.pmd.properties
- subprojects/diagnostics/src/main/resources/META-INF/gradle-plugins/org.gradle.help-tasks.properties
- subprojects/diagnostics/src/main/resources/META-INF/gradle-plugins/org.gradle.project-report.properties
- subprojects/diagnostics/src/main/resources/META-INF/gradle-plugins/org.gradle.project-reports.properties
- subprojects/ide-native/src/main/resources/META-INF/gradle-plugins/org.gradle.visual-studio.properties
- subprojects/ide-native/src/main/resources/META-INF/gradle-plugins/org.gradle.xcode.properties
- subprojects/ide/src/main/resources/META-INF/gradle-plugins/org.gradle.eclipse-wtp.properties
- subprojects/ide/src/main/resources/META-INF/gradle-plugins/org.gradle.eclipse.properties
- subprojects/ide/src/main/resources/META-INF/gradle-plugins/org.gradle.idea.properties
- subprojects/kotlin-dsl-provider-plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.kotlin.kotlin-dsl-project.properties
- subprojects/kotlin-dsl-provider-plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.kotlin.kotlin-dsl-root-project.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cpp-application.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cpp-library.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.swift-application.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.swift-library.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.swiftpm-export.properties
- subprojects/ivy/src/main/resources/META-INF/gradle-plugins/org.gradle.ivy-publish.properties
- subprojects/maven/src/main/resources/META-INF/gradle-plugins/org.gradle.maven-publish.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.lifecycle-base.properties
- subprojects/plugin-development/src/main/resources/META-INF/gradle-plugins/org.gradle.java-gradle-plugin.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.application.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.base.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.distribution.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.groovy-base.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.groovy.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.java-base.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.java-library-distribution.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.java-library.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.java-platform.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.java.properties
- subprojects/plugins/src/main/resources/META-INF/gradle-plugins/org.gradle.war.properties
- subprojects/publish/src/main/resources/META-INF/gradle-plugins/org.gradle.publishing.properties
- subprojects/reporting/src/main/resources/META-INF/gradle-plugins/org.gradle.build-dashboard.properties
- subprojects/reporting/src/main/resources/META-INF/gradle-plugins/org.gradle.reporting-base.properties
- subprojects/scala/src/main/resources/META-INF/gradle-plugins/org.gradle.scala-base.properties
- subprojects/scala/src/main/resources/META-INF/gradle-plugins/org.gradle.scala.properties
- subprojects/signing/src/main/resources/META-INF/gradle-plugins/org.gradle.signing.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cpp-unit-test.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.xctest.properties
- subprojects/ear/src/main/resources/META-INF/gradle-plugins/org.gradle.ear.properties
</details>
</summary>

**Comment by lacasseio** [comment]
All of the native plugins should not be deprecated in 6.0 for the lack of alternative and the new plugins not polished enough.

<summary>
<details>
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.assembler-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.assembler.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.c-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.c.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cpp-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cpp.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-c-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-c.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-cpp-lang.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.objective-cpp.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.windows-resource-script.properties
- subprojects/language-native/src/main/resources/META-INF/gradle-plugins/org.gradle.windows-resources.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.binary-base.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.component-base.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.component-model-base.properties
- subprojects/platform-base/src/main/resources/META-INF/gradle-plugins/org.gradle.language-base.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.clang-compiler.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.gcc-compiler.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.microsoft-visual-cpp-compiler.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.native-component-model.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.native-component.properties
- subprojects/platform-native/src/main/resources/META-INF/gradle-plugins/org.gradle.standard-tool-chains.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cunit-test-suite.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.cunit.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.google-test-test-suite.properties
- subprojects/testing-native/src/main/resources/META-INF/gradle-plugins/org.gradle.google-test.properties
</details>
</summary>

**Comment by jjohannes** [comment]
Thanks @big-guy for assembling this list. I agree that the "language" plugins for the jvm world should be deprecated and created #9837 and #9838.

**Comment by jjohannes** [comment]
> I think we should also come up with some kind of "adoption guide" and advertise a couple of plugins as up for adoption (ANTLR and JaCoCo). Maybe PMD too.

:+1: for this. How do we proceed here?

**Comment by jjohannes** [comment]
I am closing this as it is not used anymore to track work (we still plan to move more plugins out at some point in the future).
