### ISSUE TITLE
Submit worker from worker

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9442]
I'd like to be able to submit a new worker from an already running one. Is this possible?

**Comment by SUPERCILEX** [comment]
@ghale does submitting a worker require the project lock? I feel like it shouldn't since that can't affect anything other tasks are doing. My use case here is that a network request will tell me how much work I have to do. I _could_ do the network request in the task action and then schedule all the workers, but that's a ~10 second thing. Instead, it'd be cool if I could submit a worker which does the network request, then have that worker submit "children" that will each go off and do their thing.

**Comment by ghale** [comment]
You can, but only in `IsolationMode.NONE`.  We'd like to have that available from other isolation modes, too, but for now it's only available with NONE.  To use it in your unit of work, just inject `WorkerExecutor` in the constructor of the `Runnable`:

```
    @Inject
    public MyUnitOfWork(WorkerExecutor workerExecutor, ...) {
        this.workerExecutor = workerExecutor
        ...
    }
```

Then you can submit additional items of work in the same way using the `workerExecutor` object.

**Comment by SUPERCILEX** [comment]
Neat, it worked! What other services are available like that?

**Comment by SUPERCILEX** [comment]
@ghale For example, is there a way to use `project.delete/copy/file/files`. It wouldn't be through the project object of course, but it'd be nice to have access to those read-only abstractions somewhere else.

**Comment by ghale** [comment]
At the moment, `WorkerExecutor` is the only thing you can inject like that, but we're investing some time into this stuff right now and file-based operations are one thing we definitely want to provide.  We haven't finalized a set of services that we want to expose yet, but this stuff will be coming soon.

**Comment by SUPERCILEX** [comment]
Dope, can't wait!
