### ISSUE TITLE
Container filters change behavior depending on the order they're applied

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#9446]
### Expected Behavior

The order of the filtering does not change which tasks are configured.

### Current Behavior

`tasks.matching { /* predicate */ }.withType(SomeType) {}` configures all tasks of the type `SomeType` and not just the tasks that match the predicate.

### Steps to Reproduce 
I would expect that these two methods would configure the same set of tasks:
```
tasks.matching { /* predicate */ }.withType(SomeType) {}

tasks.withType(SomeType).matching { /* predicate */ } {}
```

This changed between 5.0 and 5.4.1.  We should check if this happens with all containers or just task containers.

**Comment by big-guy** [comment]
@lacasseio do you have any clues what might be going on here?

**Comment by lacasseio** [comment]
There seems to be an issue with the TaskContainer/TaskCollection. I created this commit to test this use case: https://github.com/gradle/gradle/commit/26ac15a4ecc4fc9209a24219335654e806591ecb

Some test fails, I will look at them later.
