### ISSUE TITLE
Kotlin DSL Failed to generate type-safe Gradle model accessors for Android plugin

### ISSUE THREAD

**Issue by gildor** [gradle/gradle#9448]
I have precompiled script plugin which applies `com.android.library` plugin:

```
plugins {
    id("com.android.library")
    kotlin("android")
}
```

But static accessors are not available in this precompiled plugin, but work properly in a neighbor plugin which uses only `kotlin("jvm")`.
I see this stack trace from task `:buildSrc:generatePrecompiledScriptPluginAccessors`
https://gist.github.com/gildor/23e0a1e32b2bb92167ef7cdf76884ca7

As you can see, it cannot find path to SDK, but I have sdk.dir in my local.properties file in root of the project, but apparently it tries to find it in some temporary project.

I tried to specify ANDROID_SDK_ROOT environment variable for 
```
ANDROID_SDK_ROOT=path ./gradlew assembleDebug
```

But it also does not help.

### Expected Behavior
type-safe accessors should be generated properly for precompiled plugin

### Current Behavior
Accessors are not generated, I cannot use them in the precompiled plugin (neither `android` extension, or even dependency configurations, like `implementation`), but if I do not use them, build is successful, but I see exception from task `:buildSrc:generatePrecompiledScriptPluginAccessors` in logs

### Your Environment
Gradle 5.4.1
Android Gradle Plugin 3.5.0-beta01

**Comment by gildor** [comment]
Not sure is it still an issue or not, I will check a bit later

**Comment by Tapchicoma** [comment]
I think this issue could be closed.

We are successfully using android plugin generated accessors in precompiled script plugin.
