### ISSUE TITLE
GRADLE-1377 eclipse-wtp plugin should make it easier to replace a facet version

### ISSUE THREAD

**Issue by ajoberstar** [gradle/gradle#945]
### Expected Behavior

The below code should always result in a single `jst.web` facet with the version specified, while maintaining all other facets that were previously added (including the defaults of the wtp plugin, e.g. `jst.java`).

```groovy
apply plugin: 'war'
apply plugin: 'eclipse-wtp'

eclipse.wtp.facet {
  facet name: 'jst.web', version: '3.0'
}
```

### Current Behavior

The above code currently results in the `jst.web` facet being the only one output, the `jst.java` you would normally get by default is dropped.

### Context

The facet should correspond to the servlet spec level you are targeting with your web application. It defaults to `2.4` which is very old, so you always need to update it. The current approach of [EclipseWtpPlugin](https://github.com/gradle/gradle/blob/1b7fe543efe9de4b5326115d729d921f406f2560/subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/EclipseWtpPlugin.java#L281) provides default facets through a convention mapping. This means that as soon as the user wants to customize the facets all of the defaults are removed. This results in contortions to maintain the other facets while customizing the web one:

```groovy
eclipse.wtp.facet.file.whenMerged { f -> f.facets.each { if (it.name == 'jst.web') it.version = 3.0 } }
```

If there was some intention to allow people to opt-out of all default facets, it would still be very easy for them to just blank out the facets before they append theirs: `eclipse.wtp.facet { facets = [] }`.

This fix should apply to all defaults provided by the wtp plugin (there are separate ones for ear, war, and java.

### Steps to Reproduce (for bugs)

Use the code above, run `gradlew cleanEclipse eclipse` and then look in the resulting facet file in the `.settings` directory.

### Your Environment

This is still in current master as of 11/29/2016 (i.e. post 3.2.1).

**Comment by blackfoxoh** [comment]
I would suggest to extend this issue a little bit: not only jst.web but jst.ear as well. Please have a look at https://discuss.gradle.org/t/configure-ear-project-in-eclipse/25755/3

**Comment by mauromol** [comment]
This issue is still valid, working with Eclipse WTP is still a challenge, please reconsider and reopen.

**Comment by mauromol** [comment]
For future reference: this now works as expected (without the need to use the `eclipse.wtp.facet.file.whenMerged` technique) when Buildship uses a Gradle version >= 7.2 to handle your build.

Thank you!
