### ISSUE TITLE
Clarify `PathFingerprintCompareStrategy`'s `includeAdded` parameter

### ISSUE THREAD

**Issue by paplorinc** [gradle/gradle#9459]
During https://github.com/gradle/gradle/pull/9407/files#diff-63a979673a1151b2ff2bab58f4f97857R69 we saw that `includeAdded` doesn't always make sense for every strategy, e.g. for `Normalized` we've hardcoded it to `true`.

We should investigate how to model the two paths in a meaningful way, without confusing boolean parameters that alter the client code's behavior (maybe we're hiding two independent features that should be split instead).

**Comment by lptr** [comment]
`includeAdded == false` is for detecting output changes between builds. Maybe we should do this separately completely, and detect added outputs between builds, and use these changes to detect stale output files.

**Comment by wolfs** [comment]
If we implement https://github.com/gradle/gradle/issues/9034, we can remove the flag completely since we won't use fingerprints for the outputs any more.

**Comment by wolfs** [comment]
Fixed by removing the parameter altogether in https://github.com/gradle/gradle/pull/9860.

**Comment by paplorinc** [comment]
That's the best explanation!
