### ISSUE TITLE
Don't remove libsDir and distDir

### ISSUE THREAD

**Issue by ari** [gradle/gradle#9470]
### Expected Behavior
Retain the functionality of distDir and libsDir for gradle 6.0

### Current Behavior
distsDir and libsDir now return deprecation notices

### Steps to Reproduce 
https://discuss.gradle.org/t/the-distsdir-method-has-been-deprecated-but-were-not-even-using-it/31272

### Reasons

Its appears that project.distsDirName has been retained, but this vastly less useful than a file object in the wordiness of assembling paths, handling different path separators, etc.

If these objects really need to be removed for some technical reason, the deprecation notice needs to suggest useful alternative ways to do the same thing.

**Comment by big-guy** [comment]
@ari could you describe what you're using libsDir and distsDir for?  Why is it important to specify the exact directory for jar/war/zip/etc files vs an implementation detail for where they happen to go?

There were a few things going on here:
- Reducing the surface area of an internal API (convention and convention mapping). These APIs were public, but built on top of non-public things.
- Bridging between the above and new properties (e.g., Property or Provider)
- Reducing the amount of non-useful things that can be twiddled 

We don't want to lose any useful functionality though.

**Comment by ari** [comment]
I had always assumed that a goal for gradle was convention over configuration. Sure we can define our own paths, but distsDir is especially useful since so many things need to write to that output folder.

Will you continue down this path and remove buildDir, srcDir, etc? Sure we'll cope, but its a whole lot more configuration and confusion about the expected best practices way to set up gradle.

**Comment by grandchild** [comment]
A comment in the deprecation notice in the docs about replacing it with `buildDir/distsDirName` would be helpful at least.

@big-guy 
> could you describe what you're using libsDir and distsDir for?

We are using `distsDir` specifically because we have our own mangling of class files and that is our build output (effectively replacing jar creation), and we want that tool to write to the conventional location, so we give distsDir as output base directory.
Well, `"$buildDir/$distsDirName"` works just fine, although it is a bit more verbose.

**Comment by ljacomet** [comment]
Gradle 6.0 introduced `base.distsDirectory` and `base.libsDirectory` through the `base` convention.
In Gradle 7.1 these methods are moved to the `base` extension in a transparent fashion for build script authoring.
