### ISSUE TITLE
Release Candidate does not available

### ISSUE THREAD

**Issue by Jonatha1983** [gradle/gradle#9471]
The release candidate page (https://gradle.org/release-candidate/ ) does not get update until a new release is made and also then it contains the just release version. This happen approximately since gradle ~4.X.

Once it use to contain the real release candidate ( for instance at time of writing one expect to find 5.5) 

Thanks

**Comment by big-guy** [comment]
5.5 doesn't have a RC, so this page should probably say "There isn't a release candidate".  I think that's what we used to do.

We also have some nightly pages:
https://gradle.org/nightly/ (from master)
https://gradle.org/release-nightly/ (from release)

It depends on where we are in our development cycle which of those are most current. 

I raised an issue internally for someone to update the gradle.org site to do that.  Thanks for letting us know.
