### ISSUE TITLE
using a plugins DSL block for subprojects in a precompiled script plugin neither works not errors

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9473]
Out of curiosity I tried whether this construct would work in a precompiled Kotlin script plugin:

```kotlin
subprojects {
    plugins {
        java
    }
}
```

This did not work as expected from a naive build author.
Actually the `java` plugin got applied to the root project instead, the one where the precompiled script plugin was applied.
I think it would make sense to instead fail the build as long as this is not working like the syntax suggests.

**Comment by eskatos** [comment]
Thanks for the report @Vampire
Fixed in https://github.com/gradle/gradle/pull/10947
This will ship in Gradle 6.0
