### ISSUE TITLE
Kotlin DSL plugins block in precompiled script plugins should either support or prevent declaring "apply" for a plugin

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9477]
Related to the version in #9240, you can do `id("my.plugin") apply false` and the `apply` is also silently ignored.
One option would be to error out like requested there for the version, another option I'd prefer would be to allow it.
If you ask what for as the regular dependency already adds the plugin to the classpath, my intended use-case would be to add the static accessors, so something like

```kotlin
plugins {
    id("com.github.rodm.teamcity-environments") apply false
}

subprojects {
    apply(plugin = "com.github.rodm.teamcity-environments")

    teamcity {
        version = "2018.2"
    }
}
```

instead of

```kotlin
subprojects {
    apply(plugin = "com.github.rodm.teamcity-environments")

    configure<TeamCityPluginExtension> {
        version = "2018.2"
    }
}
```

**Comment by eskatos** [comment]
If the plugin isn't applied you wouldn't get the accessors generated. It basically has no effect on a precompiled script given all plugin dependencies must be declared in the project building them. Closing

**Comment by Vampire** [comment]
I see about the accessors not being available if not applied.
But that doesn't make this issue less valid, does it?

There are still two options for this issue:

1. error out if `apply false` is given as it has no effect and is also requested for the version

2. As far as I remember the procedure, Gradle takes the plugins block, applies it to a temporary project and evaluates it to find what accessors to generate for the script.
   Nothing should prevent this logic to ignore the `apply false` so that the accessors can be generated and then in the actual script let the `apply false` be effective like described

**Comment by Vampire** [comment]
I see that maybe option 2 is not good as it is against the type-safety of only having accessors for things Gradle knows is present.

But the behavior is still wrong.
The `apply false` is still simply ignored by 6.7.1.
This means the plugin is actually applied, though it visually says something different.

So I still think the `apply false` should either work and thus being a no-op as @eskatos stated it is but isn't,
or throw a meaningful error like "Don't be stupid you added it in the build script already".

**Comment by eskatos** [comment]
`apply false` in precompiled scripts `plugins {}` block doesn't make sense and should either not compile or throw.

See https://github.com/gradle/gradle/issues/14437
