### ISSUE TITLE
Gradle fails to even start correctly (logging problem)

### ISSUE THREAD

**Issue by mouse07410** [gradle/gradle#9479]
Fresh install of Gradle-5.4.1 via Macports on MacOS 10.14.4, successful. Attempt to test it results in a failure:
```
$ gradle --full-stacktrace -v
[main] INFO org.gradle.internal.nativeintegration.services.NativeServices - Initialized native services in: /Users/ur20980/.gradle/native

FAILURE: Build failed with an exception.

* What went wrong:
org.slf4j.impl.SimpleLogger cannot be cast to org.gradle.api.logging.Logger

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
$ 
```

### Expected Behavior
Something like 
```
$ gradle -v
Gradle 5.4.1 . . . . .
. . . . .
```

### Current Behavior
See above.

### Context
I was trying to build `pdftk-java`, but it doesn't matter. Even `gradle -v` in a directory with no project at all results in this.

### Steps to Reproduce 
1. On MacOS install Oracle JDK. 
2. Install Gradle via `sudo port install gradle`
3. Try `gradle -v` and observe the result.

### Your Environment
MacOS Mojave 10.14.4, Oracle JDK 1.8.0_211, Macports-2.5.4, Gradle 5.4.1. 
Minimal `slf4j` and `log4j` installed in `/Library/Java/Extensions`:
```
$ ll /Library/Java/Extensions/*slf4j*.jar
-rw-r--r--  1 root  wheel  23645 May 20 16:52 /Library/Java/Extensions/log4j-over-slf4j-1.7.25.jar
-rw-r--r--  1 root  wheel  41203 May 20 10:58 /Library/Java/Extensions/slf4j-api-1.7.25.jar
-rw-r--r--  1 root  wheel  15257 May 20 15:53 /Library/Java/Extensions/slf4j-simple-1.7.25.jar
$ ll /Library/Java/Extensions/*log4j*.jar
-rw-r--r--  1 root  wheel  489884 May 20 16:53 /Library/Java/Extensions/log4j-1.2.17.jar
-rw-r--r--  1 root  wheel   23645 May 20 16:52 /Library/Java/Extensions/log4j-over-slf4j-1.7.25.jar
$ 
```
Removing those files did not seem to help.

**Comment by big-guy** [comment]
Hmm, I haven't seen that sort of failure before.

I don't see this with the same macOS version, a slightly older JDK8 and the 5.4.1 install from macports.  I don't have any files in /Library/Java/Extensions.  What else do you have in that directory?

Could you try downloading 5.4.1 from https://gradle.org/install/#manually and running gradle directly from the zip?  This is to rule out something funky with the MacPort install.

If that still fails, I would suggest...
- Try a different version of Java.  Maybe the extensions are interfering with what Gradle would expect.
- Check JAVA_OPTS, GRADLE_OPTS, JAVA_TOOL_OPTIONS for something funky (e.g., extra arguments that may influence the JVM)

**Comment by mouse07410** [comment]
I did not re-install `gradle` manually, but removed all the `slf4j*.jar` files from the classpath `/Library/Java/Extensions` **and** placed there the following files:
```
$ ll /Library/Java/Extensions/log4j*
-rw-r--r--  1 root     wheel  489884 May 20 16:53 /Library/Java/Extensions/log4j-1.2.17.jar
-rw-r--r--  1 ur20980  wheel  143213 May 20 20:52 /Library/Java/Extensions/log4j-api-2.4.1.jar
-rw-r--r--  1 ur20980  wheel  991033 May 20 20:52 /Library/Java/Extensions/log4j-core-2.4.1.jar
-rw-r--r--  1 root     wheel   23645 May 20 16:52 /Library/Java/Extensions/log4j-over-slf4j-1.7.25.jar
-rw-r--r--  1 ur20980  wheel    1196 May 20 20:52 /Library/Java/Extensions/log4j.properties
$ 
```

After that everything became normal:
```
$ gradle -v

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Mac OS X 10.14.4 x86_64

$ 
```

I suspect that `log4j-1.2.17.jar` and `log4j-over-slf4j-1.7.25.jar` are not needed (collaterals ;), but they don't bother me at this time.

**Comment by mouse07410** [comment]
@big-guy you may want to document somewhere that the presence of SLF4J jars anywhere on the class path would prevent Gradle from working - and likewise, the **absence** of LOG4J on the class path would break Gradle.

**Comment by big-guy** [comment]
This is something specific to how things are configured on your machine. None of these steps are necessary nor what we would expect someone to worry about. (e.g., installing jars into /Library/Java/Extensions/)

log4j and SLF4J are both included in Gradle's distribution, so I'm not sure what's happened for you.

**Comment by mrj** [comment]
On Fedora (43) I had a similar error trying to run `gradle` (9.3.1) under Java 25:
```
org.slf4j.impl.Log4jLoggerAdapter cannot be cast to org.gradle.api.logging.Logger
```

Was not fixed by manual installation. But solved by
```
sudo chmod 0 /usr/java/packages/lib/ext/slf4j-*
```

Java > 9 isn't supposed to use this system-wide extension directory.

But turns out I had `JAVA_HOME` set to Java 1.8.
