### ISSUE TITLE
SLF4J StaticMDCBinder implementation

### ISSUE THREAD

**Issue by remal** [gradle/gradle#9491]
Currently Gradle has it's own `org.slf4j.impl.StaticLoggerBinder`, however it doesn't have `org.slf4j.impl.StaticMDCBinder` implemented. So when a plugin/build script uses Slf4j MDC, you get a warning message in console.

Please consider creating this class. I suppose, it can be done just by copying corresponding class from [org.slf4j:slf4j-nop](https://mvnrepository.com/artifact/org.slf4j/slf4j-nop).

### Expected Behavior
Using Slf4j's MDC does nothing and doesn't display a warning message.

### Current Behavior
When I'm trying to use methods of class `org.slf4j.MDC`, I see this message:
```
Failed to load class "org.slf4j.impl.StaticMDCBinder".
Defaulting to no-operation MDCAdapter implementation.
See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
```

**Comment by big-guy** [comment]
Are you using MDC directly in the build script or plugin or is it coming from another dependency?

I don't see a problem with implementing these.  Would you be interested in submitting a PR?

**Comment by remal** [comment]
@big-guy I've created a PR: #9524. Please take a look.

**Comment by remal** [comment]
@big-guy Regarding your question about using MDC. I'm using testcontainers library in buildscript and the library uses MDC. So I'm getting this warning message.
