### ISSUE TITLE
How does gradle manage the cache zip

### ISSUE THREAD

**Issue by ensean** [gradle/gradle#9497]
At present, we store all the gradle versions in `~/.gradle/wrapper/dists` and gradle wrapper is used choose the target version for building. 

As for mine understanding, the zip file will be unzipped and used for building only if it has not been unzipped. But we found that sometimes it tries to delete the unzipped folder and re-do the unzip operation, does it work as design?

```
Deleting directory /home/builder/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4
Unzipping /home/builder/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4-all.zip to /home/builder/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1
```

BTW, this re-unzip operation may sometimes generate incomplete unzipped folder, which may cause the following error:
```
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

Related issues are #8289 and #4032, but they are closed without investigation ...

**Comment by big-guy** [comment]
Is `/home/builder/.gradle/` on a shared filesystem (like NFS) or are there multiple builds running that share that directory at the same time? 

Under the covers we're doing something like:
1. Is the Gradle distribution already unzipped and ready? If yes, use it.
2. If no, does it need to be downloaded? If yes, download it.
3. After downloading, delete the directory the distribution will be extracted to.
4. Verify the distribution zip.
5. Unzip.
6. Mark the distribution as ready.

There's some locking to prevent two processes from stepping on one another, but we would be interested in any problems with that.

**Comment by ensean** [comment]
`/home/builder/.gradle/` is not on a shared filesystem. The machine works as a dedicated building agent for Jenkins2, and only one building job is allowed at any given time.

As for the report case, is there something wrong with the first step? We are pretty sure that the target  distribution is unzipped already.

**Comment by big-guy** [comment]
Hmm.  Is it possible that multiple Gradle builds run concurrently within a job?  e.g., TestKit tests or just Gradle running in the background.

You can find the check/download/unzip logic here:
https://github.com/gradle/gradle/blob/506aa2182392c562c2a0a61e4ad44ccbf8888ff0/subprojects/wrapper/src/main/java/org/gradle/wrapper/Install.java#L48-L88

We hold a lock based on the path to the zip for the distribution. 

Do you use the services.gradle.org URL to download the Gradle distribution?

Is it possible a previous build step (or a periodic clean-up job) is partially deleting the distribution?

**Comment by ensean** [comment]
In order to prevent the unzipped folder being deleted, we have tried to change the permissions of the file. Please note that `builder` is the user that runs the builds
```
drwxr-xr-x 9 root    root        4096 Dec  6  2017 gradle-4.4
-rw-r--r-- 1 root    root           0 Jun  4 11:46 gradle-4.4-all.zip.lck
-rw-r--r-- 1 builder nogroup 98824466 Jun  4 11:46 gradle-4.4-all.zip
-rw-r--r-- 1 root    root           0 Jun  4 12:55 gradle-4.4-all.zip.ok
```

But when the job runs,  it complaints `permission denied` exception. From my point of view, `builder` should have read access to the `lck` file, does the exception means that gradle tries to delete the `lck` file and re-generate it?
```
14:18:29 [pw-android_4.2.0_release_maint] $ /bin/bash /tmp/jenkins3435150902850337062.sh
14:18:29 Exception in thread "main" java.io.FileNotFoundException: /home/builder/.gradle/wrapper/dists/gradle-4.4-all/9br9xq1tocpiv8o6njlyu5op1/gradle-4.4-all.zip.lck (Permission denied)
14:18:29 	at java.io.RandomAccessFile.open0(Native Method)
14:18:29 	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
14:18:29 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
14:18:29 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
14:18:29 	at org.gradle.wrapper.Install.createDist(Install.java:48)
14:18:29 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
14:18:29 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
14:18:29 [ERROR] -- Gradle build failed
```

**Comment by ensean** [comment]
@big-guy Thanks a lot for your help, as for your suggestion, 

Is it possible that multiple Gradle builds run concurrently within a job? 
   > Only one build is running at any given time

Do you use the services.gradle.org URL to download the Gradle distribution?
  > Yes, the services.gradle.org is used. But we have cached all the zip file in the `~/.gradle/wrapper` in order to accelerate the build

Is it possible a previous build step (or a periodic clean-up job) is partially deleting the distribution?
  > Nope, this issue can occurs occasionally for the same job runs on the same agent. For example, the job `awesome-android` build 1,2,3 runs correctly on build agent1, but `awesome-android` build 4 may failed on build agent1.(No other build runs on build agent1 between  `awesome-android` build 3 and #4)

**Comment by ensean** [comment]
It seems that there is some kind of expiration settings for the `lck` file ?

https://github.com/gradle/gradle/blob/506aa2182392c562c2a0a61e4ad44ccbf8888ff0/subprojects/wrapper/src/main/java/org/gradle/wrapper/Install.java#L32

**Comment by ensean** [comment]
@big-guy For a workaround, is it possible to set a parameter to force gradle do the unzip work for every run ?

**Comment by big-guy** [comment]
The lck and ok files need to be writable by the builder user since it uses those to coordinate between processes and mark the distribution as usable.  

Could you run your builds with `--info`? 

When you encounter this failure again, find the Gradle build that ran just before the failing build and look at the end of its log. If you can share that here, that would be appreciated. Gradle can do some cache clean-up at the end of a build, so maybe that's happening and leaving the distribution in a half-way state.

**Comment by ensean** [comment]
@big-guy 

We found that the `gradle-wrapper.jar ` we used is quite old(v2.10) while we are using gradle 4.6 specified in the `gradle-wrapper.properties`, may this be the problem?

As you mentioned, can you explain bit more about the cache clean-up process and it is done by whom?
> Gradle can do some cache clean-up at the end of a build,

**Comment by ensean** [comment]
OK, we found it is caused by one new [feature](https://docs.gradle.org/4.10/release-notes.html#periodic-cache-cleanup) introduced in release 4.10, and the related code is [here](https://github.com/gradle/gradle/blob/40ad77c5cd530a3536ce9fc34c23bd64657746f0/subprojects/core/src/main/java/org/gradle/cache/internal/WrapperDistributionCleanupAction.java#L89)

This feature will delete unused distribution folder in the background, and the related logs can be found in the daemon log

**Comment by timotei** [comment]
@ensean Why close the issue? We get it also on our side with no way to control it, and to me it seems a bug, since the documented feature shouldn't impact the actual running process of the gradle tasks

**Comment by ensean** [comment]
@timotei It's main cause is that starts from gradle 4.10, it will try to delete *expired* cache when the build tasks are all done. But when the gradle build is triggered through Jenkins, the deleting operation may be interrupted by Jenkins since it thinks the *Jenkins* build is accomplished. Maybe the interruption of cache deletion on Jenkins can be taken as a bug? 

Our current workaround is to change the caches access time by a script repeatedly by crontab 😭

**Comment by dfev77** [comment]
Ok, that is a hackish workaround, going against the purpose of cache expiry, but is there a proper solution for the item?
Like gradle supporting the the ability to disable this cleanup and add a standard task for it and allow us to run it on demand through the build infrastructure (that all companies have set up)

**Comment by ensean** [comment]
@dfev77 Maybe you can try [this](https://discuss.gradle.org/t/disable-the-period-cache-cleanup/29365) if all your projects use gradle version above 5.0?
