### ISSUE TITLE
Don't include transforms in percentage calculation

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9498]
Here's a build with a full 5 minutes left to complete that thinks it's 99% done:
![image](https://user-images.githubusercontent.com/9490724/58144092-f3e20c00-7c01-11e9-8299-9eaafe75ffc7.png)

I'm assuming that's because it includes transforms, but those are basically instant and don't give any measure of completeness.

**Comment by wolfs** [comment]
We currently only count and don't respect any duration in the progress bar. There may be fast tasks and slow artifact transforms. As long is we don't take task (or work node) execution time into account, I wouldn't remove the artifact transforms completely.
