### ISSUE TITLE
Add ability to display custom build switches in scan plugin

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9499]
Gradle has a bunch of switches available, as shown in the Switches tab of a build scan. It would be nice if third party plugins could add to this metadata.

Reasoning:
I often find myself wondering what special flags are enabled in the android gradle plugin or the kotlin gradle plugin. It would be super nice to be able to open a build scan and see if `android.useAndroidX`, `android.enableJetifier`, `android.enableR8`, `kotlin.parallel.tasks.in.project`, etc are enabled/disabled. Most importantly, **this would be a way to surface flags with their associated documentation**. Currently, knowing what flags are available is a nightmare.

Obviously, this would require support from Google and JetBrains, but my hope here is to get the conversation started.

**Comment by SUPERCILEX** [comment]
@ghale thoughts on this?

**Comment by ov7a** [comment]
Sorry for the late reply

This issue needs a decision from the Develocity team. They have been informed. Response time may vary.

**Comment by wolfs** [comment]
I would recommend using custom tags and values that you already can add via the Build Scan plugin. We'll keep this issue on our backlog, though it does not have priority now.
