### ISSUE TITLE
Slowness during execution of single Junit test

### ISSUE THREAD

**Issue by xtracoder** [gradle/gradle#950]
On more-or-less large projects (the ones beyond single Main with "Hello world!") there is noticeable latency with execution of Junit test. 

`--profile` says that 80% of time is spent on execution of the `:test`, however actual code under test runs in `less than 1ms`. Looking onto Gradle's self-profile output below - shows that each execution wastes more than 1 second of my life. During development of new staff under TDD (test-driven development) - such tests are executed pretty frequently and aggregated loss of time is rather annoying :( 

    Task                                    Duration    Result
    :dummy-all                              1.850s  (total)
        :dummy-all:test                     1.443s  
        :dummy-all:compileJava              0.257s  UP-TO-DATE
        :dummy-all:compileTestJava          0.096s  UP-TO-DATE
        :dummy-all:processTestResources     0.038s  UP-TO-DATE
        :dummy-all:cleanTest                0.013s  
        :dummy-all:processResources         0.003s  UP-TO-DATE
        :dummy-all:classes                  0s  
        :dummy-all:testClasses              0s  UP-TO-DATE
        :   0s  (total)

### Expected Behavior
I see reasonable time for `:test` of no more than 10-20 ms (assuming code under test is simple `assertEquals(2, 1 + 1)`)

### Current Behavior

More than 1 second of performance is lost somewhere. Note - I tried profiling Gradle deamon under NetBeans, it shows that plenty of time spent on reading of files. I suspect that even with limiting of test scope to a single file/method Gradle always tries to find all tests available in project (this can be really time consuming).

![junit-performance](https://cloud.githubusercontent.com/assets/2301820/20769751/3d94d9e2-b754-11e6-97c1-b1a64e1372fd.png)

### Context
Already described above

### Steps to Reproduce (for bugs)
You may 

1. get sources of Gradle plugin for NetBeans (the one i'm using) from here https://github.com/kelemen/netbeans-gradle-project
2. build it - `gradle nbm`
3. execute single test method via `gradle -a --profile :netbeans-gradle-plugin:cleanTest :netbeans-gradle-plugin:test --tests org.netbeans.gradle.project.util.StringUtilsTest.testSplitArgsEmpty`
3. look into Gradle's profiler output - to me it says that `1.741s` is spent on `:test` out of `2.520s` total. 

However I think that same you can get on any other project having significant number of unit tests.

### Your Environment
See steps to Reproduce

**Comment by etiennestuder** [comment]
@xtracoder Do you know [build scans](https://gradle.com/)? They are a very powerful way to share build outcomes with other people, incl. test execution. Build scans provide all information you get from the profile report and much more. If you have not yet tried them out, I can recommend to [give them a spin](https://gradle.com/get-started).

**Comment by xtracoder** [comment]
I never tried it before. I tried adding it to above mentioned `netbeans-gradle-project` - noticed that some new jars were downloaded (i.e. -Dscan had same effect), but no URL was printed at the end (as provided here https://gradle.com/img/terminal_image@2x.png). 

Anyway, information provided above should be sufficient enough to diagnose and fix that performance issue.

**Comment by xtracoder** [comment]
Since that particular issue is very annoying to me personally, I've spent some time on "reverse engineering" of Gradle and here are my findings.

Overall process is very asynchronous and involves multiple processes - therefore using a profiler is almost use-less, not talking about effort spent to catch right procedure at right time in right process.

After injecting some timers into code, I've got following for my project (single-module library, 650 *.java, 37 *Test.java):

    ?:05.357Z        : (1) start detection of JUnit tests (DefaultTestClassScanner.detectionScan)
    ?:05.431Z +0.074 :     finished - ~140 files processed (via JUnitDetector)

    ?:05.563Z +0.132 : (2) GradleWorkerMain started (separate worker process)
    ?:05.634Z +0.071 :     GradleWorkerMain main.call()

    ?:06.016Z +0.382 : (3) First JUnitTestClassProcessor.processTestClass() logged
    ?:06.082Z +0.066 : (4) ... Single-Target test is executed
    ?:06.147Z +0.064 :     .. last processTestClass() logged, total 34 classes processed

    ?:06.164Z +0.017 : (5) DefaultTestExecuter execute end (i.e. `:test` finished)

              +0.807 :  -  Total time (Gradle profiler reports .942s)

Out of all this I see following: 

* JUnitDetector wastes roughly 60ms (7%) on scanning of unneeded files. Additional note here: it tries to scan super-classes for potential declaration of unit tests and at least in my case it has some adverse effect - my test cases have inner classes as sub-classes of API/Data classes from `main`. This way, during enumeration of all classes in `tests/java/classes` scaner consequently goes deep into `main/java/classes`, thus potentially going to introspective rather large set of files which are definitelly not `@Test`.

I've added filtering on files in my local build of Gradle and some integration tests got broken - particularly `canUseTestSuperClassesFromAnotherProject`. To my mind this case is needed by rather small percentage of people (at least I see no potential usage for this in my former projects), but constant performance penalty affect each and every build of major number of people. It would be nice to have that optionally enabled/disabled.

* Test are executed in a separate JVM process. Most probably this is unavoidable thing to isolate code execution, but startup of new process takes roughly 200ms (25%). This delay can be avoided by spawning of worker process "in advance" - at the beginning of building of a project, not after `:test` has started.

* There is long pause - 380ms - between 'worker is ready' and 'first test class is processed in the worker'. I suspect some inter-process communication may eat time here, but this is only a 'guess' - 380ms (45-50%) is rather long time to think about.

* Timers in Worker process show that ALL test classes are processed there too - unneeded ~65ms (7%) is spent on this, because filtering is performed after test classes are loaded (in JUnitTestClassExecuter.runTestClass). I actually curious why separate junit-detection is needed in (1) if anyway all classes are loaded in (3). 

To summarise - I see potential to cut time on 'single-test' `:test` by 400-600ms or more (50-70%). It seems that minimal possible execution time will be around 200-300ms (loading classes in target worker + overhead of processing in Gradle).

---

Off-topic: while trying to build Gradle, it seems that minimal time to build a single module is around 11+ sec (when everything is evaluated as `up-to-date`). Waste of 500ms in that scale is not that big :) ... however may someone comment if there a way to build Gradle modules quicker? In my projects incremental build takes at most 2 seconds with daemon enabled and all tests disabled.

    D:\Temp\git\gradle\subprojects\testing-jvm>gradle build -a -x test -x integTest -x codeQuality -x checkstyleIntegTest -x checkstyleMain -x checkstyleTest -x checkstyleTestFixtures -x codenarcMain -x codenarcTest -x codenarcTestFixtures --profile
    Parallel execution is an incubating feature.
    :buildSrc:compileJava UP-TO-DATE
    :buildSrc:compileGroovy UP-TO-DATE
    :buildSrc:processResources UP-TO-DATE
    :buildSrc:classes UP-TO-DATE
    :buildSrc:jar UP-TO-DATE
    :buildSrc:assemble UP-TO-DATE
    :buildSrc:checkstyleMain UP-TO-DATE
    :buildSrc:compileTestJava UP-TO-DATE
    :buildSrc:compileTestGroovy UP-TO-DATE
    :buildSrc:processTestResources UP-TO-DATE
    :buildSrc:testClasses UP-TO-DATE
    :buildSrc:checkstyleTest UP-TO-DATE
    :buildSrc:codenarcMain UP-TO-DATE
    :buildSrc:codenarcTest UP-TO-DATE
    :buildSrc:test UP-TO-DATE
    :buildSrc:check UP-TO-DATE
    :buildSrc:build UP-TO-DATE
    :killExistingDaemons
    :testingJvm:classpathManifest UP-TO-DATE
    :testingJvm:compileJava UP-TO-DATE
    :testingJvm:compileGroovy UP-TO-DATE
    :testingJvm:processResources UP-TO-DATE
    :testingJvm:classes UP-TO-DATE
    :testingJvm:jar UP-TO-DATE
    :testingJvm:assemble UP-TO-DATE
    :killExistingDaemons UP-TO-DATE
    :docs:checkstyleApi
    :testingJvm:codenarcIntegTest UP-TO-DATE
    :docs:checkstyleApi UP-TO-DATE
    :testingJvm:check
    :testingJvm:build

    BUILD SUCCESSFUL

    Total time: 11.122 secs
