### ISSUE TITLE
[Documentation] How to use Task Avoidance Configuration and reference the output of a task

### ISSUE THREAD

**Issue by dcabasson** [gradle/gradle#9504]
I am have a simple use case of a task that has an output directory that needs to be added to `sourceSets.main.java.srcDirs`.

So I create my task with a register:
```
def jflexTaskProvider = tasks.register(JFLEX_TASK_NAME, JFlexTask)
```

Note that the task is using a DirectoryProperty:
```
@CacheableTask
class JFlexTask extends DefaultTask {

    @OutputDirectory
    DirectoryProperty generateDir = project.objects.directoryProperty()
...
```

How can I reference the output of that task to use it in:
```
sourceSets.main.java.srcDirs += jflexTaskProvider.generateDir
```
(that above obviously doesn't work).

I would need a cross documentation between [Lazy Configuration#Working with files](https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:working_with_files_in_lazy_properties),  [Lazy Configuration#Working with task inputs and outputs](https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:working_with_task_dependencies_in_lazy_properties) and [Task Configuration Avoidance](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_general)

**Comment by lacasseio** [comment]
This is because you are using `getSrcDirs()` and `setSrcDirs(Iterable)`. You should just use [`srcDir(Object)` or `srcDirs(Object...)`](https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/file/SourceDirectorySet.java#L45-L59) as the documentation explains it will resolve it as `Project#files(Object)` would resolve.

**Comment by lacasseio** [comment]
The [user forum](https://discuss.gradle.org/) should be used for questions like these.
