### ISSUE TITLE
Allow repository filtering API to express exclusivity

### ISSUE THREAD

**Issue by melix** [gradle/gradle#9515]
### Context

Today, if you want to express that a dependency _must_ be found only in one repository and not others, you have to:

- declare an `include` for this dependency for the repository it should use
- declare `exclude` for this dependency on all repositories it should not use

This can be cumbersome if there are lots of dependencies.

Some ideas:

#### Suggestion by @ldaley

```
content {
   exclusivelyIncludeGroup("org.foo") // means do not try to look other repositories for this group
}
```

#### Alternative name

```
content {
   singleSourceForGroup("org.foo") // means do not try to look other repositories for this group
}
```

#### Grouped exclusivity

```
content {
    exclusiveForOtherRepositories {
        includeGroup ...
    }
}
```

Note that this can become a bit complicated if you have conflicts, in particular between regex include/excludes and repositories. Then it becomes order dependent...

We cannot rely on declarations at the dependency usage site, because repositories are used at the _consumer_ side (both for reproducibility and security). Meaning that we _cannot_ have:

```
dependencies {
     implementation("...") from jcenter()
}
```

Because this creates a whole category of new problems (what if a transitive says nothing? What if a transitive has a different version? What if a transitive says a different repo? What if a repo is spoofed?)

**Comment by melix** [comment]
Also note that the consequence of not adding excludes on other repositories is that depending on the order of repositories, we would search for the dependency in other repositories first, which can have both a performance and security impact.

**Comment by ljacomet** [comment]
Given that this is a request to express content information _across_ repositories, another idea could be to provide DSL entry points directly on `repositories`:

```
repositories {
    mavenCentral()
    maven {
        name = "foo"
        url = uri("http://repo.foo.com/")
    }
    singleRepoGroup('com.foo', 'foo') // Name subject to discussion ;-)
    singleRepoGroup('org.apache', 'MavenRepo') //Default name of Maven Central
    // And similar methods for the other interesting concepts like that
}
```

**Comment by melix** [comment]
PR: #11763
