### ISSUE TITLE
Use --processor-module-path instead of -processorpath in JDK9+

### ISSUE THREAD

**Issue by coladict** [gradle/gradle#9519]
### Expected Behavior
If JDK version is 9 or above, it should use `--processor-module-path` instead of `-processorpath` when specifying an annotation processor.

### Current Behavior
`subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java` uses `-processorpath` for all versions.

### Context
Due to the removal of javax.xml.bind from JDK11 this prevents the use of hibernate-jpamodelgen.

This feature requires that [JDK-8223942](https://bugs.openjdk.java.net/projects/JDK/issues/JDK-8223942) is fixed first, or that `SourcepathIgnoringProxy` not be used, and just have the task always be invoked, instead of just when not up-to-date.

**Comment by coladict** [comment]
[JDK-8223942](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8223942) is now fixed for JDK 13 b25 and the upcoming JDK 14 LTS release, but they have decided not to apply the fix to the current LTS version JDK 11.

**Comment by Sm0keySa1m0n** [comment]
Is there any plans for this to be implemented, as it stands there is no way to define modular annotation processors as https://github.com/gradle/gradle/blob/45d830666efe92b35f750422d57f202e52ee3cac/platforms/jvm/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java#L214 will always add processors to the legacy `processorpath`.
