### ISSUE TITLE
Request for version of `Property.finalizeValue()` that does not resolve providers

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#9531]
We would like a version of `finalizeValue()` that 
- does prevent calls to `set()`
- does **not** resolve values already set via `Provider`.

The goal is to prevent people from touching the `DirectoryProperty`, `RegularFileProperty` and `ListProperty` public fields on task instances, while still allowing us to change things under the hood.

The idea is to set these fields with an internal `Property` that we can keep around and change via an API that allows people to rewire tasks as needed (where we can properly updated both the producer and consumer tasks), but prevent random changes to the public field.

**Comment by ducrohet** [comment]
oh, in the case of `ListProperty`, it should obviously also prevent calls to `empty`, `add`, `addAll.
On `Property` it should also prevent calls to `value`

And on both, it should also prevent calls to `convention`.

(I think I covered all of them :))

**Comment by lacasseio** [comment]
There seems to be several ways to solve this. With current Gradle, it could be solved using either:
- Use constructor arguments that receive the properties to use but implement only `Provider` getters
- Split a public and internal implementation of the task where the public implementation exposes only `Provider` and the internal implementation exposes `Property`. Unfortunately, Groovy users will still be able to change the values as they are going to see the internal type.

What Gradle could offer is a way to bind a `Property` to another one (from a DSL, for example) and lock that binding so no further change can be made. This locking could force users to only change the source `Property` and preventing any mutation on the "locked" `Property`. For others that use the task in an ad-hoc way, they can change the property directly on the task or bind & lock to another property.

Could you expand a bit more on why using the two current solutions above (constructor args or internal task implementation) wouldn't be a good fit for your need and required a "bind & lock" feature?

**Comment by ducrohet** [comment]
Constructor arguments or public/internal implementation of a task are a valid option.
However:

- You lose the recent nice automatic instantiation of properties when declaring them as abstract on your task :(
- This limits us to our own tasks, but we are trying to build an API that helps 3rd party plugins wire their tasks with ours in a very controlled API. We want to control (some of) the inputs/outputs of these tasks and we want to prevent people from touching them after we set them.

I'm not sure I understand the locked binding mechanism, especially when you mention "from a DSL for instance" and then say "they can change the property directly on the task".

We want this locked binding to prevent anyone from touching the task instance once it's been set with another property. We don't want to make a distinction between what you can do from the DSL vs what you can do on the task directly. In our case this API we are building can be used from the build file (though it wouldn't look like a declarative DSL), or from plugins. I'm not sure how you draw the line when you mention DSL.

Here's a concrete example of what we are trying to do as a small prototype: https://github.com/ducrohet/artifact-api-proto
See the readme to play with it.

Main API is here: https://github.com/ducrohet/artifact-api-proto/blob/master/buildSrc/api/src/main/kotlin/core/api/ArtifactHolder.kt

Usage of the API is here: https://github.com/ducrohet/artifact-api-proto/blob/master/buildSrc/third-party-plugin/src/main/kotlin/third/party/plugin/CustomPlugin.kt#L18

Implementation is here: (not direct impl of the interface but it delegates parts of it to this class)
https://github.com/ducrohet/artifact-api-proto/blob/master/buildSrc/core-plugin/src/main/kotlin/core/internal/impl/SingleArtifactUtils.kt

**Comment by adammurdoch** [comment]
Added via https://github.com/gradle/gradle/pull/9771
