### ISSUE TITLE
Could not download correct snapshot version

### ISSUE THREAD

**Issue by luzhzhsoft** [gradle/gradle#9532]
### Expected Behavior
I want to download a snapshot in my maven .But gradle told me Resource missing.When I open log,I found gradle download wrong version.
Gradle will download snapshot version by concating timestamp and buildnumber.It correct in almost all time.But there's something special about my situation .My maven-metadata.xml is 

```
<metadata modelVersion="1.1.0">
    <groupId>org.bwae.auth</groupId>
    <artifactId>auth</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <versioning>
        <snapshot>
            <timestamp>20190524.065754</timestamp>
            <buildNumber>2</buildNumber>
        </snapshot>
        <lastUpdated>20190524065754</lastUpdated>
        <snapshotVersions>
            <snapshotVersion>
                <extension>jar</extension>
                <value>0.0.1-20190524.065752-1</value>
                <updated>20190524065754</updated>
            </snapshotVersion>
            <snapshotVersion>
                <extension>pom</extension>
                <value>0.0.1-20190524.065752-1</value>
                <updated>20190524065754</updated>
            </snapshotVersion>
            <snapshotVersion>
                <classifier>sources</classifier>
                <extension>jar</extension>
                <value>0.0.1-20190524.065752-1</value>
                <updated>20190524065754</updated>
            </snapshotVersion>
        </snapshotVersions>
    </versioning>
</metadata>
```

Snaptshot version not equal  timestamp with buildNumber.It is happens because I upload a  jar to maven failed last time,so, it build number will add one ,but snapshot version will not.
https://github.com/gradle/gradle/blob/a4ac29f8fab55e587130677f9d2df826dc0a8786/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/resolver/MavenResolver.java#L181
so this logic is not correct.Snapshot version  should not relay on buildNumber
### Current Behavior

gradle can not download the correct  snapshot version.
```
Downloading http://maven.bwae.org/repository/ae-public/org/bwae/auth/auth/0.0.1-SNAPSHOT/maven-metadata.xml to C:\Users\Luzz\AppData\Local\Temp\gradle_download9101900790421438102bin
Resource missing. [HTTP GET: https://maven.bwae.org/repository/ae-public/org/bwae/auth/auth/0.0.1-SNAPSHOT/auth-0.0.1-20190524.065754-2.pom]
Resource missing. [HTTP HEAD: https://maven.bwae.org/repository/ae-public/org/bwae/auth/auth/0.0.1-SNAPSHOT/auth-0.0.1-20190524.065754-2.jar]
```
### Steps to Reproduce 

Deploy a jar to maven failed.And gradle will not work correctly
### Your Environment

Build scan URL:

**Comment by ljacomet** [comment]
Sadly the Maven specification for these files does not say much about the consistency of the content, especially between the `snapshotVersion` and `snapshot` child nodes.

Given this is the result of failed deployment, the easiest solution is to attempt the deployment again or correct the `maven-metadata.xml` file itself.

**Comment by ljacomet** [comment]
Closing as there is no plan on changing this behavior from the Gradle side.
