### ISSUE TITLE
Move clean task from java plugin to project scope

### ISSUE THREAD

**Issue by Thunderforge** [gradle/gradle#9538]
The `clean` task deletes the `buildDir` directory (which by default is `build/`). The `buildDir` directory is [part of every Project](https://github.com/gradle/gradle/blob/b189979845c591d8c4a0032527383df0f6d679b2/subprojects/core-api/src/main/java/org/gradle/api/Project.java#L264), but the `clean` task is [part of the `java` plugin](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_tasks). 

If the Project knows about the `buildDir`, I think that the task that does nothing aside from delete that directory should also be part of the project, rather than part of the Java plugin. After all, non-Java projects still may want to delete that directory, and re-implementing the task for every language is excessive.

### Expected Behavior
The `clean` task should be available to all projects because all projects have a `buildDir`.

### Current Behavior
The `clean` task is part of the Java project, despite it doing nothing that is Java-specific.

### Context
When using non-Java projects, we either have to add the Java plugin to get the functionality of the `clean`, or we have to create our own `clean` task to accomplish this functionality.

**Comment by ljacomet** [comment]
The `clean` lifecycle task is actually provided by the `lifecycle-base` plugin which is automatically applied by the `base` plugin.

So in which context do you have a project that does not even apply the `base` plugin, directly or indirectly?

**Comment by Thunderforge** [comment]
@ljacomet We have a project that we can build without any plugins (it does everything through command line commands). Not including our custom tasks, the output of `tasks` is:

```
> Task :tasks

------------------------------------------------------------
Tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'FooProject'.
components - Displays the components produced by root project 'FooProject'. [incubating]
dependencies - Displays all dependencies declared in root project 'FooProject'.
dependencyInsight - Displays the insight into a specific dependency in root project 'FooProject'.
dependentComponents - Displays the dependent components of components in root project 'MariaServiceWrapper'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'FooProject'. [incubating]
projects - Displays the sub-projects of root project 'FooProject'.
properties - Displays the properties of root project 'FooProject'.
tasks - Displays the tasks runnable from root project 'FooProject'.
```

We would like `clean` to be available, since even in this pluginless project, the `buildDir` directory is defined (and we use it as output for our custom tasks). Similarly, we were looking into adding some plugins that do reporting, and those write to `build/reports`. But we can't clean that output because the task isn't available.

**Comment by big-guy** [comment]
@Thunderforge You can just apply the `base` plugin.  That's what we would recommend.
