### ISSUE TITLE
Simplify connecting a task output of type `File` to a task input with `Property` type

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#9542]
Simplify connecting the output of a task that uses `File` to represent an output (an 'old' task) as an input of a task that uses property types to represent an input (a 'new' task).

Currently this is possible, but could be made simpler.

### Expected Behavior

Less boiler plate is required to connect the 2 tasks. Specifically:

- Make the process simpler when a plugin has a `Task` instance, rather than a `TaskProvider` instance.
- Make the conversion from `File` into a `RegularFile` or `Directory` simpler.

### Current Behavior

This is possible, but requires access to the project's `TaskContainer` and `ProjectLayout`, which may not be available, plus a bunch of method calls.

**Comment by big-guy** [comment]
Could we do something like this?
```
// helper API in Task

Provider<RegularFile> bridgeRegularFile(FileProvider)
Provider<Directory> bridgeDirectory(FileProvider)

// Bridging functional interface
interface FileProvider {
    File getFile()
}
```

And then to wire old and new tasks...

```
newTask.fileProp.set(oldTask.bridgeRegularFile(oldTask::getDestination) // Java 8+
newTask.fileProp.set(oldTask.bridgeRegularFile(oldTask.&getDestination) // Groovy
```

I assume Kotlin has something similar, but if not, you could always be verbose:

```
newTask.fileProp.set(oldTask.bridgeRegularFile(new FileProvider() {
    File getFile() { return oldTask.getDestination() }
})
```

A Directory bridge would look the same.

We could also avoid FileProvider and use Callable, at the cost of using a lambda with each of the calls.
