### ISSUE TITLE
5.6 nightlies break Provider-based task dependencies

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#9556]
We have a ShadowJar task in our build which is configured with the following line:

```
from(sourceSets.main.map { it.output })
```

This no longer carries the task dependency as it used to, thus failing to build the necessary classes before the jar is packaged. 

Changing it to 
```
from(sourceSets.main.get().output)
```

fixed it.

**Comment by adammurdoch** [comment]
Should be fixed via https://github.com/gradle/gradle/pull/9992
