### ISSUE TITLE
Generated POM file and module.json erroneously omit version when `resolutionStrategy.eachDependency` is used with  `useVersion`

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#9565]
When using `configurations.all {  resolutionStrategy.eachDependency { } }` technique with `useVersion` in the dependency resolution details, the version is not included in the publishing details.

### Expected Behavior

The version should be used in the generated POM and `module.json` files.

### Current Behavior

Version is omitted in the generated files.

### Context

Surprisingly broke publishing in a Gradle Plugin when switching from several duplicated versions to using a dependency resolution technique.

### Steps to Reproduce 

```kotlin
plugins {
  kotlin("jvm") version "1.3.31"
  `java-library`

  `maven-publish`
}

group = "com.mkobit.example"

repositories {
  jcenter()
}

configurations.all {
  resolutionStrategy.eachDependency {
    when (requested.group) {
      "com.squareup.okhttp3" -> {
        logger.lifecycle("setting version for configuration ${this@all.name} com.squareup.okhttp3")
        useVersion("3.14.1")
      }
    }
  }
}

dependencies {
  api("com.squareup:javapoet:1.11.1")
  implementation("io.github.microutils:kotlin-logging:1.6.26")
  implementation("com.squareup.okhttp3:okhttp")
}

publishing {
  publications {
    create<MavenPublication>("library") {
      from(components["java"])
    }
  }
}
```

Run `./gradlew generatePomFileForLibraryPublication`

Logger output

```
> Task :generatePomFileForLibraryPublication
setting version for configuration compileClasspath com.squareup.okhttp3
setting version for configuration runtimeClasspath com.squareup.okhttp3
```

In `build/publications/library/pom-default.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mkobit.example</groupId>
  <artifactId>kotlin-dsl-lab</artifactId>
  <version>unspecified</version>
  <dependencies>
    <dependency>
      <groupId>com.squareup</groupId>
      <artifactId>javapoet</artifactId>
      <version>1.11.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.github.microutils</groupId>
      <artifactId>kotlin-logging</artifactId>
      <version>1.6.26</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>

```

Notice no verson for `com.squareup.okhttp3` and `okhttp`

Run `./gradlew generateMetadataFileForLibraryPublication`

Inside of `build/publications/library/module.json`

```josn
{
  "group": "com.squareup.okhttp3",
  "module": "okhttp",
  "version": {}
}
```

No version as well.

### Your Environment

Gradle 5.4.1

**Comment by mkobit** [comment]
Possibly similar to https://github.com/gradle/gradle/issues/9508

**Comment by ljacomet** [comment]
The default behavior of publication is to use _declared_ versions, and in your buildscript, the version of `com.squareup.okhttp3:okhttp` is declared as absent and is computed during resolution.

If you want to ensure there is a version in the published result, have a look at [publishing resolved version](https://docs.gradle.org/5.4.1/userguide/publishing_maven.html#publishing_maven:resolved_dependencies).

**Comment by mkobit** [comment]
Ok, I didn't know that.

I've added:

```kotlin
afterEvaluate {
  publishing {
    publications {
      getByName("pluginMaven", MavenPublication::class) {
        versionMapping {
          allVariants {
            fromResolutionOf("runtimeClasspath")
          }
        }
      }
    }
  }
}
```

`afterEvaluate` seems to be needed because this is a Gradle plugin and it relies on https://github.com/gradle/gradle/blob/0cfcfdfd0ec76864190d66f3c2f8621095e25278/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/plugins/MavenPluginPublishPlugin.java#L49-L54

Which seems to produce the desired POM result?

**Comment by mkobit** [comment]
I also didn't see a warning (uploaded scan to https://scans.gradle.com/s/qlrapaoppmtuo).

**Comment by mkobit** [comment]
So, that _seems_ right, although I found it a bit unexpected that I had to do that. Feel free to close.

**Comment by dsilvasc** [comment]
Is there a way to publish resolved versions in gradle 4.x?  Looks like versionMapping was added in gradle 5.

**Comment by bigdaz** [comment]
> Is there a way to publish resolved versions in gradle 4.x? Looks like versionMapping was added in gradle 5.

@dsilvasc Check out the https://github.com/nebula-plugins/nebula-publishing-plugin which provides this functionality.

**Comment by dsilvasc** [comment]
thank you @bigdaz :)
