### ISSUE TITLE
Gradle build fails with class file not found on overloaded constructor

### ISSUE THREAD

**Issue by ralfstx** [gradle/gradle#9567]
When a Java class in one module calls an overloaded constructor in a class in a different module, the compiler seems to confuse the overloaded constructors and raises an access error that is related to the constructor that is not called.

### Steps to Reproduce 

A project with two modules `common` and `main`:
```
include 'main'
include 'common'
```
common:
```
dependencies {
    implementation "com.google.code.gson:gson:2.8.5"
}
```
main:
```
dependencies {
    implementation project(':common')
}
```
that contain these classes:
```java
import com.google.gson.Gson;

public class Common {

  public Common(String foo) {
  }

  private Common(Gson gson) {
  }
}
```

```java
public class Main {

  public static void main(String[] args) {
    new Common("");
  }
}
```

### Current Behavior

calling `gradlew build` fails with
```
$ ./gradlew build

> Task :main:compileJava FAILED
/tmp/delete-me/main/src/main/java/Main.java:4: error: cannot access Gson
    new Common("");
    ^
  class file for com.google.gson.Gson not found
1 error
```

Adding a second parameter to the `Common(Gson)` constructor solves the problem.
This leads to the assumption that the compiler mixes up the overloaded ctors.

### Expected Behavior
Since the constructor `Common(Gson)` is not used, the compilation should not fail.

### Your Environment
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_212 (Oracle Corporation 25.212-b03)
OS:           Linux 4.15.0-50-generic amd64
```

**Comment by koppor** [comment]
@ralfstx Any updates on this? Google found this among the first hits for similar compiler errors.

**Comment by ljacomet** [comment]
Sorry for the late reply

This is a combination of api/implementation separation in Gradle and a `javac` behavior around overload resolution. The private constructor is loaded by `javac`.

There is nothing to be done on the Gradle side to change `javac` behavior, you would have to check the spec and possibly open an issue against the JVM.
The workaround is to change `gson` to be an `api` dependency.
