### ISSUE TITLE
Provider a `FileCollection` to `ListProperty<FileSystemLocation>` conversion

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#9568]
The Android Plugin is migrating to using `DirectoryProperty`, `RegularFileProperty` and `ListProperty<FileSystemLocation>` everywhere both internally (for now) and in its public API (in the future).

We do have existing APIs (for other plugins to use) that rely on `FileCollection`. Some of these allow plugins to provide a `FileCollection` that we then pass to our tasks. This is used for example to register tasks that generate source code, or resources.

In order to migrate fully to properties, we would need a way to convert a random `FileCollection` to a `ListProperty<FileSystemLocation>` that includes the task dependency.

**Comment by lacasseio** [comment]
Do you happen to have a concret example you could point in the Android plugin code? A `FileCollection` is already lazy and contain task dependency. In general, we wouldn't allow `ListProperty<FileSystemLocation>` to be constructed given its most likely a `FileCollection` or `FileTree` (both are lazy and composable).

In order to add items to a `FileCollection` we generally recommend using `ConfigurableFileCollection` for the user to call `from` for adding anything that can be converted to a `File`.

**Comment by ducrohet** [comment]
Here our API: https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/api/BaseVariant.java#478

We currently use `FileCollection` as inputs to our tasks (and we do compose them with `from()`) but we want to move to `Property` instead. In order to do this we want to be able to do something like this (on a `ListProperty): `myListProperty.addAll(myFileCollection)`

**Comment by lacasseio** [comment]
I think I see the issue. We want to move toward where `FileCollection` and `FileTree` are `Provider` and `ConfigurableFileCollection` and `ConfigurableFileTree`are `Property`. In your case, adding a `FileCollection` to a `ListProperty` eagerly resolve it as it sees it as an `Iterable`. Could that `myListProperty` be of type `ConfigurableFileCollection`?

**Comment by ducrohet** [comment]
This would not be great. Our planned API is to make this list property accessible via an API too for people wanting to just consume a build intermediate (rather than append to it).
I'm not super fond of `ConfigurableFileCollection` as it cannot really be make read-only, which is why I filed[ Issue 9531](https://github.com/gradle/gradle/issues/9531). Take a look at the prototype (linked in that issue) of our planned API to see how it all fit together.

**Comment by lacasseio** [comment]
Let me look at those two issues in more details.

**Comment by adammurdoch** [comment]
https://github.com/gradle/gradle/pull/9772 adds a `FileCollection.getElements()` method, which returns `Provider<Set<FileSystemLocation>>`. This provider can be used as-is or can be added to any `ListProperty<FileSystemLocation>` or `SetProperty<FileSystemLocation>`.
