### ISSUE TITLE
[RegularFile|Directory]Property.convention does not add anything over set/value

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#9569]
Setting a value as a convention on a `RegularFileProperty` or `DirectoryProperty` does not seem to add anything over the standard way to set a value (via `set` or `value`).

Here's a sample test:

```
class MyPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        val prop = project.objects.fileProperty()
        val nullFile: RegularFile? = null

        prop.display("Empty")
        prop.display("setConvention") {
            convention(project.layout.projectDirectory.file("path/to/convention"))
        }
        prop.display("setValue") { set(File("/path/to/somewhere"))}
        prop.display("reset") { set(nullFile) }
        prop.display("newValue") { set(File("/path/to/somewhere/else"))}
    }
}

private fun RegularFileProperty.display(label: String, block: (RegularFileProperty.() -> Unit)? = null) {
    if (block != null) {
        block(this)
    }
    println("----------")
    println(label)
    println("isPresent: $isPresent")
    try {
        println("Value: ${get().asFile}")
    } catch (e: Exception) {
        println("get() throws: ${e.message}")
    }
}
```

the output is the following:
```
----------
Empty
isPresent: false
get() throws: No value has been specified for this provider.
----------
setConvention
isPresent: true
Value: /Users/xav/GitHub/convention-test/path/to/convention
----------
setValue
isPresent: true
Value: /path/to/somewhere
----------
reset
isPresent: false
get() throws: No value has been specified for this provider.
----------
newValue
isPresent: true
Value: /path/to/somewhere/else
```

It shows that there's no difference in the output whether setting via `set` or `convention`. I had thought that maybe when resetting the value (via `set(null)`) it would revert back to the convention value, but that's not the case. `isPresent` is also not affected (which makes sense since `get()` throws when nothing in present.)

This seems to make using `convention` useless. Am I missing something?

**Comment by lacasseio** [comment]
There may be a gab here. The convention is applied when no value is present. Setting a `Property` to `null` may seem like a "reset" the property but in fact, is interpreted as "an explicit value has been set which is `null`". The convention can be chained when creating it so you can configure the default value without specifying an explicit value: `val fileProp = objectFactory.fileProperty().convention(layout.buildDirectory.file('foo')`

Once a value is set, the convention can't be used anymore as every mutating method specify a value explicitly. The feature of "set to undefined" is missing at the moment. We just didn't have a compelling use case for that, yet.

Given that, it seems we are having a strange behaviour with regards to setting a property to `null`. We are explicitly setting the `Property` to null so a value is present in the `Property` but it can't be retrieved by `get()` which has a strong opinion on non-null return value and `isPresent()` is opinionated on `null` containing provider being empty. I think that disallowing setting null value (nagging users first before throwing an exception) and providing a method to reset the `Property` could solve this issue.

@adammurdoch What do you think? Do you see another issue/solution that I may be overlooking?

**Comment by ducrohet** [comment]
I see the chaining possibility, but you can also do this:
`val fileProp = objectFactory.fileProperty().convention(File("..."))`
The only difference is that `value()` does not work with a provider (strangely?)

It seems to me that using `convention` over `set`/`value` still does not provide any behavior differences on the instance.

We are currently looking at using `Property<String?>` (and `Int?`, `Boolean?`, etc...) in some places in our DSL where *do* want to have nullable values, and wondered if `convention` would be an interesting way to encode the default in the property while still allowing (and testing for ) `null` values.

Right now it seems like we should just ignore `convention`, and please don't remove the ability to set a null value :)

**Comment by adammurdoch** [comment]
https://github.com/gradle/gradle/pull/9774 changes `set(null)` so that the convention is used, if there is a convention set on the property. I think this is a reasonable tweak.

It's still an open question whether we will replace `set(null)` with some method that discards the value, possibly something explicit like `discardValue()` or possibly a `setNullable(T)` that can take a null or a value.

Also https://github.com/gradle/gradle/pull/9774 adds the missing `value(provider)` methods (that I forgot to add earlier).

**Comment by adammurdoch** [comment]
@ducrohet can we close this or do you think there are further changes necessary?

**Comment by ducrohet** [comment]
Yes this addresses my comments. thanks!
