### ISSUE TITLE
Gradle Daemon holding lock on dependent jar

### ISSUE THREAD

**Issue by benwatson528** [gradle/gradle#9572]
I have a multi-module Gradle 4.4 project (but I also see this on Gradle 5.4.1) - there's a parent `build.gradle` and then two child Gradle projects, each with their own `build.gradle`. Both are Java projects (one is for dev code, the other for QA). The dev project is a dependency of the QA project (I have `testCompile project(':dev-project')` in the QA project's `build.gradle`). Otherwise there is nothing remotely interesting or unusual in the `build.gradle` files - they import the `java` plugin and `com.github.johnrengelman.shadow`.

If I try to build the parent project twice in a row (no IDEs open, running `./gradlew clean build` from Git Bash without Administrator privileges), the build fails. A `Java(TM) Platform SE Binary` process has a lock on the `dev-project` jar. Disabling Gradle Daemon (or killing the process) resolves the issue.

### Expected Behavior
With Gradle Daemon enabled, I should be able to build the project twice in a row without having to unlock the `dev-project` jar.

### Current Behavior
The `dev-project` jar is locked by the Gradle Daemon after `gradle build` completes.

### Context
I want to be able to build a project as many times as I want without the cumbersome middle step of manually deleting the `Java(TM) Platform SE Binary` task or disabling Gradle Daemon.

### Steps to Reproduce 
I can set up a sample project in 9 hours which I can link here if needed. In the meantime, simply having a parent `build.gradle` and then two Java-based children, one of which depends on the other (via `testCompile project(':dev-project')`) will recreate this.

### Your Environment
Again, can do this tonight, but I've been running on Windows 10. I don't have admin access.

**Comment by big-guy** [comment]
Have you tried running without the shadow plugin applied?

A reproducer project would be great.

**Comment by benwatson528** [comment]
Hello, I've been unable to recreate this at home with a simple project; I'm going to have to find some spare time at work to play around with the more complex project I have there. My apologies, I'm not going to be able to proceed further with this.

I'll re-open if I can recreate this in a simple project.
