### ISSUE TITLE
Copy fails if target directory contains unreadable directory

### ISSUE THREAD

**Issue by chrislong** [gradle/gradle#9576]
### Expected Behavior
The Copy task should copy a file regardless of the state of unrelated files or directories in the output directory.

### Current Behavior
If the output directory of a Copy task contains an unreadable directory, the task fails with "Could not read path".

### Context
My build file copies a .war file to a tomcat directory, in which some of the directories may be owned by tomcat (and thus unreadable by the current user).

### Steps to Reproduce 
1. Put the following into a `build.gradle` file
```
task('fails', type: Copy) {
    doFirst {
        mkdir 'build/unreadable'
        file('build/unreadable').setReadable(false)
    }
    from('.') {
        include 'build.gradle'
        rename { 'fails.txt' }
    }
    into 'build'
}

```

2. Run `./gradlew fails` (or `gradlew fails` on Windows, I think)

### Your Environment
```
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.15.0-50-generic amd64
```
on Ubuntu 18.04.

This may be related to #1365.
PR: https://github.com/gradle/gradle/pull/9746

**Comment by lptr** [comment]
We'll provide a new API in #18159 that will be required to keep `Copy` tasks working with unsnapshottable outputs.
