### ISSUE TITLE
Gradle 5.5-rc1 Extra values not resolving in extension function

### ISSUE THREAD

**Issue by AndrewReitz** [gradle/gradle#9579]
We have a few extension functions in kotlin like the following
`inline val DependencyHandler.androidGradlePlugin get() = implementation("com.android.tools.build:gradle:${extra["androidGradlePluginVersion"]}")`

This works on 5.4 but on 5.5-rc-1 it is now failing with 

> Cannot get property 'androidGradlePluginVersion' on extra properties extension as it does not exist

### Expected Behavior

Should continue to resolve the value from extras

### Current Behavior

Fails with error message:
> Cannot get property 'androidGradlePluginVersion' on extra properties extension as it does not exist

### Context

Was working on 5.4, stopped working on 5.5-rc1. We are using this extension method to clean up our dependencies block as well as having the version in extras so we can have it loaded from a separate kts file.

### Steps to Reproduce 
Sample Project: https://github.com/AndrewReitz/gradle-extra-5.5-issue

### Your Environment

Working Environment:
```
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Mac OS X 10.14.3 x86_64
```

Failing Environment:
```
------------------------------------------------------------
Gradle 5.5-rc-1
------------------------------------------------------------

Build time:   2019-05-29 11:51:19 UTC
Revision:     6c070eb6e47979d5642a181e3efa11bf237dc69c

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Mac OS X 10.14.3 x86_64
```

Scan from Demo Project: https://scans.gradle.com/s/x2mezxz7zkk3k

**Comment by big-guy** [comment]
I suspect this has to do with #7414.  

You're getting a different "extra" now (from DependencyHandler instead of Project).  DependencyHandler has always had its own extra properties, but it wasn't visible to the Kotlin DSL until now.

To get to the project's extra properties, you have to go through `project.extra`.

I think you may want to use `create` instead of the side effect of adding a dependency to the implementation configuration.
Something like:
```
inline val DependencyHandler.kotlinStd get() = create("com.android.tools.build:gradle:${project.extra["stdLibVersion"]}")
```

And then you'd use it as:
```
dependencies {
   implementation(kotlinStd)
}
```

/cc @eskatos @bamboo WDYT?

**Comment by eskatos** [comment]
Yes that's #7414, `project.extra` is now required inside `dependencies {}` to access the `Project` extra properties. Just `extra` point to the extra properties of `dependencies` itself.

It is expected, I just submitted a PR to mention it explicitly in the upgrade guide
https://github.com/gradle/gradle/pull/9619

Thanks for the heads up @AndrewReitz!
