### ISSUE TITLE
External console window is visible when using Exec on Gradle 3.2.1

### ISSUE THREAD

**Issue by andreiled** [gradle/gradle#958]
### Expected Behavior
When running external executable using Exec, it should run in background and should not display console window.

### Current Behavior
On Gradle 3.2.1 I can see new console window appear for each of the commands I executed from Gradle script, it disappears once the command is finished.
On Gradle 3.1 I observe the expected behavior (no console windows appear).

### Context
I have an automation script written on Gradle that executes quite a few commands in sequence, analyses their results and executes other commands based on that.
In that script I rely on Gradle's feature to create tasks dynamically based on configuration.

### Steps to Reproduce (for bugs)
For testing purposes I created a dummy Gradle project with a single Exec task:
```
plugins {
    id 'com.gradle.build-scan' version '1.3'
}

buildScan {
    licenseAgreementUrl = 'https://gradle.com/terms-of-service'
    licenseAgree = 'yes'
}

task testExec(type: Exec) {
    executable 'ping'
    args '127.0.0.1', '-n', '3'
}
```
and then executed it first using Gradle 3.1 (`~/.gradle/wrapper/dists/gradle-3.1-bin/37qejo6a26ua35lyn7h1u9v2n/gradle-3.1/bin/gradle -b test-exec.gradle testExec`) and then Gradle 3.2.1 (`~/.gradle/wrapper/dists/gradle-3.2.1-bin/erlz51pt56t1o6vc7t39cikug/gradle-3.2.1/bin/gradle -b test-exec.gradle testExec`).

### Your Environment

GitBash 2.6.0.windows.1

 * Build scan URL: https://scans.gradle.com/s/l45mkuruiynxi

**Comment by slavashvets** [comment]
The same behaviour when I execute gradle build from my git bash, since 3.2

**Comment by big-guy** [comment]
Can either of you paste the contents of your `gradlew` script?

**Comment by andreiled** [comment]
@big-guy, I'm not using gradlew in this example at all to cut out extra steps in order to isolate the issue. As stated in the defect description I'm running my gradle script using specific gradle binaries.

When I'm actually running it using gradlew I'm using the version coming with the appropriate distribution without any changes to it: I use following command to switch project to a specific gradle version: ```./gradlew wrapper --gradle-version=3.2.1``` (that's how I first encountered the issue).

**Comment by big-guy** [comment]
Hmm, thanks.

Can you try the `gradle.bat` script and see if you have the same problem?

**Comment by andreiled** [comment]
I tested it first in Git Bash using following commands:
```
./gradlew wrapper --gradle-version=3.2.1 && ./gradlew -b test-exec.gradle testExec
./gradlew wrapper --gradle-version=3.1 && ./gradlew -b test-exec.gradle testExec
```
and then in Windows CMD as well:
```
gradlew.bat wrapper --gradle-version=3.2.1 && gradlew.bat -b test-exec.gradle testExec
gradlew.bat wrapper --gradle-version=3.1 && gradlew.bat -b test-exec.gradle testExec
```
The result is the same: on 3.2.1 I can see new console window open for the executable that I run.

**Comment by slavashvets** [comment]
It turns out that a window appears only if a build is running via Gradle Daemon. In parallel mode I see several windows for each "javac.exe" (for compile) and "java.exe" (for tests) task. My Gradle version is "3.3-rc-1". Very annoying bug :(

**Comment by slavashvets** [comment]
I've updated my JDK from 1.8.0_45 to 1.8.0_111 and the bug is gone, even using Gradle Daemon :)

**Comment by lacasseio** [comment]
Seems to me the problem was related to the JDK version and won't be addressed by us. I will close this issue as `is:not-actionable`.
