### ISSUE TITLE
Silent transitive dependency failure

### ISSUE THREAD

**Issue by rgozim** [gradle/gradle#9580]
### Steps to Reproduce 
Please see my [example project](https://github.com/rgozim/gardle-dependency-example)

The application demonstrates an issue with dependency resolution when a dependency is published to maven, using the maven-publish plugin, with multiple publications.

**Please note, this is not an issue with composite projects.**

### Expected Behavior
Depending on LibA with transitive dependencies (in this case LibB) is expected to successfully resolve, or throw an error if something isn't right.

### Current Behavior
In a linear dependency graph, where an App depends on LibA, which itself exposes transitive dependency LibB via `api` or `compile` configurations, LibA fails to resolve correctly.

### Context
In the linked example, LibA contains multiple maven `publications`. The first publication, publishes a _jar_ and the second publishes a _zip_ file containing docs. Attempting to depend on the library fails to resolve correctly and does not display any error or warning. 

On any projects depending on LibA (in the example App) calling `gradle dependencies` fails to show any transitive dependencies of the java library.

Removing the non standard `publication` resolves the error.

### Your Environment
```
------------------------------------------------------------
Gradle 5.2
------------------------------------------------------------

Build time:   2019-02-04 11:16:48 UTC
Revision:     840644a429c8b8b9ae399867eb1660e3109bc7a3

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_212 (Azul Systems, Inc. 25.212-b04)
OS:           Mac OS X 10.14.5 x86_64
```

**Also tested with Gradle 5.4.1**

**Comment by ljacomet** [comment]
Your sample defines two _different_ publications with the same coordinates. When running something like `publishToMavenLocal`, both are published, `libraryA` first then `someDocs`. But the metadata of the later overwrites the one for the former.

I believe that what you are trying to achieve is a single publication, with its main artifact. And then add a secondary artifact for the zip resource.

In that case, you can simply move the line `artifact zipResources` to the first publication and delete  the second one.

**Comment by bigdaz** [comment]
FWIW in Gradle 5.6 this will cause a failure when running `publishToMavenLocal`.

The underlying issue is https://github.com/gradle/gradle/issues/3835.

**Comment by rgozim** [comment]
I found that changing the publication name (alphabetical ordering maybe) would also cause the publication to succeed, i.e. transitive dependencies resolve - which made things even more confusing, so hopefully the fix in 5.6 solves this. 

I have modified my build.gradle to lookup an existing publication (created by a plugin) and added the `zipResources` as an artifact, which does indeed work. 

However, on a side note, at what point is it in a Java project that a user should decide that another publication is required?

In one example ([not my post, but same logic](https://stackoverflow.com/a/54280443/272446)), I have an application that has two publications - one for publishing a compiled jar only and another for publishing the jar, javadoc and sources. Would this be considered "an error" as both publications tasks will run and overwrite their contents if `publishToMavenLocal` or `publish` are run, is there a way to skip javadoc and sources generation using a single publish?

**Comment by ljacomet** [comment]
The example given in [the documentation](https://docs.gradle.org/5.4.1/userguide/publishing_overview.html#publishing_maven:conditional_publishing) differentiates what is being published to which repository. In the example sources go only in internal repos while public facing repo only has the binaries.

**Comment by rgozim** [comment]
Thanks for the pointer @ljacomet.
