### ISSUE TITLE
have gradle init also create the .gitattributes file

### ISSUE THREAD

**Issue by teyckmans** [gradle/gradle#9583]
Gradle init does not create a .gitattributes file to make sure that the newlines in the gradlew.bat file are correctly handled by git. Without the .gitattributes file the local file is different from what others will see when they clone the Git repository.

### Expected Behavior
$ gradle init --type basic --dsl kotlin

should also create a .gitattributes file with the following contents:
*.bat eol=crlf

$ git init
$ git add --all
$ git commit -m "initial commit" 

Should work without giving any warnings and should not result in inconsistent repository / local directory state.

### Current Behavior
$ gradle init --type basic --dsl kotlin
$ git init
$ git add --all
**warning: CRLF will be replaced by LF in gradlew.bat.
The file will have its original line endings in your working directory**
$ git commit -m "initial commit" 

### Context
At the moment it is required to always create the .gitattributes file manually. The warning may also confuse first time users of Gradle/Git causing them to loose time on something that may not even be an issue for them. It also gives a poor first impression.

This issue is only relevant for dev teams that have a mixture of operating systems.

**Comment by teyckmans** [comment]
It has been a while but I'll take a stab at it.

**Comment by teyckmans** [comment]
I looked impact on the documentation but don't see a reference to the creation of a .gitignore either so don't think the creation of the .gitattributes file needs specific mentioning either.

**Comment by teyckmans** [comment]
Opened a pull request for adding this.

**Comment by britter** [comment]
Fixed by #9585
