### ISSUE TITLE
Changes in case for input files causes Sync tasks to fail

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#9586]
On case-insensitive filesystems (Windows, macOS-sometimes), a change in the case of an input file is seen as a change, but causes `Sync` tasks to fail to populate the destination directory properly.

### Expected Behavior
Gradle syncs all input files.

### Current Behavior
Gradle does not sync the proper files.

### Steps to Reproduce 
```
task writeFile {
    def outputFile = new File(buildDir, project.hasProperty("capitalize") ? "OUTPUT" : "output")
    outputs.file outputFile
    doLast {
        outputFile.text = "hello"
    }
}
task sync(type: Sync) {
    from writeFile
    into new File(buildDir, "sync")
}
```

The first build works (`gradle sync`).
The second build with changed case (`gradle sync -Pcapitalize`) fails with an empty `build/sync` directory.

### Your Environment
Occurs on macOS (with case-insensitive filesystems) and Windows.

**Comment by big-guy** [comment]
Reproducer: https://github.com/gradle/gradle/commit/40f71954266840b45c5b75880f23c0050d45b9c1

**Comment by lptr** [comment]
I see the reproducer contains this:

```groovy
@Requires(TestPrecondition.CASE_INSENSITIVE_FS)
```

I guess the test should pass for case-sensitive file-systems, too, so this line can be removed.

**Comment by lptr** [comment]
Looks like the situation is even more complex than I initially understood: (emphasis mine)

> Windows 10 now offers an optional case-sensitive file system, just like Linux and other UNIX-like operating systems. All Windows processes will handle case-sensitive files and folders properly if you enable this feature. In other words, they’ll see “file” and “File” as two separate files.
> 
> ### How This Works
> 
> **This is an NTFS file system feature that you can enable on a per-directory basis.** It doesn’t apply to your entire file system, so you can just enable case sensitivity for specific folders you use for development purposes.

I don't think Java itself supports this level of detail, though.

**Comment by paplorinc** [comment]
Yeah, I've enabled case sensitivity for a folder, tried `File` and `Path` and they don't see it (i.e. the two file references are equal for both folders, the normal, case insensitive one, and the Linux-subsystem-enabled one).
Intellij's folder view only shows a single File.
Only PowerShell handles it correctly:
![image](https://user-images.githubusercontent.com/1841944/58973212-b06dcd00-87bf-11e9-9404-affbbaddab7e.png)

**Comment by paplorinc** [comment]
PR created: https://github.com/gradle/gradle/pull/9625

**Comment by lptr** [comment]
New PR: #9663.
