### ISSUE TITLE
Changing Case of File Leads to "cannot find symbol" Test Failure

### ISSUE THREAD

**Issue by dclements** [gradle/gradle#9593]
### Expected Behavior
The tests should pass. 

### Current Behavior

While trying to execute any test cases involving the refactored file it gave some variation of the following exception:

```
  symbol:   variable DdlTransformer
  location: class (Test Class)
(Path)/DdlTransformerTest.java:(line): error: cannot find symbol
                  DdlTransformer.transformDdl(
                  ^
  symbol:   variable DdlTransformer
  location: class AlterTableTest
```

### Context

In order to comply with a style guide I refactored (using IntelliJ) a class named `DDLTransformer` to `DdlTransform` and performed a clean build. IntelliJ did not show any reference problems. 

Deleting the caches in `~/.gradle/caches` fixed the problem. Deleting `${PROJECT_DIR/.gradle` did not, however. Nor did running without the daemon. 

Changing the name of the class entirely to `DdlTransformer2` also corrected the problem. 

### Steps to Reproduce 

1. Create a class and a set of tests against it. 
2. `./gradlew build`
3. Rename the class (using an automated refactor tool if possible) to change the case (only) in the file. 
4. run `./gradlew clean build`
5. Failure should happen here. 

### Your Environment

Gradle: 5.4.1
Operating System: macOS 10.14.5
Disk format: Apple APFS

**Comment by noproxy** [comment]
The case-insensitive  file system breaks the build cache.  Just like #4111.

The workaround is to do a clean build  by ```./gradlew build --rerun-tasks``` to force updating the build cache.

**Comment by paplorinc** [comment]
@dclements, thank you for reporting your findings.
I would need a bit more context to be able to reproduce it.
If I rename a Class, the content and the file name are changed correctly on a Mac. By running a `build` on it, everything works, as before.
If I rename the file only - and not the class -, I'm getting: ` error: class X is public, should be declared in a file named X.java`.
Could you maybe create a reproducer project?

**Comment by paplorinc** [comment]
Closing the issue because of inactivity, if you think it's still relevant, please reopen considering the above comment.
