### ISSUE TITLE
IDEA imports the Gradle project, and all the introduction of the package in a implementation way has become a Runtime

### ISSUE THREAD

**Issue by halower** [gradle/gradle#9596]
IDEA imports the Gradle project, and all the introduction of the package in a implementation way has become a Runtime
![微信截图_20190602211021](https://user-images.githubusercontent.com/4995227/58761839-0867c200-857b-11e9-9802-6b83fb1164fc.png)

build.gradle  
``` code
...
implementation ('xxxxx:xxxx:xxx')
...
```

**Comment by halower** [comment]
`IDEA version: 2018.2           Gradle version: 5.4.1`

**Comment by big-guy** [comment]
I'm not sure if you're saying that the import used to work with 4.10.3 and it no longer works in 5.4.1 or if you're saying the import hasn't worked with 4.10.3 or 5.4.1.  If you could provide a small example demonstrating the problem you're seeing, we're happy to take a look.
