### ISSUE TITLE
Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry()

### ISSUE THREAD

**Issue by udoyen** [gradle/gradle#9598]
### Expected Behavior

Create a java library project using gradle

### Current Behavior

And I get the following error: Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry() and the gradle init command fails.

### Context

I am unable to initialize a java library project in visual studio code

I am following this tutorial to create a basic java library using gradle and I had installed the required components like java, and I installed gradle and also created the gradle environmental variables such as GRADLE_USER_HOME and GRADLE_HOME and the project would not build in visual studio code on windows 10.

### Steps to Reproduce 

1. Install java sdk and gradle and add them to the windows PATH variable.
2. Open visual studio code and create a folder gradle-kotlin
3. Run the command from the vscode terminal: `gradle init --type java-library`

### Your Environment

Build scan URL:

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          12.0.1 (Oracle Corporation 12.0.1+12)
OS:           Windows 10 10.0 amd64

**Comment by big-guy** [comment]
What do you have GRADLE_USER_HOME and GRADLE_HOME set to? Failures of these kinds usually point to some sort of permission or path issue.  You don't need to set these variables usually.  Could you try running without them set?

**Comment by udoyen** [comment]
These are the values:

GRADLE_HOME                    C:\Gradle\gradle-5.4.1

GRADLE_USER_HOME               C:\Users\ekojo\mgradle

**Comment by udoyen** [comment]
The issue has been fixed as I installed the gradle file full version and not the bin version.

**Comment by orozcoadrian** [comment]
I just had the same error in AWS CodeBuild, using an `all` distribution (not `bin`). Adding `--debug --stacktrace` showed that the error was about not finding a `plexus-utils` jar. I deleted the gradle wrapper cache dir (S3) and then it worked.

**Comment by PiotrKujawa** [comment]
In my case the reason was wrong version of gradle set in distributionUrl, I edited gradle-wrapper.properties and it helped.
I also removed caches.

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-all.zip <------- changed it to the latest
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

**Comment by assafv** [comment]
This happend to me as well after recent giraffe upgrade.

**Comment by naXa777** [comment]
```
* Exception is:
org.gradle.internal.service.ServiceCreationException: Could not create service of type ClassLoaderRegistry using GlobalScopeServices.createClassLoaderRegistry().
...
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.openConnection()" because "url" is null
        at org.gradle.util.internal.GUtil.loadProperties(GUtil.java:242)
```
Gradle 8.8.

Solution: replace "bin" with "full" version.
