### ISSUE TITLE
Build scan plugin slows configuration even if not used

### ISSUE THREAD

**Issue by eugene-krivobokov** [gradle/gradle#9605]
### Expected Behavior
Build scan plugin do nothing unless scan is enabled explicitly (via --scan  or buildScan.publish... options).

### Current Behavior

```gradle
plugins {
    id "com.gradle.build-scan" version "2.3"
    // other plugins
}

buildScan {
    setTermsOfServiceUrl("https://gradle.com/terms-of-service")
    setTermsOfServiceAgree("yes")
}

// project.gradle.startParameter.isBuildScan() --> false
```
It slows configuration. I see it in profiler:

```
gradle-profiler --profile yourkit \
--project-dir . \
--warmups 1 \
--gradle-user-home ~/.gradle-profiler \
--output-dir profiler \
help
```
![Screenshot 2019-06-03 11 21 53](https://user-images.githubusercontent.com/1104540/58797481-c71df380-8608-11e9-90c9-659a5ba9bee1.png)

- Gradle 5.4.1
- MacOS 10.14.5
- JVM: 1.8.0_212 (AdoptOpenJDK)

### Context

Our current workaround:

```gradle
plugins {
   // no build scan plugin here
}

def isBuildScan = project.gradle.startParameter.isBuildScan()
if (isBuildScan) { 
    buildScan { ... }
}
```

**Comment by big-guy** [comment]
This is expected.  We can publish build scans after the fact (`gradle buildScanPublishPrevious`), so we need to capture the data all of the time. 

@ldaley FYI, if there's more information you'd like to gather here about performance.
