### ISSUE TITLE
Task execution should complete as soon as possible after submitted work is complete

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#9611]
When a task submits work items using `WorkerExecuter.submit` but does not call `WorkerExecuter.await()`, then the task is not considered complete until all submitted work items have finished. However, the task relinquishes its exclusive project lock while work items are running, allowing Gradle to run other tasks in the same project in parallel.

Once all work items are complete, the task must re-acquire the project lock in order to fire any post-execution actions. In many cases this step is not necessary, leading to delay in executing dependent tasks.

Instead, Gradle should only reacquire the project lock for task completion when post-action work may result in mutating the project state. (e.g. `TaskExecutionGraphListener`). When no post-action work is registered, Gradle should not wait for the project lock in order to mark a task as "complete".

**Comment by dsvoronin** [comment]
That's super cool! Can you please also consider to add some additional debug info to track enforced locks and reasons behind it?
