### ISSUE TITLE
在studio3.4.1使用gradle

### ISSUE THREAD

**Issue by wangxiongxu** [gradle/gradle#9629]
在运行studio时会报
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/5.1.1/userguide/gradle_daemon.html
Please read the following process output to find out more:
这个错误只有关机重新启动才能继续使用studio

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem.
