### ISSUE TITLE
Allow custom dependency notations

### ISSUE THREAD

**Issue by ethankhall** [gradle/gradle#964]
Feature Request:
I would like to be able to do something like

```
dependencies {
  compile product: 'foo', module: 'bar'
}
```

Right now I can't do that because the dependency notation processor will not know that I want to expand "product" to be something else.

**Comment by bigdaz** [comment]
We don't have any current plans to open up our dependency syntax. Instead, you can provide a function that will generate a `org.gradle.api.artifacts.Dependency` instance. We might want to make it easier to construct these instances, however.
