### ISSUE TITLE
Could not resolve all dependencies / Could not open cache directory

### ISSUE THREAD

**Issue by mtrakal** [gradle/gradle#9642]
Using Android, Gradle DSL, kotlin, about 15 modules in project.
When edit mobile.gradle.kts and/or bould-src file:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':mobile:preDevWalletDebugBuild'.
> Could not resolve all dependencies for configuration ':mobile:devWalletDebugRuntimeClasspath'.
   > A problem occurred configuring project ':modules:module-be-base'.
      > Could not open cache directory 8g4e7o9r14yfp6xevubnfguxq (C:\Users\mtrakal\.gradle\caches\5.4.1\gradle-kotlin-dsl\8g4e7o9r14yfp6xevubnfguxq).
         > org.gradle.api.internal.initialization.DefaultClassLoaderScope@7e44ec5b must be locked before it can be used to compute a classpath!
```

What help: `gradlew clean` and after again build

Steps which I do:
- `gradlew :mobile:installDevWalletDebug` (just installDebug when we didn't use flavor)
- build is OK
- edit files: `/mobile/build.gradle.kts` and `/bould-src/java/cz.bs/Config.kt`
- `gradlew :mobile:installDevWalletDebug` failed on error shown ^
- `gradlew clean`
- `gradlew :mobile:installDevWalletDebug` everything is OK

Tested with:
```
android.enableBuildCache=false / true
org.gradle.caching=false / true
kapt.incremental.apt=false / true
```
Same for both variants.

```
const val kotlinVersion = "1.3.31" // https://search.maven.org/search?q=g:org.jetbrains.kotlin
        // https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
        const val gradleBuildTools = "3.4.1" // https://developer.android.com/studio/releases/gradle-plugin

        const val gradleVersion = "5.4.1" // https://services.gradle.org/distributions/

        // https://developers.google.com/android/guides/google-services-plugin
        // https://bintray.com/android/android-tools/com.google.gms.google-services
        const val googleServicesVersion = "4.2.0"

        // version from: https://plugins.gradle.org/plugin/com.gradle.build-scan
        const val buildScanVersion = "2.3"

        val sourceCompatibility = JavaVersion.VERSION_1_8
        val targetCompatibility = JavaVersion.VERSION_1_8

        // sdk and tools
        const val compileSdkVersion = 28
        const val buildToolsVersion = "29.0.0" // https://developer.android.com/studio/releases/build-tools.html
        const val minSdkVersion = 19
        const val targetSdkVersion = 26 // https://developer.android.com/distribute/best-practices/develop/target-sdk
```

### Expected Behavior
Just normal build apk, without any error about error with dependencies. 

### Current Behavior
All dependencies are locally cached and available. Just comment / uncomment dependencies, no new one. Sometimes just update version, but it happen randomly after edit files. So dependencies are available.

Folder exists, is available and readable. 
[8g4e7o9r14yfp6xevubnfguxq.zip](https://github.com/gradle/gradle/files/3261008/8g4e7o9r14yfp6xevubnfguxq.zip)

When I just delete folder: 8g4e7o9r14yfp6xevubnfguxq still happen.
[8g4e7o9r14yfp6xevubnfguxq_created_after_delete.zip](https://github.com/gradle/gradle/files/3261017/8g4e7o9r14yfp6xevubnfguxq_created_after_delete.zip)
```
* What went wrong:
Could not determine the dependencies of task ':mobile:preDevWalletDebugBuild'.
> Could not resolve all dependencies for configuration ':mobile:devWalletDebugRuntimeClasspath'.
   > A problem occurred configuring project ':modules:module-be-base'.
      > Could not open cache directory 8g4e7o9r14yfp6xevubnfguxq (C:\Users\mtrakal\.gradle\caches\5.4.1\gradle-kotlin-dsl\8g4e7o9r14yfp6xevubnfguxq).
         > org.gradle.api.internal.initialization.DefaultClassLoaderScope@708b9301 must be locked before it can be used to compute a classpath!
```

Stacktrace: https://gist.github.com/mtrakal/312edebb9193b8e4ad88d714d48748de

Same when I build just from console and Android Studio

### Steps to Reproduce 
Edit file in /mobile/build.gradle.kts or /bould-src/java/cz/bs/Config.kt

### Your Environment
Build scan URL: https://gradle.com/s/dewpesyuadea4

**Comment by mtrakal** [comment]
What didn't help:
delete folders in project:
/.gradle
/build
/buildSrc/build
/buildSrc/.gradle (this folder shouldn't be there I think)
/modules/module-be-base/build
/mobile/.gradle (this foulder shouldn't be there I think)
/mobile/build 

~/.gradle/caches\5.4.1\gradle-kotlin-dsl\8g4e7o9r14yfp6xevubnfguxq

due to folders: /buildSrc/.gradle I think, that gradle use wrong folders in some cases...?
[buildSrc-.gradle.zip](https://github.com/gradle/gradle/files/3261081/buildSrc-.gradle.zip)

**Comment by mtrakal** [comment]
success build after clean: https://gradle.com/s/gnhvoa63lyo6a

**Comment by mtrakal** [comment]
maybe it caused freezed java processes, because sometimes (daily), I kill some java.exe which freeze in task manager, but it happen after I kill all java.exe processes too and create a new daemon, so maybe it's not possible to recover from some freeze and need to clean project completely

**Comment by bendb-instacart** [comment]
I just hit this same issue; cleaning resolved it, but what a pain.

**Comment by idlecat** [comment]
In my case, I have to set org.gradle.configureondemand to false to resolve the problem.

**Comment by sebhard** [comment]
Whenever I run into the issue, I have to perform one run without `configure on demand`. After that it works normally for a while.

**Comment by mikejhill** [comment]
This seems to be the same as #4823. Gradle currently struggles with Kotlin build scripts when using children projects with configuration-on-demand enabled.
