### ISSUE TITLE
inconsistent behaviour when overwriting startScripts task

### ISSUE THREAD

**Issue by rodney757** [gradle/gradle#965]
I have a custom task that is overwriting the Application plugin startScripts task.

When I run installDist or distZip, the default startScripts task is being run. So I made installDist and distZip dependOn "startScripts"

Now when I run installDist or distZip, 1/2 of the time my custom startScripts task runs, and the other half of the time the default startScripts task runs.

### Expected Behavior

I would except that specifying that when tasks run there dependent tasks, they would run any dependent tasks that overwrite the default tasks, falling back to the default task.

Ex. 
```
task startScripts(type: CreateStartScripts, overwrite:true) {
    classpath = files(jar.archivePath, configurations.custom + configurations.runtime)
    outputDir = file("${buildDir}/scripts")
    mainClassName = "com.my.main.class"
    applicationName = project.name

    dependsOn jar
}
```

I would expect any task that depends on startScripts (installDist, distZip) to use the custom implementation.

at the very least, adding 

```
installDist.dependsOn startScripts
```

should provide consistent behavior

### Steps to Reproduce (for bugs)

1. create a task overwriting the predefined startScripts task ex.

```
task startScripts(type: CreateStartScripts, overwrite:true) {
    classpath = files(configurations.runtime)
    outputDir = file("${buildDir}/scripts")
    mainClassName = "com.my.main.class"
    applicationName = project.name

    dependsOn jar

    doLast {
        println "within custom startScripts task
    }
}
```

2. run "gradle installDist"

### Your Environment

 * Build scan URL: 

https://gradle.com/s/xplalqt7kqu7u

**Comment by eriwen** [comment]
@rodney757 Thanks for the report. I think I have some idea how to reproduce this issue given your description, but could you spell it out for us in the issue? 

Is this the project being built? https://github.com/biocodellc/dipnet-fims

Do you typically work around this by running the build multiple times?

**Comment by rodney757** [comment]
@eriwen wrote the steps to reproduce.

that is the project

yes, I run the build until the custom task runs

**Comment by bmuschko** [comment]
@rodney757 Could you please explain the purpose of wanting to overwrite the `startScripts` task? Is the reason that you want to change one of it's properties e.g. point to custom scripts? I am pretty confident that you don't need to overwrite the task as you did.

What's the reason for applying the `application` plugin to the root project in a multi-project build? I would not expect the root project to produce an application - rather one of the sub projects.

BTW: I couldn't reproduce the issue in your build as 1) the Wrapper files do not include a properties file and 2) the build doesn't seem to work with 3.2.

**Comment by rodney757** [comment]
@bmuschko The reason for overwriting the startScripts class is that I wanted to modify the classpath. 

The rootProject and the subProjects all have a custom configuration "server". In the startScripts task I add all the subProject.configuration.server dependencies to the rootProject

```
subprojects.each { subproject ->     
 project.configurations.server.dependencies.addAll(subproject.configurations.server.dependencies)
 }
```

then I add the jar and all dependencies to the classpath

```
classpath = files(jar.archivePath, configurations.server, configurations.runtime)
```

The subProjects are common code bases shared between multiple rootProjects. 

So the rootProject is really the main application. Maybe there is a better way to organize our build?

I can give you a properties file, however you would also need to co 2 additional repos from that organization to be able to build the project. Let me know if you want the properties file

**Comment by bmuschko** [comment]
You don't need to overwrite the task. Instead you can simply change the property `classpath` of the existing `startScripts` task.

    startScripts {
        classpath = files(jar.archivePath, configurations.server, configurations.runtime)
    }

> So the rootProject is really the main application. Maybe there is a better way to organize our build?

I'd probably set up a new subproject that is just responsible for building the application. That would make the root project cleaner.

**Comment by rodney757** [comment]
that worked. Thanks!
