### ISSUE TITLE
Subproject uses wrong transitive dependency, if dependency is defined in root project

### ISSUE THREAD

**Issue by neworld** [gradle/gradle#9650]
### Expected Behavior

I am expecting subproject to use dependency's version as required in the subproject

### Current Behavior
Some dependencies are in the wrong version and crash build process

### Steps to Reproduce 

The easiest way to reproduce using my repo: https://github.com/neworld/quickstart-android
```
git clone git@github.com:neworld/quickstart-android.git
cd quickstart-android/perf
./gradlew assembleDebug
```

Gradle will be a success, but you will see many stacktraces like:
```
Can't instrument: com/bumptech/glide/load/data/DataFetcher.class                                      
java.lang.IllegalArgumentException                                                                                                                                                                                  
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:79)                                                                                                                                              
        at com.google.firebase.perf.plugin.instrumentation.InstrumentationVisitor.<init>(InstrumentationVisitor.java:55)                                                                                            
        at com.google.firebase.perf.plugin.instrumentation.Instrument.instrument(Instrument.java:170)                                                                                                               
        at com.google.firebase.perf.plugin.instrumentation.Instrument.instrumentClassesInJar(Instrument.java:117)                                                                                                   
        at com.google.firebase.perf.plugin.FirebasePerfTransform.performTransformationFor(FirebasePerfTransform.java:439)
```

The crash happens, because `app` subproject is using ASM 6.0.

### More info

```
./gradlew buildEnvironment
<...>
|    +--- com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta04                                
|    |    +--- org.ow2.asm:asm:6.0                                                                                                                                                                                  
|    |    +--- org.ow2.asm:asm-util:6.0 (*)                                                               
|    |    +--- org.ow2.asm:asm-commons:6.0 (*)
```

```
./gradlew app:buildEnvironment
------------------------------------------------------------
Project :app
------------------------------------------------------------

classpath
\--- com.google.firebase:perf-plugin:1.2.1
     \--- org.ow2.asm:asm:7.0
```

However, task `:app:transformClassesWithFirebasePerformancePluginForDebug` is still using `org.ow2.asm:asm:6.0`

### Workaround

Define classpath of `com.google.firebase:perf-plugin:1.2.1` in root project, as [in the original implementation](https://github.com/firebase/quickstart-android)

**Comment by ljacomet** [comment]
The `classpath` configuration of Gradle is what defines the libraries used by _the build itself_.
If there is a version issue when running a build task, you need to figure out where `:app:transformClassesWithFirebasePerformancePluginForDebug` sources its dependencies from and possibly update the `asm` dependency in the matching configuration.

This is very unlikely to be a core Gradle issue but might be a firebase plugin issue or an Android issue.

**Comment by neworld** [comment]
I don't know how to explain, but I will try my best. `perf-plugin` is using `org.ow2.asm:asm:7.0` as dependency and it is defined in `pom.xml` file. Source code of `InstrumentationVisitor.java` should look like:
```java
public class InstrumentationVisitor extends org.objectweb.asm.ClassVisitor {
   public InstrumentationVisitor(final org.objectweb.asm.ClassVisitor classVisitor, final InstrumentationConfig instrConfig) {
      super(458752, classVisitor); //crash happens here, because old ClassVisitor do not support v7 api
      this.classVisitor = classVisitor;
      this.instrConfig = instrConfig;
   }
```

It is just regular extension of the class from lib. There is no dynamically class loaders or custom dependency management. Just trust that `Gradle` will load proper classes as defined in the pom file.

Maybe I am wrong?
