### ISSUE TITLE
Allow customisation of plugin version per plugin declaration

### ISSUE THREAD

**Issue by roefunc** [gradle/gradle#9652]
It's currently possible to publish multiple plugins with different IDs and implementation classes from one project. However, each plugin has to have the same version because the plugin declaration doesn't have a version option.

### Expected Behavior
Allow specifying a version per plugin. e.g.
```
gradlePlugin {
  plugins {
    pluginOne {
      id = 'pluginOne'
      implementationClass = plugin.impl
       version = '1.0'
    }
    pluginTwo {
       id = 'pluginTwo'
       implementationClass = plugin.impl
       version = '2.0'
    }
}
```
### Context
I have a plugin with two target audiences with different release cadences. I could split the code out into a library and create two separate projects depedending on the library, but that would lead to duplication of build config etc.

**Comment by big-guy** [comment]
I think our advice would be to split this into multiple projects if they need to be released/versioned separately.

There aren't two separate jars being published when everything is in a single project, so it wouldn't be possible to mix different versions of pluginOne and pluginTwo.
