### ISSUE TITLE
How can I represent a read/write input file?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9658]
I have some state I need to save across builds, meaning I need to read the value in the file and also write it when creating the state. `@Destroys` seems like a good candidate, but my task has other inputs/output so that won't work b/c it's not allowed for whatever reason. And my concern with `@LocalState` is that it doesn't create an exclusive lock on the file across tasks. If two tasks were to run in parallel because of Gradle workers or different projects etc, I might end up in a nasty race condition.

Does `@LocalState` do the proper file locking to fit my use case?

**Comment by lptr** [comment]
Yes. Gradle will prevent scheduling two tasks to run at the same time if they have overlapping outputs declared. The outputs here include `@LocalState`, too.

https://github.com/gradle/gradle/blob/d35b309b56963f75f6c378c59d4a95e39a647ed7/subprojects/core/src/main/java/org/gradle/execution/plan/DefaultExecutionPlan.java#L719-L721

**Comment by SUPERCILEX** [comment]
Woohoo, awesome!
