### ISSUE TITLE
Files with unicode filenames may fail to be extracted or copied depending on system locale

### ISSUE THREAD

**Issue by jakegt1** [gradle/gradle#9665]
### Expected Behavior
File extracts normally.

### Current Behavior
File fails to extract saying "cannont expand zip.":
Caused by: net.rubygrapefruit.platform.NativeException: Could not set UNIX mode on /tmp/folder/build/製品カテゴリ.xlsx: could not convert string to current locale

### Context
This does not work in 5.4.1, but there is no issue in 5.1.
I am simply trying to unzip a zip file that includes a file with a unicode filename.

### Steps to Reproduce 
I am going to note that something to do with system locale/JVM options can make this work or not work. I do not know what needs to change to make this work, but i will note that you can cause this to fail in an oraclelinux:6 docker image.

[bug.zip](https://github.com/gradle/gradle/files/3271823/bug.zip)

### Your Environment
Locale:  (i will note i have tried this with en_US-utf-8 too)
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

**Comment by jakegt1** [comment]
Additional note - on 5.4.1, i cannot get this to work at all. On 5.1, i can get this to work if i set the system locale to en_US.utf-8.

**Comment by jakegt1** [comment]
Hmm.. im going to close this issue for now as i cannot find a proper way of reproducing this. It may be some funky environment going on, but i thought i could reproduce it but now I don't seem to be able.

It's unsurprising for it to fail with the POSIX locale, but it seems something else is happening.. i'll see if i can figure it out then get back.

**Comment by lukebemish** [comment]
This appears to still be an issue; my system locale is `en_US.UTF-8` and I am noting the same failure on gradle 8.7 when attempting to move, copy, zip, or delete files with certain unicode in the path through gradle.
