### ISSUE TITLE
Check usage of incrementalInputFileChanges with rebuild enabled in DefaultExecutionStateChangeDetector

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9667]
We can probably avoid calculating these if rebuild is requested:

https://github.com/gradle/gradle/blob/master/subprojects/execution/src/main/java/org/gradle/internal/execution/history/changes/DefaultExecutionStateChangeDetector.java#L67-L71

**Comment by wolfs** [comment]
Closing since https://github.com/gradle/gradle/pull/9732 has been merged.
