### ISSUE TITLE
Classifier gets ignored

### ISSUE THREAD

**Issue by stefanleh** [gradle/gradle#9668]
When using Gradle 5.4.1 and the dependecy aspose-email, which needs a classifier, i get an error message.

### Expected Behavior
Dependency should be downloaded and added to classpath.

### Current Behavior
Dependendy does not get downloaded and added to classpath.

### Context
This works with Gradle 5.2.
I cant build any more with 5.4.1.

#### General

     repositories {
          maven {
              url 'https://artifact.aspose.com/repo/'
          }
      }

     dependencies {
		compile YOUR_DEPENDENY
     }

#### in Dependency

     dependencies {
		compile group: 'com.aspose', name: 'aspose-email', version: '19.4', classifier: 'jdk16', ext: 'jar'
     }

	* What went wrong:
	Execution failed for task ':compileJava'.
	> Could not resolve all files for configuration ':compileClasspath'.
	> Could not find aspose-email.jar (com.aspose:aspose-email:19.4).
		Searched in the following locations:
			http://nexus.dev.oxaion.local/repository/maven-all/com/aspose/aspose-email/19.4/aspose-email-19.4.jar

### Your Environment
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Windows 10 10.0 amd64

**Comment by ljacomet** [comment]
With the following build script, this works as expected:
```
plugins {
    `java-library`
}

repositories {
    maven {
          url = uri("https://artifact.aspose.com/repo/")
      }
}

dependencies {
    implementation(mapOf("group" to "com.aspose", "name" to "aspose-email", "version" to "19.4", "classifier" to "jdk16", "ext" to "jar"))
}

tasks.create("printIt") {
    doLast {
        println(configurations.compileClasspath.files)
    }
}
```
as it prints text that contains `/.gradle/caches/modules-2/files-2.1/com.aspose/aspose-email/19.4/b4c3db12a0b206dec9762ea46de1eb54c0322702/aspose-email-19.4-jdk16.jar`

So there is something else in your setup that makes this break.
Please try to create a reproducer for your problem.

**Comment by stefanleh** [comment]
Yes, sorry about the initial description. We have aspose-email as transitional dependency in one of our depedencies - not directly in the project. I will post an update when i've checked if adding "ext: 'jar'" in the dependecies block of the used dependency works.

**Comment by stefanleh** [comment]
Adding "ext: 'jar'" to the dependency we use in the project helped.
The problem was that there is no default jar of aspose-email, only special versions like 'jdk16' and 'android.via.java.jar' and as transitive dependency this seems to be a problem.
Was there any change in how transitive dependencies are managed between 5.2 and 5.4.1?

**Comment by ljacomet** [comment]
There should not have been any change affecting the scenario you describe.

Can you elaborate on how is the transitive dependency graph declared? Is it between projects? With a Maven POM file in between? Something else?

I tried reproducing the issue in a multi-project but the dependency is found, whether or not it is declared with `ext: 'jar'`.

**Comment by stefanleh** [comment]
I've created https://github.com/stefanleh/9668-base and https://github.com/stefanleh/9668-proj.
After publishing the base artifact to mavenLocal i've tried building the proj and it was successful using the same JDK and Gradle versions (even using our own nexus instance as proxy instead of the official repo)
Therefore my issue was'nt reproduceble using demo projects.

Sorry for wasting your time.
