### ISSUE TITLE
Allow Codenarc Plugin to generate and exclude baseline violations

### ISSUE THREAD

**Issue by dforegger** [gradle/gradle#9679]
### Expected Behavior
The codenarc plugin supports [baseline reports](http://codenarc.sourceforge.net/codenarc-BaselineXmlReportWriter.html) to allow legacy codebases to ignore old violations and look for new ones. The gradle configuration should allow:
- report format of `baseline` which produces the standard codenarc baseline report
- a config property of `excludeBaseline` which accepts a baseline report and passes it to the codenarc runner

### Current Behavior
Currently the only output formats are Xml, Html, Text, and Console. It is not possible to ignore prior codenarc violations

### Context
We are re-evaluating our code standards and moving them into a common repository. Cleaning up failures will take a significant amount of time, and we plan to establish current baselines so we can fix them as we modify the surround code.
We use codenarc in grails 2 and grails 3 projects. With the grails 2 plugin we've been able to set-up the baseline reports, but using gradle for the grails 3 builds is preventing us from taking this approach.

**Comment by sacardoz** [comment]
Hello, did you find any solution?
