### ISSUE TITLE
setAppendix deprecated, doc's suggested alternative is a getter

### ISSUE THREAD

**Issue by dpkirchner** [gradle/gradle#9694]
### Expected Behavior

Use of the deprecated setAppendix in a build.gradle file should suggest using an alternative method (in IntelliJ IDEA and other IDEs), but more importantly it should suggest a setter.

### Current Behavior

setAppendix is marked as deprecated without an alternative in the IDE. The documentation says to use a getter, getArchiveAppendix:

https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#setAppendix-java.lang.String-

### Context

I was trying to set the appendix for an archive, so the output would have a particularly formatted name.

### Steps to Reproduce 

A full project is infeasible but you can reproduce this by adding this to your groovy build.gradle file:

    jar {
      setAppendix("foo")
    }

### Your Environment

    ------------------------------------------------------------
    Gradle 5.4.1
    ------------------------------------------------------------

    Build time:   2019-04-26 08:14:42 UTC
    Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

    Kotlin:       1.3.21
    Groovy:       2.5.4
    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
    JVM:          1.8.0_212 (AdoptOpenJDK 25.212-b03)
    OS:           Mac OS X 10.14.5 x86_64

**Comment by ljacomet** [comment]
The recommendation is correct, Gradle is moving to using `Property` types in a lot of places to allow for more laziness when configuring / evaluating.

The method `getArchiveAppendix()` returns a `Property<String>` that can be set.
In Groovy, thanks to the dynamic aspect, you can do:
```
jar {
    archiveAppendix = "foo"
}
```

In Kotlin, you have to do:
```
jar {
    archiveAppendix.set("foo")
}
```
