### ISSUE TITLE
Better INFO logging for cache hits

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9698]
It is useful to see in the `INFO` log to when there is a cache hit. We do this in a way already by logging about the unpacking here:

https://github.com/gradle/gradle/blob/9682f45ca827e0fceef51e284e72fa1bea0b16cf/subprojects/build-cache-packaging/src/main/java/org/gradle/caching/internal/command/BuildCacheCommandFactory.java#L96

We should add an explicit `INFO` log saying something about a cache hit, and turn the above log into a `DEBUG` level one.

**Comment by wolfs** [comment]
The PR has been merged.
