### ISSUE TITLE
Add support for launching the Gradle daemon with niceness

### ISSUE THREAD

**Issue by mcumings** [gradle/gradle#9706]
### Expected Behavior

I'd like the ability to have the Gradle daemon launches with a niceness value so that I can set the process priority.

### Current Behavior

Currently, the process is forked and inherits the process priority from the parent.

### Context

As our builds become increasingly parallelized, system utilization becomes completely saturated for long periods of time.  On developer workstations this can end up starving out system resources and make developer interaction with the overall system sluggish.  By way of example, browser interactions can become extremely slow while a build is proceeding.  Granted, this effect will vary from OS to OS.  My specific example is from a MacBook Pro.

It would be nice to be able to set a gradle property to enable gradle to launch the daemons in a de-prioritized mode, preserving responsiveness of other applications while still allowing the build to proceed.

As a workaround, I created a script which continually calls renice on all gradle processes.  If I launch that in a loop then I can achieve better overall system responsiveness at the expense of build time.

**Comment by big-guy** [comment]
This was added partially in 5.0: https://github.com/gradle/gradle/issues/1606

https://docs.gradle.org/current/userguide/build_environment.html#header

Setting `org.gradle.priority=low` will start the daemon with a niceness of +10.

Can you give this a try and see if this meets your needs?
