### ISSUE TITLE
Handle dangling symlinks in outputs for incremental build

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9708]
When snapshotting we sometimes fail if we encounter a dangling symlink.
We want to change this, and treat a dangling symlink as if we encountered a missing file.
In an incremental build, if the dangling symlink becomes a non-dangling one (or vice versa), we consider that a change similar to changing a file into a directory.

* [ ] task produces output (as output file/in output directory) with a dangling symlink
  * [x] should succeed (fails currently)
  * [x] should be up-to-date without changes
  * [x] changing the output to a non-dangling symlink makes the task output out of date (should track Missing files in Snapshots/Fingerprints)

**Comment by paplorinc** [comment]
Question about two statements that need clarification:
> dangling symlink as if we encountered a missing file

and

> we need an incremental task variant of the test where we check that this change is properly reported as MODIFIED

It seems to me that if a file is deleted and added back, it's not marked as modified, but as removed and added. Is that behavior okay for broken links as well?

**Comment by lptr** [comment]
> It seems to me that if a file is deleted and added back, it's not marked as modified, but as removed and added. Is that behavior okay for broken links as well?

Yes, that seems correct.

**Comment by paplorinc** [comment]
Thanks, edited the issue to reflect this change.

**Comment by paplorinc** [comment]
What should happen during file listing (e.g. `project.files`, `project.fileTree`, [etc](https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/file/FileCollectionSymlinkIntegrationTest.groovy#L45)) for broken links? Should we just logger.warn and ignore them?

**Comment by lptr** [comment]
Good question. Can we keep the current behavior and still fix incremental build, or is it a must that we change the behavior of `contains()` as well?

**Comment by paplorinc** [comment]
I think so, since currently it seems to me that we're asserting the exact opposite of the issue, i.e. that copy should fail if it encounters broken links, see:
- https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CopyErrorIntegrationTest.groovy#L73

- https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildSymlinkHandlingIntegrationTest.groovy#L134

- https://github.com/gradle/gradle/blob/master/subprojects/files/src/testFixtures/groovy/org/gradle/api/internal/file/collections/AbstractDirectoryWalkerTest.groovy#L168

**Comment by lptr** [comment]
That seems to make sense indeed. Let's continue accordingly.

**Comment by paplorinc** [comment]
Rekated: https://github.com/gradle/gradle/pull/9746#issuecomment-503921077:
> Let's add the following tests:
>
> - successfully execute a task with a dangling symlink already existing in its output directory (overlapping outputs will be present)
> - successfully execute a task that produces a dangling symlink in its output directory
> - fail a task with a `@Classpath` input containing a dangling symlink as a root element
>  - same with `@CompileClasspath`
> - fail a task with a `@Classpath` input containing a dangling symlink as a `.class` file in a directory
>  - same with `@CompileClasspath`

**Comment by paplorinc** [comment]
Reminders:
- [ ] Try a task with broken inputs which doesn’t have any sources (nothing annotated with `@SkipWhenEmpty`)?
- [ ] only ignore root missing files
- [ ] https://github.com/gradle/gradle/pull/8417#issuecomment-501592668
