### ISSUE TITLE
Java plugin is not idempotent

### ISSUE THREAD

**Issue by SurenNihalani** [gradle/gradle#9712]
### Expected Behavior

If a plugin of mine applies java plugin again, it would work because we expect plugins to be idempotent.
### Current Behavior

However when you apply java plugin twice, it causes an issue:
```   > Cannot add task 'javadocJar' as a task with that name already exists.```
### Context

I am trying to use a company internal plugin and that applies java and then I am trying to adapt an open source project that also applies the plugin java.

### Your Environment

Build scan URL:

**Comment by big-guy** [comment]
Can you provide an example where the Java plugin is able to be applied twice?  Gradle plugin application should be idempotent.

**Comment by ljacomet** [comment]
Furthermore, the `java` plugin _does not_ create a `javadocJar` task, so this is coming from another plugin.

**Comment by SurenNihalani** [comment]
yes, you are right. It was a different plugin. Closing this out! Sorry for the false alarm.
