### ISSUE TITLE
org.gradle.internal.os.OperatingSystem.current().isFreeBSD() doesn't exist

### ISSUE THREAD

**Issue by yurivict** [gradle/gradle#9714]
This code
```
        if (!(org.gradle.internal.os.OperatingSystem.current().isLinux() 
                || org.gradle.internal.os.OperatingSystem.current().isFreeBSD()
                || org.gradle.internal.os.OperatingSystem.current().isMacOsX())) {
```
Fails:
```
> No signature of method: org.gradle.internal.os.OperatingSystem$FreeBSD.isFreeBSD() is applicable for argument types: () values: []
```

```org.gradle.internal.os.OperatingSystem.current().isFreeBSD()``` needs to be replaced with ```org.gradle.internal.os.OperatingSystem.current().getName().contains("FreeBSD")``` instead for it to work.

However, https://docs.gradle.org/current/javadoc/org/gradle/nativeplatform/platform/OperatingSystem.html says that ```isFreeBSD()``` should be available.

gradle-5.0 on FreeBSD 12

**Comment by blindpirate** [comment]
We've seen some unofficial distribution on FreeBSD if I remember correctly. Can you please clarify how did you install Gradle 5.0 on your FreeBSD? It would be great if you can paste `gradle -v` output here.

**Comment by yurivict** [comment]
gradle is installed from the package ```pkg install gradle```.

```
$ gradle -v

Welcome to Gradle 5.0!

Here are the highlights of this release:
 - Kotlin DSL 1.0
 - Task timeouts
 - Dependency alignment aka BOM support
 - Interactive `gradle init`

For more details see https://docs.gradle.org/5.0/release-notes.html


------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_212 (Oracle Corporation 25.212-b04)
OS:           FreeBSD 12.0-STABLE amd64
```

**Comment by big-guy** [comment]
You're looking at two different types with the same name.  The internal API doesn't have a isFreeBSD method. It's best you don't use org.gradle.internal types as they can change without warning.
