### ISSUE TITLE
Dependency exclusion in 5.5-rc-3 is sometimes broken

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#9718]
I stumbled upon a weird regression regarding dependency exclusion, which is _mostly_ (not always) reproducible. But I managed to create a project to reproduce the issue.

The dependency module `slf4j-log4j12` is excluded in the build script.
However with 5.5-rc-3, in _many_ but not all Gradle runs, `slf4j-log4j12` is *not* excluded.

5.5-rc-2 and 5.4.1 work fine.

Steps to reproduce:

1. Extract the attached tarbal
1. Run the shell script in the tarball. It exercises 30 times against version 5.5-rc-3, 5.5-rc-2 and 5.4.1

Removing the two `exclude`s in `fails-to-exclude.build.gradle`, that don't have a `group` attribute, reduces the probability of the the issue to happen. So it seems, that the issue has something to do with partly defined `exclude`s (missing `group` attribute).

I've seen, that there are a bunch of changes in 5.5-RC-3 in the code area handling exclusions, so those probably cause this issue.

`--parallel` (or `--no-parallel`) doesn't change the behavior.

[5.5-rc-2-3-dependency-regression.tar.gz](https://github.com/gradle/gradle/files/3294190/5.5-rc-2-3-dependency-regression.tar.gz)

**Comment by melix** [comment]
Thanks for the reproducer, I'm looking into it.

**Comment by snazy** [comment]
Thanks for the fix, @melix !
