### ISSUE TITLE
 typo from installDebug

### ISSUE THREAD

**Issue by zusinShinpei** [gradle/gradle#9719]
### Expected Behavior

![image](https://user-images.githubusercontent.com/32737669/59572655-93070000-90e9-11e9-9599-5543af5c1458.png)

### Current Behavior

permision to permission

### Your Environment

Build scan URL:

**Comment by blindpirate** [comment]
Thanks @zusinShinpei would you like to provide a PR?

**Comment by zusinShinpei** [comment]
I cannot find that file Sorry @blindpirate

**Comment by blindpirate** [comment]
No worries. Thanks!

**Comment by big-guy** [comment]
Closing this since it's part of the Android plugin.  Their issue tracker is https://source.android.com/source/report-bugs

**Comment by zusinShinpei** [comment]
> Closing this since it's part of the Android plugin. Their issue tracker is https://source.android.com/source/report-bugs

it`s gradlew part
