### ISSUE TITLE
Substituted dependencies in composite builds

### ISSUE THREAD

**Issue by vRallev** [gradle/gradle#972]
The [restriction](https://docs.gradle.org/current/userguide/composite_builds.html#included_builds) section of composite builds mentions that substituted libraries must not itself be a composite build. Is this only a temporary limitation and will be resolved in the future or not? I'm asking because it makes testing hard if you have a dependency `Lib A -> Lib B -> App` and you want to test changes from `Lib A` in `Lib B` and `App` at the same time. 

### Expected Behavior
My expectation is that substituted libraries can be composite builds and that libraries are shared.

### Current Behavior
The same can be achieved by including the project directly like the following. Imagine you have the dependency graph `Lib A -> Lib B -> App` where `App` requires both `Lib A` and `Lib B`. Then I can add in `settings.gradle` the projects like
```groovy
include 'lib-A'
project(':lib-A').projectDir = new File('../lib-a/library')

include 'lib-B'
project(':lib-B').projectDir = new File('../lib-b/library')
```

The problem now is that I have to replace the dependency manually, e.g. in Lib B:
```groovy
//compile 'aaa:lib-A:1.2.3'
compile project(':lib-A')
```

And the app
```groovy
//compile 'aaa:lib-A:1.2.3' 
//compile 'aaa:lib-B:1.2.3'
compile project(':lib-B') // only reference B and not A
```

Then everything works as expected. Will this issue be addressed in Gradle itself?

**Comment by big-guy** [comment]
I think you may have misunderstood the restriction.

If you had separate builds for `libA`, `libB`, `appA`, and `appB`. And `libA` <- `appA` (appA uses libA) and `libA` <- `libB` <- `appB` (appB uses libB which uses libA). If you created two composites (one with `libA` and `appA` called `compositeA` and one with `libB` and `appB` called `compositeB`), you could not create a third composite that combined compositeA and compositeB.

You *can* create a single composite with all of them and it'll just work (without having to manually replace projects/dependencies).

**Comment by vRallev** [comment]
Thanks for the feedback. Yes, I'm aware of that. But my example I gave can't be achieved. `Lib B` depends on `Lib A`. `App` depends on both libraries. Then `Lib B -> Lib A` is `composite1` and `App -> Lib B` is `composite2`. That's supported, correct? My workaround helps, but is a lot harder to maintain.

**Comment by big-guy** [comment]
No, you can't include two builds that have included builds themselves.

So if libB has:
```
dependencies {
   compile 'org:libA:1.0'
}
```

And App has:
```
dependencies {
   compile 'org:libA:1.0'
   compile 'org:libB:1.0'
}
```

You could have all three in a composite with:
```
includeBuild("../lib-b")
includeBuild("../lib-a")
includeBuild("../app")
```

No need to change the dependencies in any build.

**Comment by vRallev** [comment]
I just had the "aha-moment". It's only necessary to declare the composite build in the very last project (the app in my example). I also declared the substitution in `Lib B`. But that's not necessary, because Gradle notices changes in `Lib A` and rebuilds `Lib B`. I thought that requires declaring the substitution in `Lib B`.

Thanks a lot for the quick help. That saved me a ton of time!

**Comment by big-guy** [comment]
No problem, thanks for asking.
