### ISSUE TITLE
Android databinding: lifecycleOwner is no longer accessible in Gradle 5.5-RC3

### ISSUE THREAD

**Issue by bohsen** [gradle/gradle#9720]
I have this snippet of code in my one fragments to get my view binding:
```kotlin
class ExaminationDetailFragment : BaseFragment(), ExaminationContract.DetailsView {

    override val layoutResId: Int
        get() = R.layout.fragment_examination_details

    private lateinit var binding: FragmentExaminationDetailsBinding
    @Inject lateinit var detailsPresenter: ExaminationContract.DetailsPresenter
    @Inject lateinit var viewModelFactory: ViewModelProvider.Factory

    override val viewModel: ExaminationViewModel by activityViewModels { viewModelFactory }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = DataBindingUtil.inflate<FragmentExaminationDetailsBinding>(
            inflater, layoutResId, container, false).apply {
            viewmodel = viewModel 
            isLandscapeMode = resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE
            viewlistener = detailsPresenter
            lifecycleOwner = viewLifecycleOwner
        }
        return binding.root
    }
...
```

Here I initialize my `ViewBinding` and set some variables for use in my layout xml. Lastly I set my lifecycleOwner. But when I upgrade to 5.5-rc3. `lifecycleOwner` no longer gets resolved.

![Skærmbillede 2019-06-17 kl  11 00 39](https://user-images.githubusercontent.com/355452/59591909-3a3a6600-90ef-11e9-8ebe-c797ae853419.png)

### Expected Behavior
`lifecycleOwner` should get resolved and it should be possible in a `Fragment` to set it to the `viewLifecycleOwner`.

### Current Behavior
`lifecycleOwner = viewLifecycleOwner` no longer gets resolved.

### Context
Stopped working with 5.5.-rc3. Worked in 5.5-rc2.

### Steps to Reproduce 
1. Create an Android Project
2. Add an `Activity` that uses a `Fragment` to display it's UI
3. Create a layout file that uses databinding for the `Fragment`
4. Initialize the `Fragment` in `onCreateView()` and set a `lifecycleOwner` to the `binding`

4 is not possible as the `lifecycleOwner`doesn't resolve.

### Your Environment
Android Studio 3.6 Canary 3
Build #AI-191.7141.44.36.5618338, built on May 30, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

gradle_plugin_version = '3.6.0-alpha03'
androidx_core_version = '1.2.0-alpha02'
androidx_activity_version = '1.0.0-beta01'
androidx_fragment_version = '1.1.0-beta01'
androidx_recyclerview_version = '1.1.0-alpha06'
androidx_coordinatorlayout_version = '1.1.0-beta01'
androidx_lifecycle_version =  '2.2.0-alpha01'

**Comment by bohsen** [comment]
[Gradle build scan](https://scans.gradle.com/s/xt53rnnpvjfgg/plugins)

**Comment by ljacomet** [comment]
Do you have an error when running your build or simply an error in the IDE view?
If there is an error when running the build, could you provide a build scan that shows it?

**Comment by bohsen** [comment]
I actually can't reproduce the problem on my laptop. I'll look into it when I'm back at my desktop computer at work tomorrow morning.

**Comment by lptr** [comment]
This sounds more like something to do with a change in the Android Gradle plugin, though there doesn't seem to be any recent changes in AGP around the code involved here either.

**Comment by ljacomet** [comment]
One check you could do is verify that the classpath did not change between Gradle 5.5 RC2 and RC3, #9718 is a regression that affected the later and which can impact dependency resolution.

**Comment by lptr** [comment]
@bohsen would it be possible for you to create a small reproducer project that you could post here?

**Comment by bohsen** [comment]
@lptr [Reproducer](https://github.com/bohsen/android-databinding) - at least on my computer.

> This sounds more like something to do with a change in the Android Gradle plugin, though there doesn't seem to be any recent changes in AGP around the code involved here either.

Haven't changed AGP version recently.

**Comment by bohsen** [comment]
> verify that the classpath did not change between Gradle 5.5 RC2 and RC3

Can you point me to how to do this? Not a Gradle expert.

**Comment by bohsen** [comment]
I'm seeing very strange behavior. Two classes with very similar contents. One class resolves the `lifecycleOwner` the other one doesn't.

![Skærmbillede 2019-06-18 kl  08 55 33](https://user-images.githubusercontent.com/355452/59659643-e8551700-91a6-11e9-9ca0-30eb2c440f12.png)

**Comment by bohsen** [comment]
@big-guy Seems to work.

With 5.5-RC3
![Skærmbillede 2019-06-19 kl  08 16 34](https://user-images.githubusercontent.com/355452/59741237-b4432a00-926a-11e9-8003-3cf52d29d8fd.png)

With nightly build:
![Skærmbillede 2019-06-19 kl  08 16 58](https://user-images.githubusercontent.com/355452/59741251-c02eec00-926a-11e9-9dc7-21806665f77c.png)

**Comment by big-guy** [comment]
A RC4 that fixes this will be going out today.

**Comment by drosztmer** [comment]
You should convert you layout to databinding first
