### ISSUE TITLE
failOnVersionConflict does not work fine with dependency constraints

### ISSUE THREAD

**Issue by rupebac** [gradle/gradle#9722]
I have been several hours trying to understand what is happening behind the hood, but I still do not understand why this simple case does not work.

Here is a reproducible sample that I managed to isolate:

https://github.com/rupebac/gradle_bug

If you try to configure that project you get: 

```
Conflict(s) found for the following module(s):
  - com.google.code.findbugs:jsr305 between versions 3.0.2 and 2.0.0
```

But, as you can see `jsr305` is set as a dependency constraint with `force=true` on `:platform`

The weird thing is, that as you can see, `:app` depends on `:lib`, which in fact is an empty project with no dependencies, if I remove this dependency, problem is gone.

If I comment out `failOnVersionConflict()`, then obviously it is fine, and in fact `jsr305` seems to be forced properly to whatever version I specify in the platform (even if it is the lowest).

If I force the version in a configuration rule, then it is fine.

### Expected Behavior
failOnVersionConflict() should honour dependency constraints, and not complain if a transitive dependency is forced there.

### Current Behavior
failOnVersionConflict() complains even though the dependency constraint is forced and resolved properly

### Your Environment
Gradle 5.4.1

**Comment by ljacomet** [comment]
You `app` project declares a dependency on `com.netflix.hystrix:hystrix-core`, version `1.3.18` sourced from the platform, which itself has a dependency on `com.google.code.findbugs:jsr305:2.0.0` which is indeed a version conflict with your platform declaration that forces `3.0.2`.

`failOnVersionConflict` really is about flagging _any_ version conflict in your graph. Platform and constraints are not special in its presence, they also count as version declarations and thus can cause version conflicts. If you want to run with `failOnVersionConflict` in your project, you have to make sure that there will be no version disagreement _anywhere in the whole dependency graph_.

For that the whole set of [metadata / substitutions and other tools](https://docs.gradle.org/5.4.1/userguide/customizing_dependency_resolution_behavior.html) are at your disposal.

**Comment by rupebac** [comment]
> You `app` project declares a dependency on `com.netflix.hystrix:hystrix-core`, version `1.3.18` sourced from the platform, which itself has a dependency on `com.google.code.findbugs:jsr305:2.0.0` which is indeed a version conflict with your platform declaration that forces `3.0.2`.

yes, this I saw already. But, why setting a constraint `jsr305` on 3.0.2 in the same platform (specially with `force=true`) does not solve the issue?

**Comment by ljacomet** [comment]
It is a definition issue. `failOnVersionConflict` will _fail for every conflict_ and in Gradle a _version conflict_ happens anytime more than a single version for a dependency enters the graph.

So what you did in your platform works for setting the version you want, but it _also_ introduces a _version conflict_ as per the Gradle definition.

**Comment by rupebac** [comment]
ok, clear now. Thanks for the quick clarification.

Another question. [Here](https://github.com/gradle/gradle/issues/947#issuecomment-372315498) @oehme mentions that the long term strategy is to get rid of resolution rules. This is why I wanted to avoid using resolution rules (also because there is no native why to reuse them within composite builds), but then, there is no alternative now, right?

**Comment by ljacomet** [comment]
You can use [a `ComponentMetadataRule`](https://docs.gradle.org/5.4.1/userguide/customizing_dependency_resolution_behavior.html#sec:component_metadata_rules) to amend the metadata of `hystrix-core`.
It is a preferred solution because it is more targeted.

**Comment by ljacomet** [comment]
Closing as clarification has been communicated.
