### ISSUE TITLE
Tasks without outputs shouldn't be up-to-date

### ISSUE THREAD

**Issue by paplorinc** [gradle/gradle#9723]
The following task shouldn't be up-to-date after rerun, since it didn't declare any outputs:
```groovy
@Issue("https://github.com/gradle/gradle/issues/9723")
def "task without output is never up-to-date"() {
    def input = file('input.txt').createFile()
    buildFile << """
        class NoOutputTask extends DefaultTask {
            @InputFile File input
         
            @TaskAction execute(InputChanges inputChanges) {
            }
        }   
        
        task noOutput(type: NoOutputTask) {
            input = file('${input.name}')
        }
    """

    when:
    run 'noOutput'
    then:
    noneSkipped()

    when:
    run 'noOutput'
    then:
    noneSkipped()
}
```

as noted by @lptr, it should display the following:
```
> Task :noOutput
Caching disabled for task ':noOutput' because:
  Caching has not been enabled for the task
Task ':noOutput' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:noOutput (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
```

**Comment by paplorinc** [comment]
It seems to me this may be a deliberate feature, based on some code comments and history:

- https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/tasks/DefaultTaskOutputs.java#L139

- https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactory.java#L56

- https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/DefaultTaskClassInfoStore.java#L73

- https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/DefaultTaskClassInfoStore.java#L105

Could you please confirm how it _should_ behave?
Should it not be marked as an incremental task, just because the action has an `InputChanges` parameter (would require reflective changes)? - would it 
Should we check later if we have outputs, then make it non-incremental?
Should we just throw an error during validation if the action has params, but the inputs are not annotated with Incremental? Or no outputs are defined?
Please advise.

**Comment by paplorinc** [comment]
@lptr we have a few failing tests, some of which may contradict this issue:
https://builds.gradle.org/viewLog.html?buildId=24114652&buildTypeId=Gradle_Check_Stage_QuickFeedbackLinuxOnly_Trigger

e.g. [`"incremental task is informed of 'out-of-date' files when task has no declared outputs or properties"`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractIncrementalTasksIntegrationTest.groovy#L206)

**Comment by paplorinc** [comment]
@adammurdoch, @bigdaz, could you guys please advise on whether the above test in the description should pass?
If not, we can close this issue.
[This comment](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/project/taskfactory/AnnotationProcessingTaskFactory.java#L56) and [this test](
https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/AbstractIncrementalTasksIntegrationTest.groovy#L206) seem to indicate this being the case.

If it should pass, please advise on how to handle it, given the [failing tests](https://builds.gradle.org/viewLog.html?buildId=24114652&buildTypeId=Gradle_Check_Stage_QuickFeedbackLinuxOnly_Trigger) for the [corresponding branch](https://github.com/gradle/gradle/commits/lorinc/9723/up-to-date-without-output).

**Comment by adammurdoch** [comment]
I think there were 2 assumptions that were made:

1. A task that declares an out-of-date spec does in fact have outputs, but we don't know what they are.
2. A task that uses the incremental inputs API does have outputs, regardless of whether they are declared or not.

I think we should keep the first assumption for now, and get rid of the second. So, something like this:

- When a task has an out-of-date spec, it has outputs. This is a way of declaring that there are outputs that are not files. Later this should be replaced with something more descriptive but is ok for now (or at least for this issue).
- It should be an error to use the incremental task APIs with a task that does not have any outputs (via deprecation first for the old API).

**Comment by lptr** [comment]
Let's deprecate incremental tasks without output in 5.6 and fail the build if they pop up in 6.0.

**Comment by bigdaz** [comment]
> Let's deprecate incremental tasks without output in 5.6 and fail the build if they pop up in 6.0.

I'm not sure about this: deprecating in the final release of 5.x and failing in 6.0 seems a bit aggressive. I guess it depends on how widespread the usage is.

**Comment by lptr** [comment]
We discussed it with @adammurdoch last week and we agreed that this should be incredibly rare, and if it is actually used then it should be an error anyway. It's also easy to fix or work around (you just have to call `task.outputs.file()` or something).

**Comment by bigdaz** [comment]
Apologies: I misread "deprecate incremental tasks without output" as "deprecate tasks using `IncrementalTaskInputs`". 

I'm completely on board with what you're suggesting.

**Comment by wolfs** [comment]
The deprecation has been done in https://github.com/gradle/gradle/pull/9896.

Now we need to remove the behaviour in 6.0.

**Comment by netvl** [comment]
This plugin: https://github.com/diffplug/spotless started to produce the incremental task API warning. This plugin adds tasks which validate formatting of code in the project. These tasks are incremental, because if nothing in the code has changed, they should not run a potentially slow process of validation. However, the only "output" of such a task is whether they failed or not. This seems to contradict the idea that incremental tasks should always have outputs.

The above reasoning is my understanding, and it might not be true specifically for spotless (I don't know if it has outputs which are not declared, or whether it should have them if it does not right now), but my question still stands - if a task does not have outputs, why can't it be incremental?
