### ISSUE TITLE
Improve messaging when spawned `exec`/`javaexec` are still running at the end of the build

### ISSUE THREAD

**Issue by tglaeser** [gradle/gradle#9735]
A task spawning off a new daemon thread blocks the console even after Gradle finished the build successfully.

### Expected Behavior
After Gradle prints `BUILD SUCCESSFUL` to the console one would expect that the console prompt becomes available again so that the user can continue entering commands.

### Current Behavior
Instead the console is blocked until the daemon thread actually finished; displaying
```
$ /c/local/gradle-5.2.1/bin/gradle --console=verbose --no-daemon spawn
Note: See directory 'C:\home\projects\test\build' for the logging output.
> Task :spawn

BUILD SUCCESSFUL in 8s
1 actionable task: 1 executed
<-------------> 0% WAITING
> IDLE
```

### Context
Trying to start an application in background using either `project.exec` or `project.javaexec`.

### Steps to Reproduce
Self-contained single-project build file attached... [build.zip](https://github.com/gradle/gradle/files/3298891/build.zip)
To reproduce execute the `spawn` task. For more information run `gradle tasks` and have a look at the `Test tasks` group. 

### Your Environment
Reproducible with almost all recent Gradle versions.

**Comment by lacasseio** [comment]
The `project.exec` and `project.javaexec` doesn't support launching an application in the background. This seems to be a duplicate of https://github.com/gradle/gradle/issues/1367 so I will close it. Reopen if it's different specifying how it's different.

**Comment by tglaeser** [comment]
Well, if #1367 would have been addressed then `project.exec` and `project.javaexec` could be configured differently to spawn of an application; but independently of #1367 wouldn't you agree @lacasseio that after Gradle prints `BUILD SUCCESSFUL`, or `BUILD FAILED` for that matter, that Gradle is done and gives access to the console again? The current behavior seems inconsistent to me, no matter what the user is trying to achieve.

**Comment by lacasseio** [comment]
Great point, let's focus this issue in providing a better messaging regarding spawn process still running. We should also track any ctrl-c to kill the running child processes.
