### ISSUE TITLE
buildscript dependencies classpath not refreshed

### ISSUE THREAD

**Issue by whojes** [gradle/gradle#9736]
**Gradle v5.2.1**

A jar file in a custom Nexus changed without name change(group/artifact/version at all) 
and buildScript did not detect this.

### Expected Behavior

My build.gradle scripts like this:
```gradle
buildscript {
  repositories {
    ...
    maven {
      url $customNexus
    }
  }
  dependencies {
    classpath("com.test:custom-build:1.0.0")
  }
}
....
```
I removed **com.test:custom-build:1.0.0** in the custom nexus and uploaded new jar file with the same name.
I expected that gradle refresh notice the change (maybe checking the checksum?) and get a new jar but it didnt.

### Current Behavior

I removed my caches ( $home/.gradle/... ) and refreshed gradle, and the new jar was downloaded and worked.
  is this the expected result?

**Comment by ljacomet** [comment]
Yes this is the expected result.

If you know that a dependency is _changing_ that is its content can change without coordinates update, you can tell Gradle about it:

```
dependencies {
    classpath("com.test:custom-build:1.0.0") {
        changing = true
    }
}
```

Note that Gradle will still cache these for 24 hours by default, this can be changed as well.

If the dependency is not really changing and this was a one time thing, adding `--refresh-dependencies` to the command line will also cause Gradle to check _all_ checksums again.

**Comment by whojes** [comment]
@ljacomet thanks for your kind support.
