### ISSUE TITLE
Clarify validation message about @Input being used on File inputs

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9749]
Currently the message says this:

```text
com.android.build.gradle.internal.tasks.AppClasspathCheckTask': property 'compileClasspath' has @Input annotation used on property of type org.gradle.api.artifacts.Configuration.
```

We should explain why this is a problem and/or what annotation to use instead.

**Comment by wolfs** [comment]
We should make the message better.

**Comment by twwwt** [comment]
> Currently the message says this:
> 
> ```
> com.android.build.gradle.internal.tasks.AppClasspathCheckTask': property 'compileClasspath' has @Input annotation used on property of type org.gradle.api.artifacts.Configuration.
> ```
> 
> We should explain why this is a problem and/or what annotation to use instead.

@lptr @wolfs 
Today I ran into precisely this issue. Please, before you improve this message, could you explain here why this is a problem and what annotation should be used instead.

**Comment by wolfs** [comment]
@twwwt: The message means that you shouldn't use `@Input` on a property with a type which is a file or a collection of files. For your case, you probably want to use `@CompileClasspath` or `@Classpath` instead. `@InputFiles`, `@InputDirectory` and `@InputFile` are other options which can be correct, depending on the type of the property.

**Comment by twwwt** [comment]
> @twwwt: The message means that you shouldn't use `@Input` on a property with a type which is a file or a collection of files. For your case, you probably want to use `@CompileClasspath` or `@Classpath` instead. `@InputFiles`, `@InputDirectory` and `@InputFile` are other options which can be correct, depending on the type of the property.

Nope. In my case, the property is exactly of the type the message says: `org.gradle.api.artifacts.Configuration`. Do not get confused by the name `compileClasspath` in the original example. Meanwhile, however, I went for annotation my property with `@Internal` since its value actually always refers the same configuration. Any other annotation options though?

**Comment by wolfs** [comment]
> > @twwwt: The message means that you shouldn't use `@Input` on a property with a type which is a file or a collection of files. For your case, you probably want to use `@CompileClasspath` or `@Classpath` instead. `@InputFiles`, `@InputDirectory` and `@InputFile` are other options which can be correct, depending on the type of the property.
> 
> Nope. In my case, the property is exactly of the type the message says: `org.gradle.api.artifacts.Configuration`. Do not get confused by the name `compileClasspath` in the original example. Meanwhile, however, I went for annotation my property with `@Internal` since its value actually always refers the same configuration. Any other annotation options though?

`Configuration` is a `FileCollection`, so a collection of files. So my suggestion above is correct and you should use one of the file input annotations.

**Comment by twwwt** [comment]
> `Configuration` is a `FileCollection`, so a collection of files. So my suggestion above is correct and you should use one of the file input annotations.

Thanks. I wasn't aware that a `Configuration` is a `FileCollection`. I have revised it to be annotated with `@InputFiles`.

To conclude the original request, I would propose to add "Note that a Configuration is a FileCollection; hence, any annotation applicable to a FileCollection may instead be used." at the end of the error message. This would help in resolving such warnings.

**Comment by lptr** [comment]
I think @tresat fixed this, no?

**Comment by tresat** [comment]
Yes, [in Gradle 7.5](https://github.com/gradle/gradle/pull/20158).
