### ISSUE TITLE
Inconsistent logging in new '--tests' vs '-Dtest.single' functionality

### ISSUE THREAD

**Issue by sboardwell** [gradle/gradle#975]
### Expected Behavior

Only the relevant matching tests or test classes should be logged and included in the test results when using a test filter.

I have the following tests 

    my.company.MySearchTermATest
    my.company.MySearchTermBTest

And the testLogging config 

     test {
        testLogging {
            displayGranularity 0
            minGranularity 2
            maxGranularity 2
            events "started", "passed", "skipped", "failed"
            exceptionFormat "short"
            debug {
                exceptionFormat "full"
            }
        }
    }

When running the tests with the `--tests ...` filter

    $ ./gradlew cleanTest test --tests="*MySearchTermA*" 

I expect only the relevant tests to be logged.

    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermATest STARTED
    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermATest PASSED

### Current Behavior

Currently I see all tests:

    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermATest STARTED
    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermATest PASSED
    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermBTest STARTED
    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermBTest PASSED

The tests are not run but the MySearchTermBTest is still added to the Junit results. 

*NOTE:* this does not happen when using the older `-Dtest.single` option. For example:

    $ ./gradlew cleanTest test -Dtest.single="*MySearchTermA*" 

will produce the expected 

    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermATest STARTED
    Gradle Test Run test > Gradle Test Executor 3 > my.company.MySearchTermATest PASSED

and the test results will only contain the matching classes.

### Context

We rely heavily on logging and test results to verify which test was run and in which job it was run. 

The test.single behaviour allowed us to do this but the current behaviour of the `--tests` test filter makes this very difficult to differentiate between non-matching and empty test classes. 

### Steps to Reproduce (for bugs)

Compare the outputs of 

Added simple example project from the java quickstart example:
[quickstart.zip](https://github.com/gradle/gradle/files/633628/quickstart.zip)

    $ ./gradlew cleanTest test --tests "*Person*" 

vs

    $ ./gradlew cleanTest test -Dtest.single="*Person*" 

### Your Environment

Gradle Version 3.2 (also tried with 3.2.1)

**Comment by eriwen** [comment]
@sboardwell Thank you for the well written issue and example. This is well enough defined that I think the community may be able to address this quicker than our schedule will allow. If this get some 👍 s though, we'll prioritize a fix higher.

**Comment by sboardwell** [comment]
@eriwen Thanks for the comment (and labels ;-) ). I will see if I have time to have a look myself in the next few days.

**Comment by oehme** [comment]
This is a bug in how we drive JUnit 4 - we create start/finished events for test classes even if none of their tests ever get run. Using `useJunitPlatform {}` with the vintage engine would be a quick workaround that should unblock you.

In general we should change our JUnit 4 runner to work more like our JUnit platform runner does, i.e. give more control to the framework and make less assumptions on its own.

**Comment by sboardwell** [comment]
@oehme thanks for that. I will pass on the information.

**Comment by ov7a** [comment]
Fixed by
* https://github.com/gradle/gradle/pull/34921
