### ISSUE TITLE
Add junit5 container to .classpath

### ISSUE THREAD

**Issue by kec2** [gradle/gradle#9756]
### Expected Behavior

I would expect that
<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/5"/>
was added to the .classpath file when I run gradle cleanEclipse eclipse

### Current Behavior

The Junit 5 container is missing from the .classpath file. This makes Eclipse not being able to run Junit5 tests.

### Context

I'm trying to be able to run Junit5 test cases from both command line and Eclipse.

### Steps to Reproduce 
This is a build file that reproduces the problem.

```
apply plugin: 'java'
apply plugin: 'eclipse'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.4.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.4.2'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

test {
    useJUnitPlatform()
}

```

Look in the .classpath file and you won't find 
```
<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/5"/>
```

### Your Environment
```
D:\Sample>gradlew -v

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Windows 10 10.0 amd64
```

Build scan URL:

**Comment by soundasleep** [comment]
For the curious this seems to work OK if you use `gradlew cleanEclipse eclipse` and then re-import the Eclipse project. [source](https://stackoverflow.com/a/28274390/39531)
