### ISSUE TITLE
Support symbolic links in FileTree

### ISSUE THREAD

**Issue by jvff** [gradle/gradle#976]
I encountered a need to archive symbolic links, and following a [discussion from 2013](http://gradle.1045684.n5.nabble.com/Symbolic-links-td5711601.html) I ended up in a [design document](https://github.com/gradle/gradle/blob/master/design-docs/copy-spec-improvements.md) to add symlink support to `FileTree`. I started implementing the first easy steps from the story, but I had a few questions.

First of all, how should I approach any issues and questions that appear? Should I use a GitHub issue (this one?)? Should I open a discussion thread in the forums?

Secondly, how should I show the code? Should I use my GitHub fork of Gradle and link to the commits there, or should I send pull requests? (How often? Or should I wait until I complete the feature?)

Regarding the implementation (more specifically, starting at step 6), should I update the `FileVisitor` interface? I thought about adding a new method `visitSymlink` (or `visitSymbolicLink`?), but that would break backwards compatibility. I also thought about adding a default implementation, but I'm also not sure if that would be supported or compatible.

I added the `FileTree.visit(Action, SymlinkStrategy)` method, but should I also add a `FileTree.visit(FileVisitor, SymlinkStrategy)` overload?

Lastly, are there any tips on where I should look to implement step 6: "Change the implementation of the file system file tree to honour the symlink strategy"?

Thanks in advance.

**Comment by eriwen** [comment]
@jvff It looks like you've rightly started a discussion on the dev list about this. That or the forum is the best avenue for questions like this. Once you've gotten them answered, I recommend perhaps reopening this issue or opening a new one with all of the sections completed about motivation and context.

Feel free to reply to this issue or contact us via another channel if you need clarifications.

**Comment by novaterata** [comment]
Why was this rejected? Please reconsider
