### ISSUE TITLE
Checkstyle config_loc is deprecated but replacement configDir is incubating

### ISSUE THREAD

**Issue by rwinch** [gradle/gradle#9761]
### Expected Behavior
There should be an API that is not deprecated and not incubating to configure Checkstyle configuration location.

### Current Behavior

The following configuration:

```groovy
plugins {
	id 'java'
	id 'checkstyle'
}

repositories {
	mavenCentral()
}

checkstyle {
	configProperties = ['config_loc' : project.file("config/nohttp") ]
}
```

will produce the warning

```
Adding 'config_loc' to checkstyle.configProperties has been deprecated. This is scheduled to be removed in Gradle 6.0. Use checkstyle.configDir instead as this will behave better with up-to-date checks.
```

Unfortunately, [configDir](https://docs.gradle.org/5.4.1/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:configDir) is still Incubating.

### Context

I'd like to be able to specify `config_loc` for the nohttp-gradle-plugin without getting a deprecation warning and without using incubating APIs. See https://github.com/spring-io/nohttp/issues/25

### Steps to Reproduce 

Checkout the `checkstyle-config-deprecated` branch from `https://github.com/rwinch/gradle-sample.git` and run `./gradlew clean check --warning-mode all`

```
git clone -b checkstyle-config-deprecated https://github.com/rwinch/gradle-sample.git
cd gradle-sample
./gradlew clean check --warning-mode all

> Task :checkstyleMain
Adding 'config_loc' to checkstyle.configProperties has been deprecated. This is scheduled to be removed in Gradle 6.0. Use checkstyle.configDir instead as this will behave better with up-to-date checks.

BUILD SUCCESSFUL in 0s
3 actionable tasks: 3 executed
<-------------> 0% WAITING
> IDLE
``` 

### Your Environment

Build scan URL: https://scans.gradle.com/s/oxooswhcdzjnk

**Comment by marcphilipp** [comment]
@gradle/core `configDir` has been added for 4.0 so I assume we're going to promote it in 6.0?

**Comment by marcphilipp** [comment]
`configDirectory` should now be used and is no longer incubating.

**Comment by rkrisztian** [comment]
Please reopen this, I see no reason to use `config_loc` anymore considering it is deprecated.
