### ISSUE TITLE
Gradle behaves different on JDK11 and JDK8

### ISSUE THREAD

**Issue by lamagicsword** [gradle/gradle#9764]
I created a simple Gradle project and added following code snippet inside my build.gradle script
```
println(new File("").getAbsoluteFile())
println(System.getProperty("user.dir"))
```
then I ran `gradle build` on this project with JDK11 and JDK8 respectively
### Expected Behavior

Under both JDK11 and JDK8 context, it should return:
```
/path/to/project/dir/
/path/to/project/dir/
```
since [Java Documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/File.html#getAbsolutePath()) specifies these two have the equivalent effect.
### Current Behavior

JDK8: Returned results as expected
JDK11: The following is returned
```
/path/to/gradle/daemon/.gradle/daemon/5.4.1
/path/to/project/dir/
```
### Context

I wish to know why `new File("").getAbsoluteFile()`  behaves differently in Gradle when switching from JDK8 to JDK11 even though the documentation states the return value should be the same
### Steps to Reproduce 

* Create a simple Gradle project from Intellij
* Add the code snippet above in build.gradle file
* Ran project against JDK11

### Your Environment

Gradle Version: 5.4.1
JVM: 11

**Comment by big-guy** [comment]
You should [never use new File("")](https://docs.gradle.org/current/userguide/working_with_files.html#sec:single_file_paths) because it's relative to the current working directory of the process and that is not guaranteed to be the project directory.  You should use `project.file("...")` instead.

In previous versions of Gradle, it was possible to change the current working directory of the process, but since JDK9 (I think), that's no longer allowed.

**Comment by cesar1000** [comment]
I'm running into this issue with Checkstyle: the `suppressions.xml` file is specified in a configuration file as a relative path, and I have no way to control how it's translated into an absolute path. JDK8 used to resolve it correctly, but JDK11 doesn't. What makes this issue particularly insane is that `file.exists()` and `file.getAbsolutePath().exists()` are inconsistent:

![image](https://user-images.githubusercontent.com/2517200/83986036-40bd8100-a8f0-11ea-8c4c-778518ef0206.png)

@big-guy I don't think the fundamental question has been answered: why does Gradle's behavior change when running under JDK11, and what's a workaround?

**Comment by cesar1000** [comment]
I just came across #8286 – I'll try that. Still curious about the inconsistency between both calls to `exists()`, which is at the core of the problems in checkstyle: an `exists()` call validates the relative path, to then crash at a later time when the absolute path is not found.
