### ISSUE TITLE
Provide 'or'-like funcitonality for providers so that they can provide a one-of like relationship for inputs

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle#9765]
`Provider` is similar to the JDK `Optional` type in that a value is derived through some execution path or the value derivation is not present. When wrapping existing tools or developing new tools, the ability to specify a one-of or hierarchy of values can be useful. For example when wrapping the Kubernetes built-in tool [`kustomize`](https://kustomize.io/), it uses a default input file of one of `kustomization.yaml`, `kustomization.yml`, or `Kustomization`. Attempting to map this to an `@InputFile` or `@InputFiles` from its contents can be difficult given the existing APIs.

### Expected Behavior

`Provider` and lazy configuration APIs should allow for providing one-of like semantics as shown below. `Provider` types should be more functional and allow or composition like most functional types that exist today.

A workaround today for providing one-of files to a task might be accomplished by something like:

```kotlin
project.objects.fileProperty().apply {
        convention(
            project.layout.file(
                project.provider {
                    val a = project.file("a")
                    if (a.exists()) {
                        return@provider a
                    }
                    val b = project.file("b")
                    if (b.exists()) {
                        return@provider b
                    }
                    project.file("c")
                }
            )
        )
    }
```

### Current Behavior

 No API exist today, so the behavior needs to be sort-of wrapped through the use of an a `provider {}` wrapped block that performs the logic itself

### Context

I was attempting to provide a one-of default value (or value in general) for a `Property` task input, such that one of the inputs are considered for up-to-date with some hierarchy. It would be useful if all inputs were considered and some type of error message could be considered, so that a "there are multiple inputs" type error message could be returned to users.

**Comment by adammurdoch** [comment]
Added via https://github.com/gradle/gradle/pull/9774
