### ISSUE TITLE
Better way to import boms

### ISSUE THREAD

**Issue by octopus-prime** [gradle/gradle#9773]
I found this in the documentation:
https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import

In a subproject i have
```
dependencies {
    annotationProcessor("org.projectlombok:lombok")
    compileOnly("org.projectlombok:lombok")

    implementation('org.springframework.boot:spring-boot-starter')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework.boot:spring-boot-starter-actuator')
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation('org.springframework.boot:spring-boot-starter-aop')
    implementation('org.springframework.retry:spring-retry')
...
}
```

So i tried the way given in documentation:
```
subprojects {
...
    dependencies {
        implementation(platform("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE"))
        implementation(platform("org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2"))
    }
}
```
to get all recommended versions from the boms.

Nice. But did not work, because i was forced to import the bom for 'implementation'.
So 'annotationProcessor' and 'compileOnly' do not find the version for lombok.
That leads to real boiler-plate code:
```
subprojects {
...
    dependencies {
        annotationProcessor(platform("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE"))
        compileOnly(platform("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE"))
        implementation(platform("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE"))
        implementation(platform("org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2"))
    }
}
```

### Expected Behavior
Would like to have same behavior as in the io.spring.dependency-management-plugin:
```
    dependencyManagement {
        imports {
            mavenBom("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE")
            mavenBom("org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2")
        }
```
As you can see: i have to declare the boms only once!

So there should be a way to use boms without tieing to 'implementation', 'annotationProcessor', 'compileOnly'... something like:
```
subprojects {
...
    dependencies {
        platform("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE")
        platform("org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR2")
    }
}
```

**Comment by melix** [comment]
I understand the intent but the way Gradle does this is _intentional_. There's no reason to share the platform with `annotationProcessor` or `yourCustomConfigurationGradleKnowsNothingAbout`. Only you, as a consumer, knows if it makes sense to share. Typically the annotation processor classpath is something aimed at the compiler, and it should use very different libraries from the runtime of the application. The fact that a BOM would mix dependencies used by the compiler and dependencies used by the application is an implementation detail that shouldn't leak into Gradle's model. In fact, I would consider this a very bad practice. Imagine that your Lombok processor needs a dependency on foo.1.9 and that your app needs `foo:2.1`. In theory one shouldn't influence the other.

Now, should you want to do this, Gradle offers you the ability to do it. You can declare a super-configuration with your bom and make the relevant configurations extend from it.
