### ISSUE TITLE
PathMatcher matches every directory if include starts with **

### ISSUE THREAD

**Issue by willamette** [gradle/gradle#9775]
So there is a npm task and we are trying to select some directories. so we 
exclude `**/.*` (like .jest-cache)
include `**/node_modules/**/package.json`

But seems `**/node_modules/**/package.json` would match `.jest-cache`

### Expected Behavior
`**/node_modules/**/package.json` would NOT match `.jest-cache`

### Current Behavior
`**/node_modules/**/package.json` would match `.jest-cache`

### Context
I think this is caused by PatternMatcherFactory

When parsing the `**/node_modules/**/package.json`, the pathMatcher is `{greedy next: {fixed-step: {match: node_modules}, next: {greedy next: {fixed-step: {match: package.json}, next: {end-of-path}}}}}`

So it seems matching every directory in PatternMatcherFactory since GreedyPathMatcher isPrefix is always returning true.
``` 
public boolean isSatisfiedBy(RelativePath element) {
            if (element.isFile() || !partialMatchDirs) {
                return pathMatcher.matches(element.getSegments(), 0);
            } else {
                return pathMatcher.isPrefix(element.getSegments(), 0);
            }
        }
```

### Steps to Reproduce 
Running this task would cause the issue.
```    
public class NpmBuildTask extends DefaultTask {
  @InputFiles
    public FileCollection getFileInputs() {
        // We have to exclude many files here, as some modules / libraries change things during build / tests

        final FileCollection projectSources = getProject().fileTree(packageJsonRoot)
                .matching(match -> match
                        .exclude("**/.*")
                );

        final FileCollection npmDependencyMetadata = getProject().fileTree(packageJsonRoot)
                .matching(match -> match.include("**/node_modules/**/package.json"));
        return projectSources.plus(npmDependencyMetadata);
    }
}```

### Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
<!--- A build scan https://scans.gradle.com/get-started is ideal -->
Build scan URL: Gradle 5.3

**Comment by wolfs** [comment]
@willamette Thank you for reporting. If I understand correctly, your problem is that the directory `.jest-cache` is included in the file tree even though you explicitely excluded it? Can you add an example how you select your directories and where you see the desired/undesired files?

**Comment by willamette** [comment]
Yes, correct.

Seems this exclude rule (`exclude "**/*"`) is conflicting with `include "**/node_modules/**/package.json"`

The java code is the plugin I wrote to select the files

The result is seen from running `gradle -i` and it shows 

```
Task ':npmBuild' is not up-to-date because:
  Input property 'fileInputs' file /home/project/src/main/npm/node_modules/.jest-cache has been added.
```

**Comment by willamette** [comment]
Another example is 
`exclude "node_modules/.cache"`, and `include "node_modules/**/package.json"`
`"node_modules/**/package.json"` seems also match 

You can write an unit test in PatternMatcherFactoryTest
```
    @Test public void testInsideGreedyPatterns() {
        matcher = PatternMatcherFactory.getPatternMatcher(true, true, "node_modules/**/package.json");
        assertThat(matcher, matchesDir("node_modules", ".cache"));
    }
```
Surprisingly it is passing

**Comment by wolfs** [comment]
`**` always needs to include all directories, since files somewhere down the directory could be included. For example, there could be a `node_modules/.cache/package.json` file and therefore Gradle needs to look into the `.cache` directory when walking the file system.

There is currently no way to state that your task wants to ignore directories in the input. See for example #2463 for a possible solution to what you want to accomplish.

**Comment by willamette** [comment]
Yea, when the exclude & include conflicts with each other, providing a way to resolve the conflict would be nice, like setting the priority.

but put the `exclude` part aside,  it is quite unconventional that `node_modules/**/package.json` matches `node_modules/.cache`

**Comment by wolfs** [comment]
Exclusion patterns have a higher priority than inclusion patterns. See the [user manual](https://docs.gradle.org/current/userguide/working_with_files.html#filtering_files).

So I guess something like
```
include '**/node_modules/**/package.json'
exclude '.*/**'
```
should work, right?

**Comment by willamette** [comment]
Unfortunately it doesn't work :(  Tried this before. 
My workaround is 
```exclude element -> element.isDirectory```
If it could be solved without this workaround, that would be great :P 
I think even with explicitly documentation, it is very error prone to use this, since it is super weird to remember ```node_modules/**/package.json``` matches ```node_modules/.cache```

**Comment by wolfs** [comment]
The following seems to work:
```
include '**/node_modules/**/package.json'
exclude '.*'
exclude '.*/**'
```

This test passes:
```
    def "can exclude directories"() {
        def source = new PatternSet()
        source.include("**/package.json")
        source.exclude(".*")
        source.exclude(".*/**")

        expect:
        def spec = factory.createSpec(source)
        spec.isSatisfiedBy(element("in/package.json"))
        !spec.isSatisfiedBy(dirElement(".excluded"))
        !spec.isSatisfiedBy(element(".excluded/some-file.json"))
        !spec.isSatisfiedBy(element(".excluded/package.json"))
        !spec.isSatisfiedBy(dirElement(".excluded/myDir"))
    }
```

Does this work for you?

**Comment by wolfs** [comment]
I am closing the issue now. Please re-open if it is still a problem.

**Comment by willamette** [comment]
Alright, thanks

it is still a problem but I've found a workaround
 
I am afraid it might cause a lot of issues when the path matcher is not working as expected, because it is supposed to work with the glob pattern

e.g: I don't understand why this is a match - `a/b/**/c` matches `a/b/d`  
https://github.com/gradle/gradle/blob/cf86ea14e63b506bddea7776184de15e94bfa0b6/subprojects/core/src/test/groovy/org/gradle/api/internal/file/pattern/PatternMatcherFactoryTest.java#L307
