### ISSUE TITLE
Slow builds due to unnecessary file system operations in DefaultBinaryStore

### ISSUE THREAD

**Issue by AndreasBrieg** [gradle/gradle#9779]
I stumbled upon seemingly unnecessary file system accesses caused by [`org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore`](https://github.com/gradle/gradle/blob/261d171646b36a6a28d5a19a69676cd098a4c19d/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/resolveengine/store/DefaultBinaryStore.java).

When the `done()` method is called the `diagnose()` method checks whether the file represented by the binary store exists and the result is included in the `sourceDescription` of the `DefaultBinaryStore.SimpleBinaryData` instance being returned. However having a watchpoint for reads on this field never yielded a hit during my debugging sessions. So in a lot of cases the file system access was of no use.

### Current Behavior
`DefaultBinaryStore.diagnose()` always checks if a file exists

### Expected Behavior
`DefaultBinaryStore.diagnose()` only checks if a file exists if debug output is turned on

### Context
I'm looking into why the intellij sync for the gradle project I'm working on does take longer than one would expect. 

Logging breakpoint hit messages for `DefaultBinaryStore.diagnose` shows that this is called about 10000 times per intellij gradle sync that currently takes about 2mins to complete in the project I'm working on. When assuming a 3ms duration per `java.io.File.exists()` this may account for an additional runtime of about 30s or 25% of total time of intellij gradle sync.

Moreover the check is executed on only two different files with a naming scheme like  `C:\Users\<user>\AppData\Local\Temp\gradle<\d+>.bin`

Searching around existing issues the provided information does show up in some of them (for example: #7481). I'm unable to say what value this information is. But therefore I'm suggesting to only do the file existence check when debug output is on.

windows 7
gradle 5.4.1
java 1.8.0_161
SSD Samsung 850 Pro

I haven't looked at different gradle executions than intellij gradle sync yet.

**Comment by AndreasBrieg** [comment]
This also has an effect on normal builds. When I `build -x check` the mentioned project `DefaultBinaryStore.diagnose` is called 20000 times if there are no changes to the project and the project has been build successfully before.

**Comment by oehme** [comment]
>> assuming a 3ms duration

We should not assume, but measure. In all likelihood this method has close to zero overhead. It certainly hasn't shown up in any profiler snapshot we've ever done. 

Please use a good sampling profiler like [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) to measure where the time in your build is going. We can then do any necessary optimizations from there

**Comment by AndreasBrieg** [comment]
I rebuild the dependency-management without the mentioned file existence check in `DefaultBinaryStore`. This doesn't make a difference in build performance. I probably was measuring the time used for logging the breakpoint hit message instead of the actual time for the file system access.

However it still feels odd that `DefaultBinaryStore` checks the existence of the same file over and over again in some usage scenarios like intellij gradle sync. But that is probably a different issue.
