### ISSUE TITLE
Any edit in Kotlin Gradle DSL script forces rebuild for whole project

### ISSUE THREAD

**Issue by alexey-tsvetkov** [gradle/gradle#9781]
All tasks in all projects are not up-to-date after doing any change to any Kotlin Gradle DSL script.
This does not happen when Groovy script is changed in a similar.
Also the reasoning message in the build scan is quite unhelpful. 

### Expected Behavior
Tasks should not run if their input properties and bytecode are unchanged.
Groovy and Kotlin scripts should not behave differently. 

### Current Behavior
When Kotlin script is changed in any way (new empty lines are causing this!),
all incremental tasks become out-of-date

### Context
Doing any changes in Kotlin scripts becomes very painful in a big project.

### Steps to Reproduce 
1. Clone https://github.com/alexey-tsvetkov/gradle-bugs-kts-change-forces-rebuild
2. Run `./gradlew build`
3. Checkout `change-groovy-script` branch (or change `lib-gradle-groovy/build.gradle`).
4. Run `./gradlew build`. Eveything is up-to-date as expected: https://scans.gradle.com/s/c4wyrykjqzwdu
5. Checkout `change-kotlin-script` branch (or change `lib-gradle-kts/build.gradle.kts`).
6. Run `./gradlew build`. All incremental tasks are out-of-date: https://scans.gradle.com/s/mkkyjyyqqrnac

**Comment by big-guy** [comment]
@lptr @wolfs could you guys take a look at this?

**Comment by paplorinc** [comment]
Hey @alexey-tsvetkov, we've tried reproducing it locally and for us it's `UP-TO-DATE`, e.g.:
```
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validateTaskProperties UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :lib-gradle-groovy
Evaluating Groovy Script

> Configure project :lib-gradle-kts
Evaluating Kotlin Script

> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :assemble UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build UP-TO-DATE
> Task :lib-gradle-groovy:compileKotlin UP-TO-DATE
> Task :lib-gradle-groovy:compileJava UP-TO-DATE
> Task :lib-gradle-groovy:processResources NO-SOURCE
> Task :lib-gradle-groovy:classes UP-TO-DATE
> Task :lib-gradle-groovy:inspectClassesForKotlinIC UP-TO-DATE
> Task :lib-gradle-groovy:jar UP-TO-DATE
> Task :lib-gradle-groovy:assemble UP-TO-DATE
> Task :lib-gradle-groovy:compileTestKotlin NO-SOURCE
> Task :lib-gradle-groovy:compileTestJava NO-SOURCE
> Task :lib-gradle-groovy:processTestResources NO-SOURCE
> Task :lib-gradle-groovy:testClasses UP-TO-DATE
> Task :lib-gradle-groovy:test NO-SOURCE
> Task :lib-gradle-groovy:check UP-TO-DATE
> Task :lib-gradle-groovy:build UP-TO-DATE
> Task :lib-gradle-kts:compileKotlin UP-TO-DATE
> Task :lib-gradle-kts:compileJava UP-TO-DATE
> Task :lib-gradle-kts:processResources NO-SOURCE
> Task :lib-gradle-kts:classes UP-TO-DATE
> Task :lib-gradle-kts:inspectClassesForKotlinIC UP-TO-DATE
> Task :lib-gradle-kts:jar UP-TO-DATE
> Task :lib-gradle-kts:assemble UP-TO-DATE
> Task :lib-gradle-kts:compileTestKotlin NO-SOURCE
> Task :lib-gradle-kts:compileTestJava NO-SOURCE
> Task :lib-gradle-kts:processTestResources NO-SOURCE
> Task :lib-gradle-kts:testClasses UP-TO-DATE
> Task :lib-gradle-kts:test NO-SOURCE
> Task :lib-gradle-kts:check UP-TO-DATE
> Task :lib-gradle-kts:build UP-TO-DATE

BUILD SUCCESSFUL in 0s
9 actionable tasks: 9 up-to-date

Publishing build scan...
https://e.grdev.net/s/5w3zmbkxml5u4
```

In your case it was not up-to-date for the following reason:
```
Output property 'destinationDir' file buildSrc/build/classes/kotlin/main has been removed.
Output property 'destinationDir' file buildSrc/build/classes/kotlin/main/BuildSrcKotlinClass.class has been removed.
Output property 'destinationDir' file buildSrc/build/classes/kotlin/main/META-INF has been removed.
```


We're running it with JDK 11 (you seem to have 8), we've tried with Mac (you seem to have Linux).
Lemme try it with your settings as well.

**Comment by paplorinc** [comment]
Tried it with Linux and Java 8, it's still up-to-date for us. Can you please try it with your reproducer?

**Comment by mkobit** [comment]
I feel like I've been seeing something similiar to this, too. For me at least, it seems to happen when running things split between the command line and IntelliJ importing and updating its settings. Both things seem to fight for control to reprocess `buildSrc`, and they both seem to constantly clean and reprocess thus requiring the build scripts themselves to need to be reprocessed. I haven't wrote up a minimal reproduction case yet, so I'm not sure if it is similar to this issue.

**Comment by wolfs** [comment]
@mkobit That might happen when IDEA and the command line use different Gradle versions - especially for `buildSrc`. Can you check if you have Gradle Daemons running which use a different version?

**Comment by alexey-tsvetkov** [comment]
Ok, it seems that the issue was happening only when I edited the script from Intellij 2019.2 that comes with JetBrains Runtime 11 (which is a fork of OpenJDK11). For some reason IDEA/Kotlin plugin always uses this runtime for completion in Kotlin scripts (for running tasks IDEA correctly uses JVM from Gradle settings).
My JAVA_HOME is set to JDK 1.8, and properties `sourceCompatibility`/`targetCompatibility` properties set, so basically `buildSrc` was alternately built with JDK 1.8 + `sourceCompatibility = 1.8` and JBR 11 + `sourceCompatibility = 11`.

The issue seems to be mostly on Intellij side, so this ticket can probably be closed.

I wish, however, that alternating Gradle daemons within the same project would be more visible to users. It is not a first (not even a second) time I'm seeing a performance issue caused by different daemons in IDE and CLI (because of different memory/locale settings, JDK version, etc.)

**Comment by paplorinc** [comment]
@lptr, @wolfs, is there anything we can do to make this more visible?

**Comment by paplorinc** [comment]
I'll open a new issue to figure out a way to allow users to figure out that they're running multiple daemons with different settings - and decide which should be done on our side and what on Idea side.

**Comment by paplorinc** [comment]
Moving the discussion over to https://github.com/gradle/gradle/issues/9809, thanks for the explanations.
