### ISSUE TITLE
No warnings if an attribute is not declared in the "attribute schema"

### ISSUE THREAD

**Issue by kyegupov** [gradle/gradle#9783]
### Expected Behavior
There's a documentation of any sort.

### Current Behavior
The documentation tells that you can "get matching strategy".
The tests (DefaultAttributesSchemaTest.groovy) show ONLY a failure when there's no matching strategy for a custom attribute and don't explain how to create one.

### Context
I want to create a custom attribute and use it in a multi-project build.
The error message is "Unable to find matching strategy for ...", and there's absolutely no way to find out what is it that I'm supposed to do.

**Comment by kyegupov** [comment]
Aha, there is a documentation section: https://docs.gradle.org/current/userguide/dependency_management_attribute_based_matching.html#sec:abm_declaring_attributes

It's very easy to skip the "attributes must be declared in the attribute schema" bit, since no error message is ever suggesting that you need to do so.

**Comment by ljacomet** [comment]
Can you describe what you are trying to achieve? What you tried? Where / when you would have wanted an error?
A reproducer might be the best way to convey that information.

**Comment by kyegupov** [comment]
Steps:
* have a multi-project build, with one sub-project depending on another
* define a custom attribute:

```
def specificAttr = Attribute.of("specificAttr", String)
configurations {
      apiElements {
          attributes {
              attribute(specificAttr, "rootprojValue")

... etc
```  

* expect the variant matching to select matching configuration based on this attribute
* discover that matching is not enforced
* spend a lot of time investigating
* discover that you needed to do also

```
dependencies.attributesSchema {
    attribute(specificAttr)
}
```
