### ISSUE TITLE
Incremental Groovy compilation when a file moves between source roots

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9785]
When a source file moves between source roots, then the `GroovyCompile` task will be up-to-date, since the path sensitivity for the sources is `RELATIVE`. When the moved file changes afterwards, then we won't be able to map the source file to the compiled classes and will not remove the leftover classes, since we use the absolute path as a key for the source to classes mapping.

We probably need to use a relative path for the mapping. That would also allow to share the mapping file via the build cache.

**Comment by isker** [comment]
@wolfs is this the same problem as in https://github.com/gradle/gradle/issues/9380?

**Comment by wolfs** [comment]
@isker It is similar, though not really the same since Groovy incremental compilation uses a slightly different mapping from class names to source files than Java incremental compilation. I wouldn't be surprised if the same error occurs though.
