### ISSUE TITLE
Javadoc task uses wrong encoding to write `javadoc.options` file

### ISSUE THREAD

**Issue by alexanderfloh** [gradle/gradle#979]
I'm trying to generate a Javadoc with a Japanese document title and window title.

### Expected Behavior
The window title should be rendered as `リファレンス` but is `??????`.

### Context
I think in https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/main/java/org/gradle/external/javadoc/internal/JavadocOptionFileWriter.java#L40 the overload with the encoding parameter should be used. The encoding should either be based on the encoding/charset specified for the Javadoc or separately configurable.

I've noticed that in the `javadoc.options` file the characters are already displayed as question marks.

### Your Environment
**Note:** my environment/locale is **not** set to Japanese.

**Comment by eriwen** [comment]
@alexanderfloh Thank you for contributing. Can you confirm what OS and Gradle version you're using, please? An example would be helpful here if you have one.

**Comment by alexanderfloh** [comment]
@eriwen I was able to reproduce the issue with `Gradle 3.1` and `Gradle 3.2.1` on `Windows 10 1511`.

I have created a minimal sample project to repro the issue at https://github.com/alexanderfloh/javadoc-issue-repro.

After running `gradlew javadoc` take a look at the contents of `build/docs/javadoc/index.html`. The title is `<title>??????</title>`.

It seems to me that this is already incorrectly encoded in the `javadoc.options` file written by the Gradle plugin. Navigating to `build/tmp/javadoc/javadoc.options`, you'll see lines like 
```
-doctitle '<h1>??????</h1>'
-windowtitle '??????'
```

Thanks for looking into this, let me know if you need anything else.

**Comment by big-guy** [comment]
Ah, Windows.

Can you try setting `-Dfile.encoding=UTF-8` in the `JAVA_OPTS` environment variable?  By default on Windows, the file encoding is CP1250 for the build.gradle files, which would produce ????.

**Comment by alexanderfloh** [comment]
This seems to fix the content of the `javadoc.options` file, although the string in the html file is still garbage. 

It is now `<title>ãƒªãƒ•ã‚¡ãƒ¬ãƒ³ã‚¹</title>`.

Any ideas?

**Comment by eriwen** [comment]
@alexanderfloh Thank you for the example and environment information. We may not be using the correct encoding in some places. 

We'll look into this when we get it prioritized in a sprint. This may be easy enough to fix by a community member given the context you've provided, so I'm going to add `help-wanted` here in case someone else fixes this before we can.

**Comment by hotchemi** [comment]
Can I grab the issue?

**Comment by lacasseio** [comment]
You can certainly grab that issue @hotchemi. Thanks for your interest. Don't hesitate to ask questions.

**Comment by hotchemi** [comment]
Ah windows...

**Comment by michael-o** [comment]
Maybe this one? https://issues.apache.org/jira/browse/MJAVADOC-544

**Comment by trejkaz** [comment]
Seems like the core sin here is use of `Charset.defaultEncoding()` inside `IoActions.java`.

**Comment by hakanai** [comment]
Not planned? i.e., corrupting people's builds is OK?

**Comment by ljacomet** [comment]
Hi @hakanai 

The recent activity is mostly us making sure that all issues closed by the stale bot are properly marked as "not planned" instead of looking like regular completed issues.

This is an area that the team cannot currently focus on. So its state reflects this now.
