### ISSUE TITLE
Gradle/kotlin/micronaut project.. intellij test are succesful but gradle test are failing

### ISSUE THREAD

**Issue by SamathaUppula** [gradle/gradle#9792]
"ObjectMapper ob = new ObjectMapper(new YAMLFactory())
    InputStream resource = CacheBustFunctionalSpec.class.getResourceAsStream(path)
    Map readValue = ob.readValue(resource, Map.class)" this piece of code is running succesfully through Intellij.. but from gradle it is throwing exception . "java.lang.UnsupportedOperationException" ..  I tried updating gradle version to 5.4.1 but no luck.

**Comment by paplorinc** [comment]
Hey @SamathaUppula, thanks for reporting it. Could you please post us the stack trace?

**Comment by ljacomet** [comment]
Closing as original reporter did not provide information to track down issue.
