### ISSUE TITLE
Are there some method to let eclipse plugin attach source jar in parallel model?

### ISSUE THREAD

**Issue by simonjhy** [gradle/gradle#9795]
Are there some method to let eclipse plugin attach source jar in parallel model?
### Expected Behavior

I hope the gradle eclipse plugin can   support download source jar in parallel model.  This is more useful when we have lots of dedependencies with source.
### Current Behavior

Hope gradle eclipse plugin can download source jars with multiple thread together to save time.
### Context

our project will be bind a target platform configuration support for our project. This configuration will be include lots of source jar, we want to add these source jars to eclipse project classpath and this will help user to work in debug model. But I found the eclipse plugin can not support download source jar in parallel model and it has to download source jars one by one and it will use long time to finish it.

**Comment by donat** [comment]
When you talk about the Eclipse plugin, is that Buildship, or the `eclipse` plugin in Gradle (i.e. running the `eclipse` task directly: `./gradlew eclipse`)? In either case, can you please elaborate where do you see the source jar download not happening concurrently? The dependencies and their source jars are downloaded during dependency resolution, which should happen concurrently.
