### ISSUE TITLE
Unable to resolve resources from project dependency when using java-library and groovy plugin

### ISSUE THREAD

**Issue by noproxy** [gradle/gradle#9796]
In the issue #7398,  the consumption of `classes` by the java-library plugin has been fixed,
but there is still same problem for `resources`. As a result, when using `groovy` plugin as well as `java-library`, the consumer project is unable to find the resources in the project dependency.

### Expected Behavior

 
Using the java-library plugin with the groovy plugin won't break the resources to be transitively included by consumer project.

### Current Behavior

Using the java-library plugin with the groovy plugin causes the resources `are not` be transitively included by consumer project.

### Context

This issue is related to issue #7398 which has been fixed by pr #8229 since 5.3. But as for resources, the same problem still exists.

### Steps to Reproduce 

This is a reproduce project: https://github.com/noproxy/gradle-issue-9796

### Your Environment

Gradle 5.4.1
Mac OS X 10.15

**Comment by noproxy** [comment]
@JamesXNelson  You might be interested in this because you kindly fixed the previous issue.

**Comment by jjohannes** [comment]
This should work in Gradle 6+. Please reopen if there is still an issue.
