### ISSUE TITLE
Error in SourceSetOutput doc example

### ISSUE THREAD

**Issue by feinstein** [gradle/gradle#9800]
The `SourceSetOutput` docs [here](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html#org.gradle.api.tasks.SourceSetOutput:dir(java.util.Map,%20java.lang.Object)) shows:

```gradle
apply plugin: 'java'

def generatedResources = "$buildDir/generated-resources/main"

sourceSets {
  main {
    //let's register an output folder on the main SourceSet:
    output.dir(generatedResources, builtBy: 'generateMyResources')
    //it is now a part of the 'main' classpath and will be a part of the jar
  }
}

//a task that generates the resources:
task generateMyResources {
  doLast {
    def generated = new File(generatedResources, "myGeneratedResource.properties")
    generated.text = "message=Stay happy!"
  }
}

//Java plugin task 'classes' and 'testClasses' will automatically depend on relevant tasks registered with 'builtBy'

//Eclipse/IDEA plugins will automatically depend on 'generateMyResources'
//because the output dir was registered with 'builtBy' information
apply plugin: 'idea'; apply plugin: 'eclipse'
```

But this code generates the following error:

>Execution failed for task ':generateMyResources'.
> java.io.FileNotFoundException: C:\MyProject\build\generated-resources\main\myGeneratedResource.properties (The system cannot find the path specified)

It works though if we change it to:

```gradle
...
new File(generatedResources).mkdirs()
def generated = new File(generatedResources, "myGeneratedResource.properties")
...
```

**Comment by big-guy** [comment]
Thanks @feinstein - I've pushed a fix.

You can also fix this by adding `outputs.dir generatedResources` to generateMyResources configuration.
