### ISSUE TITLE
Add option to set baseDir in DistributionPlugin

### ISSUE THREAD

**Issue by Lesurglesum** [gradle/gradle#9801]
When you use the distribution plugin to easily assemble contents and create an archive you may have had the wish to change the 'layout' of the resulting archive especially the base directory. I want to have an option to place all contents of the distribution into the root directory of the archive.

### Expected Behavior 1.1

```groovy
[...]
distributions.main {
  archiveBaseDir = ''
  contents {
    from 'translations'
  }
}
```

with directories:

translations/aa
translations/zz

_gradle distZip_

Content of archive:
main-1.0.zip/aa
main-1.0.zip/zz

###  Expected Behavior 1.2

```groovy
[...]
distributions.main {
  archiveBaseDir = 'custom'
  contents {
    from 'translations'
  }
}
```

with directories:

translations/aa
translations/zz

_gradle distZip_

Content of archive:
main-1.0.zip/**custom**/aa
main-1.0.zip/**custom**/zz

### Current Behavior

_gradle distZip_

Content of archive:
main-1.0.zip/**main-1.0**/aa
main-1.0.zip/**main-1.0**/zz

### Context
Software which uses these archives need to handle the extra directory level making things (a little bit) more complicated than they should be.

**Comment by alllex** [comment]
Sorry for the delayed response.

This feature request is in the backlog of the relevant team and is prioritized by them.

***

Even if it is possible today, it's not clearly documented and more complicated than it needs to be.

Relevant documentation that can help with a workaround can be found here: https://docs.gradle.org/current/userguide/working_with_files.html#renaming_files
