### ISSUE TITLE
Use a different storage method for the Groovy incremental compilation source class mapping

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9804]
Currently, we use a plain text file for mapping Groovy sources to class files. For dependency management, that file around 400kb of size. We should find out what the performance impact of reading and writing that file on each compilation is and if it makes sense to use a faster/more compact storage method (e.g. using a `PersistentIndexedCache`).

**Comment by lptr** [comment]
I guess you need all the data every time, so an _indexed_ cache won't help much. Just zipping it might help, though, as the contents should be very well compressible.

**Comment by wolfs** [comment]
We don't need all the data every time. We only need the data for the changed source files and the indexed cache will be updated with the newly written data. Though you are probably right, and zipping may be enough. Let's look at the performance impact first, maybe we don't need to do anything.

**Comment by lptr** [comment]
This would be nice. We should probably do this when we make the incremental compilation data cacheable.
