### ISSUE TITLE
Make it easy for IntelliJ/AS users to recognize when multiple Gradle daemons are running

### ISSUE THREAD

**Issue by paplorinc** [gradle/gradle#9809]
Follow-up on https://github.com/gradle/gradle/issues/9781#issuecomment-506234623

When multiple daemons are handling the same build (e.g. Idea has a daemon with a wrapper and JDK8 and the command-line used an installed version of Gradle with JDK 8), they are invalidating each other's caches.

Consider the following:
* should we warn in a user friendly manner in this case (old daemons are killed on changes, right?)
* can these warnings be displayed properly in Idea?

**Comment by lptr** [comment]
A large portion of our users don't care (and shouldn't) about what daemons are: they just need a single one running. For them multiple daemons running is a problem that should be easy to detect, understand and fix. I think this is the use case we should focus on in this issue.

The users who knowingly want to run multiple daemons are fewer, and we can expect them to understand Gradle and Gradle daemons fairly well. For them the current "Gradle Daemons" view in IntelliJ and `gradle --status` should already be sufficient.
