### ISSUE TITLE
Build time reported for few-second builds can be misleading

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9811]
When reporting the build execution times larger than a second we round down to the smaller integer. For relatively long builds this is not a big problem, but for ones close to the 1 second mark it can be very misleading. For the most extreme case of 1.999 seconds we'd report:

```text
BUILD SUCCESSFUL in 1s
48 actionable tasks: 7 executed, 1 from cache, 40 up-to-date
```

That's almost 50% faster than what actually happened.

We could do a couple things about this:

- Use `Math.round()` to round upwards when the fraction is > 0.5, which still causes 1.5 seconds to be reported as 2 seconds, but that's only a 25% distortion, which is a lot better than 50%.
- Report milliseconds for quick builds under 5 seconds or so.

I think we should do both of the above.

**Comment by paplorinc** [comment]
I guess floor was used to put us in a better light: rounding up would make us look worse than what was actually measured.
Could we always display a few decimals instead, i.e.:
```
BUILD SUCCESSFUL in 1.9s
```
(this would already reduce the error to ~5% in this case)
