### ISSUE TITLE
project.delete and clean fails sometimes, but directory is deleted anyway

### ISSUE THREAD

**Issue by swpalmer** [gradle/gradle#9813]
This is on Windows 10.
I have a few Exec tasks that have to first delete the output directory as the command will fail if it pre-exists.
The project.delete call sometimes claims to fail, but when I check the directory it claimed it couldn't delete is gone.
Sometimes "gradle clean" fails as well, e.g.:

```
Execution failed for task ':clean'.
> Unable to delete directory 'C:\dev\ServerAdminApp\build'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\dev\ServerAdminApp\build\application
    - C:\dev\ServerAdminApp\build\classes
    - C:\dev\ServerAdminApp\build\generated
    - C:\dev\ServerAdminApp\build\image\app
    - C:\dev\ServerAdminApp\build\image\runtime
    - C:\dev\ServerAdminApp\build\image
    - C:\dev\ServerAdminApp\build\installer
    - C:\dev\ServerAdminApp\build\libs
    - C:\dev\ServerAdminApp\build\temp
```

After getting the above error I went to look in the C:\dev\ServerAdminApp\build folder and it was already gone.

### Expected Behavior
project.delete should delete the given directory 

### Current Behavior
project.delete deletes the given directory and then claims it failed to do so.

### Context
Simply re-running the build will work, or at least go further and fail on a different delete call.
Builds are unreliable as it is.

### Steps to Reproduce 
In my case I am running jpackage from the early-access build at https://jdk.java.net/jpackage/I need to do this twice. First creating an application image, and then creating one or more packages from the image. In my case just a .msi for now.
I'm passing the name of a temp folder with the jpackage --temp-root option, and also an output directory.  both of these directories are deleted with project.delete in a doFirst block of the Exec task.

### Your Environment
Windows 10
Java 8u202 - for building application (JAVA_HOME is set to this)
Java 14-ea-jpackage - for the jpackage tool only
Gradle 5.5-rc-4.

**Comment by big-guy** [comment]
Is this something that just started happening with 5.5-rc-4? Which version of Gradle were you using before?

**Comment by swpalmer** [comment]
I can reproduce it with 5.4.1 as well.  All I have to do is have explorer.exe browsed to the folder that gets deleted.  This does NOT prevent the folder from being deleted, I can see the folder disappear and my explorer window automatically go up a directory level.  Gradle still fails claiming the delete was unsuccessful.

**Comment by paplorinc** [comment]
Is it possible that another process deletes the file?

**Comment by swpalmer** [comment]
Not that I'm aware of.  Nothing else is interacting with stuff in the build folder.  It's just Gradle and explorer.exe, which is sitting idle while I run the build.

I just tried with Gradle 4.10.3 and could not reproduce the problem.

If I do a clean explorer will pop up a dialog saying the folder is unavailable, otherwise it will either automatically go up to the parent folder or do nothing and I see the timestamps on the files refresh as if it was deleted and replaced but explorer.exe didn't notice.  Either way, the folder IS deleted and Gradle 5.4+ complains that it couldn't delete it.  Gradle 4.10.3 seems to work.  (hasn't failed yet anyway)

**Comment by swpalmer** [comment]
This is happening with Gradle 6.0 as well.

> Task :MyProject:clean FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MyProject:clean'.
> java.io.IOException: Unable to delete file 'C:\dev\MyParentProject\MyProject\build'

Then I get a directory list of C:\dev\MyParentProject\MyProject  and sure enough the "build" folder is gone.  I have to run "gradle clean" over and over again as it fails on each folder, but the next run of course fails one folder later...

**Comment by swpalmer** [comment]
Note this doesn't just happen with explicit clean/delete. I also get this message: "Couldn't delete stale output file"
It is also a lie. Repeating the build always gets past that spot.

**Comment by PaulWinstone** [comment]
Im on Windows10 and Gradle 6.4.1 and get this - its not consistent.

**Comment by Agraphie** [comment]
I get this consistently when using Hotswap/dcevm. Any ideas?

**Comment by ab040572** [comment]
I am getting same issue " Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory"  with gradle clean task with 6.6 gradle version.

**Comment by gamma** [comment]
Still a problem in gradle version 8.4 in a multi project setup
