### ISSUE TITLE
args in one task affects other task

### ISSUE THREAD

**Issue by aviofans** [gradle/gradle#9814]
I have two tasks define in build.gradle like below:
```
task getA(type: JavaExec) {
    main = 'aa.A'
    classpath = sourceSets.main.runtimeClasspath
}

task getB(type: JavaExec) {
    main = 'bb.B'
    classpath = sourceSets.main.runtimeClasspath
    args str1
}
```
when I run below command, it will fail due to "**Could not get unknown property 'str1' for task ':getB' of type org.gradle.api.tasks.JavaExec**."
`./gradlew  getA`
If I run 
`./gradlew getA -Pstr1='a'`
it is successful. But I don't need pass argument for task A.

I am not sure if it is a bug or my configuration issue, please help.

**Comment by big-guy** [comment]
Both getA and getB are always configured fully in your example, even if you're only executing getA.

If you're passing parameters to getB, you may just want to use [gradle getB --args "str1"](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/JavaExec.html#setArgsString-java.lang.String-).

**Comment by aviofans** [comment]
Thanks @big-guy 
I am really new to gradle.
Actually I want that the configuration in task getB will not make any affect to taskA when I run task getA.
Do you have any suggestion on that How I should configure these tasks in build.gradle?
