### ISSUE TITLE
Tests without changes don't re-execute in IntelliJ with test delegation and the build cache both enabled

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9818]
@lptr commented on [Thu Jun 27 2019](https://github.com/gradle/gradle-private/issues/2407)

When using the *Gradle Test Runner* to execute tests, IntelliJ runs the following tasks:

```
18:18:28: Executing tasks ':core:cleanIntegTest :core:integTest --tests "org.gradle.api.tasks.CachedTaskIntegrationTest.cache entry contains expected contents"'...
```

When there are no changes, running `:clean*Test` prevents incremental build from marking `:*Test` task as `UP-TO-DATE`. This is the desired behavior from the user's perspective, too, as an engineer debugging a problem might want to run the same test multiple times without making changes in the code.

However, when the build cache is enabled, the results end up being loaded back up from cache, and the user is presented with a somewhat cryptic message saying: "Test events were not received".

There is no simple way for the engineer to re-trigger the execution of the test. They can issue the same build with `--rerun-tasks` perhaps, but that will re-execute everything, including even `:buildSrc`, which is suboptimal.

Another option is to make minute changes in the codebase, but doing so still results in unnecessary recompilation, and has the potential to introduce bugs or unnecessary changes in the code.

One way to address this problem would be to introduce some form of force-rerun functionality for the `Test` task and let IntelliJ use that. See https://github.com/gradle/gradle/issues/9166 for a discussion on this feature.

---

@wolfs commented on [Fri Jun 28 2019](https://github.com/gradle/gradle-private/issues/2407#issuecomment-506616992)

The Jetbrains team is aware of the issue: https://gradle.slack.com/archives/CDH5M7FAT/p1551777144060400

This is the corresponding IDEA issue: https://youtrack.jetbrains.com/issue/IDEA-208398

---

@wolfs commented on [Fri Jun 28 2019](https://github.com/gradle/gradle-private/issues/2407#issuecomment-506617278)

@lptr As a rule of thumb, can you open issues we have with IDEA support on the public `gradle/gradle` issue tracker? That makes it easier to communicate with Jetbrains.

**Comment by lptr** [comment]
@donat can you please link to the work you are doing on Tooling API to fix this?

**Comment by donat** [comment]
Done.

**Comment by pioterj** [comment]
This is addressed in the next release of IDEA: https://youtrack.jetbrains.com/issue/IDEA-208398.
