### ISSUE TITLE
Gradle 5.4.1 shows progress bar all the time

### ISSUE THREAD

**Issue by mborysenko** [gradle/gradle#9819]
We created some kind of installer with using gradle build management system. And it has interactive mode, means that it has steps that need user input. In gradle 5.4.1 we always see progress banner on top of the output which hides question and let say some default value user can use.
Example:
  ::  What version of the system is used?
  ::  Default value: '9'

Press <Enter> to choose default value or type 'halt' to stop
Value should be one of [8, 9](THIS PART HIDES BEHIND THE BANNER)
<=------------> 14% EXECUTING [20m 15s]
> :requestParameters

### Expected Behavior
While using --quiet or -q the banner should gone
Way to manage it through some custom loggers for example

### Current Behavior
gradle --quiet or -q parameter has no effect on that banner
also custom logger does not have any way to disable or customize it

### Steps to Reproduce 
Create some task which uses user code that reads user input
Define some custom logger
Run gradle with -q or --quiet flag and try to answer
You will see progress banner

### Your Environment
jdk 11.0.3
gradle 5.4.1

**Comment by mborysenko** [comment]
--console=plain removes that banner

**Comment by mborysenko** [comment]
Not the issue

**Comment by lacasseio** [comment]
The banner is only shown once per version ran on the system. What is missing from this issue is 1) the operating system used and 2) are you asking for user input during the build?

For #2, this is not possible with public APIs using the daemon. There will be artifacts.
