### ISSUE TITLE
Test out new issue template for build cache.

### ISSUE THREAD

**Issue by paplorinc** [gradle/gradle#9820]
Validation of https://github.com/gradle/gradle/pull/9815

---

Default bug labels:
<img width="1035" alt="Screen Shot 2019-06-28 at 16 01 42" src="https://user-images.githubusercontent.com/1841944/60344012-46130b80-99be-11e9-802a-8314462db93e.png">

---

Default feature labels:
<img width="1035" alt="Screen Shot 2019-06-28 at 16 01 57" src="https://user-images.githubusercontent.com/1841944/60344013-46130b80-99be-11e9-8255-37a4161a5c20.png">

---

Default regression labels:
<img width="1027" alt="Screen Shot 2019-06-28 at 16 02 10" src="https://user-images.githubusercontent.com/1841944/60344014-46130b80-99be-11e9-901d-61acd31cdecb.png">

---

Default build-cache issue labels, text and notification:
<img width="1017" alt="Screen Shot 2019-06-28 at 16 02 31" src="https://user-images.githubusercontent.com/1841944/60344015-46130b80-99be-11e9-9eea-08f62e7979b3.png">

---

New pull request contains `Fixes` command to connect PR with issue easily:
![PR](https://user-images.githubusercontent.com/1841944/60344822-195ff380-99c0-11e9-824a-4dafa5168309.gif)

---
cc: @gradle/build-cache

**Comment by paplorinc** [comment]
@lptr, @wolfs , does this seem correct to you?
Were you guys notified because of the `cc:`?
Could someone please add me to https://github.com/orgs/gradle/teams/build-cache/members ?

**Comment by lptr** [comment]
Looks good, though I got no notification. Which issues should I have received notification for?

I added you to the team (sorry this didn't happen before).

**Comment by paplorinc** [comment]
Lemme' see that myself: @gradle/build-cache
