### ISSUE TITLE
Gradle Fails to Properly Link jniLibs to APK on Macos

### ISSUE THREAD

**Issue by gblikas** [gradle/gradle#9826]
Gradle fails to link native android libraries under `/src/main/jniLibs/armeabi-v7a`, when they are manually copied into the gradle project. They are correctly packaged into the apk, however, the runtime fails to identify their existence. 

**Important Note:** If I copy the same gradle project to a windows machine, using the same gradle version, all works. 

### Expected Behavior

When executing `gradle assembleRelease`, and `gradle installRelease`, I should expect that any native libraries copied into `/src/main/jniLibs/*` should be linked in the final apk. 

### Current Behavior

Throws a `DllNotFoundException`, even though the `.so` and its dependencies correctly live inside the apk.

### Context

I am using Unity to export a gradle project, which I am them manually copying private android libraries to. The effects me because our developers who use macos cannot build for android on their machines, in this way. 

### Steps to Reproduce 

Because of privacy, I cannot share code. However, installing gradle 4.10.3 or gradle 5.4.X building an Unity project that uses native C++ binaries, then exporting the project and copy said binaries into the subsequent `/src/main/jniLibs/armeabi-v7a` should not run.

### Your Environment

* macos 10.13.6 
* Unity 2018.3.14f1
* gradle 4.10.3 or gradle 5.3.X
* andoird sdk with platform support 25, 26, 28

Build scan URL: na
build.gradle file: 
```
// GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
}
}

allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
}

apply plugin: 'com.android.application'


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(name: 'arcore_client', ext:'aar')
    implementation(name: 'arcore_unity', ext:'aar')
    implementation(name: 'google_ar_required', ext:'aar')
    implementation(name: 'unityandroidpermissions', ext:'aar')
    implementation(name: 'unitygar', ext:'aar')
}

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 28
        applicationId 'com.example.na'
        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }
        versionCode 1
        versionName '1.9.10'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb']
    }

    buildTypes {
        debug {
            minifyEnabled false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'
            jniDebuggable true
        }
        release {
            minifyEnabled false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'
            signingConfig signingConfigs.debug
        }
    }

    packagingOptions {
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/x86/*.so'
    }

    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}
```

**Comment by gblikas** [comment]
**update**: dragging in the gradle wrapper from windows (where the system works) does _not_ allow the runtime libraries to be found, either.

**Comment by gblikas** [comment]
This was an issue with a corrupt meta file. Apparently, you need to play native libraries, when packaged with arcore, in `/Assets/Plugins/Android`, instead of the relative pathing `Assets/some/where/else/Plugins/Android`. This caused the asset packaging to not correctly validate the `.so` files, even if they were manually dragged into the project.

**Comment by lacasseio** [comment]
It also seems to be an Android plugin issue. Please report those on the Android plugin issue tracker.

**Comment by gblikas** [comment]
@lacasseio Were you able to reproduce something?
