### ISSUE TITLE
Improve type hierarchy of `FileSystemSnapshot`

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9835]
![image.png](https://images.zenhubusercontent.com/570786abbf93871ccd991383/9528d977-dba7-480e-8517-8fbd29f15fcc)

This hierarchy doesn't make sense to me. Snapshots are not fingerprints, so `CurrentFileCollectionFingerprint` is-a `FileSystemSnapshot` shouldn't be true either.

The only thing `FileSystemSnapshot` does currently is it accepts a `FileSystemSnapshotVisitor`, so it could be renamed accordingly. Say, `FileSystemSnapshotVisitable`?

Another option would be to make `CurrentFileCollectionFingerprint` return a `FileSystemSnapshot` instead of being a `FileSystemSnapshot`.

**Comment by lptr** [comment]
Something we should consider to do soon.

**Comment by wolfs** [comment]
We did this already.
