### ISSUE TITLE
Remove deprecated java and scala 'language plugins' 

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#9838]
See #9837.

### Checklist
- [x] Validate whether we should remove the API in the 7.0 release
  - If the removal is not possible then create a follow-up issue and link it in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=493905624) 
- [x] Update the upgrade guide
- [x] Check User Manual for dangling references and outdated documentation
- [ ] Mark the story as done in the [overview spreadsheet](https://docs.google.com/spreadsheets/d/19J1nR_dFKpfKdu5KDFMVZGfjR0ysT9DthsBUPwf8mkM/edit#gid=2040581133).

**Comment by jjohannes** [comment]
#15717 removed 'scala-lang'

**Comment by bmuskalla** [comment]
Java, JUnit and JVM component plugins have been removed as part of https://github.com/gradle/gradle/pull/15800
