### ISSUE TITLE
Change default configuration behavior when using Groovy DSL task shortcuts

### ISSUE THREAD

**Issue by king-tyler** [gradle/gradle#9845]
The Groovy DSL provides convenient [shortcuts](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:shortcut_notations) for creating and configuring tasks:

```groovy
task hello { ... }
hello { ... }
task copy(type: Copy) { ... }
```

These shortcuts, however, eagerly create and configure the tasks. This may not be readily apparent to new users of Gradle and is mentioned as a [pitfall](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_pitfalls) in Gradle's user guide.

It would be useful to configure a project (such as a flag or feature preview in the `settings.gradle`) to change the default behavior so that tasks created and configured using Groovy DSL's task shortcuts are lazily configured:

```groovy
task hello { ... } // equivalent to tasks.register('hello') { ... }
hello { ... } // equivalent to tasks.named('hello').configure { ... }
task copy(type: Copy) { ... } // equivalent to tasks.register('copy', Copy) { ... }
```

**Comment by ljacomet** [comment]
Sorry for the late reply

Given the evolution of Gradle and the work on a declarative DSL, this is not something we plan on doing.

If you care about registering over creating, use the longer form.
