### ISSUE TITLE
ComponentMetadataRule breaks when a ComponentMetadataSupplier is present

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#9847]
Historically, we have used `ComponentMetadataRule` to set a custom `statusScheme` for each of our dependencies:

```

class StatusSchemaAttributeRule implements ComponentMetadataRule {
    public static final Attribute<String> STATUS_SCHEME = Attribute.of('org.my.internal.statusScheme', String)

    @Override
    void execute(ComponentMetadataContext componentMetadataContext) {
        ComponentMetadataDetails details = componentMetadataContext.details
        details.attributes {
            attribute STATUS_SCHEME, 'snapshot,candidate,release'
        }
    }
}
``` 

This way, each dependency will have an attribute with status scheme, example: `snapshot, candidate, release`.

Our current setup is to have virtual repositories that aggregate snapshots, candidates and final releases for java libraries. When pulling a dependency via`latest.release`. If the latest release in the `maven-metadata.xml` is a snapshot version, gradle iterates until it finds a version with status `release` (Download the POM file for each one of those). This is the “expected” behavior but not ideal.

We decided to introduce a `ComponentMetadataSupplier` which would set the status based on the version pattern, this way we would determine the version without downloading each POM.

This is an example of this:

```
class CustomMetadataSupplier implements ComponentMetadataSupplier {

    static final SNAPSHOT_VERSION = ~/(?i).+(-|\.)(ALPHA|SNAPSHOT|PR|DEV).*/
    static final CANDIDATE_VERSION = ~/(?i).+(-|\.)(BETA|CANDIDATE|CR|RC).*/

    @Override
    void execute(ComponentMetadataSupplierDetails details) {
        def id = details.getId()
        println id
        String status
        if (id.version =~ CANDIDATE_VERSION) {
            status = 'milestone'
        }
        else if (id.version =~ SNAPSHOT_VERSION) {
            status = 'integration'
        } else {
            status = 'release'
        }
        details.getResult().setStatus(status)
    }
}
``` 

This works with vanilla gradle and no plugins involved, we can see only retrieving `maven-metadata.xml` file and the POM file for the latest release, no more snapshots or candidates POM involved. However, when we combine this with our `ComponentMetadataRule`we get the following error:

```
 Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.slf4j:slf4j-api:latest.release.
     Required by:
         project :
      > There was an error while evaluating a component metadata rule for org.slf4j:slf4j-api:2.0.0-alpha0.
         > Could not find method attribute() for arguments [org.my.internal.statusScheme, snapshot,candidate,release] on object of type StatusSchemaAttributeRule.
``` 

After some investigation, it appears that `CustomMetadataSupplier` generates a `DefaultComponentMetadataProcessor.ShallowComponentMetadataAdapter` instance which is part of `ComponentMetadataContext.details`.

Because we don’t filter or discriminate `ComponentMetadataDetails` for setting the attribute, this fails since it appears attributes can’t be set for `DefaultComponentMetadataProcessor.ShallowComponentMetadataAdapter`

https://github.com/gradle/gradle/blob/b189979845c591d8c4a0032527383df0f6d679b2/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/DefaultComponentMetadataProcessor.java#L309

Our current workaround is to filter out instances of `ShallowComponentMetadataAdapter`, something like:

```

class StatusSchemaAttributeRule implements ComponentMetadataRule {
    public static final Attribute<String> STATUS_SCHEME = Attribute.of('org.my.internal.statusScheme', String)

    @Override
    void execute(ComponentMetadataContext componentMetadataContext) {
        ComponentMetadataDetails details = componentMetadataContext.details
        if (details.class.name.contains('ShallowComponentMetadataAdapter')) {
            return
        }
        details.attributes {
            attribute STATUS_SCHEME, details.statusScheme.join(',')
        }
    }
}
``` 

Also, we do this by applying `String.contains` because `ShallowComponentMetadataAdapter` is not part of the public API so we try to keep our code free of these kind of dependencies.

### Expected Behavior
We believe there are two potential outcomes of this:

* `ShallowComponentMetadataAdapter` could support setting attributes. However, `ComponentMetadataDetails` https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/api/artifacts/ComponentMetadataDetails.java is a public API which doesn't guarantee that any class implementing this interface will support the proper attributes configuration. Don't know if this is something that should be enforced in gradle... which leads us to second outcome:
* Provide a public API to determine if a `ComponentMetadataDetails` instance is capable of registering custom attributes, this way our "workaround" really becomes a expected filtering but without relying on class names from internal APIs

### Steps to Reproduce 
This `build.gradle` should be enough to reproduce when running `build` task.

```
plugins {
    id 'java-library'
}

repositories {
    maven {
        metadataSupplier = CustomMetadataSupplier.class
        url "https://repo.maven.apache.org/maven2/" //This usually would be an internal repository
    }
}

project.dependencies.components.all(StatusSchemaAttributeRule)

dependencies {
    implementation 'org.slf4j:slf4j-api:latest.release'
}

class CustomMetadataSupplier implements ComponentMetadataSupplier {

    static final SNAPSHOT_VERSION = ~/(?i).+(-|\.)(ALPHA|SNAPSHOT|PR|DEV).*/
    static final CANDIDATE_VERSION = ~/(?i).+(-|\.)(BETA|CANDIDATE|CR|RC).*/

    @Override
    void execute(ComponentMetadataSupplierDetails details) {
        def id = details.getId()
        println id
        String status
        if (id.version =~ CANDIDATE_VERSION) {
            status = 'milestone'
        }
        else if (id.version =~ SNAPSHOT_VERSION) {
            status = 'integration'
        } else {
            status = 'release'
        }
        details.getResult().setStatus(status)
    }
}


class StatusSchemaAttributeRule implements ComponentMetadataRule {
    public static final Attribute<String> STATUS_SCHEME = Attribute.of('org.my.internal.statusScheme', String)

    @Override
    void execute(ComponentMetadataContext componentMetadataContext) {
        ComponentMetadataDetails details = componentMetadataContext.details
        details.attributes {
            attribute STATUS_SCHEME, details.statusScheme.join(',')
        }
    }
}
```

cc @ljacomet @melix

**Comment by melix** [comment]
Thanks, after investigating your reproducer, it turns out the problem is not with `ShallowComponentMetadataAdapter`, but with the fact the rule is written in Groovy. Because it's a _class_ here, there's no runtime decoration of closure based actions, so when you write:

```
        details.attributes {
            attribute STATUS_SCHEME, details.statusScheme.join(',')
        }
```

the delegate of the closure is not automatically set to the attribute container like in a build script. Therefore, you must write:

```
        details.attributes {
            it.attribute STATUS_SCHEME, details.statusScheme.join(',')
        }
```

At this stage there's nothing much we can do about this. Note that if you wrote it in Kotlin you wouldn't have the problem either, vs in Java where you'd have a similar issue.

For Groovy, I would recommend to use `@CompileStatic` for your rules which would have 2 advantages:

1. this error would have been caught by the compiler
2. it would be faster at execution time

**Comment by rpalcolea** [comment]
Hi @melix 

Thanks for taking a look at this and for your quick response!

This makes complete sense, I wish I thought about it before bugging you.

Moved our rule static compilation in groovy (https://github.com/nebula-plugins/nebula-publishing-plugin/pull/137/files):

```
@CompileStatic
class StatusSchemaAttributeRule implements ComponentMetadataRule {
    @Override
    void execute(ComponentMetadataContext componentMetadataContext) {
        modifyAttributes(componentMetadataContext.details)
    }

    static void modifyAttributes(ComponentMetadataDetails details) {
        details.attributes {
            it.attribute(PublishVerificationPlugin.STATUS_SCHEME, details.statusScheme.join(','))
        }
    }
}
``` 

And this works as expected now without "workaround". 

While most of our plugins are written in Groovy, our new ones are a mix of Groovy and Kotlin or pure Kotlin.

We will evaluate moving this plugin in particular to Kotlin in the near future.

Thanks! Closing now
