### ISSUE TITLE
GradleWrapperMain loads system properties in wrong order

### ISSUE THREAD

**Issue by zyro23** [gradle/gradle#985]
`GradleWrapperMain` loads system properties in the reverse order than the docs suggest and as the "main" gradle process does.

### Expected Behavior
ill quote the docs:
> The configuration is applied in following order (if an option is configured in multiple locations the last one wins):
>    from gradle.properties in project build dir.
>    from gradle.properties in gradle user home.
>    from system properties, e.g. when -Dsome.property is set on the command line.

### Current Behavior
during the `gradlew` bootstrapping process, system properties (`systemProp.*`) defined in `gradle.properties` in the project dir override those defined in `gradle.properties` in the user home directory:

https://github.com/gradle/gradle/blob/v3.2.1/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleWrapperMain.java#L69

and those defined in the user home `gradle.properties` override command-line supplied system props (`-Dxyz`):

https://github.com/gradle/gradle/blob/v3.2.1/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleWrapperMain.java#L52

### Context
use-case:
* default http proxy defined in `<projectDir>/gradle.properties`
* you are using an override of the http proxy defined in `<userHome>/.gradle/gradle.properties`
* `wrapper.gradleVersion` is updated, wrapper is regenerated
* gradlew launch wants to download the updated gradle version
* timeout / unknown host

### Steps to Reproduce (for bugs)
n/a

### Your Environment
gradle-3.2.1 (but looking at the commit logs, this behavior seems to be existing for a _very_ long time?)

**Comment by ljacomet** [comment]
Updating this as it will end up being fixed, see the duplicate.
