### ISSUE TITLE
Jacoco Plugin does not generate xml report

### ISSUE THREAD

**Issue by josephbaylon** [gradle/gradle#9854]
Given a jacocoTestReport task, it does not generate xml report EVEN THOUGH it generates html reports correctly.

I have set this property for jacoco,

```
    reports {
        xml.enabled true
        xml.destination file("${rootProject.projectDir}/build/reports/jacoco/report.xml")
        html.enabled true
        csv.enabled false
    }
```

### Expected Behavior

XML report should be generated on this path

"${rootProject.projectDir}/build/reports/jacoco/report.xml"

### Current Behavior
XML report file is not being created at all

### Context
Sonar now requires xml paths for their jacoco coverage reports and will need to be able to generated xml reports from jacoco in order to integrate properly. We have Java and Kotlin so we require xml reports moving forward.

### Steps to Reproduce 
This is what jacoco.gradle looks like,

```
task jacocoRootReport(type: JacocoReport, group: 'Test Reporting') {
    description = 'Generates aggregate report from all subprojects.'

    def includeFilter = ['**/build/intermediates/javac/**/classes/**/*.class']
    def excludeFilter = ['**/build/intermediates/javac/*Test/**/*.class']
    def classTree = fileTree(dir: "${rootProject.projectDir}", includes: includeFilter, excludes: excludeFilter)
    def sourceTree = fileTree(dir: "${rootProject.projectDir}", includes: ['**/src/main/java/**/*.*'])
    def executionTree = fileTree(dir: "${rootProject.projectDir}", includes: ['**/build/jacoco/*.exec'])

    classDirectories.from = files([classTree])
    sourceDirectories.from = files([sourceTree])
    executionData.from = files([executionTree])

    reports {
        xml.enabled true
        xml.destination file("${rootProject.projectDir}/build/reports/jacoco/report.xml")
        html.enabled true
        csv.enabled false
    }
}

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
}
```

**Comment by TheJuli** [comment]
True. Its happening to me too. Html is there but no xml file. Gradle 5.4.1

**Comment by javisc** [comment]
Same issue. I am using Gradle 5.4.1

**Comment by TheJuli** [comment]
I have found a solution to this problem. What i did was during some other random work i stumbled upon the fact that if you put a test closure inside the subproject, all jacoco report settings will be applied.

Before i had only this report task, whereby not a single setting inside the report closure was used:
```
task coverageReport(type: JacocoReport) {
  getSourceDirectories().setFrom(project(":application").sourceSets.main.groovy.srcDirs)
  getClassDirectories().setFrom(project(":application").sourceSets.main.groovy.outputDir)
  reports {
    xml.enabled true
    html.enabled true
    xml.destination = file(getBuildDir().toString() + File.separator.toString() + "jacoco" + File.separator.toString() + "coverage.xml")
    csv.enabled false
    html.destination = file(getBuildDir().toString() + File.separator.toString() + "jacoco" + File.separator.toString() + "html")
  }
  getExecutionData().setFrom("$buildDir/jacoco/test.exec")
}
```

But if you do this (add a test{} closure before, if its missing), the report settings will be used:
```
test {
//Empty or something here, it does not matter
}

task coverageReport(type: JacocoReport) {
  getSourceDirectories().setFrom(project(":application").sourceSets.main.groovy.srcDirs)
  getClassDirectories().setFrom(project(":application").sourceSets.main.groovy.outputDir)
  reports {
    xml.enabled true
    html.enabled true
    xml.destination = file(getBuildDir().toString() + File.separator.toString() + "jacoco" + File.separator.toString() + "coverage.xml")
    csv.enabled false
    html.destination = file(getBuildDir().toString() + File.separator.toString() + "jacoco" + File.separator.toString() + "html")
  }
  getExecutionData().setFrom("$buildDir/jacoco/test.exec")
}
```

**Comment by pranayairan** [comment]
I have the same issue for android project. Interestingly this plugin is doing exactly the same thing but it works https://github.com/arturdm/jacoco-android-gradle-plugin. It generates the report in both HTML and XML. I am on Gradle 5.5

**Comment by pranayairan** [comment]
@big-guy I tried to revert back till gradle 5.1 and this issue still exist. Do you know if there is a fix for this? Jacoco report is generated but only html not xml when configuring via gradle file. However using this plugin which configure with groovy code it works and both xml and html reports gets generated https://github.com/arturdm/jacoco-android-gradle-plugin

**Comment by WesleyBrenno** [comment]
I had the same problem, after much searching, I realized that the execution data path had changed when updating the gradle version, corrected the execution data path and it worked. 

Before, the path to coverage.ec was: "build\outputs\code-coverage\connected", and now is: "build\outputs\code_coverage\debugAndroidTest\connected"

My code was: 

`task jacocoTestReport(type: JacocoReport) {
    group = "Reporting"
    description = "Generate Jacoco coverage reports"
    reports {
        xml.enabled = true
        html.enabled = true
    }
    def fileFilter = ['**/R.class',
                      '**/R$*.class', '**/*$InjectAdapter.*',
                      '**/*$ModuleAdapter.*',
                      '**/Dao*.*',
                      '**/*$ViewInjector*.*',
                      '**/*$ViewBinder*.*',
                      '**/*MembersInjector*.*',
                      '**/BuildConfig.*',
                      '**/Manifest*.*',
                      '**/*$Lambda$*.',
                      '**/*Factory*.',
                      '**/*$Builder*',
                      '**/*$Parcelable*.*',
                      '**/*DaggerApplicationComponent*.*',
                      '**/api',
                      '**/android/**/*.*',
                      '**/me/**/*.*', '**/org/**/*.*', '**/org/**/*.*']

    def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes/br", excludes: fileFilter)
    def mainSrc = "${project.projectDir}/src/main/java/br"
    sourceDirectories = files([mainSrc])
    classDirectories = files([debugTree])
    executionData = fileTree(dir: project.projectDir, includes:
            ['**/**/*.exec', '**/**/*.ec'])
}`

and I change to: 

`task jacocoTestReport(type: JacocoReport) {
    group = "Reporting"
    description = "Generate Jacoco coverage reports"
    reports {
        xml.enabled = true
        html.enabled = true
    }
    def fileFilter = ['**/R.class',
                      '**/R$*.class', '**/*$InjectAdapter.*',
                      '**/*$ModuleAdapter.*',
                      '**/Dao*.*',
                      '**/*$ViewInjector*.*',
                      '**/*$ViewBinder*.*',
                      '**/*MembersInjector*.*',
                      '**/BuildConfig.*',
                      '**/Manifest*.*',
                      '**/*$Lambda$*.',
                      '**/*Factory*.',
                      '**/*$Builder*',
                      '**/*$Parcelable*.*',
                      '**/*DaggerApplicationComponent*.*',
                      '**/api',
                      '**/android/**/*.*',
                      '**/me/**/*.*', '**/org/**/*.*', '**/org/**/*.*']

    def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes/br", excludes: fileFilter)
    def mainSrc = "${project.projectDir}/src/main/java/br"
    sourceDirectories = files([mainSrc])
    classDirectories = files([debugTree])
    **executionData = fileTree(dir: project.projectDir, includes:
            ['**/**/*.exec', '**/**/*.ec'])**
}`

**Comment by WesleyBrenno** [comment]
I had the same issue, after much searching, I realized that after upgrading the gradle the executionData path and classDirectories were changed, after updating the paths in the jacocoTestReport task, the xml, html and csv were regenerated normally.

My original code: 

`task jacocoTestReport(type: JacocoReport) {
    group = "Reporting"
    description = "Generate Jacoco coverage reports"
    reports {
        xml.enabled = true
        html.enabled = true
        csv.enabled = true
    }
    def fileFilter = ['**/R.class',
                      '**/R$*.class', '**/*$InjectAdapter.*',
                      '**/*$ModuleAdapter.*',
                      '**/Dao*.*',
                      '**/*$ViewInjector*.*',
                      '**/*$ViewBinder*.*',
                      '**/*MembersInjector*.*',
                      '**/BuildConfig.*',
                      '**/Manifest*.*',
                      '**/*$Lambda$*.',
                      '**/*Factory*.',
                      '**/*$Builder*',
                      '**/*$Parcelable*.*',
                      '**/*DaggerApplicationComponent*.*',
                      '**/api',
                      '**/android/**/*.*',
                      '**/me/**/*.*', '**/org/**/*.*', '**/org/**/*.*']

    def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes/br", excludes: fileFilter)
    def mainSrc = "${project.projectDir}/src/main/java/br"
    sourceDirectories = files([mainSrc])
    classDirectories = files([debugTree])
    executionData = fileTree(dir: project.projectDir, includes:
            ['**/*.exec', '**/*.ec'])
}`

Updated to:

`task jacocoTestReport(type: JacocoReport) {
    group = "Reporting"
    description = "Generate Jacoco coverage reports"
    reports {
        xml.enabled = true
        html.enabled = true
        csv.enabled = true
    }
    def fileFilter = ['**/R.class',
                      '**/R$*.class', '**/*$InjectAdapter.*',
                      '**/*$ModuleAdapter.*',
                      '**/Dao*.*',
                      '**/*$ViewInjector*.*',
                      '**/*$ViewBinder*.*',
                      '**/*MembersInjector*.*',
                      '**/BuildConfig.*',
                      '**/Manifest*.*',
                      '**/*$Lambda$*.',
                      '**/*Factory*.',
                      '**/*$Builder*',
                      '**/*$Parcelable*.*',
                      '**/*DaggerApplicationComponent*.*',
                      '**/api',
                      '**/android/**/*.*',
                      '**/me/**/*.*', '**/org/**/*.*', '**/org/**/*.*']

    **def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/classes/br", excludes: fileFilter)**
    def mainSrc = "${project.projectDir}/src/main/java/br"
    sourceDirectories = files([mainSrc])
    classDirectories = files([debugTree])
    **executionData = fileTree(dir: project.projectDir, includes:
            ['**/**/*.exec', '**/**/*.ec'])**
}`

**Comment by alwa** [comment]
> I had the same issue, after much searching, I realized that after upgrading the gradle the executionData path and classDirectories were changed, after updating the paths in the jacocoTestReport task, the xml, html and csv were regenerated normally.
> 
> My original code:
> 
> `def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes/br", excludes: fileFilter) classDirectories = files([debugTree]) executionData = fileTree(dir: project.projectDir, includes: ['**/*.exec', '**/*.ec'])`
> 
> Updated to:
> `def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/classes/br", excludes:fileFilter) classDirectories = files([debugTree]) executionData = fileTree(dir: project.projectDir, includes: ['**/**/*.exec', '**/**/*.ec'])`

How does your full configuration look like for the jacoco test report task?
I merged your
s with the one provided in the original post by @josephbaylon but then I get "Error while creating report" with stacktrace leading up to:

```
Caused by: java.lang.IllegalStateException: Can't add different class with same name: my/company/module//BuildConfig
```

**Comment by WesleyBrenno** [comment]
> > I had the same issue, after much searching, I realized that after upgrading the gradle the executionData path and classDirectories were changed, after updating the paths in the jacocoTestReport task, the xml, html and csv were regenerated normally.
> > My original code:
> > `def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/compileDebugJavaWithJavac/classes/br", excludes: fileFilter) classDirectories = files([debugTree]) executionData = fileTree(dir: project.projectDir, includes: ['**/*.exec', '**/*.ec'])`
> > Updated to:
> > `def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/classes/br", excludes:fileFilter) classDirectories = files([debugTree]) executionData = fileTree(dir: project.projectDir, includes: ['**/**/*.exec', '**/**/*.ec'])`
> 
> @WesleyBrenno How does your full configuration look like for the jacoco test report task?
> I merged your snippet with the config provided in the original post by @josephbaylon but then I get "Error while creating report" with stacktrace leading up to:
> 
> ```
> Caused by: java.lang.IllegalStateException: Can't add different class with same name: my/company/module/BuildConfig
> ```

@alwa this is my full configuration for jacoco test report task: 

``` 
task jacocoTestReport(type: JacocoReport) {
    group = "Reporting"
    description = "Generate Jacoco coverage reports"
    reports {
        xml.enabled = true
        html.enabled = true
        csv.enabled = true
    }
    def fileFilter = ['**/R.class',
                      '**/R$*.class', '**/*$InjectAdapter.*',
                      '**/*$ModuleAdapter.*',
                      '**/Dao*.*',
                      '**/*$ViewInjector*.*',
                      '**/*$ViewBinder*.*',
                      '**/*MembersInjector*.*',
                      '**/BuildConfig.*',
                      '**/Manifest*.*',
                      '**/*$Lambda$*.',
                      '**/*Factory*.',
                      '**/*$Builder*',
                      '**/*$Parcelable*.*',
                      '**/*DaggerApplicationComponent*.*',
                      '**/api',
                      '**/android/**/*.*',
                      '**/me/**/*.*', '**/org/**/*.*', '**/org/**/*.*']

    def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/classes/br", excludes: fileFilter)
    def mainSrc = "${project.projectDir}/src/main/java/br"
    sourceDirectories = files([mainSrc])
    classDirectories = files([debugTree])
    executionData = fileTree(dir: project.projectDir, includes:
            ['**/**/*.exec', '**/**/*.ec'])
}
```

**Comment by dramados-ford** [comment]
I have the same issue but only for the sub modules. for the main module the xml report is generated too. Any specific jacoco tools version or any dependencies ?

**Comment by alwa** [comment]
@dramados-ford I've been able to get the coverage reports generated for submodules and it looks good (I tried with enabling HTML to check locally).
But when I analyze with SonarQube there is no coverage data reported.

My setup:

- SonarQube 8.1
- SonarQube Gradle Plugin 2.7.1

My config:

```
subprojects {

    sonarqube {

        properties {
            property "sonar.sources", "src/main"
            property "sonar.tests", "src/test"
            property "sonar.jacoco.coverage.reportPaths", "$buildDir/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"
            property "sonar.junit.reportsPaths", "$buildDir/test-results/"
            property "sonar.androidLint.reportPaths", "$buildDir/reports/lint-results-debug.xml"
        }

    }

    apply plugin: "jacoco"
    jacoco {
        toolVersion = "0.8.5"
    }

    task jacocoTestReport(type: JacocoReport) {
        group = "Reporting"
        description = "Generate Jacoco coverage reports"
        reports {
            xml.enabled = true
            html.enabled = false
            csv.enabled = false
        }
        def fileFilter = ['**/BuildConfig.class', 'src/main/gen/**/*', 'src/main/assets/**/*',]

        def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/classes", excludes: fileFilter)
        def mainSrc = "${project.projectDir}/src/main"
        sourceDirectories = files([mainSrc])
        classDirectories = files([debugTree])
        executionData = fileTree(dir: project.projectDir, includes: ['**/**/*.exec', '**/**/*.ec'])
    }

    tasks.withType(Test) {
        jacoco.includeNoLocationClasses = true
    }
}
```

@WesleyBrenno Have you been able to get the code coverage data in SonarQube?

**Comment by alwa** [comment]
NOTE: This solution does not work for Gradle 6 where executionData is read-only it seems.
However, Gradle 6 is not compatible with the latest supported Android Gradle Plugin (at the time of writing 3.5.3): https://developer.android.com/studio/releases/gradle-plugin

**Comment by WesleyBrenno** [comment]
> @dramados-ford I've been able to get the coverage reports generated for submodules and it looks good (I tried with enabling HTML to check locally).
> But when I analyze with SonarQube there is no coverage data reported.
> 
> My setup:
> 
> * SonarQube 8.1
> * SonarQube Gradle Plugin 2.7.1
> 
> My config:
> 
> ```
> subprojects {
> 
>     sonarqube {
> 
>         properties {
>             property "sonar.sources", "src/main"
>             property "sonar.tests", "src/test"
>             property "sonar.jacoco.coverage.reportPaths", "$buildDir/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"
>             property "sonar.junit.reportsPaths", "$buildDir/test-results/"
>             property "sonar.androidLint.reportPaths", "$buildDir/reports/lint-results-debug.xml"
>         }
> 
>     }
> 
>     apply plugin: "jacoco"
>     jacoco {
>         toolVersion = "0.8.5"
>     }
> 
>     task jacocoTestReport(type: JacocoReport) {
>         group = "Reporting"
>         description = "Generate Jacoco coverage reports"
>         reports {
>             xml.enabled = true
>             html.enabled = false
>             csv.enabled = false
>         }
>         def fileFilter = ['**/BuildConfig.class', 'src/main/gen/**/*', 'src/main/assets/**/*',]
> 
>         def debugTree = fileTree(dir: "${buildDir}/intermediates/javac/debug/classes", excludes: fileFilter)
>         def mainSrc = "${project.projectDir}/src/main"
>         sourceDirectories = files([mainSrc])
>         classDirectories = files([debugTree])
>         executionData = fileTree(dir: project.projectDir, includes: ['**/**/*.exec', '**/**/*.ec'])
>     }
> 
>     tasks.withType(Test) {
>         jacoco.includeNoLocationClasses = true
>     }
> 
> }
> ```
> 
> @WesleyBrenno Have you been able to get the code coverage data in SonarQube?
> 
> **UPDATE**
> I saw that I had named the property incorrectly. It should be: sonar.coverage.jacoco.xmlReportPaths
> 
> It now works :-)

@alwa I don't use sonar plugin, I use sonar scanner, but the config is similar. In the properties file, I use the property "sonar.jacoco.reportPaths" , and pass the path to coverage.ec file instead the xml. 

`
sonar.jacoco.reportPaths=build/outputs/code_coverage/debugAndroidTest/connected/coverage.ec
`

**Comment by dramados-ford** [comment]
@alwa @WesleyBrenno Thanks Guys ! Its working now even for the modules !!

**Comment by bmuskalla** [comment]
Thanks everyone for helping each other out. We understand that there a different ways how to configure the `jacoco` report task and how to best collect code coverage information across multiple subprojects. For 6.4, we added a [jacoco sample](https://docs.gradle.org/6.4-rc-1/samples/sample_jvm_multi_project_with_code_coverage.html) showing the most practical way to setup the `jacoco` plugin for multi-module projects. It also includes generating the XML report.

Please let us know if there is something you're missing from the sample and if you have trouble applying this to your own build.

**Comment by alan-czajkowski** [comment]
does anybody have a solution for 2021?
all of these solutions do not work for Gradle 6.8.x or 7.0.x with JaCoCo 0.8.6

**Comment by chirag-ji** [comment]
Hi @alan-czajkowski ,

With `Gradle 7.2`. We can use the below configurations to use **jacoco** coverage

```
apply(plugin: "org.sonarqube")
apply(plugin: 'jacoco')

allprojects {
    apply(plugin: 'java')
    apply(plugin: 'org.springframework.boot')
    apply(plugin: 'io.spring.dependency-management')

   ...
}

subprojects {
    test {
        useJUnitPlatform()
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.enabled true
            html.enabled false
            csv.enabled false
            xml.destination file("${buildDir}/reports/jacoco.xml")
        }
    }
}

sonarqube {
    properties {
        property "sonar.java.coveragePlugin", "jacoco"
        property "sonar.coverage.jacoco.xmlReportPaths", "${buildDir}/reports/jacoco.xml"
    }
}

project(':<project-A>) {
    ...
}
```

run gradle with tasks:
`clean test sonarqube`


All the best. :)

**Comment by manuelortiz28** [comment]
In my project, my task is created as a Kotlin class. I realized that the `reports` configuration was totally ignored. And for resolving this I had to move the `reports` section into each subproject instead of being under the main project:

I had to change into this:
```
open class JacocoReportTask : JacocoReport() {
    fun configure() {
        executionData(
            project.fileTree(project.rootDir.absolutePath).include(
                "**/*.exec", // JaCoCo unit tests binary report
                "**/*.ec" // JaCoCo android tests binary report
            )
        )
        project.subprojects.forEach { subProject ->
            reports {
                xml.required.set(true)
                xml.outputLocation.set(File("${project.buildDir}/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"))
                html.outputLocation.set(File("${project.buildDir}/reports/coverage-unit"))
            }
           ...
       }
}
```

This is what I had before:
```
open class JacocoReportTask : JacocoReport() {
    fun configure() {
        executionData(
            project.fileTree(project.rootDir.absolutePath).include(
                "**/*.exec", // JaCoCo unit tests binary report
                "**/*.ec" // JaCoCo android tests binary report
            )
        )
        reports {
           xml.required.set(true)
           xml.outputLocation.set(File("${project.buildDir}/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"))
           html.outputLocation.set(File("${project.buildDir}/reports/coverage-unit"))
        }

        project.subprojects.forEach { subProject ->
           ...
       }
}
```

**Comment by Nireeksha17** [comment]
reports {
            xml.enabled.set(true)
            html.enabled.set(false)
            csv.enabled.set(false)
            xml.destination file("${buildDir}/reports/jacoco.xml")

still getting this error A problem occurred evaluating root project 'traffic-service'.
Could not get unknown property 'enabled' for Report xml of type org.gradle.api.reporting.internal.TaskGeneratedSingleFileReport.
