### ISSUE TITLE
Eclipse plugin "eclipse.classpath.sourceSets" allows modifying the project's sourceSets

### ISSUE THREAD

**Issue by nbruno** [gradle/gradle#986]
When using the eclipse plugin, it's possible to unintentionally modify the sourceSets of the entire project. Changes in the return value of `eclipse.classpath.sourceSets` are reflected in the project. I understand that the [API is documented](https://docs.gradle.org/current/javadoc/org/gradle/plugins/ide/eclipse/model/EclipseClasspath.html#getSourceSets()) to return `Iterable`, but it seems that contract isn't being enforced. Regardless, from `Iterable` I could also modify the backing collection via `Iterator#remove`.

### Expected Behavior
I would not expect modifications of any property of the EclipseClasspath object to affect the entire project. Any modifications to `eclipse.classpath.sourceSets` should only affect the eclipse classpath file generation.

### Current Behavior
Modifying the return of `eclipse.classpath.sourceSets` affects the entire project's sourceSets. The below build.gradle will output:

```
Before:
source set 'example'
source set 'main'
source set 'test'
After:
source set 'main'
source set 'test'
```

Note the missing sourceSet 'example' in the "After:" block.

### Context
I was attempting to remove a sourceSet that contains generated code from the IDE. 

### Steps to Reproduce (for bugs)
Run `./gradlew clean` with this build script.

```
apply plugin: 'eclipse'
apply plugin: 'java'

sourceSets {
    example
}

println "Before:"
sourceSets.each { println it } 

eclipse.classpath.sourceSets.removeAll { it.name == 'example' }

println "After:"
sourceSets.each { println it }
```

### Your Environment
Tested with the latest version of Gradle, 3.2.1.

**Comment by oehme** [comment]
Would you be interested in contributing a fix? The returned iterable should be an unmodifiable view as you suggested.
