### ISSUE TITLE
Transitive constraints are not published as Maven's <dependencyManagement>

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#9866]
### Expected Behavior

Setup: `project(':client')` depends on `project(':core')` which depends on `platform(project(':bom'))`
Gradle resolution works just fine

Expected: `pom.xml` for both `:core` and `:client` should have `dependencyManagement` that references `:bom` (or they should just have the constraints duplicated as a part of their own `<dependencyManagement>` section)

### Current Behavior

Gradle 5.5 fails to include `dependencyManagement` for `:client` project.
That is `:client` pom file is left without any versions at all.

### Context

I am trying to declare BOM project and I don't want to include it in every dependency.
Of course I can include the BOM as `implementation` again and again, however it would be better if Gradle could handle transitive case as well.

It looks like https://github.com/gradle/gradle/pull/8086 does not fully resolves `platform` dependency publication.

### Steps to Reproduce 

[transitive_constraints.zip](https://github.com/gradle/gradle/files/3355032/transitive_constraints.zip)

### Your Environment

Gradle 5.4, 5.5
Build scan URL: https://scans.gradle.com/s/yno6yhx2kptvi

**Comment by vlsi** [comment]
Just in case:

buildscript:

```groovy
project(':bom') {
  apply(plugin: 'java-platform')

  dependencies {
    constraints {
      api "org.slf4j:slf4j-api:1.7.25"
    }
  }

  publishing {
    publications {
      maven(MavenPublication) {
        from components.javaPlatform
      }
    }
  }
}

project(':core') {
  apply(plugin: 'java-library')

  dependencies {
    api platform(project(':bom'))
  }

  publishing {
    publications {
      maven(MavenPublication) {
        from components.java
      }
    }
  }
}

project(':client') {
  apply(plugin: 'java-library')

  dependencies {
    api project(':core')
    api("org.slf4j:slf4j-api")
  }

  publishing {
    publications {
      maven(MavenPublication) {
        from components.java
      }
    }
  }
}
```

`client:dependencies`:

```
api - API dependencies for source set 'main'. (n)
+--- project core (n)
\--- org.slf4j:slf4j-api (n)

compileClasspath - Compile classpath for source set 'main'.
+--- project :core
|    \--- project :bom
|         \--- org.slf4j:slf4j-api:1.7.25 (c)
\--- org.slf4j:slf4j-api -> 1.7.25

default - Configuration for default artifacts.
+--- project :core
|    \--- project :bom
|         \--- org.slf4j:slf4j-api:1.7.25 (c)
\--- org.slf4j:slf4j-api -> 1.7.25

runtimeClasspath - Runtime classpath of source set 'main'.
+--- project :core
|    \--- project :bom
|         \--- org.slf4j:slf4j-api:1.7.25 (c)
\--- org.slf4j:slf4j-api -> 1.7.25
```

So constraint works, yet it is not published in the `client` pom:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.github.vlsi.example</groupId>
  <artifactId>client</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.github.vlsi.example</groupId>
      <artifactId>core</artifactId>
      <version>1.0.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by vlsi** [comment]
Just one more comment: adding platform dependency as `implementation` to each project helps to workaround the issue:

```groovy
project(':core') {
  apply(plugin: 'java-library')

  dependencies {
    implementation platform(project(':bom'))
  }
  // ...
}

project(':client') {
  apply(plugin: 'java-library')

  dependencies {
    implementation platform(project(':bom')) // <-- need to duplicate it otherwise `pom.xml` misses version
    api project(':core')
    api("org.slf4j:slf4j-api")
  }
  // ...
}
```

**Comment by ljacomet** [comment]
What you are facing there is the limit of the Maven model and what Gradle allows to express.
The answer to this issue is to use Gradle Module Metadata instead of Maven Metadata as then the information will be properly transitive.

There is no plan to have Gradle behave differently with regards to Maven publication in this case.

**Comment by vlsi** [comment]
Oh,

Then I wish it fails with a reasonable error message rather than silently produce corrupted `pom.xml` files.

How about an ability to customize `<parent>` via `publications { create<MavenPublication>(project.name) { pom {     parent { group.set("...") ...` ?

In other words:
1) A flag to disable generation of "dependencyManagement scope=import" (it would still be helpful for `versionMapping fromResolutionResult` because, well, dependencymanagement makes little sense when all the versions are set

2) An ability to set parent pom via dsl, so one can specify it explicitly. Then dependencymanagement would be stored just once (in the BOM) and it would be Maven-inherited. I know there's `withXml`.

**Comment by ljacomet** [comment]
* About invalid pom files, Gradle now warns about some things that cannot be mapped. However, an empty version is not by itself an issue. Though we could add a warning when there are empty versions _and_ no `dependencyManagement` entries at all.

1. This has been requested in a different context. Note that, for Gradle at least, still having the platform in dependencies matters because it can say things about _transitives_ which do not appear in the published metadata.
2. There is currently no plan to add `dependency` / `dependencyManagement` high level APIs to manipulate Maven POMs.
