### ISSUE TITLE
Use feature preview for Groovy compilation avoidance

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9870]
We have a system in place to enable features which are not ready: feature previews. We should use it for Groovy compilation avoidance, since
- it makes it obvious from the build file if the feature has been enabled
- it is more obvious if the feature is enabled for buildSrc or not

If we do this, we should probably get rid of the incubating warning, since anybody who enables the feature in the `settings.gradle` already accepted the experimental nature of the feature and it is only useless nagging at that point.

**Comment by lptr** [comment]
Not sure if this is important, but keeping the incubation warning would make it easy to see in the console log of a build scan if the feature was enabled.

**Comment by wolfs** [comment]
We can keep the incubation warnings. I think it will be mostly noise. We could add some custom tags/values to our build scans to display whether it was enabled or not.
