### ISSUE TITLE
Disable incremental Groovy compilation when Java annotation processors are present

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9871]
We don't want to support incremental joint Java/Groovy compilation together with Java annotation processors. Let's deprecate using Java annotation processors together with incremental Groovy compilation and fail the build in Gradle 6.0 if you try doing this.

**Comment by albloptor** [comment]
Sorry for bringing this up now, @wolfs, but is there any way to achieve Groovy incremental compilation in test code when using annotation processors in production code written in Java? When I use Lombok in production code, it triggers a full Groovy compilation when changing any test source written in Groovy

**Comment by wolfs** [comment]
@albloptor I the Lombok annotation processor configured for the Groovy compilation as well? If it isn't (and it shouldn't be), then I think incremental Groovy compilation should work if you enabled it.

**Comment by albloptor** [comment]
@wolfs When you ask if the Lombok annotation processor is configured for the Groovy compilation as well, how can I ensure that this is not the case? I just use Lombok annotations in Java classes and the only thing I do is to define Lombok with implementation, testImplementation, annotationProcessor and testAnnotationProcessor in my build script.

**Comment by wolfs** [comment]
You can set `-proc:none` for the `GroovyCompile` tasks, this will disable annotation processing no matter what the annotation processor path is. So something like this should work:
```
tasks.withType(GroovyCompile).configureEach {
    options.compilerArgs.add("-proc:none")
}
```
