### ISSUE TITLE
:kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable fails when the daemon it's created by IDEA

### ISSUE THREAD

**Issue by CristianGM** [gradle/gradle#9885]
As spoken with @eskatos at slack:
I'm trying to build this project, but it fails if the daemon is created by IDEA ( even if you try to build later from cli as it reuses the daemon )
Killing the daemon, and building from cli works.

### Expected Behavior
the build should succeed

### Current Behavior
* What went wrong:
Execution failed for task ':kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable'.
> Could not copy zip entry /Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/libs/kotlin-compiler-embeddable-1.3.31-patched-for-gradle-5.6.jar!javaslang/λ.class to '/Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/classes/patched/javaslang/λ.class'.
   > Could not set file mode 644 on '/Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/classes/patched/javaslang/λ.class'.

### Context

MacBook-Pro-de-Cristian-2:gradle cristiangarcia$ ./gradlew --status
No Gradle daemons are running.
   PID STATUS   INFO
 80286 STOPPED  (stop command received)
 79522 STOPPED  (stop command received)
 81613 STOPPED  (stop command received)
 82009 STOPPED  (stop command received)
 82108 STOPPED  (stop command received)
 82252 STOPPED  (stop command received)
 82296 STOPPED  (stop command received)
 82645 STOPPED  (stop command received)

Only Daemons for the current Gradle version are displayed. See https://docs.gradle.org/5.6-20190627000039+0000/userguide/gradle_daemon.html#sec:status

sync from IntelliJ:
> Task :kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable FAILED

Execution failed for task ':kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable'.
> Could not copy zip entry /Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/libs/kotlin-compiler-embeddable-1.3.31-patched-for-gradle-5.6.jar!javaslang/λ.class to '/Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/classes/patched/javaslang/λ.class'.
   > Could not set file mode 644 on '/Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/classes/patched/javaslang/λ.class'.

MacBook-Pro-de-Cristian-2:gradle cristiangarcia$ ./gradlew --status
   PID STATUS   INFO
 82690 IDLE     5.6-20190627000039+0000
 80286 STOPPED  (stop command received)
 79522 STOPPED  (stop command received)
 81613 STOPPED  (stop command received)
 82009 STOPPED  (stop command received)
 82108 STOPPED  (stop command received)
 82252 STOPPED  (stop command received)
 82296 STOPPED  (stop command received)
 82645 STOPPED  (stop command received)

Only Daemons for the current Gradle version are displayed. See https://docs.gradle.org/5.6-20190627000039+0000/userguide/gradle_daemon.html#sec:status

ps aux | grep gradle
cristiangarcia   82690   0.0  2.5  9257776 840444   ??  Ss   11:33AM   2:52.46 /Users/cristiangarcia/Downloads/jdk-11.0.1+13/Contents/Home/bin/java -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -Xmx2500m -Dfile.encoding=UTF-8 -Duser.country=ES -Duser.language=es -Duser.variant -cp /Users/cristiangarcia/.gradle/wrapper/dists/gradle-5.6-20190627000039+0000-bin/70twalydsm77rh7glv8j608b6/gradle-5.6-20190627000039+0000/lib/gradle-launcher-5.6.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.6-20190627000039+0000

MacBook-Pro-de-Cristian-2:gradle cristiangarcia$ ./gradlew
> Task :kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable'.
> Could not copy zip entry /Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/libs/kotlin-compiler-embeddable-1.3.31-patched-for-gradle-5.6.jar!javaslang/λ.class to '/Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/classes/patched/javaslang/λ.class'.
   > Could not set file mode 644 on '/Users/cristiangarcia/IdeaProjects/gradle/subprojects/kotlin-compiler-embeddable/build/classes/patched/javaslang/λ.class'.

MacBook-Pro-de-Cristian-2:gradle cristiangarcia$ ./gradlew --status
   PID STATUS   INFO
 82690 IDLE     5.6-20190627000039+0000
 80286 STOPPED  (stop command received)
 79522 STOPPED  (stop command received)
 81613 STOPPED  (stop command received)
 82009 STOPPED  (stop command received)
 82108 STOPPED  (stop command received)
 82252 STOPPED  (stop command received)
 82296 STOPPED  (stop command received)
 82645 STOPPED  (stop command received)

### Steps to Reproduce 
clone the repo
sync using intellyJ IDEA making sure no daemon was running before
it will fail

### Your Environment
IntelliJ IDEA 2019.2 EAP (Community Edition)
Build #IC-192.5438.14, built on June 26, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 1126M
Cores: 12
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: Key Promoter X, org.jetbrains.kotlin, org.intellij.scala, org.jetbrains.plugins.hocon, training

$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="es_ES.UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

Build scan URL: https://scans.gradle.com/s/yyw5aahamhl2a

**Comment by rschmitt** [comment]
I hit the same error message when trying to build Gradle on FreeBSD. I suspect the problem has something to do with my locale settings.

**Comment by wolfs** [comment]
The task `:kotlinCompilerEmbeddable:unpackPatchedKotlinCompilerEmbeddable` has been [removed from the build](https://github.com/gradle/gradle/pull/13359), so I am closing this issue. If you think it is still valid, please re-open.
