### ISSUE TITLE
Gradley can only solve the problem of incremental compilation if the changed class has a constant?

### ISSUE THREAD

**Issue by love-learning-hjk** [gradle/gradle#9891]
Hello, I want to know if gradle will consider processing in the current version or in future versions. As long as the changed class has a constant, it will prohibit the incremental compilation. Or there is already a better way to deal with it, I hope someone can tell me thank you.

**Comment by big-guy** [comment]
Sorry, there's not much Gradle can do about this.  The Java compiler can/will inline constant values in other classes, which make it very hard to track dependencies between classes. 

The workaround is to avoid using constants and use static methods instead or limit constants to a smaller subset of your project.

**Comment by love-learning-hjk** [comment]
Thank you for your answer
