### ISSUE TITLE
secondary sourceset api dependency configuration not generated by java-library plugin 

### ISSUE THREAD

**Issue by restlesswind** [gradle/gradle#9900]
My gradle file looks like the following:

```
apply plugin: 'java-library'
sourceSets {
    p1 {
        java {
            srcDir 'src/main/java/com/test/p1'
            include '**/*.java'
        }
    }
}

task p1Jar(type: Jar, dependsOn: 'jar') {
    group = 'build'
    appendix = 'p1'
    includeEmptyDirs = false
    from sourceSets.p1.output
}

dependencies {
    p1Api group: 'junit', name: 'junit', version: '4.12'
}
build.dependsOn p1Jar
```

and I am getting the following the error when running gradle build:
> Could not find method p1Api() for argument

In the dependencies session, if I change p1Api to p1Compile or p1Implementation, everything is fine. It looks to me that the p1Api configuration is not generated by java-library plugin?

**Comment by ljacomet** [comment]
The `java-library` plugin only adds `api` to the `main` `SourceSet` not to other ones. The best example is the `test` `SourceSet` on which `api` would make no sense.

So if you need an `<SourceSetName>Api` configuration, you have to add it yourself ... and remember that it only provides benefits if a matching `<SourceSetName>ApiElements` is added and properly wired for consumption.

**Comment by restlesswind** [comment]
Thanks Louis, the junit dependency is not a good example, it was only used for demonstration. 

Here is a real life example: we have a secondary sourceset "spring" which we will use it to generate a secondary artifact "springJar" that will be consumed by Spring enabled application projects (and because there are only a couple extra files, we want to keep everything in one repo) . Hence, it would have extra dependencies (api/compile) on some Spring libraries which are not required by the primary artifact.  

With your explanation, it seems like it would be quite cumbersome to achieve this through configuring the springApi and springApiElements. Unlike the compile/runtime/implementation configurations that are wired automatically by the original Java plugin, this feels like a real setback to me and it will make it difficult for people to migrate to the java-library plugin... 

Is there any plan to add this feature? And do you have an example on how to properly configure and wire the <SourceSetName>ApiElements for now? 

Thanks again.

**Comment by melix** [comment]
@restlesswind what you need is precisely what [feature variants](https://docs.gradle.org/nightly/userguide/feature_variants.html) are designed for, and they would create an API/impl for you.

**Comment by restlesswind** [comment]
Thanks @melix, seems like "feature variants" is only available for Gradle 5. Is there any workaround for Gradle 4? Thanks again.

**Comment by melix** [comment]
You can setup the configurations by yourself (`implementation` extends `api`, ...). Any reason why you can't upgrade to Gradle 5 (6 is around the corner ;))

**Comment by ljacomet** [comment]
Closing as no changes in Gradle are planned for this.

**Comment by BrainStone** [comment]
Would it be too much to ask to provide an example on how to do that?
