### ISSUE TITLE
How to link dependencies through properties with filetree?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9918]
I'm trying to remove uses of `dependsOn` from my codebase, but I'm having trouble getting the task dependencies to link correctly.

Say I have an `internal abstract val resDir: DirectoryProperty`. The problem is, that directory is far too broad. So I now have to do this:
```kt
project.fileTree(resDir.file(PRODUCTS_PATH)).apply {
    include("*.json")
}
```

That loses the type information unfortunately, so the best solution I've come up with is to use `builtBy(resDir)`.

Here's the end result to get more context:
```kt
@get:Internal
internal abstract val resDir: DirectoryProperty

@get:SkipWhenEmpty
@get:PathSensitive(PathSensitivity.RELATIVE)
@get:InputDirectory
protected val productsDir by lazy {
    project.fileTree(resDir.file(PRODUCTS_PATH)).apply {
        builtBy(resDir)
        include("*.json")
    }
}
```

Is there some way to express a subset of a directory with the property syntax and not lose dependency information?

**Comment by adammurdoch** [comment]
Both `Directory` and `DirectoryProperty` have `getAsFileTree()` methods, which allow you to convert the directory (property) to a `FileTree`. So, you should be able to do something like:

```
resDir.map { it.dir(PRODUCTS_PATH).asFileTree.matching { include("*.json") } }
```

**Comment by SUPERCILEX** [comment]
That works, thanks!
