### ISSUE TITLE
Investigate regression in `up-to-date assemble on largeJavaMultiProject (parallel true)`

### ISSUE THREAD

**Issue by paplorinc** [gradle/gradle#9923]
The changes in https://github.com/gradle/gradle/pull/9743/commits seemingly made `up-to-date assemble on largeJavaMultiProject (parallel true)` slower: https://builds.gradle.org/repository/download/Gradle_Check_PerformanceTestCoordinator/24738599:id/report-performance-performance-tests.zip%21/report/tests/up-to-date-assemble-on-largeJavaMultiProject-%28parallel-true%29.html?redirectSupported=false#result27581529

For some reason, the both of the baseline and `master` got slower after your commit, with the baseline jumping back and forth.

The ad-hoc benchmarks don't seem to replicate this finding, though (see: https://github.com/gradle/gradle/commits/lorinc/investigate-9743-regression):
* inconclusive flames:
https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&branch_Gradle_Util_Performance=lorinc%2Finvestigate-9743-regression&tab=buildTypeStatusDiv
* 20/40 runs show `Speed Results for test project 'largeJavaMultiProject' with tasks assemble: Results were inconclusive with 51% confidence. Difference: 24.5 ms faster ` https://builds.gradle.org/viewLog.html?buildId=24750520&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
I looked at the latest execution graph of this test:
![image](https://user-images.githubusercontent.com/423186/61051166-c5560580-a3e8-11e9-814e-b00f472a897d.png)

It seems that the baseline has more elements in the lower part of the graph, while the current Gradle version has more elements in the upper half of the Graph. Since we are using the median of the values to display, the Graph can easily switch between the lower and the upper execution number.

Regarding the minimums and maximums, it seems to me that there is a small regression in the scenario - though it doesn't seem big enough to be concerned. I'll rebaseline the up-to-date performance tests for now and we need to look into those anyway when we make snapshotting faster.

**Comment by wolfs** [comment]
I rebaselined here: https://github.com/gradle/gradle/commit/5f39af82485db5a0b36270309259d12ecc7463d7

**Comment by wolfs** [comment]
I think that we need to make the up-to-date scenarios more stable before we use them to measure improvement in snapshotting...

**Comment by wolfs** [comment]
@paplorinc will try to see if the up and down is due to Garbage collection by printing out the GC times as he did in [a branch](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fgithub.com%2Fgradle%2Fgradle%2Fcommits%2Fcross-pollination%2Fgc-args) already.

**Comment by paplorinc** [comment]
Started an [ad-hoc benchmark](https://builds.gradle.org/viewLog.html?buildId=24820264&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&tab=artifacts&branch_Gradle_Util_Performance=cross-pollination%2Fgc-args#%2Fresults%2Fperformance%2Fbuild%2Ftest-results-performanceAdhocTest.zip) on it with GC logs enabled. Ordering it based on the starting time we can assign GC pause times for given runs (the gc log file was probably overwritten by the second run, since we didn't get any for the first run).
If we plot the original values against the normalized one (subtracting the gc pause time from run time), we will get the following plot:
<img width="970" src="https://user-images.githubusercontent.com/1841944/61120748-f5131500-a49d-11e9-8e89-a760bbdfa695.png">

While it's obvious that the GC time is not the only factor contributing to the instability, unsurprisingly it does seem to be more stable this way.

Comparing the two histograms it also seems that the normalized one has a central value, while the original one is all over the place:
<img width="431" src="https://user-images.githubusercontent.com/1841944/61121628-f5141480-a49f-11e9-8a1f-8378dd3a7349.png">

**Comment by paplorinc** [comment]
Forcing a GC before every run will create the following histogram (100 iterations):
<img width="1546" src="https://user-images.githubusercontent.com/1841944/61142446-0ffe7d00-a4d0-11e9-9701-7718926e3fca.png">

Running the same without forced GC (as it is now):
<img width="1538" alt="Screen Shot 2019-07-12 at 18 45 59" src="https://user-images.githubusercontent.com/1841944/61144578-8356bd80-a4d5-11e9-9316-dcf0b6950891.png">

The current one seems more spread out to me.
I'll run an experiment of the whole benchmarks suite with GC before every iteration, let's see how other benchmarks are affected.

**Comment by paplorinc** [comment]
Running the whole suite of benchmarks with running a GC before every iteration seems to stabilize builds, but doesn't seem to affect the sawtooth pattern.
Before:
<img width="1032" alt="Screen Shot 2019-07-14 at 10 01 08" src="https://user-images.githubusercontent.com/1841944/61180896-70033980-a61e-11e9-9dbf-1b21182238ca.png">
After:
<img width="1031" alt="Screen Shot 2019-07-14 at 10 02 20" src="https://user-images.githubusercontent.com/1841944/61180903-80b3af80-a61e-11e9-80c7-cdabc026947d.png">

**Comment by paplorinc** [comment]
Increasing the memory from 1.5g to 2g results in the following graph:
<img width="1025" alt="Screen Shot 2019-07-14 at 11 14 20" src="https://user-images.githubusercontent.com/1841944/61181561-98903100-a628-11e9-889f-3660526ad183.png">

**Comment by paplorinc** [comment]
Same with 3g memory + regular GC:
<img width="1027" alt="Screen Shot 2019-07-14 at 12 54 01" src="https://user-images.githubusercontent.com/1841944/61182638-81f0d680-a636-11e9-9862-cedcca7a5c7e.png">

**Comment by paplorinc** [comment]
3gb memory + daemon and client gc before every iteration:
<img width="1034" alt="Screen Shot 2019-07-16 at 9 10 59" src="https://user-images.githubusercontent.com/1841944/61273578-26dff080-a7aa-11e9-9f4d-32a41ef30339.png">

**Comment by paplorinc** [comment]
Moved related findings to https://github.com/gradle/gradle-private/issues/2466#issuecomment-511724620

**Comment by wolfs** [comment]
The investigation is done. Let's continue on gradle/gradle-private#2466
