### ISSUE TITLE
Upgrade gradle 4.2 to gradle 5.3 errors: unable to resolve class org.gradle.internal.operations.BuildOperationIdentifierRegistry

### ISSUE THREAD

**Issue by staedt** [gradle/gradle#9929]
Hi! 

I am updating from gradle 4.2 to gradle 5.3. When I build my project, I get an error.
`unable to resolve class org.gradle.internal.operations.BuildOperationIdentifierRegistry`

### Expected Behavior
gradle builds project successfully

### Current Behavior

```
SomeFile.groovy: 5: unable to resolve class org.gradle.internal.operations.BuildOperationIdentifierRegistry
 @ line 5, column 1.
   import org.gradle.internal.operations.BuildOperationIdentifierRegistry
   ^
```

### Context
works in gradle 4.2
errors in gradle 5.3

I am trying to upgrade from gradle 4.2 to gradle 5.3 and to build the project without errors.
Previously, a gradle employee added the following import:
`import org.gradle.internal.operations.BuildOperationIdentifierRegistry`
it is not included in the original gradle documentation, so it is a subproject of gradle, to enable code like this:
```
Serializable operationId = BuildOperationIdentifierRegistry.getCurrentOperationIdentifier()

workerExecutor.submit(LSFUnitOfWork.class) { config ->
    config.isolationMode = IsolationMode.NONE
    config.params(lsfCommand, env, bsubDir, operationId)
}
```

Now it seems obsolete. It seems that this is the new code:
https://github.com/gradle/gradle/tree/master/subprojects/base-services/src/main/java/org/gradle/internal/operations
Which parts of the new code should we use (and how exactly?), in order to achieve the same goal?
For example, I want to be able to use the WorkerAPI and something like the below:
```
 BuildOperationIdentifierRegistry.getCurrentOperationIdentifier()
 BuildOperationIdentifierRegistry.setCurrentOperationIdentifier(...)
```

### Steps to Reproduce 

try to use the below import and use function getCurrentOperationIdentifier in a groovy file with gradle 5.3 installed:
```
import org.gradle.internal.operations.BuildOperationIdentifierRegistry
Serializable operationId = BuildOperationIdentifierRegistry.getCurrentOperationIdentifier()
```

### Your Environment

Build scan URL:

**Comment by ghale** [comment]
Can you provide some more details of why getting/setting the identifier is necessary or how it's being used in `LSFUnitOfWork`?  I'm sure this was implemented to workaround some capability that was not available in the public api at the time.  It's possible this may not be necessary any more.  

(I suspect that I may have been the mentioned employee, but there's not enough context here to jog my memory)

**Comment by staedt** [comment]
within LSFUnitOfWork's run() function, the following use of operation Id:
```
BuildOperationIdentifierRegistry.setCurrentOperationIdentifier(operationId)
..
// so we can call the below
            ExecutorService executorService = Executors.newFixedThreadPool(2)
            executorService.submit(new OutputHandler(process.getInputStream(), System.out, operationId))
            executorService.submit(new OutputHandler(process.getErrorStream(), System.err, operationId))
```
