### ISSUE TITLE
 Receiving S3 input stream abort warnings when using an S3 maven repository

### ISSUE THREAD

**Issue by BrettDuclos** [gradle/gradle#9932]
### Expected Behavior
Executing a build with an S3 maven repository runs without warnings.

### Current Behavior
Executing a build with an S3 maven repository produces multiple instances of the following warning.

> WARNING: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.

### Context

We are using S3 as a maven repository for some of our libraries. When executing builds that rely on these dependencies, the above warning is being output multiple times.

After some investigation, I believe that this is an issue with the getMetaData method on S3ResourceConnector in conjunction with the getMetaData method on S3Client. The getMetaData method of S3Client returns an S3Object instead of just the metadata. It appears this is because of an issue with the GetObjectMetadataRequest as seen in the comment shown below. The S3ResourceConnector then gets the metadata and finally closes the S3Object. This warning is occurring because S3Object's content is never read before it is closed.

S3Client
```java
public S3Object getMetaData(URI uri) {
    LOGGER.debug("Attempting to get s3 meta-data: [{}]", uri.toString());
    //Would typically use GetObjectMetadataRequest but it does not work with v4 signatures
    return doGetS3Object(uri, true);
}
```

S3ResourceConnector
```java
public ExternalResourceMetaData getMetaData(URI location, boolean revalidate) {
    LOGGER.debug("Attempting to get resource metadata: {}", location);
    S3Object s3Object = s3Client.getMetaData(location);
    if (s3Object == null) {
        return null;
    }
    try {
        ObjectMetadata objectMetadata = s3Object.getObjectMetadata();
        return new DefaultExternalResourceMetaData(location,
            objectMetadata.getLastModified().getTime(),
            objectMetadata.getContentLength(),
            objectMetadata.getContentType(),
            objectMetadata.getETag(),
            null); // Passing null for sha1 - TODO - consider using the etag which is an MD5 hash of the file (when less than 5Gb)
    } finally {
        IoActions.closeQuietly(s3Object);
    }
}
```

I was able to confirm this with a simple test. This replicates the calls as they are above. When executed this will produce the warning. When explicitly calling abort on the object content prior to calling close, it does appear to stop this warning from occurring. Alternatively, reading through all of the bytes of the object also clears this warning. 

```java
public static void main(String[] args) throws Exception {
    GetObjectRequest gor = new GetObjectRequest("bucket", "key");
    S3Object s3Object = AmazonS3Client.builder().build().getObject(gor);
    ObjectMetadata objectMetadata = s3Object.getObjectMetadata();
    objectMetadata.getLastModified().getTime();
    objectMetadata.getContentLength();
    objectMetadata.getContentType();
    objectMetadata.getETag();
//        s3Object.getObjectContent().abort();

    s3Object.close();
}
```

**Comment by danielthegray** [comment]
I also see this a lot... really annoying!!

**Comment by InTheKeyOfCSharp** [comment]
Any update to this? We use S3 Maven for our internal plugins and dependencies at my company and would like to know if the fix prescribed here will be implemented in some way.

**Comment by TeodoroFilippini** [comment]
+1 on this. Our console output is polluted by tens of occurrences of this message.

**Comment by andrearezzonico** [comment]
Please solve this issue! We get a lot of these warnings and they make the whole console output very difficult to analyse.

**Comment by TeodoroFilippini** [comment]
Is anyone aware of a way to filter out these messages from the gradle output? I can't find a way to do so with custom loggers in Gradle.

**Comment by vlk32** [comment]
+1
