### ISSUE TITLE
Issue #8726 closed prematurely

### ISSUE THREAD

**Issue by brainchild0** [gradle/gradle#9949]
Issue #8726 was marked as a duplicate, with minimal commentary.

I subsequently posted detailed commentary, indicating that marking the issue as a duplicate may be premature.  The other issue describes a very different effect.  After four months, the issue remains closed, with no further discussion.

It is unclear that the contributor who closed the issue adequately understands why the described effect is in fact occurring or what effect should rather occur.  It is clear that the same contributor made no effort to explain the correct way to achieve the desired effect, if any is available, or to consider what changes should be made to the software, if no way is available to achieve the desired effect.

Plainly, confusion follows from ambiguity and uncertainty about expected behavior, based on documentation.  Attention should be given to the possibility that the current design is inadequate for all use cases, and that the issue should be marked as a design flaw. At minimum, an explanation for how to achieve the desired results should be attached to the issue report, and added to the documentation.

**Comment by brainchild0** [comment]
Issue should remain open until resolution is confirmed.

**Comment by jjohannes** [comment]
@brainchild0 I am very sorry that you did not get any more responses on #9949. Please accept my apologies on behalf of the team.

I added a comment on the issue which I hope helps: https://github.com/gradle/gradle/issues/8726#issuecomment-819464526

If I did misunderstood, the problem, please drop another comment there. Ideally with a small reproducer project showing what does not work for you. I can then follow up and also re-open #8726 if we end up identifying something actionable for the Gradle team.
