### ISSUE TITLE
ClosureBackedMethodInvocationDispatch doesn't set the Closure delegation property

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#996]
### Expected Behavior
According to the documentation for [`TaskExecutionGraph`](https://docs.gradle.org/current/javadoc/org/gradle/api/execution/TaskExecutionGraph.html), we can expect the delegate object for the `Closure` of [`whenReady(Closure)`](https://docs.gradle.org/current/javadoc/org/gradle/api/execution/TaskExecutionGraph.html#whenReady(groovy.lang.Closure)) be `TaskExecutionGraph` as [`whenReady(Action<TaskExecutionGraph>)`](https://docs.gradle.org/current/javadoc/org/gradle/api/execution/TaskExecutionGraph.html#whenReady(org.gradle.api.Action)) shows. The following code should pass:
```
gradle.taskGraph.whenReady {
    println hasTask("foo")
}
```

### Current Behavior
The code actually fails with:
```
* What went wrong:
Could not find method hasTask() for arguments [foo] on root project 'foo-project' of type org.gradle.api.Project.
```

### Context
It seems the closure invocation is handled by [`ClosureBackedMethodInvocationDispatch`](https://github.com/gradle/gradle/blob/2e95d72913471550ea04d7b1c6f3326b4590fd31/subprojects/core/src/main/java/org/gradle/execution/taskgraph/DefaultTaskGraphExecuter.java#L128-L130) and the [dispatching](https://github.com/gradle/gradle/blob/2e95d72913471550ea04d7b1c6f3326b4590fd31/subprojects/core/src/main/java/org/gradle/listener/ClosureBackedMethodInvocationDispatch.java#L34-L42) doesn't set the delegate properly.

### Steps to Reproduce (for bugs)
Use the code above and invoke gradle on any task.

**Comment by lacasseio** [comment]
There are three ways this could get fixed:
1. Replace all usage of `ClosureBackedMethodInvocationDispatch` that will clearly be called with only a single parameter with `ConfigureUtil.configureUsing(closure)` passing the result to the overloaded method taking an `Action`
2. Modify `ClosureBackedMethodInvocationDispatch.dispatch` to always use the first arguments, if any, as the delegate
3. Modify `ClosureBackedMethodInvocationDispatch.dispatch` to use the first arguments, if only one argument is available, as the delegate

**Comment by lacasseio** [comment]
Option 1 was implemented here https://github.com/gradle/gradle/commit/ba0cbf33a217c701de24d0fd2450a0159a283b46. I see it as the best option but requires a wider change list. Option 3 could be a good one. I think option 2 would result in unexpected behavior for the couple usage that passes more than 2 parameters to the closure.

**Comment by eriwen** [comment]
I don't think we can consider this actionable without a use case. Could you please provide one @lacasseio or close this?
