### ISSUE TITLE
Improve dependency handling for native platform

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#997]
### Expected Behavior
Dependency configuration for the native platform needs to be richer in order to handle the various possible use case. Dependency should be configurable for:

- compiler only (headers)
- compiler (headers) and linker (object files/static libraries)
- compiler (headers), linker (object files/static libraries), runtime (shared libraries/executables)
- linker only (object files/static libraries)
- linker (object files/static libraries) and runtime (shared libraries/executables)
- runtime only (shared libraries/executables))

The configuration should be defined as provided (unmanaged by Gradle), project (managed by Gradle) and remote (fetch from repositories). The later is outside of the scope of this epic.

### Current Behavior
Only _api_ (compiler only), _shared_ (compiler, linker, and runtime (not modeled)) and _static_ (compiler and linker) dependency are supported. Creative solutions need to take place in order to create other dependency levels such as [linker only](https://discuss.gradle.org/t/gradle-native-pass-to-linker-precompiled-objects/9900/2).

**Comment by lacasseio** [comment]
Native dependencies also need to be fully transformable in order to allow plugins / users to modify the `linkage` type after the dependencies have been added on the binary. One example is to change the `linkage` from `shared` to `static` depending on the `operatingSystem` property of the `NativeBinarySpec.getTargetPlatform()`.

**Comment by big-guy** [comment]
Issue moved to [gradle/gradle-native #497](https://github.com/gradle/gradle-native/issues/497) via [**ZenHub**](https://www.zenhub.com/)
