### ISSUE TITLE
Kotlin DSL in 5.5.1 considers array properties as non-reassignable vals

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#9970]
The Kotlin DSL in Gradle 5.5.1 considers Groovy array properties as non-reassignable vals, but considers non-array properties as reassignable vars.

I don't know if Java (or Kotlin, etc.) array properties also suffer from the same issue.

I assume that a similar issue does not occur for the Groovy DSL, as I ran into this problem when converting an existing third-party Groovy DSL build to the Kotlin DSL.  Given that binaries exist for the project, I assume they were able to build and therefore the array property was reassignable.

### Expected Behavior
The attached Gradle Wrapper 5.5.1 project should build without any errors.

### Current Behavior
    ./gradlew clean

Produces:

    Script compilation error:

      Line 9:     publications = arrayOf("mavenPublication")
                  ^ Val cannot be reassigned

    1 error

[array-as-val.zip](https://github.com/gradle/gradle/files/3397811/array-as-val.zip)

**Comment by rgoldberg** [comment]
Do you need any more info for this issue?

**Comment by bamboo** [comment]
Thanks for the report, @rgoldberg.

It seems this is caused by Groovy emitting array property setter with a `varargs` parameter. It is not clear to me yet whether this is a recent change to Groovy or Kotlin behaviour; @melix, do you know if this is a recent change to Groovy?

As a workaround it is possible to call the setter explicitly with multiple arguments, i.e., instead of writing:

```kotlin
groovyExtension {
  stringArrayProperty = arrayOf("foo", "bar")
}
```

use:

```kotlin
groovyExtension {
  setStringArrayProperty("foo", "bar")
}
```

**Comment by melix** [comment]
I'm not aware of any change like that in Groovy but I don't follow development closely.

**Comment by rgoldberg** [comment]
@bamboo: Thanks for the diagnosis & workaround.

I imagine that a `varargs` parameter shouldn't be considered a `val`, so I imagine that the issue is either in Gradle, Kotlin, or the Gradle Kotlin DSL.  Is that correct?  Or should the Groovy team possibly change how Groovy's behavior?

**Comment by abelkov** [comment]
Related Kotlin issue: https://youtrack.jetbrains.com/issue/KT-33879
