### ISSUE TITLE
Gradle 5.5.1 Not Generating JACOCO Report

### ISSUE THREAD

**Issue by nnanda2016** [gradle/gradle#9976]
### Expected Behavior
Jacoco HTML report

### Current Behavior
No report is generated

### Steps to Reproduce 
Sample app: https://github.com/nnanda2016/gradle-jacoco-issue.git
Run this app using `./gradlew clean build jacocoTestReport`

### Your Environment
JDK: openJDK 11.2
Gradle Version: 5.5.1

**Comment by EugenMayer** [comment]
Seems to be broken for gradle 6 too. I see the `.exec` files but no `report/jacoco` any reason why this is without any progress?

**Comment by bmuskalla** [comment]
Your jacoco report may run in parallel to your tests and thus miss the `.exec` files as they generated later. Please have a look at our [new sample](https://docs.gradle.org/6.4-rc-1/samples/sample_jvm_multi_project_with_code_coverage.html) how to properly configure jacoco reports (this works with older versions as well).
