### ISSUE TITLE
Allow declaring a dependency on a Scala library without explicitly appending the project's target Scala version

### ISSUE THREAD

**Issue by alexeyOnGitHub** [gradle/gradle#998]
SBT has "%%" syntax for Scala cross-build dependencies which lets the build system automatically select the right version of an artifact (myartifact_2.11   or myartifact_2.10). I wonder if there was a simple way to add some support for this into Gradle Scala plugin  so that you don't need to add "+'scala_version'" to many artifact names.

**Comment by EronWright** [comment]
There's two ways to interpret the scope of this issue.   
1. provide a syntax for declaring a dependency on a Scala library without explicitly appending the project's target Scala version.  i.e. `%%` syntax.
2. support cross-compilation of a Scala project to target numerous versions of Scala, i.e. 2.10/2.11/2.12.    

@alexeyOnGitHub would you mind amending the title (if 1) or description (if 2) to clarify?

**Comment by alexeyOnGitHub** [comment]
@EronWright thank you for taking your time to look into this. I agree, my initial description was somewhat ambiguous. I think supporting dependencies with various scala versions (e.g. mylib_2.10 vs. mylib_2.11, depending in Scala used 2.10 or 2.11) is a more useful feature than cross-compilation of libraries because the latter can be achieved with having couple separate commands in a Gradle script.

**Comment by sschuberth** [comment]
> [cross-compilation] can be achieved with having couple separate commands in a Gradle script.

Mind sharing such commands as I'm actually trying to convince Scala people to use `gradle` instead of `sbt`, but the lacking feature they regularly complain about is missing native cross-compilation support in the Scala plugin?

**Comment by EronWright** [comment]
@sschuberth I think the suggestion is to invoke the gradle command separately for each Scala version that you're targeting, setting a project property like `scalaVersion` each time.   You might be able to use the `GradleBuild` task to construct a master build script ([ref](https://docs.gradle.org/current/userguide/organizing_build_logic.html#sec:external_build)).

**Comment by sschuberth** [comment]
> invoke the gradle command separately for each Scala version

I fear that's already asking too much from `sbt` fans. Should I file cross-compilation support as a separate feature request?

**Comment by lkasso** [comment]
Sorry for the late reply.

This feature request is in the backlog of the relevant team and is prioritized by them.
