### ISSUE TITLE
How to suppress warning when using @Input for File

### ISSUE THREAD

**Issue by Xerus2000** [gradle/gradle#9984]
Currently, I have a custom task with a File annotated like this
`@Input lateinit var linkLocation: File`

I now get a warning:
```
Task property validation finished with warnings:
  - Warning: Type 'LinkJDK': property 'linkLocation' has @Input annotation used on property of type java.io.File.
```

I know why I get the warning, but I want to know how I can suppress it, because there is a reason that I am not using `@InputFile`

**Comment by paplorinc** [comment]
Could you maybe share the reason for not using `@InputFile`?

**Comment by Xerus2000** [comment]
Because the File is not an input. It is merely the location of a symbolic link being placed, so afaik only `@Input` makes sense.

**Comment by paplorinc** [comment]
Do I under it correctly that it's basically an [@Internal](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/Internal.html) property?

**Comment by lptr** [comment]
If only the file's location is your input, consider doing something like this:

```groovy
    @Internal File inputFile
    @Input String getInputFilePath() { inputFile.path }
```

**Comment by Xerus2000** [comment]
Thanks, solved it by adding an `@Internal` annotation. @lptr is there an upside to your way? Because I need a File object anyways in the task.

**Comment by lptr** [comment]
You still want to have an `@Input` for the path if you want to re-run your task when that path changes.

**Comment by Xerus2000** [comment]
Yes, I have now annotated the variable with `@Input @Internal`.

**Comment by lptr** [comment]
That won't work, `@Input` and `@Internal` serve cross purposes. We should probably show another warning about this if we don't already.

**Comment by Xerus2000** [comment]
No, there's no warning. Is there really no way to simply declare a File as Input without getting a warning?

**Comment by lptr** [comment]
For Gradle a `File` object as input represents a file's contents and location as a whole. This is what most use cases require. Yours is somewhat different, and unfortunately we have no out-of-the-box solution for it atm.
