### ISSUE TITLE
@OutputDirectory check fails if the directory contains invalid symbolic links

### ISSUE THREAD

**Issue by Xerus2000** [gradle/gradle#9985]
Currently, I have a custom task with an output directory annotated like this
`@OutputDirectory lateinit var linkLocation: File`

### Expected Behavior
The task scans the directory and reruns it if the content changes, ignoring invalid symbolic links.

### Current Behavior
Running this task fails, because the directory contains a symbolic link pointing to an invalid location:
```
Execution failed for task ':linkJdk'.
> Could not list contents of '/home/janek/daten/projects/player/app/java/src.zip'. Couldn't follow symbolic link.
```

**Comment by paplorinc** [comment]
Hey @Xerus2000, could you please try it with the latest nightly, this was fixed very recently.

**Comment by Xerus2000** [comment]
nice, works, thank you!
