### ISSUE TITLE
Artifact declaration API is not Provider-friendly

### ISSUE THREAD

**Issue by melix** [gradle/gradle#9988]
### Context

This is similar to #2630. Wiring a task so that an _output directory_ is added as an artifact of an outgoing configuration is cumbersome. We added the ability to use directories a while back for variant aware resolution in particular in the context of cross-project boundaries. For a customer I wrote a sample showing how to create a task to generate instrumented classes and consume them at runtime.

The task is a traditional task implemented like this:

```
open class InstrumentClasses : DefaultTask() {
    @get:InputFiles
    val classesDirs = project.objects.fileCollection().from(project.sourceSets.getByName("main").output.classesDirs)

    @get:OutputDirectory
    val outputDirectory = project.layout.buildDirectory.dir("instrumented-classes")

```

Note that it has a _single_ output directory and does _not_ extend from `AbstractArchiveTask`.

My first attempt was to use this task this way:

```
val instrumentedClasses by tasks.registering(InstrumentClasses::class)

artifacts {
    add("instrumentedClassesElements", instrumentedClasses)
}
```

However Gradle fails with:

> Cannot convert provided value (task ':lib:instrumentedClasses') to a file

So, I thought "ok I need to be explicit":

```
val instrumentedClasses by tasks.registering(InstrumentClasses::class)

artifacts {
    add("instrumentedClassesElements", instrumentedClasses.get())
}
```

which already has the drawback that it's going to realize the task eagerly. But it still fails:

```
Cannot convert the provided notation to an object of type ConfigurablePublishArtifact: task ':lib:instrumentedClasses'.
The following types/formats are supported:
  - Instances of ConfigurablePublishArtifact.
  - Instances of PublishArtifact.
  - Instances of AbstractArchiveTask, for example jar.
  - Instances of Provider<RegularFile>.
  - Instances of Provider<Directory>.
  - Instances of Provider<File>.
  - Instances of RegularFile.
  - Instances of Directory.
  - Instances of File.
  - Maps with 'file' key
```

Alright, so let's go with a `Provider<Directory>`:

```
val instrumentedClasses by tasks.registering(InstrumentClasses::class)

artifacts {
    add("instrumentedClassesElements", instrumentedClasses.get().outputDirectory)
}
```

But... it still fails, because now the _task dependency_ is not set correctly, so I have to do this:

```
val instrumentedClasses by tasks.registering(InstrumentClasses::class)

artifacts {
    add("instrumentedClassesElements", instrumentedClasses.get().outputDirectory) {
        builtBy(instrumentedClasses)
    }
}
```

Which is both cumbersome and error-prone, knowing that a task has a single output.

**Comment by stephanenicolas** [comment]
Yes, the artifacts API breaks Task Config Avoidance, and
*  it also breaks the [lazy declaration of configurations](https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectContainer.html#register-java.lang.String-)
* does it fully work with Lazy properties ? Does the API allow to use a [RegularFileProperty](https://docs.gradle.org/current/javadoc/org/gradle/api/file/RegularFileProperty.html) for instance and let the artifact container figure the task dependency automatically ?
* and why not make artifacts file-representation-free so that they can simply be used to link a lazy configuration to a lazy task or a lazy buildable property ? The artifact mechanism acts as the preferred gateway to link tasks across projects and I am not sure to understand why we need a file.
* it was not clear to me whether realizing a task in an artifact declaration would break TCA. Maybe the doc should make it clear.

**Comment by stephanenicolas** [comment]
Sorry for the long ramble above, though I keep it as some elements might be interesting to make gradle / its docs / apis better. 

But I just encountered the exact problem described in the PR using properties, task providers and trying to use them for artifacts. I totally +1 the issue !

**Comment by stephanenicolas** [comment]
I was actually able to do something like (in groovy):
```
artifacts {
    instrumentedClassesElements instrumentedClasses.map { it. outputDirectory }
}
```
And it looks like everything is working fine.

**Comment by stephanenicolas** [comment]
This worked for me:
```
project.artifacts.add("config", taskProvider.flatMap { it.outputFileProperty })
```

**Comment by natario1** [comment]
My issue with the solution above is that the task is not automatically executed when "config" is resolved, even though the docs say "When the provider represents an output of a particular task, that task will be executed if the artifact is required". 

Does anyone know how to workaround this? For context https://discuss.gradle.org/t/artifact-builder-task-not-invoked-when-resolving-configuration/36077

**Comment by melix** [comment]
Closing since Gradle 6.6 the artifact notation supports more notations, including tasks with a single output property: https://github.com/gradle/gradle/pull/13505
