### ISSUE TITLE
Dependency type to file extension mapping not configurable

### ISSUE THREAD

**Issue by fvogler** [gradle/gradle#999]
The following dependency is not resolvable with gradle.
group:'org.netbeans.cluster', name:'platform', version:'RELEASE82'
http://bits.netbeans.org/nexus/service/local/repositories/release82/content/org/netbeans/cluster/platform/RELEASE82/platform-RELEASE82.pom

### Expected Behavior
In the maven world it is possible to define dependency types with a different file extension as the type name. In this case type "nbm-file" should be resolved to "*.nbm"
(See e.g. http://stackoverflow.com/questions/1427722/how-do-i-create-a-new-packaging-type-for-maven)

### Current Behavior
The current implementation (as I can see so far) only supports *extension* = *type* or a static *type* to "*.jar" mapping.
See class *org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.GradlePomModuleDescriptorBuilder*
``` 
   private String determineExtension(String type) {
        return JarDependencyType.isJarExtension(type) ? "jar" : type;
    }
```
### Context
I try to create a netbeans platform application with gradle using the available netbeans module cluster definitions (see pom link above)

### Steps to Reproduce (for bugs)
Run the following build script:
```
configurations {
    myConfig
}
dependencies {
    myConfig group:'org.netbeans.cluster', name:'platform', version:'RELEASE82'
}
task build {
    doLast {
        configurations.'myConfig'.resolve().each {
            System.out.println("Resolved file ->" + it);
        }
    }
}
```
### Environment
Running gradle 3.2.1 on a mac using jdk1.8.0_112.

**Comment by bmuschko** [comment]
I was first thinking that you can solve your use with the help of [dependency resolve rules](https://docs.gradle.org/current/userguide/dependency_management.html#sec:dependency_resolve_rules). Unfortunately, you can only replace the attributes `group`, `name` and `version` of a dependency. The extension is currently not configurable.

Question from my end: It seems that the reason _why_ you are trying to remap the file extension is the fact that the metadata in the provided repository is wrong. Is that a correct observation?

**Comment by fvogler** [comment]
From a maven point of view, I think, the meta data is right. For special types like "ejb" or "test-jar" there exists already a static mapping in gradle. Why is mapping "ejb" -> "jar" fine? Why I can't map 'nbm-file' -> 'nbm"? (See  org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.GradlePomModuleDescriptorBuilder.JarDependencyType)
By the way, the meta data is not under my control.

**Comment by bmuschko** [comment]
I see what you are saying now. I believe we have the mapping because `ejb` and `test-jar` are common, special types. So far I haven't encountered `nbm-file`. It's probably just used for Netbeans-related artifacts.

Instead of tagging on to the list of special mappings I'd rather like to see a stronger concept exposed through the Gradle API. From my perspective hooking into the dependency resolve rules would make sense. We don't necessarily want to expose Maven-specific internals as Gradle's dependency management aims to abstract differences between supported repository types (e.g. Maven, Ivy etc.). Would you be interested in writing a [design doc](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md#larger-changes-features-or-enhancements) for this?

**Comment by jjohannes** [comment]
@fvogler in case you, or others, are still looking for a solution here. With Gradle 6, we embrace **component metadata rules** as the concept to add missing information to `pom` metadata. Which I think can be used here.

You can have a rule that adds the `npm` file to the metadata. Ideally, you would declare it as a separate _variant_.

Example: https://docs.gradle.org/release-nightly/userguide/component_metadata_rules.html#making_variants_published_as_classified_jars_explicit (this one is for artifacts with different classifiers, but different extensions work similar)

**Comment by ljacomet** [comment]
Closing as an alternate solution was offered.
