### ISSUE TITLE
Eclipse task should depend on pluginUnderTestMetadata if java-grade-plugin is applied

### ISSUE THREAD

**Issue by twwwt** [gradle/gradle#9996]
### Expected Behavior
Given a project that applies both the `eclipse` and `java-gradle-plugin`, the `eclipse` task will add an entry like the following to the `.classpath` file:

```xml
<classpathentry kind="lib" path="<projectHome>/build/pluginUnderTestMetadata">
	<attributes>
		<attribute name="gradle_used_by_scope" value="test"/>
		<attribute name="test" value="true"/>
	</attributes>
</classpathentry>
```

However, the folder `pluginUnderTestMetadata` (and the file(s) generated below) is created as an effect of executing the `pluginUnderTestMetadata` task. This means that the effects of running the `eclipse` task depend on the effects of the `pluginUnderTestMetadata` task (otherwise Eclipse will complain about the missing folder `pluginUnderTestMetadata`). In other words, there should be a dependency from the `eclipse` task onto the `pluginUnderTestMetadata` task, which should be defined *only if* the `java-gradle-plugin` finds the `eclipse` plugin on the same project.

### Current Behavior
The folder `<projectHome>/build/pluginUnderTestMetadata` is not created when executing `gradle[w] eclipse`. It will be created if executing, for instance, `gradle[w] build eclipse`, which is usually not done if one wants to generate Eclipse project descriptors only.

### Context
Should be clear from the description above.

### Steps to Reproduce 
Should be clear from the description above.

### Your Environment
Gradle 5.5.1, Oracle JDK 11.0.2, Mac OS X 10.14.5. Observerd also with earlier versions of Gradle.

**Comment by nicolas-albert** [comment]
Affected to, I do this workaround:
```
tasks['eclipse'].doLast {
	mkdir 'build/pluginUnderTestMetadata'
}
```

**Comment by KITSKevinPerry** [comment]
I agree the plugin should do this. I use:

`tasks['eclipse'].dependsOn 'pluginUnderTestMetadata'`
