### ISSUE TITLE
Flush file system caches before measuring a performance test baseline

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9998]
The state of the file system caches may have an effect on a performance run for a baseline. We can try out flushing the file system caches before running the iterations for a base line and see if this stabilizes some flaky tests.

// cc @gradle/build-cache

**Comment by oehme** [comment]
Note that we tried this before and it didn't help.

**Comment by lptr** [comment]
@oehme I didn't know about that. Can you point me to something about the results of that experiment?

**Comment by oehme** [comment]
I don't think I can dig the issue back up (if there was one), but this is something that Lari tried and it didn't reduce flakiness back then.

**Comment by lptr** [comment]
Got it. In that case it's probably worth testing this again.

**Comment by lptr** [comment]
We could use `sync` and also `drop_caches` – see https://www.tecmint.com/clear-ram-memory-cache-buffer-and-swap-space-on-linux/.

**Comment by paplorinc** [comment]
I see potential in these ideas, lemme investigate

**Comment by paplorinc** [comment]
@blindpirate, @donat, @wolfs, @lptr, how do I sudo on the agent? Do we need to add Jenkins to the suoers maybe?
I'm currently getting:
> java.lang.AssertionError: Failed executing 'swapoff --all --verbose'
	at org.gradle.performance.fixture.DurationMeasurementImpl.sudo(DurationMeasurementImpl.java:107)

for e.g. https://github.com/gradle/gradle/commit/c7fdb3a1725a180ddac394cb60a9f29cfbfb106a#diff-5b7346bd16d972b64eac0cd430fb96b3R80

**Comment by donat** [comment]
@paplorinc I think you should add sudo rights for the exact commands you need to execute from the agent. Please create a PR to our infra repo to the sudoers file.

**Comment by paplorinc** [comment]
Moving this issue to https://github.com/gradle/gradle-private/issues/2473
